### PR TITLE
Synchronize access to snapshot when copying via actor

### LINKED ISSUE #7856: Concurrently deleting and copying snapshot
**Describe the bug**

It seems that on closing the leader it can happen that we remove an existing snapshot, because we [took a new snapshot](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:32:03.772479000Z&dateRangeStart=2021-09-17T10:32:33.481Z&dateRangeEnd=2021-09-17T12:32:33.481Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-5%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:32:03.106437000Z&pinnedLogId=x308dsn6t5cuwtak&pinnedLogTimestamp=2021-09-17T11:32:03.066460Z) **and** [try to copy the old snapshot to the runtime ](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:32:03.772479000Z&dateRangeStart=2021-09-17T10:32:33.481Z&dateRangeEnd=2021-09-17T12:32:33.481Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-5%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:32:03.165166000Z&pinnedLogId=hrnvaryf4jpmasna&pinnedLogTimestamp=2021-09-17T11:32:03.076106Z)(because we want to build the state on follower) this concurrent modification cause later issues.

```
D 2021-09-17T11:32:03.039237Z zeebe-5 Broker-5-ZeebePartition-27 Closing Zeebe-Partition-27: StateController closed successfully  zeebe-5 Broker-5-ZeebePartition-27
D 2021-09-17T11:32:03.039317Z zeebe-5 Broker-5-ZeebePartition-27 Partition 27 closed all previous open resources, before transitioning.  zeebe-5 Broker-5-ZeebePartition-27
D 2021-09-17T11:32:03.039637Z zeebe-5 Broker-5-ZeebePartition-27 Available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/27/snapshots/6478-1-103275-19191, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/27/snapshots/6478-1-103275-19191.checksum, checksum=1842666976, metadata=FileBasedSnapshotMetadata{index=6478, term=1, processedPosition=103275, exporterPosition=19191}}  zeebe-5 Broker-5-ZeebePartition-27
I 2021-09-17T11:32:03.065290Z zeebe-5 Broker-5-SnapshotStore-27 Committed new snapshot 6478-1-125310-19191  zeebe-5 Broker-5-SnapshotStore-27
D 2021-09-17T11:32:03.066460Z zeebe-5 Broker-5-SnapshotStore-27 Deleting previous snapshot 6478-1-103275-19191  zeebe-5 Broker-5-SnapshotStore-27
E 2021-09-17T11:32:03.076106Z zeebe-5 Broker-5-ZeebePartition-27 Problem on copying snapshot to runtime.  zeebe-5 Broker-5-ZeebePartition-27
E 2021-09-17T11:32:03.077060Z zeebe-5 Broker-5-ZeebePartition-27 Problem on copying snapshot to runtime.  zeebe-5 Broker-5-ZeebePartition-27

```

Error groups:
 * https://console.cloud.google.com/errors/CN3_xYTu_-6tRw?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
 * https://console.cloud.google.com/errors/CNKKzPvtmd_-qQE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
 * https://console.cloud.google.com/errors/CLHSx-GYwc_tjgE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

Luckily we step down then: `Unexpected failure occurred in partition 27 (role LEADER, term 77), stepping down` and it should resolve afterwards.

**To Reproduce**

See above it is an concurrency issue.

**Expected behavior**

When closing no snapshot is taken in between.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Failed to recover from snapshots
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.recover(StateControllerImpl.java:114) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.ZeebeDbPartitionStep.open(ZeebeDbPartitionStep.java:24) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.installPartition(PartitionTransitionImpl.java:110) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.lambda$installPartition$2(PartitionTransitionImpl.java:119) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-alpha2.jar:1.2.0-alpha2]
Caused by: java.lang.IllegalStateException: Unexpected error occurred trying to open the database
	at io.camunda.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.createDb(ZeebeRocksDbFactory.java:81) ~[zeebe-db-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.createDb(ZeebeRocksDbFactory.java:38) ~[zeebe-db-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.openDb(StateControllerImpl.java:123) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.recover(StateControllerImpl.java:105) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	... 10 more
Caused by: org.rocksdb.RocksDBException: While opening a file for sequentially reading: /usr/local/zeebe/data/raft-partition/partitions/27/runtime/MANIFEST-000021: No such file or directory
	at org.rocksdb.OptimisticTransactionDB.open(Native Method) ~[rocksdbjni-6.22.1.1.jar:?]
	at org.rocksdb.OptimisticTransactionDB.open(OptimisticTransactionDB.java:40) ~[rocksdbjni-6.22.1.1.jar:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.openTransactionalDb(ZeebeTransactionDb.java:81) ~[zeebe-db-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.createDb(ZeebeRocksDbFactory.java:76) ~[zeebe-db-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.createDb(ZeebeRocksDbFactory.java:38) ~[zeebe-db-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.openDb(StateControllerImpl.java:123) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.recover(StateControllerImpl.java:105) ~[zeebe-broker-1.2.0-alpha2.jar:1.2.0-alpha2]
	... 10 more
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-alpha2
 - Configuration:

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Previously the copying snapshot to the runtime was done by ZeebePartition actor. While copying, snapshot store can concurrently delete a snapshot because a new snapshot was received.  In most cases, it will recover because a new transition will happen which reinstalls this step. But this can lead to temporary issues and error messages which are difficult to debug. 

In this PR we resolve this issue by ensuring that copying snapshot is also done by the snapshot store. By this all operations that access a snapshot must go through the SnapshotStore actor to avoid any concurrent issues.

## Related issues

closes #7856 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionStep.java [hunk 1]
```diff
@@ -54,4 +43,36 @@
   public String getName() {
     return "ZeebeDb";
   }
+
+  private void recoverDb(
+      final PartitionTransitionContext context, final CompletableActorFuture<Void> openFuture) {
+    final ActorFuture<Void> recoverFuture;
+    try {
+      recoverFuture = context.getStateController().recover();
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionStep.java:51]: :x: since it returns a future, personally I would expect it would complete the future exceptionally instead of throwing an exception

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionStep.java [hunk 2]
```diff
@@ -54,4 +43,36 @@
...
+    }
+
+    recoverFuture.onComplete(
+        (ok, error) -> {
+          if (error != null) {
+            openFuture.completeExceptionally(error);
+          } else {
+            try {
+              context.getStateController().verifyDb();
+              final var zeebeDb = context.getStateController().openDb();
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionStep.java:65]: :thought_balloon: question would be then whether verify is really necessary - since we open it here twice

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java [hunk 3]
```diff
@@ -47,28 +51,48 @@
...
+              final var zeebeDb = context.getStateController().openDb();
+              context.setZeebeDb(zeebeDb);
+              transitionFuture.complete(null);
+            } catch (final Exception e) {
+              Loggers.SYSTEM_LOGGER.error("Failed to recover from snapshot", e);
+
+              transitionFuture.completeExceptionally(
+                  new IllegalStateException(
+                      String.format(RECOVERY_FAILED_ERROR_MSG, context.getPartitionId()), e));
+            }
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java:94]: :x: why we have such duplicate code ?

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java [hunk 4]
```diff
@@ -281,7 +281,6 @@ public Path getPath() {
                 new FileNotFoundException());
           } else {
             try {
-              LOGGER.info("Copying {} to {}", snapshot.getPath(), targetDirectory);
```
Comment (Zelldon) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java]: Lets keep it at least for debugging purposes, so we now which snapshot it tried to recover what do you think?

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/PersistedSnapshotStore.java [hunk 5]
```diff
@@ -78,4 +78,14 @@
...
+
+  /**
+   * Copy snapshot to the given directory
+   *
+   * @param snapshot the snapshot to be copied
+   * @param targetDirectory the directory to which the snapshot files will be copied
+   * @return future which will be completed exceptionally if the snapshot was not copied
+   *     successfully
+   */
+  ActorFuture<Void> copySnapshot(PersistedSnapshot snapshot, Path targetDirectory);
```
Comment (Zelldon) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/PersistedSnapshotStore.java:90]: :thought_balloon: First I was a bit confused why this need to be on the public api :see_no_evil: But later I realized that this will be used for the case when we need to copy a snapshot to the runtime folder. Sorry seem to be too early for me :laughing: . Do you think it might make sense to have it on the Snapshot interface instead of the store? :thinking:

**Review by ChrisKujawa — COMMENTED** [review]
@deepthidevaki thanks for fixing it so quick :rocket: I have some smaller comments please take a look

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java [hunk 6]
```diff
@@ -266,6 +267,36 @@ public Path getPath() {
...
+          if (!Files.exists(snapshot.getPath())) {
+            result.completeExceptionally(
+                String.format(
+                    "Expected to copy snapshot %s to directory %s, but snapshot directory %s does not exits. Snapshot may have been deleted.",
+                    snapshot.getId(), targetDirectory, snapshot.getPath()),
+                new FileNotFoundException());
+          } else {
+            try {
+              LOGGER.info("Copying {} to {}", snapshot.getPath(), targetDirectory);
+              FileUtil.copySnapshot(targetDirectory, snapshot.getPath());
```
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java:284]: Ya. I thought so too. But I didn't want to change a lot of things with this PR, so kept it as it is. I will change it since you also found it weird :)

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionStep.java (hunk 2 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionStep.java:65]: `verify` checks if it can open the snapshot. It deletes the runtime if anything fails. I thought of moving it to `openDb`. But I did not want to add this error handling into `openDb`. Previously verification was with in recover. But now copy snapshot is asynchrnous, we cannot verify it within in `recover()`. That's why I split into verify. I am not sure if this is the best way to do it. What do you suggest?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java (hunk 3 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java:94]: Which code is duplicated?

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java (hunk 4 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java]: Available snapshot is logged in SnapshotController#recover, isn't that not enough? I think this is just a repeated message without adding any value.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/PersistedSnapshotStore.java (hunk 5 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/PersistedSnapshotStore.java:90]: I don't have a strong opinion here. Both makes sense to me. Would you rather prefer to have it in `PersisteSnapshot`?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionStep.java (hunk 2 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionStep.java:65]: IMHO we don't need the line 64. If the opening fails we thrown an exception, which is catched by the block and handled. The deletion is not necessary, since it is anyway not recoverable and will be deleted on the next recover call. :shrug:

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java (hunk 3 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java:94]: Same as in broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionStep.java

Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java:94]: Ah.. ok. `ZeebeDbPartitionStep` is the old transition code. I added the fix to that also in case we decided to turn the feature flag back due to the concurrent transitions bug. All classes named "*PartitionStep" is from the old transition and will be removed once we are confident with the new one.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java (hunk 4 above)
Comment (Zelldon) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java]: Aggreed

File: snapshot/src/test/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStoreTest.java [hunk 7]
```diff
@@ -136,6 +138,49 @@ public void shouldPurgePendingSnapshots() {
...
+    final var result = snapshotStore.copySnapshot(persistedSnapshot, target);
+
+    // then - should fail because targetDirectory already exists
+    assertThatThrownBy(result::join).isNotNull();
+  }
+
+  @Test
+  public void shouldCompleteWithExceptionWhenCopyingIfSnapshotDoesNotExists() throws IOException {
+    // given
+    final var persistedSnapshot = (FileBasedSnapshot) takeTransientSnapshot().persist().join();
```
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply snapshot/src/test/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStoreTest.java:173]: Without creating a snapshot we cannot get a "PersistedSnapshot" object which is needed for `copySnapshot`

[the remark this answers is not in the document]
Comment (Zelldon) [reply snapshot/src/test/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStoreTest.java:175]: hehe good point

**Comment by deepthidevaki** [comment]
@Zelldon I have applied your comments except moving `copySnapshot` to `PersistedSnapshot` interface.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java [hunk 8]
```diff
@@ -81,12 +81,11 @@ private void recoverDb(
             transitionFuture.completeExceptionally(error);
           } else {
             try {
-              context.getStateController().verifyDb();
               final var zeebeDb = context.getStateController().openDb();
               context.setZeebeDb(zeebeDb);
               transitionFuture.complete(null);
             } catch (final Exception e) {
-              Loggers.SYSTEM_LOGGER.error("Failed to recover from snapshot", e);
+              Loggers.SYSTEM_LOGGER.error("Failed to recover from snapshot.", e);
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java:82]: :thought_balloon: Do you think it makes sense to add the snapshot to the output? :)

**Review by ChrisKujawa — APPROVED** [review]
Looks great thanks @deepthidevaki

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java (hunk 8 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ZeebeDbPartitionTransitionStep.java:82]: We do not know the snapshot at this point.
