### PR TITLE
Reject instance migration with sequence flows mapped to same target

### LINKED ISSUE #39237: Reject Process Instance Migration with Duplicate Sequence Flow Mapping to The Same Target
### 

### 

### 

### 

### Description

When migrating process instances, it is currently possible to map multiple source sequence flows to the same target sequence flow. If this happens, the sequence flow appears as not taken in Operate, even though the instance can be completed. This leads to poor UX and confusion for users, as the process diagram does not accurately reflect the instance state.

See the attached screenshot, where two sequence flows from tasks join into the same gateway and sequence flow. The mapping of two source flows to the same target results in this visual bug.

Process migration sequence flow mapping bug

### Steps to reproduce

1. Create a process with parallel tasks joining into a gateway (as shown in the screenshot).
2. Migrate an instance, mapping two source sequence flows to the same target sequence flow flowing from Activity A to the joining gateway.
3. Observe that in Operate, the sequence flow is not shown as taken, but the process instance can still complete.

### Current behavior

The sequence flow is not shown as taken in Operate, even though the instance is completed. This misleads users about the process state.

### Expected behavior

During migration, process mapping should be validated and reject cases where multiple source sequence flows are mapped to the same target sequence flow. This ensures that the process diagram reflects the true state and prevents user confusion.

### Workaround

Avoid mapping multiple source sequence flows to the same target during migration. Manually check the mapping before confirming the migration.

### Environment

SaaS & SM

### Version

`8.8.0`

### Rootcause

_No response_

### Solution ideas

Implement validation during process instance migration to detect and reject duplicate target sequence flow mappings. Notify the user of the issue before migration is finalized.

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #39237

### CODE REVIEW

**Comment by berkaycanbc** [comment]
@georgios-goulos @tmetzke I've discovered a sequence flow migration behaviour that leads to an inconsistent behavior and affects UX. It is only a precondition change, so nothing changes in terms of sequence flow migration logic.

@marcosgvieira also assigned you if you are interested in learning a bit more about process instance migration.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java [hunk 1]
```diff
@@ -331,14 +331,18 @@ private void tryMigrateElementInstance(
             sourceElementIdToTargetElementId,
             elementInstance);
 
+    requireNonNullTargetSequenceFlowIds(
+        sequenceFlows, sourceElementIdToTargetElementId, processInstanceKey);
+    requireNoMultipleActiveSequenceFlowsMappedToSameTarget(
+        sequenceFlows, sourceElementIdToTargetElementId, processInstanceKey);
```
Comment (tmetzke) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java]: 💭 How about we keep those validations in the for-each below instead of iterating through the list multiple times? We can collect the source-to-target mappings in that loop and do a final validation of that mapping in a dedicated method (like the `requireNoMultipleActiveSequenceFlowsMappedToSameTarget` method in `ProcessInstanceMigrationPreconditions`).

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationPreconditions.java [hunk 2]
```diff
@@ -1141,6 +1142,73 @@ public static void requireSameMultiInstanceLoopCharacteristics(
...
+                    Expected to migrate process instance '%s' \
+                    but active sequence flows '%s' are mapped to the same target sequence flow '%s'. \
+                    Each active sequence flow must be mapped to a different sequence flow in the target process definition.""",
+                    processInstanceKey,
+                    sourceElementIds.stream().sorted().collect(Collectors.joining(", ")),
+                    targetElementId);
+            throw new ProcessInstanceMigrationPreconditionFailedException(
+                reason, RejectionType.INVALID_ARGUMENT);
+          }
+        });
```
Comment (tmetzke) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationPreconditions.java]: 💭 Could we collect the errors if there are multiple such "wrong" mappings? So, if I map "flow1" & "flow2" to "flow5" and "flow3" & "flow4" to "flow6", I can see both errors in my rejection instead of only one of them.

**Review by tmetzke — COMMENTED** [review]
👍 Changes look good to me in general on a technical level.
💭 I left some improvement ideas, let me know what you think.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java (hunk 1 above)
Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java]: This one would definitely be more efficient. However, instance migration validations is structured as being preventive before executing the logic. E.g. we validate everything before actually migrating the element instance. For that reason, I am choosing to keep the structure the same. 

@tmetzke Please let me know if the above also makes sense for you.

Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java]: Understood, but we didn't do that previously either, to be honest. The `getTargetSequenceFlowId` did the `requireNonNullTargetSequenceFlowId` check in between `deleteTakenSequenceFlow` and `takeNewSequenceFlow` in the `forEach`. Integrating the other checks in that same `forEach` would retain the same structure as before. You can even collect errors within that `forEach` and only throw an error when you're done with it (like you already do when throwing a `SafetyCheckFailedException` in line 353(old code)/357(new code)) 🤷

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationPreconditions.java (hunk 2 above)
Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationPreconditions.java]: Good idea, I've updated the message and adjusted tests. 👍

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java (hunk 1 above)
Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java]: Yes, that was the idea of refactoring it actually 😅. I realised while implementing this and refactored it. For the `SafetyCheckFailedException`s, they are single entities and validated if a condition is satisfied, so kind of different. Additionally, as now we added the support for collecting multiple validations, validating inside each sequence flow iteration will require collecting failed ones again. However, if you think having the validation inside each sequence flow processing is a blocker to merge this, I'll process it anyways :cool-cry-emoji: (we need fancy emoji support here 😅).

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationPreconditions.java (hunk 2 above)
Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationPreconditions.java]: Nice, I like the updated messaging 👍

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java (hunk 1 above)
Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java]: I see. But what is this about? Not executing migrations partially? Because, if I'm not mistaken, we still write migration events in the `forEach` already, but afterwards could throw a `SafetyCheckFailedException` outside the loop. This will rollback any follow-up events and such anyways, right? So if that's not it, what is it about? 🤔 

Overall, no, I don't think it's a blocker at all. It's just about the following:

1. Code clarity (all actions are done for each item once in the loop)
2. Error message consistency (all errors collected instead of being fed one after the other)
3. Potential performance gains (but they might be marginal)

Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java]: We've met with @tmetzke and decided to do the following:

* Check against null target while collecting sequence flows to migrate
* To validate sequence flows before writing the events, keep multiple active sequence flows mapped to same target validation as it is. Despite its redundancy to go over the sequence flow list again, we chose keeping the validation structure similar to other validations.

**Review by tmetzke — APPROVED** [review]
