### PR TITLE
Fix: Broker reestablishes streams on Gateway added to cluster

### LINKED ISSUE #14002: Streams are not re-registered if a broker detects a gateway as failed but not vice-versa
**Describe the bug**

Job streams reside purely in memory, on both the gateway and broker. This means job streams rely on the membership protocol to know when to re-open their streams. For example, if a broker is marked as dead, then comes back, a gateway will re-register its streams to it, assuming it was restarted (and not a false positive).

Similarly, when a broker detects a gateway as dead, it will remove its streams. This is done to avoid unnecessary job activation for streams with recipients that are potentially gone - if a gateway were to really restart, its connections to clients would have been severed, and when the clients would reopen the connections, it might be to a different gateway.

However, in the case of a false positive - a broker detects a gateway as gone, but it really wasn't - then the gateway never re-registers its streams to the broker, and the broker does not know of its streams, thus it will never forward jobs to it, creating clients that will end up starving.

**To Reproduce**

Here's a failing integration tests (to be added to `StreamIntegrationTest#LifecycleTest`):

```java
    @Test
    void shouldRegisterStreamsAgainInCaseOfAsymmetricPartition() {
      // given
      final var streamType = BufferUtil.wrapString("foo");
      final var properties = new TestSerializableData();
      final var streamId =
          clientStreamer
              .add(streamType, properties, p -> CompletableFuture.completedFuture(null))
              .join();
      awaitStreamAdded(streamType, streamId, server1, server2);

      // when - remove client from server's members, then add it back, and expect it to be
      // re-registered
      server1.streamService.event(
          new ClusterMembershipEvent(
              Type.MEMBER_REMOVED, client.cluster.getMembershipService().getLocalMember()));
      awaitStreamOnServer(streamType, server1, stream -> assertThat(stream).isEmpty());
      server1.streamService.event(
          new ClusterMembershipEvent(
              Type.MEMBER_ADDED, client.cluster.getMembershipService().getLocalMember()));

      // then
      awaitStreamAdded(streamType, streamId, server1, server2);
    }
```

**Expected behavior**

The gateway streams should be added back to the broker again, even if the failure was only visible from the broker's side.

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

The bug arises when the broker perceives that the gateway is removed from the cluster, but in reality, this was a false positive (the stream was only created when the gateway actually joined the cluster).
This in this pr is a naive solution that when the broker notices the node being added to the cluster, it sends a command to reset the streams.

## Related issues

closes https://github.com/camunda/zeebe/issues/14002

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by rodrigo-lourenco-lopes** [comment]
Benchmark: https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=rl-broker-reestablishes-streams&var-pod=All&var-partition=All&from=now-30m&to=now

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamServiceImpl.java [hunk 1]
```diff
@@ -28,14 +29,20 @@ public class RemoteStreamServiceImpl<M extends BufferReader, P extends BufferWri
...
+  private final RemoteStreamRestarter<P> remoteStreamRestarter;
+  private final ClusterMembershipService clusterMembershipService;
 
   public RemoteStreamServiceImpl(
       final RemoteStreamerImpl<M, P> streamer,
       final RemoteStreamEndpoint<M> apiServer,
-      final RemoteStreamRegistry<M> registry) {
+      final RemoteStreamRegistry<M> registry,
+      final RemoteStreamRestarter<P> remoteStreamRestarter,
+      final ClusterMembershipService clusterMembershipService) {
```
Comment (rodrigo-lourenco-lopes) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamServiceImpl.java:40]: @npepinpe I am not sure about passing the clusterMembershipService all the way down here, should we pass the member id instead? Or perhaps there is a more elegant way? wdyt?

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/messages/StreamTopics.java [hunk 2]
```diff
@@ -11,7 +11,8 @@ public enum StreamTopics {
   ADD("stream-add"),
   PUSH("stream-push"),
   REMOVE("stream-remove"),
-  REMOVE_ALL("stream-remove-all");
+  REMOVE_ALL("stream-remove-all"),
+  RESTART_STREAMS("restart-streams");
```
Comment (npepinpe) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/messages/StreamTopics.java:15]: :wrench: Let's keep the `stream-` prefix, so e.g. `stream-restart`. Although I would suggest `recreate` as a more accurate description, or `reregister` (but that's kind of a mouthful :sweat_smile:)

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamServiceImpl.java [hunk 3]
```diff
@@ -28,14 +28,17 @@ public class RemoteStreamServiceImpl<M extends BufferReader, P extends BufferWri
...
   public RemoteStreamServiceImpl(
       final RemoteStreamerImpl<M, P> streamer,
       final RemoteStreamEndpoint<M> apiServer,
-      final RemoteStreamRegistry<M> registry) {
+      final RemoteStreamRegistry<M> registry,
+      final RemoteStreamRestarter<P> remoteStreamRestarter) {
     this.streamer = streamer;
     this.apiServer = apiServer;
     this.registry = registry;
+    this.remoteStreamRestarter = remoteStreamRestarter;
```
Comment (npepinpe) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamServiceImpl.java:41]: :+1: I like the usage of a SRP class to encapsulate sending the request. It might be a little too narrow however. 

:x: I would propose instead that, since the `RemoteStreamEndpoint` already handles communicating over the transport, we rename it `RemoteStreamTransport` or `RemoteStreamCommunication`, and delegate sending the request to it.

This has some additional benefits:

- Centralize network communication of the remote stream
- Since the `RemoteStreamEndpoint` (or now the `RemoteStreamTransport`) is an actor itself, we can have the actor send the stream recreate request. This is good because the `event(ClusterMembershipEvent)` callback is called from the thread of the membership protocol (in this case, the SWIM membership protocol's thread), and we don't want to do more work there to avoid membership update congestion.

File: transport/src/test/java/io/camunda/zeebe/transport/stream/impl/StreamIntegrationTest.java [hunk 4]
```diff
@@ -59,7 +62,10 @@ final class StreamIntegrationTest {
           .setIoBoundActorThreadCount(1)
           .build();
   private final List<Node> clusterNodes =
-      List.of(createNode("server1"), createNode("server2"), createNode("client"));
+      List.of(
+          createNode(UUID.randomUUID().toString()),
+          createNode(UUID.randomUUID().toString()),
+          createNode(UUID.randomUUID().toString()));
```
Comment (npepinpe) [inline transport/src/test/java/io/camunda/zeebe/transport/stream/impl/StreamIntegrationTest.java:68]: :question: I don't understand why make them random? Does it have any impact?

**Review by npepinpe — CHANGES_REQUESTED** [review]

File: transport/src/test/java/io/camunda/zeebe/transport/stream/impl/StreamIntegrationTest.java (hunk 4 above)
Comment (rodrigo-lourenco-lopes) [reply transport/src/test/java/io/camunda/zeebe/transport/stream/impl/StreamIntegrationTest.java]: I changed it originally when I was sending the node ID in the header of the message to recreate streams (and couldn't be a string), but it is no longer needed since we now use the method that knows who sent the message.

**Review by npepinpe — CHANGES_REQUESTED** [review]
:+1: Almost there :slightly_smiling_face:

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamTransport.java [hunk 5]
```diff
@@ -15,16 +15,14 @@
...
 import java.time.Duration;
 import java.util.concurrent.CompletableFuture;
 import java.util.function.Function;
-import org.agrona.concurrent.UnsafeBuffer;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
 public final class RemoteStreamTransport<M extends BufferReader> extends Actor {
-  private static final byte[] EMPTY_RESPONSE = new byte[0];
+  private static final byte[] EMPTY_REQUEST = new byte[0];
```
Comment (npepinpe) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamTransport.java:25]: :wrench: I guess since we use it for both request and response, we can just name it `EMPTY_PAYLOAD` or something. It's a bit weird to return something called `EMPTY_REQUEST` as a response :smile:

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamTransport.java [hunk 6]
```diff
@@ -72,34 +70,34 @@ public void removeAll(final MemberId member) {
...
   }
 
   public void recreateStreams(final MemberId receiver) {
     try {
       sendRestartStreamsCommand(receiver);
-      LOG.trace("Tried to restart streams with member: {}", receiver);
+      LOG.debug("Tried to restart streams with member: {}", receiver);
     } catch (final Exception e) {
-      LOG.debug("Failed to restart streams with member: {}", receiver);
+      LOG.warn("Failed to restart streams with member: %s".formatted(receiver), e);
```
Comment (npepinpe) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamTransport.java:91]: :x: You can keep using the `{}` format. All SLF4J calls accept an error as the last argument - that's not formatted into the log message, and instead is added as context info.

So you can do:

```java
LOG.warn("Failed to restart streams with member: {}", receiver, e);
```

**Review by npepinpe — APPROVED** [review]
:+1: Please address the comments, but no need for another review

**Comment by rodrigo-lourenco-lopes** [comment]
bors merge
