### PR TITLE
fix: change type of session refresh lock attribute to string

### LINKED ISSUE #36932: “Whitelabel Error Page” when navigating to Operate or Tasklist
### 

### 

### 

### 

### Description

On SaaS 8.8 SNAPSHOT, navigating to Operate or Tasklist results in a “Whitelabel Error Page” instead of the expected application view.

### Steps to reproduce

1. Create a cluster using SNAPSHOT (e.g., `8.8 Cross Component Test Suite` from internal dev channel).
2. Navigate to Operate or Tasklist.
3. Observe that the page loads a `Whitelabel Error Page`

Image

 rather than the expected application view.

### Current behavior

`Whitelabel Error Page` is displayed when navigating to Tasklist and Operate.

### Expected behavior

Operate and Tasklist load successfully when navigating to those apps.

### Environment

SaaS

### Version

- Component Version: `Identity Snapshot`

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by maryarm**
## Description

Session persistence faced error after the lock attribute with object type is added to the session.

`org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.Object] to type [byte[]] for value [java.lang.Object@b9a60e4]`

## Related issues

close #36932

### CODE REVIEW

**Review by bmudric — APPROVED** [review]

File: authentication/src/test/java/io/camunda/authentication/session/WebSessionRepositoryTest.java [hunk 1]
```diff
@@ -99,6 +99,21 @@ void deleteById() {
     assertThat(webSessionRepository.findById(webSession.getId())).isNull();
   }
 
+  @Test
```
Comment (npepinpe) [inline authentication/src/test/java/io/camunda/authentication/session/WebSessionRepositoryTest.java:102]: 💭 FYI, we have a `RegressionTest` annotation, which I find helpful to explain the motivation behind some of the tests or decisions which might look not obvious (e.g. using a string vs object). Typical usage is 

```java
@RegressionTest("https://github.com/camunda/camunda/pull/36919")
void shouldBlaBla() {
  // ...
}
```

The link would be usually the issue link, or a PR link if there is no issue.
