### PR TITLE
Ensure snapshots can be committed after migration

### LINKED ISSUE #37046: [8.6][8.7] Investigate failing test ExporterDisableTest.exporterStaysDisabledAfterRestart
### 

### 

, 

### 

### 

### Description

[Slack discussion](https://camunda.slack.com/archives/C08MRKHJ0CD/p1755716456899509)
`ExporterDisableTest.exporterStaysDisabledAfterRestart` is frequently failing in stable/8.6 and stable/8.7 PRs and merge queues, there are also [flakiness](https://camunda.slack.com/archives/C071KP5BTHB/p1755756693781149) reported in `main`

### Steps to reproduce

In local, the test is consistently failing
https://github.com/camunda/camunda/actions/runs/17067732786/job/48388912890

### Current behavior

```
Error:  io.camunda.zeebe.it.exporter.ExporterDisableTest.exporterStaysDisabledAfterRestart -- Time elapsed: 198.6 s <<< ERROR!
java.util.concurrent.TimeoutException: exporterStaysDisabledAfterRestart() timed out after 120 seconds
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: org.awaitility.core.ConditionTimeoutException: Condition with alias 'until cluster topology is complete' didn't complete within 3 minutes because assertion condition defined as a Lambda expression in io.camunda.zeebe.qa.util.cluster.TestCluster 
Expecting all elements of:
  [TestStandaloneGateway{nodeId = gateway-0}]
to satisfy given requirements, but these elements did not:

TestStandaloneGateway{nodeId = gateway-0}
error: Expected all partitions to be healthy, but partition <2> of broker <1> is <UNHEALTHY>.
		at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
		at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
		at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
		at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
		at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)
		at io.camunda.zeebe.qa.util.cluster.TestCluster.awaitCompleteTopology(TestCluster.java:316)
		at io.camunda.zeebe.qa.util.cluster.TestCluster.awaitCompleteTopology(TestCluster.java:294)
		at io.camunda.zeebe.qa.util.cluster.TestCluster.awaitCompleteTopology(TestCluster.java:280)
		at io.camunda.zeebe.it.exporter.ExporterDisableTest.exporterStaysDisabledAfterRestart(ExporterDisableTest.java:114)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		... 5 more
	Caused by: java.lang.AssertionError: 
```

### Expected behavior

Test to pass

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

According to the job history, it seems that it started to fail since the merge of https://github.com/camunda/camunda/pull/36847, I reverted this PR in my local, and the test is now passing

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

`MigrationSnapshotDirector` did not become healthy because a snapshot was not taken. `AsyncSnapshotDirector` could not commit the snapshot because the commitPosition remained 0. This is because `RaftServer` only notifies of new commit if there are new application entries written after transitioning to leader. This was ok until now, because snapshots will be eventually taken when new entries are committed. But this prevents the force snapshot after migration if there are no new processing records.

The test was failing due to the partition not becoming healthy because it cannot commit the snapshot. However, it is not clear why migration is running again after restart.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #37046

### CODE REVIEW

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 1]
```diff
@@ -390,7 +391,7 @@ public void onCommit(final long committedPosition) {
   public void newPositionCommitted(final long currentCommitPosition) {
     actor.run(
         () -> {
-          commitPosition = currentCommitPosition;
+          commitPosition = Math.max(currentCommitPosition, commitPosition);
```
Comment (ChrisKujawa) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:394]: ❓ Just that I get this right: The idea is that the currentCommitPosition might be 0 because we are leader and haven't seen yet a new application entry right? But isnt then the commitPosition field anyway 0? Because we reinit/restarted the partition?

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java [hunk 2]
```diff
@@ -73,6 +74,18 @@ public ActorFuture<Void> transitionTo(
...
+                // Raft server will only notify if there is a new entry commited. If the node has
+                // just restarted or transitioned to leader, but there are no new processing records
+                // written or committed, the listener is not triggered. As a result the
+                // commitPosition in the snapshotDirector remain 0, thus preventing snapshots even
+                // if the state has changed after replaying previously committed events. Hence, set
+                // the commit position from the last record in the log stream.
+                try (final LogStreamReader logStreamReader =
+                    context.getLogStream().newLogStreamReader()) {
+                  final var commitPosition = logStreamReader.seekToEnd();
+                  director.onCommit(commitPosition);
```
Comment (ChrisKujawa) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java:87]: ❓ Do we need to read the log? Doesnt RAFT or the LogStream on open already? Can we get this from there?

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStepTest.java [hunk 3]
```diff
@@ -22,42 +22,55 @@
...
     transitionContext.setStreamProcessor(mock(StreamProcessor.class));
     transitionContext.setBrokerCfg(new BrokerCfg());
+    transitionContext.setLogStream(logStream);
 
     when(raftPartition.getServer()).thenReturn(raftServer);
     transitionContext.setRaftPartition(raftPartition);
 
-    when(actorSchedulingService.submitActor(any(), any()))
-        .thenReturn(TestActorFuture.completedFuture(null));
-    transitionContext.setActorSchedulingService(actorSchedulingService);
```
Comment (ChrisKujawa) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStepTest.java:56]: 🙃 How did this ever work? 🤔

**Review by ChrisKujawa — APPROVED** [review]
Makes in general sense to me. 

I'm wondering about `MigrationSnapshotDirector` why it doesnt directly force/commit the snapshot, instead of using the logic of the other async director where we wait for the commit. 

I mean the use cases are different right? I feel it might make sense to adjust this, and have a clear difference betweem them one is sync the other is async.

But I guess in both cases you need the commit position.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java (hunk 1 above)
Comment (deepthidevaki) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:394]: The entries written before this node becomes leader would have been committed. So the actual commit position can be > 0 if there was a leader already before this one.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java (hunk 2 above)
Comment (deepthidevaki) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java:87]: I don't think we keep the information about the last entry anywhere. So we have to seek to find the information.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStepTest.java (hunk 3 above)
Comment (deepthidevaki) [reply zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStepTest.java:56]: It was only verifying if the during transitions it is removing and installing the snapshot director as expected. So an actual actor was not necessary. Now to verify if commit position is updated, we have to have an actual actor that can run and update it.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStepTest.java [hunk 4]
```diff
@@ -89,6 +102,12 @@ void shouldReInstallSnapshotDirector(final Role currentRole, final Role targetRo
     assertThat(transitionContext.getSnapshotDirector())
         .isNotNull()
         .isNotEqualTo(existingSnapshotDirector);
+    if (Role.LEADER.equals(targetRole)) {
+      // verify that the last position is read to notify snapshot director
+      verify(logstreamReader, times(1)).seekToEnd();
+      assertThat(transitionContext.getSnapshotDirector().getCommitPosition())
+          .isEqualTo(LAST_LOG_POSITION);
+    }
```
Comment (ChrisKujawa) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStepTest.java:110]: ❓ Couldnt we also validate that this snapshot is now valid/confirmed/commited?

**Comment by deepthidevaki** [comment]
> I'm wondering about `MigrationSnapshotDirector` why it doesnt directly force/commit the snapshot, instead of using the logic of the other async director where we wait for the commit.

Even though it is forcing the snapshot, it has to still follow the same logic as in AsyncSnapshotDirector because there will be concurrent state changes from StreamProcessor replay or processing.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStepTest.java (hunk 4 above)
Comment (deepthidevaki) [reply zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStepTest.java:110]: This test is not taking the snapshot, it is only verifying that commit position is initialized after role transition.

**Comment by ChrisKujawa** [comment]
> > I'm wondering about `MigrationSnapshotDirector` why it doesnt directly force/commit the snapshot, instead of using the logic of the other async director where we wait for the commit.
> 
> Even though it is forcing the snapshot, it has to still follow the same logic as in AsyncSnapshotDirector because there will be concurrent state changes from StreamProcessor replay or processing. 

But migration starts before all of this, no?

**Comment by deepthidevaki** [comment]
> But migration starts before all of this, no?

Migration is done before the StreamProcessor starts. But the snapshot after migration is done async, as far as I can see from the `MigrationSnapshotDirector`. I assume it is done in parallel to StreamProcessor startup because in 8.6 and 8.7 we cannot take snapshot if there was no new records processed or replayed.
