### PR TITLE
Handle partially written segment descriptors

### LINKED ISSUE #6979: Broker crashes if there is an empty log segment
**Describe the bug**

[logs](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-05-04T14%3A09%3A56.909000000Z&project=camunda-cloud-240911&minLogLevel=0&customFacets&limitCustomFacetWidth=true&interval=JUMP_TO_TIME&scrollTimestamp=2021-05-04T09%3A42%3A12.919247000Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22de990736-75b6-4e2b-8b51-65b2ccd9174d-zeebe%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.container_name%3D%22zeebe%22%0Atimestamp%3D%222021-05-04T09%3A42%3A10.873656000Z%22%0AinsertId%3D%2295xz4qg4ckwrmf%22)

```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: newPosition > limit: (9 > 0)
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-1.0.0-alpha7.jar:1.0.0-alpha7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: newPosition > limit: (9 > 0)
	at java.nio.Buffer.createPositionException(Unknown Source) ~[?:?]
	at java.nio.Buffer.position(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.position(Unknown Source) ~[?:?]
	at java.nio.MappedByteBuffer.position(Unknown Source) ~[?:?]
	at io.zeebe.journal.file.MappedJournalSegmentWriter.reset(MappedJournalSegmentWriter.java:202) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.zeebe.journal.file.MappedJournalSegmentWriter.<init>(MappedJournalSegmentWriter.java:66) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.zeebe.journal.file.JournalSegment.createWriter(JournalSegment.java:151) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.zeebe.journal.file.JournalSegment.<init>(JournalSegment.java:62) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.zeebe.journal.file.SegmentedJournal.newSegment(SegmentedJournal.java:461) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.zeebe.journal.file.SegmentedJournal.loadSegment(SegmentedJournal.java:472) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.zeebe.journal.file.SegmentedJournal.loadSegments(SegmentedJournal.java:520) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.zeebe.journal.file.SegmentedJournal.open(SegmentedJournal.java:228) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.zeebe.journal.file.SegmentedJournal.<init>(SegmentedJournal.java:85) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.zeebe.journal.file.SegmentedJournalBuilder.build(SegmentedJournalBuilder.java:148) ~[zeebe-journal-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.storage.log.RaftLogBuilder.build(RaftLogBuilder.java:149) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.storage.RaftStorage.openLog(RaftStorage.java:233) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:155) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:257) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:231) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:175) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:145) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:103) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:113) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:201) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:203) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-1.0.0-alpha7.jar:1.0.0-alpha7]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-1.0.0-alpha7.jar:1.0.0-alpha7]
```
I inspected disk of the broker.  The segment that caused the problem had a file length of 0. So even the `JournalSegmentDescriptor` was not written to the file.
However what is more strange was that the file was "raft-partition-partition-5-0.log". The id of the segment is 0 which should never happen. The segment id's start from 1 always.

**Expected behavior**

* There should not be any segment with id 0.
* If it is the last segment, then it is most likely empty because the broker crashed before writing anything to the file. Hence it would be safe to ignore that segment and create a new one.

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

* Adds detection of corruption and partial writes when loading the segment/descriptors
* Handles partial writes by checking the metastore's last written index. If the segment doesn't contain acked entries, the subsequent segments are deleted and the journal is opened. If not then the corrupted is reported. 
* Adds adds additional checks that the descriptor is correctly read
* Test improvements (fixes code smells, improve log corrupter)

## Related issues

closes #6979

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: journal/src/main/java/io/camunda/zeebe/journal/file/JournalSegmentDescriptor.java [hunk 1]
```diff
@@ -52,32 +53,36 @@
...
 
     /* The first byte of the buffer contains the version at which the descriptor is written.
      Currently we have only one version, so we can ignore it. We can use this version in future
     when needed. Note that we can add fields to SBE schema of the descriptor without changing this version. */
-    messageHeaderDecoder.wrap(directBuffer, VERSION_LENGTH);
+    headerDecoder.wrap(directBuffer, VERSION_LENGTH);
+
+    if (headerDecoder.schemaId() != segmentDescriptorDecoder.sbeSchemaId()
+        || headerDecoder.templateId() != segmentDescriptorDecoder.sbeTemplateId()) {
+      throw new CorruptedLogException("Cannot read segment descriptor. Header does not match.");
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/JournalSegmentDescriptor.java:72]: Add more context to the error message such as expected schemaId,templateId and read schemaId and templateId.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java [hunk 2]
```diff
@@ -493,57 +496,110 @@ private FileChannel openChannel(final File file) {
...
+              String.format(
+                  "Log segment %s is not aligned with previous segment %s.",
+                  segments.get(i - 1), segment));
         }
 
-        final JournalSegmentDescriptor descriptor = new JournalSegmentDescriptor(buffer);
-
-        // Load the segment.
-        final JournalSegment segment = loadSegment(descriptor.id());
+        log.debug("Found segment: {} ({})", descriptor.id(), file.getName());
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:516]: May be we can move this log before reading the descriptor. This way if some thing fails when reading the segment, we know which segmented failed. Currently, both log messages - "Loaded segment" and "Found segment" are redundant and printed after the segment is successfully loaded.

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java [hunk 3]
```diff
@@ -361,6 +365,72 @@ void shouldUpdateIndexMappingsAfterRestart() {
         .isEqualTo(indexBeforeClose.lookup(secondIndexedPosition).position());
   }
 
+  @Test
```
Comment (deepthidevaki) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:368]: NIT: Since this class is becoming bigger, we can also move all corruption tests to a separate test class.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java [hunk 4]
```diff
@@ -546,6 +539,33 @@ private FileChannel openChannel(final File file) {
     return segments.values();
   }
 
+  private JournalSegmentDescriptor readDescriptor(final File file) {
+    final int descriptorLength = JournalSegmentDescriptor.getEncodingLength();
+    if (file.length() < descriptorLength) {
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:580]: Can this break backward compatability? Assume we added a new field to the segment descriptor and the broker is with the new version. Then `JournalSegmentDescriptor.getEncodingLength()` will include the new field. If it is reading a segment which was written with the old version, then it is possible that file.length = old descriptor length which is smaller, right?

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java [hunk 5]
```diff
@@ -361,6 +365,72 @@ void shouldUpdateIndexMappingsAfterRestart() {
...
+    assertThat(journal.getLastIndex()).isEqualTo(record.index());
+    assertThat(reader.next()).isEqualTo(record);
+    assertThat(reader.hasNext()).isFalse();
+  }
+
+  @Test
+  void shouldDetectCorruptionAtDescriptorWithAckedEntries() throws Exception {
+    // given
+    final var journal = openJournal(1);
+    final var record = JournalTest.copyRecord(journal.append(data));
```
Comment (deepthidevaki) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:414]:
```suggestion
    final var lastWrittenIndex = journal.append(data).index();
```

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java [hunk 6]
```diff
@@ -361,6 +365,72 @@ void shouldUpdateIndexMappingsAfterRestart() {
...
+
+    // then
+    assertThat(journal.getFirstIndex()).isEqualTo(record.index());
+    assertThat(journal.getLastIndex()).isEqualTo(record.index());
+    assertThat(reader.next()).isEqualTo(record);
+    assertThat(reader.hasNext()).isFalse();
+  }
+
+  @Test
+  void shouldHandleCorruptionAtDescriptorWithoutAckedEntries() throws Exception {
```
Comment (deepthidevaki) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:389]: It would be good to also test the case where there are more than one segment.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java [hunk 7]
```diff
@@ -493,57 +496,110 @@ private FileChannel openChannel(final File file) {
...
-        final ByteBuffer buffer = ByteBuffer.allocate(JournalSegmentDescriptor.getEncodingLength());
-        try (final FileChannel channel = openChannel(file)) {
-          channel.read(buffer);
-          buffer.flip();
-        } catch (final IOException e) {
-          throw new JournalException(e);
+        if (i > 0 && segments.get(i - 1).lastIndex() + 1 != segment.index()) {
+          throw new CorruptedLogException(
+              String.format(
+                  "Log segment %s is not aligned with previous segment %s.",
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:512]: Add more context to the error message - last segment's last index, current segment index.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java [hunk 8]
```diff
@@ -493,57 +496,110 @@ private FileChannel openChannel(final File file) {
...
+    log.debug(
+        "Found corrupted segment after last ack'ed index {}. Deleting it and subsequent segments",
+        lastWrittenIndex);
+
+    for (int i = failedIndex; i < files.size(); i++) {
+      final File file = files.get(i);
+      try {
+        Files.delete(file.toPath());
+      } catch (IOException e) {
+        log.warn("Failed to delete log segment {}", file.getName(), e);
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:553]: Would it create problem later if we are not able to delete the segment properly? What would happen when we have to create a new segment with the same id?

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java [hunk 9]
```diff
@@ -493,57 +496,110 @@ private FileChannel openChannel(final File file) {
...
+      lastSegmentIndex = previousSegment.lastIndex();
+    }
+
+    if (lastWrittenIndex > lastSegmentIndex) {
+      return false;
+    }
+
+    log.debug(
+        "Found corrupted segment after last ack'ed index {}. Deleting it and subsequent segments",
+        lastWrittenIndex);
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:546]:
```suggestion
    log.debug(
        "Found corrupted segment after last ack'ed index {}. Deleting segments {} - {}",
        lastWrittenIndex,
        files.get(failedIndex).getName(),
        files.get(files.size() - 1).getName());
```

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Looks good to me. Some minor comments and questions.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java (hunk 8 above)
Comment (MiguelPires) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:553]: AFAIK, mmap will open it and the journal will overwrite its contents. We can also just fail hard here to be safe. In the next restart there will be another attempt to delete it since it's the corrupted file or it's one after it and there will be a gap in the indexes

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java (hunk 4 above)
Comment (MiguelPires) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:580]: When we have multiple versions we'll use the magic byte to know which version we're dealing with and what format to expect. Currently there's only one possible value so it's fine. I expect that to change next week when I work on broadening the corruption detection in the descriptor

Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:591]: If we are only adding new fields to the SBE message, we don't have to change to the version number in magic byte.

Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:591]: What would happen if we don't check this condition here? Would we be able to detect that the descriptor is partial when reading the sbe message?

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java (hunk 8 above)
Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java]: It might be safe to fail hard, I think. Consider the following scenario:

Segment {id = 1, firstIndex = 1, lastIndex = 1}
Segment {id = 2, firstIndex = 2, lastIndex = 2} - corrupted
Segment {id = 3, firstIndex = 3, lastIndex = 3}

1. Deleted Segment-2
2. Failed to delete Segment-3. 
3. append record at index 2
4. restart broker
5. Load segments - segment 3 is loaded successfuly, no gap in indexes, but the record at index 3 is incorrect.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java (hunk 4 above)
Comment (MiguelPires) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:591]: We can add a minimum length (i.e., what it is now) method to the descriptor and check against that. We allocate a buffer using the encoding size since it might have more but we only assume it's corruption if the length is smaller than the minimum. If we change the format then that might decrease of course but if we keep the SBE format then it should be the same since we can't remove fields

**Review by deepthidevaki — APPROVED** [review]
Thanks :+1:
