### PR TITLE
Bugfix: failure to start if OIDC provider is unavailable

### LINKED ISSUE #34189: Failure to start if OIDC provider is unavailable
### 

### 

### 

### 

### Description

The application tries to obtain the OpenID configuration from the IdP at startup, and if it's not available (as in, the server is not available), it fails to launch.

### Steps to reproduce

1. Add a fake http://localhost/.well-known/openid-configuration
2. Mock requests to simply never be completed
3. Start up the application pointing your OIDC config to this
4. See application fail to launch

### Current behavior

We've coupled the ability of the application to start up with the availability of the OpenID provider, which is unacceptable.

### Expected behavior

The application can startup, though authentication may fail until the IdP is available. 

### Environment

SaaS & SM

### Version

- Component Version: 8.8.0-alpha5

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

- https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CMm16-LckcfnDg%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.namespace_name%3D%224f339c0d-6dd4-4275-a68c-aaa692682c14-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22;cursorTimestamp=2025-06-19T19:42:35.673627525Z;startTime=2025-06-19T19:13:40.446Z;endTime=2025-06-19T20:13:40.446Z?inv=1&invt=Ab06Qg&project=camunda-cloud-240911
- https://console.cloud.google.com/errors/detail/CMm16-LckcfnDg;service=zeebe;time=P7D;locations=global?inv=1&invt=Ab06Rw&project=camunda-cloud-240911

### PR DESCRIPTION
**Pull request by ana-vinogradova-camunda**
## Description
The bug:
- application tries to obtain the OpenID configuration from the IdP at startup, and if it's not available (as in, the server is not available), it fails to launch.

Expected behaviour:

- the application should still star successfully, but authentication will fail until the IdP is available.

Solution (please see commit messages for more details):
Two places are affected by this bug:
- `clientRegistrationRepository` bean creation
- `jwtDecoder` bean creation (as it needs the `clientRegistrationRepository`) 

Lets introduce custom `ClientRegistrationRepository`  and `JwtDecoder` implementations that:

- will attempt to construct `InMemoryClientRegistrationRepository` and `decoder` the same way as it is done now (on application startup). Let's attempt it once. This would ensure that if there are no issues we are ready to authenticate after startup straight away.
- if for some reason construction of the above beans fails:
  - we log a warning message (as it is recoverable error)
  - we will schedule async retries to create the repository and the decoder in separate threads. We will continue with Spring start up.
  - we will throw an exception telling that the configuration is not yet initialised until the retries succeed.
  - the exception will be propagated to the user
  - once retries succeed - we construct both repository and decoder and use them under the hood.
  - users are able to authenticate

Integration test with the below scenario was also added:
- set up the application to point to a proxy instead of keycloak first
- verify that application is up but client request fails with the expected message
- point proxy to keycloak
- verify that client request succeeds

❓ Open question:
- Error handling. @Ben-Sheppard I'd appreciate your help here 🙏 

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #34189

### CODE REVIEW

File: authentication/src/main/java/io/camunda/authentication/config/SafeInitClientRegistrationRepository.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+  }
+
+  @Override
+  public ClientRegistration findByRegistrationId(final String registrationId) {
+    // if repository is initialized, then delegate method call to it. If not, throw an exception
+    // that will be propagated to client.
+    return proxy
+        .orElseThrow(
+            () ->
+                new RuntimeException(
```
Comment (bmudric) [inline authentication/src/main/java/io/camunda/authentication/config/SafeInitClientRegistrationRepository.java]: Here and in `SafeInitJwtDecoder` it would be useful to provide an Exception class that is more semantically appropriate.
I was thinking Spring's `BeanInitializationException` as we're building a Bean, but actually we throw here on access, not on initialization.
Perhaps then the Java built-in `IllegalStateException` makes most sense. 
We could add our own Exception, but that is probably just noise if we're not handling it specifically elsewhere.
WDYT?

Comment (ana-vinogradova-camunda) [reply authentication/src/main/java/io/camunda/authentication/config/SafeInitClientRegistrationRepository.java]: I agree with `IllegalStateException` exception for `SafeInitClientRegistrationRepository`
 However, for `SafeInitJwtDecoder` we have to have `AuthenticationCredentialsNotFoundException` in order for Spring to pass it to our error handler (unless I am missing something, but I think I am correct). There are other exceptions that could be used to achieve the same but the choice is limited as they have to extend `AuthenticationException` 🙂 
 
 UPD: I've just verified my assumption - yes, this is how it currently works. 
 For reference : please see `AuthFailureHandler`, `AuthenticationEntryPoint` and corresponding `AuthenticationException`.

Comment (ana-vinogradova-camunda) [reply authentication/src/main/java/io/camunda/authentication/config/SafeInitClientRegistrationRepository.java]: We could potentially introduce our own Exception what would extends `AuthenticationException` but it seems like an overkill to me (especially in the timeline that we currently have).

Comment (ana-vinogradova-camunda) [reply authentication/src/main/java/io/camunda/authentication/config/SafeInitClientRegistrationRepository.java]: For clarity of what's happening you can also look at `BearerTokenAuthenticationFilter` line 160:
```
	catch (AuthenticationException failed) {
		this.securityContextHolderStrategy.clearContext();
		this.logger.trace("Failed to process authentication request", failed);
		this.authenticationFailureHandler.onAuthenticationFailure(request, response, failed);
	}
```

And line 83:
```
private AuthenticationFailureHandler authenticationFailureHandler = new AuthenticationEntryPointFailureHandler(
	(request, response, exception) -> this.authenticationEntryPoint.commence(request, response, exception));
```
So if we throw something that is not `AuthenticationException`, it is not gonna be handled properly.

Comment (bmudric) [reply authentication/src/main/java/io/camunda/authentication/config/SafeInitClientRegistrationRepository.java]: Thank you for the investigation and explanation!
Then I'd propose:
* let's change the `RuntimeException` to an `IllegalStateException` for clarity
* add a comment on top of `AuthenticationCredentialsNotFoundException` explaining, in short, why the exception type is there as you just explained to me - it will be very useful for the next person not to scratch their head :)

**Review by bmudric — APPROVED** [review]
Thank you for the nice implementation and addressing the comments!
