### PR TITLE
Reset next segment when async creation failed

### LINKED ISSUE #13955: Unable to create new snapshot due to 'IOException: No space left on device'
**Describe the bug**

Google Error Reporting reported [this error](https://console.cloud.google.com/errors/detail/CIS745nl9fy3hQE;service=zeebe;time=P7D?project=camunda-cloud-240911). It occurred at a moment when the leader was Out Of Diskspace (OOD). The broker recovered independently after receiving more disk space.

The reported error log is surrounded by many logged errors stating:

<details><summary>Failed to acquire next segment, retrying synchronously now</summary>
<p>

```
java.util.concurrent.CompletionException: io.camunda.zeebe.journal.JournalException$OutOfDiskSpace: Not enough space to allocate a new journal segment. Required: 13661604004, Available: 6651944960
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: io.camunda.zeebe.journal.JournalException$OutOfDiskSpace: Not enough space to allocate a new journal segment. Required: 13661604004, Available: 6651944960
	at io.camunda.zeebe.journal.file.SegmentLoader.checkDiskSpace(SegmentLoader.java:237) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentLoader.mapNewSegment(SegmentLoader.java:211) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentLoader.createUninitializedSegment(SegmentLoader.java:90) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentsManager.createUninitializedSegment(SegmentsManager.java:336) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentsManager.lambda$prepareNextSegment$1(SegmentsManager.java:322) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	... 7 more
```

</p>
</details> 

It may be relevant to mention that this did not occur on a stable version but on `8.2.11-SNAPSHOT-dmn-cache-f439306`, although that does not exclude other versions from experiencing this.

**To Reproduce**

NA

**Expected behavior**

I'd expect the leader to gracefully stepdown before spamming error logs on OOD.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.io.UncheckedIOException: java.io.IOException: No space left on device
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newSnapshot(FileBasedSnapshotStore.java:547) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.persistInternal(FileBasedTransientSnapshot.java:152) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$persist$3(FileBasedTransientSnapshot.java:112) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:98) ~[zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:205) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
Caused by: java.io.IOException: No space left on device
	at java.io.RandomAccessFile.writeBytes(Native Method) ~[?:?]
	at java.io.RandomAccessFile.write(Unknown Source) ~[?:?]
	at io.camunda.zeebe.snapshots.impl.SnapshotChecksum.persist(SnapshotChecksum.java:64) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newSnapshot(FileBasedSnapshotStore.java:544) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	... 9 more
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: `8.2.11-SNAPSHOT-dmn-cache-f439306`
- Configuration:

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

See description here https://github.com/camunda/zeebe/issues/13955#issuecomment-1705126246
> I was able to reproduce this issue with a test. When creating the first segment and we reach out of disk, we see the following exception: io.camunda.zeebe.journal.JournalException$OutOfDiskSpace, but after the first creation, the segments are created async. This means the type of exception changes to: java.util.concurrent.CompletionException: io.camunda.zeebe.journal.JournalException$OutOfDiskSpace. This is catched in the [SegmentsManager](https://github.com/camunda/zeebe/blob/main/journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java#L134), and retried synchronously. The exception will be logged with the completion exception. If this now fails again with OutOfDisk for example, we will not reset the nextSegment future. This means on the next try we will join on the future again, throw the exception again, log it again, and try it again synchronously. This produces our loop.

This PR contains:

 * A new test to verify that OOD is thrown even when async segment creation is happening.
 * A new test to verify that exception for async segment creation is only written (and happening) once.
 * NextSegment future reset to null when future is exceptionally completed

## Related issues

closes https://github.com/camunda/zeebe/issues/13955

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java [hunk 1]
```diff
@@ -132,6 +132,7 @@ Segment getNextSegment() {
             nextSegment.join().initializeForUse(nextSegmentIndex, lastWrittenAsqn, journalMetrics);
       } catch (final CompletionException e) {
         LOG.error("Failed to acquire next segment, retrying synchronously now.", e);
+        nextSegment = null;
```
Comment (npepinpe) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java:135]: :+1: good catch!

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java [hunk 2]
```diff
@@ -900,4 +947,22 @@ private SegmentedJournal openJournal(final String data, final int entriesPerSegm
...
+   * Failing will be done via throwing an OutOfDiskException.
+   *
+   * @param failAtSegmentCount the count which should be reached, until a OOD exception is thrown.
+   * @return the failing segment allocator
+   */
+  private SegmentAllocator createFailingSegmentAllocator(final int failAtSegmentCount) {
+    final AtomicInteger segmentCount = new AtomicInteger(0);
+    return (channel, segmentSize) -> {
+      if (segmentCount.incrementAndGet() >= failAtSegmentCount) {
+        throw new OutOfDiskSpace("Nope, no free space.");
```
Comment (npepinpe) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:963]: :thought_balloon: very official error message

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java [hunk 3]
```diff
@@ -892,6 +897,49 @@ void shouldPreventWriteExclusiveOperationsWhileFlushing() {
...
+        .isInstanceOf(OutOfDiskSpace.class)
+        .hasMessage("Nope, no free space.");
+  }
+
+  @RegressionTest("https://github.com/camunda/zeebe/issues/13955")
+  void shouldPrintAsyncOODOnlyOnceFailed() {
+    // given
+    // in order to assert output
+    final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
+    System.setOut(new PrintStream(outContent));
```
Comment (npepinpe) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:922]: :question: Is `out` now always this `PrintStream` forever and ever? :thinking:

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java [hunk 4]
```diff
@@ -892,6 +897,49 @@ void shouldPreventWriteExclusiveOperationsWhileFlushing() {
...
+    assertThatThrownBy(() -> journal.append(3, journalFactory.entry()))
+        .isInstanceOf(OutOfDiskSpace.class)
+        .hasMessage("Nope, no free space.");
+    assertThatThrownBy(() -> journal.append(4, journalFactory.entry()))
+        .isInstanceOf(OutOfDiskSpace.class)
+        .hasMessage("Nope, no free space.");
+  }
+
+  @RegressionTest("https://github.com/camunda/zeebe/issues/13955")
+  void shouldPrintAsyncOODOnlyOnceFailed() {
```
Comment (npepinpe) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:918]: :thought_balloon: I'm not sure if this test is all that necessary. What do we want to test? That we switch to synchronous creation, and as such that message is printed out after? I'd like testing that better than log messages =/ That said, I don't have a good idea OTOH, hence the :thought_balloon:

**Review by npepinpe — APPROVED** [review]

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java (hunk 4 above)
Comment (Zelldon) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:918]: Thats the thing I was also struggling. There is not really a behavior observable from outside, which we can verify except the logging.

**Comment by Zelldon** [comment]
@npepinpe I removed the test.

**Comment by Zelldon** [comment]
Bors r+
