### PR TITLE
fix: handle non-numeric formKey in FlowNodeInstanceMetadataBuilder

### LINKED ISSUE #40274: 400 (Bad Request) is returned when selecting the node with embedded forms in Process Details
### 

### 

### 

### 

### Description

Slack thread: https://camunda.slack.com/archives/C08MRKHJ0CD/p1761745508712339

Error message is returned in BE and infinite loading on FE when selecting the node with embedded forms
```
{
    "type": "about:blank",
    "title": "Bad Request",
    "status": 400,
    "detail": "For input string: \"camunda-forms:bpmn:userTaskForm_0pjtr0l\"",
    "instance": "/3ecd341a-8f6b-4587-8f5e-3fc4089ddbdc/api/process-instances/2251799813685788/flow-node-metadata"
}
```
E.g. https://hel-1.operate.ultrawombat.com/3ecd341a-8f6b-4587-8f5e-3fc4089ddbdc/operate/processes/2251799813685788?continue
Cluster ID: 3ecd341a-8f6b-4587-8f5e-3fc4089ddbdc

### Steps to reproduce

1. I deployed 'Quick Start Human Tasks' process from a blueprint that uses User Task with Job worker and Camunda Form (embedded).
2. Navigate to Operate
3. Open Process instance details
4. Select the first User task node

### Current behavior

Variables panel shows infinite loading and  400 error

Image

### Expected behavior

Pannel is loaded

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS

### Version

- Component Version: [e.g. 8.8]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tsedekey**
## Description

This PR fixes a 400 Bad Request error that occurs when selecting a user task with an embedded Camunda Form in Operate's Process Instance Details view. The root cause was `Long.parseLong()` being called unconditionally on `TaskEntity.formKey` in `FlowNodeInstanceMetadataBuilder`, which throws `NumberFormatException` for embedded form key strings (e.g. `camunda-forms:bpmn:userTaskForm_0pjtr0l`). 

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes ##40274

### CODE REVIEW

File: operate/webapp/src/main/java/io/camunda/operate/webapp/reader/metadata/FlowNodeInstanceMetadataBuilder.java [hunk 1]
```diff
@@ -231,4 +233,16 @@ private ServiceTaskInstanceMetadataDto getServiceTaskInstanceMetadataDto(
...
+    if (formKey == null || EMBEDDED_FORMS_PATTERN.matcher(formKey).matches()) {
+      return null;
+    }
+    try {
+      return Long.parseLong(formKey);
+    } catch (final NumberFormatException e) {
+      LOGGER.warn("Failed to parse formKey '{}' as Long, returning null", formKey);
+      return null;
+    }
+  }
```
[the remark this answers is not in the document]
Comment (tsedekey) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/reader/metadata/FlowNodeInstanceMetadataBuilder.java:247]: I agree DEBUG is the correct level here and aligns with similar safe-parsing patterns in the codebase. Introducing the `isNumeric` here is redundant with what we already have. The current approach already handles non-numeric strings gracefully: the pattern catches the known common case, and the try-catch catches everything else. Adding `isNumeric` as a third layer of checking is unnecessary.

**Comment by tmetzke** [comment]
Quick question: what should happen for user tasks with embedded forms? Do we not display the form key, then? Is that expected, or will this be a regression?

**Comment by tsedekey** [comment]
> Quick question: what should happen for user tasks with embedded forms? Do we not display the form key, then? Is that expected, or will this be a regression?

Good question @tmetzke. The short answer is: no, we don't display the form key for embedded forms after this fix, it will be null. This is not a regression from the current behaviour (which is a 400 crash), but it is a limitation. 

### Here's the full context:

#### Why embedded form keys can't be populated today
From my understanding, the `formKey` field on `UserTaskInstanceMetadataDto` is typed as Long. This was correct when Operate had its own `UserTaskEntity` (introduced by [commit](https://github.com/camunda/camunda/commit/3f6e16ce1af)), where formKey was a Long, it only represented Zeebe native user tasks, which always have numeric form keys.

In [fix: migrate operate to use tasklist-task index](https://github.com/camunda/camunda/commit/3e6f70fc62c), Operate was migrated to read from the shared `TaskEntity` (webapps-schema), where `formKey` is a String. This was necessary because `TaskEntity` serves both Zeebe native user tasks (numeric form keys like "12345") and job-worker user tasks with embedded forms (string references like `camunda-forms:bpmn:userTaskForm_0pjtr0l`).

During that migration, `Long.parseLong(task.getFormKey())` was added to bridge the String → Long type gap. This worked for numeric keys but introduced a latent bug: any non-numeric formKey (i.e., embedded forms) throws a `NumberFormatException`, which surfaces as a 400 Bad Request. The DTO's Long type was never updated to accommodate the now-wider range of form key formats.

#### What this PR fixes
This PR prevents the crash by safely returning null for non-numeric form keys. After this fix:

- Linked/deployed forms (numeric keys): `formKey` is populated as before — no change.

- Embedded forms (string references): `formKey` is null in the response. The metadata endpoint returns successfully, and the Variables panel loads correctly instead of showing infinite loading with a 400 error.

#### Preserving the embedded form key string

To actually populate the embedded form key in the API response, the `formKey` field on `UserTaskInstanceMetadataDto` would need to change from Long to String (or a new field would need to be added). From my investigation, the Operate frontend does not consume `formKey` from this endpoint, so the type change would likely not be a breaking change in practice. It would also simplify the builder code — the `parseFormKeyOrNull` helper and embedded form pattern matching could be removed entirely in favour of a direct String assignment.

That said, this is a type change to the DTO (number → string in JSON serialization), and I'm not sure what other downstream impact this might have beyond the frontend. Given your experience with the Operate API surface, would changing `formKey` from Long to String on the DTO be something you'd be comfortable with as part of this fix, or would you prefer we keep this PR as the minimal safe fix and handle the type change separately?

**Comment by tmetzke** [comment]
Thanks, @tsedekey 👍 

Can we quickly check what we did in Operate before Camunda user tasks existed? We already handled user tasks in Operate, I guess? If not, all good. If we did, we should check why we now only expose Camunda user tasks?

Maybe those have their own handler that is job based, so we shouldn't run into those user tasks here and the fix you linked is introducing other issues now after switching the index?

Would just like to understand how both are handled in Operate.

**Comment by tsedekey** [comment]
> Thanks, @tsedekey 👍
> 
> Can we quickly check what we did in Operate before Camunda user tasks existed? We already handled user tasks in Operate, I guess? If not, all good. If we did, we should check why we now only expose Camunda user tasks?
> 
> Maybe those have their own handler that is job based, so we shouldn't run into those user tasks here and the fix you linked is introducing other issues now after switching the index?
> 
> Would just like to understand how both are handled in Operate.

Yes @tmetzke I dug a little deeper and here what I understood. Before Camunda user tasks existed, all user tasks were job-worker-based. Operate had no dedicated user task index or reader — it tracked them as generic flow nodes via `operate-flownode-instance` and `operate-event`. Form keys lived inside `jobCustomHeaders`, not as a first-class field.

When Zeebe native user tasks were introduced (~8.5), we created the `operate-user-task` index with `formKey` typed as `Long`. Only Zeebe native user tasks were written there. Job-worker user tasks had no entry in that index, so `userTaskReader.getUserTaskByFlowNodeInstanceKey()` returned `Optional.empty()` and the form key was simply `null` in the metadata response.

The Oct 2024 migration (`3e6f70fc62c`) switched Operate to the shared `tasklist-task` index, which contains both Zeebe native and job-worker user tasks with `formKey` as `String`. This expanded the reader's scope — job-worker user tasks are now found, but `Long.parseLong(task.getFormKey())` was added without handling non-numeric form keys like `camunda-forms:bpmn:userTaskForm_0pjtr0l`. 

Our fix returns `null` for non-numeric form keys, restoring the pre-migration behaviour where job-worker user tasks never had a form key in this response. But I'm inclined to change the `formKey` from Long to String type in `UserTaskInstanceMetadataDto` and this should resolve the bug more permanently.

File: operate/webapp/src/main/java/io/camunda/operate/webapp/reader/metadata/FlowNodeInstanceMetadataBuilder.java [hunk 2]
```diff
@@ -231,4 +233,16 @@ private ServiceTaskInstanceMetadataDto getServiceTaskInstanceMetadataDto(
         messageSubscription,
         job);
   }
+
+  private static Long parseFormKeyOrNull(final String formKey) {
+    if (formKey == null || EMBEDDED_FORMS_PATTERN.matcher(formKey).matches()) {
```
Comment (tmetzke) [inline operate/webapp/src/main/java/io/camunda/operate/webapp/reader/metadata/FlowNodeInstanceMetadataBuilder.java:238]: 💭 We could also drop the regex evaluation, I guess. If the Long-parsing fails, we'll return `null` anyway. Just as a thought. It's a bit cleaner with the regex, but it also means we're depending on that regex.

Comment (tsedekey) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/reader/metadata/FlowNodeInstanceMetadataBuilder.java:238]: I’d prefer that when parsing fails for reasons other than the embedded form not being found, we log it at debug level. That way, we have more context available and can rule out cases where it was simply attempting to parse a form key as a string, and this also reduces the log noise.

**Comment by tsedekey** [comment]
@tmetzke I made a quick demo showing what Operate UI and the endpoint will look like after this fix to illustrate more:

https://github.com/user-attachments/assets/fecad5b0-6449-4701-b5c3-109ca599d9e3

Top user task is Job Worker based and the bottom one is Camunda user task.

**Review by tmetzke — APPROVED** [review]
👍 Thanks for fixing this, @tsedekey 🙏

File: operate/webapp/src/main/java/io/camunda/operate/webapp/reader/metadata/FlowNodeInstanceMetadataBuilder.java (hunk 2 above)
Comment (tmetzke) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/reader/metadata/FlowNodeInstanceMetadataBuilder.java:238]: Yeah, we can certainly do that, no objections 👍
