### PR TITLE
fix: stop using tasks api for archiving

### LINKED ISSUE #34851: Opensearch archiver deleting records on Opensearch
### 

### 

, , 

### 

### 

### Description

Operate's Opensearch archiver sequence is sometimes altered, meaning that document deletion from runtime indices can happen before the reindexing of the documents to dated indices.

Further context on [thread](https://camunda.slack.com/archives/C08NQKV761G/p1751548372378939)

### Steps to reproduce

Setup an Opensearch environment for Operate & Zeebe

1. Start and complete a process instance
2. Wait for the Archiver to pick up the Process Instance
3. Search all dated indices of Operate with `processInstanceKey=<PI_KEY>`
4. On some of them, there will be no reference of that Process Instance, discretion applies depending on what your Process definition is

It's not 100% guaranteed that will happen.

### Current behavior

Opensearch archiver may sometimes delete documents from the runtime indices before the reindex operation is done.

### Expected behavior

Deletion of documents happens after the reindex operation is completed at all times.

### Environment

SM

### Version

- Component Version: 8.7, 8.6, 8.5

### Rootcause

Opensearch archiving is not making use of `OpenSearchAsyncClient`.

### Solution ideas

Utilize `OpenSearchAsyncClient`

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

Stop polling Opensearch Tasks API for reindex operation completion during Archiving, instead rely on the client response itself. The Tasks API seems to be unreliable and causes data to be removed before reindex is completed during archiving.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #34851

### CODE REVIEW

File: operate/schema/src/main/java/io/camunda/operate/util/OpensearchUtil.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+import java.util.concurrent.CompletableFuture;
+import org.opensearch.client.opensearch.OpenSearchAsyncClient;
+import org.opensearch.client.opensearch.core.DeleteByQueryRequest;
+import org.opensearch.client.opensearch.core.DeleteByQueryResponse;
+import org.opensearch.client.opensearch.core.ReindexRequest;
+import org.opensearch.client.opensearch.core.ReindexResponse;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+public abstract class OpensearchUtil {
```
Comment (houssain-barouni) [inline operate/schema/src/main/java/io/camunda/operate/util/OpensearchUtil.java]: No need for polymorphism :)
```suggestion
public final class OpensearchUtil {
  private OpensearchUtil() {}
```

File: operate/schema/src/main/java/io/camunda/operate/util/OpensearchUtil.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+  private static final Logger LOGGER = LoggerFactory.getLogger(OpensearchUtil.class);
+
+  public static <T> Either<Throwable, Long> handleResponse(
+      final T response, final Throwable error, final String sourceIndexName) {
```
Comment (houssain-barouni) [inline operate/schema/src/main/java/io/camunda/operate/util/OpensearchUtil.java:32]: what about making this method more generic and avoid handling response types
```suggestion
public static Either<Throwable, Long> handleResponse(
    final Long total,
    final List<?> failures,
    final String operation,
    final Throwable error,
    final String sourceIndexName) {
```

**Review by houssain-barouni — APPROVED** [review]
Thank you for handling this 👍 
I left couple of nitpicks, but pre-approving

File: operate/schema/src/main/java/io/camunda/operate/util/OpensearchUtil.java (hunk 2 above)
Comment (panagiotisgts) [reply operate/schema/src/main/java/io/camunda/operate/util/OpensearchUtil.java:32]: You would have to do _null_ checks on the response itself before passing it to the handler to retrieve the total and failures, introducing some noise. Since we only use it for the DeleteByQuery and Reindex response handling I think it's fine for now.

File: operate/schema/src/main/java/io/camunda/operate/util/OpensearchUtil.java [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+    // Utility class, no instantiation
+  }
+
+  public static <T> Either<Throwable, Long> handleResponse(
+      final T response, final Throwable error, final String sourceIndexName) {
+    final String operation = response instanceof ReindexResponse ? "reindex" : "deleteByQuery";
+    if (error != null) {
+      final var message =
+          String.format(
+              "Exception occurred, while performing operation %s on source index %s. the documents: %s",
```
Comment (RomanJRW) [inline operate/schema/src/main/java/io/camunda/operate/util/OpensearchUtil.java]:
```suggestion
          String.format(
              "Exception occurred, while performing operation %s on source index %s. Error: %s",
```
Not sure I understood the intention of "the documents", feel free to explain if this was intentional

**Review by RomanJRW — APPROVED** [review]
Thanks for making this change, LGTM with one small comment ✅
