### PR TITLE
Don't apply `group id` restrictions when BYOGroups is enabled

### LINKED ISSUE #41096: Group Id restrictions are applied when BYOGroups is enabled
### 

### 

### 

### 

### Description

When BYOGroups is enabled on a 8.8 cluster, users are still limited to adhere to internal id constraints e.g. when adding a Group to a Role. However as the control over the format of the id lies within the IdP, actually not restrictions should be enforced.

### Steps to reproduce

1. Create a 8.8 Cluster with [BYGroups enabled](https://docs.camunda.io/docs/self-managed/components/orchestration-cluster/identity/connect-external-identity-provider/#optional-step-8-configure-bring-your-own-groups)
2. Create a Group with the identifier "My Group" in your IDP (alternatively through Management Identity, when using Keycloak)
3. Try to assign a Group with the name "My Group" to a Role

### Current behavior

4. Adding the Group to the Role fails, see 
Image

While in the IdP and Management Identity this group exists:
Image

As well as in the JWT Access Token:
Image

### Expected behavior

4. It should succeed

### Workaround

None, or change Group identifiers in IdP to comply with the restrictions (bad UX)

### Environment

SM

### Version

- Component Version: <=8.8.4

### Rootcause

Id Constraints for Group Identifiers are still enforced on API layer when BYGroups is enabled. 
This applies to at least the Role API, we need to check other APIs for the same as well.

### Solution ideas

We should consider disabling  Group ID validation fully in this case, as Group ID format is not within control of the OC in this case.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

Relates to https://github.com/camunda/camunda/issues/40780

### PR DESCRIPTION
**Pull request by ana-vinogradova-camunda**
## Description

When BYOGroups is enabled on a 8.8 cluster, users are still limited to adhere to internal id constraints e.g. when adding a Group to a Role or Tenant. However, as the control over the format of the id lies within the IdP, no restrictions should be enforced.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #41096

### CODE REVIEW

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java [hunk 1]
```diff
@@ -369,4 +369,17 @@ private CompletableFuture<ResponseEntity<Object>> removeMemberFromRole(
                 .withAuthentication(authenticationProvider.getCamundaAuthentication())
                 .removeMember(request));
   }
+
+  private boolean hasGroupClaimConfigured() {
```
Comment (npepinpe) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: 🙃 It's sort of what we want to know, in the end:
```suggestion
  private boolean areGroupsManagedExternally() {
```

**Review by npepinpe — COMMENTED** [review]
Direction looks good

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java [hunk 2]
```diff
@@ -369,4 +369,17 @@ private CompletableFuture<ResponseEntity<Object>> removeMemberFromRole(
...
+    if (authentication == null) {
+      return false;
+    }
+    final var oidcConfiguration = authentication.getOidc();
+    if (oidcConfiguration == null) {
+      return false;
+    }
+    final var groupsClaim = oidcConfiguration.getGroupsClaim();
+    return groupsClaim != null && !groupsClaim.isEmpty();
+  }
```
Comment (ana-vinogradova-camunda) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: 💭 This method is now present in 2 controllers. I think it is OK, but let me know if you have other ideas.

Comment (npepinpe) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: It could potentially go on the configuration itself, e.g. directly on the `authentication` configuration. That _could_ make it future proof for when we support more protocols.

Or we follow the rule of three, and wait for the triplication ;)

I would recommend we add it to the authentication configuration, but I'm also OK with waiting.

Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: I like this approach. It will also make the check smaller and easier to read 👍

File: zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantControllerTest.java [hunk 3]
```diff
@@ -626,6 +628,34 @@ void testRemoveMemberToTenantWithInvalidEntityId(
       verifyNoInteractions(tenantServices);
     }
 
+    @Test
+    void shouldAssignExternalGroupToTenantAndReturnNoContentWhenGroupClaimIsPresent() {
+      // given
+      final var tenantId = "some-tenant-id";
+      final var groupId = "group id";
```
Comment (megglos) [inline zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantControllerTest.java:639]: 🔧  let's state explicitly that the point here is that the groupId used is not compliant with the [`SecurityConfiguration.idValidationPattern`](https://github.com/camunda/camunda/blob/a896ea91b12294118150269b14d304bdcbe32f50/security/security-core/src/main/java/io/camunda/security/configuration/SecurityConfiguration.java#L34)

either via comment (tend to prefer that, as it allows to provide the reference to the pattern config etc.) or in the method name

File: zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleControllerTest.java [hunk 4]
```diff
@@ -940,6 +942,36 @@ void shouldAssignGroupToRoleAndReturnNoContent() {
     verify(roleServices, times(1)).addMember(request);
   }
 
+  @Test
+  void shouldAssignExternalGroupToRoleAndReturnNoContentWhenGroupClaimIsPresent() {
+    // given
+    final var roleId = "roleId";
+    // group id containing special characters to simulate external groups
```
Comment (megglos) [inline zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleControllerTest.java]: 🔧  I see here you provided the context, let's refer to the relevant pattern config still

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantController.java [hunk 5]
```diff
@@ -170,11 +171,14 @@ public CompletableFuture<ResponseEntity<Object>> assignMappingRuleToTenant(
   @CamundaPutMapping(path = "/{tenantId}/groups/{groupId}")
   public CompletableFuture<ResponseEntity<Object>> assignGroupToTenant(
       @PathVariable final String tenantId, @PathVariable final String groupId) {
+    final boolean areGroupsManagedExternally = areGroupsManagedExternally();
```
Comment (megglos) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantController.java]: ❌  the issue also affects the `unassignGroupFromTenant` aka Delete endpoint, that one also needs to get adjusted

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java [hunk 6]
```diff
@@ -263,11 +260,14 @@ public CompletableFuture<ResponseEntity<Object>> assignRoleToClient(
   @CamundaPutMapping(path = "/{roleId}/groups/{groupId}")
   public CompletableFuture<ResponseEntity<Object>> assignRoleToGroup(
       @PathVariable final String roleId, @PathVariable final String groupId) {
+    final boolean areGroupsManagedExternally = areGroupsManagedExternally();
```
Comment (megglos) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: ❌  the issue also affects the `unassignRoleFromGroup` aka Delete endpoint, that one also needs to get adjusted

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java [hunk 7]
```diff
@@ -263,11 +260,14 @@ public CompletableFuture<ResponseEntity<Object>> assignRoleToClient(
...
     return RequestMapper.toRoleMemberRequest(
             roleId,
             groupId,
             EntityType.GROUP,
-            securityConfiguration.getCompiledIdValidationPattern())
+            areGroupsManagedExternally
+                ? Pattern.compile(".*", Pattern.DOTALL)
```
[the remark this answers is not in the document]
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: 🔧 Looks good to me, will implement this change

[the remark this answers is not in the document]
Comment (megglos) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: ❌  that will also disable validation of the roleId, wouldn't it? `validateMemberRequest` uses the pattern for both.

Wdyt of actually adding a dedicated `getCompiledGroupIdValidationPattern` to `SecurityConfiguration` and changing the interface of the mapper methods to require a pattern for each of the ids passed. That way we keep them controllable separately and you would also solve the problem that right now the flag will also disable roleId validation.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java (hunk 2 above)
Comment (megglos) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: In favor of moving too!

**Review by megglos — CHANGES_REQUESTED** [review]
Happy this gets addressed right away!

Requesting changes for:
* DELETE endpoints need the same fix
* current state also disabled roleId validation in RoleController, TenantController is not affected, as there a dedicated validation pattern is used in `TenantRequestValidator`

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantController.java [hunk 8]
```diff
@@ -170,11 +171,14 @@ public CompletableFuture<ResponseEntity<Object>> assignMappingRuleToTenant(
...
     return RequestMapper.toTenantMemberRequest(
             tenantId,
             groupId,
             EntityType.GROUP,
-            securityConfiguration.getCompiledIdValidationPattern())
+            areGroupsManagedExternally
+                ? Pattern.compile(".*", Pattern.DOTALL)
```
[the remark this answers is not in the document]
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantController.java]: 👍 Already implemented

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java [hunk 9]
```diff
@@ -263,11 +260,14 @@ public CompletableFuture<ResponseEntity<Object>> assignRoleToClient(
   @CamundaPutMapping(path = "/{roleId}/groups/{groupId}")
   public CompletableFuture<ResponseEntity<Object>> assignRoleToGroup(
       @PathVariable final String roleId, @PathVariable final String groupId) {
+    final boolean areGroupsManagedExternally = areGroupsManagedExternally();
     return RequestMapper.toRoleMemberRequest(
             roleId,
             groupId,
             EntityType.GROUP,
-            securityConfiguration.getCompiledIdValidationPattern())
+            areGroupsManagedExternally
```
[the remark this answers is not in the document]
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: I believe it is clear from the variable name why are we allowing all here (`areGroupsManagedExternally` is quite a descriptive name)

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantController.java [hunk 10]
```diff
@@ -170,11 +171,14 @@ public CompletableFuture<ResponseEntity<Object>> assignMappingRuleToTenant(
   @CamundaPutMapping(path = "/{tenantId}/groups/{groupId}")
   public CompletableFuture<ResponseEntity<Object>> assignGroupToTenant(
       @PathVariable final String tenantId, @PathVariable final String groupId) {
+    final boolean areGroupsManagedExternally = areGroupsManagedExternally();
     return RequestMapper.toTenantMemberRequest(
             tenantId,
             groupId,
             EntityType.GROUP,
-            securityConfiguration.getCompiledIdValidationPattern())
+            areGroupsManagedExternally
```
[the remark this answers is not in the document]
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantController.java]: I believe it is clear from the variable name why are we allowing all here (areGroupsManagedExternally is quite a descriptive name)

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: Solved already.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantController.java [hunk 11]
```diff
@@ -474,4 +478,17 @@ private CompletableFuture<ResponseEntity<Object>> updateTenant(
...
+    if (authentication == null) {
+      return false;
+    }
+    final var oidcConfiguration = authentication.getOidc();
+    if (oidcConfiguration == null) {
+      return false;
+    }
+    final var groupsClaim = oidcConfiguration.getGroupsClaim();
+    return groupsClaim != null && !groupsClaim.isEmpty();
+  }
```
[the remark this answers is not in the document]
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantController.java]: Solved already.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java (hunk 1 above)
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: Done 👍

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleController.java]: That's a very good catch, thanks! I'd propose to introduce another validation method for Groups as current validation method is also used for clients, users and mapping rules.
(I will push the change soon for review)

File: zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleControllerTest.java (hunk 4 above)
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/usermanagement/RoleControllerTest.java]: Done 👍

File: zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantControllerTest.java (hunk 3 above)
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/tenant/TenantControllerTest.java:639]: Done 👍

**Comment by ana-vinogradova-camunda** [comment]
> # 🧪 Flaky Tests Summary
> _👻 Haunted Tests — They Fail When No One's Watching_
> 
> * [**shouldReturnOnlyTenantAMessageSubscriptions**](https://github.com/camunda/camunda/tree/41096-fix-group-id-restrictions/qa/acceptance-tests/src/test/java/io/camunda/it/tenancy/MessageSubscriptionTenancyIT.java)
>   
>   * Jobs: `opensearch-integration-tests, elasticsearch-integration-tests`
>   * Package: `io.camunda.it.tenancy`
>   * Class: `MessageSubscriptionTenancyIT`
>   * Pipeline runs: 5
>   * **Overall retries: 2 (per run: [1, 1, 0, 0, 0])**
> * [**shouldGetAuditLog**](https://github.com/camunda/camunda/tree/41096-fix-group-id-restrictions/clients/java/src/test/java/io/camunda/client/auditlog/GetAuditLogTest.java)
>   
>   * Jobs: `general-unit-tests`
>   * Package: `io.camunda.client.auditlog`
>   * Class: `GetAuditLogTest`
>   * Pipeline runs: 5
>   * **Overall retries: 2 (per run: [0, 0, 1, 1, 0])**
> * [**shouldReturnOnlyTenantAIncidents**](https://github.com/camunda/camunda/tree/41096-fix-group-id-restrictions/qa/acceptance-tests/src/test/java/io/camunda/it/tenancy/IncidentTenancyIT.java)
>   
>   * Jobs: `elasticsearch-integration-tests`
>   * Package: `io.camunda.it.tenancy`
>   * Class: `IncidentTenancyIT`
>   * Pipeline runs: 5
>   * **Overall retries: 1 (per run: [0, 1, 0, 0, 0])**
> * [**shouldReturnTenantOwnedSequenceFlows**](https://github.com/camunda/camunda/tree/41096-fix-group-id-restrictions/qa/acceptance-tests/src/test/java/io/camunda/it/tenancy/SequenceFlowTenancyIT.java)
>   
>   * Jobs: `elasticsearch-integration-tests`
>   * Package: `io.camunda.it.tenancy`
>   * Class: `SequenceFlowTenancyIT`
>   * Pipeline runs: 5
>   * **Overall retries: 1 (per run: [0, 1, 0, 0, 0])**
> * [**getByKeyShouldReturnTenantOwnedDecisionInstance**](https://github.com/camunda/camunda/tree/41096-fix-group-id-restrictions/qa/acceptance-tests/src/test/java/io/camunda/it/tenancy/DecisionInstanceTenancyIT.java)
>   
>   * Jobs: `opensearch-integration-tests`
>   * Package: `io.camunda.it.tenancy`
>   * Class: `DecisionInstanceTenancyIT`
>   * Pipeline runs: 5
>   * **Overall retries: 1 (per run: [0, 1, 0, 0, 0])**
> * [**getByKeyShouldReturnTenantOwnedProcessDefinition**](https://github.com/camunda/camunda/tree/41096-fix-group-id-restrictions/qa/acceptance-tests/src/test/java/io/camunda/it/tenancy/ProcessDefinitionTenancyIT.java)
>   
>   * Jobs: `opensearch-integration-tests`
>   * Package: `io.camunda.it.tenancy`
>   * Class: `ProcessDefinitionTenancyIT`
>   * Pipeline runs: 5
>   * **Overall retries: 1 (per run: [0, 1, 0, 0, 0])**
> * [**shouldContinueScaleDownAfterRestart**](https://github.com/camunda/camunda/tree/41096-fix-group-id-restrictions/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/cluster/clustering/dynamic/ScaleResiliencyTest.java)
>   
>   * Jobs: `integration-tests/Zeebe - [IT] Zeebe Cluster QA - Distributed Systems`
>   * Package: `io.camunda.zeebe.it.cluster.clustering.dynamic`
>   * Class: `ScaleResiliencyTest$ScaleDown`
>   * Pipeline runs: 5
>   * **Overall retries: 1 (per run: [0, 1, 0, 0, 0])**
> * [**shouldRecoverAfterOutOfDiskSpaceAfterExporting**](https://github.com/camunda/camunda/tree/41096-fix-group-id-restrictions/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/cluster/health/DiskSpaceRecoveryIT.java)
>   
>   * Jobs: `integration-tests/Zeebe - [IT] Zeebe Cluster QA - Distributed Systems`
>   * Package: `io.camunda.zeebe.it.cluster.health`
>   * Class: `DiskSpaceRecoveryIT$WithStandardContainerTest`
>   * Pipeline runs: 5
>   * **Overall retries: 1 (per run: [0, 0, 0, 0, 1])**
> 
> If the changes affect this area, **please check and fix before merging**. If not, **leave a quick comment** explaining why it's likely unrelated.

My changes are unrelated as they only change the ID pattern validation.

**Review by megglos — APPROVED** [review]
👍  LGTM!

**Comment by ana-vinogradova-camunda** [comment]
> 👍 LGTM!

I will backport to 8.8 too
