### PR TITLE
Fix activation of Parallel Gateway through Process Instance Modification

### LINKED ISSUE #10518: Using modification, I can't activate a parallel gateway
**Describe the bug**

The process instance modification doesn't work for parallel gateways.

I deployed a process with a parallel gateway. I created an instance of the process. The parallel gateway is completed.

Now, I try to modify the process instance and activate the parallel gateway. The modification command is applied (i.e. no rejection) but the parallel gateway is not activated.

image

**To Reproduce**

1. Deploy the process: [issue-10518.bpmn](https://github.com/camunda/zeebe/files/9655007/issue-10518.bpmn.txt) (with the correct `.bpmn` file extension)
2. Create an instance of the process
3. Wait until the parallel gateway is completed
4. Modify the process instance and try to activate the parallel gateway
5. Verify that the parallel gateway is not activated

<details><summary>JUnit test</summary>
 <p>

```
@Test
  public void shouldActivateParallelGateway() {
    // given
    ENGINE
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(PROCESS_ID)
                .startEvent()
                .parallelGateway("fork")
                .serviceTask("A", a -> a.zeebeJobType("A"))
                .endEvent()
                .moveToNode("fork")
                .serviceTask("B", b -> b.zeebeJobType("B"))
                .endEvent()
                .done())
        .deploy();

    final var processInstanceKey = ENGINE.processInstance().ofBpmnProcessId(PROCESS_ID).create();

    Assertions.assertThat(
            RecordingExporter.jobRecords(JobIntent.CREATED)
                .withProcessInstanceKey(processInstanceKey)
                .limit(2))
        .hasSize(2);

    // when
    ENGINE
        .processInstance()
        .withInstanceKey(processInstanceKey)
        .modification()
        .activateElement("fork")
        .modify();

    // then
    Assertions.assertThat(
            RecordingExporter.jobRecords(JobIntent.CREATED)
                .withProcessInstanceKey(processInstanceKey)
                .limit(4))
        .hasSize(4);
  }
```

</p>
</details>

**Expected behavior**

Using the process instance modification, I can activate a parallel gateway.

**Log/Stacktrace**

<details><summary>Test output</summary>
 <p>

```
13:24:19.101 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DPLY CREATE            - #01-> -1  -1 - 
E PROC CREATED           - #02->#01 K01 - process.xml -> "process" (version:1)
E DPLY CREATED           - #03->#01 K02 - process.xml
E DPLY FULLY_DISTRIBUTED - #04->#01 K02 - 
C CREA CREATE            - #05-> -1  -1 - new <process "process"> (default start)  (no vars)
C PI   ACTIVATE          - #06->#05 K03 - PROCESS "process" in <process "process"[K03]>
E CREA CREATED           - #07->#05 K04 - new <process "process"> (default start)  (no vars)
E PI   ACTIVATING        - #08->#06 K03 - PROCESS "process" in <process "process"[K03]>
E PI   ACTIVATED         - #09->#06 K03 - PROCESS "process" in <process "process"[K03]>
C PI   ACTIVATE          - #10->#06  -1 - START_EVENT "startEv..b449aeb" in <process "process"[K03]>
E PI   ACTIVATING        - #11->#10 K05 - START_EVENT "startEv..b449aeb" in <process "process"[K03]>
E PI   ACTIVATED         - #12->#10 K05 - START_EVENT "startEv..b449aeb" in <process "process"[K03]>
C PI   COMPLETE          - #13->#10 K05 - START_EVENT "startEv..b449aeb" in <process "process"[K03]>
E PI   COMPLETING        - #14->#13 K05 - START_EVENT "startEv..b449aeb" in <process "process"[K03]>
E PI   COMPLETED         - #15->#13 K05 - START_EVENT "startEv..b449aeb" in <process "process"[K03]>
E PI   SEQ_FLOW_TAKEN    - #16->#13 K06 - SEQUENCE_FLOW "sequenc..293a63b" in <process "process"[K03]>
C PI   ACTIVATE          - #17->#13 K07 - PARALLEL_GATEWAY "fork" in <process "process"[K03]>
E PI   ACTIVATING        - #18->#17 K07 - PARALLEL_GATEWAY "fork" in <process "process"[K03]>
E PI   ACTIVATED         - #19->#17 K07 - PARALLEL_GATEWAY "fork" in <process "process"[K03]>
E PI   COMPLETING        - #20->#17 K07 - PARALLEL_GATEWAY "fork" in <process "process"[K03]>
E PI   COMPLETED         - #21->#17 K07 - PARALLEL_GATEWAY "fork" in <process "process"[K03]>
E PI   SEQ_FLOW_TAKEN    - #22->#17 K08 - SEQUENCE_FLOW "sequenc..9ca8fc5" in <process "process"[K03]>
C PI   ACTIVATE          - #23->#17 K09 - SERVICE_TASK "B" in <process "process"[K03]>
E PI   SEQ_FLOW_TAKEN    - #24->#17 K10 - SEQUENCE_FLOW "sequenc..17fa29d" in <process "process"[K03]>
C PI   ACTIVATE          - #25->#17 K11 - SERVICE_TASK "A" in <process "process"[K03]>
E PI   ACTIVATING        - #26->#23 K09 - SERVICE_TASK "B" in <process "process"[K03]>
E JOB  CREATED           - #27->#23 K12 - K12 "B" @"B"[K09] 3 retries, in <process "process"[K03]> (no vars)
E PI   ACTIVATED         - #28->#23 K09 - SERVICE_TASK "B" in <process "process"[K03]>
E PI   ACTIVATING        - #29->#25 K11 - SERVICE_TASK "A" in <process "process"[K03]>
E JOB  CREATED           - #30->#25 K13 - K13 "A" @"A"[K11] 3 retries, in <process "process"[K03]> (no vars)
E PI   ACTIVATED         - #31->#25 K11 - SERVICE_TASK "A" in <process "process"[K03]>
C MOD  MODIFY            - #32-> -1 K03 - <activate "fork" no vars> 
C PI   ACTIVATE          - #33->#32 K14 - PARALLEL_GATEWAY "fork" in <process "process"[K03]>
E MOD  MODIFIED          - #34->#32 K03 - <activate "fork" no vars> 
R PI   ACTIVATE          - #35->#33 K14 - PARALLEL_GATEWAY "fork" in <process "process"[K03]> !INVALID_STATE (Expected to be able to activate parallel gateway 'fork', but not all sequence flows have been taken.)

-------------- Deployed Processes ----------------------
process.xml -> "process" (version:1)[K01] ------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" id="definitions_a65f6d98-c5aa-42bb-865e-eaa41b502f87" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process" isExecutable="true">
    <startEvent id="startEvent_d45b3f71-2ebc-41ac-95ab-409e3b449aeb">
      <outgoing>sequenceFlow_8af37e75-c4e2-490a-bbfb-0e592293a63b</outgoing>
    </startEvent>
    <parallelGateway id="fork" name="fork">
      <incoming>sequenceFlow_8af37e75-c4e2-490a-bbfb-0e592293a63b</incoming>
      <outgoing>sequenceFlow_d9547e8b-7c1d-4900-b93a-c5c5f17fa29d</outgoing>
      <outgoing>sequenceFlow_0ef583c8-007b-4f93-b5e0-886ab9ca8fc5</outgoing>
    </parallelGateway>
    <sequenceFlow id="sequenceFlow_8af37e75-c4e2-490a-bbfb-0e592293a63b" sourceRef="startEvent_d45b3f71-2ebc-41ac-95ab-409e3b449aeb" targetRef="fork"/>
    <serviceTask id="A" name="A">
      <extensionElements>
        <ns0:taskDefinition type="A"/>
      </extensionElements>
      <incoming>sequenceFlow_d9547e8b-7c1d-4900-b93a-c5c5f17fa29d</incoming>
      <outgoing>sequenceFlow_757a977e-9f8d-46f7-992c-e71067cc3dc7</outgoing>
    </serviceTask>
    <sequenceFlow id="sequenceFlow_d9547e8b-7c1d-4900-b93a-c5c5f17fa29d" sourceRef="fork" targetRef="A"/>
    <endEvent id="endEvent_9ddc6397-b9ee-4484-93e1-096edecaafe6">
      <incoming>sequenceFlow_757a977e-9f8d-46f7-992c-e71067cc3dc7</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_757a977e-9f8d-46f7-992c-e71067cc3dc7" sourceRef="A" targetRef="endEvent_9ddc6397-b9ee-4484-93e1-096edecaafe6"/>
    <serviceTask id="B" name="B">
      <extensionElements>
        <ns0:taskDefinition type="B"/>
      </extensionElements>
      <incoming>sequenceFlow_0ef583c8-007b-4f93-b5e0-886ab9ca8fc5</incoming>
      <outgoing>sequenceFlow_b1043922-f659-4229-b13d-ad82f6420a9f</outgoing>
    </serviceTask>
    <sequenceFlow id="sequenceFlow_0ef583c8-007b-4f93-b5e0-886ab9ca8fc5" sourceRef="fork" targetRef="B"/>
    <endEvent id="endEvent_2263ad9a-69c5-4e0c-a9be-0232c9262e74">
      <incoming>sequenceFlow_b1043922-f659-4229-b13d-ad82f6420a9f</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_b1043922-f659-4229-b13d-ad82f6420a9f" sourceRef="B" targetRef="endEvent_2263ad9a-69c5-4e0c-a9be-0232c9262e74"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_eb58c4df-8390-4253-b6ef-58402d581bc2">
    <bpmndi:BPMNPlane bpmnElement="process" id="BPMNPlane_2217c3b7-4ef9-4ac3-a585-554fa67607a3">
      <bpmndi:BPMNShape bpmnElement="startEvent_d45b3f71-2ebc-41ac-95ab-409e3b449aeb" id="BPMNShape_734126f0-a5b2-41da-8b44-162aac118360">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="fork" id="BPMNShape_41920ba6-8aa5-491a-83c3-2c8d247662c2">
        <dc:Bounds height="50.0" width="50.0" x="186.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_8af37e75-c4e2-490a-bbfb-0e592293a63b" id="BPMNEdge_29831877-0a0b-49de-9e21-e793866dbbcf">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="A" id="BPMNShape_17b679f2-dac5-40f9-acdc-71fca2044293">
        <dc:Bounds height="80.0" width="100.0" x="286.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_d9547e8b-7c1d-4900-b93a-c5c5f17fa29d" id="BPMNEdge_e748554b-a9d8-4661-902c-2ee1c14c4b2f">
        <di:waypoint x="236.0" y="118.0"/>
        <di:waypoint x="286.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="endEvent_9ddc6397-b9ee-4484-93e1-096edecaafe6" id="BPMNShape_0c20f38f-d50a-49a4-9fca-f0ed6d47296a">
        <dc:Bounds height="36.0" width="36.0" x="436.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_757a977e-9f8d-46f7-992c-e71067cc3dc7" id="BPMNEdge_63b3088c-102f-4a8a-b9b7-46dc94d320d4">
        <di:waypoint x="386.0" y="118.0"/>
        <di:waypoint x="436.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="B" id="BPMNShape_a8f0a383-eb58-445a-a08a-322c291f2b1d">
        <dc:Bounds height="80.0" width="100.0" x="286.0" y="208.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_0ef583c8-007b-4f93-b5e0-886ab9ca8fc5" id="BPMNEdge_0b7e79cc-ce11-423a-b937-eb0bfbc5d9ff">
        <di:waypoint x="211.0" y="143.0"/>
        <di:waypoint x="211.0" y="248.0"/>
        <di:waypoint x="286.0" y="248.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="endEvent_2263ad9a-69c5-4e0c-a9be-0232c9262e74" id="BPMNShape_4ab7e991-41e5-4974-a0d1-dc2793945daf">
        <dc:Bounds height="36.0" width="36.0" x="436.0" y="230.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_b1043922-f659-4229-b13d-ad82f6420a9f" id="BPMNEdge_ef0c5cb0-ed2c-47d1-8131-4dba710b04bc">
        <di:waypoint x="386.0" y="248.0"/>
        <di:waypoint x="436.0" y="248.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>


--------------- Decomposed keys (for debugging) -----------------
 -1 <-> -1
K01 <-> 2251799813685249
K02 <-> 2251799813685250
K03 <-> 2251799813685251
K04 <-> 2251799813685252
K05 <-> 2251799813685253
K06 <-> 2251799813685254
K07 <-> 2251799813685255
K08 <-> 2251799813685256
K09 <-> 2251799813685257
K10 <-> 2251799813685258
K11 <-> 2251799813685259
K12 <-> 2251799813685260
K13 <-> 2251799813685261
K14 <-> 2251799813685262
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: `8.1.0`
- Configuration:

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Activating a Parallel Gateway was not possible due to a failing check if the correct amount of active sequence have been taken. This PR will increment the amount of taken sequence upon when the activate instructions contain a parallel gateway. This is done in the `ProcessInstance.MODIFIED` event applier.

One edge case that is not supported with this change is the following scenario:
image
If I want to modify this process by putting an activation on task A and on the joining gateway, the gateway will be activated immediately. Task A will be executed and will start waiting at the gateway again, meaning the process will be stuck). The gateway will not wait for task A before continuing. I could not think of a simple solution to solve this problem.

## Related issues

closes #10518

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ProcessInstanceModificationRecordValue.java [hunk 1]
```diff
@@ -33,7 +33,8 @@
   /** Returns a list of activate instructions (if available), or an empty list. */
   List<ProcessInstanceModificationActivateInstructionValue> getActivateInstructions();
 
-  Set<Long> getActivatedElementInstanceKeys();
+  @Deprecated
```
Comment (saig0) [inline protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ProcessInstanceModificationRecordValue.java:36]: :wrench: For a `@Deprecated` annotation, we should mention which method should be used instead.

File: engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceModifiedEventApplier.java [hunk 2]
```diff
@@ -7,31 +7,74 @@
...
+        elementInstanceState.getInstance(value.getProcessInstanceKey());
+    final var process =
+        processState
+            .getProcessByKey(processInstance.getValue().getProcessDefinitionKey())
+            .getProcess();
+    value
+        .getActivateInstructions()
+        .forEach(
+            instruction -> {
+              final var element = process.getElementById(instruction.getElementId());
```
Comment (saig0) [inline engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceModifiedEventApplier.java:63]: :wrench: We could avoid the casting of the element below by using the following method.

```suggestion
              final var element =
                  process.getElementById(instruction.getElementId(), ExecutableFlowNode.class);
```

File: protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ProcessInstanceModificationRecordValue.java [hunk 3]
```diff
@@ -76,6 +77,9 @@ interface ProcessInstanceModificationActivateInstructionValue {
 
     /** Returns a list of variable instructions (if available), or an empty list. */
     List<ProcessInstanceModificationVariableInstructionValue> getVariableInstructions();
+
+    /** Returns all ancestor scope keys of the element that will be activated. */
```
Comment (saig0) [inline protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ProcessInstanceModificationRecordValue.java:81]: :wrench: We could mention that the property is set only in the event.

For example:

```suggestion
    /**
     * Returns all ancestor scope keys of the element that was activated. The property is set only
     * in the event after the modification is applied.
     */
```

**Review by saig0 — APPROVED** [review]
@remcowesterhoud good job. :+1: 

I have a few minor suggestions. Please have a look.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java [hunk 4]
```diff
@@ -167,6 +168,9 @@ public void processRecord(
       return;
     }
 
+    final var extendedRecord = new ProcessInstanceModificationRecord();
+    extendedRecord.setProcessInstanceKey(value.getProcessInstanceKey());
```
[the remark this answers is not in the document]
Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java:172]: The problem here is that the activate instructions are nested. I have no way to fetch a specific activate instruction from the ArrayProperty, and searching with an iteration will provide me with a copy of the instruction, so modifying this doesn't achieve anything.

If there is a way I'm unaware about please let me know.

[the remark this answers is not in the document]
Comment (saig0) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java:172]: Good point. :smile:

**Comment by remcowesterhoud** [comment]
bors merge
