### PR TITLE
Do not reconfigure default `ObjectMapper` instance

### LINKED ISSUE #25986: [spring-boot-starter-camunda-sdk] JsonMapperConfiguration reconfigures standard Spring ObjectMapper instance
**Describe the bug**

When using `spring-boot-starter-camunda-sdk` in an application that uses _Spring Web_, the default `ObjectMapper` instance provided by Spring Boot Autoconfiguration is reconfigured.

**To Reproduce**

Add `spring-boot-starter-camunda-sdk` to a Spring Application that provides a `@RestController`. If the returned entity contains a property with a `null` value, it is removed from the serialised JSON response.

**Expected behavior**

`spring-boot-starter-camunda-sdk` should use its own instance of `ObjectMapper` and not pollute the default instance.

**References**

- Camunda SDK recieves the default ObjectMapper instance [here](https://github.com/camunda/camunda/blob/main/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/configuration/JsonMapperConfiguration.java#L32)
- Camunda SDK reconfigures it [here](https://github.com/camunda/camunda/blob/main/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/common/json/SdkObjectMapper.java#L39)

**Environment:**
- spring-boot-starter-camunda-sdk Version: 8.5.x

### PR DESCRIPTION
**Pull request by ana-vinogradova-camunda**
We should not reconfigure the default ObjectMapper instance provided by Spring Boot Autoconfiguration.
Related to [this issue](https://github.com/camunda/camunda/issues/25986)

In this PR:
- use `objectMapper.copy()` instead of `objectMapper`
- added a test to verify it works as expected now

I will backport this change in subsequent PRs.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

closes #25986

### CODE REVIEW

File: clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/configuration/JsonMapperConfiguration.java [hunk 1]
```diff
@@ -38,6 +38,6 @@ public JsonMapper jsonMapper() {
     if (objectMapper == null) {
       return new CamundaObjectMapper();
     }
-    return new CamundaObjectMapper(objectMapper);
+    return new CamundaObjectMapper(objectMapper.copy());
```
Comment (megglos) [inline clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/configuration/JsonMapperConfiguration.java:41]: 💭 I generally wonder what the use case of reusing an existing object mapper from the context would be 🤔  given this one is used only for the Orchestration/C8 API, I see no use case for a user to want to use a custom configuration here. The other way around any change done on the mapper passed in here, potentially unexpectedly, could be incompatible with the camunda client/api and actually cause issues. Wdyt?

@jonathanlukas would be interested in your feedback as you have insights and experience with the community sdk

Comment (ana-vinogradova-camunda) [reply clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/configuration/JsonMapperConfiguration.java:41]: Community SDK fix can be viewed [here](https://github.com/camunda-community-hub/spring-zeebe/pull/804).

Comment (ana-vinogradova-camunda) [reply clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/configuration/JsonMapperConfiguration.java:41]: @megglos this fix is in line with the community approach so I think this would create less confusion for users. I'd be happy to get feedback from @jonathanlukas 👍

Comment (jonathanlukas) [reply clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/configuration/JsonMapperConfiguration.java:41]: I am not 100% sure, but from my perspective, it looks like that the developer would be able to use a custom `ObjectMapper` in case their implementation would require it.

But: This could also be done by providing an own bean `camundaJsonMapper`.

Maybe this is over-engineered..

Comment (megglos) [reply clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/configuration/JsonMapperConfiguration.java:41]: @ana-vinogradova-camunda apologies for the misunderstanding, I'm fine doing it, given it's aligned with how the community sdk treated it. Some users may even expect it to be like that. I wanted to understand better on why it was designed that way as I could also imagine this to cause unexpected issues, if a global mapper object is configured in a special way and that actually conflicts with the camunda client/API and it's not clear to the user that the camunda SDK automatically reuses existing object mapper setups present in the context.

> I am not 100% sure, but from my perspective, it looks like that the developer would be able to use a custom ObjectMapper in case their implementation would require it.

Thanks, I lack to understand what a user would customize for the object mapper for the C8 API, which is out of their control.

> Some companies have their own frameworks where they are using a pre-configured ObjectMapper and this would be applied here.

I get that users will setup their own mapper with custom settings for their own APIs but I would assume it's unexpected that that one is reused automatically for the Camunda APIs as well. However I lack to understand how likely that will actually cause issues, we could adjust it still then by e.g. requiring a special bean name for the preconfigured mapper to get picked up.

Thanks both!

**Review by megglos — APPROVED** [review]
Thanks for quickly following up and creating the fix 🚀 🙇 

Pre-approving for you to only have to tame the CI 😅
