### PR TITLE
fix: set the groupKey correctly when update a group

### LINKED ISSUE #31578: [Groups API] groupKey is set to '-1' after update request
### 

### 

### 

### 

### Description

groupKey is set to '-1' after update request

### Steps to reproduce

1. update an existing group
2. check response body

### Current behavior

`{
  "groupId": "testGroup12",
  "name": "TestGroup1 Updated",
  "description": "An updated test group description.",
  "groupKey": "-1"
} `

### Expected behavior

the actual groupKey should be returned

### Environment

SM

### Version

- Component Version: [8.8]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

The `groupKey` wasn't set in the record processed by the engine

## Related issues

closes #31578

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/GroupUpdateProcessor.java [hunk 1]
```diff
@@ -92,4 +92,32 @@ public void processDistributedCommand(final TypedRecord<GroupRecord> command) {
...
+      final PersistedGroup persistedGroup, final GroupRecord updateRecord) {
+    final var updatedName = updateRecord.getName();
+    if (!updatedName.isEmpty()) {
+      persistedGroup.setName(updatedName);
+    }
+    final var updatedDescription = updateRecord.getDescription();
+    if (!updatedDescription.isEmpty()) {
+      persistedGroup.setDescription(updatedDescription);
+    }
+  }
```
Comment (ana-vinogradova-camunda) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/GroupUpdateProcessor.java:106]: ❓ Just for my own understanding - we are setting `name` and `description` here, but the `groupKey` will be taken from `persistedGroup` as it is not present in `updateRecord`?

**Review by ana-vinogradova-camunda — APPROVED** [review]
👍 The change looks good to me. 
❓ Just one question: are there any tests that verify this updated behaviour?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/GroupUpdateProcessor.java (hunk 1 above)
Comment (nicpuppa) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/GroupUpdateProcessor.java:106]: Yes correct
