### PR TITLE
fix: prevent NPE for SendTask with publish message implementation

### LINKED ISSUE #34190: NPE at evaluation of job worker properties of Send Task with Publish Message implementation
### 

### 

### 

### 

### Description

Our BPMN model API allows modeling a Send Task with publish message implementation, while this is not yet supported by the engine. However, the engine accepts it as if it can and then encounters an NPE during activation of the Send Task element.

### Steps to reproduce

See test case: https://github.com/camunda/camunda/issues/34190#issuecomment-2999589676

### Current behavior

An NPE is thrown when trying to evaluate null job worker properties.

### Expected behavior

To resolve this, we need to align SendTask processing to BusinessRuleTask processing, using a `JobWorkerTaskSupportingProcessor`. This allows specifying different implementations (job worker based and publish message based). For the publish message based implementation, we'd need to raise an incident, stating that this is not yet supported. We should also reject deployments of processes with this unsupported send task implementation for now.

### Environment

SaaS & SM

### Version

- Component Version: 8.8.0-alpha5

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

- https://console.cloud.google.com/errors/detail/CODnt5XX2J3wJQ;service=zeebe;time=P7D;locations=global?inv=1&invt=Ab06SA&project=camunda-saas-prod-sin
-

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

This PR prevent a `NullPointerException` when a Send Task is modeled with a publish-message implementation (that is not supported yet). Instead of crashing on activation, the engine now creates a clear incident and allows the instance to be terminated cleanly.

### What changed:
- Introduced a dedicated `SendTaskProcessor` (with `ExecutableSendTask`).
- If job-worker properties are present -> proceed as usual.
- If they’re missing (publish-message path) -> raise an incident with a helpful message.
- Implemented proper termination for this path (cancel related work, resolve incident, transition to `TERMINATED`).
- Added tests for incident creation and successful termination.

#### ErrorType
- Uses `ErrorType.UNKNOWN` for now (based on a [quick discussion](https://camunda.slack.com/archives/C08G19SQ1BM/p1756991336652469) we agreed a new error type is not needed at this point).

### Next
- A separate PR will improve validation to reject Send Tasks with a publish-message implementation at deployment time.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #34190

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/task/SendTaskProcessor.java [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+import io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBehaviors;
+import io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnIncidentBehavior;
+import io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnJobBehavior;
+import io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior;
+import io.camunda.zeebe.engine.processing.common.Failure;
+import io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableSendTask;
+import io.camunda.zeebe.protocol.record.value.ErrorType;
+import io.camunda.zeebe.util.Either;
+
+public final class SendTaskProcessor extends JobWorkerTaskSupportingProcessor<ExecutableSendTask> {
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/task/SendTaskProcessor.java:20]: 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/SendTaskTest.java [hunk 2]
```diff
@@ -0,0 +1,177 @@
...
+import io.camunda.zeebe.protocol.record.intent.ProcessInstanceIntent;
+import io.camunda.zeebe.protocol.record.value.ErrorType;
+import io.camunda.zeebe.test.util.record.RecordingExporter;
+import io.camunda.zeebe.test.util.record.RecordingExporterTestWatcher;
+import org.junit.ClassRule;
+import org.junit.Rule;
+import org.junit.Test;
+import org.junit.rules.TestWatcher;
+
+public final class SendTaskTest {
```
Comment (mustafadagher) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/SendTaskTest.java:26]: 👍

**Review by mustafadagher — APPROVED** [review]
Looks great @ce-dmelnych 🚀 

It took me a while to notice that the `internal` methods are called from the parent class if `isJobBehavior()` was false. 💭 Not sure if maybe a javadoc would have helped..

But otherwise, the changes are clear, and the tests made it easy to follow the logic.

Thanks
