### PR TITLE
fix: skip dynamic property mappings in Index validation

### LINKED ISSUE #34478: Index validation wrongly applied to dynamic properties
### 

### 

### 

### 

### Description

We observed the reoccurrence of https://github.com/camunda/camunda/issues/27022

### Steps to reproduce

1. Start a user task with customHeaders
2. Restart any of the orchestration pods

### Current behavior

```
Index name: tasklist-task-8.5.0_. Not supported index changes are introduced. Data migration is required. Changes found: [PropertyDifference[name=customHeaders, leftValue=IndexMappingProperty{name='customHeaders', typeDefinition={dynamic=true[Boolean], type=object[String]}}, rightValue=IndexMappingProperty{name='customHeaders', typeDefinition={dynamic=true[Boolean], type=object[String], properties={test4={type=text, fields={keyword={type=keyword, ignore_above=256}}}, test2={type=text, fields={keyword={type=keyword, ignore_above=256}}}, test={type=text, fields={keyword={type=keyword, ignore_above=256}}}}[LinkedHashMap]}}]]
```

### Expected behavior

The `customHeader` property should be ignored as it has a dynamic mapping

### Environment

SaaS & SM

### Version

- Component Version: 8.8.0-alpha6-rc1

### Rootcause

Most likely after switching to the common schema manager, the fix made for https://github.com/camunda/camunda/issues/27022 was not retrofitted from Tasklist

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

This pull request handles dynamic property differences in index mappings, ensuring they are ignored during schema validation if all differences pertain to dynamic properties. It also includes a new test to verify this behavior. 

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #34478

### CODE REVIEW

File: schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java [hunk 1]
```diff
@@ -970,4 +970,83 @@ void shouldNotRecordSchemaInitTimerMetricOnFailure(
...
+    final var runtimeIndexName = indexTemplate.getFullQualifiedName();
+    final var archiveIndexName1 = indexTemplate.getIndexPattern().replace("*", "-archived_1");
+    final var archiveIndexName2 = indexTemplate.getIndexPattern().replace("*", "-archived_2");
+
+    // index some data to the runtime and archive indices. "world" is a dynamic property
+    searchClientAdapter.index(
+        "123", runtimeIndexName, Map.of("hello", "a", "world", Map.of("header1", 1, "header2", 2)));
+    searchClientAdapter.index(
+        "123", archiveIndexName1, Map.of("hello", "a", "world", Map.of("header3", true)));
+    searchClientAdapter.index("123", archiveIndexName2, Map.of("hello", "a"));
```
Comment (panagiotisgts) [inline schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java:1013]: Nitpick, can maybe use some more defining name for the index fields to be self-descriptive since they are constantly referred to as strings and it requires some more lookups to match them :upside_down_face:

**Review by panagiotisgts — APPROVED** [review]
:rocket: Pre-approving, a minor suggestion and something I noticed: 
- I removed your change on the `IndexSchemaValidator` and run the test to verify it fails, the test kept running forever. It was on the ~5min mark when i stopped it.
- Can we also include another test case with the validation failing on a non-dynamic field, for sanity?

File: schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java (hunk 1 above)
Comment (houssain-barouni) [reply schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java:1013]: you are right! you have to check the json to understand what is going on
I think I will do this in a future PR to improve these tests

**Comment by houssain-barouni** [comment]
> 🚀 Pre-approving, a minor suggestion and something I noticed:
> 
> * I removed your change on the `IndexSchemaValidator` and run the test to verify it fails, the test kept running forever. It was on the ~5min mark when i stopped it.

Yes, now the schema manager retries for ever, to avoid crashlooping when ES not ready. But probably we need to distinguish this case where it cannot recover by itself , like in this situation :/ 

> * Can we also include another test case with the validation failing on a non-dynamic field, for sanity?

we have a bunch of test in IndexSchemaValidatorTest, I will check if I can add new ones with dynamic properties

**Comment by houssain-barouni** [comment]
@panagiotisgts after writing new tests, I figured out that I need to also handle the entries in common, since they are also expected to be the same

This happens, for example, with dated indices that don't have customHeaders. These indices will have an extra entryInCommon in the expected mapping compared to other dated indices that do include customHeaders.

File: schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java [hunk 2]
```diff
@@ -970,4 +970,87 @@ void shouldNotRecordSchemaInitTimerMetricOnFailure(
     assertThat(measuredTime.count()).isEqualTo(0);
     assertThat(measuredTime.totalTime(TimeUnit.MILLISECONDS)).isEqualTo(0);
   }
+
+  @TestTemplate
+  void shouldSkipDynamicPropertyMappingsDifferences(
+      final SearchEngineConfiguration config, final SearchClientAdapter searchClientAdapter)
+      throws IOException {
+    // given
+    // in Opensearch, "dynamic" field is stored String, while in Elasticsearch it is saved as
```
Comment (panagiotisgts) [inline schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java:979]: Had forgotten about this incompatibility :1st_place_medal:

**Review by panagiotisgts — APPROVED** [review]
