### PR TITLE
Write an event if a decision evaluation failed

### LINKED ISSUE #8235: Write an event if a decision evaluation failed
**Description**

If a business rule task is activated and the evaluation of a decision fails (e.g. missing variables, unexpected variable type, etc.) then we should create an incident. Additionally, we should write an event that reflects the partial evaluation of the decision. It may helps the user to understand what went wrong.

* write the same event as defined in #8115
* create a new intent `failed`
* add a new property `evaluationFailure` that contains the failure message 
* it should include context data about the process instance that the decision is called from    
* it should include all available data about the evaluation that is provided from the DMN module 
  * if a required decision was evaluated successfully then it should include the result
  * if a decision table was evaluated and the inputs were evaluated successfully then it should include the input values
* the last decision result in the list should indicate the failed decision 
* add a new property `failedDecisionId` that contains the id of the failed decision

blocked by #8115 
blocked by #8095

### PR DESCRIPTION
**Pull request by saig0**
## Description

* add new intent `FAILED` for decision evaluations that are not successful
* extend the decision evaluation record to expose `evaluationFailure` and `failedDecisionId` for failed decisions 
* write a decision evaluation event if the evaluation of the decision failed
* adjust the ES template

## Related issues

closes #8235 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

File: dmn/src/main/java/io/camunda/zeebe/dmn/impl/DmnScalaDecisionEngine.java [hunk 1]
```diff
@@ -106,8 +106,15 @@ public DecisionEvaluationResult evaluateDecisionById(
 
     if (result.isLeft()) {
       final var reason = result.left().get().failure().message();
+
+      String failedDecisionId = null;
+      if (!evaluatedDecisions.isEmpty()) {
+        failedDecisionId = evaluatedDecisions.get(evaluatedDecisions.size() - 1).decisionId();
+      }
```
Comment (saig0) [inline dmn/src/main/java/io/camunda/zeebe/dmn/impl/DmnScalaDecisionEngine.java:113]: :thought_balloon: In Scala, we could write:

```
val failedDecisionId = evaluatedDecisions.lastOption.orNull
``` 

I don't see an easy functional way in Java :disappointed:

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnDecisionBehavior.java [hunk 2]
```diff
@@ -89,7 +89,24 @@ public BpmnDecisionBehavior(
...
+
+                  if (evaluationResult.isFailure()) {
+                    return Either.left(
+                        new Failure(
+                            evaluationResult.getFailureMessage(),
+                            ErrorType.CALLED_ELEMENT_ERROR,
+                            scopeKey));
+                  } else {
+                    return Either.right(evaluationResult);
+                  }
```
Comment (saig0) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnDecisionBehavior.java:108]: :thought_balloon: The code looks nicer if the `Either` mapping is hidden inside the function. But on the other side, I don't want to hide the writing of the evaluation event because it is an important part.

**Comment by saig0** [comment]
I did a manual test to verify the ES record :heavy_check_mark: 

```
"_source": {
    "partitionId": 1,
    "value": {
      "bpmnProcessId": "dmn-force-user",
      "decisionRequirementsId": "force-users",
      "decisionRequirementsKey": 2251799813685295,
      "decisionId": "force_user",
      "decisionName": "Which force user?",
      "decisionKey": 2251799813685297,
      "processDefinitionKey": 2251799813685293,
      "processInstanceKey": 2251799813685311,
      "elementInstanceKey": 2251799813685315,
      "elementId": "Activity_1dprsnb",
      "decisionVersion": 2,
      "decisionOutput": "null",
      "evaluatedDecisions": [
        {
          "decisionId": "jedi_or_sith",
          "decisionName": "Jedi or Sith",
          "decisionOutput": "null",
          "decisionType": "DECISION_TABLE",
          "evaluatedInputs": [],
          "matchedRules": []
        }
      ],
      "evaluationFailureMessage": "Expected to evaluate decision 'force_user', but failed to evaluate expression 'lightsaberColor': no variable found for name 'lightsaberColor'",
      "failedDecisionId": "jedi_or_sith"
    },
    "key": 2251799813685316,
    "timestamp": 1645511341416,
    "intent": "FAILED",
    "rejectionType": "NULL_VAL",
    "rejectionReason": "",
    "brokerVersion": "1.4.0",
    "sourceRecordPosition": 160,
    "position": 162,
    "valueType": "DECISION_EVALUATION",
    "recordType": "EVENT"
  },
```

<details>
<summary>Full ES record</summary>
<pre>
{
  "_index": "zeebe-record_decision-evaluation_1.4.0-snapshot_2022-02-22",
  "_type": "_doc",
  "_id": "1-162",
  "_version": 1,
  "_score": 1,
  "_routing": "1",
  "_source": {
    "partitionId": 1,
    "value": {
      "bpmnProcessId": "dmn-force-user",
      "decisionRequirementsId": "force-users",
      "decisionRequirementsKey": 2251799813685295,
      "decisionId": "force_user",
      "decisionName": "Which force user?",
      "decisionKey": 2251799813685297,
      "processDefinitionKey": 2251799813685293,
      "processInstanceKey": 2251799813685311,
      "elementInstanceKey": 2251799813685315,
      "elementId": "Activity_1dprsnb",
      "decisionVersion": 2,
      "decisionOutput": "null",
      "evaluatedDecisions": [
        {
          "decisionId": "jedi_or_sith",
          "decisionName": "Jedi or Sith",
          "decisionOutput": "null",
          "decisionType": "DECISION_TABLE",
          "evaluatedInputs": [],
          "matchedRules": []
        }
      ],
      "evaluationFailureMessage": "Expected to evaluate decision 'force_user', but failed to evaluate expression 'lightsaberColor': no variable found for name 'lightsaberColor'",
      "failedDecisionId": "jedi_or_sith"
    },
    "key": 2251799813685316,
    "timestamp": 1645511341416,
    "intent": "FAILED",
    "rejectionType": "NULL_VAL",
    "rejectionReason": "",
    "brokerVersion": "1.4.0",
    "sourceRecordPosition": 160,
    "position": 162,
    "valueType": "DECISION_EVALUATION",
    "recordType": "EVENT"
  },
  "fields": {
    "value.decisionKey": [
      2251799813685297
    ],
    "value.evaluatedDecisions.decisionOutput": [
      "null"
    ],
    "sourceRecordPosition": [
      160
    ],
    "value.decisionRequirementsId": [
      "force-users"
    ],
    "rejectionType": [
      "NULL_VAL"
    ],
    "value.decisionVersion": [
      2
    ],
    "valueType": [
      "DECISION_EVALUATION"
    ],
    "value.decisionId": [
      "force_user"
    ],
    "value.elementId": [
      "Activity_1dprsnb"
    ],
    "key": [
      2251799813685316
    ],
    "timestamp": [
      "2022-02-22T06:29:01.416Z"
    ],
    "value.processInstanceKey": [
      2251799813685311
    ],
    "value.elementInstanceKey": [
      2251799813685315
    ],
    "value.decisionRequirementsKey": [
      2251799813685295
    ],
    "value.decisionOutput": [
      "null"
    ],
    "value.processDefinitionKey": [
      2251799813685293
    ],
    "partitionId": [
      1
    ],
    "recordType": [
      "EVENT"
    ],
    "value.decisionName": [
      "Which force user?"
    ],
    "value.failedDecisionId": [
      "jedi_or_sith"
    ],
    "brokerVersion": [
      "1.4.0"
    ],
    "intent": [
      "FAILED"
    ],
    "value.bpmnProcessId": [
      "dmn-force-user"
    ],
    "value.evaluatedDecisions.decisionName": [
      "Jedi or Sith"
    ],
    "value.evaluatedDecisions.decisionId": [
      "jedi_or_sith"
    ],
    "value.evaluatedDecisions.decisionType": [
      "DECISION_TABLE"
    ],
    "value.evaluationFailureMessage": [
      "Expected to evaluate decision 'force_user', but failed to evaluate expression 'lightsaberColor': no variable found for name 'lightsaberColor'"
    ],
    "position": [
      162
    ],
    "rejectionReason": [
      ""
    ]
  }
}
</pre>
</details>

File: dmn/src/main/java/io/camunda/zeebe/dmn/impl/DmnScalaDecisionEngine.java (hunk 1 above)
Comment (korthout) [reply dmn/src/main/java/io/camunda/zeebe/dmn/impl/DmnScalaDecisionEngine.java:113]: Not as pretty, but:
```java
evaluatedDecisions.stream()
    .reduce((a, b) -> b)
    .map(EvaluatedDecision::decisionId)
    .orElse(null)
```

Comment (korthout) [reply dmn/src/main/java/io/camunda/zeebe/dmn/impl/DmnScalaDecisionEngine.java:113]: You could also consider a util method, like suggested [here](https://stackoverflow.com/a/55593682)

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/BusinessRuleTaskTest.java [hunk 3]
```diff
@@ -334,4 +336,86 @@ public void shouldWriteDecisionEvaluationEvent() {
...
+                processWithBusinessRuleTask(
+                    t ->
+                        t.zeebeCalledDecisionId("force_user").zeebeResultVariable(RESULT_VARIABLE)))
+            .deploy();
+
+    final var calledDecision =
+        deployment.getValue().getDecisionsMetadata().stream()
+            .filter(decision -> decision.getDecisionId().equals("force_user"))
+            .findFirst()
+            .orElseThrow();
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/BusinessRuleTaskTest.java:357]: 💭 This is probably something that we (and users potentially as well) will have to do more often. We could consider adding a convenience method for this if we encounter it more often.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/BusinessRuleTaskTest.java [hunk 4]
```diff
@@ -334,4 +336,86 @@ public void shouldWriteDecisionEvaluationEvent() {
...
+
+    final var decisionEvaluationValue = decisionEvaluationRecord.getValue();
+    assertThat(decisionEvaluationValue)
+        .hasDecisionKey(calledDecision.getDecisionKey())
+        .hasDecisionId(calledDecision.getDecisionId())
+        .hasDecisionName(calledDecision.getDecisionName())
+        .hasDecisionVersion(calledDecision.getVersion())
+        .hasDecisionRequirementsKey(calledDecision.getDecisionRequirementsKey())
+        .hasDecisionRequirementsId(calledDecision.getDecisionRequirementsId())
+        .hasDecisionOutput("null")
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/BusinessRuleTaskTest.java:391]: ❓ Perhaps I misunderstand it, but should this be the string value `"null"`? I thought this should actually be `null`. (Sorry for mentioning this topic twice, but since I encountered it here again, I wanted to make sure we address it).

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnDecisionBehavior.java (hunk 2 above)
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnDecisionBehavior.java:108]: 💭 Currently the writeDecisionEvaluationEvent (which is a side-effect) happens inside the flatmap. It could be an idea to extract that to an ifRight. Something like:

```java
public Either<Failure, DecisionEvaluationResult> evaluateDecision(
    final ExecutableCalledDecision element, final BpmnElementContext context) {
  final var scopeKey = context.getElementInstanceKey();

  // todo(#8571): avoid parsing drg every time
  final var decisionOrFailure = findDecisionById(element.getDecisionId());
  final var resultOrFailure =
      decisionOrFailure
          .flatMap(this::findDrgByDecision)
          .mapLeft(
              failure ->
                  new Failure(
                      "Expected to evaluate decision '%s', but %s"
                          .formatted(element.getDecisionId(), failure.getMessage())))
          .flatMap(drg -> parseDrg(drg.getResource()))
          // all the above failures have the same error type and the correct scope
          .mapLeft(f -> new Failure(f.getMessage(), ErrorType.CALLED_DECISION_ERROR, scopeKey))
          .map(drg -> evaluateDecisionInDrg(drg, element.getDecisionId(), scopeKey));

  resultOrFailure.ifRight(
      evaluationResult -> {
        final var decision = decisionOrFailure.get();
        writeDecisionEvaluationEvent(decision, evaluationResult, context);
      });

  // todo: could have a better name
  final var evaluatedResultOrFailure =
      resultOrFailure.flatMap(
          evaluationResult -> {
            if (evaluationResult.isFailure()) {
              return Either.left(
                  new Failure(
                      evaluationResult.getFailureMessage(),
                      ErrorType.CALLED_ELEMENT_ERROR,
                      scopeKey));
            } else {
              return Either.right(evaluationResult);
            }
          });

  evaluatedResultOrFailure.ifRight(
      result -> {
        // The output mapping behavior determines what to do with the decision result. Since the
        // output mapping may fail and raise an incident, we need to write the variable to a
        // record. This is because we want to evaluate the decision on element activation, while
        // the output mapping happens on element completion. We don't want to re-evaluate the
        // decision for output mapping related incidents.
        triggerProcessEventWithResultVariable(context, element.getResultVariable(), result);
      });

  return evaluatedResultOrFailure;
}
```

**Review by korthout — COMMENTED** [review]
Thanks @saig0 Looking good 👍 

I have some questions, which should be discussed before merging. Please have a look.

File: protocol/src/main/java/io/camunda/zeebe/protocol/record/value/DecisionEvaluationRecordValue.java [hunk 5]
```diff
@@ -64,4 +64,25 @@
...
+  String getEvaluationFailureMessage();
+
+  /**
+   * If the evaluation of the decision failed then it returns the id of the decision where the
+   * evaluation failed. It can be the called/root decision or any of its required decisions. The
+   * reason of the failure can be retrieved as {@link #getEvaluationFailureMessage() evaluation
+   * failure message}. The decision id is not available if the decision was evaluated successfully.
+   *
+   * @return the id of the decision in the DMN where the evaluation failed, or an empty string if
+   *     the evaluation was successful
```
[the remark this answers is not in the document]
Comment (saig0) [reply protocol/src/main/java/io/camunda/zeebe/protocol/record/value/DecisionEvaluationRecordValue.java:85]: In general, I would agree. But we are talking here about a record value. For record values, it is common to return an empty string. For example, the error message of a [job record](https://github.com/camunda-cloud/zeebe/blob/main/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/job/JobRecord.java#L49-L50).

The reasoning for an empty string is mainly a limitation in our message pack library for the records. 

IMO, it is okay to follow the current design.

File: protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/decision/DecisionEvaluationRecord.java [hunk 6]
```diff
@@ -47,6 +51,10 @@
   private final ArrayProperty<EvaluatedDecisionRecord> evaluatedDecisionsProp =
       new ArrayProperty<>("evaluatedDecisions", new EvaluatedDecisionRecord());
 
+  private final StringProperty evaluationFailureMessageProp =
+      new StringProperty("evaluationFailureMessage", "");
+  private final StringProperty failedDecisionIdProp = new StringProperty("failedDecisionId", "");
```
[the remark this answers is not in the document]
Comment (saig0) [reply protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/decision/DecisionEvaluationRecord.java:56]: > than other id properties
Which other properties do you mean?

In the [job record](https://github.com/camunda-cloud/zeebe/blob/main/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/job/JobRecord.java#L54-L60), I see that we also use empty strings for id properties.

File: protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java [hunk 7]
```diff
@@ -848,7 +850,30 @@ void shouldConvertJsonSerializableToJson(
...
+      },
+
+      /////////////////////////////////////////////////////////////////////////////////////////////
+      ///////////////////////////////// Empty DecisionEvaluationRecord ////////////////////////////
+      /////////////////////////////////////////////////////////////////////////////////////////////
+      {
+        "Empty DecisionEvaluationRecord",
+        (Supplier<UnifiedRecordValue>)
+            () ->
```
[the remark this answers is not in the document]
Comment (saig0) [reply protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java:907]: The purpose of this test class is to verify that the records are serialized to JSON in the expected format. Usually, there are two cases: 
* record with all properties set  
* record with required properties set only

The second case verifies basically the default values.

File: protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java [hunk 8]
```diff
@@ -848,7 +850,30 @@ void shouldConvertJsonSerializableToJson(
...
+                    .setDecisionVersion(1)
+                    .setDecisionRequirementsKey(2L)
+                    .setDecisionRequirementsId("decision-requirements-id")
+                    .setProcessDefinitionKey(3L)
+                    .setBpmnProcessId("bpmn-process-id")
+                    .setDecisionVersion(1)
+                    .setProcessInstanceKey(4L)
+                    .setElementInstanceKey(5L)
+                    .setElementId("element-id"),
+        "{'decisionKey':1,'decisionId':'decision-id','decisionName':'decision-name','decisionVersion':1,'decisionRequirementsKey':2,'decisionRequirementsId':'decision-requirements-id','decisionOutput':'null','processDefinitionKey':3,'bpmnProcessId':'bpmn-process-id','processInstanceKey':4,'elementInstanceKey':5,'elementId':'element-id','evaluatedDecisions':[],'evaluationFailureMessage':'','failedDecisionId':''}"
```
[the remark this answers is not in the document]
Comment (saig0) [reply protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java]: Yes, it should. Like for other records, the decision output is returned as a string representation of a JSON value. So, the JSON value (e.g. `null`) is wrapped into a string (e.g. `"null"`).

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/BusinessRuleTaskTest.java (hunk 3 above)
Comment (saig0) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/BusinessRuleTaskTest.java:357]: Sure. Let's keep an eye open.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/BusinessRuleTaskTest.java (hunk 4 above)
Comment (saig0) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/BusinessRuleTaskTest.java:391]: Same as above. 

The value is a string representation of a JSON value. So, it is actually `null`.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnDecisionBehavior.java (hunk 2 above)
Comment (saig0) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnDecisionBehavior.java:108]: It is an interesting idea. Thank you for sharing.
But I'm not sure if it make the code more or less readable :sweat_smile:

File: protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (korthout) [reply protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java:907]: 🔧 In that case, please rename the test case to `Required properties only DecisionEvaluationRecord`

**Review by korthout — APPROVED** [review]
Thanks for addressing my concerns @saig0 LGTM 🚁

**Comment by saig0** [comment]
bors merge
