### PR TITLE
Importers Completion rework

### LINKED ISSUE #40267: Importers not completing
### 

### 

### 

### 

### Description

For idling clusters updating from 8.7 to 8.8 there is a chance that the importers are not being marked as completed for one of the partitions. This can happen either on Operate and/or Tasklist. We make use of `zeebe-record_tenant` importing to flag idling clusters as completing.

Seems like due to this being concurrent the completion mechanism breaks from time to time leaving partitions non-completed even though they have received an 8.8 record.

Previous [fix attempt](https://github.com/camunda/camunda/pull/39438) based on [this](https://camunda.slack.com/archives/C09J1F6NJJ0/p1760121660045499?thread_ts=1760098570.050819&cid=C09J1F6NJJ0) assumption

There was also a cluster which had all `*-tenant` documents marked as completed but not rest of the documents for some of the partitions in the `import-position` for Operate

### Steps to reproduce

Must be a multi-partition idling cluster

### Current behavior

Import position partitions left non completed, blocking `data-migration` job from completing.

### Expected behavior

When a partition importer receives an 8.8 record it's guaranteed to be completed.

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS

### Version

- Component Version: 8.8

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

There is a scenario where the importers never complete this is due to 

Upgrade from 8.7 to 8.8 (I created an 8.8 SaaS generation with the environment override CAMUNDA_OPERATE_IMPORTER_COMPLETEDREADERMINEMPTYBATCHES=1000. I will explain why below)
Wait for the importer to import the tenant.
Wait for the importer to flush the tenant's import position to Elasticsearch.
At this point, the position is flushed with completed=false since completedReaderMinEmptyBatches has not yet been reached (set too 1000).
Remove the CAMUNDA_OPERATE_IMPORTER_COMPLETEDREADERMINEMPTYBATCHES override (it will reset to the default value of 5).
Restart the Operate importer.
The import position stays stuck with completed=false.

Root Cause

The transition to completed=true in the import-position is conditional on two factors:
New 8.8 records being detected, and
The completedReaderMinEmptyBatches threshold being reached.

-----------------

This should fix as now completion logic relies on the fact that an 8.8 tenant record has been imported and then the same empty batch logic which as also been reduced to 1.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #40267

### CODE REVIEW

File: operate/common/src/main/java/io/camunda/operate/property/ImportProperties.java [hunk 1]
```diff
@@ -18,7 +18,7 @@ public class ImportProperties {
   private static final int DEFAULT_SCHEDULER_BACKOFF = 5000;
   private static final int DEFAULT_FLOW_NODE_TREE_CACHE_SIZE = 1000;
   private static final int DEFAULT_MAX_EMPTY_RUNS = 10;
-  private static final int DEFAULT_MINIMUM_EMPTY_BATCHES_FOR_COMPLETED_READER = 5;
```
Comment (panagiotisgts) [inline operate/common/src/main/java/io/camunda/operate/property/ImportProperties.java:21]: I'd like a reminder of why we have opted for `5` to begin with. Could we be braking something here?

File: operate/importer/src/main/java/io/camunda/operate/zeebeimport/elasticsearch/ElasticsearchRecordsReader.java [hunk 2]
```diff
@@ -602,6 +602,23 @@ private void markRecordReaderCompletedIfMinimumEmptyBatchesReceived() {
     }
   }
 
+  private boolean isPartitionCompletedImporting(final int partitionId) {
+    try {
+      final var tenantImportPosition =
+          importPositionHolder.getLatestLoadedPosition(
+              ImportValueType.TENANT.getAliasTemplate(), partitionId);
```
Comment (panagiotisgts) [inline operate/importer/src/main/java/io/camunda/operate/zeebeimport/elasticsearch/ElasticsearchRecordsReader.java]: ❓ Why couple it only to the `tenant` records? Couldn't we do the same for all value types? We only care if at least one value type has _seen_ an 8.8 record right?

Not sure I'm fond of this coupling to the `tenant` records. Tenants were only included in the importer completion scenario to assist on idling clusters. That way we are also coupling the data-migration to the identity-migration for non idling clusters I think 💭

**Review by panagiotisgts — COMMENTED** [review]
Some thoughts from my end to discuss further

File: operate/importer/src/main/java/io/camunda/operate/zeebeimport/elasticsearch/ElasticsearchRecordsReader.java (hunk 2 above)
Comment (EuroLew) [reply operate/importer/src/main/java/io/camunda/operate/zeebeimport/elasticsearch/ElasticsearchRecordsReader.java]: ah ok I was confused I thought the only way we are doing it was tenant records but if its only for idle clusters then yes all record types should trigger it

File: operate/common/src/main/java/io/camunda/operate/property/ImportProperties.java (hunk 1 above)
Comment (EuroLew) [reply operate/common/src/main/java/io/camunda/operate/property/ImportProperties.java:21]: there was no big reason other than making sure the reader is actually completed. 1 should be fine.

File: operate/importer/src/main/java/io/camunda/operate/zeebeimport/elasticsearch/ElasticsearchRecordsReader.java [hunk 3]
```diff
@@ -602,6 +607,41 @@ private void markRecordReaderCompletedIfMinimumEmptyBatchesReceived() {
...
+    final var importPositionFutures =
+        Arrays.stream(ImportValueType.IMPORT_VALUE_TYPES)
+            .map(
+                valueType ->
+                    CompletableFuture.supplyAsync(
+                        () -> getLatestLoadedPosition(valueType, partitionId),
+                        importerCompletionExecutor))
+            .toList();
+
+    CompletableFuture.allOf(importPositionFutures.toArray(new CompletableFuture[0])).join();
```
Comment (panagiotisgts) [inline operate/importer/src/main/java/io/camunda/operate/zeebeimport/elasticsearch/ElasticsearchRecordsReader.java]: 🔧  Better do this as an aggregate for the partition to extract if any value type is already completed. If there is a _relatively large_ 8.7 backlog this would delay further the importer completion to execute _N_ queries in Elasticsearch per import round.

File: operate/importer/src/main/java/io/camunda/operate/zeebeimport/ImportConfig.java [hunk 4]
```diff
@@ -46,4 +46,14 @@ public ThreadPoolTaskScheduler getImportPositionUpdateTaskExecutor() {
     executor.initialize();
     return executor;
   }
+
+  @Bean("importerCompletionThreadPoolExecutor")
+  public ThreadPoolTaskExecutor getImporterCompletionTaskExecutor() {
+    final ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
```
Comment (panagiotisgts) [inline operate/importer/src/main/java/io/camunda/operate/zeebeimport/ImportConfig.java]: ❌  We won't need this large thread pool as well if we opt for an aggregate. Keep in mind that this pool would remain open if not manually disabling the importers afterwards.

**Review by panagiotisgts — CHANGES_REQUESTED** [review]
Some optimization changes. Also, can you include some test cases that do not revolve around the `tenant` records specifically?

File: operate/importer/src/main/java/io/camunda/operate/zeebeimport/ImportConfig.java (hunk 4 above)
Comment (EuroLew) [reply operate/importer/src/main/java/io/camunda/operate/zeebeimport/ImportConfig.java]: removed given a single ES call probably doesn't need an executor

**Review by panagiotisgts — APPROVED** [review]
LGTM. I'd suggest testing the fix actually works as well on importer restart when it actually has an 8.8 record ingested already but did not update the completed flag correctly.
