### PR TITLE
fix: Failure to apply retention policy with too_long_http_line_exception error

### LINKED ISSUE #38033: Failure to apply retention policy with too_long_http_line_exception error
### 

### 

### 

### 

### Description

When enabling the retention policy in a C8 environment, if many history indices (e.g., around 100) are present, the platform attempts to update settings on all indices in one bulk PUT request to Elasticsearch. If too many indices are combined in the request URL, the payload exceeds Elasticsearch’s maximum HTTP line length (4096 bytes), resulting in a 400 Bad Request with the error too_long_http_line_exception: "An HTTP line is larger than 4096 bytes."

### Steps to reproduce

1. Enable retention policy in C8 for history indices, ensuring a large number of indices exist (approximately 100 or more).
2. C8 applies the retention policy and constructs a PUT request to the Elasticsearch `_settings` endpoint, listing all relevant indices in a single comma-separated URL.
Example failing URL:
`http://<elasticsearch-host>:9200/index1,index2,index3,.../settings?ignore_unavailable=true&allow_no_indices=true`
3. Request is rejected with a 400 status code and the `too_long_http_line_exception` error.

### Current behavior

Policy not applied on the archiver indices.
Elasticsearch responds with:
```
{
  "error": {
    "root_cause": [
      {
        "type": "too_long_http_line_exception",
        "reason": "An HTTP line is larger than 4096 bytes."
      }
    ],
    "type": "too_long_http_line_exception",
    "reason": "An HTTP line is larger than 4096 bytes."
  },
  "status": 400
}
```

### Expected behavior

Policy is applied on the archiver indices.

### Workaround

Manual application of the retention policy on the archiver indices

### Environment

SaaS & SM

### Version

- Component Version: 8.8

### Rootcause

* The application logic does not account for the maximum allowed HTTP line length when forming bulk settings requests to Elasticsearch.
* C8 sends all indices in a single PUT call, exceeding the default Elasticsearch HTTP line limit.

### Solution ideas

Update the request construction logic to batch index lists into groups that do not exceed the 4096-byte limit.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

[#inc-weekly-benchmark-es-disk-full](https://camunda.slack.com/archives/C09EECUGCER)

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

Avoids building long http path with all existing historical indices names, which causes exceeding the 4096 chars Elasticsearch limit, but async calls for each index template with the following pattern
`index_template_pattern,-runtime_index_name,-alias_name`, this allows to apply the ILM to all historical indices for a given index template 

This pull request refactors the `ArchiverRepository` implementations for Elasticsearch and OpenSearch to improve how index templates and retention policies are managed. The changes replace hardcoded index handling with a more dynamic, template-driven approach using `ExporterResourceProvider` and `IndexTemplateDescriptor`, and streamline the application of lifecycle policies.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #38033

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java [hunk 1]
```diff
@@ -113,62 +133,92 @@ void shouldDeleteDocuments() throws IOException {
...
+    // when
+    final var result = repository.setIndexLifeCycle(usageMetricIndex);
+
+    // then
+    assertThat(result).succeedsWithin(Duration.ofSeconds(30));
     assertThat(getLifeCycle(usageMetricIndex))
         .isNotNull()
         .extracting(IndexSettingsLifecycle::name)
-        .isEqualTo("camunda-usage-metrics-retention-policy");
+        .isEqualTo("camunda-retention-policy");
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java]: ❓ should this not still be `camunda-usage-metrics-retention-policy`?

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java [hunk 2]
```diff
@@ -541,33 +596,78 @@ void shouldCacheIndicesWhichHaveRetentionPolicyAppliedAndNotReapplyPointlessly()
...
+        .untilAsserted(
+            () ->
+                verify(
+                        indicesClientSpy, times(16) // number of index templates
+                        )
+                    .putSettings(captor.capture()));
+
+    final var putIndicesSettingsRequests = captor.getAllValues();
+    assertThat(putIndicesSettingsRequests).hasSize(16);
+    assertThat(putIndicesSettingsRequests)
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java]: 🔧 not a big deal but you could merge these into a chained assertion

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java [hunk 3]
```diff
@@ -541,33 +596,78 @@ void shouldCacheIndicesWhichHaveRetentionPolicyAppliedAndNotReapplyPointlessly()
...
     Awaitility.await()
-        .untilAsserted(() -> verify(indicesClientSpy, times(2)).putSettings(captor2.capture()));
+        .untilAsserted(() -> verify(indicesClientSpy, times(1)).putSettings(captor2.capture()));
+
+    final var putIndicesSettingsRequest2 = captor2.getValue();
+    assertThat(putIndicesSettingsRequest2.index()).containsExactly(indexName1);
+  }
+
+  @Test
+  void shouldApplyIlmToAllHistoricalIndices() {
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java]: 👍 nice test

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java [hunk 4]
```diff
@@ -117,27 +104,65 @@ public CompletableFuture<ArchiveBatch> getBatchOperationsNextBatch() {
...
+    final var requests =
+        indicesGroupedByPolicyName.entrySet().stream()
+            .flatMap(
+                entry ->
+                    entry.getValue().stream()
+                        .map(
+                            template ->
+                                applyPolicyToIndices(
+                                    entry.getKey(), buildHistoricalIndicesPattern(template))))
+            .toList();
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java]: ❓ am I overlooking something or can we simplify this to a single stream? i.e. something like:

```
final var requests =
    allTemplatesDescriptors.stream()
        .map(template ->
            applyPolicyToIndices(
                getRetentionPolicyName(template.getIndexName(), retention),
                buildHistoricalIndicesPattern(template)))
        .toList();
```

**Review by RomanJRW — APPROVED** [review]
Generally LGTM, just some minor comments 👍

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java (hunk 1 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java]: yes, indeed, the test is disabled though, until the rollover of metrics indices is correctly handled
I will update it

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java (hunk 4 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java]: yes, well spotted!
in the beginning it was the calls were grouped retention policy name, now we group them by index template

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java (hunk 3 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java]: I also added the usage of real schema, to assert that the ILM is applied on dated indices but not the runtime indices, because it can be source of data loss 🥵

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java (hunk 2 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java]: Done!

**Review by ce-dmelnych — APPROVED** [review]
LGTM 🚀 
Thanks for fixing the bug and for the neat refactoring of ES/OS ArchiverRepositories, it makes code much more maintainable and well-structured!
