### PR TITLE
fix: CamundaExporter starts exporting before being opened

### LINKED ISSUE #32009: CamundaExporter starts exporting before being opened
### 

### 

### 

### 

### Description

As discussed in [Slack](https://camunda.slack.com/archives/C06F0GLJNFM/p1729526856370519)
CamundaExporter starts exporting records, before `exporter#open` method completes, which causes a NullpointerException since some resources that are created in the `open` method are not initialized yet
```
18:03:52.850 [Broker-0] [zb-fs-workers-0] [Exporter-1] WARN  io.camunda.zeebe.broker.exporter.camunda - Error on exporting record with key 2251799813688996
java.lang.NullPointerException: Cannot invoke "io.camunda.exporter.store.ExporterBatchWriter.getBatchSize()" because "this.writer" is null
	at io.camunda.exporter.CamundaExporter.export(CamundaExporter.java:119) ~[classes/:?]
```

### Steps to reproduce

This typically happen when starting Zeebe from an existing state and an empty Elasticsearch (schema not created yet)

### Current behavior

`exporter#export` does not wait for `exporter#open`

### Expected behavior

`exporter#export` to wait for `exporter#open`

### Environment

SaaS & SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

I think this may caused by the exporter starting to export based on some Metadata stored in Zeebe state. But I am not sure how to prove that

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

This pull request improves the reliability of the exporter startup sequence in the Zeebe broker by ensuring that exporting does not resume until all exporters have finished opening.

* Added a new `AtomicBoolean allExportersOpened` flag to `ExporterDirector` to track when all exporters have successfully opened.
* Updated the logic in `ExporterDirector` so that exporting only starts when both `isOpened` (a state of the director itself) and `allExportersOpened` are true, preventing premature exporting.
* Set `allExportersOpened` to true only after all exporters have finished opening in the `startActiveExportingMode` method.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #32009

### CODE REVIEW

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java [hunk 1]
```diff
@@ -63,6 +63,7 @@ public final class ExporterDirector extends Actor implements HealthMonitorable,
 
   private static final Logger LOG = Loggers.EXPORTER_LOGGER;
   private final AtomicBoolean isOpened = new AtomicBoolean(false);
+  private final AtomicBoolean allExportersOpened = new AtomicBoolean(false);
```
Comment (deepthidevaki) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java]: :x: This can be a simple boolean unlike `isOpened` because it is only used with in the ExporterDirector actor.

**Review by deepthidevaki — APPROVED** [review]
Thanks @houssain-barouni . Please check my comment before merging.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java (hunk 1 above)
Comment (houssain-barouni) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java]: @deepthidevaki I suppose I don't need to set back `allExportersOpened` to `false`, when the director is being closed (when `isOpened.set(false)`) 
once a director is closed, it is not reused anymore, is this correct?

**Review by yohanfernando — APPROVED** [review]
Nice 🙌
