### PR TITLE
fix: updating cluster variable documentation link

### LINKED ISSUE #43013: Cluster Variables UI: Documentation Link Broken (404) and Incorrect URL
### 

### 

### 

### 

### Description

Cluster Variables UI's documentation/help link leads to an incorrect URL, resulting in a blank (404) page. Users expect the documentation to be available at https://docs.camunda.io/docs/next/components/identity/cluster-variable/, but the UI currently points to https://docs.camunda.io/docs/components/identity/cluster-variable/ which returns a 404 error. This blocks users from accessing guidance for this feature. Please correct the documentation link in the UI to resolve this issue.

### Steps to reproduce

1. Open Cluster Variables UI
2. Click the documentation/help link for Cluster Variables
3. Observe the browser navigates to https://docs.camunda.io/docs/components/identity/cluster-variable/ and a 404 blank page is shown
4. Compare with https://docs.camunda.io/docs/next/components/identity/cluster-variable/ (this URL works as intended)

### Current behavior

Documentation link for Cluster Variables leads to a blank (404) page because it points to the wrong URL (missing `/next/`). Users cannot access the feature documentation.

### Expected behavior

The documentation/help link in the Cluster Variables UI should point to https://docs.camunda.io/docs/next/components/identity/cluster-variable/ and the documentation should be displayed to the user.

### Workaround

_No response_

### Environment

SaaS

### Version

- UI Version: N/A
- Documentation site version: latest (docs.camunda.io)
- Bug present as of Dec 2025

### Rootcause

_No response_

### Solution ideas

Update the Cluster Variables UI to use the correct documentation URL `/next/components/identity/cluster-variable/`. Consider reviewing the documentation generation process to avoid future link mismatch.

### Dev -> QA handover

_No response_

### Links

https://docs.camunda.io/docs/components/identity/cluster-variable/
https://docs.camunda.io/docs/next/components/identity/cluster-variable/

### Automated Test Impact

Not applicable

### PR DESCRIPTION
**Pull request by steven-rg-harrison**
## Description

The cluster variables documentation page was created, so we need to update the links to point to the correct location.
https://docs.camunda.io/docs/next/components/modeler/feel/cluster-variable/cluster-variable-overview/

## Checklist

- ~[ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes)).~

## Related issues

closes #43013

### CODE REVIEW

File: identity/client/src/pages/cluster-variables/List.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ export default function List() {
     <PageHeader
       title={t("clusterVariables")}
       linkText={t("clusterVariables").toLowerCase()}
-      docsLinkPath="/docs/components/identity/cluster-variable/"
+      docsLinkPath="/docs/next/components/modeler/feel/cluster-variable/cluster-variable-overview/"
```
Comment (mrm1st3r) [inline identity/client/src/pages/cluster-variables/List.tsx:56]: 💭 Note to myself: There's a PR waiting that need's to be aligned with docs team, that'll change the docsBasePath to include the version as well. I'll need to change this new link in that PR as well. See https://github.com/camunda/camunda/pull/43594

**Review by mrm1st3r — APPROVED** [review]
