### PR TITLE
fix: validate conflicting pagination requests

### LINKED ISSUE #43977: Validate OC REST search request pagination attributes for conflicts
### 

### 

### 

### 

### Description

When a search request's `page` object contains a `limit` and additionally conflicting attributes like ` after` and `before`, validation needs to catch the conflicting attributes `after` and `before`.

### Steps to reproduce

1. Issue a search requests against V2 REST API containing `limit`, `after`, and `before`

### Current behavior

An error response with a message like "Request property [page.before] cannot be parsed" is returned.

### Expected behavior

An error response with a message like "Only one of [from, after, before] is allowed" is returned.

### Workaround

None

### Environment

SaaS & SM

### Version

- Component Version: 8.9.0-alpha3

### Rootcause

The `SearchQueryPageRequestDeserializer` doesn't consider the case when `limit` is included in the request.

### Solution ideas

Add another validation case when `limit` is included in the request.

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

Validates pagination in V2 REST search requests regarding conflicting properties when limit is included.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes)).

## Related issues

closes #43977

### CODE REVIEW

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/deserializer/SearchQueryPageRequestDeserializer.java [hunk 1]
```diff
@@ -55,7 +55,8 @@ protected void validateFields(final Set<String> presentFields) {
       throw new DeserializationException(
           ERROR_MESSAGE_AT_LEAST_ONE_FIELD.formatted(getSupportedFields()));
     }
-    if (!presentFields.contains(LIMIT_PAGINATION_FIELD) && presentFields.size() > 1) {
+    if ((!presentFields.contains(LIMIT_PAGINATION_FIELD) && presentFields.size() > 1)
+        || presentFields.contains(LIMIT_PAGINATION_FIELD) && presentFields.size() > 2) {
```
Comment (tanjinyi) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/deserializer/SearchQueryPageRequestDeserializer.java:59]: Is LIMIT + OFFSET + BEFORE/AFTER a valid combination? Just wondering how would the OFFSET field be interacted with.

**Review by tanjinyi — APPROVED** [review]
Just have a minor query with regard to the offset field, otherwise LGTM 👍

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/deserializer/SearchQueryPageRequestDeserializer.java (hunk 1 above)
Comment (tmetzke) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/deserializer/SearchQueryPageRequestDeserializer.java:59]: Nope, only one of OFFSET/BEFORE/AFTER is allowed. LIMIT can be set with any (or none) of them.

OFFSET -> "classic" offset pagination, starting a page at the item with the provided index
BEFORE -> keyset pagination, get the page before the provided cursor
AFTER -> keyset pagination, get the page after the provided cursor

They are all distinct types of pagination, so they are exclusive.

Comment (tanjinyi) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/deserializer/SearchQueryPageRequestDeserializer.java:59]: thanks for the clarification!
