### PR TITLE
fix: fail spring startup on continuous backups with document based databases

### LINKED ISSUE #45647: Continuous backups are only allowed with no secondary storage and RDBMS
Continuous backups are only allowed with no secondary storage and RDBMS, in all other cases (e.g. ES/OS) we should refuse to start up when a user tries to enable continuous backups.

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

To ensure continuous backups are not used with Elasticsearch/Opensearch, forcefully cancel Spring's startup context during property overriding. This is to not create false expectations that continuous backups are compatible with document based storages.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #45647

### CODE REVIEW

File: configuration/src/main/java/io/camunda/configuration/beanoverrides/BrokerBasedPropertiesOverride.java [hunk 1]
```diff
@@ -788,6 +788,12 @@ private void populateFromFilesystem(final BrokerBasedProperties override) {
 
   private void populateBackupScheduler(
       final BrokerBasedProperties override, final PrimaryStorageBackup primaryStorageBackup) {
+
+    if (invalidContinuousBackupConfiguration(primaryStorageBackup)) {
+      throw new IllegalArgumentException(
+          "Continuous backups are not compatible with document-based secondary storage. Please disable continuous backups.");
+    }
```
Comment (lenaschoenburg) [inline configuration/src/main/java/io/camunda/configuration/beanoverrides/BrokerBasedPropertiesOverride.java]: 🔧 Let's move the error message closer to where we actually validate and then include which secondary storage it was.

**Review by lenaschoenburg — APPROVED** [review]

File: configuration/src/main/java/io/camunda/configuration/beanoverrides/BrokerBasedPropertiesOverride.java (hunk 1 above)
Comment (panagiotisgts) [reply configuration/src/main/java/io/camunda/configuration/beanoverrides/BrokerBasedPropertiesOverride.java]: Done in https://github.com/camunda/camunda/pull/45650/commits/8b2d9d88fbe2eebbd34e5909d52594c83da9ab8c
