### PR TITLE
fix: incorrect Swagger BasicAuth Visibility And 'Enable Swagger' Toggle Inconsistencies

### LINKED ISSUE #38206: Incorrect Swagger BasicAuth Visibility And 'Enable Swagger' Toggle Inconsistencies
### 

### 

### 

### 

### Description

Two separate but related issues have been identified in the SaaS implementation of Swagger UI:

1. Swagger Authorize Button: Incorrect Display of BasicAuth Option

- When parsing `rest-api-yaml`, all security scheme components are appended rather than overwritten. This leads to the `basicAuth` option appearing in the Swagger UI Authorize pop-up, even when it should not be visible on SaaS.
- The expected behavior is that only relevant security schemes should appear, with proper overwriting rather than appending when the YAML is processed.

2. Toggle 'Enable Swagger' Setting: Inconsistent UI Visibility

- Toggling the 'Enable Swagger' setting on and off results in inconsistent behavior regarding the visibility and accessibility of `/swagger-ui/index.html`. The configuration properties controlling this are correctly implemented in Self-Managed (SM) but are missing in SaaS.
- This causes confusion about whether the Swagger UI should be accessible after toggling, leading to different results between SaaS and SM environments.

### Steps to reproduce

1. Swagger BasicAuth Visibility
- Open the Swagger UI on SaaS.
- Click on the "Authorize" button.
- Observe the authentication options displayed.

2. Swagger UI Toggle Inconsistency
- Navigate to SaaS admin/settings panel.
- Toggle 'Enable Swagger' setting on and off.
- Access /swagger-ui/index.htm after each toggle.
- Compare with Self-Managed environment.

### Current behavior

- Swagger Authorize Button: BasicAuth option appears on SaaS even if it should not, due to merging (appending) of all security schemes from the YAML instead of proper overwriting.
- 'Enable Swagger' Toggle: Changing the setting does not reliably show/hide the Swagger UI on SaaS. This contrasts with Self-Managed, where the UI visibility is correctly controlled via config properties.

### Expected behavior

- Swagger Authorize Button: Only the appropriate security schemes should be visible based on current SaaS configuration. Parsing the YAML should overwrite the existing schemes, not append all found.
- 'Enable Swagger' Toggle: Toggling 'Enable Swagger' should consistently show or hide /swagger-ui/index.htm on SaaS, mirroring the behavior seen in Self-Managed instances via equivalent config properties.

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SM

### Version

- Component Version: 8.8-alpha8

### Rootcause

_No response_

### Solution ideas

See https://camunda.slack.com/archives/C08DQB6RA8Z/p1758020975596519?thread_ts=1758020333.220579&cid=C08DQB6RA8Z

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by abremard**
## Description

We're using all components from rest-api-yaml when [parsing](https://github.com/camunda/camunda/blob/3e1ff3fb792a40bd161cf9037f35468e996426f3/zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/util/OpenApiYamlLoader.java#L87) the yaml and the security schemes are only appended instead of overwriting [here](https://github.com/camunda/camunda/blob/667fa6adf2ce4f37a738ea2c9e989b579c9fe469/zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/config/SaaSOpenApiConfigurer.java#L28). The fix is to overwrite the security schemes inside the configurer implementations.

SM has this [config properties](https://github.com/camunda/camunda/blob/667fa6adf2ce4f37a738ea2c9e989b579c9fe469/zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/config/SelfManagedOpenApiConfigurer.java#L21) but not [SaaS](https://github.com/camunda/camunda/blob/667fa6adf2ce4f37a738ea2c9e989b579c9fe469/zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/config/SaaSOpenApiConfigurer.java#L20) so disable Swagger didn't work in SaaS

## Related issues

closes #38206

### CODE REVIEW

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/config/OpenApiConfigurer.java [hunk 1]
```diff
@@ -39,15 +38,4 @@ public abstract class OpenApiConfigurer {
...
-  /**
-   * Adds bearer authentication to the OpenAPI specification. This is common for both SaaS and
-   * Self-Managed deployments.
-   *
-   * @param openApi the OpenAPI object to configure
-   */
-  protected final void addBearerAuthentication(final OpenAPI openApi) {
-    openApi.getComponents().addSecuritySchemes(BEARER_SECURITY_SCHEMA_NAME, BEARER_SECURITY_SCHEMA);
-    openApi.addSecurityItem(new SecurityRequirement().addList(BEARER_SECURITY_SCHEMA_NAME));
-  }
```
Comment (abremard) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/config/OpenApiConfigurer.java:52]: I'm removing this entirely, it made sense back then but now I believe the configurer should have control over the security schemes and since we're now overwriting the schemes it makes more sense to explicitly do it in `configureSecurity`

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/config/SelfManagedOpenApiConfigurer.java [hunk 2]
```diff
@@ -30,9 +33,18 @@ public class SelfManagedOpenApiConfigurer extends OpenApiConfigurer {
...
+        .setSecuritySchemes(
+            new LinkedHashMap<>(
+                Map.of(
+                    BEARER_SECURITY_SCHEMA_NAME, BEARER_SECURITY_SCHEMA,
+                    BASIC_SECURITY_SCHEMA_NAME, BASIC_SECURITY_SCHEMA)));
+
+    openApi.setSecurity(
+        List.of(
+            new SecurityRequirement().addList(BEARER_SECURITY_SCHEMA_NAME),
+            new SecurityRequirement().addList(BASIC_SECURITY_SCHEMA_NAME)));
```
Comment (abremard) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/config/SelfManagedOpenApiConfigurer.java]: I'm setting these inline for readability

**Review by konstantinos-mylosis — APPROVED** [review]
Nice 🚀

❓Should we:
Remove `securitySchemes` from `rest-api.yml`
OR
Keep them but don't override them in `SelfManagedOpenApiConfigurer`

**Comment by abremard** [comment]
> Nice 🚀
> 
> ❓Should we: Remove `securitySchemes` from `rest-api.yml` OR Keep them but don't override them in `SelfManagedOpenApiConfigurer`

Ah, for context, we leave the securitySchemes in `rest-api.yml` because some SM users like to export the open api specs into their own clients. We can remove the setting in `SelfManagedOpenApiConfigurer` since it will be the same as the yaml
