### PR TITLE
Handle remote stream push responses and errors

### LINKED ISSUE #15195: Encode remote/job streaming errors as part of stream protocol
**Description**

Currently, we report errors upstream during a push via exceptions. For example, a request is sent from the broker to the gateway over the `stream-push` topic. That request, say, fails because no streams can receive it. The handler on the gateway will complete the future with a `StreamExhaustedException`. This is propagated back to the broker as a `MessagingException$RemoteHandlerFailure`. While the exception type is in the message, it's not really encoded anywhere.

In order to properly handle errors, we have to encode the protocol errors (i.e. expected possible failure modes) into the remote stream protocol as possible responses to requests.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR adds handling of stream push responses and errors. Although the response type is empty for now, it's still handled for future proofing if we wish to extend it. The empty array is still accepted as a valid response until 8.5.

To simplify things, I extracted the handling of incoming requests in the `ClientStreamServiceImpl` to a separate class `ClientStreamApiHandler`. Tests mostly focus on the error mapping since the actual push logic is handled by the `ClientStreamManager`.

> **Note**
> We could move that to the API handler as well in a follow up.

No special error treatment here - we essentially retry all push errors with a different consumer (i.e. gateway), since in all cases there's a chance it might succeed.

No handling of time outs - this is still part of a follow up to decide whether it makes sense to retry time outs of not.

## Related issues

closes #15195 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/messages/MessageUtil.java [hunk 1]
```diff
@@ -34,11 +34,4 @@ private static <R extends BufferReader> R parseRequest(final byte[] bytes, final
 
     return request;
   }
-
-  public static byte[] encodeResponse(final StreamResponse response) {
```
Comment (Zelldon) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/messages/MessageUtil.java:38]: 👍🏼

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamPusher.java [hunk 2]
```diff
@@ -32,6 +34,7 @@ final class RemoteStreamPusher<P extends BufferWriter> {
   private static final Logger LOG = LoggerFactory.getLogger(RemoteStreamPusher.class);
 
   private final StreamResponseDecoder responseDecoder = new StreamResponseDecoder();
+  private final ThrottledLogger pushErrorLogger = new ThrottledLogger(LOG, Duration.ofSeconds(5));
```
Comment (Zelldon) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamPusher.java:37]: 👍🏼

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamPusher.java [hunk 3]
```diff
@@ -58,7 +61,8 @@ private RemoteStreamErrorHandler<P> instrumentingErrorHandler(
     return (error, payload) -> {
       if (error != null) {
         metrics.pushFailed();
-        LOG.debug("Failed to push (size = {}) to stream {}", payload.getLength(), streamId, error);
+        pushErrorLogger.warn(
+            "Failed to push (size = {}) to stream {}", payload.getLength(), streamId, error);
```
Comment (Zelldon) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamPusher.java:65]: ❓ Should the log level maybe different based on the error?

**Review by ChrisKujawa — APPROVED** [review]
thanks 👍🏼

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamPusher.java (hunk 3 above)
Comment (npepinpe) [reply transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamPusher.java:65]: Good question, I hadn't really thought about it. Let's walk through it.

- `NoSuchMemberException` -> thrown when we tried pushing to a gateway which was since removed from the cluster (or we have a bug, ofc :smile:). This is likely a temporary error - if the member is gone, its streams will get removed, but that's asynchronous so this may happen. It makes sense as a warning, since if it persists this is indicative of a bigger issue.
- `RemoteHandlerFailure` -> this is caused by an uncaught exception on the target side. This is typically pretty bad, but the relevant log will be on the receiver/target side. I think here also makes sense to log as a warning - the real error should be logged, as error, on the receiver side.
- `NoRemoteHandler` -> this is caused if the node isn't listening for pushes. This is either a bug (in which case warning makes sense), or temporary on shutdown, so it would resolve itself.
- `ProtocolException` -> this happens if the messaging service can't parse the request. Shouldn't happen, and if it does, it's likely a bigger issue with the complete messaging service, and we have other logs for that. We _could_ downgrade it to debug, but I think it's also OK as warning.

So as far as exceptions go, I think all of them as warning is OK.

Then we get `StreamResponseException`: basically a stream protocol error. There it will be based on the error code:

- `INTERNAL_ERROR` -> makes sense as warning, though likely won't recover, but the real error log should be on the receiver side.
- `NOT_FOUND` -> could be temporary, i.e. the stream was just closed asynchronously.
- `INVALID` -> means the request is invalid. For pushes this is not a possible case (yet anyway).
- `MALFORMED` -> could happen, means the push request we sent is not parse-able. I suppose it's unrecoverable, so here it probably makes sense as error level. wdyt?
- `EXHAUSTED` -> means all streams were tried unsuccessfully on the gateway (e.g. either they were closed as we tried pushing, or they were blocked, etc.). This could be debug since in most cases you won't care, but it could indicate that something really is wrong if this is returned all the time incorrectly :thinking: I'm not sure about this case.
- `BLOCKED` -> not yet in use, since even if the stream was blocked, we always return `EXHAUSTED` instead at the moment. Might be different later once we track and propagate capacity.

So what I see is that `MALFORMED` and `INVALID` (though not used here yet) make sense as errors, since the error is on the sender side. I don't know about `EXHAUSTED` yet :thinking:

Comment (npepinpe) [reply transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamPusher.java:65]: Also follow up decision, the throttled logger throttles regardless of log level. Should we use a different one, or refactor it so we throttle based on level? Since we probably want to show ERROR level more than WARN level errors.

**Comment by npepinpe** [comment]
bors merge
