### PR TITLE
test: Fix flakiness in `ActivatableJobsPushTest.shouldPushAfterJobFailed` test

### LINKED ISSUE #17456: `ActivatableJobsPushTest.shouldPushAfterJobFailed` is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? At least once
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Expected size: 2 but was: 1 in:
[{"key":2251799813685272,"record":{"deadline":1712926185476,"timeout":-1,"worker":"test","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"id-4b76546e-c86e-473d-87b0-988eebc44593","customHeaders":[packed value (length=1)],"variables":"3wAAAAOhYaR2YWxBoWKkdmFsQqFjpHZhbEM=","errorMessage":"","errorCode":"","bpmnProcessId":"process","processDefinitionVersion":2,"processDefinitionKey":2251799813685262,"processInstanceKey":2251799813685264,"jobKind":"BPMN_ELEMENT","elementId":"task","elementInstanceKey":2251799813685271,"tenantId":"<default>"}},
    {"key":2251799813685272,"record":{"deadline":1712926185479,"timeout":-1,"worker":"test","retries":5,"retryBackoff":0,"recurringTime":-1,"type":"id-4b76546e-c86e-473d-87b0-988eebc44593","customHeaders":[packed value (length=1)],"variables":"3wAAAAOhYaR2YWxBoWKkdmFsQqFjpHZhbEM=","errorMessage":"","errorCode":"","bpmnProcessId":"process","processDefinitionVersion":2,"processDefinitionKey":2251799813685262,"processInstanceKey":2251799813685264,"jobKind":"BPMN_ELEMENT","elementId":"task","elementInstanceKey":2251799813685271,"tenantId":"<default>"}}]
	at io.camunda.zeebe.engine.processing.job.ActivatableJobsPushTest.assertActivatedJobsPushed(ActivatableJobsPushTest.java:280)
	at io.camunda.zeebe.engine.processing.job.ActivatableJobsPushTest.shouldPushAfterJobFailed(ActivatableJobsPushTest.java:204)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

From https://github.com/camunda/zeebe/actions/runs/8662240967: [Test results for unit tests.zip](https://github.com/camunda/zeebe/files/14959010/Test.results.for.unit.tests.3.zip)

### PR DESCRIPTION
**Pull request by ce-dmelnych**
### Problem
The test `ActivatableJobsPushTest.shouldPushAfterJobFailed` exhibits flakiness due to timing issues. 
Occasionally, the test fails because the `jobStream` was not updated in time with the activated jobs.

### Solution
`Awaitility` lib was used to wait for the expected activated jobs count.

#### Test runs before the fix:
Screenshot 2024-04-16 at 08 58 47

#### Test runs after the fix:
Screenshot 2024-04-16 at 08 57 34

closes #17456

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java [hunk 1]
```diff
@@ -277,7 +278,10 @@ private void assertEventOrder(
 
   private void assertActivatedJobsPushed(final Long jobKey, final int activationCount) {
     final var activatedJobs = jobStream.getActivatedJobs();
-    assertThat(activatedJobs).hasSize(activationCount);
+    await("waiting for the expected number of jobs to be activated")
+        .atMost(Duration.ofMillis(300))
+        .pollInterval(Duration.ofMillis(10))
+        .untilAsserted(() -> assertThat(activatedJobs).hasSize(activationCount));
```
Comment (tmetzke) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java:284]: ❓ Does this make a difference? Do we need to pull the `jobStream.getActivatedJobs()` call inside the `await` as well?

Comment (ce-dmelnych) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java]: @tmetzke It's unnecessary as `jobStream.getActivatedJobs()` returns a reference (not a copy) to the activated jobs list.

But I will move `jobStream.getActivatedJobs()` to `. untilAsserted` to avoid confusion.

Thanks for highlighting this!

Comment (tmetzke) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java]: Ah nice, that makes sense, I was hoping for something like this! 👍

Comment (ce-dmelnych) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java]: Solution updated)

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java [hunk 2]
```diff
@@ -276,16 +277,21 @@ private void assertEventOrder(
...
-        activatedJob -> {
-          assertThat(activatedJob.jobKey()).isEqualTo(jobKey);
-
-          final JobRecord jobRecord = activatedJob.jobRecord();
-          assertThat(jobRecord.getWorkerBuffer()).isEqualTo(worker);
-          assertThat(jobRecord.getVariables()).isEqualTo(variables);
-          assertThat(jobRecord.getTenantId()).isEqualTo(TenantOwned.DEFAULT_TENANT_IDENTIFIER);
-        });
+    await("waiting for the expected number of jobs to be activated")
+        .atMost(Duration.ofMillis(300))
```
Comment (tmetzke) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java:281]: ❓ While this works right now, this might run into flakiness in the future again, right? We are still relying on some timing now, we just wait longer. I was wondering if we can't let this wait for something more reliable (either in this method or before we call this method). Usually, we wait for specific events on the log. That probably won't suffice here. But maybe we can wait for something more specific in the `jobStream` object that semantically tells us that the stream of jobs was updated.

Comment (tmetzke) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java:281]: If we can't - which is fine - we should at least fall back to waiting times that correlate with what we use for the recording exporter when we wait for records on the log to appear.

**Review by tmetzke — APPROVED** [review]
👍
