### PR TITLE
fix: don't apply tenant check to Identity-related entities

### LINKED ISSUE #42175: With enabled multi tenancy, the Role Search Query returns an empty result
### 

### 

### 

### 

### Description

The Role entity exists on a global level, meaning, it is not assigned to any tenant. When a user - who is not assigned to any tenant - performs a role search query, the query returns an empty result set.

### Steps to reproduce

1. Configure C8 Orchestration with a RDBMS
2. Enable multi tenancy checks
3. Enable the authentication method `basic`
4. Create a few roles
5. Create a user `foo`
6. Perform a role search query: `/v2/roles/search` with user `foo`

### Current behavior

No roles are returned.

### Expected behavior

The created roles should be returned.

### Workaround

_No response_

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

The `RoleDbReader` checks if the query would return an empty result by calling `#shouldReturnEmptyResult()`:

https://github.com/camunda/camunda/blob/2f0819a63d5099df8b0c00010fc04f0a56cb3ec1/db/rdbms/src/main/java/io/camunda/db/rdbms/read/service/RoleDbReader.java#L91

The implementation checks if a tenant check should be performed. If true, it checks if the authenticated user is assigned/authorized for any tenant, which is not the case in this scenario. So, the method will return `true`, indicating that an empty result should be returned:

https://github.com/camunda/camunda/blob/2f0819a63d5099df8b0c00010fc04f0a56cb3ec1/db/rdbms/src/main/java/io/camunda/db/rdbms/read/service/AbstractEntityReader.java#L159-L164

### Solution ideas

Allow to overwrite in certain cases the tenant check in the `CamundaSearchClients`. For example, when searching roles, intercept the search and disable the tenant check explicitly. So, the underlying search client does not apply any tenant checks to the query. This approach allows us to explicitly declare the cases in which the tenant check should not occur, rather than having each search client (ES, OS, RDBMS) implement that on its own.

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

* Disables the tenant check for Identity-related entities (Authorization, Group, Group Membership, Role, Role Membership, Mapping Rules, and User)
* Adds missing test cases
* Applies some minor refactoring for better readibility and udnerstanding of the code 

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #42175

### CODE REVIEW

**Comment by romansmirnov** [comment]
@houssain-barouni, would you be up for a quick review? 😄

**Comment by houssain-barouni** [comment]
Hi @romansmirnov 
❓ I think the tenant checks are already skipped in [IndexFilterTransformer](https://github.com/camunda/camunda/blob/9c6ae37c05760cf673900d13722be04d8d6a2937/search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/IndexFilterTransformer.java#L122-L130), when the entity is not "tenant-aware", the tenantId filter is not added to the final query
In which case, this is not working?

**Comment by romansmirnov** [comment]
>❓ I think the tenant checks are already skipped in [IndexFilterTransformer](https://github.com/camunda/camunda/blob/9c6ae37c05760cf673900d13722be04d8d6a2937/search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/IndexFilterTransformer.java#L122-L130), when the entity is not "tenant-aware", the tenantId filter is not added to the final query
In which case, this is not working?

Yep, that is correct. In the case of ES/OS, it works perfectly. The issue is with the RDBMS readers, which do not utilize the `IndexFilterTransformer`. Instead of implementing the same concern in every reader, I implemented a common pattern that makes it explicit that for some entities (i.e., Identity-related entities) the tenant check must be disabled, and that it works in all cases and must not be re-implemented in ES/OS and RDBMS.

File: search/search-client/src/main/java/io/camunda/search/clients/CamundaSearchClients.java [hunk 1]
```diff
@@ -348,12 +350,12 @@ public RoleEntity getRole(final String id) {
 
   @Override
   public SearchQueryResult<RoleEntity> searchRoles(final RoleQuery query) {
-    return doSearchWithReader(readers.roleReader(), query);
+    return doSearchWithReader(readers.roleReader(), query, this::disableTenantCheck);
```
Comment (houssain-barouni) [inline search/search-client/src/main/java/io/camunda/search/clients/CamundaSearchClients.java:353]: 🤔 I am wondering if it would be better to make this an attribute of the query itself, rather than leaving it to the client implementation to decide whether tenant checks should be skipped.

**Review by houssain-barouni — APPROVED** [review]
LGTM! with one question wether this skipping tenant check should be the concern of the client implementation

File: search/search-client/src/main/java/io/camunda/search/clients/CamundaSearchClients.java (hunk 1 above)
Comment (romansmirnov) [reply search/search-client/src/main/java/io/camunda/search/clients/CamundaSearchClients.java:353]: If by query you mean something like `RoleQuery, then yeah, it could be an alternative. What speaks against it is that it mixes concerns at this stage (authentication/authorization/tenant checks, and search capabilities).

As an alternative, I was thinking of disabling the tenant check explicitly in the service layer because this is to some degree "business logic" - similar to the defined authorization checks. Still, decided to go with the `CamundaSearchClients` to make it transparent to the service layer. However, it should be defined in a shared place and not in every reader (that would need to be implemented every time).

It is still possible to adjust it later if needed.
