### PR TITLE
fix(snapshot): create snapshot exporter position is -1

### LINKED ISSUE #7978: Do not fail snapshotting when exporter position is -1
**Describe the bug**

When exporter position is -1 takeTransientSansphot  fails with an error.

```
java.lang.IllegalStateException: Failed to take snapshot. Expected to find an indexed entry for determined snapshot position -1 (processedPosition = 111, exportedPosition=-1), but found no matching indexed entry which contains this position.

        at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.takeTransientSnapshotInternal (StateControllerImpl.java:151)
        at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.lambda$takeTransientSnapshot$0 (StateControllerImpl.java:66)
        at io.camunda.zeebe.util.sched.ActorJob.invoke (ActorJob.java:73)
        at io.camunda.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
        at io.camunda.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
        at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:95)
        at io.camunda.zeebe.util.sched.ActorThread.doWork (ActorThread.java:78)
        at io.camunda.zeebe.util.sched.ActorThread.run (ActorThread.java:192)


```
**Expected behavior**

Either
1. Do not throw IllegalStateException, instead use a meaningful exception that can be logged at debug level by AsyncSnapshotDirector. This is not an error, but an expected state.
 OR
2. Take snapshot even if exporter position is -1. This will be useful if exporter has any issues, but processing is progressing. No snapshots means it will take for ever to reprocess. In this case, the question is what would be the snapshot index.

**Environment:**
 - Camunda Cloud
 - Zeebe Version: 1.2.0

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

Allow creating snapshots when exporter position is `-1`.

## Related issues

closes #7978 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java [hunk 1]
```diff
@@ -141,26 +143,43 @@ private void takeTransientSnapshotInternal(
...
+
+      final var snapshotIndexedEntry = optionalIndexed.get();
+      index = snapshotIndexedEntry.index();
+      term = snapshotIndexedEntry.term();
+    } else {
+      final Optional<PersistedSnapshot> latestSnapshot =
+          constructableSnapshotStore.getLatestSnapshot();
+      exportedPosition = 0;
+
+      if (latestSnapshot.isPresent()) {
```
Comment (deepthidevaki) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java:173]: :wrench: May be we can add some documentation here to explain why we re-use the index from latest snapshot. It is not easy to understand the reasoning behind this logic.

File: broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImplTest.java [hunk 2]
```diff
@@ -297,6 +297,47 @@ public void shouldCloseDbOnlyAfterTakingSnapshot() {
...
+
+    exporterPosition.set(-1L);
+
+    // when
+    final var transientSnapshot = snapshotController.takeTransientSnapshot(snapshotPosition).join();
+
+    // then
+    final var snapshot = transientSnapshot.snapshotId();
+    assertThat(snapshot.getIndex()).isEqualTo(4);
+    assertThat(snapshot.getTerm()).isEqualTo(1);
```
Comment (deepthidevaki) [inline broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImplTest.java:336]: :wrench: 
```suggestion
    assertThat(snapshot.getIndex()).isEqualTo(latestSnapshot.getIndex());
    assertThat(snapshot.getTerm()).isEqualTo(latestSnapshot.getTerm());
```

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteredSnapshotTest.java [hunk 3]
```diff
@@ -131,34 +132,127 @@ public void shouldIncludeExportedPositionInSnapshot() {
...
+                        .havingSnapshot()
+                        .withProcessedPosition(expectedProcessedPosition);
+                  });
+        });
+
+    // expect - each broker has created a snapshot with exported position = Long.MAX_VALUE
+    awaitUntilAsserted(
+        (broker) -> {
+          assertThat(broker).havingSnapshot().withExportedPosition(Long.MAX_VALUE);
+        });
```
Comment (deepthidevaki) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteredSnapshotTest.java:225]: :wrench: May be the following is more compact and readable. 

```suggestion
    final var leaderId = clusteringRule.getLeaderForPartition(1).getNodeId();
    final var leaderAdminService =
        clusteringRule.getBroker(leaderId).getBrokerContext().getBrokerAdminService();
    final var expectedProcessedPosition =
        leaderAdminService.getPartitionStatus().get(1).getProcessedPosition();

    awaitUntilAsserted(
        broker -> {
          triggerSnapshotRoutine();
          assertThat(broker)
              .havingSnapshot()
              .withProcessedPosition(expectedProcessedPosition)
              .withExportedPosition(Long.MAX_VALUE);
        });
```

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteredSnapshotTest.java [hunk 4]
```diff
@@ -233,4 +360,67 @@ public void export(final Record<?> record) {
       EXPORTED_RECORDS.incrementAndGet();
     }
   }
+
+  private static class BrokerAssert extends AbstractAssert<BrokerAssert, Broker> {
```
Comment (deepthidevaki) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteredSnapshotTest.java:364]: :+1:

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
:+1: Looks good. I have some optional comments. Please take a look at them.

It would be also good to add a test in Raft to verify that it can handle snapshot with index 0. The scenario could be something as follows:
1. Stop one follower
2. Write events to leader
3. Take snapshot at index 0
4. Restart follower
5. verify follower receives all events from the leader and no snapshot.

What do you think?

File: broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImplTest.java (hunk 2 above)
Comment (romansmirnov) [reply broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImplTest.java]: 👍

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java (hunk 1 above)
Comment (romansmirnov) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java:173]: 👍

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteredSnapshotTest.java (hunk 3 above)
Comment (romansmirnov) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteredSnapshotTest.java]: 👍

**Comment by romansmirnov** [comment]
@deepthidevaki, thanks for your review. I applied your suggestions. Please let me know, if there is anything else :)

**Comment by deepthidevaki** [comment]
Thanks @romansmirnov I will review it soon. But for now, I just noticed your commit messages. We don't use `chore` anymore. https://github.com/camunda-cloud/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines Could you please update the commit messages?

**Comment by romansmirnov** [comment]
@deepthidevaki, thanks for the hint. I changed the commit messages.

File: atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java [hunk 5]
```diff
@@ -411,6 +411,30 @@ public void shouldTruncateLogOnNewerSnapshotEvenAfterRestart() throws Throwable
...
+    // when
+    raftRule.joinCluster(follower);
+
+    // then
+    final var memberLogs = raftRule.getMemberLogs();
+    assertMemberLogs(memberLogs);
+
+    // snapshot is not replicated to follower
+    final var followerSnapshotStore = raftRule.getPersistedSnapshotStore(follower);
+    assertThat(followerSnapshotStore.getLatestSnapshot().isPresent()).isFalse();
```
Comment (deepthidevaki) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java:435]: :upside_down_face: 
```suggestion
    assertThat(followerSnapshotStore.getLatestSnapshot()).isNotPresent();
```

**Review by deepthidevaki — APPROVED** [review]
Great :rocket:

File: atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java (hunk 5 above)
Comment (romansmirnov) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java]: 👍

**Comment by romansmirnov** [comment]
bors merge
