### PR TITLE
Verify schema creation eagerly

### LINKED ISSUE #24412: ES/OS index missing on search request
## Describe the bug

The C8 REST API's query endpoints can run into internal server errors when database indexes do not exist (yet).
The endpoints try to execute a query on defined indexes and receive an "index not found" exception when the index is missing.

## To Reproduce

1. Start a Camunda 8 application with the Camunda Exporter only
2. Try to search for user tasks using `POST localhost:8080/v2/user-tasks/search`
3. Receive an error response with a 500 internal server error status code
```
{
  "type": "about:blank",
  "title": "Failed to execute UserTask Search Query",
  "status": 500,
  "detail": "Failed to execute search query",
  "instance": "/v2/user-tasks/search"
}
```

## Expected behavior

Receive a successful 200 response with 0 total hits and an empty items list
```
{
  "items": [],
  "page": {
    "totalItems": 0,
    "firstSortValues": [],
    "lastSortValues": []
  }
}
```

## Environment
- Zeebe Version: 8.7.0-SNAPSHOT
- Configuration: use Camunda Exporter only

## Background

-   The Camunda Exporter creates indices when there is something to write to them
-   For example, on initial start-up, only the following indices are created:
```
health status index                                uuid                   pri rep docs.count docs.deleted store.size pri.store.size dataset.size
green  open   identity-authorizations-8.7.0_       rC-VILGaRamqlOFPYd0RsA   1   0          0            0       249b           249b         249b
green  open   identity-users-8.7.0_                W5Fh1EEHS7SmjyEbxjoEuw   1   0          0            0       249b           249b         249b
green  open   operate-decision-8.3.0_              1ehM3EaCSOaKq4AmVpUohg   1   0          0            0       249b           249b         249b
green  open   operate-decision-requirements-8.3.0_ -kaQVCPjRXucceR2lIzklQ   1   0          0            0       249b           249b         249b
green  open   operate-metric-8.3.0_                -HDCErhQTMGD2Z6MfQPxXw   1   0          0            0       249b           249b         249b
green  open   operate-process-8.3.0_               -TbEhlblQxOJ1tR_NeM7cA   1   0          0            0       249b           249b         249b
green  open   tasklist-form-8.4.0_                 _GCArQZATQyfedwQkQ_-sA   1   0          0            0       249b           249b         249b
green  open   tasklist-metric-8.3.0_               Q3j_CKl3R8acmfy2KecEMQ   1   0          0            0       249b           249b         249b
```
-   Only after running something, for example a process instance with users tasks, additional indices are created:

```
health status index                                uuid                   pri rep docs.count docs.deleted store.size pri.store.size dataset.size
green  open   identity-authorizations-8.7.0_       rC-VILGaRamqlOFPYd0RsA   1   0          0            0       249b           249b         249b
green  open   identity-users-8.7.0_                W5Fh1EEHS7SmjyEbxjoEuw   1   0          0            0       249b           249b         249b
green  open   operate-decision-8.3.0_              1ehM3EaCSOaKq4AmVpUohg   1   0          0            0       249b           249b         249b
green  open   operate-decision-requirements-8.3.0_ -kaQVCPjRXucceR2lIzklQ   1   0          0            0       249b           249b         249b
green  open   operate-event-8.3.0_                 QF3HhHzPTr2RwmxP2Q4OYQ   1   0          3            0     11.5kb         11.5kb       11.5kb
green  open   operate-flownode-instance-8.3.1_     AYTj7D3oQl2mpWJBpMrbaA   1   0          2            0     10.3kb         10.3kb       10.3kb
green  open   operate-incident-8.3.1_              cnsLaPeBQwSm27XJ7Ke3wg   1   0          1            0      9.7kb          9.7kb        9.7kb
green  open   operate-list-view-8.3.0_             IKhyIu63Te-C3HDcjpChbQ   1   0          0            0       227b           227b         227b
green  open   operate-metric-8.3.0_                -HDCErhQTMGD2Z6MfQPxXw   1   0          1            0        6kb            6kb          6kb
green  open   operate-post-importer-queue-8.3.0_   -eGbffKRRXyxMs4DdEn6lg   1   0          1            0      6.5kb          6.5kb        6.5kb
green  open   operate-process-8.3.0_               -TbEhlblQxOJ1tR_NeM7cA   1   0          1            0     10.6kb         10.6kb       10.6kb
green  open   operate-sequence-flow-8.3.0_         1wW8VOmpThWtATNiFejewg   1   0          0            0       227b           227b         227b
green  open   operate-variable-8.3.0_              vTemtCzKTxqaXWeCPOlTbg   1   0          2            0      8.4kb          8.4kb        8.4kb
green  open   tasklist-form-8.4.0_                 _GCArQZATQyfedwQkQ_-sA   1   0          0            0       249b           249b         249b
green  open   tasklist-metric-8.3.0_               Q3j_CKl3R8acmfy2KecEMQ   1   0          0            0       249b           249b         249b
green  open   tasklist-task-8.5.0_                 W_2LQOVLR964OFXqMH6UMg   1   0          3            0       10kb           10kb         10kb
```

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Verifies that the camunda exporter creates the schema eagerly, and not lazy.
Furthermore, verifies the explicit names of the indices, to make sure no index is mistakenly changed, dropped or added. If so it must be done on purpose with adjusting the explicit test.

## Related issues

closes https://github.com/camunda/camunda/issues/24412

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java [hunk 1]
```diff
@@ -254,6 +256,70 @@ void shouldNotErrorIfOldExporterRestartsWhileNewExporterHasAlreadyStarted(
...
+
+    // when
+    camundaExporter.open(new ExporterTestController());
+
+    // then
+    final var mappingsAfterOpen =
+        adapter.getSearchEngineClient().getMappings(CONFIG_PREFIX + "*", MappingSource.INDEX);
+    assertThat(mappingsAfterOpen.keySet())
+        .isNotEmpty()
+        .hasSize(expectedIndices.length)
```
Comment (EuroLew) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java:280]: Not needed `containsExactlyInAnyOrder` fails if their sizes are different, same with `isNotEmpty()`

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java [hunk 2]
```diff
@@ -254,6 +256,70 @@ void shouldNotErrorIfOldExporterRestartsWhileNewExporterHasAlreadyStarted(
...
+        // we verify the names hard coded on purpose
+        // to make sure no index will be accidentally dropped, names are changed or added
+        .containsExactlyInAnyOrder(
+            "custom-prefix-identity-authorizations-8.7.0_",
```
Comment (EuroLew) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java:284]: We already do all the work to calculate the expected indices why not use that as the expected field

**Review by EuroLew — APPROVED** [review]
Just some minor thoughts otherwise LGTM

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java (hunk 2 above)
Comment (Zelldon) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java:284]: Because if we remove the descriptor from the DefaultResourceProvider the test will not fail, as it would reuse this. So we have no prevention of mistakenly remove an descriptor, etc.

Comment (EuroLew) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java:284]: ah ok makes sense

**Review by mustafadagher — APPROVED** [review]
LGTM!

**Comment by Zelldon** [comment]
FYI @EuroLew @mustafadagher I removed the size check with the default resource provider and related helper method. As we check statically the existence of the indices, we don't need to check the size again with the resource provider. Highlighted [here](https://github.com/camunda/camunda/pull/24834#discussion_r1848076647)
