### PR TITLE
fix(logstreams): include header length on canWrite for batchSize

### LINKED ISSUE #11480: When there is a big chunk of expired messages, then Zeebe fails to write the batch of corresponding commands
**Describe the bug**

The `MessageTimeToLiveChecker` fails to submit a batch of commands to expire a big chunk of expired message:
```
2023-01-25 20:21:34.338 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] WARN
      io.camunda.zeebe.broker.logstreams - Writing of scheduled TaskResult failed!
java.lang.IllegalArgumentException: Expected to claim segment of size 9544, but can't claim more than 8192 bytes.
        at io.camunda.zeebe.dispatcher.Dispatcher.offer(Dispatcher.java:207) ~[zeebe-dispatcher-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.dispatcher.Dispatcher.claimFragmentBatch(Dispatcher.java:164) ~[zeebe-dispatcher-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.claimBatchForEvents(LogStreamBatchWriterImpl.java:235) ~[zeebe-logstreams-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.tryWrite(LogStreamBatchWriterImpl.java:212) ~[zeebe-logstreams-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:45) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
```
**To Reproduce**
1. Configure `maxMessageSize` to 8KB
2. Publish > 10k messages to Zeebe with a TTL 5 minutes
3. Stop Zeebe
4. Wait > 5 minutes
5. Start Zeebe again
6. Wait until the `MessageTimeToLiveChecker` starts working

**Expected behavior**
* Writing the batch of commands succeeds

**Hints**
* `LogStreamBatchWriterImpl#canWriteAdditionalEvent(int, int)` does not respect the header length for each (log) entry
https://github.com/camunda/zeebe/blob/0844bf55cb63d18a0ca92399034cb04f5c708049/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImpl.java#L105-L107
* It should call `#computeBatchLength()` to calculate the correct `batchSize`:
```
public boolean canWriteAdditionalEvent(final int eventCount, final int batchSize) {
  final var batchLength = computeBatchLength(eventCount, batchSize);
  return logWriteBuffer.canClaimFragmentBatch(eventCount, batchLength);
}
```
* The 8KB `maxMessageSize` setting was just made to get it quickly reproducible.

**Environment:**
- Zeebe Version: 8.1.2

**Affected versions:**
`stable/8.0` seems not affected, there is just one implementation of `canWriteAdditionalEvent ` which makes use of computeBatchLength as suggested by @romansmirnov, [see](https://github.com/camunda/zeebe/blob/stable/8.0/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImpl.java#L100).

`8.2.0/main` is not affected as well - manually verified this with the steps to reproduce.

---

related to [SUPPORT-15740](https://jira.camunda.com/browse/SUPPORT-15740)

### PR DESCRIPTION
**Pull request by megglos**
## Description

The previous state of canWriteAdditionalEvent was missing the header length for the batchSize.

This is a specific fix for the 8.1 stable branch only. In 8.0 the affected method wasn't present. For 8.2/main I'm following up.

## Related issues

relates to #11480

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImplTest.java [hunk 1]
```diff
@@ -68,6 +68,49 @@ void canWriteAdditionalEvent() {
...
   }
 
+  /**
+   * This test asserts that {@link LogStreamBatchWriterImpl#canWriteAdditionalEvent(int, int)}
+   * computes the correct batch length before passing it on to the dispatcher to check if it's
+   * acceptable. It also verifies that the same length is passed to the dispatcher when actually
+   * writing, ensuring both methods remain consistent with each other.
+   */
+  @Test
+  void canWriteAdditionalEventWithEventCount() {
```
Comment (Zelldon) [inline logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImplTest.java:78]: I know you haven't wrote these tests, but I feel they are far to complicated and too coupled with other things. This also causes to fail the tests if we replace dispatcher for example etc. which is an underlying component.

What we actually have changed was the behavior of the `canWriteAdditionalEvent` Can I write a event with value X? Where I shouldn't be able to do so.  Meaning before it returned true, whereas it should return false. This we can add a test for I think.

**Review by ChrisKujawa — COMMENTED** [review]
Great catch and thanks for taking the opportunity to dig into the code base.

I'm not 100% sure whether this is completely what we want, or whether it is correct.

The RecordBatchEntry, for example has in their length already key and source index included https://github.com/camunda/zeebe/blob/stable/8.1/engine/src/main/java/io/camunda/zeebe/engine/api/records/RecordBatchEntry.java#L33-L36 where this is already counted as well in the writer https://github.com/camunda/zeebe/blob/bb50922a426c227fa9d18f9b29b7dc8429631239/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImpl.java#L179-L183 

I feel the complete calculation might be messed up here. Might worth to investigate this further, before we mark this issue as fixed.

File: logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImplTest.java (hunk 1 above)
Comment (megglos) [reply logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImplTest.java:78]: Fully agree on the complexity of the test, we should aim for more focused test going forward on `main` for sure. For the stable branch it might be acceptable though? Let's sync on this!

**Comment by megglos** [comment]
> Great catch and thanks for taking the opportunity to dig into the code base.
> 
> I'm not 100% sure whether this is completely what we want, or whether it is correct.
> 
> The RecordBatchEntry, for example has in their length already key and source index included https://github.com/camunda/zeebe/blob/stable/8.1/engine/src/main/java/io/camunda/zeebe/engine/api/records/RecordBatchEntry.java#L33-L36 where this is already counted as well in the writer
> 
> https://github.com/camunda/zeebe/blob/bb50922a426c227fa9d18f9b29b7dc8429631239/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImpl.java#L179-L183
> 
> I feel the complete calculation might be messed up here. Might worth to investigate this further, before we mark this issue as fixed.

Thanks for the fast feedback, I think it makes sense to sync in-person, maybe even pair on the matter? wdyt?

**Comment by megglos** [comment]
Sync outcome:
- we will adjust the value passed from `RecordBatch` to `canWriteAdditionalEvent` to only contain the metadata and the value length (previously the key and source index where included)

File: logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImplTest.java (hunk 1 above)
Comment (megglos) [reply logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImplTest.java:78]: as agreed in the sync, we will keep the tests as is for now, given they are gone on main now

**Review by ChrisKujawa — APPROVED** [review]
Thanks :+1:
