### PR TITLE
fix: suppress connection issues for background tasks

### LINKED ISSUE #25631: Background tasks logs intermediate connection issues as errors
**Description**

We can see in SaaS that a lot of intermediate connections issues are logged as errors, causing to flood the error reporting.

Expectation would be here to log this as warning, as the request/connection is retried (based on the log statement at least).

[Error](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CL7rsaOb9OHu0QE%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.cluster_name%3D%22worker-3%22%0Aresource.labels.project_id%3D%22camunda-saas-int%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%22db344356-bad0-4b67-9334-92eed8f183d1-zeebe%22;pinnedLogId=2024-12-04T16:11:15.169595315Z%2Fk7doa0vxof15qhog;cursorTimestamp=2024-12-04T16:11:15.169595315Z;startTime=2024-12-04T15:42:19.537Z;endTime=2024-12-04T16:42:19.537Z?inv=1&invt=AbjSiQ&project=camunda-saas-int):

```
java.util.concurrent.CompletionException: java.net.ConnectException: Timeout connecting to [elasticsearch-es-http/10.44.45.56:9200]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.ConnectException: Timeout connecting to [elasticsearch-es-http/10.44.45.56:9200]
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:169) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:630) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:896) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:198) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:213) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:158) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.5.jar:4.1.5]
	... 1 more
```

Error group: 

- https://console.cloud.google.com/errors/detail/CL7rsaOb9OHu0QE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjSiQ&project=camunda-saas-int
- https://console.cloud.google.com/errors/detail/CL7rsaOb9OHu0QE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjSiQ&project=camunda-saas-int-chaos

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description
Suppress stacktraces for  a collection of connection exceptions for Exporter background tasks. The actual stacktrace will still be available when requiring `DEBUG` logs. 

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #25631

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/ReschedulingTask.java [hunk 1]
```diff
@@ -70,13 +76,17 @@ private long onWorkPerformed(final int count) {
...
+        "Error occurred while performing a background task; operation will be retried";
     errorDelayMs = errorStrategy.applyAsLong(errorDelayMs);
 
-    // TODO: it's likely in some cases, we do want to log things as errors, but we need to
-    //  distinguish this from "normal" cases (e.g. missing data in ES, or ES temporarily
-    //  unavailable, etc.)
-    logger.warn(
-        "Error occurred while performing a background task; operation will be retried", error);
+    if (BACKGROUND_SUPPRESSED_EXCEPTIONS.contains(error.getCause().getClass())
+        && !logger.isDebugEnabled()) {
```
Comment (ChrisKujawa) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/ReschedulingTask.java:84]: ❓ Why we check for debugEnabled?

Comment (ChrisKujawa) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/ReschedulingTask.java:84]: I think we should not bind this to debug, I guess it is in general still interesting to see when we can't connect/communicate (we shouldn't silently fail in my opinion). 

As it is a transient error, warning makes sense to me, it is a bigger issue if it happens for longer time, then some Operator can react and see the issues in their logs. 

It is not an error as there is nothing the Operator has to do _immediately_, as it might happen from time to time.

**Review by ChrisKujawa — APPROVED** [review]
I think we should remove the dependency to the debug level and then we are fine 👍🏼 Thanks Panos :)

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/ReschedulingTask.java (hunk 1 above)
Comment (panagiotisgts) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/ReschedulingTask.java:84]: The context on which these `BACKGROUND_SUPPRESSED_EXCEPTIONS` can occur is pretty vast and vague IMO. Having the option to expand the stacktraces of these issues in case something else is acting out seems a good option to have. But I guess these could also happen throughout the exporter so they will be caught elsewhere.
