### PR TITLE
test: add ArchUnit test to enforce state modifications only from allowed places

### LINKED ISSUE #42824: Ensure that only event appliers modify state
### 

### Description

We want to ensure that only event appliers are allowed to modify state in Zeebe. This is in line with the architectural direction set in [ZEP004](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.).

This was previously attempted in [PR #12929](https://github.com/camunda/camunda/pull/12929), which added an ArchUnit test for it. However, the pull request was not merged due to some failing cases. For this issue, we should re-attempt this effort. We can explicitly exclude the known problematic cases that prevented the merge previously. Those cases have been fine so far, but we should prevent unforseen cases in the future.

### Impact

Limiting state mutations to event appliers is a crucial architectural rule in Zeebe, but today we do not actively protect it automatically. So it can be broken unintentionally. As we onboard more engineers and the codebase evolves, relying on tribal knowledge and careful reviews doesn’t scale and increases the risk of accidental regressions. Adding automated tests to enforce this rule helps us continuously validate the architecture and prevent future violations early.

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

This PR introduces an ArchUnit test to enforce that state modifications in the Zeebe engine are restricted to event appliers, as defined in [ZEP004](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#activities-during-replay), from migration classes and several exclusions (1 legacy and 2 acceptable cases).

### Background

ZEP004 establishes the event sourcing pattern for Zeebe:

> "In order to rebuild the state with the events, it is necessary that all state changes from the command processing can be applied with the events only. So, the command processing may only update the state when it also writes an event that reflects the state changes."

Limiting state mutations to event appliers is a crucial architectural rule, but until now we did not actively protect it automatically. As the codebase evolves and more engineers onboard, relying on tribal knowledge and careful reviews doesn't scale and increases the risk of accidental regressions.

### What this PR does

Adds `StateModificationArchTest` that validates:
- State-modifying methods should only be called by:
  - **Event appliers** - classes implementing `TypedEventApplier`
  - **Migration classes** - in `state.migration` package for one-time data migrations
  - **Whitelisted exceptions** - documented legacy & safe cases

### Whitelisted exceptions

The following are explicitly whitelisted with documented justifications:

| Method | Reason |
|--------|--------|
| `ProcessInstanceCreationCreateWithAwaitingResultProcessor` `.createProcessInstance` | Stores transient request metadata (requestId, streamId) for response routing; doesn't affect replay determinism |
| `DbElementInstanceState.createInstance` | Internal state coordination — calls `MutableVariableState.createScope()` |
| `DbElementInstanceState.removeInstance` | Internal state coordination — calls `MutableVariableState.removeScope()` |
| `BufferedStartMessageEventStateApplier` `.removeProcessInstanceMessageLock` | Helper used exclusively by `TypedEventApplier` implementations |
| `EventSubProcessInterruptionMarker` `.markInstanceIfInterrupted` | Helper used exclusively by `TypedEventApplier` implementations |

### Prior art

This was previously attempted in #12929 but was not merged due to failing cases. This PR addresses those cases with explicit, documented whitelisting.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes)).

## Related issues

closes #42824

### CODE REVIEW

File: qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+        public boolean test(final JavaMethod method) {
+          // Method must be in a mutable state interface
+          return method
+                  .getOwner()
+                  .getPackageName()
+                  .startsWith("io.camunda.zeebe.engine.state.mutable")
+              // Exclude getter methods that return other state classes (e.g., getJobState())
+              && !(method.getName().startsWith("get") && method.getName().endsWith("State"))
+              // Exclude the getKeyGenerator() method which returns a utility object
+              && !method.getName().equals("getKeyGenerator");
```
Comment (fabiopaini-camunda) [inline qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java]: 💭 I'm not sure I agree with these two: no methods from a `Mutable*State` class should be called from outside of event appliers.

If a `get*State` method is defined in a `Mutable*State` class then either:
- it is needed to retrieve another _mutable_ state class in order to mutate the state
- it retrieves a _non-mutable_ state class and should be defined in the _non-mutable_ parent class

Allowing the use of the `getKeyGenerator` method seems quite risky to me: it can then be used to call `nextKey` which _does_ mutate the state.

File: qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+   */
+  private static final DescribedPredicate<JavaMethod> METHODS_THAT_DIRECTLY_MODIFY_STATE =
+      new DescribedPredicate<>("directly mutate state") {
+        @Override
+        public boolean test(final JavaMethod method) {
+          // Method must be in a mutable state interface
+          return method
+                  .getOwner()
+                  .getPackageName()
+                  .startsWith("io.camunda.zeebe.engine.state.mutable")
```
Comment (fabiopaini-camunda) [inline qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java:115]: 💭 We should probably ensure that state mutations are actually performed only in classes contained in this package, but I am not sure how we could do that (I guess we could look into where the `insert`/`update`/`upsert`/`delete` methods of `ColumnFamily` are used, but currently they are usually called by the `Db*State` classes which are in a different package)

File: qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+        }
+
+        /**
+         * Checks if a class is an event applier.
+         *
+         * <p>Event appliers are located in the {@code io.camunda.zeebe.engine.state.appliers}
+         * package or implement the {@link TypedEventApplier} interface.
+         */
+        private boolean isEventApplier(final JavaClass owner) {
+          return owner.getPackageName().startsWith("io.camunda.zeebe.engine.state.appliers")
```
Comment (fabiopaini-camunda) [inline qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java]: 💭 I think we can be strict here and only allow state mutations in `TypedEventApplier`s, since those are the ones for which we generate golden files and that we are testing to check that the implementation is not changed.

**Review by fabiopaini-camunda — APPROVED** [review]
👍 Very nice work @ce-dmelnych!

I added some comments that we can discuss, but I am approving this since even if we want to change it this is a good starting point and it makes sense to merge it.

File: qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java (hunk 3 above)
Comment (ce-dmelnych) [reply qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java]: 👍🏻 I've adjusted this check to only allow `TypedEventApplier` implementations (removed the `state.appliers` package check). This required adding two helper classes to the whitelist:
 - `BufferedStartMessageEventStateApplier.removeProcessInstanceMessageLock`
 - `EventSubProcessInterruptionMarker.markInstanceIfInterrupted`
 
Both live in `state.appliers` but don't implement `TypedEventApplier`, they are used exclusively by actual `TypedEventApplier` implementations to extract reusable event-applying logic.

File: qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java (hunk 1 above)
Comment (ce-dmelnych) [reply qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java]: I see your points, but `getKeyGenerator()` and `get*State()` are called pervasively from processors, behaviors, and infrastructure code throughout the engine (e.g., BpmnBehaviorsImpl, EngineProcessors, JobEventProcessors). Command processing relies on MutableProcessingState both for reading state and generating keys.

I think enforcing these is a separate (and much larger) concern.
Restricting access to the mutable state getters and key generator would require refactoring how the processing pipeline accesses state.

Lets keep these exclusions for now, we can work on a better solution durning mob-programming session, wdyt?

File: qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java (hunk 2 above)
Comment (ce-dmelnych) [reply qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java:115]: 🤔

File: qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java (hunk 1 above)
Comment (ce-dmelnych) [reply qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java]: Also, I've adjusted the predicate to replaced the method name pattern exclusions (`get*State`, `getKeyGenerator`) with an explicit `MutableProcessingState` interface check.

File: qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java (hunk 3 above)
Comment (fabiopaini-camunda) [reply qa/archunit-tests/src/test/java/io/camunda/zeebe/engine/StateModificationArchTest.java]: I think those two cases are still anti-patterns which should be removed, since no golden files are generated for those and thus we risk changing the implementation of the appliers without introducing a new record version. I hate code duplication, but our current handling of event appliers versioning forces us to put all the logic there without referencing helper classes.

Anyway, it's ok to keep the exclusions for now, having them listed at least helps us remember that they will need to be refactored in the future.

**Review by fabiopaini-camunda — APPROVED** [review]
👍 Very nice work @ce-dmelnych.
