### PR TITLE
fix: do not leak `innerInstance` variables to parent scope

### LINKED ISSUE #51939: Regression in 8.9.1 leads to variables local to an ad-hoc sub-process inner instance scope to leak into the parent scope
### 

### 

### 

### 

### Description

A job worker acting on an ad-hoc sub-process can set variables as part of the elements activated through a [complete job adHocSubProcess result](https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/complete-job/). The AI Agent connector uses this pattern to set `toolCall` and `toolCallResult` variables on element activation:

- `toolCall` is used to transport input parameters for the current tool call to the activated element
- `toolCallResult` is set as empty variable to make it local to the inner ad-hoc sub-process instance. Tools are expected to write to this variable and it will be picked up by the `outputElement` and added to the `outputCollection`.

Starting from Camunda 8.9.1, these variables are propagated to the ad-hoc sub-process and the global scope (as the AHSP does not have any input mappings marking them as local variables for it). This breaks the interaction pattern the AI Agent uses in combination with event sub-processes: the AI Agent identifies results/data coming from event sub-processes as having *no `toolCall ID` available in the scope. However, as the `toolCall` from previous activations now leaks to the upper scope and therefore is propagated down to the event sub-process, it breaks this pattern.

Confirmed that the pattern worked with 8.9.0 and started breaking with 8.9.1, potentially with commit https://github.com/camunda/camunda/commit/24ce8475a1a.

### Steps to reproduce

1. On a Camunda 8.9.1 cluster (also running connectors 8.9.1 with available AWS Bedrock credentials), deploy and start the attached process without additional inputs
2. The process will call a couple of tools and eventually end up in the `Wait for Status Update` activity
3. Send a message with the name `Report`, using the `missionKey` from the process as `correlationKey`. Example payload:

  ```json
  {
    "name": "Report",
    "correlationKey": "019dcfa165277",
    "variables": {
      "report": "20 more damage"
    }
  }
  ```

Image

[inner-instance-leak.bpmn.xml](https://github.com/user-attachments/files/27132836/inner-instance-leak.bpmn.xml)

### Current behavior

An incident is created as the AI Agent tries to use a duplicate tool call ID to its payload. The output collection `toolCallResults` contains an element from the event sub-process using tool call ID and name from the `Wait for Status Update` element activation. Example `toolCallResults`:

```json
[
	{
		"id": "tooluse_hLPSSE0LyeWcRV2rlh8t5M",
		"name": "Wait_For_Status_Update",
		"content": {
			"NewReportFromSensors": "20 more damage"
		}
	}
]
```

### Expected behavior

ID and Name are missing/null for the event payload as no `toolCall` variable exists in the event subprocess activation scope.

### Workaround

Explicitly model the event subprocess to produce a `toolCall` variable with an empty result. This works, but is a workaround and does not fix existing processes running into this issue after an upgrade.

Image

### Environment

SaaS & SM

### Version

- Component Version: Camunda 8.9.1

### Rootcause

A behavioral change, probably introduced or surfaced in https://github.com/camunda/camunda/commit/24ce8475a1a. Confirmed that the expected behavior is restored when reverting that commit.

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by konstantinos-mylosis**
## Description

Fixes unintended variable propagation from ad-hoc sub-process activations introduced in 8.9.1, which caused `toolCall` data to leak into parent and event sub-process scopes.
Restores expected scoping behavior so variables created during inner activations remain local unless explicitly mapped.
Ensures AI Agent interaction patterns work correctly again, preventing duplicate tool call IDs and incorrect `toolCallResults`.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #51939

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java [hunk 1]
```diff
@@ -1203,6 +1203,56 @@ public void shouldCompleteAgenticJobWithFollowupMetadata() {
...
+
+    // sanity check: the output mapping was actually applied
+    Assertions.assertThat(
+            RecordingExporter.records()
+                .limit(r -> r.getPosition() > innerInstanceCompleted.getPosition())
+                .variableRecords()
+                .withProcessInstanceKey(processInstanceKey)
+                .withName("outputResult"))
+        .as("output mapping for service task A must have produced `outputResult`")
+        .isNotEmpty();
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java]: ❌ Let's improve this assertion.

1. You are starting with a limit on a position > inner instance completed position. This is any record that comes after the inner instance completed. As there's no safeguard on what this is this could be flaky. It's better to limit this after the filters. (Or even better, complete the process and limit on process instance completion).
2. You are filtering for a variable record, but not what you want with this variable. There's no intent defined so it's unclear what you're actually verifying here. Is it a variable creation, an update? A rejection of one of those?

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java [hunk 2]
```diff
@@ -1203,6 +1203,56 @@ public void shouldCompleteAgenticJobWithFollowupMetadata() {
...
+
+    Assertions.assertThat(
+            RecordingExporter.records()
+                .limit(r -> r.getPosition() > innerInstanceCompleted.getPosition())
+                .variableRecords()
+                .withProcessInstanceKey(processInstanceKey)
+                .withName("toolCall"))
+        .extracting(r -> r.getValue().getScopeKey())
+        .containsOnly(innerInstanceCompleted.getKey());
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java:1262]: ❌ Pretty much the same comment as above.

1. You have the same limit here. You want to verify something only happened once. I think it's better to complete the process isntance and verify it really only happened once instead of relying on the one record after the inner instsance completion.
2. There is no intent defined. What do you want to only happen once?

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]
@konstantinos-mylosis We should improve the test a bit, otherwise it looks fine.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java (hunk 1 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java]: changed this to check existence

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java (hunk 2 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java:1262]: - limit based on `processCompleted` position
- Added intents

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java [hunk 3]
```diff
@@ -1203,6 +1203,65 @@ public void shouldCompleteAgenticJobWithFollowupMetadata() {
...
+            RecordingExporter.variableRecords(VariableIntent.CREATED)
+                .withProcessInstanceKey(processInstanceKey)
+                .withName("outputResult")
+                .exists())
+        .as("output mapping for service task A must have produced `outputResult`")
+        .isTrue();
+
+    Assertions.assertThat(
+            RecordingExporter.records()
+                .limit(r -> r.getPosition() >= processCompleted.getPosition())
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java:1256]:
```suggestion
                .limitToProcessInstanceCompleted()
```

When you do this please make sure to move the filter for process instance key above the limit.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java [hunk 4]
```diff
@@ -1203,6 +1203,65 @@ public void shouldCompleteAgenticJobWithFollowupMetadata() {
...
+            .getFirst();
+
+    // complete the ad-hoc sub-process
+    // guaranteed that all variable records of interest have been exported
+    completeJob(ahspJobType, true, false);
+    final var processCompleted =
+        RecordingExporter.processInstanceRecords(ELEMENT_COMPLETED)
+            .withProcessInstanceKey(processInstanceKey)
+            .withElementId(PROCESS_ID)
+            .getFirst();
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java:1243]: 🙃 Don't really need this

**Review by remcowesterhoud — APPROVED** [review]
Some minor comments, but I'll pre-approve

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java (hunk 3 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java:1256]: @remcowesterhoud I think this is available only for `ProcessInstanceRecordStream`

Comment (remcowesterhoud) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java:1256]: Ah that's true. Sorry I didn't realize you were on the generic records stream.
