### PR TITLE
fix: skip deserialize when verifyRepositoryExists

### LINKED ISSUE #33905: Missing RepositorySettings.location error in Optimize backups
### 

### 

### 

### 

### Description

Optimize users are not able to get backups when they use S3 and Opensearch.

When S3 is used as backup repository , AWS opensearch returns a response without a mandatory location field in org.opensearch.client.opensearch.snapshot.RepositorySettings.

### Steps to reproduce

1. create backup in S3 using opensearch
2. try to GET Optimize backups
```
curl --location --request GET 'http://localhost:8092/actuator/backups/110' \
--header 'Content-Type: application/json' \
--data '{ "backupId": "110" }'
```
3. command fails with
```
Caused by: java.lang.RuntimeException: Missing required property 'RepositorySettings.location'
	at org.opensearch.client.transport.aws.AwsSdk2Transport.extractAndWrapCause(AwsSdk2Transport.java:667)

```

### Current behavior

Users cannot get Opensearch Optimize backup when using S3

### Expected behavior

Users can get Opensearch Optimize backup when using S3

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

Looking at the [stacktrace](https://jira.camunda.com/secure/attachment/101824/101824_camunda-onboarding-optimize-f4bf86648-rzryp.txt)
```Caused by: java.lang.RuntimeException: Missing required property 'RepositorySettings.location'
	at org.opensearch.client.transport.aws.AwsSdk2Transport.extractAndWrapCause(AwsSdk2Transport.java:667)
	at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:206)
	at org.opensearch.client.opensearch.snapshot.OpenSearchSnapshotClient.getRepository(OpenSearchSnapshotClient.java:308)
	at io.camunda.optimize.service.db.os.OptimizeOpenSearchClient.verifyRepositoryExists(OptimizeOpenSearchClient.java:1038)
```
When we try to verify a repository exists, we're unable to send a `location` property. This is because when S3 is used as backup, AWS doesn't return that in the response when fetching the backup repo.

Looking through the code, the [verifyRepositoryExists](https://github.com/camunda/camunda/blob/f9655efad1783c2bb513a39d37818290a6af0738/optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/db/os/OptimizeOpenSearchClient.java#L1051) method doesn't care about the return value.

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

https://app.incident.io/camunda/incidents/2978?source=slack_bookmark
[SUPPORT-27316](https://jira.camunda.com/browse/SUPPORT-27316)

### PR DESCRIPTION
**Pull request by abremard**
## Description

Looking at the [stacktrace](https://jira.camunda.com/secure/attachment/101824/101824_camunda-onboarding-optimize-f4bf86648-rzryp.txt)
```
Caused by: java.lang.RuntimeException: Missing required property 'RepositorySettings.location'
	at org.opensearch.client.transport.aws.AwsSdk2Transport.extractAndWrapCause(AwsSdk2Transport.java:667)
	at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:206)
	at org.opensearch.client.opensearch.snapshot.OpenSearchSnapshotClient.getRepository(OpenSearchSnapshotClient.java:308)
	at io.camunda.optimize.service.db.os.OptimizeOpenSearchClient.verifyRepositoryExists(OptimizeOpenSearchClient.java:1038)
```

The same bug described in [this PR](https://github.com/camunda/camunda/pull/27225#issue-2802453741) is happening for Optimize backups. S3 backup response doesn't return a `location` field which makes the deserialization break. Same as in Tasklist, we don't need the response so we can skip it.

## Related issues

closes #33905

### CODE REVIEW

File: optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/db/os/OptimizeOpenSearchClient.java [hunk 1]
```diff
@@ -1048,9 +1051,19 @@ public void waitUntilTaskIsFinished(final String taskId, final String taskItemId
     }
   }
 
+  @VisibleForTesting
```
Comment (houssain-barouni) [inline optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/db/os/OptimizeOpenSearchClient.java]: the method is already public, so no need to use the annotation (you did not upgrade the visibility of the method to use it in the unit tests)
```suggestion
```

**Review by houssain-barouni — APPROVED** [review]
LGTM! 🚀 
I would also check with an ex-optimize engineer, maybe @buccarel can have a look?

**Comment by abremard** [comment]
Since this fix is quite urgent for the customer, most engineers are off for a long weekend and we already have one approval, I will go ahead and merge it
