### PR TITLE
Check for message names being null during validation

### LINKED ISSUE #9083: NPE in Validator
**Description**

https://console.cloud.google.com/errors/detail/CP7rvtL2xonR5QE;service=zeebe;time=P7D?project=camunda-cloud-240911

A NPE was thrown while validating a message start event. The start event apparently had a message with no name. This seems to be a user error.

The null value should probably not be logged, but reported as validation error back to the client.

```
java.lang.NullPointerException: expression
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.EnsureUtil.ensureNotNull(EnsureUtil.java:20) ~[zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.el.impl.FeelExpressionLanguage.parseExpression(FeelExpressionLanguage.java:56) ~[zeebe-expression-language-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.model.validation.ProcessMessageStartEventMessageNameValidator.validateMessageName(ProcessMessageStartEventMessageNameValidator.java:60) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.model.validation.ProcessMessageStartEventMessageNameValidator.lambda$validate$0(ProcessMessageStartEventMessageNameValidator.java:47) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$Itr.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.validation.ProcessMessageStartEventMessageNameValidator.validate(ProcessMessageStartEventMessageNameValidator.java:47) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.model.validation.ProcessMessageStartEventMessageNameValidator.validate(ProcessMessageStartEventMessageNameValidator.java:26) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.lambda$visit$0(ValidationVisitor.java:51) ~[zeebe-bpmn-model-1.3.6.jar:1.3.6]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.visit(ValidationVisitor.java:51) ~[zeebe-bpmn-model-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:61) ~[zeebe-bpmn-model-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnValidator.validate(BpmnValidator.java:41) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:119) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:96) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:100) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:297) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:287) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:252) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:212) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:188) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) [zeebe-util-1.3.6.jar:1.3.6] 
```

### PR DESCRIPTION
**Pull request by pihme**
## Description

* Adds a test that a validation error is generated if the message name is null
* Adds validation logic for message name being null 

## Related issues

closes #9083

## Definition of Done

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ProcessMessageStartEventMessageNameValidator.java [hunk 1]
```diff
@@ -57,6 +57,13 @@ private void validateMessageName(
       return;
     }
     final String nameExpression = message.getName();
+    if (nameExpression == null) {
+      resultCollector.addError(
+          0,
+          "Message name/expression must not be null. It is null in "
+              + messageEventDefinition.getId());
```
Comment (saig0) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ProcessMessageStartEventMessageNameValidator.java:64]: :thought_balloon: This change might result in an unexpected rejection message. 

The message name should be already checked by the [MessageValidator](https://github.com/camunda/zeebe/blob/f339fc92ed93ede99f040c9b4c602b1940bfde6a/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/MessageValidator.java#L59-L64). I assume that the validator already adds the failure message. We see the NPE because the validator chain is not interrupted. 

As a result, we might see now two error messages that mention that the message name is null. 

Please do a manual test and verify the rejection message.

**Review by saig0 — COMMENTED** [review]
@pihme looks good in general :+1: 

But I'm unsure about the rejection message. I have the feeling that we will mention the same validation twice. Please check my comment.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ProcessMessageStartEventMessageNameValidator.java (hunk 1 above)
Comment (pihme) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ProcessMessageStartEventMessageNameValidator.java:64]: You were correct

**Review by saig0 — APPROVED** [review]
@pihme LGTM :rocket:

**Comment by pihme** [comment]
bors merge
