### PR TITLE
Ignore misconfigured execution listeners

### LINKED ISSUE #27895: Misconfigured execution listener can cause banned instances
**Describe the bug**

In versions up to and including 8.4, it's possible to deploy a process (and start instances of it) with misconfigured execution listeners. For example, without a listener `type`. This is the default behavior in Modeler targeting 8.4, and does not produce a linting error for that version.

When updating to 8.5, this can cause two issues:
- DEAD partition, if the process is needed during replay
- banned instance, if a command for an instance looks up the process during processing

These issues have the same root cause: transformation of the execution listener fails due to NullPointerException.

https://jira.camunda.com/browse/SUPPORT-25748

**To Reproduce**

DEAD partition:
- Deploy a process with an execution listener without a `type` and a service task on 8.4 or before
- Update to 8.5, notice that the partition is DEAD

<details><summary>Reproducing (but slow) test</summary>
<p>

```java
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.zeebe.it.processing;

import static org.assertj.core.api.Assertions.assertThat;

import io.camunda.zeebe.client.ZeebeClient;
import io.camunda.zeebe.test.util.junit.AutoCloseResources;
import io.camunda.zeebe.test.util.testcontainers.ContainerLogsDumper;
import io.zeebe.containers.ZeebeVolume;
import io.zeebe.containers.cluster.ZeebeCluster;
import java.time.Duration;
import org.agrona.CloseHelper;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testcontainers.containers.Network;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

/** Verifies that data can be isolated per tenant using Identity as the tenant provider. */
@Testcontainers
@AutoCloseResources
public class ExecutionListenerMisconfiguredIT {

  public static final String PROCESS =
      """
      <?xml version="1.0" encoding="UTF-8"?>
      <bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_1us9pzw" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.31.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.4.0">
        <bpmn:process id="Process_0mklvug" isExecutable="true">
          <bpmn:extensionElements>
            <zeebe:executionListeners>
              <zeebe:executionListener eventType="start" />
            </zeebe:executionListeners>
          </bpmn:extensionElements>
          <bpmn:startEvent id="StartEvent_1">
            <bpmn:outgoing>Flow_1dbohbp</bpmn:outgoing>
          </bpmn:startEvent>
          <bpmn:sequenceFlow id="Flow_1dbohbp" sourceRef="StartEvent_1" targetRef="Activity_0my4c9i" />
          <bpmn:endEvent id="Event_1er6qvm">
            <bpmn:incoming>Flow_0pdsvap</bpmn:incoming>
          </bpmn:endEvent>
          <bpmn:sequenceFlow id="Flow_0pdsvap" sourceRef="Activity_0my4c9i" targetRef="Event_1er6qvm" />
          <bpmn:serviceTask id="Activity_0my4c9i" name="test">
            <bpmn:extensionElements>
              <zeebe:taskDefinition type="test" />
            </bpmn:extensionElements>
            <bpmn:incoming>Flow_1dbohbp</bpmn:incoming>
            <bpmn:outgoing>Flow_0pdsvap</bpmn:outgoing>
          </bpmn:serviceTask>
        </bpmn:process>
        <bpmndi:BPMNDiagram id="BPMNDiagram_1">
          <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_0mklvug">
            <bpmndi:BPMNShape id="StartEvent_1_di" bpmnElement="StartEvent_1">
              <dc:Bounds x="182" y="102" width="36" height="36" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Event_1er6qvm_di" bpmnElement="Event_1er6qvm">
              <dc:Bounds x="422" y="102" width="36" height="36" />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNShape id="Activity_1qwy544_di" bpmnElement="Activity_0my4c9i">
              <dc:Bounds x="270" y="80" width="100" height="80" />
              <bpmndi:BPMNLabel />
            </bpmndi:BPMNShape>
            <bpmndi:BPMNEdge id="Flow_1dbohbp_di" bpmnElement="Flow_1dbohbp">
              <di:waypoint x="218" y="120" />
              <di:waypoint x="270" y="120" />
            </bpmndi:BPMNEdge>
            <bpmndi:BPMNEdge id="Flow_0pdsvap_di" bpmnElement="Flow_0pdsvap">
              <di:waypoint x="370" y="120" />
              <di:waypoint x="422" y="120" />
            </bpmndi:BPMNEdge>
          </bpmndi:BPMNPlane>
        </bpmndi:BPMNDiagram>
      </bpmn:definitions>
      """;

  private static final Logger LOGGER =
      LoggerFactory.getLogger(ExecutionListenerMisconfiguredIT.class);

  private static final Network NETWORK = Network.newNetwork();
  private static final ZeebeVolume volume = ZeebeVolume.newVolume();

  @Container
  private static final ZeebeCluster CLUSTER =
      ZeebeCluster.builder()
          .withImage(DockerImageName.parse("camunda/zeebe:8.4.10"))
          .withBrokersCount(1)
          .withEmbeddedGateway(true)
          .withPartitionsCount(1)
          .withReplicationFactor(1)
          .withBrokerConfig(
              broker ->
                  broker
                      .withZeebeData(volume)
                      .withEnv("ZEEBE_LOG_LEVEL", "DEBUG")
                      .withEnv("ZEEBE_BROKER_NETWORK_MAXMESSAGESIZE", "1MB")
                      .withEnv("ZEEBE_BROKER_DATA_LOGSEGMENTSIZE", "16MB"))
          .withNetwork(NETWORK)
          .build();

  @SuppressWarnings("unused")
  @RegisterExtension
  final ContainerLogsDumper logsWatcher = new ContainerLogsDumper(CLUSTER::getBrokers, LOGGER);

  private ZeebeClient client;

  @BeforeEach
  void beforeEach() {
    client = CLUSTER.newClientBuilder().build();
  }

  @AfterEach
  void afterEach() {
    CloseHelper.quietCloseAll(client);
  }

  @Test
  @Timeout(value = 30, unit = java.util.concurrent.TimeUnit.SECONDS)
  void shouldConnectWithoutConfiguredCredentials() {
    // given
    CLUSTER.start();

    try (final var client =
        CLUSTER
            .newClientBuilder()
            .defaultRequestTimeout(Duration.ofSeconds(10))
            .usePlaintext()
            .build()) {
      final var topology = client.newTopologyRequest().send().join();
      assertThat(topology.getBrokers()).hasSize(1);

      client
          .newDeployResourceCommand()
          .addResourceStringUtf8(PROCESS, "process.bpmn")
          .send()
          .join();

      client
          .newCreateInstanceCommand()
          .bpmnProcessId("Process_0mklvug")
          .latestVersion()
          .send()
          .join();
    }

    CLUSTER.stop();

    // when update to 8.6.8
    CLUSTER.getBrokers().values().stream()
        .findFirst()
        .get()
        .setDockerImageName("camunda/zeebe:current-test");

    // then this will probably fail to complete due to the replay error
    CLUSTER.start();

    // then
    try (final var client =
        CLUSTER
            .newClientBuilder()
            .defaultRequestTimeout(Duration.ofSeconds(10))
            .usePlaintext()
            .build()) {
      // when
      final var topology = client.newTopologyRequest().send().join();
      assertThat(topology.getBrokers()).hasSize(1);

      // now retry the using the deployed process
      client
          .newCreateInstanceCommand()
          .bpmnProcessId("Process_0mklvug")
          .latestVersion()
          .send()
          .join();
    }
    assert false;

    // cleanup
    CLUSTER.close();
  }
}
```

</p>
</details> 

Banned instance:

- Deploy a process with an execution listener without a `type` and a service task on 8.4 or before
- Ensure all records regarding this process are compacted
- Update to 8.5
- Activate and complete the jobs of the service task to trigger the bug
- Notice that the instance is banned

**Expected behavior**

- 8.4 did not yet support execution listeners, so misconfigured listeners can simply be ignored.
- We should log to highlight the issue

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Failed to replay batch at 'LoggedEvent [position=265941198, key=6755399573757618, timestamp=1738933193844, sourceEventPosition=265941196] RecordMetadata{recordType=EVENT, valueType=PROCESS_EVENT, intent=TRIGGERING, authorization=UNKNOWN}'
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:170) ~[zeebe-stream-platform-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:85) ~[zeebe-scheduler-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.8.jar:8.6.8]
Caused by: java.lang.NullPointerException: expression
	at java.base/java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.EnsureUtil.ensureNotNull(EnsureUtil.java:20) ~[zeebe-util-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.el.impl.FeelExpressionLanguage.parseExpression(FeelExpressionLanguage.java:57) ~[zeebe-expression-language-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer.addListenerToFlowNode(ExecutionListenerTransformer.java:33) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer.lambda$transform$0(ExecutionListenerTransformer.java:23) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer.transform(ExecutionListenerTransformer.java:22) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.ProcessTransformer.lambda$transformExecutionListeners$0(ProcessTransformer.java:52) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.ProcessTransformer.transformExecutionListeners(ProcessTransformer.java:50) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.ProcessTransformer.transform(ProcessTransformer.java:41) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.ProcessTransformer.transform(ProcessTransformer.java:20) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:115) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:343) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupPersistenceStateForProcessByKey(DbProcessState.java:569) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getProcessByKeyAndTenant(DbProcessState.java:459) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement(DbProcessState.java:496) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.state.appliers.EventSubProcessInterruptionMarker.markInstanceIfInterrupted(EventSubProcessInterruptionMarker.java:43) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.state.appliers.ProcessEventTriggeringApplier.applyState(ProcessEventTriggeringApplier.java:54) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.state.appliers.ProcessEventTriggeringApplier.applyState(ProcessEventTriggeringApplier.java:20) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:499) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.engine.Engine.replay(Engine.java:102) ~[zeebe-workflow-engine-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayEvent(ReplayStateMachine.java:237) ~[zeebe-stream-platform-8.6.8.jar:8.6.8]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:210) ~[zeebe-stream-platform-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:109) ~[zeebe-db-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:208) ~[zeebe-stream-platform-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:164) ~[zeebe-stream-platform-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[zeebe-scheduler-8.6.8.jar:8.6.8]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:83) ~[zeebe-scheduler-8.6.8.jar:8.6.8]
	... 5 more

```

</p>
</details>

### LINKED ISSUE #27905: Ignore misconfigured execution listeners
As a way to patch the problem presented in #27895, we can simply ignore the misconfigured listeners. We should of course log about them in the transformers for debugging purposes.

### PR DESCRIPTION
**Pull request by korthout**
## Description

This PR ensures we ignore misconfigured execution listeners. For example, when no listener `type` is provided.

It was possible to deploy such processes in 8.4, but they can cause problems in later releases.

I've also tested this using the slow test in the bug description. It shows the following logged line:

>2025-02-10 10:37:42.581 [Broker-0] [zb-actors-0] [StreamProcessor-1] DEBUG io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer - Failed to transform execution listener for flow node 'Process_0mklvug', because 'type' is null. Ignoring this listener definition.

## Related issues

closes #27905

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/ExecutionListenerTransformerTest.java [hunk 1]
```diff
@@ -0,0 +1,291 @@
...
+    // when
+    final var listener = new FakeZeebeExecutionListener("start", "type", "3");
+    new ExecutionListenerTransformer()
+        .transform(process, List.of(listener), new FakeExpressionLanguage());
+
+    // then
+    Assertions.assertThat(process.hasExecutionListeners()).isTrue();
+  }
+
+  static final class FakeZeebeExecutionListener implements ZeebeExecutionListener {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/ExecutionListenerTransformerTest.java:56]: 🔧 I know you don't like mocking, but all these overrides though 😅 I'd consider just adding a mock

**Review by remcowesterhoud — APPROVED** [review]
Thanks for taking ownership of this one @korthout 🚀

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/ExecutionListenerTransformerTest.java (hunk 1 above)
Comment (korthout) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/ExecutionListenerTransformerTest.java:56]: 💡 I tried changing L49 from:

```java
final var listener = new FakeZeebeExecutionListener("start", "type", "3");
```
Screenshot 2025-02-10 at 16 55 14

to:

```java
final var listener = Mockito.mock(ZeebeExecutionListener.class);
Mockito.when(listener.getEventType()).thenReturn(ZeebeExecutionListenerEventType.start);
Mockito.when(listener.getType()).thenReturn("type");
Mockito.when(listener.getRetries()).thenReturn("3");
```
Screenshot 2025-02-10 at 16 55 30

Comment (remcowesterhoud) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/ExecutionListenerTransformerTest.java:56]: Guess I'll take back my comment 🤣

Comment (korthout) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/ExecutionListenerTransformerTest.java:56]: All good, makes total sense. Honestly, it's in some ways easier to read/understand. I was just kinda surprised about this difference. I wonder whether I do something wrong.

Comment (remcowesterhoud) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/ExecutionListenerTransformerTest.java:56]: I wonder if this is just a one time thing for the test class, or if this performance degredation happens on every case.

Comment (korthout) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/ExecutionListenerTransformerTest.java:56]: Seems that Mockito initialization is slow 
- https://github.com/mockito/mockito/issues/2423

💭 Shoutout to our @npepinpe chiming in there 
https://github.com/mockito/mockito/issues/2423#issuecomment-917408016
