### PR TITLE
fix: Use Decision Instance Primary Key in GET Endpoint

### LINKED ISSUE #24664: Use Decision Instance Primary Key in GET Endpoint
### Issue Description

After evaluating a DRD that includes multiple decisions, retrieving a decision instance by key using the current API results in an HTTP 500 error.

### Steps to Reproduce

1- Deploy a DRD that contains multiple decisions. For example, use [this DMN file](https://github.com/camunda/camunda/blob/main/operate/qa/integration-tests/src/test/resources/invoiceBusinessDecisions_v_1.dmn).
2- Evaluate the root decision and note the `DecisionInstanceKey` from the response.
3- Make a GET request to `/v2/decision-instance/{DecisionInstanceKey`}.

### Current Behavior

The request returns an HTTP 500 error.

### Root Cause

The `DecisionInstanceKey` is not a unique identifier for a decision instance. The primary key for decision instance entities should be a `id` which is a concatenated string consisting of the DecisionInstanceKey and the evaluated decision index. This `id` should be used as the unique identifier of a DecisionInstance entity.

### Proposed Solution

* Introduce a new field, decisionInstanceId, in the API:
* Add this field to the `POST /v2/decision-instances/search` endpoint (as both a filter in the query and a field in the DecisionInstanceItem response).
* Replace the current `GET /v2/decision-instance/{decisionInstanceKey}` endpoint with `GET /v2/decision-instance/{decisionInstanceId}` where decisionInstanceId is a string.
* Update the Zeebe client to reflect these changes.

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

- replaces `GET /v2/decision-instances/{decisionInstanceKey}` by `GET /v2/decision-instances/{decisionInstanceId}`
- adds `decisionInstanceId` search filter to `POST /v2/decision-instances/search`
- adds  `decisionInstanceId` attribute to DecisionInstance items
- Zeebe client is accordingly updated
- DecisionInstance query integration tests are moved to the new IT style (based on `BrokerWithCamundaExporterITInvocationProvider` test extension)

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #24664

### CODE REVIEW

File: clients/java/src/main/java/io/camunda/zeebe/client/api/search/response/DecisionInstance.java [hunk 1]
```diff
@@ -26,6 +26,11 @@ public interface DecisionInstance {
    */
   long getDecisionInstanceKey();
 
+  /**
+   * @return the id of the decision instance
```
Comment (christinaausley) [inline clients/java/src/main/java/io/camunda/zeebe/client/api/search/response/DecisionInstance.java:30]:
```suggestion
   * @return the ID of the decision instance
```

Nitpick to uppercase ID 👍

File: service/src/main/java/io/camunda/service/DecisionInstanceServices.java [hunk 2]
```diff
@@ -69,23 +69,22 @@ public SearchQueryResult<DecisionInstanceEntity> search(final DecisionInstanceQu
   }
 
   /**
-   * Get a Decision Instance by its key.
+   * Get a Decision Instance by its id.
```
Comment (christinaausley) [inline service/src/main/java/io/camunda/service/DecisionInstanceServices.java:72]:
```suggestion
   * Get a Decision Instance by its ID.
```

File: service/src/main/java/io/camunda/service/DecisionInstanceServices.java [hunk 3]
```diff
@@ -69,23 +69,22 @@ public SearchQueryResult<DecisionInstanceEntity> search(final DecisionInstanceQu
...
    *
-   * @param decisionInstanceKey the key of the Decision Instance
+   * @param decisionInstanceId the id of the Decision Instance
```
Comment (christinaausley) [inline service/src/main/java/io/camunda/service/DecisionInstanceServices.java:74]:
```suggestion
   * @param decisionInstanceId the ID of the decision instance
```

File: service/src/main/java/io/camunda/service/DecisionInstanceServices.java [hunk 4]
```diff
@@ -69,23 +69,22 @@ public SearchQueryResult<DecisionInstanceEntity> search(final DecisionInstanceQu
...
    * @return the Decision Instance
-   * @throws NotFoundException if the Decision Instance with the given key does not exist
-   * @throws CamundaSearchException if the Decision Instance with the given key exists more than
-   *     once
+   * @throws NotFoundException if the Decision Instance with the given id does not exist
```
Comment (christinaausley) [inline service/src/main/java/io/camunda/service/DecisionInstanceServices.java:76]:
```suggestion
   * @throws NotFoundException if the decision instance with the given ID does not exist
```

File: service/src/main/java/io/camunda/service/DecisionInstanceServices.java [hunk 5]
```diff
@@ -69,23 +69,22 @@ public SearchQueryResult<DecisionInstanceEntity> search(final DecisionInstanceQu
...
+   * @throws CamundaSearchException if the Decision Instance with the given id exists more than once
```
Comment (christinaausley) [inline service/src/main/java/io/camunda/service/DecisionInstanceServices.java:77]:
```suggestion
   * @throws CamundaSearchException if the decision instance with the given ID exists more than once
```

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml [hunk 6]
```diff
@@ -1717,13 +1717,12 @@ paths:
         This endpoint is an alpha feature and may be subject to change
         in future releases.
       parameters:
-        - name: decisionInstanceKey
+        - name: decisionInstanceId
           in: path
           required: true
-          description: The assigned key of the decision instance, which acts as a unique identifier for this decision instance.
+          description: The assigned id of the decision instance, which acts as a unique identifier for this decision instance.
```
Comment (christinaausley) [inline zeebe/gateway-protocol/src/main/proto/rest-api.yaml:1723]:
```suggestion
          description: The assigned ID of the decision instance, which acts as a unique identifier for this decision instance.
```

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml [hunk 7]
```diff
@@ -1742,7 +1741,7 @@ paths:
                 $ref: "#/components/schemas/ProblemDetail"
         "404":
           description: >
-            The decision instance with the given key was not found.
+            The decision instance with the given id was not found.
```
Comment (christinaausley) [inline zeebe/gateway-protocol/src/main/proto/rest-api.yaml:1744]:
```suggestion
            The decision instance with the given ID was not found.
```

**Review by christinaausley — COMMENTED** [review]
Some minor casing adjustments proposed 👍

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml [hunk 8]
```diff
@@ -4728,6 +4727,9 @@ components:
           type: integer
           format: int64
           description: The key of the decision instance.
```
Comment (stoerti) [inline zeebe/gateway-protocol/src/main/proto/rest-api.yaml:4729]: 💭 Make clear here that the key is *not* a unique PK for this entity (in contrast to all other entities)?

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml [hunk 9]
```diff
@@ -4781,6 +4783,9 @@ components:
...
```
Comment (stoerti) [inline zeebe/gateway-protocol/src/main/proto/rest-api.yaml:4785]: 💭 Make clear here that the key is not a unique PK for this entity (in contrast to all other entities)?

**Review by stoerti — APPROVED** [review]
Looks good to me. 👍 

Added a few documentation proposals.
