### PR TITLE
Exclude specific version upgrades from compatibility matrix

### LINKED ISSUE #40683: RollingUpdateTest is failing
RollingUpdateTest is failing in the CI currently. 
One issue identified is that clusters with version 8.4.0 are not becoming ready even though they are ready per the readiness indicator and all partitions are healthy.
There might be more problematic versions, this is just one issue that was identified.

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #40683

### CODE REVIEW

File: zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java [hunk 1]
```diff
@@ -42,6 +42,20 @@ final class VersionCompatibilityMatrix {
...
+   * Explicitly known incompatible upgrade paths which must be excluded from the compatibility
+   * matrix.
+   *
+   * <p>IMPORTANT: this is intentionally a whitelist of exceptions, not general logic. Each entry
+   * documents a path that is known to be unsupported.
+   */
+  private static final List<UpgradePath> INCOMPATIBLE_UPGRADES =
+      List.of(
+          // https://camunda.slack.com/archives/C013MEVQ4M9/p1763733819656189?thread_ts=1763726918.300319&cid=C013MEVQ4M9
+          new UpgradePath(parseVersion("8.5.17"), parseVersion("8.6.0"))
```
Comment (entangled90) [inline zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java]: 🔧 I think we should include the first patch release of the next minor that it can be upgraded to.

Usually what happens is that we add a new event in version `8.5.16` and that makes the upgrade impossible up to the first patch that handles that event as well, e.g. `8.6.13`.
Ideally we would write something like:
```java
new UpgradePath(parseVersion("8.5.17"), parseVersion("8.6.13"))
```

Which indicates that all versions after `8.5.17` are not compatible for the range `8.6.0...8.6.12

File: zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java [hunk 2]
```diff
@@ -200,6 +233,22 @@ public Stream<SemanticVersion> discoverVersions() {
...
+  private static SemanticVersion parseVersion(final String version) {
+    return SemanticVersion.parse(version)
+        .orElseThrow(
+            () -> new IllegalArgumentException("Invalid semantic version string: " + version));
+  }
+
+  private static boolean isKnownIncompatibleUpgrade(
+      final SemanticVersion from, final SemanticVersion to) {
+    return INCOMPATIBLE_UPGRADES.stream()
+        .anyMatch(path -> path.from.equals(from) && path.to.equals(to));
```
Comment (entangled90) [inline zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java]: See comment above, it would be nice to specify the first patch that is compatible, so that we can check ranges directly

File: zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java [hunk 3]
```diff
@@ -200,6 +242,44 @@ public Stream<SemanticVersion> discoverVersions() {
     return versions.stream().filter(version -> !unreleasedVersions.contains(version));
   }
 
+  private static SemanticVersion parseVersion(final String version) {
+    return SemanticVersion.parse(version)
+        .orElseThrow(
+            () -> new IllegalArgumentException("Invalid semantic version string: " + version));
+  }
+
+  private static boolean isKnownIncompatibleUpgrade(
```
Comment (entangled90) [inline zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java]: 🔧 I think we can just define method `isCompatible`, not sure why but I found it a bit more confusing to read, but it's just personal taste

File: zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java [hunk 4]
```diff
@@ -200,6 +242,44 @@ public Stream<SemanticVersion> discoverVersions() {
...
+      final SemanticVersion from, final SemanticVersion to) {
+    return INCOMPATIBLE_UPGRADES.stream()
+        .anyMatch(
+            path -> {
+              final var lowerBoundFrom = path.from();
+              final var firstCompatibleTo = path.to();
+
+              // same major/minor as lowerBoundFrom, and patch >= lowerBoundFrom.patch
+              if (from.major() != lowerBoundFrom.major()
```
Comment (entangled90) [inline zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java:260]: 💭 in general I think a new major will be incompatible with the previous one, however we will have to define an upgrade path, so better to consider it "compatible" now and make the test fail so that we can then decide what to do 👍 

Let's also keep in mind a new major is not near :-D

**Review by entangled90 — APPROVED** [review]
Thanks 🚀

File: zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java (hunk 4 above)
Comment (berkaycanbc) [reply zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java:260]: Yeah, I was hesitant to add it or not. But it felt more natural to consider all upgrade types at the end. Indeed, incompatibility usually resonates with the idea of major changes 🙃.

> Let's also keep in mind a new major is not near :-D

😆

File: zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java (hunk 3 above)
Comment (berkaycanbc) [reply zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/VersionCompatibilityMatrix.java]: It is a small change anyways. Updated 👍
