### PR TITLE
Enqueue transitions again

### LINKED ISSUE #7873: Multiple role transitioning seem to have concurrency problems
**Describe the bug**

It looks like that multiple role changes after another seem to cause several problems, it feels like we are not awaiting completely until we start the new one, or there are still things running (like taking snapshots?). Be aware this is currently just an assumption, because I have seen several errors today, which seem to indicate that.

Symptoms/errors which seem to show that:

 * https://github.com/camunda-cloud/zeebe/issues/7872
 * https://github.com/camunda-cloud/zeebe/issues/7871
 
I'm happy to discuss this further and close this if someone thinks this is not the case. It might be that we already fixed some of the transition issues, we had with our recent changes. Maybe @deepthidevaki or @pihme knows more here.

**To Reproduce**

Might be related to the recent benchmark we have run https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518

**Expected behavior**

No issues in w.r.t to multiple role changes after another.

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-alpha2
 - Configuration:

### LINKED ISSUE #7880: Inconsistent log detected
**Describe the bug**

I asked @Sijoma to run the same benchmark we did for 1.2.0-alpha, see comment https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518 to run with SNAPSHOT and it seems that some of the errors are not occurring again BUT we still have endless leader role change loop, which seem to cause an inconsistent log!

This is quite problematic, since we can't recover on this.

Error group:

 * https://console.cloud.google.com/errors/COqdpdqD9fXk2QE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**To Reproduce**

see comment https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518 

**Expected behavior**

No inconsistent log!

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: java.lang.IllegalStateException: Expected that position '7110' of current event is higher then position '7115' of last event, but was not. Inconsistent log detected!
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:167) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Expected that position '7110' of current event is higher then position '7115' of last event, but was not. Inconsistent log detected!
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.onRecordReplayed(ReplayStateMachine.java:260) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.replayEvent(ReplayStateMachine.java:229) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:207) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:205) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:163) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:47) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	... 5 more
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-SNAPSHOT 
 - Configuration:

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

First commit adds failing tests in regards to our issue. As discussed I changed the transition logic again to enqueuing on the transition futures, which means we will executed all transitions in order. 

I don't know who want to review it @npepinpe @pihme @deepthidevaki let me know what you think

## Related issues

closes #7873 
closes https://github.com/camunda-cloud/zeebe/issues/7880

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java [hunk 1]
```diff
@@ -71,67 +73,48 @@ public void updateTransitionContext(final PartitionTransitionContext transitionC
...
+            ? concurrencyControl.createCompletedFuture()
+            : currentTransitionFuture;
+
+    // For safety reasons we have to immediately replace the current transition future with the next
+    // transition future, such that we make sure that we enqueue all transitions after another.
+    //
+    // This means we will always add the next transition to the tail, this can become a chain of
+    // futures if we have many transitions after another. Ideally we would execute after the current
+    // transition only the last enqueue one. This should be implemented as soon we have time for it.
+    currentTransitionFuture = nextTransitionFuture;
```
Comment (pihme) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:91]: This is not thread safe

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java [hunk 2]
```diff
@@ -71,67 +73,48 @@ public void updateTransitionContext(final PartitionTransitionContext transitionC
...
-            currentTransition.cancel(); // this will drop any subsequent transition steps
-
-            // schedule new transition as soon as the current step of the current transition
-            // has completed
-            concurrencyControl.runOnCompletion(
-                currentTransitionFuture,
-                (ok, error) -> cleanupLastTransition(nextTransitionFuture, term, role));
+    ongoingTransitionFuture.onComplete(
+        (nothing, error) -> {
+          context.setCurrentTerm(term);
```
Comment (pihme) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:95]: This is set too early. Context.currenntTerm/Role is used during `lastTransition.cleanUp()` to decide what needs to be done, and must at this point reflect the values of the last successful transition.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 1 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:91]: Doesn't need to be; it is called in the same actor

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 2 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:95]: for what we use that?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java [hunk 3]
```diff
@@ -71,67 +73,48 @@ public void updateTransitionContext(final PartitionTransitionContext transitionC
...
+          context.setCurrentRole(role);
 
+          if (lastTransition == null) {
+            nextTransition.start(nextTransitionFuture);
           } else {
-            cleanupLastTransition(nextTransitionFuture, term, role);
+            final var cleanupFuture = lastTransition.cleanup(term, role);
+            cleanupFuture.onComplete(
+                (ok, e) -> {
+                  if (error != null) {
```
Comment (npepinpe) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:104]: :x: I think in the cleanup context the error is actually `e`

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 1 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:91]: It is enqueue here https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java#L105

I removed the additional #run call on purpose, since this was unnecessary scheduling. In my opinion we need the guarantee that we always run in the same actor/thread in these partitions transitions. We expect that also on other places.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java [hunk 4]
```diff
@@ -71,67 +73,48 @@ public void updateTransitionContext(final PartitionTransitionContext transitionC
...
-                    role, term));
-            currentTransition.cancel(); // this will drop any subsequent transition steps
-
-            // schedule new transition as soon as the current step of the current transition
-            // has completed
-            concurrencyControl.runOnCompletion(
-                currentTransitionFuture,
-                (ok, error) -> cleanupLastTransition(nextTransitionFuture, term, role));
+    ongoingTransitionFuture.onComplete(
+        (nothing, error) -> {
```
Comment (npepinpe) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:94]: :question: Dumb question, but do we not care if there's an error or not? I know we check it below, but I assumed that was a typo and you meant to check `e` in the other callback. If not, then - do we not care about `e` in that other callback? :smile:

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 2 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:95]: This is one difference from the old transition. `currentTerm` and `currentRole` is set only after the transition is successful. So during the transition context.currentTerm and context.currentRole refers the role which we are  transitioning from. So in PartitionTransiitonStep#transitionTo(context, targetTerm, targetRole), we can take decisions based on if we are transition from leader to follower or follower to leader.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java [hunk 5]
```diff
@@ -71,67 +73,48 @@ public void updateTransitionContext(final PartitionTransitionContext transitionC
...
           } else {
-            cleanupLastTransition(nextTransitionFuture, term, role);
+            final var cleanupFuture = lastTransition.cleanup(term, role);
+            cleanupFuture.onComplete(
+                (ok, e) -> {
+                  if (error != null) {
+                    LOG.error(
+                        String.format("Error during transition clean up: %s", error.getMessage()),
+                        error);
+                    LOG.info(
```
Comment (npepinpe) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:108]: :question: Another dumb question :upside_down_face:, since I know you just copied this, but maybe someone can tell me - why do we have an ERROR log statement and then an INFO one?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 2 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:95]: Thanks, wasn't aware. I have just checked the old impl, where it was like that.

Comment (pihme) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:95]: For example in: https://github.com/camunda-cloud/zeebe/blob/ab06e27d64fcc21d1d718cca7f1899fada5dbe87/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java#L93

It is used to figure out what needs to be done during a transition. Other steps are similar

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 1 above)
Comment (pihme) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:91]: That is just an implementation detail and can change any time. I am not comfortable implementing classes that make assumptions in how they are being used. If you insist, then at lest add a comment and a runtime check that we are indeed in an Actor thread.

**Review by npepinpe — COMMENTED** [review]
:upside_down_face: Just one small nit pick. Setting the `ongoingTransitionFuture` to a completed future so we always handle it the same is clever, but seems unnecessary, and not much more readable. What about something like:

```java
  public ActorFuture<Void> transitionTo(final long term, final Role role) {
    LOG.info("Transition to {} on term {} requested.", role, term);

    // notify steps immediately that a transition is coming; steps are encouraged to cancel any
    // ongoing activity at this point in time
    steps.forEach(step -> step.onNewRaftRole(context, role));

    final ActorFuture<Void> nextTransitionFuture = concurrencyControl.createFuture();
    final var nextTransition =
        new PartitionTransitionProcess(steps, concurrencyControl, context, term, role);
    nextTransitionFuture.onComplete((v, e) -> lastTransition = nextTransition);

    if (currentTransitionFuture == null) {
      prepareNextTransition(term, role, nextTransitionFuture, nextTransition);
    } else {
      currentTransitionFuture.onComplete(
          (nothing, error) ->
              prepareNextTransition(term, role, nextTransitionFuture, nextTransition));
    }

    // For safety reasons we have to immediately replace the current transition future with the next
    // transition future, such that we make sure that we enqueue all transitions after another.
    //
    // This means we will always add the next transition to the tail, this can become a chain of
    // futures if we have many transitions after another. Ideally we would execute after the current
    // transition only the last enqueue one. This should be implemented as soon we have time for it.
    currentTransitionFuture = nextTransitionFuture;
    return nextTransitionFuture;
  }

  private void prepareNextTransition(
      final long term,
      final Role role,
      final ActorFuture<Void> nextTransitionFuture,
      final PartitionTransitionProcess nextTransition) {
    context.setCurrentTerm(term);
    context.setCurrentRole(role);

    if (lastTransition == null) {
      nextTransition.start(nextTransitionFuture);
    } else {
      final var cleanupFuture = lastTransition.cleanup(term, role);
      cleanupFuture.onComplete(
          (ok, e) -> onTransitionCleanup(term, role, nextTransitionFuture, nextTransition, e));
    }
  }

  private void onTransitionCleanup(
      final long term,
      final Role role,
      final ActorFuture<Void> nextTransitionFuture,
      final PartitionTransitionProcess nextTransition,
      final Throwable e) {
    if (e != null) {
      LOG.error("Error during transition clean up", e);
      LOG.info("Aborting transition to {} on term {} due to error.", role, term);
      nextTransitionFuture.completeExceptionally(e);
    } else {
      nextTransition.start(nextTransitionFuture);
    }
  }
```

It reads more naturally to me since the you first read over the high level logic quickly (i.e. if there is no ongoing transition, move to the next, if there is one then wait for it to complete and move on), and aren't faking "there is a previous but already completed transition". But it's a very minor nitpick since, tbh, it's quickly obvious even with the completed future.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 1 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:91]: In general I agree with you that the we should not expect how it is used, but this is currently anyway the case. Otherwise you have to call actor.run on all places right? At some point you have to make guarantees and expectation I think. In the processor for example we know and expect everything is run in one actor. Or in the ExporterDirector etc. 

The runtime check might be problematic for the test where we are running with the other concurrency Control.

I can add the run again, but would like to hear @deepthidevaki or @npepinpe opinion

Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:91]: I think this goes a bit in what we discussed this morning. I would like a clear separation between async (i.e. actor behaviors) and sync (e.g. the partition transition process) classes, so that it's very clear when one is called and one isn't.

It makes sense for performance reason and semantic to not schedule every single method, but it should be immediately obvious when something is meant to be used outside of its actor context or not. I haven't had time yet to dig into this and produce a template, but if someone has an idea or wants time for that I'm happy to discuss it.

Anyway, going back to the problem at hand - I haven't had a deep look into the new transition behavior, so it's hard for me to gauge the risk of this particular method being called from a different thread context. If we expect the `NewPartitionTransitionImpl` to deal with asynchronicity, then it makes sense to have something, whether at compile time or runtime, to check ensure we call the method from the correct context. If we don't, but the fear is that someone might do so in the future, then I would hope documentation (whether javadoc, proper naming, or a combination) would be enough to dissuade people, and highlight the issue possibly to future reviewers.

I guess this isn't as helpful as you'd hoped :smile: Let me know if I need to take a deeper look to make a final decision, otherwise I trust you to figure something out :slightly_smiling_face:

File: broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java [hunk 6]
```diff
@@ -81,75 +80,90 @@ void shouldCallTransitionStepsInOrder() {
...
+    inOrder.verify(mockStep1).transitionTo(mockContext, 2, Role.LEADER);
+
+    // when reaching wait state (future) nothing more should happen
+    inOrder.verifyNoMoreInteractions();
   }
 
   @Test
-  void shouldAbortOngoingTransitionWhenNewTransitionIsRequested() {
+  // regression test for https://github.com/camunda-cloud/zeebe/issues/7873
+  void shouldExecuteTransitionsInOrder() {
```
Comment (deepthidevaki) [inline broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java:126]: Would be nice to have one more test  - shouldNotExecuteFollowingTransitionsIfOneFails

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 4 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:94]: When error, the following transitions should not be executed.

File: broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java [hunk 7]
```diff
@@ -81,75 +80,90 @@ void shouldCallTransitionStepsInOrder() {
...
-    sut.setConcurrencyControl(TEST_CONCURRENCY_CONTROL);
+    final var transition = new NewPartitionTransitionImpl(of(mockStep1), mockContext);
+    transition.setConcurrencyControl(TEST_CONCURRENCY_CONTROL);
+
+    final var firstTransitionFuture = transition.transitionTo(1, Role.FOLLOWER);
 
     // when
-    final var actualResult = sut.transitionTo(DEFAULT_TERM, DEFAULT_ROLE);
+    transition.transitionTo(2, Role.LEADER);
+    transition.transitionTo(2, Role.FOLLOWER);
```
Comment (npepinpe) [inline broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java:103]: :question: Other dumb question :smile: we test later that we execute transition 1, which is good, then that we execute transition 2 with role LEADER. Why are we not executing transition 2 with role FOLLOWER again?

Comment (npepinpe) [reply broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java:103]: Also, wouldn't we want to assert that the future returned by the other transitions is still completed regardless? We wouldn't want anything waiting on these forever, no?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 1 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:91]: It might be safe to add run, then it is not required to execute the transition on ZeebePartition actor. Right now it does not make any difference. But since this class is self contained it make sense to not make the assumption that it will be run on the actor which calls this method.

**Review by npepinpe — COMMENTED** [review]
AFAIK, the field `currentTransition` in `NewPartitionTransitionImpl` is now unused, but I couldn't add a comment for it since that line wasn't modified.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 4 above)
Comment (pihme) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:94]: Why not?

Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:94]: Ah.. sorry. I was not thinking clearly. 
> When error, the following transitions should not be executed.

I withdraw this comment :slightly_smiling_face:

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 5 above)
Comment (pihme) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:108]: The error reports the error. The info informs about what is going to happen next.

**Comment by Zelldon** [comment]
Hey folks,

this kept me away from sleep, so I thought a bit more about it. I was able to rewrite it in a way that we enqueue the futures but still are able to cancel the enqueued transitions. This means we still have the guarantee of execution after another, but much faster since they will be canceled, which means they are almost immediately completed. 

I brought the previous tests back and adjusted the new ones, to respect the cancel behavior. 

Example log output:


```
22:13:32.655 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 1 requested.
22:13:32.655 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 1 starting
22:13:32.656 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 1 - executing Step 1
22:13:32.656 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 2 requested.
22:13:32.657 [] [main] INFO  io.camunda.zeebe.broker.system - Received cancel signal for transition to FOLLOWER on term 1
22:13:32.657 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 2 requested.
22:13:32.658 [] [main] INFO  io.camunda.zeebe.broker.system - Received cancel signal for transition to LEADER on term 2
22:13:32.658 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 1 completed
22:13:32.658 [] [main] INFO  io.camunda.zeebe.broker.system - Cleanup of transition to FOLLOWER on term 1 starting (in preparation for new transition to LEADER)
22:13:32.660 [] [main] INFO  io.camunda.zeebe.broker.system - Cleanup of transition to FOLLOWER on term 1 - executing Step 1
22:13:32.662 [] [main] INFO  io.camunda.zeebe.broker.system - Cleanup of transition to FOLLOWER on term 1 completed
22:13:32.663 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 2 starting
22:13:32.664 [] [main] INFO  io.camunda.zeebe.broker.system - Cancelling transition to LEADER on term 2
22:13:32.664 [] [main] INFO  io.camunda.zeebe.broker.system - Cleanup of transition to LEADER on term 2 starting (in preparation for new transition to FOLLOWER)
22:13:32.664 [] [main] INFO  io.camunda.zeebe.broker.system - No steps to clean up
22:13:32.664 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 2 starting
22:13:32.665 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 2 - executing Step 1
22:13:32.665 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 2 completed
```

We can see based on the log that the canceling happens always on the previous enqueued transition and that the leader transition hasn't been executed.

I hope you like this more, happy to get your feedback on this.

 Other than that I also tried to apply your other review hints, e.g. using #run again or set the term, role later etc.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java [hunk 8]
```diff
@@ -29,25 +28,17 @@
   private PartitionTransitionContext context;
   private ConcurrencyControl concurrencyControl;
   private PartitionTransitionProcess lastTransition;
-  // these two should be set/cleared in tandem
+
+  // transient state - to keep track of the current transitions
   private PartitionTransitionProcess currentTransition;
```
Comment (pihme) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:33]: :thought_balloon: Not sure current transition is the right name anymore, because it could also refer to a transition that will happen in the future. At the same time, I don't have a better name off the top of my head

File: broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java [hunk 9]
```diff
@@ -152,6 +152,94 @@ void shouldAbortOngoingTransitionWhenNewTransitionIsRequested() {
...
+
+    firstStepFirstTransitionFuture.complete(null);
+    await().until(firstTransitionFuture::isDone);
+
+    // then
+    final var inOrder = inOrder(mockStep1);
+
+    // first transition sequence
+    inOrder.verify(mockStep1).onNewRaftRole(mockContext, Role.FOLLOWER);
+    inOrder.verify(mockStep1).transitionTo(mockContext, 1, Role.FOLLOWER);
```
Comment (pihme) [inline broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java:186]: Please also verify calls to `prepareTransition` which is where the old close logic gets executed. This is part of the cleanup.

File: broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java [hunk 10]
```diff
@@ -152,6 +152,94 @@ void shouldAbortOngoingTransitionWhenNewTransitionIsRequested() {
...
+  }
+
+  @Test
+  // regression test for https://github.com/camunda-cloud/zeebe/issues/7873
+  void shouldExecuteTransitionsInOrder() {
+    // given
+    final var firstStepFirstTransitionFuture = TEST_CONCURRENCY_CONTROL.<Void>createFuture();
+    final var firstStepSecondTransitionFuture = TEST_CONCURRENCY_CONTROL.<Void>createFuture();
+    final var firstStepThirdTransitionFuture = TEST_CONCURRENCY_CONTROL.<Void>createFuture();
+    when(mockStep1.transitionTo(any(), anyLong(), any()))
```
Comment (pihme) [inline broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java:206]: :thought_balloon: Personally, I would prefer to spell out the parameters:
`when(mockStep1.transitionTo(1, FOLLOWER)).thenReturn(firstStepFirstTransitionFuture);`

However, if this is not your cup of tea, these lines could also be written in one line `when(mockStep1.transitionTo(any(), anyLong(), any())).thenReturn(firstStepFirstTransitionFuture, firstStepSecondTransitionFuture,..)`

File: broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java [hunk 11]
```diff
@@ -152,6 +152,94 @@ void shouldAbortOngoingTransitionWhenNewTransitionIsRequested() {
...
+
+    final var transition = new NewPartitionTransitionImpl(of(mockStep1), mockContext);
+    transition.setConcurrencyControl(TEST_CONCURRENCY_CONTROL);
+
+    transition.transitionTo(1, Role.FOLLOWER);
+    transition.transitionTo(2, Role.LEADER);
+    final var lastTransitionFuture = transition.transitionTo(2, Role.FOLLOWER);
+
+    // when
+    firstStepFirstTransitionFuture.complete(null);
```
Comment (pihme) [inline broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java:221]: :+1: I like it. This is much simpler and more flexible than the `WaitingTransitionStep`

**Review by pihme — APPROVED** [review]
Looks good to me. Hope you can sleep again :-)

Thanks for stepping in!

I think this code is correct. But I am happy to wait for Deepthi's verdict on the matter.

Some comments, but all of them are optional.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java [hunk 12]
```diff
@@ -63,75 +54,99 @@ public void updateTransitionContext(final PartitionTransitionContext transitionC
...
-            concurrencyControl.runOnCompletion(
-                currentTransitionFuture,
-                (ok, error) -> cleanupLastTransition(nextTransitionFuture, term, role));
-
-          } else {
-            cleanupLastTransition(nextTransitionFuture, term, role);
+    final var nextTransition =
+        new PartitionTransitionProcess(steps, concurrencyControl, context, term, role);
+    nextTransitionFuture.onComplete(
+        (v, error) -> {
```
Comment (deepthidevaki) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:78]: I would also move this inside `concurrencyControl.run()`, as this should be executed on the transitions's actor not the caller's actor.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks. Looks good to me :rocket: . Only a small comment.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 12 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:78]: Thanks you're right

**Review by npepinpe — APPROVED** [review]
:+1: LGTM, don't have more to add than others have said. I also find it easier to read now so that's a bonus :slightly_smiling_face:

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java (hunk 8 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java:33]: currentTailTransition ? :thinking: :sweat_smile:

File: broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java (hunk 9 above)
Comment (Zelldon) [reply broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java:186]: Question on this one: How problematic is it if we close the step here as term: 2 and Leader, but never install the step again because it was canceled and then install it as follower? It seems we make decision based on this call and the role etc?

For example in this test the verification which succeeds would be `
    inOrder.verify(mockStep1).prepareTransition(mockContext, 2L, RaftServer.Role.LEADER);`

Comment (Zelldon) [reply broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java:186]: Is this a blocker @pihme and @deepthidevaki ? But i think this was already previous the case since you could cancel an ongoing transition and it some steps will not be installed in the role, where it has been notified before.

Comment (deepthidevaki) [reply broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImplTest.java:186]: > Question on this one: How problematic is it if we close the step here as term: 2 and Leader, but never install the step again because it was canceled and then install it as follower? It seems we make decision based on this call and the role etc?

This should be safe to do. See the logs that you posted above. Even if we skip transition, we still do the cleanup's if there is anything to be done. We also set the last transition to the skipped transition. So when the last transition happens, it still correctly identifies as it is transitioning from the skipped role and makes the decisions based on that. If it decides it doesn't have to re-install a step, but that step doesn't exists it will install it.

**Comment by Zelldon** [comment]
@deepthidevaki you have to approve :cry:

**Review by deepthidevaki — APPROVED** [review]
:rocket:
