### PR TITLE
fix: return 503 on job activation resource exhaustion

### LINKED ISSUE #25806: RuntimeException: Expected to activate jobs of type '..', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'
**Describe the bug**

[This error](https://console.cloud.google.com/errors/detail/CIWyxZzWobCCPw;service=zeebe;time=P1D;locations=global?inv=1&invt=AbjvWw&project=camunda-cloud-240911) was reported multiple times on SaaS: `Expected to handle REST API request, but an unexpected error occurred`

**To Reproduce**

**Expected behavior**

* On backpressure (RESOURCE_EXHAUSTED) the REST API should return a 503 status code instead of 500 or 429
  * the gateway needs to handle this case gracefully and log it as an error
* REST API Docs need to be updated to make transparent that a 503 with the cause RESOURCE_EXHAUSTED can occur and what it means (backoff and eventually retry)

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Expected to activate jobs of type '[redacted]', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.

at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$handleNoReceivedJobsFromAllPartitions$9 ( io/camunda.zeebe.gateway.impl.job/LongPollingActivateJobsHandler.java:225 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:83 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:42 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:122 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 )
Recent samples Learn more 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.6.5
- [Logs](https://cloudlogging.app.goo.gl/3gzgtvPDZ7yLBc8w6)

SUPPORT CASE: [SUPPORT-24274](https://jira.camunda.com/browse/SUPPORT-24274)

### PR DESCRIPTION
**Pull request by megglos**
## Description

Previously resource exhausted on job activation resulted in 500s due to a RuntimeException
being thrown by the dedicated exception mapping layer between broker client and rest layer as setup in the `dist` module through dedicated spring config beans.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #25806

### CODE REVIEW

File: zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java [hunk 1]
```diff
@@ -382,7 +382,7 @@ public static class Builder<T> {
     // Minimum number of responses with jobCount 0 to infer that no jobs are available
     private int minEmptyResponses = DEFAULT_LONG_POLLING_EMPTY_RESPONSE_THRESHOLD;
     private Function<JobActivationResponse, JobActivationResult<T>> activationResultMapper;
-    private Function<String, Exception> noJobsReceivedExceptionProvider;
+    private Function<String, Exception> resourceExhaustedExceptionProvider;
```
Comment (megglos) [inline zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java:385]: I renamed this field and the corresponding builder property as I found the name to be misleading, it's not used for a all no jobs received cases but only if resource exhaustion was signaled in case no jobs were received:

Image

File: zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java [hunk 2]
```diff
@@ -61,14 +61,14 @@ private LongPollingActivateJobsHandler(
       final long probeTimeoutMillis,
       final int failedAttemptThreshold,
       final Function<JobActivationResponse, JobActivationResult<T>> activationResultMapper,
-      final Function<String, Exception> noJobsReceivedExceptionProvider,
+      final Function<String, Exception> resourceExhaustedExceptionProvider,
       final Function<String, Throwable> requestCanceledExceptionProvider,
```
Comment (megglos) [inline zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java:65]: 💭 I would challenge the need of having these two fields at all, ideally the Handler throws some kind of ServiceException or similar consistently and these get handled in the corresponding ErrorMappers (GrpcErrorMapper & RestErrorMapper). I would not address this here as this is intended to get backported though but rather with a follow-up on main.

Tagging @tmetzke as you worked on this before, would you agree? Happy to align.

Comment (megglos) [reply zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java:65]: This would also eliminate the risk we have right now, that the Testsin `gateway-rest` module succeed while in the dedicated `JobHandlerConfiguration` we have in the `dist` module a different exception handler could be setup.

**Comment by megglos** [comment]
Note: I would expect the backport PRs to fail as the test asserts 503 while in 8.6/8.7 the ServiceException with status RESOURCE_EXHAUSTED results in a 429, will take care of adapting the test on the backports.

File: dist/src/main/java/io/camunda/application/commons/job/JobHandlerConfiguration.java [hunk 3]
```diff
@@ -89,8 +90,9 @@ private LongPollingActivateJobsHandler<JobActivationResult> buildLongPollingHand
         .setProbeTimeoutMillis(config.longPolling().getProbeTimeout())
         .setMinEmptyResponses(config.longPolling().getMinEmptyResponses())
         .setActivationResultMapper(ResponseMapper::toActivateJobsResponse)
-        .setNoJobsReceivedExceptionProvider(RuntimeException::new)
-        .setRequestCanceledExceptionProvider(RuntimeException::new)
+        .setResourceExhaustedExceptionProvider(
```
Comment (megglos) [inline dist/src/main/java/io/camunda/application/commons/job/JobHandlerConfiguration.java:93]: 💭 We have a risk that any change here would change behavior, while tests in the rest module are still 🟢 (Actually that was the case for the LongPollingActivateJobsRestTest, which asserted 429s while actually we get 500 due to a RuntimeException being thrown here previously).

I would accept this risk for stable branches, not expecting significant changes to this setup but follow-up on eliminating that risk see https://github.com/camunda/camunda/pull/39985/files#r2466182984

File: zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java (hunk 1 above)
Comment (tmetzke) [reply zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java:385]: Thanks, the rename makes a lot of sense 👍

File: zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java (hunk 2 above)
Comment (tmetzke) [reply zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java:65]: Yeah, I agree. This made sense to me at the time. But with the improved layers and everything we have now, it doesn't seem to be a good choice anymore overall 👍 Maybe it never was 😅

**Review by tmetzke — APPROVED** [review]
👍 Looks good from my side, thanks for streamlining this 🚀
