### PR TITLE
Intermediate signal throw should not send response

### LINKED ISSUE #15649: Intermediate signal throw event should not send a response out
**Describe the bug**

It seems the signal broadcast command is always sending responses out. Possibly other commands do the same. This has little impact right now on Zeebe itself because the transport essentially "swallows" the error, e.g. if you send a response with a request ID and stream ID that it doesn't recognize, it simply does nothing. This is still additional, unnecessary work though, copying the response around, serializing it, etc.

This also causes an error in `zeebe-process-test`, where the transport behaves differently and _always_ expects a request for every response sent out, causing [the following error](https://github.com/camunda/zeebe-process-test/issues/1011).

In my opinion, this should be fixed in both places, although the severity is quite low in Zeebe. But the command response writer should simply not add pending responses if the associated command has no request metadata. For example, see the old `CommandProcessImpl`, which does this check.

**To Reproduce**

Add the following to the engine test `SignalIntermediateThrowEventTest.java`:

```java
  @Test
  public void shouldNotSendResponseWhenPartOfBatch() {
    // given
    final var processId = Strings.newRandomValidBpmnId();
    final var process =
        Bpmn.createExecutableProcess(processId)
            .startEvent()
            .intermediateCatchEvent(
                "start", b -> b.message(m -> m.name("start").zeebeCorrelationKey("=businessKey")))
            .intermediateThrowEvent("signal", b -> b.signal("signal"))
            .endEvent()
            .done();
    ENGINE.deployment().withXmlResource(process).deploy();
    final var piKey =
        ENGINE
            .processInstance()
            .ofBpmnProcessId(processId)
            .withVariables(Map.of("businessKey", "42"))
            .create();
    assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
                .withProcessInstanceKey(piKey)
                .withElementId("start")
                .limit(1)
                .exists())
        .isTrue();

    // when
    ENGINE.message().withName("start").withCorrelationKey("42").publish();
    assertThat(
            RecordingExporter.signalRecords(SignalIntent.BROADCASTED)
                .withSignalName("signal")
                .limit(1)
                .exists())
        .isTrue();

    // then
    Mockito.verify(ENGINE.getCommandResponseWriter(), Mockito.never())
        .intent(SignalIntent.BROADCASTED)
        .tryWriteResponse(-1, -1);
  }
```

This basically creates a process consisting of `start -> message catch -> signal throw -> end`. The message catch will cause the signal throw to send out a response.

**Expected behavior**

Responses are not sent out if the command has no request metadata.

**Environment:**
- Zeebe Version: 8.3+

**Context**
Support issue: https://jira.camunda.com/browse/SUPPORT-19727

### PR DESCRIPTION
**Pull request by ana-vinogradova-camunda**
## Description
Fix for this [bug](https://github.com/camunda/zeebe/issues/15649)

- Added a check to verify if the command has request metadata
- Added a unit test to verify that response is not send if the metadata is not present. Adjusted the test case from the bug above.
- Added an Integration Test to verify the response is sent when the metadata is present

## Related issues

closes #15649

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by ana-vinogradova-camunda** [comment]
@korthout could you please have a quick look when you get time? I wonder if I can make test better. Thank you!

File: engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalIntermediateThrowEventTest.java [hunk 1]
```diff
@@ -169,4 +171,47 @@ public void shouldApplyOutputMappings() {
...
+
+    assertThat(
+            RecordingExporter.signalRecords(SignalIntent.BROADCASTED)
+                .withSignalName(SIGNAL_NAME_1)
+                .limit(1)
+                .exists())
+        .isTrue();
+
+    // then
+    verify(ENGINE.getCommandResponseWriter(), never()).intent(SignalIntent.BROADCASTED);
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalIntermediateThrowEventTest.java:219]: ❌ To ensure that this call to verify is safe, we must isolate it from the other test cases. We must do that because the engine is reused between the test cases of this class. You can achieve this by adding `Mockito.clearInvocations(ENGINE.getCommandResponseWriter());` at the start of this test method.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalIntermediateThrowEventTest.java [hunk 2]
```diff
@@ -169,4 +171,47 @@ public void shouldApplyOutputMappings() {
...
+        .isTrue();
+
+    // when
+    ENGINE.message().withName("start").withCorrelationKey("42").publish();
+
+    assertThat(
+            RecordingExporter.signalRecords(SignalIntent.BROADCASTED)
+                .withSignalName(SIGNAL_NAME_1)
+                .limit(1)
+                .exists())
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalIntermediateThrowEventTest.java:215]: 🔧 There is no need to use `.limit(1)` when calling `.exists()` because `.exists()` is a short-circuiting terminal operation. See Javadoc of `java.util.stream.Stream#findFirst()` for details, as it is used to implement `.exists()`. Feel free to add JavaDoc about this to `.exists()`.

**Review by korthout — CHANGES_REQUESTED** [review]
This looks great! Well done @ana-vinogradova-camunda 👏 

👍 I really like the integration test for verifying the response to signal broadcasting.

I noticed a few things where the test case could be improved. Please have a look at my comments.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalIntermediateThrowEventTest.java (hunk 1 above)
Comment (ana-vinogradova-camunda) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalIntermediateThrowEventTest.java:219]: A very good point, thank you!

File: engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalIntermediateThrowEventTest.java [hunk 3]
```diff
@@ -174,44 +175,26 @@ public void shouldApplyOutputMappings() {
...
-    ENGINE.message().withName(messageName).withCorrelationKey(businessKey).publish();
+    ENGINE.processInstance().ofBpmnProcessId(PROCESS).create();
 
     assertThat(
             RecordingExporter.signalRecords(SignalIntent.BROADCASTED)
                 .withSignalName(SIGNAL_NAME_1)
-                .limit(1)
+                // No need to use .limit(1) here as .exists() uses .findFirst() in order to
+                // determine if the element is present.
                 .exists())
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalIntermediateThrowEventTest.java:198]: 🔧 Feel free to remove this comment and introduce Javadoc on `.exists()`'s declaration, clarifying that it is a short-circuiting terminal operation. This would help all users of the exists method when they read it's javadoc

**Review by korthout — APPROVED** [review]
Thanks for applying the requested changes @ana-vinogradova-camunda 🚀 

This looks great, I have one last suggestion. Feel free to apply or ignore it and merge.

LGTM 👍

**Comment by ana-vinogradova-camunda** [comment]
bors merge

**Comment by ana-vinogradova-camunda** [comment]
bors retry

**Comment by korthout** [comment]
Thanks @ana-vinogradova-camunda I completely forgot at the time 🙇
