### PR TITLE
Async Raft flush

### LINKED ISSUE #11488: Configurable raft flush interval
Currently, we flush on every commit or disable flush completely. Instead we could still think about this idea of providing varying level of guarantees, e.g.

- at least flush on every snapshot
- the above + flush when creating a new segment (aka flush a segment only after it's filled up)
- the above + flush open segments every X seconds
- the above + flush on every append before acknowledging (i.e. current approach)
- the above + also maintain the setLastWrittenIndex for better crash resilience

Similarly, we can look into restore consistency levels:

- Strict, aka distinguish between partial writes and corruption, and do not start on corruption detected
- Lenient, aka do not distinguish between partial writes and corruption, and discard data on corruption of the last segment
- None, aka discard data on corruption detection (not sure if that's even feasible considering the snapshots)

_Originally posted by @megglos in https://github.com/camunda/zeebe/issues/11423#issuecomment-1385002390_

### LINKED ISSUE #11519: Promote disable raft flush flag to non-experimental
**Description**

Now that #11423 is done, we can officially support this flag. 

-[ ] Properly document dangers of disabling raft flush.
-[ ] Move the flag out of non-experimental. TBD whether we can make breaking changes for this config.

Related https://github.com/camunda/product-hub/issues/642

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

First draft for asynchronous Raft flush. A second iteration could potentially simplify things further push down the flush strategy pattern to the journal, and introduce the concept of a background executor for the journal, useful for compaction, for segment creation, etc.

As a first step here, we just make sure the flush path is thread-safe, and we still provide a way to flush synchronously on the Raft thread if required.

The thread-safety relies on two things: the fact the segments map is thread-safe already, and a new volatile last flushed index that the `SegmentedJournalWriter` keeps track of.

By keeping track of what was the last successfully flushed index, we don't need to flush the moving to the next segment on write. Instead, on flush, we'll just pick up all the segments whose last index is greater than or equal to the last known flushed index, and flush them. At the end, we store the last successfully flushed index. This means we sometimes will flush a little more than what we need to, but that's fine.

This needs to be polished a little more, but I wanted to get some early feedback.

## Related issues

closes #11519 
closes #11488 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java [hunk 1]
```diff
@@ -191,7 +191,14 @@ public RaftContext(
     lastVotedFor = meta.loadVote();
 
     // Construct the core log, reader, writer, and compactor.
-    raftLog = storage.openLog(meta, threadContext);
+    // very much unclear if we want to redirect uncaught exceptions here and step down all the time
+    raftLog =
```
Comment (npepinpe) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:195]: Not a fan of this. Needs to be cleaned up a little, how the thread factory is provided.

File: atomix/cluster/src/main/java/io/atomix/raft/storage/log/DelayedFlusher.java [hunk 2]
```diff
@@ -39,37 +38,33 @@ public DelayedFlusher(final Scheduler scheduler, final Duration delayTime) {
 
   @Override
   public void flush(final Journal journal) {
-    scheduleFlush(journal);
+    synchronized (scheduledMonitor) {
```
Comment (npepinpe) [inline atomix/cluster/src/main/java/io/atomix/raft/storage/log/DelayedFlusher.java:41]: I went this way, as AFAIK the performance difference between synchronized and reentrant locks is negligible, and in all cases I want to lock/unlock directly, so the structured approach is safer.

File: atomix/cluster/src/main/java/io/atomix/raft/storage/log/DelayedFlusher.java [hunk 3]
```diff
@@ -39,37 +38,33 @@ public DelayedFlusher(final Scheduler scheduler, final Duration delayTime) {
...
   private void asyncFlush(final Journal journal) {
-    scheduledFlush = null;
-
-    if (closed || !journal.isOpen()) {
-      return;
+    synchronized (scheduledMonitor) {
+      scheduledFlush = null;
     }
 
     journal.flush();
```
Comment (npepinpe) [inline atomix/cluster/src/main/java/io/atomix/raft/storage/log/DelayedFlusher.java:65]: We may be flushing even if we're closing, but that's probably fine.

File: atomix/cluster/src/main/java/io/atomix/raft/storage/log/DelayedFlusher.java [hunk 4]
```diff
@@ -39,37 +38,33 @@ public DelayedFlusher(final Scheduler scheduler, final Duration delayTime) {
...
+    synchronized (scheduledMonitor) {
+      if (scheduledFlush == null) {
+        scheduledFlush = scheduler.schedule(delayTime, () -> asyncFlush(journal));
+      }
+    }
   }
 
   @Override
   public void close() {
-    if (closed) {
```
Comment (npepinpe) [inline atomix/cluster/src/main/java/io/atomix/raft/storage/log/DelayedFlusher.java:47]: I think the close method is idempotent already anyway, and it's always called from the same thread. Checking if we're closed in the `asyncFlush` method was just a best effort anyway, so we can omit it.

File: atomix/utils/src/main/java/io/atomix/utils/concurrent/SingleThreadContext.java [hunk 5]
```diff
@@ -155,6 +155,13 @@ public Scheduled schedule(
   @Override
   public void close() {
     executor.shutdownNow();
+
+    try {
+      //noinspection ResultOfMethodCallIgnored
+      executor.awaitTermination(30, TimeUnit.SECONDS);
```
Comment (npepinpe) [inline atomix/utils/src/main/java/io/atomix/utils/concurrent/SingleThreadContext.java:161]: While it may introduce some delay on shut down, imo I like the idea that we wait until the thread is terminated. 

We may want to add some logging here, as 30 seconds elapsed without termination means we have a single task taking 30 seconds (:exploding_head:), which should not happen.

File: journal/src/main/java/io/camunda/zeebe/journal/file/JournalMetrics.java [hunk 6]
```diff
@@ -47,6 +47,14 @@ final class JournalMetrics {
           .labelNames(PARTITION_LABEL)
           .register();
 
+  private static final Histogram JOURNAL_FLUSH_TIME =
```
Comment (npepinpe) [inline journal/src/main/java/io/camunda/zeebe/journal/file/JournalMetrics.java:50]: Will measure the complete journal flush time, not the per-segment flush time. I expect they will typically be the same, but I figured it could be interesting in the cases where it's not.

File: journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java [hunk 7]
```diff
@@ -230,6 +235,21 @@ private void safeDelete() {
...
+  boolean flush() {
+    try (final var ignored = metrics.observeSegmentFlush()) {
+      buffer.force();
+    } catch (final UncheckedIOException e) {
+      if (isOpen()) {
+        throw e;
+      }
+
+      LOG.trace("Flushing failed on a closed or deleted segment, and will be ignored");
+      return false;
```
Comment (npepinpe) [inline journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java:247]: I debated if we should return true or not. It will be mostly if we update the meta store. I'm still not sure honestly :thinking: If we do, then we can omit the return value and assume a non-exceptional call always succeeds.

File: journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java [hunk 8]
```diff
@@ -240,7 +260,6 @@ private void markForDeletion() {
       return;
     }
 
-    writer.close();
```
Comment (npepinpe) [inline journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java:243]: The writer close wasn't really doing anything but flushing. But since we closed it only on deletion, it seemed silly to flush right before deleting :smile:

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java [hunk 9]
```diff
@@ -295,6 +304,10 @@ private void prepareNextSegment() {
     nextSegment = CompletableFuture.supplyAsync(() -> createUninitializedSegment(descriptor));
   }
 
+  Collection<Segment> getSegments(final long index) {
+    return Collections.unmodifiableSortedMap(segments.tailMap(index, true)).values();
```
Comment (npepinpe) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java:308]: I wasn't 100% sure about the `inclusive = true` here, but I think it's safer to do that.

**Comment by npepinpe** [comment]
The thread safety around `IoUtil.free(buffer)` (which un-maps the `MappedByteBuffer` via [munmap](https://linux.die.net/man/3/munmap)) and `MappedByteBuffer#force` (which flushes the buffer via [msync](https://linux.die.net/man/3/msync)) is predicated on the following information:

1. Free-ing or unmapping a mapped buffer is safe to call multiple times and will not throw errors. Once freed, a `SIGBUS` is thrown if we try to access any page (via writes or reads, for example), but `msync` does not access pages directly, just tells the kernel to flush.
2. Calling `msync` on pages which are not mapped returns an error, but does not generate a `SIGSEGV` nor a `SIGBUS`. Instead, it simply returns an error.
3. In JVM land, `MappedByteBuffer#force` then throws an `UncheckedIOException` if any error occurs (e.g. the buffer was unmapped).
4. By setting the `Segment#open` flag as volatile, and setting it to false whenever we delete/free, we can safely ignore these errors when flushing, but rethrow them in all other cases. **We have to ensure that the flag is set to false _before_ we unmap, otherwise we may not be able to properly detect this**.

This holds on [all Unix platforms](https://github.com/openjdk/jdk/blob/c29a13678744522503f899bdf5f4c13f130942f7/src/java.base/unix/native/libnio/MappedMemoryUtils.c) and [Windows](https://github.com/openjdk/jdk/blob/c29a13678744522503f899bdf5f4c13f130942f7/src/java.base/windows/native/libnio/MappedMemoryUtils.c) as well, as [FlushViewOfFile](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-flushviewoffile) behaves similarly to `msync`, and will also just return an error on failure.

**Comment by npepinpe** [comment]
I can confirm via logs that we're flushing exactly every 5 seconds, but for some reason the metrics show more samples than that. It's a step size of 15s, so I would expect 3 samples per step, but I get something like ~10 (for a single partition/pod, on the leader).

**Comment by npepinpe** [comment]
Preliminary results [here](https://grafana.dev.zeebe.io/goto/2eQfb0J4k?orgId=1). The bump in the graph is when I scaled from 75 PI/s to 150 PI/s so it would be more comparable.

image

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java [hunk 10]
```diff
@@ -80,34 +91,68 @@ public void append(final JournalRecord record) {
...
+          lastFlushedIndex,
+          getLastIndex());
+      return;
+    }
 
-  public void close() {
-    currentWriter.close();
+    try {
+      for (final var segment : dirtySegments) {
+        final long lastSegmentIndex = segment.lastIndex();
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:135]: `segment.lastIndex()` is not accessing a volatile field. Wouldn't that be a problem if flush is executed on another thread? What would happen if it gets an incorrect value?

Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:135]: I thought about that. In general it shouldn't matter as you may just end up flushing more data than expected, however if we've truncated or reset it might be a problem, since we would then save that as the last flushed index, which would be wrong, I think. So it might be we do need to ensure it's volatile unfortunately.

I also thought about passing the expected last index during scheduling, but again, this may change due to reset/truncate in between.

File: journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java (hunk 7 above)
Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java:249]: I think we can keep it. It might be unnecessary, but I feel safe to keep it incase if there is an edge case that we haven't thought about.

File: journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java (hunk 8 above)
Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java:243]: :question: We also close segments while shutting down, right? Shouldn't we flush before shutting down? But this can be handled somewhere higher up in the journal.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java (hunk 10 above)
Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:135]: Looks like flush should be synchronized with `deleteAfter` and `reset`. And after deleteAfter and reset, lastFlushedIndex should be immediately updated. :thinking:

**Review by deepthidevaki — COMMENTED** [review]
Just some comments. I haven't done a through review yet.

**Comment by npepinpe** [comment]
I think lastFlushedIndex is adding more trouble than it's worth. Maybe there's a better way to keep track of which segments must be flushed that doesn't require so much synchronization :thinking_face:

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java (hunk 10 above)
Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:135]: I think with the following we can resolve this issue:
- SegmentedJournal:Flush acquire rwLock.readLock before flushing. All delete methods already acquire write lock and it happens only rarely. So it doesn't add any contention.
- SegmentedWriter:deleteAfter and reset update lastFlushedIndex in metastore  and in-memory before delete. No need to update after if it is not flushed. 
- Next step, see if we have to remove the lock when direct flush is configured for perf reasons.

wdyt?

File: journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java (hunk 8 above)
Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/Segment.java:243]: As far as I could tell, we only closed the writer when deleting the segment, not when closing it. So we weren't flushing either on closing.

The `SegmentedJournalWriter#close` method was calling the `SegmentWriter#close` as well, but we also never closed the `SegmentedJournalWriter`. Was that an over sight?

I also agree we might want to flush before closing, but as you said we can probably do this on journal close.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java (hunk 10 above)
Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:135]: @npepinpe Let's sync on this monday. If it is becoming more complex, we can re-think if we really want to do this or not.

Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:135]: :+1: 

I didn't have much time to look into this today anyway.

I think the `lastIndex` access here is actually not super critical and there's an easy workaround (i.e. when scheduling the flush, pass the expected last index from the Raft thread as an argument). I think the truncate/reset issues are the more complicated ones.

Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:134]: I added acquiring the read lock. It seems to have little impact in general, including in the blocking case. There's little contention for the lock, since it would only content with compact/reset/truncate, which are all done synchronously as well, and it will not contend with the readers.

I would go with this for now, as it will also ease making compaction asynchronous if we want to.

Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:134]: :+1: Please ping me when it is ready for review.

Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:134]: I started a benchmark with the synchronous flush just to verify my claims, let's see

Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:134]: Benchmark with synchronous flush looks comparable to the baseline. Initially I had worse performance because of all the logging I added actually, but that wouldn't be debug in the final PR anyway. Looks fine now

Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:134]: Sync flushing with acquiring lock:

image
image
image
image


Without acquiring lock (i.e. baseline):

image
image
image
image

Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:134]: One change with the sync flush versus baseline is we don't flush on segment creation anymore. You can see it has a very small improvement there. The p99 is similar, but more of them are clustered in the lower ranges:

Sync flush:

image

Baseline:

image

Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:134]: It seems very small though, so I wouldn't immediately classify that as a win, just figured I'd mention it :smile:

Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:134]: Great :+1:

**Comment by npepinpe** [comment]
I'm struggling a little to properly test this. I think our journal implementation suffers from having classes which do too much, which tend to lead to having  making them difficult to test without either stubbing or mocking so many things.

There's also no real easy way to observe flushing externally, e.g. have all the expected entries been flushed, since we can't query the kernel page cache.

**Comment by npepinpe** [comment]
For testing, in the end, I ended up extracting the main flushing logic and the management of the `lastFlushedIndex` into its own class so it could be tested.

I'm a bit mixed about the last 2 commits, and I'm happy to drop them. I wanted to ensure we reset the last flushed index during delete operations, and we could do that to some extent directly via the journal by allowing to inject the `SegmentsFlusher` instance. I'm happy to drop them, though I do also like that building this journal stuff is centralized now...though it's one more layer of abstraction. I'm very much on the fence, so whatever you lean more towards we can do that :sweat_smile:

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java [hunk 11]
```diff
@@ -145,8 +148,19 @@ public boolean isEmpty() {
...
   public void flush() {
-    writer.flush();
-    journalMetaStore.storeLastFlushedIndex(getLastIndex());
+    if (!isOpen() || isEmpty()) {
+      LOGGER.debug("Skipped journal flush as it is either closed or empty");
+      return;
+    }
+
+    try (final var ignored = journalMetrics.observeJournalFlush()) {
+      final var stamp = rwlock.readLock();
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:157]: :wrench: Documenting why to lock would be useful for future.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java [hunk 12]
```diff
@@ -299,6 +308,15 @@ private void prepareNextSegment() {
     nextSegment = CompletableFuture.supplyAsync(() -> createUninitializedSegment(descriptor));
   }
 
+  Collection<Segment> getSegments(final long index) {
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java:307]: :wrench: May be rename to `getTailSegments` and/or add a one line doc.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsFlusher.java [hunk 13]
```diff
@@ -0,0 +1,73 @@
...
+  private static final Logger LOGGER = LoggerFactory.getLogger(SegmentsFlusher.class);
+  // no need to make this volatile if callers always acquire the write-lock beforehand
+  private long lastFlushedIndex;
+
+  SegmentsFlusher(final long lastFlushedIndex) {
+    resetLastFlushedIndex(lastFlushedIndex);
+  }
+
+  void resetLastFlushedIndex(final long lastFlushedIndex) {
+    this.lastFlushedIndex = lastFlushedIndex;
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsFlusher.java:26]: :x: Shouldn't this also update the metastore. Otherwise if there was no explicit flush after this and if the node restarts, it can detect the segment as corrupted if the previous lastFlushedIndex was greater thatn reset index.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java [hunk 14]
```diff
@@ -80,34 +84,31 @@ public void append(final JournalRecord record) {
...
-      currentSegment = journal.getLastSegment();
+    while (index < currentSegment.index() && currentSegment != segments.getFirstSegment()) {
+      segments.removeSegment(currentSegment);
+      currentSegment = segments.getLastSegment();
       currentWriter = currentSegment.writer();
     }
 
     // Truncate the current index.
     currentWriter.truncate(index);
+    flusher.resetLastFlushedIndex(index - 1);
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:103]: :wrench: I think it is better to update it before deleting entries. We didn't do it before also. But what if node crashes after deleting but before updating metastore? There is a small chance the after restart it incorrectly detects journal corruption.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsFlusher.java (hunk 13 above)
Comment (deepthidevaki) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsFlusher.java:26]:
```suggestion
    if(this.lastFlushedIndex > lastFlushedIndex) {
                // update metastore
    }
    this.lastFlushedIndex = lastFlushedIndex;
```

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalWriterTest.java [hunk 15]
```diff
@@ -0,0 +1,67 @@
...
+    writer.append(2, journalFactory.entry());
+    writer.append(3, journalFactory.entry());
+    writer.append(4, journalFactory.entry());
+    writer.flush(journalFactory.metaStore());
+
+    // when
+    writer.deleteAfter(2);
+
+    // then
+    assertThat(flusher.nextFlushIndex()).isEqualTo(2L);
```
Comment (deepthidevaki) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalWriterTest.java:51]: :x: This should also verify that metastore is updated. See above comment.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
:rocket: Great! Thanks. I have only some small comments. Let me know if it is not clear.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java (hunk 12 above)
Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java:307]: :+1: Good catch, this is not descriptive at all :sweat_smile: I think tail is too tied to the `NavigableMap` concept, but then again something like `getSegmentsWithIndexGreaterThanOrEqualTo` is a mouthful :smile:

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsFlusher.java (hunk 13 above)
Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsFlusher.java:26]: I thought about that, I think it was one of the comments I had somewhere? Maybe I forgot to add it here.

In `RaftLog`, we always flush after any `deleteAfter` operation. We don't flush after reset because there isn't anything really to flush, and AFAIK we always reset to an index greater than the previous one (since resetting on snapshot). I wasn't 100% sure about that last point though, but it would be cheap.

Why I didn't add it here is that it would be performing two unnecessary I/Os in the `deleteAfter` case, i.e. call `storeLastFlushedIndex` here, then again since we have to flush as well.

But better be safe than not, and I can had some failsafe in the `MetaStore` to not write the same value more than once.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java (hunk 14 above)
Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournalWriter.java:103]: If we do it before, then crash before truncating, we would treat any corruption as a partial write. Which is probably fine as we wanted to truncate anyway, I guess :smile:

**Comment by npepinpe** [comment]
Had to force push because of merge conflicts :(

**Review by deepthidevaki — APPROVED** [review]
Great! :rocket:
