### PR TITLE
fix: skip snapshot when nothing processed and not forced

### LINKED ISSUE #38484: Snapshot can be taken at processed position 0 only if forced exception is thrown unexpectedly
### 

### 

### 

### 

### Description

In the dev environment, the following exception is thrown:

```
java.lang.IllegalArgumentException: Snapshot can be taken at processed position 0 only if forced.
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.takeTransientSnapshotInternal(StateControllerImpl.java:170)
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.lambda$takeTransientSnapshot$0(StateControllerImpl.java:76)
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:84)
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:43)
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127)
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104)
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224)
```

This appears related to a recent change introduced in PR #38053, which added a guard disallowing non-forced snapshots when the processed position is zero. It is unclear whether periodic snapshot triggers are expected to run before any records are processed, or whether this should be handled more gracefully.

### Steps to reproduce

1. Start the broker in a fresh environment
2. Observe logs before any events are processed
3. Notice a snapshot attempt with processed position 0 resulting in the exception above

### Current behavior

The broker throws an `IllegalArgumentException` when attempting a non-forced snapshot at processed position 0, even during normal startup.

### Expected behavior

The broker should either delay snapshot attempts until processed position advances, or handle this edge case without throwing an exception.

### Workaround

_No response_

### Environment

SaaS

### Version

Component Version: `SNAPSHOT`

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

Related PR: https://github.com/camunda/camunda/pull/38053
GCP Logs: [LINK](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22worker-2%22%0Aresource.labels.namespace_name%3D%2240c3020d-96ee-4d02-b18c-0ef24961f499-zeebe%22%0Aresource.labels.project_id%3D%22camunda-saas-dev%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.location%3D%22europe-north1%22;pinnedLogId=2025-09-19T04:21:13.205187086Z%2Fk5gxufiul4e9o5zy;cursorTimestamp=2025-09-19T04:24:11.348238362Z;startTime=2025-09-19T03:51:43.205Z;endTime=2025-09-19T05:51:43.205Z?project=camunda-saas-dev)
GCP Logs Downloaded: [LINK](https://drive.google.com/file/d/1NEjiSZIG6jCw6IdnY-25OHy9jZ5OzuqU/view?usp=share_link)

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

When snapshot is scheduled too fast and nothing has been processed yet, we should skip it. Otherwise it will fail at a later stage when trying to read the index entry at position 0. The impact of this is low, as the result is just noisy error logs. Otherwise the system works fine and the next snapshot after processing at least one record will be successful. This was the previous behavior which got changed when we added forced snapshot for migration. We want to allow taking snapshot at position 0 only when the snapshot is forced.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #38484

### CODE REVIEW

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 1]
```diff
@@ -222,6 +222,12 @@ private ActorFuture<PersistedSnapshot> trySnapshot(final boolean forceSnapshot)
               } else {
                 inProgressSnapshot.lowerBoundSnapshotPosition =
                     position == StreamProcessor.UNSET_POSITION ? 0L : position;
+                if (inProgressSnapshot.lowerBoundSnapshotPosition == 0 && !forceSnapshot) {
```
Comment (entangled90) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:225]: :question: when a new partition is bootstrapped I think we set the initial index to 1, so this should not be a problem right? Moreover a snapshot for that index is already there. Correct?

Comment (deepthidevaki) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:225]: When a snapshot is forced, it takes a snapshot at the same index even if the positions has not been changed. So it should be fine. Moreover, after a partition bootstrapped there is always something processed new. So a snapshot can be taken anyway without forced.

**Review by entangled90 — APPROVED** [review]
Thanks!
