### PR TITLE
Reject modification command if flow scope can't be created

### LINKED ISSUE #9980: Reject the modification command if the flow scope of an element for activation can't be created
## Description

The modification command can contain activation instructions for different elements. An element can be inside a flow scope (e.g. an embedded subprocess). If the flow scope of the given element doesn't exist yet then it is created before the element is activated.

The creation of the flow scope could fail if it subscribes to events (#9643). For example, a message boundary event is attached to the subprocess but the variable for the message correlation key is missing. 

If at least one flow scope can't be created successfully then the command should be rejected. 

image

Related to 
- #9422 

Blocked by 
- #9643

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

The creation of a flow scope could fail if it subscribes to an event. For example, if the event requires a variable that does not exist. When this happens the command should be rejected and a response should be written to the client.

## Related issues

closes #9980 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java [hunk 1]
```diff
@@ -164,6 +165,16 @@ public void processRecord(
         eventKey, ProcessInstanceModificationIntent.MODIFIED, value, command);
   }
 
+  @Override
+  public ProcessingError tryHandleError(final TypedRecord<ProcessInstanceModificationRecord> typedCommand, final Throwable error) {
+    if (error instanceof EventSubscriptionException exception) {
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java:171]: ❓ Is this exception already thrown by this processor? It's not part of this PR

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @remcowesterhoud 

👍 Looks already good, but it requires a small change before we can merge.

❌ There's a small typo in one of the rejection types. Please adjust.

I also have a question that wasn't clear from the PR description and commits, but I can make an assumption because of the test case.

🔧 Lastly, about commit message types:
- the commit `refactor: capitalise error message` has a behavioral change, for which `fix` and `feat` are better suited
- the commit `refactor: automatic formatting` is a styling change for which you can use `style`.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java (hunk 1 above)
Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java:171]: Yes, it's already thrown because we use this same logic for start process instance anywhere:
https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/common/ElementActivationBehavior.java#L245

**Review by korthout — APPROVED** [review]
Thanks for making the changes @remcowesterhoud 

LGTM 🚀

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors retry
