### PR TITLE
fix(atomix): fix DNS/UDP resource leaks

### LINKED ISSUE #14837: UDP resource leaks
**Describe the bug**

In CW42 and CW43, we have a massive UDP resource leak which causes UDP listening connections to eventually max out, such that no new ones can be created. This causes widespread DNS failures, eventually leading to out of disk space as we cannot export data anymore.

I can confirm this is not happening in 8.3.1 or prior versions.

**To Reproduce**

In any of the pods in CW42 and CW43, run `watch -n1 -- 'wc -l /proc/net/udp'`, and you will see the amount of open UDP connections is constantly increasing, all coming from the Java process.

A quick `netstat -ulpne` gives little more information.

**Expected behavior**

The only open UDP connections are our Netty unicast service and temporary ones, meaning we should have a baseline of 2, and possibly transient ones that do not remain.

**Environment:**
- Zeebe Version: 8.4.0-SNAPSHOT CW42 and CW43

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

Fixes a UDP resource leak associated with the `DnsAddressResolverGroup` usage. The group is meant to be reused and shared, as the channels will not close any associated resolvers/groups. By creating a new group for every channel, especially with transient channels, we end up with a new group that is created and garbage collected, but the underlying socket is never closed (since as far as the channel is concerned, it doesn't "own" the group).

While we could create one group per channel and ensure it's closed along with the channel via a promise, the group is thread safe and seems perfectly reusable, so let's do that and make full use of the underlying cache.

## Related issues

closes camunda/zeebe#14837

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Currently tested manually only, since locally and in tests you won't see much of a difference due to us using only localhost.

Without digging too much into it, it also seems to have brought the latency back to pre-CW42 levels, around the very stable typical 64ms. I wonder if it's because any transient request was incurring the DNS look up cost since the cache was per-client and not for the whole messaging service.

**Comment by npepinpe** [comment]
Pictures of the graphs:

image

**Comment by Zelldon** [comment]
> Pictures of the graphs:
> 
> image

Do you have graphs from the base?

**Comment by Zelldon** [comment]
> There are still some things I don't get - for example, I did a quick test with and without the patch:
> 
> ```java
>   @Test
>   public void testUdpSocketLeak() throws InterruptedException {
>     final String subject = nextSubject();
>     final AtomicBoolean handlerInvoked = new AtomicBoolean(false);
>     final AtomicReference<byte[]> request = new AtomicReference<>();
>     final AtomicReference<Address> sender = new AtomicReference<>();
> 
>     final BiFunction<Address, byte[], byte[]> handler =
>         (ep, data) -> {
>           handlerInvoked.set(true);
>           sender.set(ep);
>           request.set(data);
>           return "hello there".getBytes();
>         };
>     netty2.registerHandler(subject, handler, MoreExecutors.directExecutor());
> 
>     while (true) {
>       netty1.sendAndReceive(address2, subject, "hello world".getBytes(), false).join();
>       Thread.sleep(1_000);
>     }
>   }
> ```
> 
> With the patch, the total number of listening UDP connections increases but tops off at 32. Without the patch, it will continue to increase for every request seemingly forever.
> 
> Since each `DnsNameResolver` has its own channel, I assume these are the ones being created, and we somehow top off at 32 for a given group.
> 
> Ah, so it seems each group creates one resolver per "executor", in this case, per thread in our Epoll executor. On my machine, this happens to be 2 * the number of cores, so 32. I'm a little confused, since I figured the resolvers were sharing the same executor 🤔
> 
> I suppose it's more that resolution happens on the same shared executor, but each client loop executor gets its own resolver as well.

Is this something I need to consider or is this just FYI?

anything we can use as a test? Like only X sockets are created after Y requests.

**Comment by npepinpe** [comment]
We did notice that there are errors, and we should investigate those - they seem to be real errors - but I think we can do this in another PR.

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyDnsMetrics.java [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+
+import io.netty.channel.ChannelFuture;
+import io.netty.handler.codec.dns.DnsQuestion;
+import io.netty.handler.codec.dns.DnsResponseCode;
+import io.netty.resolver.dns.DnsQueryLifecycleObserver;
+import io.prometheus.client.Counter;
+import java.net.InetSocketAddress;
+import java.util.List;
+
+final class NettyDnsMetrics implements DnsQueryLifecycleObserver {
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyDnsMetrics.java:18]: 👍🏼 

Was first to write lets remove the parameters, but then realized we use here the interface and register this.

**Comment by npepinpe** [comment]
Here's the test I was thinking of using right now:

```java
@Test
    void shouldNotLeakUdpSockets() throws IOException {
      // given
      final var pid = ProcessHandle.current().pid();
      final var udpPath = Path.of("/proc/" + pid + "/net/udp");
      final var udp6Path = Path.of("/proc/" + pid + "/net/udp6");
      // the configured amount of threads for Netty's epoll transport
      final var maxConnections = Runtime.getRuntime().availableProcessors() * 2;
      final var subject = nextSubject();
      netty2.registerHandler(
          subject, (address, bytes) -> new byte[0], MoreExecutors.directExecutor());

      // when
      for (int i = 0; i < maxConnections * 2; i++) {
        netty1.sendAndReceive(netty2.address(), subject, "hello world".getBytes()).join();
      }

      // then
      final var socketCount =
          Files.readAllLines(udpPath).size() + Files.readAllLines(udp6Path).size();
      // add two extra lines due to the headers
      assertThat(socketCount).isLessThan(maxConnections + 2);
    }
```

You can read the open sockets for your process via `/proc/<PID>/net/udp` and `/proc/<PID>/net/udp6`, however the test is missing a few things:

1. We should only count the sockets opened by the current user, obviously, and these include shared sockets opened by other users. One option is to filter by the `uid` for your current user, but meh.
2. The number of sockets obtained via this method seems to be fluctuating, so it might lead to a flaky test.

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 2]
```diff
@@ -375,6 +378,15 @@ public CompletableFuture<MessagingService> start() {
         .thenCompose(ok -> bootstrapServer())
         .thenRun(
             () -> {
+              final var metrics = new NettyDnsMetrics();
+              dnsResolverGroup =
+                  new DnsAddressResolverGroup(
+                      new DnsNameResolverBuilder(clientGroup.next())
+                          .dnsQueryLifecycleObserverFactory(
+                              new BiDnsQueryLifecycleObserverFactory(
+                                  ignored -> metrics,
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:387]: 🔧 With Java 21 we can now use `_` https://openjdk.org/jeps/443

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 3]
```diff
@@ -721,11 +738,7 @@ private CompletableFuture<Channel> bootstrapClient(final Address address) {
     bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 1000);
     bootstrap.group(clientGroup);
     bootstrap.channel(clientChannelClass);
-    bootstrap.resolver(
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:724]: ❓ So we created on each client a new DNSResolver which opened then a socket got I this right? We now create one and reuse this.

Comment (Zelldon) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:724]: Plus it was not closed before.

**Review by ChrisKujawa — APPROVED** [review]
Nice catch and great work @npepinpe ! 🚀 🎖️

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java (hunk 3 above)
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:724]: Exactly, the problem was it was never closed. The reusability is just because it makes sense to me, there doesn't seem to be any advantage in creating a new one every time.

**Comment by Zelldon** [comment]
> Here's the test I was thinking of using right now:
> 
> ```java
> @Test
>     void shouldNotLeakUdpSockets() throws IOException {
>       // given
>       final var pid = ProcessHandle.current().pid();
>       final var udpPath = Path.of("/proc/" + pid + "/net/udp");
>       final var udp6Path = Path.of("/proc/" + pid + "/net/udp6");
>       // the configured amount of threads for Netty's epoll transport
>       final var maxConnections = Runtime.getRuntime().availableProcessors() * 2;
>       final var subject = nextSubject();
>       netty2.registerHandler(
>           subject, (address, bytes) -> new byte[0], MoreExecutors.directExecutor());
> 
>       // when
>       for (int i = 0; i < maxConnections * 2; i++) {
>         netty1.sendAndReceive(netty2.address(), subject, "hello world".getBytes()).join();
>       }
> 
>       // then
>       final var socketCount =
>           Files.readAllLines(udpPath).size() + Files.readAllLines(udp6Path).size();
>       // add two extra lines due to the headers
>       assertThat(socketCount).isLessThan(maxConnections + 2);
>     }
> ```
> 
> You can read the open sockets for your process via `/proc/<PID>/net/udp` and `/proc/<PID>/net/udp6`, however the test is missing a few things:
> 
> 1. We should only count the sockets opened by the current user, obviously, and these include shared sockets opened by other users. One option is to filter by the `uid` for your current user, but meh.
> 2. The number of sockets obtained via this method seems to be fluctuating, so it might lead to a flaky test.

I guess we need to add a execution condition? Because I think it will not work on windows?

File: atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java [hunk 4]
```diff
@@ -729,4 +712,48 @@ public void testNoRemoteHandlerExceptionEmptyStringValue() {
...
+
+    // when
+    for (int i = 0; i < maxConnections * 4; i++) {
+      netty1.sendAndReceive(netty2.address(), subject, "hello world".getBytes(), false).join();
+    }
+
+    // then - there seems to be a slight amount more than maxConnections normally, but without the
+    // fix this was way, way, way more, so it should be fine to allow a little bit more than the
+    // expected max number of connections
+    assertThat(udpSocketCount()).isLessThanOrEqualTo(maxConnections * 2L);
```
Comment (npepinpe) [inline atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java:734]: I'm not happy that we have to account for more, but if you remove the patch, you'll see that the number of open sockets is way, way more than the max connections, so it's still correct. But I wish we could have an accurate number =/

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java (hunk 2 above)
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:387]: IntelliJ flags this as a preview feature :thinking:

**Comment by npepinpe** [comment]
FYI other than the new test, the only changes in the tests are migrating them to junit 5. You can skip the commit https://github.com/camunda/zeebe/pull/14839/commits/1973e8ba6128fc21a1c6ee5ddac3a898bbdb49bd if that helps.

**Comment by npepinpe** [comment]
Removed the backport label as the original feature was not back ported anywhere.

**Comment by npepinpe** [comment]
Also created a follow up issue: https://github.com/camunda/zeebe/issues/14853

**Comment by npepinpe** [comment]
@Zelldon - do you want to review the test, or are we good to merge?

**Review by ChrisKujawa — APPROVED** [review]
👍🏼

File: atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java [hunk 5]
```diff
@@ -705,4 +712,48 @@ void testNoRemoteHandlerExceptionEmptyStringValue() {
...
+    final var lines = Files.readAllLines(path);
+    final var uid = new UnixSystem().getUid();
+    lines.remove(0);
+
+    // then filter out any sockets not opened by the current user
+    return lines.stream()
+        .filter(
+            line -> {
+              final String[] columns = line.trim().split("\\s+");
+              return Long.parseLong(columns[7]) == uid;
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java:755]: :see_no_evil: That's fair, but in my defense, 7 is a very magic number :magic_wand:

File: atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java [hunk 6]
```diff
@@ -705,4 +712,48 @@ void testNoRemoteHandlerExceptionEmptyStringValue() {
...
+    // given
+    // the configured amount of threads for Netty's epoll transport
+    final var maxConnections = Runtime.getRuntime().availableProcessors() * 2;
+    final var subject = nextSubject();
+    netty2.registerHandler(
+        subject, (address, bytes) -> new byte[0], MoreExecutors.directExecutor());
+
+    // when
+    for (int i = 0; i < maxConnections * 4; i++) {
+      netty1.sendAndReceive(netty2.address(), subject, "hello world".getBytes(), false).join();
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java:729]: Do you mean why we set `keepAlive=false` here? It's because otherwise our channel pool is limited, and we won't create more connections as we keep reusing the same channels. But we do use transient connections in production sometimes, and channels get recreated over time - but it's easiest to test with just creating a new channel every time here.

**Comment by npepinpe** [comment]
bors merge

File: atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java:729]: I was wondering why each request will create an own socket and client.

**Comment by npepinpe** [comment]
bors r+

Died building the docker image in one of the stages :roll_eyes:
