### PR TITLE
Do not reset snapshot replication when a single request timedout

### LINKED ISSUE #11496: Improve raft snapshot replication failure handling
**Description**

Currently, if replicating a snapshot fails due to timeout for example, the leader restarts the snapshot replication and re-sends from the first chunk. If the network is unstable and the timeouts are frequent, then the follower is less likely to receive the complete snapshot before encountering a timeout. To ensure progress in such cases, it would be better if leader/follower can identify what was the last successfully replicated chunk and continue from that point instead of restarting from the beginning.

We observed a similar situation in a [support ticket](https://jira.camunda.com/browse/SUPPORT-15739). It appears that the leader was cpu bottlenecked which resulted in InstallRequest being timed out. So follower was never able to receiving the full snapshot.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Previously, when replicating a snapshot chunk timedout, leader restarts snapshot replication from the first chunk. This can result in a never ending retry loop if one of the other chunk hits a timeout frequently. This can happen more frequent when network latency is high and/or snapshot is large.  To ensure that snapshot replication can complete in such cases,

1. Leader do not reset snapshot replication, instead re-send the same chunk if it encounters a timeout
2. Follower accepts the chunk even if it is a duplicate.

Tests are added where we can inject timeout and observer the behavior. `RaftRandomizedTest` also covers snapshot replication. 

## Related issues

closes #11496 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: zeebe/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java [hunk 1]
```diff
@@ -467,8 +475,14 @@ private void handleInstallResponseFailure(
       final RaftMemberContext member, final InstallRequest request, final Throwable error) {
     // Reset the member's snapshot index and offset to resend the snapshot from the start
     // once a connection to the member is re-established.
-    member.setNextSnapshotIndex(0);
-    member.setNextSnapshotChunk(null);
+    final boolean isTimeout =
+        error instanceof TimeoutException
+            || (error != null && error.getCause() instanceof TimeoutException);
```
Comment (npepinpe) [inline zeebe/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java:480]: :question: What were the case where it would be the cause? Do you think it could also be more deeply nested?

File: zeebe/atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java [hunk 2]
```diff
@@ -223,19 +223,6 @@ public CompletableFuture<InstallResponse> onInstall(final InstallRequest request
       // When all chunks of the snapshot is received the log will be reset. Hence notify the
       // listeners in advance so that they can close all consumers of the log.
       raft.notifySnapshotReplicationStarted();
-    } else {
-      // fail the request if this is not the expected next chunk
-      if (!isExpectedChunk(request.chunkId())) {
```
Comment (npepinpe) [inline zeebe/atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:228]: :wrench: isExpectedChunk can probably removed

File: zeebe/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java [hunk 3]
```diff
@@ -397,11 +398,17 @@ private Optional<InstallRequest> buildInstallRequest(
     }
 
     final SnapshotChunkReader reader = member.getSnapshotChunkReader();
-    if (!reader.hasNext()) {
-      return Optional.empty();
-    }
 
     try {
+      if (member.getNextSnapshotChunk() != null) {
```
Comment (npepinpe) [inline zeebe/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java:403]: :wrench: Please document that the first chunk is null :D

**Review by npepinpe — APPROVED** [review]
:rocket:

File: zeebe/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java (hunk 1 above)
Comment (deepthidevaki) [reply zeebe/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java:480]: `error` is usually `CompletionException` so we always have to get the cause. I don't think it can be more deeply nested.

**Comment by deepthidevaki** [comment]
This was not backported to older versions. But there was an [incident](https://camunda.slack.com/archives/C0769EW6NAW) today for which this would have helped. I don't see any reason not to backport this, although original issue was tagged as an improvement. 

I'm backporting this. /cc @npepinpe
