### PR TITLE
Fix ArrayOutOfBounds / collection has wrong type errors by raising an incident

### LINKED ISSUE #6953: The process instance is stuck if the output collection is modified
**Describe the bug**
If the output collection variable is modified then the process instance is stuck in the multi-instance subprocess.

The sequential/parallel multi-instance subprocess iterates over an input collection and collects the results in an output collection. If the value of the output collection variable is modified (e.g. change the type of the value or reduce the size of the collection) then the inner instance can't be completed. 

The process instance doesn't continue (i.e. it is added to the blacklist). No incidents are created. 

image

**To Reproduce**
1. deploy a process with a sequential/parallel multi-instance subprocess that defines
  * an input collection `= items`
  * an input element `item`
  * an output collection `results`
  * an output element `= r`
2. create an instance with variables `{"items":[1,2,3]}`
3. await until the service task in the subprocess is activated
4. set the value of the variable `results` to `123` (some value that is not a list)
5. complete the job
6. verify that the process instance doesn't continue 

**Expected behavior**
It creates an incident when completing the inner instance.
I can resolve the incident and the process instance continues.

**Log/Stacktrace**

```
MsgpackReaderException: Unable to determine array type, found unknown header byte 0x7b at reader offset 0
```

<details><summary>Full Stacktrace</summary>
 <p>

```
io.zeebe.msgpack.spec.MsgpackReaderException: Unable to determine array type, found unknown header byte 0x7b at reader offset 0
at io.zeebe.msgpack.spec.MsgPackReader.exceptionOnUnknownHeader (MsgPackReader.java:474)
at io.zeebe.msgpack.spec.MsgPackReader.readArrayHeader (MsgPackReader.java:107)
at io.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.insertAt (MultiInstanceBodyProcessor.java:372)
at io.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.lambda$updateOutputCollection$14 (MultiInstanceBodyProcessor.java:355)
at io.zeebe.util.Either$Right.map (Either.java:213)
at io.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.updateOutputCollection (MultiInstanceBodyProcessor.java:346)
at io.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.lambda$updateOutputCollection$13 (MultiInstanceBodyProcessor.java:332)
at java.util.Optional.map (Unknown Source)
at io.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.updateOutputCollection (MultiInstanceBodyProcessor.java:330)
at io.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.beforeExecutionPathCompleted (MultiInstanceBodyProcessor.java:150)
at io.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.beforeExecutionPathCompleted (MultiInstanceBodyProcessor.java:35)
at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.lambda$beforeExecutionPathCompleted$2 (BpmnStateTransitionBehavior.java:406)
at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent (BpmnStateTransitionBehavior.java:489)
at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.beforeExecutionPathCompleted (BpmnStateTransitionBehavior.java:402)
at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionToCompletedWithParentNotification (BpmnStateTransitionBehavior.java:167)
at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.lambda$onComplete$3 (SubProcessProcessor.java:78)
at io.zeebe.util.Either$Right.ifRightOrLeft (Either.java:238)
at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onComplete (SubProcessProcessor.java:74)
at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onComplete (SubProcessProcessor.java:23)
at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent (BpmnStreamProcessor.java:213)
at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$1 (BpmnStreamProcessor.java:134)
at io.zeebe.util.Either$Right.ifRightOrLeft (Either.java:238)
at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord (BpmnStreamProcessor.java:131)
at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord (TypedRecordProcessor.java:54)
at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3 (ProcessingStateMachine.java:296)
at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run (ZeebeTransaction.java:84)
at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction (ProcessingStateMachine.java:286)
at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent (ProcessingStateMachine.java:254)
at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent (ProcessingStateMachine.java:219)
at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent (ProcessingStateMachine.java:210)
at io.zeebe.util.sched.ActorJob.invoke (ActorJob.java:73)
at io.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
at io.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
at io.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:94)
at io.zeebe.util.sched.ActorThread.doWork (ActorThread.java:78)
at io.zeebe.util.sched.ActorThread.run (ActorThread.java:191)
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `1.0.0-alpha7`
 - Configuration:

### LINKED ISSUE #9143: IndexOutOfBounds if output collection of multi-instance is modified
**Describe the bug**

I deployed a BPMN process with a parallel multi-instance embedded subprocess. The multi-instance subprocess defines an output collection to collect the results of the iterations. If the output collection is modified during the iteration (e.g. the size of the output collection is reduced) then multi-instance can't be completed. The processing fails with an `IndexOutOfBounds` exception. The concrete exception may change depending on the modification.   

**To Reproduce**

image

[test-multi-instance-output-collection.bpmn.txt](https://github.com/camunda/zeebe/files/8512641/test-multi-instance-output-collection.bpmn.txt)

1. deploy a BPMN process with a parallel multi-instance embedded subprocess
  * define an output collection variable `results`
2. create an instance of the process
3. modify the variable `results` when the multi-instance is active (e.g. set the variable to `[]` - an empty array)
  * set variables via command
  * set variables via job worker
  * set variable via output mapping (e.g. on the start event of the embedded subprocess)
4. verify that the multi-instance is not completed
5. verify that a related error record is written   

**Expected behavior**

An incident is created if the output element can't be added to the output collection. The incident is visible to the user and allows to fix the issue manually by modifying the output collection.  

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IndexOutOfBoundsException: index=8 capacity=8
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:2212) ~[agrona-1.15.0.jar:1.15.0]
	at org.agrona.concurrent.UnsafeBuffer.getByte(UnsafeBuffer.java:947) ~[agrona-1.15.0.jar:1.15.0]
	at io.camunda.zeebe.msgpack.spec.MsgPackReader.skipValues(MsgPackReader.java:355) ~[zeebe-msgpack-core-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.msgpack.spec.MsgPackReader.skipValue(MsgPackReader.java:350) ~[zeebe-msgpack-core-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.insertAt(MultiInstanceBodyProcessor.java:410) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.lambda$updateOutputCollection$17(MultiInstanceBodyProcessor.java:389) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.Either$Right.map(Either.java:355) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.updateOutputCollection(MultiInstanceBodyProcessor.java:380) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.lambda$updateOutputCollection$16(MultiInstanceBodyProcessor.java:366) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.updateOutputCollection(MultiInstanceBodyProcessor.java:364) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.beforeExecutionPathCompleted(MultiInstanceBodyProcessor.java:153) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.beforeExecutionPathCompleted(MultiInstanceBodyProcessor.java:35) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.lambda$beforeExecutionPathCompleted$5(BpmnStateTransitionBehavior.java:354) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:442) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.beforeExecutionPathCompleted(BpmnStateTransitionBehavior.java:350) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionToCompleted(BpmnStateTransitionBehavior.java:164) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.SubProcessProcessor.lambda$onComplete$3(SubProcessProcessor.java:76) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onComplete(SubProcessProcessor.java:73) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onComplete(SubProcessProcessor.java:23) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:133) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:110) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:107) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:300) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:290) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:253) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:213) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:189) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.0.jar:8.0.0]
```
</p>
</details>

**Environment:**
- Zeebe Version: 8.0.0 (and others)

### PR DESCRIPTION
**Pull request by pihme**
## Description

* Move updating of outbound collection into behavior class
* Some refactorings (mostly renames)
* Check for index out of bounds, implement tests for it
* Check for outbound collection is not an array, implement tests for it

## Related issues

closes #9143
closes #6953

## Definition of Done

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [X] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/behavior/OutputCollectionBehaviorTest.java [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+import java.util.Optional;
+import org.agrona.DirectBuffer;
+import org.agrona.ExpandableArrayBuffer;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.ExtendWith;
+import org.mockito.Answers;
+import org.mockito.junit.jupiter.MockitoExtension;
+
+@ExtendWith(MockitoExtension.class)
+public class OutputCollectionBehaviorTest {
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/behavior/OutputCollectionBehaviorTest.java:38]: :x: I'm in favor of removing this unit test. 

Objections:
* too much mocking to verify the logic
* is closely coupled to the implementation
* too many assumptions on how other classes behave
* the behavior is already covered by `MultiInstanceIncidentTest`

I think that the maintenance costs are higher than the benefits. But I'm happy to discuss it f2f.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/incident/MultiInstanceIncidentTest.java [hunk 2]
```diff
@@ -627,6 +628,182 @@ public void shouldResolveIncidentDueToCompletionCondition() {
...
+
+    Assertions.assertThat(incidentEvent.getValue())
+        .hasErrorType(ErrorType.EXTRACT_VALUE_ERROR)
+        .hasErrorMessage(
+            "Unable to update item in output collection 'outputItems' at position 1 because the size of the collection is: 0. This happens when multiple BPMN elements write to the same variable.")
+        .hasProcessInstanceKey(processInstanceKey);
+  }
+
+  @Test
+  public void shouldResolveIncidentRaisedByOutputElementCannotBeReplacedInOutputCollection() {
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/incident/MultiInstanceIncidentTest.java:669]: :wrench: We could merge this test case into the previous test case `shouldCreateIncidentIfOutputElementCannotBeReplacedInOutputCollection`.

I know that this is handled differently until now. But both test cases have much in common. We would reduce the duplicated code and shrink the test class by merging both test cases.

Same with the other test.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/incident/MultiInstanceIncidentTest.java [hunk 3]
```diff
@@ -627,6 +628,182 @@ public void shouldResolveIncidentDueToCompletionCondition() {
...
+
+    // then the process is able to complete
+    assertThat(
+            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_COMPLETED)
+                .withElementType(BpmnElementType.PROCESS)
+                .withProcessInstanceKey(processInstanceKey)
+                .limitToProcessInstanceCompleted()
+                .exists())
+        .describedAs("the process has completed")
+        .isTrue();
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/incident/MultiInstanceIncidentTest.java:703]: :x: In addition, we should verify that the output collection is updated with the output element after the incident has been resolved.

**Review by saig0 — CHANGES_REQUESTED** [review]
@pihme thank you for fixing the issue :+1: 

I just have a few suggestions and one concern about the test. But I like the direction. 

I highly recommend testing the behavior manually (if not already done). A manual test can discover odd behaviors sometimes easier than our tests.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/incident/MultiInstanceIncidentTest.java (hunk 2 above)
Comment (pihme) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/incident/MultiInstanceIncidentTest.java:669]: Not sure what you have in mind, tbh.

**Comment by pihme** [comment]
@saig0 Incorporated most of your suggestions. Regarding your rephrasing suggestions I took some liberties. 

Two are still open for discussion, clarification.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/behavior/OutputCollectionBehaviorTest.java (hunk 1 above)
Comment (pihme) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/behavior/OutputCollectionBehaviorTest.java]: I agree with all your objections. And I think it's worth it. So let's discuss it f2f.

**Review by saig0 — APPROVED** [review]
Feel free to merge when you're ready. The major points are solved :+1: 

We discussed that 
* we want to merge the two cases in the incident test to avoid duplication
* we could keep the unit mock test (if you prefer) with the assumption that it would help us to root cause issues.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/behavior/OutputCollectionBehaviorTest.java (hunk 1 above)
Comment (pihme) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/behavior/OutputCollectionBehaviorTest.java]: I decided to keep it for now. I added a comment in this class, that the future developer is welcome to delete the class if she/he is annoyed by it.

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
bors cancel

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
bors merge

**Comment by saig0** [comment]
This PR fixed also the issue #6953.
