### PR TITLE
fix: use more robust getLong method

### LINKED ISSUE #44592: Operate V1 decision instance search fails for standalone evaluated decisions
### Description

If a decision has been evaluated standalone, i.e., without a related process, e.g., through the [Evaluate Decision API](https://docs.camunda.io/docs/8.7/apis-tools/camunda-api-rest/specifications/evaluate-decision/), using the [Operate search decision instances API](https://docs.camunda.io/docs/8.7/apis-tools/operate-api/specifications/search-6/) leads to an error.

### Steps to reproduce

1. deploy a DMN diagram
2. call [Evaluate decision](https://docs.camunda.io/docs/8.7/apis-tools/camunda-api-rest/specifications/evaluate-decision/) endpoint with that decision
3. call operate API [search decision instance](https://docs.camunda.io/docs/8.7/apis-tools/operate-api/specifications/search-6/) with size > 0

### Current behavior

The API returns an error

```
{
    "status": 500,
    "message": "Error in reading decision instance",
    "instance": "<uuid>",
    "type": "API application error"
}
```

### Expected behavior

The API returns a list of evaluated decisions

### Workaround

none

### Environment

SaaS & SM

### Version

- Component Version: 8.6+

### Rootcause

There is an exception in the server log:

```
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')	at io.camunda.operate.webapp.api.v1.dao.elasticsearch.ElasticsearchDecisionInstanceDao.searchHitToDecisionInstance(ElasticsearchDecisionInstanceDao.java:184) ~[operate-webapp-8.7.18.jar:8.7.18]	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
```

This happens when trying to cast an integer value from processDefinitionKey to Long in lines 183 and 184 from the [ElasticsearchDecisionInstanceDao](https://github.com/camunda/camunda/blob/157972a890d08556049eb23161b4e74b5075c2fb/operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDecisionInstanceDao.java#L184).

### Solution ideas

Use a more robust solution to get the potential Integer as Long.

### Dev -> QA handover

_No response_

### Links

- Support: https://jira.camunda.com/browse/SUPPORT-30965

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tanjinyi**
## Description

Fixes the long casting issue where `ElasticsearchDao` retrieves `-1` in Integer format for Long values. The tests will be coming from @eppdot's PR.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

related to #44592

### CODE REVIEW

File: operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java [hunk 1]
```diff
@@ -140,4 +140,11 @@ protected QueryBuilder buildMatchDateQuery(final String name, final String dateA
     }
     return null;
   }
+
+  protected Long getLong(final Object value) {
```
Comment (eppdot) [inline operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java:144]: ❌ I think it makes sense to also check for `null` to make this safer. What was the reason for the `toString()` fallback? 🤔

**Review by eppdot — CHANGES_REQUESTED** [review]
👍 can you make the code a bit more robust and also add proper testing of the method/cases. (e.g. create unit tests and port the tests from the other PR)

File: operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java (hunk 1 above)
Comment (tanjinyi) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java:144]: I don't think it's necessary but it was in case we wanted to do string conversions to long. I'm not sure what to put here in place of the string check, returning null is not ideal either. Additionally, the `isInstance` will return false for `null` values and moves it into the `parseLong` method which would then throw a `NumberFormatException` for null values too

Comment (eppdot) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java:144]: How can you be sure, this is never called with `null`? Maybe it's too early in the morning for me, but `value.toString()` would throw a `NullPointerException`, no?

Let's also add some unit tests and ensure behavior 😄

Comment (eppdot) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java:144]: Also, handling `String` here could lead to akward behavior, that is hard to reason about after the fact or detect at all.

Comment (tanjinyi) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java:144]: agh, you're right, it would 

> How can you be sure, this is never called with `null`? Maybe it's too early in the morning for me, but `value.toString()` would throw a `NullPointerException`, no?
> 
> Let's also add some unit tests and ensure behavior 😄

Comment (tanjinyi) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java:144]: I'll just throw a NumberFormatException if it's not an instance of Number.

Comment (eppdot) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java:144]: I still think `null` should short-circuit and also return `null`. What would be the consequence of throwing an exception? what are the other "parsing" helper methods doing?

Comment (tanjinyi) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/dao/elasticsearch/ElasticsearchDao.java:144]: oops, the comment wasn't clear. i've added a short-circuit for the null check and then throwing an exception otherwise

**Review by eppdot — APPROVED** [review]
