### PR TITLE
Use one column family with RocksDB

### LINKED ISSUE #4002: Can we drop multiple ColumnFamily support
**Description**

Currently we use multiple column families ~ 50. This comes with a price, since each column family has his own mem table, index and bloom filter.

We can see [here](https://github.com/zeebe-io/zeebe/issues/3988) how problematic this is.

Actually I'm not really sure whether we need the different column families at all.

> The main idea behind Column Families is that they share the write-ahead log and don't share memtables and table files. By sharing write-ahead logs we get awesome benefit of atomic writes. By separating memtables and table files, we are able to configure column families independently and delete them quickly.
> _from:_ https://github.com/facebook/rocksdb/wiki/Column-Families

Since we not really want to dynamically delete nor create new ones. Furthermore we don't want to configure them separately since usage of the different column families is totally use case dependent. That is why I see no big value in them.

I think it is still possible to use our abstraction and the related enum. If we would use only one column family we would use the Enum.value as key marker and put it as first byte in the keys. In that way the keys are still ordered and we can easily seek and access them. This would mean that we only need to change the implementation for now. We would probably gain a better memory consumption. Still we need to check how the performance would be affected by that.

### LINKED ISSUE #4560: Unstable cluster on bigger state
**Describe the bug**

I have setup an stable cluster on gke (no preemtable nodes) and expected to run a benchmark for a while. Unfortunately it died after around 12 hours.

general

Investigating this I saw that we had unexpected often Leader changes in the cluster.

to-many-leader-changes

These caused then also a growing of the disk space. Because we are not able to compact if we have to often a leader change.

growing-resources

As we can see above only a few restarts are really related due to restarts. The restarts were caused by reaching the memory limit. Probably rocksdb reached there limits again.

memory

We had the problem with our helm charts that the gateway used only one thread to process the requests, which means we were not able to work fast on the created jobs. See related issue #4524 . This caused an growing running count.

running

As you can see we have around 2 million running instances. This big state causes also a bigger snapshot size. 
snapshot-size

This might be related to the leader changes, because it will take a long time to replicate these snapshots. Furthermore it increases the disk usage as well.

**To Reproduce**

Start an usual benchmark with non preemtable nodes and start less workers.
Steps to reproduce the behavior

**Expected behavior**
A stable running system.

**Environment:**
 - OS: k8
 - Zeebe Version: 0.24.0-SNAPSHOT
 - Configuration: elastic, standalone gw

### LINKED ISSUE #5137: low load causes continuously growing of snapshot file count
**Describe the bug**
In order to reproduce https://github.com/zeebe-io/zeebe/issues/5135 I have setup a benchmark with quite small load. One workflow per second created and completed. The configure is our default one.

lowload

If the load is quite small, then the snapshot file count seems to grow continuously. The size of RocksDB seems also to grow. It seems that RocksDB does no compaction.

lowloadres
lowloadrocks1
lowloadrocks2
lowloadrocks3

If we take a look at the snapshot metrics, then we can see that the snapshot file count is continuously growing.

lowloadsnapshot

**To Reproduce**

Run benchmark with low load.

**Expected behavior**

State and snapshot file count is not increasing.

**Environment:**
 - OS: k8s
 - Zeebe Version: SNAPSHOT
 - Configuration: our default benchmark

### LINKED ISSUE #5810: RocksDB Log file seems to grow unlimited
**Describe the bug**

[Reported by an user in slack](https://zeebe-io.slack.com/archives/C6WGNHV2A/p1605086440397500?thread_ts=1603343832.203000&cid=C6WGNHV2A):

> Abhishek Oct 22nd at 07:17
> Hi Team,
> I am using zeebe 0.24.2 helm chart (standlone gateway and 1 broker configuration) setup
> PVC Disk size = 10 gb , Current Disk usage ~ 80%
> Is it ok delete old snapshots manually from PVC disk, will it corrupt the data from disk ?
>  2.  Or is there any configuration/lifecycle policy available to  manage lifecycle of old snapshots, I dont have to keep on monitoring disk usage for zeebe ?

> zell:house_with_garden:  20 days ago
> Several questions regarding this.
> How many partition do you have?
> Which old snapshots do you mean? There should only one snapshot per partition. Zeebe will take care of cleaning up, you should not do that.
> In general how does you configuration look like?
> You can decrease the snapshot interval to trigger compacting more often.
> Why is the disk so small?
> Why not using the latest patch release?

> Abhishek  20 days ago
> Following are the configuration values (satndalone gateway and 1 broker and 2 exporters enabled - hazelcast and elasticsearch)
> ```
> clusterSize: "1"
> partitionCount: "1"
> replicationFactor: "1"
> cpuThreadCount: "2"
> ioThreadCount: "2"
> resources: 
>   requests:
>     cpu: 500m
>     memory: 2Gi
>   limits:
>     cpu: 1000m
>     memory: 4Gi
> ```
> By old snapshots I meant the .sst files in this location /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/7820099-10-1603353704805  I thought that maybe these snapshots are using up my disk space
> So to check actual usage I ran ncdu /  command and my zeebe broker container exited as it went Outof memory while proccessing this command, and when the new container started again on kubernetes it was using only ~5% disk space but all my deployed workflows were intact.
> as you can see in the attached screenshot the usage dropped from 78% to 5% after the container restart
> So wanted to ask whether zeebe was saving some temp data on PVC disk which was growing day by day like logs ?
image (2)

> zell:house_with_garden:  19 days ago
> @Abhishek please never delete these .sst files, these are part of our internal state (RocksDB). If you would delete one of them it would probably cause an inconsistent state.
> So to check actual usage I ran ncdu /  command and my zeebe broker container exited as it went Outof memory while proccessing this command, and when the new container started again on kubernetes it was using only ~5% disk space but all my deployed workflows were intact.
> That sounds weird. But you don't know what else used much space there? Is another pod/container using this PVC?
>  So wanted to ask whether zeebe was saving some temp data on PVC disk which was growing day by day like logs ?
> No. (edited) 
> 
> Abhishek  19 days ago
> That sounds weird. But you don't know what else used much space there? Is another pod/container using this PVC?
> Yes even I was shocked that how it could delete so much data just on a container restart and still have all workflows intact afterwards.
> No other pod/container is using that PVC. Also could not figure out what was using this much space...will keep monitoring from now onwards and let you know if I get any insights.
> Thanks @zell
> 
> zell:house_with_garden:  19 days ago
> Thanks @Abhishek :+1:

> Abhishek  1 hour ago
> From the time we had our last conversation ie. within 19 days ...the PVC disk usage by zeebe broker (total size -10gb) has grown from 5% to 97%
> (Refer screenshot 6)
> Also this time I was able to find out which directory/file  is using so much space
> When I executed
> cd /usr/local/zeebe/data
> ncdu /raft-partition
> I got to know that this directory is occupying 9 Gb of my disk space
> And as per our previous conversation I had shared one observation that after container restart this much space gets free....So I know I can easily restart the container to gain the free space again ...but can you please tell me how important is this(refer screenshot 4) LOG which is almost 8.7 GB and can it be deleted to free disk space
> Scrrenshot (1-4) : Showing space occupied by directories and files in raft-partition directory
> Screenshot 5 : Zeebe Disk usage for last 12 hours
> Screenshot 6 : Zeebe Disk usage for last 15 days
zee1pvc
zee2pvc
zee3pvc
zee4pvc
image
image (1)

**To Reproduce**
Run brokers not on preemtable nodes.

**Expected behavior**
Rolling log file.

**Environment:**
 - OS: k8
 - Zeebe Version: 0.24.2
 - Configuration: helm

### LINKED ISSUE #6038: java.nio.file.FileSystemException: No Space Left on Device
**Describe the bug**
This error was observed in production logs. https://console.cloud.google.com/errors/CMaf_tS4rq6nowE?time=P30D&project=camunda-cloud-240911

This error is somewhat peculiar, because at the time that the error occurred there was ample of disk space available. All persistent volumes were around 20% usage and flat throughout the time.

Error happened twice with a 5 minute period in between

image

Cluster seems healthy to me. It's serving traffic, and aside from some small dips, Yield over 1 week is 99.89%.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
<p>
<pre>
java.nio.file.FileSystemException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/7228399-350-1608639478170-8206587-8206587-1/416435.sst: No space left on device

        at sun.nio.fs.UnixException.translateToIOException (Unknown Source)
        at sun.nio.fs.UnixException.rethrowAsIOException (Unknown Source)
        at sun.nio.fs.UnixException.rethrowAsIOException (Unknown Source)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel (Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newOutputStream (Unknown Source)
        at java.nio.file.Files.newOutputStream (Unknown Source)
        at java.nio.file.Files.write (Unknown Source)
        at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.writeReceivedSnapshotChunk (FileBasedReceivedSnapshot.java:175)
        at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.apply (FileBasedReceivedSnapshot.java:132)
        at io.zeebe.broker.system.partitions.impl.StateControllerImpl$ReplicationContext.apply (StateControllerImpl.java:343)
        at io.zeebe.broker.system.partitions.impl.StateControllerImpl.consumeSnapshotChunk (StateControllerImpl.java:226)
        at io.zeebe.broker.system.partitions.impl.StateReplication.lambda$consume$1 (StateReplication.java:70)
        at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept (DefaultClusterCommunicationService.java:308)
        at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept (DefaultClusterCommunicationService.java:297)
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$3 (NettyMessagingService.java:186)
        at java.util.concurrent.ThreadPoolExecutor.runWorker (Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run (Unknown Source)
        at java.lang.Thread.run (Unknown Source)
</pre>
</p>
</details>

**Environment:**
 - OS: Camunda Cloud/US East
 - Zeebe Version: 0.25.3
 - Configuration: `Test S - Low Latency`

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Migrates the RocksDB multiple column family usage to one column family. 

Acceptance criteria:

 * Tests running :heavy_check_mark: 
 * QA runs :heavy_check_mark: 
 * Zeebe Benchmark :heavy_check_mark: 
 * Low Load Benchmark :heavy_check_mark: 
 * Big State Benchmark :heavy_check_mark: 

For further insights check the related issue and the documented observations https://github.com/zeebe-io/zeebe/issues/4002.

### Benchmarks

Based on our normal benchmarks (three nodes, three partitions and replication factor three) the following impact has been observed

|Impact | Base | One Column |Description|
|---------|---------|-------------------|---------------|
|Memory |base-res|res| Reduces the memory consumption by factor ~4.|
| Snapshots|base-snapshot|snapshot| Reduces snapshot size by factor 4-5 and reduces file count by factor 10.|
| Throughput | base-general-2|general-2| throughput is improved by ~15% | 
| Latency |base-latency|latency| Latency is improved by ~50%|
|RocksDB|base-rocks1|rocks1|RocksDb stays in his bounds.|
|RocksDB 2|base-rocks2|rocks2|SST file size usage is reduced by factor 4, correlates to the snapshot size reduction.|

Based on the results we can see in the benchmarks I would say the solution fulfills our needs.

#### Big State Benchmark

As part of the acceptance criteria we wanted to investigate how it now behaves on big state and determine whether it changes something in our current support of long running workflows etc.

|Section | Base | One Column |Description|
|---------|---------|-------------------|---------------|
|General|base-big-state-general|big-state-general|We can see that in the base the processing has already stopped.|
|General 2|base-big-state-general-2|big-state-general-2|The one col benchmark is still processing|
|Running workflows|base-big-state-proc|big-state-proc|In the base we have half of the running workflow instances|
|Resources|base-big-state-res|big-state-res| The resource consumption looks similar, except that the one col. uses more java heap. It might be related to the processing stop of the base benchmark.|
|Disk|base-big-state-disk|big-state-disk|The base has a higher disk usage, by factor 2.|
|Snapshots|base-big-state-snap|big-state-snap|The snapshot size is on the base also doubled, which is very likely that this causes to fail the benchmark|
|RocksDB|base-big-state-rocks|big-state-rocks|The one col RocksDB stays pretty well in his bounds.|
|RocksDB 2|base-big-state-rocks2|big-state-rocks2|SST file size usage is much less on the one column benchmark|
|Latency|base-big-state-lat|big-state-lat|Interesting is the latency, which degrades overtime in the one column benchmark.|

I think the results are quite interesting and promising. It seems that we are now more likely to support long running workflows and big states, still we need to fix our current snapshot replication approach but this is a good first step I would say. Furthermore It seems that we trade latency for availability which is totally fine for me.

closes https://github.com/zeebe-io/zeebe/issues/4560

#### Low Load Benchmark

Another acceptance criteria was that low load shouldn't cause more incidents, since earlier this caused defragmentation of RocksDB and there snapshots.

|Section | Base | One Column |Description|
|---------|---------|-------------------|---------------|
|General|base-low-load-general-1|low-load-general-1|We can see that on one col. one node is leader for all partition, which causes higher memory usage on that node|
|General 2|base-low-load-general|low-load-general|Both benchmarks were still running|
|Resources|base-low-load-res|low-load-res|The process memory usage of one col. is much less then for the base|
|Snapshot|base-low-load-snap|low-load-snap|The snapshot size and file count has been reduced a lot at the one col. benchmark|
|Latency|base-low-load-lat|low-load-lat|Looks similar|

As we can see, with this change we can solve our low load problem.

closes https://github.com/zeebe-io/zeebe/issues/5137

## Further Work

We will run another benchmark to see whether the memory issues with frequent snapshots have been mitigated, but 
I think we can already review and merge it as first increment. The results we see above and in the related issue are quite promising and a big improvement.

I created several follow up issues regarding exposing configuration, making things optional etc.

**Follow up issues:**

 * https://github.com/zeebe-io/zeebe/issues/6157
 * https://github.com/zeebe-io/zeebe/issues/6158
 * https://github.com/zeebe-io/zeebe/issues/6159

## Related issues

closes https://github.com/zeebe-io/zeebe/issues/4002 _drop multi column families usage_
closes https://github.com/zeebe-io/zeebe/issues/5137 _low load causes defragmentation_
https://github.com/zeebe-io/zeebe/issues/5185 _investigate high snapshot rate_
closes https://github.com/zeebe-io/zeebe/issues/4560 _unstable cluster on bigger state_
closes https://github.com/zeebe-io/zeebe/issues/5810 _Log file to big_
closes https://github.com/zeebe-io/zeebe/issues/6038 _Out of Disk: to many inodes in use_

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [x] The change has been verified by a QA run
* [x] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [x] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDBMetricExporter.java [hunk 1]
```diff
@@ -77,41 +71,33 @@
...
       try {
         database
-            .getProperty(columnFamilyName, metric.getPropertyName())
+            .getProperty(metric.getPropertyName())
             .map(Double::parseDouble)
-            .ifPresent(value -> metric.exportValue(partition, columnFamilyName, value));
-      } catch (Throwable t) {
-        LOG.debug(t.getMessage(), t);
+            .ifPresent(value -> metric.exportValue(partition, value));
+      } catch (final Exception exception) {
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDBMetricExporter.java:99]: :muscle:

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 2]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
+        .setBytesPerSync(4 * 1024 * 1024L)
+        // limit the size of the manifest (logs all operations), otherwise it will grow
+        // unbounded
+        .setMaxManifestFileSize(256 * 1024 * 1024L)
+        // speeds up opening the DB
+        .setSkipStatsUpdateOnDbOpen(true)
+        // keep 1 hour of logs - completely arbitrary. we should keep what we think would be
+        // a good balance between useful for performance and small for replication
+        .setLogFileTimeToRoll(Duration.ofMinutes(30).toSeconds())
+        .setKeepLogFileNum(2)
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:120]: Just a thought - if we don't disable the WAL for now, we might still want to tune it by limiting its size, reusing WALs, how many to reuse, etc.

I guess that's out of scope now, I can write that on the other issue

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 3]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
-        ColumnFamilyOptions.getColumnFamilyOptionsFromProps(columnFamilyOptionProps);
-    if (columnFamilyOptions == null) {
-      throw new IllegalStateException(
-          String.format(
-              "Expected to create column family options for RocksDB, "
-                  + "but one or many values are undefined in the context of RocksDB "
-                  + "[Compiled ColumnFamilyOptions: %s; User-provided ColumnFamilyOptions: %s]. "
-                  + "See RocksDB's cf_options.h and options_helper.cc for available keys and values.",
-              columnFamilyOptionProps, userProvidedColumnFamilyOptions));
+  public ColumnFamilyOptions createColumnFamilyOptions(final List<AutoCloseable> closeables) {
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:127]:
```suggestion
  private ColumnFamilyOptions createColumnFamilyOptions(final List<AutoCloseable> closeables) {
```

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 4]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
+
+    final var hasUserOptions = !userProvidedColumnFamilyOptions.isEmpty();
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:129]: Above we don't use var, and here we do - I have a slight preference to not use var anymore (happy to discuss why somewhere else :sweat_smile:), but it's not a strong opinion, so here I'd just prefer we be at least consistent in the same file.

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 5]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
+
+    if (hasUserOptions) {
+      final var columnFamilyOptionProps = new Properties();
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:132]: Nit: extract into a separate method and just `return createFromUserOptions(userProvidedColumnFamilyOptions)`

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 6]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
+    final long totalMemoryBudget = 512 * 1024 * 1024L; // make this configurable
+    // recommended by RocksDB, but we could tweak it; keep in mind we're also caching the indexes
+    // and filters into the block cache, so we don't need to account for more memory there
+    final long blockCacheMemory = totalMemoryBudget / 3;
+    // flushing the memtables is done asynchronously, so there may be multiple memtables in memory,
+    // although only a single one is writable. once we have too many memtables, writes will stop.
+    // since prefix iteration is our bread n butter, we will build an additional filter for each
+    // memtable which takes a bit of memory which must be accounted for from the memtable's memory
+    final int maxConcurrentMemtableCount = 6;
+    final double memtablePrefixFilterMemory = 0.15;
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:167]: I guess we should also comment this magic number? I mean it's explained what it does, but the value isn't - basically you put something between 0 and 0.25 (anything higher gets clamped to 0.25), and I randomly picked 0.15 :man_shrugging: Maybe we can add that it's currently a guess, and is candidate for tuning later

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 7]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
+
+    return createDefaultColumnFamilyOptions(closeables);
+  }
+
+  private ColumnFamilyOptions createDefaultColumnFamilyOptions(
+      final List<AutoCloseable> closeables) {
+    final var columnFamilyOptions = new ColumnFamilyOptions();
+
+    // given
+    final long totalMemoryBudget = 512 * 1024 * 1024L; // make this configurable
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:158]:
```suggestion
    final long totalMemoryBudget = 512 * 1024 * 1024L; // TODO: make this configurable
```

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 8]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
+    final double memtablePrefixFilterMemory = 0.15;
+    final long memtableMemory =
+        Math.round(
+            ((totalMemoryBudget - blockCacheMemory) / (double) maxConcurrentMemtableCount)
+                * (1 - memtablePrefixFilterMemory));
+
+    final TableFormatConfig tableConfig = createTableFormatConfig(closeables, blockCacheMemory);
+
+    return columnFamilyOptions
+        // prefix seek must be fast, so allocate an extra 10% of a single memtable budget to create
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:176]: Oops, see it says `extra 10%`, but that comes from `memtablePrefixFilterMemory`, which is now 15% :see_no_evil: 

I guess we should comment that above? idk, but it's probably confusing atm

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 9]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
+        // a filter for each memtable, allowing us to skip them if possible
+        .useFixedLengthPrefixExtractor(Long.BYTES)
+        .setMemtablePrefixBloomSizeRatio(memtablePrefixFilterMemory)
+        // memtables
+        // merge at least 3 memtables per L0 file, otherwise all memtables are flushed as individual
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:181]: Another magic number, I guess we could say it's a rough guess, another candidate for tuning

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 10]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
+        // compaction
+        .setLevelCompactionDynamicLevelBytes(true)
+        .setCompactionPriority(CompactionPriority.OldestSmallestSeqFirst)
+        .setCompactionStyle(CompactionStyle.LEVEL)
+        // L-0 means immediately flushed memtables
+        .setLevel0FileNumCompactionTrigger(maxConcurrentMemtableCount)
+        .setLevel0SlowdownWritesTrigger(
+            maxConcurrentMemtableCount + (maxConcurrentMemtableCount / 2))
+        .setLevel0StopWritesTrigger(maxConcurrentMemtableCount * 2)
+        // configure 4 levels: L1 = 32mb, L2 = 320mb, L3 = 3.2Gb, L4 >= 3.2Gb
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:196]: If we want to support bigger states, we'll probably want to add levels. Can we add a follow up issue for this?

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 11]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
+        .setMaxBytesForLevelBase(32 * 1024 * 1024L)
+        .setMaxBytesForLevelMultiplier(10)
+        .setCompressionPerLevel(
+            List.of(
+                CompressionType.NO_COMPRESSION,
+                CompressionType.NO_COMPRESSION,
+                CompressionType.LZ4_COMPRESSION,
+                CompressionType.LZ4_COMPRESSION))
+        // defines the desired SST file size (but not guaranteed, it is usually lower)
+        // L0 => 8Mb, L1 => 16Mb, L2 => 32Mb, L3 => 64Mb
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:210]: I guess with big state we could still get `OutOfMemoryError` from trying to replicate? I wonder how it didn't happen, since we'd load potentially 4GB of files into memory while waiting for the replication? I mean your benchmark shows it works, but I'm surprised it does :sweat_smile:

**Review by npepinpe — COMMENTED** [review]
:tada: 

I didn't do the most thorough review, I'll leave that to the others (:hand_over_mouth:), so I'm just going to note some things here:

- we still use the wording `ColumnFamily` in a bunch of places (e.g. `ZeebeDb<ColumnFamilyType>`): should we change that?
- Do we need a long for the CF prefix? That seems like, uh, way too many possible values :sweat_smile: I used a short in the prototype, and even then I was wondering if a byte might be enough.

**Comment by Zelldon** [comment]
> Do we need a long for the CF prefix? That seems like, uh, way too many possible values sweat_smile I used a short in the prototype, and even then I was wondering if a byte might be enough.

I thought about a while as well and my conclusion was that this gives us more possibilities then just having a byte as prefix, since you can use the left free space for other stuff like version or other metadata which we might add in the future.

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java (hunk 2 above)
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:120]: Please create a follow up issue for that yes.

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java (hunk 10 above)
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:196]: Feel free to create one :D

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java (hunk 11 above)
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:210]: Yes I agree this is also what I mentioned above that we still need to fix the replication stuff.

**Comment by npepinpe** [comment]
> > Do we need a long for the CF prefix? That seems like, uh, way too many possible values sweat_smile I used a short in the prototype, and even then I was wondering if a byte might be enough.
> 
> I thought about a while as well and my conclusion was that this gives us more possibilities then just having a byte as prefix, since you can use the left free space for other stuff like version or other metadata which we might add in the future.

I don't know, it'd be complicated to have versions/metadata as part of the prefix since this changes the ordering, so now you have different ordering for the same "column" or group...I'd like to hear what others think, but I'm not sure about it.

**Comment by Zelldon** [comment]
> we still use the wording ColumnFamily in a bunch of places (e.g. ZeebeDb<ColumnFamilyType>): should we change that?

I think we shouldn't since we only changed the implementation, API wise we still using column families.

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java (hunk 11 above)
Comment (npepinpe) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:210]: But I still don't get how you didn't run into it - I guess we replicate fast enough that memory gets freed fast enough and we can keep replicating? :confused:

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java (hunk 10 above)
Comment (npepinpe) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:196]: https://github.com/zeebe-io/zeebe/issues/6179

Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:196]: Thanks @npepinpe :+1:

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/TransactionalColumnFamily.java [hunk 12]
```diff
@@ -50,7 +58,7 @@ public void put(final KeyType key, final ValueType value) {
 
   @Override
   public void put(final DbContext context, final KeyType key, final ValueType value) {
-    transactionDb.put(handle, context, key, value);
+    transactionDb.put(handle, context, compositeKey, value);
```
Comment (MiguelPires) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/TransactionalColumnFamily.java:61]: The TransactionalColumnFamily doesn't really align well with the ColumnFamily interface. The keys passed into TransactionalColumnFamily are never used (explicitly) so having them is not only unnecessary but possibly misleading. If we pass a different key when calling an operation, the result would be unexpected. Maybe we can change the interface to reflect the new semantics. wdyt?

**Review by miguelpires — CHANGES_REQUESTED** [review]
Looks good, I just have a couple of small comments.
- Keeping the name "column family" in places where we just use the enum value as a part of the key might seem confusing to a future maintainer. I get that this way we can maintain the abstraction that there are multiple column families but it might not be so clear in the future.  This is not a great issue for me, so if you want to keep it I'd leave it at your discretion
- I assume that the idea of keeping the handle in the TransactionDb and passing it with each operation is a way of maintaining the abstraction of mulitple column families intact? I found this to be a bit confusing. TransactionalColumnFamily calls `getColumnFamilyHandle()` which takes a columnFamily but no longer uses it since it always returns the default. Then it's used with most methods except the iteration ones since `newIterator` takes the handle but then doesn't use that to map anything and uses the default. T, I would simplify it and just use the default handle in the db, removing it from TransactionalColumnFamily. Then we could remove that arguments from all of the methods that end up not using it (`isEmpty` and `whileEqualPrefix`)

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 13]
```diff
@@ -55,84 +68,189 @@ private ZeebeRocksDbFactory(
...
-    return columnFamilyOptions;
+
+    return createDefaultColumnFamilyOptions(closeables);
+  }
+
+  private ColumnFamilyOptions createDefaultColumnFamilyOptions(
+      final List<AutoCloseable> closeables) {
+    final var columnFamilyOptions = new ColumnFamilyOptions();
+
+    // given
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:157]: tbh this was just something I copied from the other branch - I assume it was meant to mark this variable as given, like it should be given via config. I can remove it.

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/TransactionalColumnFamily.java (hunk 12 above)
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/TransactionalColumnFamily.java:61]: I kind of agree. Tbh I just did the minimal things to keep the changes and the review small. Sorry if this was confusing to you then. Are you fine when I create a follow up issue for refactoring it? I happily do it, but would like to do it separately.

**Comment by Zelldon** [comment]
I have setup yesterday an benchmark on stable nodes with frequent snapshots (1 min snapshot interval) to reproduce memory issues which are described here https://github.com/zeebe-io/zeebe/issues/5736. It looks quite promising and I think we are coming closer to a solution of this problem or at least it looks better now for me. I will keep the benchmark running for an week.

### Benchmark

| Section | Base | One column | Description |
|------------|--------|------------------|-----------------|
| General | base-freq-snap-general | freq-snap-general | We can see that on the base benchmark two out of three partitions stopped working at some point. |
| General 2 | base-freq-snap-general-2 | freq-snap-general-2 | The processing on the one col. looks more or less stable |
| Snapshot | base-freq-snap-snapshot | freq-snap-snapshot | On the base we stopped at some point with taking snapshots. The snapshot seem to be quite big. |
| Resources | base-freq-snap-res | freq-snap-res | We can see that at the base we reached quite often the limit. On the one column family only the java heap seems to be increasing. |
| Disk | base-freq-snap-disk | freq-snap-disk | The disk usage of the base went up, might be related to unhealthy partitions. |
| RocksDB | base-freq-snap-rocks | freq-snap-rocks | One column benchmark seem to stay in his bounds. |
| RocksDB 2 | base-freq-snap-rocks2 | freq-snap-rocks2 | The difference between the SST file sizes is enormously.|


\cc @deepthidevaki

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/TransactionalColumnFamily.java (hunk 12 above)
Comment (MiguelPires) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/TransactionalColumnFamily.java:61]: Absolutely 👍 it's not urgent, it that can be a follow-up issue. Thanks

**Comment by npepinpe** [comment]
I think @deepthidevaki also noticed in her previous tests that the heap was slowly going up. I hope its not a new memory leak 🤞though this one should be easier to track down.

Looks good, can't wait to get this issue closed 😄

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/TransactionalColumnFamily.java (hunk 12 above)
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/TransactionalColumnFamily.java:61]: thanks I created https://github.com/zeebe-io/zeebe/issues/6206

**Comment by deepthidevaki** [comment]
> I think @deepthidevaki also noticed in her previous tests that the heap was slowly going up. I hope its not a new memory leak crossed_fingersthough this one should be easier to track down.
> 

Heaps looked good in my experiments. I observed direct memory slowly going up over several days. It was too small compared to rocksdb memory usage. So I ignored it. But now if everything else is in control, that could be the next candidate to look into.

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java [hunk 14]
```diff
@@ -343,6 +301,7 @@ private void foreach(
    * <p>While iterating over subsequent keys we have to validate it.
    */
   protected <KeyType extends DbKey, ValueType extends DbValue> void whileEqualPrefix(
+      final DbLong columnFamilyKey,
```
Comment (deepthidevaki) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java:304]: Where do we actually test this? I can't find it.

**Review by deepthidevaki — APPROVED** [review]
LGTM. :+1: Just have some minor comments - mostly questions.

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 15]
```diff
@@ -55,84 +66,196 @@ private ZeebeRocksDbFactory(
...
+            List.of(
+                CompressionType.NO_COMPRESSION,
+                CompressionType.NO_COMPRESSION,
+                CompressionType.LZ4_COMPRESSION,
+                CompressionType.LZ4_COMPRESSION))
+        // defines the desired SST file size (but not guaranteed, it is usually lower)
+        // L0 => 8Mb, L1 => 16Mb, L2 => 32Mb, L3 => 64Mb
+        // as levels get bigger, we want to have a good balance between the number of files and the
+        // individual file sizes
+        .setTargetFileSizeBase(8 * 1024 * 1024L)
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:217]: `minWriteBufferToMerge` just describes the minimum it should wait until it can flush - not the exact number it will be, so it can always be greater. From experience, I could never get the file size to be within expected range without the targetFileSize setting.

**Review by miguelpires — APPROVED** [review]

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 16]
```diff
@@ -55,84 +66,196 @@ private ZeebeRocksDbFactory(
...
 
-    if (columnFamilyNames != null && !columnFamilyNames.isEmpty()) {
-      for (final byte[] name : columnFamilyNames) {
-        final ColumnFamilyDescriptor columnFamilyDescriptor =
-            new ColumnFamilyDescriptor(name, columnFamilyOptions);
-        columnFamilyDescriptors.add(columnFamilyDescriptor);
-      }
-    }
-    return columnFamilyDescriptors;
+    return new DBOptions()
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:95]: Yes there's an overhead of keeping track of all SST files which grows as you get more files and become noticeable with thousands or more, I removed it in the prototype because I saw we had so few files on both low and high load, and never saw much impact. We could still preemptively set it just in case - RocksDB docs mention this has a performance impact however, as every access to an SST file needs to look up the `fd` in a table (even if it's already open), but it's unclear if it really is for us.

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java [hunk 17]
```diff
@@ -55,84 +66,196 @@ private ZeebeRocksDbFactory(
...
+        .setBytesPerSync(4 * 1024 * 1024L)
+        // limit the size of the manifest (logs all operations), otherwise it will grow
+        // unbounded
+        .setMaxManifestFileSize(256 * 1024 * 1024L)
+        // speeds up opening the DB
+        .setSkipStatsUpdateOnDbOpen(true)
+        // keep 1 hour of logs - completely arbitrary. we should keep what we think would be
+        // a good balance between useful for performance and small for replication
+        .setLogFileTimeToRoll(Duration.ofMinutes(30).toSeconds())
+        .setKeepLogFileNum(2)
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:116]: afaik these are just for the log file - yes, we should set `maxLogFileSize`, good catch :muscle:

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java (hunk 16 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:95]: https://github.com/zeebe-io/zeebe/issues/6213

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java (hunk 14 above)
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java:304]: Not sure what you mean @deepthidevaki The functionality of `whileEqualPrefix`? Can you elaborate on that?

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:116]: Java Doc
```java
  /**
   * Specifies the maximum size of a info log file. If the current log file
   * is larger than `max_log_file_size`, a new info log file will
   * be created.
   * If 0, all logs will be written to one log file.
   *
   * @param maxLogFileSize the maximum size of a info log file.
   * @return the instance of the current object.
   * @throws java.lang.IllegalArgumentException thrown on 32-Bit platforms
   *   while overflowing the underlying platform specific value.
   */
  T setMaxLogFileSize(long maxLogFileSize);

  /**
   * Returns the maximum size of a info log file. If the current log file
   * is larger than this size, a new info log file will be created.
   * If 0, all logs will be written to one log file.
   *
   * @return the maximum size of the info log file.
   */
  long maxLogFileSize();

  /**
   * Specifies the time interval for the info log file to roll (in seconds).
   * If specified with non-zero value, log file will be rolled
   * if it has been active longer than `log_file_time_to_roll`.
   * Default: 0 (disabled)
   *
   * @param logFileTimeToRoll the time interval in seconds.
   * @return the instance of the current object.
   * @throws java.lang.IllegalArgumentException thrown on 32-Bit platforms
   *   while overflowing the underlying platform specific value.
   */
  T setLogFileTimeToRoll(long logFileTimeToRoll);

  /**
   * Returns the time interval for the info log file to roll (in seconds).
   * If specified with non-zero value, log file will be rolled
   * if it has been active longer than `log_file_time_to_roll`.
   * Default: 0 (disabled)
   *
   * @return the time interval in seconds.
   */
  long logFileTimeToRoll();

  /**
   * Specifies the maximum number of info log files to be kept.
   * Default: 1000
   *
   * @param keepLogFileNum the maximum number of info log files to be kept.
   * @return the instance of the current object.
   * @throws java.lang.IllegalArgumentException thrown on 32-Bit platforms
   *   while overflowing the underlying platform specific value.
   */
  T setKeepLogFileNum(long keepLogFileNum);

  /**
   * Returns the maximum number of info log files to be kept.
   * Default: 1000
   *
   * @return the maximum number of info log files to be kept.
   */
  long keepLogFileNum();
```

https://github.com/facebook/rocksdb/blob/7c19d43883bdbb26b1cfceeeebeee983e7d5cf20/include/rocksdb/options.h#L601-L617
```cpp
  // Specify the maximal size of the info log file. If the log file
  // is larger than `max_log_file_size`, a new info log file will
  // be created.
  // If max_log_file_size == 0, all logs will be written to one
  // log file.
  size_t max_log_file_size = 0;

  // Time for the info log file to roll (in seconds).
  // If specified with non-zero value, log file will be rolled
  // if it has been active longer than `log_file_time_to_roll`.
  // Default: 0 (disabled)
  // Not supported in ROCKSDB_LITE mode!
  size_t log_file_time_to_roll = 0;

  // Maximal info log files to be kept.
  // Default: 1000
  size_t keep_log_file_num = 1000;
```

I'm not sure here. We set the log file to roll, so as far as I understand it will be enough, since we have not size set we use anyway only one file?

[the remark this answers is not in the document]
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:116]: If I check the long running benchmark we can see that we have two files. One old one and a current one. I assume after 30 min it marks the current as old and writes into a new one


```
root@zell-one-col-memory-zeebe-0:/usr/local/zeebe# ls -lah data/raft-partition/partitions/1/runtime/
total 117M
drwxr-xr-x 2 root root 4.0K Jan 28 06:25 .
drwxr-xr-x 5 root root 4.0K Jan 28 06:25 ..
-rw-r--r-- 1 root root  37M Jan 28 06:25 028919.log
-rw-r--r-- 1 root root 2.0M Jan 28 06:25 028921.sst
-rw-r--r-- 1 root root  21M Jan 28 06:25 028922.log
-rw-r--r-- 1 root root   16 Jan 26 07:04 CURRENT
-rw-r--r-- 1 root root   37 Jan 26 07:04 IDENTITY
-rw-r--r-- 1 root root    0 Jan 26 07:04 LOCK
-rw-r--r-- 1 root root 940K Jan 28 06:25 LOG
-rw-r--r-- 1 root root 2.9M Jan 28 06:15 LOG.old.1611814546976970
-rw-r--r-- 1 root root 1.6M Jan 28 06:25 MANIFEST-000003
-rw-r--r-- 1 root root 6.1K Jan 26 07:04 OPTIONS-000006
```

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:217]:
```
  // Target file size for compaction.
  // target_file_size_base is per-file size for level-1.
  // Target file size for level L can be calculated by
  // target_file_size_base * (target_file_size_multiplier ^ (L-1))
  // For example, if target_file_size_base is 2MB and
  // target_file_size_multiplier is 10, then each file on level-1 will
  // be 2MB, and each file on level 2 will be 20MB,
  // and each file on level-3 will be 200MB.
  //
  // Default: 64MB.
  //
  // Dynamically changeable through SetOptions() API
  uint64_t target_file_size_base = 64 * 1048576;
```

https://github.com/facebook/rocksdb/blob/fd0d35d390e212b617e90d7567102d3e5fd1c706/include/rocksdb/advanced_options.h#L417-L429

[the remark this answers is not in the document]
Comment (npepinpe) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:217]: So my comment is wrong then, L0 is what gets flushed, e.g. 3 to X memtables, and target file size is for L1. So L1 is 8mb, L2 is 16MB, L3 is 32MB only. Or?

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java (hunk 14 above)
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java:304]: API wise nothing has changed. We have the same tests, since they expect usage of multiple column families. We can put and get values from different column families and also iterate over them. This works and is tested in zb-db. We have tests with one but also with multiple column families. Plus in the engine we have tests where we use 50 column families.

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:217]: Yes correct.

[the remark this answers is not in the document]
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java:217]: i will update the comment then
