### PR TITLE
fix: do not handle incident RESOLVE records in the exporter

### LINKED ISSUE #39636: Resolving an incident twice removes the incident
### 

### 

### 

### 

### Description

Resolving an incident through the ["resolve incident" C8 API endpoint](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/resolve-incident/) returns a `204` and changes the state of the incident to `RESOLVED`. The incident continues to be included in search results, e.g the ["process instance incidents search " endpoint](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/search-process-instance-incidents/).

Calling the same endpoint again for the same `incidentKey` returns a `404`. Afterwards the issue is gone from search results as well. It appears the second call caused the data to be removed.

### Steps to reproduce

1. Create a process instance with an incident that can be resolved successfully (resolution can also fail - bug either way). _See "links" for a process definition that can be used._
2. Find the incident through the "process instance incidents search " endpoint](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/search-process-instance-incidents/) and extract its `incidentKey`.
3. Call ["resolve incident"](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/resolve-incident/) for that `incidentKey`. The response should have the status `204`.
4. Wait until the incident has the state `RESOLVED` in the "process instance incidents search " endpoint](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/search-process-instance-incidents/) endpoint.
5. Call ["resolve incident"](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/resolve-incident/) again for that `incidentKey`. The API should return `404`.
6. When calling the "process instance incidents search " endpoint](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/search-process-instance-incidents/), the incident will no longer appear in the result data.

### Current behavior

Calling the same endpoint again for the same `incidentKey` returns a `404`. Afterwards the issue is gone from search results as well. It appears like the second call caused the data to be removed.

### Expected behavior

Calling the same endpoint again for the same `incidentKey` returns a fitting status code - `404` might already be correct. The incident should remain resolved and should continue to exist in result data.

### Workaround

_No response_

### Environment

SM

### Version

- C8 API locally started from the `main` branch. Likely also appears in other 8.8 environments.

### Rootcause

_No response_

### Solution ideas

_No response_

### Links

- Example Prozess that can be started with a `count: 0` variable: [incident_resolve_bug.bpmn.zip](https://github.com/user-attachments/files/22946885/incident_resolve_bug.bpmn.zip)

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

Details can be found [here](https://github.com/camunda/camunda/issues/39636#issuecomment-3553582397)

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #39636

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/PostImporterQueueFromIncidentHandlerTest.java [hunk 1]
```diff
@@ -40,11 +42,14 @@ void testGetEntityType() {
     assertThat(underTest.getEntityType()).isEqualTo(PostImporterQueueEntity.class);
   }
 
-  @Test
-  void shouldHandleRecord() {
+  @ParameterizedTest
+  @EnumSource(
+      value = IncidentIntent.class,
+      names = {"CREATED", "MIGRATED", "RESOLVED"})
+  void shouldHandleRecordWithSupportedIntent(final IncidentIntent intent) {
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/PostImporterQueueFromIncidentHandlerTest.java:49]: 🔧 can we also have a test for the `shouldNotHandle...` in this class? i.e. for `RESOLVE`

File: qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/IncidentIT.java [hunk 2]
```diff
@@ -104,14 +107,42 @@ void shouldUnmarkAllInstancesWithIncident() {
...
+        client.newResolveIncidentCommand(incidentKey).send();
+    assertThat(secondResolveResponse)
+        .failsWithin(Duration.ofSeconds(5))
+        .withThrowableThat()
+        .withRootCauseInstanceOf(ProblemException.class)
+        .withMessageContaining("404: 'Not Found'");
+
+    // then incident is not updated in the secondary storage
+    Awaitility.await()
+        .pollDelay(Duration.ofSeconds(5)) // wait for a while to ensure incident is not updated
```
Comment (RomanJRW) [inline qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/IncidentIT.java:131]: I would say ignore the copilot suggestion, I can't think of an easy way to test this without just waiting unfortunately

**Review by RomanJRW — APPROVED** [review]
LGTM 🎉

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/PostImporterQueueFromIncidentHandlerTest.java (hunk 1 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/PostImporterQueueFromIncidentHandlerTest.java:49]: the test already exists in this class and it is called `shouldNotHandleResolveIntentRecords`
