### PR TITLE
Auth request tenant id fix

### LINKED ISSUE #31977: AuthorizationRequest constructor provides wrong tenant id for tenant ownership check
### 

### 

### 

### 

### Description

When Zeebe processes a command record, it creates an `AuthorizationRequest` instance to encapsulate the "authorization data context", i.e., a DTO for the entity (user, application, or mapping) that made the request. This object is used by the `AuthorizationCheckBehavior` class to verify that the entity that made the request has the correct permissions and authorizations to make this request.

The [`AuthorizationRequest.tenantId` property](https://github.com/camunda/camunda/blob/4729cdd6cd8514acc032705e8de0c4fc4b9dd77f/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java#L416) provides the ID of the tenant that owns the resource on which the operation will be applied. For example:
1. When deploying a process definition, a user will define tenant ID with the request to specify which tenant will own the process definition when deployed.
   - When Zeebe processes the deployment command, it will check if the user is authorized to deploy to the specified tenant.
2. When completing a job, a user doesn't have to specify the ID of the tenant that owns the job. The job is looked up by it's key from the `JobState` and the tenant ID is extracted from there.
- When Zeebe processes the job complete command, it will check if the user is authorized to complete jobs for the tenant that owns the job.

**The bug:**
The `AuthorizationRequest` class currently provides a [constructor that always sets the `<default>` tenant ID](https://github.com/camunda/camunda/blob/4729cdd6cd8514acc032705e8de0c4fc4b9dd77f/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java#L442-L447) to the `AuthorizationRequest.tenantId` property. This is not correct when MultiTenancy is enabled and results in the following:
- An auth check may incorrectly pass when a user is assigned to the `<default>` tenant, but not assigned to the tenant that owns the resource.
- An auth check may incorrectly fail when a user is not assigned to the `<default>` tenant, but assigned to the tenant that owns the resource.

### Steps to reproduce

1. Create a process with a service task
2. Deploy the process to `tenant-a`
3. Start a process instance of the process above
4. Create a user and assign it to `tenant-a`, but not to tenant `<default>`
5. Attempt to activate and complete the job created from the service task.

### Current behavior

The auth check will incorrectly fail since the user is not assigned to the `<default>` tenant, but assigned to the tenant that owns the resource.

### Expected behavior

The auth check should pass since the user is assigned to `tenant-a` that owns the job.

### Environment

SaaS & SM

### Version

- Component Version: Zeebe `8.8.0-SNAPSHOT` (target alpha5)

### Rootcause

The `AuthorizationRequest` constructor that is used in the classes below always provides the `<default>` tenant as the owner of the resource. This is not correct, instead ,the ID of the tenant that owns the resource should be provided.

The following classes have a high risk of incorrect behavior as they work with resources owned by specific tenants:
* DefaultJobCommandPreconditionGuard
* UserTaskCommandPreconditionChecker
* ResourceFetchProcessor
* IncidentResolveProcessor
* JobBatchCollector
* JobFailProcessor
* JobUpdateBehaviour
* PermissionsBehavior
* ResourceDeletionDeleteProcessor

The following classes don't work with tenant-owned resources, but may still be impacted by the bug:
* BatchOperationCancelProcessor
* BatchOperationCreateProcessor
* BatchOperationPauseProcessor
* BatchOperationResumeProcessor
* ClockProcessor
* GroupAddEntityProcessor
* GroupCreateProcessor
* GroupDeleteProcessor
* GroupRemoveEntityProcessor
* GroupUpdateProcessor
* MappingCreateProcessor
* MappingDeleteProcessor
* MappingUpdateProcessor
* RoleAddEntityProcessor
* RoleCreateProcessor
* RoleDeleteProcessor
* RoleRemoveEntityProcessor
* RoleUpdateProcessor
* TenantAddEntityProcessor
* TenantCreateProcessor
* TenantDeleteProcessor
* TenantRemoveEntityProcessor
* TenantUpdateProcessor
* UserCreateProcessor
* UserDeleteProcessor
* UserUpdateProcessor

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Ensure that the ID of the tenant that owns a given resource is passed to the authorization check when a processor accepts a command to operate on that resource.

Furthermore, internal data (like Users, Roles, Groups, Tenants) is not owned by tenants, and tenant ownership doesn't need to be validated in the authorization check for this type of entities. This PR adds a flag to the AuthorizationRequest class to specify when data is tenant-owned. The flag is then used to skip tenant checks.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #31977

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java [hunk 1]
```diff
@@ -413,35 +412,47 @@ public static final class AuthorizationRequest {
...
+    }
+
+    public AuthorizationRequest(
+        final TypedRecord<?> command,
+        final AuthorizationResourceType resourceType,
+        final PermissionType permissionType,
+        final String tenantId,
+        final boolean isNewResource) {
+      this(command, resourceType, permissionType, tenantId, isNewResource, true);
     }
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java:441]: 💭 I wonder if we should to more of a builder pattern as opposed to having all these overloaded constructors. But that's a refactoring we can always do at a later point in time.

**Review by remcowesterhoud — APPROVED** [review]

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java (hunk 1 above)
Comment (koevskinikola) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java:441]: I thought about that as well, but then I would have had to refactor all the processors where the `tenantId` is needed, which would have pushed the scope of this PR a bit.

I created [a task](https://github.com/camunda/camunda/issues/32467) for this.
