### PR TITLE
Fix flaky JobMetricsTest

### LINKED ISSUE #10160: JobMetricsTest.shouldCountTimedOut  is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once (saw it on main) https://github.com/camunda/zeebe/runs/7987166782?check_suite_focus=true

- Does it block your work? Not yet
- Do we suspect that it is a real failure? Maybe

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.camunda.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:72)
	at io.camunda.zeebe.engine.metrics.JobMetricsTest.shouldCountTimedOut(JobMetricsTest.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:[413](https://github.com/camunda/zeebe/runs/7987166782?check_suite_focus=true#step:7:414))
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[Test results for Slow Unit Tests.zip](https://github.com/camunda/zeebe/files/9414579/Test.results.for.Slow.Unit.Tests.zip)

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

This test activates a job with a timeout of 10 minutes. After activating the engine time is increased by 10 minutes. The test will now verify that the job has run into a timeout. The assertion we do has a maximum waiting time of 5 seconds. The `JobTimeoutTrigger` is scheduled once every 30 seconds. This results in a relatively high margin of error. The expectation would be that the test fails 1 in 6 times. This is not the case. Most of the time the test succeeds. My assumption is that the increase in engine time will cause the `JobTimeoutTrigger` to be executed as the increase > 30 seconds. The activating of the Job takes a few milliseconds. This means that in reality this job does not time out after 10 minutes exactly, but after 10 minutes + a few milliseconds. If the `JobTimeoutTrigger` triggers immediately when the engine time is increased this could mean that the job still has a few milliseconds before it's supposed to time out. These few milliseconds are the margin of error. Since the next trigger will be in 30 seconds, the job won't time out within the 5 seconds we try to assert.

By increasing the engine time with 50ms more, we know for sure that the Job has passed it's timeout time and the trigger will write the `TIMEOUT` command.

## Related issues

closes #10160 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/metrics/JobMetricsTest.java [hunk 1]
```diff
@@ -96,7 +96,7 @@ public void shouldCountTimedOut() {
     ENGINE.jobs().withType(JOB_TYPE).withTimeout(timeout.toMillis()).activate();
 
     // when
-    ENGINE.getClock().addTime(timeout);
+    ENGINE.getClock().addTime(timeout.plus(Duration.ofMillis(50)));
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/metrics/JobMetricsTest.java:99]: :wrench: We could make the time shift less fuzzy by using the record timestamp instead.

The additional time of 50 milliseconds might be enough in most cases. But in the CI, it could take longer. 

In the implementation, it adds the timeout to the timestamp of the `activate` command. We could do something similar by calculating the time shift based on the timestamp of the `activated` event that is returned by the activation.

**Review by saig0 — APPROVED** [review]
@remcowesterhoud good catch. :+1: 

I like your explanation. I have a suggestion on how to make it a bit less fuzzy. Please have a look.

File: engine/src/test/java/io/camunda/zeebe/engine/metrics/JobMetricsTest.java (hunk 1 above)
Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/metrics/JobMetricsTest.java:99]: Clever! I like that 🍪

**Comment by remcowesterhoud** [comment]
bors merge
