### PR TITLE
fix: prevent access of closed rocksdb instances from async scheduled tasks

### LINKED ISSUE #11908: RocksDB segfaults when running engine unit tests
**Describe the bug**

When running the engine unit tests, there's a segmentation fault in RocksDB.

**To Reproduce**

Not clear, happened on CI: https://github.com/camunda/zeebe/actions/runs/4321761695/jobs/7543371810

**Expected behavior**

No segmentation faults

**Log/Stacktrace**

[hs_err_pid23696.log](https://github.com/camunda/zeebe/files/10881657/hs_err_pid23696.log)

<details><summary>JVM error report snippets</summary>
 <p>

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=23696, tid=33784
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# Core dump will be written. Default location: /core.%e.23696.%t
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/runner/_work/zeebe/zeebe/engine/target/jacoco.exec /runner/_work/zeebe/zeebe/engine/target/surefire/surefirebooter-20230303085420925_1059.jar /runner/_work/zeebe/zeebe/engine/target/surefire 2023-03-03T08-51-16_818-jvmRun3 surefire-20230303085420925_1044tmp surefire_124-20230303085420925_1056tmp

Host: Intel(R) Xeon(R) CPU @ 2.80GHz, 16 cores, 50G, Ubuntu 20.04.5 LTS
Time: Fri Mar  3 08:54:58 2023 UTC elapsed time: 37.641046 seconds (0d 0h 0m 37s)

---------------  T H R E A D  ---------------

Current thread (0x00007f4e348c2850):  JavaThread "-zb-actors-6" [_thread_in_native, id=33784, stack(0x00007f4ddc14c000,0x00007f4ddc24d000)]

Stack: [0x00007f4ddc14c000,0x00007f4ddc24d000],  sp=0x00007f4ddc24ade8,  free space=1019k
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 6733  org.rocksdb.OptimisticTransactionDB.beginTransaction_withOld(JJJ)J (0 bytes) @ 0x00007f4e2531dfe0 [0x00007f4e2531dfa0+0x0000000000000040]
J 6927 c1 org.rocksdb.OptimisticTransactionDB.beginTransaction(Lorg/rocksdb/WriteOptions;Lorg/rocksdb/Transaction;)Lorg/rocksdb/Transaction; (79 bytes) @ 0x00007f4e1de7bf7c [0x00007f4e1de7bee0+0x000000000000009c]
J 6539 c1 io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.renewTransaction(Lorg/rocksdb/Transaction;)Lorg/rocksdb/Transaction; (25 bytes) @ 0x00007f4e1ddd772c [0x00007f4e1ddd76c0+0x000000000000006c]
J 5799 c1 io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.resetTransaction()V (34 bytes) @ 0x00007f4e1dc97564 [0x00007f4e1dc974c0+0x00000000000000a4]
j  io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInNewTransaction(Lio/camunda/zeebe/db/TransactionOperation;)V+10
J 10683 c1 io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(Lio/camunda/zeebe/db/TransactionOperation;)V (134 bytes) @ 0x00007f4e1e06528c [0x00007f4e1e065060+0x000000000000022c]
J 11496 c1 io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(Lio/camunda/zeebe/db/impl/rocksdb/transaction/TransactionConsumer;)V (29 bytes) @ 0x00007f4e1e255bd4 [0x00007f4e1e255720+0x00000000000004b4]
j  io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(Lio/camunda/zeebe/db/KeyValuePairVisitor;)V+15
j  io.camunda.zeebe.engine.state.message.DbMessageState.visitMessagesWithDeadlineBefore(JLio/camunda/zeebe/engine/state/immutable/MessageState$ExpiredMessageVisitor;)V+19
j  io.camunda.zeebe.engine.processing.message.MessageTimeToLiveChecker.execute(Lio/camunda/zeebe/stream/api/scheduling/TaskResultBuilder;)Lio/camunda/zeebe/stream/api/scheduling/TaskResult;+28
j  io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.lambda$runAtFixedRate$1(Lio/camunda/zeebe/stream/api/scheduling/Task;Ljava/time/Duration;Lio/camunda/zeebe/stream/api/scheduling/TaskResultBuilder;)Lio/camunda/zeebe/stream/api/scheduling/TaskResult;+10
j  io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl$$Lambda$1003+0x000000080120aef8.execute(Lio/camunda/zeebe/stream/api/scheduling/TaskResultBuilder;)Lio/camunda/zeebe/stream/api/scheduling/TaskResult;+13
j  io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.lambda$toRunnable$5(Lio/camunda/zeebe/stream/api/scheduling/Task;)V+115
j  io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl$$Lambda$1004+0x000000080120b120.run()V+8
J 11344 c1 io.camunda.zeebe.scheduler.ActorJob.invoke()V (96 bytes) @ 0x00007f4e1e203384 [0x00007f4e1e203080+0x0000000000000304]
J 11343 c1 io.camunda.zeebe.scheduler.ActorJob.execute(Lio/camunda/zeebe/scheduler/ActorThread;)V (351 bytes) @ 0x00007f4e1e20034c [0x00007f4e1e2001e0+0x000000000000016c]
J 12109 c1 io.camunda.zeebe.scheduler.ActorTask.execute(Lio/camunda/zeebe/scheduler/ActorThread;)Z (350 bytes) @ 0x00007f4e1dad225c [0x00007f4e1dad1fc0+0x000000000000029c]
J 11428 c1 io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask()V (224 bytes) @ 0x00007f4e1e247f24 [0x00007f4e1e247cc0+0x0000000000000264]
J 9919 c2 io.camunda.zeebe.scheduler.ActorThread.doWork()V (285 bytes) @ 0x00007f4e251d40fc [0x00007f4e251d3980+0x000000000000077c]
J 11082% c1 io.camunda.zeebe.scheduler.ActorThread.run()V (103 bytes) @ 0x00007f4e1e15eb14 [0x00007f4e1e15e9c0+0x0000000000000154]
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

[...]

VM Arguments:
jvm_args: -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/runner/_work/zeebe/zeebe/engine/target/jacoco.exec 
java_command: /runner/_work/zeebe/zeebe/engine/target/surefire/surefirebooter-20230303085420925_1059.jar /runner/_work/zeebe/zeebe/engine/target/surefire 2023-03-03T08-51-16_818-jvmRun3 surefire-20230303085420925_1044tmp surefire_124-20230303085420925_1056tmp
java_class_path (initial): /runner/_work/zeebe/zeebe/engine/target/surefire/surefirebooter-20230303085420925_1059.jar
Launcher Type: SUN_STANDARD

[Global flags]
     intx CICompilerCount                          = 4                                         {product} {ergonomic}
     uint ConcGCThreads                            = 3                                         {product} {ergonomic}
     uint G1ConcRefinementThreads                  = 12                                        {product} {ergonomic}
   size_t G1HeapRegionSize                         = 8388608                                   {product} {ergonomic}
    uintx GCDrainStackTargetSize                   = 64                                        {product} {ergonomic}
   size_t InitialHeapSize                          = 838860800                                 {product} {ergonomic}
   size_t MarkStackSize                            = 4194304                                   {product} {ergonomic}
   size_t MaxHeapSize                              = 13421772800                               {product} {ergonomic}
   size_t MaxNewSize                               = 8053063680                                {product} {ergonomic}
   size_t MinHeapDeltaBytes                        = 8388608                                   {product} {ergonomic}
   size_t MinHeapSize                              = 8388608                                   {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5839372                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122909434                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122909434                              {pd product} {ergonomic}
    uintx ReservedCodeCacheSize                    = 251658240                              {pd product} {ergonomic}
     bool SegmentedCodeCache                       = true                                      {product} {ergonomic}
   size_t SoftMaxHeapSize                          = 13421772800                            {manageable} {ergonomic}
     bool UseCompressedClassPointers               = true                           {product lp64_product} {ergonomic}
     bool UseCompressedOops                        = true                           {product lp64_product} {ergonomic}
     bool UseG1GC                                  = true                                      {product} {ergonomic}

Logging:
Log output configuration:
 #0: stdout all=warning uptime,level,tags
 #1: stderr all=off uptime,level,tags

Environment Variables:
JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.6-10/x64
PATH=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.6-10/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/runner/.local/bin

Signal Handlers:
   SIGSEGV: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
    SIGBUS: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
    SIGFPE: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGPIPE: javaSignalHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGXFSZ: javaSignalHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
    SIGILL: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGUSR2: SR_handler in libjvm.so, mask=00100000000000000000000000000000, flags=SA_RESTART|SA_SIGINFO
    SIGHUP: UserHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
    SIGINT: UserHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGTERM: UserHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGQUIT: UserHandler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO
   SIGTRAP: crash_handler in libjvm.so, mask=11100100010111111101111111111110, flags=SA_RESTART|SA_SIGINFO


---------------  S Y S T E M  ---------------

OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
uname: Linux 5.10.161+ #1 SMP Thu Jan 5 22:49:42 UTC 2023 x86_64
OS uptime: 0 days 0:15 hours
libc: glibc 2.31 NPTL 2.31 
rlimit (soft/hard): STACK 8192k/infinity , CORE infinity/infinity , NPROC infinity/infinity , NOFILE 1048576/1048576 , AS infinity/infinity , CPU infinity/infinity , DATA infinity/infinity , FSIZE infinity/infinity , MEMLOCK 64k/64k
load average: 20.48 14.56 6.24

/proc/meminfo:
MemTotal:       65861696 kB
MemFree:        49620900 kB
MemAvailable:   53586368 kB
Buffers:          139440 kB
Cached:          7093712 kB
SwapCached:            0 kB
Active:          2535048 kB
Inactive:       12884200 kB
Active(anon):    1909108 kB
Inactive(anon):  9154436 kB
Active(file):     625940 kB
Inactive(file):  3729764 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               300 kB
Writeback:             0 kB
AnonPages:       8184936 kB
Mapped:           668744 kB
Shmem:           2928488 kB
KReclaimable:     336944 kB
Slab:             484592 kB
SReclaimable:     336944 kB
SUnreclaim:       147648 kB
KernelStack:       21616 kB
PageTables:        32256 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    32930848 kB
Committed_AS:   19020096 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       25928 kB
VmallocChunk:          0 kB
Percpu:            11776 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      340800 kB
DirectMap2M:    13287424 kB
DirectMap1G:    55574528 kB

/sys/kernel/mm/transparent_hugepage/enabled: always [madvise] never
/sys/kernel/mm/transparent_hugepage/defrag (defrag/compaction efforts parameter): always defer defer+madvise [madvise] never

Process Memory:
Virtual Size: 19222668K (peak: 19288204K)
Resident Set Size: 619032K (peak: 619032K) (anon: 580760K, file: 29736K, shmem: 8536K)
Swapped out: 0K
C-Heap outstanding allocations: 155573K, retained: 230662K
glibc malloc tunables: (default)

/proc/sys/kernel/threads-max (system-wide limit on the number of threads): 4194304
/proc/sys/vm/max_map_count (maximum number of memory map areas a process may have): 65530
/proc/sys/kernel/pid_max (system-wide limit on number of process identifiers): 4194304

container (cgroup) information:
container_type: cgroupv1
cpu_cpuset_cpus: 0-15
cpu_memory_nodes: 0
active_processor_count: 15
cpu_quota: 1500000
cpu_period: 100000
cpu_shares: 15360
memory_limit_in_bytes: 52428800 k
memory_and_swap_limit_in_bytes: unlimited
memory_soft_limit_in_bytes: unlimited
memory_usage_in_bytes: 12003900 k
memory_max_usage_in_bytes: 12006024 k
kernel_memory_usage_in_bytes: 211296 k
kernel_memory_max_usage_in_bytes: unlimited
kernel_memory_limit_in_bytes: 221324 k
maximum number of tasks: unlimited
current number of tasks: 739

KVM virtualization detected
Steal ticks since vm start: 0
Steal ticks percentage since vm start:  0.000

CPU: total 16 (initial active 15) (8 cores per cpu, 2 threads per core) family 6 model 85 stepping 7 microcode 0xffffffff, cx8, cmov, fxsr, ht, mmx, 3dnowpref, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, lzcnt, tsc, tscinvbit, avx, avx2, aes, erms, clmul, bmi1, bmi2, rtm, adx, avx512f, avx512dq, avx512cd, avx512bw, avx512vl, fma, vzeroupper, avx512_vnni, clflush, clflushopt, clwb, hv
CPU Model and flags from /proc/cpuinfo:
model name	: Intel(R) Xeon(R) CPU @ 2.80GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities

Online cpus: 0-15
Offline cpus: 
BIOS frequency limitation: <Not Available>
Frequency switch latency (ns): <Not Available>
Available cpu frequencies: <Not Available>
Current governor: <Not Available>
Core performance/turbo boost: <Not Available>

Memory: 4k page, physical 52428800k(40424772k free), swap 0k(0k free)
Page Sizes: 4k

vm_info: OpenJDK 64-Bit Server VM (17.0.6+10) for linux-amd64 JRE (17.0.6+10), built on Jan 17 2023 00:00:00 by "temurin" with gcc 10.3.0

END.

```

</p>
</details>

**Environment:**
- OS: Linux
- Zeebe Version: 5b6ad89566f7444abc6a5990d92e109d4699e6dd

### PR DESCRIPTION
**Pull request by lenaschoenburg**
The `asyncActor` used for executing scheduled tasks must be closed synchronously when stopping the stream processor to prevent scheduled tasks from accessing resources, especially the `ZeebeDb`, that will be closed after the stream processor is stopped.

fixes #11908 
related to #11788

### CODE REVIEW

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/StreamProcessor.java [hunk 1]
```diff
@@ -264,7 +264,7 @@ private boolean shouldProcessNext() {
 
   private void tearDown() {
     processorActorService.close();
-    asyncActor.closeAsync();
```
Comment (Zelldon) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/StreamProcessor.java:267]: Not sure whether this will work, since we are not allowed to Block in actors.

Try the runOnCompletionBlocking Phase method

Comment (oleschoenburg) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/StreamProcessor.java:267]: I think I found a correct way to do this, check out 9f900e3

**Review by ChrisKujawa — APPROVED** [review]
bors r+

**Comment by oleschoenburg** [comment]
That was an OOM while running the stream processor tests :grimacing:

**Comment by oleschoenburg** [comment]
`shouldRepeatExecutePostCommitTask` does not run through locally

**Comment by oleschoenburg** [comment]
bors merge
