### PR TITLE
fix: Truncate error message based on db vendor contraints (#35647)

### LINKED ISSUE #35647: RDBMS - Truncate error message
As an error message can become very long, we could reach the limits of the maximum column length (currently 4000). 
We have decided [here](https://camunda.slack.com/archives/C08MRKHJ0CD/p1752771343273719?thread_ts=1752053926.063709&cid=C08MRKHJ0CD) that we want to trim and log the error message in this case.

IMPORTANT is to use the correct length were we trim, especially for oracle. See also: [Truncate of big variable values uses wrong base for oracle](https://github.com/camunda/camunda/issues/35097).

**AC**:
* Error message gets trimmed based on the max possible length of the column (and the database type)
* If the message gets trimmed, we log the full message.

### PR DESCRIPTION
**Pull request by stefanzilske**
## Description

Incident errorMessage is truncated based on db vendor specific configuration for maxSize and maxBytes.

If the message is truncated the complete message is logged on level WARN.

## Related issues

closes #35647

### CODE REVIEW

**Review by stoerti — COMMENTED** [review]
Good solution 👍 

We have this message pattern too with other objects' error messages:
- `JobDbModel`
- `BatchOperationErrorDbModel`
- `BatchOperationItemDbModel`
- `DecisionInstanceDbModel`

At least for `BatchOperationErrorDbModel` I know that the property will contain a stacktrace. There we should also truncate byte-correct.

File: db/rdbms/src/main/java/io/camunda/db/rdbms/config/VendorDatabaseProperties.java [hunk 1]
```diff
@@ -18,18 +18,25 @@ public class VendorDatabaseProperties {
...
+   * messages will be truncated to this size.
+   */
+  private static final String ERROR_MESSAGE_SIZE = "errorMessage.size";
+
+  /**
+   * Optional property to limit the maximum size of string column in bytes, if required by the
    * database vendor. If not set, no limit is applied.
    */
-  private static final String VARIABLE_VALUE_MAX_BYTES = "variableValue.maxBytes";
+  private static final String COLUMN_MAX_BYTES = "column.maxBytes";
```
Comment (p-wunderlich) [inline db/rdbms/src/main/java/io/camunda/db/rdbms/config/VendorDatabaseProperties.java]: It's just for String / Varchar Columns, not for all, I thin we should be more precise there.

**Review by p-wunderlich — APPROVED** [review]
Good solution, I have just one "naming things" comment.

**Comment by p-wunderlich** [comment]
I've created a follow up issue for the error message handling in batch operations: https://github.com/camunda/camunda/issues/35977

File: db/rdbms/src/main/java/io/camunda/db/rdbms/config/VendorDatabaseProperties.java (hunk 1 above)
Comment (stefanzilske) [reply db/rdbms/src/main/java/io/camunda/db/rdbms/config/VendorDatabaseProperties.java]: Renamed
