### PR TITLE
fix: list backup can handle duplicate backupids of a partition

### LINKED ISSUE #12622: List backup fails when a partition has same backup taken by multiple nodes
**Describe the bug**

Sometime, a partition may attempt to take a backup again when a backup for the same id already exists. This case is rare, but can happen sometimes if there is a leader change while taking a backup. If this happens, list backup fails with an error message:
```
{
    "message": "Duplicate key 1 (attempted merging values BackupStatus[backupId=1, partitionId=1, status=COMPLETED, failureReason=, brokerVersion=8.2.2, createdAt=...])"
}
```

**Expected behavior**
List backup should be able to handle duplicate backup ids for a partition.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Choose a suitable backup when more than one backup exists for a partition with same backupId. This is not a common case, and should happen only in rare cases caused by leader change. 

## Related issues

closes #12622 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java [hunk 1]
```diff
@@ -189,6 +193,31 @@ private List<BackupStatus> aggregateBackupList(
...
+              .formatted(x, y));
+    }
+
+    final List<BackupStatusCode> comparingOrder =
+        List.of(
+            BackupStatusCode.SBE_UNKNOWN,
+            BackupStatusCode.DOES_NOT_EXIST,
+            BackupStatusCode.FAILED,
+            BackupStatusCode.IN_PROGRESS,
+            BackupStatusCode.COMPLETED);
```
Comment (oleschoenburg) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:212]: :wrench: Maybe we should have this statically defined in `BackupListResponse.BackupStatus` or as a helper method? So that this merge logic could just be

```java
if (x.hasBetterStatusThan(y)) {
  return x;
} else {
  return y;
}
```

**Review by lenaschoenburg — APPROVED** [review]
:+1: Looks good to me

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java (hunk 1 above)
Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:212]: `BackupStatus` is generated code from SBE.

**Comment by deepthidevaki** [comment]
bors merge

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java (hunk 1 above)
Comment (oleschoenburg) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:212]: Hm `BackupListResponse.BackupStatus` isn't, we define it here: https://github.com/camunda/zeebe/blob/81ccf953228d0dc77ae7937b174afd02f28e5803/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/encoding/BackupListResponse.java#L119-L125

Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:212]: Oops. Sorry. I thought you meant BackupStatusCode.
