### PR TITLE
Mark command as processed even on processing error

### LINKED ISSUE #13101: On processing error lastProcessPosition is not updated which can cause inconsistent state on restart
**Describe the bug**

For https://github.com/camunda/zeebe/pull/13068 I was testing the upgrade path and whether there are any bad consequences, due to the renaming of the column family. Unfortunately, I run into an issue, where the partition ended up in an inconsistent state. 

Related error group: 
 * https://console.cloud.google.com/errors/detail/CPDM9-CV9Nvk3wE;service=zeebe;version=zell-ban-instance-update?project=zeebe-io
 * https://console.cloud.google.com/errors/detail/CN6dsM6mmY3fIw;service=zeebe;version=zell-ban-instance-update?project=zeebe-io

**Details:** 

The problem was not the renaming itself, but more a bug in the ProcessingStateMachine.

On normal processing, we set the [last successful processed position here](https://github.com/camunda/zeebe/blob/main/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L277), but on error, this is not set. 

 * In my benchmark, I executed a process instance, which caused an error (incl. banning the instance) on 8.2.6.
 * Shortly after this, a snapshot was created.
 *  I manually upgraded the Zeebe cluster to my refactored version. The cluster restarted, on recovery it took the latest snapshot and used the lastProcessedPosition. Since the lastProcessedPosition was not updated it recovered before the command which caused the error. 
 * Replay applied the error event again, resulting in an inconsistent state (since the snapshot itself contained already the change).

**To Reproduce**

baninstance

1. Start a cluster
2. cause banning an instance with 
[baninstance.bpmn.txt](https://github.com/camunda/zeebe/files/11739266/baninstance.bpmn.txt)
3. wait until a snapshot happened, there will be no more processing anyway if there is only one instance
4. restart cluster
5. FAIL

**Expected behavior**

We set the last processed position even on error, to overcome this issue.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbLong{4503599627370497} in ColumnFamily BLACKLIST already exists

at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4 ( io/camunda.zeebe.stream.impl/ReplayStateMachine.java:169 )
at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run ( io/camunda.zeebe.scheduler.future/FutureContinuationRunnable.java:33 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:94 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:45 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:119 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:106 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:87 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:198 )
Caused by: io.camunda.zeebe.db.ZeebeDbInconsistentException

…
at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyDoesNotExist ( TransactionalColumnFamily.java:288 )
at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$insert$0 ( TransactionalColumnFamily.java:82 )
at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19 ( TransactionalColumnFamily.java:316 )
at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction ( DefaultTransactionContext.java:31 )
at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction ( TransactionalColumnFamily.java:315 )
at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.insert ( TransactionalColumnFamily.java:77 )
at io.camunda.zeebe.engine.state.processing.DbBlackListState.blacklist ( DbBlackListState.java:66 )
at io.camunda.zeebe.engine.state.processing.DbBlackListState.blacklistProcessInstance ( DbBlackListState.java:114 )
at io.camunda.zeebe.engine.state.appliers.ErrorCreatedApplier.applyState ( ErrorCreatedApplier.java:25 )
at io.camunda.zeebe.engine.state.appliers.ErrorCreatedApplier.applyState ( ErrorCreatedApplier.java:15 )
at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState ( EventAppliers.java:302 )
at io.camunda.zeebe.engine.Engine.replay ( Engine.java:110 )
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: all
- Configuration:

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Mark a command as processed even when processing failed due to this command and caused it to call `#onProcessingError`.

If we don't mark it, we might replay events again which have been created during `#onProcessingError`,
this can lead to inconsistency. If the consistency checks are enabled the partition will fail to start.

Added a test which verifies that replay is not called, on the restart, in order to make the test reliable we write some more commands and await them to be processed.

## Related issues

closes https://github.com/camunda/zeebe/issues/13101

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by Zelldon** [comment]
:eyes: looking into the flakiness of the test.

File: stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorReplayTest.java [hunk 1]
```diff
@@ -257,6 +266,74 @@ void shouldNotReplayEventIfAlreadyApplied() throws Exception {
...
+
+    // when
+    streamPlatform.startStreamProcessor();
+    streamPlatform.writeBatch(
+        RecordToWrite.command().processInstance(ACTIVATE_ELEMENT, Records.processInstance(1)));
+
+    // then
+    verifyProcessingErrorLifecycle(processorWhichFails);
+    // we shouldn't replay any events - due to snapshot
+    // we shouldn't replay any events - due to snapshot
```
Comment (deepthidevaki) [inline stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorReplayTest.java:298]:
```suggestion
   
```

File: stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorReplayTest.java [hunk 2]
```diff
@@ -257,6 +266,74 @@ void shouldNotReplayEventIfAlreadyApplied() throws Exception {
         .isEqualTo(21L);
   }
 
+  @RegressionTest("https://github.com/camunda/zeebe/issues/13101")
+  public void shouldNotApplyErrorEventOnReplay() throws Exception {
```
Comment (deepthidevaki) [inline stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorReplayTest.java:270]: :wrench: 
```suggestion
  public void shouldNotReplayErrorEventAppliedInSnapshot() throws Exception {
```

**Review by deepthidevaki — APPROVED** [review]
:tada:

**Comment by Zelldon** [comment]
I was able to backport it to 8.2 https://github.com/camunda/zeebe/pull/13225 (with already minimal changes) and 8.1 https://github.com/camunda/zeebe/pull/13252 (with more work). Since the likelihood of this bug is really low (there must be the error event written only, no more commands on the log to be processed before the restart, and consistency checks need to be enabled, which are per default off) I would refuse to backport it to 8.0, the code is completely different, and the tests need to be completely rewritten.

Let me know if you think otherwise @deepthidevaki @megglos
