### PR TITLE
Persist snapshot checksum to avoid recomputing it on every replication

### LINKED ISSUE #6269: Leader cannot send heartbeats when calculating checksum of large snapshot
**Describe the bug**

When starting the replication of a snapshot, the Raft leader will calculate its checksum, which means it has to read the whole snapshot. If the snapshot is large (in the order of GBs), it could take quite a while to calculate, which blocks the Raft thread and causes the leader to be unable to send heartbeats, causing a leader change.

This would be fine, except as this the state for that partition, most likely no leader will be able to replicate it, causing an election loop.

**To Reproduce**

Start a replicated cluster, at least replication factor 3, with 4 CPUs and 16GI memory. Build up a very large state, e.g. 6GB. Disconnect a broker, such that it misses some snapshot, then reconnect it so the Raft replication kicks in and tries to send the snapshot.

**Expected behavior**

The leader can replicate a large snapshot without triggering an election.

**Environment:**
 - OS: official Docker distro
 - Zeebe Version: 0.26.0
 - Configuration: Camunda Cloud Production M v4

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR partially backports the work done in #6326, but removes the usage of the checksum file as a marker file for backwards compatibility. Instead, on startup, if a snapshot does not have a checksum file, it will get created.

It also extends the behaviour by extracting the checksum file from the snapshot folder and making it a sibling file. Snapshots will now have a sibling file with the same name, except with an extension of `.checksum`. Its contents is the same as the old `CHECKSUM` file, a simple long containing the CRC32C checksum of the folder.

The last changes are related to the QA tests. Instead of duplicating the checksum computation logic to compare snapshots, we compare snapshot file names and their contents recursively, including the checksum file. This gives improved error messages and allows us to avoid leaking the checksum logic.

Some corners were cut - for example, the snapshot module's tests have a high degree of redundancy/duplication and unnecessary checks, but refactoring these on a release branch was considered out of scope. Similarly, computation of the checksum should be improved to reduce memory usage (read block by block instead of the whole file all at once), include the file names in the checksum, and compute a global checksum of all data instead of a checksum of checksums. All these were considered out of scope for a release branch and should be done on the main branch after or before (depending) forward porting this to the main branch.

## Related issues

closes #6269 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Hints for the reviewer as this is a large-ish PR:

1. The first commit was cherry picked as is with almost no conflicts (only a small one with imports)
2. The second commit is the extended behaviour, extracting the CHECKSUM file out of the snapshot and as a sibling file, as well as creating it for pre-existing snapshots
3. The rest are adapting existing utilities/fixing tests.

**Comment by npepinpe** [comment]
Had to change CRC32C to CRC32 for backwards compat, all green now :+1:

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java [hunk 1]
```diff
@@ -388,6 +406,23 @@ PersistedSnapshot newSnapshot(final FileBasedSnapshotMetadata metadata, final Pa
...
   }
 
+  private Path buildChecksumFilePath(final FileBasedSnapshotMetadata metadata) {
+    return snapshotsDirectory.resolve(metadata.getSnapshotIdAsString() + CHECKSUM_SUFFIX);
+  }
+
+  private void writeChecksumFile(final Path checksumFile, final long checksum) {
+    try {
+      SnapshotChecksum.persist(checksumFile, checksum);
+    } catch (final IOException e) {
```
Comment (deepthidevaki) [inline snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java:416]: If this fails, shouldn't we delete the snapshot directory?

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java [hunk 2]
```diff
@@ -354,9 +369,12 @@ PersistedSnapshot newSnapshot(final FileBasedSnapshotMetadata metadata, final Pa
     }
 
     final var destination = buildSnapshotDirectory(metadata);
+    final var checksumFile = buildChecksumFilePath(metadata);
     moveToSnapshotDirectory(directory, destination);
+    writeChecksumFile(checksumFile, checksum);
```
Comment (deepthidevaki) [inline snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java:374]: Write checksum first before moving the directory. It would help to detect partial moves in case of crashes.

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshot.java [hunk 3]
```diff
@@ -63,22 +70,26 @@ public long getTerm() {
...
+        LOGGER.warn("Failed to delete snapshot {}", this, e);
+      }
     }
 
     try {
-      FileUtil.deleteFolder(directory);
+      Files.deleteIfExists(checksumFile);
     } catch (final IOException e) {
-      LOGGER.warn("Failed to delete snapshot {}", this, e);
+      LOGGER.warn("Failed to delete snapshot checksum file {}", checksum, e);
```
Comment (deepthidevaki) [inline snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshot.java:92]:
```suggestion
LOGGER.warn("Failed to delete snapshot checksum file {}", checksumFile, e);
```

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshot.java [hunk 4]
```diff
@@ -97,32 +113,59 @@ public String getId() {
...
+
   @Override
   public void close() {
     // nothing to be done
   }
 
   @Override
   public int hashCode() {
-    return Objects.hash(getDirectory(), getMetadata());
+    int result = getDirectory().hashCode();
```
Comment (deepthidevaki) [inline snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshot.java:128]: Why do you have to calculate hash like this?

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks. I mainly focused on the second commit, as it is the new logic.

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java (hunk 2 above)
Comment (npepinpe) [reply snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java:374]: Good idea! I was thinking of using it as a marker file (as we do in 1.0) later, but that's even better.

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshot.java (hunk 4 above)
Comment (npepinpe) [reply snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshot.java:128]: I auto generated the hash using the IntelliJ defaults. I thought we'd discussed this in a team meeting and agreed to just use that in the future? I didn't manually write it.

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java (hunk 1 above)
Comment (npepinpe) [reply snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java:416]: Not if we write the checksum file first :stuck_out_tongue:

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java (hunk 2 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java:374]: Ya. in 1.0 it is ok in which ever order, because if there is no checksum file we detect it as corrupted.

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java (hunk 1 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java:416]: Yes :+1:

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshot.java (hunk 4 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshot.java:128]: :+1: Never seen this autogenerated code. Is it the default in IntelliJ?

Comment (npepinpe) [reply snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshot.java:128]: When you generate it, it asks you how you want to generate it, and one of the options is called `IntelliJ default`. This is what it generates for me :man_shrugging:

**Comment by npepinpe** [comment]
I've updated to write the checksum file before the snapshot :+1:

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Comment by npepinpe** [comment]
It seems all my builds are aborted by connection errors :sweat_smile: (at least the last 3 in a row)
