### PR TITLE
Authorized tenant and category filtering

### LINKED ISSUE #42789: Audit log search endpoint doesn't filter by authorized tenants
### 

### 

### 

### 

### Description

The audit log `/v2/audit-logs/search` endpoint should filter audit log entries by the user/client authorized tenants.

### Steps to reproduce

1. Create a process instance from a defintion deployed to tenantA
2. Create a process instance from a defintion deployed to tenantB
3. Using a user assigned only to tenantA, query the audit log search endpoint

### Current behavior

Audit logs for both process instances can be seen.

### Expected behavior

Only audit logs from the PI assigned to tenantA should be seen.

### Workaround

None. This should be fixed.

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

Probable root-cause: filtering isn't done correctly when the ES/OS query is generated.

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Filter audit logs by authorized tenants and categories.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #42789, #42736, #41120, #41231, #41211, [#42132](https://github.com/camunda/camunda/issues/42132)

### CODE REVIEW

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java [hunk 1]
```diff
@@ -56,4 +56,28 @@ public SearchQuery toSearchQuery(final AuditLogFilter filter) {
...
+    final var tenantCheckQuery =
+        Optional.of(tenantCheck)
+            .map(TenantCheck::tenantIds)
+            .filter(t -> !t.isEmpty())
+            .map(t -> stringTerms(field, t))
+            .orElse(null);
+
+    final var matchGlobalQuery = term(TENANT_SCOPE, AuditLogTenantScope.GLOBAL.name());
+
+    return or(matchGlobalQuery, tenantCheckQuery);
```
Comment (eppdot) [inline search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:90]: ❓ this basically says, give me all audit logs that are wether global or assigned to one of the given tenants in the TenantCheck, right?

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java [hunk 2]
```diff
@@ -56,4 +56,28 @@ public SearchQuery toSearchQuery(final AuditLogFilter filter) {
...
+  }
+
+  @Override
+  protected SearchQuery toAuthorizationCheckSearchQuery(final Authorization<?> authorization) {
```
Comment (eppdot) [inline search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:106]: ❌ it's not clear to me what and why this is done 🤔 which is a sign that this should be refactored to be more expressive or a least some explaining comments need to be added.

File: search/search-domain/src/main/java/io/camunda/search/entities/AuditLogEntity.java [hunk 3]
```diff
@@ -43,6 +43,11 @@ public record AuditLogEntity(
     Long resourceKey)
     implements TenantOwnedEntity {
 
+  @Override
+  public boolean isInTenantScope() {
```
Comment (eppdot) [inline search/search-domain/src/main/java/io/camunda/search/entities/AuditLogEntity.java]: 🔧 rename to `hasTenantScope`

File: webapps-schema/src/main/java/io/camunda/webapps/schema/descriptors/template/AuditLogTemplate.java [hunk 4]
```diff
@@ -13,13 +13,15 @@
...
 import io.camunda.webapps.schema.entities.usermanagement.EntityJoinRelation.EntityJoinRelationFactory;
+import java.util.Optional;
 
 public class AuditLogTemplate extends AbstractTemplateDescriptor
     implements ProcessInstanceDependant, Prio5Backup {
 
   public static final String INDEX_NAME = "audit-log";
   public static final String INDEX_VERSION = "8.9.0";
 
+  public static final String ID = "id";
```
Comment (eppdot) [inline webapps-schema/src/main/java/io/camunda/webapps/schema/descriptors/template/AuditLogTemplate.java:24]: 💭  would it make things better to name `ID` -> `AUDIT_LOG_KEY`?

File: service/src/main/java/io/camunda/service/AuditLogServices.java [hunk 5]
```diff
@@ -49,8 +52,14 @@ public SearchQueryResult<AuditLogEntity> search(final AuditLogQuery query) {
...
-                        withAuthorization(
-                            AUDIT_LOG_READ_AUTHORIZATION, al -> al.category().name())))
+                        AuthorizationConditions.anyOf(
+                            withAuthorization(
+                                AUDIT_LOG_READ_AUTHORIZATION, al -> al.category().name()),
+                            withAuthorization(
+                                PROCESS_INSTANCE_READ_AUTHORIZATION,
+                                al -> al.processDefinitionId()),
+                            withAuthorization(
+                                USER_TASK_READ_AUTHORIZATION, al -> al.processDefinitionId()))))
```
Comment (eppdot) [inline service/src/main/java/io/camunda/service/AuditLogServices.java]: ❓ how to we make sure the authorizations are only applied to user tasks audit log entries and skipped for others?

File: service/src/main/java/io/camunda/service/AuditLogServices.java [hunk 6]
```diff
@@ -72,8 +81,14 @@ public AuditLogEntity getAuditLog(final String auditLogKey) {
                 .withSecurityContext(
                     securityContextProvider.provideSecurityContext(
                         authentication,
-                        withAuthorization(
-                            AUDIT_LOG_READ_AUTHORIZATION, al -> al.category().name())))
+                        AuthorizationConditions.anyOf(
```
Comment (eppdot) [inline service/src/main/java/io/camunda/service/AuditLogServices.java:80]: 🔧 this is pretty much duplicated with line 55, should we store this in a constant/class? or extract into a method?

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java [hunk 7]
```diff
@@ -143,6 +144,16 @@ static void setUp() {
     deployResource(adminClient, "testProcess.bpmn", PROCESS, TENANT_A);
     deployResource(adminClient, "processA.bpmn", PROCESS_A, TENANT_A);
     deployResource(adminClient, "processB.bpmn", PROCESS_B, TENANT_B);
+
+    final var useRest = true;
+    final var useGrpc = false;
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: 💭 use parameterized tests here?

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java [hunk 8]
```diff
@@ -153,149 +164,105 @@ void cleanUp() {
...
-                    .isEqualTo(processInstanceEvent.getProcessDefinitionKey());
-                assertThat(auditLog.getProcessInstanceKey()).isEqualTo(processInstanceKey);
-                assertThat(auditLog.getTenantId()).isEqualTo(TENANT_A);
-                assertThat(auditLog.getResult()).isEqualTo(AuditLogResultEnum.SUCCESS);
-              });
-    }
+  @Test
+  void shouldCreateAuditLogEntryFromPICreation() {
+    final var processInstanceKey = processInstanceEvent.getProcessInstanceKey();
+    Awaitility.await("Audit log entry is created for process instance creation")
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: 🔧 in all tests cases this is utility functionality and should be moved in a helper method. Thus the actual test becomes very clear and to the point.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java [hunk 9]
```diff
@@ -153,149 +164,105 @@ void cleanUp() {
...
+                      .newAuditLogSearchRequest()
+                      .filter(
+                          fn ->
+                              fn.processInstanceKey(String.valueOf(processInstanceKey))
+                                  .operationType(AuditLogOperationTypeEnum.CREATE))
+                      .send()
+                      .join();
+
+              // then
+              assertThat(auditLogItems.items()).hasSize(1);
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: 💭 this is quite a defensive check, is it really necessary? the test would fail if no items were found 🤔 and it's not part of the core logic this test is checking. It's checking that the test setup / utility functionality works, right?

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java [hunk 10]
```diff
@@ -153,149 +164,105 @@ void cleanUp() {
...
-                assertThat(fetchedAuditLog.getProcessDefinitionKey())
-                    .isEqualTo(processInstanceEvent.getProcessDefinitionKey());
-                assertThat(fetchedAuditLog.getProcessInstanceKey()).isEqualTo(processInstanceKey);
-                assertThat(fetchedAuditLog.getTenantId()).isEqualTo(TENANT_A);
-                assertThat(fetchedAuditLog.getResult()).isEqualTo(AuditLogResultEnum.SUCCESS);
-              });
-    }
+  @Test
+  void shouldFetchAuditLogEntryByAuditLogKey() {
+    Awaitility.await("Audit log entry is created and can be fetched by audit log key")
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: 💭 this is all prep work right? couldn't it even go into the before all?

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java [hunk 11]
```diff
@@ -329,107 +294,64 @@ void shouldIsolateAuditLogsByTenant(
...
+                      .send()
+                      .join();
 
-              // User C should see no audit logs since they only have access to ADMIN category
-              // and process instance creation is OPERATOR category
+              // then
               assertThat(userCAuditLogs.items()).isEmpty();
 
-              // Verify that the audit log entry exists for admin
+              // Admin should see the OPERATOR category audit log
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: 🔧 it's not the `OPERATOR` category

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java [hunk 12]
```diff
@@ -329,107 +294,64 @@ void shouldIsolateAuditLogsByTenant(
             });
   }
 
-  @Disabled("https://github.com/camunda/camunda/issues/41120")
   @Test
-  void shouldNotSeeOperatorAuditLogsWithOnlyAdminCategoryPermission(
+  void shouldNotSeeDeployedResourceAuditLogsWithOnlyAdminCategoryPermission(
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: 🔧 it's a bit misleading that the admin user see all logs, but user C is the one that only can see audit logs from the admin category, but not deployed resources.

**Review by eppdot — CHANGES_REQUESTED** [review]
Good Job Nikola.

A few things are not 100% clear to me (could also be because I am not super familiar with identity/auth checks), see the comments I left.

Also I think we could add some more non-IT tests especially for the authorization logic etc.

We can also jump on a sync call to accelerate 😄

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java (hunk 1 above)
Comment (koevskinikola) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:90]: Yes, correct.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java (hunk 11 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: Ah, right. Nice catch!

File: webapps-schema/src/main/java/io/camunda/webapps/schema/descriptors/template/AuditLogTemplate.java (hunk 4 above)
Comment (koevskinikola) [reply webapps-schema/src/main/java/io/camunda/webapps/schema/descriptors/template/AuditLogTemplate.java:24]: The `ID` is part of the `AbstractExporterEntity` class that is extended by all `webapp-schema` entities. So if I rename it, it will change this field for all Camunda Exporter entities.

@eppdot alternatively, I can add a new `auditLogKey` entity that will duplicate the `ID` value. What do you think?

File: service/src/main/java/io/camunda/service/AuditLogServices.java (hunk 6 above)
Comment (koevskinikola) [reply service/src/main/java/io/camunda/service/AuditLogServices.java:80]: @eppdot do you mean so that we reduce the duplication between the SEARCH and GET endpoints?

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java (hunk 10 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: @eppdot do you mean obtaining the `auditLogKey`?

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java (hunk 9 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: We want to check that the client managed to retrieve at least a single `PROCESS_INSTANCE` audit log from the cluster. And we need to assert that a valid audit log entry is returned.

The test should fail if no audit log entries are returned though, so it's a valid check.

I can refactor it to `assertThat(auditLogItems.items()).hasSizeGreaterThanOrEqualTo(1);`.

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java (hunk 2 above)
Comment (koevskinikola) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:106]: The `toTenantCheckSearchQuery` and `toAuthorizationCheckSearchQuery` methods are related to authorized tenants and authorized permission checks. They allow us to customize the logic of the tenant and authorization check parts of the search queries.

If I refactor this one to be more expressive, the other one should be aligned as well. That would refactor 32 files.

I'll add an explaining comment for it.

Comment (eppdot) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:106]: I think here it would help to explain via comments what this does and why it does it like this, e.g. why are the resourceIds mapped o the `CATEGORY` and also mapped to the `PROCESS_DEFINTION_ID` -> that just doesn't fit my thinking.

File: service/src/main/java/io/camunda/service/AuditLogServices.java (hunk 6 above)
Comment (eppdot) [reply service/src/main/java/io/camunda/service/AuditLogServices.java:80]: isn't the setup of `AuthorizationConditions.anyOf` exactly the same?

File: webapps-schema/src/main/java/io/camunda/webapps/schema/descriptors/template/AuditLogTemplate.java (hunk 4 above)
Comment (eppdot) [reply webapps-schema/src/main/java/io/camunda/webapps/schema/descriptors/template/AuditLogTemplate.java:24]: Hmm, let's keep it simple. Sounds like it would complicate things more 😅

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java (hunk 9 above)
Comment (eppdot) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: I still think that it is not part of this/each specific test case, but of the "setup" of the test case.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java (hunk 10 above)
Comment (eppdot) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: awaiting that all the audit logs have been written, right? This is what we are waiting for, that the setup/preparation completed.

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java (hunk 2 above)
Comment (koevskinikola) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:106]: > why are the resourceIds mapped o the CATEGORY and also mapped to the PROCESS_DEFINTION_ID

This is because we're supporting composite authorizations in the AUDIT_LOG queries. The only indication that this method is related to Authorizations is its name and the input argument, but I guess it's not yet visible that composite authorizations are possible.

I'll make sure this is included in the comment.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java (hunk 12 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: I'll switch the user to the `USER_TASKS` category authorization. It will have the same outcome, but it will be less confusing.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java (hunk 10 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: I see your point. Instead of "awaiting" in every test, we can just do it in the `BeforeAll` and then skip this code in the test cases, as we're operating on the assumption that this was already confirmed in the `BeforeAll` method.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java (hunk 7 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: It seems like JUnit 5 isn't the most flexible when we need to parameterize the whole class. We need to switch to `TestTemplates` and `TemplateProviders`.

For just a single flag, an abstract class would be easier to implement and maintain.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java (hunk 9 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogIT.java]: It's removed, since we already have a similar assertion in the test setup.

File: service/src/main/java/io/camunda/service/AuditLogServices.java (hunk 5 above)
Comment (koevskinikola) [reply service/src/main/java/io/camunda/service/AuditLogServices.java]: That's part of the `AuditLogFilterTransformer`. I've included an extra query for `USER_TASK` audit logs there.

**Comment by koevskinikola** [comment]
@eppdot I applied your feedback. I'm including additional test cases with https://github.com/camunda/camunda/pull/43253

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java (hunk 2 above)
Comment (eppdot) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:106]: ❌ I am still a bit puzzled here 🤔 mostly about the lines below
```
final var categoryQuery = stringTerms(CATEGORY, authorization.resourceIds());
final var processDefinitionQuery =
        stringTerms(PROCESS_DEFINITION_ID, authorization.resourceIds());
```
We are using the SAME `resourceIds` for both subqueries? Couldn't that leak unintended auditlogs?

In one line the `resourceIds` are supposed to be category names, in the other line these are process defintinon ids 🤔 what if I (as user) assign `ADMIN` to my process definition id?

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java (hunk 1 above)
Comment (eppdot) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:90]: ❓ How would this work, if I am not allowed to access these global audit logs? e.g. if I don't have access to the `ADMIN` category?

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AbstractAuditLogClientIT.java [hunk 13]
```diff
@@ -0,0 +1,152 @@
...
+import io.camunda.client.api.search.enums.AuditLogResultEnum;
+import io.camunda.qa.util.auth.Authenticated;
+import io.camunda.zeebe.model.bpmn.Bpmn;
+import io.camunda.zeebe.model.bpmn.BpmnModelInstance;
+import io.camunda.zeebe.protocol.record.intent.ProcessInstanceCreationIntent;
+import io.camunda.zeebe.test.util.record.RecordingExporter;
+import org.awaitility.Awaitility;
+import org.junit.jupiter.api.Test;
+
+abstract class AbstractAuditLogClientIT {
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AbstractAuditLogClientIT.java]: 💭 Maybe a better name could be `BasicAuditLogClientIT` or `Base...` - it feels a bit strange that an `abstract` test has `@Test` case 🤔

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java [hunk 14]
```diff
@@ -0,0 +1,275 @@
...
+import java.util.List;
+import java.util.stream.Collectors;
+import org.awaitility.Awaitility;
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.condition.DisabledIfSystemProperty;
+
+@MultiDbTest
+@DisabledIfSystemProperty(named = "test.integration.camunda.database.type", matches = "AWS_OS")
+public class AuditLogAuthorizationsIT {
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java:50]: 🔧 the setup code is quite similar to the `Abstract...` test, but this one doesn't inherit from it.

Could we prefer composition over inheritance and just move things into a shared helper? Then we could get rid of `abstract` and the inheritances stuff.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AbstractAuditLogClientIT.java [hunk 15]
```diff
@@ -0,0 +1,152 @@
...
+    assertThat(fetchedAuditLog.getCategory()).isEqualTo(AuditLogCategoryEnum.DEPLOYED_RESOURCES);
+    assertThat(fetchedAuditLog.getProcessDefinitionId())
+        .isEqualTo(processInstanceEvent.getBpmnProcessId());
+    assertThat(fetchedAuditLog.getProcessDefinitionKey())
+        .isEqualTo(String.valueOf(processInstanceEvent.getProcessDefinitionKey()));
+    assertThat(fetchedAuditLog.getProcessInstanceKey())
+        .isEqualTo(String.valueOf(processInstanceEvent.getProcessInstanceKey()));
+    assertThat(fetchedAuditLog.getTenantId()).isEqualTo(TENANT_A);
+    assertThat(fetchedAuditLog.getResult()).isEqualTo(AuditLogResultEnum.SUCCESS);
+  }
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AbstractAuditLogClientIT.java]: We test the `creation` and `getByKey` here, why not the search as well? What is our testing concept/purpose/goal here?

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java [hunk 16]
```diff
@@ -0,0 +1,275 @@
...
+                .noneMatch(log -> PROCESS_ID_A.equals(log.getProcessDefinitionId())))
+        .isTrue();
+  }
+
+  @Test
+  void shouldNotSeeDeployedResourceAuditLogsWithOnlyUserTasksCategoryPermission(
+      @Authenticated(USER_C_USERNAME) final CamundaClient userCClient) {
+    // when
+    final var userCAuditLogs =
+        userCClient
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java]: 🔧 how about naming this something like `userTaskUserClient` or so? A/B/C is pretty generic 😄

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java [hunk 17]
```diff
@@ -0,0 +1,275 @@
...
+            .filter(fn -> fn.operationType(AuditLogOperationTypeEnum.CREATE))
+            .send()
+            .join();
+
+    // then
+    // User D should only see audit logs from PROCESS_ID
+    assertThat(userDAuditLogs.items().size()).isOne();
+    assertThat(
+            userDAuditLogs.items().stream()
+                .allMatch(log -> PROCESS_ID.equals(log.getProcessDefinitionId())))
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java]: 💭 probably over engineered, but just wanted to leave a thought here to create a "scenario" record or something like that, that groups the information about who can access what together, e.g. userD is allowed to access `PROCESS_ID` (right now, you need to look up the full setup of the test case)

or be very explicit and every test case can become parameterized, e.g.


```
clientA -> AL1, AL2, AL3
clientB -> AL1
clientC -> AL2
clientD -> AL3
```

or the like

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogGrpcClientIT.java [hunk 18]
```diff
@@ -0,0 +1,37 @@
...
+import io.camunda.client.CamundaClient;
+import io.camunda.qa.util.multidb.MultiDbTest;
+import io.camunda.qa.util.multidb.MultiDbTestApplication;
+import io.camunda.zeebe.qa.util.cluster.TestStandaloneBroker;
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.condition.DisabledIfSystemProperty;
+
+@MultiDbTest
+@DisabledIfSystemProperty(named = "test.integration.camunda.database.type", matches = "AWS_OS")
+public class AuditLogGrpcClientIT extends AbstractAuditLogClientIT {
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogGrpcClientIT.java]: 😂 sorry but this confuses me very much, that this TestClass has "no" test cases, at least on first look. Sure then you can follow the inheritance chain, but still 🤔

File: service/src/main/java/io/camunda/service/AuditLogServices.java [hunk 19]
```diff
@@ -71,9 +73,14 @@ public AuditLogEntity getAuditLog(final String auditLogKey) {
...
                 .withSecurityContext(
                     securityContextProvider.provideSecurityContext(
-                        authentication,
-                        withAuthorization(
-                            AUDIT_LOG_READ_AUTHORIZATION, al -> al.category().name())))
+                        authentication, getRequiredAuthorizations()))
                 .getAuditLog(auditLogKey));
   }
+
+  private AuthorizationCondition getRequiredAuthorizations() {
```
Comment (eppdot) [inline service/src/main/java/io/camunda/service/AuditLogServices.java]: 🔧  can this be static and/or a constant?

**Review by eppdot — DISMISSED** [review]
I have still a few open questions 😄 maybe it makes sense to jump on a quick sync call. Probably, I am just not getting it.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AbstractAuditLogClientIT.java (hunk 13 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AbstractAuditLogClientIT.java]: I'll remove the abstract class and move the helper methods in a `Util` class.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AbstractAuditLogClientIT.java (hunk 15 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AbstractAuditLogClientIT.java]: We test the search API, not `creation`. The test concept for the `AuditLog[Rest\GRPC]ClientIT` tests is to cover the Java Client and REST API endpoints.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogGrpcClientIT.java (hunk 18 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogGrpcClientIT.java]: I've cleared this up. There's no abstract class anymore.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java (hunk 17 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java]: Right now, the `MultiDbTest` JUnit 5 extension takes care of creating the users, injecting the clients, and auto-closing the clients once the test is done.

If we want to parameterize the user permissions, we would need to add a lot more boilerplate code that would create users and clients manually within each test case. We would also need to ensure that the clients are closed after each test.

I'll see if it makes sense to parameterize some of the tests, and manually create clients from the defined users there. However, I would leave the user creation to be part of the `MultiDbTest` code.

**Comment by koevskinikola** [comment]
@eppdot you feedback is applied now. Can you have another look?

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java (hunk 2 above)
Comment (koevskinikola) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:106]: The authorization query creation is fixed now.

File: qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java (hunk 17 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/auditlog/AuditLogAuthorizationsIT.java]: It didn't make sense to parameterize any of the tests. It would have created more work and boilerplate code that is already reduced by the JUnit 5 extension.

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java (hunk 1 above)
Comment (koevskinikola) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/AuditLogFilterTransformer.java:90]: I refactored the `AuditLogFilterTransformer` to produce queries depending on the authorization resource type and permissions. It won't create all of the queries at once, but depending on what authorizations are provided.

**Review by konstantinos-mylosis — APPROVED** [review]
Ran through comments
Already reviewed
Also LGTM
Nice!
