### PR TITLE
Fix flaky IncidentQueryTest

### LINKED ISSUE #24271: IncidentQueryTest is flaky
**Summary**

- How often does the test fail? once [here](https://github.com/camunda/camunda/actions/runs/11614274002/attempts/1?pr=24268) so far.
- Does it block your work? 
- Do we suspect that it is a real failure? no

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
❌ shouldFilterByTreePath (Flaky Test): io.camunda.it.client.IncidentQueryTest

org.opentest4j.AssertionFailedError: 

expected: null
 but was: "PI_2251799813685271/FN_taskAIncident/FNI_2251799813685275"
	at io.camunda.it.client.IncidentQueryTest.shouldFilterByTreePath(IncidentQueryTest.java:257)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
<pre>
❌   shouldGetIncidentByKey (Flaky Test): io.camunda.it.client.IncidentQueryTest

org.opentest4j.AssertionFailedError: 
expected: io.camunda.zeebe.client.impl.search.response.IncidentImpl@ca4834ff
but was: io.camunda.zeebe.client.impl.search.response.IncidentImpl@e51e266e
        at io.camunda.it.client.IncidentQueryTest.shouldGetIncidentByKey(IncidentQueryTest.java:86)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
</details>

**Hypotheses**

**Logs**

[LOGS](https://drive.google.com/file/d/1vU0Rs3SG2s_iCATwb2LhenwZevDRi6l_/view?usp=drive_link)

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

The IncidentQueryTest should test the minimal required data to avoid flakiness. It's important that the incident key matches. All other attributes of the incident are not relevant for this test case and only increase potential flakiness if we verify them, too.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #24271

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/it/client/IncidentQueryTest.java [hunk 1]
```diff
@@ -82,7 +82,7 @@ void shouldGetIncidentByKey() {
 
     // then
     assertThat(result).isNotNull();
-    assertThat(result).isEqualTo(incident);
+    assertThat(result.getIncidentKey()).isEqualTo(incidentKey);
```
Comment (houssain-barouni) [inline qa/integration-tests/src/test/java/io/camunda/it/client/IncidentQueryTest.java:85]: @tmetzke any idea which field from the incident does not match? unfortunately `toString()` is not implemented in IncidentImpl, so we cannot find out from the CI logs
it is still strange that the entity returned by the search does not match the one returned by getByKey 🤔

Comment (tmetzke) [reply qa/integration-tests/src/test/java/io/camunda/it/client/IncidentQueryTest.java:85]: I don't know yet, I had it running on my machine for ~800 times and it never failed. I tried multiple setups, ES and OS, running all tests in the class, running the test method only - nothing popped up.

My goal is now: unflake this for now with this PR and create another PR as a follow-up that reverts this and adds `toString` to the `IncidentImpl` so we can hopefully see what is different.

Comment (tmetzke) [reply qa/integration-tests/src/test/java/io/camunda/it/client/IncidentQueryTest.java:85]: Created https://github.com/camunda/camunda/pull/28552 for this

**Review by houssain-barouni — APPROVED** [review]
