### PR TITLE
fix: prevent showing forbidden page while loading identity

### LINKED ISSUE #29848: Forbidden page appears briefly before user endpoint loads
#### Description
When accessing the application, the forbidden page appears momentarily before the user endpoint is fully loaded. This creates a poor user experience and may confuse users.

#### Steps to Reproduce
1. Open the application.
2. Navigate to a protected page requiring authentication.
3. Observe that the forbidden page briefly appears before the correct user data loads.

#### Expected Behavior
- The user should not see the forbidden page if they have the necessary permissions.
- The application should wait for the user endpoint response before rendering any unauthorized state.

#### Actual Behavior
- The forbidden page flashes on the screen before the user data is loaded.
- After a second, the correct content loads.

### PR DESCRIPTION
**Pull request by OmranAbazid**
## Description

The forbidden page appear due to two issues: 
1. Loading the current user to check if it is forbidden or not takes a bit of time and during that time, we do not display any loading state. So the forbidden page appears briefly until the user loads.

2. When redirecting to the /login page after receiving a 401 response, we issue a hard refresh, which takes a bit of time as well. During this time, the user info is not available, causing the forbidden page to appear.

I fixed the first issue by adding a loading state and second one by doing the redirection to `/login` in the front-end without a hard refresh

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #29848

### CODE REVIEW

File: identity/client/src/utility/api/request.ts [hunk 1]
```diff
@@ -99,9 +115,11 @@ const apiRequest: <R, P>(
         redirect: "manual",
       },
     );
-    if (response.status === 401) {
-      redirectToLogin();
```
Comment (OmranAbazid) [inline identity/client/src/utility/api/request.ts:103]: When logging out from identity, we do the following
1. Hard refresh the page
2. wait for the first 401 response
3. Load /login using a hard refresh as well

This causes the page to refresh twice.
I added a handler utility so that we can listen to the 401 instead a react component and do a FE redirect instead of doing it with a hard refresh.

**Review by vitorwtavares — APPROVED** [review]
