### PR TITLE
fix(broker-core): don't schedule task for update position if in actor

### LINKED ISSUE #1334: Null pointer exception if update last position in exporter close call
If an exporter flushes in the `close` method and updates the last position an new actor task is scheduled in the `ExpoterStreamProcessor`.

https://github.com/zeebe-io/zeebe/blob/63a17b4d012638eecdad14a7ade1d9fa98c760f0/broker-core/src/main/java/io/zeebe/broker/exporter/stream/ExporterStreamProcessor.java#L172-L178

But before this can be executed the state database is already closed, so a NPE is thrown.

https://github.com/zeebe-io/zeebe/blob/63a17b4d012638eecdad14a7ade1d9fa98c760f0/broker-core/src/main/java/io/zeebe/broker/exporter/stream/ExporterStreamProcessor.java#L140-L150

### PR DESCRIPTION
**Pull request by miguelpires**
Avoid scheduling the update of the last record position when the call is made in the actor.
Also deletes the RocksDB folder (which wasn't happening on Windows)

closes #1334

### CODE REVIEW

File: logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java [hunk 1]
```diff
@@ -442,8 +443,13 @@ protected void onActorClosing() {
     metrics.close();
 
     if (!isFailed()) {
-      createSnapshot();
       streamProcessor.onClose();
+      createSnapshot();
+
+      final StateController stateController = streamProcessor.getStateController();
```
Comment (Zelldon) [inline logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java]: I think it makes sense that we decouple this and close it after the stream processor.

File: logstreams/src/main/java/io/zeebe/logstreams/state/StateController.java [hunk 2]
```diff
@@ -270,6 +270,11 @@ public void delete(final File dbDirectory) throws Exception {
 
     try (Options options = createOptions()) {
       RocksDB.destroyDB(dbDirectory.toString(), options);
+
+      // on Windows, destroyDB does not remove the directory but simply clears the contents
+      if (dbDirectory.exists()) {
+        dbDirectory.delete();
```
Comment (Zelldon) [inline logstreams/src/main/java/io/zeebe/logstreams/state/StateController.java]: This will only work if the folders are empty right?

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
I'm unsure if this is good to have this constraint that this only works if it is on the same actor thread.

I would like to propose that we use simply `actor.run` instead of the conditional logic in the update last position method. Furthermore I think it makes sense that we submit the state.close as extra job, then we have no problems with different threads, since it ends up in the same job queue.

Does this makes sense to you guys?

File: broker-core/src/main/java/io/zeebe/broker/exporter/stream/ExporterStreamProcessor.java [hunk 3]
```diff
@@ -131,8 +138,6 @@ public void onClose() {
         container.context.getLogger().error("Error on close", e);
       }
     }
-
-    state.close();
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply broker-core/src/main/java/io/zeebe/broker/exporter/stream/ExporterStreamProcessor.java]: That should work if there's a blocking equivalent (i.e. we don't want to leave the closing phase until the state is closed). I think closing the state should probably be refactored to the stream processor controller anyway since all processors use one and need to do this.

[the remark this answers is not in the document]
Comment (Zelldon) [reply broker-core/src/main/java/io/zeebe/broker/exporter/stream/ExporterStreamProcessor.java]: > but if an exception would be thrown in state.close(), the actor could still close but the state wouldn't be right? Then runUntilDone() might be better? Though we don't handle errors at all right now, and retrying might not be particularly useful anyway...

Yes could be true. 

> Though we don't handle errors at all right now, and retrying might not be particularly useful anyway... man_shrugging

I totally agree :D How to fix this then :sweat_smile: 

> I anyway think closing the state should probably be refactored to the stream processor controller anyway since all processors use one and need to do this, though I guess it doesn't have to be in this issue in particular.

Yes for sure. I think is ok that we have this in this issue is not a big change :)

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 16d0b15137e2b4f04681c1dd0e51386c440e0441
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

File: logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java [hunk 4]
```diff
@@ -443,13 +443,19 @@ protected void onActorClosing() {
     metrics.close();
 
     if (!isFailed()) {
-      streamProcessor.onClose();
-      createSnapshot();
+      // since actor.run() makes the task the next executed job, we first schedule the state closing
```
Comment (Zelldon) [inline logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java]: Maybe it is more intuitive if we use the actor lifecycle methods? Like onActorCloseRequested you do your streamProcessor.onClose and onClosing you do your close/teardown work or event do this in onActorClosed.

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Sorry for the late response. Looks better I have two small requests

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 16d0b15137e2b4f04681c1dd0e51386c440e0441
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 07f857d16ee68097445d5da0bfc082f13fb59968
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 16d0b15137e2b4f04681c1dd0e51386c440e0441
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 07f857d16ee68097445d5da0bfc082f13fb59968
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: cf354c1113ff6ca29ea3e6b8215a104e025aabef
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by MiguelPires** [comment]
I refactored that code to be less counter-intuitive

**Review by ChrisKujawa — APPROVED** [review]
