### PR TITLE
Replicate snapshots faster

### LINKED ISSUE #5135: Restart takes too long or never completes when snapshot contains many files
**Describe the bug**

Snapshot replication initiated via raft sends the chunks sequentially. So if the snapshot has many chunks it takes too long to replicate. Since this often happens during restart, a follower takes several minutes to catch up its state. If this takes longer than the snapshot period, the leader might start a new replication. As a result the node restart never completes.  
Related #4887

To fix this we should improve the snapshot replication logic in raft to sends more chunks in parallel.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

FileBasedSnapshotChunkReader constructor read all files to calculate checksum. When we create a new instance of the reader for each install request, it affects the overall snapshot replication duration. The performance impact is visible when the snapshot contains more than 1000 files. So instead of creating a new reader each time, we create the reader once and iterate over the chunks to build each install request.

## Related issues

closes #5135 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [x] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

**Comment by deepthidevaki** [comment]
#### Result from benchmark
image

**Comment by deepthidevaki** [comment]
@Zelldon This PR contains only the fix with the readers. It is still sending the chunks one by one. Sending chunks parallely with out this fix did not help. I will evaluate if sending them parallely has any significant impact after this fix. I will create a different PR for parallel sending it is beneficial.

File: atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java [hunk 1]
```diff
@@ -363,6 +342,28 @@ public void close() {
...
+        return;
+      }
+
+      final var persistedSnapshot = optSnapshot.get();
+      log.debug(
+          "Replicating snapshot {} to {}",
+          persistedSnapshot.getIndex(),
+          member.getMember().memberId());
+      buildInstallRequest(member, persistedSnapshot)
+          .ifPresent(installRequest -> sendInstallRequest(member, installRequest));
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java:361]: What happens when we failed to open the reader and return here empty? No install request is send. Is this an issue?

File: atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java [hunk 2]
```diff
@@ -170,6 +170,28 @@ public void shouldReplicateSnapshotOnJoin() throws Exception {
...
+    // when
+    raftRule.joinCluster(follower);
+
+    // then
+    assertThat(raftRule.allNodesHaveSnapshotWithIndex(snapshotIndex)).isTrue();
+    final var snapshot = raftRule.getSnapshotOnNode(follower);
+
+    assertThat(snapshot.getIndex()).isEqualTo(leaderSnapshot.getIndex()).isEqualTo(snapshotIndex);
+    assertThat(snapshot.getTerm()).isEqualTo(snapshot.getTerm());
+    assertThat(snapshot.getPath().toFile().list())
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java:191]: Could be flaky, since ordering is not guaranteed right?

Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java:191]: First I thought hm this should also worked before right? So what is the matter of this test, the I tried it without your fix and it toooook soo long, wow didn't expected that :D 

Thanks for fixing that, awesome.

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Awesome nice catch @deepthidevaki thanks for fixing it. I had some smaller comments.

File: atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java (hunk 1 above)
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java:361]: Ya. Then no install request is send. But will be retried in the next heartbeat/appendEntry turn. In worst case, it will be retried for ever if there is something seriously wrong with the snapshot. The other option is to throw an exception, but this will cause the leader to fail and go to INACTIVE phase.

File: atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java (hunk 2 above)
Comment (deepthidevaki) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java:191]: Actually, this test was added to test parallel/pipelined sending of snapshot chunks. But this PR doesnot have it. I didn't notice performance difference :smile: Should I keep/remove this test?

Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverTest.java:191]: Lets keep it. It fails, because of timeouts, if I we create always the snapshot chunk reader :) I tried that :D

**Comment by deepthidevaki** [comment]
@Zelldon I have updated the test assert to be not flaky.

**Review by ChrisKujawa — APPROVED** [review]
@deepthidevaki thanks :+1: 

I think we should backport this. Could you please create a PR for 0.24?

**Comment by deepthidevaki** [comment]
I did not backport this to 0.23 yet. The code has changed a lot. But I think the root cause is the same. So a similar fix should work. @npepinpe Should we fix it on 0.23 as well?

**Comment by npepinpe** [comment]
As we're not sure if it would be a lot of work, let's timebox it, say 2h - after that you should have some idea if you need a bit of time more or if it's not worth it
