### PR TITLE
fix: archiver blocking flag being reapplied

### LINKED ISSUE #39187: Archiver blocked flag is reapplied on restart
The Archiver flag is being reapplied on restart of 8.8 deployments, blocking the archiving on PI related data.

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

- Utilize the presence of old `tasklist-task-8.5.0_` indices to determine whether this is a greenfield or a brownfield installation
- Fixed some minor comment issues
- Added tests to rerun the Schema Manager and verify the flag is not being reset

> It's not guaranteed that if the check introduced is true, that it is a Greenfield installation since a previous installation could have Tasklist disabled. It's enough for checking regarding flagging the archiver

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #39187

### CODE REVIEW

File: schema-manager/src/main/java/io/camunda/search/schema/SchemaManager.java
Comment (houssain-barouni) [inline schema-manager/src/main/java/io/camunda/search/schema/SchemaManager.java]:
```suggestion
  private boolean blockedArchiverMetaIsMissing(final String tasklistImportPositionIndex) {
```

**Review by houssain-barouni — APPROVED** [review]
LGTM! can you just rename a variable to remove the confusion
I see there is a failing test, but I think you need to change the test pre-conditions

**Comment by panagiotisgts** [comment]
@houssain-barouni This was a flake, I'm rerunning the job, as locally it passes and I'm investigating in the meantime. But not sure why it would flake since at least one of the instances should find missing descriptors. Locally it does not fail though

File: schema-manager/src/main/java/io/camunda/search/schema/utils/TasklistLegacyTaskTemplate.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+  @Override
+  public String getVersion() {
+    return "8.5.0";
+  }
+
+  @Override
+  public String getSchemaClasspathFilename() {
+    return super.getSchemaClasspathFilename();
+  }
```
Comment (houssain-barouni) [inline schema-manager/src/main/java/io/camunda/search/schema/utils/TasklistLegacyTaskTemplate.java]: Is this needed?

**Review by houssain-barouni — APPROVED** [review]
