### PR TITLE
Coordinate backup status query in gateway

### LINKED ISSUE #10288: Coordinate backup status query in gateway
Implement a request handler in Gateway to coordinate backup status query. This request handler should send the qeury to all partitions and collect the responses. The status of the backup should be deduced from the status of all partitions. If at least one partition failed then the backup is failed. 

The actuator should be able to delegate the request to this handler and collect the responses. All coordination logic must be in this request handler.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

* BackupRequestHandler coordinates status query. It sends the requests to all partitions and collect the responses. The aggregate status of the backup is calculated by combining status of backups of all partition. The status is completed only if all partitions have completed backup.
* Returned `BackupStatus` consists of an aggregate status and the status of each partition. So if backup is not completed, we can see which one is not completed and the reasons for it.

## Related issues

closes #10288

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java [hunk 1]
```diff
@@ -25,40 +31,144 @@ public BackupRequestHandler(final BrokerClient brokerClient) {
...
+
+    return CompletableFuture.allOf(statusesReceived.toArray(CompletableFuture[]::new))
+        .thenApply(ignore -> aggregatePartitionStatus(backupId, statusesReceived))
+        .exceptionallyCompose(
+            error ->
+                CompletableFuture.failedFuture(
+                    operationFailed("query", backupId, error.getCause())));
+  }
+
+  private Either<Throwable, Boolean> checkTopologyComplete() {
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:76]: :wrench: I would recommend returning a `CompletionStage<BrokerClusterState>` here instead of `Either`. We don't really care about the return value at the moment, but what we want is "if the topology is complete, use it immediately after; if it's not, fail". As our public API relies on futures, why not simply already return a failed or completed future, and go from there? Even if the operation is not explicitly asynchronous here, it fits better with our asynchronous API, and who knows if one day it might not become asynchronous.

e.g.

```java
  @Override
  public CompletionStage<Long> takeBackup(final long backupId) {
    return checkTopologyComplete()
        .thenApply(topology -> broadcastBackupRequest(backupId, topology))
        .thenApply(ignore -> backupId)
        .exceptionallyCompose(
            error ->
                CompletableFuture.failedFuture(
                    operationFailed("take", backupId, error.getCause())));
  }

  private CompletionStage<BrokerClusterState> checkTopologyComplete() {
    final BrokerClusterState topology = topologyManager.getTopology();
    if (topology == null) {
      return CompletableFuture.failedFuture(new NoTopologyAvailableException());
    }

    final int expectedPartitionCount = topology.getPartitionsCount();
    final int knownPartitions = topology.getPartitions().size();
    if (expectedPartitionCount != knownPartitions) {
      return CompletableFuture.failedFuture(
          new IncompleteTopologyException(
              "Expected to send request to all %d partitions, but found only %d partitions in topology."
                  .formatted(expectedPartitionCount, knownPartitions)));
    }

    return CompletableFuture.completedFuture(topology);
  }

  private CompletableFuture<?>[] broadcastBackupRequest(final long backupId,
      final BrokerClusterState topology) {
    return topology.getPartitions().stream()
        .map(partitionId -> getBackupRequestForPartition(backupId, partitionId))
        .map(brokerClient::sendRequestWithRetry)
        .toArray(CompletableFuture[]::new);
  }
```

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupApi.java [hunk 2]
```diff
@@ -20,4 +20,13 @@ public interface BackupApi {
...
   CompletableFuture<Long> takeBackup(long backupId);
+
+  /**
+   * Returns the status of the backup. The future fails if the request was not processed by at least
+   * one partition.
+   *
+   * @param backupId
+   * @return the status of the backup
+   */
+  CompletableFuture<BackupStatus> getStatus(long backupId);
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupApi.java:31]: :wrench: I would recommend using `CompletionStage` wherever we want to pass an immutable future. Sorry I didn't mention it last time, but returning a `CompletableFuture` for me hints that a consumer may complete the future, which I don't think is our intended usage.

You can always switch from a CompletionStage to a CompletableFuture of course, e.g. `CompletionStage#toCompletableFuture`, but here the gain is more in semantics (strongly hinting at how the method should be used) than anything.

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java [hunk 3]
```diff
@@ -25,40 +31,144 @@ public BackupRequestHandler(final BrokerClient brokerClient) {
...
+              "Expected to send request to all %d partitions, but found only %d partitions in topology."
+                  .formatted(expectedPartitionCount, knownPartitions)));
+    }
+
+    return Either.right(true);
+  }
+
+  private static BackupOperationFailedException operationFailed(
+      final String operation, final long backupId, final Throwable error) {
+    return new BackupOperationFailedException(operation, backupId, error);
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:96]: :question: I'm not sure I get why we abstracted a single constructor call away into a method with the same arguments/no additional logic. Is this a leftover from previous approaches? Or just to ensure that we always fail with the same exception (in which case, it could still happen that someone forgets to call `operationFailed` anyway)?

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java [hunk 4]
```diff
@@ -25,40 +31,144 @@ public BackupRequestHandler(final BrokerClient brokerClient) {
...
+        .map(
+            p -> {
+              final var reason = p.failureReason().orElse("Unknown reason");
+              return "Backup on partition %d failed due to %s.".formatted(p.partitionId(), reason);
+            })
+        .toList()
+        .toString();
+  }
+
+  private static Optional<BackupStatusCode> getAggregatedStatus(
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:136]: :question: It's unclear to me why both this and `combine` are static, as they're only used in this class, in an instance context. Is this a performance optimization?

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java [hunk 5]
```diff
@@ -25,40 +31,144 @@ public BackupRequestHandler(final BrokerClient brokerClient) {
...
+
+    final var partitionStatuses =
+        completedFutures.stream()
+            .map(response -> response.join().getResponse())
+            .map(PartitionBackupStatus::from)
+            .toList();
+
+    final var combinedStatus = getAggregatedStatus(partitionStatuses);
+
+    if (combinedStatus.isEmpty()) {
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:111]: :question: If I understood correctly, this can only happen if we did not send any requests, correct? If that's the case, the error message is somewhat obscure. Is there another case where this could be empty but we did send some requests? Or is this for future proofing?

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/PartitionBackupStatus.java [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+ * Licensed under the Zeebe Community License 1.1. You may not use this file
+ * except in compliance with the Zeebe Community License 1.1.
+ */
+package io.camunda.zeebe.gateway.admin.backup;
+
+import io.camunda.zeebe.protocol.impl.encoding.BackupStatusResponse;
+import io.camunda.zeebe.protocol.management.BackupStatusCode;
+import java.util.Optional;
+
+public record PartitionBackupStatus(
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/PartitionBackupStatus.java:14]: :x: Please comment if this is truly public; but looking at its usages, it seems to be a package private thing, so we can also just downgrade the visibility (here and for its methods).

**Review by npepinpe — CHANGES_REQUESTED** [review]
:+1: 

- :wrench: I would recommend paying more attention to errors as they are part of our API, and as backup is a feature ripe for automation, I can imagine more than one user will want to parse our errors. At the moment it seems our errors are more or less unformatted. I think this is maybe OK for the first iteration, but it would be best to look into something like `application/problem+json` as a solution in the future as a general payload format for errors, and then make sure our error messages are actionable (as much as possible).

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java [hunk 7]
```diff
@@ -25,40 +31,144 @@ public BackupRequestHandler(final BrokerClient brokerClient) {
...
+  private String collectFailureReason(final List<PartitionBackupStatus> partitionStatuses) {
+    return partitionStatuses.stream()
+        .filter(p -> p.status() == BackupStatusCode.FAILED)
+        .map(
+            p -> {
+              final var reason = p.failureReason().orElse("Unknown reason");
+              return "Backup on partition %d failed due to %s.".formatted(p.partitionId(), reason);
+            })
+        .toList()
+        .toString();
```
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:133]: The intent of this field is for investigation or debugging. I don't see a use for it in automation yet.

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java (hunk 5 above)
Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:111]: This would only happen if no response list is empty. This should never happen because if there are no partitions in the topology, it should fail before reaching this step. This check is added just as a safety condition.

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java (hunk 4 above)
Comment (npepinpe) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:136]: No need to apologize, was just wondering :smile:

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupApi.java (hunk 2 above)
Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupApi.java:31]: :+1: Make sense. I will update both APIs to use `CompletionStage`

**Comment by deepthidevaki** [comment]
>  it would be best to look into something like application/problem+json as a solution in the future as a general payload format for errors, and then make sure our error messages are actionable (as much as possible).

This is a nice suggestion. As you said we could look into it in the next iteration.

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java (hunk 5 above)
Comment (npepinpe) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:100]: :x: Can we reflect that in the error message?

```java
throw new IncompleteTopologyException("Backup status cannot be calculated from %s, as the topology is incomplete".formatted(partitionStatuses))
```

I think it will help us faster understand what's going on in case anything goes wrong.

**Review by npepinpe — APPROVED** [review]
One small thing, but nothing worth another review :+1:

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java (hunk 5 above)
Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java]: :+1: I have updated the error message. But kept the exception as `IllegalStateException` because this should never happen.

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors merge
