### PR TITLE
fix: make RoutingState backward compatible between 8.8 and 8.7

### LINKED ISSUE #38140: Rolling update test is failing when partition scaling is enabled
### 

### 

### 

### 

### Description

RollingUpdateTest on stable 8.8 branch is failing when trying to the merge the PR that enables partition scaling by default. 

https://github.com/camunda/camunda/actions/runs/17648076698?pr=37988 

```
[2025-09-15 07:33:21.517] [zb-actors-1] [{actor-name=Startup, actor-scheduler=Broker-1}] WARN 
	io.camunda.zeebe.broker.system - Aborting startup process due to exception during step Cluster Topology Manager
io.camunda.zeebe.dynamic.config.serializer.DecodingFailed: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at io.camunda.zeebe.dynamic.config.serializer.ProtoBufSerializer.decodeClusterTopology(ProtoBufSerializer.java:133)
	at io.camunda.zeebe.dynamic.config.PersistedClusterConfiguration.readFromFile(PersistedClusterConfiguration.java:107)
	at io.camunda.zeebe.dynamic.config.PersistedClusterConfiguration.ofFile(PersistedClusterConfiguration.java:60)
	at io.camunda.zeebe.dynamic.config.ClusterConfigurationManagerService.<init>(ClusterConfigurationManagerService.java:87)
	at io.camunda.zeebe.broker.partitioning.topology.DynamicClusterConfigurationService.getClusterTopologyManagerService(DynamicClusterConfigurationService.java:169)
	at io.camunda.zeebe.broker.partitioning.topology.DynamicClusterConfigurationService.start(DynamicClusterConfigurationService.java:66)
	at io.camunda.zeebe.broker.bootstrap.ClusterConfigurationManagerStep.startup(ClusterConfigurationManagerStep.java:41)
	at io.camunda.zeebe.broker.bootstrap.ClusterConfigurationManagerStep.startup(ClusterConfigurationManagerStep.java:19)
	at io.camunda.zeebe.broker.bootstrap.BrokerStepMetricDecorator.callDelegateAndUpdateTimer(BrokerStepMetricDecorator.java:62)
	at io.camunda.zeebe.broker.bootstrap.BrokerStepMetricDecorator.startup(BrokerStepMetricDecorator.java:44)
	at io.camunda.zeebe.broker.bootstrap.BrokerStepMetricDecorator.startup(BrokerStepMetricDecorator.java:25)
	at io.camunda.zeebe.scheduler.startup.StartupProcess.proceedWithStartupSynchronized(StartupProcess.java:162)
	at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:170)
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28)
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86)
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:43)
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127)
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104)
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:110)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readTag(CodedInputStream.java:649)
	at io.camunda.zeebe.dynamic.config.protocol.Topology$RequestHandling$Builder.mergeFrom(Topology.java:5007)
	at io.camunda.zeebe.dynamic.config.protocol.Topology$RequestHandling$Builder.mergeFrom(Topology.java:4873)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:868)
	at io.camunda.zeebe.dynamic.config.protocol.Topology$RoutingState$Builder.mergeFrom(Topology.java:2902)
	at io.camunda.zeebe.dynamic.config.protocol.Topology$RoutingState$Builder.mergeFrom(Topology.java:2748)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:868)
	at io.camunda.zeebe.dynamic.config.protocol.Topology$ClusterTopology$Builder.mergeFrom(Topology.java:1790)
	at io.camunda.zeebe.dynamic.config.protocol.Topology$ClusterTopology$1.parsePartialFrom(Topology.java:2385)
	at io.camunda.zeebe.dynamic.config.protocol.Topology$ClusterTopology$1.parsePartialFrom(Topology.java:2377)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:111)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:126)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:25)
	at io.camunda.zeebe.dynamic.config.protocol.Topology$ClusterTopology.parseFrom(Topology.java:1477)
	at io.camunda.zeebe.dynamic.config.serializer.ProtoBufSerializer.decodeClusterTopology(ProtoBufSerializer.java:128)
	... 19 more
```

### Steps to reproduce

Run RollingUpdateTest `shouldPerformRollingUpdate` with partition scaling enabled  by setting the env var `ZEEBE_BROKER_EXPERIMENTAL_FEATURES_ENABLEPARTITIONSCALING`

### Current behavior

.

### Expected behavior

.

### Workaround

Most likely shutting down the whole cluster and restarting it on the new version works. This hypothesis is based on the fact that other update tests which are not rolling passes.

### Environment

SM

### Version

- Component Version: Update from 8.7 to 8.8

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by entangled90**
## Description
BREAKING CHANGE:
This PR reverts a  **BREAKING CHANGE** introduced in 8.8.
In 8.8 an incompatibility between RoutingState has been introduced by reusing the field with id 2 for a new field, therefore introduce an incompatibility between the two formats.

A fallback to the previous field has been introduced to be able to deserialize correctly messages generated by 8.7. 

Some property tests reported errors, mostly related to generating `RequestHandling` classes with `basePartitionCount=-1` which is not a valid value. However, the validation for that field was missing.

I also noticed that the value `basePartitionCount = -1` should not have been "generated" at all, since `Arbitrary` for `RequestHandling.AllPartitions` should have produced only positive values. 
By making the `Arbitrary<RequestHandling>` explicitly refer to our custom instances, the error vanished.

## Checklist

- [X] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #38140

### CODE REVIEW

**Comment by deepthidevaki** [comment]
@entangled90 It seems it breaks another update test.

**Comment by entangled90** [comment]
When trying locally I don't see the same error, but I do get an error for ad-hoc-subprocesses:
```
io.camunda.client.api.command.ClientStatusException: Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'process.bpmn': - Element: ahsp
    - ERROR: Elements of type 'AdHocSubProcess' are currently not supported. Please refer to the documentation for a list of supported elements: https://docs.camunda.io/docs/components/modeler/bpmn/bpmn-coverage/

```
Let's see if it fails with the same error as before in the CI

**Comment by entangled90** [comment]
Interesting error from the failing OldGatewayTest failed CI RUN:
```
io.camunda.zeebe.dynamic.config.serializer.DecodingFailed: Cluster topology could not be deserialized from gossiped state: clusterTopology {
  version: 1
  members {
    key: "0"
    value {
      lastUpdated {
        seconds: -31557014167219200
      }
      state: ACTIVE
      partitions {
        key: 1
        value {
          state: ACTIVE
          priority: 1
          config {
            exporting {
              exporters {
                key: "DebugLogExporter"
                value {
                  state: ENABLED
                }
              }
            }
          }
        }
      }
      partitions {
        key: 2
        value {
          state: ACTIVE
          priority: 1
          config {
            exporting {
              exporters {
                key: "DebugLogExporter"
                value {
                  state: ENABLED
                }
              }
            }
          }
        }
      }
    }
  }
  routingState {
    version: 1
    messageCorrelation {
      hashMod {
        partitionCount: 2
      }
    }
  }
}
	at io.camunda.zeebe.dynamic.config.serializer.ProtoBufSerializer.decode(ProtoBufSerializer.java:111)
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageBiConsumer.accept(DefaultClusterCommunicationService.java:328)
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageBiConsumer.accept(DefaultClusterCommunicationService.java:313)
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$6(NettyMessagingService.java:319)
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:84)
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:43)
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127)
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104)
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224)
Caused by: java.lang.IllegalArgumentException: Unknown request handling type
	at io.camunda.zeebe.dynamic.config.serializer.ProtoBufSerializer.decodeRequestHandling(ProtoBufSerializer.java:561)
	at io.camunda.zeebe.dynamic.config.serializer.ProtoBufSerializer.decodeRoutingState(ProtoBufSerializer.java:546)
	at io.camunda.zeebe.dynamic.config.serializer.ProtoBufSerializer.decodeClusterTopology(ProtoBufSerializer.java:153)
	at io.camunda.zeebe.dynamic.config.serializer.ProtoBufSerializer.decode(ProtoBufSerializer.java:107)
	... 9 more
```

This log should be produced by 8.8+ version (as `RequestHandling` does not exists in 8.7). 
The flag is set in 8.7, which initializes the `RoutingState`, however, we validate that `RequestHandling` is initialized in some way:

```java

  private RequestHandling decodeRequestHandling(final Topology.RequestHandling requestHandling) {
    return switch (requestHandling.getStrategyCase()) {
      case ALLPARTITIONS ->
          new RequestHandling.AllPartitions(requestHandling.getAllPartitions().getPartitionCount());
      case ACTIVEPARTITIONS ->
          new RequestHandling.ActivePartitions(
              requestHandling.getActivePartitions().getBasePartitionCount(),
              new TreeSet<>(
                  requestHandling.getActivePartitions().getAdditionalActivePartitionsList()),
              new TreeSet<>(requestHandling.getActivePartitions().getInactivePartitionsList()));
      case STRATEGY_NOT_SET -> throw new IllegalArgumentException("Unknown request handling type");
    };
  
```

File: zeebe/dynamic-config/src/main/java/io/camunda/zeebe/dynamic/config/state/RoutingState.java [hunk 1]
```diff
@@ -66,6 +67,13 @@ public static RoutingState initializeWithPartitionCount(final int partitionCount
         1, new AllPartitions(partitionCount), new MessageCorrelation.HashMod(partitionCount));
   }
 
+  private static void validatePartitionCount(final int partitionCount) {
+    if (partitionCount < 1) {
+      throw new IllegalArgumentException(
+          "Partition count must be greater than %d".formatted(Protocol.START_PARTITION_ID));
```
Comment (deepthidevaki) [inline zeebe/dynamic-config/src/main/java/io/camunda/zeebe/dynamic/config/state/RoutingState.java]: It is enough to say "Partition count must be greater than or equal to 1". No need to use the START_PARTITION_ID.

**Review by deepthidevaki — APPROVED** [review]
Thanks. Did you already test this on rolling update from 8.7 to 8.8 with scaling enabled?

**Comment by entangled90** [comment]
Yes, I tested it just now on top of #37988

**Comment by entangled90** [comment]
Operate backup/restore failed, retrying
