### PR TITLE
Authentication endpoint should return `username`, but not `usedId` and `userKey`

### LINKED ISSUE #35378: V2 Authentication Endpoint returns userid and userkey instead of username
### 

### 

### 

### 

### Description

[The authentication endpoint](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/get-authentication/) returns an object with userId, userKey, but it should only return the username.

### Steps to reproduce

Use the https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/get-authentication/ endpoint and check the response

### Current behavior

[The authentication endpoint](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/get-authentication/) returns an object with userId, userKey, 

### Expected behavior

but it should only return the username.

### Environment

SaaS & SM

### Version

8.8-alpha6

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by ana-vinogradova-camunda**
## Description

[The authentication endpoint](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/get-authentication/) returns an object with `userId`, `userKey`, but it should only return the `username`.

Also, `BasicCamundaUserService` should return `username` in `username` field, currently it returns display name.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #35378

### CODE REVIEW

File: tasklist/client/e2e/mocks/v2/processes.ts [hunk 1]
```diff
@@ -15,13 +15,15 @@ const mockProcesses = [
     processDefinitionId: 'multipleVersions',
     tenantId: '<default>',
     processDefinitionKey: '0',
+    hasStartForm: false,
```
Comment (pedesen) [inline tasklist/client/e2e/mocks/v2/processes.ts:18]: Was this change intentional? Looks unrelated to authentication.

**Review by pedesen — COMMENTED** [review]
Frontend part (Tasklist/Operate) looks good to me!

**Review by pedesen — APPROVED** [review]

File: tasklist/client/e2e/mocks/v2/processes.ts (hunk 1 above)
Comment (vsgoulart) [reply tasklist/client/e2e/mocks/v2/processes.ts:18]: Yes, the typedefs were corrected in a previous version which wasn't bumped yet on Tasklist

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml [hunk 2]
```diff
@@ -7647,6 +7647,9 @@ components:
         displayName:
           description: The display name of the user.
           type: string
+        email:
```
Comment (maryarm) [inline zeebe/gateway-protocol/src/main/proto/rest-api.yaml:7650]: As I see in the rest api, the return type of `authentication/me` endpoint is `CamundaUserResult`, but in `AuthenticationController#getCurrentUser` the return type is `CamundaUserDTO`. To me it makes sense to use the DTO defined in rest-api in the controller as well to prevent inconsistencies.

File: authentication/src/main/java/io/camunda/authentication/entity/CamundaUser.java [hunk 3]
```diff
@@ -19,7 +19,6 @@
 
 public final class CamundaUser extends User implements CamundaPrincipal {
```
Comment (maryarm) [inline authentication/src/main/java/io/camunda/authentication/entity/CamundaUser.java:20]: :question: Is there any usage for `getUserId` method or it can be removed?

**Review by maryarm — CHANGES_REQUESTED** [review]
Nice job, I've added a question and one request for change regarding the sync between api definition and implementation.

File: authentication/src/main/java/io/camunda/authentication/entity/CamundaUser.java (hunk 3 above)
Comment (ana-vinogradova-camunda) [reply authentication/src/main/java/io/camunda/authentication/entity/CamundaUser.java:20]: Yes, I believe this should be also removed

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml (hunk 2 above)
Comment (ana-vinogradova-camunda) [reply zeebe/gateway-protocol/src/main/proto/rest-api.yaml:7650]: Yes, for consistency. I am just wondering if we should rename it? As if we use `CamundaUserDTO` it will be the only DTO object in the entire rest api spec and it will be inconsistent with other namings. WDYT?

Comment (ana-vinogradova-camunda) [reply zeebe/gateway-protocol/src/main/proto/rest-api.yaml:7650]: May be renaming the DTO to `CamundaCurrentUserResult` or `CurrentUserResult`?
Most of our API responses are following the `...Result` pattern

Comment (maryarm) [reply zeebe/gateway-protocol/src/main/proto/rest-api.yaml:7650]: Im my idea, we have to use the generated class for `CamundaUserResult` as the response type.

Comment (ana-vinogradova-camunda) [reply zeebe/gateway-protocol/src/main/proto/rest-api.yaml:7650]: I've switched to `CamundaUserResult` and adjuste API spec to reflect that.
Also, I've removed `tenantKey` as per discussion with Thorben.

**Review by maryarm — APPROVED** [review]
Thanks for addressing my comments, looks good to me.
