### PR TITLE
fix(gateway): allow to use IPv6 addresses in a cluster

### LINKED ISSUE #5951: Gateway not able to parse ipv6 addresses
**Describe the bug**
I am trying to get a 1 gateway & 3 broker setup done on an env with **ipv6.**

I am getting this in each broker, so I know they are starting correctly.

```
2020-12-02 07:38:26.429 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-2 succeeded. Started 14 steps in 16049 ms.
```
however when I try to exec inside the broker and try "zbctl status" or "zbctl status --insecure" I keep getting this error

```
kubectl exec -it z2943-broker1-01 /bin/bash
root@z2943-broker1-01:/usr/local/zeebe# zbctl status
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
root@z2943-broker1-01:/usr/local/zeebe# zbctl status --insecure
Error: rpc error: code = Unknown desc = 
```
If I try to specify the pod address...
```
root@z2943-broker1-01:/usr/local/zeebe# zbctl status --address 240b:c0e0:202:5e2b:b424:2:0:51f
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address tcp/c0e0: unknown port"
root@z2943-broker1-01:/usr/local/zeebe# zbctl status --address [240b:c0e0:202:5e2b:b424:2:0:51f]
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address [240b:c0e0: missing ']' in address"
```

My guess is that the brokers are not able to differentiate between a ipv4 and ipv6 address.

**To Reproduce**
1 gateway with 3 clusters with the below settings - 

for broker - > image version is 0.25.1
env vars are ->
     ZEEBE_BROKER_CLUSTER_NODEID: '1' #different 0,1,2 for each of the three brokers.
     ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT: '3'
     ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR: '3'
     ZEEBE_BROKER_CLUSTER_CLUSTERSIZE: '3'
     ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS: '{{APP_NAME}}-broker1-cl-0:26502,{{APP_NAME}}-broker2-cl-0:26502,{{APP_NAME}}-broker3-cl-0:26502'
     ZEEBE_BROKER_CLUSTER_CLUSTERNAME: 'zeebe-cluster'
     ZEEBE_BROKER_NETWORK_COMMANDAPI_PORT: '26501'
     ZEEBE_BROKER_NETWORK_INTERNALAPI_PORT: '26502'
     ZEEBE_BROKER_NETWORK_MONITOIRNGAPI_PORT: '9600'

for gateway -> image version is 0.25.1
env vars are ->
     ZEEBE_STANDALONE_GATEWAY: 'true'
     ZEEBE_GATEWAY_NETWORK_HOST: '0.0.0.0'
     ZEEBE_GATEWAY_NETWORK_PORT: '26500'
     ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT: '{{APP_NAME}}-broker1-cl-0:26502'
     ZEEBE_GATEWAY_CLUSTER_CLUSTERNAME: 'zeebe-cluster'
     ZEEBE_GATEWAY_CLUSTER_MEMBERID: '3'
     ZEEBE_GATEWAY_CLUSTER_HOST: '0.0.0.0'
     ZEEBE_GATEWAY_CLUSTER_PORT: '26502'

**Expected behavior**
Gateway should be able to connect to the brokers and I should be able to use zbctl status to see the brokers,replications,partitions.

**Log/Stacktrace**
This error comes up inside the gateway
```
2020-12-02 07:45:11.612 [] [grpc-default-executor-0] ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@501e95a8
java.lang.NumberFormatException: For input string: "c0e0"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at io.zeebe.gateway.EndpointManager.addBrokerInfo(EndpointManager.java:78) ~[zeebe-gateway-0.25.1.jar:0.25.1]
	at io.zeebe.gateway.EndpointManager.lambda$topology$1(EndpointManager.java:253) ~[zeebe-gateway-0.25.1.jar:0.25.1]
	at org.agrona.collections.IntArrayList.forEach(IntArrayList.java:588) ~[agrona-1.8.0.jar:1.8.0]
	at io.zeebe.gateway.EndpointManager.topology(EndpointManager.java:250) ~[zeebe-gateway-0.25.1.jar:0.25.1]
	at io.zeebe.gateway.GatewayGrpcService.topology(GatewayGrpcService.java:135) ~[zeebe-gateway-0.25.1.jar:0.25.1]
	at io.zeebe.gateway.protocol.GatewayGrpc$MethodHandlers.invoke(GatewayGrpc.java:1532) ~[zeebe-gateway-protocol-impl-0.25.1.jar:0.25.1]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.33.0.jar:1.33.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.33.0.jar:1.33.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

My pods are
```
kubectl get pods -o wide | grep z2943
z2943-broker1-01                        1/1     Running            0          54m     240b:c0e0:202:5e2b:b424:2:0:51f
z2943-broker2-01                        1/1     Running            0          54m     240b:c0e0:202:5e2b:b424:2:0:37b
z2943-broker3-01                        1/1     Running            0          54m     240b:c0e0:202:5e2b:b424:2:0:c56
z2943-gateway-01                        1/1     Running            0          53m     240b:c0e0:202:5e2b:b424:2:0:af3
```

**Environment:**
 - OS: kubernetes - ipv6
 - Zeebe Version: 0.25.1
 - Configuration: 1 gateway with 3 brokers

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

Allow using IPv6 stack in a cluster. Also, I added the Maven profile for testing the IPv6 in the Atomix cluster.

## Related issues

closes #5951

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by aivinog1** [comment]
Hi, reviewer! Can you label this PR with backport labels, please? :)

**Review by npepinpe — CHANGES_REQUESTED** [review]
Hey @aivinog1, thanks for the fast PR!

Instead of adding a new direct dependency to guava in the gateway, how about we replace `io.atomix.utils.net.Address#from(String)` with something like

```java
/**
   * Returns the address from the given host:port string.
   *
   * @param address the address string
   * @return the address
   */
  public static Address from(final String address) {
    try {
      final HostAndPort parsedAddress =
          HostAndPort.fromString(address).withDefaultPort(DEFAULT_PORT);
      return new Address(parsedAddress.getHost(), parsedAddress.getPort());
    } catch (final IllegalStateException e) {
      return from(DEFAULT_PORT);
    }
  }
```

And then use that in the gateway? `Address.from(brokerAddress).getHost()`. This would improve the current `Address` class (since it currently has a hand-written parsing method, better use Guava's), and avoid adding a new direct dependency to the gateway which already depends on Atomix utils.

Regarding the new profiles, that's a good idea, but I think we don't need something so complicated, and I think it's a little overkill to run the test suite with different profiles. We could simply write a QA test which uses IPv6, then make sure all the nodes can find each other by checking that the topology is as expected. This should be do-able via Zeebe Test Container, but let me know if you need some help to write one :+1: 

Finally, I think you missed a case in `io.zeebe.broker.clustering.atomix.AtomixFactory#NodeDiscoveryProvider createDiscoveryProvider(ClusterCfg, String)`, where we also split over `:` - here we can also just reuse `Address.from(String)` as well.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+  @Rule
+  public final Network network =
+      Network.builder()
+          .createNetworkCmdModifier(
+              createNetworkCmd ->
+                  createNetworkCmd
+                      .withIpam(new Ipam().withConfig(new Config().withSubnet(SUBNET)))
+                      .withName(NETWORK_ALIAS))
+          .enableIpv6(true)
+          .build();
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:51]: Great stuff :+1:

**Review by npepinpe — COMMENTED** [review]
Nice! I'll push it to our Jenkins and let's see, but I don't see any blockers now :muscle:

**Review by npepinpe — COMMENTED** [review]
I see there's some debugging things, ping me when you're finished with it - I'll check the build result and put what went wrong in a bit

**Comment by aivinog1** [comment]
Hey @npepinpe! I've fixed all review comments, can you take a look, please? :)

**Comment by npepinpe** [comment]
There was a build failure earlier, let's re-run it and see again :+1: 

Just FYI, the failure was:

<details><summary>Logs</summary>

```
Error Message

Container startup failed

Stacktrace

org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at io.zeebe.broker.it.network.Ipv6IntegrationTest.shouldCommunicateOverIpv6(Ipv6IntegrationTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	... 57 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:497)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 58 more
Caused by: java.lang.IllegalStateException: Container exited with code 1
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:469)
	... 60 more

Standard Output

13:24:54.408 [] [main] INFO  io.zeebe.test - Test started: shouldCommunicateOverIpv6(io.zeebe.broker.it.network.Ipv6IntegrationTest)
13:24:54.413 [] [main] INFO  Test - Configuring broker with initial contactpoints [[fe81::aede:4844:fe00:2]:26502]
13:24:54.414 [] [main] INFO  Test - Configuring broker with initial contactpoints [[fe81::aede:4844:fe00:2]:26502, [fe81::aede:4844:fe00:3]:26502]
13:24:54.414 [] [main] INFO  Test - Configuring broker with initial contactpoints [[fe81::aede:4844:fe00:2]:26502, [fe81::aede:4844:fe00:3]:26502, [fe81::aede:4844:fe00:4]:26502]
13:24:54.415 [] [main] INFO  🐳 [camunda/zeebe:current-test] - Creating container for image: camunda/zeebe:current-test
13:24:54.415 [] [ForkJoinPool.commonPool-worker-17] INFO  🐳 [camunda/zeebe:current-test] - Creating container for image: camunda/zeebe:current-test
13:24:54.415 [] [ForkJoinPool.commonPool-worker-5] INFO  🐳 [camunda/zeebe:current-test] - Creating container for image: camunda/zeebe:current-test
13:25:16.216 [] [ForkJoinPool.commonPool-worker-17] INFO  🐳 [camunda/zeebe:current-test] - Starting container with ID: c7a6e63291df51f1df96069771e98c6023698d72530c67f91396e7ecd5f261b5
13:25:16.216 [] [main] INFO  🐳 [camunda/zeebe:current-test] - Starting container with ID: b1f9165e15976de9b9dd260048a29103e1f1a4dd6846271a90a4b71695a74b47
13:25:16.219 [] [ForkJoinPool.commonPool-worker-5] INFO  🐳 [camunda/zeebe:current-test] - Starting container with ID: d076a8402d1ada36cabbc5bc94fe75dae58048e514cdef4932e216cb5ade805a
13:25:16.788 [] [main] INFO  🐳 [camunda/zeebe:current-test] - Container camunda/zeebe:current-test is starting: b1f9165e15976de9b9dd260048a29103e1f1a4dd6846271a90a4b71695a74b47
13:25:16.860 [] [ForkJoinPool.commonPool-worker-5] INFO  🐳 [camunda/zeebe:current-test] - Container camunda/zeebe:current-test is starting: d076a8402d1ada36cabbc5bc94fe75dae58048e514cdef4932e216cb5ade805a
13:25:16.904 [] [ForkJoinPool.commonPool-worker-17] INFO  🐳 [camunda/zeebe:current-test] - Container camunda/zeebe:current-test is starting: c7a6e63291df51f1df96069771e98c6023698d72530c67f91396e7ecd5f261b5
13:26:16.798 [] [main] ERROR 🐳 [camunda/zeebe:current-test] - Could not start container
java.lang.IllegalStateException: Container exited with code 1
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:469) ~[testcontainers-1.15.2.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.15.2.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) ~[testcontainers-1.15.2.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) ~[testcontainers-1.15.2.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) [?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408) [?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736) [?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) [?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) [?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661) [?:?]
	at io.zeebe.broker.it.network.Ipv6IntegrationTest.shouldCommunicateOverIpv6(Ipv6IntegrationTest.java:78) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
13:26:16.829 [] [main] ERROR 🐳 [camunda/zeebe:current-test] - Log output from the failed container:
++ hostname -i
+ export ZEEBE_HOST=fe81::aede:4844:fe00:3
+ ZEEBE_HOST=fe81::aede:4844:fe00:3
+ '[' false = true ']'
+ export ZEEBE_BROKER_NETWORK_HOST=fe81::aede:4844:fe00:3
+ ZEEBE_BROKER_NETWORK_HOST=fe81::aede:4844:fe00:3
+ export ZEEBE_BROKER_GATEWAY_CLUSTER_HOST=fe81::aede:4844:fe00:3
+ ZEEBE_BROKER_GATEWAY_CLUSTER_HOST=fe81::aede:4844:fe00:3
+ exec /usr/local/zeebe/bin/broker
  ______  ______   ______   ____    ______     ____    _____     ____    _  __  ______   _____  
 |___  / |  ____| |  ____| |  _ \  |  ____|   |  _ \  |  __ \   / __ \  | |/ / |  ____| |  __ \ 
    / /  | |__    | |__    | |_) | | |__      | |_) | | |__) | | |  | | | ' /  | |__    | |__) |
   / /   |  __|   |  __|   |  _ <  |  __|     |  _ <  |  _  /  | |  | | |  <   |  __|   |  _  / 
  / /__  | |____  | |____  | |_) | | |____    | |_) | | | \ \  | |__| | | . \  | |____  | | \ \ 
 /_____| |______| |______| |____/  |______|   |____/  |_|  \_\  \____/  |_|\_\ |______| |_|  \_\
                                                                                                
2021-03-04 13:25:18.555 [] [main] INFO 
      io.zeebe.broker.StandaloneBroker - Starting StandaloneBroker v1.0.0-SNAPSHOT using Java 11.0.10 on fe81::aede:4844:fe00:3 with PID 6 (/usr/local/zeebe/lib/zeebe-distribution-1.0.0-SNAPSHOT.jar started by root in /usr/local/zeebe)
2021-03-04 13:25:18.566 [] [main] DEBUG
      io.zeebe.broker.StandaloneBroker - Running with Spring Boot v2.4.3, Spring v5.3.4
2021-03-04 13:25:18.567 [] [main] INFO 
      io.zeebe.broker.StandaloneBroker - No active profile set, falling back to default profiles: default
2021-03-04 13:25:20.105 [] [main] INFO 
      org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 9600 (http)
2021-03-04 13:25:20.118 [] [main] INFO 
      org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-fe81:0:0:0:aede:4844:fe00:3-9600"]
2021-03-04 13:25:20.119 [] [main] INFO 
      org.apache.catalina.core.StandardService - Starting service [Tomcat]
2021-03-04 13:25:20.120 [] [main] INFO 
      org.apache.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.43]
2021-03-04 13:25:20.250 [] [main] INFO 
      org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2021-03-04 13:25:20.250 [] [main] INFO 
      org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 1624 ms
2021-03-04 13:25:20.773 [] [main] INFO 
      org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
2021-03-04 13:25:21.156 [] [main] INFO 
      org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver - Exposing 4 endpoint(s) beneath base path '/actuator'
2021-03-04 13:25:21.193 [] [main] INFO 
      org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-fe81:0:0:0:aede:4844:fe00:3-9600"]
2021-03-04 13:25:21.204 [] [main] WARN 
      org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
2021-03-04 13:25:21.205 [] [main] INFO 
      org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
2021-03-04 13:25:21.213 [] [main] INFO 
      org.apache.coyote.http11.Http11NioProtocol - Pausing ProtocolHandler ["http-nio-fe81:0:0:0:aede:4844:fe00:3-9600"]
2021-03-04 13:25:21.214 [] [main] INFO 
      org.apache.catalina.core.StandardService - Stopping service [Tomcat]
2021-03-04 13:25:21.221 [] [main] INFO 
      org.apache.coyote.http11.Http11NioProtocol - Stopping ProtocolHandler ["http-nio-fe81:0:0:0:aede:4844:fe00:3-9600"]
2021-03-04 13:25:21.222 [] [main] INFO 
      org.apache.coyote.http11.Http11NioProtocol - Destroying ProtocolHandler ["http-nio-fe81:0:0:0:aede:4844:fe00:3-9600"]
2021-03-04 13:25:21.237 [] [main] INFO 
      org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-04 13:25:21.261 [] [main] ERROR
      org.springframework.boot.SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.4.jar:5.3.4]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:934) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:585) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.3.jar:2.4.3]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:47) [zeebe-distribution-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:229) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.4.jar:5.3.4]
	... 15 more
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:244) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.4.jar:5.3.4]
	... 15 more
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1074) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:240) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.4.jar:5.3.4]
	... 15 more
Caused by: java.net.SocketException: No such device
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
	at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[?:?]
	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:277) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:241) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1193) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1279) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:608) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1071) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:240) ~[tomcat-embed-core-9.0.43.jar:9.0.43]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.4.jar:5.3.4]
	... 15 more
```

</details>

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+  private void configureBrokerContainer(final int index, final List<ZeebeBrokerContainer> brokers) {
+    final int clusterSize = brokers.size();
+    final var broker = brokers.get(index);
+    final var hostNameWithoutBraces = String.format("%s%d", BASE_PART_OF_SUBNET, index + 2);
+    final var hostName = String.format("[%s]", hostNameWithoutBraces);
+
+    initialContactPoints.add(hostName + ":" + ZeebePort.INTERNAL.getPort());
+    LoggerFactory.getLogger("Test")
+        .info("Configuring broker with initial contactpoints {}", initialContactPoints);
+
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:103]: Probably not necessary

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+    // given
+    containers.parallelStream().forEach(GenericContainer::start);
+    gateway.start();
+
+    // when
+    final ZeebeClientBuilder zeebeClientBuilder =
+        ZeebeClient.newClientBuilder()
+            .usePlaintext()
+            .gatewayAddress(gateway.getExternalGatewayAddress());
+    final Topology topology;
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:86]: Just a nit pick, since the topology is only used in the try catch, you can just declare there.

**Comment by aivinog1** [comment]
@npepinpe Well, I encountered these issues:

1. There was a documentation error in Docker, that says that IPv6 with Docker doesn't work on Mac OS. This isn't actually true, but I spend a lot of time pushing to the branch to see what's going on on my second Linux machine
2. I'll use a fe80::/64 addresses for first but it doesn't work since they are link-local addresses(P2P), and I saw that gossip doesn't work on such subnets.
3. I figured out that I should not change `ZEEBE_HOST`, `ZEEBE_GATEWAY_NETWORK_HOST`, and `ZEEBE_BROKER_NETWORK_HOST`, because if I do this I'll break communication docker hosts with parent host and the container doesn't up.

**Comment by aivinog1** [comment]
@npepinpe Actually, we should enable IPv6 support in the Docker server that runs on CI (it is disabled by default): https://docs.docker.com/config/daemon/ipv6/

**Comment by npepinpe** [comment]
Ah, I see - I have to get off, but I'll look into this tomorrow. For now the build fails because of formatting issues in the IPv6 test.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java (hunk 2 above)
Comment (aivinog1) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java]: Done

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java (hunk 3 above)
Comment (aivinog1) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java]: Done

**Comment by aivinog1** [comment]
@npepinpe Oops missed that 😅. So I fixed review comments and fixed all code formating issues :)

**Comment by bhupesh-sf** [comment]
@npepinpe Any update on this PR being merged?

File: dist/src/main/resources/application.properties [hunk 4]
```diff
@@ -14,3 +14,4 @@ management.endpoint.loggers.enabled=true
 #Allow partitions api - this allows to trigger snapshots and pause processing
 management.endpoint.partitions.enabled=true
 
+zeebe.broker.network.host=::1
```
Comment (npepinpe) [inline dist/src/main/resources/application.properties:17]: This will default to bind to ipv6 loopback always - what if we deploy to a VM without IPv6 support? I know it's unlikely, but I wouldn't set it as default. We can set it in the environment variables in the test.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+import org.junit.Test;
+import org.testcontainers.containers.GenericContainer;
+import org.testcontainers.containers.Network;
+
+public class Ipv6IntegrationTest {
+  private static final int CLUSTER_SIZE = 3;
+  private static final int PARTITION_COUNT = 1;
+  private static final int REPLICATION_FACTOR = 3;
+  private static final String ZEEBE_IMAGE_VERSION = "camunda/zeebe:current-test";
+  private static final String NETWORK_ALIAS = "test-ipv6";
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:37]:
```suggestion
  private static final String NETWORK_ALIAS = Ipv6IntegrationTest.class.getName();
```

I think this will make it less likely to collide with anything, and clearer what it references/is used for.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+        .withEnv("ZEEBE_BROKER_NETWORK_MAXMESSAGESIZE", "128KB")
+        .withEnv("ZEEBE_BROKER_CLUSTER_NODEID", String.valueOf(index))
+        .withEnv("ZEEBE_BROKER_CLUSTER_CLUSTERSIZE", String.valueOf(clusterSize))
+        .withEnv("ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR", String.valueOf(REPLICATION_FACTOR))
+        .withEnv("ZEEBE_BROKER_CLUSTER_PARTITIONCOUNT", String.valueOf(PARTITION_COUNT))
+        .withEnv(
+            "ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS", String.join(",", initialContactPoints))
+        .withEnv("ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDHOST", hostNameWithoutBraces)
+        .withEnv("ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDHOST", hostNameWithoutBraces)
+        .withEnv("ZEEBE_BROKER_NETWORK_MONITORINGAPI_ADVERTISEDHOST", hostNameWithoutBraces)
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:117]:
```suggestion
        .withEnv("ZEEBE_BROKER_NETWORK_ADVERTISEDHOST", hostNameWithoutBraces)
```

This will be picked up by the various APIs.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 7]
```diff
@@ -0,0 +1,138 @@
...
+        .withEnv("ZEEBE_LOG_LEVEL", "DEBUG")
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:118]:
```suggestion
        .withEnv("ZEEBE_BROKER_NETWORK_HOST", "::")
        .withEnv("ZEEBE_LOG_LEVEL", "DEBUG")
```

I want to ensure that we go through IPv6 interfaces, but we still need to work around the Testcontainers limitation for now (i.e. the WaitStrategy-s we use).

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 8]
```diff
@@ -0,0 +1,138 @@
...
+      final Topology topology = client.newTopologyRequest().send().join(5, TimeUnit.SECONDS);
+      // then - can find each other
+      TopologyAssert.assertThat(topology).isComplete(3, 1);
+    }
+  }
+
+  private void configureBrokerContainer(final int index, final List<ZeebeBrokerContainer> brokers) {
+    final int clusterSize = brokers.size();
+    final var broker = brokers.get(index);
+    final var hostNameWithoutBraces = String.format("%s%d", BASE_PART_OF_SUBNET, index + 2);
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:95]:
```suggestion
    final var hostNameWithoutBraces = String.format("%s%d", BASE_PART_OF_SUBNET, index + 2);
```

Can we extract this to a private method and reuse it for the gateway? This will allow us to document and explain why the +2.

e.g.

```java
private String getIpv6AddressForIndex(final int index) {
    // offset the index by 2 as indexes start at 0, and :1 is the gateway, so the first address
    // should start at :2
    return String.format("%s%d", BASE_PART_OF_SUBNET, index + 2);
  }
```

Then we can call `getIpv6AddressForIndex(CLUSTER_SIZE)` for the gateway.

**Review by npepinpe — CHANGES_REQUESTED** [review]
I had a look, and after some finagling with Docker, I have a few notes:

1. It seems on Linux you need at least version 20.x so it properly routes IPv6 stuff - that's fine, not an issue, but we'll need to document this for developers.
2. When I set an IPv6 address to the gateway (e.g. `::`), the client it uses internally for health checks cannot be built.
3. I'm not sure the test is really testing IPv6 - yes the brokers can find each other over IPv6, but then we're only testing the internal communication and not the gateway or the embedded gateway. It's better than nothing but it's not complete I think.
4. I tried setting host to the IPv6 address as well, but I ran into limitations with Testcontainers - I asked on their Slack and some of the wait strategies have issues since they use the Docker host's IPv4 address by default. So if the server doesn't find to the IPv4 iface as well then the container is not detected as started by Testcontainers (even though it starts fine!). The suggestion for now was that we cannot use `HostPortWaitStrategy` at all (since the internal check for IPv4 hardcoded), and for others we need to wrap existing ones to supply the correct IPv6 host address, which is rather meh (though it works from what I can see).

Regarding the last points, I think at least setting the host to `::` (i.e. `INADDR6_ANY`) is a good compromise until Testcontainers fully supports IPv6 OOTB (bsideup if you read this again, no need to apologize, Testcontainers is still a godsend :sweat_smile:)

Regarding point 2, I get the following error in the gateway when I make the gateway bind to `::`:

```
2021-03-10 16:44:47.168 [] [scheduling-1] ERROR
      org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
java.lang.NullPointerException: target
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897) ~[guava-30.1-jre.jar:?]
	at io.grpc.internal.ManagedChannelImplBuilder.<init>(ManagedChannelImplBuilder.java:246) ~[grpc-core-1.36.0.jar:1.36.0]
	at io.grpc.internal.ManagedChannelImplBuilder.<init>(ManagedChannelImplBuilder.java:231) ~[grpc-core-1.36.0.jar:1.36.0]
	at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:184) ~[grpc-netty-1.36.0.jar:1.36.0]
	at io.grpc.netty.NettyChannelBuilder.forTarget(NettyChannelBuilder.java:152) ~[grpc-netty-1.36.0.jar:1.36.0]
	at io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:135) ~[grpc-netty-1.36.0.jar:1.36.0]
	at io.zeebe.client.impl.ZeebeClientImpl.buildChannel(ZeebeClientImpl.java:124) ~[zeebe-client-java-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:80) ~[zeebe-client-java-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.client.impl.ZeebeClientBuilderImpl.build(ZeebeClientBuilderImpl.java:301) ~[zeebe-client-java-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.gateway.impl.probes.health.ResponsiveHealthIndicator.createZeebeClient(ResponsiveHealthIndicator.java:93) ~[zeebe-gateway-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.gateway.impl.probes.health.ResponsiveHealthIndicator.supplyZeebeClient(ResponsiveHealthIndicator.java:72) ~[zeebe-gateway-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.gateway.impl.probes.health.ResponsiveHealthIndicator.health(ResponsiveHealthIndicator.java:53) ~[zeebe-gateway-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.health.DelayedHealthIndicator.checkHealth(DelayedHealthIndicator.java:68) ~[zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.3.4.jar:5.3.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

This breaks our liveness probes, but it looks like it has to do with client code.

One last thing, for our CI builds, you'll need to update the following files:

- .ci/podSpecs/distribution-template.yml
- .ci/podSpecs/integration-test-template.yml

In both, you will find the following:

```yaml
    - name: docker
      image: docker:19.03.13-dind
      args:
        - --storage-driver=overlay
```

Which you need to replace with:

```yaml
    - name: docker
      image: docker:20.10.5-dind
      args:
        - --storage-driver=overlay
        - --ipv6
        - --fixed-cidr-v6 "2001:db8:1::/64"
```

**Comment by aivinog1** [comment]
@npepinpe Hey, many thanks for your review :) But I have a question about this:

> Regarding point 2, I get the following error in the gateway when I make the gateway bind to :::
2021-03-10 16:44:47.168 [] [scheduling-1] ERROR

Actually, when I set `.withEnv("ZEEBE_GATEWAY_NETWORK_HOST", "::")` to the gateway container I have no errors.

I fixed all your review comments, please, take another look.

**Comment by npepinpe** [comment]
I don't know what to say :sweat_smile: 

I rebased, rebuilt, etc., and if I do a `docker logs -f <GATEWAY CONTAINER ID>`, I do see the error I mentioned above. I think the problem is the client doesn't handle a gateway address like `::`, since it will just append the port, so you end up with `:::26500`, which is an invalid URL (it should be `[::]:26500`.

See `ResponsiveHealthIndicator#getContactPoint(String)`, where it returns `host + ":" + port` :sweat_smile: So if you put `::` it will generate this invalid URL.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 9]
```diff
@@ -0,0 +1,145 @@
...
+        .withEnv("ZEEBE_BROKER_NETWORK_MAXMESSAGESIZE", "128KB")
+        .withEnv("ZEEBE_BROKER_CLUSTER_NODEID", String.valueOf(index))
+        .withEnv("ZEEBE_BROKER_CLUSTER_CLUSTERSIZE", String.valueOf(clusterSize))
+        .withEnv("ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR", String.valueOf(REPLICATION_FACTOR))
+        .withEnv("ZEEBE_BROKER_CLUSTER_PARTITIONCOUNT", String.valueOf(PARTITION_COUNT))
+        .withEnv(
+            "ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS", String.join(",", initialContactPoints))
+        .withEnv("ZEEBE_BROKER_NETWORK_ADVERTISEDHOST", hostNameWithoutBraces)
+        .withEnv("ZEEBE_LOG_LEVEL", "DEBUG")
+        .withEnv("ZEEBE_BROKER_NETWORK_HOST", "::")
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:117]:
```suggestion
        .withEnv("ZEEBE_BROKER_NETWORK_HOST", "[::]")
```

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 10]
```diff
@@ -0,0 +1,145 @@
...
+    gateway
+        .withEnv("ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT", initialContactPoint)
+        .withTopologyCheck(
+            new ZeebeTopologyWaitStrategy()
+                .forBrokersCount(CLUSTER_SIZE)
+                .forPartitionsCount(PARTITION_COUNT)
+                .forReplicationFactor(REPLICATION_FACTOR))
+        .withNetwork(network)
+        .withNetworkAliases(NETWORK_ALIAS)
+        .withEnv("ZEEBE_GATEWAY_NETWORK_HOST", "::")
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:134]:
```suggestion
        .withEnv("ZEEBE_GATEWAY_NETWORK_HOST", "[::]")
        .withEnv("ZEEBE_GATEWAY_CLUSTER_HOST", address)
```

`ZEEBE_GATEWAY_CLUSTER_HOST` sets the address on which brokers should talk back to the gateway, so we also want it to be IPv6. Sorry I missed that initially.

**Review by npepinpe — CHANGES_REQUESTED** [review]

**Review by npepinpe — CHANGES_REQUESTED** [review]
Enabling IPv6 seems to break testcontainers-go :sweat_smile: 

If you go to `clients/go/test` and run `go test integration_test.go`, the container seems to try to start with the following host 

```
++ hostname -i
+ export 'ZEEBE_HOST=2001:db8:1::242:ac11:3 172.17.0.3'
+ ZEEBE_HOST='2001:db8:1::242:ac11:3 172.17.0.3'
+ '[' false = true ']'
+ export 'ZEEBE_BROKER_NETWORK_HOST=2001:db8:1::242:ac11:3 172.17.0.3'
+ ZEEBE_BROKER_NETWORK_HOST='2001:db8:1::242:ac11:3 172.17.0.3'
+ export 'ZEEBE_BROKER_GATEWAY_CLUSTER_HOST=2001:db8:1::242:ac11:3 172.17.0.3'
+ ZEEBE_BROKER_GATEWAY_CLUSTER_HOST='2001:db8:1::242:ac11:3 172.17.0.3'
+ exec /usr/local/zeebe/bin/broker
```

So it seems to pick up both the IPv6 host and the IPv4? I think this is an issue with the startup script in Zeebe that we use to build the image? Changing `containerSuite.go#SetupSuite()` to setup the container as:

```go
	req := testcontainers.GenericContainerRequest{
		ContainerRequest: testcontainers.ContainerRequest{
			Image:        s.ContainerImage,
			ExposedPorts: []string{"26500"},
			WaitingFor:   zeebeWaitStrategy{waitTime: s.WaitTime},
			Env:          map[string]string{
				"ZEEBE_BROKER_NETWORK_HOST": "0.0.0.0",
				"ZEEBE_BROKER_NETWORK_ADVERTISEDHOST": "0.0.0.0",
			},
		},
		Started: true,
	}
```

Seems to work (we explicit set the host to bind to as 0.0.0.0). So it looks like in `docker/utils/startup.sh`, we pick up all the host names available and set that as default host, which is probably wrong? I guess we should pick only one at the very least, but we can consider it as out of scope here as we have a workaround.

You can play around with it by running the Go tests - they were failing locally for me without these changes. You can run them by just going to `clients/go && go test ./...`. If you need any help just ask!

Finally, I also see the following test fail: shouldContainRootCauses – io.zeebe.broker.it.client.ClientExceptionHandlingTest

```Error
Expecting throwable message:
  "connect(..) failed: Address family not supported by protocol: localhost/0:0:0:0:0:0:0:1:1234"
to contain:
  "Connection refused:"
but did not.
Throwable that failed the check:
io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: localhost/0:0:0:0:0:0:0:1:1234
Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
 at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
 at io.netty.channel.unix.Socket.connect(Socket.java:240)
 at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:736)
 at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:721)
 at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:563)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
 at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
 at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
 at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
 at io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:150)
 at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
 at io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
 at io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:538)
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:834)
Stacktrace
java.lang.AssertionError: 
Expecting throwable message:
  "connect(..) failed: Address family not supported by protocol: localhost/0:0:0:0:0:0:0:1:1234"
to contain:
  "Connection refused:"
but did not.
Throwable that failed the check:
io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: localhost/0:0:0:0:0:0:0:1:1234
Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
	at io.netty.channel.unix.Socket.connect(Socket.java:240)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:736)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:721)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:563)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:538)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at io.zeebe.broker.it.client.ClientExceptionHandlingTest.shouldContainRootCauses(ClientExceptionHandlingTest.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

<details><summary>Standard Output</summary>

```
17:09:49.349 [] [main] INFO  io.zeebe.test - Test started: shouldContainRootCauses(io.zeebe.broker.it.client.ClientExceptionHandlingTest)
17:09:49.351 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7130 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=106}
17:09:49.351 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7131 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=107}
17:09:49.351 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7132 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=108}
17:09:49.351 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7133 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=109}
17:09:49.351 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7134 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=110}
17:09:49.351 [] [main] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/8acbb172-dab4-4afb-b998-326b081ac013
17:09:49.352 [] [main] INFO  io.zeebe.broker.system - Version: 1.0.0-SNAPSHOT
17:09:49.352 [] [main] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 7132,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7132,
      "address" : "0.0.0.0:7132",
      "advertisedAddress" : "0.0.0.0:7132"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 7133,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7133,
      "address" : "0.0.0.0:7133",
      "advertisedAddress" : "0.0.0.0:7133"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 7134,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7134,
      "address" : "0.0.0.0:7134",
      "advertisedAddress" : "0.0.0.0:7134"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 1,
    "clusterSize" : 1,
    "clusterName" : "zeebe-cluster",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : null,
    "directory" : "/tmp/8acbb172-dab4-4afb-b998-326b081ac013/data",
    "logSegmentSize" : "128MB",
    "snapshotPeriod" : "PT5M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.99,
    "diskUsageCommandWatermark" : 0.97,
    "diskUsageMonitoringInterval" : "PT1S",
    "logSegmentSizeInBytes" : 134217728,
    "freeDiskSpaceCommandWatermark" : 0,
    "freeDiskSpaceReplicationWatermark" : 0
  },
  "exporters" : {
    "test-recorder" : {
      "jarPath" : null,
      "className" : "io.zeebe.test.util.record.RecordingExporter",
      "args" : null,
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 7130,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:7133",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 7131,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT0.1S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      }
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "initialized" : true,
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "0MB",
    "disableExplicitRaftFlush" : false,
    "detectReprocessingInconsistency" : false,
    "rocksdb" : {
      "columnFamilyOptions" : { },
      "enableStatistics" : false,
      "memoryLimit" : "512MB",
      "maxOpenFiles" : -1,
      "maxWriteBufferNumber" : 6,
      "minWriteBufferNumberToMerge" : 3,
      "ioRateBytesPerSecond" : 0,
      "disableWal" : false
    },
    "maxAppendBatchSizeInBytes" : 32768
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
17:09:49.352 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/14]: actor scheduler
17:09:49.353 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/14]: actor scheduler started in 1 ms
17:09:49.353 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/14]: membership and replication protocol
17:09:49.355 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/14]: membership and replication protocol started in 2 ms
17:09:49.355 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/14]: command api transport
17:09:49.357 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:7132
17:09:49.357 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
17:09:49.357 [] [main] DEBUG io.zeebe.broker.system - Bound command API to [0.0.0.0:7132], using advertised address 0.0.0.0:7132 
17:09:49.357 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/14]: command api transport started in 2 ms
17:09:49.357 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/14]: command api handler
17:09:49.357 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/14]: command api handler started in 0 ms
17:09:49.357 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/14]: subscription api
17:09:49.358 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/14]: subscription api started in 1 ms
17:09:49.358 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services
17:09:49.358 [] [main] INFO  io.atomix.core.Atomix - 1.0.0-SNAPSHOT (revision 06815b built on 2021-03-12 17:00:20)
17:09:49.366 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:7133
17:09:49.366 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
17:09:49.368 [] [netty-unicast-event-nio-client-0] INFO  io.atomix.cluster.messaging.impl.NettyUnicastService - UDP server listening for connections on 0.0.0.0:7133
17:09:49.368 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
17:09:49.369 [] [atomix-cluster-0] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - Nodes from discovery service []
17:09:49.369 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
17:09:49.369 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
17:09:49.369 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started
17:09:49.369 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
17:09:49.370 [] [atomix-0] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-1} - Starting server for partition PartitionId{id=1, group=raft-partition}
17:09:49.376 [] [atomix-0] DEBUG io.zeebe.journal.file.SegmentedJournal - Created segment: JournalSegment{id=1, version=1, index=1}
17:09:49.379 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
17:09:49.379 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Single member cluster. Transitioning directly to candidate.
17:09:49.379 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE
17:09:49.379 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.raft.roles.FollowerRole$$Lambda$711/0x0000000840866840@21f089e8 not registered
17:09:49.379 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Single member cluster. Transitioning directly to leader.
17:09:49.384 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Set term 1
17:09:49.386 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Voted for 0
17:09:49.386 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to LEADER
17:09:49.386 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 0
17:09:49.389 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 1. RaftServer is ready only after it has committed events upto this index
17:09:49.389 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server join completed. Waiting for the server to be READY
17:09:49.389 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server started successfully!
17:09:49.389 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-1} - Successfully started server for partition PartitionId{id=1, group=raft-partition} in 19ms
17:09:49.389 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
17:09:49.389 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.primitive.partition.impl.DefaultPartitionService - Started class io.atomix.primitive.partition.impl.DefaultPartitionService
17:09:49.390 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services started in 32 ms
17:09:49.390 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/14]: topology manager
17:09:49.390 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/14]: topology manager started in 0 ms
17:09:49.390 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/14]: embedded gateway
17:09:49.390 [] [main] INFO  io.zeebe.gateway - Version: 1.0.0-SNAPSHOT
17:09:49.390 [] [main] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 7130,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "0.0.0.0:7133",
    "requestTimeout" : "PT15S",
    "clusterName" : "zeebe-cluster",
    "memberId" : "gateway",
    "host" : "0.0.0.0",
    "port" : 7131,
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "0.0.0.0",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  },
  "longPolling" : {
    "enabled" : true
  },
  "initialized" : true,
  "enable" : true
}
17:09:49.390 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Received new broker BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=1, replicationFactor=1, partitionRoles={}, partitionLeaderTerms={}, partitionHealthStatuses={}, version=1.0.0-SNAPSHOT}.
17:09:49.393 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/14]: embedded gateway started in 3 ms
17:09:49.393 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/14]: monitoring services
17:09:49.393 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [9/14]: monitoring services started in 0 ms
17:09:49.393 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/14]: disk space monitor
17:09:49.393 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/14]: disk space monitor started in 0 ms
17:09:49.393 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [11/14]: leader management request handler
17:09:49.393 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [11/14]: leader management request handler started in 0 ms
17:09:49.393 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [12/14]: zeebe partitions
17:09:49.394 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
17:09:49.394 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER in term 1
17:09:49.394 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition 1 closed all previous open resources, before transitioning.
17:09:49.395 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {logstream-raft-partition-partition-1=HEALTHY}
17:09:49.511 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/8acbb172-dab4-4afb-b998-326b081ac013/data/raft-partition/partitions/1/runtime'.
17:09:49.571 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
17:09:49.572 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
17:09:49.572 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@7dd661a3)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@f9fe444, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@57c56abb, configuration: Configuration(false)]
17:09:49.573 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
17:09:49.574 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@378ddcf7)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@799878dc, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@9d51e6f, configuration: Configuration(false)]
17:09:49.574 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@75393d5c)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@2c0a3d68, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@166efead, configuration: Configuration(false)]
17:09:49.576 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition 1 transition complete, installed 12 resources!
17:09:49.576 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
17:09:49.576 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
17:09:49.576 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Recovered exporter 'Broker-0-Exporter-1' from snapshot at lastExportedPosition -1
17:09:49.576 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'test-recorder'
17:09:49.576 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {Partition-1=HEALTHY}
17:09:49.576 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 182 ms
17:09:49.576 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] INFO  io.zeebe.broker.system - Partition-1 recovered, marking it as healthy
17:09:49.576 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 182 ms.
17:09:49.576 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [12/14]: zeebe partitions started in 183 ms
17:09:49.576 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [13/14]: register diskspace usage listeners
17:09:49.576 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [13/14]: register diskspace usage listeners started in 0 ms
17:09:49.576 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [14/14]: upgrade manager
17:09:49.576 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={EVENT=true, COMMAND=true, SBE_UNKNOWN=true, COMMAND_REJECTION=true, NULL_VAL=true}, acceptValueTypes={ERROR=true, MESSAGE_SUBSCRIPTION=true, INCIDENT=true, WORKFLOW_INSTANCE=true, DEPLOYMENT=true, VARIABLE=true, WORKFLOW=true, DEPLOYMENT_DISTRIBUTION=true, WORKFLOW_INSTANCE_RESULT=true, JOB_BATCH=true, SBE_UNKNOWN=true, WORKFLOW_INSTANCE_SUBSCRIPTION=true, TIMER=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, JOB=true, VARIABLE_DOCUMENT=true, WORKFLOW_INSTANCE_CREATION=true, NULL_VAL=true, MESSAGE=true}}
17:09:49.576 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [14/14]: upgrade manager started in 0 ms
17:09:49.576 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 14 steps in 224 ms.
17:09:49.576 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Open exporter with id 'test-recorder'
17:09:49.619 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MTMyBQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}
17:09:49.619 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER}, terms {1=1} and health {1=HEALTHY}.
17:09:49.676 [] [main] INFO  io.zeebe.broker.test - 
====
Broker startup time: 326
====
17:09:49.678 [] [main] INFO  io.zeebe.broker.test - 
====
Client startup time: 2
====
17:09:49.689 [] [main] INFO  io.zeebe.broker.test - Client Rule assumption: Test execution time: 11
17:09:49.690 [] [main] INFO  io.zeebe.broker.test - Client closing time: 1
17:09:49.691 [] [main] INFO  io.zeebe.test.records - Test failed, following records were exported:
17:09:49.691 [] [main] INFO  io.zeebe.broker.test - Test execution time: 15
17:09:49.691 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [1/14]: upgrade manager
17:09:49.691 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [1/14]: upgrade manager closed in 0 ms
17:09:49.691 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [2/14]: register diskspace usage listeners
17:09:49.691 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [2/14]: register diskspace usage listeners closed in 0 ms
17:09:49.691 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [3/14]: zeebe partitions
17:09:49.691 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1
17:09:49.691 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe Partition 1.
17:09:49.691 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] ERROR io.zeebe.broker.system - ZeebePartition-1 failed, marking it as unhealthy
17:09:49.691 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {ZeebePartition-1=UNHEALTHY, Raft-1=HEALTHY, Broker-0-StreamProcessor-1=HEALTHY, logstream-raft-partition-partition-1=HEALTHY}
17:09:49.691 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ExporterDirector
17:09:49.692 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] ERROR io.zeebe.broker.system - Partition-1 failed, marking it as unhealthy
17:09:49.692 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {Partition-1=UNHEALTHY}
17:09:49.692 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Closed exporter director 'Broker-0-Exporter-1'.
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ExporterDirector closed successfully
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RocksDB metric timer
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RocksDB metric timer closed successfully
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AsyncSnapshotDirector
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AsyncSnapshotDirector closed successfully
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StreamProcessor
17:09:49.692 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StreamProcessor closed successfully
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ZeebeDb
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ZeebeDb closed successfully
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RegisterSnapshotListener
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RegisterSnapshotListener closed successfully
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: LogDeletionService
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: LogDeletionService closed successfully
17:09:49.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StateController
17:09:49.722 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/8acbb172-dab4-4afb-b998-326b081ac013/data/raft-partition/partitions/1/runtime'.
17:09:49.722 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StateController closed successfully
17:09:49.722 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: SnapshotReplication
17:09:49.722 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: SnapshotReplication closed successfully
17:09:49.722 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RaftLogReader
17:09:49.722 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RaftLogReader closed successfully
17:09:49.722 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: logstream
17:09:49.723 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Close appender for log stream logstream-raft-partition-partition-1
17:09:49.723 [logstream-raft-partition-partition-1-write-buffer] [Broker-0-zb-actors-1] DEBUG io.zeebe.dispatcher - Dispatcher closed
17:09:49.723 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-1 close 2 readers
17:09:49.723 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: logstream closed successfully
17:09:49.723 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AtomixLogStorage
17:09:49.723 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AtomixLogStorage closed successfully
17:09:49.723 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition 1 closed all previous open resources, before transitioning.
17:09:49.723 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition 1 transition complete, installed 0 resources!
17:09:49.723 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1 closed in 32 ms
17:09:49.723 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions succeeded. Closed 1 steps in 32 ms.
17:09:49.723 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [3/14]: zeebe partitions closed in 32 ms
17:09:49.723 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [4/14]: leader management request handler
17:09:49.723 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [4/14]: leader management request handler closed in 0 ms
17:09:49.723 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [5/14]: disk space monitor
17:09:49.723 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [5/14]: disk space monitor closed in 0 ms
17:09:49.723 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [6/14]: monitoring services
17:09:49.723 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [6/14]: monitoring services closed in 0 ms
17:09:49.723 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [7/14]: embedded gateway
17:09:49.723 [] [main] DEBUG io.zeebe.gateway - Closing gateway broker client ...
17:09:49.724 [] [main] DEBUG io.zeebe.gateway - topology manager closed
17:09:49.724 [] [main] DEBUG io.zeebe.gateway - Gateway broker client closed.
17:09:49.724 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [7/14]: embedded gateway closed in 1 ms
17:09:49.724 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [8/14]: topology manager
17:09:49.724 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [8/14]: topology manager closed in 0 ms
17:09:49.724 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [9/14]: cluster services
17:09:49.724 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [9/14]: cluster services closed in 0 ms
17:09:49.724 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [10/14]: subscription api
17:09:49.724 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [10/14]: subscription api closed in 0 ms
17:09:49.724 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [11/14]: command api handler
17:09:49.724 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [11/14]: command api handler closed in 0 ms
17:09:49.724 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [12/14]: command api transport
17:09:49.869 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MTMyBQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}
17:09:51.735 [] [ForkJoinPool.commonPool-worker-19] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
17:09:51.735 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [12/14]: command api transport closed in 2011 ms
17:09:51.735 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [13/14]: membership and replication protocol
17:09:51.735 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
17:09:51.735 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.zeebe.LogCompactor - LogCompactor{raft-partition-partition-1} - Closing the log compactor raft-partition-partition-1
17:09:51.735 [] [raft-server-0-raft-partition-partition-1] DEBUG io.zeebe.journal.file.SegmentedJournal - Closing segment: JournalSegment{id=1, version=1, index=1}
17:09:51.736 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
17:09:51.736 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.primitive.partition.impl.DefaultPartitionService - Stopped
17:09:51.736 [] [atomix-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Stopped
17:09:51.736 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Stopped
17:09:51.737 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Member deactivated: Member{id=0, address=0.0.0.0:7133, properties={brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MTMyBQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}
17:09:51.737 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Stopped
17:09:51.737 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Left
17:09:51.737 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Stopped
17:09:55.752 [] [ForkJoinPool.commonPool-worker-19] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
17:09:55.752 [] [atomix-cluster-0] INFO  io.atomix.cluster.AtomixCluster - Stopped
17:09:55.752 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [13/14]: membership and replication protocol closed in 4017 ms
17:09:55.752 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [14/14]: actor scheduler
17:09:55.752 [] [main] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers'
17:09:55.752 [] [main] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors'
17:09:55.753 [] [Broker-0-zb-actors-1] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors': closed successfully
17:09:55.753 [] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers': closed successfully
17:09:55.753 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [14/14]: actor scheduler closed in 1 ms
17:09:55.753 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 14 steps in 6062 ms.
17:09:55.753 [] [main] INFO  io.zeebe.broker.system - Broker shut down.
17:09:55.834 [] [main] INFO  io.zeebe.broker.test - Broker closing time: 6143
```

</details>

**Comment by aivinog1** [comment]
@npepinpe Hey, I fixed all review comments. Also, to remove the `SocketUtil` class I had to do some refactoring, and I made a rebase on the fresh develop branch to resolve conflicts.

**Review by npepinpe — CHANGES_REQUESTED** [review]
Thanks again for all the effort @aivinog1! I realize this is a lot so far, sorry about that, but we'll get there! :muscle: 

Some questions:

Sorry if I missed it, but why are we replacing `SocketUtil`? Instead of replacing everywhere with creating more objects and adding dependencies, can't we just replace it with:

```java
public final class SocketUtil {
  private static final String DEFAULT_FORMAT = "%s:%d";
  private static final String IPV6_FORMAT = "[%s]:%d";

  private SocketUtil() {}

  public static String toHostAndPortString(InetSocketAddress inetSocketAddress) {
    inetSocketAddress.getAddress()
    final String format =
        inetSocketAddress.getAddress() instanceof Inet6Address ? IPV6_FORMAT : DEFAULT_FORMAT;
    return String.format(format, inetSocketAddress.getHostString(), inetSocketAddress.getPort());
  }
}
```

We can reuse this in `Address`, but we can also use it elsewhere. I ask because:

- I wasn't expecting it tbh :sweat_smile:
- utils now depends on atomix-utils, which isn't the direction we want to go forward. I'd like to integrate Atomix code progressively into our homegrown modules instead of depending on them (so pull things out of Atomix into other modules).
-  Address is a data class that packages some stuff together, some more like a DTO, than it is about printing stuff. I like that we can keep the separation between both.
- Keeps the change small for now. I do think we should have a standardized approach to networking and working with addresses and so on, but I think that's outside the scope of the PR, especially considering it keeps growing :sweat_smile:

Regarding the `docker/utils/startup.sh`, I need to double check what could go wrong if we change it.

Finally, regarding the go stuff, I was under the impression just fixing the host/advertisedHost/etc. would solve it, and we wouldn't need to ignore the addresses in the golden files. Is that not correct?

I'll rebase the branch and push tomorrow so we can see how it runs in our CI environment.

File: atomix/core/src/test/java/io/atomix/core/AtomixRule.java [hunk 11]
```diff
@@ -101,7 +101,7 @@ private Address getAddress(final Integer memberId) {
         memberId,
         newId -> {
           final var nextInetAddress = SocketUtil.getNextAddress();
-          final var addressString = io.zeebe.util.SocketUtil.toHostAndPortString(nextInetAddress);
+          final var addressString = Address.from(nextInetAddress).toString();
           return Address.from(addressString);
```
[the remark this answers is not in the document]
Comment (aivinog1) [reply atomix/core/src/test/java/io/atomix/core/AtomixRule.java:105]: I'm going to revert this commit, and fix the logic of printing address in the `SocketUtil` class, so I'll leave this as it was :)

File: clients/java/src/main/java/io/zeebe/client/impl/response/BrokerInfoImpl.java [hunk 12]
```diff
@@ -58,7 +59,7 @@ public int getPort() {
 
   @Override
   public String getAddress() {
-    return String.format("%s:%d", host, port);
+    return new InetSocketAddress(host, port).toString();
```
[the remark this answers is not in the document]
Comment (aivinog1) [reply clients/java/src/main/java/io/zeebe/client/impl/response/BrokerInfoImpl.java:62]: Oops, this is not working as I expected 😅. I will fix that.

[the remark this answers is not in the document]
Comment (npepinpe) [reply clients/java/src/main/java/io/zeebe/client/impl/response/BrokerInfoImpl.java:62]: I guess we can't reuse SocketUtil here since the client is on Java 8. I'm fine with copying it to the client code as an internal class, though, if it's small enough.

File: clients/go/cmd/zbctl/main_test.go [hunk 13]
```diff
@@ -40,6 +40,11 @@ const (
...
+	ipv6RegexWithPort = `\[(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))]`
+	ipv4Regex         = `(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4})`
+	ipRegex           = ipv6Regex + `|` + ipv6RegexWithPort + `|` + ipv4Regex
```
[the remark this answers is not in the document]
Comment (aivinog1) [reply clients/go/cmd/zbctl/main_test.go:47]: Yes, I will remove that part :)

File: clients/go/cmd/zbctl/internal/commands/status.go [hunk 14]
```diff
@@ -136,3 +139,11 @@ func healthToString(health pb.Partition_PartitionBrokerHealth) string {
 		return unknownState
 	}
 }
+
+func formatIPAddress(ipAddress string) string {
```
[the remark this answers is not in the document]
Comment (aivinog1) [reply clients/go/cmd/zbctl/internal/commands/status.go:143]: Good point! Right now it works only with IP addresses, but I will fix that.

**Comment by aivinog1** [comment]
@npepinpe Hey, I've fixed all your review comments, can you take a look, please? :)

File: clients/go/internal/containersuite/containerSuite.go [hunk 15]
```diff
@@ -175,6 +175,7 @@ func (s *ContainerSuite) SetupSuite() {
 			Image:        s.ContainerImage,
 			ExposedPorts: []string{"26500"},
 			WaitingFor:   zeebeWaitStrategy{waitTime: s.WaitTime},
+			Env:          map[string]string{"ZEEBE_HOST": "0.0.0.0"},
```
Comment (npepinpe) [inline clients/go/internal/containersuite/containerSuite.go:178]: I know this is supported, but using `ZEEBE_HOST` is deprecated, and we should use `ZEEBE_BROKER_NETWORK_HOST` and `ZEEBE_BROKER_NETWORK_ADVERTISEDHOST` (since this is what shows up in the topology).

File: clients/java/src/main/java/io/zeebe/client/impl/util/SocketUtil.java [hunk 16]
```diff
@@ -0,0 +1,32 @@
...
+
+public final class SocketUtil {
+  private static final String DEFAULT_FORMAT = "%s:%d";
+  private static final String IPV6_FORMAT = "[%s]:%d";
+
+  private SocketUtil() {}
+
+  public static String toHostAndPortString(InetSocketAddress inetSocketAddress) {
+    final String format =
+        inetSocketAddress.getAddress() instanceof Inet6Address ? IPV6_FORMAT : DEFAULT_FORMAT;
```
Comment (npepinpe) [inline clients/java/src/main/java/io/zeebe/client/impl/util/SocketUtil.java:29]: Hm, so I guess if the address is unresolved yet and we return null, it will return as an IPv4 address? Fair enough.

What if I have a domain which resolves to an IPv6 address? Is it going to print `[foobar.com]:80`?

File: util/src/main/java/io/zeebe/util/SocketUtil.java [hunk 17]
```diff
@@ -0,0 +1,24 @@
...
+
+public final class SocketUtil {
+  private static final String DEFAULT_FORMAT = "%s:%d";
+  private static final String IPV6_FORMAT = "[%s]:%d";
+
+  private SocketUtil() {}
+
+  public static String toHostAndPortString(InetSocketAddress inetSocketAddress) {
+    final String format =
+        inetSocketAddress.getAddress() instanceof Inet6Address ? IPV6_FORMAT : DEFAULT_FORMAT;
```
Comment (npepinpe) [inline util/src/main/java/io/zeebe/util/SocketUtil.java:21]: Same comment as above.

File: clients/java/src/main/java/io/zeebe/client/impl/util/SocketUtil.java [hunk 18]
```diff
@@ -0,0 +1,32 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.zeebe.client.impl.util;
+
+import java.net.Inet6Address;
+import java.net.InetSocketAddress;
+
+public final class SocketUtil {
```
Comment (npepinpe) [inline clients/java/src/main/java/io/zeebe/client/impl/util/SocketUtil.java:21]: Can we add a comment explaining why it's duplicated? i.e. `utils/` is not a Java 8 module so we can't directly depend from it, hence the duplication. And possibly if it got more complex we'd need to figure out how to share it :sweat_smile:

**Review by npepinpe — CHANGES_REQUESTED** [review]
Thanks for this again! I will rebase and push to CI to see how it is.

Some random notes:

- can we reuse SocketUtil in `Address#toString()`?

File: clients/java/src/main/java/io/zeebe/client/impl/util/SocketUtil.java (hunk 16 above)
Comment (aivinog1) [reply clients/java/src/main/java/io/zeebe/client/impl/util/SocketUtil.java:29]: Hm, good point! I'll create tests for that :)

**Comment by aivinog1** [comment]
@npepinpe Hey, I've fixed all your review comments, can you take another look, please? :)

**Comment by aivinog1** [comment]
@npepinpe I see that the `golangci-lint` action is failed, but the root cause of it is a timeout. Can you rerun it, please? :)

File: clients/java/src/main/java/io/zeebe/client/impl/util/SocketUtil.java [hunk 19]
```diff
@@ -26,7 +31,16 @@ private SocketUtil() {}
 
   public static String toHostAndPortString(InetSocketAddress inetSocketAddress) {
     final String format =
-        inetSocketAddress.getAddress() instanceof Inet6Address ? IPV6_FORMAT : DEFAULT_FORMAT;
+        isHostOrIpv4Address(inetSocketAddress.getAddress()) ? DEFAULT_FORMAT : IPV6_FORMAT;
     return String.format(format, inetSocketAddress.getHostString(), inetSocketAddress.getPort());
   }
+
+  private static boolean isHostOrIpv4Address(final InetAddress address) {
+    if (address != null) {
```
Comment (npepinpe) [inline clients/java/src/main/java/io/zeebe/client/impl/util/SocketUtil.java:39]: Might read better with a guard clause and then the rest under, e.g.

```java
if (address == null) {
  return true;
}

return (address instanceof Inet4Address) || address.getHostAddress().equals(address.getHostName());
```

File: util/src/test/java/io/zeebe/util/SocketUtilTest.java [hunk 20]
```diff
@@ -0,0 +1,73 @@
...
+
+public class SocketUtilTest {
+
+  @Test
+  public void shouldPrintDnsAndPort() {
+    final String host = "foo.barr";
+    final int port = 1234;
+    final String hostAndPortString =
+        SocketUtil.toHostAndPortString(InetSocketAddress.createUnresolved(host, port));
+    assertThat(hostAndPortString).isEqualTo(String.format("%s:%d", host, port));
```
Comment (npepinpe) [inline util/src/test/java/io/zeebe/util/SocketUtilTest.java:27]: Let's just write "foo.barr:1234". Having hard coded here will help us better visualize what's the expected output. Plus the tests are simple/small enough that if we change the args we can easily change the values. Same for all the other tests.

File: util/src/test/java/io/zeebe/util/SocketUtilTest.java [hunk 21]
```diff
@@ -0,0 +1,73 @@
...
+import static org.assertj.core.api.Assertions.assertThat;
+
+import java.net.Inet4Address;
+import java.net.Inet6Address;
+import java.net.InetAddress;
+import java.net.InetSocketAddress;
+import java.net.UnknownHostException;
+import org.junit.Test;
+
+public class SocketUtilTest {
```
Comment (npepinpe) [inline util/src/test/java/io/zeebe/util/SocketUtilTest.java:19]:
```suggestion
public final class SocketUtilTest {
```

Comment (npepinpe) [reply util/src/test/java/io/zeebe/util/SocketUtilTest.java:19]: Can we also add a comment about how it relies on `-Djdk.net.hosts.file=src/test/resources/test-hosts` as specified in the pom? Meaning it probably won't work via the IDE I guess.

Actually, is there a way we could make this work so it would also work in the IDE? Would mocking it be the only way? I'm not asking for it, as for such a utility class I think it'd make the test too artificial...but maybe you're aware of something I'm not :slightly_smiling_face:

File: util/pom.xml [hunk 22]
```diff
@@ -102,5 +102,16 @@
         <filtering>true</filtering>
       </resource>
     </resources>
+    <plugins>
+      <plugin>
+        <groupId>org.apache.maven.plugins</groupId>
+        <artifactId>maven-surefire-plugin</artifactId>
+        <configuration combine.children="append">
+          <argLine combine.children="append">
```
Comment (npepinpe) [inline util/pom.xml:110]: Let's add a comment that specifies this is for the SocketUtilTest and that you can look there to see why it's necessary.

**Comment by npepinpe** [comment]
I've pushed the latest changes, and I'll check on CI tomorrow.

File: util/src/test/java/io/zeebe/util/SocketUtilTest.java (hunk 21 above)
Comment (aivinog1) [reply util/src/test/java/io/zeebe/util/SocketUtilTest.java:19]: Hey, I was a little bit thinking about this and consider the next options:
1. Use reflection to actually set proper implementation of the `java.net.InetAddress.NameService`. I think this is a bit ugly, I would like not to do this 😅
2. We can create a shared IDEA configuration, that actually sets a correct option. But it hard to maintain: you can't put this on CI, if you will rename/move the file you can't run this configuration any longer until you will fix it.

**Comment by aivinog1** [comment]
@npepinpe Hey, I've fixed all your review comments besides the opportunity to run tests with the system property from IDE. Can you take a look, please? :)

**Comment by npepinpe** [comment]
We have 2 tests failing:

### io.zeebe.broker.it.client.ClientExceptionHandlingTest#shouldContainRootCauses

<details><summary>Error</summary>

```
Error
Expecting throwable message:
  "connect(..) failed: Address family not supported by protocol: localhost/0:0:0:0:0:0:0:1:1234"
to contain:
  "Connection refused:"
but did not.
Throwable that failed the check:
io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: localhost/0:0:0:0:0:0:0:1:1234
Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
 at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
 at io.netty.channel.unix.Socket.connect(Socket.java:240)
 at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:736)
 at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:721)
 at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:563)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
 at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
 at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
 at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
 at io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:150)
 at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
 at io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
 at io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:538)
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Logs</summary>

```
Standard Output
20:07:55.013 [] [main] INFO  io.zeebe.test - Test started: shouldContainRootCauses(io.zeebe.broker.it.client.ClientExceptionHandlingTest)
20:07:55.015 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7244 for test fork 2 with range PortRange{host='localhost', basePort=7225, maxOffset=100, currentOffset=120}
20:07:55.015 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7245 for test fork 2 with range PortRange{host='localhost', basePort=7225, maxOffset=100, currentOffset=121}
20:07:55.015 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7246 for test fork 2 with range PortRange{host='localhost', basePort=7225, maxOffset=100, currentOffset=122}
20:07:55.015 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7247 for test fork 2 with range PortRange{host='localhost', basePort=7225, maxOffset=100, currentOffset=123}
20:07:55.015 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7248 for test fork 2 with range PortRange{host='localhost', basePort=7225, maxOffset=100, currentOffset=124}
20:07:55.015 [] [main] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/f319d4e8-b4ff-443b-8093-030255cd7844
20:07:55.016 [] [main] INFO  io.zeebe.broker.system - Version: 1.0.0-SNAPSHOT
20:07:55.016 [] [main] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 7246,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7246,
      "address" : "0.0.0.0:7246",
      "advertisedAddress" : "0.0.0.0:7246"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 7247,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7247,
      "address" : "0.0.0.0:7247",
      "advertisedAddress" : "0.0.0.0:7247"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 7248,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7248,
      "address" : "0.0.0.0:7248",
      "advertisedAddress" : "0.0.0.0:7248"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 1,
    "clusterSize" : 1,
    "clusterName" : "zeebe-cluster",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : null,
    "directory" : "/tmp/f319d4e8-b4ff-443b-8093-030255cd7844/data",
    "logSegmentSize" : "128MB",
    "snapshotPeriod" : "PT5M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.99,
    "diskUsageCommandWatermark" : 0.97,
    "diskUsageMonitoringInterval" : "PT1S",
    "logSegmentSizeInBytes" : 134217728,
    "freeDiskSpaceCommandWatermark" : 0,
    "freeDiskSpaceReplicationWatermark" : 0
  },
  "exporters" : {
    "test-recorder" : {
      "jarPath" : null,
      "className" : "io.zeebe.test.util.record.RecordingExporter",
      "args" : null,
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 7244,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:7247",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 7245,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT0.1S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      }
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "initialized" : true,
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "0MB",
    "disableExplicitRaftFlush" : false,
    "detectReprocessingInconsistency" : false,
    "rocksdb" : {
      "columnFamilyOptions" : { },
      "enableStatistics" : false,
      "memoryLimit" : "512MB",
      "maxOpenFiles" : -1,
      "maxWriteBufferNumber" : 6,
      "minWriteBufferNumberToMerge" : 3,
      "ioRateBytesPerSecond" : 0,
      "disableWal" : false
    },
    "maxAppendBatchSizeInBytes" : 32768
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
20:07:55.017 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/14]: actor scheduler
20:07:55.017 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/14]: actor scheduler started in 0 ms
20:07:55.017 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/14]: membership and replication protocol
20:07:55.019 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/14]: membership and replication protocol started in 1 ms
20:07:55.019 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/14]: command api transport
20:07:55.021 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:7246
20:07:55.021 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
20:07:55.022 [] [main] DEBUG io.zeebe.broker.system - Bound command API to [0.0.0.0:7246], using advertised address 0.0.0.0:7246 
20:07:55.022 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/14]: command api transport started in 3 ms
20:07:55.022 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/14]: command api handler
20:07:55.022 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/14]: command api handler started in 0 ms
20:07:55.022 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/14]: subscription api
20:07:55.022 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/14]: subscription api started in 0 ms
20:07:55.022 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services
20:07:55.022 [] [main] INFO  io.atomix.core.Atomix - 1.0.0-SNAPSHOT (revision e0256d built on 2021-03-28 19:57:08)
20:07:55.024 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:7247
20:07:55.024 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
20:07:55.026 [] [netty-unicast-event-nio-client-0] INFO  io.atomix.cluster.messaging.impl.NettyUnicastService - UDP server listening for connections on 0.0.0.0:7247
20:07:55.026 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
20:07:55.026 [] [atomix-cluster-0] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - Nodes from discovery service []
20:07:55.026 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
20:07:55.026 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
20:07:55.027 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started
20:07:55.027 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
20:07:55.027 [] [atomix-0] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-1} - Starting server for partition PartitionId{id=1, group=raft-partition}
20:07:55.034 [] [atomix-0] DEBUG io.zeebe.journal.file.SegmentedJournal - Created segment: JournalSegment{id=1, version=1, index=1}
20:07:55.037 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
20:07:55.037 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Single member cluster. Transitioning directly to candidate.
20:07:55.037 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE
20:07:55.037 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.raft.roles.FollowerRole$$Lambda$301/0x000000084039f040@f93acd3 not registered
20:07:55.038 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Single member cluster. Transitioning directly to leader.
20:07:55.043 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Set term 1
20:07:55.045 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Voted for 0
20:07:55.045 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to LEADER
20:07:55.045 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 0
20:07:55.048 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 1. RaftServer is ready only after it has committed events upto this index
20:07:55.049 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server join completed. Waiting for the server to be READY
20:07:55.049 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server started successfully!
20:07:55.049 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-1} - Successfully started server for partition PartitionId{id=1, group=raft-partition} in 22ms
20:07:55.049 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
20:07:55.049 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.primitive.partition.impl.DefaultPartitionService - Started class io.atomix.primitive.partition.impl.DefaultPartitionService
20:07:55.049 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services started in 27 ms
20:07:55.049 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/14]: topology manager
20:07:55.049 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/14]: topology manager started in 0 ms
20:07:55.049 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/14]: embedded gateway
20:07:55.050 [] [main] INFO  io.zeebe.gateway - Version: 1.0.0-SNAPSHOT
20:07:55.051 [] [main] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 7244,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "0.0.0.0:7247",
    "requestTimeout" : "PT15S",
    "clusterName" : "zeebe-cluster",
    "memberId" : "gateway",
    "host" : "0.0.0.0",
    "port" : 7245,
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "0.0.0.0",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  },
  "longPolling" : {
    "enabled" : true
  },
  "initialized" : true,
  "enable" : true
}
20:07:55.051 [GatewayTopologyManager] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Received new broker BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=1, replicationFactor=1, partitionRoles={}, partitionLeaderTerms={}, partitionHealthStatuses={}, version=1.0.0-SNAPSHOT}.
20:07:55.054 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/14]: embedded gateway started in 5 ms
20:07:55.054 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/14]: monitoring services
20:07:55.054 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [9/14]: monitoring services started in 0 ms
20:07:55.054 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/14]: disk space monitor
20:07:55.054 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/14]: disk space monitor started in 0 ms
20:07:55.054 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [11/14]: leader management request handler
20:07:55.054 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [11/14]: leader management request handler started in 0 ms
20:07:55.054 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [12/14]: zeebe partitions
20:07:55.054 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
20:07:55.055 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER in term 1
20:07:55.055 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition 1 closed all previous open resources, before transitioning.
20:07:55.055 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {logstream-raft-partition-partition-1=HEALTHY}
20:07:55.184 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/f319d4e8-b4ff-443b-8093-030255cd7844/data/raft-partition/partitions/1/runtime'.
20:07:55.250 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
20:07:55.250 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
20:07:55.250 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@44680592)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@5126e91f, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@f226f98, configuration: Configuration(false)]
20:07:55.251 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
20:07:55.252 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@4466f4d8)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@40263d53, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@262e5a59, configuration: Configuration(false)]
20:07:55.252 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@3a6cbfab)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@495f5c0a, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@38623cd7, configuration: Configuration(false)]
20:07:55.262 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition 1 transition complete, installed 12 resources!
20:07:55.262 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
20:07:55.262 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
20:07:55.262 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovered exporter 'Broker-0-Exporter-1' from snapshot at lastExportedPosition -1
20:07:55.262 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'test-recorder'
20:07:55.262 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 208 ms
20:07:55.262 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {Partition-1=HEALTHY}
20:07:55.262 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 208 ms.
20:07:55.262 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={SBE_UNKNOWN=true, EVENT=true, COMMAND_REJECTION=true, NULL_VAL=true, COMMAND=true}, acceptValueTypes={ERROR=true, PROCESS_INSTANCE_RESULT=true, TIMER=true, VARIABLE=true, PROCESS_INSTANCE_SUBSCRIPTION=true, NULL_VAL=true, PROCESS_INSTANCE_CREATION=true, JOB_BATCH=true, INCIDENT=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, PROCESS=true, SBE_UNKNOWN=true, MESSAGE=true, VARIABLE_DOCUMENT=true, MESSAGE_SUBSCRIPTION=true, DEPLOYMENT_DISTRIBUTION=true, JOB=true, DEPLOYMENT=true, PROCESS_INSTANCE=true}}
20:07:55.262 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [12/14]: zeebe partitions started in 208 ms
20:07:55.262 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] INFO  io.zeebe.broker.system - Partition-1 recovered, marking it as healthy
20:07:55.262 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [13/14]: register diskspace usage listeners
20:07:55.262 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [13/14]: register diskspace usage listeners started in 0 ms
20:07:55.262 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [14/14]: upgrade manager
20:07:55.262 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [14/14]: upgrade manager started in 0 ms
20:07:55.262 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 14 steps in 245 ms.
20:07:55.263 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Open exporter with id 'test-recorder'
20:07:55.276 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MjQ2BQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}
20:07:55.277 [GatewayTopologyManager] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER}, terms {1=1} and health {1=HEALTHY}.
20:07:55.363 [] [main] INFO  io.zeebe.broker.test - 
====
Broker startup time: 349
====
20:07:55.365 [] [main] INFO  io.zeebe.broker.test - 
====
Client startup time: 2
====
20:07:55.377 [] [main] INFO  io.zeebe.broker.test - Client Rule assumption: Test execution time: 12
20:07:55.377 [] [main] INFO  io.zeebe.broker.test - Client closing time: 0
20:07:55.378 [] [main] INFO  io.zeebe.test.records - Test failed, following records were exported:
20:07:55.378 [] [main] INFO  io.zeebe.broker.test - Test execution time: 15
20:07:55.379 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [1/14]: upgrade manager
20:07:55.379 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [1/14]: upgrade manager closed in 0 ms
20:07:55.379 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [2/14]: register diskspace usage listeners
20:07:55.379 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [2/14]: register diskspace usage listeners closed in 0 ms
20:07:55.379 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [3/14]: zeebe partitions
20:07:55.379 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1
20:07:55.379 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe Partition 1.
20:07:55.379 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] ERROR io.zeebe.broker.system - ZeebePartition-1 failed, marking it as unhealthy
20:07:55.379 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {ZeebePartition-1=UNHEALTHY, Raft-1=HEALTHY, Broker-0-StreamProcessor-1=HEALTHY, logstream-raft-partition-partition-1=HEALTHY}
20:07:55.379 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ExporterDirector
20:07:55.379 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] ERROR io.zeebe.broker.system - Partition-1 failed, marking it as unhealthy
20:07:55.379 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {Partition-1=UNHEALTHY}
20:07:55.379 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Closed exporter director 'Broker-0-Exporter-1'.
20:07:55.379 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ExporterDirector closed successfully
20:07:55.379 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RocksDB metric timer
20:07:55.379 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RocksDB metric timer closed successfully
20:07:55.379 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AsyncSnapshotDirector
20:07:55.379 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AsyncSnapshotDirector closed successfully
20:07:55.380 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StreamProcessor
20:07:55.380 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
20:07:55.380 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StreamProcessor closed successfully
20:07:55.380 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ZeebeDb
20:07:55.380 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ZeebeDb closed successfully
20:07:55.380 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RegisterSnapshotListener
20:07:55.380 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RegisterSnapshotListener closed successfully
20:07:55.380 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: LogDeletionService
20:07:55.380 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: LogDeletionService closed successfully
20:07:55.380 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StateController
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/f319d4e8-b4ff-443b-8093-030255cd7844/data/raft-partition/partitions/1/runtime'.
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StateController closed successfully
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: SnapshotReplication
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: SnapshotReplication closed successfully
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RaftLogReader
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RaftLogReader closed successfully
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: logstream
20:07:55.410 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream logstream-raft-partition-partition-1
20:07:55.410 [logstream-raft-partition-partition-1-write-buffer] [Broker-0-zb-actors-0] DEBUG io.zeebe.dispatcher - Dispatcher closed
20:07:55.410 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-1 close 2 readers
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: logstream closed successfully
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AtomixLogStorage
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AtomixLogStorage closed successfully
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition 1 closed all previous open resources, before transitioning.
20:07:55.410 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition 1 transition complete, installed 0 resources!
20:07:55.411 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1 closed in 32 ms
20:07:55.411 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions succeeded. Closed 1 steps in 32 ms.
20:07:55.411 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [3/14]: zeebe partitions closed in 32 ms
20:07:55.411 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [4/14]: leader management request handler
20:07:55.411 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [4/14]: leader management request handler closed in 0 ms
20:07:55.411 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [5/14]: disk space monitor
20:07:55.411 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [5/14]: disk space monitor closed in 0 ms
20:07:55.411 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [6/14]: monitoring services
20:07:55.411 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [6/14]: monitoring services closed in 0 ms
20:07:55.411 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [7/14]: embedded gateway
20:07:55.412 [] [main] DEBUG io.zeebe.gateway - Closing gateway broker client ...
20:07:55.412 [] [main] DEBUG io.zeebe.gateway - topology manager closed
20:07:55.412 [] [main] DEBUG io.zeebe.gateway - Gateway broker client closed.
20:07:55.412 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [7/14]: embedded gateway closed in 1 ms
20:07:55.412 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [8/14]: topology manager
20:07:55.412 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [8/14]: topology manager closed in 0 ms
20:07:55.412 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [9/14]: cluster services
20:07:55.412 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [9/14]: cluster services closed in 0 ms
20:07:55.412 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [10/14]: subscription api
20:07:55.412 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [10/14]: subscription api closed in 0 ms
20:07:55.412 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [11/14]: command api handler
20:07:55.413 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [11/14]: command api handler closed in 1 ms
20:07:55.413 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [12/14]: command api transport
20:07:55.527 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MjQ2BQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}
20:07:57.422 [] [ForkJoinPool.commonPool-worker-5] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
20:07:57.422 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [12/14]: command api transport closed in 2009 ms
20:07:57.422 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [13/14]: membership and replication protocol
20:07:57.422 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
20:07:57.423 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.zeebe.LogCompactor - LogCompactor{raft-partition-partition-1} - Closing the log compactor raft-partition-partition-1
20:07:57.423 [] [raft-server-0-raft-partition-partition-1] DEBUG io.zeebe.journal.file.SegmentedJournal - Closing segment: JournalSegment{id=1, version=1, index=1}
20:07:57.424 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
20:07:57.424 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.primitive.partition.impl.DefaultPartitionService - Stopped
20:07:57.424 [] [atomix-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Stopped
20:07:57.424 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Stopped
20:07:57.424 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Member deactivated: Member{id=0, address=0.0.0.0:7247, properties={brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MjQ2BQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}
20:07:57.424 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Stopped
20:07:57.424 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Left
20:07:57.424 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Stopped
20:08:01.440 [] [ForkJoinPool.commonPool-worker-5] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
20:08:01.440 [] [atomix-cluster-0] INFO  io.atomix.cluster.AtomixCluster - Stopped
20:08:01.441 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [13/14]: membership and replication protocol closed in 4019 ms
20:08:01.441 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [14/14]: actor scheduler
20:08:01.441 [] [main] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers'
20:08:01.441 [] [main] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors'
20:08:01.441 [] [Broker-0-zb-actors-1] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors': closed successfully
20:08:01.442 [] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers': closed successfully
20:08:01.442 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [14/14]: actor scheduler closed in 1 ms
20:08:01.442 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 14 steps in 6064 ms.
20:08:01.442 [] [main] INFO  io.zeebe.broker.system - Broker shut down.
20:08:01.504 [] [main] INFO  io.zeebe.broker.test - Broker closing time: 6126
```

</details>

### io.zeebe.broker.it.startup.MultiPartitionRecoveryTest

This one also failed, but I can't see it because it produced so much logs that the XML is all broken :sweat_smile:  I can see from the broken XML that it timed out. I can't paste the logs since it's too long, but I can attach them.

[io.zeebe.broker.it.startup.MultiPartitionRecoveryTest-it-testrun-output.txt](https://github.com/camunda-cloud/zeebe/files/6222161/io.zeebe.broker.it.startup.MultiPartitionRecoveryTest-it-testrun-output.txt)

**Comment by aivinog1** [comment]
@npepinpe I have to say that both of these tests are actually passing on my machine 😅. I need more time to investigate this (I think that the root cause of this issue is building the project in the DinD).

**Comment by npepinpe** [comment]
I don't think it's DinD related, as neither of these tests use Docker :slightly_smiling_face: They start the broker directly in the same process, so it sounds like something else to me.

Also, there were tons of changes since you started this PR, you probably want to rebase against develop soon :sweat_smile:

**Comment by aivinog1** [comment]
@npepinpe, okay, let's try to pass it with CI after I will rebase on the fresh develop :)

**Comment by aivinog1** [comment]
@npepinpe Done, let's try CI again :)

**Comment by npepinpe** [comment]
Hm, ClientExceptionHandlingTest is still failing with the same error. It seems like it resolves the name to IPv6 loop back but doesn't add [] around, such that it fails to connect. What's weird is this test doesn't use the DinD sibling or start any containers...it is running in a container, however, but still... :thinking:

**Comment by npepinpe** [comment]
TIL: Netty's NetUtil class (and we have a hard dependency on Netty that's not going away anytime soon :smile:) already has a method `toSocketAddressString` which returns the correct `host:port` or `ipv4:port` or `[ipv6]:port` from a given hostname and port, or `InetSocketAddress`. So we could probably get rid of SocketUtil everywhere for that :+1:

**Comment by npepinpe** [comment]
BTW regarding the failing test, I actually ran into the same issue locally (but not with Zeebe :sweat_smile:). So if you have IPv4 and IPv6 configured locally, gRPC will resolve "localhost" to both 127.0.0.1 and ::1, and will prioritize IPv6 over IPv4 (which is more or less standard to allow IPv6 to eventually take over). However, we're only listening on IPv4, so the connection is refused.

**Comment by aivinog1** [comment]
Hi @npepinpe! I've tried to reproduce this falling test but without luck (MBP 2019/16, Mac OS 11.2.3) :( Maybe we should just add the JVM option `java.net.preferIPv4Stack` as true in the tests?

**Comment by aivinog1** [comment]
@npepinpe Hey, I move from the `SocketUtil` to the `NetUtil` and set the IPv4 stack for surefire tests. Can you take a look, please? :)

**Comment by aivinog1** [comment]
I even tried to run the `ClientExceptionHandlingTest` in the Docker environment with IPv6 (special thanks to the new feature of IDEA 2021.1 😊) but this test still works 🤷🏻‍♂️

**Comment by npepinpe** [comment]
It fails locally, so I can have a look at it :smile:

**Comment by aivinog1** [comment]
@npepinpe Hi, many thanks :)

File: qa/integration-tests/pom.xml [hunk 23]
```diff
@@ -243,7 +249,7 @@
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-plugin</artifactId>
         <configuration>
-          <argLine>-Xmx2048m -XX:MaxDirectMemorySize=4g</argLine>
+          <argLine>-Xmx2048m -XX:MaxDirectMemorySize=4g -Djava.net.preferIPv4Stack=true</argLine>
```
Comment (npepinpe) [inline qa/integration-tests/pom.xml:252]:
```suggestion
          <!--
            as our in-house CI does not enable IPv6, clients not running in a Testcontainer-managed
            container will not be able to use IPv6; as such, ensure we always prefer IPv4 when
            resolving host names
            -->
          <argLine>-Xmx2048m -XX:MaxDirectMemorySize=4g -Djava.net.preferIPv4Stack=true</argLine>
```

**Review by npepinpe — CHANGES_REQUESTED** [review]
You were right - our in-house CI runs in a k8s cluster, where each build is a job, and the job has one maven container and one docker-in-docker container (for Testcontainers). While IPv6 was enabled for the docker-in-docker container (and as such for all containers we start there), it's disabled on the maven container. This isn't something we can control here directly unfortunately (AFAIK), so let's add the param you added to the QA module. I'd just ask we add the comment I suggested so everyone knows why we're doing this, then please rebase the commits logically, and ping me again so we can run CI one last time after rebase (just in case) before merging.

thanks for your patience, that was a long one :smile:

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java [hunk 24]
```diff
@@ -0,0 +1,150 @@
...
+import java.util.stream.IntStream;
+import org.junit.After;
+import org.junit.Before;
+import org.junit.Rule;
+import org.junit.Test;
+import org.testcontainers.containers.GenericContainer;
+import org.testcontainers.containers.Network;
+import org.testcontainers.utility.DockerImageName;
+
+public class Ipv6IntegrationTest {
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/Ipv6IntegrationTest.java:33]: Can we make this a junit5 test? Just add the following dependency in qa/integration-tests/pom.xml:

```xml
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
```

From there, we can turn this into a junit5 and add the following annotation to the test class:

```java
@EnabledOnOs(OS.LINUX)
class Ipv6IntegrationTest {
```

Since the Docker docs specify that IPv6 only works on Linux.

**Review by npepinpe — CHANGES_REQUESTED** [review]

**Comment by aivinog1** [comment]
@npepinpe Hey, I've rebased on fresh develop, squashed my commits, and fixed your review comments. Can you take a look, please? :)

**Comment by aivinog1** [comment]
@npepinpe Actually, I want to say many thanks for such comprehended, picky (in good meaning 😅), straightforward review comments. You are the best! I see some improvement points of my skills in such good review comments 🙂

**Review by npepinpe — APPROVED** [review]
Looks good! Thanks again for this!
