### PR TITLE
fix: send a request to all partitions before marking scaling as completed

### LINKED ISSUE #37004: Scaling is marked as completed before all partitions update their routing state
### 

### 

### 

### 

### Description

The topology response indicates the partition scaling is completed - that means all operations are applied and completed. However, some partitions still doesn't have the new partitions in the `routingState.currentPartitions()`. This is because this is updated by commands from partition 1 sent via the command distribution and there can be delay. So the other partitions will only eventually update their routing state. As a result, the backup request fails on those partitions, even though according to the topology response scaling is completed.

This is not a good UX because, backup request fails with message "Scaling is in progress", but when we query the status of scaling it is completed.

### Steps to reproduce

Reproducible by IT tests
1. Scale cluster
2. Wait until scaling is completed by querying actuator response
3. Take backup

If you wait long enough between step 2 and 3, backup succeeds because eventually all partitions have updated their state. 

### Current behavior

.

### Expected behavior

1. Backups can be taken immediately after scaling is marked as completed
2. Scaling is only completed after all partitions have updated their state

### Environment

SM

### Version

- 8.8-SNAPSHOT

### Rootcause

_No response_

### Solution ideas

One way to solve is this to add an operation to await until all partitions has updated their routing state.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by entangled90**
## Description

To avoid having a partition not being aware of the new partitions, check
that the routing state is up to date in all partitions.

Start from Protocol.DEPLOYMENT_PARTITION and stop with the newly started
partitions.
The requests are sent one at a time, following the partitionId order, so
that the first partition is invoked first.
If the first partition is not ready yet, requests to other partitions
are not sent.

### New api in `CompletableActorFuture`

`CompletableActorFuture.traverseIgnoring` has been added, following what's already available in `FuturesUtil` for `java.util.concurrent.CompletableFuture`. 

However, it's not easy to port this functionality to `ActorFuture` since it's a static method.

## Checklist

- [X] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #37004

### CODE REVIEW

File: zeebe/scheduler/src/test/java/io/camunda/zeebe/scheduler/future/CompletableActorFutureTest.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+                          new RuntimeException("Expected")),
+                  EXECUTOR))
+          .isDone();
+    }
+
+    @Test
+    public void shouldRunAllFuturesSequentially() {
+      // given
+      final var count = 1000;
+      final var map = new CopyOnWriteArrayList<>();
```
Comment (deepthidevaki) [inline zeebe/scheduler/src/test/java/io/camunda/zeebe/scheduler/future/CompletableActorFutureTest.java]: The name `map` for a list is confusing :smile:

**Review by deepthidevaki — APPROVED** [review]
:rocket: 

:x: Could you update the [test that reproduced this bug](https://github.com/camunda/camunda/blob/949603fc846815123e6c30fd2af32586dcf1e61d/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/dynamic/ScaleUpPartitionsTest.java#L396-L403)? The expectation is that the first attempt of taking backup succeeds. No need to repeat until success with in awaitiliy.

:thought_balloon: Should we have an operation for each partition to wait for the status instead of having one operation that queries all partitions? One issue with having one operation for all partitions is that a failure midway requires querying all partitions again. In the worst case scenario - such as in a high load situation, we may end up retrying the query for a long time because each time a different partition rejects the request due to hitting write limit. On the other hand, adding one operation per partition might not be worth it because this would become unnecessary when we have message relocation implemented because waiting for message relocation to complete would indirectly cover waiting for redistribution probably.

**Comment by entangled90** [comment]
Nice catch! After removing it the test passed 10 times in a row:
image

Regarding splitting it into multiple operation I'm not sure what's the best way forward. This is surely the simplest approach.
Should we add this intent to the whitelisted intents?

**Comment by deepthidevaki** [comment]
> Should we add this intent to the whitelisted intents?

That would be enough for now I guess. Is there a chance of partitions getting spammed by this request?

File: zeebe/scheduler/src/test/java/io/camunda/zeebe/scheduler/future/CompletableActorFutureTest.java (hunk 1 above)
Comment (entangled90) [reply zeebe/scheduler/src/test/java/io/camunda/zeebe/scheduler/future/CompletableActorFutureTest.java]: good point, I changed the type to `ArrayBlockingQueue` as well

**Comment by entangled90** [comment]
No AFAIK it's used only for this operation.
