### PR TITLE
Only resolve ACTIVE incidents in batch incident resolution

### LINKED ISSUE #40822: Batch resolve incident should only identify active incidents
### 

### 

, 

### 

### 

### Description

The batch operation to resolve incidents identifies ALL incidents related to a process instance as the items to handle. It should only handle ACTIVE incidents.

### Steps to reproduce

1. With Zeebe batch operations, resolve incidents for (a) process instance(s) (the incidents must "return", so new incidents are created)
2. With Zeebe batch operations, resolve incidents for the same process instance(s) again

### Current behavior

The number of items is twice the number of existing incidents

### Expected behavior

The number of items is exactly the number of existing incidents

### Workaround

None

### Environment

SaaS & SM

### Version

- Component Version: 8.8.x & 8.9.x

### Rootcause

In `io.camunda.zeebe.engine.processing.batchoperation.itemprovider.IncidentItemProvider::getIncidentItemsOfProcessInstanceKeys`, we don't restrict the state of incidents to fetch, so we're identifiyng resolved ones as well.

### Solution ideas

FIlter by ACTIVE incident state in that method as well.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

Only considers ACTIVE incidents when resolving incidents in a batch.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #40822

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java [hunk 1]
```diff
@@ -89,6 +90,7 @@ private Set<Item> getIncidentItemsOfProcessInstanceKeys(
           new IncidentFilter.Builder()
               .processInstanceKeyOperations(
                   FilterUtil.mapDefaultToOperation(processInstanceKeysBatch))
+              .states(IncidentState.ACTIVE.name())
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java:93]: Not sure how we never done that before🙈

**Review by mustafadagher — APPROVED** [review]
Good catch! Thanks @tmetzke!

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java (hunk 1 above)
Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java:93]: Ah well 🤷

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java [hunk 2]
```diff
@@ -89,6 +90,7 @@ private Set<Item> getIncidentItemsOfProcessInstanceKeys(
...
               .build();
       incidents.addAll(fetchIncidentItems(filter, pageSize));
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java:95]: 💭 @tmetzke about this actually, I was just thinking. Could we assume we can get all incidents for a certain process instance from zeebe state, do we need a secondary storage query for this?

Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java:95]: I did actually wonder about the same thing, to be honest. I didn't want to refactor it that much in this fix PR as it messes with the inner workings of how to handle incidents in a batch. Happy to have a look together or try to hack it that way, though, if you like.

I could imagine that to work, if the item provider has access to state and such.

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java:95]: it's not a pushing matter now, I wasn't suggesting that it was needed in this PR. But I just came to realize it.

Happy to pair on it together when we have a breathing space, hopefully next week or the week after?

Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java:95]: Sounds good to me. Can you pick a time slot, maybe an hour for the two of us? Just create an appointment for us and we'll try to hack it?

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/itemprovider/IncidentItemProvider.java:95]: Cool! I created an issue https://github.com/camunda/camunda/issues/40840 to track it. And will book something for us to look at it.
