### PR TITLE
Fix flaky test in retries logic (#31090)

### LINKED ISSUE #31090: `ProcessInstanceAndFlowNodeInstanceSearchTest` is flaky
**Summary**

- How often does the test fail? - 10 times in the last 2 days
- Does it block your work? - blocks PRs and merge queues
- Do we suspect that it is a real failure? - only flaky in RDBMS H2 tests, so maybe not

Might be related to https://github.com/camunda/camunda/issues/30892. Either the related fix didn't capture everything, or it's a different root cause.

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
shouldQueryProcessInstancesByHasRetriesLeft (Flaky Test): io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceSearchTest
org.opentest4j.AssertionFailedError: 

expected: 2
 but was: 1
	at io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceSearchTest.shouldQueryProcessInstancesByHasRetriesLeft(ProcessInstanceAndFlowNodeInstanceSearchTest.java:1589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
</details>

**Hypotheses**

none

**Logs**

Example build: https://github.com/camunda/camunda/actions/runs/14472216725/attempts/1
IT run logs: [Test results for \[IT\] RDBMS - H2.zip](https://github.com/user-attachments/files/19771915/Test.results.for.IT.RDBMS.-.H2.zip)
Flaky test run log: [TEST-io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceSearchTest.txt](https://github.com/user-attachments/files/19771943/TEST-io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceSearchTest.txt)

<details><summary>Logs</summary>
<pre>
<![CDATA[14:41:26.336 [] [] [http-nio-0.0.0.0-1245-exec-3] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.count - ==>  Preparing: SELECT COUNT(*) FROM PROCESS_INSTANCE pi LEFT JOIN PROCESS_DEFINITION pd ON (pi.PROCESS_DEFINITION_KEY = pd.PROCESS_DEFINITION_KEY) WHERE EXISTS ( SELECT 1 FROM JOB j WHERE j.PROCESS_INSTANCE_KEY = pi.PROCESS_INSTANCE_KEY AND j.STATE IN ('FAILED', 'ERROR_THROWN') AND j.RETRIES > 0 )
14:41:26.337 [] [] [http-nio-0.0.0.0-1245-exec-3] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.count - ==> Parameters: 
14:41:26.345 [] [] [http-nio-0.0.0.0-1245-exec-3] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.count - <==      Total: 1
14:41:26.349 [] [] [http-nio-0.0.0.0-1245-exec-3] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.search - ==>  Preparing: SELECT * FROM ( SELECT pi.PROCESS_INSTANCE_KEY, pi.PROCESS_DEFINITION_ID, pi.PROCESS_DEFINITION_KEY, pi.STATE, pi.START_DATE, pi.END_DATE, pi.TENANT_ID, CASE WHEN pi.NUM_INCIDENTS = 0 THEN FALSE ELSE TRUE END AS HAS_INCIDENT, pi.PARENT_PROCESS_INSTANCE_KEY, pi.PARENT_ELEMENT_INSTANCE_KEY, pi.ELEMENT_ID, pi.VERSION PROCESS_DEFINITION_VERSION, pd.NAME AS PROCESS_DEFINITION_NAME, pd.VERSION_TAG AS PROCESS_DEFINITION_VERSION_TAG FROM PROCESS_INSTANCE pi LEFT JOIN PROCESS_DEFINITION pd ON (pi.PROCESS_DEFINITION_KEY = pd.PROCESS_DEFINITION_KEY) WHERE EXISTS ( SELECT 1 FROM JOB j WHERE j.PROCESS_INSTANCE_KEY = pi.PROCESS_INSTANCE_KEY AND j.STATE IN ('FAILED', 'ERROR_THROWN') AND j.RETRIES > 0 ) ) t ORDER BY PROCESS_INSTANCE_KEY ASC LIMIT ? OFFSET ?
14:41:26.351 [] [] [http-nio-0.0.0.0-1245-exec-3] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.search - ==> Parameters: 100(Integer), 0(Integer)
14:41:26.351 [] [] [http-nio-0.0.0.0-1245-exec-3] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.search - <==      Total: 0
14:41:26.472 [] [] [http-nio-0.0.0.0-1245-exec-7] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.count - ==>  Preparing: SELECT COUNT(*) FROM PROCESS_INSTANCE pi LEFT JOIN PROCESS_DEFINITION pd ON (pi.PROCESS_DEFINITION_KEY = pd.PROCESS_DEFINITION_KEY) WHERE EXISTS ( SELECT 1 FROM JOB j WHERE j.PROCESS_INSTANCE_KEY = pi.PROCESS_INSTANCE_KEY AND j.STATE IN ('FAILED', 'ERROR_THROWN') AND j.RETRIES > 0 )
14:41:26.472 [] [] [http-nio-0.0.0.0-1245-exec-7] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.count - ==> Parameters: 
14:41:26.472 [] [] [http-nio-0.0.0.0-1245-exec-7] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.count - <==      Total: 1
14:41:26.474 [Broker-0] [Exporter-1] [zb-fs-workers-0] DEBUG io.camunda.exporter.rdbms.RdbmsExporter - [RDBMS Exporter] Exporting record {"deadline":1744728386363,"timeout":-1,"worker":"default","retries":1,"retryBackoff":0,"recurringTime":-1,"type":"taskA","customHeaders":[packed value (length=1)],"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"service_tasks_v1","processDefinitionVersion":1,"processDefinitionKey":2251799813685282,"processInstanceKey":2251799813685295,"jobKind":"BPMN_ELEMENT","jobListenerEventType":"UNSPECIFIED","elementId":"taskA","elementInstanceKey":2251799813685300,"tenantId":"<default>","changedAttributes":[],"result":{"denied":false,"corrections":{"assignee":"","dueDate":"","followUpDate":"","candidateUsersList":[],"candidateGroupsList":[],"priority":-1},"correctedAttributes":[],"deniedReason":""}} with handler class io.camunda.exporter.rdbms.handlers.JobExportHandler
14:41:26.474 [Broker-0] [Exporter-1] [zb-fs-workers-0] DEBUG io.camunda.db.rdbms.write.queue.DefaultExecutionQueue - [RDBMS ExecutionQueue, Partition 1] Flushing execution queue with 1 items
14:41:26.474 [Broker-0] [Exporter-1] [zb-fs-workers-0] DEBUG io.camunda.db.rdbms.sql.JobMapper.update - ==>  Preparing: UPDATE JOB SET JOB_KEY = ?, PROCESS_INSTANCE_KEY = ?, RETRIES = ?, STATE = ?, HISTORY_CLEANUP_DATE = ? WHERE JOB_KEY = ?
14:41:26.474 [Broker-0] [Exporter-1] [zb-fs-workers-0] DEBUG io.camunda.db.rdbms.sql.JobMapper.update - ==> Parameters: 2251799813685302(Long), 2251799813685295(Long), 1(Integer), FAILED(String), null, 2251799813685302(Long)
14:41:26.474 [Broker-0] [Exporter-1] [zb-fs-workers-0] DEBUG io.camunda.exporter.rdbms.RdbmsExporter - [RDBMS Exporter] Updating position to 290 in rdbms
14:41:26.478 [] [] [http-nio-0.0.0.0-1245-exec-7] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.search - ==>  Preparing: SELECT * FROM ( SELECT pi.PROCESS_INSTANCE_KEY, pi.PROCESS_DEFINITION_ID, pi.PROCESS_DEFINITION_KEY, pi.STATE, pi.START_DATE, pi.END_DATE, pi.TENANT_ID, CASE WHEN pi.NUM_INCIDENTS = 0 THEN FALSE ELSE TRUE END AS HAS_INCIDENT, pi.PARENT_PROCESS_INSTANCE_KEY, pi.PARENT_ELEMENT_INSTANCE_KEY, pi.ELEMENT_ID, pi.VERSION PROCESS_DEFINITION_VERSION, pd.NAME AS PROCESS_DEFINITION_NAME, pd.VERSION_TAG AS PROCESS_DEFINITION_VERSION_TAG FROM PROCESS_INSTANCE pi LEFT JOIN PROCESS_DEFINITION pd ON (pi.PROCESS_DEFINITION_KEY = pd.PROCESS_DEFINITION_KEY) WHERE EXISTS ( SELECT 1 FROM JOB j WHERE j.PROCESS_INSTANCE_KEY = pi.PROCESS_INSTANCE_KEY AND j.STATE IN ('FAILED', 'ERROR_THROWN') AND j.RETRIES > 0 ) ) t ORDER BY PROCESS_INSTANCE_KEY ASC LIMIT ? OFFSET ?
14:41:26.480 [Broker-0] [Exporter-1] [zb-fs-workers-0] DEBUG io.camunda.exporter.rdbms.RdbmsExporter - [RDBMS Exporter] Updating position to 290 in broker
14:41:26.480 [Broker-0] [Exporter-1] [zb-fs-workers-0] DEBUG io.camunda.db.rdbms.write.queue.DefaultExecutionQueue - [RDBMS ExecutionQueue, Partition 1] Commit queue with 1 entries in 6ms
14:41:26.483 [] [] [http-nio-0.0.0.0-1245-exec-7] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.search - ==> Parameters: 100(Integer), 0(Integer)
14:41:26.483 [] [] [http-nio-0.0.0.0-1245-exec-7] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.search - <==      Total: 1
14:41:26.490 [] [] [http-nio-0.0.0.0-1245-exec-10] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.count - ==>  Preparing: SELECT COUNT(*) FROM PROCESS_INSTANCE pi LEFT JOIN PROCESS_DEFINITION pd ON (pi.PROCESS_DEFINITION_KEY = pd.PROCESS_DEFINITION_KEY) WHERE EXISTS ( SELECT 1 FROM JOB j WHERE j.PROCESS_INSTANCE_KEY = pi.PROCESS_INSTANCE_KEY AND j.STATE IN ('FAILED', 'ERROR_THROWN') AND j.RETRIES > 0 )
14:41:26.490 [] [] [http-nio-0.0.0.0-1245-exec-10] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.count - ==> Parameters: 
14:41:26.492 [] [] [http-nio-0.0.0.0-1245-exec-10] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.count - <==      Total: 1
14:41:26.493 [] [] [http-nio-0.0.0.0-1245-exec-10] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.search - ==>  Preparing: SELECT * FROM ( SELECT pi.PROCESS_INSTANCE_KEY, pi.PROCESS_DEFINITION_ID, pi.PROCESS_DEFINITION_KEY, pi.STATE, pi.START_DATE, pi.END_DATE, pi.TENANT_ID, CASE WHEN pi.NUM_INCIDENTS = 0 THEN FALSE ELSE TRUE END AS HAS_INCIDENT, pi.PARENT_PROCESS_INSTANCE_KEY, pi.PARENT_ELEMENT_INSTANCE_KEY, pi.ELEMENT_ID, pi.VERSION PROCESS_DEFINITION_VERSION, pd.NAME AS PROCESS_DEFINITION_NAME, pd.VERSION_TAG AS PROCESS_DEFINITION_VERSION_TAG FROM PROCESS_INSTANCE pi LEFT JOIN PROCESS_DEFINITION pd ON (pi.PROCESS_DEFINITION_KEY = pd.PROCESS_DEFINITION_KEY) WHERE EXISTS ( SELECT 1 FROM JOB j WHERE j.PROCESS_INSTANCE_KEY = pi.PROCESS_INSTANCE_KEY AND j.STATE IN ('FAILED', 'ERROR_THROWN') AND j.RETRIES > 0 ) ) t ORDER BY PROCESS_INSTANCE_KEY ASC LIMIT ? OFFSET ?
14:41:26.494 [] [] [http-nio-0.0.0.0-1245-exec-10] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.search - ==> Parameters: 100(Integer), 0(Integer)
14:41:26.495 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.write.queue.DefaultExecutionQueue - [RDBMS ExecutionQueue, Partition 1] Flushing execution queue with 1 items
14:41:26.496 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.sql.ExporterPositionMapper.update - ==>  Preparing: UPDATE EXPORTER_POSITION SET LAST_EXPORTED_POSITION = ?, LAST_UPDATED = ? WHERE PARTITION_ID = ?
14:41:26.496 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.sql.ExporterPositionMapper.update - ==> Parameters: 290(Long), 2025-04-15T14:41:26.474648959(LocalDateTime), 1(Integer)
14:41:26.496 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.exporter.rdbms.RdbmsExporter - [RDBMS Exporter] Updating position to 291 in rdbms
14:41:26.497 [] [] [http-nio-0.0.0.0-1245-exec-10] DEBUG io.camunda.db.rdbms.sql.ProcessInstanceMapper.search - <==      Total: 1
14:41:26.497 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.exporter.rdbms.RdbmsExporter - [RDBMS Exporter] Updating position to 291 in broker
14:41:26.497 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.write.queue.DefaultExecutionQueue - [RDBMS ExecutionQueue, Partition 1] Commit queue with 1 entries in 2ms
14:41:26.500 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.exporter.rdbms.RdbmsExporter - [RDBMS Exporter] Exporting record {"deadline":1744728386363,"timeout":-1,"worker":"default","retries":1,"retryBackoff":0,"recurringTime":-1,"type":"taskA","customHeaders":[packed value (length=1)],"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"service_tasks_v1","processDefinitionVersion":1,"processDefinitionKey":2251799813685282,"processInstanceKey":2251799813685303,"jobKind":"BPMN_ELEMENT","jobListenerEventType":"UNSPECIFIED","elementId":"taskA","elementInstanceKey":2251799813685309,"tenantId":"<default>","changedAttributes":[],"result":{"denied":false,"corrections":{"assignee":"","dueDate":"","followUpDate":"","candidateUsersList":[],"candidateGroupsList":[],"priority":-1},"correctedAttributes":[],"deniedReason":""}} with handler class io.camunda.exporter.rdbms.handlers.JobExportHandler
14:41:26.500 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.write.queue.DefaultExecutionQueue - [RDBMS ExecutionQueue, Partition 1] Flushing execution queue with 2 items
14:41:26.501 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.sql.ExporterPositionMapper.update - ==>  Preparing: UPDATE EXPORTER_POSITION SET LAST_EXPORTED_POSITION = ?, LAST_UPDATED = ? WHERE PARTITION_ID = ?
14:41:26.501 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.sql.ExporterPositionMapper.update - ==> Parameters: 291(Long), 2025-04-15T14:41:26.496362629(LocalDateTime), 1(Integer)
14:41:26.501 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.sql.JobMapper.update - ==>  Preparing: UPDATE JOB SET JOB_KEY = ?, PROCESS_INSTANCE_KEY = ?, RETRIES = ?, STATE = ?, HISTORY_CLEANUP_DATE = ? WHERE JOB_KEY = ?
14:41:26.502 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.sql.JobMapper.update - ==> Parameters: 2251799813685311(Long), 2251799813685303(Long), 1(Integer), FAILED(String), null, 2251799813685311(Long)
14:41:26.502 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.exporter.rdbms.RdbmsExporter - [RDBMS Exporter] Updating position to 293 in rdbms
14:41:26.507 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.exporter.rdbms.RdbmsExporter - [RDBMS Exporter] Updating position to 293 in broker
14:41:26.507 [Broker-0] [Exporter-1] [zb-fs-workers-1] DEBUG io.camunda.db.rdbms.write.queue.DefaultExecutionQueue - [RDBMS ExecutionQueue, Partition 1] Commit queue with 2 entries in 7ms
]]>
</pre>
</details>

### PR DESCRIPTION
**Pull request by tsedekey**
## Description

This issue addresses a flaky test reported in [#31090](https://github.com/camunda/camunda/issues/31090).

### Root Cause:
The original `waitUntilJobWorkerHasFoundJob()` method waited for at least one process with a found job. However, the test logic assumes a specific number of such processes—two, in this case.

### Proposed Fix:
Introduce a new parameter to `waitUntilJobWorkerHasFoundJob(int expectedProcesses)` that allows specifying an exact number of expected process instances with found jobs. Update the test to call this method with 2.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #31090

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]

**Review by p-wunderlich — APPROVED** [review]
Thanks, LGTM!

**Review by p-wunderlich — CHANGES_REQUESTED** [review]
But sadly it looks like the root problem is still not fixed. The Test now simply runs in a timeout because the new await just is never meet. 

`Condition with alias 'should wait until the process instance has been updated to reflect retries left.' didn't complete within 2 minutes because assertion condition defined as a Lambda expression in io.camunda.it.util.TestHelper 
expected: 2
 but was: 1.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1160)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)
	at io.camunda.it.util.TestHelper.waitUntilJobWorkerHasFailedJob(TestHelper.java:275)`

**Comment by tsedekey** [comment]
Hi @p-wunderlich, thanks for reviewing, in the previous fix, which added support for asserting an exact number of process instances with found jobs, did not resolve the underlying flakiness of the test.

While the logic of that fix is sound and should be retained, the test remains non-deterministic in CI environments.

To improve stability, this change simplifies the test setup by switching to a BPMN model that spawns a single process
instance. The test now creates one job, fails it with retries left, and verifies behaviour against just that one instance.

This reduces timing dependencies and should eliminate flakiness without compromising coverage.

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/ProcessDefinitionStatisticsTest.java [hunk 1]
```diff
@@ -530,20 +530,20 @@ void shouldReturnStatisticsForCanceled() {
   void shouldReturnStatisticsAndFilterByHasRetriesLeft() {
     // given
     final var processDefinitionKey =
-        TestHelper.deployResource(camundaClient, "process/service_tasks_v1.bpmn")
+        TestHelper.deployResource(camundaClient, "process/service_tasks_v2.bpmn")
```
Comment (p-wunderlich) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/ProcessDefinitionStatisticsTest.java:533]: Why have you changed also this test, is it also flaky?

**Review by p-wunderlich — APPROVED** [review]

**Comment by p-wunderlich** [comment]
LGTM, thanks!
