### PR TITLE
test: Add variable deserialization test

### LINKED ISSUE #10307: I can't use a serialized date-time value in a temporal expression
**Describe the bug**
In my process, I have an intermediate timer catch event. The duration is calculated dynamically based on a process variable (e.g. `= date and time(nextMedicTime) - now()`). 

The process variable is created in a previous step by using a temporal FEEL expression (e.g. `= date and time(now() + duration("P5D"), time("17:00:00@Europe/Berlin"))`).

When the process instance reaches the intermediate timer event, it creates an incident (message: `
Expected result of the expression "date and time(nextMedicTime) - now()" to be one of '[DURATION, PERIOD, STRING]', but was 'NULL'`). The issue is that it fails to convert the process variable into a date-time by using the function [date and time()](https://docs.camunda.io/docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion/#date-and-time). As a result, the calculation returns `null`.

The conversion fails because the process variable is stored as a string in the ISO-8601 format (e.g. `"2022-09-14T17:00+02:00[Europe/Berlin]"`) but the function expects a string in the [FEEL-specific format](https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-data-types/#date-time) (e.g. `"2022-09-14T17:00@Europe/Berlin"`). The difference in the formats is the representation of the timezone (i.e. `+02:00[Europe/Berlin]` vs. `@Europe/Berlin`).

To sum it up, the roundtrip of storing and using a serialized date-time process variable is broken.

**To Reproduce**

1. deploy the process: [date-time-roundtrip.bpmn.txt](https://github.com/camunda/zeebe/files/9532155/date-time-roundtrip.bpmn.txt)
2. create a new instance of the process
3. verify that an incident is created

**Expected behavior**

I can store a date-time value in a process variable and use it later in a temporal expression. 

So, the roundtrip of serializing and deserializing of a date-time value in a process variable works.

**Log/Stacktrace**

image

**Environment:**
- OS: 
- Zeebe Version: `8.0.5`
- Configuration: 

**Related**
[SUPPORT-17470](https://jira.camunda.com/browse/SUPPORT-17470)
[SUPPORT-19669]( https://jira.camunda.com/browse/SUPPORT-19669)

### PR DESCRIPTION
**Pull request by saig0**
## Description

Add a new test class to verify the deserialization of variables.

## Related issues

closes https://github.com/camunda/camunda/issues/10307

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/variable/ProcessInstanceVariableDeserializationTest.java [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+import org.junit.runner.RunWith;
+import org.junit.runners.Parameterized;
+import org.junit.runners.Parameterized.Parameter;
+import org.junit.runners.Parameterized.Parameters;
+
+/**
+ * To ensure that we can serialize and deserialize all FEEL data types into process instance
+ * variables (i.e., a working round-trip).
+ */
+@RunWith(Parameterized.class)
```
Comment (megglos) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/variable/ProcessInstanceVariableDeserializationTest.java:30]: junit4 as other tests are on 4 still as well, right?

**Review by megglos — APPROVED** [review]
Nice that you thought of adding verification to the engine as well given the recent FEEL release 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/variable/ProcessInstanceVariableDeserializationTest.java (hunk 1 above)
Comment (saig0) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/variable/ProcessInstanceVariableDeserializationTest.java:30]: Yes, the engine tests are still based on JUnit 4.
