### PR TITLE
fix: initialize routing info when desired key is not present

### LINKED ISSUE #36219: Initialize RoutingInfo when desired state is not present
We make use of the Desired partition count from the RoutingState in the Resource/Command distribution among partitions, currently during upgrade from 8.7 to 8.8 the distribution fails because desired partition count is not present in RocksDB.

This need to be taken into account when running the Migrations to perform the insert in RocksDB for the initial value, being equal to the current partitions count.

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

Allow RoutingInfoInitializationMigration to be run when the `desired` key is not present in RocksDB, this happens when upgrading from 8.7 to 8.8.

- Had to make `PersistedRoutingInfo` public to mock the values
- Had to make initialization perform `upsert` for the current partition info, since `insert` would fail if called a second time
## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #36219
Ref: https://camunda.slack.com/archives/C037RS2JHB8/p1753805567395329

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/DbMigratorImplTest.java [hunk 1]
```diff
@@ -275,4 +290,83 @@ void shouldOnlyRunInitializationMigrationsWhenDbIsEmpty() {
     verify(migration).runMigration(any());
     verify(mockProcessingState.getMigrationState()).setMigratedByVersion(eq(CURRENT_VERSION));
   }
+
+  @Test
+  void shouldRunRoutingInfoInitializationWhenDesiredIsNotSet() {
```
Comment (deepthidevaki) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/DbMigratorImplTest.java]: :wrench: I don't think these tests belong here. It should be in `RoutingInfoInitializationMigrationTest` or just add a test for `isInitialized` in `DbRoutingStateTest` because that is what we are essentially testing.

**Review by deepthidevaki — APPROVED** [review]
LGTM. 

:question: Can we also add a test that reproduce the original bug that instances are not created in all partitions after update?

**Comment by panagiotisgts** [comment]
> Can we also add a test that reproduce the original bug that instances are not created in all partitions after update?

I'll address this in another PR to have this fix available for the next alpha release :+1:
