### PR TITLE
Write an error record to prevent error loop in ProcessingStateMachine

### LINKED ISSUE #16107: Endless processing state machine error loop
**Describe the bug**

Extracted from https://github.com/camunda/zeebe/issues/14929 and https://github.com/camunda/zeebe/issues/16104

When such cases produce an error, the processing state machine will try and handle it. Part of the error handling is to respond to the user with a rejection. However, in this case, we failed to serialize the record when appending the rejection, which causes a new error. This is then handled the same way, and simply loops forever.

**To Reproduce**

```java
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Zeebe Community License 1.1. You may not use this file
 * except in compliance with the Zeebe Community License 1.1.
 */
package io.camunda.zeebe.it.client.command;

import static org.assertj.core.api.Assertions.assertThat;

import io.camunda.zeebe.qa.util.cluster.TestStandaloneBroker;
import io.camunda.zeebe.qa.util.junit.ZeebeIntegration;
import io.camunda.zeebe.qa.util.junit.ZeebeIntegration.TestZeebe;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.concurrent.Future;
import org.junit.jupiter.api.Test;

@ZeebeIntegration
public class EndlessLoopTest {
  @TestZeebe private final TestStandaloneBroker broker = new TestStandaloneBroker();

  private final String dmn =
      """
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" id="_6f87b3aa-d613-4c41-93ad-832f021c8318" name="definitions" namespace="http://camunda.org/schema/1.0/dmn">
  <decision id="_51711_44808585-3491-42a8-87ea-3c4fcda46eff" name="">
    <decisionTable id="_07c6fdc3-7bdf-459a-a016-2ae12e474bd2">
      <input id="_f00d0717-d08a-4918-ad51-568788e92038" label="Percent Responsible (Loan Roles)">
        <inputExpression id="_0b922041-84c3-47bf-b94c-1dd423c394ae" typeRef="number">
          <text>proposedLoan.loanRoles.percentResponsible</text>
        </inputExpression>
      </input>
      <output id="_b304292d-98e5-4dde-8fbd-0de1981c97ea" label="" name="out" typeRef="string">
        <outputValues id="UnaryTests_1yu7moy">
          <text>"Approve","Decline","Review"</text>
        </outputValues>
      </output>
      <rule id="DecisionRule_1j6jzzn">
        <inputEntry id="UnaryTests_105fhm8">
          <text></text>
        </inputEntry>
        <outputEntry id="LiteralExpression_1ucr6zl">
          <text>"Approve"</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>
</definitions>
""";

  @Test
  void shouldNotLoopEndlessly() {
    // given
    try (final var client = broker.newClientBuilder().build()) {
      // when
      final Future<?> result =
          client
              .newDeployResourceCommand()
              .addResourceBytes(dmn.getBytes(StandardCharsets.UTF_8), "bork.dmn")
              .requestTimeout(Duration.ofSeconds(30))
              .send();

      // then - expand the assert to check that it's rejected appropriately within reasonable amount
      // of time
      assertThat(result).failsWithin(Duration.ofSeconds(10)).withThrowableThat();
    }
  }
}
```

**Expected behavior**

On error, attempt to handle it via the processor which caused it, then:

1. Write a rejection and send it
2. If this causes an error, then handle it by making it more generic: omit the record value (unfortunately) and make the record which caused it as failed.
3. Send a generic error back to the gateway/client.
4. If this causes an error, mark the record as failed (so we can skip it) but omit sending anything.

This affects all supported version as far as I can tell.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Previously we reset the value and used it to write the follow up rejection record and the rejection response. However, as we saw in https://github.com/camunda/zeebe/issues/16429 not all records are serializable when the value is reset because it may not have a valid value for the properties. 

To ensure all cases can be handled in the error handling logic in `ProcessingStateMachine`, we write an `ErrorRecord`. It is guaranteed that an `ErrorRecord` is always serializable. 

We also send the `ErrorRecord` in the response. However, the gateway do not read the value in a rejection response anyway. So it does not matter. Alternatively, we can also decide not to send any "value" in a rejection response. But this could break several parts of the code as we assume this is not null when serializing or deserializing it. It feels safer to just sent an error record which is currently ignored by the gateway. But can be read if needed if we decide to use it later. 

## Related issues

closes #16107 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 1]
```diff
@@ -522,23 +525,24 @@ private void tryRejectingIfUserCommand(final String errorMessage) {
...
+            .rejectionReason("");
+    processingResultBuilder.appendRecord(currentRecord.getKey(), errorRecord, recordMetadata);
     processingResultBuilder.withResponse(
         RecordType.COMMAND_REJECTION,
         typedCommand.getKey(),
         typedCommand.getIntent(),
-        typedCommand.getValue(),
-        typedCommand.getValueType(),
+        errorRecord,
+        ValueType.ERROR,
```
Comment (deepthidevaki) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:545]: :question: Here I'm undecided whether to send the error record or a null. The problem with null is, it may break several parts because we assume a record always have a non-null value. The value is ignored by the gateway anyway if it is a rejection.

File: zeebe/protocol/src/main/resources/protocol.xml [hunk 2]
```diff
@@ -115,6 +115,7 @@
     <field name="partitionId" id="1" type="uint16"/>
     <field name="key" id="2" type="uint64"/>
     <field name="recordType" id="3" type="RecordType"/>
+    <!-- value type is usually request.ValueType but can also be ERROR if RecordType is COMMAND_REJECTION -->
```
Comment (npepinpe) [inline zeebe/protocol/src/main/resources/protocol.xml:118]: :+1:

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 3]
```diff
@@ -522,23 +525,24 @@ private void tryRejectingIfUserCommand(final String errorMessage) {
     final var rejectionReason = errorMessage != null ? errorMessage : "";
     final ProcessingResultBuilder processingResultBuilder =
         new BufferedProcessingResultBuilder(logStreamWriter::canWriteEvents);
-    // reset value to minimize any potential error loop that can be caused by writing the full
-    // record.
-    typedCommand.getValue().reset();
-    final var rejectionMetadata =
+    final var errorRecord = new ErrorRecord();
+    errorRecord.initErrorRecord(new RuntimeException(rejectionReason), currentRecord.getPosition());
```
Comment (npepinpe) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:529]: :upside_down_face: Very soft suggestion, I would prefer a specific exception so it's immediately obvious what it is, but you can still find out via stack trace (and technically no one is reading this record ;)). Plus, it's not the hot path, so we don't need to think about a stackless exception anyway. But a `CommandRejectionException` might not be a bad thing in the protocol in general :shrug:

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 1 above)
Comment (npepinpe) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:545]: I think that's perfectly fine. It only gets serialized at the transport layer, so we could still decide there to drop it.

**Review by npepinpe — APPROVED** [review]
:tada:

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 3 above)
Comment (deepthidevaki) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java]: Replaced RuntimeException with `CommandRejectionException`.
