### PR TITLE
Handle concurrent modifications of a stream's consumers during push

### LINKED ISSUE #13038: Handle stream consumers changes during push
**Describe the bug**

When trying/retrying a push from the broker side, we every time pick the next random stream consumer to push to. However, it's possible that during a retry all consumers are removed. Right now, this throws an error because we try to generate a random index from 0 to 0 :smile: 

**Expected behavior**

We should cope with streams having no consumers (on both the gateway/broker) even during retries, and bail out early.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes handling of concurrent modifications of an aggregated remote stream's consumers  during a job push. `AggregatedRemoteStream` is now thread-safe by using a `CopyOnWriteArrayList` for its consumers. This is considered fine as its usage is read heavy, but not write heavy, and it's expected to be fairly small.

The `RemoteStreamImpl` now handles when the consumers are modified before a call to push, and during retry.

On the first try, it picks a consumers by randomly generating an index from the list. On the happy/common path, this will return an item without requiring a copy of the list. On the exceptional case, this will throw an exception, and we do an optimistic loop where we recompute the initial consumer. If there are no consumers left, the error handler is called with `StreamExhaustedException`.

On subsequent retries, the first thing we do is a copy of the consumers list, from which we remove the initial consumer tried. Then shuffle that, and keep an iterator to it. While this is more "expensive", this is the exceptional case, so it's an acceptable trade-off.

The downside is we may now be pushing to consumers which were removed in the meantime, but we should be handling these errors properly. As this will not happen most of the time, this was deemed a simpler and easier to maintain approach, than making `AggregatedRemoteStream` thread-safe and handling possible concurrent modifications.

## Related issues

closes #13038 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by deepthidevaki** [comment]
@npepinpe I'm not sure if there was concurrency problem before. `AggregatedRemoteStream` is accessed in the same actor as `RemoteStreamerImpl`. https://github.com/camunda/zeebe/blob/ef43ddbacc898c85a6c6aa584a93ede034b1f8ba/transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamerImpl.java#L69

This is also why it was executed using an executor https://github.com/camunda/zeebe/blob/ef43ddbacc898c85a6c6aa584a93ede034b1f8ba/transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamImpl.java#L51

**Comment by npepinpe** [comment]
I think the issue is between getting the remote strwam in the engine, and then calling push later as a side effect (asynchronously), meaning in between we may have mutated the list of consumers. It's not a race condition to access the list itself. Sorry for the confusion.

**Comment by deepthidevaki** [comment]
As far as I can see, what ever is accessed from the engine thread is threadsafe. `RemoteSTreamRegistry:typeToConsumers` is a `ConcurrentHashMap`, and Set of `AggregatedRemoteStream` is a `CopyOnWriteArraySet`.

**Comment by npepinpe** [comment]
Oh, I thought it was simply an array list. But the issue still remains. We get a stream initially from RemoteStreamer, amd at that point it has consumers. We call push later down the line, asynchronously, at which point it may have no comsumers anymore. So we can either handle this then (and also handle every time we get the list of streamConsumers), or we can freeze the list.

Is that not the case? That it is thread safe doesn't change it can be mutated at any point, yeah? So we still need to handlen concurrent modifications between picking, pushing, and retrying.

**Comment by deepthidevaki** [comment]
Mutating it is fine, right? It happens in the same thread. What can happen is you pick an AggregatedStream and by the time you call push, all streams in the AggregatedStream is closed. This can also happen if you use a fixed immutable list. 

Am I overlooking something? I will be in TR. May be it is better to discuss it f2f.

**Comment by npepinpe** [comment]
@deepthidevaki I've updated the PR and description

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamImpl.java [hunk 1]
```diff
@@ -48,41 +44,82 @@ public M metadata() {
...
-                final var consumers = new ArrayList<>(streamConsumers);
-                consumers.remove(randomClient);
-                Collections.shuffle(consumers);
-                new RetryHandler(errorHandler, consumers).retry(error, payload);
-              },
-              randomClient.id());
-        });
+    final var initialConsumer = pickInitialConsumer();
+    if (initialConsumer == null) {
+      errorHandler.handleError(
```
Comment (deepthidevaki) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamImpl.java:49]: :thought_balloon: This will be run in the engine thread. But I guess this is ok, because we know the errorHandler is non-blocking eventhough we don't enforce it.

**Review by deepthidevaki — APPROVED** [review]
:tada:  for finding the concurrency issue.

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamImpl.java (hunk 1 above)
Comment (npepinpe) [reply transport/src/main/java/io/camunda/zeebe/transport/stream/impl/RemoteStreamImpl.java:49]: :thinking: Should we enforce it? We could use the streamer's executor if only to avoid additional load on the engine. Seems a little much considering it then delegates to another actor, but :shrug: It's a pretty uncommon case, I would lean to leave it as is.

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors merge
