### PR TITLE
fix: fix broken serialisation of offsetdatetime in document stores

### LINKED ISSUE #41327: LocalStorageDocumentStore fails when expiresAt is set in the DocumentCreationRequest
### Description

`LocalStorageDocumentStore` throws an error when the `expiresAt` field is set in requests.

This might also happen for the in-memory store and should be fixed there as well (needs investigation).

The field is not used in local storage but this is not clear from the [API documentation](https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/create-document/), so docs will also need to be updated depending on the solution.

### Steps to reproduce

Create a test case that sets the `expiresAt` date in the `DocumentCreationRequest` in the request for `LocalStorageDocumentStore`.

### Current behavior

A jackson error is thrown:

> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (or disable `MapperFeature.REQUIRE_HANDLERS_FOR_JAVA8_TIMES`) (through reference chain: io.camunda.document.api.DocumentMetadataModel["expiresAt"])
> 	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
> ...
> 	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:4104)
> 	at io.camunda.document.store.localstorage.LocalStorageDocumentStore.lambda$createDocumentInternal$4(LocalStorageDocumentStore.java:138)

### Expected behavior

- API requests that set the `expiresAt` field don't fail.
- Documentation is clear about the expected behavior when setting the `expiresAt` field for different storage types

### Workaround

Don't set the `expiresAt` field for document creation requests - The application itself does not set this when configured to use local storage (but it should still be something the API can handle).

### Environment

SaaS & SM

### Version

- Component Version: 8.7, 8.8, 8.9

### Rootcause

The default ObjectMapper can not handle the `OffsetDateTime` data type that is set for the expiresAt field when serializing the document.

### Solution ideas

Solution suggestions:
1. Handle the expiresAt field for local storage for easier migration later
2. Ignore the field but don't fail (maybe log a warning)
3. Fail more gracefully (return an error that clearly states this is not supported)

Out of these Options 1 is the preferred and probably easiest solution:
The error occurs in [LocalStorageDocumentStore.java:138](https://github.com/camunda/camunda/blob/e6178afbe8aa04eea71f0ea4892ea916af60cd7c/document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java#L138). That line simply serialises` request.metadata()` which contains the field in question. `LocalDocumentStore` doesn't attempt to do anything specific with that field, it simply tries to serialise it using an ObjectMapper (and probably tries to deserialise it too when reading the document), so we simply need to allow the ObjectMapper to ser/des fields of that type.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Support case discussion (internal): https://camunda.slack.com/archives/C09T3N34D7T/p1763567062530729

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tanjinyi**
## Description

To fix the broken serialisation of `OffsetDateTime` due to the missing `JavaTimeModule` required in Jackson for serialising DateTime classes.

Based on the tests that are written for the other document stores, only `LocalStorageDocumentStore` throws an exception when attempting to serialise metadata with `OffsetDateTime` set. Other document stores do not face this issue.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #41327

### CODE REVIEW

File: document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java [hunk 1]
```diff
@@ -190,7 +190,8 @@ public void shouldStoreContentType() {
     final InMemoryDocumentStore store = new InMemoryDocumentStore();
     final String id = "key";
     final DocumentMetadataModel metadata =
-        new DocumentMetadataModel("application/json", null, null, null, null, null, null);
+        new DocumentMetadataModel(
+            "application/json", "test.json", OffsetDateTime.now(), null, null, null, null);
```
Comment (kristinkomschow) [inline document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java]: We should create an own test case where `expiresAt` is set since we still also want to allow for null values, so we should ensure that both options work.

🗯️  Ideally we could make this a parameterized test. That way it would be easy to extend in the future if we want to test more metadata model configurations.
If you're not familiar with parameterized tests, you can check e.g.  [UsageMetricAuthorizationIT](https://github.com/camunda/camunda/blob/main/qa/acceptance-tests/src/test/java/io/camunda/it/auth/UsageMetricAuthorizationIT.java) for reference.

File: document/store/src/test/java/io/camunda/document/store/localstorage/LocalStorageDocumentStoreTest.java [hunk 2]
```diff
@@ -297,7 +302,13 @@ private void createDocumentForTest(final byte[] content, final String documentId
 
   private DocumentMetadataModel givenMetadata(final byte[] content) {
     return new DocumentMetadataModel(
-        "text/plain", "test-file.txt", null, (long) content.length, null, null, null);
+        "text/plain",
```
Comment (kristinkomschow) [inline document/store/src/test/java/io/camunda/document/store/localstorage/LocalStorageDocumentStoreTest.java]: Same as with in-memory storage, we should have a separate test case here.

**Review by kristinkomschow — CHANGES_REQUESTED** [review]

File: document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java (hunk 1 above)
Comment (georgios-goulos) [reply document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java]: The test `createDocumentShouldSucceed` uses

```java
    final var metadata =
        new DocumentMetadataModel(
            "application/json",
            "hello.json",
            OffsetDateTime.now(),
            10L,
            null,
            null,
            Map.of("key", "value"));
```

So there is already a test that handles a case with a populated `expiresAt` for the InMemoryDocumentStore. the original implementation of this test here seems to be handling the case when `expiresAt` is `null` (although the test name `shouldStoreContentType` indicates this check is implicit and unrelated to the actual purpose of the test).

File: document/store/src/test/java/io/camunda/document/store/localstorage/LocalStorageDocumentStoreTest.java [hunk 3]
```diff
@@ -41,7 +43,9 @@ void setUp() throws IOException {
     storagePath = Files.createTempDirectory(UUID.randomUUID().toString());
     documentStore =
         new LocalStorageDocumentStore(
-            storagePath, new ObjectMapper(), Executors.newSingleThreadExecutor());
+            storagePath,
+            new ObjectMapper().registerModule(new JavaTimeModule()),
+            Executors.newSingleThreadExecutor());
```
Comment (georgios-goulos) [inline document/store/src/test/java/io/camunda/document/store/localstorage/LocalStorageDocumentStoreTest.java:58]: Given this setup here it looks to me that we are testing this instance of `LocalDocumentStore` and not the instance that is actually used in production (created in `LocalStorageDocumentStoreProvider.java`). This means that e.g. someone could accidentally change the instance creation in `LocalStorageDocumentStoreProvider` and remove the registered `JavaTimeModule` but these tests would still pass so the issue would not be exposed via these tests.

Comment (georgios-goulos) [reply document/store/src/test/java/io/camunda/document/store/localstorage/LocalStorageDocumentStoreTest.java:58]: There are a few ways of testing the behaviour of the instance used in production. The easiest one is probably to create a test for `LocalStorageDocumentStoreProvider`. Copilot suggested

```java
     @Test
     void shouldSerializeOffsetDateTimeWhenCreatedViaProvider() throws IOException {
       // given
       Path tempPath = Files.createTempDirectory("test");
       DocumentStoreConfigurationRecord config = 
         new DocumentStoreConfigurationRecord("localstorage", 
           LocalStorageDocumentStoreProvider.class, 
           Map.of("PATH", tempPath.toString()));
       
       LocalStorageDocumentStoreProvider provider = new LocalStorageDocumentStoreProvider();
       DocumentStore store = provider.createDocumentStore(config, Executors.newSingleThreadExecutor());
       
       DocumentMetadataModel metadata = new DocumentMetadataModel(
         "text/plain", "test.txt", OffsetDateTime.now(), 100L, null, null, null);
       
       // when - store document with OffsetDateTime
       DocumentCreationRequest request = new DocumentCreationRequest(
         "doc-id", content, metadata, null);
       var result = store.createDocument(request).join();
       
       // then - should succeed without serialization errors
       assertThat(result.isRight()).isTrue();
     }
```

This has not been tested but I think it is a good starting point.

Comment (tanjinyi) [reply document/store/src/test/java/io/camunda/document/store/localstorage/LocalStorageDocumentStoreTest.java:58]: Thanks, I've added a test that captures the provider itself.

File: document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java (hunk 1 above)
Comment (tanjinyi) [reply document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java]: Thanks for the reference, I've added a set of tests to check each field individually.

File: document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java [hunk 4]
```diff
@@ -202,5 +207,36 @@ public void shouldStoreContentType() {
     assertThat(result).isInstanceOf(Either.Right.class);
     final var reference = ((Either.Right<DocumentError, DocumentReference>) result).value();
     assertThat(reference).isNotNull();
+    assertThat(reference.metadata())
+        .hasFieldOrPropertyWithValue(
+            fieldToCheck,
+            ReflectionSupport.tryToReadFieldValue(
+                    metadata.getClass().getDeclaredField(fieldToCheck), metadata)
+                .getOrThrow(
```
Comment (kristinkomschow) [inline document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java]: The error here is never thrown even when setting all metadata model values to `null` because it does not fail for null values (only if the field does not exist). I think the `LocalStorageDocumentStoreTest#shouldHandleMetadataParamsCorrectly` does this better by just comparing the result metadata with the result.

File: document/store/src/test/java/io/camunda/document/store/localstorage/LocalStorageDocumentStoreTest.java [hunk 5]
```diff
@@ -223,6 +239,64 @@ void verifyContentHashShouldSucceed() {
...
+
+    // then - should succeed without serialization errors
+    final DocumentReference documentReference = result.get();
+    assertThat(result.isRight()).isTrue();
+  }
+
+  @ParameterizedTest
+  @MethodSource("metadataSingleParamProvider")
+  public void shouldHandleMetadataParamsCorrectly(
+      final String fieldToCheck, final DocumentMetadataModel metadata) throws NoSuchFieldException {
```
Comment (kristinkomschow) [inline document/store/src/test/java/io/camunda/document/store/localstorage/LocalStorageDocumentStoreTest.java]: `fieldToCheck` is never used here and can be removed from the arguments.

File: document/store/pom.xml [hunk 6]
```diff
@@ -74,6 +74,11 @@
       <artifactId>jackson-core</artifactId>
     </dependency>
 
+    <dependency>
+      <groupId>com.fasterxml.jackson.datatype</groupId>
+      <artifactId>jackson-datatype-jsr310</artifactId>
+    </dependency>
+
     <dependency>
```
Comment (kristinkomschow) [inline document/store/pom.xml:82]: Java tests are currently failing because of missing

```
<dependency>
  <groupId>org.junit.platform</groupId>
  <artifactId>junit-platform-commons</artifactId>
  <version>1.13.4</version>
  <scope>test</scope>
</dependency>
```

If we don't use reflection to check individual record fields but instead compare the given and result metadata instead, we don't need it though.

**Review by kristinkomschow — CHANGES_REQUESTED** [review]
I left some notes. Mostly I noticed that setting null values for the metadata fields that should be tested currently does not lead to exceptions or test failures.

File: document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java (hunk 4 above)
Comment (tanjinyi) [reply document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java]: The metadata is modified in the case of `InMemoryDocumentStore` where the `fileName` gets overridden to the document ID in the case where it is not defined, hence the attempt to only read the field value that is populated and only checking whether the field is null. What would be the better method to handle this? Would it be better to just pass in the `fileName` for all of the arguments?

Comment (tanjinyi) [reply document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java]: Refactored with fileName argument supplied.

File: document/store/pom.xml (hunk 6 above)
Comment (tanjinyi) [reply document/store/pom.xml:82]: Removed the reflection call.

File: document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java [hunk 7]
```diff
@@ -184,13 +188,13 @@ public void createLinkShouldFail() {
         .isInstanceOf(DocumentError.OperationNotSupported.class);
   }
 
-  @Test
-  public void shouldStoreContentType() {
+  @ParameterizedTest
+  @MethodSource("metadataSingleParamProvider")
+  public void shouldHandleMetadataParamsCorrectly(
+      final String fieldToCheck, final DocumentMetadataModel metadata) throws NoSuchFieldException {
```
Comment (kristinkomschow) [inline document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java]: We don't need the `fieldToCheck` here anymore and the test also doesn't throw `NoSuchFieldException` anymore, so those should be removed

File: document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java [hunk 8]
```diff
@@ -202,5 +206,32 @@ public void shouldStoreContentType() {
     assertThat(result).isInstanceOf(Either.Right.class);
     final var reference = ((Either.Right<DocumentError, DocumentReference>) result).value();
     assertThat(reference).isNotNull();
+    assertThat(reference.metadata()).isEqualTo(metadata);
+  }
+
+  public static Stream<Arguments> metadataSingleParamProvider() {
+    // Due to the filename being overridden by the store, it must be set for all args.
```
Comment (kristinkomschow) [inline document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java]: 🗯️ We could maybe clarify here that we do this to simplify the assertion, so "Filename is always set here to prevent it from being overridden with the id by the store to simplify assertions"

Overall I think this is a valid approach since it simplifies the test code quite a bit compared to needing to assert individual fields 👍

**Review by kristinkomschow — APPROVED** [review]
I left two small comments but overall it LGTM now 👍

File: document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java (hunk 8 above)
Comment (tanjinyi) [reply document/store/src/test/java/io/camunda/document/store/inmemory/InMemoryDocumentStoreTest.java]: cool, i'll change the comments here
