### PR TITLE
Log RESOURCE_EXHAUSTED on trace

### LINKED ISSUE #7061: Warning logs in the job worker
**Description**

In the worker we log several things, one of it is the following warning:
```
01:42:49.069 [grpc-default-executor-399] WARN io.camunda.zeebe.client.job.poller - Failed to activated jobs for worker benchmark-worker and job type benchmark-task
```

I'm questioning whether this really make sense, since in the worker it is expected that from time to time there are no jobs to be activated. This will cause flooding the customers logs with useless information. This happens also in our benchmarks. 

If we take a window of ~10 minutes it was logged in our cluster ~80k times.

[log](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Alabels.k8s-pod%2Fapp%3D%22worker%22%0AtextPayload:%22Failed%20to%20activated%20jobs%20for%20worker%20benchmark-worker%20and%20job%20type%20benchmark-task%22;timeRange=2021-05-18T02:35:00.000Z%2F2021-05-18T02:42:00.000Z;summaryFields=:true:32:beginning;cursorTimestamp=2021-05-18T02:41:59.937941777Z?customFacets=&scrollTimestamp=2021-05-18T01:42:52.266113777Z&authuser=1&project=zeebe-io)

Furthermore we log in the worker RESOURCE_EXHAUSTED exceptions, which I expected are ignored?

```
I 2021-05-18T01:42:49.069958278Z io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Expected to activate jobs of type 'benchmark-task', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.
	at io.grpc.Status.asRuntimeException(Status.java:535) ~[app.jar:1.1.0-SNAPSHOT]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [app.jar:1.1.0-SNAPSHOT]
	at me.dinowernli.grpc.prometheus.MonitoringClientCallListener.onClose(MonitoringClientCallListener.java:50) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [app.jar:1.1.0-SNAPSHOT]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [app.jar:1.1.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2021-05-18T01:42:49.148067121Z 01:42:49.147 [grpc-default-executor-396] WARN  io.camunda.zeebe.client.job.poller - Failed to activated jobs for worker benchmark-worker and job type benchmark-task
 
```

Example log https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-05-18T01:41:31.243000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-cw-20-f8b1a83e1-benchmark%22%0Alabels.k8s-pod%2Fapp%3D%22worker%22&scrollTimestamp=2021-05-18T01:42:49.707280450Z&dateRangeStart=2021-05-18T00:41:31.243Z&dateRangeEnd=2021-05-18T02:41:31.243Z

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Logging the RESOURCE_EXHAUSTED on warning level caused some confusion in
the community and it produced a lot of noise in our logs. In most cases
it is expected if the broker is overloaded or is quite busy, our backoff
strategy will handle this case. For these cases we don't need to see
this exception.

I thought a bit about completely removing it as we previous discussed it @npepinpe but I then thought i might make more sense to have it on trace so you can see it if you really want to.

If there is an issue with activation and we need to investigate that we can lower the log level to trace to see the exception again.

## Related issues

closes #7061 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/worker/JobPoller.java [hunk 1]
```diff
@@ -133,6 +131,24 @@ public void onCompleted() {
     pollingDone();
   }
 
+  private void logFailure(final Throwable throwable) {
+    final String errorMsg = "Failed to activated jobs for worker {} and job type {}";
+
+    if (throwable instanceof StatusRuntimeException) {
+      final StatusRuntimeException statusRuntimeException = (StatusRuntimeException) throwable;
+      if (statusRuntimeException.getStatus().equals(Status.RESOURCE_EXHAUSTED)) {
```
Comment (npepinpe) [inline clients/java/src/main/java/io/camunda/zeebe/client/impl/worker/JobPoller.java:139]: From the docs of `Status#equals`:

> Equality on Statuses is not well defined. Instead, do comparison based on their Code with getCode. The description and cause of the Status are unlikely to be stable, and additional fields may be added to Status in the future.

```suggestion
      if (statusRuntimeException.getStatus().getCode() == Code.RESOURCE_EXHAUSTED) {
```

**Review by npepinpe — APPROVED** [review]
:rocket: 

Just a small thing, but no need for a second review I think
