### PR TITLE
Replace incremental requestId in AtomixServerTransport with unique SnowflakeId

### LINKED ISSUE #5624: Unexpected value type in command response
**Describe the bug**
In the gateway, the following error is logged: 
```
io.zeebe.gateway.cmd.ClientResponseException: 
io.zeebe.gateway.cmd.UnsupportedBrokerResponseException: 
Expected command response with value type 'JOB_BATCH', but received 'WORKFLOW_INSTANCE_RESULT'
```

It seems that the response is mapped to the wrong request. As a result, the client may not receive the response.

**To Reproduce**
This issue occurred in Camunda Cloud: https://console.cloud.google.com/errors/COflgoCR7tbWdA?service=zeebe&time=P7D&project=camunda-cloud-240911

This issue was logged a few times.

A few timeouts between the gateway and the broker were logged before.
```
Expected to handle gRPC request, but request timed out between gateway and broker
```

The following error was logged just before this one - in all cases: 
```
Failed to read response: Expected command response with value type 'DEPLOYMENT', but received 'WORKFLOW_INSTANCE_CREATION'
``` 
(see https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%224e6de936-a992-4f41-b171-2025b4f182e6-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-18T13:22:41.899Z%2F2020-10-18T14:22:41.899Z;pinnedLogId=2020-10-18T13:52:11.899543Z%2Fypp81fyhzawnz7ie8?project=camunda-cloud-240911) 

**Expected behavior**
The response is mapped to the correct request.

**Log/Stacktrace**
From the Camunda cloud: https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%224e6de936-a992-4f41-b171-2025b4f182e6-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-17T08:48:29.752Z%2F2020-10-17T09:48:29.752Z;pinnedLogId=2020-10-17T09:17:59.752357Z%2Ff2dm0mnhtg9jnic8m?project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.zeebe.gateway.cmd.ClientResponseException: io.zeebe.gateway.cmd.UnsupportedBrokerResponseException: Expected command response with value type 'JOB_BATCH', but received 'WORKFLOW_INSTANCE_RESULT'
at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2 (BrokerRequestManager.java:135)
at io.zeebe.util.sched.future.FutureContinuationRunnable.run (FutureContinuationRunnable.java:28)
at io.zeebe.util.sched.ActorJob.invoke (ActorJob.java:76)
at io.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
at io.zeebe.util.sched.ActorTask.execute (ActorTask.java:118)
at io.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:107)
at io.zeebe.util.sched.ActorThread.doWork (ActorThread.java:91)
at io.zeebe.util.sched.ActorThread.run (ActorThread.java:204)
Caused by: io.zeebe.gateway.cmd.UnsupportedBrokerResponseException: Expected command response with value type 'JOB_BATCH', but received 'WORKFLOW_INSTANCE_RESULT'
at io.zeebe.gateway.impl.broker.request.BrokerExecuteCommand.readResponse (BrokerExecuteCommand.java:92)
at io.zeebe.gateway.impl.broker.request.BrokerRequest.getResponse (BrokerRequest.java:70)
at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2 (BrokerRequestManager.java:129)
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `0.24.4`
 - Configuration: [e.g. exporters etc.]

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

In the issue "Unexpected value type in command response" the problem is likely being cause by:

> Request X was sent to leader A, leader A assigns it a requestId R.
> New leader B before record X is processed
> New Request Y was sent to leader B, it got same requestId R.
> leader B process X first, and respond using the requestId R which will be sent to the response future waiting for request Y
> Why would this happen? RequestId is kept in memory per broker, and can restart at 0 after a broker restart.

https://github.com/camunda/zeebe/blob/a6803100c462387705716cfa1c90f17cd8fc6703/transport/src/main/java/io/camunda/zeebe/transport/impl/AtomixServerTransport.java#L106

https://github.com/camunda/zeebe/issues/5624#issuecomment-1746328756

The solution chosen was to use SnowflakeIdGenerator which provides us with a unique request ID generated that uses the node ID and time as seed. It is also capable of generating up to 4096 unique IDs per millisecond per node.

## Related issues

closes https://github.com/camunda/zeebe/issues/5624

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: transport/src/main/java/io/camunda/zeebe/transport/impl/AtomixServerTransport.java [hunk 1]
```diff
@@ -103,7 +104,7 @@ private CompletableFuture<byte[]> handleAtomixRequest(
     final var completableFuture = new CompletableFuture<byte[]>();
     actor.call(
         () -> {
-          final var requestId = requestCount.getAndIncrement();
+          final long requestId = UUID.randomUUID().getMostSignificantBits();
```
Comment (deepthidevaki) [inline transport/src/main/java/io/camunda/zeebe/transport/impl/AtomixServerTransport.java:107]: :x: Getting most significant 64 bit of a 128bit UUID is does not guarantee uniqueness. If we are using UUID we should use the full 128 bits, which in this case is not possible.

I'm thinking of using something like [snowflake id](https://en.wikipedia.org/wiki/Snowflake_ID) which encodes timestamps and nodeid to ensure uniqueness. That said, we don't care about making the id unique over time. It is enough if the id is unique with in a specific period - say a few hours or days. So if we can find something simpler than snowflake id that would be also ok.

Comment (npepinpe) [reply transport/src/main/java/io/camunda/zeebe/transport/impl/AtomixServerTransport.java:107]: Agrona has a built-in Snowflake ID generator, which is a single long, so it would be an easy fix.

Comment (deepthidevaki) [reply transport/src/main/java/io/camunda/zeebe/transport/impl/AtomixServerTransport.java:107]: > Agrona has a built-in Snowflake ID generator, which is a single long, so it would be an easy fix.

Great :tada:  Then it would be easy to use it.

Comment (npepinpe) [reply transport/src/main/java/io/camunda/zeebe/transport/impl/AtomixServerTransport.java:107]: They have an `IdGenerator` interface which we can use as base type if we don't want to fully commit to Snowflake IDs :smile:

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Cool. :rocket:  LGTM, but requesting change to add a test for this.

:x: It would be good to write a simple test to verify uniqueness of the ID.
:x: Please update the PR title and description to reflect the new fix. 

:thought_balloon: By using default nodebits=10, we can have maximum of 1024 brokers. Was wondering if we should adjust that. It is not a problem now, so we can also adjust it later. Since we don't need to ensure uniqueness of the id overtime, it would be ok to make a breaking change then.

**Comment by rodrigo-lourenco-lopes** [comment]
> using default nodebits=10, we can have maximum of 1024 brokers. Was wondering if we should adjust that. It is not a problem now, so we can also adjust it later. Since we don't need to ensure uniqueness of the id overtime, it would be ok to make a breaking change then.

@deepthidevaki The default implementation supports 69 years of loop starting from 1970, it should be enough I think 🤔

**Comment by deepthidevaki** [comment]
>  The default implementation supports 69 years of loop starting from 1970, it should be enough I think 🤔

Good point. It doesn't hurt to start the timestamp offset from today.

**Review by deepthidevaki — APPROVED** [review]
:rocket: Please fix the checkstyle error reported by CI before merging.

**Comment by rodrigo-lourenco-lopes** [comment]
bors merge

**Comment by oleschoenburg** [comment]
@rodrigo-lourenco-lopes Please update the PR title to not refer to UUIDs. This makes it easier to find this PR in the future and might also help in generating a clean changelog.

**Comment by rodrigo-lourenco-lopes** [comment]
> @rodrigo-lourenco-lopes Please update the PR title to not refer to UUIDs. This makes it easier to find this PR in the future and might also help in generating a clean changelog.

Great catch, thanks 🙌

**Comment by deepthidevaki** [comment]
@rodrigo-lourenco-lopes We should backport this as it is bug affecting all older versions.
