### PR TITLE
fix: provide latest user task properties to UTL job headers

### LINKED ISSUE #27177: User task listener job headers include initial properties after they been cleared
## Describe the bug:

User task listener headers incorrectly retain initial property values after these
properties are cleared after task update or unassignment.
Listener headers should reflect the most recent (fresh) user task state.

This issue causes properties (such as `assignee`, `candidateGroups`, `candidateUsers`, `dueDate`, and `followUpDate`) with their initial values to appear in listener job headers, leading to inconsistencies between the task's actual state and the propagated data to listener job headers.

## To reproduce:

<details><summary>Test 1: Cleared properties were provided to <code>completing</code> listener job headers after user task was updated</summary>

### 
```java
  @Test
  public void
  shouldNotIncludeEmptyOrClearedUserTaskPropertiesInCompletingListenerHeadersAfterTaskUpdate() {
    // given: a process instance with a user task configured with an initial assignee, candidate
    // users/groups, due/follow-up dates, and a `completing` listener
    final long processInstanceKey =
        createProcessInstance(
            createProcessWithZeebeUserTask(
                userTask ->
                    userTask
                        .zeebeAssignee("admin")
                        .zeebeCandidateUsers("user_A, user_B")
                        .zeebeCandidateGroups("group_A, group_C, group_F")
                        .zeebeDueDate("2085-09-21T11:22:33+02:00")
                        .zeebeFollowUpDate("2095-09-21T11:22:33+02:00")
                        .zeebeTaskListener(listener -> listener.completing().type(listenerType))));

    final var changes =
        new UserTaskRecord()
            // Clear candidate groups and users, due date, and follow-up date
            .setCandidateGroupsList(List.of())
            .setCandidateUsersList(List.of())
            .setDueDate("")
            .setFollowUpDate("")
            // Update priority
            .setPriority(1);

    // when: updating the user task with the specified changes
    ENGINE.userTask().ofInstance(processInstanceKey).update(changes);

    // and: completing the user task
    final var userTaskCommand = ENGINE.userTask().ofInstance(processInstanceKey).complete();

    // then: validate the headers of the completing listener job triggered after the task update
    final var activatedListenerJob = activateJob(processInstanceKey, listenerType);

    assertThat(activatedListenerJob.getCustomHeaders())
        .describedAs(
            "Headers should include only the configured, updated or automatically set user task properties")
        .containsOnly(
            // Assignee remains unchanged
            entry(Protocol.USER_TASK_ASSIGNEE_HEADER_NAME, "admin"),
            // Task key is always included
            entry(Protocol.USER_TASK_KEY_HEADER_NAME, String.valueOf(userTaskCommand.getKey())),
            // Default action value for the completing operation
            entry(Protocol.USER_TASK_ACTION_HEADER_NAME, "complete"),
            // Updated priority
            entry(Protocol.USER_TASK_PRIORITY_HEADER_NAME, "1"))
        .describedAs(
            "Headers should not include not configured or cleared properties such as candidate groups, candidate users, due date, and follow-up date")
        .doesNotContainKeys(
            Protocol.USER_TASK_CANDIDATE_GROUPS_HEADER_NAME,
            Protocol.USER_TASK_CANDIDATE_USERS_HEADER_NAME,
            Protocol.USER_TASK_DUE_DATE_HEADER_NAME,
            Protocol.USER_TASK_FOLLOW_UP_DATE_HEADER_NAME);
  }
```

### Expected behavior:
The listener job headers should only include the most recent user task properties. Cleared properties should not appear in the headers.

### Observed behavior:
Headers incorrectly include initial properties such as `candidateGroups`, `candidateUsers`, `dueDate`, and `followUpDate` that were cleared during the task update.

</details>

<details><summary>Test 2: Initial assignee was provided to <code>assigning</code> listener job headers after unassignment transition was triggered</summary>

```java
  @Test
  public void
  shouldNotIncludeEmptyOrClearedUserTaskPropertiesInAssigningListenerHeadersAfterTaskUnassignment() {
    // given: a process instance with a user task configured with an initial assignee and an
    // `assigning` listener
    final long processInstanceKey =
        createProcessInstance(
            createProcessWithZeebeUserTask(
                userTask ->
                    userTask
                        .zeebeAssignee("initial_assignee")
                        .zeebeTaskListener(listener -> listener.assigning().type(listenerType))));

    final var createdUserTaskRecord =
        RecordingExporter.userTaskRecords(UserTaskIntent.CREATED)
            .withProcessInstanceKey(processInstanceKey)
            .getFirst();

    final var assigningListenerJob = activateJob(processInstanceKey, listenerType);

    // assert the headers of the assigning listener job triggered after the user task creation
    final var userTaskKey = String.valueOf(createdUserTaskRecord.getKey());
    assertThat(assigningListenerJob.getCustomHeaders())
        .describedAs("Headers should not contain empty or non-configured properties")
        .doesNotContainKeys(
            Protocol.USER_TASK_ACTION_HEADER_NAME,
            Protocol.USER_TASK_CANDIDATE_GROUPS_HEADER_NAME,
            Protocol.USER_TASK_CANDIDATE_USERS_HEADER_NAME,
            Protocol.USER_TASK_DUE_DATE_HEADER_NAME,
            Protocol.USER_TASK_FOLLOW_UP_DATE_HEADER_NAME)
        .describedAs(
            "Headers should include only configured, default or automatically set user task properties")
        .containsOnly(
            // Task key is always included
            entry(Protocol.USER_TASK_KEY_HEADER_NAME, userTaskKey),
            // Assignee should match the initial value
            entry(Protocol.USER_TASK_ASSIGNEE_HEADER_NAME, "initial_assignee"),
            // Default priority is propagated
            entry(Protocol.USER_TASK_PRIORITY_HEADER_NAME, "50"));

    // Complete the assigning listener job triggered after the user task creation
    completeJobs(processInstanceKey, listenerType);

    // when: unassigning the user task
    ENGINE.userTask().ofInstance(processInstanceKey).unassign();

    // then
    final var unassigningListenerJob = activateJob(processInstanceKey, listenerType);
    assertThat(unassigningListenerJob.getCustomHeaders())
        .describedAs(
            "Headers should not include the 'assignee' property, as it is cleared during unassignment")
        .doesNotContainKeys(Protocol.USER_TASK_ASSIGNEE_HEADER_NAME)
        .describedAs("Headers should not contain other empty or non-configured properties")
        .doesNotContainKeys(
            Protocol.USER_TASK_CANDIDATE_GROUPS_HEADER_NAME,
            Protocol.USER_TASK_CANDIDATE_USERS_HEADER_NAME,
            Protocol.USER_TASK_DUE_DATE_HEADER_NAME,
            Protocol.USER_TASK_FOLLOW_UP_DATE_HEADER_NAME)
        .describedAs(
            "Headers should include only configured, default or automatically set user task properties")
        .containsOnly(
            // Task key is always included
            entry(Protocol.USER_TASK_KEY_HEADER_NAME, userTaskKey),
            // Priority remains unchanged
            entry(Protocol.USER_TASK_PRIORITY_HEADER_NAME, "50"),
            // Action set to "unassign"
            entry(Protocol.USER_TASK_ACTION_HEADER_NAME, "unassign"));
  }
```

### Expected behavior:
After unassignment transition was triggered, the listener headers should not include the `assignee` property as it was cleared.

### Observed behavior:
Headers incorrectly include the outdated `assignee` value, even though it was cleared during unassignment.

</details>

## Environment:
- OS: MacOS
- Zeebe Version: 8.7.0-alpha3

## Proposed fix:
- Modify the user task listener job creation logic to only propagate the current (fresh) state of user task properties to the user task listener job headers.

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

This pull request resolves inconsistencies in user task listener job headers by ensuring that they reflect the most recent state of user task properties.

Previously, initial values provided during user task creation were retained in listener job headers after properties were cleared during user task unassignment, update, or after applying corrections.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #27177

### CODE REVIEW

**Review by ana-vinogradova-camunda — APPROVED** [review]
Changes make sense to me, good catch! 
Love the tests and the coverage 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/listeners/task/TaskListenerTest.java [hunk 1]
```diff
@@ -817,6 +817,132 @@ public void shouldUseUpdatedUserTaskDataInCompleteTaskListenerJobHeadersAfterTas
...
+            entry(Protocol.USER_TASK_ACTION_HEADER_NAME, "complete"),
+            // Updated priority
+            entry(Protocol.USER_TASK_PRIORITY_HEADER_NAME, "1"))
+        .describedAs(
+            "Headers should not include not configured or cleared properties such as candidate groups, candidate users, due date, and follow-up date")
+        .doesNotContainKeys(
+            Protocol.USER_TASK_CANDIDATE_GROUPS_HEADER_NAME,
+            Protocol.USER_TASK_CANDIDATE_USERS_HEADER_NAME,
+            Protocol.USER_TASK_DUE_DATE_HEADER_NAME,
+            Protocol.USER_TASK_FOLLOW_UP_DATE_HEADER_NAME);
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/listeners/task/TaskListenerTest.java:875]: ❓ I'm wondering whether it makes more sense to add all of them to task listener jobs regardless, but with empty or null values. This could help clarify to the user that they understand that the property's value correctly. What do you think?

**Review by korthout — APPROVED** [review]
Nice work @ce-dmelnych 🚀 

👍 I really like the improvements to the `verifyUserTaskDataPropagationAcrossListenerJobHeaders` test method.

🔧 I'd like us to consider whether task listener jobs should provide all properties as custom headers regardless of their value.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/listeners/task/TaskListenerTest.java (hunk 1 above)
Comment (korthout) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/listeners/task/TaskListenerTest.java:875]: That's a great point! This is also more efficient (less data). Let's cover it there in #25890
