### PR TITLE
fix: create incident if single outgoing sequence flow has no matching condition

### LINKED ISSUE #13936: Condition ignored on Inclusive Gateway with singular outgoing Sequence Flow
**Describe the bug**

It seems that an Inclusive Gateway with a single outgoing Sequence Flow ignores the Condition

Screenshot 2023-08-17 at 09 52 07

The BPMN spec is quite clear about the expected behavior:

> A default path can optionally be identified, to be taken in the event that none of the conditional `Expressions` evaluate to `true`. If a default path is not specified and the **Process** is executed such that none of the conditional `Expressions` evaluates to `true`, a runtime exception occurs. - [10.6.3 Inclusive Gateway](https://www.omg.org/spec/BPMN/2.0.2/PDF#10.6.3%20Inclusive%20Gateway)

For C8, such a runtime exception should be represented by [an incident](https://docs.camunda.io/docs/next/components/concepts/incidents/) at the inclusive gateway.

Originally reported on the forums: https://forum.camunda.io/t/strange-behavior-with-only-one-sequence-flow-with-condition/46938

**To Reproduce**

- deploy a process with an inclusive gateway that has one outgoing sequence flow with the condition `= false`
- create an instance of it
- notice that the sequence flow is taken and that no incident is raised

**Expected behavior**

An incident is raised at the inclusive gateway

### PR DESCRIPTION
**Pull request by lzgabel**
## Description

This PR adds support of inclusive gateway with single outgoing Sequence Flow has no matching condition, then we should create incident.

## Related issues

closes #13936

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by lzgabel** [comment]
Hi @korthout. Please take a moment to check this out. :bow:

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayProcessor.java [hunk 1]
```diff
@@ -93,8 +93,8 @@ private Either<Failure, List<ExecutableSequenceFlow>> findSequenceFlowsToTake(
       return Either.right(null);
     }
 
-    if (element.getOutgoing().size() == 1) {
-      // only one flow can just be taken
+    if (element.getOutgoing().size() == 1 && element.getOutgoing().get(0).getCondition() == null) {
+      // only one flow without a condition, can just be taken
```
Comment (nicpuppa) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayProcessor.java:97]: 🔧 Small update
```suggestion
      // only one flow without a condition can be taken
```

**Review by nicpuppa — APPROVED** [review]
Hi @lzgabel, thank for the contribution 🚀 

LGTM 👍 

Just left some suggestion, please have a look 👀

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayProcessor.java (hunk 1 above)
Comment (lzgabel) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayProcessor.java:97]: Let's keep the status quo. 😄 

https://github.com/camunda/zeebe/blob/26a44bdeaec381c988baee50a7e80ca0de7a48fb/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/ExclusiveGatewayProcessor.java#L93-L94

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayProcessor.java [hunk 2]
```diff
@@ -93,8 +93,8 @@ private Either<Failure, List<ExecutableSequenceFlow>> findSequenceFlowsToTake(
       return Either.right(null);
     }
 
-    if (element.getOutgoing().size() == 1) {
-      // only one flow can just be taken
+    if (element.getOutgoing().size() == 1 && element.getOutgoing().get(0).getCondition() == null) {
```
[the remark this answers is not in the document]
Comment (nicpuppa) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayProcessor.java:96]: Awesome! 👍

**Comment by lzgabel** [comment]
Hi @nicpuppa. I've applied your review hints. Please check this out. :heart:

**Review by nicpuppa — APPROVED** [review]
Great work @lzgabel 💪

**Comment by lzgabel** [comment]
> bord merge

❓ bors merge

**Comment by nicpuppa** [comment]
bors merge 😂

**Comment by nicpuppa** [comment]
bors retry

**Comment by lzgabel** [comment]
Hi @nicpuppa. We need to backport to `8.2`.

**Comment by korthout** [comment]
@nicpuppa There are conflicts on cherry-picking to both of the branches, you'll have to backport manually and resolve the conflicts by hand.
