### PR TITLE
fix: `MigrationSnapshotDirector` health status is propagated correctly  

### LINKED ISSUE #39751: `TopologyFaultToleranceTest` is slow, can take up to 2 minutes
`TopologyFaultToleranceTest` may be slower that it should be as it can take around 1m30s to run in the CI.

There may be some simple things to change (such as config) to speed it up.

For example, `engineDistribution` config may be quicked to perform more retries:

```java
  final var engineDistribution = config.getExperimental().getEngine().getDistribution();
  engineDistribution.setMaxBackoffDuration(Duration.ofSeconds(1));
  engineDistribution.setRedistributionInterval(Duration.ofMillis(200));
```

## Impact
Slow  CI builds

### PR DESCRIPTION
**Pull request by entangled90**
## Description
The `MigrationSnapshotDirector` would sometimes not notify its `HealthStatus` on changes to the `CriticalComponentHealthMonitor`. 
As a result, a partition may become healthy only when the scheduled tasks recomputed the health check of all components, leading to a long test duration.

## Checklist

- [X] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #39751

### CODE REVIEW

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/MigrationSnapshotDirector.java [hunk 1]
```diff
@@ -96,7 +96,9 @@ public HealthReport getHealthReport() {
 
   @Override
   public void addFailureListener(final FailureListener failureListener) {
+    LOG.info("Added failure listener {}", failureListener);
```
Comment (panagiotisgts) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/MigrationSnapshotDirector.java]: Is that a debug log maybe?

File: zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/health/CriticalComponentsHealthMonitor.java [hunk 2]
```diff
@@ -107,6 +107,7 @@ public void removeComponent(final HealthMonitorable component) {
             graphListener.unregisterRelationship(componentName, name);
             graphListener.unregisterNode(monitoredComponent.component);
             log.trace("Unregistered edge {}:{}", name, componentName);
+            calculateHealth();
```
Comment (panagiotisgts) [inline zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/health/CriticalComponentsHealthMonitor.java:110]: ❓  Could this cause a _snowball_ effect during normal operation in state changes since components are getting removed/added during that window?

Introducing delays until you eventually have a stable state again?

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/MigrationSnapshotDirector.java (hunk 1 above)
Comment (entangled90) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/MigrationSnapshotDirector.java]: Even trace actually :-D

File: zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/health/CriticalComponentsHealthMonitor.java (hunk 2 above)
Comment (entangled90) [reply zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/health/CriticalComponentsHealthMonitor.java:110]: This might increase the number of state changes when shutting down components (I assume this happens on partition transitions most of the times).
In general if there are healthy components registered, then the partition state will still be healthy :shrug: 
When no components are registered, then the partition is not healthy, but that is already the case as we have the
```Services not installed``` error when the partition hasn't started completely yet.

**Review by panagiotisgts — APPROVED** [review]
LGTM!
