### PR TITLE
`LogStream` and its readers and writers are built synchronously

### LINKED ISSUE #10227: NPE "this.appenderFuture" is null when closing the partition
**Description**

The following message is logged as a failure:

```
java.lang.NullPointerException: 
    Cannot invoke "io.camunda.zeebe.util.sched.future.ActorFuture.complete(Object)" 
    because "this.appenderFuture" is null
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$openAppender$7(LogStreamImpl.java:310)
```

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.util.sched.future.ActorFuture.complete(Object)" because "this.appenderFuture" is null
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$openAppender$7(LogStreamImpl.java:310) ~[zeebe-logstreams-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:82) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.4.jar:8.0.4]
```

</p>
</details>

The message is logged after a partition is transitioned to `LEADER` and back to `INACTIVE` in a short time (< 5s). 

However, the broker was able to transition to `INACTIVE` successfully. We can consider the log statement as noise and should omit it.  

[Log](https://drive.google.com/file/d/1o7-5Y3js1vqSYn2xUimy-q3VNs58lFrf/view?usp=sharing)

Related to #8757

**Environment:**
- Zeebe Version: `8.0.4`
- Camunda SaaS

### LINKED ISSUE #12254: NPE when receiving a log stream writer while shutting down
**Describe the bug**

There seems to be a slight race condition when partitions are transitioning to leader while shutting down (note: this may also occur while transitioning to follower, but I haven't observed it).

In various places, we try to get a log stream writer. When the future completes, we assume that no error means there is something. Turns out that while shutting down, we seem to have some race conditions, because the writer returned is sometimes null (which is fine during shutdown).

This triggers 3 different but related NPEs (see stack traces below). Note that for other actors, an error is propagated instead, which hints at a race condition:

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Actor is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.createNewLogStreamWriter(LogStreamImpl.java:191) ~[zeebe-logstreams-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamWriter(LogStreamImpl.java:175) ~[zeebe-logstreams-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiServiceImpl.lambda$onBecomingLeader$3(CommandApiServiceImpl.java:112) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:75) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

</p></details>

**To Reproduce**

**Expected behavior**

There is no unnecessary noisy errors. We also don't expect race conditions in our startup/shutdown, so I would have expected the shutdown to wait for the writer to have been initially obtained, then the ongoing transition step to finish, and then shutdown to occur.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: value cannot be null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:602) ~[agrona-1.18.0.jar:1.18.0]
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiRequestHandler.lambda$addPartition$0(CommandApiRequestHandler.java:149) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT] 
```

</p>
</details>

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: value cannot be null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:602) ~[agrona-1.18.0.jar:1.18.0]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:588) ~[agrona-1.18.0.jar:1.18.0]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:44) ~[agrona-1.18.0.jar:1.18.0]
	at io.camunda.zeebe.broker.transport.queryapi.QueryApiRequestHandler.lambda$addPartition$0(QueryApiRequestHandler.java:62) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

</p>
</details>

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.scheduler.future.ActorFuture.complete(Object)" because "this.appenderFuture" is null
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$openAppender$6(LogStreamImpl.java:282) ~[zeebe-logstreams-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.2.0-SNAPSHOT

### LINKED ISSUE #12870: Race condition when closing the log stream and opening a writer
**Describe the bug**

There is currently a race condition between closing the log stream and opening a writer. This comes from the fact that we close the appender while the log stream is still in the STARTED phase. Only when the appender is closed do we close the log stream. This means calls to `closeAppender` and, say, `newLogStreamWriter` can be interleaved, resulting in the completion of the second call attempting to complete the now null `appenderFuture`.

Low severity because it mostly leads to noisy error logs.

**To Reproduce**

Not easy to reliably reproduce, as it has to do with a specific scheduling of asynchronous operations.

**Expected behavior**

The appender is closed as part of the log stream's closing phase, and no new writers/readers can be created in closing.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.scheduler.future.ActorFuture.complete(Object)" because "this.appenderFuture" is null
at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$openAppender$6 ( [io/camunda.zeebe.logstreams.impl.log/LogStreamImpl.java:282](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.logstreams.impl.log%2FLogStreamImpl.java&line=282&project=camunda-saas-dev) )
at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run ( [io/camunda.zeebe.scheduler.future/FutureContinuationRunnable.java:28](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler.future%2FFutureContinuationRunnable.java&line=28&project=camunda-saas-dev) )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( [io/camunda.zeebe.scheduler/ActorJob.java:94](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorJob.java&line=94&project=camunda-saas-dev) )
at io.camunda.zeebe.scheduler.ActorJob.execute ( [io/camunda.zeebe.scheduler/ActorJob.java:45](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorJob.java&line=45&project=camunda-saas-dev) )
at io.camunda.zeebe.scheduler.ActorTask.execute ( [io/camunda.zeebe.scheduler/ActorTask.java:119](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorTask.java&line=119&project=camunda-saas-dev) )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( [io/camunda.zeebe.scheduler/ActorThread.java:106](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorThread.java&line=106&project=camunda-saas-dev) )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( [io/camunda.zeebe.scheduler/ActorThread.java:87](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorThread.java&line=87&project=camunda-saas-dev) )
at io.camunda.zeebe.scheduler.ActorThread.run ( [io/camunda.zeebe.scheduler/ActorThread.java:198](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorThread.java&line=198&project=camunda-saas-dev) )
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.3.0-alpha1

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Since removing the Dispatcher a while ago, there's not much reason for the `LogStream` and related classes such as `LogStreamBuilder` to be actors and return futures.

This PR removes this aspect, simplifying the implementation and also call-sites. Perhaps most significantly, I've removed most health monitoring of the `LogStream` as this component itself is not doing anything except holding on to writers and readers and does not have any failure cases.

## Related issues

relates to #17547
closes #12254
closes #10227
closes #12870

### CODE REVIEW

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartitionAdminAccess.java [hunk 1]
```diff
@@ -183,21 +183,8 @@ public ActorFuture<Void> banInstance(final long processInstanceKey) {
...
-                        LOG.error(
-                            "Could not retrieve writer to write error record for process instance.",
-                            error);
-                        future.completeExceptionally(error);
-                        return;
-                      }
-
-                      writeErrorEventAndBanInstance(processInstanceKey, writer, future);
-                    });
+            final var logStreamWriter = adminControl.getLogStream().newLogStreamWriter();
```
Comment (npepinpe) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartitionAdminAccess.java:186]: :question: Previous behavior was to fail the future if the writer cannot be obtained (e.g. log stream is closed). Now, we will throw an exception here, which may end up failing the concurrency control (if it's an actor)? Or what happens here?

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/BackupApiRequestHandlerStep.java [hunk 2]
```diff
@@ -48,16 +48,8 @@ public String getName() {
...
-    writerFuture.onComplete(
-        (logStreamRecordWriter, error) -> {
-          if (error == null) {
-            createBackupApiRequestHandler(context, installed, logStreamRecordWriter);
-          } else {
-            installed.completeExceptionally(error);
-          }
-        });
-
+    final var logStreamRecordWriter = context.getLogStream().newLogStreamWriter();
```
Comment (npepinpe) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/BackupApiRequestHandlerStep.java:51]: :question: Same as above, what happens here if the logstream is closed?

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/InterPartitionCommandServiceStep.java [hunk 3]
```diff
@@ -87,23 +87,22 @@ private void waitForSenderToStart(
 
   private ActorFuture<Void> installReceiver(final PartitionTransitionContext context) {
     final ActorFuture<Void> future = context.getConcurrencyControl().createFuture();
-
+    final var logStreamWriter = context.getLogStream().newLogStreamWriter();
```
Comment (npepinpe) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/InterPartitionCommandServiceStep.java:90]: :question: If log stream is closed, will I fail the partition entirely due to an unhandled exception?

**Review by npepinpe — APPROVED** [review]
:+1: Approving as it's generally good, but please address questions :)

:question: We used to handle errors when fetching the writer, since the log stream might be closed at that point. That forced us to handle the possible errors at that point, where, for example, in ExporterDirector we would just close the actor. I think the current behavior is the same in most places, but not sure - and it might be unexpected in some others. Please address my questions, as I wasn't 100% sure honestly of the new behavior.

I think this also closes:
- https://github.com/camunda/camunda/issues/12254
- https://github.com/camunda/camunda/issues/10227

I think this _might_ close the following, but not sure:
- https://github.com/camunda/camunda/issues/12870
-

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartitionAdminAccess.java (hunk 1 above)
Comment (lenaschoenburg) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartitionAdminAccess.java:186]: Caught be the surrounding try-catch block and handled gracefully.

Comment (npepinpe) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartitionAdminAccess.java:186]: Oh god, I thought the try catch was part of the removed code :see_no_evil: My bad

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/BackupApiRequestHandlerStep.java (hunk 2 above)
Comment (lenaschoenburg) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/BackupApiRequestHandlerStep.java:51]: This is executed by the `ZeebePartition` actor, which handles all failed actor jobs in `onInstallFailure`. In our case this ends up at `handleRecoverableFailure` which ultimately steps down and makes the partition inactive.

This is the same that would have happened before. The install future would have completed exceptionally, which `ZeebePartition#leaderTransition` handles by calling `onInstallFailure`.

This is now less explicit than before so let me know if you'd prefer a try-catch block to explicitly complete the future exceptionally instead of going through `ZeebePartition#handleFailure`.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/InterPartitionCommandServiceStep.java (hunk 3 above)
Comment (lenaschoenburg) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/InterPartitionCommandServiceStep.java:90]: Same as for the `BackupApiRequestHandlerStep`: the end result is the same because this exception would be handled by `ZeebePartition#onInstallFailure`. The only difference is that we now rely on `ZeebePartition#handleFailure` instead of the error handling callback in `ZeebePartition#leaderTransition`.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/BackupApiRequestHandlerStep.java (hunk 2 above)
Comment (lenaschoenburg) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/BackupApiRequestHandlerStep.java:51]: To be fair, it's something I wasn't sure about either and I should have checked it before opening the PR :sweat_smile:
