### PR TITLE
Adjust C8 API search naming

### LINKED ISSUE #28791: Name search endpoints consistently
**Description**

All C8 REST API endpoints in the [OpenAPI description](https://github.com/camunda/camunda/edit/main/zeebe/gateway-protocol/src/main/proto/rest-api.yaml) should consistently use "search" wording in descriptions, paths, operation IDs, and summaries.

The endpoints currently use a mixture of "search", "query", and "find".

**Note**

If we adjust the existing DTO names for this, we could introduce regressions for generated REST API clients that use the generated models. If this only affects endpoints marked as alpha features, that would be fine.

### LINKED ISSUE #28814: Name search commands consistently
**Description**

All search commands use "search" wording in method names, descriptions, and parameters.

The commands currently use a mixture of "search", "query", and "find".

**Note**

This will introduce regressions for downstream users of the methods. This only affects methods marked as experimental, so this is fine.

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

* Streamline the names of REST search endpoints and Java client classes to align on "search", replacing "find" and "query" where appropriate.
* REST DTOs named "...Query" remain where appropriate (the term is fine since it's the query part of the search request). This avoids unnecessary code changes and further breaking changes for custom REST clients, generating their data model from the OpenAPI spec.
* This breaks existing client API commands (all in alpha feature state before 8.8) - this is acceptable.
* The `ZeebeClient` classes stay untouched to retain the migration path for Zeebe client users from 8.7. Moving to the Camunda client brings the breaking changes to Zeebe client commands marked as experimental API.
* This breaks existing URLs in the public reference documentation - this will receive a follow-up in the https://github.com/camunda/camunda-docs/ repository to add redirects with https://github.com/camunda/camunda-docs/issues/5093.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #28791 
closes #28814

### CODE REVIEW

File: clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/DecisionDefinitionQuery.java [hunk 1]
```diff
@@ -15,13 +15,13 @@
...
 
+import io.camunda.client.api.search.request.DecisionDefinitionSearchRequest;
 import io.camunda.zeebe.client.api.search.filter.DecisionDefinitionFilter;
 import io.camunda.zeebe.client.api.search.response.DecisionDefinition;
 import io.camunda.zeebe.client.api.search.sort.DecisionDefinitionSort;
 
 /**
- * @deprecated since 8.8 for removal in 8.9, replaced by {@link
- *     io.camunda.client.api.search.query.DecisionDefinitionQuery}
+ * @deprecated since 8.8 for removal in 8.9, replaced by {@link DecisionDefinitionSearchRequest}
```
Comment (houssain-barouni) [inline clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/DecisionDefinitionQuery.java:24]:
```suggestion
 * @deprecated since 8.8 for removal in 8.9, replaced by {@link io.camunda.client.api.search.request.DecisionDefinitionSearchRequest}
```
I prefer not mixing the imports with different namespaces

File: clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/DecisionRequirementsQuery.java [hunk 2]
```diff
@@ -16,13 +16,13 @@
...
 
+import io.camunda.client.api.search.request.DecisionRequirementsSearchRequest;
 import io.camunda.zeebe.client.api.search.filter.DecisionRequirementsFilter;
 import io.camunda.zeebe.client.api.search.response.DecisionRequirements;
 import io.camunda.zeebe.client.api.search.sort.DecisionRequirementsSort;
 
 /**
- * @deprecated since 8.8 for removal in 8.9, replaced by {@link
- *     io.camunda.client.api.search.query.DecisionRequirementsQuery}
+ * @deprecated since 8.8 for removal in 8.9, replaced by {@link DecisionRequirementsSearchRequest}
```
Comment (houssain-barouni) [inline clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/DecisionRequirementsQuery.java:25]: same here

File: clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/FlownodeInstanceQuery.java [hunk 3]
```diff
@@ -15,13 +15,13 @@
...
 
+import io.camunda.client.api.search.request.FlownodeInstanceSearchRequest;
 import io.camunda.zeebe.client.api.search.filter.FlownodeInstanceFilter;
 import io.camunda.zeebe.client.api.search.response.FlowNodeInstance;
 import io.camunda.zeebe.client.api.search.sort.FlownodeInstanceSort;
 
 /**
- * @deprecated since 8.8 for removal in 8.9, replaced by {@link
- *     io.camunda.client.api.search.query.FlownodeInstanceQuery}
+ * @deprecated since 8.8 for removal in 8.9, replaced by {@link FlownodeInstanceSearchRequest}
```
Comment (houssain-barouni) [inline clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/FlownodeInstanceQuery.java:24]: and here

File: clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/IncidentQuery.java [hunk 4]
```diff
@@ -15,13 +15,13 @@
...
 
+import io.camunda.client.api.search.request.IncidentSearchRequest;
 import io.camunda.zeebe.client.api.search.filter.IncidentFilter;
 import io.camunda.zeebe.client.api.search.response.Incident;
 import io.camunda.zeebe.client.api.search.sort.IncidentSort;
 
 /**
- * @deprecated since 8.8 for removal in 8.9, replaced by {@link
- *     io.camunda.client.api.search.query.IncidentQuery}
+ * @deprecated since 8.8 for removal in 8.9, replaced by {@link IncidentSearchRequest}
```
Comment (houssain-barouni) [inline clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/IncidentQuery.java:24]: and here

**Review by houssain-barouni — DISMISSED** [review]
LGTM! 👍 
Just a minor comment

File: clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/DecisionDefinitionQuery.java (hunk 1 above)
Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/zeebe/client/api/search/query/DecisionDefinitionQuery.java]: Good catch, totally agree, classic IDE auto-adjustment. Changed with https://github.com/camunda/camunda/pull/30219/commits/530eab88dd90ea689c11aa4481c3c9cbf5aa33b2.

**Comment by tmetzke** [comment]
@houssain-barouni, thanks for reviewing. I also added an ArchUnit test regarding naming with https://github.com/camunda/camunda/pull/30219/commits/530eab88dd90ea689c11aa4481c3c9cbf5aa33b2, maybe you can give it a quick look as well. Just to be sure I didn't overlook anything 🙂

**Review by houssain-barouni — APPROVED** [review]
LGTM!
