### PR TITLE
java-client: Fix job worker polling schedule

### LINKED ISSUE #6294: java-client job worker has problems with completing all activated jobs
**Describe the bug**
After short while after merging #6093, I had a feeling that I should run a benchmark to verify that it doesn't affect the performance negatively. Perhaps we needed to reconfigure the workers for our use case. Testing it at this scale showed that the current java-client is unable to complete all activated jobs in our benchmark.

**To Reproduce**
- rebuild the benchmark worker docker image and push the tag
- create 2 new benchmarks
- stop starters, wait a bit and stop workers to make sure all processing has finished
- switch worker to new tagged image on 1 of the benchmarks, leaving the other alone as baseline
- start workers, wait a bit and start starters
- look at zeebe dashboard

**Expected behavior**
New java client should be able to complete at least as many jobs as the baseline

**Metrics**

<details><summary>Grafana Dashboard</summary>
 <p>

Note: starters stopped at 10:42

Baseline | New Client
---------|------------
Screenshot 2021-02-10 at 11 00 28 | Screenshot 2021-02-10 at 11 00 31
Screenshot 2021-02-10 at 10 59 49 | Screenshot 2021-02-10 at 10 59 55

</p>
</details>

**Environment:**
 - OS: Zeebe Benchmark
 - Zeebe Version: develop @ d540f968d

### PR DESCRIPTION
**Pull request by korthout**
## Description

- fixes the poll scheduling
- improves the benchmark config to reduce the number of ActivateJobs requests

For reviewer: see commit messages

## Related issues

fixes #6294 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [x] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by korthout** [comment]
Benchmark results:

Baseline | Bugged develop | Fix + new config 
---------|-----------------|-----------------
Screenshot 2021-02-12 at 19 46 59 | Screenshot 2021-02-12 at 19 50 15 | Screenshot 2021-02-12 at 19 46 30

File: benchmarks/project/src/main/java/io/zeebe/Worker.java [hunk 1]
```diff
@@ -62,12 +64,13 @@ public void run() {
...
                     try {
                       Thread.sleep(completionDelay);
-                    } catch (Exception e) {
+                    } catch (final Exception e) {
                       e.printStackTrace();
                     }
                     requestFutures.add(command.send());
                   }
                 })
+            .backoffSupplier(newBackoffBuilder().minDelay(250L).backoffFactor(2).build())
```
Comment (npepinpe) [inline benchmarks/project/src/main/java/io/zeebe/Worker.java:73]: Any reason to not use the defaults?

File: clients/java/src/main/java/io/zeebe/client/impl/worker/JobWorkerImpl.java [hunk 2]
```diff
@@ -161,7 +161,9 @@ private void poll(final JobPoller jobPoller) {
     // to avoid race conditions that would let us exceed the buffer size
     final int actualRemainingJobs = remainingJobs.get();
     if (!shouldPoll(actualRemainingJobs)) {
+      LOG.debug("Expected to activate for jobs, but still enough remain. Reschedule poll.");
```
Comment (npepinpe) [inline clients/java/src/main/java/io/zeebe/client/impl/worker/JobWorkerImpl.java:164]: This seems like trace level to me - any reason to put it as debug?

**Review by npepinpe — COMMENTED** [review]
I don't understand how this fixes the actual problem? Aren't we still counting remaining jobs in the wrong way? Was the issue just that the pollingInterval was not volatile?

For next time, when doing small changes that fix complex issues (e.g. concurrency issues), it's really useful (at least for dummies like me :sweat_smile:) if you explain the change and how it fixes the issue in the PR :slightly_smiling_face:

File: benchmarks/project/src/main/java/io/zeebe/Worker.java (hunk 1 above)
Comment (korthout) [reply benchmarks/project/src/main/java/io/zeebe/Worker.java:73]: I wrote this commit message:
```
chore(benchmark): configure backoff for workers 

To improve the benchmark, it makes sense to reduce the number of
unnecessary ActivateJobs requests the workers send. This should provide
more resources to actually completing jobs and creating new workflow
instances. The default minDelay of 50ms, is too small for this case
and can easily be increased for our benchmarks.

Even if a request receives a RESOURCE_EXHAUSTED error, the delayed
request had about 50% change that it succeeds afterwards (we actually
want to optimise to increase that chance). So it never get's a real
chance to build up the delay (exponentially). For the benchmark, I
therefore increased the min delay to 250ms and a faster increase at 2
times. Expected intervals are thus: 250ms, 500ms, 1s, 2s, 4s and 5s.

These values seem to reduce the number of ActivateJobs requests by half
compared to the defaults without stressing the workers with too many
jobs.

This might not hold for real world applications.
```

WDYT? Are these sensible values? Should we also change the defaults?

File: clients/java/src/main/java/io/zeebe/client/impl/worker/JobWorkerImpl.java (hunk 2 above)
Comment (korthout) [reply clients/java/src/main/java/io/zeebe/client/impl/worker/JobWorkerImpl.java:164]: You're right, it was for my own debugging. I'll lower the log level

**Comment by korthout** [comment]
> For next time, when doing small changes that fix complex issues (e.g. concurrency issues), it's really useful (at least for dummies like me 😅) if you explain the change and how it fixes the issue in the PR 🙂

I explained the changes in the commit messages. Sorry, I could have pointed you in the right direction in the PR. Please have a look at those and let me know if it makes more sense now

> Was the issue just that the pollingInterval was not volatile

No, but it's a good change to take along I think.

> Aren't we still counting remaining jobs in the wrong way? 

Yes, but onPollSuccess was unable to reschedule if >0 jobs were returned and those jobs were finished before the onPollSuccess was called. That is fixed now. 

WDYT, should we fix the counting of remaining jobs as well now? This was already always broken, but in the past it did not lead to rescheduling issues since it was a fixed periodic schedule.

**Review by npepinpe — CHANGES_REQUESTED** [review]
> > Was the issue just that the pollingInterval was not volatile
> No, but it's a good change to take along I think.

Can you elaborate? What are the impacts of having it volatile vs not?

Is it not possible to have a regression test here?

Finally, imo, I usually expect a description of the PR in the PR itself and not in the commit messages :slightly_smiling_face: If this is your workflow and you think it's better, I'm happy to discuss this but I guess we should just all be aware of this

**Review by npepinpe — APPROVED** [review]

**Comment by korthout** [comment]
I just wanted to recap on what we discussed:

> > > Was the issue just that the pollingInterval was not volatile
> > > No, but it's a good change to take along I think.
> 
> Can you elaborate? What are the impacts of having it volatile vs not?

Multiple threads are reading/writing this value, so we should take care of it.

> 
> Is it not possible to have a regression test here?

I struggled to produce a test that reaches and detects the race condition. We should improve the testability of the implementation. I've opened a new issue to investigate better maintainable implementations: #6380.

> 
> Finally, imo, I usually expect a description of the PR in the PR itself and not in the commit messages 🙂 If this is your workflow and you think it's better, I'm happy to discuss this but I guess we should just all be aware of this

You're absolutely right. I don't know why I didn't this time. I've added a remark to refer to the commit messages in the PR. Next time I'll give a more complex description in the PR again.

**Comment by korthout** [comment]
bors merge
