### PR TITLE
fix(log/appender): yield thread when experiencing backpressure

### LINKED ISSUE #8540: `LogStorageAppender` Actor occupies an Actor Thread forever due to a full backpressue queue
**Describe the bug**

The `LogStorageAppender` subscribes to the write buffer (i.e., `Dispatcher`) to read from it and to append the available fragments to the `LogStorage`:

https://github.com/camunda-cloud/zeebe/blob/73e5c7be9f453e30b5aebc07aae322ee5f82b11e/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java#L151-L154

However, before appending to the `LogStorage`, the `LogStorageAppender` tries to acquire a "token" from a `limiter` (i.e., backpressure queue), and only if a token got acquired it appends to the `LogStorage` (and the read fragments are marked as read in the write buffer). On the other side, if _no_ token got acquired, the fragments are not appended to the `LogStorage` (and the fragments are still marked as not read in the write buffer):

https://github.com/camunda-cloud/zeebe/blob/73e5c7be9f453e30b5aebc07aae322ee5f82b11e/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java#L119-L136

So whenever some fragments are available on the write buffer, the Actor `LogStorageAppender` is submitted to the broker thread group's task queue so that a broker thread can execute this Actor eventually. When executing this Actor, it checks whether there are some fragments are available on the write buffer:

https://github.com/camunda-cloud/zeebe/blob/73e5c7be9f453e30b5aebc07aae322ee5f82b11e/util/src/main/java/io/camunda/zeebe/util/sched/channel/ChannelConsumerCondition.java#L43-L48

and if there are some fragments available, it will execute the corresponding Actor Job (i.e., read from the write buffer and try to append to the `LogStorage`).

The actor job is executed as long as `ChannelConsumerCondition#poll()` returns true.

In a scenario, where the appender's backpressure queue is full (i.e., no token can be acquired from the limiter), the Actor Thread keeps executing the actor job because `ChannelConsumerCondition#poll()` still returns true. And as long as the backpressure is not emptied the Actor Thread will continue executing that job forever.

For example, this can happen in the following case:

1. For a certain partition - where the broker is the leader, the appender's backpressure queue is full (so that no token can be acquired from the limiter)
2. The Actor Thread executes the `LogStorageAppender`s actor job, i.e., it reads from the write buffer and tries to append the `LogStorage` (and `ChannelConsumerCondition#poll()` returns always true, but no token can be acquired)
3. For the same partition, the Raft layer transitions from leader to follower. This submits an Actor Task to ensure that the Zeebe application layer transitions to follower as well (i.e., to ensure that corresponding services are stopped and started).
4. The submitted Actor Task gets assigned to the same thread task queue as the `LogStorageAppender` is already in.

As a consequence, the submitted Actor Task to transition to follower on the Zeebe application layer won't be executed, because the Actor Thread is already occupied by the `LogStorageAppender` Actor which never releases the Actor Thread.

Note: This may also happen in other scenarios in which no leader change happens.

**What is the impact of that issue?**

In the worst case, it can happen that all Actor Threads are occupied by such Actor's (but for different partitions). This results in:

* The broker being stuck in those Actor Jobs and never being able to make progress with any other Actor
* Growing Actor Job Queues, as long as others (e.g., Raft) are able to submit jobs to the Actor Job Queues. That may result in OOMs.
* ...

**Expected behavior**
The `LogStorageAppender` Actor releases the Actor Thread so that other Actor Jobs can be executed.

**Possible Solutions**
* When no token can be acquired because the backpressure queue is full, then resubmit the Actor Task to the actor thread task queue.
* When executing `ChannelConsumerCondition#poll()` take the backpressure queue into account.

**Environment:**
 - Zeebe Version: 1.3.0

---

related to https://jira.camunda.com/browse/SUPPORT-11966

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

Yield the thread, when the log storage appender experiences backpressure when trying to append the fragments to the log storage. That way, the actual actor task (log storage appender) is resubmitted to the working queue, and the actor thread is released to execute other actor tasks.

## Related issues

closes #8540 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [x] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by romansmirnov** [comment]
Dear reviewer, thanks for reviewing my PR 😄 However, writing a test case for this bug fix isn't that easy. It requires controlling different components (like the append limiter, actor thread, ...). In the end, I decided to submit this PR without a test case (and actually I didn't succeed in writing a working test case), because it does not change any existing behavior apart from handling the backpressure gracefully in the log storage appender. Do you see any working approach to test it? I am happy to get your feedback.

**Comment by Zelldon** [comment]
> Dear reviewer, thanks for reviewing my PR smile However, writing a test case for this bug fix isn't that easy. It requires controlling different components (like the append limiter, actor thread, ...). In the end, I decided to submit this PR without a test case (and actually I didn't succeed in writing a working test case), because it does not change any existing behavior apart from handling the backpressure gracefully in the log storage appender. Do you see any working approach to test it? I am happy to get your feedback.

Hey Roman I would like to at least see a benchmark for it. Furthermore how we found this issues? Is there anything how we could reproduce the problem?

**Comment by npepinpe** [comment]
Just my two cents, but if we can't write a test, it may be an indication that the class/unit/component needs to be refactored :smile:

**Comment by romansmirnov** [comment]
As discussed with @Zelldon:

* I already run a benchmark containing that bug fix. The bug fix doesn't have any negative (nor positive) impact in terms of performance.
* The bug has been found when working on a customer's support case, i.e.,  when analyzing the provided heap dump and thread dump. Details can be found here: https://jira.camunda.com/browse/SUPPORT-11966 and #8540 - if necessary, I can do a walkthrough of the heap dump.
* Regarding the test case, we discussed a potential approach to how to test the scenario. However, I will give it a try next week. In the meantime, I would like to get this merged so that the customer can run their tests with a snapshot. (Unless the test case is a blocker for this bug fix.)

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java [hunk 1]
```diff
@@ -178,10 +186,19 @@ public void onActorFailed() {
...
+
+    final var shouldAppendBlock = readBytes > 0;
+    var appendBlockSucceeded = false;
+
+    if (shouldAppendBlock) {
+      appendBlockSucceeded = appendBlock(blockPeek);
+    }
+
+    // Yield the thread, when no bytes are read or
+    // when the block could not be appended.
```
Comment (Zelldon) [inline logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java:200]: :wrench: I think this comment is not necessary. It documents the what, which we can see in the code. It would be useful if we would document the why :)

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java [hunk 2]
```diff
@@ -178,10 +186,19 @@ public void onActorFailed() {
...
 
   private void onWriteBufferAvailable() {
-    final BlockPeek blockPeek = new BlockPeek();
-    if (writeBufferSubscription.peekBlock(blockPeek, maxAppendBlockSize, true) > 0) {
-      appendBlock(blockPeek);
-    } else {
+    final var blockPeek = new BlockPeek();
+    final var readBytes = writeBufferSubscription.peekBlock(blockPeek, maxAppendBlockSize, true);
+
+    final var shouldAppendBlock = readBytes > 0;
```
Comment (Zelldon) [inline logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java:192]: :wrench: NIT: might make sense to call it `canAppend` or `hasToAppend`, since there is a block we can append.

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java [hunk 3]
```diff
@@ -178,10 +186,19 @@ public void onActorFailed() {
...
+    var appendBlockSucceeded = false;
+
+    if (shouldAppendBlock) {
+      appendBlockSucceeded = appendBlock(blockPeek);
+    }
+
+    // Yield the thread, when no bytes are read or
+    // when the block could not be appended.
+    if (!shouldAppendBlock || !appendBlockSucceeded) {
```
Comment (Zelldon) [inline logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java:201]: :question: Is it necessary to yield if we not append? I think the subscription (actor condition) is only called if it was notified right?

**Review by ChrisKujawa — APPROVED** [review]
Thanks @romansmirnov :) :medal_military: 

Had some smaller comments, please take a look before merging. 

I think @npepinpe is right that it might make sense to refactor all of this a bit. But maybe we can write a test as discussed @romansmirnov lets see, ping me if you want to discuss this further. :)

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java (hunk 2 above)
Comment (romansmirnov) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java]: Done

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java (hunk 1 above)
Comment (romansmirnov) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java]: I personally think the comment explains the what and the why 😃 However, I removed the comment.

Comment (Zelldon) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java]: For me it would be more useful why we need to yield. Like without the yield we try in a loop endless after failing to append and no other thread is able to do other work. This will overwhelm the raft thread, since we not react on the backpressure.

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java (hunk 3 above)
Comment (romansmirnov) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStorageAppender.java]: Yes, if there is nothing to append, it is still necessary to yield, because of

https://github.com/camunda-cloud/zeebe/blob/3da1a75d52e524b123f91a8ec9e480a0337bbf42/util/src/main/java/io/camunda/zeebe/util/sched/channel/ChannelConsumerCondition.java#L43-L48

In more detail, because of that condition `polledCount > processedTiggersCount` (BTW there is a typo in the source code 😄 ). There might be a case, where the `polledCount` is much greater than the `processedTiggersCount` but currently there is nothing to peek from the write buffer. Meaning, the condition in `#poll()` still returns `true`. If the yield would not happen, then the task would continue executing the corresponding actor job until the condition is `false` (i.e., the `processedTiggersCount` is greater or equal to `polledCount`).

**Comment by romansmirnov** [comment]
bors merge

**Comment by romansmirnov** [comment]
bors cancel

**Comment by romansmirnov** [comment]
bors retry
