### PR TITLE
chore(atomix): fix log output in state machine

### LINKED ISSUE #4414: Improve on skip compaction log message
**Description**

It seems the following log statement is somehow broken:

```
ZeebeRaftStateMachine5947999{partition=raft-partition-partition-3} - Skipping compaction of non-compactable index 5802441 (first log index: {})
```

More Context:

```
2020-04-29 13:42:22.409 CEST
Received all snapshot chunks (123/123), snapshot is valid
2020-04-29 13:42:22.419 CEST
Purging snapshots older than DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/5947999-14-1588160541853, metadata=DbSnapshotMetadata{index=5947999, term=14, timestamp=2020-04-29 11:42:21,853}}
2020-04-29 13:42:22.420 CEST
Deleting snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/5899299-14-1588160482227, metadata=DbSnapshotMetadata{index=5899299, term=14, timestamp=2020-04-29 11:41:22,227}}
2020-04-29 13:42:22.482 CEST
Snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/5899299-14-1588160482227, metadata=DbSnapshotMetadata{index=5899299, term=14, timestamp=2020-04-29 11:41:22,227}} removed from store io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore@4871f610
2020-04-29 13:42:22.482 CEST
Search for orphaned snapshots below oldest valid snapshot with index 5947999 in /usr/local/zeebe/data/raft-partition/partitions/3/pushed-pending
2020-04-29 13:42:22.482 CEST
Compacting Atomix log up to index 5947999
2020-04-29 13:42:22.482 CEST
Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/5947999-14-1588160541853, metadata=DbSnapshotMetadata{index=5947999, term=14, timestamp=2020-04-29 11:42:21,853}}
2020-04-29 13:42:22.483 CEST
ZeebeRaftStateMachine5947999{partition=raft-partition-partition-3} - Skipping compaction of non-compactable index 5802441 (first log index: {})
```

It is logged when compaction doesn't happen, but actually I'm not 100% sure what exactly it tells me.

Is there are reason why we now use these ContextualLoggers?

\cc @deepthidevaki @npepinpe

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Log looks now like this:

```
14:10:33.466 [] DEBUG io.atomix.raft.impl.zeebe.ZeebeRaftStateMachine - ZeebeRaftStateMachine{raft-partition-partition-3} - Skipping compaction of non-compactable index 300 (first log index: 301)
```

Instead of:

```
ZeebeRaftStateMachine5947999{partition=raft-partition-partition-3} - Skipping compaction of non-compactable index 5802441 (first log index: {})
```

## Related issues

closes https://github.com/zeebe-io/zeebe/issues/4414

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/impl/zeebe/ZeebeRaftStateMachine.java [hunk 1]
```diff
@@ -41,7 +41,7 @@ public ZeebeRaftStateMachine(final RaftContext raft) {
     this.lastEnqueued = reader.getFirstIndex() - 1;
     this.logger =
         ContextualLoggerFactory.getLogger(
```
Comment (npepinpe) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/zeebe/ZeebeRaftStateMachine.java:43]: Nit: as you mentioned, we could also just add the partition into the MDC and use a normal logger here. Up to you.

**Review by npepinpe — APPROVED** [review]

File: atomix/cluster/src/main/java/io/atomix/raft/impl/zeebe/ZeebeRaftStateMachine.java (hunk 1 above)
Comment (Zelldon) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/zeebe/ZeebeRaftStateMachine.java:43]: Will probably do during some of the refactorings, let see
