### PR TITLE
Process instance archiver task silently stops

### LINKED ISSUE #42838: Process instance archiver task silently stops
### 

### 

### 

### 

### Description

We observed that the process instance archiver job, can silently stop executing.

The root cause is located in [ElasticsearchArchiverRepository#archivingIsBlocked](https://github.com/camunda/camunda/blob/d071a77ecfe9e8a03db77f0287a1f68a6dc8a08d/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java#L336-L348). This method performs a blocking `.join()` call on the asynchronous Elasticsearch client. If this call fails (e.g., due to a connection timeout or network unreachable error), it throws an unchecked exception synchronously.

Because this exception occurs before the [`CompletableFuture` chain](https://github.com/camunda/camunda/blob/0873ad1038128ee1d60f61fe9d9d04ab23e21847/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ProcessInstancesArchiverJob.java#L48-L60) is returned to the ReschedulingTask, the `ScheduledThreadPoolExecutor` catches the exception and, suppresses all future executions of that task. This results in the Archiver permanently stopping until the it gets rescheduled again after a restart.

### Steps to reproduce

1. Start Camunda with archiving configured.
2. Induce a network condition where the Elasticsearch call fails immediately (e.g. stop ES).
3. Restore connectivity to Elasticsearch.
4. The issue can also be reproduced with Opensearch

### Current behavior

The PI archiver task does not resume 

### Expected behavior

The task should handle connection failures gracefully, and resume after ES connection is restored

### Workaround

Restart zeebe container that is the leader of the partition for which the archiver is not scheduled anymore

### Environment

SaaS & SM

### Version

- Component Version: 8.8.8

### Rootcause

The method [ElasticsearchArchiverRepository#archivingIsBlocked](https://github.com/camunda/camunda/blob/d071a77ecfe9e8a03db77f0287a1f68a6dc8a08d/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java#L336-L348) uses `.join()`: This forces a synchronous wait. If it fails, it breaks the async contract required by `ReschedulingTask`.

### Solution ideas

* Make `archivingIsBlocked` method asynchronous to avoid blocking the thread and to allow errors to flow through the standard exceptionally stages of the future chain.
* Harden `ReschedulingTask`: Wrap the `task.execute()` call in a try-catch block to handle synchronous exceptions and ensure `reschedule()` is always called.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

[#inc-achiver-backlog-growing-in-many-saas-clusters](https://camunda.slack.com/archives/C0A3G5HNKC3)

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

* Updated `archivingIsBlocked()` in both `ElasticsearchArchiverRepository` and `OpenSearchArchiverRepository` to return a `CompletableFuture<Boolean>` instead of a synchronous boolean, making the `getProcessInstancesNextBatch `  block fully asynchronous to avoid any synchronous exception from skipping the [CompletableFuture chain]
* In `ReschedulingTask`, exceptions thrown by the background task execute() are caught and converted into failed futures. 

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #42838

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java [hunk 1]
```diff
@@ -131,20 +131,26 @@ private static Cache<String, String> buildLifeCycleAppliedCache(
...
-      logger.debug("Archiving is currently blocked.");
-      return CompletableFuture.completedFuture(new ArchiveBatch(null, List.of()));
-    }
-    final var searchRequest = createFinishedInstancesSearchRequest();
-
-    final var timer = Timer.start();
-    return client
-        .search(searchRequest, Object.class)
-        .whenCompleteAsync((ignored, error) -> metrics.measureArchiverSearch(timer), executor)
+    return archivingIsBlocked()
```
Comment (yohanfernando) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java]: 🔧  A massive nabd, this _almost reads_ like do something if archiving is blocked.. Why not rename to `getArchiverStatus()` (or even `withArchiverStatus()`)

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java [hunk 2]
```diff
@@ -333,18 +339,17 @@ public CompletableFuture<Integer> getCountOfProcessInstancesAwaitingArchival() {
...
-        .map(m -> m.meta().get(PI_ARCHIVING_BLOCKED_META_KEY))
-        .map(jd -> jd.to(Boolean.class))
-        .orElse(false);
+  private CompletableFuture<Boolean> archivingIsBlocked() {
+    return client
+        .indices()
+        .get(r -> r.index(archiverBlockedMetaIndex))
+        .thenApply(
+            response ->
+                Optional.ofNullable(response.result().get(archiverBlockedMetaIndex))
```
Comment (yohanfernando) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:348]: ❓  On Elasticsearch exception (especially on server 500 or client timeout), would there always be a value in `response` and `response.result()` or can either of them be `null`? If yes we may need to add some guards to that

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/ReschedulingTask.java [hunk 3]
```diff
@@ -50,7 +51,13 @@ public ReschedulingTask(
...
   public void run() {
     scheduled = true;
-    var result = task.execute();
+    CompletionStage<Integer> result;
+    try {
+      result = task.execute();
+    } catch (final Exception e) {
+      // in case the task throws an exception instead of returning a failed CompletionStage
+      result = CompletableFuture.failedFuture(e);
+    }
```
Comment (yohanfernando) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/ReschedulingTask.java:60]: 🔥  Nice

**Review by yohanfernando — APPROVED** [review]
Looking great, couple of questions

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java (hunk 1 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java]: this makes sense

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java (hunk 2 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:348]: I believe this is not necessary, the client should guarantee that the response is not null in case of success.
`thenApply` is only triggered when the upstream CompletableFuture completes successfully

Also checking the SDK, `GetIndexResponse.result()` cannot be null, the constructor is ensuring that and the builder starts with an empty HashMap

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java (hunk 1 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java]: @yohanfernando Done here https://github.com/camunda/camunda/pull/42967/changes/c19891e35e33093c11ce8f70de96cc92319bb27a
