### PR TITLE
pg-26966-unbind-process-migration-from-tasklist

### LINKED ISSUE #26966: Figure out where should `process-migration` be run
The `process-migration` profile is being triggered on the `tasklist-importer-archiver` deployment as well. 

```
"ApplicationErrorListener.java","line":24},"message":"Failed to start application with message: Error creating bean with name 'migrationsRunner' defined in URL [jar:file:/usr/local/tasklist/lib/camunda-zeebe-8.7.0-alpha3.jar!/io/camunda/application/commons/migration/MigrationsRunner.class]: 
Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'process-migrator'
```

Also, another consideration is that if a SaaS cluster/SM installation does not make use of Tasklist, the migration of existing `operate-process` records might be mandatory as well for the V2 APIs. This needs some further investigation.

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

- Tasklist profile no longer runs process-migration
- Include migration modules in StandaloneCamunda
## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #26966

### CODE REVIEW

File: dist/src/main/java/io/camunda/application/StandaloneCamunda.java [hunk 1]
```diff
@@ -46,7 +47,8 @@ public static void main(final String[] args) {
                 IdentityModuleConfiguration.class,
                 WebappsModuleConfiguration.class,
                 BrokerModuleConfiguration.class,
-                GatewayModuleConfiguration.class)
```
Comment (ChrisKujawa) [inline dist/src/main/java/io/camunda/application/StandaloneCamunda.java:49]: 💭 ❓  I think we also need to enable the profile in Line 32 right?

Comment (panagiotisgts) [reply dist/src/main/java/io/camunda/application/StandaloneCamunda.java:49]: This will cause the profile to run as default. Adding just it's configuration allows it to be enabled when the profile is actually specified when running the StandaloneCamunda application.

File: dist/src/main/java/io/camunda/application/StandaloneCamunda.java [hunk 2]
```diff
@@ -46,7 +47,8 @@ public static void main(final String[] args) {
...
+                GatewayModuleConfiguration.class,
+                MigrationsRunner.class)
```
Comment (houssain-barouni) [inline dist/src/main/java/io/camunda/application/StandaloneCamunda.java:51]: 🔧 I think this is not needed to add this . `MigrationsRunner` is part of `io.camunda.application.commons` package so it should be scanned by `CommonsModuleConfiguration` and enabled when the right profiles are set

**Review by houssain-barouni — CHANGES_REQUESTED** [review]
Remove unnecessary MigrationsRunner in application sources

**Review by houssain-barouni — APPROVED** [review]

**Review by houssain-barouni — APPROVED** [review]
