### PR TITLE
Await until all index templates are present before running ES test

### LINKED ISSUE #4709: ElasticsearchExporterFaultToleranceIT.shouldExportEvenIfElasticNotInitiallyReachable flaky
**Summary**

- How often does the test fail? once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**
(Currently this information is not available)

### LINKED ISSUE #8825: `ElasticsearchExporterDmnRecordIT.shouldExportDecisionEvaluationRecord` is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? At least twice in a row so far
- Does it block your work? No
- Do we suspect that it is a real failure? Haven't checked but it's an exporter test so probably not.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.camunda.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:77)
	at zeebe.elasticsearch.exporter@1.4.0-SNAPSHOT/io.camunda.zeebe.exporter.records.ElasticsearchExporterDmnRecordIT.shouldExportDecisionEvaluationRecord(ElasticsearchExporterDmnRecordIT.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:199)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:193)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
10:54:18.901 [] [main] INFO  io.camunda.zeebe.test.util.SocketUtil - Choosing next port 7728 for test fork 7 with range PortRange{host='localhost', basePort=7725, maxOffset=100, currentOffset=4}
10:54:18.902 [] [main] INFO  io.camunda.zeebe.test.util.SocketUtil - Choosing next port 7729 for test fork 7 with range PortRange{host='localhost', basePort=7725, maxOffset=100, currentOffset=5}
10:54:18.902 [] [main] INFO  io.camunda.zeebe.test.util.SocketUtil - Choosing next port 7730 for test fork 7 with range PortRange{host='localhost', basePort=7725, maxOffset=100, currentOffset=6}
10:54:18.903 [] [main] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:7.17.0] - Creating container for image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
10:54:18.985 [] [main] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:7.17.0] - Container docker.elastic.co/elasticsearch/elasticsearch:7.17.0 is starting: 58461c7fdde10a83f4a7c9cda72befa51d6c333b093cf26014627330d7f43d8d
10:54:19.865 [] [main] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /affectionate_chaum: Waiting for 120 seconds for URL: http://localhost:49286/_cluster/health?wait_for_status=green&timeout=1s (where port 49286 maps to container port 9200)
10:54:59.349 [] [main] INFO  🐳 [docker.elastic.co/elasticsearch/elasticsearch:7.17.0] - Container docker.elastic.co/elasticsearch/elasticsearch:7.17.0 started in PT40.446651031S
10:54:59.352 [] [main] DEBUG io.camunda.zeebe.broker.system - Initializing system with base path /tmp/79fb0878-a394-498e-9a6f-fa1f030f7ed0
10:54:59.358 [] [main] DEBUG io.camunda.zeebe.broker.exporter - Exporter configured with ElasticsearchExporterConfiguration{url='http://localhost:49286', index=IndexConfiguration{indexPrefix='test-record', createTemplate=true, command=true, event=true, rejection=true, error=true, deployment=true, process=true, incident=true, job=true, message=true, messageSubscription=true, variable=true, variableDocument=true, processInstance=true, processInstanceCreation=true, processMessageSubscription=true, decisionRequirements=true, decision=true, decisionEvaluation=true}, bulk=BulkConfiguration{delay=1, size=1, memoryLimit=10485760}}
10:54:59.359 [] [main] INFO  io.camunda.zeebe.broker.system - Version: 1.4.0-SNAPSHOT
10:54:59.362 [] [main] INFO  io.camunda.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 7729,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7729,
      "address" : "0.0.0.0:7729",
      "advertisedAddress" : "0.0.0.0:7729"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 7730,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7730,
      "address" : "0.0.0.0:7730",
      "advertisedAddress" : "0.0.0.0:7730"
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 1,
    "clusterSize" : 1,
    "clusterName" : "zeebe-cluster",
    "heartbeatInterval" : "PT0.25S",
    "electionTimeout" : "PT2.5S",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    },
    "raft" : {
      "enablePriorityElection" : true
    },
    "messageCompression" : "NONE"
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directory" : "/tmp/79fb0878-a394-498e-9a6f-fa1f030f7ed0/data",
    "logSegmentSize" : "128MB",
    "snapshotPeriod" : "PT5M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.99,
    "diskUsageCommandWatermark" : 0.97,
    "diskUsageMonitoringInterval" : "PT1S",
    "logSegmentSizeInBytes" : 134217728,
    "freeDiskSpaceCommandWatermark" : 0,
    "freeDiskSpaceReplicationWatermark" : 0
  },
  "exporters" : {
    "test-recorder" : {
      "jarPath" : null,
      "className" : "io.camunda.zeebe.test.util.record.RecordingExporter",
      "args" : null,
      "external" : false
    },
    "es" : {
      "jarPath" : null,
      "className" : "io.camunda.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "url" : "http://localhost:49286",
        "requestTimeoutMs" : 30000,
        "index" : {
          "prefix" : "test-record",
          "createTemplate" : true,
          "command" : true,
          "event" : true,
          "rejection" : true,
          "deployment" : true,
          "process" : true,
          "error" : true,
          "incident" : true,
          "job" : true,
          "jobBatch" : true,
          "message" : true,
          "messageSubscription" : true,
          "variable" : true,
          "variableDocument" : true,
          "processInstance" : true,
          "processInstanceCreation" : true,
          "processMessageSubscription" : true,
          "decisionRequirements" : true,
          "decision" : true,
          "decisionEvaluation" : true,
          "numberOfShards" : null,
          "numberOfReplicas" : null
        },
        "bulk" : {
          "delay" : 1,
          "size" : 1,
          "memoryLimit" : 10485760
        },
        "authentication" : {
          "username" : "***",
          "password" : "***",
          "present" : false
        }
      },
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 7728,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:7730",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT0.1S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      },
      "security" : {
        "enabled" : false,
        "certificateChainPath" : null,
        "privateKeyPath" : null
      },
      "messageCompression" : "NONE"
    },
    "threads" : {
      "managementThreads" : 1
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "interceptors" : [ ],
    "initialized" : true,
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "32KB",
    "disableExplicitRaftFlush" : false,
    "rocksdb" : {
      "columnFamilyOptions" : { },
      "enableStatistics" : false,
      "memoryLimit" : "512MB",
      "maxOpenFiles" : -1,
      "maxWriteBufferNumber" : 6,
      "minWriteBufferNumberToMerge" : 3,
      "ioRateBytesPerSecond" : 0,
      "disableWal" : false
    },
    "raft" : {
      "requestTimeout" : "PT5S",
      "maxQuorumResponseTimeout" : "PT0S",
      "minStepDownFailureCount" : 3,
      "preferSnapshotReplicationThreshold" : 100
    },
    "partitioning" : {
      "scheme" : "ROUND_ROBIN",
      "fixed" : [ ]
    },
    "queryApi" : {
      "enabled" : false
    },
    "maxAppendBatchSizeInBytes" : 32768
  },
  "executionMetricsExporterEnabled" : false
}
10:54:59.365 [Broker-0-Startup] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Startup was called with context: io.camunda.zeebe.broker.bootstrap.BrokerStartupContextImpl@3785848d
10:54:59.365 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Disk Space Usage Monitor
10:54:59.366 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Health Monitor
10:54:59.366 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Broker Admin Interface
10:54:59.367 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Cluster Services (Start)
10:54:59.383 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup API Messaging Service
10:54:59.389 [Broker-0-Startup] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Bound API to [0.0.0.0:7729], using advertised address 0.0.0.0:7729 
10:54:59.389 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Command API
10:54:59.390 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Admin API
10:54:59.390 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Subscription API
10:54:59.391 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Leader Management Request Handler
10:54:59.391 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Embedded Gateway
10:54:59.394 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup Partition Manager
10:54:59.414 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.raft.roles.FollowerRole$$Lambda$791/0x00000001006b46c8@3e2e3047 not registered
10:54:59.423 [] [raft-server-0-raft-partition-partition-1] INFO  io.camunda.zeebe.broker.partitioning.PartitionManagerImpl - Registering Partition Manager
10:54:59.423 [] [raft-server-0-raft-partition-partition-1] INFO  io.camunda.zeebe.broker.partitioning.PartitionManagerImpl - Starting partitions
10:54:59.424 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [Partition-1{status=UNHEALTHY, issue='Components are not yet initialized'}]
10:54:59.424 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Startup was called with context: io.camunda.zeebe.broker.system.partitions.PartitionStartupAndTransitionContextImpl@464b6f82
10:54:59.425 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup LogDeletionService
10:54:59.425 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Startup RocksDB metric timer
10:54:59.425 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Finished startup process
10:54:59.426 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=UNHEALTHY, issue='Initial state'}]
10:54:59.426 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=UNHEALTHY, issue='Initial state'}, raft-partition-partition-1{status=HEALTHY}]
10:54:59.426 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 requested.
10:54:59.426 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Partition role transitioning from null to LEADER in term 1
10:54:59.427 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 starting
10:54:59.426 [Broker-0-Startup] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Finished startup process
10:54:59.427 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 - transitioning LogStorage
10:54:59.427 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 - transitioning LogStream
10:54:59.427 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=UNHEALTHY, issue='Initial state'}, raft-partition-partition-1{status=HEALTHY}, Broker-0-LogStream-1{status=HEALTHY}]
10:54:59.428 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 - transitioning ZeebeDb
10:54:59.575 [Broker-0-SnapshotStore-1] [Broker-0-zb-fs-workers-1] DEBUG io.camunda.zeebe.logstreams.snapshot - Opened database from '/tmp/79fb0878-a394-498e-9a6f-fa1f030f7ed0/data/raft-partition/partitions/1/runtime'.
10:54:59.577 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 - transitioning QueryService
10:54:59.577 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@21db2748)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@416c8242, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@10b0a2a9, configuration: Configuration(false)]
10:54:59.581 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 - transitioning StreamProcessor
10:54:59.634 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.gateway - Received metadata change from Broker 0, partitions {}, terms {} and health {1=UNHEALTHY}.
10:54:59.636 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
10:54:59.637 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.logstreams - Recovering state of partition 1 from snapshot
10:54:59.638 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@4855e5d0)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@4a8ba4a7, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@6e88c203, configuration: Configuration(false)]
10:54:59.641 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
10:54:59.642 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@739caba9)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@1400bb6f, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@3b99bd4, configuration: Configuration(false)]
10:54:59.645 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@2b09c97a)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@3d5efe51, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@2c14e156, configuration: Configuration(false)]
10:54:59.647 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@633ca83b)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@69bef3f, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@4cfd35cb, configuration: Configuration(false)]
10:54:59.653 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.dmn.DmnEngine - DMN-Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@63d6c5d1)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@76fd6e33, audit-loggers: List(), configuration: Configuration(false,false,false)]
10:54:59.654 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.dmn.NoUnpackValueMapper@3ffdcd37)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@76fd6e33, clock: SystemClock, configuration: Configuration(false)]
10:54:59.657 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.dmn.DmnEngine - DMN-Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@465fa821)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@76fd6e33, audit-loggers: List(), configuration: Configuration(false,false,false)]
10:54:59.658 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.dmn.NoUnpackValueMapper@ff6a8c1)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@76fd6e33, clock: SystemClock, configuration: Configuration(false)]
10:54:59.661 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.processor - Processor starts replay of events. [snapshot-position: -1, replay-mode: PROCESSING]
10:54:59.662 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.processor - Processor finished replay, with [lastProcessedPosition: -1, lastWrittenPosition: -1]
10:54:59.662 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.engine.state.migration - Starting processing of migration tasks (use LogLevel.DEBUG for more details) ... 
10:54:59.662 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.engine.state.migration - Found 3 migration tasks: ProcessMessageSubscriptionSentTimeMigration, MessageSubscriptionSentTimeMigration, TemporaryVariableMigration
10:54:59.662 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.engine.state.migration - Skipping ProcessMessageSubscriptionSentTimeMigration migration (1/3).  It was determined it does not need to run right now.
10:54:59.663 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=UNHEALTHY, issue='Initial state'}, raft-partition-partition-1{status=HEALTHY}, Broker-0-StreamProcessor-1{status=HEALTHY}, Broker-0-LogStream-1{status=HEALTHY}]
10:54:59.663 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.engine.state.migration - Skipping MessageSubscriptionSentTimeMigration migration (2/3).  It was determined it does not need to run right now.
10:54:59.663 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 - transitioning SnapshotDirector
10:54:59.663 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.engine.state.migration - Skipping TemporaryVariableMigration migration (3/3).  It was determined it does not need to run right now.
10:54:59.663 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.engine.state.migration - Completed processing of migration tasks (use LogLevel.DEBUG for more details) ... 
10:54:59.663 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.engine.state.migration - Executed 0 migration tasks: 
10:54:59.664 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=UNHEALTHY, issue='Initial state'}, raft-partition-partition-1{status=HEALTHY}, Broker-0-StreamProcessor-1{status=HEALTHY}, Broker-0-LogStream-1{status=HEALTHY}, Broker-0-SnapshotDirector-1{status=HEALTHY}]
10:54:59.664 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 - transitioning ExporterDirector
10:54:59.666 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=UNHEALTHY, issue='Initial state'}, raft-partition-partition-1{status=HEALTHY}, Broker-0-Exporter-1{status=HEALTHY}, Broker-0-StreamProcessor-1{status=HEALTHY}, Broker-0-LogStream-1{status=HEALTHY}, Broker-0-SnapshotDirector-1{status=HEALTHY}]
10:54:59.666 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 1 completed
10:54:59.666 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.broker.exporter - Recovering exporter from snapshot
10:54:59.666 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - All partitions are installed. Broker is ready!
10:54:59.667 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - ZeebePartition-1 recovered, marking it as healthy
10:54:59.667 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.broker.exporter - Recovered exporter 'Broker-0-Exporter-1' from snapshot at lastExportedPosition -1
10:54:59.667 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Detected 'HEALTHY' components. The current health status of components: [ZeebePartition-1{status=HEALTHY}, raft-partition-partition-1{status=HEALTHY}, Broker-0-Exporter-1{status=HEALTHY}, Broker-0-StreamProcessor-1{status=HEALTHY}, Broker-0-LogStream-1{status=HEALTHY}, Broker-0-SnapshotDirector-1{status=HEALTHY}]
10:54:59.667 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.broker.exporter - Configure exporter with id 'test-recorder'
10:54:59.667 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.broker.exporter - Configure exporter with id 'es'
10:54:59.668 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.broker.exporter.es - Exporter configured with ElasticsearchExporterConfiguration{url='http://localhost:49286', index=IndexConfiguration{indexPrefix='test-record', createTemplate=true, command=true, event=true, rejection=true, error=true, deployment=true, process=true, incident=true, job=true, message=true, messageSubscription=true, variable=true, variableDocument=true, processInstance=true, processInstanceCreation=true, processMessageSubscription=true, decisionRequirements=true, decision=true, decisionEvaluation=true}, bulk=BulkConfiguration{delay=1, size=1, memoryLimit=10485760}}
10:54:59.668 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={COMMAND_REJECTION=true, EVENT=true, SBE_UNKNOWN=true, NULL_VAL=true, COMMAND=true}, acceptValueTypes={DECISION=true, PROCESS_EVENT=true, DEPLOYMENT_DISTRIBUTION=true, PROCESS=true, PROCESS_INSTANCE=true, MESSAGE=true, TIMER=true, VARIABLE_DOCUMENT=true, MESSAGE_SUBSCRIPTION=true, INCIDENT=true, VARIABLE=true, DECISION_EVALUATION=true, NULL_VAL=true, PROCESS_INSTANCE_RESULT=true, SBE_UNKNOWN=true, ERROR=true, DEPLOYMENT=true, PROCESS_MESSAGE_SUBSCRIPTION=true, PROCESS_INSTANCE_CREATION=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, JOB=true, JOB_BATCH=true, DECISION_REQUIREMENTS=true}}
10:54:59.669 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.broker.exporter - Open exporter with id 'test-recorder'
10:54:59.669 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.broker.exporter - Open exporter with id 'es'
10:54:59.671 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] INFO  io.camunda.zeebe.broker.exporter.es - Exporter opened
10:54:59.884 [GatewayTopologyManager] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER}, terms {1=1} and health {1=HEALTHY}.
10:55:03.564 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_component_template/test-record] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:04.337 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_deployment_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:04.634 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_process_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:04.879 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_error_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:05.172 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_incident_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:05.436 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_job_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:05.664 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_job-batch_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:06.031 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_message_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:06.260 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_message-subscription_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:06.570 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_variable_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:06.840 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_variable-document_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:07.051 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_process-instance_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:07.255 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_process-instance-creation_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:07.455 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_process-message-subscription_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:07.831 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_decision-requirements_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:08.271 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_decision_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:08.559 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [PUT http://localhost:49286/_index_template/test-record_decision-evaluation_1.4.0-snapshot] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:10.511 [Broker-0-Startup] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Shutdown was called with context: io.camunda.zeebe.broker.bootstrap.BrokerStartupContextImpl@3785848d
10:55:10.511 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Shutdown Partition Manager
10:55:10.512 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Closing ZeebePartition 1
10:55:10.512 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 requested.
10:55:10.512 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] WARN  io.camunda.zeebe.broker.system - ZeebePartition-1 failed, marking it as unhealthy: Partition-1{status=HEALTHY}
10:55:10.512 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=UNHEALTHY, issue='Services not installed'}, raft-partition-partition-1{status=HEALTHY}, Broker-0-Exporter-1{status=HEALTHY}, Broker-0-StreamProcessor-1{status=HEALTHY}, Broker-0-LogStream-1{status=HEALTHY}, Broker-0-SnapshotDirector-1{status=HEALTHY}]
10:55:10.512 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 1 to INACTIVE
10:55:10.512 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 1 to INACTIVE - preparing ExporterDirector
10:55:10.513 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.logstreams - Paused processing for partition 1
10:55:10.540 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  org.elasticsearch.client.RestClient - request [POST http://localhost:49286/_bulk] returned 1 warnings: [299 Elasticsearch-7.17.0-bee86328705acaa9a6daede7140defd4d9ec56bd "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
10:55:10.542 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.camunda.zeebe.util.sched.ActorTask - Discard job io.camunda.zeebe.broker.exporter.stream.ExporterDirector$$Lambda$1466/0x0000000100a2e978 QUEUED from fastLane of Actor Broker-0-Exporter-1.
10:55:10.543 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.camunda.zeebe.util.sched.ActorTask - Discard job io.camunda.zeebe.exporter.ElasticsearchExporter$$Lambda$1128/0x000000010082b5d0 QUEUED from fastLane of Actor Broker-0-Exporter-1.
10:55:10.543 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.camunda.zeebe.util.sched.ActorTask - Discard job io.camunda.zeebe.util.sched.future.FutureContinuationRunnable QUEUED from fastLane of Actor Broker-0-Exporter-1.
10:55:10.544 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  io.camunda.zeebe.broker.exporter.es - Exporter closed
10:55:10.544 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.camunda.zeebe.broker.exporter - Closed exporter director 'Broker-0-Exporter-1'.
10:55:10.544 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 1 to INACTIVE - preparing SnapshotDirector
10:55:10.545 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 1 to INACTIVE - preparing StreamProcessor
10:55:10.545 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.util.sched.ActorTask - Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$1474/0x0000000100a2fd08 QUEUED from fastLane of Actor Broker-0-StreamProcessor-1.
10:55:10.546 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
10:55:10.546 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 1 to INACTIVE - preparing QueryService
10:55:10.546 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 1 to INACTIVE - preparing ZeebeDb
10:55:10.546 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 1 to INACTIVE - preparing LogStream
10:55:10.547 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.logstreams - Close appender for log stream logstream-raft-partition-partition-1
10:55:10.547 [logstream-raft-partition-partition-1-write-buffer] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.dispatcher - Dispatcher closed
10:55:10.547 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-1 close 2 readers
10:55:10.547 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 1 to INACTIVE - preparing LogStorage
10:55:10.548 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Preparing transition from LEADER on term 1 completed
10:55:10.548 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 starting
10:55:10.548 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 - transitioning LogStorage
10:55:10.548 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 - transitioning LogStream
10:55:10.548 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 - transitioning ZeebeDb
10:55:10.548 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 - transitioning QueryService
10:55:10.549 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 - transitioning StreamProcessor
10:55:10.549 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 - transitioning SnapshotDirector
10:55:10.549 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 - transitioning ExporterDirector
10:55:10.549 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to INACTIVE on term 1 completed
10:55:10.549 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Shutdown was called with context: io.camunda.zeebe.broker.system.partitions.PartitionStartupAndTransitionContextImpl@464b6f82
10:55:10.549 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Shutdown RocksDB metric timer
10:55:10.550 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Shutdown LogDeletionService
10:55:10.550 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Finished shutdown process
10:55:10.592 [Broker-0-SnapshotStore-1] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.logstreams.snapshot - Closed database from '/tmp/79fb0878-a394-498e-9a6f-fa1f030f7ed0/data/raft-partition/partitions/1/runtime'.
10:55:10.594 [] [raft-server-0-raft-partition-partition-1] DEBUG io.camunda.zeebe.journal.file.SegmentedJournal - Closing segment: JournalSegment{id=1, index=1}
10:55:10.595 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Shutdown Embedded Gateway
10:55:10.597 [] [ForkJoinPool.commonPool-worker-4] DEBUG io.camunda.zeebe.gateway - Closing gateway broker client ...
10:55:10.597 [] [ForkJoinPool.commonPool-worker-4] DEBUG io.camunda.zeebe.gateway - topology manager closed
10:55:10.598 [] [ForkJoinPool.commonPool-worker-4] DEBUG io.camunda.zeebe.gateway - Gateway broker client closed.
10:55:10.598 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Shutdown Leader Management Request Handler
10:55:10.598 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Shutdown Subscription API
10:55:10.598 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Shutdown Admin API
10:55:10.599 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Shutdown Command API
10:55:10.599 [Broker-0-Startup] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Shutdown API Messaging Service
10:55:10.714 [Broker-0-Startup] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Shutdown Cluster Services (Start)
10:55:12.864 [Broker-0-Startup] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Shutdown Broker Admin Interface
10:55:12.864 [Broker-0-Startup] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Shutdown Health Monitor
10:55:12.865 [Broker-0-Startup] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Shutdown Disk Space Usage Monitor
10:55:12.865 [Broker-0-Startup] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Finished shutdown process
10:55:12.865 [] [main] INFO  io.camunda.zeebe.broker.system - Broker shut down.
10:55:12.866 [] [main] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers'
10:55:12.866 [] [main] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors'
10:55:12.866 [] [Broker-0-zb-actors-0] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors': closed successfully
10:55:12.867 [] [Broker-0-zb-fs-workers-0] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers': closed successfully
10:55:13.961 [] [main] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
10:55:13.987 [] [main] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DEPLOYMENT CREATE - #1->-1 -1 - 
-------------- Deployed Processes ----------------------
--------------- Decomposed keys (for debugging) -----------------
-1 <-> -1
</pre>
</details>

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR is a tentative fix for the flaky ES exporter tests. It does so by extracting a very hacky, nonsensical interface from the `ExporterIntegrationRule` called `NonStartableBrokerRule`. This terrible interface just prevents starting the broker from tests. As such, the broker can only be started via the abstract test case's `startBroker` method. In there we publish a dummy message and await the index templates to be added Elastic. That way all tests benefit from the hack.

Note that this is super hacky, and should never be considered an example of what to do. I think it's worth it in this case because one of my KRs this quarter is refactoring these tests, and the result will be that there will be no brokers involved, so we'll simply sidestep this issue. It also means all these classes will be removed, and there also won't be an abstract test case, so generally all this hacky stuff will disappear.

The PR also ensures we always reset the wait time (which is sometimes reduced in other tests). This guarantees that things like the `RecordingExporterTestWatcher`, which does call reset after each test, will also reset the timeout. This may fix some flaky tests where we sometimes change or reduce the timeout, which is then global for that forked process, and since ordering is random it's very hard to pinpoint/reproduce.

## Related issues

closes #8825 
closes #4709 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Comment by npepinpe** [comment]
Running it 7 times to see if it changes anything. :crossed_fingers:

**Comment by npepinpe** [comment]
Oh well, it occurred again with one of the tests, so I guess it wasn't that. This might hint at a real issue :thinking:

**Comment by npepinpe** [comment]
You can see from the logs that actually no records are exported to the `RecordingExporter` :exploding_head: - https://ci.zeebe.camunda.cloud/job/camunda/job/zeebe/job/8825-es-flaky-tentative-fix/12/testReport/junit/io.camunda.zeebe.exporter.records/ElasticsearchExporterDmnRecordIT(it-testrun)/Verify___IT___Test___shouldExportDeploymentRecord/

**Comment by npepinpe** [comment]
My guess is the ES exporter is blocking the `RecordingExporter` from seeing records. We can see only one record is exported, and ES was still trying to create the index templates. The broker was started at :26, and shutdown started at :36, and ES is still trying to create index templates. It won't export ANY record until the index templates exist, so it will block ALL exporters from exporting further records.

**Comment by Zelldon** [comment]
@npepinpe reminds me on https://github.com/camunda/zeebe/issues/7831#issue-998049414 which we should tackle at some point

**Comment by npepinpe** [comment]
Alright, I started 10 builds, let's see :crossed_fingers:

**Comment by npepinpe** [comment]
I think this is my hackiest PR so far :smile:

**Comment by npepinpe** [comment]
So apparently if you're too fast and no index templates were created yet, the look up returns a 404 instead of just an empty array. Super cool :ok_man:

**Comment by npepinpe** [comment]
@Zelldon Let me know if you don't have time. Keep in mind also this is super hacky, but as we are refactoring the tests to be much simpler - i.e. use the exporter instance directly without a broker and just test the integration with Elastic - all the utilities and the abstract test case/test harness will go away.

I ran this for 10 builds, and there were no ES test failures (whereas before I could trigger it in ~5 builds every time).

File: exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/util/it/NonStartableBrokerRule.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+import java.util.function.Consumer;
+
+/**
+ * This interface is a temporary workaround to prevent actual tests from starting a broker manually.
+ * Instead, you should use {@link AbstractElasticsearchExporterIntegrationTestCase#startBroker()}.
+ *
+ * <p>As all of these utility classes will be removed by the end of Q2-2022, it's an OK trade-off to
+ * avoid rewriting most of the tests (which will be rewritten differently anyway).
+ */
+public interface NonStartableBrokerRule {
```
Comment (Zelldon) [inline exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/util/it/NonStartableBrokerRule.java:29]: :wrench: not sure why this was necessary since we any want to remove or rewrite this but ok :)

**Review by ChrisKujawa — APPROVED** [review]
Thanks @npepinpe :medal_military: :rocket:  I know you had a lot of fun with it but I hope we have less flaky tests now :D Looking forward to replace the tests. What is the status of rewriting the elasticexporter to be async?

File: exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/util/it/ExporterIntegrationRule.java [hunk 2]
```diff
@@ -317,16 +300,29 @@ public void publishMessage(final String messageName, final String correlationKey
...
 
   /**
-   * Blocks and wait until the process identified by the key has been completed.
+   * Starts the broker and the client. This is blocking and will return once the broker is ready to
+   * accept commands.
    *
-   * @param processInstanceKey ID of the process
+   * @throws IllegalStateException if no exporter has previously been configured
    */
-  public void awaitProcessCompletion(final long processInstanceKey) {
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/util/it/ExporterIntegrationRule.java:324]: It was dead code/unused

File: exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/util/it/NonStartableBrokerRule.java (hunk 1 above)
Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/util/it/NonStartableBrokerRule.java:29]: Because while I dont think anyone will add a test, I can't guarantee it, so I just wanted to make sure you have to call the other method :smile:

**Comment by npepinpe** [comment]
bors merge
