### PR TITLE
fix: allow HTTP to be disabled in Optimize

### LINKED ISSUE #44222: Optimize 8.8.x cannot disable HTTP via CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTP / container.ports.http (regression from 8.7)
### 

### 

### 

### 

### Description

In Optimize 8.8.x (Tomcat-based), disabling HTTP via the documented configuration (CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTP / container.ports.http set to empty or null) causes Optimize to fail on startup with:

`io.camunda.optimize.service.exceptions.OptimizeConfigurationException: HTTP port not configured`

This behavior differs from Optimize 8.7.5, where the same configuration is accepted and results in HTTPS-only operation (no HTTP listener), which is still what the documentation describes.

The error is thrown in OptimizeTomcatConfig.getPort, which now treats an empty HTTP port as fatal:

```
final Optional<Integer> httpPort = configurationService.getContainerHttpPort();
if (httpPort.isEmpty()) {
  throw new OptimizeConfigurationException("HTTP port not configured");
}
```

### Steps to reproduce

1. Deploy Camunda 8.8.3 Self-Managed with Helm (e.g. Helm chart 10.x) and Optimize 8.8.3.
2. Configure Optimize environment variables to disable HTTP according to the docs:
`optimize:
  env:
    - name: CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTP
      value: ""          # disable HTTP per docs
    - name: CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTPS
      value: "8091"`
3. Apply the Helm release and watch the Optimize pod
4. Observe that the Optimize pod enters a CrashLoopBackOff, with logs showing:
`io.camunda.optimize.service.exceptions.OptimizeConfigurationException: HTTP port not configured
  at io.camunda.optimize.OptimizeTomcatConfig.getPort(OptimizeTomcatConfig.java:174)
  at io.camunda.optimize.OptimizeTomcatConfig.configureHttpConnector(OptimizeTomcatConfig.java:223)`
5. Change only the HTTP env var to a non-empty port:
`- name: CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTP
  value: "8090"`
6. Re-deploy. Optimize now starts successfully and is reachable via both HTTP (8090) and HTTPS (8091).

### Current behavior

On Optimize 8.8.2 / 8.8.3:
- Setting CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTP (or container.ports.http) to an empty value ("") or null — as documented for disabling HTTP — causes Optimize to fail startup with:
`OptimizeConfigurationException: HTTP port not configured`
- The pod crashloops until the HTTP port is configured with a non-empty integer value.
- When the HTTP port is set (e.g. 8090), Optimize starts successfully but is reachable over both HTTP and HTTPS, i.e. no HTTPS-only mode.

On Optimize 8.7.5 (Jetty):
- The same configuration with CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTP="" is accepted.
- Optimize starts successfully, logs show Jetty initialization and Started Main in ... with no HTTP-port error.
- The service is reachable only via HTTPS (HTTP effectively disabled).

### Expected behavior

Optimize should support the documented HTTPS-only mode:

- Setting CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTP (or container.ports.http) to null or "" should:
- Not cause an OptimizeConfigurationException.
- Result in no HTTP connector being created / no HTTP port bound.
- Keep the service reachable only via HTTPS on the configured HTTPS port.

Behavior should match Optimize 8.7.5 and the current docs

### Workaround

_No response_

### Environment

SM

### Version

Observed working: Optimize 8.7.5
Observed failing: Optimize 8.8.2, 8.8.3

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

https://jira.camunda.com/browse/SUPPORT-30803

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tanjinyi**
## Description

Fixes the regression from 8.7 after migrating from Jetty to Tomcat where the HTTP port could not be disabled.

The behaviour prior to this PR was to check whether both HTTP and HTTPS ports were defined, and if not throw an exception if one is not defined. This breaks the contractual behaviour defined at the point of Optimize 8.7.5 where HTTP ports, if not defined, should result in configuring the application to HTTPS-only operation mode. This PR reverts the behaviour to the expected one from 8.7.5.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #44222

### CODE REVIEW

File: optimize/backend/src/main/java/io/camunda/optimize/OptimizeTomcatConfig.java [hunk 1]
```diff
@@ -170,10 +173,7 @@ public int getPort(final String portType) {
     }
 
     final Optional<Integer> httpPort = configurationService.getContainerHttpPort();
-    if (httpPort.isEmpty()) {
-      throw new OptimizeConfigurationException("HTTP port not configured");
-    }
-    return httpPort.get();
+    return httpPort.filter(port -> port > 0).orElse(-1);
```
Comment (tanjinyi) [inline optimize/backend/src/main/java/io/camunda/optimize/OptimizeTomcatConfig.java:179]: this is an internal behaviour but i'm not sure whether we want to return null here by performing variable boxing

**Comment by tanjinyi** [comment]
Running Optimize `Main` with env variables
`CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTP=;CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTPS=8091` results in the following startup:
```
2026-02-24 15:49:45.426  INFO 56333 --- [           main] o.s.b.t.TomcatWebServer                  : Tomcat started on port 8091 (https) with context path '/'
2026-02-24 15:49:45.462  INFO 56333 --- [           main] o.s.b.t.TomcatWebServer                  : Tomcat initialized with port 8092 (http)
2026-02-24 15:49:45.475  INFO 56333 --- [           main] b.w.c.s.WebApplicationContextInitializer : Root WebApplicationContext: initialization completed in 47 ms
```

With env variables `CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTP=8090;CAMUNDA_OPTIMIZE_CONTAINER_PORTS_HTTPS=8091`, this is the result: 

```
2026-02-24 15:51:28.651  INFO 56408 --- [           main] o.s.b.t.TomcatWebServer                  : Tomcat started on ports 8091 (https), 8090 (http) with context path '/'
2026-02-24 15:51:28.678  INFO 56408 --- [           main] o.s.b.t.TomcatWebServer                  : Tomcat initialized with port 8092 (http)
2026-02-24 15:51:28.688  INFO 56408 --- [           main] b.w.c.s.WebApplicationContextInitializer : Root WebApplicationContext: initialization completed in 35 ms
```

**Review by konstantinos-mylosis — APPROVED** [review]
LGTM

`-1` seems ok
Consider adding a `LOG` if `Optional.empty`
