### PR TITLE
fix: tenant custom filters on Tasklist

### LINKED ISSUE #37296: Filter userTasks by tenant is not working using V2 API
### 

### 

### 

### 

### Description

When using the Tasklist V2 API, applying a **custom filter** with the **"Tenant"** option does not correctly apply the Tenant filter.

* **Sent request via UI:**

```json
{"sort":[{"field":"creationDate","order":"desc"}],"page":{"limit":50,"from":0},"filter":{}}
```

https://github.com/user-attachments/assets/e53a3ea8-6931-470c-959d-b0b8f427ed56

### Steps to reproduce

1. Start Camunda with V2 API - make sure to have multiTenancy enabled `CAMUNDA_SECURITY_MULTITENANCY_CHECKSENABLED=true`
2. Create a new tenant in identity and assign it to demo user
3. Deploy and start a process with userTask on default tenant
4.  Deploy and start a process with userTask on the created tenant
5. Apply a custom filter with choosing "default" tenant

### Current behavior

userTasks from both tenant are retrieved

### Expected behavior

Only userTasks relevant to default tenant are retrieved

### Environment

SM

### Version

- Component Version: SNAPSHOT

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by vsgoulart**
## Description

On this PR:
- Fix custom filter cleanup when switching filters
- Fixes default tenant selection
- Add extra check for empty strings on tenant field

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #37296

### CODE REVIEW

File: tasklist/client/src/common/tasks/available-tasks/CollapsiblePanel/index.tsx [hunk 1]
```diff
@@ -63,6 +63,7 @@ function getNavLinkSearchParam(options: {
     'processDefinitionKey',
     'processInstanceKey',
     'tenantIds',
+    'tenantId',
```
Comment (christoph-fricke) [inline tasklist/client/src/common/tasks/available-tasks/CollapsiblePanel/index.tsx:66]: ❓ What the difference between `tenantIds` and `tenantId`? Is "Ids" a separate field that is just not visible in the bug report video?

**Review by christoph-fricke — APPROVED** [review]
Didn't test it locally, but code wise it looks fine.

**Review by christoph-fricke — APPROVED** [review]
Didn't test it locally but code-wise it looks fine.

File: tasklist/client/src/common/tasks/available-tasks/CollapsiblePanel/index.tsx (hunk 1 above)
Comment (vsgoulart) [reply tasklist/client/src/common/tasks/available-tasks/CollapsiblePanel/index.tsx:66]: @christoph-fricke This was from the v1 API. This will all be removed on the coming weeks with this issue https://github.com/camunda/camunda/issues/46919
