### PR TITLE
Do not take a backup if it already exists

### LINKED ISSUE #10430: After restore, a completed backup is marked as failed
**Describe the bug**

Observed this behavior when testing restore: 
After restore, the backup service attempt to take the backup  with the same id (from which it restored from). Since the backup already exists, backup store throws an exception and marks it as failed(?). 

**To Reproduce**

`BackupTest` added in #10412 can reproduce this. The test does not fail, but it logs a bunch of exception.

**Expected behavior**

1. After a restore, BackupService should not attempt to take the same backup again.
2. BackupStore should not mark a completed backup as failed.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

After restore, the log is truncated to the checkpoint position. So the checkpoint record is processed again and will trigger a new backup with the same Id of the backup it restored from. With this PR, `BackupService` handles this case gracefully. In addition, we also do not take a new backup if existing backup is failed or in progress. Alternatively, we can delete this backup and take a new one. But chances of it happening (i.e triggering a new backup when one already is in progress/failed) is very low. So we can keep this simple.

## Related issues

closes #10430 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: backup/src/test/java/io/camunda/zeebe/backup/management/BackupServiceImplTest.java [hunk 1]
```diff
@@ -40,12 +43,21 @@ class BackupServiceImplTest {
   @Mock InProgressBackup inProgressBackup;
   @Mock BackupStore backupStore;
 
+  @Mock BackupStatus notExistingBackupStatus;
```
Comment (oleschoenburg) [inline backup/src/test/java/io/camunda/zeebe/backup/management/BackupServiceImplTest.java:46]: :wrench: this looks like it is unused.

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/S3BackupStoreTests.java [hunk 2]
```diff
@@ -235,4 +238,22 @@ default void deletingInProgressBackupFails(final Backup backup) {
         .withThrowableOfType(Throwable.class)
         .withRootCauseInstanceOf(BackupInInvalidStateException.class);
   }
+
+  @ParameterizedTest
+  @ArgumentsSource(TestBackupProvider.class)
+  default void shouldNotOverwriteCompletedBackup(final Backup backup) {
```
Comment (oleschoenburg) [inline backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/S3BackupStoreTests.java:244]: :wrench: This should be part of the testkit, IMO. All store implementations should satisfy this.

**Review by lenaschoenburg — APPROVED** [review]
Looks good, and thanks for adding a test for the s3 store :+1: 

:upside_down_face: the last commit message has a typo

File: backup/src/test/java/io/camunda/zeebe/backup/management/BackupServiceImplTest.java (hunk 1 above)
Comment (deepthidevaki) [reply backup/src/test/java/io/camunda/zeebe/backup/management/BackupServiceImplTest.java:46]: This is required because all takeBackup operation first check the status of existing backup.

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/S3BackupStoreTests.java (hunk 2 above)
Comment (deepthidevaki) [reply backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/S3BackupStoreTests.java]: Moved to testkit.

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors merge

**Comment by megglos** [comment]
bors retry

**Comment by deepthidevaki** [comment]
bors cancel

**Comment by deepthidevaki** [comment]
Merge this PR after https://github.com/camunda/zeebe/pull/10495

**Comment by oleschoenburg** [comment]
Hopefully in the same batch as #10495 now:

bors r+
