### PR TITLE
fix: ensure shutdown is completed when raft bootstrap is waiting

### LINKED ISSUE #48136: Raft bootstrap can block broker shutdown
With dynamic node id provider, we want to shutdown the broker as soon as possible if a lease cannot be renewed. However, it was observed that in some cases the shutdown takes a long time after the lease renewal failed and the raft is still running during this time. This could be dangerous as it could write to the raft log while the lease is not acquired. If a new task acquires the lease, then SWIM detects it and kicks the old task out of the cluster, so the impact is very minimal. However, for better safety we should ensure that the broker is shutdown immediately after lease renewal is failed. 

related to https://github.com/camunda/camunda/issues/40166

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Raft bootstrap only completes when the replica has caught up with the leader. This can take a while if it is lagging behind. If a shutdown is triggered during that time it can take a while before it is shutdown. This can cause issues in some cases, especially when dynamica node id provider is configured we want to ensure the broker is shutdown as soon as possible when the lease renewal is failed.

To ensure fast shutdown, we allow interrupting the startup step if a shutdown is triggered. It is not clear if it is safe to make all steps interruptible. So this commit only makes the RaftBootstrapStep intteruptible as it is known to be blocking for a significantly long time.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #48136

### CODE REVIEW

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/partitioning/startup/steps/RaftBootstrapStep.java
Comment (entangled90) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/partitioning/startup/steps/RaftBootstrapStep.java:42]: 🔧 I'd add a cancellation point by check if the future is already canceled before starting the bootstrap?

File: zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/startup/StartupProcess.java [hunk 1]
```diff
@@ -73,6 +73,8 @@ public final class StartupProcess<CONTEXT> {
   private ActorFuture<CONTEXT> shutdownFuture;
   private ActorFuture<CONTEXT> startupFuture;
   private Map<String, String> loggingContext = Map.of();
+  private StartupStep<CONTEXT> ongoingStartupStep;
```
Comment (entangled90) [inline zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/startup/StartupProcess.java:76]: 🔧 I always wondered if we adding `volatile` is necessary for these fields as they are potentially accessed by multiple threads, but that's probably ok since only one thread at a time modified them. 
However, with the support of cancellation in this PR there's another thread that access them now, so we might need to mark them volatile.

File: zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/startup/StartupProcess.java [hunk 2]
```diff
@@ -233,6 +239,28 @@ private void shutdownSynchronized(
...
+      if (ongoingStartupStep != null
+          && ongoingStartupStep.isInterruptible()
+          && ongoingStartupStepFuture != null) {
+        setCustomMDC();
+        logger.info(
+            "Interrupting ongoing startup step {} due to shutdown request",
+            ongoingStartupStep.getName());
+        clearCustomMDC();
+        try {
+          ongoingStartupStepFuture.completeExceptionally(
```
Comment (entangled90) [inline zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/startup/StartupProcess.java:251]: 💭 we don't cancel the future because it's an `ActorFuture` and that does not support cancellation

**Review by entangled90 — COMMENTED** [review]
With this implementation, we complete the future from another thread, but the "task" is still running and is not cancelled/notified in any way.
Will the startup be prevented anyway because of a non daemon thread is still running for example?

**Comment by entangled90** [comment]
I'm also a bit worried that if shutdown is called after cancelling startup, then some fields will be null (because the startup was interrupted) and because the shutdown sets them to null. 
Did you checked already if need to include some extra null checks in the steps? 
Does the shutdown starts to shutdown all steps or only the ones that started successfully?

File: zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/startup/StartupProcess.java (hunk 1 above)
Comment (deepthidevaki) [reply zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/startup/StartupProcess.java:76]: Here it is not necessary, as they access is wrapped in `concurrencyControl`, so only one thread is accessing it.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/partitioning/startup/steps/RaftBootstrapStep.java
Comment (deepthidevaki) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/partitioning/startup/steps/RaftBootstrapStep.java:42]: I think it is not necessary as it is a blocking call and startup has not returned the future yet.

**Comment by deepthidevaki** [comment]
> I'm also a bit worried that if shutdown is called after cancelling startup, then some fields will be null (because the startup was interrupted) and because the shutdown sets them to null. Did you checked already if need to include some extra null checks in the steps? Does the shutdown starts to shutdown all steps or only the ones that started successfully?

Shutdown only calls step that are already started (for which startup was called). We already support aborting startup process if shutdown was called before startup process is completed. The difference is that it only aborts after the current step is completed, before next step is started. So that case is handled already.

**Comment by deepthidevaki** [comment]
> With this implementation, we complete the future from another thread, but the "task" is still running and is not cancelled/notified in any way. Will the startup be prevented anyway because of a non daemon thread is still running for example?

This is not a problem for Raft, as it can be shutdown in parallel. It might be a problem for some other steps, that's why we have to be careful when a step can be marked as interruptible.

**Review by entangled90 — APPROVED** [review]
Sorry I thought I approve this already!
Thanks
