### PR TITLE
Only allow the restore profile in the restore app.

### LINKED ISSUE #35022: Restore application fails to start with default profiles
### 

### 

### 

### 

### Description

The restore application fails to start by default in 8.8 as all the default profiles are applied, but there are several beans missing.

### Steps to reproduce

1. Launch the `camunda/camunda` image with `ZEEBE_RESTORE=true`

### Current behavior

Launching it fails with this exception:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.4.7)

[2025-07-08 11:29:22.703] [main] INFO
	io.camunda.zeebe.restore.RestoreApp - Starting RestoreApp v8.8.0-SNAPSHOT using Java 21.0.7 with PID 20 (/usr/local/camunda/lib/camunda-zeebe-8.8.0-SNAPSHOT.jar started by camunda in /usr/local/camunda/bin)
[2025-07-08 11:29:22.704] [main] INFO
	io.camunda.zeebe.restore.RestoreApp - The following 6 profiles are active: "restore", "identity", "operate", "tasklist", "broker", "consolidated-auth"
[2025-07-08 11:29:25.852] [main] WARN
	org.springframework.context.annotation.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.boot.actuate.autoconfigure.health.HealthEndpointConfiguration$HealthEndpointGroupMembershipValidator$NoSuchHealthContributorException: Included health contributor 'brokerStatus' in group 'status' does not exist
[2025-07-08 11:29:25.855] [main] INFO
	io.camunda.zeebe.backup.s3.S3BackupStore - Closing backup store
[2025-07-08 11:29:25.868] [main] INFO
	org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger -

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
[2025-07-08 11:29:25.874] [main] ERROR
	org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter -

***************************
APPLICATION FAILED TO START
***************************

Description:

Included health contributor 'brokerStatus' in group 'status' does not exist

Action:

Update your application to correct the invalid configuration.
You can also set 'management.endpoint.health.validate-group-membership' to false to disable the validation.
```

### Expected behavior

I don't need to specify any profiles when launching the application directly.

### Environment

SM
Helm Chart (8.8), which actively sets the `spring profiles`
```
  application.yaml: |
    spring:
      profiles:
        active: "identity,operate,tasklist,broker,consolidated-auth"
```

### Version

- Component Version: 8.8.0

### Rootcause

_No response_

### Solution ideas

None, but as a workaround you can set `SPRING_PROFILES_ACTIVE=restore`.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

This PR fixes the issue of several profiles being set while running the restore app. 

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes https://github.com/camunda/camunda/issues/35022

### CODE REVIEW

File: dist/src/main/java/io/camunda/zeebe/restore/RestoreApp.java [hunk 1]
```diff
@@ -65,6 +66,15 @@ public static void main(final String[] args) {
             .profiles(Profile.RESTORE.getId())
             .build();
 
+    final String activeProfiles = System.getProperty("spring.profiles.active");
```
Comment (npepinpe) [inline dist/src/main/java/io/camunda/zeebe/restore/RestoreApp.java:69]: 🤔 I'm realizing you can configure it in some many ways in Spring, via properties, config file, environment variable... I guess this will be a best effort?

A proper fix is likely to further split the configuration I guess, but... meh.

🔧 At least lets also check the `SPRING_PROFILES_ACTIVE` environment variable.

**Review by npepinpe — APPROVED** [review]
