### PR TITLE
fix(broker): limit JobBatchRecord to 65Kb

### LINKED ISSUE #1578: Broker dies if job worker wants to activate to many jobs at once
On JobWorker creation the user can specify how many jobs should be activated at once.

This could look like this:
```java

 final JobWorker subscription =
        client
            .jobClient()
            .newWorker()
            .jobType(JOB_TYPE)
            .handler(
                (c, t) -> {
                  reporter.increment();
                  c.newCompleteCommand(t.getKey()).payload("{}").send().join();
                })
            .timeout(10_000)
            .name("test")
            .bufferSize(1000)
            .open();
```
Apart from that the fact that name `bufferSize` is a bit misleading, the user can specify any `int` value.
This means the current JobProcessor implementation tries to create an batch with for example `1000` activate job events. 

This will cause following exception to be thrown:

```java
14:07:16.298 [0.0.0.0:26501-zb-actors-1] ERROR io.zeebe.logstreams - Stream processor 'job' failed to process event. It stop processing further events.
java.lang.RuntimeException: Cannot claim more than 174763 bytes.
	at io.zeebe.dispatcher.Dispatcher.claim(Dispatcher.java:294) ~[zb-dispatcher-0.13.0-20181028.182342-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.claimBatchForEvents(LogStreamBatchWriterImpl.java:220) ~[zb-logstreams-0.13.0-20181028.182352-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.logstreams.log.LogStreamBatchWriterImpl.tryWrite(LogStreamBatchWriterImpl.java:198) ~[zb-logstreams-0.13.0-20181028.182352-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedCommandWriterImpl.flush(TypedCommandWriterImpl.java:144) ~[zeebe-broker-core-0.13.0-20181028.182407-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.writeEvent(TypedStreamProcessor.java:201) ~[zeebe-broker-core-0.13.0-20181028.182407-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.writeEvent(StreamProcessorController.java:339) ~[zb-logstreams-0.13.0-20181028.182352-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.13.0-20181028.182325-25.jar:0.13.0-SNAPSHOT]
io.zeebe.client.cmd.ClientException: Failed to await termination of in-flight requests
	at io.zeebe.client.impl.ZeebeClientImpl.close(ZeebeClientImpl.java:125)
	at io.zeebe.AutoCloseables.close(AutoCloseables.java:41)
	at io.zeebe.cluster.ZeebeBrokerExtension.afterEach(ZeebeBrokerExtension.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:217)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:229)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:227)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:216)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:119)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Since the dispatcher explodes the broker also stops processing.

### PR DESCRIPTION
**Pull request by miguelpires**
This is a hotfix for the problem of the broker crashing when the job records returned in the JobBatchRecord exceed a limit imposed by the SBE protocol definition. This fix simply limits the jobs returned in a JobBatchRecord such that its size doesn't exceed 65Kb and ignoring the remaining jobs. Issue #1896 improves on this by proposing a way for the gateway to request the remaining jobs that couldn't be included in the broker's response and also an increase of the maximum permitted size in the record payload.

closes #1578

### CODE REVIEW

File: broker-core/src/test/java/io/zeebe/broker/job/ActivateJobsTest.java [hunk 1]
```diff
@@ -419,6 +420,26 @@ public void shouldFetchFullJobRecordFromWorkflow() {
     assertThat(customHeaders).isEqualTo(jobRecord.getValue().getCustomHeaders());
   }
 
+  @Test
+  public void shouldLimitJobsTo65KbSize() {
+    // given
```
Comment (Zelldon) [inline broker-core/src/test/java/io/zeebe/broker/job/ActivateJobsTest.java]: I would like to change a bit the test to the following, are you ok with that?

```java
@Test
  public void shouldLimitJobsTo65KbSize() {
    // given
    final int payloadSize = MAX_RECORD_SIZE / 3;
    final String payload = "{\"key\": \"" + RandomString.make(payloadSize) + "\"}";

    // when
    createJobs(JOB_TYPE, 3, payload);
    final List<Job> jobs = activateJobs(JOB_TYPE, 3);

    // then
    assertThat(jobs).hasSize(2);
    final List<Job> remainingJobs = activateJobs(JOB_TYPE, 1);
    assertThat(remainingJobs).hasSize(1);
  }
```

File: logstreams/src/main/java/io/zeebe/logstreams/impl/LoggedEventImpl.java [hunk 2]
```diff
@@ -30,6 +30,8 @@
 
 /** Represents the implementation of the logged event. */
 public class LoggedEventImpl implements ReadableFragment, LoggedEvent {
+
+  public static final int MAX_RECORD_SIZE = 65535;
```
Comment (Zelldon) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/LoggedEventImpl.java]: I would prefer using `1 << 16` or `0xFFFF` but this could be a matter of taste.

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Looks good I have some small things, if you want we can discuss them f2f.

**Comment by MiguelPires** [comment]
Thanks for the feedback. I made the changes you requested

**Review by ChrisKujawa — APPROVED** [review]
Thanks. LGTM :+1:
