### PR TITLE
fix(logstreams): fixes detection of empty log on seekToEnd

### LINKED ISSUE #3543: Unexpected non-empty log failed to read the last block
**Description**
On running qa tests I saw after test start the following logs.

```
09:00:58.927 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/10]: zeebe partitions
09:00:58.929 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
09:00:58.960 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-1] WARN  io.zeebe.logstreams - Unexpected non-empty log failed to read the last block
09:00:58.972 [GatewayTopologyManager] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {} and terms {}.
09:00:58.974 [GatewayTopologyManager] [0.0.0.0:25602-zb-actors-1] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '0' with address '0.0.0.0:25602' on transport 'gateway-broker-client'
09:00:58.980 [io.zeebe.logstreams.impl.log.LogStreamImpl] [0.0.0.0:25602-zb-actors-0] WARN  io.zeebe.logstreams - Unexpected non-empty log failed to read the last block
```

This doesn't make sense to me

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

- adds `LogStorageReader#isEmpty` as interface method
- fixes detection of empty log on `seekToEnd`
- removes `LogStorageReader#getFirstBlockAddress`, which was only used to detect an empty log

## Related issues

closes #3543 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: logstreams/src/main/java/io/zeebe/logstreams/spi/LogStorageReader.java [hunk 1]
```diff
@@ -11,11 +11,14 @@
...
   /**
-   * Returns the address of the first block in the storage or {@link
-   * LogStorage#OP_RESULT_INVALID_ADDR} if the storage is empty.
+   * Returns true if nothing could be read from the log, regardless of the current position of the
+   * reader - meaning any seek operations would not change the result of this call.
+   *
+   * @return true no records are readable, false otherwise
    */
-  long getFirstBlockAddress();
+  boolean isEmpty();
```
Comment (Zelldon) [inline logstreams/src/main/java/io/zeebe/logstreams/spi/LogStorageReader.java]: Should `isEmpty` be part of the `LogStorage`? And when this returns `true` `hasNext` should return false right? Or either read return `NO_DATA`.

Comment (npepinpe) [reply logstreams/src/main/java/io/zeebe/logstreams/spi/LogStorageReader.java]: What do you propose? The reader needs to figure out somehow if the underlying log is empty; before it was using `getFirstBlockAddress` and checking if it was negative, which imo is kind of hacky, when the goal is to determine if the underlying storage is empty.

Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/spi/LogStorageReader.java]: Was not sure whether isEmpty is the right place in the reader. Normally isEmpty are part of collections or persistence. And the reader or iterators has normally an hasNext method. This is more an abstraction/interface design thing I wanted to highlight/ask.

Comment (npepinpe) [reply logstreams/src/main/java/io/zeebe/logstreams/spi/LogStorageReader.java]: Agreed, it should be in the `LogStorage` (though it's arguable if our reader interfaces are really iterators since they do random access as well). In general I'd like to revise the log stream abstraction anyway, which apparently is an OKR next quarter. As it is, for now, I can move it to `LogStorage` and query the storage directly from the log reader (though I wanted to avoid having to keep an extra reference =/).

**Review by ChrisKujawa — APPROVED** [review]
We decided to change this now like this, because everything else would be a bigger topic. We plan to refactor the logstorage and journal handling part, such that we have access to the journal directly and check for is isEmpty in the LogStorage instead of the reader.
