### PR TITLE
fix: supply a timeout for process migration

### LINKED ISSUE #36176: Timeout for ProcessMigration application
For SaaS auto-upgrading clusters there can be a chance that the Process Migration job never concludes under the provided condition that the 8.7 Importers must be marked as `completed`.

To handle this scenario and free resources from our SaaS environments we will be providing a default timeout for this job. Within this window the process migration itself should be concluded.

Relevant threads:
https://github.com/camunda/camunda-operator/pull/4311
https://camunda.slack.com/archives/C06F0GLJNFM/p1753793831974129

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

Provide a force timeout for the process migration. This timeout will not trigger the termination if there are still Process Definitions being migrated. Rather, it's used to determine whether there is possible idling in the cluster and terminate without waiting for the 8.7 Importers to be completed.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #36176

### CODE REVIEW

File: migration/process-migration/src/test/java/io/camunda/migration/process/it/ProcessMigratorIT.java [hunk 1]
```diff
@@ -423,4 +424,71 @@ public void shouldNotFlushStepOnError(final boolean isElasticsearch) throws IOEx
...
+            () ->
+                assertThatExceptionOfType(MigrationException.class)
+                    .isThrownBy(migrator::call)
+                    .withCauseInstanceOf(MigrationTimeoutException.class)
+                    .withMessageContaining("Process Migration timed out"));
+  }
+
+  @ParameterizedTest
+  @ValueSource(booleans = {true, false})
+  public void shouldTimeoutAfterMigratingDataWithoutImportersCompleted(
```
Comment (RomanJRW) [inline migration/process-migration/src/test/java/io/camunda/migration/process/it/ProcessMigratorIT.java:459]: ❓ Could we also have a third test that asserts that the timeout doesn't occur while the countdown task is still running but not yet completed?

File: migration/process-migration/src/test/java/io/camunda/migration/process/it/ProcessMigratorIT.java [hunk 2]
```diff
@@ -423,4 +424,71 @@ public void shouldNotFlushStepOnError(final boolean isElasticsearch) throws IOEx
...
+            + 1;
+    Awaitility.await()
+        .atLeast(properties.getTimeout().getSeconds() - 1, TimeUnit.SECONDS)
+        .atMost(maxTimeout, TimeUnit.SECONDS)
+        .untilAsserted(
+            () ->
+                assertThatExceptionOfType(MigrationException.class)
+                    .isThrownBy(migrator::call)
+                    .withCauseInstanceOf(MigrationTimeoutException.class)
+                    .withMessageContaining("Process Migration timed out"));
```
Comment (RomanJRW) [inline migration/process-migration/src/test/java/io/camunda/migration/process/it/ProcessMigratorIT.java:454]: 🔧 NABD but you _could_ assert on the complete message here as you know the duration. Same for test below

**Review by RomanJRW — APPROVED** [review]
Couple of minor comments but otherwise LGTM 👍

File: migration/process-migration/src/test/java/io/camunda/migration/process/it/ProcessMigratorIT.java (hunk 1 above)
Comment (panagiotisgts) [reply migration/process-migration/src/test/java/io/camunda/migration/process/it/ProcessMigratorIT.java:459]: Caught a minor bug :+1:

File: migration/process-migration/src/test/java/io/camunda/migration/process/it/ProcessMigratorIT.java (hunk 2 above)
Comment (panagiotisgts) [reply migration/process-migration/src/test/java/io/camunda/migration/process/it/ProcessMigratorIT.java:454]: I'd avoid putting numbers here for potential flakes and changes that can be required to the durations down the road. I think it's pretty clear what is expected to be thrown.
