### PR TITLE
Fix garbage left after metrics exporter cleanup

### LINKED ISSUE #16405: Metrics Exporter leads to OOM
**Describe the bug**

We had an incident which caused a node to go OOM. Note that the cluster was doing very weird things like a PI calling itself recursively :upside_down_face: 

That said, we should avoid the metrics exporter going OOM by simply applying a memory bound to the maps it keeps, even as a fail safe.

Incident: https://app.incident.io/camunda/incidents/1012

**To Reproduce**

It's unclear why the map was not cleared out by the scheduled tasks, but there was also an incident recently where it seemed like a timer was not triggered, so it could be related (since the timer is in charge of rescheduling itself).

**Expected behavior**

The map does not grow beyond a certain, low size.

**Environment:**
- Zeebe Version: 8.1.x - 8.4.3

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

It's possible to build state in the metrics exporter if we have process instances or jobs which have the same timestamp creation. This is possible if you create more instances in the same milliseconds, which is possible thanks to call activities and batch processing :)

This PR fixes the issue by keeping track of a list of keys per timestamp, instead of a single value. It also adds a max capacity to the cache as a failsafe, defaulting to 10_000 for now (completely arbitrary number).

## Related issues

closes #16405 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java [hunk 1]
```diff
@@ -131,33 +129,28 @@ private void handleProcessInstanceRecord(
 
     if (currentIntent == ProcessInstanceIntent.ELEMENT_ACTIVATING
         && isProcessInstanceRecord(record)) {
-      storeProcessInstanceCreation(record.getTimestamp(), recordKey);
+      processInstanceCache.store(recordKey, record.getTimestamp());
     } else if (currentIntent == ProcessInstanceIntent.ELEMENT_COMPLETED
         && isProcessInstanceRecord(record)) {
-      final var creationTime = processInstanceKeyToCreationTimeMap.remove(recordKey);
+      final var creationTime = processInstanceCache.remove(recordKey);
```
Comment (deepthidevaki) [inline broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java:135]: :thought_balloon: When the key is not in the cache, this will update the latency as `completedTime - (-1)`, which would skew the metrics. This is not introduced in this PR though. But would be nice to handle this case.

**Review by deepthidevaki — APPROVED** [review]
:rocket:

File: broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java (hunk 1 above)
Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java:135]: Any ideas? We could simply not report it I suppose. Not sure why we were doing it before.

Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java:135]: I first though simply not reporting it would ok. But this also skews the result because we might not report any long running instances. May be cap it to threshold like a minute. May be use the default TIME_TO_LIVE as it is the cleanup interval. It is still not accurate, but better than us assuming it is all good because long lived instances are never included in the metric.

Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java:135]: Capping is probably the "best" solution, agreed

Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java:138]: The "null" value is now customizable instead of fixed at -1, so the exporter uses the TTL for missing values from now on :+1:
