### PR TITLE
fix(backup/s3): allow not configuring s3 credentials

### LINKED ISSUE #12433: Broker cannot start with S3 accessKey and secretKey not supplied
**Description**
We are configuring brokers with the S3 backup properties as follows:
- ZEEBE_BROKER_EXPERIMENTAL_FEATURES_ENABLEBACKUP: true
- ZEEBE_BROKER_DATA_BACKUP_STORE: S3
- ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME: <s3_bucket_name>
- ZEEBE_BROKER_DATA_BACKUP_S3_REGION: us-east-1
- ZEEBE_BROKER_DATA_BACKUP_S3_ENDPOINT: "https://s3.us-east-1.amazonaws.com"

We don't supply credentials through environment variables as they can be pulled from aws credentials provider chain. These properties worked on old version 8.1.9 but we got errors when switching to latest version 8.2.1 and broker cannot start due to the error:

> 
> 2023-04-14T11:21:51.313-04:00 | org.springframework.boot.SpringApplication - Application run failed
> 2023-04-14T11:21:51.313-04:00 | java.lang.IllegalStateException: Failed to execute CommandLineRunner
> 2023-04-14T11:21:51.313-04:00 | at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772) [spring-boot-3.0.5.jar:3.0.5]
> 2023-04-14T11:21:51.313-04:00 | at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:753) [spring-boot-3.0.5.jar:3.0.5]
> 2023-04-14T11:21:51.313-04:00 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-3.0.5.jar:3.0.5]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:82) [camunda-zeebe-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | Caused by: io.camunda.zeebe.broker.system.InvalidConfigurationException: Failed configuring backup store S3
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:132) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.1.jar:8.2.1]
> 2023-04-14T11:21:51.313-04:00 | at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:769) ~[spring-boot-3.0.5.jar:3.0.5]
> 2023-04-14T11:21:51.313-04:00 | ... 3 more
> 2023-04-14T11:21:51.313-04:00 | Caused by: java.lang.NullPointerException: Access key ID cannot be blank.

It looks like io.camunda.zeebe.backup.s3.S3BackupStore.buildClient still calls AwsBasicCredentials.create(credentials.accessKey(), credentials.secretKey() even we don't pass in any credentials. It might be related to this commit: https://github.com/camunda/zeebe/commit/dfd3b9e1034365b3fc1859d5e35353826e1222b3#diff-1b91d4d4e6875c0169ea56f9c35382f5f194a1af782db4879a26971fe32e6daeL72-L74
We also noticed that none of your unit or integration tests are checking for cases where ACCESS_KEY, SECRET_KEY are not passed. 

Could you please look into this issue? Thank you!

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This fixes a regression introduced in dfd3b9e and again allows to not configure s3 credentials and let the AWS SDK discover them instead.

Closes #12433

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/S3BackupAuthenticationIT.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+import io.zeebe.containers.ZeebeContainer;
+import org.apache.commons.lang3.RandomStringUtils;
+import org.assertj.core.api.Assertions;
+import org.junit.jupiter.api.Test;
+import org.testcontainers.containers.Network;
+import org.testcontainers.junit.jupiter.Container;
+import org.testcontainers.junit.jupiter.Testcontainers;
+
+@Testcontainers
+final class S3BackupAuthenticationIT {
```
Comment (deepthidevaki) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/S3BackupAuthenticationIT.java:22]: :thought_balloon: It's a bit unfortunate that we have to start the whole zeebe container for testing this. Wondering whether there is any way to do it in unit tests. I found some libraries for this https://github.com/webcompere/system-stubs and https://junit-pioneer.org/docs/environment-variables/. I have never used it, so don't know how useful they are.

**Review by deepthidevaki — APPROVED** [review]
:see_no_evil:  Thanks @oleschoenburg

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/S3BackupAuthenticationIT.java (hunk 1 above)
Comment (oleschoenburg) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/S3BackupAuthenticationIT.java:22]: Yeah that's fair. The AWS SDK also support reading the from properties which are a bit easier to set during runtime I think. I'll see if I can get something working.

Comment (oleschoenburg) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/S3BackupAuthenticationIT.java:22]: I think this is sort of possible but I'd like to not do this here:
1.junit-pioneer warns against modifying env variables or system properties. Both have concurrency issues and are not what Java expects.
2. This configuration is passed through a couple of places until it eventually ends up being used by the S3 client. Each of those places can break this so I think it makes sense to test this once, end to end, instead of unit testing a couple of different places.

**Comment by oleschoenburg** [comment]
bors merge
