### PR TITLE
fix: return a fallback from structuredContent to TextContent in MCP gateway responses

### LINKED ISSUE #46949: MCP gateway should return serialized JSON text response along with structuredContent
### 

### 

### 

### 

### Description

According to the [MCP spec](https://modelcontextprotocol.io/specification/2025-11-25/server/tools#structured-content), tools returning `structuredContent` should have a fallback to support clients without structured content support.

> For backwards compatibility, a tool that returns structured content SHOULD also return the serialized JSON in a TextContent block.

We currently only return `structuredContent` leading to issues with client implementations not reading it (e.g. Spring AI).

### Steps to reproduce

1. Use Spring AI to connect to the MCP gateway
2. Call a tool returning structured output
3. The LLM assumes no content is returned

### Current behavior

Only `structuredContent` is returned, leading to issues with clients not supporting it.

### Expected behavior

Both `structuredContent` and `content` with a single `TextContent` block containing the serialized response is returned.

### Workaround

Only workaround is to use a client capable of reading `structuredContent`.

### Environment

SaaS & SM

### Version

`8.9.0-SNAPSHOT`

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by maff**
## Description

According to the MCP spec: "For backwards compatibility, a tool that returns structured content SHOULD also return the serialized JSON in a TextContent block." This PR updates all usages of `CallToolResult` which produce `structuredContent` to also include a serialized version as `content`.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #46949

### CODE REVIEW

File: gateways/gateway-mcp/src/main/java/io/camunda/gateway/mcp/mapper/CallToolResultMapper.java [hunk 1]
```diff
@@ -17,7 +19,10 @@
 public class CallToolResultMapper {
 
   public static CallToolResult from(final Object content) {
-    return CallToolResult.builder().structuredContent(content).build();
+    return CallToolResult.builder()
```
Comment (maff) [inline gateways/gateway-mcp/src/main/java/io/camunda/gateway/mcp/mapper/CallToolResultMapper.java:22]: ℹ️ Potentially, we could move the mapping logic to `CallToolResult` into the tool callback and just return primitives/DTOs from tools, but this is out of scope for this fix.

File: gateways/gateway-mcp/src/main/java/io/camunda/gateway/mcp/mapper/CallToolResultMapper.java [hunk 2]
```diff
@@ -62,10 +67,22 @@ public static <T> Either<Throwable, T> executeServiceMethod(final CompletableFut
...
+        .build();
   }
 
   public static CallToolResult mapErrorToResult(final Throwable error) {
     return mapProblemToResult(GatewayErrorMapper.mapErrorToProblem(error));
   }
+
+  private static String structuredContentAsJson(final Object object) {
+    try {
+      return McpObjectMapperUtilities.getObjectMapper().writeValueAsString(object);
```
Comment (tmetzke) [inline gateways/gateway-mcp/src/main/java/io/camunda/gateway/mcp/mapper/CallToolResultMapper.java:83]: 💭 I'm wondering if we should use a different object mapper for this. This one is just for JSON schema generation. It doesn't have all the configuration our Spring app object mapper has 🤔

Comment (maff) [reply gateways/gateway-mcp/src/main/java/io/camunda/gateway/mcp/mapper/CallToolResultMapper.java:83]: That's a good point. I traced this back and what happens now:

- The `CallToolResult` is wrapped in the JSON-RPC response in [WebMvcStatelessServerTransport](https://github.com/spring-projects/spring-ai/blob/main/mcp/transport/mcp-spring-webmvc/src/main/java/org/springframework/ai/mcp/server/webmvc/transport/WebMvcStatelessServerTransport.java#L164), which returns a `ServerResponse` that is handled by the WebMvc stack
- As the JSON-RPC response is not one of our models, it is handled by the [default message converter](https://github.com/camunda/camunda/blob/main/dist/src/main/java/io/camunda/application/commons/rest/HttpMessageConverterConfiguration.java#L78) with the default ObjectMapper
- The only _serialization_ feature which is configured on the default OM is `WRITE_DATES_AS_TIMESTAMPS` which is also configured on `JsonParser`'s ObjectMapper.

⏩ We could also use `JsonParser.toJson()` to align what the library callback would do internally. I agree that this is confusing and we should probably align this to a canonical ObjectMapper, but I think the fallback result would be the same one as when using the platform one. As this would imply bigger refactorings, would you be ok with keeping this here as a fix for now & then potentially look at consolidating the serialization logic? Ideally we could handle this in our custom callback.

Comment (tmetzke) [reply gateways/gateway-mcp/src/main/java/io/camunda/gateway/mcp/mapper/CallToolResultMapper.java:83]: Thanks for digging in there. Makes sense to me 👍

Comment (tmetzke) [reply gateways/gateway-mcp/src/main/java/io/camunda/gateway/mcp/mapper/CallToolResultMapper.java:83]: Should we track this somewhere to follow up in 8.10?

**Review by tmetzke — APPROVED** [review]
👍 :shipit:
