### PR TITLE
Removes duplicate descriptor load

### LINKED ISSUE #7116: Segment descriptor is loaded twice
**Describe the bug**
In the `SegmentedJournal`, the descriptor is loaded twice. The first time we use it to read the metadata (e.g., id, index, etc) but we then read it again before loading the rest of the segment. Not only is this unnecessary but it might cause problems when we merge the additional safety checks (although it's unlikely). The checks could pass for the first load but become corrupted before the second which would result in corrupted data being loaded.

**Expected behavior**
The descriptor is loaded once.

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Remove second descriptor load and fix some issues in JournalSegmentFile.

blocked by #7121

## Related issues

closes #7116 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: journal/src/main/java/io/camunda/zeebe/journal/file/JournalSegmentFile.java [hunk 1]
```diff
@@ -94,7 +90,14 @@ static int getSegmentIdFromPath(final String name) {
...
     return new File(
-        directory, String.format("%s-%d.log", checkNotNull(name, "name cannot be null"), id));
+        directory,
+        String.format(
+            "%s%s%d%s%s",
+            checkNotNull(name, "name cannot be null"),
+            PART_SEPARATOR,
+            id,
+            EXTENSION_SEPARATOR,
+            EXTENSION));
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/JournalSegmentFile.java:100]: :+1:

**Review by deepthidevaki — APPROVED** [review]
:tada:
