### PR TITLE
Throw exceptions when task is submitted while actor scheduler is not running

### LINKED ISSUE #7771: I don't understand the actor system we use
Maybe I am just being stupid, but I don't get the actor system we use.

Given the following commit: https://github.com/camunda-cloud/zeebe/commit/0b1e17823f1797a299e197f52877914afbfd0f0a

If I change line 98 in `Broker`

From `scheduler.submitActor(brokerStartupActor);` to `scheduler.submitActor(brokerStartupActor).join();` the system halts completely (e.g. when running `SimpleBrokerStartTest`). I don't understand why. And I would rather wait for the actor to start.

Also, it seems like the join doesn't work as expected:
```
  private AutoCloseable migratedStartupSteps() {
    LOG.info("before Join");
    brokerStartupActor.call(() -> brokerStartupProcess.start()).join();
    LOG.info("after Join");
```

Produces this log:
```
20:05:55.646 [] [main] INFO  io.camunda.zeebe.broker.system - Bootstrap Broker-0 [1/12]: Migrated Startup Steps
20:05:55.647 [] [main] INFO  io.camunda.zeebe.broker.system - before Join
20:05:55.650 [] [main] INFO  io.camunda.zeebe.broker.system - after Join
20:05:55.650 [Broker Startup Actor] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Startup was called with context: io.camunda.zeebe.broker.bootstrap.BrokerStartupContextImpl@3eb6fd17
20:05:55.651 [Broker Startup Actor] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Startup monitoring services
20:05:55.653 [] [main] DEBUG io.camunda.zeebe.broker.system - Bootstrap Broker-0 [1/12]: Migrated Startup Steps started in 3 ms
```

However, I would have expected this log (ignore the millis in the timestamps):
```
20:05:55.646 [] [main] INFO  io.camunda.zeebe.broker.system - Bootstrap Broker-0 [1/12]: Migrated Startup Steps
20:05:55.647 [] [main] INFO  io.camunda.zeebe.broker.system - before Join
20:05:55.650 [Broker Startup Actor] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Startup was called with context: io.camunda.zeebe.broker.bootstrap.BrokerStartupContextImpl@3eb6fd17
20:05:55.651 [Broker Startup Actor] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Startup monitoring services
20:05:55.650 [] [main] INFO  io.camunda.zeebe.broker.system - after Join
20:05:55.653 [] [main] DEBUG io.camunda.zeebe.broker.system - Bootstrap Broker-0 [1/12]: Migrated Startup Steps started in 3 ms
```

### PR DESCRIPTION
**Pull request by pihme**
## Description

Changes the actor scheduler to check for running state when an actor is submitted

## Related issues

closes #7771 

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by pihme** [comment]
I have thought about completing the future exceptionally instead of throwing an exception. But then if somebody forgets to join on the future, the API would still not complain. And since this is such an obvious design error if it happens, I thought it's ok to just throw an exception

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java [hunk 1]
```diff
@@ -283,12 +283,13 @@ private Broker createBroker(final int nodeId) {
...
     systemContexts.put(nodeId, systemContext);
 
+    systemContext.getScheduler().start();
+
     final Broker broker = new Broker(systemContext, getSpringBrokerBridge(nodeId));
 
     broker.addPartitionListener(new LeaderListener(partitionLatch, nodeId));
     new Thread(
             () -> {
-              systemContext.getScheduler().start();
```
Comment (deepthidevaki) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java:291]: Previously it was working fine even if the actor was submitted before the scheduler is started? :thinking: It seems the task is not lost, but eventually get picked up once the scheduler is started.

**Review by deepthidevaki — APPROVED** [review]
Thanks :+1:

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java (hunk 1 above)
Comment (pihme) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java:291]: Seems like it, yes

**Comment by pihme** [comment]
bors merge
