### PR TITLE
fix: Cannot start Operate 8.7.18 with AWS Opensearch

### LINKED ISSUE #41383: Cannot start Operate 8.7.18 with AWS Opensearch
### 

### 

, 

### 

### 

### Description

Operate 8.7.18 fails to start when connected to AWS OpenSearch Service if the schema metadata document (id = "schema-version") is not present. 
AWS OpenSearch returns HTTP 404 for the `GET /operate-metadata_8.8.0/_doc/schema-version` call, and this case is retried/treated as an error, causing startup to loop instead of initializing a fresh baseline and writing the metadata.

### Steps to reproduce

1.  Ensure no metadata index/document exists for Operate’s schema version (for example, no operate-metadata-*/_doc/schema-version)
2. Configure Operate 8.7.18 to use AWS OpenSearch Service.
3. Start Operate.
4. Observe startup logs.

### Current behavior

* Operate attempts to read /operate-metadata-8.8.0_/_doc/schema-version.
* AWS OpenSearch returns HTTP 404.
* Operate retries and fails to progress past startup.

### Expected behavior

If the metadata index or schema-version document is missing, Operate should treat it as a fresh baseline and create the metadata after initialization.

### Workaround

**First ensure** that `operate-metadata-8.8.0_` index is created
Manually insert schema-version document matching the intended baseline before starting Operate, so the GET does not return 404.

```
PUT /operate-metadata-8.8.0_/_doc/schema-version
{
  "id": "schema-version",
  "value": "8.7.18"
}
```
In case `operate-metadata-8.8.0_` is not created (Operate 8.7.18 was not deployed yet), you can manually create it
```
PUT /operate-metadata-8.8.0_
{
    "aliases": {
      "operate-metadata-8.8.0_alias": {
        "is_write_index": false
      }
    },
    "settings": {
      "index": {
        "number_of_shards": 1, # update with the correct number of shards
        "number_of_replicas": 0 # update with the correct number of replicas
      }
    },
    "mappings": {
      "dynamic": "strict",
      "properties": {
        "id": {
          "type": "keyword"
        },
        "value": {
          "type": "keyword"
        }
      }
    }
  }
```

### Environment

SM

### Version

- Component Version: 8.7.18

### Rootcause

The OpenSearch client path used by Operate treats AWS OpenSearch’s 404 response for the missing document as a retriable error rather than “metadata not found → initialize baseline”.
There may be a mismatch in how Not Found is mapped/handled between different implementation as it works for Elasticsearch and open-source OpenSearch but not for AWS OpenSearch Service.

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

https://jira.camunda.com/browse/SUPPORT-30086

Version compatibility checks (schema metadata behavior and location): https://docs.camunda.io/docs/self-managed/components/orchestration-cluster/core-settings/concepts/version-compatibility/

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

OpenSearchClient uses 2 different OpenSearchTransport implementations between AWS IRSA and Basic Auth setups.
- AWS IRSA mode: `org.opensearch.client.transport.aws.AwsSdk2Transport`
- Basic auth mode: `org.opensearch.client.transport.rest_client.RestClientTransport`

When calling get document by Id for inexistent document, OpenSearch returns a 404 with an error payload that AwsSdk2Transport is not able to deserialize and causes this error
```
09:12:54.465 [] [main] [] INFO  io.camunda.operate.store.opensearch.client.sync.RichOpenSearchClient - Retrying #1  due to org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [http_exception] server returned 404
```

Same issue was reported in https://github.com/opensearch-project/opensearch-java/issues/424 and it was fixed in 2.12.0 version of the library, while we are still using 2.9.0.
**I confirm that when bumping the version to 2.12.0, the issue does not happen anymore.**

In this pull request, I propose an alternative solution, since I am unsure whether upgrading the SDK might introduce other issues.
I consists on adding a HEAD (exists) check before the GET-by-ID call to avoid triggering the exception.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #41383

### CODE REVIEW

File: operate/schema/src/test/java/io/camunda/operate/store/opensearch/OpensearchMetadataStoreTest.java [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.ExtendWith;
+import org.mockito.ArgumentCaptor;
+import org.mockito.InjectMocks;
+import org.mockito.Mock;
+import org.mockito.junit.jupiter.MockitoExtension;
+import org.opensearch.client.opensearch.core.IndexRequest;
+
+@ExtendWith(MockitoExtension.class)
+public class OpensearchMetadataStoreTest {
```
Comment (lilspikey) [inline operate/schema/src/test/java/io/camunda/operate/store/opensearch/OpensearchMetadataStoreTest.java:33]: Should we port this test over to the later versions too?

**Review by lilspikey — COMMENTED** [review]
Seems ok to me - assuming `getSchemaVersion` isn't called very often?

I assume this is only for the older versions too and we're on the newer version already on 8.8+?

**Comment by houssain-barouni** [comment]
> Seems ok to me - assuming `getSchemaVersion` isn't called very often?

yes, just on application startup
 
> I assume this is only for the older versions too and we're on the newer version already on 8.8+?

in 8.8, we use a newer version of Opensearch SDK, so the issue is not happening there

File: operate/schema/src/test/java/io/camunda/operate/store/opensearch/OpensearchMetadataStoreTest.java (hunk 1 above)
Comment (houssain-barouni) [reply operate/schema/src/test/java/io/camunda/operate/store/opensearch/OpensearchMetadataStoreTest.java:33]: The implementation is different in 8.8

Comment (lilspikey) [reply operate/schema/src/test/java/io/camunda/operate/store/opensearch/OpensearchMetadataStoreTest.java:33]: Right yeah I see that `OpensearchMetadataStore` doesn't exist in 8.8/main

**Review by lilspikey — APPROVED** [review]

File: operate/schema/src/main/java/io/camunda/operate/store/opensearch/OpensearchMetadataStore.java
Comment (yohanfernando) [inline operate/schema/src/main/java/io/camunda/operate/store/opensearch/OpensearchMetadataStore.java:54]: 💭  If it throws an exception, why not just catch it and return null to say the doc is not found? Rather than one exist call and one get call.

Comment (houssain-barouni) [reply operate/schema/src/main/java/io/camunda/operate/store/opensearch/OpensearchMetadataStore.java:54]: The SDK throws a generic `OpenSearchException`.  I need to parse the exception message to find out if this is a 404 for a missing document or other errors like cannot connect or anything else.
I prefer an extra call, it is expected to be done once on application start-up, no more

Comment (yohanfernando) [reply operate/schema/src/main/java/io/camunda/operate/store/opensearch/OpensearchMetadataStore.java:54]: Sure make sense if thats the case

**Review by yohanfernando — APPROVED** [review]
