### PR TITLE
4420 failed job activation

### LINKED ISSUE #4420: Endless loop on job activation if job does not fit in max message size
**Describe the bug**

When activating the oldest job in the job state would result in a `JobBatchRecord` which is too large to fit in the max message size, we currently end up in an endless loop - the gateway sees that `truncated` property of the response is true, and will retry that partition over and over again, but will never get anything while the job exists, as jobs are deterministically ordered.

Not only does this brick a gateway, but it's also not obvious what is going on at all, making this hard to react to.

**To Reproduce**

<details><summary>Integration Test</summary>

```java
package io.zeebe.broker.it.network;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.zeebe.broker.it.util.GrpcClientRule;
import io.zeebe.broker.test.EmbeddedBrokerRule;
import io.zeebe.model.bpmn.Bpmn;
import io.zeebe.model.bpmn.BpmnModelInstance;
import io.zeebe.test.util.BrokerClassRuleHelper;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.RuleChain;
import org.springframework.util.unit.DataSize;

public final class SmallMessageSizeTest {
  private static final ObjectMapper MAPPER = new ObjectMapper();
  private static final DataSize MAX_MESSAGE_SIZE = DataSize.ofKilobytes(4);
  private static final String LARGE_TEXT = "x".repeat((int) (MAX_MESSAGE_SIZE.toBytes() / 4));

  private static final EmbeddedBrokerRule BROKER_RULE =
      new EmbeddedBrokerRule(b -> b.getNetwork().setMaxMessageSize(MAX_MESSAGE_SIZE));
  private static final GrpcClientRule CLIENT_RULE = new GrpcClientRule(BROKER_RULE);

  @ClassRule
  public static RuleChain ruleChain = RuleChain.outerRule(BROKER_RULE).around(CLIENT_RULE);

  @Rule public final BrokerClassRuleHelper helper = new BrokerClassRuleHelper();

  private String jobType;

  private static BpmnModelInstance workflow(final String jobType) {
    return Bpmn.createExecutableProcess("process")
        .startEvent()
        .serviceTask("task", t -> t.zeebeJobType(jobType))
        .endEvent()
        .done();
  }

  @Before
  public void init() {
    jobType = helper.getJobType();
  }

  @Test
  public void shouldDeployLargeWorkflow() {
    // given
    final var workflowKey = CLIENT_RULE.deployWorkflow(workflow(jobType));
    final var workflowInstanceKey = CLIENT_RULE.createWorkflowInstance(workflowKey);

    // when
    for (int i = 0; i < 4; i++) {
      CLIENT_RULE
          .getClient()
          .newSetVariablesCommand(workflowInstanceKey)
          .variables(Map.of(String.valueOf(i), LARGE_TEXT))
          .send()
          .join();
    }

    // then
    final var response =
        CLIENT_RULE
            .getClient()
            .newActivateJobsCommand()
            .jobType(jobType)
            .maxJobsToActivate(1)
            .send()
            .join(10, TimeUnit.SECONDS);
    assertThat(response.getJobs()).hasSize(1);
  }
}
```

</details>

**Expected behavior**

Busting the max message size should not result in an inability to use a partition until the workflow is terminated. In an ideal world, if the job is too large to fit by itself, we could mark it as failed and raise an incident, that way we can keep processing other jobs. I would also be OK with a solution where the issue is clear and easy to diagnose so users can increase the max message size.

**Environment:**
 - OS: Fedora 31
 - Zeebe Version: 0.24.0-SNAPSHOT
 - Configuration: max message size 4kb

### PR DESCRIPTION
**Pull request by pihme**
## Description

* Raises incident if a single job cannot be activated, because it alone is too big for the max message size

## Related issues

closes #4420 

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java [hunk 1]
```diff
@@ -221,4 +236,31 @@ private void rejectCommand(
...
+      long jobKey, final JobRecord job, final TypedStreamWriter streamWriter) {
+
+    final DirectBuffer jobErrorMessage = job.getErrorMessageBuffer();
+    DirectBuffer incidentErrorMessage =
+        wrapString(
+            String.format(
+                "The job with key '%s' is too large for the configured message size.", jobKey));
+    if (jobErrorMessage.capacity() > 0) {
+      incidentErrorMessage = jobErrorMessage;
+    }
```
Comment (saig0) [inline engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java:250]: The job should not have an error message before. So, we can directly set the incident message. 

I think it could help the user if we provide more information about the message size and how to fix it. For example, 

`The job with key '123' can not be activated because it is larger than the configured message size (1,8MB). Try to reduce the size by limiting the fetched variables or modifying the variable values.`.

File: engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java [hunk 2]
```diff
@@ -221,4 +236,31 @@ private void rejectCommand(
...
+
+    final IncidentRecord incidentEvent =
+        new IncidentRecord()
+            .setErrorType(ErrorType.CONDITION_ERROR.IO_MAPPING_ERROR)
```
Comment (saig0) [inline engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java:254]: We need a new error type for this incident. The existing types don't fit.

File: engine/src/test/java/io/zeebe/engine/processor/workflow/incident/JobActivationIncidentTest.java [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+import org.junit.BeforeClass;
+import org.junit.ClassRule;
+import org.junit.Rule;
+import org.junit.Test;
+
+public final class JobActivationIncidentTest {
+  @ClassRule public static final EngineRule ENGINE = EngineRule.singlePartition();
+  private static final int MAX_MESSAGE_SIZE =
+      1024 * 1024 * 4; // copy and paste from LogStreamBuilderImpl
+  private static final String LARGE_TEXT = "x".repeat((int) (MAX_MESSAGE_SIZE / 4));
```
Comment (saig0) [inline engine/src/test/java/io/zeebe/engine/processor/workflow/incident/JobActivationIncidentTest.java:30]: Use a constant for this magic number `4` :)

File: engine/src/test/java/io/zeebe/engine/processor/workflow/incident/JobActivationIncidentTest.java [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+            .withIntent(IncidentIntent.CREATE)
+            .withWorkflowInstanceKey(workflowInstanceKey)
+            .getFirst();
+
+    ENGINE
+        .variables()
+        .ofScope(workflowInstanceKey)
+        .withDocument(
+            Map.of("0", "lorem ipsum", "1", "lorem ipsum", "2", "lorem ipsum", "3", "lorem ipsum"))
+        .update();
```
Comment (saig0) [inline engine/src/test/java/io/zeebe/engine/processor/workflow/incident/JobActivationIncidentTest.java:119]: An alternative would be to limit the fetched variables (e.g. fetch 3 instead of 4 variables). Maybe, we can create another test case for this.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/SmallMessageSizeTest.java [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+  }
+
+  @Before
+  public void init() {
+    jobType = helper.getJobType();
+  }
+
+  @Test
+  public void
+      shouldIgnoreJobsThatAreTooLargeToFitIntoAMessageAndProceedWithJobsThatAreBehindInQueue() {
```
Comment (saig0) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/SmallMessageSizeTest.java:58]: Wow. That is a long method name :joy: 
Can we shrink it a bit?

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/SmallMessageSizeTest.java [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+import java.util.concurrent.TimeUnit;
+import org.junit.Before;
+import org.junit.ClassRule;
+import org.junit.Rule;
+import org.junit.Test;
+import org.junit.rules.RuleChain;
+import org.springframework.util.unit.DataSize;
+
+public class SmallMessageSizeTest {
+  private static final ObjectMapper MAPPER = new ObjectMapper();
```
Comment (saig0) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/SmallMessageSizeTest.java:28]: The object mapper is not used in the test.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/SmallMessageSizeTest.java [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+  private static final DataSize MAX_MESSAGE_SIZE = DataSize.ofKilobytes(4);
+  private static final String LARGE_TEXT = "x".repeat((int) (MAX_MESSAGE_SIZE.toBytes() / 4));
```
Comment (saig0) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/SmallMessageSizeTest.java:30]: Use a constant for the magic number `4`.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/SmallMessageSizeTest.java [hunk 8]
```diff
@@ -0,0 +1,92 @@
...
+    return Bpmn.createExecutableProcess("process")
+        .startEvent()
+        .serviceTask("task", t -> t.zeebeJobType(jobType))
+        .endEvent()
+        .done();
+  }
+
+  @Before
+  public void init() {
+    jobType = helper.getJobType();
```
Comment (saig0) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/SmallMessageSizeTest.java:53]: We don't need a dynamic job type. We have only one test case.

**Review by saig0 — CHANGES_REQUESTED** [review]
Looks good :+1: Just a few notes.

Maybe, we can add a new test case to `JobStateTest`.

File: engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java (hunk 2 above)
Comment (pihme) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java:254]: @saig0 Is this a problem with backwards compatibility? Or is it just important to add the new error code at the end?

Comment (saig0) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java:254]: Good point. We should add it at the end to avoid any problem on deserialization.

File: engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java [hunk 9]
```diff
@@ -144,6 +153,12 @@ private void collectJobsToActivate(
             arrayValueJob.wrap(buffer);
           } else {
             value.setTruncated(true);
+
+            if (value.getJobs().isEmpty()) {
+              raiseIncidentJobTooLargeForMessageSize(key, jobRecord, streamWriter);
+              jobState.disable(key, jobRecord);
+            }
```
[the remark this answers is not in the document]
Comment (pihme) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java:160]: I agree with you that it would be easier to follow. However, then I would not have access to the `jobRecord`.

Would you rather leave it as it is, or refactor it for the collect method to return something that then can be analyzed?
Or am I missing something?

[the remark this answers is not in the document]
Comment (saig0) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java:161]: Good point. Then I don't have a suggestion.

File: util/pom.xml [hunk 10]
```diff
@@ -96,6 +96,11 @@
       <artifactId>assertj-core</artifactId>
       <scope>test</scope>
     </dependency>
+    <dependency>
+      <groupId>pl.pragmatists</groupId>
+      <artifactId>JUnitParams</artifactId>
+      <scope>test</scope>
+    </dependency>
```
Comment (saig0) [inline util/pom.xml:103]: I don't like to introduce a new testing framework only for this one case. I would prefer to migrate to JUnit 5 instead and use a more plain test style before.

File: engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java [hunk 11]
```diff
@@ -240,19 +241,19 @@ private void rejectCommand(
...
+
+    final DirectBuffer incidentMessage =
         wrapString(
             String.format(
-                "The job with key '%s' is too large for the configured message size.", jobKey));
-    if (jobErrorMessage.capacity() > 0) {
-      incidentErrorMessage = jobErrorMessage;
-    }
+                "The job with key '%s' can not be activated because it plus additional activation-related data together is larger than the configured message size (%s). "
+                    + "Try to reduce the size by reducing the number of fetched variables or modifying the variable values.",
```
Comment (saig0) [inline engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java:250]: The message is very precise but also a bit long. Maybe, we can remove some parts that are not so interesting for the user/operator.

```suggestion
                "The job with key '%s' can not be activated because it is larger than the configured message size (%s). "
                    + "Try to reduce the size by reducing the number of fetched variables or modifying the variable values.",
```

**Review by saig0 — CHANGES_REQUESTED** [review]

**Review by saig0 — APPROVED** [review]
:+1:

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
@ralfpuchert FYI this PR introduces a new ErrorType `MESSAGE_SIZE_EXCEEDED` in develop

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry
