### PR TITLE
Lower log level of broker errors in the gateway based on the error code

### LINKED ISSUE #5638: BrokerErrorException: Received error from broker (PARTITION_LEADER_MISMATCH)
**Describe the bug**
In the gateway, the following error is logged:
```
io.zeebe.gateway.cmd.BrokerErrorException: 
Received error from broker (PARTITION_LEADER_MISMATCH): 
Expected to handle client message on the leader of partition '4', but this node is not the leader for it
```

This error is expected when the leader of the partition is changed. No need to log it as an error.

**To Reproduce**
This issue occurred in Camunda Cloud: https://console.cloud.google.com/errors/CLewlMij0eqgkAE?service=zeebe&time=P7D&project=camunda-cloud-240911

This issue was logged a few times.

**Expected behavior**
The error is not logged in the gateway. Either, the request is sent to the new leader, or the failure is reported to the client (to do a client-side retry). 

**Log/Stacktrace**
From the Camunda cloud: https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%2287b431f1-1416-4490-b9ac-106b7520d437-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-19T11:48:57.376Z%2F2020-10-19T12:48:57.376Z;pinnedLogId=2020-10-19T12:18:27.376817Z%2Fnzuxqqwx7j1uqsj90?project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.zeebe.gateway.cmd.BrokerErrorException: Received error from broker (PARTITION_LEADER_MISMATCH): Expected to handle client message on the leader of partition '4', but this node is not the leader for it
at io.zeebe.gateway.impl.broker.BrokerRequestManager.handleResponse (BrokerRequestManager.java:148)
at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2 (BrokerRequestManager.java:130)
at io.zeebe.util.sched.future.FutureContinuationRunnable.run (FutureContinuationRunnable.java:28)
at io.zeebe.util.sched.ActorJob.invoke (ActorJob.java:76)
at io.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
at io.zeebe.util.sched.ActorTask.execute (ActorTask.java:118)
at io.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:107)
at io.zeebe.util.sched.ActorThread.doWork (ActorThread.java:91)
at io.zeebe.util.sched.ActorThread.run (ActorThread.java:204)
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `0.24.4`
 - Configuration: [e.g. exporters etc.]

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR lowers the log level of broker errors in the gateway to trace for RESOURCE_EXHAUSTED and PARTITION_LEADER_MISMATCH, both of which are reported verbatim to the client and counted in our gateway metrics, such that logs are of little use.

## Related issues

closes #5638 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Will backport once it's accepted.

File: gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java [hunk 1]
```diff
@@ -113,22 +105,20 @@ private Status mapBrokerErrorToStatus(final BrokerError error) {
         break;
       case RESOURCE_EXHAUSTED:
         builder.setCode(Code.RESOURCE_EXHAUSTED_VALUE);
+        logger.trace("Target broker is currently overloaded: {}", error);
         break;
       case PARTITION_LEADER_MISMATCH:
         // return UNAVAILABLE to indicate to the user that retrying might solve the issue, as this
         // is usually a transient issue
+        logger.trace("Target broker was not the leader of the partition: {}", error);
```
Comment (npepinpe) [inline gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:113]: One thing: I thought about setting it to debug, since it may be useful sometimes to know if we have leader mismatch - however you can see that via metrics, and here, well, we don't have request context info so I'm not sure it gives any more insight.

File: gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java [hunk 2]
```diff
@@ -113,22 +105,20 @@ private Status mapBrokerErrorToStatus(final BrokerError error) {
...
         builder.setCode(Code.UNAVAILABLE_VALUE);
         break;
-        // all the following are not errors which retrying (with the same gateway) will solve
-      case INVALID_MESSAGE_TEMPLATE:
```
Comment (npepinpe) [inline gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:123]: Normally I'd prefer having all cases, but in this case the non default cases are more the exceptions where we want different behaviour, so I think it makes sense to remove all explicit cases.

**Review by ChrisKujawa — APPROVED** [review]
thanks :+1:

**Comment by npepinpe** [comment]
bors retry
