### PR TITLE
fix: io mapping banner moves focus on render

### LINKED ISSUE #45994: Learn more button is focused when opening input mappings tab
### 

### 

### 

### 

### Description

"Learn more" button is focused when opening Input Mappings tab:

https://github.com/user-attachments/assets/82f459f2-d23a-45a1-9de4-f5be1c52f56b

### Steps to reproduce

1. Go to process instance details view
2. Select an element without any mappings
3. Click "Input Mappings" in the bottom right panel

### Current behavior

The "Learn More" button inside the panel is focused.

### Expected behavior

The focus should stay on the actively selected tab, same as for the other tabs

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- Component Version: 8.9-SNAPSHOT

### Rootcause

Might be a Carbon issue, because it tries to focus buttons inside of a tab view.

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by christoph-fricke**
## Description

This is a minimal solution that no longer moves the focus to the banner when rendered. The problem is that `hasFocus` is **marked deprecated** and will be removed with Carbon v12.

I briefly explored the suggested approach of using [`Callout`](https://react.carbondesignsystem.com/?path=/docs/components-notifications-callout--overview) instead, and looked at [`InlineNotification`](https://react.carbondesignsystem.com/?path=/docs/components-notifications-inline--overview). `Callout` seems to be closed to a workable solution but **requires concerning style hacks** to get the layout to look as before.

I believe a proper solution for Carbon v12 is to rather align with design on a solution that does not require styling hacks... For this bugfix, it feels a bit out of scope before Camunda 8.9.

## Related issues

closes #45994

### CODE REVIEW

File: operate/client/src/App/ProcessInstance/BottomPanel/VariablePanel/InputOutputMappings/IOMappingInfoBanner.tsx
Comment (juliasaienko) [inline operate/client/src/App/ProcessInstance/BottomPanel/VariablePanel/InputOutputMappings/IOMappingInfoBanner.tsx:20]: I understand that it wasn't introduced in this PR, but as we're already fixing something in the file, this small note can be considered:  he component renders with no title, which is used for its aria-labelledby on the alertdialog role. So as a result dialog has no accessible name.

File: operate/client/src/App/ProcessInstance/BottomPanel/VariablePanel/InputOutputMappings/index.test.tsx [hunk 1]
```diff
@@ -107,4 +107,12 @@ describe('Input Mappings', () => {
       expect(screen.queryByText(message)).not.toBeInTheDocument();
     },
   );
+
+  it('should not move focus to the info banner on render', () => {
```
Comment (juliasaienko) [inline operate/client/src/App/ProcessInstance/BottomPanel/VariablePanel/InputOutputMappings/index.test.tsx:111]: Is it correct that the baner requires fetch data to render? If thats correct, the test checks `document.activeElement` synchronously after render(), before data received and the baner appears. This means the test passes because the baner hasn't rendered yet, not because focus wasn't shifted.

Comment (christoph-fricke) [reply operate/client/src/App/ProcessInstance/BottomPanel/VariablePanel/InputOutputMappings/index.test.tsx:111]: Yeah. The component itself loads the instance XML, but the banner is shown immediately independent of the loading state. The other banner tests above also do not wait on data loading.

The tests passes due to the fix. Before submitting the change, I verified that the test fails without it - with the change it passes.

File: operate/client/src/App/ProcessInstance/BottomPanel/VariablePanel/InputOutputMappings/IOMappingInfoBanner.tsx
Comment (christoph-fricke) [reply operate/client/src/App/ProcessInstance/BottomPanel/VariablePanel/InputOutputMappings/IOMappingInfoBanner.tsx:20]: Any suggestions? Currently the `alertdialog` is labeled by the subtitle. If we add a title, it is visible which is not intended in the design files. Aria properties like `aria-label` do not seem to work, i.e. do not label the alert dialog.

Comment (juliasaienko) [reply operate/client/src/App/ProcessInstance/BottomPanel/VariablePanel/InputOutputMappings/IOMappingInfoBanner.tsx:20]: Ideally i would’ve use visually hidden title, but as it does have some label(even if labeling a dialog with a long explanation paragraph is not perfect) and I believe we don’t have practice to use visually hidden approch, we can left it as it is.

> Aria properties like aria-label do not seem to work, i.e. do not label the alert dialog.

I found this in the carbon code `"aria-labelledby": title ? id : subtitleId,`, so probably thats the reason.

**Review by juliasaienko — APPROVED** [review]
