### PR TITLE
pg/tenant-based-importer-completion

### LINKED ISSUE #38476: Migration from 8.7 to 8.8 gets stuck if cluster is "idle"
### 

### 

### 

### 

### Description

When upgrading from 8.7 to 8.8 we are introducing harmonized indices and exporters. As part of that data migration is going to happen to harmonize indices.

The problem here is that for some migrations to start we need to have the importers finished. The condition to check that the importer is finished relies on having a new record coming from 8.8, so if the cluster is idle, this never happens.

With that, user tasks are never migrated and not displayed. The same happens for metrics (but with no visible effect on UI)

### Steps to reproduce

1 - Create a 8.7 cluster with some data
2 - Update the cluster to 8.8, but ensure that the cluster is idle (not importing/exporting anything new from 8.8)
3 - The status of the update will be forever Updating because it's waiting for the importers to finish,

### Current behavior

Cluster update does not complete until it imported something from 8.8 - then user-task and metrics migration are triggered

### Expected behavior

After last record of the importer happens it should be flagged as completed

### Workaround

When reaching the state of getting stuck, it's possible to unblock it by deploying processes to the cluster

### Environment

SaaS & SM

### Version

8.8.0

### Rootcause

_No response_

### Solution ideas

[#tmp-migration-87-to-88-delay](https://camunda.slack.com/archives/C09G8PA8TCL)

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

Remove requirement for cluster processing in order to complete the Importers by having them access the `Tenant` created records.

These records, will be created by default once the upgrade to 8.8 has happened.

- Have ES/OS Exporters export `ValueType.TENANT` records by default
- Have Tasklist RecordReaders scrape the `tenant` aliased Zeebe record indices
- Have Operate RecordReaders scrape the `tenant` aliased Zeebe record indices

For verification, the manual ingestion of records during the Migration test suite has been removed and solely relies on the auto exporting of the `tenant` records

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #38476

### CODE REVIEW

File: qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java [hunk 1]
```diff
@@ -42,22 +40,25 @@ public class MigrationsShouldCompleteWithoutAnyDataIT {
...
-        id -> {
-          try {
-            assertMigrationStepsExist(tasklistMigrationIndex.getFullQualifiedName(), id);
-            assertMigrationStepsExist(operateMigrationIndex.getFullQualifiedName(), id);
-          } catch (final IOException | InterruptedException e) {
-            throw new UncheckedException(e);
-          }
-        });
+    // Migrations with suffix "1" is the Tasklist Task index Migrations
+    assertMigrationStepsExist(tasklistMigrationIndex.getFullQualifiedName(), "1");
```
Comment (deepthidevaki) [inline qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java:51]: :wrench: exist -> exits?

File: qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java [hunk 2]
```diff
@@ -42,22 +40,25 @@ public class MigrationsShouldCompleteWithoutAnyDataIT {
...
+
+    // Migration with suffix "2" is the Usage Metrics Migration
+    assertMigrationStepsExist(tasklistMigrationIndex.getFullQualifiedName(), "2");
+
+    // Since there is no data available for the process migration it will not be present in the
+    // migration index as no action has been taken. That's the reason the suffix "1" is missing
+    // here.
+
+    // Migration with suffix "2" is the Usage Metrics Migration
+    assertMigrationStepsExist(operateMigrationIndex.getFullQualifiedName(), "2");
```
Comment (deepthidevaki) [inline qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java:61]: :question: Where are these suffix coming from?

**Review by deepthidevaki — APPROVED** [review]
Thanks.

:wrench: Can you also add a test `MigrationsShouldCompleteWithoutAnyDataIT `where authentication, authorization and multi-tenancy check is disabled?

File: qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java (hunk 1 above)
Comment (panagiotisgts) [reply qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java:51]: No it's _exists_, we check whether the Migration step is recorded in the `tasklist/operate-migration-steps-repository` index. This is used to track the migrations

File: qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java (hunk 2 above)
Comment (panagiotisgts) [reply qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java:61]: It's an incremental suffix for the migrations that are running. It's inherited from how the `tasklist/operate-migration-steps-repository` used to operate. We declare them on each migration task, fex [TaskMigration](https://github.com/camunda/camunda/blob/248d6be59e0414cda32d90a340f9c32423d091d5/migration/task-migration/src/main/java/io/camunda/migration/task/adapter/TaskMigrationAdapter.java#L18)

File: qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java (hunk 1 above)
Comment (deepthidevaki) [reply qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java:51]: Ok. The migration is completed is implicitly verified in the `MigrationITExtension`.

Comment (panagiotisgts) [reply qa/migration-tests/src/test/java/io/camunda/it/migration/MigrationsShouldCompleteWithoutAnyDataIT.java:51]: Ah yeah. The actual @Test method is executed after the migration is completed. Everything else happens in the background for these update tests.

**Review by deepthidevaki — APPROVED** [review]
Thanks.
