### PR TITLE
Fix: Zeebe gateway fails to stream out activated jobs by not respecting the max message size

### LINKED ISSUE #12778: When activating jobs, the Zeebe Gateway fails to stream out activated jobs by not respecting the `maxMessageSize`
**Describe the bug**

By default, the `maxMessageSize` is set to 4MB, meaning, any incoming message cannot be greater than 4MB but also any outgoing message won't be greater than 4MB. This setting applies to the Broker and also to the Gateway.

Eventually, the `maxMessageSize` is used to collect jobs to activate in the Broker. So while collecting jobs, the broker checks the following conditions:
1. If the number of jobs already collected is greater than or equal to the passed `maxJobsToActivate`, then stop collecting further.
2. If the size (in bytes) of jobs - including their variables  - already collected + the size (in bytes) of the next job is greater than `maxMessageSize`, then stop collecting further.

https://github.com/camunda/zeebe/blob/f1a8adc26245dd132397d8a82c3e4ffb1486ca5f/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java#L94-L95

Assuming there are 100 jobs and each job has, in addition, variables of 1MB, that means - and when keeping it simple - it will collect the first jobs up to `maxMessageSize` of 4MB, and return these 4 jobs back to the Gateway.

Before streaming out the activated jobs, the Gateway will convert the Broker Response (MessagePack) to a Client Response (gRPC):

https://github.com/camunda/zeebe/blob/f1a8adc26245dd132397d8a82c3e4ffb1486ca5f/gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java#L245-L276

Thereby, it converts the variables from a byte array to a JSON as String representation:

https://github.com/camunda/zeebe/blob/f1a8adc26245dd132397d8a82c3e4ffb1486ca5f/gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java#L269

In terms of memory usage, the JSON as String is bigger than the byte array representation. That means, while the broker response is `<= 4MB` the actual Client response might result in a size `> 4MB`. So Zeebe Java Client rejects the response containing the activated jobs, and the Client cancels the channel/stream/connection as well. Also, the Gateway logs out a `Stream Error` indicating that streaming out the activated jobs to the client failed:

```
io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:173)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:481)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:105)
        at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1007)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:963)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:515)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:521)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:628)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onRstStreamRead(DefaultHttp2ConnectionDecoder.java:444)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onRstStreamRead(Http2InboundFrameLogger.java:80)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readRstStreamFrame(DefaultHttp2FrameReader.java:509)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:259)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Consequently, the activated jobs remain locked in the Broker (and they only are re-activatable after a configured timeout) because the exception above happens out of the control flow when sending back the activated jobs to the client. Additionally, the Gateway continues collecting further jobs for the same `ActivateJobs` request but fails to send them back to the Client as the stream already got canceled (but this time it happens in the control flow of the Gateway).

Why does the Zeebe Java Client reject the response?
By default, the max message inbound size is limited to 4MB.

**To Reproduce**
1. Start Zeebe 8.2.x with default values
2. Execute the following code with a Zeebe Java Client version 8.2.x:
```
public class DeployAndStartInstance {

  private static final Logger LOG = LogManager.getLogger(DeployAndStartInstance.class);

  public static void main(String[] args) {
    try (ZeebeClient client = ZeebeClientFactory.getZeebeClient()) {
      final var modelInstance = Bpmn.createExecutableProcess("foo")
          .startEvent()
          .serviceTask()
            .zeebeJobType("foo")
          .endEvent()
          .done();

      client.newDeployResourceCommand()
          .addProcessModel(modelInstance, "foo.bpmn")
          .send()
          .join();

      final var byteArray = new byte[1024*1024*1];
      new Random().nextBytes(byteArray);
      final var message = new String(byteArray, Charset.forName("UTF-8")); 

      for (int i = 0; i < 70; i++) {
        final ProcessInstanceEvent event = client.newCreateInstanceCommand()
            .bpmnProcessId("foo")
            .latestVersion()
            .variables(Map.of("message_content", message))
            .send()
            .join();
        
        LOG.info(
            "Started instance for processDefinitionKey='{}', bpmnProcessId='{}', version='{}' with processInstanceKey='{}'",
            event.getProcessDefinitionKey(), event.getBpmnProcessId(), event.getVersion(),
            event.getProcessInstanceKey());
      }

      client.newWorker().jobType("foo").handler((jobClient, job) -> {
        jobClient.newCompleteCommand(job.getKey()).send()
          // join(); <-- This would block for the result. While this is easier-to-read code, it has limitations for parallel work.
          // Hence, the following code leverages reactive programming. This is discssed in https://blog.bernd-ruecker.com/writing-good-workers-for-camunda-cloud-61d322cad862.
          .whenComplete((result, exception) -> {
            if (exception == null) {
              LOG.info("Completed job successful with result:" + result);
            } else {
              LOG.error("Failed to complete job", exception);
            }
          });
      }).open();

      // run until System.in receives exit command
      waitUntilSystemInput("exit");
    }
  }

  private static void waitUntilSystemInput(final String exitCode) {
    try (final Scanner scanner = new Scanner(System.in)) {
      while (scanner.hasNextLine()) {
        final String nextLine = scanner.nextLine();
        if (nextLine.contains(exitCode)) {
          return;
        }
      }
    }
  }
}
```

**Observed behavior**
* The Gateway logs a `WARNING: Stream Error` exception.
* The activated jobs remain locked for a given timeout.
* The Client logs out the following:
```
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
```

**Expected behavior**
* The Gateway respects the `maxMessageSize` when sending back the activated jobs to the Client.

**Some Solution Ideas**
* When mapping the broker response to the client response, do bookkeeping on the response size to ensure the `maxMessageSize`.
* Another idea would be to double the max inbound message size in the Zeebe Java Client by default.
* Nice to have: Bring the `WARNING: Stream Error` exception into the control flow of the Gateway so that the Gateway can react to it and potentially make the jobs re-activatable again.

**Environment:**
- Zeebe Version: 8.2.3
- Configuration: Default Configuration

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

There were three options to solve original problem:
1) When mapping the broker response to the client response, do bookkeeping
on the response size to ensure the maxMessageSize.
2) Double the max inbound message size in the Zeebe Java Client by default.
3) Bring the WARNING: Stream Error exception into the control flow of the Gateway
so that the Gateway can react to it and potentially make the jobs re-activatable again.

I used mixed of option 1 and 3 for better UX. With option 2, it is still possible for
client users to override default maxInboundMessage which might result in the same issue.

In the ResponseMapper, we check if the gRPC response size of the activated job will
exceed the allowed maxMessageSize in the gateway. Afterward, we re-activate exceeding
jobs in RoundRobinActivateJobsHandler in a similar way that we do for failed jobs.

Using `getSerializedSize()` method shouldn't have any performance impact here since
the result of it will be cached to be used while actually returning the response.
See: https://protobuf.dev/reference/java/api-docs/com/google/protobuf/AbstractMessage.html#getSerializedSize--

## Related issues

closes #12778 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java [hunk 1]
```diff
@@ -134,4 +151,64 @@ public void shouldCompleteJobWithLargeVariables() {
...
+              .bpmnProcessId("foo")
+              .latestVersion()
+              .variables(Map.of("message_content", message))
+              .send()
+              .join();
+
+      RecordingExporter.processInstanceRecords()
+          .withProcessInstanceKey(event.getProcessInstanceKey())
+          .withElementType(BpmnElementType.PROCESS)
+          .await();
```
Comment (korthout) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java:192]: 🔧 I think we don't have to wait for the command to be appended to the log in the loop because sending the 5 create instance commands and processing them asynchronously should be fine. I don't think it affects the rest of this test case.

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java [hunk 2]
```diff
@@ -134,4 +151,64 @@ public void shouldCompleteJobWithLargeVariables() {
...
+          .untilAsserted(
+              () ->
+                  assertThat(
+                          RecordingExporter.jobRecords(JobIntent.COMPLETED)
+                              .withType("foo")
+                              .limit(numberOfJobsToActivate)
+                              .count())
+                      .isEqualTo(numberOfJobsToActivate));
+    }
+  }
```
Comment (korthout) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java:213]: 👍 I like the test case!

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java [hunk 3]
```diff
@@ -134,4 +151,64 @@ public void shouldCompleteJobWithLargeVariables() {
...
+
+      RecordingExporter.processInstanceRecords()
+          .withProcessInstanceKey(event.getProcessInstanceKey())
+          .withElementType(BpmnElementType.PROCESS)
+          .await();
+    }
+
+    // when
+    final JobWorkerBuilderStep3 builder =
+        CLIENT_RULE.getClient().newWorker().jobType("foo").handler(COMPLETING_JOB_HANDLER);
```
Comment (korthout) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java:197]: ❌ Before opening the job worker, we must ensure that all 5 jobs exist. Otherwise, the job worker might activate jobs and receive less than 5 jobs.

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @berkaycanbc this looks like a great addition!

⏸️ I haven't come as far as reviewing the implementation, but the test looks good and I like the main idea for the implementation.

❌ However, I thought I would already send out this review because there's a change required in the test case. Please have a look.

File: gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java [hunk 4]
```diff
@@ -276,22 +278,30 @@ public static SetVariablesResponse toSetVariablesResponse(
     return SetVariablesResponse.newBuilder().setKey(key).build();
   }
 
-  public static ActivateJobsResponse toActivateJobsResponse(
-      final long key, final JobBatchRecord brokerResponse) {
+  public static JobActivationResult toActivateJobsResponse(
```
Comment (korthout) [inline gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:281]: 🔧 I'd like to see some Javadoc on this method, to clarify why the result contains a response **and** jobs to defer, and why a maxMessageSize is needed.

🔧 When writing that, we may choose to rename this maxMessageSize to maxResponseSize, as this better clarifies the parameter in the context of the method.

💭 I also wonder whether jobsToDefer is a fitting name in this method. In the context of the method, something like jobsExceedingSize, jobsThatDontFitInTheResponse, or something along those lines, may fit better semantically.

File: gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java [hunk 5]
```diff
@@ -276,22 +278,30 @@ public static SetVariablesResponse toSetVariablesResponse(
...
+      final long key, final JobBatchRecord brokerResponse, final int maxMessageSize) {
     final ActivateJobsResponse.Builder responseBuilder = ActivateJobsResponse.newBuilder();
 
     final Iterator<LongValue> jobKeys = brokerResponse.jobKeys().iterator();
     final Iterator<JobRecord> jobs = brokerResponse.jobs().iterator();
 
+    int currentResponseSize = 0;
```
Comment (korthout) [inline gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:288]: ❌ I believe this is not entirely correct. I assume there is some metadata associated to an `ActivateJobsResponse`. Currently, only the size of the individual `ActivatedJob`s are taken into account.

You could try creating an empty `ActivateJobsResponse` object to see the serialized size, and then doing the same with one, two, and three added `ActivatedJob`s to see how it grows. This will give you the insight what the initial size should be.

**Review by korthout — CHANGES_REQUESTED** [review]

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java (hunk 1 above)
Comment (berkaycanbc) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java:192]: @korthout is it because the instances themselves are lightweight so will be created fast enough? If so, could you give me some examples where we should use `await()` method? I am asking to clarify for the next time I use it. 👍

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java (hunk 3 above)
Comment (berkaycanbc) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java:197]: Yeah, makes sense! Updated.

File: gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java [hunk 6]
```diff
@@ -27,6 +27,7 @@
 import java.util.Queue;
 import java.util.concurrent.ConcurrentHashMap;
 import org.slf4j.Logger;
+import org.springframework.util.unit.DataSize;
```
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java]: Very good point! 🚀 Updated.

File: gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/RoundRobinActivateJobsHandler.java [hunk 7]
```diff
@@ -44,17 +46,22 @@ public final class RoundRobinActivateJobsHandler implements ActivateJobsHandler
...
+  private final int maxMessageSize;
 
   private ActorControl actor;
 
-  public RoundRobinActivateJobsHandler(final BrokerClient brokerClient) {
+  public RoundRobinActivateJobsHandler(
+      final BrokerClient brokerClient, final DataSize maxMessageSize) {
     this.brokerClient = brokerClient;
     topologyManager = brokerClient.getTopologyManager();
+    this.maxMessageSize = (int) maxMessageSize.toBytes();
```
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/RoundRobinActivateJobsHandler.java]: 🤦‍♂️. Updated!

File: gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java (hunk 4 above)
Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:281]: Good points, updated!

File: gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java (hunk 5 above)
Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java]: @korthout 


```java
final ActivateJobsResponse response =
        ActivateJobsResponse.newBuilder()
            .addJobs(ActivatedJob.newBuilder().build())
            .build();
System.out.println("response size: " + response.getSerializedSize()); // prints 2

final ActivatedJob activatedJob1 = ActivatedJob.newBuilder().build();
    System.out.println("activatedJob empty size: " + activatedJob1.getSerializedSize()); // prints 0
```

It only adds 2 bytes for each job added to ActivateJobsResponse and 0 for an empty activated job. I updated the code based on that, please take a look. 👀

**Comment by berkaycanbc** [comment]
Very useful feedback, thanks @korthout! ⭐ 

I applied your suggestions, please take a look. 👀

File: gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java [hunk 8]
```diff
@@ -276,22 +278,53 @@ public static SetVariablesResponse toSetVariablesResponse(
...
+
     while (jobKeys.hasNext() && jobs.hasNext()) {
       final LongValue jobKey = jobKeys.next();
       final JobRecord job = jobs.next();
       final ActivatedJob activatedJob = toActivatedJob(jobKey.getValue(), job);
 
-      responseBuilder.addJobs(activatedJob);
+      // +2 is for the metadata size that is added to ActivateJobsResponse when a new ActivatedJob
+      // is added to it
+      currentResponseSize += activatedJob.getSerializedSize() + 2;
```
Comment (korthout) [inline gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:319]: 🤔 This looks hard to maintain. If we ever add something to `ActivatedJob` or `ActivateJobsResponse` then this is no longer correct.

🔧 How about adding a post-condition check at the end of this method?
```java
if (currentResponseSize != response.getSerializedSize()) {
 // we've calculated the current response size incorrectly
}
```

Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:319]: @korthout If that is the case, how are we going to handle it? Are we going to put all jobs to `sizeExceedingJobs`? Or take the last job from the responseBuilder jobs list and put it into `sizeExceedingJobs`?

Comment (korthout) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:319]: When that happens, it means we have a bug. We can:
- log an error so users can report the bug
- throw an exception and reject the command
- or somehow add a test case that fails when the size is calculated wrongly (seems difficult)

I don't see a need to complicate the job selection logic for this. If we calculate the size wrongly **and** the response exceeds the size limit, then this will result in an error again.

My personal preference is simply logging an error, hoping that a user reports it.

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java (hunk 1 above)
Comment (berkaycanbc) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java]: Definitely more clear, thanks! 🚀

File: gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java (hunk 8 above)
Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:319]: @korthout The if check suggestion you provided will not do the work. Because current response size will always be different than the `response.getSerializedSize()` (e.g. serialized size will be +2).

Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:319]: I would either keep `+2` or not add it at all. Even if a new field is added to the ActivateJobsResponse and we faced with exceeding size failures, it will be easier to add a fix for that. WDYT? @korthout

Comment (korthout) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:319]: >The if check suggestion you provided will not do the work. Because current response size will be different than the `response.getSerializedSize()` even if we add jobs to exceeding list.

I don't understand what you mean. 

❓ In my mind, the goal is to not exceed the max message size with the response because that may break things. We added a way to calculate the response size while adding jobs to the response. That calculation is 0 bytes for the response + for each job: 'size of the job + 2 bytes for metadata'. Just before returning the response, we can also request the actual size of the response with `response.getSerializedSize()` which should be equivalent to the manually calculated size. Or is that not the case? Am I missing something?

Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:319]: Ohh :

Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:319]: Ohh 😯. You mean keeping the `+2` and if we forget to update the value on field updates, we log the error. Then, we expected to see these errors in log and fix the issue. Is that correct? @korthout 

I thought it is hard to maintain +2, so we should remove it.

Comment (korthout) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:319]: > You mean keeping the +2 and if we forget to update the value on field updates, we log the error. Then, we expected to see these errors in log and fix the issue. Is that correct?

Yes, that's correct. I would keep that logic while it's correct, but add a check on top that tells us that the logic is correct. If things ever change, we might not have a failing test for this, but at least we have an ERROR log message that users could report.

**Comment by berkaycanbc** [comment]
@korthout I found that the calculation of serialised size also depends of the length of returned response field. Looks like making the metadata size addition static will not be correct.

See related google protobuf implementations:
https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L607
https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L700


I will give a try to the re-building response until the actual response size is under max message size. 👍

**Comment by berkaycanbc** [comment]
@korthout I added another if check to the end of response mapper in case gRPC response exceeds max message size after building it. (metadata will be added)

I also added a test case in another commit by configuring it with some magic numbers. I try to add as much as explanation as possible to make the test case clear.

Please take a look. 👀

File: gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java [hunk 9]
```diff
@@ -301,30 +301,42 @@ public static SetVariablesResponse toSetVariablesResponse(
...
-    return new JobActivationResult(responseBuilder.build(), sizeExceedingJobs);
+    ActivateJobsResponse response =
+        ActivateJobsResponse.newBuilder().addAllJobs(responseJobs).build();
+    // Response size can still exceed the maximum response size because of the metadata added on
+    // building the response. Therefore, we check the response size again and if the response size
+    // is still exceeding the maximum response size, we remove the last added job from the response
+    // and add it to the list of jobs to be reactivated.
+    // We do this until the response size is below the maximum response size.
+    if (response.getSerializedSize() > maxResponseSize) {
+      while (!responseJobs.isEmpty() && response.getSerializedSize() > maxResponseSize) {
```
Comment (korthout) [inline gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:333]: 🔧 You could remove the if statement, as the while already covers it on its own.

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java (hunk 3 above)
Comment (korthout) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java:262]: ❌ This is still missing in both this test and the one above

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java [hunk 10]
```diff
@@ -134,4 +150,139 @@ public void shouldCompleteJobWithLargeVariables() {
...
+
+    RecordingExporter.jobRecords(JobIntent.CREATED)
+        .withType("foo")
+        .limit(numberOfJobsToActivate)
+        .await();
```
Comment (korthout) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java:267]: 💭 I think this does something else than you expect. While you limit the stream to 5 records, it only throws an exception when the stream has no entries after 5 seconds. It would wait 5 seconds and then continue if there is only a single job record.

**Review by korthout — CHANGES_REQUESTED** [review]
Nice @berkaycanbc 🙌 

👍 I like the new approach with a fast happy path and an easy to understand edge case.

❌ The test cases could be flaky, please have a look

File: gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java (hunk 9 above)
Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java:333]: Ahh, right, I missed it after the refactor. 👍

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java (hunk 10 above)
Comment (berkaycanbc) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java:267]: Just learned that it works that way, thanks! 🚀  Now, I assert the job count. 👍

**Comment by berkaycanbc** [comment]
@korthout I sent updates. Please take a look. 👀

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @berkaycanbc 

❌ There are still some things to fix:
- unused local variables on lines 179 and 249
- unnecessary blocking `join` on lines 187 and 257
- slow tests due to missing `limit` on lines 194 and 264
- test speed improvement possible by awaiting for all 5 jobs created before opening job worker (avoids multiple activation roundtrips)

**Comment by berkaycanbc** [comment]
@korthout I sent updates, please take a look. 👀 

> test speed improvement possible by awaiting for all 5 jobs created before opening job worker (avoids multiple activation roundtrips)

I am not sure which change is need for this one tho. I expect asserting job creation should do the work. Please feel free to add a code suggest if you think there is additional change needed for that. There is a support case waiting for this issue to be merged, so that we can speed this up to unblock customer. 👍

**Review by korthout — APPROVED** [review]
Thanks for the last changes @berkaycanbc ❤️ 

👍 LGTM

**Comment by korthout** [comment]
@berkaycanbc As you'll want to backport this PR, please rebase it on top of main rather than merging main in with a merge commit.

If you struggle with resolving conflicts multiple times, I recommend enabling [`git rerere`](https://git-scm.com/book/en/v2/Git-Tools-Rerere).

**Comment by berkaycanbc** [comment]
> @berkaycanbc As you'll want to backport this PR, please rebase it on top of main rather than merging main in with a merge commit.
> 
> If you struggle with resolving conflicts multiple times, I recommend enabling [`git rerere`](https://git-scm.com/book/en/v2/Git-Tools-Rerere).

Thanks @korthout, rebased onto main. 👍

**Comment by berkaycanbc** [comment]
Code scanning has a false positive, triggering merge.

bors merge

**Comment by berkaycanbc** [comment]
> This PR was included in a batch that successfully built, but then failed to merge into main. It will not be retried.
> 
> Additional information:
> 
> ```json
> {"message":"Changes must be made through the merge queue You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.","documentation_url":"https://docs.github.com/articles/about-protected-branches"}
> ```

Any ideas @korthout ?
