### PR TITLE
[backport - sort of - 1.2] Prevent multiple stream processors - fix and narrow test

### LINKED ISSUE #8044: StreamProcessors are kept alive
**Describe the bug**

We have a support issue, where the customer encountered several OOM issues. I had a deeper look at the dump and found some interesting parts were StreamProcessors seem to kept alive.

**Impact:** System has been killed by OOM Error at some point. We seem to keep some references to processors, which might lead to inconsistencies.

## Investigation

We have the following configuration: 

> Setup:
> cluster size:4
> partitions: 24
> replication factor: 4
> process: 150second duration
> PIPS: 2x100
> workers: 10
> embedded gateway

This means on each partition we have:

> Partitions per Node:
> N 0: 24
> N 1: 24
> N 2: 24
> N 3: 24
> 

### StreamProcessors
We would expect at max 24 StreamProcessors on each node, or in the heap dump. We can see 30.

streamprocessors-general

Using a OQL: `select s
from instanceof io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor s
where s.shouldProcess == false`

We find several paused/suspended StreamProcessors

suspendedProcessors

We can see that we have duplicate stream processors, one which is paused and probably another which is active. Can be shown if we query for there partition ids

duplicateProcessors

E.g. for partition 8 we have the two processors

If we check the suspended processor, we can only see that it is still referenced by an actor task and jobs plus timer subscriptions. 
processor-refs

### TypedRecordProcessor[]
Furthermore we see 26 TypedRecordProcessor arrays, which have 1300 entries. I feel this is to much (?).
recordProcessors

Taking a look at this we can see we have several times the same reference of processors.

refprocessors

### Partition

partition

Here we can see we have 24 partitions as expected.

Weird is that the Partition object has two fields call `context`.

contextinPartition

### ZeebeDBState

We can see that we have 26 states (more than partition)
dbstate

And for some partitions are duplicates
dbstate-duplicates

**To Reproduce**

Not sure.

**Expected behavior**

No duplicates of processors. Resources should be closed correctly.

**Log/Stacktrace**

Will be added later

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0
> Setup:
> cluster size:4
> partitions: 24
> replication factor: 4
> process: 150second duration
> PIPS: 2x100
> workers: 10
> embedded gateway

### PR DESCRIPTION
**Pull request by pihme**
## Description

Changes the transition logic as follows:
- preparation/cleanup is done for all steps (not just the steps started by the last iteration)
- preparation/cleanup is done in the context of the next transition, not in the context of the last transition.

As a consequence, preparation/cleanup will be executed more often than transitionTo. This can also be seen in the log for the new test case. Essentially, when a transition is "skipped" then only it's transitionTo is skipped, but the cleanup is executed anyway. I think one could improve that by making the cleanup react to the cancel signal, but I want to be conservative here. Also, multiple cleanup calls should be fast, because if a cleanup succeeds it sets e.g. the stream processor to null in the context, and any subsequent call will do nothing if it finds no stream processor.

Previously:
- The old transition did clean up the steps that were started by it
- The cleanup assumed that the transitionTo will immediately follow, but this was not a given. The transitionTo might be cancelled, and might eventually transition to a completely different role.
- So in essence, it did prepare for a role that maybe never came.

## Related issues

closes #8044
subset of #8059 
Essentially the same changes as #8062 (develop branch)

## Review Hints
This PR is a subset of #8059. It contains the fix and commits related to the first round of review comments. 
It does not contain the property based test, which is still the object of further discussion.

The purpose of this PR is to separate consensus from ongoing discussions.

The property based test has been run and in my mind validated the fix. Last week I also ran it with chains of six consecutive transitions and found no inconsistency. This gives me the confidence to merge the fix into the stable branch.

Please also indicate whether you think we need to add the property based test to `stable/1.2`. In my mind, it will be sufficient to introduce it in develop.

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java [hunk 1]
```diff
@@ -68,14 +70,16 @@ private void proceedWithTransition(final ActorFuture<Void> future) {
...
-
-          nextStep
-              .transitionTo(context, term, role)
-              .onComplete((ok, error) -> onStepCompletion(future, error));
+          try {
+            nextStep
+                .transitionTo(context, term, role)
+                .onComplete((ok, error) -> onStepCompletion(future, error));
+          } catch (final Exception | AssertionError e) {
+            future.completeExceptionally(e);
```
Comment (pihme) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java:81]: @Zelldon In the other PR you asked whether this change is necessary (the bit about catching the exception),
It is necessary, because without it any exception thrown in `transitionTo` will be logged by the threads uncaught exception method and the transition will be stuck.

Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java:81]: For me it feels like we mix test with production code

Comment (pihme) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java:81]: Because of the `AssertionError` ? Or how do you mean it?

Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java:81]: Yeah correct, also the try catch in general was only added because of the tests right? Before there was no try catch, in production code in this case the actor (zeebe partition)  would fail.

**Review by ChrisKujawa — COMMENTED** [review]
Since you mentioned you will not follow my request I don't know what else I should review here (https://github.com/camunda-cloud/zeebe/pull/8059#discussion_r740028063 )

> The purpose of this PR is to separate consensus from ongoing discussions.
> 
> The property based test has been run and in my mind validated the fix. Last week I also ran it with chains of six consecutive transitions and found no inconsistency. This gives me the confidence to merge the fix into the stable branch.
> 
> Please also indicate whether you think we need to add the property based test to stable/1.2. In my mind, it will be sufficient to introduce it in develop.

You know my opinion. I would like to have it on stable and close to the dev. Since we continue working on dev it might happen that dev property tests are green, but the property test in stable are not right? But you or @deepthidevaki might have an different opinion.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java (hunk 1 above)
Comment (pihme) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java:81]: Well, yes and no. It was discovered in tests that when an exception is thrown at this location, then the actor would fail. Which is a bug in my opinion. But happy to discuss this aspect. 

But the assertion error, yes, that is very specific to the tests and not needed.

**Comment by deepthidevaki** [comment]
IMO adding property test to the stable branch is a good idea. But it would be ok to do this as part of a separate PR because we are still discussing about the tests on the other PR.

**Review by deepthidevaki — APPROVED** [review]
Looks good to me. 
Do we want to toggle the transition feature flag back to using the new one?

One small thing - This PR is mostly the backport of the fix done in develop, right? If yes, I would suggest to change the title as such and may be link the original PR in the PR description.

**Comment by pihme** [comment]
> Do we want to toggle the transition feature flag back to using the new one?

Good question. @Zelldon @deepthidevaki @npepinpe What do you think?

**Review by ChrisKujawa — APPROVED** [review]

**Comment by pihme** [comment]
bors merge

**Comment by npepinpe** [comment]
We definitely want to enable it on develop. As for 1.2, how confident do we feel about it at the moment? I would defer to the judgement of those who were involved at the moment - however if you want, I can take a deeper look at the PR and the test coverage and give a more detailed opinion.

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
> We definitely want to enable it on develop. As for 1.2, how confident do we feel about it at the moment? I would defer to the judgement of those who were involved at the moment - however if you want, I can take a deeper look at the PR and the test coverage and give a more detailed opinion.

On develop the old code has been removed for a month now, so there is no other option right now.

I feel confident to switch to the new code.

**Comment by pihme** [comment]
bors retry
