### PR TITLE
fix(journal): clear index mapping on reset

### LINKED ISSUE #6237: Follower index is sometimes not cleaned up correctly
**Describe the bug**

**TL;DR;** It seems that the growing heap usage is related to the index of a follower.

We observed in the stable cluster benchmark a growing heap memory usage.
growing

I took some heap dump's on different times and different nodes and I saw that often when the memory usage was quite high we had a lot of long living `Long` objects. These objects are referenced for example by a `TreeMap`, which is used by the SparseJournalIndex. But also some are referenced by the `ConccurentSkipList` which is used by the `ZeebeIndexAdapter`.

One of the heap I checked was node **two** which was leader for partition one and two and follower for partition three. This node had a quite high heap usage.

zb2-global

We can see it had 15 million Long objects and a lot TreeMap and ConcurrentSkipList nodes. Based on a OQL query I was able to find relative big TreeMaps.

query

Based on that I was able to find the SparseJournalIndex.

sparseindex

and the related partition.

partition

If we check the `ZeebeIndexAdapter` we see the usage of the `ConcurrentSkipList`.

zb2-zeebeindexadapter

**Node 0**

If we check another node (broker 0), which is follower for all partitions, we see around ~60k indexes in the journal indexes. 
node0-sparseindex

node0-sparseindex2

It seems to be a problem with compacting. After a leader change has happened we saw for short time different heap usage.

[I check also the logs and it seems that we are able to compact the log at node 2 for partition 3.](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-01-30T17:11:20.447460000Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2021-01-30T16:28:19.302467000Z&dateRangeStart=2021-01-30T16:13:22.000Z&dateRangeEnd=2021-01-30T18:13:22.000Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-long-running%22%0Aresource.labels.namespace_name%3D%22zell-one-col-memory%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-one-col-memory%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0Aresource.labels.pod_name%3D%22zell-one-col-memory-zeebe-2%22%0AjsonPayload.context.actor-name%3D%22Broker-2-DeletionService-3%22)

```
Expand all | Collapse all{
 insertId: "469zgyg1exlr5f"  
 jsonPayload: {
  context: {
   actor-name: "Broker-2-DeletionService-3"    
   loggerName: "io.zeebe.broker.logstreams.delete"    
   threadId: 35    
   threadName: "Broker-2-zb-actors-3"    
   threadPriority: 5    
  }
  logger: "io.zeebe.broker.logstreams.delete"   
  message: "Compacting Atomix log up to index 741501199" 
```

```
D 2021-01-30T16:16:18.668634Z Compacting Atomix log up to index 741389699 
D 2021-01-30T16:17:18.921243Z Compacting Atomix log up to index 741501199 
D 2021-01-30T16:18:18.339542Z Compacting Atomix log up to index 741613099 
D 2021-01-30T16:19:18.670935Z Compacting Atomix log up to index 741725699 
D 2021-01-30T16:20:18.937142Z Compacting Atomix log up to index 741838299 
D 2021-01-30T16:21:19.167123Z Compacting Atomix log up to index 741945699 
D 2021-01-30T16:22:18.529814Z Compacting Atomix log up to index 742056799 
```

**To Reproduce**
Run a benchmark on stable nodes.

**Expected behavior**
The journal index is not that big and can be compacted.

**Environment:**
 - OS: k8
 - Zeebe Version:  1.0.0-SNAPSHOT
 - Configuration: [e.g. exporters etc.]

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Related issues

closes #6237 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java [hunk 1]
```diff
@@ -120,19 +120,20 @@ public void deleteUntil(final long index) {
...
         compactSegments.clear();
       }
+      journalIndex.deleteUntil(index);
       resetHead(getFirstSegment().index());
     }
   }
 
   @Override
   public void reset(final long nextIndex) {
+    journalIndex.clear();
```
Comment (Zelldon) [inline journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java:136]: This would mean we clear the complete index right? Is this really what we want here? Isn't this call reseting the journal to the given index, like deleteAfter(index-1) and set this index on the writer?

Comment (deepthidevaki) [reply journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java:136]: reset means deleting all entries in the journal and reset the nextIndex. So, yes. We want to clear the complete index. 

Should we rename the method to make the semantics clear? Any suggestions?

Comment (Zelldon) [reply journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java:136]: yeah it seems I have still issues to understand this method even after discussing several times it with you :laughing: sorry

**Review by ChrisKujawa — APPROVED** [review]
thanks @deepthidevaki :medal_military:

File: journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java (hunk 1 above)
Comment (Zelldon) [reply journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java:136]: maybe also calling reset on index would help :man_shrugging:

Comment (Zelldon) [reply journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java:136]: I looking at the code and I still don't get it. If we take a look at the writer for example you mentioned that it will reset (clear the journal and set the index to the given one right? Why does it need to read all entries, index them verify the checksum etc. This doesn't make sense to me

Comment (deepthidevaki) [reply journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java:136]: Journal#reset calls SegmentedJournalWriter#reset which deletes all existing segments and creates a new segment with the given index. 
#reset() in MappedJournalSegmentWriter is different. It is more like re-initializing the writer. Yes, it is confusing. But this was the existing code. I hope that we will fix it as part of rewriting SegmentedJournal implementation.

Comment (Zelldon) [reply journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java:136]: Ok then this will not fix our current bug or? :thinking: The PassiveRole calles directly writer#reset

Comment (deepthidevaki) [reply journal/src/main/java/io/zeebe/journal/file/SegmentedJournal.java:136]: When new journal is integrated to the raft, it can only call journal#reset. So it should not be a problem. 
But when backporting the index should be cleared in the writer.
Btw, only realized now that I fixed it only on the new journal which is not yet used by the raft. Should I also do the fix on the existing one?

**Comment by deepthidevaki** [comment]
@Zelldon As we discussed, I also fixed the existing code. The benchmark is running on long running cluster. I will update the memory impact after a few hours.

**Comment by Zelldon** [comment]
Any insights from the benchmark?

**Comment by deepthidevaki** [comment]
Sorry. Here is heap usage for last 4 days. It is stable.

image

**Comment by Zelldon** [comment]
Awesome thanks :+1: :rocket:

**Review by ChrisKujawa — APPROVED** [review]
