### PR TITLE
fix: update index template settings only when they change

### LINKED ISSUE #37240: Unnecessary index template settings updates cause redundant PUT requests and startup overhead
### 

### 

### 

### 

### Description

During schema initialization the system always issues PUT requests to update index template settings for both Elasticsearch and OpenSearch, even when no actual change (priority, shard/replica settings) is required. This leads to redundant cluster state updates, noisy logs, and avoidable startup latency.

### Steps to reproduce

1. Start Camunda with search schema creation enabled.
2. Observe logs: template creation/updates logged.
3. Enable ES or OS debug logs.
4. Restart without changing any index related configuration.
5. Observe repeated template update attempts despite no changes.

### Current behavior

On each startup, the SchemaManager triggers template update logic which unconditionally sends template PUT requests.

### Expected behavior

Template settings (priority, number_of_shards, number_of_replicas, other static settings) are compared with the desired configuration. Only when differences exist should an update (PUT) be sent. Otherwise no-op with a debug log.

### Environment

SaaS & SM

### Version

- Component Version: 8.8

### Rootcause

Missing pre‑update comparison of template priority and resolved settings block loaded from descriptor vs current template state retrieved from the cluster.

### Solution ideas

- Skip updating index templates settings when no updates are detected
- Run settings updates concurrently using virtual threads in SchemaManager to reduce total time.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

Skip redundant index template settings PUTs for Elasticsearch/OpenSearch. 
Adds parallel execution of index settings updates  to cut overhead.

## Problem
Every startup overwrote template settings (priority, shards, replicas) even when unchanged. This wasted requests, bumped ES/OS cluster.

## Solution
* Compare desired vs current template priority + serialized settings.
* Only send PUT if something changed; otherwise log debug skip.
* Run settings updates in parallel (virtual threads).

## Effects
* No unnecessary template PUTs on steady restarts.
* Faster startup with many templates.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes [#37240](https://github.com/camunda/camunda/issues/37240)

### CODE REVIEW

File: schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchEngineClient.java [hunk 1]
```diff
@@ -483,33 +491,46 @@ utils.new SchemaSettingsAppender(templateFile)
     }
   }
 
-  private PutIndexTemplateRequest updateTemplateSettings(
+  private Optional<PutIndexTemplateRequest> buildTemplateSettingsUpdateRequestIfChanged(
```
Comment (EuroLew) [inline schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchEngineClient.java:495]: 🔧 A bit hard to understand I would prefer it be split up

```
private Optional<PutIndexTemplateRequest> buildTemplateSettingsUpdateRequestIfChanged(
    final IndexTemplateDescriptor templateDescriptor,
    final IndexConfiguration configuredSettings) {

  try (final var templateFile = getResourceAsStream(templateDescriptor.getMappingsClasspathFilename())) {
    final var currentTemplate = getIndexTemplateState(templateDescriptor);
    final var configuredPriority = convertValue(configuredSettings.getTemplatePriority(), Long::valueOf);
    
    final var newSettings = utils.new SchemaSettingsAppender(templateFile)
        .withNumberOfShards(configuredSettings.getNumberOfShards())
        .withNumberOfReplicas(configuredSettings.getNumberOfReplicas());

    if (areTemplateSettingsEqualToConfigured(currentTemplate, configuredPriority, newSettings)) {
      LOG.debug("Index template settings for [{}] are already up to date", templateDescriptor.getTemplateName());
      return Optional.empty();
    }

    return Optional.of(buildPutIndexTemplateRequest(templateDescriptor, currentTemplate, newSettings, configuredPriority));

  } catch (final IOException e) {
    throw new SearchEngineException(
        "Failed to load file " + templateDescriptor.getMappingsClasspathFilename() + " from classpath.", e);
  }
}

private boolean areTemplateSettingsEqualToConfigured(IndexTemplateState currentTemplate, Long configuredPriority, SchemaSettingsAppender newSettings) {
  return Objects.equals(configuredPriority, currentTemplate.priority())
      && newSettings.equalsSettings(serializeAsMap(currentTemplate.template().settings()));
}

private PutIndexTemplateRequest buildPutIndexTemplateRequest(
    IndexTemplateDescriptor templateDescriptor,
    IndexTemplateState currentTemplate, 
    SchemaSettingsAppender settingsAppender,
    Long priority) {
  
  final var updatedSettings = deserializeJson(IndexTemplateMapping._DESERIALIZER, settingsAppender.build()).settings();
  
  LOG.debug("Applying to index template [{}]: settings={}, priority={}", 
      templateDescriptor.getTemplateName(), updatedSettings, priority);

  return new PutIndexTemplateRequest.Builder()
      .name(templateDescriptor.getTemplateName())
      .indexPatterns(templateDescriptor.getIndexPattern())
      .template(t -> t
          .settings(updatedSettings)
          .mappings(currentTemplate.template().mappings())
          .aliases(currentTemplate.template().aliases()))
      .priority(priority)
      .build();
}
```

**Review by EuroLew — APPROVED** [review]
LGTM would just like th logic to be easier to understand

File: schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchEngineClient.java (hunk 1 above)
Comment (EuroLew) [reply schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchEngineClient.java:495]: also do the same for OS

Comment (houssain-barouni) [reply schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchEngineClient.java:495]: Thanks for the hint, I tired to make it clearer now
 I did not add though
```
private PutIndexTemplateRequest buildPutIndexTemplateRequest(
    IndexTemplateDescriptor templateDescriptor,
    IndexTemplateState currentTemplate, 
    SchemaSettingsAppender settingsAppender,
    Long priority) {
```
I feel it is very specific and it is not reusable, I think it is clear enough now
