### PR TITLE
fix(broker): use correct term and role when reacting to install failures 

### LINKED ISSUE #6997: Back to back role changes cause ZeebePartition to go unhealthy and transition to inactive
**Describe the bug**

Installing leader services failed because of following exception:

```
java.lang.IllegalStateException: Not leader of partition 1
	at io.zeebe.broker.system.partitions.impl.steps.AtomixLogStoragePartitionStep.lambda$open$1(AtomixLogStoragePartitionStep.java:43) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.Optional.ifPresentOrElse(Optional.java:203) ~[?:?]
	at io.zeebe.broker.system.partitions.impl.steps.AtomixLogStoragePartitionStep.open(AtomixLogStoragePartitionStep.java:26) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.installPartition(PartitionTransitionImpl.java:105) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.lambda$transition$1(PartitionTransitionImpl.java:85) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```

This error happens when raft has changed the role and term before ZeebePartition has completed transition for the previous term. When this happens, we want to prevent the leader from previous term from appending new entries with the new term. That's why this step fails with this exception. However this fails the leader installation and ZeebePartition detects it as a failure and go inactive, which is not expected.

```
E 2021-05-06T13:42:18.479009Z Expected to open step 'AtomixLogStorage' but failed with 
E 2021-05-06T13:42:18.479385Z Failed to install leader partition 1 
I 2021-05-06T13:42:18.479743Z Unexpected failures occurred when installing follower services, transitioning to inactive 
E 2021-05-06T13:42:18.480418Z ZeebePartition-1 failed, marking it as unhealthy 
```

There are two issues here:
1. When "java.lang.IllegalStateException: Not leader of partition 1" exception happens, there will be already next transition in queue. But ZeebePartition takes action as if the leader install failed. ZeebePartition doesn't have to react as if installation failed and steps down. If it steps down, it might trigger another unnecessary leader election.
2. Even though here leader installation failed, ZeebePartition reacts as if the follower installation failed and go inactive. This happened because it is reading the current role of the raft partition instead of checking which transition failed. This role is different because of asynchronous role transition between raft and zeebe.

In this situation, one partition is unhealthy and the raft is inactive. However it is recoverable by restarting the node.

**To Reproduce**
Not sure how to reproduce this. But check the logs for understanding the scenario.

**Expected behavior**

1. When "java.lang.IllegalStateException: Not leader of partition 1" exception happens, it should just close the current leader services instead of failing or stepdown.
2. On install failures the reaction should be based on for which transitions it failed instead of reading the current role of raft partition.

**Log/Stacktrace**
[logs](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-05-06T13%3A50%3A34.903000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe-cluster%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.namespace_name%3D%22medic-cw-17-df496d4b4-benchmark%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.pod_name%3D%22medic-cw-17-df496d4b4-benchmark-zeebe-1%22%0Atimestamp%3D%222021-05-06T13%3A42%3A18.479009000Z%22%0AinsertId%3D%221iya3xff2y1jbd%22&scrollTimestamp=2021-05-06T13%3A42%3A18.484158000Z) 

**Environment:**
 - Zeebe Version: 1.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

The role transitions are enqueued in ZeebePartition actor. When there are more than one role transition happened one after the other in a short span, ZeebePartition doesn't know which installation has failed. Previously it was reading the term and role from the RaftPartition. However, since the role transitions are asynchronous the role and term on the RaftPartition might be already referring to a newer term and role.

To fix this, now PartitionContext keep track of current term and role which is updated when the corresponding install steps has started. On install failure, ZeebePartition can read the term and role from the context to determine how to react to the failure.

## Related issues

closes #6997 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java [hunk 1]
```diff
@@ -118,14 +116,14 @@ private void onRoleChange(final Role newRole, final long newTerm) {
                 listenerFutures,
                 t -> {
                   // Compare with the current term in case a new role transition happened
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:118]:
```suggestion
```

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java [hunk 2]
```diff
@@ -258,28 +256,31 @@ public void onUnrecoverableFailure() {
     actor.run(this::handleUnrecoverableFailure);
   }
 
-  private void onInstallFailure(final long term, final Throwable error) {
+  private void onInstallFailure(final Throwable error) {
     if (error instanceof UnrecoverableException) {
       LOG.error(
           "Failed to install partition {} with unrecoverable failure: ",
           context.getPartitionId(),
           error);
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:264]: I assume it would be quite interesting to log the current term and index right?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java [hunk 3]
```diff
@@ -258,28 +256,31 @@ public void onUnrecoverableFailure() {
...
     context
         .getPartitionListeners()
-        .forEach(l -> l.onBecomingInactive(context.getPartitionId(), term));
+        .forEach(l -> l.onBecomingInactive(context.getPartitionId(), context.getCurrentTerm()));
 
-    if (context.getRaftPartition().getRole() == Role.LEADER) {
+    // If RaftPartition has already transition to a new role in a new term, we can ignore this
+    // failure. Services will be installed for the new role.
+    if (context.getCurrentRole() == Role.LEADER
+        && context.getCurrentTerm() == context.getRaftPartition().term()) {
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:280]: Lets say the node become leader in raft. The previous follower installation failed, for what ever reason. Then the term is not equal and the currentRole is Follower, we going to inactive, instead of just installing the leader partition. Does this make sense?

Why we ignore the failure when we become leader in a higher term? This would mean we have a running raft leader but not Zeebe Leader Partition installed?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/PartitionStep.java [hunk 4]
```diff
@@ -16,20 +16,6 @@
...
-  /**
-   * Performs some action required for the partition to function. This may include opening
-   * components (e.g., logstream), setting their values in {@link PartitionContext}, etc. The
-   * subsequent partition steps will only be opened after the returned future is completed.
-   *
-   * @param currentTerm the current term of the transition
-   * @param context the partition context
-   * @return future
-   */
-  default ActorFuture<Void> open(final long currentTerm, final PartitionContext context) {
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/PartitionStep.java:29]: This was no longer used?

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @deepthidevaki :+1: 

I thought we already fixed that. I have the feeling that this is permanent construction site :see_no_evil: I think it is fine for now, I just added some questions/comments we can discuss them f2f if you want. 

At some point I would like to have a solution where these properties are immutable. I thought about having an actor for the leader and follower partition which are created for each transition. You submit an actor on installing, which follows the complete open lifecycle and if a new transition is happening you close the actor (which then closes the resources in the close-actor-lifecycle) and after the actor is closed you submit the next one. Wdyt?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java (hunk 3 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:280]: > Lets say the node become leader in raft. The previous follower installation failed, for what ever reason. Then the term is not equal and the currentRole is Follower, we going to inactive, instead of just installing the leader partition. Does this make sense?

If the previous follower installation failed, raft would go inactive.

> Why we ignore the failure when we become leader in a higher term? This would mean we have a running raft leader but not Zeebe Leader Partition installed?

Higher term in raft means there is already a new transition enqueued in ZeebePartition. Hence the services for that transition will be installed. If we don't ignore this failure and stepdown, then we are unnecessarily triggering a new leader election.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/PartitionStep.java (hunk 4 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/PartitionStep.java:29]: No. Term is now in PartitionContext. There was only one PartitionStep that needed the term. It now reads it from the context.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java (hunk 2 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:263]: Term might be interesting. But why should we log index? I assume you mean raft log index.

Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:263]: Actually I meant what you added to the context, so term and role, sorry for the confusion. I think it makes sense to add more context.

Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:263]: That make sense. Before we didn't know which role failed. But now it is in the context. So we should log it.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java (hunk 3 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:279]: > If the previous follower installation failed, raft would go inactive.

I get that, but why? We could also just install the leader partition right?

> Higher term in raft means there is already a new transition enqueued in ZeebePartition. Hence the services for that transition will be installed. If we don't ignore this failure and stepdown, then we are unnecessarily triggering a new leader election.

Thanks makes sense now. Maybe we can make the doc a bit more clearer. As you wrote before with higher term, we know that a transition is enqueue which is why it is safe to ignore it etc.

Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:279]: > I get that, but why? We could also just install the leader partition right?

Sorry. I misunderstood your question. :facepalm: 
We can ignore the failure if (only if) the new role is leader. However there is a scenario that can lead to no follower services installed in zeebe.
1. Raft transition to leader (term 2). But the initial entry is not committed. Raft doesn't notify zeebe until initial entry is committed.
2. Follower install failed (term 1)
3. Raft initial entry commit failed. Raft transition to follower in term 2.
4. Raft notifies zeebe of follower role.
5. Zeebe doesn't install follower services because it is already in follower role.

**Review by ChrisKujawa — APPROVED** [review]
Nice thanks :100:

**Comment by deepthidevaki** [comment]
Forgot to backport :slightly_smiling_face: 

/backport
