### PR TITLE
Batch operation - additional status handling (started / failed)

### LINKED ISSUE #30325: Proper status handling in batch execution scheduler
Follow up from this comment: https://github.com/camunda/camunda/pull/29916#discussion_r2018543513

🔧 before appending chunks, let's write a BatchOperationIntent.STARTED event.

🔧 if the query fails for whatever reason (maybe not able to serialize the filter), let's write a BatchOperationIntent.FAILED event.

In both appliers we should remove pending status from the state.
In case of failed, maybe add it to another column family.

### PR DESCRIPTION
**Pull request by p-wunderlich**
## Description

Adds new status started and failed to batch operation scheduler. 

* A Started event will be appended before we work on the chunks
* A Failed event will be appended, if the persisted filter cannot be deserialised 
  * For this a new custom EntityFilterDeserializeException was introduced, it will be thrown by the getEntityFilter method of the PersistedBatchOperation

## Related issues

closes #30325

### CODE REVIEW

**Review by mustafadagher — COMMENTED** [review]
❌ I've looked into this PR, and I'm not sure that the addition of `appendEventRecord` to `TaskResultBuilder` would work as expected to be honest. 
If you look at how the `ResultBuilderBackedEventApplyingStateWriter` applies events before appending them, you might understand what I mean. This this not the same for `TaskResults`

Let's discuss this at a later point

**Comment by p-wunderlich** [comment]
@mustafadagher You are right, just tested it again, although the exporter get's the record, it will not be applied to the state.

`[RDBMS Exporter] Process record 1-28664 - BATCH_OPERATION_CREATION:STARTED`

Hm, and since a Task should also not manipulate state, wer have to throw a command first and use a processor the create the event. I will rework it.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java [hunk 1]
```diff
@@ -97,16 +100,55 @@ private TaskResult execute(final TaskResultBuilder taskResultBuilder) {
...
+          batchOperation.getKey(),
+          batchOperation.getBatchOperationType(),
+          e);
+      appendFailedEvent(taskResultBuilder, batchOperation);
     }
 
     appendExecution(batchOperation, taskResultBuilder);
   }
 
+  private void appendStartedEvent(
```
Comment (stoerti) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:132]: ❌  it's called appendEvent but actually you append a command

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java [hunk 2]
```diff
@@ -97,16 +100,55 @@ private TaskResult execute(final TaskResultBuilder taskResultBuilder) {
...
+      final TaskResultBuilder taskResultBuilder, final PersistedBatchOperation batchOperation) {
+    final var batchOperationKey = batchOperation.getKey();
+    final var command = new BatchOperationCreationRecord();
+    command.setBatchOperationKey(batchOperationKey);
+    command.setBatchOperationType(batchOperation.getBatchOperationType());
+    LOG.debug("Appending batch operation {} started event", batchOperationKey);
+    taskResultBuilder.appendCommandRecord(batchOperationKey, BatchOperationIntent.START, command);
+  }
+
+  private void appendFailedEvent(
```
Comment (stoerti) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:142]: ❌  it's called appendEvent but actually you append a command

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java [hunk 3]
```diff
@@ -97,16 +100,55 @@ private TaskResult execute(final TaskResultBuilder taskResultBuilder) {
...
+        final Set<Long> chunkKeys =
+            keys.stream().skip(i).limit(CHUNK_SIZE_IN_RECORD).collect(Collectors.toSet());
+        appendChunk(batchOperation, taskResultBuilder, chunkKeys);
+      }
+    } catch (final EntityFilterDeserializeException e) {
+      LOG.error(
+          "Failed to deserialize entity filter, batch operation with key {} will be removed from queue",
+          batchOperation.getKey(),
+          e);
+      appendFailedEvent(taskResultBuilder, batchOperation);
```
Comment (stoerti) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:119]: 💭 The failure has no reason field, so the end user does not know what and why it failed and if a retry would be useful.

**Review by stoerti — CHANGES_REQUESTED** [review]

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java [hunk 4]
```diff
@@ -97,16 +100,55 @@ private TaskResult execute(final TaskResultBuilder taskResultBuilder) {
...
+    } catch (final IllegalArgumentException e) {
+      LOG.error(
+          "Failed to execute batch operation with key {} because operation type '{}' is not known",
+          batchOperation.getKey(),
+          batchOperation.getBatchOperationType(),
+          e);
+      appendFailedEvent(taskResultBuilder, batchOperation);
```
[the remark this answers is not in the document]
Comment (p-wunderlich) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:126]: Yes if it already happens at creation time. But what if save works and it just happens here? E.g. because of a pot restart and the filter object changed?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java (hunk 3 above)
Comment (p-wunderlich) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:119]: Hm to transport the reason to the user we would have to extend the BatchOperationCreationRecord with something like a rejection reason. Or could we just use the rejection reason of the record for this? @mustafadagher 

But for this we would have to extend the TaskResultBuilder as well, to pass the rejection reason.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java [hunk 5]
```diff
@@ -97,16 +100,55 @@ private TaskResult execute(final TaskResultBuilder taskResultBuilder) {
...
+          batchOperation.getKey(),
+          e);
+      appendFailedCommand(taskResultBuilder, batchOperation);
+    } catch (final IllegalArgumentException e) {
+      LOG.error(
+          "Failed to execute batch operation with key {} because operation type '{}' is not known",
+          batchOperation.getKey(),
+          batchOperation.getBatchOperationType(),
+          e);
+      appendFailedCommand(taskResultBuilder, batchOperation);
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:126]: 💭 I'm thinking about this again now, both of those validations should really happen on the API layer and not delayed until here.

Comment (p-wunderlich) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:126]: But even if we do this, it could happen that the Filter could not be deserialized? Or should we ignore it? 

In general I think we need a fail handling.

Comment (stoerti) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:126]: I think the validations automatically happen in the API layer because the filter and the type are deserialized there before they are wrapped in the batch request dto.

The only edge case is, when a type might be removed or the filter object changes in an incompatible way while the batchOperation is in INIT phase. But IMHO that is VERY unlikely and we also could fail with a generic internal server error then. My bigger concern ist, that in any case we currently do not deliver a failure reason to the client.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java [hunk 6]
```diff
@@ -93,16 +96,55 @@ private TaskResult execute(final TaskResultBuilder taskResultBuilder) {
...
   }
 
+  private void appendStartedCommand(
+      final TaskResultBuilder taskResultBuilder, final PersistedBatchOperation batchOperation) {
+    final var batchOperationKey = batchOperation.getKey();
+    final var command = new BatchOperationCreationRecord();
+    command.setBatchOperationKey(batchOperationKey);
+    command.setBatchOperationType(batchOperation.getBatchOperationType());
+    LOG.debug("Appending batch operation {} started event", batchOperationKey);
+    taskResultBuilder.appendCommandRecord(batchOperationKey, BatchOperationIntent.START, command);
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:135]: 💭 this command does not have the filter now, not sure if we actually need it here. but I'm just thinking out loud

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java [hunk 7]
```diff
@@ -93,16 +96,55 @@ private TaskResult execute(final TaskResultBuilder taskResultBuilder) {
...
+  }
+
+  private void appendFailedCommand(
+      final TaskResultBuilder taskResultBuilder, final PersistedBatchOperation batchOperation) {
+    final var batchOperationKey = batchOperation.getKey();
+    final var command = new BatchOperationCreationRecord();
+    command.setBatchOperationKey(batchOperationKey);
+    command.setBatchOperationType(batchOperation.getBatchOperationType());
+    LOG.debug("Appending batch operation {} failed event", batchOperationKey);
+    taskResultBuilder.appendCommandRecord(batchOperationKey, BatchOperationIntent.FAIL, command);
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:145]: same here

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java (hunk 5 above)
Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:122]: I want to emphasize on this point:
It's almost absolutely unlikely that one of those two errors will happen here and now.
We can still have some failures here, if for example the secondary storage is down and is not responding. But we haven't taken that into consideration here.
But right now, it's not possible that neither case would happen if we already validate it on the API layer. And more specifically the wrong operation type case.

**Review by mustafadagher — APPROVED** [review]
I'll approve this to move forward for now. But please consider my last comments. Specially the one about the `failed` status.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java (hunk 6 above)
Comment (p-wunderlich) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:135]: At this state we have the filter at least already in the state, and in rdbms we don't need it right now. I would say if we need it later, we can still add it here.

**Review by stoerti — APPROVED** [review]
