### PR TITLE
fix: distributed commands not starting

### LINKED ISSUE #33960: Distributed commands are not distributed once a partition becomes active
When a partition becomes active, the distributed commands that were enqueued when the partition was not active yet are not distributed when it becomes active.

Those commands are `ENQUEUED`, which means they are put into the `pendingDistributionQueue`, but the `CommandRedistributor` only sends commands that are in the `retriableDistributionQueue`.

## Solution proposal
When a partition becomes active, we should do something similar to `CommandDistributionBehaviour.startDistributing` (for all queues though).

### PR DESCRIPTION
**Pull request by entangled90**
## Description
When a partition is starting, it's included in command distribution, but the distribution itself is not starting yet: the events are just enqueued.
Once the partition becomes active, we need to start distributing immediately all the enqueued events.

Before this fix, each queue would start distributing only when one command was received for that queue, which is problematic as it could take a long time before such command is distributed.

## Related issues

closes #33960

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java [hunk 1]
```diff
@@ -69,10 +69,12 @@ public void processNewCommand(final TypedRecord<ScaleRecord> command) {
...
 
     final var rejection = validate(command);
-    if (rejection.isPresent()) {
-      rejectWith(command, rejection.get().getLeft(), rejection.get().getRight());
+    if (rejection.isLeft()) {
+      final var tuple = rejection.getLeft();
+      rejectWith(command, tuple.getLeft(), tuple.getRight());
       return;
     }
+    final var partitionId = rejection.get();
```
[the remark this answers is not in the document]
Comment (entangled90) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java]: `getRight` method does not exist.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/distribution/CommandDistributionBehavior.java [hunk 2]
```diff
@@ -120,6 +120,18 @@ public void onRecovered(final ReadonlyStreamProcessorContext context) {
             });
   }
 
+  public void startDistributingForPartition(final int partitionId) {
+    for (final var queue : DistributionQueue.getValues()) {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/distribution/CommandDistributionBehavior.java]: 💭 This means we lose the flexibility of using custom distribution queue in the future. For example, distributing a deployment in it's own deployment queue using it's key. And any later commands related to this deployment in the same queue. As opposed to what we have now, a single queue for all deployments.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java [hunk 3]
```diff
@@ -69,10 +69,12 @@ public void processNewCommand(final TypedRecord<ScaleRecord> command) {
     final var scaleUp = command.getValue();
 
     final var rejection = validate(command);
-    if (rejection.isPresent()) {
-      rejectWith(command, rejection.get().getLeft(), rejection.get().getRight());
+    if (rejection.isLeft()) {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java]: 🔧 It's a bit odd to call this variable `rejection` as it's an either that could also be a success.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java [hunk 4]
```diff
@@ -85,6 +87,7 @@ public void processNewCommand(final TypedRecord<ScaleRecord> command) {
       stateWriter.appendFollowUpEvent(scalingKey, ScaleIntent.SCALED_UP, scaleUp);
     }
     distributionBehavior.withKey(scalingKey).inQueue(DistributionQueue.SCALING).distribute(command);
+    distributionBehavior.startDistributingForPartition(partitionId);
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java]: ❓ What partition is this? It comes from the validation where it seems we just grab the first redistributed partition. What if you scale up with more than 1 partition? Shouldn't we call this for each of them? Or will those be separate commands?

**Review by remcowesterhoud — COMMENTED** [review]
❓ I was wondering how this situation could happen. If we have the distribution in the queued distribution CF, why wouldn't we have the first one in the retriable distribution CF? Then I saw this code:

```java
    if (routingInfo.isPartitionScaling(partition)) {
      // If the partition is currently being scaled up, we don't want to distribute the command yet.
      return;
    }
```

Why is this? It seems a lot easier if we have it in the retriable CF already. If the retry fails a couple times because the partition is scaling, that's not much of a problem imo. The mechanism is especially build for situations where a partition is temporarily unreachable.

So I checked the `CommandRedistributor`, as I figured we could also add a check here to retry distribution to a scaling partition. And I found it already exists 😅 

```java
          // If the partition is currently being scaled up, we won't yet try distributing to it.
          if (routingInfo.isPartitionScaling(record.getPartitionId())) {
            LOG.debug(
                "Excluding distribution {} for partition {} as it is currently scaling up.",
                distributionKey,
                record.getPartitionId());
            return false;
          }
```

Which makes we wonder, do we need this change you made here at all? Can't we just remove this first check so it's always in the retriable distribution CF, even though the partition is scaling?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java (hunk 3 above)
Comment (entangled90) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java]: Good point, didn't realize when refactoring

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java (hunk 4 above)
Comment (entangled90) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/scaling/MarkPartitionBootstrappedProcessor.java]: Only one partition at a time should be marked as bootstrapped at a time, we currently validate that this is the case.
We support scaling to multiple partitions at the same time, but they still need to bootstrap/join sequentially one after the other

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/distribution/CommandDistributionBehavior.java (hunk 2 above)
Comment (entangled90) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/distribution/CommandDistributionBehavior.java]: That's something I didn't know it was a possibility actually :thinking:

Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/distribution/CommandDistributionBehavior.java]: It's not used so I don't blame you. But it's something we've talked about previously. Basically ensuring a blocking distribution doesn't block an entire queue, but to keep it isolated to the smallest possible scope. It's not an easy thing to do though 😄

**Comment by entangled90** [comment]
As each partition is started sequentially in case of scaling up to multiple partitions it may take a while for a partition to be online. For that reason we though that it may just introduce noise or may simply take more time than expected to distribute these commands.

From the [docs](https://github.com/camunda/camunda/blob/main/docs/zeebe/generalized_distribution.md):
> If we don't receive a response after the first retry, we don't want to keep spamming distributions. Because of this we introduced a backoff mechanism. After every retry we will double the redistribution interval. This means that the first retry is done after max. 10 seconds. The second will be 20 seconds after this, the third 40 seconds after that and so on. This goes on until we've reached a maximum interval of 5 minutes.

I was wondering if we could instead "reset" the retry cycle once we scaled up or trigger a retry cycle to avoid waiting too much.

**Comment by remcowesterhoud** [comment]
@entangled90 

What you refer to in the docs is a backoff mechanism for a distribution. The thing is, the check you're doing in the redistributor happens before we do this backoff. So when the partition is online it will take at most 10 seconds for the distribution to be retried. I'd write that off as acceptable for the first delivery. Later on we could consider optimizing this. Maybe we can extend the schedule service to trigger a retry cycle manually or w/e.

The impact this has on the distribution to the other partitions is negligible. It's only an extra entry in RocksDB we iterate over.

**Comment by remcowesterhoud** [comment]
@entangled90 I did notice that the check in the redistributor returns false. That breaks out of the redistribution loop. You'll want to return true here.

**Comment by entangled90** [comment]
Yeah I noticed that as well when reviewing it, I updated that when you were reviewing probably

**Comment by entangled90** [comment]
I agree to keep things as simple as possible to start redistribution immediately. 
Probably, it will be helpful in general for redistribution to somehow "trigger" a redistribution for a partition in case we know (from an external "source") that the partition has recovered (or has bootstrapped).
So it makes sense to implement it for a more generic use case as well

**Comment by panagiotisgts** [comment]
@remcowesterhoud @entangled90 If for some reason the scaling up of the partition takes more time than expected (fex snapshot transfer is flaky and requires more time) wouldn't adding it immediately to the retriable distributions cause it's distribution to be greatly delayed? 

Not sure if that's a valid scenario just thinking out aloud. That was the reason I initially skipped distribution for scaling partitions to begin with, along with unnecessary requests done to brokers and error noise.

**Comment by remcowesterhoud** [comment]
> @remcowesterhoud @entangled90 If for some reason the scaling up of the partition takes more time than expected (fex snapshot transfer is flaky and requires more time) wouldn't adding it immediately to the retriable distributions cause it's distribution to be greatly delayed? 
> 
> 
> 
> Not sure if that's a valid scenario just thinking out aloud. That was the reason I initially skipped distribution for scaling partitions to begin with, along with unnecessary requests done to brokers and error noise. 

@panagiotisgts  Why would the distribution be delayed? The backoff is not applied yet at the time of the check. So it at most takes 10 seconds as far as I can see.

**Comment by panagiotisgts** [comment]
@remcowesterhoud Assuming the check `routingInfo.isPartitionScaling(partition)` is removed, based on your initial comment if i understand this correctly. You would start distributing immediately to _yet not active_ partitions thus resulting in the backoff delay increasing.

**Comment by remcowesterhoud** [comment]
@panagiotisgts Ah there's a misunderstanding. I'm proposing to remove this check here: https://github.com/camunda/camunda/blob/f22bb46243ae093d7a9140bc25541757368686e2/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/distribution/CommandDistributionBehavior.java#L201-L204

We should leave the one in the redistributor.

**Comment by entangled90** [comment]
Implemented what you suggested and also added a flag to avoid sending commands to the partition while it's scaling.

**Review by remcowesterhoud — APPROVED** [review]
Thanks! This looks better to me 🙂
