### PR TITLE
Reset error phase only after processing current record is completed

### LINKED ISSUE #16429: Missing resourceKey property when deleting a resource causes an endless error loop
**Describe the bug**

See the following report: https://console.cloud.google.com/errors/detail/CI7Z3fDnpK-ZOw;service=zeebe;time=P7D?project=camunda-saas-prod

**Expected behavior**

Validation is performed on the command preemptively such that no exception is thrown.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 io.camunda.zeebe.msgpack.MsgpackPropertyException: Property 'resourceKey' is invalid: Expected a value or default value to be specified, but has nothing
at io.camunda.zeebe.msgpack.property.BaseProperty.resolveValue ( io/camunda.zeebe.msgpack.property/BaseProperty.java:65 )
at io.camunda.zeebe.msgpack.property.BaseProperty.getEncodedLength ( io/camunda.zeebe.msgpack.property/BaseProperty.java:71 )
at io.camunda.zeebe.msgpack.value.ObjectValue.getEncodedLength ( io/camunda.zeebe.msgpack.value/ObjectValue.java:203 )
at io.camunda.zeebe.msgpack.value.ObjectValue.getEncodedLength ( io/camunda.zeebe.msgpack.value/ObjectValue.java:141 )
at io.camunda.zeebe.protocol.impl.record.UnifiedRecordValue.getEncodedLength ( io/camunda.zeebe.protocol.impl.record/UnifiedRecordValue.java:36 )
at io.camunda.zeebe.msgpack.UnpackedObject.getLength ( io/camunda.zeebe.msgpack/UnpackedObject.java:57 )
at io.camunda.zeebe.protocol.impl.record.UnifiedRecordValue.getLength ( io/camunda.zeebe.protocol.impl.record/UnifiedRecordValue.java:30 )
at io.camunda.zeebe.stream.impl.records.RecordBatchEntry.createEntry ( io/camunda.zeebe.stream.impl.records/RecordBatchEntry.java:35 )
at io.camunda.zeebe.stream.impl.records.RecordBatch.appendRecord ( io/camunda.zeebe.stream.impl.records/RecordBatch.java:46 )
at io.camunda.zeebe.stream.impl.BufferedProcessingResultBuilder.appendRecordReturnEither ( io/camunda.zeebe.stream.impl/BufferedProcessingResultBuilder.java:59 )
at io.camunda.zeebe.stream.api.ProcessingResultBuilder.appendRecord ( io/camunda.zeebe.stream.api/ProcessingResultBuilder.java:33 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryRejectingIfUserCommand ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:523 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.onError ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:442 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:309 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:232 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:208 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:94 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:47 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:122 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 ) 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.4.3

**Affected Versions:**
- Zeebe Version: 8.4.3
- Zeebe Version: 8.1.24
- Zeebe Version: 8.2.23
- Zeebe Version: 8.3.7

**Workaround:**
- restart affected broker

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

The root cause for issue #16429 
Error phase was reset everytime `readNextRecord` was called. As a result, it was reset even before the error was handled. So at some point, the `onErrorRetries` is 0, while `errorHandlingPhase` is something other than `NO_ERROR`. As a result, the next command that encounters an exception, skips the error handling in the engine and would be directly handled by the error handling in `ProcessingStateMachine`. 

This is fixed by ensuring that the error phase is always reset after the processing of current record is completed.

It was not possible to reproduce this with a unit test. So an integration test is added.

The second issue that `ProcessingStateMachine` could not prevent endless error loop is not yet fixed. This is less critical, as it is not a regression. It will be fixed in a follow up PR.

## Related issues

closes #16429 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/MultipleInvalidResourceDeletionTest.java [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+import io.camunda.zeebe.qa.util.cluster.TestStandaloneBroker;
+import io.camunda.zeebe.qa.util.junit.ZeebeIntegration;
+import io.camunda.zeebe.qa.util.junit.ZeebeIntegration.TestZeebe;
+import io.camunda.zeebe.test.util.junit.AutoCloseResources.AutoCloseResource;
+import io.camunda.zeebe.test.util.junit.RegressionTest;
+import io.grpc.Status.Code;
+import org.junit.jupiter.api.BeforeEach;
+
+@ZeebeIntegration
+public class MultipleInvalidResourceDeletionTest {
```
Comment (Zelldon) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/MultipleInvalidResourceDeletionTest.java:25]: ❌ I think it is good that we have such regression test, but still I would like to have a more scoped unit tests/stream platform test, since we know now what the actual bug was.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 2]
```diff
@@ -200,18 +200,21 @@ public ProcessingStateMachine(
 
   private void skipRecord() {
     notifySkippedListener(currentRecord);
-    inProcessing = false;
+    markProcessingCompleted();
     actor.submit(this::readNextRecord);
     metrics.eventSkipped();
   }
 
   void readNextRecord() {
```
Comment (Zelldon) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:208]: 🔧 Can we remove the method then?

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 3]
```diff
@@ -200,18 +200,21 @@ public ProcessingStateMachine(
...
+    tryToReadNextRecord();
+  }
+
+  void markProcessingCompleted() {
```
Comment (Zelldon) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:212]: ❓ Just to clarify:

The issue was that on each read next, which could happen in between the error loop, we might have reset the errorHandlingPhase. Wasn't this the case before then already? I'm wondering why this was an issue now.

Comment (Zelldon) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:212]: 💭 Do we still need the count?! Can it be removed?

**Review by ChrisKujawa — DISMISSED** [review]
Thanks @deepthidevaki I reviewed this https://github.com/camunda/zeebe/pull/16290 as well since I feel I miss the full picture. Please also bare with me if I miss something. 

I have some comments also related to https://github.com/camunda/zeebe/pull/16290

  * Why was this phase made volatile [here](https://github.com/camunda/zeebe/blob/486e2a0e6c9fb004cfa3773c326107af993c5eff/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L162)
  * I think it is a good step [to introduce the enums](https://github.com/camunda/zeebe/blob/486e2a0e6c9fb004cfa3773c326107af993c5eff/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L754-L769), but might be even better to leverage some more of the OOP and create behavior classes for each error handling. So you could better couple the code to the actual states like these [here](https://github.com/camunda/zeebe/blob/486e2a0e6c9fb004cfa3773c326107af993c5eff/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L439-L452) Wdyt? 
  * I think would be great if we could update the state machine visualization to reflect our changes and how it works now. [Here](https://github.com/camunda/zeebe/blob/486e2a0e6c9fb004cfa3773c326107af993c5eff/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L60-L94)
  * Related to tests I was missing a bit that we actually sent the rejection back to the client
  * Furthermore the last bug was related to not correctly serialize the rejection/error record, but I see no regression test for such. Or do I miss this one? See related [issue ](https://github.com/camunda/zeebe/issues/16107)


In general, I think or feel we should add some more tests here (to better cover the new error lifecycle handling).

Sorry if some of these things sound a bit nitpicky, but I think it is crucial to be here rigorous (better safe than sorry) and clearer what happens as this is our core business logic.

Happy to discuss these things also f2f, I can also take some of these parts over if you need me to.

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/MultipleInvalidResourceDeletionTest.java (hunk 1 above)
Comment (deepthidevaki) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/MultipleInvalidResourceDeletionTest.java:25]: It is explained in the PR description:
> It was not possible to reproduce this with a unit test. So an integration test is added.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 3 above)
Comment (deepthidevaki) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:212]: >  Wasn't this the case before then already? 

Yes. This was already the case before. But it was not used for anything critical. It was more of an observability/debugging info.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 4]
```diff
@@ -200,18 +200,21 @@ public ProcessingStateMachine(
 
   private void skipRecord() {
     notifySkippedListener(currentRecord);
-    inProcessing = false;
+    markProcessingCompleted();
```
Comment (berkaycanbc) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:203]: ❓ @Zelldon why do we need to call this here? inProcessing should never be equal to `true` when we enter the `skipRecord()` method, right? I am asking you because it was already there also for the previous implementation.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 2 above)
Comment (berkaycanbc) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:208]: I think, that makes sense now. I will remove this.

**Review by berkaycanbc — APPROVED** [review]
Thanks @deepthidevaki! 🚀 These changes should fix the error we encountered.

@Zelldon do you think you suggestions has to be addressed in this PR? Otherwise, we can merge this one and back-port it to affected versions.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 4 above)
Comment (Zelldon) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:203]: SkipRecord is called from different places.

**Comment by Zelldon** [comment]
Yes @deepthidevaki please go ahead. I will take a look at potential test cases, where I can think of something :)

**Review by ChrisKujawa — APPROVED** [review]

**Comment by Zelldon** [comment]
I just thought about the current regression test again, doesn't the test relies currently on the fact that the processing fails when the resource key is wrong? 🤔 When we fix this this test is a bit useless or?

**Comment by Zelldon** [comment]
I'm not sure whether I can follow.

Normally the engine should sent an rejection when invalid arguments are given or a different state is expected right? But right now it is just exploding when a key was not referencing a none existing resource right?

**Comment by deepthidevaki** [comment]
> Normally the engine should sent an rejection when invalid arguments are given or a different state is expected right? 

Yes. This is done in the error handling in the engine `RecordProcessor#onProcessingError`. But what happens is the due to this bug, we 
> skips the error handling in the engine and would be directly handled by the error handling in `ProcessingStateMachine`.

**Comment by Zelldon** [comment]
Interesting. We now use the exceptional error handling case for expected errors? 🤯 I found the code you referring to https://github.com/camunda/zeebe/blob/main/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/resource/ResourceDeletionDeleteProcessor.java#L168


I'm wondering about this approach tbh this feels suboptimal (but nothing we need to discuss this here. I will reach out to the ZPA team.)

Normally we did handling of such like this https://github.com/camunda/zeebe/blob/main/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceCancelProcessor.java#L72-L79 directly writing the rejection without throwing an exception going into the onError and then handling the error (feels like we use goto's 😅 )
