### PR TITLE
fix: insert UsageMetricsTUEntity might already exist

### LINKED ISSUE #40985: Reassignment of task fails in TU metrics insert in V1 Tasklist
### 

### 

, 

### 

### 

### Description

When re-assiging a task to the same user via V1 Tasklist API in 8.8, the TU usage metrics insertion fails the API call.

### Steps to reproduce

Using Tasklist V1 API, do the following:
1. Assign a task to user1
2. Assign the task to user2 or just unassign
3. Assign the task back to user1

### Current behavior

API call fails

### Expected behavior

API call succeeds

### Workaround

No workaround is known if you want to assign to the previous user again.

### Environment

SaaS & SM

### Version

- Component Version: 8.8.x

### Rootcause

Metrics insert to ES expects a CREATED response. Remote debug shows it's an OK response. The UsageMetricsTUEntity instance is the exact same when re-assigned.

### Solution ideas

Check for 200 response codes, not only CREATED in https://github.com/camunda/camunda/blob/main/tasklist/els-schema/src/main/java/io/camunda/tasklist/store/elasticsearch/TaskMetricsStoreElasticSearch.java#L126

### Dev -> QA handover

_No response_

### Links

- Support: https://jira.camunda.com/browse/SUPPORT-30096

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by konstantinos-mylosis**
### Context
Tasklist, v1, Job based implementation

### Scenario
1. assignTask (assignee: demo)
2. unassignTask / assignTask to another user
3. assignTask (assignee: demo)

### Problem
This sequence causes the `insert UsageMetricsTUEntity` operation to return false, because the entry already exists with the same key. As a result, it triggers a `TasklistRuntimeException`.

### Fix
This scenario should be considered valid.
The insert operation should return true when the entity already exists, avoiding any exceptions. When receiving an updated result from ES/OS, we should not throw an exception in such cases.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #40985

### CODE REVIEW

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/api/rest/v1/controllers/TaskControllerIT.java [hunk 1]
```diff
@@ -1031,6 +1031,83 @@ public void unassignZeebeUserTask() {
               });
     }
 
+    @Test
+    public void assignUnassignAssignZeebeUserTask() {
```
Comment (danielkelemen) [inline tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/api/rest/v1/controllers/TaskControllerIT.java:1035]: ❓ Is this running it with ES/OS? It would be important to validate that both of them work fine.

Comment (konstantinos-mylosis) [reply tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/api/rest/v1/controllers/TaskControllerIT.java:1035]: Yeap, run on both: 

- [Integration / Tests (elasticsearch)](https://github.com/camunda/camunda/actions/runs/19424114239/job/55567542258?pr=41044#logs)
- [Integration / Tests (opensearch)](https://github.com/camunda/camunda/actions/runs/19424114239/job/55567542261?pr=41044#logs)

**Review by danielkelemen — APPROVED** [review]
Looks good! 👍
