### PR TITLE
fix: Element instance IDs do not get updated after user task migration

### LINKED ISSUE #47609: Element instance IDs do not get updated after user task migration from embedded form
### 

### 

### 

### 

### Description

After migrating a process instance with job worker user task with embedded form to a Camunda user task, element instance ids do not get updated in the operate list-view index, leading to the element instance not showing active tokens anymore.

### Steps to reproduce

1. Deploy process and start instance with job worker user task with embedded form
2. Migrate the process instance to a process with any Camunda user task type that has a different element instance ID

### Current behavior

The element instance Ids of all elements are not updated correctly for the target process.

### Expected behavior

All element instances in the target process have the correct id (of the target process).

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- Component Version: 8.9

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

Bug was found during peer-review where a video is included (Scenario 2): https://github.com/camunda/camunda/issues/46487#issuecomment-3991612069

### PR DESCRIPTION
**Pull request by kristinkomschow**
## Description

Fixes updated flownode entities getting overwritten by the canceled job record of a camunda user task migration.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes https://github.com/camunda/camunda/issues/47609

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/ListViewFlowNodeFromJobHandlerTest.java [hunk 1]
```diff
@@ -78,6 +78,25 @@ public void shouldNotHandlesRecord() {
...
+    final Record<JobRecordValue> jobRecord =
+        factory.generateRecord(
+            r ->
+                r.withValueType(ValueType.JOB)
+                    .withValue(
+                        ImmutableJobRecordValue.builder()
+                            .withProcessDefinitionKey(1L)
+                            .withElementInstanceKey(111L)
+                            .withProcessInstanceKey(222L)
+                            .withJobToUserTaskMigration(true)
```
Comment (konstantinos-mylosis) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/ListViewFlowNodeFromJobHandlerTest.java:93]: Is it possible to jump in a case where we have a process instance matching the :

❓What happens with the following scenario? Is it handled by `shouldHandlesRecord` test case since `isJobToUserTaskMigrationProp` is defaulted to `false`?

```
                         .withElementInstanceKey(111L)
                         .withProcessInstanceKey(222L)
                         .withJobToUserTaskMigration(false)
```

**Review by konstantinos-mylosis — APPROVED** [review]
LGTM Pre-approving
Please check my question before merging

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/ListViewFlowNodeFromJobHandlerTest.java (hunk 1 above)
Comment (kristinkomschow) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/ListViewFlowNodeFromJobHandlerTest.java:93]: Yes, `false` is the default value so it's implicitly covered by `shouldHandlesRecord`.
