### PR TITLE
Filter for membertype on child query

### LINKED ISSUE #31960: Member types for roles are not filtered correctly in the gateway
### 

### 

### 

### 

### Description

We have a single filter for the member type in the `RoleFilterTransformer`, where we expect the document we are querying to contain the member type. This is wrong depending on the request we make.

1. When we want to query all the members for a role we try to retrieve the membership documents. In this case the current filter works, as the queried documents contain the member type.
2. When we want to query all the roles of a member, we try to receive the role documents. In this case the filter doesn't work as it expects the member type to be on the role document. That's invalid, as the member type resides on the membership documents.

### Steps to reproduce

Query all roles of a member.

### Current behavior

You will receive an empty response, regardless of what is in ES.

### Expected behavior

Querying for all role of a member should yield results if they are stored in ES.

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

The current filter transformer does this:

```java
        filter.memberType() == null
            ? null
            : term(RoleIndex.MEMBER_TYPE, filter.memberType().name()),
```

As explained in the description that's not valid for all cases, as the member type is sometimes part of the child documents. We need to be able to make this distinction.

### Solution ideas

Ideally we refactor this so we have a clear separation in filters between querying for roles and role members. Due to time constraints we are going for a pragmatic approach:

```java
        filter.childMemberType() == null
             ? null
             : hasChildQuery(
                 IdentityJoinRelationshipType.MEMBER.getType(),
                 term(RoleIndex.MEMBER_TYPE, filter.childMemberType().name())),
```

We introduce a `childMemberType` on the `RoleFilter`. If this is set we expect the member type on the child of the document we are querying for.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

The member type is stored on the document of the child, not of the role itself.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #31960
Related to https://camunda.slack.com/archives/C06UYJMMETZ/p1747044361499869

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@ThorbenLindhauer Would you mind reviewing this as you already have the context?

File: search/search-domain/src/main/java/io/camunda/search/filter/RoleFilter.java [hunk 1]
```diff
@@ -20,10 +20,20 @@ public record RoleFilter(
...
+    return new Builder()
+        .roleKey(roleKey)
+        .roleId(roleId)
+        .name(name)
+        .description(description)
+        .memberIds(memberIds)
+        .memberType(memberType)
+        .roleIds(roleIds)
+        .childMemberType(childMemberType)
+        .tenantId(tenantId);
```
Comment (ana-vinogradova-camunda) [inline search/search-domain/src/main/java/io/camunda/search/filter/RoleFilter.java:36]: ❓ Am I right to say that we are keeping both `childMemberType` and `memberType` to accommodate both queries from parent and child perspective?

**Review by ana-vinogradova-camunda — APPROVED** [review]
From the best of my knowledge changes look good.
Thank you @remcowesterhoud for the detailed commit message - it helps big time 👍

File: search/search-domain/src/main/java/io/camunda/search/filter/RoleFilter.java (hunk 1 above)
Comment (remcowesterhoud) [reply search/search-domain/src/main/java/io/camunda/search/filter/RoleFilter.java:36]: Yes that's exactly right. We need both so we can still differentiate between querying for roles by member, and querying for members by role.
