### PR TITLE
Terminate elements iteratively instead of recursively during PI modification

### LINKED ISSUE #20307: StackOverflowError during process instance modification
**Describe the bug**

Due to a recursive call in this processor there's a chance we run into a `StackOverflowError`. It happens when there's a terminate instruction for an element with a lot of nested child elements (think a chain of call activities).
As impact, one partition dies when this happens.

A workaround for now would be to increase the stack size and rebooting the brokers, but it's not ideal.

**To Reproduce**

1. Create a process with a call activity that calls itself and let it run for a while. I used beneath process. This doesn't get caught by the `StraightThroughProcessingLoopValidator` (yet) and let it create 10k instances.
2. In the root process, try to move the token from the call activity to the user task
3. Watch the SO cause the partition to crash and burn :fire:

image

**Expected behavior**

All the element instances should get terminated without problem. We should try to replace the recursion with a regular iteration.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2024-07-10 10:02:41.402 [Broker-2] [zb-actors-0] [StreamProcessor-2] ERROR
      io.camunda.zeebe.util.actor - Shutting down because we can't recover from JVM errors. Consider restarting this broker if it is a temporary issue.
java.lang.StackOverflowError: null
	at io.camunda.zeebe.msgpack.spec.MsgPackWriter.writeString(MsgPackWriter.java:143) ~[zeebe-msgpack-core-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.spec.MsgPackWriter.writeString(MsgPackWriter.java:139) ~[zeebe-msgpack-core-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.StringValue.write(StringValue.java:86) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.EnumValue.write(EnumValue.java:54) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.property.BaseProperty.write(BaseProperty.java:91) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:166) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:92) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.property.BaseProperty.write(BaseProperty.java:91) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:166) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:92) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.property.BaseProperty.write(BaseProperty.java:91) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:166) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:92) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.UnpackedObject.write(UnpackedObject.java:63) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.copyElementInstance(DbElementInstanceState.java:404) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.getInstance(DbElementInstanceState.java:296) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.lambda$getChildren$2(DbElementInstanceState.java:310) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$whileEqualPrefix$10(TransactionalColumnFamily.java:202) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.visit(TransactionalColumnFamily.java:475) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$forEachInPrefix$20(TransactionalColumnFamily.java:407) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ColumnFamilyContext.withPrefixKey(ColumnFamilyContext.java:112) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEachInPrefix(TransactionalColumnFamily.java:391) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEachInPrefix(TransactionalColumnFamily.java:361) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$whileEqualPrefix$11(TransactionalColumnFamily.java:199) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:344) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:343) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileEqualPrefix(TransactionalColumnFamily.java:197) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.getChildren(DbElementInstanceState.java:306) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:701) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:708) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:703) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:708) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:703) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:708) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
...
```

</p>
</details>

**Environment:**
- Zeebe Version: All that support PI modification

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

We've seen a few times now that a PI modification resulted in a `StackOverflowError`. This has quite an impact on the broker where it occurs. We should avoid recursive logic in our processors so we don't run the risk of running into a SO.

This PR removes the recursive logic and replaces it with an iterative method. The second commit of this PR does the fix itself. I've committed it like this so it's easier to review the differences. In the 3rd commit I've refactored it a bit.

Note:
I had a test for this, but it ran so slow I decided no to commit it. It actually ran so slow that the test started failing due to timeouts instead of running into SO with the old solution.

<details><summary>test</summary>

```
  @Test // Regression for https://github.com/camunda/camunda/issues/20307
  public void shouldTerminateElementWithoutRunningInStackOverflow() {
    // given
    final var processAmount = 2000;
    ENGINE
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(PROCESS_ID)
                .startEvent()
                .scriptTask(
                    "script", c -> c.zeebeExpression("count + 1").zeebeResultVariable("count"))
                .exclusiveGateway()
                .defaultFlow()
                .endEvent()
                .moveToLastExclusiveGateway()
                .sequenceFlowId("callActivityLoopFlow")
                .condition("= count < %d".formatted(processAmount))
                .callActivity("callActivity", c -> c.zeebeProcessId(PROCESS_ID))
                .userTask("waitTask")
                .endEvent()
                .done())
        .deploy();

    final var processInstanceKey =
        ENGINE
            .processInstance()
            .ofBpmnProcessId(PROCESS_ID)
            .withVariables(Map.of("count", 1))
            .create();

    RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
        .withElementId("waitTask")
        .limit(1)
        .await();

    // when
    ENGINE
        .processInstance()
        .withInstanceKey(processInstanceKey)
        .modification()
        .terminateElement(processInstanceKey)
        .modify();

    // then
    assertThatElementIsTerminated(processInstanceKey, PROCESS_ID);
    Assertions.assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_TERMINATED)
                .withProcessInstanceKey(processInstanceKey)
                .withElementType(BpmnElementType.PROCESS)
                .getFirst()
                .getKey())
        .isEqualTo(processInstanceKey);
  }
```

</details>

## Related issues

closes #20307

### CODE REVIEW

**Review by ana-vinogradova-camunda — APPROVED** [review]
LGTM 🚀

**Comment by remcowesterhoud** [comment]
@ana-vinogradova-camunda I forgot to fix some tests. Would you mind reviewing the last commit?

**Review by ana-vinogradova-camunda — APPROVED** [review]

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 1]
```diff
@@ -676,36 +677,50 @@ public void executeVariableInstruction(
...
+          elementInstancesToTerminate.add(calledActivityElementInstance);
+        }
       }
+
+      elementsTerminating.push(currentElement);
     }
 
-    stateWriter.appendFollowUpEvent(
-        elementInstanceKey, ProcessInstanceIntent.ELEMENT_TERMINATED, elementInstanceRecord);
+    while (!elementsTerminating.isEmpty()) {
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:735]: ❓ I'm curious why was the choice to wait till the end to append all `ELEMENT_TERMINATED` events rather than one by one?

**Review by mustafadagher — APPROVED** [review]
LGTM! 🚀  I only have one question below

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java (hunk 1 above)
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:735]: It's about the order of the events. Before would recursion it would be:

1. Parent `TERMINATING`
2. Child `TERMINATING`
3. Child `TERMINATED`
4. Parent `TERMINATED`

If I wouldn't append all terminated events what would happen now is:

1. Parent `TERMINATING`
2. Parent `TERMINATED`
3. Child `TERMINATING`
4. Child `TERMINATED`

This is an issue, because handling the `TERMINATED` event for the child requires the parent instance to be available in the state. That would no longer be the case since we deleted it from the state with the parent `TERMINATED` event. To resolve this I collected all the element instances that require a `TERMINATED` event to be written in a stack and worked from the smallest child back to the root element instance.
