### PR TITLE
Unflake TimerStartEventTest.shouldTriggerOnlyTwice

### LINKED ISSUE #10169: Flaky test TimerStartEventTest.shouldTriggerOnlyTwice
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? it failed once [here](https://github.com/camunda/zeebe/runs/7991555657?check_suite_focus=true) while attempting to merge https://github.com/camunda/zeebe/pull/10153
- Does it block your work? It blocked a merge and may block future ones
- Do we suspect that it is a real failure? No, this seems like a timing issue. The test only has a window of a few seconds. When it's slow (e.g. on CI), it could be unstable.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  Failures: 
Error:    TimerStartEventTest.shouldTriggerOnlyTwice:1107 
Expecting actual:
  [2251799813685249L, 2251799813685252L, 2251799813685249L, 2251799813685252L]
to contain exactly (and in same order):
  [2251799813685249L,
    2251799813685252L,
    2251799813685249L,
    2251799813685252L,
    2251799813685252L]
but could not find the following elements:
  [2251799813685252L]
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

The test is based on seconds. If the test takes longer than those few seconds it could break.

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

The following logs are from a local reproduction, as the CI didn't show the actual logs.

I was able to reproduce it locally by pinning the Engine clock's time at the start of test and then running the test repeatedly until failure.
```java
engine.getClock().pinCurrentTime();
// ... rest of the test
```

<details><summary>Logs from local reproduction</summary>
<pre>
--------
	[Timestamp] [Partition] ['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
14:32:02 C DPLY      CREATE            - #001->  -1   -1 - 
14:32:02 E PROC      CREATED           - #002->#001 K001 - process.xml -> "process_1" (version:1)
14:32:02 E TIME      CREATED           - #003->#001 K003 -  @"start_1"[  -1]  in <process "K001"[?]> due T14:32:12.462 reps
14:32:02 E DPLY      CREATED           - #004->#001 K002 - process.xml
14:32:02 E DPLY      FULLY_DISTRIBUTED - #005->#001 K002 - 
14:32:02 C DPLY      CREATE            - #006->  -1   -1 - 
14:32:02 E PROC      CREATED           - #007->#006 K004 - process.xml -> "process_2" (version:1)
14:32:02 E TIME      CREATED           - #008->#006 K006 -  @"start_2"[  -1]  in <process "K004"[?]> due T14:32:12.463 reps
14:32:02 E DPLY      CREATED           - #009->#006 K005 - process.xml
14:32:02 E DPLY      FULLY_DISTRIBUTED - #010->#006 K005 - 
14:32:17 C TIME      TRIGGER           - #011->  -1 K003 -  @"start_1"[  -1]  in <process "K001"[?]> due T14:32:12.462 reps
14:32:17 C TIME      TRIGGER           - #012->  -1 K006 -  @"start_2"[  -1]  in <process "K004"[?]> due T14:32:12.463 reps
14:32:17 E TIME      TRIGGERED         - #013->#011 K003 -  @"start_1"[  -1]  in <process "K001"[K007]> due T14:32:12.462 reps
14:32:17 E PROC_EVNT TRIGGERING        - #014->#011 K008 -  @"start_1"[K001] in <process K001[K007]> (no vars)
14:32:17 C PI        ACTIVATE          - #015->#011 K007 - PROCESS "process_1" in <process "process_1"[K007]>
14:32:17 E TIME      CREATED           - #016->#011 K009 -  @"start_1"[  -1]  in <process "K001"[K007]> due T14:32:22.46
14:32:17 E TIME      TRIGGERED         - #017->#012 K006 -  @"start_2"[  -1]  in <process "K004"[K010]> due T14:32:12.463 reps
14:32:17 E PROC_EVNT TRIGGERING        - #018->#012 K011 -  @"start_2"[K004] in <process K004[K010]> (no vars)
14:32:17 C PI        ACTIVATE          - #019->#012 K010 - PROCESS "process_2" in <process "process_2"[K010]>
14:32:17 E TIME      CREATED           - #020->#012 K012 -  @"start_2"[  -1]  in <process "K004"[K010]> due T14:32:22.462 reps
14:32:17 E PI        ACTIVATING        - #021->#015 K007 - PROCESS "process_1" in <process "process_1"[K007]>
14:32:17 E PI        ACTIVATED         - #022->#015 K007 - PROCESS "process_1" in <process "process_1"[K007]>
14:32:17 E PROC_EVNT TRIGGERED         - #023->#015 K008 -  @"start_1"[K001] in <process K001[K007]> (no vars)
14:32:17 E PI        ACTIVATING        - #024->#015 K013 - START_EVENT "start_1" in <process "process_1"[K007]>
14:32:17 E PI        ACTIVATED         - #025->#015 K013 - START_EVENT "start_1" in <process "process_1"[K007]>
14:32:17 C PI        COMPLETE          - #026->#015 K013 - START_EVENT "start_1" in <process "process_1"[K007]>
14:32:22 E PI        ACTIVATING        - #027->#019 K010 - PROCESS "process_2" in <process "process_2"[K010]>
14:32:22 E PI        ACTIVATED         - #028->#019 K010 - PROCESS "process_2" in <process "process_2"[K010]>
14:32:22 E PROC_EVNT TRIGGERED         - #029->#019 K011 -  @"start_2"[K004] in <process K004[K010]> (no vars)
14:32:22 E PI        ACTIVATING        - #030->#019 K014 - START_EVENT "start_2" in <process "process_2"[K010]>
14:32:22 E PI        ACTIVATED         - #031->#019 K014 - START_EVENT "start_2" in <process "process_2"[K010]>
14:32:22 C PI        COMPLETE          - #032->#019 K014 - START_EVENT "start_2" in <process "process_2"[K010]>
14:32:22 E PI        COMPLETING        - #033->#026 K013 - START_EVENT "start_1" in <process "process_1"[K007]>
14:32:22 E PI        COMPLETED         - #034->#026 K013 - START_EVENT "start_1" in <process "process_1"[K007]>
14:32:22 E PI        SEQ_FLOW_TAKEN    - #035->#026 K015 - SEQUENCE_FLOW "sequenc..030bc05" in <process "process_1"[K007]>
14:32:22 C PI        ACTIVATE          - #036->#026 K016 - END_EVENT "end_1" in <process "process_1"[K007]>
14:32:22 E PI        COMPLETING        - #037->#032 K014 - START_EVENT "start_2" in <process "process_2"[K010]>
14:32:22 E PI        COMPLETED         - #038->#032 K014 - START_EVENT "start_2" in <process "process_2"[K010]>
14:32:22 E PI        SEQ_FLOW_TAKEN    - #039->#032 K017 - SEQUENCE_FLOW "sequenc..c40f048" in <process "process_2"[K010]>
14:32:22 C PI        ACTIVATE          - #040->#032 K018 - END_EVENT "end_2" in <process "process_2"[K010]>
14:32:22 E PI        ACTIVATING        - #041->#036 K016 - END_EVENT "end_1" in <process "process_1"[K007]>
14:32:22 E PI        ACTIVATED         - #042->#036 K016 - END_EVENT "end_1" in <process "process_1"[K007]>
14:32:22 E PI        COMPLETING        - #043->#036 K016 - END_EVENT "end_1" in <process "process_1"[K007]>
14:32:22 E PI        COMPLETED         - #044->#036 K016 - END_EVENT "end_1" in <process "process_1"[K007]>
14:32:22 C PI        COMPLETE          - #045->#036 K007 - PROCESS "process_1" in <process "process_1"[K007]>
14:32:22 C TIME      TRIGGER           - #046->  -1 K009 -  @"start_1"[  -1]  in <process "K001"[K007]> due T14:32:22.46
14:32:22 C TIME      TRIGGER           - #047->  -1 K012 -  @"start_2"[  -1]  in <process "K004"[K010]> due T14:32:22.462 reps
14:32:22 C TIME      TRIGGER           - #048->  -1 K009 -  @"start_1"[  -1]  in <process "K001"[K007]> due T14:32:22.46
14:32:22 C TIME      TRIGGER           - #049->  -1 K012 -  @"start_2"[  -1]  in <process "K004"[K010]> due T14:32:22.462 reps
14:32:22 E PI        ACTIVATING        - #050->#040 K018 - END_EVENT "end_2" in <process "process_2"[K010]>
14:32:22 E PI        ACTIVATED         - #051->#040 K018 - END_EVENT "end_2" in <process "process_2"[K010]>
14:32:22 E PI        COMPLETING        - #052->#040 K018 - END_EVENT "end_2" in <process "process_2"[K010]>
14:32:22 E PI        COMPLETED         - #053->#040 K018 - END_EVENT "end_2" in <process "process_2"[K010]>
14:32:22 C PI        COMPLETE          - #054->#040 K010 - PROCESS "process_2" in <process "process_2"[K010]>
14:32:22 C TIME      TRIGGER           - #055->  -1 K009 -  @"start_1"[  -1]  in <process "K001"[K007]> due T14:32:22.46
14:32:22 C TIME      TRIGGER           - #056->  -1 K012 -  @"start_2"[  -1]  in <process "K004"[K010]> due T14:32:22.462 reps
14:32:22 E PI        COMPLETING        - #057->#045 K007 - PROCESS "process_1" in <process "process_1"[K007]>
14:32:22 E PI        COMPLETED         - #058->#045 K007 - PROCESS "process_1" in <process "process_1"[K007]>
14:32:22 E TIME      TRIGGERED         - #059->#046 K009 -  @"start_1"[  -1]  in <process "K001"[K019]> due T14:32:22.46
14:32:22 E PROC_EVNT TRIGGERING        - #060->#046 K020 -  @"start_1"[K001] in <process K001[K019]> (no vars)
14:32:22 C PI        ACTIVATE          - #061->#046 K019 - PROCESS "process_1" in <process "process_1"[K019]>
14:32:22 E TIME      TRIGGERED         - #062->#047 K012 -  @"start_2"[  -1]  in <process "K004"[K021]> due T14:32:22.462 reps
14:32:22 E PROC_EVNT TRIGGERING        - #063->#047 K022 -  @"start_2"[K004] in <process K004[K021]> (no vars)
14:32:22 C PI        ACTIVATE          - #064->#047 K021 - PROCESS "process_2" in <process "process_2"[K021]>
14:32:22 E TIME      CREATED           - #065->#047 K023 -  @"start_2"[  -1]  in <process "K004"[K021]> due T14:32:32.46
14:32:32 R TIME      TRIGGER           - #066->#048 K009 -  @"start_1"[  -1]  in <process "K001"[K007]> due T14:32:22.46 !NOT_FOUND (Expected to trigger timer with key '2251799813685257', but no such timer was found)
14:32:32 R TIME      TRIGGER           - #067->#049 K012 -  @"start_2"[  -1]  in <process "K004"[K010]> due T14:32:22.462 reps !NOT_FOUND (Expected to trigger timer with key '2251799813685260', but no such timer was found)
14:32:32 E PI        COMPLETING        - #068->#054 K010 - PROCESS "process_2" in <process "process_2"[K010]>
14:32:32 E PI        COMPLETED         - #069->#054 K010 - PROCESS "process_2" in <process "process_2"[K010]>
14:32:32 R TIME      TRIGGER           - #070->#055 K009 -  @"start_1"[  -1]  in <process "K001"[K007]> due T14:32:22.46 !NOT_FOUND (Expected to trigger timer with key '2251799813685257', but no such timer was found)
14:32:32 R TIME      TRIGGER           - #071->#056 K012 -  @"start_2"[  -1]  in <process "K004"[K010]> due T14:32:22.462 reps !NOT_FOUND (Expected to trigger timer with key '2251799813685260', but no such timer was found)
14:32:32 E PI        ACTIVATING        - #072->#061 K019 - PROCESS "process_1" in <process "process_1"[K019]>
14:32:32 E PI        ACTIVATED         - #073->#061 K019 - PROCESS "process_1" in <process "process_1"[K019]>
14:32:32 E PROC_EVNT TRIGGERED         - #074->#061 K020 -  @"start_1"[K001] in <process K001[K019]> (no vars)
14:32:32 E PI        ACTIVATING        - #075->#061 K024 - START_EVENT "start_1" in <process "process_1"[K019]>
14:32:32 E PI        ACTIVATED         - #076->#061 K024 - START_EVENT "start_1" in <process "process_1"[K019]>
14:32:32 C PI        COMPLETE          - #077->#061 K024 - START_EVENT "start_1" in <process "process_1"[K019]>
14:32:32 E PI        ACTIVATING        - #078->#064 K021 - PROCESS "process_2" in <process "process_2"[K021]>
14:32:32 E PI        ACTIVATED         - #079->#064 K021 - PROCESS "process_2" in <process "process_2"[K021]>
14:32:32 E PROC_EVNT TRIGGERED         - #080->#064 K022 -  @"start_2"[K004] in <process K004[K021]> (no vars)
14:32:32 E PI        ACTIVATING        - #081->#064 K025 - START_EVENT "start_2" in <process "process_2"[K021]>
14:32:32 E PI        ACTIVATED         - #082->#064 K025 - START_EVENT "start_2" in <process "process_2"[K021]>
14:32:32 C PI        COMPLETE          - #083->#064 K025 - START_EVENT "start_2" in <process "process_2"[K021]>
14:32:32 E PI        COMPLETING        - #084->#077 K024 - START_EVENT "start_1" in <process "process_1"[K019]>
14:32:32 E PI        COMPLETED         - #085->#077 K024 - START_EVENT "start_1" in <process "process_1"[K019]>
14:32:32 E PI        SEQ_FLOW_TAKEN    - #086->#077 K026 - SEQUENCE_FLOW "sequenc..030bc05" in <process "process_1"[K019]>
14:32:32 C PI        ACTIVATE          - #087->#077 K027 - END_EVENT "end_1" in <process "process_1"[K019]>
14:32:32 E PI        COMPLETING        - #088->#083 K025 - START_EVENT "start_2" in <process "process_2"[K021]>
14:32:32 E PI        COMPLETED         - #089->#083 K025 - START_EVENT "start_2" in <process "process_2"[K021]>
14:32:32 E PI        SEQ_FLOW_TAKEN    - #090->#083 K028 - SEQUENCE_FLOW "sequenc..c40f048" in <process "process_2"[K021]>
14:32:32 C PI        ACTIVATE          - #091->#083 K029 - END_EVENT "end_2" in <process "process_2"[K021]>
14:32:32 E PI        ACTIVATING        - #092->#087 K027 - END_EVENT "end_1" in <process "process_1"[K019]>
14:32:32 E PI        ACTIVATED         - #093->#087 K027 - END_EVENT "end_1" in <process "process_1"[K019]>
14:32:32 E PI        COMPLETING        - #094->#087 K027 - END_EVENT "end_1" in <process "process_1"[K019]>
14:32:32 E PI        COMPLETED         - #095->#087 K027 - END_EVENT "end_1" in <process "process_1"[K019]>
14:32:32 C PI        COMPLETE          - #096->#087 K019 - PROCESS "process_1" in <process "process_1"[K019]>
14:32:32 E PI        ACTIVATING        - #097->#091 K029 - END_EVENT "end_2" in <process "process_2"[K021]>
14:32:32 E PI        ACTIVATED         - #098->#091 K029 - END_EVENT "end_2" in <process "process_2"[K021]>
14:32:32 E PI        COMPLETING        - #099->#091 K029 - END_EVENT "end_2" in <process "process_2"[K021]>
14:32:32 E PI        COMPLETED         - #100->#091 K029 - END_EVENT "end_2" in <process "process_2"[K021]>
14:32:32 C PI        COMPLETE          - #101->#091 K021 - PROCESS "process_2" in <process "process_2"[K021]>
14:32:32 E PI        COMPLETING        - #102->#096 K019 - PROCESS "process_1" in <process "process_1"[K019]>
14:32:32 E PI        COMPLETED         - #103->#096 K019 - PROCESS "process_1" in <process "process_1"[K019]>
14:32:32 E PI        COMPLETING        - #104->#101 K021 - PROCESS "process_2" in <process "process_2"[K021]>
14:32:32 E PI        COMPLETED         - #105->#101 K021 - PROCESS "process_2" in <process "process_2"[K021]>

-------------- Deployed Processes ----------------------
process.xml -> "process_1" (version:1)[K001] ------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="definitions_f6f49a32-859b-4747-aec7-43afe2db6879" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process_1" isExecutable="true">
    <startEvent id="start_1" name="start_1">
      <outgoing>sequenceFlow_770fab2d-9719-44ae-b876-c237c030bc05</outgoing>
      <timerEventDefinition id="timerEventDefinition_98dee063-f18a-4cd6-a0a8-2d47ed6741d6">
        <timeCycle id="timeCycle_9e542a25-27e6-4b34-9371-6ca94057862c">R2/2022-08-24T14:32:12.460+02:00[Europe/Berlin]/PT10S</timeCycle>
      </timerEventDefinition>
    </startEvent>
    <endEvent id="end_1" name="end_1">
      <incoming>sequenceFlow_770fab2d-9719-44ae-b876-c237c030bc05</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_770fab2d-9719-44ae-b876-c237c030bc05" sourceRef="start_1" targetRef="end_1"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_a27320fb-42ab-45d6-9d52-e4ad2a6b15fe">
    <bpmndi:BPMNPlane bpmnElement="process_1" id="BPMNPlane_6d93b3aa-6bcd-47f9-b505-3efdd7b9fbdc">
      <bpmndi:BPMNShape bpmnElement="start_1" id="BPMNShape_2494aa78-7348-48f4-b620-4de36cdef259">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="end_1" id="BPMNShape_a00f0699-5202-4195-9749-5e841653a033">
        <dc:Bounds height="36.0" width="36.0" x="186.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_770fab2d-9719-44ae-b876-c237c030bc05" id="BPMNEdge_785eefc9-b0f4-4042-b417-774dc32909d6">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>

process.xml -> "process_2" (version:1)[K004] ------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="definitions_d937b567-e14d-4778-a5c9-7e092d87d7ea" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process_2" isExecutable="true">
    <startEvent id="start_2" name="start_2">
      <outgoing>sequenceFlow_bb8b06e2-2aea-4b24-a6fe-9eeddc40f048</outgoing>
      <timerEventDefinition id="timerEventDefinition_5df1a4e6-e587-4947-8bbf-740c5379f960">
        <timeCycle id="timeCycle_76231eb7-eca3-4746-a7f4-2c5c7248fe05">R3/2022-08-24T14:32:12.460+02:00[Europe/Berlin]/PT10S</timeCycle>
      </timerEventDefinition>
    </startEvent>
    <endEvent id="end_2" name="end_2">
      <incoming>sequenceFlow_bb8b06e2-2aea-4b24-a6fe-9eeddc40f048</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_bb8b06e2-2aea-4b24-a6fe-9eeddc40f048" sourceRef="start_2" targetRef="end_2"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_ba6b5931-6423-4f75-a9a1-4aa19c81deab">
    <bpmndi:BPMNPlane bpmnElement="process_2" id="BPMNPlane_1e8deaaa-3a1d-4ee3-ac75-2a92713dce26">
      <bpmndi:BPMNShape bpmnElement="start_2" id="BPMNShape_1e1d98f4-da85-4c62-846c-87ff9b20931c">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="end_2" id="BPMNShape_034ad89f-5c4c-4587-9ec9-4cb56171554c">
        <dc:Bounds height="36.0" width="36.0" x="186.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_bb8b06e2-2aea-4b24-a6fe-9eeddc40f048" id="BPMNEdge_616f4cd5-6e9e-4860-b6f0-874bc8b9ed51">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>

--------------- Decomposed keys (for debugging) -----------------
  -1 <-> -1
K001 <-> 2251799813685249
K002 <-> 2251799813685250
K003 <-> 2251799813685251
K004 <-> 2251799813685252
K005 <-> 2251799813685253
K006 <-> 2251799813685254
K007 <-> 2251799813685255
K008 <-> 2251799813685256
K009 <-> 2251799813685257
K010 <-> 2251799813685258
K011 <-> 2251799813685259
K012 <-> 2251799813685260
K013 <-> 2251799813685261
K014 <-> 2251799813685262
K015 <-> 2251799813685263
K016 <-> 2251799813685264
K017 <-> 2251799813685265
K018 <-> 2251799813685266
K019 <-> 2251799813685267
K020 <-> 2251799813685268
K021 <-> 2251799813685269
K022 <-> 2251799813685270
K023 <-> 2251799813685271
K024 <-> 2251799813685272
K025 <-> 2251799813685273
K026 <-> 2251799813685274
K027 <-> 2251799813685275
K028 <-> 2251799813685276
K029 <-> 2251799813685277

14:32:07.690 [] DEBUG io.camunda.zeebe.broker.logstreams - Close stream processor
...

java.lang.AssertionError: 
Expecting actual:
  [2251799813685249L, 2251799813685252L, 2251799813685249L, 2251799813685252L]
to contain exactly (and in same order):
  [2251799813685249L,
    2251799813685252L,
    2251799813685249L,
    2251799813685252L,
    2251799813685252L]
but could not find the following elements:
  [2251799813685252L]
</pre>
</details>

### PR DESCRIPTION
**Pull request by korthout**
## Description

This test became flaky after a [change in the task scheduler](https://github.com/camunda/zeebe/pull/10112). Since then, tasks that have been scheduled are only executed when the engine is in the PROCESSING phase, but isn't currently processing a command. If that is the case, then it is rescheduled. That means that sometimes things take longer, especially when the processor is busy.

In this specific test case, new process instances are created using 2 timer start events on different processes. Each time they trigger, they produce a bunch of records because they start new process instances. The processing of the relevant commands for these instances can interfere with the DueDateTimerChecker which is a scheduled task. Because of the new task scheduler change, it can happen that the DueDateTimerChecker is postponed.

The problem is solved by periodically checking that the assertion holds, and increasing the clock's time every time we check this. This makes sure that the DueDateTimerChecker's task can be executed, even when it's rescheduled.

## Related issues

closes #10169 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java [hunk 1]
```diff
@@ -1105,21 +1105,26 @@ public void shouldTriggerOnlyTwice() {
...
+              assertThat(RecordingExporter.timerRecords(TimerIntent.TRIGGERED).limit(5))
+                  .describedAs("Expect that start_1 triggered twice and start_2 triggered thrice")
+                  .extracting(record -> record.getValue().getProcessDefinitionKey())
+                  .containsExactly(
+                      firstDeploymentProcessDefinitionKey,
+                      secondDeploymentProcessDefinitionKey,
+                      firstDeploymentProcessDefinitionKey,
+                      secondDeploymentProcessDefinitionKey,
+                      secondDeploymentProcessDefinitionKey);
+            });
```
Comment (remcowesterhoud) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java:1130]: ❓ In the commit you mention
> So, if it only triggered 4 times at the
moment we check it, then we have to wait 5 seconds until we can increase
the time.

Isn't this the case for the previous solution as well? The only downside in the old solution is that it would fail the test after waiting the 5 seconds, here it will try it a second time before Awaitility gives a timeout (10s).

**Review by remcowesterhoud — COMMENTED** [review]
The code looks fine but I'm not sure I fully understand what the problem was here @korthout.

❓ You've added this `Awaitility.await()` to check if 5 timers have been triggered. I can see why we would expect 5 timers to trigger. But why do we need this wait here and not before the assertion that timers have triggered 4 times. Or with the assertion where they are triggered 2 times. What makes the 5th one special?

**Comment by korthout** [comment]
> But why do we need this wait here and not before the assertion that timers have triggered 4 times. Or with the assertion where they are triggered 2 times. What makes the 5th one special?

That's a very good question. I guess that the engine is not yet too busy with completing the existing process instances and somehow still allows the DueDateTimerChecker to run without being postponed. But you raise an interesting concern. 🔧 I guess we should use the same logic for the second assertion.

Note that it's unnecessary on the first assertion because the engine is not busy doing other things at that time, and should always be able to trigger the timers.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java (hunk 1 above)
Comment (korthout) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java:1130]: >The only downside in the old solution is that it would fail the test after waiting the 5 seconds, here it will try it a second time before Awaitility gives a timeout (10s).

No, the downside of the old solution was that it depends on a technical concept (that the engine must be idle in other for the DueDateTimerChecker to check for expired timers). The solution provided in 6bee15abe3760811d6722890f1b6aeb2b069a004 didn't have that problem but came with the downside of being slow (taking 5 seconds or so). That's why a later commit was used to improve the performance of the test.

**Review by remcowesterhoud — APPROVED** [review]
Thanks for your explanation. That we don't need to check it on the first assertion makes sense. Please add it to the second assertion as well and it's good to go.

**Comment by korthout** [comment]
bors merge
