### PR TITLE
fix(broker): environmentalise sed -i in benchmarks

### LINKED ISSUE #4508: Running newBenchmark.sh fails with sed error on macOS
**Describe the bug**
Running `benchmark/setup/newBenchmark.sh my-branch-name` on macOS (10.15.4) results in the following error produced by the sed command in the last line of this shell script:

```
sed: 1: "Makefile": invalid command code M
```

**To Reproduce**
On macOS do:
```
cd benchmark/setup
./newBenchmark.sh somebranchname
```

**Expected behavior**
Expect to run without problems.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
↳ ./newBenchmark.sh 4333-bpmn-lifecycle
+ '[' -z 4333-bpmn-lifecycle ']'
+ namespace=4333-bpmn-lifecycle
+ kubectl create namespace 4333-bpmn-lifecycle
namespace/4333-bpmn-lifecycle created
+ kubens 4333-bpmn-lifecycle
Context "gke_zeebe-io_europe-west1-b_zeebe-cluster" modified.
Active namespace is "4333-bpmn-lifecycle".
+ cp -rv default/ 4333-bpmn-lifecycle
default/ -> 4333-bpmn-lifecycle
default//curator-configmap.yaml -> 4333-bpmn-lifecycle/curator-configmap.yaml
default//starter.yaml -> 4333-bpmn-lifecycle/starter.yaml
default//Makefile -> 4333-bpmn-lifecycle/Makefile
default//worker.yaml -> 4333-bpmn-lifecycle/worker.yaml
default//timer.yaml -> 4333-bpmn-lifecycle/timer.yaml
default//simpleStarter.yaml -> 4333-bpmn-lifecycle/simpleStarter.yaml
default//curator-cronjob.yaml -> 4333-bpmn-lifecycle/curator-cronjob.yaml
default//zeebe-values.yaml -> 4333-bpmn-lifecycle/zeebe-values.yaml
+ cd 4333-bpmn-lifecycle
+ sed -i s/default/4333-bpmn-lifecycle/g Makefile starter.yaml timer.yaml simpleStarter.yaml worker.yaml
sed: 1: "Makefile": invalid command code M
```

</p>
</details>

**Environment:**
 - OS: macOS 10.15.4
 - Zeebe Version: 4333-bpmn-lifecycle
 - Configuration: clean build (`mvn clean install -DskipTests -T1C`)

### PR DESCRIPTION
**Pull request by jwulf**
## Description

sed -i needs a different syntax on Mac OS. 

This patch detects the OS and uses the appropriate syntax.

Closes #4508

### CODE REVIEW

File: benchmarks/setup/newBenchmark.sh [hunk 1]
```diff
@@ -1,4 +1,27 @@
...
+    # Detect the OS name
+    case "$(uname -s)" in
+      Darwin)
+        host_os=darwin
+        ;;
+      Linux)
+        host_os=linux
+        ;;
+      *)
+        echo "Unsupported host OS. Must be Linux or Mac OS X." >&2
```
Comment (korthout) [inline benchmarks/setup/newBenchmark.sh:15]: I'm not sure about this. We have co-worker(s) working on Windows as well AFAIK. 

@pihme does the current sed implementation of this newBenchmark script work on your machine?

**Review by korthout — CHANGES_REQUESTED** [review]
Great addition, I really appreciate this one, but I'd like to check that we are now not breaking this script for Windows users.

**Comment by korthout** [comment]
Also please add `Closes #4508` to the description of this PR.

File: benchmarks/setup/newBenchmark.sh (hunk 1 above)
Comment (pihme) [reply benchmarks/setup/newBenchmark.sh:15]: It does work. I have to use WSL (Windows Subsystem for Linux) anyway, and it registers properly as Linux i that mode.

Comment (korthout) [reply benchmarks/setup/newBenchmark.sh:15]: @pihme ok, so the change here would also still work on WSL?

Comment (pihme) [reply benchmarks/setup/newBenchmark.sh:15]: Yes, I tested it.

Comment (korthout) [reply benchmarks/setup/newBenchmark.sh:15]: Thanks

**Review by korthout — APPROVED** [review]
Okay, LGTM! 🎉
