### PR TITLE
fix: variable filter in migration and modification batch operations

### LINKED ISSUE #42721: Variable filter is ignored for batch operations (migration, modification)
### 

### 

### 

### 

### Description

When filtering for process instances, filtering for variable values and starting a process instance migration, the variable filter is ignored.

### Steps to reproduce

**Process instance migration**

1. Go to process instances list in Operate UI
2. Use the variable filter to narrow down the filtered process instances
3. Click "select all" checkbox above the instances list
4. Click migrate
5. Map all required elements and start the migration
6. Observe the operations panel

**Batch modification**

1. Go to process instances list in Operate UI
2. Use the variable filter to narrow down the filtered process instances
3. Click "select all" checkbox above the instances list
4. Click modify
5. Select a target element
6. Observe the operations panel

### Current behavior

The variable filter is ignored and only the remaining search filters are respected, which potentially causes more instances to be part of the batch operation (migration or modification)

### Expected behavior

The variable filter is respected and only instances related to the filter set are included in the batch operation (migration or modification)

### Workaround

If possible: Select process instances from the list instead of using "select all"

### Environment

SaaS & SM

### Version

- Component Version: 8.8, 8.9

### Rootcause

The variable filter parameter is not included in the instance migration API request.

### Solution ideas

- Add variable filter parameter to instance migration API request
- Ensure all filter parameters are present in all batch operation types (migration, modification, cancellation, incident resolution).
- Validate functionality with a test

### Dev -> QA handover

This issue affects the filter panel and batch operations based on a selection in the instances list view.

Notable areas to test:

- Batch modification (move button)
- Batch migration (migrate button)
- Batch cancellation (cancel button)
- Batch incident resolution (retry button)

Only filtered elements in the instances list should be part of the specific batch operations. Especially single and multiple variable filters need to be part of the batch operation request. Also selecting all, including and excluding process instances should work as exptected.

### Links

Support case: https://jira.camunda.com/browse/SUPPORT-30675

### Automated Test Impact

_No response_

Test case link 
[User can applied variable filter correctly during Batch Operations](https://camunda.testrail.com/index.php?/cases/view/2145378)

### PR DESCRIPTION
**Pull request by pedesen**
## Description

Consolidate batch operation mutation request body for
- modification
- cancellation
- incident resolution

Add variable filter parameter to mutation request body for
- migration

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #42721

### CODE REVIEW

File: operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+import {buildMutationRequestBody} from 'App/Processes/ListView/v2/InstancesTable/Toolbar/buildMutationRequestBody';
+
+/**
+ * A hook that builds the request body for process instance batch operations,
+ * taking into account:
+ * - current search parameters from the URL
+ * - selected and excluded IDs from the processInstancesSelectionStore
+ * - variable filters from variableFilterStore.
+ */
+const useBatchOperationMutationRequestBody = () => {
```
Comment (pedesen) [inline operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts:21]: This is now used by modification, cancellation and incident resolution batch operation requests to increase consistency.

File: operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+  const includeIds =
+    selectedProcessInstanceIds.length > 0
+      ? checkedRunningProcessInstanceIds
+      : [];
+
+  return buildMutationRequestBody({
+    searchParams,
+    includeIds,
+    excludeIds: excludedProcessInstanceIds,
+    variableFilter: variable,
```
[the remark this answers is not in the document]
Comment (pedesen) [reply operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts:40]: This should not be needed, because processDefinitionId and processDefinitionVersion are included in the searchParams, which in combination resolve to a specific processDefintionKey

File: operate/client/src/App/Processes/MigrationView/Footer/index.tsx [hunk 3]
```diff
@@ -148,16 +146,28 @@ const Footer: React.FC = observer(() => {
...
-                    processDefinitionKey: sourceProcessDefinitionKey,
+                    variableFilter:
+                      variable !== undefined
+                        ? {
+                            name: variable.name,
+                            values: variable.values.join(','),
+                          }
+                        : undefined,
+                    processDefinitionKey:
+                      sourceProcessDefinitionKey ?? undefined,
```
Comment (pedesen) [inline operate/client/src/App/Processes/MigrationView/Footer/index.tsx:166]: Unfortunately I was not able to reuse `useBatchOperationMutationRequestBody` here, because the migration view is quite different compared to the other batch operation types:

- `includeIds` and `excludeIds` are taken from `batchOperationQuery` instead of `processInstancesSelectionStore`
- `variable` is also taken from `batchOperationQuery` instead of `processInstancesSelectionStore`

That's why I'm calling `buildMutationRequestBody` directly.

File: operate/client/src/App/Processes/MigrationView/Footer/buildMigrationBatchOperationFilter.ts [hunk 4]
```diff
@@ -1,56 +0,0 @@
...
-type MigrationFilterOptions = {
-  baseFilter:
-    | GetProcessDefinitionStatisticsRequestBody['filter']
-    | CreateMigrationBatchOperationRequestBody['filter'];
-  includeIds: string[];
-  excludeIds: string[];
-  processDefinitionKey?: string | null;
-};
-
-const buildMigrationBatchOperationFilter = ({
```
Comment (pedesen) [inline operate/client/src/App/Processes/MigrationView/Footer/buildMigrationBatchOperationFilter.ts:24]: This was only used in `MigrationView/Footer/index.tsx` and was duplicated logic:

- The key criterion is already build as part of `buildMutationRequestBody`
- `processDefinitionKey` is now passed directly to `buildMutationRequestBody`

**Comment by pedesen** [comment]
There is still a problem with the process instance statistics (instances count badges in the diagram). The variable filter is also not included in this request. I will fix this in a follow-up PR.

**Comment by pedesen** [comment]
We currently don't have any E2E test coverage for checking if all filters are included in the batch operation requests. I'm considering adding this to the [Orchestration Cluster E2E Test Suite](https://github.com/camunda/camunda/tree/main/qa/c8-orchestration-cluster-e2e-test-suite#readme).

File: operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+    excludedProcessInstanceIds,
+    checkedRunningProcessInstanceIds,
+  } = processInstancesSelectionStore;
+
+  const includeIds =
+    selectedProcessInstanceIds.length > 0
+      ? checkedRunningProcessInstanceIds
+      : [];
+
+  return buildMutationRequestBody({
```
Comment (christoph-fricke) [inline operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts:36]: 🔧 Are the arguments somewhat stable? I know that the `searchParams` reference is stable as long as they don't change. If so, I would consider using `useMemo`.

File: operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.test.tsx [hunk 6]
```diff
@@ -0,0 +1,347 @@
...
+ * except in compliance with the Camunda License 1.0.
+ */
+
+import {renderHook} from '@testing-library/react';
+import {MemoryRouter, Route, Routes} from 'react-router-dom';
+import {useBatchOperationMutationRequestBody} from './useBatchOperationMutationRequestBody';
+import {variableFilterStore} from 'modules/stores/variableFilter';
+import {processInstancesSelectionStore} from 'modules/stores/processInstancesSelection';
+
+const getWrapper = (initialSearchParams?: {[key: string]: string}) => {
```
Comment (christoph-fricke) [inline operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.test.tsx]: 🔧
```suggestion
const getWrapper = (initialSearchParams?: Record<string, string>) => {
```

File: operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+ * except in compliance with the Camunda License 1.0.
+ */
+
+import {useSearchParams} from 'react-router-dom';
+import {variableFilterStore} from 'modules/stores/variableFilter';
+import {processInstancesSelectionStore} from 'modules/stores/processInstancesSelection';
+import {buildMutationRequestBody} from 'modules/utils/buildMutationRequestBody';
+
+/**
+ * A hook that builds the request body for process instance batch operations,
```
Comment (christoph-fricke) [inline operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts:15]: 💭 The downside of using a hook here is that the filter are already calculated on render - right now even on every render. While already created, they are actually only needed once the user triggers an action. I don't think they really **need** to be a hook. A function that takes `searchParams` as an argument and accesses the MobX stores adhoc should also work and avoids upfront computation.

**Review by christoph-fricke — APPROVED** [review]

File: operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts (hunk 5 above)
Comment (christoph-fricke) [reply operate/client/src/modules/hooks/useBatchOperationMutationRequestBody.ts:36]: I will skip it for now, since it might not need to be a hook anyway: https://github.com/camunda/camunda/pull/42856#discussion_r2630239379

File: operate/client/src/App/Processes/ListView/v2/InstancesTable/Toolbar/index.tsx
Comment (christoph-fricke) [inline operate/client/src/App/Processes/ListView/v2/InstancesTable/Toolbar/index.tsx:1]: ❓ With the v1 <=> v2 stuff, it looks like this toolbar is never used? Both Instances tables appear to use the v1 toolbar. Is this intentional? Why does it seem to work when this changes aren't even used?! Is it really working?

Comment (christoph-fricke) [reply operate/client/src/App/Processes/ListView/v2/InstancesTable/Toolbar/index.tsx:1]: While this `Toolbar` is not used, the v1 `Toolbar` seems to apply the variables correctly - mass canceling instances only cancel the amount filtered by the variable.

The v1 toolbar includes its own `buildMutationRequestBody` function (the one moved from the v2 toolbar in this PR) and seeds the `baseFilter` from `getProcessInstancesRequestFilters`, which extracts the variable filter from `variableFilterStore` inside.

The v2 `buildMutationRequestBody` uses `parseProcessInstancesSearchFilter` for its base filter, and while the variable is [part of the search Params schema](https://github.com/camunda/camunda/blob/operate-42721-bo-variable-filter/operate/client/src/modules/utils/filter/v2/processInstancesSearch.ts#L43) for its parsing, the variable never ends up in the URL (intentionally).
