### PR TITLE
fix: correct zeebe incident events metric name

### LINKED ISSUE #34342: Regression in metric `zeebe_incident_events_total`
### 

### 

, , , 

### 

### 

### Description

With migrating the metrics to micrometer in https://github.com/camunda/camunda/pull/28082, a regression was introduced to the `zeebe_incident_events_total` metric. The metric was accidentally renamed to `zeebe_incidents_events_total` (with an additional s in incidents). 

This was ported to some other versions as well, resulting in releases `8.5.15`, `8.6.10`, and `8.7.0` having regressed.

The [documentation](https://docs.camunda.io/docs/next/self-managed/operational-guides/monitoring/metrics/#process-processing-metrics) is stating `zeebe_incident_events_total` for all versions.

This only impacts users that directly access this metric. Our grafana dashboards do not visualize this specific metric.

### Steps to reproduce

1. deploy a process and create an instance that results in an incident
2. check prometheus for the zeebe_* metrics
3. notice that the metric is named `zeebe_incidents_events_total` rather than `zeebe_incident_events_total`

### Current behavior

The metric is named differently since `8.5.15`, `8.6.10`, and `8.7.0`. This was unintentional and does not align with the documentation.

### Expected behavior

The metric must be renamed back to its original name in patches for 8.5, 8.6, 8.7, and on main for 8.8 development.

### Environment

SM

### Version

- Component Version: `8.5.15`, `8.6.10`, and `8.7.0`

### Rootcause

The regression was accidentally introduced with the migration of metrics to micrometer in https://github.com/camunda/camunda/pull/28082

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

- Related support case: https://jira.camunda.com/browse/SUPPORT-27804

### PR DESCRIPTION
**Pull request by fabiopaini-camunda**
## Description

Change metric name from "zeebe.incidents.events.total" to "zeebe.incident.events.total" (zeebe_incidents_events_total to zeebe_incident_events_total on Prometheus) to restore the original name and align with documentation.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #34342

### CODE REVIEW

**Review by korthout — CHANGES_REQUESTED** [review]
Nice work @fabiopaini-camunda! 🚀 

👍 The change itself is good!

❌ We need to add some test to ensure we don't regress this again. 

💡 I recommend adding a case to `io.camunda.zeebe.engine.metrics.ProcessEngineMetricsTest`. To create an incident in a test we can take inspiration from other test. For example, we can use `io.camunda.zeebe.engine.processing.incident.BusinessRuleTaskIncidentTest#shouldCreateIncidentIfDecisionNotDeployed()` which is very similar in setup to the other `ProcessEngineMetricsTest` tests - it uses a process with a business rule task, but just doesn't deploy a DMN resource. When the business rule task activates, there is no decision that can be called, so an incident is raised. We can use that to check that the metric with the correct name has been incremented. I also recommend rebasing your fix commit on top of a test commit, to show that the test fails without the fix.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/metrics/IncidentMetricsTest.java [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+    final long processInstanceKey = engine.processInstance().ofBpmnProcessId(PROCESS_ID).create();
+
+    // then - wait for incident to be created and verify metrics
+    RecordingExporter.incidentRecords(IncidentIntent.CREATED)
+        .withProcessInstanceKey(processInstanceKey)
+        .await();
+    assertIncidentMetrics(
+        1.0, // created
+        1.0, // pending
+        0.0); // resolved
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/metrics/IncidentMetricsTest.java]: 🔧 Given the need for the comments, it's likely better to inline this assertIncidentMetrics method. [Dare to violate DRY](https://mtlynch.io/good-developers-bad-tests/#dare-to-violate-dry) in tests.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/metrics/IncidentMetricsTest.java [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+        .withProcessInstanceKey(processInstanceKey)
+        .await();
+
+    // when - cancel the process instance, resolving the incident
+    engine.processInstance().withInstanceKey(processInstanceKey).cancel();
+
+    // then - wait for process to be canceled and verify metrics
+    RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_TERMINATED)
+        .withProcessInstanceKey(processInstanceKey)
+        .await();
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/metrics/IncidentMetricsTest.java]: 🔧 This awaits the first `ELEMENT_TERMINATED` within the process instance, but it does not specify that this has to concern the termination of the process instance itself. The first `ELEMENT_TERMINATED` will be the termination of the call activity instance. It does not lead to problems in this test because the metric is already updated at the call activity instance, but the comment is not correct.

I suggest changing it to the following (note that you'll also need to import the `BpmnElementType` enum):
```suggestion
    // then - wait for process to be canceled and verify metrics
    RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_TERMINATED)
        .withProcessInstanceKey(processInstanceKey)
        .withElementType(BpmnElementType.PROCESS)
        .await();
```

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/metrics/IncidentMetricsTest.java [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+        .isNotNull()
+        .isEqualTo(expectedCreated);
+    assertThat(pendingIncidentsMetric())
+        .describedAs("Pending incidents metric")
+        .isNotNull()
+        .isEqualTo(expectedPending);
+    assertThat(resolvedIncidentsMetric())
+        .describedAs("Resolved incidents metric")
+        .isNotNull()
+        .isEqualTo(expectedResolved);
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/metrics/IncidentMetricsTest.java]: 🔧 There's no need for an explicit `isNotNull` check because the `isEqualTo` already verifies this implicitly.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/metrics/IncidentMetricsTest.java [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+  }
+
+  private Double resolvedIncidentsMetric() {
+    return engine
+        .getMeterRegistry()
+        .get("zeebe.incident.events.total")
+        .tag("action", "resolved")
+        .counter()
+        .count();
+  }
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/metrics/IncidentMetricsTest.java:107]: 👍 Great helper methods

**Review by korthout — APPROVED** [review]
Well done @fabiopaini-camunda 👏 

👍 I really like how you wrote the tests: 
- given,when,then with explanation
- minimal processes
- useful helper methods to retrieve the current metric values

🔧 I have a few suggestions you can consider to apply before merging. Whether you apply them or not is your own decision, and applying them does not require another review round. Feel free to merge at your own leisure.

LGTM 👍

**Comment by mustafadagher** [comment]
@fabiopaini-camunda I see that `spotless` is failing here, if you run `./mvnw spotless:apply` on the project directory, they'll be possibly auto fixed. And you can push these style fixed to pass CI.

**Comment by fabiopaini-camunda** [comment]
> @fabiopaini-camunda I see that `spotless` is failing here, if you run `./mvnw spotless:apply` on the project directory, they'll be possibly auto fixed. And you can push these style fixed to pass CI.

I forgot to run it with the last commit, thank you @mustafadagher !

**Comment by korthout** [comment]
@fabiopaini-camunda Are you aware of the remaining open backport PRs? 🙇

**Comment by fabiopaini-camunda** [comment]
@korthout Yes, the 8.7 one seems to be failing due to flaky tests, the 8.5 is a little bit harder since tests are initializing the meter registry differently than in later versions
