### PR TITLE
test(engine): fix concurrency issue with subscription handler

### LINKED ISSUE #3639: shouldCorrelateMessageOnDifferentPartitions test is unstable
**Description**

io.zeebe.engine.processor.workflow.message.MessageCorrelationMultiplePartitionsTest.shouldCorrelateMessageOnDifferentPartitions is unstable.

```
Error
No event found matching the criteria
```

### PR DESCRIPTION
**Pull request by saig0**
## Description

* multiple subscription handlers used the same log stream writer for writing on the same partition
* avoid concurrent access by delegating the command to the subscription handler of the receiver partition instead of the sender partition
* use a single thread pool to avoid concurrent access to the same subscription handler

## Related issues

closes #3639 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: engine/src/test/java/io/zeebe/engine/util/EngineRule.java [hunk 1]
```diff
@@ -155,6 +159,13 @@ private void startProcessors() {
                           (key, partition) -> {},
                           jobsAvailableCallback)
                       .withListener(new ProcessingExporterTransistor()));
+
+          // sequenialize the commands to avoid concurrency
+          final var subscriptionHandlerExecutor = Executors.newSingleThreadExecutor();
```
Comment (Zelldon) [inline engine/src/test/java/io/zeebe/engine/util/EngineRule.java]: Here you create now an executor for each handler? What if we create one for all? So outside of the loop?

Comment (saig0) [reply engine/src/test/java/io/zeebe/engine/util/EngineRule.java]: It would be possible too. The handlers may block each other a bit. But I guess that it is not a big difference in your test setup.

Comment (saig0) [reply engine/src/test/java/io/zeebe/engine/util/EngineRule.java]: @Zelldon, I applied your suggestion and use only one thread pool for all subscription handler.

**Review by ChrisKujawa — APPROVED** [review]
👍
