### PR TITLE
Ensure lastProcessesPosition is set when StreamProcessor is paused

### LINKED ISSUE #16550: Flaky shouldRecoverAfterOutOfDiskSpaceAfterExporting: io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTes
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
org.awaitility.core.ConditionTimeoutException: 
Condition with alias 'until the disk is not full anymore' didn't complete within 3 minutes because assertion condition with alias until the disk is not full anymore 
Expecting code not to raise a throwable but caught
  "io.camunda.zeebe.client.api.command.ClientStatusException: Cannot accept requests for partition 1. Broker is out of disk space
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:116)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:54)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT.publishMessage(DiskSpaceRecoveryIT.java:84)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.NotThrownAssert.isThrownBy(NotThrownAssert.java:43)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest.lambda$shouldRecoverAfterOutOfDiskSpaceAfterExporting$1(DiskSpaceRecoveryIT.java:132)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52)
	... 11 more
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
".
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest.shouldRecoverAfterOutOfDiskSpaceAfterExporting(DiskSpaceRecoveryIT.java:131)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.AssertionError: 
Expecting code not to raise a throwable but caught
  "io.camunda.zeebe.client.api.command.ClientStatusException: Cannot accept requests for partition 1. Broker is out of disk space
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:116)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:54)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT.publishMessage(DiskSpaceRecoveryIT.java:84)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.NotThrownAssert.isThrownBy(NotThrownAssert.java:43)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest.lambda$shouldRecoverAfterOutOfDiskSpaceAfterExporting$1(DiskSpaceRecoveryIT.java:132)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52)
	... 11 more
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
"
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest.lambda$shouldRecoverAfterOutOfDiskSpaceAfterExporting$1(DiskSpaceRecoveryIT.java:132)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

https://github.com/camunda/zeebe/actions/runs/8024770580
[Test results for [IT] QA Integration Tests.zip](https://github.com/camunda/zeebe/files/14401732/Test.results.for.IT.QA.Integration.Tests.zip)

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

1. `lastProcessedPosition` was UNSET when replay is paused. This prevents a new snapshot to be taken when the StreamProcessor is paused. Taking a new snapshot is required if the broker is currently OOD. This PR fixes this by ensuring the lastProcessedPosition is read from replay state machine.
2. The test was flaky because when StreamProcessor is paused at start, the `lastProcessedPosition` is not set when there is no snapshot. Thus it cannot take a snapshot and recover from OOD. We decided that we would not handle this case where the broker goes out of disk where the partitions has not taken any snapshot. This is unlikely to happen in production because resources are allocated properly. So to fix the flaky test, we now ensure that a snapshot exists before going OOD. 

## Related issues

closes #16550 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by deepthidevaki** [comment]
Test was run locally over 100 times without any failure.

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/health/DiskSpaceRecoveryIT.java [hunk 1]
```diff
@@ -112,10 +112,14 @@ void shouldRecoverAfterOutOfDiskSpaceAfterExporting()
...
-                      .hasRootCauseMessage(
-                          "RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space"));
+              () -> {
+                // Ensure at least one snapshot with a compactable processed position before going
+                // out of disk space
+                partitionsClient.takeSnapshot();
+                assertThatThrownBy(DiskSpaceRecoveryIT.this::publishMessage)
+                    .hasRootCauseMessage(
+                        "RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space");
+              });
```
Comment (npepinpe) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/health/DiskSpaceRecoveryIT.java:122]: :upside_down_face: IIRC, `takeSnapshot()` here only triggers the operation. Couldn't we just do something like:

- Publish a message (once we get a response, we know it will have been processed)
- Take a snapshot
- Await the snapshot
- Then continue with the test as usual

Right now, we're triggering a snapshot on every poll after every message. It likely works because we won't take snapshots in parallel (I hope :crossed_fingers:), and the snapshot is probably there very quickly, but I'd feel safer w.r.t. flakiness with a more structured approach.

Anyway, very minor :)

**Review by npepinpe — APPROVED** [review]
:tada:

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/health/DiskSpaceRecoveryIT.java (hunk 1 above)
Comment (deepthidevaki) [reply zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/health/DiskSpaceRecoveryIT.java:122]: We have to ensure a snapshot is taken with a position in segment 2 or later. If we take a snapshot once after the first command, it might not have filled the first segment. When we resume exporting, we won't be able to compact the segment and release disk space.

**Comment by korthout** [comment]
@deepthidevaki The automatic backport to 8.1 failed, and I just encountered the flaky case on 8.1 again: https://github.com/camunda/zeebe/actions/runs/8538186244/job/23390314496?pr=17265

Just wanted to give you a heads up. I don't think it's necessary to spend time on it anymore, as 8.1 is going out of support soon.
