### PR TITLE
fix: renew OIDC access token when refresh token is not JWT in tasklist

### LINKED ISSUE #39080: Tasklist fails to renew OIDC access token when refresh token is not a JWT
### 

### 

### 

### 

### Description

In Operate, a fix was applied ([#27710](https://github.com/camunda/camunda/issues/27710)) to handle cases where an OIDC refresh token is not a JWT. The fix ensures that Operate does not fail when attempting to decode such tokens, instead ignoring the decoding exception and continuing with token renewal.

Tasklist uses a similar authentication mechanism as Operate, but the fix is missing in the Tasklist codebase. As a result, environments running Tasklist 8.7 still log repeated errors such as:

> io.camunda.tasklist.webapp.security.identity.IdentityAuthentication - Unable to decode refresh token ...

This prevents Tasklist from correctly renewing access tokens when the refresh token is not JWT-encoded.

### Steps to reproduce

1. Configure Tasklist with OIDC authentication where the Identity provider issues refresh tokens that are not JWTs.
2. Allow the access token to expire.
3. Tasklist attempts to renew the access token using the refresh token.
4. Observe the Tasklist logs.

### Current behavior

- Tasklist fails to renew the access token.
- Logs show repeated errors:
> Unable to decode refresh token ...

### Expected behavior

- Tasklist should be able to handle non-JWT refresh tokens without failing.
- If decoding is not possible, it should ignore the exception and continue with the token renewal process (as in Operate’s fix).

### Environment

SM

### Version

Version 8.7

### Rootcause

- Tasklist reuses similar authentication code to Operate, but the fix from #27710 was only applied to Operate.
- Tasklist’s `IdentityAuthentication` and `IdentityRetryService` do not yet contain the updated logic for handling non-JWT refresh tokens.

### Solution ideas

- Apply the same fix that was implemented in Operate:
   - Update tasklist/webapp/.../security/identity/IdentityAuthentication.java and IdentityRetryService.java to catch and ignore exceptions when decoding a non-JWT refresh token.
   - Ensure the refresh date is set to null if decoding fails, rather than failing the entire flow.

- Add an integration test under Tasklist QA (similar to Operate’s AuthenticationRefreshTokenIT) to verify that token renewal succeeds when the refresh token is not a JWT.

### Links

Jira li: [SUPPORT-29396 ](https://jira.camunda.com/browse/SUPPORT-29396?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D)

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tanjinyi**
## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #39080

### CODE REVIEW

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/identity/AuthenticationRefreshTokenIT.java [hunk 1]
```diff
@@ -58,7 +58,7 @@
     },
     webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
 @ActiveProfiles({IDENTITY_AUTH_PROFILE, "test"})
-public class IdentityAuthenticationIT {
```
Comment (kristinkomschow) [inline tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/identity/AuthenticationRefreshTokenIT.java:61]: What's the reason for renaming this class? This doesn't only test refresh tokens but general authentication, so it seems counter-intuitive.

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/identity/AuthenticationRefreshTokenIT.java [hunk 2]
```diff
@@ -58,7 +58,7 @@
...
+public class AuthenticationRefreshTokenIT {
```
Comment (kristinkomschow) [inline tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/identity/AuthenticationRefreshTokenIT.java]: What's the reason for renaming this class? It seems counter-intuitive since this does not test refresh tokens but mostly multitenancy

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+  @BeforeEach
+  public void setup() {
+    new SpringContextHolder().setApplicationContext(applicationContext);
+    final IdentityConfiguration identityConfiguration =
+        applicationContext.getBean(IdentityConfiguration.class);
+    // setting properties with reflection because we need the wiremock server url here
+    ReflectionTestUtils.setField(
+        identityConfiguration, "issuerBackendUrl", wireMockInfo.getHttpBaseUrl());
+    ReflectionTestUtils.setField(identityConfiguration, "issuer", wireMockInfo.getHttpBaseUrl());
+    identityAuthentication = new IdentityAuthentication();
```
Comment (kristinkomschow) [inline tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java]: We don't need to instanciate `IdentityAuthentication` here. The line can be removed. Copilot is somewhat right here (same for the Operate Test).

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java [hunk 4]
```diff
@@ -0,0 +1,151 @@
...
+            WireMock.post(WireMock.urlMatching(".*/protocol/openid-connect/token"))
+                .willReturn(
+                    WireMock.jsonResponse(
+                        objectMapper.writeValueAsString(newAccessToken), HttpStatus.OK.value())));
+
+    // when - then
+    // throws token expired exception but does not log out
+    Assertions.assertThrows(
+        TokenExpiredException.class, () -> identityAuthentication.authenticate(tokens));
+    // methode will request new access token via the refresh token successfully
```
[the remark this answers is not in the document]
Comment (kristinkomschow) [reply tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java]: That typo is also in the Operate test, so it would be nice to fix it there as well as here 😄

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java [hunk 5]
```diff
@@ -0,0 +1,151 @@
...
+@SpringBootTest(
+    classes = {
+      TestApplicationWithNoBeans.class,
+      TasklistProperties.class,
+      IdentityAuthentication.class
+    },
+    properties = {
+      "camunda.identity.audience=test-client",
+      "camunda.identity.clientId=test-client",
+      "camunda.identity.clientSecret=secret",
```
Comment (kristinkomschow) [inline tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java:57]: The test is failing because of a health indicator missing. Copilot suggested fixing this by adding `"management.endpoint.health.validate-group-membership=false"` to the properties and it works.

**Review by kristinkomschow — CHANGES_REQUESTED** [review]
Overall it looks good but the test currently fails.
I left some remarks to fix it.

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/identity/AuthenticationRefreshTokenIT.java (hunk 2 above)
Comment (tanjinyi) [reply tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/identity/AuthenticationRefreshTokenIT.java]: I wanted to synchronise the naming between Operate and Tasklist ITs. I'll revert this change. I don't think I touched this file outside of the name either 😅  mistook it for the IT I created in the other file

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (tanjinyi) [reply tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java]: sure, let me port the changes over to the operate IT as well

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java [hunk 6]
```diff
@@ -0,0 +1,151 @@
...
+    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
+@ActiveProfiles({IDENTITY_AUTH_PROFILE, "test"})
+@WireMockTest
+public class AuthenticationRefreshTokenIT {
+
+  @Autowired private ApplicationContext applicationContext;
+  @Mock private Identity identity;
+  private final WireMockRuntimeInfo wireMockInfo;
+  private final ObjectMapper objectMapper = new ObjectMapper();
+  @InjectMocks private IdentityAuthentication identityAuthentication;
```
[the remark this answers is not in the document]
Comment (tanjinyi) [reply tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/webapp/security/oauth/AuthenticationRefreshTokenIT.java:70]: Removed the instantiation below in favour of @InjectMocks.

**Review by kristinkomschow — APPROVED** [review]
Assuming the last test also passes after retrying it LGTM now 👍
