### PR TITLE
fix: fix correct mapping of BatchOperationItemState #33720

### LINKED ISSUE #33720: API: Fix batchOperationItem filter by state
When searching batchOperationItems by state `ACTIVE` I find nothing, although the searchAll returns items with state `ACTIVE`.

```
### get items of single batch operation
POST http://localhost:8080/v2/batch-operation-items/search
Content-Type: application/json

{
  "page": {
    "from": 0,
    "limit": 100
  },
  "filter": {
    "state": {
      "$eq": "ACTIVE"
    }
  }
}
```

This is probably caused by a missing translation from the API state enum value `ACTIVE` to the templates state enum value `SCHEDULED`.

### PR DESCRIPTION
**Pull request by stoerti**
## Description

Adds missing enum mapping for BatchOperationItemState.

Note:
To be backwards compatible with the legacy Operate BO engine, we use the existing state schema in the ES/OS backend. This is slightly different to the new API schema.

## Related issues

closes #33720

### CODE REVIEW

**Review by p-wunderlich — APPROVED** [review]

**Review by mustafadagher — APPROVED** [review]

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/BatchOperationItemFilterTransformer.java [hunk 1]
```diff
@@ -38,4 +40,27 @@ public SearchQuery toSearchQuery(final BatchOperationItemFilter filter) {
...
+    return switch (state) {
+      case "ACTIVE" -> "SCHEDULED";
+      case "COMPLETED" -> "COMPLETED";
+      case "CANCELED" -> "CANCELED";
+      case "FAILED" -> "FAILED";
+      default -> {
+        throw new IllegalArgumentException("Unknown batch operation item state: " + state);
+      }
+    };
+  }
```
Comment (tmetzke) [inline search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/BatchOperationItemFilterTransformer.java:65]: 🔧 I believe this should rather happen in the API request mapper. We did something similar in https://github.com/camunda/camunda/pull/28430.
