### PR TITLE
6596 spaced command tests

### LINKED ISSUE #6596: [zbctl] unable to publish message containing space in message name
**Describe the bug**
Using `zbctl`, I'm unable to publish a message with a message name containing a space. It states:
```
Error: accepts 1 arg(s), received 2
```

**To Reproduce**
Steps to reproduce the behavior

Run:
```sh
zbctl publish message "Analysis Completed"
```

Result:
```
Error: accepts 1 arg(s), received 2
Usage:
  zbctl publish message <messageName> [flags]

Flags:
      --correlationKey string   Specify message correlation key
  -h, --help                    help for message
      --messageId string        Specify the unique id of the message
      --ttl duration            Specify the time to live of the message (default 5s)
      --variables string        Specify message variables as JSON string (default "{}")

Global Flags:
      --address string        Specify a contact point address. If omitted, will read from the environment variable 'ZEEBE_ADDRESS' (default '127.0.0.1:26500')
      --audience string       Specify the resource that the access token should be valid for. If omitted, will read from the environment variable 'ZEEBE_TOKEN_AUDIENCE'
      --authzUrl string       Specify an authorization server URL from which to request an access token. If omitted, will read from the environment variable 'ZEEBE_AUTHORIZATION_SERVER_URL' (default "https://login.cloud.camunda.io/oauth/token/")
      --certPath string       Specify a path to a certificate with which to validate gateway requests. If omitted, will read from the environment variable 'ZEEBE_CA_CERTIFICATE_PATH'
      --clientCache string    Specify the path to use for the OAuth credentials cache. If omitted, will read from the environment variable 'ZEEBE_CLIENT_CONFIG_PATH' (default "/Users/korthout/.camunda/credentials")
      --clientId string       Specify a client identifier to request an access token. If omitted, will read from the environment variable 'ZEEBE_CLIENT_ID'
      --clientSecret string   Specify a client secret to request an access token. If omitted, will read from the environment variable 'ZEEBE_CLIENT_SECRET'
      --insecure              Specify if zbctl should use an unsecured connection. If omitted, will read from the environment variable 'ZEEBE_INSECURE_CONNECTION'
```

**Expected behavior**
The client should publish a message with the provided message name

**Environment:**
 - OS: macOS 11.2.3
 - Zeebe Version: 0.26.1
 - Configuration: ultrawombat (testbench)

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

I decided to add a test that verified that commands with spaces will be executed correctly. From this: https://github.com/camunda-cloud/zeebe/issues/6596#issuecomment-826471112

## Related issues

closes #6596 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [X] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by aivinog1** [comment]
Hey, @MiguelPires and @korthout! Can you take a look at this? :)

**Review by korthout — COMMENTED** [review]
LGTM. Thanks for this @aivinog1

@MiguelPires please also have a look

File: clients/go/cmd/zbctl/main_test.go [hunk 1]
```diff
@@ -48,86 +48,104 @@ type integrationTestSuite struct {
...
+		},
+		cmd:        strings.Fields("--insecure activate jobs jobType --maxJobsToActivate 2"),
 		goldenFile: "testdata/double_activate_job.golden",
 		jsonOutput: true,
 	},
+	{
+		name:      "send message with a space",
+		setupCmds: [][]string{strings.Fields("--insecure deploy testdata/start_event.bpmn")},
+		// we have to use a "`" symbol to create a command argument with quotes.
+		cmd:        []string{"--insecure", "publish", "message", "`Start Process`", "--correlationKey", "1234"},
```
Comment (MiguelPires) [inline clients/go/cmd/zbctl/main_test.go:145]:
```suggestion
		cmd:        []string{"--insecure", "publish", "message", "Start Process", "--correlationKey", "1234"},
```
This works without the backticks. Can you confirm that it works for you as well?

**Review by miguelpires — CHANGES_REQUESTED** [review]
Thanks for the contribution @aivinog1. Just a small comment

File: clients/go/cmd/zbctl/main_test.go (hunk 1 above)
Comment (aivinog1) [reply clients/go/cmd/zbctl/main_test.go:145]: Hey @MiguelPires! Yep, it works, but I think that the test should be more robust (I would like to verify that a process instance will be created after sending a message). WDYT? Or we can leave this test as is (just verify that there will be no error if we use arguments with spaces)?

File: clients/go/cmd/zbctl/main_test.go [hunk 2]
```diff
@@ -48,86 +48,103 @@ type integrationTestSuite struct {
...
+		cmd:        strings.Fields("--insecure activate jobs jobType --maxJobsToActivate 2"),
 		goldenFile: "testdata/double_activate_job.golden",
 		jsonOutput: true,
 	},
+	{
+		name:       "send message with a space",
+		setupCmds:  [][]string{strings.Fields("--insecure deploy testdata/start_event.bpmn")},
+		cmd:        []string{"--insecure", "publish", "message", "Start Process", "--correlationKey", "1234"},
+		goldenFile: "testdata/publish_message_with_space.golden",
+		jsonOutput: true,
```
Comment (MiguelPires) [inline clients/go/cmd/zbctl/main_test.go:146]: I'm thinking it might be simpler to add this as a separate test case instead of changing all of the other tests cases and suite code just to cope with this specific test case. If we ever decide to remove this "assurance" and delete the test, then we'll probably forget to revert the other changes. Especially, since this isn't testing Zeebe functionality, it's more a functionality of the Cobra library, so I'm not sure that changing the all the other cases for something that isn't implemented in Zeebe is very robust. Wdyt? Although I'm not sure if writing a separate test for this will add to much duplication. I don't think so but I haven't tried to write it

Comment (MiguelPires) [reply clients/go/cmd/zbctl/main_test.go:146]: Maybe I'm being overzealous, it'll probably be fine

**Review by miguelpires — APPROVED** [review]
Thanks for the contribution @aivinog1. Please squash the review commits and then I'll run tests and merge the PR

**Comment by korthout** [comment]
@aivinog1 when rebasing, please also consider to reword the commit(s) to match the commit message guideline changes introduced with https://github.com/camunda-cloud/zeebe/pull/6870

**Comment by aivinog1** [comment]
@korthout @MiguelPires I've squashed my commits and fix a commit message, can you check this out, please? :)

**Comment by MiguelPires** [comment]
Looks good, thanks @aivinog1

bors r+

**Comment by MiguelPires** [comment]
bors retry
