### PR TITLE
fix: update legacy operations appearance in operations panel

### LINKED ISSUE #37370: Legacy batch operations are not shown properly in the operations panel of Operate's UI
### 

### 

### 

### 

### Description

The following legacy batch operations types are not shown properly in the operations panel:

- `DELETE_DECISION_DEFINITION`
- `DELETE_PROCESS_DEFINITION`
- `DELETE_PROCESS_INSTANCE`

Image

### Steps to reproduce

1. Delete a process instance OR process definition OR decision definition
2. Go to instances list view and expand the operations panel
3. Observe the operations panel entries

### Current behavior

- The entry does not show the operation type and icon
- A link is shown which always filters for an empty set of instances

### Expected behavior

- No link should be shown for these operation types (because there are no related instances)
- The correct icon should be shown
- The correct operation typs should be shown in a human readable way

### Environment

SaaS & SM

### Version

- Component Version: 8.8.0-alpha8

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by juliasaienko**
## Description

Update delete operations appearance in the operations panel by showing the corresponding:
- operation icon
- operation title
- textual(not a link) representation for the operation id

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #37370

### CODE REVIEW

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx [hunk 1]
```diff
@@ -67,18 +88,25 @@ const OperationsEntry: React.FC<Props> = ({operation}) => {
         {label === 'Migrate' && (
           <MigrateAlt size={16} data-testid="operation-migrate-icon" />
         )}
+        {label === 'Delete' && (
```
Comment (vsgoulart) [inline operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx]: I know this was already here but I guess I think it should compare against the operation type and not the label, no?

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/OperationEntryStatus/index.tsx [hunk 2]
```diff
@@ -16,15 +16,22 @@ import {Stack} from '@carbon/react';
 import {PartiallyCompleted} from './PartiallyCompleted';
 import {Failed} from './Failed';
 
+// Extended type to handle legacy operation types
+type ExtendedBatchOperationType =
+  | BatchOperationType
+  | 'DELETE_PROCESS_INSTANCE'
+  | 'DELETE_PROCESS_DEFINITION'
+  | 'DELETE_DECISION_DEFINITION';
```
Comment (vsgoulart) [inline operate/client/src/modules/components/OperationsPanel/OperationsEntry/OperationEntryStatus/index.tsx]: @juliasaienko I think we should actually extend `@camunda/camunda-api-zod-schemas/8.8`

This is coming from there, so it means the types are wrong.

**Review by vsgoulart — COMMENTED** [review]
I have only 2 small comments

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx (hunk 1 above)
Comment (juliasaienko) [reply operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx]: You're right, updated

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/OperationEntryStatus/index.tsx (hunk 2 above)
Comment (juliasaienko) [reply operate/client/src/modules/components/OperationsPanel/OperationsEntry/OperationEntryStatus/index.tsx]: I thought that these types are valid only for legacy operations, and the change is temporary, but they are the same for v2 api, so having it in one place makes more sense

**Review by vsgoulart — APPROVED** [review]

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx [hunk 3]
```diff
@@ -49,36 +58,45 @@ const OperationsEntry: React.FC<Props> = ({operation}) => {
...
+        {batchOperationType === 'MODIFY_PROCESS_INSTANCE' && (
           <Tools size={16} data-testid="operation-modify-icon" />
         )}
-        {label === 'Migrate' && (
+        {batchOperationType === 'MIGRATE_PROCESS_INSTANCE' && (
           <MigrateAlt size={16} data-testid="operation-migrate-icon" />
         )}
+        {(batchOperationType === 'DELETE_PROCESS_INSTANCE' ||
+          batchOperationType === 'DELETE_PROCESS_DEFINITION' ||
+          batchOperationType === 'DELETE_DECISION_DEFINITION') && (
```
Comment (vsgoulart) [inline operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx]:
```suggestion
        {(['DELETE_PROCESS_INSTANCE', 'DELETE_PROCESS_DEFINITION', 'DELETE_DECISION_DEFINITION'].includes(batchOperationType)) && (
```

Comment (juliasaienko) [reply operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx]: Updated

**Review by vsgoulart — APPROVED** [review]
