### PR TITLE
fix: more precise and reliable way to force new leaders in tests

### LINKED ISSUE #9921: Flaky InstallRequestHandlingTest.shouldBeAbleToBecomeLeader
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 1
- Does it block your work? No
- Do we suspect that it is a real failure? no

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
java.util.concurrent.CompletionException: java.net.ConnectException: Expected to send a message with subject 'raft-partition-partition-1-transfer' to member '0', but member is not known. Known members are '[Member{id=1, address=0.0.0.0:2146, properties={brokerInfo=EADJAAAAAwABAAAAAQAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoyMTQ1BQABAQAAAAEMAAAOAAAAOC4xLjAtU05BUFNIT1QFAAEBAAAAAQ==}}, Member{id=2, address=0.0.0.0:2150, properties={brokerInfo=EADJAAAAAwACAAAAAQAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoyMTQ5BQABAQAAAAEMAAAOAAAAOC4xLjAtU05BUFNIT1QFAAEBAAAAAQ==}}, Member{id=gateway, address=0.0.0.0:2152, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}]'.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService.send(DefaultClusterCommunicationService.java:115)
	at io.atomix.raft.partition.impl.RaftServerCommunicator.sendAndReceive(RaftServerCommunicator.java:216)
	at io.atomix.raft.partition.impl.RaftServerCommunicator.transfer(RaftServerCommunicator.java:89)
	at io.atomix.raft.impl.RaftContext.lambda$anoint$33(RaftContext.java:563)
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:171)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Expected to send a message with subject 'raft-partition-partition-1-transfer' to member '0', but member is not known. Known members are '[Member{id=1, address=0.0.0.0:2146, properties={brokerInfo=EADJAAAAAwABAAAAAQAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoyMTQ1BQABAQAAAAEMAAAOAAAAOC4xLjAtU05BUFNIT1QFAAEBAAAAAQ==}}, Member{id=2, address=0.0.0.0:2150, properties={brokerInfo=EADJAAAAAwACAAAAAQAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoyMTQ5BQABAQAAAAEMAAAOAAAAOC4xLjAtU05BUFNIT1QFAAEBAAAAAQ==}}, Member{id=gateway, address=0.0.0.0:2152, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}]'.
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService.failOnMemberNotKnown(DefaultClusterCommunicationService.java:235)
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService.sendAndReceive(DefaultClusterCommunicationService.java:223)
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService.send(DefaultClusterCommunicationService.java:114)
	... 10 more
</pre>
</details>

**Hypotheses**

None.

**Logs**

[Build](https://github.com/camunda/zeebe/runs/7560828899?check_suite_focus=true)

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

This PR changes two things:
1. after promoting a new leader, we assert that the new leader is as expected
2. retries the promote request to allow for temporary failures, for example unavailable receivers

## Related issues

closes #9921 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java [hunk 1]
```diff
@@ -602,27 +603,38 @@ public void stopBroker(final int nodeId) {
...
+        ((RaftPartition)
+                expectedLeader
+                    .getBrokerContext()
+                    .getPartitionManager()
+                    .getPartitionGroup()
+                    .getPartition(partitionId))
+            .getServer();
+
+    Awaitility.await("Promote request is successful")
+        .pollInterval(Duration.ofMillis(500))
```
Comment (Zelldon) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java:624]: :question: Any specifc reason for that poll  interval?

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java [hunk 2]
```diff
@@ -68,7 +68,7 @@ public void shouldDeleteCompactedSegmentsFilesAfterLeaderChange() {
             .getConfig()
             .getCluster()
             .getNodeId();
-    clusteringRule.forceClusterToHaveNewLeader(followerId);
+    clusteringRule.forceClusterToHaveNewLeader(1, followerId);
```
Comment (Zelldon) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java:71]: :wrench: Maybe we rename the method to `forceClusterToHaveNewLeaderForPartition` and switch the order of the parameters, then it might be more clearer for which the different numbers stand for.

:thought_balloon: Besides that, I see no different usage of the parameter yet.

**Review by ChrisKujawa — APPROVED** [review]
Thanks @oleschoenburg I have some comment see below, please check them before merging :)

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java (hunk 1 above)
Comment (oleschoenburg) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java:624]: Not at all, 500ms just felt like a reasonable interval before retrying :shrug:

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java (hunk 2 above)
Comment (oleschoenburg) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java:71]: :+1: Will rename and reorder parameters.

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java (hunk 1 above)
Comment (Zelldon) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteringRule.java:624]: Hm ok I would just remove it, otherwise it looks like it is important :shrug:

**Comment by oleschoenburg** [comment]
Thanks @Zelldon! 

bors r+

**Comment by oleschoenburg** [comment]
bors retry

**Comment by remcowesterhoud** [comment]
Flaky on stable/8.0 still. Let me try backporting

/backport
