### PR TITLE
fix(raft): reset term from last log if metastore is empty

### LINKED ISSUE #14509: Potential inconsistency in raft after restoring from a backup
**Describe the bug**

After restoring from backup, some partitions encountered [following error](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-09-26T11:26:03.072149905Z;endTime=2023-09-26T11:56:36.088Z;pinnedLogId=2023-09-26T11:26:01.585896295Z%2Fh1uykcs15coafgsq;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%22eab43606-a898-467f-967f-21a757fc69b7-zeebe%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0AjsonPayload.context.partitionId%3D%2226%22%0Atimestamp%3D%222023-09-26T11:26:01.585896295Z%22%0AinsertId%3D%22h1uykcs15coafgsq%22;startTime=2023-09-26T10:56:36.088Z;summaryFields=jsonPayload%252Fcontext%252FpartitionId,resource%252Flabels%252Fpod_name:false:32:beginning?project=camunda-saas-int-chaos).

```
java.lang.IllegalStateException: Expected to delete index after 3982, but it is lower than the commit index 3983. Deleting committed entries can lead to inconsistencies and is prohibited.
	at io.atomix.raft.storage.log.RaftLog.deleteAfter(RaftLog.java:168) ~[zeebe-atomix-cluster-8.2.13.jar:8.2.13]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:565) ~[zeebe-atomix-cluster-8.2.13.jar:8.2.13]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:511) ~[zeebe-atomix-cluster-8.2.13.jar:8.2.13]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:367) ~[zeebe-atomix-cluster-8.2.13.jar:8.2.13]
```

What happened:

First Zeebe-1 votes for Zeebe-2 and Zeebe-2 becomes leader.
```
INFO 2023-09-26T11:25:57.870482436Z [jsonPayload.context.partitionId: 26] [resource.labels.podName: zeebe-1] RaftServer{raft-partition-partition-26}{role=FOLLOWER} - Accepted PollRequest{term=0, candidate=2, lastLogIndex=3982, lastLogTerm=2}: candidate's log is up-to-date
INFO 2023-09-26T11:25:57.887139637Z [jsonPayload.context.partitionId: 26] [resource.labels.podName: zeebe-1] RaftServer{raft-partition-partition-26}{role=FOLLOWER} - Accepted VoteRequest{term=1, candidate=2, lastLogIndex=3982, lastLogTerm=2}: candidate's log is up-to-date
INFO 2023-09-26T11:25:57.892834402Z [jsonPayload.context.partitionId: 26] [resource.labels.podName: zeebe-1] RaftServer{raft-partition-partition-26} - Found leader 2
```
See above. `term` is 1, but the lastLogTerm is 2. This is because after restore, raft metastore is empty. So it restarts the term from 1. This is ok so far. But after Zeebe-2 becomes the leader and commits its InitialEntry at index `3983`, Zeebe-0 starts election probably because it did not receive any heartbeat from the leader `Zeebe-2`.

```
INFO 2023-09-26T11:26:01.569385207Z [jsonPayload.context.partitionId: 26] [resource.labels.podName: zeebe-1] RaftServer{raft-partition-partition-26}{role=FOLLOWER} - Accepted PollRequest{term=1, candidate=0, lastLogIndex=3982, lastLogTerm=2}: candidate's log is up-to-date
INFO 2023-09-26T11:26:01.577404370Z [jsonPayload.context.partitionId: 26] [resource.labels.podName: zeebe-1] RaftServer{raft-partition-partition-26}{role=FOLLOWER} - Accepted VoteRequest{term=2, candidate=0, lastLogIndex=3982, lastLogTerm=2}: candidate's log is up-to-date
INFO 2023-09-26T11:26:01.582069421Z [jsonPayload.context.partitionId: 26] [resource.labels.podName: zeebe-1] RaftServer{raft-partition-partition-26} - Found leader 0
```
Zeebe-1 accepts poll request from Zeebe-0 because Zeebe-0's lastLogTerm > Zeebe-1's current term 1. This leads to inconsistency. 

**Impact**
If it happens immediately after restore before writing any new data, it should be safe to restart the brokers. Due to the above error, the new leader Zeebe-0 cannot commit anything. So, as a result there won't be any actual data inconsistency. If we wait until all nodes are healthy before restarting the traffic to the cluster, this will not lead to any actual data inconsistency because no user requests has been processed yet. However, if there are new user data that has been processed, then there is a possibility for partial data loss. **Note that the data recovered from the backup won't be lost if this happens. Only new data will be affected.**

**To Reproduce**

Following scenario can lead to this error:
1. A, B, C restored from the same backup, where the term of the last entry in the log is > 1
2. A, B forms the quorum and A became the leader
3. A and B committed new entries 
4. C does not know about the new leader. So it starts new election.

**Expected behavior**

After, restoring from a backup raft can continue working in all scenarios.

**Environment:**
- Zeebe Version: Observed in 8.2.13

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

After restoring from a backup, metastore will be empty because backup contains only journal segments. Since metastore is empty, previously raft node re-starts the term at 0. This caused issues in election, because accepting or rejecting a poll request is also based on the last log entry's term. When the term restarts at 0, the last log entry's term can be higher than the local term which results in unexpected election results. To prevent this case we have to start the term at the term of the last log entry.

Alternate is to include meta file in the backup. But this doesn't have much benefit because no other data in the metastore is useful after restore. In some cases, it might even cause issues if restore starts with a different configuration than in the backup.

## Related issues

closes #14509 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by deepthidevaki** [comment]
@oleschoenburg I haven't added a reproducer test for the actual observed error. I don't have an idea how to deterministically reproduce it. But I hope the unit test covers the root cause.

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java [hunk 1]
```diff
@@ -249,6 +249,19 @@ public RaftContext(
...
+      // backup. Backup only contains the logs. Other case, where this can happen is when the meta
+      // file was manually deleted to recover from an unexpected bug.
+      // In both cases, we should not restart the term from 0 because the assumption in raft is that
+      // the term always increase. After restore, it is safe to restart the term at the last log's
+      // term. During the first election, the term will be incremented by 1.
+      // In the second case, it is possible that the actual term is higher. But it is still safe to
+      // set it to last log's term because the actual term will be set when this node gets the first
+      // message from other healthy replicas.
+      setTerm(raftLog.getLastEntry().term());
+    }
```
Comment (oleschoenburg) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:264]: :question: Is there are reason to do this so "late" in the constructor? I think ideally we'd do this in line 214, right after setting the term from the metastore and opening the log.

Comment (oleschoenburg) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:264]: Hm, I guess this interacts with verification of the snapshot and we have to call  `StateUtil.verifySnapshotLogConsistent`  first which can either throw if validation fails or even reset the log.

Comment (oleschoenburg) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:264]: Slightly unrelated but: when we detect a gap in `StateUtil.verifySnapshotLogConsistent`  (so log index >= snapshot index + 1) _and_ the log is empty, we reset the log. How can we have a log index > 1 but an empty log at the same time? :thinking:

File: atomix/cluster/src/test/java/io/atomix/raft/RaftResetTermAfterRestoreTest.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    }
+
+    raftRule.joinCluster(serverId);
+
+    // then
+    assertThat(raftRule.getLeader().orElseThrow().getTerm())
+        .describedAs("Should reset term by reading the last entry in the log")
+        // should be typically termBeforeShutdown + 1, but can be higher if there was more than one
+        // leader election.
+        .isGreaterThan(termBeforeShutdown);
```
Comment (oleschoenburg) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftResetTermAfterRestoreTest.java:52]: :question: I'm wondering if this is enough to validate this. `termBeforeShutdown` should typically be 1 (or 2?), right? Since we have a one-member cluster, there shouldn't be any leader elections. But we rely on that behavior because otherwise, the term after restart could be higher than `termBeforeShutdown` even without restoring the term from the last log entry.
So if we rely on it, we could also make it explicit and require that `termBeforeShutdown=1` and `termAfterShutdown=2`.

**Review by lenaschoenburg — APPROVED** [review]
Thanks @deepthidevaki, I think you found a really elegant solution here! :rocket: 

Just a couple of thoughts/questions.

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java (hunk 1 above)
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:264]: > Hm, I guess this interacts with verification of the snapshot and we have to call StateUtil.verifySnapshotLogConsistent first which can either throw if validation fails or even reset the log.

Yes. This is the reason.

Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:264]: > How can we have a log index > 1 but an empty log at the same time?

This can happen due to snapshot replication + resetting the log. Resetting the log will result in an empty log with index > 1. We reset the log before committing the snapshot. If the node restarted while committing the snapshot, but reset was successful the node will end up in this state.

File: atomix/cluster/src/test/java/io/atomix/raft/RaftResetTermAfterRestoreTest.java (hunk 2 above)
Comment (deepthidevaki) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftResetTermAfterRestoreTest.java:52]: That makes sense. :+1: We can pin the terms. I thought it is safer to assume it is not deterministic. But as you said, since it is a single node cluster it is fixed that the term will be 1 and 2 before and after respectively.

**Comment by deepthidevaki** [comment]
bors merge
