### PR TITLE
Fix overwrite of component template bug in 8.6

### LINKED ISSUE #33881: Backport the fix for ES templates getting overwritten during rolling update
### 

### 

### 

### 

### Description

Backport the fix to this issue to 8.6: https://github.com/camunda/camunda/issues/14863

The bug happens when a zeebe pod that still has the old version restarts during an update, which leads to ES/OS templates being overwritten and subsequently to the zeebe exporter lagging behind because of:
`Failed to flush bulk request: [Failed to flush 439 item(s) of bulk request [type: strict_dynamic_mapping_exception, reason: [1:1141] mapping set to strict, dynamic introduction of [operationReference] within [_doc] is not allowed]`

The bug was fixed for 8.7 but not backported.

A customer encountered this during an upgrade from 8.5 to 8.6 and is worried this will happen during their production upgrade as well. We should backport the fix for this bug to 8.6 (and maybe 8.5).

### Steps to reproduce

1. Start a rolling update
2. kill a pod that still runs the previous version
3. when it restarts it will override the templates with the previous state
4. Any index request from a pod with the new version will now fail if the last restarted pod was the previous version

### Current behavior

ES/OS schemas are in an inconsistent state after a rolling update where zeebe pods were restarted.

### Expected behavior

ES/OS schemas remain in a consistent state or get automatically corrected when (old version) zeebe pods restart during a rolling update.

### Environment

SaaS

### Version

- <8.7

### Rootcause

_No response_

### Solution ideas

Solution for 8.7: https://github.com/camunda/camunda/pull/24483

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Support case (internal): [SUPPORT-27754](https://jira.camunda.com/browse/SUPPORT-27754), [slack](https://camunda.slack.com/archives/C091ZFQSYQ0)

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

- Between versions 8.5 and 8.6, a new property called operationReference was added to the zeebe-record component template mapping (used by all zeebe-record index templates).
- However, this component template is not versioned.
- So, during the upgrade process, if an 8.5 container restarts and exports data, it overwrites the component template (effectively removing the new operationReference property).
- As a result, when an 8.6 pod creates a new zeebe-record index, it is missing the operationReference field because the older 8.5 component template was used. => strict_dynamic_mapping_exception is returned when exporting 8.6 records

This is fixed by versioning the component template, and then 
for the index templates, ensure that you are composing the versioned component template.

## Related issues

closes #33881

### CODE REVIEW

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java [hunk 1]
```diff
@@ -235,7 +235,13 @@ private boolean putIndexTemplate(final String templateName, final Template templ
 
   private boolean putComponentTemplate(final Template template) {
     try {
-      final var request = new Request("PUT", "/_component_template/" + configuration.index.prefix);
+      final var request =
```
Comment (RomanJRW) [inline zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:238]: Is this also potentially something that can happen with OpenSearch too? Do we also need to update the OS client/exporter?

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/SchemaManagerIT.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+            node ->
+                assertThat(node.at("/name").asText()).isEqualTo("zeebe-record-" + upgradedVersion));
+
+    // all 8.6.0 index templates are composed of the new index template
+    final var templateReq = new Request("GET", "/_index_template/*" + upgradedVersion + "*");
+    final var templateRes = restClient.performRequest(templateReq);
+    final var indexTemplates =
+        MAPPER.readValue(templateRes.getEntity().getContent().readAllBytes(), JsonNode.class);
+
+    assertThat(indexTemplates.at("/index_templates"))
```
Comment (RomanJRW) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/SchemaManagerIT.java:90]: can we add a `isNotEmpty()` to this assertion chain? I believe that `allSatisfy` will succeed on an empty list

**Review by RomanJRW — COMMENTED** [review]
Generally LGTM, but let a couple of comments to consider 👍 

One other thing: Do you already have a way to test this change manually? I know that Houssain identified this during manual testing, but that it came from a lot of custom changes and that it was not easily reproducible.

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 1 above)
Comment (EuroLew) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:238]: will update opensearch as well

**Comment by EuroLew** [comment]
> Generally LGTM, but let a couple of comments to consider 👍
> 
> One other thing: Do you already have a way to test this change manually? I know that Houssain identified this during manual testing, but that it came from a lot of custom changes and that it was not easily reproducible.

I can write an additional test to make sure the exporting works as expected, but regarding manual testing, I think there's a way to compile the zeebe image with my changes and then start a local cluster which could be tested on that.

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/SchemaManagerIT.java [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+import org.mockito.MockedStatic;
+import org.testcontainers.elasticsearch.ElasticsearchContainer;
+import org.testcontainers.junit.jupiter.Container;
+import org.testcontainers.junit.jupiter.Testcontainers;
+
+@Testcontainers
+public class SchemaManagerIT {
+  @Container
+  private static final ElasticsearchContainer CONTAINER =
+      TestSupport.createDefaultContainer().withEnv("action.destructive_requires_name", "false");
```
Comment (RomanJRW) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/SchemaManagerIT.java:33]: Thanks for adding the OpenSearch support. Can we also have these tests using the OpenSearchContainer?

**Review by RomanJRW — CHANGES_REQUESTED** [review]
Thanks for making the changes. I think it's good to go once we add the missing tests.

With respect to testing, I was more referring to that Houssain had to manipulate container restarts under quite fiddly circumstances and with lots of trial and error in order to see this error. I am wondering if there is a way to do the same in order to verify that this fix works as expected 🤔

**Comment by EuroLew** [comment]
> Thanks for making the changes. I think it's good to go once we add the missing tests.
> 
> With respect to testing, I was more referring to that Houssain had to manipulate container restarts under quite fiddly circumstances and with lots of trial and error in order to see this error. I am wondering if there is a way to do the same in order to verify that this fix works as expected 🤔

I don't think there's an easy way to QA these changes other than the steps that @houssain-barouni outlined in https://github.com/camunda/camunda/issues/33881#issuecomment-3036856837

**Review by RomanJRW — APPROVED** [review]
Great job, thanks @EuroLew! 🎉
