### PR TITLE
Correctly truncate a job activation batch if it will not fit in the dispatcher

### LINKED ISSUE #5525: I can't activate jobs with a high max job count
**Describe the bug**

Reported by an user I have investigate an issue where it seems they are not able to activate more jobs. They changed the default configuration of the `maxMessageSize` to `128KB` and experienced errors in the broker which indicate that job batch record is to large.

**To Reproduce**
 * Run a cluster with `maxMessageSize` set to `128KB`
 * Run our starters to create a backlog of jobs
 * Start an worker locally with `maxActivationCount` 1000+
 * FetchVariables needs to be set to "" otherwise we will fetch all variables in our benchmarks and it seem to work that the splitting of job activation succeeds

If we set the FetchVariables to empty, then the broker seems to try to put more jobs into the job activation and fails on doing that.

```csharp
                client.NewWorker()
                      .JobType(JobType)
                      .Handler(HandleJob)
                      .MaxJobsActive(5000)
                      .Name(WorkerName)
                      .AutoCompletion()
                      .PollInterval(TimeSpan.FromSeconds(1))
                      .Timeout(TimeSpan.FromSeconds(10))
                      .FetchVariables("")
                      .Open();
```

**Expected behavior**
I can activate jobs without issues. If the max message size is reached it will still returned me jobs up to the specific limit.

**Log/Stacktrace**
https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-10-07T11:40:15.009000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-small-msg-size%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-small-msg-size%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22&scrollTimestamp=2020-10-07T11:39:38.166836000Z&pinnedLogId=hrguh6fg7uydd&pinnedLogTimestamp=2020-10-07T11:39:38.166836Z

<details><summary>Full Stacktrace</summary>
 <p>

```
Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE, requestStreamId=1, requestId=533714, protocolVersion=2, valueType=JOB_BATCH, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=0.25.0}, value={"type":"benchmark-task","worker":"zell-T490","timeout":10000,"maxJobsToActivate":5000,"jobKeys":[2251799820188250,2251799820188259,2251799820188260,2251799820188282,2251799820188295,2251799820188296,2251799820188393,2251799820188400,2251799820188401,2251799820188429,2251799820188526,2251799820188557,2251799820188600,2251799820188601,2251799820188811,2251799820188851,2251799820188853,2251799820188854,2251799820188855,2251799820188857,2251799820188858,2251799820188864,2251799820188866,2251799820188875,2251799820188895,2251799820188896,2251799820188897,2251799820188898,2251799820188916,2251799820188942,2251799820189019,2251799820189048,2251799820189062,2251799820189067,2251799820189068,2251799820189082,2251799820189083,2251799820189090,2251799820189094,2251799820189097,2251799820189098,2251799820189099,2251799820189163,2251799820189166,2251799820189189,2251799820189206,2251799820189229,2251799820189230,2251799820189232,2251799820189259,2251799820189267,2251799820189309,2251799820189343,2251799820189393,22517998...}' without errors, but exception occurred with message 'Expected to claim segment of size 152616, but can't claim more than 131072 bytes.' ." 
```

</p>
</details>

**Environment:**
 - OS: k8s
 - Zeebe Version: 0.24.2, 0.25.0-SNAPSHOT
 - Configuration: default + maxMessageSize = 128KB

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes a bug where at times, we would try to activate a job batch which was too big and could not be written into the dispatcher, as when it was framed and aligned, its size would exceed the `maxFragmentLength`. The fix itself is simple, and it was to delegate, all the way down to the dispatcher (with layers adding their own framing in between), the responsibility to decide whether more jobs can be added to the batch or not. To simplify the code and testing, the responsibility of collecting jobs into a batch was extracted into a specific class.

The new API, `TypedEventWriter#canWriteEventOfLength(int)` could potentially be reused in other places where we want to prevent writing batches that are too large. However, this is a bit brittle, since it requires the code in the engine to properly compute beforehand how the record will grow when you modify it. For example, in the `JobBatchCollector`, to calculate the length of the `TypedRecord<JobBatchRecordValue> record` when adding a given `JobRecordValue` to it, we need the following:

```java
// the expected length is based on the current record's length plus the length of the job
// record we would add to the batch, the number of bytes taken by the additional job key,
// as well as one byte required per job key for its type header. if we ever add more, 
// should be updated accordingly.
final var jobRecordLength = jobRecord.getLength();
final var expectedEventLength = record.getLength() + jobRecordLength + Long.BYTES + 1;
```

Not extremely complicated, but could be error prone. A better solution, chunking the follow up events, is not something we can sanely do in between KRs, unfortunately, and would most likely carry a high risk, so wouldn't be anything we can backport. For now, I think this is an OK compromise.

NOTE: this PR depends on #8797 and #8798. Wait for these to be merged before reviewing!

## Related issues

closes #5525

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Comment by npepinpe** [comment]
Ah, so I used a `record` here, but I realize now if I want to backport this, I can't...my disappointment is immeasurable, and my day is ruined :disappointed:

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java [hunk 1]
```diff
@@ -0,0 +1,169 @@
...
+    final ValueArray<LongValue> jobKeyIterator = value.jobKeys();
+    final Collection<DirectBuffer> requestedVariables = collectVariableNames(value);
+    final var maxActivatedCount = value.getMaxJobsToActivate();
+    final var activatedCount = new MutableInteger(0);
+    final var jobCopyBuffer = new ExpandableArrayBuffer();
+    final var unwritableJob = new MutableReference<LargeJob>();
+
+    jobState.forEachActivatableJobs(
+        value.getTypeBuffer(),
+        (key, jobRecord) -> {
```
Comment (npepinpe) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java:81]: I would have liked to split this further, as this is quite a big lambda and not that readable in my opinion, but it wasn't really much better due to the amount of large state required for each iteration anyway (plus some of it being mutable).

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java [hunk 2]
```diff
@@ -0,0 +1,169 @@
...
+   * @param variableState the state from which variables are resolved and collected
+   * @param canWriteEventOfLength a predicate which should return whether the resulting {@link
+   *     TypedRecord} containing the {@link JobBatchRecord} will be writable or not. The predicate
+   *     takes in the size of the record, and should return true if it can write such a record, and
+   *     false otherwise
+   */
+  JobBatchCollector(
+      final JobState jobState,
+      final VariableState variableState,
+      final Predicate<Integer> canWriteEventOfLength) {
```
Comment (npepinpe) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java:52]: I went with passing a predicate instead of the full writer for two reasons. I didn't see the need to couple this class to the writer (which makes it easier to maintain/test imo), and in the end I wanted to discourage (for now anyway) writing here, and keep all the writes in the processor (as much as possible anyway). I think that makes the processing itself easier to understand in the end.

**Comment by npepinpe** [comment]
@saig0 - if you'd rather focus on DMN this week, I can also ask Nico to review this. Just let me know

**Comment by saig0** [comment]
>  I can also ask Nico to review this

**Review by saig0 — APPROVED** [review]
@npepinpe looks good :rocket: 
It's a nice improvement :tada: 
I like also the new test :heavy_check_mark:

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java [hunk 3]
```diff
@@ -0,0 +1,169 @@
...
+    if (variableNames.isEmpty()) {
+      variables = variableState.getVariablesAsDocument(elementInstanceKey);
+    } else {
+      variables = variableState.getVariablesAsDocument(elementInstanceKey, variableNames);
+    }
+
+    return variables;
+  }
+
+  record LargeJob(long key, JobRecord record) {}
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java:168]: I initially started with `ExcessivelyLargeJob` :smile:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
Note to self: the `record` will need to be converted to a `class` in the backports.
