### PR TITLE
Fix can activate a job without retries bug

### LINKED ISSUE #16484: I can activate a job without retries after resolving the JOB_NO_RETRIES incident
**Describe the bug**

I can activate a job without retries after resolving the JOB_NO_RETRIES incident.

**To Reproduce**

- fail a job with retries `0`
- await the incident created with error type `JOB_NO_RETRIES`
- attempt to resolve the incident
- note that the incident is resolved
- note that you can activate the job

<details><summary>Tests</summary>
<p>

Add the following test cases to `io.camunda.zeebe.engine.processing.incident.JobFailIncidentTest`

```java
@Test
public void shouldRejectResolveIncidentIfJobRetriesStillZero() {
  // given
  ENGINE.job().withType(JOB_TYPE).ofInstance(processInstanceKey).withRetries(0).fail();
  final Record<IncidentRecordValue> incidentCreatedEvent =
      RecordingExporter.incidentRecords()
          .withProcessInstanceKey(processInstanceKey)
          .withIntent(IncidentIntent.CREATED)
          .getFirst();

  // when
  final Record<IncidentRecordValue> resolvedIncidentRejection =
      ENGINE
          .incident()
          .ofInstance(processInstanceKey)
          .withKey(incidentCreatedEvent.getKey())
          .expectRejection()
          .resolve();

  // then
  assertThat(resolvedIncidentRejection)
      .hasRejectionType(RejectionType.INVALID_STATE)
      .hasRejectionReason("Job has no retries left");
}

@Test
public void shouldNotActivateJobAfterResolveIncidentRejectedBecauseJobRetriesStillZero() {
  // given
  ENGINE.job().withType(JOB_TYPE).ofInstance(processInstanceKey).withRetries(0).fail();
  final Record<IncidentRecordValue> incidentCreatedEvent =
      RecordingExporter.incidentRecords()
          .withProcessInstanceKey(processInstanceKey)
          .withIntent(IncidentIntent.CREATED)
          .getFirst();

  // when
  ENGINE
      .incident()
      .ofInstance(processInstanceKey)
      .withKey(incidentCreatedEvent.getKey())
      // .expectRejection() // todo: enable when the issue is fixed
      .resolve();

  // then
  final var reactivatedJobs = ENGINE.jobs().withType(JOB_TYPE).activate();
  assertThat(reactivatedJobs.getValue().getJobs())
      .describedAs("Expected job not activatable because no retries left")
      .isEmpty();
}
```

</p>
</details> 

**Expected behavior**

The resolve incident command should be rejected and the job should not be made activatable again.

I also suggest considering the following:
- https://github.com/camunda/zeebe/issues/9246

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
C JOB       FAIL           - #24-> -1 K10 - K10 "test" @""[ -1] 0 retries, in <process ?[?]> (no vars)
E JOB       FAILED         - #25->#24 K10 - K10 "test" @"failingTask"[K08] 0 retries, in <process "process"[K03]> (no vars)
E INCIDENT  CREATED        - #26->#24 K12 - JOB_NO_RETRIES No more retries left., joBKey: K10  @"failingTask"[K08] in <process "process"[K03]>
C INCIDENT  RESOLVE        - #27-> -1 K12 - K12
E INCIDENT  RESOLVED       - #28->#27 K12 - JOB_NO_RETRIES No more retries left., joBKey: K10  @"failingTask"[K08] in <process "process"[K03]>
C JOB_BATCH ACTIVATE       - #29-> -1  -1 - "test" max: 10
E JOB_BATCH ACTIVATED      - #30->#29 K13 - "test" 1/10
                K10 "test" @"failingTask"[K08] 0 retries, in <process "process"[K03]> with variables: {foo=bar}
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration: 
- Support: https://jira.camunda.com/browse/SUPPORT-20693

### PR DESCRIPTION
**Pull request by ana-vinogradova-camunda**
## Description
A fix for [this bug](https://github.com/camunda/zeebe/issues/16484).

It was possible before to resolve job incident when the job had 0 retries. According to Camunda 8 [documentation](https://docs.camunda.io/docs/8.3/components/concepts/incidents/#resolving-a-job-related-incident) it is not the expected behaviour and remaining retries of the job should be increased first.

Adding a check and relevant tests.

## Related issues

closes #16484 #15437

### CODE REVIEW

**Comment by megglos** [comment]
@ana-vinogradova-camunda can you double-check if the retries are updated from Operate?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java [hunk 1]
```diff
@@ -72,10 +74,17 @@ public void processRecord(final TypedRecord<IncidentRecord> command) {
       return;
     }
 
+    final long jobKey = incident.getJobKey();
+    if (isJobRelatedIncident(jobKey) && jobState.getJob(jobKey).getRetries() == 0) {
```
Comment (megglos) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java:78]: because of https://github.com/camunda/zeebe/issues/15437 it might be best to check for `<= 0`

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java [hunk 2]
```diff
@@ -29,6 +29,8 @@
 
 public final class IncidentResolveProcessor implements TypedRecordProcessor<IncidentRecord> {
 
+  public static final String NO_RETRIES_LEFT_MSG =
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java:32]: 🔧 Let's instruct api users how to solve the issue. At the end of the error message, let's mention that they can update the job retries and retry resolving the incident.

**Review by berkaycanbc — CHANGES_REQUESTED** [review]
Thanks @ana-vinogradova-camunda, clean one! 🚀 

I added couple of suggestions, please take a look. 👀 

Also, in the issue description the issue https://github.com/camunda/zeebe/issues/9246 is mentioned. Since we prioritise that one as later, should be fine to keep it out of scope for this PR. 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/incident/JobFailIncidentTest.java [hunk 3]
```diff
@@ -450,4 +460,59 @@ public void shouldDeleteIncidentIfJobIsCanceled() {
...
+    // when
+    ENGINE
+        .incident()
+        .ofInstance(processInstanceKey)
+        .withKey(incidentCreatedEvent.getKey())
+        .expectRejection()
+        .resolve();
+
+    // then
+    final var reactivatedJobs = ENGINE.jobs().withType(JOB_TYPE).activate();
```
[the remark this answers is not in the document]
Comment (ana-vinogradova-camunda) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/incident/JobFailIncidentTest.java:513]: Thank you, great suggestion 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/incident/JobFailIncidentTest.java [hunk 4]
```diff
@@ -450,4 +460,59 @@ public void shouldDeleteIncidentIfJobIsCanceled() {
...
+            .expectRejection()
+            .resolve();
+
+    // then
+    assertThat(resolvedIncidentRejection)
+        .hasRejectionType(RejectionType.INVALID_STATE)
+        .hasRejectionReason(
+            String.format(
+                "Expected to resolve incident with key '%d', but job with key '%d' has no retries left",
+                incidentCreatedEvent.getKey(), failedJob.getKey()));
```
[the remark this answers is not in the document]
Comment (ana-vinogradova-camunda) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/incident/JobFailIncidentTest.java:491]: I wonder if `shouldResolveIncidentIfJobRetriesIncreased` test already tests that?

[the remark this answers is not in the document]
Comment (berkaycanbc) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/incident/JobFailIncidentTest.java:491]: @ana-vinogradova-camunda Yes, the test case you mentioned already covers it. No need to duplicate. 👍

**Review by berkaycanbc — APPROVED** [review]
Thanks @ana-vinogradova-camunda, LGTM! 🚀 

🔧  While merging the PR: please consider rebasing smaller commits into more coarse grained commits. Also, would be good if you update description of commits with the decisions you made during the development. (e.g. because of https://github.com/camunda/zeebe/issues/15437 I added check `<= 0` instead of `=0`). That way, when we look back to related changes, we will be able to reason about decisions easily.

I am approving the PR already, feel free to add it to merge queue after re-arranging the commits.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java [hunk 5]
```diff
@@ -72,10 +74,17 @@ public void processRecord(final TypedRecord<IncidentRecord> command) {
       return;
     }
 
+    final long jobKey = incident.getJobKey();
+    if (isJobRelatedIncident(jobKey) && jobState.getJob(jobKey).getRetries() <= 0) {
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java:78]: ❓ could `jobState.getJob(jobKey)` ever return `null`? 

💭 I know this would have thrown also at `jobActivationBehavior.publishWork(jobKey, failedJobRecord)`, but just raising the question to think about null safety here

Comment (ana-vinogradova-camunda) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java:78]: I am adding a null check, could you please take a look?

Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java]: @mustafadagher @ana-vinogradova-camunda If retrieving job from the state returns null, that points to a bug in our system. Because, the job key is set to the incident record is expected to be found in the state. Other processors or any other code in our system should not remove this job from the state. Therefore, we shouldn't cover the case where the job is not found with the usual rejection.

Comment (ana-vinogradova-camunda) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java]: @berkaycanbc should the check be present in `IncindentResolverProcessor` then? If not, then it is another issue, I'd say, unrelated to what is fixed here.

Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java]: @ana-vinogradova-camunda it is not an issue existing. If there would appear to be an issue where the job is not found, an exception should be thrown and the error message should be observed on our logs. Then, we can create an issue for that. For now, removing the null check should be sufficient.

Comment (ana-vinogradova-camunda) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/incident/IncidentResolveProcessor.java]: @berkaycanbc thank you for the clarification!
