### PR TITLE
Pause and resume ReplayStateMachine

### LINKED ISSUE #5728: Only retry recoverable errors during reprocessing
**Description**

Currently, during reprocessing, we blindly retry all possible errors. As seen here #5393, some errors are definitely not recoverable, but we end up wasting resources and time (as the leader will remain leader but never process anything) unnecessarily. We should implement the same as in processing, and only retry recoverable errors.

### LINKED ISSUE #7512: Make it possible to pause ReplayStateMachine
**Description**

Currently pausing of replay is not possible, it is uninterruptible. This might be problematic if we run the Follower ReplayStateMachine in continuously mode. We should support the pause and resume pattern, we use in the ProcessingStateMachine and ExporterDirector as well.

It might make sense to verify whether we still need the EndlessRetryStrategies or whether we can replace them by AbortableStrategies, such that only RecoverableExceptions are retried. 

See related change in the POC https://github.com/camunda-cloud/zeebe/commit/375733d3a51ad2d10157fc1786486180ff2e219d

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

 * Allows to pause and resume the replay state machine
 * Add new tests which verify this behavior
 * Replace retry strategies, such that we no longer retry endless

## Related issues

closes https://github.com/camunda-cloud/zeebe/issues/7512
closes https://github.com/camunda-cloud/zeebe/issues/5728

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java [hunk 1]
```diff
@@ -56,7 +56,7 @@ public void onPaused() {
 
   @Override
   public void onResumed() {
-    if (timer == null) {
+    if (timer == null && writer != null) { // only when recovered
```
Comment (Zelldon) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java:59]: @saig0 this stuff I would like to discuss. What we actually would like to have, how should it behave. Are we expecting that when it was paused/resumed on replay that the listeners are called? Does it make sense ? Or maybe we don't want to call them, then we don't need that check here and we need to make it explicit in the inteface.

**Review by saig0 — APPROVED** [review]
Looks good :+1: 

Please have a look at my optional suggestions before merging :rocket:

**Review by saig0 — APPROVED** [review]
:+1:
