### PR TITLE
fix: write response for COMPLETE user task command with correct request metadata

### LINKED ISSUE #23925: Respond to `COMPLETE` user task command after task listener execution
## Description:
Currently, when `client.newUserTaskCompleteCommand(userTaskKey).send()` is invoked, it results in a timeout error, but at the same time user task completes successfully. The issue occurs because when finalizing the `COMPLETE` user task command after all task listener jobs are completed, the engine uses the `requestId` and `requestStreamId` from the `COMPLETE_TASK_LISTENER` command instead of the original `COMPLETE` command.

To resolve this issue, we need to:
1. Persist the `requestId` and `requestStreamId` from the original `COMPLETE` user task command.
2. Use these fields after task listener execution to finalize the original `COMPLETE` user task command.
3. Ensure that the client receives response after all task listeners are processed and user task completed.

This will allow proper tracking of user task completion ensure the client receives successfull response when all task listeners are completed.

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description
When the `client.newUserTaskCompleteCommand(userTaskKey).send().join()` method is invoked, it results in a timeout error despite the user task completing successfully. This occurs because the engine uses the `requestId` and `requestStreamId` from the `COMPLETE_TASK_LISTENER` command instead of the original `COMPLETE` command when finalizing the user task.

### Fix:
This PR implements the following changes:
1. Persists the `requestId` and `requestStreamId` from the original `COMPLETE` user task command from `UserTaskProcessor`:
> Note: Generally, persistence logic should be handled via `*Applier` classes. However, since this involves
> request-related data - in the case of command reconstruction, new request values will be produced anyway,
> so the invocation of persistence logic for request metadata from `UserTaskProcessor` is acceptable.
> This approach has precedent in `ProcessInstanceCreationCreateWithResultProcessor` also.

2. Uses the original `COMPLETE` command request metadata after all task listener jobs are completed to send the correct response.
   This ensures that the request metadata is available to finalize the original command after processing
   all task listeners, allowing the engine to respond correctly to the request.

These changes prevent the timeout error and ensure that the client receives the appropriate success response when all task listeners have finished executing and the user task is completed.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #23925

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/UserTaskProcessor.java [hunk 1]
```diff
@@ -127,6 +129,20 @@ private void handleCommandProcessing(
...
+       * command after all task listeners have been processed, ensuring that the engine can respond
+       * appropriately to the original command request.
+       *
+       * Note:
+       * Typically, persistence logic should be handled via `*Applier` classes. However, since
+       * this involves request-related data, so in the case of command reconstruction,
+       * we will have new request values anyway, so persisting these data here is acceptable.
+       * A similar approach has been used in `ProcessInstanceCreationCreateWithResultProcessor`.
+       */
+      storeUserTaskRecordRequestMetadata(command);
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/UserTaskProcessor.java:144]: 👍 I like that you store it here. This ensures it's stored for all user task commands, rather than just for the complete command.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/processors/UserTaskCompleteProcessor.java [hunk 2]
```diff
@@ -80,10 +84,29 @@ public void onFinalizeCommand(
...
+            responseWriter.writeResponse(
+                userTaskKey,
+                UserTaskIntent.COMPLETED,
+                userTaskRecord,
+                ValueType.USER_TASK,
+                metadata.getRequestId(),
+                metadata.getRequestStreamId()),
+        () ->
+            responseWriter.writeEventOnCommand(
+                userTaskKey, UserTaskIntent.COMPLETED, userTaskRecord, command));
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/processors/UserTaskCompleteProcessor.java:109]: 🔧 It's probably never the case, but we could consider the case where the command doesn't have request metadata and it also wasn't stored in the state.

```suggestion
    if (command.requestId != null && command.requestStreamId() != null) {
      responseWriter.writeEventOnCommand(
          userTaskKey, UserTaskIntent.COMPLETED, userTaskRecord, command));
    } else {
      // If the record request metadata is present, it indicates that "complete" task listeners were
      // configured, and that the normal flow of the "COMPLETE" command was interrupted by the
      // "COMPLETE_TASK_LISTENER" command. In this case, we need to use the `requestId` and
      // `requestStreamId` from the persisted metadata, which refers to the original "COMPLETE"
      // command to write the response back.
      recordRequestMetadata.ifPresent(
        metadata ->
            responseWriter.writeResponse(
                userTaskKey,
                UserTaskIntent.COMPLETED,
                userTaskRecord,
                ValueType.USER_TASK,
                metadata.getRequestId(),
                metadata.getRequestStreamId()));
    }
```

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/immutable/UserTaskState.java [hunk 3]
```diff
@@ -21,6 +23,8 @@ public interface UserTaskState {
 
   UserTaskIntermediateStateValue getIntermediateState(final long userTaskKey);
 
+  Optional<UserTaskRecordRequestMetadata> getRecordRequestMetadata(final long userTaskKey);
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/immutable/UserTaskState.java:26]: 🔧 As this returns an optional, we could consider naming this `findRecordRequestMetadata` to clarify that it could optionally return a value or not.

**Review by korthout — APPROVED** [review]
Thanks @ce-dmelnych 🚀 

👍 I like the changes. 

💭 The commit that stores the metadata from the processor rather than an event should IMO describe why this is acceptable. I know it's currently described in a code comment which is also appropriate, but it could get out-of-date. This is not the case with commit messages as they describe the changes in the context of that moment in time rather than the code itself.

🔧 Please have a look at my comments, I've made a few suggestions.

**Review by ana-vinogradova-camunda — APPROVED** [review]
LGTM 🚀 
Very clean and easy to understand changes, thanks @ce-dmelnych!

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/processors/UserTaskCompleteProcessor.java (hunk 2 above)
Comment (ce-dmelnych) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/processors/UserTaskCompleteProcessor.java]: Thanks for the suggestion, @korthout! 🚀

I found that we can use the `command.hasRequestMetadata()` method to check if the current command contains request metadata. So, I’ve improved the previous implementation to only query request metadata from `UserTaskState` if it’s not present in the current command.

❓ Would it make sense to add `warn` logging when request metadata is missing in both: the current command and `UserTaskState`?
I noticed that logging isn’t widely used across command processors, but adding it here could improve visibility in such "unexpected" cases. I’d be glad to hear your thoughts on this!

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/immutable/UserTaskState.java (hunk 3 above)
Comment (ce-dmelnych) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/immutable/UserTaskState.java]: Yeah, I've changed the method to return `Optional` just before committing the first commit 🙈.
Thanks Nico for highlighting this! I’ve renamed it to `findRecordRequestMetadata` 👍.

**Comment by ce-dmelnych** [comment]
> 💭 The commit that stores the metadata from the processor rather than an event should IMO describe why this is acceptable. I know it's currently described in a code comment which is also appropriate, but it could get out-of-date. This is not the case with commit messages as they describe the changes in the context of that moment in time rather than the code itself.

Thank you, @korthout, for the thoughtful review and recommendations. I’ve updated the body of the first commit to explain why it’s acceptable in a such case to store request metadata directly from `UserTaskProcessor`.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/processors/UserTaskCompleteProcessor.java (hunk 2 above)
Comment (korthout) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/processors/UserTaskCompleteProcessor.java]: You're right that logging isn't widely used, but this is something [we'd like to improve](https://github.com/camunda/camunda/issues/16276). 

However, too many logs is also bad, so we need to consider whether they are useful. The way I think about it is: would it be helpful in this context when that case were to occur? Here, if we don't have any request info available, we can't respond. But that's expected I guess. Perhaps I'm overlooking something though. Curious to your thought 🙇

Comment (ce-dmelnych) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/processors/UserTaskCompleteProcessor.java]: 🤔 Hmm… what I imagine is that having this log (e.g., `Request metadata was not present in the current command nor in user task state for user task with key {}. The client will not receive a response.`) could help clarify cases where the client didn’t receive a response - not due to a timeout issue (such as a long-running listener exceeded the Tasklist timeout value of 10-15 seconds (or whatever is configured)) but specifically because request metadata was unexpectedly missing.

Additionally, since this is a "_should not happen_" case, we normally wouldn’t expect to see it in the logs. So, its presence could serve as an indicator that something went wrong.

Or maybe I’m just overthinking it! 😄

Comment (ce-dmelnych) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/processors/UserTaskCompleteProcessor.java]: Anyway, we can always add the logging later if it turns out to be helpful!
For now, I’m merging it as is 😉
