### PR TITLE
39202 stop throwing exception when process not yet imported for incident

### LINKED ISSUE #39202: Lower severity for incident update task
Current severity for is logged as `ERROR` where this is something that can happen under normal circumstances and usually results in being auto resolved. We should lower the severity to `WARN`

```
Caused by: io.camunda.zeebe.exporter.api.ExporterException
at io.camunda.exporter.tasks.incident.IncidentUpdateTask.checkDataAndCollectParentTreePaths ( IncidentUpdateTask.java:166 )
at io.camunda.exporter.tasks.incident.IncidentUpdateTask.searchForInstances ( IncidentUpdateTask.java:121 )
at io.camunda.exporter.tasks.incident.IncidentUpdateTask.processNextBatch ( IncidentUpdateTask.java:92 )
at io.camunda.exporter.tasks.incident.IncidentUpdateTask.execute ( IncidentUpdateTask.java:73 )
at io.camunda.exporter.tasks.ReschedulingTask.run ( ReschedulingTask.java:47 )
```

Console log: https://console.cloud.google.com/errors/detail/CPbqnsKaiKu05AE;service=zeebe;time=P7D;locations=global?project=camunda-saas-int

### PR DESCRIPTION
**Pull request by lilspikey**
## Description

Previously if the incident update task ran and could not find a matching process instance for an incident it would throw an exception to force retrying later on.  This would lead to a fair bit of log noise.

It's expected that we will have times where this will happen under normal operation and retrying is the correct behaviour.  As it's expected behaviour there is little point raising an exception and thus triggering ERROR level logging.

This PR changes things so we just return early from the task if the process instance is not found.  It does also perform some WARN logging.

In addition metrics have been added to track how often we end up skipping updates like this vs how often we actually perform the updates.  This should let us attach alerts if for some reason we _never_ find the matching process instance.

## Related issues

closes #39202

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java [hunk 1]
```diff
@@ -255,15 +274,7 @@ private void checkDataAndCollectParentTreePaths(
...
                   .toString());
     }
-
-    if (countMissingInstance > 0 && !ignoreMissingData) {
-      throw new ExporterException(
-          """
-        "%d process instances are not yet imported for incident post processing; operation will \
-        be retried...
-        """
-              .formatted(countMissingInstance));
```
Comment (houssain-barouni) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java:263]: ❓ this was never reached before, isn't?

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java [hunk 2]
```diff
@@ -136,7 +142,16 @@ private CompletableFuture<Integer> processNextBatch() {
...
     }
     logger.trace("Applying the following pending incident updates: {}", batch.newIncidentStates());
-    searchForInstances(data);
+    final var check = searchForInstances(data);
+    final int incidentCount = batch.newIncidentStates().size();
+    if (check != InstancesCheck.OK) {
+      // there was missing data, but this is often transient, so we just skip this batch for now.
+      // we return the batch size so it's clear that we want to try again soon (as there was work
+      // to do, but we just can't do it ATM)
+      metrics.recordIncidentUpdatesSkipped(incidentCount);
```
Comment (houssain-barouni) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java]: I am not sure about the word `skipped`, it can be understood as ignored, maybe `toBeRetried` is better?

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java [hunk 3]
```diff
@@ -152,31 +167,33 @@ private CompletableFuture<Integer> processNextBatch() {
...
-                  batch.newIncidentStates().size(),
+                  incidentCount,
                   documentsUpdated,
                   batch.highestPosition());
 
               if (documentsUpdated > 0) {
                 metadata.setLastIncidentUpdatePosition(batch.highestPosition());
               }
 
+              metrics.recordIncidentUpdatesProcessed(incidentCount);
```
Comment (houssain-barouni) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java]: it may be useful to record the updated documents count metric, as well

**Review by houssain-barouni — APPROVED** [review]
LGMT!
I left some minor comments

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java (hunk 1 above)
Comment (lilspikey) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java:263]: Yeah in practice if `ignoreMissingData` was `false`, then `forceIgnoreMissingData` is always false as we do:
```
checkDataAndCollectParentTreePaths(incidents, data, false);
    ...
checkDataAndCollectParentTreePaths(incidents, data, ignoreMissingData);
```

so it would always trigger the earlier exception instead (which is now a `return InstancesCheck.MISSING_DATA;`)

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java (hunk 2 above)
Comment (lilspikey) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/IncidentUpdateTask.java]: yeah retry probably makes better sense

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/metrics/CamundaExporterMetrics.java [hunk 4]
```diff
@@ -336,6 +373,8 @@ public void close() {
     meterRegistry.remove(flushDuration);
     meterRegistry.remove(failedFlush);
     meterRegistry.remove(recordExportDuration);
+    meterRegistry.remove(incidentUpdatesRetriesNeeded);
+    meterRegistry.remove(incidentUpdatesProcessed);
```
Comment (houssain-barouni) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/metrics/CamundaExporterMetrics.java:377]: 🔧 we need to remove `incidentUpdatesDocumentsUpdated`

**Review by houssain-barouni — COMMENTED** [review]
LGTM! I had one last comment

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/metrics/CamundaExporterMetrics.java (hunk 4 above)
Comment (lilspikey) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/metrics/CamundaExporterMetrics.java:377]: done
