### PR TITLE
fix: handle invalid incidentKey gracefully #35201

### LINKED ISSUE #35201: Handle already resolved incident gracefully in batch operation
When an incident is tried to be resolved by the Zeebe batch operation which already has been resolved in the mean time (due to eventual consistency this can happen), currently a `NullPointerException` is thrown.

AC:
- No NPE is thrown. Instead the a rejection NOT_FOUND is appended and the batch operation item is marked with an error.

### PR DESCRIPTION
**Pull request by stoerti**
## Description

This PR solves a `NullPointerException` when an incident is trying to be resolved in a batch operation and this incident is already resolved by some external event and dos not exist anymore.

Also added some more explicit tests for this scenario to the other batch operation types as well.

## Related issues

closes #35201

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java [hunk 1]
```diff
@@ -32,19 +32,31 @@ public ResolveIncidentBatchOperationExecutor(
...
 
   @Override
-  public void execute(final long itemKey, final PersistedBatchOperation batchOperation) {
-    final var incident = incidentState.getIncidentRecord(itemKey);
+  public void execute(final long incidentKey, final PersistedBatchOperation batchOperation) {
+    final var incident = incidentState.getIncidentRecord(incidentKey);
+    if (incident == null) {
+      // ok I admit it, this is a bit of a hack, but we need to provoke an IncidentIntent.REVOLVE
+      // rejection here, so we still append the resolve incident command
+      resolveIncident(incidentKey, batchOperation);
```
Comment (p-wunderlich) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java:40]: Maybe we should at least also add a log statement here. We could also skip the following if in this case and use the resolve incident from line 52.

Comment (stoerti) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java:40]: - I wanted to be consistent with the other batch types, there also no logging happens.
- you mean to have the "resolveIncident" only once? For me it is more readable and clear this way because I have a clear "if not exist" branch and a clear "if exist" branch 🤔

Comment (p-wunderlich) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java:40]: I think in other batch types we don't have such an hack like her, or? :D (At least up to now)

Comment (stoerti) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java:40]: Ok, added a log statement ;)

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java [hunk 2]
```diff
@@ -32,19 +32,32 @@ public ResolveIncidentBatchOperationExecutor(
   }
 
   @Override
-  public void execute(final long itemKey, final PersistedBatchOperation batchOperation) {
-    final var incident = incidentState.getIncidentRecord(itemKey);
+  public void execute(final long incidentKey, final PersistedBatchOperation batchOperation) {
+    final var incident = incidentState.getIncidentRecord(incidentKey);
+    if (incident == null) {
+      // ok I admit it, this is a bit of a hack, but we need to provoke an IncidentIntent.REVOLVE
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java:38]: 💭 would it be an idea to reject the `execution` instead? or does that influence too much downwards?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java [hunk 3]
```diff
@@ -32,19 +32,32 @@ public ResolveIncidentBatchOperationExecutor(
   }
 
   @Override
-  public void execute(final long itemKey, final PersistedBatchOperation batchOperation) {
-    final var incident = incidentState.getIncidentRecord(itemKey);
+  public void execute(final long incidentKey, final PersistedBatchOperation batchOperation) {
+    final var incident = incidentState.getIncidentRecord(incidentKey);
+    if (incident == null) {
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java:37]: 🔧 if we decide to keep it this way, we might want to move this check below
```java
if (incident != null && incidentState.isJobIncident(incident)) {
...
}
```

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java [hunk 4]
```diff
@@ -32,19 +32,32 @@ public ResolveIncidentBatchOperationExecutor(
...
+      // ok I admit it, this is a bit of a hack, but we need to provoke an IncidentIntent.REVOLVE
+      // rejection here, so we still append the resolve incident command
+      LOGGER.debug("Incident with key '{}' not found, rejecting command", incidentKey);
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java]: 💭 this will be already clear from the rejection

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java (hunk 2 above)
Comment (stoerti) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/handlers/ResolveIncidentBatchOperationExecutor.java:38]: I would move that to a separate issue, if needed.

This would require some more planning, since it might also lead to a new status in exporter/API/Frontend, as the record is just SKIPPED but neither FAILED or COMPLETED.

Also, appending an EXECUTE-rejection with this single key feels a bit off for me when we actually afterwards continue with the next item and loop and also have to mark the rejected item as EXECUTED as well.

But yes, Patrick and me had the same feeling, that in the future we might need to have some record/intent to mark items with a status without involving the actual executors.

**Review by mustafadagher — APPROVED** [review]
Thanks @stoerti !
🔧 I left some suggestions to move the check where it's only needed and get rid of an unnecessary log if it will make the flow cleaner
🔧 Let's maybe create an issue to think about / consider if rejecting executions when we know they're unnecessary could be desirable. 

Pre-approving since nothing is blocking

**Comment by stoerti** [comment]
- removed the log statement again which @p-wunderlich requested during his review 😉 
- added a follow-up ticket https://github.com/camunda/camunda/issues/35457 for a maybe new rejection & status flow
