### PR TITLE
Don't override variables when completing sub process

### LINKED ISSUE #6926: Variables are overridden when the subprocess is completed
**Describe the bug**
Variables of the process instance are overridden when the embedded subprocess is completed.

The subprocess has a non-interrupting message boundary event. The boundary event and the subprocess have no output mappings.

A message with variables is correlated to the boundary event and the variables are created at the scope of the process instance.
The variables are updated with a different value afterward (i.e. by completing a job). When the subprocess is completed then the values of the variables are overridden by their original values from the message (i.e. lost update). 

image

**To Reproduce**
1. deploy a workflow with an embedded subprocess and a non-interrupting boundary event
2. create a new process instance 
3. publish a message with variables `{"x":1}`
4. update the variables `{"x":2}`
5. complete the subprocess by completing the job (without variables)
6. verify that the variables are overridden to `{"x":1}`  

**Expected behavior**
The variables are not overridden when the embedded subprocess is completed.

**Log/Stacktrace**
No log or stacktrace available.

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `1.0.0-alpha7`
 - Configuration:

### PR DESCRIPTION
**Pull request by korthout**
## Description

fix(engine): use local vars for msg correlation

Variables could be overridden when a subprocess is completed,
specifically when non-interrupting events have happened on that
subprocess that placed temporary variables on it.

The biggest problem here is/was that the temporary variables are not
cleaned up until the element is completed. On completing the element,
the output mappings are applied and these then use all temporary
variables that still exist on it.

We can avoid this by reducing our temporary variables usage (something
we anyways want to do).

Message correlations with variables already create the variables
locally, so temporary variables are no longer needed for boundary
events.

## Related issues

closes #6926 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by korthout** [comment]
@saig0 I've added the `backport release-1.0.0-rc1` label, but I'm not sure this absolutely needs to be in there. Please let me know what you think.

File: test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java [hunk 1]
```diff
@@ -483,15 +483,20 @@ private String summarizeProcessInstanceSubscription(final Record<?> record) {
...
         .append("[")
         .append(shortenKey(value.getProcessInstanceKey()))
-        .append("]>")
-        .toString();
+        .append("]");
+    if (value.getProcessInstanceKey() != value.getScopeKey()) {
+      // only add if they're different, no need to state things twice
+      builder.append(" at [").append(shortenKey(value.getScopeKey()));
+    }
+    return builder.append("]>").toString();
```
Comment (saig0) [inline test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java:499]: If the variable has the process instance as the scope then the formatted message looks not symmetric. There is an additional square bracket.

`x -> 1 in <process[1]]>`

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/subprocess/EmbeddedSubProcessTest.java [hunk 2]
```diff
@@ -500,4 +523,44 @@ public void shouldTerminateSubProcessWithPendingParallelGateway() {
             tuple(BpmnElementType.SUB_PROCESS, ProcessInstanceIntent.ELEMENT_TERMINATED),
             tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.ELEMENT_TERMINATED));
   }
+
+  @Test
+  public void shouldNotOverrideVariablesOnCompleteSubProcess() {
+    // given a process instance waiting for a job inside a sub process
+    ENGINE.deployment().withXmlResource(ONE_TASK_SUB_PROC_WITH_NON_INT_MSG_BNDRY_EVENT).deploy();
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/subprocess/EmbeddedSubProcessTest.java:530]: `ONE_TASK_SUB_PROC_WITH_NON_INT_MSG_BNDRY_EVENT` this is a long name for a variable :sweat_smile: 

(optional) We could write the BPMN directly in the test case instead of using a constant. It could make the test case easier to understand if the BPMN is closer to the code that tests the flow. Otherwise, you may need to jump from bottom to top and back.

**Review by saig0 — APPROVED** [review]
Nice :rocket: 

Please have a look at my two minor comments before merging :cookie:

File: test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java (hunk 1 above)
Comment (korthout) [reply test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java]: Fixed, I've also applied `String.format` to make the formatting more readable.

**Comment by korthout** [comment]
bors merge
