### PR TITLE
Coordinate take backup request in gateway

### LINKED ISSUE #10281: Coordinate take backup operation in gateway
Implement a request handler in Gateway to coordinate take backup operation. This request handler should send take backup request to all partitions and collect the responses. If at least one partition failed then the operation is failed.

The actuator should be able to delegate the request to this handler and collect the responses. All coordination logic must be in this request handler.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

- Added a request handler that sends take backup requests to all partitions.
- The request fails if atleast one partitions fails to successfully respond
- When the request is completed, backup would have started on all partition, but not necessarily completed.

## Related issues

closes #10281 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupFailedException.java [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+ * Licensed under the Zeebe Community License 1.1. You may not use this file
+ * except in compliance with the Zeebe Community License 1.1.
+ */
+package io.camunda.zeebe.gateway.admin.backup;
+
+public class BackupFailedException extends RuntimeException {
+
+  public BackupFailedException(final long backupId, final Throwable error) {
+    super(
+        "Failed to trigger backup (id = %d) on at least one partition.".formatted(backupId), error);
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupFailedException.java:14]: :+1: Haven't seen `.formatted` usages yet

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+package io.camunda.zeebe.gateway.admin.backup;
+
+import io.camunda.zeebe.gateway.cmd.NoTopologyAvailableException;
+import io.camunda.zeebe.gateway.impl.broker.BrokerClient;
+import io.camunda.zeebe.gateway.impl.broker.cluster.BrokerClusterState;
+import io.camunda.zeebe.gateway.impl.broker.cluster.BrokerTopologyManager;
+import java.util.concurrent.CompletableFuture;
+import java.util.stream.IntStream;
+
+public class BackupRequestHandler implements BackupApi {
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:17]:
```suggestion
public final class BackupRequestHandler implements BackupApi {
```

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BrokerBackupRequest.java [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+import io.camunda.zeebe.protocol.record.intent.management.CheckpointIntent;
+import io.camunda.zeebe.transport.RequestType;
+import io.camunda.zeebe.util.buffer.BufferWriter;
+import org.agrona.DirectBuffer;
+import org.agrona.MutableDirectBuffer;
+
+/** Wraps the request and response for "Take Backup" sent between gateway and broker */
+public class BrokerBackupRequest extends BrokerRequest<CheckpointRecord> {
+
+  protected final BackupRequest request = new BackupRequest();
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BrokerBackupRequest.java:31]: :question: Is this class meant to be extensible?

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BrokerBackupRequest.java [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+  }
+
+  @Override
+  protected void wrapResponse(final DirectBuffer buffer) {
+    response.wrap(buffer, 0, buffer.capacity());
+  }
+
+  @Override
+  protected BrokerResponse<CheckpointRecord> readResponse() {
+    if (response.getRecordType() == RecordType.COMMAND_REJECTION) {
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BrokerBackupRequest.java:76]: :thought_balloon: This code is sort of shared with the `BrokerExecuteCommand` right? Perhaps we should think about moving it to the `BrokerRequest` in general, if now all requests can return a rejection? I know the admin requests can't, but that just means it will never be mapped to a rejection (and that method can still be overwritten anyway :shrug:)

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+  }
+
+  @Override
+  public CompletableFuture<Long> takeBackup(final long backupId) {
+    final BrokerClusterState topology = topologyManager.getTopology();
+    if (topology == null) {
+      return CompletableFuture.failedFuture(new NoTopologyAvailableException());
+    }
+
+    final int partitionsCount = topology.getPartitionsCount();
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:34]: :wrench: This tripped me up a bit, I was wondering why not just use `topology.getPartitions()`, but then realized it's to deal with incomplete topologies. Maybe we can add a comment here why we're specifically going via the partition count? 

:upside_down_face: It also feels somewhat brittle to count 1 to partition count, and use that as the ID. I'm wondering if it might not make more sense to do something like `IntStream.range(0, partitionsCount).map(topology::getPartition)`, to decouple that. Just a minor nit, feel free to ignore, I'm not even convinced by myself :smile:

**Review by npepinpe — COMMENTED** [review]
:+1: 

I need to go through the failure modes, primarily error reporting before I can approve. Though if you already went through, then you can comment and that will save us both some time :slightly_smiling_face: Or if you think we should focus on the UX once we're closer to having all the parts together, that's also fair, we can postpone this.

- [ ] What happens when there is no leader, or no known broker, for a given partition? What error will the user get?
- [ ] What happens when the command is rejected? What error will be the user get?

:thought_balloon: Speaking of, I'm also wondering, since error reporting is part of the API, shouldn't we define this, at the very least through tests? Again it's possible we decide to do this once we have more of the moving parts glued together.

**Comment by deepthidevaki** [comment]
The request is send via `BrokerClient`. So the errors are similar to what we get for other operations.

> What happens when there is no leader, or no known broker, for a given partition? What error will the user get?

If the request is received by the a broker, then it gets an error response with PARTITION_LEADER_MISMATCH. If the gateway does not know about a partition or the leader or partition, then the request fails with an exception. This exception is defined by the BrokerClient. Assumption is that this exception has a user friendly error message. `BackupRequestHandler` does not care what this exception is, it just fails the request with `BackupFailedException` with this exception as the cause. 

> What happens when the command is rejected? What error will be the user get?

If the command is rejected, `BrokerClient::sendRequest` fails the future with exception. Then it is handled as above.

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BrokerBackupRequest.java (hunk 3 above)
Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BrokerBackupRequest.java:31]: No. This can be final.

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BrokerBackupRequest.java (hunk 4 above)
Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BrokerBackupRequest.java:76]: The type of `response` is different for other requests. So we cannot move it to `BrokerRequest`.

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java (hunk 5 above)
Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:34]: Yes. It is brittle because we are assuming how partition ids are generated. 
We cannot use `topology::getPartition` because it returns a valid id only if it has full topology. 

Alternate: we can check if `topology.getPartitionCount() == topology.getPartitions().size()`. And then use `topology.getPartitions()`.

Comment (npepinpe) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java:34]: Assuming the error you get when the partition is unknown is alright, then I think how you did it is fine, maybe we can add a comment since the why is not immediately clear I think.

**Comment by deepthidevaki** [comment]
> Speaking of, I'm also wondering, since error reporting is part of the API, shouldn't we define this, at the very least through tests? Again it's possible we decide to do this once we have more of the moving parts glued together.

My idea was that, there will be two response:
1: Success -> BackupApi::takeBackup completes the future successfully
2. Failure -> future is completed with BackupFailedException, with a cause that is thrown by BrokerClient. User gets the response with this error message.

If we need to differentiate between different types of failure, we can discuss this during the actuator implementation.

File: gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java (hunk 5 above)
Comment (deepthidevaki) [reply gateway/src/main/java/io/camunda/zeebe/gateway/admin/backup/BackupRequestHandler.java]: I updated it to check if topology.getPartitionCount() == topology.getPartitions().size(). And then use topology.getPartitions(). This is safer, as we are not assuming that partitionIds starts from 1.

**Review by npepinpe — APPROVED** [review]
:+1: I like the usage of specific exceptions, as that'll make it much easier to translate to good user errors when we get to that part

**Comment by deepthidevaki** [comment]
@npepinpe Thanks for the review. Let's fine tune the api, especially the error responses when we add the actuator.

**Comment by deepthidevaki** [comment]
bors merge
