### PR TITLE
Suppress error messages in ReschedulingTask.

### LINKED ISSUE #28039: CamundaExporter reschedulingTask: "Error occurred while performing a background "task leads to exception
**Describe the bug**

`ReschedulingTask` has the following warning:
` "Error occurred while performing a background task; operation will be retried"`

As the comment on line 75 states:
```
    // TODO: it's likely in some cases, we do want to log things as errors, but we need to
    //  distinguish this from "normal" cases (e.g. missing data in ES, or ES temporarily
    //  unavailable, etc.)
```
It might be a "normal" case. However, I am not sure and I observed multiple `ConnectionClosedException: Connection is closed` in this particular case.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.CompletionException: org.apache.http.ConnectionClosedException: Connection is closed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.apache.http.ConnectionClosedException: Connection is closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.16.jar:4.4.16]
	... 1 more
```

</p>
</details>

Link to GCP logs: [here](https://console.cloud.google.com/errors/detail/CPbl4OrCgZPgeA;service=zeebe;time=P7D;locations=global?inv=1&invt=AbpXhA&project=camunda-saas-prod-sin)

Warning logged after three `Error occurred while performing a background task; operation will be retried` errors:
```
{
    "severity": "ERROR",
    "logging.googleapis.com/sourceLocation": {
        "function": "onError",
        "file": "ReschedulingTask.java",
        "line": 74
    },
    "message": "Error occurred while performing a background task; operation will be retried",
    "serviceContext": {
        "service": "zeebe",
        "version": "8.7.0-alpha2"
    },
    "context": {
        "threadId": 142,
        "threadPriority": 5,
        "loggerName": "io.camunda.zeebe.broker.exporter.camundaExporter",
        "threadName": "exporter-camundaexporter-p1-tasks-2"
    }
}
```

**Environment:**
- OS: 
- Zeebe Version: zeebe:8.7.0-alpha2
- Configuration:

### LINKED ISSUE #30731: ExporterException: Flow node instance with incident cannot be updated due to no document for it in list view index.
Describe the bug

On the exporter, we observe the following error message, which is caused by the stack trace below.

```
Error occurred while performing a background task; operation will be retried
```

Seems that we cannot export flow node with incident since there is no document for it. Although it seems to have recovered as it contained to export right after this.

[link to logs](https://console.cloud.google.com/errors/detail/CKDSpLHejM2jUQ;service=zeebe;time=P7D;locations=global?inv=1&invt=AbtPLA&project=camunda-saas-prod), happened in `8.8.0-alpha2` in Saas-prod. 

```
java.util.concurrent.CompletionException: io.camunda.zeebe.exporter.api.ExporterException: Flow node instance 2251799816968994 affected by incident 2251799816969003 cannot be updated because there is no document for it in the list view index yet; this will be retried later.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApplyAsync(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApplyAsync(Unknown Source) ~[?:?]
	at io.camunda.exporter.tasks.ReschedulingTask.run(ReschedulingTask.java:62) ~[camunda-exporter-8.8.0-alpha2.jar:8.8.0-alpha2]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: io.camunda.zeebe.exporter.api.ExporterException: Flow node instance 2251799816968994 affected by incident 2251799816969003 cannot be updated because there is no document for it in the list view index yet; this will be retried later.
	at io.camunda.exporter.tasks.incident.IncidentUpdateTask.createFlowNodeInstanceUpdates(IncidentUpdateTask.java:291) ~[camunda-exporter-8.8.0-alpha2.jar:8.8.0-alpha2]
	at io.camunda.exporter.tasks.incident.IncidentUpdateTask.processIncidents(IncidentUpdateTask.java:245) ~[camunda-exporter-8.8.0-alpha2.jar:8.8.0-alpha2]
	at io.camunda.exporter.tasks.incident.IncidentUpdateTask.processNextBatch(IncidentUpdateTask.java:88) ~[camunda-exporter-8.8.0-alpha2.jar:8.8.0-alpha2]
	at io.camunda.exporter.tasks.incident.IncidentUpdateTask.execute(IncidentUpdateTask.java:73) ~[camunda-exporter-8.8.0-alpha2.jar:8.8.0-alpha2]
	at io.camunda.exporter.tasks.ReschedulingTask.run(ReschedulingTask.java:51) ~[camunda-exporter-8.8.0-alpha2.jar:8.8.0-alpha2]
	... 6 more
```

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

This PR suppresses the error messages in ReschedulingTask, since these can happen for several reasons such as common ES restarts. See issue: https://github.com/camunda/camunda/issues/28039
## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes https://github.com/camunda/camunda/issues/28039 
closes https://github.com/camunda/camunda/issues/30731
closes https://github.com/camunda/camunda/issues/25991

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/ReschedulingTask.java [hunk 1]
```diff
@@ -37,7 +37,7 @@ public ReschedulingTask(
     this.executor = executor;
     this.logger = logger;
 
-    periodicLogger = new ReschedulingTaskLogger(logger);
+    periodicLogger = new ReschedulingTaskLogger(logger, true);
```
Comment (EuroLew) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/ReschedulingTask.java:40]: ❓  Should we make this configurable?

**Review by EuroLew — COMMENTED** [review]
just a question

**Review by RomanJRW — APPROVED** [review]
