### PR TITLE
Ensure unique Identity ES/OS index IDs

### LINKED ISSUE #32252: Identity index IDs are not unique enough
### 

### 

### 

### 

### Description

I will take roles and users as an example here. This problem also exists for groups and tenants.

When we create a role it is stored in the roles index with the `roleId` as the id of the document. When we assign this role to a user we will add another document to the index. This id will becomes `roleId-username`. With this setup it is very easy to overwrite certain documents. See the reproduction steps. 

### Steps to reproduce

1. Create a role with id `roleX`
2. Create a role with id `roleX-roleY`
3. Create a user with username `roleY`
4. Assign `roleX` to the user `roleY`. The id of the membership document becomes `roleX-roleY`. This conflicts with the role create in step 2 and thus that role gets overridden in favor of the membership.

### Current behavior

Documents can override each other.

### Expected behavior

Documents shouldn't override each other.

### Environment

SaaS & SM

### Version

8.8

### Rootcause

We use the user-inputted username and role id as ids for the documents.

### Solution ideas

Add a prefix to the document ids. Creating `roleX` would get the id `<role>roleX`, the user membership would become `<member>roleX-username`

I jsut randomly chose prefixes here. I didn't think it through at all.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

https://camunda.slack.com/archives/C05QBRGMA9F/p1747647698076559

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Ensure that Identity-related IDs provided by users are unique when persisted to secondary storage.

ℹ️ Note: I didn't add any new tests for this change as we extensively test the Tenant, Role, and Group APIs in the QA acceptance tests suite. Both retrieval by ID, as well as searching member entities are tested.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #32252

### CODE REVIEW

**Comment by koevskinikola** [comment]
Hey @remcowesterhoud do you have time to review this one?

File: webapps-schema/src/main/java/io/camunda/webapps/schema/entities/usermanagement/EntityJoinRelation.java [hunk 1]
```diff
@@ -7,9 +7,9 @@
  */
 package io.camunda.webapps.schema.entities.usermanagement;
 
-public record EntityJoinRelation<T>(String name, T parent) {
+public record EntityJoinRelation(String name, String parent) {
```
Comment (koevskinikola) [inline webapps-schema/src/main/java/io/camunda/webapps/schema/entities/usermanagement/EntityJoinRelation.java:10]: ℹ️ I de-generified this class as I noticed we always use String-based IDs and I don't think that will change in the future. Furthermore, the class is internal, so we can refactor the previous behavior in the future without much impact to users.

**Comment by remcowesterhoud** [comment]
Yes, I'll do it after the Identity demo. Be aware that I'll be FTO next week so if there's another iteration you'll likely need to find someone else

**Review by remcowesterhoud — APPROVED** [review]
Nothing to add. Thanks for the descriptive commtis. This made it really easy to review this one 🚀
