### PR TITLE
fix: Fire timer start events immediately when cycle start date is in the past

### LINKED ISSUE #38987: Timer Start events with a time cycle and start date in the past will not be executed on deployment
### 

### 

### 

### 

### Description

When deploying a process model with a timer start event have a time cycle like `R3/2022-04-27T17:20:00Z/PT10M`, it doesn't get executed right now, as I expect.

The first process instance gets created 10 minutes after deployment.

Some background and first analysis on this Slack thread by @tmetzke: https://camunda.slack.com/archives/C08MRKHJ0CD/p1759217287978929

### Steps to reproduce

Deploy this process model: 

[Timer immediate start test.bpmn.txt](https://github.com/user-attachments/files/22640836/Timer.immediate.start.test.bpmn.txt)

### Current behavior

The first process instance gets created after the first cycle.

### Expected behavior

The first process instance is created directly after deployment, as the start date is in the past. 

### Workaround

Add another timer start event with a date in the past. This will be started directly after deployment, as the start date is in the past.

### Environment

SaaS & SM

### Version

Zeebe 8.7 gen10.

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by ce-dmelnych**
### Problem

Timer start events with a time cycle that includes a past start date (e.g. `R3/2022-04-27T17:20:00Z/PT10M`) were not firing on deployment. Instead, the first instance was created one full interval later — 10 minutes after deployment in the example above.

### Root cause

`Interval.toEpochMilli(long fromEpochMilli)` used a single `epochMilli <= fromEpochMilli` condition to handle two structurally different cases together:

1. **An explicit start date that is in the past** — the cycle expression contains a concrete start date
(e.g. `2022-04-27T17:20:00Z`) that has already passed by the time the process is deployed.
2. **No start date at all** — a relative interval like `R1/PT10M`, or the duration-from-epoch encoding used internally by `TimeDateTimer`.

When a past start date was present, `epochMilli` (the 2022 timestamp) was correctly less than `fromEpochMilli` (today), so the condition was true. But the code then applied the **no-start-date** logic: `fromEpochMilli + duration.toMillis()`, scheduling the first firing one full interval in the future rather than immediately.

```java
// old — conflates "past start date" with "no start date"
final long epochMilli = start.map(...).orElse(fromEpochMilli);
if (epochMilli <= fromEpochMilli) {
    return fromEpochMilli + getDuration().toMillis(); // wrong for past start
}
return epochMilli;
```

### Fix

Split the logic on `start.isPresent()`, cleanly separating the two cases:

```java
// new — explicit start date handled independently
if (start.isPresent()) {
    final long startEpochMilli = start.get().toInstant().toEpochMilli();
    // Past start date means the timer is already overdue — fire immediately.
    return Math.max(startEpochMilli, fromEpochMilli);
}
// No explicit start date — compute relative to fromEpochMilli (unchanged).
if (!isCalendarBased()) {
    return fromEpochMilli + getDuration().toMillis();
}
return ZonedDateTime.ofInstant(...).plus(this)...toEpochMilli();
```

Key points:
- **`Math.max(startEpochMilli, fromEpochMilli)`** — returns `fromEpochMilli` when the start date is in the past (fire immediately), and `startEpochMilli` when it is at or after now (wait for the declared start). The result is always `>= fromEpochMilli`, so a past start can never schedule a timer before the current clock.
- **Subsequent firings are unaffected.** After each trigger, `TimerTriggerProcessor` calls `interval.withStart(Instant.ofEpochMilli(dueDate))`, which sets a new start to `previousDueDate + interval`. That new start is always in the future, so it takes the `startEpochMilli > fromEpochMilli` path and is returned as-is — preserving correct spacing between cycles.
- **No-start-date paths are unchanged.** The `!isCalendarBased()` and calendar-based branches are only reached when `start` is absent, so `TimeDateTimer` (which calls `toEpochMilli(0)` with a duration-encoded date) and plain relative cycles like `R1/PT1S` continue to work exactly as before.

## Checklist
- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues
closes #38987

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java [hunk 1]
```diff
@@ -854,6 +854,145 @@ public void shouldTriggerIfTimeDatePassedOnDeployment() {
...
+    final long now = engine.getClock().getCurrentTimeInMillis();
+
+    // then — 1st timer is due immediately (due date <= now at deployment time)
+    final TimerRecordValue createdTimer =
+        RecordingExporter.timerRecords(TimerIntent.CREATED)
+            .withProcessDefinitionKey(processDefinitionKey)
+            .getFirst()
+            .getValue();
+
+    assertThat(createdTimer.getDueDate()).isLessThanOrEqualTo(now);
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java]: :x: There's a race condition here between the deployment creating the timer (in one thread) and the test thread asking for the clock's time. It's not certain which succeeds first. If the current time retrieval succeeds first, the assertion will still succeed, but is it clear what we are comparing?

I believe the current time is not used in the correct way. The assertion should verify that the created timer's due date is not the specified due date in the process (`2022-04-27T17:20:00Z`) but rather the current time. We can verify this safely by:
- First retrieving the current time
- Then deploying and verifying that the due date is later than the previously retrieved current time

```java
assertThat(createdTimer.getDueDate())
    .describedAs(
        "Expect timer with start date in the past to be scheduled 'now' (or shortly after)")
    .isBetween(now, now + Duration.ofMinutes(1).toMillis());
```

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java [hunk 2]
```diff
@@ -854,6 +854,145 @@ public void shouldTriggerIfTimeDatePassedOnDeployment() {
...
+
+    // and — 1st process instance is triggered without advancing the clock
+    final long firstDueDate =
+        RecordingExporter.timerRecords(TimerIntent.TRIGGERED)
+            .withProcessDefinitionKey(processDefinitionKey)
+            .getFirst()
+            .getValue()
+            .getDueDate();
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java]: 🔧 There's no assertion on the time of the triggered timer. For completeness, I think we should assert it here. I think it should be the same value as the due date in the `createdTimer` above:

```java
assertThat(firstDueDate)
    .describedAs("Expect triggered timer to still reflect the initial due date")
    .isEqualTo(createdTimer.getDueDate());
```

🔧 You could also verify that the `timestamp` of this record is 'now' (or shortly after)

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java [hunk 3]
```diff
@@ -854,6 +854,145 @@ public void shouldTriggerIfTimeDatePassedOnDeployment() {
...
+
+    Assertions.assertThat(
+            RecordingExporter.timerRecords(TimerIntent.TRIGGERED)
+                .withProcessDefinitionKey(processDefinitionKey)
+                .getFirst()
+                .getValue())
+        .hasTargetElementId("start")
+        .hasElementInstanceKey(TimerInstance.NO_ELEMENT_INSTANCE)
+        .hasTenantId(TenantOwned.DEFAULT_TENANT_IDENTIFIER);
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java]: 🔧 This is a duplicate retrieval of the TRIGGERED event which slows down the test ever so slightly. Consider deduplicating this lookup.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java [hunk 4]
```diff
@@ -854,6 +854,145 @@ public void shouldTriggerIfTimeDatePassedOnDeployment() {
...
+            .getFirst()
+            .getValue()
+            .getDueDate();
+
+    assertThat(secondDueDate).isEqualTo(firstDueDate + Duration.ofMinutes(10).toMillis());
+
+    // when — advance for the 3rd (and final) firing
+    engine.increaseTime(Duration.ofMinutes(10));
+
+    // then — 3rd timer is spaced PT10M from the 2nd; no 4th timer created (R3 exhausted)
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java:925]: 🔧 Consider adding a final assertion using `RecordingExporter.expectNoMatchingRecords` to verify that indeed no 4th timer is created

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/util/time/Interval.java [hunk 5]
```diff
@@ -76,12 +76,9 @@ public Optional<ZonedDateTime> getStart() {
...
     if (start.isPresent()) {
-      final long epochMilli = start.get().toInstant().toEpochMilli();
-      if (epochMilli < fromEpochMilli) {
-        // Start date is strictly in the past: the timer is already overdue, fire immediately.
-        return fromEpochMilli;
-      }
-      return epochMilli;
+      final long startEpochMilli = start.get().toInstant().toEpochMilli();
+      // If the start date is in the past the timer is already overdue, so fire immediately.
+      return Math.max(startEpochMilli, fromEpochMilli);
```
Comment (korthout) [inline zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/util/time/Interval.java]: 👍 Nice one!

**Review by korthout — CHANGES_REQUESTED** [review]
Nice work @ce-dmelnych! 

🔧 I'd like to see some improvements to the tests to ensure this behaves as expected!

However, the fix looks good to me!

LGTM 👍

**Review by korthout — APPROVED** [review]
Sorry, meant to approve

**Comment by ce-dmelnych** [comment]
@korthout thank you for your review and nice suggestions!

I've addressed all your feedback in [this commit](https://github.com/camunda/camunda/pull/49135/changes/c4f5b548688b0982946329bad1a68fea1709d01d). Could you please take another look? 🙏

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java [hunk 6]
```diff
@@ -854,6 +854,145 @@ public void shouldTriggerIfTimeDatePassedOnDeployment() {
...
+                        .withProcessDefinitionKey(processDefinitionKey)
+                        .skip(3)
+                        .exists()))
+        .describedAs("Expect no more timer events to be created after R3 cycle is exhausted")
+        .isFalse();
+  }
+
+  @Test
+  public void shouldTriggerInfiniteCycleImmediatelyWhenStartDateIsInThePast() {
+    // given — infinite cycle (R/) whose start date is in the past
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java:951]: Sorry @ce-dmelnych I should've pointed this out prior, but this test has the same issues as the previous one

Comment (ce-dmelnych) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerStartEventTest.java:951]: Oh, no worries @korthout, my bad for not catching it myself!
I've applied improvements and included them in the [amended commit](https://github.com/camunda/camunda/pull/49135/changes/c4f5b548688b0982946329bad1a68fea1709d01d). 🙏

**Review by korthout — APPROVED** [review]
Thanks @ce-dmelnych 

LGTM 👍
