### PR TITLE
fix(gateway): fix NPE related to cluster state supplier

### LINKED ISSUE #7018: NPE in StandaloneGateway
**Describe the bug**
Observed in production logs: https://console.cloud.google.com/errors/CNL3hp_Fn5TcUA?service=zeebe-gateway&version=medic-cw-16-bb2064273-benchmark&time=P30D&project=zeebe-io

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```

java.lang.NullPointerException: null

        at io.zeebe.gateway.StandaloneGateway.lambda$new$1 (StandaloneGateway.java:52)
        at io.zeebe.gateway.impl.SpringGatewayBridge.getClusterState (SpringGatewayBridge.java:44)
        at io.zeebe.gateway.impl.probes.health.PartitionLeaderAwarenessHealthIndicator.health (PartitionLeaderAwarenessHealthIndicator.java:33)
        at io.zeebe.util.health.DelayedHealthIndicator.checkHealth (DelayedHealthIndicator.java:68)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (Unknown Source)
        at java.lang.reflect.Method.invoke (Unknown Source)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run (ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run (DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call (Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset (Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker (Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run (Unknown Source)
        at java.lang.Thread.run (Unknown Source)
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version/Configuration: medic-cw-16-bb2064273-benchmark

### PR DESCRIPTION
**Pull request by pihme**
## Description

Fix NPE in cluster state supllier

## Related issues

closes #7018 

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: gateway/src/main/java/io/camunda/zeebe/gateway/impl/SpringGatewayBridge.java [hunk 1]
```diff
@@ -41,7 +42,7 @@ public void registerClusterStateSupplier(Supplier<BrokerClusterState> clusterSta
 
   public Optional<BrokerClusterState> getClusterState() {
     if (clusterStateSupplier != null) {
-      return Optional.ofNullable(clusterStateSupplier.get());
+      return clusterStateSupplier.get();
     } else {
       return Optional.empty();
     }
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/impl/SpringGatewayBridge.java:48]: Nit: it looks like we're duplicating the optional behavior. Why not reuse it:

```java
return Optional.ofNullable(clusterStateSupplier).map(Supplier::get);
```

**Review by npepinpe — APPROVED** [review]
:rocket: 

Just some nits, nothing major:

- Would be nice next time if you quickly summarize the change in the PR or in the commit, e.g. "NPE was thrown because X/Y/Z; migrated the method to return an Optional as this is an expected case due to asynchronous startup", it makes reviewing simpler.
