### PR TITLE
Remove maxSnapshotCount config setting

### LINKED ISSUE #3889: Moving valid snapshot fails with zero maxSnapshotCount
**Describe the bug**

With using max snapshot count zero I seeing exceptions on moving valid snapshots.

```
I 2020-02-20T14:23:10.262324650Z 2020-02-20 14:23:10.262 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 17785461840704 is committed, current commit position is 17785461848800. After that snapshot can be marked as valid.
 
I 2020-02-20T14:23:10.384128523Z 2020-02-20 14:23:10.382 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-3] ERROR io.zeebe.logstreams.snapshot - Unexpected exception occurred on moving valid snapshot.
 
I 2020-02-20T14:23:10.384162668Z java.lang.IllegalArgumentException: -1
	at java.util.stream.ReferencePipeline.skip(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.onNewSnapshot(AtomixSnapshotStorage.java:160) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.lambda$put$0(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:222) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.newSnapshot(DbSnapshotStore.java:130) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.commitSnapshot(AtomixSnapshotStorage.java:95) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.SnapshotStorage.commitSnapshot(SnapshotStorage.java:48) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.commitSnapshot(StateSnapshotController.java:67) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$onCommitCheck$4(AsyncSnapshotDirector.java:177) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-02-20T14:23:10.968051307Z 2020-02-20 14:23:10.967 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Created snapshot for Broker-2-StreamProcessor-3
 
I 2020-02-20T14:23:10.968227659Z 2020-02-20 14:23:10.967 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 14675905108864 is committed, current commit position is 14675905108864. After that snapshot can be marked as valid.
 
I 2020-02-20T14:23:11.133494304Z 2020-02-20 14:23:11.132 [Broker-2-SnapshotDirector-3] [Broker-2-zb-fs-workers-2] ERROR io.zeebe.logstreams.snapshot - Unexpected exception occurred on moving valid snapshot.
 
I 2020-02-20T14:23:11.133525097Z java.lang.IllegalArgumentException: -1
	at java.util.stream.ReferencePipeline.skip(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.onNewSnapshot(AtomixSnapshotStorage.java:160) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.lambda$put$0(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:222) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.newSnapshot(DbSnapshotStore.java:130) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.commitSnapshot(AtomixSnapshotStorage.java:95) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.SnapshotStorage.commitSnapshot(SnapshotStorage.java:48) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.state.StateSnapshotController.commitSnapshot(StateSnapshotController.java:67) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$onCommitCheck$4(AsyncSnapshotDirector.java:177) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 
I 2020-02-20T14:23:12.222074479Z 2020-02-20 14:23:12.221 [] [raft-server-2-raft-partition-partition-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.spi.JavaValueMapper@156a2374)), function-provider: org.camunda.feel.interpreter.FunctionProvider$EmptyFunctionProvider$@69c9fc23]
 
I 2020-02-20T14:23:12.222905305Z 2020-02-20 14:23:12.222 [] [raft-server-2-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - The last processed position for snapshot /usr/local/zeebe/data/raft-partition/partitions/1/pending/7581936-1-1582208589431 is 17828415826080
 
I 2020-02-20T14:23:12.239152342Z 2020-02-20 14:23:12.237 [] [raft-server-2-raft-partition-partition-1] ERROR io.atomix.protocols.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Failed to commit pending snapshot DbPendingSnapshot{index=7581936, term=1, timestamp=2020-02-20 02:23:09,431, directory=/usr/local/zeebe/data/raft-partition/partitions/1/pending/7581936-1-1582208589431}, rolling back
 
I 2020-02-20T14:23:12.239220211Z java.lang.IllegalArgumentException: -1
	at java.util.stream.ReferencePipeline.skip(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage.onNewSnapshot(AtomixSnapshotStorage.java:160) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.lambda$put$0(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:196) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.put(DbSnapshotStore.java:222) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore.newSnapshot(DbSnapshotStore.java:143) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbPendingSnapshot.commit(DbPendingSnapshot.java:114) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.atomix.protocols.raft.roles.PassiveRole.onInstall(PassiveRole.java:306) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.roles.FollowerRole.onInstall(FollowerRole.java:81) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$null$10(RaftContext.java:218) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$runOnContext$33(RaftContext.java:255) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200214.153010-125.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-02-20T14:23:12.247462006Z 2020-02-20 14:23:12.239 [] [raft-server-2-raft-partition-partition-1] WARN  io.zeebe.broker.clustering.atomix.storage.snapshot.DbPendingSnapshot - Failed to delete pending snapshot DbPendingSnapshot{index=7581936, term=1, timestamp=2020-02-20 02:23:09,431, directory=/usr/local/zeebe/data/raft-partition/partitions/1/pending/7581936-1-1582208589431}
 
I 2020-02-20T14:23:12.247505472Z java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/7581936-1-1582208589431
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at io.zeebe.util.FileUtil.deleteFolder(FileUtil.java:41) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbPendingSnapshot.abort(DbPendingSnapshot.java:120) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.atomix.protocols.raft.roles.PassiveRole.abortPendingSnapshot(PassiveRole.java:521) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.roles.PassiveRole.onInstall(PassiveRole.java:314) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.roles.FollowerRole.onInstall(FollowerRole.java:81) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$null$10(RaftContext.java:218) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$runOnContext$33(RaftContext.java:255) ~[atomix-raft-3.2.0-20200214.153120-125.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200214.153010-125.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-02-20T14:23:12.248386380Z 2020-02-20 14:23:12.247 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.protocols.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - Failed to install 2
 
I 2020-02-20T14:23:12.684790704Z 2020-02-20 14:23:12.684 [] [raft-server-0-raft-partition-partition-3] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.spi.JavaValueMapper@5be3bbf8)), function-provider: org.camunda.feel.interpreter.FunctionProvider$EmptyFunctionProvider$@4b1d46bc]
 

```

Actually I'm not 100% sure what I would expect by this setting. Probably that it is either not allowed to set it to zero **OR** it does not create any snapshots. But currently it takes snapshots and fails on moving them, which is not nice and unexpected.

### PR DESCRIPTION
**Pull request by korthout**
## Description

This PR removes the maxSnapshotCount configuration setting from the
DataCfg. From now on we can assume there is always only a maximum of 1
snapshot present at any time.

## Related issues

closes #3889

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java [hunk 1]
```diff
@@ -606,16 +610,40 @@ public File getSnapshotsDirectory(final Broker broker) {
...
+          if (files == null || files.length == 0) {
+            return false;
+          }
+          final Optional<DbSnapshotMetadata> latestSnapshot =
+              Arrays.stream(files)
+                  .map(File::toPath)
+                  .map(DbSnapshotMetadata::ofPath)
+                  .flatMap(Optional::stream)
+                  .max(Comparator.naturalOrder());
+          if (previousSnapshot != null
```
Comment (Zelldon) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: I think this would work also if the latest is the same as the previous right? It then returns and I think it is a bit misleading that it says `waitForNew..` ?

File: broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java [hunk 2]
```diff
@@ -146,6 +143,8 @@ public void onNewSnapshot(
     metrics.incrementSnapshotCount();
     observeSnapshotSize(snapshot);
 
+    // todo: simplify now that maxSnapshotCount can only be 1
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java]: Please create a separate issue for this todo and the best would be also to reference it in the todo

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Thanks @korthout small things

File: broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java (hunk 2 above)
Comment (korthout) [reply broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java]: Will do 👍

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java (hunk 1 above)
Comment (korthout) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: No that is not correct. Either `previousSnapshot` is null, in which case it is enough to just find a snapshot. Or `previousSnapshot` is not null, in which case `latestSnapshot.map(previousSnapshot::compareTo).orElse(0)` needs to be `-1`. The compareTo will return 0 if the `previousSnapshot` and the `latestSnapshot` are the same.
I've tried an early return (with exceptional cases first) approach to this method. So only in the last return `return true` it will have actually found something and stop waiting.

Comment (Zelldon) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]:
```
latestSnapshot.map(previousSnapshot::compareTo).orElse(0)
```

Is translated to:

```
if (latestSnapshot != null)
{

  return latestsnapshot.compareTo(previousSnapshot); // return 1 when latest bigger, 0 when equal, -1 when smaller
}
return 0;
```

Or is it `previousSnapshot.compareTo(latestSnapshot)` ? :sweat_smile:

Comment (korthout) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: It's actually: `latestSnapshot.map(latestSnapshot -> previousSnapshot.compareTo(latestSnapshot)).orElse(0)`

Comment (korthout) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: So, 
if latest is empty, the result 0. 
If previous is before latest, the result is -1.
If previous is the same as latest, the result is 0.
If previous is after latest, the result is 1.

Comment (korthout) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: Only the case where previous is before the latest (or in other words, the latest is actually the newest), then it stops waiting

Comment (Zelldon) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: Ok sorry I get it now. As you can see it was for me not easy to understand :sweat_smile:  I always find this streaming api and compare a bit confusing :sweat_smile: But might be just me. If it is actually previousSnapshot.compareTo(latestSnapshot) then yes it makes sense otherwise it would not :sweat_smile:

Comment (korthout) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: Yeah, streaming api can be confusing (just remember that it is a method reference, so in this case it will apply the provided method with the values in the Optional/Stream as argument). 

I have to add that I also wrote it a little confusing, but I wanted to maintain a return early approach. Perhaps I can have another look at it, to make it less confusing.

Comment (korthout) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: @Zelldon Would this be more readable?
```
final File[] files = snapshotsDir.listFiles();
if (files == null || files.length == 0) {
  return false;
}
final Optional<DbSnapshotMetadata> latestSnapshot =
    Arrays.stream(files)
        .map(File::toPath)
        .map(DbSnapshotMetadata::ofPath)
        .flatMap(Optional::stream)
        .max(Comparator.naturalOrder());
if (latestSnapshot.isEmpty()) {
  return false;
}
if (previousSnapshot != null && previousSnapshot.compareTo(latestSnapshot.get()) > -1) {
  return false;
}
// latestSnapshot is newer than previousSnapshot (or previous is null)
referenceToResult.set(latestSnapshot);
return true;
```

File: broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java [hunk 3]
```diff
@@ -142,31 +139,17 @@ public SnapshotMetrics getMetrics() {
...
-        final var converted = optionalConverted.get();
-        deletionListeners.forEach(listener -> listener.onSnapshotsDeleted(converted));
-      }
+    LOGGER.info("Purging snapshots older than {}", snapshot);
+    store.purgeSnapshots(snapshot);
+
+    final var optionalConverted = toSnapshot(snapshot.getPath());
+    if (optionalConverted.isPresent()) {
+      final var converted = optionalConverted.get();
+      // TODO #4067(@korthout): rename onSnapshotsDeleted, because it doesn't always delete
```
Comment (korthout) [inline broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java]: Created #4067 for this

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java (hunk 1 above)
Comment (Zelldon) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: Yes I think it is easier from my point of view

File: broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java (hunk 3 above)
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java]: nice thanks

File: broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java [hunk 4]
```diff
@@ -142,31 +139,17 @@ public SnapshotMetrics getMetrics() {
...
-          snapshots.size(),
-          oldest);
-      store.purgeSnapshots(oldest);
-
-      final var optionalConverted = toSnapshot(oldest.getPath());
-      if (optionalConverted.isPresent()) {
-        final var converted = optionalConverted.get();
-        deletionListeners.forEach(listener -> listener.onSnapshotsDeleted(converted));
-      }
+    LOGGER.info("Purging snapshots older than {}", snapshot);
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java]: Probably debug level is enough here

Comment (korthout) [reply broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java]: Where would we normally draw the line between info and debug?

File: docs/src/operations/resource-planning.md [hunk 5]
```diff
@@ -9,58 +9,57 @@ While we cannot tell you exactly what you need - beyond _it depends_ - we can ex
...
+An event log segment is not deleted until all the events in it have been exported by all configured exporters. This means that exporters that rely on side-effects, perform intensive computation, or experience back pressure from external storage will cause disk usage to grow, as they delay the deletion of event log segments.
 
 Exporting is only performed on the partition leader, but the followers of the partition do not delete segments in their replica of the partition until the leader marks all events in it as unneeded by exporters.
 
-No event log segments are deleted until the maximum number of snapshots has been reached. When the maximum number of snapshots has been reached, the event log is truncated up to the oldest snapshot.
+No event log segments are deleted until a snapshot has been taken that includes that log segment. When a snapshot has been taken, the event log is truncated up to that point.
```
Comment (Zelldon) [inline docs/src/operations/resource-planning.md]: > No event log segments are deleted until a snapshot has been taken that includes that log segment

sounds a bit weird

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
I like the changes just have more comments especially for docs part. I think truncates conflict a bit the truncate terminology in raft. I would like to avoid that.

File: broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java (hunk 4 above)
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java]: I think it is often not easy to decide. But maybe it helps to think from the user point of view. Does he needs to know it? What is the benefit or what can he do with this knowledge? Maybe also if we keep it on info the more context would be interesting. which dirs have been deleted

**Comment by pihme** [comment]
Just wanted to make you aware of https://github.com/zeebe-io/zeebe/pull/4025 where I also worked on the resource planning section and mentioning the max snapshot settings.
I think we should coordinate our merges and make sure that after both are merged, it still makes sense

**Comment by korthout** [comment]
@pihme Thanks for the heads-up. I think it's easiest to merge the changes once they are in a more or less finished state. Let me know when you're reaching that point on that PR and I'll do the same.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java (hunk 1 above)
Comment (korthout) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java]: Ok, changed it.

File: broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java (hunk 4 above)
Comment (korthout) [reply broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/AtomixSnapshotStorage.java]: Agreed. At this location it is not that interesting because purging does not necessarily mean that a snapshot was deleted. This is to be tackled in #4067. I've changed it to debug level now.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 657c1e5b69b398a7b6f832428b7e08065f5f8d54
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 657c1e5b69b398a7b6f832428b7e08065f5f8d54
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

File: docs/src/operations/resource-planning.md [hunk 6]
```diff
@@ -9,58 +9,57 @@ While we cannot tell you exactly what you need - beyond _it depends_ - we can ex
 All Brokers in a partition use disk space to store:
 
 - The event log for each partition they participate in. By default, this is a minimum of 512MB for each partition, incrementing in 512MB segments. The event log is truncated on a given broker when data has been processed and successfully exported by all loaded exporters.
-- One or more periodic snapshots of the running state (inflight data) of each partition (unbounded, based on in-flight work). The number of snapshots to retain, and their frequency is configurable. By default it is set to three snapshots retained, and a snapshot [every 15 minutes](https://github.com/zeebe-io/zeebe/blob/cca5aeda4bd9d7e7e83f68d221bbf1a3e4d0f000/dist/src/main/config/zeebe.cfg.toml#L145).
+- One or more periodic snapshots of the running state (inflight data) of each partition (unbounded, based on in-flight work). The frequency of snapshots to retain is configurable. By default it is set to a snapshot [every 15 minutes](https://github.com/zeebe-io/zeebe/blob/cca5aeda4bd9d7e7e83f68d221bbf1a3e4d0f000/dist/src/main/config/zeebe.cfg.toml#L145).
```
[the remark this answers is not in the document]
Comment (korthout) [reply docs/src/operations/resource-planning.md]:
```suggestion
- A snapshot of the running state (inflight data) of each partition (unbounded, based on in-flight work). The frequency of snapshots to retain is configurable. By default it is set to a snapshot [every 15 minutes](https://github.com/zeebe-io/zeebe/blob/cca5aeda4bd9d7e7e83f68d221bbf1a3e4d0f000/dist/src/main/config/zeebe.cfg.toml#L145).
```

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 657c1e5b69b398a7b6f832428b7e08065f5f8d54
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 80eb31029ff16914ff77016dbb5ae9903985a458
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

File: docs/src/operations/resource-planning.md (hunk 5 above)
Comment (korthout) [reply docs/src/operations/resource-planning.md]: The original line reads to me as 'don't worry about your data being deleted too early'.  I've tried to capture that again. Perhaps it should just start like: 
```suggestion
We make sure that event log segments are not deleted too early. No event log segments are deleted until a snapshot has been taken that includes that segment. When a snapshot has been taken, the event log is only deleted up to that point.
```

Comment (Zelldon) [reply docs/src/operations/resource-planning.md]: > No event log segments are deleted until a snapshot has been taken that includes that segment

Maybe:

No event log segment is deleted until a snapshot has been taken that includes that segment.

Comment (korthout) [reply docs/src/operations/resource-planning.md]: That's better. So like:
```suggestion
We make sure that event log segments are not deleted too early. No event log segment is deleted until a snapshot has been taken that includes that segment. When a snapshot has been taken, the event log is only deleted up to that point.
```

Comment (Zelldon) [reply docs/src/operations/resource-planning.md]: I think this is better thanks

File: docs/src/operations/resource-planning.md (hunk 6 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply docs/src/operations/resource-planning.md]: yes

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 657c1e5b69b398a7b6f832428b7e08065f5f8d54
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 80eb31029ff16914ff77016dbb5ae9903985a458
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 2378faa3174522bd5acd81ca2666cf71864a829f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 657c1e5b69b398a7b6f832428b7e08065f5f8d54
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 80eb31029ff16914ff77016dbb5ae9903985a458
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 2378faa3174522bd5acd81ca2666cf71864a829f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by Zelldon** [comment]
You can btw change the commit msg on applying review hints then gitcop will not complain about the wrong commit messages :sweat_smile:

**Review by ChrisKujawa — APPROVED** [review]
Thanks nico :+1: 

Could you please remove before merging the following maxSnapshot occurrences:

```
[zell zeebe/ ns:operate]$ ag maxSnapshot
dist/src/main/config/zeebe.cfg.yaml
190:      # maxSnapshots: 3

broker/src/test/resources/system/default.yaml
190:      # maxSnapshots: 3
```

**Comment by pihme** [comment]
@korthout My PR is close to finished. But I have only doc changes no code, so I would suggest you merge first.

**Comment by korthout** [comment]
@pihme Thanks will do.
