### PR TITLE
fix: use distinct properties for incident alert version and tag

### LINKED ISSUE #42555: Add processVersionTag field
# Description

In Camunda 8.8, the `processVersion` field in alerts sent to the webhook via the `IncidentNotifier` has been changed, now it will be the value of the process version tag if it is not null. 

This should be reverted, `processVersion` should work the same as 8.7 and `processVersionTag` should be a new field added.

## Links
https://jira.camunda.com/browse/SUPPORT-30599

### PR DESCRIPTION
**Pull request by RomanJRW**
## Description

We previously prioritised using the version tag in the incident alert, but this was an unintended regression. This PR sets distinct properties for both the process version and the process version tag.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #42555

### CODE REVIEW

**Review by houssain-barouni — APPROVED** [review]
LGTM!
I suppose we need to notify the customer that has implemented a workaround for this regression, so that they remove this workaround before upgrading

**Comment by RomanJRW** [comment]
I just realised that we [document](https://docs.camunda.io/docs/components/console/manage-clusters/manage-alerts/#webhook-alerts) the `processVersion` field as a number but it's actually a string 🤔 

We could:
- Change this to a number again:
  - This would be consistent with 8.7 behaviour
  - We would need to document the breaking change between patch versions somewhere
- Update the documentation to show that it is now a string
  - This is a breaking change for 8.7 -> 8.8 and would need to be documented

My proposal would be to go for the first option and favour consistency with older <8.8 versions. @houssain-barouni - do you agree?

Whatever the decision, we should inform the customer that the workaround can be removed, good point 👍

**Comment by houssain-barouni** [comment]
> I just realised that we [document](https://docs.camunda.io/docs/components/console/manage-clusters/manage-alerts/#webhook-alerts) the `processVersion` field as a number but it's actually a string 🤔
> 
> We could:
> 
> * Change this to a number again:
>   
>   * This would be consistent with 8.7 behaviour
>   * We would need to document the breaking change between patch versions somewhere
> * Update the documentation to show that it is now a string
>   
>   * This is a breaking change for 8.7 -> 8.8 and would need to be documented
> 
> My proposal would be to go for the first option and favour consistency with older <8.8 versions. @houssain-barouni - do you agree?
> 
> Whatever the decision, we should inform the customer that the workaround can be removed, good point 👍

It think we should serialize it as integer as before, I don't know why it is inserted in the process cache as String 🤔 
There is something else we need to consider, [CachedProcessEntity](https://github.com/camunda/camunda/blob/6d0fb341bdd9f00299946e350c212c79b256b00f/zeebe/exporter-common/src/main/java/io/camunda/zeebe/exporter/common/cache/process/CachedProcessEntity.java#L19-L25) has a constructor that sets version to null, and this one seems to be widely used
I think we should:
1. turn version to integer
2. make sure to always provide it, I think it should be always available when caching the process entities

**Comment by RomanJRW** [comment]
Docs will be handled in https://github.com/camunda/camunda-docs/pull/7600

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/cache/ProcessCacheImplIT.java [hunk 1]
```diff
@@ -109,7 +109,7 @@ void shouldLoadProcessEntityFromBackend(final ProcessCacheArgument processCacheA
     expectedFlowNodesMap.put(startEventId, null);
     final var expectedCachedProcessEntity =
         new CachedProcessEntity(
-            "test", "v1", List.of("Banana", "Cherry", "apple"), expectedFlowNodesMap);
+            "test", 0, "v1", List.of("Banana", "Cherry", "apple"), expectedFlowNodesMap);
```
Comment (houssain-barouni) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/cache/ProcessCacheImplIT.java]: 🧪 can we set in the test a value for the version that is different from the `0` default value, to ensure that is correctly propagated to the cached process entity?

**Review by houssain-barouni — APPROVED** [review]
LGTM! 👍 
I had one comment regarding one unit test
