### PR TITLE
Yield actor thread between retries

### LINKED ISSUE #10539: RetryStrategies do not yield
**Describe the bug**

Previously we had implemented the ActorRetryStrategies with Actor#runUntilDone this was replaced with  https://github.com/camunda/zeebe/pull/9850 we realized that Actor#submit is not optimal and replaced it with Actor#run again https://github.com/camunda/zeebe/pull/10289, but we missed to add an Actor#yield if we want to retry (and loop).
https://github.com/camunda/zeebe/blob/main/scheduler/src/main/java/io/camunda/zeebe/scheduler/retry/AbortableRetryStrategy.java#L47

This is necessary since otherwise we would loop endless with the same Actor, without getting any other Actor to give a chance to run. This is especially an issue if we have only one thread. 

Important is this if we write to dispatcher and the LogStorageAppender has to clean the dispatcher.

Was found in investigating https://github.com/camunda/zeebe/issues/10526

**To Reproduce**
Use the RetryStrategy you will see that it doesn't yield.

**Expected behavior**
Give others actors an chance to run.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.x
- Configuration:

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

Ensures retry strategies are yielding their thread between retries. Note that this doesn't really apply to the `BackOffRetryStrategy`, as it's already yielding via its usage of timers.

This PR also updates the `RetryStrategyTest` to junit 5, and adds test coverage by applying the existing tests to the other strategies where applicable (previously, only the `RecoverableRetryStrategy` and `AbortableRetryStrategy` were tested there).

## Related issues

closes #10539 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
As discussed, the `BackOffRetryStrategy` relies on the caller to prevent interleaving. I didn't change this here, but it's more explicit since we document that we're not testing that. If we want to do this, it shouldn't be too hard, but we'll have to buffer the execution as part of the strategy. I figured that was out of scope here.

File: scheduler/src/test/java/io/camunda/zeebe/scheduler/retry/RetryStrategyTest.java [hunk 1]
```diff
@@ -12,140 +12,128 @@
...
-      final Constructor<RetryStrategy> constructor =
-          retryStrategyClass.getConstructor(ActorControl.class);
-      retryStrategy = constructor.newInstance(actorControl);
-    } catch (final Exception e) {
-      throw new RuntimeException(e);
-    }
+  /** Ensure we use a single thread to better control the scheduling in the tests. */
+  @RegisterExtension
+  private final ControlledActorSchedulerExtension schedulerRule =
+      new ControlledActorSchedulerExtension(
```
Comment (deepthidevaki) [inline scheduler/src/test/java/io/camunda/zeebe/scheduler/retry/RetryStrategyTest.java:33]: :+1:

**Review by deepthidevaki — APPROVED** [review]
:rocket: As you said, I don't think we have to ensure BackoffStrategy doesn't interleave tasks. :+1:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
> The self-hosted runner: actions-runner-16-n5tz8-7chz2 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error. 

:')

bors r+
