### PR TITLE
fix(topology): maintain gossip state update ordering

### LINKED ISSUE #15231: ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 
  - Once so far.
- Does it block your work? 
  - Not really.
- Do we suspect that it is a real failure? 
  - Not sure.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Assertion condition [List check single element] 
Expecting actual:
  class BrokerState {
    id: 2
    state: ACTIVE
    version: 2
    lastUpdatedAt: 2023-11-16T09:13:32.135700584Z
    partitions: []
}
to match 'Broker 2 has partition 2' predicate within 10 seconds.
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted
/

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 28.37 s <<< FAILURE! -- in io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown
Error:  io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart -- Time elapsed: 28.37 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Assertion condition [List check single element] 
Expecting actual:
  class BrokerState {
    id: 2
    state: ACTIVE
    version: 2
    lastUpdatedAt: 2023-11-16T09:13:32.135700584Z
    partitions: []
}
to match 'Broker 2 has partition 2' predicate within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart(ScaleResiliencyTest.java:210)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)
	... 12 more
</pre>
</details>

[Test result archive](https://drive.google.com/file/d/1iVtdYDtFkpBmLCzvspbXvTVPADR4btf3/view?usp=drive_link) (internal drive link)

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Closes #15231

### CODE REVIEW

**Comment by oleschoenburg** [comment]
Ughhh, this doesn't work yet because the service can't orchestrate the shutdown of manager and gossiper actor services without being an actor itself...

File: scheduler/src/main/java/io/camunda/zeebe/scheduler/AsyncClosable.java [hunk 1]
```diff
@@ -17,5 +17,5 @@ public interface AsyncClosable {
    *
    * @return the future, which is completed when resources are closed
    */
-  ActorFuture<Void> closeAsync();
+  CompletableActorFuture<Void> closeAsync();
```
Comment (deepthidevaki) [inline scheduler/src/main/java/io/camunda/zeebe/scheduler/AsyncClosable.java:20]: :wrench: I would prefer to use the interface `ActorFuture` instead of the concrete implementation here.

File: scheduler/src/main/java/io/camunda/zeebe/scheduler/future/CompletableActorFuture.java [hunk 2]
```diff
@@ -278,6 +281,52 @@ public Throwable getException() {
...
+   * completion callbacks on a provided executor. As such, it should be used for orchestrating
+   * futures in a non-performance critical context, for example for startup and shutdown sequences.
+   *
+   * @param next function to apply to the result of this future.
+   * @param executor The executor used to handle completion callbacks.
+   * @return a new future that completes with the result of applying the function to the result of
+   *     this future or exceptionally if this future completes exceptionally. This future can be
+   *     used for further chaining.
+   */
+  public CompletableActorFuture<V> andThen(
```
Comment (deepthidevaki) [inline scheduler/src/main/java/io/camunda/zeebe/scheduler/future/CompletableActorFuture.java:306]: :wrench: A test for this would be nice.

**Review by deepthidevaki — APPROVED** [review]
:rocket: 

:x: My main concern is the change to use the concrete class `CompletableActorFuture` instead of the interface `ActorFuture`. I think it is better to add `andThen` in the interface. Please check this before merging.

File: scheduler/src/main/java/io/camunda/zeebe/scheduler/future/CompletableActorFuture.java [hunk 3]
```diff
@@ -278,6 +281,52 @@ public Throwable getException() {
     return failureCause;
   }
 
+  /**
+   * Convenience wrapper over {@link #andThen(Function, Executor)} for the case where the next step
+   * does not require the result of this future.
+   */
+  public CompletableActorFuture<V> andThen(
```
[the remark this answers is not in the document]
Comment (oleschoenburg) [reply scheduler/src/main/java/io/camunda/zeebe/scheduler/future/CompletableActorFuture.java]: I had this initially but I can't remember why I changed it back. Anyway, I moved things around so now everything is in the `ActorFuture` interface. The other implementation, `TestActorFuture` just throws `UnsupportedOperationException` for now.

**Comment by oleschoenburg** [comment]
bors merge
