### PR TITLE
fix(clients/go): retry job poll after token refresh

### LINKED ISSUE #5625: OAuth Token Refreshment in Go Client
**Describe the bug**
The go client does not automatically refresh the oauth2 token when it expires. The token refreshment is currently triggered in `OAuthCredentialsProvider.ShouldRetryRequest`. Since this method never gets executed during the client usage in the job poller the client never gets a refrehed token and all subsequent requests fail.

**To Reproduce**
- Create new client with OAuth
- Create a new JobWorker
- Run JobWorker until initially provided token expires

**Expected behavior**
The token shall be refreshed regardless of any checks for request retry.

**Environment:**
 - Zeebe Version: 0.24.4

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Adds retry/refresh logic to the job poller and activate command. It also adds a way to test streaming RPCs which we previously weren't doing. This adds a new parameter to the `NewJobWorkerBuilder` which breaks compatibility but it's probably not used by users.

## Related issues

closes #5625 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: clients/go/pkg/worker/jobPoller.go [hunk 1]
```diff
@@ -101,6 +113,18 @@ func (poller *jobPoller) activateJobs() {
 	}
 }
 
+func (poller *jobPoller) openStream(ctx context.Context) (pb.Gateway_ActivateJobsClient, error) {
+	stream, err := poller.client.ActivateJobs(ctx, poller.request)
+	if err != nil {
+		if poller.shouldRetry(ctx, err) {
+			return poller.openStream(ctx)
+		}
+		return nil, fmt.Errorf("Worker '%s' failed to open job stream due to error: %w", poller.request.Worker, err)
```
Comment (npepinpe) [inline clients/go/pkg/worker/jobPoller.go:122]: Why not use `errors.Wrapf`?

File: clients/go/pkg/worker/jobPoller_test.go [hunk 2]
```diff
@@ -51,6 +52,7 @@ func (suite *JobPollerSuite) BeforeTest(_, _ string) {
 		closeSignal:    make(chan struct{}),
 		remaining:      0,
 		threshold:      int(math.Round(float64(DefaultJobWorkerMaxJobActive) * DefaultJobWorkerPollThreshold)),
+		shouldRetry:    func(_ context.Context, _ error) bool { return false },
```
Comment (npepinpe) [inline clients/go/pkg/worker/jobPoller_test.go:55]: Should we introduce a type as we did for credentials provider? Considering this is then passed in a public function, it would help document its intent.

File: clients/go/pkg/worker/jobWorker_builder.go [hunk 3]
```diff
@@ -190,7 +193,7 @@ func (builder *JobWorkerBuilder) Open() JobWorker {
 	}
 }
 
-func NewJobWorkerBuilder(gatewayClient pb.GatewayClient, jobClient JobClient) JobWorkerBuilderStep1 {
+func NewJobWorkerBuilder(gatewayClient pb.GatewayClient, jobClient JobClient, retryPred func(ctx context.Context, err error) bool) JobWorkerBuilderStep1 {
```
Comment (npepinpe) [inline clients/go/pkg/worker/jobWorker_builder.go:196]: Just realized, we don't document the public API in this package? :man_shrugging: 

Do you think it would make sense to pass here the `CredentialsProvider` instead? It might make the intent of the predicate clearer, and we could document it as "you should pass the same credentials provider used when creating the client" or something.

**Review by npepinpe — CHANGES_REQUESTED** [review]
:tada: 

Looks good! I think we should still open an issue to be able to reuse the client in the worker in the long run, so we don't have to reimplement this kind of logic in two places.

One small thing - I guess we're testing generally that the retry works, but not exactly that we're retrying when opening the stream, and when receiving? But I tried to come up with how we could test both to ensure we're covering everything, and couldn't come up with anything :sweat_smile: There's nothing we can do on the interceptor/mock server side, right?

File: clients/go/pkg/commands/activate_jobs.go [hunk 4]
```diff
@@ -81,21 +82,26 @@ func (cmd *ActivateJobsCommand) FetchVariables(fetchVariables ...string) Activat
...
 	for {
 		response, err := stream.Recv()
 		if err == io.EOF {
 			break
 		}
+		if cmd.shouldRetry(ctx, err) {
+			// the headers are outdated and need to be remade
+			stream, err = cmd.openStream(ctx)
+			if err != nil {
+				log.Printf("Failed to reopen job polling stream after UNATHENTICATED error: %v\n", err)
```
[the remark this answers is not in the document]
Comment (MiguelPires) [reply clients/go/pkg/commands/activate_jobs.go:100]: That's what `log` does by default

File: clients/go/pkg/worker/jobPoller_test.go (hunk 2 above)
Comment (MiguelPires) [reply clients/go/pkg/worker/jobPoller_test.go:55]: I can change it so it's consistent with the other usage but I'm not sure. It's true that it gives you a small description of what it is but the parameter name does the same. Also, it covers the function signature which you need to implement. Besides, the `retryPredicate` in the commands package isn't exported so you can't see what it is and how it's documented. Wdyt?

Comment (npepinpe) [reply clients/go/pkg/worker/jobPoller_test.go:55]: I think it might be ambiguous for users - not exactly what it does, but what should they pass? What should they implement here?

Comment (MiguelPires) [reply clients/go/pkg/worker/jobPoller_test.go:55]: I can change both interfaces to receive a CredentialsProvider (like you said in another comment) since that's an exported and documented interface. It's a breaking change but users are probably not using the New....Command methods directly in the command package

Comment (npepinpe) [reply clients/go/pkg/worker/jobPoller_test.go:55]: Internally I guess we can use the function directly - I guess using CredentialsProvider would only be for the "public" stuff anyway. That way it's a little less coupled, but it's maybe a bit clearer to the users what should be passed? I guess the only concern here is that we need to be very specific that it should be the exact same used to configure the pb.GatewayClient, since if they pass another one we wouldn't use the "auth" part of it (does that make sense?).

wdyt of this idea? I feel like this is a better approach from a user pov - though like you said, users probably aren't creating the worker directly :thinking: 

If you like the idea then go for it, but if it sounds weird to you then I won't insist, as I'm only 80% sure about it :wink:

Comment (MiguelPires) [reply clients/go/pkg/worker/jobPoller_test.go:55]: Makes sense. It's not ideal but I think is as good as it gets if we want to keep exposing this builder. Imo the underlying issue here is that our API is way too big and exposes unnecessary things

Comment (MiguelPires) [reply clients/go/pkg/worker/jobPoller_test.go:55]: Makes sense. It's not ideal but I think is as good as it gets if we want to keep exposing this builder. Imo the underlying issue here is that our API is way too big and exposes unnecessary things

**Comment by MiguelPires** [comment]
@npepinpe  I improved the logs like you requested. I didn't change the retryPredicate for the CredentialsProvider because to avoid adding a cyclic dependency, I'd have to move it to the worker which is not ideal imo. I could pull the CredentialsProvider into its own package but that goes against how interfaces are meant to be used. Hopefully, eventually we can refactor this job worker and it won't have this dependency at all

File: clients/go/pkg/worker/jobWorker_builder.go [hunk 5]
```diff
@@ -190,7 +193,8 @@ func (builder *JobWorkerBuilder) Open() JobWorker {
 	}
 }
 
-func NewJobWorkerBuilder(gatewayClient pb.GatewayClient, jobClient JobClient) JobWorkerBuilderStep1 {
+// NewJobWorkerBuilder should use the same retryPredicate used by the CredentialProvider (ShouldRetry method)
```
Comment (npepinpe) [inline clients/go/pkg/worker/jobWorker_builder.go:196]: Can we give an example usage here?

**Review by npepinpe — APPROVED** [review]
One small request, but not a blocker :+1:

File: clients/go/pkg/worker/jobWorker_builder.go (hunk 5 above)
Comment (MiguelPires) [reply clients/go/pkg/worker/jobWorker_builder.go:196]: In a comment? It's just going to look like straight text, not very readable. Ideally, we'd have example files which help our users see sample usages (good thing to add to the to do list actually)

Comment (npepinpe) [reply clients/go/pkg/worker/jobWorker_builder.go:196]: I've seen other Go packages put examples in comments. It looks OK-ish, we just keep it short.

See for example: https://godoc.org/github.com/aws/aws-sdk-go/aws#Config

```go
    // Retryer guides how HTTP requests should be retried in case of
    // recoverable failures.
    //
    // When nil or the value does not implement the request.Retryer interface,
    // the client.DefaultRetryer will be used.
    //
    // When both Retryer and MaxRetries are non-nil, the former is used and
    // the latter ignored.
    //
    // To set the Retryer field in a type-safe manner and with chaining, use
    // the request.WithRetryer helper function:
    //
    //   cfg := request.WithRetryer(aws.NewConfig(), myRetryer)
    //
    Retryer RequestRetryer
```
