### PR TITLE
fix: ignore unknown response properties in zeebe client

### LINKED ISSUE #39675: Camunda 8.7 REST client fails on unknown response properties on job activate
### 

### 

, 

### 

### 

### Description

We've confirmed a bug in the Zeebe 8.7 client that causes job activation failures with Zeebe 8.8 clusters when 'preferRestOverGrpc' is enabled.

The issue is caused by the client not ignoring unknown response properties, resulting in parsing errors, thus if you update a cluster to 8.8 while still having 8.7 clients running all clients will fail to activate jobs.

We consider this the usual upgrade path, given that zeebe clients were historically mostly forward-compatible, although never explicitly stated. Thus many users may have been used to this procedure.
However, this is only relevant when users opted into using the REST API instead of GRPC, GRPC was still the default with 8.7, thus attributing a low likelihood here (until proven wrong).

This means that existing Java client setups that set `preferRestOverGrpc=true` will break when updating the targeted cluster to 8.8, as several APIs, at least the Jobs API contain new fields.

### Steps to reproduce

1. Create a 8.7 cluster and run a process with service tasks
2. Setup and run workers using the 8.7 Zeebe Client with `preferRestOverGrpc=true` (opt-in)
3. Update the cluster to 8.8

### Current behavior

4. Clients will start to fail on job activation with:
```
io.camunda.zeebe.client.api.command.MalformedResponseException: Expected to receive a response body, but got a problem: class ProblemDetail {
    type: about:blank
    title: Unexpected server response
    status: 500
    detail: {"jobs":[{"type":"check-generation-usage-job","processDefinitionId":"c[...]
    instance: null
}
```

### Expected behavior

4. Existing clients should still be operational

### Workaround

1. reconfigure clients to `preferRestOverGrpc=false` (the default)

### Environment

SaaS & SM

### Version

- Component Version: Zeebe Java Client & Zeebe Spring SDK <=8.7.15 connecting to a 8.8.x cluster.

### Rootcause

The 8.7 Zeebe Rest client is failing in unknown properties by default, blocking it from being forward-compatible. As this is the default behavior of the ObjectMapper setup [here](https://github.com/camunda/camunda/blob/stable/8.7/clients/java/src/main/java/io/camunda/zeebe/client/impl/http/HttpClientFactory.java#L72).

On `main`/`8.8` this was already [fixed](https://github.com/camunda/camunda/blob/main/clients/java/src/main/java/io/camunda/client/impl/http/HttpClientFactory.java#L75)

### Solution ideas

Do not fail response parsing on unknown properties in the 8.7 Http client.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Incident channel https://camunda.slack.com/archives/C09M2JU3Z4J

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by megglos**
## Description

To ensure it doesn't unnecessarily fail on non-breaking changes like new properties.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #39675

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
👍

**Comment by megglos** [comment]
~~deleted~~

Edit:
I will improvement on parse exception handling  into a dedicated PR, goes out of scope for the fix.
https://github.com/camunda/camunda/tree/meg-do-not-wrap-parse-errors-as-problem

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java [hunk 1]
```diff
@@ -93,17 +93,10 @@ public JsonApiEntityConsumer(
...
-        return ApiEntity.of(json.readValue(buffer.asParserOnFirstToken(), ProblemDetail.class));
-      } catch (final IOException ioe) {
-        // write the original JSON response into an error response
-        final String jsonString = getJsonString();
-        return ApiEntity.of(
-            new ProblemDetail().title("Unexpected server response").status(500).detail(jsonString));
+      if (isResponse) {
+        return ApiEntity.of(json.readValue(buffer.asParserOnFirstToken(), type));
       }
+      return ApiEntity.of(json.readValue(buffer.asParserOnFirstToken(), ProblemDetail.class));
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java]: 👍 Makes a lot more sense to just properly fail in the client, yeah, thanks for this 🚀

**Comment by megglos** [comment]
Adding backport to 8.6 as well, given we had the http client there too.

For the backport to `main`/`stable/8.8` we will hit conflicts as there mapper is already configured to ignore unknown props, might be worth to check whether the test is worth keeping there. Will decide when looking at those after we have the 8.7 fix ready and validated.

**Review by tmetzke — APPROVED** [review]
Thanks for adding the test as well, looks good to me 👍
