### PR TITLE
Resolve LogStorage concurrency bug

### LINKED ISSUE #7475: AvailabilityTest is unstable
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Regularly
- Does it block your work? YES
- Do we suspect that it is a real failure? IDK

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds
	at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2211)
	at app//io.camunda.zeebe.test.util.record.RecordingExporter$RecordIterator.hasNext(RecordingExporter.java:265)
	at java.base@11.0.10/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.base@11.0.10/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.10/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base@11.0.10/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.10/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at app//io.camunda.zeebe.test.util.stream.StreamWrapper.exists(StreamWrapper.java:67)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule.lambda$waitUntilDeploymentIsDone$3(GrpcClientRule.java:102)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule$$Lambda$1632/0x00000007c0963040.getAsBoolean(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil.lambda$waitUntil$2(TestUtil.java:36)
	at app//io.camunda.zeebe.test.util.TestUtil$$Lambda$1634/0x00000007c0963c40.apply(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.lambda$until$4(TestUtil.java:89)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation$$Lambda$1636/0x00000007c0964440.apply(Unknown Source)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:179)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:149)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:88)
	at app//io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)
	at app//io.camunda.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule.waitUntilDeploymentIsDone(GrpcClientRule.java:98)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.util.GrpcClientRule.deployProcess(GrpcClientRule.java:177)
	at app/zeebe.qa.integration.tests@1.2.0-SNAPSHOT/io.camunda.zeebe.broker.it.clustering.AvailabilityTest.setup(AvailabilityTest.java:59)
	at java.base@11.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.10/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.10/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.10/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

What do I know

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[log.txt](https://github.com/camunda-cloud/zeebe/files/6795011/log.txt)

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

The logStorage was concurrently manipulated by different actors, since
the step was installed for each partition and the same object was in use. In order to avoid that the
storage is set into the partition context, which is an object for each partition.

I dont like to add more to the context, but it quickly solves the issue for now.
Alternative solution would be to have instead of one object for all partitions, separate
objects. Like defining only the classes for the Leader- and Follower-Steps.
Since we plan to refactor the bootstraping I don't think it makes sense to spent
more time on this.

Unfortunately I had to first reformat the context class, it seem to not align with our guidelines/settings ?

## Related issues

closes #7475

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStreamPartitionStep.java [hunk 1]
```diff
@@ -95,8 +94,9 @@ public String getName() {
     if (raftTerm != context.getCurrentTerm()) {
       return left(buildWrongTermException(context, raftTerm));
     } else {
-      logStorage = AtomixLogStorage.ofPartition(server::openReader, logAppender);
+      final var logStorage = AtomixLogStorage.ofPartition(server::openReader, logAppender);
       server.addCommitListener(logStorage);
+      context.setLogStorage(logStorage);
```
Comment (pihme) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStreamPartitionStep.java:99]: :wrench: I would prefer if we set the log storage in the method that calls this place. We could also remove the `context` parameter altogether if we pass in `currentTerm` and `partitionId`

The reason I don't want it here, is that hierarchically, I would read the open method first. And there I want to see all the changes to the context.

**Review by pihme — APPROVED** [review]
lgtm :tada:

**Comment by pihme** [comment]
Regarding the reformatting of the file. Honestly, I don't know what more settings I should set. It is not my strong suit, and maybe I configured something wrong. But I have a reformat on safe, and I have the code guidelines, to the best of my knowledge.

And I have no idea why the previous formatting was wrong and the new one is correct, so I am not able to detect that.

What I think I notices is some inconsistencies. Sometimes methods are sorted in alphabetical order, sometimes in the order they appear in the interface. I find it very confusing. 

(And then I yesterday had a case in another PR where IDEA was inserting line breaks in funny places in a markdown file.)

All that is to say: If you have the patience and inclination, I am happy to set up a Zoom call and we can go through my settings. Just to check whether I have everything configured correctly.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStreamPartitionStep.java (hunk 1 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStreamPartitionStep.java:99]: sounds good

**Comment by Zelldon** [comment]
I had always the same issue with @deepthidevaki regarding method ordering. I agree this is confusing. Yeah we can check that together. I don't like that the save actions, can't be configured via file or something.
