### PR TITLE
fix(gateway): synchronize cancellation of long polling request

### LINKED ISSUE #13867: ConcurrentModificationException when clearing obsolete job activation requests
**Describe the bug**

A `ConcurrentModificationException` occurs when clearing obsolete job activation (long polling) requests. The exception is thrown when clearing the `activeRequests` LinkedList which isn't thread-safe ([code](https://github.com/camunda/zeebe/blob/8ef7c6ffd293ab11c9d2f2ee2f79f98b47941d1d/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/InFlightLongPollingActivateJobsRequestsState.java#L77)).

**To Reproduce**

**Expected behavior**

A `ConcurrentModificationException` doesn't occur. 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.ConcurrentModificationException: null

at java.util.LinkedList$ListItr.checkForComodification
at java.util.LinkedList$ListItr.remove
at java.util.Collection.removeIf
at io.camunda.zeebe.gateway.impl.job.InFlightLongPollingActivateJobsRequestsState.removeObsoleteRequestsAndUpdateMetrics ( io/camunda.zeebe.gateway.impl.job/InFlightLongPollingActivateJobsRequestsState.java:77 )
at io.camunda.zeebe.gateway.impl.job.InFlightLongPollingActivateJobsRequestsState.getPendingRequests ( io/camunda.zeebe.gateway.impl.job/InFlightLongPollingActivateJobsRequestsState.java:71 )
at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.resetFailedAttemptsAndHandlePendingRequests ( io/camunda.zeebe.gateway.impl.job/LongPollingActivateJobsHandler.java:245 )
at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$onNotification$6 ( io/camunda.zeebe.gateway.impl.job/LongPollingActivateJobsHandler.java:181 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:92 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:45 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:119 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:109 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:87 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:204 )
```

</p>
</details>

**Environment:**
- OS:  Linux
- Zeebe Version:  8.3.0-SNAPSHOT
- Configuration: 
- Error occured in CW32 benchmark ([src](https://console.cloud.google.com/logs/query;query=error_group%2528%22CKD6icXrpN_oLA%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22medic-y-2023-cw-32-1f55f22-benchmark-zeebe-gateway-5fbb459ctcwr%22%0Aresource.labels.container_name%3D%22zeebe-gateway%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-y-2023-cw-32-1f55f22-benchmark%22;cursorTimestamp=2023-08-10T20:21:27.752805343Z;startTime=2023-08-10T19:51:57.752Z;endTime=2023-08-10T20:51:57.752Z?project=zeebe-io)).

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes a concurrent modification error when removing obsolete requests/a client cancels a long polling request.

## Related issues

closes #13867 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Last commit adds a test, but it's very brittle, just checking that the on cancel callback calls `actor.run`. I'm in favor of omitting it, but even better would be if you have another idea for a regression test here.

File: gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java [hunk 1]
```diff
@@ -672,6 +674,29 @@ public BrokerResponse<?> handle(final BrokerActivateJobsRequest request)
     assertThat(request.hasScheduledTimer()).isFalse();
   }
 
+  @RegressionTest("https://github.com/camunda/zeebe/issues/13867")
+  @Test
+  public void shouldExecuteOnCancelRequestHandlerOnActor() {
```
Comment (koevskinikola) [inline gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java:679]: :X: The CI reports this test is flaky. I'm not sure why it's failing.

```
Error:  io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldExecuteOnCancelRequestHandlerOnActor -- Time elapsed: 1.963 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.accept(io.camunda.zeebe.scheduler.ActorControl)" because "this.handler" is null
	at io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldExecuteOnCancelRequestHandlerOnActor(LongPollingActivateJobsTest.java:691)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Review by koevskinikola — CHANGES_REQUESTED** [review]
The fix looks good, but the new test is failing in the CI.

File: gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java (hunk 1 above)
Comment (npepinpe) [reply gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java:679]: tbh I would remove it anyway, like I wrote, I don't think it's a very useful test, but I couldn't come up with anything else for this specific concurrency edge case.

**Review by koevskinikola — APPROVED** [review]
LGTM :rocket: 

bors merge
