### PR TITLE
fix: check permission for correlated messages

### LINKED ISSUE #39301: Intermediate message event gets correlated even when a user doesn't have permissions
### 

### 

### 

### 

### Description

On correlating a message without having the proper permissions, a `FORBIDDEN` response is received. This is expected. However, the message still gets correlated.

### Steps to reproduce

1. Setup a proces waiting at an intermediate message catch event
2. Create an entity with process instance read permissions, but without update permissions
3. Publish a message to correlate with the catch event
4. Observe the `FORBIDDEN` response
5. Observe the message getting correlated and the process instance continuuing

### Current behavior

The message gets correlated

### Expected behavior

The message should not get correlated

### Workaround

N/A

### Environment

SaaS & SM

### Version

8.8.*

### Rootcause

Events are written before the authorization checks are performed.

### Solution ideas

Authorization checks should happen before anything else.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

Enforce user permissions check before correlating messages

## Related issues

closes #39301

### CODE REVIEW

**Review by remcowesterhoud — DISMISSED** [review]

**Comment by remcowesterhoud** [comment]
Ideally we don't retrieve the subscriptions from RocksDb twice. But as it's important to fix this issue quickly it's good enough for now. It's also not as straightforward as it seems to remove the double retrieval due to the events that get written in the second one.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/resource/ResourceDeletionDeleteProcessor.java [hunk 1]
```diff
@@ -195,6 +196,7 @@ private boolean tryDeleteResource(
           PermissionType.DELETE_PROCESS,
           bufferAsString(process.getBpmnProcessId()),
           process.getTenantId());
+      stateWriter.appendFollowUpEvent(eventKey, ResourceDeletionIntent.DELETING, value);
```
Comment (koevskinikola) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/resource/ResourceDeletionDeleteProcessor.java:199]: 🙃 We can reduce the duplication inside these process/decision/form/resource `if` blocks, but considering the urgency of the fix, we can postpone it. 🙂

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageCorrelationCorrelateProcessor.java [hunk 2]
```diff
@@ -104,6 +104,28 @@ public void processRecord(final TypedRecord<MessageCorrelationRecord> command) {
...
+
+    // Create a temporary subscriptions collector to check authorization first
+    final var tempCorrelatingSubscriptions = new Subscriptions();
+    correlateBehavior.collectMessageEventSubscriptions(messageData, tempCorrelatingSubscriptions);
+    correlateBehavior.collectMessageStartEventSubscriptions(
+        messageData, tempCorrelatingSubscriptions);
+
+    // Check authorization before writing anything to state
+    final var authorizationRejectionOptional =
+        isAuthorizedForAllSubscriptions(
```
Comment (koevskinikola) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageCorrelationCorrelateProcessor.java:119]: As far as I can see, the `isAuthorizedForAllSubscriptions` works in `all-or-nothing` mode. So even if one message subscription isn't authorized, we don't correlate at all. 

🔧  In the `isAuthorizedForAllSubscriptions`, we can collect all the `bpmnProcessId`s in two `authorizationRequests`, one for `PermissionType.CREATE_PROCESS_INSTANCE` and one for `PermissionType.UPDATE_PROCESS_INSTANCE`, i.e. message start events and message catch events. This way, we only access the Identity-related states two times, instead of the arbitrary number we do now.

We don't have to do this now, as the fix is critical, but it might significantly improve the message correlation performance when we correlate to a large number of subscriptions.

**Review by koevskinikola — APPROVED** [review]
👍 Looks good @nicpuppa!

🔧 I have some feedback on how we perform the authorization check, but it's an optimization on the code that isn't related to the critical bug, so we can tackle it another time.

**Comment by nicpuppa** [comment]
As shared on slack, let's merge the PR and then address the suggestions in the follow up backport PRs
