### PR TITLE
fix(broker): fix lost messages on rejected correlation

### LINKED ISSUE #1811: Messages get lost if correlate command is rejected
A workflow instance correlate command is rejected when the event scope is left. However, the command is acknowledged by the workflow instance subscription processor. So the message subscription processor is not aware that the command is rejected. As result, the message is not correlated again when a new subscription is opened - it is lost!

AT:
* a message can be correlated again when the correlate command is rejected (-> so don't lose messages)

### PR DESCRIPTION
**Pull request by miguelpires**
Sends a reset command which removes the message's correlation from the state, allowing it to be correlated again.

closes #1811

### CODE REVIEW

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/ResetMessageCorrelationProcessor.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+    if (subscription != null) {
+      correlateMessageRecord.reset();
+      correlateMessageRecord
+          .setMessageKey(subscription.getMessageKey())
+          .setWorkflowInstanceKey(subscription.getWorkflowInstanceKey())
+          .setElementInstanceKey(subscription.getElementInstanceKey())
+          .setCorrelationKey(subscription.getCorrelationKey())
+          .setMessageName(subscription.getMessageName());
+
+      streamWriter.appendNewCommand(MessageSubscriptionIntent.CORRELATE, correlateMessageRecord);
```
[the remark this answers is not in the document]
Comment (saig0) [reply broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/ResetMessageCorrelationProcessor.java]: If the subscription is closed then we don't write an event as confirmation of the command. This is very uncommon for our stream processing.

**Review by saig0 — CHANGES_REQUESTED** [review]
I think we missed two cases:

a) open subscription before rejection

  1. message is published
  1. open first subscription
  1. send correlated message command
  1. open second subscription
  1. reject correlate command 

-> the message is not correlated to the second subscription

b) correlate messages in wrong order

same situation as a) but with two messages

-> the second message is correlated before the first message was rejected
-> so, the order of the correlated messages is different from order how they are published (unexpected behavior)

**Comment by MiguelPires** [comment]
Hey @saig0, I refactored the reject command and added the test case you mentioned. As we discussed, I opened an issue for the second case, where messages appear to be correlated out of order https://github.com/zeebe-io/zeebe/issues/2459

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/ResetMessageCorrelationProcessor.java [hunk 2]
```diff
@@ -62,20 +70,30 @@ public void processRecord(
...
+    correlateMessageRecord
+        .setMessageKey(subscription.getMessageKey())
+        .setWorkflowInstanceKey(subscription.getWorkflowInstanceKey())
+        .setElementInstanceKey(subscription.getElementInstanceKey())
+        .setCorrelationKey(subscription.getCorrelationKey())
+        .setMessageName(subscription.getMessageName());
 
-      streamWriter.appendNewCommand(MessageSubscriptionIntent.CORRELATE, correlateMessageRecord);
-    }
+    messageCorrelator.correlateNextMessage(subscription, correlateMessageRecord, sideEffect);
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/ResetMessageCorrelationProcessor.java]: This looks a bit odd because we already have the message to correlate with ;) I would like to have it more explicitly to be sure that we correlate the rejected message.

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/MessageEventProcessors.java [hunk 3]
```diff
@@ -77,7 +77,8 @@ public static void addMessageProcessors(
         .onCommand(
             ValueType.MESSAGE_SUBSCRIPTION,
             MessageSubscriptionIntent.RESET,
-            new ResetMessageCorrelationProcessor(messageState, subscriptionState))
+            new ResetMessageCorrelationProcessor(
+                messageState, subscriptionState, subscriptionCommandSender))
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/MessageEventProcessors.java]: We should also change the intent to "REJECT" to be aligned with the subscription command.

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/ResetMessageCorrelationProcessor.java [hunk 4]
```diff
@@ -62,20 +70,30 @@ public void processRecord(
     }
     messageState.removeMessageCorrelation(messageKey, workflowInstanceKey);
 
-    final MessageSubscription subscription =
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/ResetMessageCorrelationProcessor.java]: We should write an "ACKNOWLEDGE" event for the command (with intent "REJECTED"). Otherwise, we would have no follow-up event if no subscription exists.

File: broker-core/src/test/java/io/zeebe/broker/subscription/message/MessageStreamProcessorTest.java [hunk 5]
```diff
@@ -375,6 +375,53 @@ public void shouldCorrelateMultipleMessagesTwoBeforeOpen() {
...
+    assertThat(BufferUtil.equals(captor.getValue(), firstSubscription.getMessageName())).isTrue();
+
+    verify(mockSubscriptionCommandSender, timeout(5_000))
+        .correlateWorkflowInstanceSubscription(
+            eq(secondSubscription.getWorkflowInstanceKey()),
+            eq(secondSubscription.getElementInstanceKey()),
+            captor.capture(),
+            eq(messageKey),
+            any(DirectBuffer.class));
+    assertThat(BufferUtil.equals(captor.getValue(), secondSubscription.getMessageName())).isTrue();
```
Comment (saig0) [inline broker-core/src/test/java/io/zeebe/broker/subscription/message/MessageStreamProcessorTest.java]: Why do we need to verify the message name? It is equal in both cases.

File: broker-core/src/test/java/io/zeebe/broker/workflow/message/MessageCorrelationTest.java [hunk 6]
```diff
@@ -678,6 +681,59 @@ public void shouldCorrelateToNonInterruptingBoundaryEvent() {
     assertThat(correlatedValues).containsOnly("0", "1", "2");
   }
 
+  @Test
+  public void shouldCorrelateBothMessages() {
```
Comment (saig0) [inline broker-core/src/test/java/io/zeebe/broker/workflow/message/MessageCorrelationTest.java]:
```suggestion
  public void shouldCorrelateMessageAgainAfterRejection() {
```

**Review by saig0 — CHANGES_REQUESTED** [review]

**Comment by MiguelPires** [comment]
Hey @saig0, I iterated again on the rejection processor

**Review by saig0 — APPROVED** [review]

**Comment by MiguelPires** [comment]
bors retry
