### PR TITLE
test(qa/integration-tests): increase test stability

### LINKED ISSUE #4430: SingleBrokerDataDeletionTest.shouldNotCompactNotExportedEvents flaky
**Summary**

- How often does the test fail? - top 3 flaky tests for CW 20, CW 21
- Does it block your work? - not really
- Do we suspect that it is a real failure? - unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error Message

Segment not open

Stacktrace

java.util.concurrent.ExecutionException: Segment not open
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:141)
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:108)
	at io.zeebe.util.sched.FutureUtil.join(FutureUtil.java:21)
	at io.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:196)
	at io.zeebe.broker.it.clustering.SingleBrokerDataDeletionTest.shouldNotCompactNotExportedEvents(SingleBrokerDataDeletionTest.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.lang.IllegalStateException: Segment not open
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.atomix.storage.journal.JournalSegment.checkOpen(JournalSegment.java:234)
	at io.atomix.storage.journal.JournalSegment.createReader(JournalSegment.java:211)
	at io.atomix.storage.journal.SegmentedJournalReader.initialize(SegmentedJournalReader.java:41)
	at io.atomix.storage.journal.SegmentedJournalReader.<init>(SegmentedJournalReader.java:34)
	at io.atomix.storage.journal.SegmentedJournal.openReader(SegmentedJournal.java:227)
	at io.atomix.raft.storage.log.RaftLog.openReader(RaftLog.java:63)
	at io.atomix.raft.partition.impl.RaftPartitionServer.openReader(RaftPartitionServer.java:198)
	at io.zeebe.logstreams.storage.atomix.AtomixRaftServer.create(AtomixRaftServer.java:30)
	at io.zeebe.logstreams.storage.atomix.AtomixReaderFactory.create(AtomixReaderFactory.java:18)
	at io.zeebe.logstreams.storage.atomix.AtomixReaderFactory.create(AtomixReaderFactory.java:22)
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorage.newReader(AtomixLogStorage.java:40)
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.<init>(LogStreamReaderImpl.java:41)
	at io.zeebe.logstreams.impl.log.LogStreamImpl.lambda$newLogStreamReader$2(LogStreamImpl.java:117)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204)

</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
00:16:18.453 [] [main] INFO  io.zeebe.test - Test started: shouldNotCompactNotExportedEvents(io.zeebe.broker.it.clustering.SingleBrokerDataDeletionTest)
00:16:18.458 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27822 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=23}
00:16:18.459 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27823 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=24}
00:16:18.459 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27824 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=25}
00:16:18.459 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27825 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=26}
00:16:18.459 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27826 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=27}
00:16:18.459 [] [main] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/junit5766860902055733790/0
00:16:18.461 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27827 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=28}
00:16:18.461 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27828 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=29}
00:16:18.461 [] [Thread-559] INFO  io.zeebe.broker.system - Version: 0.24.0-SNAPSHOT
00:16:18.466 [] [Thread-559] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "0MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 27824,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27824,
      "address" : "0.0.0.0:27824",
      "advertisedAddress" : "0.0.0.0:27824"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 27825,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27825,
      "address" : "0.0.0.0:27825",
      "advertisedAddress" : "0.0.0.0:27825"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 27826,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27826,
      "address" : "0.0.0.0:27826",
      "advertisedAddress" : "0.0.0.0:27826"
    },
    "maxMessageSizeInBytes" : 8192
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 1,
    "clusterSize" : 1,
    "clusterName" : "zeebe-cluster-1",
    "gossipFailureTimeout" : 2000,
    "gossipInterval" : 150,
    "gossipProbeInterval" : 250
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/tmp/junit5766860902055733790/0/data" ],
    "logSegmentSize" : "0MB",
    "snapshotPeriod" : "PT1M",
    "logIndexDensity" : 5,
    "logSegmentSizeInBytes" : 8192
  },
  "exporters" : {
    "snapshot-test-exporter" : {
      "jarPath" : null,
      "className" : "io.zeebe.broker.it.clustering.SingleBrokerDataDeletionTest$ControllableExporter",
      "args" : null,
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 27822,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:27825",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 27823
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
00:16:18.467 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/10]: actor scheduler
00:16:18.469 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/10]: actor scheduler started in 2 ms
00:16:18.469 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/10]: membership and replication protocol
00:16:18.478 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/10]: membership and replication protocol started in 9 ms
00:16:18.478 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/10]: command api transport
00:16:18.530 [] [Thread-559] DEBUG io.zeebe.broker.system - Bound command API to 0.0.0.0:27824 
00:16:18.531 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/10]: command api transport started in 53 ms
00:16:18.531 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/10]: command api handler
00:16:18.533 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/10]: command api handler started in 1 ms
00:16:18.534 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/10]: subscription api
00:16:18.534 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/10]: subscription api started in 0 ms
00:16:18.534 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/10]: cluster services
00:16:18.556 [] [atomix-0] WARN  io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService - Failed to locate partition group(s) via bootstrap nodes. Please ensure partition groups are configured either locally or remotely and the node is able to reach partition group members.
00:16:18.559 [] [atomix-0] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=1, group=raft-partition}
00:16:18.633 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
00:16:18.634 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Single member cluster. Transitioning directly to candidate.
00:16:18.634 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE
00:16:18.634 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.raft.roles.FollowerRole$$Lambda$387/0x0000000840424840@70419b60 not registered
00:16:18.636 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Single member cluster. Transitioning directly to leader.
00:16:18.645 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to LEADER
00:16:18.646 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 0
00:16:18.653 [] [raft-partition-group-raft-partition-0] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
00:16:18.653 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/10]: cluster services started in 118 ms
00:16:18.654 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/10]: topology manager
00:16:18.654 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/10]: topology manager started in 0 ms
00:16:18.654 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/10]: metric's server
00:16:18.657 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/10]: metric's server started in 3 ms
00:16:18.657 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/10]: leader management request handler
00:16:18.657 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [9/10]: leader management request handler started in 0 ms
00:16:18.657 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/10]: zeebe partitions
00:16:18.658 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
00:16:18.658 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Removing follower partition service for partition PartitionId{id=1, group=raft-partition}
00:16:18.659 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER
00:16:18.659 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Installing leader partition service for partition PartitionId{id=1, group=raft-partition}
00:16:18.660 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: []
00:16:19.582 [] [raft-partition-group-raft-partition-0] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
00:16:19.635 [] [main] INFO  io.zeebe.gateway - Version: 0.24.0-SNAPSHOT
00:16:19.644 [] [main] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 27827,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "0.0.0.0:27825",
    "requestTimeout" : "PT45S",
    "clusterName" : "zeebe-cluster-1",
    "memberId" : "gateway",
    "host" : "0.0.0.0",
    "port" : 27828
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "0.0.0.0",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  }
}
00:16:19.652 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Received new broker BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=1, replicationFactor=1, partitionRoles={}, partitionLeaderTerms={}, version=0.24.0-SNAPSHOT}.
00:16:19.960 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/runtime'.
00:16:19.962 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
00:16:19.962 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
00:16:19.963 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@791945ba)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@526fb264, configuration: Configuration(false)]
00:16:19.964 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
00:16:19.965 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@6afeb026)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@59f91c56, configuration: Configuration(false)]
00:16:19.965 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@762a799f)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@15784dde, configuration: Configuration(false)]
00:16:19.969 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
00:16:19.970 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
00:16:19.971 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 1313 ms
00:16:19.971 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovered exporter 'Broker-0-Exporter-1' from snapshot at lastExportedPosition -1
00:16:19.971 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 1313 ms.
00:16:19.971 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'snapshot-test-exporter'
00:16:19.971 [] [Thread-559] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/10]: zeebe partitions started in 1313 ms
00:16:19.971 [] [Thread-559] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 10 steps in 1504 ms.
00:16:19.972 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={COMMAND_REJECTION=true, SBE_UNKNOWN=true, COMMAND=true, EVENT=true, NULL_VAL=true}, acceptValueTypes={INCIDENT=true, JOB_BATCH=true, VARIABLE=true, WORKFLOW_INSTANCE_SUBSCRIPTION=true, JOB=true, NULL_VAL=true, WORKFLOW_INSTANCE_CREATION=true, DEPLOYMENT=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, WORKFLOW_INSTANCE_RESULT=true, WORKFLOW_INSTANCE=true, MESSAGE=true, SBE_UNKNOWN=true, MESSAGE_SUBSCRIPTION=true, VARIABLE_DOCUMENT=true, ERROR=true, TIMER=true}}
00:16:19.972 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Open exporter with id 'snapshot-test-exporter'
00:16:20.058 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER} and terms {1=1}.
00:16:20.146 [] [main] INFO  io.zeebe.broker.system - Full replication factor
00:16:20.236 [] [main] INFO  io.zeebe.broker.system - All brokers in topology TopologyImpl{brokers=[BrokerInfoImpl{nodeId=0, host='0.0.0.0', port=27824, version=0.24.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=LEADER}]}], clusterSize=1, partitionsCount=1, replicationFactor=1, gatewayVersion=0.24.0-SNAPSHOT}
00:16:22.773 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {Raft-1=HEALTHY, Broker-0-StreamProcessor-1=UNHEALTHY, logStream=HEALTHY}
00:16:22.774 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] ERROR io.zeebe.broker.system - Partition-1 failed, marking it as unhealthy
00:16:22.777 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Taking temporary snapshot into /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/pushed-pending/84-1-1588292182776.
00:16:23.004 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Created snapshot for Broker-0-StreamProcessor-1
00:16:23.006 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] INFO  io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 8589939224 is committed, current commit position is 8589939224. After that snapshot can be marked as valid.
00:16:23.006 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] INFO  io.zeebe.logstreams.snapshot - Current commit position 8589939224 is greater then 8589939224, snapshot is valid.
00:16:23.039 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Purging snapshots older than DbSnapshot{directory=/tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776, metadata=DbSnapshotMetadata{index=84, term=1, timestamp=2020-05-01 12:16:22,776}}
00:16:23.041 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Search for orphaned snapshots below oldest valid snapshot with index 84 in /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/pushed-pending
00:16:23.044 [Broker-0-DeletionService-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.logstreams.delete - Compacting Atomix log up to index 84
00:16:23.045 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776, metadata=DbSnapshotMetadata{index=84, term=1, timestamp=2020-05-01 12:16:22,776}}
00:16:23.045 [] [raft-server-0-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - ZeebeRaftStateMachine1{partition=raft-partition-partition-1} - Compacting log up from 45 up to {}
00:16:23.046 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Start replicating latest snapshot /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776
00:16:23.129 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] ERROR io.zeebe.util.actor - Uncaught exception in 'Broker-0-LogStream-1' in phase 'STARTED'. Continuing with next job.
java.lang.IllegalStateException: Segment not open
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-29.0-jre.jar:?]
	at io.atomix.storage.journal.JournalSegment.checkOpen(JournalSegment.java:234) ~[atomix-storage-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.storage.journal.JournalSegment.createReader(JournalSegment.java:211) ~[atomix-storage-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournalReader.initialize(SegmentedJournalReader.java:41) ~[atomix-storage-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournalReader.<init>(SegmentedJournalReader.java:34) ~[atomix-storage-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.storage.journal.SegmentedJournal.openReader(SegmentedJournal.java:227) ~[atomix-storage-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.raft.storage.log.RaftLog.openReader(RaftLog.java:63) ~[atomix-cluster-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.openReader(RaftPartitionServer.java:198) ~[atomix-cluster-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.storage.atomix.AtomixRaftServer.create(AtomixRaftServer.java:30) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.storage.atomix.AtomixReaderFactory.create(AtomixReaderFactory.java:18) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.storage.atomix.AtomixReaderFactory.create(AtomixReaderFactory.java:22) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorage.newReader(AtomixLogStorage.java:40) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.<init>(LogStreamReaderImpl.java:41) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.lambda$newLogStreamReader$2(LogStreamImpl.java:117) ~[zeebe-logstreams-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) ~[zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
00:16:23.131 [] [main] INFO  io.zeebe.test.records - Test failed, following records where exported:
00:16:23.132 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776/000092.sst
00:16:23.133 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776/000093.sst
00:16:23.134 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776/000094.sst
00:16:23.134 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776/000095.sst
00:16:23.135 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776/000096.sst
00:16:23.136 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776/000097.sst
00:16:23.136 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776/CURRENT
00:16:23.137 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776/MANIFEST-000004
00:16:23.137 [] [ForkJoinPool.commonPool-worker-5] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
00:16:23.138 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/snapshots/84-1-1588292182776/OPTIONS-000090
00:16:23.139 [] [main] DEBUG io.zeebe.gateway - Closing gateway broker client ...
00:16:23.144 [] [main] DEBUG io.zeebe.gateway - topology manager closed
00:16:23.145 [] [main] DEBUG io.zeebe.gateway - Gateway broker client closed.
00:16:23.146 [] [main] DEBUG io.zeebe.broker.system - Closing ClusteringRule...
00:16:23.146 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [1/10]: zeebe partitions
00:16:23.146 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1
00:16:23.146 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Broker-0-Exporter-1
00:16:23.147 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Closed exporter director 'Broker-0-Exporter-1'.
00:16:23.147 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-0-Exporter-1 successfully
00:16:23.147 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-0-SnapshotDirector-1
00:16:23.147 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-0-SnapshotDirector-1 successfully
00:16:23.148 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-0-StreamProcessor-1
00:16:23.148 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
00:16:23.148 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-0-StreamProcessor-1 successfully
00:16:23.148 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-0-DeletionService-1
00:16:23.148 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-0-DeletionService-1 successfully
00:16:23.252 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/junit5766860902055733790/0/data/raft-partition/partitions/1/runtime'.
00:16:23.330 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream raft-partition-partition-1
00:16:23.331 [raft-partition-partition-1-write-buffer] [Broker-0-zb-actors-0] DEBUG io.zeebe.dispatcher - Dispatcher closed
00:16:23.331 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - On closing logstream raft-partition-partition-1 close 3 readers
00:16:23.331 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Close log storage with name raft-partition-partition-1
00:16:23.332 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1 closed in 186 ms
00:16:23.332 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions succeeded. Closed 1 steps in 186 ms.
00:16:23.332 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [1/10]: zeebe partitions closed in 186 ms
00:16:23.332 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [2/10]: leader management request handler
00:16:23.332 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [2/10]: leader management request handler closed in 0 ms
00:16:23.332 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [3/10]: metric's server
00:16:23.337 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [3/10]: metric's server closed in 5 ms
00:16:23.337 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [4/10]: topology manager
00:16:23.338 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [4/10]: topology manager closed in 0 ms
00:16:23.338 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [5/10]: cluster services
00:16:23.338 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [5/10]: cluster services closed in 0 ms
00:16:23.338 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [6/10]: subscription api
00:16:23.338 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [6/10]: subscription api closed in 0 ms
00:16:23.338 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [7/10]: command api handler
00:16:23.339 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [7/10]: command api handler closed in 1 ms
00:16:23.339 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [8/10]: command api transport
00:16:25.558 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [8/10]: command api transport closed in 2218 ms
00:16:25.558 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [9/10]: membership and replication protocol
00:16:25.559 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
00:16:25.634 [] [ForkJoinPool.commonPool-worker-3] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
00:16:27.848 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [9/10]: membership and replication protocol closed in 2290 ms
00:16:27.848 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [10/10]: actor scheduler
00:16:27.849 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [10/10]: actor scheduler closed in 1 ms
00:16:27.849 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 10 steps in 4703 ms.
00:16:27.849 [] [main] INFO  io.zeebe.broker.system - Broker shut down.
</pre>
</details>

### LINKED ISSUE #4519: ClusteredDataDeletionTest.shouldDeleteDataOnFollowers flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? - top 3 flaky tests in CW 23
- Does it block your work? - no
- Do we suspect that it is a real failure? - unkown

**Failures**

https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/develop/1137

<details><summary>Example assertion failure</summary>
<pre>
Error Message

expected:<[tru]e> but was:<[fals]e>

Stacktrace

org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:91)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)
	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
	at io.zeebe.broker.it.clustering.ClusteredDataDeletionTest.shouldDeleteDataOnFollowers(ClusteredDataDeletionTest.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
Standard Output

08:31:08.133 [] [main] INFO  io.zeebe.test - Test finished: shouldDeleteDataOnLeader[0: no-exporter](io.zeebe.broker.it.clustering.ClusteredDataDeletionTest)
08:31:08.133 [] [main] INFO  io.zeebe.test - Test started: shouldDeleteDataOnFollowers[0: no-exporter](io.zeebe.broker.it.clustering.ClusteredDataDeletionTest)
08:31:08.134 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27837 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=38}
08:31:08.134 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27838 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=39}
08:31:08.134 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27839 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=40}
08:31:08.135 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27840 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=41}
08:31:08.135 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27841 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=42}
08:31:08.135 [] [main] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/junit10189461558897322716/0
08:31:08.136 [] [Thread-763] INFO  io.zeebe.broker.system - Version: 0.24.0-SNAPSHOT
08:31:08.137 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27842 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=43}
08:31:08.137 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27843 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=44}
08:31:08.137 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27844 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=45}
08:31:08.137 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27845 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=46}
08:31:08.137 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27846 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=47}
08:31:08.137 [] [main] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/junit10189461558897322716/1
08:31:08.137 [] [Thread-763] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "0MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 27839,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27839,
      "address" : "0.0.0.0:27839",
      "advertisedAddress" : "0.0.0.0:27839"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 27840,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27840,
      "address" : "0.0.0.0:27840",
      "advertisedAddress" : "0.0.0.0:27840"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 27841,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27841,
      "address" : "0.0.0.0:27841",
      "advertisedAddress" : "0.0.0.0:27841"
    },
    "maxMessageSizeInBytes" : 8192
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster-1",
    "gossipFailureTimeout" : 2000,
    "gossipInterval" : 150,
    "gossipProbeInterval" : 250
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/tmp/junit10189461558897322716/0/data" ],
    "logSegmentSize" : "0MB",
    "snapshotPeriod" : "PT1M",
    "logIndexDensity" : 50,
    "atomixStorageLevel" : "DISK",
    "logSegmentSizeInBytes" : 8192
  },
  "exporters" : { },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 27837,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:27840",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 27838
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
08:31:08.137 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/10]: actor scheduler
08:31:08.139 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/10]: actor scheduler started in 1 ms
08:31:08.139 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/10]: membership and replication protocol
08:31:08.140 [] [Thread-768] INFO  io.zeebe.broker.system - Version: 0.24.0-SNAPSHOT
08:31:08.140 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27847 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=48}
08:31:08.140 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27848 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=49}
08:31:08.140 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27849 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=50}
08:31:08.141 [] [Thread-768] INFO  io.zeebe.broker.system - Starting broker 1 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "0MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 27844,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27844,
      "address" : "0.0.0.0:27844",
      "advertisedAddress" : "0.0.0.0:27844"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 27845,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27845,
      "address" : "0.0.0.0:27845",
      "advertisedAddress" : "0.0.0.0:27845"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 27846,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27846,
      "address" : "0.0.0.0:27846",
      "advertisedAddress" : "0.0.0.0:27846"
    },
    "maxMessageSizeInBytes" : 8192
  },
  "cluster" : {
    "initialContactPoints" : [ "0.0.0.0:27840" ],
    "partitionIds" : [ 1 ],
    "nodeId" : 1,
    "partitionsCount" : 1,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster-1",
    "gossipFailureTimeout" : 2000,
    "gossipInterval" : 150,
    "gossipProbeInterval" : 250
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/tmp/junit10189461558897322716/1/data" ],
    "logSegmentSize" : "0MB",
    "snapshotPeriod" : "PT1M",
    "logIndexDensity" : 50,
    "atomixStorageLevel" : "DISK",
    "logSegmentSizeInBytes" : 8192
  },
  "exporters" : { },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 27842,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:27845",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 27843
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
08:31:08.141 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27850 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=51}
08:31:08.141 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27851 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=52}
08:31:08.141 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [1/10]: actor scheduler
08:31:08.141 [] [main] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/junit10189461558897322716/2
08:31:08.143 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [1/10]: actor scheduler started in 2 ms
08:31:08.143 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [2/10]: membership and replication protocol
08:31:08.143 [] [Thread-768] DEBUG io.zeebe.broker.clustering - Member 1 will contact node: 0.0.0.0:27840
08:31:08.144 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27852 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=53}
08:31:08.144 [] [Thread-776] INFO  io.zeebe.broker.system - Version: 0.24.0-SNAPSHOT
08:31:08.144 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 27853 for test fork 2 with range PortRange{host='localhost', basePort=27800, maxOffset=100, currentOffset=54}
08:31:08.145 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/10]: membership and replication protocol started in 6 ms
08:31:08.145 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/10]: command api transport
08:31:08.145 [] [Thread-776] INFO  io.zeebe.broker.system - Starting broker 2 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "0MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 27849,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27849,
      "address" : "0.0.0.0:27849",
      "advertisedAddress" : "0.0.0.0:27849"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 27850,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27850,
      "address" : "0.0.0.0:27850",
      "advertisedAddress" : "0.0.0.0:27850"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 27851,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 27851,
      "address" : "0.0.0.0:27851",
      "advertisedAddress" : "0.0.0.0:27851"
    },
    "maxMessageSizeInBytes" : 8192
  },
  "cluster" : {
    "initialContactPoints" : [ "0.0.0.0:27840" ],
    "partitionIds" : [ 1 ],
    "nodeId" : 2,
    "partitionsCount" : 1,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster-1",
    "gossipFailureTimeout" : 2000,
    "gossipInterval" : 150,
    "gossipProbeInterval" : 250
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/tmp/junit10189461558897322716/2/data" ],
    "logSegmentSize" : "0MB",
    "snapshotPeriod" : "PT1M",
    "logIndexDensity" : 50,
    "atomixStorageLevel" : "DISK",
    "logSegmentSizeInBytes" : 8192
  },
  "exporters" : { },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 27847,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:27850",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 27848
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
08:31:08.145 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [1/10]: actor scheduler
08:31:08.146 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [1/10]: actor scheduler started in 1 ms
08:31:08.146 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [2/10]: membership and replication protocol
08:31:08.146 [] [Thread-776] DEBUG io.zeebe.broker.clustering - Member 2 will contact node: 0.0.0.0:27840
08:31:08.146 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [2/10]: membership and replication protocol started in 3 ms
08:31:08.146 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [3/10]: command api transport
08:31:08.148 [] [Thread-763] DEBUG io.zeebe.broker.system - Bound command API to 0.0.0.0:27839 
08:31:08.149 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/10]: command api transport started in 3 ms
08:31:08.149 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/10]: command api handler
08:31:08.149 [] [Thread-768] DEBUG io.zeebe.broker.system - Bound command API to 0.0.0.0:27844 
08:31:08.149 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [3/10]: command api transport started in 3 ms
08:31:08.149 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [4/10]: command api handler
08:31:08.149 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/10]: command api handler started in 0 ms
08:31:08.149 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/10]: subscription api
08:31:08.149 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/10]: subscription api started in 0 ms
08:31:08.149 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [4/10]: command api handler started in 0 ms
08:31:08.149 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/10]: cluster services
08:31:08.149 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [5/10]: subscription api
08:31:08.149 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [5/10]: subscription api started in 0 ms
08:31:08.149 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [6/10]: cluster services
08:31:08.150 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [2/10]: membership and replication protocol started in 4 ms
08:31:08.150 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [3/10]: command api transport
08:31:08.154 [] [Thread-776] DEBUG io.zeebe.broker.system - Bound command API to 0.0.0.0:27849 
08:31:08.154 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [3/10]: command api transport started in 4 ms
08:31:08.154 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [4/10]: command api handler
08:31:08.156 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [4/10]: command api handler started in 2 ms
08:31:08.156 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [5/10]: subscription api
08:31:08.156 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [5/10]: subscription api started in 0 ms
08:31:08.157 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [6/10]: cluster services
08:31:08.156 [] [atomix-0] WARN  io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService - Failed to locate partition group(s) via bootstrap nodes. Please ensure partition groups are configured either locally or remotely and the node is able to reach partition group members.
08:31:08.157 [] [atomix-0] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=1, group=raft-partition}
08:31:08.157 [] [atomix-0] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=1, group=raft-partition}
08:31:08.179 [] [atomix-0] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=1, group=raft-partition}
08:31:08.182 [] [raft-server-1-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
08:31:08.182 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
08:31:08.193 [] [raft-server-2-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
08:31:09.178 [] [raft-partition-group-raft-partition-0] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
08:31:09.179 [] [main] INFO  io.zeebe.gateway - Version: 0.24.0-SNAPSHOT
08:31:09.184 [] [main] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 27852,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "0.0.0.0:27840",
    "requestTimeout" : "PT45S",
    "clusterName" : "zeebe-cluster-1",
    "memberId" : "gateway",
    "host" : "0.0.0.0",
    "port" : 27853
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "0.0.0.0",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  }
}
08:31:11.600 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from null in the last PT3.417S (calculated from last 3417 ms), sending poll requests
08:31:11.604 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE
08:31:11.605 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Starting election
08:31:11.665 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to LEADER
08:31:11.665 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 0
08:31:11.671 [] [raft-server-2-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 0
08:31:11.672 [] [raft-server-1-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 0
08:31:11.683 [] [raft-partition-group-raft-partition-0] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
08:31:11.683 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/10]: cluster services started in 3534 ms
08:31:11.684 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/10]: topology manager
08:31:11.684 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/10]: topology manager started in 0 ms
08:31:11.684 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/10]: metric's server
08:31:11.686 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/10]: metric's server started in 2 ms
08:31:11.686 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/10]: leader management request handler
08:31:11.686 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [9/10]: leader management request handler started in 0 ms
08:31:11.686 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/10]: zeebe partitions
08:31:11.686 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
08:31:11.691 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Removing follower partition service for partition PartitionId{id=1, group=raft-partition}
08:31:11.691 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER
08:31:11.691 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Installing leader partition service for partition PartitionId{id=1, group=raft-partition}
08:31:11.693 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: []
08:31:11.905 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {} and terms {}.
08:31:11.968 [] [raft-partition-group-raft-partition-0] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
08:31:11.968 [] [raft-partition-group-raft-partition-0] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
08:31:11.969 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [6/10]: cluster services started in 3819 ms
08:31:11.969 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [6/10]: cluster services started in 3812 ms
08:31:11.969 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [7/10]: topology manager
08:31:11.969 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [7/10]: topology manager
08:31:11.969 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [7/10]: topology manager started in 0 ms
08:31:11.969 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [8/10]: metric's server
08:31:11.970 [Broker-2-TopologyManager] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 0, partitions {} terms {}
08:31:11.970 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [7/10]: topology manager started in 1 ms
08:31:11.970 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [8/10]: metric's server
08:31:11.971 [Broker-1-TopologyManager] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 0, partitions {} terms {}
08:31:11.972 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [8/10]: metric's server started in 3 ms
08:31:11.972 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [9/10]: leader management request handler
08:31:11.972 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [9/10]: leader management request handler started in 0 ms
08:31:11.972 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 [10/10]: zeebe partitions
08:31:11.972 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 partitions [1/1]: partition 1
08:31:11.973 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Removing leader partition services for partition PartitionId{id=1, group=raft-partition}
08:31:11.973 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [8/10]: metric's server started in 3 ms
08:31:11.973 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [9/10]: leader management request handler
08:31:11.973 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Partition role transitioning from null to FOLLOWER
08:31:11.973 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Installing follower partition service for partition PartitionId{id=1, group=raft-partition}
08:31:11.973 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [9/10]: leader management request handler started in 0 ms
08:31:11.973 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [10/10]: zeebe partitions
08:31:11.973 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 partitions [1/1]: partition 1
08:31:11.974 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.system - Removing leader partition services for partition PartitionId{id=1, group=raft-partition}
08:31:11.975 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.system - Partition role transitioning from null to FOLLOWER
08:31:11.975 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.system - Installing follower partition service for partition PartitionId{id=1, group=raft-partition}
08:31:11.980 [Broker-2-HealthCheckService] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
08:31:11.981 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 partitions [1/1]: partition 1 started in 8 ms
08:31:11.981 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 partitions succeeded. Started 1 steps in 9 ms.
08:31:11.981 [] [Thread-776] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [10/10]: zeebe partitions started in 9 ms
08:31:11.981 [] [Thread-776] INFO  io.zeebe.broker.system - Bootstrap Broker-2 succeeded. Started 10 steps in 3836 ms.
08:31:11.982 [Broker-1-HealthCheckService] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
08:31:11.983 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 partitions [1/1]: partition 1 started in 10 ms
08:31:11.983 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 partitions succeeded. Started 1 steps in 10 ms.
08:31:11.983 [] [Thread-768] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [10/10]: zeebe partitions started in 10 ms
08:31:11.983 [] [Thread-768] INFO  io.zeebe.broker.system - Bootstrap Broker-1 succeeded. Started 10 steps in 3842 ms.
08:31:12.068 [Broker-0-TopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 1, partitions {1=FOLLOWER} terms {}
08:31:12.068 [Broker-2-TopologyManager] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 1, partitions {1=FOLLOWER} terms {}
08:31:12.078 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 2, partitions {1=FOLLOWER} terms {}
08:31:12.079 [Broker-0-TopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 2, partitions {1=FOLLOWER} terms {}
08:31:12.170 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 1, partitions {1=FOLLOWER} and terms {}.
08:31:12.170 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 2, partitions {1=FOLLOWER} and terms {}.
08:31:13.486 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/runtime'.
08:31:13.489 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
08:31:13.490 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
08:31:13.490 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@6f5e17b4)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@1a2e1fd1, configuration: Configuration(false)]
08:31:13.491 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
08:31:13.492 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@6ba6f1f4)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@745ab883, configuration: Configuration(false)]
08:31:13.492 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@1e60e14e)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@336d386f, configuration: Configuration(false)]
08:31:13.494 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
08:31:13.495 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 1804 ms
08:31:13.495 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 1809 ms.
08:31:13.495 [] [Thread-763] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/10]: zeebe partitions started in 1809 ms
08:31:13.495 [] [Thread-763] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 10 steps in 5358 ms.
08:31:13.563 [Broker-1-TopologyManager] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 0, partitions {1=LEADER} terms {1=1}
08:31:13.564 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER} and terms {1=1}.
08:31:13.581 [] [main] INFO  io.zeebe.broker.system - Full replication factor
08:31:13.591 [] [main] INFO  io.zeebe.broker.system - All brokers in topology TopologyImpl{brokers=[BrokerInfoImpl{nodeId=0, host='0.0.0.0', port=27839, version=0.24.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=LEADER}]}, BrokerInfoImpl{nodeId=1, host='0.0.0.0', port=27844, version=0.24.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=FOLLOWER}]}, BrokerInfoImpl{nodeId=2, host='0.0.0.0', port=27849, version=0.24.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=FOLLOWER}]}], clusterSize=3, partitionsCount=1, replicationFactor=3, gatewayVersion=0.24.0-SNAPSHOT}
08:31:13.664 [Broker-2-TopologyManager] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 0, partitions {1=LEADER} terms {1=1}
08:31:15.279 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {Raft-1=HEALTHY, Broker-0-StreamProcessor-1=UNHEALTHY, logStream=HEALTHY}
08:31:15.279 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] ERROR io.zeebe.broker.system - Partition-1 failed, marking it as unhealthy
08:31:15.279 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Taking temporary snapshot into /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/pushed-pending/49-1-1589445075279.
08:31:15.473 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Created snapshot for Broker-0-StreamProcessor-1
08:31:15.473 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 4294981208 is committed, current commit position is 4294981056. After that snapshot can be marked as valid.
08:31:15.473 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Current commit position 4294981208 is greater then 4294981208, snapshot is valid.
08:31:15.474 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Purging snapshots older than DbSnapshot{directory=/tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279, metadata=DbSnapshotMetadata{index=49, term=1, timestamp=2020-05-14 08:31:15,279}}
08:31:15.475 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Search for orphaned snapshots below oldest valid snapshot with index 49 in /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/pushed-pending
08:31:15.475 [Broker-0-DeletionService-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.logstreams.delete - Compacting Atomix log up to index 49
08:31:15.475 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279, metadata=DbSnapshotMetadata{index=49, term=1, timestamp=2020-05-14 08:31:15,279}}
08:31:15.475 [] [raft-server-0-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - ZeebeRaftStateMachine1{partition=raft-partition-partition-1} - Compacting log up from 45 up to {}
08:31:15.475 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Start replicating latest snapshot /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279
08:31:15.476 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279/000092.sst
08:31:15.477 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279/000093.sst
08:31:15.477 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279/000094.sst
08:31:15.478 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279/000095.sst
08:31:15.478 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279/000096.sst
08:31:15.478 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279/CURRENT
08:31:15.479 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279/MANIFEST-000004
08:31:15.478 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000092.sst of snapshot 49-1-1589445075279
08:31:15.479 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000092.sst of snapshot 49-1-1589445075279
08:31:15.479 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 1/8
08:31:15.479 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/snapshots/49-1-1589445075279/OPTIONS-000090
08:31:15.479 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 1/8
08:31:15.479 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000093.sst of snapshot 49-1-1589445075279
08:31:15.479 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 2/8
08:31:15.479 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000093.sst of snapshot 49-1-1589445075279
08:31:15.479 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000094.sst of snapshot 49-1-1589445075279
08:31:15.480 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 2/8
08:31:15.480 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 3/8
08:31:15.480 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000095.sst of snapshot 49-1-1589445075279
08:31:15.480 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000094.sst of snapshot 49-1-1589445075279
08:31:15.480 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 4/8
08:31:15.480 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 3/8
08:31:15.480 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000096.sst of snapshot 49-1-1589445075279
08:31:15.480 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 5/8
08:31:15.480 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000095.sst of snapshot 49-1-1589445075279
08:31:15.481 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk CURRENT of snapshot 49-1-1589445075279
08:31:15.481 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 4/8
08:31:15.481 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 6/8
08:31:15.481 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk MANIFEST-000004 of snapshot 49-1-1589445075279
08:31:15.481 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000096.sst of snapshot 49-1-1589445075279
08:31:15.481 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 7/8
08:31:15.481 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 5/8
08:31:15.481 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk CURRENT of snapshot 49-1-1589445075279
08:31:15.481 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 6/8
08:31:15.482 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk MANIFEST-000004 of snapshot 49-1-1589445075279
08:31:15.482 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 7/8
08:31:15.482 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk OPTIONS-000090 of snapshot 49-1-1589445075279
08:31:15.482 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Received all snapshot chunks (8/8), snapshot is valid
08:31:15.482 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk OPTIONS-000090 of snapshot 49-1-1589445075279
08:31:15.483 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Received all snapshot chunks (8/8), snapshot is valid
08:31:15.483 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Purging snapshots older than DbSnapshot{directory=/tmp/junit10189461558897322716/2/data/raft-partition/partitions/1/snapshots/49-1-1589445075279, metadata=DbSnapshotMetadata{index=49, term=1, timestamp=2020-05-14 08:31:15,279}}
08:31:15.484 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Search for orphaned snapshots below oldest valid snapshot with index 49 in /tmp/junit10189461558897322716/2/data/raft-partition/partitions/1/pushed-pending
08:31:15.484 [Broker-2-DeletionService-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.logstreams.delete - Compacting Atomix log up to index 49
08:31:15.484 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/tmp/junit10189461558897322716/2/data/raft-partition/partitions/1/snapshots/49-1-1589445075279, metadata=DbSnapshotMetadata{index=49, term=1, timestamp=2020-05-14 08:31:15,279}}
08:31:15.484 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Purging snapshots older than DbSnapshot{directory=/tmp/junit10189461558897322716/1/data/raft-partition/partitions/1/snapshots/49-1-1589445075279, metadata=DbSnapshotMetadata{index=49, term=1, timestamp=2020-05-14 08:31:15,279}}
08:31:15.484 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Search for orphaned snapshots below oldest valid snapshot with index 49 in /tmp/junit10189461558897322716/1/data/raft-partition/partitions/1/pushed-pending
08:31:15.484 [] [raft-server-2-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - ZeebeRaftStateMachine1{partition=raft-partition-partition-1} - Compacting log up from 45 up to {}
08:31:15.484 [Broker-1-DeletionService-1] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.logstreams.delete - Compacting Atomix log up to index 49
08:31:15.484 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/tmp/junit10189461558897322716/1/data/raft-partition/partitions/1/snapshots/49-1-1589445075279, metadata=DbSnapshotMetadata{index=49, term=1, timestamp=2020-05-14 08:31:15,279}}
08:31:15.484 [] [raft-server-1-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.ZeebeRaftStateMachine - ZeebeRaftStateMachine1{partition=raft-partition-partition-1} - Compacting log up from 45 up to {}
08:31:25.607 [] [main] INFO  io.zeebe.test.records - Test failed, following records where exported:
08:31:25.613 [] [ForkJoinPool.commonPool-worker-3] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
08:31:25.698 [] [main] DEBUG io.zeebe.gateway - Closing gateway broker client ...
08:31:25.864 [] [main] DEBUG io.zeebe.gateway - topology manager closed
08:31:25.866 [] [main] DEBUG io.zeebe.gateway - Gateway broker client closed.
08:31:25.866 [] [main] DEBUG io.zeebe.broker.system - Closing ClusteringRule...
08:31:25.867 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [1/10]: zeebe partitions
08:31:25.867 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1
08:31:25.867 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-0-SnapshotDirector-1
08:31:25.867 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-0-SnapshotDirector-1 successfully
08:31:25.867 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-0-StreamProcessor-1
08:31:25.867 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
08:31:25.867 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-0-StreamProcessor-1 successfully
08:31:25.867 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-0-DeletionService-1
08:31:25.867 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-0-DeletionService-1 successfully
08:31:25.989 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/junit10189461558897322716/0/data/raft-partition/partitions/1/runtime'.
08:31:25.989 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream raft-partition-partition-1
08:31:25.989 [raft-partition-partition-1-write-buffer] [Broker-0-zb-actors-0] DEBUG io.zeebe.dispatcher - Dispatcher closed
08:31:25.989 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - On closing logstream raft-partition-partition-1 close 2 readers
08:31:25.990 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Close log storage with name raft-partition-partition-1
08:31:25.990 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1 closed in 123 ms
08:31:25.990 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions succeeded. Closed 1 steps in 123 ms.
08:31:25.990 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [1/10]: zeebe partitions closed in 123 ms
08:31:25.990 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [2/10]: leader management request handler
08:31:25.990 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [2/10]: leader management request handler closed in 0 ms
08:31:25.990 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [3/10]: metric's server
08:31:26.293 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [3/10]: metric's server closed in 303 ms
08:31:26.293 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [4/10]: topology manager
08:31:26.293 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [4/10]: topology manager closed in 0 ms
08:31:26.293 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [5/10]: cluster services
08:31:26.293 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [5/10]: cluster services closed in 0 ms
08:31:26.293 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [6/10]: subscription api
08:31:26.294 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [6/10]: subscription api closed in 1 ms
08:31:26.294 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [7/10]: command api handler
08:31:26.294 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [7/10]: command api handler closed in 0 ms
08:31:26.294 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [8/10]: command api transport
08:31:28.869 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [8/10]: command api transport closed in 2575 ms
08:31:28.869 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [9/10]: membership and replication protocol
08:31:28.872 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
08:31:28.878 [] [ForkJoinPool.commonPool-worker-15] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
08:31:29.407 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received REACHABILITY_CHANGED from member 0, was not handled.
08:31:29.462 [Broker-2-TopologyManager] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received REACHABILITY_CHANGED from member 0, was not handled.
08:31:31.093 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [9/10]: membership and replication protocol closed in 2224 ms
08:31:31.093 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [10/10]: actor scheduler
08:31:31.095 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [10/10]: actor scheduler closed in 0 ms
08:31:31.095 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 10 steps in 5228 ms.
08:31:31.095 [] [main] INFO  io.zeebe.broker.system - Broker shut down.
08:31:31.095 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [1/10]: zeebe partitions
08:31:31.095 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 partitions [1/1]: partition 1
08:31:31.095 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Broker-1-DeletionService-1
08:31:31.095 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.system - Closed Broker-1-DeletionService-1 successfully
08:31:31.096 [Broker-1-LogStream-1] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - On closing logstream raft-partition-partition-1 close 1 readers
08:31:31.096 [Broker-1-LogStream-1] [Broker-1-zb-actors-1] INFO  io.zeebe.logstreams - Close log storage with name raft-partition-partition-1
08:31:31.096 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 partitions [1/1]: partition 1 closed in 1 ms
08:31:31.096 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 partitions succeeded. Closed 1 steps in 1 ms.
08:31:31.096 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [1/10]: zeebe partitions closed in 1 ms
08:31:31.096 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [2/10]: leader management request handler
08:31:31.097 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [2/10]: leader management request handler closed in 1 ms
08:31:31.097 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [3/10]: metric's server
08:31:31.100 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [3/10]: metric's server closed in 3 ms
08:31:31.100 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [4/10]: topology manager
08:31:31.101 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [4/10]: topology manager closed in 1 ms
08:31:31.101 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [5/10]: cluster services
08:31:31.101 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [5/10]: cluster services closed in 0 ms
08:31:31.101 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [6/10]: subscription api
08:31:31.101 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [6/10]: subscription api closed in 0 ms
08:31:31.101 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [7/10]: command api handler
08:31:31.101 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [7/10]: command api handler closed in 0 ms
08:31:31.101 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [8/10]: command api transport
08:31:31.561 [] [raft-server-1-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Known leader 0 was removed from cluster, sending poll requests
08:31:31.563 [Broker-2-TopologyManager] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received member removed BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=3, replicationFactor=3, partitionRoles={1=LEADER}, partitionLeaderTerms={1=1}, version=0.24.0-SNAPSHOT} 
08:31:31.566 [] [raft-server-2-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Known leader 0 was removed from cluster, sending poll requests
08:31:31.569 [] [raft-server-1-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - java.net.ConnectException
08:31:31.569 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - java.net.ConnectException
08:31:31.570 [] [raft-server-1-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted PollRequest{term=1, candidate=2, lastLogIndex=89, lastLogTerm=1}: candidate's log is up-to-date
08:31:31.570 [] [raft-server-2-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE
08:31:31.571 [] [raft-server-2-raft-partition-partition-1] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Starting election
08:31:31.578 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - java.net.ConnectException
08:31:31.578 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Partition role transitioning from FOLLOWER to CANDIDATE
08:31:31.583 [] [raft-server-1-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=2, candidate=2, lastLogIndex=89, lastLogTerm=1}: candidate's log is up-to-date
08:31:31.586 [] [raft-server-2-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to LEADER
08:31:31.587 [] [raft-server-2-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 2
08:31:31.590 [] [raft-server-1-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 2
08:31:31.590 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - ConfigureRequest{term=2, leader=2, index=0, timestamp=1589445068190, members=[DefaultRaftMember{id=0, type=ACTIVE, updated=2020-05-14T08:31:08.190344Z}, DefaultRaftMember{id=2, type=ACTIVE, updated=2020-05-14T08:31:08.190344Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-05-14T08:31:08.190344Z}]} to 0 failed: java.util.concurrent.CompletionException: java.net.ConnectException
08:31:31.591 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - ConfigureRequest{term=2, leader=2, index=0, timestamp=1589445068190, members=[DefaultRaftMember{id=0, type=ACTIVE, updated=2020-05-14T08:31:08.190344Z}, DefaultRaftMember{id=2, type=ACTIVE, updated=2020-05-14T08:31:08.190344Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-05-14T08:31:08.190344Z}]} to 0 failed: java.util.concurrent.CompletionException: java.net.ConnectException
08:31:31.595 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - ConfigureRequest{term=2, leader=2, index=0, timestamp=1589445068190, members=[DefaultRaftMember{id=0, type=ACTIVE, updated=2020-05-14T08:31:08.190344Z}, DefaultRaftMember{id=2, type=ACTIVE, updated=2020-05-14T08:31:08.190344Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-05-14T08:31:08.190344Z}]} to 0 failed: java.util.concurrent.CompletionException: java.net.ConnectException
08:31:31.599 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Removing follower partition service for partition PartitionId{id=1, group=raft-partition}
08:31:31.599 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-2-DeletionService-1
08:31:31.599 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Partition role transitioning from CANDIDATE to LEADER
08:31:31.599 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-2-DeletionService-1 successfully
08:31:31.599 [Broker-2-LogStream-1] [Broker-2-zb-actors-0] INFO  io.zeebe.logstreams - On closing logstream raft-partition-partition-1 close 1 readers
08:31:31.600 [Broker-2-LogStream-1] [Broker-2-zb-actors-0] INFO  io.zeebe.logstreams - Close log storage with name raft-partition-partition-1
08:31:31.600 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Installing leader partition service for partition PartitionId{id=1, group=raft-partition}
08:31:31.608 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: [SnapshotImpl{path=/tmp/junit10189461558897322716/2/data/raft-partition/partitions/1/snapshots/49-1-1589445075279, compactionBound=49}]
08:31:32.128 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/junit10189461558897322716/2/data/raft-partition/partitions/1/runtime'.
08:31:32.128 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Recovered state from snapshot 'SnapshotImpl{path=/tmp/junit10189461558897322716/2/data/raft-partition/partitions/1/snapshots/49-1-1589445075279, compactionBound=49}'
08:31:32.130 [Broker-2-LogStream-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
08:31:32.131 [Broker-2-StreamProcessor-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
08:31:32.132 [Broker-2-StreamProcessor-1] [Broker-2-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@5dced7c0)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@74befa2f, configuration: Configuration(false)]
08:31:32.133 [Broker-2-StreamProcessor-1] [Broker-2-zb-actors-0] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position 4294981056
08:31:32.133 [Broker-2-StreamProcessor-1] [Broker-2-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@17c577d3)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@3c9ec23c, configuration: Configuration(false)]
08:31:32.134 [Broker-2-StreamProcessor-1] [Broker-2-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@3ff23802)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@7663bc7c, configuration: Configuration(false)]
08:31:33.309 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [8/10]: command api transport closed in 2208 ms
08:31:33.309 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [9/10]: membership and replication protocol
08:31:33.311 [] [raft-server-1-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
08:31:33.311 [] [ForkJoinPool.commonPool-worker-15] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
08:31:33.361 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - AppendRequest{term=2, leader=2, prevLogIndex=90, prevLogTerm=2, entries=0, commitIndex=90} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message
08:31:33.591 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - AppendRequest{term=2, leader=2, prevLogIndex=90, prevLogTerm=2, entries=0, commitIndex=90} to 1 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:27845
08:31:33.679 [Broker-2-TopologyManager] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received REACHABILITY_CHANGED from member 1, was not handled.
08:31:33.841 [] [raft-server-2-raft-partition-partition-1] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-1} - AppendRequest{term=2, leader=2, prevLogIndex=90, prevLogTerm=2, entries=0, commitIndex=90} to 1 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:27845
08:31:35.564 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [9/10]: membership and replication protocol closed in 2255 ms
08:31:35.564 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 [10/10]: actor scheduler
08:31:35.566 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-1 [10/10]: actor scheduler closed in 2 ms
08:31:35.566 [] [main] INFO  io.zeebe.broker.system - Closing Broker-1 succeeded. Closed 10 steps in 4471 ms.
08:31:35.566 [] [main] INFO  io.zeebe.broker.system - Broker shut down.
08:31:35.566 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [1/10]: zeebe partitions
08:31:35.566 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 partitions [1/1]: partition 1
08:31:35.566 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Broker-2-SnapshotDirector-1
08:31:35.566 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Closed Broker-2-SnapshotDirector-1 successfully
08:31:35.566 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Broker-2-StreamProcessor-1
08:31:35.566 [Broker-2-StreamProcessor-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-2-StreamProcessor-1.
08:31:35.567 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Closed Broker-2-StreamProcessor-1 successfully
08:31:35.567 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Broker-2-DeletionService-1
08:31:35.567 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - Closed Broker-2-DeletionService-1 successfully
08:31:35.604 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/junit10189461558897322716/2/data/raft-partition/partitions/1/runtime'.
08:31:35.604 [Broker-2-LogStream-1] [Broker-2-zb-actors-1] INFO  io.zeebe.logstreams - Close appender for log stream raft-partition-partition-1
08:31:35.604 [raft-partition-partition-1-write-buffer] [Broker-2-zb-actors-1] DEBUG io.zeebe.dispatcher - Dispatcher closed
08:31:35.605 [Broker-2-LogStream-1] [Broker-2-zb-actors-1] INFO  io.zeebe.logstreams - On closing logstream raft-partition-partition-1 close 2 readers
08:31:35.605 [Broker-2-LogStream-1] [Broker-2-zb-actors-1] INFO  io.zeebe.logstreams - Close log storage with name raft-partition-partition-1
08:31:35.605 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 partitions [1/1]: partition 1 closed in 39 ms
08:31:35.605 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 partitions succeeded. Closed 1 steps in 39 ms.
08:31:35.605 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [1/10]: zeebe partitions closed in 39 ms
08:31:35.605 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [2/10]: leader management request handler
08:31:35.605 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [2/10]: leader management request handler closed in 0 ms
08:31:35.605 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [3/10]: metric's server
08:31:35.608 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [3/10]: metric's server closed in 3 ms
08:31:35.608 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [4/10]: topology manager
08:31:35.608 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [4/10]: topology manager closed in 0 ms
08:31:35.608 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [5/10]: cluster services
08:31:35.608 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [5/10]: cluster services closed in 0 ms
08:31:35.608 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [6/10]: subscription api
08:31:35.608 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [6/10]: subscription api closed in 0 ms
08:31:35.608 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [7/10]: command api handler
08:31:35.608 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [7/10]: command api handler closed in 0 ms
08:31:35.608 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [8/10]: command api transport
08:31:37.869 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [8/10]: command api transport closed in 2261 ms
08:31:37.869 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [9/10]: membership and replication protocol
08:31:37.870 [] [raft-server-2-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
08:31:37.874 [] [ForkJoinPool.commonPool-worker-15] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
08:31:40.082 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [9/10]: membership and replication protocol closed in 2213 ms
08:31:40.082 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 [10/10]: actor scheduler
08:31:40.083 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-2 [10/10]: actor scheduler closed in 1 ms
08:31:40.083 [] [main] INFO  io.zeebe.broker.system - Closing Broker-2 succeeded. Closed 10 steps in 4517 ms.
08:31:40.083 [] [main] INFO  io.zeebe.broker.system - Broker shut down.

</pre>
</details>

### PR DESCRIPTION
**Pull request by saig0**
## Description

* write more segments to ensure that the log can be compacted
* favor `waitUntil()` instead of `assertThat()` because the log is compacted asynchronously

## Related issues

closes #4519 
closes #4430

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by saig0** [comment]
I also saw that the `ClusteredDataDeletionTest` fails sometimes because the snapshot is not replicated to all followers. I guess that it is related to #4648. 

<details>
<summary>Log output</summary>

```
11:25:25.814 [Broker-2-HealthCheckService] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
11:25:25.814 [Broker-1-HealthCheckService] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
11:25:25.814 [] [Thread-1471] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 partitions [1/1]: partition 1 started in 4 ms
11:25:25.814 [] [Thread-1471] INFO  io.zeebe.broker.system - Bootstrap Broker-2 partitions succeeded. Started 1 steps in 5 ms.
11:25:25.814 [] [Thread-1464] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 partitions [1/1]: partition 1 started in 5 ms
11:25:25.814 [] [Thread-1471] DEBUG io.zeebe.broker.system - Bootstrap Broker-2 [10/10]: zeebe partitions started in 5 ms
11:25:25.814 [] [Thread-1464] INFO  io.zeebe.broker.system - Bootstrap Broker-1 partitions succeeded. Started 1 steps in 5 ms.
11:25:25.814 [] [Thread-1471] INFO  io.zeebe.broker.system - Bootstrap Broker-2 succeeded. Started 10 steps in 3762 ms.
11:25:25.814 [] [Thread-1464] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [10/10]: zeebe partitions started in 5 ms
11:25:25.814 [] [Thread-1464] INFO  io.zeebe.broker.system - Bootstrap Broker-1 succeeded. Started 10 steps in 3788 ms.
11:25:25.907 [Broker-1-TopologyManager] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 2, partitions {1=FOLLOWER} terms {}
11:25:25.907 [Broker-0-TopologyManager] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 2, partitions {1=FOLLOWER} terms {}
11:25:25.954 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 2, partitions {1=FOLLOWER} and terms {}.
11:25:25.954 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 1, partitions {1=FOLLOWER} and terms {}.
11:25:25.954 [Broker-2-TopologyManager] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 1, partitions {1=FOLLOWER} terms {}
11:25:26.038 [Broker-0-TopologyManager] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 1, partitions {1=FOLLOWER} terms {}
11:25:26.949 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/junit3126396394269813422/0/data/raft-partition/partitions/1/runtime'.
11:25:27.006 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
11:25:27.007 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
11:25:27.007 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@2bf5f024)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@22ebac51, configuration: Configuration(false)]
11:25:27.008 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
11:25:27.009 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@450d662e)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@417dca7b, configuration: Configuration(false)]
11:25:27.009 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@3e0b6f21)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@5cae8389, configuration: Configuration(false)]
11:25:27.011 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
11:25:27.011 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
11:25:27.012 [] [Thread-1459] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 1471 ms
11:25:27.012 [] [Thread-1459] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 1471 ms.
11:25:27.012 [] [Thread-1459] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/10]: zeebe partitions started in 1472 ms
11:25:27.012 [] [Thread-1459] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 10 steps in 4989 ms.
11:25:27.012 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovered exporter 'Broker-0-Exporter-1' from snapshot at lastExportedPosition -1
11:25:27.012 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'data-delete-test-exporter'
11:25:27.012 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={EVENT=true, COMMAND_REJECTION=true, COMMAND=true, SBE_UNKNOWN=true, NULL_VAL=true}, acceptValueTypes={JOB=true, DEPLOYMENT=true, WORKFLOW_INSTANCE=true, WORKFLOW_INSTANCE_CREATION=true, WORKFLOW_INSTANCE_RESULT=true, WORKFLOW_INSTANCE_SUBSCRIPTION=true, TIMER=true, ERROR=true, INCIDENT=true, MESSAGE_SUBSCRIPTION=true, JOB_BATCH=true, VARIABLE_DOCUMENT=true, NULL_VAL=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, SBE_UNKNOWN=true, VARIABLE=true, MESSAGE=true}}
11:25:27.012 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Open exporter with id 'data-delete-test-exporter'
11:25:27.207 [Broker-1-TopologyManager] [Broker-1-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 0, partitions {1=LEADER} terms {1=1}
11:25:27.207 [GatewayTopologyManager] [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER} and terms {1=1}.
11:25:27.207 [Broker-2-TopologyManager] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 0, partitions {1=LEADER} terms {1=1}
11:25:27.237 [] [main] INFO  io.zeebe.broker.system - Full replication factor
11:25:27.243 [] [main] INFO  io.zeebe.broker.system - All brokers in topology TopologyImpl{brokers=[BrokerInfoImpl{nodeId=0, host='0.0.0.0', port=27873, version=0.24.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=LEADER}]}, BrokerInfoImpl{nodeId=2, host='0.0.0.0', port=27883, version=0.24.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=FOLLOWER}]}, BrokerInfoImpl{nodeId=1, host='0.0.0.0', port=27878, version=0.24.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=FOLLOWER}]}], clusterSize=3, partitionsCount=1, replicationFactor=3, gatewayVersion=0.24.0-SNAPSHOT}
11:25:27.707 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=2, version=1, index=45}
11:25:27.709 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=2, version=1, index=45}
11:25:27.709 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=2, version=1, index=45}
11:25:28.120 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=3, version=1, index=88}
11:25:28.121 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=3, version=1, index=88}
11:25:28.121 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=3, version=1, index=88}
11:25:28.615 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=4, version=1, index=131}
11:25:28.617 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=4, version=1, index=131}
11:25:28.617 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=4, version=1, index=131}
11:25:29.038 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=5, version=1, index=174}
11:25:29.041 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=5, version=1, index=174}
11:25:29.042 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=5, version=1, index=174}
11:25:29.523 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=6, version=1, index=217}
11:25:29.524 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=6, version=1, index=217}
11:25:29.524 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=6, version=1, index=217}
11:25:29.840 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=7, version=1, index=260}
11:25:29.841 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=7, version=1, index=260}
11:25:29.841 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=7, version=1, index=260}
11:25:30.171 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=8, version=1, index=303}
11:25:30.172 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=8, version=1, index=303}
11:25:30.212 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=8, version=1, index=303}
11:25:30.448 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=9, version=1, index=345}
11:25:30.450 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=9, version=1, index=345}
11:25:30.450 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=9, version=1, index=345}
11:25:30.906 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=10, version=1, index=387}
11:25:30.908 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=10, version=1, index=387}
11:25:30.908 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=10, version=1, index=387}
11:25:31.417 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=11, version=1, index=429}
11:25:31.420 [] [raft-server-1-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=11, version=1, index=429}
11:25:31.420 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=11, version=1, index=429}
11:25:31.431 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Taking temporary snapshot into /tmp/junit3126396394269813422/0/data/raft-partition/partitions/1/pending/399-1-1592565931431.
11:25:31.610 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Created snapshot for Broker-0-StreamProcessor-1
11:25:31.611 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] INFO  io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 21474839832 is committed, current commit position is 21474839680. After that snapshot can be marked as valid.
11:25:31.611 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] INFO  io.zeebe.logstreams.snapshot - Current commit position 21474839832 is greater then 21474839832, snapshot is valid.
11:25:31.616 [Broker-0-DeletionService-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.logstreams.delete - Compacting Atomix log up to index 399
11:25:31.617 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - raft-partition-partition-1 - Compacting 9 segment(s)
11:25:31.617 [] [raft-server-0-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=1, version=1, index=1}
11:25:31.617 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 1/9
11:25:31.617 [] [raft-server-0-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=2, version=1, index=45}
11:25:31.618 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 2/9
11:25:31.618 [] [raft-server-0-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=3, version=1, index=88}
11:25:31.618 [] [raft-server-0-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=4, version=1, index=131}
11:25:31.618 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 3/9
11:25:31.619 [] [raft-server-0-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=5, version=1, index=174}
11:25:31.619 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 4/9
11:25:31.619 [] [raft-server-0-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=6, version=1, index=217}
11:25:31.619 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 5/9
11:25:31.619 [] [raft-server-0-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=7, version=1, index=260}
11:25:31.619 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 6/9
11:25:31.620 [] [raft-server-0-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=8, version=1, index=303}
11:25:31.620 [] [raft-server-0-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=9, version=1, index=345}
11:25:31.620 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 7/9
11:25:31.620 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 8/9
11:25:31.622 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Received all snapshot chunks (9/9), snapshot is valid
11:25:31.627 [Broker-2-DeletionService-1] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.logstreams.delete - Compacting Atomix log up to index 399
11:25:31.627 [] [raft-server-2-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - raft-partition-partition-1 - Compacting 9 segment(s)
11:25:31.628 [] [raft-server-2-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=1, version=1, index=1}
11:25:31.628 [] [raft-server-2-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=2, version=1, index=45}
11:25:31.628 [] [raft-server-2-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=3, version=1, index=88}
11:25:31.629 [] [raft-server-2-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=4, version=1, index=131}
11:25:31.629 [] [raft-server-2-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=5, version=1, index=174}
11:25:31.630 [] [raft-server-2-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=6, version=1, index=217}
11:25:31.630 [] [raft-server-2-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=7, version=1, index=260}
11:25:31.630 [] [Broker-1-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 1/9
11:25:31.630 [] [raft-server-2-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=8, version=1, index=303}
11:25:31.630 [] [raft-server-2-raft-partition-partition-1] TRACE io.atomix.storage.journal.SegmentedJournal - Deleting segment: JournalSegment{id=9, version=1, index=345}
11:26:31.437 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] WARN  io.zeebe.logstreams.snapshot - Failed to obtain a pending snapshot directory for position 21474839680
11:27:11.761 [] [main] INFO  io.zeebe.test.records - Test failed, following records where exported:
```

</details>

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java [hunk 1]
```diff
@@ -58,46 +65,62 @@ public void shouldNotCompactNotExportedEvents() {
...
-    // write one more to make sure last processed position in segment 3
-    writeToLog();
-
-    // increase snapshot interval and wait
+    // - trigger a snapshot creation
     clusteringRule.getClock().addTime(SNAPSHOT_PERIOD);
     final var firstSnapshot = clusteringRule.waitForSnapshotAtBroker(broker);
 
-    // then
+    // then verify that the log still contains the records that are not exported
```
Comment (deepthidevaki) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java:80]: Before this we should also verify that the compaction is completed, right? `waitUntil(getSegmentsCount() < segmentsBeforeSnapshot` . Otherwise we may not be verifying the state after compaction.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteredDataDeletionTest.java [hunk 2]
```diff
@@ -90,22 +94,19 @@ public void shouldDeleteDataOnLeader() {
...
+    fillSegments(List.of(leader), SEGMENT_COUNT);
 
     // when
-    final var segmentCount =
+    final var segmentCountBeforeSnapshot =
         takeSnapshotAndWaitForReplication(Collections.singletonList(leader), clusteringRule);
 
     // then
-    TestUtil.waitUntil(() -> getSegments(leader).size() < segmentCount.get(leaderNodeId));
+    waitUntil(
```
Comment (deepthidevaki) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteredDataDeletionTest.java:104]: Nit: 
```suggestion
  Awaitility.await()
        .untilAsserted(
            () ->
                assertThat(getSegmentsCount(leader))
                    .isLessThan(segmentCountBeforeSnapshot.get(leaderNodeId)));
```

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks. Only a minor comment.
Also wondering why you had to increase the segments count. Could be related to this https://github.com/zeebe-io/zeebe/issues/4373.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java (hunk 1 above)
Comment (saig0) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java:80]: :+1: 

> we may not be verifying the state after compaction

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteredDataDeletionTest.java (hunk 2 above)
Comment (saig0) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteredDataDeletionTest.java:104]: Do you suggest to replace our `TestUtil`? :sweat_smile:

Comment (deepthidevaki) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteredDataDeletionTest.java:104]: :D We had some discussions before about starting to use Awaitility instead of our own `waitUntil`. This looks like a good place to use it.

Comment (Zelldon) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteredDataDeletionTest.java:104]: We already use it for example here https://github.com/zeebe-io/zeebe/blob/379afe7174267f168d967b09d295e5b5ab0fd6c4/atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java#L385-L387

**Comment by saig0** [comment]
@deepthidevaki, I applied your review hints. Please have a look :)

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteredDataDeletionTest.java (hunk 2 above)
Comment (saig0) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteredDataDeletionTest.java]: Ok :+1: If we plan to replace the `TestUtil` then we should create an issue and communicate it to the team.

**Review by deepthidevaki — APPROVED** [review]
:+1:

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java (hunk 1 above)
Comment (deepthidevaki) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java:89]: Ya. You are right. But I guess there is no other way to wait for compaction.
