### PR TITLE
fix(bpmn-model): inclusive gateway only allows default flow with cond…

### LINKED ISSUE #10310: Inclusive gateway only allows default flow with condition
**Describe the bug**

According to the spec (10.5.3 - page 293):
>The default Sequence Flow should not have a conditionExpression.
>Any such Expression SHALL be ignored.

However, processes with a default flow are required to have a condition in Zeebe currently, and this condition is evaluated.

**To Reproduce**

- deploy a process with inclusive gateway with multiply outgoing sequence flows with conditions and a default outgoing sequence flow
- notice the rejection

**Expected behavior**

- Inclusive gateway's default flow should be allowed to have a condition, but not be required
- Zeebe should not evaluate this condition.

### PR DESCRIPTION
**Pull request by skayliu**
## Description

This solves a bug that inclusive gateway only allows default flow with condition.

## Related issues

closes #10310 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [x] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks for this fix @skayliu 🏅 

👍 Now the default flow no longer requires a condition, while it still allows one.

>The default Sequence Flow should not have a conditionExpression.
> Any such Expression SHALL be ignored.

❌ We should make sure that the Condition of a default flow is not evaluated, i.e. it should be ignored. 

Please also add a test that verifies that no such condition (condition on default flow) is evaluated. For example, you could use a condition on the default flow that we expect to raise an incident when evaluated (e.g. `= missing_var` and then create an instance without that variable). The test can verify that no incident was created, while it could take the expected sequence flow(s).

As always, let me know if you need a hand with this. For the rest, great work! 🚀

**Comment by skayliu** [comment]
> ❌ We should make sure that the Condition of a default flow is not evaluated, i.e. it should be ignored.

You mean we should task the default sequence flow and not raise an incident even missing variable for the condition?

**Comment by korthout** [comment]
@skayliu We need to make sure that we do not evaluate the Condition on a sequence flow if that sequence flow is the Default flow.

The part about raising an incident is merely a test scenario in which we can verify that the condition is not evaluated. When we evaluate an expression that refers to a variable that is missing, then an incident is created. So we can use that as a way to verify that an expression is, or is not evaluated. Does that make sense?

**Comment by skayliu** [comment]
@korthout,  i've resolve this, please review again.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java [hunk 1]
```diff
@@ -626,6 +626,50 @@ public void shouldCreateDeploymentInclusiveGatewayWithDefaultFlow() {
...
+            .conditionExpression("= contains(str,\"a\")")
+            .endEvent("end1")
+            .moveToLastGateway()
+            .sequenceFlowId("s2")
+            .conditionExpression("= contains(str,\"b\")")
+            .endEvent("end2")
+            .moveToLastInclusiveGateway()
+            .defaultFlow()
+            .sequenceFlowId("s3")
+            .conditionExpression("= contains(str,\"c\")")
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java]: What I meant was to change this to:
```suggestion
            .conditionExpression("= missing_var")
```

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java [hunk 2]
```diff
@@ -626,6 +626,50 @@ public void shouldCreateDeploymentInclusiveGatewayWithDefaultFlow() {
...
+            .endEvent("end3")
+            .done();
+    ENGINE.deployment().withXmlResource(processDefinition).deploy();
+
+    // when
+    final long processInstance =
+        ENGINE
+            .processInstance()
+            .ofBpmnProcessId(processId)
+            .withVariable("missing_str", "d")
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java]: What I meant was not adding that var, but allowing the other conditions to evaluate correctly but not fulfilling them, so we need a `str` variable (e.g. containing an empty list):
```suggestion
            .withVariable(Map.of("str", List.of()))
```

**Comment by skayliu** [comment]
@korthout ,OK, I misunderstood, I'll fix it.

**Review by korthout — CHANGES_REQUESTED** [review]
Here are some of my ideas.

What I meant was to assert that the process instance completed, but that no incident was raised.

Something like:

```java
assertThat(RecordingExporter.records().limitToProcessInstance(processInstanceKey))
    .describedAs("Expect that the default flow is taken")
    .satisfies(
        record ->
            assertThat(
                    record.stream().filter(r -> r.getValueType() == ValueType.PROCESS_INSTANCE))
                .extracting(
                    r -> ((ProcessInstanceRecordValue) r.getValue()).getElementId(),
                    Record::getIntent)
                .containsSubsequence(
                    tuple("inclusive", ProcessInstanceIntent.ELEMENT_COMPLETED),
                    tuple("s2", ProcessInstanceIntent.SEQUENCE_FLOW_TAKEN),
                    tuple("end2", ProcessInstanceIntent.ELEMENT_COMPLETED)))
    .describedAs("Expect that the default flow's condition is not evaluated")
    .satisfies(
        r ->
            assertThat(r).extracting(Record::getIntent).doesNotContain(IncidentIntent.CREATED));
```

**Comment by skayliu** [comment]
@korthout, i've resolve this, please review again.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java [hunk 3]
```diff
@@ -74,7 +77,7 @@ public void shouldSplitOnInclusiveGateway() {
             .moveToLastInclusiveGateway()
             .defaultFlow()
             .sequenceFlowId("s3")
-            .conditionExpression("= contains(str,\"c\")")
+            .conditionExpression("= missing_var")
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java:80]: ❌ This condition is distracting a lot from the intent of this test case.

🔧 Let's make it more clear that the default condition is ignored here by changing the default flow's condition to `= true`

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java [hunk 4]
```diff
@@ -574,6 +562,104 @@ public void shouldCompleteScopeOnInclusiveGateway() {
...
+
+    // then
+    assertThat(deployment2.getKey())
+        .describedAs(
+            "Inclusive gateway's default flow should be allowed to have a condition, but not be required")
+        .isNotNegative();
+  }
+
+  @Test
+  public void shouldTakeDefaultFlowDoesNotRaiseIncident() {
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java:617]: 🔧 The intent of this test is to verify that the default flow's condition is not evaluated. Let's capture that in the test case name.

```suggestion
  public void shouldNotEvaluateConditionOfDefaultFlow() {
```

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayProcessor.java [hunk 5]
```diff
@@ -100,15 +100,19 @@ private Either<Failure, List<ExecutableSequenceFlow>> findSequenceFlowsToTake(
...
-          expressionBehavior.evaluateBooleanExpression(condition, context.getElementInstanceKey());
-      if (isFulfilledOrFailure.isLeft()) {
-        return Either.left(isFulfilledOrFailure.getLeft());
-
-      } else if (isFulfilledOrFailure.get()) {
-        // the condition is fulfilled
-        executableSequenceFlows.add(sequenceFlow);
+      if (element.getDefaultFlow() != null && element.getDefaultFlow() == sequenceFlow) {
+        continue;
+      } else {
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayProcessor.java:105]: 🔧 This can be simplified while remaining logically equivalent 
```suggestion
      if (element.getDefaultFlow() == null || element.getDefaultFlow() != sequenceFlow) {
```

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks for the changes! That's exactly what I meant! 🚀 

Please have a look at my last comments 🙇

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java [hunk 6]
```diff
@@ -127,22 +132,6 @@ public void shouldSplitOnInclusiveGateway() {
         .extracting(v -> tuple(v.getProcessInstanceKey(), v.getElementId()))
         .contains(tuple(processInstance3, "end3"));
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java:134]: Sorry I forgot this one:

🔧 We'll also need to change this one to: if no conditions are fulfilled, then the default flow is taken

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @skayliu I discovered that we missed one test case

Please update it and then this should be ready

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java (hunk 6 above)
Comment (skayliu) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java:134]: It's done.

**Review by korthout — APPROVED** [review]
👏 thanks for all the work @skayliu 

LGTM 👍 

bors merge
