### PR TITLE
fix(transport): avoid out-of-order requests

### LINKED ISSUE #13061: Cancel on-going remote stream registration on stream removal
**Describe the bug**

There is currently a potential race condition which would result in a remote stream existing server side, even though the client stream has gone away.

Since we register remote streams asynchronously, a remove request may be submitted client side, which will immediately remove it there. Then asynchronous removal requests are sent to the server. However, this can be interleaved with the asynchronous registration, resulting in a stream existing server side.

The impact is additional latency during a push, or possible unnecessary job activation if it was the last stream for this type. However, the stream will eventually get removed appropriately.

**Expected behavior**

Registration/removal of remote streams is sequenced, such that a removal request would cancel registration attempts, and queue the removal after whatever in-flight requests were sent are finished.

There is still a slight edge case around time outs, of course, but I think this is acceptable for now. The other option would be introducing even more coordination in the protocol, and I'd rather avoid this.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

Avoid out-of-order stream lifecycle requests by using a registration state machine which handles the state of the remote registration.

The registration keeps track of its remote state (`ADDING`, `ADDED`, `REMOVING`, `REMOVED`), and local state (`INITIAL` and `CLOSED`), as well as the single allowed in-flight request for itself. Note that registration are scoped per host, so we effectively have one registration per host per aggregated client stream. To know if a stream is connected to a specific host, we just check if its registration is in the `ADDED` state.

The `INITIAL` state allows transitioning to `ADDING` or `REMOVED`. An `ADD` operation can be started when in the `INITIAL` state only.

When that happens, an `ADD` request is sent, and the registration will transition to `ADDING`. Once a successful `ADD` response is received, it will transition to `ADDED` if it's still in the `ADDING` state. No further requests will be sent while it's in the `ADDING` state. When receiving an `ADD` response, the response is discarded if the state is not `ADDING` anymore or the request manager is closed.

At any point, a `REMOVE` operation can be started. If it is already in the `REMOVING` or `REMOVED` states, then nothing happens. If it's in the `INITIAL` state, then the registration immediately transitions to `REMOVED` and no request is sent out. If it's in the `ADDING` state, then it will wait until the request is finished (or times out) before sending the `REMOVE` request. This is done to reduce the likelihood of requests being processed out of order on the server side. If it's in the `ADDED` state, then a request is immediately sent out. Once it receives a successful response, the registration transitions to `REMOVED`. If unsuccessful, the request is retried. If at any point it receives a response but its state is not `REMOVING`, or the request manager is closed, then the response is discarded.

Finally, there's a `CLOSED` state which allows short-circuiting any existing operation. Registrations can transition to `CLOSED` from any state, but `CLOSED` is a terminal state. All asynchronous results will be discarded when closed.

## Related issues

closes #13061 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/AggregatedClientStream.java [hunk 1]
```diff
@@ -188,11 +182,27 @@ private void tryPush(
...
+      requestManager.add(registrationFor(serverId));
+    }
+  }
+
+  ClientStreamRegistration registrationFor(final MemberId serverId) {
+    if (!isOpened) {
+      // TODO: or return optional? anything but null
+      final var registration = new ClientStreamRegistration(streamId, logicalId, serverId);
+      registration.transitionToClosed();
+      return registration;
```
Comment (npepinpe) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/AggregatedClientStream.java:201]: Would like to challenge that - I definitely don't want to return null here, so we can return either an `Optional<ClientStreamRegistration>` (which is empty when closed) or an ephemeral, `CLOSED` registration.

**Comment by npepinpe** [comment]
So the main thing I'd like to challenge here is keeping track of the registrations in the `AggregatedClientStream` vs in the `ClientStreamRequestManager`. The drawback of keeping track of them in the `ClientStreamRequestManager` is we now have another source of map of maps, mapping the streams per host. The upside is the whole concept of registration state machines is implementation detail of the request manager. As it is now, by keeping track of them in the `AggregatedClientStream`, it's shared between both classes, and we need to "close" the `ClientStreamRequestManager` when we remove all to ensure no dangling asynchronous operations are performed after sending the `REMOVE_ALL` request (well, to reduce the likelihood).

**Comment by npepinpe** [comment]
The more I think about it, the more I'm leaning towards pushing the registrations to the `ClientStreamRequestManager`, and making registration an implementation detail there. I wouldn't have to change that much from the PR honestly, just revert back some of the changes in `ClientStreamManager` and `AggregatedClientStream`.

Let me know what you think.

**Comment by npepinpe** [comment]
Oops, I thought for sure I'd already requested a review :smile:

**Comment by deepthidevaki** [comment]
I couldn't get to this today. Will review tomorrow.

File: transport/src/main/java/io/camunda/zeebe/transport/stream/impl/ClientStreamRequestManager.java [hunk 2]
```diff
@@ -39,104 +46,204 @@ final class ClientStreamRequestManager<M extends BufferWriter> {
...
+      LOGGER.trace("Skip handling ADD response since the state is {}", state, error);
+      return;
+    }
+
+    if (error == null) {
+      registration.transitionToAdded();
+      return;
+    }
+
+    // TODO: define some abort conditions. We may not have to retry indefinitely.
```
Comment (deepthidevaki) [inline transport/src/main/java/io/camunda/zeebe/transport/stream/impl/ClientStreamRequestManager.java:191]: :wrench: I think this comment can be removed. Now the request will be retried only until the registration is marked as removing/removed.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
:rocket: I really like the handling of registration life cycle via state transitions. There is one major edge case that is not handled, if I'm not mistaken. 
- :x:  What happens if a `clientStream` is registered to a server. Then the server is disconnected and restarted. From, what I understood from the code, the registration remains in the ADDED state, so the clientStream is not re-registered with the re-started server.
   - :see_no_evil: Please also add a test for this case in `StreamIntegrationTest`.
   - Now keeping `ClientStreamRegistration` in the request manager makes sense. But I'm wondering if it changes with the solution to the above problem. I leave it up to you to decide. 
- :wrench: I think the `liveConnections` in `AggregatedClientStream` is not necessary anymore. It is only used in tests. Feel free to do it in a follow up.

**Comment by npepinpe** [comment]
Thanks, yeah, it's pretty obvious now that you point it out :sweat_smile:

There's a bigger issue with our topology listener though. Possibly if a server restarts fast enough before being removed, it wouldn't be added again to the set. So we'd want to also add the broker on every metadata change (just in case), as long as it's reachable. I'm on my phone now, so I can't check if we already do, but I don't think so. This would be tested at a higher level anyway, where I'm still missing some parts to properly test it.

I'm also not sure if we remove the registrations properly when a broker is removed, it's possible not. I'll double check.

**Comment by npepinpe** [comment]
I double checked, and we only call `brokerAdded` when it is new to the topology. If the node restarted before it was removed (so only the version would've changed or something), we could risk not detecting it was restarted, leading to missing server side streams.

Ah, if only this was just a gRPC stream :shrug:

**Comment by deepthidevaki** [comment]
> I double checked, and we only call `brokerAdded` when it is new to the topology. If the node restarted before it was removed (so only the version would've changed or something), we could risk not detecting it was restarted, leading to missing server side streams.
> 
> Ah, if only this was just a gRPC stream shrug

That is correct. https://camunda.slack.com/archives/C04G2F074UQ/p1685700205662889 . Chances of this happening can be low, though. I think we can try to address this in SWIM - something like what we discussed before to detect duplicate nodes https://camunda.slack.com/archives/C037RS2JHB8/p1684750547299219 

I think it is ok to address these two problems separately.

**Comment by npepinpe** [comment]
Yeah, [I opened another issue around this](https://github.com/camunda/zeebe/issues/13389). Likely the solution is to change something in our SWIM implementation to detect restarts.

**Comment by npepinpe** [comment]
I've added tests in `ClientStreamRequestManagerTest`, `ClientStreamManagerTest`, and `StreamIntegrationTest`. There's some overlap between the last two, but I think that's OK, as the one in `ClientStreamManagerTest` gives us a narrow scope to debug, and the one in `StreamIntegrationTest` tests with the actual implementations.

File: transport/src/test/java/io/camunda/zeebe/transport/stream/impl/StreamIntegrationTest.java [hunk 3]
```diff
@@ -318,6 +338,35 @@ void shouldRemoveAllStreamsOnClientShutdown() {
...
+      final var properties = new TestSerializableData();
+      final var streamId =
+          clientStreamer
+              .add(streamType, properties, p -> CompletableFuture.completedFuture(null))
+              .join();
+      awaitStreamAdded(streamType, streamId, server1, server2);
+      // since we can't really restart the server (at least until we can restart AtomixCluster
+      // instances), we'll just simulate it by removing it; this means the stream is still
+      // registered server side, so we only wait for it to be removed client side
+      client.streamService.onServerRemoved(server1.memberId());
```
Comment (deepthidevaki) [inline transport/src/test/java/io/camunda/zeebe/transport/stream/impl/StreamIntegrationTest.java:355]: :wrench: This would not have caught the bug, right? Can't we simulate restart by closing and creating a new server with same id? 
```
      server1.close();
      client.streamService.onServerRemoved(server1.memberId());
      awaitStreamOnClient(
          streamId,
          maybeStream -> {
            assertThat(maybeStream).isPresent();
            assertThat(maybeStream.get().isConnected(server1.memberId())).isFalse();
          });

      // when - reuse memberId of server1 to simulate restart
      final var restartedServer1 = new TestServer(createClusterNode(clusterNodes.get(0), clusterNodes));
      restartedServer1.start();
      client.streamService.onServerJoined(restartedServer1.memberId());
```

**Review by deepthidevaki — APPROVED** [review]
:rocket: Please check my comment before merging.

**Comment by npepinpe** [comment]
FYI I've kept live connections as part of the stream because of how useful it was to debug, and the more I work with this, the more I lean towards having actuators to show the registry states - it's very, very useful when debugging to see the state without having to do a heap dump :smile:

File: transport/src/test/java/io/camunda/zeebe/transport/stream/impl/StreamIntegrationTest.java (hunk 3 above)
Comment (npepinpe) [reply transport/src/test/java/io/camunda/zeebe/transport/stream/impl/StreamIntegrationTest.java:355]: You're right, I was being lazy and avoiding more refactoring - we can of course recreate the server entirely :+1:

Comment (npepinpe) [reply transport/src/test/java/io/camunda/zeebe/transport/stream/impl/StreamIntegrationTest.java:355]: Though I did test without the fix and the test failed, so it would catch something at least ;)

**Comment by npepinpe** [comment]
bors merge
