### PR TITLE
fix: TreePath properties not populated in some cases

### LINKED ISSUE #26048: Camunda Exporter is not able to consume treePath
**Describe the bug**

When running a benchmark we see endless [logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22ck-main-exporter%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zeebe-benchmark-test%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22;pinnedLogId=2024-12-12T21:20:50.685776443Z%2F6nksld3qseaqfa3z;cursorTimestamp=2024-12-12T21:20:50.691136797Z;duration=PT1H?inv=1&invt=Abj9IQ&project=zeebe-io) of:

```
No elementInstancePath is provided for flow node instance id: 6755399442562079. TreePath will be set to default value.
```

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description
- Populate tree-path for activating compensation boundary events
- Populate tree-path properties for `ACTIVATING` triggered events
- Populate tree-path properties for `ACTIVATING` ancestral subprocesses for elements triggered by events
- Added a test cases to verify:
   - re-activating element by modification recalculates the tree-path
   - tree-path is populated for sub-process body element instance on activation
   - tree-path is populated for compensation event elements
   - tree-path is populated for all activating elements in RandomizedPropertyTest
## Related issues

closes #26048

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 1]
```diff
@@ -1553,4 +1584,29 @@ private void assertThatJobIsCancelled(final long processInstanceKey, final Strin
...
+      final Record<ProcessInstanceRecordValue> elementBeforeModification) {
+    final var elementInstance = elementBeforeModification.getValue();
+
+    final Record<ProcessInstanceRecordValue> modifiedRecord =
+        RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATING)
+            .withProcessInstanceKey(elementInstance.getProcessInstanceKey())
+            .withElementId(elementInstance.getElementId())
+            .withElementType(elementInstance.getBpmnElementType())
+            .withFlowScopeKey(elementInstance.getFlowScopeKey())
+            .getLast();
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:1598]: 🔧 You'd need to limit this, otherwise it will run for 5 seconds.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 2]
```diff
@@ -1487,8 +1424,102 @@ public void shouldUseAncestorSelectionInsideMultiInstances() throws InterruptedE
...
+            .withProcessInstanceKey(processInstanceKey)
+            .withElementId("A")
+            .getFirst();
+    // when
+    ENGINE
+        .processInstance()
+        .withInstanceKey(processInstanceKey)
+        .modification()
+        .activateElement("A")
+        .modify();
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:1453]: 💭 The modification looks fine. Thought I don't think it is the scenario you want to test. Currently your process is:

start event > service task A > service task B > end event

You start the process so you'll be at service task A, there's 1 active element instsance of A. Next you modify the process instance and activate element A again. As a result you'll end up in a process with 2 active element instances of A.

❓ Do you actually want the process to be at service task A, or do you want it to be past service task A, and at service task B?

Now since I assume you don't want to have 2 active element instances you'll have to add a termination to your modify command. You choose which element to terminate using the element instance key:

`.terminateElement(elementBeforeModification.getKey())`

Comment (mustafadagher) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:1453]: No, you guessed right! I didn't mean to have two active element instances. Thanks a lot for the hint! I will update the test case to terminate it then reactivate it.

And yes, I wanted to be past service task A to verify it updated the treepath after reactivation with the new element instance key.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ProcessExecutionRandomizedPropertyTest.java [hunk 3]
```diff
@@ -88,4 +92,35 @@ public static Collection<TestDataGenerator.TestDataRecord> getTestRecords() {
     //    return List.of(
     //        TestDataGenerator.regenerateTestRecord(-8532388551768899121L, -6565756334590616537L));
   }
+
+  private static void assertAllActivatingElementsHaveTreePathPopulated(final String processId) {
```
Comment (ChrisKujawa) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ProcessExecutionRandomizedPropertyTest.java:96]: 👍🏼 I really like that we have this now as part of the randomized tests

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/EventTriggerBehavior.java [hunk 4]
```diff
@@ -234,6 +238,14 @@ public void activateTriggeredEvent(
         .setBpmnEventType(triggeredEvent.getEventType());
 
     final var eventInstanceKey = keyGenerator.nextKey();
+
+    final var elementTreePath =
+        stateBehavior.getElementTreePath(eventInstanceKey, flowScopeKey, elementRecord);
+    eventRecord
+        .setElementInstancePath(elementTreePath.elementInstancePath())
+        .setProcessDefinitionPath(elementTreePath.processDefinitionPath())
+        .setCallingElementPath(elementTreePath.callingElementPath());
```
Comment (ChrisKujawa) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/EventTriggerBehavior.java:247]: 💭 I was often thinking now, whether the ProcessInstanceRecord could maybe have a method `setTreePath(TreePath)` where we have this logic inside:

Pseudo code:
```
public void setTreePath(TreePath elementTreePath) {
    this.setElementInstancePath(elementTreePath.elementInstancePath())
        .setProcessDefinitionPath(elementTreePath.processDefinitionPath())
        .setCallingElementPath(elementTreePath.callingElementPath());
}
```

**Review by ChrisKujawa — APPROVED** [review]
Thanks @mustafadagher great catches 🚀

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnCompensationSubscriptionBehaviour.java [hunk 5]
```diff
@@ -291,6 +291,14 @@ private void activateAndCompleteCompensationBoundaryEvent(
...
+    final var elementTreePath =
+        stateBehavior.getElementTreePath(
+            boundaryEventKey, context.getFlowScopeKey(), boundaryEventRecord);
+    boundaryEventRecord
+        .setElementInstancePath(elementTreePath.elementInstancePath())
+        .setProcessDefinitionPath(elementTreePath.processDefinitionPath())
+        .setCallingElementPath(elementTreePath.callingElementPath());
+
     stateWriter.appendFollowUpEvent(
         boundaryEventKey, ProcessInstanceIntent.ELEMENT_ACTIVATING, boundaryEventRecord);
```
Comment (ChrisKujawa) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnCompensationSubscriptionBehaviour.java:303]: ❓ Should we maybe check all usages of `ELEMENT_ACTIVATING` manually, whether treePath is set in the cases?

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnCompensationSubscriptionBehaviour.java:303]: I did already search the whole code base, and that's the end of it so far. Every usage of it by now is covered

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/EventTriggerBehavior.java (hunk 4 above)
Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/EventTriggerBehavior.java:247]: I actually had the same idea earlier, will try to see if it can work

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/EventTriggerBehavior.java:247]: this will need the `protocol` to depend on `work-flow-engine` to have access to `ElementTreePathProperties`
or the ElemenTreePathBuilder has to be moved somehow to the `protocol`

Comment (ChrisKujawa) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/EventTriggerBehavior.java:247]: Might make sense to have it in the protocol 🤔
