### PR TITLE
Unflake timer start event test

### LINKED ISSUE #10272: Flaky TimerStartEventTest (multiple cases)
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Multiple times a week
- Does it block your work? yes, CI is failing
- Do we suspect that it is a real failure? No

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.camunda.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:77)
	at io.camunda.zeebe.engine.processing.timer.TimerStartEventTest.shouldTriggerAtSpecifiedTimeDate(TimerStartEventTest.java:806)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:234)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:228)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:131)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be omitted

- I suspect it's related to the recent task scheduling changes, just like 
  - #10214 

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
[2022-09-05T12:36:18.344Z] [INFO] Running io.camunda.zeebe.engine.processing.timer.TimerStartEventTest
[2022-09-05T12:36:19.723Z] [INFO] Tests run: 44, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.525 s - in io.camunda.zeebe.engine.processing.message.MessageCatchElementTest
[2022-09-05T12:36:19.723Z] [INFO] Running io.camunda.zeebe.engine.processing.timer.ConcurrentTimerEventTest
[2022-09-05T12:36:20.292Z] [INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.69 s - in io.camunda.zeebe.engine.processing.message.MessageStartEventSubscriptionTest
[2022-09-05T12:36:20.292Z] [INFO] Running io.camunda.zeebe.engine.processing.timer.TimerCatchEventTest
[2022-09-05T12:36:20.860Z] [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.098 s - in io.camunda.zeebe.engine.processing.timer.ConcurrentTimerEventTest
[2022-09-05T12:36:20.860Z] [INFO] Running io.camunda.zeebe.engine.processing.timer.DueDateTimerCheckerTest
[2022-09-05T12:36:20.860Z] [INFO] Running io.camunda.zeebe.engine.processing.timer.DueDateTimerCheckerTest$YieldingDecoratorTest
[2022-09-05T12:36:21.121Z] [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.287 s - in io.camunda.zeebe.engine.processing.timer.DueDateTimerCheckerTest$YieldingDecoratorTest
[2022-09-05T12:36:21.121Z] [INFO] Running io.camunda.zeebe.engine.processing.timer.DueDateTimerCheckerTest$TriggerTimersSideEffectTest
[2022-09-05T12:36:21.692Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.34 s - in io.camunda.zeebe.engine.processing.timer.DueDateTimerCheckerTest$TriggerTimersSideEffectTest
[2022-09-05T12:36:21.692Z] [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.63 s - in io.camunda.zeebe.engine.processing.timer.DueDateTimerCheckerTest
[2022-09-05T12:36:21.692Z] [INFO] Running io.camunda.zeebe.engine.processing.timer.CronTimerTest
[2022-09-05T12:36:21.692Z] [INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.247 s - in io.camunda.zeebe.engine.processing.timer.CronTimerTest
[2022-09-05T12:36:21.692Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceTest
[2022-09-05T12:36:21.952Z] [INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.201 s - in io.camunda.zeebe.engine.processing.message.MessageCorrelationTest
[2022-09-05T12:36:21.952Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceTerminationTest
[2022-09-05T12:36:21.952Z] [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.15 s - in io.camunda.zeebe.engine.processing.bpmn.gateway.InclusiveGatewayTest
[2022-09-05T12:36:21.952Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceCommandRejectionTest
[2022-09-05T12:36:22.225Z] [INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.838 s - in io.camunda.zeebe.engine.processing.timer.TimerCatchEventTest
[2022-09-05T12:36:22.225Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceWithResultTest
[2022-09-05T12:36:22.795Z] [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.6 s - in io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceWithResultTest
[2022-09-05T12:36:22.795Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceAnywhereTest
[2022-09-05T12:36:22.795Z] [INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.919 s - in io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceTest
[2022-09-05T12:36:22.795Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceRejectionTest
[2022-09-05T12:36:23.055Z] [INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.147 s - in io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceTerminationTest
[2022-09-05T12:36:23.055Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceTest
[2022-09-05T12:36:23.623Z] [INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.458 s - in io.camunda.zeebe.engine.processing.message.MessageStartEventTest
[2022-09-05T12:36:23.623Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest
[2022-09-05T12:36:23.623Z] [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.428 s - in io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceTest
[2022-09-05T12:36:23.623Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceRejectionTest
[2022-09-05T12:36:23.623Z] [INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.894 s - in io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceAnywhereTest
[2022-09-05T12:36:23.623Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceUnsupportedElementsTest
[2022-09-05T12:36:23.883Z] [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.092 s - in io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceRejectionTest
[2022-09-05T12:36:23.883Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceUnsupportedElementTypeTest
[2022-09-05T12:36:24.143Z] [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.534 s - in io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceRejectionTest
[2022-09-05T12:36:24.143Z] [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.413 s - in io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceUnsupportedElementsTest
[2022-09-05T12:36:24.143Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceTokenTest
[2022-09-05T12:36:24.143Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceVariablesTest
[2022-09-05T12:36:24.713Z] [INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.613 s - in io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceVariablesTest
[2022-09-05T12:36:24.713Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceTest
[2022-09-05T12:36:24.972Z] [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.137 s - in io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceUnsupportedElementTypeTest
[2022-09-05T12:36:24.972Z] [INFO] Running io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceSupportedElementTest
[2022-09-05T12:36:25.232Z] [INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.152 s - in io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceTokenTest
[2022-09-05T12:36:25.232Z] [INFO] Running io.camunda.zeebe.engine.state.variable.VariableStateTest
[2022-09-05T12:36:25.491Z] [INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.859 s - in io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceTest
[2022-09-05T12:36:25.491Z] [INFO] Running io.camunda.zeebe.engine.state.variable.IndexedDocumentTest
[2022-09-05T12:36:25.750Z] [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in io.camunda.zeebe.engine.state.variable.IndexedDocumentTest
[2022-09-05T12:36:25.750Z] [INFO] Running io.camunda.zeebe.engine.state.deployment.DeploymentStateTest
[2022-09-05T12:36:25.750Z] [INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.413 s - in io.camunda.zeebe.engine.state.variable.VariableStateTest
[2022-09-05T12:36:25.750Z] [INFO] Running io.camunda.zeebe.engine.state.deployment.ProcessStateTest
[2022-09-05T12:36:25.750Z] [INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.714 s - in io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceSupportedElementTest
[2022-09-05T12:36:25.750Z] [INFO] Running io.camunda.zeebe.engine.state.deployment.DecisionStateTest
[2022-09-05T12:36:26.318Z] [INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.288 s - in io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceCommandRejectionTest
[2022-09-05T12:36:26.318Z] [INFO] Running io.camunda.zeebe.engine.state.query.StateQueryServiceTest
[2022-09-05T12:36:26.885Z] [INFO] Running io.camunda.zeebe.engine.state.query.StateQueryServiceTest$GetBpmnProcessIdForJob
[2022-09-05T12:36:26.885Z] [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.232 s - in io.camunda.zeebe.engine.state.query.StateQueryServiceTest$GetBpmnProcessIdForJob
[2022-09-05T12:36:26.885Z] [INFO] Running io.camunda.zeebe.engine.state.query.StateQueryServiceTest$GetBpmnProcessIdForProcessInstance
[2022-09-05T12:36:27.145Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.237 s - in io.camunda.zeebe.engine.state.query.StateQueryServiceTest$GetBpmnProcessIdForProcessInstance
[2022-09-05T12:36:27.145Z] [INFO] Running io.camunda.zeebe.engine.state.query.StateQueryServiceTest$GetBpmnProcessIdForProcess
[2022-09-05T12:36:27.145Z] [INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.47 s - in io.camunda.zeebe.engine.state.deployment.DecisionStateTest
[2022-09-05T12:36:27.404Z] [INFO] Running io.camunda.zeebe.engine.state.ProcessExecutionCleanStateTest
[2022-09-05T12:36:27.404Z] [INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.721 s - in io.camunda.zeebe.engine.state.deployment.DeploymentStateTest
[2022-09-05T12:36:27.404Z] [INFO] Running io.camunda.zeebe.engine.state.migration.DbMigratorImplTest
[2022-09-05T12:36:27.404Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.256 s - in io.camunda.zeebe.engine.state.query.StateQueryServiceTest$GetBpmnProcessIdForProcess
[2022-09-05T12:36:27.404Z] [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.113 s - in io.camunda.zeebe.engine.state.query.StateQueryServiceTest
[2022-09-05T12:36:27.404Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_3.TemporaryVariableMigrationTest
[2022-09-05T12:36:27.404Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_3.TemporaryVariableMigrationTest$BlackboxTest
[2022-09-05T12:36:27.663Z] [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.248 s - in io.camunda.zeebe.engine.state.migration.DbMigratorImplTest
[2022-09-05T12:36:27.663Z] [INFO] Running io.camunda.zeebe.engine.state.migration.DbMigrationControllerTest
[2022-09-05T12:36:27.663Z] [WARNING] Tests run: 12, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 85.098 s - in io.atomix.raft.zeebe.ZeebeTest
[2022-09-05T12:36:27.923Z] [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.225 s - in io.camunda.zeebe.engine.state.migration.DbMigrationControllerTest
[2022-09-05T12:36:27.923Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.MessageSubscriptionSentTimeMigrationTest
[2022-09-05T12:36:27.923Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.MessageSubscriptionSentTimeMigrationTest$BlackboxTest
[2022-09-05T12:36:27.923Z] [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.369 s - in io.camunda.zeebe.engine.state.migration.to_1_3.TemporaryVariableMigrationTest$BlackboxTest
[2022-09-05T12:36:27.923Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_3.TemporaryVariableMigrationTest$MockBasedTests
[2022-09-05T12:36:28.183Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.307 s - in io.camunda.zeebe.engine.state.migration.to_1_1.MessageSubscriptionSentTimeMigrationTest$BlackboxTest
[2022-09-05T12:36:28.183Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.MessageSubscriptionSentTimeMigrationTest$MockBasedTests
[2022-09-05T12:36:28.183Z] [INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.74 s - in io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest
[2022-09-05T12:36:28.183Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.ProcessMessageSubscriptionSentTimeMigrationTest
[2022-09-05T12:36:28.183Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.ProcessMessageSubscriptionSentTimeMigrationTest$BlackboxTest
[2022-09-05T12:36:28.442Z] [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.479 s - in io.camunda.zeebe.engine.state.migration.to_1_3.TemporaryVariableMigrationTest$MockBasedTests
[2022-09-05T12:36:28.442Z] [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.852 s - in io.camunda.zeebe.engine.state.migration.to_1_3.TemporaryVariableMigrationTest
[2022-09-05T12:36:28.442Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.DbMigrationStateTest
[2022-09-05T12:36:28.442Z] [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.277 s - in io.camunda.zeebe.engine.state.migration.to_1_1.MessageSubscriptionSentTimeMigrationTest$MockBasedTests
[2022-09-05T12:36:28.442Z] [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.589 s - in io.camunda.zeebe.engine.state.migration.to_1_1.MessageSubscriptionSentTimeMigrationTest
[2022-09-05T12:36:28.442Z] [INFO] Running io.camunda.zeebe.engine.state.message.PendingMessageSubscriptionStateTest
[2022-09-05T12:36:28.701Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.31 s - in io.camunda.zeebe.engine.state.migration.to_1_1.ProcessMessageSubscriptionSentTimeMigrationTest$BlackboxTest
[2022-09-05T12:36:28.701Z] [INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.ProcessMessageSubscriptionSentTimeMigrationTest$MockBasedTests
[2022-09-05T12:36:28.701Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.247 s - in io.camunda.zeebe.engine.state.migration.to_1_1.DbMigrationStateTest
[2022-09-05T12:36:28.701Z] [INFO] Running io.camunda.zeebe.engine.state.message.MessageStateTest
[2022-09-05T12:36:28.960Z] [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.459 s - in io.camunda.zeebe.engine.state.migration.to_1_1.ProcessMessageSubscriptionSentTimeMigrationTest$MockBasedTests
[2022-09-05T12:36:28.960Z] [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.772 s - in io.camunda.zeebe.engine.state.migration.to_1_1.ProcessMessageSubscriptionSentTimeMigrationTest
[2022-09-05T12:36:28.960Z] [INFO] Running io.camunda.zeebe.engine.state.message.PendingProcessMessageSubscriptionStateTest
[2022-09-05T12:36:28.960Z] [INFO] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.375 s - in io.camunda.zeebe.engine.state.deployment.ProcessStateTest
[2022-09-05T12:36:28.960Z] [INFO] Running io.camunda.zeebe.engine.state.message.TransientSubscriptionCommandStateTest
[2022-09-05T12:36:29.219Z] [INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in io.camunda.zeebe.engine.state.message.TransientSubscriptionCommandStateTest
[2022-09-05T12:36:29.219Z] [INFO] Running io.camunda.zeebe.engine.state.message.MessageSubscriptionStateTest
[2022-09-05T12:36:29.477Z] [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.852 s - in io.camunda.zeebe.engine.state.message.PendingMessageSubscriptionStateTest
[2022-09-05T12:36:29.477Z] [INFO] Running io.camunda.zeebe.engine.state.message.ProcessMessageSubscriptionStateTest
[2022-09-05T12:36:29.735Z] [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.782 s - in io.camunda.zeebe.engine.state.message.PendingProcessMessageSubscriptionStateTest
[2022-09-05T12:36:29.735Z] [INFO] Running io.camunda.zeebe.engine.state.message.MessageStartEventSubscriptionStateTest
[2022-09-05T12:36:29.994Z] [INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.962 s - in io.camunda.zeebe.engine.state.message.MessageSubscriptionStateTest
[2022-09-05T12:36:29.994Z] [INFO] Running io.camunda.zeebe.engine.state.KeyGeneratorTest
[2022-09-05T12:36:30.253Z] [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.818 s - in io.camunda.zeebe.engine.state.message.ProcessMessageSubscriptionStateTest
[2022-09-05T12:36:30.253Z] [INFO] Running io.camunda.zeebe.engine.state.instance.JobStateTest
[2022-09-05T12:36:30.513Z] [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.477 s - in io.camunda.zeebe.engine.state.KeyGeneratorTest
[2022-09-05T12:36:30.513Z] [INFO] Running io.camunda.zeebe.engine.state.instance.ElementInstanceStateTest
[2022-09-05T12:36:30.772Z] [INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.929 s - in io.camunda.zeebe.engine.state.message.MessageStartEventSubscriptionStateTest
[2022-09-05T12:36:30.772Z] [INFO] Running io.camunda.zeebe.engine.state.instance.IncidentStateTest
[2022-09-05T12:36:31.030Z] [ERROR] Tests run: 22, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.826 s <<< FAILURE! - in io.camunda.zeebe.engine.processing.timer.TimerStartEventTest
[2022-09-05T12:36:31.030Z] [ERROR] io.camunda.zeebe.engine.processing.timer.TimerStartEventTest.shouldTriggerAtSpecifiedTimeDate  Time elapsed: 5.255 s  <<< ERROR!
[2022-09-05T12:36:31.031Z] io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
[2022-09-05T12:36:31.031Z] 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[2022-09-05T12:36:31.031Z] 	at io.camunda.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:77)
[2022-09-05T12:36:31.031Z] 	at io.camunda.zeebe.engine.processing.timer.TimerStartEventTest.shouldTriggerAtSpecifiedTimeDate(TimerStartEventTest.java:806)
[2022-09-05T12:36:31.031Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-09-05T12:36:31.031Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-09-05T12:36:31.031Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-09-05T12:36:31.031Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[2022-09-05T12:36:31.031Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[2022-09-05T12:36:31.031Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2022-09-05T12:36:31.031Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[2022-09-05T12:36:31.031Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
[2022-09-05T12:36:31.031Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2022-09-05T12:36:31.031Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2022-09-05T12:36:31.031Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2022-09-05T12:36:31.031Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2022-09-05T12:36:31.031Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2022-09-05T12:36:31.031Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2022-09-05T12:36:31.031Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2022-09-05T12:36:31.031Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[2022-09-05T12:36:31.031Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2022-09-05T12:36:31.031Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2022-09-05T12:36:31.031Z] 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
[2022-09-05T12:36:31.031Z] 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
[2022-09-05T12:36:31.031Z] 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
[2022-09-05T12:36:31.031Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
[2022-09-05T12:36:31.031Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
[2022-09-05T12:36:31.031Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
[2022-09-05T12:36:31.031Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
[2022-09-05T12:36:31.031Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
[2022-09-05T12:36:31.031Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
[2022-09-05T12:36:31.031Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
[2022-09-05T12:36:31.031Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
[2022-09-05T12:36:31.031Z] 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
[2022-09-05T12:36:31.031Z] 	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
[2022-09-05T12:36:31.031Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:234)
[2022-09-05T12:36:31.031Z] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[2022-09-05T12:36:31.031Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:228)
[2022-09-05T12:36:31.032Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
[2022-09-05T12:36:31.032Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:131)
[2022-09-05T12:36:31.032Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
[2022-09-05T12:36:31.032Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
[2022-09-05T12:36:31.032Z] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
[2022-09-05T12:36:31.032Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
[2022-09-05T12:36:31.032Z] 
[2022-09-05T12:36:31.290Z] [INFO] Running io.camunda.zeebe.engine.state.instance.TimerInstanceStateTest
[2022-09-05T12:36:31.290Z] [INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.57 s - in io.camunda.zeebe.engine.state.message.MessageStateTest
[2022-09-05T12:36:31.290Z] [INFO] Running io.camunda.zeebe.engine.state.instance.EventScopeInstanceStateTest
[2022-09-05T12:36:31.857Z] [INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.17 s - in io.camunda.zeebe.engine.state.instance.IncidentStateTest
[2022-09-05T12:36:31.857Z] [INFO] Running io.camunda.zeebe.engine.state.instance.NumberOfTakenSequenceFlowsStateTest
[2022-09-05T12:36:32.115Z] [INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.514 s - in io.camunda.zeebe.engine.state.instance.ElementInstanceStateTest
[2022-09-05T12:36:32.115Z] [INFO] Running io.camunda.zeebe.engine.state.instance.BlackListStateTest
[2022-09-05T12:36:32.115Z] [INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.068 s - in io.camunda.zeebe.engine.state.instance.TimerInstanceStateTest
[2022-09-05T12:36:32.373Z] [INFO] Running io.camunda.zeebe.engine.util.EngineRuleTest
[2022-09-05T12:36:32.632Z] [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.291 s - in io.camunda.zeebe.engine.util.EngineRuleTest
[2022-09-05T12:36:32.632Z] [INFO] Running io.camunda.zeebe.engine.util.LogStreamPrinterTest
[2022-09-05T12:36:32.632Z] [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.074 s - in io.camunda.zeebe.engine.util.LogStreamPrinterTest
[2022-09-05T12:36:32.632Z] [INFO] Running io.camunda.zeebe.engine.processing.timer.TimerStartEventTest
[2022-09-05T12:36:32.890Z] [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.802 s - in io.camunda.zeebe.engine.state.instance.NumberOfTakenSequenceFlowsStateTest
[2022-09-05T12:36:32.890Z] [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.22 s - in io.camunda.zeebe.engine.processing.timer.TimerStartEventTest
[2022-09-05T12:36:32.890Z] [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.835 s - in io.camunda.zeebe.engine.state.instance.BlackListStateTest
[2022-09-05T12:36:33.825Z] [INFO] Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.694 s - in io.camunda.zeebe.engine.state.instance.JobStateTest
[2022-09-05T12:36:34.392Z] [INFO] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.97 s - in io.camunda.zeebe.engine.state.instance.EventScopeInstanceStateTest
[2022-09-05T12:36:36.926Z] [INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.212 s - in io.camunda.zeebe.engine.state.ProcessExecutionCleanStateTest
[2022-09-05T12:36:36.926Z] [INFO] 
[2022-09-05T12:36:36.926Z] [INFO] Results:
[2022-09-05T12:36:36.926Z] [INFO] 
[2022-09-05T12:36:36.926Z] [WARNING] Flakes: 
[2022-09-05T12:36:36.926Z] [WARNING] io.camunda.zeebe.engine.processing.timer.TimerStartEventTest.shouldTriggerAtSpecifiedTimeDate
[2022-09-05T12:36:36.926Z] [ERROR]   Run 1: TimerStartEventTest.shouldTriggerAtSpecifiedTimeDate:806 » StreamWrapper No event found matching the criteria
[2022-09-05T12:36:36.926Z] [INFO]   Run 2: PASS
[2022-09-05T12:36:36.926Z] [INFO] 
[2022-09-05T12:36:36.926Z] [INFO] 
[2022-09-05T12:36:36.926Z] [WARNING] Tests run: 1732, Failures: 0, Errors: 0, Skipped: 2, Flakes: 1
</pre>
</details>

### PR DESCRIPTION
**Pull request by korthout**
## Description

Most cases in the timer start event test were suffering from flakiness. This stabilizes these tests again.

The cause of the flakiness was a race condition between time traveling and scheduling an upcoming timer:
 - the time would be increased after the deployment is completed
 - that includes writing all the deployment events (up to and including fully_distributed)
 - it does not await post-commit task execution
 - upcoming timers are scheduled in a post-commit task
 - this post-commit task could be executed after the time traveling
 - in that case the timer does not trigger after the time travel, as it is scheduled in the future

This changes the time travel to guarantee that the post-commit tasks have been executed. It does that by awaiting that the engine reaches the end of the log.

## Related issues

closes #10272 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
@korthout :+1:

**Review by remcowesterhoud — APPROVED** [review]
LGTM!

bors merge

**Comment by korthout** [comment]
There was another timer related test that flaked. We should investigate it before merging this, to avoid this creating a bigger problem than it tries to resolve.

**Comment by remcowesterhoud** [comment]
I had a peek at the test. It is flaky because the test case was flawed to begin with. It relied upon the engine increasing it's time before the timer was scheduled.
I have pushed a new commit to fix it. @korthout I can't assign you as reviewer as you created the PR, but please have a look 👀

File: engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerCatchEventTest.java [hunk 1]
```diff
@@ -204,8 +204,6 @@ public void shouldTriggerTimer() {
             .withProcessInstanceKey(processInstanceKey)
             .getFirst();
 
-    ENGINE.increaseTime(Duration.ofSeconds(1));
-
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerCatchEventTest.java:208]: @remcowesterhoud Are you sure we should also delete the time increase? The time increase made the issue clear, but it still seems reasonable. I'd suggest increasing the time by 0.1s though.

Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerCatchEventTest.java:208]: I think the problem with that is that it will remain flaky that way. Sometimes the engine time is still increased before the timer is scheduled. I'm not entirely sure why but if I increase the engine time by 100ms I can't get it to succeed.

Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerCatchEventTest.java:208]: Hmm what I said doesn't make sense. But the assertion will fail because the timer is now triggered after 200ms instead 100ms. I will take a luncbreak, maybe my subconscious will explain it to me 😄

Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerCatchEventTest.java:208]: @korthout I reckon it has to do with the `TIMER_RESOLUTION` of 100ms. This would cause the test to fail if we increase the time since we check that the timer gets triggered within 100ms ± 50ms.

We don't really need to increase the time here though. The timer gets triggered within 100ms. This won't slow down the tests enough to be significant. I would propose to leave it out.
I will change the assertion to check that it has been triggered within 100-150ms. The current assertion would also pass if it gets triggered at 50ms, which is not intended.

Comment (korthout) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/timer/TimerCatchEventTest.java:208]: Thanks for looking into it and clarifying @remcowesterhoud 

Let's keep it without the time traveling 👍

**Comment by remcowesterhoud** [comment]
bors merge
