### PR TITLE
fix: avoid actor call to unregister handlers when it is closing

### LINKED ISSUE #25897: UnsupportedOperationException: Incorrect usage of actor.call(...) cannot be called from current actor.
**Describe the bug**

Reported on SaaS Int Chaos [here](https://console.cloud.google.com/errors/detail/COKDyumjivrUSQ;service=zeebe;time=P7D;locations=global?project=camunda-saas-int-chaos): `Actor failed in phase 'CLOSING'. Discard all jobs and stop immediately`.

**To Reproduce**

Happened during transition from `FOLLOWER` to `INACTIVE`.

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.UnsupportedOperationException: Incorrect usage of actor.call(...) cannot be called from current actor.
	at io.camunda.zeebe.scheduler.ActorControl.call(ActorControl.java:211) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorControl.call(ActorControl.java:79) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiServiceImpl.unregisterHandlers(CommandApiServiceImpl.java:114) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiServiceImpl.onActorClosing(CommandApiServiceImpl.java:57) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:83) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT] 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.7.0-SNAPSHOT
- Logs ([link](https://cloudlogging.app.goo.gl/bfvLJkvaau34oJer7), [Drive](https://drive.google.com/file/d/1Ex9rQMrTzlgZo_mcG0m0XuRLMiU5vyAx/view?usp=drive_link))

### PR DESCRIPTION
**Pull request by filipecampos**
## Description
Decouples the actual unregistering of handlers while `actor` is closing from using `actor.call`.
Added unit tests to validate fix both on direct role transition from Follower to Inactive as well as closing the CommandApiService actor.

## Related issues

closes #25897

### CODE REVIEW

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImplTest.java [hunk 1]
```diff
@@ -98,4 +110,63 @@ public void subscribesWhenBecomingLeader(final Role nonLeaderRole) {
...
+
+    // then - subscriptions are cleaned up
+    verify(serverTransport, times(1)).unsubscribe(eq(1), eq(RequestType.QUERY));
+    verify(serverTransport, times(1)).unsubscribe(eq(1), eq(RequestType.COMMAND));
+
+    clearInvocations(serverTransport);
+    final var unregisterFuture =
+        transitionStep.prepareTransition(transitionContext, 2, Role.INACTIVE);
+    scheduler.workUntilDone();
+    unregisterFuture.join();
```
Comment (entangled90) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImplTest.java:138]: :wrench: Adding a timeout here will avoid blocking for an indefinite amount of time. I suggest checking out the `@Timeout` annotation.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImplTest.java [hunk 2]
```diff
@@ -98,4 +110,63 @@ public void subscribesWhenBecomingLeader(final Role nonLeaderRole) {
...
+    commandApiService.registerHandlers(1, logStream, transitionContext.getQueryService());
+    scheduler.workUntilDone();
+
+    verify(serverTransport, times(1)).subscribe(eq(1), eq(RequestType.QUERY), any());
+    verify(serverTransport, times(1)).subscribe(eq(1), eq(RequestType.COMMAND), any());
+
+    // when - closing the actor
+    final ActorFuture<Void> closeFuture = commandApiService.closeAsync();
+    scheduler.workUntilDone();
+    closeFuture.join(10, TimeUnit.SECONDS);
```
Comment (entangled90) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImplTest.java:166]: :wrench: If you setup a common `@Timeout` this can be removed

**Review by entangled90 — APPROVED** [review]
Pre-approving as they are small suggestions :smile:

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImplTest.java (hunk 1 above)
Comment (filipecampos) [reply zeebe/broker/src/test/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImplTest.java:139]: Done.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImplTest.java (hunk 2 above)
Comment (filipecampos) [reply zeebe/broker/src/test/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImplTest.java]: Done.

**Comment by npepinpe** [comment]
Do we not need to backport to older versions as well, e.g. 8.4 and 8.3? Or will you backport the 8.5 PR to those?

**Comment by filipecampos** [comment]
Added 8.4 and 8.3 backports to this PR as I somehow missed them.
