### PR TITLE
separate checkpoint schedule timers

### LINKED ISSUE #46232: Backup frequency matches checkpoint frequency
### 

### 

### 

### 

### Description

When a partition is lagging behind and experiences delays in taking a backup, it's checkpoint state is considered an outlier as it can be minutes behind. When this happens, if a checkpoint interval is set at a high frequency, it will cause taking backups instead since we check the state to determine the type of checkpoint to take when the scheduler ticks.

### Steps to reproduce

1. Enable backups with a lower checkpoint interval relative to backup interval
2. Have one partition lagging behind
3. Multiple backups are issued based on the checkpoint interval

### Current behavior

Backup interval is being replaced by the checkpoint interval causing more than the expected backups to be created. Eventually the scheduler will return back to it's expected types based on the intervals when backups are completed within the expected time frame. 

### Expected behavior

This behavior needs to be throttled since it can cause the lagging partition to lag even further due to backup processing resource requirements.

### Workaround

Reducing checkpoint intervals will make the cluster to recover possibly faster but requires a rollout.

### Environment

SM

### Version

- Component Version: 8.9-rc5

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

Separate the checkpoint `MARKER` and `SCHEDULED_BACKUP` scheduler in two different timers.

Include the laggard partition check only for backups while allowing markers to be uninterrupted, since processing time is rarely the case while backup confirmation has the bigger impact.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #46232

### CODE REVIEW

File: zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java [hunk 1]
```diff
@@ -140,25 +144,60 @@ private ActorFuture<CheckpointState> acquireEarliestState() {
...
+        Duration.between(now, schedule.nextExecution(now).orElse(Instant.MAX)).toMillis();
+
+    if (spreadMs > intervalMs * LAGGING_PARTITION_FACTOR) {
+      LOG.warn(
+          "Detected lagging partition in states: spread {} ms exceeds interval {} ms. Delaying next execution.",
+          spreadMs,
+          intervalMs);
+      throw new PartitionLaggingException(spreadMs, intervalMs);
+    }
+  }
```
[the remark this answers is not in the document]
Comment (panagiotisgts) [reply zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java]: Done in https://github.com/camunda/camunda/pull/47749/commits/2189bd3ed2a08ff1a506675f183734d2d23d1af5

File: zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java [hunk 2]
```diff
@@ -140,25 +145,65 @@ private ActorFuture<CheckpointState> acquireEarliestState() {
...
+    if (nextExecution.isEmpty()) {
+      return;
+    }
+    final Instant followingExecution =
+        schedule.nextExecution(nextExecution.get()).orElse(Instant.MAX);
+    final long intervalMs = Duration.between(nextExecution.get(), followingExecution).toMillis();
+
+    if (spreadMs > intervalMs * LAGGING_PARTITION_FACTOR) {
+      LOG.warn(
+          "Detected lagging partition in states: spread {} ms exceeds interval {} ms. Delaying next execution.",
```
Comment (lenaschoenburg) [inline zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java]: 🔧 Convert to duration and log that. Much nicer to read, especially with large intervals.

File: zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java [hunk 3]
```diff
@@ -50,14 +50,22 @@ public CheckpointScheduler(
...
   protected void onActorStarted() {
     LOG.debug("Checkpoint scheduler started");
     metrics.register();
-    actor.run(this::reschedulingTask);
+    if (checkpointSchedule != null) {
+      actor.run(this::markerSchedulingTask);
+    }
+    if (backupSchedule != null) {
+      actor.run(this::backupSchedulingTask);
+    }
```
[the remark this answers is not in the document]
Comment (panagiotisgts) [reply zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java:66]: I'd leave this as is for now. If anywhere, we'll figure this out during the benchmarking where we'd have proof. It's still a valid but probably not rare scenario. And it will trigger the backoff mechanism if we do get an ID collision.

File: zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java [hunk 4]
```diff
@@ -228,29 +255,28 @@ private Instant previousExecution(final Schedule schedule, final Instant from) {
...
-      this(0L, type, checkpointTime, currentCheckpointState, false);
-    }
-
-    ScheduleInstruction taken(final long checkpointId, final Instant checkpointTime) {
-      return new ScheduleInstruction(checkpointId, type, checkpointTime, state, true);
+  static class PartitionLaggingException extends RuntimeException {
+    public PartitionLaggingException(final long spreadMs, final long intervalMs) {
+      super(
+          "Partition lagging in states: spread %d ms exceeds interval %d ms"
+              .formatted(spreadMs, intervalMs));
```
Comment (lenaschoenburg) [inline zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java]: 🔧 Log these as `Duration`, that makes it nicer to read, especially for larger intervals

File: zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java [hunk 5]
```diff
@@ -66,154 +74,151 @@ protected void onActorClosed() {
...
+    final var now = ActorClock.currentInstant();
+    final CompletableActorFuture<ExecutionResult> future = new CompletableActorFuture<>();
+    if (nextExecution.isBefore(now) || nextExecution.equals(now)) {
+      backupRequestHandler
+          .checkpoint(type)
+          .toCompletableFuture()
+          .thenApplyAsync(
+              id -> {
+                LOG.debug("Checkpoint {} triggered with id {}", type, id);
+                return new ExecutionResult(id, type, ActorClock.currentInstant(), true);
```
Comment (lenaschoenburg) [inline zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java:162]: 🔧 

```suggestion
                return new ExecutionResult(id, type, nextExecution, true);
```

File: zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java [hunk 6]
```diff
@@ -18,29 +19,28 @@
...
 import org.slf4j.LoggerFactory;
 
 public class CheckpointScheduler extends Actor implements AutoCloseable {
 
-  // If the time difference between the next checkpoint and backup is less than this threshold, we
-  // skip the checkpoint and instruct only a backup on the backup's defined interval. Since backups
-  // also create a checkpoint, this avoids  redundant checkpoints and the possibility for
-  // checkpointId collisions.
-  static final long SKIP_CHECKPOINT_THRESHOLD = Duration.ofSeconds(2).toMillis();
+  private static final double LAGGING_PARTITION_FACTOR = 1.5;
```
Comment (lenaschoenburg) [inline zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java]: 🔧 unused and can be removed

**Review by lenaschoenburg — APPROVED** [review]
Thanks, resolves the bug _and_ is easier to understand now 🚀

File: zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java (hunk 5 above)
Comment (panagiotisgts) [reply zeebe/backup/src/main/java/io/camunda/zeebe/backup/schedule/CheckpointScheduler.java:162]: This is actually on purpose to accommodate for broker fanout possible lag in order to calculate the delay for the next execution, as this will essentially be the last response's time. In theory they should be pretty close tho
