### PR TITLE
fix: create new readers and writer for every async request

### LINKED ISSUE #10014: NullPointerException upon writing error response
**Describe the bug**

The `ErrorResponseWriter` tried to write an error response, but the `errorCode` was null.

**To Reproduce**

I don't know

**Expected behavior**

No NPE is thrown.

**Log/Stacktrace**

https://console.cloud.google.com/errors/detail/CNr_jurZ9ZLCzAE;service=zeebe;time=P7D?project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: error code
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.EnsureUtil.ensureNotNull(EnsureUtil.java:20) ~[zeebe-util-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.ErrorResponseWriter.tryWriteResponse(ErrorResponseWriter.java:161) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.AsyncApiRequestHandler.lambda$handleRequest$1(AsyncApiRequestHandler.java:114) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT] 
```

</p>
</details>

**Environment:**
- Zeebe Version: latest SNAPSHOT

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

This allows async api handlers to get new instances of request readers and writers on every request, while synchronous handlers can re-use their writers and readers.

## Related issues

closes #10014 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/transport/ApiRequestHandler.java [hunk 1]
```diff
@@ -11,17 +11,33 @@
...
  */
 public abstract class ApiRequestHandler<R extends RequestReader<?>, W extends ResponseWriter>
     extends AsyncApiRequestHandler<R, W> {
 
   protected ApiRequestHandler(final R requestReader, final W responseWriter) {
-    super(requestReader, responseWriter);
+    super(
+        () -> requestReader,
+        () -> responseWriter,
+        new Supplier<>() {
```
Comment (oleschoenburg) [inline broker/src/main/java/io/camunda/zeebe/broker/transport/ApiRequestHandler.java:33]: :thought_balloon: Looks weird but I found no other way to define a supplier that always returns the same instance of `errorResponseWriter`

File: broker/src/main/java/io/camunda/zeebe/broker/transport/AsyncApiRequestHandler.java [hunk 2]
```diff
@@ -79,6 +90,10 @@ private void handleRequest(
       final DirectBuffer buffer,
       final int offset,
       final int length) {
+    final var requestReader = requestReaderSupplier.get();
+    final var responseWriter = responseWriterSupplier.get();
+    final var errorResponseWriter = errorResponseWriterSupplier.get();
```
Comment (deepthidevaki) [inline broker/src/main/java/io/camunda/zeebe/broker/transport/AsyncApiRequestHandler.java:95]: :thought_balloon: I still think you don't have to create these instances here. Instead it can be created in the implementation of `handleAsync`. But this is ok for now. We can discuss it when you refactor this class.

**Review by deepthidevaki — APPROVED** [review]
Thanks.

File: broker/src/main/java/io/camunda/zeebe/broker/transport/ApiRequestHandler.java (hunk 1 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/transport/ApiRequestHandler.java:33]: Sorry. Didn't see this comment before my review.

I think it is ok if it creates a new instance everytime.

**Comment by oleschoenburg** [comment]
I'll merge this directly once jenkins runs through.
