### PR TITLE
fix: handle `null` resourcePropertyName for backward compatibility with pre-8.9 authorizations

### LINKED ISSUE #45302: SM 8.8 → 8.9 alpha4 migration breaks login/OC access
### 

### 

### 

### 

### Description

For SM, there is an issue with the 8.9 migration flow from SM 8.8 to SM 8.9 alpha4. 
Demo user can't log in after migration and users like Bart or Lisa cannot access OC apps after migration.
[Here](https://camunda.slack.com/archives/C06BN4SRB6C/p1770643765180039?thread_ts=1770620857.196729&cid=C06BN4SRB6C) is the conversation thread.
 
[@jessesimpson36 ](https://camunda.slack.com/team/U04KEUQ1S4S) investigated the issue and found that the problem is related to a Keycloak configuration issue with the refresh token. [@Ben-Sheppard ](https://camunda.slack.com/team/U01R34DBKAP) provided further analysis and identified a potential root cause related to the resourcePropertyName field in the authorization data.

### Steps to reproduce

1. Trigger [this workflow](https://github.com/camunda/c8-cross-component-e2e-tests/actions/workflows/playwright_sm_manual_upgrade_minor_8_9.yml) with helmChartVersion as "14-rc-latest"
2. SM 8.8 will be installed, and users and some processes will be created. Wait for migration to 8.9
3. Observe that demo user can't login and lisa and bart users can't access OC apps (OC IDentity, Tasklist, Operate) after migration.

### Current behavior

Demo user can't login and lisa and bart users can't access OC apps after migration.

### Expected behavior

Demo user should be able to log in after migration and demo and lisa users should be able to access and view processes on OC apps .

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SM

### Version

- Component Version: 8.8 alpha4

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

During the 8.8 -> 8.9 upgrade path, users who had authorizations created in 8.8 were unable to log in or access OC apps (Operate, Identity, Tasklist) after migration.

### Root cause

The `resourcePropertyName` field was introduced in 8.9-SNAPSHOT. Authorizations persisted before 8.9 therefore have no value for this field in the database, causing it to deserialize as `null`. However, newly created 8.9 authorizations use an empty string (`""`).

The authorization checker [compares scopes](https://github.com/camunda/camunda/blob/e074ad63c9b078e11da0dfec5dd46201aa9a00a9/search/search-client-query-transformer/src/main/java/io/camunda/search/clients/auth/DefaultResourceAccessProvider.java#L60), where the static `WILDCARD` scope is constructed with `resourcePropertyName = ""`. When a legacy authorization came back from Elasticsearch with `resourcePropertyName = null`, the `null != ""` comparison caused the scope match to fail — effectively denying access to all users whose authorizations were created before 8.9.

Two places lacked proper null handling:

1. **`AuthorizationEntity`** was annotated with `@SinceVersion(value = "8.9.0", requireDefault = false)` and had no Java-level field default, so deserialized legacy records carried `null`.
2. **`AuthorizationScope`** 3-arg constructor assigned `resourcePropertyName` directly without null normalization, propagating the `null` into equality checks.

### Changes

**Backward compatibility and default handling:**
- `AuthorizationEntity`: Changed the field initializer to default `resourcePropertyName` to `""` and updated the `@SinceVersion` annotation to require default value (by removing `requireDefault = false`) so that pre 8.9 records without this field are treated identically to new resourceId-based authorizations.
- `AuthorizationScope`: In addition to the `AuthorizationEntity` default, defensive null-to-empty-string normalization was added to the 3-arg constructor, since `AuthorizationScope` is instantiated from several places across the codebase and relies on field-level `equals()` for authorization scopes matching. This ensures that even if `null` is passed from any call site, the comparison behavior remains correct. The 2-arg constructor was refactored to use constructor chaining for consistency.

#### Testing
- Added a new test scenario simulating a legacy (pre-8.9) authorization entity where `resourcePropertyName = null`, verifying that scope retrieval correctly matches and returns expected results.

#### Developer experience
- Added `toString()` to `AuthorizationScope` for improved debugging and logging output.

## Related issues

closes #45302

### CODE REVIEW

File: security/security-protocol/src/main/java/io/camunda/zeebe/protocol/record/value/AuthorizationScope.java [hunk 1]
```diff
@@ -33,7 +31,10 @@ public AuthorizationScope(
       final String resourcePropertyName) {
     this.matcher = matcher;
     this.resourceId = resourceId;
-    this.resourcePropertyName = resourcePropertyName;
+
+    // Since this class is used for comparisons, normalize null to empty string for this field
+    // (introduced in 8.9.0) to handle cases where null is provided while empty string is expected.
+    this.resourcePropertyName = resourcePropertyName != null ? resourcePropertyName : "";
```
Comment (ce-dmelnych) [inline security/security-protocol/src/main/java/io/camunda/zeebe/protocol/record/value/AuthorizationScope.java:37]: ℹ️ **Note for reviewers:**
The default value in `AuthorizationEntity` should already ensure `resourcePropertyName` is non-null in the common path.
However, `AuthorizationScope` is constructed from multiple call sites, so normalizing `null` -> `""` here as well is a defensive measure to avoid any subtle equality issues if another caller passes `null` when it should be an empty string for resourceId-based authorizations.

**Review by RomanJRW — APPROVED** [review]
LGTM, thanks again for fixing this 💪
