### PR TITLE
fix: allow support agents to access optimize

### LINKED ISSUE #52065: Support agents are not allowed to access Optimize
### 

### 

, 

### 

### 

### Description

Support and Dev are unable to access the customer's Optimize application due to strict per-organization role checks added in #39350. Currently, only users with the owner, admin, or analyst roles can access Optimize; having the supportagent role is not sufficient. Until the role is updated, support access to Optimize will require being added as analyst by the customer.

### Steps to reproduce

1. Onboard to a cluster as a support agent
2. Attempt to access Optimize

### Current behavior

The user fails authentication as a support agent.

### Expected behavior

The user should be able to access Optimize as a support agent.

### Workaround

1. Request the cluster owner to add the user as an analyst/admin/owner instead of using a support agent role.

### Environment

SaaS

### Version

- Optimize `8.8.18` and `8.9.0`

### Rootcause

Currently, only users with the owner, admin, or analyst roles can access Optimize as configured in the `CCSaaSSecurityConfigurerAdapter`. This should include the `supportagent` role so that engineers have access to debugging Optimize. https://github.com/camunda/camunda/blob/03d376d78520aec765ea3ad4b8762d38706f3c33/optimize/backend/src/main/java/io/camunda/optimize/rest/security/cloud/CCSaaSSecurityConfigurerAdapter.java#L90

### Solution ideas

Add the `supportagent` role as an allowed role to access Optimize.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tanjinyi**
## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #52065

### CODE REVIEW

File: optimize/backend/src/main/java/io/camunda/optimize/rest/security/cloud/CCSaaSSecurityConfigurerAdapter.java [hunk 1]
```diff
@@ -87,7 +87,8 @@ public class CCSaaSSecurityConfigurerAdapter extends AbstractSecurityConfigurerA
   public static final String CAMUNDA_CLUSTER_ID_CLAIM_NAME = "https://camunda.com/clusterId";
 
   private static final Logger LOG = LoggerFactory.getLogger(CCSaaSSecurityConfigurerAdapter.class);
-  private static final List<String> ALLOWED_ORG_ROLES = Arrays.asList("admin", "analyst", "owner");
+  private static final List<String> ALLOWED_ORG_ROLES =
```
Comment (konstantinos-mylosis) [inline optimize/backend/src/main/java/io/camunda/optimize/rest/security/cloud/CCSaaSSecurityConfigurerAdapter.java:90]: ❓Is there a chance we might be missing any other roles and bump into the same issue?
Should we make this configurable, or are these roles final and sufficient?

It might also be worth raising this in the incident channel for visibility.

**Review by konstantinos-mylosis — APPROVED** [review]
Pre-approving just a question to consider

File: optimize/backend/src/main/java/io/camunda/optimize/rest/security/cloud/CCSaaSSecurityConfigurerAdapter.java (hunk 1 above)
Comment (tanjinyi) [reply optimize/backend/src/main/java/io/camunda/optimize/rest/security/cloud/CCSaaSSecurityConfigurerAdapter.java:90]: I agree that we should make this list configurable as a follow-up. I noticed that there could also be the `operationsengineer` role in the list here: https://github.com/camunda/camunda-8-js-sdk/blob/9df162ecf9be1262b00a1d66c1547e6cac291524/src/admin/lib/AdminDto.ts#L111-L120
