### PR TITLE
Truncate log if checksum mismatch was caused by partial write

### LINKED ISSUE #6744: Distinguish corruption and partial flush
**Description**

Currently, a partial write caused by a crash during a flush is detected as log corruption. The issue is that even though the partial write can be safely discarded, a partially flushed write it's currently indistinguishable from an actual log corruption. This is the cause of this issue #6709 and the short-term solution to unblock us is to ignore it during start-up. Since that means we won't detect corruption, it would be good to have a better long-term solution.

Section 3.3.3 of https://www.usenix.org/system/files/conference/fast18/fast18-alagappan.pdf suggests an additional "persist" write and flush. I think this is equivalent to writing the written index in the config store. However, this would require another write and flush before the record can be considered persisted. The paper then suggests writing both and only flushing once after to reduce the performance impact. This means that if the second write can be verified, the checksum failed because of a partial write. If the second write isn't present then it's either because of a partially flushed write or because both were corrupted. These two situations can only be distinguished if we can read valid entries after them (which would tell us the previous records were corrupted). Corruption in the last record and in its "persist" record, and a partial write can't be distinguished.

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Use written index in the persisted in the metastore to distinguish between log corruption and partial writes caused by a broker crashing. Also adds an integration test that had to be removed due to the partial write issue as well as a new test for the partial write case.
 
## Related issues

closes #6744 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java [hunk 1]
```diff
@@ -216,6 +216,11 @@ public void deleteSnapshotStore() {
    * @return The opened log.
    */
   public RaftLog openLog() {
+    final long lastWrittenIndex;
+    try (final MetaStore metaStore = openMetaStore()) {
```
Comment (deepthidevaki) [inline atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java:220]: Why not pass the `lastWrittenIndex` instead of re-opening metastore?

File: journal/pom.xml [hunk 2]
```diff
@@ -142,7 +142,17 @@
           </usedDependencies>
         </configuration>
       </plugin>
-
+      <plugin>
+        <groupId>org.apache.maven.plugins</groupId>
+        <artifactId>maven-jar-plugin</artifactId>
```
Comment (deepthidevaki) [inline journal/pom.xml:147]: Why is this needed?

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerCorruptionTest.java [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+    clusteringRule
+        .getClient()
+        .newCreateInstanceCommand()
+        .bpmnProcessId("process")
+        .latestVersion()
+        .send()
+        .join();
+  }
+
+  private long getLastIndexWrittenToMetastore(final int nodeId) throws IOException {
```
Comment (deepthidevaki) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerCorruptionTest.java:104]: Can we move this test to Raft? Then we don't have to expose the implementation of metastore. We can use `metaStore.loadLastIndex` and `metastore.storeLastIndex` directly.

File: journal/src/main/java/io/zeebe/journal/file/SegmentedJournalBuilder.java [hunk 4]
```diff
@@ -131,9 +132,20 @@ public SegmentedJournalBuilder withJournalIndexDensity(final int journalIndexDen
     return this;
   }
 
+  public SegmentedJournalBuilder withLastWrittenIndex(final long lastWrittenIndex) {
```
Comment (deepthidevaki) [inline journal/src/main/java/io/zeebe/journal/file/SegmentedJournalBuilder.java:135]: Please add doc.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Looks good. Just some minor comments :+1:

On another point, I just realized a corner case that we may have not considered. What would happen if the lastWrittenIndex was updated to X, then the log was truncated to X-2, append new record at index X-1, crash with partial write at X-1.  No need to address it in this PR. But we should resolve it later.

File: atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java (hunk 1 above)
Comment (MiguelPires) [reply atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java:220]: It's self-contained, everything we need is in the RaftStorage itself so I didn't see a reason to involve something else. It's also only done when opening the log so there weren't any performance or concurrency issues. But I can keep a reference at the RaftStorage and always return it, like a singleton

File: journal/pom.xml (hunk 2 above)
Comment (MiguelPires) [reply journal/pom.xml:147]: To make LogCorrupter (which is in the journal tests) available for the qa tests

**Review by deepthidevaki — APPROVED** [review]
:tada:
