### PR TITLE
Use child instance loop counter

### LINKED ISSUE #6933: Multi-instance variables are wrong after resolving an incident
**Describe the bug**
If I resolve incidents on a parallel multi-instance subprocess then the multi-instance variables (i.e. loop counter and input element) of all instances are set to the values of the last inner instance.

The parallel multi-instance subprocess defines an input collection, an input element, and an input mapping.
If the input mapping fails then one incident is created for each inner instance.

image

If the incidents are resolved then the inner instances are activated but the values of the input element and the values of the loop counter are the same for all instances.

image

**To Reproduce**
1. deploy a workflow with a parallel multi-instance that defines 
  * an input collection `= items` 
  * an input element `item`
  * an input mapping `= y` -> `y`
2. create an instance with variables `{"items":[1,2,3]}`
3. await that 3 incidents are created
4. set a variable `y` on the process instance scope  
5. resolve the incidents   
6. verify that the inner instances are created but have the same muli-instance variables

**Expected behavior**
The multi-instance variables are different for each inner instance (i.e. all values of the input collection and loop counter).

**Log/Stacktrace**
No log or stacktrace available.

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `1.0.0-alpha7`
 - Configuration:

### PR DESCRIPTION
**Pull request by korthout**
## Description

After resolving an incident the failed command is processed again. If
that command is Element:Activate for a multi-instance marked element,
then the loop counter has already been incremented and would be
incremented again. 

To make sure we continue at the correct loop index, the loop counter
(which is used as index) can just be taken directly from the child instance.
The child instance already has the correct value set on activating.

## Related issues

closes #6933 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/MultiInstanceBodyProcessor.java [hunk 1]
```diff
@@ -115,12 +117,18 @@ public void onTerminate(
       final BpmnElementContext childContext) {
 
     final var bodyInstance = stateBehavior.getElementInstance(flowScopeContext);
-    final var loopCounter = bodyInstance.getMultiInstanceLoopCounter();
+
+    // on resolve incident, loop counter is potentially already set on the inner instance
+    final int loopCounter =
+        Optional.ofNullable(stateBehavior.getLocalVariable(childContext, LOOP_COUNTER_VARIABLE))
+            .map(MsgPackConverter::convertToJson)
+            .map(Integer::parseInt)
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/MultiInstanceBodyProcessor.java:125]: I am not sure whether this is the best way to retrieve this variable

Comment (saig0) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/MultiInstanceBodyProcessor.java:125]: This works nicely :+1: 

However, there is a small chance that it doesn't work. If the variable is modified (very unlikely but it is possible) then it would set the wrong loop variables. Or, it could create another incident or an error.

Instead, we could use the loop counter that was written to the state before.   

```
    final int loopCounter =
        Optional.ofNullable(stateBehavior.getElementInstance(childContext))
            .map(ElementInstance::getMultiInstanceLoopCounter)
            .orElse(bodyInstance.getMultiInstanceLoopCounter());
```

**Review by saig0 — CHANGES_REQUESTED** [review]
I like it :+1: 
Please have a look at my comment.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/MultiInstanceBodyProcessor.java (hunk 1 above)
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/MultiInstanceBodyProcessor.java]: That's a really nice solution, and I like it much better 👍

Comment (saig0) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/MultiInstanceBodyProcessor.java]: True. We don't need the optional :+1:

**Review by saig0 — APPROVED** [review]
:rocket: 

Feel free to remove the usage of `Optional` before merging.

**Comment by korthout** [comment]
bors merge
