### PR TITLE
Stop raft server when going inactive due to unrecoverable errors

### LINKED ISSUE #9924: ZeebePartition caught in a loop transition to inactive after a dead partition
**Describe the bug**

When the partition is dead to #9115, the partition is marked as dead. Since it is an unrecoverable error, it is transition to inactive. The transition to inactive is somehow cause it is triggering the failure listener again and a new transition is triggered.

See the following repeated log 
```
2022-07-28 16:20:27.724 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:21:27.844 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:22:27.866 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:23:28.048 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:24:28.352 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:25:28.613 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:26:28.634 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:27:28.731 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:28:29.242 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:29:30.363 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:30:30.373 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:31:30.375 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:32:30.903 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:33:31.575 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:34:32.325 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:35:32.414 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:36:32.803 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:37:33.645 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:38:34.538 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:39:34.984 CEST
Transition to INACTIVE on term 407 requested.
2022-07-28 16:40:35.415 CEST
Transition to INACTIVE on term 407 requested.
```
**To Reproduce**

Trigger #9115 

**Expected behavior**

* Mark the partition as dead once
* Transiton to inactive one and stop

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Previously, it was transitioning to inactive. But, in the configuration the member is still marked as active. As a result, the member transition back to active when it gets a new message from the leader. We cannot change the configuration, and mark this member as inactive because that would mean we are changing the quorum. What we really requires is that this partition is "dead" (atleast temporarily) so that it doesn't become leader again. We also don't want it to become a follower because this can also lead to partial functionality which can cause problems. For example, in follower role, raft is replicating events, but the streamprocessor or snapshotting is not working because of this error. So it is not able to compact the logs. This will eventually leads to disk space full and thus affecting other possibly healthy partitions.

To fix this, in this PR we stop the raft server instead of only transitioning to inactive. The replication factor and quorum remains the same. But this node cannot become leader again until the member is restarted.

## Related issues

closes #9924

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/partition/RaftPartition.java [hunk 1]
```diff
@@ -247,7 +247,7 @@ private boolean shouldStepDown() {
   }
 
   public CompletableFuture<Void> goInactive() {
-    return server.goInactive();
+    return server.stop();
   }
```
Comment (oleschoenburg) [inline atomix/cluster/src/main/java/io/atomix/raft/partition/RaftPartition.java:251]: :question: `goInactive` is used in two places, on unrecoverable errors and on recoverable errors on followers. Is it intended that recoverable errors on followers now stop the raft server?
Either way, I think we should rename the method to `stop` or similar.

Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/partition/RaftPartition.java:251]: Previously it was going inactive in both places, which was intended to behave similar to stop. So we are not changing the expected behavior.

**Review by lenaschoenburg — APPROVED** [review]
Thanks @deepthidevaki, LGTM :+1:

**Comment by deepthidevaki** [comment]
bors merge
