### PR TITLE
fix: do not log at error for known ClassCastException related to 8.7 heartbeats

### LINKED ISSUE #33127: Failed to dispatch message due to class ProtocolRequest cannot be cast to class ProtocolReply
### 

### 

### 

### 

### Description

- [Reported error in GCP](https://console.cloud.google.com/errors/detail/CO7zr_HSrffHigE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbzM9g&project=camunda-saas-int)
- [Logs](https://cloudlogging.app.goo.gl/yuhtJDJNJ4VxWgNs5)
- [Logs on Drive](https://drive.google.com/file/d/157u-oXp21XC-J0ve1g5WruWhJiTYFX4a/view?usp=sharing)

### Steps to reproduce

Unknown

### Current behavior

Unknown

### Expected behavior

Unknown

### Environment

SaaS

### Version

- Component Version: `8.8.0-alpha5-rc1`

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

_No response_

### PR DESCRIPTION
**Pull request by entangled90**
## Description
Unfortunately, the 8.7 heartbeats are not compatible with 8.8 version: as this is a known issue which does not cause any actual problem we don't need to log this particular case at error, but we can just log it infrequently at warn.

## Checklist

- [X] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #33127

### CODE REVIEW

File: zeebe/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 1]
```diff
@@ -1252,10 +1253,16 @@ protected void channelRead0(final ChannelHandlerContext ctx, final Object messag
...
         if (message instanceof final ProtocolRequest protocolMessage) {
           subject = protocolMessage.subject();
+          if (subject.equals(HeartbeatHandler.HEARTBEAT_SUBJECT)) {
+            level = Level.WARN;
+          }
         }
-        logger.error("Failed to dispatch message with subject {}", subject, e);
+        logger
+            .atLevel(level)
+            .log("Failed to dispatch message with subject {} because {}", subject, e.getMessage());
```
Comment (panagiotisgts) [inline zeebe/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:1267]: ❓ Could `subject=UNKOWN` lead to questions regarding the failed message? Maybe rename it to `no-subject`? `UNKNOWN` seems like a default enum mapping.

Comment (entangled90) [reply zeebe/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:1267]: Didn't thought about it being mistaken for a default enum value. We might even use a different log line if it's not set :shrug:

File: zeebe/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 2]
```diff
@@ -1250,12 +1251,21 @@ protected void channelRead0(final ChannelHandlerContext ctx, final Object messag
...
+        logClassCastException(message, e);
+      }
+    }
+
+    private void logClassCastException(final Object message, final ClassCastException e) {
+      final var logger = getLogger(message.getClass());
+      if (message instanceof final ProtocolRequest protocolMessage) {
+        final var subject = protocolMessage.subject();
+        final var level =
+            subject.equals(HeartbeatHandler.HEARTBEAT_SUBJECT) ? Level.WARN : Level.ERROR;
```
Comment (panagiotisgts) [inline zeebe/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java]:
```suggestion
            HeartbeatHandler.HEARTBEAT_SUBJECT.equals(subject) ? Level.WARN : Level.ERROR;
```
Inverse to avoid possible NPE if not all messages have subject value

**Review by panagiotisgts — APPROVED** [review]
LGTM. One suggestion for a possible NPE

File: zeebe/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java (hunk 2 above)
Comment (entangled90) [reply zeebe/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java]: Good catch!
