### PR TITLE
fix: set a project id for gcs backup store tests

### LINKED ISSUE #35204: GCS backup store without authentication needs a project id config
The GCS backup store supports `Authentication.None` for testing. Using that mode, the GCS client library can't know about the project id, a prerequisite for creating new buckets.

You can verify this by running `gcloud config unset project` in a terminal, and then trying to execute tests like `GcsBackupAcceptanceIT`. The will fail with the following exception: 

```
com.google.cloud.storage.StorageException: Required parameter project must be specified.
	at com.google.cloud.storage.StorageException.getStorageException(StorageException.java:110)
	at com.google.cloud.storage.StorageException.coalesce(StorageException.java:131)
	at com.google.cloud.storage.Retrying$DefaultRetrier.run(Retrying.java:180)
	at com.google.cloud.storage.Retrying$HttpRetrier.run(Retrying.java:206)
	at com.google.cloud.storage.StorageImpl.run(StorageImpl.java:1619)
	at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:147)
	at io.camunda.zeebe.it.backup.GcsBackupAcceptanceIT.beforeAll(GcsBackupAcceptanceIT.java:75)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	Suppressed: com.google.cloud.storage.RetryContext$RetryBudgetExhaustedComment: Unretryable error (attempts: 1, maxAttempts: 6, elapsed: PT0.009S, nextBackoff: PT1.565733751S, timeout: PT50S)
Caused by: java.lang.NullPointerException: Required parameter project must be specified.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:920)
	at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:138)
	at com.google.api.services.storage.Storage$Buckets$Insert.<init>(Storage.java:2605)
	at com.google.api.services.storage.Storage$Buckets.insert(Storage.java:2580)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:394)
	at com.google.cloud.storage.StorageImpl.lambda$create$0(StorageImpl.java:149)
	at com.google.cloud.storage.Retrying$DefaultRetrier.run(Retrying.java:165)
	... 6 more
```

This went unnotices so far because most of our developers have at some point set a default project, for example `gcloud config set project zeebe-io`. In our CI, the integration tests run on self-hosted VMs in GCP where the client library can discover the project id from its environment.

We should introduce a new optional configuration property to specify the project id. If it is set, we use it to build the client in `GcsBackupStore#buildClient`

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Sets a fixed project id for tests where no authentication information is set. Closes #35204

### CODE REVIEW

File: zeebe/backup-stores/gcs/src/main/java/io/camunda/zeebe/backup/gcs/GcsBackupConfig.java [hunk 1]
```diff
@@ -68,18 +70,19 @@ public Builder withBasePath(final String basePath) {
...
-    public Builder withHost(String host) {
+    public Builder withHost(final String host) {
       this.host = host;
       return this;
     }
 
     public Builder withoutAuthentication() {
-      this.auth = new GcsConnectionConfig.Authentication.None();
+      // This is only used for testing, so we can make up a project id for it.
+      auth = new None("tmp");
```
Comment (panagiotisgts) [inline zeebe/backup-stores/gcs/src/main/java/io/camunda/zeebe/backup/gcs/GcsBackupConfig.java:80]: ❓  Do we really need this `projectId` to be passed here? We can consider this a default when building a client with Authentication.None since this is only for testing purposes.

Comment (lenaschoenburg) [reply zeebe/backup-stores/gcs/src/main/java/io/camunda/zeebe/backup/gcs/GcsBackupConfig.java:80]: Yeah that would be another way to do it 👍 
I don't have a strong preference but also see no problem with attaching it to the `Authentication.None` record.

**Review by panagiotisgts — APPROVED** [review]
LGTM. Leaving the specified default `projectId` up to you as it's mostly personal preference.
