### PR TITLE
fix: make publishMessage via REST pickup the default timeToLive

### LINKED ISSUE #32320: Zeebe client is not applying default ttl of 1h to REST request
### 

### 

, , 

### 

### 

### Description

The docs on the Zeebe/Camunda Spring SDK state that a [default TTL of 1h](https://docs.camunda.io/docs/8.6/apis-tools/spring-zeebe-sdk/configuration/#message-time-to-live) is used for publishMessage commands/requests.

However, this default ttl is only applied for GRPC requests not on HTTP requests when using:
```
camunda:
  client:
    zeebe:
      prefer-rest-over-grpc: true
```

### Steps to reproduce

1. configure the 8.6 sdk/client to prefer REST over GRPC
2. create and send a publishMessage command

### Current behavior

3. the default TTL of 1h (3600000) is not set on the HTTP request, but 0 instead
```
{
  "name" : "Message_Receive",
  "correlationKey" : "2",
  "timeToLive" : 0,
  "variables" : {
    "someId" : "value"
  },
  "tenantId" : "<default>"
}
```

### Expected behavior

3. the default TTL of 1h should be set on the request
```
{
  "name" : "Message_Receive",
  "correlationKey" : "2",
  "timeToLive" : 3600000,
  "variables" : {
    "someId" : "value"
  },
  "tenantId" : "<default>"
}
```
just like it's done for the GRPC request if `prefer-rest-over-grpc: false`
```
name: "Message_Receive"
correlationKey: "2"
timeToLive: 3600000
variables: "{\"someId\":\"value\"}"
tenantId: "<default>"
```

### Environment

SaaS & SM

### Version

- Component Version: >=8.6 up to 8.8

### Rootcause

The default TTL is only set for the GRPC request builder at https://github.com/camunda/camunda/blob/main/clients/java/src/main/java/io/camunda/client/impl/command/PublishMessageCommandImpl.java#L66 but not on `httpRequestConfig`

### Solution ideas

Apply the default TTL to both request builders.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

See this [thread](https://camunda.slack.com/archives/C08MRKHJ0CD/p1747724563904209) by @kaviya-sridhar how encountered this behavior

### PR DESCRIPTION
**Pull request by megglos**
## Description

The default ttl was not applied to publishMessage requests via REST. The cause was that the default was only applied to the GRPC request builder.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #32320

### CODE REVIEW

File: clients/java/src/test/java/io/camunda/zeebe/client/process/PublishMessageTest.java [hunk 1]
```diff
@@ -63,6 +63,22 @@ public void shouldPublishMessage() {
...
+    final long messageKey = 123L;
+    gatewayService.onPublishMessageRequest(messageKey);
+
+    // when
+    final PublishMessageResponse response =
+        client.newPublishMessageCommand().messageName("name").correlationKey("key").send().join();
+
+    // then
+    final PublishMessageRequest request = gatewayService.getLastRequest();
+    assertThat(request.getTimeToLive()).isEqualTo(Duration.ofHours(1).toMillis());
```
Comment (tmetzke) [inline clients/java/src/test/java/io/camunda/zeebe/client/process/PublishMessageTest.java:78]: 💭 Ideally, the default ttl would be a constant we can use here to avoid adjusting magic numbers in tests if we change it in the future. But I guess it's stable enough, so 🤷

**Review by tmetzke — APPROVED** [review]
👍 Thanks, @megglos 🚀

File: clients/java/src/test/java/io/camunda/zeebe/client/process/PublishMessageTest.java (hunk 1 above)
Comment (megglos) [reply clients/java/src/test/java/io/camunda/zeebe/client/process/PublishMessageTest.java:78]: 👍  let me extract that for reuse.

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientBuilderImpl.java [hunk 2]
```diff
@@ -83,6 +83,7 @@ public final class ZeebeClientBuilderImpl implements ZeebeClientBuilder, ZeebeCl
   public static final String USE_DEFAULT_RETRY_POLICY_VAR = "ZEEBE_CLIENT_USE_DEFAULT_RETRY_POLICY";
   private static final String TENANT_ID_LIST_SEPARATOR = ",";
   private static final boolean DEFAULT_PREFER_REST_OVER_GRPC = false;
+  public static final Duration DEFAULT_MESSAGE_TTL = Duration.ofHours(1);
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientBuilderImpl.java:86]: 🙃 Public constants go first, according to codestyle 🙂

Comment (megglos) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientBuilderImpl.java:86]: need to check my intellij settings, don't we have this covered by auto-format config?

Comment (megglos) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientBuilderImpl.java:86]: Seems intelliJ only does this via "rearrange code", enabled it now, let's see how often it causes more changes than intended :D

Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientBuilderImpl.java]: 🤣
