### PR TITLE
fix(stream-processor): throw instead of ignoring unknown records

### LINKED ISSUE #7449: Stream processor is not able to detect nor handle records of different versions gracefully
**Description**

Currently we compare on processing the version of the records, but this version is hard coded in the protocol. It might be never or very sparse updated. If a version mismatch is detected then the processor blows up. This might also not really visible to the end user.

Related comment on ZEP: Build State on Followers https://github.com/zeebe-io/enhancements/pull/16

> saig0
>> In our processing and replay state machine we have event filters, which verify the version of the read entry.
> 
> Yes, we have a filter in the processing and the replay state machine. But it's good to know that it checks the version of the protocol (defined in /protocol/pom.xml) and not the version of the broker itself.
> 
> Currently, the protocol version is not updated strictly. For example, when adding a new value type to the enum.
> 
> Apart from changing the protocol definition itself, we might need to consider other changes in the broker. For example, adding a new BPMN element type. If an old follower is not aware of a new BPMN element then it is not able to produce the correct state.
> 
> We should think about checking the broker version instead.
> 
>> Newer entries are ignored by the Follower with the old version.
> 
> Ignored is maybe not the correct word sweat_smile The version check throws an exception. I'm not sure how nice this looks in the logs.
> 
> Maybe, we want to handle this case more clear to identify it in the logs when it happens.

https://github.com/zeebe-io/enhancements/pull/16#discussion_r662755676

This is interesting for building state on followers and supporting rolling updates.

### LINKED ISSUE #16376: `ProcessingStateMatchine` must not ignore commands without a matching processor

### LINKED ISSUE #16379: `ReplayStateMachine` must not ignore events without a matching processor

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Both Processing- and ReplayStateMachine now throw instead of ignoring records without a matching processor. This results in the StreamProcessor failing, ensuring that no further processing occurs.

Closes #16376
Closes #16379 
Closes #7449 because the issue is now outdated. The stream processor shuts down when it encounters a record it can't process or replay.

### CODE REVIEW

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ * except in compliance with the Zeebe Community License 1.1.
+ */
+package io.camunda.zeebe.stream.impl;
+
+import io.camunda.zeebe.stream.api.records.TypedRecord;
+import io.camunda.zeebe.util.exception.UnrecoverableException;
+
+/**
+ * Exception type thrown by the {@link ProcessingStateMachine} when encountering a command that is
+ * not accepted by any of the registered processors.
```
Comment (Zelldon) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java:15]: 💭 Since we don't expect ever a command that is not processed? 🤔 Might there be any case for this, the backup processor is next to the engine right in the same state machine so this will not cause any issue I guess?

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 2]
```diff
@@ -356,22 +356,21 @@ private void batchProcessing(final TypedRecord<?> initialCommand) {
...
-                lastProcessingResultSize,
-                // +1 since we already need include the current command in the calculation
-                pendingCommands.size() + processedCommandsCount + 1,
-                currentProcessingBatchLimit);
-
-        pendingCommands.addAll(batchProcessingStepResult.toProcess());
-        pendingWrites.addAll(batchProcessingStepResult.toWrite());
-        currentProcessingResult.getProcessingResponse().ifPresent(pendingResponses::add);
-      }
+              .orElseThrow(() -> new NoSuchProcessorException(command));
```
Comment (Zelldon) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java]: ❓ 🤔 Can this be an issue when we stop supporting a certain command, and write different command now ( I think this happened in the past). This would mean we have no longer a processor for an old command 🤔 Hm before we just skipped it? 🤔 I'm a bit unsure here.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java [hunk 3]
```diff
@@ -16,7 +16,20 @@
...
-    super("No processor registered for command type %s".formatted(command.getValueType()));
+  private NoSuchProcessorException(final String message) {
+    super(message);
+  }
+
+  public static NoSuchProcessorException forRecord(final TypedRecord<?> record) {
+    final var message =
+        switch (record.getRecordType()) {
+          case EVENT ->
+              "No processor registered for event type %s".formatted(record.getValueType());
```
Comment (Zelldon) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java:27]: ❌ 🤔 There are no processor for events (per definition) and also no for command rejections.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/records/TypedRecordImpl.java [hunk 4]
```diff
@@ -38,6 +38,7 @@ public void wrap(
     this.value = value;
   }
 
+  @JsonIgnore
```
Comment (Zelldon) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/records/TypedRecordImpl.java:41]: ❓ Why was this necessary?

**Review by ChrisKujawa — COMMENTED** [review]
I'm a bit unsure about some changes, and would like to play the "telefon joker" card

🤙🏼 Calling (old engine gurus) @saig0 or @korthout for some more input on this, related to my questions what if a processor doesn't exist for a deprecated command (can or will this happen? Did it ever happened?)

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/records/TypedRecordImpl.java (hunk 4 above)
Comment (oleschoenburg) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/records/TypedRecordImpl.java:41]: Because otherwise it's serialized. See the other fields in this class.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java (hunk 3 above)
Comment (oleschoenburg) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java:27]: This is the terminology we use within the stream-platform module. Everything is a `RecordProcessor`: https://github.com/camunda/zeebe/blob/4e17f4375c77b5087b7d1ae447e19f7fff2d18f3/stream-platform/src/main/java/io/camunda/zeebe/stream/api/RecordProcessor.java

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 2 above)
Comment (oleschoenburg) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java]: This would be a problem, yeah :+1:
But if we stop using a command, we can't just remove the processor for it because we need to process anything that's already on the logstream. So it would be correct to stop here, incorrect to just remove the processor.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java (hunk 1 above)
Comment (oleschoenburg) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java:15]: Yeah, this assumes that all commands have a matching processor.
Based on that all tests are passing and the engine registers processors for all commands + we register one processor for Checkpoint records.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java (hunk 3 above)
Comment (Zelldon) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java:27]: Ah so you referring to the record processor here? 

Still there will never be an exception for the command rejection, as processing will filter this already before.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/records/TypedRecordImpl.java (hunk 4 above)
Comment (Zelldon) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/records/TypedRecordImpl.java:41]: But why was it necessary NOW ?

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java (hunk 3 above)
Comment (oleschoenburg) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/NoSuchProcessorException.java:27]: Yeah that's fair. I provided a special error message for `COMMAND_REJECTION`, `SBE_UNKNOWN`, and `NULL_VAL`. While it's currently not necessary because it should be filtered out, I think it's better to be safe here and also handle these cases so that we get nice error messages if we ever break the filtering.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/records/TypedRecordImpl.java (hunk 4 above)
Comment (oleschoenburg) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/records/TypedRecordImpl.java:41]: Because I added the method `getMetadata` that gets picked up by Jackson such that all metadata is serialized again. We don't want that so I also had to add `JsonIgnore` to prevent it.

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 2 above)
Comment (korthout) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java]: Hmm. Yes, we should not remove processors when we deprecate commands. While this may have happened in the past, we also keep such processors around. For example, we still support the deprecated deployment distributions while deployments are distributed with command distribution nowadays:

https://github.com/camunda/zeebe/blob/4e17f4375c77b5087b7d1ae447e19f7fff2d18f3/engine/src/main/java/io/camunda/zeebe/engine/processing/EngineProcessors.java#L253-L266

We could benefit from tests that deter us from removing processors.

Comment (oleschoenburg) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java]: Alright, thanks for confirming :+1: 

I think this discussion is resolved then?

**Review by ChrisKujawa — APPROVED** [review]
Thanks 🙇‍♂️
