### PR TITLE
fix: Operate OpensearchConnector ignores awsEnabled

### LINKED ISSUE #45761: [8.9.0-alpha4+] Legacy Operate OpensearchConnector ignores awsEnabled — crashes on IRSA deployments
# Legacy Operate OpensearchConnector ignores `awsEnabled` — crashes on IRSA deployments

### 

### 

### 

### 

### Description

The **legacy** Operate `OpensearchConnector` (`io.camunda.operate.connect.OpensearchConnector`) does not pick up `awsEnabled=true` when running with AWS OpenSearch via IRSA authentication. The **new unified** connector (`io.camunda.search.connect.os.OpensearchConnector`) correctly resolves AWS credentials in the exact same pod.

This causes the legacy connector to fall back to basic auth (no credentials), resulting in HTTP 401 from AWS OpenSearch, 50 failed retries, bean creation failure, and ultimately `CrashLoopBackOff`.

Two connectors coexist in the same JVM, reading `awsEnabled` from different sources:

| Connector | Class | Property read | Result |
|---|---|---|---|
| **NEW** (unified) | `io.camunda.search.connect.os.OpensearchConnector` | `camunda.database.awsEnabled` | `true` ✅ |
| **LEGACY** (Operate) | `io.camunda.operate.connect.OpensearchConnector` | `operateProperties.getOpensearch().isAwsEnabled()` | `false` ❌ |

### Steps to reproduce

1. Deploy Camunda 8.9.0-alpha4 on EKS with AWS OpenSearch using IRSA (IAM Roles for Service Accounts)
2. Set `global.opensearch.aws.enabled: true` in helm values
3. Observe the orchestration pod entering `CrashLoopBackOff`
4. In the pod logs, the NEW connector logs `"AWS Credentials CAN be resolved"` while the LEGACY connector logs `"AWS Credentials are disabled. Using basic auth."`

### Current behavior

The legacy Operate `OpensearchConnector` ignores the `awsEnabled` property and falls back to basic auth, producing this crash chain:

```
UnsatisfiedDependencyException
  → ProcessCache
    → OpensearchProcessStore
      → RichOpenSearchClient
        → operateOpenSearchClient bean
          → Factory method threw exception: java.io.IOException: Unauthorized access
```

Log evidence:

```
io.camunda.operate.connect.OpensearchConnector - AWS Credentials are disabled. Using basic auth.
io.camunda.operate.connect.OpensearchConnector - Username and/or password for are empty. Basic authentication for OpenSearch is not used.
io.camunda.operate.connect.OpensearchConnector - Error in getting health status from localhost:9205
```

Note: `"localhost:9205"` is a hardcoded string in the source code of `OpensearchConnector.checkHealth()`, not a configuration value. The actual retry logs show the correct URL (`https://vpc-eks-....eu-west-2.es.amazonaws.com:443`), all returning HTTP 401.

### Expected behavior

The legacy Operate `OpensearchConnector` should respect `awsEnabled=true` and use SigV4-signed requests against AWS OpenSearch, just like the new unified connector does in the same pod.

### Workaround

Add explicit environment variables in helm values to force `awsEnabled=true` via Spring Boot property binding, bypassing the `OperatePropertiesOverride` bean construction:

```yaml
orchestration:
  env:
    - name: CAMUNDA_OPERATE_OPENSEARCH_AWSENABLED
      value: "true"
    - name: CAMUNDA_TASKLIST_OPENSEARCH_AWSENABLED
      value: "true"
```

### Environment

SM — AWS EKS single-region with IRSA, AWS Managed OpenSearch (SigV4 auth, no basic auth)

### Version

- Camunda image: `camunda/camunda:8.9.0-alpha4`
- Helm chart: `oci://ghcr.io/camunda/helm/camunda-platform` version `0.0.0-snapshot-alpha` (chart 8.9)
- Spring profiles active: `broker, identity, operate, tasklist, consolidated-auth`

### Rootcause

The `@Primary OperateProperties` bean is constructed in `OperatePropertiesOverride.operateProperties()` as follows:

```java
// Step 1: fresh instance with defaults (awsEnabled=false)
OperateProperties override = new OperateProperties();

// Step 2: copy from legacy bean (bound to camunda.operate.*)
BeanUtils.copyProperties(legacyOperateProperties, override);

// Step 3: populate from unified database config
populateFromOpensearch(override, database);
```

The method `populateFromOpensearch()` explicitly sets many properties but **omits `awsEnabled`**:

```java
private void populateFromOpensearch(OperateProperties override, DatabaseProperties database) {
    override.getOpensearch().setUrl(database.getUrl());
    override.getOpensearch().setUrls(database.getUrls());
    override.getOpensearch().setUsername(database.getUsername());
    override.getOpensearch().setPassword(database.getPassword());
    override.getOpensearch().setClusterName(database.getClusterName());
    override.getOpensearch().setIndexPrefix(database.getIndexPrefix());
    override.getOpensearch().setDateFormat(database.getDateFormat());
    override.getOpensearch().setProxy(database.getProxy());
    override.getOpensearch().setSocketTimeout(database.getSocketTimeout());
    override.getOpensearch().setConnectTimeout(database.getConnectTimeout());
    override.getOpensearch().setSsl(database.getSsl());
    override.getOpensearch().setInterceptorPlugins(database.getInterceptorPlugins());
    override.getDatabase(DatabaseType.Opensearch);
    // NOTE: awsEnabled is NOT propagated here
}
```

This means `awsEnabled` relies entirely on Step 2 (`BeanUtils.copyProperties`) copying from `LegacyOperateProperties`. If `camunda.operate.opensearch.awsEnabled` is absent from the ConfigMap (possible with snapshot chart drift), the default `false` is kept, and `populateFromOpensearch()` never corrects it.

The chart 8.9 `_application.yaml` template on current `main` does generate the property correctly:

```yaml
{{- if .Values.orchestration.profiles.operate -}}
  {{- if .Values.global.opensearch.enabled }}
    operate:
      opensearch:
        awsEnabled: {{ .Values.global.opensearch.aws.enabled }}
  {{- end }}
{{- end }}
```

However, the `0.0.0-snapshot-alpha` chart is a moving target rebuilt on every merge. The exact template at deployment time may differ from `main`.

### Solution ideas

In `populateFromOpensearch()`, add the missing propagation:

```java
override.getOpensearch().setAwsEnabled(database.isAwsEnabled());
```

This ensures `awsEnabled` is always propagated from the unified `DatabaseProperties`, regardless of whether the legacy `camunda.operate.opensearch.awsEnabled` property is present in the ConfigMap.

The same fix should be applied to any equivalent `populateFromElasticsearch()` or Tasklist override if a similar pattern exists.

### Dev -> QA handover

- Resources:
  - `io.camunda.operate.connect.OpensearchConnector`
  - `io.camunda.webapps.operate.OperatePropertiesOverride`
  - `io.camunda.webapps.operate.OperatePropertiesOverride.populateFromOpensearch()`
- Versions to validate: 8.9.0-alpha5+
- Release version (in which version this feature will be released):

### Links

- Affected classes:
  - `io.camunda.operate.connect.OpensearchConnector` — legacy Operate connector
  - `io.camunda.webapps.operate.OperatePropertiesOverride` — bean override logic
  - `io.camunda.webapps.operate.OperatePropertiesOverride.populateFromOpensearch()` — missing `awsEnabled`
- Helm chart template: `charts/camunda-platform-8.9/templates/orchestration/configmap.yaml` → `_application.yaml`

### Automated Test Impact

A test should verify that when `camunda.database.awsEnabled=true` is set, the `@Primary OperateProperties` bean also has `opensearch.awsEnabled=true` after `OperatePropertiesOverride` construction. Currently no test covers this propagation path.

### PR DESCRIPTION
**Pull request by kristinkomschow**
## Description

Ensure awsEnabled properties get propagated to the legacy Operate OS connector.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes https://github.com/camunda/camunda/issues/45761

### CODE REVIEW

File: configuration/src/test/java/io/camunda/configuration/OperatePropertiesTest.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  OperatePropertiesOverride.class,
+  UnifiedConfigurationHelper.class,
+  UnifiedConfiguration.class,
+  SearchEngineConnectProperties.class,
+  SearchEngineConnectPropertiesOverride.class
+})
+@TestPropertySource(
+    properties = {
+      "camunda.data.secondary-storage.type=opensearch",
+      "camunda.database.awsEnabled=true"
```
Comment (buccarel) [inline configuration/src/test/java/io/camunda/configuration/OperatePropertiesTest.java]: I don't think I am understanding this PR: `camunda.database.awsEnabled` doesn't seem to be a Unified Configuration property:
* `camunda.database` is not part of the unified schema
* (nit pick) `awsEnabled` is not in kebab-case

If we're ignoring this property, it might be a bug, but that means:
* there should be a unified configuration version of this property
* such unified property should have `camunda.database.awsEnabled` as fallback (most likely, backwards compatibility fully supported)

Do we have this already? Or maybe I am misunderstanding the PR?

Comment (kristinkomschow) [reply configuration/src/test/java/io/camunda/configuration/OperatePropertiesTest.java]: The issue description specifically mentioned that `camunda.database.awsEnabled=true` is expected to result in `opensearch.awsEnabled=true` being set in the Operate properties so the legacy Operate OpensearchConnector uses that configuration in the same way as the `io.camunda.search.connect.os.OpensearchConnector`. The latter gets this property from the [ConnectConfiguration](https://github.com/camunda/camunda/blob/b1338c3725788a05f3f2d6f0c8c0623bcc9e67d0/search/search-client-connect/src/main/java/io/camunda/search/connect/os/OpensearchConnector.java#L51), which is populated by the [LegacySearchEngineConnectProperties ](https://github.com/camunda/camunda/blob/main/configuration/src/main/java/io/camunda/configuration/beans/LegacySearchEngineConnectProperties.java)(that's where the `camunda.database` property prefix comes from).
If we want this property in the unified config I don't mind either, but my understanding is that `camunda.database.awsEnabled=true` specifically used to work as expected for Operate but broke with a recent update. Whether we want to move this property to the unified config may also be a discussion worth having, but this PR aimed to fix something that seems to have been a regression from a prevous patch version.

File: operate/common/src/main/java/io/camunda/operate/connect/OpensearchConnector.java [hunk 2]
```diff
@@ -159,7 +162,7 @@ public OpenSearchClient createOsClient(
         final HealthResponse response = openSearchClient.cluster().health();
         LOGGER.info("OpenSearch cluster health: {}", response.status());
       } catch (final IOException e) {
-        LOGGER.error("Error in getting health status from {}", "localhost:9205", e);
+        LOGGER.error("Error in getting health status from {}", hosts, e);
```
[the remark this answers is not in the document]
Comment (kristinkomschow) [reply operate/common/src/main/java/io/camunda/operate/connect/OpensearchConnector.java]: I'll still fix that with any other change requests that might come up

**Comment by kristinkomschow** [comment]
I'd forgotten to also fix the "hosts" log message when updating the branch.

File: configuration/src/test/java/io/camunda/configuration/OperatePropertiesTest.java (hunk 1 above)
Comment (buccarel) [reply configuration/src/test/java/io/camunda/configuration/OperatePropertiesTest.java]: I think I didn't explain myself very well, sorry about that. I'll rephrase it.

The unified configuration system in general, currently, works by taking values from the unified configuration and propagating them into the legacy values. For example, the unified property `camunda.database.secondary-storage.type`, that can be {elasticsearch, opensearch, etc...} is propagated into the legacy `camunda.database.type` (and others).

If, as you're saying, the legacy property `camunda.database.awsEnabled=true` needs to be set in the operate properties, that is fine. But this PR is using the unified configuration classes to do `setAwsEnabled(x)` - which is legacy - with the value `x` that comes from `connectProperties` - which is also legacy.

Why is the unified configuration system involved with this assignment?

**Comment by houssain-barouni** [comment]
@buccarel I believe the `awsEnabled` qualifies to be part of the unified configuration.
We need a common property to feed all the legacy properties:
- connect property: `camunda.database.awsEnabled`
- tasklist property: `camunda.tasklist.opensearch.awsEnabled`
- operate property: `camunda.operate.opensearch.awsEnabled`
- exporter property: `zeebe.broker.exporters.camundaexporter.args.connect.awsEnabled`

I think it is very important especially for the exporter, because if we don't have it, you need to explicitly specify it with the legacy exporter property, and you would loose the auto configuration of the exporter, as you will need also to define all the exporters properties

The unified configuration would be `camunda.data.secondary-storage.opensearch.aws-enabled`

File: configuration/src/test/java/io/camunda/configuration/OperatePropertiesTest.java (hunk 1 above)
Comment (kristinkomschow) [reply configuration/src/test/java/io/camunda/configuration/OperatePropertiesTest.java]: Ok, now I understand the concern.

> Why is the unified configuration system involved with this assignment?

My confusion came from the fact that the `io.camunda.search.connect.os.OpensearchConnector` was marked as "unified" in the issue description and uses the new `ConnectConfiguration`, which also sets this property via `camunda.database.awsEnabled`, so I wasn't aware this configuration is not considered part of the unified config, especially since the whole issue description is based on the assumption that this property should be propagated.
I'll write a suggestion in the issue description since I think it shouldn't be buried in the comments here 😄

**Review by buccarel — DISMISSED** [review]
requesting changes based on the following discussion:

https://github.com/camunda/camunda/pull/47230/changes#r2877138179

**Comment by kristinkomschow** [comment]
I introduced a unified config value as was suggested in the discussions so far. Waiting for[ distro to confirm](https://github.com/camunda/camunda/issues/45761#issuecomment-4083504133) we can implement this in the helm-chart.
@buccarel is there anyone else we'd have to involve (e.g. console)?

**Comment by kristinkomschow** [comment]
@igpetrov Also adding you as reviewer since @buccarel is out sick and I'd like to get this merged sooner rather than later (since code freeze is close)

**Review by igpetrov — APPROVED** [review]
LGTM. Please, keep in mind, I haven't see UC code for a while, so maybe it would be worth for @buccarel having another round of review post-merge.
For now, in my opinion, this code is good to move `main`.

**Comment by kristinkomschow** [comment]
Rebased branch to see if the merge stops failing
