### PR TITLE
Stabilize `LongPollingActivateJobsTest` by awaiting for condition before assertions

### LINKED ISSUE #8671: `LongPollingActivateJobsTest.shouldUnblockRequestWhenJobsAvailable` is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? At least once in this PR: https://github.com/camunda-cloud/zeebe/pull/8614
- Does it block your work? No
- Do we suspect that it is a real failure? Not sure

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Wanted but not invoked:
serverStreamObserver.onCompleted();
-> at io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldUnblockRequestWhenJobsAvailable(LongPollingActivateJobsTest.java:119)
However, there were exactly 4 interactions with this mock:
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.onNext(
    jobs {
  key: 4503599627370496
  type: "test"
  processInstanceKey: 123
  bpmnProcessId: "stubProcess"
  processDefinitionVersion: 23
  processDefinitionKey: 4532
  elementId: "stubActivity"
  elementInstanceKey: 459
  customHeaders: "{\"foo\":12,\"bar\":\"val\"}"
  retries: 12
  deadline: 123123123
  variables: "{\"foo\":13,\"bar\":\"world\"}"
}
);
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
Wanted but not invoked:
serverStreamObserver.onCompleted();
-> at io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldUnblockRequestWhenJobsAvailable(LongPollingActivateJobsTest.java:119)
However, there were exactly 4 interactions with this mock:
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.onNext(
    jobs {
  key: 4503599627370496
  type: "test"
  processInstanceKey: 123
  bpmnProcessId: "stubProcess"
  processDefinitionVersion: 23
  processDefinitionKey: 4532
  elementId: "stubActivity"
  elementInstanceKey: 459
  customHeaders: "{\"foo\":12,\"bar\":\"val\"}"
  retries: 12
  deadline: 123123123
  variables: "{\"foo\":13,\"bar\":\"world\"}"
}
);
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.onResponse(LongPollingActivateJobsRequest.java:88)
	at io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldUnblockRequestWhenJobsAvailable(LongPollingActivateJobsTest.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:199)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:193)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Standard Output
14:09:30.855 [main] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
14:09:30.856 [-zb-fs-workers-0] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
14:09:30.857 [main] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
14:09:30.859 [-zb-actors-11] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
</pre>
</details>

### PR DESCRIPTION
**Pull request by korthout**
## Description

This tries to improve the stability of the `LongPollingActivateJobsTest` by awaiting a condition before making the assertions, instead of having an individual timeout on each assertion. Awaitility waits at most 10s for the condition.

## Related issues

closes #8671

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by deepthidevaki — COMMENTED** [review]
Thanks @korthout for looking into this. I am not sure if this will fix it because I think the root cause is different.

After reading the logs from the error report, I think that the issue is with the timeout in https://github.com/camunda/zeebe/blob/403942f036cdd9120d153f3f4b25cedd3d36fd13/gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java#L133
In the logs, `onNext` has been called. But not `onComplete`. But it is not clear if the request has been cancelled. `isCancelled` only checks if it is cancelled. I doubt it is cancelled because then it wouldn't call onNext. What might have happened is the following. One job is activated, so it call `onNext` to send the job to the client, but then continue to activate the remaining jobs from the remaining partitions. So `onComplete` will not be called until long polling timeout as there are no more jobs available.

Wdyt?

**Comment by korthout** [comment]
@deepthidevaki sorry for the late reply. I've finally had some time to look at it again, and I think you're right. I misread the `isCancelled` calls for `onCancel` or so, when they in fact only indicate a status check.

I also think your analysis is correct and that the onCompleted simply had not yet been called, even though onNext had. I think it makes more sense to first await for a condition after which we know that we can make all assertions. I've applied this concept in the latest commit.

Please have a look and let me know what you think.

File: gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java [hunk 1]
```diff
@@ -212,10 +214,11 @@ public void shouldCompleteFollowingRequestsAfterTimeout() {
     activateJobsStub.addAvailableJobs(TYPE, 1);
     brokerClient.notifyJobsAvailable(TYPE);
     handler.activateJobs(successRequest);
+    Awaitility.await().until(successRequest::isCompleted);
```
Comment (deepthidevaki) [inline gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java:217]: :thought_balloon: Should we wait until it is completed? I think since we request 2 jobs, but only one job is available it will still wait for longPollingTimeout (=5s) to complete the request. So either we don't wait until it is completed (only verify that `onNext` is called), or ensure that the request can be completed fast by making 2 jobs available.

Comment (deepthidevaki) [reply gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java:217]: Sorry.. This comment was meant to the changes in  `shouldUnblockRequestWhenJobsAvailable` :)

Comment (korthout) [reply gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java:217]: Interesting point, but the test completes after about 200ms, so it doesn't look like it waits for this timeout.

Screen Shot 2022-05-04 at 15 44 30

I also tested it without awaiting until the request has been completed (and removing the assertion that onCompleted is called altogether), which is faster (somewhat unsurprisingly).
Screen Shot 2022-05-04 at 15 45 39

I do like the idea, but I'm just uncertain about our assumptions because of this. What do you think?

Comment (deepthidevaki) [reply gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java:217]: Ok. Then ignore my comment. Looks like it completes the request because atleast one job was activated.

**Review by deepthidevaki — APPROVED** [review]
Thanks @korthout :tada:
