### PR TITLE
fix: Operate cannot deserialize IN_PROGRESS snapshot state in Opensearch

### LINKED ISSUE #33516: Operate cannot deserialize IN_PROGRESS snapshot state in Opensearch
### 

### 

, , , , 

### 

### 

### Description

Operate is not able to deserialize `IN_PROGRESS` snapshot state returned by Opensearch when polling for backup status. As a result, calls to Get Backup status throws an exception whenever a snapshot is still in progress.

The list of supported snapshot state by Opensearch are documented here https://docs.opensearch.org/docs/latest/api-reference/snapshots/get-snapshot-status/#snapshot-states

### Steps to reproduce

It is hard to reproduce as this requires having a snapshot in IN_PROGRESS state in OpenSearch

### Current behavior

```
io.camunda.operate.webapp.api.v1.exceptions.ClientException: Exception occurred when searching for backup with ID [...].
	at io.camunda.operate.webapp.api.v1.rest.ErrorController.handleException(ErrorController.java:66) ~[operate-webapp-8.6.9.jar:8.6.9]
...
Caused by: io.camunda.operate.exceptions.OperateRuntimeException: Exception occurred when searching for backup with ID [...].
	at io.camunda.operate.webapp.opensearch.backup.OpensearchBackupRepository.findSnapshots(OpensearchBackupRepository.java:342) ~[operate-webapp-8.6.9.jar:8.6.9]
	at io.camunda.operate.webapp.opensearch.backup.OpensearchBackupRepository.getBackupState(OpensearchBackupRepository.java:140) ~[operate-webapp-8.6.9.jar:8.6.9]
	at io.camunda.operate.webapp.backup.BackupService.getBackupState(BackupService.java:190) ~[operate-webapp-8.6.9.jar:8.6.9]
	at io.camunda.operate.webapp.management.BackupController.getBackupState(BackupController.java:56) ~[operate-webapp-8.6.9.jar:8.6.9]
...
Caused by: java.lang.IllegalArgumentException: No enum constant io.camunda.operate.store.opensearch.response.SnapshotState.IN_PROGRESS
	at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at io.camunda.operate.store.opensearch.response.SnapshotState.valueOf(SnapshotState.java:10) ~[operate-schema-8.6.9.jar:8.6.9]
	at io.camunda.operate.store.opensearch.client.sync.OpenSearchSnapshotOperations.mapToSnapshotInfo(OpenSearchSnapshotOperations.java:82) ~[operate-schema-8.6.9.jar:8.6.9]
```

### Expected behavior

`IN_PROGRESS` state deserialized with no errors

### Environment

SM

### Version

- Component Version: 8.6.9

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

Replacing STARTED by IN_PROGRESS snapshot status
There is not such status STARTED according to Opensearch docs https://docs.opensearch.org/docs/latest/api-reference/snapshots/get-snapshot-status/#snapshot-states

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #33516

### CODE REVIEW

**Comment by houssain-barouni** [comment]
Hi @entangled90 , I have noticed that you added IN_PROGRESS status in https://github.com/camunda/camunda/pull/27029
Can you confirm it should actually replace the STARTED status that does not exist in Opensearch docs?

**Comment by entangled90** [comment]
I assume so :+1: . I noticed the mismatch when running the IT with the real opensearch DB running.

File: operate/webapp/src/test/java/io/camunda/operate/webapp/opensearch/backup/OpensearchBackupRepositoryTest.java [hunk 1]
```diff
@@ -93,7 +93,7 @@ void getBackupsReturnsNotEmptyListOfBackups() {
         List.of(
             new OpenSearchSnapshotInfo()
                 .setSnapshot("test-snapshot")
-                .setState(SnapshotState.STARTED)
+                .setState(SnapshotState.IN_PROGRESS)
                 .setStartTimeInMillis(23L));
     final var response = new OpenSearchGetSnapshotResponse(snapshotInfos);
```
Comment (grlimacan) [inline operate/webapp/src/test/java/io/camunda/operate/webapp/opensearch/backup/OpensearchBackupRepositoryTest.java:98]: Line 115 below still needs changing

**Review by grlimacan — APPROVED** [review]
LGTM! There's still one test that needs changing. Pre-approving

File: operate/webapp/src/test/java/io/camunda/operate/webapp/opensearch/backup/OpensearchBackupRepositoryTest.java (hunk 1 above)
Comment (houssain-barouni) [reply operate/webapp/src/test/java/io/camunda/operate/webapp/opensearch/backup/OpensearchBackupRepositoryTest.java:98]: Thanks!

**Review by buccarel — APPROVED** [review]
