### PR TITLE
fix: Incorrect Not Found Message in Get User API

### LINKED ISSUE #37741: Incorrect “User Not Found” Message in Get User API
### 

### 

### 

### 

### Description

The [Get User](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/get-user/) endpoint returns an incorrect error message when a user is not found. The message currently refers to id, but the lookup is actually performed by username.

```
{
    "type": "about:blank",
    "title": "NOT_FOUND",
    "status": 404,
    "detail": "User with id 'user123' not found",
    "instance": "/v2/users/user"
}
```

### Steps to reproduce

1. Call the Get User endpoint with a non-existent username (e.g., invalidUser).
2. Observe the error response.

### Current behavior

The error message incorrectly refers to id: `User with id '1' not found`

### Expected behavior

The error message should correctly reflect the lookup key: `User with username '1' not found`

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by kristinkomschow**
## Description

- added custom message for username search errors to refer to the username as "username" instead of "id"
- improved error message test coverage

Even though we internally treat the username as an id, this is not clear from the naming.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes https://github.com/camunda/camunda/issues/37741

### CODE REVIEW

**Comment by kristinkomschow** [comment]
I'll backport this to stable/8.8

File: search/search-client/src/main/java/io/camunda/search/clients/CamundaSearchClients.java [hunk 1]
```diff
@@ -322,7 +322,7 @@ public SearchQueryResult<GroupMemberEntity> searchGroupMembers(final GroupQuery
   @Override
   public UserEntity getUser(final String id) {
```
Comment (danielkelemen) [inline search/search-client/src/main/java/io/camunda/search/clients/CamundaSearchClients.java]: 🔧 The parameter could be also changed to username to make it more consistent:

```suggestion
  public UserEntity getUser(final String username) {
```

**Review by danielkelemen — APPROVED** [review]
👍 Looks good! I left one low prio suggestion.

**Comment by kristinkomschow** [comment]
I renamed the method parameter as suggested in the review and squashed it into the fix.

@danielkelemen Thanks for the quick review!
