### PR TITLE
fix: force flush moved snapshots

### LINKED ISSUE #28407: Restoring from snapshot is not guaranteed to be durable
`FileBasedSnapshotStoreImpl#restore` moves and copies files via `Files#move` and `Files#copy` but does not flush the target files, it only flushes the parent directory. As a result, a restored snapshot is not guaranteed to be properly persisted to disk.

The impact and severity is probably low, because opening of a corrupted snapshot _should_ fail various checksum tests. Still, it's much safer to ensure durability by flushing restored snapshot files immediately.

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

- Flush snapshot files after moving
- Instead of copying `checksum` file move it as well
## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #28407

### CODE REVIEW

File: zeebe/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStoreImpl.java [hunk 1]
```diff
@@ -667,11 +667,12 @@ public void restore(final String snapshotId, final Map<String, Path> snapshotFil
     }
   }
 
-  private void copyNamedFileToDirectory(
+  private void moveNamedFileToDirectory(
       final String name, final Path source, final Path targetDirectory) {
     final var targetFilePath = targetDirectory.resolve(name);
     try {
       Files.move(source, targetFilePath);
```
Comment (entangled90) [inline zeebe/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStoreImpl.java:674]: :wrench: I would add `ATOMIC_MOVE` as copy option. If that's not supported (a `AtomicMoveNotSupportedException` is raised) then we can fallback to your proposal. 
If the file systems are the same, the move should be atomic?

File: zeebe/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStoreImpl.java [hunk 2]
```diff
@@ -667,11 +669,16 @@ public void restore(final String snapshotId, final Map<String, Path> snapshotFil
...
       final String name, final Path source, final Path targetDirectory) {
     final var targetFilePath = targetDirectory.resolve(name);
     try {
-      Files.move(source, targetFilePath);
+      try {
+        Files.move(source, targetFilePath, ATOMIC_MOVE);
+      } catch (final AtomicMoveNotSupportedException e) {
+        Files.move(source, targetFilePath);
+      }
+      FileUtil.flush(targetFilePath);
```
Comment (entangled90) [inline zeebe/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStoreImpl.java:681]: :wrench: I think flush is needed only if the atomic move failed

**Review by entangled90 — APPROVED** [review]
:rocket:
