### PR TITLE
fix: internal server error after user task migration

### LINKED ISSUE #44911: 500 (Internal Server Error) is returned in Tasklist after user migrates from a Job Worker task with an embedded form to a Camunda task without a form
### 

### 

### 

### 

### Description

User tasks disappear from Tasklist and 500 is returned in the logs after user migrates from a process with Job worker task with an embedded form to another process with Camunda user task without a form

### Steps to reproduce

1. Run and Deploy a process with Job worker user task with embedded form
2. Duplicate the process
3. Change implementation in the user task to Camunda user task and <none> Form type
4. Run and deploy the process
5. Navigate to Operate and migrate process from step 1 to process from step 3 
6. Navigate to Tasklist and check the tasks

### Current behavior

After the migration the tasks disappered and 500 Internal error is displayed in the logs
```
{
    "type": "about:blank",
    "title": "java.lang.NumberFormatException",
    "status": 500,
    "detail": "Unexpected error occurred during the request processing: For input string: \"camunda-forms:bpmn:UserTaskForm_21b4rq4\"",
    "instance": "/05c21b1b-7338-4c23-998b-da1b27aaf0d5/v2/user-tasks/search"
}
```

https://github.com/user-attachments/assets/4268513a-60ad-4f33-bd32-c31951e81ae2

### Expected behavior

User should be able to migrate user task with embedded form to camunda user task without a form **or** informative error message should be returned

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS

### Version

- Component Version: 8.9.0 -SNAPSHOT

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by kristinkomschow**
## Description

Fix error in tasklist after user task migration.

V2 API requires the `formKey` to be a long, but for job worker user tasks the `formKey` is a String. When the new user task is created, it did not update the `formKey` value in the secondary storage because the `updateField` only got set when `formKey` is not `null`, so the old job-worker string remained in secondary storage which then caused a long parsing error in the controller. We need to update the `formKey` to null if it is set to null when the entity is newly created.

The external form reference was also missing from the update fields.

I refactored the acceptance tests to be in an own class and made them parameterized tests. I also added a test case for embedded form -> external form reference. This will make it easier to add more test cases with https://github.com/camunda/camunda/issues/44635

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes)).

## Related issues

relates to https://github.com/camunda/camunda/issues/44911

### CODE REVIEW

File: qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+        deploymentEvent.getProcesses().stream()
+            .filter(p -> p.getBpmnProcessId().equals(TO_PROCESS_ID))
+            .findFirst()
+            .get()
+            .getProcessDefinitionKey();
+    final var processInstanceKey =
+        startProcessInstance(
+                client,
+                FROM_PROCESS_ID,
+                Map.of("varAssignee", "demo", "varPriority", 20)) // TODO variables?
```
[the remark this answers is not in the document]
Comment (kristinkomschow) [reply qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java]: I'll remove the TODO with whatever other change requests there may be. I'll turn these into variables if necessary when adding more test cases.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java [hunk 2]
```diff
@@ -56,7 +56,7 @@ public class UserTaskHandler implements ExportHandler<TaskEntity, UserTaskRecord
           UserTaskIntent.COMPLETION_DENIED);
   private static final String UNMAPPED_USER_TASK_ATTRIBUTE_WARNING =
       "Attribute update not mapped while importing ZEEBE_USER_TASKS: {}";
-
+  private static final String RECREATE_WITH_NULL = "NULL";
```
Comment (danielkelemen) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java]: 🙃 I feel the variable name describing the action not the value a bit odd.

```suggestion
  private static final String FORM_KEY_NULL = "NULL";
```

File: qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+            .send()
+            .join()
+            .singleItem();
+    assertThat(migratedTask.getAssignee()).isEqualTo(expectedTask.assignee);
+    assertThat(migratedTask.getCandidateGroups()).isEqualTo(List.of("g1", "g2"));
+    assertThat(migratedTask.getCandidateUsers()).isEqualTo(List.of("u1", "u2"));
+    assertThat(migratedTask.getDueDate()).isEqualTo(EXAMPLE_DUE_DATE);
+    assertThat(migratedTask.getFollowUpDate()).isEqualTo(EXAMPLE_FOLLOW_UP_DATE);
+    assertThat(migratedTask.getPriority()).isEqualTo(expectedTask.priority);
+    assertThat(migratedTask.getFormKey()).isEqualTo(expectedTask.formKey);
```
Comment (danielkelemen) [inline qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java:162]: 🔧 Could we have a test for the use-case where `formKey` gets nulled after migration?

**Review by danielkelemen — APPROVED** [review]
Looks good, left 2 comments but pre-approving already.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java (hunk 2 above)
Comment (kristinkomschow) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java]: The thought here was to make it a flag for values that need to be overwritten with null since we usually only check if we have a value before adding something to the updateFields and we can't always overwrite the value if it's "null" in the entity because that is the default for unchanged entity values.
I did change it to the suggestion since we have no other cases of this as of now.

File: qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java (hunk 3 above)
Comment (kristinkomschow) [reply qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java:162]: The formKey gets nulled in the case the jobworker usertask has an embedded or external form, so this is implicit in the "embedded form to external form reference" test case. However, I noticed that in the test case the flush may only happen after the migration, so I now added a verification to wait for the original job worker task to show up in secondary storage before the migration.

**Comment by kristinkomschow** [comment]
I'll squash the last commit into the previous one after the new review before merging.

File: qa/util/src/main/java/io/camunda/qa/util/cluster/TestRestTasklistClient.java [hunk 4]
```diff
@@ -8,8 +8,11 @@
 package io.camunda.qa.util.cluster;
 
 import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
+import com.fasterxml.jackson.core.JsonProcessingException;
 import com.fasterxml.jackson.databind.ObjectMapper;
+import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
 import io.camunda.client.CredentialsProvider;
+import io.camunda.tasklist.webapp.api.rest.v1.entities.TaskSearchResponse;
```
Comment (konstantinos-mylosis) [inline qa/util/src/main/java/io/camunda/qa/util/cluster/TestRestTasklistClient.java:15]: This dependency is necessary:
```
<dependency>
  <groupId>io.camunda</groupId>
  <artifactId>tasklist-webapp</artifactId>
</dependency>
```

I also see `operate-webapp` in `qa/util.pom` so that shouldn't be an issue adding `tasklist-webapp`

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java [hunk 5]
```diff
@@ -200,12 +200,20 @@ private Map<String, Object> getUpdatedFields(final TaskEntity entity) {
...
+      }
+    }
+    if (entity.getFormKey() != null) {
+      if (entity.getFormKey().equals(RECREATE_WITH_NULL)) {
+        entity.setFormKey(null);
+        updateFields.put(TaskTemplate.FORM_KEY, null);
+      } else {
+        updateFields.put(TaskTemplate.FORM_KEY, entity.getFormKey());
       }
     }
```
[the remark this answers is not in the document]
Comment (konstantinos-mylosis) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java]: It would be nice to move this logic to `UserTaskHandler#flush`, in a new method, e.g. `updateFormKey(updateFields, entity)` , since it updates the entity and it is currently hidden in a get method.

I would suggest adding Javadoc here, as it could be helpful for future reference. It may also address common questions about the rationale upfront, reducing the need for follow-up clarification.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java [hunk 6]
```diff
@@ -230,7 +238,8 @@ private Map<String, Object> getUpdatedFields(final TaskEntity entity) {
 
   private void createTaskEntity(final TaskEntity entity, final Record<UserTaskRecordValue> record) {
     final var taskValue = record.getValue();
-    final var formKey = taskValue.getFormKey() > 0 ? String.valueOf(taskValue.getFormKey()) : null;
+    final var formKey =
+        taskValue.getFormKey() > 0 ? String.valueOf(taskValue.getFormKey()) : FORM_KEY_NULL;
```
Comment (konstantinos-mylosis) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java]: Consider adding a small Javadoc or inline comment here to explain why `FORM_KEY_NULL` was created, or to reference the new method introduced in `updateFormKey` (or its final name).

**Review by konstantinos-mylosis — CHANGES_REQUESTED** [review]

File: qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java [hunk 7]
```diff
@@ -0,0 +1,195 @@
...
+        Arguments.of(from1, to1, new ExpectedUserTask("demo", 40, null, null)),
+        Arguments.of(
+            fromWithoutAssigneeAndPriority,
+            toWithoutAssigneeAndPriority,
+            new ExpectedUserTask(null, 50, null, null)),
+        Arguments.of(
+            fromEmbeddedForm,
+            toExternalForm,
+            new ExpectedUserTask("demo", 50, "localhost:8080//example.form", null)));
+  }
```
[the remark this answers is not in the document]
Comment (kristinkomschow) [reply qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java:249]: The bug was caused by the problem with formKeys not being correctly set to null. The test case that migrates to an external form covers this and we do not want to write full integration tests for every user task form type migration combination.

**Comment by kristinkomschow** [comment]
I changed the implementation for the user task handlers with the last commit.
Background: I had a talk with @konstantinos-mylosis yesterday that made it obvious that the implementation that used the update mapping for overwriting values was hard to follow and in the long term very likely a pain to maintain. I saw that we have handlers that use an `addWithRouting` method that would overwrite existing documents and asked for some feedback from data-layer ([slack link](https://camunda.slack.com/archives/C08MRKHJ0CD/p1770795357025529)) on an approach where we use a separate handler for CREATING records that use this method on flush. This way we completely overwrite an old record.

This approach seems way less hacky and is very likely more robust, because:
- all fields get reliably overwritten, so we shouldn't run into any more inconsistencies
- it's more readable because we don't need to check almost every field for updates in the original handler
- I still had some concerns that updates don't get correctly written if the flush happens on any other state other than creating/created, which definitely can't happen with this implementation

Any thoughts or concerns for this approach? @danielkelemen @konstantinos-mylosis

**Comment by konstantinos-mylosis** [comment]
@kristinkomschow 
I like this approach 👍 
It feels much cleaner, easier to read, and more maintainable.

I’d also be interested to see whether the discussion [here](https://camunda.slack.com/archives/C08MRKHJ0CD/p1770795357025529) leads to a different outcome.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java [hunk 8]
```diff
@@ -56,7 +57,7 @@ public class UserTaskHandler implements ExportHandler<TaskEntity, UserTaskRecord
           UserTaskIntent.COMPLETION_DENIED);
   private static final String UNMAPPED_USER_TASK_ATTRIBUTE_WARNING =
       "Attribute update not mapped while importing ZEEBE_USER_TASKS: {}";
-
+  private static final String FORM_KEY_NULL = "NULL";
   private final String indexName;
   private final ExporterEntityCache<String, CachedFormEntity> formCache;
```
Comment (danielkelemen) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java]: 🔧 `FORM_KEY_NULL` and `formCache` are not used anymore.

File: qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java [hunk 9]
```diff
@@ -0,0 +1,276 @@
...
+    assertThat(migratedTask.getCandidateUsers()).isEqualTo(List.of("u1", "u2"));
+    assertThat(migratedTask.getDueDate()).isEqualTo(EXAMPLE_DUE_DATE);
+    assertThat(migratedTask.getFollowUpDate()).isEqualTo(EXAMPLE_FOLLOW_UP_DATE);
+    assertThat(migratedTask.getPriority()).isEqualTo(expectedTask.priority);
+    assertThat(migratedTask.getFormKey()).isEqualTo(expectedTask.formKey);
+    assertThat(migratedTask.getExternalFormReference())
+        .isEqualTo(expectedTask.externalFormReference);
+  }
+
+  static Stream<Arguments> migrationTestCases() {
```
Comment (danielkelemen) [inline qa/acceptance-tests/src/test/java/io/camunda/it/orchestration/UserTaskProcessInstanceMigrationIT.java:167]: 👍 Nice

**Review by danielkelemen — APPROVED** [review]
@kristinkomschow, I like this approach, it is definitely cleaner and in the CREATING we can just `addWithRouting`.

I had to double check how 2 exporters work with the same entity and how the flush order is. Sharing here just in case I missed something:
1. Invoke handlers: https://github.com/camunda/camunda/blob/6a21e11c531af364edb5fa23a905933a52cb2928/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ExporterBatchWriter.java#L56-L62
2. Put key-handler and entity pairs into `cachedEntitiesToFlush`:
   - 🔧 BTW this has just changed, you could rebase it to double check
   - Stored in a LinkedHashMap, so order by keys added.
   https://github.com/camunda/camunda/blob/6a21e11c531af364edb5fa23a905933a52cb2928/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ExporterBatchWriter.java#L77-L82 
3. Flush retrieves keys in the order of inserts and flushes them. So first `UserTaskCreatingHandler` and then `UserTaskHandler`.

**Comment by kristinkomschow** [comment]
fixed the last small comments, rebased on main and squashed everything into sensible commits to have a clean history

**Comment by kristinkomschow** [comment]
@konstantinos-mylosis I need approval for the change requests to merge this. I don't think I'm getting more input from data layer and it seems like the cleanest option anyway 😄

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskCreatingHandler.java [hunk 10]
```diff
@@ -0,0 +1,162 @@
...
+  @Override
+  public void updateEntity(final Record<UserTaskRecordValue> record, final TaskEntity entity) {
+    entity.setProcessInstanceId(String.valueOf(record.getValue().getProcessInstanceKey()));
+    entity.setAction(record.getValue().getAction());
+    entity.setKey(record.getKey());
+    createTaskEntity(entity, record);
+    final TaskJoinRelationship joinRelation = new TaskJoinRelationship();
+    joinRelation.setName(TaskJoinRelationshipType.TASK.getType());
+    joinRelation.setParent(Long.parseLong(entity.getProcessInstanceId()));
+    entity.setJoin(joinRelation);
```
Comment (konstantinos-mylosis) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskCreatingHandler.java:90]: This can slightly be refactored since now `UserTaskIntent.CREATING` moved away from the other handler, but it's minor.

**Review by konstantinos-mylosis — APPROVED** [review]
LGTM

I had almost identical comments with Daniel before.
Nice 👍 😃

Minor comment, that you can as well skip

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskCreatingHandler.java (hunk 10 above)
Comment (kristinkomschow) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskCreatingHandler.java:90]: I'll leave this in for now so we can finally get this merged and will refactor it with the last open PIM task (https://github.com/camunda/camunda/issues/44635)

**Comment by kristinkomschow** [comment]
I did some smoke-testing with different form combinations (including assigning and completing after) and it all looked good, so I'm gonna merge this. Thanks everyone for the input!
