### PR TITLE
fix(engine): check element instance before trigger timer

### LINKED ISSUE #4663: NullPointerException in EventHandle.java
**Describe the bug**

This occurred in production 266 times in the last week - a NullPointerException is thrown in `io.zeebe.engine.processor.workflow.EventHandle` on line 42. You can see the stack trace below. Here is the offending block of code:

https://github.com/zeebe-io/zeebe/blob/29a31b6dab5acd28631598a0529c902921c9f30e/engine/src/main/java/io/zeebe/engine/processor/workflow/EventHandle.java#L39-L42

As this is an unexpected exception, I think it will blacklist the workflow instance, which is pretty bad, meaning that instance can never recover.

**To Reproduce**

As another user triggered this, I can't really say how to reproduce it unfortunately.

**Expected behavior**

NullPointerException are very rarely expected :slightly_smiling_face: 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: null
	at io.zeebe.engine.processor.workflow.EventHandle.triggerEvent(EventHandle.java:42) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.workflow.timer.TriggerTimerProcessor.triggerEvent(TriggerTimerProcessor.java:116) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.workflow.timer.TriggerTimerProcessor.processTimerTrigger(TriggerTimerProcessor.java:88) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.workflow.timer.TriggerTimerProcessor.processRecord(TriggerTimerProcessor.java:73) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:28) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:48) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.lambda$processInTransaction$2(ProcessingStateMachine.java:265) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:256) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:225) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:201) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.engine.processor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:192) ~[zeebe-workflow-engine-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.2.jar:0.23.2]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.2.jar:0.23.2]
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.23.2
 - Configuration: can't tell yet the cluster type, we'll have to look at logs

### PR DESCRIPTION
**Pull request by saig0**
## Description

* trigger timer only if the related element instance is still activated
* remove element instance on terminated
* replace old stream processor test with new record batch style

## Related issues

closes #4663 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by saig0** [comment]
Thanks to @Zelldon, I was able to replace one of the old stream processor tests :balloon: 
The new style is so much better and close to the other tests.

File: engine/src/test/java/io/zeebe/engine/processor/workflow/timer/ConcurrentTimerEventTest.java [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+        RecordingExporter.timerRecords(TimerIntent.TRIGGER)
+            .onlyCommandRejections()
+            .withWorkflowInstanceKey(workflowInstanceKey)
+            .getFirst();
+
+    Assertions.assertThat(rejection).hasRejectionType(RejectionType.NOT_FOUND);
+  }
+
+  @Test
+  public void shouldTriggerCommandIfTimerIsTriggered() {
```
Comment (korthout) [inline engine/src/test/java/io/zeebe/engine/processor/workflow/timer/ConcurrentTimerEventTest.java:83]:
```suggestion
  public void shouldRejectTriggerCommandIfTimerIsTriggered() {
```

File: engine/src/test/java/io/zeebe/engine/processor/workflow/timer/ConcurrentTimerEventTest.java [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+            .workflowInstance(WorkflowInstanceIntent.ELEMENT_TERMINATING, eventActivated.getValue())
+            .key(eventActivated.getKey())
+            .causedBy(1),
+        RecordToWrite.event()
+            .workflowInstance(WorkflowInstanceIntent.ELEMENT_TERMINATED, eventActivated.getValue())
+            .key(eventActivated.getKey())
+            .causedBy(2),
+        RecordToWrite.command()
+            .timer(TimerIntent.TRIGGER, timerCreated.getValue())
+            .key(timerCreated.getKey()));
```
Comment (korthout) [inline engine/src/test/java/io/zeebe/engine/processor/workflow/timer/ConcurrentTimerEventTest.java:161]: I'm not sure I like this test. It looks like the test binds too much to the implementation. Instead of writing commands and events, I feel it would be better to only write commands and wait for something to have occurred before writing another command. For example, send the cancel command for the process, that in turn terminates the process incl the timer intermediate catch event. We wait for that to happen and then send a trigger timer command.

**Review by korthout — CHANGES_REQUESTED** [review]
Good changes, just a remark about one of the tests.

File: engine/src/test/java/io/zeebe/engine/processor/workflow/timer/ConcurrentTimerEventTest.java (hunk 2 above)
Comment (saig0) [reply engine/src/test/java/io/zeebe/engine/processor/workflow/timer/ConcurrentTimerEventTest.java:161]: I see your point. This type of tests are more coupled to the implementation (i.e. the records on the stream).  

However, I see no other way to test this. We have no way to pause the stream processing and inject commands.

If I would write the test like this:
* wait until the timer event is activated
* write the cancel workflow instance command
* wait until the workflow instance is terminated
* write the trigger timer command

then it wouldn't test the behavior because the timer is canceled when the timer event is terminated. The command would be rejected but it is a different situation. 

Let's discuss it f2f if you want to challenge the approach or have more questions :)

**Review by korthout — APPROVED** [review]

File: engine/src/test/java/io/zeebe/engine/processor/workflow/timer/ConcurrentTimerEventTest.java (hunk 2 above)
Comment (korthout) [reply engine/src/test/java/io/zeebe/engine/processor/workflow/timer/ConcurrentTimerEventTest.java:161]: As discussed, this approach was chosen after pausing the stream processing became too complex in other tests.

**Comment by saig0** [comment]
bors retry
