### PR TITLE
Ensure one principle identifier is set

### LINKED ISSUE #37473: A request matching both the configured user and the client claim should be treated as a client request
### 

### 

### 

### 

### Description

* Scenario: OIDC with a configured username and client id claim
* At the moment, we extract both a username and a client id from one access token: The `CamundaAuthenticationConverter` implementations ([example authorization code flow token](https://github.com/camunda/camunda/blob/3166803b9d8066d16a3d5da5f44252d8412cc96d/authentication/src/main/java/io/camunda/authentication/converter/OidcUserAuthenticationConverter.java#L60)) delegate to `TokenClaimsConverter` ([reference](https://github.com/camunda/camunda/blob/3166803b9d8066d16a3d5da5f44252d8412cc96d/authentication/src/main/java/io/camunda/authentication/converter/TokenClaimsConverter.java#L55-L61))
* We use such `CamundaAuthentication` objects inconsistently:
  * [Workflow engine AuthorizationCheckBehavior prefers with user name over client id](https://github.com/camunda/camunda/blob/3166803b9d8066d16a3d5da5f44252d8412cc96d/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java#L102-L118)
  * [Search layer uses both](https://github.com/camunda/camunda/blob/3166803b9d8066d16a3d5da5f44252d8412cc96d/security/security-services/src/main/java/io/camunda/security/impl/AuthorizationChecker.java#L168-L173)
* Furthermore, [we mix group and role memberships for both the user and client](https://github.com/camunda/camunda/blob/24c45ad6cec32c7aec736ef4c3467eb6fd8faedc/authentication/src/main/java/io/camunda/authentication/service/DefaultMembershipService.java#L103) when authenticating the user. For the workflow engine, which decides to treat the request as coming from a user, this leads to a bug: Authorizations are applied only as if a user accesses the system, but groups are mixed.
* Originally, [we had decided to prefer a client id over a username](https://camunda.slack.com/archives/C06UYJMMETZ/p1746529676126149?thread_ts=1746173814.015579&amp;cid=C06UYJMMETZ), since we expect client requests to carry additional claims that user access tokens do not. However, this was not implemented so far.
* Besides this inconsistency, accepting `CamundaAuthentication` objects that carry both a username and a client id make it hard to attribute a request to one party. It may be challenging to build features in the future that require this (e.g. an audit log)

### Steps to reproduce

1. Configure the Orchestration Cluster with OIDC
2. Set the username and client ID claim configuration so that the user's access token matches both
3. Configure an authorization that grants the user's client id permission to start a process instance
4. Send a request to start a process instance

### Current behavior

* The request is rejected due to missing permissions (as the workflow engine treats the request as coming from a user)

### Expected behavior

* The request is successful

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

* See description

### Solution ideas

* On the level of the `CamundaAuthenticationProvider`:
  * Validate that a `CamundaAuthentication` object can only have one, a username or a client id; add this constraint to the definition of the interface
    * Introducing this constraint creates generally a stronger contract that other code can rely on and fits more naturally the mental model of engineers (a request is only made by one party)
    * Note that we still have to allow for neither a username or a client id being present (compare `CamundaAuthentication#anonymous` and its usages)
  * We could also do this in the builder for `CamundaAuthentication` objects, however as `CamundaAuthentication` is public, code is not forced to use the builder
* In `TokenClaimsConverter#convert` prefer the client id (if present) over the username and set only one on the `CamundaAuthentication` object and in its `claims` property
* Optional: we could add a boolean configuration flag that allows users to decide which claim should take preference; reduces the risk that our assumption about the expectation is wrong; that said, we can still add it at any future point
* Merge this change carefully, e.g. partner with a QA engineer to ensure that:
  * Access in SaaS clusters doens't break (both users and clients work as before)
  * QA test suites do not break (e.g. if they configure the claims so that an access was previously a user that is now a client)
  * Validate with Entra and Keycloak that a separate client id claim can be meaningfully used (i.e. that not all users become clients)

### Dev -> QA handover

- Resources: There is a branch [here](https://github.com/camunda/camunda/tree/ensure-one-principle-identifier-is-set)
- Versions to validate: 8.8
- Release version (in which version this feature will be released): 8.8
- Testing context:
  - The core of this issue is relating to a the claim configured as the username claim `CAMUNDA_SECURITY_AUTHENTICATION_OIDC_USERNAMECLAIM` being present on both a user token, and a M2M token
  - A real world example of this could be the `USERNAMECLAIM` being set to `sub` (`sub` is a common claim found on all tokens), and the `CAMUNDA_SECURITY_AUTHENTICATION_OIDC_CLIENTIDCLAIM` set to something specific to a M2M token i.e. `client_id`
  - In the overlapping instance, the M2M token would be detected as a user token due to the sub claim being present on both tokens, and we would (prior to the bug fix) prefer the username
  - The resolution here is to change the preference such that the `CLIENTIDCLAIM` is preferred over the `USERNAMECLAIM`

To test this bug I would recommend a setup where:
1. There is a claim configuration that creates the overlap (as above)
2. There is an authorization for the client ID of your M2M client
3. There is no authorization for the matching username claim
4. You enable authorizations in your cluster
5. You try to deploy using the M2M credentials

Validation of this bug would be that prior to the fix, step 5 would receive an unauthorized error (as we would search for the username claim value against authorizations. Post bug fix the correct authorizations would apply and the M2M client could deploy a model.

Another instance where this bug could be seen would be on search related endpoints, in this test scenario, the M2M client would have incorrect authorizations applied such that more or less data is returned, post fix, the correct authorizations are applied.

### Links

* Discussion where this was raised: https://camunda.slack.com/archives/C06UYJMMETZ/p1756735475364219

### PR DESCRIPTION
**Pull request by Ben-Sheppard**
## Description

As per the parent issue, this PR achieves two core tasks:
1. Implement a defensive constraint to ensure that only one of the principle identifiers is set on the `CamundaAuthentication` object (describing this in javadocs too so calling code/implementations from a plugin system can abide by a known construct in our system)
2. In places where we detect the principles prefer the client ID over username

I have for now decided against including configuration to allow selection of the preference because, as mentioned by @ThorbenLindhauer , this can always be added at a later date.

## Related issues

closes #37473

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java [hunk 1]
```diff
@@ -95,26 +95,27 @@ public Either<Rejection, Void> isAuthorized(final AuthorizationRequest request)
       return Either.right(null);
     }
 
-    final var username = getUsername(request);
     final var clientId = getClientId(request);
+    final var username = getUsername(request);
```
Comment (bmudric) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java]: Do we also want to throw here if both are present?
From Zeebe POV this is again a kind of "user input", no?

File: authentication/src/main/java/io/camunda/authentication/converter/TokenClaimsConverter.java [hunk 2]
```diff
@@ -52,15 +52,13 @@ public CamundaAuthentication convert(final Map<String, Object> tokenClaims) {
...
 
     if (clientId != null) {
       authenticatedClaims.put(AUTHORIZED_CLIENT_ID, clientId);
+      return membershipService.resolveMemberships(tokenClaims, authenticatedClaims, null, clientId);
     }
 
-    return membershipService.resolveMemberships(
-        tokenClaims, authenticatedClaims, username, clientId);
+    authenticatedClaims.put(AUTHORIZED_USERNAME, username);
+    return membershipService.resolveMemberships(tokenClaims, authenticatedClaims, username, null);
```
Comment (bmudric) [inline authentication/src/main/java/io/camunda/authentication/converter/TokenClaimsConverter.java]: WDYT about throwing the `OAuth2AuthenticationException` at the beginning of this method if both `clientId` and `username` are set? I assume this is a kind of entry point where this dual possibility rears its head.

The additional benefit of having it "at the beginning" is that you can then refactor and simplify `io.camunda.authentication.service.MembershipService#resolveMemberships` to accept only one `String principal` instead of both `clientId` and `username`, and drop the additional check logic in that method. Also, it prevents any accidents by callers not reading the Javadoc.

Comment (ThorbenLindhauer) [reply authentication/src/main/java/io/camunda/authentication/converter/TokenClaimsConverter.java]: > and drop the additional check logic in that method

Just keep in mind that users and clients have different memberships, i.e. we still need to know there what kind the principal is.

edit: maybe that's how you mean it, just want to make sure :)

Comment (bmudric) [reply authentication/src/main/java/io/camunda/authentication/converter/TokenClaimsConverter.java]: My only point was not to duplicate logic, or in other words not to expect other components to implicitly "understand" hidden semantics and "remember" to do checks that could have been resolved at the root. 🙂 

If we still need to pass the information downstream regarding the kind of principal (which is fine of course), I'd suggest adding a parameter for that explicitly.
So for example, instead of:
```java
String clientId;
String username;
// downstream code needs to know how to interpret the null/non-null relationship of the above
```
we could have:
```java
enum PrincipalType {
  USER, CLIENT, ANONYMOUS // did not think the last one through yet
}
String principal;
PrincipalType type;
// downstream code has all the semantics explicitly served and requires no hidden knowledge to use the above
```

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java (hunk 1 above)
Comment (Ben-Sheppard) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java]: By the time we get to this point we've already unpacked the authn from the request, but the throwing in the other classes largely is because these are public facing classes that people can use via the plugin system so if someone else wants to create a CamundaAuthentication object we thrown when its not valid (both supplied).

After this, we have to detect for either or because of treating the ids differently in code so we switch to prefer the clientId over username.

Happy to explain more via a call if its easier

**Review by bmudric — APPROVED** [review]

**Comment by Ben-Sheppard** [comment]
FYI @sergiizakharov is doing some pre merge testing as per the parent issue. I've added the hold label for now

**Review by bmudric — APPROVED** [review]
