### PR TITLE
fix: check state version for compatibility

### LINKED ISSUE #15885: Handle snapshots correctly during a rolling update
During a rolling update, snapshots can be replicated.

1. Old broker sends a snapshot to a new broker
2. New broker sends an old snapshot to an old broker
3. New broker sends a new snapshot to an old broker

Because our runtime state and our snapshots are not versioned in any way, we currently accept all of the above scenarios. This can lead to issues, especially in case 3 where an old broker suddenly has to operate on new runtime state that is possibly incompatible.

In the past, this has caused issues such as https://github.com/camunda/zeebe/issues/14406.

One idea to resolve this is to version our runtime state (and thus snapshots too). When an old broker recovers from a snapshot with a newer version, it should stop processing or replaying the partition to avoid incorrect processing results or data corruption. This would also resolve https://github.com/camunda/zeebe/issues/14406 because we could use the same version to decide whether migrations need to run or not. 
```[tasklist]
### Tasks
- [x] Write broker version to state after running migrations
- [x] Don't use snapshots from newer broker versions
- [x] Don't use snapshots from too old broker versions
- [ ] https://github.com/camunda/zeebe/issues/16812
```

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This adds a check before running migrations to evaluate whether the current runtime state, as recovered from a snapshot, is compatible with the current broker version.

The rules are neatly contained in `VersionCompatibilityCheck` and are the following:
**Compatible**
1. Same version
3. Upgrade of patch version
4. Upgrade to the _next_ minor version

**Incompatible**
1. Upgrade of major version
2. Skipping a minor version
3. Downgrade of any version component
4. Migration to or from a pre-release version

**Indeterminate**
1. Previous or current version is not known
2. Previous or current version is not compliant with SemVer.

The result of this check is then handled here: https://github.com/camunda/zeebe/blob/0a2e5d533e78f7265224dc6341c09220be7750e5/engine/src/main/java/io/camunda/zeebe/engine/state/migration/DbMigratorImpl.java#L93-L112

We obviously allow compatible results but also allow indeterminate results. This is necessary to allow the upgrade from 8.4 to 8.5 where 8.4 did not yet write a version. This also allows the check to pass during development where we might not always have a SemVer compliant broker version.

If the versions are found to be incompatible, we throw an `IllegalStateException` which breaks the transition and prevents the broker from working on this partition. To recover, we require either a different snapshot or a broker version upgrade.

To implement the version comparisons, I've included a small utility for parsing versions according to [SemVer 2.0
](https://semver.org/spec/v2.0.0.html): `SemanticVersion`. This class has some overlap with the previously existing `Version` class in Atomix. I've decided to not remove this class because it is not SemVer 2.0 compliant and we rely on it for SWIM and to detect upgrades from 8.3 to 8.4. I did not want to break this in any way so I decided that another class that has slightly different (but standard compliant!) rules would be safer.

Closes https://github.com/camunda/zeebe/issues/15885

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheck.java [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+      } else if (previous.minor() - current.minor() < -1) {
+        return new Incompatible.SkippedMinorVersion(previous, current);
+      } else if (previous.minor() < current.minor()) {
+        return new Compatible.MinorUpgrade(previous, current);
+      } else if (previous.patch() < current.patch()) {
+        return new Compatible.PatchUpgrade(previous, current);
+      } else {
+        return new Compatible.PreReleaseUpgrade(previous, current);
+      }
+    }
```
Comment (oleschoenburg) [inline engine/src/main/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheck.java:79]: I'm not super happy with this because it seems brittle and somewhat hard to read. I'd be happy to hear suggestions on how this can be improved!

File: engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+  final class CompatibleResults {
+    @Test
+    void shouldAcceptPreReleaseUpgrades() {
+      assertThat(check("8.0.0-alpha1", "8.0.0-alpha2"))
+          .isInstanceOf(Compatible.PreReleaseUpgrade.class);
+      assertThat(check("8.0.0-alpha1", "8.0.0-alpha4"))
+          .isInstanceOf(Compatible.PreReleaseUpgrade.class);
+      assertThat(check("8.0.0-alpha1", "8.0.0-beta1"))
+          .isInstanceOf(Compatible.PreReleaseUpgrade.class);
+    }
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:77]: 🤔 Interesting. Currently, we don't support upgrading pre-release versions, right? Not sure whether we want to allow it here.

❌ Please add a test case that shows that you cannot upgrade from a pre-release to a regular release version, e.g. reject upgrade for `8.0.0-alpha3 -> 8.0.0`

Comment (oleschoenburg) [reply engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:77]: That's a good point that I'm not sure about :+1: 

I think it's a grey area currently because we don't guarantee that this works but probably make use of it sometimes in internal testing etc.

**Comment by oleschoenburg** [comment]
I've updated the PR to prevent leaving a pre-release version, as discussed with @korthout and @Zelldon.

I think this is ready for a review @rodrigo-lourenco-lopes.

File: engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java (hunk 2 above)
Comment (oleschoenburg) [reply engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java]: Implemented as discussed in https://github.com/camunda/zeebe/pull/16421/commits/15e68ded2da3963580fa7cbb2fdb1a420b8725da

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+      assertThat(check("8.1.0-alpha1+build123", "8.1.0-alpha1+build234"))
+          .isInstanceOf(Compatible.SameVersion.class);
+    }
+
+    @Test
+    void shouldAcceptUpgradeToPreReleaseVersions() {
+      assertThat(check("8.0.0", "8.0.1-alpha1")).isInstanceOf(Compatible.PatchUpgrade.class);
+      assertThat(check("8.0.0", "8.1.0-beta1")).isInstanceOf(Compatible.MinorUpgrade.class);
+      assertThat(check("8.1.2", "8.2.3-rc1")).isInstanceOf(Compatible.MinorUpgrade.class);
+    }
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:113]: ❌ This would be dangerous for production clusters. After any of these updates, they can no longer update to a regular release. We should reject these.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java [hunk 4]
```diff
@@ -0,0 +1,115 @@
...
+      assertThat(check("9.0.0", "8.0.0")).isInstanceOf(Incompatible.MajorDowngrade.class);
+      assertThat(check("9.0.0", "8.1.0")).isInstanceOf(Incompatible.MajorDowngrade.class);
+      assertThat(check("8.5.0", "8.4.0")).isInstanceOf(Incompatible.MinorDowngrade.class);
+      assertThat(check("8.5.0", "8.4.1")).isInstanceOf(Incompatible.MinorDowngrade.class);
+      assertThat(check("8.5.3", "8.5.2")).isInstanceOf(Incompatible.PatchDowngrade.class);
+      assertThat(check("8.5.3", "8.5.0")).isInstanceOf(Incompatible.PatchDowngrade.class);
+      assertThat(check("8.5.3", "8.5.3-alpha1"))
+          .isInstanceOf(Incompatible.PreReleaseDowngrade.class);
+      assertThat(check("8.1.0", "8.1.0-alpha1"))
+          .isInstanceOf(Incompatible.PreReleaseDowngrade.class);
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:38]: 🔧 I'd love to a rejection for PreReleaseUpgrade as well (so from alpha to regular release

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java (hunk 3 above)
Comment (oleschoenburg) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:113]: So this would extend the checks to not only forbid going away from a pre-release version but also prevent switching to a pre-release version.
I feel like both checks severely limit the usefulness of our alpha releases. For example, they make it impossible for customers to accept some risk and start using an alpha version to test out a new feature on their existing cluster.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java (hunk 4 above)
Comment (oleschoenburg) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:38]: These cases are covered as `ChangeOfPreReleaseVersion`, with matching tests.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java (hunk 3 above)
Comment (oleschoenburg) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:113]: As discussed, I'll prevent any version change **to** or **from** a pre-release version.

Comment (korthout) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:113]: Thanks @oleschoenburg for taking care of this 🙇

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+ * except in compliance with the Zeebe Community License 1.1.
+ */
+package io.camunda.zeebe.engine.state.migration;
+
+import static io.camunda.zeebe.engine.state.migration.VersionCompatibilityCheck.check;
+import static org.assertj.core.api.Assertions.assertThat;
+
+import io.camunda.zeebe.engine.state.migration.VersionCompatibilityCheck.CheckResult.Compatible;
+import io.camunda.zeebe.engine.state.migration.VersionCompatibilityCheck.CheckResult.Incompatible;
+import io.camunda.zeebe.engine.state.migration.VersionCompatibilityCheck.CheckResult.Incompatible.UseOfPreReleaseVersion;
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:15]: 🔧 For clarity, I would inline this import as you do with all other uses (I guess you may have added this import by accident)

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+      assertThat(check("8.0.0", "8.0.0-alpha1")).isInstanceOf(UseOfPreReleaseVersion.class);
+      assertThat(check("8.0.1", "8.1.0-alpha1")).isInstanceOf(UseOfPreReleaseVersion.class);
+    }
+
+    @Test
+    public void shouldRejectChangeOfPreRelease() {
+      assertThat(check("8.0.0-alpha1", "8.0.0-alpha2")).isInstanceOf(UseOfPreReleaseVersion.class);
+      assertThat(check("8.1.0-alpha1", "8.0.0-beta1")).isInstanceOf(UseOfPreReleaseVersion.class);
+      assertThat(check("8.0.1-beta1", "8.0.2-rc1")).isInstanceOf(UseOfPreReleaseVersion.class);
+    }
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:39]: 🔧 I think you can merge these with `shouldRejectChangeOfPreReleaseVersion`

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+
+    @Test
+    public void shouldRejectChangeOfPreReleaseVersion() {
+      assertThat(check("8.0.0-alpha1", "8.0.0-alpha2")).isInstanceOf(UseOfPreReleaseVersion.class);
+      assertThat(check("8.0.0-alpha1", "8.0.0-beta1")).isInstanceOf(UseOfPreReleaseVersion.class);
+      assertThat(check("8.0.0-beta1", "8.0.0-rc1")).isInstanceOf(UseOfPreReleaseVersion.class);
+      assertThat(check("8.0.0-rc1", "8.0.0")).isInstanceOf(UseOfPreReleaseVersion.class);
+      assertThat(check("8.0.0-alpha1", "8.1.0")).isInstanceOf(UseOfPreReleaseVersion.class);
+      assertThat(check("8.0.0-alpha2", "8.0.1")).isInstanceOf(UseOfPreReleaseVersion.class);
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:70]: 🔧 I think you can merge these with `shouldRejectUpgradeFromPreRelease`

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java [hunk 8]
```diff
@@ -0,0 +1,124 @@
...
+  }
+
+  @Nested
+  final class CompatibleResults {
+
+    @Test
+    void shouldAcceptPatchUpgrades() {
+      assertThat(check("8.0.0", "8.0.1")).isInstanceOf(Compatible.PatchUpgrade.class);
+      assertThat(check("8.1.4", "8.1.5")).isInstanceOf(Compatible.PatchUpgrade.class);
+    }
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:108]: 🔧 It should be fine to skip some patches, e.g. `8.1.2 -> 8.1.6`

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java [hunk 9]
```diff
@@ -0,0 +1,124 @@
...
+
+    @Test
+    void shouldAcceptMinorUpgrades() {
+      assertThat(check("8.0.0", "8.1.0")).isInstanceOf(Compatible.MinorUpgrade.class);
+      assertThat(check("8.1.3", "8.2.0")).isInstanceOf(Compatible.MinorUpgrade.class);
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/VersionCompatibilityCheckTest.java:113]: 🔧 It should be fine to skip some patches on a minor upgrade, e.g. `8.1.3 -> 8.2.2`

**Review by korthout — APPROVED** [review]
Thanks @oleschoenburg 👏 

I have a few last suggestions before merging, but nothing blocking

**Comment by oleschoenburg** [comment]
@rodrigo-lourenco-lopes Let me know whether you want to give this a review too.

**Comment by rodrigo-lourenco-lopes** [comment]
> @rodrigo-lourenco-lopes Let me know whether you want to give this a review too.

@oleschoenburg Yes I would also want to review it :) I will do it tomorrow morning, unless there is another pr waiting for this one to be merged, in this case it is fine to merge.

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
Thanks for the fix! 🚀 LGTM!
