### PR TITLE
Job Worker Name property null check

### LINKED ISSUE #14176: ActivateJobsCommandImpl throws NullPointerException when ZeebeClientProperties.getDefaultJobWorkerName is null
**Describe the bug**

The constructor of the `ActivateJobsCommandImpl` is trying to set the `workerName` during construction and expects the `config.getDefaultJobWorkerName())` to be non null. This leads to a `NullPointerException` as the underlying builder doesnt support a null value. This is an issue as clients are able to set the `workerName` using the builder pattern after constructing the command.

```
public ActivateJobsCommandImpl(
      final GatewayStub asyncStub,
      final ZeebeClientConfiguration config,
      final JsonMapper jsonMapper,
      final Predicate<Throwable> retryPredicate) {
    this.asyncStub = asyncStub;
    this.jsonMapper = jsonMapper;
    this.retryPredicate = retryPredicate;
    builder = ActivateJobsRequest.newBuilder();
    requestTimeout(config.getDefaultRequestTimeout());
    timeout(config.getDefaultJobTimeout());
    workerName(config.getDefaultJobWorkerName());
  }
```

**To Reproduce**

Create an implementation of the `ZeebeClientProperties` that returns `null` for the `getDefaultJobWorkerName`

**Expected behavior**

The builder should fallback to the default worker name only if it wasnt set by a client when constructing the final command.

**Log/Stacktrace**

```
java.lang.NullPointerException: null
	at io.camunda.zeebe.gateway.protocol.GatewayOuterClass$ActivateJobsRequest$Builder.setWorker(GatewayOuterClass.java:2169)
	at io.camunda.zeebe.client.impl.command.ActivateJobsCommandImpl.workerName(ActivateJobsCommandImpl.java:83)
	at io.camunda.zeebe.client.impl.command.ActivateJobsCommandImpl.<init>(ActivateJobsCommandImpl.java:60)
```

**Environment:**
- Zeebe Version:8.3.0-alpha4

Looks like it happens as the command builder is used instead of the previously used request builder since: https://github.com/camunda/zeebe/commit/359a402b5bbee7247749385a458c5b3f3aba7e78

### PR DESCRIPTION
**Pull request by nicpuppa**
## Related issues

closes #14176 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by berkaycanbc — APPROVED** [review]
Since we pair programmed on it, LGTM!

There is an unused import though, but should be fine after removing it.

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/command/ActivateJobsCommandImpl.java [hunk 1]
```diff
@@ -87,6 +88,11 @@ public ActivateJobsCommandStep3 timeout(final Duration timeout) {
 
   @Override
   public ActivateJobsCommandStep3 workerName(final String workerName) {
+    if (workerName == null) {
+      builder.setWorker(ZeebeClientBuilderImpl.DEFAULT_JOB_WORKER_NAME);
```
Comment (saig0) [inline clients/java/src/main/java/io/camunda/zeebe/client/impl/command/ActivateJobsCommandImpl.java:92]: :x: IMO: using "default" as the worker name is not exactly the expected behavior.

I would expect that the default job worker name from the configuration is used instead of the constant. 

Consider the following scenario:
- I set "my-worker" as the default job worker name in the config
- I pass `null` as the worker name in the builder
- Expected: the worker name is "my-worker" 
- Actual: the worker name is "default"

The behavior could be implemented by adding this null-check in the configuration builder.

**Review by saig0 — CHANGES_REQUESTED** [review]
@nicpuppa the changes look good and fix the issue. :+1: 

However, the behavior is not 100% what I would expect. Please see my comment. Let talk if you don't agree with me.

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/command/ActivateJobsCommandImpl.java (hunk 1 above)
Comment (nicpuppa) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/command/ActivateJobsCommandImpl.java:92]: In this scenario, what will happen if I don't have a configuration, or in the configuration the property is `null` ?

Comment (saig0) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/command/ActivateJobsCommandImpl.java:92]: In the configuration, the default job worker name is set to "default". 

It should not be possible to set the default job worker name in the configuration to `null`.

Comment (nicpuppa) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/command/ActivateJobsCommandImpl.java:92]: I think I understand your point, I will update the implementation 👍

**Review by saig0 — APPROVED** [review]
@nicpuppa looks good. :rocket:

**Comment by nicpuppa** [comment]
bors retry

**Comment by saig0** [comment]
bors merge
