### PR TITLE
Close logstream on transition

### LINKED ISSUE #3920: IllegalStateException: Failed to recover 'Broker-0-StreamProcessor-2'
**Describe the bug**
After redeploying the cluster, it is falling into an IllegalStateException state. The broker is still up, but rejecting all gRPC requests with `INTERNAL` error. It is happening on my beta environment, but not on alpha environment. My dev cluster was fine till few hours back, but now I am seeing same gRPC `INTERNAL` errors on dev as well. Alpha is still fine by the way.

**Expected behavior**
The cluster should accept all gRPC requests.

<details><summary>Full Stacktrace</summary>
 <p>

```
2020-02-25 13:39:27.859 [Broker-0-StreamProcessor-2] [Broker-1-zb-actors-0] DEBUG io.zeebe.logstreams - Recovering state of partition 2 from snapshot
2020-02-25 13:39:28.608 [Broker-0-StreamProcessor-2] [Broker-1-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.IllegalStateException: Expected to find event with the snapshot position 64424590432 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-2'.
	at io.zeebe.engine.processor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:209) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:121) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
2020-02-25 13:39:28.608 [Broker-1-ZeebePartition-2] [Broker-1-zb-actors-0] ERROR io.zeebe.broker.system - Unexpected error on stream processor installation!
java.lang.IllegalStateException: Expected to find event with the snapshot position 64424590432 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-2'.
	at io.zeebe.engine.processor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:209) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:121) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
2020-02-25 13:39:28.609 [Broker-1-ZeebePartition-2] [Broker-1-zb-actors-0] ERROR io.zeebe.broker.system - Failed to install leader partition 2
java.lang.IllegalStateException: Expected to find event with the snapshot position 64424590432 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-2'.
	at io.zeebe.engine.processor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:209) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:121) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
2020-02-25 13:39:28.609 [Broker-0-LogStream-2] [Broker-1-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream raft-partition-partition-2
2020-02-25 13:39:28.609 [Broker-0-StreamProcessor-2] [Broker-1-zb-actors-0] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-2.
2020-02-25 13:39:28.614 [Broker-0-StreamProcessor-3] [Broker-1-zb-actors-0] DEBUG io.zeebe.logstreams - Recovering state of partition 3 from snapshot
2020-02-25 13:39:29.185 [Broker-0-StreamProcessor-3] [Broker-1-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.IllegalStateException: Expected to find event with the snapshot position 60130044736 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-3'.
	at io.zeebe.engine.processor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:209) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:121) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
2020-02-25 13:39:29.186 [Broker-1-ZeebePartition-3] [Broker-1-zb-actors-0] ERROR io.zeebe.broker.system - Unexpected error on stream processor installation!
java.lang.IllegalStateException: Expected to find event with the snapshot position 60130044736 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-3'.
	at io.zeebe.engine.processor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:209) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:121) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
2020-02-25 13:39:29.186 [Broker-1-ZeebePartition-3] [Broker-1-zb-actors-0] ERROR io.zeebe.broker.system - Failed to install leader partition 3
java.lang.IllegalStateException: Expected to find event with the snapshot position 60130044736 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-3'.
	at io.zeebe.engine.processor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:209) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:121) ~[zeebe-workflow-engine-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
2020-02-25 13:39:29.187 [Broker-0-LogStream-3] [Broker-1-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream raft-partition-partition-3
2020-02-25 13:39:29.187 [Broker-0-StreamProcessor-3] [Broker-1-zb-actors-0] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-3.
2020-02-25 13:39:29.187 [raft-partition-partition-2-write-buffer] [Broker-1-zb-actors-0] DEBUG io.zeebe.dispatcher - Dispatcher closed
2020-02-25 13:39:29.187 [raft-partition-partition-3-write-buffer] [Broker-1-zb-actors-0] DEBUG io.zeebe.dispatcher - Dispatcher closed
2020-02-25 13:39:32.638 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received broker was removed BrokerInfo{nodeId=2, partitionsCount=3, clusterSize=3, replicationFactor=3, partitionRoles={1=FOLLOWER, 2=FOLLOWER, 3=FOLLOWER}, partitionLeaderTerms={}}.
2020-02-25 13:39:32.639 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received member removed BrokerInfo{nodeId=2, partitionsCount=3, clusterSize=3, replicationFactor=3, partitionRoles={1=FOLLOWER, 2=FOLLOWER, 3=FOLLOWER}, partitionLeaderTerms={}} 
2020-02-25 13:40:03.405 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 2, partitions {} and terms {}.
2020-02-25 13:40:03.405 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 2, partitions {} terms {}
2020-02-25 13:40:04.404 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 2, partitions {3=FOLLOWER} and terms {}.
2020-02-25 13:40:04.405 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 2, partitions {3=FOLLOWER} terms {}
2020-02-25 13:40:05.154 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 2, partitions {2=FOLLOWER, 3=FOLLOWER} and terms {}.
2020-02-25 13:40:05.155 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 2, partitions {2=FOLLOWER, 3=FOLLOWER} terms {}
2020-02-25 13:40:05.904 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 2, partitions {1=FOLLOWER, 2=FOLLOWER, 3=FOLLOWER} and terms {}.
2020-02-25 13:40:05.905 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 2, partitions {1=FOLLOWER, 2=FOLLOWER, 3=FOLLOWER} terms {}
2020-02-25 13:43:49.394 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received REACHABILITY_CHANGED for broker 0, do nothing.
2020-02-25 13:43:49.394 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received REACHABILITY_CHANGED from member 0, was not handled.
2020-02-25 13:43:59.638 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received broker was removed BrokerInfo{nodeId=0, partitionsCount=3, clusterSize=3, replicationFactor=3, partitionRoles={1=FOLLOWER, 2=FOLLOWER, 3=FOLLOWER}, partitionLeaderTerms={}}.
2020-02-25 13:43:59.639 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received member removed BrokerInfo{nodeId=0, partitionsCount=3, clusterSize=3, replicationFactor=3, partitionRoles={1=FOLLOWER, 2=FOLLOWER, 3=FOLLOWER}, partitionLeaderTerms={}} 
2020-02-25 13:44:25.471 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.system - Removing leader partition services for partition PartitionId{id=1, group=raft-partition}
2020-02-25 13:44:25.471 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-0-StreamProcessor-1
2020-02-25 13:44:25.471 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.system - Partition role transitioning from LEADER to FOLLOWER
2020-02-25 13:44:25.471 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-0-StreamProcessor-1 successfully
2020-02-25 13:44:25.471 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.system - Closing io.zeebe.broker.logstreams.LogStreamDeletionService
2020-02-25 13:44:25.472 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.logstreams.LogStreamDeletionService successfully
2020-02-25 13:44:25.473 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/usr/local/zeebe/data/raft-partition/partitions/1/runtime'.
2020-02-25 13:44:25.473 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.system - Installing follower partition service for partition PartitionId{id=1, group=raft-partition}
2020-02-25 13:44:25.479 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: [SnapshotImpl{position=68719979328, path=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/314340-19-1581687776238-68719979328}, SnapshotImpl{position=68719943328, path=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/314201-19-1581686876225-68719943328}, SnapshotImpl{position=68719907328, path=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/314064-19-1581685976198-68719907328}]
2020-02-25 13:44:25.516 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/usr/local/zeebe/data/raft-partition/partitions/1/runtime'.
2020-02-25 13:44:25.517 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Recovered state from snapshot 'SnapshotImpl{position=68719979328, path=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/314340-19-1581687776238-68719979328}'
2020-02-25 13:44:26.523 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {} and terms {}.
2020-02-25 13:44:26.523 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 0, partitions {} terms {}
2020-02-25 13:44:26.773 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {3=FOLLOWER} and terms {}.
2020-02-25 13:44:26.773 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 0, partitions {3=FOLLOWER} terms {}
2020-02-25 13:44:27.023 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {2=FOLLOWER, 3=FOLLOWER} and terms {}.
2020-02-25 13:44:27.023 [Broker-1-TopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.broker.clustering - Received metadata change for 0, partitions {2=FOLLOWER, 3=FOLLOWER} terms {}


2020-02-25 13:50:22.051 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [Broker-2-zb-actors-0] ERROR io.zeebe.gateway - Error handling gRPC request
io.grpc.StatusRuntimeException: INTERNAL: Unexpected error occurred during the request processing
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
	at io.zeebe.gateway.EndpointManager.convertThrowable(EndpointManager.java:372) ~[zeebe-gateway-0.22.1.jar:0.22.1]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.logErrorResponse(ActivateJobsHandler.java:109) ~[zeebe-gateway-0.22.1.jar:0.22.1]
	at io.zeebe.gateway.impl.job.ActivateJobsHandler.lambda$activateJobs$1(ActivateJobsHandler.java:96) ~[zeebe-gateway-0.22.1.jar:0.22.1]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequest$3(BrokerRequestManager.java:147) ~[zeebe-gateway-0.22.1.jar:0.22.1]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$5(BrokerRequestManager.java:183) ~[zeebe-gateway-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]
Caused by: java.util.concurrent.TimeoutException: Request timed out after PT15S
	at io.zeebe.transport.impl.RequestContext.timeout(RequestContext.java:109) ~[zeebe-transport-0.22.1.jar:0.22.1]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.timeoutFuture(AtomixClientTransportAdapter.java:128) ~[zeebe-transport-0.22.1.jar:0.22.1]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestWithRetry$0(AtomixClientTransportAdapter.java:60) ~[zeebe-transport-0.22.1.jar:0.22.1]
	... 6 more
2020-02-25 13:50:22.052 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [Broker-2-zb-actors-0] WARN  io.zeebe.gateway - Failed to activate jobs for type http from partition 2
java.util.concurrent.TimeoutException: Request timed out after PT15S
	at io.zeebe.transport.impl.RequestContext.timeout(RequestContext.java:109) ~[zeebe-transport-0.22.1.jar:0.22.1]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.timeoutFuture(AtomixClientTransportAdapter.java:128) ~[zeebe-transport-0.22.1.jar:0.22.1]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestWithRetry$0(AtomixClientTransportAdapter.java:60) ~[zeebe-transport-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.22.1.jar:0.22.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.22.1.jar:0.22.1]

```

</p>
</details>

**Environment:**
```
2020-02-25 13:53:58.999 [] [main] DEBUG io.zeebe.broker.system - Initializing configuration with base path /usr/local/zeebe
2020-02-25 13:53:59.065 [] [main] INFO  io.zeebe.broker.system - Version: 0.22.1
2020-02-25 13:53:58.459 [] [main] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network": {
    "host": "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local",
    "portOffset": 0,
    "maxMessageSize": "4M",
    "commandApi": {
      "defaultPort": 26501,
      "host": "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local",
      "port": 26501,
      "advertisedHost": "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local",
      "advertisedPort": 26501
    },
    "internalApi": {
      "defaultPort": 26502,
      "host": "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local",
      "port": 26502,
      "advertisedHost": "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local",
      "advertisedPort": 26502
    },
    "monitoringApi": {
      "defaultPort": 9600,
      "host": "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local",
      "port": 9600,
      "advertisedHost": "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local",
      "advertisedPort": 9600
    }
  },
  "cluster": {
    "initialContactPoints": [
      "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local:26502",
      "beta-zeebe-zeebe-1.zeebe.beta.svc.cluster.local:26502",
      "beta-zeebe-zeebe-2.zeebe.beta.svc.cluster.local:26502"
    ],
    "partitionIds": [
      1,
      2,
      3
    ],
    "nodeId": 0,
    "partitionsCount": 3,
    "replicationFactor": 3,
    "clusterSize": 3,
    "clusterName": "zeebe-cluster",
    "gossipFailureTimeout": 10000,
    "gossipInterval": 250,
    "gossipProbeInterval": 1000
  },
  "threads": {
    "cpuThreadCount": 1,
    "ioThreadCount": 1
  },
  "data": {
    "directories": [
      "/usr/local/zeebe/data"
    ],
    "logSegmentSize": "512M",
    "snapshotPeriod": "15m",
    "raftSegmentSize": "512M",
    "maxSnapshots": 3
  },
  "exporters": [
    {
      "id": "elasticsearch",
      "className": "io.zeebe.exporter.ElasticsearchExporter",
      "args": {
        "index": {
          "workflowInstance": true,
          "messageSubscription": true,
          "prefix": "zeebe-beta",
          "jobBatch": true,
          "error": true,
          "message": true,
          "createTemplate": true,
          "command": true,
          "rejection": true,
          "workflowInstanceCreation": true,
          "variable": true,
          "variableDocument": true,
          "workflowInstanceSubscription": true,
          "event": true,
          "job": true,
          "incident": true,
          "deployment": true
        },
        "bulk": {
          "delay": 10.0,
          "size": 1000.0
        },
        "url": "my_url"
      }
    },
    {
      "id": "hazelcast",
      "jarPath": "/usr/local/zeebe/lib/zeebe-hazelcast-exporter.jar",
      "className": "io.zeebe.hazelcast.exporter.HazelcastExporter",
      "args": {
        "updatePosition": true,
        "port": 5701.0,
        "topicPrefix": "zeebe-",
        "enabledRecordTypes": "EVENT",
        "enabledValueTypes": "DEPLOYMENT,JOB,JOB_BATCH,WORKFLOW_INSTANCE,WORKFLOW_INSTANCE_CREATION,WORKFLOW_INSTANCE_SUBSCRIPTION,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION"
      }
    }
  ],
  "gateway": {
    "enable": true,
    "network": {
      "host": "0.0.0.0",
      "port": 26500,
      "minKeepAliveInterval": "30s"
    },
    "cluster": {
      "contactPoint": "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local:26502",
      "maxMessageSize": "4M",
      "requestTimeout": "15s",
      "clusterName": "zeebe-cluster",
      "memberId": "gateway",
      "host": "0.0.0.0",
      "port": 26502
    },
    "threads": {
      "managementThreads": 1
    },
    "monitoring": {
      "enabled": false,
      "host": "beta-zeebe-zeebe-0.zeebe.beta.svc.cluster.local",
      "port": 9600
    },
    "security": {
      "enabled": false
    }
  },
  "backpressure": {
    "enabled": true,
    "useWindowed": true,
    "algorithm": "vegas"
  },
  "stepTimeout": "5m"
}
```

### LINKED ISSUE #3966: Close appender immediately on becoming follower
**Description**

Currently we use a reference counting approach to keep track of the writers writing to the logstream. When those writers are not closed properly (#3965 ), appender and hence the dispatcher is not closed. When the node becomes leader again, it will then use the old dispatcher instead of creating a new one. This would cause it use the old positions instead of updating the positions by reading the latest log. Since only the leader is allowed to write, it would be better to close the appender and dispatcher immediately on becoming the follower. The writers that are using this dispatcher should handle the case when they are trying to write to the already closed dispatcher.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Instead of relying on writers to close the dispatcher when transitioning to follower, we now close logstream on each role transition and recreate it. So when a node transition between leader to follower to leader, it does not re-use the dispatcher position from previous leader role.  

## Related issues

closes #3966 
closes #3920
Related to #3965 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 1]
```diff
@@ -276,6 +279,35 @@ private void transitionToLeader(final CompletableActorFuture<Void> transitionCom
...
+              } else {
+                LOG.error("Failed to install log stream for partition {}", partitionId, error);
+                installFuture.completeExceptionally(error);
+                onFailure();
+              }
+            });
+    return installFuture;
+  }
+
+  private ActorFuture<Void> installDeletionService() {
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: It is not only deletion service right? Maybe we split it more or we rename to install state?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 2]
```diff
@@ -276,6 +279,35 @@ private void transitionToLeader(final CompletableActorFuture<Void> transitionCom
...
 
   private ActorFuture<Void> basePartitionInstallation() {
+    final ActorFuture installFuture = new CompletableActorFuture();
+    openLogStream()
+        .onComplete(
+            (log, error) -> {
+              if (error == null) {
+                this.logStream = log;
+                if (!deferredCommitNotifications.isEmpty()) {
+                  deferredCommitNotifications.forEach(Runnable::run);
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: Why we need this ? :eyes:

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 3]
```diff
@@ -430,16 +461,40 @@ private StreamProcessor createStreamProcessor(final ZeebeDb zeebeDb) {
...
   }
 
-  private void tearDownBaseInstallation() {
+  private void tearDownBaseInstallation(final CompletableActorFuture<Void> closeFuture) {
     if (closeStateReplication()) {
+      closeFuture.complete(null);
       return;
     }
 
     if (closeSnapshotController()) {
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: In these cases we also would not delete the log stream right?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 4]
```diff
@@ -518,7 +573,15 @@ private void stepByStepClosing(
   @Override
   public <T extends RaftLogEntry> void onCommit(final Indexed<T> indexed) {
     if (indexed.type() == ZeebeEntry.class) {
-      this.logStream.setCommitPosition(indexed.<ZeebeEntry>cast().entry().highestPosition());
+      actor.run(
+          () -> {
+            final long commitPosition = indexed.<ZeebeEntry>cast().entry().highestPosition();
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: I dont think that this is necessary. Because at some point we will get the next commit position and we also seek to the last committed position, so for me there is no need for that?

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamBatchWriterImpl.java [hunk 5]
```diff
@@ -296,7 +293,5 @@ private void resetEvent() {
   }
 
   @Override
-  public void close() {
-    closeCallback.run();
-  }
+  public void close() {}
```
Comment (Zelldon) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamBatchWriterImpl.java]: We can remove this then again

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java [hunk 6]
```diff
@@ -193,78 +174,78 @@ public void removeOnCommitPositionUpdatedCondition(final ActorCondition conditio
...
+      writerFuture.complete(creator.create(partitionId, writeBuffer));
     } else if (appenderFuture != null) {
       appenderFuture.onComplete(onOpenAppender(writerFuture, creator));
     } else {
-      final var errorMsg =
-          String.format(
-              "Expected to have an open appender, since we have already %d open writers",
-              alreadyOpenWriters);
-      writerFuture.completeExceptionally(new IllegalStateException(errorMsg));
+      openAppender().onComplete(onOpenAppender(writerFuture, creator));
```
Comment (Zelldon) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: So this means the first writer will create the appender right?

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamWriterImpl.java [hunk 7]
```diff
@@ -173,7 +170,5 @@ private long claimLogEntry(final int valueLength, final int metadataLength) {
   }
 
   @Override
-  public void close() {
-    closeCallback.run();
-  }
+  public void close() {}
```
Comment (Zelldon) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamWriterImpl.java]: this can also be removed

File: logstreams/src/test/java/io/zeebe/logstreams/log/LogStreamBatchWriterTest.java [hunk 8]
```diff
@@ -414,4 +414,16 @@ public void shouldNotFailToWriteBatchWithoutEvents() {
...
+  public void shouldFailToWriteOnClosedLogStream() {
+    // given
+    logStreamRule.getLogStream().close();
+
+    // when
+    final long pos = writer.event().key(1).value(EVENT_VALUE_1).done().tryWrite();
+
+    // then
+    assertThat(pos).isEqualTo(-1);
+  }
```
Comment (Zelldon) [inline logstreams/src/test/java/io/zeebe/logstreams/log/LogStreamBatchWriterTest.java]: Do we already have a test for creating reader or writer on closed log stream?

File: logstreams/src/test/java/io/zeebe/logstreams/log/LogStreamTest.java [hunk 9]
```diff
@@ -92,6 +92,25 @@ public void shouldCloseLogStream() {
...
+    final long positionBeforeClose = writer.value(wrapString("value")).tryWrite();
+
+    // when
+    logStream.close();
+    logStreamRule.createLogStream();
+    final LogStreamRecordWriter newWriter = logStreamRule.getLogStream().newLogStreamRecordWriter();
+    final long positionAfterReOpen = newWriter.value(wrapString("value")).tryWrite();
+
+    // then
+    assert (positionAfterReOpen > positionBeforeClose);
```
Comment (Zelldon) [inline logstreams/src/test/java/io/zeebe/logstreams/log/LogStreamTest.java]: I like the test but please use assertj

File: logstreams/src/test/java/io/zeebe/logstreams/util/LogStreamRule.java [hunk 10]
```diff
@@ -90,7 +90,7 @@ protected void after() {
     actorSchedulerRule.after();
   }
 
-  private void startLogStream() {
+  public void createLogStream() {
```
Comment (Zelldon) [inline logstreams/src/test/java/io/zeebe/logstreams/util/LogStreamRule.java]: does it need to be public available?

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Thanks @deepthidevaki 

In general looks good just smaller stuff and questions.

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 4 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: There is still a chance for race condition, right? logstream seek to last event, onCommit listner was invoke but ZeebePartition.logstream is null as the start is not completed. Then the commit position is one event behind.  commit position gets updated only if there are more commits. As said in a comment on the other draft PR, this is not a problem on the leader (now) because it doesn't start committing until stream processor is up. But it is possible on followers.

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 3 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: Yes. It is safe to call `closeLogStream` in all cases. I will update.

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 4 above)
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: So you expect that we never commit again ? :sweat_smile:

Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: :D What if there are no more requests?

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java (hunk 6 above)
Comment (deepthidevaki) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: Yes.

File: logstreams/src/test/java/io/zeebe/logstreams/log/LogStreamBatchWriterTest.java (hunk 8 above)
Comment (deepthidevaki) [reply logstreams/src/test/java/io/zeebe/logstreams/log/LogStreamBatchWriterTest.java]: We have one in LogStreamTest.

File: logstreams/src/test/java/io/zeebe/logstreams/util/LogStreamRule.java (hunk 10 above)
Comment (deepthidevaki) [reply logstreams/src/test/java/io/zeebe/logstreams/util/LogStreamRule.java]: Yes. For access in  `LogStreamTest#shouldIncreasePositionOnRestart`

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 4 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: I did it like this for it to be more safe. But it might not be necessary now as followers never need to know commit position.

Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: I think it is a good idea, but I'm still unsure whether it adds to much complexity which is not really needed. :man_shrugging:

File: broker/src/main/java/io/zeebe/broker/engine/impl/SubscriptionApiCommandMessageHandlerService.java [hunk 11]
```diff
@@ -36,16 +36,17 @@ public String getName() {
     return actorName;
   }
 
+  @Override
+  protected void onActorStarting() {
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/engine/impl/SubscriptionApiCommandMessageHandlerService.java]: It seems your IDE orders methods lexicographically.

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 12]
```diff
@@ -430,16 +461,32 @@ private StreamProcessor createStreamProcessor(final ZeebeDb zeebeDb) {
...
+  }
+
+  private ActorFuture<Void> closeLogStream() {
+    if (logStream == null) {
+      return CompletableActorFuture.completed(null);
     }
 
-    closeSnapshotStorage();
+    final LogStream logStreamToClose = logStream;
+    logStream = null;
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: :+1:

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 4 above)
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: Btw does it mean that we collect all commits on follower? didn't we go out of mem at some point?

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 4 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: No. Once the logstream is opened, notifications will be cleared.

File: broker/src/main/java/io/zeebe/broker/engine/impl/SubscriptionApiCommandMessageHandlerService.java (hunk 11 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/engine/impl/SubscriptionApiCommandMessageHandlerService.java]: Don't know why that happens. I don't remember changing any settings. I will verify it.

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 2 above)
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: I had a deeper thinking about that. I think it should be enough to just keep track of the last commit position, which we received. It is not necessary to keep track of the lambdas, which in the end set the commit position.

**Comment by Zelldon** [comment]
Do we have a benchmark with that running?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 2 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: :+1:  That would be enough.

**Comment by deepthidevaki** [comment]
> Do we have a benchmark with that running?

No. I had one with the spike fix. But I can setup one.

**Review by ChrisKujawa — APPROVED** [review]

**Comment by deepthidevaki** [comment]
bors retry
