### PR TITLE
fix(exporters/elasticsearch-exporter): avoid OOM when retrying

### LINKED ISSUE #4668: Elasticsearch exporter bulk is not limited
**Describe the bug**
The Elasticsearch exporter inserts all records in a bulk and flushes the bulk when the size/time limit is reached. If a failure occurs while flushing the bulk then the exporter try to flush the bulk again.

If a new record is passed to the exporter then the record is added to the bulk. 

If the failure persists for a longer period then the bulk is growing and may lead to an out-of-memory exception. 

**To Reproduce**
Stop ES while exporting records. 

**Expected behavior**
The exporter stops adding new records to the bulk after some limit is reached. 

**Log/Stacktrace**
Nope.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.23.0, 0.24.0-alpha2
 - Configuration: elasticsearch exporter

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Don't append record again when retrying to export, in order to avoid OOM exception.

## Related issues

closes #4668 

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java [hunk 1]
```diff
@@ -118,7 +125,10 @@ public void bulk(final Map<String, Object> command, final Record<?> record) {
           "Failed to serialize bulk request command to JSON", e);
     }
 
-    bulkRequest.add(serializedCommand + "\n" + record.toJson());
+    final String jsonCommand = serializedCommand + "\n" + record.toJson();
+    if (bulkRequest.isEmpty() || !bulkRequest.get(bulkRequest.size() - 1).equals(jsonCommand)) {
```
Comment (saig0) [inline exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java:129]: We could add a comment here why we're filtering it out. I think it is not so obvious.

File: exporters/elasticsearch-exporter/src/test/java/io/zeebe/exporter/ElasticsearchClientTest.java [hunk 2]
```diff
@@ -143,4 +145,22 @@ public void shouldThrowExceptionIfFailToFlushBulk() {
...
+
+  @Test
+  public void shouldIgnoreRecordIfDuplicateOfLast() {
+    // given
+    final Record<VariableRecordValue> recordMock = mock(Record.class);
+    when(recordMock.getPartitionId()).thenReturn(1);
+    when(recordMock.getValueType()).thenReturn(ValueType.WORKFLOW_INSTANCE);
+    when(recordMock.getKey()).thenReturn(RECORD_KEY + 1);
+    when(recordMock.toJson()).thenReturn("{}");
+    client.index(recordMock);
```
Comment (saig0) [inline exporters/elasticsearch-exporter/src/test/java/io/zeebe/exporter/ElasticsearchClientTest.java:157]: A new-line could improve the reading flow.

```suggestion
    when(recordMock.toJson()).thenReturn("{}");
    
    client.index(recordMock);
```

**Review by saig0 — APPROVED** [review]
:+1: 

Just two small optional suggestions.
