### PR TITLE
Remove ignoreVariablesAbove ES configuration option

### LINKED ISSUE #6286: Improve log warning message for variable exceeded max size, not indexed by ES
**Description**

The following warning often leads investigators to incorrect conclusions about whether or not the variable is successfully exported (or imported by ES).
> "Variable {key: .., name: .., variableScope: .., workflowInstanceKey: ..} exceeded max size of .. bytes with a size of .. bytes. As a consequence this variable is not index by elasticsearch.

During the incident postmortem of gameday (28-01-2021), the issue was brought up. The group agreed that the warning message should be altered to better describe the scope of the consequences.

https://github.com/zeebe-io/zeebe/pull/3896

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR removes the `ignoreVariablesAbove` configuration option from the ES exporter. This option was previously used to control when to log a warning if a variable was too big. After discussion, it was considered a normal pitfall of using Elastic, and it should be documented, but doesn't warrant a warning in the logs.

## Related issues

closes #6286 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java [hunk 1]
```diff
@@ -377,7 +353,7 @@ private static String indexTemplateForValueType(final ValueType valueType) {
   }
 
   private Map<String, Object> convertToMap(final XContent content, final InputStream input) {
-    try (XContentParser parser =
+    try (final XContentParser parser =
```
Comment (korthout) [inline exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:356]: Nit: This change stops you from having a PR that only removes lines 😢

**Review by korthout — APPROVED** [review]
LGTM 🌈
