### PR TITLE
Fix issues with class loading for external exporters relying on the Thread's context class loader

### LINKED ISSUE #4196: Kafka cannot be loaded through our ExporterJarClassLoader
**Describe the bug**

If loading an exporter with Kafka as a dependency through an isolated `ExporterJarClassLoader`, Kafka will produce `ClassNotFoundError`. The class, however, is definitely found by our class loader - it is simply unavailable to Kafka as it tries to load it through the `Thread#getContextClassLoader()`, which is (if unset) the class loader of the thread's creator - in our case, the system class loader.

**To Reproduce**

I used one of our user's exporter - https://github.com/openMF/ph-ee-exporter - and could reproduce the problem by loading an exporter and pointing the JAR path to the fat JAR it produces. I also verified the issue is indeed the `Thread#getContextClassLoader` by wrapping all of the accesses to an exporter instance's methods (e.g. `#configure`, `#open`, `#close`, etc.) in a try/finally block where I override the thread context class loader, and the problem went away.

**Expected behavior**

I expect that we support exporters providing their own dependency versions in an isolated class loader to avoid dependency collisions, and that we support most common access cases (e.g. `getClass().getClassLoader()`, `Thread.currentThread().getContextClassLoader()`, etc.).

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
19:30:22.391 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] ERROR io.zeebe.util.actor - Uncaught exception in 'Broker-0-Exporter-1' in phase 'STARTED'. Continuing with next job.
org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serialization.StringSerializer for configuration key.serializer: Class org.apache.kafka.common.serialization.StringSerializer could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:728) ~[?:?]
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:474) ~[?:?]
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:467) ~[?:?]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108) ~[?:?]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129) ~[?:?]
	at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:409) ~[?:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:326) ~[?:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:270) ~[?:?]
	at hu.dpc.rt.kafkastreamer.exporter.KafkaExporterClient.<init>(KafkaExporterClient.java:57) ~[?:?]
	at hu.dpc.rt.kafkastreamer.exporter.KafkaExporter.createClient(KafkaExporter.java:77) ~[?:?]
	at hu.dpc.rt.kafkastreamer.exporter.KafkaExporter.open(KafkaExporter.java:43) ~[?:?]
	at io.zeebe.broker.exporter.stream.ExporterDirector.onSnapshotRecovered(ExporterDirector.java:225) ~[classes/:?]
	at io.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:140) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [classes/:?]
19:30:22.591 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER} and terms {1=12}.
```
</p>
</details>

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes issues when an external exporter (i.e. a self-contained JAR) wants to load classes via the current thread's context class loader. This occurred, for example, in the Kafka exporter, as the Kafka library will use the current thread's context class loader instead of just the current class loader. The fix is to wrap every exporter call and set/reset the context class loader before/after.

Part of this PR brings improvements to the exporter tests, mostly relating to external exporters. It introduces ByteBuddy as a simpler alternative to building external exporters: ByteBuddy is a battle tested library which gives you an easy to use API to implement classes on the fly and package them as JARs. Additionally, by using this instead of pre-made classes and building JARs out of them, we can guarantee that the class ByteBuddy creates does not exist in the current class loader, which increases the robustness of our tests.

This PR also introduces junit5 to the broker and migrates the modified tests to it, as part of our long term goals to migrate from junit4 to junit5.

I recommend the reviewer to check commit-by-commit, but keep in mind that the last commit is the "goal" of the PR, and all the work prior to it is essentially building up to it. I'm also happy to split this into multiple PR if that's easier to review instead, don't hesitate to ask! I hesitated on this as I felt it was important to keep the context, but in the end I think the reviewer will have better insight in what's easier for them.

I have some worries about the PR, in that while using ByteBuddy is probably more reliable than writing out own code to churn out classes on the fly and create JARs for them, it's also a little "arcane" if you've never used it, and I fear the test is maybe more complex than desired. I'd be happy to hear thoughts on how we could avoid this complexity while still testing the functionality. Although working on this really impressed on me that we may want to rethink exporters, and instead of running arbitrary code in the broker, we may just want to provide an API to get data out.

## Related issues

closes #4196 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
FYI - this is something I did in slack time for the Kafka exporter, so treat it as you normally would external PRs in terms of prio :slightly_smiling_face:

File: broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java [hunk 1]
```diff
@@ -88,7 +88,15 @@ private void validate(final ExporterDescriptor descriptor) throws ExporterLoadEx
...
-      instance.configure(context);
+
+      final var currentThread = Thread.currentThread();
+      final var previousClassLoader = currentThread.getContextClassLoader();
+      try {
+        currentThread.setContextClassLoader(instance.getClass().getClassLoader());
+        instance.configure(context);
+      } finally {
+        currentThread.setContextClassLoader(previousClassLoader);
+      }
```
Comment (korthout) [inline broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java:99]: Would it be possible to reuse the ExporterContainer's checkedRunWithClassLoader? It seems to be the same logic and `() -> instance.configure(context)` would fit the CheckedRunnable interface. If it's possible, this would fit DRY. If it doesn't, I think it might be good to add a comment here why this is necessary (perhaps even referring to the ExporterContainer)

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java [hunk 2]
```diff
@@ -0,0 +1,203 @@
...
+ * property set to it. We can then compare the captured TCL with that.
+ */
+@Execution(ExecutionMode.CONCURRENT)
+final class ExternalExporterContainerTest {
+  private static final String EXPORTER_CLASS_NAME = "com.acme.TestExporter";
+  private ExporterContainerRuntime runtime;
+
+  @BeforeEach
+  void beforeEach(final @TempDir Path storagePath) {
+    runtime = new ExporterContainerRuntime(storagePath);
```
Comment (korthout) [inline broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java:54]: I'm not that familiar with junit5, but the `@Execution` is set to `CONCURRENT`. Wouldn't that mean the runtime is overwritten concurrently? Or does each test get its own instance of this test class?

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java [hunk 3]
```diff
@@ -0,0 +1,203 @@
...
+    // then
+    final var exporterInstance = (TclExporter) container.getExporter();
+    assertThat(exporterInstance.onCloseTCL)
+        .isSameAs(expectedClassLoader)
+        .isInstanceOf(ExporterJarClassLoader.class);
+  }
+
+  private Unloaded<TclExporter> createUnloadedExporter() {
+    return new ByteBuddy().subclass(TclExporter.class).name(EXPORTER_CLASS_NAME).make();
+  }
```
Comment (korthout) [inline broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java:161]: This might need a comment describing why bytebuddy is used

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java [hunk 4]
```diff
@@ -0,0 +1,203 @@
...
+    public ClassLoader onConfigureTCL;
+    public ClassLoader onOpenTCL;
+    public ClassLoader onCloseTCL;
+    public ClassLoader onExportTCL;
+
+    @Override
+    public void configure(final Context context) throws Exception {
+      onConfigureTCL = Thread.currentThread().getContextClassLoader();
+
+      // this will cause it to fail when using the wrong class loader during validation
```
Comment (korthout) [inline broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java:184]: please also explain why this would fail (that might be lost to future readers)

**Review by korthout — APPROVED** [review]
LGTM 👏 Please see my comments before merging.

Since this is a larger PR, I have some additional notes:
- I don't mind that this is a larger PR, these changes clearly belong together (although an exception could've been made for the junit4 -> junit5 changes)
- I like the setup with bytebuddy and I don't think it's that archaic. The 'complex' test you mentioned is also totally fine. It simply captures the used classloader and makes some assertions on it. I do agree that a better solution would be to change our exporter api altogether and no longer allow side loading arbitrary code, but I consider that out of scope for this issue
- The split of commits was very well done and made review so much easier
- Nit: the last commit already has type `fix` so doesn't need to restate it, instead it could be something like `fix(broker): use local class loader in exporters`
- You might consider backporting this as well to 0.26

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterContainerTest.java [hunk 5]
```diff
@@ -11,53 +11,42 @@
...
-
-    final var exporterDescriptor =
-        new ExporterDescriptor("fakeExporter", FakeExporter.class, Map.of("key", "value"));
-    exporterContainer = new ExporterContainer(exporterDescriptor);
+  @BeforeEach
+  void beforeEach(final @TempDir Path storagePath) throws ExporterLoadException {
+    runtime = new ExporterContainerRuntime(storagePath);
+
+    final var descriptor =
+        runtime.getRepository().load("fakeExporter", FakeExporter.class, Map.of("key", "value"));
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterContainerTest.java:43]: Actually, this method really should be in the repository test class, which is why it seems a little strange here. There we just work directly with the repository - so it might make more sense to move it there. I'll think about it a bit

File: broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java (hunk 1 above)
Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java:99]: I considered it briefly, but what component would you use to share this code? It's too special purpose I think for a general utility, and it only has one small case of duplication.

It actually made me think that the approach to validation is possibly incorrect - maybe we should instead build the container once at startup, and just keep it around, calling open/close? It does put more burden on the exporter authors to clean up their resources and ensure the same instance can be reused though, so it has some non negligible downsides.

Anyhow, if you have some idea of where it would fit to reuse/share this code, I'm open to it. I just didn't really see it.

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java (hunk 2 above)
Comment (npepinpe) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java:54]: No, the lifecycle is still as you expect - for each test, an instance of the class is created, so instance-level properties are isolated.

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java (hunk 3 above)
Comment (npepinpe) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java:161]: I figured the class level doc was enough - do you think it's not?

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java (hunk 4 above)
Comment (npepinpe) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java:184]: Good point, it seemed obvious to me at the time why it fails, but yeah :sweat_smile:

File: broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java (hunk 1 above)
Comment (korthout) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java:99]: I don't really see it either, I was thinking about just making `checkedRunWithClassLoader` in `ExporterContainer` public and static. You'd need to pass in the exporter instance to use that way. Not sure if that's nice to use. But like I said, it's also fine to just add a comment why this is necessary and possibly referring to ExporterContainer.

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java (hunk 3 above)
Comment (korthout) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExternalExporterContainerTest.java:161]: Ah sorry, I lost that context during this review point I think., but you're absolutely right. Fine as is

File: broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java (hunk 1 above)
Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java:99]: I thought about it some more, and in theory this is thread specific code - you could do something like:

```java
public final class ThreadUtil {
  public static void runCheckedWithClassLoader(
      final CheckedRunnable runnable, final ClassLoader classLoader) throws Exception {
    final var currentThread = Thread.currentThread();
    final var contextClassLoader = currentThread.getContextClassLoader();

    try {
      currentThread.setContextClassLoader(classLoader);
      runnable.run();
    } finally {
      currentThread.setContextClassLoader(contextClassLoader);
    }
  }
}
```

That's not too crazy - however in our code base it's still only used for really on purpose, side loading external exporters, so I'm unsure about moving it into something like `zeebe-util`. We could have it as a utility in the exporter package maybe?

Comment (korthout) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java]: I like the idea to keep this in the exporter package. There's a big chance we remove this in the future, when we rework exporters.

**Comment by npepinpe** [comment]
Regarding your other points:


>  I don't mind that this is a larger PR, these changes clearly belong together (although an exception could've been made for the junit4 -> junit5 changes)

Well, I wanted to write the new tests to junit5, so I thought it fit all together contextually - but I would also be fine splitting them.

>  I like the setup with bytebuddy and I don't think it's that archaic. The 'complex' test you mentioned is also totally fine. It simply captures the used classloader and makes some assertions on it. I do agree that a better solution would be to change our exporter api altogether and no longer allow side loading arbitrary code, but I consider that out of scope for this issue

Good to hear :slightly_smiling_face: I thought it might be too strange if you'd never used it, but it's always hard to think about this without bias.

>  You might consider backporting this as well to 0.26

We can try, but I wouldn't invest too much time if it's difficult to port due to conflicts or having to back port other things. Let's see what the bot does.

File: broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java (hunk 1 above)
Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/repo/ExporterRepository.java]: > when we rework exporters

Such optimism :smile:

**Review by korthout — APPROVED** [review]
Nice work on the improvements. The test setup has really improved in your last commit.

Note that your build fails currently.

**Comment by npepinpe** [comment]
Forgot to add the license :smile:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors retry

**Comment by npepinpe** [comment]
Back porting to 0.26 is a pain due to the artifact/group rename and some other changes in 1.0. I'm also not sure this is so high value that it's worth it, tbh.
