### PR TITLE
test: don't fail test if scheduled task runs more often than expected

### LINKED ISSUE #10745: `ProcessingScheduleServiceTest.shouldScheduleOnFixedRate` is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Twice in the last two days
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Warning:  Flakes: 
Warning:  io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest.shouldScheduleOnFixedRate
Error:    Run 1: ProcessingScheduleServiceTest.shouldScheduleOnFixedRate:291 
dummyTask.execute(<any>);
Wanted 5 times:
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest$DummyTask.execute(ProcessingScheduleServiceTest.java:383)
But was 145 times:
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$runAtFixedRate$1(ProcessingScheduleServiceImpl.java:65)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$runAtFixedRate$1(ProcessingScheduleServiceImpl.java:65)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$runAtFixedRate$1(ProcessingScheduleServiceImpl.java:65)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$runAtFixedRate$1(ProcessingScheduleServiceImpl.java:65)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$runAtFixedRate$1(ProcessingScheduleServiceImpl.java:65)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$runAtFixedRate$1(ProcessingScheduleServiceImpl.java:65)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$runAtFixedRate$1(ProcessingScheduleServiceImpl.java:65)
</pre>
</details>

**Hypotheses**

If the test thread is blocked (e.g. by gc), the task can be executed more than 5 times. The verification is too strict.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
If the test thread was blocked for a while, for example due to garbage collection, verifying that the task ran exactly 5 times within 2 seconds would fail because it ran more often than that.

With this change we just verify that the task ran at least 5 times within 2 seconds.

closes #10745

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/streamprocessor/ProcessingScheduleServiceTest.java [hunk 1]
```diff
@@ -288,7 +288,7 @@ public void shouldScheduleOnFixedRate() {
     scheduleService.runAtFixedRate(Duration.ofMillis(10), mockedTask);
 
     // then
-    verify(mockedTask, TIMEOUT.times(5)).execute(any());
+    verify(mockedTask, TIMEOUT.atLeast(5)).execute(any());
```
Comment (deepthidevaki) [inline engine/src/test/java/io/camunda/zeebe/streamprocessor/ProcessingScheduleServiceTest.java:291]: It doesn't look like this test is testing really what it wants. To make it deterministic, one way would be to use `ControlledActorScheduler`. Then we can write:

```
    scheduleService.runAtFixedRate(Duration.ofSeconds(10), mockedTask);
    actorScheduler.runUntilDone();

    // verify it ran at the first interval
    clock.addTime(Duration.ofSeconds(10));
    actorScheduler.runUntilDone();
    verify(mockedTask, times(1)).execute(any());
 
   // verify it was rescheduled for the next interval
    clock.addTime(Duration.ofSeconds(10));
    actorScheduler.runUntilDone();
    verify(mockedTask, times(2)).execute(any());
```

What do you think?

Comment (oleschoenburg) [reply engine/src/test/java/io/camunda/zeebe/streamprocessor/ProcessingScheduleServiceTest.java:291]: I interpreted the test more as a "see if `runAtFixedRate` works at all" test and not so much as a test that verifies specific timings.

I think it makes sense to test that `runAtFixedRate` runs jobs at a rate that is close to the requested rate but that'd be a separate test IMO.

Comment (deepthidevaki) [reply engine/src/test/java/io/camunda/zeebe/streamprocessor/ProcessingScheduleServiceTest.java:291]: Ok. Then this test is enough. I don't think another test is required. I assume time based scheduling is already tested for actor scheduler.

**Review by deepthidevaki — APPROVED** [review]
Thanks :tada:

**Comment by oleschoenburg** [comment]
bors merge
