### PR TITLE
fix: do not throw Exception when GCS store is not accessible on startup

### LINKED ISSUE #14593: InvalidConfigurationException when GCS store is not accessible on startup
**Describe the bug**

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) [spring-boot-3.1.2.jar:3.1.2]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:82) [camunda-zeebe-8.2.15.jar:8.2.15]
Caused by: io.camunda.zeebe.broker.system.InvalidConfigurationException: Failed configuring backup store GCS
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:132) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more
Caused by: io.camunda.zeebe.backup.gcs.GcsBackupStoreException$ConfigurationException$CouldNotAccessBucketException: Bucket Expected to access bucket 'camunda-saas-int-backup-worker-3', but failed does not exist
	at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig(GcsBackupStore.java:200) ~[zeebe-backup-store-gcs-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:124) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more
Caused by: com.google.cloud.storage.StorageException: Error getting access token for service account: oauth2.googleapis.com, iss: backups-worker-3@camunda-saas-int.iam.gserviceaccount.com
	at com.google.cloud.storage.StorageException.translate(StorageException.java:165) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:297) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:441) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.lambda$listBlobs$11(StorageImpl.java:421) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.23.3.jar:2.23.3]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.Retrying.run(Retrying.java:60) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:418) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:384) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig(GcsBackupStore.java:197) ~[zeebe-backup-store-gcs-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:124) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more
Caused by: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account: oauth2.googleapis.com, iss: backups-worker-3@camunda-saas-int.iam.gserviceaccount.com
	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointIOException(GoogleAuthException.java:166) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:543) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-31.1-jre.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:581) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:232) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:182) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:938) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) ~[google-cloud-core-http-2.13.0.jar:2.13.0]
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109) ~[google-cloud-core-http-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc$InvocationIdInitializer.initialize(HttpStorageRpc.java:152) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:91) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:442) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:431) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.lambda$listBlobs$11(StorageImpl.java:421) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.23.3.jar:2.23.3]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.Retrying.run(Retrying.java:60) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:418) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:384) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig(GcsBackupStore.java:197) ~[zeebe-backup-store-gcs-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:124) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more
Caused by: java.net.UnknownHostException: oauth2.googleapis.com
	at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:538) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-31.1-jre.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:581) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:232) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:182) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:938) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) ~[google-cloud-core-http-2.13.0.jar:2.13.0]
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109) ~[google-cloud-core-http-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc$InvocationIdInitializer.initialize(HttpStorageRpc.java:152) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:91) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:442) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:431) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.lambda$listBlobs$11(StorageImpl.java:421) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.23.3.jar:2.23.3]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.Retrying.run(Retrying.java:60) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:418) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:384) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig(GcsBackupStore.java:197) ~[zeebe-backup-store-gcs-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:124) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more

```

Impact:
Fails broker startup. But restart succeeds.

**To Reproduce**

I don't think this is due to an actual configuration error, but because we validate GCS store configuration by trying to connect to the storage. If it is temporarily unavailable, validation fails. 

**Expected behavior**

Temporary errors should not cause validation failures.

**Log/Stacktrace**

[link to logs](https://console.cloud.google.com/errors/detail/CNeMl4mEyt_8NA;service=zeebe;time=P7D?project=camunda-saas-int)

**Environment:**
- Zeebe Version: 8.2.15

### PR DESCRIPTION
**Pull request by entangled90**
## Description

In an exception is throw at startup, just log it at warning so that all information necessary if available when reading the logs. Because this error can be transient, it's better to continue anyway the initialization of the broker.
`GcsBackupStoreConfig`  performs validation in the constructor already.
## Related issues
closes #14593

### CODE REVIEW

File: zeebe/backup-stores/gcs/src/main/java/io/camunda/zeebe/backup/gcs/GcsBackupStore.java [hunk 1]
```diff
@@ -167,11 +170,13 @@ public static Storage buildClient(final GcsBackupConfig config) {
...
   public static void validateConfig(final GcsBackupConfig config) {
+    Objects.requireNonNull(config);
     try (final var storage = buildClient(config)) {
       storage.list(config.bucketName(), BlobListOption.pageSize(1));
     } catch (final Exception e) {
-      throw new CouldNotAccessBucketException(
-          ERROR_MSG_ACCESS_FAILED.formatted(config.bucketName()), e);
+      LOG.warn(
+          "Unable to verify that the config is valid, initialization will continue as it can be a transient network issue",
+          e);
```
Comment (deepthidevaki) [inline zeebe/backup-stores/gcs/src/main/java/io/camunda/zeebe/backup/gcs/GcsBackupStore.java:179]: :x: This validation ignores all failures. I think it is better to follow the validation approach used in S3BackupStore. 

There is no need to query GCS during validation. This way it does not fail when GCS is temporarily unavailable. But we have to do other validations, like if bucket name is configured etc. It would be good to create a throw away client to verify the configuration if it does not fail when GCS is not reachable.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks. Please see my comment.

**Comment by rodrigo-lourenco-lopes** [comment]
As @korthout mentioned, as a follow-up issue can we also make the changes in the docs to remove the following paragraph?

> The bucket specified with bucketName must already exist, Zeebe will not try to create one for you. To prevent misconfiguration, Zeebe will check at startup that the specified bucket exists and can be accessed.

**Comment by deepthidevaki** [comment]
> As @korthout mentioned, as a follow-up issue can we also make the changes in the docs to remove the following paragraph?
> 
> > The bucket specified with bucketName must already exist, Zeebe will not try to create one for you. To prevent misconfiguration, Zeebe will check at startup that the specified bucket exists and can be accessed.
> 
> https://docs.camunda.io/docs/next/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore/



> The bucket specified with bucketName must already exist, Zeebe will not try to create one for you.

This is still valid. Zeebe will not create the bucket.

File: zeebe/backup-stores/gcs/src/main/java/io/camunda/zeebe/backup/gcs/GcsBackupStore.java (hunk 1 above)
Comment (entangled90) [reply zeebe/backup-stores/gcs/src/main/java/io/camunda/zeebe/backup/gcs/GcsBackupStore.java:179]: In class `GcsBackupConfig` those fields are validate in the constructor, hence that's why no validation was added in this function.
Considering that the exception in the issue's stacktrace was raised from the call to `list` I don't know if building the client can raise an Exception.
I can separate these two calls into two different try/catch blocks and raise an exception only if building the client fails.

I would keep the log line for the list call so if the bucket is not existing for example it's logged somewhere with the name configured.

File: zeebe/backup-stores/gcs/src/main/java/io/camunda/zeebe/backup/gcs/GcsBackupStore.java [hunk 2]
```diff
@@ -168,7 +171,13 @@ public static Storage buildClient(final GcsBackupConfig config) {
 
   public static void validateConfig(final GcsBackupConfig config) {
     try (final var storage = buildClient(config)) {
-      storage.list(config.bucketName(), BlobListOption.pageSize(1));
+      try {
+        storage.list(config.bucketName(), BlobListOption.pageSize(1));
+      } catch (final Exception e) {
+        LOG.warn(
+            "Unable to verify that the bucket exists, initialization will continue as it can be a transient network issue",
```
Comment (deepthidevaki) [inline zeebe/backup-stores/gcs/src/main/java/io/camunda/zeebe/backup/gcs/GcsBackupStore.java:178]: :wrench: Would be good to add the bucket name to the warning message.

**Review by deepthidevaki — APPROVED** [review]
Thanks. Please see my comments before merging.

**Comment by deepthidevaki** [comment]
> In regard to this phrase `Zeebe will check at startup that the specified bucket exists and can be accessed.` should I change the docs as suggested? Do I need also to add it in the release notes as a behaviour change that the customer should be aware of?

Yes.

**Comment by nicpuppa** [comment]
Hey @entangled90 do you know why this fix wasn't backported ?

**Comment by entangled90** [comment]
I don't remember any, I probably wasn't aware at the time
