### PR TITLE
fix: fail fast if a partition generates a key outside of its keyspace

### LINKED ISSUE #40981: Add key range validation to prevent partition key overflows
### 

### 

  

### 

### 

### Description

A customer reported issues where process instance keys created by Partition 1 appeared to belong to Partition 2, resulting in `NOT_FOUND` errors when the gateway routed requests to the wrong partition. Investigation revealed that Partition 1's key range had overflowed into Partition 2's key range, even though the allocated key ranges are designed to prevent this.

The root cause of the overflow is still unknown, but it is not likely due to key space exhaustion as the key ranges are very large. 

Impact:
- Instances created in Partition 1 cannot be processed because gateway routes related requests to partition 2
- Resource distribution is affected as other partitions do not ack back to Partition 1, but Partition 2.
- Key collision in Partition 2 can leads to corrupted state.
- Potential data loss or data corruption

### Steps to reproduce

Unknown.

### Workaround

Recovering the state might be possible by manually re-mapping the affected keys in the primary and secondary storage. But this is error prone.

### Rootcause

The root cause is unknown. One possible reason is that the key space has really exhausted, but this is highly unlikely. Another possibility is the somehow we jumped the key space - we don't know yet how this can happen. 

### Solution ideas

To prevent state corruption and hard-to-debug errors in the future, add validation checks to ensure that:

- Any newly generated key is within the valid range for its partition.
- Any operation that overwrites a key in the state verifies the key belongs to the correct partition.

If a key is found to be out of range, the system should fail fast and log an error, preventing further state corruption.

### Links

https://jira.camunda.com/browse/SUPPORT-30086

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #40981

### CODE REVIEW

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java [hunk 1]
```diff
@@ -31,14 +32,20 @@ public final class DbKeyGenerator implements KeyGeneratorControls {
...
         new NextValueManager(keyStartValue, zeebeDb, transactionContext, ZbColumnFamilies.KEY);
   }
 
   @Override
   public long nextKey() {
-    return nextValueManager.getNextValue(LATEST_KEY);
+    final var nextKey = nextValueManager.getNextValue(LATEST_KEY);
+    if (Protocol.decodePartitionId(nextKey) != partitionId) {
+      throw new IllegalStateException(
+          String.format("Generated key %d does not belong to partition %d", nextKey, partitionId));
```
Comment (entangled90) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java]: 🔧 we could also add to the message which partition the key belongs to

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java [hunk 2]
```diff
@@ -57,6 +64,10 @@ public void setKeyIfHigher(final long key) {
     final var currentKey = nextValueManager.getCurrentValue(LATEST_KEY);
 
     if (key > currentKey) {
+      if (Protocol.decodePartitionId(key) != partitionId) {
+        throw new IllegalArgumentException(
+            String.format("Provided key %d does not belong to partition %d", key, partitionId));
```
Comment (entangled90) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java]: 🔧 same as above

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java [hunk 3]
```diff
@@ -31,14 +32,20 @@ public final class DbKeyGenerator implements KeyGeneratorControls {
    */
   public DbKeyGenerator(
       final int partitionId, final ZeebeDb zeebeDb, final TransactionContext transactionContext) {
+    this.partitionId = partitionId;
     keyStartValue = Protocol.encodePartitionId(partitionId, INITIAL_VALUE);
     nextValueManager =
         new NextValueManager(keyStartValue, zeebeDb, transactionContext, ZbColumnFamilies.KEY);
```
Comment (entangled90) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java:39]: 💭 we might even validate that the value in the snapshot is valid in the constructor: that will help diagnosing the issue if the snapshot is broken.

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java [hunk 4]
```diff
@@ -31,14 +32,20 @@ public final class DbKeyGenerator implements KeyGeneratorControls {
...
 
   @Override
   public long nextKey() {
-    return nextValueManager.getNextValue(LATEST_KEY);
+    final var nextKey = nextValueManager.getNextValue(LATEST_KEY);
+    if (Protocol.decodePartitionId(nextKey) != partitionId) {
+      throw new IllegalStateException(
+          String.format("Generated key %d does not belong to partition %d", nextKey, partitionId));
+    }
+    return nextKey;
```
Comment (ChrisKujawa) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java:61]: This might be not enough, as this will just fail the processing of the command and banning the corresponding instance. What we want is to hard fail right?

**Review by entangled90 — APPROVED** [review]
Thanks 🚀

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/MigrationTransitionStep.java [hunk 5]
```diff
@@ -44,7 +43,9 @@ public ActorFuture<Void> transitionTo(
             context.getPartitionId(),
             zeebeDb,
             zeebeDbContext,
-            new DbKeyGenerator(context.getPartitionId(), zeebeDb, zeebeDbContext),
```
Comment (ChrisKujawa) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/MigrationTransitionStep.java:47]: I saw this as well in the code and was wondering whether this could be the culprint. That we somewhere in the migrations generated some keys 🤔 We wouldn't see now in our CI I think because we dont execute them ? 🤔

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java (hunk 4 above)
Comment (deepthidevaki) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java:61]: Ah.. true. An unrecoverable exception will force stream processor to fail, right?

Comment (ChrisKujawa) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/state/DbKeyGenerator.java:61]: Yeah I think so 👍🏼

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/MigrationTransitionStep.java (hunk 5 above)
Comment (deepthidevaki) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/MigrationTransitionStep.java:47]: Based on the code, it is not used in the migration path. So I think it is safe for now. This is just to prevent future misuses.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/KeyGeneratorTest.java [hunk 6]
```diff
@@ -75,4 +75,26 @@ public void shouldGetUniqueValuesOverPartitions() throws Exception {
...
+    // when - then
+    try {
+      keyGenerator2.setKeyIfHigher(keyOfAnotherPartition);
+    } catch (final IllegalArgumentException e) {
+      assertThat(e.getMessage())
+          .isEqualTo(
+              String.format(
+                  "Provided key %d does not belong to partition %d",
+                  keyOfAnotherPartition, Protocol.DEPLOYMENT_PARTITION));
+    }
```
Comment (ChrisKujawa) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/KeyGeneratorTest.java]: I think you want assertThrow, because otherwise the test can also be green if no exception is thrown

File: zeebe/stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorKeyGeneratorErrorTest.java [hunk 7]
```diff
@@ -0,0 +1,60 @@
...
+  @Test
+  void shouldShutdownIfKeyGenerationFailed() {
+    // given
+    streamProcessor = streamPlatform.startStreamProcessorNotAwaitOpening();
+    final var mockedRecordProcessor = streamPlatform.getDefaultMockedRecordProcessor();
+
+    final var zeebeDb = streamPlatform.getZeebeDb();
+    final DbKeyGenerator dbKeyGenerator = new DbKeyGenerator(1, zeebeDb, zeebeDb.createContext());
+    // set the key generator to a value that will cause an overflow on next key generation
+    dbKeyGenerator.setKeyIfHigher(Protocol.encodePartitionId(1, (long) Math.pow(2, 51) - 1));
```
Comment (ChrisKujawa) [inline zeebe/stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorKeyGeneratorErrorTest.java:42]: ❤️ Thanks for adding this test 👍🏼

**Review by ChrisKujawa — APPROVED** [review]
Just one thing regarding the assertion of the exception otherwise looks good. Thanks for doing this 👍🏼

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/KeyGeneratorTest.java (hunk 6 above)
Comment (deepthidevaki) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/KeyGeneratorTest.java]: :see_no_evil:
