### PR TITLE
Fix race condition between snapshot listener and updating currentSnapshot by PassiveRole

### LINKED ISSUE #14694: `RandomizedRaftTest#consistencyTestWithSnapshot` fails with uncaught exception
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once so far: https://github.com/camunda/zeebe/actions/runs/6491028769/job/17627701526
- Does it block your work? No
- Do we suspect that it is a real failure? Possibly

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
java.lang.AssertionError: Uncaught exception
	at org.junit.Assert.fail(Assert.java:89)
	at io.atomix.raft.DeterministicSingleThreadContext$WrappedRunnable.run(DeterministicSingleThreadContext.java:112)
	at org.jmock.lib.concurrent.DeterministicScheduler$CallableRunnableAdapter.call(DeterministicScheduler.java:176)
	at org.jmock.lib.concurrent.DeterministicScheduler$ScheduledTask.run(DeterministicScheduler.java:251)
	at org.jmock.lib.concurrent.DeterministicScheduler.runNextPendingCommand(DeterministicScheduler.java:66)
	at org.jmock.lib.concurrent.DeterministicScheduler.runUntilIdle(DeterministicScheduler.java:56)
	at org.jmock.lib.concurrent.DeterministicScheduler.tick(DeterministicScheduler.java:45)
	at io.atomix.raft.ControllableRaftContexts.tick(ControllableRaftContexts.java:313)
	at io.atomix.raft.ControllableRaftContexts.tickElectionTimeout(ControllableRaftContexts.java:287)
	at io.atomix.raft.RaftOperation.run(RaftOperation.java:42)
	at io.atomix.raft.RandomizedRaftTest.consistencyTest(RandomizedRaftTest.java:180)
	at io.atomix.raft.RandomizedRaftTest.consistencyTestWithSnapshot(RandomizedRaftTest.java:96)
</pre>
</details>

**Hypotheses**
Not clear what happened. Unfortunately, the actual exception is lost because it is printed to stderr and not logged properly:
https://github.com/camunda/zeebe/blob/b7df1f5ee03d9187a1c15e640928be3aeb64f62d/atomix/cluster/src/test/java/io/atomix/raft/DeterministicSingleThreadContext.java#L106-L114

**Logs**

[randomized-raft-test.zip](https://github.com/camunda/zeebe/files/12878159/randomized-raft-test.zip)

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

The current snapshot is updated two ways.
1. When a new snapshot is committed by the SnapshotStore, and the listener is executed
   asynchrously.
2. When the follower recieves a snapshot, the current snapshot is updated immediately after
   it is committed.

Since the listener from step 1 is scheduled on the Raft context, it might be executed after
another `InstallRequest` is processed. If that happens, the listener might overwrite the
`currentSnapshot` with an older one. Eventually the cached snapshot will be updated to the latest
one. But there can be a short time when it is not reflecting the latest one. This can
cause issues in append requests and install requests.

A specific scenario is described [here](https://github.com/camunda/zeebe/issues/14694#issuecomment-1794824736)

To prevent this race condition, we update the cached snapshot by directly reading it from the
persisted snapshot store. This way the out of order execution of the listener will not
overwrite the current snapshot info. The listener is just a way to notify that a new snapshot
is available in the snapshot store.

## Related issues

closes #14694 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java [hunk 1]
```diff
@@ -187,8 +188,16 @@ public CompletableFuture<InstallResponse> onInstall(final InstallRequest request
...
-          raft.getPersistedSnapshotStore().newReceivedSnapshot(snapshotChunk.getSnapshotId());
+      try {
+        pendingSnapshot =
+            raft.getPersistedSnapshotStore().newReceivedSnapshot(snapshotChunk.getSnapshotId());
+      } catch (final SnapshotAlreadyExistsException snapshotAlreadyExists) {
+        // This should not happen because we previously check for the latest snapshot. But, if it
+        // happens, instead of crashing raft thread, we respond with success because we already have
+        // the snapshot.
+        return CompletableFuture.completedFuture(
+            logResponse(InstallResponse.builder().withStatus(RaftResponse.Status.OK).build()));
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:199]: ❓ 🧪 Can we have a test for such? That if we send multiple times the same install request that we get immediately an success for example ? 🤔

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java [hunk 2]
```diff
@@ -1256,9 +1256,12 @@ public PersistedSnapshot getCurrentSnapshot() {
...
-  public void setCurrentSnapshot(final PersistedSnapshot snapshot) {
+  public void updateCurrentSnapshot() {
     checkThread();
-    currentSnapshot = snapshot;
+    // Get the latest snapshot from snapshot store because it might have been updated already before
+    // this listener is executed
+    currentSnapshot = persistedSnapshotStore.getLatestSnapshot().orElse(null);
+    log.trace("Set currentSnapshot to {}", currentSnapshot);
     logCompactor.compactFromSnapshots(persistedSnapshotStore);
   }
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:1266]: ❓ Wdyt this can we test this behavior or do you think it is enough with the RaftRandomized? I guess it is not easy to verify.

**Review by ChrisKujawa — APPROVED** [review]
Great catch and analysis @deepthidevaki thanks ! 🚀

File: atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java (hunk 1 above)
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:199]: This case would be covered randomized tests for liveness, right? Eventually, the follower that received the snapshot also receives the following log entries. If it doesn't liveness test fails.
We can add a test in `PassiveRoleTest`, but I'm not keen on that because we have to mock everything to be able to test a small thing.

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java (hunk 2 above)
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:1266]: It is not easy to simulate the scenario outside the randomized tests. I would say Randomized tests are enough. It was quite easy to reproduce this failure.

**Comment by deepthidevaki** [comment]
Failed to download docker image.

bors retry
