### PR TITLE
Exporter template creation warns if already exists

### LINKED ISSUE #24251: Camunda Exporter: Templates shouldn't recreated - when existing
## Description

We see [errors](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%224f98469f-8a58-4be7-9f5e-38220b719d3b-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.project_id%3D%22camunda-saas-int%22%0Aresource.labels.cluster_name%3D%22worker-3%22;pinnedLogId=2024-10-30T13:45:00.051221309Z%2Fykht9q7hc1nx5jw7;cursorTimestamp=2024-10-30T13:45:00.051221309Z;startTime=2024-10-30T13:15:26.235Z;endTime=2024-10-30T14:15:26.235Z?project=camunda-saas-int) on INT 

```
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/indices.put_index_template] failed: [illegal_argument_exception] index template [operate-decision-instance-8.3.0_template] already exists
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.putIndexTemplate(ElasticsearchIndicesClient.java:1560) ~[elasticsearch-java-8.13.4.jar:?]
	at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.createIndexTemplate(ElasticsearchEngineClient.java:84) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.lambda$initialiseIndexTemplates$3(SchemaManager.java:96) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.exporter.schema.SchemaManager.initialiseIndexTemplates(SchemaManager.java:94) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.initialiseResources(SchemaManager.java:63) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.startup(SchemaManager.java:49) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.CamundaExporter.open(CamundaExporter.java:102) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$openExporter$0(ExporterContainer.java:118) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:59) ~[zeebe-util-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:35) ~[zeebe-util-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.openExporter(ExporterContainer.java:117) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$startActiveExportingMode$16(ExporterDirector.java:532) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:85) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]

```

This can have multiple reasons:

 1. Race condition: Importer is currently running and still maintaining the schema as well 
     2. as start it doesn't exist
     3. exporter checks for templates
     4. importer creates templates
     5. then exporter tries and fails
 3. Race condition: Different partitions might create the same schema
   4. See slack https://camunda.slack.com/archives/C06F0GLJNFM/p1730369317470839?thread_ts=1730360930.291949&cid=C06F0GLJNFM
 5. Bug: We might have a bug in the template resolvment see https://github.com/camunda/camunda/issues/24243 

In any case we should handle the template creation more gracefully. If the reason for an error is that the template exists, we could simply ignore it.

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

Instead of an `ERROR` log and throwing an exception warns if trying to create an already existing template.

Opensearch does not require the feature manually implemented as `putIndexTemplate` requests are already idempotent.

## Related issues

closes #24251

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java [hunk 1]
```diff
@@ -84,6 +84,15 @@ public void createIndexTemplate(
       client.indices().putIndexTemplate(request);
       LOG.debug("Template [{}] was successfully created", templateDescriptor.getTemplateName());
     } catch (final IOException | ElasticsearchException e) {
+      if (e.getMessage()
+          .contains(
+              String.format(
+                  "index template [%s] already exists", templateDescriptor.getTemplateName()))) {
+        LOG.warn(
+            "Did not create index template [{}] as it already exists",
+            templateDescriptor.getTemplateName());
```
Comment (Zelldon) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java:93]: 💭 I'm still not sure whether this is really worth a warning. It is sort of expected that if I run Camunada with three partitions this will happen as we have no synchronization of who does the schema creation.

Comment (Zelldon) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java:93]: 🔧 I would like to see a clarification comment, why we think it is expected.

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/schema/ElasticsearchEngineClientIT.java [hunk 2]
```diff
@@ -101,6 +110,32 @@ void shouldCreateIndexTemplateCorrectly() throws IOException {
...
+            "/mappings.json");
+
+    final var settings = new IndexSettings();
+    elsEngineClient.createIndexTemplate(indexTemplate, settings, true);
+
+    // when
+    elsEngineClient.createIndexTemplate(indexTemplate, settings, true);
+
+    // then
+    assertThat(logWatcher.list.stream().map(ILoggingEvent::getFormattedMessage))
```
Comment (Zelldon) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/schema/ElasticsearchEngineClientIT.java:132]: ❓ We are not really checking whether this is a warning or?

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java (hunk 1 above)
Comment (EuroLew) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java:93]: I'd be fine with a debug as well

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java [hunk 3]
```diff
@@ -84,6 +84,18 @@ public void createIndexTemplate(
       client.indices().putIndexTemplate(request);
       LOG.debug("Template [{}] was successfully created", templateDescriptor.getTemplateName());
     } catch (final IOException | ElasticsearchException e) {
+      if (e.getMessage()
+          .contains(
+              String.format(
+                  "index template [%s] already exists", templateDescriptor.getTemplateName()))) {
```
Comment (mustafadagher) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java:90]: 💭 `ElasticsearchException` rather has an `error()` field that has a `type`. Is there one type that matches our failure here? would be better than matching the error message text

Comment (mustafadagher) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java:90]: 💭 Also similar to what we did for `opensearch`, elastic search client has a `existsTemplate()` endpoint. Would using that be cleaner?

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/schema/ElasticsearchEngineClientIT.java [hunk 4]
```diff
@@ -101,6 +112,36 @@ void shouldCreateIndexTemplateCorrectly() throws IOException {
...
+    // then
+    assertThat(logWatcher.list.stream())
+        .anyMatch(
+            log ->
+                log.getLevel().equals(Level.DEBUG)
+                    && log.getFormattedMessage()
+                        .contains(
+                            String.format(
+                                "Did not create index template [%s] as it already exists",
+                                indexTemplate.getTemplateName())));
```
Comment (mustafadagher) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/schema/ElasticsearchEngineClientIT.java:142]: 💭 I wouldn't assert a debug or a warning log to be honest. That should not be an expected behavior from an API that `it logs`. 
I'd rather assert here that it does not fail. And then in unit tests, and verify it doesn't call `putIndexTemplate` if `exists` returned true. (if we decided to implement it this way).

Logging is/should be hidden implementation details.

But I'd leave that up to you to decide

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java (hunk 3 above)
Comment (EuroLew) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java:90]: there is not feature parity regarding the clients that was why opensearch needed to manually implement the create logic. But elastic has a create field so no need.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java [hunk 5]
```diff
@@ -84,6 +84,18 @@ public void createIndexTemplate(
       client.indices().putIndexTemplate(request);
       LOG.debug("Template [{}] was successfully created", templateDescriptor.getTemplateName());
     } catch (final IOException | ElasticsearchException e) {
```
Comment (mustafadagher) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java:86]: 🔧 please split the `catch` clause to two if we have unique handling for one of exceptions.

**Review by mustafadagher — APPROVED** [review]
LGTM! 
I left only one more suggestion above
