### PR TITLE
Reset the diskSpaceAvailable flag correctly

### LINKED ISSUE #6232: No space left on device while receiving snapshot leads to unhealthy followers
**Describe the bug**
The following [error](https://console.cloud.google.com/errors/CKjN-8qmwNKc0wE?service=zeebe&time=P30D&project=camunda-cloud-240911&authuser=1) was reported `IOException: No space left on device`. This has been reported on other versions in the past (see https://github.com/zeebe-io/zeebe/issues/6038), but that problem was already resolved. 

The cluster producing this error was part of the [28-01-2020 game day](https://docs.google.com/document/d/1uX1N2jzvURhd8-L-uu90AqXO6KONRTY5btmdqNjMA3s/edit), for which the customer was triggering https://github.com/zeebe-io/zeebe/issues/6207. This lead to very a large snapshot state (>5GB).

The following morning, the error was reported, due to a short moment of not enough space left on pvc. Disk space recovered quickly, but 2 out of 3 brokers (the followers) have unhealthy partitions, that did not recover from this incident.

**Expected behavior**
Followers should become healthy again after disk space recovered

**Log/Stacktrace**
<details><summary>Logs diskspace</summary>
<p>

[link to logs](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%223ba69e11-1785-4b14-929d-7534736f175a-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-2%22;timeRange=2021-01-29T06:58:54.320Z%2F2021-01-29T08:58:54.320Z?authuser=1&project=camunda-cloud-240911)

```
Error 
2021-01-29 08:28:24.320 CET 
"Unexpected error on writing the received snapshot chunk SnapshotChunkImpl{snapshotId=602799-290-1611905228412-689596-689597, totalCount=671, chunkName='002801.sst', checksum=3874943013, snapshotChecksum=770344077} io.atomix.raft.snapshot.impl.SnapshotChunkImpl@25db7a97"
Debug
2021-01-29 08:28:24.346 CET
"Abort snapshot 602799-290-1611905228412-689596-689597 and mark it as invalid."
Debug
2021-01-29 08:28:24.346 CET
"DELETE dir /usr/local/zeebe/data/raft-partition/partitions/1/pending/602799-290-1611905228412-689596-689597-1"
Info
2021-01-29 08:28:25.236 CET
"Disk space available again. Current available 5464420352 bytes"
Debug
2021-01-29 08:28:25.238 CET
"Broker has disk space available again. All requests with topic subscription will be accepted."
Debug
2021-01-29 08:28:25.238 CET
"Broker has disk space available again. All requests with topic subscription will be accepted."
Debug
2021-01-29 08:28:25.238 CET
"Broker has disk space available again. All requests with topic deployment will be accepted."
```
</p>
</details>

<details><summary>Logs partition health</summary>
<p>

[link to logs](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%223ba69e11-1785-4b14-929d-7534736f175a-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Ahealthy;timeRange=2021-01-29T06:58:54.320Z%2F2021-01-29T08:58:54.320Z?authuser=1&project=camunda-cloud-240911)

```
Error
2021-01-29 08:27:41.572 CET
"ZeebePartition-1 failed, marking it as unhealthy"
Debug
2021-01-29 08:27:41.596 CET
"Detected unhealthy components. The current health status of components: {ZeebePartition-1=UNHEALTHY, Raft-1=HEALTHY}"
Error
2021-01-29 08:27:41.597 CET
"Partition-1 failed, marking it as unhealthy"
Debug
2021-01-29 08:27:41.598 CET
"Detected unhealthy components. The current health status of components: {Partition-1=UNHEALTHY}"
Debug
2021-01-29 08:27:41.756 CET
"Received metadata change from Broker 2, partitions {1=FOLLOWER}, terms {} and health {1=UNHEALTHY}."
```

</p>
</details>

<details><summary>Full Stacktrace</summary>
 <p>

```
java.io.IOException: No space left on device
at sun.nio.ch.FileDispatcherImpl.write0 (Native Method)
at sun.nio.ch.FileDispatcherImpl.write (Unknown Source)
at sun.nio.ch.IOUtil.writeFromNativeBuffer (Unknown Source)
at sun.nio.ch.IOUtil.write (Unknown Source)
at sun.nio.ch.FileChannelImpl.write (Unknown Source)
at java.nio.channels.Channels.writeFullyImpl (Unknown Source)
at java.nio.channels.Channels.writeFully (Unknown Source)
at java.nio.channels.Channels$1.write (Unknown Source)
at java.nio.file.Files.write (Unknown Source)
at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.writeReceivedSnapshotChunk (FileBasedReceivedSnapshot.java:175)
at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.apply (FileBasedReceivedSnapshot.java:132)
at io.zeebe.broker.system.partitions.impl.StateControllerImpl$ReplicationContext.apply (StateControllerImpl.java:343)
at io.zeebe.broker.system.partitions.impl.StateControllerImpl.consumeSnapshotChunk (StateControllerImpl.java:226)
at io.zeebe.broker.system.partitions.impl.StateReplication.lambda$consume$1 (StateReplication.java:70)
at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept (DefaultClusterCommunicationService.java:308)
at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept (DefaultClusterCommunicationService.java:297)
at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$3 (NettyMessagingService.java:186)
at java.util.concurrent.ThreadPoolExecutor.runWorker (Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (Unknown Source)
at java.lang.Thread.run (Unknown Source)
```

</p>
</details>

**Environment:**
 - Env: Camunda Cloud Int
 - Zeebe Version: 0.26.0

Relates to https://jira.camunda.com/browse/SUPPORT-17326

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

The flag was set incorrectly in the ZeebePartition. IMHO it shows again that we should try to avoid such, and instead have specific methods which set these flags/values, but I deferred this refactoring to keep the changes small.

_Example follow up refactoring:_

```java

  zeebePartitionHealth.setDiskSpaceAvailable(true);

  // could be:
  zeebePartitionHealth.notifyForDiskSpaceAvailable(); or zeebePartitionHealth.diskSpaceAvailable(); 
  // and
  zeebePartitionHealth.notifyForDiskSpaceUnavailable(); or zeebePartitionHealth.diskSpaceUnavailable();
```

Of course, we could still run into the issue that only one method is called, but we would detect it more easily if one method is not used (with IDE support).

## Related issues

closes https://github.com/camunda/zeebe/issues/6232

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java [hunk 1]
```diff
@@ -440,7 +440,7 @@ public void onDiskSpaceAvailable() {
     actor.call(
         () -> {
           context.setDiskSpaceAvailable(true);
-          zeebePartitionHealth.setDiskSpaceAvailable(false);
+          zeebePartitionHealth.setDiskSpaceAvailable(true);
```
Comment (deepthidevaki) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:443]: :+1: Good catch.

**Review by deepthidevaki — APPROVED** [review]
:100: Thanks for fixing it.

> instead have specific methods which set these flags/values, but I deferred this refactoring to keep the changes small.

:wrench: I think this would be a small change anyway. If you feel like it, please change it.
