### PR TITLE
fix: prevent 404 when showing flownode instance popover details

### LINKED ISSUE #38131: 404 on showing flownode instance popover details
### 

### 

### 

### 

### Description

The popover that normally shows the details of the instance is broken. Fetching the data fails with a  404.

Image

### Steps to reproduce

1. Run the latest snapshot version
2. Deploy any process
3. Navigate to Operate. Select any element in the model, or in the history tree.
4. Observe a 404

### Current behavior

No popover is shown. Variable do not load either.

### Expected behavior

The data is fetched and the popover is shown normally.

### Workaround

None

### Environment

SaaS & SM

### Version

- Component Version: Tried on `stable/8.8` branch

### Rootcause

The API call tries to fetch data from the `operate-event` index. This index contains no data.

Image

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tsedekey**
## Description

This PR implements a fix for [#38131](https://github.com/camunda/camunda/issues/38131), which caused a 404 error when attempting to retrieve flow node instance popover metadata in certain scenarios (e.g., when the event index no longer holds data for certain elements like user tasks).

Key Fix Details:
	•	We are no longer retrieving job-related data from the Operate event index.
	•	Instead, job metadata (e.g. type, retries, worker, etc.) is now fetched from the Operate job index, via a newly introduced JobReader.
	•	The event index is now only queried when the flow node element is of type message, to retrieve the messageName and correlationKey.

This change prevents failures that previously occurred due to missing data in the event index for elements like user tasks.

Note:
I intentionally avoided making structural or architectural changes to the existing code. While the current implementation could benefit from a more maintainable pattern (e.g., a builder strategy based on element types), such a redesign was deemed unnecessary at this point — especially given that this logic is expected to be removed or refactored as part of the 8.9 release. This PR instead takes the minimal, non-invasive route to resolve the bug while preserving the current structure.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #38131

### CODE REVIEW

File: operate/webapp/src/main/java/io/camunda/operate/webapp/rest/dto/metadata/FlowNodeInstanceMetadata.java [hunk 1]
```diff
@@ -10,16 +10,9 @@
...
-import com.fasterxml.jackson.annotation.JsonTypeInfo;
-import com.fasterxml.jackson.annotation.JsonTypeInfo.As;
 import io.camunda.webapps.schema.entities.flownode.FlowNodeType;
 import java.time.OffsetDateTime;
 
-@JsonTypeInfo(
-    use = JsonTypeInfo.Id.NAME,
-    include = As.PROPERTY,
-    property = "flowNodeType",
-    defaultImpl = FlowNodeInstanceMetadataDto.class)
```
Comment (tsedekey) [inline operate/webapp/src/main/java/io/camunda/operate/webapp/rest/dto/metadata/FlowNodeInstanceMetadata.java:22]: I removed the above because it was already defined in line 33, and this was causing duplicate entries in the JSON output.

File: operate/webapp/src/test/java/io/camunda/operate/webapp/rest/FlowNodeInstanceMetadataBuilderTest.java [hunk 2]
```diff
@@ -46,14 +48,19 @@ class FlowNodeInstanceMetadataBuilderTest {
   @Mock private DecisionInstanceReader decisionInstanceReader;
   @Mock private EventReader eventReader;
   @Mock private UserTaskReader userTaskReader;
+  @Mock private ElasticsearchJobReader elasticsearchJobReader;
```
Comment (kristinkomschow) [inline operate/webapp/src/test/java/io/camunda/operate/webapp/rest/FlowNodeInstanceMetadataBuilderTest.java]: We should use the `io.camunda.operate.webapp.reader.JobReader` interface here rather than the elasticsearch implementation

**Review by kristinkomschow — APPROVED** [review]
Pre-approving because I only have one small comment.

Thank you!
