### PR TITLE
Configure record filter for metrics exporter

### LINKED ISSUE #9240: MetricsExporter does not configure a record filter
**Describe the bug**

The [MetricsExporter](https://github.com/camunda/zeebe/blob/8.0.0/broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporter.java#L27) does not override the [configure](https://github.com/camunda/zeebe/blob/8.0.0/exporter-api/src/main/java/io/camunda/zeebe/exporter/api/Exporter.java#L43) method. This method allows to set a filter for which records are available to export. Since the MetricsExporter only exports records of a few value types (i.e. JOB, JOB_BATCH, PROCESS_INSTANCE), it unnecessarily reads the record values of all other records.

This can completely halt exporting on a partition when combined with #6442. 

**To Reproduce**

- configure the MetricsExporter for the broker
- run the broker
- deploy a very large process with mistakes that lead to zeebe rejecting the deployment with validation errors
- note that the exporter stops making progress
- note an increase in CPU because it keeps trying to re-read the record value indefinitely

**Expected behavior**

The metrics exporter should be configured in such a way that only those records that it wants to export are actually read from the log by the exporter director.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalArgumentException: invalid offset: -31808
	at org.agrona.concurrent.UnsafeBuffer.boundsCheckWrap(UnsafeBuffer.java:2425) ~[agrona-1.15.0.jar:1.15.0]
	at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:277) ~[agrona-1.15.0.jar:1.15.0]
	at io.camunda.zeebe.msgpack.spec.MsgPackReader.wrap(MsgPackReader.java:49) ~[zeebe-msgpack-core-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:30) ~[zeebe-msgpack-value-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.logstreams.impl.log.LoggedEventImpl.readValue(LoggedEventImpl.java:135) ~[zeebe-logstreams-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.RecordValues.readRecordValue(RecordValues.java:35) ~[zeebe-workflow-engine-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.wrap(ExporterDirector.java:489) ~[zeebe-broker-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$exportEvent$9(ExporterDirector.java:391) ~[zeebe-broker-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.0.jar:8.0.0]
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.0
- Configuration: MetricsExporter

### PR DESCRIPTION
**Pull request by korthout**
## Description

Configures a record filter for the Metrics exporter.

## Related issues

closes #9240 
relates to #6442 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by korthout** [comment]
This should also be backported to 1.3, but due to Java 17 language level usage, I already know that the bot will fail. I'll make sure to backport manually.

File: .gitignore [hunk 1]
```diff
@@ -30,6 +30,7 @@ faces-config.NavData
 *.lock.db
 .cache-main
 .cache-tests
+.jqwik-database
```
Comment (npepinpe) [inline .gitignore:33]: :sunglasses: nice, I run into this from time to time

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+import org.slf4j.Logger;
+
+class MetricsExporterTest {
+
+  @Test
+  void shouldObserveJobLifetime() {
+    // given
+    final var metrics = new ExecutionLatencyMetrics();
+    final var exporter = new MetricsExporter(metrics);
+    exporter.open(new FakeController());
```
Comment (npepinpe) [inline broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:38]: :wrench: We have a new module, `exporter-test`, which provides test implementations of the exporter API.

Comment (npepinpe) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:38]: It's not yet used, but you can see how it will be used here: https://github.com/camunda/zeebe/blob/1259bb86847c8ede5c987bd478df5c6110200c55/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterTest.java

(feel free to improve the API of course :slightly_smiling_face:)

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java [hunk 3]
```diff
@@ -0,0 +1,173 @@
...
+    assertThat(metrics.getJobLifeTime().collect())
+        .flatMap(x -> x.samples)
+        .describedAs("Expected no metrics to be recorded at start of test")
+        .isEmpty();
+
+    // when
+    exporter.export(
+        ImmutableRecord.builder()
```
Comment (npepinpe) [inline broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:46]: :muscle: I like it

File: broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/ExecutionLatencyMetrics.java [hunk 4]
```diff
@@ -56,6 +56,10 @@ public void observeJobActivationTime(
         .observe(latencyInSeconds(creationTimeMs, activationTimeMs));
   }
 
+  public Histogram getJobLifeTime() {
```
Comment (npepinpe) [inline broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/ExecutionLatencyMetrics.java:59]: :thought_balloon: I'm not sure about exposing these just for testing. I wonder if there isn't a better way :thinking: I don't have an alternative though, just thinking out loud.

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java [hunk 5]
```diff
@@ -0,0 +1,173 @@
...
+      // don't care
+      return null;
+    }
+  }
+
+  @Nested
+  @DisplayName("MetricsExporter should configure a Filter")
+  class FilterTest {
+
+    static Stream<TypeCombination> acceptedCombinations() {
```
Comment (npepinpe) [inline broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:89]: :wrench: Clever :slightly_smiling_face: Maybe too clever? :wink: The requirements, I think, are: only events, and then only JOB, JOB_BATCH, PROCESS_INSTANCE? So we could rewrite this as one test checking that only EVENT is accepted (regardless of value type), and one test that only the 3 value types are accepted.

Or is it because we don't want to assume the implementation of `RecordFilter` (i.e. that it treats RecordType and ValueType independently), so we want to test the combinations? Its interface already seem to imply they are treated independently, after all.

**Review by npepinpe — APPROVED** [review]
Looks good! I had some suggestions, no real blockers. Might be interesting to take a look at this issue in the future, since it would also help here: https://github.com/camunda/zeebe/issues/7529

**Comment by npepinpe** [comment]
Small reviews call for many comments :smile:

File: .gitignore (hunk 1 above)
Comment (korthout) [reply .gitignore:33]: Yeah thought about putting it in a separate PR, but just wanted to get this out the door (and backported)

File: broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/ExecutionLatencyMetrics.java (hunk 4 above)
Comment (korthout) [reply broker/src/main/java/io/camunda/zeebe/broker/exporter/metrics/ExecutionLatencyMetrics.java:59]: 💭 Instead of exposing the internals, we could replace it with a method that reads the recorded data so far. But that's also only useful for testing. So I don't see a real benefit to it. Alternatively, we could pass in the histogram through construction injection, but that's practically the same as this getter. I'm not sure how to really improve this

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java (hunk 5 above)
Comment (korthout) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:89]: Ah, well originally I wasn't aware of how the record filter worked. I assumed it would take some combination of record type, valuetype, and intent to filter a single record, but instead it offers this strange inflexible configuration. Apparently, you can't say: only export JOB events and JOB_BATCH commands. I wrote the test playing around with this concept and thought: If we happen to change the exporter API, then this test at least already checks for the correct combinations.

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java (hunk 3 above)
Comment (korthout) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:46]: Felt great to use it 🚀

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java (hunk 2 above)
Comment (korthout) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:38]: Awesome, I missed that 💯  I'll give it a try

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java (hunk 5 above)
Comment (npepinpe) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:89]: I think it makes sense to allow filtering by intent eventually, but hadn't really spent time thinking about more fine-grained control (e.g. allow JOB commands, but not process commands). I'll let the automation team decide here :slightly_smiling_face:

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java (hunk 2 above)
Comment (korthout) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:38]: Oh darn, that is all spike code. @npepinpe Any chance we're seeing that code in `main` before the next patch goes out?

Comment (npepinpe) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:38]: The test implementations have already been merged, you should be able to use it.

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java (hunk 5 above)
Comment (korthout) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java:89]: I don't necessarily need it now, but I think it makes sense to have this eventually. This test is at least ready for it when it does come 😆

**Comment by npepinpe** [comment]
As we're on the topic, it would be cool if you consider bringing up https://github.com/camunda/zeebe/issues/7529 for your next triage :+1:

File: broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java [hunk 6]
```diff
@@ -0,0 +1,173 @@
...
+    }
+
+    @ParameterizedTest
+    @DisplayName("accepting records of specific RecordType and ValueType")
+    @MethodSource("acceptedCombinations")
+    void shouldConfigureFilterAccepting(final TypeCombination combination) throws Exception {
+      // given
+      final var recordType = combination.recordType();
+      final var valueType = combination.valueType();
+      final var context = new FilterSpyingContext();
```
[the remark this answers is not in the document]
Comment (korthout) [reply broker/src/test/java/io/camunda/zeebe/broker/exporter/metrics/MetricsExporterTest.java]: I really like it 👍 Thanks for the tip

**Comment by korthout** [comment]
Thanks for the nice review @npepinpe 

bors merge

**Comment by Zelldon** [comment]
> ￼ Can I argue that the Exporter API is/should be a responsibility of the Zeebe DPT? It is part of the log stream capabilities of the platform and not really a process automation topic. Sure, we use it to export process-related data, but the API that is built on should probably be part of the platform.

:no_good: 

DPT doesn't care what is inside the logstream. It is the output of your application, which is written to the logstream, in your protocol format. I think it is discussable whether you have to maintain it or the teams which consume it (operate/optimize), but I don't think that we (DPT) should maintain it.

I guess we should clarify this topic, somewhere, somewhen.

**Comment by korthout** [comment]
>DPT doesn't care what is inside the logstream. It is the output of your application, which is written to the logstream, in your protocol format. I think it is discussable whether you have to maintain it or the teams which consume it (operate/optimize), but I don't think that we (DPT) should maintain it.

@Zelldon I think we talk about different things. I understand that the content of what is exported is not of interest to you. It is only interesting to us and the consumers, but the ability to export whatever it is that lives on the log stream should be part of the platform right? So the exporter API is part of the platform right? I'm not talking about the different exporters that are implemented, but specifically about the exporter API.

**Comment by Zelldon** [comment]
Ok yeah thanks, then I mistunderstood your message. I agree. This is I think goes a bit into the direction
what we have touched a bit in the engine abstraction draft document.

**Comment by npepinpe** [comment]
I'm not sure I fully agree about the exporter API - it's not about getting the RAFT log out, it's about getting specifically the engine log out, it's very coupled to the engine's protocol, after all. It's all about getting data out of the engine. Anyway, we can discuss that some other place/time :smile:

**Comment by Zelldon** [comment]
I would agree in regards to the ExporterDirector which is similar to the streamprocessor.
