### PR TITLE
fix: handle assignment/unassignment/completion notification for lack of permissions

### LINKED ISSUE #37230: When user has no access to update userTask no message is displayed in the UI
### 

### 

### 

### 

### Description

With **Authorization enabled**, when a user **does not have `updateUserTasks` permissions**, assigning, unassigning, or completing a user task in the **V2 Tasklist UI** does **not display any message**. However, the **V1 API** correctly shows a **“Service is not reachable”** message in the same scenario.

### Steps to reproduce

1. Start the Tasklist on SaaS/SM using the **V2 API**.
2. Enable **Authorization**.
3. Deploy and run a process containing a **user task**.
4. Open **Identity** and go to the **Authorizations** tab.
5. Select the **Process Definition**.
6. Remove **admin user** permissions.
7. Create a new authorization for the target user, granting only the following permissions:

   * `CREATE_PROCESS_INSTANCE`
   * `DELETE_PROCESS_INSTANCE`
   * `READ_PROCESS_DEFINITION`
   * `READ_PROCESS_INSTANCE`
   * `READ_USER_TASK`
8. Navigate to the **Tasklist**.
9. Attempt any action on the **user task** (assign, unassign, or complete).

### Current behavior

* When assigning or unassigning a task, the UI **keeps loading indefinitely**, even when switching to another task.
* When completing a task, a **“completion failed”** message appears in the **bottom bar**, but **no banner is displayed**, unlike in V1.

https://github.com/user-attachments/assets/e49bac4d-4da3-4f06-8955-5dc779024e2f

https://github.com/user-attachments/assets/53ed5689-8bde-4316-aa12-7c76fdf6759e

### Expected behavior

* When assigning or unassigning a task without sufficient permissions, the UI should **display an error message** instead of loading indefinitely.
* When completing a task without sufficient permissions, the UI should **show a visible banner** (similar to V1) indicating that the action failed.

https://github.com/user-attachments/assets/c26d550b-1dcd-493e-948d-f5914a972133

### Environment

SaaS & SM

### Version

- Component Version: SNAPSHOT

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by vsgoulart**
## Description

Before we handled lack of permission notification with 401 some time ago we changed it to 403. This PR fixes that

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #37230

### CODE REVIEW

File: tasklist/client/src/v2/TaskDetailsLayout/AssignButton/index.tsx [hunk 1]
```diff
@@ -98,16 +98,23 @@ const AssignButton: React.FC<Props> = ({
       if (success && parsedError.variant === 'failed-response') {
         const errorData = await parsedError.response.json();
```
Comment (juliasaienko) [inline tasklist/client/src/v2/TaskDetailsLayout/AssignButton/index.tsx]: It seems that `errorData` is parsed but never used. Should it be called inside `else` branch when its actually needed

File: tasklist/client/src/v2/TaskDetailsLayout/AssignButton/index.tsx [hunk 2]
```diff
@@ -98,16 +98,23 @@ const AssignButton: React.FC<Props> = ({
...
-          kind: 'error',
-          title: t('taskDetailsTaskAssignmentError'),
-          subtitle: parseDenialReason(errorData, 'assignment'),
-          isDismissable: true,
-        });
-
-        if (errorData.title !== 'DEADLINE_EXCEEDED') {
-          setAssignmentStatus('off');
+        if (parsedError.response.status === 403) {
+          notificationsStore.displayNotification({
```
Comment (juliasaienko) [inline tasklist/client/src/v2/TaskDetailsLayout/AssignButton/index.tsx:100]: I've noticed that this pattern repeats in several places. Does it make sense to extract the message calculation to a helper function(I believe we have something similar in Operate)?

**Review by juliasaienko — APPROVED** [review]
Looks good. I've added two small comments

File: tasklist/client/src/v2/TaskDetailsLayout/AssignButton/index.tsx (hunk 2 above)
Comment (vsgoulart) [reply tasklist/client/src/v2/TaskDetailsLayout/AssignButton/index.tsx:100]: I'll handle this with the frontend reunification
