### PR TITLE
Fix flaky MultiPartitionDeploymentLifecycleTest

### LINKED ISSUE #9964: Flaky `MultiPartitionDeploymentLifecycleTest.shouldTestLifecycle`
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? More than once
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  io.camunda.zeebe.engine.processing.deployment.MultiPartitionDeploymentLifecycleTest.shouldTestLifecycle  Time elapsed: 0.601 s  <<< FAILURE!
java.lang.AssertionError: 

Actual and expected have the same elements but not in the same order, at index 6 actual element was:
  (COMPLETED, EVENT)
whereas expected element was:
  (COMPLETE, COMMAND)

at io.camunda.zeebe.engine.processing.deployment.MultiPartitionDeploymentLifecycleTest.shouldTestLifecycle(MultiPartitionDeploymentLifecycleTest.java:59)
</pre>
</details>

**Hypotheses**

The ordering of events from multiple deployment distribution attempts is not guaranteed, the tests seems to be too strict.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Test was flaky because it was asserted that the COMPLETE commands and COMPLETED events were written in order.
This is not always as the case. The COMPLETE commands are a result of partition 2 and 3 sending the command to partition 1. There is no guarantee that partition 1 will first receive both commands before it starts processing them.
As long as we assert that we receive the COMPLETE command of partition X before the COMPLETED event of partition X the test should be accurate without being flaky.

## Related issues

closes #9964 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@pihme Just pinging you to make sure you've seen this PR

**Comment by pihme** [comment]
Thanks for the reminder. I wasn't ware of it.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java [hunk 1]
```diff
@@ -53,20 +54,32 @@ public void shouldTestLifecycle() {
     final var deploymentPartitionRecords =
         RecordingExporter.records().withPartitionId(1).limit(10).collect(Collectors.toList());
 
-    assertThat(deploymentPartitionRecords)
+    assertThat(deploymentPartitionRecords).hasSize(10);
```
Comment (pihme) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java:57]: :thinking: Not sure this is a useful assertion. Could change with implementation details. Same with the limit call above

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java [hunk 2]
```diff
@@ -53,20 +54,32 @@ public void shouldTestLifecycle() {
...
+            Record::getRecordType,
+            r -> ((DeploymentDistributionRecordValue) r.getValue()).getPartitionId())
+        .containsSubsequence(
+            tuple(DeploymentDistributionIntent.COMPLETE, RecordType.COMMAND, 2),
+            tuple(DeploymentDistributionIntent.COMPLETED, RecordType.EVENT, 2))
+        .containsSubsequence(
+            tuple(DeploymentDistributionIntent.COMPLETE, RecordType.COMMAND, 3),
+            tuple(DeploymentDistributionIntent.COMPLETED, RecordType.EVENT, 3));
+
+    assertThat(deploymentPartitionRecords.subList(9, deploymentPartitionRecords.size()))
```
Comment (pihme) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java:80]: :x: Please assert 
`containsSequence( COMPLETED on partition 2, FULLY_DISTRIBUTED)`
`containsSequence( COMPLETED on partition 3, FULLY_DISTRIBUTED)`

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java [hunk 3]
```diff
@@ -53,20 +54,32 @@ public void shouldTestLifecycle() {
...
             tuple(DeploymentDistributionIntent.DISTRIBUTING, RecordType.EVENT),
-            tuple(DeploymentDistributionIntent.DISTRIBUTING, RecordType.EVENT),
-            tuple(DeploymentDistributionIntent.COMPLETE, RecordType.COMMAND),
-            tuple(DeploymentDistributionIntent.COMPLETE, RecordType.COMMAND),
-            tuple(DeploymentDistributionIntent.COMPLETED, RecordType.EVENT),
-            tuple(DeploymentDistributionIntent.COMPLETED, RecordType.EVENT),
-            tuple(DeploymentIntent.FULLY_DISTRIBUTED, RecordType.EVENT));
+            tuple(DeploymentDistributionIntent.DISTRIBUTING, RecordType.EVENT));
+
+    assertThat(deploymentPartitionRecords.subList(5, 9))
```
Comment (pihme) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java:68]: Again hard coded index values

**Review by pihme — CHANGES_REQUESTED** [review]
Great improvement, but I think it can be improved further

**Comment by pihme** [comment]
Oh, and maybe we want to backport this

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java (hunk 2 above)
Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java:80]: I don't think we can do this. The `FULLY_DISTRIBUTED` it not written once per partition. It is only written once on partition 1 when we have received all the `COMPLETE` commands from the other partitions, which is already asserted with the previous assertion.

Comment (pihme) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java:80]: Couldn't this work?
```
        .containsSubsequence(
            tuple(DeploymentDistributionIntent.COMPLETE, RecordType.COMMAND, 2),
            tuple(DeploymentDistributionIntent.COMPLETED, RecordType.EVENT, 2)).
            tuple(DeploymentIntent.FULLY_DISTRIBUTED, RecordType.EVENT, 1));
        .containsSubsequence(
            tuple(DeploymentDistributionIntent.COMPLETE, RecordType.COMMAND, 3),
            tuple(DeploymentDistributionIntent.COMPLETED, RecordType.EVENT, 3)),
            tuple(DeploymentIntent.FULLY_DISTRIBUTED, RecordType.EVENT, 1));
```

Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java]: I have done something similar now 🙂

**Comment by remcowesterhoud** [comment]
@pihme I have removed all the hardcoded indexes, please have another look!

**Comment by remcowesterhoud** [comment]
We can backport them. The test wasn't flaky in previous versions though, as it was introduced with the new inter partition command sending.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java [hunk 4]
```diff
@@ -50,29 +51,52 @@ public void shouldTestLifecycle() {
...
+        .extracting(
+            Record::getIntent,
+            Record::getRecordType,
+            r -> {
+              // We want to verify the partition id where the deployment was distributing to and
+              // where it was completed. Since only the DeploymentDistribution records have a value
+              // that contains the partition id, we use the partition id the record was written on
+              // for the other records. It should be noted that the DeploymentDistribution records
+              // are also written on partition 1!
+              try {
```
Comment (pihme) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/MultiPartitionDeploymentLifecycleTest.java:67]: :wrench: This could also be an instanceof check instead of an exception

**Review by pihme — APPROVED** [review]
lgtm :tada:

**Comment by remcowesterhoud** [comment]
bors merge
