### PR TITLE
Return correct status code when a user has insufficient permissions

### LINKED ISSUE #26010: Missing permissions should return status code 403 Forbidden
When a request is rejected because of missing permissions, the response status code is a 401 Unauthorized. This is incorrect, a 401 should indicate missing or invalid authentication. Instead we should return status code 403 Forbidden to indicate that authentication worked but the entity does not have the required permissions.

The root cause is that `RejectionType.UNAUTHORIZED` is used too broadly. When we find valid authentication details in a request but not the required permission we should return a new `RejectionType.FORBIDDEN`. The `RestErrorMapper` needs to be extended to map this to a 403.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

This PR changes the HTTP status codes and gRPC error codes from unauthorized to forbidden if there are insufficients permissions. It contains some refactoring to make the error messages more generic instead of handling them in every processor individually.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #26010

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java [hunk 1]
```diff
@@ -349,22 +358,30 @@ public Set<String> getResourceIds() {
     public String getTenantId() {
       return tenantId;
     }
+
+    public String getForbiddenErrorMessage() {
+      return hasAddedResourceIds
```
Comment (lenaschoenburg) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java:363]: :upside_down_face: Could also check that `resourceIds` is not just the wildcard. Perhaps a bit less brittle than the boolean change flag.

File: zeebe/protocol/src/main/resources/protocol.xml [hunk 2]
```diff
@@ -86,6 +86,7 @@
       <validValue name="PROCESSING_ERROR">4</validValue>
       <validValue name="EXCEEDED_BATCH_RECORD_SIZE">5</validValue>
       <validValue name="UNAUTHORIZED">6</validValue>
+      <validValue name="FORBIDDEN">7</validValue>
```
Comment (lenaschoenburg) [inline zeebe/protocol/src/main/resources/protocol.xml:89]: :thought_balloon: In theory we could rename `UNAUTHORIZED` to `UNAUTHENTICATED`, right? Because that's what it actually means now.

**Review by lenaschoenburg — APPROVED** [review]
