### PR TITLE
fix: increment totalOperationsCount correctly #35455

### LINKED ISSUE #35455: operationsTotalCount should be incremented correctly on small chunkSizes
The BatchOperationChunkCreationHandler in CamundaExporter uses an update script to update the operationsTotalCount.

When the chunkSize is set to a small value, the handler will be called with the same entity multiple times before it is flushed. In that case, the total count update is wrong because it is not locally incremented but overridden with the latest value from the last record.

### PR DESCRIPTION
**Pull request by stoerti**
## Description

Fixes a bug where the totalOperationsCount was not updated correctly when the item chunks are very small and the entity was updated multiple times before flushing.

## Related issues

closes #35455

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java [hunk 1]
```diff
@@ -72,7 +72,8 @@ public BatchOperationEntity createNewEntity(final String id) {
   public void updateEntity(
       final Record<BatchOperationChunkRecordValue> record, final BatchOperationEntity entity) {
     // set to just the size of the current chunk. delta update is performed in the update script
-    entity.setOperationsTotalCount(record.getValue().getItems().size());
+    entity.setOperationsTotalCount(
+        entity.getOperationsTotalCount() + record.getValue().getItems().size());
```
Comment (mustafadagher) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java:76]: ❓ do we have test coverage for this in our e2e (acceptance) tests?

**Review by mustafadagher — APPROVED** [review]
