### PR TITLE
Ensure raft storage lock file is update atomically

### LINKED ISSUE #10681: Ensure RaftStore lock files are created and updated atomically
**Describe the bug**

We observed that on startup the lock file is empty, and this failed the startup of the partition with "Failed to acquire lock". 
Possible reasons:
1. Pod crashed after creating the lock file, but before writing the lock info
2. Lock file was created and updated, but it was not flushed to disk before the pod restarted.

Workaround in this case is to delete the lock file and restart the pod. This is risky, because lock file exists to ensure that the directories are not shared by multiple pods. If we workaround it, we have to manually check if everything is configured correctly.

**Expected behavior**
The lock is not empty.  Either lock file exists and have contents, or lock file does not exist. 

**Environment:**
- Zeebe Version: 8.1.0

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Previously the file creation and updating the contents were not done atomically. Moreover the content of the files were not flushed immediately. Because of this, if the pod restarts there is a chance the lock file exists but it is empty. As a result, a new lock cannot be acquired and the partition startup fails. 

To fix this, we first the write to a temporary file with "SYNC" option and then move the file atomically to the actual lock file.

Existing tests are refactored. No new test is added to verify this, as it is difficult to simulate crashes while acquiring the lock.

## Related issues

closes #10681 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java [hunk 1]
```diff
@@ -110,17 +112,30 @@ public String prefix() {
...
+        Files.writeString(
+            tempLockFile.toPath(),
+            id,
+            StandardOpenOption.CREATE,
+            StandardOpenOption.TRUNCATE_EXISTING,
+            StandardOpenOption.WRITE,
+            StandardOpenOption.SYNC);
+
+        // If two nodes tries to acquire lock, move will fail with FileAlreadyExistsException
+        FileUtil.moveDurably(
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java:129]: :question: I can remember a discussion that this was only supported on some environments wasn't that something? Like only linux or? Is this an issue?

File: atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java [hunk 2]
```diff
@@ -110,17 +112,30 @@ public String prefix() {
...
+            tempLockFile.toPath(), lockFile.toPath(), StandardCopyOption.ATOMIC_MOVE);
       }
+      // Read the lock file again to ensure that contents matches the local id
+      final String lock = Files.readString(lockFile.toPath());
+      return lock != null && lock.equals(id);
+    } catch (final FileAlreadyExistsException e) {
+      return false;
     } catch (final IOException e) {
-      throw new StorageException("Failed to acquire storage lock");
+      throw new StorageException("Failed to acquire storage lock", e);
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java:138]: :+1:

File: atomix/cluster/src/test/java/io/atomix/raft/storage/RaftStorageTest.java [hunk 3]
```diff
@@ -54,49 +48,54 @@ public void testCustomConfiguration() throws Exception {
...
     final RaftStorage storage2 =
         RaftStorage.builder().withDirectory(PATH.toFile()).withPrefix("test").build();
 
-    assertFalse(storage2.lock("b"));
+    // then
+    assertThat(storage2.lock("b")).isFalse();
+  }
+
+  @Test
+  public void canAcquireLockOnDirectoryLockedBySameNode() {
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/storage/RaftStorageTest.java:83]: :thought_balloon: Just as an idea regarding another test. If we would make the writing to a file injectable (via dependency injection) we could also fail the writing and write a test whether failing write doesn't lock the storage anymore.

**Review by ChrisKujawa — APPROVED** [review]
Thanks @deepthidevaki as always for the quick fix! Please consider my comments before merging :)

File: atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java (hunk 1 above)
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java:129]: Do you know what exactly was the problem? 

Flushing the parent directory does not work in windows. But according to what is documented in `FileUtil`, this is ok.

File: atomix/cluster/src/test/java/io/atomix/raft/storage/RaftStorageTest.java (hunk 3 above)
Comment (deepthidevaki) [reply atomix/cluster/src/test/java/io/atomix/raft/storage/RaftStorageTest.java:83]: :thinking: Ya. May be. I will pass it for now. It would be also good if we can inject a mock filesystem in which we can simulate all kinds of failure.

Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/raft/storage/RaftStorageTest.java:83]: Agree but then we shouldn't longer use Files class :) or at least some wrapper :)

Comment (deepthidevaki) [reply atomix/cluster/src/test/java/io/atomix/raft/storage/RaftStorageTest.java:83]: I think @npepinpe had look into to similar ideas for testing journal.

File: atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java (hunk 1 above)
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java:129]: We are using `FileUtil#moveDurably` in other places as well. So far no problems are reported. So I guess it should be ok. So I will merge this PR. If we see/know any problems later, let's tackle it then.

**Comment by deepthidevaki** [comment]
bors merge
