### PR TITLE
fix: identity: add context path handling in client

### LINKED ISSUE #37616: I cannot log out of the Identity UI with a non-root servlet context path
### 

### 

### 

### 

### Description

* When Identity is not running on the root context path, the logout button doesn't work (the logout request returns a 404)

Example:

* Servlet context path is `/foo`, i.e. Identity UI is accessible at `http://localhost:8080/foo/identity/`
* The UI requests the logout at `http://localhost:8080/logout`, but it should be `http://localhost:8080/foo/logout`

### Steps to reproduce

1. Configure Identity to run in a non-root servlet path, e.g. with the application property `server.servlet.context-path: /foo` in a local setup; 
  * note that SaaS configures the servlet context path as the cluster id, so the issue occurs there, too
  * I'm still only putting Self-Managed into the environment here, since it's a bug that the logout button is displayed in SaaS (compare 8.7 and earlier)
3. Log into Identity
4. Click the logout button

### Current behavior

* Nothing happens in the UI
* The user remains logged in

### Expected behavior

* The user is logged out successfully
* In case of a basic auth setup, they are redirected to the login form

### Environment

SM

### Version

- 8.8

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

* Related issue: https://github.com/camunda/camunda/issues/36134

### PR DESCRIPTION
**Pull request by igpetrov**
## Description

Fixes context path handling at login and logout.

## Demo

Since I am not very familiar with this part, here's a demo how it works.

https://github.com/user-attachments/assets/64c53aee-18f1-4d25-8fea-3e15ae6651d5

## Related issues

closes #37616

### CODE REVIEW

**Comment by igpetrov** [comment]
Hey @OmranAbazid , I am not a front end engineer, so maybe you could give it a glance. Related to https://github.com/camunda/camunda/issues/37616.

**Comment by ThorbenLindhauer** [comment]
@igpetrov why did you decide on exposing the context path via the configuration controller? Compare for example the fix for how the [favicon is loaded including the context path](https://github.com/camunda/camunda/pull/36651). And how does it work at the moment in Operate, where the context path is correctly considered? We should implement this consistently between all webapps.

File: identity/client/src/pages/login/LoginPage.tsx [hunk 1]
```diff
@@ -169,8 +171,10 @@ export const LoginPage: React.FC = () => {
   });
 
   const redirectUrl = getRedirectUrl(location.search);
+  const contextPath = window.clientConfig?.contextPath ?? "";
   const onSuccess = useCallback(() => {
-    window.location.href = redirectUrl ?? `/identity${Paths.users()}`;
+    window.location.href =
+      redirectUrl ?? mergePathname(contextPath, `/identity${Paths.users()}`);
```
Comment (OmranAbazid) [inline identity/client/src/pages/login/LoginPage.tsx]: Why do you need the contextPath here?
would it be possible to just call the `getBasePathBeforeIdentity() + /identity${Paths.users()}`?
This way, we would not need `mergePathname` utility anymore. I guess you also do not need the backend logic to expose the contextPath.

**Comment by igpetrov** [comment]
Hi @ThorbenLindhauer @OmranAbazid 

The decision taking context path is coming from [Operate](https://github.com/camunda/camunda/blob/506973f5b22a99e1af090059d2ecce0cff9bcf66/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/ClientConfig.java#L45) and [Tasklist](https://github.com/camunda/camunda/blob/506973f5b22a99e1af090059d2ecce0cff9bcf66/tasklist/webapp/src/main/java/io/camunda/tasklist/webapp/rest/ClientConfig.java#L70) implementation.

Regarding the [favicon example](https://github.com/camunda/camunda/pull/36651), I am not sure we can replicate it easily with existing implementation, because context path in Thymeleaf from the example will resolve to servlet, and we somehow would need to inject that data to react. (1) If we were to maintain client config wrapper, as all other apps do, we'll need to rewrite that logic which I don't think is a good idea; (2) if we want to just pass context path as global variable - it is potentially possible but not sustainable.

File: identity/client/src/pages/login/LoginPage.tsx (hunk 1 above)
Comment (igpetrov) [reply identity/client/src/pages/login/LoginPage.tsx]: > Why do you need the contextPath here?

Because post-login redirect does not take into account context pass, and given `context-path=/foo`, I still get redirected to `localhost:8080/identity/users`.

> would it be possible to just call the getBasePathBeforeIdentity() + /identity${Paths.users()}?

I don't know, I am very far away from FE, but that is what I will try out right away. I thought, I would have visibility issue here but let me try.

> I guess you also do not need the backend logic to expose the contextPath

I answered it [here](https://github.com/camunda/camunda/pull/38278#issuecomment-3306076056) but I might be missing something. If you have suggestions that you sure will work out, I am happy to adapt.

**Comment by igpetrov** [comment]
@ThorbenLindhauer @OmranAbazid reusing `getBasePathBeforeIdentity` did the trick, so we don't need to expose context path, at least for now

**Comment by ThorbenLindhauer** [comment]
Thanks, looks meaningful to me. I'll leave the code review to Omran as it's now a frontend-only change.

File: identity/client/src/pages/login/LoginPage.tsx [hunk 2]
```diff
@@ -170,7 +171,8 @@ export const LoginPage: React.FC = () => {
 
   const redirectUrl = getRedirectUrl(location.search);
   const onSuccess = useCallback(() => {
-    window.location.href = redirectUrl ?? `/identity${Paths.users()}`;
+    window.location.href =
+      redirectUrl ?? getBasePathBeforeIdentity() + `/identity${Paths.users()}`;
```
Comment (OmranAbazid) [inline identity/client/src/pages/login/LoginPage.tsx]: Sorry that i asked for `getBasePathBeforeIdentity`. I just noticed that we have `getBaseUrl()` that we can use like this:
```suggestion
      redirectUrl ?? getBaseUrl() + Paths.users();
```

**Review by OmranAbazid — APPROVED** [review]
pre-approving

**Comment by igpetrov** [comment]
Hi @OmranAbazid, I applied suggested change. Could you please re-approve the PR?

**Review by OmranAbazid — APPROVED** [review]

**Comment by igpetrov** [comment]
Hi @ThorbenLindhauer , we do need to backport this onto 8.8, don't we?

**Comment by ThorbenLindhauer** [comment]
@igpetrov yes, correct
