### PR TITLE
Fix variable update formatting in Operate

### LINKED ISSUE #32439: Extra Backslashes Escaping Variable Values in Operate (Regression from 8.8)
### 

### 

### 

### 

### Description

When editing variable values in Operate on a SNAPSHOT generation cluster, the UI appends an additional `"\` on either side of the string. This behavior was not present in previous versions (up to and including 8.8 until last evening) and appears to be a regression introduced recently. This change is currently breaking automated regression tests that expect the previous behavior. The issue seems related to unintended double escaping of strings in the UI, which may cause confusion for users and developers alike.

### Steps to reproduce

1. Navigate to Operate on a SNAPSHOT generation cluster.
2. Edit an existing variable.
3. Observe that the updated value appears with extra backslashes and quotes.

### Current behavior

See the following recording:

https://github.com/user-attachments/assets/345dc295-72a7-4b5b-acd5-36ee0781ef9c

### Expected behavior

The variable should just be like this `"updatedVariable"`

### Environment

SaaS

### Version

- Component Version: Using a cluster with generation 8.8 Cross Component Test Suite

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Ensure that variable updates are done correctly in Operate.

This PR covers the following:
- Restores the previous variable update behavior in the Operate#UpdateVariableHandler.
- Extends the Operate compatibility tests with assertions on the expected Zeebe events. This ensures that Zeebe produces the same events, independently of Operate's compatibility mode.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

related to #32387
closes #32439

### CODE REVIEW

File: qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateAuthorizationIT.java [hunk 1]
```diff
@@ -52,7 +60,14 @@ public class NoCompatibilityModeOperateAuthorizationIT {
...
           .withBasicAuth()
-          .withProperty("camunda.operate.zeebe.compatibility.enabled", false);
+          .withAdditionalProperties(
+              Map.of(
+                  "camunda.operate.zeebe.compatibility.enabled",
+                  false,
+                  "camunda.operate.operationExecutor.executorEnabled",
+                  true))
+          .withExporter(
+              "recordingExporter", cfg -> cfg.setClassName(RecordingExporter.class.getName()));
```
[the remark this answers is not in the document]
Comment (ChrisKujawa) [reply qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateAuthorizationIT.java:70]: Hey @koevskinikola I was just reading over it, I miss something but can you confirm that `@MethodSource("provideUserAndResponseCode")` is actually working? 🤔


Because it doesn't use any annotations `@Authenticated` which might lead to that the respective user will not be created 🤔

[the remark this answers is not in the document]
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateAuthorizationIT.java:74]: 💡 I found the issue. The Operate `OperationExecutor` is started in the `StartupBean` class and this class is annotated with the `@Profile("!test")` annotation ([src](https://github.com/camunda/camunda/blob/0b0c1ee6094226aeb1283dec2848b28ad29f0dd6/operate/webapp/src/main/java/io/camunda/operate/webapp/StartupBean.java#L28)).

Unfortunately, the `TestCamundaApplication` extends the `TestSpringApplication`. which sets the `TEST` profile [here](https://github.com/camunda/camunda/blob/3271553fc9c935a05a8d4a47a3038eec17743a7b/zeebe/qa/util/src/main/java/io/camunda/zeebe/qa/util/cluster/TestSpringApplication.java#L66). As a result, the Operate and Tasklist `StartupBean` classes are not created, and the Operate  `OperationExecutor` is not started.

[the remark this answers is not in the document]
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateAuthorizationIT.java:74]: For a possible solution, we need to expand Operate's `StartupBean` @Profile("!test") annotation with an additional profile that will enable the creation of this bean during testing, ex.: `@Profile({"!test", "dev"})`.

Removing the `TEST` profile in the impacted test classes isn't a good solution since that way we disable the `TestElasticsearchSchemaManager`class (and similar test classes) which clean up the ES state.

Alternatively, we should move the executor start-up to a different class that isn't impacted by the `test` profile, but I'm not familiar with Operate's code to be sure where that class would be.

[the remark this answers is not in the document]
Comment (ChrisKujawa) [reply qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateAuthorizationIT.java:74]: You can also check how we do it with the schema managers for Operate and Tasklist (if thry still exist?) We had similar issue and extended them in the QA test module and referenced them in the test application.

**Comment by koevskinikola** [comment]
Hey @ThorbenLindhauer, do you have some time to review this PR?

It's about this bug #32439. I've also used this opportunity to improve Operate's compatibility tests since they are a good place to assert that Operate and Zeebe interact well together.

File: qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateAuthorizationIT.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateAuthorizationIT.java:74]: Hey @ChrisKujawa, I wasn't able to get a "test start-up bean"  injected into the `TestCamundaApplication` so I went with creating a `TEST_EXECUTOR` Spring profile which we can use to enable the Operate executor. Wdyt?

File: qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateZeebeAuthorizationIT.java [hunk 2]
```diff
@@ -344,13 +410,25 @@ public void shouldUpdateProcessInstanceVariable(
       // when
       final var response =
           operateRestClient.updateVariable(
-              processInstanceKey, variableScopeId, variableName, "\"update\"");
+              processInstanceKey, variableScopeId, variableName, variableValue);
```
Comment (ThorbenLindhauer) [inline qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateZeebeAuthorizationIT.java:413]: Why did you make this change? Like this, it doesn't reproduce the problem anymore, or? As now we are no longer sending a JSON String (i.e. with escaped double quotes) to the Operate backend. Same for the other test methods and class with this change.

File: operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/UpdateVariableHandler.java [hunk 3]
```diff
@@ -10,23 +10,31 @@
...
+import org.springframework.beans.factory.annotation.Qualifier;
 import org.springframework.stereotype.Component;
 
 /** Update the variable. */
 @Component
 public class UpdateVariableHandler extends AbstractOperationHandler implements OperationHandler {
 
+  @Autowired
+  @Qualifier("operateObjectMapper")
+  private final ObjectMapper objectMapper = new ObjectMapper();
```
Comment (ThorbenLindhauer) [inline operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/UpdateVariableHandler.java]: Previously, the Zeebe/Camunda client used an instance of [CamundaObjectMapper](https://github.com/camunda/camunda/blob/0487c646aefd82ddaaf8f1224ef1c7d3743aa80d/clients/java/src/main/java/io/camunda/client/impl/CamundaObjectMapper.java) that in turn wraps a relatively plain `ObjectMapper`. In comparison, the [Operate ObjectMapper](https://github.com/camunda/camunda/blob/0487c646aefd82ddaaf8f1224ef1c7d3743aa80d/operate/common/src/main/java/io/camunda/operate/JacksonConfig.java#L35) applies more configuration, e.g. registering modules for date deserialization. I didn't think this fully through, but I can imagine there might be certain String variable values that will get deserialized differently than before.

Should we use either a plain `ObjectMapper` or an instance of `CamundaObjectMapper` instead?

**Review by ThorbenLindhauer — CHANGES_REQUESTED** [review]
Fix looks generally fine. Please see two details about the choice of ObjectMapper and the tests.

File: operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/UpdateVariableHandler.java (hunk 3 above)
Comment (koevskinikola) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/UpdateVariableHandler.java]: I wasn't aware of the additional configuration of the Operate `ObjectMapper`, my goal was to reduce duplication and use an `ObjectMapper` instance that was already available, as I noticed that Tasklist uses this approach (i.e. it autowires a "Tasklist ObjectMapper") for variable serialization.

But you make a good point, I'll use a plain ObjectMapper.

File: qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateZeebeAuthorizationIT.java (hunk 2 above)
Comment (koevskinikola) [reply qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateZeebeAuthorizationIT.java:413]: @ThorbenLindhauer my goal was to make the test more readable. Passing an interger variable and expecting the exported Zeebe event to have an integer variable is more readable than a quote-escaped String.

You need to consider this change with the refactoring I made in the `TestRestOperateClient` [here](https://github.com/camunda/camunda/pull/32497/files#diff-e7487ecc0fe2908f95a2356c9036725430ff23b7ad95fbd23fcba035c87c84d5R146), where I convert the variable value to a String.

The bug can still be reproduced with the int value. I tested with both int and wrapped String when I reproduced the issue.

If you prefer, I can restore the original variable value.

File: operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/UpdateVariableHandler.java (hunk 3 above)
Comment (ThorbenLindhauer) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/UpdateVariableHandler.java:29]: Thanks for the explanation. I think I get it now that previously a Number was sent as a JSON String to Zeebe, whereas it's now a number again. That's fine for me.

File: qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateZeebeAuthorizationIT.java (hunk 2 above)
Comment (ThorbenLindhauer) [reply qa/acceptance-tests/src/test/java/io/camunda/it/operate/compatibility/NoCompatibilityModeOperateZeebeAuthorizationIT.java:413]: Thanks for the explanation. I think I get it now that previously a Number was sent as a JSON String to Zeebe, whereas it's now a number again. That's fine for me.

**Comment by koevskinikola** [comment]
@ThorbenLindhauer I applied your feedback. I refactored the `UpdateVariableHandler` to use a plain `ObjectMapper` instead of the `CamundaObjectMapper`. 

The latter is a Java Client-specific class, and we want to move away from using the Java client in Operate in favor of the Service layer API. So as we phase out the Java client usage, we probably don't want our core Operate functionality to depend on client classes.

**Comment by matthewBearCamunda** [comment]
@koevskinikola - Does this change need to be backported to `8.7` and `8.6`? Or is this exclusive to `8.8`/`main`?

**Comment by koevskinikola** [comment]
@matthewBearCamunda this is exclusive to 8.8. The regression is due to my refactoring of the `*Handler` classes to support the new Camunda Service layer API.

**Review by ThorbenLindhauer — APPROVED** [review]
Looks good to me!
