### PR TITLE
chore(atomix): fix flaky Swim test

### LINKED ISSUE #4382: SwimProtocolTest.shouldSynchronizePeriodically flaky
**Summary**

- How often does the test fail? - Top3 flaky test for CW 19
- Does it block your work? yes
- Do we suspect that it is a real failure? unknown

**Failures**

https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/4340-do-not-merge-monitor-build-health-branch/135/

<details><summary>Example assertion failure</summary>
<pre>
Stacktrace

java.lang.NullPointerException
	at io.atomix.cluster.protocol.SwimProtocolTest.shouldSynchronizePeriodically(SwimProtocolTest.java:259)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
22:14:10.897 [] INFO  io.zeebe.test - Test started: shouldSynchronizePeriodically(io.atomix.cluster.protocol.SwimProtocolTest)
22:14:10.922 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
22:14:10.924 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
22:14:10.927 [] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 1 - Member activated: Member{id=1, address=localhost:5001, properties={}}
22:14:10.932 [] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
22:14:10.933 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
22:14:10.933 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
22:14:10.934 [] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 2 - Member activated: Member{id=2, address=localhost:5002, properties={}}
22:14:10.936 [] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
22:14:10.939 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
22:14:10.939 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
22:14:10.940 [] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 3 - Member activated: Member{id=3, address=localhost:5003, properties={}}
22:14:10.941 [] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
</pre>
</details>

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
Fixes and improves flaky SwimProtocolTest. Introduces Awaitility lib to await certain events.
Reduces the execution time from ~15 seconds to 6 seconds.

## Related issues

closes #4382 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java [hunk 1]
```diff
@@ -164,7 +211,7 @@ public void testSwimProtocol() throws Exception {
 
     // Verify that neither node is ever removed from the cluster since node 3 can still ping nodes 1
     // and 2.
-    Thread.sleep(5000);
+    Thread.sleep(500);
```
Comment (npepinpe) [inline atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java:214]: Do you think we could get rid of all these `Thread.sleep` :smiley: ? We're clearly waiting for something to happen here - can we use awaitility again for it, or is this something that's not observable?

**Review by npepinpe — APPROVED** [review]
Love it, thanks for looking into that! I had one comment but don't consider it a blocker :+1:

File: atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java (hunk 1 above)
Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java:214]: I would love to. But this is not possible since there is no really a thing we can verify. I was really close to just drop the sleeps. And also the last part which says "is never removed" :sweat_smile:

Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java:214]: If you agree then I would just drop this part.

Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java:214]:
```java

    // Verify that neither node is ever removed from the cluster since node 3 can still ping nodes 1
    // and 2.
    Awaitility.await().atLeast(Duration.ofSeconds(1));
    Thread.sleep(500);
    checkMembers(member1, member1, member2, member3);
    checkMembers(member2, member1, member2, member3);
    checkMembers(member3, member1, member2, member3);
```

Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java:214]: @npepinpe ping

Comment (npepinpe) [reply atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java:214]: Ah, so it just waits to make sure that nodes are not removed if nothing happens?

Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/cluster/protocol/SwimProtocolTest.java:214]: Yes

**Review by npepinpe — APPROVED** [review]
