### PR TITLE
Job activate fix

### LINKED ISSUE #1800: Activated job deadline is updated after restart without snapshot
If a broker is restarted with removing the snapshots already activated jobs get a new deadline, as the current time is used to calculate the deadline. This is not optimal be not sure if this can be prevented.

### LINKED ISSUE #2515: DB transaction loops forever with an exception in new leader
I have seen the following error a couple of times in docker-compose setup, after leadership change occurs. The transaction retries forever because there is an exception. It doesn't block the processor. It can still create workflows and activate jobs.
`Caused by: java.lang.IllegalStateException: Expected to find job with key 2251799813692390, but no job found`
I wonder if it is due to some inconsistent state.

```
java.lang.RuntimeException: Unexpected error occurred during zeebe db transaction operation.
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:155) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:154) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.whileTrue(ZeebeTransactionDb.java:266) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:117) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:108) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:104) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.engine.state.instance.JobState.forEachTimedOutEntry(JobState.java:176) ~[zeebe-workflow-engine-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.engine.processor.workflow.job.JobTimeoutTrigger.deactivateTimedOutJobs(JobTimeoutTrigger.java:61) ~[zeebe-workflow-engine-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zeebe-util-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | Caused by: java.lang.IllegalStateException: Expected to find job with key 2251799813692390, but no job found
broker-2_1  | 	at io.zeebe.engine.state.instance.JobState.visitJob(JobState.java:225) ~[zeebe-workflow-engine-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.engine.state.instance.JobState.lambda$forEachTimedOutEntry$0(JobState.java:182) ~[zeebe-workflow-engine-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.visit(ZeebeTransactionDb.java:365) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$whileTrue$8(ZeebeTransactionDb.java:273) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$ensureInOpenTransaction$1(ZeebeTransactionDb.java:155) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:171) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
broker-2_1  | 	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:143) ~[zeebe-db-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by ChrisKujawa**
closes #2515 
closes https://github.com/zeebe-io/zeebe/issues/1800

### CODE REVIEW

File: engine/src/test/java/io/zeebe/engine/processor/workflow/job/JobTimeOutTest.java [hunk 1]
```diff
@@ -82,6 +82,29 @@ public void shouldTimeOutJob() {
...
 
+  @Test
+  public void shouldTimeOutAfterReprocessing() {
+    // given
+    final long jobKey = ENGINE.createJob(jobType, PROCESS_ID).getKey();
+    final long timeout = 10L;
+
+    ENGINE.jobs().withType(jobType).withTimeout(timeout).activate();
+    ENGINE.increaseTime(JobTimeoutTrigger.TIME_OUT_POLLING_INTERVAL);
+    jobRecords(TIME_OUT).withRecordKey(jobKey).getFirst();
```
Comment (saig0) [inline engine/src/test/java/io/zeebe/engine/processor/workflow/job/JobTimeOutTest.java]: Do you need two jobs for this test case? I don't see what is the first job used for.

File: engine/src/test/java/io/zeebe/engine/util/EngineRule.java [hunk 2]
```diff
@@ -139,6 +144,29 @@ public void increaseTime(Duration duration) {
...
+  public void reprocess() {
+    forEachPartition(
+        partitionId -> {
+          try {
+            environmentRule.closeStreamProcessor(partitionId);
+            FileUtil.deleteFolder(
+                environmentRule
+                    .getStateSnapshotController(partitionId)
+                    .getLastValidSnapshotDirectory()
+                    .toPath());
```
Comment (saig0) [inline engine/src/test/java/io/zeebe/engine/util/EngineRule.java]: :see_no_evil:

**Review by npepinpe — APPROVED** [review]
👍

File: engine/src/test/java/io/zeebe/engine/util/TestStreams.java [hunk 3]
```diff
@@ -263,6 +263,11 @@ private StreamProcessor buildStreamProcessor(
 
     final ActorFuture<Void> openFuture = new CompletableActorFuture<>();
 
+    try {
+      currentSnapshotController.recover();
+    } catch (Exception e) {
+      throw new RuntimeException(e);
+    }
```
Comment (saig0) [inline engine/src/test/java/io/zeebe/engine/util/TestStreams.java]: I guess that this is only necessary if we deleted the snapshots before. If so, we could also do it in `EngineRule#reprocess()`.

File: engine/src/test/java/io/zeebe/engine/util/EngineRule.java [hunk 4]
```diff
@@ -139,6 +144,29 @@ public void increaseTime(Duration duration) {
     environmentRule.getClock().addTime(duration);
   }
 
+  public void reprocess() {
```
Comment (saig0) [inline engine/src/test/java/io/zeebe/engine/util/EngineRule.java]: Maybe, we could rename it to `deleteSnapshotAndReprocess()`. What do you think?

**Review by saig0 — CHANGES_REQUESTED** [review]

**Review by saig0 — APPROVED** [review]

File: engine/src/test/java/io/zeebe/engine/processor/workflow/job/JobTimeOutTest.java (hunk 1 above)
Comment (Zelldon) [reply engine/src/test/java/io/zeebe/engine/processor/workflow/job/JobTimeOutTest.java]: As discussed only with the second job we see the real problem, that we can't timeout further jobs

File: engine/src/test/java/io/zeebe/engine/util/EngineRule.java (hunk 4 above)
Comment (Zelldon) [reply engine/src/test/java/io/zeebe/engine/util/EngineRule.java]: Reprocessing includes without snapshot since in this tests always the snapshots are enforced.
