### PR TITLE
Stabilize `ReplayStateRandomizedPropertyTest`

### LINKED ISSUE #14596: Multiple failures in ReplayStateRandomizedPropertyTest
**Summary**

<details><summary>Stacktrace</summary>

```
-------------------------------------------------------------------------------
Test set: io.camunda.zeebe.engine.processing.randomized.ReplayStateRandomizedPropertyTest
-------------------------------------------------------------------------------
Tests run: 44, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 216.8 s <<< FAILURE! -- in io.camunda.zeebe.engine.processing.randomized.ReplayStateRandomizedPropertyTest
io.camunda.zeebe.engine.processing.randomized.ReplayStateRandomizedPropertyTest.shouldRestoreStateAtEachStepInExecution[TestDataRecord{processSeed=-6151309027320488640, executionPathSeed=-4098306458066079953}] -- Time elapsed: 13.66 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Condition with alias 'await that the replay state is equal to the processing state' didn't complete within 10 seconds because assertion condition defined as a io.camunda.zeebe.engine.processing.randomized.ReplayStateRandomizedPropertyTest 
Multiple Failures (14 failures)
-- failure 1 --
[The state column 'ELEMENT_INSTANCE_CHILD_PARENT' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12]"="{"parentScopeKey":2251799813685254}", "[0, 8, 0, 0, 0, 0, 0, 33]"="{"parentScopeKey":2251799813685254}", "[0, 8, 0, 0, 0, 0, 0, 42]"="{"parentScopeKey":2251799813685254}", "[0, 8, 0, 0, 0, 0, 0, 45]"="{"parentScopeKey":-1}", "[0, 8, 0, 0, 0, 0, 0, 50]"="{"parentScopeKey":2251799813685293}", "[0, 8, 0, 0, 0, 0, 0, 6]"="{"parentScopeKey":-1}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 12]"="{"parentScopeKey":2251799813685254}",
    "[0, 8, 0, 0, 0, 0, 0, 42]"="{"parentScopeKey":2251799813685254}",
    "[0, 8, 0, 0, 0, 0, 0, 33]"="{"parentScopeKey":2251799813685254}",
    "[0, 8, 0, 0, 0, 0, 0, 6]"="{"parentScopeKey":-1}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 50]"="{"parentScopeKey":2251799813685293}",
    "[0, 8, 0, 0, 0, 0, 0, 45]"="{"parentScopeKey":-1}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 2 --
[The state column 'MESSAGE_SUBSCRIPTION_BY_KEY' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57]"="{"record":{"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685260,"messageKey":-1,"messageName":"message_id_19","correlationKey":"default_correlation_key","interrupting":true,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685268,"correlating":false}", "[0, 8, 0, 0, 0, 0, 0, 45, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"processInstanceKey":2251799813685293,"elementInstanceKey":2251799813685293,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","correlationKey":"default_correlation_key","interrupting":false,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685299,"correlating":false}", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685254,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","correlationKey":"default_correlation_key","interrupting":false,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685262,"correlating":false}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 6, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685254,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","correlationKey":"default_correlation_key","interrupting":false,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685262,"correlating":false}",
    "[0, 8, 0, 0, 0, 0, 0, 12, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57]"="{"record":{"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685260,"messageKey":-1,"messageName":"message_id_19","correlationKey":"default_correlation_key","interrupting":true,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685268,"correlating":false}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 45, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"processInstanceKey":2251799813685293,"elementInstanceKey":2251799813685293,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","correlationKey":"default_correlation_key","interrupting":false,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685299,"correlating":false}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 3 --
[The state column 'TIMER_DUE_DATES' has different entries] 
Expecting map:
  {}
to contain only:
  ["[0, 0, 1, -118, -6, -4, -74, 96, -1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 4]"="-1"]
but could not find the following map entries:
  ["[0, 0, 1, -118, -6, -4, -74, 96, -1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 4]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 4 --
[The state column 'JOB_STATES' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 36]"="{"jobState":"ACTIVATABLE"}", "[0, 8, 0, 0, 0, 0, 0, 43]"="{"jobState":"ACTIVATABLE"}", "[0, 8, 0, 0, 0, 0, 0, 52]"="{"jobState":"ACTIVATABLE"}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 36]"="{"jobState":"ACTIVATABLE"}",
    "[0, 8, 0, 0, 0, 0, 0, 43]"="{"jobState":"ACTIVATABLE"}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 52]"="{"jobState":"ACTIVATABLE"}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 5 --
[The state column 'MESSAGE_SUBSCRIPTION_BY_NAME_AND_CORRELATION_KEY' has different entries] 
Expecting map:
  {"[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 12]"="-1", "[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 45]"="-1", "[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"}
to contain only:
  ["[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 12]"="-1",
    "[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"]
but the following map entries were unexpected:
  ["[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 45]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 6 --
[The state column 'JOB_ACTIVATABLE' has different entries] 
Expecting map:
  {"[0, 0, 0, 15, 105, 100, 95, 50, 55, 95, 118, 97, 114, 105, 97, 98, 108, 101, 115, 0, 8, 0, 0, 0, 0, 0, 52]"="-1", "[0, 0, 0, 25, 105, 111, 46, 99, 97, 109, 117, 110, 100, 97, 46, 122, 101, 101, 98, 101, 58, 117, 115, 101, 114, 84, 97, 115, 107, 0, 8, 0, 0, 0, 0, 0, 43]"="-1", "[0, 0, 0, 9, 106, 111, 98, 95, 105, 100, 95, 49, 53, 0, 8, 0, 0, 0, 0, 0, 36]"="-1"}
to contain only:
  ["[0, 0, 0, 25, 105, 111, 46, 99, 97, 109, 117, 110, 100, 97, 46, 122, 101, 101, 98, 101, 58, 117, 115, 101, 114, 84, 97, 115, 107, 0, 8, 0, 0, 0, 0, 0, 43]"="-1",
    "[0, 0, 0, 9, 106, 111, 98, 95, 105, 100, 95, 49, 53, 0, 8, 0, 0, 0, 0, 0, 36]"="-1"]
but the following map entries were unexpected:
  ["[0, 0, 0, 15, 105, 100, 95, 50, 55, 95, 118, 97, 114, 105, 97, 98, 108, 101, 115, 0, 8, 0, 0, 0, 0, 0, 52]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 7 --
[The state column 'EVENT_SCOPE' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12]"="{"accepting":true,"interrupting":["id_19"],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 33]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 42]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 45]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 50]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 6]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 12]"="{"accepting":true,"interrupting":["id_19"],"boundaryElementIds":[],"interrupted":false}",
    "[0, 8, 0, 0, 0, 0, 0, 42]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}",
    "[0, 8, 0, 0, 0, 0, 0, 33]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}",
    "[0, 8, 0, 0, 0, 0, 0, 6]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 50]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}",
    "[0, 8, 0, 0, 0, 0, 0, 45]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 8 --
[The state column 'PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0, 45]"="-1", "[0, 8, 0, 0, 0, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0, 45]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 9 --
[The state column 'ELEMENT_INSTANCE_PARENT_CHILD' has different entries] 
Expecting map:
  {"[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 45]"="-1", "[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 6]"="-1", "[0, 8, 0, 0, 0, 0, 0, 45, 0, 8, 0, 0, 0, 0, 0, 50]"="-1", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 12]"="-1", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 33]"="-1", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 42]"="-1"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 12]"="-1",
    "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 33]"="-1",
    "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 42]"="-1",
    "[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"]
but the following map entries were unexpected:
  ["[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 45]"="-1",
    "[0, 8, 0, 0, 0, 0, 0, 45, 0, 8, 0, 0, 0, 0, 0, 50]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 10 --
[The state column 'ELEMENT_INSTANCE_KEY' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685260,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"RECEIVE_TASK","elementId":"id_19","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"MESSAGE","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 33]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685284,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685281,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"SEND_TASK","elementId":"id_15","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 42]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685291,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685290,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"USER_TASK","elementId":"id_12","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 45]"="{"parentKey":-1,"childCount":1,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685293,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"PROCESS","elementId":"process_id_25","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 50]"="{"parentKey":2251799813685293,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685300,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685298,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"SERVICE_TASK","elementId":"id_27_variables_task","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"flowScopeKey":2251799813685293,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 6]"="{"parentKey":-1,"childCount":3,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685254,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"PROCESS","elementId":"process_id_25","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 12]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685260,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"RECEIVE_TASK","elementId":"id_19","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"MESSAGE","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}",
    "[0, 8, 0, 0, 0, 0, 0, 42]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685291,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685290,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"USER_TASK","elementId":"id_12","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}",
    "[0, 8, 0, 0, 0, 0, 0, 33]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685284,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685281,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"SEND_TASK","elementId":"id_15","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}",
    "[0, 8, 0, 0, 0, 0, 0, 6]"="{"parentKey":-1,"childCount":3,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685254,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"PROCESS","elementId":"process_id_25","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 50]"="{"parentKey":2251799813685293,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685300,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685298,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"SERVICE_TASK","elementId":"id_27_variables_task","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"flowScopeKey":2251799813685293,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}",
    "[0, 8, 0, 0, 0, 0, 0, 45]"="{"parentKey":-1,"childCount":1,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685293,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"PROCESS","elementId":"process_id_25","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 11 --
[The state column 'PROCESS_SUBSCRIPTION_BY_KEY' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685260,"messageKey":-1,"messageName":"message_id_19","variables":"gA==","interrupting":true,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"id_19","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685267}", "[0, 8, 0, 0, 0, 0, 0, 45, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685293,"elementInstanceKey":2251799813685293,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","variables":"gA==","interrupting":false,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"start_event_eventSubProcess_id_26","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685296}", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685254,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","variables":"gA==","interrupting":false,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"start_event_eventSubProcess_id_26","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685258}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 12, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685260,"messageKey":-1,"messageName":"message_id_19","variables":"gA==","interrupting":true,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"id_19","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685267}",
    "[0, 8, 0, 0, 0, 0, 0, 6, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685254,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","variables":"gA==","interrupting":false,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"start_event_eventSubProcess_id_26","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685258}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 45, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685293,"elementInstanceKey":2251799813685293,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","variables":"gA==","interrupting":false,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"start_event_eventSubProcess_id_26","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685296}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 12 --
[The state column 'JOBS' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 36]"="{"jobRecord":{"deadline":1696426543437,"worker":"","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"job_id_15","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"elementId":"id_15","elementInstanceKey":2251799813685281,"tenantId":"<default>"}}", "[0, 8, 0, 0, 0, 0, 0, 43]"="{"jobRecord":{"deadline":-1,"worker":"","retries":1,"retryBackoff":0,"recurringTime":-1,"type":"io.camunda.zeebe:userTask","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"elementId":"id_12","elementInstanceKey":2251799813685290,"tenantId":"<default>"}}", "[0, 8, 0, 0, 0, 0, 0, 52]"="{"jobRecord":{"deadline":-1,"worker":"","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"id_27_variables","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"elementId":"id_27_variables_task","elementInstanceKey":2251799813685298,"tenantId":"<default>"}}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 36]"="{"jobRecord":{"deadline":1696426543437,"worker":"","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"job_id_15","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"elementId":"id_15","elementInstanceKey":2251799813685281,"tenantId":"<default>"}}",
    "[0, 8, 0, 0, 0, 0, 0, 43]"="{"jobRecord":{"deadline":-1,"worker":"","retries":1,"retryBackoff":0,"recurringTime":-1,"type":"io.camunda.zeebe:userTask","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"elementId":"id_12","elementInstanceKey":2251799813685290,"tenantId":"<default>"}}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 52]"="{"jobRecord":{"deadline":-1,"worker":"","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"id_27_variables","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"elementId":"id_27_variables_task","elementInstanceKey":2251799813685298,"tenantId":"<default>"}}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 13 --
[The state column 'TIMERS' has different entries] 
Expecting map:
  {}
to contain only:
  ["[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 4]"="{"handlerNodeId":"id_27","processDefinitionKey":2251799813685249,"key":2251799813685252,"elementInstanceKey":-1,"processInstanceKey":-1,"dueDate":1696427980384,"repetitions":1,"tenantId":"<default>"}"]
but could not find the following map entries:
  ["[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 4]"="{"handlerNodeId":"id_27","processDefinitionKey":2251799813685249,"key":2251799813685252,"elementInstanceKey":-1,"processInstanceKey":-1,"dueDate":1696427980384,"repetitions":1,"tenantId":"<default>"}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 14 --
[The state column 'KEY' has different entries] 
Expecting map:
  {"[0, 0, 0, 9, 108, 97, 116, 101, 115, 116, 75, 101, 121]"="{"nextValue":2251799813685300}"}
to contain only:
  ["[0, 0, 0, 9, 108, 97, 116, 101, 115, 116, 75, 101, 121]"="{"nextValue":2251799813685292}"]
map entries not found:
  ["[0, 0, 0, 9, 108, 97, 116, 101, 115, 116, 75, 101, 121]"="{"nextValue":2251799813685292}"]
and map entries not expected:
  ["[0, 0, 0, 9, 108, 97, 116, 101, 115, 116, 75, 101, 121]"="{"nextValue":2251799813685300}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159).
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at io.camunda.zeebe.engine.processing.randomized.ReplayStateRandomizedPropertyTest.stopAndRestartEngineAndCompareStates(ReplayStateRandomizedPropertyTest.java:131)
	at io.camunda.zeebe.engine.processing.randomized.ReplayStateRandomizedPropertyTest.shouldRestoreStateAtEachStepInExecution(ReplayStateRandomizedPropertyTest.java:86)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Caused by: org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (14 failures)
-- failure 1 --
[The state column 'ELEMENT_INSTANCE_CHILD_PARENT' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12]"="{"parentScopeKey":2251799813685254}", "[0, 8, 0, 0, 0, 0, 0, 33]"="{"parentScopeKey":2251799813685254}", "[0, 8, 0, 0, 0, 0, 0, 42]"="{"parentScopeKey":2251799813685254}", "[0, 8, 0, 0, 0, 0, 0, 45]"="{"parentScopeKey":-1}", "[0, 8, 0, 0, 0, 0, 0, 50]"="{"parentScopeKey":2251799813685293}", "[0, 8, 0, 0, 0, 0, 0, 6]"="{"parentScopeKey":-1}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 12]"="{"parentScopeKey":2251799813685254}",
    "[0, 8, 0, 0, 0, 0, 0, 42]"="{"parentScopeKey":2251799813685254}",
    "[0, 8, 0, 0, 0, 0, 0, 33]"="{"parentScopeKey":2251799813685254}",
    "[0, 8, 0, 0, 0, 0, 0, 6]"="{"parentScopeKey":-1}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 50]"="{"parentScopeKey":2251799813685293}",
    "[0, 8, 0, 0, 0, 0, 0, 45]"="{"parentScopeKey":-1}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 2 --
[The state column 'MESSAGE_SUBSCRIPTION_BY_KEY' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57]"="{"record":{"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685260,"messageKey":-1,"messageName":"message_id_19","correlationKey":"default_correlation_key","interrupting":true,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685268,"correlating":false}", "[0, 8, 0, 0, 0, 0, 0, 45, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"processInstanceKey":2251799813685293,"elementInstanceKey":2251799813685293,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","correlationKey":"default_correlation_key","interrupting":false,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685299,"correlating":false}", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685254,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","correlationKey":"default_correlation_key","interrupting":false,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685262,"correlating":false}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 6, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685254,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","correlationKey":"default_correlation_key","interrupting":false,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685262,"correlating":false}",
    "[0, 8, 0, 0, 0, 0, 0, 12, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57]"="{"record":{"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685260,"messageKey":-1,"messageName":"message_id_19","correlationKey":"default_correlation_key","interrupting":true,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685268,"correlating":false}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 45, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"processInstanceKey":2251799813685293,"elementInstanceKey":2251799813685293,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","correlationKey":"default_correlation_key","interrupting":false,"bpmnProcessId":"process_id_25","variables":"gA==","tenantId":"<default>"},"key":2251799813685299,"correlating":false}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 3 --
[The state column 'TIMER_DUE_DATES' has different entries] 
Expecting map:
  {}
to contain only:
  ["[0, 0, 1, -118, -6, -4, -74, 96, -1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 4]"="-1"]
but could not find the following map entries:
  ["[0, 0, 1, -118, -6, -4, -74, 96, -1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 4]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 4 --
[The state column 'JOB_STATES' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 36]"="{"jobState":"ACTIVATABLE"}", "[0, 8, 0, 0, 0, 0, 0, 43]"="{"jobState":"ACTIVATABLE"}", "[0, 8, 0, 0, 0, 0, 0, 52]"="{"jobState":"ACTIVATABLE"}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 36]"="{"jobState":"ACTIVATABLE"}",
    "[0, 8, 0, 0, 0, 0, 0, 43]"="{"jobState":"ACTIVATABLE"}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 52]"="{"jobState":"ACTIVATABLE"}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 5 --
[The state column 'MESSAGE_SUBSCRIPTION_BY_NAME_AND_CORRELATION_KEY' has different entries] 
Expecting map:
  {"[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 12]"="-1", "[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 45]"="-1", "[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"}
to contain only:
  ["[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 12]"="-1",
    "[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"]
but the following map entries were unexpected:
  ["[0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54, 0, 0, 0, 23, 100, 101, 102, 97, 117, 108, 116, 95, 99, 111, 114, 114, 101, 108, 97, 116, 105, 111, 110, 95, 107, 101, 121, 0, 8, 0, 0, 0, 0, 0, 45]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 6 --
[The state column 'JOB_ACTIVATABLE' has different entries] 
Expecting map:
  {"[0, 0, 0, 15, 105, 100, 95, 50, 55, 95, 118, 97, 114, 105, 97, 98, 108, 101, 115, 0, 8, 0, 0, 0, 0, 0, 52]"="-1", "[0, 0, 0, 25, 105, 111, 46, 99, 97, 109, 117, 110, 100, 97, 46, 122, 101, 101, 98, 101, 58, 117, 115, 101, 114, 84, 97, 115, 107, 0, 8, 0, 0, 0, 0, 0, 43]"="-1", "[0, 0, 0, 9, 106, 111, 98, 95, 105, 100, 95, 49, 53, 0, 8, 0, 0, 0, 0, 0, 36]"="-1"}
to contain only:
  ["[0, 0, 0, 25, 105, 111, 46, 99, 97, 109, 117, 110, 100, 97, 46, 122, 101, 101, 98, 101, 58, 117, 115, 101, 114, 84, 97, 115, 107, 0, 8, 0, 0, 0, 0, 0, 43]"="-1",
    "[0, 0, 0, 9, 106, 111, 98, 95, 105, 100, 95, 49, 53, 0, 8, 0, 0, 0, 0, 0, 36]"="-1"]
but the following map entries were unexpected:
  ["[0, 0, 0, 15, 105, 100, 95, 50, 55, 95, 118, 97, 114, 105, 97, 98, 108, 101, 115, 0, 8, 0, 0, 0, 0, 0, 52]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 7 --
[The state column 'EVENT_SCOPE' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12]"="{"accepting":true,"interrupting":["id_19"],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 33]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 42]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 45]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 50]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}", "[0, 8, 0, 0, 0, 0, 0, 6]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 12]"="{"accepting":true,"interrupting":["id_19"],"boundaryElementIds":[],"interrupted":false}",
    "[0, 8, 0, 0, 0, 0, 0, 42]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}",
    "[0, 8, 0, 0, 0, 0, 0, 33]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}",
    "[0, 8, 0, 0, 0, 0, 0, 6]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 50]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}",
    "[0, 8, 0, 0, 0, 0, 0, 45]"="{"accepting":true,"interrupting":[],"boundaryElementIds":[],"interrupted":false}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 8 --
[The state column 'PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0, 45]"="-1", "[0, 8, 0, 0, 0, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0, 45]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 9 --
[The state column 'ELEMENT_INSTANCE_PARENT_CHILD' has different entries] 
Expecting map:
  {"[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 45]"="-1", "[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 6]"="-1", "[0, 8, 0, 0, 0, 0, 0, 45, 0, 8, 0, 0, 0, 0, 0, 50]"="-1", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 12]"="-1", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 33]"="-1", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 42]"="-1"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 12]"="-1",
    "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 33]"="-1",
    "[0, 8, 0, 0, 0, 0, 0, 6, 0, 8, 0, 0, 0, 0, 0, 42]"="-1",
    "[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 6]"="-1"]
but the following map entries were unexpected:
  ["[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 45]"="-1",
    "[0, 8, 0, 0, 0, 0, 0, 45, 0, 8, 0, 0, 0, 0, 0, 50]"="-1"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 10 --
[The state column 'ELEMENT_INSTANCE_KEY' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685260,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"RECEIVE_TASK","elementId":"id_19","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"MESSAGE","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 33]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685284,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685281,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"SEND_TASK","elementId":"id_15","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 42]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685291,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685290,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"USER_TASK","elementId":"id_12","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 45]"="{"parentKey":-1,"childCount":1,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685293,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"PROCESS","elementId":"process_id_25","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 50]"="{"parentKey":2251799813685293,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685300,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685298,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"SERVICE_TASK","elementId":"id_27_variables_task","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"flowScopeKey":2251799813685293,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}", "[0, 8, 0, 0, 0, 0, 0, 6]"="{"parentKey":-1,"childCount":3,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685254,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"PROCESS","elementId":"process_id_25","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 12]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685260,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"RECEIVE_TASK","elementId":"id_19","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"MESSAGE","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}",
    "[0, 8, 0, 0, 0, 0, 0, 42]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685291,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685290,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"USER_TASK","elementId":"id_12","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}",
    "[0, 8, 0, 0, 0, 0, 0, 33]"="{"parentKey":2251799813685254,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685284,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685281,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"SEND_TASK","elementId":"id_15","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":2251799813685254,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}",
    "[0, 8, 0, 0, 0, 0, 0, 6]"="{"parentKey":-1,"childCount":3,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685254,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"PROCESS","elementId":"process_id_25","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 50]"="{"parentKey":2251799813685293,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":2251799813685300,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685298,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"SERVICE_TASK","elementId":"id_27_variables_task","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"flowScopeKey":2251799813685293,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}",
    "[0, 8, 0, 0, 0, 0, 0, 45]"="{"parentKey":-1,"childCount":1,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":2251799813685293,"state":"ELEMENT_ACTIVATED","processInstanceRecord":{"bpmnElementType":"PROCESS","elementId":"process_id_25","bpmnProcessId":"process_id_25","version":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 11 --
[The state column 'PROCESS_SUBSCRIPTION_BY_KEY' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 12, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685260,"messageKey":-1,"messageName":"message_id_19","variables":"gA==","interrupting":true,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"id_19","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685267}", "[0, 8, 0, 0, 0, 0, 0, 45, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685293,"elementInstanceKey":2251799813685293,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","variables":"gA==","interrupting":false,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"start_event_eventSubProcess_id_26","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685296}", "[0, 8, 0, 0, 0, 0, 0, 6, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685254,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","variables":"gA==","interrupting":false,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"start_event_eventSubProcess_id_26","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685258}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 12, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 13, 109, 101, 115, 115, 97, 103, 101, 95, 105, 100, 95, 49, 57]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685260,"messageKey":-1,"messageName":"message_id_19","variables":"gA==","interrupting":true,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"id_19","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685267}",
    "[0, 8, 0, 0, 0, 0, 0, 6, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685254,"elementInstanceKey":2251799813685254,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","variables":"gA==","interrupting":false,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"start_event_eventSubProcess_id_26","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685258}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 45, 0, 0, 0, 9, 60, 100, 101, 102, 97, 117, 108, 116, 62, 0, 0, 0, 29, 109, 101, 115, 115, 97, 103, 101, 95, 101, 118, 101, 110, 116, 83, 117, 98, 80, 114, 111, 99, 101, 115, 115, 95, 105, 100, 95, 50, 54]"="{"record":{"subscriptionPartitionId":1,"processInstanceKey":2251799813685293,"elementInstanceKey":2251799813685293,"messageKey":-1,"messageName":"message_eventSubProcess_id_26","variables":"gA==","interrupting":false,"bpmnProcessId":"process_id_25","correlationKey":"default_correlation_key","elementId":"start_event_eventSubProcess_id_26","tenantId":"<default>"},"state":"STATE_OPENED","key":2251799813685296}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 12 --
[The state column 'JOBS' has different entries] 
Expecting map:
  {"[0, 8, 0, 0, 0, 0, 0, 36]"="{"jobRecord":{"deadline":1696426543437,"worker":"","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"job_id_15","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"elementId":"id_15","elementInstanceKey":2251799813685281,"tenantId":"<default>"}}", "[0, 8, 0, 0, 0, 0, 0, 43]"="{"jobRecord":{"deadline":-1,"worker":"","retries":1,"retryBackoff":0,"recurringTime":-1,"type":"io.camunda.zeebe:userTask","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"elementId":"id_12","elementInstanceKey":2251799813685290,"tenantId":"<default>"}}", "[0, 8, 0, 0, 0, 0, 0, 52]"="{"jobRecord":{"deadline":-1,"worker":"","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"id_27_variables","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"elementId":"id_27_variables_task","elementInstanceKey":2251799813685298,"tenantId":"<default>"}}"}
to contain only:
  ["[0, 8, 0, 0, 0, 0, 0, 36]"="{"jobRecord":{"deadline":1696426543437,"worker":"","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"job_id_15","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"elementId":"id_15","elementInstanceKey":2251799813685281,"tenantId":"<default>"}}",
    "[0, 8, 0, 0, 0, 0, 0, 43]"="{"jobRecord":{"deadline":-1,"worker":"","retries":1,"retryBackoff":0,"recurringTime":-1,"type":"io.camunda.zeebe:userTask","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685254,"elementId":"id_12","elementInstanceKey":2251799813685290,"tenantId":"<default>"}}"]
but the following map entries were unexpected:
  ["[0, 8, 0, 0, 0, 0, 0, 52]"="{"jobRecord":{"deadline":-1,"worker":"","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"id_27_variables","customHeaders":{},"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"process_id_25","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685293,"elementId":"id_27_variables_task","elementInstanceKey":2251799813685298,"tenantId":"<default>"}}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 13 --
[The state column 'TIMERS' has different entries] 
Expecting map:
  {}
to contain only:
  ["[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 4]"="{"handlerNodeId":"id_27","processDefinitionKey":2251799813685249,"key":2251799813685252,"elementInstanceKey":-1,"processInstanceKey":-1,"dueDate":1696427980384,"repetitions":1,"tenantId":"<default>"}"]
but could not find the following map entries:
  ["[-1, -1, -1, -1, -1, -1, -1, -1, 0, 8, 0, 0, 0, 0, 0, 4]"="{"handlerNodeId":"id_27","processDefinitionKey":2251799813685249,"key":2251799813685252,"elementInstanceKey":-1,"processInstanceKey":-1,"dueDate":1696427980384,"repetitions":1,"tenantId":"<default>"}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
-- failure 14 --
[The state column 'KEY' has different entries] 
Expecting map:
  {"[0, 0, 0, 9, 108, 97, 116, 101, 115, 116, 75, 101, 121]"="{"nextValue":2251799813685300}"}
to contain only:
  ["[0, 0, 0, 9, 108, 97, 116, 101, 115, 116, 75, 101, 121]"="{"nextValue":2251799813685292}"]
map entries not found:
  ["[0, 0, 0, 9, 108, 97, 116, 101, 115, 116, 75, 101, 121]"="{"nextValue":2251799813685292}"]
and map entries not expected:
  ["[0, 0, 0, 9, 108, 97, 116, 101, 115, 116, 75, 101, 121]"="{"nextValue":2251799813685300}"]
at ReplayStateRandomizedPropertyTest.lambda$assertIdenticalStates$5(ReplayStateRandomizedPropertyTest.java:159)
	at jdk.internal.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at io.camunda.zeebe.engine.processing.randomized.ReplayStateRandomizedPropertyTest.assertIdenticalStates(ReplayStateRandomizedPropertyTest.java:163)
	at io.camunda.zeebe.engine.processing.randomized.ReplayStateRandomizedPropertyTest.lambda$stopAndRestartEngineAndCompareStates$3(ReplayStateRandomizedPropertyTest.java:134)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details> 

**Logs**
https://github.com/camunda/zeebe/actions/runs/6406762116

[Test results for Property Tests.zip](https://github.com/camunda/zeebe/files/12804157/Test.results.for.Property.Tests.zip)

### PR DESCRIPTION
**Pull request by korthout**
## Description

Makes `ReplayStateRandomizedPropertyTest` deterministic by restarting the engine in `REPLAY` mode, by avoiding processing any leftover commands after the engine restart.

This test case ensures that the state after replay is equivalent to state before restart, i.e. it verifies that replay is deterministic. It does this as follows:
- deploy a random process
- determine a random execution path through this process
- for each step in the random execution path:
  - run the step
  - stop the engine and collect the state for later comparison
  - restart the engine in replay mode
  - collect the state again and compare with previous state
  - continue processing

There is a small window where processing is stopped before the restart and new commands could be appended by a checker. For example, a timer trigger command. This made it possible for unprocessed commands on the log stream to be processed at restart, because the test did restarted the engine after restart in processing mode. The main change of this PR is to restart the engine in replay mode and to continue in processing mode after each verification step.

## Related issues

closes #14596

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ReplayStateRandomizedPropertyTest.java [hunk 1]
```diff
@@ -168,14 +165,10 @@ private void processingHasStoppedAndNoNewRecordsAreAddedDuringGracePeriod()
     assertThat(engineRule.hasReachedEnd())
         .describedAs("Processing has reached end of the log.")
         .isTrue();
-    final var stateBeforeGracePeriod = engineRule.collectState();
     Thread.sleep(GRACE_PERIOD);
     assertThat(engineRule.hasReachedEnd())
         .describedAs("Processing has reached end of the log.")
         .isTrue();
```
Comment (tmetzke) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ReplayStateRandomizedPropertyTest.java:171]: ❓ Do we still need this grace period wait time?

Comment (tmetzke) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ReplayStateRandomizedPropertyTest.java:171]: That makes a lot of sense, thanks @korthout 👍 

I'm wondering what could still go wrong without waiting for another grace period:
* Before we stop the engine, we collect the last position and the state.
* After we collect the state and position, another event is processed.
* We stop the engine.
* We restart the engine in REPLAY mode.
* The engine replays more events than in the first run, at least according to our stored last position and collected state.

I'm not 100% confident that this would fail the test, happy for any further thoughts on this.

Comment (korthout) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ReplayStateRandomizedPropertyTest.java:171]: The thing is that we pause the processing before collecting the state and position. I think, but I don't know for sure, that after pausing it's possible for the engine to wrap up processing the current command it is processing.

What I mean is that the processing state machine moves through its states in steps, each executed as a task by the actor scheduler. Pausing is also just a task executed by the actor scheduler. I believe this can be exeucted in between any of the tasks, but only takes affected at the start of each new cycle of states:
- In `tryToReadNextRecord` it checks `shouldProcessNext` which is flipped by pausing: https://github.com/camunda/camunda/blob/889db69401e94fc86d5f1dd8daf7d0ba35f458d3/zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L238

Note that pausing joins on it's own execution, not the completion of the cycle of processing state machine.

So, the grace period could protect against the following:
- we pause the engine (flipping the boolean)
- we collect the state
- the engine still appends some new events, changing state
- we stop the engine
- ... 

With that in mind, the strange thing is that I've already made 350 successful passes of the test without the grace period.

Comment (tmetzke) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ReplayStateRandomizedPropertyTest.java:171]: Yay for async systems 😄
I think the possibility of the test still failing now without the grace period is simply super small.
There might only be a theoretical chance left now to get into this edge case, if at all possible.

**Review by tmetzke — APPROVED** [review]
👍 Great improvement, @korthout 🌟 

The only thing left to decide is whether we want the extra "safety margin" of waiting for a grace period before collecting the state after pausing and before stopping the engine.

I'm fine either way as it doesn't leave much room for unexpected events anymore now.

Pre-approving as I don't think this blocks the merge.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ReplayStateRandomizedPropertyTest.java (hunk 1 above)
Comment (korthout) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ReplayStateRandomizedPropertyTest.java:171]: @tmetzke Let's keep the grace period in for now then. I'd prefer a deterministic slightly slower test over a faster but possibly flaky test.

We would be able to remove this grace period, if `pause` would only return once the ProcessingStateMachine is paused **and** has completed a full cycle. @camunda/zeebe-distributed-platform is that something you would be willing to add to the admin pause endpoint?
