### PR TITLE
chore(qa): fix flaky snapshot replication test

### LINKED ISSUE #4053: SnapshotReplicationTest.shouldReceiveNewSnapshotsOnRejoin is flaky
**Description**

It sometimes happens that there are more snapshots than expected, even though the snapshot interval is 5 minutes, these snapshots (from the logged timestamp) seem to be taken with smaller intervals - it is a controlled clock however, so we should investigate.

NOTE: I've seen this happen with other tests in that suite, so the same issue might be related to flakiness of other tests.

<details>
<summary>Sample output</summary>
<pre>
Failures: 

[ERROR]   SnapshotReplicationTest.shouldReceiveNewSnapshotsOnRejoin:120 

Expecting:

 <{"2-1-1584316799462/000091.log"=2794790440L, "2-1-1584316799462/000092.sst"=3762184780L, "2-1-1584316799462/000093.sst"=2073560521L, "2-1-1584316799462/000095.sst"=2902222425L, "2-1-1584316799462/000096.sst"=3165565020L, "2-1-1584316799462/000097.sst"=3946582159L, "2-1-1584316799462/000098.sst"=400477988L, "2-1-1584316799462/000099.sst"=30820173L, "2-1-1584316799462/000100.sst"=1959921764L, "2-1-1584316799462/000101.sst"=3306696654L, "2-1-1584316799462/CURRENT"=2380087979L, "2-1-1584316799462/MANIFEST-000004"=4035880576L, "2-1-1584316799462/OPTIONS-000090"=3042895128L, "2-1-1584316808269/000092.sst"=3762184780L, "2-1-1584316808269/000093.sst"=2073560521L, "2-1-1584316808269/000095.sst"=2902222425L, "2-1-1584316808269/000096.sst"=3165565020L, "2-1-1584316808269/000097.sst"=3946582159L, "2-1-1584316808269/000098.sst"=400477988L, "2-1-1584316808269/000099.sst"=30820173L, "2-1-1584316808269/000100.sst"=1959921764L, "2-1-1584316808269/000101.sst"=3306696654L, "2-1-1584316808269/000103.sst"=1095198306L, "2-1-1584316808269/000108.log"=874173147L, "2-1-1584316808269/000109.sst"=35270537L, "2-1-1584316808269/000110.sst"=1968252910L, "2-1-1584316808269/000111.sst"=1199288592L, "2-1-1584316808269/000112.sst"=1337337557L, "2-1-1584316808269/000113.sst"=548214779L, "2-1-1584316808269/CURRENT"=1352198163L, "2-1-1584316808269/MANIFEST-000104"=1667902739L, "2-1-1584316808269/OPTIONS-000107"=2111876784L}>

to contain:

 <[2-1-1584316808269/000096.sst=3165565020,

    2-1-1584316808269/000103.sst=1095198306,

    2-1-1584316808269/000112.sst=1337337557,

    2-1-1584316799462/000091.log=2794790440,

    2-1-1584316802297/000095.sst=2902222425,

    2-1-1584316808269/000095.sst=2902222425,

    2-1-1584316799462/000096.sst=3165565020,

    2-1-1584316799462/000092.sst=3762184780,

    2-1-1584316799462/000095.sst=2902222425,

    2-1-1584316799462/OPTIONS-000090=3042895128,

    2-1-1584316808269/000099.sst=30820173,

    2-1-1584316808269/CURRENT=1352198163,

    2-1-1584316808269/000110.sst=1968252910,

    2-1-1584316808269/000100.sst=1959921764,

    2-1-1584316802297/000099.sst=30820173,

    2-1-1584316808269/000113.sst=548214779,

    2-1-1584316802297/OPTIONS-000090=3042895128,

    2-1-1584316808269/000109.sst=35270537,

    2-1-1584316802297/CURRENT=2380087979,

    2-1-1584316802297/000098.sst=400477988,

    2-1-1584316808269/000098.sst=400477988,

    2-1-1584316799462/MANIFEST-000004=4035880576,

    2-1-1584316808269/000101.sst=3306696654,

    2-1-1584316802297/000101.sst=3306696654,

    2-1-1584316799462/000099.sst=30820173,

    2-1-1584316802297/000100.sst=1959921764,

    2-1-1584316799462/000101.sst=3306696654,

    2-1-1584316799462/CURRENT=2380087979,

    2-1-1584316808269/000093.sst=2073560521,

    2-1-1584316802297/000093.sst=2073560521,

    2-1-1584316808269/000097.sst=3946582159,

    2-1-1584316802297/000102.sst=764452740,

    2-1-1584316802297/000097.sst=3946582159,

    2-1-1584316799462/000098.sst=400477988,

    2-1-1584316799462/000100.sst=1959921764,

    2-1-1584316808269/OPTIONS-000107=2111876784,

    2-1-1584316808269/MANIFEST-000104=1667902739,

    2-1-1584316808269/000111.sst=1199288592,

    2-1-1584316799462/000097.sst=3946582159,

    2-1-1584316802297/000096.sst=3165565020,

    2-1-1584316799462/000093.sst=2073560521,

    2-1-1584316808269/000108.log=874173147,

    2-1-1584316802297/MANIFEST-000004=1466873043,

    2-1-1584316808269/000092.sst=3762184780,

    2-1-1584316802297/000092.sst=3762184780]>

but could not find:

 <[2-1-1584316802297/000095.sst=2902222425,

    2-1-1584316802297/000099.sst=30820173,

    2-1-1584316802297/OPTIONS-000090=3042895128,

    2-1-1584316802297/CURRENT=2380087979,

    2-1-1584316802297/000098.sst=400477988,

    2-1-1584316802297/000101.sst=3306696654,

    2-1-1584316802297/000100.sst=1959921764,

    2-1-1584316802297/000093.sst=2073560521,

    2-1-1584316802297/000102.sst=764452740,

    2-1-1584316802297/000097.sst=3946582159,

    2-1-1584316802297/000096.sst=3165565020,

    2-1-1584316802297/MANIFEST-000004=1466873043,

    2-1-1584316802297/000092.sst=3762184780]>

</pre>
</details>

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

ensure we don't restart broker-0 to prevent unexpected elections.

## Related issues

closes #4053 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SnapshotReplicationTest.java [hunk 1]
```diff
@@ -77,9 +77,16 @@ public void shouldReplicateSnapshots() {
...
-    final var firstFollowerId = otherBrokers.get(0).getConfig().getCluster().getNodeId();
-    final var secondFollowerId = otherBrokers.get(1).getConfig().getCluster().getNodeId();
+    final var followers =
+        clusteringRule.getOtherBrokerObjects(leaderNodeId).stream()
+            .map(b -> b.getConfig().getCluster().getNodeId())
+            .collect(Collectors.toList());
+
+    // Temp fix to make sure we don't restart broker-0 due to
+    // https://github.com/zeebe-io/atomix/issues/208
+    final var firstFollowerId = followers.stream().filter(nodeId -> nodeId != 0).findFirst().get();
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SnapshotReplicationTest.java]: Nit: to get rid of warnings, you can use `orElseThrow()` instead of `get()` in tests, since probably if we didn't find it you'd want to abort anyway.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SnapshotReplicationTest.java [hunk 2]
```diff
@@ -77,9 +77,16 @@ public void shouldReplicateSnapshots() {
...
+    final var secondFollowerId =
+        followers.stream().filter(nodeId -> nodeId != firstFollowerId).findFirst().get();
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SnapshotReplicationTest.java]: Nit: by using implicit variable inference with `var` above, the type of `firstFollowerId` is now Number (i.e. it was not implicitly unboxed by casting it to `int`), so `!=` checks object instance equality. I mean it works here but not sure if this is what you intended :sweat_smile:

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SnapshotReplicationTest.java [hunk 3]
```diff
@@ -77,9 +77,16 @@ public void shouldReplicateSnapshots() {
   public void shouldReceiveLatestSnapshotOnRejoin() {
     // given
     final var leaderNodeId = clusteringRule.getLeaderForPartition(1).getNodeId();
-    final var otherBrokers = clusteringRule.getOtherBrokerObjects(leaderNodeId);
-    final var firstFollowerId = otherBrokers.get(0).getConfig().getCluster().getNodeId();
-    final var secondFollowerId = otherBrokers.get(1).getConfig().getCluster().getNodeId();
+    final var followers =
+        clusteringRule.getOtherBrokerObjects(leaderNodeId).stream()
+            .map(b -> b.getConfig().getCluster().getNodeId())
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SnapshotReplicationTest.java]: Nit: I guess we could just sort by nodeId and always pick the last one, which is for sure not 0. But the intent of what we're doing may be less clear as we're not explicitly checking for `!= 0`, which is more obvious. Plus I hope this is temporary, so :man_shrugging:

**Review by npepinpe — APPROVED** [review]
LGTM :+1: 

Only nits, so decide as you want :)

Thanks for fixing this, it was really bothering me :tada:
