### PR TITLE
fix: Write `VariableDocument` terminal events with `operationReference`

### LINKED ISSUE #30686: Variables add/update operations in Operate remain in `"SENT"` state when user task has `"updating"` listeners
**Describe the bug**
When a Camunda User Task is configured with `"updating"` task listeners, adding or updating variables via the Operate UI results in an inconsistent state.

The related Operate operations (`"ADD_VARIABLE"` or `"UPDATE_VARIABLE"`) are never turned into `"COMPLETED"` state. Instead, they remain stuck in the `"SENT"` state indefinitely.

**To Reproduce**

1. Deploy a process with a Camunda User Task that includes a task listener of type `"updating"`.
2. Start a process instance and reach the user task.
3. Open the instance in Operate and add or modify a task-local variable.
4. Observe the network requests:
    - GET: `https://<operate.host>/api/operations?batchOperationId=<operationId>`:
      - The `"ADD_VARIABLE"` or `"UPDATE_VARIABLE"` operations stays in `"SENT"` state.
    - POST: `https://<operate.host>/api/process-instances/<processInstanceKey>/variables`
      - Updated variable is marked with `hasActiveOperation = true`, preventing further edits via Operate UI.

**Expected behavior**

The `"ADD_VARIABLE"`/`"UPDATE_VARIABLE"` operation should transition to `"COMPLETED"` state once the variable is successfully added/updated.

**Impact**  
This behavior blocks users from editing task-local variables again in the UI, even though no error was shown and the variable was technically updated.

**Notes**  
This issue occurs during regular add/update variables flow (without `"updating"` listener denying the update).  
The problem seems to be that Operate unable to receives a completion signal or fails to recognize it after `"updating"` listeners are completed.

**Environment:**
- OS: 
- Zeebe Version: 8.8.0-alpha3-rc3
- Configuration:

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

This PR addresses a bug in Zeebe that caused `ADD_VARIABLE` and `UPDATE_VARIABLE` operations triggered via Operate to remain in the `SENT` state indefinitely when "updating" task listeners were involved.

### 🐞 Problem
The root cause was the missing `operationReference` in follow-up `VariableDocument:UPDATED` events emitted after completing the user task update transition with `"updating"` task listeners. Since Operate relies on this reference to correlate and complete the variable operation, it was unable to mark it as completed — effectively blocking further user input in the UI.

### 🛠️ Solution
To enable proper operation tracking and correlation:
* A new `FollowUpEventMetadata` abstraction was introduced to support writing enriched follow-up events.
* The `TypedEventWriter` interface and its implementations were extended with a new method `appendFollowUpEvent(..., FollowUpEventMetadata)` and a builder-based overload.
* This metadata now allows attaching an `operationReference` and/or record version to any follow-up event.
* The `UserTaskProcessor` and `UserTaskUpdateProcessor` were updated to use this new method when writing `VariableDocument:UPDATED` and `VariableDocument:UPDATE_DENIED` events.
* `BufferedProcessingResultBuilder` was updated to ensure that `operationReference` is included in the follow-up response, if it was provided.

This ensures that `operationReference` is retained in `VariableDocument` terminal events, even when task listeners are involved.

### 💡 Why add `operationReference` to `VD:UPDATE_DENIED`?
While it is not required for the current Operate flow — since it awaits completion of the `UPDATE` command [itself](https://github.com/camunda/camunda/blob/a53e7e4e575d02f1e0e0274482707ca97725296e/operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/adapter/ClientBasedAdapter.java#L112) – it will enabl tracking and correlation for other consumers of the `Update element instance variables` endpoint or future use cases.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #30686

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/FollowUpEventMetadata.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+  public OptionalLong getOperationReference() {
+    return operationReference == NOT_SET
+        ? OptionalLong.empty()
+        : OptionalLong.of(operationReference);
+  }
+
+  public OptionalInt getRecordVersion() {
+    return recordVersion == NOT_SET ? OptionalInt.empty() : OptionalInt.of(recordVersion);
+  }
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/FollowUpEventMetadata.java]: 🔧 it is our convention to use `-1` as a way to describe "this value is not set". There's no need to introduce additional optional handling to the API, which requires the caller to deal with the optional at all times. In most cases the -1 can simply be propagated.

💭 While Java does support Optional, [the intention](https://nipafx.dev/design-java-optional/) was never to be used as a built-in Option but was meant only to simplify working with lambdas and to provide reasonable apis for Stream. It is even [recommended not to use Optional as the return type for simple getters of a POJO](https://www.baeldung.com/java-optional-return#when-to-not-return-optional). I think there's a place for it in Zeebe, but I don't think this is one.

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/BufferedProcessingResultBuilder.java [hunk 2]
```diff
@@ -57,8 +57,11 @@ final class BufferedProcessingResultBuilder implements ProcessingResultBuilder {
   public Either<RuntimeException, ProcessingResultBuilder> appendRecordReturnEither(
       final long key, final RecordValue value, final RecordMetadata metadata) {
 
-    if (operationReference != operationReferenceNullValue()) {
-      metadata.operationReference(operationReference);
+    // `operationReference` from `metadata` should have a higher precedence
+    if (metadata.getOperationReference() == -1) {
+      if (operationReference != operationReferenceNullValue()) {
+        metadata.operationReference(operationReference);
+      }
```
Comment (korthout) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/BufferedProcessingResultBuilder.java]: 👍 Nice!

**Review by korthout — APPROVED** [review]
Nice work @ce-dmelnych 🚀 

🔧 I have one suggestion. Please have a look before merging.

👍 LGTM

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/FollowUpEventMetadata.java (hunk 1 above)
Comment (ce-dmelnych) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/FollowUpEventMetadata.java]: Thanks, @korthout  – I’ve [removed](https://github.com/camunda/camunda/pull/33220/commits/d5f7fa33dd7b33427400ec4933ec2a432d19ca2a) the usage of `Optional`-s.

To indicate not set value for  `operationReference` I've used `RecordMetadataDecoder#operationReferenceNullValue`, which is effectively `-1L` and already used consistently across our codebase as default value.
<details>
<summary>Screenshot 1 <code>RecordMetadataDecoder#operationReferenceNullValue</code></summary>
Screenshot 2025-06-11 at 17 45 33
</details>


For the record version, I decided to go with a plain `-1` instead of `RecordMetadataDecoder#recordVersionNullValue`, since the latter returns `65535`, which feels a bit awkward and less intuitive in this context.
<details>
<summary>Screenshot 2 <code>RecordMetadataDecoder#recordVersionNullValue</code></summary>
Screenshot 2025-06-11 at 17 46 29
</details>

Let me know if that sounds reasonable to you!

Comment (korthout) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/FollowUpEventMetadata.java]: That's a great idea!

**Review by korthout — APPROVED** [review]
Thanks @ce-dmelnych 💯 

LGTM 👍
