### PR TITLE
Fix ZeebePartition can be closed when there are ongoing transitions

### LINKED ISSUE #7981: DeploymentClusteredTest.shouldDeployProcessAndCreateInstances
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? at least once
- Does it block your work? Blocked merging
- Do we suspect that it is a real failure? not sure

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
io.camunda.zeebe.it.clustering.DeploymentClusteredTest

[2021-10-13T09:22:45.475Z] [ERROR] io.camunda.zeebe.it.clustering.DeploymentClusteredTest.shouldDeployProcessAndCreateInstances  Time elapsed: 120.012 s  <<< ERROR!

[2021-10-13T09:22:45.475Z] org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds

[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)

[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)

[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)

[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:133)

[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:108)

[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:21)

[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:196)

[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.broker.Broker.lambda$close$0(Broker.java:170)

[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.broker.Broker$$Lambda$1358/0x00000007c0977c40.accept(Unknown Source)

[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)

[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)

[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.broker.Broker.lambda$close$1(Broker.java:168)
[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.broker.Broker$$Lambda$1357/0x00000007c0977840.run(Unknown Source)
[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23)
[2021-10-13T09:22:45.475Z] 	at app//io.camunda.zeebe.broker.Broker.close(Broker.java:163)
[2021-10-13T09:22:45.475Z] 	at app/zeebe.qa.integration.tests@1.3.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.lambda$after$3(ClusteringRule.java:257)
[2021-10-13T09:22:45.475Z] 	at app/zeebe.qa.integration.tests@1.3.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule$$Lambda$1582/0x00000007c0a67840.accept(Unknown Source)
[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
[2021-10-13T09:22:45.475Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:1957)
[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.concurent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)

[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)

[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)

[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)

[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)

[2021-10-13T09:22:45.476Z] 	at app/zeebe.qa.integration.tests@1.3.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.after(ClusteringRule.java:254)

[2021-10-13T09:22:45.476Z] 	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59)

[2021-10-13T09:22:45.476Z] 	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2021-10-13T09:22:45.476Z] 	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)

[2021-10-13T09:22:45.476Z] 	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)

[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[2021-10-13T09:22:45.476Z] 	at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)

[2021-10-13T09:22:45.476Z] 
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

Failing https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1173/pipeline

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

This problem was identified via flaky test #7981 

When ZeebePartition#closeAsync is called, it waits for the currentTransition to be completed before actor#closeAsync is executed. However, if there was a new transition that happened between these two calls, there is a good chance that that transition gets stuck because actor#closeAsync will discard jobs from actor queue. As a result transitionToInactive triggered by the close will never gets completed and thus ZeebePartition is not closed.

In this PR,
* Added a test that can reproduced the behaviour without this fix
* Ensure that no ongoing transitions when actor#closeAsync is called. This will ensure that the actor can be safely closed.

## Related issues

closes #7981 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java [hunk 1]
```diff
@@ -186,10 +171,19 @@ protected void onActorCloseRequested() {
...
+          closing = true;
+
+          removeListeners();
+          context.getComponentHealthMonitor().removeComponent(zeebePartitionHealth.getName());
+
+          final var inactiveTransitionFuture = transitionToInactive();
+
+          // allows to await current transition to avoid concurrent modifications and
+          // transitioning
+          inactiveTransitionFuture.onComplete((nothing, err) -> super.closeAsync());
```
Comment (oleschoenburg) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:185]: :thought_balloon: Here we can have a gap where we have transitioned to inactive but haven't closed the actor yet. During that gap we could have another transition (for example to leader) happening that was scheduled earlier and has already passed the `!closing` check. I _think_ this is bad and should not happen?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java [hunk 2]
```diff
@@ -57,6 +57,7 @@
   private final PartitionTransition transition;
   private CompletableActorFuture<Void> closeFuture;
   private ActorFuture<Void> currentTransitionFuture;
```
Comment (oleschoenburg) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:59]: `currentTransitionFuture` is no longer needed

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java (hunk 1 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:185]: This would not happen, as far as I understand. 
If the other transition has already passed `!closing` check, then inactive transition is enqueued after the other transition. In `PartitionTransitionImpl`, we already ensure that all transitions are executed sequentially. So inactive transition will wait until the other transition is completed.

Comment (oleschoenburg) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java:184]: I see, that makes sense and I agree that this is the case :+1:

**Review by lenaschoenburg — APPROVED** [review]
:rocket: LGTM
