### PR TITLE
Accurately mark history deletion batch operation items as complete

### LINKED ISSUE #46526: Batch operation related to historic data deletion are marked as completed before the data is deleted
### 

### 

### 

### 

### Description

When creating a batch operation to delete process instances, or decision instance. Or when deleting a process definition or DRG, we create a batch operation. This batch operation writes `HistoryDeletion.DELETED` events.
These event write a deletion document in an index, which a background task in the exporter will read from in order to delete the data from secondary storage.

Within a batch operation we have individual operations. These operations have a state that is either scheduled, failed or completed. The scheduled and failed states are set properly at the moment. The completed state, however is set immediately upon exporting the `HistoryDeletion.DELETED` event. This is not accurate to when the data is properly deleted.

We should ensure the operation state is set to `COMPLETED` at the moment we have actually deleted the data from secondary storage.

### Steps to reproduce

1. Deploy a model and create some process instances.
2. Complete the process instances
3. Create a batch operation to delete the proces instances
4. Observe how the operations in the batch operation are marked as `COMPLETD` before the process instance are actually deleted.

### Current behavior

The operations are marked as `COMPLETED` immediately, before any data is deleted. This will be confusing for users.

### Expected behavior

The operations are marked as `COMPLETED` once the actual data is deleted.

### Workaround

N/A

### Environment

SaaS & SM

### Version

- Component Version: 8.9+

### Rootcause

**ES/OS**
[Here](https://github.com/camunda/camunda/blob/ee19e7af21a08358c2b7125bc6abff4b0fde9b27/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/ProcessInstanceHistoryDeletionOperationHandler.java#L54-L58) and [here](https://github.com/camunda/camunda/blob/ee19e7af21a08358c2b7125bc6abff4b0fde9b27/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/DecisionInstanceHistoryDeletionOperationHandler.java#L54-L58) we mark the operation as completed as soon as we receive an event with the `DELETED` intent.

**RDBMS**
[Here](https://github.com/camunda/camunda/blob/ee19e7af21a08358c2b7125bc6abff4b0fde9b27/zeebe/exporters/rdbms-exporter/src/main/java/io/camunda/exporter/rdbms/handlers/batchoperation/ProcessInstanceHistoryDeletionBatchOperationExportHandler.java#L52-L55) and [here](https://github.com/camunda/camunda/blob/ee19e7af21a08358c2b7125bc6abff4b0fde9b27/zeebe/exporters/rdbms-exporter/src/main/java/io/camunda/exporter/rdbms/handlers/batchoperation/DecisionInstanceHistoryDeletionBatchOperationExportHandler.java#L52-L55) we mark the operation as completed as soon as we receive an event with the `DELETED` intent.

### Solution ideas

The above handlers should always return `false` when the `isCompleted` check is ran. We don't want to mark the operations as completed on the event export, but only once the background task has deleted the relevant data.

We should extend the [HistoryDeletionJob](https://github.com/camunda/camunda/blob/9a7411dd3194d5aae40e4c4412f95b047b374ef5/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/historydeletion/HistoryDeletionJob.java#L40) and the [HistoryDeletionService](https://github.com/camunda/camunda/blob/9a7411dd3194d5aae40e4c4412f95b047b374ef5/db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/HistoryDeletionService.java#L33) to mark the operations as completed once the actual data is deleted.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Accurately reflect the operation items state. Only mark them as complete once they data is actually deleted.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #46526

### CODE REVIEW

File: db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/HistoryDeletionService.java [hunk 1]
```diff
@@ -109,12 +112,33 @@ private List<Long> deleteProcessInstances(final HistoryDeletionBatch batch) {
...
+            .map(
+                model ->
+                    new BatchOperationItemCompletionDto(
+                        String.valueOf(model.batchOperationKey()), model.resourceKey()))
+            .toList();
+
+    if (!completionItems.isEmpty()) {
+      rdbmsWriters
+          .getBatchOperationWriter()
+          .completeBatchOperationItems(completionItems, OffsetDateTime.now(ZoneOffset.UTC));
```
Comment (kristinkomschow) [inline db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/HistoryDeletionService.java]: Shouldn't we use the engine clock here (if not I'm gonna need an explanation 😄)?

**Review by kristinkomschow — APPROVED** [review]
LGTM, just left one comment

File: db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/HistoryDeletionService.java (hunk 1 above)
Comment (remcowesterhoud) [reply db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/HistoryDeletionService.java]: You are very right. And I'm not just saying that because I do not want to give an explanation 😄
