### PR TITLE
ES/OS Exporter writes to correct versioned indices

### LINKED ISSUE #24316: ES/OS exporter are writing to wrong versioned Zeebe indices
**Describe the bug**

Imagine the following scenario:

We have the following log:

```
         Exporter pos
             ||
             \/                               
[ R 8.6 | R 8.6 | R 8.6 | R 8.6 | R 8.7 | R 8.7 | R 8.7 | R 8.7 | R 8.7 | R 8.7]
```

When doing an update to 8.7, the Engine will create new records with the new version. For simplicity, we just show the version above. 

Let's say the exporter is currently in a position where the Record was written with version 8.6.

When the ES/OS exporter continues now with a record in version 8.6 it will write them into a Zeebe index named 8.7, because of this https://github.com/camunda/camunda/blob/main/zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java#L63

This means it will be imported by Operate as a record for version 8.7 https://github.com/camunda/camunda/blob/main/operate/importer/src/main/java/io/camunda/operate/zeebeimport/ImportJob.java#L151

### Why is it a problem:

  * it is unexpected when the Broker writes a record with version 8.6 and it is exported as 8.7
  * changing the record format could lead to further problems (luckily we were mostly backwards compatible)
  * **Important:** With the Camunda Exporter project we expect that we get rid of the Importer, and need to make sure that all old data is correctly imported ( Note: we have differentiation between 8.7 and 8.6 Importer modules. We will have no 8.7 Importer component).

**To Reproduce**

Run an update, and see that the exporter writes records directly to new indices.

**Expected behavior**

Records are written into the corresponding indices (where records belong to).

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

If the log has records which were generated in an older version of camunda and the brokers (and thus exporters) update, the old records should write to the old versioned zeebe indices instead of the new ones.
e.g.
- log has 8.6 records
- exporter updates to 8.7
- as exporter runs the 8.6 records get written to the 8.6 zeebe indices. (Currently it writes to the 8.7 zeebe indice)

## Related issues

closes #24316

### CODE REVIEW

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java [hunk 1]
```diff
@@ -61,6 +62,10 @@ String aliasNameForValueType(final ValueType valueType) {
   /** Returns the index for this value type, minus the current date. */
   String indexPrefixForValueType(final ValueType valueType) {
```
Comment (Zelldon) [inline zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java:63]: I think we shouldn't use this method anymore, as we always need to make sure that we write into the right version or?

Comment (EuroLew) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java:63]: I looked at the other usages and I agree 
- tests 
- `RecordIndexRouter.searchPatternForValueType[81]` we want this to return the versionUtil version
- `ElasticsearchClient.putIndexTemplate[165]` we want this to return the versionUtil version as we are created the current exporter (8.7.0) indices. 

All this can be refactored such that the (ValueType, Version) is the only function that is used but just wanted to make sure it's the correct logic as a draft.

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java [hunk 2]
```diff
@@ -40,7 +41,18 @@ final class RecordIndexRouter {
...
+
+    // if the record version is less than the current version use that as the record should be
+    // written to old versioned index.
+    if (recordVersion.isPresent() && recordVersion.get().compareTo(indexVersion) < 0) {
+      indexVersion = recordVersion.get();
+    }
+
+    return (indexPrefixForValueType(record.getValueType(), indexVersion.toString().toLowerCase())
+            + INDEX_DELIMITER)
         + formatter.format(timestamp);
```
Comment (Zelldon) [inline zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java:56]: ❌ I think we should "simply" always use the Record version, no?

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java [hunk 3]
```diff
@@ -163,7 +164,8 @@ public boolean shouldFlush() {
    * @return true if request was acknowledged
    */
   public boolean putIndexTemplate(final ValueType valueType) {
-    final String templateName = indexRouter.indexPrefixForValueType(valueType);
+    final String templateName =
+        indexRouter.indexPrefixForValueType(valueType, VersionUtil.getVersionLowerCase());
```
Comment (Zelldon) [inline zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:168]: ❓ Here we can use the VersionUtil, because we create the new template right? For the new version of the Exporter?

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
I think we should use always the record version, but happy to discuss this in more depth. I might oversee something.

@remcowesterhoud could you also have a short look, whether the changes are fine, as this falls in the ZPA (just to cross-check).

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 3 above)
Comment (remcowesterhoud) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:168]: Yes, this should be fine.

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java (hunk 2 above)
Comment (remcowesterhoud) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java:56]: I agree. The version is set on the record. If it's older we should write it to the older index. If it's not older, it should be the same as the version that comes out of `VersionUtil` anyway. So the version comparison is redundant.

**Review by remcowesterhoud — COMMENTED** [review]
I can think of one edge-case where this could go wrong:

1. Broker is updated to 8.6.0
2. ES/OS is down
3. Broker is processing and tries to export records with version 8.6.0, which fails due to ES/OS being down
4. Broker is updated to 8.7.0 and continues processing
5. ES/OS comes back up
6. Exporting starts. The exporter tries to export the old records to the 8.6.0 index. This template doesn't exist, as they couldn't get created due to ES/OS being down.

When this happens a workaround would be to manually create the missing index template(s)

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java (hunk 2 above)
Comment (EuroLew) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java:56]: True the record version is what we should write to but there is a lot of tests which will fail as a result of not checking if the recordVersion is a valid semantic version as the factory which generates records will fill it with a random value. `

I agree though I'll work through the tests

image

**Comment by EuroLew** [comment]
> I can think of one edge-case where this could go wrong:
> 
> 1. Broker is updated to 8.6.0
> 2. ES/OS is down
> 3. Broker is processing and tries to export records with version 8.6.0, which fails due to ES/OS being down
> 4. Broker is updated to 8.7.0 and continues processing
> 5. ES/OS comes back up
> 6. Exporting starts. The exporter tries to export the old records to the 8.6.0 index. This template doesn't exist, as they couldn't get created due to ES/OS being down.
> 
> When this happens a workaround would be to manually create the missing index template(s)

Adds a fix for the edge case https://github.com/camunda/camunda/pull/24483/commits/6e1f06a75ed38dad561c877b2325e2949c6dca34 where due to ES/OS being down templates are not created.

For each record version we create templates for that version if not created.

This is just a WIP commit to gauge interest in the solution

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java [hunk 4]
```diff
@@ -175,6 +175,17 @@ public boolean putIndexTemplate(final ValueType valueType) {
...
+  public boolean putIndexTemplate(final ValueType valueType, final String version) {
+    final String templateName = indexRouter.indexPrefixForValueType(valueType, version);
+    final Template template =
+        templateReader.readIndexTemplate(
+            valueType,
+            indexRouter.searchPatternForValueType(valueType, version),
+            indexRouter.aliasNameForValueType(valueType));
+
+    return putIndexTemplate(templateName, template);
+  }
```
Comment (remcowesterhoud) [inline zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:187]: 🔧 You can reduce some duplication here by changing the method above this to just call this one with the `VersionUtil.getVersionLowerCase()` as the version

**Review by remcowesterhoud — COMMENTED** [review]
@EuroLew I looked at your WIP commit. I like the solution and I believe it'll work 👍 

I think with this we may have solved https://github.com/camunda/camunda/issues/14863 as well 🤔 

We also need to do this for the OS exporter.

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 4 above)
Comment (EuroLew) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:187]: yep was just doing it quick and dirty to see if it was worth doing

**Review by remcowesterhoud — APPROVED** [review]
Thanks @EuroLew, looks good to me 🚀 

Would you mind closing the issue I mentioned in previous comment when this PR is merged. I am 99% sure this is resolved with versioned exporting 🙂

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java [hunk 5]
```diff
@@ -245,117 +247,117 @@ private void createIndexTemplates() {
...
       }
 
       if (index.authorization) {
-        createValueIndexTemplate(ValueType.AUTHORIZATION);
+        createValueIndexTemplate(ValueType.AUTHORIZATION, version);
       }
     }
 
-    indexTemplatesCreated = true;
+    indexTemplatesCreated.add(version);
```
Comment (Zelldon) [inline zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java:360]: ❓ So we always try to create the indices on restart?

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java [hunk 6]
```diff
@@ -163,11 +164,15 @@ public boolean shouldFlush() {
    * @return true if request was acknowledged
    */
   public boolean putIndexTemplate(final ValueType valueType) {
-    final String templateName = indexRouter.indexPrefixForValueType(valueType);
+    return putIndexTemplate(valueType, VersionUtil.getVersionLowerCase());
```
Comment (Zelldon) [inline zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:167]: Do we ever want to use this? With Broker version?

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java [hunk 7]
```diff
@@ -325,11 +355,94 @@ final var record = factory.generateRecord(ValueType.JOB);
...
+          .setPortBindings(List.of(currentPort + ":9200"));
+      CONTAINER.start();
+      Awaitility.await().until(CONTAINER::isRunning);
+
+      // when
+      final var record2 = factory.generateRecord(r -> r.withBrokerVersion("8.7.0"));
+      try (final var mockVersion =
+          Mockito.mockStatic(VersionUtil.class, Mockito.CALLS_REAL_METHODS)) {
+        mockVersion.when(VersionUtil::getVersionLowerCase).thenReturn("8.7.0");
+        configureExporter(false);
```
Comment (Zelldon) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:411]: ❓ What does this do?

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/RecordIndexRouterTest.java [hunk 8]
```diff
@@ -142,7 +149,8 @@ void shouldReturnSearchPatternForValueType() {
     final var valueType = ValueType.PROCESS;
 
     // when
-    final var prefix = router.searchPatternForValueType(valueType);
+    final var prefix =
+        router.searchPatternForValueType(valueType, VersionUtil.getVersionLowerCase());
```
Comment (Zelldon) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/RecordIndexRouterTest.java:153]: 🔧 I think it would be beneficial to also have a test not using the VersionUtil, to verify that we actual use the parameter not the static

File: zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchExporterIT.java [hunk 9]
```diff
@@ -413,14 +441,18 @@ void shouldNotTimeoutWhenUpdatingLifecyclePolicyForExistingIndices() {
       // using 490 here as we will export one more record after (1 main shard, 1 replica)
       final int limit = 490;
       for (int i = 0; i < limit; i++) {
-        final var record = factory.generateRecord(ValueType.JOB);
+        final var record =
+            factory.generateRecord(
+                ValueType.JOB, r -> r.withBrokerVersion(VersionUtil.getVersionLowerCase()));
```
Comment (Zelldon) [inline zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchExporterIT.java:446]: 🔧 Might make sense to make this the default - that the broker version is set correctly?

**Review by ChrisKujawa — APPROVED** [review]
Thanks. I think the solution likely works in our cases, but strictly speaking it is not correct, as we actually create the schema 8.7 just with a 8.6 version in the name. 

Just as feedback: Personally, I would have made a cut on this PR to scope it only to the one bug (and fix) we had planned before. 

And go with the part @remcowesterhoud mentioned:
> When this happens a workaround would be to manually create the missing index template(s)

Or look at it _separately_ when we have time for it (which we don't really have right now afaik).

I will any way approve, to not block us further and make progress here.

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java (hunk 5 above)
Comment (EuroLew) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java:360]: Yes we always try to create on restart, this mimics the behaviour of the old `indexTemplatesCreated `logic where it was a boolean.

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 6 above)
Comment (EuroLew) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:167]: It's only used for tests right now and no the default implementation is always the VersionUtil version

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java (hunk 7 above)
Comment (EuroLew) [reply zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:411]: oops yea it doesn't need to be configured twice as the port doesn't change I'll move it out.
