### PR TITLE
fix: allow kebab case for initializing mapping rules in default roles

### LINKED ISSUE #36382: Initializer config for defaultroles and mappingrules does not allow kebab-case
### 

### 

### 

### 

### Description

Kebab-case is not supported for initialization config for security, but it is allowed everywhere else in the configuration. 

> camunda.security.initialization.default-roles.<role>.**mapping-rules**[0]
> and
> camunda.security.initialization.**default-roles**.<role>.users[0]

are not supported and instead the following

> camunda.security.initialization.defaultroles.<role>.**mappingrules**[0]
> and
> camunda.security.initialization.**defaultroles**.<role>.users[0]

or

> camunda.security.initialization.defaultRoles.<role>.**mappingRules**[0]
> and
> camunda.security.initialization.**defaultRoles**.<role>.users[0]

has to be used

### Steps to reproduce

Use the config:

> camunda.security.initialization.default-roles.admin.mapping-rules[0]
> and
> camunda.security.initialization.default-roles.admin.users[0]

### Current behavior

The configs have no effect when kebab case is used.

### Expected behavior

Kebab case should work as for all other configs.

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by mrm1st3r**
## Description

Allow kebab case for initializing mapping rules in default roles.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #36382

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/IdentitySetupInitializer.java [hunk 1]
```diff
@@ -190,7 +190,8 @@ private static void setupRoleMembership(
             switch (assignmentsForEntityType.getKey().toLowerCase()) {
               case "users" -> EntityType.USER;
               case "clients" -> EntityType.CLIENT;
-              case "mappingrules" -> EntityType.MAPPING_RULE;
+              // when using config via env variables, spring will convert MAPPING_RULES to mapping.rules
+              case "mappingrules", "mapping-rules", "mapping.rules" -> EntityType.MAPPING_RULE;
```
[the remark this answers is not in the document]
Comment (mrm1st3r) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/IdentitySetupInitializer.java]: This comments seems to be misleading. Testing locally, I got the following exception message:
`java.lang.IllegalStateException: Unexpected entity type for role membership: mapping.rules`

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/IdentitySetupInitializer.java [hunk 2]
```diff
@@ -190,7 +190,9 @@ private static void setupRoleMembership(
             switch (assignmentsForEntityType.getKey().toLowerCase()) {
               case "users" -> EntityType.USER;
               case "clients" -> EntityType.CLIENT;
-              case "mappingrules" -> EntityType.MAPPING_RULE;
+              // when using config via env variables,
+              // spring will convert MAPPING_RULES to mapping.rules
+              case "mappingrules", "mapping-rules", "mapping.rules" -> EntityType.MAPPING_RULE;
```
Comment (Ben-Sheppard) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/IdentitySetupInitializer.java:195]: ❓ Are we able to add tests for this logic? it feels like an area that we could slip up on in the future :)

Comment (mrm1st3r) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/IdentitySetupInitializer.java:195]: Very good point! I do vaguely remember Nicolas pointing out that there are already some config tests in place (not for identity though). I'll look for these and add some accordingly.

**Review by Ben-Sheppard — APPROVED** [review]
