### PR TITLE
fix: always clear ES scroll context on exception

### LINKED ISSUE #50892: Scroll contexts leaked in ElasticsearchUtil.scrollWith on error paths
## Description

`ElasticsearchUtil.scrollWith` (and related `scroll` overloads) in `operate/schema/src/main/java/io/camunda/operate/util/ElasticsearchUtil.java` does not clear the scroll when the iteration loop exits exceptionally. `clearScroll(scrollId, esClient)` is only called after the `while` loop completes normally — there is no `try/finally`.

If any of the following throw during iteration, the scroll contexts on ES remain alive until the 60s keep-alive expires:
- `IOException` from `esClient.scroll(...)` (network blip, timeout)
- Exceptions from the `searchHitsProcessor` / `aggsProcessor` / `firstResponseConsumer` callbacks
- Any other unchecked exception inside the loop

Under load (e.g. many concurrent post-importer workers, batch-operation API users) this creates a rolling population of leaked search contexts on the ES data nodes, consuming heap, blocking segment merges, and counting against `search.max_open_scroll_context` (default 500).

## Impact

- Amplifies ES pressure during incidents where scroll-heavy paths are already failing (e.g. `search_context_missing_exception` surfacing in `BatchOperationWriter.addOperations` and post-importer paths).
- Makes recovery slower because leaked contexts have to wait out the full keep-alive instead of being released immediately on failure.

## Expected behavior

Wrap the scroll iteration loop in `try/finally` so `clearScroll` is always invoked, even when the loop exits with an exception. Applies to all `scroll` / `scrollWith` overloads in `ElasticsearchUtil`.

## Affected file

- `operate/schema/src/main/java/io/camunda/operate/util/ElasticsearchUtil.java` (methods `scroll`, `scrollWith`)

### SUPPORT TICKETS
 - https://jira.camunda.com/browse/SUPPORT-31925

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #50892

### CODE REVIEW

**Comment by houssain-barouni** [comment]
Failing Operate / [IT] Import is fixed in https://github.com/camunda/camunda/pull/50914

File: operate/schema/src/main/java/io/camunda/operate/util/ElasticsearchUtil.java [hunk 1]
```diff
@@ -503,29 +503,31 @@ public static <T> List<T> scroll(
...
-      response = esClient.scroll(scrollRequest, RequestOptions.DEFAULT);
+        response = esClient.scroll(scrollRequest, RequestOptions.DEFAULT);
 
-      scrollId = response.getScrollId();
-      hits = response.getHits();
+        scrollId = response.getScrollId();
+        hits = response.getHits();
+      }
+    } finally {
+      clearScroll(scrollId, esClient);
```
Comment (mustafadagher) [inline operate/schema/src/main/java/io/camunda/operate/util/ElasticsearchUtil.java:528]: ❓ is there no similar thing needed for opensearch?

Comment (houssain-barouni) [reply operate/schema/src/main/java/io/camunda/operate/util/ElasticsearchUtil.java:528]: Opensearch implementation was good
https://github.com/camunda/camunda/blob/a42e46e3f595d7b13b81b7610cb7aefb398267a8/operate/schema/src/main/java/io/camunda/operate/store/opensearch/client/sync/OpenSearchDocumentOperations.java#L168-L171

**Review by mustafadagher — APPROVED** [review]
LGTM! 👍
