### PR TITLE
Do not log health status unnecessarily

### LINKED ISSUE #9207: Partition is healthy is logged unnecessarily
**Describe the bug**

Partition is logged as healthy repeatedly. However we do not see it becoming unhealthy. This is just noise. We should log only if there is a change in the health status.

image

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

* Compare current and previous healthstatus instead of healthreport 

## Related issues

closes #9207

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: util/src/main/java/io/camunda/zeebe/util/health/CriticalComponentsHealthMonitor.java [hunk 1]
```diff
@@ -105,26 +105,15 @@ private void calculateHealth() {
     final var previousReport = healthReport;
     healthReport = calculateStatus();
 
-    if (previousReport == healthReport) {
+    if (previousReport.getStatus() == healthReport.getStatus()) {
```
Comment (oleschoenburg) [inline util/src/main/java/io/camunda/zeebe/util/health/CriticalComponentsHealthMonitor.java:108]: :question: I could imagine that sometimes we are setting the status to `UNHEALTHY` first and then adding details such as an underlying exception later. In that case we wouldn't log the details since the status hasn't changed. So maybe we need to check status and issue for equality here?

Comment (deepthidevaki) [reply util/src/main/java/io/camunda/zeebe/util/health/CriticalComponentsHealthMonitor.java:108]: You mean when it becomes unhealthy two times in a row for two different reasons?

Comment (oleschoenburg) [reply util/src/main/java/io/camunda/zeebe/util/health/CriticalComponentsHealthMonitor.java:108]: No, but that's another example! I meant something where a component reports `UNHEALTHY` without setting the issue at first. When it later adds an issue and still reports `UNHEALTHY`, we'd want to log that.

Comment (deepthidevaki) [reply util/src/main/java/io/camunda/zeebe/util/health/CriticalComponentsHealthMonitor.java:108]: Would that happen? 
Anyway, I will change the check to compare two healthReports.

**Review by lenaschoenburg — APPROVED** [review]
Thanks @deepthidevaki, looks good to me! :+1:

**Comment by deepthidevaki** [comment]
bors merge
