### PR TITLE
fix: add RESOLVE IncidentState which was missing

### LINKED ISSUE #37288: NullPointerException in SearchQueryResponseMapper when IncidentEntity state is null
### 

### 

### 

### 

### Description

A NullPointerException occurs in the SearchQueryResponseMapper when calling IncidentEntity$IncidentState.name() because IncidentEntity.state() is null. This breaks the incident search feature and may indicate missing or invalid incident state data.

Excerpt from stack trace:

    java.lang.NullPointerException: Cannot invoke "io.camunda.search.entities.IncidentEntity$IncidentState.name()" because the return value of "io.camunda.search.entities.IncidentEntity.state()" is null
        at io.camunda.zeebe.gateway.rest.SearchQueryResponseMapper.toIncident(SearchQueryResponseMapper.java:808)

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.search.entities.IncidentEntity$IncidentState.name()" because the return value of "io.camunda.search.entities.IncidentEntity.state()" is null
        at io.camunda.zeebe.gateway.rest.SearchQueryResponseMapper.toIncident(SearchQueryResponseMapper.java:808)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
        at io.camunda.zeebe.gateway.rest.SearchQueryResponseMapper.toIncidents(SearchQueryResponseMapper.java:794)
        at java.base/java.util.Optional.map(Unknown Source)
        at io.camunda.zeebe.gateway.rest.SearchQueryResponseMapper.toIncidentSearchQueryResponse(SearchQueryResponseMapper.java:468)
        at io.camunda.zeebe.gateway.rest.controller.IncidentController.search(IncidentController.java:93)
        at io.camunda.zeebe.util.Either$Right.fold(Either.java:445)
        at io.camunda.zeebe.gateway.rest.controller.IncidentController.searchIncidents(IncidentController.java:68)
        ... (rest of stack trace omitted for brevity)
```

</p>
</details>

Possible reason: IncidentEntity.state() can be null if IncidentEntityTransformer.toState() returns null, which may occur if the incident data is incomplete or the transformation logic fails to map a valid state.

### Steps to reproduce

1. Trigger an incident search via the REST API.
2. Ensure there is an IncidentEntity with a null state (e.g. due to incomplete incident data or transformation failure).
3. Observe the NullPointerException in SearchQueryResponseMapper.toIncident().

### Current behavior

The incident search fails with a NullPointerException when an IncidentEntity has a null state.

### Expected behavior

The system should gracefully handle incidents with null state and not throw a NullPointerException. A proper error message or a default/fallback state should be used.

### Environment

SaaS

### Version

`8.8.0-alpha7`

### Rootcause

Likely cause: IncidentEntity.state() returns null, which can happen if IncidentEntityTransformer.toState() returns null. However, toIncident() assumes state is always non-null and directly calls .name().

### Solution ideas

Add a null check for IncidentEntity.state() in SearchQueryResponseMapper.toIncident() before calling .name(). Consider handling or logging invalid or incomplete incident states.

### Dev -> QA handover

_No response_

### Links

- Seen in [SUPPORT-30488](https://jira.camunda.com/browse/SUPPORT-30488)

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

add RESOLVE IncidentState which was missing, also throw an error if this happens again so the cause of the issue is clear.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #37288

### CODE REVIEW

**Review by houssain-barouni — COMMENTED** [review]
🧪 @EuroLew can you add a unit test asserting that all `io.camunda.zeebe.protocol.record.intent.IncidentIntent` enum values can be mapped to `IncidentState`

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/ElasticsearchIncidentUpdateRepository.java [hunk 1]
```diff
@@ -348,6 +349,16 @@ private PendingIncidentUpdateBatch createPendingIncidentBatch(
...
       final var entity = hit.source();
       final var newState = IncidentState.createFrom(entity.intent());
+
+      if (newState == null) {
+        final var errMsg =
+            String.format(
+                "Pending incident has a new state of [%s], which is not a valid IncidentState, should be on of %s",
+                entity.intent(), Arrays.toString(IncidentState.values()));
+        logger.error(errMsg);
+        throw new IllegalStateException(errMsg);
```
Comment (yohanfernando) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/incident/ElasticsearchIncidentUpdateRepository.java:358]: _Ideally_, you should either throw the exception or log, not both. We should really log where we are handling the exception, rather than where its thrown..

**Comment by EuroLew** [comment]
> 🧪 @EuroLew can you add a unit test asserting that all `io.camunda.zeebe.protocol.record.intent.IncidentIntent` enum values can be mapped to `IncidentState`

added

**Review by yohanfernando — APPROVED** [review]
lgtm 👍
