### PR TITLE
fix(journal): always release acquired read lock

### LINKED ISSUE #8369: Acquiring a write lock in the Journal blocks installing a received snapshot for ever
**Describe the bug**

Based on the observations made in #7992, the follower could not install a received snapshot: https://github.com/camunda-cloud/zeebe/issues/7992#issuecomment-944311204

According to the thread dump in #7992, the installation of the snapshot is blocked when trying to acquire a write lock:

image

The write lock cannot be acquired, because a read lock is already held which was acquired when trying to open a reader. But the read lock will never be released because opening the reader failed with the exception `"java.lang.IllegalStateException: Segment not open`:

https://github.com/camunda-cloud/zeebe/blob/2dee25fcb748d8a9c6457eee465d08fd5a4d5471/journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java#L211-L218

**To Reproduce**
1. Acquire a read lock, when trying to open a reader
2. Let opening the reader fail
3. Try to install a new snapshot, which will acquire a write lock on the same journal

**Observed Behavior:**
* The Raft thread cannot acquire the write lock, because a read lock is held already.
* This blocks the Raft thread so that the snapshot cannot be installed.
* Additionally, an Actor Thread that executes an Actor Job to compact the log is waiting for the completion of a future which must be completed by the blocked Raft thread.
image

**Expected behavior**
* When opening the reader fails unexpectedly, the read lock is always released.
* The Raft thread and other threads are not blocked by it.

**Environment:**
 - Zeebe Version: 1.2.5

---

related to #7992

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

* Release read lock in a `finally` block so that the lock is also released in a failure case

## Related issues

closes #8369 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java [hunk 1]
```diff
@@ -624,6 +624,27 @@ void shouldBeAbleToResetAgainWhileThePreviousFileIsNotDeleted() {
...
+    // expect
+    assertThat(segment.isOpen()).isFalse();
+    assertThatThrownBy(() -> journal.openReader()).withFailMessage("Segment not open");
+
+    // when
+    journal.reset(100);
+
+    // then
+    assertThat(journal.getJournalIndex().lookup(journalIndexDensity)).isNull();
+    assertThat(journal.getJournalIndex().lookup(2 * journalIndexDensity)).isNull();
```
Comment (oleschoenburg) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:645]: :thought_balloon: I don't understand how these two assertions test that the read lock is released. I think what we are really testing here is whether the `journal.reset(...)` finishes?

Comment (romansmirnov) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:645]: Correct! The test case tests whether the read lock is released implicitly when `journal.reset(...)` finishes. Because it is not possible to assert the release of the read lock explicitly, I decided to assert the effects that result out of `journal.reset()` (which I copied and pasted from another test case in the same test class). Otherwise, a test case without any assertions at the end does not seem to be useful (at least for me).

What could we do to improve that test case?

1. Add a comment to the assertions to make my intent transparent/explicit.
2. Assert other things, but not sure which one.
3. Rewrite the test case may be as follows (pseudo-code):
```
@Test
void shouldReleaseReadLock() {
  // given
  final var journal = openJournal(5);

  // delete first segment so that it closes
  final var segment = journal.getFirstSegment();
  segment.delete();

  // expect
  assertThat(segment.isOpen()).isFalse();
  assertThatThrownBy(() -> journal.openReader()).withFailMessage("Segment not open");

  final var latch = new CountDownLatch(1)

  // when
 new Thread(() -> {
    journal.reset(100));
    latch.countDown();
  }).start();

  assertThat(latch.await(5, TimeUnit.SECONDS)).isTrue();
}
```

After giving it a second thought, I would go with the third option (i.e., re-writing the test case as suggested). That way, the test case is much more explicit about the scenario and the expected result.

WDYT? Do you see any other alternatives?

Comment (oleschoenburg) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:645]: I like option three, let's do it this way :+1:

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java [hunk 2]
```diff
@@ -211,10 +211,13 @@ public void flush() {
...
-    readers.add(reader);
-    releaseReadlock(stamped);
-    return reader;
+    try {
+      final var reader = new SegmentedJournalReader(this);
+      readers.add(reader);
+      return reader;
+    } finally {
+      releaseReadlock(stamped);
+    }
```
Comment (Zelldon) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:220]: Can we check whether there are more cases like this? I feel again uncomfortable with this lock strategy. Maybe just create an issue to invest time in this.

**Review by ChrisKujawa — APPROVED** [review]
Nice catch and thanks  for fixing @romansmirnov :100: :medal_military:

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java (hunk 1 above)
Comment (Zelldon) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:645]: What I not like is that we couple these test a lot how it is implemented, which is likely to change and than we need to change this test. But I see currently no other better way unfortunately, except moving the lock/release logic into a separate class and using it as a composite in the journal. In that way we could test the lock/release logic separately.

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java (hunk 2 above)
Comment (romansmirnov) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:220]: I am not completely sure what you mean by that and what makes you uncomfortable.

To get a first overview of where locks are used, I scanned the source code for the usage of different locks (like `StampedLock` or `ReentrantLock`). For example, the `StampedLock` is used only in the `SegmentedJournal`, or the `ReentrantLock` is used in the class `CompletableActorFuture`. But I could not find any other usage of those locks or others in the source code.

As I am not into the entire code base yet, do you see/know any other locks being used? Also, what would be the separate issue about? Would it be about to look for other locking cases to ensure that the locks are properly released? Or would it be to investigate other locking options to avoid that way of locking? If it is the latter, could you please give a bit of context on what kind of problems you see with this locking strategy (or what makes you uncomfortable with those)?

Comment (Zelldon) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:220]: > As I am not into the entire code base yet, do you see/know any other locks being used? Also, what would be the separate issue about? Would it be about to look for other locking cases to ensure that the locks are properly released? Or would it be to investigate other locking options to avoid that way of locking? If it is the latter, could you please give a bit of context on what kind of problems you see with this locking strategy (or what makes you uncomfortable with those)?

For me it would be more like checking whether we have in other places the same issue

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java (hunk 1 above)
Comment (romansmirnov) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:645]: Thanks for your input, @Zelldon. I think I get your point. However, to keep this PR as simple as possible, I would suggest including your suggestion as a to-do in the separate issue mentioned in the comment below: https://github.com/camunda-cloud/zeebe/pull/8372#discussion_r768483240. Meaning, when checking the code-base for other locking patterns, it turns out that there are several occurrences of such a locking pattern, then we should put that concern in a separate class and adjust the test cases as necessary. But for now, I would go with the test case as suggested above.

Are you okay with that approach?

Comment (Zelldon) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:645]: Yes thanks @romansmirnov

**Review by lenaschoenburg — APPROVED** [review]

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java (hunk 2 above)
Comment (romansmirnov) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:220]: Here is the ticket: #8382

**Comment by romansmirnov** [comment]
bors abort

**Comment by romansmirnov** [comment]
bors cancel

**Comment by romansmirnov** [comment]
bors retry
