### PR TITLE
[Issue#31464] Resolving "Too many open files" error in atomix cluser module tests

### LINKED ISSUE #31464: "Too many open files" error when running tests in atomix-cluser module
**Summary**

- How often does the test fail? Always
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

<details><summary>Too many open files</summary>
<pre>
java.nio.file.FileSystemException: /var/folders/7n/yx2t1r_j0pl9057qt17nw6vm0000gn/T/16935143966505870533/0/snapshots/snapshots: Too many open files

	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:115)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:452)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:445)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:288)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:356)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2574)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2606)
	at io.camunda.zeebe.util.FileUtil.deleteFolder(FileUtil.java:134)
	at io.atomix.raft.RandomizedRaftTest.shutDownRaftNodes(RandomizedRaftTest.java:79)
</pre>
</details>

**Hypotheses**

Probably a file leak, there are thousand of thousand of files that get opened when running tests. The number of opened files will increase over time.

**Logs**

Despite I have not hard limit for the file descriptor resource:

```
simonegiusso@MacBook-Air-2 camunda % ulimit -Hn                                                                                                                                                                                                    
unlimited
```

I've the above error. I can replicate it by just running `RandomizedRaftTest` test. This test `livenessTestWithRestarts` will constantly fail. If running all the tests in the module, more tests will fail. Running just`RandomizedRaftTest` fails on my machine but may not fail on yours.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

P.S. I'm working already on the issue

### PR DESCRIPTION
**Pull request by SimoneGiusso**
## Description

The `io.atomix.raft.impl.RaftContext` handles a `MetaStore` object. This object creates and opens a file (see its constructor).  There are tests, like `RandomizedRaftTest` that uses the `ControllableRaftContexts` class, which creates raft contexts, stored in the `raftServers` map.

The `ControllableRaftContexts` creates (or better recreate) `RaftContext`s (which is `AutoClosable`) over and over during the test execution without closing it. That's a problem because it can create over 50'000  `RaftContext` during a single test execution, which translates in the same amount of files (actually can be even more, as a `MetaStore` creates more than one file) being and left open. 

You can check this by adding this method:

```java
    private static void printOpenedFilesByThisProcess(){
        OperatingSystemMXBean os = ManagementFactory.getOperatingSystemMXBean();
        if(os instanceof UnixOperatingSystemMXBean){
            System.out.println("Number of open fd: " + ((UnixOperatingSystemMXBean) os).getOpenFileDescriptorCount());
        }
    }
```

and call it in the `initOperations`. You should see that at every test/property, the amount of file opened increases over time. You can actually see this also between the execution of the same property with the different parameters or just by monitoring the opened file by the PID executing the test using a monitoring tool.

## How the issue has been investigated

Once the error has been understood, I've collected information about the methods which, after called, were leaving a file opened. I achieved this by creating an aspect around all the methods in the `io.atomix` package. This gave me a sort of stack trace of the method that was opening a file, and confirming that the callers were not closing the file. This was enough to start look at the code involved and find the issue (luckily was related to a test class) when putting an entry in the `raftServers` map.

## Related issues

closes #31464

### CODE REVIEW

File: zeebe/atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java [hunk 1]
```diff
@@ -213,6 +212,16 @@ public RaftContext createRaftContext(
     return raft;
   }
 
+  private RaftContext addRaftServer(final MemberId memberId, final RaftContext raftContext) {
+    final var currRaftContext = raftServers.get(memberId);
+    if (currRaftContext != null) {
+      currRaftContext.close();
+    }
+
+    raftServers.put(memberId, raftContext);
```
Comment (SimoneGiusso) [inline zeebe/atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java:221]: `MemberId` is created by `nodeId` which is just created from the sequence `1...nodeCount`.  nodeCount is defined once, when the `ControllableRaftContexts.java` get constructed (final class variable). `raftServers.put(memberId, raftContext);` get called over and over, during the tests, with the same key - memberId.

**Review by lenaschoenburg — COMMENTED** [review]
Thanks for you contribution!
Could you point out some code paths where the RaftContext is not closed?

On first scan, everything already looks correct to me:
1. `RandomizedForceConfigureTest` and `RandomizedRaftTest` call `ControllableRaftContexts#shutdown` in an `@AfterTry`.
2. `CandidateRoleTest` calls `ControllableRaftContexts#shutdown` in an `@AfterEach`.
3. `ControllableRaftContexts#restart` and `ControllableRaftContexts#restartWithDataLoss` close the previous context before replacing it.

File: zeebe/atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java [hunk 2]
```diff
@@ -428,10 +414,9 @@ public void restartWithDataLoss(final MemberId memberId) {
       newContext.getCluster().bootstrap(raftServers.keySet());
     }
 
-    raftServers.put(memberId, newContext);
```
Comment (SimoneGiusso) [inline zeebe/atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java:431]: This is not needed since the newContext is added to raftServers  via `createRaftContextForMember`

**Review by lenaschoenburg — COMMENTED** [review]
>Exactly, apart from point 3! This is were the leak resides. raftContext.getThreadContext().execute(raftContext::close); doesn't close the raft simply because the .close() method never gets called!

Oh right, that's a nice catch, thanks for explaining :+1: 

:x: We should still ensure that the raft context is closed in the right thread context though, otherwise we might run into race conditions, for example when the raft thread tries to write to the meta store while we are currently closing it.
To do that, we could use the `runUntilDone` method that you incidentally removed because it wasn't used anymore.
So after scheduling the close, wait for completion with `runUntilDone`. This has the same effect, ensuring that the close runs, but without running close concurrently.
Could you give this a try and see if it works? :pray: 

Less important, but before we merge there's two things that need adjustment:
1. Code formatting appears to be broken, you can fix it by running `mvn spotless:apply`
2. Commit messages should follow this format: https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#commit-message-guidelines

**Comment by SimoneGiusso** [comment]
Alright. Intellij was suggesting the formatting. I thought it was folliwing the Camunda style set up for the IDE. 

Anyway, yes I called simply `.close()` sequentially because I found it simpler to read and think of and I didn't notice any problems about concurrency or race conditions (the tests pass). But ok we can use `runUntilDone` ofc.

**Review by lenaschoenburg — APPROVED** [review]
Thanks for your contribution, it's really appreciated :rocket: The changes look good to me now.
There seems to be some hiccup in our CI that I'm checking on internally, once that is resolved, I'll merge this.

**Comment by lenaschoenburg** [comment]
@SimoneGiusso I've rebased your PR, hoping that https://github.com/camunda/camunda/pull/31663 unblocks us here.
