### PR TITLE
fix: cache JSON value in VariableRecord to avoid redundant MsgPack-to-JSON conversions

### LINKED ISSUE #45807: We copy variables multiple times during exporting
### 

### 

### 

### 

### Description

We seem to convert the variables to json during our exporting. Instead of doing this once, we seem to do it at least three times.

This came up during investigating new profiling results.

### Steps to reproduce

1. Create a benchmark
2. Run a profile

### Current behavior

Image

[flamegraph-alloc-camunda-2 (1).zip](https://github.com/user-attachments/files/25292769/flamegraph-alloc-camunda-2.1.zip)

### Expected behavior

We do it once, and reuse the json.

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by EuroLew**
## Summary

- Cache the JSON string returned by `VariableRecord.getValue()` to eliminate redundant MsgPack-to-JSON conversions during export, where multiple handlers call `getValue()` 7-10 times per record
- Add cache invalidation in `setValue()`, `setValue(offset, length)`, and `reset()` (also covers `wrap()`)

## Problem

During export, a single `VARIABLE` record is dispatched to multiple handlers (`VariableHandler`, `UserTaskVariableHandler`, `ListViewVariableFromVariableHandler`) that collectively call `getValue()` 7-10 times. Each call performed a full MsgPack-to-JSON conversion including `byte[]` copies, `ByteArrayInputStream`/`ByteArrayOutputStream` allocations, and Jackson `JsonParser`/`JsonGenerator` instantiation. This was visible as a significant allocation hotspot in flamegraphs.

closes #45807

### CODE REVIEW

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java [hunk 1]
```diff
@@ -47,6 +47,12 @@ public final class VariableRecord extends UnifiedRecordValue implements Variable
   private final LongProperty rootProcessInstanceKeyProp =
       new LongProperty(ROOT_PROCESS_INSTANCE_KEY_KEY, -1L);
 
+  /**
+   * Cached JSON representation of the value. Lazily computed on first call to {@link #getValue()}
+   * and invalidated when the underlying value changes via {@link #setValue} or {@link #wrap}.
+   */
+  private String cachedJsonValue;
```
Comment (entangled90) [inline zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java:58]: 🔧 I wonder if we need to add a `volatile` or not 🤔 
We might mark this as `transient` so it's skipped by the `Populator` maybe?

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java [hunk 2]
```diff
@@ -59,14 +65,23 @@ public VariableRecord() {
...
 
+  @Override
+  public void reset() {
+    super.reset();
+    cachedJsonValue = null;
+  }
+
   @Override
   public String getName() {
     return BufferUtil.bufferAsString(nameProp.getValue());
```
Comment (entangled90) [inline zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java:81]: ❓ do we need to cache this as well?

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java [hunk 3]
```diff
@@ -131,6 +147,7 @@ public VariableRecord setName(final DirectBuffer name) {
 
   public VariableRecord setValue(final DirectBuffer value, final int offset, final int length) {
     valueProp.setValue(value, offset, length);
+    cachedJsonValue = null;
```
Comment (entangled90) [inline zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java:165]: 💭 we might want to check if the buffer reference is the same as the current one, but it's probably unlikely so it's ok to not check at all

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java (hunk 1 above)
Comment (entangled90) [reply zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java:58]: I think `transient` is not really necessary anyway.

Comment (EuroLew) [reply zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java:58]: I don't think `volatile` or `transient` is needed as the stream processor is single threaded and each exporter director has its own record values cache.

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java (hunk 2 above)
Comment (EuroLew) [reply zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java:81]: a byte array allocation + utf 8 decode is much much cheaper than msg pack, its probably called a lot of times so it is a possible optimisation. If this PR get's merged I'll also implement for name

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java (hunk 1 above)
Comment (entangled90) [reply zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/variable/VariableRecord.java:58]: 🔧 we might even introduce a `JsonBinaryValue` subclass that caches the json conversion. I see that there a few occasions of `BinaryValue` which are then converted to json, so not sure if this would apply there as well. 
It would make this caching "cleaner" and easier to toggle on/off

File: zeebe/protocol-test-util/src/main/java/io/camunda/zeebe/test/broker/protocol/ImplRecordValuePopulator.java [hunk 4]
```diff
@@ -156,8 +155,14 @@ private static void populateBinaryProperty(
       throws IllegalAccessException {
     final BinaryProperty binaryProperty = (BinaryProperty) field.get(implInstance);
     if (binaryProperty != null) {
-      final String randomString = random.nextObject(String.class);
-      binaryProperty.setValue(BufferUtil.wrapString(randomString));
+      // Encode as valid MsgPack so that getters calling MsgPackConverter.convertToJson() work
+      final Map<String, Object> randomMap = new HashMap<>();
```
Comment (entangled90) [inline zeebe/protocol-test-util/src/main/java/io/camunda/zeebe/test/broker/protocol/ImplRecordValuePopulator.java]: 🔧 so now binary value can only contains a json-encoded string rather than a generic string.  This might reduce the test coverage as `BinaryValue` doesn't have to be a json string.

Was this necessary? we didn't change the API of `VariableRecord`

**Review by entangled90 — APPROVED** [review]
Pre-approving, just take a look at my comments before merging.

File: zeebe/protocol-test-util/src/main/java/io/camunda/zeebe/test/broker/protocol/ImplRecordValuePopulator.java (hunk 4 above)
Comment (EuroLew) [reply zeebe/protocol-test-util/src/main/java/io/camunda/zeebe/test/broker/protocol/ImplRecordValuePopulator.java]: you're right going to keep as binary string and just add a carve out in the if statement in `populate`

**Comment by entangled90** [comment]
@EuroLew  We should backport this to 8.8 as well
