### PR TITLE
test: add authorized tenant search test

### LINKED ISSUE #31621: [Tenants] New user cannot read users of a Tenant
### 

### 

### 

### 

### Description

Search users for a tenant endpoint throws an error.

### Steps to reproduce

1. create a new test user and assign it to the tenantA
2. grant *  for applications, tenants and resources for a user
3. as a test user execute 'search users for tenant' request

### Current behavior

`{
    "type": "about:blank",
    "title": "java.lang.IllegalArgumentException",
    "status": 400,
    "detail": "Expected to handle REST API request, but JSON property was invalid",
    "instance": "/v2/tenants/tenantB/users/search"
}`

### Expected behavior

User 'test' should be able to read users assigned for the tenant

### Environment

SM

### Version

- Component Version: [8.8]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Add test coverage for searching tenant-assigned users by authorized user requests.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #31621

### CODE REVIEW

**Comment by koevskinikola** [comment]
Hey @nicpuppa, do you have some time to review this PR?

It only adds (basic) test coverage for tenant-assigned user search to assert that the bug isn't present anymore.

We're still missing a Java client command for it, which will be added with https://github.com/camunda/camunda/issues/34333. I noted there that the test should be expanded.

**Comment by nicpuppa** [comment]
Hey @koevskinikola some tests are failing, please have a look 👀

**Comment by koevskinikola** [comment]
That's strange, I ran the test multiple times locally, and it passed without issues. I'll have a look later today or next Monday.

**Comment by nicpuppa** [comment]
If I find time today I'll also try to run them locally

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/UsersByTenantSearchTest.java [hunk 1]
```diff
@@ -0,0 +1,169 @@
...
+      @Authenticated(USER_USERNAME_2) final CamundaClient user2Client,
+      @Authenticated(USER_USERNAME_3) final CamundaClient user3Client) {
+
+    createTenant(adminClient, TENANT_ID);
+    assignUserToTenant(adminClient, ADMIN_USER_NAME, TENANT_ID);
+    assignUserToTenant(adminClient, USER_USERNAME_2, TENANT_ID);
+    assignUserToTenant(adminClient, USER_USERNAME_3, TENANT_ID);
+
+    waitUntilExactUsersExist(
+        adminClient, ADMIN_USER_NAME, TENANT_ID, ADMIN_USER_NAME, USER_USERNAME_2, USER_USERNAME_3);
```
Comment (koevskinikola) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/UsersByTenantSearchTest.java:93]: @nicpuppa the test should be fixed now. The issue was that the user assignment wasn't written to secondary storage before the test case. I added an assertion that will block until the users can be read from secondary storage by an "admin user".

Comment (nicpuppa) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/UsersByTenantSearchTest.java:93]: Sorry I didn't had time, I'll look at the PR shortly

**Review by nicpuppa — APPROVED** [review]
