### PR TITLE
fix: determine element incident status from incident field

### LINKED ISSUE #35169: Parent instance not shown when call activity has incident in child process
### 

### 

 

### 

### 

### Description

When filtering process instances in Operate using a selected call activity and setting the instance state to “Incident”, the expected process instances are not shown in the results, even though an incident exists in the called child process. The issue seems to stem from a mismatch between how incident presence is tracked (hasIncident) and how it’s queried (via errorMessage).

This leads to inconsistencies between:

- The diagram, which correctly shows the incident marker on the call activity
- The statistics API, which reports the incident
- The process instance list, which fails to return the parent instance

### Steps to reproduce

1. Deploy a process with a call activity (either standalone or inside a multi-instance sub-process)
2. The call activity should invoke a child process that throws an incident (e.g. a faulty timer catch event)
3. Go to the Operate UI → Processes page
4. Select the main process
5. Filter by the call activity flow node
6. Set instance state filter to Running -> Active = false, Incident = true, 
7. Observe that no process instances are listed

https://github.com/user-attachments/assets/eff0cff3-8c4d-4bbc-865d-35b93912b411

### Current behavior

- No process instance is shown when filtering by call activity and incident state
- This happens even though:
   - The diagram shows the incident on the call activity
   - The statistics API includes the incident
   - The element instance for the call activity has hasIncident = true

### Expected behavior

- When filtering by a call activity and selecting “Incident”, any process instance that has an incident in the called child process should be shown
- The UI behaviour should align with the diagram markers and statistics API

### Environment

SaaS & SM

### Version

- Component Version: 8.7.5

### Rootcause

- The filtering logic in operate-list-view checks the errorMessage field, which is tied to the process instance
- In this scenario, errorMessage is null because the incident originates in the child process
- However, the element instance for the call activity correctly has hasIncident = true

### Solution ideas

- Update the filtering logic in operate-list-view to check the hasIncident field on the element instance instead of relying solely on errorMessage

- Ensure that filtering by flow node + incident state correctly includes parent process instances when incidents exist in child processes

### Links

related to: [SUPPORT-28102](https://jira.camunda.com/browse/SUPPORT-28102)

### PR DESCRIPTION
**Pull request by tsedekey**
## Description

This PR fixes an issue where the parent instance was not shown in the Operate UI when the call activity had an incident in the child process. The fix ensures that the incident status of an element is determined directly from the incident field, which correctly reflects the presence of an incident, even if it originates in a subprocess.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #35169

### CODE REVIEW

**Review by RomanJRW — APPROVED** [review]
Change looks reasonable to me, but can we have a test to catch this?

**Comment by tsedekey** [comment]
> Change looks reasonable to me, but can we have a test to catch this?

Thanks for the review @RomanJRW. I have added unit tests as suggested!

File: operate/webapp/src/test/java/io/camunda/operate/webapp/elasticsearch/QueryHelperTest.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+    final PermissionsService permissionsService = mock(PermissionsService.class);
+    final ListViewQueryDto queryDto =
+        new ListViewQueryDto().setActivityId(activityId).setIncidents(true).setRunning(true);
+
+    queryHelper.setPermissionsService(permissionsService);
+    when(permissionsService.getProcessesWithPermission(PermissionType.READ_PROCESS_INSTANCE))
+        .thenReturn(ResourcesAllowed.wildcard());
+
+    final QueryBuilder qb = queryHelper.createQueryFragment(queryDto);
+    assertNotNull(qb, "QueryBuilder should not be null");
```
Comment (RomanJRW) [inline operate/webapp/src/test/java/io/camunda/operate/webapp/elasticsearch/QueryHelperTest.java]:
```suggestion
    assertThat(qb).as("QueryBuilder should not be null")).isNotNull();
```

File: operate/webapp/src/test/java/io/camunda/operate/webapp/elasticsearch/QueryHelperTest.java [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+    final String queryString = qb.toString();
+    assertTrue(queryString.contains("activityState"), "Should contain activityState field");
```
Comment (RomanJRW) [inline operate/webapp/src/test/java/io/camunda/operate/webapp/elasticsearch/QueryHelperTest.java]:
```suggestion
    assertThat(queryString).as("Should contain activityState field").contains("activityState");
```

etc. below

**Review by RomanJRW — APPROVED** [review]
