### PR TITLE
Require wildcard read permission when retrieving global listeners

### LINKED ISSUE #48056: Resource access check failing when retrieving specific Global Task Listeners via API
### 

### 

### 

### 

### Description

When using the Orchestration Cluster API to retrieve a specific Global User Task Listener through the `/v2/global-task-listeners/{listener-id}` API while authenticated, the request fails with a 500 Internal Server Error.
This does not happen when the request is performed with an anonymous user.

The bug is caused by an error in the implementation of resource access checks for this specific API, requiring a generic `GLOBAL_LISTENER:READ_TASK_LISTENER` permission without specifying the related resource ID. Since the permission to read global listeners is general and not related to individual listeners, the "wildcard" `*` resource ID should always be required.

### Steps to reproduce

Execute a GET request to `/v2/global-task-listeners/{listener-id}` while authenticated as a user

### Current behavior

The request fails with error:
```
Expected one resource id to check resource access, but received none or more than one
```

### Expected behavior

The request is handled correctly, providing the requested information if authorized to do so (permission `GLOBAL_LISTENER:READ_TASK_LISTENER:*`) or returning a 403 error.

### Workaround

Use the search API instead.
URL: `/v2/global-task-listeners/search`
Body:
```
{
  "filter": {
    "id": "{listener-id}"
  }
}
```

### Environment

SaaS & SM

### Version

- Orchestration Cluster: 8.9.0 (unreleased)

### Rootcause

A resource ID needs to be specified when creating the security context to execute the get request related to global listeners:
```
  public GlobalListenerEntity getGlobalTaskListener(final GlobalListenerRecord request) {
    return executeSearchRequest(
        () ->
            globalListenerSearchClient
                .withSecurityContext(
                    securityContextProvider.provideSecurityContext(
                        authentication, GLOBAL_TASK_LISTENER_READ_AUTHORIZATION)) // <--- a resource ID needs to be specified here
                .getGlobalListener(
                    request.getId(), GlobalListenerType.valueOf(request.getListenerType().name())));
  }
```

### Solution ideas

Explicitly require the "wildcard" permission to read global listeners.

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by fabiopaini-camunda**
## Description

When executing a GET request in a search client, access to the retrieved resource is checked through the
DefaultResourceAccessProvider#hasResourceAccess method. The latter expects the provided authorization to either:
- define property-based access
- provide a list of resource IDs
- provide a resource ID supplier If none of those are available, the access check fails with an exception.

Since the permission to read global task listener is all-or-nothing, no resource ID was previously provided in the
GlobalListenerServices#getGlobalTaskListener method, incurring in the above exception.

This behaviour is now correctly mapped by requiring a "wildcard" (`*`) permission of type `READ_TASK_LISTENER` to access global listeners.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #48056

### CODE REVIEW

File: service/src/main/java/io/camunda/service/GlobalListenerServices.java [hunk 1]
```diff
@@ -68,7 +70,8 @@ public GlobalListenerEntity getGlobalTaskListener(final GlobalListenerRecord req
             globalListenerSearchClient
                 .withSecurityContext(
                     securityContextProvider.provideSecurityContext(
-                        authentication, GLOBAL_TASK_LISTENER_READ_AUTHORIZATION))
+                        authentication,
+                        withAuthorization(GLOBAL_TASK_LISTENER_READ_AUTHORIZATION, WILDCARD_CHAR)))
```
Comment (mustafadagher) [inline service/src/main/java/io/camunda/service/GlobalListenerServices.java:74]: 🔧 should we extend the test suite to verify this change works as expected?

Comment (mustafadagher) [reply service/src/main/java/io/camunda/service/GlobalListenerServices.java:74]: I'm not sure if this specific case is tested already here: https://github.com/camunda/camunda/pull/48066

Comment (mustafadagher) [reply service/src/main/java/io/camunda/service/GlobalListenerServices.java:74]: I mean, I see that we have there tests for different authorized users, or one with no auth at all. 

But what if we have just a user with the correct authorization but no resource id (wild card or whatever)

Comment (fabiopaini-camunda) [reply service/src/main/java/io/camunda/service/GlobalListenerServices.java:74]: I can add to the other PR a test with a user having permissions with a non-wildcard resource ID, checking that they are not allowed to use the API. I'll do it now.

Comment (fabiopaini-camunda) [reply service/src/main/java/io/camunda/service/GlobalListenerServices.java:74]: @mustafadagher I added the test in [7a1e475f237660e57f349d659528d28c27f76783](https://github.com/camunda/camunda/pull/48066/changes/7a1e475f237660e57f349d659528d28c27f76783) (PR #48066)

Comment (mustafadagher) [reply service/src/main/java/io/camunda/service/GlobalListenerServices.java:74]: Thanks!

**Review by mustafadagher — APPROVED** [review]
