### PR TITLE
fix: Handle BatchOperation.INITIALIZED event in RDBMS exporter to align state lifecycle with ES/OS

### LINKED ISSUE #44899: RDBMS exporter does not handle `BatchOperation.INITIALIZED` event, causing `state` and `startDate` divergence from ES/OS handling
### Description

RDBMS exporter doesn't handle `BatchOperation.INITIALIZED` event. As a result, batch operations created on RDBMS backend immediately transition to `ACTIVE` state and set their `startDate` on `CREATED` event, whereas ES/OS transitions through `CREATED` -> `ACTIVE` and sets `startDate` on `INITIALIZED`.
This causes divergent `state` and `startDate` semantics between the two exporters, which in turn leads to inconsistent API responses and maintenance burden. This parity bug was discovered when fixing https://github.com/camunda/camunda/issues/42165.

### Steps to reproduce

1. Create a batch operation, running a RDBMS backend
2. Observe that the record is created directly in `ACTIVE` state and `startDate` is set on `CREATED` event
3. Observe ES/OS instance where record is first `CREATED` then transitions to `ACTIVE` on `INITIALIZED` event
4. Compare the `startDate` and `status` between both backends

### Current behavior

- RDBMS exporter creates `BatchOperation` records in `ACTIVE` state and sets `startDate` on handling `CREATED` event
- ES/OS creates record in `CREATED`, then sets `startDate` and leads to `ACTIVE` upon `INITIALIZED` event
- API response for batch operations exposes different behavior for RDBMS and ES/OS

### Expected behavior

- `BatchOperation` event handling should be aligned so both RDBMS and ES/OS:  
  - create the record in `CREATED` state  
  - only transition to `ACTIVE` and set `startDate` on `INITIALIZED` event (mirroring ES/OS)
- API responses and fields should be consistent regardless of storage backend

### Workaround

- Use ES/OS as secondary storage

### Environment

SM

### Version

- Camunda RDBMS exporters: [8.8, 8.9]

### Rootcause

RDBMS exporter does not process `INITIALIZED` event, so never transitions batch operation to `ACTIVE` via event or sets `startDate` at that point; instead, it does so early on `CREATED` event. This is inconsistent with ES/OS exporters implementation.

### Solution ideas

- Implement handling of `BatchOperation.INITIALIZED` event in RDBMS exporter (mirroring `BatchOperationInitializedHandler` in ES/OS)
- Set `startDate` and mark as `ACTIVE` only when receiving `INITIALIZED` event
- Adjust `BatchOperationCreatedExportHandler` (RDBMS) to create in `CREATED` state without setting `startDate`
- Ensure API and all backends expose unified state progression and fields

### Dev -> QA handover

- Resources: 
  - `BatchOperationCreatedExportHandler`, `BatchOperationInitializedHandler`, #42165
- Versions to validate:
  - RDBMS and ES/OS exporters, 8.8 & 8.9
- Release version (in which version this feature will be released):
  - 8.9-alpha-5

### Links

- Discovered while fixing: #42165
- Handler code: `BatchOperationInitializedHandler` (ES/OS), `BatchOperationCreatedExportHandler` (RDBMS)
- Acceptance test: `BatchOperationSearchIT`

### Automated Test Impact

`BatchOperationSearchIT` should be enough to ensure that there no regression after aligning handling of BatchOperation records between ES/OS and RBDMS exporters.

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

This PR aligns the RDBMS exporter's `BatchOperation` lifecycle handling with the ES/OS exporter by introducing support for the `INITIALIZED` event.

### Why

The RDBMS exporter was missing handling for the `BatchOperation.INITIALIZED` event. This caused batch operations to be created directly in `ACTIVE` state with `startDate` set on the `CREATED` event — diverging from ES/OS, which follows a `CREATED` -> `ACTIVE` transition and only sets `startDate` upon `INITIALIZED`. This inconsistency may lead to different API responses depending on the storage backend.

### RDBMS exporter changes
- **`BatchOperationCreatedExportHandler`**: Now creates records in `CREATED` state without setting `startDate`, matching the ES/OS `CREATED` event semantics.
- **`BatchOperationInitializedExportHandler`** *(new)*: Handles `BATCH_OPERATION_INITIALIZATION[INITIALIZED]` events - transitions the batch operation to `ACTIVE` state and sets `startDate` from the record timestamp, mirroring the ES/OS `BatchOperationInitializedHandler`.
- **`RdbmsExporterWrapper`**: Registers the new `BatchOperationInitializedExportHandler` for `ValueType.BATCH_OPERATION_INITIALIZATION`.

### Data layer changes
- **`BatchOperationMapper`**: Added `activate(BatchOperationActivateDto)` method and `BatchOperationActivateDto` record.
- **`BatchOperationMapper.xml`**: Added `activate` SQL update statement that sets `STATE = 'ACTIVE'` and `START_DATE` by `BATCH_OPERATION_KEY`.
- **`BatchOperationWriter`**: Added `activate(batchOperationKey, startDate)` method that enqueues the activation update.

### Tests
- Added `shouldActivateBatchOperation` test to `BatchOperationIT` that verifies a batch operation in `CREATED` state transitions to `ACTIVE` with the correct `startDate` after calling `activate`.
- Fix test failures in `RdbmsExporterBatchOperationsIT` and `RdbmsExporterIT` caused by moving `ACTIVE` state transition logic from the `CREATED` event handler to the new `INITIALIZED` event handler, by adding `batchOperationInitializedRecord` export to all test methods that create batch operations and expect `ACTIVE` state.

## State lifecycle (before & after this change)

| Event         | RDBMS (before) | RDBMS (after) | ES/OS       |
|---------------|----------------|---------------|-------------|
| `CREATED`     | `ACTIVE` + `startDate` | `CREATED` (no `startDate`) | `CREATED` (no `startDate`) |
| `INITIALIZED` | *(not handled)* | `ACTIVE` + `startDate` | `ACTIVE` + `startDate` |

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #44899

### CODE REVIEW

File: qa/acceptance-tests/src/test/java/io/camunda/it/rdbms/exporter/RdbmsExporterBatchOperationsIT.java
Comment (mustafadagher) [inline qa/acceptance-tests/src/test/java/io/camunda/it/rdbms/exporter/RdbmsExporterBatchOperationsIT.java:1]: ❓ is it worth it to add an extra test that just tests that now without an `initialized record` the batch operation state will be `created` and the start date is empty?

File: qa/acceptance-tests/src/test/java/io/camunda/it/rdbms/exporter/RdbmsExporterIT.java [hunk 1]
```diff
@@ -1145,14 +1145,12 @@ public void shouldExportAndDeleteAuthorization() {
   @Test
   public void shouldExportBatchOperationCreatedRecord() {
```
Comment (mustafadagher) [inline qa/acceptance-tests/src/test/java/io/camunda/it/rdbms/exporter/RdbmsExporterIT.java:1146]: 🔧 This test method name assumes we are only testing exporting the `created` record. 
Similar to the suggestion above, I'd leave this to test only the created record export, and create a separate method to test the activation. WDYT?

**Review by mustafadagher — APPROVED** [review]
Thanks @ce-dmelnych 🚀 !

🔧 I only left a couple of suggestions regarding tests.

I think you should also ask for a review from @camunda/data-layer team

**Review by RomanJRW — APPROVED** [review]
Looks good from my perspective. @stoerti - feel free to double check this from your side on RDBMS/Batch Operations

**Comment by mustafadagher** [comment]
@ce-dmelnych did you decide if we will backport this to `stable/8.8`?

File: qa/acceptance-tests/src/test/java/io/camunda/it/rdbms/exporter/RdbmsExporterIT.java (hunk 1 above)
Comment (ce-dmelnych) [reply qa/acceptance-tests/src/test/java/io/camunda/it/rdbms/exporter/RdbmsExporterIT.java:1146]: Yeah, thanks for noticing this, I've adjusted this one to handle only `CREATED` record, and added separate `shouldExportBatchOperationActivatedRecord` test below.

File: qa/acceptance-tests/src/test/java/io/camunda/it/rdbms/exporter/RdbmsExporterBatchOperationsIT.java
Comment (ce-dmelnych) [reply qa/acceptance-tests/src/test/java/io/camunda/it/rdbms/exporter/RdbmsExporterBatchOperationsIT.java:1]: Yep, I think it's fine to have it, so I've covered this scenario in: `shouldExportCreatedBatchOperation` test.

**Review by ce-dmelnych — COMMENTED** [review]
Hey @mustafadagher thanks for your suggestions 🙌🏻 , I've added missing tests (by amending the last [commit](https://github.com/camunda/camunda/pull/45736/changes/ecd3a2525690f146f094c9435a5f4016df52f193)), would you mind to check it again? 🙏🏻

**Review by mustafadagher — APPROVED** [review]
LGTM! 🚀
