### PR TITLE
fix: handle PathNotFoundException

### LINKED ISSUE #34292: handle PathNotFoundException when groupsClaim path is not found
With some sort of expressions as groupsClaim, OidcGroupLoader throws PathNotFoundException when the claim is not available in the token.

### PR DESCRIPTION
**Pull request by maryarm**
## Description

With some sort of expressions as groupsClaim, OidcGroupLoader throws PathNotFoundException when the claim is not available in the token. 
The expected behaviour is if for any reason the expression is not available with claims, it returns empty list for the groups.

## Related issues

closes #34292

### CODE REVIEW

File: security/security-core/src/main/java/io/camunda/security/auth/OidcGroupsLoader.java [hunk 1]
```diff
@@ -47,24 +50,28 @@ public List<String> load(final Map<String, Object> claims) {
...
+        } else {
+          throw new IllegalArgumentException(
+              String.format(DERIVED_GROUPS_ARE_NOT_STRING_ARRAY, groupsClaim));
         }
-      } else {
-        throw new IllegalArgumentException(
-            String.format(DERIVED_GROUPS_ARE_NOT_STRING_ARRAY, groupsClaim));
       }
+    } catch (final PathNotFoundException exception) {
+      LOGGER.warn("Could not load groups from claims {}", claims, exception);
```
Comment (remcowesterhoud) [inline security/security-core/src/main/java/io/camunda/security/auth/OidcGroupsLoader.java:74]: ❓ Sorry I miss some context here. When is this exception thrown? Is it a misconfiguration on the user's side? I'm wondering if the log level should be an error or a warning mostly.

Comment (maryarm) [reply security/security-core/src/main/java/io/camunda/security/auth/OidcGroupsLoader.java:74]: It doesn't happens for an invalid json path, but for some cases like I've put in the test: for example as you can see in the test if I use the `group_names` as the json path, it returns null but if I use `groups.names[*]` and a matching claim doesn't exist in the token then it throws PathNotFoundException.

Comment (remcowesterhoud) [reply security/security-core/src/main/java/io/camunda/security/auth/OidcGroupsLoader.java:74]: Right, and then we just want a warning and returning an empty list of groups, as there were no matches found. Got it! Thank you

**Review by remcowesterhoud — APPROVED** [review]
