### PR TITLE
fix: add the filter for user task implementation

### LINKED ISSUE #26155: fix: re-introduce the user task implementation filter

### PR DESCRIPTION
**Pull request by nathansandi**
## Description

Re-introduce the User Task implementation filter, in order to filter out the job workers from the User Task Search Query. 

In addition: Deploy/ start a process with a job worker, in order to validate it doesnt affect the existent integration tests.

## Related issues

closes https://github.com/camunda/camunda/issues/26155

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/it/client/UserTaskQueryTest.java [hunk 1]
```diff
@@ -67,6 +68,9 @@ static void beforeAll() {
     startProcessInstance("bpmProcessVariable");
     startProcessInstance("processWithForm");
     startProcessInstance("processWithSubProcess");
+    startProcessInstance(
+        "jobWorkerProcess"); // Start a Job Worker instance in order to validate if User Tasks
+    // queries has the same result
```
Comment (tmetzke) [inline qa/integration-tests/src/test/java/io/camunda/it/client/UserTaskQueryTest.java:73]:
```suggestion
    // Start a Job Worker instance to validate if User Tasks queries have the same result
    startProcessInstance("jobWorkerProcess");
```

**Review by tmetzke — APPROVED** [review]
👍
