### PR TITLE
Deploy process with data object and data store

### LINKED ISSUE #8230: BPMN deployment fails due to Data Object
**Describe the bug**

The Zeebe engine refuses to deploy a schema-valid BPMN file that contains a BPMN Data Object

This issue has been discovered during the preparations for the demo of the OMG's BPMN Model Interchange Working Group that is planned for the OMG Technical Meeting during March 21-25, 2022 in Reston, VA USA.

**To Reproduce**

Deploy the attached BPMN file: 
[vacation-request.bpmn.txt](https://github.com/camunda-cloud/zeebe/files/7558801/vacation-request.bpmn.txt)

**Expected behavior**

The BPMN parser of the engine ignores any XML elements that it doesn't know about. It may warn about them. It should fail if a model is not schema-valid.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'vacation-request.bpmn': no transformer found for element type: interface io.camunda.zeebe.model.bpmn.instance.DataObject [ deploy-error ]
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 1.3.0-alpha1
 - Configuration: Camunda Cloud SaaS

Camunda Modeler system information
 * Version: 4.12.0-nightly.20211117
 * Operating System: Linux x86_64 amd64
 * Plugins: BPMN Driven Testing, Layering, BPMN Linter, Rename Technical IDs, Transaction Boundaries, Camunda Property Infos, Camunda Cloud, Cloud Connect
 * Execution Platform: BPMN - Camunda Cloud

### PR DESCRIPTION
**Pull request by skayliu**
## Description

Support deploy and execute process with data object and data store

## Related issues

closes #8230 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by skayliu** [comment]
Hi, @saig0, @korthout. Please take a moment to review this feature when you have time. Thanks. ❤️

**Comment by saig0** [comment]
@skayliu thank you for your contribution. :tada: We'll have a look at your PR in the next few days. :eyes:

File: protocol/src/main/java/io/camunda/zeebe/protocol/record/value/BpmnElementType.java [hunk 1]
```diff
@@ -55,7 +55,12 @@ public enum BpmnElementType {
 
   BUSINESS_RULE_TASK("businessRuleTask"),
   SCRIPT_TASK("scriptTask"),
-  SEND_TASK("sendTask");
+  SEND_TASK("sendTask"),
+
+  // Data
+  DATA_OBJECT(null),
+  DATA_OBJECT_REFERENCE(null),
+  DATA_STORE_REFERENCE(null);
```
Comment (koevskinikola) [inline protocol/src/main/java/io/camunda/zeebe/protocol/record/value/BpmnElementType.java:63]: :x: We can remove this addition. 

The `BpmnElementType` is only used for `ExecutableFlowElement` objects. Since we aim to skip the `BpmnElementType` assignment for non-executable elements in `[FlowElementInstantiationTransformer.java](https://github.com/camunda/zeebe/pull/10845/files#diff-d920f8b5e298a7ea3d2797fc3a85f43ff1ca7cfc9f57df5a0ba1691e5cdf993c), we don't need to define enums for the non-executable elements.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/FlowElementInstantiationTransformer.java [hunk 2]
```diff
@@ -7,6 +7,8 @@
  */
 package io.camunda.zeebe.engine.processing.deployment.model.transformer;
 
+import static io.camunda.zeebe.model.bpmn.validation.zeebe.FlowElementValidator.NON_EXECUTABLE_ELEMENT_TYPES;
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/FlowElementInstantiationTransformer.java:10]: As mentioned above, instead of importing the `NON_EXECUTABLE_ELEMENT_TYPES` HashSet, let's duplicate this data into this class.

**Review by koevskinikola — CHANGES_REQUESTED** [review]
Hi @skayliu, I added some review hints to the PR.

:+1: In general, the fix looks good. I especially liked the additional test coverage.

**Comment by skayliu** [comment]
Hi @koevskinikola. I've fixed all review comments. Please check this out.

**Review by koevskinikola — APPROVED** [review]
Looks good now. Thanks for the contribution! :rocket: 

bors merge

**Comment by menski** [comment]
bors merge
