### PR TITLE
 fix: don't pollute the command cache 

### LINKED ISSUE #29735: Pollution of command cache breaks scheduled tasks
The `BoundedScheduledCommandCache` is responsible for "caching" commands written by scheduled commands such as the job timeouts, timer trigger and message expiry, to avoid repeatedly writing the same commands over and over again before the first one is processed.
This mechanism works by adding commands to the cache when they are written and removing from the cache when they are processed.

We have now detected a bug where this cache is polluted such that some commands are not removed from the cache, thus blocking progress of scheduled tasks.

The problem is that _adding_ to the cache and _removing_ from the cache are not ordered correctly. Adding occurs in the actor responsible for scheduled tasks, asynchronously after successful writing of commands. Removal occurs in the processing actor, after the successful commit of state changes. We cannot prevent that sometimes, the scheduled tasks actor is notified about a succesful write _after_ the write occurred and the processing actor already processed the same command.

Symptoms may include:
- Jobs not timing out
- Jobs not retrying with backoff
- Timers not triggering
- Messages not expiring

Once the cache is polluted, only a restart or leader change can clear the cache and thus restore normal operation.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This fixes #29735 where the command cache was polluted with commands that were processed before they were added to the cache.

Instead of only persisting staged cache entries after a successful write, we now do so before trying to write. In rare cases where writing fails, we perform a rollback by removing all staged, and by now persisted, cache entries. There is a small possibility that rollback removes entries that were added by other cache users. This is safe though, the cache is only an optimization.

Sadly I didn't manage to write a regression test for this. I think that's okay though, the bug is well understood and relatively simple.

### CODE REVIEW

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/engine/impl/BoundedCommandCache.java [hunk 1]
```diff
@@ -64,8 +64,32 @@ public BoundedCommandCache(final int capacity, final IntConsumer sizeReporter) {
...
+        lock,
+        () -> {
+          final int evictionCount = cache.size() + 1 - capacity;
+          if (evictionCount > 0) {
+            evict(evictionCount);
+          }
+
+          cache.add(key);
+          sizeReporter.accept(cache.size());
+        });
```
Comment (npepinpe) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/engine/impl/BoundedCommandCache.java:78]: :upside_down_face: I find keeping the synchronized methods in private method makes it easier to separate business logic from dealing with concurrency, and thus more readable. Since we don't make use of things like the Checker framework to check for `@GuardedBy` annotations, it's purely for humans - but I would recommend it in general. No super strong argument though.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/engine/impl/BoundedCommandCacheTest.java [hunk 2]
```diff
@@ -94,4 +50,104 @@ private LongHashSet setOf(final long... keys) {
     set.addAll(Arrays.stream(keys).boxed().toList());
     return set;
   }
+
+  @Nested
+  final class BulkOperations {
```
Comment (npepinpe) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/engine/impl/BoundedCommandCacheTest.java:55]: :+1:

**Review by npepinpe — APPROVED** [review]

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/engine/impl/BoundedCommandCache.java (hunk 1 above)
Comment (lenaschoenburg) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/engine/impl/BoundedCommandCache.java]: Done with ae875a55005198a05823f0daf499d7a6a60dfde6
