### PR TITLE
refactor: fix memory leaks and improve performance

### LINKED ISSUE #51576: Address memory leaks and CI instability in Operate frontend tests
### 

### Description

The Operate frontend CI jobs are running into JavaScript OOM (out-of-memory) errors:

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Sample failure logs:
- https://github.com/camunda/camunda/actions/runs/24551387468/job/71777779948
- https://github.com/camunda/camunda/actions/runs/24508206905/job/71632166803#step:7:21

When running unit tests, the current test setup (using vitest with --maxWorkers=1, --no-file-parallelism, --shard=3/4) executes ~60 test files sequentially within a single process. Over time, memory from sources such as JSDOM environments, BpmnModdle circular reference graphs, and MSW handlers accumulates and leaks. When a test fails or times out and is retried, the same process is reused, leading to compounding memory growth and, eventually, OOM crashes (~8GB usage).

Additionally, some "not implemented" errors (e.g., window.prompt) appear sporadically in CI logs.

### Impact

These memory leaks and the current process reuse in test runs cause CI instability, delayed pipelines, and unreliable test results for Operate frontend. Addressing them will improve test reliability, reduce developer friction, and ensure we catch regressions sooner. Reducing persistent memory growth also makes it easier to extend the test suite and ensures results can be trusted in the future.

### PR DESCRIPTION
**Pull request by OmranAbazid**
## Description

Unit tests were running out of memory in CI.

The CI configuration (`--maxWorkers=1 --no-file-parallelism --shard=3/4`) executes ~60 test files sequentially within a single process. Over time, memory accumulates from sources like JSDOM environments, `BpmnModdle` circular reference graphs, and MSW handlers.

When memory pressure increases and a test fails or times out, `retry: 3` re-runs the same file in the *same process*. This leads to a compounding effect, eventually causing an OOM crash (~8GB).

## Improvements

This PR removes key sources of cumulative memory leaks that build up across sequential test execution:

* Orphaned `setInterval` handles
* Stale closure references
* Duplicate `QueryClient` instances

These issues were especially problematic when retries re-executed failing tests in the same process, amplifying memory usage.

## Benchmark Results

**Shard 3/4 (previously resulted in OOM crash)**

| Metric    | Before | After  | Delta   |
| --------- | ------ | ------ | ------- |
| Peak heap | 300 MB | 295 MB | -5 MB   |
| 2nd peak  | 295 MB | 181 MB | -114 MB |
| 3rd peak  | 289 MB | 181 MB | -108 MB |
| Average   | 111 MB | 105 MB | -6 MB   |

### Notes

* Shard 1/4 did not show noticeable improvements.
* Locally, OOM is not reproducible due to:

  * No retry loops
  * Less restrictive memory limits compared to CI

## Additional Fix

Resolved an error in shard 2/4:

```
Error: Not implemented: window.prompt
```

This was caused by Carbon’s `CodeSnippet` copy button falling back to `window.prompt()` in JSDOM. The issue has been addressed in this PR.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

See slack discussion:
https://camunda.slack.com/archives/C071KP5BTHB/p1776673179148269?thread_ts=1776667462.389809&cid=C071KP5BTHB

### CODE REVIEW

File: operate/client/src/App/ProcessInstance/ElementInstanceLog/ElementInstancesTree/mocks.tsx [hunk 1]
```diff
@@ -1199,6 +1199,8 @@ const adHocSubProcessInnerInstanceElementInstances = {
 } satisfies Record<string, QueryElementInstancesResponseBody>;
 
 const Wrapper = ({children}: {children?: React.ReactNode}) => {
+  const [queryClient] = useState(() => getMockQueryClient());
```
Comment (vsgoulart) [inline operate/client/src/App/ProcessInstance/ElementInstanceLog/ElementInstancesTree/mocks.tsx:1202]: I would prefer we use existing method by wrapping the `Wrapper` component with a `getWrapper` function like on the rest of the codebase

File: operate/client/src/modules/stores/notifications.tsx [hunk 2]
```diff
@@ -86,9 +87,11 @@ class Notifications {
 
       if (time <= 0) {
         clearInterval(intervalId);
+        this.#activeIntervalIds.delete(intervalId);
```
Comment (vsgoulart) [inline operate/client/src/modules/stores/notifications.tsx:90]: I'm wondering if it isn't better to use `notificationsQueue` which already exists

**Review by vsgoulart — APPROVED** [review]
I'm per-approving but I think we should fix the comments I made before.

@OmranAbazid please also remove this: https://github.com/camunda/camunda/blob/d82f9425c115dc9465208b57e5347adbe31c55b5/operate/client/vite.config.ts#L93

File: operate/client/src/modules/stores/notifications.tsx (hunk 2 above)
Comment (OmranAbazid) [reply operate/client/src/modules/stores/notifications.tsx]: notificationsQueue is used for invisible notification (pending to be shown).
The visible ones are not tracked using it
