### PR TITLE
Flaky shouldExportToCorrectIndexWithElasticsearchNotReachable fix

### LINKED ISSUE #24725: Flaky shouldExportToCorrectIndexWithElasticsearchNotReachable test.
**Summary**

```
org.opentest4j.AssertionFailedError: 

expected: 1
 but was: 0
	at io.camunda.zeebe.exporter.ElasticsearchExporterIT$IndexSettingsTest.shouldExportToCorrectIndexWithElasticsearchNotReachable(ElasticsearchExporterIT.java:431)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
	
	
- How often does the test fail? Only once so far. 
- Does it block your work? It recovered after so it did not block work.
- Do we suspect that it is a real failure? I don't know. 

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Paste the failure here
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

Fix the flaky test by only generating records that have index templates. Refer to https://github.com/camunda/camunda/issues/24725#issuecomment-2485905114 for more information

## Related issues

closes #24725

### CODE REVIEW

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java [hunk 1]
```diff
@@ -240,6 +243,18 @@ private <T extends RecordValue> Record<T> generateRecord(final ValueType valueTy
         valueType, r -> r.withBrokerVersion(VersionUtil.getVersionLowerCase()));
   }
 
+  private <T extends RecordValue> Record<T> generateSupportedRecord(
+      final UnaryOperator<Builder<T>> modifier) {
+    Record<T> record = factory.generateRecord(modifier);
+    while (!TestSupport.provideValueTypes()
```
Comment (mustafadagher) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:249]: ❌ We are `collecting` the set in every iteration again now.

🔧 instead of retrying to generate a record until success, is it an idea to randomly pick a valuetype of this stream and set it in the record?

**Review by mustafadagher — APPROVED** [review]
