### PR TITLE
fix: rework prefix migration

### LINKED ISSUE #38032: Disable Archiver for Migration
During the rollout of 8.8 on existing deployments, the Tasklist task migration has to run, moving data from the old `8.5.0` runtime and dated indices to the new `8.8.0` indices with an updated schema.

The migration cannot be reliably run while the Archiver is running. Introducing possible exporter lag makes the situation even less reliable as there are high chances that you can end up with documents being present both in dated and the runtime index.

The solution proposed here is to flag the `tasklist-import-position` index with a `meta` property that will be accessed by the archiver to check whether archiving should proceed. This property will be set by the SchemaManager if on brownfield deployment and updated by the Tasklist migration when completed. For greenfield deployments this property will be omitted. 

Relevant discussion thread: https://camunda.slack.com/archives/C0958TXFFNE/p1757572709573179

### LINKED ISSUE #38068: Prefix Migration affects Zeebe indices
### 

### 

### 

### 

### Description

Running the Prefix Migration with having Tasklist or Operate share the same prefix as Zeebe indices results in Zeebe indices being also migrated as the names of the indices also match some of the Zeebe index names. For example, 
- job
- variable
- process

### Steps to reproduce

Ref quick verification steps through IT: https://camunda.slack.com/archives/C07UA4C7STY/p1757685430691249?thread_ts=1757684897.493069&cid=C07UA4C7STY

On Camunda 8.7:
1. Set Tasklist prefix to `tasklist-prefix`, `CAMUNDA_TASKLIST_ELASTICSEARCH_INDEXPREFIX=tasklist-prefix`
2. Set Operate prefix to `operate-prefix`, `CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX=operate-prefix`
3. Set Zeebe's exporter prefix to one of the above values, fex `operate-prefix`, `ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_PREFIX=`operate-prefix`
4. Start 8.7
5. Run some PIs to generate Zeebe indices
6. Stop 8.7 deployments
7. Run prefix migration with 
``` bash
export CAMUNDA_OPERATE_ELASTICSEARCH_INDEX_PREFIX=operate-prefix; \
export CAMUNDA_TASKLIST_ELASTICSEARCH_INDEX_PREFIX=tasklist-prefix; \
export CAMUNDA_DATABASE_INDEXPREFIX=prefixmigrationit; \
./prefix-migration
```

Check the indices,

``` bash
curl -s "localhost:9200/_cat/indices?h=index" | grep prefixmigration
prefixmigrationit-tasklist-draft-task-variable-8.3.0_
prefixmigrationit-operate-flownode-instance-8.3.1_
prefixmigrationit-operate-metric-8.3.0_
prefixmigrationit-tasklist-task-8.8.0_
prefixmigrationit-tasklist-import-position-8.2.0_
prefixmigrationit-operate-sequence-flow-8.3.0_
prefixmigrationit-camunda-user-8.8.0_
prefixmigrationit-camunda-correlated-message-8.8.0_
prefixmigrationit-tasklist-form-8.4.0_
prefixmigrationit-camunda-role-8.8.0_
prefixmigrationit-operate_job_8.7.9_2025-09-12                <- Thats a Zeebe
prefixmigrationit-operate_process_8.7.9_2025-09-12            <- Thats a Zeebe
prefixmigrationit-camunda-usage-metric-tu-8.8.0_
prefixmigrationit-camunda-mapping-rule-8.8.0_
prefixmigrationit-camunda-tenant-8.8.0_
prefixmigrationit-operate-process-8.3.0_
prefixmigrationit-operate-import-position-8.3.0_
prefixmigrationit-camunda-web-session-8.8.0_
prefixmigrationit-camunda-authorization-8.8.0_
prefixmigrationit-camunda-usage-metric-8.8.0_
prefixmigrationit-operate-event-8.3.0_
prefixmigrationit-operate_variable_8.7.9_2025-09-12           <- Thats a Zeebe
prefixmigrationit-operate-variable-8.3.0_
prefixmigrationit-operate-operation-8.4.1_
prefixmigrationit-operate-decision-8.3.0_
prefixmigrationit-operate-list-view-8.3.0_
prefixmigrationit-camunda-group-8.8.0_
prefixmigrationit-tasklist-task-variable-8.3.0_
prefixmigrationit-operate-job-8.6.0_
prefixmigrationit-tasklist-metric-8.3.0_
prefixmigrationit-operate_deployment_8.7.9_2025-09-12         <- Thats a Zeebe
prefixmigrationit-operate-batch-operation-1.0.0_
prefixmigrationit-operate-message-8.5.0_
prefixmigrationit-operate-incident-8.3.1_
prefixmigrationit-operate-decision-requirements-8.3.0_
prefixmigrationit-operate_process-instance_8.7.9_2025-09-12   <- Thats a Zeebe
prefixmigrationit-operate-post-importer-queue-8.3.0_
prefixmigrationit-operate-decision-instance-8.3.0_
prefixmigrationit-operate_process-instance-creation_8.7.9_2025-09-12  <- Thats a Zeebe
```

### Current behavior

Zeebe indices with same Index name as Operate/Tasklist will be reprefixed

### Expected behavior

Zeebe indices should be left intact

### Workaround

_No response_

### Environment

SM

### Version

- Component Version: Upgrade from 8.7 to 8.8

### Rootcause

_No response_

### Solution ideas

Maybe we can try retrieving the eligible for re-prefixing indices using the state of ES/OS regarding the index aliases from the existing IndexDescriptors.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

Rework PrefixMigration to:
- Not start the SchemaManager as it's supposed to run on 8.7
- Clone indices based on their Alias from the _new_ descriptors expected
- Make use of ES/OS Async clients to chain the requests per index for updating settings, cloning, updating aliases and finally deleting the old index
- Override `TasklistProperties` and `OperateProperties` that are being validated by the Unified Config with custom properties just for the migration. The previous ones, have their values replaced from the new `CAMUNDA_DATA_SECONDARYSTORAGE_ELASTICSEARCH_INDEXPREFIX` which for the Prefix migration corresponds to the unified prefix

Since it relies on the Aliases to find the required indices this means that the migration can be retried without side effects.

Still WiP need to make some adjustments

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #38032
closes #38068

### CODE REVIEW

**Comment by EuroLew** [comment]
I was working on the test so that we verify zeebe indices are not migrated as well. https://github.com/camunda/camunda/pull/38272. I think it would be helpful to add a test based on that.

**Comment by panagiotisgts** [comment]
> I was working on the test so that we verify zeebe indices are not migrated as well. #38272. I think it would be helpful to add a test based on that.

@EuroLew We could include a scenario for that, but since we are utilizing the Aliases now there is no chance we pick up the Zeebe indices to migrate them AFAIK

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java [hunk 1]
```diff
@@ -36,29 +39,36 @@
...
-  private static final Logger LOG = LoggerFactory.getLogger(PrefixMigrationHelper.class);
-
-  private static final Set<Class<? extends AbstractIndexDescriptor>> TASKLIST_INDICES_TO_MIGRATE =
-      new HashSet<>(Arrays.asList(FormIndex.class, TaskTemplate.class));
-
-  private static final Set<Class<? extends AbstractIndexDescriptor>> OPERATE_INDICES_TO_MIGRATE =
+  @VisibleForTesting
+  public static final Set<Class<? extends AbstractIndexDescriptor>> TASKLIST_INDICES_TO_MIGRATE =
+      new HashSet<>(
+          Arrays.asList(
```
Comment (houssain-barouni) [inline dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]:
```suggestion
      Set.of(
```

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java [hunk 2]
```diff
@@ -36,29 +39,36 @@
...
+              // Not pointing to the new TaskTemplate as we care about the old version
+              TaskLegacyIndex.class,
+              SnapshotTaskVariableTemplate.class,
+              TasklistMigrationRepositoryIndex.class,
+              TasklistImportPositionIndex.class));
+
+  @VisibleForTesting
+  public static final Set<Class<? extends AbstractIndexDescriptor>> OPERATE_INDICES_TO_MIGRATE =
       new HashSet<>(
           Arrays.asList(
```
Comment (houssain-barouni) [inline dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]:
```suggestion
Set.of(
```

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java [hunk 3]
```diff
@@ -132,164 +134,135 @@ private static PrefixMigrationClient getPrefixMigrationClient(
...
-      final String operatePrefix,
-      final String tasklistPrefix,
-      final ConnectConfiguration connectConfig,
-      final PrefixMigrationClient prefixMigrationClient,
-      final ExecutorService executor) {
-    final var srcToDestOperateCloneMap =
-        createSrcToDestCloneMap(
-            operatePrefix, connectConfig.getIndexPrefix() + "-operate", prefixMigrationClient);
-    cloneHistoricIndicesWithRetry(srcToDestOperateCloneMap, prefixMigrationClient, executor);
+    final boolean isElasticsearch = connectConfig.getTypeEnum() == DatabaseType.ELASTICSEARCH;
```
Comment (houssain-barouni) [inline dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]:
```suggestion
    final boolean isElasticsearch = connectConfig.getTypeEnum().isElasticSearch();
```

File: schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java [hunk 4]
```diff
@@ -7,103 +7,98 @@
...
-    client
-        .indices()
-        .putSettings(r -> r.index(index).settings(s -> s.index(i -> i.blocks(b -> b.write(true)))));
-  }
-
-  private void cloneIndex(final String src, final String target) throws IOException {
-    final var targetAlias = target.replaceAll(DATE_REGEX_FOR_INDICES, "alias");
-    client
+  @Override
+  public CompletableFuture<CloneResult> cloneAndDeleteIndex(
```
Comment (EuroLew) [inline schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java:57]:
```
private CompletableFuture<Void> makeIndexReadOnly(String index) {
    return asyncClient.indices()
        .putSettings(r -> r.index(index)
            .settings(s -> s.index(i -> i.blocks(b -> b.write(true)))))
        .thenRun(() -> LOG.info("Marked index [{}] as read-only", index));
}

private CompletableFuture<Void> cloneIndex(String source, String destination) {
    return asyncClient.indices()
        .clone(c -> c.index(source).target(destination))
        .thenRun(() -> LOG.info("Cloned index [{}] to [{}]", source, destination));
}

private CompletableFuture<Void> updateAliasesAtomically(String source, String destination, 
                                                       String sourceAlias, String destinationAlias) {
    return asyncClient.indices()
        .updateAliases(u -> u.actions(
            Action.of(a -> a.remove(rm -> rm.index(destination).alias(sourceAlias))),
            Action.of(a -> a.add(add -> add.index(destination)
                .alias(destinationAlias)
                .isWriteIndex(false)))
        ))
        .thenRun(() -> LOG.info("Updated aliases: removed [{}] from [{}], added [{}] to [{}]", 
            sourceAlias, source, destinationAlias, destination));
}

private CompletableFuture<Void> deleteSourceIndex(String index) {
    return asyncClient.indices()
        .delete(d -> d.index(index))
        .thenRun(() -> LOG.info("Deleted source index [{}]", index));
}

private CloneResult handleMigrationFailure(Throwable throwable) {
    LOG.error("Failed to migrate index [{}] to [{}]", source, destination, throwable);
    return new CloneResult(false, source, destination, throwable);
}



public CompletableFuture<CloneResult> migrateIndex(String source, String destination, 
                                                  String sourceAlias, String destinationAlias) {
    return makeIndexReadOnly(source)
        .thenCompose(ignore -> cloneIndex(source, destination))
        .thenCompose(ignore -> updateAliasesAtomically(source, destination, sourceAlias, destinationAlias))
        .thenCompose(ignore -> deleteSourceIndex(source))
        .thenApply(ignore -> {
            LOG.info("Successfully migrated index [{}] to [{}]", source, destination);
            return new CloneResult(true, source, destination, null);
        })
        .exceptionally(this::handleMigrationFailure);
}
```

Comment (EuroLew) [reply schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java:57]: 🔧 group the log with the actual action and make things a bit easier to understand

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java [hunk 5]
```diff
@@ -132,164 +134,135 @@ private static PrefixMigrationClient getPrefixMigrationClient(
...
-    final var srcToDestTasklistCloneMap =
-        createSrcToDestCloneMap(
-            tasklistPrefix, connectConfig.getIndexPrefix() + "-tasklist", prefixMigrationClient);
-    cloneHistoricIndicesWithRetry(srcToDestTasklistCloneMap, prefixMigrationClient, executor);
+    CompletableFuture.allOf(futures).join();
   }
 
-  private static void cloneHistoricIndicesWithRetry(
-      final Map<String, String> srcToDestCloneMap,
+  private static void buildCloneTargets(
```
Comment (houssain-barouni) [inline dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]: 🔧 can we make it return the cloneOperations, instead of having at argument, then do the aggregation by the caller method

File: schema-manager/src/main/java/io/camunda/search/schema/opensearch/OpensearchPrefixMigrationClient.java [hunk 6]
```diff
@@ -9,98 +9,118 @@
...
-      return new CloneResult(false, source, destination, e);
+      LOG.error("Failed to get all aliased indices for alias [{}]", alias, e);
+      throw new IllegalStateException(
+          "Failed to retrieve aliased indices for alias [" + alias + "]", e);
     }
   }
 
   @Override
-  public List<String> getAllHistoricIndices(final String prefix) {
+  public CompletableFuture<CloneResult> cloneAndDeleteIndex(
```
Comment (EuroLew) [inline schema-manager/src/main/java/io/camunda/search/schema/opensearch/OpensearchPrefixMigrationClient.java:55]: 🔧 same changes as for ES, group logs and make it easier to understand

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java [hunk 7]
```diff
@@ -132,164 +134,135 @@ private static PrefixMigrationClient getPrefixMigrationClient(
...
-              // we can use the new version index as it does not change
-              final var oldIndexName =
-                  String.format(
-                      "%s-%s-%s_", oldPrefix, newIndex.getIndexName(), newIndex.getVersion());
-
-              return Map.entry(oldIndexName, newIndex.getFullQualifiedName());
-            })
-        .collect(Collectors.toMap(Entry::getKey, Entry::getValue));
+  public static boolean isHistoricIndex(final String indexName) {
+    return indexName.matches(".*\\d{4}-\\d{2}-\\d{2}$");
```
Comment (houssain-barouni) [inline dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]: this depends on the legacy rolloverDateFormat https://github.com/camunda/camunda/blob/6e186fd78282861cdd6919e4899ba19651c28b16/operate/common/src/main/java/io/camunda/operate/property/ArchiverProperties.java#L22
❓ do you think this would be overkill ?

Comment (houssain-barouni) [reply dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]: I would consider any index that uses the index template alias, but is not the runtime index, as the historical index

File: qa/migration-tests/src/test/java/io/camunda/it/migration/PrefixMigrationIT.java [hunk 8]
```diff
@@ -398,4 +407,97 @@ private CamundaClient createCamundaClient(final GenericContainer<?> container) {
...
+                    .withReadTimeout(Duration.ofSeconds(30)))
+            .withAccessToHost(true)
+            .withExposedPorts(REST.port(), MONITORING.port(), GATEWAY.port())
+            .withEnv("CAMUNDA_OPERATE_CSRFPREVENTIONENABLED", "false")
+            .withEnv("CAMUNDA_TASKLIST_CSRFPREVENTIONENABLED", "false")
+            .withEnv("SPRING_PROFILES_ACTIVE", "broker,operate,tasklist,identity,consolidated-auth")
+            .withEnv("CAMUNDA_SECURITY_AUTHENTICATION_METHOD", "BASIC")
+            .withAccessToHost(true);
+
+    if (currentMultiDbDatabaseType() == DatabaseType.ES) {
```
Comment (EuroLew) [inline qa/migration-tests/src/test/java/io/camunda/it/migration/PrefixMigrationIT.java:248]: :wrench: I don't think this is needed as you are now applying properties in the test with the uuid prefixes

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java [hunk 9]
```diff
@@ -132,164 +134,135 @@ private static PrefixMigrationClient getPrefixMigrationClient(
...
+    } else if (cls.equals(TasklistMigrationRepositoryIndex.class)) {
+      return new TasklistMigrationRepositoryIndex(prefix, isElasticsearch);
+    } else if (cls.equals(TasklistImportPositionIndex.class)) {
+      return new TasklistImportPositionIndex(prefix, isElasticsearch);
+    } else if (cls.equals(MigrationRepositoryIndex.class)) {
+      return new MigrationRepositoryIndex(prefix, isElasticsearch);
+    } else if (cls.equals(ImportPositionIndex.class)) {
+      return new ImportPositionIndex(prefix, isElasticsearch);
+    }
+    return descriptors.get(cls);
```
Comment (houssain-barouni) [inline dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]: ❓ if I am not mistaken, getDescriptor is always called with the new prefix, why don't we just use `descriptors.get(cls)` in all cases?

File: schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java (hunk 4 above)
Comment (houssain-barouni) [inline schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java:57]: 💯

File: schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java [hunk 10]
```diff
@@ -7,103 +7,98 @@
...
-                c.index(src)
-                    .target(target)
-                    .settings(
-                        Map.of(
-                            "index.blocks.write",
-                            JsonData.of(false),
-                            "number_of_replicas",
-                            JsonData.of(0)))
-                    .aliases(targetAlias, new Alias.Builder().build()));
+        .putSettings(r -> r.index(source).settings(s -> s.index(i -> i.blocks(b -> b.write(true)))))
```
Comment (houssain-barouni) [inline schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java]: ❓ should we unblock write on the destination index, after the cloning

**Review by houssain-barouni — COMMENTED** [review]
Nice work 💯 
I left some questions and suggestions

File: qa/migration-tests/src/test/java/io/camunda/it/migration/PrefixMigrationIT.java [hunk 11]
```diff
@@ -251,16 +144,132 @@ void shouldMigrateCorrectIndicesDuringPrefixMigration() {
...
+    final var oldOperateAliases =
+        client.indices().getAlias(a -> a.name(oldOperatePrefix + "-*")).result();
+    descriptors
+        .all()
+        .forEach(
+            desc -> assertThat(oldOperateAliases).doesNotContainKey(desc.getFullQualifiedName()));
+  }
+
   @Test
   void shouldReindexDocumentsDuringPrefixMigration() throws IOException {
```
Comment (EuroLew) [inline qa/migration-tests/src/test/java/io/camunda/it/migration/PrefixMigrationIT.java]: 🔧  It's probably good to remove all the `esClient` and `osClient` stuff from the `shouldReindexDocumentsDuringPrefixMigration` test which was used to track storage state due to the flakes. remove all the logs should make it cleaner.

**Review by EuroLew — APPROVED** [review]
real nice stuff ❤️ , just cleaning up of the tests

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java (hunk 9 above)
Comment (panagiotisgts) [reply dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]: The reason for this custom mapping, is that some of these legacy indices are not part of the 8.8 schema descriptors. `TasklistMigrationRepositoryIndex`, `MigrationRepositoryIndex` and `TaskLegacyIndex` are not present in the descriptors. The import positions are I can remove them

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java (hunk 7 above)
Comment (panagiotisgts) [reply dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]: We can possibly generalize this, any index that does not end with `_` should be a historic index right?

File: schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java (hunk 10 above)
Comment (panagiotisgts) [reply schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java]: I thought about this, this flag is only relative when you're doing document updates on the alias itself, it does not exactly block writing. The default value when an index is created is `false` on this AFAIK

Comment (houssain-barouni) [reply schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java]: no, it is a real restriction on the index, maybe you are talking about the alias setting that we set few lines below
I was talking about the index setting itself

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java (hunk 7 above)
Comment (houssain-barouni) [reply dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]: yes, any index not exactly equal the full qualified name of the index template

File: schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java (hunk 10 above)
Comment (panagiotisgts) [reply schema-manager/src/main/java/io/camunda/search/schema/elasticsearch/ElasticsearchPrefixMigrationClient.java]: Ah, you are right :rocket:

**Review by EuroLew — APPROVED** [review]
LGTM

File: dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java [hunk 12]
```diff
@@ -195,14 +190,14 @@ public static void migrate(
...
 
-  private static void buildCloneTargets(
-      final String oldPrefix,
-      final String newPrefix,
-      final boolean isElasticsearch,
-      final PrefixMigrationClient prefixMigrationClient,
-      final Class<? extends AbstractIndexDescriptor> cls,
-      final IndexDescriptors descriptors,
-      final Map<Tuple<String, String>, List<Tuple<String, String>>> cloneOperations) {
+  private static Optional<Tuple<Tuple<String, String>, List<Tuple<String, String>>>>
```
Comment (houssain-barouni) [inline dist/src/main/java/io/camunda/application/commons/migration/PrefixMigrationHelper.java]: 💀

File: dist/src/main/java/io/camunda/application/StandalonePrefixMigration.java [hunk 13]
```diff
@@ -74,4 +82,18 @@ public void run(final String... args) throws Exception {
     PrefixMigrationHelper.runPrefixMigration(
         operateProperties, tasklistProperties, connectConfiguration);
   }
+
+  ///  Override {@link io.camunda.tasklist.property.TasklistProperties} bean which is validated
+  /// by the Unified Configuration and gets overriden by the {@link
+  /// io.camunda.configuration.SecondaryStorage} new prefix configuration
+  @ConfigurationProperties("camunda.tasklist")
+  public record TasklistIndexPrefixPropertiesOverride(
```
Comment (houssain-barouni) [inline dist/src/main/java/io/camunda/application/StandalonePrefixMigration.java:90]: ❓ I see that you removed
```
                TasklistPropertiesOverride.class,
                OperatePropertiesOverride.class,
```
from the standalone app sources, do you still need this? can we just include in the sources
```
                TasklistProperties.class,
                OperateProperties.class,
```

**Review by houssain-barouni — COMMENTED** [review]
@panagiotisgts thank you for taking into account the last review
I had one question left

File: dist/src/main/java/io/camunda/application/StandalonePrefixMigration.java (hunk 13 above)
Comment (panagiotisgts) [reply dist/src/main/java/io/camunda/application/StandalonePrefixMigration.java:90]: <s> Just found out we have `LegacyTasklist/OperateProperties` that are bean enabled. Gonna use those </s> I can't use the _Override_ ones since they are being overriden from the SecondaryStorage configuration from the UnifiedConfigHelper
