### PR TITLE
fix(engine): throw instead of ignoring events that can't be applied

### LINKED ISSUE #15833: New event applier versions could lead to data inconsistencies
**Describe the bug**

> [!NOTE]
> This bug cannot have caused any data inconsistencies so far, but the bug should be resolved before adding more versioned event appliers.

Brokers ignore newer events (by record version) if the event applier cannot be found. This could cause problems when an older broker (after having received events from a newer broker) eventually becomes leader.

--- 

Originally, event appliers would [log when the relevant event applier could not be found](https://github.com/camunda/zeebe/blob/7c4c9670ad088819ccb329ebd072fdcd0f4aa3f2/engine/src/main/java/io/zeebe/engine/state/appliers/EventAppliers.java#L30-L34) (before versioned event appliers existed).

This log message was removed because [not all events produce state changes](https://github.com/camunda/zeebe/commit/2952e16efbf557c3deb348870ee7b658bc09d595), i.e. not all events have an event applier.

This could cause problems if an old broker becomes leader after attempting to apply newer versions of an event for which it doesn't have the applier.

> When we added versioned event appliers, we likely did not consider the case where an older broker could receive newer versions of events that it couldn't apply, but still could become leader afterward.

Luckily for us, there has only been one versioned event appliers added so far:
[Deployment CREATED has become NOOP in v2](https://github.com/camunda/zeebe/blob/f2c170fac5df52b3f5838a6c9bd7abf4069264fc/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/EventAppliers.java#L111-L112)

And, this v2 event applier is a NOOP, so the behavior is equivalent. This means the bug cannot yet cause any problems.

However, we must resolve this before adding more event versions.

**Expected behavior**

An event must always produce the same state when replayed compared to when it was first appended. If a broker cannot apply the event, it should stop replaying until it can.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
If an event can't be applied because no applier is registered, we can't just ignore it by using the no-op applier, we must stop processing so that we don't process incorrectly, especially during rolling updates where an old engine might apply events written by a new engine.

Closes #15833

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I'm missing a test that shows how the `ReplayStateMachine` behaves when encountering an exception that isn't `RecoverableException`.

**Comment by oleschoenburg** [comment]
More importantly, we don't have a good way to verify that all event intents are actually registered. This already failed for `VariableDocumentIntent.UPDATED` but I fear that there might be others that are used less often and could evade tests.

**Comment by oleschoenburg** [comment]
@Zelldon I've requested your review already since I'm curious if you have any ideas for testing. I've mentioned two testing topics in the comments above.

**Comment by Zelldon** [comment]
Sorry @oleschoenburg I try to take a look at it on monday

**Comment by Zelldon** [comment]
> I'm missing a test that shows how the `ReplayStateMachine` behaves when encountering an exception that isn't `RecoverableException`.

AFAIK the state machine should loop in this case.

**Comment by Zelldon** [comment]
I'm wondering whether it makes sense on basis of Engine, or more on the basis of the stream platform. 

Couldn't we check the record version before giving the engine? I think we actually do already. If we detect an record with higher version we should simply stop. I think this would the easiest and safest no?

**Comment by oleschoenburg** [comment]
I've added a test that uses some heuristic to figure out all of the event intents and checks that there's at least one event applier registered for it: https://github.com/camunda/zeebe/pull/16160/commits/fc795c5593c9ec100a118d936655e1f19f1d1562

File: engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java [hunk 1]
```diff
@@ -136,4 +141,33 @@ void shouldGetLatestVersionWhenMultipleRegisteredEventAppliersWithDifferentInten
...
+
+  @Test
+  void shouldRegisterApplierForAllIntents() {
+    // given
+    final var events =
+        Intent.INTENT_CLASSES.stream()
+            .flatMap(c -> Arrays.stream(c.getEnumConstants()))
+            // Heuristic to detect event intents which are generally in past or present tense
+            // instead of the imperative used for commands.
+            .filter(intent -> intent.name().endsWith("ED") || intent.name().endsWith("ING"))
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java:153]: 🔧 Alternatively, we could hardcode this for each intent. If so, we'd need to consider that intents used for commands can also be used for command rejections. Perhaps something like `isCommanding()` would be fitting on the Intent interface. What do you think?

File: engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java [hunk 2]
```diff
@@ -136,4 +141,33 @@ void shouldGetLatestVersionWhenMultipleRegisteredEventAppliersWithDifferentInten
...
+            // CheckpointIntent is not handled by the engine
+            .filter(intent -> !(intent instanceof CheckpointIntent))
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java:155]: 🔧 Rather than filtering it out explicitly, we could add a `isRelatedTo()` method to `Intent` that informs whether the intent is related to the engine or the stream processor (or something else if we'd need that in the future). Such a check could be easier to maintain than this one.

File: engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java [hunk 3]
```diff
@@ -136,4 +141,33 @@ void shouldGetLatestVersionWhenMultipleRegisteredEventAppliersWithDifferentInten
...
+            // ProcessInstanceResultIntent is only used for client responses and does not appear on
+            // the log
+            .filter(intent -> !(intent instanceof ProcessInstanceResultIntent));
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java:158]: 🔧 Rather than filtering it out here, it might be better to simply add a NOOP applier. Benefits that I see:
- consistent with other engine related intents
- simpler to maintain when we add other intents that don't appear on the log
- gives the option to eventually add a ProcessInstanceResultIntents to the log

File: engine/src/main/java/io/camunda/zeebe/engine/state/EventApplier.java [hunk 4]
```diff
@@ -29,6 +29,34 @@ public interface EventApplier {
...
+
+    public static final class NoApplierForVersion extends NoSuchEventApplier {
+      public NoApplierForVersion(
+          final Intent intent, final int recordVersion, final int latestVersion) {
+        super(
+            String.format(
+                "Expected to find an event applier for intent '%s' and version '%d', but '%s' is the latest supported version.",
+                intent, recordVersion, latestVersion));
+      }
+    }
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/state/EventApplier.java:60]: ❓ SM users would see this error message. Is it clear enough to figure out how to recover? I think so right, because of https://github.com/camunda/zeebe/pull/16160#issuecomment-1938712611

**Review by korthout — APPROVED** [review]
Great work @oleschoenburg. Thanks so much for doing this! 🚀 

👍 I like the overall approach, test case and sealed exceptions 

🔧 I only have a few suggestions, but they don't require another review round perse. Feel free to request another review as you see fit.

File: engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java (hunk 1 above)
Comment (oleschoenburg) [reply engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java:153]: > If so, we'd need to consider that intents used for commands can also be used for command rejections

I understand that commands show up in command rejections but I don't quite get how that's relevant here. Could you elaborate?

I like the idea of a method in the `Intent` interface that takes an intent instance and tells you whether it's a command or event :+1: I only though of adding that to the enum members which I discarded because it seemed wasteful to have that data available at runtime. A method solves that nicely though!

File: engine/src/main/java/io/camunda/zeebe/engine/state/EventApplier.java (hunk 4 above)
Comment (oleschoenburg) [reply engine/src/main/java/io/camunda/zeebe/engine/state/EventApplier.java:60]: Yeah I think it's okay. Usually this would only show up during a rolling update (if at all) and would resolve itself as the rolling update proceeds.

File: engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java (hunk 1 above)
Comment (korthout) [reply engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java:153]: >I understand that commands show up in command rejections but I don't quite get how that's relevant here. Could you elaborate?
>[..] takes an intent instance and tells you whether it's a command or event

We have three record types. An intent is used either for a:
- command
- command rejection
- event

So an intent can't be just a command or an event. However, intents used for commands can also be used for command rejections. That's why I was hinting at a different wording, something like `isCommanding` or so.

File: engine/src/main/java/io/camunda/zeebe/engine/state/EventApplier.java (hunk 4 above)
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/EventApplier.java:60]: 💭 It could also occur on downgrading.

File: engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java (hunk 2 above)
Comment (oleschoenburg) [reply engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java]: I've left that out for now. This only applies to `CheckpointIntent`, I don't expect we add any new intents like soon and if we do, this test will fail and it will be obvious how to fix it.

File: engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java (hunk 1 above)
Comment (oleschoenburg) [reply engine/src/test/java/io/camunda/zeebe/engine/state/appliers/EventAppliersTest.java]: Thanks, I've added a method `isEvent` and use that for tests. To ensure that the implementations of that are correct, I've added another test to ensure that only event intents have a registered event applier. Combined with the other test that all event intents have a registered event applier, we also know that the implementations are exhaustive.

**Comment by oleschoenburg** [comment]
:sob: Somewhat predictable. I'll try to backport manually.
