### PR TITLE
fix: Improve REST API response when deployResources payload is too large

### LINKED ISSUE #29965: [C8 API] Max file upload size for the Deploy Resources API
The Document Handling API allows [batch file uploads](https://docs.camunda.io/docs/8.7/apis-tools/camunda-api-rest/specifications/create-documents/) up to 10MB. In order to support that on SaaS we needed to pass the env vars
```
SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
```
to the app because the default values are defined in [application.properties](https://github.com/camunda/camunda/blob/stable/8.7/dist/src/main/resources/application.properties#L71) and are
```
spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB
```
We were testing the [deploy resources](https://docs.camunda.io/docs/8.7/apis-tools/camunda-api-rest/specifications/deploy-resources/) endpoint to see if its behaviour changed with the new limit of 10MB and we consistently noticed that:
* before our changes (4MB) when the payload was between 4MB and 10MB the server would respond with `413 Request Entity Too Large`
* after our changes (10MB) when the payload was between 4MB and 10MB the server would respond with
```
{
    "type": "about:blank",
    "title": "MALFORMED_REQUEST",
    "status": 500,
    "detail": "Received an unexpected error from the broker, code: MALFORMED_REQUEST, message: Request size is above configured maxMessageSize.",
    "instance": "/v2/deployments"
}
```
This is something that we should address as the 500 response is not ideal.

### PR DESCRIPTION
**Pull request by georgios-goulos**
## Description

The linked task has all the necessary context.

Current behaviour on main for an upload of file that is between 4MB and 10MB

Screenshot 2025-03-24 at 14 20 35

New behaviour for the same scenario

Screenshot 2025-03-25 at 09 18 31

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes https://github.com/camunda/camunda/issues/29965

### CODE REVIEW

**Review by tmetzke — CHANGES_REQUESTED** [review]
❌ The behavior in the gRPC API shouldn't change regarding the status code.

💭 An alternative here: don't introduce a new error code, reuse the MALFORMED_REQUEST code, and issue an appropriate 4xx status code in the REST API. I believe this would be good enough as well. Do we really NEED the 413? The 500 status code is not correct, I agree. This would be less invasive and still convey to the user that the input cannot be handled. The exact problem (message size larger than the engine can handle) is still in the detail message.

File: zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/grpc/GrpcErrorMapper.java [hunk 1]
```diff
@@ -177,7 +177,10 @@ private Status mapBrokerErrorToStatus(
         logger.trace("Target broker was not the leader of the partition: {}", error, rootError);
         builder.setCode(Code.UNAVAILABLE_VALUE);
       }
-      case MALFORMED_REQUEST -> builder.setCode(Code.INVALID_ARGUMENT_VALUE);
+      case MALFORMED_REQUEST -> {
+        logger.debug("Malformed request: {}", message, rootError);
```
Comment (georgios-goulos) [inline zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/grpc/GrpcErrorMapper.java:181]: @tmetzke I added this because we were logging the errors in most other cases. If there are any concerns about what could be logged here let me know and I will get rid of it.

**Comment by georgios-goulos** [comment]
> and issue an appropriate 4xx status code in the REST API

@tmetzke Thanks for the review. I followed your advice and I reverted most of my changes. The REST response code is now a 400 BAD_REQUEST. I will update the PR description to reflect that

**Review by tmetzke — APPROVED** [review]
👍 Looks good to me, thanks for looking into the suggestions.
🔧 I believe we have to remove the MALFORMED_REQUEST enum value from one test method in the `ErrorMapperTest`. It currently expects to see a 500 for that in the REST API which is not true anymore. It's a simple fix, so pre-approving already 🙂

**Comment by tmetzke** [comment]
@georgios-goulos, you added the backport label for 8.7. Should we also add 8.6? Or do you plan to trigger the backport from the 8.7 PR? Or is this irrelevant for 8.6?

**Comment by georgios-goulos** [comment]
> @georgios-goulos, you added the backport label for 8.7. Should we also add 8.6? Or do you plan to trigger the backport from the 8.7 PR? Or is this irrelevant for 8.6?

The reason we noticed this issue is because we bumped 
```
spring.servlet.multipart.max-file-size
spring.servlet.multipart.max-request-size
```
in [application.properties](https://github.com/camunda/camunda/blob/main/dist/src/main/resources/application.properties#L71C1-L72C47) on `main` to 10MB. We only need this change for document handling which is officially released with 8.7 as we did the bump to allow uploads for larger files.

Those spring props are currently not updated in `8.7` but:
* I am planning to backport that too
* We are changing the values of those spring props via env vars in SaaS and we will also do the same via Helm charts

so we will still see the same issue that this PR addresses.

I think we don't need to backport to 8.6

**Comment by tmetzke** [comment]
Thanks, @georgios-goulos 👍 

In 8.6, we also have the [upload documents](https://github.com/camunda/camunda/blob/stable/8.6/zeebe/gateway-protocol/src/main/proto/rest-api.yaml#L1348-L1405) endpoint (in alpha state because only in-memory is supported).
Plus, we [document](https://docs.camunda.io/docs/8.6/apis-tools/camunda-api-rest/camunda-api-rest-overview/#deployment-api) that you can increase the upload limit.
So I would suggest we also add this fix to 8.6 for consistency.
