### PR TITLE
Fix termination of children when modifying an ad-hoc sub-process

### LINKED ISSUE #48530: Batch move of regular ad-hoc subprocess corrupts the process instance
### 

### 

, , 

### 

### 

### Description

When batch-moving a regular (non-MI) ad-hoc subprocess, the subprocess gets canceled but the inner instances and their active tasks remain active. This leaves the process instance in a **severely broken, unrecoverable state**. Further modifications (e.g., attempts to cancel the orphaned inner instances) fail with errors. The instance can be canceled, but the broken active parts remain active.

Not a regression — confirmed to reproduce on 8.8 and 8.7.

Discovered in peer review: https://github.com/camunda/camunda/issues/47139

### Steps to reproduce

1. Deploy a process with a regular (non-MI) ad-hoc subprocess containing user tasks A and B, with two active inner instances of A
2. Create process instances
3. From the process instances overview, select the process instances and use the batch move operation
4. Select the ad-hoc subprocess as the source element
5. Select a target element (e.g., the same ad-hoc subprocess to re-create it)
6. Apply the batch modification

### Current behavior

The subprocess gets canceled, but the inner instances and their active tasks (e.g., A) remain active. The process instance is now in a severely broken state:
- The ad-hoc subprocess shows as canceled
- The inner instance and its active task A remain active (orphaned)
- Further modifications to the broken instance fail with errors
- Canceling the instance leaves the broken active parts still active

Not a regression — confirmed to reproduce on 8.8 and 8.7.

Batch move of regular ad-hoc subprocess (selecting source):

Batch move target selection:

Confusing result — says cancelled 2 / created 2, but still 2 active:

Subprocess is canceled, but innerInstance and A instance are still active (broken state):

Further modifications fail with errors, broken parts remain active after canceling the instance:

### Expected behavior

When batch-moving an ad-hoc subprocess, all inner instances and their active tasks should be properly canceled along with the subprocess. The process instance should remain in a consistent, recoverable state.

### Workaround

No known workaround. Once the instance is corrupted, it cannot be recovered.

### Environment

SaaS & SM

### Version

- Component Version: Camunda SNAPSHOT-8.9 (also reproduced on 8.8 and 8.7)

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

https://github.com/camunda/camunda/issues/47139

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Children of the ad-hoc sub-process were never terminated. The element type was not added to the if-statement that would fetch the children. As a result, the ad-hoc sub-process itself would get terminated, the process instance would get terminated, but the children inside of the ad-hoc sub-process would remain indefinitely.

I added a small refactoring to make it harder to forget this in the future if more container elements are added.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #48530

### CODE REVIEW

File: zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/BpmnElementType.java [hunk 1]
```diff
@@ -21,48 +21,50 @@
...
+  EVENT_BASED_GATEWAY("eventBasedGateway", false),
+  INCLUSIVE_GATEWAY("inclusiveGateway", false),
 
   // Other
-  SEQUENCE_FLOW("sequenceFlow"),
-  MULTI_INSTANCE_BODY(null),
-  CALL_ACTIVITY("callActivity"),
+  SEQUENCE_FLOW("sequenceFlow", false),
+  MULTI_INSTANCE_BODY(null, true),
+  CALL_ACTIVITY("callActivity", false),
```
Comment (remcowesterhoud) [inline zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/BpmnElementType.java:58]: Let me know what you think about this one. Call activities have a different behavior from other container elements. They don't have direct children, they just have a child process instanc that's created.
To me saying it is **not** a container element feels right and wrong at the same time 😅. But as it's always an exceptional case already, I am fine with marking it as `false`.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 2]
```diff
@@ -3394,16 +3396,28 @@ private long getElementInstanceKeyOfElement(
...
+                .limitByCount(
+                    r ->
+                        r.getValue().getElementId().equals(elementId)
+                            && r.getIntent().equals(ProcessInstanceIntent.ELEMENT_TERMINATED),
+                    count)
                 .toList())
         .extracting(Record::getIntent)
-        .containsSequence(
-            ProcessInstanceIntent.ELEMENT_TERMINATING, ProcessInstanceIntent.ELEMENT_TERMINATED);
+        .containsSequence(expectedIntents);
```
[the remark this answers is not in the document]
Comment (remcowesterhoud) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:3420]: This is not the case during a process instance modification:

```java
  private void terminateElement(final ElementInstance elementInstance) {
    final var elementsTerminating = startTerminatingElementAndChildren(elementInstance);
    terminateElements(elementsTerminating);
  }
```

We first write all terminating events, and after all terminate events. I had copilot's suggestion at first and my test failed 🙂

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 3]
```diff
@@ -1465,10 +1465,7 @@ private List<ElementInstance> getChildInstances(
       final ElementInstance currentElement) {
     final var childInstances = new ArrayList<ElementInstance>();
     // terminate all child instances if the element is an event subprocess
```
[the remark this answers is not in the document]
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]: This comment is garbage anyway. I'll remove it.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (korthout) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:3420]: 🔧 Would be cool to assert the number of `ELEMENT_TERMINATING` and `ELEMENT_TERMINATED` pairs instead to avoid the test depending on this specific order. But I understand if you think it's not worth it to explore (costs too much time and perhaps makes the assertion more complex)

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 4]
```diff
@@ -3394,16 +3396,28 @@ private long getElementInstanceKeyOfElement(
...
   private void assertThatElementIsTerminated(
       final long processInstanceKey, final String elementId) {
+    assertThatElementIsTerminated(processInstanceKey, elementId, 1);
+  }
+
+  private void assertThatElementIsTerminated(
+      final long processInstanceKey, final String elementId, final int count) {
+    final var expectedIntents = new ArrayList<ProcessInstanceIntent>();
+    expectedIntents.addAll(Collections.nCopies(count, ProcessInstanceIntent.ELEMENT_TERMINATING));
+    expectedIntents.addAll(Collections.nCopies(count, ProcessInstanceIntent.ELEMENT_TERMINATED));
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:3406]: 💭 Clever

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 5]
```diff
@@ -3546,6 +3560,43 @@ public void shouldSubscribeToIntermediateConditionalCatchEventWhenTokenIsAdded()
...
+        .modification()
+        .moveElements("AHSP", "C")
+        .modify();
+
+    // then
+    assertThatElementIsTerminated(processInstanceKey, "AHSP");
+    assertThatElementIsTerminated(processInstanceKey, "AHSP#innerInstance", 2);
+    assertThatElementIsTerminated(processInstanceKey, "A");
+    assertThatElementIsTerminated(processInstanceKey, "B");
+    verifyThatRootElementIsActivated(processInstanceKey, "C", BpmnElementType.USER_TASK);
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:3597]: 👍 Good test!

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 6]
```diff
@@ -1464,7 +1464,6 @@ private List<ElementInstance> getChildInstances(
       final long elementInstanceKey,
       final ElementInstance currentElement) {
     final var childInstances = new ArrayList<ElementInstance>();
-    // terminate all child instances if the element is an event subprocess
     if (elementType.isContainerElement()) {
       elementInstanceState.getChildren(elementInstanceKey).stream()
           .filter(ElementInstance::canTerminate)
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:1469]: 🔧 This comment appears to have related to this `.filter(canTerminate)`. It might be useful to clarify something about this. Why do we filter and not just return all child instances?

File: zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/BpmnElementType.java (hunk 1 above)
Comment (korthout) [reply zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/BpmnElementType.java:58]: 💭 Good point. I guess as well that Call Activity is not a container element in the sense that the element instance does not have children, but I can see that it's close because the child process instance is sort-of a child and there are similar interactions.

🔧 Perhaps we can clarify what is meant by `isContainerElement` with JavaDoc on the field. Additionally, we can clarify why Call Activity is not one in an inline  block comment at the Call Activity's false declaration.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (remcowesterhoud) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:3420]: I tried, but for this I need to have something unique to the element instances, which means I need the key. I felt grabbing the keys from the recording exporter made the test more complex than necessary.

File: zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/BpmnElementType.java [hunk 7]
```diff
@@ -21,48 +21,50 @@
 public enum BpmnElementType {
 
   // Default
-  UNSPECIFIED(null),
+  UNSPECIFIED(null, false),
```
Comment (korthout) [inline zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/BpmnElementType.java:24]: 👍 Personally, I find always requiring false/true this way a bit verbose and cluttering, but then again I see the value (we won't forget it) and there's not much other info that it takes away from. So, it seems fitting to me.

**Review by korthout — APPROVED** [review]
Thanks @remcowesterhoud 🚀 

👍 LGTM

🔧 Please have a look at my suggestions before merging

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (korthout) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:3420]: >I need to have something unique to the element instances,

You could probably write a new assertion that simply looks for a pair and pops them from the list and continues with the rest until done. This way you don't need to uniquely identify them

[the remark this answers is not in the document]
Comment (remcowesterhoud) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:3420]: It doesn't make the assertion prettier and easier to understand. I'll just keep it as-is, but it was a good suggestion 👍

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java (hunk 6 above)
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:1469]: That's not really what the comment relates to. When the comment was introduced the code was:

```java
    // terminate all child instances if the element is an event subprocess
    if (elementInstance.getValue().getBpmnElementType() == BpmnElementType.EVENT_SUB_PROCESS) {
      elementInstanceState.getChildren(elementInstanceKey).stream()
          .filter(ElementInstance::canTerminate)
          .forEach(childInstance -> terminateElement(childInstance, sideEffects));
    }
```

It literally only said we should terminate if the element is an event sub-process. It's honestly a useless comment. If I'd replace it now it'd be "terminate all child instances if the element is a container element". People can read the if-statement themselves 🤷.
