### PR TITLE
fix(logstreams): prevent bad system clock from causing crash

### LINKED ISSUE #6520: Can't append entries due to Low system clock granularity causes
**Describe the bug**
We received a user report where a broker fails to append entries. This happens because the rate limiter library we're using when appending entries throws an `IllegalArgumentException` stating that the RTT must be larger than zero. 
The limiter library uses `System.nanoTime()` to calculate the round-trip time two calculate the start and end time of the request and takes the difference between them to be the RTT. This means that, in this environment, two consecutive calls to `System.nanoTime()` return the same value. This is weird but not impossible, as the documentation of `System.nanoTime()` states "no guarantees are made except that the resolution is at least as good as that of currentTimeMillis()" and the documentation of `currentTimeMillis()` states "many operating systems measure time in units of tens of milliseconds". So this even though this is unusual, it's possible and we should handle it. 
I made a simple app to verify that the user's system clock doesn't have enough granularity to measure very small time differences and the results reported by the user confirm this hypothesis.

**To Reproduce**
This is dependent on the granularity of the system clock so it's hard to reproduce in other systems but I worked with the user to confirm it.

**Expected behavior**
Entries can be appended without issues.

**Log/Stacktrace**

This is the only the relevant stack trace, I'm omitting the rest of the logs.

<details><summary>Stack trace</summary>
<p>

```
java.lang.IllegalArgumentException: rtt must be >0 but got 0 
	at com.netflix.concurrency.limits.internal.Preconditions.checkArgument(Preconditions.java:21) ~[concurrency-limits-core-0.3.6.jar:0.3.6] 
	at com.netflix.concurrency.limits.limit.VegasLimit._update(VegasLimit.java:201) ~[concurrency-limits-core-0.3.6.jar:0.3.6] 
	at com.netflix.concurrency.limits.limit.AbstractLimit.onSample(AbstractLimit.java:34) ~[concurrency-limits-core-0.3.6.jar:0.3.6] 
	at com.netflix.concurrency.limits.limiter.AbstractLimiter$1.onSuccess(AbstractLimiter.java:102) ~[concurrency-limits-core-0.3.6.jar:0.3.6] 
	at io.zeebe.logstreams.impl.backpressure.AppendEntryLimiter.onCommit(AppendEntryLimiter.java:54) ~[zeebe-logstreams-0.26.1.jar:0.26.1] 
	at io.zeebe.logstreams.impl.log.LogStorageAppender.lambda$releaseBackPressure$2(LogStorageAppender.java:216) ~[zeebe-logstreams-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.1.jar:0.26.1] 
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.1.jar:0.26.1] 
```
</p>
</details>

**Environment:**
 - OS: RHEL 7.7
 - Zeebe Version: 0.26.1
 - Configuration: [e.g. exporters etc.]

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Some systems were returning smaller values in consecutive calls to System.nanoTime() which caused the rate-limiter library to throw an exception. This fixes the issue by catching the exception, ignoring the request in the limiter and suggesting the 'fixed' bp algorithm to users.

## Related issues

closes #6520

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [x] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStorageAppender.java [hunk 1]
```diff
@@ -98,6 +99,7 @@ private AppendLimiter initBackpressure(final int partitionId) {
     return AppendEntryLimiter.builder()
         .limit(windowedLimiter ? WindowedLimit.newBuilder().build(abstractLimit) : abstractLimit)
         .partitionId(partitionId)
+        .clock(new IncreasingClock())
```
Comment (deepthidevaki) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStorageAppender.java:102]: same as above. May be make it configurable.

File: logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/AppendEntryLimiter.java [hunk 2]
```diff
@@ -51,7 +55,12 @@ public boolean tryAcquire(final Long position) {
   public void onCommit(final long position) {
     final Listener listener = appendedListeners.remove(position);
     if (listener != null) {
-      listener.onSuccess();
+      try {
+        listener.onSuccess();
+      } catch (final IllegalArgumentException e) {
+        listener.onIgnore();
+        LOG.trace("Ignoring request in append entry rate limiter due to: ", e);
```
Comment (deepthidevaki) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/AppendEntryLimiter.java:62]: Same as above. Make it a warning.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks @MiguelPires . Only some minor comments.

File: broker/src/main/java/io/zeebe/broker/transport/backpressure/PartitionAwareRequestLimiter.java [hunk 3]
```diff
@@ -42,7 +43,12 @@ private PartitionAwareRequestLimiter() {
   }
 
   private PartitionAwareRequestLimiter(final Supplier<Limit> limitSupplier) {
-    limiterSupplier = i -> CommandRateLimiter.builder().limit(limitSupplier.get()).build(i);
+    limiterSupplier =
+        i ->
+            CommandRateLimiter.builder()
+                .clock(new IncreasingClock())
```
[the remark this answers is not in the document]
Comment (MiguelPires) [reply broker/src/main/java/io/zeebe/broker/transport/backpressure/PartitionAwareRequestLimiter.java:49]: I don't see any benefit in making this configurable. If the user's clock doesn't cause this bug, this won't change anything, the measurements will be exactly the same. Besides, how would the user know to enable this? A user can't know that 'System.nanoTime()` will cause us problems a priori, only after a crash.

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStorageAppender.java (hunk 1 above)
Comment (MiguelPires) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStorageAppender.java:102]: Same answer as above

File: broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java [hunk 4]
```diff
@@ -65,7 +69,13 @@ public boolean tryAcquire(final int streamId, final long requestId, final Intent
   public void onResponse(final int streamId, final long requestId) {
     final Listener listener = responseListeners.remove(new ListenerId(streamId, requestId));
     if (listener != null) {
-      listener.onSuccess();
+      try {
+        listener.onSuccess();
+      } catch (final IllegalArgumentException e) {
+        LOG.trace("Ignoring request in command rate limiter due to: ", e);
```
[the remark this answers is not in the document]
Comment (MiguelPires) [reply broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java:75]: This should never happen because we're passing a custom clock but, if this happens at all then it would happen very often. The log would be filled with warning messages. Also, in that scenario, the consequence would be that the backpressure wouldn't be accurate but if the system clock is not accurate then there's not much we can do right? Maybe then debug level at most would be the appropriate, wdyt?

**Comment by MiguelPires** [comment]
Thanks for the review @deepthidevaki. I added docs and changed the log levels, let me know what you think

File: broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (MiguelPires) [reply broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java]: On second thought, I changed them to warning in the latest commit as you requested

File: broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java [hunk 5]
```diff
@@ -65,7 +69,13 @@ public boolean tryAcquire(final int streamId, final long requestId, final Intent
   public void onResponse(final int streamId, final long requestId) {
     final Listener listener = responseListeners.remove(new ListenerId(streamId, requestId));
     if (listener != null) {
-      listener.onSuccess();
+      try {
+        listener.onSuccess();
+      } catch (final IllegalArgumentException e) {
+        LOG.warn("Ignoring request in command rate limiter due to: ", e);
```
Comment (npepinpe) [inline broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java:75]: I'm wondering if we shouldn't recommend something to the user here, or maybe in the docs, as I can imagine users running into this wouldn't be sure what to do.

File: logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/IncreasingClock.java [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+ * This ensure that measurements round-trip times in are always positive despite with potential
+ * concurrency or resolution issues in System.nanoTime() measurements.
+ */
+@SuppressWarnings("java:S4276")
+public class IncreasingClock implements Supplier<Long> {
+
+  private Long lastTime = null;
+
+  @Override
+  public synchronized Long get() {
```
Comment (npepinpe) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/IncreasingClock.java:23]: I'm not sure about adding another lock on every append/every incoming command, but I guess there's no way around it for now.

File: broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java (hunk 5 above)
Comment (MiguelPires) [reply broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java:75]: Any suggestions? Maybe it's worth stating repeatedly ignore the request will make the request limiter less accurate. It would be easier if we could there was a specific cause we could point to, it would be more actionable

Comment (npepinpe) [reply broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java:75]: We could direct users to our reference documentation, and in there we can explain the situation in more details.

Comment (MiguelPires) [reply broker/src/main/java/io/zeebe/broker/transport/backpressure/CommandRateLimiter.java:75]: Sounds good

File: broker/src/main/java/io/zeebe/broker/transport/backpressure/PartitionAwareRequestLimiter.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/transport/backpressure/PartitionAwareRequestLimiter.java:49]: There is a slight overhead in using IncreasingClock because of additional synchronized access. The user would know to enable this, if the other log logs it as a warning. The system wouldn't crash anymore, right? Because now you catch the exception and logs it. My expectation is that users test it on production hardware before actually running it on production.

File: logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/IncreasingClock.java (hunk 6 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/IncreasingClock.java:23]: AtomicLong compareAndSet?

Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/IncreasingClock.java:23]: Similar to something like this https://github.com/camunda-cloud/zeebe/blob/develop/util/src/main/java/io/zeebe/util/sched/channel/ActorConditions.java#L33-L41 I see no need for a lock here

File: logstreams/src/test/java/io/zeebe/logstreams/impl/backpressure/IncreasingClockTest.java [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+
+import org.junit.jupiter.api.Test;
+
+public class IncreasingClockTest {
+  private static final int TRIES = 100_000;
+
+  @Test
+  public void shouldReturnStrictlyIncreasingValues() {
+    // given
+    final IncreasingClock clock = new IncreasingClock();
```
Comment (Zelldon) [inline logstreams/src/test/java/io/zeebe/logstreams/impl/backpressure/IncreasingClockTest.java:20]: To make this test really use full I think we need dependency injection here. You pass an supplier in which gives twice the  same value or a lower value and then you can verify that your increasing clock still gives an higher value back.

**Review by ChrisKujawa — COMMENTED** [review]
Sorry for interfere here just read in the github slack the discussion about locks so I just wanted to add my two cents. Don't want to overrule here someone, so feel free to ignore me :sweat_smile:

File: logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/IncreasingClock.java (hunk 6 above)
Comment (MiguelPires) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/IncreasingClock.java:23]: Why is this necessary? The rate limiter listeners are created inside actors which eliminates contention in the first call and if there's contention is the second call it's probably very small. Even if there was some, I don't think this would be the bottleneck, if you think about the lifecycle of the request. Just my opinion though, I may be wrong

**Comment by deepthidevaki** [comment]
@MiguelPires Should we also backport this?

**Review by deepthidevaki — APPROVED** [review]
Thanks @MiguelPires
