### PR TITLE
fix: restore app can start successfully

### LINKED ISSUE #37544: restore primary storage fail due to missing BrokerBasedProperties
### <!-- Component -->

<!-- Zeebe- -->

### <!-- Affected version -->

<!-- -8.8 -->

### <!-- Severity -->

<!-- Low- -->

### <!-- Likelihood -->

<!-- Unknown_ -->

### Description

in 8.8.0-alpha8-rc3 restore command fails to start due to missing BrokerBasedProperties bean

### Steps to reproduce

1. Attempt to restore [following docs](https://docs.camunda.io/docs/next/self-managed/operational-guides/backup-restore/restore/#restore-zeebe-cluster) or use [workflow](https://github.com/camunda/c8-cross-component-sm-testing/actions/workflows/backup-n-restore-GKE.yml)
2. orchestration cluster in crashloop


### Current behavior

```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.                                                                                        
[2025-09-03 08:54:22.486] [main] ERROR                                                                                                                                                                             
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter -                                                                                                                                          
                                                                                                                                                                                                                   
***************************                                                                                                                                                                                        
APPLICATION FAILED TO START                                                                                                                                                                                        
***************************                                                                                                                                                                                        
                                                                                                                                                                                                                   
Description:                                                                                                                                                                                                       
                                                                                                                                                                                                                   
Parameter 1 of constructor in io.camunda.application.commons.configuration.BrokerBasedConfiguration required a bean of type 'io.camunda.configuration.beans.BrokerBasedProperties' that could not be found.        
                                                                                                                                                                                                                   
                                                                                                                                                                                                                   
Action:                                                                                                                                                                                                            
                                                                                                                                                                                                                   
Consider defining a bean of type 'io.camunda.configuration.beans.BrokerBasedProperties' in your configuration.
```

### Expected behavior

successfully restored backup

### Environment

SM

### Version

- Component Version: 8.8.0-alpha8-rc3


### Rootcause

initialization and dependency order

### Solution ideas

add @ConditionalOnMissingBean



### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):


### Links

_No response_

### PR DESCRIPTION
**Pull request by buccarel**
## Description

The application `RestoreApp` is missing the imports related to the Unified Configuration system.
This PR adds the imports. It also adds a test that makes sure that the app starts correctly.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #37544

### CODE REVIEW

**Comment by Szik** [comment]
looks good
backups can be restored successfully

File: dist/src/test/java/io/camunda/zeebe/restore/RestoreAppTest.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+import org.springframework.test.context.ActiveProfiles;
+
+@ActiveProfiles("restore")
+@SpringBootTest(
+    classes = RestoreApp.class,
+    properties = {
+      "camunda.data.backup.store=filesystem",
+      "camunda.data.backup.filesystem.basepath=/tmp",
+      "camunda.cluster.node-id=26",
+      "backupId=27"
```
Comment (RomanJRW) [inline dist/src/test/java/io/camunda/zeebe/restore/RestoreAppTest.java:25]: why did you include this?

**Review by RomanJRW — APPROVED** [review]
Changes seem fine but does this also need including in the 8.8 release?
