### PR TITLE
fix(journal): reset writer asqn on truncate

### LINKED ISSUE #6217: Journal should reject append if the sequence number is not greater than the previous record
#6216 introduces a journal module with new api. The new api includes an application sequence number which is a number provided by the application. The application can use either this sequence number or the index to seek to a record. The journal requires that the sequence number is always increasing. The first version implemented in #6216  does not validate this. However it is required that journal implementation rejects the append when the sequence number is not greater than the previous record.

Scope:
- Implement correct behaviour
- Introduce a new exception/error to indicate the failure if necessary
- Add tests

### PR DESCRIPTION
**Pull request by megglos**
## Description

On truncate the current lastAsqn of the segment writer is reset to allow overwriting non-committed records afterwards.

## Related issues

closes #6217

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentWriter.java [hunk 1]
```diff
@@ -257,6 +258,7 @@ public void truncate(final long index) {
     if (index < segment.index()) {
       buffer.position(descriptorLength);
       invalidateNextEntry(descriptorLength);
+      lastAsqn = firstAsqn - 1;
```
Comment (deepthidevaki) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentWriter.java:261]: :x: This should be moved before `if`. `lastAsqn` must be reset in both cases. It could happen that in `reset`, while iterating over the records, there are no records with valid asqn. Then the lastAsqn is not reset.

Following test fails.
```
@Test
  void shouldResetAsqnOnTruncateToIndexWithinCurrentSegment() {
    final SegmentedJournal journal = openJournal(2);

    // when
    journal.append(1, data);
    final var expectedLastAsqn = journal.append(2, data).asqn();

    // write to second segment
    final var indexToTruncate = journal.append(-1, data).index();
    journal.append(3, data);
    journal.deleteAfter(indexToTruncate);

    // then
    assertThat(journal.getLastSegment().lastAsqn()).isEqualTo(expectedLastAsqn);
  }
```

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
:+1: Looks good. One edge case is not handled. Please see my comment.

**Review by deepthidevaki — APPROVED** [review]
:tada:

**Comment by megglos** [comment]
bors merge
