### PR TITLE
Suppress transient connection issues to ES/OS down to a WARN

### LINKED ISSUE #25811: ElasticsearchExporterException: Failed retrieving mappings from index/index templates with pattern
**Describe the bug**

https://console.cloud.google.com/errors/detail/CMjsyJf_4uLtkAE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjvZQ&project=camunda-saas-int-chaos

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.exporter.exceptions.ElasticsearchExporterException: Failed retrieving mappings from index/index templates with pattern [camunda-tenant-8.8.0_*,camunda-web-session-8.8.0_*,operate-decision-8.3.0_*,camunda-authorization-8.8.0_*,tasklist-metric-8.3.0_*,operate-process-8.3.0_*,camunda-user-8.8.0_*,operate-metric-8.3.0_*,tasklist-form-8.4.0_*,camunda-mapping-8.8.0_*,camunda-role-8.8.0_*,operate-decision-requirements-8.3.0_*,tasklist-import-position-8.2.0_*,camunda-group-8.8.0_*,operate-import-position-8.3.0_*]

at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.getMappings ( io/camunda.exporter.schema.elasticsearch/ElasticsearchEngineClient.java:171 )
at io.camunda.exporter.schema.SchemaManager.validateIndices ( io/camunda.exporter.schema/SchemaManager.java:300 )
at io.camunda.exporter.schema.SchemaManager.startup ( io/camunda.exporter.schema/SchemaManager.java:63 )
at io.camunda.exporter.CamundaExporter.open ( io/camunda.exporter/CamundaExporter.java:132 )
at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$openExporter$0 ( io/camunda.zeebe.broker.exporter.stream/ExporterContainer.java:118 )
at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader ( io/camunda.zeebe.util.jar/ThreadContextUtil.java:59 )
at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader ( io/camunda.zeebe.util.jar/ThreadContextUtil.java:35 )
at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.openExporter ( io/camunda.zeebe.broker.exporter.stream/ExporterContainer.java:117 )
at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$startActiveExportingMode$16 ( io/camunda.zeebe.broker.exporter.stream/ExporterDirector.java:529 )
at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run ( io/camunda.zeebe.scheduler.retry/BackOffRetryStrategy.java:51 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:86 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:43 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:125 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:127 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:104 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:224 )
Caused by: java.io.IOException

…
at org.elasticsearch.client.RestClient.extractAndWrapCause ( RestClient.java:939 )
at org.elasticsearch.client.RestClient.performRequest ( RestClient.java:304 )
at org.elasticsearch.client.RestClient.performRequest ( RestClient.java:292 )
at co.elastic.clients.transport.rest_client.RestClientHttpClient.performRequest ( RestClientHttpClient.java:92 )
at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest ( ElasticsearchTransportBase.java:145 )
at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.getMapping ( ElasticsearchIndicesClient.java:1257 )
at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.getMapping ( ElasticsearchIndicesClient.java:1275 )
at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.getCurrentMappings ( ElasticsearchEngineClient.java:329 )
at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.getMappings ( ElasticsearchEngineClient.java:154 )
…
Caused by: java.net.UnknownHostException

…
at org.elasticsearch.client.RestClient.performRequest ( RestClient.java:300 )
at org.elasticsearch.client.RestClient.performRequest ( RestClient.java:292 )
at co.elastic.clients.transport.rest_client.RestClientHttpClient.performRequest ( RestClientHttpClient.java:92 )
at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest ( ElasticsearchTransportBase.java:145 )
at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.getMapping ( ElasticsearchIndicesClient.java:1257 )
at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.getMapping ( ElasticsearchIndicesClient.java:1275 )
at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.getCurrentMappings ( ElasticsearchEngineClient.java:329 )
at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.getMappings ( ElasticsearchEngineClient.java:154 )
…
```
</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

Suppress transient connection issues to ES/OS down to a WARN, for the schema manager

## Related issues

closes #25811

### CODE REVIEW

File: schema-manager/src/main/java/io/camunda/search/schema/utils/SuppressLogger.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+      Set.of(SocketTimeoutException.class, ConnectException.class, SocketException.class);
+  private final Logger logger;
+
+  public SuppressLogger(final Logger logger) {
+    this.logger = logger;
+  }
+
+  public void error(final String message, final Throwable t) {
+    if (SUPPRESSED_EXCEPTIONS.contains(t.getClass())) {
+      logger.warn("[downgraded from ERROR]: {} ", message, t);
```
Comment (rodrigo-lourenco-lopes) [inline schema-manager/src/main/java/io/camunda/search/schema/utils/SuppressLogger.java:28]: ❓ Do we have other use cases where we use the same pattern? And we do we need to explain why it is downgraded from an error? I don't have a strong opinion here, as adding more info might also make it to verbose.

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
Thanks for the improvement 🚀  this will save us a lot of work for the medic in the error reporting tool 😅

File: schema-manager/src/main/java/io/camunda/search/schema/utils/SuppressLogger.java (hunk 1 above)
Comment (EuroLew) [reply schema-manager/src/main/java/io/camunda/search/schema/utils/SuppressLogger.java:28]: I feel it's self explanatory enough with the variable and class names
