### PR TITLE
fix(broker): fix race condition in persisting snapshot

### LINKED ISSUE #6377: Snapshot is not valid. There is no checksum file.
**Describe the bug**

Snapshot can't be persisted because the checksum file is missing.

It seems like we have a race condition between taking and persisting the snapshot.
```
D 2021-02-17T13:09:11.883106Z Broker-2-SnapshotDirector-1 Based on lowest exporter position '591' and last processed position '714', determined '591' as snapshot position.  Broker-2-SnapshotDirector-1
D 2021-02-17T13:09:11.892135Z io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/1/pending/499-1-1613567351888-714-591.  io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore
D 2021-02-17T13:09:11.921155Z Broker-2-SnapshotDirector-1 Created pending snapshot for Broker-2-StreamProcessor-1  Broker-2-SnapshotDirector-1
I 2021-02-17T13:09:11.922269Z Broker-2-SnapshotDirector-1 Finished taking snapshot, need to wait until last written event position 715 is committed, current commit position is 715. After that snapshot can be marked as valid.  Broker-2-SnapshotDirector-1
D 2021-02-17T13:09:11.924762Z io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore Purging snapshots older than FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/499-1-1613567351888-714-591, metadata=FileBasedSnapshotMetadata{index=499, term=1, timestamp=2021-02-17 01:09:11,888, processedPosition=714, exporterPosition=591}}  io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore
D 2021-02-17T13:09:11.931943Z io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore Search for orphaned snapshots below oldest valid snapshot with index FileBasedSnapshotMetadata{index=499, term=1, timestamp=2021-02-17 01:09:11,888, processedPosition=714, exporterPosition=591} in /usr/local/zeebe/data/raft-partition/partitions/1/pending  io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore
D 2021-02-17T13:09:11.934254Z io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore New snapshot 499-1-1613567351888-714-591 was persisted. Start replicating.  io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore
D 2021-02-17T13:09:11.935008Z Broker-2-DeletionService-1 Compacting Atomix log up to index 499  Broker-2-DeletionService-1
D 2021-02-17T13:09:11.957536Z io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore Created new snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/499-1-1613567351888-714-591, metadata=FileBasedSnapshotMetadata{index=499, term=1, timestamp=2021-02-17 01:09:11,888, processedPosition=714, exporterPosition=591}}  io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore
I 2021-02-17T13:09:11.958251Z Broker-2-SnapshotDirector-1 Current commit position 715 >= 715, snapshot 499-1-1613567351888-714-591 is valid and has been persisted.  Broker-2-SnapshotDirector-1
E 2021-02-17T13:09:11.958650Z Broker-2-SnapshotDirector-1 Unexpected exception occurred on moving valid snapshot.  Broker-2-SnapshotDirector-1
  undefined
```

There are no other errors which indicate problem on writing the snapshot.

Error group https://console.cloud.google.com/errors/CIzr1vKOuue-DA?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

**To Reproduce**

Not sure seems to be a race condition.

**Expected behavior**
No race condition and that I can persist my snapshot.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Snapshot is not valid. There is no checksum file.
	at io.zeebe.snapshots.broker.impl.FileBasedTransientSnapshot.lambda$persist$3(FileBasedTransientSnapshot.java:114) ~[zeebe-snapshots-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:136) ~[zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
 - OS:  k8
 - Zeebe Version: SNAPSHOT
 - Configuration:

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

It's possible for a second call to `persist` to be executed between the first call to `persist` and the subsequent nulling of the pending snapshot (since it happens in an `onComplete` block). This PR eliminates this race condition and changes the 'persist' operation to be idempotent so that external race conditions don't cause it to fail.
 
## Related issues

closes #6377 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by Zelldon** [comment]
@MiguelPires awesome that you already worked on that :rocket: thanks for that! 

One thing I thought as a alternative way is to just register for the commit listener only if after taking the snapshot when we are not able to persist, because the commit position wasn't high enough. This means we wouldn't register per default only if we need to. wdyt?

Do you think we can add a test for that? Tbh it would also be nice for me if we had idempotency on the #persist, so second call would be a no-op for example.

**Comment by MiguelPires** [comment]
I definitely agree, that makes more sense. Making `persist` idempotent would also be simple to do and even easier to test so I like it even more I think. Thanks for suggesting it!

**Comment by MiguelPires** [comment]
@Zelldon I changed persist to be idempotent. Please have a look when you can.

File: broker/src/main/java/io/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 1]
```diff
@@ -199,7 +199,6 @@ private void persistSnapshotIfLastWrittenPositionCommitted() {
               if (pendingSnapshot != null
                   && lastWrittenEventPosition != null
                   && currentCommitPosition >= lastWrittenEventPosition) {
-
                 final var snapshotPersistFuture = pendingSnapshot.persist();
 
                 snapshotPersistFuture.onComplete(
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:204]: I like that persist is now idempotent :+1: Didn't expected that you remove the other change :) Isn;t it problematic when we call the onComplete listener twice? Since we reset the positions twice then? Happy to discuss this :)

**Review by ChrisKujawa — APPROVED** [review]
Thanks @MiguelPires :+1: :medal_military:

**Comment by MiguelPires** [comment]
bors cancel

File: broker/src/main/java/io/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 2]
```diff
@@ -198,7 +200,9 @@ private void persistSnapshotIfLastWrittenPositionCommitted() {
             (currentCommitPosition, error) -> {
               if (pendingSnapshot != null
                   && lastWrittenEventPosition != null
-                  && currentCommitPosition >= lastWrittenEventPosition) {
+                  && currentCommitPosition >= lastWrittenEventPosition
+                  && !persistingSnapshot) {
+                persistingSnapshot = true;
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:205]: @MiguelPires I think this could be backported right?
