### PR TITLE
Avoid JVM crashes on closing the broker

### LINKED ISSUE #5066: Segmentation fault when closing the broker
**Describe the bug**
The JVM crashes when the broker is closing. It seems that the `ExporterDirector` tried to access RocksDB but it is already closed.

```
Stack: [0x00007f96857af000,0x00007f96858b0000],  sp=0x00007f96858adc80,  free space=1019k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [librocksdbjni13548028829736559504.so+0x202f3a]  std::_Function_handler<rocksdb::Status (rocksdb::ReadOptions const&, rocksdb::Slice const&, std::string*), std::_Bind<rocksdb::Status (rocksdb::Transaction::*(rocksdb::Transaction*, std::_Placeholder<1>, rocksdb::ColumnFamilyHandle*, std::_Placeholder<2>, std::_Placeholder<3>))(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::string*)> >::_M_invoke(std::_Any_data const&, rocksdb::ReadOptions const&, rocksdb::Slice const&, std::string*&&)+0x2a
C  [librocksdbjni13548028829736559504.so+0x1fd204]  txn_get_helper(JNIEnv_*, std::function<rocksdb::Status (rocksdb::ReadOptions const&, rocksdb::Slice const&, std::string*)> const&, long const&, _jbyteArray* const&, int const&)+0x84
C  [librocksdbjni13548028829736559504.so+0x1fd83f]  Java_org_rocksdb_Transaction_get__JJ_3BIJ+0x7f
j  org.rocksdb.Transaction.get(JJ[BIJ)[B+0
j  jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+431
J 12834 c2 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.3 (10 bytes) @ 0x00007f9724ac6274 [0x00007f9724ac6220+0x0000000000000054]
J 2612 c1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.3 (65 bytes) @ 0x00007f971d26410c [0x00007f971d263da0+0x000000000000036c]
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.get(JJ[BI)[B+48
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$getValue$2(JLio/zeebe/db/DbContext;ILio/zeebe/db/impl/rocksdb/transaction/ZeebeTransaction;)V+18
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb$$Lambda$1068.run(Lio/zeebe/db/impl/rocksdb/transaction/ZeebeTransaction;)V+17
J 12753 c1 io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb$$Lambda$1069.run()V (12 bytes) @ 0x00007f971e58a72c [0x00007f971e58a480+0x00000000000002ac]
j  io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(Lio/zeebe/db/TransactionOperation;)V+8
J 12752 c1 io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(Lio/zeebe/db/TransactionOperation;)V (77 bytes) @ 0x00007f971e5898b4 [0x00007f971e5896e0+0x00000000000001d4]
J 13194 c1 io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(Lio/zeebe/db/DbContext;Lio/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb$TransactionConsumer;)V (14 bytes) @ 0x00007f971e66601c [0x00007f971e665b20+0x00000000000004fc]
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.getValue(JLio/zeebe/db/DbContext;I)Lorg/agrona/DirectBuffer;+12
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.get(JLio/zeebe/db/DbContext;Lio/zeebe/db/DbKey;)Lorg/agrona/DirectBuffer;+22
j  io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(Lio/zeebe/db/DbContext;Lio/zeebe/db/DbKey;Lio/zeebe/db/DbValue;)Lio/zeebe/db/DbValue;+10
j  io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(Lio/zeebe/db/DbContext;Lio/zeebe/db/DbKey;)Lio/zeebe/db/DbValue;+7
j  io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(Lio/zeebe/db/DbKey;)Lio/zeebe/db/DbValue;+6
j  io.zeebe.broker.exporter.stream.ExportersState.getPosition()J+8
j  io.zeebe.broker.exporter.stream.ExportersState.getPosition(Ljava/lang/String;)J+9
j  io.zeebe.broker.exporter.stream.ExporterDirector.onSnapshotRecovered()V+77
j  io.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted()V+120
j  io.zeebe.util.sched.ActorTask$$Lambda$562.run()V+4
J 13806 c2 io.zeebe.util.sched.ActorJob.execute(Lio/zeebe/util/sched/ActorThread;)V (203 bytes) @ 0x00007f97247a09c8 [0x00007f97247a0860+0x0000000000000168]
J 10364 c1 io.zeebe.util.sched.ActorTask.execute(Lio/zeebe/util/sched/ActorThread;)Z (195 bytes) @ 0x00007f971e0e61f4 [0x00007f971e0e5fa0+0x0000000000000254]
J 9002 c2 io.zeebe.util.sched.ActorThread.doWork()V (103 bytes) @ 0x00007f972451091c [0x00007f9724510580+0x000000000000039c]
J 12307 c2 io.zeebe.util.sched.ActorThread.run()V (49 bytes) @ 0x00007f9724a68a94 [0x00007f9724a689e0+0x00000000000000b4]
``` 

**To Reproduce**
* it happens quite often for builds running in the Zeebe CI on branch `0.24`
* the situation is not clear yet - happens on different tests
* looking at the output it seems that
  * it runs an integration test with 3 nodes
  * the test is finished and it is closing the brokers
  * while closing the brokers, one follower gets elected as a new leader
  * it tries to install the partition services while it is getting closed from the test

**Expected behavior**
No JVM crash :see_no_evil: 

**Log/Stacktrace**

<details><summary>Full Java Error Report</summary>
 <p>

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f941e88ff3a, pid=4239, tid=31029
#
# JRE version: OpenJDK Runtime Environment (11.0.3+1) (build 11.0.3+1-Debian-1bpo91)
# Java VM: OpenJDK 64-Bit Server VM (11.0.3+1-Debian-1bpo91, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [librocksdbjni13548028829736559504.so+0x202f3a]  std::_Function_handler<rocksdb::Status (rocksdb::ReadOptions const&, rocksdb::Slice const&, std::string*), std::_Bind<rocksdb::Status (rocksdb::Transaction::*(rocksdb::Transaction*, std::_Placeholder<1>, rocksdb::ColumnFamilyHandle*, std::_Placeholder<2>, std::_Placeholder<3>))(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::string*)> >::_M_invoke(std::_Any_data const&, rocksdb::ReadOptions const&, rocksdb::Slice const&, std::string*&&)+0x2a
#
# Core dump will be written. Default location: /home/jenkins/agent/workspace/zeebe-io_zeebe_stable_0.24/qa/integration-tests/core.%e.%p.%t
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -XX:+UseContainerSupport -XX:MaxRAMFraction=8 -Xmx2048m -XX:MaxDirectMemorySize=4g /home/jenkins/agent/workspace/zeebe-io_zeebe_stable_0.24/qa/integration-tests/target/surefire/surefirebooter10423158930574598707.jar /home/jenkins/agent/workspace/zeebe-io_zeebe_stable_0.24/qa/integration-tests/target/surefire 2020-07-24T13-53-31_643-jvmRun5 surefire16185005548469433544tmp surefire_417551437800713479873tmp

Host: Intel(R) Xeon(R) CPU @ 2.30GHz, 32 cores, 32G, Debian GNU/Linux 9 (stretch)
Time: Fri Jul 24 13:59:04 2020 UTC elapsed time: 327 seconds (0d 0h 5m 27s)

---------------  T H R E A D  ---------------

Current thread (0x00007f956c1e9800):  JavaThread "Broker-1-zb-fs-workers-1" daemon [_thread_in_native, id=31029, stack(0x00007f96857af000,0x00007f96858b0000)]

Stack: [0x00007f96857af000,0x00007f96858b0000],  sp=0x00007f96858adc80,  free space=1019k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [librocksdbjni13548028829736559504.so+0x202f3a]  std::_Function_handler<rocksdb::Status (rocksdb::ReadOptions const&, rocksdb::Slice const&, std::string*), std::_Bind<rocksdb::Status (rocksdb::Transaction::*(rocksdb::Transaction*, std::_Placeholder<1>, rocksdb::ColumnFamilyHandle*, std::_Placeholder<2>, std::_Placeholder<3>))(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::string*)> >::_M_invoke(std::_Any_data const&, rocksdb::ReadOptions const&, rocksdb::Slice const&, std::string*&&)+0x2a
C  [librocksdbjni13548028829736559504.so+0x1fd204]  txn_get_helper(JNIEnv_*, std::function<rocksdb::Status (rocksdb::ReadOptions const&, rocksdb::Slice const&, std::string*)> const&, long const&, _jbyteArray* const&, int const&)+0x84
C  [librocksdbjni13548028829736559504.so+0x1fd83f]  Java_org_rocksdb_Transaction_get__JJ_3BIJ+0x7f
j  org.rocksdb.Transaction.get(JJ[BIJ)[B+0
j  jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+431
J 12834 c2 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.3 (10 bytes) @ 0x00007f9724ac6274 [0x00007f9724ac6220+0x0000000000000054]
J 2612 c1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.3 (65 bytes) @ 0x00007f971d26410c [0x00007f971d263da0+0x000000000000036c]
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.get(JJ[BI)[B+48
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$getValue$2(JLio/zeebe/db/DbContext;ILio/zeebe/db/impl/rocksdb/transaction/ZeebeTransaction;)V+18
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb$$Lambda$1068.run(Lio/zeebe/db/impl/rocksdb/transaction/ZeebeTransaction;)V+17
J 12753 c1 io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb$$Lambda$1069.run()V (12 bytes) @ 0x00007f971e58a72c [0x00007f971e58a480+0x00000000000002ac]
j  io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(Lio/zeebe/db/TransactionOperation;)V+8
J 12752 c1 io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(Lio/zeebe/db/TransactionOperation;)V (77 bytes) @ 0x00007f971e5898b4 [0x00007f971e5896e0+0x00000000000001d4]
J 13194 c1 io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(Lio/zeebe/db/DbContext;Lio/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb$TransactionConsumer;)V (14 bytes) @ 0x00007f971e66601c [0x00007f971e665b20+0x00000000000004fc]
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.getValue(JLio/zeebe/db/DbContext;I)Lorg/agrona/DirectBuffer;+12
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.get(JLio/zeebe/db/DbContext;Lio/zeebe/db/DbKey;)Lorg/agrona/DirectBuffer;+22
j  io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(Lio/zeebe/db/DbContext;Lio/zeebe/db/DbKey;Lio/zeebe/db/DbValue;)Lio/zeebe/db/DbValue;+10
j  io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(Lio/zeebe/db/DbContext;Lio/zeebe/db/DbKey;)Lio/zeebe/db/DbValue;+7
j  io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(Lio/zeebe/db/DbKey;)Lio/zeebe/db/DbValue;+6
j  io.zeebe.broker.exporter.stream.ExportersState.getPosition()J+8
j  io.zeebe.broker.exporter.stream.ExportersState.getPosition(Ljava/lang/String;)J+9
j  io.zeebe.broker.exporter.stream.ExporterDirector.onSnapshotRecovered()V+77
j  io.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted()V+120
j  io.zeebe.util.sched.ActorTask$$Lambda$562.run()V+4
J 13806 c2 io.zeebe.util.sched.ActorJob.execute(Lio/zeebe/util/sched/ActorThread;)V (203 bytes) @ 0x00007f97247a09c8 [0x00007f97247a0860+0x0000000000000168]
J 10364 c1 io.zeebe.util.sched.ActorTask.execute(Lio/zeebe/util/sched/ActorThread;)Z (195 bytes) @ 0x00007f971e0e61f4 [0x00007f971e0e5fa0+0x0000000000000254]
J 9002 c2 io.zeebe.util.sched.ActorThread.doWork()V (103 bytes) @ 0x00007f972451091c [0x00007f9724510580+0x000000000000039c]
J 12307 c2 io.zeebe.util.sched.ActorThread.run()V (49 bytes) @ 0x00007f9724a68a94 [0x00007f9724a689e0+0x00000000000000b4]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x827f02]
V  [libjvm.so+0x826030]
V  [libjvm.so+0x8c9b75]
V  [libjvm.so+0xd2c003]
V  [libjvm.so+0xd2c29f]
V  [libjvm.so+0xd28686]
V  [libjvm.so+0xb8f17e]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.rocksdb.Transaction.get(JJ[BIJ)[B+0
j  jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+431
J 12834 c2 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.3 (10 bytes) @ 0x00007f9724ac6274 [0x00007f9724ac6220+0x0000000000000054]
J 2612 c1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.3 (65 bytes) @ 0x00007f971d26410c [0x00007f971d263da0+0x000000000000036c]
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.get(JJ[BI)[B+48
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.lambda$getValue$2(JLio/zeebe/db/DbContext;ILio/zeebe/db/impl/rocksdb/transaction/ZeebeTransaction;)V+18
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb$$Lambda$1068.run(Lio/zeebe/db/impl/rocksdb/transaction/ZeebeTransaction;)V+17
J 12753 c1 io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb$$Lambda$1069.run()V (12 bytes) @ 0x00007f971e58a72c [0x00007f971e58a480+0x00000000000002ac]
j  io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(Lio/zeebe/db/TransactionOperation;)V+8
J 12752 c1 io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(Lio/zeebe/db/TransactionOperation;)V (77 bytes) @ 0x00007f971e5898b4 [0x00007f971e5896e0+0x00000000000001d4]
J 13194 c1 io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(Lio/zeebe/db/DbContext;Lio/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb$TransactionConsumer;)V (14 bytes) @ 0x00007f971e66601c [0x00007f971e665b20+0x00000000000004fc]
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.getValue(JLio/zeebe/db/DbContext;I)Lorg/agrona/DirectBuffer;+12
j  io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.get(JLio/zeebe/db/DbContext;Lio/zeebe/db/DbKey;)Lorg/agrona/DirectBuffer;+22
j  io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(Lio/zeebe/db/DbContext;Lio/zeebe/db/DbKey;Lio/zeebe/db/DbValue;)Lio/zeebe/db/DbValue;+10
j  io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(Lio/zeebe/db/DbContext;Lio/zeebe/db/DbKey;)Lio/zeebe/db/DbValue;+7
j  io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(Lio/zeebe/db/DbKey;)Lio/zeebe/db/DbValue;+6
j  io.zeebe.broker.exporter.stream.ExportersState.getPosition()J+8
j  io.zeebe.broker.exporter.stream.ExportersState.getPosition(Ljava/lang/String;)J+9
j  io.zeebe.broker.exporter.stream.ExporterDirector.onSnapshotRecovered()V+77
j  io.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted()V+120
j  io.zeebe.util.sched.ActorTask$$Lambda$562.run()V+4
J 13806 c2 io.zeebe.util.sched.ActorJob.execute(Lio/zeebe/util/sched/ActorThread;)V (203 bytes) @ 0x00007f97247a09c8 [0x00007f97247a0860+0x0000000000000168]
J 10364 c1 io.zeebe.util.sched.ActorTask.execute(Lio/zeebe/util/sched/ActorThread;)Z (195 bytes) @ 0x00007f971e0e61f4 [0x00007f971e0e5fa0+0x0000000000000254]
J 9002 c2 io.zeebe.util.sched.ActorThread.doWork()V (103 bytes) @ 0x00007f972451091c [0x00007f9724510580+0x000000000000039c]
J 12307 c2 io.zeebe.util.sched.ActorThread.run()V (49 bytes) @ 0x00007f9724a68a94 [0x00007f9724a689e0+0x00000000000000b4]
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 128 (SI_KERNEL), si_addr: 0x0000000000000000

Register to memory mapping:

RAX=0x00007f936495c990 points into unknown readable memory: 90 ce 95 64 93 7f 00 00
RBX=0x00007f96858adce0 is pointing into the stack for thread: 0x00007f956c1e9800
RCX=0x00007f96858adcd0 is pointing into the stack for thread: 0x00007f956c1e9800
RDX=0x00007f9364920d10 points into unknown readable memory: 00 00 00 00 00 00 00 00
RSP=0x00007f96858adc80 is pointing into the stack for thread: 0x00007f956c1e9800
RBP=0x00007f96858adc90 is pointing into the stack for thread: 0x00007f956c1e9800
RSI=0x00007f9470000e40 points into unknown readable memory: 00 00 00 0d 74 65 73 74
RDI=0x747365740d000000 is an unknown value
R8 =0x00007f96858adcc8 is pointing into the stack for thread: 0x00007f956c1e9800
R9 =0x00007f96858adcc0 is pointing into the stack for thread: 0x00007f956c1e9800
R10=0x0000000000000061 is an unknown value
R11=0x0000000080000102 points into unknown readable memory: 0a 00 00 08 08 00
R12=0x00007f9739934fa0: _ZNSs4_Rep20_S_empty_rep_storageE+0x0000000000000000 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6 at 0x00007f97395b4000
R13=0x00007f9470000e40 points into unknown readable memory: 00 00 00 0d 74 65 73 74
R14=0x00007f96858add50 is pointing into the stack for thread: 0x00007f956c1e9800
R15=0x00007f96858add40 is pointing into the stack for thread: 0x00007f956c1e9800


Registers:
RAX=0x00007f936495c990, RBX=0x00007f96858adce0, RCX=0x00007f96858adcd0, RDX=0x00007f9364920d10
RSP=0x00007f96858adc80, RBP=0x00007f96858adc90, RSI=0x00007f9470000e40, RDI=0x747365740d000000
R8 =0x00007f96858adcc8, R9 =0x00007f96858adcc0, R10=0x0000000000000061, R11=0x0000000080000102
R12=0x00007f9739934fa0, R13=0x00007f9470000e40, R14=0x00007f96858add50, R15=0x00007f96858add40
RIP=0x00007f941e88ff3a, EFLAGS=0x0000000000010202, CSGSFS=0x002b000000000033, ERR=0x0000000000000000
  TRAPNO=0x000000000000000d

Top of Stack: (sp=0x00007f96858adc80)
0x00007f96858adc80:   00007f96858add50 00007f956c1e9b40
0x00007f96858adc90:   00007f96858add20 00007f941e88a204
0x00007f96858adca0:   00007f96858ae2e8 00007f96858add3c
0x00007f96858adcb0:   0000000000000018 00007f972482f1d8 

Instructions: (pc=0x00007f941e88ff3a)
0x00007f941e88ff1a:   ec 08 48 8b 3e 4d 8b 08 4c 8b 17 48 8b 77 08 48
0x00007f941e88ff2a:   03 77 18 48 8b 47 10 41 f6 c2 01 74 08 48 8b 3e
0x00007f941e88ff3a:   4e 8b 54 17 ff 49 89 c8 48 89 df 48 89 c1 41 ff
0x00007f941e88ff4a:   d2 48 83 c4 08 48 89 d8 5b 5d c3 66 2e 0f 1f 84 

Stack slot to memory mapping:
stack at sp + 0 slots: 0x00007f96858add50 is pointing into the stack for thread: 0x00007f956c1e9800
stack at sp + 1 slots: 0x00007f956c1e9b40 points into unknown readable memory: a0 4f c7 3a 97 7f 00 00
stack at sp + 2 slots: 0x00007f96858add20 is pointing into the stack for thread: 0x00007f956c1e9800
stack at sp + 3 slots: 0x00007f941e88a204: _Z14txn_get_helperP7JNIEnv_RKSt8functionIFN7rocksdb6StatusERKNS2_11ReadOptionsERKNS2_5SliceEPSsEERKlRKP11_jbyteArrayRKi+0x0000000000000084 in /tmp/librocksdbjni13548028829736559504.so at 0x00007f941e68d000
stack at sp + 4 slots: 0x00007f96858ae2e8 is pointing into the stack for thread: 0x00007f956c1e9800
stack at sp + 5 slots: 0x00007f96858add3c is pointing into the stack for thread: 0x00007f956c1e9800
stack at sp + 6 slots: 0x0000000000000018 is an unknown value
stack at sp + 7 slots: 0x00007f972482f1d8 is at entry_point+152 in (nmethod*)0x00007f972482ef90


---------------  P R O C E S S  ---------------

Threads class SMR info:
_java_thread_list=0x00007f95a40008c0, length=103, elements={
0x00007f9734011800, 0x00007f97342b8800, 0x00007f97342ba800, 0x00007f97342c2000,
0x00007f97342c4000, 0x00007f97342c6000, 0x00007f97342c8000, 0x00007f9734312000,
0x00007f9734317800, 0x00007f97349b5000, 0x00007f9734f7f800, 0x00007f96ac088800,
0x00007f96c8251800, 0x00007f96c80d5800, 0x00007f968010b800, 0x00007f9680124800,
...
}

Java Threads: ( => current thread )
  0x00007f9734011800 JavaThread "main" [_thread_blocked, id=4270, stack(0x00007f973ba00000,0x00007f973bb01000)]
  0x00007f97342b8800 JavaThread "Reference Handler" daemon [_thread_blocked, id=4311, stack(0x00007f97101e9000,0x00007f97102ea000)]
  0x00007f97342ba800 JavaThread "Finalizer" daemon [_thread_blocked, id=4314, stack(0x00007f97100e8000,0x00007f97101e9000)]
  0x00007f97342c2000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=4318, stack(0x00007f970358c000,0x00007f970368d000)]
  0x00007f97342c4000 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=4320, stack(0x00007f970348b000,0x00007f970358c000)]
  0x00007f97342c6000 JavaThread "C1 CompilerThread0" daemon [_thread_blocked, id=4322, stack(0x00007f970338a000,0x00007f970348b000)]
  0x00007f97342c8000 JavaThread "Sweeper thread" daemon [_thread_blocked, id=4327, stack(0x00007f9703289000,0x00007f970338a000)]
  0x00007f9734312000 JavaThread "Service Thread" daemon [_thread_blocked, id=4337, stack(0x00007f9703188000,0x00007f9703289000)]
  0x00007f9734317800 JavaThread "Common-Cleaner" daemon [_thread_blocked, id=4340, stack(0x00007f9702f85000,0x00007f9703086000)]
  0x00007f97349b5000 JavaThread "surefire-forkedjvm-command-thread" daemon [_thread_in_native, id=4407, stack(0x00007f9702651000,0x00007f9702752000)]
  0x00007f9734f7f800 JavaThread "ForkJoinPool.commonPool-worker-3" daemon [_thread_blocked, id=4682, stack(0x00007f9702550000,0x00007f9702651000)]
  0x00007f96ac088800 JavaThread "OkHttp ConnectionPool" daemon [_thread_blocked, id=4831, stack(0x00007f9701211000,0x00007f9701312000)]
  0x00007f96c8251800 JavaThread "tc-okhttp-stream-1503545914" daemon [_thread_in_native, id=4992, stack(0x00007f970070a000,0x00007f970080b000)]
  0x00007f96c80d5800 JavaThread "testcontainers-ryuk" daemon [_thread_blocked, id=5016, stack(0x00007f9700508000,0x00007f9700609000)]
  0x00007f968010b800 JavaThread "grpc-default-worker-ELG-1-1" daemon [_thread_in_native, id=7482, stack(0x00007f96875da000,0x00007f96876db000)]
  0x00007f9680124800 JavaThread "grpc-default-worker-ELG-1-2" daemon [_thread_in_native, id=7490, stack(0x00007f96876ed000,0x00007f96877ee000)]
  0x00007f967c183000 JavaThread "grpc-default-worker-ELG-1-3" daemon [_thread_in_native, id=7547, stack(0x00007f96870b6000,0x00007f96871b7000)]
  0x00007f93ec001000 JavaThread "grpc-default-worker-ELG-1-4" daemon [_thread_in_native, id=10448, stack(0x00007f9685fb5000,0x00007f96860b6000)]
  0x00007f93ec003000 JavaThread "grpc-default-worker-ELG-1-5" daemon [_thread_in_native, id=10449, stack(0x00007f94740e3000,0x00007f94741e4000)]
  0x00007f967c00b800 JavaThread "grpc-default-worker-ELG-1-6" daemon [_thread_in_native, id=10452, stack(0x00007f941c388000,0x00007f941c489000)]
  0x00007f953c001000 JavaThread "grpc-default-worker-ELG-1-7" daemon [_thread_in_native, id=10458, stack(0x00007f941c287000,0x00007f941c388000)]
  0x00007f93e0001000 JavaThread "grpc-default-worker-ELG-1-8" daemon [_thread_in_native, id=10478, stack(0x00007f941c085000,0x00007f941c186000)]
  0x00007f953c003800 JavaThread "grpc-shared-destroyer-0" daemon [_thread_blocked, id=10661, stack(0x00007f95ff5f2000,0x00007f95ff6f3000)]
  0x00007f9658048800 JavaThread "ForkJoinPool.commonPool-worker-5" daemon [_thread_blocked, id=10772, stack(0x00007f95ff6f3000,0x00007f95ff7f4000)]
  0x00007f96c817d000 JavaThread "ForkJoinPool.commonPool-worker-7" daemon [_thread_blocked, id=16198, stack(0x00007f94777e3000,0x00007f94778e4000)]
  0x00007f96c8289800 JavaThread "ForkJoinPool.commonPool-worker-9" daemon [_thread_blocked, id=16353, stack(0x00007f94765ed000,0x00007f94766ee000)]
  0x00007f96c81bf800 JavaThread "ForkJoinPool.commonPool-worker-11" daemon [_thread_blocked, id=16742, stack(0x00007f95fc9d7000,0x00007f95fcad8000)]
  0x00007f96c825f800 JavaThread "ForkJoinPool.commonPool-worker-13" daemon [_thread_blocked, id=16745, stack(0x00007f954cdfb000,0x00007f954cefc000)]
  0x00007f96c8262000 JavaThread "ForkJoinPool.commonPool-worker-15" daemon [_thread_blocked, id=17009, stack(0x00007f96850a8000,0x00007f96851a9000)]
  0x00007f935c001000 JavaThread "grpc-default-executor-2" daemon [_thread_blocked, id=27105, stack(0x00007f9477cfd000,0x00007f9477dfe000)]
  0x00007f93d4205000 JavaThread "grpc-default-executor-3" daemon [_thread_blocked, id=27925, stack(0x00007f9685bb3000,0x00007f9685cb4000)]
  0x00007f9735ae4000 JavaThread "Time-limited test" daemon [_thread_blocked, id=29401, stack(0x00007f96855ad000,0x00007f96856ae000)]
  0x00007f9590001000 JavaThread "Broker-2-zb-actors-0" daemon [_thread_blocked, id=29416, stack(0x00007f95fc8d6000,0x00007f95fc9d7000)]
  0x00007f9590009000 JavaThread "Broker-2-zb-actors-1" daemon [_thread_blocked, id=29417, stack(0x00007f968479f000,0x00007f96848a0000)]
  0x00007f9590012000 JavaThread "Broker-2-zb-fs-workers-0" daemon [_thread_blocked, id=29418, stack(0x00007f96854ac000,0x00007f96855ad000)]
  0x00007f9590013800 JavaThread "Broker-2-zb-fs-workers-1" daemon [_thread_blocked, id=29419, stack(0x00007f968469e000,0x00007f968479f000)]
  0x00007f9590015000 JavaThread "atomix-cluster-0" daemon [_thread_blocked, id=29424, stack(0x00007f95feeeb000,0x00007f95fefec000)]
  0x00007f959000d800 JavaThread "atomix-0" daemon [_thread_blocked, id=29428, stack(0x00007f95fc1cf000,0x00007f95fc2d0000)]
  0x00007f959000e000 JavaThread "netty-messaging-event-epoll-server-0" daemon [_thread_in_native, id=29434, stack(0x00007f952cbf9000,0x00007f952ccfa000)]
  0x00007f959000f000 JavaThread "netty-messaging-event-epoll-server-0" daemon [_thread_in_native, id=29444, stack(0x00007f9700a0b000,0x00007f9700b0c000)]
  0x00007f9380033000 JavaThread "netty-unicast-event-nio-client-0" daemon [_thread_in_native, id=29452, stack(0x00007f96858b0000,0x00007f96859b1000)]
  0x00007f9380034800 JavaThread "atomix-cluster-events" daemon [_thread_blocked, id=29453, stack(0x00007f96852aa000,0x00007f96853ab000)]
  0x00007f9380036000 JavaThread "atomix-cluster-heartbeat-sender" daemon [_thread_blocked, id=29454, stack(0x00007f96851a9000,0x00007f96852aa000)]
  0x00007f9380037800 JavaThread "atomix-cluster-event-executor-0" daemon [_thread_blocked, id=29455, stack(0x00007f9684ea6000,0x00007f9684fa7000)]
  0x00007f945c002000 JavaThread "raft-server-2-raft-partition-partition-1" daemon [_thread_blocked, id=29462, stack(0x00007f968449c000,0x00007f968459d000)]
  0x00007f945c003800 JavaThread "raft-server-2-raft-partition-partition-1-load" daemon [_thread_blocked, id=29463, stack(0x00007f968439b000,0x00007f968449c000)]
  0x00007f945c005000 JavaThread "raft-server-2-raft-partition-partition-1-state" daemon [_thread_blocked, id=29464, stack(0x00007f968429a000,0x00007f968439b000)]
  0x00007f95a0007000 JavaThread "netty-messaging-event-epoll-client-0" daemon [_thread_in_native, id=29491, stack(0x00007f95fedea000,0x00007f95feeeb000)]
  0x00007f9458012000 JavaThread "netty-messaging-timeout-0" daemon [_thread_blocked, id=29499, stack(0x00007f95fe3e0000,0x00007f95fe4e1000)]
  0x00007f95bc009800 JavaThread "netty-messaging-event-epoll-client-1" daemon [_thread_in_native, id=29502, stack(0x00007f95fcbd9000,0x00007f95fccda000)]
  0x00007f94fc00b000 JavaThread "netty-messaging-timeout-1" daemon [_thread_blocked, id=29506, stack(0x00007f95fc4d2000,0x00007f95fc5d3000)]
  0x00007f9608931000 JavaThread "netty-messaging-event-epoll-client-2" daemon [_thread_in_native, id=29509, stack(0x00007f95fc0ce000,0x00007f95fc1cf000)]
  0x00007f95bc033800 JavaThread "netty-messaging-event-epoll-client-3" daemon [_thread_in_native, id=29511, stack(0x00007f9584dfb000,0x00007f9584efc000)]
  0x00007f9608932000 JavaThread "netty-messaging-event-epoll-client-4" daemon [_thread_in_native, id=29512, stack(0x00007f9584cfa000,0x00007f9584dfb000)]
  0x00007f946c001800 JavaThread "netty-messaging-timeout-2" daemon [_thread_blocked, id=29515, stack(0x00007f95848f6000,0x00007f95849f7000)]
  0x00007f95bc035000 JavaThread "netty-messaging-timeout-3" daemon [_thread_blocked, id=29517, stack(0x00007f95845f3000,0x00007f95846f4000)]
  0x00007f95a0018800 JavaThread "netty-messaging-event-epoll-client-5" daemon [_thread_in_native, id=29542, stack(0x00007f954ccfa000,0x00007f954cdfb000)]
  0x00007f9608933000 JavaThread "netty-messaging-event-epoll-client-6" daemon [_thread_in_native, id=29546, stack(0x00007f954cbf9000,0x00007f954ccfa000)]
  0x00007f95a0019800 JavaThread "netty-messaging-event-epoll-client-7" daemon [_thread_in_native, id=29577, stack(0x00007f954c8f6000,0x00007f954c9f7000)]
  0x00007f9608933800 JavaThread "netty-messaging-event-epoll-client-8" daemon [_thread_in_native, id=29581, stack(0x00007f95ff3f0000,0x00007f95ff4f1000)]
  0x00007f95a021b800 JavaThread "netty-messaging-event-epoll-client-9" daemon [_thread_in_native, id=29590, stack(0x00007f95428f8000,0x00007f95429f9000)]
  0x00007f9608943800 JavaThread "netty-messaging-event-epoll-client-10" daemon [_thread_in_native, id=29596, stack(0x00007f95402f7000,0x00007f95403f8000)]
  0x00007f95a021c800 JavaThread "netty-messaging-event-epoll-client-11" daemon [_thread_in_native, id=29597, stack(0x00007f952cefc000,0x00007f952cffd000)]
  0x00007f9608944800 JavaThread "netty-messaging-event-epoll-client-12" daemon [_thread_in_native, id=29600, stack(0x00007f952c7f5000,0x00007f952c8f6000)]
  0x00007f95a021e000 JavaThread "netty-messaging-event-epoll-client-13" daemon [_thread_in_native, id=29605, stack(0x00007f952c5f3000,0x00007f952c6f4000)]
  0x00007f95a021f000 JavaThread "netty-messaging-event-epoll-client-14" daemon [_thread_in_native, id=29610, stack(0x00007f952c2f0000,0x00007f952c3f1000)]
  0x00007f9608945000 JavaThread "netty-messaging-event-epoll-client-15" daemon [_thread_in_native, id=29611, stack(0x00007f9524efc000,0x00007f9524ffd000)]
  0x00007f956c03a800 JavaThread "Broker-1-zb-actors-0" daemon [_thread_in_native, id=31025, stack(0x00007f9700609000,0x00007f970070a000)]
  0x00007f956c04f000 JavaThread "Broker-1-zb-actors-1" daemon [_thread_in_vm, id=31026, stack(0x00007f9700005000,0x00007f9700106000)]
  0x00007f956c1c5800 JavaThread "Broker-1-zb-fs-workers-0" daemon [_thread_blocked, id=31028, stack(0x00007f9685ab2000,0x00007f9685bb3000)]
=>0x00007f956c1e9800 JavaThread "Broker-1-zb-fs-workers-1" daemon [_thread_in_native, id=31029, stack(0x00007f96857af000,0x00007f96858b0000)]
  0x00007f956c1ea800 JavaThread "atomix-cluster-0" daemon [_thread_blocked, id=31030, stack(0x00007f96853ab000,0x00007f96854ac000)]
  0x00007f956c1ec000 JavaThread "atomix-0" daemon [_thread_blocked, id=31031, stack(0x00007f9684da5000,0x00007f9684ea6000)]
  0x00007f956c36d800 JavaThread "netty-messaging-event-epoll-server-0" daemon [_thread_in_native, id=31032, stack(0x00007f9684ba3000,0x00007f9684ca4000)]
  0x00007f956c4ee800 JavaThread "netty-messaging-event-epoll-server-0" daemon [_thread_in_native, id=31033, stack(0x00007f96848a0000,0x00007f96849a1000)]
  0x00007f9514001000 JavaThread "netty-unicast-event-nio-client-0" daemon [_thread_in_native, id=31039, stack(0x00007f95ff1ee000,0x00007f95ff2ef000)]
  0x00007f9514033800 JavaThread "atomix-cluster-events" daemon [_thread_blocked, id=31040, stack(0x00007f95ff0ed000,0x00007f95ff1ee000)]
  0x00007f9514035000 JavaThread "atomix-cluster-heartbeat-sender" daemon [_thread_blocked, id=31041, stack(0x00007f95fefec000,0x00007f95ff0ed000)]
  0x00007f9514036800 JavaThread "atomix-cluster-event-executor-0" daemon [_thread_blocked, id=31042, stack(0x00007f95feae7000,0x00007f95febe8000)]
  0x00007f9348002000 JavaThread "raft-server-1-raft-partition-partition-1" daemon [_thread_blocked, id=31044, stack(0x00007f95fe8e5000,0x00007f95fe9e6000)]
  0x00007f9348003000 JavaThread "raft-server-1-raft-partition-partition-1-load" daemon [_thread_blocked, id=31046, stack(0x00007f95fe2df000,0x00007f95fe3e0000)]
  0x00007f9348004800 JavaThread "raft-server-1-raft-partition-partition-1-state" daemon [_thread_blocked, id=31050, stack(0x00007f95fdfde000,0x00007f95fe0df000)]
  0x00007f94ac003000 JavaThread "netty-messaging-event-epoll-client-0" daemon [_thread_in_native, id=31072, stack(0x00007f95fcedc000,0x00007f95fcfdd000)]
  0x00007f9440001000 JavaThread "netty-messaging-timeout-0" daemon [_thread_blocked, id=31073, stack(0x00007f95fccda000,0x00007f95fcddb000)]
  0x00007f944c002800 JavaThread "netty-messaging-event-epoll-client-1" daemon [_thread_in_native, id=31077, stack(0x00007f95fc5d3000,0x00007f95fc6d4000)]
  0x00007f9648001000 JavaThread "netty-messaging-timeout-1" daemon [_thread_blocked, id=31078, stack(0x00007f95fc2d0000,0x00007f95fc3d1000)]
  0x00007f94ac004800 JavaThread "netty-messaging-event-epoll-client-2" daemon [_thread_in_native, id=31105, stack(0x00007f9584efc000,0x00007f9584ffd000)]
  0x00007f93e0404000 JavaThread "netty-messaging-timeout-2" daemon [_thread_blocked, id=31107, stack(0x00007f9584bf9000,0x00007f9584cfa000)]
  0x00007f965400d000 JavaThread "netty-messaging-event-epoll-client-3" daemon [_thread_in_native, id=31108, stack(0x00007f95844f2000,0x00007f95845f3000)]
  0x00007f965401d000 JavaThread "netty-messaging-event-epoll-client-4" daemon [_thread_in_native, id=31138, stack(0x00007f954cefc000,0x00007f954cffd000)]
  0x00007f965400b000 JavaThread "netty-messaging-event-epoll-client-5" daemon [_thread_in_native, id=31139, stack(0x00007f952caf8000,0x00007f952cbf9000)]
  0x00007f94ac006000 JavaThread "netty-messaging-event-epoll-client-6" daemon [_thread_in_native, id=31145, stack(0x00007f954c3fa000,0x00007f954c4fb000)]
  0x00007f9508044000 JavaThread "netty-messaging-timeout-3" daemon [_thread_blocked, id=31147, stack(0x00007f954c2f9000,0x00007f954c3fa000)]
  0x00007f9654009800 JavaThread "netty-messaging-event-epoll-client-7" daemon [_thread_in_native, id=31166, stack(0x00007f9542afa000,0x00007f9542bfb000)]
  0x00007f94ac007000 JavaThread "netty-messaging-event-epoll-client-8" daemon [_thread_in_native, id=31170, stack(0x00007f954c4fb000,0x00007f954c5fc000)]
  0x00007f965401a000 JavaThread "netty-messaging-event-epoll-client-9" daemon [_thread_in_native, id=31184, stack(0x00007f95405fa000,0x00007f95406fb000)]
  0x00007f94ac008800 JavaThread "netty-messaging-event-epoll-client-10" daemon [_thread_in_native, id=31190, stack(0x00007f95406fb000,0x00007f95407fc000)]
  0x00007f94ac009800 JavaThread "netty-messaging-event-epoll-client-12" daemon [_thread_in_native, id=31212, stack(0x00007f954c1f8000,0x00007f954c2f9000)]
  0x00007f965401b000 JavaThread "netty-messaging-event-epoll-client-11" daemon [_thread_in_native, id=31213, stack(0x00007f94767dc000,0x00007f94768dd000)]
  0x00007f94ac00a800 JavaThread "netty-messaging-event-epoll-client-13" daemon [_thread_in_native, id=31215, stack(0x00007f94764ec000,0x00007f94765ed000)]
  0x00007f965401e000 JavaThread "netty-messaging-event-epoll-client-14" daemon [_thread_in_native, id=31217, stack(0x00007f94763eb000,0x00007f94764ec000)]
  0x00007f94ac00c000 JavaThread "netty-messaging-event-epoll-client-15" daemon [_thread_in_native, id=31218, stack(0x00007f94762ea000,0x00007f94763eb000)]
  0x00007f948c002800 JavaThread "globalEventExecutor-2-112" [_thread_blocked, id=31993, stack(0x00007f94746de000,0x00007f94747df000)]

Other Threads:
  0x00007f97342b5800 VMThread "VM Thread" [stack: 0x00007f97102ec000,0x00007f97103ec000] [id=4307]
  0x00007f9734314800 WatcherThread [stack: 0x00007f9703088000,0x00007f9703188000] [id=4338]
  0x00007f9734027800 GCTaskThread "GC Thread#0" [stack: 0x00007f971c4a2000,0x00007f971c5a2000] [id=4274]
  0x00007f96f8001000 GCTaskThread "GC Thread#1" [stack: 0x00007f9702450000,0x00007f9702550000] [id=4424]
  0x00007f96f8002800 GCTaskThread "GC Thread#2" [stack: 0x00007f970234e000,0x00007f970244e000] [id=4429]
  0x00007f96f8004000 GCTaskThread "GC Thread#3" [stack: 0x00007f970224c000,0x00007f970234c000] [id=4430]
  0x00007f96f8005800 GCTaskThread "GC Thread#4" [stack: 0x00007f970214a000,0x00007f970224a000] [id=4436]
  0x00007f96f8007000 GCTaskThread "GC Thread#5" [stack: 0x00007f9702048000,0x00007f9702148000] [id=4437]
  0x00007f96f8008800 GCTaskThread "GC Thread#6" [stack: 0x00007f9701f46000,0x00007f9702046000] [id=4441]
  0x00007f96f800a800 GCTaskThread "GC Thread#7" [stack: 0x00007f9701e44000,0x00007f9701f44000] [id=4442]
  0x00007f973405a800 ConcurrentGCThread "G1 Main Marker" [stack: 0x00007f9712efc000,0x00007f9712ffc000] [id=4277]
  0x00007f973405c800 ConcurrentGCThread "G1 Conc#0" [stack: 0x00007f9712dfa000,0x00007f9712efa000] [id=4283]
  0x00007f970c001000 ConcurrentGCThread "G1 Conc#1" [stack: 0x00007f9700d11000,0x00007f9700e11000] [id=4808]
  0x00007f9734225000 ConcurrentGCThread "G1 Refine#0" [stack: 0x00007f97104f0000,0x00007f97105f0000] [id=4293]
  0x00007f9708001000 ConcurrentGCThread "G1 Refine#1" [stack: 0x00007f95fff00000,0x00007f9600000000] [id=9417]
  0x00007f95f8001000 ConcurrentGCThread "G1 Refine#2" [stack: 0x00007f95ffdfe000,0x00007f95ffefe000] [id=9418]
  0x00007f95f0001000 ConcurrentGCThread "G1 Refine#3" [stack: 0x00007f95ffcfc000,0x00007f95ffdfc000] [id=9421]
  0x00007f95f4001000 ConcurrentGCThread "G1 Refine#4" [stack: 0x00007f95ffbfa000,0x00007f95ffcfa000] [id=9439]
  0x00007f95e8001000 ConcurrentGCThread "G1 Refine#5" [stack: 0x00007f95ffaf8000,0x00007f95ffbf8000] [id=9440]
  0x00007f95ec001000 ConcurrentGCThread "G1 Refine#6" [stack: 0x00007f95ff9f6000,0x00007f95ffaf6000] [id=9652]
  0x00007f9734227000 ConcurrentGCThread "G1 Young RemSet Sampling" [stack: 0x00007f97103ee000,0x00007f97104ee000] [id=4297]

Threads with active compile tasks:

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap address: 0x0000000080000000, size: 2048 MB, Compressed Oops mode: 32-bit
Narrow klass base: 0x0000000800000000, Narrow klass shift: 3
Compressed class space size: 1073741824 Address: 0x0000000840000000

Heap:
 garbage-first heap   total 1863680K, used 1079572K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 140 young (143360K), 40 survivors (40960K)
 Metaspace       used 83310K, capacity 86750K, committed 87040K, reserved 1124352K
  class space    used 10489K, capacity 11944K, committed 11980K, reserved 1048576K
Heap Regions: E=young(eden), S=young(survivor), O=old, HS=humongous(starts), HC=humongous(continues), CS=collection set, F=free, A=archive, TAMS=top-at-mark-start (previous, next)
|   0|0x0000000080000000, 0x0000000080100000, 0x0000000080100000|100%|HS|  |TAMS 0x0000000080100000, 0x0000000080000000| Complete 
|   1|0x0000000080100000, 0x0000000080200000, 0x0000000080200000|100%|HC|  |TAMS 0x0000000080200000, 0x0000000080100000| Complete 
... 

Card table byte_map: [0x00007f97173fc000,0x00007f97177fc000] _byte_map_base: 0x00007f9716ffc000

Marking Bits (Prev, Next): (CMBitMap*) 0x00007f9734051978, (CMBitMap*) 0x00007f97340519b0
 Prev Bits: [0x00007f9714ffc000, 0x00007f9716ffc000)
 Next Bits: [0x00007f9712ffc000, 0x00007f9714ffc000)

Polling page: 0x00007f973bb09000

Metaspace:

Usage:
  Non-class:     73.05 MB capacity,    71.11 MB ( 97%) used,     1.57 MB (  2%) free+waste,   372.12 KB ( <1%) overhead. 
      Class:     11.66 MB capacity,    10.24 MB ( 88%) used,     1.24 MB ( 11%) free+waste,   185.19 KB (  2%) overhead. 
       Both:     84.72 MB capacity,    81.36 MB ( 96%) used,     2.81 MB (  3%) free+waste,   557.31 KB ( <1%) overhead. 

Virtual space:
  Non-class space:       74.00 MB reserved,      73.30 MB (>99%) committed 
      Class space:        1.00 GB reserved,      11.70 MB (  1%) committed 
             Both:        1.07 GB reserved,      85.00 MB (  8%) committed 

Chunk freelists:
   Non-Class:  190.00 KB
       Class:  34.00 KB
        Both:  224.00 KB

CodeHeap 'non-profiled nmethods': size=120032Kb used=9096Kb max_used=9471Kb free=110935Kb
 bounds [0x00007f9724240000, 0x00007f9724b90000, 0x00007f972b778000]
CodeHeap 'profiled nmethods': size=120028Kb used=23174Kb max_used=26708Kb free=96853Kb
 bounds [0x00007f971cd09000, 0x00007f971e739000, 0x00007f9724240000]
CodeHeap 'non-nmethods': size=5700Kb used=2412Kb max_used=2460Kb free=3287Kb
 bounds [0x00007f971c778000, 0x00007f971c9e8000, 0x00007f971cd09000]
 total_blobs=18891 nmethods=11301 adapters=988
 compilation: enabled
              stopped_count=0, restarted_count=0
 full_count=0

Compilation events (10 events):
Event: 327.504 Thread 0x00007f97342c6000 13850       1       scala.collection.mutable.ListBuffer::first_$eq (6 bytes)
Event: 327.504 Thread 0x00007f97342c6000 nmethod 13850 0x00007f9724608990 code [0x00007f9724608b40, 0x00007f9724608cb0]
Event: 327.505 Thread 0x00007f97342c6000 13852       3       io.zeebe.msgpack.property.IntegerProperty::<init> (13 bytes)
Event: 327.505 Thread 0x00007f97342c6000 nmethod 13852 0x00007f971cf9e990 code [0x00007f971cf9eb80, 0x00007f971cf9ef88]
Event: 327.505 Thread 0x00007f97342c6000 13853       3       io.zeebe.protocol.impl.record.RecordMetadata::<init> (98 bytes)
Event: 327.506 Thread 0x00007f97342c6000 nmethod 13853 0x00007f971d046d90 code [0x00007f971d046fe0, 0x00007f971d047bc8]
Event: 327.507 Thread 0x00007f97342c6000 13854       3       io.zeebe.protocol.record.RecordMetadataEncoder::<init> (10 bytes)
Event: 327.507 Thread 0x00007f97342c6000 nmethod 13854 0x00007f971cfb6590 code [0x00007f971cfb6740, 0x00007f971cfb6970]
Event: 327.514 Thread 0x00007f97342c6000 13855       3       io.zeebe.broker.system.partitions.ZeebePartition$$Lambda$1402/0x0000000840b18840::<init> (26 bytes)
Event: 327.515 Thread 0x00007f97342c6000 nmethod 13855 0x00007f971cfcbb10 code [0x00007f971cfcbce0, 0x00007f971cfcc030]

GC Heap History (10 events):
Event: 285.765 GC heap before
{Heap before GC invocations=61 (full 0):
 garbage-first heap   total 1863680K, used 823808K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 72 young (73728K), 32 survivors (32768K)
 Metaspace       used 82564K, capacity 86010K, committed 86144K, reserved 1124352K
  class space    used 10425K, capacity 11851K, committed 11852K, reserved 1048576K
}
Event: 285.773 GC heap after
{Heap after GC invocations=62 (full 0):
 garbage-first heap   total 1863680K, used 730624K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 33 young (33792K), 33 survivors (33792K)
 Metaspace       used 82564K, capacity 86010K, committed 86144K, reserved 1124352K
  class space    used 10425K, capacity 11851K, committed 11852K, reserved 1048576K
}
Event: 286.553 GC heap before
{Heap before GC invocations=63 (full 0):
 garbage-first heap   total 1863680K, used 782848K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 40 young (40960K), 33 survivors (33792K)
 Metaspace       used 82567K, capacity 86010K, committed 86144K, reserved 1124352K
  class space    used 10425K, capacity 11851K, committed 11852K, reserved 1048576K
}
Event: 286.569 GC heap after
{Heap after GC invocations=64 (full 0):
 garbage-first heap   total 1863680K, used 754688K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 29 young (29696K), 29 survivors (29696K)
 Metaspace       used 82567K, capacity 86010K, committed 86144K, reserved 1124352K
  class space    used 10425K, capacity 11851K, committed 11852K, reserved 1048576K
}
Event: 300.314 GC heap before
{Heap before GC invocations=65 (full 0):
 garbage-first heap   total 1863680K, used 907264K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 108 young (110592K), 29 survivors (29696K)
 Metaspace       used 83271K, capacity 86733K, committed 86784K, reserved 1124352K
  class space    used 10507K, capacity 11978K, committed 11980K, reserved 1048576K
}
Event: 300.324 GC heap after
{Heap after GC invocations=66 (full 0):
 garbage-first heap   total 1863680K, used 744448K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 46 young (47104K), 46 survivors (47104K)
 Metaspace       used 83271K, capacity 86733K, committed 86784K, reserved 1124352K
  class space    used 10507K, capacity 11978K, committed 11980K, reserved 1048576K
}
Event: 302.504 GC heap before
{Heap before GC invocations=67 (full 0):
 garbage-first heap   total 1863680K, used 1508352K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 657 young (672768K), 46 survivors (47104K)
 Metaspace       used 83278K, capacity 86797K, committed 87040K, reserved 1124352K
  class space    used 10507K, capacity 11978K, committed 11980K, reserved 1048576K
}
Event: 302.513 GC heap after
{Heap after GC invocations=68 (full 0):
 garbage-first heap   total 1863680K, used 882964K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 36 young (36864K), 36 survivors (36864K)
 Metaspace       used 83278K, capacity 86797K, committed 87040K, reserved 1124352K
  class space    used 10507K, capacity 11978K, committed 11980K, reserved 1048576K
}
Event: 304.487 GC heap before
{Heap before GC invocations=68 (full 0):
 garbage-first heap   total 1863680K, used 1347860K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 491 young (502784K), 36 survivors (36864K)
 Metaspace       used 83278K, capacity 86797K, committed 87040K, reserved 1124352K
  class space    used 10507K, capacity 11978K, committed 11980K, reserved 1048576K
}
Event: 304.497 GC heap after
{Heap after GC invocations=69 (full 0):
 garbage-first heap   total 1863680K, used 887060K [0x0000000080000000, 0x0000000100000000)
  region size 1024K, 40 young (40960K), 40 survivors (40960K)
 Metaspace       used 83278K, capacity 86797K, committed 87040K, reserved 1124352K
  class space    used 10507K, capacity 11978K, committed 11980K, reserved 1048576K
}

Deoptimization events (10 events):
Event: 300.987 Thread 0x00007f9598002000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f9724b24684 method=java.util.concurrent.CompletableFuture.postComplete()V @ 42 c2
Event: 300.987 Thread 0x00007f95a8002800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f972473f9e0 method=java.util.concurrent.CompletableFuture.unipush(Ljava/util/concurrent/CompletableFuture$Completion;)V @ 34 c2
Event: 300.987 Thread 0x00007f95a8002800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f9724769ae4 method=java.util.concurrent.CompletableFuture.postFire(Ljava/util/concurrent/CompletableFuture;I)Ljava/util/concurrent/CompletableFuture; @ 25 c2
Event: 301.285 Thread 0x00007f93f428f800 Uncommon trap: reason=profile_predicate action=maybe_recompile pc=0x00007f9724b5c800 method=java.util.concurrent.ConcurrentHashMap$Traverser.advance()Ljava/util/concurrent/ConcurrentHashMap$Node; @ 15 c2
Event: 301.437 Thread 0x00007f93f428f800 Uncommon trap: reason=profile_predicate action=maybe_recompile pc=0x00007f9724b5c800 method=java.util.concurrent.ConcurrentHashMap$Traverser.advance()Ljava/util/concurrent/ConcurrentHashMap$Node; @ 15 c2
Event: 302.180 Thread 0x00007f93f428f800 Uncommon trap: reason=profile_predicate action=maybe_recompile pc=0x00007f9724b5c800 method=java.util.concurrent.ConcurrentHashMap$Traverser.advance()Ljava/util/concurrent/ConcurrentHashMap$Node; @ 15 c2
Event: 302.281 Thread 0x00007f93f428f800 Uncommon trap: reason=profile_predicate action=maybe_recompile pc=0x00007f9724b5c800 method=java.util.concurrent.ConcurrentHashMap$Traverser.advance()Ljava/util/concurrent/ConcurrentHashMap$Node; @ 15 c2
Event: 302.283 Thread 0x00007f93f428f800 Uncommon trap: reason=profile_predicate action=maybe_recompile pc=0x00007f9724b61c68 method=java.util.concurrent.ConcurrentHashMap$Traverser.advance()Ljava/util/concurrent/ConcurrentHashMap$Node; @ 15 c2
Event: 305.807 Thread 0x00007f9680124800 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00007f972488ed80 method=io.netty.handler.codec.ByteToMessageDecoder.callDecode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V @ 87 c2
Event: 327.514 Thread 0x00007f956c03a800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00007f9724add7a8 method=io.zeebe.util.sched.ActorFutureSubscription.triggersInPhase(Lio/zeebe/util/sched/ActorTask$ActorLifecyclePhase;)Z @ 16 c2

Classes redefined (0 events):
No events

Internal exceptions (10 events):
Event: 287.093 Thread 0x00007f9580027000 Exception <a 'java/lang/NoSuchMethodError'{0x00000000ef51f1f0}: java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/la
Event: 287.094 Thread 0x00007f9580027000 Exception <a 'java/lang/NoSuchMethodError'{0x00000000ef219908}: java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I> (0x00000000ef219908) thrown at [/build/o
Event: 301.285 Thread 0x00007f93f428f800 Implicit null exception at 0x00007f9724b59d2e to 0x00007f9724b5c7e2
Event: 301.437 Thread 0x00007f93f428f800 Implicit null exception at 0x00007f9724b59d2e to 0x00007f9724b5c7e2
Event: 302.180 Thread 0x00007f93f428f800 Implicit null exception at 0x00007f9724b59d2e to 0x00007f9724b5c7e2
Event: 302.281 Thread 0x00007f93f428f800 Implicit null exception at 0x00007f9724b59d2e to 0x00007f9724b5c7e2
Event: 302.283 Thread 0x00007f93f428f800 Implicit null exception at 0x00007f9724b5f7bc to 0x00007f9724b61c52
Event: 306.333 Thread 0x00007f9735ae4000 Exception <a 'java/net/UnknownHostException'{0x00000000f0dc4778}> (0x00000000f0dc4778) thrown at [/build/openjdk-11-1uPVZa/openjdk-11-11.0.3+1/src/hotspot/share/prims/jni.cpp, line 636]
Event: 312.676 Thread 0x00007f956c1c5800 Exception <a 'java/net/UnknownHostException'{0x00000000efb7ee88}> (0x00000000efb7ee88) thrown at [/build/openjdk-11-1uPVZa/openjdk-11-11.0.3+1/src/hotspot/share/prims/jni.cpp, line 636]
Event: 319.386 Thread 0x00007f956c1c7800 Exception <a 'java/net/UnknownHostException'{0x00000000ed38d798}> (0x00000000ed38d798) thrown at [/build/openjdk-11-1uPVZa/openjdk-11-11.0.3+1/src/hotspot/share/prims/jni.cpp, line 636]

Events (10 events):
Event: 327.367 Thread 0x00007f96180cd000 Thread exited: 0x00007f96180cd000
Event: 327.367 Thread 0x00007f96180cb800 Thread exited: 0x00007f96180cb800
Event: 327.367 Thread 0x00007f9538001000 Thread exited: 0x00007f9538001000
Event: 327.367 Thread 0x00007f96180c7800 Thread exited: 0x00007f96180c7800
Event: 327.367 Thread 0x00007f96180c8800 Thread exited: 0x00007f96180c8800
Event: 327.368 Thread 0x00007f96180ca800 Thread exited: 0x00007f96180ca800
Event: 327.368 Thread 0x00007f96180c9800 Thread exited: 0x00007f96180c9800
Event: 327.514 Thread 0x00007f956c03a800 Uncommon trap: trap_request=0xffffff4d fr.pc=0x00007f9724add7a8 relative=0x0000000000000088
Event: 327.514 Thread 0x00007f956c03a800 DEOPT PACKING pc=0x00007f9724add7a8 sp=0x00007f9700708840
Event: 327.514 Thread 0x00007f956c03a800 DEOPT UNPACKING pc=0x00007f971c7a0a25 sp=0x00007f97007087f0 mode 2


Dynamic libraries:
80000000-f1c00000 rw-p 00000000 00:00 0 
f1c00000-100000000 ---p 00000000 00:00 0 
800000000-800002000 rwxp 00001000 08:01 3792487                          /usr/lib/jvm/java-11-openjdk-amd64/lib/server/classes.jsa
800002000-8003be000 rw-p 00003000 08:01 3792487                          /usr/lib/jvm/java-11-openjdk-amd64/lib/server/classes.jsa
8003be000-800a9a000 r--p 003bf000 08:01 3792487                          /usr/lib/jvm/java-11-openjdk-amd64/lib/server/classes.jsa
800a9a000-800a9b000 rw-p 00a9b000 08:01 3792487                          /usr/lib/jvm/java-11-openjdk-amd64/lib/server/classes.jsa
800a9b000-8010b0000 r--p 00a9c000 08:01 3792487                          /usr/lib/jvm/java-11-openjdk-amd64/lib/server/classes.jsa
840000000-840bb3000 rw-p 00000000 00:00 0 
840bb3000-880000000 ---p 00000000 00:00 0 
55799889e000-55799889f000 r-xp 00000000 08:01 3792122                    /usr/lib/jvm/java-11-openjdk-amd64/bin/java
557998a9f000-557998aa0000 r--p 00001000 08:01 3792122                    /usr/lib/jvm/java-11-openjdk-amd64/bin/java
557998aa0000-557998aa1000 rw-p 00002000 08:01 3792122                    /usr/lib/jvm/java-11-openjdk-amd64/bin/java
55799a6ea000-55799a70b000 rw-p 00000000 00:00 0                          [heap]
7f92d37ff000-7f92d8000000 rw-p 00000000 00:00 0 
7f92d8000000-7f92d8021000 rw-p 00000000 00:00 0 
...

VM Arguments:
jvm_args: -XX:+UseContainerSupport -XX:MaxRAMFraction=8 -Xmx2048m -XX:MaxDirectMemorySize=4g 
java_command: /home/jenkins/agent/workspace/zeebe-io_zeebe_stable_0.24/qa/integration-tests/target/surefire/surefirebooter10423158930574598707.jar /home/jenkins/agent/workspace/zeebe-io_zeebe_stable_0.24/qa/integration-tests/target/surefire 2020-07-24T13-53-31_643-jvmRun5 surefire16185005548469433544tmp surefire_417551437800713479873tmp
java_class_path (initial): /home/jenkins/agent/workspace/zeebe-io_zeebe_stable_0.24/qa/integration-tests/target/surefire/surefirebooter10423158930574598707.jar
Launcher Type: SUN_STANDARD

[Global flags]
     intx CICompilerCount                          = 4                                         {product} {ergonomic}
     uint ConcGCThreads                            = 2                                         {product} {ergonomic}
     uint G1ConcRefinementThreads                  = 8                                         {product} {ergonomic}
   size_t G1HeapRegionSize                         = 1048576                                   {product} {ergonomic}
    uintx GCDrainStackTargetSize                   = 64                                        {product} {ergonomic}
   size_t InitialHeapSize                          = 536870912                                 {product} {ergonomic}
   size_t MarkStackSize                            = 4194304                                   {product} {ergonomic}
 uint64_t MaxDirectMemorySize                      = 4294967296                                {product} {command line}
   size_t MaxHeapSize                              = 2147483648                                {product} {command line}
   size_t MaxNewSize                               = 1287651328                                {product} {ergonomic}
    uintx MaxRAMFraction                           = 8                                         {product} {environment}
   size_t MinHeapDeltaBytes                        = 1048576                                   {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5835340                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122911450                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122911450                              {pd product} {ergonomic}
    uintx ReservedCodeCacheSize                    = 251658240                              {pd product} {ergonomic}
     bool SegmentedCodeCache                       = true                                      {product} {ergonomic}
     bool UseCompressedClassPointers               = true                                 {lp64_product} {ergonomic}
     bool UseCompressedOops                        = true                                 {lp64_product} {ergonomic}
     bool UseContainerSupport                      = true                                      {product} {environment}
     bool UseG1GC                                  = true                                      {product} {ergonomic}

Logging:
Log output configuration:
 #0: stdout all=warning uptime,level,tags
 #1: stderr all=off uptime,level,tags

Environment Variables:
JAVA_HOME=/docker-java-home
JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport
 -XX:MaxRAMFraction=8
CLASSPATH=
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Signal Handlers:
SIGSEGV: [libjvm.so+0xd8fdc0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGBUS: [libjvm.so+0xd8fdc0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGFPE: [libjvm.so+0xd8fdc0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGPIPE: [libjvm.so+0xb85910], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGXFSZ: [libjvm.so+0xb85910], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGILL: [libjvm.so+0xd8fdc0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGUSR2: [libjvm.so+0xb857b0], sa_mask[0]=00100000000000000000000000000000, sa_flags=SA_RESTART|SA_SIGINFO
SIGHUP: SIG_IGN, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGINT: SIG_IGN, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGTERM: [libjvm.so+0xb85b10], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGQUIT: [libjvm.so+0xb85b10], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO


---------------  S Y S T E M  ---------------

OS:PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
uname:Linux 4.19.109+ #1 SMP Mon Mar 16 06:27:01 PDT 2020 x86_64
libc:glibc 2.24 NPTL 2.24 
rlimit: STACK 8192k, CORE infinity, NPROC infinity, NOFILE 1048576, AS infinity, DATA infinity, FSIZE infinity
load average:20.49 23.70 12.04

/proc/meminfo:
MemTotal:       123772848 kB
MemFree:        79134724 kB
MemAvailable:   93796776 kB
Buffers:          521968 kB
Cached:         13927760 kB
SwapCached:            0 kB
Active:         30712336 kB
Inactive:       11324948 kB
Active(anon):   27563384 kB
Inactive(anon):      516 kB
Active(file):    3148952 kB
Inactive(file): 11324432 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:             36384 kB
Writeback:             0 kB
AnonPages:      27585592 kB
Mapped:           555316 kB
Shmem:              1520 kB
Slab:            1874536 kB
SReclaimable:    1367976 kB
SUnreclaim:       506560 kB
KernelStack:       46688 kB
PageTables:        83512 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    61886424 kB
Committed_AS:   37360128 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:            26624 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      933052 kB
DirectMap2M:    39960576 kB
DirectMap1G:    87031808 kB


/proc/sys/kernel/threads-max (system-wide limit on the number of threads):
966647


/proc/sys/vm/max_map_count (maximum number of memory map areas a process may have):
262144


/proc/sys/kernel/pid_max (system-wide limit on number of process identifiers):
4194304



container (cgroup) information:
container_type: cgroupv1
cpu_cpuset_cpus: 0-31
cpu_memory_nodes: 0
active_processor_count: 8
cpu_quota: 800000
cpu_period: 100000
cpu_shares: 8192
memory_limit_in_bytes: 34359738368
memory_and_swap_limit_in_bytes: 34359738368
memory_soft_limit_in_bytes: -1
memory_usage_in_bytes: 23385661440
memory_max_usage_in_bytes: 26110906368


CPU:total 32 (initial active 8) (16 cores per cpu, 2 threads per core) family 6 model 63 stepping 0, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, fma
CPU Model and flags from /proc/cpuinfo:
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities

Memory: 4k page, physical 33554432k(10716616k free), swap 0k(0k free)

vm_info: OpenJDK 64-Bit Server VM (11.0.3+1-Debian-1bpo91) for linux-amd64 JRE (11.0.3+1-Debian-1bpo91), built on Apr  1 2019 10:19:01 by "buildd" with gcc 6.3.0 20170516

END.
```

</p>
</details>

**Environment:**
 - OS: Zeebe CI
 - Zeebe Version: 0.24.2-SNAPSHOT
 - Configuration: [e.g. exporters etc.]

### PR DESCRIPTION
**Pull request by saig0**
## Description

I assume that the JVM crashed because the broker was closed while installing a new partition. 
When the `ZeebePartition` is closed then it calls `closePartition()` that closes every resource - one after each other using a `actor.onComple()` chain. But this doesn't interrupt the install process of a partition.

* using actor.close() to interrupt all running jobs (i.e. installing or closing the partition or a part of it)
* closing in the partition in action.onClosing() that blocks the close future until its done

Backport #5040 on `0.24`

## Related issues

closes #5066 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

**Comment by saig0** [comment]
It runs several times in the CI without a crash. Before, every second or third build fails. So, I assume that the problem is fixed now :sweat_smile:

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 1]
```diff
@@ -710,6 +663,57 @@ protected void handleFailure(final Exception failure) {
...
+    final var closeFuture = closingStep.getClosable().closeAsync();
+    closeFuture.onComplete(
+        (v, t) -> {
+          if (t == null) {
+            LOG.debug(
+                "Closing Zeebe-Partition-{}: {} closed successfully",
+                partitionId,
+                closingStep.getName());
+
+            // remove the completed step from the list in case that the closing is interrupted
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:700]: Ideally we should prevent that; in case of multiple role changes we do this due to waiting of the last transition. I think it makes sense to intorduce a closing flag which is toggled and nothing can be executed anymore, like transition. I think actor scheduler also supports something like that. That some jobs are only executed on starting right?

File: util/src/main/java/io/zeebe/util/sched/ActorExecutor.java [hunk 2]
```diff
@@ -70,6 +71,7 @@ public void start() {
   }
 
   public CompletableFuture<Void> closeAsync() {
+    Loggers.ACTOR_LOGGER.debug("Closing blocking task runner");
```
Comment (Zelldon) [inline util/src/main/java/io/zeebe/util/sched/ActorExecutor.java:74]: This is not the blocking task runner right?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 3]
```diff
@@ -610,39 +601,17 @@ private StreamProcessor createStreamProcessor(final ZeebeDb zeebeDb) {
...
   }
 
-  private void stepByStepClosing(
-      final CompletableActorFuture<Void> closingFuture, final List<AsyncClosable> actorsToClose) {
-    if (actorsToClose.isEmpty()) {
-      closingFuture.complete(null);
-      return;
-    }
-
-    final AsyncClosable asyncClosable = actorsToClose.remove(0);
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:620]: So actually we remove the closables already before I thought this was part of the fix?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 4]
```diff
@@ -710,6 +663,57 @@ protected void handleFailure(final Exception failure) {
...
+  }
+
+  private void stepByStepClosing(
+      final CompletableActorFuture<Void> closingFuture, final List<ClosingStep> actorsToClose) {
+    if (actorsToClose.isEmpty()) {
+      closingFuture.complete(null);
+      return;
+    }
+
+    final ClosingStep closingStep = actorsToClose.remove(0);
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:688]: We remove now twice from two different lists ? :sweat_smile:

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Thanks for taking a look at this and fixing it. I'm not 100% sure whether I get the real solution. So the only change was that we move the closing in the closing phase. But still we expect concurrency issues? Please answer my questions and comments below :)

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 5]
```diff
@@ -123,9 +123,9 @@ public ZeebePartition(
     this.typedRecordProcessorsFactory = typedRecordProcessorsFactory;
     this.commandApiService = commandApiService;
     this.partitionListeners = Collections.unmodifiableList(partitionListeners);
-    this.partitionId = atomixRaftPartition.id().id();
-    this.scheduler = actorScheduler;
-    this.maxFragmentSize = (int) brokerCfg.getNetwork().getMaxMessageSizeInBytes();
+    partitionId = atomixRaftPartition.id().id();
```
[the remark this answers is not in the document]
Comment (saig0) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:126]: This was my IDE. It removes all `this` if they're not necessary. We never talked about it yet. So, I can remove it.

[the remark this answers is not in the document]
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:126]: Agree, but maybe we need :D I would like to keep the `this` keyword, but we can discuss this in the team. For now I think it makes it harder to review if we change this. We probably need again a big PR where we remove all of it if we decide to do it.

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 6]
```diff
@@ -710,6 +663,57 @@ protected void handleFailure(final Exception failure) {
     onInstallFailure();
   }
 
+  private void addClosingStep(final String name, final AsyncClosable closable) {
+    closingSteps.add(new ClosingStep(name, closable));
+  }
+
+  private CompletableActorFuture<Void> closePartition() {
+    // this method may be called concurrently when the actor is closed
```
[the remark this answers is not in the document]
Comment (saig0) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:670]: I'm not sure how to prevent this situation. 

* first `closePartition()` is called by `transitionToLeader()`
* then `closePartition()` is called by `onActorClosing()`

What do you suggest in detail?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 1 above)
Comment (saig0) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:699]: When `actor.close()` is called then every scheduled job is canceled. That mean, if `closePartition()` is called first and `actor.close()` is called later then this interrupts the `closeFuture.onComplete()` chain in `stepByStepClosing()`. So, we need to continue with the closing of the partition.

What exactly do you suggest?

File: util/src/main/java/io/zeebe/util/sched/ActorExecutor.java (hunk 2 above)
Comment (saig0) [reply util/src/main/java/io/zeebe/util/sched/ActorExecutor.java:74]: Not? It is closing the task runner afterward `blockingTasksRunner.shutdown()`.

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 4 above)
Comment (saig0) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:687]: Yes. We remove the closed item from both lists.

File: util/src/main/java/io/zeebe/util/sched/ActorExecutor.java (hunk 2 above)
Comment (Zelldon) [reply util/src/main/java/io/zeebe/util/sched/ActorExecutor.java:74]: This was confusing since it is happening in the ActorExeuctor :sweat_smile:

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 1 above)
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:700]: OK the comments before sounded like it is a problem when we are do the actor closing that the next transition interrupt it?

> When actor.close() is called then every scheduled job is canceled.
But partition closing if scheduled will not be interrupted?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (saig0) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:671]: Ok. I'll extend the code comment :+1:

**Comment by saig0** [comment]
@Zelldon I tried to address all of your comment. Please have a look :)

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 7]
```diff
@@ -668,7 +668,10 @@ private void addClosingStep(final String name, final AsyncClosable closable) {
   }
 
   private CompletableActorFuture<Void> closePartition() {
-    // this method may be called concurrently when the actor is closed
+    // caution: this method may be called concurrently when the actor is closed
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:671]:
```suggestion
    // caution: this method may be called concurrently on role transition due to closing the actor
```

**Review by ChrisKujawa — APPROVED** [review]
thanks :+1:
