### PR TITLE
Fix exporter index creation failures (already-exists exceptions)

### LINKED ISSUE #25812: ElasticsearchException: [es/indices.create] failed: [resource_already_exists_exception] index [operate-sequence-flow-8.3.0_/mi8AWfmuQWqAM1k79lkdPg] already exists
**Describe the bug**

https://console.cloud.google.com/errors/detail/CMjsyJf_4uLtkAE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjvZQ&project=camunda-saas-int-chaos

https://console.cloud.google.com/errors/detail/COGAtdrpsfPDxgE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjvZQ&project=camunda-saas-int-chaos

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Stacktrace</summary>
<p>

<pre>
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/indices.create] failed: [resource_already_exists_exception] index [operate-sequence-flow-8.3.0_/mi8AWfmuQWqAM1k79lkdPg] already exists

at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse ( co/elastic.clients.transport/ElasticsearchTransportBase.java:345 )
at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest ( co/elastic.clients.transport/ElasticsearchTransportBase.java:147 )
at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.create ( co/elastic.clients.elasticsearch.indices/ElasticsearchIndicesClient.java:277 )
at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.createIndex ( io/camunda.exporter.schema.elasticsearch/ElasticsearchEngineClient.java:65 )
at io.camunda.exporter.schema.SchemaManager.lambda$initialiseIndexTemplates$3 ( io/camunda.exporter.schema/SchemaManager.java:127 )
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept
at java.util.stream.ReferencePipeline$2$1.accept
at java.util.Iterator.forEachRemaining
at java.util.Spliterators$IteratorSpliterator.forEachRemaining
at java.util.stream.AbstractPipeline.copyInto
at java.util.stream.AbstractPipeline.wrapAndCopyInto
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential
at java.util.stream.AbstractPipeline.evaluate
at java.util.stream.ReferencePipeline.forEach
at io.camunda.exporter.schema.SchemaManager.initialiseIndexTemplates ( io/camunda.exporter.schema/SchemaManager.java:118 )
at io.camunda.exporter.schema.SchemaManager.initialiseResources ( io/camunda.exporter.schema/SchemaManager.java:75 )
at io.camunda.exporter.schema.SchemaManager.startup ( io/camunda.exporter.schema/SchemaManager.java:51 )
at io.camunda.exporter.CamundaExporter.open ( io/camunda.exporter/CamundaExporter.java:117 )
at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$openExporter$0 ( io/camunda.zeebe.broker.exporter.stream/ExporterContainer.java:118 )
at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader ( io/camunda.zeebe.util.jar/ThreadContextUtil.java:59 )
at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader ( io/camunda.zeebe.util.jar/ThreadContextUtil.java:35 )
at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.openExporter ( io/camunda.zeebe.broker.exporter.stream/ExporterContainer.java:117 )
at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$startActiveExportingMode$16 ( io/camunda.zeebe.broker.exporter.stream/ExporterDirector.java:532 )
at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run ( io/camunda.zeebe.scheduler.retry/BackOffRetryStrategy.java:51 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:85 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:42 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:122 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 )
</pre>

</p>
</details> 

<details><summary>Stacktrace</summary>
<p>

<pre>
 co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/indices.create] failed: [resource_already_exists_exception] index [operate-sequence-flow-8.3.0_/mi8AWfmuQWqAM1k79lkdPg] already exists
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.create(ElasticsearchIndicesClient.java:277) ~[elasticsearch-java-8.13.4.jar:?]
	at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.createIndex(ElasticsearchEngineClient.java:65) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.lambda$initialiseIndexTemplates$3(SchemaManager.java:127) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.exporter.schema.SchemaManager.initialiseIndexTemplates(SchemaManager.java:118) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.initialiseResources(SchemaManager.java:75) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.startup(SchemaManager.java:51) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.CamundaExporter.open(CamundaExporter.java:117) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$openExporter$0(ExporterContainer.java:118) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:59) ~[zeebe-util-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:35) ~[zeebe-util-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.openExporter(ExporterContainer.java:117) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$startActiveExportingMode$16(ExporterDirector.java:532) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:85) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT] 
</pre>

</p>
</details> 

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

### LINKED ISSUE #25814: ElasticsearchExporterException: Index [import-position] was not created
**Describe the bug**

https://console.cloud.google.com/errors/detail/CLiyvYyS5uemigE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjvaQ&project=zeebe-io

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.exporter.exceptions.ElasticsearchExporterException: Index [import-position] was not created
	at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.createIndex(ElasticsearchEngineClient.java:74) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.lambda$initialiseIndices$1(SchemaManager.java:96) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.exporter.schema.SchemaManager.initialiseIndices(SchemaManager.java:93) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.initialiseResources(SchemaManager.java:74) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.startup(SchemaManager.java:51) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.CamundaExporter.open(CamundaExporter.java:124) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$openExporter$0(ExporterContainer.java:118) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:59) ~[zeebe-util-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:35) ~[zeebe-util-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.openExporter(ExporterContainer.java:117) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$startActiveExportingMode$16(ExporterDirector.java:532) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:83) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
Caused by: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/indices.create] failed: [resource_already_exists_exception] index [operate-import-position-8.3.0_/Gv7iU3PwSHmji3gx6cBb-A] already exists
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.create(ElasticsearchIndicesClient.java:277) ~[elasticsearch-java-8.13.4.jar:?]
	at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.createIndex(ElasticsearchEngineClient.java:68) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	... 27 more 
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Exporter failed and logged errors when starting in parallel with other partitions. All tried to created a schema. In general not a problem as failing caused retry and detected existing schema. But this causes noise and unnecessary error reports and red herings.

## PR 

 * Add new test to validate multiple exporter opens for multiple partitions
 * Add partition support on TestContext
 * Handle index creation for already exist exceptions

## Related issues

closes https://github.com/camunda/camunda/issues/25812
closes https://github.com/camunda/camunda/issues/25814

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java [hunk 1]
```diff
@@ -67,11 +67,27 @@ public void createIndex(final IndexDescriptor indexDescriptor, final IndexSettin
...
+    } catch (final ElasticsearchException elsEx) {
+      if ("resource_already_exists_exception".equals(elsEx.error().type())) {
+        // we can ignore already exists exceptions
+        // as this means the index was created by another exporter on a different partition
+        final var warnMsg =
+            String.format(
+                "Expected to create index [%s], but already exist. Will continue, likely was created by different partition (exporter).",
+                indexDescriptor.getFullQualifiedName());
+        LOG.debug(warnMsg, elsEx);
+        return;
```
Comment (ChrisKujawa) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java:84]: :thinking: or should we still fail to simply retry by the director, but just not log an error :thinking:

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java [hunk 2]
```diff
@@ -100,6 +101,35 @@ void beforeEach() {
...
+    final var p2Context = getContextFromConfig(config, 2);
+    p2Exporter.configure(p2Context);
+
+    // when
+    new Thread(
+            () -> {
+              final var p1ExporterController = new ExporterTestController();
+              p1Exporter.open(p1ExporterController);
+            })
+        .start();
```
Comment (npepinpe) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java:122]: :upside_down_face: 
```suggestion
    CompletableFuture.runAsync(() -> p1Exporter.open(new ExporterTestController()));
```

Comment (npepinpe) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java:122]: :question: If you don't join on the thread (or future with the suggestion), how do you guarantee that this runs before the code below, or even that you wait for the P1 exporter to be opened? I don't understand what we want to this in this case.

Comment (ChrisKujawa) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java:122]: The idea is to run in between and produce a more or less failing test

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java [hunk 3]
```diff
@@ -67,11 +67,27 @@ public void createIndex(final IndexDescriptor indexDescriptor, final IndexSettin
...
-    } catch (final IOException | ElasticsearchException e) {
+    } catch (final IOException ioe) {
       final var errMsg =
           String.format("Index [%s] was not created", indexDescriptor.getFullQualifiedName());
-      LOG.error(errMsg, e);
-      throw new ElasticsearchExporterException(errMsg, e);
+      LOG.error(errMsg, ioe);
+      throw new ElasticsearchExporterException(errMsg, ioe);
+    } catch (final ElasticsearchException elsEx) {
+      if ("resource_already_exists_exception".equals(elsEx.error().type())) {
```
[the remark this answers is not in the document]
Comment (ChrisKujawa) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/elasticsearch/ElasticsearchEngineClient.java:76]: Afaik there is nothing like that 😅

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java (hunk 2 above)
Comment (ChrisKujawa) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java:122]: The issue only happens on concurrent run

Comment (npepinpe) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java:122]: We're still not guaranteeing they run at the same time, but I'm also not sure how we can do this without more granular jobs I guess...

**Review by npepinpe — APPROVED** [review]
Unsure about the test as there's no guarantee it will run in parallel, but that's likely OK for now, as flakiness doesn't result in a failing test, and sometimes it will test the right thing I think.
