### PR TITLE
Reset last written position

### LINKED ISSUE #7218: Metrics reporting unusually high number of written records
**Describe the bug**

The Grafana dashboard is showing an unusually high number of written records (~3M compared to ~3K per minute). See screenshots.

This seems to coincide with the restart of broker `zeebe-2`, which at the time of the restart was leader for partition 2. Partitions 1 and 3 were lead by `zeebe-0`, which took over leadership of partition 2 after `zeebe-2` went down.

<details><summary>Screenshots</summary>
 <p>

## Larger timeframe
Shows high peaks in processing per partition panel. Also note that written normally is about 3K per minute per partition.
Screen Shot 2021-06-08 at 13 35 53

## Focussed timeframe
Shows unusually high numbers as written in the processing per partition panel.
Screen Shot 2021-06-08 at 13 36 13

</p>
</details>

**To Reproduce**

Unknown.

I've tried to reproduce it on the same benchmark by restarting pods individually, but without success.

**Expected behavior**

Failover should not lead to a report of additional written records

**Environment:**
 - Context: `gke_zeebe-io_europe-west1-b_zeebe-cluster`
 - Namespace: `medic-cw-23-f01b5bc83-benchmark`
 - Zeebe Version: f01b5bc83
 - Configuration: benchmark

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Previously the last written position was not reset on starting the processing state machine, which could cause weird metric exports, because the gap between lastWritten and newWritten position was to high (over million and more). The replay state machine now returns all positions and initialized the processing state machine with it.

## Related issues

closes #7218 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ProcessingStateMachine.java [hunk 1]
```diff
@@ -446,15 +446,21 @@ public boolean isMakingProgress() {
...
     // we need to seek to the next record after that position where the processing should start
     // Be aware on processing we ignore events, so we will process the next command
+    final var lastProcessedPosition = lastProcessingPositions.getLastProcessedPosition();
     logStreamReader.seekToNextEvent(lastProcessedPosition);
     if (lastSuccessfulProcessedEventPosition == StreamProcessor.UNSET_POSITION) {
       lastSuccessfulProcessedEventPosition = lastProcessedPosition;
     }
+
+    if (lastWrittenEventPosition == StreamProcessor.UNSET_POSITION) {
+      lastWrittenEventPosition = lastProcessingPositions.getLastWrittenPosition();
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ProcessingStateMachine.java:461]: 🔧  While we're at it, let's rename this field to what it actually is: `lastWrittenPosition` (it does not necessary only relate to events).

File: engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java [hunk 2]
```diff
@@ -230,11 +229,19 @@ private void replayEvent(final LoggedEvent currentEvent) {
...
-   * the last source event, which has caused the last applied event.
+   * the last processing positions.
    */
   private void onRecordsReplayed() {
-    LOG.info(LOG_STMT_REPLAY_FINISHED, lastReadRecordPosition);
-    recoveryFuture.complete(lastSourceEventPosition);
+    final var lastProcessingPositions =
+        new LastProcessingPositions(
+            // the last source pos. is the last processed command by the processing state machine
+            lastSourceEventPosition,
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java:238]: 🔧  This comment describes a what not a why. It can also be captured in code by extracting the value into a local variable called `lastProcessedPosition`. It is generally considered a best practice to restrict comment usage for the why-part only.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java [hunk 3]
```diff
@@ -230,11 +229,19 @@ private void replayEvent(final LoggedEvent currentEvent) {
...
+            // the last read position on replay, will be used as the last written for
+            // the processing state machine
+            lastReadRecordPosition);
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java:241]: ❓  Why does the lastReadRecordPosition match the last written position? Does the replay state machine read all the way to the end of the log? If so, please expand the comment to describe why it's possible to use it here.

**Review by korthout — CHANGES_REQUESTED** [review]
👍  Great work @Zelldon. I really like the introduction of the `LastProcessingPositions` class. 

I do have some comments that need to be addressed before merging. Please have a look.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ProcessingStateMachine.java (hunk 1 above)
Comment (Zelldon) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ProcessingStateMachine.java:461]: true

File: engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java (hunk 2 above)
Comment (Zelldon) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java:238]: Yeah well I see this here as worth to mention because I know that otherwise will stumble over it and think we might put here the wrong values and even if we have a variable it is not really visible.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java (hunk 3 above)
Comment (Zelldon) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java:241]: yes

File: engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java (hunk 2 above)
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java:238]: Perhaps you can extract it to a variable and add a comment explaining why this can work this way

**Comment by Zelldon** [comment]
Thanks for the review @korthout I followed your review hints, btw I don't think that these were blockers tbh. Especially if we check the emoji code https://devblogs.microsoft.com/appcenter/how-the-visual-studio-mobile-center-team-does-code-review/#introducing-the-emoji-code where it says 

> `:wrench:`: This is a well-meant suggestion. Take it or leave it.

But I found a blocker based on a failing test. I opened an issue for it https://github.com/camunda-cloud/zeebe/issues/8329
I tried to adjust the test, but had no success yet.

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java [hunk 4]
```diff
@@ -70,6 +70,14 @@ public void shouldDeleteCompactedSegmentsFilesAfterLeaderChange() throws IOExcep
...
             .getNodeId();
     clusteringRule.forceClusterToHaveNewLeader(followerId);
+    // because of https://github.com/camunda-cloud/zeebe/issues/8329
+    // we need to add another record so we can do a snapshot
+    clientRule
+        .getClient()
+        .newPublishMessageCommand()
+        .messageName("test")
+        .correlationKey("test")
+        .send();
```
Comment (Zelldon) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java:80]: This is just a workaround for now ideally we fix https://github.com/camunda-cloud/zeebe/issues/8329

**Comment by korthout** [comment]
>btw I don't think that these were blockers tbh

Sorry for the confusion. The blocker was the comment with the ❓. It was unclear to me whether the lastReadRecordPosition matched the last written position. If it wouldn't match, then the last written position would be wrongly accounted. This needed to be discussed before we could merge. 

I guess the ❓ symbol is not clearly a blocking comment, but it was for me. I'll make sure to address it better next time. Thanks for informing about it.

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java (hunk 4 above)
Comment (korthout) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java:80]: Please correct me if I'm wrong. #8329 exist as a problem as well without the changes in this PR, but this PR makes the impact of the problem larger. If that's the case, then perhaps we shouldn't merge this PR until we've fixed this bug. 

❓ Is this bug blocking this PR in your opinion?

Comment (Zelldon) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java:80]: You're right that it the change increases the impact, but still the likelihood is really low. This can only happen if no event is appended from outside or the processor doesn't process anything, otherwise it will update the commit position and then it is all fine. I think @npepinpe can decide here.

**Review by korthout — APPROVED** [review]
LGTM 👍 

Thanks for the changes. Let's wait until we have clarity on the #8329 before merging.

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java (hunk 4 above)
Comment (npepinpe) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ReaderCloseTest.java:80]: From #8329, it sounds to me like the impact is minimal? You won't be able to take snapshot if nothing is committed, but chances are if you're processing anything, some follow up event will be committed. If you're replaying, it just delays until the next entry is committed, which greatly lowers the potential impact: either nothing is committed (meaning nothing was replicated, meaning disk does not grow either), or something is and a snapshot can be taken. It would only affect the case where you're only exporting but nothing is to be processed, which is not very likely. I think we can go ahead and merge, unless I'm missing something.
