### PR TITLE
fix: configure `ResourceAccessController` beans regardless of having the gateway embedded

### LINKED ISSUE #38214: BatchOperation Initialization fails on test clusters as unable to find a matching `ResourceAccessController`
After resolving #38211, we started to see a new error on `8.8-SNAPSHOT` test clusters:

```
"type": "QUERY_FAILED",
"message": "Failed to initialize batch operation with end cursor: null. Reason: Failed to find a matching ResourceAccessController, make sure to set a security context using #withSecurityContext()"
```

We need to investigate and resolve the error as it blocks 8.8.

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description

Similar to #38211, In `production` environments for some customers, the gateway runs standalone in a separate deployment that can scale separately, and the broker runs without exposing an `embedded` gateway.

But we will still need the `ResourceAccessControllers` to be injected to the broker, to be able to authorize batch operation items queries in the client providers.

## Related issues

closes #38214

### CODE REVIEW

File: dist/src/main/java/io/camunda/application/commons/search/ResourceAccessControllerConfiguration.java [hunk 1]
```diff
@@ -22,12 +22,12 @@
...
 import io.camunda.security.reader.TenantAccessProvider;
 import io.camunda.spring.utils.ConditionalOnSecondaryStorageEnabled;
-import io.camunda.zeebe.gateway.rest.ConditionalOnRestGatewayEnabled;
+import org.springframework.boot.autoconfigure.condition.ConditionalOnWebApplication;
 import org.springframework.context.annotation.Bean;
 import org.springframework.context.annotation.Configuration;
 
 @Configuration(proxyBeanMethods = false)
-@ConditionalOnRestGatewayEnabled
+@ConditionalOnWebApplication
```
Comment (korthout) [inline dist/src/main/java/io/camunda/application/commons/search/ResourceAccessControllerConfiguration.java:30]: ❌ I don't understand how this change is related to problem.

>we will still need the ResourceAccessControllers to be injected to the broker, to be able to authorize batch operation items queries in the client providers.

So, I think what you really need is an OR check on either the RestGatewayEnabled, or the Broker profile is active, or both. That way, the code remains the same for the gateway, and you additionally configure it for the standalone broker.

File: dist/src/main/java/io/camunda/application/commons/security/AuthorizationCheckerConfiguration.java [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+import org.springframework.context.annotation.Bean;
+import org.springframework.context.annotation.Configuration;
+
+@Configuration(proxyBeanMethods = false)
+public class AuthorizationCheckerConfiguration {
+  @Bean
+  public AuthorizationChecker authorizationChecker(final AuthorizationReader authorizationReader) {
+    return new AuthorizationChecker(authorizationReader);
+  }
+}
```
Comment (korthout) [inline dist/src/main/java/io/camunda/application/commons/security/AuthorizationCheckerConfiguration.java:21]: 💭 I wonder whether we need this in ALL configurations, or just in a few. And can it hurt in some?

File: dist/src/main/java/io/camunda/application/commons/search/ResourceAccessControllerConfiguration.java (hunk 1 above)
Comment (mustafadagher) [reply dist/src/main/java/io/camunda/application/commons/search/ResourceAccessControllerConfiguration.java:30]: The change is exactly what we need to make this work.
if you check how `ConditionalOnRestGatewayEnabled` was implemented, I removed the part checking it being enabled, and kept the rest. so we make sure those beans are configured also if we don't have an embedded gateway.
You might be able to achieve the same with different ways, but I don't think this one is wrong
https://github.com/camunda/camunda/blob/31d02e5f2f736240643100c078253f8662805de9/zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/ConditionalOnRestGatewayEnabled.java#L26-L31

File: dist/src/main/java/io/camunda/application/commons/security/AuthorizationCheckerConfiguration.java (hunk 2 above)
Comment (mustafadagher) [reply dist/src/main/java/io/camunda/application/commons/security/AuthorizationCheckerConfiguration.java:21]: I assume we could also limit it in the same way as I did in `ResourceAccessControllerConfiguration`.

But in all cases, when we have no db configured, a `noop` reader will be injected to it, and it will simply do nothing. Even if somewhat called.

PS: The dependency between profiles and conditions as-is is quite complicated, and it took me quiet a lot of trials and test failures to understand what's needed where.

Comment (korthout) [reply dist/src/main/java/io/camunda/application/commons/security/AuthorizationCheckerConfiguration.java:21]: >PS: The dependency between profiles and conditions as-is is quite complicated, and it took me quiet a lot of trials and test failures to understand what's needed where.

💭 Yes, Spring magic complicates this. It's better to specify a single Bean method and use some logic to dynamically decide it than to provide all kinds of conditional configurations to maybe provide a bean.

File: dist/src/main/java/io/camunda/application/commons/search/ResourceAccessControllerConfiguration.java (hunk 1 above)
Comment (korthout) [reply dist/src/main/java/io/camunda/application/commons/search/ResourceAccessControllerConfiguration.java:30]: >You might be able to achieve the same with different ways, but I don't think this one is wrong

I just worry it's in too many situations now. By removing the conditional, it's effectively saying `if (true)`, but we're checking some undefined enum and I don't know if there are more options I'm not seeing. That's why I'm suggesting `if (A OR B)`. It's strictly better right, because we'd be sure we don't accidentally break something.

Comment (mustafadagher) [reply dist/src/main/java/io/camunda/application/commons/search/ResourceAccessControllerConfiguration.java:30]: I completely understand what you're saying, and I'm not objecting to it.

But let me explain it from a different perspective:
This series of changes started because we accidentally discovered that batch operations fail on saas-int clusters (while they worked perfectly locally and event I believe in dev).
Batch operations did not work initially because of missing the `search clients`, because of these condition limitations. When I fixed that, I was then faced with another missing bean (the `ResourceAccsessController`).

I don't want to be surprised again with failures due to missing beans. 
These beans are only used in certain cases when security is needed. They could be extra (not needed) sometimes, but I'd rather accept that, than not finding them when I need them.
I kept the limitation to not have them except for when the application is running as a web-app (then they won't be created in use cases where the application is acting as `backup manager` or `schema manager`), but I'm not comfortable with adding more limitations.

Effectively, the only thing I did is to release the limitation on having it `only and only if rest is enabled`.

**Review by korthout — APPROVED** [review]
Thanks for the added reasoning and discussion @mustafadagher 🚀 

LGTM 👍

**Comment by mustafadagher** [comment]
rebased to resolve conflicts
