### PR TITLE
Re-enable the update tests now that 8.7 is released

### LINKED ISSUE #27333: [After 8.7 Release] Enable Update Tests
With the release schedule being adjusted, there are currently two versions in development: 8.7 (on the `stable/8.7` branch) and 8.8 (on the `main` branch`). That means some of the Update Tests, i.e., `SnapshotTest` and `RollingUpdateTest`, are failing on `main`. They are failing because they are supposed to test the update path from a previous 8.7 release to 8.8, but currently, no 8.7 release exists.

- [x] Set `backwards.compat.version` to `8.7.0` ([ref](https://github.com/camunda/camunda/blob/66d694989dc03ad90c0540da1a0053b599b36228/parent/pom.xml#L231))
- [x] Enable `SnapshotTest` ([ref](https://github.com/camunda/camunda/blob/main/zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/SnapshotTest.java))
- [x] Enable `RollingUpdateTest` ([ref](https://github.com/camunda/camunda/blob/main/zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java))

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR re-enables the update tests now that 8.7 is released.

## Related issues

closes #27333

### CODE REVIEW

**Comment by npepinpe** [comment]
Looks like RollingUpdateTest is hanging forever :(

**Comment by npepinpe** [comment]
Tests pass :) https://github.com/camunda/camunda/actions/runs/16420693872/job/46398539841?pr=35626

So it looks like unrelated issues from flaky jobs :shrug:

**Comment by npepinpe** [comment]
@rodrigo-lourenco-lopes - this is a very small PR, do you think you'll have time to look at it? :)

File: zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java [hunk 1]
```diff
@@ -79,6 +80,11 @@ final class RollingUpdateTest {
           .withBrokersCount(3)
           .withPartitionsCount(1)
           .withReplicationFactor(3)
+          .withNodeConfig(
+              node ->
+                  node.withEnv(CREATE_SCHEMA_ENV_VAR, "false")
```
Comment (rodrigo-lourenco-lopes) [inline zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java:85]: ❓ These were added because security checks are now enabled by default, correct?

**Review by rodrigo-lourenco-lopes — APPROVED** [review]

File: zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java (hunk 1 above)
Comment (npepinpe) [reply zeebe/qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java:85]: And also creating the schema - but we don't have a DB here.

**Comment by npepinpe** [comment]
@rodrigo-lourenco-lopes - I rebased this morning but the tests still fail :(

https://github.com/camunda/camunda/actions/runs/16437620505/job/46450809417?pr=35626

**Comment by npepinpe** [comment]
@rodrigo-lourenco-lopes - we had to use 8.7.7 because of a known bug in 8.7.8 :(. See https://github.com/camunda/camunda/pull/35587
