### PR TITLE
fix: make the liquibase setup retryable for specific exception messages

### LINKED ISSUE #50230: MSSQL causes deadlocks in parallel E2E tests
In the `MultiDbTest` stage, the MSSQL stages often result in failing tests because of the following error:

```
Error:  Errors: 
Error:    DecisionAuthorizationIT ? BeanCreation Error creating bean with name 'rdbmsExporterLiquibase' defined in class path resource [io/camunda/application/commons/rdbms/MyBatisConfiguration.class]: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/rdbms-exporter/changesets/8.9.0.xml::create_authorizations_table::camunda:
     Reason: 
          db/changelog/rdbms-exporter/changelog-master.xml : liquibase.precondition.core.TableExistsPrecondition@44b98633 : An error occurred during the current command (Done status 0). Transaction (Process ID 54) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
```

The tests are executed in parallel and the newly introduced `TableExists` check causes deadlocks.

AC:
- the MSSQL setup should be stable and either not cause deadlocks or recover from them

### PR DESCRIPTION
**Pull request by stoerti**
Add a retry-loop around the Liquibase setup to be able to recover from deadlock exceptions.

## Related issues

closes #50230

### CODE REVIEW

File: db/rdbms/src/main/java/io/camunda/db/rdbms/LiquibaseSchemaManager.java [hunk 1]
```diff
@@ -32,18 +35,96 @@ public class LiquibaseSchemaManager extends MultiTenantSpringLiquibase
...
+  protected void waitBeforeRetry(final Duration retryBackoff) throws InterruptedException {
+    try {
+      Thread.sleep(retryBackoff.toMillis());
+    } catch (final InterruptedException e) {
+      Thread.currentThread().interrupt();
+      throw e;
+    }
+  }
+
+  private boolean isRetryableException(final Throwable throwable) {
```
Comment (p-wunderlich) [inline db/rdbms/src/main/java/io/camunda/db/rdbms/LiquibaseSchemaManager.java:111]: Hm currently this is just focused on deadlocks in MySQL, or? So either we should expand the identifiable errors which can cause a retry, or we rename it to "isDeadlock" ...

File: db/rdbms/src/main/java/io/camunda/db/rdbms/LiquibaseSchemaManager.java [hunk 2]
```diff
@@ -32,18 +35,96 @@ public class LiquibaseSchemaManager extends MultiTenantSpringLiquibase
...
+        return;
+      } catch (final Exception e) {
+        final boolean shouldRetry =
+            isRetryableException(e) && attempt < DEFAULT_MIGRATION_RETRY_ATTEMPTS;
+        if (!shouldRetry) {
+          throw e;
+        }
+
+        LOG.warn(
+            "Liquibase migration failed due to a transient deadlock (attempt {}/{}). Retrying in {}.",
```
Comment (p-wunderlich) [inline db/rdbms/src/main/java/io/camunda/db/rdbms/LiquibaseSchemaManager.java]: Here, too, the code focuses solely on deadlocks, but the names of the methods suggest that we’re generally checking whether an operation can be repeated. :D

**Review by p-wunderlich — CHANGES_REQUESTED** [review]

**Review by p-wunderlich — APPROVED** [review]
