### PR TITLE
Fix process version cache to prevent different proceses referencing the same version info

### LINKED ISSUE #14055: No executable process found while processing Deployment:Create command
**Describe the bug**

```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=DEPLOYMENT, intent=CREATE}, value={...}' without errors, but exception occurred with message 'Expected to find executable process in persisted process with key '2251799813685388', but after transformation no such executable process could be found.'.


java.util.NoSuchElementException: Expected to find executable process in persisted process with key '2251799813685388', but after transformation no such executable process could be found.
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lambda$updateInMemoryState$2(DbProcessState.java:231) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:228) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupProcessByIdAndPersistedVersion(DbProcessState.java:375) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getLatestProcessVersionByProcessId(DbProcessState.java:271) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.isLatestProcess(StartEventSubscriptionManager.java:64) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.tryReOpenStartEventSubscription(StartEventSubscriptionManager.java:55) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processDistributedCommand(DeploymentCreateProcessor.java:105) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:31) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:126) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:353) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]

```

The error is repeatedly occurring in partitions 2 and 3. But didn't see it in Partition 1. The error is logged every time, partition 1 retries to distribute the deployment. It looks like the deployment was created successfully in partition 1, but it cannot distributed it to partitions 2 and 3. So the users would assume the deployment was successful, but they cannot create instances on other partitions.

**To Reproduce**

Not sure. Further data for analysis is [here](https://drive.google.com/drive/folders/1g6HlGdY3RwJO1yd1zl3Ld3T7r_CJUxto)

**Expected behavior**

A deployment successfully created in partition 1 should be accepted by other partitions.

**Log/Stacktrace**

[Link to logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-08-29T12:56:18.601486031Z;endTime=2023-08-30T07:23:27.338991Z;pinnedLogId=2023-08-29T12:56:18.601486031Z%2Fenfqgfrxijsl5m8x;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%2225697942-1bb8-47f8-9c2e-2d7e6b348a75-zeebe%22%0Aresource.labels.location%3D%22australia-southeast1%22%0Aresource.labels.cluster_name%3D%22prod-worker-4%22%0Atimestamp%3D%222023-08-29T12:56:18.601486031Z%22%0AinsertId%3D%22enfqgfrxijsl5m8x%22;startTime=2023-08-25T12:33:36.208Z;summaryFields=resource%252Flabels%252Fpod_name,jsonPayload%252Fcontext%252FpartitionId:false:32:beginning?project=camunda-cloud-240911)

```

DEBUG 2023-08-29T12:56:18.012401245Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 1] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
DEBUG 2023-08-29T12:56:18.490833810Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
DEBUG 2023-08-29T12:56:18.492924797Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
DEBUG 2023-08-29T12:56:18.493531262Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
DEBUG 2023-08-29T12:56:18.493878660Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
ERROR 2023-08-29T12:56:18.601486031Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=DEPLOYMENT, intent=CREATE}, value={"resources":...}' without errors, but exception occurred with message 'Expected to find executable process in persisted process with key '2251799813685388', but after transformation no such executable process could be found.'.


```

**Environment:**
- Zeebe Version: 8.3.0-alpha4

Support
https://jira.camunda.com/browse/SUPPORT-24946

### LINKED ISSUE #14309: Cannot process record due to process deployed version being null.
**Describe the bug**

The issue seemed to happen while processing. The exporter could not process the record as the DeployedProcess.getVersion() returns null, because ProcessState.getLatestProcessVersionByProcessId()" is null. 

```
Expected to process record 
'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=DEPLOYMENT, intent=CREATE, authorization=UNKNOWN}, value={"resources":[],"processesMetadata":[{"bpmnProcessId":"Process_Connect_Intra","version":4,"processDefinitionKey":2251799813740831,"resourceName":"diagram_connect_intra.bpmn","checksum":"vE026arBq5Hh09ilkSj4Cw==","isDuplicate":false,"tenantId":"<default>"}],"decisionRequirementsMetadata":[],"decisionsMetadata":[],"tenantId":"<default>"}}' 
without errors, but exception occurred with message 
'Cannot invoke "io.camunda.zeebe.engine.state.deployment.DeployedProcess.getVersion()" 
because the return value of "io.camunda.zeebe.engine.state.immutable.ProcessState.getLatestProcessVersionByProcessId(org.agrona.DirectBuffer)" is null'.
```

**To Reproduce**

Dont know as of moment, the previous behavior in the [logs](https://console.cloud.google.com/logs/query%3Bquery=logName:%22stdout%22%0Aresource.type=%22k8s_container%22%0Aresource.labels.container_name=%22zeebe%22%0Aresource.labels.project_id=%22camunda-cloud-240911%22%0Aresource.labels.namespace_name=%22179a54e4-45b8-4850-8ff8-7caca6407a47-zeebe%22%0Aresource.labels.cluster_name=%22prod-worker-4%22%0Aresource.labels.location=%22australia-southeast1%22%0Aresource.labels.pod_name=%22zeebe-1%22%0A%3BpinnedLogId=2023-09-14T00:20:12.977565274Z/az5svd4vg7gfo3zz%3BcursorTimestamp=2023-09-14T00:21:43.373199577Z%3BstartTime=2023-09-13T23:50:42.977Z%3BendTime=2023-09-14T00:50:42.977Z?project=camunda-cloud-240911) seems normal at first glance.

**Log/Stacktrace**

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.deployment.DeployedProcess.getVersion()" because the return value of "io.camunda.zeebe.engine.state.immutable.ProcessState.getLatestProcessVersionByProcessId(org.agrona.DirectBuffer)" is null
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.isLatestProcess(StartEventSubscriptionManager.java:68) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.tryReOpenStartEventSubscription(StartEventSubscriptionManager.java:58) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processDistributedCommand(DeploymentCreateProcessor.java:108) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:31) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:353) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
```

**Environment:**
- OS: 
- Zeebe Version: 8.3.0-alpha6
- Configuration:

### LINKED ISSUE #14366: Cancel command fails because process is null (NPE)
**Describe the bug**

Error group: https://console.cloud.google.com/errors/detail/CJLK28eniZi1JA;service=zeebe;time=P7D?project=camunda-cloud-240911 (occurred 12 times yesterday on alpha6)

The cancelation of a process fails because the process model can't be found or is not available and the processing then fails with a NPE.

**To Reproduce**

Cancel a process I guess? I'm not 100% sure how this could happen in the log we also don't see the reference key, unfortunately. 

I tried with zbctl to cancel negative or non-existing but it didn't worked

```
$ zbctl cancel instance "-1"
Error: unknown shorthand flag: '1' in -1
$ zbctl cancel instance "1" --insecure
Error: rpc error: code = Unavailable desc = Expected to execute command on partition 0, but either it does not exist, or the gateway is not yet aware of it
```

For me it looks like it has to be a real key otherwise it will not be forwarded from the gateway to the right partition and written to the log.
🤷🏼 

I tried to reproduce this on SaaS:

1. Created a cluster with alpha6
2. Deployed a simple model with a user task
3. Created an instance
4. Canceled the instance in operate
5. Cancelation was successful

Not sure how to reproduce this, but I think this is clearly a regression.

**Expected behavior**

We can cancel a process instance without issues.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
<pre>
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.deployment.DeployedProcess.getKey()" because "process" is null
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBufferedMessageStartEventBehavior.findNextMessageToCorrelate(BpmnBufferedMessageStartEventBehavior.java:95) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBufferedMessageStartEventBehavior.correlateNextBufferedMessage(BpmnBufferedMessageStartEventBehavior.java:76) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBufferedMessageStartEventBehavior.correlateMessage(BpmnBufferedMessageStartEventBehavior.java:66) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$getPostTransitionAction$10(ProcessProcessor.java:212) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$getPostTransitionAction$11(ProcessProcessor.java:210) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.transitionTo(ProcessProcessor.java:182) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:167) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:27) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.lambda$onElementTerminated$5(BpmnStateTransitionBehavior.java:424) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:474) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementTerminated(BpmnStateTransitionBehavior.java:419) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.lambda$onTerminate$10(JobWorkerTaskProcessor.java:97) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.onTerminate(JobWorkerTaskProcessor.java:86) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.onTerminate(JobWorkerTaskProcessor.java:25) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:153) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:92) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:89) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:353) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
"
</pre>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.3.0-alpha6
- Configuration:

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

t's an issue with the caching of process versions. There is a scenario in which different keys in the cache reference the same value object. Because of this versions of different processes can influence each other.

1. If we deploy a process we store it in the state using a shared object (nextVersion) (this name is still bad btw)
2. If get the version info we search in the cache. If we can't find it we get it from the state and store this in the cache.
3. Since getting it from the state wraps the values in the same object it means the entries in the cache all reference this same object. So if the object changes it changes for all entries.

We can fix it by making sure we copy the value from the state before storing it in the cache.

## Related issues

I am convinced that all these version related issues are resolved by this PR (thank @korthout for this list 🙇)

closes #14309 
closes #14366 
closes #14055 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
No back ports necessary as this bug is introduced in one the alphas.

File: engine/src/main/java/io/camunda/zeebe/engine/state/deployment/VersionManager.java [hunk 1]
```diff
@@ -160,4 +154,6 @@ public Optional<Integer> findResourceVersionBefore(
     idKey.wrapString(resourceId);
     return getVersionInfo().findVersionBefore(version);
   }
+
+  private record TenantIdAndProcessId(String tenantId, String processId) {}
```
Comment (nicpuppa) [inline engine/src/main/java/io/camunda/zeebe/engine/state/deployment/VersionManager.java:158]: ❌ As the `VersionManager` is used also by Forms, this record should be renamed

```suggestion
  private record TenantIdAndResourceId(String tenantId, String resourceId) {}
```

File: engine/src/test/java/io/camunda/zeebe/engine/state/deployment/ProcessStateTest.java [hunk 2]
```diff
@@ -216,6 +216,29 @@ public void shouldNotIncrementNextProcessVersionForDifferentProcessId() {
     assertThat(otherversion).isEqualTo(2L);
   }
 
+  @Test
+  // Regression test for https://github.com/camunda/zeebe/issues/14309#issuecomment-1731052065
+  public void shouldStoreVersionsInCacheSeparately() {
```
Comment (nicpuppa) [inline engine/src/test/java/io/camunda/zeebe/engine/state/deployment/ProcessStateTest.java:221]: ❤️

**Review by nicpuppa — CHANGES_REQUESTED** [review]
Hey @remcowesterhoud great work on find the cause of the bugs! 🚀 

I left some comments, please have a look 👀

File: engine/src/main/java/io/camunda/zeebe/engine/state/deployment/VersionManager.java (hunk 1 above)
Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/state/deployment/VersionManager.java]: Good catch 👍

**Comment by remcowesterhoud** [comment]
@nicpuppa I've applied your suggestions, please have another look.

**Review by nicpuppa — APPROVED** [review]
LGTM 💪 

bors merge
