### PR TITLE
fix: complete future with error when leadership change is cancelled

### LINKED ISSUE #10141: Error on retrieving write buffer from log stream
**Describe the bug**

On becoming a leader the LogStream seems to be closed and thrown an exception if the CommandAPI wants to create a new writer.

**To Reproduce**

Not 100% sure, but it looks like it is related to concurrent transitions, becoming leader and going into inactive.
In general, I can't see really an impact/effect, since the cluster was almost immediately deleted afterward.

metrics
metrics2

We see after the error happening also a lot of https://github.com/camunda/zeebe/issues/8606 might be related.

**Expected behavior**

No error, and handling the case more gracefully. 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Actor is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamWriter(LogStreamImpl.java:203) ~[zeebe-logstreams-8.1.0-alpha4.jar:8.1.0-alpha4]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamRecordWriter(LogStreamImpl.java:181) ~[zeebe-logstreams-8.1.0-alpha4.jar:8.1.0-alpha4]
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiServiceImpl.lambda$onBecomingLeader$3(CommandApiServiceImpl.java:112) ~[zeebe-broker-8.1.0-alpha4.jar:8.1.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:123) ~[zeebe-scheduler-8.1.0-alpha4.jar:8.1.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86) ~[zeebe-scheduler-8.1.0-alpha4.jar:8.1.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-alpha4.jar:8.1.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-alpha4.jar:8.1.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-alpha4.jar:8.1.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-alpha4.jar:8.1.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-alpha4.jar:8.1.0-alpha4]
```

</p>
</details>

Logs: https://drive.google.com/drive/u/0/folders/1DKM8gPL92xcdWeVZNfLQYWEdCHKGij4r

Error group: https://console.cloud.google.com/errors/detail/COaxsKTpuvHoOQ;service=zeebe;time=P7D?project=camunda-cloud-240911

**Environment:**
- OS: ultrachaos
- Zeebe Version: 8.1.0-alpha4
- Configuration: trial

### PR DESCRIPTION
**Pull request by entangled90**
## Description
While there a transition to a leader is cancelled, the logStream will be closed, throwing an exception when creating a Writer.

To avoid concurrency issues, the `CommandServiceApiImpl` is not a `PartitionListener` anymore, but it's a `PartitionTransitionStep`: this should avoid it as they would be executed serially.

## Related issues
closes #10141

### CODE REVIEW

**Review by deepthidevaki — COMMENTED** [review]
My preference would be to define a separate transition step instead of extending the interface of CommandApiService. Then we can add the following methods to the `CommandApiService` interface - `registerHandlers` and `removeHandlers`.

What do you think?

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImpl.java [hunk 1]
```diff
@@ -76,44 +74,27 @@ protected void onActorClosing() {
...
-  private ActorFuture<Void> removeLeaderHandlersAsync(final int partitionId) {
-    return actor.call(() -> removeLeaderHandlers(partitionId));
-  }
-
-  private void removeLeaderHandlers(final int partitionId) {
+  public ActorFuture<Void> unregisterHandlers(final int partitionId) {
     commandHandler.removePartition(partitionId);
     queryHandler.removePartition(partitionId);
     cleanLeadingPartition(partitionId);
+    return createCompletedFuture();
```
Comment (deepthidevaki) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/transport/commandapi/CommandApiServiceImpl.java:97]: :x: This method should be wrapped in `actor.call` or `actor.run` because it is modifying data local to this actor which are not thread-safe.

**Review by deepthidevaki — APPROVED** [review]
Thanks. Please fix my comment before merging. Another review is not necessary.

**Comment by deepthidevaki** [comment]
@entangled90 Since this is a bug fix, it would be good to backport this until 8.3.
