### PR TITLE
Split `ClusteredSnapshotTest`

### LINKED ISSUE #8669: ClusteredSnapshotTest.shouldKeepIndexAndTerm
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once
- Does it block your work? Failed on my PR
- Do we suspect that it is a real failure? Yes

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
[ERROR] Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 660.709 s <<< FAILURE! - in io.camunda.zeebe.it.clustering.ClusteredSnapshotTest

[2022-01-26T12:55:30.912Z] [ERROR] ClusteredSnapshotTest.shouldKeepIndexAndTerm  Time elapsed: 310.693 s  <<< ERROR!

[2022-01-26T12:55:30.912Z] java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: Shutdown failed in the following steps: [Partition Manager]. See suppressed exceptions for details.

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:761)

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)

[2022-01-26T12:55:30.912Z] 	at io.camunda.zeebe.broker.Broker.lambda$close$1(Broker.java:168)

[2022-01-26T12:55:30.912Z] 	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23)

[2022-01-26T12:55:30.912Z] 	at io.camunda.zeebe.broker.Broker.close(Broker.java:163)

[2022-01-26T12:55:30.912Z] 	at zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.stopBroker(ClusteringRule.java:653)

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[2022-01-26T12:55:30.912Z] 	at zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.restartCluster(ClusteringRule.java:528)

[2022-01-26T12:55:30.912Z] 	at zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.restartCluster(ClusteredSnapshotTest.java:282)

[2022-01-26T12:55:30.912Z] 	at zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.shouldKeepIndexAndTerm(ClusteredSnapshotTest.java:166)

[2022-01-26T12:55:30.912Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2022-01-26T12:55:30.912Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[2022-01-26T12:55:30.912Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2022-01-26T12:55:30.912Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

[2022-01-26T12:55:30.912Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

[2022-01-26T12:55:30.912Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

[2022-01-26T12:55:30.912Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

[2022-01-26T12:55:30.912Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)

[2022-01-26T12:55:30.912Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-01-26T12:55:30.912Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-01-26T12:55:30.912Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.Suite.runChild(Suite.java:27)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

[2022-01-26T12:55:30.913Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

[2022-01-26T12:55:30.913Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

[2022-01-26T12:55:30.913Z] 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)

[2022-01-26T12:55:30.913Z] 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)

[2022-01-26T12:55:30.913Z] 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:199)

[2022-01-26T12:55:30.913Z] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:193)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

[2022-01-26T12:55:30.913Z] Caused by: java.util.concurrent.ExecutionException: Shutdown failed in the following steps: [Partition Manager]. See suppressed exceptions for details.

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:141)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:108)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:21)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:196)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.broker.Broker.lambda$close$0(Broker.java:170)

[2022-01-26T12:55:30.913Z] 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)

[2022-01-26T12:55:30.913Z] 	... 66 more

[2022-01-26T12:55:30.913Z] Caused by: io.camunda.zeebe.util.startup.StartupProcessException: Shutdown failed in the following steps: [Partition Manager]. See suppressed exceptions for details.

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.startup.StartupProcess.aggregateExceptionsSynchronized(StartupProcess.java:282)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.startup.StartupProcess.completeShutdownFutureSynchronized(StartupProcess.java:265)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.startup.StartupProcess.proceedWithShutdownSynchronized(StartupProcess.java:230)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.startup.StartupProcess.lambda$proceedWithShutdownSynchronized$6(StartupProcess.java:250)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:82)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)

[2022-01-26T12:55:30.914Z] 	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

[2022-01-26T12:55:30.914Z] 	Suppressed: io.camunda.zeebe.util.startup.StartupProcessStepException: Bootstrap step Partition Manager failed

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.startup.StartupProcess.lambda$proceedWithShutdownSynchronized$6(StartupProcess.java:244)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33)

[2022-01-26T12:55:30.914Z] 		... 6 more

[2022-01-26T12:55:30.914Z] 	Caused by: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[2022-01-26T12:55:30.914Z] 	Caused by: java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.Actor.close(Actor.java:96)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.broker.partitioning.PartitionManagerImpl.stopPartition(PartitionManagerImpl.java:211)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.broker.partitioning.PartitionManagerImpl.lambda$stopPartitions$6(PartitionManagerImpl.java:203)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

[2022-01-26T12:55:30.914Z] 		... 6 more

[2022-01-26T12:55:30.914Z] 

[2022-01-26T12:55:30.914Z] [INFO] Running io.camunda.zeebe.it.clustering.ClusteredSnapshotTest

[2022-01-26T12:56:27.161Z] [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 56.547 s - in io.camunda.zeebe.it.clustering.ClusteredSnapshotTest

[2022-01-26T12:56:27.161Z] [INFO] 

[2022-01-26T12:56:27.161Z] [INFO] Results:

[2022-01-26T12:56:27.161Z] [INFO] 

[2022-01-26T12:56:27.161Z] [WARNING] Flakes: 

[2022-01-26T12:56:27.161Z] [WARNING] ClusteredSnapshotTest.shouldKeepIndexAndTerm

[2022-01-26T12:56:27.161Z] [INFO]   Run 1: PASS

[2022-01-26T12:56:27.161Z] [ERROR]   Run 2: java.util.concurrent.ExecutionException: Shutdown failed in the following steps: [Partition Manager]. See suppressed exceptions for details.

[2022-01-26T12:56:27.161Z] [INFO]   Run 3: PASS

[2022-01-26T12:56:27.161Z] [INFO] 

[2022-01-26T12:56:27.161Z] [INFO] 
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

IDK

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

Unfortunately the logs can't be read.

```
Stacktrace
Failed to read test report file /home/jenkins/agent/workspace/be_zell-8644-flaky-exporter-test/qa/integration-tests/target/failsafe-reports/TEST-io.camunda.zeebe.it.clustering.ClusteredSnapshotTest-it-testrun.xml
org.dom4j.DocumentException: Error on line 193 of document  : XML document structures must start and end within the same entity.
	at org.dom4j.io.SAXReader.read(SAXReader.java:511)
	at org.dom4j.io.SAXReader.read(SAXReader.java:392)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:177)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:378)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:308)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:224)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:196)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:151)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:146)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3329)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:122)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; lineNumber: 193; columnNumber: 28; XML document structures must start and end within the same entity.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.endEntity(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.endEntity(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanData(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.dom4j.io.SAXReader.read(SAXReader.java:494)
	... 18 more
```

### LINKED ISSUE #10484: Flaky ClusteredSnapshotTest.shouldNotTakeNewSnapshot
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Multiple times a day
- Does it block your work? No
- Do we suspect that it is a real failure? Possibly

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:    Run 2: Assertion condition defined as a io.camunda.zeebe.it.clustering.ClusteredSnapshotTest 
Expecting all elements of:
  [io.camunda.zeebe.broker.Broker@5af5f886,
    io.camunda.zeebe.broker.Broker@150f0793,
    io.camunda.zeebe.broker.Broker@60cbec7c]
to satisfy given requirements, but these elements did not:

io.camunda.zeebe.broker.Broker@5af5f886
error: 
expected: FileBasedSnapshotId{index=20, term=3, processedPosition=19, exporterPosition=9223372036854775807}
 but was: FileBasedSnapshotId{index=20, term=3, processedPosition=30, exporterPosition=0}

io.camunda.zeebe.broker.Broker@60cbec7c
error: 
expected: FileBasedSnapshotId{index=20, term=3, processedPosition=19, exporterPosition=9223372036854775807}
 but was: FileBasedSnapshotId{index=20, term=3, processedPosition=30, exporterPosition=0} within 1 minutes.
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.
https://github.com/camunda/zeebe/actions/runs/3125858740/jobs/5070854985

<details><summary>Logs</summary>
<pre>
2022-09-26T07:59:07.9956021Z [ERROR] ClusteredSnapshotTest.shouldNotTakeNewSnapshot  Time elapsed: 124.584 s  <<< ERROR!
2022-09-26T07:59:07.9956960Z org.awaitility.core.ConditionTimeoutException: 
2022-09-26T07:59:07.9957870Z Assertion condition defined as a io.camunda.zeebe.it.clustering.ClusteredSnapshotTest 
2022-09-26T07:59:07.9962766Z Expecting all elements of:
2022-09-26T07:59:07.9963598Z   [io.camunda.zeebe.broker.Broker@5af5f886,
2022-09-26T07:59:07.9964192Z     io.camunda.zeebe.broker.Broker@150f0793,
2022-09-26T07:59:07.9965147Z     io.camunda.zeebe.broker.Broker@60cbec7c]
2022-09-26T07:59:07.9966005Z to satisfy given requirements, but these elements did not:
2022-09-26T07:59:07.9966237Z 
2022-09-26T07:59:07.9969219Z io.camunda.zeebe.broker.Broker@5af5f886
2022-09-26T07:59:07.9969580Z error: 
2022-09-26T07:59:07.9970288Z expected: FileBasedSnapshotId{index=20, term=3, processedPosition=19, exporterPosition=9223372036854775807}
2022-09-26T07:59:07.9971234Z  but was: FileBasedSnapshotId{index=20, term=3, processedPosition=30, exporterPosition=0}
2022-09-26T07:59:07.9971498Z 
2022-09-26T07:59:07.9975119Z io.camunda.zeebe.broker.Broker@60cbec7c
2022-09-26T07:59:07.9976923Z error: 
2022-09-26T07:59:07.9979153Z expected: FileBasedSnapshotId{index=20, term=3, processedPosition=19, exporterPosition=9223372036854775807}
2022-09-26T07:59:07.9980307Z  but was: FileBasedSnapshotId{index=20, term=3, processedPosition=30, exporterPosition=0} within 1 minutes.
2022-09-26T07:59:07.9981256Z 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
2022-09-26T07:59:07.9982657Z 	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
2022-09-26T07:59:07.9983238Z 	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
2022-09-26T07:59:07.9983986Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
2022-09-26T07:59:07.9984761Z 	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
2022-09-26T07:59:07.9986043Z 	at io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.awaitUntilAsserted(ClusteredSnapshotTest.java:245)
2022-09-26T07:59:07.9987102Z 	at io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.shouldNotTakeNewSnapshot(ClusteredSnapshotTest.java:232)
2022-09-26T07:59:07.9987752Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-09-26T07:59:07.9988355Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-09-26T07:59:07.9989039Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-09-26T07:59:07.9989561Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-09-26T07:59:07.9990016Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-09-26T07:59:07.9990549Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-09-26T07:59:07.9991113Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-09-26T07:59:07.9991665Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-09-26T07:59:07.9992186Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-09-26T07:59:07.9992646Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-09-26T07:59:07.9993060Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2022-09-26T07:59:07.9993496Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2022-09-26T07:59:07.9993924Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2022-09-26T07:59:07.9994350Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-09-26T07:59:07.9994851Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2022-09-26T07:59:07.9995494Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2022-09-26T07:59:07.9995986Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2022-09-26T07:59:07.9996516Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2022-09-26T07:59:07.9997395Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2022-09-26T07:59:07.9997788Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2022-09-26T07:59:07.9998223Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2022-09-26T07:59:07.9998701Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2022-09-26T07:59:07.9999237Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2022-09-26T07:59:07.9999639Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2022-09-26T07:59:08.0000015Z 	at org.junit.runners.Suite.runChild(Suite.java:128)
2022-09-26T07:59:08.0000366Z 	at org.junit.runners.Suite.runChild(Suite.java:27)
2022-09-26T07:59:08.0000749Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2022-09-26T07:59:08.0001148Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2022-09-26T07:59:08.0001576Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2022-09-26T07:59:08.0001995Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2022-09-26T07:59:08.0002546Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2022-09-26T07:59:08.0002990Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-09-26T07:59:08.0003403Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2022-09-26T07:59:08.0003971Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
2022-09-26T07:59:08.0004347Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
2022-09-26T07:59:08.0004821Z 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
2022-09-26T07:59:08.0005624Z 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
2022-09-26T07:59:08.0006209Z 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
2022-09-26T07:59:08.0006852Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
2022-09-26T07:59:08.0007753Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
2022-09-26T07:59:08.0008524Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
2022-09-26T07:59:08.0009248Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
2022-09-26T07:59:08.0010062Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
2022-09-26T07:59:08.0010859Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
2022-09-26T07:59:08.0011491Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
2022-09-26T07:59:08.0012070Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
2022-09-26T07:59:08.0012720Z 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
2022-09-26T07:59:08.0013512Z 	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
2022-09-26T07:59:08.0014220Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:234)
2022-09-26T07:59:08.0014811Z 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
2022-09-26T07:59:08.0015631Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:228)
2022-09-26T07:59:08.0016416Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
2022-09-26T07:59:08.0017179Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:131)
2022-09-26T07:59:08.0017839Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
2022-09-26T07:59:08.0018779Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
2022-09-26T07:59:08.0019334Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
2022-09-26T07:59:08.0019867Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
2022-09-26T07:59:08.0020270Z Caused by: java.lang.AssertionError: 
2022-09-26T07:59:08.0020639Z Expecting all elements of:
2022-09-26T07:59:08.0020962Z   [io.camunda.zeebe.broker.Broker@5af5f886,
2022-09-26T07:59:08.0021338Z     io.camunda.zeebe.broker.Broker@150f0793,
2022-09-26T07:59:08.0021707Z     io.camunda.zeebe.broker.Broker@60cbec7c]
2022-09-26T07:59:08.0022034Z to satisfy given requirements, but these elements did not:
2022-09-26T07:59:08.0022229Z 
2022-09-26T07:59:08.0022377Z io.camunda.zeebe.broker.Broker@5af5f886
2022-09-26T07:59:08.0022639Z error: 
2022-09-26T07:59:08.0023012Z expected: FileBasedSnapshotId{index=20, term=3, processedPosition=19, exporterPosition=9223372036854775807}
2022-09-26T07:59:08.0023520Z  but was: FileBasedSnapshotId{index=20, term=3, processedPosition=30, exporterPosition=0}
2022-09-26T07:59:08.0023759Z 
2022-09-26T07:59:08.0023911Z io.camunda.zeebe.broker.Broker@60cbec7c
2022-09-26T07:59:08.0024179Z error: 
2022-09-26T07:59:08.0024542Z expected: FileBasedSnapshotId{index=20, term=3, processedPosition=19, exporterPosition=9223372036854775807}
2022-09-26T07:59:08.0025043Z  but was: FileBasedSnapshotId{index=20, term=3, processedPosition=30, exporterPosition=0}
2022-09-26T07:59:08.0025838Z 	at io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.lambda$awaitUntilAsserted$11(ClusteredSnapshotTest.java:247)
2022-09-26T07:59:08.0026469Z 	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
2022-09-26T07:59:08.0026999Z 	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
2022-09-26T07:59:08.0027550Z 	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
2022-09-26T07:59:08.0028053Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-09-26T07:59:08.0028641Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-09-26T07:59:08.0029359Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-09-26T07:59:08.0029811Z 	at java.base/java.lang.Thread.run(Thread.java:833)
</pre>
</details>

### LINKED ISSUE #10560: ClusteredSnapshotTest.shouldSendSnapshotOnReconnect is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once
- Does it block your work? Yes bors ....
- Do we suspect that it is a real failure? IDK

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
rror:  Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 524.259 s <<< FAILURE! - in io.camunda.zeebe.it.clustering.ClusteredSnapshotTest
Error:  ClusteredSnapshotTest.shouldSendSnapshotOnReconnect  Time elapsed: 79.515 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with alias 'Expected snapshot at partition one on broker: 1 with previous snapshot: null' didn't complete within 1 minutes because io.camunda.zeebe.it.clustering.ClusteringRule expected the predicate to return <true> but it returned <false> for input of <Optional.empty>.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:691)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:708)
	at io.camunda.zeebe.it.clustering.ClusteringRule.waitForNewSnapshotAtBroker(ClusteringRule.java:812)
	at io.camunda.zeebe.it.clustering.ClusteringRule.waitForSnapshotAtBroker(ClusteringRule.java:765)
	at io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.shouldSendSnapshotOnReconnect(ClusteredSnapshotTest.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:234)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:228)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:131)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.txt](https://github.com/camunda/zeebe/files/9674174/io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.txt)
[io.camunda.zeebe.it.clustering.ClusteredSnapshotTest-output.txt](https://github.com/camunda/zeebe/files/9674175/io.camunda.zeebe.it.clustering.ClusteredSnapshotTest-output.txt)

### PR DESCRIPTION
**Pull request by lenaschoenburg**
`ClusteredSnapshotTest` is one of our longest running tests, running for roughly 6 minutes on GHA. Here we split this class into two, moving all tests related to exporting into `SnapshotWithExportersTest`. We also migrate `ClusteredSnapshotTest` to JUnit5.

`SnapshotWithExportersTest` work a bit differently than before but I think test coverage is the same:
* `shouldIncludeExportedPositionInSnapshot` tests that snapshots taken by a broker with a running exporter have the correct exporter position.
* `shouldTakeSnapshotWhenExporterPositionIsMinusOne` tests that snapshots taken by a broker with a non-functioning exporter can take snapshots
* `shouldNotTakeNewSnapshotWhenAddingNewExporter` tests that taking a new snapshot after adding an exporter will not trigger a new snapshot and instead reuse the previous one taken without any exporters.

The remaining `ClusteredSnapshotTest` are essentially untouched but I'd say this PR should close existing issues regarding flaky tests too as it is unclear if they were failing on GHA, and if they will fail again after this refactoring.

closes #10560
closes #10484
closes #8669

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteredSnapshotTest.java [hunk 1]
```diff
@@ -11,85 +11,68 @@
...
+  @RegisterExtension
+  private final ClusteringRuleExtension clusteringRule =
+      new ClusteringRuleExtension(1, 3, 3, this::configureBroker);
+
+  public static Stream<Arguments> snapshotTriggers() {
+    return Stream.of(
+        Arguments.of(
+            Named.of(
+                "explicit trigger snapshot",
+                (Consumer<ClusteringRule>)
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/ClusteredSnapshotTest.java:53]: :upside_down_face: I'd just make it a type itself - a type can implement `Named` as well, so e.g.

```java
private final record TestCase(String name, Consumer<ClusteringRule> snapshotTrigger) implements Named<Consumer<ClusteringRule>> {
  public Consumer<ClusteringRule> getPayload() {
    return snapshotTrigger;
  }

  public String getName() {
    return name;
  }
}

private static Stream<TestCase> snapshotTriggers() {
  return Stream.of(
    new TestCase("explicit", rule -> rule.triggerAndWaitForSnapshots()),
    new TestCase("implicit via clock", rule -> rule.getClock().addTime(SNAPSHOT_INTERVAL))
  );
}
```

I find it more readable, and more extensible in the future. But it's a very soft suggestion, as the impact is quite low :)

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/SnapshotWithExportersTest.java [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+
+        try (final var client =
+            ZeebeClient.newClientBuilder()
+                .gatewayAddress(zeebe.getExternalGatewayAddress())
+                .usePlaintext()
+                .build()) {
+
+          publishMessages(client);
+          final var exporterPosition =
+              Awaitility.await("Exported position is stable")
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/SnapshotWithExportersTest.java:48]: :thought_balloon: This isn't the first place we want to wait until the exporter has exported everything. I wonder if it might not be useful to add this to the partitions actuator, or some other actuator letting us introspect the current last exported positions :thinking:

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/SnapshotWithExportersTest.java [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+          final var exportedPositionInSnapshot =
+              Awaitility.await("Snapshot is taken")
+                  .atMost(Duration.ofSeconds(60))
+                  .during(Duration.ofSeconds(5))
+                  .until(
+                      () ->
+                          FileBasedSnapshotId.ofFileName(partitions.query().get(1).snapshotId())
+                              .orElseThrow()
+                              .getExportedPosition(),
+                      hasStableValue());
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/SnapshotWithExportersTest.java:67]: :question: I don't understand why we wait for the exporter position of the snapshot to stabilize. Can't we take snapshots in a controlled way? Maybe with a ridiculously high interval? So we essentially have a high interval, then trigger a snapshot, and when we have one expect the exporter position to be the expected position?

**Review by npepinpe — APPROVED** [review]
:+1: 

Looks great, no blockers, just a few minor comments :)

**Comment by npepinpe** [comment]
Ah and we should backport it if possible ofc

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/SnapshotWithExportersTest.java (hunk 3 above)
Comment (oleschoenburg) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/SnapshotWithExportersTest.java:67]: Oh yeah, that looks a bit confusing. I think at first this was just waiting for a snapshot to become available but then I merged extracting the exporter position in there and now it's misleading. 

> Can't we take snapshots in a controlled way? Maybe with a ridiculously high interval?

That's basically what we are doing already: snapshots are taken via the partitions actuator. The default snapshot interval should be high enough to not interfere with the tests here.
