### PR TITLE
Remove usage of Throwable#printStackTrace from production code

### LINKED ISSUE #4867: Log errors in actor scheduler
**Description**

The ActorScheduler still has a few places where the error is simply dumped via `Throwable#printStackTrace()`. This is for historical reasons, but now it's more painful as these errors are not aggregated to our error reporting tool since they don't go through any logger. 

To that end we should make sure all errors are logged via SLF4J so they end up properly formatted, labelled, etc., and we can better deal with them.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR removes usage of `Throwable#printStackTrace()` from our production code, notably in the actor scheduler, and replaces it with standard `org.slf4j.Logger#error`.

## Related issues

closes #4867 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Should be backported - will do so once this is merged :slightly_smiling_face:

File: util/src/main/java/io/zeebe/util/sched/ActorThread.java [hunk 1]
```diff
@@ -32,13 +32,16 @@
...
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 import org.slf4j.MDC;
 import sun.misc.Unsafe;
 
 @SuppressWarnings("restriction")
 public class ActorThread extends Thread implements Consumer<Runnable> {
   static final Unsafe UNSAFE = UnsafeAccess.UNSAFE;
   private static final long STATE_OFFSET;
+  private static final Logger LOG = LoggerFactory.getLogger(ActorThread.class);
```
Comment (saig0) [inline util/src/main/java/io/zeebe/util/sched/ActorThread.java:44]: Shouldn't we use the existing `ActorLogger`?
https://github.com/zeebe-io/zeebe/blob/develop/util/src/main/java/io/zeebe/util/Loggers.java#L16

File: dist/src/main/java/io/zeebe/broker/StandaloneBroker.java [hunk 2]
```diff
@@ -28,6 +31,7 @@
 @SpringBootApplication(exclude = ElasticsearchRestClientAutoConfiguration.class)
 @ComponentScan({"io.zeebe.broker", "io.zeebe.shared"})
 public class StandaloneBroker implements CommandLineRunner {
+  private static final Logger LOG = LoggerFactory.getLogger(StandaloneBroker.class);
```
Comment (saig0) [inline dist/src/main/java/io/zeebe/broker/StandaloneBroker.java:34]: Shouldn't we use the existing `SystemLogger`? https://github.com/zeebe-io/zeebe/blob/develop/broker/src/main/java/io/zeebe/broker/Loggers.java#L16

**Review by saig0 — COMMENTED** [review]
Thanks @npepinpe :cookie: 

Just a question about the logger.

File: util/src/main/java/io/zeebe/util/sched/ActorThread.java (hunk 1 above)
Comment (npepinpe) [reply util/src/main/java/io/zeebe/util/sched/ActorThread.java:44]: Yes; why I initially went with a per-class logger is because I think in the long run it makes sense for us to drop these broad loggers. If you want to get fine-grained trace logs, or debug, etc., if you want control over what you're seeing, having one logger used for a complete unit is counter productive as you may get too much logs. At the same time, having one logger per class is cheap, and you can still group things by packages...

However for this PR we probably should remain consistent, and moving away from module-level loggers or some such should be something we do in a separate PR.

File: dist/src/main/java/io/zeebe/broker/StandaloneBroker.java (hunk 2 above)
Comment (npepinpe) [reply dist/src/main/java/io/zeebe/broker/StandaloneBroker.java:34]: Should we? It's unclear to me what is referred to here by the system, to be honest. I think this kind of fits with the point I was trying to make above, but again, outside of scope for this PR, so let's go with that for now.

**Review by saig0 — APPROVED** [review]
:+1:

File: util/src/main/java/io/zeebe/util/sched/ActorThread.java (hunk 1 above)
Comment (saig0) [reply util/src/main/java/io/zeebe/util/sched/ActorThread.java]: I agree. Let's discuss/announce it in the team meeting first :)
