### PR TITLE
fix(broker): compact after exporters removed

### LINKED ISSUE #5105: Will not compact after exporters are removed
**Describe the bug**

Taking snapshot and compaction will not happen anymore after broker is reconfigured in way where no exporters are configured anymore.

**To Reproduce**

```java

  @Test
  public void shouldCompactWhenExporterHasBeenRemoved() {
    // given
    final Broker broker = clusteringRule.getBroker(0);
    ControllableExporter.updatePosition(true);
    fillSegments(broker, SEGMENT_COUNT);
    clusteringRule.getClock().addTime(SNAPSHOT_PERIOD);
    // create first snapshot with exporter positions
    final var firstSnapshot = clusteringRule.waitForSnapshotAtBroker(broker);

    // restart with no exporter
    final var brokerCfg = clusteringRule.getBrokerCfg(0);
    brokerCfg.setExporters(Map.of());
    clusteringRule.stopBroker(0);
    clusteringRule.startBroker(0);

    final var filledSegmentCount = SEGMENT_COUNT * 2;
    writeSegments(broker, filledSegmentCount);

    // when triggering new snapshot creation
    final var segmentsCount = getSegmentsCount(broker);
    clusteringRule.getClock().addTime(SNAPSHOT_PERIOD);
    final var secondSnapshot = clusteringRule.waitForSnapshotAtBroker(broker);

    // then
    assertThat(firstSnapshot).isNotEqualTo(secondSnapshot);
    await()
        .untilAsserted(
            () ->
                assertThat(getSegmentsCount(broker))
                    .describedAs("Expected less segments after a snapshot is taken")
                    .isLessThan(segmentsCount));
  }
```

**Expected behavior**

Snapshotting and compaction is doen without issues.

**Log/Stacktrace**

Following log indicates that no snapshots are taken.
```
21:40:04.444 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=15, version=1, index=620}
21:40:04.447 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] WARN  io.zeebe.logstreams.snapshot - Failed to obtain a pending snapshot directory for position 617
```

**Environment:**
 - Zeebe Version: 0.24.0

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

First installs exporter director to clean up the state correctly. Closes the exporter director afterwards, if no more exporters are configured.

## Related issues

closes #5105 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

File: broker/src/main/java/io/zeebe/broker/exporter/stream/ExporterDirector.java [hunk 1]
```diff
@@ -227,7 +227,11 @@ private void onSnapshotRecovered() {
 
     clearExporterState();
 
-    actor.submit(this::readNextEvent);
+    if (state.hasExporters()) {
+      actor.submit(this::readNextEvent);
+    } else {
+      actor.close();
```
Comment (korthout) [inline broker/src/main/java/io/zeebe/broker/exporter/stream/ExporterDirector.java:233]: could we close the actor sooner if we anyways know there are no exporters? or is the point of this change to do this after the state.setPosition above here at line 222?

**Review by korthout — APPROVED** [review]
LGTM, just some minor questions

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java [hunk 2]
```diff
@@ -113,12 +114,42 @@ public void shouldNotCompactNotExportedEvents() {
...
 
-    while (getSegmentsCount(broker) <= segmentCount) {
-      writeToLog();
-      writtenRecords.incrementAndGet();
-    }
+    // restart with no exporter
+    final var brokerCfg = clusteringRule.getBrokerCfg(0);
+    brokerCfg.setExporters(Map.of());
+    clusteringRule.stopBroker(0);
+    clusteringRule.startBroker(0);
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java:131]: No I can't because It waits for a new leader, which is not possible on a single node. I tried it before with that :D

File: broker/src/main/java/io/zeebe/broker/exporter/stream/ExporterDirector.java (hunk 1 above)
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/exporter/stream/ExporterDirector.java:233]: The point is after cleaning up the state to close the actor yes. Before we haven't done it, which caused this issue. Its about line 228.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (korthout) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SingleBrokerDataDeletionTest.java:131]: Ah good point.

File: broker/src/main/java/io/zeebe/broker/exporter/stream/ExporterDirector.java (hunk 1 above)
Comment (korthout) [reply broker/src/main/java/io/zeebe/broker/exporter/stream/ExporterDirector.java:233]: Thanks for explaining

**Review by korthout — APPROVED** [review]

**Comment by korthout** [comment]
Please remember the backports and `New content is added to the release announcement`

**Comment by Zelldon** [comment]
Bors r+

**Comment by npepinpe** [comment]
bors retry

**Comment by npepinpe** [comment]
Seems the new test is failing when we try to merge

**Comment by Zelldon** [comment]
> Seems the new test is failing when we try to merge

Will check tomorrow

**Comment by Zelldon** [comment]
> Please remember the backports and New content is added to the release announcement

@korthout and where I can find this doc? :sweat_smile: Might make sense to link it in the PR todo list 
\cc @npepinpe

**Comment by Zelldon** [comment]
Bors r+

**Comment by korthout** [comment]
> @korthout and where I can find this doc?

I'll send it via Slack (not sure we want that public).
