### PR TITLE
fix: AssignUserTaskTest is unstable

### LINKED ISSUE #17668: Several flaky tests in  io.camunda.zeebe.it.client.command.AssignUserTaskTest
**Summary**

- How often does the test fail? Once
- Does it block your work? No 
- Do we suspect that it is a real failure?

**Failures**

shouldRejectIfUserTaskIsAlreadyAssignedWithProhibitedOverride: io.camunda.zeebe.it.client.command.AssignUserTaskTest
```
[Expected a created user task] 
Expecting actual:
  -1L
to be greater than:
  0L
java.lang.AssertionError: 
[Expected a created user task]
Expecting actual:
-1L
to be greater than:
0L


at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:187)
at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:173)
at io.camunda.zeebe.it.client.command.AssignUserTaskTest.initClientAndInstances(AssignUserTaskTest.java:42)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

shouldRejectIfMissingAssignee: io.camunda.zeebe.it.client.command.AssignUserTaskTest
```
java.lang.AssertionError: 
[Expected a created user task] 
Expecting actual:
  -1L
to be greater than:
  0L
at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:187)
at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:173)
at io.camunda.zeebe.it.client.command.AssignUserTaskTest.initClientAndInstances(AssignUserTaskTest.java:42)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
**Hypotheses**

None

**Logs**
https://github.com/camunda/zeebe/actions/runs/8786220325

[Test results for [IT] QA Integration Tests.zip](https://github.com/camunda/zeebe/files/15072345/Test.results.for.IT.QA.Integration.Tests.zip)

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

`@TestZeebe` annotation can be used to create an instance of `TestStandaloneBroker` object. When the field is defined as static, the broker instance is created once for all test in the related test class (see zeebe/qa/util/src/main/java/io/camunda/zeebe/qa/util/junit/ ZeebeIntegrationExtension.java). Otherwise, the test broker re-created for every test case.

Even if we reset the exporter before executing each test case, the order of accessing to the exporter is not guaranteed. While running the test in a multi threaded environment this might lead to unordered access to the exporter (see: [ReentrantLock docs](https://docs.oracle.com/javase%2F8%2Fdocs%2Fapi%2F%2F/java/util/concurrent/locks/ReentrantLock.html)) so break the test isolation. We would like to improve the isolation and re-ceate TestStandaloneBroker for each case.

## Related issues

closes #17668

### CODE REVIEW

**Comment by berkaycanbc** [comment]
@npepinpe this PR is expected to fix the issue `failed: Address already in use` as we fixed it in a similar way before. But it might be a solution reported in the issue #17668 as well since we will now also re-create the exported for each test (see my comment https://github.com/camunda/camunda/issues/17668#issuecomment-2147329129). Any opinions on that?

**Comment by berkaycanbc** [comment]
@npepinpe I think, the hypothesis for #16583 was initially the REST port or binding ports without going through the `SocketUtil` utility as you mentioned. But then the provided solution was based on different hypothesis that mutating single broker state may create side-effects across tests see https://github.com/camunda/camunda/pull/16697#issue-2168519485. How could that be related to port collision?

**Comment by npepinpe** [comment]
Oh, are we mutating the broker state here between tests? That may affect the other flaky cases, but I don't see how that would affect the launch of the static broker and the address already in use though :thinking: Are we restarting it during or in between the tests?

**Comment by npepinpe** [comment]
I mean, we can launch it at every test, it's relatively cheap honestly once it's already launched once, I just don't see how it will help with the address in use error. But it may prevent flakiness with the other tests by improving the test isolation :+1:

**Comment by berkaycanbc** [comment]
> Oh, are we mutating the broker state here between tests? That may affect the other flaky cases, but I don't see how that would affect the launch of the static broker and the address already in use though 🤔 Are we restarting it during or in between the tests?

W are mutating it in this class, so shouldn't make a difference. I think, the issue with port collision is still a different issue exist also in other user tasks test classes (see issue #17007).

> I mean, we can launch it at every test, it's relatively cheap honestly once it's already launched once, I just don't see how it will help with the address in use error. But it may prevent flakiness with the other tests by improving the test isolation 👍

I agree, it will improve test isolation anyways.


Even if we reset the underlying exporter, since the order of access to it is not guaranteed. Is it possible that it might lead to cases where `RecordingExporter.reset()` acquires the lock and while `RecordingExporter.export()` should have it? If so, this PR can actually fix the flakiness. @npepinpe

**Comment by npepinpe** [comment]
Hm, reseting should prevent any exporting. What we've observed is if you run two tests in a row, you may see records from the previous test being exported in the next, which may skew things. I guess unless you're running your tests in parallel threads, which we typically don't (we only run them in parallel processes) :thinking:

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/AssignUserTaskTest.java [hunk 1]
```diff
@@ -27,12 +27,10 @@
 @AutoCloseResources
 class AssignUserTaskTest {
 
+  @AutoCloseResource ZeebeClient client;
   @TestZeebe
-  private static final TestStandaloneBroker ZEEBE =
+  private final TestStandaloneBroker ZEEBE =
```
Comment (npepinpe) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/AssignUserTaskTest.java:32]: :x: To fix the linter, you'll need to rename this to `zeebe`.

**Review by npepinpe — APPROVED** [review]
We can try it, but I'm not sure it will fix all the issues =/

**Comment by tmetzke** [comment]
As far as I understood the related issue, the `Address already in use` problem only comes up when the respective tests are retried due to a failure (like the one in #17007). The fix might still resolve this issue now with the changes. I have to admit I cannot fully judge this at this point. Just wanted to leave this bit of information here for context.

**Comment by npepinpe** [comment]
I guess I'm not super familiar with how the retries interact with the junit extensions. Would the extensions be restarted as well? :thinking:

**Comment by tmetzke** [comment]
> I guess I'm not super familiar with how the retries interact with the junit extensions. Would the extensions be restarted as well? 🤔

No idea, to be honest. @berkaycanbc, any ideas here?

Also, @berkaycanbc, thanks for tackling this! ⭐ 

Was there any specific reason for only updating one of the user task IT classes and not all? This issue persists for the other user task ITs as well, namely [CompleteUserTaskTest](https://github.com/camunda/camunda/blob/main/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/CompleteUserTaskTest.java), [UnassignUserTaskTest](https://github.com/camunda/camunda/blob/main/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/UnassignUserTaskTest.java), and [UpdateUserTaskTest](https://github.com/camunda/camunda/blob/main/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/UpdateUserTaskTest.java).

**Comment by berkaycanbc** [comment]
> Was there any specific reason for only updating one of the user task IT classes and not all? This issue persists for the other user task ITs as well, namely [CompleteUserTaskTest](https://github.com/camunda/camunda/blob/main/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/CompleteUserTaskTest.java), [UnassignUserTaskTest](https://github.com/camunda/camunda/blob/main/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/UnassignUserTaskTest.java), and [UpdateUserTaskTest](https://github.com/camunda/camunda/blob/main/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/UpdateUserTaskTest.java).

We were not sure if the solution provided here will actually resolve the flakiness, so didn't apply it to similar classes yet.

> > I guess I'm not super familiar with how the retries interact with the junit extensions. Would the extensions be restarted as well? 🤔
> 
> No idea, to be honest. @berkaycanbc, any ideas here?

Not really. But I locally run the same `mvn` command we run in CI for tests:

```
mvnd -B -T 1 --no-snapshot-updates -D forkCount=10 -D maven.javadoc.skip=true -D skipUTs -D skipChecks -D failsafe.rerunFailingTestsCount=3 -D flaky.test.reportDir=failsafe-reports -P parallel-tests,extract-flaky-tests -pl qa/integration-tests -Dit.test=io.camunda.zeebe.it.client.command.AssignUserTaskTest -f zeebe verify | tee "build_output.txt"
```

still only getting assertion errors when I insert a random assertion failure (`assert random.nextBoolean()`) to one of the test cases. So, unable to verify if it is because of failing test retries.

@tmetzke
