### PR TITLE
Fix error when taking a backup with the native file system store

### LINKED ISSUE #38957: Cannot take native filesystem backup in an empty state
### 

### 

### 

### 

### Description

Since we now query for an existing backup with wildcard before taking a backup, the native file system store fails immediately, as the initial directories are not created.

### Steps to reproduce

1. Start a broker configured to use native file system backup
2. Take a backup
3. See the logs for the error

### Current behavior

Fails to take a backup on an empty state when the directories are missing.

### Expected behavior

Works out of the box :)

### Workaround

1. Create the `contents` and `manifests` directory manually in your volume

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR ensures two things with the native file system backup store:

1. The paths are portable by delegating the creation/resolution to the JVM
2. The paths for contents/manifests are pre-created when the store is set up

## Related issues

closes #38957

### CODE REVIEW

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/FilesystemBackupAcceptanceIT.java [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+          backup.setStore(BackupStoreType.FILESYSTEM);
+
+          final var config = new FilesystemBackupStoreConfig();
+          config.setBasePath(basePath.toAbsolutePath().toString());
+          backup.setFilesystem(config);
+        });
+  }
+
+  private void configureNode(final TestApplication<?> node) {
+    node.withProperty("management.endpoints.web.exposure.include", "*");
```
Comment (lenaschoenburg) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/FilesystemBackupAcceptanceIT.java]: 🙃 I'm pretty sure that's not needed anymore

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/FilesystemRestoreAcceptanceIT.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    final var config = new FilesystemBackupStoreConfig();
+    config.setBasePath(basePath.toAbsolutePath().toString());
+    backup.setFilesystem(config);
+  }
+
+  private Path createBackupDir() {
+    final var path = tempDir.resolve(UUID.randomUUID().toString());
+
+    try {
+      FileUtil.ensureDirectoryExists(path);
```
Comment (lenaschoenburg) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/FilesystemRestoreAcceptanceIT.java]: ❓ I think that's not needed because the changes in https://github.com/camunda/camunda/pull/38959/files#diff-bf078cbb027ea07dacdad5242af9bd17833f6772badcfd11db3fe811355ae13dR68-R69?

File: zeebe/backup-stores/filesystem/src/main/java/io/camunda/zeebe/backup/filesystem/ManifestManager.java
Comment (lenaschoenburg) [inline zeebe/backup-stores/filesystem/src/main/java/io/camunda/zeebe/backup/filesystem/ManifestManager.java]: 🔧 Should be just `manifestsPath` now that we don't hardcode "manifests" in here anymore.

**Review by lenaschoenburg — APPROVED** [review]
Thanks!

File: zeebe/backup-stores/filesystem/src/main/java/io/camunda/zeebe/backup/filesystem/ManifestManager.java [hunk 3]
```diff
@@ -138,7 +139,7 @@ void markAsFailed(final BackupIdentifier manifestId, final String failureReason)
     }
   }
 
-  public void deleteManifest(final BackupIdentifier id) {
+  void deleteManifest(final BackupIdentifier id) {
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply zeebe/backup-stores/filesystem/src/main/java/io/camunda/zeebe/backup/filesystem/ManifestManager.java:141]: False positive

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/FilesystemRestoreAcceptanceIT.java (hunk 2 above)
Comment (npepinpe) [reply zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/FilesystemRestoreAcceptanceIT.java]: Possibly not, but I wasn't sure if the tests ever do something else or weird where they access it directly :thinking:

Comment (npepinpe) [reply zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/FilesystemRestoreAcceptanceIT.java]: Guess there's an easy way to find out :D

File: zeebe/backup-stores/filesystem/src/main/java/io/camunda/zeebe/backup/filesystem/ManifestManager.java
Comment (npepinpe) [reply zeebe/backup-stores/filesystem/src/main/java/io/camunda/zeebe/backup/filesystem/ManifestManager.java]: Can't believe Copilot didn't catch that smh

What's even the point of AI
