### PR TITLE
Fixes rolling update issues

### LINKED ISSUE #4961: Rolling update not possible with 0.24
**Describe the bug**

We removed in the last version unused requests, commands, primitives and sessions etc. from atomix, related PR https://github.com/zeebe-io/zeebe/pull/4466.

The problem is that  we remove types from the RaftNamespace [here](https://github.com/zeebe-io/zeebe/commit/d34a70ac0ead5ff927ea939d695576da626412a0#diff-21fe866d2487733146e40ee22dcef1b0), which breaks rolling updates.

Internally the atomix namespace classes are based on kryo, which assign each registered type an index. If you remove one of these types in between the types get different values as on the previous version. It is like an enum ordinal.

To fix this for the storage we introduce `void` types into the namespace to keep the ids
https://github.com/zeebe-io/zeebe/blob/develop/atomix/cluster/src/main/java/io/atomix/raft/partition/impl/RaftNamespaces.java#L102-L114

For the communication namespace we haven't done that, because no test were failing. The problem was we had no tests for rolling updates.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

The first test a totally simple and only test that we are able to upgrade a node and start the new version without problems. Later we can add more sophisticated tests.

The fix is fairly simple we just register void as placeholder for the removed classes.

For reference test passes with fix https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/zell-fix-rolling-update/1/pipeline/89 and fails without https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/zell-rolling-update/4/pipeline/89/

## Related issues

closes #4961 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release annoncement

### CODE REVIEW

File: upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+import org.slf4j.event.Level;
+import org.testcontainers.containers.Network;
+import org.testcontainers.containers.output.Slf4jLogConsumer;
+import org.testcontainers.lifecycle.Startables;
+
+public class RollingUpdateTest {
+  private static final Logger LOG = LoggerFactory.getLogger(ContainerStateRule.class);
+  private static final String OLD_VERSION = "0.23.3";
```
Comment (npepinpe) [inline upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:31]:
```suggestion
  private static final String OLD_VERSION = VersionUtil.getPreviousVersion();
```

Or replace all occurrences of `OLD_VERSION` to `VersionUtil.getPreviousVersion()`

File: upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+        .withEnv("ZEEBE_BROKER_CLUSTER_NODEID", String.valueOf(index))
+        .withEnv("ZEEBE_BROKER_CLUSTER_CLUSTERSIZE", String.valueOf(clusterSize))
+        .withEnv("ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR", String.valueOf(clusterSize))
+        .withEnv("ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS", initialContactPoints)
+        .withLogConsumer(new Slf4jLogConsumer(LOG))
+        .withLogLevel(Level.DEBUG)
+        .withDebug(false);
+  }
+
+  private <T extends AutoCloseable> T withCloseable(final T closeable) {
```
Comment (npepinpe) [inline upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:123]:
```suggestion
  private <T extends AutoCloseable> T asManagedCloseable(final T closeable) {
```

File: upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+        .withEnv("ZEEBE_BROKER_NETWORK_ADVERTISED_HOST", hostName)
+        .withEnv("ZEEBE_BROKER_CLUSTER_CLUSTERNAME", "zeebe-cluster")
+        .withEnv("ZEEBE_BROKER_DATA_SNAPSHOTPERIOD", "1m")
+        .withEnv("ZEEBE_BROKER_DATA_LOGSEGMENTSIZE", "1MB")
+        .withEnv("ZEEBE_BROKER_NETWORK_MAXMESSAGESIZE", "1MB")
+        .withEnv("ZEEBE_BROKER_CLUSTER_NODEID", String.valueOf(index))
+        .withEnv("ZEEBE_BROKER_CLUSTER_CLUSTERSIZE", String.valueOf(clusterSize))
+        .withEnv("ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR", String.valueOf(clusterSize))
+        .withEnv("ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS", initialContactPoints)
+        .withLogConsumer(new Slf4jLogConsumer(LOG))
```
Comment (npepinpe) [inline upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:118]: Is this necessary always? It's really only useful when debugging, no? And the container state rule should output logs of containers when the test fails, so we probably only need that.

File: upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+    final var zeebeBrokerContainer = replaceBrokerContainer(index, newVersion);
+
+    // then
+    zeebeBrokerContainer.start();
+  }
+
+  private ZeebeBrokerContainer replaceBrokerContainer(final int index, final String newVersion) {
+    final var broker = new ZeebeBrokerContainer(newVersion);
+    containers.set(index, broker);
+    nodeZeroContainer = getConfiguredClusterBroker(index, containers);
```
Comment (npepinpe) [inline upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:95]:
```suggestion
    newContainer = getConfiguredClusterBroker(index, containers);
```

nodeZeroContainer made it sound like index should always be 0 :sweat_smile:

**Review by npepinpe — CHANGES_REQUESTED** [review]
Thanks for the fast PR :slightly_smiling_face:  

I think the tests aren't testing the rolling upgrade - they simply restart a single node. A rolling upgrade would restart each node sequentially, then make sure the cluster is up and running again. In this instance, we're just testing that brokers of different versions can speak to each other.

We could write a test where we do this - from OLD_VERSION to CURRENT_VERSION, sequentially, then await until we have a complete topology.

You can write something like:

```java
Awaitility.await().atMost(Duration.ofSeconds(30)).untilAsserted(() -> assertThat(zeebeClient.newTopologyRequest().send().join()).isComplete(3, 1));
```

The `GatewayLivenessProbeIntegrationTest` is an example of how to wait until the topology is complete for example (e.g. `assertTopologyIsComplete`).

**Comment by Zelldon** [comment]
> In this instance, we're just testing that brokers of different versions can speak to each other.

Yes which is the key point of a rolling upgrade that the node can still talk to each other and join successfully the cluster. This was also the thing which fails, as I wrote I just did a simple test for now, which we can always improve.

**Comment by npepinpe** [comment]
Then let's add a follow up issue to add a rolling upgrade tests :+1:

File: upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java (hunk 1 above)
Comment (Zelldon) [reply upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:31]: Actually I want to have this hard coded, since we should also be able to do upgrade from pre-previous version if we are really backwards compatible. So ideally we should have tests which starts on the last supported and be able to upgrade to the newest.

Comment (npepinpe) [reply upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:31]: Do you mean skip minor versions (e.g. 0.23 to 0.25) or do you mean skip micro versions (0.23.x to 0.24.x)?

Comment (Zelldon) [reply upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:31]: I mean if we say we are backwards compatible this is implicit that this is possible.

Comment (npepinpe) [reply upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:31]: We typically say we're backwards compatible from one version to the other, I've never heard any mention that we also are with older versions. Was this something that was decided a while back?

File: upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java (hunk 2 above)
Comment (Zelldon) [reply upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:123]: this method was copied btw from your branch :D

Comment (npepinpe) [reply upgrade-tests/src/test/java/io/zeebe/test/RollingUpdateTest.java:123]: Everybody makes mistakes :sweat_smile:

**Comment by Zelldon** [comment]
@npepinpe I updated the branch

**Review by npepinpe — APPROVED** [review]
:+1:  thanks!

I'll add a follow up issue to add a test that checks the rolling upgrade completely
