### PR TITLE
test: refactor flaky test case

### LINKED ISSUE #24824: Flaky test CredentialsProviderSelfManagedTest shouldHaveZeebeAuth
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once [here](https://github.com/camunda/camunda/actions/runs/11897299647?pr=24823)
- Does it block your work? no
- Do we suspect that it is a real failure? IDK

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
  shouldHaveZeebeAuth: io.camunda.zeebe.spring.client.config.CredentialsProviderSelfManagedTest

expected: {"Authorization"="***;}
 but was: {"Authorization"="***;}
org.opentest4j.AssertionFailedError: 
expected: {"Authorization"=";}
but was: {"Authorization"=";}
at io.camunda.zeebe.spring.client.config.CredentialsProviderSelfManagedTest.shouldHaveZeebeAuth(CredentialsProviderSelfManagedTest.java:108)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

The `clientId` is the same with multiple credentials tests in the Camunda Spring SDK ([src](https://github.com/camunda/camunda/blob/d5e476b70dfc2dd2e430200e3de5979bfa25871c/clients/spring-boot-starter-camunda-sdk/src/test/java/io/camunda/spring/client/config/CredentialsProviderSelfManagedTest.java#L48)). 

The `credentialsCache` used by the `OAuthCredentialsProvider` in the tests (see [src](https://github.com/camunda/camunda/blob/d5e476b70dfc2dd2e430200e3de5979bfa25871c/clients/java/src/main/java/io/camunda/client/impl/oauth/OAuthCredentialsProvider.java#L98-L99)) may return a token from a different test that is run in parallel.

This PR sets a unique `clientId` to avoid getting tokens from the cache from other tests run in parallel.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #24824

### CODE REVIEW

File: clients/spring-boot-starter-camunda-sdk/src/test/java/io/camunda/spring/client/config/CredentialsProviderSelfManagedTest.java [hunk 1]
```diff
@@ -92,10 +93,13 @@ void shouldHaveZeebeAuth() throws IOException {
...
 
+    // when
     credentialsProvider.applyCredentials(headers::put);
-    credentialsProvider.applyCredentials(headers::put);
+
+    // then
     assertThat(credentialsProvider).isExactlyInstanceOf(OAuthCredentialsProvider.class);
-    assertThat(headers).containsEntry("Authorization", "Bearer " + accessToken);
+    final var authorizationValue = headers.get("Authorization");
+    assertThat(authorizationValue).isEqualTo("Bearer " + accessToken);
```
Comment (danielkelemen) [inline clients/spring-boot-starter-camunda-sdk/src/test/java/io/camunda/spring/client/config/CredentialsProviderSelfManagedTest.java:102]: 🙃 The map `containsEntry` would also work fine I guess.

**Review by danielkelemen — APPROVED** [review]

File: clients/spring-boot-starter-camunda-sdk/src/test/java/io/camunda/spring/client/config/CredentialsProviderSelfManagedTest.java (hunk 1 above)
Comment (koevskinikola) [reply clients/spring-boot-starter-camunda-sdk/src/test/java/io/camunda/spring/client/config/CredentialsProviderSelfManagedTest.java:102]: 👍 I'll revert this change
