### PR TITLE
fix: Get decision instance by ID does not return evaluatedInputs and matchedRules

### LINKED ISSUE #38634: Get decision instance by ID does not return evaluatedInputs and matchedRules
### 

### 

### 

### 

### Description

`GET /v2/decision-instances/<instance-key>` returns empty arrays for both `evaluatedInputs` and `matchedRules` (should contain evaluatedOutputs according to the API spec).

### Steps to reproduce

1. Evaluate a decision
2. Get the decision instance using `GET /v2/decision-instances/<instance-key>`

### Current behavior

`GET /v2/decision-instances/<instance-key>` returns empty arrays for both `evaluatedInputs` and `matchedRules`.

### Expected behavior

`GET /v2/decision-instances/<instance-key>` should return both `evaluatedInputs` and `matchedRules`
### Environment

SaaS & SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

Evaluated inputs and outputs fields inclusion in ES/OS results was removed in https://github.com/camunda/camunda/pull/35517

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

[Slack discussion](https://camunda.slack.com/archives/C08MRKHJ0CD/p1758548603242399)

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #38634

### CODE REVIEW

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/DecisionInstanceSearchTest.java [hunk 1]
```diff
@@ -15,6 +15,8 @@
 import static org.assertj.core.api.Assertions.assertThat;
 import static org.assertj.core.api.Assertions.tuple;
 import static org.assertj.core.api.AssertionsForClassTypes.assertThatExceptionOfType;
+import static org.skyscreamer.jsonassert.JSONAssert.assertEquals;
```
Comment (tmetzke) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/DecisionInstanceSearchTest.java]: Why are we doing JSON assertions in QA client tests? Shouldn't we validate the Java client response and its properties?

Comment (houssain-barouni) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/DecisionInstanceSearchTest.java]: the `toJson()` returns the json representation of the the java client response object, and not the rest API json response.
Asserting the json is implicitly asserting the client response properties

```
  public String toJson() {
    return jsonMapper.toJson(this);
  }
```

Comment (tmetzke) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/DecisionInstanceSearchTest.java]: Sorry, I wasn't clear enough on this 😅 On a technical level, this is absolutely fine, of course 👍

I was simply wondering why we're doing it here this way, testing the JSON representation of the client response, and not the properties directly like we usually do. It makes the acceptance tests less consistent, introducing another way of testing client properties.

Comment (houssain-barouni) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/DecisionInstanceSearchTest.java]: I see. I found the json comparison more readable and less tedious to write, especially for nested objects. But I agree, let's keep it consistent.

Comment (tmetzke) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/DecisionInstanceSearchTest.java]: Yeah, I can definitely see that 👍😅

Comment (houssain-barouni) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/DecisionInstanceSearchTest.java]: Done!

File: qa/acceptance-tests/pom.xml [hunk 2]
```diff
@@ -460,7 +460,6 @@
     <dependency>
       <groupId>io.camunda</groupId>
       <artifactId>configuration</artifactId>
-      <version>${project.version}</version>
```
Comment (tmetzke) [inline qa/acceptance-tests/pom.xml:463]: 👍

**Review by tmetzke — APPROVED** [review]
🚀
