### PR TITLE
fix: parse unexpected REST responses in client

### LINKED ISSUE #25087: Zeebe Java Client Fails to Handle Error Responses Gracefully
## Description

The Zeebe Java client currently does not handle error responses properly. When the server sends an error response with a payload that doesn’t match the expected response model, the client attempts to deserialize it into the expected type. This causes a deserialization exception instead of providing meaningful feedback about the error.

**Example**
```
io.camunda.zeebe.client.api.command.ClientException: io.camunda.zeebe.client.api.command.ClientException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "timestamp" (class io.camunda.zeebe.client.protocol.rest.UserCreateResponse), not marked as ignorable (one known property: "userKey"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.camunda.zeebe.client.protocol.rest.UserCreateResponse["timestamp"])
```

This behavior makes troubleshooting issues difficult because the actual problem from the server is obscured by client-side deserialization errors.

The client should throw a predefined exception that contains the raw error message from the server for easier debugging.

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

If an unexpected response is returned for REST calls, the Java client needs to handle this in a meaningful way. The client tries to parse "application/json" responses as the defined target type. If this fails, it returns a ProblemDetail instead, containing the original payload JSON as detail information.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #25087

### CODE REVIEW

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java [hunk 1]
```diff
@@ -91,10 +92,18 @@ public JsonApiEntityConsumer(
...
+        try {
+          return ApiEntity.of(json.readValue(buffer.asParserOnFirstToken(), type));
+        } catch (final IOException ioe) {
+          return ApiEntity.of(
+              new ProblemDetail()
+                  .title("Unexpected server response")
+                  .status(500)
+                  .detail(
+                      json.writeValueAsString(
+                          json.readValue(buffer.asParserOnFirstToken(), Map.class))));
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java:105]: 💭 I'm not really happy with this. Overall, I'm wondering if we should go for a similar approach as the raw entity and simply collect the text. That way, we can create a very generic catch clause for the whole `generateContent` method (including trying to parse the problem detail response) that is less prone to run into response obfuscation again. Currently, this can still happen if the response cannot be parsed into a `Map` either.

Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java:105]: Alternative I will pursue: Flush the original JSON collected in the `TokenBuffer` out into an output stream "raw"

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java [hunk 2]
```diff
@@ -91,13 +93,23 @@ public JsonApiEntityConsumer(
...
-        return ApiEntity.of(json.readValue(buffer.asParserOnFirstToken(), type));
+      try {
+        if (isResponse) {
+          return ApiEntity.of(json.readValue(buffer.asParserOnFirstToken(), type));
+        }
+        return ApiEntity.of(json.readValue(buffer.asParserOnFirstToken(), ProblemDetail.class));
+      } catch (final IOException ioe) {
+        // write the original JSON response into an error response
+        final ByteArrayOutputStream output = new ByteArrayOutputStream();
+        final JsonGenerator generator = json.createGenerator(output);
```
Comment (houssain-barouni) [inline clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java:104]: `JsonGenerator` is closable so may need to be closed
```suggestion
    try (final ByteArrayOutputStream output = new ByteArrayOutputStream();
         final JsonGenerator generator = json.createGenerator(output)) {
```

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java [hunk 3]
```diff
@@ -91,13 +93,23 @@ public JsonApiEntityConsumer(
...
+        buffer.serialize(generator);
```
Comment (houssain-barouni) [inline clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java:105]: `serialize` itself throws an `IOException`, I guess we handle it upstreams as before?

**Review by houssain-barouni — COMMENTED** [review]
Thanks for fixing this! 💪 
one little suggestion 🔧

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java (hunk 2 above)
Comment (nathansandi) [inline clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java:104]: 💭 Should we place this inside a try, to ensure proper resource cleanup? 

```
try (JsonGenerator generator = json.createGenerator(output)) {
      buffer.serialize(generator);
      generator.flush();
  }
```

**Review by nathansandi — APPROVED** [review]
Looks good to me, I have added a minor suggestion related to `ByteArrayOutputStream`  usage, once it can throw a new exception inside the exception block.

**Review by nathansandi — CHANGES_REQUESTED** [review]
I approve by accident. But so far, minor suggestion changes.

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java (hunk 2 above)
Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java]: Yep, let's do that

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java (hunk 3 above)
Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java]: We'll handle it explicitly to avoid obfuscating the original issue. However, I don't see much we can do anymore except for saying "we received something we cannot decipher"

File: clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java [hunk 4]
```diff
@@ -136,6 +142,17 @@ public void releaseResources() {
...
     }
+
+    private String getJsonString() {
+      try (final ByteArrayOutputStream output = new ByteArrayOutputStream();
+          final JsonGenerator generator = json.createGenerator(output)) {
+        buffer.serialize(generator);
+        generator.flush();
+        return output.toString(StandardCharsets.UTF_8.name());
+      } catch (final Exception ex) {
+        return "Original response cannot be constructed";
```
Comment (houssain-barouni) [inline clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java:153]: we should pass the exception to the logger, you will thank me when you are the medic 😄 
```suggestion
        LOGGER.error("Failed to serialize the error response", ex);
        return "Original response cannot be constructed";
```

Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/zeebe/client/impl/http/TypedApiEntityConsumer.java:153]: Yeah, you're right 😆

**Review by houssain-barouni — APPROVED** [review]
LGTM 👍

**Review by nathansandi — APPROVED** [review]
LGTM :) 🥇
