### PR TITLE
fix: add configuration for maximum incident search groups

### LINKED ISSUE #44596: Big API response causes the Operate UI to crash when retrieving incidents
### 

### 

### 

### 

### Description

The full discussion about this bug is available in the following slack channel:
https://camunda.slack.com/archives/C0AAPHF7W9W/p1769070895698619

This bug is caused by a performance problem caused by the internal (v1) API used by the Operate UI to fetch the incidents. When the number of incidents is large, the API response is so big ([some experiment](https://camunda.slack.com/archives/C0AAPHF7W9W/p1769023926653349) evaluated a payload of ~50 MB)that the UI times out into crashing.

The longer term solution to this problem is already happening and it is achieved by the deprecation of the API v1, in favor of the API v2. Such replacement would implicitly solve the problem, as v2 works with paginated responses for all of the endpoints. The EPICs that track this API migration are the following:
* https://github.com/camunda/camunda/issues/27250
* https://github.com/camunda/camunda/issues/32400

If we decide to go for a shorter term solution, there could be some possibilities, although investigation should happen. Some ideas are the following:
* introduce pagination in the incidents endpoint
* put a limit on the amount of results returned by the API (this could be justified by the fact that, as a user, one could hardly manage a very big result in any case)

### Steps to reproduce

https://camunda.slack.com/archives/C0AAPHF7W9W/p1769023926653349

### Current behavior

The payload returned by the API grows linearly with the number of incidents, preventing the web socket to complete the operation.

### Expected behavior

The API should be invocable with success in every situation.

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

8.8

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by lev-safro**
## Description

- Fixes issue #44596: avoid extremely large responses from the incidents API by capping the number of incident search groups returned.
- Adds a configurable limit with a safe default and enforces it in the reader logic.

**What this change does**
- Initially the query results were limited by `ElasticsearchUtil` constant:
```
 public static final int TERMS_AGG_SIZE = 10000;
```
- Introduces a configurable property `camunda.operate.max-incident-search-groups` with a default of `1000`.
- The default is applied using the `@Value` fallback, so modules without a local properties file still get the default.
- Example declaration used: 

```
@Value("${camunda.operate.max-incident-search-groups:1000}")
private int maxIncidentSearchGroups;
```
- Enforces the limit in `IncidentStatisticsReader` so it truncates search groups to the configured maximum.

**Behavioral changes**
- API responses for incident statistics are now capped to at most `camunda.operate.max-incident-search-groups` groups (default `1000`).
- No breaking changes to API shape; only the number of returned items may be reduced when the raw count exceeds the configured limit.

**Testing**
To test this fix add an env variable `CAMUNDA_OPERATE_MAX_INCIDENT_SEARCH_GROUPS` to start configuration and change the value, for example, to `3` and trigger the endpoint 

```
GET http://localhost:8080/api/incidents/byError
```

Test results will be documented in the comments

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes)).

## Related issues

closes #44596

### CODE REVIEW

**Comment by lev-safro** [comment]
### Dev testing

**Default configuration:** 

```GET http://localhost:8080/api/incidents/byError```

```
[
  {
    "errorMessage": "Expected process with BPMN process id 'call-level-3-process' to be deployed, but not found.",
    "incidentErrorHashCode": -1525158685,
    "instancesWithErrorCount": 45,
    "processes": [
      {
        "processId": "2251799813689147",
        "version": 1,
        "name": "Call Level 2 Process",
        "bpmnProcessId": "call-level-2-process",
        "tenantId": "<default>",
        "errorMessage": "Expected process with BPMN process id 'call-level-3-process' to be deployed, but not found.",
        "instancesWithActiveIncidentsCount": 30,
        "activeInstancesCount": 0
      },
      {
        "processId": "2251799813689154",
        "version": 1,
        "name": "Process with elements incidents",
        "bpmnProcessId": "incidents-process",
        "tenantId": "<default>",
        "errorMessage": "Expected process with BPMN process id 'call-level-3-process' to be deployed, but not found.",
        "instancesWithActiveIncidentsCount": 15,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Failed to extract the correlation key for 'clientId': The value must be either a string or a number, but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'clientId'",
    "incidentErrorHashCode": 746263669,
    "instancesWithErrorCount": 45,
    "processes": [
      {
        "processId": "2251799813697721",
        "version": 3,
        "name": null,
        "bpmnProcessId": "complexProcess",
        "tenantId": "<default>",
        "errorMessage": "Failed to extract the correlation key for 'clientId': The value must be either a string or a number, but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'clientId'",
        "instancesWithActiveIncidentsCount": 25,
        "activeInstancesCount": 0
      },
      {
        "processId": "2251799813694931",
        "version": 2,
        "name": "Event based gateway with timer start",
        "bpmnProcessId": "eventBasedGatewayProcess",
        "tenantId": "<default>",
        "errorMessage": "Failed to extract the correlation key for 'clientId': The value must be either a string or a number, but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'clientId'",
        "instancesWithActiveIncidentsCount": 20,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Expected result of the expression 'candidateGroups' to be 'ARRAY', but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'candidateGroups'",
    "incidentErrorHashCode": 142758297,
    "instancesWithErrorCount": 37,
    "processes": [
      {
        "processId": "2251799813685449",
        "version": 1,
        "name": "Flight registration",
        "bpmnProcessId": "flightRegistration",
        "tenantId": "<default>",
        "errorMessage": "Expected result of the expression 'candidateGroups' to be 'ARRAY', but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'candidateGroups'",
        "instancesWithActiveIncidentsCount": 37,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Expected to evaluate decision 'invoiceAssignApprover', but no decision found for id 'invoiceAssignApprover'",
    "incidentErrorHashCode": -146147960,
    "instancesWithErrorCount": 27,
    "processes": [
      {
        "processId": "2251799813689091",
        "version": 1,
        "name": "DMN invoice",
        "bpmnProcessId": "invoice",
        "tenantId": "<default>",
        "errorMessage": "Expected to evaluate decision 'invoiceAssignApprover', but no decision found for id 'invoiceAssignApprover'",
        "instancesWithActiveIncidentsCount": 27,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Expected at least one condition to evaluate to true, or to have a default flow",
    "incidentErrorHashCode": 1868633234,
    "instancesWithErrorCount": 25,
    "processes": [
      {
        "processId": "2251799813697721",
        "version": 3,
        "name": null,
        "bpmnProcessId": "complexProcess",
        "tenantId": "<default>",
        "errorMessage": "Expected at least one condition to evaluate to true, or to have a default flow",
        "instancesWithActiveIncidentsCount": 25,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Expected result of the expression ' list contains(flows,\"2\")' to be 'BOOLEAN', but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'flows'\n[FUNCTION_INVOCATION_FAILURE] Failed to invoke function 'list contains': Illegal arguments: 'null', '\"2\"'",
    "incidentErrorHashCode": 1599471906,
    "instancesWithErrorCount": 25,
    "processes": [
      {
        "processId": "2251799813697721",
        "version": 3,
        "name": null,
        "bpmnProcessId": "complexProcess",
        "tenantId": "<default>",
        "errorMessage": "Expected result of the expression ' list contains(flows,\"2\")' to be 'BOOLEAN', but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'flows'\n[FUNCTION_INVOCATION_FAILURE] Failed to invoke function 'list contains': Illegal arguments: 'null', '\"2\"'",
        "instancesWithActiveIncidentsCount": 25,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Expected result of the expression 'approverGroups' to be 'ARRAY', but was 'NULL'.",
    "incidentErrorHashCode": 1372322812,
    "instancesWithErrorCount": 16,
    "processes": [
      {
        "processId": "2251799813689091",
        "version": 1,
        "name": "DMN invoice",
        "bpmnProcessId": "invoice",
        "tenantId": "<default>",
        "errorMessage": "Expected result of the expression 'approverGroups' to be 'ARRAY', but was 'NULL'.",
        "instancesWithActiveIncidentsCount": 16,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Expected to evaluate decision 'decision-a', but Assertion failure on evaluate the expression 'assert(0,1)': The condition is not fulfilled",
    "incidentErrorHashCode": 1916097228,
    "instancesWithErrorCount": 16,
    "processes": [
      {
        "processId": "2251799813689141",
        "version": 1,
        "name": "Process with root cause decision",
        "bpmnProcessId": "Process_rootCauseDecision",
        "tenantId": "<default>",
        "errorMessage": "Expected to evaluate decision 'decision-a', but Assertion failure on evaluate the expression 'assert(0,1)': The condition is not fulfilled",
        "instancesWithActiveIncidentsCount": 16,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Assertion failure on evaluate the expression 'assert(false, \"Expression evaluation failed\")': The condition is not fulfilled The evaluation reported the following warnings:\n[ASSERT_FAILURE] The condition is not fulfilled",
    "incidentErrorHashCode": -1320329926,
    "instancesWithErrorCount": 15,
    "processes": [
      {
        "processId": "2251799813689154",
        "version": 1,
        "name": "Process with elements incidents",
        "bpmnProcessId": "incidents-process",
        "tenantId": "<default>",
        "errorMessage": "Assertion failure on evaluate the expression 'assert(false, \"Expression evaluation failed\")': The condition is not fulfilled The evaluation reported the following warnings:\n[ASSERT_FAILURE] The condition is not fulfilled",
        "instancesWithActiveIncidentsCount": 15,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Assertion failure on evaluate the expression '{result:assert(false, \"IO mapping failed\")}': The condition is not fulfilled The evaluation reported the following warnings:\n[ASSERT_FAILURE] The condition is not fulfilled",
    "incidentErrorHashCode": 443438159,
    "instancesWithErrorCount": 15,
    "processes": [
      {
        "processId": "2251799813689154",
        "version": 1,
        "name": "Process with elements incidents",
        "bpmnProcessId": "incidents-process",
        "tenantId": "<default>",
        "errorMessage": "Assertion failure on evaluate the expression '{result:assert(false, \"IO mapping failed\")}': The condition is not fulfilled The evaluation reported the following warnings:\n[ASSERT_FAILURE] The condition is not fulfilled",
        "instancesWithActiveIncidentsCount": 15,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Expected process with BPMN process id 'called-process' to be deployed, but not found.",
    "incidentErrorHashCode": 1117563109,
    "instancesWithErrorCount": 15,
    "processes": [
      {
        "processId": "2251799813689106",
        "version": 1,
        "name": "Call Activity Process",
        "bpmnProcessId": "call-activity-process",
        "tenantId": "<default>",
        "errorMessage": "Expected process with BPMN process id 'called-process' to be deployed, but not found.",
        "instancesWithActiveIncidentsCount": 15,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Expected to evaluate decision 'decision-a-called', but Assertion failure on evaluate the expression 'assert(0,1)': The condition is not fulfilled",
    "incidentErrorHashCode": 1965156924,
    "instancesWithErrorCount": 15,
    "processes": [
      {
        "processId": "2251799813689154",
        "version": 1,
        "name": "Process with elements incidents",
        "bpmnProcessId": "incidents-process",
        "tenantId": "<default>",
        "errorMessage": "Expected to evaluate decision 'decision-a-called', but Assertion failure on evaluate the expression 'assert(0,1)': The condition is not fulfilled",
        "instancesWithActiveIncidentsCount": 15,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Expected to throw an error event with the code 'end', but it was not caught. No error events are available in the scope.",
    "incidentErrorHashCode": -1142220660,
    "instancesWithErrorCount": 15,
    "processes": [
      {
        "processId": "2251799813689114",
        "version": 1,
        "name": null,
        "bpmnProcessId": "error-end-process",
        "tenantId": "<default>",
        "errorMessage": "Expected to throw an error event with the code 'end', but it was not caught. No error events are available in the scope.",
        "instancesWithActiveIncidentsCount": 15,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "No space left on device.",
    "incidentErrorHashCode": -601262857,
    "instancesWithErrorCount": 4,
    "processes": [
      {
        "processId": "2251799813687932",
        "version": 2,
        "name": "Only Incidents Process",
        "bpmnProcessId": "onlyIncidentsProcess",
        "tenantId": "<default>",
        "errorMessage": "No space left on device.",
        "instancesWithActiveIncidentsCount": 4,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Cannot connect to server delivery05",
    "incidentErrorHashCode": -539263260,
    "instancesWithErrorCount": 2,
    "processes": [
      {
        "processId": "2251799813689075",
        "version": 2,
        "name": "Order process",
        "bpmnProcessId": "orderProcess",
        "tenantId": "<default>",
        "errorMessage": "Cannot connect to server delivery05",
        "instancesWithActiveIncidentsCount": 2,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Cannot connect to server fly-host",
    "incidentErrorHashCode": -524590227,
    "instancesWithErrorCount": 1,
    "processes": [
      {
        "processId": "2251799813694918",
        "version": 3,
        "name": "Flight registration",
        "bpmnProcessId": "flightRegistration",
        "tenantId": "<default>",
        "errorMessage": "Cannot connect to server fly-host",
        "instancesWithActiveIncidentsCount": 1,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "No memory left.",
    "incidentErrorHashCode": -234272505,
    "instancesWithErrorCount": 1,
    "processes": [
      {
        "processId": "2251799813685374",
        "version": 1,
        "name": "Only Incidents Process",
        "bpmnProcessId": "onlyIncidentsProcess",
        "tenantId": "<default>",
        "errorMessage": "No memory left.",
        "instancesWithActiveIncidentsCount": 1,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Order information is not complete",
    "incidentErrorHashCode": 983975478,
    "instancesWithErrorCount": 1,
    "processes": [
      {
        "processId": "2251799813689075",
        "version": 2,
        "name": "Order process",
        "bpmnProcessId": "orderProcess",
        "tenantId": "<default>",
        "errorMessage": "Order information is not complete",
        "instancesWithActiveIncidentsCount": 1,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "error",
    "incidentErrorHashCode": 96784904,
    "instancesWithErrorCount": 1,
    "processes": [
      {
        "processId": "2251799813689102",
        "version": 1,
        "name": null,
        "bpmnProcessId": "nonInterruptingBoundaryEvent",
        "tenantId": "<default>",
        "errorMessage": "error",
        "instancesWithActiveIncidentsCount": 1,
        "activeInstancesCount": 0
      }
    ]
  }
]
```

**Overriden env var:** 

`CAMUNDA_OPERATE_MAX_INCIDENT_SEARCH_GROUPS` set to `2`

Screenshot 2026-02-04 at 16 01 12


```GET http://localhost:8080/api/incidents/byError```

```
[
  {
    "errorMessage": "Expected process with BPMN process id 'call-level-3-process' to be deployed, but not found.",
    "incidentErrorHashCode": -1525158685,
    "instancesWithErrorCount": 45,
    "processes": [
      {
        "processId": "2251799813689147",
        "version": 1,
        "name": "Call Level 2 Process",
        "bpmnProcessId": "call-level-2-process",
        "tenantId": "<default>",
        "errorMessage": "Expected process with BPMN process id 'call-level-3-process' to be deployed, but not found.",
        "instancesWithActiveIncidentsCount": 30,
        "activeInstancesCount": 0
      },
      {
        "processId": "2251799813689154",
        "version": 1,
        "name": "Process with elements incidents",
        "bpmnProcessId": "incidents-process",
        "tenantId": "<default>",
        "errorMessage": "Expected process with BPMN process id 'call-level-3-process' to be deployed, but not found.",
        "instancesWithActiveIncidentsCount": 15,
        "activeInstancesCount": 0
      }
    ]
  },
  {
    "errorMessage": "Failed to extract the correlation key for 'clientId': The value must be either a string or a number, but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'clientId'",
    "incidentErrorHashCode": 746263669,
    "instancesWithErrorCount": 45,
    "processes": [
      {
        "processId": "2251799813697721",
        "version": 3,
        "name": null,
        "bpmnProcessId": "complexProcess",
        "tenantId": "<default>",
        "errorMessage": "Failed to extract the correlation key for 'clientId': The value must be either a string or a number, but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'clientId'",
        "instancesWithActiveIncidentsCount": 25,
        "activeInstancesCount": 0
      },
      {
        "processId": "2251799813694931",
        "version": 2,
        "name": "Event based gateway with timer start",
        "bpmnProcessId": "eventBasedGatewayProcess",
        "tenantId": "<default>",
        "errorMessage": "Failed to extract the correlation key for 'clientId': The value must be either a string or a number, but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name 'clientId'",
        "instancesWithActiveIncidentsCount": 20,
        "activeInstancesCount": 0
      }
    ]
  }
]
```

File: operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java [hunk 1]
```diff
@@ -18,9 +18,15 @@ public class OperateProperties {
...
 
   public static final long BATCH_OPERATION_MAX_SIZE_DEFAULT = 1_000_000L;
-
   private static final String UNKNOWN_VERSION = "unknown-version";
 
+  /**
+   * Maximum number of groups to request from Elasticsearch when searching incidents by error
+   * message.
+   */
+  @Value("${camunda.operate.max-incident-search-groups:1000}")
```
Comment (RomanJRW) [inline operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: ❓ Is this copilot or do you need it for some reason?

**Review by RomanJRW — CHANGES_REQUESTED** [review]
Can we add a test for this to make sure that it's limited as expected? I think it would be in `IncidentStatisticsIT`

File: operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java (hunk 1 above)
Comment (lev-safro) [reply operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: Not sure that I fully got your comment.

We need this property to be able to override this default value of `1000` via env variable.

Comment (RomanJRW) [reply operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: I mean the annotation specifically. This is a `@ConfigurationProperties` class so the `@Value` annotation isn't needed. You can see on pretty much all the other properties here that it's the same

Comment (lev-safro) [reply operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: Ahhhh, I see.

It took me some time to understand where it get's [initialized](https://github.com/camunda/camunda/blob/fix/44596-limit-incidents-api-response/configuration/src/main/java/io/camunda/configuration/beanoverrides/OperatePropertiesOverride.java#L48-L50) :)

This part was a bit unexpected:
```
final OperateProperties override = new OperateProperties();
BeanUtils.copyProperties(legacyOperateProperties, override);
```

I'll fix that. For the testing part - I'm looking into it - it's a bit trickier then to write these couple of lines for the incident fix because we need to manipulate env variables and when SpringContext is already loaded it's a bit to late. Tried several approaches but no easy solution so far. Let's see, if nothing works - I'll probably mock this part:

`operateProperties.getMaxIncidentSearchGroups();`

Comment (RomanJRW) [reply operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: yeah it's not clear, and it's actually the subclass that is loaded with the annotation rather than `OperateProperties` itself 🙃

File: operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java [hunk 2]
```diff
@@ -18,9 +18,10 @@ public class OperateProperties {
   public static final String PREFIX = "camunda.operate";
 
   public static final long BATCH_OPERATION_MAX_SIZE_DEFAULT = 1_000_000L;
-
   private static final String UNKNOWN_VERSION = "unknown-version";
 
+  private int maxIncidentSearchGroups = 1000;
```
Comment (tsedekey) [inline operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: ❓ Would changing the default from 10,000 to 1,000 effectively alter the existing behaviour for all clients? Previously, users could retrieve up to 10,000 incident error messages without any configuration.
My concern is that this may unintentionally impact existing users who rely on the higher default and don’t suffer from large error payloads. My expectation would be:
	•	Keep the default at 10,000 to preserve current behaviour
	•	Allow customers with very large error messages (e.g. stack traces) to opt in to a lower limit via configuration. That way, the change is additive and targeted rather than globally restrictive.

File: operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/reader/IncidentStatisticsReader.java [hunk 3]
```diff
@@ -114,7 +119,7 @@ public Set<IncidentsByErrorMsgStatisticsDto> getIncidentStatisticsByError() {
             .subAggregation(
                 terms(GROUP_BY_PROCESS_KEYS)
                     .field(IncidentTemplate.PROCESS_DEFINITION_KEY)
-                    .size(ElasticsearchUtil.TERMS_AGG_SIZE)
+                    .size(termsAggSize)
                     .subAggregation(
                         cardinality(UNIQ_PROCESS_INSTANCES)
                             .field(IncidentTemplate.PROCESS_INSTANCE_KEY)));
```
[the remark this answers is not in the document]
Comment (tsedekey) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/reader/IncidentStatisticsReader.java:125]: 💭 I think this a valid suggestion from Copilot and the same changes should be applied to OpenSearch for parity.

**Review by tsedekey — CHANGES_REQUESTED** [review]
Implementation looks good! 👍  Just a couple of questions and suggestions. I think the changes should also apply to OpenSearch for parity.

File: operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java (hunk 2 above)
Comment (lev-safro) [reply operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: That's my understanding as well. 
I took the inspiration from our discussion in the incident channel.
@RomanJRW what do you think? Should we change the `default` for everybody from `10k` to `1k`? Or should we keep it as is and only introduce the property for customers to update that limit to the lower option?

Comment (RomanJRW) [reply operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: Oh I missed this, we should not change the default no. I think this should be considered to be a kind of hidden config for just <8.9 versions. Most customers never ran into this trouble so let's leave at 10k, and we apply it for this customer as part of a cluster modification

Comment (lev-safro) [reply operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: @RomanJRW 
So to be clear here: **we don't change the default values, only adding a possibility to modify it** via ENV Variables, correct?

Comment (RomanJRW) [reply operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java]: - We add a configuration property, with it's default set to whatever the implicit value was before (i.e. 10k). Spring Boot means that this new property is modifiable by env var
- In SaaS, for this particularly cluster, we add a cluster modification using that env var to reduce this value to something more reasonable (maybe 1k?)

Does that make sense? We can also pair this if you haven't done things like cluster modifications before 🙂

**Review by tsedekey — APPROVED** [review]

File: operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java [hunk 4]
```diff
@@ -18,9 +18,19 @@ public class OperateProperties {
...
 
+  /**
+   * Maximum number of groups to search for when searching for incidents. For the backward
+   * compatibility reasons, the default value is set to 10000, which is the default value for the
+   * maxClauseCount in Elasticsearch. We must keep it as 10000 to keep the behavior unchanged for
+   * the users.
+   *
+   * @see
+   *     io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.TERMS_AGG_SIZE
+   */
```
Comment (RomanJRW) [inline operate/common/src/main/java/io/camunda/operate/property/OperateProperties.java:27]: 🔧 nitpick: but this comment talks about ES, and then references an OpenSearch constant. It would be clearer to make this generic and then either reference both or neither of the default size constants

File: operate/qa/integration-tests/src/test/java/io/camunda/operate/elasticsearch/IncidentStatisticsIT.java [hunk 5]
```diff
@@ -70,6 +73,8 @@ public void setup() {
         .thenReturn(PermissionsService.ResourcesAllowed.wildcard());
     when(permissionsService.getProcessesWithPermission(PermissionType.READ_PROCESS_DEFINITION))
         .thenReturn(PermissionsService.ResourcesAllowed.wildcard());
+    // Default behavior for operate properties, can be overridden in specific tests
```
Comment (RomanJRW) [inline operate/qa/integration-tests/src/test/java/io/camunda/operate/elasticsearch/IncidentStatisticsIT.java:76]: 🔧 This comment feels inverted, as you are doing the overriding here rather than setting the default

**Review by RomanJRW — APPROVED** [review]
LGTM and thanks for taking this - just a couple of minor non-blocking comments 👍
