### PR TITLE
fix: fix Stackdriver not being able to output JSON for Optimize

### LINKED ISSUE #45223: Optimize cannot output JSON logs with Stackdriver
### 

### 

### 

### 

### Description

Following the docs [here](https://docs.camunda.io/docs/self-managed/components/optimize/configuration/logging/) we expected to be able to see Optimize output logs in JSON but this is not the behaviour we are seeing. 

### Steps to reproduce

1. Follow the instructions in https://docs.camunda.io/docs/self-managed/components/optimize/configuration/logging/
2. start Optimize
3. check the Optimize logs in stdout

### Current behavior

The Optimize logs show the message

> main ERROR Console contains an invalid element or attribute "StackdriverLayout"

The logs are also not in JSON

### Expected behavior

The stdout logs appear in JSON format

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- 8.8
- 8.9

### Rootcause

The root cause of this issue is due to the removal of the `StackdriverLayout` Java implementation in [#35622](https://github.com/camunda/camunda/pull/35622). After the removal of the layout, the Optimize logging configuration was not amended with the new Stackdriver setup.

### Solution ideas

Migrate to a the `JsonTemplateLayout` as used in [#35622](https://github.com/camunda/camunda/pull/35622) for Optimize. 

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

- [Relevant incident](https://camunda.slack.com/archives/C0ABJH4PZC0)
- [Relevant post](https://camunda.slack.com/archives/C08NPPTEEHH/p1770232315610539) with a summary of the issue
- Related to: [SUPPORT-31115](https://jira.camunda.com/browse/SUPPORT-31115)
### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tanjinyi**
## Description

Fixes the configuration for `log4j2` where Optimize could not output JSON given the configuration as described in https://docs.camunda.io/docs/self-managed/components/optimize/configuration/logging/. There will need to be a follow-up task to clean up the `JSON_LOGGING` environment variable as that variable no longer exists.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #45223

### CODE REVIEW

**Comment by tanjinyi** [comment]
Note that the resolver classes are direct copies of the classes found in https://github.com/camunda/camunda/tree/main/dist/src/main/java/io/camunda/application/commons/logging.

File: optimize/backend/src/test/java/io/camunda/optimize/logging/OptimizeStackdriverLayoutTest.java [hunk 1]
```diff
@@ -0,0 +1,231 @@
...
+    assertMessageMatchesWithContext(expectedSeverity, null);
+  }
+
+  private void assertMessageMatchesWithContext(
+      final String expectedSeverity, final String expectedContext) {
+    final var message = appender.getEvents().getFirst();
+    final var jsonMessage = encodingAppender.getMessages().getFirst();
+
+    assertThat(jsonMessage)
+        .isEqualTo(
```
Comment (konstantinos-mylosis) [inline optimize/backend/src/test/java/io/camunda/optimize/logging/OptimizeStackdriverLayoutTest.java:162]: CI is failing on this test, probably due to a line break

**Review by konstantinos-mylosis — APPROVED** [review]
LGTM 👍 
Pre-approving

1. Please fix failing UT mentioned in my comment
2. Quick sync in [#prj-move-optimize-to-unified-release](https://camunda.slack.com/archives/C09PLKZG42H) since optimize release should be part of the unified release -- maybe keeping only `StackdriverResolver`, `StackdriverResolverFactory` and `StackdriverLayout.json`  in `/dist` are enough?!
3. Also please create a tech debt issue if needed for 
> There will need to be a follow-up task to clean up the JSON_LOGGING environment variable as that variable no longer exists.

File: optimize/backend/src/test/java/io/camunda/optimize/logging/OptimizeStackdriverLayoutTest.java (hunk 1 above)
Comment (tanjinyi) [reply optimize/backend/src/test/java/io/camunda/optimize/logging/OptimizeStackdriverLayoutTest.java:162]: thanks, somehow the indentation messed up on the string blocks

**Comment by tanjinyi** [comment]
> LGTM 👍 Pre-approving
> 
> 1. Please fix failing UT mentioned in my comment
> 2. Quick sync in [#prj-move-optimize-to-unified-release](https://camunda.slack.com/archives/C09PLKZG42H) since optimize release should be part of the unified release -- maybe keeping only `StackdriverResolver`, `StackdriverResolverFactory` and `StackdriverLayout.json`  in `/dist` are enough?!
> 3. Also please create a tech debt issue if needed for
> 
> > There will need to be a follow-up task to clean up the JSON_LOGGING environment variable as that variable no longer exists.

Unfortunately, the `StackdriverLayout.json` is not accessible through `/dist` even though Optimize is part of the unified release. I'll ping the channel as a heads up.
