### PR TITLE
Fix notification of snapshot replication listeners about missed events

### LINKED ISSUE #8978: Partition without leader where all brokers are listed as followers
**Describe the bug**

According to the heap dump, in the Raft layer, `Broker 1` is leader for partition 2:
image

But when checking the cluster state with `zbctl`, there isn't any leader for partition 2, instead, all brokers are listed as followers:
```
Cluster size: 4
Partitions count: 4
Replication factor: 4
Gateway version: 1.3.5
Brokers:
  Broker 0
    Version: 1.3.5
    Partition 2 : Follower, Healthy
  Broker 1
    Version: 1.3.5
    Partition 2 : Follower, Healthy
  Broker 2
    Version: 1.3.5
    Partition 2 : Follower, Healthy
  Broker 3
    Version: 1.3.5
    Partition 2 : Follower, Healthy
```

According to the logs, on Broker 1 the `ZeebePartition` tried to transition to `LEADER` but that transition got canceled by a transition to `INACTIVE` followed up by a transition to `FOLLOWER`. So, as a result, the `ZeebePartition` ends up in the `FOLLOWER` role while in the Raft layer it is still in the `LEADER` role.

The following events happened which lead to the state:
1. During the bootstrap phase, a snapshot is received on partition 2
```
2022-03-24 09:47:58.934 [] [raft-server-1-raft-partition-partition-2] INFO 
      io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Started receiving new snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/1416-1-1595-1594-1, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@46da365a, metadata=FileBasedSnapshotMetadata{index=1416, term=1, processedPosition=1595, exporterPosition=1594}} from 2
2022-03-24 09:47:59.026 [Broker-1-SnapshotStore-2] [Broker-1-zb-fs-workers-0] INFO 
      io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 1416-1-1595-1594
```
2. Broker 1 starts an election and becomes leader for partition 2:
```
2022-03-24 10:28:42.856 [] [raft-server-1-raft-partition-partition-2] INFO 
      io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-2}{role=CANDIDATE} - Starting election
...
2022-03-24 10:28:42.868 [] [raft-server-1-raft-partition-partition-2] INFO 
      io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-2} - Transitioning to LEADER
```
3. Eventually, the server for partition 4 has been started successfully which triggers the start of the `ZeebePartition`s
```
2022-03-24 10:29:45.669 [] [raft-server-1-raft-partition-partition-4] INFO 
      io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-4} - Successfully started server for partition PartitionId{id=4, group=raft-partition} in 2509718ms
```
4. The registration of the `RoleChangeListener` and the `SnapshotReplicationListener` results in the following transitions:
```
2022-03-24 10:29:45.916 [Broker-1-ZeebePartition-2] [Broker-1-zb-actors-1] INFO 
      io.camunda.zeebe.broker.system - Transition to LEADER on term 4 requested.
2022-03-24 10:29:45.920 [Broker-1-ZeebePartition-2] [Broker-1-zb-actors-1] INFO 
      io.camunda.zeebe.broker.system - Transition to INACTIVE on term 0 requested.
2022-03-24 10:29:45.920 [Broker-1-ZeebePartition-2] [Broker-1-zb-actors-1] INFO 
      io.camunda.zeebe.broker.system - Received cancel signal for transition to LEADER on term 4
...
2022-03-24 10:29:45.928 [Broker-1-ZeebePartition-2] [Broker-1-zb-actors-1] INFO 
      io.camunda.zeebe.broker.system - Cancelling transition to INACTIVE on term 0
2022-03-24 10:29:45.928 [Broker-1-ZeebePartition-2] [Broker-1-zb-actors-1] INFO 
      io.camunda.zeebe.broker.system - Prepare transition from INACTIVE on term 0 to FOLLOWER
...
2022-03-24 10:29:47.718 [Broker-1-ZeebePartition-2] [Broker-1-zb-actors-1] INFO 
      io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 4 completed
```

The registration of the listeners happens in the following order:

https://github.com/camunda/zeebe/blob/41008dde419ba93115c8981fde36b807496d61e3/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java#L289-L293

This means it will submit three transitions in the `ZeebePartition`:
1. to `LEADER`,
2. to `INACTIVE`, and
3. to `FOLLOWER`

Transitions 2- and 3- are caused by the fact that at the beginning a snapshot was received:

https://github.com/camunda/zeebe/blob/41008dde419ba93115c8981fde36b807496d61e3/atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java#L472-L488

**Impact**
* Stream processor is not in processing mode, hence, nothing gets processed.
* Inflight process instances on that partition are "stuck" in the sense that any activatable job won't be activated.
* Incoming commands (requests) like create process instance, activate jobs, etc. will be dispatched between the other partitions.

**Expected behavior**

The `ZeebePartition` transitions to the `LEADER` role successfully.

**Possible Solutions:**
* ~~Change the order in which the listeners are registered, for instance, register first the `SnapshotReplicationListener` and then the `RoleChangeListener`.~~
* ~~Ensure that in `SnapshotReplicationListener#onSnapshotReplicationCompleted()` a transition is triggered to the previous role.~~

---

related to
* [SUPPORT-13302](https://jira.camunda.com/browse/SUPPORT-13302)
* (regression of) #8830
* #8852

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description
Whenever a raft partition transitions to a new role, we must reset `missedSnapshotReplicationEvents` so that registering new snapshot replication listeners does not trigger the listener for snapshot replication events that occurred for a different role.

This is to guard against a known case where raft received a snapshot and transitioned to leader before role change and snapshot replication listeners were registered. Once the registration of the snapshot replication listener registration went through, the listener was informed about the missed replication and caused the zeebe partition to transition to follower, while the raft partition was leader.

Additionally, because we keep track of missed snapshot replication events to notify listeners on registering, the partition is not necessarily in follower role at that point. This breaks the assumption of the listener, so we add a condition here to only trigger listeners on register if the raft partition is still follower.

## Related issues

relates to #8830
closes #8978

### CODE REVIEW

File: atomix/cluster/src/test/java/io/atomix/raft/SnapshotReplicationListenerTest.java [hunk 1]
```diff
@@ -100,4 +100,18 @@ public void shouldNotCallListenerOnRegister() {
     verify(snapshotReplicationListener, times(0))
         .onSnapshotReplicationCompleted(follower.getTerm());
   }
+
+  @Test
+  public void shouldNotCallListenerOnRegisterIfLeader() {
```
Comment (deepthidevaki) [inline atomix/cluster/src/test/java/io/atomix/raft/SnapshotReplicationListenerTest.java:105]: :thought_balloon: Can we test this with property based testing, using the infrastructure from `RandomizedRaftTest`? It might help us to find other race conditions, if there any. I don't have a concrete idea how it would look like. But might we worth considering.

**Review by deepthidevaki — APPROVED** [review]
:rocket: Thanks for the fast fix. Looks good to me. 

Please see my comment. It is not a blocker, but we can probably find some time to discuss it.

**Comment by deepthidevaki** [comment]
@oleschoenburg You may have to backport this to release branch as well.

**Comment by oleschoenburg** [comment]
@deepthidevaki Thanks, looks like you are right. I thought I merged just in time :sweat_smile: 

/backport
