### PR TITLE
Prevent NPE when terminating call activity

### LINKED ISSUE #10606: NPE during process instance modification
**Describe the bug**

```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=MODIFY, requestStreamId=1, requestId=37707, protocolVersion=3, valueType=PROCESS_INSTANCE_MODIFICATION, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.1.0}, value={"processInstanceKey":2251799813688377,"terminateInstructions":[{"elementInstanceKey":2251799813688383}],"activateInstructions":[{"elementId":"end","ancestorScopeKey":-1,"variableInstructions":[]}]}}' without errors, but exception occurred with message 'Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "elementInstance" is null'.
```

**To Reproduce**

Unclear, data (ie. models) is not accessible anymore.

**Expected behavior**

No NPE, if this is expected then we should throw a meaningful exception.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "elementInstance" is null
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.terminateElement(ProcessInstanceModificationProcessor.java:535) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.terminateElement(ProcessInstanceModificationProcessor.java:558) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.lambda$processRecord$3(ProcessInstanceModificationProcessor.java:203) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.processRecord(ProcessInstanceModificationProcessor.java:197) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:261) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:257) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:206) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:182) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2] 
```

</p>
</details>

Error group: https://console.cloud.google.com/errors/detail/CNSa-5ifjeT1Og?project=camunda-cloud-240911

**Environment:**
- Zeebe Version: 8.1.0-rc2

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

If a parent process has an active call activity element instance there is no guarantee that the called activity is still activate. When the called activity is completed it will try to complete the call activity element. At this point we try to apply the output mappings. If something goes wrong here an incident is created. When we try to terminate the call activity at this point the called activity is already completed and no instance of it will be available. For this reason we must verify that this instance is not null before we try to terminate it.

## Related issues

closes #10606 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java [hunk 1]
```diff
@@ -572,7 +572,9 @@ private void terminateElement(
     } else if (elementType == BpmnElementType.CALL_ACTIVITY) {
       final var calledActivityElementInstance =
           elementInstanceState.getInstance(elementInstance.getCalledChildInstanceKey());
-      terminateElement(calledActivityElementInstance, sideEffects);
+      if (calledActivityElementInstance != null) {
```
Comment (saig0) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java:575]: :wrench: We could apply the same check `.canTerminate()` as for the other child instances.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 2]
```diff
@@ -850,6 +851,48 @@ public void shouldActivateParallelGateway() {
...
+    ENGINE
+        .processInstance()
+        .withInstanceKey(processInstanceKey)
+        .modification()
+        .activateElement("task")
+        .terminateElement(callActivityElement.getKey())
+        .modify();
+
+    verifyThatRootElementIsActivated(processInstanceKey, "task", BpmnElementType.MANUAL_TASK);
+    verifyThatProcessInstanceIsCompleted(processInstanceKey);
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:893]: :wrench: Additionally, we could verify that the call activity is terminated.

**Review by saig0 — APPROVED** [review]
@remcowesterhoud looks good. :+1: 

I have two minor suggestions. Please have a look.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java (hunk 1 above)
Comment (saig0) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java:575]: Yes, we could add `canTerminate()` additionally to the null check. :sweat_smile:

**Review by saig0 — APPROVED** [review]

**Comment by remcowesterhoud** [comment]
bors merge

**Review by remcowesterhoud — COMMENTED** [review]
bors merge
