### PR TITLE
Fix flaky multipartition tests

### LINKED ISSUE #28129: MultiPartition engine tests are flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Very often
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

Image

The image above lists the flaky tests over the last week that are related to multi partition engine tests. Except for the `BackupMultiPartitionTest` these likely all have the same root-cause.

**Hypotheses**

We don't wait properly for the Identity setup to be completed when we have multiple partitions. An example of the logged records on a test failure:

```
3 E AUTHORIZATION  CREATED      - #15->#01 P3K13 - AuthorizationRecord {"ownerType":"ROLE","permissions":[],"ownerId":"2251799813685249","ownerKey":-1,"resourceId":"*","authorizationKey":-1,"resourceType":"USER","authorizationPermissions":["CREATE","UPDATE","DELETE","READ"]}
3 E AUTHORIZATION  CREATED      - #16->#01 P3K14 - AuthorizationRecord {"ownerType":"ROLE","permissions":[],"ownerId":"2251799813685249","ownerKey":-1,"resourceId":"*","authorizationKey":-1,"resourceType":"ROLE","authorizationPermissions":["CREATE","UPDATE","DELETE","READ"]}
2 E IDENTITY_SETUP INITIALIZED  - #18->#01 P1K17 - IdentitySetupRecord {"defaultRole":{"name":"Admin","entityKey":-1,"entityType":"UNSPECIFIED","roleKey":2251799813685249},"users":[],"mappings":[],"defaultTenant":{"name":"Default","tenantKey":2251799813685264,"description":"","entityKey":-1,"entityId":"","entityType":"UNSPECIFIED","tenantId":"<default>"}}
3 E TENANT         CREATED      - #17->#01 P1K16 - Tenant[Key=P1K16, Id="<default>", Name="Default", EntityKey=   -1, EntityId=""]
3 E IDENTITY_SETUP INITIALIZED  - #18->#01 P1K17 - IdentitySetupRecord {"defaultRole":{"name":"Admin","entityKey":-1,"entityType":"UNSPECIFIED","roleKey":2251799813685249},"users":[],"mappings":[],"defaultTenant":{"name":"Default","tenantKey":2251799813685264,"description":"","entityKey":-1,"entityId":"","entityType":"UNSPECIFIED","tenantId":"<default>"}}
1 C TENANT         CREATE       - #30-> -1    -1 - Tenant[Key=   -1, Id="tenant-123", Name="New Tenant", EntityKey=   -1, EntityId=""]
1 E TENANT         CREATED      - #31->#30 P1K18 - Tenant[Key=P1K18, Id="tenant-123", Name="New Tenant", EntityKey=   -1, EntityId=""]
1 E DSTR           STARTED      - #32->#30 P1K18 - TENANT CREATE on partition 1 on queue IDENTITY
1 E DSTR           ENQUEUED     - #33->#30 P1K18 - NULL_VAL UNKNOWN to partition 2 on queue IDENTITY
1 E DSTR           DISTRIBUTING - #34->#30 P1K18 - TENANT CREATE to partition 2 on queue null
1 E DSTR           ENQUEUED     - #35->#30 P1K18 - NULL_VAL UNKNOWN to partition 3 on queue IDENTITY
1 E DSTR           DISTRIBUTING - #36->#30 P1K18 - TENANT CREATE to partition 3 on queue null
2 C TENANT         CREATE       - #19-> -1 P1K18 - Tenant[Key=P1K18, Id="tenant-123", Name="New Tenant", EntityKey=   -1, EntityId=""]
3 C TENANT         CREATE       - #19-> -1 P1K18 - Tenant[Key=P1K18, Id="tenant-123", Name="New Tenant", EntityKey=   -1, EntityId=""]
2 E TENANT         CREATED      - #20->#19 P1K18 - Tenant[Key=P1K18, Id="tenant-123", Name="New Tenant", EntityKey=   -1, EntityId=""]
1 C DSTR           ACKNOWLEDGE  - #37-> -1 P1K18 - TENANT CREATE for partition 2 on queue null
3 E TENANT         CREATED      - #20->#19 P1K18 - Tenant[Key=P1K18, Id="tenant-123", Name="New Tenant", EntityKey=   -1, EntityId=""]
1 C DSTR           ACKNOWLEDGE  - #38-> -1 P1K18 - TENANT CREATE for partition 3 on queue null
1 E DSTR           ACKNOWLEDGED - #39->#37 P1K18 - TENANT CREATE for partition 2 on queue null
1 E DSTR           ACKNOWLEDGED - #40->#38 P1K18 - TENANT CREATE for partition 3 on queue null
1 C DSTR           FINISH       - #41->#38 P1K18 - TENANT CREATE on partition 1 on queue IDENTITY
1 E DSTR           FINISHED     - #42->#38 P1K18 - TENANT CREATE on partition 1 on queue IDENTITY
```

As we can see the first 5 records are related to the identity setup, even though the `EngineRule` is configured to wait for this setup to be completed.

We await for the setup with the following code:

```java
public void awaitIdentitySetup() {
    if (partitionCount > 1) {
      RecordingExporter.commandDistributionRecords(CommandDistributionIntent.FINISHED)
          .withDistributionIntent(IdentitySetupIntent.INITIALIZE)
          .await();
    } else {
      RecordingExporter.identitySetupRecords(IdentitySetupIntent.INITIALIZED).await();
    }
    RecordingExporter.reset();
  }
```

What's notable is that when we have multiple partitions we only wait for the distribution to be finished. This doesn't mean all partitions have exported all the processed event. As a result, when we reset the recording exporter there could still be events that need to be exported on the other partitions. This await needs to be changed so we no only verify the distribution finished, but also that the initialized event is exported on all partitions.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Fixes a number of flaky tests due to a bug in awaiting the identity setup. We were waiting for the distrinbution to be finished on partition 1. When there's multiple partitions we should also make sure we wait that the initialized events are exported.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #28129

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/CreateAuthorizationMultipartitionTest.java [hunk 1]
```diff
@@ -91,7 +94,8 @@ record ->
 
     for (int partitionId = 2; partitionId < PARTITION_COUNT; partitionId++) {
       assertThat(
-              RecordingExporter.records()
+              RecordingExporter.authorizationRecords()
+                  .withAuthorizationKey(authorizationKey)
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/CreateAuthorizationMultipartitionTest.java:98]: 👍 Nice!

**Review by korthout — APPROVED** [review]
Thanks @remcowesterhoud 

👍 I like that you spend some extra time to harden the other tests that are affected by this as well.

❓ How did you find those other cases? Did you use the flakytest dashboard? Or did you have some other way?

Either way, changes look good

LGTM 💯

**Comment by remcowesterhoud** [comment]
> ❓ How did you find those other cases? Did you use the flakytest dashboard? Or did you have some other way?

I looked into the flaky test dashboard which were the other flaky ones 😄
