### PR TITLE
Apply event sourcing to incident resolve/resolved

### LINKED ISSUE #6174: Apply event-sourcing to the incident processors
**Description**

* apply the event-sourcing concept to the incident processors

Reference:
* [ZEP: Incident](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#the-stream-processor#incident)

### LINKED ISSUE #6527: Inconsistent state on reprocessing of incident resolve records
**Describe the bug**
As part of https://github.com/camunda-cloud/zeebe/pull/6495 I discovered that we did not yet test for replay/reprocessing of incident resolution for non-job related incidents.

For example, the exclusive gateway processor has already been migrated to the event sourcing model and an incident can be raised on evaluation of the condition expression. This incident case is not tested for in the randomized replay state property test. 

So I created a randomized and an example-based test here https://github.com/camunda-cloud/zeebe/commit/bb45d6ab4ecd38d119244fcfcff2d2a4ef3b2efb, which fails.

**To Reproduce**
Run test in above commit

**Expected behavior**
Test should pass (on replay/reprocessing the state should lead to the same state as was achieved on processing)

exists on `1.0.0-alpha2`

### PR DESCRIPTION
**Pull request by korthout**
## Description

This PR is most easily reviewed by looking at the individual commits

Main points are:
- note that the first commit refactors the processor mainly to highlight the mutable state dependencies
- deletes incident from state on apply Incident:Resolved
- no longer needs the failed record to be stored in state
- adds a test case to the ReplayStateRandomizedPropertyTest for:
  - creating incident on evaluating condition expression
  - resolving this incident
- note that error thrown incidents cannot be resolved, no effort was taken to reimplement that logic

## Related issues

closes #6174
fixes #6527

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java [hunk 1]
```diff
@@ -91,12 +89,20 @@ private boolean tryRejectJobIncident(
...
+      // this fails MultiInstanceIncidentTest shouldCreateIncidentIfOutputElementExpre...
+      // because an incident raised in the container processor does not interrupt the processing of
+      // the child element's complete and results in deleting the child element instance (where the
+      // incident relates to). So it is also impossible to resolve this incident.
+      //      commandControl.reject(
+      //          RejectionType.NOT_FOUND,
+      //          String.format(
+      //          NO_ELEMENT_INSTANCE_MESSAGE,
+      //          elementInstanceKey
+      //      ));
```
Comment (korthout) [inline engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java:104]: I'll create an issue before merging this

**Comment by menski** [comment]
Hi @korthout and @Zelldon, I rebased this branch on the changes from PR #6453. I hope I resolved the merge conflicts correctly but please give it another look before merging. In case I mixed something up the commit before my force push was f695e95f4d5e26660c19f8b6d4aad146efa00045.

**Comment by korthout** [comment]
@menski Thanks for the rebase, it's much appreciated ❤️

File: engine/src/main/java/io/zeebe/engine/state/appliers/ProcessInstanceElementActivatedApplier.java [hunk 2]
```diff
@@ -7,58 +7,25 @@
...
-              value.getProcessDefinitionKey(),
-              value.getElementIdBuffer(),
-              ExecutableFlowElementContainer.class);
-
-      final var events = executableFlowElementContainer.getEvents();
-      if (!events.isEmpty()) {
-        eventScopeInstanceState.createIfNotExists(
-            key, executableFlowElementContainer.getInterruptingElementIds());
-      }
-    }
```
Comment (korthout) [inline engine/src/main/java/io/zeebe/engine/state/appliers/ProcessInstanceElementActivatedApplier.java:62]: Oops this shouldn't be removed. 😓

File: engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java (hunk 1 above)
Comment (korthout) [reply engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java:104]: @Zelldon, I read this comment again, ready to create the issue, but now I'm hesitant. 

This situation will be solved when stop processing `Incident:Create` altogether, since the incident can then be created on the processing of the command that actually wants to write the incident (already creating the incident before the child element is completed and removed from state).

However, that means that when we merge this this bug exists. Should I maybe remove processing of the Incident:Create in this PR?

File: engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java [hunk 3]
```diff
@@ -102,7 +94,8 @@ private void attemptToResolveIncident(
     final boolean isJobIncident = jobKey > 0;
 
     if (isJobIncident) {
-      attemptToSolveJobIncident(jobKey, streamWriter);
+      // todo (#6000): resolve incident for UNHANDLED_ERROR_EVENT
+      // at time of writing the workflow cannot be fixed, so this incident cannot be resolved
```
Comment (Zelldon) [inline engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java]: Maybe we add here a log statement?

File: engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java (hunk 1 above)
Comment (Zelldon) [reply engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java:104]: How big will this change be?

File: engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java [hunk 4]
```diff
@@ -97,28 +104,63 @@ private void attemptToResolveIncident(
...
+    getFailedCommand(incidentRecord)
+        .ifRightOrLeft(
+            failedCommand -> {
+              sideEffects.clear();
+              sideEffects.add(responseWriter::flush);
 
-      sideEffects.clear();
-      sideEffects.add(responseWriter::flush);
+              bpmnStreamProcessor.processRecord(
+                  failedCommand, noopResponseWriter, streamWriter, sideEffects::add);
```
Comment (Zelldon) [inline engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java:126]: Wouldn't this also mean that we can only migrated that if all bpmn stream processors which cause incidents are migrated?

**Review by ChrisKujawa — APPROVED** [review]
Thanks @korthout looks good :+1: I have just some questions

File: engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnIncidentBehavior.java [hunk 5]
```diff
@@ -67,41 +51,12 @@ private void createIncident(
...
-        String.format(
-            "Expected to raise incident, but element state %s not one of incident supporting states %s %s",
-            context.getIntent(),
-            ProcessInstanceIntent.ELEMENT_ACTIVATING,
-            ProcessInstanceIntent.ELEMENT_COMPLETING));
-  }
-
   public void resolveIncidents(final BpmnElementContext context) {
     incidentState.forExistingProcessIncident(
         context.getElementInstanceKey(),
```
Comment (Zelldon) [inline engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnIncidentBehavior.java:62]: I have seen during the sub process migration that it is used on terminating. Does it make sense here to use the state writer?

Comment (Zelldon) [reply engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnIncidentBehavior.java:62]: Do you want to do it here ? Or should I do it on my migration?

Comment (korthout) [reply engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnIncidentBehavior.java:62]: I'll have a look at this

File: engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java (hunk 4 above)
Comment (korthout) [reply engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java:126]: No, this is only executed on processing `Incident:Resolve`, so it is not reprocessed.

File: engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java (hunk 3 above)
Comment (korthout) [reply engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java]: Good idea

File: engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java (hunk 1 above)
Comment (korthout) [reply engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java:104]: I don't think its big, but I think it is dependent on having all other element processors (that can raise incidents) migrated. Now this PR already fixes a known replay bug, so perhaps we should just postpone this fix to later

File: engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java (hunk 4 above)
Comment (Zelldon) [reply engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java:126]: Ah because you already marked it as migrated right?

Comment (korthout) [reply engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java:126]: Yup, Incident records will be migrated, if on processing the resolve we produce records that have not been migrated yet, then those records are reprocessed as always

File: engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java (hunk 1 above)
Comment (korthout) [reply engine/src/main/java/io/zeebe/engine/processing/incident/CreateIncidentProcessor.java:104]: Created https://github.com/camunda-cloud/zeebe/issues/6546 (and removed this from the pr, because it in the future we wont reject this command anymore anyways because with #6528 we won't have a create command anymore)

File: engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java (hunk 3 above)
Comment (korthout) [reply engine/src/main/java/io/zeebe/engine/processing/incident/ResolveIncidentProcessor.java]: It now rejects the resolve command. No need to log anything. Just inform the client.

File: engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnIncidentBehavior.java (hunk 5 above)
Comment (korthout) [reply engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnIncidentBehavior.java:62]: I don't think that's should be part of this PR. Let's do it on the first element processor that needs that.

Comment (Zelldon) [reply engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnIncidentBehavior.java:62]: ok so sub processor :laughing:

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
bors retry

**Comment by korthout** [comment]
bors retry

**Comment by Zelldon** [comment]
I think there are some failing test cases

**Comment by korthout** [comment]
bors retry

**Comment by korthout** [comment]
It was a flaky IT

bors retry
