### PR TITLE
Retry on recoverable exceptions

### LINKED ISSUE #2169: Create new RuntimeException types in ZeebeDb
The new created exceptions types  should distingush between recoverable and non recoverable exceptions. This means the recoverable ones are wrapping the RocksDB exceptions and the non recoverable all other.

### LINKED ISSUE #2170: Create Recoverable interface for Exceptions in util

### PR DESCRIPTION
**Pull request by ChrisKujawa**
closes #2170 
closes #2169

### CODE REVIEW

File: logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java [hunk 1]
```diff
@@ -246,6 +249,10 @@ private void reprocessEvent(final LoggedEvent currentEvent) {
           try {
             // don't execute side effects or write events
             zeebeDb.transaction(eventProcessor::processEvent);
+          } catch (final RecoverableException recoverableException) {
+            // recoverable
```
Comment (npepinpe) [inline logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java]: I think logging the exception is useful here, since even if it succeeds on the next retry, it could indicate symptoms of intermittent failure.

File: logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java [hunk 2]
```diff
@@ -303,6 +310,9 @@ private void processEvent(final LoggedEvent event) {
           zeebeDb.transaction(eventProcessor::processEvent);
           metrics.incrementEventsProcessedCount();
           actor.runUntilDone(this::executeSideEffects);
+        } catch (final RecoverableException recoverableException) {
+          // recoverable
+          actor.runDelayed(PROCESSING_RETRY_DELAY, () -> processEvent(currentEvent));
```
Comment (npepinpe) [inline logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java]: Same as above

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java [hunk 3]
```diff
@@ -165,8 +167,11 @@ public void transaction(TransactionOperation operations) {
       } else {
         runInNewTransaction(operations);
       }
+    } catch (RocksDBException rdbex) {
+      throw new ZeebeDbException("Unexpected error occurred during RocksDB transaction.", rdbex);
     } catch (Exception ex) {
-      throw new RuntimeException("Unexpected error occurred during RocksDB transaction.", ex);
+      throw new ZeebeDbOperationException(
```
Comment (npepinpe) [inline zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java]: I don't get why we are catching `Exception` here; the only checked exception is `RocksDBException` which we handle, why not just let this one bubble up? I guess this is a little outside the scope of the issue though.

File: util/src/main/java/io/zeebe/util/exception/NonRecoverableException.java [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.zeebe.util.exception;
+
+/**
+ * A non recoverable exception should wrap any exception, where it makes no sense to apply any retry
+ * strategy.
+ */
+public class NonRecoverableException extends RuntimeException {
```
Comment (npepinpe) [inline util/src/main/java/io/zeebe/util/exception/NonRecoverableException.java]: Aren't all exceptions which are not `RecoverableException` non-recoverable exceptions? What is the advantage of an explicit type here? If we have both `NonRecoverableException` and `RecoverableException`, what does that make exception types that don't derive from either?

**Review by npepinpe — CHANGES_REQUESTED** [review]
I like the general concept. Maybe we can discuss some points f2f before doing the profiling stuff.

File: logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java (hunk 1 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java]: Yeah was not sure, since we then spam the log :sweat_smile: but we could do on debug or trace level

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java (hunk 3 above)
Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java]: Because the transaction operation could throw exceptions

File: util/src/main/java/io/zeebe/util/exception/NonRecoverableException.java (hunk 4 above)
Comment (Zelldon) [reply util/src/main/java/io/zeebe/util/exception/NonRecoverableException.java]: Yes was also not sure about that specific type, we can also simply remove it

File: zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java (hunk 3 above)
Comment (npepinpe) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java]: I still don't get what's the advantage of wrapping the exception :sweat_smile:

Comment (Zelldon) [reply zb-db/src/main/java/io/zeebe/db/impl/rocksdb/transaction/ZeebeTransactionDb.java]: Nothing just be more explicit can also be runtime exception again

**Comment by Zelldon** [comment]
@npepinpe please have a look

**Comment by Zelldon** [comment]
That is awesome that LGTM found that :+1: I think I fixed it

**Review by npepinpe — APPROVED** [review]
:+1: 

Next steps would be to identify what we consider recoverable errors. Maybe some RocksDB exceptions are not recoverable? Maybe a follow up issue at least to identify which RocksDB exceptions are/aren't recoverable. As for other types of exceptions, I guess we should add them as we go.

**Comment by Zelldon** [comment]
> Next steps would be to identify what we consider recoverable errors. Maybe some RocksDB exceptions are not recoverable? Maybe a follow up issue at least to identify which RocksDB exceptions are/aren't recoverable. As for other types of exceptions, I guess we should add them as we go.

Yes I thought the same. I will create then a follow up issue.

**Comment by Zelldon** [comment]
Created an issue https://github.com/zeebe-io/zeebe/issues/2188

**Comment by Zelldon** [comment]
Bors r+
