### PR TITLE
fix: match historic/rollover indices correctly

### LINKED ISSUE #25810: Index name: task. Not supported index changes are introduced. Data migration is required.
**Describe the bug**

https://console.cloud.google.com/errors/detail/CI6Ujunh37jOAQ;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjvZQ&project=camunda-saas-int-chaos

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

**Environment:**
- OS: 
- Zeebe Version: 8.7.0-SNAPSHOT
- Configuration:

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR matches the rollover indices correctly, ensuring that lifecycle policies are _only_ applied to the rollover indices and nothing else.

This fix improves the test coverage by testing when we have no global prefix, and when there is one defined, and adding cases such as when there is another index with a different prefix, or when there is no historic suffix.

> [!Note]
> When there is no global prefix, we cannot properly test the case where the DB would be shared, meaning you have one app with a prefix, and one without, and we should apply the policy only to the one without. This is because we match names with a regex, and since index names may contain multiple separators `-`, we can't differentiate between `prefix-name-version_` and `name-with-separator-version_` (i.e. no prefix).

## Related issues

closes #25810

### CODE REVIEW

**Comment by npepinpe** [comment]
Added both @megglos and @rodrigo-lourenco-lopes as reviewers - I assume @megglos is more focused on the release so will review this sooner, in which case I'd still like @rodrigo-lourenco-lopes to review this to learn.

**Comment by npepinpe** [comment]
FYI, Operate E2E tests also fail in other PRs and on main with similar failures

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java [hunk 1]
```diff
@@ -50,7 +51,7 @@ public final class ElasticsearchArchiverRepository implements ArchiverRepository
   private static final String INSTANCES_AGG = "instancesAgg";
   private static final String DATES_SORTED_AGG = "datesSortedAgg";
   private static final String ALL_INDICES = "*";
-  private static final String INDEX_WILDCARD = "-.*-\\d+\\.\\d+\\.\\d+_.+$";
+  private static final String INDEX_WILDCARD = ".+-\\d+\\.\\d+\\.\\d+_.+$";
```
Comment (megglos) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:54]: ❓ `.+` is matching the component name, right?

**Review by megglos — APPROVED** [review]
LGTM! Thanks for fixing this!

❓ One follow-up question as I didn't dig deeper, do we also support disabling ILM after it was enabled once? From what I currently see the `SchemaManager` creates the policy and we apply it via the archiver. If disabled it would just stay effective though?

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java (hunk 1 above)
Comment (npepinpe) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:54]: Exactly, we always have a component name at least.

**Comment by npepinpe** [comment]
> ❓ One follow-up question as I didn't dig deeper, do we also support disabling ILM after it was enabled once? From what I currently see the `SchemaManager` creates the policy and we apply it via the archiver. If disabled it would just stay effective though?

Yes, this is a limitation with pre 8.7.0 as well, but we're just maintaining the status quo for now (i.e. feature parity). There are other potentially breaking configuration changes (e.g. changing the rollover suffix for example) which are already problems pre 8.7 as well.
