### PR TITLE
fix: re-install MigrationSnapshotDirector on each role transition

### LINKED ISSUE #37234: MigrationSnapshotDirector should be closed and re-installed during role changes
### 

### 

### 

### 

### Description

Currently `MigrationSnapshotDirector` is only installed once and reused after role changes. This is not correct, because it depends on `AsyncSnapshotDirector` which will be re-installed during role transitions. As a result the migration director might be using an already closed AsyncSnapshotDirector to take snapshot. 

### Current behavior

This was observed in some flaky tests where there were fast role transitions before `MigrationSnapshotDirector` became healthy. As a result it never became healthy in the new role because it cannot take a new snapshot anymore.

### Version

- 8.8-SNAPSHOT (and 8.8-0-alpha8)

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

`MigrationSnapshotDirector` needs to be re-installed on role changes, because otherwise it might be using an already closed `AsyncSnapshotDirector`.  This leads to the partition remain in unhealthy state as the migration snapshot director cannot take a snapshot anymore.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #37234

### CODE REVIEW

**Review by ChrisKujawa — COMMENTED** [review]
I haven't looked at the changes, but I have a general question why this is necessary? 

Shouldn't the MigrationSnapshotDirector only needed after Migration? Means on bootstrap we do migration and then take a snapshot? Why we need this on every transition? I might miss something here?

**Comment by deepthidevaki** [comment]
> I haven't looked at the changes, but I have a general question why this is necessary?
> 
> Shouldn't the MigrationSnapshotDirector only needed after Migration? Means on bootstrap we do migration and then take a snapshot? Why we need this on every transition? I might miss something here?

Sorry. My explanation is not clear. 

There is already a check that skips the installation if there was no migration. But what happens in the failure case is as follows:
1. Migration is executed
2. MigrationSnapshotDirector is installed -> Starts as unhealthy -> Snapshot is not yet taken
3. Role changes
4. AsyncSnapshotDirector closed and re-installed
5. MigrationSnapshotDirector is NOT closed and so not re-installed -> It remains unhealthy. It cannot become healthy because it cannot take snapshot because it has reference to the old AsyncSnapshotDirector from the old role. The partition remains unhealthy.

This PR fixes this by closing the `MigrationSnapshotDirector` at step 3. So that is it is either re-installed at step 5, or skip the installation if there was no migration done.

**Comment by ChrisKujawa** [comment]
Thanks @deepthidevaki this helps

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotAfterMigrationTransitionStep.java [hunk 1]
```diff
@@ -22,7 +22,7 @@ public class SnapshotAfterMigrationTransitionStep implements PartitionTransition
   @Override
   public ActorFuture<Void> prepareTransition(
       final PartitionTransitionContext context, final long term, final Role targetRole) {
-    if (targetRole == Role.INACTIVE & migrationSnapshotDirector != null) {
```
Comment (ChrisKujawa) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotAfterMigrationTransitionStep.java:25]: 🙃 Also interesting that we used a bit-wise and `&`

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotMigrationTransitionStepTest.java [hunk 2]
```diff
@@ -159,29 +160,6 @@ public void shouldNotScheduleASnapshotWhenNoMigrationWasPerformed(final Role rol
     verify(snapshotDirector, times(0)).forceSnapshot();
   }
 
-  @ParameterizedTest
-  @EnumSource(
-      value = Role.class,
-      mode = Mode.EXCLUDE,
-      names = {"INACTIVE"})
-  public void shouldNotScheduleASnapshotAfterItsDoneInAPreviousTransition(final Role role) {
```
Comment (ChrisKujawa) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotMigrationTransitionStepTest.java:167]: ❓ Can we somehow reproduce that the first installation doesnt work? Can we inject somehow a failure? Were you able to reproduce this somehow?

**Review by ChrisKujawa — APPROVED** [review]
Thanks @deepthidevaki the second description helped a lot 👍🏼 

Would be good to have a test for this.

**Comment by deepthidevaki** [comment]
Oops. Forgot about this PR.

**Comment by deepthidevaki** [comment]
> Would be good to have a test for this.

No. I couldn't find a deterministic way to reproduce this. The timing of migration, snapshot and role change has to align to reproduce this.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotMigrationTransitionStepTest.java (hunk 2 above)
Comment (deepthidevaki) [reply zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotMigrationTransitionStepTest.java:167]: Since we are re-installing on new role, this test do not make sense anymore. That's why it is removed. 

Also, since we are re-installing which will take a snapshot anyway, there is not much value in verifying the first installation does not work in the context of this unit test.
