### PR TITLE
Fix: batch operation memory safety issue with scheduled task

### LINKED ISSUE #30536: Do not use `KeyGenerator` in scheduled task
**Describe the bug**

According to the comments in the [slack thread](https://camunda.slack.com/archives/C05DH1F5TAR/p1743605166704629), `KeyGenerator` writes to the state which is forbidden in scheduled tasks. It introduces a memory leak.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Current thread (0x00007f644c520400):  JavaThread "zb-actors-1" daemon [_thread_in_native, id=113725, stack(0x00007f6407500000,0x00007f6407600000) (1024K)]

Stack: [0x00007f6407500000,0x00007f6407600000],  sp=0x00007f64075fe268,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007f6320000480
C  [librocksdbjni4141218812818420804.so+0x91d080]  rocksdb::OptimisticTransaction::Reinitialize(rocksdb::OptimisticTransactionDB*, rocksdb::WriteOptions const&, rocksdb::OptimisticTransactionOptions const&)+0x30
C  [librocksdbjni4141218812818420804.so+0x91e4d4]  rocksdb::OptimisticTransactionDBImpl::BeginTransaction(rocksdb::WriteOptions const&, rocksdb::OptimisticTransactionOptions const&, rocksdb::Transaction*)+0x24
C  [librocksdbjni4141218812818420804.so+0x30b219]  Java_org_rocksdb_OptimisticTransactionDB_beginTransaction_1withOld__JJJ+0x39
J 4156  org.rocksdb.OptimisticTransactionDB.beginTransaction_withOld(JJJ)J (0 bytes) @ 0x00007f6538516bfd [0x00007f6538516b20+0x00000000000000dd]
J 27607 c2 io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.resetTransaction()V (23 bytes) @ 0x00007f65396711cc [0x00007f6539671140+0x000000000000008c]
J 21428 c2 io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(Lio/camunda/zeebe/db/TransactionOperation;)V (77 bytes) @ 0x00007f653925b6a8 [0x00007f653925b640+0x0000000000000068]
J 28988 c1 io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEach(Ljava/util/function/BiConsumer;)V (12 bytes) @ 0x00007f65333b9dec [0x00007f65333b9580+0x000000000000086c]
j  io.camunda.zeebe.engine.state.distribution.DbDistributionState.foreachRetriableDistribution(Lio/camunda/zeebe/engine/state/immutable/DistributionState$PendingDistributionVisitor;)V+30
j  io.camunda.zeebe.engine.processing.distribution.CommandRedistributor.runRetryCycle()V+19
j  io.camunda.zeebe.engine.processing.distribution.CommandRedistributor$$Lambda+0x00007f64c470a938.run()V+4
j  io.camunda.zeebe.stream.api.scheduling.SimpleProcessingScheduleService.lambda$runAtFixedRate$0(Ljava/lang/Runnable;Ljava/time/Duration;)V+1
j  io.camunda.zeebe.stream.api.scheduling.SimpleProcessingScheduleService$$Lambda+0x00007f64c4706440.run()V+12
j  io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl$ScheduledTaskImpl.run()V+35
J 16104 c2 io.camunda.zeebe.scheduler.ActorJob.execute(Lio/camunda/zeebe/scheduler/ActorThread;)V (154 bytes) @ 0x00007f6538edd908 [0x00007f6538edd7c0+0x0000000000000148]
J 21989 c2 io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask()V (213 bytes) @ 0x00007f65392feb88 [0x00007f65392fe0e0+0x0000000000000aa8]
J 11127 c2 io.camunda.zeebe.scheduler.ActorThread.doWork()V (183 bytes) @ 0x00007f6538a2eee8 [0x00007f6538a2e8a0+0x0000000000000648]
J 27198 c2 io.camunda.zeebe.scheduler.ActorThread.run()V (74 bytes) @ 0x00007f65395edf5c [0x00007f65395edda0+0x00000000000001bc]
```

</p>
</details>

### PR DESCRIPTION
**Pull request by p-wunderlich**
## Description

Removes the usage of keyGenerator in the BatchOperationExecutionScheduler since this can cause memory safety issue and is not allowed. Instead we now just use the batch operation key for all follow up commands. We don't need own keys at this place.

See also here https://camunda.slack.com/archives/C05DH1F5TAR/p1743605166704629

## Related issues
closes #30536

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java [hunk 1]
```diff
@@ -101,37 +97,34 @@ private void executeBatchOperation(
...
-    command.setBatchOperationKey(batchOperation.getKey());
+    command.setBatchOperationKey(batchOperationKey);
     command.setItemKeys(keys);
-    command.setChunkKey(chunkKey);
 
     LOG.debug(
-        "Appending batch operation {} subbatch with key {}", batchOperation.getKey(), chunkKey);
-    taskResultBuilder.appendCommandRecord(chunkKey, BatchOperationChunkIntent.CREATE, command);
+        "Appending batch operation {} subbatch with {} items.", batchOperationKey, keys.size());
+    taskResultBuilder.appendCommandRecord(
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:116]: 💭 there's an `appendCommandRecord` in `TaskResultBuilder` that does not take a key at all as a parameter, I wonder how does it work 🤔 
💭 also in the `BufferedTaskResultBuilder` we add commands to a `cache` using `intent` and `key`. If the cache had the same key and intent we do not add it. 
Now since we are writing several chunk commands with the same key and intent, will that work?

Comment (p-wunderlich) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:116]: Hm you are right, that cannot work ... damn. So we need to generate something which is at least for the cache unique, without using key generator. Or we make it possible to disable the cache for our case.

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:116]: yes, let's discuss it more tomorrow in sync

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationExecutionScheduler.java:116]: let's test if this now works once this [PR](https://github.com/camunda/camunda/pull/30560) gets merged. if so, we can merge this one too.

**Review by mustafadagher — APPROVED** [review]
Let's rebase on main to have the cache fix, and test that it works before merging. 🙇

**Comment by p-wunderlich** [comment]
Tested it locally with a running broker, this works now. :)
