### PR TITLE
Properly handle connection closed error in the gRPC server

### LINKED ISSUE #18339: Do not log MessagingException$ConnectionClosed as an error in the gateway
**Description**

We recently introduced a new exception to represent when a connection was closed in the messaging service before it was completed, usually because we're closing the service itself. This triggers logging lots of errors when we have in flight connections, which aren't particularly useful, since you're shutting down.

Instead, we should treat this as upstream being temporarily unavailable, return `UNAVAILABLE`, and log it like we do with the `ConnectException` in `GrpcErrorMapper` (see line 120 for 8.2).

Context:

- https://console.cloud.google.com/errors/detail/CKCP-c-I5-3zkQE;service=zeebe;time=P7D?project=zeebe-io
- https://console.cloud.google.com/errors/detail/CIr23a-H74DG8QE;service=zeebe;time=P7D?project=zeebe-io
- https://console.cloud.google.com/errors/detail/CIr23a-H74DG8QE;service=zeebe;time=P7D;locations=global?project=camunda-saas-prod-lhr

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR maps the `ConnectionClosed` error - which is returned by the `BrokerClient` when the broker has forcefully closed the connection before the gateway request was completed - as ABORTED, since it's unclear whether or not the request is safe to retry (i.e. is it idempotent?).

Also includes a little bit of refactoring as the first commit.

## Related issues

closes #18339

### CODE REVIEW

File: zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/grpc/GrpcErrorMapper.java [hunk 1]
```diff
@@ -51,81 +52,106 @@ private Status mapErrorToStatus(
...
+      case final ConnectException ignored -> {
+        builder.setCode(Code.UNAVAILABLE_VALUE).setMessage(error.getMessage());
+        logger.warn(
+            "Expected to handle gRPC request, but there was a connection error with one of the brokers",
+            rootError);
+      }
+      case final MessagingException.ConnectionClosed ignored -> {
+        builder.setCode(Code.ABORTED_VALUE).setMessage(error.getMessage());
+        logger.warn(
+            "Expected to handle gRPC request, but the connection was cut between with the broker",
```
Comment (lenaschoenburg) [inline zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/grpc/GrpcErrorMapper.java:144]: :upside_down_face: Broken grammar "between with the broker"

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
Thanks for the refactoring! 🚀
