### PR TITLE
fix: calculate modification menu entries based on resolved element instance

### LINKED ISSUE #44553: Operate modification dropdown contains wrong entries (add, move, move all, etc.)
### 

### 

### 

### 

### Description

In single modification mode, the modification dropdown contains wrong entries:

- Cancel/move modifications are not available when an element with one instance is selected from the diagram
- Modification of a single instance of a multi instance element is not possible
 

### Steps to reproduce (use case 1)

1. Set feature flag `IS_ELEMENT_SELECTION_V2` to `true`  in `src/modules/feature-flags.ts`
2. Go to Operate UI and select a process instance with active element instances
3. Enable modification mode (top right wrench button)
4. Click on an element with exactly one active instance
5. Observe the modification dropdown menu

### Current behavior (use case 1)

The dropdown contains the following entries:

- Add

### Expected behavior (use case 1)

The dropdown should contain the following entries:

- Add
- Cancel instance
- Move instance

---

### Steps to reproduce (use case 2)

1. Set feature flag `IS_ELEMENT_SELECTION_V2` to `true`  in `src/modules/feature-flags.ts`
2. Go to Operate UI and select a process instance with multi instance elements (e.g. an instance of "Multi-Instance Process" from demo data)
3. Enable modification mode (top right wrench button)
4. Select a single instance of a multi instance element from the instance history (bottom left panel)
5. Observe the modification dropdown menu

### Current behavior (use case 2)

The dropdown contains the following entries:

Selected running instances: 3
- Cancel all
- Move all

Image

### Expected behavior (use case 2)

The dropdown should contain the following entries:

Selected running instances: 1
- Cancel instance
- Move instance

Image

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- 8.9.0-alpha4 (behind feature flag)

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by pedesen**
## Description

- fix wrong modification dropdown menu entries
- add test coverage for `useAvailableModifications` hook

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #44553

### CODE REVIEW

File: operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx [hunk 1]
```diff
@@ -60,21 +60,28 @@ const ModificationDropdown: React.FC<Props> = observer(
...
 
     const availableModifications = useAvailableModifications({
       runningElementInstanceCount: selectedElementRunningInstancesCount ?? 0,
       elementId: selectedElementId ?? undefined,
       elementInstanceKey: selectedElementInstanceKey ?? undefined,
       isMultiInstanceBody: isSelectedInstanceMultiInstanceBody,
-      isElementInstanceResolved: resolvedElementInstance !== null,
+      isElementInstanceKeyAvailable:
+        selectedElementInstanceKey !== null ||
+        resolvedElementInstanceKey !== undefined,
```
Comment (pedesen) [inline operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx:84]: This was a bit misleading. I renamed it to `isElementInstanceKeyAvailable` because the expectation is that either an element instance is selected from the instance history (selectedElementInstanceKey is set) or an element instance is resolved after an element is selected from the diagram (resolvedElementInstanceKey).

Comment (pedesen) [reply operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx:84]: 💭 Overall I think we would be better with a state machine here to cover all the possible combinations, but this exceeds the scope of this issue.

Comment (christoph-fricke) [reply operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx:84]: Do you mean a state machine powering the `useProcessInstanceElementSelection` logic?

**Review by christoph-fricke — APPROVED** [review]
Looks good.

💭 The `elementInstanceKey` parameter for `useAvailableModifications` is used to check whether it is `undefined`, which is passed the `selectedElementInstanceKey` as an argument. So basically it checks whether or not an instance is selected in the instance history, right? Would it be more explicit that one should not provide the `resolvedElementInstanceKey` by using a boolean parameter instead, e.g. `has(Specific)ElementInstanceSelected`?

**Review by juliasaienko — APPROVED** [review]

**Review by vsgoulart — APPROVED** [review]

File: operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx (hunk 1 above)
Comment (pedesen) [reply operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx:84]: No, I meant a state machine responsible for deciding which conditions need to be met to show which kind of entries in the modification dropdown.

**Comment by pedesen** [comment]
> Would it be more explicit that one should not provide the resolvedElementInstanceKey by using a boolean parameter instead, e.g. has(Specific)ElementInstanceSelected?

@christoph-fricke I also think it's more explicit and changed it accordingly.

**Review by christoph-fricke — APPROVED** [review]
