### PR TITLE
Centralize gRPC error mapping

### LINKED ISSUE #5237: Detect wrongly mapped Gateway error responses earlier
**Description**

We had an issue (https://github.com/zeebe-io/zeebe/issues/5187) where we haven't mapped a returned ErrorResponse correctly to a StatusRuntimeException, which caused in the client weird error messages and per default the error is then mapped to `UNKNOWN`. 

This PR https://github.com/zeebe-io/zeebe/pull/5228 fixed that, but it doesn't prevent it from happening again.
We currently have two problems in the Gateway:

 1. We aren't testing error handling or sending error responses properly
 2. We can send errors and in general response everywhere in the code. This means it is hard to make sure that all errors are mapped correctly, you can just call `streamObserver.onError(Throwable)` and it will be returned to the client.

## Proposal:

I have two possible solutions for this:

### First solution

In order to overcome this, we could wrap the `StreamObserver` and `EndpointManager`, such they intercept every call and verify that the `Throwable`, which is given into the `onError` is actually a `StatusRuntimeException`. If not we could throw a new exception that indicates this problem. This exception we then should see at least in our benchmarks, ideally of course in our tests as well. You can find at this branch https://github.com/zeebe-io/zeebe/tree/zell-gateway-wrapper a working example.

### Second solution

Another approach would be to refactor the gateway in a way that the response handling is at one place. We could achieve that for example with futures. We give the request handlers instead of the stream observer an future which can be completed with the response or an exception. We add a completion handler to the future which then sends the correctly mapped exception or the response.

In all cases we need to improve our test coverage in the gateway.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR centralizes gRPC error mapping by introducing a new `ErrorMappingStreamObserver`. The new observer will decorate an existing one, and `onError`, map the given exception to a `StatusRuntimeException` (assuming it isn't one already). It will also suppress the cancel exception if the decorated observer is a `ServerCallStreamObserver` (which it should be, as this is meant to be used only on the server side).

Part of the PR also introduces a new, richer error model as described by Google (see [here](https://cloud.google.com/apis/design/errors#error_model)), by first mapping errors to `com.google.rpc.Status`, before converting it to exceptions via `StatusProto`. Later on, we can then add details to errors, or aggregate multiple errors into composite types (see for example these [types](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto) which we could use), but this was not done as part of the scope of this PR.

## Related issues

closes #5237 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: gateway/src/main/java/io/zeebe/gateway/grpc/ErrorMappingStreamObserver.java [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+import io.grpc.StatusRuntimeException;
+import io.grpc.stub.ServerCallStreamObserver;
+import io.grpc.stub.StreamObserver;
+import io.zeebe.gateway.Loggers;
+
+/**
+ * A {@link StreamObserver} decorator which will map errors to {@link StatusException} before
+ * passing them on to the {@code delegate}.
+ *
+ * <p>Additionally, if the decorated {@link StreamObserver} is a {@link ServerCallStreamObserver},
```
Comment (Zelldon) [inline gateway/src/main/java/io/zeebe/gateway/grpc/ErrorMappingStreamObserver.java:20]: Actually you only accept ServerCallStreamObserver

File: gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+    if (error instanceof ExecutionException) {
+      return mapErrorToStatus(error.getCause());
+    } else if (error instanceof BrokerErrorException) {
+      final Status status = mapBrokerErrorToStatus(((BrokerErrorException) error).getError());
+      builder.mergeFrom(status);
+
+      // When there is back pressure, there will be a lot of `RESOURCE_EXHAUSTED` errors and the log
+      // can get flooded, so log them at the lowest level possible
+      if (status.getCode() != Code.RESOURCE_EXHAUSTED.getNumber()) {
+        logger.error("Expected to handle gRPC request, but received error from broker", error);
```
Comment (Zelldon) [inline gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:55]: Currently thinking whether it really necessary to error in gateway in general, since they properly logged in the broker already and when the client receives the error

File: gateway/src/main/java/io/zeebe/gateway/impl/broker/RequestRetryHandler.java [hunk 3]
```diff
@@ -27,6 +27,7 @@
  * all partitions are tried. The request is retried only for specific errors such as connection
  * errors or resource exhausted errors. The request is not retried for time outs.
  */
+@SuppressWarnings("java:S119")
```
Comment (Zelldon) [inline gateway/src/main/java/io/zeebe/gateway/impl/broker/RequestRetryHandler.java:30]: :sweat_smile:

File: gateway/src/test/java/io/zeebe/gateway/grpc/GrpcErrorMapperTest.java [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+  }
+
+  @AfterEach
+  void tearDown() {
+    recorder.stop();
+    log.removeAppender(recorder);
+  }
+
+  @Test
+  void shouldTraceLogResourceExhaustedError() {
```
Comment (Zelldon) [inline gateway/src/test/java/io/zeebe/gateway/grpc/GrpcErrorMapperTest.java:49]:
```suggestion
  void shouldLogResourceExhaustedErrorOnTrace() {
```

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @npepinpe just some small comments

File: gateway/src/main/java/io/zeebe/gateway/EndpointManager.java [hunk 5]
```diff
@@ -119,7 +111,8 @@ private void addPartitionInfoToBrokerInfo(
   public void activateJobs(
       final ActivateJobsRequest request,
       final StreamObserver<ActivateJobsResponse> responseObserver) {
-    activateJobsHandler.activateJobs(request, responseObserver);
+    activateJobsHandler.activateJobs(
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply gateway/src/main/java/io/zeebe/gateway/EndpointManager.java:114]: Wasn't aware of it, but its a good idea

File: gateway/src/main/java/io/zeebe/gateway/grpc/ErrorMappingStreamObserver.java (hunk 1 above)
Comment (npepinpe) [reply gateway/src/main/java/io/zeebe/gateway/grpc/ErrorMappingStreamObserver.java:20]: True, I wrote this before I changed the interface 😅

File: gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java (hunk 2 above)
Comment (npepinpe) [reply gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:55]: I'm not sure we log all errors in the broker. For example, partition mismatch i think is not logged, maybe others?

Comment (Zelldon) [reply gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:55]: But is this really an error then is the question? It is kind of expected that this can happen - ideally we should just retry that in this case

File: gateway/src/main/java/io/zeebe/gateway/impl/broker/RequestRetryHandler.java (hunk 3 above)
Comment (npepinpe) [reply gateway/src/main/java/io/zeebe/gateway/impl/broker/RequestRetryHandler.java:30]: SonarCloud complains that the type names don't conform to the format. I don't think we ever decided on one, but I suppose we could just change the format on sonarcloud and not have to suppress those warnings

File: gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java (hunk 2 above)
Comment (npepinpe) [reply gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:55]: My rule of thumb in general is, assuming a client-server setup, if the server returns an error, the client should log it, not the server. However, the server might log error details that are not returned to the client - i.e. sensitive info, information that isn't helpful for the client, etc. 

In this particular case, we return an INTERNAL error to the client (e.g. 500 - which, by the way, is probably the wrong code to return for `PARTITION_LEADER_MISMATCH` :sweat_smile:), with very little information from the client point of view. So we need to log it in the broker/gateway. From the broker point of view though, you're right, this is an expected error - hence why I'd log it on the "client" side, i.e. the gateway in this instance. But like I said, bad example, as `PARTITION_LEADER_MISMATCH` should probably return `UNAVAILABLE` or something like this, indicating the user can retry the request :sweat_smile:

**Comment by npepinpe** [comment]
I applied your review feedback, adding `EndpointWrapper` as `GatewayGrpcService`, and a new interface `ServerStreamObserver`.

The idea of `GatewayGrpcService` is to start moving in a direction where we decouple the gRPC entry point from the actual gateway logic. Moving forward, we could move the request mapping/response mapping to the gRPC specific stuff, and have the endpoint handlers already use the mapped requests/response so we they can focus on the business logic and not the gRPC specific stuff.

The `ServerStreamObserver` I added - I get that it seems like additional fuzz (and it might be, maybe I'm overthinking this), but the idea is that `ServerCallStreamObserver` is not only a concrete class, but it has a wider API (so more difficult to mock), and is an experimental API. So I'd rather have our own small interface, and we simply need to make sure we're mapping the implementations properly instead of polluting all the call sites with the experimental one.

I also added missing branches for broker errors/rejections; the main difference is now mapping `PROCESSING_ERROR` to `INTERNAL` (wasn't sure about that one though, happy to discuss), and `PARTITION_LEADER_MISMATCH` to `UNAVAILABLE` (since it most likely is transient, and retrying should fix it).

Let me know what you think :+1:

File: gateway/src/main/java/io/zeebe/gateway/EndpointManager.java [hunk 6]
```diff
@@ -107,48 +106,42 @@ private void addPartitionInfoToBrokerInfo(
...
         RequestMapper::toCancelWorkflowInstanceRequest,
         ResponseMapper::toCancelWorkflowInstanceResponse,
-        ErrorMappingStreamObserver.ofStreamObserver(responseObserver));
+        responseObserver);
   }
 
-  @Override
   public void completeJob(
       final CompleteJobRequest request,
       final StreamObserver<CompleteJobResponse> responseObserver) {
```
Comment (Zelldon) [inline gateway/src/main/java/io/zeebe/gateway/EndpointManager.java:127]: Why are some methods are changed to use the new interface and some not?

File: gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java [hunk 7]
```diff
@@ -99,6 +99,20 @@ private Status mapBrokerErrorToStatus(final BrokerError error) {
...
+      case INVALID_DEPLOYMENT_PARTITION:
+      case MALFORMED_REQUEST:
+      case INVALID_CLIENT_VERSION:
+      case UNSUPPORTED_MESSAGE:
+      case INTERNAL_ERROR:
+      case SBE_UNKNOWN:
+      case NULL_VAL:
       default:
         builder.setCode(Code.INTERNAL_VALUE);
         message =
```
Comment (Zelldon) [inline gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:118]: Maybe it makes more sense to return the string representation of the error code,  instead of returning the code in the error message? Then it is more clear for the user/client?

File: gateway/src/main/java/io/zeebe/gateway/impl/broker/RequestRetryHandler.java (hunk 3 above)
Comment (Zelldon) [reply gateway/src/main/java/io/zeebe/gateway/impl/broker/RequestRetryHandler.java:30]: What type names we are talking here? That interface should be an adjective?

File: gateway/src/main/java/io/zeebe/gateway/grpc/ServerStreamObserver.java [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+/**
+ * A simple extension of {@link StreamObserver}, meant to be used in conjunction with {@link
+ * io.grpc.stub.ServerCallStreamObserver}. In order to avoid depending on {@link
+ * io.grpc.stub.ServerCallStreamObserver}, which is experimental (as of now), we introduce this
+ * simple interface, and we can easily change the implementation whenever the experimental API is
+ * changed.
+ *
+ * @param <GrpcResponseT> the expected gRPC response type
+ */
+@SuppressWarnings("java:S119")
```
Comment (Zelldon) [inline gateway/src/main/java/io/zeebe/gateway/grpc/ServerStreamObserver.java:21]: It is a bit weird with the suppresswarnings to be honest

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
I like it :+1: I had just some smaller comments

File: gateway/src/main/java/io/zeebe/gateway/grpc/ServerStreamObserver.java (hunk 8 above)
Comment (npepinpe) [reply gateway/src/main/java/io/zeebe/gateway/grpc/ServerStreamObserver.java:21]: Like I said, it's because sonar cloud is set up to warn you if you don't use all caps for your types. We can also change the SonarCloud config instead :+1:

File: gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java (hunk 7 above)
Comment (npepinpe) [reply gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:118]: Probably, - I can't remember now why we return the code and not the string representation.

File: gateway/src/main/java/io/zeebe/gateway/EndpointManager.java (hunk 6 above)
Comment (npepinpe) [reply gateway/src/main/java/io/zeebe/gateway/EndpointManager.java:127]: Only the activateJobsHandler really needs the new type actually...but it makes sense to change all methods to accept it.

**Comment by npepinpe** [comment]
Applied review feedback :+1:

File: gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java (hunk 7 above)
Comment (npepinpe) [reply gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:118]: By string representation, you mean of the code (in this case that's what we do), or you mean the error message? The idea why we don't put the error message is that for these errors, we've logged it on the broker side, and it's probably not very useful for the client (also, it may contain sensitive info for some customers such as file path, system info, etc.)

Comment (Zelldon) [reply gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:118]: Ok my fault sorry. I thought this returns the int representation.

**Review by ChrisKujawa — APPROVED** [review]
Thanks @npepinpe good job :+1:
