### PR TITLE
Unrecoverable exception at snapshot director

### LINKED ISSUE #6698: Handle and test log corruption while taking snapshots
**Description**

As described in #6661, the scope of this issue is to handle and test log corruption while taking snapshots.

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Handle unrecoverable exceptions at snapshot director.

## Related issues

closes #6698 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 1]
```diff
@@ -108,6 +116,40 @@ public void forceSnapshot() {
...
   }
 
+  @Override
+  protected void handleFailure(final Exception failure) {
+    LOG.error(
+        "Snapshot director '{}' failed in phase {} with: {}",
+        actorName,
+        actor.getLifecyclePhase(),
+        failure);
+    actor.fail();
```
Comment (deepthidevaki) [inline broker/src/main/java/io/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:126]: I'm wondering if we should hard fail here. It is possible to recover when it takes the next snapshot, right? If the corruption is in one segment, but the processor and exporter have already moved past that segment, we would be able to take the next snapshot and compact the corrupted segment.

**Comment by menski** [comment]
FYI I rebased this branch to the artifact id changes

File: broker/src/main/java/io/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java (hunk 1 above)
Comment (MiguelPires) [reply broker/src/main/java/io/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java]: I guess it depends on whether the exporter and snapshot have passed that position or not. We can set the snapshot director's health to unhealthy and back to healthy when it successfully takes a snapshot

Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java]: This was more of a question than request to change. It would be good to discuss and decide what would be a good behavior. If it goes only unhealthy, then we also need to ensure that it's state is rolled back - pending snapshot is aborted, all other internal actor states are reverted so that next snapshot can be successfully taken (if possible).

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 2]
```diff
@@ -119,24 +118,16 @@ public void forceSnapshot() {
...
-        "Snapshot director '{}' failed in phase {} with: {}",
+        "Uncaught exception at snapshot director '{}' in phase {}: {}",
         actorName,
         actor.getLifecyclePhase(),
         failure);
-    actor.fail();
 
-    if (failure instanceof UnrecoverableException) {
-      healthStatus = HealthStatus.DEAD;
+    resetStateOnFailure();
```
Comment (deepthidevaki) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:126]: :+1:

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 3]
```diff
@@ -119,24 +118,16 @@ public void forceSnapshot() {
   @Override
   protected void handleFailure(final Exception failure) {
     LOG.error(
-        "Snapshot director '{}' failed in phase {} with: {}",
+        "Uncaught exception at snapshot director '{}' in phase {}: {}",
```
Comment (deepthidevaki) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:121]: May be add a bit more context to the log messag. Something like `No snapshot will be taken now. Will try to take a snapshot at the next snapshot period. Please report the issue if the error persists.`.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks. The healthstatus should be set back to healthy, if it was able to successfully take a snapshot later.

**Comment by MiguelPires** [comment]
Thanks @deepthidevaki. I applied your comments, please let me know what you think

**Review by deepthidevaki — APPROVED** [review]
Thanks :100: 

We could also think about marking it as dead if there were 3 consecutive failures. It is out of scope for this PR. But something to take away.
