### PR TITLE
fix: NPE in PendingMessageSubscriptionChecker

### LINKED ISSUE #14588: NPE in `PendingMessageSubscriptionChecker`
**Describe the bug**

There appears to be a race condition in the `PendingMessageSubscriptionChecker`. It can run concurrently to the stream processor, where the two access a shared in-memory state (aka transient state). Access to this state is threadsafe, but not spread over multiple calls.

The race condition appears to exist here: The entries are first retrieved from the transient state, before we `get` the subscription from the persisted state. The transient state may have been modified before, leading to both states not being in-sync.

https://github.com/camunda/zeebe/blob/d928ba2ed6321b3e613320e9c7fcdd0bc0decc44/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageSubscriptionState.java#L229-L236

**To Reproduce**

This may be hard to reproduce, as it's a race condition. It may be possible to set up by calling the associated method in a specific order where the order can be controlled.

**Expected behavior**

The checker should be able to run concurrently to the stream processor without issues.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.message.MessageSubscription.getRecord()" because "subscription" is null
    at io.camunda.zeebe.engine.processing.message.PendingMessageSubscriptionChecker.sendCommand(PendingMessageSubscriptionChecker.java:36) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
    at io.camunda.zeebe.engine.state.message.DbMessageSubscriptionState.visitPending(DbMessageSubscriptionState.java:253) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
    at io.camunda.zeebe.engine.processing.message.PendingMessageSubscriptionChecker.run(PendingMessageSubscriptionChecker.java:32) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
    at io.camunda.zeebe.stream.api.scheduling.SimpleProcessingScheduleService.lambda$runAtFixedRate$0(SimpleProcessingScheduleService.java:35) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
```

</p>
</details>

[Link to log](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-10-02T13:01:28.455354092Z;endTime=2023-10-02T14:54:41.744537Z;query=error_group%2528%22CKOmuvKMwLOtvAE%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.namespace_name%3D%2228dc004a-c9eb-4ee4-bd43-122d19470705-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Atimestamp%3D%222023-10-02T13:01:28.455354092Z%22%0AinsertId%3D%22t5z8oevltfufcaqu%22;startTime=2023-10-02T12:54:41.744Z?project=camunda-saas-int-chaos)

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

A null check is added to visitPending() method. When a subscription not found, a warning logs the situation. Also, a comment added to clarify the situation further. Writing a test for the race condition is not trivial since the written test itself can be non-deterministic. E.g. we create a couple of thousand subscription records in the state and remove one asynchronously in the test can lead to a flaky test as well.

## Related issues

closes #14588 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageSubscriptionState.java [hunk 1]
```diff
@@ -250,7 +253,16 @@ public void visitPending(final long deadline, final MessageSubscriptionVisitor v
...
 
-      visitor.visit(subscription);
+      if (subscription == null) {
+        // This case can occur while a scheduled job is running asynchronously
+        // and the stream processor removes one of the returned subscriptions from the state.
+        LOG.warn(
+            "Expected to find a subscription with key {} and message name {}, but none found. The state is inconsistent.",
+            pendingSubscription.elementInstanceKey(),
+            pendingSubscription.messageName());
+      } else {
```
Comment (nicpuppa) [inline engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageSubscriptionState.java:263]: 🔧 you can remove the else state by returning at the end of the if state

**Review by nicpuppa — APPROVED** [review]
LGTM 💪 

Left a small suggestion, but great work on finding a solution of this bug 🚀

File: engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageSubscriptionState.java (hunk 1 above)
Comment (berkaycanbc) [reply engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageSubscriptionState.java:263]: @nicpuppa you probably mean using `continue` here. Because if I use `return` statement, it will go out of the loop and we will skip other subscriptions. Since, using `continue` is not a good practice of clean code, I prefer `else` statement instead. WDYT?

Comment (nicpuppa) [reply engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageSubscriptionState.java:263]: Didn't saw it was a loop 👀 👓 , sorry for that! 

In this particular case using `continue` statement is not so bad, but is just my own preference. You can ignore my suggestion

**Comment by berkaycanbc** [comment]
bors merge
