### PR TITLE
check returned error of leader election service

### LINKED ISSUE #2404: NPE in PartitionInstallService
```
07:21:38.629 [service-container-main] [0.0.0.0:25602-zb-actors-1] ERROR io.zeebe.servicecontainer - Failed to remove service cluster.base.raft.install.partition-1: java.lang.IllegalArgumentException: Cannot remove service with name 'cluster.base.raft.install.partition-1': no such service registered.
07:21:38.627 [io.zeebe.broker.clustering.base.partitions.PartitionInstallService] [0.0.0.0:25602-zb-actors-0] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.NullPointerException: null
	at io.zeebe.broker.clustering.base.partitions.PartitionInstallService.lambda$onActorStarted$0(PartitionInstallService.java:148) ~[classes/:?]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:40) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
```

### PR DESCRIPTION
**Pull request by deepthidevaki**
closes #2404 

This PR handles the null pointer exception which can happen if the leader election service did not start successfully.

### CODE REVIEW

File: broker-core/src/main/java/io/zeebe/broker/clustering/base/partitions/PartitionInstallService.java [hunk 1]
```diff
@@ -145,7 +145,15 @@ public void stop(ServiceStopContext stopContext) {
...
   protected void onActorStarted() {
     actor.runOnCompletion(
-        leaderElectionInstallFuture, (leaderElection, e) -> leaderElection.addListener(this));
+        leaderElectionInstallFuture,
+        (leaderElection, e) -> {
+          if (e == null) {
+            leaderElection.addListener(this);
+          } else {
+            LOG.error(
+                "Could not install leader election listener for partition {}", partitionId, e);
```
Comment (Zelldon) [inline broker-core/src/main/java/io/zeebe/broker/clustering/base/partitions/PartitionInstallService.java]:
```suggestion
                "Could not install leader election for partition {}", partitionId, e);
```

**Review by ChrisKujawa — APPROVED** [review]
Thanks for fixing this :+1: I think "listener" can be removed from the message, because it failed to install the election not the listener :)

File: broker-core/src/main/java/io/zeebe/broker/clustering/base/partitions/PartitionInstallService.java (hunk 1 above)
Comment (deepthidevaki) [reply broker-core/src/main/java/io/zeebe/broker/clustering/base/partitions/PartitionInstallService.java]: :+1:

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 76d6ba3c3301a1366d14581d2f67e8f1dc5f8b4a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 120 characters

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by menski** [comment]
What is the expected state if we fail to install the leader election? The partition is still installed but is not participating in the leader election?

**Comment by deepthidevaki** [comment]
I have added another issue #2414 for that case. We should either fail the broker or retry joining leader election until it succeeds.
