### PR TITLE
Handle snapshot replication from 0.23.x brokers

### LINKED ISSUE #5035: RollingUpdateTest.shouldPerformRollingUpgrade flaky
**Summary**

- How often does the test fail? several times since the last fix for this test (new and different error message)
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>

org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at io.zeebe.test.RollingUpdateTest.shouldPerformRollingUpgrade(RollingUpdateTest.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	... 43 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:498)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 44 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:32825/ready should return HTTP [204])
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:214)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at io.zeebe.containers.BrokerWaitStrategy.waitUntilReady(BrokerWaitStrategy.java:45)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:890)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441)
	... 46 more

</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
00:39:17.181 [main] [] INFO  io.zeebe.test - Test started: shouldPerformRollingUpgrade(io.zeebe.test.RollingUpdateTest)
00:39:26.386 [testcontainers-lifecycle-1] [] INFO  org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy - Found docker client settings from environment
00:39:26.404 [testcontainers-lifecycle-1] [] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=tcp://localhost:2375
00:39:28.205 [testcontainers-lifecycle-1] [] INFO  org.testcontainers.DockerClientFactory - Docker host IP address is localhost
00:39:28.305 [testcontainers-lifecycle-1] [] INFO  org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 18.09.4
  API Version: 1.39
  Operating System: Alpine Linux v3.9 (containerized)
  Total Memory: 120871 MB
00:39:28.611 [testcontainers-lifecycle-1] [] WARN  org.testcontainers.utility.RegistryAuthLocator - Failure when attempting to lookup auth config (dockerImageName: testcontainersofficial/ryuk:0.3.0, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
00:39:30.090 [tc-okhttp-stream-1239130408] [] INFO  org.testcontainers.DockerClientFactory - Starting to pull image
00:39:30.192 [tc-okhttp-stream-1239130408] [] INFO  org.testcontainers.DockerClientFactory - Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
00:39:33.485 [testcontainers-lifecycle-1] [] INFO  org.testcontainers.DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
00:39:33.486 [testcontainers-lifecycle-1] [] INFO  org.testcontainers.DockerClientFactory - Checking the system...
00:39:33.493 [testcontainers-lifecycle-1] [] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
00:39:33.683 [testcontainers-lifecycle-1] [] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker environment should have more than 2GB free disk space
00:39:33.706 [testcontainers-lifecycle-2] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling docker image: camunda/zeebe:0.23.0. Please be patient; this may take some time but only needs to be done once.
00:39:33.706 [testcontainers-lifecycle-0] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling docker image: camunda/zeebe:0.23.0. Please be patient; this may take some time but only needs to be done once.
00:39:33.707 [testcontainers-lifecycle-1] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling docker image: camunda/zeebe:0.23.0. Please be patient; this may take some time but only needs to be done once.
00:39:34.978 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Starting to pull image
00:39:34.979 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
00:39:34.996 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Starting to pull image
00:39:34.998 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
00:39:34.998 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Starting to pull image
00:39:35.002 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
00:39:35.499 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers: 11 pending,  1 downloaded,  0 extracted, (673 KB/? MB)
00:39:35.502 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers: 11 pending,  1 downloaded,  0 extracted, (673 KB/? MB)
00:39:35.510 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers: 11 pending,  1 downloaded,  0 extracted, (673 KB/? MB)
00:39:35.515 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers: 10 pending,  2 downloaded,  0 extracted, (20 MB/? MB)
00:39:35.516 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers: 10 pending,  2 downloaded,  0 extracted, (20 MB/? MB)
00:39:35.518 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers: 10 pending,  2 downloaded,  0 extracted, (20 MB/? MB)
00:39:35.878 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  9 pending,  3 downloaded,  0 extracted, (54 MB/? MB)
00:39:35.880 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  9 pending,  3 downloaded,  0 extracted, (54 MB/? MB)
00:39:35.881 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  9 pending,  3 downloaded,  0 extracted, (54 MB/? MB)
00:39:35.940 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  8 pending,  4 downloaded,  0 extracted, (54 MB/? MB)
00:39:35.940 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  8 pending,  4 downloaded,  0 extracted, (54 MB/? MB)
00:39:35.978 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  8 pending,  4 downloaded,  0 extracted, (54 MB/? MB)
00:39:36.020 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  7 pending,  5 downloaded,  0 extracted, (54 MB/? MB)
00:39:36.017 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  7 pending,  5 downloaded,  0 extracted, (54 MB/? MB)
00:39:36.017 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  7 pending,  5 downloaded,  0 extracted, (54 MB/? MB)
00:39:36.379 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  6 pending,  6 downloaded,  0 extracted, (54 MB/? MB)
00:39:36.379 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  6 pending,  6 downloaded,  0 extracted, (54 MB/? MB)
00:39:36.380 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  6 pending,  6 downloaded,  0 extracted, (54 MB/? MB)
00:39:36.479 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  5 pending,  7 downloaded,  0 extracted, (64 MB/? MB)
00:39:36.480 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  5 pending,  7 downloaded,  0 extracted, (64 MB/? MB)
00:39:36.484 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  5 pending,  7 downloaded,  0 extracted, (64 MB/? MB)
00:39:36.787 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  4 pending,  8 downloaded,  0 extracted, (87 MB/? MB)
00:39:36.788 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  4 pending,  8 downloaded,  0 extracted, (87 MB/? MB)
00:39:36.801 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  4 pending,  8 downloaded,  0 extracted, (87 MB/? MB)
00:39:37.279 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  3 pending,  9 downloaded,  0 extracted, (121 MB/? MB)
00:39:37.280 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  3 pending,  9 downloaded,  0 extracted, (121 MB/? MB)
00:39:37.281 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  3 pending,  9 downloaded,  0 extracted, (121 MB/? MB)
00:39:37.778 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  2 pending, 10 downloaded,  0 extracted, (190 MB/? MB)
00:39:37.779 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  2 pending, 10 downloaded,  0 extracted, (190 MB/? MB)
00:39:37.780 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  2 pending, 10 downloaded,  0 extracted, (190 MB/? MB)
00:39:38.835 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  1 pending, 11 downloaded,  0 extracted, (280 MB/? MB)
00:39:38.878 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  0 extracted, (280 MB/306 MB)
00:39:38.878 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  1 pending, 11 downloaded,  0 extracted, (280 MB/? MB)
00:39:38.879 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  0 extracted, (280 MB/306 MB)
00:39:38.879 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  1 pending, 11 downloaded,  0 extracted, (280 MB/? MB)
00:39:38.880 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  0 extracted, (280 MB/306 MB)
00:39:39.208 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  1 extracted, (280 MB/306 MB)
00:39:39.211 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  1 extracted, (280 MB/306 MB)
00:39:39.211 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  1 extracted, (280 MB/306 MB)
00:39:39.978 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  2 extracted, (288 MB/306 MB)
00:39:39.981 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  2 extracted, (288 MB/306 MB)
00:39:39.985 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  2 extracted, (288 MB/306 MB)
00:39:40.806 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  3 extracted, (289 MB/306 MB)
00:39:40.806 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  3 extracted, (289 MB/306 MB)
00:39:40.810 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  3 extracted, (289 MB/306 MB)
00:39:41.378 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  4 extracted, (294 MB/306 MB)
00:39:41.378 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  4 extracted, (294 MB/306 MB)
00:39:41.378 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  4 extracted, (294 MB/306 MB)
00:39:41.593 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  5 extracted, (294 MB/306 MB)
00:39:41.593 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  5 extracted, (294 MB/306 MB)
00:39:41.596 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  5 extracted, (294 MB/306 MB)
00:39:45.096 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  6 extracted, (300 MB/306 MB)
00:39:45.099 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  6 extracted, (300 MB/306 MB)
00:39:45.099 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  6 extracted, (300 MB/306 MB)
00:39:45.339 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  7 extracted, (300 MB/306 MB)
00:39:45.379 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  7 extracted, (300 MB/306 MB)
00:39:45.386 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  7 extracted, (300 MB/306 MB)
00:39:45.691 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  8 extracted, (300 MB/306 MB)
00:39:45.691 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  8 extracted, (300 MB/306 MB)
00:39:45.704 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  8 extracted, (300 MB/306 MB)
00:39:49.278 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  9 extracted, (303 MB/306 MB)
00:39:49.279 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  9 extracted, (303 MB/306 MB)
00:39:49.279 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded,  9 extracted, (303 MB/306 MB)
00:39:52.678 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded, 10 extracted, (305 MB/306 MB)
00:39:52.678 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded, 10 extracted, (305 MB/306 MB)
00:39:52.681 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded, 10 extracted, (305 MB/306 MB)
00:39:52.805 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded, 11 extracted, (305 MB/306 MB)
00:39:52.805 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded, 11 extracted, (305 MB/306 MB)
00:39:52.805 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded, 11 extracted, (305 MB/306 MB)
00:39:52.928 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded, 12 extracted, (306 MB/306 MB)
00:39:52.978 [tc-okhttp-stream-738877513] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pull complete. 12 layers, pulled in 17s (downloaded 306 MB at 18 MB/s)
00:39:52.978 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded, 12 extracted, (306 MB/306 MB)
00:39:52.978 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pulling image layers:  0 pending, 12 downloaded, 12 extracted, (306 MB/306 MB)
00:39:52.982 [tc-okhttp-stream-1145082700] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pull complete. 12 layers, pulled in 18s (downloaded 306 MB at 17 MB/s)
00:39:52.983 [tc-okhttp-stream-1917895787] [] INFO  🐳 [camunda/zeebe:0.23.0] - Pull complete. 12 layers, pulled in 17s (downloaded 306 MB at 18 MB/s)
00:39:53.105 [testcontainers-lifecycle-0] [] INFO  🐳 [camunda/zeebe:0.23.0] - Creating container for image: camunda/zeebe:0.23.0
00:39:53.106 [testcontainers-lifecycle-1] [] INFO  🐳 [camunda/zeebe:0.23.0] - Creating container for image: camunda/zeebe:0.23.0
00:39:53.108 [testcontainers-lifecycle-2] [] INFO  🐳 [camunda/zeebe:0.23.0] - Creating container for image: camunda/zeebe:0.23.0
00:40:19.714 [testcontainers-lifecycle-2] [] INFO  🐳 [camunda/zeebe:0.23.0] - Starting container with ID: 05ada3e25f568b313b1dc28d9ba967b969e8ab341b9bce859c49571e5f70e15e
00:40:20.669 [testcontainers-lifecycle-0] [] INFO  🐳 [camunda/zeebe:0.23.0] - Starting container with ID: a8c71c2e0b93d6146cd2ec2727050824486315091d2116b0ba2cc52a6f8b3348
00:40:20.732 [testcontainers-lifecycle-1] [] INFO  🐳 [camunda/zeebe:0.23.0] - Starting container with ID: f9715b562ccc6498ed42c4e79542e89b02a91c2575ba22d6f90abf39ad8c307e
00:40:21.501 [testcontainers-lifecycle-2] [] INFO  🐳 [camunda/zeebe:0.23.0] - Container camunda/zeebe:0.23.0 is starting: 05ada3e25f568b313b1dc28d9ba967b969e8ab341b9bce859c49571e5f70e15e
00:40:21.512 [testcontainers-lifecycle-2] [] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /zeebe-broker-5j3p7C-gXjoha: Waiting for 60 seconds for URL: http://localhost:32783/ready
00:40:22.116 [testcontainers-lifecycle-0] [] INFO  🐳 [camunda/zeebe:0.23.0] - Container camunda/zeebe:0.23.0 is starting: a8c71c2e0b93d6146cd2ec2727050824486315091d2116b0ba2cc52a6f8b3348
00:40:22.118 [testcontainers-lifecycle-1] [] INFO  🐳 [camunda/zeebe:0.23.0] - Container camunda/zeebe:0.23.0 is starting: f9715b562ccc6498ed42c4e79542e89b02a91c2575ba22d6f90abf39ad8c307e
00:40:22.515 [testcontainers-lifecycle-0] [] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /zeebe-broker-KtxHtV-gc4hK9: Waiting for 60 seconds for URL: http://localhost:32788/ready
00:40:22.516 [testcontainers-lifecycle-1] [] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /zeebe-broker-Xjsuje-mJ7EzN: Waiting for 60 seconds for URL: http://localhost:32791/ready
00:41:00.405 [testcontainers-lifecycle-1] [] INFO  🐳 [camunda/zeebe:0.23.0] - Container camunda/zeebe:0.23.0 started in PT1M39.508816S
00:41:00.405 [testcontainers-lifecycle-2] [] INFO  🐳 [camunda/zeebe:0.23.0] - Container camunda/zeebe:0.23.0 started in PT1M39.506756S
00:41:02.588 [testcontainers-lifecycle-0] [] INFO  🐳 [camunda/zeebe:0.23.0] - Container camunda/zeebe:0.23.0 started in PT1M41.690506S
00:41:17.247 [main] [] INFO  🐳 [camunda/zeebe:current-test] - Creating container for image: camunda/zeebe:current-test
00:41:17.364 [main] [] INFO  🐳 [camunda/zeebe:current-test] - Starting container with ID: 1bea8b9360a2cbbcfd0345fac924769e0a92a555f8883757e4b4c5cf1471aacd
00:41:19.592 [main] [] INFO  🐳 [camunda/zeebe:current-test] - Container camunda/zeebe:current-test is starting: 1bea8b9360a2cbbcfd0345fac924769e0a92a555f8883757e4b4c5cf1471aacd
00:41:19.681 [main] [] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /zeebe-broker-dSczZw-SEgZdz: Waiting for 60 seconds for URL: http://localhost:32817/ready
00:41:43.706 [main] [] INFO  🐳 [camunda/zeebe:current-test] - Container camunda/zeebe:current-test started in PT26.459848S
00:41:51.737 [main] [] INFO  🐳 [camunda/zeebe:current-test] - Creating container for image: camunda/zeebe:current-test
00:41:51.825 [main] [] INFO  🐳 [camunda/zeebe:current-test] - Starting container with ID: 46f1aad2492b7a8cb377a33d4dc3a855719f46ff89ce59531654edc102b7ba13
00:41:52.415 [main] [] INFO  🐳 [camunda/zeebe:current-test] - Container camunda/zeebe:current-test is starting: 46f1aad2492b7a8cb377a33d4dc3a855719f46ff89ce59531654edc102b7ba13
00:41:52.423 [main] [] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /zeebe-broker-fo6WB2-Cd9qy2: Waiting for 60 seconds for URL: http://localhost:32825/ready
00:42:52.427 [main] [] ERROR 🐳 [camunda/zeebe:current-test] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:32825/ready should return HTTP [204])
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:214) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35) ~[testcontainers-1.14.3.jar:?]
	at io.zeebe.containers.BrokerWaitStrategy.waitUntilReady(BrokerWaitStrategy.java:45) ~[zeebe-test-container-0.33.0.jar:0.33.0]
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:890) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.14.3.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) [testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) [testcontainers-1.14.3.jar:?]
	at io.zeebe.test.RollingUpdateTest.shouldPerformRollingUpgrade(RollingUpdateTest.java:144) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.jar:4.13]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.jar:4.13]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.jar:4.13]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.jar:4.13]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.jar:4.13]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.13.jar:4.13]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.jar:4.13]
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157) [surefire-junit47-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548) [surefire-booter-3.0.0-M5.jar:3.0.0-M5]
00:42:52.462 [main] [] ERROR 🐳 [camunda/zeebe:current-test] - Log output from the failed container:
+ export ZEEBE_HOST=zeebe-broker-fo6WB2

+ ZEEBE_HOST=zeebe-broker-fo6WB2

+ '[' false = true ']'

+ export ZEEBE_BROKER_NETWORK_HOST=0.0.0.0

+ ZEEBE_BROKER_NETWORK_HOST=0.0.0.0

+ export ZEEBE_BROKER_GATEWAY_CLUSTER_HOST=0.0.0.0

+ ZEEBE_BROKER_GATEWAY_CLUSTER_HOST=0.0.0.0

+ exec /usr/local/zeebe/bin/broker

2020-07-22 00:41:54.383 [] [main] WARN  io.zeebe.legacy - Found use of legacy system environment variable 'ZEEBE_EMBED_GATEWAY'. Please use 'ZEEBE_BROKER_GATEWAY_ENABLE' instead.

2020-07-22 00:41:54.391 [] [main] INFO  io.zeebe.legacy - The old environment variable is currently supported as part of our backwards compatibility goals.

2020-07-22 00:41:54.392 [] [main] INFO  io.zeebe.legacy - However, please note that support for the old environment variable is scheduled to be removed for release 0.24.0.

2020-07-22 00:41:54.393 [] [main] WARN  io.zeebe.legacy - Found use of legacy system environment variable 'ZEEBE_PARTITIONS_COUNT'. Please use 'ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT' instead.

2020-07-22 00:41:54.393 [] [main] INFO  io.zeebe.legacy - The old environment variable is currently supported as part of our backwards compatibility goals.

2020-07-22 00:41:54.394 [] [main] INFO  io.zeebe.legacy - However, please note that support for the old environment variable is scheduled to be removed for release 0.24.0.

  ______  ______   ______   ____    ______     ____    _____     ____    _  __  ______   _____  

 |___  / |  ____| |  ____| |  _ \  |  ____|   |  _ \  |  __ \   / __ \  | |/ / |  ____| |  __ \ 

    / /  | |__    | |__    | |_) | | |__      | |_) | | |__) | | |  | | | ' /  | |__    | |__) |

   / /   |  __|   |  __|   |  _ <  |  __|     |  _ <  |  _  /  | |  | | |  <   |  __|   |  _  / 

  / /__  | |____  | |____  | |_) | | |____    | |_) | | | \ \  | |__| | | . \  | |____  | | \ \ 

 /_____| |______| |______| |____/  |______|   |____/  |_|  \_\  \____/  |_|\_\ |______| |_|  \_\

                                                                                                

2020-07-22 00:41:55.214 [] [main] INFO  io.zeebe.broker.StandaloneBroker - Starting StandaloneBroker v0.25.0-SNAPSHOT on 46f1aad2492b with PID 6 (/usr/local/zeebe/lib/zeebe-distribution-0.25.0-SNAPSHOT.jar started by root in /usr/local/zeebe)

2020-07-22 00:41:55.220 [] [main] DEBUG io.zeebe.broker.StandaloneBroker - Running with Spring Boot v2.3.1.RELEASE, Spring v5.2.7.RELEASE

2020-07-22 00:41:55.222 [] [main] INFO  io.zeebe.broker.StandaloneBroker - No active profile set, falling back to default profiles: default

2020-07-22 00:41:57.728 [] [main] INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 9600 (http)

2020-07-22 00:41:57.791 [] [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-0.0.0.0-9600"]

2020-07-22 00:41:57.793 [] [main] INFO  org.apache.catalina.core.StandardService - Starting service [Tomcat]

2020-07-22 00:41:57.795 [] [main] INFO  org.apache.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.37]

2020-07-22 00:41:58.044 [] [main] INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext

2020-07-22 00:41:58.045 [] [main] INFO  org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 2771 ms

2020-07-22 00:41:59.005 [] [main] INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'

2020-07-22 00:41:59.885 [] [main] INFO  org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver - Exposing 2 endpoint(s) beneath base path '/actuator'

2020-07-22 00:41:59.987 [] [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-0.0.0.0-9600"]

2020-07-22 00:42:00.114 [] [main] INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port(s): 9600 (http) with context path ''

2020-07-22 00:42:00.194 [] [main] INFO  io.zeebe.broker.StandaloneBroker - Started StandaloneBroker in 5.656 seconds (JVM running for 7.782)

2020-07-22 00:42:00.233 [] [main] DEBUG io.zeebe.broker.system - Initializing system with base path /usr/local/zeebe

2020-07-22 00:42:00.318 [] [main] INFO  io.zeebe.broker.system - Version: 0.25.0-SNAPSHOT

2020-07-22 00:42:00.711 [] [main] INFO  io.zeebe.broker.system - Starting broker 1 with configuration {

  "network" : {

    "host" : "0.0.0.0",

    "portOffset" : 0,

    "maxMessageSize" : "0MB",

    "advertisedHost" : "broker-1",

    "commandApi" : {

      "host" : "0.0.0.0",

      "port" : 26501,

      "advertisedHost" : "broker-1",

      "advertisedPort" : 26501,

      "address" : "0.0.0.0:26501",

      "advertisedAddress" : "broker-1:26501"

    },

    "internalApi" : {

      "host" : "0.0.0.0",

      "port" : 26502,

      "advertisedHost" : "broker-1",

      "advertisedPort" : 26502,

      "address" : "0.0.0.0:26502",

      "advertisedAddress" : "broker-1:26502"

    },

    "monitoringApi" : {

      "host" : "0.0.0.0",

      "port" : 9600,

      "advertisedHost" : "broker-1",

      "advertisedPort" : 9600,

      "address" : "0.0.0.0:9600",

      "advertisedAddress" : "broker-1:9600"

    },

    "maxMessageSizeInBytes" : 131072

  },

  "cluster" : {

    "initialContactPoints" : [ "broker-0:26502", "broker-1:26502", "broker-2:26502" ],

    "partitionIds" : [ 1 ],

    "nodeId" : 1,

    "partitionsCount" : 1,

    "replicationFactor" : 3,

    "clusterSize" : 3,

    "clusterName" : "zeebe-cluster",

    "membership" : {

      "broadcastUpdates" : false,

      "broadcastDisputes" : true,

      "notifySuspect" : false,

      "gossipInterval" : "PT0.25S",

      "gossipFanout" : 2,

      "probeInterval" : "PT1S",

      "probeTimeout" : "PT2S",

      "suspectProbes" : 3,

      "failureTimeout" : "PT10S",

      "syncInterval" : "PT10S"

    }

  },

  "threads" : {

    "cpuThreadCount" : 2,

    "ioThreadCount" : 2

  },

  "data" : {

    "directories" : [ "/usr/local/zeebe/data" ],

    "logSegmentSize" : "512MB",

    "snapshotPeriod" : "PT15M",

    "logIndexDensity" : 100,

    "diskUsageReplicationWatermark" : 0.9,

    "diskUsageCommandWatermark" : 0.8,

    "diskUsageMonitoringInterval" : "PT1S",

    "freeDiskSpaceCommandWatermark" : 20248258150,

    "freeDiskSpaceReplicationWatermark" : 10124129075,

    "logSegmentSizeInBytes" : 536870912,

    "atomixStorageLevel" : "DISK"

  },

  "exporters" : {

    "DebugLogExporter" : {

      "jarPath" : null,

      "className" : "io.zeebe.broker.exporter.debug.DebugLogExporter",

      "args" : {

        "prettyPrint" : false

      },

      "external" : false

    }

  },

  "gateway" : {

    "network" : {

      "host" : "0.0.0.0",

      "port" : 26500,

      "minKeepAliveInterval" : "PT30S"

    },

    "cluster" : {

      "contactPoint" : "0.0.0.0:26502",

      "requestTimeout" : "PT15S",

      "clusterName" : "zeebe-cluster",

      "memberId" : "gateway",

      "host" : "0.0.0.0",

      "port" : 26502,

      "membership" : {

        "broadcastUpdates" : false,

        "broadcastDisputes" : true,

        "notifySuspect" : false,

        "gossipInterval" : "PT0.25S",

        "gossipFanout" : 2,

        "probeInterval" : "PT1S",

        "probeTimeout" : "PT2S",

        "suspectProbes" : 3,

        "failureTimeout" : "PT10S",

        "syncInterval" : "PT10S"

      }

    },

    "threads" : {

      "managementThreads" : 1

    },

    "monitoring" : {

      "enabled" : false,

      "host" : "0.0.0.0",

      "port" : 9600

    },

    "security" : {

      "enabled" : false,

      "certificateChainPath" : null,

      "privateKeyPath" : null

    },

    "longPolling" : {

      "enabled" : true

    },

    "initialized" : true,

    "enable" : true

  },

  "backpressure" : {

    "enabled" : true,

    "algorithm" : "VEGAS",

    "aimd" : {

      "requestTimeout" : "PT1S",

      "initialLimit" : 100,

      "minLimit" : 1,

      "maxLimit" : 1000,

      "backoffRatio" : 0.9

    },

    "fixedLimit" : {

      "limit" : 20

    },

    "vegas" : {

      "alpha" : 3,

      "beta" : 6,

      "initialLimit" : 20

    },

    "gradient" : {

      "minLimit" : 10,

      "initialLimit" : 20,

      "rttTolerance" : 2.0

    },

    "gradient2" : {

      "minLimit" : 10,

      "initialLimit" : 20,

      "rttTolerance" : 2.0,

      "longWindow" : 600

    }

  },

  "stepTimeout" : "PT5M",

  "executionMetricsExporterEnabled" : false

}

2020-07-22 00:42:00.783 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [1/13]: actor scheduler

2020-07-22 00:42:00.828 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [1/13]: actor scheduler started in 44 ms

2020-07-22 00:42:00.829 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [2/13]: membership and replication protocol

2020-07-22 00:42:00.832 [] [http-nio-0.0.0.0-9600-exec-1] INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'

2020-07-22 00:42:00.833 [] [http-nio-0.0.0.0-9600-exec-1] INFO  org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'

2020-07-22 00:42:00.845 [] [main] DEBUG io.zeebe.broker.clustering - Member 1 will contact node: broker-0:26502

2020-07-22 00:42:00.880 [] [main] DEBUG io.zeebe.broker.clustering - Member 1 will contact node: broker-1:26502

2020-07-22 00:42:00.881 [] [http-nio-0.0.0.0-9600-exec-1] INFO  org.springframework.web.servlet.DispatcherServlet - Completed initialization in 48 ms

2020-07-22 00:42:00.881 [] [main] DEBUG io.zeebe.broker.clustering - Member 1 will contact node: broker-2:26502

2020-07-22 00:42:05.594 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [2/13]: membership and replication protocol started in 4765 ms

2020-07-22 00:42:05.595 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [3/13]: command api transport

2020-07-22 00:42:06.038 [] [main] DEBUG io.zeebe.broker.system - Bound command API to broker-1:26501 

2020-07-22 00:42:06.089 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [3/13]: command api transport started in 494 ms

2020-07-22 00:42:06.090 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [4/13]: command api handler

2020-07-22 00:42:06.186 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [4/13]: command api handler started in 96 ms

2020-07-22 00:42:06.187 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [5/13]: subscription api

2020-07-22 00:42:06.224 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [5/13]: subscription api started in 37 ms

2020-07-22 00:42:06.224 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [6/13]: embedded gateway

2020-07-22 00:42:06.235 [] [main] INFO  io.zeebe.gateway - Version: 0.25.0-SNAPSHOT

2020-07-22 00:42:06.236 [] [main] INFO  io.zeebe.gateway - Starting gateway with configuration {

  "network" : {

    "host" : "0.0.0.0",

    "port" : 26500,

    "minKeepAliveInterval" : "PT30S"

  },

  "cluster" : {

    "contactPoint" : "0.0.0.0:26502",

    "requestTimeout" : "PT15S",

    "clusterName" : "zeebe-cluster",

    "memberId" : "gateway",

    "host" : "0.0.0.0",

    "port" : 26502,

    "membership" : {

      "broadcastUpdates" : false,

      "broadcastDisputes" : true,

      "notifySuspect" : false,

      "gossipInterval" : "PT0.25S",

      "gossipFanout" : 2,

      "probeInterval" : "PT1S",

      "probeTimeout" : "PT2S",

      "suspectProbes" : 3,

      "failureTimeout" : "PT10S",

      "syncInterval" : "PT10S"

    }

  },

  "threads" : {

    "managementThreads" : 1

  },

  "monitoring" : {

    "enabled" : false,

    "host" : "0.0.0.0",

    "port" : 9600

  },

  "security" : {

    "enabled" : false,

    "certificateChainPath" : null,

    "privateKeyPath" : null

  },

  "longPolling" : {

    "enabled" : true

  },

  "initialized" : true,

  "enable" : true

}

2020-07-22 00:42:06.405 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [6/13]: embedded gateway started in 179 ms

2020-07-22 00:42:06.405 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-1 [7/13]: cluster services

2020-07-22 00:42:06.989 [GatewayTopologyManager] [Broker-1-zb-actors-1] DEBUG io.zeebe.gateway - Received new broker BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=3, replicationFactor=3, partitionRoles={1=LEADER}, partitionLeaderTerms={1=1}, version=0.23.0}.

2020-07-22 00:42:07.403 [] [raft-server-1-raft-partition-partition-1] ERROR io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role

java.lang.IndexOutOfBoundsException: index=9224 length=4 capacity=885

	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1692) ~[agrona-1.6.0.jar:1.6.0]

	at org.agrona.concurrent.UnsafeBuffer.getInt(UnsafeBuffer.java:472) ~[agrona-1.6.0.jar:1.6.0]

	at io.atomix.raft.snapshot.impl.SnapshotChunkDecoder.snapshotId(SnapshotChunkDecoder.java:341) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]

	at io.atomix.raft.snapshot.impl.SnapshotChunkImpl.wrap(SnapshotChunkImpl.java:102) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]

	at io.atomix.raft.roles.PassiveRole.onInstall(PassiveRole.java:189) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]

	at io.atomix.raft.roles.FollowerRole.onInstall(FollowerRole.java:88) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]

	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$2(RaftContext.java:208) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]

	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$19(RaftContext.java:224) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]

	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]

	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]

	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]

	at java.lang.Thread.run(Unknown Source) [?:?]

2020-07-22 00:42:07.556 [GatewayTopologyManager] [Broker-1-zb-actors-1] DEBUG io.zeebe.gateway - Received new broker BrokerInfo{nodeId=2, partitionsCount=1, clusterSize=3, replicationFactor=3, partitionRoles={1=FOLLOWER}, partitionLeaderTerms={}, version=0.25.0-SNAPSHOT}.
</pre>
</details>

### LINKED ISSUE #5102: Rolling update from 0.23 to 0.24 is not possible
**Describe the bug**

Rolling update from 0.23 to 0.24 is not possible if the restarted node has to replicate snapshot from brokers on older version. Only rolling update is affected. You can shutdown the whole cluster and restart all brokers with new version.

Reference https://github.com/zeebe-io/zeebe/issues/5035

**Environment:**
 - Zeebe Version: 0.24.1

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR allows a 0.24.x broker to receive and replicate a snapshot being sent by a 0.23.x broker, fixing the rolling upgrade problem on start up. It essentially does so by attempting to decode the SBE message, and if it fails to do so, falling back to interpreting it as an old request where the data is the chunk data, building a snapshot chunk out of the install request instead.

This means there is no checksum checks (neither for the chunk nor the total snapshot) if it comes from a 0.23.x, which is essentially the behaviour of the 0.23.x snapshot replication.

## Related issues

closes #5102 
closes #5035 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

> Not necessary to back port as it affects only 0.24.x, but should be forward ported to develop.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

**Comment by npepinpe** [comment]
Note that this is kind of hacky so we should discuss what would be a good design :slightly_smiling_face:

File: atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java [hunk 1]
```diff
@@ -185,8 +189,17 @@ private void addSnapshotListener() {
                   .build()));
     }
 
-    final var snapshotChunk = new SnapshotChunkImpl();
-    snapshotChunk.wrap(new UnsafeBuffer(request.data()), 0, request.data().capacity());
+    SnapshotChunk snapshotChunk;
+    try {
+      final var snapshotChunkImpl = new SnapshotChunkImpl();
+      snapshotChunkImpl.wrap(new UnsafeBuffer(request.data()), 0, request.data().capacity());
```
Comment (deepthidevaki) [inline atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:195]: Suggestion: you can use `snapshotChunkImpl.tryWrap`

Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:195]: The way tryWrap is implemented would most likely work here, though it would also normally reject messages with the wrong schema ID or versions...still works but I feel for the wrong reason (as it doesn't explicitly fail if it cannot be parsed, just if some header properties are wrong). wdyt?

Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java]: Ya. In this case, it does not make much difference. Might be useful for future-proofing.

**Comment by npepinpe** [comment]
ping @Zelldon :eyes: 

I think the stuff I hate most is the part in `atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/FileBasedReceivedSnapshot.java` and using these `MIN_VALUE` to ignore some checks =/

File: atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java [hunk 2]
```diff
@@ -385,6 +389,18 @@ private void addSnapshotListener() {
                 .build()));
   }
 
+  private SnapshotChunk decodeSnapshotChunk(final InstallRequest request) {
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:392]: Maybe we can have a legacy util class or something where we keep this code and can it remove it more easily. This might be also easier to track then.

File: atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/FileBasedReceivedSnapshot.java [hunk 3]
```diff
@@ -192,27 +192,29 @@ public PersistedSnapshot persist() {
     final var files = directory.toFile().listFiles();
     Objects.requireNonNull(files, "No chunks have been applied yet");
 
-    if (files.length != expectedTotalCount) {
+    if (expectedTotalCount != Integer.MIN_VALUE && files.length != expectedTotalCount) {
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/FileBasedReceivedSnapshot.java:195]: I think it feels less hacky if you name the constants. Like FALLBACK_TOTAL_COUNT or something

File: atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/FileBasedReceivedSnapshot.java [hunk 4]
```diff
@@ -192,27 +192,29 @@ public PersistedSnapshot persist() {
...
-    } catch (final IOException e) {
-      throw new UncheckedIOException("Unexpected exception on calculating snapshot checksum.", e);
-    }
-
-    if (actualSnapshotChecksum != expectedSnapshotChecksum) {
-      throw new IllegalStateException(
-          String.format(
-              "Expected snapshot checksum %d, but calculated %d.",
-              expectedSnapshotChecksum, actualSnapshotChecksum));
+    if (expectedSnapshotChecksum != Long.MIN_VALUE) {
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/FileBasedReceivedSnapshot.java:202]: The same here - currently I would ask why it should be min value. But if you add a constant which describes this a bit better I think it would be clearer

File: atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/SnapshotChunkUtil.java [hunk 5]
```diff
@@ -23,6 +25,36 @@ static long createChecksum(final byte[] content) {
...
+   *
+   * <p>The snapshot chunk will take most of its information from the install request, and use the
+   * data as the chunk content, while setting the total count to {@link Integer#MIN_VALUE} and the
+   * snapshot checksum to {@link Long#MIN_VALUE} so that neither will be validated against. See
+   * {@link FileBasedReceivedSnapshot} for more on that.
+   *
+   * @param request the install request to build from
+   * @return a valid {@link SnapshotChunk} built from the request
+   */
+  public static SnapshotChunk fromOldInstallRequest(final InstallRequest request) {
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/SnapshotChunkUtil.java:40]: I think we need a mechanism to track these kind of methods or logic, which we expect to remove at some point. Maybe via annotation or adding it to a separate class which can be tracked more easily.

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @npepinpe for fixing it I think in general it is good. I added some comments to it how we could improve it.

File: atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/FileBasedReceivedSnapshot.java (hunk 4 above)
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/FileBasedReceivedSnapshot.java:202]: iirc I think SBE uses this as the null value, so I assume this came from there - naming the constants is probably anyway the better solution :+1:

File: atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/SnapshotChunkUtil.java (hunk 5 above)
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/SnapshotChunkUtil.java:40]: I'll group all that legacy stuff together :+1:

**Comment by npepinpe** [comment]
@Zelldon I updated based on your review - let me know how it looks

**Comment by Zelldon** [comment]
Like it 👍do you think it makes sense to also move the decoding part in the Passiverole into a static method which lies in a Legacy marked class?

**Comment by npepinpe** [comment]
I guess semantically it doesn't really fit (e.g. replacing the call to `decodeSnapshotChunk` by `LegacySnapshotChunk.decode`, as the normal case is to not use the `LegacySnapshotChunk`), but pragmatically it makes it a lot easier to spot what needs changing when we remove `LegacySnapshotChunk`. I would leave it as is, tbh, as it's more explicit `LegacySnapshotChunk` is a fall back, and looking for usages it will still be obvious that we need to update `PassiveRole` I think.

**Review by ChrisKujawa — APPROVED** [review]
Thanks :+1:
