### PR TITLE
fix(broker): use correct address for binding and advertising

### LINKED ISSUE #5426: Failed to bind TCP server to port 0.0.0.0:8443 due to io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
My issue is a followup of https://github.com/zeebe-io/zeebe/issues/5410. The answer to that issue helped me set up advertised addresses and hosts for command, internal and monitoring APIs (I'm mostly interested in the first two though).

After having set that up accordingly, the broker crashes because 0.0.0.0:8443 is in use by another service. 8443 is a proxy port, not a port that the broker has to be listening to. This is very strange behavior. Please look at my log below. It shows the application.yml settings and the errors I'm getting. Thank you for the help.
```
$ kubectl logs pod/zeebe-cluster-0 -n 103462-zeebe-2-dev
Using startup_fromconfmap.sh as startup script.
This is updated by a rolling restart.
+ echo 'Using startup_fromconfmap.sh as startup script.'
+ echo 'This is updated by a rolling restart.'
+ export ZEEBE_BROKER_CLUSTER_NODEID=0
+ ZEEBE_BROKER_CLUSTER_NODEID=0
+ ZEEBE_NODE_ID=0
++ hostname -f
+ export ZEEBE_BROKER_NETWORK_HOST=zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local
+ ZEEBE_BROKER_NETWORK_HOST=zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local
+ export ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDHOST=zeebe-broker-0-command.apps.mt-d1.pool1.proxydomain.net
+ ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDHOST=zeebe-broker-0-command.apps.mt-d1.pool1.proxydomain.net
+ export ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDPORT=8443
+ ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDPORT=8443
+ export ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDHOST=zeebe-broker-0-internal.apps.mt-d1.pool1.proxydomain.net
+ ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDHOST=zeebe-broker-0-internal.apps.mt-d1.pool1.proxydomain.net
+ export ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDPORT=8443
+ ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDPORT=8443
+ echo 'ZEEBE_STANDALONE_GATEWAY is false'
ZEEBE_STANDALONE_GATEWAY is false
+ '[' false = true ']'
+ ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502
+ (( i=0 ))
+ (( i<6/2 ))
+ '[' 0 '!=' 0 ']'
+ (( i++  ))
+ (( i<6/2 ))
+ '[' 0 '!=' 1 ']'
++ hostname -d
+ ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-cluster-1.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502
+ (( i++  ))
+ (( i<6/2 ))
+ '[' 0 '!=' 2 ']'
++ hostname -d
+ ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-cluster-1.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-cluster-2.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502
+ (( i++  ))
+ (( i<6/2 ))
+ REMOTE_BROKER_0=zeebe-broker-0-internal.apps.mt-d1.pool2.proxydomain.net:8443
+ REMOTE_BROKER_1=zeebe-broker-1-internal.apps.mt-d1.pool2.proxydomain.net:8443
+ REMOTE_BROKER_2=zeebe-broker-2-internal.apps.mt-d1.pool2.proxydomain.net:8443
+ ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-cluster-1.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-cluster-2.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-broker-0-internal.apps.mt-d1.pool2.proxydomain.net:8443,zeebe-broker-1-internal.apps.mt-d1.pool2.proxydomain.net:8443,zeebe-broker-2-internal.apps.mt-d1.pool2.proxydomain.net:8443
+ export ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-cluster-1.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-cluster-2.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-broker-0-internal.apps.mt-d1.pool2.proxydomain.net:8443,zeebe-broker-1-internal.apps.mt-d1.pool2.proxydomain.net:8443,zeebe-broker-2-internal.apps.mt-d1.pool2.proxydomain.net:8443
+ ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-cluster-1.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-cluster-2.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502,zeebe-broker-0-internal.apps.mt-d1.pool2.proxydomain.net:8443,zeebe-broker-1-internal.apps.mt-d1.pool2.proxydomain.net:8443,zeebe-broker-2-internal.apps.mt-d1.pool2.proxydomain.net:8443
+ exec /usr/local/zeebe/bin/broker
  ______  ______   ______   ____    ______     ____    _____     ____    _  __  ______   _____
 |___  / |  ____| |  ____| |  _ \  |  ____|   |  _ \  |  __ \   / __ \  | |/ / |  ____| |  __ \
    / /  | |__    | |__    | |_) | | |__      | |_) | | |__) | | |  | | | ' /  | |__    | |__) |
   / /   |  __|   |  __|   |  _ <  |  __|     |  _ <  |  _  /  | |  | | |  <   |  __|   |  _  /
  / /__  | |____  | |____  | |_) | | |____    | |_) | | | \ \  | |__| | | . \  | |____  | | \ \
 /_____| |______| |______| |____/  |______|   |____/  |_|  \_\  \____/  |_|\_\ |______| |_|  \_\

2020-09-24 13:53:21.495 [] [main] INFO  io.zeebe.broker.StandaloneBroker - Starting StandaloneBroker v0.23.2 on zeebe-cluster-0 with PID 1 (/usr/local/zeebe/lib/zeebe-distribution-0.23.2.jar started by ? in /usr/local/zeebe)
2020-09-24 13:53:21.499 [] [main] INFO  io.zeebe.broker.StandaloneBroker - No active profile set, falling back to default profiles: default
2020-09-24 13:53:22.413 [] [main] INFO  io.zeebe.broker.StandaloneBroker - Started StandaloneBroker in 1.341 seconds (JVM running for 2.432)
2020-09-24 13:53:22.480 [] [main] INFO  io.zeebe.broker.system - Version: 0.23.2
2020-09-24 13:53:22.581 [] [main] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local",
    "commandApi" : {
      "host" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local",
      "port" : 26501,
      "advertisedHost" : "zeebe-broker-0-command.apps.mt-d1.pool1.proxydomain.net",
      "advertisedPort" : 8443,
      "address" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26501",
      "advertisedAddress" : "zeebe-broker-0-command.apps.mt-d1.pool1.proxydomain.net:8443"
    },
    "internalApi" : {
      "host" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local",
      "port" : 26502,
      "advertisedHost" : "zeebe-broker-0-internal.apps.mt-d1.pool1.proxydomain.net",
      "advertisedPort" : 8443,
      "address" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502",
      "advertisedAddress" : "zeebe-broker-0-internal.apps.mt-d1.pool1.proxydomain.net:8443"
    },
    "monitoringApi" : {
      "host" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local",
      "port" : 9600,
      "advertisedHost" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local",
      "advertisedPort" : 9600,
      "address" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:9600",
      "advertisedAddress" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502", "zeebe-cluster-1.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502", "zeebe-cluster-2.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502", "zeebe-broker-0-internal.apps.mt-d1.pool2.proxydomain.net:8443", "zeebe-broker-1-internal.apps.mt-d1.pool2.proxydomain.net:8443", "zeebe-broker-2-internal.apps.mt-d1.pool2.proxydomain.net:8443" ],
    "partitionIds" : [ 1, 2 ],
    "nodeId" : 0,
    "partitionsCount" : 2,
    "replicationFactor" : 3,
    "clusterSize" : 6,
    "clusterName" : "zeebe-cluster",
    "gossipFailureTimeout" : 10000,
    "gossipInterval" : 250,
    "gossipProbeInterval" : 1000
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/usr/local/zeebe/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT15M",
    "logIndexDensity" : 100,
    "logSegmentSizeInBytes" : 536870912,
    "atomixStorageLevel" : "DISK"
  },
  "exporters" : {
    "elasticsearch" : {
      "jarPath" : null,
      "className" : "io.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "url" : "http://zeebe-elasticsearch-service:9200",
        "bulk" : {
          "delay" : 5,
          "size" : 1000
        },
        "index" : {
          "prefix" : "zeebe-record",
          "createTemplate" : true,
          "command" : false,
          "event" : true,
          "rejection" : false,
          "deployment" : true,
          "error" : true,
          "incident" : true,
          "job" : true,
          "jobBatch" : false,
          "message" : false,
          "messageSubscription" : false,
          "variable" : true,
          "variableDocument" : true,
          "workflowInstance" : true,
          "workflowInstanceCreation" : false,
          "workflowInstanceSubscription" : false,
          "ignoreVariablesAbove" : 32677
        }
      },
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M"
}
2020-09-24 13:53:22.599 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/11]: actor scheduler
2020-09-24 13:53:22.601 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/11]: membership and replication protocol
2020-09-24 13:53:24.847 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/11]: command api transport
2020-09-24 13:53:25.138 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/11]: command api handler
2020-09-24 13:53:25.170 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/11]: subscription api
2020-09-24 13:53:25.189 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/11]: embedded gateway
2020-09-24 13:53:25.194 [] [main] INFO  io.zeebe.gateway - Version: 0.23.2
2020-09-24 13:53:25.195 [] [main] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 26500,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local:26502",
    "requestTimeout" : "PT15S",
    "clusterName" : "zeebe-cluster",
    "memberId" : "gateway",
    "host" : "0.0.0.0",
    "port" : 26502
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "zeebe-cluster-0.zeebe-cluster.103462-zeebe-2-dev.svc.cluster.local",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  },
  "enable" : true
}
2020-09-24 13:53:25.298 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/11]: cluster services
2020-09-24 13:53:25.302 [] [netty-messaging-event-epoll-server-0] WARN  io.atomix.cluster.messaging.impl.NettyMessagingService - Failed to bind TCP server to port 0.0.0.0:8443 due to io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
2020-09-24 13:53:25.303 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/11]: cluster services failed with unexpected exception.
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bind$32(NettyMessagingService.java:699) ~[atomix-cluster-0.23.2.jar:0.23.2]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:993) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:552) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
2020-09-24 13:53:25.307 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [1/6]: embedded gateway
2020-09-24 13:53:25.313 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [2/6]: subscription api
2020-09-24 13:53:25.314 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [3/6]: command api handler
2020-09-24 13:53:25.314 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [4/6]: command api transport
2020-09-24 13:53:27.329 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [5/6]: membership and replication protocol
2020-09-24 13:53:27.331 [] [main] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.primitive.partition.impl.DefaultPartitionService$$Lambda$529/0x000000080056c440@3de8f85c not registered
2020-09-24 13:53:27.334 [] [main] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService$$Lambda$530/0x000000080056b840@359e27d2 not registered
2020-09-24 13:53:27.338 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [6/6]: actor scheduler
2020-09-24 13:53:27.340 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 6 steps in 2033 ms.
2020-09-24 13:53:27.340 [] [main] ERROR io.zeebe.broker.system - Failed to start broker 0!
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bind$32(NettyMessagingService.java:699) ~[atomix-cluster-0.23.2.jar:0.23.2]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:993) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:552) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
2020-09-24 13:53:27.343 [] [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener -
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-09-24 13:53:27.345 [] [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
        at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:46) [zeebe-distribution-0.23.2.jar:0.23.2]
Caused by: io.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
        at io.zeebe.broker.Broker.internalStart(Broker.java:142) ~[zeebe-broker-0.23.2.jar:0.23.2]
        at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-0.23.2.jar:0.23.2]
        at io.zeebe.broker.Broker.start(Broker.java:115) ~[zeebe-broker-0.23.2.jar:0.23.2]
        at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:59) ~[zeebe-distribution-0.23.2.jar:0.23.2]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
        ... 5 more
Caused by: java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bind$32(NettyMessagingService.java:699) ~[atomix-cluster-0.23.2.jar:0.23.2]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:993) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:552) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387) ~[netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```

Update 1:

I changed the ports to different numbers (because 8443 is used for both command and internal APIs - just different hostname) and I noticed that where it says 0.0.0.0:8443 already in use, the port it is trying to use is ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDPORT. I can understand that gateways listen to brokers on port 26502 just like brokers listen to other brokers on this port. The issue appears to be related to this. Still no solution to this error. Both gateways and brokers listen on port 26502,

I wonder how this is handled in code when one is using the embedded broker approach: how does the embedded gateway talk to the broker if both of them use the same port?

Update 2:

I am ruling out the gateway being the culprit. I have set different host and cluster.host values for the gateway (127.0.0.1) and the 0.0.0.0:8443 message persists. I think the bug is within the internalApi network configuration. In particular, I suspect the bug might be in the following function:

```
 public void applyDefaults(final NetworkCfg networkCfg) {
    advertisedHost =
        Optional.ofNullable(advertisedHost)
            .orElseGet(() -> Optional.ofNullable(host).orElseGet(networkCfg::getAdvertisedHost));
    host = Optional.ofNullable(host).orElse(networkCfg.getHost());
    port = Optional.ofNullable(port).orElse(defaultPort) + networkCfg.getPortOffset() * 10;
    advertisedPort =
        Optional.ofNullable(advertisedPort)
            .map(p -> p + networkCfg.getPortOffset() * 10)
            .orElse(port);
 }
```

I suspect that somehow the port and advertisedPort are taking the value of 8443, and host and advertisedHost are both taking 0.0.0.0 for reasons I don't understand, even though in the configuration I never set 0.0.0.0 for any hosts.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

* Fix Atomix and CommandAPI so that it uses configured host and port to bind and use advertisedHost and advertisedPort for advertising to other nodes

## Related issue

closes #5426

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Can we backport this as well?

**Comment by deepthidevaki** [comment]
> Can we backport this as well?

Yes. I forgot it :+1:

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/AdvertisedAddressTest.java [hunk 1]
```diff
@@ -0,0 +1,167 @@
...
+
+  @Rule public final Network network = Network.newNetwork();
+
+  @Rule
+  public final ToxiproxyContainer toxiproxy =
+      new ToxiproxyContainer(TOXIPROXY_IMAGE)
+          .withNetwork(network)
+          .withNetworkAliases(TOXIPROXY_NETWORK_ALIAS);
+
+  private List<ZeebeContainer> containers;
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/AdvertisedAddressTest.java:54]: `ZeebeContainer` use the embedded gateway - did you mean to use `ZeebeBrokerContainer`? I guess here we don't want the gateway to be behind the proxy since it's currently broken, right?

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/AdvertisedAddressTest.java [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+        .withEnv(
+            "ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDPORT",
+            String.valueOf(internalApiProxy.getOriginalProxyPort()))
+        .withEnv("ZEEBE_BROKER_NETWORK_MONITORINGAPI_ADVERTISEDHOST", TOXIPROXY_NETWORK_ALIAS)
+        .withEnv(
+            "ZEEBE_BROKER_NETWORK_MONITORINGAPI_ADVERTISEDPORT",
+            String.valueOf(monitoringApiProxy.getOriginalProxyPort()))
+        // Since gossip does not work with ToxiProxy, increase the sync interval so changes are
+        // propagated faster
+        .withEnv("ZEEBE_BROKER_CLUSTER_MEMBERSHIP_SYNCINTERVAL", "1s");
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/network/AdvertisedAddressTest.java:151]: Any reason not to make it even faster? Or would it make no difference?

**Review by npepinpe — CHANGES_REQUESTED** [review]
Thanks Deepthi! Looks good! 

I didn't see changes in the unicast service - how does it work there? Don't we ever tell nodes to reply to use to a particular address? Where is this address coming from?

I think in the `NettyUnicastService`, each `Message` contains our local address so nodes know who to reply to (correct me if I'm wrong). I think the address in this case may be the node address (from the `MemberConfig`), so that would be the advertised address, right? Just to be sure, since I guess the new integration test doesn't cover this case?

As usual, all comments with `Nit:` prefixed, you can ignore if you feel strongly against them :+1:

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 3]
```diff
@@ -574,46 +592,38 @@ private RemoteClientConnection getOrCreateClientConnection(final Channel channel
...
    */
   private void bind(
       final ServerBootstrap bootstrap,
-      final Iterator<String> ifaces,
-      final int port,
+      final Iterator<Address> addressIterator,
       final CompletableFuture<Void> future) {
-    if (ifaces.hasNext()) {
-      final String iface = ifaces.next();
+    if (addressIterator.hasNext()) {
```
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:613]: No. We don't bind to multiple interfaces. But it is unrelated to this PR. I would suggest to address it in a different issue. Let's keep the scope of the PR with in the issue.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/AdvertisedAddressTest.java (hunk 1 above)
Comment (deepthidevaki) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/network/AdvertisedAddressTest.java:54]: It does not really matter. But since the test have standalone gateway, it would be better to use ZeebeBrokerContainer.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/network/AdvertisedAddressTest.java (hunk 2 above)
Comment (deepthidevaki) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/network/AdvertisedAddressTest.java:151]: No. I don't know if it makes a difference. We are not expecting any topology changes after the startup.

**Comment by deepthidevaki** [comment]
> I didn't see changes in the unicast service - how does it work there? Don't we ever tell nodes to reply to use to a particular address? Where is this address coming from?
> 
> I think in the `NettyUnicastService`, each `Message` contains our local address so nodes know who to reply to (correct me if I'm wrong). I think the address in this case may be the node address (from the `MemberConfig`), so that would be the advertised address, right? Just to be sure, since I guess the new integration test doesn't cover this case?
> 

Yes. That is correct. Both NettyUnicastService and NettyMessagingService uses the member's address (advertisedAddress) as returnAddress. And uses the interfaces in MessagingConfig as the address to bind to. Both services had it implemented correctly, the bug was that we were not configuring it correctly. So that's why I did not have to change anything in NettyUnicastService.

**Review by npepinpe — APPROVED** [review]
:tada:
