### PR TITLE
fix: ensure scheduled tasks are closed before shutdown

### LINKED ISSUE #31151: Segfault in `CommandRedistributor`
### 

### 

### 

### 

### Description

A SIGSEGV occurs when running tests and potentially in production too

```
Current thread (0x00007f995cabd510):  JavaThread "zb-actors-0"        [_thread_in_native, id=375614, stack(0x00007f9a4b800000,0x00007f9a4b900000) (1024K)]

Stack: [0x00007f9a4b800000,0x00007f9a4b900000],  sp=0x00007f9a4b8fe2d0,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [librocksdbjni15077634749360731091.so+0x97c3c8]  rocksdb::OptimisticTransaction::CommitWithParallelValidate()+0x78
C  [librocksdbjni15077634749360731091.so+0x97c865]  rocksdb::OptimisticTransaction::Commit()+0x55
C  [librocksdbjni15077634749360731091.so+0x36cd6e]  Java_org_rocksdb_Transaction_commit+0x1e
J 13460  org.rocksdb.Transaction.commit(J)V (0 bytes) @ 0x00007f9a72b0a861 [0x00007f9a72b0a7a0+0x00000000000000c1]
J 33955 c2 io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInNewTransaction(Lio/camunda/zeebe/db/TransactionOperation;)V (41 bytes) @ 0x00007f9a72b1bae4 [0x00007f9a72b1b940+0x00000000000001a4]
J 24581 c2 io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(Lio/camunda/zeebe/db/TransactionOperation;)V (77 bytes) @ 0x00007f9a72871c9c [0x00007f9a72871b00+0x000000000000019c]
J 30123 c1 io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEach(Ljava/util/function/BiConsumer;)V (12 bytes) @ 0x00007f9a6ae50b74 [0x00007f9a6ae50460+0x0000000000000714]
j  io.camunda.zeebe.engine.state.distribution.DbDistributionState.foreachRetriableDistribution(Lio/camunda/zeebe/engine/state/immutable/DistributionState$PendingDistributionVisitor;)V+30
j  io.camunda.zeebe.engine.processing.distribution.CommandRedistributor.runRetryCycle()V+19
j  io.camunda.zeebe.engine.processing.distribution.CommandRedistributor$$Lambda+0x00007f9a0b94bc90.run()V+4
J 21860 c1 io.camunda.zeebe.stream.api.scheduling.SimpleProcessingScheduleService$$Lambda+0x00007f9a0b949a48.run()V (18 bytes) @ 0x00007f9a6c7cd89c [0x00007f9a6c7cd660+0x000000000000023c]
J 17824 c1 io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl$ScheduledTaskImpl.run()V (67 bytes) @ 0x00007f9a6c102bfc [0x00007f9a6c1028a0+0x000000000000035c]
J 31145 c2 io.camunda.zeebe.scheduler.ActorJob.execute(Lio/camunda/zeebe/scheduler/ActorThread;)V (19 bytes) @ 0x00007f9a7328e0e8 [0x00007f9a7328df00+0x00000000000001e8]
J 26621 c2 io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask()V (213 bytes) @ 0x00007f9a7285724c [0x00007f9a72856ec0+0x000000000000038c]
J 28146 c2 io.camunda.zeebe.scheduler.ActorThread.doWork()V (183 bytes) @ 0x00007f9a7271e7cc [0x00007f9a7271de20+0x00000000000009ac]
J 19842 c2 io.camunda.zeebe.scheduler.ActorThread.run()V (74 bytes) @ 0x00007f9a72e85a7c [0x00007f9a72e859e0+0x000000000000009c]
v  ~StubRoutines::call_stub 0x00007f9a71c5fc86
V  [libjvm.so+0x8cfcdb]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*)+0x2db
V  [libjvm.so+0x8d15af]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, JavaThread*)+0x1bf
V  [libjvm.so+0x9a99ac]  thread_entry(JavaThread*, JavaThread*)+0x8c
V  [libjvm.so+0x8e64d8]  JavaThread::thread_main_inner() [clone .part.0]+0xb8
V  [libjvm.so+0xeaab7f]  Thread::call_run()+0x9f
V  [libjvm.so+0xcc6555]  thread_native_entry(Thread*)+0xd5
C  [libc.so.6+0x71324]  start_thread+0x2e4
```

### Steps to reproduce

Running all engine tests under stress sometimes reproduces the issue

### Current behavior

Segfault

### Expected behavior

No segfault

### Environment

SaaS & SM

### Version

Snapshot

### Rootcause

It appears like the `CommandRedistributor` is running after the regular stream processor has shut down already: 

```
16:36:10.937 [StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Recovering state of partition 1 from snapshot
16:36:10.937 [StreamProcessor-1] INFO  io.camunda.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
16:36:10.939 [StreamProcessor-1] INFO  io.camunda.zeebe.processor - Processor starts replay of events. [snapshot-position: -1, replay-mode: PROCESSING]
16:36:10.939 [StreamProcessor-1] INFO  io.camunda.zeebe.processor - Processor finished replay, with [lastProcessedPosition: -1, lastWrittenPosition: -1]
16:36:10.964 [StreamProcessor-2] DEBUG io.camunda.zeebe.logstreams - Recovering state of partition 2 from snapshot
16:36:10.964 [StreamProcessor-2] INFO  io.camunda.zeebe.logstreams - Recovered state of partition 2 from snapshot at position -1
16:36:10.966 [StreamProcessor-2] INFO  io.camunda.zeebe.processor - Processor starts replay of events. [snapshot-position: -1, replay-mode: PROCESSING]
16:36:10.966 [StreamProcessor-2] INFO  io.camunda.zeebe.processor - Processor finished replay, with [lastProcessedPosition: -1, lastWrittenPosition: -1]
16:36:11.185 [] DEBUG io.camunda.zeebe.broker.logstreams - Close stream processor
16:36:11.185 [StreamProcessor-2] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller StreamProcessor-2.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f996797c3c8, pid=359074, tid=375614
```

This would probably result in an attempt to access the state after it has been closed already.

### Solution ideas

Ensure that closing the `AsyncScheduleServiceContext` finishes before proceeding with shutdown of other components, including the runtime state.

### Dev -> QA handover

_No response_

### Links

_No response_

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This fixes bug where the actors running scheduled tasks were not started and stopped properly before proceeding with the overall stream processor startup and shutdown.

In rare cases, this would lead to SIGSEGV when a scheduled task such as `CommandRedistributor` would try to access the runtime state after it has already been closed.

The issue was that `AsyncUtil` returned futures that would complete with the first step, not waiting on any further steps.

Instead of `AsyncUtil`, we now use `ActorFutureCollector` and discard  the result. Technically, this comes with a slight overhead but that's  acceptable since startup and shutdown are not in the hot path.

The broken `AsyncUtil` is removed entirely, if a new implementation is needed, it should be tested properly and be part of already existing utility classes such as `FutureUtil`.

closes #31151

### CODE REVIEW

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/StreamProcessor.java [hunk 1]
```diff
@@ -372,30 +371,35 @@ private void onRecovered(final LastProcessingPositions lastProcessingPositions)
...
-        this::onFailure);
+    processorActorService
+        .open(actor)
+        .andThen(() -> asyncScheduleServiceContext.submitActors(actor), actor)
+        .onComplete(
+            (ignored, error) -> {
+              if (error != null) {
+                onFailure(error);
+              }
+              startProcessing(lastProcessingPositions);
```
Comment (entangled90) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/StreamProcessor.java:382]: :question: should we start processing even  if there is an error in the future?

Comment (lenaschoenburg) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/StreamProcessor.java:382]: Oops, no we shouldn't :grimacing: 
I think that the `onFailure` will prevent that anyway but let's make it clearer :+1:

**Review by entangled90 — APPROVED** [review]
:rocket:
