### PR TITLE
Fix xor incident resolving on workflow instance canceling 

### LINKED ISSUE #1681: Incidents on XOR Gateway are not resolved on wf instance cancel
See the failing test case:

```java

  @Test
  public void shouldResolveIncidentIfInstanceCanceled() {
    // given
    testClient.deploy(
      Bpmn.createExecutableProcess("workflow")
        .startEvent()
        .exclusiveGateway("xor")
        .sequenceFlowId("s1")
        .condition("$.foo < 5")
        .endEvent()
        .moveToLastGateway()
        .sequenceFlowId("s2")
        .condition("$.foo >= 5 && $.foo < 10")
        .endEvent()
        .done());

    long workflowInstance = testClient.createWorkflowInstance("workflow", asMsgPack("foo", "bar"));

    // when
    testClient.receiveFirstIncidentEvent(IncidentIntent.CREATED);
    testClient.cancelWorkflowInstance(workflowInstance);

    // then incident is resolved
    final Record incidentEvent = testClient.receiveFirstIncidentEvent(IncidentIntent.RESOLVED);

    assertThat(incidentEvent.getKey()).isGreaterThan(0);
    assertIncidentRecordValue(
      ErrorType.CONDITION_ERROR.name(),
      "Cannot compare values of different types: STRING and INTEGER",
      "xor",
      incidentEvent);
  }
```

### PR DESCRIPTION
**Pull request by ChrisKujawa**
closes #1681

### CODE REVIEW

File: broker-core/src/main/java/io/zeebe/broker/incident/processor/IncidentState.java [hunk 1]
```diff
@@ -165,4 +166,15 @@ public long getJobIncidentKey(long jobKey) {
   public boolean isJobIncident(IncidentRecord record) {
     return record.getJobKey() > 0;
   }
+
+  public void forExistingWorkflowIncident(
+      long elementInstanceKey, BiConsumer<Long, IncidentRecord> resolver) {
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/incident/processor/IncidentState.java]: Use a different interface which accepts a primitive `long` (e.g. `ObjLongConsumer`).

File: broker-core/src/main/java/io/zeebe/broker/workflow/processor/flownode/TerminateFlowNodeHandler.java [hunk 2]
```diff
@@ -61,23 +65,7 @@ public void handle(BpmnStepContext<T> context) {
...
-
-    final long workflowIncidentKey =
-        incidentState.getWorkflowInstanceIncidentKey(elementInstanceKey);
-
-    final boolean hasIncident = workflowIncidentKey != IncidentState.MISSING_INCIDENT;
-    if (hasIncident) {
-      final IncidentRecord incidentRecord = incidentState.getIncidentRecord(workflowIncidentKey);
-      context.getOutput().appendResolvedIncidentEvent(workflowIncidentKey, incidentRecord);
-    }
+  public void resolveExistingIncident(long incidentKey, IncidentRecord incidentRecord) {
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/workflow/processor/flownode/TerminateFlowNodeHandler.java]:
```suggestion
  private void resolveExistingIncident(long incidentKey, IncidentRecord incidentRecord) {
```

File: broker-core/src/main/java/io/zeebe/broker/workflow/processor/subprocess/TerminateContainedElementsHandler.java [hunk 3]
```diff
@@ -63,4 +80,8 @@ public void handle(BpmnStepContext<ExecutableFlowElementContainer> context) {
       }
     }
   }
+
+  public void resolveExistingIncident(long workflowIncidentKey, IncidentRecord incidentRecord) {
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/workflow/processor/subprocess/TerminateContainedElementsHandler.java]:
```suggestion
  private void resolveExistingIncident(long workflowIncidentKey, IncidentRecord incidentRecord) {
```

File: broker-core/src/main/java/io/zeebe/broker/workflow/state/ElementInstanceState.java [hunk 4]
```diff
@@ -327,6 +327,29 @@ public void updateFailedToken(IndexedRecord indexedRecord) {
...
+  private void visitTokens(long scopeKey, Purpose purpose, TokenVisitor visitor) {
+    longKeyPurposeBuffer.putLong(0, scopeKey, STATE_BYTE_ORDER);
+    longKeyPurposeBuffer.putByte(Long.BYTES, (byte) purpose.ordinal());
+
+    rocksDbWrapper.whileEqualPrefix(
+        tokenParentChildHandle,
+        longKeyPurposeBuffer.byteArray(),
+        (key, value) -> {
+          final StoredRecord tokenEvent =
+              getTokenEvent(getLong(key, Long.BYTES + BitUtil.SIZE_OF_BYTE));
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/workflow/state/ElementInstanceState.java]: Add a `null` check to fail fast if the state is corrupted.

File: broker-core/src/main/java/io/zeebe/broker/workflow/state/ElementInstanceState.java [hunk 5]
```diff
@@ -327,6 +327,29 @@ public void updateFailedToken(IndexedRecord indexedRecord) {
...
+  @FunctionalInterface
+  public interface TokenVisitor {
+    void visitToken(IndexedRecord indexedRecord);
+  }
+
+  public void visitFailedTokens(long scopeKey, TokenVisitor visitor) {
+    visitTokens(scopeKey, Purpose.FAILED_TOKEN, visitor);
+  }
+
+  private void visitTokens(long scopeKey, Purpose purpose, TokenVisitor visitor) {
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/workflow/state/ElementInstanceState.java]: This method is similar to `getTokenEvents(...)`. Can we delete the other one?

File: broker-core/src/test/java/io/zeebe/broker/incident/ExpressionIncidentTest.java [hunk 6]
```diff
@@ -351,4 +351,38 @@ public void shouldResolveIncidentForExclusiveGatewayWithoutMatchingCondition() {
     testClient.receiveFirstIncidentEvent(IncidentIntent.RESOLVED);
     testClient.receiveElementInState("workflow", ELEMENT_COMPLETED);
   }
+
+  @Test
+  public void shouldResolveIncidentIfInstanceCanceled() {
+    // given
+    testClient.deploy(
+        Bpmn.createExecutableProcess("workflow")
```
Comment (saig0) [inline broker-core/src/test/java/io/zeebe/broker/incident/ExpressionIncidentTest.java]: This workflow is used multiple times in the test class. We should write it only once :)

**Review by saig0 — CHANGES_REQUESTED** [review]

File: broker-core/src/main/java/io/zeebe/broker/workflow/state/ElementInstanceState.java (hunk 5 above)
Comment (Zelldon) [reply broker-core/src/main/java/io/zeebe/broker/workflow/state/ElementInstanceState.java]: I refactored a bit the method. I tried also to avoid creating garbage in the getToken method, but this was in the end not easy possible. I would like to postpone this until we refactor the whole stuff.

**Comment by Zelldon** [comment]
@saig0 please see the latest comiit

**Review by saig0 — APPROVED** [review]

File: broker-core/src/main/java/io/zeebe/broker/workflow/state/ElementInstanceState.java (hunk 5 above)
Comment (Zelldon) [reply broker-core/src/main/java/io/zeebe/broker/workflow/state/ElementInstanceState.java]: https://github.com/zeebe-io/zeebe/issues/1691 :)
