### PR TITLE
fix: skip clients w/o permissions in keycloak migration

### LINKED ISSUE #35431: Identity Migration App fails on Console and Web Modeler Client Migration
### <!-- Component -->

<!-- Identity- -->

### <!-- Affected version -->

<!-- -8.8 -->

### <!-- Severity -->

<!-- High- -->

### <!-- Likelihood -->

<!-- High_ -->

### Description

The Identity Migration app fails in a keycloak setup migrating the clients with:
```
io.camunda.application.commons.migration.BlockingMigrationsRunner - The cause of the failed migration was: 403  on GET request for "https://hamzatest.ci.distro.ultrawombat.com/identity/api/clients/c9dbd5f9-68de-4289-9242-031a00a444c9/permissions": "{"errors":["clientType.invalid"]}"                                                                                                                                                                                                                                                    camunda-identity-migration-job-sfln2 org.springframework.web.client.HttpClientErrorException$Forbidden: 403  on GET request for "https://hamzatest.ci.distro.ultrawombat.com/identity/api/clients/c9dbd5f9-68de-4289-9242-031a00a444c9/permissions": "{"errors":["clientType.invalid"]}"
```

This happens when the migration iterates over client with a different type than "m2m".

### Steps to reproduce

In a Self-Managed with Keycloak environment:

1. Setup a an application with a type different than m2m in management identity
<img width="802" height="281" alt="Image" src="https://github.com/user-attachments/assets/a0524025-f0a0-4ea3-86cd-228e847d7b3a" />
2. run the identity migration app 

### Current behavior

It fails on the client that is not of m2m type, as reading permissions for it fails with a 403 and the cause being `"{"errors":["clientType.invalid"]}"`

### Expected behavior

It should just skip such clients, it's actually only required to migrate m2m clients.

### Environment

SM

### Version

- Component Version: 8.8.0-SNAPSHOT


### Rootcause

The migration is trying to migrate non m2m clients, while only m2m clients are relevant to migrate.

### Solution ideas

skip non m2m clients

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):


### Links

_No response_

### PR DESCRIPTION
**Pull request by megglos**
## Description

The migration app was failing when encountering "PUBLIC" clients returned from management identity.

This instructs it to only handle supported clients of type m2m and confidential and skip everything else, issuing a debug log in this expected but handled case. See the equivalent logic in management identity [here](https://github.com/camunda-cloud/identity/blob/d76e23bc85c76c1c31ace0fd1d21e148706a9885/management-api/src/main/java/io/camunda/identity/impl/keycloak/initializer/service/ClientInitializationService.java#L216).
## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #35431

### CODE REVIEW

File: migration/identity-migration/src/main/java/io/camunda/migration/identity/dto/ClientType.java [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+ * one or more contributor license agreements. See the NOTICE file distributed
+ * with this work for additional information regarding copyright ownership.
+ * Licensed under the Camunda License 1.0. You may not use this file
+ * except in compliance with the Camunda License 1.0.
+ */
+package io.camunda.migration.identity.dto;
+
+import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
+
+public enum ClientType {
```
Comment (megglos) [inline migration/identity-migration/src/main/java/io/camunda/migration/identity/dto/ClientType.java:12]: compare to https://github.com/camunda-cloud/identity/blob/main/management-api/src/main/java/io/camunda/identity/record/ClientType.java I went for an explicit UNKNOWN type in case there is any upstream change.

File: migration/identity-migration/src/main/java/io/camunda/migration/identity/dto/Client.java [hunk 2]
```diff
@@ -7,4 +7,8 @@
  */
 package io.camunda.migration.identity.dto;
 
-public record Client(String id, String clientId) {}
+public record Client(String id, String clientId, ClientType type) {
+  public Client(final String id, final String clientId) {
+    this(id, clientId, ClientType.M2M);
```
[the remark this answers is not in the document]
Comment (megglos) [reply migration/identity-migration/src/main/java/io/camunda/migration/identity/dto/Client.java:12]: it's for internal use only where we previously assumed to have a valid client, thus UNKNOWN would be a breaking change.

File: migration/identity-migration/src/main/java/io/camunda/migration/identity/handler/sm/ClientMigrationHandler.java [hunk 3]
```diff
@@ -46,57 +46,73 @@ protected List<Client> fetchBatch(final int page) {
...
-            logger.debug(
-                "No permissions found for client '{}', skipping authorization creation.", clientId);
-            return;
-          }
-          totalAuthorizationsCount.incrementAndGet();
+    clients.stream()
+        .filter(
+            client -> {
+              switch (client.type()) {
+                case M2M, CONFIDENTIAL -> {
```
Comment (megglos) [inline migration/identity-migration/src/main/java/io/camunda/migration/identity/handler/sm/ClientMigrationHandler.java:53]: I went for an inclusive solution to make sure, that in the unlikely event of new types we'll just skip them by default.

**Review by nicpuppa — APPROVED** [review]
