### PR TITLE
fix: change IncidentFilter creationTime to OffsetDateTime

### LINKED ISSUE #38827: Camunda Client `IncidentFilter#creationTime` is of type `String` instead of `OffsetDateTime`
### 

### 

### 

### 

### Description

The decribed type is not conforming with the type of the field in the API: https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/search-incidents/

### Steps to reproduce

1. Use Camunda Client
2. Try to apply a creation time
3. String type is required instead of expected OffsetDateTime

### Current behavior

Requires string type

### Expected behavior

Requires OffsetDateTime type

### Workaround

_No response_

### Environment

SaaS & SM

### Version

- Component Version: 8.8.0-rc1

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by megglos**
## Description

Aligns it with other filters.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #38827

### CODE REVIEW

File: clients/java/src/main/java/io/camunda/client/api/search/filter/IncidentFilter.java [hunk 1]
```diff
@@ -91,7 +94,15 @@ public interface IncidentFilter extends SearchRequestFilter {
...
-  IncidentFilter creationTime(final String creationTime);
+  IncidentFilter creationTime(final OffsetDateTime creationTime);
+
+  /**
+   * Filters incidents by creation time of incident.
+   *
+   * @param fn the creationTime {@link DateTimeProperty} consumer of the incident
+   * @return the updated filter
+   */
+  IncidentFilter creationTime(final Consumer<DateTimeProperty> fn);
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/client/api/search/filter/IncidentFilter.java]: ❓ Can we offer this? Does the API support Advanced search?

Comment (megglos) [reply clients/java/src/main/java/io/camunda/client/api/search/filter/IncidentFilter.java]: according to [spec](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/search-incidents/), it doesn't 🫠 So the issue is wider than just the client.

Comment (megglos) [reply clients/java/src/main/java/io/camunda/client/api/search/filter/IncidentFilter.java]: removed advanced filter

File: clients/java/src/main/java/io/camunda/client/impl/search/filter/IncidentFilterImpl.java [hunk 2]
```diff
@@ -83,8 +84,12 @@ public IncidentFilter elementInstanceKey(final Long value) {
   }
 
   @Override
-  public IncidentFilter creationTime(final String creationTime) {
-    filter.setCreationTime(creationTime);
+  public IncidentFilter creationTime(final OffsetDateTime creationTime) {
+    if (creationTime == null) {
+      filter.setCreationTime(null);
+      return this;
+    }
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/client/impl/search/filter/IncidentFilterImpl.java]: 💭 Looking at this, our client implementation for Advanced datetime search will probably [fail with NPEs](https://github.com/camunda/camunda/blob/fed98c2c788483292d1185ad1f71658dcd080ecd/clients/java/src/main/java/io/camunda/client/impl/search/filter/builder/DateTimePropertyImpl.java#L56) when I hand in a `null`. I assume we did not cover that with tests? 🙈

File: clients/java/src/main/java/io/camunda/client/impl/search/filter/IncidentFilterImpl.java [hunk 3]
```diff
@@ -83,8 +84,12 @@ public IncidentFilter elementInstanceKey(final Long value) {
...
+    filter.setCreationTime(creationTime.toString());
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/client/impl/search/filter/IncidentFilterImpl.java]:
```suggestion
    filter.setCreationTime(creationTime == null ? null : creationTime.toString());
```

File: clients/java/src/main/java/io/camunda/client/impl/search/filter/IncidentFilterImpl.java (hunk 2 above)
Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/impl/search/filter/IncidentFilterImpl.java]: Should be easy to fix in the `DateTimePropertyImpl` though. All advanced fields taking a date time object should do a check for null and set accordingly, like propose below.

Comment (megglos) [reply clients/java/src/main/java/io/camunda/client/impl/search/filter/IncidentFilterImpl.java]: I added this to the acceptance criteria of https://github.com/camunda/camunda/issues/33678

**Review by jonathanlukas — COMMENTED** [review]
Should we go the full roundtrip and fix the response type as well? https://github.com/camunda/camunda/blob/main/clients/java/src/main/java/io/camunda/client/api/search/response/Incident.java#L39

**Comment by megglos** [comment]
> Should we go the full roundtrip and fix the response type as well? https://github.com/camunda/camunda/blob/main/clients/java/src/main/java/io/camunda/client/api/search/response/Incident.java#L39

already done on stable and the release branch https://github.com/camunda/camunda/blob/stable/8.8/clients/java/src/main/java/io/camunda/client/api/search/response/Incident.java#L40

main backport is pending [here](https://github.com/camunda/camunda/pull/38486)
