### PR TITLE
fix: lastHistoricalArchiverDate state collision causes incorrect archiving

### LINKED ISSUE #43902: lastHistoricalArchiverDate state collision causes incorrect archiving
## Description:
The ElasticsearchArchiverRepository and OpenSearchArchiverRepository classes improperly share a single state field, lastHistoricalArchiverDate, across all archiving tasks. This field is used to verify and calculate the next index rollover date. Because it is shared, archiving operations for different entity types (e.g., Process Instances vs. Batch Operations) overwrite each other's state.

## Scenario
Archiving is triggered for multiple different templates (e.g., listViewTemplate and batchOperationTemplate) within the same exporter (same partition).

## Actual Behavior
When multiple archive batches run, they read and write to the same `lastHistoricalArchiverDate` field.
If the "Process Instance" archiver advances the date to 2025-05-01, the subsequent "Batch Operation" archiver (which might be processing data from just 2025-01-01) picks up this future date as its baseline. This prevents the correct rollover calculation for the Batch Operations.

## Impact
This causes indices to rollover incorrectly or not at all, potentially leading to massive distinct indices or failure to respect retention policies.

## Proposed Fix
Change the single `lastHistoricalArchiverDate` field to a `Map<String, String>` (`ConcurrentHashMap`) keyed by the index template name.

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #43902

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java [hunk 1]
```diff
@@ -393,10 +397,12 @@ private CompletableFuture<ArchiveBatch> createArchiveBatch(
 
     return dateFuture.thenApply(
         date -> {
-          lastHistoricalArchiverDate =
+          final String nextArchiverDate =
               DateOfArchivedDocumentsUtil.calculateDateOfArchiveIndexForBatch(
                   endDate, date, rolloverInterval, config.getElsRolloverDateFormat());
 
+          lastHistoricalArchiverDates.put(templateIndexName, nextArchiverDate);
```
Comment (yohanfernando) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]: ❓ I'm curious why we want to maintain this `lastHistoricalArchiverDates`? 

The `dateFuture` returns the last set date, or if null, the historical indices would then give the latest index. Which we used in the batch before.. And honestly, it feels wrong to me 🤔 

Then your code now always calculates the date based on the first record in the list and uses that - which feels more correct to me. Now I can't see why the need to keep maintaining this map of last archive dates  🤷

**Review by yohanfernando — COMMENTED** [review]
❓ Regarding the need for this map overall

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java (hunk 1 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]: I had the exact same questions, it seems it was implemented this way to cache this date, and not have to compute it every time from the existing dated indices
This seems to be related to the the handling of rollover intervals that are higher than `1d`, but probably there is an easier way to implement it

Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]: > the historical indices would then give the latest index. Which we used in the batch before.

the existing logic checks if the new `endDate` lands within `lastHistoricalArchiverDate` + rolloverInteval, if not it would create a new date and a new index

Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]: There is a difference with 8.7 implementation which was handling it using [aggregation with calendar interval](https://github.com/camunda/camunda/blob/802f8399735813cf9951384627636bbed9850af2/operate/archiver/src/main/java/io/camunda/operate/archiver/ElasticsearchArchiverRepository.java#L352-L369) 
so the index date is deduces from the keys of the aggregation buckets, and handled out of the box
While now, it is somehow manually computed

Comment (yohanfernando) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]: > the existing logic checks if the new endDate lands within lastHistoricalArchiverDate + rolloverInteval, if not it would create a new date and a new index

Where does it do that? I cant see it in the usages of `lastHistoricalArchiverDate`?

Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]: > Where does it do that? I cant see it in the repository code?

This is the place where it computes the date that is passed to the ArchiverBatch and used for reindexing
https://github.com/camunda/camunda/blob/3fa3aef84385874ac80953c09193ba3b98eaf0dd/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/util/DateOfArchivedDocumentsUtil.java#L34-L79

Comment (yohanfernando) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]: I mean, apart from logging (in debug), it's not really doing anything useful, ya? 

It's a lot of processing, including fetching a list of indexes each time this rolls over simply to log in debug 🤷.. It might be just simpler to always log the date we are archiving in debug and skip all that logic..

**Review by yohanfernando — APPROVED** [review]
Technically, your change is okay. But I feel this last archive date and all logic around it is wasteful, and either now or sometime soon we should get rid of that..

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java (hunk 1 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]:
```
if (endDateTime.isAfter(rollover)) {
        // If the end date is after the last historical archiver date plus
        // the rollover, then a new one needs to be set.
        final var previousDate = dateOfMostRecentArchiveIndex;
        dateOfMostRecentArchiveIndex = dateOfArchiveBatch;
        LOGGER.debug(
            "Rolling over historical archive date from {} date to: {}",
            previousDate,
            dateOfMostRecentArchiveIndex);
      }
```
it is also changing the last archive date, when the new endDate is after last `archive date + rollover`

Comment (yohanfernando) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]: I 👍  the PR as this logic has nothing to do with what you are trying to achieve.. But we should create a ticket to remove that logic and simplify it IMO

Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java:404]: I created this issue https://github.com/camunda/camunda/issues/43931

**Comment by houssain-barouni** [comment]
> Technically, your change is okay. But I feel this last archive date and all logic around it is wasteful, and either now or sometime soon we should get rid of that..

Created this issue as follow-up https://github.com/camunda/camunda/issues/43931
