### PR TITLE
Merge BackupRepositoryProps based on OperateProperties & TasklistProperties

### LINKED ISSUE #25410: Merge BackupConfiguration from operate & tasklist
Operate and tasklist currently have separate backup configuration, but the backup service will be completely shared, so we cannot have two different configurations.
Considering that tasklist's backup config contains only the repository name we will do the following:
- if only one of them is provided, use that one
- if both are provided and they have the same repository one, then use operate one (which has more settings)
- if both are provided and the repository name is different, fail fast and interrupt the startup.

### PR DESCRIPTION
**Pull request by entangled90**
## Description
Create BackupRepositoryProps based on the information present in OperateProperties & TasklistProperties.
If both are present, their repositoryName configured must match otherwise we fail fast.
If only one is present, we use that configuration.
If none is present we can't start the application.

> Based on #24992 , wait for it before merging

## Related issues
closes #25410

### CODE REVIEW

File: webapps-backup/src/main/java/io/camunda/webapps/backup/repository/BackupRepositoryProps.java [hunk 1]
```diff
@@ -21,7 +21,9 @@ public interface BackupRepositoryProps {
 
   Long incompleteCheckTimeoutInSeconds();
 
-  boolean includeGlobalState();
+  default boolean includeGlobalState() {
```
Comment (entangled90) [inline webapps-backup/src/main/java/io/camunda/webapps/backup/repository/BackupRepositoryProps.java:24]: This setting was true for tasklist & false for operate, I guess this should be true by default

**Comment by entangled90** [comment]
It's probably better to merge this branch into #24465 as it should probably fix the Spring startup issues of that one

File: dist/src/main/java/io/camunda/webapps/config/BackupConfig.java [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+        throw new IllegalArgumentException(
+            "Different repository name configured for operate & tasklist backups: if both are configured, they must point to the same repository");
+      }
+      return props(operateProperties.getVersion(), operateBackup);
+    } else if (operateProperties != null) {
+      return props(operateProperties.getVersion(), operateProperties.getBackup());
+    } else if (tasklistProperties != null) {
+      return props(tasklistProperties.getVersion(), tasklistProperties.getBackup());
+    } else {
+      return BackupRepositoryProps.EMPTY;
```
Comment (entangled90) [inline dist/src/main/java/io/camunda/webapps/config/BackupConfig.java:47]: If we throw an exception here, IT will not pass. The backup controller will check if the repository name is not null or not empty before taking any backup.

File: webapps-backup/src/main/java/io/camunda/webapps/backup/repository/BackupRepositoryProps.java [hunk 3]
```diff
@@ -29,5 +42,7 @@ static Long defaultIncompleteCheckTimeoutInSeconds() {
     return 5 * 60L;
   }
 
-  boolean includeGlobalState();
+  default boolean includeGlobalState() {
```
Comment (entangled90) [inline webapps-backup/src/main/java/io/camunda/webapps/backup/repository/BackupRepositoryProps.java:45]: this flag=true was needed by tasklist

Comment (lenaschoenburg) [reply webapps-backup/src/main/java/io/camunda/webapps/backup/repository/BackupRepositoryProps.java:45]: :question: Why make this a default though? I'd prefer no default implementation and making this explicit for both Tasklist and Operate when you return the anonymous types implementing `BackupRepositoryProps`.

:question: Your changes overall mean that now both Operate and Tasklist have this as `true` whereas before it was only true for Tasklist. Is this intended?

**Review by lenaschoenburg — APPROVED** [review]

File: webapps-backup/src/main/java/io/camunda/webapps/backup/repository/BackupRepositoryProps.java (hunk 3 above)
Comment (entangled90) [reply webapps-backup/src/main/java/io/camunda/webapps/backup/repository/BackupRepositoryProps.java:45]: Because i'm not even sure if it should be configurable. Now there is no operate vs tasklist anymore, just "webapps" indices. 
By default (in ES/OS) is true, but it was set as false in operate. So in the end we could even get rid of this setting

Comment (lenaschoenburg) [reply webapps-backup/src/main/java/io/camunda/webapps/backup/repository/BackupRepositoryProps.java:45]: Okay makes sense I guess :+1:
