### PR TITLE
Combine Elasticsearch errors with exception

### LINKED ISSUE #5398: Combine ElasticsearchExporterClient error logs with exception thrown
**Description**

Right now, if the `ElasticsearchExporterClient` receives an error on flush, it will go through the response and log an error for each different error, then after thrown an exception. This causes two things:

1. Fragmentation of error logs makes it harder to diagnose
1. Error reporting tool only reports the exception, but that has no context or anything useful

We should collect the reasons and use those for context in the exception instead.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR combines the Elastic application-level errors with the exception thrown to avoid having to trawl the logs for the cause of the exception.

The exceptions now look like this:

> "Failed to flush bulk request: [Failed to flush 10 item(s) of bulk request [type: mapper_parsing_exception, reason: failed to parse], Failed to flush 2 item(s) of bulk request [type: document_missing_exception, reason: no document was present]]"

## Related issues

closes #5398 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java [hunk 1]
```diff
@@ -128,32 +128,36 @@ public void flush() {
...
+        .forEach(
+            (errorType, errors) ->
+                collectedErrors.add(
+                    String.format(
+                        "Failed to flush %d item(s) of bulk request [type: %s, reason: %s]",
+                        errors.size(), errorType, errors.get(0).getReason())));
+
+    final var exception =
+        new ElasticsearchExporterException("Failed to flush bulk request: " + collectedErrors);
+    return Optional.of(exception);
```
Comment (Zelldon) [inline exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:160]: Why we no immediately throw it here?

File: exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java [hunk 2]
```diff
@@ -128,32 +128,36 @@ public void flush() {
...
+    bulkResponse.getItems().stream()
+        .flatMap(item -> Optional.ofNullable(item.getIndex()).stream())
+        .flatMap(index -> Optional.ofNullable(index.getError()).stream())
+        .collect(Collectors.groupingBy(BulkItemError::getType))
+        .forEach(
+            (errorType, errors) ->
+                collectedErrors.add(
+                    String.format(
+                        "Failed to flush %d item(s) of bulk request [type: %s, reason: %s]",
+                        errors.size(), errorType, errors.get(0).getReason())));
```
Comment (Zelldon) [inline exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:156]: Why we only append the first error reason? Are they always the same?

File: exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientTest.java [hunk 3]
```diff
@@ -69,14 +66,7 @@ public void shouldThrowExceptionIfFailToFlushBulk() {
...
         .isInstanceOf(ElasticsearchExporterException.class)
-        .hasMessage("Failed to flush all items of the bulk");
-
-    verify(logSpy)
-        .warn(
-            "Failed to flush {} item(s) of bulk request [type: {}, reason: {}]",
-            bulkSize,
-            "mapper_parsing_exception",
-            "failed to parse");
+        .hasMessageContaining("Failed to flush bulk request:");
```
Comment (Zelldon) [inline exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientTest.java:69]: Shouldn't the exception now contain that message?

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @npepinpe 

I have some questions regarding this, please see below

File: exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 2 above)
Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:150]: :man_facepalming: 

I just kept the previous structure without thinking, but you're right, we should just throw :sweat_smile: Sorry, I wasn't thinking

File: exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientTest.java (hunk 3 above)
Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientTest.java:69]: Yeah, though I'm not a fan of asserting the exact message - it's not really part of our API, so why should a test fail if the format slightly changes? But I guess we only have one exception type, so... :man_shrugging:

File: exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 1 above)
Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java]: :man_facepalming: 

I just kept the previous structure without thinking, but you're right, we should just throw :sweat_smile: Sorry, I wasn't thinking

File: exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 2 above)
Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:150]: I assume - it was already like this, so I would assume whoever initially wrote this also double checked that. Do we think the reason may sometimes be different? Would it matter much?

File: exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientTest.java (hunk 3 above)
Comment (Zelldon) [reply exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientTest.java]: I mean it was before already asserting the log message right ? :sweat_smile:

File: exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java [hunk 4]
```diff
@@ -128,21 +128,15 @@ public void flush() {
       throw new ElasticsearchExporterException("Failed to flush bulk", e);
     }
 
-    final var failure = checkBulkResponse(bulkResponse);
-    if (failure.isPresent()) {
-      throw failure.get();
+    if (bulkResponse.hasErrors()) {
+      throw collectBulkErrors(bulkResponse);
```
Comment (Zelldon) [inline exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:132]: maybe we rename the method then to throwBulkErrors

**Review by ChrisKujawa — APPROVED** [review]

File: exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 4 above)
Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:132]: But it doesn't throw it? Or do you mean it should throw it? I thought about it but I felt this was more explicit - when reading the flush method, you can see it will throw an exception and stop on error, whereas the other you'd have to look into it.

I have no strong feelings though to be honest, both seem fine and indicate intent - as long as it's not something like `checkError` or something where it's not clear if it throws or not :sweat_smile:

Comment (Zelldon) [reply exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:132]: Hm I see. Maybe then createExceptionWith or newElasticException

CollectBulkErrors sounds not really like it would create an return an exception object, tbh :sweat_smile:

**Comment by npepinpe** [comment]
bors merge
