### PR TITLE
fix: unified config: Camunda exporter args are not set when created for the first time

### LINKED ISSUE #38731: Bug: exporter args are not being set when created from the first time
### 

### 

### 

### 

### Description

**Description:**

In BrokerBasedPropertiesOverride#populateCamundaExporter a new LinkedHashMap for exporter args is created when the ExporterCfg doesn’t have any arguments yet:
```
    // https://github.com/camunda/camunda/issues/37880
    // it is possible to have an exporter with no args defined
    final Map<String, Object> args =
        exporter.getArgs() == null ? new LinkedHashMap<>() : exporter.getArgs();
```
It seems that was introduced to prevent NullPointerExceptions, but while this new map is then populated with all the args from the unified config, it is never set on the ExporterCfg and properties from UnifiedConfiguration will basically have no effect

**Slack conversation:**
https://camunda.slack.com/archives/C08E56YUUMS/p1758798429894999

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Current behavior

The arguments have no effect

### Expected behavior

The configuration should be applied to the camunda exporter

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by buccarel**
## Description

Issue: https://github.com/camunda/camunda/issues/38731

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes https://github.com/camunda/camunda/issues/38731

### CODE REVIEW

**Review by stefanzilske — APPROVED** [review]
This looks good to me 👍

Just one thought:

💭 Instead of removing the `ExporterTestWithoutArgs` test case, we could keep it and let it assert that args are set on the ExporterCfg when there are no legacy-args.

File: configuration/src/test/java/io/camunda/configuration/SecondaryStorageElasticsearchTest.java [hunk 1]
```diff
@@ -284,41 +284,6 @@ void testCamundaSearchEngineIndexProperties() {
...
-    }
-
-    // https://github.com/camunda/camunda/issues/37880
-    // it is possible to have an exporter with no args defined
-    @Test
-    void testSecondaryStorageExporterCanWorkWithoutArgs() {
-      final ExporterCfg camundaExporter = brokerBasedProperties.getCamundaExporter();
-      assertThat(camundaExporter).isNotNull();
-      final Map<String, Object> args = camundaExporter.getArgs();
-      assertThat(args).isNull();
```
Comment (deepthidevaki) [inline configuration/src/test/java/io/camunda/configuration/SecondaryStorageElasticsearchTest.java:318]: Instead of removing this test, assert that the url of the exporter is set from the unified config.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]

**Review by deepthidevaki — APPROVED** [review]
Thanks
