### PR TITLE
Escalate errors in output mapping evaluation

### LINKED ISSUE #9543: Output mapping doesn't create an incident if a variable is missing
**Describe the bug**

I deployed a BPMN process with a task. The task has an output mapping that adds (or updates) a property of a variable `a.b`.

image

Now, the job of the task is completed (accidentally) without the variable `x` that is referenced as the variable assignment value.

If the process instance doesn't have the variable `a` then an incident is created, as expected. The incident has the following error message:

```
failed to evaluate expression '{a:if (a = null) then {b: x} else put all(a,{b: x})}': no variable found for name 'x'
```

But if the process instance has the variable `a` then no incident is created. Instead, the variable `a` is set to `null` and the task is completed. 

image

**To Reproduce**

1. Deploy the BPMN process: [output_mapping.bpmn.txt](https://github.com/camunda/zeebe/files/8909195/output_mapping.bpmn.txt) (without the `.txt` ending)
2. Create a new process instance with the variables `{ "a": { "c": 1 } }`
3. Complete the task with job type `task-a` without variables
4. Verify that no incident is created and the task is completed

**Expected behavior**

An incident is created if a job is completed without a variable that is referenced as the variable assignment value of an output mapping.

The behavior should be consistent. For the case that the variable is present and the case that the variable is not present. 

**Log/Stacktrace**

None.

**Environment:**
- OS: 
- Zeebe Version: `8.0.2`
- Configuration:

### PR DESCRIPTION
**Pull request by pihme**
## Description

Changes the expression which merges the result of the output mapping to be consistent

## Review Hints
There are two versions of the expression. The last one is easier to comprehend, in my mind. If you like the first one better, we can just drop the last commit.

## Related issues

closes #9543

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/processing/variable/mapping/VariableOutputMappingTransformerTest.java [hunk 1]
```diff
@@ -161,6 +162,28 @@ public void shouldApplyMappings() {
     MsgPackUtil.assertEquality(result.toBuffer(), expectedOutput);
   }
 
+  @ParameterizedTest(name = "{index}: mapping {0} fails with: {2}")
+  @MethodSource("parametersEvaluationToFailure")
+  public void shouldEvaluateToFailure(
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/variable/mapping/VariableOutputMappingTransformerTest.java:167]: I like the refactoring of the test class :+1:

**Review by saig0 — APPROVED** [review]
@pihme great job :tada: I really like your idea to fix the behavior :+1: 

I prefer the second option. I have only one minor suggestion for it. Please have a look at my comment.
