### PR TITLE
fix: use extra underscore to differentiate Zeebe exporter indexes from Camunda exporter indexes

### LINKED ISSUE #45705: Harden index prefix configuration to prevent ILM from deleting unified indices (Zeebe records vs secondary storage)
### 

### 

### 

### 

### Description

This issue is about adding protection against a **dangerous misconfiguration** that can lead to **data loss**

Today, it is possible to configure:

- **Zeebe records indices** (legacy exporter, zeebe-recrods), and  
- **Unified Camunda indices** (secondary storage: Operate/Tasklist/Identity/etc.)

to share the **same index prefix** on the same Elasticsearch/OpenSearch cluster.

Because the legacy Zeebe exporter applies ILM to all indices matching: `{zeebe-exporter-index-prefix} + "*"`

Any unified indices that reuse the same prefix are also subject to the same ILM policy. This can result in **unexpected deletion of unified indices** some time after a migration to 8.8, even though the configuration “looks” fine and the migration initially appears successful.

This misconfiguration is easy for customers to make and can cause silent data loss days later when ILM triggers.

Reference discussion (internal):  

### Steps to reproduce

1. Configure the application with legacy Elasticsearch exporter using the same prefix as the unified indices
```
ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_PREFIX=zeebe-record
CAMUNDA_DATA_SECONDARYSTORAGE_ELASTICSEARCH_INDEXPREFIX=zeebe-record
```
2. set the retention period of legacy zeebe indices to a low value
```
ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_RETENTION_MINIMUMAGE=1s
```

### Current behavior

zeebe records ILM policy is applied by legacy ES exporter to the unified indices
the unified indices get removed after few minutes

### Expected behavior

ILM policy should not be applied by legacy ES exporter to the unified indices

### Workaround

the only workaround is to deactivate ES exporter and remove the ILM policy from the unified indices
OR disable the retention for ES exporter

### Environment

SM

### Version

- Component Version: 8.8

### Rootcause

The legacy Elasticsearch exporter (Zeebe records exporter) [applies the ILM policy using the pattern](https://github.com/camunda/camunda/blob/331d33b046b3f68f6e1f41987fc9bf770e4191e1/zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java#L273) `"index-prefix + *"` so it when the index prefixes are the same, it applies to all indices

### Solution ideas

1. **Configuration validation**

   - During startup, validate that:
     - Zeebe records prefix (legacy exporter) and
     - Secondary storage index prefix
     are **not identical** and do not “include” each other. In other words:
     - The prefix groups must not share the same value, and
     - `{prefix}*` for one group must not match indices that belong to the other group.
   - If such a conflict is detected:
     - Either fail fast with a clear error, or
     - Log a prominent error and refuse to start the component until it is fixed.

2. **Safer ILM application for legacy exporter**
   - Investigate whether the legacy exporter can narrow ILM application to **only** its own indices, even when prefixes coincide, for example by:
     - Using more specific patterns that cannot match unified indices, or
     - Tagging its indices and targeting ILM via filters rather than a plain `{prefix}*` wildcard (if feasible).
   - This may be constrained by the fact that the ILM policy might already have been created in previous versions, so we might need:
     - A migration / cleanup path for existing ILM policies, or
     - At least a detection + warning mechanism when such a policy exists and conflicts with current secondary-storage configuration.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

[Slack (internal)](https://camunda.slack.com/archives/C08NQKV761G/p1770900903792699)
https://jira.camunda.com/browse/SUPPORT-30954

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by lilspikey**
This fixes an issue where the `OpensearchExporter` and `ElasticsearchExporter` were a bit too broad in how they applied their ILM/ISM policies.  This meant that if a client had configured those exporters and the `CamundaExporter` with the same prefix then indexes for the `CamundaExporter` would have those extra policies applied - which would then result in those indexes being deleted after the retention period expires.

This simply narrows the pattern used for those policies to include an extra underscore (`_`), which avoids this issue.

We might still want a more bullet proof fix in the future, but this should at least handle the common case of re-using the same prefixes.

Refs #45705

### CODE REVIEW

**Comment by lilspikey** [comment]
Running this locally I can see the policy now only applies to the relevant ES indices:

```
$ curl -sSf localhost:9200/_ilm/policy/zeebe-record-retention-policy | jq '.["zeebe-record-retention-policy"].in_use_by'
{
  "indices": [
    "zeebe-record_process-instance_8.8.12_2026-02-16",
    "zeebe-record_deployment_8.8.12_2026-02-16",
    "zeebe-record_tenant_8.8.12_2026-02-16",
    "zeebe-record_process_8.8.12_2026-02-16"
  ],
  "data_streams": [],
  "composable_templates": [
    "zeebe-record_process_8.8.12",
    "zeebe-record_message_8.8.12",
    "zeebe-record_signal-subscription_8.8.12",
    "zeebe-record_variable_8.8.12",
    "zeebe-record_job_8.8.12",
    "zeebe-record_deployment_8.8.12",
    "zeebe-record_signal_8.8.12",
    "zeebe-record_process-instance-migration_8.8.12",
    "zeebe-record_ad-hoc-sub-process-instruction_8.8.12",
    "zeebe-record_escalation_8.8.12",
    "zeebe-record_tenant_8.8.12",
    "zeebe-record_command-distribution_8.8.12",
    "zeebe-record_error_8.8.12",
    "zeebe-record_process-instance-modification_8.8.12",
    "zeebe-record_user-task_8.8.12",
    "zeebe-record_deployment-distribution_8.8.12",
    "zeebe-record_runtime-instruction_8.8.12",
    "zeebe-record_process-instance_8.8.12",
    "zeebe-record_compensation-subscription_8.8.12",
    "zeebe-record_message-subscription_8.8.12",
    "zeebe-record_decision-evaluation_8.8.12",
    "zeebe-record_form_8.8.12",
    "zeebe-record_process-instance-creation_8.8.12",
    "zeebe-record_incident_8.8.12",
    "zeebe-record_decision_8.8.12",
    "zeebe-record_process-message-subscription_8.8.12",
    "zeebe-record_decision-requirements_8.8.12",
    "zeebe-record_message-correlation_8.8.12",
    "zeebe-record_message-start-event-subscription_8.8.12",
    "zeebe-record_timer_8.8.12",
    "zeebe-record_resource-deletion_8.8.12",
    "zeebe-record_variable-document_8.8.12"
  ]
}
```

**Comment by lilspikey** [comment]
and similarly for opensearch:
```
$ curl -sSf 'localhost:9200/_plugins/_ism/explain/zeebe-record*' | jq -c '. | to_entries | .[].value' | grep zeebe-record-retention-policy | jq .index
"zeebe-record_process-instance_8.8.12_2026-02-16"
"zeebe-record_process_8.8.12_2026-02-16"
"zeebe-record_deployment_8.8.12_2026-02-16"
"zeebe-record_tenant_8.8.12_2026-02-16"
```

**Comment by lilspikey** [comment]
ok and I've double checked that the retention stuff still actually works after these changes (i.e. that the zeebe exporter indexes still get removed after a while).  Took a little while as ES/OS are not particularly quick at actually removing them...

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java [hunk 1]
```diff
@@ -16,7 +16,7 @@
 
 /** Computes the name of the index, alias, or search pattern for a record or its value type. */
 final class RecordIndexRouter {
-  private static final String INDEX_DELIMITER = "_";
+  public static final String INDEX_DELIMITER = "_";
```
Comment (houssain-barouni) [inline zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/RecordIndexRouter.java]: just a nitpick, but this could have a package visibility instead of public

File: zeebe/exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/OpensearchClient.java [hunk 2]
```diff
@@ -291,9 +291,16 @@ private boolean putIndexStateManagementPolicy(final Map<String, String> queryPar
   }
 
   public boolean bulkAddISMPolicyToAllZeebeIndices() {
+    System.out.println(configuration.retention.getPolicyName());
+    System.out.println(configuration.index.prefix);
```
Comment (houssain-barouni) [inline zeebe/exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/OpensearchClient.java]: 🔧 to be removed

File: zeebe/exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/RecordIndexRouter.java [hunk 3]
```diff
@@ -16,9 +16,9 @@
 
 /** Computes the name of the index, alias, or search pattern for a record or its value type. */
 final class RecordIndexRouter {
+  public static final String INDEX_DELIMITER = "_";
```
Comment (houssain-barouni) [inline zeebe/exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/RecordIndexRouter.java]: same here

**Review by houssain-barouni — APPROVED** [review]
LGTM!

File: zeebe/exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/OpensearchClient.java [hunk 4]
```diff
@@ -306,7 +311,12 @@ public boolean bulkAddISMPolicyToAllZeebeIndices() {
   public boolean bulkRemoveISMPolicyToAllZeebeIndices() {
```
Comment (RomanJRW) [inline zeebe/exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/OpensearchClient.java]:
```suggestion
  public boolean bulkRemoveISMPolicyFromAllZeebeIndices() {
```
Not new, but just nitpicking on name ;)

**Comment by houssain-barouni** [comment]
> ok and I've double checked that the retention stuff still actually works after these changes (i.e. that the zeebe exporter indexes still get removed after a while). Took a little while as ES/OS are not particularly quick at actually removing them...

by default it takes up to 10 minutes

File: zeebe/exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/OpensearchClient.java (hunk 2 above)
Comment (lilspikey) [reply zeebe/exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/OpensearchClient.java]: yeah 😄

**Comment by lilspikey** [comment]
yeah was rushing to get it checked on Friday and couldn't work out why it was taking quite so long.  Seems like OS in particular really wanted to take it's time (and I think it didn't like me setting the retention to `1s` either).

File: zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchClientIT.java [hunk 5]
```diff
@@ -120,24 +125,131 @@ void shouldPutComponentTemplate() {
...
 
     // then
-    assertThat(searchDB.testClient().getComponentTemplate()).isPresent();
+    assertThat(SEARCH_DB.testClient().getComponentTemplate()).isPresent();
+  }
+
+  @Test
+  void shouldCreateIndexStateManagementPolicyWithoutTouchingCamundaExporterIndexes() {
+    // given
+
```
Comment (RomanJRW) [inline zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchClientIT.java:151]: 🔧 not strictly needed, but also not a big deal

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientIT.java [hunk 6]
```diff
@@ -198,6 +203,32 @@ void shouldPutIndexLifecycleManagementPolicy() throws IOException {
     assertThat(lifecycle.policy().phases().delete().actions().delete()).isNotNull();
   }
 
+  @Test
+  void shouldBulkPutIndexLifecycleSettingsWithoutAlteringCamundaExporterIndexes()
```
Comment (RomanJRW) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientIT.java]:
```suggestion
  void shouldBulkPutIndexLifecycleSettingsWithoutAlteringCamundaExporterIndexesWithSamePrefix()
```
I don't think it's clear from the test that we are sharing index prefix between both index sets

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientIT.java [hunk 7]
```diff
@@ -198,6 +203,32 @@ void shouldPutIndexLifecycleManagementPolicy() throws IOException {
...
+      throws IOException {
+    // given
+    final var esClient = testClient.getEsClient();
+    final var ownedIndexName =
+        indexRouter.indexPrefixForValueType(ValueType.VARIABLE, VersionUtil.getVersionLowerCase())
+            + "_2024-01-01";
+    // camunda exporter indexes have a slightly different format
+    final var camundaExporterIndexName = config.index.prefix + "-camunda-exporter-2024-01-01";
```
Comment (RomanJRW) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientIT.java]: ❓ wdyt about including one of each of the possible prefixes for Camunda Exporter that we know about right now. So that would be three vars essentially:

```
final var camundaExporterCamundaIndexName = config.index.prefix + "-camunda-authorization-2024-01-01";
final var camundaExporterOperateIndexName = config.index.prefix + "-operate-variable-2024-01-01";
final var camundaExporterTasklistIndexName = config.index.prefix + "-tasklist-task-2024-01-01";
```

And then expanding the assertion to include them all. Note I used real index names here as well rather than the `camunda-exporter` more generically named index

File: zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchClientIT.java [hunk 8]
```diff
@@ -120,24 +125,131 @@ void shouldPutComponentTemplate() {
...
+      throws IOException {
+    // given
+    final var config = SEARCH_DB.config();
+    final var indexRouter = SEARCH_DB.indexRouter();
+    final var ownedIndexName =
+        indexRouter.indexPrefixForValueType(ValueType.VARIABLE, VersionUtil.getVersionLowerCase())
+            + "_2024-01-01";
+
+    // camunda exporter indexes have a slightly different format
+    final var camundaExporterIndexName = config.index.prefix + "-camunda-exporter-2024-01-01";
```
Comment (RomanJRW) [inline zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchClientIT.java]: same comment as for the ES test

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java [hunk 9]
```diff
@@ -268,9 +268,15 @@ public boolean putIndexLifecycleManagementPolicy() {
 
   public boolean bulkPutIndexLifecycleSettings(final String policyName) {
     try {
+      // camunda exporter indexes have a slightly different format (dash instead of underscore after
+      // prefix) so using that to avoid accidentally updating them
```
Comment (RomanJRW) [inline zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:272]: ❓ I didn't check, but do we need the handling the other way around too? i.e. do we need to make sure that the Camunda exporter doesn't update the ILM/ISM policy of the ES/OS exporter indices?

**Review by RomanJRW — COMMENTED** [review]
Generally LGTM, just a question about scope and whether we need the same check in the Camunda exporter. Would be happy to review again after this is clarified 👍

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 9 above)
Comment (lilspikey) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:272]: I _think_ from looking at the code it's usually applied on a per-index prefix basis.  I'll do a sanity check though.

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientIT.java (hunk 7 above)
Comment (lilspikey) [reply zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientIT.java]: Probably having three is overkill, but I could change the name to match one of the real ones.

Comment (RomanJRW) [reply zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchClientIT.java]: works for me 👍

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java (hunk 9 above)
Comment (RomanJRW) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:272]: If this is covered already, then fine to proceed from my perspective. Will preemptively give you an approval 👍

**Review by RomanJRW — APPROVED** [review]

**Comment by lilspikey** [comment]
ok done sanity check and `camunda-retention-policy` is not getting applied to the zeebe indexes
