### PR TITLE
Ensure requests are always completed

### LINKED ISSUE #7360: Race condition in messaging service causes "infinitely" waiting requests
**Describe the bug**

It came to our attention via #6856 that some times, requests in the transport layer are sometimes never "completed" - neither successfully or exceptionally. This breaks the contract of the messaging service, as we expect all requests to eventually succeed or fail, at the very least via time out. But it seems like there is a problem with the way we handle time outs - they are only scheduled after the protocol handshake. As we saw, it can happen that the channel is closed successfully (this part is still not clear as to why this happened in the first place) _before_ the handshake is completed, and before we even list for the channel's close event. In fact, we only list for the close event after the handshake - so if it happens mid-way, it will never terminate, the future is never completed, there is no time out, and we aren't notified that the connection was closed. The consumer of the messaging service is then effectively waiting "forever". This causes bugs in the SWIM protocol, and may possibly explain https://github.com/camunda-cloud/zeebe/issues/7339.

**To Reproduce**

This one was fun to reproduce :smile: I was running, in a loop, the `AdvertisedAddressTest` (pre-fix). You have to ensure that in a cluster of 3 nodes - 1, 2, 3 - nodes 1 and 2 only know about each other, and node 3 is the black sheep trying to connect to them via probing. Sometimes, the probe will fail due to the above, at which point you can then debug the instance remotely.

Not the best way to reproduce, and very time consuming, but as it's a race condition I'm not sure how to trigger it other than try to stress it.

**Expected behavior**

The future returned by messaging service is eventually completed, _always_. The other option is to move to a pure message passing approach, and avoid request-response. Then the consumer is in charge of retrying, which is possibly simpler to understand, but you have to deal with out of order responses.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR attempts to ensure requests sent via the messaging service's `sendAndReceive` method(s) are _always_ completed, whether successfully or at the very least via a timeout. This highlights one of the weakness of the send/receive approach - while it simplifies ordering, it does make it harder to have a proper retry logic. At any rate, I say attempt, as it's hard to prove something truly halts :wink: 

The approach was to remove the callback construct and the time out executor, and simply leverage the `CompletableFuture#orTimeout` callback. This is done on the future being returned to the consumer of the `sendAndReceive` contract, so we are nearly guaranteed that it will at the very least timeout, regardless of whatever happens in the chain of callback handlers.

I've also added that we immediately listen to the channel's `closeFuture` and complete the response future when the channel is closed. This should be fine, as we normally expect to close the channel only after we've handled the request (and as such have completed the response future) - this is meant as a fail safe in case the channel is closed unexpectedly (e.g. mid handshake) and nobody is listening for such event, resulting in the future being left incomplete.

I also simplified the messaging service a bit - I removed the callback construct as mentioned, and also the dynamic time outs which were based on sampling. I don't think this helped us much to be honest, as from checking the usage, our explicit usage of the service is always with an explicit time out, or we use `sendAsync` where the time outs don't matter (as we don't wait for a reply).

I also added some minor test improvements to reduce the time the messaging service took. I think it might be easier to review commit by commit, or at least look at the commit messages.

## Related issues

closes #7360 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
It might still be interesting to run a benchmark for this just to be safe.

**Comment by npepinpe** [comment]
For some reason the prepare stage is broken in this PR, but I didn't change anything in the build pipeline... :thinking: 

At any rate, it's blocking the IT stage from running, so maybe wait for that before you review it :sweat_smile:

**Comment by npepinpe** [comment]
:man_shrugging: Now it passed - maybe it was a temporary thing, seemed to fail to resolve dependencies.

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 1]
```diff
@@ -565,14 +566,36 @@ private RemoteClientConnection getOrCreateClientConnection(final Channel channel
...
+            onClose -> {
+              if (onClose.isSuccess()) {
+                future.completeExceptionally(
+                    new ConnectException(
+                        String.format(
+                            "Channel %s for address %s was closed before the request could be completed",
+                            channel, address)));
+              } else {
+                future.completeExceptionally(onClose.cause());
               }
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:609]: Sorry I'm not so into this API. This addition is not so obvious to me sorry :see_no_evil: 

I assume the listener for close will be called also when our request went trough? How can we detect that the request wasn't sent? What does `onClose.isSuccess` even mean? Why we have no message on the else branch? Shouldn't we check whether our future is not yet completed? Or is it fine the thrown an exception in this listener?

File: gateway/src/test/java/io/camunda/zeebe/gateway/grpc/GrpcErrorMapperTest.java [hunk 2]
```diff
@@ -30,11 +30,8 @@
 import org.junit.jupiter.api.AfterEach;
 import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
-import org.junit.jupiter.api.parallel.Execution;
-import org.junit.jupiter.api.parallel.ExecutionMode;
 import org.slf4j.helpers.NOPLogger;
 
-@Execution(ExecutionMode.CONCURRENT)
```
Comment (Zelldon) [inline gateway/src/test/java/io/camunda/zeebe/gateway/grpc/GrpcErrorMapperTest.java:37]: Sorry but is this related to the other changes? If not I would suggest that we next time create another PR for it, even if this change is so small.

File: atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java [hunk 3]
```diff
@@ -127,21 +130,17 @@ private String nextSubject() {
...
+        .parallel()
+        .filter(Objects::nonNull)
+        .forEach(
+            service -> {
+              try {
+                service.stop().join();
+              } catch (final Exception e) {
+                LOGGER.warn("Failed stopping NettyMessagingService {}", service, e);
+              }
+            });
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/cluster/messaging/impl/NettyMessagingServiceTest.java:143]: :rocket:

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/ClusterCommunicationService.java [hunk 4]
```diff
@@ -133,55 +133,44 @@
       boolean reliable);
 
   /**
-   * Sends a message and expects a reply.
+   * Multicasts a message to a set of members over TCP.
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/cluster/messaging/ClusterCommunicationService.java:136]: This is not true right? It sends directly to the member with the id?

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @npepinpe :rocket: this was long overdue! 

I really like the changes and simplifications. The git commit messages helped me to understand the changes better thanks for that. I just have some suggestion, comments and questions I want clarify before we can merge that. Furthermore I would like to see a benchmark, whether this makes any issues which we don't cover with our tests.

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 5]
```diff
@@ -191,13 +189,17 @@ public Address address() {
...
+          executeOnPooledConnection(
+              address, type, c -> c.sendAndReceive(message, timeout), executor);
     } else {
-      return executeOnTransientConnection(
-          address, c -> c.sendAndReceive(message, timeout), executor);
+      responseFuture =
+          executeOnTransientConnection(address, c -> c.sendAndReceive(message, timeout), executor);
     }
+
+    return responseFuture.orTimeout(timeout.toNanos(), TimeUnit.NANOSECONDS);
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:208]: Yeah, you lose some context I guess. It's much simpler/robust however from my pov than what we used to have :sweat_smile: I suppose I could put it back with a scheduled executor for the time outs, and we simply schedule it before returning the future - then you have more control over it. It still seemed more error-proof to tie it to the future since that's what you end up waiting on. You could still keep the context if the caller/consumer of the future handled the exception properly (since the caller should know what request it sent :sweat_smile:). I think that's a more general discussion to have. We tend to centralize error/logging in these kind of methods, and the callers just let them bubble up instead of handling them and enriching them with the right context, which sometimes leads to missing context or logging things multiple times (so more noise). But yeah, out of scope here I guess :sweat_smile: 

I can try with the scheduled executor, it's not that much more complicated tbh.

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 6]
```diff
@@ -268,10 +270,7 @@ public void unregisterHandler(final String type) {
     return bootstrapServer()
         .thenRun(
             () -> {
-              timeoutExecutor =
-                  Executors.newScheduledThreadPool(
-                      4, namedThreads("netty-messaging-timeout-%d", log));
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:273]: Yeah, go figure :sweat_smile: I would expect we can just use 1, and do the same thing we did with our timers in the engine - schedule the next to expire, then expire any that have also expired in the mean time, and schedule the next one after. :man_shrugging:

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/AbstractClientConnection.java [hunk 7]
```diff
@@ -54,40 +57,33 @@ public void dispatch(final ProtocolReply message) {
   @Override
   public void close() {
     if (closed.compareAndSet(false, true)) {
-      for (final Callback callback : callbacks.values()) {
-        callback.completeExceptionally(new ConnectException());
+      for (final CompletableFuture<byte[]> responseFuture : responseFutures.values()) {
+        // TODO(npepinpe): would be interesting to know the cause of the connection closing, but
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/AbstractClientConnection.java:61]: I guess not, I was hoping I would figure it out but I don't really have a good idea on how to propagate it. I would like to know why the connection is closing obviously, but for now I suppose we need to assume it's closing gracefully :sweat_smile:

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/AbstractClientConnection.java [hunk 8]
```diff
@@ -54,40 +57,33 @@ public void dispatch(final ProtocolReply message) {
...
+        responseFutures.computeIfAbsent(id, ignored -> new CompletableFuture<>());
 
-    Callback(final long id, final CompletableFuture<byte[]> future) {
-      this.id = id;
-      replyFuture = future;
-      callbacks.put(id, this);
-    }
+    // return this stage directly will cause downstream stages to receive a CompletionException
+    // instead of the error itself; so when not composing things, it's better to tack on your
+    // handler but return the original future itself
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/AbstractClientConnection.java:84]: Yes. So, if you have the following:

```java
future.orTimeout(5, TimeUnit.SECONDS).whenComplete((ignored, error) -> LOGGER.info("Something", error)).whenComplete((ignored, error) -> LOGGER.error("Oh no!", error)).join();
```

Then the first whenComplete will log a `TimeoutException`, and the second whenComplete will log a `CompletionException` (with the cause being `TimeoutException`). However, if you just do:

```java
final var result = future.orTimeout(5, TimeUnit.SECONDS);
result.whenComplete((ignored, error) -> LOGGER.info("Something", error));
result.whenComplete((ignored, error) -> LOGGER.error("Oh no!", error))
result.join();
```

Then both will log a `TimeoutException`.

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 9]
```diff
@@ -565,14 +566,36 @@ private RemoteClientConnection getOrCreateClientConnection(final Channel channel
     bootstrap.channel(clientChannelClass);
     bootstrap.remoteAddress(resolvedAddress, address.port());
     bootstrap.handler(new BasicClientChannelInitializer(future));
-    bootstrap
-        .connect()
+    final Channel channel =
+        bootstrap
+            .connect()
+            .addListener(
+                f -> {
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:586]: A future, the result of the connect operation. I can rename it result - tbh here was just laziness cause it was already existing and called `f` :sweat_smile:

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java (hunk 1 above)
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:609]: The future is called when it's completed AFAIK. We don't need to detect that the request was or wasn't sent - it's a bit tricky because it relies on the order of callbacks and when they're called. There is one edge case I suppose where the channel may get closed while we're waiting for the response. I can reword the message so it's more about the channel was closed before the request was processed correctly. Or is that still not clear?

So normally the channel is closed at the end, right, when we're done with it. At that point though, we've handled the request, and we've already either completed the future successfully or with an exception. So in the common case, where we close the channel at the end when we're done, nothing really happens here since the future is already completed.

There was an edge case that we noticed in the AdvertisedAddressTest where the channel was closed mid-way through the handshake - it was closed successfully mind, and I never figured out why or who was closing it. At any rate, from a `sendAndReceive` perspective (i.e. contract), this is a failure. We didn't send nor receive the request, so we shouldn't mark it as successfully completed. If the channel is closed _before_ anything else completes the future, imo, it's a breach of contract and clearly it's a failure. If the channel was closed with an error, then we can report that error. If it wasn't, the best we can do is that something closed it before we could fully handle it (but unfortunately it's difficult to know what).

I hope that clears things up. To be honest, this whole API is a overly complex I think. I don't think Netty is per se, but how the transport here is implemented makes things much more complex than they need to be. I can't wait to switch to gRPC.

File: gateway/src/test/java/io/camunda/zeebe/gateway/grpc/GrpcErrorMapperTest.java (hunk 2 above)
Comment (npepinpe) [reply gateway/src/test/java/io/camunda/zeebe/gateway/grpc/GrpcErrorMapperTest.java:37]: Oh, it is in another PR, I'm not sure why it's there :thinking: In fact we already merged that PR...

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/ClusterCommunicationService.java (hunk 4 above)
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/ClusterCommunicationService.java:136]: Oops, the dangers of copy pasting :see_no_evil:

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java [hunk 10]
```diff
@@ -197,14 +206,22 @@ public Address address() {
...
-          executeOnTransientConnection(address, c -> c.sendAndReceive(message, timeout), executor);
+          executeOnTransientConnection(address, c -> c.sendAndReceive(message), executor);
     }
 
-    return responseFuture.orTimeout(timeout.toNanos(), TimeUnit.NANOSECONDS);
+    final var timeoutFuture =
+        timeoutExecutor.schedule(
+            () ->
+                responseFuture.completeExceptionally(
+                    new TimeoutException("Request " + message + " timed out in " + timeout)),
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java:219]: Could we add here the target address?

**Review by ChrisKujawa — APPROVED** [review]
Thanks @npepinpe good stuff.

**Comment by npepinpe** [comment]
Started a [benchmark](http://34.77.165.228/goto/xHgIPvznk)

**Comment by Zelldon** [comment]
Looks good :+1:

**Comment by npepinpe** [comment]
bors merge
