### PR TITLE
fix: SnapshotCopy opens the source db in read only mode

### LINKED ISSUE #34430: Creating the snapshot for bootstrap may change persisted files and violate checksums
Opening the snapshot without a readOnly RocksDB instance may write to the log to disk, invalidating the checksums.
This results in a corrupted snapshot when trying to backup and restore.

When creating a snapshot for bootstrap, we need to open a readOnlyDB with
`RocksDB.openReadOnly`

### PR DESCRIPTION
**Pull request by entangled90**
## Description
The db opened at the source snapshot location is a `SnapshotOnlyDb`, which opens RocksDB in readOnly mode.
This should avoid having rocksDB changing the files on disk while performing get operations.

The `forEach` method from `RawTransactionalColumnFamily` has been defined as static as well, in order to be used from `SnapshotOnlyDb` as well, as it does not have an open transaction. 

A new `forEachPreallocated` method preallocates `byte [] key, byte[] value` in order to avoid allocating altogether when iterating. 
To avoid introducing new bugs, a new method has been created, so that the caller knows that the `byte[]` received cannot be used outside the invoked callback.

## Integration tests:
- this fix is tested by PR #34495 (stacked on this branch)
## Related issues

closes #34430

### CODE REVIEW

**Comment by entangled90** [comment]
~~I think we might need to be able to use `ZeebeDb.createColumnFamily` from a snapshot only DB even for restoring the `RoutingState` from a backup.
So it would actually make sense move the `forEach` in `SnapshotOnlyDb` to a read-only column family~~

File: zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/transaction/RawTransactionalColumnFamily.java [hunk 1]
```diff
@@ -140,6 +139,50 @@ private void forEach(
     }
   }
 
+  public static void forEachPreallocated(
```
Comment (deepthidevaki) [inline zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/transaction/RawTransactionalColumnFamily.java:157]: :wrench: Would be nice to document the semantics of these two variants of "forEach". It is not easy to understand the difference from the method name.

File: zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java [hunk 2]
```diff
@@ -135,7 +135,7 @@ public void copySnapshot(
                   new DbNullKey(),
                   (prefixKey, prefixLength) -> {
                     try (final RocksIterator iterator = db.newIterator(readOptions)) {
-                      RawTransactionalColumnFamily.forEach(
+                      RawTransactionalColumnFamily.forEachPreallocated(
```
Comment (deepthidevaki) [inline zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java:138]: :question: Did you make this change based on a performance test / profiling? If so, can you share the results?

File: zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java [hunk 3]
```diff
@@ -103,4 +112,55 @@ private UnsupportedOperationException unsupported(final String operation) {
         "Failed to execute 'ZeebeDb#%s'; this operation is not supported on a snapshot-only DB"
             .formatted(operation));
   }
+
+  public void copySnapshot(
+      final ZeebeTransactionDb<ZbColumnFamilies> toDB, final Set<ColumnFamilyScope> scopes) {
+    try (final var readOptions = PrefixReadOptions.readOptions()) {
+      final var toCtx = toDB.createContext();
+      final var abort = new AtomicBoolean(false);
```
Comment (deepthidevaki) [inline zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java]: :question: Why is it `AtomicBoolean`? Is there concurrent access to this object? Can use agrona's `MutableBoolean` instead.

File: zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java [hunk 4]
```diff
@@ -103,4 +112,55 @@ private UnsupportedOperationException unsupported(final String operation) {
...
+                            try {
+                              toCf.rawPut(
+                                  toTx, key, keyOffset, keyLen, value, valueOffset, valueLen);
+                            } catch (final Exception e) {
+                              LOG.error(
+                                  "Failed to copy column family '{}' on key {} and value with length {} terminating.",
+                                  cf,
+                                  new String(key),
+                                  value.length);
+                              LOG.error("Exception", e);
```
Comment (deepthidevaki) [inline zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java]:
```suggestion
                              LOG.error(
                                  "Failed to copy column family '{}' on key {} and value with length {} terminating.",
                                  cf,
                                  new String(key),
                                  value.length, e);
```

**Review by deepthidevaki — APPROVED** [review]
:rocket:  An easily overlooked bug :see_no_evil: 

Pre-approving. But please address my comments before merging. 
Also did not check the first two commits related to ClusterConfiguration. I beleive they are reviewed and being merged in a parallel PR.

File: zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java (hunk 2 above)
Comment (entangled90) [reply zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java:138]: I did a quick profiling of the tests:
- I didn't spot any big difference in the time it takes to complete the test, but it's also contains a bit of noise, so I'd say they take around the same
- The preallocated version basically does not allocate when iterating over the column families, while the other allocated a few hundreds of MB.

File: zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java (hunk 3 above)
Comment (entangled90) [reply zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java]: Good point, I think I added because of the lambda, but forgot to fix it later on :+1:

**Comment by entangled90** [comment]
I'll rebase the PR now that the other PR got merged (I did some changes there before merging it).

Unfortunately I realized this when doing Integration tests :laughing:

File: zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java (hunk 4 above)
Comment (entangled90) [reply zeebe/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/SnapshotOnlyDb.java]: just realized I also needed to add `new String(key, 0, keyLen)`
