### PR TITLE
Track process definition key in process message subscriptions

### LINKED ISSUE #40325: Message Subscription API regression: processDefinitionKey is missing
### 

### 

### 

### 

### Description

In 8.8.0-alpha8, the Message Subscription API response contained a `processDefinitionKey`. (See MessageSubscriptionEntity).

```json
  "items": [
        {
            "messageSubscriptionKey": "2251799813685310",
            "processDefinitionId": "Process_2",
            "processDefinitionKey": "2251799813685298",
            "processInstanceKey": "2251799813685300",
            ...
        },
```

In version 8.8, this field is no longer present. 

### Steps to reproduce

1. Checkout 8.8.0-alpha8
2. Deploy and start a process (rename this file from .xml to .bpmn) [diagram.xml](https://github.com/user-attachments/files/23265694/diagram.xml)
3. Call `http://localhost:8080/v2/message-subscriptions/search`
4. The result contains the `processDefinitionKey`

### Current behavior

`processDefinitionKey` is not present

### Expected behavior

`processDefinitionKey` should be present

### Workaround

none

### Environment

SaaS & SM

### Version

- Camunda: [e.g. 8.8.0]

### Rootcause

This is due to the `EventFromProcessInstanceHandler` class, which has been removed, and was previously setting the `processDefinitionKey` in the `EventEntity`.  `EventFromProcessMessageSubscriptionHandler` was then updating the `EventEntity`.

Now that we only have the latest handler, `processDefinitionKey` is never set.

### Solution ideas

We would need to add this field to `ProcessMessageSubscriptionRecordValue`, and all the way up.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

Tracks the process defintion key also for **process** message subscriptions (already present in start message subscriptions).

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #40325

### CODE REVIEW

File: zeebe/protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java [hunk 1]
```diff
@@ -1295,13 +1295,16 @@ final var record = new DeploymentDistributionRecord();
...
+              final long processDefinitionKey = 6L;
               final String correlationKey = "key";
               final long messageKey = 3L;
               final long requestId = 4L;
               final int requestStreamId = 5;
 
               return new MessageSubscriptionRecord()
                   .setElementInstanceKey(elementInstanceKey)
+                  .setProcessDefinitionKey(processDefinitionKey)
+                  .setMessageKey(processDefinitionKey)
```
Comment (johnBgood) [inline zeebe/protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java]: `setMessageKey` has been added by mistake I guess

Comment (tmetzke) [reply zeebe/protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java]: 🤯 👍

Comment (tmetzke) [reply zeebe/protocol-impl/src/test/java/io/camunda/zeebe/protocol/impl/JsonSerializableToJsonTest.java]: Fixed with https://github.com/camunda/camunda/pull/40366/commits/2bf26eb13edfd46334c9588548e4bbc3d6a5f957

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/MessageSubscriptionFromProcessMessageSubscriptionHandler.java [hunk 2]
```diff
@@ -75,6 +75,11 @@ public void updateEntity(
       entity.setProcessInstanceKey(processInstanceKey);
     }
 
+    final long processDefinitionKey = recordValue.getProcessDefinitionKey();
+    if (processDefinitionKey > 0) {
+      entity.setProcessDefinitionKey(processDefinitionKey);
+    }
```
Comment (georgios-goulos) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/MessageSubscriptionFromProcessMessageSubscriptionHandler.java:87]: Why are we doing this check here but not in `zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/CorrelatedMessageSubscriptionFromProcessMessageSubscriptionHandler.java`?

```java
.setProcessDefinitionKey(value.getProcessDefinitionKey())
```

**Review by georgios-goulos — COMMENTED** [review]
I just had one question while going through the app logic. I will take a look at the tests too

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/MessageSubscriptionFromProcessMessageSubscriptionHandler.java (hunk 2 above)
Comment (tmetzke) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/MessageSubscriptionFromProcessMessageSubscriptionHandler.java:87]: With `CorrelatedMessageSubscriptionFromProcessMessageSubscriptionHandler`, we only handle one intent: CORRELATED. We never override the exported data, as the correlation occurs only once per subscription & message key combination.

For `MessageSubscriptionFromProcessMessageSubscriptionHandler`, we handle multiple intents that may arrive with different sets of keys in the records. Not all engine records contain all the keys in all circumstances, as we don't always need them all. We don't want to remove any previously written data in secondary storage, so we only update the data when it's considered "set" by the engine record.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/message/MessageSubscriptionStateTest.java [hunk 3]
```diff
@@ -95,17 +95,19 @@ public void shouldVisitSubscription() {
...
+    assertThat(expectedSubscription.getElementInstanceKey())
+        .isEqualTo(expectedSubscription.getElementInstanceKey());
+    assertThat(expectedSubscription.getProcessDefinitionKey())
+        .isEqualTo(expectedSubscription.getProcessDefinitionKey());
+    assertThat(expectedSubscription.getMessageName())
+        .isEqualTo(expectedSubscription.getMessageName());
+    assertThat(expectedSubscription.getCorrelationKey())
+        .isEqualTo(expectedSubscription.getCorrelationKey());
+    assertThat(expectedSubscription.getVariables()).isEqualTo(expectedSubscription.getVariables());
+    assertThat(subscriptions.getFirst().isCorrelating()).isFalse();
```
Comment (georgios-goulos) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/message/MessageSubscriptionStateTest.java]: Given the previous assertions I'd expect these to be

```suggestion
    assertThat(expectedSubscription.getProcessInstanceKey())
        .isEqualTo(subscription.getProcessInstanceKey());
    assertThat(expectedSubscription.getElementInstanceKey())
        .isEqualTo(subscription.getElementInstanceKey());
    assertThat(expectedSubscription.getProcessDefinitionKey())
        .isEqualTo(subscription.getProcessDefinitionKey());
    assertThat(expectedSubscription.getMessageName())
        .isEqualTo(subscription.getMessageName());
    assertThat(expectedSubscription.getCorrelationKey())
        .isEqualTo(subscription.getCorrelationKey());
assertThat(expectedSubscription.getVariables()).isEqualTo(subscription.getVariables());
```

**Review by georgios-goulos — DISMISSED** [review]

**Comment by johnBgood** [comment]
@tmetzke What do you think about including this idea in the API documentation for the `processDefinitionKey` description:
```json
  processDefinitionKey:
    allOf:
      - $ref: "#/components/schemas/ProcessDefinitionKey"
    description: The process definition key associated with this message subscription. Available starting from 8.8.2.
```

As a user, I'd like to know when it's available or not. WDYT?

**Comment by tmetzke** [comment]
> As a user, I'd like to know when it's available or not. WDYT?

@johnBgood, I generally like this, yes. We do this for the [user task name filter](https://github.com/camunda/camunda/blob/cd773e98ea99b29c89a246d8f00d60f79a8bed79/zeebe/gateway-protocol/src/main/proto/rest-api.yaml#L6104-L6108) as well 👍

**Comment by georgios-goulos** [comment]
```
Available starting from 8.8.2.
```

Will this be backported to 8.8? 🤔

**Comment by tmetzke** [comment]
> ```
> Available starting from 8.8.2.
> ```
> 
> Will this be backported to 8.8? 🤔

In this PR here, I'll set it to 8.9. If we backport it (not sure yet, probably not), we can adjust it 👍

**Review by johnBgood — APPROVED** [review]

File: zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json [hunk 4]
```diff
@@ -22,6 +22,9 @@
             "processInstancePartitionId": {
               "type": "integer"
             },
+            "processDefinitionKey": {
```
Comment (georgios-goulos) [inline zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json:25]: Are these `zeebe-record` index templates still used in 8.9?

Comment (tmetzke) [reply zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json:25]: I was under the impression that they are not, no 👍

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml
Comment (tmetzke) [inline zeebe/gateway-protocol/src/main/proto/rest-api.yaml:1]: @johnBgood, this shouldn't have been restored 😅

Comment (johnBgood) [reply zeebe/gateway-protocol/src/main/proto/rest-api.yaml:1]: I think it's an old commit, I fixed it already, correct?

File: zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json (hunk 4 above)
Comment (johnBgood) [reply zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json:25]: It was required for the OS tests, what's used in 8.9? And what would you recommend, should I still add the field there?

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml
Comment (tmetzke) [reply zeebe/gateway-protocol/src/main/proto/rest-api.yaml:1]: Apparently, yeah, I must have selected one commit accidentally, maybe 🤷

File: zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json (hunk 4 above)
Comment (tmetzke) [reply zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json:25]: Really good question. Can you check with the data layer team on the ask channel whether we should still extend Zeebe ES/OS templates or not? And if not, if we should adjust/remove the OpensearchIT in that regard?

Comment (tmetzke) [reply zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json:25]: Responses from @panagiotisgts 

>We're still supporting ES/OS exporters, so the value should be present in the Zeebe record templates. Also, make sure to exclude that value from being Serialized in previous version since, existing 8.8 indices which do not have this property field will throw exceptions regarding undeclared fields on strict mappings, [example to do so](https://github.com/camunda/camunda/blob/f028b2f497d59cce91a9e30f7517ab378a832b63/zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/BulkIndexRequest.java#L186). This has to be done for both ES and OS.

>ES/OS exporters are replaced by the CamundaExporter as of 8.8, we still have to support them for Optimize, but the bulk of the data is not being exported by these exporters by default. Customers however can still enable exporting of desired records through ES/OS - for their business needs. ES/OS Exporters likely will be deprecated in the future.
In the file I linked, there are two object mappers instantiated, one for the current version of records (8.9) and one for the previous version (in this case 8.8). The previous version mapper should not include the new property when serializing the MessageSubscription records. This is done using the Mixins at the moment to ignore specific properties

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/MessageSubscriptionSearchTest.java [hunk 5]
```diff
@@ -17,13 +17,14 @@
...
 import io.camunda.client.api.search.response.MessageSubscription;
+import io.camunda.qa.util.multidb.CamundaMultiDBExtension.DatabaseType;
 import io.camunda.qa.util.multidb.MultiDbTest;
 import java.util.Comparator;
 import java.util.List;
 import org.junit.jupiter.api.BeforeAll;
 import org.junit.jupiter.api.Test;
 
-@MultiDbTest
+@MultiDbTest(DatabaseType.RDBMS)
```
Comment (tmetzke) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/MessageSubscriptionSearchTest.java]:
```suggestion
@MultiDbTest
```

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/MessageSubscriptionFilterTransformer.java [hunk 6]
```diff
@@ -13,6 +13,7 @@
 import static io.camunda.search.clients.query.SearchQueryBuilders.stringOperations;
 import static io.camunda.search.clients.query.SearchQueryBuilders.stringTerms;
 import static io.camunda.webapps.schema.descriptors.IndexDescriptor.TENANT_ID;
+import static io.camunda.webapps.schema.descriptors.template.CorrelatedMessageSubscriptionTemplate.PROCESS_DEFINITION_KEY;
```
Comment (tmetzke) [inline search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/MessageSubscriptionFilterTransformer.java]: Not needed
```suggestion
```

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/MessageSubscriptionFilterTransformer.java [hunk 7]
```diff
@@ -43,6 +44,7 @@ public SearchQuery toSearchQuery(final MessageSubscriptionFilter filter) {
         List.of(messageSubscriptionTerm),
         longOperations(KEY, filter.messageSubscriptionKeyOperations()),
         stringOperations(BPMN_PROCESS_ID, filter.processDefinitionIdOperations()),
+        longOperations(PROCESS_DEFINITION_KEY, filter.processDefinitionKeyOperations()),
```
Comment (tmetzke) [inline search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/MessageSubscriptionFilterTransformer.java]: Already exists in the line below
```suggestion
```

File: zeebe/gateway-protocol/src/main/proto/v2/messages.yaml [hunk 8]
```diff
@@ -323,6 +323,10 @@ components:
           allOf:
             - $ref: 'filters.yaml#/components/schemas/MessageSubscriptionKeyFilterProperty'
           description: The message subscription key associated with this message subscription.
+        processDefinitionKey:
+          allOf:
+            - $ref: 'filters.yaml#/components/schemas/ProcessDefinitionKeyFilterProperty'
+          description: The process definition key associated with this correlated message subscription. This only works for data created with 8.9 and onwards. Message subscriptions from prior versions don't contain this data and cannot be found.
```
Comment (tmetzke) [inline zeebe/gateway-protocol/src/main/proto/v2/messages.yaml]:
```suggestion
          description: The process definition key associated with this correlated message subscription. This only works for data created with 8.9 and later.
```

File: zeebe/gateway-protocol/src/main/proto/v2/messages.yaml [hunk 9]
```diff
@@ -510,7 +514,7 @@ components:
         processDefinitionKey:
           allOf:
             - $ref: 'filters.yaml#/components/schemas/ProcessDefinitionKeyFilterProperty'
-          description: The process definition key associated with this correlated message subscription.
+          description: The process definition key associated with this correlated message subscription. This only works for data created with 8.9 and onwards. Correlated message subscriptions from prior versions don't contain this data and cannot be found.
```
Comment (tmetzke) [inline zeebe/gateway-protocol/src/main/proto/v2/messages.yaml]:
```suggestion
          description: The process definition key associated with this correlated message subscription. For intermediate message events, this only works for data created with 8.9 and later.
```

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/MessageSubscriptionSearchTest.java [hunk 10]
```diff
@@ -17,6 +17,7 @@
 import io.camunda.client.CamundaClient;
 import io.camunda.client.api.search.enums.MessageSubscriptionState;
 import io.camunda.client.api.search.response.MessageSubscription;
+import io.camunda.qa.util.multidb.CamundaMultiDBExtension.DatabaseType;
```
Comment (tmetzke) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/MessageSubscriptionSearchTest.java]:
```suggestion
```

File: zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json (hunk 4 above)
Comment (tmetzke) [reply zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json:25]: @panagiotisgts, I added this for ES & OS Zeebe exporters. Could you double-check that this is as expected?

Comment (panagiotisgts) [reply zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json:25]: @tmetzke  I've only looked at the `BulkIndexRequest` modifications for ES/OS and LGTM. Could you add the respective test cases in the `BulkIndexRequestTest.SerializationTest` for previous and current versions as per the existing cases?

Comment (tmetzke) [reply zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json:25]: Thank you, @panagiotisgts 🙏 
Yes, absolutely, I even had it open in my IDE, but forgot to add test cases there. On it 👍

Comment (tmetzke) [reply zeebe/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-message-subscription-template.json:25]: Done in https://github.com/camunda/camunda/pull/40366/commits/f51d1f793645665810c0734b47c863e05a5c0be1

**Comment by tmetzke** [comment]
I believe this is done now.
@johnBgood, please check again if everything you'd expect is there.
@georgios-goulos, maybe you can give this a second look after all the recent changes.
@panagiotisgts, I added the bulk index request tests for both records.

**Review by georgios-goulos — APPROVED** [review]
LGTM!

**Comment by johnBgood** [comment]
Perfect! Thank you for helping

**Review by johnBgood — APPROVED** [review]
