### PR TITLE
Use partition ID for journal metrics

### LINKED ISSUE #11556: Fix journal metrics
**Description**

Since the journal metrics use the logname as the partition label value (e.g. `raft-partition-1`) and not the partition ID itself, filtering by partition is wrong for all journal metrics.

This should be fixed, so we can either filter by partition (preferably), or they are outside of the partition filter.

Secondly, the journal append latency graph shows the average of the log appender commit latency, and not the journal's append latency. This should be fixed.

We can decide if we'd like to also have the log appender latency or not as well as a separate graph.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes the journal labels so the partition correctly refers to the partition ID, and not the journal name. This means the journal metrics can be filtered on the dashboard just like all the others.

## Related issues

closes #11556 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Running a benchmark where you can see it in action: https://grafana.dev.zeebe.io/goto/3ZZYEuA4k?orgId=1

File: journal/src/main/java/io/camunda/zeebe/journal/file/JournalMetrics.java [hunk 1]
```diff
@@ -104,16 +104,20 @@ final class JournalMetrics {
...
-    segmentCount = SEGMENT_COUNT.labels(logName);
-    journalOpenTime = JOURNAL_OPEN_DURATION.labels(logName);
-    segmentAllocationTime = SEGMENT_ALLOCATION_TIME.labels(logName);
-    appendLatency = APPEND_LATENCY.labels(logName);
-    appendRate = APPEND_RATE.labels(logName);
-    appendDataRate = APPEND_DATA_RATE.labels(logName);
+  JournalMetrics(final String name) {
+    // hacky way of fetching the partition ID if the journal was created from a partition group; if
+    // not, the name is used as is
+    final var partition = name.substring(name.lastIndexOf('-') + 1);
```
Comment (oleschoenburg) [inline journal/src/main/java/io/camunda/zeebe/journal/file/JournalMetrics.java:110]: :wrench: Can't we "just" pass in the partition id? `RaftPartitionServer#createRaftStorage` knows the id, from there it's just a lot of passing it down...

**Review by lenaschoenburg — APPROVED** [review]

File: journal/src/main/java/io/camunda/zeebe/journal/file/JournalMetrics.java (hunk 1 above)
Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/JournalMetrics.java]: We can. Keep in mind the journal name is not the ID, but [`partitionGroupName`-partition-`partitionId`]

So passing the partition ID here is really just for the metrics and nothing else. It felt like more refactoring than I was comfortable doing for this, since the storage is built in a way that it has a prefix and is not partition aware really. I'm not against pushing down to the storage the building of the prefix/name thing, but I also didn't see a ton of value of doing it right now :shrug: 

Doing it, means we have to refactor the `RaftStorageBuilder` to take in the partition group and the ID, which then creates the prefix itself and owns it (since it needs it for the lock and other stuff). We then pass it down to the journal (for backwards compat) but also the ID just for the metrics. Seems like a lot of cruft for just that :smile: Though maybe that's saying more about the whole builder set up than anything else :smile: 

I'm happy to do that. There's some small value in being explicit, for sure, just seemed to me like very small :sweat_smile: 

I added a last commit which does exactly this. If you prefer that, then let's go with it.

Comment (oleschoenburg) [reply journal/src/main/java/io/camunda/zeebe/journal/file/JournalMetrics.java]: Thanks for doing this! I do prefer it this way but feel free to just reject a :wrench: next time :wink:

**Review by lenaschoenburg — APPROVED** [review]

**Comment by npepinpe** [comment]
bors merge

File: journal/src/main/java/io/camunda/zeebe/journal/file/JournalMetrics.java (hunk 1 above)
Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/JournalMetrics.java]: Ofc, but in this case it was a pretty quick/small change anyway.
