### PR TITLE
Await record writting

### LINKED ISSUE #10913: StreamProcessorTest#shouldBeAbleToWriteRejectionOnErrorHandling
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
  - at least once
- Does it block your work?
  - no
- Do we suspect that it is a real failure?
  - no

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 26, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 26.364 s <<< FAILURE! - in io.camunda.zeebe.streamprocessor.StreamProcessorTest
Error:  io.camunda.zeebe.streamprocessor.StreamProcessorTest.shouldBeAbleToWriteRejectionOnErrorHandling  Time elapsed: 8.768 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting value to be true but was false
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at io.camunda.zeebe.streamprocessor.StreamProcessorTest.shouldBeAbleToWriteRejectionOnErrorHandling(StreamProcessorTest.java:637)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

https://github.com/camunda/zeebe/actions/runs/3391040744/jobs/5635816543

See the build link for logs.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

It might happen that the records are not yet written to the 'log' and this would fail the test, we need to await that the reader can see the new records before continuing

## Related issues

resolves a flaky test

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/streamprocessor/StreamProcessorTest.java [hunk 1]
```diff
@@ -286,6 +286,9 @@ public void shouldSetSourcePointerForFollowUpRecords() {
     final var firstRecord = logStreamReader.next();
     assertThat(firstRecord.getSourceEventPosition()).isEqualTo(-1);
     final var firstRecordPosition = firstRecord.getPosition();
+
+    await("should write follow up events")
+        .untilAsserted(() -> assertThat(logStreamReader.hasNext()).isTrue());
     while (logStreamReader.hasNext()) {
       final var followUpRecord = logStreamReader.next();
       assertThat(followUpRecord.getSourceEventPosition()).isEqualTo(firstRecordPosition);
```
Comment (deepthidevaki) [inline engine/src/test/java/io/camunda/zeebe/streamprocessor/StreamProcessorTest.java:294]: :wrench: Since we are expecting exactly two follow up records, I suggest to remove the loop and verify that.
```
    await("should write follow up events")
        .untilAsserted(() -> assertThat(logStreamReader.hasNext()).isTrue());    
    assertThat(logStreamReader.next().getSourceEventPosition()).isEqualTo(firstRecordPosition);
    assertThat(logStreamReader.next().getSourceEventPosition()).isEqualTo(firstRecordPosition);
```

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Comment by npepinpe** [comment]
As this may fix the flakiest test we have, do you think you could take over and merge this @deepthidevaki ?

**Comment by deepthidevaki** [comment]
My comments were only a suggestion. So I will not apply them. I will merge this PR. 

bors r+

**Comment by npepinpe** [comment]
BTW, do we know if this had to be backported?
