### PR TITLE
fix: move `filter` criteria of v2 batch endpoints under a new filter root level request attribute

### LINKED ISSUE #37332: Move filter criteria of V2 batch endpoints under a new `filter` root-level request attribute
### 

### 

### 

### 

### Description

The following two endpoints deviate from other V2 batch endpoints and are not easily extensible in the future:
* https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/resolve-incidents-batch-operation/
* https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/cancel-process-instances-batch-operation/

They expect all filter criteria on the root-level of the request.

### Steps to reproduce

1. Inspect the endpoints

### Current behavior

Filter criteria are expected on the request root level.

### Expected behavior

Filter criteria are expected in a `filter` object attribute at the request root level.

### Environment

SaaS & SM

### Version

- Component Version: 8.8.0-SNAPSHOT

### Rootcause

The endpoints are defined in an inconsistent and hard-to-extend way.

### Solution ideas

* Introduce a `filter` object attribute at the request's root level, containing all the filter criteria currently expected there.
* Adjust the Operate UI to the new DTO structure.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

- [Internal communication](https://camunda.slack.com/archives/C088A1LL5CZ/p1756316380788879?thread_ts=1756219807.947399&cid=C088A1LL5CZ) highlighting the need

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description

This PR restructures the v2 batch operation endpoints to move filter criteria under a new "filter" root-level request attribute, ensuring API consistency across all batch operation endpoints. The change affects process instance cancellation and incident resolution endpoints to match the existing pattern used by migration and modification operations.

- Updates REST API schema to use dedicated request objects with nested filter attributes
- Modifies Java client implementation to construct proper request bodies with the new structure
- Enhances validation logic to handle the restructured request format
- **Ensures a valid filter object is required by all batch endpoints with at least one criteria filled**

## Related issues

closes #37332

### CODE REVIEW

File: clients/java/src/main/java/io/camunda/client/impl/command/CreateBatchOperationCommandImpl.java [hunk 1]
```diff
@@ -150,6 +152,12 @@ private Object getBody() {
       return new ProcessInstanceModificationBatchOperationRequest()
           .filter(provideSearchRequestProperty(filter))
           .moveInstructions(moveInstructions);
+    } else if (type == BatchOperationTypeEnum.CANCEL_PROCESS_INSTANCE) {
+      return new ProcessInstanceCancellationBatchOperationRequest()
+          .filter(provideSearchRequestProperty(filter));
+    } else if (type == BatchOperationTypeEnum.RESOLVE_INCIDENT) {
+      return new ProcessInstanceIncidentResolutionBatchOperationRequest()
+          .filter(provideSearchRequestProperty(filter));
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/client/impl/command/CreateBatchOperationCommandImpl.java]: ❓ Should we go for a switch like in the method above, failing if any other option is provided?

File: clients/java/src/test/java/io/camunda/client/batchoperation/CreateBatchOperationTest.java [hunk 2]
```diff
@@ -147,4 +150,28 @@ public void shouldSendProcessInstanceModificationCommand() {
     assertThat(lastRequest.getMoveInstructions().get(1).getSourceElementId()).isEqualTo("source2");
     assertThat(lastRequest.getMoveInstructions().get(1).getTargetElementId()).isEqualTo("target2");
   }
+
+  @Test
+  public void shouldSendResolveIncidentCommand() {
```
Comment (tmetzke) [inline clients/java/src/test/java/io/camunda/client/batchoperation/CreateBatchOperationTest.java:155]: 👍 Nice catch and addition

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java [hunk 3]
```diff
@@ -184,8 +187,9 @@ public CompletableFuture<ResponseEntity<Object>> cancelProcessInstancesBatchOper
   @RequiresSecondaryStorage
   @CamundaPostMapping(path = "/incident-resolution")
   public CompletableFuture<ResponseEntity<Object>> resolveIncidentsBatchOperation(
-      @RequestBody(required = false) final ProcessInstanceFilter filter) {
+      @RequestBody final ProcessInstanceIncidentResolutionBatchOperationRequest request) {
 
+    final ProcessInstanceFilter filter = request != null ? request.getFilter() : null;
```
Comment (tmetzke) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java]: ❓ So, we can work without a filter here, right? I guess that makes the request body optional. What happens if no filter is provided? We don't resolve incidents for any process instance or for all process instances we can find?

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml [hunk 4]
```diff
@@ -2039,11 +2039,11 @@ paths:
         filters for state are ignored and overridden during this batch operation.
         This is done asynchronously, the progress can be tracked using the batchOperationKey from the response and the batch operation status endpoint (/batch-operations/{batchOperationKey}).
       requestBody:
-        required: false
+        required: true
```
Comment (tmetzke) [inline zeebe/gateway-protocol/src/main/proto/rest-api.yaml:2042]: 🔧 I believe this doesn't change. The body is still not required.

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml [hunk 5]
```diff
@@ -2000,11 +2000,11 @@ paths:
         parentProcessInstanceKey are ignored and overridden during this batch operation.
         This is done asynchronously, the progress can be tracked using the batchOperationKey from the response and the batch operation status endpoint (/batch-operations/{batchOperationKey}).
       requestBody:
-        required: false
+        required: true
```
Comment (tmetzke) [inline zeebe/gateway-protocol/src/main/proto/rest-api.yaml:2003]: 🔧 I believe this doesn't change. The body is still not required.

**Review by tmetzke — COMMENTED** [review]
👍 Thanks for this.
❓ I left some questions and minor improvement suggestions.

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml (hunk 4 above)
Comment (mustafadagher) [reply zeebe/gateway-protocol/src/main/proto/rest-api.yaml:2042]: I saw it was for the migration and modification, so changed it here too.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java (hunk 3 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java]: > What happens if no filter is provided? We don't resolve incidents for any process instance or for all process instances we can find?

That's a good question that needs further investigation, probably not part of this PR though

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java [hunk 6]
```diff
@@ -171,9 +172,9 @@ public ResponseEntity<Object> sequenceFlows(
   @RequiresSecondaryStorage
   @CamundaPostMapping(path = "/cancellation")
   public CompletableFuture<ResponseEntity<Object>> cancelProcessInstancesBatchOperation(
-      @RequestBody(required = false) final ProcessInstanceFilter filter) {
-
-    return SearchQueryRequestMapper.toProcessInstanceFilter(filter)
+      @RequestBody(required = false)
+          final ProcessInstanceCancellationBatchOperationRequest request) {
+    return SearchQueryRequestMapper.toProcessInstanceFilter(request.getFilter())
```
Comment (tmetzke) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java]: 🔧 Well, this can fail with an NPE, to be honest. The `request` can be `null`. We need to check for this and provide a `null` filter in that case. That was correct previously 😅

Comment (tmetzke) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java]: We can also add test cases for this. We do this for search endpoints as well:
* The controller can handle "no request body".
* The controller can handle "empty request body"

File: zeebe/gateway-protocol/src/main/proto/rest-api.yaml [hunk 7]
```diff
@@ -10869,6 +10869,24 @@ components:
...
           type: string
+    ProcessInstanceCancellationBatchOperationRequest:
+      type: object
+      description: |
+        The process instance filter that defines which process instances should be canceled.
+      properties:
+        filter:
+          $ref: "#/components/schemas/ProcessInstanceFilter"
+      required:
+        - filter
```
Comment (tmetzke) [inline zeebe/gateway-protocol/src/main/proto/rest-api.yaml:10880]: 🔧 This prevents sending an empty request body (i.e., `{}`). But the controller doesn't enforce this, actually. So, this is not correct.

Comment (mustafadagher) [reply zeebe/gateway-protocol/src/main/proto/rest-api.yaml:10880]: I believe it should not be required for migration and modification too, right?

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java (hunk 6 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java]: I made sure it's required, and a filter has to be there too with at least one criteria filled. added tests as well

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java [hunk 8]
```diff
@@ -758,18 +759,29 @@ public static Either<ProblemDetail, ProcessInstanceMigrateRequest> toMigrateProc
...
+
   public static Either<ProblemDetail, ProcessInstanceMigrateBatchOperationRequest>
       toProcessInstanceMigrationBatchOperationRequest(
           final ProcessInstanceMigrationBatchOperationRequest request) {
     // First validate filter and return early
-    final var filter = SearchQueryRequestMapper.toProcessInstanceFilter(request.getFilter());
+    final var filter = toRequiredProcessInstanceFilter(request.getFilter());
     if (filter.isLeft()) {
-      return Either.left(createProblemDetail(filter.getLeft()).get());
+      return Either.left(filter.getLeft());
```
Comment (tmetzke) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java]: 🔧 For consistency and better user experience, we should collect validation issues and return one problem detail in the end that contains all of them. Otherwise, we'll annoy users with step-by-step validation errors (e.g. they fixed the error we returned and then another one pops up that was present before already). Other validation routines here do the same.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/validator/ProcessInstanceRequestValidator.java [hunk 9]
```diff
@@ -71,21 +71,25 @@ public static Optional<ProblemDetail> validateCancelProcessInstanceRequest(
   }
 
   public static Optional<ProblemDetail> validateMigrateProcessInstanceBatchOperationRequest(
-      final ProcessInstanceMigrationBatchOperationPlan request) {
+      final ProcessInstanceMigrationBatchOperationRequest request) {
```
Comment (tmetzke) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/validator/ProcessInstanceRequestValidator.java:79]: ❓ Do we actually need to change this? Why can't we hand in the migration plan? We only use the request here to extract the migration plan now.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java [hunk 10]
```diff
@@ -758,18 +759,29 @@ public static Either<ProblemDetail, ProcessInstanceMigrateRequest> toMigrateProc
...
     }
 
     final var migrationPlan = request.getMigrationPlan();
```
Comment (tmetzke) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java:776]: ❓ Do we need to check if the migration plan is `null`? Does the framework check this for us?

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/SearchQueryRequestMapper.java [hunk 11]
```diff
@@ -957,6 +957,18 @@ private static OffsetDateTime toOffsetDateTime(final String text) {
     return StringUtils.isEmpty(text) ? null : OffsetDateTime.parse(text);
   }
 
+  public static Either<List<String>, ProcessInstanceFilter> toRequiredProcessInstanceFilter(
+      final io.camunda.zeebe.gateway.protocol.rest.ProcessInstanceFilter filter) {
+    if (filter == null) {
+      return Either.left(List.of(ERROR_MESSAGE_EMPTY_ATTRIBUTE.formatted("filter")));
+    }
+    final var emptyFilter = new io.camunda.zeebe.gateway.protocol.rest.ProcessInstanceFilter();
```
Comment (tmetzke) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/SearchQueryRequestMapper.java]: 🔧 Should we create a constant for this so we don't create this anew for every validation?

File: zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java [hunk 12]
```diff
@@ -1638,4 +1644,360 @@ public void shouldGetProcessInstanceIncidents() {
...
+        .expectStatus()
+        .isBadRequest()
+        .expectHeader()
+        .contentType(MediaType.APPLICATION_PROBLEM_JSON)
+        .expectBody()
+        .json(expectedBody, JsonCompareMode.STRICT);
+  }
+
+  @Test
+  void shouldRejectMigrateProcessInstancesBatchOperationWithEmptyFilter() {
```
Comment (tmetzke) [inline zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java:1880]: ❓ Do we already check for "no migration plan" and "empty migration plan"?

File: zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java [hunk 13]
```diff
@@ -1638,4 +1644,360 @@ public void shouldGetProcessInstanceIncidents() {
...
+        .expectStatus()
+        .isBadRequest()
+        .expectHeader()
+        .contentType(MediaType.APPLICATION_PROBLEM_JSON)
+        .expectBody()
+        .json(expectedBody, JsonCompareMode.STRICT);
+  }
+
+  @Test
+  void shouldRejectModifyProcessInstancesBatchOperationWithEmptyFilter() {
```
Comment (tmetzke) [inline zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java:2055]: ❓ Do we already check for "no instructions" and "empty instructions"?

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/validator/ProcessInstanceRequestValidator.java (hunk 9 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/validator/ProcessInstanceRequestValidator.java:79]: I'm going to use it now to add the filter violations to the rest of violations

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java (hunk 10 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java:776]: They are actually all checked out of the box, even the filter, and are also wrapped in a problem detail response body, just not the same format as the rest of the validations.
e.g. the title would be `Bad Request` not `INVALID_ARGUEMENT`, and the detail would be more verbose.

File: zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java (hunk 12 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java:1880]: empty is already validated indirectly with the tests checking no target process definitions and no mapping instructions, but I can add a dedicated test

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java (hunk 10 above)
Comment (tmetzke) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java:776]: OK, thanks for trying! That's probably something we could fix in the REST layer's global exception handler. They will be the default Spring problem details we create for certain scenarios. Not the scope of this PR though.

File: zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java (hunk 13 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java:2055]: added

File: zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java (hunk 12 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceControllerTest.java:1880]: added new tests

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/SearchQueryRequestMapper.java (hunk 11 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/SearchQueryRequestMapper.java]: done

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java (hunk 10 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java:776]: I did include specific validations for migration and modification requests.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java (hunk 8 above)
Comment (mustafadagher) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/RequestMapper.java]: done

**Comment by mustafadagher** [comment]
> # 🧪 Flaky Tests Summary
> _👻 Haunted Tests — They Fail When No One's Watching_
> 
> * [**shouldTriggerNonInterruptingEventSubProcess**](https://github.com/camunda/camunda/tree/md/37332-move-filter-criteria-of-v2-batch-endpoints-under-a-new-filter-root-level-request-attribute/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/AdHocSubProcessTest.java) – 💀 **100% flakiness**
>   
>   * Jobs: `zeebe-unit-tests/General-Core Features`
>   * Package: `io.camunda.zeebe.engine.processing.bpmn.activity`
>   * Class: `AdHocSubProcessTest`
>   * Occurrences: 1 / 1
> * [**shouldTriggerNonInterruptingEventSubProcessMultipleTimes**](https://github.com/camunda/camunda/tree/md/37332-move-filter-criteria-of-v2-batch-endpoints-under-a-new-filter-root-level-request-attribute/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/AdHocSubProcessTest.java) – 💀 **100% flakiness**
>   
>   * Jobs: `zeebe-unit-tests/General-Core Features`
>   * Package: `io.camunda.zeebe.engine.processing.bpmn.activity`
>   * Class: `AdHocSubProcessTest`
>   * Occurrences: 1 / 1
> * [**shouldRecreateJobAfterEventSubProcessCompletion**](https://github.com/camunda/camunda/tree/md/37332-move-filter-criteria-of-v2-batch-endpoints-under-a-new-filter-root-level-request-attribute/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java) – 💀 **100% flakiness**
>   
>   * Jobs: `zeebe-unit-tests/General-Core Features`
>   * Package: `io.camunda.zeebe.engine.processing.bpmn.activity`
>   * Class: `JobBasedAdHocSubProcessTest`
>   * Occurrences: 1 / 1
> * [**shouldTriggerNonInterruptingEventSubProcess**](https://github.com/camunda/camunda/tree/md/37332-move-filter-criteria-of-v2-batch-endpoints-under-a-new-filter-root-level-request-attribute/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java) – 💀 **100% flakiness**
>   
>   * Jobs: `zeebe-unit-tests/General-Core Features`
>   * Package: `io.camunda.zeebe.engine.processing.bpmn.activity`
>   * Class: `JobBasedAdHocSubProcessTest`
>   * Occurrences: 1 / 1
> * [**shouldTriggerNonInterruptingEventSubProcessMultipleTimes**](https://github.com/camunda/camunda/tree/md/37332-move-filter-criteria-of-v2-batch-endpoints-under-a-new-filter-root-level-request-attribute/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/JobBasedAdHocSubProcessTest.java) – 💀 **100% flakiness**
>   
>   * Jobs: `zeebe-unit-tests/General-Core Features`
>   * Package: `io.camunda.zeebe.engine.processing.bpmn.activity`
>   * Class: `JobBasedAdHocSubProcessTest`
>   * Occurrences: 1 / 1
> 
> If the changes affect this area, **please check and fix before merging**. If not, **leave a quick comment** explaining why it's likely unrelated.

That's new, and I like it. 
But no, can't be right. I only made changes related to batch operations rest API endpoints in this PR, and all of those are engine tests.

**Review by tmetzke — APPROVED** [review]
👍 Looks good to me, thanks for following up here, @mustafadagher 🙌
