### PR TITLE
Reset reschedule flag correctly on JobTimeoutTrigger

### LINKED ISSUE #13190: Jobs not timing out in v8.1.12
**Describe the bug**

In a self-hosted 8.1.12 Zeebe cluster, unfinished jobs are not timing out when the workers are terminated. As a result, the jobs are not sent back out to new workers and reactivated. They and the process instances that contain them remain stuck permanently.

On Zeebe 1.3.2, we do see the jobs timing out as expected.

**To Reproduce**

We are still working on reproducing the issue. We wanted to alert you right away in the interim, because we've seen this reliably in production and it's a blocker to upgrading.

The observed real world scenario is as follows:
1. Worker grabs a job
1. Worker gets a `SIGTERM` and shuts down without completing or failing the job
1. Worker starts back up
1. Worker is never reassigned the job by the Zeebe cluster

**Expected behavior**

We expect that jobs, when abandoned, would time out and be made available for other workers to pick up.

**Log/Stacktrace**

Below are screenshots from our own internal monitoring tool (similar to Operate), which consumes the Kafka messages from the Kafka Exporter.

Audit log snippet from 1.3.2, which shows the job timing out and then being reactivated and completed:

Screenshot 2023-06-22 at 12 28 11 PM

Audit log snippet from 8.1.12, which shows the job getting stuck without ever timing out:

image

**Environment:**
- OS: Linux
- Zeebe Version: 8.1.12 (via official Camunda Docker image)
- Configuration: 
  - Camunda Helm chart 8.1.6 (`zeebe` and `zeebe-gateway` subcharts only)
  - Kafka Exporter 3.1.1
  - [zeebe-client-ruby](https://github.com/zeebe-io/zeebe-client-ruby) 0.17.0 (also tested with 0.19.0)

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
On pause processing we set the `shouldReschedule` flag to false, in order to avoid jobs timing out during the pause of processing.

On resume we haven't reset the flag, which caused us to never timeout jobs again. This PR reset the flag and reschedules the timeout timer

## Related issues

closes https://github.com/camunda/zeebe/issues/13190

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java [hunk 1]
```diff
@@ -57,9 +57,8 @@ public void onPaused() {
 
   @Override
   public void onResumed() {
-    if (shouldReschedule) {
-      scheduleDeactivateTimedOutJobsTask();
-    }
+    shouldReschedule = true;
+    scheduleDeactivateTimedOutJobsTask();
```
Comment (Zelldon) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java:61]: 🔧 @korthout I think you mentioned directly calling `deactivateTimedOutJobs`. Not sure whether this is easily possible, since we need the taskResultBuilder. We could schedule it for Zero delay if you want.

https://github.com/camunda/zeebe/issues/13190#issuecomment-1631880802

This case is btw harder to test, that it is immediately executed, instead of after the delay, but might be enough our current next test. Let me know what you think.

**Review by korthout — APPROVED** [review]
Thanks @Zelldon

💭 I assume the `StreamProcessorLifecycleAware.onResumed()` guarantee is still valid:
> Callback which is called when the processing is resumed, will only called after onPaused was called before.

🔧 We should backport this to 8.2 and 8.1.

LGTM 👍

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java (hunk 1 above)
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java:61]: I was not specific enough. I did not specifically mean directly calling it or scheduling it again. Simply that we should make a starting pass again. So, I'm happy with the solution you proposed.

**Comment by Zelldon** [comment]
Bors r+

File: engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobTimeOutTest.java [hunk 2]
```diff
@@ -91,6 +91,24 @@ public void shouldTimeOutAfterReprocessing() {
...
+    final long jobKey = ENGINE.createJob(jobType, PROCESS_ID).getKey();
+    final long timeout = JobTimeoutTrigger.TIME_OUT_POLLING_INTERVAL.toMillis() * 2;
+
+    ENGINE.jobs().withType(jobType).withTimeout(timeout).activate();
+    ENGINE.pauseProcessing(1);
+    ENGINE.increaseTime(JobTimeoutTrigger.TIME_OUT_POLLING_INTERVAL);
+
+    // when
+    ENGINE.resumeProcessing(1);
+    ENGINE.increaseTime(JobTimeoutTrigger.TIME_OUT_POLLING_INTERVAL);
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobTimeOutTest.java:107]: Thanks @jaeger401 for your input.

I think I concentrated on the first issue you described, and code wise it didn't make a difference, but I agree it makes sense to have such an additional scenario covered and tested. I added the test already. Thanks again. :)

**Comment by korthout** [comment]
@Zelldon the `@RegressionTest` annotation only works for junit5 tests. You'll need to revert that change.

**Comment by Zelldon** [comment]
Time to change this @korthout 😉 Thanks for the hint 👍🏼
