### PR TITLE
Identity Migration: add entity IDs normalization configuration

### LINKED ISSUE #41605: The Identity migration application applies lowercase conversion unnecessarily to role IDs
### 

### 

### 

### 

### Description

* When migrating from 8.7 to 8.8, the Identity migration application moves roles from Management Identity to Orchestration Cluster Identity
* In that process, it converts role names in Mgmt Identity to role IDs in OC Identity to lowercase and restricts it to characters in the range `a-z0-9_@.-` ([reference 1](https://github.com/camunda/camunda/blob/5c6f431a595aa677f20e78abc08cfb2b82cb1ec6/migration/identity-migration/src/main/java/io/camunda/migration/identity/handler/sm/RoleMigrationHandler.java#L75), [reference 2](https://github.com/camunda/camunda/blob/5c6f431a595aa677f20e78abc08cfb2b82cb1ec6/migration/identity-migration/src/main/java/io/camunda/migration/identity/MigrationUtil.java#L73))
  * This is motivated by (however not equivalent to) the ID pattern in the Orchestration Cluster that is `[a-zA-Z0-9_~@.+-]+` ([reference](https://github.com/camunda/camunda/blob/c40a82108680df07061af192cffe81b03109dfed/security/security-core/src/main/java/io/camunda/security/configuration/SecurityConfiguration.java#L17))
* For example, role names that use mixed case like `thisIsMyRole` will change during migration to `thisismyrole`
* If such a role name/ID is used outside of the Orchestration Cluster, this reference becomes invalid after migration.
  * Example: 
    * I use the `candidateGroups` attribute of a BPMN user task and base this on my users' role names/IDs. I enter `thisIsMyRole` into the BPMN file
    * I write a tasklist application using the task search API filtering by candidate group; I populate the query parameter dynamically based on the current user's roles (e.g. obtained via /v2/authentication/me - [reference](https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/get-authentication/)); before migration, this value is `thisIsMyRole`; after migration it is `thisismyrole`
    * In effect, the task query won't return any tasks anymore after migration
    * Note that while the feature is called candidate_Groups_, it allows any String value input; there is no validation that the value identifies a true group
  * We can imagine other cases whenever role IDs are stored outside of the OC before migration and used to access OC APIs after migration
* There was no particularly strong reason for the lowercase conversion in the past ([reference](https://github.com/camunda/camunda/pull/33138#discussion_r2126803247))

### Steps to reproduce

1. Set up the C8 Helm Chart in the latest 8.7 patch level with Keycloak
2. Assign a user to a role that has a mixed case ID
3. Migrate to 8.8

### Current behavior

* The role ID was converted to lowercase

### Expected behavior

* Depending on configuration (see solution ideas), the role ID maintains mixed case

### Workaround

* Option 1: Re-create the role with correct case after migration
* Option 2: Change the role name to lowercase (and all usages of it) before migration

### Environment

SaaS & SM

### Version

- 8.8.4

### Rootcause

* See description

### Solution ideas

* Make the conversion to lower case configurable (boolean config property of the migration application) specifically for roles
  * So that people having problems only with the role ID conversion can simply clean up the previously incorrectly migrated roles and can run the migration app again
  * The default should remain as the current behavior, so that the possibility to run the migration application idempotently remains between patch level updates
* In addition, make the lower case conversion configurable for all ID conversions
  * The role-specific config overrule the general setting
  * The default should remain as the current behavior for the same reason as above (and for that reason also not match the OC default)
  * Making this configurable will give users more flexibility to workaround similar migration problems
* Make the [pattern of characters that are substituted](https://github.com/camunda/camunda/blob/5c6f431a595aa677f20e78abc08cfb2b82cb1ec6/migration/identity-migration/src/main/java/io/camunda/migration/identity/MigrationUtil.java#L73) configurable
  * The default should remain as the current behavior for the same reason as above (and for that reason also not match the OC default)
  * Making this configurable will give users more flexibility to workaround similar migration problems; since the ID validation pattern in OC Identiy is configurable ([reference](https://github.com/camunda/camunda/blob/c40a82108680df07061af192cffe81b03109dfed/security/security-core/src/main/java/io/camunda/security/configuration/SecurityConfiguration.java#L99-L105)), making it configurable in the migration app would match that and allow users to extend the pattern if they have circumstances requiring that; this can prevent depending on Camunda patches

### Dev -> QA handover

The QA test should reproduce the problem in a proper 8.7 -> 8.8 migration of a Helm Chart deloyment with Keycloak. It should specifically also validate that the new config properties for the Identity migration application can be specified through environment variables in a Helm Chart deployment.

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

* https://jira.camunda.com/browse/SUPPORT-30061

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

This PRs add a new property class to allow users to configure the entity IDs normalization. Example:

```
# Set defaults
camunda.migration.identity.entities.defaults.lowercase=true
camunda.migration.identity.entities.defaults.pattern=[^a-z0-9_@.-]

# Override for roles only
camunda.migration.identity.entities.role.lowercase=false

# Override for groups
camunda.migration.identity.entities.group.lowercase=false
camunda.migration.identity.entities.group.pattern=[^a-z0-9_]
```

## Related issues

closes #41605

### CODE REVIEW

File: migration/identity-migration/src/main/java/io/camunda/migration/identity/handler/sm/GroupMigrationHandler.java [hunk 1]
```diff
@@ -87,7 +91,7 @@ private void createGroupRoleMembership(final Group group) {
     groupRoles.forEach(
         role -> {
           try {
-            final var roleId = normalizeID(role.name());
+            final var roleId = normalizeID(role.name(), entitiesProperties, GROUP);
```
Comment (megglos) [inline migration/identity-migration/src/main/java/io/camunda/migration/identity/handler/sm/GroupMigrationHandler.java]: ❌ this is the role id, group names are not normalized in the SM case, as there Group entities are not migrated into the OC but the original name needs to be used as managed in the IDP.

Wdyt about extending the handler unit tests to ensure entity specific normalization config is applied as expected to FKs like these?

```suggestion
            final var roleId = normalizeID(role.name(), entitiesProperties, ROLE);
```

**Review by megglos — APPROVED** [review]
🚀  I like the generic solution, giving flexibility down the road.

One bug to address, still pre-approving and leaving the decision to request another review to you.

In terms of HC integration, are we ok with just making use of the [global OC env vars](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform-8.8/templates/orchestration/migration-identity-job.yaml#L49)? If we consider this exceptional, which my current perspective is, I guess that's fine. CC @ThorbenLindhauer do you still agree on that?

**Review by bmudric — APPROVED** [review]

**Comment by nicpuppa** [comment]
@megglos from my point of view yes

**Comment by ThorbenLindhauer** [comment]
I know it's merged already but I wanted to give the code a quick look, too.

Looks fine to me. One aspect: I would have considered choosing a more descriptive property name than `camunda.migration.identity.entities.defaults.pattern`, especially the `pattern` part. Maybe camunda.migration.identity.entities.defaults.id-substitution-pattern` or so.

edit: re configuring in Helm Chart as env var: Yeah, I think that's fine.

**Comment by nicpuppa** [comment]
@ThorbenLindhauer I don't have a preference tbh. I was planning to add a section in the migration doc explaining those property and how/when to use them. 
I think the shorter version (mine) is just more handy and less prone to error

**Comment by ThorbenLindhauer** [comment]
Given that the PR is merged, I think it's fine to keep it. And thanks for writing the docs for this, too, that's indeed important to have.
