### PR TITLE
fix: refactor permission deletion to consider overlapping authorizations

### LINKED ISSUE #40276: Authorization DELETE fails with HTTP 500 after PUT update with overlapping permissions (Permission index corruption)
### Component

C8-API

### Affected version

8.8, 8.9

### Severity

High

### Likelihood

High

### Description

Deleting authorizations fails with HTTP 500 "Internal Server Error" after performing a specific sequence of operations involving permission updates and authorization recreation. Bug appears to be resource-independent.

### Steps to reproduce

1. Creating multiple authorizations for the same resource (e.g., READ, UPDATE, and DELETE+CANCEL permissions)
2. Using PUT to update one authorization to add permissions that overlap with other existing authorizations
3. Deleting and recreating another authorization with the same parameters

### Current behavior

The authorization DELETE endpoint returns HTTP 500 when trying to delete an authorization that was previously updated, due to corruption in the shared PERMISSIONS index caused by the update() method
using delete() + create() logic.
Orphaned authorization records persist indefinitely.
Image

```
[2025-10-30 18:03:25.179] [zb-actors-2] [{actor-name=StreamProcessor-1, actor-scheduler=Broker-0, partitionId=1}] ERROR                                                                                            
    io.camunda.zeebe.broker.process - Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=GROUP, intent=DELETE, authorization={"format":"UNKNOWN","authData":"***","c
laims":"***"}}, value={"groupKey":2251799813685304,"groupId":"bug-test-3030740","name":"","description":"","entityId":"","entityType":"UNSPECIFIED"}}' without errors, but exception occurred with message 'Cannot 
invoke "io.camunda.zeebe.engine.state.authorization.Permissions.removeAuthorizationScopes(io.camunda.zeebe.protocol.record.value.PermissionType, java.util.Set)" because "permissions" is null'.                   
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.authorization.Permissions.removeAuthorizationScopes(io.camunda.zeebe.protocol.record.value.PermissionType, java.util.Set)" because "pe
rmissions" is null 
```

### Expected behavior

DELETE operations on authorizations should return HTTP 204 and successfully remove the authorization, regardless of prior PUT updates or overlapping permissions with other authorizations.

### Workaround

1. edit database

### Environment

SaaS & SM

### Version

OC Identity 8.8.x and 8.9.x

### Rootcause

1. The [update()](https://github.com/camunda/camunda/blob/74afc53a94c5feb330bdd9b6959096731df8fc02/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/authorization/DbAuthorizationState.java#L116) method calls delete() which removes ONLY the OLD permissions from the shared permissions index
2. Then it calls create() which adds ALL the NEW permissions to the permissions index
3. Problem: If the new permissions overlap with OTHER existing authorizations, the permissions index gets DUPLICATE entries
4. These duplicates corrupt the shared permissions index (key: ownerType + ownerId + resourceType)
5. Later delete operations fail because the broker detects inconsistent state → HTTP 500 errors

### Solution ideas

_No response_

### Dev -> QA handover

QA -> Dev
[test-auth-bug-variations.sh](https://github.com/user-attachments/files/23243315/test-auth-bug-variations.sh)

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by Ben-Sheppard**
## Description

The linked issue contains deeper context for the fix so I would strongly suggest reviewing there also, specifically the rootcause investigation comment [here](https://github.com/camunda/camunda/issues/40276#issuecomment-3583481909).

The core of this change is to make the deletion logic against the permissions CF more intelligent/tollerant in situations where a permission is shared across different authorizations but only one authorization is deleted (therefore the permission must remain in the CF to support the remaining authorization).

There are conversations regarding the usage patterns of these flows, for example, not allowing duplicate `ownerId+ownerType+resourceId+resourceType` keys with different permission sets (that can be then updated causing the bug) but that is a broader topic that I am not addressing with this PR :)

## Related issues

closes #40276

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/authorization/DbAuthorizationState.java [hunk 1]
```diff
@@ -126,37 +128,71 @@ public void update(final long authorizationKey, final AuthorizationRecord author
...
+    // For each authorization key get the authorization and check if it matches the persisted
+    // Authorization ResourceType and ResourceMatcher, collecting the matching authorization
+    // permissions in a set.
+    final var sharedPermissionTypes =
+        overlappingAuthorizationKeys.getAuthorizationKeys().stream()
+            .filter(overlappingKey -> overlappingKey != authorizationToDelete.getAuthorizationKey())
+            .map(
+                key -> {
+                  this.authorizationKey.wrapLong(key);
+                  return authorizationByAuthorizationKeyColumnFamily.get(this.authorizationKey);
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/authorization/DbAuthorizationState.java]: 💭 I guess this works as long as the stream is sequential. This getter returns the object defined as a field in this class. Getting it twice would mean the data of the first authorization gets overridden with the data of the second one. We could consider adding `PersistedAuthorization::new` to the call to circumvent this. But as it is now it shouldn't be an issue.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/authorization/DbAuthorizationState.java [hunk 2]
```diff
@@ -126,37 +128,71 @@ public void update(final long authorizationKey, final AuthorizationRecord author
...
+        authorizationByAuthorizationKeyColumnFamily.get(
+            this.authorizationKey, PersistedAuthorization::new);
 
-    // remove the old permissions
-    persistedAuthorization
+    ownerId.wrapString(authorizationToDelete.getOwnerId());
+    ownerType.wrapString(authorizationToDelete.getOwnerType().name());
+
+    final var overlappingAuthorizationKeys =
+        authorizationKeysByOwnerColumnFamily.get(ownerTypeAndOwnerId);
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/authorization/DbAuthorizationState.java]: 🔧 Later in this method we retrieve these same keys again to remove the one we're trying to delete. I think we can refactor this by moving that part up. Son the flow would be:

1. Retrieve all authorization keys
2. Remove the one you're currently deleting
3. For the remaining keys find overlapping permissions.

This way should also be good to remove the filter that checks if the autorization key is the one you're currently deleting, as that's already removed from the set of keys.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_8/PermissionStateCorrectionMigration.java [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+  @Override
+  public boolean needsToRun(final MigrationTaskContext context) {
+    final var processingState = context.processingState();
+
+    /*
+     * We need to correct any instances where a permission does not exist in the permissions CF but
+     * does exist in a record in the authorizations CF under permissionType. We only need to do this
+     * if we have authorizations present.
+     */
+    return !processingState.isEmpty(ZbColumnFamilies.AUTHORIZATIONS);
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_8/PermissionStateCorrectionMigration.java]: ❓ So this basically means we always run it, correct? Especially as we initialize roles with default authorizations.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/to_8_8/PermissionStateCorrectionMigrationTest.java [hunk 4]
```diff
@@ -0,0 +1,245 @@
...
+  void shouldMigrateWhenPermissionTypeIsMissing() {
+    // given
+    final var authorizationKey = 1L;
+    final var resourceId = "process-definition-1";
+    final var permissionTypes =
+        Set.of(PermissionType.CREATE_PROCESS_INSTANCE, PermissionType.DELETE_PROCESS_INSTANCE);
+    final var authorizationRecord =
+        generateAuthorizationRecord(authorizationKey, resourceId, permissionTypes);
+
+    state.create(authorizationKey, authorizationRecord);
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/migration/to_8_8/PermissionStateCorrectionMigrationTest.java]: 🔧 There's quite a bit of duplicated code in this class. Would be nice to extract the authorization in a separate method which creates the authorization in state with the provided permission types. As you still need access to some of the properties you can make the method return the record so you can still access it all.

**Review by remcowesterhoud — APPROVED** [review]
@Ben-Sheppard I don't really have blockers, but I do have some comments that could use some attention 🙂. I'll pre-approve the PR anyway, but please have a look at the comments before merging.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_8/PermissionStateCorrectionMigration.java (hunk 3 above)
Comment (Ben-Sheppard) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_8/PermissionStateCorrectionMigration.java]: Ah yes, I can make that clearer here and just use `true` for now
