### PR TITLE
fix: Trigger Exporter Flush If Flush Timer Exceded

### LINKED ISSUE #49820: Scheduled flush timer in CamundaExporter get starved under sustained load
## Summary
Under sustained load, the scheduled flush timer in `CamundaExporter` can be starved and fail to run at the expected interval. This impacts timely flushing behavior and can delay exporter progress/visibility of records.

## Context
https://github.com/camunda/camunda/pull/49780 (specifically https://github.com/camunda/camunda/pull/49780/changes/feb0dc6e03623fd4d2e811303f34a86f767354fd)

## Problem
`CamundaExporter` relies on a scheduled timer for periodic flushes. 

The scheduled timer-based flush (flushAndReschedule) runs on the same actor as record export. Under sustained load, the actor scheduler starves timer subscriptions because pollSubmittedJobs() always drains before pollSubscriptions(), so the flush callback never fires.

## Observed Impact
- Flushes do not happen at the intended cadence.
- Increased lag before data is persisted/exported.
- Potential operational confusion due to delayed visibility and accumulation.

## Expected Behavior
Flush scheduling should remain reliable even under sustained load:
- Timer should fire close to configured cadence.
- Flush should not be indefinitely postponed by continuous processing pressure.

### PR DESCRIPTION
**Pull request by yohanfernando**
## Description

This will ensure the records will be flushed whilst exporting if the since exported time is over the flush duration. This will help where the time threads are starved when due to handling large no of jobs.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes https://github.com/camunda/camunda/issues/49820

### CODE REVIEW

**Review by lilspikey — APPROVED** [review]

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java [hunk 1]
```diff
@@ -252,7 +252,7 @@ void shouldPeriodicallyFlushBasedOnConfiguration(
     spiedController.runScheduledTasks(Duration.ofSeconds(duration));
 
     // then
-    verify(spiedController, times(2)).scheduleCancellableTask(eq(Duration.ofSeconds(2)), any());
+    verify(spiedController, times(2)).scheduleCancellableTask(any(), any());
```
Comment (yohanfernando) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java]: The first invocation is always after 2 seconds, but we cannot be sure what the second one will be. So removing the time value check from this

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java [hunk 2]
```diff
@@ -139,7 +139,9 @@ public void open(final Controller controller) {
       writer = createBatchWriter();
       controller.readMetadata().ifPresent(metadata::deserialize);
       taskManager.start();
-      scheduleDelayedFlush(context.clock().millis());
+      final long now = context.clock().millis();
+      lastFlushTimestamp = now;
+      scheduleDelayedFlush(now);
```
Comment (yohanfernando) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java:144]: We are setting this so the exporter won't try to export data too eagerly. Otherwise, it would get the first record, see that gap between `now-lastFlushTimeStamp` (latter was 0) is larger than flushDelay, and immediately export

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java (hunk 1 above)
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/CamundaExporterIT.java]: we can assert it is lower or equals 2s, strictly higher than 0s :)

**Review by lilspikey — APPROVED** [review]

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java [hunk 3]
```diff
@@ -322,17 +326,21 @@ private void scheduleDelayedFlush(final long now) {
...
       if (now - lastFlushTimestamp >= flushDelayMs) {
-        flush();
+        flushed = flush();
       }
     } catch (final Exception e) {
       LOG.warn("Unexpected exception occurred on periodically flushing bulk, will retry later.", e);
     }
-    scheduleDelayedFlush(now);
+    // if not flushed, forced to use full delay, else time from "last flush + delay"
+    final var scheduleFor = !flushed ? now : lastFlushTimestamp;
```
Comment (entangled90) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java]: 🔧 this feels odd, I wonder if the problem arises because we don't update the flush timestamp when the batch size is 0. 

If we update it (not when there's an exception of course) then it should not be necessary?

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java [hunk 4]
```diff
@@ -350,6 +359,7 @@ private void flush() {
     // Update the record counters only after the flush was successful. If the synchronous flush
     // fails then the exporter will be invoked with the same record again.
     updateLastExportedPosition(lastPosition);
```
Comment (entangled90) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java:356]: 🤔  Ideally if we're exporting the position then we can also update the `lastFlushedTimestamp`?
Let's think of that `if` on the batch size as an optimization: it's like if we flushed a batch of 0 size.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java (hunk 3 above)
Comment (lilspikey) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java]: yeah - we spotted when that happens it'll just reschedule with zero delay

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java (hunk 4 above)
Comment (yohanfernando) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java:356]: Its last flushed, not exported timestamp - by flushed I presume more ES than updating the position

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java (hunk 3 above)
Comment (yohanfernando) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java]: Yeah, the only problem is we lose the regularity of what we are posting to elasticsearch. Other option I was considering was to do the delay calculations here so the logic is a bit clearer why we are doing this

Comment (entangled90) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java]: why do we lose the regularity? It should start after 1 sec after the last flushed?

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java (hunk 4 above)
Comment (entangled90) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java:356]: Yeah what I'm saying is that considering that we update the exported positions (as if we flushed for real) then it's probably ok to update the `lastFlushedTimestamp`. It's the same comment as above basically. 

That will revert the bug introduced by "optimizing" what we do when the batch size is empty

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java (hunk 3 above)
Comment (yohanfernando) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java]: Ignore this, for some reason I thought this value is used for metrics - its not and can change it

**Review by entangled90 — APPROVED** [review]
Thanks for the fix 🚀
