### PR TITLE
Lower log level of IOException during snapshot replication to warning

### LINKED ISSUE #6505: IOException: No space left on device
**Describe the bug**
Observed in logs: https://console.cloud.google.com/errors/CP-qk6vd55GyiQE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.FileDispatcherImpl.write(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at sun.nio.ch.FileChannelImpl.write(Unknown Source) ~[?:?]
	at java.nio.channels.Channels.writeFullyImpl(Unknown Source) ~[?:?]
	at java.nio.channels.Channels.writeFully(Unknown Source) ~[?:?]
	at java.nio.channels.Channels$1.write(Unknown Source) ~[?:?]
	at java.nio.file.Files.write(Unknown Source) ~[?:?]
	at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.writeReceivedSnapshotChunk(FileBasedReceivedSnapshot.java:180) ~[zeebe-snapshots-0.26.1.jar:0.26.1]
	at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.applyInternal(FileBasedReceivedSnapshot.java:120) ~[zeebe-snapshots-0.26.1.jar:0.26.1]
	at io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot.lambda$apply$0(FileBasedReceivedSnapshot.java:68) ~[zeebe-snapshots-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) ~[zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.1.jar:0.26.1]
```

</p>
</details>

<details><summary>Log</summary>
 <p>

```
Error 2021-03-05 18:12:07.828 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:08.961 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:10.101 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.336 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.364 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.369 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.372 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.403 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:11.406 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:12.652 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:14.071 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:15.524 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.961 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.967 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.972 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.975 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.977 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:16.980 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:17.428 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:18.863 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:20.116 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.239 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.246 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.250 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.252 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:21.254 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:23.237 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:23.949 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.471 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.904 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.910 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.913 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.915 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.936 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job." 
Error 2021-03-05 18:12:25.939 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.953 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:25.955 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:27.248 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:28.136 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:29.911 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:29.917 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.442 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.647 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.650 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.652 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.656 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.658 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:30.659 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:32.106 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:33.215 CET "Uncaught exception in 'io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore' in phase 'STARTED'. Continuing with next job."
Error 2021-03-05 18:12:34.031 CET "RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role"
Error 2021-03-05 18:12:37.545 CET "Raft-1 failed, marking it as unhealthy"
Info 2021-03-05 18:12:37.626 CET "Disk space available again. Current available 10878291968 bytes" 
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.26.1
 - Configuration: Camunda Cloud

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR lowers the log level of IOException occurring during snapshot replication on the follower side, both in the Atomix replication and in the push based replication. This aligns the logging to our guidelines, where most IOException may be recovered, but only repeated ones should be investigated by a human.

## Related issues

closes #6505

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java [hunk 1]
```diff
@@ -173,7 +174,17 @@ private boolean isSnapshotIdInvalid(final String snapshotId) {
...
+    try (final var channel =
+        FileChannel.open(snapshotFile, StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE)) {
+      while (contents.hasRemaining()) {
+        final var limit = Math.min(IoUtil.BLOCK_SIZE, contents.remaining());
+        channel.write(contents.limit(contents.position() + limit));
+      }
+
+      channel.force(false);
+    }
+
```
Comment (Zelldon) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:187]: Tbh. It was totally unexpected for me to have this in this PR :sweat_smile: Maybe we can create next time a different PR. Is there an issue we want to fix with that? 

> Also reduces the number of copies necessary by removing the need for an intermediary buffer used in Files#write.

Have we seen issues with that?

If you take a look at the java doc then you see that it say it closes after writing to it, so I would assume that the content needs to be written otherwise it wouldn't make sense?

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Files.html#write(java.nio.file.Path,java.lang.Iterable,java.nio.charset.Charset,java.nio.file.OpenOption...)
> public static Path write​(Path path, Iterable<? extends CharSequence> lines, Charset cs, OpenOption... options) throws IOException
> Write lines of text to a file. Each line is a char sequence and is written to the file in sequence with each line terminated by the platform's line separator, as defined by the system property line.separator. Characters are encoded into bytes using the specified charset.
> The options parameter specifies how the file is created or opened. If no options are present then this method works as if the CREATE, TRUNCATE_EXISTING, and WRITE options are present. In other words, it opens the file for writing, creating the file if it doesn't exist, or initially truncating an existing regular-file to a size of 0. The method ensures that the file is closed when all lines have been written (or an I/O error or other runtime exception is thrown). If an I/O error occurs then it may do so after the file has been created or truncated, or after some bytes have been written to the file.

The previous code looked way simpler and I would prefer to use the java utilities instead of implementing such things on our own.

File: atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java [hunk 2]
```diff
@@ -237,12 +238,21 @@ private void addSnapshotListener() {
       }
     }
 
-    boolean snapshotChunkConsumptionFailed;
+    boolean snapshotChunkConsumptionFailed = true;
     try {
       snapshotChunkConsumptionFailed = !pendingSnapshot.apply(snapshotChunk).join();
+    } catch (final IOException e) {
+      log.warn(
+          "Failed to write pending snapshot chunk {}, rolling back snapshot {}",
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:246]: Maybe we can make it a constant string (static field)

**Review by ChrisKujawa — APPROVED** [review]
Thanks :+1: 

I have some concerns regarding the write replacement and would question this, but if you think it is really necessary go for it.

**Comment by npepinpe** [comment]
Can you elaborate? Or we can zoom quickly about it

**Comment by Zelldon** [comment]
> Can you elaborate? Or we can zoom quickly about it

More then my comment https://github.com/camunda-cloud/zeebe/pull/6999#discussion_r627951186 ? Yes we can do it also via zoom.

File: atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java (hunk 2 above)
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:246]: What's the advantage here? I typically only make them constants if they're reused or if they're long enough that it's hard to read, but I also didn't give it this much thought.

**Review by ChrisKujawa — APPROVED** [review]
:+1:
