### PR TITLE
fix: prevent NPE when BoundaryEvent attachedTo is null

### LINKED ISSUE #42907: Deployment crashes with NullPointerException if BPMN BoundaryEvent attachedTo is missing or invalid
### 

### 

### 

### 

### Description

In Camunda SaaS, deploying malformed BPMN XML with a bpmn:BoundaryEvent element whose attachedTo reference is missing or invalid crashes deployment, resulting in a NullPointerException. See the stack trace below for details.

Stack trace:

```java
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.model.bpmn.instance.Activity.equals(Object)" because the return value of "io.camunda.zeebe.model.bpmn.instance.BoundaryEvent.getAttachedTo()" is null
	at io.camunda.zeebe.model.bpmn.impl.instance.ActivityImpl.lambda$getBoundaryEvents$0(ActivityImpl.java:200)
```

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.model.bpmn.instance.Activity.equals(Object)" because the return value of "io.camunda.zeebe.model.bpmn.instance.BoundaryEvent.getAttachedTo()" is null
	at io.camunda.zeebe.model.bpmn.impl.instance.ActivityImpl.lambda$getBoundaryEvents$0(ActivityImpl.java:200)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.camunda.zeebe.model.bpmn.impl.instance.ActivityImpl.getBoundaryEvents(ActivityImpl.java:201)
	at io.camunda.zeebe.model.bpmn.util.ModelUtil.getEventDefinitionsForBoundaryEvents(ModelUtil.java:105)
	at io.camunda.zeebe.model.bpmn.util.ModelUtil.verifyNoDuplicatedBoundaryEvents(ModelUtil.java:169)
	at io.camunda.zeebe.model.bpmn.validation.zeebe.ActivityValidator.validate(ActivityValidator.java:34)
	at io.camunda.zeebe.model.bpmn.validation.zeebe.ActivityValidator.validate(ActivityValidator.java:23)
	at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.lambda$visit$0(ValidationVisitor.java:51)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.visit(ValidationVisitor.java:51)
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39)
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73)
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnValidator.validate(BpmnValidator.java:43)
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$createMetadata$3(BpmnResourceTransformer.java:83)
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:417)
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.createMetadata(BpmnResourceTransformer.java:81)
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.createMetadata(DeploymentTransformer.java:168)
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:110)
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment(DeploymentCreateProcessor.java:208)
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand(DeploymentCreateProcessor.java:148)
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:33)
	at io.camunda.zeebe.engine.Engine.process(Engine.java:178)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:379)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:280)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:128)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:280)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:238)
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:84)
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:43)
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127)
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104)
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224)
```

 </p>
</details>

### Steps to reproduce

1. Deploy a BPMN process containing a boundary event with missing, empty, whitespace, or invalid attachedTo reference.
2. Observe deployment failure (NPE).

Examples:
- <bpmn:boundaryEvent id="b1" />
- <bpmn:boundaryEvent id="b2" attachedTo="" />
- <bpmn:boundaryEvent id="b3" attachedTo="   " />
- <bpmn:boundaryEvent id="b4" attachedTo="no_such_activity" />

### Current behavior

Deployment fails with NullPointerException instead of a validation error.

### Expected behavior

Deployment should be rejected with a user-facing validation/deployment error, not an NPE. Example:
- BoundaryEvent <id> is missing required attribute attachedTo
- BoundaryEvent <id> has attachedTo value <x> which cannot be resolved

### Workaround

No user workaround – only avoid by not deploying invalid XML.

### Environment

SaaS & SM

### Version

`8.8.8`

### Rootcause

Handling for BoundaryEvent attachedTo presence and resolvability is missing in validation. Downstream code assumes getAttachedTo() is non-null and fails if invalid.

### Solution ideas

Extend validation (ActivityValidator or other relevant validator) to check BoundaryEvent attachedTo presence and resolvability. Harden downstream code to prevent NPE and return structured deployment errors.

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by firedog1234**
Add a null check in ActivityImpl#getBoundaryEvents to prevent a NullPointerException when a BPMN BoundaryEvent has a missing, empty, or invalid attachedTo reference. Adds testing to verify no Exceptions are thrown in ActivityImplBoundaryEventTest.

This change prevents NullPointerExceptions from occurring.

closes #42907

### CODE REVIEW

File: zeebe/bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/validation/ZeebeBoundaryEventValidationTest.java [hunk 1]
```diff
@@ -73,7 +73,8 @@ public static Object[][] parameters() {
         singletonList(
             expect(
                 "boundary",
-                "Compensation boundary events must have a compensation association and no outgoing sequence flows"))
+                "Compensation boundary events must have a compensation association and no outgoing"
```
Comment (berkaycanbc) [inline zeebe/bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/validation/ZeebeBoundaryEventValidationTest.java]: ❌ This change is unrelated, let's remove that.

File: zeebe/bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/validation/ActivityImplBoundaryEventTest.java [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+import io.camunda.zeebe.model.bpmn.instance.BoundaryEvent;
+import io.camunda.zeebe.model.bpmn.instance.Process;
+import io.camunda.zeebe.model.bpmn.instance.TimeDuration;
+import io.camunda.zeebe.model.bpmn.instance.TimerEventDefinition;
+import org.junit.Test;
+
+public class ActivityImplBoundaryEventTest {
+
+  @Test
+  public void shouldNotThrowNPEWhenBoundaryEventHasMissingAttachedTo() {
```
Comment (berkaycanbc) [inline zeebe/bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/validation/ActivityImplBoundaryEventTest.java]: ❌ We do not need to assert cases except `no_such_activity`. Because BPMN parser will fail without even reaching to the validator.

For simplicity, let's move private method `createBoundaryEventWithAttachedTo` to the existing`ZeebeBoundaryEventValidationTest` and validate the boundary event validator fails. Dropping an example test to clarify what I mean:
```
  { 
    createBoundaryEventWithNonExistingAttachedTo(),
    singletonList(expect("boundary", "Must be attached to an activity"))
  }
```

We can remove this test class at the end.

**Review by berkaycanbc — CHANGES_REQUESTED** [review]
Thanks for the contribution @firedog1234 ! 🙌 

The change LGTM and we can further simplify testing. Please see my comments. 👀

**Review by berkaycanbc — APPROVED** [review]
Thanks for the contribution @firedog1234, LGTM 🚀!

**Comment by berkaycanbc** [comment]
@firedog1234 there are currently CI failures where we are trying to pull a dependency from a private repo. It is not working for fork PRs at the moment. I've bring this to the infrastructure team and waiting on the resolution. I'll update here once we decide on a solution.

**Comment by firedog1234** [comment]
@berkaycanbc Sounds good! Thank you for the review 🙌 .

**Comment by berkaycanbc** [comment]
@firedog1234 the issue will be fixed via ~~https://github.com/camunda/camunda/issues/46027~~ https://github.com/camunda/camunda/pull/47921 (pasted wrong issue 🙈) , I'll re-run jobs once the fix gets merged.

**Comment by berkaycanbc** [comment]
@firedog1234 can you please get changes from main? It should allow CI jobs to succeed with the license check.

**Comment by berkaycanbc** [comment]
@firedog1234 merge commits not allowed. Can you please rebase your changes onto main?

**Comment by berkaycanbc** [comment]
@firedog1234 now CI is blocked by this issue https://github.com/camunda/camunda/issues/39943 unfortunately. Sorry for the inconvenience. 🙇‍♂️ I asked team to prioritise this ASAP https://github.com/camunda/camunda/issues/39943#issuecomment-4056021996.

**Comment by firedog1234** [comment]
Thanks for the update! No worries at all. Let me know if there's anything I should update on my side.

**Comment by berkaycanbc** [comment]
Hey @firedog1234, we've created a PR https://github.com/camunda/camunda/pull/49290 to have this bug fix available to the next `8.9` release (see PR description). We plan to keep this PR open to still make your contribution directly visible, I am communicating CI fixes with the team.

**Comment by firedog1234** [comment]
Thanks, appreciate you pushing this forward and keeping my contribution visible!

**Comment by berkaycanbc** [comment]
@firedog1234 now it is merged! Looking forward to your future contributions! 🙌
