### PR TITLE
Ignore DebugLogExporter if ZEEEB_DEBUG is false

### LINKED ISSUE #5695: Allow debug exporter to be disabled by using ZEEBE_DEBUG=false
**Describe the bug**

At the moment the broker enables the debug exporter once the env variable `ZEEBE_DEBUG` exists, no matter what value it has.

https://github.com/zeebe-io/zeebe/blob/2fcaac571a474cb28801aa1c861b936db5ffe31d/broker/src/main/java/io/zeebe/broker/system/configuration/BrokerCfg.java#L63-L69

**To Reproduce**

Export `ZEEBE_DEBUG=false` and start the broker, the debug exporter is enabled.

**Expected behavior**

The debug log exporter is not enabled.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
  "exporters" : {                                                                                                                                                                                      
    "DebugLogExporter" : {                                                                                                                                                                                   "jarPath" : null,                                                                                                                                                                                
      "className" : "io.zeebe.broker.exporter.debug.DebugLogExporter",                                                                                                                                 
      "args" : {                                                                                                                                                                                               "prettyPrint" : false                                                                                                                                                                          
      },                                                                                                                                                                                                     "external" : false                                                                                                                                                                               
    }                                                                                                                                                                                                  
  },
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: develop
 - Configuration: default config with `ZEEBE_DEBUG=false` env var

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR ensures the `DebugLogExporter` is only enabled iff `ZEEBE_DEBUG==true`.

## Related issues

closes #5695 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Not sure if we should backport this to be honest. Some might consider it a bug, some might not :sweat_smile:

File: broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java [hunk 1]
```diff
@@ -240,16 +240,20 @@ public void shouldEnableDebugLogExporter() {
     environment.put(ENV_DEBUG_EXPORTER, "true");
 
     // then
-    assertDefaultDebugLogExporter(false);
+    assertDefaultDebugLogExporter();
   }
 
   @Test
-  public void shouldEnableDebugLogExporterWithPrettyOption() {
+  public void shouldDisableDebugLogExporter() {
```
Comment (pihme) [inline broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java:247]:
```suggestion
  public void shouldNotRegisterDebugLogExporter() {
```

File: broker/src/test/java/io/zeebe/broker/test/EmbeddedBrokerConfigurator.java [hunk 2]
```diff
@@ -20,7 +20,7 @@
 public final class EmbeddedBrokerConfigurator {
 
   public static final Consumer<BrokerCfg> DEBUG_EXPORTER =
-      cfg -> cfg.getExporters().put("DebugLogExporter", DebugLogExporter.defaultConfig(false));
+      cfg -> cfg.getExporters().put("DebugLogExporter", DebugLogExporter.defaultConfig());
```
Comment (pihme) [inline broker/src/test/java/io/zeebe/broker/test/EmbeddedBrokerConfigurator.java:23]: Is it deliberate that the literal is used here? (as opposed to using `DebugLogExporter.defaultConfig();`

File: broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java (hunk 1 above)
Comment (pihme) [inline broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java:247]: Is there a test case that verifies the debug exporter is not enabled if the environment variable doesn't exist?

**Review by pihme — APPROVED** [review]
Looks good.

Some suggestions for improvement.

**Comment by pihme** [comment]
I would vote to not backport it for the reason mentioned above.

File: broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java (hunk 1 above)
Comment (npepinpe) [reply broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java:247]: No, and honestly I was on the fence about the worth of this test - on one hand, the normal state is to not have the exporter. On the other hand, previous versions would include it regardless of the value, so I did want a "regression" test to ensure the behaviour was changed.

However, now that I think about it, we could simply have a test which checks there are no exporters by default (we have several other default tests, but none for exporters).

File: broker/src/test/java/io/zeebe/broker/test/EmbeddedBrokerConfigurator.java (hunk 2 above)
Comment (npepinpe) [reply broker/src/test/java/io/zeebe/broker/test/EmbeddedBrokerConfigurator.java:23]: I don't understand - do you mean the exporter ID? This is using `DebugLogExporter.defaultConfig()`.

Comment (pihme) [reply broker/src/test/java/io/zeebe/broker/test/EmbeddedBrokerConfigurator.java:23]: I mean the key in the map

Comment (npepinpe) [reply broker/src/test/java/io/zeebe/broker/test/EmbeddedBrokerConfigurator.java:23]: Ah, no I just refactored the usage - I can't really speak for the original intent, and I was unaware we had a `DebugLogExporter.defaultExporterId()`, but I can use it :+1:

File: broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java (hunk 1 above)
Comment (npepinpe) [reply broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java]: Added the test and a follow up issue: https://github.com/zeebe-io/zeebe/issues/5944

File: broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java [hunk 3]
```diff
@@ -836,13 +847,13 @@ private void assertEmbeddedGatewayEnabled(final String configFileName, final boo
     assertThat(gatewayCfg.isEnable()).isEqualTo(enabled);
   }
 
-  private void assertDefaultDebugLogExporter(final boolean prettyPrint) {
-    assertDebugLogExporter("default", prettyPrint);
-    assertDebugLogExporter("empty", prettyPrint);
+  private void assertDefaultDebugLogExporter() {
```
Comment (pihme) [inline broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java:850]:
```suggestion
  private void assertDebugLogExporterRegistered() {
```

The name is confusing. In line 262 ` public void shouldHaveNoExportersByDefault() {` we test for having no exporter by default.

Here, with the name `Default` in it we would be testing that there is an exporter registered. But the only place we call it from is not a vanilla default configuration.

**Review by pihme — CHANGES_REQUESTED** [review]
One thing remaining which is a bit confusing, in my mind, after several independent changes

File: broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java [hunk 4]
```diff
@@ -892,4 +892,15 @@ private void assertSystemClusterConfiguration(
     assertThat(cfgCluster.getClusterSize()).isEqualTo(clusterSize);
     assertThat(cfgCluster.getInitialContactPoints()).isEqualTo(initialContactPoints);
   }
+
+  private void assertWithDefaultConfigurations(final Consumer<BrokerCfg> assertions) {
+    Stream.of("default", "empty")
+        .forEach(configFileName -> assertWithDefaultConfiguration(assertions, configFileName));
+  }
+
+  private void assertWithDefaultConfiguration(
```
Comment (pihme) [inline broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java:901]: This could be renamed:
```suggestion
  private void assertWithConfiguration(
```

**Review by pihme — APPROVED** [review]
lgtm
