### PR TITLE
Persist raft members list on every member change

### LINKED ISSUE #1068: Raft allows two leaders to be elected in the same term
On Jenkins we saw a failure of the should rejoin cluster test which shows in the log that two nodes became leader in the same term.

```
[ERROR] shouldRejoinCluster(io.zeebe.raft.RaftFiveNodesTest)  Time elapsed: 35.324 s  <<< FAILURE!
java.lang.AssertionError: Failed to wait for commit of event EventInfo{position=8589934816, term=2, message='world'} with message on all rafts
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:138)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:86)
	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:58)
	at io.zeebe.raft.util.RaftClusterRule.awaitCondition(RaftClusterRule.java:277)
	at io.zeebe.raft.util.RaftClusterRule.awaitEventCommittedOnAll(RaftClusterRule.java:166)
	at io.zeebe.raft.RaftFiveNodesTest.shouldRejoinCluster(RaftFiveNodesTest.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

[surefire-output.log](https://github.com/zeebe-io/zeebe/files/2213774/surefire-output.log)

### PR DESCRIPTION
**Pull request by menski**
closes #1068

### CODE REVIEW

File: raft/src/main/java/io/zeebe/raft/RaftMembers.java [hunk 1]
```diff
@@ -100,7 +100,7 @@ public RaftMember removeMember(final int nodeId) {
     if (member != null) {
       members.remove(member);
       memberLookup.remove(nodeId, member);
-      persistentStorage.removeMember(nodeId);
+      persistentStorage.removeMember(nodeId).save();
```
Comment (Zelldon) [inline raft/src/main/java/io/zeebe/raft/RaftMembers.java]: We can then remove the save in Raft#memberLeaves right?

**Review by ChrisKujawa — APPROVED** [review]

File: raft/src/main/java/io/zeebe/raft/RaftMembers.java (hunk 1 above)
Comment (menski) [reply raft/src/main/java/io/zeebe/raft/RaftMembers.java]: Yes, sorry wasn't aware that we called save there.
