### PR TITLE
fix(docker): data and logs mount for unprivileged user

### LINKED ISSUE #11866: Running the zeebe container with the unprivileged user `zeebe` may fail due to lack of write permissions
**Describe the bug**

As of now the log and data folder ownership setup may not allow to run the zeebe container with the unprivileged user `zeebe` that is already setup in Dockerfile due to these directories being owned by the root user:
```
root@9f6bb138376a:/usr/local/zeebe# ls -al
...
drwxrwxr-x 3 root  root  4096 Feb 23 17:26 data
drwxr-xr-x 2 zeebe root 12288 Feb 23 07:59 lib
drwxr-xr-x 2 root  root  4096 Feb 23 17:26 logs
```

whether the issue occurs depends on whether these directories are mounted to volumes and how the permissions for these volumes are setup.  This relates to this [docker issue](https://github.com/moby/moby/issues/2259), which indicates that at best volumes folders should be pre-created with the desired ownership.

Depending on the setup the zeebe user may lack permission to e.g. write to the logs directory:
```
Unable to create file /usr/local/zeebe/logs/zeebe.log java.io.IOException: Could not create directory /usr/local/zeebe/logs
```

Relates to https://jira.camunda.com/browse/SUPPORT-15854

### PR DESCRIPTION
**Pull request by megglos**
## Description

This change fixes permission issues if zeebe would be run with the `zeebe` user, a test to verify this works is also added.

Additionally the log directory is marked as a mount point in the Dockerfile now, this will instruct docker to always create volumes for it and thus allow us to verify mounting this dir works fine, without potential permission issues when using the `zeebe` user.

Note this does not make the `zeebe` user the default user which would be a breaking change for existing setups where volume data might be owned by root. I will handle this separately.

Ownership before this change:
```
root@9f6bb138376a:/usr/local/zeebe# ls -al
...
drwxrwxr-x 3 root  root  4096 Feb 23 17:26 data
drwxr-xr-x 2 zeebe root 12288 Feb 23 07:59 lib
drwxr-xr-x 2 root  root  4096 Feb 23 17:26 logs
```
after
```
root@753497ed6a06:/usr/local/zeebe# ls -al
...
drwxrwxr-x 3 zeebe root  4096 Feb 23 17:27 data
drwxr-xr-x 2 zeebe root 12288 Feb 23 07:59 lib
drwxrwxr-x 2 zeebe root  4096 Feb 23 17:27 logs
...
```

## Related issues

relates to #11784
closes #11866

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/startup/AbstractRootlessImageTest.java [hunk 1]
```diff
@@ -11,52 +11,34 @@
...
- * by processes in the image must be owned by the root group and be read/writable by that group.
- * Files to be executed must also have "group" execute permissions.
- *
- * <p>You can read more about UIDs/GIDs <a
- * href="https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids">here</a>.
- */
-@Testcontainers
-final class RootlessImageTest {
+/** Tests a small deployment of one standalone broker and gateway, running "rootless". */
+abstract class AbstractRootlessImageTest {
```
Comment (oleschoenburg) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/startup/AbstractRootlessImageTest.java:27]: :upside_down_face: Just a personal opinion: using an abstract class for this feels very heavy handed. I think this could just be a parameterized tests if the single test case just starts the container directly instead of using class fields and the `@Container` annotation.

**Review by lenaschoenburg — APPROVED** [review]

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/startup/AbstractRootlessImageTest.java (hunk 1 above)
Comment (npepinpe) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/startup/AbstractRootlessImageTest.java:27]: Agreed, abstract test classes are a gateway to the dark side :smile:

**Comment by npepinpe** [comment]
So in OpenShift this works because volume mounts will be mounted using the user assigned, which should also include the logs. I kind of assumed this would be the case on most Kubernetes platform. I can attest this work for a fact as we tested it once on GKE as well, but still always specified the right permissions for all volumes and volume mounts.

I would have to re-read the issue to understand what the problem is again, but it seems that Ole is on this anyway so I doubt we need 2 people :smile:

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/startup/ZeebeUserRootlessImageTest.java [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+
+import org.testcontainers.junit.jupiter.Testcontainers;
+
+/** Tests a deployment running with user "zeebe" instead of root. */
+@Testcontainers
+final class ZeebeUserRootlessImageTest extends AbstractRootlessImageTest {
+
+  @Override
+  public String getUser() {
+    return "zeebe";
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/startup/ZeebeUserRootlessImageTest.java:18]: :thought_balloon: FYI, putting "1000:0" works. In fact, putting anything as long as you are part of the root group, works.

This is the standard on OpenShift (as described [here](https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids#uids-and-guis-in-action-container-perspective)).

:question: Do you know what's the default for Kubernetes in general? Or do we also want to support this out of the box for plain Docker users?

**Review by npepinpe — CHANGES_REQUESTED** [review]
:x: The tests could easily be parameterized. Let me know if you need help, or just an example.

:question: I was also wondering if we should maybe actually test with [volumes](https://github.com/camunda-community-hub/zeebe-test-container#volumes-and-data)?

:information_source: I also tried deploying the latest image as a normal pod in our cluster, with the following:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: camunda/zeebe
    securityContext:
      runAsUser: 1000
```

This ran without problem, and the logs folder is given the `zeebe` user group. I did not try mounting a volume for the logs though, but I imagine if you mounted it with the right permissions it would work.

So I guess the main issue is with Docker by itself, which creates some random group apparently for the container user unless you specify one.

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/startup/ZeebeUserRootlessImageTest.java (hunk 2 above)
Comment (megglos) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/startup/ZeebeUserRootlessImageTest.java:18]: > Or do we also want to support this out of the box for plain Docker users?
exactly, this test is motivated by plain docker security recommendations to make use of an unpriviliged user, e.g. [here](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-2-set-a-user), which don't cover group assignment. Thus I deliberately omitted the group assignment.

That's why I wanted to keep it simple by making sure just using the zeebe user is enough to run zeebe, regardless of group assignment. Also if we go for making the zeebe user the default from the dockerfile we wouldn't need to bother about group assignment.

> This is the standard on OpenShift (as described [here](https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids#uids-and-guis-in-action-container-perspective)).
To me the role of the group id `0` is a bit confusing 😅 , e.g. dist docs like the [one from debian](https://wiki.debian.org/SystemGroups) indicate this group is not intended to be used by others but the root user which makes me wonder if the handling by OpenShift is a general one to rely on.
I can also imagine asking customers to assign the root group to the users they run the image with may raise confusion as well.

**Comment by megglos** [comment]
> ❌ The tests could easily be parameterized. Let me know if you need help, or just an example.
done

> ❓ I was also wondering if we should maybe actually test with [volumes](https://github.com/camunda-community-hub/zeebe-test-container#volumes-and-data)?
By flagging the data and logs path as volumes in the Dockerfile, docker will already create volumes whenever the image is run, [see the reference](https://docs.docker.com/engine/reference/builder/#volume).

**Review by npepinpe — APPROVED** [review]
:rocket:
