### PR TITLE
Prevent exceeding max message size on job batch activate commands

### LINKED ISSUE #12007: ExceededBatchRecordSizeException: Can't append entry
**Describe the bug**

```
io.camunda.zeebe.stream.api.records.ExceededBatchRecordSizeException: Can't append entry: 
'RecordBatchEntry[recordMetadata=RecordMetadata{recordType=EVENT, valueType=JOB_BATCH, intent=ACTIVATED}, 
key=4503599628576248, sourceIndex=-1, unifiedRecordValue=

"maxJobsToActivate":13822
```

Partition is unhealthy. 
```
Broker-1-StreamProcessor-2{status=UNHEALTHY, issue=HealthIssue[message=not making progress, 

Broker-1-StreamProcessor-1{status=UNHEALTHY, issue=HealthIssue[message=actor appears blocked, 
```
But StreamProcessor is not stuck. Eventhough there is high backpressure, it is not 100%. Meaning that StreamProcessor is accepting new commands and processing them. But it seems no job can be activated.

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

[Link to logs](https://console.cloud.google.com/errors/detail/CIeFtI729PW2Cw;service=zeebe;time=P7D?project=camunda-cloud-240911)

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.stream.api.records.ExceededBatchRecordSizeException: Can't append entry: 'RecordBatchEntry[recordMetadata=RecordMetadata{recordType=EVENT, valueType=JOB_BATCH, intent=ACTIVATED}, key=4503599628576248, sourceIndex=-1, unifiedRecordValue={"type":"***","worker":"***","timeout":300000,"maxJobsToActivate":13822,"jobKeys":[4503599628420203,4503599628420225,4503599628420247,4503599628420269,4503599628420291,4503599628420314,4503599628420318,4503599628420340,4503599628420344,4503599628420348,4503599628420352,4503599628420356,4503599628420360,4503599628420364,4503599628420446,4503599628420450,4503599628420454,4503599628420458,4503599628420462,4503599628420466,4503599628420516,4503599628420520,4503599628420524,4503599628420528,4503599628420532,4503599628420629,4503599628420633,4503599628420650,4503599628420702,4503599628420706,4503599628420716,4503599628420726,4503599628420730,4503599628420734,4503599628420770,4503599628420790,4503599628420794,4503599628420810,4503599628420818,4503599628420822,4503599628420834,4503599628420842,4503599...' with size: 4194277 this would exceed the maximum batch size. [ currentBatchEntryCount: 0, currentBatchSize: 0]

at io.camunda.zeebe.stream.impl.records.RecordBatch.appendRecord ( [io/camunda.zeebe.stream.impl.records/RecordBatch.java:67](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.stream.impl.records%2FRecordBatch.java&line=67&project=camunda-cloud-240911) )
at io.camunda.zeebe.stream.impl.BufferedProcessingResultBuilder.appendRecordReturnEither ( [io/camunda.zeebe.stream.impl/BufferedProcessingResultBuilder.java:62](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.stream.impl%2FBufferedProcessingResultBuilder.java&line=62&project=camunda-cloud-240911) )
at io.camunda.zeebe.stream.api.ProcessingResultBuilder.appendRecord ( [io/camunda.zeebe.stream.api/ProcessingResultBuilder.java:38](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.stream.api%2FProcessingResultBuilder.java&line=38&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent ( [io/camunda.zeebe.engine.processing.streamprocessor.writers/ResultBuilderBackedEventApplyingStateWriter.java:40](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.streamprocessor.writers%2FResultBuilderBackedEventApplyingStateWriter.java&line=40&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.job.JobBatchActivateProcessor.activateJobBatch ( [io/camunda.zeebe.engine.processing.job/JobBatchActivateProcessor.java:125](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.job%2FJobBatchActivateProcessor.java&line=125&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.job.JobBatchActivateProcessor.activateJobs ( [io/camunda.zeebe.engine.processing.job/JobBatchActivateProcessor.java:86](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.job%2FJobBatchActivateProcessor.java&line=86&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.job.JobBatchActivateProcessor.processRecord ( [io/camunda.zeebe.engine.processing.job/JobBatchActivateProcessor.java:63](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.job%2FJobBatchActivateProcessor.java&line=63&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.Engine.process ( [io/camunda.zeebe.engine/Engine.java:127](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine%2FEngine.java&line=127&project=camunda-cloud-240911) )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing ( [io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:340](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.stream.impl%2FProcessingStateMachine.java&line=340&project=camunda-cloud-240911) )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2 ( [io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:263](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.stream.impl%2FProcessingStateMachine.java&line=263&project=camunda-cloud-240911) )
at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run ( [io/camunda.zeebe.db.impl.rocksdb.transaction/ZeebeTransaction.java:84](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.db.impl.rocksdb.transaction%2FZeebeTransaction.java&line=84&project=camunda-cloud-240911) )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand ( [io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:263](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.stream.impl%2FProcessingStateMachine.java&line=263&project=camunda-cloud-240911) )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord ( [io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:222](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.stream.impl%2FProcessingStateMachine.java&line=222&project=camunda-cloud-240911) )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord ( [io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:198](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.stream.impl%2FProcessingStateMachine.java&line=198&project=camunda-cloud-240911) )
```

</p>
</details>

**Environment:**

- Zeebe Version: 8.2.0-alpha5

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

We've been seeing errors where we exceed the max message size upon a job batch activate command. This occurs when there is too many jobs in the command.

In this code we tried to be very clever and calculated the exact size the record could be before it would reach its limit. While this is nice, because it would allow for the largest batches, it is also very fault-sensitive. If anything changes in any of the records it would break the calculation, which will most definitely be missed.

With this commit I have given the expected event length a buffer of 8KB. This is the same buffer we use for PI batch activate/terminate.

## Related issues

closes #12007 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java [hunk 1]
```diff
@@ -86,10 +86,9 @@ Either<TooLargeJob, Integer> collectJobs(final TypedRecord<JobBatchRecord> recor
 
           // the expected length is based on the current record's length plus the length of the job
           // record we would add to the batch, the number of bytes taken by the additional job key,
-          // as well as one byte required per job key for its type header. if we ever add more, this
-          // should be updated accordingly.
+          // as well as an 8 KB buffer.
           final var jobRecordLength = jobRecord.getLength();
-          final var expectedEventLength = record.getLength() + jobRecordLength + Long.BYTES + 1;
+          final var expectedEventLength = record.getLength() + jobRecordLength + (1024 * 8);
```
Comment (nicpuppa) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java:91]: 🔧  We can put `1024 * 8` in a variable to avoid replication in the tests. Or even better, we can move that into the `EngineConfiguration` file and use it where needed

**Review by nicpuppa — APPROVED** [review]
LGTM! 🚀 

Thank you for applying my suggestion! 💪 🥳

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors cancel

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
Lame, dependency issues. Guess I'm not using `DataSize` after all.

**Comment by remcowesterhoud** [comment]
Sorry for the spam to whoever is notified by this 😄 

bors merge
