### PR TITLE
fix(broker): handle failures during transitions

### LINKED ISSUE #5117: Failed to install follower partition: Actor is closed
**Describe the bug**
We came across this error in our production cluster (attached stacktrace below). This may lead to a bigger issue ([quoted](https://github.com/zeebe-io/zeebe/issues/5063#issuecomment-669111936)):
>causes us to be unable to install the follower service, which means you will not be getting snapshots and may eventually run out of disk space.

Currently, the standalone gateway is showing a skewed network topology:
```
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.23.4
Brokers:
  Broker 0 - prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26501
    Version: 0.23.4
    Partition 1 : Leader
    Partition 2 : Follower
    Partition 3 : Leader
  Broker 1 - prod-zeebe-zeebe-broker-1.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26501
    Version: 0.23.4
    Partition 1 : Follower
    Partition 2 : Leader
    Partition 3 : Follower
  Broker 2 - prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26501
    Version: 0.23.4
    Partition 1 : Follower
    Partition 3 : Follower
```
However Grafana shows this:
Screenshot 2020-08-05 at 5 22 16 PM

**To Reproduce**
Nothing as such. It just happened randomly. Attached stacktrace below if that can help.

**Expected behavior**
Installation of follower service should happen successfully in case of partition role change.

**Log/Stacktrace**
Attached full stacktrace since the start of the issue.
<details><summary>Full Stacktrace</summary>
 <p>

```
2020-08-04 23:39:10.844 [Broker-2-SnapshotDirector-2] [Broker-2-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/50514399-209-1596584349885/028389.sst
2020-08-04 23:41:08.498 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] DEBUG io.zeebe.broker.system - Removing leader partition services for partition PartitionId{id=2, group=raft-partition}
2020-08-04 23:41:08.498 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] DEBUG io.zeebe.broker.system - Closing Broker-2-Exporter-2
2020-08-04 23:41:08.498 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] DEBUG io.zeebe.broker.system - Partition role transitioning from LEADER to FOLLOWER
2020-08-04 23:41:08.498 [] [raft-server-2-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 11506225119720.
java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1422) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1407) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.23.4.jar:0.23.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-08-04 23:41:08.498 [] [raft-server-2-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 11506225119920.
java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1422) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1407) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.23.4.jar:0.23.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-08-04 23:41:08.499 [Broker-2-LogAppender-2] [Broker-2-zb-actors-0] ERROR io.zeebe.logstreams - Actor Broker-2-LogAppender-2 failed in phase STARTED.
java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1422) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1407) ~[atomix-cluster-0.23.4.jar:0.23.4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-0.23.4.jar:0.23.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
2020-08-04 23:41:08.500 [Broker-2-LogStream-2] [Broker-2-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream logstream-raft-partition-partition-2
2020-08-04 23:41:08.500 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-0] ERROR io.zeebe.broker.system - logstream-raft-partition-partition-2 failed, marking it as unhealthy
2020-08-04 23:41:08.500 [logstream-raft-partition-partition-2-write-buffer] [Broker-2-zb-actors-2] DEBUG io.zeebe.dispatcher - Dispatcher closed
2020-08-04 23:41:08.500 [Broker-2-LogStream-2] [Broker-2-zb-actors-2] INFO  io.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-2 close 3 readers
2020-08-04 23:41:08.501 [Broker-2-LogStream-2] [Broker-2-zb-actors-2] INFO  io.zeebe.logstreams - Close log storage with name logstream-raft-partition-partition-2
2020-08-04 23:41:08.501 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {Raft-2=HEALTHY, Broker-2-StreamProcessor-2=HEALTHY, logstream-raft-partition-partition-2=UNHEALTHY}
2020-08-04 23:41:08.501 [Broker-2-HealthCheckService] [Broker-2-zb-actors-0] ERROR io.zeebe.broker.system - Partition-2 failed, marking it as unhealthy
2020-08-04 23:41:09.607 [Broker-2-Exporter-2] [Broker-2-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Closed exporter director 'Broker-2-Exporter-2'.
2020-08-04 23:41:09.607 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Closed Broker-2-Exporter-2 successfully
2020-08-04 23:41:09.607 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Broker-2-SnapshotDirector-2
2020-08-04 23:41:09.608 [Broker-2-SnapshotDirector-2] [Broker-2-zb-fs-workers-1] ERROR io.zeebe.logstreams.snapshot - Unexpected error on retrieving commit position
2020-08-04 23:41:09.608 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] DEBUG io.zeebe.broker.system - Unexpected exception on closing Broker-2-SnapshotDirector-2
java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:166) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:95) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:135) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.getCommitPositionAsync(LogStreamImpl.java:105) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$closeAsync$1(AsyncSnapshotDirector.java:108) ~[zeebe-workflow-engine-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
2020-08-04 23:41:09.609 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] ERROR io.zeebe.broker.system - Unexpected exception on removing leader partition!
java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:166) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:95) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:135) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.getCommitPositionAsync(LogStreamImpl.java:105) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$closeAsync$1(AsyncSnapshotDirector.java:108) ~[zeebe-workflow-engine-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
2020-08-04 23:41:09.609 [Broker-2-ZeebePartition-2] [Broker-2-zb-actors-2] ERROR io.zeebe.broker.system - Failed to install follower partition 2
java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:166) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:95) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:135) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.logstreams.impl.log.LogStreamImpl.getCommitPositionAsync(LogStreamImpl.java:105) ~[zeebe-logstreams-0.23.4.jar:0.23.4]
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$closeAsync$1(AsyncSnapshotDirector.java:108) ~[zeebe-workflow-engine-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
2020-08-04 23:41:14.059 [Broker-2-TopologyManager] [Broker-2-zb-actors-1] DEBUG io.zeebe.broker.clustering - Received metadata change for 1, partitions {1=FOLLOWER, 2=LEADER, 3=FOLLOWER} terms {2=216}
```

</p>
</details>

**Environment:**
 - Zeebe Version: `0.23.4`
<details><summary>Configuration</summary>
 <p>

```
Starting broker 2 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 26501,
      "advertisedHost" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
      "advertisedPort" : 26501,
      "advertisedAddress" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26501",
      "address" : "0.0.0.0:26501"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 26502,
      "advertisedHost" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
      "advertisedPort" : 26502,
      "advertisedAddress" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502",
      "address" : "0.0.0.0:26502"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 9600,
      "advertisedHost" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local",
      "advertisedPort" : 9600,
      "advertisedAddress" : "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:9600",
      "address" : "0.0.0.0:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "prod-zeebe-zeebe-broker-0.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502", "prod-zeebe-zeebe-broker-1.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502", "prod-zeebe-zeebe-broker-2.prod-zeebe-zeebe-broker.prod.svc.cluster.local:26502" ],
    "partitionIds" : [ 1, 2, 3 ],
    "nodeId" : 2,
    "partitionsCount" : 3,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster",
    "gossipFailureTimeout" : 10000,
    "gossipInterval" : 250,
    "gossipProbeInterval" : 1000
  },
  "threads" : {
    "cpuThreadCount" : 3,
    "ioThreadCount" : 3
  },
  "data" : {
    "directories" : [ "/usr/local/zeebe/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT15M",
    "logIndexDensity" : 100,
    "logSegmentSizeInBytes" : 536870912,
    "atomixStorageLevel" : "DISK"
  },
  "exporters" : {
    "hazelcast" : {
      "jarPath" : "/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar",
      "className" : "io.zeebe.hazelcast.exporter.HazelcastExporter",
      "args" : {
        "port" : 5701,
        "enabledValueTypes" : "DEPLOYMENT,JOB,WORKFLOW_INSTANCE,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION",
        "enabledRecordTypes" : "EVENT",
        "name" : "zeebe",
        "capacity" : 10000,
        "timeToLiveInSeconds" : 100,
        "format" : "protobuf"
      },
      "external" : true
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS"
  },
  "stepTimeout" : "PT5M"
}
```

</p>
</details>

### LINKED ISSUE #5291: Transition from leader to follower sometime fails
**Describe the bug**
In one cluster we observed the following:

Zeebe-0 was the leader for partition 1. Then there was a new leader. Zeebe-0 closes its leader services. Partition is them marked as unhealthy and it remains unhealthy for ever. It seems then no follower services are installed. As a result it didnot receive any new snapshots, but was still replicating log. So it could not compact the logs and eventually the node went out of disk space.

**Environment:**
 - Zeebe Version: stable/0.23

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

We've seen nodes get stuck in invalid states because of errors during role transitions. This PR makes improves handling of these failures by:
* ensuring that all steps are closed even if one of them fails (nothing is gained by leaving some pieces of state open)
* partition listeners are notified if a transition fails or if the partition transitions to inactive (we want to close things like the commandApiService even if the follower wasn't successfully installed) 
* if an error occurs during the closing part of a transition, we still try to install the new partition (some closing failures are expected in which case we shouldn't prevent the install)
* if an error occurs while trying to install the leader partition, we step down to follower
* if an error occurs while trying to install the follower partition, we become inactive

## Related issues

closes #5117
closes #5291

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [x] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/zeebe/broker/system/partitions/impl/PartitionTransitionImpl.java [hunk 1]
```diff
@@ -132,26 +143,22 @@ private void stepByStepClosing(
 
     final ActorFuture<Void> closeFuture = step.close(context);
     closeFuture.onComplete(
-        (v, t) -> {
-          if (t == null) {
+        (v, newThrowable) -> {
```
Comment (deepthidevaki) [inline broker/src/main/java/io/zeebe/broker/system/partitions/impl/PartitionTransitionImpl.java:146]:
```suggestion
        (v, closeFailedError) -> {
```

File: protocol/src/main/resources/protocol.xml [hunk 2]
```diff
@@ -55,6 +55,7 @@
     <enum name="PartitionRole" encodingType="uint8">
       <validValue name="LEADER">0</validValue>
       <validValue name="FOLLOWER">1</validValue>
+      <validValue name="INACTIVE">2</validValue>
```
Comment (deepthidevaki) [inline protocol/src/main/resources/protocol.xml:58]: How does this work on the gateway side? Would it work during rolling upgrade, gateway and broker is on different versions?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 3]
```diff
@@ -272,11 +272,17 @@ public void onRecovered() {
...
     zeebePartitionHealth.setServicesInstalled(false);
+    context
+        .getPartitionListeners()
+        .forEach(l -> l.onBecomingInactive(context.getPartitionId(), term));
+
     if (context.getRaftPartition().getRole() == Role.LEADER) {
       LOG.info("Unexpected failures occurred when installing leader services, stepping down");
       context.getRaftPartition().stepDown();
+    } else {
+      context.getRaftPartition().leave();
```
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:285]: We should either "stop" the raft server or transition to "Role.INACTIVE". Transitioning to Inactive will be safer, because several other modules might expect a running raft server.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks @MiguelPires . Overall looks good. But we should reconsider what happens when a follower install fails.

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (MiguelPires) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:285]: That's what `leave()` does:
https://github.com/zeebe-io/zeebe/blob/ba3400c7ee0a6f910a3b1cfef75fb668f7cecca0/atomix/cluster/src/main/java/io/atomix/raft/cluster/impl/RaftClusterContext.java#L262
`leave()` transitions to INACTIVE. The reaction to the role transition is to leave the cluster. Which makes sense since it's not going to take part in consensus. We can shutdown the broker so it can be restarted as soon as possible, but that will impact other partitions

[the remark this answers is not in the document]
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:285]: `leave()` also leaves the replication group which means that the other nodes would stop communicating with this - we don't want to do that because this node is still part of the replication group, but it is only in a error state.. What we really need is only transition to Inactive which means it is still part of the replication group, but doesn't actively do anything. It acts as if it is unreachable.

File: protocol/src/main/resources/protocol.xml (hunk 2 above)
Comment (MiguelPires) [reply protocol/src/main/resources/protocol.xml:58]: A previous version would map the value to SBE_UNKNOWN but it shouldn't break

File: atomix/cluster/src/main/java/io/atomix/raft/impl/DefaultRaftServer.java [hunk 4]
```diff
@@ -149,6 +149,17 @@ public void removeFailureListener(final Runnable failureListener) {
     return future;
   }
 
+  public CompletableFuture<Void> goInactive() {
```
Comment (deepthidevaki) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/DefaultRaftServer.java:152]: Add `@Override`

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 5]
```diff
@@ -272,11 +272,17 @@ public void onRecovered() {
...
     zeebePartitionHealth.setServicesInstalled(false);
+    context
+        .getPartitionListeners()
+        .forEach(l -> l.onBecomingInactive(context.getPartitionId(), term));
+
     if (context.getRaftPartition().getRole() == Role.LEADER) {
       LOG.info("Unexpected failures occurred when installing leader services, stepping down");
       context.getRaftPartition().stepDown();
+    } else {
+      context.getRaftPartition().goInactive();
```
Comment (deepthidevaki) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:285]: May be also add a log here?

File: broker/src/test/java/io/zeebe/broker/system/partitions/ZeebePartitionTest.java [hunk 6]
```diff
@@ -100,6 +107,76 @@ public void shouldCallOnRecoveredOnAddFailureListenerAndHealthy() {
...
+        .then(
+            invocation -> {
+              partition.onNewRole(Role.FOLLOWER, 2);
+              return CompletableFuture.completedFuture(null);
+            });
+
+    // when
+    partition.onNewRole(Role.LEADER, 1);
+    schedulerRule.workUntilDone();
+    assertThatNoException().isThrownBy(() -> latch.await(30, TimeUnit.SECONDS));
```
Comment (deepthidevaki) [inline broker/src/test/java/io/zeebe/broker/system/partitions/ZeebePartitionTest.java:136]:
```suggestion
    assertThat(latch.await(30, TimeUnit.SECONDS)).isTrue();
```

File: broker/src/test/java/io/zeebe/broker/system/partitions/ZeebePartitionTest.java [hunk 7]
```diff
@@ -100,6 +107,76 @@ public void shouldCallOnRecoveredOnAddFailureListenerAndHealthy() {
...
+        .then(
+            invocation -> {
+              partition.onNewRole(Role.INACTIVE, 2);
+              return CompletableFuture.completedFuture(null);
+            });
+
+    // when
+    partition.onNewRole(Role.FOLLOWER, 1);
+    schedulerRule.workUntilDone();
+    assertThatNoException().isThrownBy(() -> latch.await(30, TimeUnit.SECONDS));
```
Comment (deepthidevaki) [inline broker/src/test/java/io/zeebe/broker/system/partitions/ZeebePartitionTest.java:171]:
```suggestion
    assertThat(latch.await(30, TimeUnit.SECONDS)).isTrue();
```

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Looks good. Only some minor comments. :+1:

**Comment by MiguelPires** [comment]
Thanks for the review @deepthidevaki. I addressed your comments in the latest review

**Review by deepthidevaki — APPROVED** [review]
:tada:
