### PR TITLE
Validate user input before registering a worker to the job stream

### LINKED ISSUE #13465: Validate user input before registering a worker to the job stream
**Description**

We need to validate user input before registering workers to the job stream. That will provide two main benefits:
- We will be able to return better validation error messages to the client
- Without validation, worker can register to the stream with a wrong job type and later no jobs will be pushed. We will prevent that with validation.

**Expected validation checks:**
- type is blank (empty string, null)
- ~worker is blank (empty string, null)~ this is going to be optional as we do in polling mechanism
- timeout less than 1

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

* Update gateway.proto to indicate validation changes
* Add error handler to ClientStreamAdapter and reject call with INVALID_ARGUMENT when job type is empty or timeout is less than 1
* Add tests to cover introduced validation cases

## Related issues

closes #13465 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java [hunk 1]
```diff
@@ -33,6 +35,22 @@ public ClientStreamAdapter(final ClientStreamer<JobActivationProperties> jobStre
   public void handle(
       final StreamActivatedJobsRequest request,
       final ServerCallStreamObserver<ActivatedJob> responseObserver) {
+    if (request.getType().isEmpty()) {
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java:38]: :wrench: Soft suggestion, but you could rewrite them as [guard clauses](https://en.wikipedia.org/wiki/Guard_(computer_science)) instead of if/else if/else, e.g.

```suggestion
if (request.getType().isBlank()) {
  handleError(responseObserver, "type", "present", "blank");
  return;
}

if (request.getTimeout() < 1) {
  handleError(responseObserver, "timeout", "greater than zero", Long.toString(request.getTimeout()));
  return;
}

handleInternal(request, responseObserver);
```

Pros of guards is you quickly spot the "invalid" cases. Cons can be increased cyclomatic complexity, but in this case it's pretty much the same.

Since the cases are still pretty minimal, I would say it's up to you, even if I have a slight preference toward guards :upside_down_face:

Comment (npepinpe) [reply gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java:38]: Oh, also, `isBlank` might be more interesting here than `isEmpty` - it will also match strings which are purely whitespaces. But I don't know if we want to enforce this to be honest, so I'd leave that up to your team. Is "     " a valid job type? :smile:

Comment (npepinpe) [reply gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java:38]: And you can use `Long.toString` to convert the timeout instead of `String.format`, although you don't really need it. See the comment below.

File: gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java [hunk 2]
```diff
@@ -46,6 +64,17 @@ public void handle(
     responseObserver.setOnCancelHandler(removeJobStream);
   }
 
+  private void handleError(
+      final ServerCallStreamObserver<ActivatedJob> responseObserver,
+      final String field,
+      final String expectation,
+      final String actual) {
```
Comment (npepinpe) [inline gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java:71]: :wrench: You can make `actual` an `Object`. For objects (e.g. `String`) this will change nothing, but for primitives, this means we're now boxing them (e.g. `long` becomes `Long`). This can sometimes be a performance thing, but since we do this only in the error case here, I think simplicity is easier.

If you do, then you don't need to convert the parameters above (e.g. `String.format("'%d'", request.getTimeout())`. You can just pass `request.getTimeout()`, and `request.getType()`.

When it formats `%s` with an object, it'll just call its `toString` method :+1: 

By the way, since Java 16 (? maybe earlier, can't remember), you can do:

```java
    final var format = "Expected to stream activated jobs with %s to be %s, but it was %s";
    final String errorMessage = format.formatted(field, expectation, actual);
    responseObserver.onError(
        new StatusRuntimeException(Status.INVALID_ARGUMENT.withDescription(errorMessage)));
```

File: gateway/src/test/java/io/camunda/zeebe/gateway/api/job/StreamActivatedJobsTest.java [hunk 3]
```diff
@@ -114,25 +114,78 @@ public void shouldRemoveStreamOnCancel() {
     final List<String> fetchVariables = List.of("foo");
     final TestStreamObserver streamObserver =
         getStreamActivatedJobsRequest(jobType, WORKER, timeout, fetchVariables);
-    assertThat(jobStreamer.containsStreamFor(jobType)).isTrue();
 
     // when
-    streamObserver.cancel();
```
Comment (npepinpe) [inline gateway/src/test/java/io/camunda/zeebe/gateway/api/job/StreamActivatedJobsTest.java:120]: :x: Doesn't this make the test pointless? :thinking: I'm confused

**Review by npepinpe — APPROVED** [review]
:rocket: 

Please address all comments, but I'm pre-approving because I don't think we'll need another review :+1:

File: gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java (hunk 1 above)
Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java:38]: I also prefer guard clauses but I hesitate to use them with empty returns. Since you also prefer them, let's change it. 👍

File: gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java (hunk 2 above)
Comment (berkaycanbc) [reply gateway/src/main/java/io/camunda/zeebe/gateway/impl/stream/ClientStreamAdapter.java:71]: Wouldn't it reduce the readability of the code if we pass `Object`? I think, it is too much of optimisation that we will start to sacrifice readability. WDYT?

**Comment by berkaycanbc** [comment]
bors merge
