### PR TITLE
Replace usages of IoUtil.ensureDirectoryExists

### LINKED ISSUE #7311: Use FileUtil instead of IOUtil for file operations
Found following error in one cluster:

```
 java.lang.IllegalArgumentException: could not create Raft data directory directory: /usr/local/zeebe/data/raft-partition

        at org.agrona.IoUtil.ensureDirectoryExists (IoUtil.java:241)
        at io.camunda.zeebe.broker.clustering.atomix.AtomixFactory.createRaftPartitionGroup (AtomixFactory.java:98)
        at io.camunda.zeebe.broker.clustering.atomix.AtomixFactory.fromConfiguration (AtomixFactory.java:87)
        at io.camunda.zeebe.broker.Broker.atomixCreateStep (Broker.java:260)
        at io.camunda.zeebe.broker.Broker.lambda$initStart$0 (Broker.java:209)
        at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2 (StartProcess.java:63)
        at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration (StartProcess.java:92)
        at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep (StartProcess.java:61)
        at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration (StartProcess.java:92)
        at io.camunda.zeebe.broker.bootstrap.StartProcess.start (StartProcess.java:46)
        at io.camunda.zeebe.broker.Broker.internalStart (Broker.java:180)
        at io.camunda.zeebe.util.LogUtil.doWithMDC (LogUtil.java:21)
        at io.camunda.zeebe.broker.Broker.start (Broker.java:160)
        at io.camunda.zeebe.broker.StandaloneBroker.run (StandaloneBroker.java:60)

    at io.camunda.zeebe.broker.StandaloneBroker.main (StandaloneBroker.java:47)
```

The cause for this error is most probably an instrastructure issue or misconfiguration. However, `IoUtil.ensureDirectoryExists`  did not report why it failed. It might be better to use `FileUtil` as it uses nio.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Replace use of `IoUtil.ensureDirectoryExists` with `FileUtil.ensureDirectoryExists`. IoUtil hides the actual exception which makes it difficult to debug. 

All uses replaced in this PR is happening in the startup phase. Hence the exception is not handled, but simply rethrown. As a result the startup will fail.

## Related issues

closes #7311

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java [hunk 1]
```diff
@@ -73,7 +74,12 @@ private RaftStorage(
     this.persistedSnapshotStore = persistedSnapshotStore;
     this.journalIndexDensity = journalIndexDensity;
 
-    IoUtil.ensureDirectoryExists(directory, prefix + " raft partition storage");
+    try {
+      FileUtil.ensureDirectoryExists(directory.toPath());
+    } catch (final IOException e) {
+      throw new UncheckedIOException(
```
Comment (pihme) [inline atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java:80]: Please check with @npepinpe. Afaik he is working on guidelines for exception handling. Last time we talked about the matter he preferred `LangUtil.rethrowUnchecked(e);` over using `UncheckedIOException`

Other than that, I would approve the review.

Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java:80]: For the purpose of this PR that's fine, especially since we're wrapping explicitly an IOException (so the indirection from UncheckedIOException -> IOException isn't as bad imo as UncheckedIOException -> JsonProcessingException), I don't want to block you. That said, my 2 cents here, I would avoid doing I/O in a constructor if I can, and if I can't, then throw the checked exception. imo anyone calling constructors most likely doesn't think about handling potentially I/O errors most of the time.

Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/storage/RaftStorage.java:80]: I guess, moving this check outside of the constructor is out of scope for this issue. Besides, currently there is nothing a caller of this constructor can do to handle this error other than failing the startup.

**Review by pihme — APPROVED** [review]
Code looks good. Please check failing tests

**Comment by deepthidevaki** [comment]
Thanks for that fast review. The tests were failing because the options used when opening metastore files were incorrect. I have fixed it now. The build still fails because of an unrelated flaky test.
