### PR TITLE
fix(broker): do not log error if follower fails to take snapshot when log is not uptodate

### LINKED ISSUE #7911: Could not take snapshot on followers because the position doesn't exist
**Describe the bug**

Found the following error in a cluster

```
java.lang.IllegalStateException: Failed to take snapshot. Expected to find an indexed entry for determined snapshot position 243718629 (processedPosition = 243718629, exportedPosition=243718630), but found no matching indexed entry which contains this position.
```

On further investigation, this happened because the follower received a new snapshot from the leader, and it reset the log. After that it did not receive any new events because of network issues. Then later the follower tries to take a snapshot, but since the log is empty it cannot find the index of the position. In this case this is not actually an error because nothing has been processed/exported yet.  So ideally this error case should be handled differently on follower and leader.

The impact of this is nothing. The follower will eventually takes the snapshot when it starts receiving the new events.

**Expected behavior**

* If possible, not log this as an error on the follower. But this is most likely an error (inconsistent state) on the leader.
* It would be good if the follower does not attempt to take a snapshot if its log is not up-to-date with the processed and exported positions in the latest snapshot.

**Log/Stacktrace**

 https://console.cloud.google.com/errors/CJu-z5WFm_fKVw?service=zeebe-broker&version=release-1-2-0&time=P7D&project=zeebe-io

**Environment:**
 - Zeebe Version: release candidate 1.2.0

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Previously, this case was logged as error. Now AsyncSnapshotDirector treat it as a special case, log it in debug level.

Alternative options where to prevent taking snapshot in such cases. But it is very difficult to identify this case. All options prevented taking snapshots in scenarios where we want to take snapshot.
1. One option was to return -1 as processed position in ReplayStateMachine when no events after snapshot position is replayed. But this also prevents taking snapshot when there are no new records, but the exporter position increases.
2. Another options was to skip snapshot in StateController, when the determined snapshot position <= position in latest snapshot. This would not fix the bug, because if the exporter position has changed, it will still try to take snapshot and enter the same situation where it cannot find the indexed entry. Other options were attempted, but all failed in one or the other edge case.

So, the easiest solution is to treat it as a special case in AsyncSnapshotDirector.

## Related issues

closes #7911 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImplTest.java [hunk 1]
```diff
@@ -84,6 +92,19 @@ public void shouldNotTakeSnapshotIfDbIsClosed() {
         .hasCauseInstanceOf(StateClosedException.class);
   }
 
+  @Test
+  public void shouldNotTakeSnapshotIfNoIndexedEntry() {
+    // given
+    final var snapshotPosition = 1;
+    exporterPosition.set(snapshotPosition - 1);
```
Comment (oleschoenburg) [inline broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImplTest.java:99]: :wrench: These two aren't needed apparently. Not sure if it's worth to remove but it threw me off a bit while reading the test because I didn't understand how they are related.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/NoEntryAtSnapshotPosition.java [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+ */
+package io.camunda.zeebe.broker.system.partitions;
+
+/**
+ * Used when there is no entry at the determined snapshot position while taking a transient
+ * snapshot.
+ */
+public class NoEntryAtSnapshotPosition extends RuntimeException {
+
+  public NoEntryAtSnapshotPosition(final String format) {
```
Comment (oleschoenburg) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/NoEntryAtSnapshotPosition.java:16]: :upside_down_face:  
```suggestion
  public NoEntryAtSnapshotPosition(final String message) {
```

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 3]
```diff
@@ -256,6 +259,12 @@ private void takeSnapshot() {
           if (snapshotTakenError != null) {
             if (snapshotTakenError instanceof SnapshotException.SnapshotAlreadyExistsException) {
               LOG.debug("Did not take a snapshot. {}", snapshotTakenError.getMessage());
+            } else if (snapshotTakenError instanceof NoEntryAtSnapshotPosition
```
Comment (oleschoenburg) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:262]: :wrench: this is getting a bit unwieldy I think, maybe we could have a `logSnapshotTakenError` method?

**Review by lenaschoenburg — APPROVED** [review]
Thanks @deepthidevaki, nice to have fewer error logs!

Just a couple of optional suggestions, looks good otherwise.
