### PR TITLE
Ensures the advertised address is not resolved

### LINKED ISSUE #6983: The advertised address should be unresolved locally in the broker
**Describe the bug**

Currently, the broker will resolve its advertised address on start up. This is incorrect behavior, as this address may not resolve to anything locally for the broker, but may resolve to something for external nodes. It's not necessary for the node itself to be able to resolve its advertised address, as it's only meant to be used by others. Furthermore, resolving it at startup means we aren't using dynamic names anymore - the IP is fixed in the topology. While this isn't too terrible (since the node will eventually be replaced), it can lead to IP reuse causing nodes to contact other clusters, and it can lead to a broker being unable to startup if it cannot resolve its own advertised address.

imo this is an edge case, as I expect in most cases it's fine - but it's also a simple fix.

**To Reproduce**

Give an non existent (locally) address as your advertised node, and it will fail. There's nothing saying that the other node cannot resolve this address however. Second, assign it a DNS name, and then change the record's value - it will not update itself since only the initial resolved address is used.

**Expected behavior**

The advertised address is given verbatim to the nodes as is, without attempting to resolve it - it should be resolved by the other nodes at runtime.

**Environment:**
 - OS: 
 - Zeebe Version: 1.0.0
 - Configuration:

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes the usage of the advertised address to ensure it is not resolved when advertising it. This means it appears as is in the topology. This was already correct in the messaging layer with version 2 of the messaging protocol, where we always encode the host regardless of whether the address is resolved or not. It's then only resolved on the client side when trying to send a message.

## Related issues

closes #6983

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: atomix/utils/src/main/java/io/atomix/utils/net/Address.java [hunk 1]
```diff
@@ -140,43 +140,20 @@ public InetAddress address() {
...
+    if (resolve || socketAddress.isUnresolved()) {
+      // the constructor will by default attempt to resolve the host, and will fallback to the an
+      // unresolved address if it couldn't
+      socketAddress = new InetSocketAddress(host, port);
       return socketAddress.getAddress();
     }
 
-    // Try to resolve address, if not successful return null
-    if (socketAddress.isUnresolved()) {
-      synchronized (this) {
```
Comment (deepthidevaki) [inline atomix/utils/src/main/java/io/atomix/utils/net/Address.java:150]: Why was `synchronized` needed before? Would it cause any problem if this is removed?

**Review by deepthidevaki — COMMENTED** [review]
Looks good. :+1: Just have some questions.

File: atomix/utils/src/main/java/io/atomix/utils/net/Address.java [hunk 2]
```diff
@@ -140,43 +140,20 @@ public InetAddress address() {
    * @return the IP address
    */
   public InetAddress address(final boolean resolve) {
-    if (resolve) {
-      socketAddress = resolveAddress();
+    if (resolve || socketAddress.isUnresolved()) {
+      // the constructor will by default attempt to resolve the host, and will fallback to the an
+      // unresolved address if it couldn't
+      socketAddress = new InetSocketAddress(host, port);
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply atomix/utils/src/main/java/io/atomix/utils/net/Address.java:146]: That's my understanding - the boolean here refers to whether or not you should force the resolve even if it was already resolved. It will still fallback to the given host if it can't resolve anything. I checked usages, and this is called when bootstrapping client connections (where we force resolve, which makes sense), and in the V1 of the messaging protocol - but I think we always use V2 now, which encodes the host, and doesn't call this method.

File: atomix/utils/src/main/java/io/atomix/utils/net/Address.java (hunk 1 above)
Comment (npepinpe) [reply atomix/utils/src/main/java/io/atomix/utils/net/Address.java:150]: I imagine because there could be a race condition where you force resolve from different threads, and you want to avoid forcing resolve unless really necessary? So you need to do the check (read) and resolve (write) in the same critical section. This looks to me more like an small optimization imo, as the end result is the same. But none of us wrote this, so I can't be 100% sure of the original intent.

Comment (deepthidevaki) [reply atomix/utils/src/main/java/io/atomix/utils/net/Address.java:150]: Ya. I think it is safe to remove it.

**Review by deepthidevaki — APPROVED** [review]
:tada:

**Comment by npepinpe** [comment]
bors retry
