### PR TITLE
Don't create batch operations for single instance deletions

### LINKED ISSUE #44282: Batch operation details page showing Delete Process Instance for single operation
### 

### 

### 

### 

### Description

When triggering a single Delete operation from the Processes tab process instances, the Batch Operation is displaying this operation on the overview page

### Steps to reproduce

1. Deploy process and start a process instance
2. Go to Operate
3. Select the process instance and cancel it
4. Now delete the process instance

### Current behavior

The overview page for the Batch Operation is showing the **Cancel Process Instance** regarding this was not a batch operation. 

### Expected behavior

The overview page for the Batch Operation does not display single operation but only Batch operations for Delete Process Instance

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- Version 8.9.0-SNAPSHOT

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Single delete operations would result in a batch operation. This does not align with our other commands (eg. cancellation).  By directly writing a `HistoryDeletion.DELETE` command we don't have to have a batch operation here. This is fixed for both process instances and decision instances.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #44282

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@kristinkomschow I did both singular process instance and decision instance deletion in this one. The split is pretty clear by commits. If you prefer separate PRs for each let me know and I'll split it.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java [hunk 1]
```diff
@@ -142,15 +142,13 @@ public ResponseEntity<Object> getByKey(
...
+    return RequestExecutor.executeServiceMethodWithNoContentResult(
         () ->
             processInstanceServices
                 .withAuthentication(authenticationProvider.getCamundaAuthentication())
                 .deleteProcessInstance(
                     processInstanceKey,
-                    Objects.nonNull(request) ? request.getOperationReference() : null),
-        ResponseMapper::toBatchOperationCreatedWithResultResponse,
-        HttpStatus.OK);
+                    Objects.nonNull(request) ? request.getOperationReference() : null));
```
Comment (kristinkomschow) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java:151]: In which cases do we want `operationalReference` to be set in requests made via the API? Shouldn't this be removed for the single operation endpoints?

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/DecisionInstanceController.java [hunk 2]
```diff
@@ -73,15 +73,13 @@ public ResponseEntity<DecisionInstanceGetQueryResult> getDecisionInstanceById(
...
+    return RequestExecutor.executeServiceMethodWithNoContentResult(
         () ->
             decisionInstanceServices
                 .withAuthentication(authenticationProvider.getCamundaAuthentication())
                 .deleteDecisionInstance(
                     decisionInstanceKey,
-                    Objects.nonNull(request) ? request.getOperationReference() : null),
-        ResponseMapper::toBatchOperationCreatedWithResultResponse,
-        HttpStatus.OK);
+                    Objects.nonNull(request) ? request.getOperationReference() : null));
```
Comment (kristinkomschow) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/DecisionInstanceController.java:82]: Same question/remark as ProcessInstanceController.

**Review by kristinkomschow — APPROVED** [review]
Overall looks good to me.
I left two comments regarding the `operationalReference` in the deletion requests for single operations.

👍 I really appreciated the explanations for why the changes were made in the commit messages. Definitely helped with the review at points and made me think I should also do that more often.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java (hunk 1 above)
Comment (remcowesterhoud) [reply zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceController.java:151]: @kristinkomschow I don't think this is specific for batch operations. We have this, for example, for process instance cancellation as well.

https://github.com/camunda/camunda/blob/d983d72c9526a52f5f9ee4f688d8155109fc9c25/service/src/main/java/io/camunda/service/ProcessInstanceServices.java#L247-L257

I think the idea behind this is that a user could provide this reference and correlate exported events to this action.
