### PR TITLE
Do not fail consistency check if log is empty

### LINKED ISSUE #10451: Corrupt partition prevents startup of node
**Describe the bug**

A [benchmark node](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-09-22T11:20:44.904454673Z;query=resource.labels.namespace_name%3D%22medic-cw-37-de38e9e086-benchmark-mixed%22%0Aresource.labels.pod_name%3D%22medic-cw-37-de38e9e086-benchmark-mixed-zeebe-2%22%0A-resource.labels.container_name%3D%22debugger-9q4tw%22%0A-logName%3D%22projects%2Fzeebe-io%2Flogs%2Fevents%22%0Atimestamp%3D%222022-09-22T11:20:44.904454673Z%22%0AinsertId%3D%2238ntsbk0c2ikn344%22%0Atimestamp%3D%222022-09-22T11:20:44.904454673Z%22%0AinsertId%3D%2238ntsbk0c2ikn344%22;summaryFields=:false:32:beginning;timeRange=2022-09-22T10:20:44.905Z%2F2022-09-22T11:20:44.905Z?project=zeebe-io) became unhealthy after a restart because of being stuck at starting the Partition Server for partition 2.

**To Reproduce**

Zeebe node 2 in `medic-cw-37-de38e9e086-benchmark` is stuck at this issue.

**Expected behavior**

Would it make sense to discard the log and/or snapshot in this case to recover?

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.ExecutionException: Startup failed in the following steps: [Partition Manager]. See suppressed exceptions for details.
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:142) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:109) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:21) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:198) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:101) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23) ~[zeebe-util-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.broker.Broker.start(Broker.java:83) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:95) ~[camunda-zeebe-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.3.jar:2.7.3]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:81) ~[camunda-zeebe-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
Caused by: io.camunda.zeebe.scheduler.startup.StartupProcessException: Startup failed in the following steps: [Partition Manager]. See suppressed exceptions for details.
	at io.camunda.zeebe.scheduler.startup.StartupProcess.aggregateExceptionsSynchronized(StartupProcess.java:282) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:183) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:167) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	Suppressed: io.camunda.zeebe.scheduler.startup.StartupProcessStepException: Bootstrap step Partition Manager failed
		at io.camunda.zeebe.scheduler.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:185) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:167) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Expected to find a snapshot at index >= log's first index 213419494, but found snapshot 213252958. A previous snapshot is most likely corrupted.
		at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
		at java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source) ~[?:?]
		at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[?:?]
		at java.util.concurrent.CompletableFuture.thenApply(Unknown Source) ~[?:?]
		at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:106) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:193) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
		at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
		at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
		at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
		at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
		at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
		at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:195) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:63) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.broker.partitioning.PartitionManagerImpl.start(PartitionManagerImpl.java:125) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.broker.bootstrap.PartitionManagerStep.lambda$startupInternal$4(PartitionManagerStep.java:42) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
	Caused by: java.lang.IllegalStateException: Expected to find a snapshot at index >= log's first index 213419494, but found snapshot 213252958. A previous snapshot is most likely corrupted.
		at io.atomix.raft.impl.RaftContext.verifySnapshotLogConsistent(RaftContext.java:226) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:203) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:258) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:232) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:190) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:156) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:114) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:106) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:193) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
		at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
		at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
		at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
		at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
		at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
		at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:195) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:63) ~[zeebe-atomix-cluster-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.broker.partitioning.PartitionManagerImpl.start(PartitionManagerImpl.java:125) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at io.camunda.zeebe.broker.bootstrap.PartitionManagerStep.lambda$startupInternal$4(PartitionManagerStep.java:42) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]

```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration: 

Partition logs:
[partition-2-logs.tar.gz](https://github.com/camunda/zeebe/files/9626104/partition-2-logs.tar.gz)

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

When a follower receives a snapshot from the leader, it has to throw away the log and reset the log to `snapshotIndex + 1`. Previously we were doing it in the following order:
1. commit snapshot
2. reset 

In this case, if the system crashed after step 1, when the node restarts it is in an invalid state because the log is not reset after the snapshot. To prevent this case, we reset the log on startup based on the existing snapshot. This was buggy and caused issues, which was fixed by #10183. The fix was to reverse the order:

1. reset log
2. commit snapshot.

So on restart, there is no need to reset the log. If the system crashes after step 1, we have any empty log and no snapshot (or a previous snapshot). This is a valid state because this follower is not in the quorum, so no data is lost. After the restart the follower will receive the snapshot and the following events.

But this caused the consistency check to fail because it detected gaps between the snapshot and the first log entry. The state is not actually inconsistent, because no data is lost. So we fix this by updating the consistency check to treat this is a valid state. To make the state valid, if the log is empty, we reset it based on the available snapshot.

## Related issues

closes #10451 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+import java.util.concurrent.CompletableFuture;
+import org.junit.Rule;
+import org.junit.Test;
+
+public class RaftStartupConsistencyCheckTest {
+
+  @Rule public RaftRule raftRule = RaftRule.withBootstrappedNodes(3);
+
+  @Test // Regression test for https://github.com/camunda/zeebe/issues/10451
+  public void shouldNotFailRestartIfFollowerCrashedBeforeCommittingSnapshot() throws Exception {
```
Comment (deepthidevaki) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:22]: I added this test for reproducing the bug. I'm not fully satisfied with this test. May be the unit test `StateUtilTest` is enough, a we can remove this one?

**Review by lenaschoenburg — APPROVED** [review]

**Comment by Zelldon** [comment]
Give me an ~1 hour I want to take a look

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+    // given
+    final var followerToRestart = raftRule.getFollower().orElseThrow();
+    raftRule.partition(followerToRestart);
+
+    final var commitIndex = raftRule.appendEntries(10);
+    final var leader = raftRule.getLeader().orElseThrow();
+
+    // lower the threshold so that the follower recieves snapshot instead of log events
+    leader.getContext().setPreferSnapshotReplicationThreshold(1);
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:31]: TIL :D

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+    final long snapshotIndex = commitIndex - 1;
+    raftRule.doSnapshotOnMember(leader, snapshotIndex, 1);
+
+    final TestSnapshotStore testSnapshotStore =
+        (TestSnapshotStore) followerToRestart.getContext().getPersistedSnapshotStore();
+    final CompletableFuture<Void> followerCrashed = new CompletableFuture<>();
+    // Throw exception before committing the snapshot and trigger shutdown to simulat "crash"
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:38]:
```suggestion
    // Throw exception before committing the snapshot and trigger shutdown to simulate "crash"
```

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+    testSnapshotStore.interceptOnNewSnapshot(
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:39]: Cool :+1:

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+        });
+
+    // when
+    // reconnect follower so that it receives the snapshot, and trigger "crash"
+    raftRule.reconnect(followerToRestart);
+    followerCrashed.join(); // wait until follower is crashed
+
+    // then
+    // restart the follower
+    assertThatNoException()
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:60]: :wrench: We could also add that we check whether it received the snapshot to make it more explicit, that everything works again.

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java (hunk 1 above)
Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:22]: I would keep the test :+1: I like it. I guess would be also great if we build us some more tooling to start nodes in a specific state, like here I want to start a follower with no log at certain index and no snapshot or something like that.

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @deepthidevaki especially for the PR description this helped me to better understand the issue :+1: 

I have some remarks, but since Ole already accepted I guess you can decided what you want to do with them :)

File: atomix/cluster/src/main/java/io/atomix/raft/utils/StateUtil.java [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+ */
+package io.atomix.raft.utils;
+
+import java.util.function.LongConsumer;
+import org.slf4j.Logger;
+
+public class StateUtil {
+
+  /** throws IllegalStateException if state is inconsistent */
+  public static void verifySnapshotLogConsistent(
```
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/utils/StateUtil.java:16]: I added it there, for unit testing it easily. Otherwise, I don't know how to test it property.

[the remark this answers is not in the document]
Comment (Zelldon) [reply atomix/cluster/src/main/java/io/atomix/raft/utils/StateUtil.java:16]: Ok then maybe we split it into two methods like, one for verify and one like handleInconsistency or ensureConsistent log

**Comment by deepthidevaki** [comment]
bors merge

File: atomix/cluster/src/main/java/io/atomix/raft/utils/StateUtil.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/utils/StateUtil.java:16]: Sorry. I already triggered merge. I didn't see you reply. I had thought about it before, but didn't find it good enough. I will think about it on how to split as well as test it.
