### PR TITLE
fix: Creating Duplicate Beans for Tasklist & Operate

### LINKED ISSUE #36067: Process instance deletion fails via Operate V1 API due to version_conflict_engine_exception
### 

### 

### 

### 

### Description

Operate returns an error when attempting to [delete a process instance via the V1 API](https://docs.camunda.io/docs/apis-tools/operate-api/specifications/delete/).

### Steps to reproduce

Run `OperateV1ApiPermissionsIT#shouldBePermittedToDeleteProcessInstanceUsingV1Api` with Opensearch (run Option `-Dtest.integration.camunda.database.type=OS`).

### Current behavior

Test fails with a `version_conflict_engine_exception`.

### Expected behavior

Test passes consistently.

### Environment

SaaS & SM

### Version

- Component Version: 8.8

### Rootcause

For the single application setup there are two beans (one for operate and one for tasklist) created from some templates with the same index name.

For the deletion, Operate iterates over `ProcessInstanceDependant` templates and deletes documents associated with the process instance. What happens [here](https://github.com/camunda/camunda/blob/43d29775285f9c53748bbb7926a52ac86466cea5/operate/webapp/src/main/java/io/camunda/operate/webapp/opensearch/writer/OpensearchProcessInstanceWriter.java#L68-L77) is that the delete fails because some templates appear twice, leading to two (almost) simultaneous deletion requests for the same document which results in a `version_conflict_engine_exception`.

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Slack discussion with more context (internal): https://camunda.slack.com/archives/C08GPP57D8R/p1753708794658299

### PR DESCRIPTION
**Pull request by yohanfernando**
## Description

Previously, the Tasklist and Operate apps each had their own Elasticsearch/OpenSearch indexes, requiring separate beans of the same record type since they wrote to different indexes. Starting with v8.8, both apps now share the same indexes for reading and writing. Despite this, we were still creating two beans of the same type, with distinct names based on the app usage. As a result, running in standalone mode would unnecessarily create about four extra index template beans.

This change eliminates the need to create and wire duplicate beans by name. Instead, a single bean per type is created. However, in standalone mode, both Tasklist and Operate could end up creating identical beans without differentiation. To prevent this, Tasklist beans are annotated with an exclusion, ensuring they are only created when the "operate" profile is not active.

An additional benefit is that, in standalone mode, a "delete process instance by ID" request is no longer sent to all beans, including duplicates. This reduces the number of redundant delete calls made to the same indices due to duplicate beans—previously, about four unnecessary delete calls occurred.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes https://github.com/camunda/camunda/issues/36067

### CODE REVIEW

File: qa/acceptance-tests/src/test/java/io/camunda/it/operate/OperateV1ApiPermissionsIT.java [hunk 1]
```diff
@@ -64,7 +63,6 @@ public class OperateV1ApiPermissionsIT {
       new TestCamundaApplication()
           .withAuthorizationsEnabled()
           .withBasicAuth()
-          .withAdditionalProfile(Profile.OPERATE)
```
Comment (yohanfernando) [inline qa/acceptance-tests/src/test/java/io/camunda/it/operate/OperateV1ApiPermissionsIT.java:67]: We don't need this as the operate, tasklist, broker and identity profiles are added by default..

File: qa/util/src/main/java/io/camunda/qa/util/cluster/IndexTemplateDescriptorsConfigurator.java [hunk 2]
```diff
@@ -195,16 +195,8 @@ public TasklistMetricIndex getTasklistMetricIndex(
         operateProperties.getIndexPrefix(), databaseInfo.isElasticsearchDb());
   }
 
-  @Bean("operateSnapshotTaskVariableTemplate")
-  public SnapshotTaskVariableTemplate getOperateSnapshotTaskVariableTemplate(
-      final OperateProperties operateProperties, final DatabaseInfo databaseInfo) {
-    // Just take the provided DatabaseInfo, no need to distinguish between Tasklist or Operate
-    return new SnapshotTaskVariableTemplate(
-        operateProperties.getIndexPrefix(), databaseInfo.isElasticsearchDb());
-  }
```
Comment (yohanfernando) [inline qa/util/src/main/java/io/camunda/qa/util/cluster/IndexTemplateDescriptorsConfigurator.java:204]: fyi deleting app specific template beans

File: tasklist/common/src/main/java/io/camunda/tasklist/property/TasklistProperties.java [hunk 3]
```diff
@@ -369,12 +369,16 @@ public void setDocumentation(final TasklistDocumentationProperties documentation
...
   public String getIndexPrefix() {
-    if (database.equals(ELASTIC_SEARCH)) {
-      return elasticsearch.getIndexPrefix();
-    } else if (database.equals(OPEN_SEARCH)) {
-      return openSearch.getIndexPrefix();
-    }
-    return null;
+    return switch (database) {
+      case ELASTIC_SEARCH ->
+          getElasticsearch() == null ? null : getElasticsearch().getIndexPrefix();
```
Comment (houssain-barouni) [inline tasklist/common/src/main/java/io/camunda/tasklist/property/TasklistProperties.java]: `getElasticsearch() == null` is not needed, `getElasticsearch()` can never be null

File: tasklist/common/src/main/java/io/camunda/tasklist/property/TasklistProperties.java [hunk 4]
```diff
@@ -369,12 +369,16 @@ public void setDocumentation(final TasklistDocumentationProperties documentation
...
+      case OPEN_SEARCH -> getOpenSearch() == null ? null : getOpenSearch().getIndexPrefix();
```
Comment (houssain-barouni) [inline tasklist/common/src/main/java/io/camunda/tasklist/property/TasklistProperties.java]: same `getOpenSearch()` can never be null

**Review by houssain-barouni — APPROVED** [review]
LGTM! 💪
