### PR TITLE
Always activate the correct start event upon a create command

### LINKED ISSUE #10536: When creating an instance using createProcessInstanceCommand message start event is triggered
**Describe the bug**

Here is the process we used.
image

The process instance is created with one variable "uniqueId", using the following command
```
 client
            .newCreateInstanceCommand()
            .bpmnProcessId(processId)
            .latestVersion()
            .variables(variables)
            .send();
```
 But we can observe that it also receives the variable "rootProcessInstanceKey = 2251799813685320" that is only provided when publishing a message.

<details><summary>Records related to the instance</summary>
 <p>

```

{
  "brokerVersion": "8.0.6",
  "intent": "CREATE",
  "key": -1,
  "partitionId": -1,
  "position": 11152,
  "recordType": "COMMAND",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": -1,
  "timestamp": 1664363628533,
  "value": {
    "bpmnProcessId": "ping-pong-message",
    "processDefinitionKey": 0,
    "processInstanceKey": -1,
    "variables": {
      "uniqueId": "3d9efff3-28c1-45f1-bb87-da3b81505ace"
    },
    "version": -1
  },
  "valueType": "PROCESS_INSTANCE_CREATION"
}

{
  "brokerVersion": "8.0.6",
  "intent": "CREATED",
  "key": 2251799813689800,
  "partitionId": 1,
  "position": 11172,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11152,
  "timestamp": 1664363628552,
  "value": {
    "bpmnProcessId": "ping-pong-message",
    "name": "uniqueId",
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689799,
    "scopeKey": 2251799813689799,
    "value": "\"3d9efff3-28c1-45f1-bb87-da3b81505ace\""
  },
  "valueType": "VARIABLE"
}
{
  "brokerVersion": "8.0.6",
  "intent": "ACTIVATE_ELEMENT",
  "key": 2251799813689799,
  "partitionId": 1,
  "position": 11173,
  "recordType": "COMMAND",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11152,
  "timestamp": 1664363628552,
  "value": {
    "bpmnElementType": "PROCESS",
    "bpmnProcessId": "ping-pong-message",
    "elementId": "ping-pong-message",
    "flowScopeKey": -1,
    "parentElementInstanceKey": -1,
    "parentProcessInstanceKey": -1,
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689799,
    "version": 1
  },
  "valueType": "PROCESS_INSTANCE"
}
{
  "brokerVersion": "8.0.6",
  "intent": "CREATED",
  "key": 2251799813689801,
  "partitionId": 1,
  "position": 11174,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11152,
  "timestamp": 1664363628552,
  "value": {
    "bpmnProcessId": "ping-pong-message",
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689799,
    "variables": {
      "uniqueId": "3d9efff3-28c1-45f1-bb87-da3b81505ace"
    },
    "version": 1
  },
  "valueType": "PROCESS_INSTANCE_CREATION"
}
{
  "brokerVersion": "8.0.6",
  "intent": "ELEMENT_ACTIVATING",
  "key": 2251799813689799,
  "partitionId": 1,
  "position": 11188,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11173,
  "timestamp": 1664363628571,
  "value": {
    "bpmnElementType": "PROCESS",
    "bpmnProcessId": "ping-pong-message",
    "elementId": "ping-pong-message",
    "flowScopeKey": -1,
    "parentElementInstanceKey": -1,
    "parentProcessInstanceKey": -1,
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689799,
    "version": 1
  },
  "valueType": "PROCESS_INSTANCE"
}
{
  "brokerVersion": "8.0.6",
  "intent": "ELEMENT_ACTIVATED",
  "key": 2251799813689799,
  "partitionId": 1,
  "position": 11189,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11173,
  "timestamp": 1664363628571,
  "value": {
    "bpmnElementType": "PROCESS",
    "bpmnProcessId": "ping-pong-message",
    "elementId": "ping-pong-message",
    "flowScopeKey": -1,
    "parentElementInstanceKey": -1,
    "parentProcessInstanceKey": -1,
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689799,
    "version": 1
  },
  "valueType": "PROCESS_INSTANCE"
}
{
  "brokerVersion": "8.0.6",
  "intent": "TRIGGERED",
  "key": 2251799813689804,
  "partitionId": 1,
  "position": 11190,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11173,
  "timestamp": 1664363628571,
  "value": {
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689799,
    "scopeKey": 2251799813685250,
    "targetElementId": "Event_0q1ofs6",
    "variables": {}
  },
  "valueType": "PROCESS_EVENT"
}
{
  "brokerVersion": "8.0.6",
  "intent": "ELEMENT_ACTIVATING",
  "key": 2251799813689809,
  "partitionId": 1,
  "position": 11191,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11173,
  "timestamp": 1664363628571,
  "value": {
    "bpmnElementType": "START_EVENT",
    "bpmnProcessId": "ping-pong-message",
    "elementId": "Event_0q1ofs6",
    "flowScopeKey": 2251799813689799,
    "parentElementInstanceKey": -1,
    "parentProcessInstanceKey": -1,
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689799,
    "version": 1
  },
  "valueType": "PROCESS_INSTANCE"
}
{
  "brokerVersion": "8.0.6",
  "intent": "ELEMENT_ACTIVATED",
  "key": 2251799813689809,
  "partitionId": 1,
  "position": 11192,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11173,
  "timestamp": 1664363628571,
  "value": {
    "bpmnElementType": "START_EVENT",
    "bpmnProcessId": "ping-pong-message",
    "elementId": "Event_0q1ofs6",
    "flowScopeKey": 2251799813689799,
    "parentElementInstanceKey": -1,
    "parentProcessInstanceKey": -1,
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689799,
    "version": 1
  },
  "valueType": "PROCESS_INSTANCE"
}
```
</p>
</details>

In the last record you can see that the element activated is the message start event (id = Event_0q1ofs6)

A message was published around the same time, which correlated to the message start event and created process instance as expected:

<details><summary>Records related to this message</summary>
 <p>

```
cat log.json | jq '.records[].entries[] | select(.valueType == "MESSAGE") | select(.value.variables.rootProcessInstanceKey == "2251799813685320")'
{
  "brokerVersion": "8.0.6",
  "intent": "PUBLISH",
  "key": -1,
  "partitionId": -1,
  "position": 11158,
  "recordType": "COMMAND",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": -1,
  "timestamp": 1664363628536,
  "value": {
    "correlationKey": "2251799813685320",
    "deadline": -1,
    "messageId": "2251799813685320",
    "name": "receive-ping",
    "timeToLive": 3600000,
    "variables": {
      "rootProcessInstanceKey": "2251799813685320"
    }
  },
  "valueType": "MESSAGE"
}
{
  "brokerVersion": "8.0.6",
  "intent": "PUBLISHED",
  "key": 2251799813689802,
  "partitionId": 1,
  "position": 11177,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11158,
  "timestamp": 1664363628558,
  "value": {
    "correlationKey": "2251799813685320",
    "deadline": 1664367228536,
    "messageId": "2251799813685320",
    "name": "receive-ping",
    "timeToLive": 3600000,
    "variables": {
      "rootProcessInstanceKey": "2251799813685320"
    }
  },
  "valueType": "MESSAGE"
}

cat log.json | jq '.records[].entries[] | select(.sourceRecordPosition==11158)'

{
  "brokerVersion": "8.0.6",
  "intent": "PUBLISHED",
  "key": 2251799813689802,
  "partitionId": 1,
  "position": 11177,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11158,
  "timestamp": 1664363628558,
  "value": {
    "correlationKey": "2251799813685320",
    "deadline": 1664367228536,
    "messageId": "2251799813685320",
    "name": "receive-ping",
    "timeToLive": 3600000,
    "variables": {
      "rootProcessInstanceKey": "2251799813685320"
    }
  },
  "valueType": "MESSAGE"
}
{
  "brokerVersion": "8.0.6",
  "intent": "CORRELATED",
  "key": 2251799813685252,
  "partitionId": 1,
  "position": 11178,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11158,
  "timestamp": 1664363628558,
  "value": {
    "bpmnProcessId": "ping-pong-message",
    "correlationKey": "2251799813685320",
    "messageKey": 2251799813689802,
    "messageName": "receive-ping",
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689803,
    "startEventId": "Event_0q1ofs6",
    "variables": {
      "rootProcessInstanceKey": "2251799813685320"
    }
  },
  "valueType": "MESSAGE_START_EVENT_SUBSCRIPTION"
}
{
  "brokerVersion": "8.0.6",
  "intent": "TRIGGERING",
  "key": 2251799813689804,
  "partitionId": 1,
  "position": 11179,
  "recordType": "EVENT",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11158,
  "timestamp": 1664363628558,
  "value": {
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689803,
    "scopeKey": 2251799813685250,
    "targetElementId": "Event_0q1ofs6",
    "variables": {
      "rootProcessInstanceKey": "2251799813685320"
    }
  },
  "valueType": "PROCESS_EVENT"
}
{
  "brokerVersion": "8.0.6",
  "intent": "ACTIVATE_ELEMENT",
  "key": 2251799813689803,
  "partitionId": 1,
  "position": 11180,
  "recordType": "COMMAND",
  "rejectionReason": "",
  "rejectionType": "NULL_VAL",
  "sourceRecordPosition": 11158,
  "timestamp": 1664363628558,
  "value": {
    "bpmnElementType": "PROCESS",
    "bpmnProcessId": "ping-pong-message",
    "elementId": "ping-pong-message",
    "flowScopeKey": -1,
    "parentElementInstanceKey": -1,
    "parentProcessInstanceKey": -1,
    "processDefinitionKey": 2251799813685250,
    "processInstanceKey": 2251799813689803,
    "version": 1
  },
  "valueType": "PROCESS_INSTANCE"
}
```

</p>
</details>

**To Reproduce**

Run [e2e test](https://github.com/camunda/zeebe-e2e-test/) with [ping-pong-message.bpmn](https://github.com/camunda/zeebe-e2e-test/blob/main/loadgen/src/main/resources/ping-pong-message.bpmn) 

**Environment:**
- OS: 
- Zeebe Version: 8.0.6
- Configuration: Reproduced it with 1 partition, replication factor = 1 and 3 partitions, replication factor = 3

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

A process could contain multiple start events. Depending on whether we can find an EventTrigger we activate the triggered start event, or the none start event. If we want to activate the none start event, but we already have an EventTrigger in the state we will trigger the wrong one.

By using the process instance key in the EventTrigger we can determine whether this activation relates to the EventTrigger in the state. If this is the case we should activate this triggered start event. Otherwise we should activate the none start event.

For backwards compatibility's sake, if the process instance key is not available in the EventTrigger, we should still activate the triggered start event. This way behavior does not change.

## Related issues

closes #10536 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@saig0 Feel free to leave this review for a couple of weeks, since I won't be fixing comment before I'm back from my holidays anyway 😄

File: engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceTest.java [hunk 1]
```diff
@@ -222,4 +227,63 @@ public void shouldCompleteUndefinedTask() {
             tuple(BpmnElementType.TASK, ProcessInstanceIntent.ELEMENT_COMPLETED),
             tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.ELEMENT_COMPLETED));
   }
+
+  @Test
+  public void shouldActivateNoneStartEventWhenEventTriggerIsAvailableInState() {
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceTest.java:232]: :wrench: We could add a comment with a link to the issue (e.g. "This is a regression test of ..."). 

The issue can give more context than the test case itself.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceTest.java [hunk 2]
```diff
@@ -222,4 +227,63 @@ public void shouldCompleteUndefinedTask() {
...
+            .message(
+                MessageIntent.PUBLISH,
+                new MessageRecord().setName("msg").setCorrelationKey("").setTimeToLive(0)));
+
+    final var processInstanceKey =
+        RecordingExporter.processInstanceCreationRecords()
+            .withIntent(ProcessInstanceCreationIntent.CREATED)
+            .getFirst()
+            .getValue()
+            .getProcessInstanceKey();
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceTest.java:262]: :x: Getting the first process instance creation record with a class rule is flaky.

If the test case is not executed first then the first record is written by a different test case. If I run the whole test class locally then the test case fails. 

We could use a unique process id (e.g. `BrokerClassRuleHelper.getBpmnProcessId()`) and use it to filter the records.

File: engine/src/test/java/io/camunda/zeebe/engine/util/client/ProcessInstanceClient.java [hunk 3]
```diff
@@ -122,6 +129,11 @@ public ProcessInstanceCreationClient expectRejection() {
       expectation = REJECTION_EXPECTATION;
       return this;
     }
+
+    public ProcessInstanceCreationClient withoutExpectation() {
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/util/client/ProcessInstanceClient.java:133]: :wrench: The new method is not used. Can it be removed?

File: engine/src/test/java/io/camunda/zeebe/engine/state/instance/EventScopeInstanceStateTest.java [hunk 4]
```diff
@@ -404,7 +404,7 @@ void shouldTriggerStartEventForNonExistingEventScope() {
     final EventTrigger eventTrigger = createEventTrigger();
 
     // when
-    triggerStartEvent(SCOPE_KEY, 456, eventTrigger);
+    triggerStartEvent(SCOPE_KEY, 456, eventTrigger, -1L);
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/state/instance/EventScopeInstanceStateTest.java:407]: :wrench: We should verify in a test case that the process instance key of the event trigger is stored in the state.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceTest.java [hunk 5]
```diff
@@ -222,4 +227,63 @@ public void shouldCompleteUndefinedTask() {
...
+            tuple(
+                BpmnElementType.START_EVENT, "noneStart", ProcessInstanceIntent.ELEMENT_ACTIVATING),
+            tuple(
+                BpmnElementType.START_EVENT, "noneStart", ProcessInstanceIntent.ELEMENT_ACTIVATED))
+        .doesNotContain(
+            tuple(BpmnElementType.START_EVENT, "msgStart", ProcessInstanceIntent.ACTIVATE_ELEMENT),
+            tuple(
+                BpmnElementType.START_EVENT, "msgStart", ProcessInstanceIntent.ELEMENT_ACTIVATING),
+            tuple(
+                BpmnElementType.START_EVENT, "msgStart", ProcessInstanceIntent.ELEMENT_ACTIVATED));
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceTest.java:287]: :wrench: Additionally, we could verify that the message start event is activated later but with a different process instance key.

File: bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/builder/ProcessBuilder.java [hunk 6]
```diff
@@ -89,11 +89,20 @@ public IntermediateCatchEventBuilder linkCatchEvent(final String id) {
   protected void setCoordinates(final BpmnShape targetBpmnShape) {
     final Bounds bounds = targetBpmnShape.getBounds();
     bounds.setX(100);
-    bounds.setY(100);
+    bounds.setY(100 + getLowestHeight());
```
Comment (saig0) [inline bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/builder/ProcessBuilder.java:92]: :x: The `CoordinatesGenerationTest` doesn't like your changes. 

This test fails because the coordinated doesn't match the expectations anymore.

**Review by saig0 — CHANGES_REQUESTED** [review]
@remcowesterhoud the changes look good. :+1: 

But some tests are failing. I have also a few minor suggestions. Please have a look. :cookie:

**Review by saig0 — APPROVED** [review]
@remcowesterhoud looks good. :+1:

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors retry
