### PR TITLE
fix: don't accidentally skip processing after log truncation

### LINKED ISSUE #41325: Log entry `skipProcessing` flag can unintentionally be set after log truncation
Log entries have a `skipProcessing` flag which is only set when we actually want to skip: https://github.com/camunda/camunda/blob/ff8dbe135d1523283ba1324ed42c98824150432d/zeebe/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/serializer/LogAppendEntrySerializer.java#L93-L95

This causes problems if the underlying log segment is not zeroed out, for example after log truncation. Because the byte is not written, if the old data had set that specific byte to anything but 0, that command would be skipped during processing.

This bug seemingly existed ever since we have introduced the `skipProcessing` flag.

There are at least two ways to address it:
1. Always write the `skipProcessing` byte. That ensures that none of the underlying segment data can peek through.
2. Zero out data on log truncation.

Most likely related to https://jira.camunda.com/browse/SUPPORT-28579

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This ensures that we always set the `skipProcessing` byte, regardless of whether we should skip or not. This is important because log truncation does not zero out invalidated data. New entries without the `skipProcessing` byte set would allow that invalidated data to peek through. If that data happened to contain a `1`, we'd unintentionally skip processing of the new record.

This could occur:
1. When truncating uncommitted entries, for example on passive members
2. When replacing an existing entry because it is written again with a higher term.

In versions <8.8, this could also occur after restoring from a backup because the log is truncated down to the checkpoint position.

We go one step further and overwrite all unused bytes in general, see 8c682f5.

closes #41325

### CODE REVIEW

File: zeebe/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/serializer/LogAppendEntrySerializer.java [hunk 1]
```diff
@@ -85,14 +86,13 @@ static int serialize(
     final var framedEntryLength = framedLength(entry);
 
     // Write the dispatcher framing
-    DataFrameDescriptor.setFramedLength(writeBuffer, writeBufferOffset, framedEntryLength);
+    DataFrameDescriptor.write(writeBuffer, writeBufferOffset, framedEntryLength);
     final var entryOffset = writeBufferOffset + DataFrameDescriptor.HEADER_LENGTH;
 
     // Write the entry
     setVersion(writeBuffer, entryOffset);
-    if (entry.isProcessed()) {
```
Comment (entangled90) [inline zeebe/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/serializer/LogAppendEntrySerializer.java:93]: 💭 without this fix, `skipProcessing` would contain any random data it was previously written there, in case the log was truncated.
Now it's always written to the correct value.
Moreover, we also now make sure that any remaining bytes in the headers are zeroed for safety, even though they are not actually used.

File: zeebe/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/serializer/DataFrameDescriptor.java [hunk 2]
```diff
@@ -23,9 +23,11 @@ public final class DataFrameDescriptor {
 
   public static final int HEADER_LENGTH = 12;
 
-  public static void setFramedLength(
-      final MutableDirectBuffer buffer, final int offset, final int length) {
+  public static void write(final MutableDirectBuffer buffer, final int offset, final int length) {
     buffer.putInt(offset + FRAME_LENGTH_OFFSET, length);
+    for (int i = 4; i < HEADER_LENGTH; i++) {
```
Comment (entangled90) [inline zeebe/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/serializer/DataFrameDescriptor.java:28]: 💭 no need to do a ~ `memcopy` here probably as the compiler should just unroll this loop, there is no data dependencies between iteration and the number of iterations is static.

**Review by entangled90 — APPROVED** [review]
Thanks for spotting this & fixing it!
