### PR TITLE
fix: prevent path traversal in local document store

### LINKED ISSUE #29528: Uncontrolled data used in path expression
Fix this vulnerability: https://github.com/camunda/camunda/security/code-scanning/6104

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This fixes https://github.com/camunda/camunda/issues/29528 by actually checking that the paths used to store documents and their metadata are not escaping the local storage path.

### CODE REVIEW

File: document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java [hunk 1]
```diff
@@ -208,6 +208,16 @@ private Either<DocumentError, Void> verifyContentHashInternal(
     return Either.right(null);
   }
 
+  private Path resolveInStorage(final String fileName) {
+    // Prevent path traversal
+    final var resolved = storagePath.resolve(fileName).normalize();
+    if (!resolved.startsWith(storagePath)) {
+      // Don't provide the actual path in the error message to avoid leaking information
+      throw new IllegalArgumentException("Cannot store %s".formatted(fileName));
```
Comment (georgios-goulos) [inline document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java:216]: The code in this class does not typically throw exceptions. Instead, we use `Either.left(...)`.

File: document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java [hunk 2]
```diff
@@ -208,6 +208,16 @@ private Either<DocumentError, Void> verifyContentHashInternal(
     return Either.right(null);
   }
 
+  private Path resolveInStorage(final String fileName) {
```
Comment (georgios-goulos) [inline document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java:211]: It would be good to validate this logic via a test or two.

**Review by georgios-goulos — DISMISSED** [review]
Thanks for picking this up

**Comment by lenaschoenburg** [comment]
> The code in this class does not typically throw exceptions. Instead, we use Either.left(...).

Nice! Feel free to adjust to your code style before merging. As long as we `normalize` the path and compare it against the `storagePath`, I'm happy :) 

> It would be good to validate this logic via a test or two.

Makes sense :+1: That would be easier without the document id validation though.

**Comment by georgios-goulos** [comment]
> Feel free to adjust to your code style before merging

I will take care of it when I have some time for non-critical things 👍

**Comment by georgios-goulos** [comment]
@marcosgvieira this PR is not ready to be merged yet due to the comments above.

This could be addressed as part of https://github.com/camunda/camunda/issues/31418 once we prioritise it accordingly

**Comment by marcosgvieira** [comment]
> @marcosgvieira this PR is not ready to be merged yet due to the comments above.
> 
> This could be addressed as part of #31418 once we prioritise it accordingly

Thanks for clarifying that @georgios-goulos - can we have this as a side task for you next week?

**Comment by georgios-goulos** [comment]
> Thanks for clarifying that @georgios-goulos - can we have this as a side task for you next week?

Sure!

File: document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java [hunk 3]
```diff
@@ -41,17 +41,12 @@ public class LocalStorageDocumentStore implements DocumentStore {
       org.slf4j.LoggerFactory.getLogger(LocalStorageDocumentStore.class);
   private static final List<String> INVALID_DOCUMENT_ID_CHARACTERS = List.of("..", "/", "\\");
   private final Path storagePath;
-  private final FileHandler fileHandler;
   private final ExecutorService executor;
   private final ObjectMapper mapper;
 
   public LocalStorageDocumentStore(
-      final Path storagePath,
-      final FileHandler fileHandler,
```
Comment (georgios-goulos) [inline document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java:50]: I decided to get rid of FileHandler because the methods in that class looked quite vulnerable. I could:

* improve that class by providing the storage path in the constructor of that class and use that to ensure that any file to be deleted/created/read should exist within the given storage path 
* delete the class and move all its methods to `LocalStorageDocumentStore`. This way we can ensure within this `LocalStorageDocumentStore` that any operation affecting the filesystem will be done only after the appropriate input validation has taken place.

Getting rid of `FileHandler` also seemed simpler and it was not used in any other place so I thought removing it would also adhere to [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it).

**Comment by georgios-goulos** [comment]
@lenaschoenburg can you please take a look at the current state of this PR and let me know if my proposed solution is acceptable?

File: document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java [hunk 4]
```diff
@@ -110,26 +105,27 @@ public void validateSetup() {
...
       final DocumentCreationRequest request) {
     final String documentId = getDocumentId(request);
-    if (!documentIdIsValid(documentId)) {
-      return Either.left(new InvalidInput(generateInvalidDocumentIdMessage(documentId)));
+
+    final Path documentPath;
+    try {
+      documentPath = resolveInStorage(documentId);
+    } catch (final IllegalArgumentException e) {
+      return Either.left(new InvalidInput(e.getMessage()));
```
Comment (lenaschoenburg) [inline document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java:113]: :question: Why throw away the cause here? Just extracting the message and repackaging it as a new exception throws away useful information.

**Review by lenaschoenburg — COMMENTED** [review]
The fix itself looks fine but then again, I already opened the PR with that included so my review is a bit biased :)

Since it's my own PR, I can't approve it.

File: document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java (hunk 4 above)
Comment (georgios-goulos) [reply document/store/src/main/java/io/camunda/document/store/localstorage/LocalStorageDocumentStore.java:113]: `InvalidInput` is not an Exception, it is an implementation of the [DocumentError](https://github.com/camunda/camunda/blob/main/document/api/src/main/java/io/camunda/document/api/DocumentError.java#L15) interface.

**Comment by georgios-goulos** [comment]
> Since it's my own PR, I can't approve it.

That's perfectly fine! If you are okay with the current implementation I will approve and merge it myself.

Thanks for investing your time in addressing this 👍

**Review by georgios-goulos — APPROVED** [review]
