### PR TITLE
fix: truncated variables create/update stuck in loading state

### LINKED ISSUE #51469: Variables tab stuck in infinite loading state when editing or adding a large (truncated) variable
## Description

  When a process instance has a variable whose value is too large to be returned in full by the search API (`isTruncated: true`), editing that variable causes the UI to get stuck in a permanent loading state. The backend update succeeds, but the frontend
  never acknowledges it and the spinner never disappears. The same issue affects adding a new variable with a sufficiently large value.

  ## Steps to reproduce

  1. Open Operate and navigate to a process instance that has at least one variable with a large value (large enough that the API returns it with `isTruncated: true`)
  2. Go to the **Variables** tab
  3. Click the **Edit** button next to the truncated variable
  4. The full value loads in the editor (this part works correctly)
  5. Make any change to the value, or leave it as-is
  6. Click **Save**

  ## Current behavior

  - The loading spinner appears on the variable row (replacing the Save button)
  - The spinner never disappears
  - The "Variable updated" success notification never appears
  - All edit buttons on other variables remain disabled
  - The form is permanently stuck in a submitting state
  - The UI is effectively broken until the page is refreshed

  ## Expected behavior

  - After clicking Save, the loading spinner appears briefly while the update propagates to Elasticsearch
  - Once the updated value is confirmed in ES, the spinner disappears and the "Variable updated" notification is shown
  - The variable list refreshes with the new value
  - Other edit buttons become available again

  ## Workaround

  Refreshing the page resolves the stuck state. The backend update **did** succeed (the new value is persisted), so a refresh will show the correct updated value. The issue is purely a frontend confirmation loop that never exits.

  ## Root cause

  After a successful `PUT /v2/elementInstances/{key}` (204), the frontend polls `POST /v2/variables/search` with the filter `{name, value: <submittedValue>, processInstanceKey, scopeKey}` to confirm Elasticsearch has indexed the update before showing success.

  For large variables, the search API returns items where `value` is a **truncated** string and `isTruncated: true`. The filter compares the full submitted value against this truncated stored value — they never match. React Query retries every second
  indefinitely, so the mutation promise never resolves and the form stays in `submitting: true` forever.

  The same bug exists for adding a new variable with a large value, for the same reason.

  ## Solution ideas

  **Editing an existing variable** — use `GET /v2/variables/{variableKey}` for the polling check instead of `searchVariables`. The single-variable GET endpoint returns the full non-truncated value. After the PUT, poll the GET until `response.value ===
  submittedValue`. The `variableKey` is available in the variables list and is threaded through the form state for this purpose.

  **Adding a new variable** — drop the `value` filter from the search entirely. For a new variable there is no prior value to confuse with, so finding the variable by name in the search result is sufficient confirmation that ES has indexed it.

  **Discarded option — use full value as search filter** — the search filter schema only supports filtering on the (truncated) `value` field, not `fullValue`. Doing a full-text equality match on potentially megabyte-sized strings also has significant
  performance implications.

  ## Dev → QA handover

  The fix changes the polling strategy post-save depending on whether it's an edit or an add.

  | Scenario | Variable size | Action | Expected |
  |---|---|---|---|
  | Edit existing variable | Large (`isTruncated: true`) | Change value, Save | Loading resolves, "Variable updated" shown, list refreshes |
  | Edit existing variable | Large (`isTruncated: true`) | Open editor without changes, Save | Same as above |
  | Add new variable | Large value pasted/typed | Save | Loading resolves, "Variable added" shown |
  | Edit existing variable | Small (not truncated) | Change value, Save | Behaviour unchanged — still works |
  | Add new variable | Small value | Save | Behaviour unchanged — still works |
  | Network is slow | Any | Save | Loading spinner shows until ES confirms, then resolves normally |
  | Page refresh mid-edit | Large variable | Save → immediately refresh | Refreshed page shows the updated value (backend was always correct) |

### PR DESCRIPTION
**Pull request by arienzIT**
## Summary

  - Fix infinite loading state when editing a large (truncated) variable in the Variables tab
  - Fix the same issue when adding a new variable with a large value

  ## Changes

  After a successful variable update, the polling strategy now depends on the operation:

  - **Edit:** polls `GET /v2/variables/{variableKey}` (returns full value) and compares against the submitted value — replaces the broken `searchVariables` approach which compared against the truncated stored value
  - **Add:** polls `searchVariables` by name only, without a value filter — finding the variable by name is sufficient confirmation for a new variable

  ## How to test

  1. Open a process instance with a variable where `isTruncated: true`
  2. Edit it, change the value, click Save → loading should resolve and "Variable updated" should appear
  3. Add a new variable with a large value → same result
  4. Edit/add a small variable → behaviour unchanged

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #51469

### CODE REVIEW

File: operate/client/src/modules/mutations/elementInstances/useElementInstanceVariables.tsx [hunk 1]
```diff
@@ -39,36 +40,55 @@ function useElementInstanceVariables(
...
-        retry: true,
-        retryDelay: 1000,
-      });
+            return response;
+          },
+          retry: true,
+          retryDelay: 1000,
+        });
+      } else {
+        await queryClient.fetchQuery({
```
Comment (arienzIT) [inline operate/client/src/modules/mutations/elementInstances/useElementInstanceVariables.tsx:63]: 💡 this is still needed for creation where the `variableKey` is not set yet

File: operate/client/src/modules/mutations/elementInstances/useElementInstanceVariables.tsx [hunk 2]
```diff
@@ -39,36 +40,55 @@ function useElementInstanceVariables(
...
-          return response;
-        },
-        retry: true,
-        retryDelay: 1000,
-      });
+            return response;
+          },
+          retry: true,
+          retryDelay: 1000,
+        });
```
[the remark this answers is not in the document]
Comment (arienzIT) [reply operate/client/src/modules/mutations/elementInstances/useElementInstanceVariables.tsx:61]: Ignore, the config is what was used in the previous implementation and it was not reported to be buggy. We can leave it out for now and follow-up on this if needed

File: operate/client/src/modules/mutations/elementInstances/useElementInstanceVariables.tsx [hunk 3]
```diff
@@ -39,36 +40,55 @@ function useElementInstanceVariables(
...
-              value: variable.value,
-              processInstanceKey,
-              scopeKey: elementInstanceKey,
-            },
-          });
+      if (variable.variableKey !== undefined) {
+        await queryClient.fetchQuery({
+          queryKey: queryKeys.variable.get(variable.variableKey),
+          queryFn: async () => {
+            const {response, error} = await getVariable(variable.variableKey!);
```
[the remark this answers is not in the document]
Comment (arienzIT) [reply operate/client/src/modules/mutations/elementInstances/useElementInstanceVariables.tsx:47]: @copilot remove the changes you applied for this comment in latest commit as: staleTime on useQuery controls when that observer considers its cached data fresh enough to skip a background refetch. Specifically it affects two things for that component:

  1. On mount — if data is already in cache and younger than staleTime, no background refetch is triggered
  2. On window focus / reconnect — same check before deciding to refetch

  So staleTime: 5000 in useVariable means: if a component using useVariable mounts (or the window refocuses) within 5 seconds of the last fetch, it won't fire another network request and will just use the cached value. This avoids redundant requests when, for
   example, the user opens and closes the full variable modal quickly, or when multiple components subscribe to the same key in quick succession.

  It has nothing to do with fetchQuery because fetchQuery is an imperative call on the client — it has no observer, no component lifecycle, no mount/focus events. It just looks at the options you pass it plus the global client defaults.

  So the copilot's concern conflates two separate things: observer-level staleness (controls reactive refetches) vs. fetchQuery's imperative staleness check (controls whether the one-off call hits the network). They share the query key and the cache, but each
   uses its own staleTime configuration independently.

File: operate/client/src/App/ProcessInstance/BottomPanelTabs/VariablesTab/tests/addVariable.test.tsx [hunk 4]
```diff
@@ -536,4 +545,80 @@ describe('Add variable', () => {
...
+      screen.getByRole('textbox', {name: /value/i}),
+      '"large-value"',
+    );
+
+    await waitFor(() => {
+      expect(screen.getByRole('button', {name: /save/i})).toBeEnabled();
+    });
+
+    mockUpdateElementInstanceVariables(':1').withDelay(null);
+    mockSearchVariables().withSuccess({
```
Comment (danielkelemen) [inline operate/client/src/App/ProcessInstance/BottomPanelTabs/VariablesTab/tests/addVariable.test.tsx:574]: ❓ Does this need to be repeated twice? If yes, a loop might be better.

In `editVariable.test.tsx‎` as well.

**Review by danielkelemen — APPROVED** [review]
Nice, thanks for fixing it!

🔧 Adding a limit to the retries as copilot suggested could make sense but it's not a new thing so I let you decide. With this logic it probably will only happen if there is a backend issue.

File: operate/client/src/App/ProcessInstance/BottomPanelTabs/VariablesTab/tests/addVariable.test.tsx (hunk 4 above)
Comment (arienzIT) [reply operate/client/src/App/ProcessInstance/BottomPanelTabs/VariablesTab/tests/addVariable.test.tsx:574]: Removed

**Comment by arienzIT** [comment]
> Nice, thanks for fixing it!
> 
> 🔧 Adding a limit to the retries as copilot suggested could make sense but it's not a new thing so I let you decide. With this logic it probably will only happen if there is a backend issue.

I will consider it if turns out to be problematic when the BE fails, but I think since this logic is pre-existing, I would just keep it as is for the sake of this PR
