### PR TITLE
fix: existence check for adding members

### LINKED ISSUE #44773: Bypassing existence check for users and groups assigned to Tenant
### 

### 

### 

### 

### Description

I can assign fake users and groups via configuration of Tenant w.ith Basic auth

### Steps to reproduce

1. create a tenant:
`export ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_CLASSNAME=io.camunda.exporter.CamundaExporter && \
export ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_CONNECT_URL=http://localhost:9200 && \
export ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_BULK_SIZE=100 && \
export ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_INDEX_SHOULDWAITFORIMPORTERS=false && \
export CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED=true && \
export CAMUNDA_SECURITY_AUTHENTICATION_UNPROTECTEDAPI=false && \
export CAMUNDA_SECURITY_MULTITENANCY_CHECKSENABLED=true && \
export CAMUNDA_SECURITY_INITIALIZATION_USERS_0_USERNAME=demo && \
export CAMUNDA_SECURITY_INITIALIZATION_USERS_0_PASSWORD=demo && \
export CAMUNDA_SECURITY_INITIALIZATION_USERS_0_NAME=Demo && \
export CAMUNDA_SECURITY_INITIALIZATION_USERS_0_EMAIL=demo@example.com && \
export CAMUNDA_SECURITY_INITIALIZATION_USERS_1_USERNAME=test && \
export CAMUNDA_SECURITY_INITIALIZATION_USERS_1_PASSWORD=test && \
export CAMUNDA_SECURITY_INITIALIZATION_USERS_1_NAME=Test && \
export CAMUNDA_SECURITY_INITIALIZATION_USERS_1_EMAIL=test@example.com && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_0_OWNER_TYPE=USER && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_0_OWNER_ID=test && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_0_RESOURCE_TYPE=AUTHORIZATION && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_0_RESOURCE_ID='*' && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_0_PERMISSIONS='CREATE,READ,UPDATE,DELETE' && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_1_OWNER_TYPE=USER && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_1_OWNER_ID=test && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_1_RESOURCE_TYPE=BATCH && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_1_RESOURCE_ID='*' && \
export CAMUNDA_SECURITY_INITIALIZATION_AUTHORIZATIONS_1_PERMISSIONS='CREATE,CREATE_BATCH_OPERATION_CANCEL_PROCESS_INSTANCE,CREATE_BATCH_OPERATION_DELETE_PROCESS_INSTANCE,CREATE_BATCH_OPERATION_MIGRATE_PROCESS_INSTANCE,CREATE_BATCH_OPERATION_MODIFY_PROCESS_INSTANCE,CREATE_BATCH_OPERATION_RESOLVE_INCIDENT,CREATE_BATCH_OPERATION_DELETE_DECISION_INSTANCE,CREATE_BATCH_OPERATION_DELETE_DECISION_DEFINITION,CREATE_BATCH_OPERATION_DELETE_PROCESS_DEFINITION,READ,UPDATE' && \
export CAMUNDA_SECURITY_INITIALIZATION_DEFAULTROLES_ADMIN_USERS_0=demo && \
export CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_TENANAT_ID=tenantConfigId && \
export CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_NAME="test config tenant" && \
export CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_DESCRIPTION="test tenant descriptioon" && \
export CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_USERS='demo,test,UserA,UserB,UserC' && \
export CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_ROLES='admin,connectors,R4' && \
export CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_GROUPS='adminGr,connectorsGr,R4GR' && \
export CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_CLIENTS='adminGr,connectorsGr,R4GR.,msdfdsjhb' && \
export SPRING_PROFILES_ACTIVE=identity,tasklist,operate,broker,consolidated-auth,dev-data && \
./bin/camunda
`
2. check users & groups & roles

### Current behavior

Users and Groups are populated, but not roles(which is good!).

### Expected behavior

Non-existent entities should not be assigned to the tenant.

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SM

### Version

- Component Version: 8.9-RC1

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by mrm1st3r**
## Description

fix existence check for adding members for groups, roles and tenants

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #44773

### CODE REVIEW

File: security/security-core/src/main/java/io/camunda/security/configuration/AuthenticationConfiguration.java [hunk 1]
```diff
@@ -60,4 +60,12 @@ public ProvidersConfiguration getProviders() {
...
     this.providers = providers;
   }
+
+  public boolean isCamundaGroupsEnabled() {
+    return !(getMethod() == AuthenticationMethod.OIDC && getOidc().isGroupsClaimConfigured());
+  }
+
+  public boolean isCamundaUsersEnabled() {
+    return getMethod() != AuthenticationMethod.OIDC;
+  }
```
Comment (remcowesterhoud) [inline security/security-core/src/main/java/io/camunda/security/configuration/AuthenticationConfiguration.java:70]: 👍 I like extracting this logic to the configuration class itself

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/RoleAddEntityProcessor.java [hunk 2]
```diff
@@ -143,15 +144,10 @@ final var record = command.getValue();
...
-      final EntityType entityType,
-      final String entityId) {
+  private boolean isEntityPresent(final EntityType entityType, final String entityId) {
 
-    final boolean localUserEnabled =
-        (boolean) authorizations.getOrDefault(IS_CAMUNDA_USERS_ENABLED, false);
-    final boolean localGroupEnabled =
-        (boolean) authorizations.getOrDefault(IS_CAMUNDA_GROUPS_ENABLED, false);
+    final boolean localUserEnabled = securityConfig.getAuthentication().isCamundaUsersEnabled();
+    final boolean localGroupEnabled = securityConfig.getAuthentication().isCamundaGroupsEnabled();
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/RoleAddEntityProcessor.java:150]: @entangled90 IIRC you asked about not using the authorizations map here at some point. They are dissapearing now 🙂

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/UpdateAuthorizationTest.java [hunk 3]
```diff
@@ -31,6 +32,12 @@ public class UpdateAuthorizationTest {
   @Rule public final EngineRule engine = EngineRule.singlePartition();
   @Rule public final TestWatcher recordingExporterTestWatcher = new RecordingExporterTestWatcher();
 
+  @Before
+  public void setup() {
+    engine.user().newUser("ownerId").create();
+    engine.group().newGroup("ownerId").create();
+  }
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/UpdateAuthorizationTest.java:39]: ❓ Why do we need this now in the tests?

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/CreateAuthorizationMultipartitionTest.java [hunk 4]
```diff
@@ -35,7 +36,12 @@ public class CreateAuthorizationMultipartitionTest {
 
   private static final int PARTITION_COUNT = 3;
 
-  @Rule public final EngineRule engine = EngineRule.multiplePartition(PARTITION_COUNT);
+  @Rule
+  public final EngineRule engine =
+      EngineRule.multiplePartition(PARTITION_COUNT)
+          .withSecurityConfig(
+              (cfg) -> cfg.getAuthentication().setMethod(AuthenticationMethod.OIDC));
+
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/CreateAuthorizationMultipartitionTest.java:44]: ❓ Am I right that we need this now as before it defaulted to `false` so we didn't have to think about it at all, and now we actually need to set the security configurations properly?

File: security/security-core/src/main/java/io/camunda/security/configuration/AuthenticationConfiguration.java (hunk 1 above)
Comment (remcowesterhoud) [inline security/security-core/src/main/java/io/camunda/security/configuration/AuthenticationConfiguration.java:70]: 🔧 As this contains some logic I think it'd be good to make sure it's tested. Maybe it is implicitly covered somewhere already in ITs, but I didn't catch anything in this PR.

**Review by remcowesterhoud — COMMENTED** [review]
Looks good from my side. I'll let @Ben-Sheppard finish the review as well.

Overall really happy with this approach. Using the configurations makes much more sense than using this authorizations map in the engine.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/RoleAddEntityProcessor.java (hunk 2 above)
Comment (entangled90) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/RoleAddEntityProcessor.java:150]: Yes, that was because of this [pr](https://github.com/camunda/camunda/pull/47181), let's see if it works after this is merged :wink:

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/CreateAuthorizationMultipartitionTest.java (hunk 4 above)
Comment (mrm1st3r) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/CreateAuthorizationMultipartitionTest.java:44]: Exactly, before the change the `is_camunda_users_enabled` defaulted to `false`, but the authenticationConfig defaults to `basic`, as a result the derived flag defaults to `true`.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/UpdateAuthorizationTest.java (hunk 3 above)
Comment (mrm1st3r) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/UpdateAuthorizationTest.java:39]: The same reason as for the added config property. Here the fix is the other way round, making sure all referenced entities exist and keeping the auth method to basic (default).

Fixing it this way didn't work for the multipartition tests, so I changed it there to OIDC mode instead.

**Review by Ben-Sheppard — APPROVED** [review]
Thank you for looking into this @mrm1st3r - as we spoke about, using the configuration for this feels like the correct approach, we have the problem still (but we had it anyway) of what is the expected interaction when multiple providers are configured with dofferent configurations but I think that is something we need to look at deeper and resolve with Steve. I'll approve from my side because it seems ok to me, would be good to also get @remcowesterhoud 's thoughts on your answers :)
