### PR TITLE
fix: close response in 404 handling for management identity

### LINKED ISSUE #39284: Identity Migration leaks http connections in case of 404s
### 

### 

### 

### 

### Description

The 404 handling on requests to management identity causes connections to leak.

The issue is here https://github.com/camunda/camunda/blob/stable/8.8/migration/identity-migration/src/main/java/io/camunda/migration/identity/config/ManagementIdentityConnectorConfig.java#L115

In case of 404s an exception is thrown which interrupts the spring internal handling of the response that would normally close it.

In case 5 404s have happened all 5 concurrent connections to management identity API have been occupied and the next request will eventually timeout acquiring a connection. This is indicated by this log:
```
org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ex-0000000039 endpoint lease request (3 MINUTES) [route: {}->[[http://camunda-platform-identity:80](http://camunda-platform-identity/)]][total available:; route allocated: 5 of 5; total allocated: 5 of 25[]
```

### Steps to reproduce

1. setup a 8.7 cluster **without RBA and without Multi-Tenancy** (this causes some 404s) and at least 5 users and Keycloak as IDP
2. migrate to 8.8 with identity migration enabled

### Current behavior

3. the migration will fail due to a timeout when trying to call management identity (e.g. on user authorizations or on tenants

note this is only possible for Keycloak setups, as there the likelihood of 404s are higher (e.g. you get a 404 for authorizations if they are disabled, for tenants as well ...)

### Expected behavior

3. it should just pass and not leak connections :) 

### Workaround

None possible, requires application side fix.

Alternatively enable RBA and Multi-Tenancy => this will prevent 404s from happening and thus the connection leakage

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by megglos**
## Description

This caused the migration app to eventually become stale and fail with a timeout, given enough 404s were encountered each causing one connection to leak, e.g. due to RBA disabled on management identity.

The default connection pool used allows to use 5 concurrent connections for the same route, so once 404s happened and subsequent request will eventually run into a timeout acquiring a connection, indicated by this log and a following 3 minute timeout:
```
endpoint lease request (3 MINUTES) [route: {}->[[[http://camunda-platform-identity:80](http://camunda-platform-identity/)](http://camunda-platform-identity/)]][total available:; route allocated: 5 of 5; total allocated: 5 of 25[]
```

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #39284

### CODE REVIEW

File: migration/identity-migration/src/main/java/io/camunda/migration/identity/config/ManagementIdentityConnectorConfig.java [hunk 1]
```diff
@@ -110,12 +110,14 @@ public class EndpointUnavailableInterceptor implements ClientHttpRequestIntercep
     public ClientHttpResponse intercept(
         final HttpRequest request, final byte[] body, final ClientHttpRequestExecution execution)
         throws IOException {
-      final var result = execution.execute(request, body);
-      if (result.getStatusCode() == HttpStatus.NOT_FOUND) {
+      final var response = execution.execute(request, body);
+      if (response.getStatusCode() == HttpStatus.NOT_FOUND) {
+        // the response needs to be closed as it won't be processed anymore due the exception thrown
+        response.close();
```
Comment (megglos) [inline migration/identity-migration/src/main/java/io/camunda/migration/identity/config/ManagementIdentityConnectorConfig.java:116]: this is the actual fix, the dedicated IT class `KeycloakIdentityMigrationNoRbaNoMultiTenancyIT` ensures we have the exact setup needed to trigger the leakage, being keycloak with RBA and MT disabled + at least 5 groups (without authorizations)

**Review by Ben-Sheppard — APPROVED** [review]
I was thinking about if we had to be so specific with catching the `NOT_FOUND` and rather if we encounter any non success code we would close the response.

Potentially something to think about in the future, for now I think this issue is better off merged like this to improve stability.

**Comment by megglos** [comment]
> I was thinking about if we had to be so specific with catching the `NOT_FOUND` and rather if we encounter any non success code we would close the response.
> 
> Potentially something to think about in the future, for now I think this issue is better off merged like this to improve stability.

In other cases it's done by the usual response handling chain. The issue here is that this interceptor is used to convert a 404 to this not implemented exception to be handled in the service/migration handler layer. By throwing an exception it causes the usual handling to never happen though, thus we have to take care of closing.
