### PR TITLE
Change to a get + put pattern to avoid deadlock.

### LINKED ISSUE #33941: Deadlock in registering/unregistering micrometer metrics
### 

### 

, , , 

### 

### 

### Description

There is a dead lock when removing and creating meters:

```
Found one Java-level deadlock:
=============================
"zb-actors-1":
  waiting to lock monitor 0x00007ab6d41dabb0 (object 0x00000000e7fc4558, a java.util.concurrent.ConcurrentHashMap$Node),
  which is held by "raft-server-1-5"

"raft-server-1-5":
  waiting to lock monitor 0x00007ab71407de00 (object 0x00000000e40053f0, a java.lang.Object),
  which is held by "zb-actors-1"

Java stack information for the threads listed above:
===================================================
"zb-actors-1":
	at java.util.concurrent.ConcurrentHashMap.replaceNode(java.base@21.0.7/Unknown Source)
	- waiting to lock <0x00000000e7fc4558> (a java.util.concurrent.ConcurrentHashMap$Node)
	at java.util.concurrent.ConcurrentHashMap.remove(java.base@21.0.7/Unknown Source)
	at io.camunda.zeebe.util.micrometer.StatefulMeterRegistry.onMeterRemoved(StatefulMeterRegistry.java:61)
	at io.camunda.zeebe.util.micrometer.StatefulMeterRegistry$$Lambda/0x00007ab7207baf10.accept(Unknown Source)
	at io.micrometer.core.instrument.MeterRegistry.remove(MeterRegistry.java:813)
	- locked <0x00000000e40053f0> (a java.lang.Object)
	at io.camunda.zeebe.broker.system.monitoring.HealthTreeMetrics.removeFromRegistry(HealthTreeMetrics.java:124)
	at io.camunda.zeebe.broker.system.monitoring.HealthTreeMetrics.unregisterNode(HealthTreeMetrics.java:64)
	at io.camunda.zeebe.scheduler.health.CriticalComponentsHealthMonitor.lambda$removeComponent$2(CriticalComponentsHealthMonitor.java:108)
	at io.camunda.zeebe.scheduler.health.CriticalComponentsHealthMonitor$$Lambda/0x00007ab7207df750.run(Unknown Source)
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:84)
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:43)
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127)
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104)
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224)
"raft-server-1-5":
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:670)
	- waiting to lock <0x00000000e40053f0> (a java.lang.Object)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:615)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:609)
	at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:350)
	at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:195)
	at io.camunda.zeebe.util.micrometer.StatefulGauge.registerAsGauge(StatefulGauge.java:120)
	at io.camunda.zeebe.util.micrometer.StatefulMeterRegistry.registerStatefulGauge(StatefulMeterRegistry.java:44)
	at io.camunda.zeebe.util.micrometer.StatefulMeterRegistry$$Lambda/0x00007ab7207f34f0.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(java.base@21.0.7/Unknown Source)
	- locked <0x00000000e7fc4558> (a java.util.concurrent.ConcurrentHashMap$Node)
	at io.camunda.zeebe.util.micrometer.StatefulMeterRegistry.registerIfNecessary(StatefulMeterRegistry.java:40)
	at io.camunda.zeebe.util.micrometer.StatefulGauge$Builder.register(StatefulGauge.java:222)
	at io.camunda.zeebe.util.micrometer.StatefulGauge$Builder.register(StatefulGauge.java:215)
	at io.atomix.raft.metrics.LeaderAppenderMetrics.<init>(LeaderAppenderMetrics.java:55)
	at io.atomix.raft.roles.LeaderAppender.<init>(LeaderAppender.java:85)
	at io.atomix.raft.roles.LeaderRole.<init>(LeaderRole.java:86)
	at io.atomix.raft.impl.RaftContext.createRole(RaftContext.java:808)
	at io.atomix.raft.impl.RaftContext.transition(RaftContext.java:727)
	at io.atomix.raft.roles.CandidateRole.lambda$sendVoteRequests$1(CandidateRole.java:123)
	at io.atomix.raft.roles.CandidateRole$$Lambda/0x00007ab720c67568.accept(Unknown Source)
	at io.atomix.raft.utils.SimpleVoteQuorum.checkComplete(SimpleVoteQuorum.java:64)
	at io.atomix.raft.utils.SimpleVoteQuorum.succeed(SimpleVoteQuorum.java:38)
	at io.atomix.raft.roles.CandidateRole.onVoteResponse(CandidateRole.java:234)
	at io.atomix.raft.roles.CandidateRole.lambda$sendVoteRequestToMember$3(CandidateRole.java:205)
	at io.atomix.raft.roles.CandidateRole$$Lambda/0x00007ab720c67c08.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@21.0.7/Unknown Source)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@21.0.7/Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(java.base@21.0.7/Unknown Source)
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:183)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@21.0.7/Unknown Source)
	at java.util.concurrent.FutureTask.run(java.base@21.0.7/Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@21.0.7/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@21.0.7/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@21.0.7/Unknown Source)
	at io.atomix.utils.concurrent.AtomixThreadFactory.lambda$newThread$0(AtomixThreadFactory.java:46)
	at io.atomix.utils.concurrent.AtomixThreadFactory$$Lambda/0x00007ab720625390.run(Unknown Source)
	at java.lang.Thread.runWith(java.base@21.0.7/Unknown Source)
	at java.lang.Thread.run(java.base@21.0.7/Unknown Source)
```

### Steps to reproduce

Unclear as it's a concurrency related issue

### Current behavior

Two threads (of the same partition, but it remains to be verified) are in deadlock, making the processing on the partition unable to continue.

### Expected behavior

No deadlock

### Environment

SaaS & SM

### Version

- Component 8.8.0-SNAPSHOT

### Rootcause
The deadlock is caused by the callback `onMeterRemoved`:
```java
  StatefulMeterRegistry(final MeterRegistry parent) {
    super(parent.config().clock(), Collections.singleton(parent));
    config().onMeterAdded(this::onMeterAdded).onMeterRemoved(this::onMeterRemoved);
  }
```
It should probably be run in another/when the other lock is already released
### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

This PR changes to a get() + put() pattern in StatefulGauge.registerIfNecessary() instead of a computIfAbsent() to avoid a deadlock.

See explanation in comment https://github.com/camunda/camunda/issues/33941#issuecomment-3965969887

This issue was also observed in the following support case: [#inc-support-31666-zeebe-partitions-unhealthy](https://camunda.slack.com/archives/C0AGR3G0PUM).

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes https://github.com/camunda/camunda/issues/33941

### CODE REVIEW

File: zeebe/util/src/main/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistry.java [hunk 1]
```diff
@@ -39,7 +39,17 @@ final class StatefulMeterRegistry extends CompositeMeterRegistry {
   }
 
   StatefulGauge registerIfNecessary(final Id id, final Builder builder) {
-    return gauges.computeIfAbsent(id, metricId -> registerStatefulGauge(metricId, builder));
+    // NOTE: We intentionally use get() + put() instead of computeIfAbsent() here.
+    // Using computeIfAbsent() could cause a deadlock, see issue
+    // https://github.com/camunda/camunda/issues/33941#issuecomment-3965969887
+    final var existing = gauges.get(id);
```
Comment (entangled90) [inline zeebe/util/src/main/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistry.java:45]: ❌ this might produce a wrong result a `get + put` is not the same as computeIfAbsent.
If another threads inserts a gauge befor the `put` then its gauge will be removed from the map, without that thread knowing it. 

You should use `putIfAbsent` and then return the gauge that's actually in the map (which might not be the one you created just now).

I'm not entirely sure if this will remove the deadlock.

**Comment by megglos** [comment]
@rodrigo-lourenco-lopes this needs backporting all the way to 8.6, right?

**Review by entangled90 — CHANGES_REQUESTED** [review]

**Comment by entangled90** [comment]
Note that in `MeterRegistry.getOrCreateMeter` it uses a `synchronized(meterMapLock)` so it never releases the lock

**Comment by entangled90** [comment]
I'd say that if you do as you tried with `putIfAbsent` and you create the gauge outside of the map lock, then it should be fine. 
Make sure to return the right gauge (the one in the map)

**Comment by rodrigo-lourenco-lopes** [comment]
Using the put if absent avoids the lock as well (testing locally with the tests mentioned above) and prevents sending the new meter if one was registered in between.

**Comment by rodrigo-lourenco-lopes** [comment]
Ups putIfAbsent returns null if there was no key before, will fix.

**Review by entangled90 — COMMENTED** [review]
Thanks. 
I'd like to have a test for this to be sure it works and to avoid any regressions later on.

**Comment by rodrigo-lourenco-lopes** [comment]
I will clean up the test that I was using locally to test this 👍

File: zeebe/util/src/test/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistryTest.java [hunk 2]
```diff
@@ -45,4 +58,122 @@ void shouldReturnSameStatefulGauge() {
...
+                  }
+                },
+                executor));
+      }
+
+      try {
+        // Wait for all futures to complete
+        final var allFutures = CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]));
+        // This will throw a TimeoutException if the deadlock occurs
+        allFutures.get();
```
Comment (entangled90) [inline zeebe/util/src/test/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistryTest.java:109]: ❓ is there a timeout if you just use `.get()`? If you specify a timeout it's more reliable?

Comment (rodrigo-lourenco-lopes) [reply zeebe/util/src/test/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistryTest.java:109]: Yes, the comment is incorrect, I forced pushed immediately after noticing it was still there 😓 In the previous version, I did have a timeout specified, but it did not work, since synchronized blocks are not interruptible by setting the timeout there. My previous tests were much simpler where the test just hanged forever instead of failing after 5 seconds.

**Comment by entangled90** [comment]
So you were able to reproduce the deadlock with the test?

**Comment by rodrigo-lourenco-lopes** [comment]
Yes yes, with the old code blocks every time. I just meant that the comment was a leftover from a previous iteration.

**Review by entangled90 — APPROVED** [review]
Thank you 🚀

File: zeebe/util/src/test/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistryTest.java [hunk 3]
```diff
@@ -45,4 +58,120 @@ void shouldReturnSameStatefulGauge() {
     assertThat(second).isSameAs(first);
     assertThat(second.value()).isOne();
   }
+
+  /** See issue: <a href="https://github.com/camunda/camunda/issues/33941">...</a> */
+  @Test
+  @Timeout(value = 5, unit = TimeUnit.SECONDS)
```
Comment (entangled90) [inline zeebe/util/src/test/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistryTest.java]: ❓ isn't this timeout a bit too short? Shall we set it to like 30s?

File: zeebe/util/src/test/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistryTest.java (hunk 2 above)
Comment (entangled90) [reply zeebe/util/src/test/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistryTest.java:109]: Ok so we should set a timeout smaller than the test timeout outside?

**Comment by entangled90** [comment]
Check my comments before merging though :smile:

File: zeebe/util/src/test/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistryTest.java (hunk 3 above)
Comment (rodrigo-lourenco-lopes) [reply zeebe/util/src/test/java/io/camunda/zeebe/util/micrometer/StatefulMeterRegistryTest.java]: The test completes in less than 300ms (on my machine), even if the other machines are slower it should be fine, but I can increase it yes 👍
