### PR TITLE
test: ensure PI modify moveAll works for MI subs

### LINKED ISSUE #44955: Moving tokens out of multi-instance subprocess does not combine the tokens
### 

### 

### 

### 

### Description

While testing single process-instance modifications in Operate against the relevant [Orchestration Cluster API endpoint](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/modify-process-instance/), we noticed that a "Move All" modification on tokens in a multi-instance subprocess does not combine the tokens if they are moved out of the multi-instance. The old v1 endpoint caused the tokens to be combined.

**Note:** This bug has been observed for multi-instance subprocesses. The behavior should also be checked for single multi-instance activities that do not have nested element.

### Steps to reproduce

1. Have a local version of Camunda with the Operate running
2. Open an instance of the "Multi-Instance Process" process
3. Enter modification mode
4. Select the "Filter" element and choose the "Move All" modification
5. Select the "Peter Fork" element as the move target
6. Finish the modification

_Note: that the UI does correctly display the tokens count at the target for the modification. It would likely require simulating the engine itself. In both version it displays 3 tokens at the move target, even though the engine should only move one token out of the multi-instance._

### Current behavior

The process instance is successfully modified. After a short time, 9 tokens appear at the "Peter case task". Reason for 9:
- 3 tokens are moved out of the multi-instance subprocess but **not** combined again
- Each token is split into 3 at the Peter fork
- 3 x 3 = 9

### Expected behavior

The 3 tokens moved out of multi-instance subprocess should be combined into a single token again. After a while 3 tokens (due to the Peter fork) should be appearing at the "Peter case task".

### Workaround

No known workaround

### Environment

SM

### Version

- Orchestration Cluster API: latest `main` version
- Operate App: latest `main` version

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

Improves the handling of process instance modifications involving multi-instance (MI) elements. The main focus is to ensure that when moving elements out of or within MI sub-processes, activation instructions are deduplicated so that only one activation per MI body and ancestor scope is created, preventing redundant activations. The changes also introduce new tests to verify this behavior.

## Related issues

closes #44955

### CODE REVIEW

**Comment by tmetzke** [comment]
@copilot, can you fix the engine behavior so the new test case no longer fails and all other tests still pass? Apparently, the engine doesn't consider the multi-instance sub-process parent correctly in the ProcessInstanceModificationModifyProcessor. This works well if the multi-instance marker is on a single activity, and all its tokens are moved at once by element ID.

**Comment by tmetzke** [comment]
@mustafadagher, could you have a look at this one, maybe? You're the one with most context here, I believe 😅

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 1]
```diff
@@ -482,17 +486,26 @@ private void mapIdInstructions(
...
+                new ProcessInstanceModificationActivateInstruction()
+                    .setElementId(moveInstruction.getTargetElementId())
+                    .setAncestorScopeKey(ancestorScopeKey);
+            moveInstruction
+                .getVariableInstructions()
+                .forEach(
+                    vi ->
+                        activateInstruction.addVariableInstruction(
+                            (ProcessInstanceModificationVariableInstruction) vi));
+            finalActivateInstructions.add(activateInstruction);
```
[the remark this answers is not in the document]
Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]: Huh, what an edge case, but true. You could have a parallel split inside the MI subprocess, and move all tokens on both parallel paths to the next activity on that path. I'll create a test case 👍

[the remark this answers is not in the document]
Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]: @copilot+gpt-5.3-codex, create a test case for this and fix the code accordingly. Ensure the existing tests for modification still pass after your changes.

**Comment by tmetzke** [comment]
@mustafadagher, done from my end. Maybe you can give this a look today or on Monday?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 2]
```diff
@@ -482,17 +486,30 @@ private void mapIdInstructions(
...
-                  .setAncestorScopeKey(ancestorScopeKey);
-          moveInstruction
-              .getVariableInstructions()
-              .forEach(
-                  vi ->
-                      activateInstruction.addVariableInstruction(
-                          (ProcessInstanceModificationVariableInstruction) vi));
-          finalActivateInstructions.add(activateInstruction);
+          // Check whether this element instance is inside a multi-instance body. If so, deduplicate
+          // only when the resolved target ancestor scope is identical.
```
Comment (tmetzke) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]: 🔧 Comment isn't completely correct. We're using the move instruction's `source` as an indicator.
```suggestion
          // only when the source is identical, so elements are moved only once.
```

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 3]
```diff
@@ -2313,7 +2418,263 @@ public void shouldMoveAllMultiInstanceParentElementsByIds() {
             tuple(
                 BpmnElementType.MULTI_INSTANCE_BODY, "A", ProcessInstanceIntent.ELEMENT_TERMINATED),
             tuple(BpmnElementType.USER_TASK, "B", ProcessInstanceIntent.ELEMENT_ACTIVATED),
-            tuple(BpmnElementType.USER_TASK, "B", ProcessInstanceIntent.ELEMENT_ACTIVATED));
+            tuple(BpmnElementType.USER_TASK, "B", ProcessInstanceIntent.ELEMENT_ACTIVATED),
+            tuple(BpmnElementType.USER_TASK, "B", ProcessInstanceIntent.ELEMENT_TERMINATED),
+            tuple(BpmnElementType.USER_TASK, "B", ProcessInstanceIntent.ELEMENT_TERMINATED));
```
Comment (tmetzke) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:2553]: ℹ️ This ensures we activate exactly two times and not more often without noticing.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 4]
```diff
@@ -2230,7 +2231,110 @@ public void shouldMoveAllMultiInstanceElementsByIds() {
             tuple(BpmnElementType.USER_TASK, "A", ProcessInstanceIntent.ELEMENT_TERMINATED),
             tuple(
                 BpmnElementType.MULTI_INSTANCE_BODY, "A", ProcessInstanceIntent.ELEMENT_TERMINATED),
-            tuple(BpmnElementType.USER_TASK, "B", ProcessInstanceIntent.ELEMENT_ACTIVATED));
+            tuple(BpmnElementType.USER_TASK, "B", ProcessInstanceIntent.ELEMENT_ACTIVATED),
+            tuple(BpmnElementType.USER_TASK, "B", ProcessInstanceIntent.ELEMENT_TERMINATED));
```
Comment (tmetzke) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:2235]: ℹ️ This ensures we activate exactly once and not more often without noticing.

**Comment by mustafadagher** [comment]
> @mustafadagher, done from my end. Maybe you can give this a look today or on Monday?

I'll take a look on Monday, if it can wait 🙏

**Comment by tmetzke** [comment]
That should be fine, I think. Should go into 8.9.0, but doesn't have to be today 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 5]
```diff
@@ -2201,6 +2201,7 @@ public void shouldMoveAllMultiInstanceElementsByIds() {
         .modification()
         .moveElements("A", "B")
         .modify();
+    ENGINE.processInstance().withInstanceKey(processInstanceKey).cancel();
```
Comment (mustafadagher) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:2204]: 👍
nice, makes sense to cancel to be able to deterministically limit!

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 6]
```diff
@@ -649,6 +686,29 @@ private long findProperAncestorScopeKeyForTarget(
...
+      if (instance == null) {
+        break;
+      }
+      if (instance.getValue().getBpmnElementType() == BpmnElementType.MULTI_INSTANCE_BODY) {
+        return currentKey;
+      }
+      currentKey = instance.getParentKey();
+    }
+    return -1;
+  }
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:710]: 🔧 I think it's better to replace the recursion here with an iterative approach (using queues) to avoid out of memory exceptions

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 7]
```diff
@@ -530,17 +577,7 @@ private void mapMoveInstructionsByInstanceKey(
       final var ancestorScopeKey =
           determineAncestorScopeKey(moveInstruction, elementInstance.getParentKey(), process);
 
-      final var activateInstruction =
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:533]: ❓ what happens if we move 3 instances of the same element from the same multi-instance body instance to the same target now one by one using the key?

will it not cause the same issue?

---

**UPDATE:**
Thinking about this again, there can't be 3 element instances of the same element within the same multi-instance body instance :D There can be only one in each, unless the element itself is a multi-instance element

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java [hunk 8]
```diff
@@ -2337,6 +2337,136 @@ public void shouldMoveAllMultiInstanceElementsOutOfSubprocessByIds() {
             tuple(BpmnElementType.USER_TASK, "B", ProcessInstanceIntent.ELEMENT_TERMINATED));
   }
 
+  @Test
+  public void shouldMoveAllMultiInstanceElementsOutOfNestedSubprocessByIds() {
```
Comment (mustafadagher) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:2341]: I wrote this test locally to verify it also works with nested subprocesses, and I thought it makes sense to push it as well

**Review by mustafadagher — APPROVED** [review]
Thanks @tmetzke 👍 It looks good to me 🚀 
🔧 I left one suggestion regarding changing recursion to iteration, please consider it

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java (hunk 5 above)
Comment (tmetzke) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:2204]: 🚀

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java (hunk 6 above)
Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:710]: Yeah, you're right, that will become nasty pretty quick otherwise for nested sub-processes 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java (hunk 8 above)
Comment (tmetzke) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTest.java:2341]: Awesome, good idea, love it 👍 🫶

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java (hunk 7 above)
Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:533]: Overall, there might always be another edge case here. Modification is complex and ugly. We'll never catch them all, I believe 😅

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java (hunk 6 above)
Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:710]: Coming back to this, isn't this iterative already? We don't do recursion here, do we? 🤔
Do you have a concrete code suggestion in mind to improve this?

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:710]: oh! I think I was too tired when I wrote this! You're right!

Comment (tmetzke) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:710]: No worries, I had to look at it twice again as well to understand it's not recursing, actually. This is better than having it slip through 👍
