### PR TITLE
fix: retry on other partitions for process instance creation in REST API

### LINKED ISSUE #46756: Partition retry inconsistency between gRPC and REST gateways for process instance creation
### 

### 

, , , 

### 

### 

### Description

There is an inconsistency between the gRPC and REST gateways in how process instance creation (and creation with result) are retried in the event of partition-related failures.

**gRPC gateway behavior:**
In the gRPC gateway (`EndpointManager.java`), the `createProcessInstance` and `createProcessInstanceWithResult` requests are sent via `sendRequestWithRetryPartitions`, which uses `RequestRetryHandler`. This handler retries the request on different partitions when certain transient errors occur. Specifically, the following errors are considered retriable (see `shouldRetryWithNextPartition()` in `RequestRetryHandler`):

- **`ConnectException`** — the partition leader is unreachable (e.g., network failure, node down)
- **`BrokerErrorException` with `ErrorCode.PARTITION_LEADER_MISMATCH`** — the targeted broker is no longer the leader for the partition
- **`BrokerErrorException` with `ErrorCode.RESOURCE_EXHAUSTED`** — the partition's resources are exhausted (e.g., backpressure)

When any of these errors occur, the gRPC gateway automatically retries the request on the next available partition (round-robin), iterating through all partitions before giving up with a `RequestRetriesExhaustedException`.

**REST gateway behavior:**
The REST gateway (`ProcessInstanceServices.java`) uses `ApiServices.sendBrokerRequest()`, which calls `brokerClient.sendRequest()` directly. This does **not** perform any partition-level retry logic — if the request fails with any of the above retriable errors, the failure is immediately propagated to the caller.

According to the discussion in [PR #46554](https://github.com/camunda/camunda/pull/46554#discussion_r2847260674), this was likely an oversight when the REST gateway was originally implemented.

**Relevant files:**
- [`EndpointManager.java`](https://github.com/camunda/camunda/blob/main/zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/EndpointManager.java) — gRPC gateway, uses `RequestRetryHandler` for process instance creation
- [`RequestRetryHandler.java`](https://github.com/camunda/camunda/blob/main/zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/broker/RequestRetryHandler.java) — implements partition retry logic with `shouldRetryWithNextPartition()`
- [`ProcessInstanceServices.java`](https://github.com/camunda/camunda/blob/main/service/src/main/java/io/camunda/service/ProcessInstanceServices.java) — REST gateway, uses `sendBrokerRequest()` without partition retry
- [`ApiServices.java`](https://github.com/camunda/camunda/blob/main/service/src/main/java/io/camunda/service/ApiServices.java) — base class, `sendBrokerRequest()` calls `brokerClient.sendRequest()` directly

**Discussion:**
- https://github.com/camunda/camunda/pull/46554#discussion_r2845914481

### Steps to reproduce

1. Attempt to create a process instance via the REST gateway (`ProcessInstanceServices`).
2. Simulate a partition failure (e.g., shutting down a partition leader to trigger a `ConnectException` or `PARTITION_LEADER_MISMATCH`).
3. Observe that the REST gateway does not retry on other partitions, while the gRPC gateway does.

### Current behavior

REST gateway fails process instance creation and does not retry across partitions. gRPC gateway retries on different partitions in the event of failures.

### Expected behavior

REST gateway should implement partition retry logic similar to the gRPC gateway, using a retry handler (e.g., `RequestRetryHandler`). When `createProcessInstance` or `createProcessInstanceWithResult` fails with a `ConnectException`, `PARTITION_LEADER_MISMATCH`, or `RESOURCE_EXHAUSTED` error, the request should be retried on a different partition, consistent with gRPC gateway behavior.

### Workaround

- Use the gRPC gateway if partition retry behavior is required.
- No workaround exists for REST gateway users.

### Environment

SaaS & SM

### Version

- Component Version: [e.g. 8.8]
- REST Gateway Version: [specify if known]
- gRPC Gateway Version: [specify if known]

### Rootcause

Based on code review and the GitHub discussion, the omission of partition retry logic in the REST gateway appears to be an oversight during initial implementation.

### Solution ideas

- Refactor the REST gateway (`ProcessInstanceServices`) to apply partition retry logic for `createProcessInstance` and `createProcessInstanceWithResult`, similar to the gRPC gateway's `RequestRetryHandler`.
- Consider reusing or adapting the existing `RequestRetryHandler` to be shared between gRPC and REST gateways, to avoid duplicating retry logic.
- Ensure the same set of retriable errors (`ConnectException`, `PARTITION_LEADER_MISMATCH`, `RESOURCE_EXHAUSTED`) trigger retries on both gateways.

### Dev -> QA handover

_No response_

### Links

- https://github.com/camunda/camunda/pull/46554#discussion_r2845914481

### Automated Test Impact

REST gateway test cases may be missing coverage for partition failure and retry scenarios. Add/modify automated tests to cover this case.

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description

Fixes a partition retry inconsistency between the gRPC and REST gateways for process instance creation.

### Problem

The REST gateway (`ProcessInstanceServices`) used `ApiServices.sendBrokerRequest()` to handle `createProcessInstance` and `createProcessInstanceWithResult` requests. This method calls `brokerClient.sendRequest()` directly and does **not** perform any partition-level retry logic — if the request fails due to a transient partition error, the failure is immediately propagated to the caller.

In contrast, the gRPC gateway (`EndpointManager`) uses `sendRequestWithRetryPartitions` via `RequestRetryHandler`, which automatically retries requests on different partitions when certain transient errors occur:
- **`ConnectException`** — partition leader unreachable
- **`PARTITION_LEADER_MISMATCH`** — targeted broker is no longer the leader
- **`RESOURCE_EXHAUSTED`** — partition under backpressure

This inconsistency was identified as an oversight during the original REST gateway implementation (see [discussion](https://github.com/camunda/camunda/pull/46554#discussion_r2845914481)).

### Solution

This PR introduces `sendRequestWithRetryPartitions` to the `ProcessInstanceServices` base class, reusing the existing `RequestRetryHandler` from the gateway module. The method is provided in two overloads (with and without a custom request timeout), matching the existing `sendBrokerRequest` signatures.

`ProcessInstanceServices.createProcessInstance` and `createProcessInstanceWithResult` are updated to use `sendRequestWithRetryPartitions` instead of `sendBrokerRequest`, making the REST API path consistent with the gRPC gateway behavior.

## Related issues

closes #46756

### CODE REVIEW

File: service/src/main/java/io/camunda/service/ProcessInstanceServices.java [hunk 1]
```diff
@@ -434,6 +443,47 @@ public SearchQueryResult<IncidentEntity> searchIncidents(
...
+    return responseFuture.handleAsync(
+        (response, error) -> {
+          if (error != null) {
+            throw ErrorMapper.mapError(error);
+          }
+          return response;
+        },
+        executor);
+  }
+
```
Comment (tmetzke) [inline service/src/main/java/io/camunda/service/ProcessInstanceServices.java:478]: 💭 How about we move this to the `ApiServices`, next to the other `sendBrokerRequest...` methods and align them?
🔧 There's a bit of code duplication going on here. Maybe we can reduce it.
🔧 I believe the response handling also derails from what the send broker request methods usually do in `ApiServices`. If we move these two there, you'll see it immediately.

Comment (mustafadagher) [reply service/src/main/java/io/camunda/service/ProcessInstanceServices.java:478]: Initially I had it in `ApiServices`. Tests from `TopologyServiceTest` failed because of the extra calls to `topology manager and get topology`
I could fix the tests, but it looked hacky.

The only place is is used anywhere is for the specific case of process instance creation, so it made sense to keep it here.

>I believe the response handling also derails from what the send broker request methods usually do in ApiServices. If we move these two there, you'll see it immediately.

Actually, what the `ApiServices ` does in `handleBrokerResponse` is unnecessary. If you look at `BrokerRequestManager`'s `handleResponse()`, it already maps the error responses and rejection to exceptional futures. 

>🔧 There's a bit of code duplication going on here. Maybe we can reduce it.

I pushed a change to reduce the duplication a bit.

Comment (mustafadagher) [reply service/src/main/java/io/camunda/service/ProcessInstanceServices.java:478]: >Tests from TopologyServiceTest failed because of the extra calls to topology manager and get topology

💭 I could still move the methods back to APIServices, and make the instantiation of `requestRetryHandler` lazy (only on the first call that needs it). This way, there will no need to introduce any changes to topology tests. 
🤔 But we never use these methods anywhere else anyway. so do we really need to move them?
WDYT?

Comment (tmetzke) [reply service/src/main/java/io/camunda/service/ProcessInstanceServices.java:478]: >Initially I had it in ApiServices. Tests from TopologyServiceTest failed because of the extra calls to topology manager and get topology
I could fix the tests, but it looked hacky.

Not sure I understand how moving the methods to the parent class created those test failures. I'd have to see it to grasp it, maybe 😅 

> The only place is is used anywhere is for the specific case of process instance creation, so it made sense to keep it here.

That's generally fine, I agree. As soon as we need it in another place, though, I'm sure we'll miss this exists already and create it again in another service class 😅
Not a hard requirement, of course, but I just think it would make more sense to have those methods in one place.

> Actually, what the ApiServices  does in handleBrokerResponse is unnecessary. If you look at BrokerRequestManager's handleResponse(), it already maps the error responses and rejection to exceptional futures.

True, you never stop learning 😄
I guess removing this from those methods will fail a couple of tests that mock broker rejection and error responses from the broker client, although in reality it (currently) doesn't do that.

Comment (mustafadagher) [reply service/src/main/java/io/camunda/service/ProcessInstanceServices.java:478]: >Not sure I understand how moving the methods to the parent class created those test failures. I'd have to see it to grasp it, maybe 😅



In the constructor I had 
```java
requestRetryHandler = new RequestRetryHandler(brokerClient, brokerClient.getTopologyManager());
``` 
Which makes a call to `getTopologyManager()`;

In all Topology tests we verify that `getTopologyManager` is only called once in `verify(brokerClient).getTopologyManager();`

Hence the suggestion above.

Comment (tmetzke) [reply service/src/main/java/io/camunda/service/ProcessInstanceServices.java:478]: Saw your second reply too late 😅 

Nah, all good, no hard requirement, as I said.

Comment (mustafadagher) [reply service/src/main/java/io/camunda/service/ProcessInstanceServices.java:478]: >I guess removing this from those methods will fail a couple of tests that mock broker rejection and error responses from the broker client, although in reality it (currently) doesn't do that.

Maybe it's worth doing actually, to remove confusion. I'd not do it as part of this PR though.

**Review by tmetzke — APPROVED** [review]
👍 Let's roll with this, thanks for porting this to the REST gateway!

File: service/src/main/java/io/camunda/service/ProcessInstanceServices.java (hunk 1 above)
Comment (tmetzke) [reply service/src/main/java/io/camunda/service/ProcessInstanceServices.java:478]: Yep, I agree. Should be a follow-up, though. A small comment in the result handler will be nice, too. Making sure we don't fall into this trap again 😅
