### PR TITLE
Prevent canceling of element instances

### LINKED ISSUE #1790: I can cancel an element instance with the cancel workflow instance API
With the cancel workflow instance command every element instance can be canceled.
If for example an job is canceled the workflow instance is still active but broken. :man_shrugging: 
I think this is not intended.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
closes #1790

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/workflow/CancelWorkflowInstanceTest.java [hunk 1]
```diff
@@ -127,4 +127,39 @@ public void shouldFailToCompleteJobAfterCancel() {
...
+    // given
+    clientRule
+        .getClient()
+        .newCreateInstanceCommand()
+        .bpmnProcessId("process")
+        .latestVersion()
+        .send()
+        .join();
+
+    final List<ActivatedJob> jobEvents = new ArrayList<>();
```
Comment (saig0) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/workflow/CancelWorkflowInstanceTest.java]: We don't need jobs here. Just use the `RecordingExporter` and get any `WorkflowInstanceRecord`.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/workflow/CancelWorkflowInstanceTest.java [hunk 2]
```diff
@@ -127,4 +127,39 @@ public void shouldFailToCompleteJobAfterCancel() {
     assertJobCanceled();
     assertWorkflowInstanceCanceled("process");
   }
+
+  @Test
+  public void shouldNotCancelJob() {
```
Comment (saig0) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/workflow/CancelWorkflowInstanceTest.java]: I'm confused about the test name.

File: broker-core/src/main/java/io/zeebe/broker/workflow/processor/instance/CancelWorkflowInstanceHandler.java [hunk 3]
```diff
@@ -28,27 +28,39 @@
 
 public class CancelWorkflowInstanceHandler implements WorkflowInstanceCommandHandler {
 
+  public static final String ERROR_MSG_CHILD_INSTANCE =
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/workflow/processor/instance/CancelWorkflowInstanceHandler.java]: Do you need the error message to be `public`?

**Review by saig0 — CHANGES_REQUESTED** [review]

**Review by saig0 — APPROVED** [review]
