### PR TITLE
Remove priority scheduling for actors

### LINKED ISSUE #9453: ArrayIndexOutOfBoundsException at PriorityScheduler$Run.getTimeSlicePriority
**Describe the bug**
We observed the following error message in the logs:

```
Unexpected error occurred while in the actor thread Broker-0-zb-actors-0
```

With the following exception:

```
ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 100
```
  
The failure is caused by `PriorityScheduler$Run.getTimeSlicePriority`.

We didn't observe any negative impact. It seems that the broker continued as normal.

**To Reproduce**

Unclear. 

**Expected behavior**

No failure occurred. 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 100
	at io.camunda.zeebe.util.sched.PriorityScheduler$Run.getTimeSlicePriority(PriorityScheduler.java:122) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.PriorityScheduler.getNextTask(PriorityScheduler.java:91) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:76) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.0.jar:8.0.0]
```

</p>
</details>

[Logs](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.namespace_name%3D%22be0bf678-a7d7-4ef0-8e05-db31878d499a-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;timeRange=2022-05-25T16:19:43.465Z%2F2022-05-25T17:19:43.465Z;pinnedLogId=2022-05-25T16:49:13.465734995Z%2Fb5kbqxui68cmvkw9;cursorTimestamp=2022-05-25T16:49:39.563769499Z?project=camunda-cloud-240911)
[Error Reporting](https://console.cloud.google.com/errors/detail/CL6_tYD4gpK80QE;service=zeebe;time=P7D?project=camunda-cloud-240911)

**Environment:**
- OS: Camunda Cloud 
- Zeebe Version: 8.0.0
- Configuration: Cluster plan G3-Trial

### PR DESCRIPTION
**Pull request by lenaschoenburg**
* This removes the concept of priority scheduling from the actor scheduler. Priority scheduling wasn't used, all actors shared the same priority.
* This doesn't affect work stealing, it just makes it simpler because we don't have to maintain multiple task queues per thread.
* The separation of IO and CPU bound actors is maintained but the scheduling hints are implemented a little bit different now because they aren't part of the priority bitfield anymore.

closes https://github.com/camunda/zeebe/issues/9453

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java [hunk 1]
```diff
@@ -67,7 +68,8 @@ public ActorFuture<Void> transitionTo(
                 snapshotPeriod);
       }
 
-      final var future = context.getActorSchedulingService().submitActor(director);
+      final var future =
+          context.getActorSchedulingService().submitActor(director, SchedulingHints.ioBound());
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java:72]: :wrench: I guess we learned from our recent discussion that the director doesn't need to be an IO-bound actor, but the SnapshotStore. I would suggest not to mark here the director as io bound.

File: util/src/main/java/io/camunda/zeebe/util/sched/ActorScheduler.java [hunk 2]
```diff
@@ -52,19 +50,15 @@ public ActorFuture<Void> submitActor(final Actor actor) {
...
-    if (SchedulingHints.isCpuBound(schedulingHints)) {
-      task.setPriority(SchedulingHints.getPriority(schedulingHints));
-      startingFuture = actorTaskExecutor.submitCpuBound(task);
-    } else {
-      startingFuture = actorTaskExecutor.submitIoBoundTask(task);
-    }
-    return startingFuture;
+    return switch (schedulingHints) {
+      case CPU_BOUND -> actorTaskExecutor.submitCpuBound(task);
+      case IO_BOUND -> actorTaskExecutor.submitIoBoundTask(task);
```
Comment (Zelldon) [inline util/src/main/java/io/camunda/zeebe/util/sched/ActorScheduler.java:60]: :question: what happens on default here? Or will this break the compiling if new type is added?

We could also just have two methods `submitIOBoundActor` and `submitActor` :shrug:

File: util/src/main/java/io/camunda/zeebe/util/sched/ActorScheduler.java [hunk 3]
```diff
@@ -104,7 +98,6 @@ public static ActorSchedulerBuilder newActorScheduler() {
   }
 
   public static class ActorSchedulerBuilder {
-    private final double[] priorityQuotas = new double[] {0.60, 0.30, 0.10};
```
Comment (Zelldon) [inline util/src/main/java/io/camunda/zeebe/util/sched/ActorScheduler.java:107]: :magic_wand:

File: util/src/main/java/io/camunda/zeebe/util/sched/ActorTask.java [hunk 4]
```diff
@@ -63,7 +59,6 @@ public ActorTask(final Actor actor) {
   /** called when the task is initially scheduled. */
   public ActorFuture<Void> onTaskScheduled(
       final ActorExecutor actorExecutor, final ActorThreadGroup actorThreadGroup) {
-    this.actorExecutor = actorExecutor;
```
Comment (Zelldon) [inline util/src/main/java/io/camunda/zeebe/util/sched/ActorTask.java:66]: :wrench: Can we remove the related parameter as well?

File: util/src/main/java/io/camunda/zeebe/util/sched/ActorThread.java [hunk 5]
```diff
@@ -74,19 +74,14 @@ private void doWork() {
       timerJobQueue.processExpiredTimers(clock);
     }
 
-    currentTask = taskScheduler.getNextTask(clock);
```
Comment (Zelldon) [inline util/src/main/java/io/camunda/zeebe/util/sched/ActorThread.java:77]: :+1:

File: util/src/main/java/io/camunda/zeebe/util/sched/ActorThread.java [hunk 6]
```diff
@@ -74,19 +74,14 @@ private void doWork() {
...
     if (currentTask != null) {
-      try {
-        final var actorName = currentTask.actor.getName();
-        try (final var timer = actorMetrics.startExecutionTimer(actorName)) {
-          executeCurrentTask();
-        }
-        actorMetrics.countExecution(actorName);
-
-      } finally {
-        taskScheduler.onTaskReleased(currentTask);
```
Comment (Zelldon) [inline util/src/main/java/io/camunda/zeebe/util/sched/ActorThread.java:88]: :question: What does this do before? :thinking:

File: util/src/main/java/io/camunda/zeebe/util/sched/ActorThreadGroup.java [hunk 7]
```diff
@@ -19,66 +19,46 @@
 public abstract class ActorThreadGroup {
   protected final String groupName;
   protected final ActorThread[] threads;
-  protected final MultiLevelWorkstealingGroup tasks;
```
Comment (Zelldon) [inline util/src/main/java/io/camunda/zeebe/util/sched/ActorThreadGroup.java:22]: :rocket:

File: util/src/main/java/io/camunda/zeebe/util/sched/WorkStealingGroup.java [hunk 8]
```diff
@@ -12,7 +12,7 @@
 import java.util.concurrent.ThreadLocalRandom;
 
 /** Workstealing group maintains a queue per thread. */
-public final class WorkStealingGroup {
+public final class WorkStealingGroup implements TaskScheduler {
```
Comment (Zelldon) [inline util/src/main/java/io/camunda/zeebe/util/sched/WorkStealingGroup.java:15]: :question: Just so I get it right, we have no longer an Io nor CpuScheduler. The WorkStealingGroup does this right? Maybe we should give it a better name.

**Review by ChrisKujawa — COMMENTED** [review]
Big kudos to you @oleschoenburg :medal_military: one of the few people who ever contributed to the ActorScheduler :grin: 

Just for visibility and for the posterity:

@deepthidevaki brought up whether we might need that for the RAFT migration. We together concluded that currently, we see no need for it, since we already have high timeouts on the RAFT implementation and the observed queue lengths are manageable, so with work stealing it should still be possible to send heartbeats on time. Let's see how it works when we really migrate it, we still can either bring that feature back OR add a separate scheduling group as mentioned by you.

**Review by ChrisKujawa — APPROVED** [review]
Github published my comment to early :fast_forward:

File: util/src/main/java/io/camunda/zeebe/util/sched/ActorScheduler.java (hunk 2 above)
Comment (oleschoenburg) [reply util/src/main/java/io/camunda/zeebe/util/sched/ActorScheduler.java:60]: Yes, that'd be an error. It's exhaustive matching :heart_eyes: 

> We could also just have two methods submitIOBoundActor and submitActor

True! I like this api so unless you feel strongly about it I'd leave it as is.

Comment (Zelldon) [reply util/src/main/java/io/camunda/zeebe/util/sched/ActorScheduler.java:60]: Great I love compile errors :)

File: util/src/main/java/io/camunda/zeebe/util/sched/ActorThread.java (hunk 6 above)
Comment (oleschoenburg) [reply util/src/main/java/io/camunda/zeebe/util/sched/ActorThread.java:88]: Nothing! :smile: There was only an empty default implementation in `TaskScheduler`

Comment (Zelldon) [reply util/src/main/java/io/camunda/zeebe/util/sched/ActorThread.java:88]: :see_no_evil:

File: util/src/main/java/io/camunda/zeebe/util/sched/WorkStealingGroup.java (hunk 8 above)
Comment (oleschoenburg) [reply util/src/main/java/io/camunda/zeebe/util/sched/WorkStealingGroup.java:15]: Yes, that's right. Ultimately, both the IO and CPU schedulers already delegated to `WorkStealingGroup`'s `getNextTask` so this is essentially just removing indirection. Regarding naming: I feel like this is one of the few cases in the actor scheduler where the naming is spot on. Let me elaborate:

`WorkStealingGroup` is a just a collection of tasks that are available to an `ActorThreadGroup` (for us that is one group for IO and one for CPU bound). It implements `TaskScheduler` because it is in charge providing the next task that should be run. It is called `WorkStealingGroup` because it does that by potentially stealing tasks from other threads in the same group.

Does that make sense to you?

File: util/src/main/java/io/camunda/zeebe/util/sched/ActorTask.java (hunk 4 above)
Comment (oleschoenburg) [reply util/src/main/java/io/camunda/zeebe/util/sched/ActorTask.java:66]: Whoops, nice catch!

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java (hunk 1 above)
Comment (oleschoenburg) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java]: Yes, that's a good point! :+1:

File: util/src/main/java/io/camunda/zeebe/util/sched/WorkStealingGroup.java (hunk 8 above)
Comment (Zelldon) [reply util/src/main/java/io/camunda/zeebe/util/sched/WorkStealingGroup.java:15]: I guess then the interface TaskScheduler is misleading, since it just provides the task but doesn't schedules it.

Comment (oleschoenburg) [reply util/src/main/java/io/camunda/zeebe/util/sched/WorkStealingGroup.java:15]: Yep, maybe `TaskProvider` or something? Naming is difficult :sweat_smile:

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java (hunk 1 above)
Comment (oleschoenburg) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java]: @Zelldon I'm thinking we should do the same for the `LogDeletionService` which is actually blocking longer than the snapshot store. Are you okay with just making the change in this pr?

Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java]: Doit!

Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/SnapshotDirectorPartitionTransitionStep.java]: But I guess we need to verify that with an benchmark whether it makes an impact ? :thinking:

**Comment by oleschoenburg** [comment]
@Zelldon Yep, I just re-used this one http://34.77.165.228/d/NzsO1mUnk/zeebe-overview?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=os-actorscheduler-cleanup-2&var-pod=All&var-partition=All to also get more insights into the actor scheduling metrics here: http://34.77.165.228/d/LAQSbGjnz/zeebe-actorscheduler-metrics?orgId=1&refresh=10s&from=now-3h&to=now&var-namespace=os-actorscheduler-cleanup-2

**Comment by Zelldon** [comment]
Thanks @oleschoenburg :+1:
