### PR TITLE
fix: make sdk properties tests able to run in parallel

### LINKED ISSUE #19520: [Spring SDK] Fix unit tests to run into the unified CI
**Description**

Adjust spring sdk unit tests to run into the unified CI

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

In order to enable SDK unit's test to be used in the unified ci we need to make sure that those tests can run in parallel

## Related issues

closes #19520

### CODE REVIEW

**Comment by nicpuppa** [comment]
Hey @Zelldon this change should fix the issue with the unified CI 👍

File: spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSelfManagedTest.java [hunk 1]
```diff
@@ -53,13 +53,13 @@
...
       "camunda.client.auth.client-secret=my-client-secret",
-      "camunda.client.auth.issuer=http://localhost:14682/auth-server"
+      "camunda.client.auth.issuer=http://localhost:14683/auth-server"
     })
 @EnableConfigurationProperties({
   ZeebeClientConfigurationProperties.class,
   CamundaClientProperties.class
 })
-@WireMockTest(httpPort = 14682)
+@WireMockTest(httpPort = 14683)
```
Comment (Zelldon) [inline spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSelfManagedTest.java:62]: 🪄 ⚠️ I would prefer to avoid magic numbers here. Why?

Because, 

 1. We will likely run into the same issue again if someone else decides to use the same port for some test. We have for example already dynamic assignments for ports in other tests, what if they use this port and your test does the same? It is unclear and will fail.
 2. In general it is not clear why to use this port over others. It feels more like an bandaid.

In general, I would always advise to use a dynamic/random port that is free during the assignment. 

WireMock seems to also allow to use dynamic ports https://wiremock.org/docs/configuration/#network-ports-and-binding maybe something we want to look into.


Maybe some of these answers help as well https://stackoverflow.com/questions/48707625/set-property-with-wiremock-random-port-in-spring-boot-test

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Thanks, Nic for the quick look at it. Unfortunately, I'm not sure whether we should do it like this. Maybe we can find something else.

File: spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSelfManagedTest.java (hunk 1 above)
Comment (nicpuppa) [reply spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSelfManagedTest.java]: Thanks for the advice, really nice one

**Comment by nicpuppa** [comment]
Should I remove also this workflow https://github.com/camunda/camunda/blob/main/.github/workflows/spring-boot-starter-camunda-sdk-ci.yml @Zelldon ?

File: spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSaasTest.java [hunk 2]
```diff
@@ -51,20 +52,30 @@
...
   ZeebeClientConfigurationProperties.class,
   CamundaClientProperties.class
 })
-@WireMockTest(httpPort = 14682)
 public class CredentialsProviderSaasTest {
 
+  @RegisterExtension
+  static WireMockExtension wm =
+      WireMockExtension.newInstance()
+          // dynamic port is the default
```
Comment (Zelldon) [inline spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSaasTest.java:66]: 🔧 Let's be specific and directly use the dynamic, with that we make sure that it works even if they change the defaults and we don't need to document it.

File: spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSelfManagedTest.java [hunk 3]
```diff
@@ -41,32 +39,45 @@
...
   ZeebeClientConfigurationProperties.class,
   CamundaClientProperties.class
 })
-@WireMockTest(httpPort = 14683)
 public class CredentialsProviderSelfManagedTest {
+
+  @RegisterExtension
+  static WireMockExtension wm =
+      WireMockExtension.newInstance()
+          // dynamic port is the default
```
Comment (Zelldon) [inline spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSelfManagedTest.java:67]: 🔧 Same here:)

File: spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSelfManagedTest.java [hunk 4]
```diff
@@ -41,32 +39,45 @@
...
   private static final String ACCESS_TOKEN =
       JWT.create().withExpiresAt(Instant.now().plusSeconds(300)).sign(Algorithm.none());
-
   @MockBean ZeebeClientExecutorService zeebeClientExecutorService;
   @Autowired ZeebeClientConfigurationImpl configuration;
 
+  @DynamicPropertySource
+  static void registerPgProperties(final DynamicPropertyRegistry registry) {
+    final String issuer = "http://localhost:" + wm.getPort() + "/auth-server";
+    registry.add("camunda.client.auth.issuer", () -> issuer);
```
Comment (Zelldon) [inline spring-boot-starter-camunda-sdk/src/test/java/io/camunda/zeebe/spring/client/config/CredentialsProviderSelfManagedTest.java:78]: 👍🏼

File: .github/workflows/ci.yml [hunk 5]
```diff
@@ -92,7 +92,7 @@ jobs:
           -D skipITs -D skipChecks -D surefire.rerunFailingTestsCount=3
           -D junitThreadCount=16
           -P skip-random-tests,parallel-tests,extract-flaky-tests
-          -pl '!testing/camunda-process-test-java,!spring-boot-starter-camunda-sdk'
+          -pl '!testing/camunda-process-test-java'
```
Comment (Zelldon) [inline .github/workflows/ci.yml:95]: 👍🏼

**Review by ChrisKujawa — APPROVED** [review]
Great thanks for fixing and adjusting :) @nicpuppa 🚀 


```
[INFO] Camunda Spring SDK ................................. SUCCESS [ 24.671 s]
```

If we are sure that we completely cover all tests (and there are no IT tests missing), then yes I think we can rid of the other workflow 🚀 👍🏼

**Comment by nicpuppa** [comment]
@Zelldon I checked the Spring SDK tests and everything seems ok. I also removed the rule from the branch protection on main. 

I'm going to merge this PR 👍
