### PR TITLE
test(journal): always close journal in tests

### LINKED ISSUE #11529: Flaky `SegmentedJournalTest.shouldCreateNewSegmentIfEntryExceedsBuffer`
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? quite often
- Does it block your work? no
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Warning:  Flakes: 
Warning:  io.camunda.zeebe.journal.file.SegmentedJournalTest.shouldCreateNewSegmentIfEntryExceedsBuffer
Error:    Run 1: SegmentedJournalTest.shouldCreateNewSegmentIfEntryExceedsBuffer ? IO Failed to delete temp directory /tmp/junit17963844446426179517. The following paths could not be deleted (see suppressed exceptions for details): , data
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
2023-02-02T14:53:48.3914818Z [ERROR] io.camunda.zeebe.journal.file.SegmentedJournalTest.shouldCreateNewSegmentIfEntryExceedsBuffer  Time elapsed: 0.076 s  <<< ERROR!
2023-02-02T14:53:48.3916097Z java.io.IOException: Failed to delete temp directory /tmp/junit17963844446426179517. The following paths could not be deleted (see suppressed exceptions for details): , data
2023-02-02T14:53:48.3917404Z 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:350)
2023-02-02T14:53:48.3918454Z 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:251)
2023-02-02T14:53:48.3919351Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-02-02T14:53:48.3920405Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$closeAllStoredCloseableValues$3(ExtensionValuesStore.java:68)
2023-02-02T14:53:48.3921496Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2023-02-02T14:53:48.3922355Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2023-02-02T14:53:48.3923142Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2023-02-02T14:53:48.3923887Z 	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
2023-02-02T14:53:48.3924677Z 	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
2023-02-02T14:53:48.3925677Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
2023-02-02T14:53:48.3926549Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2023-02-02T14:53:48.3927604Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2023-02-02T14:53:48.3928424Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2023-02-02T14:53:48.3929281Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2023-02-02T14:53:48.3930165Z 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2023-02-02T14:53:48.3931341Z 	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:68)
2023-02-02T14:53:48.3932650Z 	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:80)
2023-02-02T14:53:48.3933895Z 	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
2023-02-02T14:53:48.3934993Z 	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
2023-02-02T14:53:48.3936116Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$cleanUp$1(TestMethodTestDescriptor.java:155)
2023-02-02T14:53:48.3937486Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-02-02T14:53:48.3938703Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.cleanUp(TestMethodTestDescriptor.java:155)
2023-02-02T14:53:48.3940033Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.cleanUp(TestMethodTestDescriptor.java:68)
2023-02-02T14:53:48.3941185Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$10(NodeTestTask.java:167)
2023-02-02T14:53:48.3942435Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-02-02T14:53:48.3943601Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:167)
2023-02-02T14:53:48.3944718Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:98)
2023-02-02T14:53:48.3946187Z 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
2023-02-02T14:53:48.3948320Z 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:155)
2023-02-02T14:53:48.3950239Z 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)
2023-02-02T14:53:48.3951703Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2023-02-02T14:53:48.3952939Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-02-02T14:53:48.3954120Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2023-02-02T14:53:48.3955161Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2023-02-02T14:53:48.3956251Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2023-02-02T14:53:48.3957512Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-02-02T14:53:48.3958686Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2023-02-02T14:53:48.3959765Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2023-02-02T14:53:48.3961223Z 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
2023-02-02T14:53:48.3963195Z 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
2023-02-02T14:53:48.3964636Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2023-02-02T14:53:48.3965865Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-02-02T14:53:48.3967283Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2023-02-02T14:53:48.3968397Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2023-02-02T14:53:48.3969492Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2023-02-02T14:53:48.3970645Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-02-02T14:53:48.3971819Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2023-02-02T14:53:48.3972810Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2023-02-02T14:53:48.3974242Z 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
2023-02-02T14:53:48.3975691Z 	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
2023-02-02T14:53:48.3976573Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
2023-02-02T14:53:48.3977906Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
2023-02-02T14:53:48.3978721Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
2023-02-02T14:53:48.3979398Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
2023-02-02T14:53:48.3980191Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2023-02-02T14:53:48.3981013Z 	Suppressed: java.nio.file.DirectoryNotEmptyException: /tmp/junit17963844446426179517
2023-02-02T14:53:48.3981905Z 		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:246)
2023-02-02T14:53:48.3982908Z 		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
2023-02-02T14:53:48.3983668Z 		at java.base/java.nio.file.Files.delete(Files.java:1152)
2023-02-02T14:53:48.3984576Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:293)
2023-02-02T14:53:48.3985547Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:288)
2023-02-02T14:53:48.3986447Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:264)
2023-02-02T14:53:48.3987407Z 		at java.base/java.nio.file.Files.walkFileTree(Files.java:2828)
2023-02-02T14:53:48.3988047Z 		at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
2023-02-02T14:53:48.3988960Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:264)
2023-02-02T14:53:48.3989994Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:249)
2023-02-02T14:53:48.3990628Z 		... 53 more
2023-02-02T14:53:48.3991173Z 	Suppressed: java.nio.file.DirectoryNotEmptyException: /tmp/junit17963844446426179517/data
2023-02-02T14:53:48.3992053Z 		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:246)
2023-02-02T14:53:48.3992953Z 		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
2023-02-02T14:53:48.3993689Z 		at java.base/java.nio.file.Files.delete(Files.java:1152)
2023-02-02T14:53:48.3994675Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:293)
2023-02-02T14:53:48.3995668Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:288)
2023-02-02T14:53:48.3996601Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:264)
2023-02-02T14:53:48.3997517Z 		at java.base/java.nio.file.Files.walkFileTree(Files.java:2828)
2023-02-02T14:53:48.3998214Z 		at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
2023-02-02T14:53:48.3999057Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:264)
2023-02-02T14:53:48.3999993Z 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:249)
2023-02-02T14:53:48.4000535Z 		... 53 more
2023-02-02T14:53:48.4000758Z 
2023-02-02T14:53:48.4089383Z [INFO] Running io.camunda.zeebe.journal.file.SegmentedJournalTest
2023-02-02T14:53:48.4222220Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in io.camunda.zeebe.journal.file.SegmentedJournalTest
2023-02-02T14:53:48.7923737Z [INFO] Tests run: 34, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.568 s - in io.camunda.zeebe.journal.JournalTest
2023-02-02T14:53:49.0174058Z [INFO] 
2023-02-02T14:53:49.0175069Z [INFO] Results:
2023-02-02T14:53:49.0175839Z [INFO] 
2023-02-02T14:53:49.0176940Z [WARNING] Flakes: 
2023-02-02T14:53:49.0178239Z [WARNING] io.camunda.zeebe.journal.file.SegmentedJournalTest.shouldCreateNewSegmentIfEntryExceedsBuffer
2023-02-02T14:53:49.0190274Z [ERROR]   Run 1: SegmentedJournalTest.shouldCreateNewSegmentIfEntryExceedsBuffer ? IO Failed to delete temp directory /tmp/junit17963844446426179517. The following paths could not be deleted (see suppressed exceptions for details): , data
</pre>
</details>

https://github.com/camunda/zeebe/actions/runs/4076414664/jobs/7024115993

### PR DESCRIPTION
**Pull request by lenaschoenburg**
* Ensures that closing the journal waits for async segment preparation to finish
* Closes the journal in all tests

This prevents flaky tests that fail because removing the temporary data folder fails which can occur when cleanup of segment files races with completion of the async preparation task.

fixes #11529

### CODE REVIEW

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java [hunk 1]
```diff
@@ -71,14 +71,25 @@ final class SegmentsManager {
...
     segments
         .values()
         .forEach(
             segment -> {
               LOG.debug("Closing segment: {}", segment);
               segment.close();
             });
+
+    try {
+      nextSegment.join();
```
Comment (npepinpe) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java:85]: :question: Is it not cancellable? If not, then ignore this :smile:

File: journal/src/test/java/io/camunda/zeebe/journal/JournalReaderTest.java [hunk 2]
```diff
@@ -15,33 +15,25 @@
...
 
   private static final int ENTRIES = 4;
+  @TempDir File directory;
 
   private final UnsafeBuffer data = new UnsafeBuffer("test".getBytes(StandardCharsets.UTF_8));
   private final BufferWriter recordDataWriter = new DirectBufferWriter().wrap(data);
-  private JournalReader reader;
-  private SegmentedJournal journal;
-
-  @BeforeEach
```
Comment (npepinpe) [inline journal/src/test/java/io/camunda/zeebe/journal/JournalReaderTest.java:33]: :x: Correct me if I'm wrong, but can't we use `AfterEach` here to close the journal? Specifically, by adding it at the end of the test, if a test fails, the journal is not closed, right, as the line is never called? :thinking:

File: journal/src/test/java/io/camunda/zeebe/journal/JournalTest.java [hunk 3]
```diff
@@ -31,58 +31,61 @@
...
 
   @TempDir Path directory;
 
-  private byte[] entry;
-  private final DirectBufferWriter recordDataWriter = new DirectBufferWriter();
-  private final DirectBufferWriter otherRecordDataWriter = new DirectBufferWriter();
-  private Journal journal;
-
-  @BeforeEach
-  void setup() {
```
Comment (npepinpe) [inline journal/src/test/java/io/camunda/zeebe/journal/JournalTest.java:48]: :x: Same as JournalReaderTest

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java [hunk 4]
```diff
@@ -71,6 +70,8 @@ void shouldDeleteIndexMappingsOnReset() {
     // then
     assertThat(journal.getJournalIndex().lookup(journalIndexDensity)).isNull();
     assertThat(journal.getJournalIndex().lookup(2 * journalIndexDensity)).isNull();
+
+    journal.close();
```
Comment (npepinpe) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:74]: :x: Same as JournalReaderTest

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentsManagerTest.java [hunk 5]
```diff
@@ -39,22 +39,25 @@ class SegmentsManagerTest {
...
+      segments.open();
+      segments.getFirstSegment().createReader();
+      segments.getFirstSegment().delete();
+    }
 
     // when
     // if we close the current journal, it will delete the files on closing. So we cannot test this
     // scenario.
-    createSegmentsManager(0).open();
+    final var newSegments = createSegmentsManager(0);
```
Comment (npepinpe) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentsManagerTest.java:51]: :x: Wrap in a try-with-resources too

**Review by npepinpe — CHANGES_REQUESTED** [review]
:rocket: Thanks for the fast PR!

It's mostly one comment over all tests, but if a test fails and the last line is the close, this won't be executed, but the directory will still try to be cleaned up? It's minor, but what prevents us from using the `AfterEach` annotation? :thinking:

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java [hunk 6]
```diff
@@ -71,14 +71,25 @@ final class SegmentsManager {
...
+    } catch (final Throwable throwable) {
```
Comment (npepinpe) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java:86]: :question: Why throwable? Exception should suffice here, no? :thinking:

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java (hunk 4 above)
Comment (oleschoenburg) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:74]: That'd require "leaking" the journal to an instance field so that it is accessible to and `AfterEach` callback

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java [hunk 7]
```diff
@@ -51,10 +53,19 @@ class SegmentedJournalTest {
   private final BufferWriter recordDataWriter = new DirectBufferWriter().wrap(data);
   private final int entrySize = getSerializedSize(data);
 
+  private SegmentedJournal journal;
+
+  @AfterEach
+  void teardown() {
+    if (journal != null) {
```
Comment (npepinpe) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java:60]: :upside_down_face: I always use Agrona's `CloseHelper.quietClose` since it deals with nulls, quiets any errors if I don't care, etc. Also supports collections via `CloseHelper.quietCloseAll`.

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentsManagerTest.java [hunk 8]
```diff
@@ -48,16 +48,16 @@ void shouldDeleteFilesMarkedForDeletionsOnLoad() {
     // when
     // if we close the current journal, it will delete the files on closing. So we cannot test this
     // scenario.
-    final var newSegments = createSegmentsManager(0);
-    newSegments.open();
+    try (var newSegments = createSegmentsManager(0)) {
+      newSegments.open();
```
Comment (npepinpe) [inline journal/src/test/java/io/camunda/zeebe/journal/file/SegmentsManagerTest.java:52]: :x: From the comment, I expected the assertions need to be inside this right?

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java (hunk 4 above)
Comment (oleschoenburg) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentedJournalTest.java]: I've gone with the first approach now

File: journal/src/test/java/io/camunda/zeebe/journal/file/SegmentsManagerTest.java (hunk 8 above)
Comment (oleschoenburg) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentsManagerTest.java:52]: Oops, yeah you are right :sweat_smile:

Comment (oleschoenburg) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentsManagerTest.java:52]: But actually the test has been broken for longer than that I think. It wants to test that files marked for deletion are deleted **when opening**. So the initial segments manager must not be closed, otherwise the files are deleted **when closing**. I think this

Comment (oleschoenburg) [reply journal/src/test/java/io/camunda/zeebe/journal/file/SegmentsManagerTest.java:54]: I think the test was actually broken before. I've adjusted and updated the comments to clarify what's being tested here.

**Comment by npepinpe** [comment]
Even the container tests are having trouble with apt :smile:

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors retry
