### PR TITLE
Extend advanced search to support incidentErrorHashCode in OR filter

### LINKED ISSUE #31180: [C8 API] PI search & PD statistics `incidentErrorHashCode` is not working with `$or` filters
### Description

In PI search or PD statistics we've introduced both the `incidentErrorHashCode` filter and the `$or` filters. These currently don't work in combination. In order for them both to work, we need to add a little extra code for ES/OS (See Rootcause).

### Steps to reproduce

Call the PI search or PD statistics with `$or` filters containing `incidentErrorHashCode`.

### Current behavior

`incidentErrorHashCode` doesn't work in `$or` filters with search and statistics.

### Expected behavior

`incidentErrorHashCode` works in `$or` filters with search and statistics.

### Rootcause

`incidentErrorHashCode` is not part of the list-view index, it's stored in the incident index. So we map the code to PI keys using [`mapIncidentErrorHashCodesToProcessInstanceKeys` in `DocumentBasedSearchClients`](https://github.com/camunda/camunda/blob/main/search/search-client-query-transformer/src/main/java/io/camunda/search/clients/DocumentBasedSearchClients.java#L267) and then update the search/statistics filter with these PI keys.
This extra logic is not implemented for `$or` filters.

### Solution ideas

- Implementation is either:
  - Expand the current logic to `$or` filters as well. Move the logic out of the `DocumentBasedSearchClients` because it will grow quite substantial.
  - Try to find a better solution for this filter in ES/OS.
- Add QA tests for both endpoints.

### PR DESCRIPTION
**Pull request by tsedekey**
## Description

This PR adds support for using incidentErrorHashCode with the advanced OR filter in the Process Instance and Process Definition Statistics search endpoints.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #31180

### CODE REVIEW

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java [hunk 1]
```diff
@@ -121,9 +130,10 @@ public SearchQuery toSearchQuery(final ProcessInstanceFilter filter) {
   private static SearchQuery getFlowNodeInstanceQuery(final ProcessInstanceFilter filter) {
     final var flowNodeInstanceQueries = new ArrayList<SearchQuery>();
 
-    flowNodeInstanceQueries.addAll(stringOperations(ACTIVITY_ID, filter.flowNodeIdOperations()));
-    flowNodeInstanceQueries.addAll(
-        stringOperations(ACTIVITY_STATE, filter.flowNodeInstanceStateOperations()));
+    Optional.of(stringOperations(ACTIVITY_ID, filter.flowNodeIdOperations()))
+        .ifPresent(flowNodeInstanceQueries::addAll);
```
Comment (tmetzke) [inline search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java:128]: ❓ Why do we move back to the lengthy Optional-based code for operations that cannot be null? The methods like `stringOperations` always return a non-null result, if I'm not mistaken. Using Optional here wraps this unnecessarily, I think.

Comment (tsedekey) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java:128]: You’re right — this change wasn’t necessary. I followed the IDE suggestion a bit too hastily.

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java [hunk 2]
```diff
@@ -70,7 +70,7 @@ public ArrayList<SearchQuery> toSearchQueryFields(final ProcessInstanceFilter fi
     queries.addAll(dateTimeOperations(START_DATE, filter.startDateOperations()));
     queries.addAll(dateTimeOperations(END_DATE, filter.endDateOperations()));
     queries.addAll(stringOperations(STATE, filter.stateOperations()));
-    ofNullable(getIncidentQuery(filter.hasIncident())).ifPresent(queries::add);
+    queries.add(getIncidentQuery(filter.hasIncident()));
```
Comment (tmetzke) [inline search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java]: ❌ The `getIncidentQuery` can be `null`, so we should only add it when it's not, right?

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java [hunk 3]
```diff
@@ -80,16 +80,13 @@ public ArrayList<SearchQuery> toSearchQueryFields(final ProcessInstanceFilter fi
...
-              ACTIVITIES_JOIN_RELATION,
-              SearchMatchQueryOperator.AND));
+          stringMatchPhraseWithHasChildOperations(
+              ERROR_MSG, filter.errorMessageOperations(), ACTIVITIES_JOIN_RELATION));
     }
 
     queries.addAll(stringOperations(BATCH_OPERATION_IDS, filter.batchOperationIdOperations()));
 
-    ofNullable(getHasRetriesLeftQuery(filter.hasRetriesLeft())).ifPresent(queries::add);
+    queries.add(getHasRetriesLeftQuery(filter.hasRetriesLeft()));
```
Comment (tmetzke) [inline search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java]: ❌ Same as above, I guess.

File: search/search-domain/src/main/java/io/camunda/search/filter/ProcessInstanceFilter.java [hunk 4]
```diff
@@ -39,7 +39,7 @@ public record ProcessInstanceFilter(
     List<Operation<String>> flowNodeIdOperations,
     Boolean hasFlowNodeInstanceIncident,
     List<Operation<String>> flowNodeInstanceStateOperations,
-    List<Integer> incidentErrorHashCodes,
+    Integer incidentErrorHashCode,
```
Comment (tmetzke) [inline search/search-domain/src/main/java/io/camunda/search/filter/ProcessInstanceFilter.java]: ❓ Can we make this a list of operations as well so it's consistent with the other filter criteria?

File: db/rdbms/src/main/resources/mapper/ProcessInstanceMapper.xml [hunk 5]
```diff
@@ -238,12 +238,12 @@
         )
       </foreach>
     </if>
-    <if test="filter.incidentErrorHashCodes != null and !filter.incidentErrorHashCodes.isEmpty()">
+    <if test="filter.incidentErrorHashCode != null">
```
Comment (tmetzke) [inline db/rdbms/src/main/resources/mapper/ProcessInstanceMapper.xml]: 🔧 If we make this a list of operations, we need to adjust this here as well.

**Review by tmetzke — CHANGES_REQUESTED** [review]
👍 The core changes to the mapping look good to me, nice job 🚀 
🔧 Added some refactoring suggestions and some improvement ideas.
❌ I think in two places we're introducing potential NPEs but maybe I am overlooking something and that's not true.

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java (hunk 1 above)
Comment (tmetzke) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java:128]: There are a lot of those changes, ideally we can simply revert them. Did your IDE suggest to turn those lines into `Optional`s? Just wondering, because the results of those methods cannot be null. An Optional doesn't really seem right to me.

Comment (tsedekey) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java:128]: Yes the IDE did make the suggestion but it's clearly wrong.

Comment (tmetzke) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java:128]: It's interesting though that it takes this as the better option. I am wondering why.

**Review by tmetzke — APPROVED** [review]
👍 Looks good to me 🚀 
🔧 There is one last open conversation regarding the use of `Optional` but it's not a blocking issue, so pre-approving already.

File: search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java (hunk 1 above)
Comment (tsedekey) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java:128]: Screenshot 2025-07-21 at 16 15 42

I'm not entirely sure why it thinks this is better but the best thing to do is add the operations types directly to the queries list since they cannot be null. For non-operation types it is better to use Optional.ofNullable method to make sure we don't add null values into the queries list.

Comment (tmetzke) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java:128]: Ah, I see. OK, well, for the code it encountered the proposed solution is indeed better. But that is not the original code. The original code indeed was `flowNodeInstanceQueries.addAll(stringOperations(ACTIVITY_STATE, filter.flowNodeInstanceStateOperations()))`. Does the IDE have anything to say against that?

Comment (tsedekey) [reply search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessInstanceFilterTransformer.java:128]: Ah I see, no issues to the original `flowNodeInstanceQueries.addAll(stringOperations(ACTIVITY_STATE, filter.flowNodeInstanceStateOperations())) ` from the IDE!
