### PR TITLE
fix: Avoid concurrent commands during process instance migration

### LINKED ISSUE #15129: Avoid executing process according to unprocessed commands referring to source process definition
If we allow the migration of process instances not entirely in a wait state, Zeebe would wrongly execute the process instance after the migration.

In short, unprocessed commands referring to the source process definition may exist on the log stream with a position higher than the process instance migration command. When we process these commands, the engine wrongly attempts to continue the processing on the source process definition as if the migration didn't occur. For a complete discussion, please read 'How should we deal with process instances in non-wait states?' in the epic's 'Discussions and Decisions' section. 

We can either:
1. Reject process instance migration if we know the process instance is not entirely in a wait state.
2. Don't trust the process definition key in such commands, but rather look up the process definition from the state when processing commands.

A downside to option 1 is: We don't know what commands exist on the log with a higher position than the command being processed. It may be that this solution is not water tight, requiring us to investigate option 2.

A downside to option 2 is: Some commands may refer to elements that no longer exist in the target process. These will be rejected.

### PR DESCRIPTION
**Pull request by saig0**
## Description

If the batch processing is disabled, a process instance migration command in combination with a concurrent command for the same process instance could lead to an invalid state. The process instance is migrated but the element instance of the concurrent command continues processing on the previous version of the process.  

To avoid invalid states, Zeebe rejects the process instance migration command if it detects a concurrent command. We use the event trigger and the active sequence flow count as indicators for a concurrent comment. The event trigger is created if an event, like a timer, message, or signal, is triggered. The active sequence flow count is greater than zero if a sequence flow is taken but the connected element is not activated yet. 

## Related issues

requires #15571
closes #15129 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/MigrateProcessInstanceConcurrentNoBatchingTest.java [hunk 1]
```diff
@@ -0,0 +1,933 @@
...
+            tuple("end_v2", ProcessInstanceIntent.ELEMENT_COMPLETED),
+            tuple(targetProcessId, ProcessInstanceIntent.ELEMENT_COMPLETED))
+        .doesNotContain(
+            tuple("B_v1", ProcessInstanceIntent.ELEMENT_COMPLETED),
+            tuple("end_v1", ProcessInstanceIntent.ELEMENT_COMPLETED),
+            tuple(processId, ProcessInstanceIntent.ELEMENT_COMPLETED));
+  }
+
+  @Test
+  public void shouldContinueMigratedInstanceWithTimerBefore() {
```
Comment (berkaycanbc) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/MigrateProcessInstanceConcurrentNoBatchingTest.java:213]: ❌ This test case and other ones that are containing the boundary events needs to be updated because we will reject migrating tasks with boundary events in #15665.

**Review by berkaycanbc — CHANGES_REQUESTED** [review]
Clever implementation, thanks @saig0! 🚀 

I asked changes only for refactoring. Some parts needs to be updated according to changes that will be introduced with PR #15665.

**Review by berkaycanbc — APPROVED** [review]
@saig0 I am approving the PR as the changes I requested are not related to actual implementation logic and doesn't need another review round.

Please feel free to merge afterwards! 👍

**Comment by saig0** [comment]
bors merge
