### PR TITLE
fix: deduplicate user task variables by scope in API

### LINKED ISSUE #46967: Tasklist v2 variables search endpoint returns fewer variables
### 

### 

### 

### 

### Description

For certain user tasks, the Tasklist v2 variables search endpoint:

```
POST /v2/user-tasks/{taskId}/variables/search
```
returns **fewer variables than reported in `page.totalItems`**, and silently drops some **local task variables**. Operate shows the full, correct set of local variables for the same user task, so this is not an engine/scoping issue.

In a concrete example, for three consecutive user tasks in the same process instance:

- Operate’s variables view for user task 3 shows these locals:

  ```json
  {
    "instructions": "...X5 M Competition per official database lookup...",
    "numberPlate": "A1234B",
    "vehicleMake": "BMW",
    "vehicleModel": "X5 M Competition",
    "vehicleType": "LCV (Light Commercial Vehicle)",
    "zipCode": ""
  }
  ```

- The Tasklist variables search response for that task contains:
  - **7 root/process variables** (scopeKey = 2251799816802594):  
    `vehicleModel`, `vehicleMake`, `vehicleType`, `vehicleUsage`, `numberPlate`, `zipCode`, `privateUsage`
  - **Only 3 user-task locals** (scopeKey = 2251799816805492):  
    `vehicleType`, `numberPlate`, `zipCode`
  - **Missing locals:** `instructions`, `vehicleMake`, `vehicleModel`

- Response metadata:

  ```json
  "page": {
    "totalItems": 13,
    "hasMoreTotalItems": false,
    ...
  }
  ```

- But `items.length` is only `10`, not `13`.

The same pattern occurs for user tasks 1 and 2 in the same instance:

- `totalItems` is always `13`
- `items.length` is always `10`
- Exactly **3 local variables are missing** each time.

This causes Tasklist forms and any custom UIs using the Tasklist REST API to see **stale or incomplete data** (e.g., global `vehicleModel = "X5"` instead of the local `"X5 M Competition"`, and no `instructions` or `vehicleMake` at all).

This is **not** the same as the large-variable truncation bug in `camunda/camunda#39189`:

- Values here are short strings.
- The issue is about **missing items vs `totalItems`**, not truncated values.
- `hasMoreTotalItems` is `false`, so clients have no way to page for the missing variables.

### Steps to reproduce

Minimal high‑level steps (exact JSON examples attached below):

1. Model a process that:
   - Has a user task with several **local variables** (e.g., set via input mappings or via a script/connector), and
   - Also has several **process‑scope (root) variables**.
   - Ensure that for a given user task, the **total number of accessible variables (root + locals) > 10**.

2. Start a process instance and reach that user task.

3. In **Operate**, open the user task and inspect:
   - Root variables,
   - “Local variables” for that task.  
   Confirm there are, for example, **7 root vars + 6 local vars = 13** variables in total.

4. In **Tasklist**, or via direct REST call, execute:

   ```http
   POST /v2/user-tasks/{taskId}/variables/search
   Content-Type: application/json

   {
     "searchAfter": null,
     "pageSize": 50,
     "filters": []
   }
   ```

5. Observe the response:
   - `page.totalItems` reports `13`,
   - `page.hasMoreTotalItems` is `false`,
   - but `items` only contains **10 entries** (7 root + 3 locals), and several local variables that Operate shows are **missing**.

6. Repeat for multiple user tasks in the same instance (e.g., a user task as a tool invoked multiple times by an agentic sub-process). You’ll see the same pattern: **constant 10 returned, 13 reported, 3 locals missing**.

**Attached example files (sanitized names; please see uploads in the issue):**

- `a1-operate-toolcall.json` – tool call payload from Operate (complete data).
- `a1-tasklist-make-missing.json` – Tasklist variables search for user task 1.  
  → `items.length = 10`, `page.totalItems = 13`.
- `a2-operate-toolcall.json` – tool call payload for user task 2.
- `a2-tasklist-instructions-and-make-missing.json` – same pattern for task 2.
- `a3-operate-local-variables.json` – **local variables in Operate** for user task 3 (6 locals).
- `a3-tasklist-instructions-and-make-missing.json` – Tasklist variables search for task 3:  
  7 globals + 3 locals, 3 locals missing, `totalItems = 13`, `hasMoreTotalItems = false`.

[a1-operate-local-variables-after-completion.json](https://github.com/user-attachments/files/25574615/a1-operate-local-variables-after-completion.json)
[a1-operate-toolcall.json](https://github.com/user-attachments/files/25574614/a1-operate-toolcall.json)
[a1-tasklist-make-missing.json](https://github.com/user-attachments/files/25574613/a1-tasklist-make-missing.json)
[a2-operate-local-variables-after-completion.json](https://github.com/user-attachments/files/25574612/a2-operate-local-variables-after-completion.json)
[a2-operate-toolcall.json](https://github.com/user-attachments/files/25574609/a2-operate-toolcall.json)
[a2-tasklist-instructions-and-make-missing.json](https://github.com/user-attachments/files/25574610/a2-tasklist-instructions-and-make-missing.json)
[a3-operate-local-variables.json](https://github.com/user-attachments/files/25574608/a3-operate-local-variables.json)
[a3-operate-toolcall.json](https://github.com/user-attachments/files/25574607/a3-operate-toolcall.json)
[a3-tasklist-instructions-and-make-missing.json](https://github.com/user-attachments/files/25574611/a3-tasklist-instructions-and-make-missing.json)
[a-operate-global-variables.json](https://github.com/user-attachments/files/25574616/a-operate-global-variables.json)

[Agentic Vehicle Data Reconciliation.bpmn.xml](https://github.com/user-attachments/files/25574813/Agentic.Vehicle.Data.Reconciliation.bpmn.xml)

### Current behavior

- `/v2/user-tasks/{taskId}/variables/search`:
  - Returns **fewer variables than `page.totalItems`**, consistently capped at 10 in this case.
  - Silently omits some **local variables** from the response, even though they exist and are visible in Operate.
  - Sets `hasMoreTotalItems = false`, so the client cannot detect that variables are missing or request additional pages.
- Tasklist UI and external clients built on this endpoint:
  - See **incomplete** variable sets.
  - Fall back to **global/root variables** where locals are missing, leading to stale or incorrect values in forms and UIs.

### Expected behavior

- The variables search endpoint should either:
  - Return **all** accessible variables for the given task (root + local) when `page.hasMoreTotalItems = false`, **or**
  - If a page size limit is applied, ensure:
    - `items.length <= pageSize`,
    - `page.totalItems` reflects the true total,
    - `page.hasMoreTotalItems = true` whenever not all items are returned, so clients can page through and retrieve **all** variables.

In other words, `items.length` must never be less than `page.totalItems` when `hasMoreTotalItems = false`, and **local variables must not be silently dropped**.

### Workaround

- There is no reliable programmatic workaround on Tasklist’s REST API:
  - The endpoint claims `hasMoreTotalItems = false`, so the client has no indication that variables are missing.
- The only workaround for UIs is, one can try to avoid relying on the missing locals (e.g., duplicate values into fewer variables), but this is brittle and does not fix the underlying API inconsistency.

### Environment

SaaS

### Version

- Component: Tasklist (backed by Orchestration Cluster REST v2)
- Environment: Camunda 8 SaaS
- Orchestration Cluster generation: **8.8+gen14**, “No updates available – running on latest available version” (as shown in Console at the time of writing).

### Rootcause

From the outside, this looks like a **Tasklist/Orchestration Cluster REST API bug** in `/v2/user-tasks/{taskId}/variables/search`:

- Likely a hard cap (10 items) or incorrect pagination logic in the underlying implementation.
- `page.totalItems` is derived correctly (13), but the returned `items` list is truncated to 10.
- `hasMoreTotalItems` is incorrectly set to `false`, hiding the truncation from clients.
- The truncation consistently affects some **local scope** variables, not just any arbitrary subset.

This is related in spirit (same endpoint family) but **different in nature** from `camunda/camunda#39189` (large-variable truncation + parsing errors).

### Solution ideas

- Review the implementation of `/v2/user-tasks/{taskId}/variables/search`:
  - Remove any implicit hard limit on the number of returned variables, or
  - Make sure server-side paging is consistent:
    - Respect `pageSize`,
    - Correctly return `hasMoreTotalItems = true` whenever `items.length < totalItems`,
    - Never return `hasMoreTotalItems = false` when not all items are included.
- Add E2E and unit tests covering:
  - A user task with >10 accessible variables (combination of root + local scopes),
  - Verifying that:
    - `items.length` + paging behaviour matches `totalItems`,
    - Local variables present in the engine (and visible in Operate) are all discoverable via Tasklist’s variables search.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

- Possibly related (but different root cause):  
  - `camunda/camunda#39189` – “Tasklist v2 tasks not loaded when includes large variable”
  - `camunda/camunda#44197` – “Nested variables are not displayed in forms” (front-end selection issue)
- Internal reference (similar symptom of missing variables in Tasklist search): SUPPORT-29974 (if accessible to maintainers).

### Automated Test Impact

- No known existing automated test is referenced, but this behaviour suggests:
  - A new test should be added to the **Orchestration Cluster E2E / Tasklist** test suites that:
    - Creates a user task with >10 variables (mix of root and local),
    - Calls `/v2/user-tasks/{taskId}/variables/search`,
    - Asserts that all engine variables are returned (or correctly paginated) and that `totalItems` / `hasMoreTotalItems` are consistent.

### PR DESCRIPTION
**Pull request by tsedekey**
## Description

This PR adds a new endpoint `POST /v2/user-tasks/{userTaskKey}/effective-variables/search` that returns deduplicated variables for a user task, where the innermost scope wins when the same variable name exists at multiple levels in the scope hierarchy (e.g., process root and subprocess). The existing `/variables/search` endpoint has kept its original pass-through behaviour with improved documentation clarifying that it may return the same variable name at multiple scopes.

## Problem
When a user task sits inside a subprocess, the V2 variables search endpoint returns all variable documents across every scope in the tree path. If the same variable name exists at both process and subprocess scope, duplicates inflate totalItems and cause the Tasklist UI to silently drop variables when `page.limit `equals the number of expected form fields.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

>[!NOTE] 
> ### Note to reviewer
>I realise this PR touches quite a few files across multiple modules. To help with reviewing, I've kept the individual commits as small and focused as possible, following the commit trail should make the review more manageable. I considered breaking this into separate PRs, but the interdependencies between the changes made it difficult to split without leaving intermediate states that wouldn't compile or function correctly. 

## Related issues

closes #46967

### CODE REVIEW

File: service/src/main/java/io/camunda/service/UserTaskServices.java [hunk 1]
```diff
@@ -280,6 +287,128 @@ public SearchQueryResult<VariableEntity> searchUserTaskVariables(
...
+
+    final var unlimitedQuery =
+        variableSearchQuery(
+            q ->
+                q.filter(f -> f.copyFrom(variableQuery.filter()).scopeKeys(treePathList))
+                    .unlimited());
+
+    final var allVariables =
+        executeSearchRequest(
+            () -> variableServices.search(unlimitedQuery, CamundaAuthentication.anonymous()));
```
[the remark this answers is not in the document]
Comment (tsedekey) [reply service/src/main/java/io/camunda/service/UserTaskServices.java:320]: This an internal call to a secondary service within the main service, user authentication is not usually required for this call right?

File: service/src/main/java/io/camunda/service/UserTaskServices.java [hunk 2]
```diff
@@ -280,6 +287,128 @@ public SearchQueryResult<VariableEntity> searchUserTaskVariables(
...
+    final List<Long> treePathList =
+        treePath != null
+            ? Arrays.stream(treePath.split("/")).map(Long::valueOf).toList()
+            : Collections.emptyList();
+
+    final var unlimitedQuery =
+        variableSearchQuery(
+            q ->
+                q.filter(f -> f.copyFrom(variableQuery.filter()).scopeKeys(treePathList))
+                    .unlimited());
```
[the remark this answers is not in the document]
Comment (tsedekey) [reply service/src/main/java/io/camunda/service/UserTaskServices.java:316]: Can ES/OS theoretically return more than 10,000 in this example? If so maybe capping it at 10,000 is not a bad idea.

File: service/src/main/java/io/camunda/service/UserTaskServices.java [hunk 3]
```diff
@@ -280,6 +287,128 @@ public SearchQueryResult<VariableEntity> searchUserTaskVariables(
...
+        Comparator.comparing(
+            entity -> {
+              try {
+                return (Comparable<Object>) accessor.invoke(entity);
+              } catch (final ReflectiveOperationException e) {
+                throw new IllegalStateException("Failed to access field: " + sorting.field(), e);
+              }
+            },
+            Comparator.nullsLast(Comparator.naturalOrder()));
+
```
[the remark this answers is not in the document]
Comment (tsedekey) [reply service/src/main/java/io/camunda/service/UserTaskServices.java]: But there is a trade off with having to maintain this code when sort fields are added or removed, but then again this would be a breaking change of the API contract, so maybe explicit mapping isn't such a bad idea.

File: service/src/main/java/io/camunda/service/UserTaskServices.java [hunk 4]
```diff
@@ -280,6 +287,128 @@ public SearchQueryResult<VariableEntity> searchUserTaskVariables(
...
+    // The Tasklist UI uses offset-based pagination for variables exclusively.
+    final var page = variableQuery.page();
+    final int size = page.size() != null ? page.size() : SearchQueryPage.DEFAULT_SIZE;
+    final int total = dedupedVariables.size();
+    final int from = page.from() != null ? page.from() : 0;
+    final int end = Math.min(from + size, total);
+    final List<VariableEntity> pageItems =
+        from < total ? new ArrayList<>(dedupedVariables.subList(from, end)) : List.of();
+
+    return new SearchQueryResult<>(total, false, pageItems, null, null);
```
[the remark this answers is not in the document]
Comment (tsedekey) [reply service/src/main/java/io/camunda/service/UserTaskServices.java:339]: Would the suggested code simply work? I thought the `hasMoreTotalItems` property was just an indication that there are more items than the ES limitation of 10,000 🤔

File: service/src/main/java/io/camunda/service/UserTaskServices.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (tsedekey) [reply service/src/main/java/io/camunda/service/UserTaskServices.java:320]: Rejecting this because this is an established pattern throughout `UserTaskServices`. Every method follows the same "gate-then-bypass" pattern: authorise once at the user task level via `getByKey(userTaskKey, authentication)`, then use `CamundaAuthentication.anonymous()` for all downstream internal service calls

File: service/src/main/java/io/camunda/service/UserTaskServices.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (tsedekey) [reply service/src/main/java/io/camunda/service/UserTaskServices.java:339]: Rejecting this because `hasMoreTotalItems` is specifically a "total count is capped" indicator, not a "there are more pages" indicator. Since our in-memory dedup knows the exact total, false is correct. Setting it to end < total would change the semantics to mean "there are more pages" — which is what totalItems + from + limit already communicate.

File: service/src/main/java/io/camunda/service/UserTaskServices.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (tsedekey) [reply service/src/main/java/io/camunda/service/UserTaskServices.java:316]: Rejecting this because ES's default `max_result_window` is 10,000, so `.unlimited()` wouldn't return more than that anyway without explicit configuration. And even in extreme case (100 variables × 10 scope levels = 1,000 rows) are well within memory.

File: gateways/gateway-mcp/src/main/java/io/camunda/gateway/mcp/tool/usertask/UserTaskTools.java [hunk 5]
```diff
@@ -201,4 +202,47 @@ public CallToolResult searchUserTaskVariables(
...
+          SearchQueryResponseMapper.toVariableSearchQueryResponse(
+              userTaskServices.searchUserTaskEffectiveVariables(
+                  userTaskKey,
+                  variableSearchQuery.get(),
+                  authenticationProvider.getCamundaAuthentication()),
+              shouldTruncate));
+    } catch (final Exception e) {
+      return CallToolResultMapper.mapErrorToResult(e);
+    }
+  }
```
Comment (tmetzke) [inline gateways/gateway-mcp/src/main/java/io/camunda/gateway/mcp/tool/usertask/UserTaskTools.java]: 👍 Thanks for looking into the MCP tools as well 🚀 
🔧 We can simply replace the existing user task variable search tool here, no need to keep both. We can keep the "old" name `searchUserTaskVariables`. We can scratch the `Use this instead of searchUserTaskVariables when you need the resolved variable values visible to a user task."` part.

File: gateways/gateway-mcp/src/test/java/io/camunda/gateway/mcp/tool/usertask/UserTaskToolsTest.java [hunk 6]
```diff
@@ -1070,4 +1070,233 @@ void shouldFailSearchUserTaskVariablesOnInvalidKey() {
...
+      assertThat(result.content())
+          .hasSize(1)
+          .first()
+          .isInstanceOfSatisfying(
+              TextContent.class,
+              textContent ->
+                  assertThat(textContent.text())
+                      .isEqualTo("userTaskKey: User task key must be a positive number."));
+    }
+  }
```
Comment (tmetzke) [inline gateways/gateway-mcp/src/test/java/io/camunda/gateway/mcp/tool/usertask/UserTaskToolsTest.java]: 🔧 We can simply keep the "old" tests, and adjust where needed (if needed at all).

File: gateways/gateway-mcp/src/test/resources/schema/tools-schema-snapshot.json [hunk 7]
```diff
@@ -841,6 +841,93 @@
...
+          }
+        },
+        "required": [
+          "userTaskKey"
+        ]
+      },
+      "annotations": {
+        "readOnlyHint": true
+      }
+    },
```
Comment (tmetzke) [inline gateways/gateway-mcp/src/test/resources/schema/tools-schema-snapshot.json]: 🔧 We can remove this and adjust the existing schema "golden" file if needed after adjusting the "old" tool.

File: clients/java/src/main/java/io/camunda/client/CamundaClient.java [hunk 8]
```diff
@@ -2213,6 +2214,28 @@ TenantScopedClusterVariableDeletionCommandStep1 newTenantScopedClusterVariableDe
    */
   UserTaskVariableSearchRequest newUserTaskVariableSearchRequest(long userTaskKey);
 
+  /**
+   * Executes a search request to query effective variables related to a user task. Returns
+   * deduplicated variables where the innermost scope wins when the same variable name exists at
+   * multiple scope levels. Uses offset-based pagination only.
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/client/CamundaClient.java]: 🔧 We don't need to mention which pagination it uses. The interface makes that clear already.
```suggestion
   * multiple scope levels.
```

File: service/src/main/java/io/camunda/service/UserTaskServices.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (tmetzke) [reply service/src/main/java/io/camunda/service/UserTaskServices.java:320]: This would only be an issue if reading variables and reading the user task itself require different permissions. If they are the same, i.e., I can read all variables visible from a user task including process variables if I can read the user task, then this is fine.

File: service/src/main/java/io/camunda/service/UserTaskServices.java [hunk 9]
```diff
@@ -280,6 +287,128 @@ public SearchQueryResult<VariableEntity> searchUserTaskVariables(
...
+      final CamundaAuthentication authentication) {
+
+    final var userTask = getByKey(userTaskKey, authentication);
+
+    final String treePath = fetchFlowNodeTreePath(userTask.elementInstanceKey());
+
+    final List<Long> treePathList =
+        treePath != null
+            ? Arrays.stream(treePath.split("/")).map(Long::valueOf).toList()
+            : Collections.emptyList();
```
Comment (tmetzke) [inline service/src/main/java/io/camunda/service/UserTaskServices.java:299]: 💭 Just wondering: if there is no tree path or it only contains the user task itself, i.e., there is no hierarchy, can we "escape" with a simple query, no `unlimited` calls and such? We don't need to do any deduplication or anything in that case, so we can keep the simple scenarios simple/performing well.

File: service/src/main/java/io/camunda/service/UserTaskServices.java [hunk 10]
```diff
@@ -280,6 +287,128 @@ public SearchQueryResult<VariableEntity> searchUserTaskVariables(
...
+        deduplicateVariablesByScope(allVariables.items(), treePathList);
+
+    // Sort the deduplicated variables according to the user's requested sort
+    final var fieldSortings = variableQuery.sort().getFieldSortings();
+    sortVariables(dedupedVariables, fieldSortings);
+
+    // Apply offset-based pagination to the deduplicated and sorted result.
+    // Cursor-based pagination (after/before) is not supported for this endpoint because
+    // deduplication and sorting are performed in-memory after fetching from the search backend.
+    // The Tasklist UI uses offset-based pagination for variables exclusively.
```
Comment (tmetzke) [inline service/src/main/java/io/camunda/service/UserTaskServices.java]: 🔧 We can scratch this, not relevant for this service method.
```suggestion
```

File: service/src/main/java/io/camunda/service/UserTaskServices.java (hunk 2 above)
Comment (tmetzke) [inline service/src/main/java/io/camunda/service/UserTaskServices.java:316]: 💭 If we use the original query (with its filtering AND sorting), do we still have to do a sorting afterwards on the service level? Couldn't we just retain the values in their place in the result list by iterating through them, keeping them where they are index-wise, and removing them from the result list if we find one that's closer to the innermost scope?

Rough idea:
- We use a `LinkedHashMap` (key `name`, value `VariableEntity`) as the result (to keep the order of additions).
- We iterate through the filtered and sorted search response items.
- We look into the map by name
  - If it does not exist, put the variable value by name.
  - If it does, check if our new one is closer to the innermost element using the tree path.
    - If it is, remove from result map, put new one to result map (gets a new position in the map, maybe the `put` already does this by itself, I'm not sure)
    - If it is not, continue to next (we found a more "outer one" and ignore it).

File: service/src/main/java/io/camunda/service/UserTaskServices.java [hunk 11]
```diff
@@ -280,6 +287,128 @@ public SearchQueryResult<VariableEntity> searchUserTaskVariables(
...
+    final var page = variableQuery.page();
+    final int size = page.size() != null ? page.size() : SearchQueryPage.DEFAULT_SIZE;
+    final int total = dedupedVariables.size();
+    final int from = page.from() != null ? page.from() : 0;
+    final int end = Math.min(from + size, total);
+    final List<VariableEntity> pageItems =
+        from < total ? new ArrayList<>(dedupedVariables.subList(from, end)) : List.of();
```
Comment (tmetzke) [inline service/src/main/java/io/camunda/service/UserTaskServices.java:337]: ❓ Have you checked what happens in a regular search request if I put `from` greater than or equal to `total`? Do I get an empty result or an error?

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 12]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
               .set(field(FlowNodeInstanceEntity::flowNodeInstanceKey), entity.elementInstanceKey())
               .set(field(FlowNodeInstanceEntity::treePath), "1/2/3")
               .create();
-      final var variable = Instancio.create(VariableEntity.class);
+      final var variable =
+          new VariableEntity(100L, "city", "Berlin", "Berlin", false, 3L, 1L, 1L, "proc", "t1");
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java:125]: 🔧 I believe we can keep this as is, no?

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 13]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
...
 
       when(client.getUserTask(any(Long.class))).thenReturn(entity);
       when(elementInstanceServices.getByKey(
               eq(flowNodeInstanceEntity.flowNodeInstanceKey()), any()))
           .thenReturn(flowNodeInstanceEntity);
-      when(variableServices.search(
-              eq(variableSearchQuery(q -> q.filter(f -> f.scopeKeys(1L, 2L, 3L)))), any()))
-          .thenReturn(SearchQueryResult.of(variable));
+      when(variableServices.search(any(), any()))
+          .thenReturn(new SearchQueryResult<>(1, false, List.of(variable), null, null));
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java]: 🔧 Can't we use the simple variant here? If not, why?

```suggestion
      when(variableServices.search(any(), any())).thenReturn(SearchQueryResult.of(variable));
```

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 14]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
...
+      final var entity = Instancio.create(UserTaskEntity.class);
+      final var flowNodeInstanceEntity =
+          Instancio.of(FlowNodeInstanceEntity.class)
+              .set(field(FlowNodeInstanceEntity::flowNodeInstanceKey), entity.elementInstanceKey())
+              .set(field(FlowNodeInstanceEntity::treePath), "1/2/3")
+              .create();
+      final var outerVar =
+          new VariableEntity(100L, "city", "Munich", "Munich", false, 1L, 1L, 1L, "proc", "t1");
+      final var innerVar =
+          new VariableEntity(101L, "city", "Berlin", "Berlin", false, 3L, 1L, 1L, "proc", "t1");
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java:159]: 👍 Great focused setup, using Instancio where possible, adjusting those values that need it.

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 15]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
...
+
+      when(client.getUserTask(any(Long.class))).thenReturn(entity);
+      when(elementInstanceServices.getByKey(
+              eq(flowNodeInstanceEntity.flowNodeInstanceKey()), any()))
+          .thenReturn(flowNodeInstanceEntity);
+      when(variableServices.search(any(), any()))
+          .thenReturn(new SearchQueryResult<>(2, false, List.of(outerVar, innerVar), null, null));
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java]: 🔧 Can't we use the simple variant here? If not, why? I believe this yields the exact same result.
```suggestion
      when(variableServices.search(any(), any()))
          .thenReturn(SearchQueryResult.of(outerVar, innerVar));
```

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 16]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
...
+      final var leafVar =
+          new VariableEntity(102L, "x", "leaf", "leaf", false, 3L, 1L, 1L, "proc", "t1");
+
+      when(client.getUserTask(any(Long.class))).thenReturn(entity);
+      when(elementInstanceServices.getByKey(
+              eq(flowNodeInstanceEntity.flowNodeInstanceKey()), any()))
+          .thenReturn(flowNodeInstanceEntity);
+      when(variableServices.search(any(), any()))
+          .thenReturn(
+              new SearchQueryResult<>(3, false, List.of(rootVar, midVar, leafVar), null, null));
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java]: 🔧 Same as above, I think we can use the `of` method.

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 17]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
...
+          .extracting(VariableEntity::value)
+          .containsExactly("v2");
+      assertThat(result.items())
+          .filteredOn(v -> v.name().equals("b"))
+          .extracting(VariableEntity::value)
+          .containsExactly("v4");
+      assertThat(result.items())
+          .filteredOn(v -> v.name().equals("c"))
+          .extracting(VariableEntity::value)
+          .containsExactly("v5");
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java]: 🔧 I think you can use `extracting` to get the name and value at the same time. Then you can simply validate the 3 resulting tuples.

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 18]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
...
+      final var flowNodeInstanceEntity =
+          Instancio.of(FlowNodeInstanceEntity.class)
+              .set(field(FlowNodeInstanceEntity::flowNodeInstanceKey), entity.elementInstanceKey())
+              .set(field(FlowNodeInstanceEntity::treePath), "1")
+              .create();
+      final var vars =
+          List.of(
+              new VariableEntity(1L, "zebra", "z", "z", false, 1L, 1L, 1L, "p", "t"),
+              new VariableEntity(2L, "apple", "a", "a", false, 1L, 1L, 1L, "p", "t"),
+              new VariableEntity(3L, "mango", "m", "m", false, 1L, 1L, 1L, "p", "t"));
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java]: 🔧 We should ensure deduplication also happens and doesn't mess with the sorting, i.e., insert variables to deduplicate.

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 19]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
...
+      final var flowNodeInstanceEntity =
+          Instancio.of(FlowNodeInstanceEntity.class)
+              .set(field(FlowNodeInstanceEntity::flowNodeInstanceKey), entity.elementInstanceKey())
+              .set(field(FlowNodeInstanceEntity::treePath), "1")
+              .create();
+      final var vars =
+          List.of(
+              new VariableEntity(1L, "a", "alpha", "alpha", false, 1L, 1L, 1L, "p", "t"),
+              new VariableEntity(2L, "b", "charlie", "charlie", false, 1L, 1L, 1L, "p", "t"),
+              new VariableEntity(3L, "c", "bravo", "bravo", false, 1L, 1L, 1L, "p", "t"));
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java]: 🔧 Same as above, we should include variables to deduplicate to ensure it doesn't mess with the sorting. We can also introduce innermost values that are not in line with the variable names to ensure sorting works as expected when sorting by something other than name, e.g., variable "b" could get an innermost value that puts it at the end of the list when sorting by value.

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 20]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
...
+          Instancio.of(FlowNodeInstanceEntity.class)
+              .set(field(FlowNodeInstanceEntity::flowNodeInstanceKey), entity.elementInstanceKey())
+              .set(field(FlowNodeInstanceEntity::treePath), "1")
+              .create();
+      final var vars =
+          List.of(
+              new VariableEntity(1L, "a", "1", "1", false, 1L, 1L, 1L, "p", "t"),
+              new VariableEntity(2L, "b", "2", "2", false, 1L, 1L, 1L, "p", "t"),
+              new VariableEntity(3L, "c", "3", "3", false, 1L, 1L, 1L, "p", "t"),
+              new VariableEntity(4L, "d", "4", "4", false, 1L, 1L, 1L, "p", "t"));
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java]: 🔧 Same as above, deduplication should really happen to ensure this doesn't mess with the paginated result.

File: service/src/test/java/io/camunda/service/UserTaskServiceTest.java [hunk 21]
```diff
@@ -117,23 +120,284 @@ public void shouldReturnUserTaskVariables() {
...
+          List.of(
+              new VariableEntity(10L, "alpha", "a", "a", false, 1L, 1L, 1L, "p", "t"),
+              new VariableEntity(20L, "bravo", "b", "b", false, 1L, 1L, 1L, "p", "t"));
+
+      when(client.getUserTask(any(Long.class))).thenReturn(entity);
+      when(elementInstanceServices.getByKey(
+              eq(flowNodeInstanceEntity.flowNodeInstanceKey()), any()))
+          .thenReturn(flowNodeInstanceEntity);
+      when(variableServices.search(any(), any()))
+          .thenReturn(new SearchQueryResult<>(2, false, vars, null, null));
```
Comment (tmetzke) [inline service/src/test/java/io/camunda/service/UserTaskServiceTest.java]: 🔧 The search result should return cursors, to ensure the servive level "strips" them from the DTO page.

**Review by tmetzke — COMMENTED** [review]
👍 Awesome, looks really good already 🚀
🔧 I added some potential improvement ideas for the dedup and its tests.

File: service/src/main/java/io/camunda/service/UserTaskServices.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (tsedekey) [reply service/src/main/java/io/camunda/service/UserTaskServices.java]: I switched to an explicit switch statement as suggested. The reflection approach avoided maintenance but at the cost of type safety and clarity. To address the maintenance trade-off, I added an alignment test (`shouldHaveComparatorForEveryVariableSortField`) that dynamically discovers all sort field methods on VariableSort.Builder via reflection and verifies that buildFieldComparator handles each one without throwing.

File: service/src/main/java/io/camunda/service/UserTaskServices.java (hunk 2 above)
Comment (tmetzke) [reply service/src/main/java/io/camunda/service/UserTaskServices.java:316]: A big bonus if this works: we don't have to mess around with all the sorting code in the service layer, too.

**Comment by tmetzke** [comment]
@claude[agent], please implement the open review hints from @tmetzke

**Review by tmetzke — APPROVED** [review]
👍 Looks good from my end

File: client-components/packages/camunda-api-zod-schemas/lib/8.9/user-task.ts [hunk 22]
```diff
@@ -193,7 +193,7 @@ type QueryVariablesByUserTaskResponseBody = z.infer<typeof queryVariablesByUserT
 const queryVariablesByUserTask: Endpoint<Pick<UserTask, 'userTaskKey'> & {truncateValues?: boolean}> = {
```
Comment (christoph-fricke) [inline client-components/packages/camunda-api-zod-schemas/lib/8.9/user-task.ts:193]: 💭 Not sure if we want to modify this endpoint definition or create a new one instead. Don't really have a strong preference to one approach.

**Review by christoph-fricke — APPROVED** [review]

**Comment by tmetzke** [comment]
Thanks a lot, @christoph-fricke 🙏
