### PR TITLE
Ensure missing index templates are created after restore

### LINKED ISSUE #40675: Improve backup/restore usability: always ensure missing index templates are created (>=8.8)
### Context / Problem
When restoring to a clean Elasticsearch/OpenSearch cluster, backups do not include the necessary index templates or ILM policies. After restore, if the templates are not manually restored, as explicitly instructed in Restore docs [Step 1: Restore Template](https://docs.camunda.io/docs/self-managed/operational-guides/backup-restore/restore/#1-restore-templates):, the application fails to start because of missing templates.
```
WARN                                                                                                                                                                   
    io.camunda.zeebe.util.retry.RetryDecorator - Retrying operation for 'init schema': attempt 184. Message: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/indices.get_index_template] failed
```
For versions prior to 8.8. this leads to new indices with incorrect mappings, producing mixed aliases with incompatible structures. This is tracked by: https://github.com/camunda/camunda/issues/32806

Since 8.8.3, we store a schema-version in ES metadata. If the stored version matches the app version, Schema Manager may skip initialization steps, even when templates are actually missing, leading to the problem described after a restore to an empty cluster.

### Motivation / Goal
- Make backup/restore robust and user-friendly by eliminating a manual step and preventing invalid/mixed indices after restore.

### Scope
- Web Apps data in Elasticsearch/OpenSearch: ensure required index and component templates and (if enabled) ILM policies are present after restore to an empty cluster.
- Non-goal: Zeebe records (Zeebe creates its templates when required).

### Proposed Solution
- Adjust Schema Manager logic to always validate and create any missing templates (and ILM policies if enabled) regardless of “schema-version” metadata. 
- Decouple the “schema-version equals app-version” fast-path from the concrete existence check of required templates.
- Ensure parity for Elasticsearch and OpenSearch.
- Check if we can/should make the templates part of the backup as proposed in https://github.com/camunda/camunda/issues/32806, and compare that to the solution proposed here.

### References
[Slack discussion](https://camunda.slack.com/archives/C08MRKHJ0CD/p1762513998203259)

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

Updated `SchemaManager` to separately initialize index templates and indices, ensuring missing templates are always created after restore in an empty Elasticsearch/OpenSearch cluster, outside upgrade scenarios.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #40675

### CODE REVIEW

File: schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java [hunk 1]
```diff
@@ -1612,4 +1612,9 @@ private String retentionMinAge(final JsonNode policyNode) {
 
     return deletedTransition.at("/conditions/min_index_age").asText();
   }
+
+  private void initalizeResources(final SchemaManager schemaManager) {
```
Comment (houssain-barouni) [inline schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java]: 🇺🇸

File: qa/acceptance-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java [hunk 2]
```diff
@@ -116,6 +119,17 @@ public class BackupRestoreIT {
   private MultiDbConfigurator configurator;
   private WorkingDirectory workingDirectory;
 
+  @BeforeAll
+  public static void beforeAll() {
+    // Non-snapshot version
+    VersionUtil.overrideVersionForTesting("8.10.0");
```
Comment (lilspikey) [inline qa/acceptance-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java:125]: Do we need to worry about this with any parallel tests?  Should we add `@Isolated` or similar to be safe?

Comment (houssain-barouni) [reply qa/acceptance-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java:125]: No, this is not really needed, the tests are run in parallel by maven across forks, each fork is a separate JVM, so static state is shared.
Within a fork, the test classes are run sequentially, and the version static state is reset in `@AfterAll`

**Review by lilspikey — APPROVED** [review]
