### PR TITLE
Backup status endpoint returns INCOMPLETE while backup is still in progress

### LINKED ISSUE #33717: Backup status endpoint returns INCOMPLETE while backup is still in progress
### 

### 

, , , , 

### 

### 

### Description

In some cases, the backup status endpoint returns an `INCOMPLETE` state, even though the backup is still actively progressing.

This seems to be an edge case where some of the snapshots in a backup have completed successfully, but the next ones have not yet been scheduled by ElasticSearch/OpenSearch.

### Steps to reproduce

* Trigger a backup for large data
* Actively call get back status endpoint
* Observe the status returned

### Current behavior

Get backup status sometimes returns INCOMPLETE

### Expected behavior

Get backup status should return IN_PROGRESS while the backup is in progress

### Environment

SM

### Version

- Component Version: 8.6.9

### Rootcause

_No response_

### Solution ideas

Implement a check in the status computation logic:
If the number of completed snapshots in a backup is fewer than 6, and none are in IN_PROGRESS or FAILED states:
* Check the in-memory queue for pending snapshots with the same backupId.
* If found → return IN_PROGRESS
* If not found → return INCOMPLETE

**Limitations**
In multi-node deployments of Operate, if the request is routed to a node where the backup has not been scheduled, the status may still be returned as INCOMPLETE.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

The GET backup status endpoint sometimes returns an `INCOMPLETE` state, even though the backup is still actively progressing.

This happens when some of the snapshots of a backup were successfully completed, but the next ones have not yet been scheduled by ElasticSearch/OpenSearch.

The GET backup status endpoint will fetch from ES/OS for example 2 snapshots with SUCCESS status out of 6,  and no status about the remaining snapshots as they were not scheduled yet by ES/OS. So this is mistakenly considered as `INCOMPLETE` backup status for the backup.

I managed to reproduce the issue by running [BackupRestoreTest](https://github.com/camunda/camunda/blob/stable/8.6/operate/qa/backup-restore-tests/src/test/java/io/camunda/operate/qa/backup/BackupRestoreTest.java#L126)  and reducing the retry delay to check the backup state to 10 milliseconds 

To solve this, the idea is to check the in-memory state to check if a given backup is still in progress, besides the snapshot states that we get from ES/OS. This has the limitation that it does not work in multi-mode deployment, if the GET backup status hits the node where the backup is not running. In this case, INCOMPLETE would be returned.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #33717

### CODE REVIEW

File: tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/os/BackupManagerOpenSearchTest.java [hunk 1]
```diff
@@ -253,4 +266,48 @@ public void shouldWaitForSnapshotTillCompleted() throws IOException {
...
+    // given
+    // run takeBackup in parallel to simulate an ongoing backup
+    when(openSearchClient.snapshot().create(any(CreateSnapshotRequest.class)))
+        .thenAnswer(
+            invocation -> {
+              Thread.sleep(1000);
+              return mock(CompletableFuture.class);
+            });
+    /*when(openSearchClient.snapshot().get(any(GetSnapshotRequest.class)))
+    .thenReturn(mock(GetSnapshotResponse.class));*/
```
Comment (RomanJRW) [inline tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/os/BackupManagerOpenSearchTest.java]: needs removing

File: tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/es/BackupManagerElasticsearchTest.java [hunk 2]
```diff
@@ -64,20 +69,28 @@ class BackupManagerElasticsearchTest {
...
   @InjectMocks private BackupManagerElasticSearch backupManager;
 
   @Mock(strictness = Strictness.LENIENT)
-  @Qualifier("tasklistObjectMapper")
   private ObjectMapper objectMapper;
 
+  @Mock private List<Prio1Backup> prio1BackupIndices;
+  @Mock private List<Prio2Backup> prio2BackupTemplates;
+  @Mock private List<Prio3Backup> prio3BackupTemplates;
+  @Mock private List<Prio4Backup> prio4BackupIndices;
```
Comment (RomanJRW) [inline tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/es/BackupManagerElasticsearchTest.java:87]: what are these used for? Maybe overlooking something obvious here

File: tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/es/BackupManagerElasticsearchTest.java [hunk 3]
```diff
@@ -64,20 +69,28 @@ class BackupManagerElasticsearchTest {
   @Mock(answer = Answers.RETURNS_DEEP_STUBS)
   private RestHighLevelClient searchClient;
 
-  @Mock(answer = Answers.RETURNS_DEEP_STUBS)
+  @Mock(answer = Answers.RETURNS_DEEP_STUBS, strictness = Strictness.LENIENT)
```
Comment (RomanJRW) [inline tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/es/BackupManagerElasticsearchTest.java]: Similar to comment below, what is the need to change the strictness?

**Review by RomanJRW — COMMENTED** [review]
I had a quick review to help unblock progress, and the changes look reasonable to me with just a couple of clarifying questions ✅

File: tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/es/BackupManagerElasticsearchTest.java (hunk 2 above)
Comment (houssain-barouni) [reply tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/es/BackupManagerElasticsearchTest.java:87]: since I added a test with `takeBackup()` call, I got an NPE, since `takeBackup()` makes use of these autowired fields.
With this `@Mock`, they will be injected as mocks to `@InjectMocks private BackupManagerElasticSearch backupManager`

File: tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/es/BackupManagerElasticsearchTest.java (hunk 3 above)
Comment (houssain-barouni) [reply tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/es/BackupManagerElasticsearchTest.java]: in `@BeforeEach`, I added `when(tasklistProperties.getVersion()).thenReturn("8.6.0");` that was required in the new test. this mocking was not used in the other tests, so it complained about it. 
I could have just added it to the new test itself, but I think it can be useful for future tests. So I marked it as LENIENT to skip the warning

Comment (houssain-barouni) [reply tasklist/webapp/src/test/java/io/camunda/tasklist/webapp/es/backup/es/BackupManagerElasticsearchTest.java]: `LENIENT` is removed

**Review by buccarel — APPROVED** [review]
🚀
