### PR TITLE
fix: operate pi incident handling

### LINKED ISSUE #42059: Process Instance level incidents are not handled correctly in secondary storage
### 

### 

, , , 

### 

### 

### Description

The engine can throw incidents on process instance level and not only on activity level. Operate's importer is not able to handle such incidents causing data corruption in the `operate-list-view` index. 

### Steps to reproduce

1. Create a Process Definition with Execution Listener on the root
```
<bpmn:process id="Process_ID" isExecutable="true" name="name">
    <bpmn:extensionElements>
      <zeebe:versionTag value="2.0.4-dev"/>
      <zeebe:executionListeners>
        <zeebe:executionListener eventType="start" retries="1" type="startListener"/>
        <zeebe:executionListener eventType="end" type="endListener"/>
      </zeebe:executionListeners>
    </bpmn:extensionElements>
```
2. Have a Job Worker registered handle the execution listeners
3. Have Job Workers **fail** when they get invoked
4. Start a process instance for this definition

### Current behavior

The engine will raise an Incident in the root of the Process Instance and not bound to an Activity. When operate handles the [incident](https://github.com/camunda/camunda/blob/ccaf688b53a82186d1bea04fc618f28f646871b7/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/FlowNodeInstanceZeebeRecordProcessor.java#L106) it will overwrite the Process Instance document in `operate-list-view` index as the record's `elementInstanceKey` is the `processInstanceKey`.

This results in losing the Process Instance document from `operate-list-view` as the `joinRelation.type` is being set to `activity`. This results in documents with the following format: 

```json
{
        "_index": "operate-list-view-8.3.0_",
        "_id": "2251799864209095",
        "_score": 2.692649,
        "_routing": "2251799864209095",
        "_source": {
          "id": "2251799864209095",
          "key": 2251799864209095,
          "partitionId": 1,
          "processInstanceKey": 2251799864209095,
          "activityId": "Qmc.PatchPort.2",
          "activityState": null,
          "activityType": null,
          "errorMessage": "<ERROR FROM LISTENER>",
          "incident": false,
          "jobFailedWithRetriesLeft": false,
          "tenantId": "<default>",
          "position": 101078708,
          "positionIncident": 101078867,
          "positionJob": null,
          "joinRelation": {
            "name": "activity",
            "parent": 2251799864209095
          },
          "processVersionTag": "2.0.3",
          "processName": "<PROCESS_NAME>",
          "bpmnProcessId": "<PROCESS_ID>",
          "state": "ACTIVE",
          "processVersion": <VERSION>,
          "startDate": "<TIMESTAMP>",
          "processDefinitionKey": 2251799861683508
        }
      }
}
```
Note that `_id==id==key==processInstanceKey==joinRelation.parent`, which would not be the case for a proper Activity record, and that `_id` field can never be updated by ES/OS restrictions.

### Expected behavior

The `operate-list-view` entry for the process instance should not be modified and instead have the incident information linked to it without overriding it's type (joinRelation)

When such an incident is being handled by Operate's importer different handling should be provided for this case. You can identify such incidents because `elementInstanceKey == processInstanceKey` in the incident record, example:

```
{
  "errorType" : "EXECUTION_LISTENER_NO_RETRIES",
  "errorMessage" : "No more retries left.",
  "bpmnProcessId" : "process",
  "processDefinitionKey" : 2251799813685251,
  "processInstanceKey" : 2251799813685252,
  "elementId" : "process",
  "elementInstanceKey" : 2251799813685252,
  "jobKey" : 2251799813685254,
  "variableScopeKey" : 2251799813685252,
  "tenantId" : "<default>",
  "elementInstancePath" : [ [ 2251799813685252 ] ],
  "processDefinitionPath" : [ 2251799813685251 ],
  "callingElementPath" : [ ]
}
```

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- Component Version: 8.9, 8.8, 8.7, 8.6 ...

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Ref incident: [#inc-support-30053-help-with-stuck-operate-post-importer](https://camunda.slack.com/archives/C09SD8XK1N3)

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by panagiotisgts**
## Description

Correctly handle Process Instance level incidents that can occur with the usage of Start/End execution listeners.
- Enable `ProcessInstanceForListViewEntity` to contain information regarding incidents
- Correctly update `ProcessInstance` document when a process instance level incident document is being imported
- Handle post importer process of such process instance level incidents

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #42059

### CODE REVIEW

File: operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java [hunk 1]
```diff
@@ -269,6 +297,7 @@ public void processProcessInstanceRecord(
         updateFields.put(ListViewTemplate.PROCESS_VERSION, piEntity.getProcessVersion());
         updateFields.put(ListViewTemplate.PROCESS_KEY, piEntity.getProcessDefinitionKey());
         updateFields.put(ListViewTemplate.BPMN_PROCESS_ID, piEntity.getBpmnProcessId());
+        updateFields.put(ListViewTemplate.TREE_PATH, piEntity.getTreePath());
```
Comment (houssain-barouni) [inline operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java:286]: ❓ is this related to the issue? does this mean we never update the tree path, in case of process migration ?

File: operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java [hunk 2]
```diff
@@ -131,30 +132,58 @@ public void processIncidentRecord(final Record record, final BatchRequest batchR
...
+      piEntity.setPartitionId(record.getPartitionId());
+      piEntity.setTenantId(tenantOrDefault(recordValue.getTenantId()));
+      piEntity.setProcessDefinitionKey(recordValue.getProcessDefinitionKey());
+      piEntity.setPositionIncident(record.getPosition());
+
+      if (intentStr.equals(IncidentIntent.CREATED.name())) {
+        piEntity.setErrorMessage(StringUtils.trimWhitespace(recordValue.getErrorMessage()));
+      } else if (intentStr.equals(IncidentIntent.RESOLVED.name())) {
+        piEntity.setErrorMessage(null);
+      }
```
Comment (houssain-barouni) [inline operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java]: ❓  these new fields are consumed by what? For now I see it is used only in the tests

File: operate/importer/src/main/java/io/camunda/operate/zeebeimport/post/elasticsearch/ElasticsearchIncidentPostImportAction.java [hunk 3]
```diff
@@ -286,6 +286,7 @@ protected boolean processIncidents(final AdditionalData data, final PendingIncid
         incident.setState(newState);
 
         final List<String> fniIds = incidentTreePath.extractFlowNodeInstanceIds();
+        fniIds.removeAll(piIds);
```
Comment (houssain-barouni) [inline operate/importer/src/main/java/io/camunda/operate/zeebeimport/post/elasticsearch/ElasticsearchIncidentPostImportAction.java:289]: ❓ is this needed to unblock the post importer, for the data written before the fix?

File: operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/FlowNodeInstanceZeebeRecordProcessor.java [hunk 4]
```diff
@@ -108,6 +108,11 @@ public void processIncidentRecord(final Record record, final BatchRequest batchR
     final String intentStr = record.getIntent().name();
     final IncidentRecordValue recordValue = (IncidentRecordValue) record.getValue();
 
+    if (recordValue.getProcessInstanceKey() == recordValue.getElementInstanceKey()) {
+      // Incident is on process instance level, so no need to update FNI
```
Comment (houssain-barouni) [inline operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/FlowNodeInstanceZeebeRecordProcessor.java:112]: ❓ maybe we should add a debug log, just in case?

**Review by houssain-barouni — COMMENTED** [review]
Thanks for taking care of the fix
I left some questions

File: operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java (hunk 1 above)
Comment (panagiotisgts) [reply operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java:286]: Not sure how migration is handled, but for this issue, since the TreePath is initially `null` as the Incident record is imported first, the tree path will never get updated when the PI record is imported.

File: operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java (hunk 2 above)
Comment (panagiotisgts) [reply operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java]: I've only added them for consistency, since we have PI level incidents and the FNI documents in the `list-view` index already have these fields set. Another thought I initially had was that Operate's UI would not be able to display such incidents, but turns out they are retrieved in another fashion. Can drop them if you consider them uneccessary :shrug:

File: operate/importer/src/main/java/io/camunda/operate/zeebeimport/post/elasticsearch/ElasticsearchIncidentPostImportAction.java (hunk 3 above)
Comment (panagiotisgts) [reply operate/importer/src/main/java/io/camunda/operate/zeebeimport/post/elasticsearch/ElasticsearchIncidentPostImportAction.java:289]: The PI incidents generate tree path terms when analyzed via the ES tokenizer such as: 
```
PI_2251799813685262/FN_Process_104uykb/FNI_2251799813685262
```

As you can see the FNI_ and the PI_ value is the same, and the FN activity ID is definitely an activity.

Thus the post importer tries to update an FNI in the `flownode-instance` index. Now i'm not that familiar with how the ES Analyzer tokenizer behaves. But removing these ids from the list fixes the dataset of FNIs to be updated.

File: operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java (hunk 2 above)
Comment (houssain-barouni) [reply operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java]: I think it is better to drop them if they are not needed, because old documents will not have these fields populated, and in the future, we may assume they are, which will add more confusion 😄

Comment (panagiotisgts) [reply operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java]: Sure yeah. But also the FNI message and incidentPosition are never used aswell, at least for 8.6 :sweat_smile:

File: operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java [hunk 5]
```diff
@@ -131,30 +132,48 @@ public void processIncidentRecord(final Record record, final BatchRequest batchR
...
+      piEntity.setKey(recordValue.getElementInstanceKey());
+      piEntity.setProcessInstanceKey(processInstanceKey);
+      piEntity.setPartitionId(record.getPartitionId());
+      piEntity.setTenantId(tenantOrDefault(recordValue.getTenantId()));
+      piEntity.setProcessDefinitionKey(recordValue.getProcessDefinitionKey());
 
-    // set parent
-    final Long processInstanceKey = recordValue.getProcessInstanceKey();
-    entity.getJoinRelation().setParent(processInstanceKey);
+      entity = piEntity;
```
Comment (houssain-barouni) [inline operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java]: @panagiotisgts , in the end what is the added value of creating the processInstance from the incident? can we just skip it? and wait for the process Instance record that should have the complete data?

File: operate/importer/src/main/java/io/camunda/operate/zeebeimport/post/elasticsearch/ElasticsearchIncidentPostImportAction.java (hunk 3 above)
Comment (houssain-barouni) [reply operate/importer/src/main/java/io/camunda/operate/zeebeimport/post/elasticsearch/ElasticsearchIncidentPostImportAction.java:289]: sorry, it is not clear for me what is the expected processInstanceKey and FNIkey in this case? in this case should we flag the FNI having key `2251799813685262` with the incident? what about the process instance , how can we find its key?

Comment (panagiotisgts) [reply operate/importer/src/main/java/io/camunda/operate/zeebeimport/post/elasticsearch/ElasticsearchIncidentPostImportAction.java:289]: The record which `2251799813685262` refers to is actually the process instance, since for process instance level incidents, there is nothing pointing to an FNI.

So after tokenization, there is an FNI reference for this key which is invalid. Not removing this reference causes the post importer to again get blocked because it's trying to update an FNI record in `operate-flownode-instance` index which does not exist.

Comment (houssain-barouni) [reply operate/importer/src/main/java/io/camunda/operate/zeebeimport/post/elasticsearch/ElasticsearchIncidentPostImportAction.java:289]: Thanks for the clarification, should we handle the case `fniIds` is empty after removing the `piIds` ? some of the queries may not work as expected with an empty list

File: operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java (hunk 5 above)
Comment (panagiotisgts) [reply operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java]: Weeeell 🤷  If we don't track the message and the incident position it's probably just fine to skip updating the PI for the incident. But why where they persisted for FNIs to begin with if they aren't used even there 😅

File: operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java (hunk 2 above)
Comment (houssain-barouni) [reply operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java]: it must be something old, that was never cleaned-up in the importer, but this requires some archeology to confirm 🦖

**Comment by ArezooAzar** [comment]
@panagiotisgts : Tested, works as expected.

**Review by houssain-barouni — APPROVED** [review]
LGTM!
