### PR TITLE
Try fix flaky HealthMonitoringTest and DeploymentClusteredTest

### LINKED ISSUE #5005: HealthMonitoringTest.shouldReportUnhealthyWhenRaftInactive flaky
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1798)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1868)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at app//io.zeebe.broker.Broker.lambda$actorSchedulerStep$12(Broker.java:194)
	at app//io.zeebe.broker.Broker$$Lambda$465/0x0000000840694040.close(Unknown Source)
	at app//io.zeebe.broker.bootstrap.CloseProcess.lambda$closingStepByStep$0(CloseProcess.java:56)
	at app//io.zeebe.broker.bootstrap.CloseProcess$$Lambda$989/0x000000084095a440.run(Unknown Source)
	at app//io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88)
	at app//io.zeebe.broker.bootstrap.CloseProcess.closingStepByStep(CloseProcess.java:56)
	at app//io.zeebe.broker.bootstrap.CloseProcess$$Lambda$988/0x000000084095a040.run(Unknown Source)
	at app//io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88)
	at app//io.zeebe.broker.bootstrap.CloseProcess.closeReverse(CloseProcess.java:37)
	at app//io.zeebe.broker.Broker.lambda$close$24(Broker.java:405)
	at app//io.zeebe.broker.Broker$$Lambda$987/0x0000000840959c40.accept(Unknown Source)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base@11.0.3/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at app//io.zeebe.broker.Broker.lambda$close$25(Broker.java:403)
	at app//io.zeebe.broker.Broker$$Lambda$986/0x0000000840959840.run(Unknown Source)
	at app//io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21)
	at app//io.zeebe.broker.Broker.close(Broker.java:398)
	at app//io.zeebe.broker.test.EmbeddedBrokerRule.stopBroker(EmbeddedBrokerRule.java:191)
	at app//io.zeebe.broker.test.EmbeddedBrokerRule.after(EmbeddedBrokerRule.java:140)
	at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base@11.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.3/java.lang.Thread.run(Thread.java:834)
</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>
<pre>
System Ou:

12:42:47.980 [] [main] INFO  io.zeebe.test - Test started: shouldReportUnhealthyWhenRaftInactive(io.zeebe.broker.it.health.HealthMonitoringTest)
12:42:48.009 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Starting socket assignment with testForkNumber 4 and testMavenId 2
12:42:48.021 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 29800 for test fork 4 with range PortRange{host='localhost', basePort=29800, maxOffset=100, currentOffset=1}
12:42:48.023 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 29801 for test fork 4 with range PortRange{host='localhost', basePort=29800, maxOffset=100, currentOffset=2}
12:42:48.024 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 29802 for test fork 4 with range PortRange{host='localhost', basePort=29800, maxOffset=100, currentOffset=3}
12:42:48.024 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 29803 for test fork 4 with range PortRange{host='localhost', basePort=29800, maxOffset=100, currentOffset=4}
12:42:48.025 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 29804 for test fork 4 with range PortRange{host='localhost', basePort=29800, maxOffset=100, currentOffset=5}
12:42:48.055 [] [Time-limited test] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/00b2a541-2a8d-41a6-a415-0d8f52f26fc5
12:42:48.097 [] [Time-limited test] INFO  io.zeebe.broker.system - Version: 0.25.0-SNAPSHOT
12:42:48.229 [] [Time-limited test] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 29802,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 29802,
      "address" : "0.0.0.0:29802",
      "advertisedAddress" : "0.0.0.0:29802"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 29803,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 29803,
      "address" : "0.0.0.0:29803",
      "advertisedAddress" : "0.0.0.0:29803"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 29804,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 29804,
      "address" : "0.0.0.0:29804",
      "advertisedAddress" : "0.0.0.0:29804"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 1,
    "clusterSize" : 1,
    "clusterName" : "zeebe-cluster",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT2S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : [ "/tmp/00b2a541-2a8d-41a6-a415-0d8f52f26fc5/data" ],
    "logSegmentSize" : "512MB",
    "snapshotPeriod" : "PT5M",
    "logIndexDensity" : 1,
    "diskUsageReplicationWatermark" : 0.9,
    "diskUsageCommandWatermark" : 0.8,
    "diskUsageMonitoringInterval" : "PT1S",
    "logSegmentSizeInBytes" : 536870912,
    "atomixStorageLevel" : "DISK",
    "freeDiskSpaceCommandWatermark" : 0,
    "freeDiskSpaceReplicationWatermark" : 0
  },
  "exporters" : {
    "test-recorder" : {
      "jarPath" : null,
      "className" : "io.zeebe.test.util.record.RecordingExporter",
      "args" : null,
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 29800,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:29803",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 29801,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT2S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      }
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "initialized" : true,
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixedLimit" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
12:42:48.271 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/13]: actor scheduler
12:42:48.275 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/13]: actor scheduler started in 3 ms
12:42:48.275 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/13]: membership and replication protocol
12:42:51.991 [] [Time-limited test] DEBUG io.atomix.utils.serializer.Namespace - (no name): class io.atomix.utils.time.LogicalTimestamp already registered as 53. Skipping 58.
12:42:51.992 [] [Time-limited test] DEBUG io.atomix.utils.serializer.Namespace - (no name): class io.atomix.utils.time.WallClockTimestamp already registered as 54. Skipping 59.
12:42:52.000 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/13]: membership and replication protocol started in 3725 ms
12:42:52.000 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/13]: command api transport
12:42:52.055 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:29802
12:42:52.063 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
12:42:52.064 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bound command API to 0.0.0.0:29802 
12:42:52.076 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/13]: command api transport started in 75 ms
12:42:52.076 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/13]: command api handler
12:42:52.159 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/13]: command api handler started in 82 ms
12:42:52.159 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/13]: subscription api
12:42:52.196 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/13]: subscription api started in 37 ms
12:42:52.196 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/13]: embedded gateway
12:42:52.204 [] [Time-limited test] INFO  io.zeebe.gateway - Version: 0.25.0-SNAPSHOT
12:42:52.205 [] [Time-limited test] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 29800,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "0.0.0.0:29803",
    "requestTimeout" : "PT15S",
    "clusterName" : "zeebe-cluster",
    "memberId" : "gateway",
    "host" : "0.0.0.0",
    "port" : 29801,
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT2S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "0.0.0.0",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  },
  "longPolling" : {
    "enabled" : true
  },
  "initialized" : true,
  "enable" : true
}
12:42:52.344 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/13]: embedded gateway started in 148 ms
12:42:52.344 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/13]: cluster services
12:42:52.344 [] [Time-limited test] INFO  io.atomix.core.Atomix - 0.25.0-SNAPSHOT (revision N/A built on 2020-07-19 12:38:28)
12:42:52.353 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:29803
12:42:52.354 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
12:42:52.392 [] [netty-unicast-event-nio-client-0] INFO  io.atomix.cluster.messaging.impl.NettyUnicastService - UDP server listening for connections on 0.0.0.0:29803
12:42:52.394 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
12:42:52.397 [] [atomix-cluster-0] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - Nodes from discovery service []
12:42:52.399 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
12:42:52.399 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
12:42:52.400 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started
12:42:52.402 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
12:42:52.437 [] [atomix-0] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=1, group=raft-partition}
12:42:52.468 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 500.
12:42:52.468 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 501.
12:42:52.468 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 502.
12:42:52.468 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 503.
12:42:52.468 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 504.
12:42:52.468 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 505.
12:42:52.469 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 506.
12:42:52.469 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 507.
12:42:52.469 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 508.
12:42:52.469 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 509.
12:42:52.469 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 510.
12:42:52.469 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 511.
12:42:52.469 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 512.
12:42:52.469 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 513.
12:42:52.472 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 530.
12:42:52.472 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 531.
12:42:52.476 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 535.
12:42:52.476 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 536.
12:42:52.476 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 537.
12:42:52.477 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 538.
12:42:52.477 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 541.
12:42:52.477 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 542.
12:42:52.477 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 543.
12:42:52.477 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 544.
12:42:52.477 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 545.
12:42:52.477 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 546.
12:42:52.478 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 547.
12:42:52.478 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 548.
12:42:52.478 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 549.
12:42:52.478 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 550.
12:42:52.478 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: class java.util.ArrayList already registered as 27. Skipping 551.
12:42:52.478 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: class java.util.LinkedList already registered as 28. Skipping 552.
12:42:52.478 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: class java.util.Collections$EmptyList already registered as 41. Skipping 553.
12:42:52.478 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: class java.util.HashSet already registered as 29. Skipping 554.
12:42:52.480 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftProtocol: void already registered as 9. Skipping 557.
12:42:52.482 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 600.
12:42:52.483 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 601.
12:42:52.483 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 604.
12:42:52.483 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 605.
12:42:52.483 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 606.
12:42:52.483 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 607.
12:42:52.483 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 608.
12:42:52.483 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 609.
12:42:52.483 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 610.
12:42:52.484 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: void already registered as 9. Skipping 611.
12:42:52.484 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: class java.util.ArrayList already registered as 27. Skipping 612.
12:42:52.484 [] [atomix-0] DEBUG io.atomix.utils.serializer.Namespace - RaftStorage: class java.util.HashSet already registered as 29. Skipping 613.
12:42:52.739 [] [atomix-0] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=1, version=1, index=1}
12:42:52.872 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
12:42:52.880 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Single member cluster. Transitioning directly to candidate.
12:42:52.880 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE
12:42:52.881 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.raft.roles.FollowerRole$$Lambda$622/0x0000000840794c40@397078a7 not registered
12:42:52.885 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Single member cluster. Transitioning directly to leader.
12:42:52.892 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Set term 1
12:42:52.896 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Voted for 0
12:42:52.896 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to LEADER
12:42:52.942 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 0
12:42:53.077 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server started successfully!
12:42:53.078 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.partition.impl.RaftPartitionServer - Successfully started server for partition PartitionId{id=1, group=raft-partition}
12:42:53.078 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
12:42:53.079 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.primitive.partition.impl.DefaultPartitionService - Started class io.atomix.primitive.partition.impl.DefaultPartitionService
12:42:53.080 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/13]: cluster services started in 736 ms
12:42:53.080 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/13]: topology manager
12:42:53.082 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/13]: topology manager started in 2 ms
12:42:53.082 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/13]: monitoring services
12:42:53.088 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [9/13]: monitoring services started in 6 ms
12:42:53.088 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/13]: disk space monitor
12:42:53.091 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/13]: disk space monitor started in 3 ms
12:42:53.091 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [11/13]: leader management request handler
12:42:53.097 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [11/13]: leader management request handler started in 6 ms
12:42:53.097 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [12/13]: zeebe partitions
12:42:53.100 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
12:42:53.149 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAQAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyOTgwMgUAAAwAAA8AAAAwLjI1LjAtU05BUFNIT1Q=, event-service-topics-subscribed=HwEBAwFqb2JzQXZhaWxhYmzl}
12:42:53.155 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {} and terms {}.
12:42:53.179 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Removing follower partition service for partition PartitionId{id=1, group=raft-partition}
12:42:53.182 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER
12:42:53.183 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Installing leader partition service for partition PartitionId{id=1, group=raft-partition}
12:42:54.184 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/00b2a541-2a8d-41a6-a415-0d8f52f26fc5/data/raft-partition/partitions/1/runtime'.
12:42:54.413 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
12:42:54.426 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
12:42:54.765 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@32fd36ab)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@76ba6a82, configuration: Configuration(false)]
12:42:55.090 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
12:42:55.148 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@39050d60)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@1873c37f, configuration: Configuration(false)]
12:42:55.173 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@7ed9d673)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@7fa17795, configuration: Configuration(false)]
12:42:55.384 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
12:42:55.439 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
12:42:55.440 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAQAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyOTgwMgUAAQEAAAAADAABAQAAAAEAAAAAAAAADwAAADAuMjUuMC1TTkFQU0hPVA==, event-service-topics-subscribed=HwEBAwFqb2JzQXZhaWxhYmzl}
12:42:55.449 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER} and terms {1=1}.
12:42:55.455 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 2355 ms
12:42:55.455 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 2355 ms.
12:42:55.456 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [12/13]: zeebe partitions started in 2359 ms
12:42:55.456 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [13/13]: register diskspace usage listeners
12:42:55.456 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [13/13]: register diskspace usage listeners started in 0 ms
12:42:55.456 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 13 steps in 7185 ms.
12:42:55.537 [] [Time-limited test] INFO  io.zeebe.broker.test - 
====
Broker startup time: 7543
====

12:42:55.556 [] [Time-limited test] INFO  io.zeebe.broker.test - 
====
Client startup time: 18
====

12:42:55.558 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
12:42:55.688 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Recovered exporter 'Broker-0-Exporter-1' from snapshot at lastExportedPosition -1
12:42:55.688 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'test-recorder'
12:42:55.699 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={NULL_VAL=true, EVENT=true, SBE_UNKNOWN=true, COMMAND_REJECTION=true, COMMAND=true}, acceptValueTypes={NULL_VAL=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, SBE_UNKNOWN=true, JOB=true, ERROR=true, TIMER=true, JOB_BATCH=true, DEPLOYMENT=true, INCIDENT=true, VARIABLE_DOCUMENT=true, MESSAGE_SUBSCRIPTION=true, WORKFLOW_INSTANCE=true, VARIABLE=true, WORKFLOW_INSTANCE_SUBSCRIPTION=true, MESSAGE=true, WORKFLOW_INSTANCE_CREATION=true, WORKFLOW_INSTANCE_RESULT=true}}
12:42:55.745 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Open exporter with id 'test-recorder'
12:42:55.749 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.zeebe.ZeebeRaftStateMachine - ZeebeRaftStateMachine{raft-partition-partition-1} - Closing state machine raft-partition-partition-1
12:42:55.751 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Closing segment: JournalSegment{id=1, version=1, index=1}
12:42:55.752 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] ERROR io.zeebe.broker.system - Partition-1 failed, marking it as unhealthy
12:42:55.755 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition role transitioning from LEADER to INACTIVE
12:42:55.762 [] [Time-limited test] INFO  io.zeebe.broker.test - Client Rule assumption: Test execution time: 202
12:42:55.765 [] [Time-limited test] INFO  io.zeebe.broker.test - Client closing time: 2
12:42:55.766 [] [Time-limited test] INFO  io.zeebe.broker.test - Test execution time: 228
12:42:55.768 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [1/13]: register diskspace usage listeners
12:42:55.768 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [1/13]: register diskspace usage listeners closed in 0 ms
12:42:55.768 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [2/13]: zeebe partitions
12:42:55.769 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1
12:42:55.770 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Close appender for log stream logstream-raft-partition-partition-1
12:42:55.771 [logstream-raft-partition-partition-1-write-buffer] [Broker-0-zb-actors-1] DEBUG io.zeebe.dispatcher - Dispatcher closed
12:42:55.772 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-1 close 3 readers
12:42:55.772 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Close log storage with name logstream-raft-partition-partition-1
12:42:55.772 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.system.partitions.ZeebePartition$$Lambda$685/0x00000008407bcc40@30f011c5 successfully
12:42:55.773 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.system.partitions.ZeebePartition$$Lambda$687/0x00000008407bc440@489003a2 successfully
12:42:55.773 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.system.partitions.ZeebePartition$$Lambda$688/0x00000008407bb840@2adddc9a successfully
12:42:55.773 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.system.partitions.ZeebePartition$$Lambda$689/0x00000008407bbc40@1a939e3d successfully
12:42:55.881 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/00b2a541-2a8d-41a6-a415-0d8f52f26fc5/data/raft-partition/partitions/1/runtime'.
12:42:55.882 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.system.partitions.ZeebePartition$$Lambda$703/0x00000008407d2440@67fe2d76 successfully
12:42:55.882 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.logstreams.LogDeletionService@2303141f successfully
12:42:55.882 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.system.partitions.ZeebePartition$$Lambda$705/0x00000008407d2c40@25e71434 successfully
12:42:55.883 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
12:42:55.884 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closed io.zeebe.engine.processing.streamprocessor.StreamProcessor@130d8e0e successfully
12:42:55.884 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.system.partitions.ZeebePartition$$Lambda$687/0x00000008407bc440@5c0bd816 successfully
12:42:55.885 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector@7a8479c6 successfully
12:42:55.885 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.system.partitions.ZeebePartition$$Lambda$905/0x00000008408f3840@67df9416 successfully
12:42:55.885 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1 closed in 116 ms
12:42:55.885 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 partitions succeeded. Closed 1 steps in 117 ms.
12:42:55.886 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [2/13]: zeebe partitions closed in 118 ms
12:42:55.886 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [3/13]: leader management request handler
12:42:55.886 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [3/13]: leader management request handler closed in 0 ms
12:42:55.886 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [4/13]: disk space monitor
12:42:55.886 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [4/13]: disk space monitor closed in 0 ms
12:42:55.886 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [5/13]: monitoring services
12:42:55.887 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [5/13]: monitoring services closed in 0 ms
12:42:55.887 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [6/13]: topology manager
12:42:55.887 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [6/13]: topology manager closed in 0 ms
12:42:55.887 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [7/13]: cluster services
12:42:55.887 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [7/13]: cluster services closed in 0 ms
12:42:55.887 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [8/13]: embedded gateway
12:42:55.900 [] [Time-limited test] DEBUG io.zeebe.gateway - Closing gateway broker client ...
12:42:55.901 [] [Time-limited test] DEBUG io.zeebe.gateway - topology manager closed
12:42:55.902 [] [Time-limited test] DEBUG io.zeebe.gateway - Gateway broker client closed.
12:42:55.902 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [8/13]: embedded gateway closed in 15 ms
12:42:55.902 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [9/13]: subscription api
12:42:55.902 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [9/13]: subscription api closed in 0 ms
12:42:55.902 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [10/13]: command api handler
12:42:55.904 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [10/13]: command api handler closed in 2 ms
12:42:55.904 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [11/13]: command api transport
12:42:57.959 [] [ForkJoinPool.commonPool-worker-3] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
12:42:57.962 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [11/13]: command api transport closed in 2058 ms
12:42:57.962 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [12/13]: membership and replication protocol
12:42:57.965 [] [Time-limited test] ERROR io.atomix.raft.partition.RaftPartition - Error on shutdown partition: PartitionId{id=1, group=raft-partition}.
java.lang.IllegalStateException: Server not running
	at io.atomix.raft.impl.DefaultRaftServer.shutdown(DefaultRaftServer.java:128) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.stop(RaftPartitionServer.java:133) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.closeServer(RaftPartition.java:183) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.close(RaftPartition.java:173) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.close(RaftPartitionGroup.java:230) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.stop(DefaultPartitionService.java:102) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.core.Atomix.stopServices(Atomix.java:533) ~[atomix-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.cluster.AtomixCluster.stop(AtomixCluster.java:330) ~[atomix-cluster-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.atomix.core.Atomix.stop(Atomix.java:526) ~[atomix-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.Broker.lambda$atomixCreateStep$15(Broker.java:216) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.CloseProcess.lambda$closingStepByStep$0(CloseProcess.java:56) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.CloseProcess.closingStepByStep(CloseProcess.java:56) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.CloseProcess.closeReverse(CloseProcess.java:37) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.Broker.lambda$close$24(Broker.java:405) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
	at io.zeebe.broker.Broker.lambda$close$25(Broker.java:403) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.Broker.close(Broker.java:398) [zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.test.EmbeddedBrokerRule.stopBroker(EmbeddedBrokerRule.java:191) [zeebe-broker-0.25.0-SNAPSHOT-tests.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.test.EmbeddedBrokerRule.after(EmbeddedBrokerRule.java:140) [zeebe-broker-0.25.0-SNAPSHOT-tests.jar:0.25.0-SNAPSHOT]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282) [junit-4.13.jar:4.13]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
12:42:57.974 [] [Time-limited test] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
12:42:57.975 [] [Time-limited test] INFO  io.atomix.primitive.partition.impl.DefaultPartitionService - Stopped
12:42:57.976 [] [atomix-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Stopped
12:42:57.977 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Stopped
12:42:57.978 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Member deactivated: Member{id=0, address=0.0.0.0:29803, properties={brokerInfo=EADJAAAAAQAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyOTgwMgUAAQEAAAAADAABAQAAAAEAAAAAAAAADwAAADAuMjUuMC1TTkFQU0hPVA==, event-service-topics-subscribed=HwEBAwFqb2JzQXZhaWxhYmzl}}
12:42:57.979 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Stopped
12:42:57.979 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Left
12:42:57.980 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Stopped
12:43:02.050 [] [ForkJoinPool.commonPool-worker-3] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
12:43:02.051 [] [atomix-cluster-0] INFO  io.atomix.cluster.AtomixCluster - Stopped
12:43:02.052 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [12/13]: membership and replication protocol closed in 4089 ms
12:43:02.052 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [13/13]: actor scheduler
12:44:47.993 [] [Time-limited test] ERROR io.zeebe.broker.system - Closing Broker-0 [13/13]: actor scheduler failed to close.
java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~[?:?]
	at io.zeebe.broker.Broker.lambda$actorSchedulerStep$12(Broker.java:194) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.CloseProcess.lambda$closingStepByStep$0(CloseProcess.java:56) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.CloseProcess.closingStepByStep(CloseProcess.java:56) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.CloseProcess.closeReverse(CloseProcess.java:37) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.Broker.lambda$close$24(Broker.java:405) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
	at io.zeebe.broker.Broker.lambda$close$25(Broker.java:403) ~[zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) [zeebe-util-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.Broker.close(Broker.java:398) [zeebe-broker-0.25.0-SNAPSHOT.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.test.EmbeddedBrokerRule.stopBroker(EmbeddedBrokerRule.java:191) [zeebe-broker-0.25.0-SNAPSHOT-tests.jar:0.25.0-SNAPSHOT]
	at io.zeebe.broker.test.EmbeddedBrokerRule.after(EmbeddedBrokerRule.java:140) [zeebe-broker-0.25.0-SNAPSHOT-tests.jar:0.25.0-SNAPSHOT]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282) [junit-4.13.jar:4.13]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
12:44:47.994 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 13 steps in 112226 ms.
12:44:47.994 [] [Time-limited test] INFO  io.zeebe.broker.system - Broker shut down.
12:44:48.056 [] [Time-limited test] INFO  io.zeebe.broker.test - Broker closing time: 112287

Sytem Error:
Jul 19, 2020 12:42:55 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=1, target=localhost:32778} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:517)
	at io.zeebe.client.impl.ZeebeClientImpl.buildChannel(ZeebeClientImpl.java:129)
	at io.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:79)
	at io.zeebe.client.impl.ZeebeClientBuilderImpl.build(ZeebeClientBuilderImpl.java:267)
	at io.zeebe.broker.it.gateway.GatewayLivenessProbeIntegrationTest.createZeebeClient(GatewayLivenessProbeIntegrationTest.java:115)
	at io.zeebe.broker.it.gateway.GatewayLivenessProbeIntegrationTest.shouldReportLivenessUpIfConnectedToBroker(GatewayLivenessProbeIntegrationTest.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

Exception in thread "Broker-0-zb-fs-workers-0" java.lang.AssertionError
	at org.rocksdb.Transaction.rollback(Transaction.java:215)
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.rollbackInternal(ZeebeTransaction.java:122)
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:166)
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:135)
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:173)
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.foreach(ZeebeTransactionDb.java:284)
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.foreach(ZeebeTransactionDb.java:270)
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEach(TransactionalColumnFamily.java:142)
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEach(TransactionalColumnFamily.java:79)
	at io.zeebe.broker.exporter.stream.ExportersState.visitPositions(ExportersState.java:75)
	at io.zeebe.broker.exporter.stream.ExporterDirector.clearExporterState(ExporterDirector.java:292)
	at io.zeebe.broker.exporter.stream.ExporterDirector.onSnapshotRecovered(ExporterDirector.java:228)
	at io.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:140)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204)
</pre>
</details>

### PR DESCRIPTION
**Pull request by korthout**
## Description

HealthMonitoringTest and DeploymentClusteredTest are both flaky. The
test timesout due to the outerrule (timeout) wrapped around the
embeddedbrokerrule.

At least for the health monitoring test it was clear that a lot of time
was spend waiting for the broker to finish, because the raft partition
server was already stopped inside the test and could then later not be
stopped by the after of the embeddedbrokerrule.

This PR allows calling the shutdown method of DefaultRaftServer
multiple times by keeping track of a stopped flag. The server is only
allowed to stop if it is started and not already stopped. If it is
already stopped it can just return.

It also refactors the HealthMonitoringTest a bit to focus on what matters.

It does not fix the flakyness of these tests, but was an attempt for it.

## Related issues

see #5005
and #5013

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by korthout** [comment]
We're not entirely sure this fixes the flakyness, but we're keeping our fingers crossed. Let's see what the ci says.

**Comment by Zelldon** [comment]
Doesnt look better 🤔😕

**Comment by korthout** [comment]
@Zelldon you're right. We only had a hunch since we saw this errored in the log. That error should at least be gone with this change.

File: atomix/cluster/src/main/java/io/atomix/raft/impl/DefaultRaftServer.java [hunk 1]
```diff
@@ -123,22 +124,27 @@ public void removeFailureListener(final Runnable failureListener) {
...
    * @return A completable future to be completed once the server has been shutdown.
    */
+  @Override
   public CompletableFuture<Void> shutdown() {
-    if (!started) {
+    if (!started && !stopped) {
       return Futures.exceptionalFuture(new IllegalStateException("Server not running"));
     }
 
+    if (stopped) {
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/DefaultRaftServer.java:133]: @korthout do you think it makes sense to replace the boolean flags with just having a future for starting and stopping?

If starting future is null, you know it hasn't been started etc. If you call stop twice you just return the stopping future. I think it is not necessary to return an exceptionally future, for me it is not an error to close something what haven't been started. What do you think?

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/health/HealthMonitoringTest.java [hunk 2]
```diff
@@ -56,7 +46,7 @@ public void shouldReportUnhealthyWhenRaftInactive() {
     raftPartition.getServer().stop();
 
     // then
-    waitUntil(() -> !isBrokerHealthy());
+    Awaitility.waitAtMost(Duration.ofMinutes(1)).until(() -> !isBrokerHealthy());
```
Comment (Zelldon) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/health/HealthMonitoringTest.java:49]: Thanks for replacing that :+1:

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @korthout for cleaning this up.

I had just a small question regarding the future.

File: atomix/cluster/src/main/java/io/atomix/raft/impl/DefaultRaftServer.java (hunk 1 above)
Comment (korthout) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/DefaultRaftServer.java:133]: It makes sense but since you can start, stop and leave async this gets very complex. It requires keeping track of a queue of futures (or something similar to ZeebePartitionTransition). It would be easier if we could just remove leaving behaviour, since we don't use this anyways. I'll create an issue for it.

Comment (korthout) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/DefaultRaftServer.java:133]: Created here: https://github.com/zeebe-io/zeebe/issues/5663

**Comment by korthout** [comment]
@Zelldon I've just left it at this right now. I think the restrictions currently make it more clear that the code cannot handle more complex stuff.

**Review by ChrisKujawa — APPROVED** [review]
Thanks @korthout :+1:
