### PR TITLE
test(broker-core): fix flaky test

### LINKED ISSUE #2293: TimerCatchEventTest is flaky
```
13:42:43 [1 - Java Tests] [ERROR] Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.775 s <<< FAILURE! - in io.zeebe.broker.workflow.timer.TimerCatchEventTest
13:42:43 [1 - Java Tests] [ERROR] shouldTriggerMultipleTimers(io.zeebe.broker.workflow.timer.TimerCatchEventTest)  Time elapsed: 1.004 s  <<< FAILURE!
13:42:43 [1 - Java Tests] java.lang.AssertionError: 
13:42:43 [1 - Java Tests] 
13:42:43 [1 - Java Tests] Expecting:
13:42:43 [1 - Java Tests]  <1553863360737L>
13:42:43 [1 - Java Tests] to be less than:
13:42:43 [1 - Java Tests]  <1553863359837L> 
13:42:43 [1 - Java Tests] 	at io.zeebe.broker.workflow.timer.TimerCatchEventTest.shouldTriggerMultipleTimers(TimerCatchEventTest.java:285)
13:42:43 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:42:43 [1 - Java Tests] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:42:43 [1 - Java Tests] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:42:43 [1 - Java Tests] 	at java.lang.reflect.Method.invoke(Method.java:498)
13:42:43 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
13:42:43 [1 - Java Tests] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
13:42:43 [1 - Java Tests] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
13:42:43 [1 - Java Tests] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
13:42:43 [1 - Java Tests] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
13:42:43 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:42:43 [1 - Java Tests] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
13:42:43 [1 - Java Tests] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
13:42:43 [1 - Java Tests] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
13:42:43 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
13:42:43 [1 - Java Tests] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
13:42:43 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:128)
13:42:43 [1 - Java Tests] 	at org.junit.runners.Suite.runChild(Suite.java:27)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
13:42:43 [1 - Java Tests] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
13:42:43 [1 - Java Tests] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

### PR DESCRIPTION
**Pull request by saig0**
closes #2293

### CODE REVIEW

File: broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java [hunk 1]
```diff
@@ -357,45 +358,46 @@ public void shouldCancelTimer() {
...
-    // then
-    assertThat(timerCreatedRecord.getValue().getDueDate()).isEqualTo(nowMs + 1000);
-    assertThat(timerCreatedRecord.getValue().getElementInstanceKey())
-        .isEqualTo(activityRecord.getKey());
-    assertThat(timerCreatedRecord.getValue().getHandlerFlowNodeId()).isEqualTo("timer");
+    Assertions.assertThat(timerRecord.getValue())
+        .hasElementInstanceKey(activityRecord.getKey())
+        .hasHandlerFlowNodeId("timer");
+
+    assertThat(timerRecord.getValue().getDueDate())
```
Comment (Zelldon) [inline broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java]: It could still happen that If we wait on one of the events with the Recording exporter longer than 1 second, our lower bound is not longer correct right?

File: broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java [hunk 2]
```diff
@@ -406,126 +408,145 @@ public void shouldTriggerHandlerNodeWhenAttachedToActivity() {
...
-    brokerRule.getClock().addTime(Duration.ofSeconds(10));
+    final Record<TimerRecordValue> timerCreated =
+        RecordingExporter.timerRecords(TimerIntent.CREATED)
+            .withWorkflowInstanceKey(workflowInstanceKey)
+            .getFirst();
+
+    brokerRule.getClock().addTime(Duration.ofSeconds(1));
 
     // then
+    final Record<TimerRecordValue> timerTriggered =
```
Comment (Zelldon) [inline broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java]: This fails on my machine

File: broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java [hunk 3]
```diff
@@ -218,23 +213,25 @@ public void shouldCompleteTimerEvent() {
...
-    brokerRule.getClock().addTime(Duration.ofSeconds(1));
-
-    // then
     final Record<WorkflowInstanceRecordValue> completedEvent =
         RecordingExporter.workflowInstanceRecords()
             .withWorkflowInstanceKey(workflowInstanceKey)
             .withElementId("timer")
             .withIntent(WorkflowInstanceIntent.ELEMENT_COMPLETED)
-            .limitToWorkflowInstanceCompleted()
             .getFirst();
```
Comment (Zelldon) [inline broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java]: This now fails sometimes

File: broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java [hunk 4]
```diff
@@ -406,126 +408,145 @@ public void shouldTriggerHandlerNodeWhenAttachedToActivity() {
...
-                .limitToWorkflowInstance(workflowInstanceKey)
-                .timerRecords()
+            RecordingExporter.timerRecords(TimerIntent.TRIGGERED)
                 .withWorkflowInstanceKey(workflowInstanceKey)
-                .withHandlerNodeId("timer")
-                .withIntent(TimerIntent.CREATED)
-                .count())
-        .isEqualTo(expectedRepetitions);
+                .limit(expectedRepetitions))
+        .hasSize(expectedRepetitions);
```
Comment (Zelldon) [inline broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java]: Flaky

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Sorry @saig0 still some flaky tests :see_no_evil:

**Review by ChrisKujawa — APPROVED** [review]

**Comment by Zelldon** [comment]
Forget what I wrote it seems I had an old state of the branch somehow, sorry :see_no_evil:
