### PR TITLE
fix: prevent batch operation document overwrite in multi-partition clusters

### LINKED ISSUE #44841: Batch operation can remain stuck in CREATED or ACTIVE state
### Description

A batch operation (e.g., modification or resolve incident) is created on one partition and distributed across partitions. It's lifecycle is that it should progress from CREATED to ACTIVE and then to COMPLETED, PARTIALLY_COMPLETED, or FAILED. I encountered cases where batch operations remain in CREATED or in ACTIVE, affecting process instance modification and incident resolution. The UI continues to show SUSPEND/CANCEL options that fail when clicked.

### Steps to reproduce

So far, I've only encountered these on a SaaS cluster where the main differences that I can imagine is that it runs multiple-partitions. 

1. Start a batch modification on several process instances (occasionally remains in CREATED or in ACTIVE).
2. Select process instances without incidents, click 'Retry' for batch resolve incident (reproducible: operation remains in CREATED or in ACTIVE, no process instances affected).

### Current behavior

On two occasions, batch operations remain stuck in the CREATED state:
1. Batch modification on 16 process instances (not reproducible) remained in CREATED despite success on all affected instances.

Image

2. Batch resolve incident operation (reproducible): selecting process instances without incidents and clicking Retry has no effect and remains in CREATED.

Image

In both cases, the SUSPEND And CANCEL buttons remains visible to the user. When clicking them, an error message is displayed.

### Expected behavior

Batch operations should initialize and process on each partition, progressing through the lifecycle states and ultimately complete (COMPLETED, PARTIALLY_COMPLETED, or FAILED).

### Workaround

Unknown

### Environment

SaaS & SM

### Version

8.8 and 8.9

### Rootcause

Possibly, this is related to a race condition between the exporters writing about the same batch operation on the different partitions to the same secondary storage. Note that the batch operation (identified by key) exists on all partitions, and moves through the lifecycle on all partitions. Each exporter will see these events in order, but there is no ordering between the exporters. However, with eventual consistency, each exporter should eventually see COMPLETED/CANCELED at the end. So, it's not clear to me how this could be full rootcause.

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

No it doesn't affect an automated test suite.

### LINKED ISSUE #46466: Operate incident retry button spinner does not stop after retry
### 

### 

### 

### 

### Description

When retrying an incident in Operate, the retry button's spinner shows unlimited spinning and does not stop.

### Steps to reproduce

1. Go to Operate
2. Navigate to details view of a process with incident
3. Click on retry button
4. Check that the retry spinner is not stopping

### Current behavior

The retry spinner keeps spinning indefinitely, without completing the retry operation or updating in the UI.

https://github.com/user-attachments/assets/bb6b0440-50f7-44cc-9182-70882ea90478

### Expected behavior

The retry spinner should stop after the retry action completes, indicating the incident is resolved or retried successfully.

### Workaround

_No response_

### Environment

SaaS

### Version

9.8 Snapshot

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### LINKED ISSUE #46696: Activate ClusterMultiplePartitionsBatchOperationIT for ES/OS
The `ClusterMultiplePartitionsBatchOperationIT` currently only tests RDBMS, ES/OS is actively excluded.

AC:
- the `ClusterMultiplePartitionsBatchOperationIT` also executes on ES and OS tests successfully

### PR DESCRIPTION
**Pull request by tsedekey**
## Description

This PR fixes the "Operate incident retry button spinner does not stop after retry" bug (https://github.com/camunda/camunda/issues/46466) that occurs in multi-partition SaaS clusters.

### Root Cause

The CREATED event for batch operations is distributed to all partitions in the cluster. Each partition's exporter independently writes to the same batch operation document in the search index. Using ES `INDEX` (full overwrite) operations in `BatchOperationCreatedHandler.flush()` allowed a late write from a slow partition's exporter to overwrite `operationsTotalCount` increments and state transitions already applied by other partitions, causing the batch operation to appear permanently stuck in ACTIVE state with `operationsTotalCount=0`.

This race condition is latent in both 8.9 and 8.10 (the batch operation code is identical), but manifests probabilistically in multi-partition environments. Single-partition self-managed deployments are unaffected because there's only one exporter processing events sequentially.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #46466 
closes #46696
closes #44841

### CODE REVIEW

**Comment by tmetzke** [comment]
Substituting myself for @camunda/data-layer to review this. They are way more knowledgable with those things 🤓

**Comment by tmetzke** [comment]
Can this be an issue in 8.8 as well? If not, why? Those routines exist in 8.8 as well, don't they?

**Comment by tsedekey** [comment]
> Can this be an issue in 8.8 as well? If not, why? Those routines exist in 8.8 as well, don't they?

@tmetzke yes this is also an issue in 8.8 and this fix would need to be backported once merged, thanks for noteing!

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationLifecycleManagementHandler.java [hunk 1]
```diff
@@ -111,16 +111,46 @@ public void updateEntity(
...
+      def terminalStates = ['COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'CANCELED'];
+      def isNewStateTerminal = terminalStates.contains(params.state);
+      def isCurrentStateTerminal = terminalStates.contains(ctx._source.state);
+      def shouldApplyState = isNewStateTerminal || !isCurrentStateTerminal;
+      if (shouldApplyState) {
+          ctx._source.state = params.state;
+          ctx._source.endDate = params.endDate;
+          if (params.containsKey('errors')) {
+              ctx._source.errors = params.errors;
+          }
```
[the remark this answers is not in the document]
Comment (tsedekey) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationLifecycleManagementHandler.java]: @copilot the suggestion adds significant complexity to guard against terminal-to-terminal state regression, but that scenario cannot occur in practice. The suggested fix introduces a Painless precedence map with 4 case branches to prevent something the engine already prevents.

**Comment by houssain-barouni** [comment]
@tsedekey I believe your fix should solve `ClusterMultiplePartitionsBatchOperationIT` for ES/OS, this test is currently disabled for ES/OS as per https://github.com/camunda/camunda/issues/46696 , but I guess with your PR we can enable it
Can you try that out?

**Comment by korthout** [comment]
@tsedekey Do you think this will resolve https://github.com/camunda/camunda/issues/44841 as well? To me it appears that this would do just that, but I haven't gone deep on this so I'd love to hear what you think.

**Comment by mustafadagher** [comment]
> @tsedekey I believe your fix should solve `ClusterMultiplePartitionsBatchOperationIT` for ES/OS, this test is currently disabled for ES/OS as per #46696 , but I guess with your PR we can enable it Can you try that out?

I contributed this in 8253478. 
CC: @tsedekey

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationLifecycleManagementHandler.java [hunk 2]
```diff
@@ -111,22 +111,44 @@ public void updateEntity(
...
+      def isNewStateTerminal = terminalStates.contains(params.state);
+      def isCurrentStateTerminal = terminalStates.contains(ctx._source.state);
+      if (isNewStateTerminal || !isCurrentStateTerminal) {
+          ctx._source.state = params.state;
+      }
+      ctx._source.endDate = params.endDate;
+      if (params.containsKey('errors')) {
+          ctx._source.errors = params.errors;
+      }
+      """;
```
Comment (mustafadagher) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationLifecycleManagementHandler.java]: 👍

**Review by mustafadagher — APPROVED** [review]
Thanks @tsedekey ! I've reviewed this and it LGTM 🚀 

I'd still wait for a review from @houssain-barouni or someone from DL team.

I also agree with @korthout that it might be also resolving https://github.com/camunda/camunda/issues/44841

**Comment by korthout** [comment]
>that it might be also resolving https://github.com/camunda/camunda/issues/44841

Would be good to verify this with QA 🙇

**Comment by korthout** [comment]
@tsedekey Please make sure to backport this to 8.9 and 8.8

**Comment by tsedekey** [comment]
@mustafadagher — Thanks for the review, approval, and the test enablement commit!

@houssain-barouni — Thanks for the suggestion. I see the CI has passed, confirming the fix resolves the test that was disabled per #46696. Are you happy to approve this PR?

@korthout — Yes, I believe this PR also resolves #44841. The root cause described there (batch operations stuck in CREATED or ACTIVE on multi-partition clusters) is the same cross-partition exporter race condition fixed here. This aligns with your solution idea [3](https://github.com/camunda/camunda/issues/44841#issuecomment-3824554379) in #44841: "Only progress forward in the lifecycle... use an update-if construct.". I agree it would good to get QA verification after merging this, I will backport to 8.9 and 8.8 after merge.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationLifecycleManagementHandler.java
Comment (mustafadagher) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationLifecycleManagementHandler.java:113]: @houssain-barouni / @camunda/data-layer 
My comment is unrelated to this PR.
But with 8.10 onwards, we should expect no legacy `operate` batch operations, right?
❓ Does it make sense to get rid of all the occurrences setting `end-date` to `null` and get rid of the `BatchOperationUpdateTask` ?
❓ Do we have an issue open for that?

💭 if this is feasible, it can be also considered a performance improvements. it reduces the background tasks load, queries and writes, when batch operations are executed

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationCreatedHandler.java [hunk 3]
```diff
@@ -92,7 +95,28 @@ public void updateEntity(
...
+
+    final var actorType = entity.getActorType();
+    if (actorType != null) {
+      updateFields.put(BatchOperationTemplate.ACTOR_TYPE, actorType);
+    }
+
+    final var actorId = entity.getActorId();
+    if (actorId != null) {
+      updateFields.put(BatchOperationTemplate.ACTOR_ID, actorId);
+    }
```
Comment (houssain-barouni) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationCreatedHandler.java]: ❓ would any of these fields change, in case of concurrent insertion of the same batch operation entity?  I believe these are idempotent (same value from any partition), so no need to update them in case the document exist

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationLifecycleManagementHandler.java
Comment (houssain-barouni) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationLifecycleManagementHandler.java:113]: I don't think we are owner of this. If this needs to be removed in 8.10, core-features teams have to handle that.

**Review by houssain-barouni — COMMENTED** [review]
LGTM! I just had one minor remark
❓ should we consider updating the RDBMS implementation as well? I Previously made a fix https://github.com/camunda/camunda/pull/46691 because of a flaky test, but it seems that we need to do more than that

**Comment by tsedekey** [comment]
> LGTM! I just had one minor remark ❓ should we consider updating the RDBMS implementation as well? I Previously made a fix #46691 because of a flaky test, but it seems that we need to do more than that

I looked into the RDBMS implementation and it looks already safe to me, because `BatchOperationWriter.createIfNotAlreadyExists()` does a read-before-insert and skips if the row exists (no overwrite). The chunk handling uses atomic SQL increments `(SET col = col + N)`, and the INITIALIZED -> ACTIVE state regression was already guarded by your fix in #46691. So I don't think changes are needed on the RDBMS side.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationCreatedHandler.java (hunk 3 above)
Comment (tsedekey) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationCreatedHandler.java]: Good call, you're right these fields are idempotent, so I've removed the need to update them which simplifies the logic.

**Comment by houssain-barouni** [comment]
> > LGTM! I just had one minor remark ❓ should we consider updating the RDBMS implementation as well? I Previously made a fix #46691 because of a flaky test, but it seems that we need to do more than that
> 
> I looked into the RDBMS implementation and it looks already safe to me, because `BatchOperationWriter.createIfNotAlreadyExists()` does a read-before-insert and skips if the row exists (no overwrite). The chunk handling uses atomic SQL increments `(SET col = col + N)`, and the INITIALIZED -> ACTIVE state regression was already guarded by your fix in #46691. So I don't think changes are needed on the RDBMS side.

In #46691, I added an extra condition in the query to activate a batch operation, checking if it is already `COMPLETED`, but it seems there are more "terminal" states that should be handled, isn't?

**Review by houssain-barouni — APPROVED** [review]

**Comment by tsedekey** [comment]
> > > LGTM! I just had one minor remark ❓ should we consider updating the RDBMS implementation as well? I Previously made a fix #46691 because of a flaky test, but it seems that we need to do more than that
> > 
> > 
> > I looked into the RDBMS implementation and it looks already safe to me, because `BatchOperationWriter.createIfNotAlreadyExists()` does a read-before-insert and skips if the row exists (no overwrite). The chunk handling uses atomic SQL increments `(SET col = col + N)`, and the INITIALIZED -> ACTIVE state regression was already guarded by your fix in #46691. So I don't think changes are needed on the RDBMS side.
> 
> In #46691, I added an extra condition in the query to activate a batch operation, checking if it is already `COMPLETED`, but it seems there are more "terminal" states that should be handled, isn't?

I see what you mean, yes there are more terminal states to guard against. Beyond COMPLETED, the full set of terminal states is PARTIALLY_COMPLETED, FAILED, and CANCELED.  Since this PR is focused on the ES/OS exporter side, I think it would be best to address the RDBMS state guards in a follow-up. Would you be open to creating a follow-up issue from #46691 for it?

**Comment by houssain-barouni** [comment]
> > > > LGTM! I just had one minor remark ❓ should we consider updating the RDBMS implementation as well? I Previously made a fix #46691 because of a flaky test, but it seems that we need to do more than that
> > > 
> > > 
> > > I looked into the RDBMS implementation and it looks already safe to me, because `BatchOperationWriter.createIfNotAlreadyExists()` does a read-before-insert and skips if the row exists (no overwrite). The chunk handling uses atomic SQL increments `(SET col = col + N)`, and the INITIALIZED -> ACTIVE state regression was already guarded by your fix in #46691. So I don't think changes are needed on the RDBMS side.
> > 
> > 
> > In #46691, I added an extra condition in the query to activate a batch operation, checking if it is already `COMPLETED`, but it seems there are more "terminal" states that should be handled, isn't?
> 
> I see what you mean, yes there are more terminal states to guard against. Beyond COMPLETED, the full set of terminal states is PARTIALLY_COMPLETED, FAILED, and CANCELED. Since this PR is focused on the ES/OS exporter side, I think it would be best to address the RDBMS state guards in a follow-up. Would you be open to creating a follow-up issue from #46691 for it?

I prefer someone from core features doing that. We don't have the knowledge about how batch operations should work

**Comment by tsedekey** [comment]
@houssain-barouni I've created a [follow-up](https://github.com/camunda/camunda/issues/48488) to address the RDBMS side.
