### PR TITLE
Ensure retries are not interleaved even on multiple sequential calls

### LINKED ISSUE #10240: IllegalStateException in StreamProcessor : Cannot complete future, the future is already completed
**Describe the bug**

```
java.lang.IllegalStateException: Cannot complete future, the future is already completed exceptionally with 'Expected to claim segment of size 20033584, but can't claim more than 4194304 bytes.' 
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:186) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:193) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:50) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: Expected to claim segment of size 20033584, but can't claim more than 4194304 bytes.
	at io.camunda.zeebe.dispatcher.Dispatcher.offer(Dispatcher.java:207) ~[zeebe-dispatcher-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.dispatcher.Dispatcher.claimFragmentBatch(Dispatcher.java:164) ~[zeebe-dispatcher-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.claimBatchForEvents(LogStreamBatchWriterImpl.java:235) ~[zeebe-logstreams-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.tryWrite(LogStreamBatchWriterImpl.java:212) ~[zeebe-logstreams-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$4(ProcessingScheduleServiceImpl.java:127) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:45) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	... 6 more
```

StreamProcessor actor failed and the partition is unhealthy.

**To Reproduce**

Observed this when running an e2e test with a new process added in [this PR](https://github.com/zeebe-io/zeebe-e2e-test/pull/137) 

**Expected behavior**

StreamProcessor should not fail.

**Log/Stacktrace**

[Logs](https://drive.google.com/drive/folders/1598z2E7JteJhKEAbHr5M91Yn7bz-Yj0c)

[Log explorer](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-08-31T14:31:48.722741133Z;pinnedLogId=2022-08-31T14:31:48.722741133Z%2Frhi4ghqrjodsyl5z;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22c2bc90c4-b12c-46c8-b2bc-00a9b9457be1-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%0A-resource.labels.container_name%3D%22zeebe-analytics%22%0A-jsonPayload.context.loggerName%3D%22io.camunda.zeebe.broker.exporter%22%0AjsonPayload.context.partitionId%3D%223%22%0Atimestamp%3D%222022-08-31T14:31:48.722741133Z%22%0AinsertId%3D%22rhi4ghqrjodsyl5z%22;summaryFields=jsonPayload%252Fcontext%252FpartitionId:false:32:beginning;timeRange=2022-08-31T13:31:48.723Z%2F2022-08-31T15:31:48.723Z?project=camunda-cloud-240911)

<details><summary>Logs before this error that might be relevant</summary>
 <p>

```
2022-08-31 16:28:33.521 CEST
Expected to find job with key 6755399441066071, but no job found
2022-08-31 16:28:33.521 CEST
Expected to find job with key 6755399441066104, but no job found
2022-08-31 16:28:33.521 CEST
Expected to find job with key 6755399441067170, but no job found
2022-08-31 16:28:33.521 CEST
Expected to find job with key 6755399441067940, but no job found
2022-08-31 16:31:10.218 CEST
Failed to write command MESSAGE_SUBSCRIPTION CREATE from 0 to logstream
2022-08-31 16:31:10.218 CEST
Failed to write command MESSAGE_SUBSCRIPTION CREATE from 0 to logstream
2022-08-31 16:31:10.219 CEST
Failed to write command MESSAGE_SUBSCRIPTION CREATE from 0 to logstream
2022-08-31 16:31:10.219 CEST
.....
Failed to write command MESSAGE_SUBSCRIPTION CREATE from 0 to logstream
2022-08-31 16:31:40.226 CEST
Failed to write command MESSAGE_SUBSCRIPTION CREATE from 0 to logstream
2022-08-31 16:31:40.226 CEST
Failed to write command MESSAGE_SUBSCRIPTION CREATE from 0 to logstream
2022-08-31 16:31:48.722 CEST
Actor Broker-2-StreamProcessor-3 failed in phase STARTED.
2022-08-31 16:31:48.728 CEST
Discard job io.camunda.zeebe.scheduler.retry.AbortableRetryStrategy$$Lambda$2505/0x00000008016d7530 QUEUED from fastLane of Actor Broker-2-StreamProcessor-3.
2022-08-31 16:31:48.728 CEST
Discard job io.camunda.zeebe.streamprocessor.StreamProcessor$$Lambda$2317/0x0000000801677500 QUEUED from fastLane of Actor Broker-2-StreamProcessor-3.

```

</p>
</details>

**Environment:**
- OS: camunda cloud
- Zeebe Version: 8.1.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

By using `ActorControl#submit` in some of the retry strategies, we can create race conditions if the retry strategy is reused. Since the initial call uses run to prepend a retry attempt, and further retries use submit, it's possible for one run to retry (thus submitting the retry job to the end of the queue) and the next call to `runWithRetry` cause its state to be overwritten, causing issues when it comes to completing the future (as well as potential shared state by the operations).

Additionally, this PR fixes an issue where on retry, we were not resetting the writer, causing the same command to be written multiple times.

There is a regression test added which isn't perfect, and I'd like some suggestions on how to improve it. The integration test added to the `ProcessingScheduleServiceTest` is not amazing and likely to flaky, as it's hard to write controlled tests with our timers. Suggestions are welcomed :+1: 

## Related issues

closes #10240 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
One additional thing, we could potentially refactor the retry mechanism such that each retry operation is self contained and isolated from others, but I wasn't sure what that would mean in terms of semantic. To some extent, our retry operations should be sequenced between themselves, right? Perhaps we do need `runUntilDone` after all, or rather, the functionality:

- You can submit a task, and not allow any future tasks to be executed until it and any tasks it enqueues are completed
- Thread should be yielded in between executions

Right now, the fix relies on the fact that when we're executing a task, calling `run` will prepend the next task at the top of the queue, and while we're still executing the original task, _nothing can prepend tasks to the queue, ensuring that whatever we prepend is executed first immediately after on that actor_. That's easy to break in general, and makes reasoning about scheduling much harder.

I'm wondering if, in general, instead of using the retry strategies, we might not simply build retrying into the state machines that need them. Would that make things easier to understand? :thinking:

File: engine/src/test/java/io/camunda/zeebe/streamprocessor/ProcessingScheduleServiceImplTest.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+  @AfterEach
+  void afterEach() {
+    schedulerRule.get().stop();
+  }
+
+  @Test
+  void shouldCompleteFutureTwice() {
+    // given
+    final var actor = new TestActor();
+    final var service = new ProcessingScheduleServiceImpl(new StreamProcessorContext());
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply engine/src/test/java/io/camunda/zeebe/streamprocessor/ProcessingScheduleServiceImplTest.java:34]: Oops, this wasn't meant to be there, sorry

File: scheduler/src/test/java/io/camunda/zeebe/scheduler/retry/RetryStrategyTest.java [hunk 2]
```diff
@@ -116,6 +118,25 @@ public void shouldAbortOnOtherException() {
     assertThat(resultFuture.getException()).isExactlyInstanceOf(RuntimeException.class);
   }
 
+  @Test
+  public void shouldNotInterleaveRetry() {
+    // given
+    final AtomicReference<ActorFuture<Boolean>> firstFuture = new AtomicReference<>();
```
Comment (npepinpe) [inline scheduler/src/test/java/io/camunda/zeebe/scheduler/retry/RetryStrategyTest.java:124]: If you revert the fix and use `submit` again, you will see this test fails (the first future is incomplete), and you will get the logs that the second future was completed twice.

File: scheduler/src/test/java/io/camunda/zeebe/scheduler/retry/RetryStrategyTest.java [hunk 3]
```diff
@@ -116,6 +118,25 @@ public void shouldAbortOnOtherException() {
     assertThat(resultFuture.getException()).isExactlyInstanceOf(RuntimeException.class);
   }
 
+  @Test
+  public void shouldNotInterleaveRetry() {
```
Comment (deepthidevaki) [inline scheduler/src/test/java/io/camunda/zeebe/scheduler/retry/RetryStrategyTest.java:122]: :wrench:  Do we want to prevent interleaving the retries, and ensure that the ordering is preserved? Or just that two concurrently submitted tasks can be completed successfully even if they have to be retried? The test verifies the second behavior, which is acceptable. But just rename the method to reflect this.

**Review by deepthidevaki — APPROVED** [review]
Thanks @npepinpe :tada: 

The test looks good to me. It can reproduce the root cause of the bug. 

:wrench: As an integration test, may be you can also add a similar test in `ProcessSchedulingServiceTest`

**Comment by npepinpe** [comment]
I cannot find a file called `ProcessSchedulingServiceTest` :thinking:

**Comment by npepinpe** [comment]
I'm sort of struggling with the integration tests, because our timers are non-deterministic. If I submit two timers one after the other, I'm not guaranteed that they will be executed in the order in which I submitted them, unless there is enough time in between them. I also cannot use a latch to coordinate both timer tasks, since with the fix, the second task shouldn't run anyway before the first one does...

I thought about scheduling the second task only once the first one runs (but before it writes), which works anyway with the fix. Without the fix, I cannot guarantee that it fails, because I would have to guarantee that the first task at least starts retrying before the second task is scheduled...A latch there would help (but I can't use it with the fix, as explained above).

**Comment by npepinpe** [comment]
I also hit a weird bug (seldom), where one of the scheduled tasks just isn't called. Fun times.

**Comment by npepinpe** [comment]
I'm omitting anything about the issue with the timer tasks, I will open another issue for this.

**Comment by deepthidevaki** [comment]
> OK, I wrote an integration test, and good thing! I found a second bug: we don't reset the batch writer in the retry, meaning on each retry we re-append the record :x

This might explain why, in the exception reported in the issue, it was trying to claim 20MB.

**Comment by deepthidevaki** [comment]
> Ah, and regarding your comment about reusing the actor retry mechanism on the issue - I wasn't sure if this would have adverse effect. We can isolate the retry attempts by making sure they contain all their state, but then they might still be interleaved, and I'm not sure this is expected by users of this interface. So I went with the safe option right now. We could of course still isolate them AND also using `run` to make sure they aren't interleaved.

If the jobs have to be ordered, then there is not much value in isolating the retry attempts. So I'm ok to leave it as it is.

**Comment by npepinpe** [comment]
The test fail due to the timer not triggering :smile: I'm reluctant to merge it as it'll be flaky, but I'm now wondering if it's related to the other flaky test with timers :thinking:

**Comment by npepinpe** [comment]
I'll omit the flaky test so we can merge, and I'll add it to the follow up issue https://github.com/camunda/zeebe/issues/10306 as an action item so it can be added back (and used for reproduction) when that's root caused.

**Comment by npepinpe** [comment]
bors merge
