### PR TITLE
fix: Speed Up History Cleanup ITs

### LINKED ISSUE #39870: CI: opensearch-integration-tests > HistoryCleanupIT#shouldDeleteProcessesWhichAreMarkedForCleanup takes 4 minutes
Investigate to speed up, parallelize or move to dedicated job.

### PR DESCRIPTION
**Pull request by yohanfernando**
## Description

At the moment, the ILM/ISM policies can take any time up to 5-10 minutes to apply deletion to an index. This is for cleanup tests, and we set a very low poll interval so that they run often, as a result, speeding up the tests. 

## Related issues

closes #39870

### CODE REVIEW

File: qa/util/src/main/java/io/camunda/qa/util/multidb/AWSOpenSearchSetupHelper.java [hunk 1]
```diff
@@ -97,6 +112,9 @@ public boolean validateSchemaCreation(final String testPrefix) {
 
   @Override
   public void cleanup(final String prefix) {
+    // reset cluster settings if changed
+    resetIndicesLifecyclePollInterval();
```
Comment (houssain-barouni) [inline qa/util/src/main/java/io/camunda/qa/util/multidb/AWSOpenSearchSetupHelper.java]: in the CI, tests that are run in parallel against the same cluster, it means that they may be influenced by the change of cluster settings
I am not sure though how much ES performance could be impacted by the reduction of job polling interval

File: qa/util/src/main/java/io/camunda/qa/util/multidb/ElasticOpenSearchSetupHelper.java [hunk 2]
```diff
@@ -173,10 +151,51 @@ public void cleanup(final String prefix) {
...
+          }
+        },
+        5,
+        LOGGER);
+  }
+
+  private Map<String, Object> getSettingsWithLifecyclePollInterval(final Duration pollInterval) {
+    return Map.of(
+        "persistent",
+        Map.of("indices.lifecycle.poll_interval", String.format("%ds", pollInterval.toSeconds())));
```
Comment (houssain-barouni) [inline qa/util/src/main/java/io/camunda/qa/util/multidb/ElasticOpenSearchSetupHelper.java]: since this is an Elasticsearch setting, can we make `ElasticOpenSearchSetupHelper` abstract and create an implementation for Elasticsearch (as you did for Opensearch), where we put the Elasticsearch only settings?

**Review by houssain-barouni — COMMENTED** [review]
Great finding and good idea to reduce the test execution time! 🚀 
I am wondering though if we should run such tests that require changing cluster settings, separately in an another module or in another CI 🤔 ?

File: qa/util/src/main/java/io/camunda/qa/util/multidb/AWSOpenSearchSetupHelper.java (hunk 1 above)
Comment (yohanfernando) [reply qa/util/src/main/java/io/camunda/qa/util/multidb/AWSOpenSearchSetupHelper.java]: It _definitely should_ increase the workload, but not in a meaningful way for ITs. We are not testing the limits of the system or performance in ITs, only the app functionality. 

Given this is lower only during the lifetime of a test annotated with `@HistoryMultiDbTest`, I think that should be okay..

File: qa/util/src/main/java/io/camunda/qa/util/multidb/ElasticOpenSearchSetupHelper.java (hunk 2 above)
Comment (yohanfernando) [reply qa/util/src/main/java/io/camunda/qa/util/multidb/ElasticOpenSearchSetupHelper.java]: Good shout, let me refactor 👍

**Review by houssain-barouni — APPROVED** [review]
LGTM! 🚀 
I ran the AWS CI on your branch and it is passing https://github.com/camunda/camunda/actions/runs/19422657003
