### PR TITLE
fix(broker-core): correlate a message only once per wf instance

### LINKED ISSUE #1017: A message is correlated only once per workflow instance
AT:
* a message can be correlated only once per workflow instance

Context:
* a workflow instance may open multiple subscriptions with the same name and correlation-key (e.g. an intermediate message catch event in a loop)
* to avoid loops and make the behavior more clear, a message is correlated only once

### PR DESCRIPTION
**Pull request by saig0**
* store the correlated messages in state
* check if a message is already correlated to a wf instance before
correlating
* check if a subscription is already correlated before correlating
* update message correlation docs

closes #1017

### CODE REVIEW

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/OpenMessageSubscriptionProcessor.java [hunk 1]
```diff
@@ -73,33 +76,46 @@ public void processRecord(
...
+
+    streamWriter.writeFollowUpEvent(
+        record.getKey(), MessageSubscriptionIntent.OPENED, subscriptionRecord);
+  }
+
+  private boolean correlateMessage(Message message) {
+    // correlate the first message which matches
+    // - ignore messages which are correlated to the workflow instance before
+
+    final boolean isCorrelatedBefore =
```
Comment (Zelldon) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/OpenMessageSubscriptionProcessor.java]: To recap: this means you check if the message was correlated before to this wf instance, since each message has an unique key. This also means that a message with the same correlation key and name can be correlated again against this wf instance. Is this what you expect/want?

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/OpenMessageSubscriptionProcessor.java [hunk 2]
```diff
@@ -73,33 +76,46 @@ public void processRecord(
...
 
-    if (message != null) {
+    messageStateController.put(subscription);
+
+    streamWriter.writeFollowUpEvent(
+        record.getKey(), MessageSubscriptionIntent.OPENED, subscriptionRecord);
+  }
+
+  private boolean correlateMessage(Message message) {
+    // correlate the first message which matches
```
Comment (Zelldon) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/OpenMessageSubscriptionProcessor.java]: which are not correlated and matches the prefix

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java [hunk 3]
```diff
@@ -74,35 +75,59 @@ public void processRecord(
...
-      }
+    final TypedBatchWriter batchWriter = streamWriter.newBatch();
+    final long key = batchWriter.addNewEvent(MessageIntent.PUBLISHED, command.getValue());
+    responseWriter.writeEventOnCommand(key, MessageIntent.PUBLISHED, command.getValue(), command);
+
+    // correlate the message only once per workflow instance
+    // - will be improved by #1421
+    matchingSubscriptions =
+        messageStateController
+            .findSubscriptions(messageRecord.getName(), messageRecord.getCorrelationKey())
```
Comment (Zelldon) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java]: stream api really?

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java [hunk 4]
```diff
@@ -74,35 +75,59 @@ public void processRecord(
...
-                messageRecord.getCorrelationKey(),
-                messageRecord.getPayload(),
-                messageRecord.getMessageId(),
-                messageRecord.getTimeToLive());
-        messageStateController.put(message);
-
-      } else {
-        // don't add the message to the store to avoid that it can be correlated afterwards
-        batchWriter.addFollowUpEvent(key, MessageIntent.DELETED, messageRecord);
+      messageStateController.updateCommandSentTime(sub);
```
Comment (Zelldon) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java]: but the sending is not guaranteed at this point?

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java [hunk 5]
```diff
@@ -185,7 +195,37 @@ private int writeMessageIdKey(
...
+        0,
+        EXISTENCE.length);
+  }
+
+  public boolean existMessageCorrelation(long messageKey, long workflowInstanceKey) {
+    final int length = writeCorrelatedMessageKey(keyBuffer, messageKey, workflowInstanceKey);
+    return db.exists(correlatedMessageColumnFamily, keyBuffer.byteArray(), 0, length);
+  }
+
+  public void findMessage(
```
Comment (Zelldon) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java]: I think the naming is not clear to what the method really does

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java [hunk 6]
```diff
@@ -294,7 +340,13 @@ public void updateCommandSentTime(final MessageSubscription subscription) {
 
   public List<MessageSubscription> findSubscriptions(
       final DirectBuffer messageName, final DirectBuffer correlationKey) {
-    return subscriptionState.findSubscriptions(messageName, correlationKey);
+    // ignore subscriptions for which a correlate command is already send for (i.e. pending
```
Comment (Zelldon) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java]: Since you update the send time already before sending it will also not be found here right?

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java [hunk 7]
```diff
@@ -294,7 +340,13 @@ public void updateCommandSentTime(final MessageSubscription subscription) {
...
+    // subscription) - will be improved by #1421
+    return subscriptionState
+        .findSubscriptions(messageName, correlationKey)
+        .stream()
```
Comment (Zelldon) [inline broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java]: Can we avoid to create garbage?

File: broker-core/src/test/java/io/zeebe/broker/subscription/message/state/MessageStateControllerTest.java [hunk 8]
```diff
@@ -111,7 +111,7 @@ public void shouldExist() {
   public void shouldNotExistIfSubscriptionNotStored() {
     // given
     final MessageSubscription subscription =
-        new MessageSubscription("messageName", "correlationKey", "{\"foo\":\"bar\"}", 1, 2, 1234);
+        new MessageSubscription("messageName", "correlationKey", "{\"foo\":\"bar\"}", 1, 2, 0);
```
Comment (Zelldon) [inline broker-core/src/test/java/io/zeebe/broker/subscription/message/state/MessageStateControllerTest.java]: why zero?

File: broker-core/src/test/java/io/zeebe/broker/subscription/message/state/MessageStateControllerTest.java [hunk 9]
```diff
@@ -135,7 +135,42 @@ public void shouldExistSubscription() {
...
+    // given
+    final Message message = createMessage(1L, "name", "correlationKey");
+    stateController.put(message);
+
+    final Message message2 = createMessage(2L, "name", "correlationKey");
+    stateController.put(message2);
+
+    // when
+    final List<Long> keys = new ArrayList<>();
+    stateController.findMessage(
```
Comment (Zelldon) [inline broker-core/src/test/java/io/zeebe/broker/subscription/message/state/MessageStateControllerTest.java]: findMessagesInOrder maybe the new name ? :sweat_smile:

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/OpenMessageSubscriptionProcessor.java (hunk 1 above)
Comment (saig0) [reply broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/OpenMessageSubscriptionProcessor.java]: Correct.

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java (hunk 3 above)
Comment (saig0) [reply broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java]: Yes, for now. But I promise that I will remove it soon ;)

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java (hunk 4 above)
Comment (saig0) [reply broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java]: Correct. It could be that the command is sent later. However, I need to remember that I need to send the command.  I want to introduce a subscription life cycle with #1421. `OPENED -> [ CORRELATING (PENDING) -> CORRELATED ] | -> CLOSED`

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java (hunk 5 above)
Comment (saig0) [reply broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java]: What about `visitMessages(...)`?

File: broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java (hunk 7 above)
Comment (saig0) [reply broker-core/src/main/java/io/zeebe/broker/subscription/message/state/MessageStateController.java]: Agree. I'll clean it up with #1421. Promise!

**Comment by saig0** [comment]
@Zelldon , please have a look at the changes :)

**Review by ChrisKujawa — APPROVED** [review]
