### PR TITLE
fix: Process coverage report doesn't show completed ad-hoc sub-process elements

### LINKED ISSUE #47653: [CPT] Process coverage report doesn't show completed ad-hoc sub-process elements
### 

### 

, 

### 

### 

### Description

I have a process with an ad-hoc sub-process. I ran my CPT process test and checked the process coverage report. The report shows the completed elements, except for the elements inside the ad-hoc sub-process. 

Image

### Steps to reproduce

1. Run a process test with an ad-hoc sub-process
2. Check the process coverage report
3. Verify that the elements inside the ad-hoc sub-process are not highlighted 

### Current behavior

All completed elements are highlighted, except those within the ad-hoc sub-process.

The coverage rate is not correct. It shows 100% even if not all elements in the ad-hoc sub-process were activated or completed.

### Expected behavior

All completed elements, outside and inside the ad-hoc sub-process, are highlighted.

The coverage rate is correct, also for the elements inside the ad-hoc sub-process.

### Workaround

No workaround. The coverage report doesn't show the correct coverage of the ad-hoc sub-process.

### Environment

SM

### Version

- Component Version: `camunda-process-test-spring:8.8.11`

### Rootcause

I see the following error in the web browser's console: 

```
styles/index.css:1  Failed to load resource: net::ERR_FILE_NOT_FOUND
ProcessView.js:51 Could not import BPMN diagram TypeError: Cannot read properties of undefined (reading 'id')
    at un._updateMarker (Canvas.js:485:55)
    at un.addMarker (Canvas.js:534:8)
    at ProcessView.js:31:32
    at Array.forEach (<anonymous>)
    at ProcessView.js:30:44
(anonymous) @ ProcessView.js:51
```

I assume that the rendering fails because the completed elements contain the ad-hoc sub-process inner instance (`Activity_1piozem#innerInstance`). The inner instance doesn't exist in the BPMN. 

The inner instance also causes the issue in the coverage rate for the same reason. 

### Solution ideas

Exclude the ad-hoc sub-process inner instance in the completed element list.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by saig0**
## Description

This PR fixes an issue with ad-hoc sub-processes in the CPT coverage report by excluding the inner instances. These inner instances cause issues in the diagram rendering and the coverage calculation, because they are not part of the BPMN, but are added by the runtime.

I confirmed the fix in a manual test:

image

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #47653

### CODE REVIEW

File: testing/camunda-process-test-java/src/test/java/io/camunda/process/test/impl/coverage/report/CoverageReportUtilTest.java [hunk 1]
```diff
@@ -86,6 +87,8 @@ public String getSelf() {
     assertThat(CoverageReportUtil.toJson(nonSerializableObject)).isNotNull();
   }
 
+  @Disabled(
+      "The frontend resources are not generate in the CI build. Should be fixed by https://github.com/camunda/camunda/issues/48222.")
```
Comment (megglos) [inline testing/camunda-process-test-java/src/test/java/io/camunda/process/test/impl/coverage/report/CoverageReportUtilTest.java:91]: will we backport the changes done for there also to 8.8?

File: testing/camunda-process-test-java/src/test/java/io/camunda/process/test/api/DeploymentAnnotationIT.java [hunk 2]
```diff
@@ -24,7 +24,7 @@
 import org.junit.jupiter.api.Test;
 
 @CamundaProcessTest
-public class TestDeploymentIT {
+public class DeploymentAnnotationIT {
```
Comment (megglos) [inline testing/camunda-process-test-java/src/test/java/io/camunda/process/test/api/DeploymentAnnotationIT.java:27]: thanks for cleaning that up, I still have to finish the work started here https://github.com/camunda/camunda/pull/46415

**Review by megglos — APPROVED** [review]
LGTM! Just one question on the future of disabled tests.

File: testing/camunda-process-test-java/src/test/java/io/camunda/process/test/impl/coverage/report/CoverageReportUtilTest.java (hunk 1 above)
Comment (saig0) [reply testing/camunda-process-test-java/src/test/java/io/camunda/process/test/impl/coverage/report/CoverageReportUtilTest.java:91]: Yes, we will disable these tests also in 8.8 because they don't work in CI. Currently, the tests use a fake `index.html` file, but this file breaks the local process coverage report. 

We should enable/rewrite these tests in the follow-up issue: https://github.com/camunda/camunda/issues/48222.
