### PR TITLE
Fix resource managment in ZeebePartition

### LINKED ISSUE #4686: Failed to delete pending snapshot
**Description**

After merging #4641 I started some benchmarks and found the following Log message:

```
W 2020-06-09T01:54:43.978Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/36323999-4-1591667681170-104, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=36323999, term=4, timestamp=2020-06-09 01:54:41,170}} 
```

It seems that this happens quite often:

```
W 2020-06-09T00:09:43.074Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/29605799-4-1591661380246-85, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=29605799, term=4, timestamp=2020-06-09 12:09:40,246}} 
W 2020-06-09T00:39:41.805Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/31677899-4-1591663179391-90, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=31677899, term=4, timestamp=2020-06-09 12:39:39,391}} 
W 2020-06-09T00:54:44.717Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/32583699-4-1591664082173-93, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=32583699, term=4, timestamp=2020-06-09 12:54:42,173}} 
W 2020-06-09T01:24:41.562Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/34486399-4-1591665878842-98, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=34486399, term=4, timestamp=2020-06-09 01:24:38,842}} 
W 2020-06-09T01:39:42.245Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/35443999-4-1591666779323-101, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=35443999, term=4, timestamp=2020-06-09 01:39:39,323}} 
W 2020-06-09T01:54:43.978Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/36323999-4-1591667681170-104, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=36323999, term=4, timestamp=2020-06-09 01:54:41,170}} 
W 2020-06-09T02:24:44.600Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/38250399-4-1591669482753-109, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=38250399, term=4, timestamp=2020-06-09 02:24:42,753}} 
W 2020-06-09T02:39:42.181Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/39213999-4-1591670379424-112, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=39213999, term=4, timestamp=2020-06-09 02:39:39,424}} 
W 2020-06-09T02:54:42.768Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/40068299-4-1591671280244-115, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=40068299, term=4, timestamp=2020-06-09 02:54:40,244}} 
W 2020-06-09T03:09:42.994Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/40884999-4-1591672180654-118, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=40884999, term=4, timestamp=2020-06-09 03:09:40,654}} 
W 2020-06-09T03:54:44.588Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/43738099-4-1591674881738-125, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=43738099, term=4, timestamp=2020-06-09 03:54:41,738}} 
W 2020-06-09T04:09:44.378Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/44544799-4-1591675781438-128, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=44544799, term=4, timestamp=2020-06-09 04:09:41,438}} 
W 2020-06-09T04:24:41.976Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/45558399-4-1591676680062-131, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=45558399, term=4, timestamp=2020-06-09 04:24:40,062}} 
W 2020-06-09T04:39:42.472Z Failed to delete pending snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/46491899-4-1591677579465-134, snapshotStore=io.atomix.raft.snapshot.impl.FileBasedSnapshotStore@45b7de80, expectedId=null, metadata=DbSnapshotMetadata{index=46491899, term=4, timestamp=2020-06-09 04:39:39,465}} 
```

We should check that.

### LINKED ISSUE #4810: No new Leader is assigned after Leader dies
**Describe the bug**
On the long running cluster (stable nodes) we have a benchmark running with the following settings:

 * 3 partition
 * 3 nodes
 * 3 repl. factor
 * 1 starter - starts 100 workflow instances per seconds
 * 6 workers - activate 120 workers max

We can see in the metrics that the node 2 died on 2020-06-20 10:00 and came ready again at 2020-06-22 09:30.
We can also verify this in the [logs](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-06-20T08:00:00.000000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-long-running%22%0Aresource.labels.namespace_name%3D%22long-running%22%0Alabels.k8s-pod%2Fapp%3D%22long-running-zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22long-running%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0AjsonPayload.logger!%3D%22io.zeebe.broker.exporter.elasticsearch%22%0Alabels.%22k8s-pod%2Fstatefulset_kubernetes_io%2Fpod-name%22%3D%22long-running-zeebe-2%22&scrollTimestamp=2020-06-22T08:21:19.824334000Z&dateRangeUnbound=forwardInTime)

```
I 2020-06-20T07:21:56.659539Z Bootstrap Broker-2 [6/10]: cluster services 
I 2020-06-20T07:21:57.082580Z Initializing Spring DispatcherServlet 'dispatcherServlet' 
I 2020-06-20T07:21:57.083878Z Initializing Servlet 'dispatcherServlet' 
I 2020-06-20T07:21:57.093290Z Completed initialization in 9 ms 
D 2020-06-22T08:21:19.804473Z Bootstrap Broker-2 [6/10]: cluster services started in 176363144 ms
```
It take for the node two, two complete days to come back! It might due to #4664 or something which is related to #4158 
During this time the processing stops completely! It sounds like a bug we have fixed before https://github.com/zeebe-io/zeebe/pull/4451

noprogress

We can see int the metrics that there is no leader choosen during this time!
leaders

Since we have so high atomix log level it seems there is [nothing happing in the nodes](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-06-20T08:00:00.000000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-long-running%22%0Aresource.labels.namespace_name%3D%22long-running%22%0Alabels.k8s-pod%2Fapp%3D%22long-running-zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22long-running%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0AjsonPayload.logger!%3D%22io.zeebe.broker.exporter.elasticsearch%22%0A&scrollTimestamp=2020-06-22T08:20:01.464196000Z&pinnedLogId=suhmu7tz2v62uszs6&pinnedLogTimestamp=2020-06-20T07:51:15.181259Z)

```
D 2020-06-20T07:51:15.181259Z Partition role transitioning from FOLLOWER to CANDIDATE 
D 2020-06-20T07:51:25.215208Z Partition role transitioning from CANDIDATE to FOLLOWER 
D 2020-06-20T07:51:44.834318Z Detected unhealthy components. The current health status of components: {Raft-2=HEALTHY, logStream=UNHEALTHY} 
E 2020-06-20T07:51:44.834770Z Partition-2 failed, marking it as unhealthy 
D 2020-06-20T08:10:41.926965Z Partition role transitioning from FOLLOWER to CANDIDATE 
D 2020-06-20T08:10:46.831298Z Partition role transitioning from CANDIDATE to FOLLOWER 
D 2020-06-22T08:19:50.813829Z Partition role transitioning from FOLLOWER to CANDIDATE 
D 2020-06-22T08:19:51.849798Z Partition role transitioning from CANDIDATE to FOLLOWER 
D 2020-06-22T08:19:56.052915Z Partition role transitioning from FOLLOWER to CANDIDATE 

```

**Side note:**

It seems that over the days the memory is growing and it seems GC can't release everything or it least we have a lot of long living objects or a memory leak.

highmem

With no load the memory looks like this:

noload

**To Reproduce**
Just run the cluster for long time and restart node.

**Expected behavior**
Leader is immediately chosen.

**Environment:**
 - OS: k8s
 - Zeebe Version: SNAPSHOT
 - Configuration: elastic

### LINKED ISSUE #4844: StateController is not removed as SnapshotListener on closing partition
**Describe the bug**
Since the StateController is not removed as SnapshotListener on closing partition this means we can replicate snapshots from followers and also multiple times from leader and followers etc.

In the last benchmarks it doesn't cause much harm, since after snapshot already exist on the remote node the chunks are just ignored. On #persist call a warn is printed that the pending dir can't be deleted, since no chunk have been applied. The pending dir was not created. Seen on https://github.com/zeebe-io/zeebe/issues/4686

It might cause a lot of traffic due to multiple snapshot replications. This only affects 0.24.0, since we refactored in this version the snapshot replication.

**To Reproduce**
Run a benchmark and cause a leader change.

**Expected behavior**
No multiple snapshot replications.

**Environment:**
 - OS: k8s
 - Zeebe Version: 0.24.0
 - Configuration:

### LINKED ISSUE #4847: MetricsTimer is not canceled on removing Leader partition
**Describe the bug**
We now reporting RocksDB in a five second rate. 

```

                            metricsTimer =
                                actor.runAtFixedRate(
                                    Duration.ofSeconds(5),
                                    () -> {
                                      if (zeebeDb != null) {
                                        metricExporter.exportMetrics();
                                      }
                                    });


```

When we step down we don't cancel this timer. This causes no harm, since the db is null at this point.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
@npepinpe @deepthidevaki who ever has time to review this. We can also talk shortly before you're starting with the review.

## Description

Some resources were not correctly closed or not removed as listener and some resources have been closed, where the responsibility was not existing. In general made some minor improvements on logging and closing resources in the ZeebePartition.

_QA Tests:_

 * use all nodes as initial contact pointes -> makes tests more stable -> less flaky 
 * Add functionallity to the clustering rule to cause a network partition and to step down from the leadership
 * Added new tests which test whether leader steps down on network partition and new leader is chosen and that replication still works on reconnect.
 * Added regression test for #4810

_Fixes:_

 Added new interface to close asynchronously a resource. Remove in the ZeebePartition the hybrid handling of resources.
 Now we have just a closable list which is iterated on closing the partition.

  * SnapshotStore is not closed in ZeebePartition, since the ZeebePartition is not responsible for that and causes an bug #4810.
  * StateController is only registered for replication on LeaderPartition, fixes #4844
  *  MetricsTimer is closed correctly, fixes #4847

 The state controller was previous also registered on follower side, which caused replication on follower side when new snapshot was received this caused #4686 this is fixed now.

## Related issues

closes #4810 
closes #4844
closes #4847
closes #4686

## Benchmark

Looks good.

genral
snapshot

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/FailOverReplicationTest.java [hunk 1]
```diff
@@ -0,0 +1,247 @@
...
+    try {
+      return Files.list(clusteringRule.getSegmentsDirectory(broker))
+          .filter(path -> path.toString().endsWith(".log"))
+          .collect(Collectors.toList());
+    } catch (final IOException e) {
+      throw new UncheckedIOException(e);
+    }
+  }
+
+  private void fillSegments(final List<Broker> brokers, final int segmentCount) {
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/FailOverReplicationTest.java:215]:
```suggestion
  private void sendCommandAndAwaitMinimumSegmentCount(final List<Broker> brokers, final int segmentCount) {
```

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/FailOverReplicationTest.java [hunk 2]
```diff
@@ -0,0 +1,247 @@
...
+    final var followerA =
+        followers.stream()
+            .filter(broker -> broker.getConfig().getCluster().getNodeId() != previousLeaderId)
+            .findFirst()
+            .orElseThrow();
+
+    // Leader and Follower A have new entries
+    // which Follower B - old leader hasn't
+    fillSegments(List.of(newLeader, followerA), 2);
+    awaitSnapshot(newLeader);
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/FailOverReplicationTest.java:176]: Why are we waiting for a snapshot/the snapshot to be replicated?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 3]
```diff
@@ -84,7 +84,7 @@
   private final TypedRecordProcessorsFactory typedRecordProcessorsFactory;
   private final CommandApiService commandApiService;
   private final List<PartitionListener> partitionListeners;
-  private final List<Actor> closeables = new ArrayList<>();
+  private final List<AsyncClosable> asyncClosables = new ArrayList<>();
```
Comment (npepinpe) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:87]:
```suggestion
  private final List<AsyncClosable> managedResources = new ArrayList<>();
```

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 4]
```diff
@@ -399,30 +395,34 @@ private void transitionToLeader(final CompletableActorFuture<Void> transitionCom
...
-    closeables.add(deletionService);
+    asyncClosables.add(deletionService);
 
     return scheduler.submitActor(deletionService);
   }
 
+  private void registerSnapshotListenerForReplication() {
+    asyncClosables.add(
+        () -> {
+          persistedSnapshotStore.removeSnapshotListener(snapshotController);
```
Comment (npepinpe) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:416]: Can we also extract this to a method?

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 5]
```diff
@@ -485,6 +486,22 @@ private void installProcessingPartition(final CompletableActorFuture<Void> insta
             });
   }
 
+  private void installRocksDBMetricExporter(final ZeebeRocksDBMetricExporter metricExporter) {
+    final var metricsTimer =
+        actor.runAtFixedRate(
+            Duration.ofSeconds(5),
+            () -> {
+              if (zeebeDb != null) {
```
Comment (npepinpe) [inline broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:494]: Who closes `zeebeDb`? `ZeebePartition`? `StateSnapshotController`? Just wondering if this null check is enough.

Also, a little out of scope but since we're here, should we rather reschedule the next metrics export here instead of using `runAtFixedRate`? We've ran into issues before where you may build up a lot of tasks with `runAtFixedRate`, no? Though I guess here our actor is usually not very busy, so :man_shrugging:

**Review by npepinpe — CHANGES_REQUESTED** [review]
Looks good, I like the ideas for testing network partitions! Since it was a bit longer, we can also go over it via zoom, it's always faster f2f :slightly_smiling_face: 

Apart from the comments, some notes/questions that came up:

1. We still use `TestUtil.waitUntil` a bunch - any reason to prefer this over `Awaitility`?
1. How could we be better in the future to avoid dangling resources? Are there tests we could write for this, or maybe a different way of initializing managed resources?

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/FailOverReplicationTest.java [hunk 6]
```diff
@@ -0,0 +1,247 @@
...
+    // when
+    clusteringRule.disconnect(leader);
+
+    // then
+    final var newLeader = clusteringRule.awaitOtherLeader(1, leaderNodeId);
+    assertThat(newLeader.getNodeId()).isNotEqualTo(leaderNodeId);
+  }
+
+  @Test
+  public void shouldNotReceiveEntriesOnDisconnect() {
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/FailOverReplicationTest.java:68]: Please comment explaining why this test is there

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/FailOverReplicationTest.java [hunk 7]
```diff
@@ -0,0 +1,247 @@
...
+    // when
+    clusteringRule.connect(oldLeader);
+
+    // then
+    TestUtil.doRepeatedly(() -> getSegmentsCount(oldLeader)).until(count -> count >= segmentCount);
+    assertThat(getSegmentsCount(oldLeader)).isGreaterThanOrEqualTo(segmentCount);
+  }
+
+  @Test
+  public void shouldStillReceiveEntriesAfterStepDown() {
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/FailOverReplicationTest.java:102]: Let's remove this and rewrite to ensure we are compacting after failover

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 3 above)
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java:87]: would be nice if github had a replace all

**Comment by Zelldon** [comment]
@npepinpe thanks for the fast review I applied the review hints we discussed

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java [hunk 8]
```diff
@@ -634,38 +692,28 @@ public FileBasedSnapshotMetadata waitForSnapshotAtBroker(final Broker broker) {
...
-
-    return referenceToResult
-        .get()
+
+    return Awaitility.await()
+        .pollInterval(Duration.ofMillis(100))
+        .atMost(Duration.ofMinutes(1))
+        .until(
+            () -> {
+              final var files = snapshotsDir.listFiles();
```
Comment (npepinpe) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java:705]: This is a pretty long lambda, can we extract it to a method?

**Review by npepinpe — CHANGES_REQUESTED** [review]
One small thing, and I still have to test it, sorry - I'll do it tomorrow morning first thing :+1:

**Comment by deepthidevaki** [comment]
Should I also review it since @npepinpe has already reviewed?

**Comment by Zelldon** [comment]
I think it is not necessary but If you want you can of course do it.

**Comment by npepinpe** [comment]
Agreed - so as long as we have someone who is reviewing it it's fine, but it's also totally OK to have more than one reviews if you think we might've missed something or had some ideas :slightly_smiling_face:

**Comment by npepinpe** [comment]
Seems like this causes some consistent test failures with snapshot replication. But from my side it looks good :+1: Just re-request a review once the tests are passing (excluding flaky ones)

**Review by npepinpe — APPROVED** [review]
Looks good, but let's merge https://github.com/zeebe-io/zeebe/pull/4870 first since it'll be cherry picked into the release branch. It might cause some conflict in ZeebePartition though - wdyt?

**Comment by Zelldon** [comment]
@npepinpe yep sounds good to me. I will also adjust some tests then to maybe rely on the leaderlistener instead of the topology, because turns out it is a bit flaky

**Comment by npepinpe** [comment]
Also seems the `FailOverReplicationTest` fails but the error is that the XML report cannot be parsed? :thinking:

**Comment by Zelldon** [comment]
bors retry
