### PR TITLE
Prevent activation of failed job without retries

### LINKED ISSUE #10308: I can activate a failed job that has no remaining retries
**Describe the bug**

I can active a job marked as failed with no retries left. In the process instance, the related service task has an incident. 

I should not be able to activate the job. It should require resolving the incident first. Otherwise, this violates the semantics of the job retries.

After activating the job (but not resolving the incident), I can complete the job. The process instance continues but the incident is not marked as resolved.

**To Reproduce**

1. deploy the process: [process-with-service-task.bpmn.txt](https://github.com/camunda/zeebe/files/9533644/process-with-service-task.bpmn.txt)
2. create a new instance of the process
3. mark the job as failed with no retries (e.g. with job key `2251799813685258`)
```
zbctl --insecure fail job 2251799813685258 --retries=0
----------------------------------------------------------------------------------------------
Failed job with key '2251799813685258' and set remaining retries to '0'
``` 
4. activate jobs of this type
```
zbctl --insecure activate jobs A
----------------------------------------------------------------------------------------------
{
  "jobs": [
    {
      "key": "2251799813685258",
      "type": "A",
      "processInstanceKey": "2251799813685253",
      "bpmnProcessId": "process-with-service-task",
      "processDefinitionVersion": 1,
      "processDefinitionKey": "2251799813685251",
      "elementId": "Activity_15nqzqo",
      "elementInstanceKey": "2251799813685257",
      "customHeaders": "{}",
      "worker": "zbctl",
      "retries": 0,
      "deadline": "1662710683385",
      "variables": "{}"
    }
  ]
}
```
5. complete the job
```
zbctl --insecure complete job 2251799813685258
----------------------------------------------------------------------------------------------
Completed job with key '2251799813685258' and variables '{}'
```
6. verify that the process instance continues but the incident is not resolved

**Expected behavior**

I can't activate a job that is marked as failed and has no remaining retries.

**Log/Stacktrace**

image

**Environment:**
- OS: 
- Zeebe Version: `8.0.5`
- Configuration:

### LINKED ISSUE #10309: ZeebeDbInconsistentException INCIDENT_JOBS already exists
**Describe the bug**

An error was reported indicating that 1 of 3 partitions (partition 2) is marked as DEAD, due to a consistency check that safeguards against corrupted data. This is likely due to a bug.

The impact is that all processing on that partition stops, and all process instances on that partition can no longer make progress. Instances on the partitions are unaffected.

The reported error was:

> Broker-2-StreamProcessor-2 failed, marking it as dead: Broker-2-StreamProcessor-2{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{4503599721837837}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda$1437/0x00000008014656c8@4febef84] in ColumnFamily INCIDENT_JOBS already exists, cause=null]}

The specific case has been resolved by disabling the consistency check and allowing the additional incident to be written for the job. However, the root cause has not been resolved.

**To Reproduce**

- unclear at this time

**Expected behavior**

Only a single incident should exist for a job at any time

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2022-09-08 13:28:35.272 CEST
zeebe
Received new exporter state {elasticsearch=194625463, MetricsExporter=194625463}
2022-09-08 13:28:38.649 CEST
zeebe
Received new exporter state {elasticsearch=189124268, MetricsExporter=189124268}
2022-09-08 13:28:38.649 CEST
zeebe
Received new exporter state {elasticsearch=189124268, MetricsExporter=189124268}
2022-09-08 13:28:40.758 CEST
zeebe
Actor Broker-1-StreamProcessor-2 failed in phase STARTED.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.759 CEST
zeebe
Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$2335/0x000000080170d1d8 QUEUED from fastLane of Actor Broker-1-StreamProcessor-2.
2022-09-08 13:28:40.761 CEST
zeebe
Broker-1-StreamProcessor-2 failed, marking it as dead: Broker-1-StreamProcessor-2{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{4503599721837837}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda$1445/0x000000080146f118@1b83e0ac] in ColumnFamily INCIDENT_JOBS already exists, cause=null]}
2022-09-08 13:28:40.764 CEST
zeebe
Detected 'DEAD' components. The current health status of components: [ZeebePartition-2{status=HEALTHY}, Broker-1-Exporter-2{status=HEALTHY}, raft-partition-partition-2{status=HEALTHY}, Broker-1-LogStream-2{status=HEALTHY}, Broker-1-SnapshotDirector-2{status=HEALTHY}, Broker-1-StreamProcessor-2{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{4503599721837837}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda$1445/0x000000080146f118@1b83e0ac] in ColumnFamily INCIDENT_JOBS already exists, cause=null]}]
2022-09-08 13:28:40.835 CEST
zeebe
Transition to INACTIVE on term 5 requested.
2022-09-08 13:28:40.836 CEST
zeebe
Partition-2 failed, marking it as dead: Broker-1-ZeebePartition-2{status=DEAD, issue=HealthIssue[message=null, throwable=null, cause=null]}
```

</p>
</details>

**Environment:**
- Instance: `807c46c7-9459-4ac8-bacb-e71c45d9e897`
- Zeebe Version: 8.0.5
- Configuration: G3-Trial cluster

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

When a job has failed and has no retries left, it should no longer be possible to activate this job. Activating this job would result in an incident. Since there already is an incident a second one will be created. This will conflict with the consistency checks, where we only allow a single incident for a task.

## Related issues

closes #10308 
closes #10309 (most likely this will be fixed by this PR as well)

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java [hunk 1]
```diff
@@ -212,6 +213,12 @@ public JobRecord updateJobRetries(final long jobKey, final int retries) {
     if (job != null) {
       job.setRetries(retries);
       updateJobRecord(jobKey, job);
+
+      if (retries <= 0) {
+        makeJobNotActivatable(job.getTypeBuffer());
```
Comment (saig0) [inline engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:218]: :thinking: This part is not reachable. The [processor](https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobUpdateRetriesProcessor.java#L38) doesn't accept if retries are less than 1.

We could remove this part.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobUpdateRetriesTest.java [hunk 2]
```diff
@@ -158,4 +160,28 @@ public void shouldRejectUpdateRetriesIfRetriesLessThanZero() {
     // then
     Assertions.assertThat(jobRecord).hasRejectionType(RejectionType.INVALID_ARGUMENT);
   }
+
+  @Test
+  public void shouldMakeJobActivatableAfterIncreasingRetries() {
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobUpdateRetriesTest.java:165]: :question: Why do we change the behavior of updating job retries?

Before, the job update command doesn't make the job activatable. Instead, only the incident resolve command made the job activable again.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivateJobsTest.java [hunk 3]
```diff
@@ -455,6 +455,36 @@ public void shouldActivateJobUpToMaxMessageSize() {
         .isEqualTo(Map.of("foo", "x".repeat(variablesSize), "bar", "x".repeat(variablesSize)));
   }
 
+  // regression test for https://github.com/camunda/zeebe/issues/10308
+  @Test
+  public void shouldNotActivateJobWithNoRemainingRetries() {
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivateJobsTest.java:460]: :x: Additionally, we should add a similar test case to the unit test for the state `JobStateTest`.

We need a similar test case as [shouldFailJobWithNoRetriesLeft()](https://github.com/camunda/zeebe/blob/main/engine/src/test/java/io/camunda/zeebe/engine/state/instance/JobStateTest.java#L428-L445) but without activation.

**Review by saig0 — CHANGES_REQUESTED** [review]
@remcowesterhoud thank you for fixing the issue. :+1: 

I have one minor comment about a missing test case. And a question about the changed behavior when updating the job retries. Please have a look.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobUpdateRetriesTest.java (hunk 2 above)
Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobUpdateRetriesTest.java:165]: Doesn't it make sense that if a job has retries, it is possible to activate it? Do we always have to use this command in combination with an incident resolve?

Before we still have this bug where the job stays activatable. So increasing the retries would mean the job is activatable like before. I suppose this could still lead to the consistency issue if the incident is not resolve so perhaps it's better to leave this out.

File: engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java (hunk 1 above)
Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java]: I have removed the changes to the `updateJobRetries` in its entirety, because of your comment below this.

**Review by saig0 — APPROVED** [review]
@remcowesterhoud LGTM. :+1:

**Comment by saig0** [comment]
bors merge
