### PR TITLE
fix: validate that all bpmn elements have an identifier

### LINKED ISSUE #26248: BPMN model with missing element ID fails with NPE during deployment
**Describe the bug**

A Zeebe deployment of a BPMN model with missing element IDs will fail during resource transformation with a `NullPointerException` as the element ID is a required property.

**To Reproduce**

1. Manually remove an ID from a `LinkedIntermediateCatchEvent`.
2. Deploy the modified model.

**Expected behavior**

The deployment fails on deployment (design) validation and reports a missing ID to the user.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "value" is null

at io.camunda.zeebe.util.StringUtil.getBytes ( io/camunda.zeebe.util/StringUtil.java:39 )
at io.camunda.zeebe.util.StringUtil.getBytes ( io/camunda.zeebe.util/StringUtil.java:35 )
at io.camunda.zeebe.util.buffer.BufferUtil.wrapString ( io/camunda.zeebe.util.buffer/BufferUtil.java:42 )
at io.camunda.zeebe.engine.processing.deployment.model.element.AbstractFlowElement.<init> ( io/camunda.zeebe.engine.processing.deployment.model.element/AbstractFlowElement.java:23 )
at io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableLink.<init> ( io/camunda.zeebe.engine.processing.deployment.model.element/ExecutableLink.java:19 )
at io.camunda.zeebe.engine.processing.deployment.model.transformer.CatchEventTransformer.transformLinkEventDefinition ( io/camunda.zeebe.engine.processing.deployment.model.transformer/CatchEventTransformer.java:185 )
at io.camunda.zeebe.engine.processing.deployment.model.transformer.CatchEventTransformer.transformEventDefinition ( io/camunda.zeebe.engine.processing.deployment.model.transformer/CatchEventTransformer.java:82 )
at io.camunda.zeebe.engine.processing.deployment.model.transformer.CatchEventTransformer.transform ( io/camunda.zeebe.engine.processing.deployment.model.transformer/CatchEventTransformer.java:61 )
at io.camunda.zeebe.engine.processing.deployment.model.transformer.CatchEventTransformer.transform ( io/camunda.zeebe.engine.processing.deployment.model.transformer/CatchEventTransformer.java:47 )
at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit ( io/camunda.zeebe.engine.processing.deployment.model.transformation/TransformationVisitor.java:42 )
at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit ( io/camunda.zeebe.model.bpmn.traversal/TypeHierarchyVisitor.java:39 )
at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk ( io/camunda.zeebe.model.bpmn.traversal/ModelWalker.java:73 )
at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions ( io/camunda.zeebe.engine.processing.deployment.model.transformation/BpmnTransformer.java:118 )
at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$createMetadata$3 ( io/camunda.zeebe.engine.processing.deployment.transform/BpmnResourceTransformer.java:88 )
at io.camunda.zeebe.util.Either$Right.flatMap ( io/camunda.zeebe.util/Either.java:417 )
at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.createMetadata ( io/camunda.zeebe.engine.processing.deployment.transform/BpmnResourceTransformer.java:81 )
at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.createMetadata ( io/camunda.zeebe.engine.processing.deployment.transform/DeploymentTransformer.java:178 )
at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform ( io/camunda.zeebe.engine.processing.deployment.transform/DeploymentTransformer.java:120 )
at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment ( io/camunda.zeebe.engine.processing.deployment/DeploymentCreateProcessor.java:196 )
at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand ( io/camunda.zeebe.engine.processing.deployment/DeploymentCreateProcessor.java:139 )
at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord ( io/camunda.zeebe.engine.processing.streamprocessor/DistributedTypedRecordProcessor.java:33 )
at io.camunda.zeebe.engine.Engine.process ( io/camunda.zeebe.engine/Engine.java:129 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:375 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3 ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:285 )
at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run ( io/camunda.zeebe.db.impl.rocksdb.transaction/ZeebeTransaction.java:109 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:285 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:244 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:83 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:42 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:122 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 )
```

</p>
</details>

**Environment:**
- OS: Camunda SaaS Prod
- Zeebe Version: 8.7.0-alpha2
- Configuration:

### PR DESCRIPTION
**Pull request by giampa91**
## Description

Introduces:
- A new `IdentifiableBpmnElement` interface for BPMN elements with identifiers, which can also be used for extension elements like `ZeebeUserTaskForm`
- A validator to systematically validate that all `IdentifiableBpmnElement` implementations have an ID

## Related issues

closes #26248

### CODE REVIEW

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/ActivityValidator.java [hunk 1]
```diff
@@ -17,10 +17,10 @@
 
 import io.camunda.zeebe.model.bpmn.instance.Activity;
 import io.camunda.zeebe.model.bpmn.util.ModelUtil;
-import org.camunda.bpm.model.xml.validation.ModelElementValidator;
 import org.camunda.bpm.model.xml.validation.ValidationResultCollector;
 
-public class ActivityValidator implements ModelElementValidator<Activity> {
+public class ActivityValidator extends IdentifiableBpmnElementValidator<Activity> {
+
```
Comment (korthout) [inline zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/ActivityValidator.java:23]: ❌ Let's [avoid inheritance as a way to reuse code](https://github.com/camunda/camunda/wiki/Code-Style#favor-final-modifier). Please use composition instead: Call the `validate` method of `IdentifiableBpmnElementValidator` inside this class's `validate` method, either by making `IdentifiableBpmnElementValidator#validate` a static method, or keep an instance of `IdentifiableBpmnElementValidator` as a field and call the instance method.

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/ValidationVisitor.java [hunk 2]
```diff
@@ -18,6 +18,7 @@
 import static java.util.stream.Collectors.groupingBy;
 
 import io.camunda.zeebe.model.bpmn.instance.BpmnModelElementInstance;
+import io.camunda.zeebe.model.bpmn.instance.TimerEventDefinition;
```
Comment (korthout) [inline zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/ValidationVisitor.java:21]: ❌ Please remove this redundant import

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @giampa91 for your first contribution to this repo! 🙌 

💭 Apologies for having to wait so long before our reply.

👍 I really like the idea to move the `id` to a separate reusable interface.
👍 The change in the api is backward compatible.

❌ We favor composition over inheritance, especially when concerning code reuse. Please adjust the validation changes accordingly.

❌ Also please ensure you run `mvn spotless:apply` to auto-format the code correctly.

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/ActivityValidator.java (hunk 1 above)
Comment (giampa91) [reply zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/ActivityValidator.java]: Thanks korthout, I decided to use a static method, because in the end we don't use a complex validation for id that require a dependency.

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks a lot @giampa91 🚀 

:x: I have one last request before we can merge this:
- Please add a test case to [`ValidateProcessTest`](https://github.com/camunda/camunda/blob/main/zeebe/bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/validation/ValidateProcessTest.java) that shows that we require process to have an ID
- Bonus: Test it for all IdentifiableBpmnElements

🔧 Please also rebase your changes [rather than using a merge commit to](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#updating-a-pull-request).

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/IdentifiableBpmnElementValidator.java [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+import io.camunda.zeebe.model.bpmn.instance.IdentifiableBpmnElement;
+import org.camunda.bpm.model.xml.validation.ValidationResultCollector;
+
+public class IdentifiableBpmnElementValidator {
+
+  public static <T extends IdentifiableBpmnElement> void validate(
+      final T element, final ValidationResultCollector validationResultCollector) {
+    if (element.getId() == null || element.getId().isEmpty()) {
+      validationResultCollector.addError(0, "Link id must be present and not empty.");
```
Comment (korthout) [inline zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/IdentifiableBpmnElementValidator.java:26]: ❌ I just noticed this when you added the test case.

```suggestion
      validationResultCollector.addError(0, "Element id must be present and not empty.");
```

**Review by korthout — CHANGES_REQUESTED** [review]
:x: your changes are failing the [Reject merge commits](https://github.com/camunda/camunda/actions/runs/14945996057/job/42145668702) CI workflow. Please rebase your changes [rather than using a merge commit to](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#updating-a-pull-request).

**Comment by giampa91** [comment]
Thank you @korthout  🚀

- I've adjusted the commit message to comply with commitlint. 
- Additionally, I've reviewed the failing tests and removed the ID validation from the ZeebeLoopCharacteristicsValidator and other classes where it wasn't actually required.
- I've also squashed all the changes into a single commit for a cleaner history. 
- Finally, I ran mvn spotless:apply again just to be sure everything is formatted correctly.

Hopefully, the CI pipeline should pass this time, if I am not missing something else. 
Let me know if there's anything else I can do!

**Review by korthout — CHANGES_REQUESTED** [review]
I had another look to ensure that we don't unnecessarily break backward compatibility with process models that could be deployed previously.

**Review by korthout — APPROVED** [review]
🙇 I've added a commit to remove the unnecessary validations.

With that, I think we can merge this 👍 LGTM 

🚀 Thanks again for this great contribution @giampa91
