### PR TITLE
Reject terminate instruction when element instance not found

### LINKED ISSUE #9983: Reject the modification command if an element instance for termination doesn't exist
## Description

The modification command can contain termination instructions for different element instances. The element instances are identified by their element instance keys. 

If at least one element instance key doesn't exist then the command should be rejected. 

This could happen if the key is wrong, or the element instance is already completed or terminated.

Edge case: the given element instance is currently in the state `terminating` (because it is terminated currently by another command or within the process). In this case, the command should be also rejected because the element instance can't be terminated. But the element instance will be terminated eventually.     

Blocked by 
- #9690

### PR DESCRIPTION
**Pull request by korthout**
## Description

The modification command can contain terminate instructions for different element instances. The element instances are identified by their keys. If at least one element instance key is unknown (i.e. no element instance with the given key can be found) then the command is rejected as NOT_FOUND.

The reason for the rejection contains a reference to the Bpmn Process ID and all of the unknown element instance keys. For example:
`Expected to modify instance of process 'process' but it contains one or more terminate instructions with an element instance that could not be found: '123', '456'`

## Related issues

closes #9983 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java [hunk 1]
```diff
@@ -121,7 +125,7 @@ public void processRecord(
     final var process =
         processState.getProcessByKey(processInstanceRecord.getProcessDefinitionKey());
 
-    final var validationResult = validateCommand(command, process);
+    final var validationResult = validateCommand(command, process, processInstance);
```
Comment (remcowesterhoud) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationProcessor.java:128]: 🔧 We don't need the `processInstance` here. The only reason we are using it is for getting the process id, which is already available in the `process`.

**Review by remcowesterhoud — APPROVED** [review]
Good work @korthout, sorry for taking long to review it 🙇 

I have one small comment, LGTM otherwise.

**Comment by korthout** [comment]
bors merge
