### PR TITLE
fix: handle API conversion errors as validation errors

### LINKED ISSUE #48578: MCP gateway: invalid search filter values cause 500 with Java class name leak
### Description

The MCP gateway returns 500 Internal Server Error with fully qualified Java class names in the error title when search filter fields receive invalid values. This affects two categories of input:

1. **Non-numeric key strings:** String-typed key filter fields (e.g. `processInstanceKey`, `processDefinitionKey`, `scopeKey`) are converted via `Long.valueOf((String) value)` in `AdvancedSearchFilterUtil.convertValue()` without validation. Values like `""` or `"abc"` cause an unhandled `NumberFormatException`.

2. **Invalid date strings:** Date filter fields like `startDate`, `endDate`, `creationTime` accept arbitrary strings. Values like `"not-a-date"` fail during `OffsetDateTime.parse()` in `convertValue()`, producing an `IllegalArgumentException`.

In both cases, the exception is not a `ServiceException`, so `GatewayErrorMapper.mapErrorToProblem()` maps it to a 500 and sets the error title to `exception.getClass().getName()`, leaking Java class names like `java.lang.NumberFormatException` or `java.lang.IllegalArgumentException`.

The REST API is not affected — its `GlobalControllerExceptionHandler` has a catch-all `@ExceptionHandler(Exception.class)` that maps unhandled exceptions to 400 Bad Request with generic titles.

**Affected MCP tools/fields:**
- `searchProcessInstances` (`processInstanceKey`, `processDefinitionKey`, `startDate`, `endDate`)
- `searchProcessDefinitions` (`processDefinitionKey`)
- `searchIncidents` (`processDefinitionKey`, `processInstanceKey`, `creationTime`)
- `searchUserTasks` (`userTaskKey`, `processDefinitionKey`, `processInstanceKey`, `elementInstanceKey`, `creationDate`, `dueDate`, `followUpDate`)
- `searchVariables` (`variableKey`, `scopeKey`, `processInstanceKey`)

### Steps to reproduce

1. Call any MCP search tool with a non-numeric key filter:
   ```bash
   curl -s -X POST http://localhost:8080/mcp/cluster \
     -H "Content-Type: application/json" -H "Accept: application/json, text/event-stream" \
     -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"searchProcessInstances","arguments":{"filter":{"processInstanceKey":"abc"}}}}'
   ```
2. Or call with an invalid date filter:
   ```bash
   curl -s -X POST http://localhost:8080/mcp/cluster \
     -H "Content-Type: application/json" -H "Accept: application/json, text/event-stream" \
     -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"searchProcessInstances","arguments":{"filter":{"startDate":{"from":"not-a-date"}}}}}'
   ```

### Current behavior

500 Internal Server Error with Java class name in the error title:
```json
{"status":500,"title":"java.lang.NumberFormatException","detail":"Unexpected error occurred during the request processing: For input string: \"abc\""}
```
```json
{"status":500,"title":"java.lang.IllegalArgumentException","detail":"Unexpected error occurred during the request processing: Failed to parse date-time: [not-a-date]"}
```

### Expected behavior

400 Bad Request with a structured ProblemDetail and generic title (no Java class names):
```json
{"status":400,"title":"INVALID_ARGUMENT","detail":"Invalid value for key field: [abc] is not a valid number"}
```

### Version

* Component Version: 8.10-SNAPSHOT

### Rootcause

`CallToolResultMapper.mapErrorToResult()` in `gateway-mcp` delegates directly to `GatewayErrorMapper.mapErrorToProblem()`, which maps non-`ServiceException` errors to 500 with `exception.getClass().getName()` as the title (line 51 in `GatewayErrorMapper`). There is no MCP-layer interception for `IllegalArgumentException` or `NumberFormatException`.

Additionally, `AdvancedSearchFilterUtil.convertValue()` in `gateway-mapping-http` wraps `DateTimeParseException` as `IllegalArgumentException` but lets `NumberFormatException` from `Long.valueOf()` escape raw.

### Solution ideas

1. In `AdvancedSearchFilterUtil.convertValue()`: wrap `Long.valueOf()` in try-catch and throw `IllegalArgumentException` (matching existing date pattern)
2. In `CallToolResultMapper.mapErrorToResult()`: intercept `IllegalArgumentException` → map to 400 INVALID_ARGUMENT; for remaining 500s, replace `exception.getClass().getName()` with generic `"Internal Server Error"` title

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by maff**
## Description

Instead of throwing exception on conversion errors (from String to Long or to OffsetDateTime), add to the list of validation errors and return a collection of validation errors (see [comment](https://github.com/camunda/camunda/issues/48578#issuecomment-4066021617) on the original issue).

This fixes multiple issues from #48578, but also makes the REST API validation more usable as it collects errors:

- Key conversion errors in MCP tool filters lead to `400 Bad Request` responses with a proper validation message. Same for OffsetDateTime conversions.
- No leaked Java class names in validation error messages.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #48578

### CODE REVIEW

File: gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/util/AdvancedSearchFilterUtil.java [hunk 1]
```diff
@@ -25,51 +28,84 @@ public class AdvancedSearchFilterUtil {
 
   private static final Logger LOG = LoggerFactory.getLogger(AdvancedSearchFilterUtil.class);
 
-  public static <T> Function<Object, List<Operation<T>>> mapToOperations(final Class<T> tClass) {
-    return (final Object filter) -> mapToOperations(filter, tClass);
+  public static Function<Object, List<Operation<Long>>> mapToKeyOperations(
```
Comment (maff) [inline gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/util/AdvancedSearchFilterUtil.java:31]: ℹ️ I called this `toKeyOperations` as all callers of this method are related to keys and this allows us to use the key-specific error message. If we need an additional `Long` overload in the future, I'd suggest to add it as a separate one.

File: gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/util/AdvancedSearchFilterUtil.java [hunk 2]
```diff
@@ -25,51 +28,84 @@ public class AdvancedSearchFilterUtil {
...
+      final CustomConverter<String> converter) {
+    return (final Object filter) ->
+        mapToTypedOperations(
+            filter,
+            value -> {
+              if (converter.canConvert(value)) {
+                try {
+                  return converter.convertValue(value);
+                } catch (final Exception e) {
+                  validationErrors.add(
```
Comment (maff) [inline gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/util/AdvancedSearchFilterUtil.java:83]: ℹ️ I experimented with adding the validation errors to the converters but ended up with this variant to reduce the amount of changes on this PR. We' probably have 2 options if we want to move it to the converter:

- pass field name and list of errors to the converter constructor (making the converter stateful for the value)
- pass field name and list of errors to the `convertValue` method

If we want to do this, I'd suggest we do it in a follow-up.

File: gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/util/AdvancedSearchFilterUtil.java (hunk 1 above)
Comment (tmetzke) [reply gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/util/AdvancedSearchFilterUtil.java:31]: I like it 👍

File: gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/util/AdvancedSearchFilterUtil.java (hunk 2 above)
Comment (tmetzke) [reply gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/util/AdvancedSearchFilterUtil.java:83]: Good call 👍

File: gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/search/SearchQueryFilterMapper.java [hunk 3]
```diff
@@ -184,105 +188,108 @@ public class SearchQueryFilterMapper {
...
-          .ifPresent(builder::typeOperations);
+      ofNullable(filter.getType()).map(mapToStringOperations()).ifPresent(builder::typeOperations);
       ofNullable(filter.getWorker())
-          .map(mapToOperations(String.class))
+          .map(mapToStringOperations())
           .ifPresent(builder::workerOperations);
       ofNullable(filter.getState())
-          .map(mapToOperations(String.class))
+          .map(mapToStringOperations())
           .ifPresent(builder::stateOperations);
```
Comment (tmetzke) [inline gateways/gateway-mapping-http/src/main/java/io/camunda/gateway/mapping/http/search/SearchQueryFilterMapper.java:205]: ℹ️ Quite interestingly, this is an enum field in the HTTP DTO filter class. We simply call `toString` on the enum instance then. Seems to work, but it's actually deviating from what we do for most enums. I didn't know that we do this 😅

**Review by tmetzke — APPROVED** [review]
👍 Love this, way more consistent type conversion handling 🚀 

//cc @megglos and @nicpuppa for awareness that we adjusted the REST-filter-to-search-filter conversion. It now collects validation errors for all REST filter advanced criteria that cannot be converted to operations. Previously, we simply threw an exception on the first thing we couldn't convert and caught those exceptions in the global exception handler. This didn't scale to other consumers like the MCP gateway.

**Review by tmetzke — APPROVED** [review]
👍 Nice additions in the latest commits to make it more consistent and general 🚀

**Comment by nicpuppa** [comment]
@maff @tmetzke @megglos this might be a breaking change 

## Impact on REST API Customers

| Aspect | Before | After | Breaking? |
|--------|--------|-------|-----------|
| HTTP status code | `400` | `400` | ✅ No |
| ProblemDetail `title` | `"Bad Request"` | `"INVALID_ARGUMENT"` | ⚠️ **Yes** |
| ProblemDetail `detail` | `"Failed to parse date-time: [invalid]"` | `"The provided evaluationDate 'invalid' cannot be parsed as a date according to RFC 3339, section 5.6."` | ⚠️ **Yes** |
| Error collection | Fails on first error | Collects all validation errors | ⚠️ **Yes** (response may contain more info) |

## Who Is Affected?

- **Customers parsing error response bodies** (specifically `title` or `detail` fields) for validation errors → **affected**
- **Customers only checking HTTP status codes** on the REST API → **not affected**
- **Customers sending valid requests** → **not affected at all** (happy path is unchanged)

## Conclusion

This is a **low-risk behavioral change on error paths only**. It improves error handling consistency and fixes a bug (500 + Java class name leak in MCP). However, any customer programmatically matching on `"Bad Request"` in the `title` field or parsing the `detail` message string for conversion errors would need to adapt. If we consider ProblemDetail `detail` messages not stable API contracts, this is acceptable as a bug fix rather than a breaking API change.

**Comment by tmetzke** [comment]
Good analysis, @nicpuppa, thanks for this 👍

I agree with your assessment. It is a behavior change in the REST API for error responses. It's no API contract change 👍

I agree that's a low-risk one as well, but risks tend to grow with increasing user bases. So, I'd suggest we add this to list of behavior changes in the update guide. Wdyt?

**Comment by nicpuppa** [comment]
@tmetzke I'll take care of the docs

**Comment by nicpuppa** [comment]
here is the PR https://github.com/camunda/camunda-docs/pull/8312

**Comment by tmetzke** [comment]
> here is the PR [camunda/camunda-docs#8312](https://github.com/camunda/camunda-docs/pull/8312)

Thanks a lot, @nicpuppa, for noticing, describing, and documenting this 🫶
