### PR TITLE
Static multi-instance body input collections

### LINKED ISSUE #31837: Multi-Instance body does not complete if the amount of items in the input collection is changed dynamically
### 

### 

, , , , , 

### 

### 

### Description

Multi-Instance bodies require an input collection. For each of the elements in this collection the child element within gets activated. Once all of the child elements are compled the MI-body should complete.

Since this input collection is a variable it is possible to modify this dynamically. With https://github.com/camunda/camunda/pull/21442 we've added a check on this size of this input collection which determines if the MI-body can be completed or not. The check takes the size of the input collection and compare it against the number of completed/terminated child elements. If this is **equal** the MI-body is completed.

Now imagine a scenario where we dynamically add/remove elements to this input collection. What will (assuming parallel MI) happen is:

1. The input collection has 1 element
2. 1 child instance gets activated
3. During processing of this child instance, the input collection variable is updated. The element is removed from the input collection.
4. Once the child instance completes there the MI-body processor retrieves the, now updated, input collection. It determines the amount of elements in there, which will be 0. It compares it to the amount of completed child instances, which will be 1. This is not equal so the MI-body does not get completed.
5. The process instance is stuck

This is a very minimal example. Of course there is more scenarios, such as having a larger input collection. I haven't verified it but I would expect it's possible the MI-body completes too soon. Then there's also the scenario of adding more elements to the input collection instead of removing them.

### Steps to reproduce

I've created a unit test to reproduce this:

```java
  @Test
  public void shouldCompleteWhenChangingInputCollectionDuringProcessing() {
    // given
    final var processId = "processId";
    final var inputCollectionVariable = "items";
    final var jobType = "jobType";
    final var process =
        Bpmn.createExecutableProcess(processId)
            .startEvent()
            .subProcess(
                "subProcessId",
                s ->
                    s.multiInstance(
                        b ->
                            b.zeebeInputCollectionExpression(inputCollectionVariable)
                                .zeebeInputElement("item")))
            .embeddedSubProcess()
            .startEvent("sub-process-start")
            .serviceTask("task", t -> t.zeebeJobType(jobType))
            .zeebeInputExpression("[]", inputCollectionVariable)
            .endEvent()
            .done();

    ENGINE.deployment().withXmlResource(process).deploy();

    ENGINE
        .processInstance()
        .ofBpmnProcessId(processId)
        .withVariable(inputCollectionVariable, List.of(1))
        .create();

    // when
    final var jobBatch =
        ENGINE.jobs().withType(jobType).withMaxJobsToActivate(1).activate().getValue();
    final var jobKey = jobBatch.getJobKeys().getFirst();
    final var job = jobBatch.getJobs().getFirst();
    final var variables = job.getVariables();
    ENGINE.job().withKey(jobKey).withVariables(variables).complete();

    // then
    assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_COMPLETED)
                .filterRootScope()
                .limitToProcessInstanceCompleted())
        .extracting(Record::getIntent)
        .containsExactly(ProcessInstanceIntent.ELEMENT_COMPLETED);
  }
```

### Current behavior

The MI-body is not completed when all the children are completed. As a result the process instance is stuck.

A process instance modification can be used to recover the process. However, this awkward as it's not possible in Operate to move the "token" from the MI-body. I tried it by calling the API directly, which did work.

### Expected behavior

I'm not sure yet. One thing is for sure, the process instance should not get stuck.

### Environment

SaaS & SM

### Version

Zeebe versions:
- 8.2.31+
- 8.3.15+
- 8.4.11+
- 8.5.7+

### Rootcause

This check that was introduced relatively recent:
https://github.com/camunda/camunda/blob/0299fce6af9c784bc4c9751e72ad004b0920a8ca/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/MultiInstanceBodyProcessor.java#L245-L249

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

https://jira.camunda.com/browse/SUPPORT-27059
https://camunda.slack.com/archives/C08NC7BLJ2J/p1746706922808549

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

In our `MultiInstanceBodyProcessor` we evaluate the input collection of the MI body multiple times. This goes against[ our documentation ](https://docs.camunda.io/docs/next/components/modeler/bpmn/multi-instance/#defining-the-collection-to-iterate-over)and introduces bugs like the one closed by this PR.

> A multi-instance activity must have an inputCollection expression that defines the collection to iterate over (e.g. = items). Usually, it [accesses a variable](https://docs.camunda.io/docs/next/components/modeler/feel/language-guide/feel-variables/#access-variable) of the process instance that holds the collection. **The expression is evaluated on activating the multi-instance body**. It must result in an array of any type (e.g. ["item-1", "item-2"]).

With this PR we get rid of the multiple expression evaluations. Instead, we evaluate once on activation and store the result in a new `DbMultiInstanceState`. This result is fetched everytime we need to access the input collection during processing.

⚠️ For backwards compatibility I made it so that when input collection cannot be found, it will evaluate the expression regardless. If there's running instances where the MI Body is already activated the input collection will not be available in state!

[This comment](https://github.com/camunda/camunda/issues/31837#issuecomment-3011966880) describes the new flow best. It shows the way the log is now, where the new `MultiInstance.INPUT_COLLECTION_EVALUATED` event is written, as well as where the state gets cleaned up in the ProcessInstance Completed/Terminated applier.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #31837

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@deepthidevaki It auto-requested your review. Probably due to changes in the `TypedEventRegistry` I personally don't see the need for it 😅

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementCompletedApplier.java [hunk 1]
```diff
@@ -53,6 +57,10 @@ public void applyState(final long key, final ProcessInstanceRecord value) {
 
     bufferedStartMessageEventStateApplier.removeMessageLock(value);
 
+    if (value.getBpmnElementType() == BpmnElementType.MULTI_INSTANCE_BODY) {
+      multiInstanceState.deleteInputCollection(key);
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementCompletedApplier.java:61]: ℹ️ As deleting is backwards compatible (`deleteIfExists()`) I don't see the need of adding a new event applier version.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementTerminatedApplier.java [hunk 2]
```diff
@@ -37,6 +41,10 @@ public void applyState(final long key, final ProcessInstanceRecord value) {
 
     bufferedStartMessageEventStateApplier.removeMessageLock(value);
 
+    if (value.getBpmnElementType() == BpmnElementType.MULTI_INSTANCE_BODY) {
+      multiInstanceState.deleteInputCollection(key);
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementTerminatedApplier.java:45]: ℹ️ As deleting is backwards compatible (`deleteIfExists()`) I don't see the need of adding a new event applier version.

File: zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/intent/MultiInstanceIntent.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+  }
+
+  @Override
+  public short value() {
+    return value;
+  }
+
+  @Override
+  public boolean isEvent() {
+    return this == INPUT_COLLECTION_EVALUATED;
```
Comment (koevskinikola) [inline zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/intent/MultiInstanceIntent.java]: 🤔 We can just return `true` for now. It would remove the need for evaluating `this`.

A counterargument to the above is that the current code is more resilient to future changes; i.e., it will remain correct in case we add a "command" intent.

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/multiinstance/MultiInstanceRecord.java [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+  public List<DirectBuffer> getInputCollectionBuffers() {
+    return inputCollectionProperty.stream().map(BinaryValue::getValue).collect(Collectors.toList());
+  }
+
+  @Override
+  public List<String> getInputCollection() {
+    return getInputCollectionBuffers().stream().map(MsgPackConverter::convertToJson).toList();
+  }
+
+  public MultiInstanceRecord setInputCollection(final List<DirectBuffer> inputCollection) {
```
Comment (koevskinikola) [inline zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/multiinstance/MultiInstanceRecord.java:41]: 🙃 Might be good to rename this to `setInputCollectionBuffer` for clarity. 

🤔 I wonder if it makes sense to have a second method that accepts a `List<String>` as the `inputCollection` for future usage of this record.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/multiinstance/PersistedInputCollection.java [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+    declareProperty(inputCollectionProperty);
+  }
+
+  public List<DirectBuffer> getInputCollection() {
+    return inputCollectionProperty.stream()
+        .map(element -> BufferUtil.cloneBuffer(element.getValue()))
+        .toList();
+  }
+
+  public PersistedInputCollection setInputCollection(final List<DirectBuffer> inputCollection) {
```
Comment (koevskinikola) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/multiinstance/PersistedInputCollection.java:34]: 🙃 Same as my comment for the related record, might be clearer to rename this to `setInputCollectionBuffer`.

File: zeebe/test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java [hunk 6]
```diff
@@ -122,7 +123,9 @@ public class CompactRecordLogger {
           entry("ROLE", "RL"),
           entry("GROUP", "GR"),
           entry("MAPPING", "MAP"),
-          entry("ASYNC_REQUEST", "ASYNC"));
+          entry("ASYNC_REQUEST", "ASYNC"),
+          entry("MULTI_INSTANCE", "MI"),
+          entry("INPUT_COLLECTION_EVALUATED", "IN_COL_EVAL"));
```
Comment (koevskinikola) [inline zeebe/test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java:128]: 🙃 I wonder if `IN_COL_EVAL` would be clear enough for a new engineer that sees this shorthand for the first time. Do you think `MI_INPUT_EVAL` would be clearer and still correct?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/multiinstance/DbMultiInstanceState.java [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+  @Override
+  public Optional<List<DirectBuffer>> getInputCollection(final long multiInstanceKey) {
+    this.multiInstanceKey.wrapLong(multiInstanceKey);
+    final var persistedInputCollection = inputCollectionColumnFamily.get(this.multiInstanceKey);
+
+    if (persistedInputCollection == null) {
+      return Optional.empty();
+    }
+
+    return Optional.of(persistedInputCollection.getInputCollection());
```
Comment (koevskinikola) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/multiinstance/DbMultiInstanceState.java:61]: ❓ Should we make a copy of the input collection buffers here, instead of returning them directly?

I don't think we write to this data to cause issues, but better to be safe.

**Review by koevskinikola — APPROVED** [review]
Nice improvement @remcowesterhoud! 🚀 

I only have a question related to the safety of returning the input collection buffer directly. Please have a look before merging the PR.

Otherwise, I have several nitpicks below, but they don't impact the correctness of the PR.

👍 Nice commit breakdown, it helped with the review a lot. It's even future-proofed 😄 
> Famous last words: This should not introduce any bugs.

File: zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/intent/MultiInstanceIntent.java (hunk 3 above)
Comment (remcowesterhoud) [reply zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/intent/MultiInstanceIntent.java]: Yeah resiliency was my intent, but I'll change it. I don't really expect there's going to be another value added to this intent anyway.

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/multiinstance/MultiInstanceRecord.java (hunk 4 above)
Comment (remcowesterhoud) [reply zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/multiinstance/MultiInstanceRecord.java:41]: I'll leave this as-is. If there's a need for a setter with a `List<String>` in the future it can easily be added then 🤷

File: zeebe/test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java (hunk 6 above)
Comment (remcowesterhoud) [reply zeebe/test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java:128]: The `MI` already gets logged with is as it's the `ValueType`. So it'll become `MI IN_COL_EVAL`. I also want to keep the `COL` in there as it's a differentiator between input collection, input element and input variable.

I believe it'll be fine. If a new engineer really becomes confused about the abbreviation they can always look up what it means.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/multiinstance/DbMultiInstanceState.java (hunk 7 above)
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/multiinstance/DbMultiInstanceState.java:61]: This already happens 🙂 The `getInputCollection()` method returns a List of buffers. This list is created as:

```java
  public List<DirectBuffer> getInputCollection() {
    return inputCollectionProperty.stream()
        .map(element -> BufferUtil.cloneBuffer(element.getValue()))
        .toList();
  }
```

So we clone the value buffers and add them to a new list.
