### PR TITLE
Use new thread pool from ApiServicesExecutorProvider

### LINKED ISSUE #35076: REST API v2 response handling uses common ForkJoinPool
### 

### 

### 

### 

### Description

During our [performance investigation of the REST API](https://camunda.github.io/zeebe-chaos/2025/07/02/Follow-up-REST-API-performance#request-handling-execution-logic), a difference we have spotted with REST API and gRPC is the usage of the BrokerClient.

While we use on the gRPC side the [BrokerClient with retries](https://github.com/camunda/camunda/blob/main/zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/EndpointManager.java#L457) and direct response handling, on the REST API we use no retries and [handle the response async with the ForkJoinPool](https://github.com/camunda/camunda/blob/main/service/src/main/java/io/camunda/service/ApiServices.java#L55).

As our benchmark clusters have two CPUs, [meaning 1 Thread for the common ForkJoin thread pool](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html), we expected some contention on the thread.

### Steps to reproduce

https://camunda.github.io/zeebe-chaos/2025/07/02/Follow-up-REST-API-performance#request-handling-execution-logic

### Current behavior

This can lead to contention, as one thread is not able to handle all the responses in time.

### Expected behavior

We use a different thread pool, with more than one thread, ideally configurable.

### Environment

SM

### Version

- Component Version: 8.8

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

> I am creating this as draft. I might need to figure out how to run the same test setup as here https://camunda.github.io/zeebe-chaos/2025/07/02/Follow-up-REST-API-performance to compare results.

This PR adds ApiServicesExecutorProvider, a dedicated factory for the service executor. It creates a grow-on-demand ThreadPoolExecutor that is bounded relative to CPU cores, mirrors gRPC’s “cached” behavior (no queue, direct handoff), and remains configurable for load testing.

```java
maxPoolSize = Runtime.getRuntime().availableProcessors() * threadCountMultiplier
workQueue   = new SynchronousQueue<>()
rejection   = CallerRunsPolicy
coreSize    = configurable (often 0)
keepAlive   = configurable (seconds)
daemon      = true
name        = "api-service-thread-#"
allowCoreThreadTimeOut(true)
```

## Chosen strategy
**1) gRPC-like growth without unbounded explosion**
* Direct handoff (SynchronousQueue): no internal queue ⇒ each task either finds an idle thread or creates a new one—this mimics gRPC’s default executor behavior (cached pool).
* CPU-scaled cap: unlike gRPC’s unbounded pool, we cap with cores × threadCountMultiplier to prevent pathological thread growth (OOMs, context switching storms) under bursts.

**2) Predictable throttling instead of hard failures**
* CallerRunsPolicy: when at the cap, the submitting thread runs the task. This naturally slows producers (simple back-pressure) without throwing `RejectedExecutionException` or silently dropping work.

**3) Elasticity and resource efficiency**
* corePoolSize (often 0) + allowCoreThreadTimeOut(true): pool can shrink to zero when idle and regrow under load. Idle threads above core are retired after `keepAliveSeconds`.

**4) Operational clarity**
* Named, daemon threads make debugging thread dumps and shutdown behavior straightforward. Daemon status prevents stray executors from blocking JVM exit.

## Alternatives considered
**Unbounded cached pool (exact gRPC default)**
* Perfect fidelity to gRPC behavior
* Risk of unbounded threads under overload; hard to operate safely without additional guards.

**Fixed pool with bounded queue**
* Simple to reason about; stable thread count
* Queues introduce latency and head-of-line blocking; under spikes, you accumulate waiting tasks rather than scaling throughput.

## Configuration & tuning
* `corePoolSize`: default is `0`. Raise only if you want warm threads for steady traffic.
* `threadCountMultiplier`: default is `8`. primary knob. Example: on 4 cores, multiplier 8 ⇒ max 32 threads.
* `keepAliveSeconds`: default is `60` seconds. Shorten to retract faster after bursts.

Example (YAML):
```yaml
camunda:
  rest:
    api-executor:
      core-pool-size: 1
      thread-count-multiplier: 2
      keep-alive-seconds: 60
```

## Risks
**CPU-bound handlers with a large multiplier can oversubscribe the CPU.**
* Multiplier set to 8 might be performant with lower CPU count but can overwhelm CPU on higher CPU count.
* Needs to be validated with load tests (e.g. watch CPU% and context switches if possible)
**CallerRunsPolicy can push work onto request threads.**
* This is intentional throttling; might result in latency too early. 
* We should monitor request latency and adjust multiplier/cores accordingly.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #35076

### CODE REVIEW

**Comment by berkaycanbc** [comment]
@npepinpe I've updated configuration defaults to align with gRPC changes #36340 (and resolved conflicts 🤞). This PR is now ready for review.

**Comment by npepinpe** [comment]
Should I review now while tests are red?

**Comment by berkaycanbc** [comment]
Conflict resolution should be the reason, I'll put it into draft again.

**Comment by kpo-holi** [comment]
@berkaycanbc
I am working on the unified configuration project and added the api-executor properties to the unified configuration. I would like to add Javadoc for these properties, but I could not find it. Could you provide the Javadoc?

**Comment by berkaycanbc** [comment]
@kpo-holi added JavaDoc to `ApiExecutorConfiguration`

**Comment by berkaycanbc** [comment]
@npepinpe it is now ready for review

**Comment by kpo-holi** [comment]
@berkaycanbc 
Thanks for adding the JavaDoc.
With this change, some checks were also added for the properties corePoolSizeMultiplier and maxPoolSizeMultiplier. In one of my tests, I tried to set both properties using "camunda.rest.apiExecutor.corePoolSizeMultiplier=10" and "camunda.rest.apiExecutor.maxPoolSizeMultiplier=15" and got the  following message:

> Caused by: java.lang.IllegalArgumentException: corePoolSizeMultiplier (10) cannot be greater than current maxPoolSizeMultiplier (2)
	at io.camunda.zeebe.gateway.rest.config.GatewayRestConfiguration$ApiExecutorConfiguration.setCorePoolSizeMultiplier(GatewayRestConfiguration.java:132)
	
I was wondering how this can work, because setCorePoolSizeMultiplier is called before setMaxPoolSizeMultiplier by Spring. Did I miss something?

**Comment by berkaycanbc** [comment]
> I was wondering how this can work, because setCorePoolSizeMultiplier is called before setMaxPoolSizeMultiplier by Spring.

@kpo-holi right, Spring does not resolve this automatically. Removed the cross parameter validation. Thanks for checking!

File: service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+        new ThreadFactory() {
+          private final AtomicInteger counter = new AtomicInteger(0);
+
+          @Override
+          public Thread newThread(final Runnable r) {
+            final Thread t = new Thread(r, API_SERVICE_THREAD_NAME + counter.incrementAndGet());
+            t.setDaemon(true);
+            return t;
+          }
+        };
```
Comment (npepinpe) [inline service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java]: 🔧 You can make use of the default factories available:


```suggestion
    final ThreadFactory threadFactory = Thread.ofPlatform().name(API_SERVICE_THREAD_NAME, 0).daemon(true).factory();
```

File: service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+ */
+package io.camunda.service;
+
+import java.util.Objects;
+import java.util.concurrent.*;
+import java.util.concurrent.atomic.AtomicInteger;
+
+public final class ApiServicesExecutorProvider {
+
+  public static final String API_SERVICE_THREAD_NAME = "api-service-thread-";
```
Comment (npepinpe) [inline service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java]: 🔧 Unlikely to be necessary to be public

```suggestion
  private static final String API_SERVICE_THREAD_NAME = "api-service-thread-";
```

File: service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+        Objects.requireNonNull(
+            create(corePoolSizeMultiplier, maxPoolSizeMultiplier, keepAliveSeconds),
+            "REST API Executor Service must not be null");
+  }
+
+  public ApiServicesExecutorProvider(final ExecutorService executor) {
+    this.executor = Objects.requireNonNull(executor, "REST API Executor Service must not be null");
+  }
+
+  public static ApiServicesExecutorProvider of(final ExecutorService executor) {
```
Comment (npepinpe) [inline service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java]: 🔧 Does this factory method provide any value?

File: service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+          }
+        };
+
+    final ThreadPoolExecutor executor =
+        new ThreadPoolExecutor(
+            corePoolSize,
+            maxPoolSize,
+            keepAliveSeconds,
+            TimeUnit.SECONDS,
+            new SynchronousQueue<>(),
```
Comment (npepinpe) [inline service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java]: ❓ Are you sure this is the right behavior we want? This means, when all threads are busy, submission to the thread pool will simply block until a thread is available again.

I'm not saying this is bad, just wondering if this is what we really want - what happens here when all the threads are already busy? The caller ends up running the task? Does that end up burning all the web server threads? I mean, maybe that's fine? I think we need to evaluate what happens under high load here.

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/config/GatewayRestConfiguration.java [hunk 5]
```diff
@@ -42,4 +47,113 @@ public void setExpirationIdleMillis(final Long expirationIdleMillis) {
...
+   * </ul>
+   *
+   * <p><b>Constraints:</b>
+   *
+   * <ul>
+   *   <li>{@code corePoolSizeMultiplier} should be &gt;= 0 (0 means no core threads, only on-demand
+   *       threads).
+   *   <li>{@code maxPoolSizeMultiplier} should be &gt; 0
+   * </ul>
+   */
```
Comment (npepinpe) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/config/GatewayRestConfiguration.java]: 💭 I appreciate the Javadoc, but it's quite noisy. It describes things which are not controllable by the configuration (e.g. `CallerRunsPolicy` and `SynchronousQueue`), for example, which just adds confusion/noise to it.

🔧 Can we make this more succinct?

File: dist/src/main/java/io/camunda/application/commons/service/CamundaServicesConfiguration.java [hunk 6]
```diff
@@ -80,52 +81,72 @@ public class CamundaServicesConfiguration {
...
   }
 
   @Bean
   public DecisionDefinitionServices decisionDefinitionServices(
       final BrokerClient brokerClient,
       final SecurityContextProvider securityContextProvider,
       final DecisionDefinitionSearchClient decisionDefinitionSearchClient,
-      final DecisionRequirementsServices decisionRequirementsServices) {
+      final DecisionRequirementsServices decisionRequirementsServices,
+      final ApiServicesExecutorProvider executorProvider) {
```
Comment (npepinpe) [inline dist/src/main/java/io/camunda/application/commons/service/CamundaServicesConfiguration.java:112]: ❓ As this is used by every single bean in this class, do you think it might make sense to autowire it as an instance field, and pass it on? Instead of in every bean method?

**Review by npepinpe — APPROVED** [review]
Looks good generally, I had some questions and suggestions. The combo of `CallerRunsPolicy` and `SynchronousQueue` needs a load test, I'd like to understand how that translates from a user/client PoV.

So pre-approving, but before merging, please:
1. Address all comments
2. Run a load test, specifically testing using REST with an increasing number of requests to see how the server will handle when all its threads are busy.

**Comment by npepinpe** [comment]
@ChrisKujawa - we don't have an easy way to run a benchmark using only REST yet, right? I know you did that, but did you merge anything to help with that, or was it a one time manual effort?

**Comment by ChrisKujawa** [comment]
> @ChrisKujawa - we don't have an easy way to run a benchmark using only REST yet, right? I know you did that, but did you merge anything to help with that, or was it a one time manual effort?

@npepinpe 
Easy.

https://github.com/camunda/zeebe-benchmark-helm/blob/main/charts%2Fzeebe-benchmark%2Fvalues.yaml#L29 

Put the following in the github benchmark action as additional config
```
--set global.preferRest.enabled=true
```

_One time things don't exist for me 🤣_

File: service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java (hunk 3 above)
Comment (berkaycanbc) [reply service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java]: Supposed to get a little complex but didn't happen, so removed.

File: service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java (hunk 4 above)
Comment (berkaycanbc) [reply service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java]: > Are you sure this is the right behavior we want?

There is a trade-off with `SynchronousQueue` + `CallerRunsPolicy`. We avoid queue growth and enforce backpressure. The downside is that submitter threads may end up doing the work, which can reduce concurrency on the caller side (e.g., web threads). Well I am not sure whether it’s “right”. Depends on our goals (protect memory vs. protect request latency).

gRPC internally uses unbounded streams and has its own flow-control/backpressure mechanism. The idea here was to get closer to that behavior: we don’t build up a big queue, instead backpressure is applied once all threads are busy. In this setup that effectively means backpressure shows up at the web tier, since the request thread ends up executing the task if the pool is saturated.

> This means, when all threads are busy, submission to the thread pool will simply block until a thread is available again.

Not exactly. With `SynchronousQueue`, if the pool is at `maxPoolSize`, the handoff fails immediately and the rejection handler runs. With `CallerRunsPolicy`, the caller executes the task synchronously. So the caller is “blocked” because it’s doing the work itself—not because it’s waiting for a free pool thread.

> What happens here when all the threads are already busy?

The calling thread runs the task (synchronously) due to `CallerRunsPolicy`.

> Does that end up burning all the web server threads?

Potentially, yes. If submissions come from request threads, they can execute tasks, reducing the number of threads available to serve other requests. This provides backpressure but can cause latency spikes and timeouts under load.

Comment (berkaycanbc) [reply service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java]: @npepinpe 

**My idea got changed a bit**
Endpoints perform two separate operations:

1) Search through Elasticsearch documents (I/O-bound)
2) Perform changes in Zeebe (CPU-bound sometimes, I guess?)

I expect this setup will perform better for the second operation type. But now, I am thinking `CallerRunsPolicy` might not be the best for I/O bound operations as it will potentially cause latency spikes for new requests when `CallerRunsPolicy` is in effect. That’s why I’m reconsidering it.

Let's benchmark + compare the current and an alternative approach:
* Current: no queue + `CallerRunsPolicy`.
* Alternative: single bounded executor with a tiny queue (for micro-bursts) and fail-fast on saturation (immediate rejection without `CallerRunsPolicy`), mapping rejections to 503.

Comment (npepinpe) [reply service/src/main/java/io/camunda/service/ApiServicesExecutorProvider.java]: Zeebe can also be I/O bound, since it needs to replicate the command before processing it. So it's really a mixed workload. We should consider both sort of I/O bound? :thinking: 

The main difference is Zeebe has back pressure, so it's unlikely for requests to become very slow (unless configured by the user), as the default target is 200ms per command.

So in that sense, you're right, it will likely behave quite differently than ES there.

**Comment by berkaycanbc** [comment]
Triggered the benchmark here https://github.com/camunda/camunda/actions/runs/17299074179

Zeebe dashboard: https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&from=now-15m&to=now&timezone=browser&var-DS_PROMETHEUS=prometheus&var-cluster=$__all&var-namespace=bc-benchmark-rest-api-new-thread-pool&var-pod=$__all&var-partition=$__all&var-memory_state=committed

Core features dashboard: https://grafana.dev.zeebe.io/d/fel9lob8vajggd/core-features-overview?orgId=1&from=now-15m&to=now&timezone=browser&var-namespace=bc-benchmark-rest-api-new-thread-pool&var-region=$__all&var-container=$__all&var-uri=$__all&var-method=$__all&var-DS_PROMETHEUS=prometheus

**Comment by npepinpe** [comment]
Can you please link:
- The baseline comparison (so a benchmark using REST but without your change)
- The benchmark with the CallerRunsPolicy
- The benchmark with the new approach

**Comment by berkaycanbc** [comment]
Initially, average latency seems improved.
Screenshot 2025-08-28 at 18 03 34

However, CPU throttling doesn't look good still.

Screenshot 2025-08-28 at 18 04 40

**Comment by berkaycanbc** [comment]
@npepinpe 

> The baseline comparison (so a benchmark using REST but without your change)

I compare it to @ChrisKujawa's findings here https://camunda.github.io/zeebe-chaos/2025/07/02/Follow-up-REST-API-performance/#request-handling-execution-logic.

> The benchmark with the CallerRunsPolicy

It is here https://github.com/camunda/camunda/pull/36517#issuecomment-3233866847

> The benchmark with the new approach

I will implement it tomorrow and run a new benchmark 👍

**Comment by npepinpe** [comment]
Hm, I'd prefer we test with the closest baseline, as things might've changed since. But if you're confident they haven't, that's fine.

**Comment by berkaycanbc** [comment]
Ok, let's do that indeed. Started a new one from main with rest enabled.

https://github.com/camunda/camunda/actions/runs/17300242386

**Comment by berkaycanbc** [comment]
Some results are arrived. With the default setup, the REST performance seems to be improved only slightly.

**Without changes**

Screenshot 2025-08-29 at 12 21 25
Screenshot 2025-08-29 at 12 21 49


**With PR changes**
Screenshot 2025-08-29 at 12 22 43
Screenshot 2025-08-29 at 12 22 55


Changing parameters for the new thread setup might improve the performance but I would like to try the alternative approach first. Therefore, I will make changes in the executor implementation and create a new benchmark.

**Comment by berkaycanbc** [comment]
I've tested different max pool size multiplier and setting it as `8` already seems like the sweet spot.

`maxPoolSizeMultiplier=8`:
Screenshot 2025-09-02 at 17 15 36

`maxPoolSizeMultiplier=4`:
Screenshot 2025-09-02 at 17 16 04

`maxPoolSizeMultiplier=16`:
Screenshot 2025-09-02 at 17 16 33

FYI @npepinpe @ChrisKujawa

**Comment by berkaycanbc** [comment]
@kpo-holi another configuration variable `queueCapacity` is added, FYI.
