### PR TITLE
fix: Operate variable values are null when MIGRATED and CREATED

### LINKED ISSUE #27755: Operate variable values are null when CREATED/UPDATED and MIGRATED events are imported in the same batch
### Description (required on creation)

* When a variable is created/updated and then migrated in quick succession, then it's possible that the resulting value in the Operate variable index is `null` instead of the true value

### Steps to reproduce (required on creation)

1. Deploy a process in two versions
1. Start an instance and set a variable
1. Immediately migrate the instance from one version to the next

Note: this can be reproduced by using the Java client, e.g. creating instances in a loop.

### Current behavior (required on creation)

* Viewing the variable in the process instance details view, it is null

### Expected behavior (required on creation)

* The true value is displayed correctly

### Environment (required on creation)

* Affects Operate 8.7 and lower (backport down to 8.5)
* The new exporter does not have this problem, because it does not apply this kind of variable caching logic

### Root cause (required on prioritization)

* If the same variable is in one import batch, we collect the different events in a list (e.g. one CREATED, one MIGRATED event): https://github.com/camunda/camunda/blob/8.6.6/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ImportBulkProcessor.java#L268-L271
* We then iterate the events per variable (and scope) and create a map of distinct variable values: https://github.com/camunda/camunda/blob/8.6.6/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/VariableZeebeRecordProcessor.java#L56-L72
   * This map contains tuples of <the first intent; the latest value>
   * In the case of a CREATED and MIGRATED event in the same batch, this results in <CREATED; null value> (as Zeebe MIGRATED events do not contain the actual variable value)
* Subsequently we choose to override the value: https://github.com/camunda/camunda/blob/8.6.6/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/VariableZeebeRecordProcessor.java#L85-L91

### Solution ideas

* Do not update the cached variable value if the source is a MIGRATED event

### Additional context

* related bug: https://github.com/camunda/camunda/issues/26490

### Handover Dev to QA (required before manual testing)

- Resources:
  
- Versions to validate:
  
- Release version (in which version this feature will be released)
  

### Links

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/29623
- [ ] https://github.com/camunda/camunda/pull/29637
- [ ] https://github.com/camunda/camunda/pull/29638
- [ ] https://github.com/camunda/camunda/pull/29639
```

### PR DESCRIPTION
**Pull request by ghost**
fix: Operate variable values are null when MIGRATED and CREATED

Closes https://github.com/camunda/camunda/issues/27755

### CODE REVIEW

File: operate/importer-8_7/src/main/java/io/camunda/operate/zeebeimport/v8_7/processors/processors/VariableZeebeRecordProcessor.java [hunk 1]
```diff
@@ -53,15 +53,15 @@ public void processVariableRecords(
       final var scopedVariables = variableRecords.getValue();
 
       for (final var scopedVariable : scopedVariables) {
+        if (!shouldProcessVariableRecord(scopedVariable)) {
+          continue;
```
Comment (sdorokhova) [inline operate/importer-8_7/src/main/java/io/camunda/operate/zeebeimport/v8_7/processors/processors/VariableZeebeRecordProcessor.java:57]: But we will then also skip update of `processDefinitionKey` and `bpmnProcessId` fields, right?
https://github.com/camunda/camunda/pull/29639/files#diff-c84c359a0aa539ce1522a9e4ec7a7633ecea43e94c09d6075febe516c6bbacb1R78-R79

May be we should get rid of this grouping fully and just process all the records that come? This grouping was done at times for performance reasons, but I think we already lost the essential part of it when we decided [whether we should index or upsert](http://github.com/camunda/camunda/commit/5f772471570e92ec609d14fee9c018a780cf7729#diff-bc2c80941beb6328c56cec34ef9697549fea3fe0edcb0d6bdc9f92d03f70574bR84-R88).

**Review by sdorokhova — DISMISSED** [review]
@mihail-ca please check my comment. We can also discuss it, if you prefer.

**Comment by mihail-ca** [comment]
Hello @ThorbenLindhauer I had a call with Svetlana about this ticket yesterday, and she concluded the current implementation has more bugs, not only the one we are trying to fix as part of this issue. Svetlana suggested a solution, which I implemented and committed, however, there is test that fails now:

https://github.com/camunda/camunda/actions/runs/14179278105/job/39721425418?pr=29639
```
Error:  Failures: 
Error:  io.camunda.operate.zeebeimport.processors.VariableZeebeRecordProcessorIT.shouldNotOverrideVariableFields
Error:    Run 1: VariableZeebeRecordProcessorIT.shouldNotOverrideVariableFields:143 
```

But I am not sure if the test is wrong, and needs to be adjusted, or the solution needs another fix. I investigated this today, but also asked Svetlana about this, however she seems to be unavailable with sickness. Since I am not 100% confident the current implementation is correct, I will not able to merge this today. 

I will hand this over to you, since I am FTO for the rest of the week.

Thank you

**Comment by mihail-ca** [comment]
@ThorbenLindhauer the current PR is the solution suggested by Svetlana, thank you.

File: operate/qa/integration-tests/src/test/java/io/camunda/operate/zeebeimport/processors/VariableZeebeRecordProcessorIT.java [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+import org.springframework.beans.factory.BeanFactory;
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.boot.test.mock.mockito.MockBean;
+
+public class VariableZeebeRecordProcessorIT extends OperateSearchAbstractIT {
+
+  @Autowired private VariableTemplate variableTemplate;
+  @Autowired private VariableZeebeRecordProcessor variableZeebeRecordProcessor;
+  @Autowired private BeanFactory beanFactory;
+  @MockBean private PartitionHolder partitionHolder;
```
Comment (kristinkomschow) [inline operate/qa/integration-tests/src/test/java/io/camunda/operate/zeebeimport/processors/VariableZeebeRecordProcessorIT.java:43]: Consider using `org.springframework.test.context.bean.override.mockito.MockitoBean` here instead since MockBean is deprecated.

**Review by kristinkomschow — APPROVED** [review]
Small comment in the code.
The rest LGTM
