### PR TITLE
Job Yield Processor is implemented to be used for Job Push fallback

### LINKED ISSUE #12085: Job Yield Processor is implemented to be used for Job Push fallback
## Description
A job pushed to the `JobStreamer` API may fail to be handed over to the client due to client failure.

## AC
* A new `JobIntent.YIELD` intent is added.
* A new `JobYield` processor is added. The processor will perform logic similar to the `JobFailProcessor`, i.e. make a job `ACTIVATABLE` again.

## Additional context
* The implementation of this issue should then be used in the job push `ErrorHandler` implementation.

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description
A job pushed to the JobStreamer API may fail while sending it over to the client due to client failure. This should be handled in a way that we should make job available for long polling (make activatable) again.

**First Commit**

* BpmnJobActivationBehavior is refactored to have a method for appending long polling as a side effect
* New JobIntent "YIELD" is created
* JobIntent.YIELD is handled in JobYieldProcessor
* JobYieldProcessor is registered in JobEventProcessors
* New JobIntent "YIELDED" is created
* JobIntent.YIELDED is handled in JobYieldedApplier
* JobYieldedApplier is registered in EventAppliers
* "yield()" method is added to DbJobState to make job ACTIVATABLE in the state

**Second Commit**
* "yield()" method is added to JobClient for testing
* JobYieldProcessor tests are added to YieldJobTest

**Note**: the duplication of job command preconditions will be refactored in a separate PR.

## Related issues

closes #12085 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+import io.camunda.zeebe.engine.state.immutable.ProcessingState;
+import io.camunda.zeebe.protocol.impl.record.value.job.JobRecord;
+import io.camunda.zeebe.protocol.record.RejectionType;
+import io.camunda.zeebe.protocol.record.intent.JobIntent;
+import io.camunda.zeebe.stream.api.records.TypedRecord;
+
+public final class JobYieldProcessor implements TypedRecordProcessor<JobRecord> {
+
+  public static final String NOT_ACTIVATED_JOB_MESSAGE =
+      "Expected to time out activated job with key '%d', but %s";
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java:27]: :x: Since we're yielding a job back to the engine, I guess the verb in the error message should be "yield" instead of "time out"

```suggestion
      "Expected to yield activated job with key '%d', but %s";
```

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+    stateWriter = writers.state();
+    rejectionWriter = writers.rejection();
+  }
+
+  @Override
+  public void processRecord(final TypedRecord<JobRecord> record) {
+    final long key = record.getKey();
+    final JobState.State state = jobState.getState(key);
+    if (state == State.ACTIVATED) {
+      final JobRecord yieldedJob = jobState.getJob(key);
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java:46]: :x: Wouldn't it be easier to get the `JobRecord` from the command, i.e. `TypedRecord`. That way we can avoid accessing the `jobState` again, optimizing the performance a bit.

```suggestion
      final JobRecord yieldedJob = record.getValue());
```

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+
+      stateWriter.appendFollowUpEvent(key, JobIntent.YIELDED, yieldedJob);
+      jobActivationBehavior.notifyJobAvailable(yieldedJob);
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java:49]: :wrench: I wonder if we should add a code comment here that the job notification is done through a side-effect, as it might not be clear with the method name, i.e. it might seem that we do it immediately.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+          textState = "it is marked as failed";
+          break;
+        default:
+          textState = "no such job was found";
+          break;
+      }
+
+      rejectionWriter.appendRejection(
+          record,
+          RejectionType.NOT_FOUND,
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java:67]: :x: The `RejectionType.INVALID_STATE` fits better here since we only reject the `YIELD` command when the job is not in the `ACTIVATED` state.. Alternatively, we can change the `RejectionType` in the `switch` statement depending on the `textState` value.

```suggestion
          RejectionType.INVALID_STATE,
```

File: engine/src/test/java/io/camunda/zeebe/engine/processing/job/YieldJobTest.java [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+    final JobRecordValue job = batchRecord.getValue().getJobs().get(0);
+    final long jobKey = batchRecord.getValue().getJobKeys().get(0);
+
+    // when
+    final Record<JobRecordValue> yieldRecord =
+        ENGINE.job().withKey(jobKey).ofInstance(job.getProcessInstanceKey()).yield();
+
+    // then
+    Assertions.assertThat(yieldRecord).hasRecordType(RecordType.EVENT).hasIntent(JobIntent.YIELDED);
+    Assertions.assertThat(yieldRecord.getValue()).hasWorker(job.getWorker()).hasType(job.getType());
```
Comment (koevskinikola) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/job/YieldJobTest.java:54]: :+1: Nice work with the worker and job type assertion. I was initially confused when I saw this, but it makes sense to have the `worker` that was **supposed to receive** the job for audit reasons.

**Review by koevskinikola — CHANGES_REQUESTED** [review]
Looks good @berkaycanbc. I left some review hints below.

:upside_down_face: You can also merge the last two test commits, and change the commit message to `test(engine):...` instead of `feat(engine):...` since those changes are related to tests in the engine.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/job/YieldJobTest.java (hunk 5 above)
Comment (koevskinikola) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/job/YieldJobTest.java:54]: :wrench: It would be nice to assert the error message here as well.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java (hunk 3 above)
Comment (berkaycanbc) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java:49]: @koevskinikola I think, this is one will become invalid with the changes in JobStreamer, right?

Comment (koevskinikola) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobYieldProcessor.java:49]: @berkaycanbc it's still valid. The JobStreamer API will be changed so that we don't need to pass the `ErrorHandler` with every job push, but only pass a single instance when the `JobStreamer` is instantiated. 

In the `ErrorHandler` implementation, we will still be using the job `YIELD` command, and as we confirmed in the meeting yesterday if a job is yielded, it falls back under the long polling mechanism. So we still need to do a notification.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/job/YieldJobTest.java (hunk 5 above)
Comment (koevskinikola) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/job/YieldJobTest.java:54]: Yes, correct. Sorry about that, I should've commented in the test below.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnJobActivationBehavior.java
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnJobActivationBehavior.java:1]: Catched up with @koevskinikola that we will create another PR for the new ErrorHandler implementation.

**Review by koevskinikola — APPROVED** [review]
Looks great! :rocket: 

bors merge
