### PR TITLE
fix: Eliminate need for top_hits limit when fetching grouped processes

### LINKED ISSUE #41058: Operate UI only loads process instances from the first 100 processDefinitionKeys for a model
### 

### 

  

### 

### 

### Description

In Operate, the UI builds its process-instance list by first calling the internal endpoint:
```
POST /processes/grouped
```
This endpoint uses an Elasticsearch top_hits aggregation with size = 100, which means Operate can retrieve a maximum of 100 versions for any given `processDefinitionId`.

The UI then passes only these 100 `processDefinitionKeys` to the internal process-instance search endpoint (`/api/process-instances`).

If a process model has more than 100 deployed versions, all versions beyond the first 100 are silently dropped.
As a result, the UI misses process instances (including those with incidents), causing a discrepancy between:
- Operate UI (under-counting instances)
- V1 Process Instance Search API (returns the correct full set)

This results in customers seeing fewer active/incident instances in the UI than what the public API reports.

### Steps to reproduce

1. Deploy a BPMN process enough times to create >100 versions (e.g., 120+).
2. Ensure some process instances exist—and potentially have incidents—in versions above the 100th version (e.g., version 110, 115, 120).
3. Open Operate UI → Process Instances → filter for incidents (or any filter requiring instance retrieval).
4. Observe the count shown in the UI.
5. Call the public V1 search endpoint:
```curl
POST /v1/process-instances/search
{
  "filter": { 
     "state": "ACTIVE",    
     "incident": true, 
     "bpmnProcessId": "<your-process-id>" 
  }
}
```
6. Compare the total totalCount returned by the API with the UI count.

### Current behavior

- Operate UI only retrieves process instances for the first 100 processDefinitionKeys of a given bpmnProcessId.
- Any instances belonging to versions above 100 are never included in the UI’s results.
- This leads to:
   - Incorrect incident counts
   - Incomplete search results
   - Mismatch between UI and V1 API

### Expected behavior

- Operate UI should retrieve all processDefinitionKeys for a process model, without an arbitrary 100-version limit.
- UI counts and UI results should match the V1 API’s full, accurate results.

### Workaround

Use the V1 Process Instance Search API directly:
```curl
POST /v1/process-instances/search
```
This endpoint does not depend on the top_hits aggregation and returns all process instances regardless of version count.

### Environment

SaaS

### Version

- Component Version: 8.7.15

### Rootcause

- The /processes/grouped endpoint uses an Elasticsearch aggregation with:

```curl
"top_hits": { "size": 100 }
```

- This limits Operate to retrieving only the first 100 versions of a process.
- Operate UI depends on this grouped endpoint to assemble the list of definition keys for subsequent queries.
- Versions above 100 are never fetched, so their process instances are not included.

### Solution ideas

Option 1. Increase or remove the top_hits size limit
   - E.g., increase from 100 → 500 or make it configurable.
   - Pros: minimal UI/API changes.
   - Cons: increases ES memory usage and response size.

Option 2. Switch UI to use V1 or V2 search APIs instead of internal grouped + process-instances endpoints
   - Would eliminate grouping/version limitations entirely.
   - Aligns UI and API behaviour.
   - More work, but more correct long-term.

I would go with Option 1 for now to alleviate the customer’s immediate pain point, but Option 2 would ultimately be preferred as it aligns with the Operate UI V2 API Migration project.

### Links

[SUPPORT LINK](https://jira.camunda.com/browse/SUPPORT-29929)

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by georgios-goulos**
## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes https://github.com/camunda/camunda/issues/41058

### CODE REVIEW

File: operate/qa/integration-tests/src/test/java/io/camunda/operate/it/store/ProcessStoreGroupedProcessesIT.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+import io.camunda.webapps.schema.descriptors.index.ProcessIndex;
+import io.camunda.webapps.schema.entities.ProcessEntity;
+import io.camunda.zeebe.protocol.record.value.TenantOwned;
+import java.util.List;
+import java.util.Map;
+import java.util.Set;
+import org.junit.jupiter.api.Test;
+import org.springframework.beans.factory.annotation.Autowired;
+
+public class ProcessStoreGroupedProcessesIT extends OperateSearchAbstractIT {
```
Comment (georgios-goulos) [inline operate/qa/integration-tests/src/test/java/io/camunda/operate/it/store/ProcessStoreGroupedProcessesIT.java:23]: It looks like in operate/qa/integration-tests/src/test/java/io/camunda/operate/it/store/ProcessStoreIT.java we use `runAdditionalBeforeAllSetup` for the test data setup. I didn't want to create this many versions and muddle the data for the existing class so I decided to create this class that focuses specifically on the fix.

File: operate/qa/integration-tests/src/test/java/io/camunda/operate/it/store/ProcessStoreIT.java [hunk 2]
```diff
@@ -194,6 +223,75 @@ public void testGetProcessesGrouped() {
         .isEqualTo(1);
   }
 
+  @Test
```
Comment (georgios-goulos) [inline operate/qa/integration-tests/src/test/java/io/camunda/operate/it/store/ProcessStoreIT.java:225]: Unrelated to the fix but addresses test gaps

File: operate/qa/integration-tests/src/test/java/io/camunda/operate/it/store/ProcessStoreGroupedProcessesIT.java [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+    // then
+    final List<ProcessEntity> versions = results.get(processKey);
+    assertThat(versions).hasSize(TOTAL_VERSIONS);
+    assertThat(versions.getFirst().getVersion()).isEqualTo(TOTAL_VERSIONS);
+    assertThat(versions.getLast().getVersion()).isEqualTo(1);
+
+    final Set<Integer> returnedVersions =
+        versions.stream()
+            .map(ProcessEntity::getVersion)
+            .collect(java.util.stream.Collectors.toSet());
```
Comment (RomanJRW) [inline operate/qa/integration-tests/src/test/java/io/camunda/operate/it/store/ProcessStoreGroupedProcessesIT.java]: 🔧 use import

File: operate/qa/integration-tests/src/test/java/io/camunda/operate/it/store/ProcessStoreGroupedProcessesIT.java [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+    // given
+    final ProcessStore.ProcessKey processKey =
+        new ProcessStore.ProcessKey(BPMN_PROCESS_ID, TenantOwned.DEFAULT_TENANT_IDENTIFIER);
+
+    // when
+    final Map<ProcessStore.ProcessKey, List<ProcessEntity>> results =
+        processStore.getProcessesGrouped(
+            TenantOwned.DEFAULT_TENANT_IDENTIFIER, Set.of(BPMN_PROCESS_ID));
+
+    // then
```
Comment (RomanJRW) [inline operate/qa/integration-tests/src/test/java/io/camunda/operate/it/store/ProcessStoreGroupedProcessesIT.java:61]: 🔧 You can simplify this whole `when` clause by leveraging a bit more assertJ, for example:

```
final List<ProcessEntity> processEntities = results.get(processKey);
    assertThat(processEntities)
        .extracting(ProcessEntity::getVersion)
        .hasSize(TOTAL_VERSIONS)
        .startsWith(TOTAL_VERSIONS)
        .endsWith(1)
        .isSortedAccordingTo((v1, v2) -> Integer.compare(v2, v1));
```

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java [hunk 5]
```diff
@@ -196,98 +198,71 @@ public String getDiagramByKey(final Long processDefinitionKey) {
...
-      groupsEs8.sterms().buckets().array().stream()
+      if (bpmnProcessIds.isEmpty()) {
+        return new HashMap<>();
+      }
+
+      final var docsQuery =
+          tenantHelper.makeQueryTenantAware(buildQueryEs8(tenantId, new HashSet<>(bpmnProcessIds)));
+
+      final var searchRequestBuilder =
+          new co.elastic.clients.elasticsearch.core.SearchRequest.Builder()
```
Comment (RomanJRW) [inline operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: 🔧 use import

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java [hunk 6]
```diff
@@ -196,98 +198,71 @@ public String getDiagramByKey(final Long processDefinitionKey) {
...
+    final List<String> sourceFields =
+        Arrays.asList(
+            ProcessIndex.ID,
+            ProcessIndex.NAME,
+            ProcessIndex.VERSION,
+            ProcessIndex.VERSION_TAG,
+            ProcessIndex.BPMN_PROCESS_ID,
+            ProcessIndex.TENANT_ID);
 
     final Aggregation groupsAgg =
```
Comment (RomanJRW) [inline operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: 🔧 I find this class a little hard to understand and I think it can be cleaned a bit with better naming. Can this be something like `processIdAgg` - wdyt?

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java [hunk 7]
```diff
@@ -196,98 +198,71 @@ public String getDiagramByKey(final Long processDefinitionKey) {
...
                       .query(tenantAwareQuery)
-                      .aggregations(tenantsGroupsAggName, tenantsAgg)
+                      .aggregations(groupsAggName, groupsAgg)
                       .size(0),
               Void.class);
 
-      final var groupsEs8 = res.aggregations().get(tenantsGroupsAggName);
+      final List<String> bpmnProcessIds =
+          aggResponse.aggregations().get(groupsAggName).sterms().buckets().array().stream()
+              .map(b -> b.key().stringValue())
```
Comment (RomanJRW) [inline operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: 🔧 not a big deal, but you could use a method reference in the stream here

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java [hunk 8]
```diff
@@ -196,98 +198,71 @@ public String getDiagramByKey(final Long processDefinitionKey) {
...
               s ->
                   s.index(processIndex.getAlias())
                       .query(tenantAwareQuery)
-                      .aggregations(tenantsGroupsAggName, tenantsAgg)
+                      .aggregations(groupsAggName, groupsAgg)
                       .size(0),
               Void.class);
 
-      final var groupsEs8 = res.aggregations().get(tenantsGroupsAggName);
+      final List<String> bpmnProcessIds =
```
Comment (RomanJRW) [inline operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: ❓ It might just be that I am reviewing this crazy late at night but I am a little confused as to why we even need this aggregation in the first place if we have been passed already a list of allowed IDs. I have a feeling I am not seeing the clear intent of this method though so might be overlooking something.

Would you mind explaining the method intent clearly to help me ensure that my review doesn't overlook something? It could also indicate that some code comments here might be useful to make it clear why we need to do the various aggs

**Review by RomanJRW — CHANGES_REQUESTED** [review]
Thanks for taking this. Consider this just a short review but would like to review again with a fresh brain and after we align on the intention of the method here

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java (hunk 5 above)
Comment (georgios-goulos) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: I noticed other parts of the code in this class were using `co.elastic.clients.elasticsearch.core.SearchRequest`. I thought I'd keep it for that reason but I am happy to change it across everything.

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java (hunk 7 above)
Comment (georgios-goulos) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: Do you mean that we should replace

```java
.map(b -> b.key().stringValue())
```

with 

```java
.map(StringTermsBucket::key)
.map(FieldValue::stringValue)
```

?

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java (hunk 8 above)
Comment (georgios-goulos) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: I do not have any experience with aggregations, so this refactoring was done with heavy use of copilot that recommended the 2 aggregations in this implementation, which I went with as I thought my lack of experience made me miss something. I believe that you pointed out a valid flaw in the implementation so I will make the necessary adjustments.

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java [hunk 9]
```diff
@@ -196,98 +198,71 @@ public String getDiagramByKey(final Long processDefinitionKey) {
   @Override
   public Map<ProcessKey, List<ProcessEntity>> getProcessesGrouped(
```
Comment (RomanJRW) [inline operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java:200]: @copilot before the changes in this PR, explain what the parameters represented, and what the method did step-by-step. Then do the same for the method after the changes in this PR and why the change is necessary

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java (hunk 8 above)
Comment (georgios-goulos) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: > Would you mind explaining the method intent clearly to help me ensure that my review doesn't overlook something? It could also indicate that some code comments here might be useful to make it clear why we need to do the various aggs

This method's intent is to return all process definitions that the user is authorized to access, grouped by `bpmnProcessId` and `tenantId`, with process definition versions sorted in descending order within each group.

I believe I have a better version of this that does not require aggregations. I will push a commit in a bit. This will also contain fixes for the rest of your feedback.

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java (hunk 6 above)
Comment (georgios-goulos) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: If I remove the aggregations the code is simplified and there is no need for `groupsAgg`

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java (hunk 8 above)
Comment (georgios-goulos) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: @RomanJRW In commit [28dc51b046bff9a713c2903a62f64e719a133890](https://github.com/camunda/camunda/pull/43503/changes/28dc51b046bff9a713c2903a62f64e719a133890) I pushed an update that simply uses a scroll search query that filters by tenant ID (using the input param`tenantId` and security-applied tenant IDs) and `allowedBPMNProcessIds`. This query also orders the process definitions by version. The response stream go through all hits and groups them by `ProcessKey` (bpmnProcessId - tenantId key). This implementation makes sense to me but please do let me know if you think it is good enough. Furthermore, I have currently only done the update for ES. If this is a reasonable solution I can update the OS implementation too.

Comment (georgios-goulos) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: For transparency: this is a fix for a bug that a customer is waiting for so I would like us to merge this before the next patch releases.

Comment (georgios-goulos) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: In [99764189a9fad0055bd1b0a7e8f4408cab8bffa4](https://github.com/camunda/camunda/pull/43503/changes/99764189a9fad0055bd1b0a7e8f4408cab8bffa4) I tried to follow the same steps for Opensearch.

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java (hunk 9 above)
Comment (RomanJRW) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java:200]: How copilot handled this comment was really dumb 🙃

**Review by RomanJRW — APPROVED** [review]
Nice! Much simpler now and this LGTM ✅

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java (hunk 8 above)
Comment (RomanJRW) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java]: Thanks for the context and details on the change, this was very helpful in being able to review 👍

**Comment by tmetzke** [comment]
This is great, thanks for sharing, @georgios-goulos!

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java [hunk 10]
```diff
@@ -196,98 +199,43 @@ public String getDiagramByKey(final Long processDefinitionKey) {
...
+                        f ->
+                            f.includes(
+                                Arrays.asList(
+                                    ProcessIndex.ID,
+                                    ProcessIndex.NAME,
+                                    ProcessIndex.VERSION,
+                                    ProcessIndex.VERSION_TAG,
+                                    ProcessIndex.BPMN_PROCESS_ID,
+                                    ProcessIndex.TENANT_ID))))
+            .sort(so -> so.field(fs -> fs.field(ProcessIndex.VERSION).order(SortOrder.Desc)));
```
Comment (EuroLew) [inline operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java:222]: 🔧 there's a helper to crete a sort order `public static SortOptions sortOrder(
      final String field, final co.elastic.clients.elasticsearch._types.SortOrder sortOrder)`

**Review by EuroLew — COMMENTED** [review]
much simpler nice one

File: operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java (hunk 10 above)
Comment (georgios-goulos) [reply operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchProcessStore.java:222]: Thanks for this! 👍  I already added the PR to the merge queue. If it passes, I will raise a new low-risk PR with this tiny change. If it fails I will push this in a new commit and try to merge again.
