### PR TITLE
Use kryo for backwards compatibility

### LINKED ISSUE #11989: Recent changes cause issues on rolling updates
**Describe the bug**

I know that we not officially support rolling updates, mostly because of https://github.com/camunda/zeebe/issues/7449

But there were also recent some changes it seems, which causes issues with the `ExporterStateDecoder`. Right now the issues have been detected on Clusters which uses the SNAPSHOT version. I understand that is not supported and might have issues due to incompatibilities, but I'm wondering whether this is not also an issue on the next version.

If we release the version, and a user does a normal update (e.g. helm update) as of now I feel they might run into this, since on k8 you normally do a rolling update.

**Error groups:**

* https://console.cloud.google.com/errors/detail/CNzmrcPlmbiEPQ;service=zeebe;version=SNAPSHOT;time=P7D?project=camunda-cloud-240911
* https://console.cloud.google.com/errors/detail/CNP86-m_5vn5Ew;service=zeebe;version=SNAPSHOT;time=P7D?project=camunda-cloud-240911

_My current assumption would be that it can be resolved by restarting all PODS._ Or is this an issue on the state?

**To Reproduce**

Starting with an old version, run with some load, upgrade to current SNAPSHOT.

**Expected behavior**
No issues during the upgrade.

**Log/Stacktrace**

[LOG](https://console.cloud.google.com/logs/query;query=error_group%2528%22CNzmrcPlmbiEPQ%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.cluster_name%3D%22integration-worker-1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%22a6c25d58-8fad-4479-bd96-f1ec44f865ec-zeebe%22%0Aresource.labels.location%3D%22europe-west1%22;timeRange=2023-03-10T07:16:58.477Z%2F2023-03-10T08:16:58.477Z;cursorTimestamp=2023-03-10T07:44:38.303108654Z?project=camunda-cloud-240911)

<details><summary>
LOG
</summary>
 <p>

```
java.lang.IndexOutOfBoundsException: index=78 capacity=78
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:2212) ~[agrona-1.17.1.jar:1.17.1]
	at org.agrona.concurrent.UnsafeBuffer.getByte(UnsafeBuffer.java:947) ~[agrona-1.17.1.jar:1.17.1]
	at io.camunda.zeebe.broker.protocol.ExporterStateDecoder$StateDecoder.wrap(ExporterStateDecoder.java:179) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.protocol.ExporterStateDecoder.state(ExporterStateDecoder.java:148) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterStateDistributeMessage.wrap(ExporterStateDistributeMessage.java:84) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterStateDistributionService.storeExporterState(ExporterStateDistributionService.java:46) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:286) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:275) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$6(NettyMessagingService.java:268) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

</p>
</details>

[Similar issue here](https://console.cloud.google.com/logs/query;query=error_group%2528%22CNP86-m_5vn5Ew%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22integration-worker-1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.namespace_name%3D%22569ed5b9-9321-4fc8-94d3-06f0bed6d6d6-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22;timeRange=2023-03-09T10:36:03.535Z%2F2023-03-09T11:36:03.535Z;cursorTimestamp=2023-03-09T11:05:33.535591043Z?project=camunda-cloud-240911)

[This also caused issues on dev, ](https://camunda.slack.com/archives/C04CABJF6FP/p1678363913819779)

**Environment:**
- OS: 
- Zeebe Version: SNAPSHOT

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR reverts the removal of unnecessary Kryo copy/usage from the `InterPartitionCommandSender`, `InterPartitionCommandReceiver`, and `PartitionMessagingService`, as this causes errors during rolling update. While we should figure out a way to deal with this properly, it's not super urgent for now. 

However, for new features, we should try to avoid using Kryo in the first place.

## Related issues

closes #11989 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
The test is not ideal - essentially by adding an exporter to the rolling update test, we now also test the replication of the exporter state across versions, specifically in the one where we test that the snapshot is replicated (you can easily simulate the failure by removing the fix). To figure out what happened you then need to read the logs.

I don't have a good idea that wouldn't take a lot of time to have a smaller scoped test for this, unfortunately.

File: qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java [hunk 1]
```diff
@@ -330,6 +336,8 @@ private void configureBroker(final ZeebeBrokerNode<?> broker) {
         .withEnv("ZEEBE_BROKER_CLUSTER_MEMBERSHIP_PROBETIMEOUT", "1s")
         .withEnv("ZEEBE_BROKER_CLUSTER_MEMBERSHIP_FAILURETIMEOUT", "2s")
         .withEnv("ZEEBE_BROKER_CLUSTER_MEMBERSHIP_SUSPECTPROBES", "2")
+        // ensure we have an exporter present to test sharing exporter state across nodes
+        .withEnv("ZEEBE_BROKER_EXECUTIONMETRICSEXPORTERENABLED", "true")
```
Comment (Zelldon) [inline qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java:340]: :D That was it? Great :laughing:

File: qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java [hunk 2]
```diff
@@ -69,6 +71,10 @@ final class RollingUpdateTest {
           .withNetwork(network)
           .build();
 
+  @SuppressWarnings("unused")
+  @RegisterExtension
+  private final ContainerLogsDumper logsPrinter = new ContainerLogsDumper(cluster::getNodes);
```
Comment (Zelldon) [inline qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java:76]: :question: Do we want this always? Out of curiosity or was that because of debugging?

**Review by ChrisKujawa — APPROVED** [review]
Thanks @npepinpe :+1: 

I think it would be great if we could rerun the same test I did to reproduce https://github.com/camunda/zeebe/issues/11989

Benchmark [zell-update-test](https://grafana.dev.zeebe.io/d/NzsO1mUnk/zeebe-overview?orgId=1&from=1678438759809&to=1678443580493&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=zell-update-test&var-pod=All&var-partition=All) and [related errors ](https://console.cloud.google.com/errors;service=zeebe;version=zell-update-test;time=P7D;resolution=OPEN?project=zeebe-io)

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AtomixPartitionMessagingService.java [hunk 3]
```diff
@@ -39,37 +40,22 @@ public AtomixPartitionMessagingService(
...
-    }
-
-    final var serialized = new byte[payload.remaining()];
-    payload.mark();
-    payload.get(serialized);
-    payload.reset();
-
-    return serialized;
-  }
-
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AtomixPartitionMessagingService.java:72]: I guess this is because you removed the default implementation, which is why the changes a bit different :+1:

[the remark this answers is not in the document]
Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AtomixPartitionMessagingService.java:72]: I wanted to keep some things from the commit, but for now just revert the Kryo stuff specifically. I'd still like to encourage us to not use Kryo, esp. if we're using something else (e.g. SBE)

File: qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java (hunk 1 above)
Comment (npepinpe) [reply qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java:340]: It failed pretty reliably, since in the tests when we update a broker, we wait for it to rejoin and for its partitions to be healthy.

File: qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java (hunk 2 above)
Comment (npepinpe) [reply qa/update-tests/src/test/java/io/camunda/zeebe/test/RollingUpdateTest.java:76]: It's because if the test fails due to exporter state, and we don't print the logs on failure, it's very hard to diagnose the issue :smile:

**Comment by npepinpe** [comment]
One small note: you will now see errors again between this snapshot and the previous snapshot, of course :smile: But I think that's better than getting it when we release 8.2.

**Comment by npepinpe** [comment]
> One small note: you will now see errors again between this snapshot and the previous snapshot, of course smile But I think that's better than getting it when we release 8.2.

/cc @deepthidevaki as you're medic, so you might see these errors again a bit once it's merged

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors r-

I found a bug while testing the upgrade manually, but I can't tell if it's related. There was an NPE in the exporter state, so the communication worked fine (no deserialization errors), but still...let me double check.

**Comment by npepinpe** [comment]
Oh, lol, I'm an idiot. I tested with the version that had the regression, of course they will have errors :smile:

**Comment by npepinpe** [comment]
bors merge
