### PR TITLE
fix: remove hardcoded default tenant access

### LINKED ISSUE #29518: Access to <default> tenant is hardcoded for all users and mappings
**Describe the bug**

With the original Multi-tenancy implementation (with versions [8.3 - 8.7]), we had the following behavior:
- If MT is disabled, data is mapped to the `<default>` tenant.
- If MT is ~disabled~ enabled, the `<default>` tenant is ~created~ treated as any other tenant, i.e. users need to be granted access to it.

With the current re-architecture of Identity, access to the `<default>` tenant when MT is enabled is granted by default to all users and mappings (see code [here](https://github.com/camunda/camunda/blob/5df6e9f92ce85bf3f06ce33a853f1f5ab9e9693f/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java#L145-L147) and [here](https://github.com/camunda/camunda/blob/5df6e9f92ce85bf3f06ce33a853f1f5ab9e9693f/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java#L159-L161)). This access is hardcoded and can't be revoked.

**To Reproduce**

Execute the `MultiTenancyIT#shouldDenyDeployProcessWhenUnauthorizedForDefaultTenant()`test case.

ℹ The test class will be restored with https://github.com/camunda/camunda/issues/29233

**Expected behavior**

The `<default>` tenant should not be explicitly available when MT is enabled.

Be sure to re-enable the disabled tests in the `MultiTenancyOverIdentityIT`

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- Camunda Version: 
- Configuration:

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Remove hardcoded default tenant access.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #29518

### CODE REVIEW

**Comment by koevskinikola** [comment]
Hey @remcowesterhoud, let's give this bug another go :D

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/AuthorizationCheckBehaviorMultiTenancyTest.java [hunk 1]
```diff
@@ -299,26 +299,25 @@ void shouldGetDefaultAuthorizedTenantIdsIfUserKeyIsNotPresent() {
...
-        .containsOnly(TenantOwned.DEFAULT_TENANT_IDENTIFIER);
+    assertThat(authorizedTenantIds.getAuthorizedTenantIds()).isEmpty();
     assertThat(authorizedTenantIds.isAuthorizedForTenantId(TenantOwned.DEFAULT_TENANT_IDENTIFIER))
-        .isTrue();
+        .isFalse();
     assertThat(
             authorizedTenantIds.isAuthorizedForTenantIds(
                 List.of(TenantOwned.DEFAULT_TENANT_IDENTIFIER)))
-        .isTrue();
+        .isFalse();
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/AuthorizationCheckBehaviorMultiTenancyTest.java:320]: 🙃 I guess it can't hurt to have the assertions. But imo they're not really necessary anymore. Feel free to leave it though. In the end it's an extra security 🤷

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/MultiTenantJobOperationsTest.java [hunk 2]
```diff
@@ -0,0 +1,432 @@
...
+import java.time.Duration;
+import java.util.Collections;
+import java.util.UUID;
+import org.junit.Before;
+import org.junit.BeforeClass;
+import org.junit.ClassRule;
+import org.junit.Rule;
+import org.junit.Test;
+
+public class MultiTenantJobOperationsTest {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/MultiTenantJobOperationsTest.java:44]: 👍 I like this. Much more clear this way.

**Review by remcowesterhoud — APPROVED** [review]
I found some time to do it today anyway 🙂 I like the refactorings a lot. It's much clearer when tests fail and they are isolated in their own test class.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/AuthorizationCheckBehaviorMultiTenancyTest.java (hunk 1 above)
Comment (koevskinikola) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/authorization/AuthorizationCheckBehaviorMultiTenancyTest.java:320]: I would leave it as a guard, in case:
1. We miss this again and add logic that grants `<default>` tenant access by default again;
2. We decide to pass along an `AnonymousAuthorizedTenants` instance, where this method always returns `true`.
