### PR TITLE
Fix LGTM alerts

### LINKED ISSUE #5647: Fix warnings in LGTM
**Description**

Now there are some warnings in [LGTM](https://lgtm.com/projects/g/zeebe-io/zeebe/alerts/?mode=list). They should be fixed.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Fixes lgtm alerts

## Related issues

closes https://github.com/zeebe-io/zeebe/issues/5647

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: util/src/main/java/io/zeebe/util/sched/ActorThread.java [hunk 1]
```diff
@@ -173,7 +173,7 @@ public int getRunnerId() {
   }
 
   @Override
-  public void start() {
+  public synchronized void start() {
```
Comment (npepinpe) [inline util/src/main/java/io/zeebe/util/sched/ActorThread.java:176]: Can you elaborate why the `synchronized`?

**Review by npepinpe — CHANGES_REQUESTED** [review]

File: util/src/main/java/io/zeebe/util/sched/ActorThread.java (hunk 1 above)
Comment (Zelldon) [reply util/src/main/java/io/zeebe/util/sched/ActorThread.java:176]: https://lgtm.com/rules/5990064/

**Review by npepinpe — APPROVED** [review]
