### PR TITLE
fix: fixed batch operation resume behavior when paused/resumed while …

### LINKED ISSUE #32269: Fix batch operation RESUME when not fully started
When a batch operation is still in creation by the scheduler, it already can be paused. Then the scheduler does nothing for this batch operation. 

When the batch operation then is resumed, the BatchOperationResumeProcessor directly appends the EXECUTE command even though the batch operation is not even initialized. This then completes the batch operation without haven executed anything (for that partition).

### PR DESCRIPTION
**Pull request by stoerti**
## Description

This PR fixes an issue which can occur when a batch operation is paused & resumed while still in the init phase in the scheduler.

## Related issues

closes #32269

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/PersistedBatchOperation.java [hunk 1]
```diff
@@ -61,6 +61,16 @@ public PersistedBatchOperation wrap(final BatchOperationCreationRecord record) {
     return this;
   }
 
+  /**
+   * Returns true if the batch operation is initialized and ready for execution. A batch operation
+   * is considered initialized if it has any stored chunkKeys.
+   *
+   * @return true if the batch operation is initialized, false otherwise
+   */
+  public boolean isInitialized() {
```
Comment (p-wunderlich) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/PersistedBatchOperation.java:70]: Hm, isn't it really only initialised when all element keys are present? Do we perhaps have to wait for the first execution command and set our own status?

Comment (stoerti) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/PersistedBatchOperation.java:87]: Indeed, there is a small chance that this would not be enough. I have switched to use the first EXECUTING event.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationResumeProcessor.java [hunk 2]
```diff
@@ -138,16 +140,19 @@ public void processDistributedCommand(
...
+      final PersistedBatchOperation batchOperation,
       final BatchOperationLifecycleManagementRecord recordValue) {
     stateWriter.appendFollowUpEvent(resumeKey, BatchOperationIntent.RESUMED, recordValue);
 
     final var batchExecute = new BatchOperationExecutionRecord();
-    batchExecute.setBatchOperationKey(batchOperationKey);
-    commandWriter.appendFollowUpCommand(
-        batchOperationKey, BatchOperationExecutionIntent.EXECUTE, batchExecute);
+    batchExecute.setBatchOperationKey(batchOperation.getKey());
+    if (batchOperation.isInitialized()) {
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationResumeProcessor.java:152]: ❓ can't this be simply replaced with `batchOperation.getStatus == STARTED`?

Comment (stoerti) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationResumeProcessor.java:152]: No, not quite. When a batch operation is paused, it will be in state `PAUSED`. So we need some way to remember, that it previously has been in that state.

But what I indeed changed was, that the isInitialized flag is set on the START event and not the EXECUTING event, because that should be sufficient too and only happens once and not for every item.

**Review by mustafadagher — APPROVED** [review]
