### PR TITLE
Propagate issue details of unhealthy components

### LINKED ISSUE #7759: Unnecessary complexity figuring out why a partition is unhealthy
**Describe the bug**

I ran into an issue in production where we had a bug (https://github.com/camunda-cloud/zeebe/issues/7758) which caused stream processors to fail. However, since only the stream processor failed, there was no leader change (which is another problem, but let's put that aside for now). The main issue is the only log message I got was `Partition-X is unhealthy` - nothing told me it was the stream processor explicitly.

The first issue is that I would expect a message for each sub component, but nothing was there. The second one is that because the stream processor was blocked (not processing), I couldn't access the `partitions` actuator either - it was effectively blocked forever. Finally, there was no easy way for me to query the component states.

**To Reproduce**

Cause a failure in the stream processor such that it stops processing, then try to observe from the outside what's the state of your broker.

**Expected behavior**

There should be an easy way to query the state of all components in the system, such that I can quickly pin point which is down, and why a partition is unhealthy. I shouldn't need a heap dump (which is what I ended up with) to tell me which component is down. That means our monitoring endpoints should block forever and wait until they get an answer from all the components - dead components cannot answer, so it becomes useless.

**Environment:**
 - Zeebe Version: latest
 - Configuration: any

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

To provide more details when components become dead or unhealthy we are adding `HealthReport` and `HealthIssue` classes.
They can be arbitrarily nested to allow tracing issues back to a root cause.

`HealthMonitorable` and `FailureListener` are changed to use `HealthReport` instead of `HealthStatus`.

## Related issues

closes #7759

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I *believe* the SonarCube warnings for improper use of volatile `HealthReport` are false-positives. `HealthReport` is immutable and we always assign a new instance when the health changes, which should make the use of volatile safe.

**Comment by oleschoenburg** [comment]
@deepthidevaki Probably best reviewed commit by commit

File: util/src/main/java/io/camunda/zeebe/util/health/CriticalComponentsHealthMonitor.java [hunk 1]
```diff
@@ -168,17 +176,17 @@ public void onRecovered() {
...
+      actor.run(() -> onComponentDied(report));
     }
 
-    private void onComponentFailure() {
+    private void onComponentFailure(final HealthReport report) {
       if (!monitoredComponents.containsKey(componentName)) {
         return;
       }
 
       log.warn("{} failed, marking it as unhealthy", componentName);
```
Comment (deepthidevaki) [inline util/src/main/java/io/camunda/zeebe/util/health/CriticalComponentsHealthMonitor.java:188]: :x: I think we should also log the health report here. Reason: The other log is "debug" level. It would be good to get these info even if "debug" level is not enabled.

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java [hunk 2]
```diff
@@ -125,7 +125,7 @@
   // Used for randomizing election timeout
   private final Random random;
   private PersistedSnapshot currentSnapshot;
-  private volatile HealthStatus health = HealthStatus.HEALTHY;
+  private volatile HealthReport health = HealthReport.healthy(this);
```
Comment (deepthidevaki) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:128]: :thought_balloon: You can probably suppress this warning via `@SuppressWarning` annotation. I don't remember why we didn't do it yet. Could you please try it?

File: util/src/main/java/io/camunda/zeebe/util/health/HealthMonitorable.java [hunk 3]
```diff
@@ -10,13 +10,24 @@
...
 public interface HealthMonitorable {
 
+  /**
+   * Used by a HealthMonitor to get the name of this component. Most `HealthMonitorable`s override
+   * this method to return their actor name. If they don't override the method, the name of the
+   * class is returned.
+   *
+   * @return the name of this component
+   */
+  default String getName() {
```
Comment (deepthidevaki) [inline util/src/main/java/io/camunda/zeebe/util/health/HealthMonitorable.java:20]: :+1: 

:x: When a subcomponenent is unhealthy, this is how it is shown in the log.

`
 Detected 'UNHEALTHY' components. The current health status of components: [CriticalComponentsHealthMonitor{status=UNHEALTHY, issue=Broker-0-LogStream-1{status=UNHEALTHY, issue=Broker-0-LogAppender-1{status=UNHEALTHY, issue=java.lang.RuntimeException: FIRE!!!!!}}}]
`

Here `CriticalComponentHealthMonitor` is a monitor with in a specific partition. So can we give a proper name for it? It should be something like `partition-<ID>`. So the log looks like:
`
 Detected 'UNHEALTHY' components. The current health status of components: [Partition-1{status=UNHEALTHY, issue=Broker-0-LogStream-1....]
`

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks @oleschoenburg . I have only some minor comments.

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java (hunk 2 above)
Comment (oleschoenburg) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:128]: I think it wasn't a warning before because volatile enums are probably fine? I'll add a suppression here.

**Review by deepthidevaki — APPROVED** [review]
:rocket:
