### PR TITLE
fix(broker): broadcast snapshots to static set of followers

### LINKED ISSUE #3763: Follower do not delete data because it does not receive any snapshots
**Description**

On running our benchmarks I saw an unexpected drop of the processing metrics.

processing

The problem seem that some nodes went out of disk space.

pvc-usage

After taking a look in the logs at broker 2. I just found the following logs:

```
I 2020-01-30T03:08:48.998201888Z 2020-01-30 03:08:48.998 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 000337.sst of snapshot 43897974-5-1580353721239-108611136510024
 
I 2020-01-30T03:08:48.998324095Z 2020-01-30 03:08:48.998 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.logstreams.snapshot - Received all snapshot chunks (74/74), snapshot is valid
 
I 2020-01-30T03:08:49.000942314Z 2020-01-30 03:08:49.000 [] [Broker-2-StateReplication-1] INFO  io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Max snapshot count reached (4), purging snapshots older than DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/42497265-5-1580351919842-105136510471232, metadata=DbSnapshotMetadata{index=42497265, term=5, timestamp=2020-01-30 02:38:39,842, position=105136510471232}}
 
I 2020-01-30T03:08:49.001165833Z 2020-01-30 03:08:49.000 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Deleting snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/40764155-3-1580350135469-101004747137888, metadata=DbSnapshotMetadata{index=40764155, term=3, timestamp=2020-01-30 02:08:55,469, position=101004747137888}}
 
I 2020-01-30T03:08:49.013363468Z 2020-01-30 03:08:49.013 [] [Broker-2-StateReplication-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/40764155-3-1580350135469-101004747137888, metadata=DbSnapshotMetadata{index=40764155, term=3, timestamp=2020-01-30 02:08:55,469, position=101004747137888}} removed from store io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore@1c1c1850
```

It seems that the Broker-2 only receives snapshots for partition 1.
Based on the metrics I also saw that broker 2 is follower for all partitions and Broker-1 Leader for partition 2. I had a deeper look in the logs of the other nodes. 

**Broker-1 Leader for 2**

Seem to send the snapshots for partition 2.
```
I 2020-01-30T03:10:05.371088688Z 2020-01-30 03:10:05.370 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/006076.sst
 
I 2020-01-30T03:10:05.686133211Z 2020-01-30 03:10:05.685 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/005312.sst
 
I 2020-01-30T03:10:06.095022116Z 2020-01-30 03:10:06.094 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/005840.sst
 
I 2020-01-30T03:10:06.096600272Z 2020-01-30 03:10:06.096 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/000425.sst
 
I 2020-01-30T03:10:06.096628849Z 2020-01-30 03:10:06.096 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/006125.sst
 
I 2020-01-30T03:10:06.100268999Z 2020-01-30 03:10:06.099 [Broker-1-SnapshotDirector-2] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160/006232.sst
 
```

**Broker-0 Follower for 2**
Broker 0 seems to receive the snapshots for partition 2.
```
I 2020-01-30T03:10:15.323098175Z 2020-01-30 03:10:15.322 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 006197.sst of snapshot 43099325-3-1580353776084-104969001240160
 
I 2020-01-30T03:10:15.437579442Z 2020-01-30 03:10:15.437 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.logstreams.snapshot - Waiting for more snapshot chunks, currently have 127/128
 
I 2020-01-30T03:10:15.438570092Z 2020-01-30 03:10:15.438 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 006112.sst of snapshot 43099325-3-1580353776084-104969001240160
 
I 2020-01-30T03:10:15.440894706Z 2020-01-30 03:10:15.440 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.logstreams.snapshot - Received all snapshot chunks (128/128), snapshot is valid
 
I 2020-01-30T03:10:15.443213438Z 2020-01-30 03:10:15.442 [] [Broker-0-StateReplication-2] INFO  io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Max snapshot count reached (4), purging snapshots older than DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/41699671-3-1580351977845-101588868285656, metadata=DbSnapshotMetadata{index=41699671, term=3, timestamp=2020-01-30 02:39:37,845, position=101588868285656}}
 
I 2020-01-30T03:10:15.443432341Z 2020-01-30 03:10:15.443 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Deleting snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/40782490-3-1580351085942-99505805655416, metadata=DbSnapshotMetadata{index=40782490, term=3, timestamp=2020-01-30 02:24:45,942, position=99505805655416}}
 
I 2020-01-30T03:10:15.761355865Z 2020-01-30 03:10:15.761 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.AtomixSnapshotStorage - Snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/40782490-3-1580351085942-99505805655416, metadata=DbSnapshotMetadata{index=40782490, term=3, timestamp=2020-01-30 02:24:45,942, position=99505805655416}} removed from store io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore@4d80f1eb
 
I 2020-01-30T03:10:15.761456660Z 2020-01-30 03:10:15.761 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Search for orphaned snapshots below oldest valid snapshot DbSnapshotMetadata{index=41699671, term=3, timestamp=2020-01-30 02:39:37,845, position=101588868285656}
 
I 2020-01-30T03:10:15.761815249Z 2020-01-30 03:10:15.761 [] [Broker-0-StateReplication-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43099325-3-1580353776084-104969001240160, metadata=DbSnapshotMetadata{index=43099325, term=3, timestamp=2020-01-30 03:09:36,084, position=104969001240160}}
 
```

**Broker-2 Follower for 2**
Do not receive any snapshot replication for partition 2.

broker-2-partition-2
broker-2-partition-1

The snapshot replication view is not 100% clear to me, seems to be not working correctly?
replication

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

Removes our dependency on the buggy `ClusterEventService` for snapshot replication, and instead broadcasting is changed to sending to all other reachable nodes in our Raft for the given topic. Removing this dependency fixes known issues where topic subscriptions are not propagated in certain cases, resulting in missed snapshots.

This keeps the same guarantees as the previous implementation, insofar as it may still fail to send some chunks as we perform UDP unicast.

This introduces a very thin abstraction over messaging to other Raft nodes such that our services do not need to know much about Atomix.

## Related issues

closes #3763 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: broker/src/main/java/io/zeebe/broker/system/partitions/RaftMessagingService.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+ * except in compliance with the Zeebe Community License 1.0.
+ */
+package io.zeebe.broker.system.partitions;
+
+import java.nio.ByteBuffer;
+import java.util.concurrent.Executor;
+import java.util.function.Consumer;
+
+/** Abstracts away messaging to other members of a given Raft - add operations as needed. */
+public interface RaftMessagingService {
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/RaftMessagingService.java]: Could we remove the Raft prefix, since it is not really related to that right?

File: broker/src/main/java/io/zeebe/broker/system/partitions/RaftMessagingService.java [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+  /**
+   * Subscribes to a given subject - if another Raft member sends a message on this topic, the
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/RaftMessagingService.java]: just member in the cluster - whether it is a raft member is more implementation specific or?

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @npepinpe i like it. You run benchmarks with this approach as well right? 

I have just some comments see below

File: broker/src/main/java/io/zeebe/broker/system/partitions/RaftMessagingService.java (hunk 1 above)
Comment (npepinpe) [reply broker/src/main/java/io/zeebe/broker/system/partitions/RaftMessagingService.java]: I see what you mean - it's more the partition messaging service, I guess. Will do

File: broker/src/main/java/io/zeebe/broker/system/partitions/RaftMessagingService.java (hunk 2 above)
Comment (npepinpe) [reply broker/src/main/java/io/zeebe/broker/system/partitions/RaftMessagingService.java]: It's another member in the same partition, I'll correct the naming

**Comment by npepinpe** [comment]
I did run benchmarks with this but nothing too strenuous - basically started the cluster, let it run such that snapshots are replicated, trigger failover a few times. Is there something in particular you're thinking of?

**Comment by Zelldon** [comment]
> I did run benchmarks with this but nothing too strenuous - basically started the cluster, let it run such that snapshots are replicated, trigger failover a few times. Is there something in particular you're thinking of? 

Just seeing that snapshot repl works as expected. So after snapshotInterval follower received something. I think also after restart would also be a good think to know

**Comment by npepinpe** [comment]
I tried with no failover, restarting a leader, restarting a follower, restarting the whole cluster. I did get an NPE but I fixed it (also it would fix itself eventually but still, better not to have it :sweat_smile:). I expected `clusterMembershipService#getMember(MemberId)` to always return a member, even if dead, but it returns null when dead :man_shrugging:

**Comment by npepinpe** [comment]
So I wrote a test which covers more cases, mainly that snapshots are replicated even as we restart nodes at different intervals, but unfortunately it's very difficult to assert the correctness of our snapshot replication at the moment. Right now the way we do it is by running the test, ensuring snapshots are replicated, then at the end we compute checksums of the snapshots on the different brokers and assert they are equal.

This unfortunately does not work for snapshots that are replicated not through the `StateReplicationController` but through the normal Raft `InstallRPC`, as on reception we open it to find the last processed position. This causes RocksDB to create some files, maybe compact the MANIFEST, etc., which results in the snapshots being a little different if we only compare naively with checksums.

I think in general as described [here](https://github.com/zeebe-io/zeebe/issues/3918#issuecomment-592972028) we might not need to use positions for snapshot. I think we only need them really to wait until they are valid, but afterwards really once we "commit" them we could drop the position and use indexes, removing the need to open snapshots except for recovery.

**Comment by Zelldon** [comment]
What is actually now our current state here ? :sweat_smile:

**Comment by npepinpe** [comment]
Still working on that test - #3962 will help there as the naive checksum approach should work (though maybe we should investigate how to do it better anyway? :thinking: )

**Comment by npepinpe** [comment]
I added more integration tests for snapshot replication - one caveat is they currently compare snapshot equality using only the SST files, which is not correct, but is necessary until #3962 is merged.

File: broker/src/main/java/io/zeebe/broker/system/partitions/impl/AtomixPartitionMessagingService.java [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+  }
+
+  @Override
+  public void unsubscribe(final String subject) {
+    communicationService.unsubscribe(subject);
+  }
+
+  private Set<MemberId> getOtherMemberIds(
+      final ClusterMembershipService clusterMembershipService, final Collection<MemberId> members) {
+    final var localMemberId = clusterMembershipService.getLocalMember().id();
```
Comment (Zelldon) [inline broker/src/main/java/io/zeebe/broker/system/partitions/impl/AtomixPartitionMessagingService.java]: This only works when all nodes configured as initial entries right?

**Review by ChrisKujawa — APPROVED** [review]
Like it :+1: Had just a small question

File: broker/src/main/java/io/zeebe/broker/system/partitions/impl/AtomixPartitionMessagingService.java (hunk 3 above)
Comment (npepinpe) [reply broker/src/main/java/io/zeebe/broker/system/partitions/impl/AtomixPartitionMessagingService.java]: Sort of - it assumes that the set of members in the Raft is static, so it's really just filtering out the local member. But this is independent of the discovery protocol.

Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/impl/AtomixPartitionMessagingService.java]: You use the ClusterMemberShipService to get the members or?

Comment (npepinpe) [reply broker/src/main/java/io/zeebe/broker/system/partitions/impl/AtomixPartitionMessagingService.java]: It's used initially to get the local member ID, and later to check if a member is reachable. So this assumes member IDs are static, and the Raft configuration is also static - but whether they are reachable or not is dynamic and relies on SWIM.
