### PR TITLE
Incident notifier version bug

### LINKED ISSUE #31192: Incidents in incident notifier does not include process version
### 

### 

### 

### 

### Description

As per https://github.com/camunda/camunda-operator/issues/3747#issuecomment-2812452683, there are two bugs in the incident notifier:

1. The version tag is used rather than the process version. If there is no version tag, then this is omitted from the notified incident. We should consider either of the following:
  - Using the process instead
  - Using the versionTag, but falling back to the process if empty
2. The incident count is showing as double the correct value, when compared to 8.7 version

### Steps to reproduce

Testing instructions documented [here](https://github.com/camunda/camunda-operator/issues/3747#issuecomment-2700789011)

### Current behavior

The incidents do not include the version, if no version Tag exists

### Expected behavior

The process version is included. Linked [comment](https://github.com/camunda/camunda-operator/issues/3747#issuecomment-2700789011) has a screenshot demonstrating the issue

### Environment

SaaS & SM

### Version

- Component Version: 8.8.0-alpha3

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

The version tag which does not always exist is used instead of the process version, this sometimes results in a null value which doesn't display any information, this fixes it.

## Related issues

closes #31192

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/ProcessHandler.java [hunk 1]
```diff
@@ -86,7 +86,7 @@ public void updateEntity(final Record<Process> record, final ProcessEntity entit
     // record handler
     final var cachedProcessEntity =
         new CachedProcessEntity(
-            entity.getName(), entity.getVersionTag(), entity.getCallActivityIds());
+            entity.getName(), Integer.toString(entity.getVersion()), entity.getCallActivityIds());
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/ProcessHandler.java:89]: The changes here seem reasonable to me. However, just wondering if it would make more sense to instead show the version tag if it exists, and fall back to the version if it doesn't. Wdyt?

I don't feel strongly and we can get PM input if needed. I would also be fine merging as is and following up on this later if needed

Comment (EuroLew) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/ProcessHandler.java:89]: yea sure that works as well

**Review by RomanJRW — COMMENTED** [review]
One comment on the processCache. If I am overlooking something, happy to approve

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/cache/process/CachedProcessEntity.java [hunk 2]
```diff
@@ -9,4 +9,10 @@
...
 import java.util.List;
 
-public record CachedProcessEntity(String name, String versionTag, List<String> callElementIds) {}
+public record CachedProcessEntity(
+    String name, String versionTag, String version, List<String> callElementIds) {
+  public CachedProcessEntity(
+      final String name, final String versionTag, final List<String> callElementIds) {
+    this(name, versionTag, null, callElementIds);
+  }
+}
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/cache/process/CachedProcessEntity.java:18]: isn't this the wrong way around? i.e. a cached entity should _always_ have a version but only sometimes a version tag. So the constructor should take a version rather than a tag, and then pass the second argument as null rather than the third. Like this:

```suggestion
public record CachedProcessEntity(
    String name, String versionTag, String version, List<String> callElementIds) {
  public CachedProcessEntity(
      final String name, final String version, final List<String> callElementIds) {
    this(name, null, version, callElementIds);
  }
}
```

**Comment by RomanJRW** [comment]
@EuroLew: Are you waiting for further review here? If we get a resolution/answer to [this thread](https://github.com/camunda/camunda/pull/31414#discussion_r2111682531), I think we can get this merged

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/cache/process/CachedProcessEntity.java (hunk 2 above)
Comment (EuroLew) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/cache/process/CachedProcessEntity.java]: no this is the correct way round, with my solution all the current instances of `CachedProcessEntity` which use the `(name,versionTag,callElements)` constructor are unchanged, but for incidents which may require the `version` field it is filled in.

**Review by RomanJRW — APPROVED** [review]
