### PR TITLE
Avoid using the logstream writer on reprocessing

### LINKED ISSUE #6557: StateWriter doesn't use ReprocessingStreamWriter during reprocessing
**Describe the bug**
During reprocessing it appears that the StateWriter uses a normal `TypedStreamWriterImpl` as its streamWriter instead of the ReprocessingStreamWriter that is normally used during reprocessing.

Note, that records are not actually written to the log, since the batchwriter is not flushed on reprocessing. However, this can still lead to problems. One of which we've seen in [reported error](https://console.cloud.google.com/errors/CIyOy5qX44qppgE?service=zeebe-broker&time=P7D&filter=text:IndexOutOfBoundsException&project=zeebe-io&authuser=1). In this error, the batchwriter is unable to copy a new `Variable` event into its batch for the reprocessing of a `CreateWorkflowInstance` command.

**To Reproduce**
Process a `CreateWorkflowInstance` command and start reprocessing.

**Expected behavior**
No new events are written to the log (or to the batchwriter) during reprocessing

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IndexOutOfBoundsException: index=1073741823 length=8 maxCapacity=1073741824
	at org.agrona.ExpandableDirectByteBuffer.ensureCapacity(ExpandableDirectByteBuffer.java:1151) ~[agrona-1.9.0.jar:1.9.0]
	at org.agrona.ExpandableDirectByteBuffer.putLong(ExpandableDirectByteBuffer.java:184) ~[agrona-1.9.0.jar:1.9.0]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.copyExistingEventToBuffer(LogStreamBatchWriterImpl.java:165) ~[zeebe-logstreams-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.event(LogStreamBatchWriterImpl.java:78) ~[zeebe-logstreams-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.TypedStreamWriterImpl.appendRecord(TypedStreamWriterImpl.java:72) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.TypedStreamWriterImpl.appendRecord(TypedStreamWriterImpl.java:60) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.TypedStreamWriterImpl.appendFollowUpEvent(TypedStreamWriterImpl.java:171) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.EventApplyingStateWriter.appendFollowUpEvent(EventApplyingStateWriter.java:48) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.writers.EventApplyingStateWriter.appendFollowUpEvent(EventApplyingStateWriter.java:39) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.variable.VariableBehavior.setLocalVariable(VariableBehavior.java:182) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.variable.VariableBehavior.mergeLocalDocument(VariableBehavior.java:76) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.workflowinstance.CreateWorkflowInstanceProcessor.setVariablesFromDocument(CreateWorkflowInstanceProcessor.java:117) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.workflowinstance.CreateWorkflowInstanceProcessor.onCommand(CreateWorkflowInstanceProcessor.java:81) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:70) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:34) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.reprocessRecord(ReProcessingStateMachine.java:402) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$chooseOperationForEvent$7(ReProcessingStateMachine.java:368) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$processUntilDone$4(ReProcessingStateMachine.java:340) ~[zeebe-workflow-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
 - Zeebe Version: medic-cw-09-cf1627167-benchmark
 - Source: cf1627167
 - Configuration: Weekly benchmark

### PR DESCRIPTION
**Pull request by saig0**
## Description

* the stream processor enables writing to the log stream when start processing
* on reprocessing, it uses the reprocessing checker
* no tests to verify the behavior because we'll remove it after the migration is done

## Related issues

closes #6557

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/main/java/io/zeebe/engine/processing/streamprocessor/StreamProcessor.java [hunk 1]
```diff
@@ -122,6 +122,10 @@ protected void onActorStarted() {
       final ReProcessingStateMachine reProcessingStateMachine =
           new ReProcessingStateMachine(processingContext);
 
+      // disable writing to the log stream but for reprocessing checks
+      processingContext.disableLogStreamWriter();
+      processingContext.enableReprocessingStreamWriter();
+
```
Comment (korthout) [inline engine/src/main/java/io/zeebe/engine/processing/streamprocessor/StreamProcessor.java:128]: line 127 kind of negates whatever 126 did. Did you want this explicitly to make it more clear what happens? I think it's fine to use only line 127.

**Review by korthout — APPROVED** [review]
LGTM, just a minor detail, but nothing stopping us from merging this.

File: engine/src/main/java/io/zeebe/engine/processing/streamprocessor/StreamProcessor.java (hunk 1 above)
Comment (saig0) [reply engine/src/main/java/io/zeebe/engine/processing/streamprocessor/StreamProcessor.java:128]: Yes, exactly. I would just keep it for now. We can look at it again when we remove the reprocessing writer after the migration is done.
