### PR TITLE
fix(engine): don't mutate state when checking for job backoffs

### LINKED ISSUE #13041: Don't mutate state through `JobBackoffChecker`

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Remove sneaky state mutation when visiting jobs with expired backoffs. Instead, reliably cleanup backoff when recurring or deleting the job. When a backoff is found again before the first `RECUR_AFTER_BACKOFF` command is processed, another `RECUR_AFTER_BACKOFF` command is written. This is okay because on processing, we ignore jobs that no longer exist or that have a newer recurring time set.

Closes #13041

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/state/instance/JobStateTest.java [hunk 1]
```diff
@@ -347,8 +347,13 @@ public void shouldFailJobWithRetriesLeft() {
...
     // given
     final long key = 1L;
+    final long now = 0;
     final var retryBackoff = 100;
-    final JobRecord jobRecord = newJobRecord().setRetries(1).setRetryBackoff(retryBackoff);
+    final JobRecord jobRecord =
+        newJobRecord()
+            .setRetries(1)
+            .setRetryBackoff(retryBackoff)
+            .setRecurringTime(now + retryBackoff);
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/state/instance/JobStateTest.java:356]: 👍 Good find, much cleaner

File: engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java [hunk 2]
```diff
@@ -288,8 +288,7 @@ public void forEachActivatableJobs(
         jobTypeKey,
         ((compositeKey, zbNil) -> {
           final long jobKey = compositeKey.second().inner().getValue();
-          // TODO #6521 reconsider race condition and whether or not the cleanup task is needed
-          return visitJob(jobKey, callback::apply, () -> {});
+          return visitJob(jobKey, callback::apply);
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:291]: - 🎉 #6521

File: engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobRecurProcessor.java [hunk 3]
```diff
@@ -42,9 +43,10 @@ public JobRecurProcessor(
   @Override
   public void processRecord(final TypedRecord<JobRecord> record) {
     final long jobKey = record.getKey();
-    final JobState.State state = jobState.getState(jobKey);
+    final var job = jobState.getJob(jobKey);
+    final var state = jobState.getState(jobKey);
 
-    if (state == State.FAILED) {
+    if (state == State.FAILED && hasRecurred(job)) {
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobRecurProcessor.java:49]: 👋 Bye bye race condition

**Review by korthout — APPROVED** [review]
Great work once again @oleschoenburg 💯 

I can only give praise 🙌 

❓ Should we backport this? I think so 🤔 

LGTM 👍 

PS: Sorry for the delayed review 🙇

File: engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java (hunk 2 above)
Comment (oleschoenburg) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:291]: Do you think we can close #6521 then?

**Comment by oleschoenburg** [comment]
Regarding backporting: we didn't backport https://github.com/camunda/zeebe/pull/13035 either. I don't think a backport is necessary because job timeouts and backoffs are always checked in between processing. Does that make sense to you @korthout or am I missing something?

bors merge

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors retry

**Comment by korthout** [comment]
>Regarding backporting: we didn't backport https://github.com/camunda/zeebe/pull/13035 either. I don't think a backport is necessary because job timeouts and backoffs are always checked in between processing. Does that make sense to you @korthout or am I missing something?

@oleschoenburg The constraint that only events can produce state changes through event appliers exists on the previous releases also. I'd prefer to backport it to fix that and keep implementation alike.

**Comment by oleschoenburg** [comment]
Alright then I'll first backport https://github.com/camunda/zeebe/pull/13035 and then this one. Wish me luck :crossed_fingers: :sweat_smile:

**Comment by oleschoenburg** [comment]
bors merge
