### PR TITLE
Fix/32715 bo count failure as completed

### LINKED ISSUE #32715: Include FAILED status to complete batch operation
In processing batch operations, when one of the partitions fails in the scheduler phase, it will never send a COMPLETED to the leader partition.

AC:
- The failing partition must send a FAIL_PARTITION to the leader partition
- the leader partition count's this as COMPLETED

### PR DESCRIPTION
**Pull request by stoerti**
## Description

This PR adds a FAIL_PARTITION
 distributed command and includes that one into the COMPLETED check
## Related issues

closes #32715

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationPartitionFailProcessor.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+    final var batchOperationKey = command.getValue().getBatchOperationKey();
+    LOGGER.debug(
+        "Processing command from partition {} to mark batch operation {} as failed",
+        command.getValue().getSourcePartitionId(),
+        command.getValue().getBatchOperationKey());
+
+    final var oBatchOperation = batchOperationState.get(batchOperationKey);
+    if (oBatchOperation.isPresent()) {
+      final var bo = oBatchOperation.get();
+      if (bo.getFinishedPartitions().contains(command.getValue().getSourcePartitionId())) {
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationPartitionFailProcessor.java:74]: 👍 nice! I like this better than the `containsAll()` in the Complete processor

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationFailProcessor.java [hunk 2]
```diff
@@ -24,16 +31,57 @@ public final class BatchOperationFailProcessor
   private static final Logger LOGGER = LoggerFactory.getLogger(BatchOperationFailProcessor.class);
 
   private final StateWriter stateWriter;
+  private final TypedCommandWriter commandWriter;
+  private final CommandDistributionBehavior commandDistributionBehavior;
+  private final KeyGenerator keyGenerator;
+  private final int partitionId;
 
-  public BatchOperationFailProcessor(final Writers writers) {
+  public BatchOperationFailProcessor(
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationFailProcessor.java:39]: ❓ An overall question to be sure I understand correctly:
Right now, we publish a `FAIL`, that then publishes a `FAIL_PARTITION` command. 
The `FAILED` applier only marks the bo locally as failed. and the `FAIL_PARTITION` applier actually either updates the count on the lead partition, or removes the bo from the local state.

Did I get that right?

❓ If so, do we really have a need for this intermediary `FAIL`/`FAILED` command/event? would it make sense to remove it?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationPartitionCompleteProcessor.java [hunk 3]
```diff
@@ -102,7 +102,7 @@ private void doProcessRecord(final TypedRecord<BatchOperationPartitionLifecycleR
         stateWriter.appendFollowUpEvent(
             batchOperationKey, BatchOperationIntent.PARTITION_COMPLETED, command.getValue());
 
-        if (bo.getCompletedPartitions().containsAll(bo.getPartitions())) {
+        if (bo.getFinishedPartitions().containsAll(bo.getPartitions())) {
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationPartitionCompleteProcessor.java]: 🔧 could we refactor this like the one above to only check the size? the check above already guarantees we won't have the same partition twice

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/BatchOperationPartitionFailedApplier.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+  public BatchOperationPartitionFailedApplier(
+      final MutableBatchOperationState batchOperationState, final int partitionId) {
+    this.batchOperationState = batchOperationState;
+    this.partitionId = partitionId;
+  }
+
+  @Override
+  public void applyState(final long recordKey, final BatchOperationPartitionLifecycleRecord value) {
+    if (Protocol.decodePartitionId(value.getBatchOperationKey()) == partitionId) {
+      batchOperationState.finishPartition(
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/BatchOperationPartitionFailedApplier.java:31]: 💭 could we also pass (and store) a flag here if it was completed successfully or with errors, so we maybe in the end write a `COMPLETED` or `COMPLETED_WITH_ERRORS` or something of that sort?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationFailProcessor.java (hunk 2 above)
Comment (stoerti) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationFailProcessor.java:39]: In this PR I have removed publishing the `BatchOperationIntent.FAILED` event from this processor. It is completely replaced by the `BatchOperationIntent.FAIL_PARTITION` command and `BatchOperationIntent.PARTITION_FAILED` event. The `BatchOperationIntent.PARTITION_FAILED` behaves exactly like the `BatchOperationIntent.PARTITION_COMPLETED` event for now in the appliers.

I tried to get rid of the command/event roundtrip, but unfortunately we need it, because the original failure happens in the BatchOperationExecutionScheduler. There I only can append local commands, not events. SO I always need an intermediate command+processor to append the events and distribute the command to the leader.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/BatchOperationPartitionFailedApplier.java (hunk 4 above)
Comment (stoerti) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/BatchOperationPartitionFailedApplier.java:31]: Definitely! But since the discussion about this is still open and running, I would like to do that in a separate issue & PR.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationPartitionCompleteProcessor.java (hunk 3 above)
Comment (stoerti) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationPartitionCompleteProcessor.java]: I chose the more specific `containsAll()` because it checks the existence of every single original partition in the batch. Mostly because it might be more stable in future when rescaling the partitions.
But sure, compare the size should also do the job 👍

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationFailProcessor.java (hunk 2 above)
Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationFailProcessor.java:39]: I see, makes sense! 

Initially, I was thinking why can't we distribute commands from the scheduler. But then I realized than `commandDistributionBehavior` actually alters the state, which we should not do in a scheduled task.

**Review by mustafadagher — APPROVED** [review]
