### PR TITLE
9416 duplicate task headers

### LINKED ISSUE #9416: Explicitly handle duplicated task headers
**Description**

When deploying a model where a service task has more than one custom header with the same key, an error is raised and the deploy fails.

The error message returned on deploy is pretty clear:
image

But the error is not handled explicitly:
https://github.com/camunda/zeebe/blob/2c793910c4ed5a996c40f0b1b52b346880edb551/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/TaskHeadersTransformer.java#L38-L41

We should handle this a bit more gracefully so that the error does not show up in our error reporting tool: https://console.cloud.google.com/errors/detail/CPr11a6I_KbY6gE;service=zeebe;time=P7D?project=camunda-cloud-240911

Related discussion on Slack: https://camunda.slack.com/archives/CSQ2E3BT4/p1652943416460409

BPMN file to reproduce: [duplicatetaskheaders.zip](https://github.com/camunda/zeebe/files/8726153/duplicatetaskheaders.zip)

### PR DESCRIPTION
**Pull request by pihme**
## Description
Adds a validation that adds an error when headers have duplicate keys.

## Related issues

closes #9416

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ZeebeTaskHeadersValidator.java [hunk 1]
```diff
@@ -40,4 +46,18 @@ private void checkForReservedHeaderKeys(
         .map(key -> String.format(RESERVED_KEY_MESSAGE_TEMPLATE, key, RESERVED_HEADER_NAME_PREFIX))
         .forEach(message -> validationResultCollector.addError(0, message));
   }
+
+  private void checkForDuplicateKeys(
+      final ZeebeTaskHeaders element, final ValidationResultCollector validationResultCollector) {
+    element.getHeaders().stream()
+        .map(ZeebeHeader::getKey)
+        .collect(Collectors.toMap(Function.identity(), value -> 1, Integer::sum))
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ZeebeTaskHeadersValidator.java:54]: 🔧 Not sure if this is better, but alternatively you could use:
```.collect(Collectors.groupingBy(Function.identity(), Collectors.counting()))```

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ZeebeTaskHeadersValidatorTest.java [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+    // when
+    sut.validate(element, mockValidationResultCollector);
+
+    // then
+    verify(mockValidationResultCollector)
+        .addError(0, "Headers contain duplicate entries for key 'testKey'");
+    verify(mockValidationResultCollector)
+        .addError(0, "Headers contain duplicate entries for key 'testKey3'");
+    verify(mockValidationResultCollector, never())
+        .addError(0, "Headers contain duplicate entries for key 'testKey2'");
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ZeebeTaskHeadersValidatorTest.java:87]: 💭 I'm not a big fan of interaction checks when all we want is to verify some results. But I guess it works nicely here.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ZeebeTaskHeadersValidatorTest.java [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+  final ZeebeTaskHeadersValidator sut = new ZeebeTaskHeadersValidator();
+
+  @Test
+  public void shouldNotAddErrorAboutDuplicateKeys() {
+    // given
+    final ValidationResultCollector mockValidationResultCollector =
+        mock(ValidationResultCollector.class);
+
+    final ZeebeTaskHeaders element =
+        creatMockTaskHeaders(List.of(new HeaderEntry("testKey", "testValue")));
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ZeebeTaskHeadersValidatorTest.java:35]: 🔧 I'd prefer that this case checks no duplicate keys, but that it does have multiple header entries. That way its edge is closer to the other test case. Currently, this case could also succeed simply because the validator doesn't accept multiple header entries but accepts single entries.

**Review by korthout — APPROVED** [review]
LGTM 👍 I really like the solution

Sorry for the slow review though.

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

File: engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ZeebeTaskHeadersValidator.java (hunk 1 above)
Comment (pihme) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ZeebeTaskHeadersValidator.java]: Turns out this one behaves differently with respect to null values. I will revert back to the first way.
https://ci.zeebe.camunda.cloud/job/camunda/job/zeebe/job/9416-duplicate-task-headers/2/testReport/junit/io.camunda.zeebe.engine.processing.bpmn.activity/ActivityTest(java-testrun)/Verify___Test___shouldIgnoreTaskHeadersIfEmpty/

**Comment by korthout** [comment]
@pihme It seems the most [recent change](https://github.com/camunda/zeebe/compare/1344bcfe33e363aaa734761d0c3b026d04fd4e64..a5ffefc40c3f926ae6fc6735ac1b8f9ffb2b665a) caused test failures

**Comment by pihme** [comment]
bors merge

**Comment by oleschoenburg** [comment]
This was just a networking issue, so I'm retrying for you :slightly_smiling_face: 

bors retry

**Comment by oleschoenburg** [comment]
Sorry for accidentally closing. Not sure why bors says it's already running a review :thinking:
Shall we try again?

bors r+
