### PR TITLE
fix(engine): fix message transformer of extension elements

### LINKED ISSUE #8521: BpmnModelException: Collection expected to have <1> entry but has <0>
**Describe the bug**

The attached BPMN model produces a deployment error without saying what the real issue is.

zbctl output
```
Error: rpc error: code = InvalidArgument desc = Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'2 - Vacation Request Part4 - Trisotech-CamundaCloud3.bpmn': Collection expected to have <1> entry but has <0>
```
This issue has been discovered during the dry runs for the upcoming demo of the BPMN Model Interchange Working Group during the OMG Technical Meeting on March 21-25, 2022 in Reston, VA, USA.

**To Reproduce**

[2 - Vacation Request Part4 - Trisotech-CamundaCloud3.bpmn.txt](https://github.com/camunda-cloud/zeebe/files/7810592/2.-.Vacation.Request.Part4.-.Trisotech-CamundaCloud3.bpmn.txt)

```sh
zbctl deploy --insecure "2 - Vacation Request Part4 - Trisotech-CamundaCloud3.bpmn"
```

**Expected behavior**
A clear and concise description of what was wrong with the model ideally with id and name of the element that causes it so that I can find it in the modeler.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2022-01-04 15:46:20.442 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] ERROR
      io.camunda.zeebe.broker.process - Unexpected error while processing resource '2 - Vacation Request Part4 - Trisotech-CamundaCloud3.bpmn'
io.camunda.zeebe.model.bpmn.BpmnModelException: Collection expected to have <1> entry but has <0>
	at io.camunda.zeebe.model.bpmn.impl.QueryImpl.singleResult(QueryImpl.java:77) ~[zeebe-bpmn-model-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:39) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:21) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:61) ~[zeebe-bpmn-model-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:108) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:123) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:96) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:100) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$2(ProcessingStateMachine.java:263) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:253) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:221) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:192) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:184) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
```

</p>
</details>

**Environment:**
 - OS: Ubuntu 21.10 Kernel 5.13.0-22-generic
 - Zeebe Version: 1.3.0-alpha1
 - Configuration: distro defaults

### LINKED ISSUE #10962: BpmnModelException: Collection expected to have <1> entry but has <0>
**Describe the bug**

When transforming a message element, if there are any extension elements, we look up a message subscription and expect one to be present. It seems possible that there are other extensions and yet not subscription.

**To Reproduce**

Since the error occurs during the deployment (and prevents it), I couldn't get the original model. I did come up with one equivalent, though I realize it doesn't represent a real user model. I'm still very curious how a user ran into this!

Deploy the following model:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_17ciwxv" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.0.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.0.0">
  <bpmn:process id="Process_1e1db37" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_1ihpu77</bpmn:outgoing>
      <bpmn:messageEventDefinition id="MessageEventDefinition_1i4l5ll" messageRef="Message_3us25ap" />
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_1ihpu77" sourceRef="StartEvent_1" targetRef="Event_1t5fhii" />
    <bpmn:endEvent id="Event_1t5fhii">
      <bpmn:incoming>Flow_1ihpu77</bpmn:incoming>
    </bpmn:endEvent>
  </bpmn:process>
  <bpmn:message id="Message_3us25ap" name="Message_3us25ap">
    <bpmn:extensionElements>
      <zeebe:loopCharacteristics inputCollection="=inputs" inputElement="input" outputCollection="outputs" outputElement="=output" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1e1db37">
      <bpmndi:BPMNEdge id="Flow_1ihpu77_di" bpmnElement="Flow_1ihpu77">
        <di:waypoint x="215" y="97" />
        <di:waypoint x="432" y="97" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_0n9czjp_di" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="79" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1t5fhii_di" bpmnElement="Event_1t5fhii">
        <dc:Bounds x="432" y="79" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1kncmh3_di" bpmnElement="Event_1legy83">
        <dc:Bounds x="272" y="272" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

Notice that instead of a `zeebe:subscription` extension element in the message, I put a `zeebe:loopCharacteristics`. It doesn't really matter, the real issue is that:

1. It is a message start event
2. The message has some extension element
3. There is no subscription extension element

**Expected behavior**

I get a clear rejection message saying I need a subscription. Right now, I just get an error in the logs and no rejection, and I am a sad user.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.model.bpmn.BpmnModelException: Collection expected to have <1> entry but has <0>
	at io.camunda.zeebe.model.bpmn.impl.QueryImpl.singleResult(QueryImpl.java:79) ~[zeebe-bpmn-model-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:39) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:21) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:66) ~[zeebe-bpmn-model-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:110) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:69) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:98) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:261) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:257) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:206) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:182) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
```

</p>
</details>

**Environment:**
- OS: SaaS
- Zeebe Version: 8.1.2
- Configuration: SaaS

### PR DESCRIPTION
**Pull request by skayliu**
## Description

Fix message transformer of extension elements for start event.

If a message start event has any extension elements, the error `BpmnModelException: Collection expected to have <1> entry but has <0>` occurs during the deployment.

## Related issues

closes #10962 
closes #8521 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by skayliu** [comment]
Hi, @saig0, Please have a look at this fix. Thanks.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/MessageTransformer.java [hunk 1]
```diff
@@ -34,7 +38,7 @@ public void transform(final Message element, final TransformContext context) {
     final ExecutableMessage executableElement = new ExecutableMessage(id);
     final ExtensionElements extensionElements = element.getExtensionElements();
 
-    if (extensionElements != null) {
+    if (extensionElements != null && !isReferredByStartEvent(element)) {
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/MessageTransformer.java:41]: :x: The `isReferredByStartEvent` method solves the issue by preventing the `if` block from being executed by validating that the current `message` isn't referred by a `start event`.

This is a bit redundant, and the `isReferredByStartEvent` is a duplication of [this message validation](https://github.com/camunda/zeebe/blob/20c87ed36587fc6e73b55e97de19868a12ced4ca/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/MessageValidator.java#L77-L90) code.

:thought_balloon: We already validate against the two Message use-cases in the `MessageValidator` class, i.e. 
* If the message is referred by a Catch event, Receive task, or Event SubProcess start event, we check for a `name` attribute and for a `subscription` element.
* If the message is referred by a process Start event, we only check for a `name` attribute.

So, when we get to the `MessageTransformer`, we have already validated the use cases, so it would be better to avoid another validation check.

:wrench: I think we can do this by expanding the [Query](https://github.com/camunda/zeebe/blob/dbac8504f4cf680865c44919252f0c3118db44e2/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/Query.java#L39) API, by adding a new method there. The method can be `Optional<T> findSingleResult()`.

Using this method, we can then get the `correlationKeyExpression` only when a `subscription` is available.

With this refactoring, we will have two benefits. We will improve the Query API, we will avoid code duplication. And we will generalize the `MessageTransformer` code so that the specific use-cases are not as visible here.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java [hunk 2]
```diff
@@ -484,6 +485,28 @@ public void shouldDeployProcessModelWithUndefinedTask() {
     assertThat(deployedProcess.getProcessDefinitionKey()).isGreaterThan(0);
   }
 
+  @Test
+  public void shouldCreateDeploymentWithMessageStartEventIgnoreExtensionElements() {
```
Comment (koevskinikola) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java:489]: :+1: Nice test coverage for the fix.

**Review by koevskinikola — CHANGES_REQUESTED** [review]
Hi @skayliu,

Thank you for this bug fix. Your solution solves the problem, but causes some code duplication, which I think can be avoided.

Have a look at my comment bellow.

**Comment by skayliu** [comment]
> I think we can do this by expanding the [Query](https://github.com/camunda/zeebe/blob/dbac8504f4cf680865c44919252f0c3118db44e2/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/Query.java#L39) API, by adding a new method there. The method can be Optional<T> findSingleResult()

@koevskinikola, 👍  That's a great idea.  I've implemented this, Plese review again.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/MessageTransformer.java [hunk 3]
```diff
@@ -35,12 +36,17 @@ public void transform(final Message element, final TransformContext context) {
     final ExtensionElements extensionElements = element.getExtensionElements();
 
     if (extensionElements != null) {
-      final ZeebeSubscription subscription =
-          extensionElements.getElementsQuery().filterByType(ZeebeSubscription.class).singleResult();
-      final Expression correlationKeyExpression =
-          expressionLanguage.parseExpression(subscription.getCorrelationKey());
+      final Optional<ZeebeSubscription> subscription =
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/MessageTransformer.java:39]: :+1: Looks awesome!

File: bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/impl/QueryImpl.java [hunk 4]
```diff
@@ -79,4 +81,13 @@ public T singleResult() {
...
   }
+
+  @Override
+  public Optional<T> findSingleResult() {
+    if (collection.size() == 1) {
+      return Optional.of(collection.iterator().next());
+    } else {
+      return Optional.empty();
+    }
+  }
```
Comment (koevskinikola) [inline bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/impl/QueryImpl.java:92]: :x: The new method looks great. We can also refactor the code of the `singleResult()` method, to use the new `optionalSingleResult()`. It can look something like this:

```
  @Override
  public T singleResult() {
    if (optionalSingleResult().isPresent()) {
      return optionalSingleResult().get();
    } else {
      throw new BpmnModelException(
          "Collection expected to have <1> entry but has <" + collection.size() + ">");
    }
  }
```

**Review by koevskinikola — CHANGES_REQUESTED** [review]
@skayliu the changes look good now. There is just one more place to further improve the code.

File: bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/impl/QueryImpl.java (hunk 4 above)
Comment (skayliu) [reply bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/impl/QueryImpl.java:92]: It's done.

**Comment by skayliu** [comment]
@koevskinikola, Done.

**Review by koevskinikola — APPROVED** [review]
LGTM :tada: 

Awesome, thank you for fixing this!

bors merge
