### PR TITLE
[CPT] fix: Element assertion can handle BPMN elements with the same name

### LINKED ISSUE #25355: [CPT] hasCompletedElements() throws an IllegalStateException: Duplicate key null
## Description

I have a process test with an `hasCompletedElements()` assertion. When running the test case, it throws the following exception:

```
java.lang.IllegalStateException: Duplicate key null (attempted merging values COMPLETED and COMPLETED)
```

The test case:
```

### PR DESCRIPTION
**Pull request by saig0**
## Description

Fix a bug in the element assertions if two BPMN elements have the same name (or an empty name). 

Note that the element assertions will change soon when switching it element IDs instead ([ref](https://github.com/camunda/camunda/issues/23294)).

## Related issues

closes #25355

### CODE REVIEW

File: testing/camunda-process-test-java/src/test/java/io/camunda/process/test/api/ProcessInstanceAssertTest.java [hunk 1]
```diff
@@ -608,6 +666,22 @@ void shouldHasTerminatedElements() throws IOException {
       CamundaAssert.assertThat(processInstanceEvent).hasTerminatedElements("A", "B");
     }
 
+    @Test
+    void shouldHasTwoTerminatedElements() throws IOException {
```
Comment (berkaycanbc) [inline testing/camunda-process-test-java/src/test/java/io/camunda/process/test/api/ProcessInstanceAssertTest.java:670]: 🔧 
```suggestion 
    void shouldHaveTwoTerminatedElements() throws IOException {
```

File: testing/camunda-process-test-java/src/test/java/io/camunda/process/test/api/ProcessInstanceAssertTest.java [hunk 2]
```diff
@@ -520,6 +541,22 @@ void shouldHasCompletedElements() throws IOException {
       CamundaAssert.assertThat(processInstanceEvent).hasCompletedElements("A", "B");
     }
 
+    @Test
+    void shouldHasTwoCompletedElements() throws IOException {
```
Comment (berkaycanbc) [inline testing/camunda-process-test-java/src/test/java/io/camunda/process/test/api/ProcessInstanceAssertTest.java:545]: 🔧 
```suggestion 
    void shouldHaveTwoCompletedElements() throws IOException {
```

**Review by berkaycanbc — APPROVED** [review]
LGTM 🚀 

🔧 Left two naming correction suggestion.
