### PR TITLE
fix: set correct default redirect URI

### LINKED ISSUE #45555: Unable to log in without explicitly configuring the OIDC callback/redirect URI
### 

### 

, 

### 

### 

### Description

At the moment, if we do not set the redirect_uri, it will default to `/login/oauth2/code/oidc`. 

When this is set, on successful login, the user is redirected to `/oauth2/authorization/oidc`, which turns into a loop and an too many redirects error.

### Steps to reproduce

1. Set up your cluster for OIDC
2. **Do not configure a CAMUNDA_SECURITY_AUTHENTICATION_OIDC_REDIRECTURI**
3. Make sure your IdP allows for `/login/oauth2/code/oidc` as a redirect URI
4. Try to log in

### Current behavior

At the moment, if we do not set the redirect_uri, it will default to `/login/oauth2/code/oidc`. 

When this is set, on successful login, the user is redirected to `/oauth2/authorization/oidc`, which turns into a loop and an too many redirects error.

### Expected behavior

The default `/sso-callback` redirect URI is used when nothing is configured.

### Workaround

Always configure the REDIRECTURI to be `/sso-callback`.

### Environment

SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR ensures we use an appropriate default redirect URI when none is given, such that we always redirect to `/sso-callback` unless explicitly told not to.

We keep the override to support cases such as reverse proxies and so on.

## Related issues

closes #45555

### CODE REVIEW

**Comment by npepinpe** [comment]
Related docs PR: https://github.com/camunda/camunda-docs/pull/7922

File: authentication/src/main/java/io/camunda/authentication/config/ClientRegistrationFactory.java [hunk 1]
```diff
@@ -23,6 +23,8 @@
 public final class ClientRegistrationFactory {
   private static final Logger LOGGER = LoggerFactory.getLogger(ClientRegistrationFactory.class);
 
+  private static final String DEFAULT_REDIRECT_URI = "{baseUrl}" + WebSecurityConfig.REDIRECT_URI;
```
Comment (Ben-Sheppard) [inline authentication/src/main/java/io/camunda/authentication/config/ClientRegistrationFactory.java:26]: ❓ Is `{baseUrl}` a special placeholder here? My instinct says yes however the test assertion makes me thing this will literally be `{baseUrl}/sso-callback`

**Review by Ben-Sheppard — APPROVED** [review]
The logic is fine for me, just one question about `{baseUrl}` but I'll approve early if you suggest that does work how I think it does

File: authentication/src/main/java/io/camunda/authentication/config/ClientRegistrationFactory.java (hunk 1 above)
Comment (npepinpe) [reply authentication/src/main/java/io/camunda/authentication/config/ClientRegistrationFactory.java:26]: It's documented in `ClientRegistration.Builder.redirectUri(String)`

```java
/**
 * Sets the uri (or uri template) for the redirection endpoint.
 *
 * <br />
 * The supported uri template variables are: {baseScheme}, {baseHost}, {basePort},
 * {basePath} and {registrationId}.
 *
 * <br />
 * <b>NOTE:</b> {baseUrl} is also supported, which is the same as
 * {baseScheme}://{baseHost}{basePort}{basePath}.
 *
 * <br />
 * Configuring uri template variables is especially useful when the client is
 * running behind a Proxy Server. This ensures that the X-Forwarded-* headers are
 * used when expanding the redirect-uri.
 * @param redirectUri the uri (or uri template) for the redirection endpoint
 * @return the {@link Builder}
 * @since 5.4
 */
```

Comment (npepinpe) [reply authentication/src/main/java/io/camunda/authentication/config/ClientRegistrationFactory.java:26]: I did think about adding `registrationId`, e.g. `{baseUrl}/sso-callback?id={registrationId}`, however it doesn't seem like we use it anyway.
