### PR TITLE
fix: invalidate ilm policy cache after retention period

### LINKED ISSUE #39134: Historical indices can be missing ILM policies
### 

### 

### 

### 

### Description

Under certain configurations or load conditions, the archiver may continue writing to indices that have been deleted by the ILM policy. This scenario often occurs when the history data retention period is set to a low value (for example, 1 hour) and the archiver is lagging (such as still archiving process instances that completed several hours prior), or the archiver is using the default rollover period of 1 day

When this happens, Elasticsearch automatically recreates the deleted historical index. However, since we have the index in this [cache](https://github.com/camunda/camunda/blob/25f4461a2c1bff3e6d2a21936f7386579288e605/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepository.java#L70-L71), the newly created index will not have the ILM policy applied, causing it to remain in Elasticsearch until the exporter is restarted. At that point, the ILM policy is applied to all historical indices.

### Steps to reproduce

1. Configure the Retention policy to 1 minute
2. Configure `history.waitPeriodBeforeArchiving` to `1m`
3. Complete a first process instance, after 1 minute, the historical indices of the current day are created
4. One minute later, the index is deleted by ES
5. Complete a second process instance, after 1 minute, the historical indices of the current day is re-created

### Current behavior

The historical index is not deleted after the retention period

### Expected behavior

The historical index is deleted after the retention period

### Workaround

Restarting the application triggers the job of applying the ILM on all historical indices

### Environment

SM

### Version

- Component Version: 8.8

### Rootcause

* The cache used to store the indices to which the ILM was applied is now aligned with Elasticsearch state
* Retention period is applied on index lifecycle and not the time since the PI was completed

### Solution ideas

These solutions can be applied an independent way, we can create other issues for the ones that we will apply to fix this bug: 
* make the cache expire after the retention period (since now we have 2 retention policies, the cache expiration time should depend on the used policy for the index)
* make the job that applies the ILM policies to all indices, scheduled every X minutes, and not only run once on exporter opening
* make the ILM policy part of the index templates, to remove this adhoc application of the ILM policy and leave it handled by Elasticsearch
* delete the PIs (and dependent documents) if they are older than the retention period, without reindexing them to the historical index

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

[#inc-weekly-benchmark-es-disk-full](https://camunda.slack.com/archives/C09EECUGCER)

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

Ensure that the index is removed from the `lifeCyclePolicyApplied` cache after the retention period is expired.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

relates to #39134

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java [hunk 1]
```diff
@@ -757,6 +757,57 @@ void shouldCacheIndicesWhichHaveRetentionPolicyAppliedAndNotReapplyPointlessly()
     assertThat(putIndicesSettingsRequest2.index()).containsExactly(indexName1);
   }
 
+  @Test
+  void shouldReapplyILMPolicyAfterRetentionPeriodExpiration() throws Exception {
```
Comment (EuroLew) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/tasks/archiver/ElasticsearchArchiverRepositoryIT.java:761]: ❓ Why do we care to to spy the client and capture the requests. Can't we just
1. set low minimum age
2. apply ilm to index 1.
3. wait for it to expire
4. explicit make a request to remove ilm from index (and verify)
5. call set ilm policy again, if it is expired it will get set, so we know logic works

**Review by EuroLew — COMMENTED** [review]
LGTM just a question about the test

**Comment by houssain-barouni** [comment]
@EuroLew Elasticsearch checks the indices lifecycles every 10 minutes by default https://www.elastic.co/docs/reference/elasticsearch/configuration-reference/index-lifecycle-management-settings 
Meaning we can still have the issue for the following case:
- retention period is 1h
- index is created at 12:00 with the retention policy
- 13:00 the end lifecycle is reached but not checked yet by elasticsearch
- 13:05 new documents are inserted in the index, the cache is reset since > 1h, ILM applied again (no effect)
- 13:10: Elasticsearch deletes the index
- 13:15: new documents are inserted in the index, index recreated, cache is still valid (15 minutes old), so ILM is not applied again 
- 13:20: the archiver does not write anymore to the index, the index remains without ILM

I think for a permanent fix, we need to make this [job](https://github.com/camunda/camunda/blob/main/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ApplyRolloverPeriodJob.java) scheduled every hour or so. WDYT?

**Comment by EuroLew** [comment]
> @EuroLew Elasticsearch checks the indices lifecycles every 10 minutes by default https://www.elastic.co/docs/reference/elasticsearch/configuration-reference/index-lifecycle-management-settings Meaning we can still have the issue for the following case:
> 
> * retention period is 1h
> * index is created at 12:00 with the retention policy
> * 13:00 the end lifecycle is reached but not checked yet by elasticsearch
> * 13:05 new documents are inserted in the index, the cache is reset since > 1h, ILM applied again (no effect)
> * 13:10: Elasticsearch deletes the index
> * 13:15: new documents are inserted in the index, index recreated, cache is still valid (15 minutes old), so ILM is not applied again
> * 13:20: the archiver does not write anymore to the index, the index remains without ILM
> 
> I think for a permanent fix, we need to make this [job](https://github.com/camunda/camunda/blob/main/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks/archiver/ApplyRolloverPeriodJob.java) scheduled every hour or so. WDYT?

makes sense to me, and yea the job can get scheduled it will have essentially 0 performance impact anyway form the request. 👍

**Comment by entangled90** [comment]
you mentioned setting the policy in the template as well in the call, what are the pros and cons of both solutions?

**Comment by EuroLew** [comment]
> you mentioned setting the policy in the template as well in the call, what are the pros and cons of both solutions?

I actually like that idea better, Im pretty sure we don't need runtime changing of ilm policies so if its set in the index template it resolves the race condition, removes the job overhead (which is not super clear to people not familiar with the background tasks)

**Comment by houssain-barouni** [comment]
> you mentioned setting the policy in the template as well in the call, what are the pros and cons of both solutions?

yes, this is one of the solution ideas mentioned here https://github.com/camunda/camunda/issues/39134

In some support cases, we got some scenarios where the runtime index got created from the template. So if the ILM is part of the template, the index will get that and will be deleted after the retention period.
I am not saying this can happen in 8.8, however, we need to be careful with that, because it can be source of data loss

**Review by yohanfernando — APPROVED** [review]
lgtm

**Review by entangled90 — APPROVED** [review]
Thanks for this fix!
Using index templates might be a simpler & more stable solution in the future, but as a quick fix this should be ok.

**Comment by houssain-barouni** [comment]
> Thanks for this fix! Using index templates might be a simpler & more stable solution in the future, but as a quick fix this should be ok.

As explained in https://github.com/camunda/camunda/pull/39137#issuecomment-3365406954, this may not be enough.
I will merge this, then in a second PR, I will make the job applying the ILM policy to all historical indices, scheduled every X minutes (maybe 60 minutes is a good default value). This should make the benchmark scenario more stable.
Then, I will open a new issue to handle this with the index templates solution
