### PR TITLE
1683 fail job error message go

### LINKED ISSUE #1683: With the go client I can fail an job with an error message
see for details #152

### PR DESCRIPTION
**Pull request by menski**
closes #1683

### CODE REVIEW

File: clients/go/commands/failJob_command.go [hunk 1]
```diff
@@ -15,7 +15,12 @@ type FailJobCommandStep1 interface {
 }
 
 type FailJobCommandStep2 interface {
-	Retries(int32) DispatchFailJobCommand
+	Retries(int32) FailJobCommandStep3
+}
+
+type FailJobCommandStep3 interface {
+	DispatchFailJobCommand
+	ErrorMessage(string) FailJobCommandStep3
```
Comment (Zelldon) [inline clients/go/commands/failJob_command.go]: I assume returning `DispatchFailJobCommand` makes more sense?

**Review by ChrisKujawa — COMMENTED** [review]
Looks good thanks :) One small suggestion/question

File: clients/go/commands/failJob_command.go (hunk 1 above)
Comment (menski) [reply clients/go/commands/failJob_command.go]: I decided to return `FailJobCommandStep3` to allow us to add more optional methods in case we need it. Similar to the Java API.

Comment (Zelldon) [reply clients/go/commands/failJob_command.go]: But this is still possible, because Retries returns `FailJobCommandStep3`. The thing is now it is possible to call `ErrorMessage` twice which makes no sense, since the last call will overwrite the first one.

Comment (Zelldon) [reply clients/go/commands/failJob_command.go]: Ok I think I get it. You mean that if you call ErrorMessage you can only call send not new optional parameters which are added. Ja ok lets stay with this solution

**Review by ChrisKujawa — APPROVED** [review]

File: clients/go/commands/failJob_command.go (hunk 1 above)
Comment (menski) [reply clients/go/commands/failJob_command.go]: > The thing is now it is possible to call ErrorMessage twice which makes no sense, since the last call will overwrite the first one.

That is also true for the Java API for all the last steps in the builder pattern. Its not really possible to have optional parameters without allowing them to be called twice or?

Comment (Zelldon) [reply clients/go/commands/failJob_command.go]: I think only with new interfaces.
