### PR TITLE
Broker skips record on processing exception

### LINKED ISSUE #2054: After skipping an event all events corresponding to the workflow instance should also be skipped
With merging #2030 we skip commands and events on error. 

If there is an event after this failing event, which belongs to the same workflow instance this leads to undefined behavior. We need to skip them as well.

For this we could introduce a black list, which contains the workflow instance keys of the failing events.
If an event is read, which belongs to a black listed workflow instance this event should not be processed.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
Updated to the latest changes -> Reopen #2030

> StreamProcessorController skips the corresponding record when an exception was thrown in`#onEvent` or `#processEvent`. The `#updateState` method was removed, since it is not used.
> 
> When an exception/error appears on the command processing in the `TypedStreamProcessor`
> a corresponding command rejection is send and the exception is rethrown such that the `StreamProcessorController` can skip this record.
> 
> An follow up issue #2028 was created to clean up the state, when an exception appears on processing an event. Since we hope/expect that not so many exceptions/errors appear this issue has no high priority, but should be done somehow in the near future.
> 
> I was not sure whether we should also write an command rejection on the log or not, currently I think it makes no real difference (?).
> 
> related to #1988 

closes #2054

### CODE REVIEW

File: broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java [hunk 1]
```diff
@@ -159,16 +162,38 @@ public void wrap(
...
+            position, event, responseWriter, writer, this::setSideEffectProducer);
+      } catch (Exception exception) {
+        final String errorMessage =
+            String.format(PROCESSING_ERROR_MESSAGE, event, exception.getMessage());
+        LOG.error(errorMessage, exception);
+
+        if (event.metadata.getRecordType() == RecordType.COMMAND) {
+          sendCommandRejectionOnException(errorMessage);
+        } else if (event.getMetadata().getRecordType() == RecordType.EVENT) {
+          // TODO(#2028) clean up state
```
Comment (npepinpe) [inline broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java]: Is this still relevant? Aren't we already rolling back the transaction?

File: broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java [hunk 2]
```diff
@@ -159,16 +162,38 @@ public void wrap(
...
+        }
+
+        // re-throw such that stream process controller skips this record
+        throw exception;
```
Comment (npepinpe) [inline broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java]: I would like that we have a mechanism for `StreamProcessor` implementations to specify what to do on error as opposed to catching and rethrowing the exception, but we can implement that later if you think it's more refactoring/outside the scope here.

**Review by npepinpe — CHANGES_REQUESTED** [review]
:tada: 

What are the next steps here? Our end goal is still that we "ignore" instances which have events that we couldn't process. With this PR we will skip "bad" events (and never retry), which doesn't necessarily freeze a "bad" instance. Do we have follow up issues to help us move forward towards that goal?

@menski pinging because I'm not sure if it makes sense to merge this if we aren't going to keep working on the topic if Chris is going to jump on the payload concept next.

File: broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java (hunk 1 above)
Comment (Zelldon) [reply broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java]: It is still, because it is meant to erase the complete instance from the state if the processing is not recoverable, for that we need the distinction between recoverable and non recoverable exception and a retry mechanism on recoverable exceptions.

File: broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java (hunk 2 above)
Comment (Zelldon) [reply broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java]: Yeah would be nice, but I would like to postpone this for now, since we have no real need and is out of scope of this issue. Feel free to create an follow up issue.

**Comment by Zelldon** [comment]
>What are the next steps here? Our end goal is still that we "ignore" instances which have events that we couldn't process. With this PR we will skip "bad" events (and never retry), which doesn't necessarily freeze a "bad" instance. Do we have follow up issues to help us move forward towards that goal?

Blacklisting #2054 , distinction of recoverable and non recoverable #2051  exception and retry mechanism #2052 .  

My Commander told me to do other work :grin:

**Review by npepinpe — CHANGES_REQUESTED** [review]
Last thing would be to add what we discussed, rejecting commands even when there is no response, as it provides some feedback on the stream at least.

**Comment by Zelldon** [comment]
Hey @npepinpe would be nice if you could take a look at the latest commits. Commands rejections are written to the log and workflow instance events are black listed.

File: logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java [hunk 3]
```diff
@@ -294,9 +294,16 @@ private void processEvent(final LoggedEvent event) {
...
-        actor.runUntilDone(this::executeSideEffects);
+        try {
+          zeebeDb.transaction(eventProcessor::processEvent);
+          metrics.incrementEventsProcessedCount();
+          actor.runUntilDone(this::executeSideEffects);
+        } catch (final Exception e) {
+          LOG.error(ERROR_MESSAGE_PROCESSING_FAILED_SKIP_EVENT, getName(), event, e);
+          zeebeDb.transaction(() -> eventProcessor.processingFailed(e));
+          // send rejection etc
+          actor.runUntilDone(this::executeSideEffects);
```
Comment (npepinpe) [inline logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java]: Is there a risk that we also execute side effects such as sending a `CORRELATE` message command, or other undesirable things?

File: broker-core/src/test/java/io/zeebe/broker/logstreams/processor/SkipFailingEventsTest.java [hunk 4]
```diff
@@ -0,0 +1,215 @@
...
+                                ValueType.WORKFLOW_INSTANCE,
+                                WorkflowInstanceIntent.ELEMENT_COMPLETED))
+                    .findFirst())
+        .until(o -> o.isPresent())
+        .get();
+
+    doRepeatedly(() -> {}).until(o -> processor.getProcessCount() > 0);
+
+    // then
+    final TypedEventImpl typedEvent = new TypedEventImpl();
```
Comment (npepinpe) [inline broker-core/src/test/java/io/zeebe/broker/logstreams/processor/SkipFailingEventsTest.java]: You can also use `MockTypedRecord` which lets you just set the properties instead of wrapping the impl.

File: broker-core/src/main/java/io/zeebe/broker/logstreams/state/ZeebeState.java [hunk 5]
```diff
@@ -92,4 +96,21 @@ public IncidentState getIncidentState() {
   public KeyGenerator getKeyGenerator() {
     return keyState;
   }
+
+  public BlackList getBlackList() {
```
Comment (npepinpe) [inline broker-core/src/main/java/io/zeebe/broker/logstreams/state/ZeebeState.java]: Is this used only for testing? Are the `blacklist` and `isOnBlacklist` methods not enough?

File: broker-core/src/main/java/io/zeebe/broker/logstreams/state/BlackList.java [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+  private final ColumnFamily<DbLong, DbNil> blackListColumnFamily;
+  private final DbLong workflowInstanceKey;
+
+  public BlackList(ZeebeDb<ZbColumnFamilies> zeebeDb) {
+    workflowInstanceKey = new DbLong();
+    blackListColumnFamily =
+        zeebeDb.createColumnFamily(ZbColumnFamilies.BLACKLIST, workflowInstanceKey, DbNil.INSTANCE);
+  }
+
+  public void blacklist(TypedRecord<WorkflowInstanceRecord> workflowInstance) {
```
Comment (npepinpe) [inline broker-core/src/main/java/io/zeebe/broker/logstreams/state/BlackList.java]: Instead of having to pass an unchecked record, why not just here ask for the workflow instance key directly? After all the black list is (at least for now) a workflow instance black list, nothing else. We can always change that later.

File: broker-core/src/test/java/io/zeebe/broker/logstreams/processor/SkipFailingEventsTest.java [hunk 7]
```diff
@@ -0,0 +1,215 @@
...
+                        e ->
+                            Records.isEvent(
+                                e,
+                                ValueType.WORKFLOW_INSTANCE,
+                                WorkflowInstanceIntent.ELEMENT_COMPLETED))
+                    .findFirst())
+        .until(o -> o.isPresent())
+        .get();
+
+    doRepeatedly(() -> {}).until(o -> processor.getProcessCount() > 0);
```
Comment (npepinpe) [inline broker-core/src/test/java/io/zeebe/broker/logstreams/processor/SkipFailingEventsTest.java]: Is it necessary to do `doRepeatedly`? Since the previous check for `ELEMENT_COMPLETED` should only happen if the last event was processed, then we must have processed the error prone processor's event, so we could just check if the process count == 1.

**Review by npepinpe — CHANGES_REQUESTED** [review]
I like that we moved the key generator on the state, though I'm not sure about passing the state to the more generic `TypedStreamProcessor`, when this is more a feature of the workflow stream processor. That said, our workflow stream processor is the only `TypedStreamProcessor`, so maybe it's more that that abstraction doesn't really make sense anymore 😅 Anyway, I think for first step its fine to have this behavior be in `TypedStreamProcessor`, and either we one day collapse the whole abstraction into a `WorkflowStreamProcessor` (instead of building a workflow stream processor from a generic `TypedStreamProcessor`), or we have more typed stream processors and we move this behavior out.

Otherwise see the comments, the main one for me is the one related to executing side effects even on error. We can also discuss it f2f later when I'm in the office.

File: logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java (hunk 3 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java]: It will not since it is rested in the processingFailed

File: broker-core/src/main/java/io/zeebe/broker/logstreams/state/BlackList.java (hunk 6 above)
Comment (Zelldon) [reply broker-core/src/main/java/io/zeebe/broker/logstreams/state/BlackList.java]: can do

File: broker-core/src/test/java/io/zeebe/broker/logstreams/processor/SkipFailingEventsTest.java (hunk 7 above)
Comment (Zelldon) [reply broker-core/src/test/java/io/zeebe/broker/logstreams/processor/SkipFailingEventsTest.java]: Was more an wip

**Comment by Zelldon** [comment]
@npepinpe added an fixup commit

**Review by npepinpe — APPROVED** [review]
:tada: 

Before closing the related issue, can you write-up in there basically how it works now? So other people also know (e.g. we only blacklist based on `WorkflowInstanceRecord`, not `JobRecord`, etc.)

**Review by npepinpe — CHANGES_REQUESTED** [review]
Actually, I'm afraid I have to go back on what I'd said :see_no_evil: 

We should blacklist a workflow instance if either a command or an event (not just `WorkflowInstanceRecord`) fails, such that workflow execution is as predictable as possible. We can discuss it more tomorrow if you want.

**Comment by Zelldon** [comment]
Could you elaborate on that? It is not really clear for me what you mean? What is missing in your opinion? Would be nice if you just write it down. I want to get this thing done.

For me it makes no sense to blacklist the wf instance on commands.

**Comment by npepinpe** [comment]
Essentially, it's easier and safer for a user to say that if there is an error in the processing of the workflow instance, it completely stops, as opposed to maybe it continues depending on which event/command failed. 

For example, if I have a task with a timer boundary event, and my timer fails to be created, then the workflow instance being executed does not conform to what I defined. I think predictability in this case is more important that having an escape hatch for, say, if your job fails to complete.

**Comment by Zelldon** [comment]
@npepinpe hey please have a look at the latest changes. I also rebased the PR to the latest develop.

File: broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java [hunk 8]
```diff
@@ -159,16 +169,61 @@ public void wrap(
...
+
+      final Intent intent = event.getMetadata().getIntent();
+      if (isWorkflowInstanceRelated(intent)) {
+        if (shouldBeBlacklisted(intent)) {
+          zeebeState.blacklist(event);
+        }
+      }
+    }
+
+    private boolean shouldBeBlacklisted(Intent intent) {
```
Comment (npepinpe) [inline broker-core/src/main/java/io/zeebe/broker/logstreams/processor/TypedStreamProcessor.java]: Can we enforce here that the argument is `WorkflowInstanceRelatedIntent`? In case someone ever calls this and expects us to do the check here. So the caller has to check and cast. 

Or merge both `isWorkflowInstanceRelated` and `shouldBeBlacklisted`, whichever you prefer.

File: broker-core/src/test/java/io/zeebe/broker/logstreams/processor/BlacklistInstanceTest.java [hunk 9]
```diff
@@ -0,0 +1,288 @@
...
+      {ValueType.JOB, JobIntent.CREATE, true},
+      {ValueType.JOB, JobIntent.CREATED, true},
+      {ValueType.JOB, JobIntent.ACTIVATED, true},
+      {ValueType.JOB, JobIntent.COMPLETED, true},
+      {ValueType.JOB, JobIntent.TIMED_OUT, true},
+      {ValueType.JOB, JobIntent.FAILED, true},
+      {ValueType.JOB, JobIntent.RETRIES_UPDATED, true},
+      {ValueType.JOB, JobIntent.CANCEL, true},
+      {ValueType.JOB, JobIntent.CANCELED, true},
+      {ValueType.JOB, JobIntent.TIME_OUT, false},
```
Comment (npepinpe) [inline broker-core/src/test/java/io/zeebe/broker/logstreams/processor/BlacklistInstanceTest.java]: Didn't we end up saying time out should blacklist as well? I think it's better to be conservative here initially, and we can always change them easily later.

**Review by npepinpe — CHANGES_REQUESTED** [review]
Looks good. I would initially blacklist `Job.TIME_OUT`, even if it seems unnecessarily strict; I'd rather be too conservative initially, and we can make it more lenient with time. Otherwise everything is good!

File: broker-core/src/test/java/io/zeebe/broker/logstreams/processor/BlacklistInstanceTest.java (hunk 9 above)
Comment (Zelldon) [reply broker-core/src/test/java/io/zeebe/broker/logstreams/processor/BlacklistInstanceTest.java]: No the other 2 we talked about (Job.ACTIVATED and Job.CANCEL), but Time_out we thought that we should not blacklist it, because you can then still complete or fail the task (which I would like to have). But I can do it for now more strict.

**Comment by npepinpe** [comment]
Yeah, I can't think of a better argument then predictability in the case of an error; if you're sure that it's safe you can leave it as is.

**Review by npepinpe — APPROVED** [review]
