### PR TITLE
Camunda exporter flush failure type metric

### LINKED ISSUE #34737: Camunda exporter [flush failure type]
Description: When a bulk request is flushed for the exporter there may be partial failures, this would document the error type.

Metrics needed:
- [flush_exceptions_total] - Track the exceptions from all flush results, different exceptions will be tracked using labels.

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

When a bulk request is flushed it can partially or completely fail, when it does it sends back error objects per item in the bulk request, we now track all error types that are returned, this enables the narrowing down of errors.

Here is a snapshot to see the title, description, query https://snapshots.raintank.io/dashboard/snapshot/j85fGg1DBPDMYhp02KzniFBL3sYn58xg

Here is an image of what it looks like 
image

## Related issues

closes #34737

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/OpensearchBatchRequest.java [hunk 1]
```diff
@@ -35,6 +36,7 @@ public class OpensearchBatchRequest implements BatchRequest {
   private final OpenSearchClient osClient;
   private final BulkRequest.Builder bulkRequestBuilder;
   private final OpensearchScriptBuilder scriptBuilder;
+  private CamundaExporterMetrics metrics;
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/OpensearchBatchRequest.java:39]: 🔧 can also be final?

**Review by RomanJRW — APPROVED** [review]
Nice improvement 👍

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/OpensearchBatchRequest.java (hunk 1 above)
Comment (EuroLew) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/OpensearchBatchRequest.java:39]: no it can't be set it's done using a setter, if I made it final it would need to be part of the constructor and it would require far more sweeping changes to interfaces and classes, Ideally we like immutable objects but I think it's a good trade off.
