### PR TITLE
Fix race condition in random replay test

### LINKED ISSUE #6710: ProcessExecutionRandomizedPropertyTest shouldExecuteProcessToEnd fails
**Summary**

- How often does the test fail? - once
- Does it block your work? - no
- Do we suspect that it is a real failure? - no idea

**Failures**
 
shouldExecuteProcessToEnd[TestDataRecord{processSeed=8364364902926438369, executionPathSeed=-9118484849103666056}] – ProcessExecutionRandomizedPropertyTest(java-testrun)

https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/143

See logs below.

**Logs**

<details><summary>Logs</summary>
<pre>
```
Stacktrace
io.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:72)
	at io.zeebe.engine.util.ProcessExecutor.waitForJobToBeCreated(ProcessExecutor.java:174)
	at io.zeebe.engine.util.ProcessExecutor.activateAndCompleteJob(ProcessExecutor.java:85)
	at io.zeebe.engine.util.ProcessExecutor.applyStep(ProcessExecutor.java:54)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at io.zeebe.engine.processing.streamprocessor.ProcessExecutionRandomizedPropertyTest.shouldExecuteProcessToEnd(ProcessExecutionRandomizedPropertyTest.java:73)
	at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:199)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:193)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Standard Output
10:46:09.757 [Broker-0-LogStream-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
10:46:09.828 [Broker-0-StreamProcessor-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
10:46:09.828 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@320b4806)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@3cccb037, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@38f32376, configuration: Configuration(false)]
10:46:09.829 [Broker-0-StreamProcessor-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
10:46:09.829 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@7df1ba0c)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@15d296cc, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@4c46c149, configuration: Configuration(false)]
10:46:09.830 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@6d8fb324)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@1dde4543, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@1cbbd4c2, configuration: Configuration(false)]
10:46:09.840 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@625ecc24)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@6e61115e, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@46b63073, configuration: Configuration(false)]
10:46:14.853 [] INFO  io.zeebe.test - Test failed, following records were exported:
10:46:14.991 [] INFO  io.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DEPLOYMENT CREATE      - #1->-1 -1 - process.xml
E PROC       CREATED     - #2->#1 K1 - process.xml->"process_id_1" (version:1)
C TIMER      CREATE      - #3->#1 -1 -  @"id_2"[-1]  in <process "K1"[-1]> due T11:08:09.849
E DEPLOYMENT CREATED     - #4->#1 K2 - process.xml
E DEPLOYMENT FULLY_DISTR - #5->#1 K2 - 
E TIMER      CREATED     - #6->#3 K3 -  @"id_2"[-1]  in <process "K1"[-1]> due T11:08:09.849
--------
Decomposed keys (for debugging):
-1 <-> -1
K1 <-> 2251799813685249
K2 <-> 2251799813685250
K3 <-> 2251799813685251
10:46:14.994 [] DEBUG io.zeebe.util.buffer - Close stream processor
10:46:14.994 [Broker-0-StreamProcessor-1] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
10:46:15.037 [Broker-0-LogStream-1] INFO  io.zeebe.logstreams - Close appender for log stream stream-1
10:46:15.037 [stream-1-write-buffer] DEBUG io.zeebe.dispatcher - Dispatcher closed
10:46:15.037 [Broker-0-LogStream-1] INFO  io.zeebe.logstreams - On closing logstream stream-1 close 2 readers
10:46:15.037 [] DEBUG io.zeebe.broker.test - Clean up test files on path /tmp/junit3817538301076002345
10:46:15.038 [] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
10:46:15.038 [] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-actors'
10:46:15.039 [] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
10:46:15.039 [] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
10:46:15.039 [] INFO  io.zeebe.engine.processing.streamprocessor.FailedPropertyBasedTestDataPrinter - Data of failed test case: TestDataRecord{processSeed=8364364902926438369, executionPathSeed=-9118484849103666056}
10:46:15.042 [] INFO  io.zeebe.engine.processing.streamprocessor.FailedPropertyBasedTestDataPrinter - Process(es) of failed test case:

10:46:15.067 [] INFO  io.zeebe.engine.processing.streamprocessor.FailedPropertyBasedTestDataPrinter - Execution path of failed test case:
StepTriggerTimer[timeToAdd=PT22M,variables={}]
StepActivateAndCompleteJob[jobType=id_2_variables,variables={correlationKey=default_correlation_key}]
StepPublishMessage[correlationKeyValue=default_correlation_key,messageName=message_id_0,variables={correlationKey=default_correlation_key}]

```
</pre>
</details>

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes a potential race condition with timer start event where we increased the clock before the timer was created. We now wait for the the Timer.CREATE has been processed and its state changes applied, since we're guaranteed at that point that the timer has been scheduled.

Adds new helper in ProcessExecutor to await until a record has been processed, helping avoid race conditions with things such as timer scheduling Additionally await until the TRIGGER command has been processed, as otherwise there may be a race condition in certain tests (e.g. ReplayStateTest) where we want to apply the step and then stop the engine at the next wait state. It could be that we immediately think we're in a wait state BEFORE the timer is actually triggered if we don't wait for the command to be processed, and thus have different processing/reprocessing states.

Adds a new helper in TestStreams to get the last processed position for a given log.

## Related issues

closes #6710 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/test/java/io/zeebe/engine/util/ProcessExecutor.java [hunk 1]
```diff
@@ -225,6 +229,15 @@ private void createProcessInstance(final StepStartProcessInstance startProcess)
...
 
   private void triggerTimer(final StepTriggerTimer timerStep) {
+    final Record<TimerRecordValue> timerRecord =
+        RecordingExporter.timerRecords(TimerIntent.CREATED)
+            .withHandlerNodeId(timerStep.getTargetElementId())
+            .getFirst();
+
+    Awaitility.await(
+            "until timer " + timerStep.getTargetElementId() + " has created has been created")
+        .until(() -> engineRule.getLastWrittenPosition(1) >= timerRecord.getPosition());
```
Comment (saig0) [inline engine/src/test/java/io/zeebe/engine/util/ProcessExecutor.java:239]: Here, we wait until the stream processor written the `created` event of the timer. But the timer is scheduled as a side effect that is called after the `lastWrittenPosition` is updated.
So, there is still the chance of a race condition. 

We could use the [callbacks](https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/test/java/io/zeebe/engine/util/EngineRule.java#L91-L92) of the `EngineRule` (i.e. `onProcessed`/`onSkipped`) to be sure that the side effects are called before.
As suggested by Peter, we could expose the last processed position as a getter on the `EngineRule`.

**Review by saig0 — CHANGES_REQUESTED** [review]
@npepinpe thanks :icecream: 
But I think this doesn't solve the problem completely :smiling_imp:

File: engine/src/test/java/io/zeebe/engine/util/ProcessExecutor.java (hunk 1 above)
Comment (npepinpe) [reply engine/src/test/java/io/zeebe/engine/util/ProcessExecutor.java:239]: Sorry, I meant to use last processed :see_no_evil: I trusted my auto complete too much :sweat_smile:

**Comment by npepinpe** [comment]
Ah, sorry, I squashed and totally forgot that it would not let you see the new changes since your last review :see_no_evil:

File: engine/src/test/java/io/zeebe/engine/util/StreamProcessorRule.java [hunk 2]
```diff
@@ -181,6 +181,10 @@ public MutableZeebeState getZeebeState() {
     return streamProcessingComposite.getZeebeState();
   }
 
+  public long getLastProcessedPosition(final int partitionId) {
```
Comment (npepinpe) [inline engine/src/test/java/io/zeebe/engine/util/StreamProcessorRule.java:184]: I added this instead of reusing getLastSuccessfulProcessRecordPosition because, well, I'm not sure why that one is there in the first place :sweat_smile: If I read correctly, if you have multiple partitions, the zeebeState is that of the last started one? I think it's a confusing API imo, but I also didn't want to refactor everything.

File: engine/src/test/java/io/zeebe/engine/util/TestStreams.java [hunk 3]
```diff
@@ -164,6 +164,10 @@ public long getLastWrittenPosition(final String name) {
     return getLogStream(name).getCommitPosition();
   }
 
+  public long getLastProcessedPosition(final String name) {
+    return getStreamProcessor(name).getLastProcessedPositionAsync().join();
+  }
```
Comment (saig0) [inline engine/src/test/java/io/zeebe/engine/util/TestStreams.java:169]: Nice try but nope :sweat_smile: 

The last processed position is also set **before** the side effects are called. And it doesn't work for records that are not processed (i.e. events are skipped). (see https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/main/java/io/zeebe/engine/processing/streamprocessor/ProcessingStateMachine.java#L426)

Instead, the [callbacks](https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/main/java/io/zeebe/engine/processing/streamprocessor/ProcessingStateMachine.java#L456) are invoked after the event is processed completely. And, also for skipped records. Please have a look at them. We use these callback already in the [replay property test](https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/test/java/io/zeebe/engine/processing/streamprocessor/ReplayStateRandomizedPropertyTest.java#L46-L49).

**Review by saig0 — CHANGES_REQUESTED** [review]
You shall not pass :mage_man:

File: engine/src/test/java/io/zeebe/engine/util/TestStreams.java (hunk 3 above)
Comment (npepinpe) [reply engine/src/test/java/io/zeebe/engine/util/TestStreams.java:169]: You're totally right, callbacks are the only way to really know that the side effects have been performed. I really should spend more time in the engine :sweat_smile: 

I've added that you can chain multiple callbacks and changed the wait method to use that. The reason for chaining is that this is kind of a requirement for the `ProcessExecutor`, and as its also used in at least one other test which does not need a callback, I figured we should just allow that instead of passing a supplier to it.

I wasn't sure if the property should be volatile, as I guess it may be set by a different thread than the one running the test - it's probably fine as we don't rely too much on its actual value and just use it as a trigger that X has happened, but if we ever do want to do something with the value then the poll may return but then when we read it it may be an older value? Am I overthinking this? :thinking:

**Review by saig0 — APPROVED** [review]
Looks good now :tada:

File: engine/src/test/java/io/zeebe/engine/util/TestStreams.java (hunk 3 above)
Comment (saig0) [reply engine/src/test/java/io/zeebe/engine/util/TestStreams.java]: I think it is okay for now :sweat_smile:
