### PR TITLE
fix: NPE when migrating call activities with missing called element incident

### LINKED ISSUE #41846: `NullPointerException` in `ProcessInstanceMigrationMigrateProcessor#adjustCalledInstancesTreePath`
[Error](https://console.cloud.google.com/errors/detail/COrx3PfH0NVA;service=zeebe;time=P7D;locations=global?project=camunda-saas-int):
```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=PROCESS_INSTANCE_MIGRATION, intent=MIGRATE, authorization={"format":"UNKNOWN","authData":"***","claims":"***"}, batchOperationReference=2251799814898427}, value={"processInstanceKey":2251799814894258,"targetProcessDefinitionKey":2251799814896041,"mappingInstructions":[{"sourceElementId":"Gateway_Split","targetElementId":"Gateway_Split"},{"sourceElementId":"Task_Decision","targetElementId":"Task_Decision"},{"sourceElementId":"Task_CallActivity","targetElementId":"Task_CallActivity"},{"sourceElementId":"Task_IOMapping","targetElementId":"Task_IOMapping"},{"sourceElementId":"Gateway_Expression","targetElementId":"Gateway_Expression"},{"sourceElementId":"Task_E_Bad","targetElementId":"Task_E_Bad"},{"sourceElementId":"Task_E_Good","targetElementId":"Task_E_Good"},{"sourceElementId":"Gateway_E_Join","targetElementId":"Gateway_E_Join"},{"sourceElementId":"Gateway_Merge","targetElementId":"Gateway_Merge"},{"sourceElementId":"Flow_A_Merge","targetElementId":"Flow_A_Merge"},{"sourceElementId":"Flow_B_Merge","targetElementId":"Flow_B_Merge"},{"sourceElementId":"Flow_D_Merge","targetElementId":"Flow_D_Merge"},{"sourceElementId":"Flow_E_Merge","targetElementId":"Flow_E_Merge"}]}}' without errors, but exception occurred with message 'null'.
```

Stacktrace:
```
java.lang.NullPointerException
	at java.base/java.util.ArrayDeque.addLast(Unknown Source)
	at java.base/java.util.ArrayDeque.add(Unknown Source)
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceMigrationMigrateProcessor.adjustCalledInstancesTreePath(ProcessInstanceMigrationMigrateProcessor.java:573)
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceMigrationMigrateProcessor.migrateCalledSubProcessElements(ProcessInstanceMigrationMigrateProcessor.java:533)
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceMigrationMigrateProcessor.tryMigrateElementInstance(ProcessInstanceMigrationMigrateProcessor.java:466)
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceMigrationMigrateProcessor.processRecord(ProcessInstanceMigrationMigrateProcessor.java:187)
	at io.camunda.zeebe.engine.Engine.process(Engine.java:179)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:373)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:281)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:128)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:281)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:239)
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:84)
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:43)
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127)
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104)
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224)
```

This should not happen, it either needs to be handled graciously if this is to be expected or we need to fix a bug.

### PR DESCRIPTION
**Pull request by konstantinos-mylosis**
## Description
Fix NPE when migrating call activities with incident `CALLED_ELEMENT_ERROR` -- called element process id not deployed
Based on discussion [here](https://camunda.slack.com/archives/C08MRKHJ0CD/p1764595924546799)

2 cases covered:
- 1 PI with 1 Call Activity - Incident work/migrated if Called element process id not deployed yet 
  -  ✅ IncidentIntent.MIGRATED
- 1 PI with 2 Subsequent child Call Activities - Incident exists on last child
  -  ✅ ProcessInstanceIntent.ANCESTOR_MIGRATED
  - Incident not migrated since it is not a direct migration, it is an ancestor one

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #41846

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateCallActivityTest.java [hunk 1]
```diff
@@ -602,4 +605,209 @@ public void shouldReflectChangesInCallingElementPath() {
...
+            RecordingExporter.processInstanceMigrationRecords(
+                    ProcessInstanceMigrationIntent.MIGRATED)
+                .withProcessInstanceKey(processInstanceKey)
+                .exists())
+        .describedAs("Expect that process instance is migrated")
+        .isTrue();
+  }
+
+  @Test
+  public void shouldMigrateSubsequentCallActivitiesWithIncident() {
```
Comment (mustafadagher) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateCallActivityTest.java:695]: 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateCallActivityTest.java [hunk 2]
```diff
@@ -602,4 +605,209 @@ public void shouldReflectChangesInCallingElementPath() {
             parentProcessDefinitionKey, targetProcessDefinitionKey, level2ChildProcessDefinitionKey)
         .hasOnlyCallingElementPath(0, 1);
   }
+
+  @Test
+  public void shouldMigrateCallActivityWithIncident() {
```
Comment (mustafadagher) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateCallActivityTest.java:610]: 👍

**Review by mustafadagher — APPROVED** [review]
Thanks @konstantinos-mylosis for the fix, All looks good to me!
