### PR TITLE
fix: remove the job reference from the element instance on job completed

### LINKED ISSUE #33237: Process execution listener jobs are not cleaned up correctly
### 

### 

### 

### 

### Description

Execution listener jobs are not correctly cleaned up from the Element Instance that the job is scoped to.

For the `START` execution listener on a `PROCESS`, this means that the Element Instance continues to reference a job that no longer exists after the execution listener job was completed.

This can prevent the migration of this process instance, because of a safety check that fails when the migrator encounters the job reference but can't find the associated job. To prevent wrongful migration, it rejects the command and informs:

> Command 'MIGRATE' rejected with code 'PROCESSING_ERROR': Expected to migrate a job for process instance with key '2251799823947432', but could not find job with key '2251799823947433'. Please report this as a bug

### Steps to reproduce

1. deploy a process with a START execution listener and a task 
2. create an instance and complete the execution listener
3. await the process to reach the task
4. try to migrate the process instance to another process definition
5. notice the rejection message

### Current behavior

The following behavior is known: 
- The process instance refers to a no longer existing job by key.
- Process instance migration attempts of such a process instance are rejected.

### Expected behavior

- The process instance should no longer refer to the completed job.
- Process instance migration attempts of such a process instance should be allowed, but the failed migration attempt of the missing job should be logged as warning.

### Environment

SaaS & SM

### Version

- Component Version: 8.6+

### Rootcause

Jobs have a reference to the element instance that they belong to, and element instances have a similar back reference.

When a job is created, the element instance is updated to reference this job.

https://github.com/camunda/camunda/blob/86e8f2f5c8d2214280753dc4540bb7fff69ea342/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/JobCreatedApplier.java#L39-L48

Likewise, when a job is completed, the element instance needs to be updated to remove this reference to the completed job. However, that is limited to element instances with an active flowscope:

https://github.com/camunda/camunda/blob/86e8f2f5c8d2214280753dc4540bb7fff69ea342/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/JobCompletedApplier.java#L35-L43

However, a process instance doesn't have a flowscope.

So, when the job of a `START` execution listener at the `PROCESS` level is created, then the process instance is updated to reference this job. However, when that job is completed, the reference is not removed from the process instance, because it doesn't have a flowscope.

### Solution ideas

- Register a new `JobCompletedApplier` version that clears the relevant job key regardless of the flow scope's state
- Adjust the `ProcessInstanceMigrationMigrateProcessor` to allow migrating the process instance if it can't find the job belonging to an element instance, and instead log the case as a warning.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

- [#inc-support-26664-process-migration-not-work-process-not-found](https://camunda.slack.com/archives/C08QJ0A9GGH)

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description
This PR fixes a bug by removing the job reference from an element instance on job completed and ensures process instance migration works correctly by adding a regression test.  
- Created a new `JobCompletedV2Applier` that removes the job key reference from the element instance whether or not it has an (active) flowscope instance
- Added a regression test to verify that a process instance migrates correctly after a start execution listener is completed.  

## Related issues

closes #33237

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceRegressionTest.java [hunk 1]
```diff
@@ -101,4 +102,55 @@ public void shouldResolveIncidentAfterMigratingActivatingElementWithMessageBound
...
+    // when
+    ENGINE.job().ofInstance(processInstanceKey).withType(startELType).complete();
+
+    ENGINE
+        .processInstance()
+        .withInstanceKey(processInstanceKey)
+        .migration()
+        .withTargetProcessDefinitionKey(targetProcessDefinitionKey)
+        .addMappingInstruction("A", "B")
+        .migrate();
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceRegressionTest.java:146]: 🔧 You need to await the service task to be created otherwise the migration could sometimes fail

**Review by korthout — APPROVED** [review]
Nice work @mustafadagher 🚀 

🔧 Just one change request

💭 Next time please first commit a copy of the applier to the new version, and in another commit make the changes. Otherwise, to review the changes, I need to compare files.
