### PR TITLE
chore(engine): fix flaky StreamProcessorTest snapshot tests

### LINKED ISSUE #4202: StreamProcessorTest#shouldCreateSnapshotAfterInterval is flaky
**Description**

It seems the test sometimes is too fast and does not wait for the event to have been processed - or there is a bug. But I verified that the way we await processing is race-prone (is that correct to say? :sweat_smile:), so I think it is flaky.

Sample output:

```
Error
expected:<[tru]e> but was:<[fals]e>
Stacktrace
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:91)
	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)
	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
	at io.zeebe.engine.processor.StreamProcessorTest.shouldCreateSnapshotsAfterInterval(StreamProcessorTest.java:644)
```

From the output logs we can see that it skipped taking a snapshot because we were still on processed position -1.

```
16:50:52.220 [Broker-0-StreamProcessor-0] INFO  io.zeebe.logstreams - Recovered state of partition 0 from snapshot at position -1
16:50:52.250 [Broker-0-SnapshotDirector-0] DEBUG io.zeebe.logstreams.snapshot - We will skip taking this snapshot, because we haven't processed something yet.
```

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR updates tests in `StreamProcessorTest` where we wanted to wait for one event to be processed, but were actually waiting for one event to appear on the log; this usually coincided, but not 100% of the time. It replaces checking the event count on the stream with actually awaiting that we have processed this event; there was a race condition where the event count might be incremented before the processor had processed, resulting in non-deterministic tests.

## Related issues

Closes #4202, #4010 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java [hunk 1]
```diff
@@ -578,16 +587,25 @@ public void onRecovered(final ReadonlyProcessingContext context) {
   }
 
   @Test
-  public void shouldCreateSnapshotsEvenIfNoProcessorProcessEvent() {
+  public void shouldCreateSnapshotsEvenIfNoProcessorProcessEvent() throws InterruptedException {
```
Comment (deepthidevaki) [inline engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java:590]: I did not understand the intention of this test. The name says no processor process event, but there is a processor processing the event. :thinking:

Comment (npepinpe) [reply engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java:590]: The name is misleading, true; what it means is that between an open/close of the processor, even if we didn't process an event, on close we still snapshot.

You can see we process the event then close, then re-open the processor. This is because we don't take snapshots if we have never processed anything (i.e. if the last processed position is -1) - to support "empty" snapshots (e.g. index -1), we'd need to refactor Atomix more, so skipping at -1 seemed simpler. We can challenge that.

In the mean time, we can find a better name, any ideas?

Comment (deepthidevaki) [reply engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java:590]: It sounds like `shouldNotCreateSnapshotIfNoProcessorProcessEvent()`.

Comment (npepinpe) [reply engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java:590]: But we want to test that it does create one :sweat_smile: Let's just quickly clear it up on Zoom

File: engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java [hunk 2]
```diff
@@ -731,31 +693,56 @@ public void processRecord(
...
+      lastProcessedRecord = typedRecord;
+    }
+
+    private AwaitableProcessedListener expect(final int expectedCount) {
+      expectedPhase = phaser.bulkRegister(expectedCount);
+      return this;
+    }
+
+    private void await() throws TimeoutException, InterruptedException {
+      Loggers.LOGSTREAMS_LOGGER.info("Expected phase: {}", expectedPhase);
```
Comment (deepthidevaki) [inline engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java:744]: This log statement can be removed.

**Review by deepthidevaki — APPROVED** [review]
Thanks :+1: 

Just one question. Isn't using Phaser a bit of overkill? Why not just use CountDownLatch?

File: engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java (hunk 2 above)
Comment (npepinpe) [reply engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java:744]: Oops, yes :see_no_evil:

**Comment by npepinpe** [comment]
I went for a phaser because it's a reusable concurrency primitive, but admittedly:

1. Not everybody is familiar with phasers
1. It is only using a subset of the capabilities of a phasers

And more importantly, you could just use multiple latches here. So I'll switch over to that as it's easier to understand, I think :+1: (with the only downside that a latch will let you count down forever, whereas a phaser expects a specific number of parties - but I think here that's not all that important).

**Review by deepthidevaki — APPROVED** [review]
:+1:
