### PR TITLE
fix: show decision instance key & incident key in batch items table

### LINKED ISSUE #45988: Details page does not show affected item key for certain batch operation types
### 

### 

### 

### 

### Description

The Details page for batch operations does not properly display the key for items of certain batch operation types. In particular, for `DELETE_DECISION_INSTANCE` and `RESOLVE_INCIDENT` types, the affected item key is not shown, leading to a gap for users in identifying what is being operated on.

### Steps to reproduce

1. Create a batch operation of type DELETE_DECISION_INSTANCE and another of type RESOLVE_INCIDENT
2. Open the Details page for each batch operation in Operate
3. Observe the columns displayed for the affected items
4. Note the keys displayed and whether they correspond to the right entity (decision instance or incident)

### Current behavior

For DELETE_DECISION_INSTANCE, the Details page shows process instance key as -1 AND displays no information about the affected decision instance. 

For RESOLVE_INCIDENT, there is also no column or information displaying the affected incident key, but it does always show the process instance key that the incident exists/existed in.

### Expected behavior

A new column should be added to the Details page for batch operation items, using the itemKey property:

- For DELETE_DECISION_INSTANCE, show a column "Decision instance key" (link to decision instance page if not -1; otherwise, show "No decision instance"). If process instance key is -1, show "No process instance" in the "Process instance key" column.
- For RESOLVE_INCIDENT, show a column "Incident key" (no link needed; show "No incident" if key is -1)
- For other types, the column does not have to displayed.

This ensures users know exactly which item is affected by each operation.

### Workaround

None

### Environment

SaaS & SM

### Version

- 8.9-alpha4

### Rootcause

_No response_

### Solution ideas

- Update Details page table rendering logic to check batch operation type and display the itemKey in the correct column as described above.
- For DELETE_DECISION_INSTANCE, render link to decision instance when key != -1; otherwise, show friendly empty label.
- For RESOLVE_INCIDENT, conditionally show incident key or friendly empty label.

### Dev -> QA handover

_No response_

### Links

Related: #41678
User discussion and context in project breakdown.

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by OmranAbazid**
## Description

This PR adds support for displaying item keys in the batch operations details page for `DELETE_DECISION_INSTANCE` and `RESOLVE_INCIDENT` operation types, addressing issue #45988. Previously, these operation types didn't properly display the affected item keys, making it difficult for users to identify which entities were being operated on.

To make this work, i had to do the following:
* Update the zod schema to include `DELETE_DECISION_INSTANCE`
* Extend the decision instance page to display `not found` error. This is useful when the user clicks on a decision instance batch item link.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #45988

### CODE REVIEW

File: operate/client/src/App/BatchOperation/BatchItemsTable.tsx [hunk 1]
```diff
@@ -13,20 +13,68 @@ import {useBatchOperationItems} from 'modules/queries/batch-operations/useBatchO
...
+];
+
+const DELETE_DECISION_INSTANCE_HEADER_COLUMNS = [
+  {
+    key: 'decisionInstanceKey',
+    header: 'Decision Instance Key',
+    isDisabled: true,
+  },
+  ...COMMON_HEADER_COLUMNS,
+];
```
[the remark this answers is not in the document]
Comment (OmranAbazid) [reply operate/client/src/App/BatchOperation/BatchItemsTable.tsx:36]: @korthout is the issue description outdated? 
As far as i understood from the slack descussion that we should omit the process instance column for decision instance deletion and omit the decision instance column for all other operation types.

I however have a fallback to `No process instance / No decision instance / No incident` if i ever recieve a value of `-1 `  

Let me know any further change is needed.

[the remark this answers is not in the document]
Comment (korthout) [reply operate/client/src/App/BatchOperation/BatchItemsTable.tsx:36]: No decision instances may be related to a process instance, e.g. Through business rule task. So it depends per decision instance. But I'm okay with either choice right now. Decision instance key is the most important part here and the rest could be added later if users request it

**Review by vsgoulart — COMMENTED** [review]
@OmranAbazid Could you rebase this PR? I updated the 8.9 types due to the API changes

File: operate/client/src/App/DecisionInstance/index.test.tsx [hunk 2]
```diff
@@ -310,4 +328,27 @@ describe('<DecisionInstance />', () => {
       'https://docs.camunda.io/docs/self-managed/operate-deployment/operate-authentication/#resource-based-permissions',
     );
   });
+
+  it('should redirect to decisions page and display notification if decision instance is not found (404)', async () => {
+    vi.useFakeTimers({shouldAdvanceTime: true});
```
Comment (vsgoulart) [inline operate/client/src/App/DecisionInstance/index.test.tsx]: @OmranAbazid Are the timers really necessary?

File: operate/client/src/App/BatchOperation/BatchItemsTable.tsx [hunk 3]
```diff
@@ -14,20 +14,68 @@ import {BatchStateIndicator} from 'App/BatchOperations/BatchStateIndicator';
...
+    <Link
+      to={Paths.processInstance(processInstanceKey)}
+      title={`View process instance ${processInstanceKey}`}
+      aria-label={`View process instance ${processInstanceKey}`}
+    >
+      {processInstanceKey}
+    </Link>
+  );
+
+const renderDecisionInstanceCell = (itemKey: string) =>
```
Comment (vsgoulart) [inline operate/client/src/App/BatchOperation/BatchItemsTable.tsx]: These should components. If you feel like you need to name it render something and it spawns JSX then its a component

File: operate/client/src/App/BatchOperation/BatchItemsTable.test.tsx
Comment (vsgoulart) [inline operate/client/src/App/BatchOperation/BatchItemsTable.test.tsx:1]: I think we should not mention API details here and focus more on the user interface naming since the API is a implementation detail. We should avoid mentioning `itemKey`, `DELETE_DECISION_INSTANCE`, `RESOLVE_INCIDENT` and `-1` (an `itemKey` value) on the titles

**Review by vsgoulart — COMMENTED** [review]
@OmranAbazid Could you double check if I didn't mess up the rebase?

**Comment by vsgoulart** [comment]
There some type errors after the rebase too

File: operate/client/src/App/DecisionInstance/index.test.tsx (hunk 2 above)
Comment (OmranAbazid) [reply operate/client/src/App/DecisionInstance/index.test.tsx]: Good catch, they are not really necessary

File: operate/client/src/App/BatchOperation/BatchItemsTable.tsx (hunk 3 above)
Comment (OmranAbazid) [reply operate/client/src/App/BatchOperation/BatchItemsTable.tsx]: Yea, makes sense 👍

**Review by vsgoulart — APPROVED** [review]
