### PR TITLE
fix: Allow retrying `ADD_VARIABLE` operation with the same variable name

### LINKED ISSUE #33337: Cannot re-add variable with the same name after failed `ADD_VARIABLE` operation using Operate UI/REST-API
### Description

When adding a new variable to a user task element in Operate UI, and the operation was failed (e.g. denied by a Task Listener (`deny=true` result)), so the operation enters the `FAILED` state. After that, the UI/REST-API prevents the user from adding a variable with the same name again, showing the message *"Name should be unique"*, even though the original variable was never successfully created.

<details><summary><b>Click to open screenshots</b></summary>

Image

Image

</details>

### Steps to reproduce

1. Deploy a process with a User Task that has an `updating` Task Listener which always denies transitions.
2. In Operate, attempt to add a new variable `testVar` for user task element via the **Variables** tab.
3. Confirm that the operation fails due to denial from Task Listener.
4. Try adding the same variable name `testVar` again.

### Current behavior

* Operate UI displays a validation error: *“Name should be unique”*
* REST call to `POST /api/process-instances/<pid>/operation` returns `400 Bad Request`
* Backend logs include:

Image

### Expected behavior

* Operate UI/REST-API should allow initiating a new `ADD_VARIABLE` operation if all previous `ADD_VARIABLE` operations for that variable are in a `FAILED` state.

### Environment

SaaS & SM

### Version

- Operate: [8.6-8.8]

### Rootcause

The [CreateRequestOperationValidator.java](https://github.com/camunda/camunda/blob/2f068352adeb929ad19095ca8db886d3fdeb3674/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java#L50-L56) checks for existing operations via `operationReader.getOperations(...)` but does not filter out `FAILED` operations.

### Solution ideas

* Update [CreateRequestOperationValidator.java](https://github.com/camunda/camunda/blob/2f068352adeb929ad19095ca8db886d3fdeb3674/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java#L50-L56) to ignore operations in `FAILED` (`COMPLETED`?) states when checking uniqueness for variable names.
* Allow the same name to be retried if no active/pending operation exists.

### PR DESCRIPTION
**Pull request by ce-dmelnych**
> [!TIP]
> For clarity, this PR was intentionally split into focused commits (improving tests, fix, and small refactoring).
Reviewing it commit-by-commit (rather than as one diff) will make it easier to understand the purpose and motivation of each change.

## Description

This PR fixes an issue related to `ADD_VARIABLE` operation request validation that prevented users from retrying a variable addition after a previous attempt had failed, even though the variable was never created.

### Motivation

When a variable addition via Operate UI or REST API failed, the validator would still block any subsequent `ADD_VARIABLE` request with the same name—even though no variable was actually created.

While this was a rare case before, the introduction of "updating" task listeners that can dynamically deny user task transitions (e.g., based on variable value validation logic) makes this a realistic and common scenario.
In such cases, users should be able to fix the value and trigger `ADD_VARIABLE` operation with same name.

### Fix
- Changed the check to exclude operations in the `FAILED` state.
- Added a dedicated unit test to confirm that a failed prior operation does not cause validation failure.

### Refactoring
- Extracted inline validation conditions into helper methods to improve the readability of `validate(...)` method.

### Test improvements
1. Parameterized missing‐field tests:
   - Consolidated many null/empty‐parameter test methods for both `ADD_VARIABLE` and `UPDATE_VARIABLE` into a single `@MethodSource`‐driven parameterized test.
2. Parameterized happy‐path tests:
   - Replaced two separate “valid request” tests with a single `@EnumSource({ADD_VARIABLE, UPDATE_VARIABLE})` test.
3. Added missing tests for `"Variable with the name already exists"` checks.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #33337

### CODE REVIEW

File: operate/webapp/src/test/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidatorTest.java [hunk 1]
```diff
@@ -36,88 +41,48 @@ public void setup() {
...
-    operationRequest.setVariableValue(null);
-
-    final InvalidRequestException exception =
-        assertThrows(
-            InvalidRequestException.class, () -> underTest.validate(operationRequest, "123"));
-
-    assertThat(exception.getMessage())
-        .isEqualTo("ScopeId, name and value must be defined for UPDATE_VARIABLE operation.");
+  @ParameterizedTest(name = "should fail for {0} with scopeId=''{1}'', name=''{2}'', value=''{3}''")
+  @MethodSource("invalidAddOrUpdateVariableOperation")
```
Comment (mustafadagher) [inline operate/webapp/src/test/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidatorTest.java:75]: 👍 I like it!

File: operate/webapp/src/test/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidatorTest.java [hunk 2]
```diff
@@ -36,88 +41,48 @@ public void setup() {
...
+      final OperationType type, final String scopeId, final String name, final String value) {
+    final var request = new CreateOperationRequestDto(type);
+    request.setVariableScopeId(scopeId);
+    request.setVariableName(name);
+    request.setVariableValue(value);
+
+    // when - then
+    assertThatThrownBy(() -> underTest.validate(request, "123"))
+        .isInstanceOf(InvalidRequestException.class)
+        .hasMessage("ScopeId, name and value must be defined for UPDATE_VARIABLE operation.");
```
Comment (mustafadagher) [inline operate/webapp/src/test/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidatorTest.java]: 🔧 to add to your improvement, we can also fix the message to include the correct `operationType` instead of printing `UPDATE_VARIABLE`  always

File: operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java [hunk 3]
```diff
@@ -41,22 +43,34 @@ public void validate(
...
-          String.format(
-              "Variable with the name \"%s\" already exists.", operationRequest.getVariableName()));
+
+    if (operationRequest.getOperationType().equals(ADD_VARIABLE)) {
+      if (variableAlreadyExists(operationRequest, processInstanceId)
+          || hasNonFailedAddVariableOperation(operationRequest, processInstanceId)) {
+        throw new InvalidRequestException(
+            String.format(
+                "Variable with the name \"%s\" already exists.",
+                operationRequest.getVariableName()));
```
Comment (mustafadagher) [inline operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java]: 🔧 while this was already like wrong before your fix, the message does not completely reflect the reality.
It could be that ` the variable exists` or `an operation to create is is created/ongoing`.

💭 We can assume that the operation will eventually be completed before a user sees this message 🤔 

We shall leave it as is, or we can improve it. I'll leave it up to you

File: operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java [hunk 4]
```diff
@@ -41,22 +43,34 @@ public void validate(
...
+      }
     }
   }
+
+  private boolean variableAlreadyExists(
+      final CreateOperationRequestDto request, final String processInstanceId) {
+    final var variable = variableReader.getVariableByName(
```
Comment (mustafadagher) [inline operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java]: 💭  this `getVariableByName` method can through an exception if an error occurs when reading the variable from es/os. 
I don't exactly know if we should handle it here to accommodate this case.

**Review by mustafadagher — APPROVED** [review]
LGTM! I just left some thoughts below

File: operate/webapp/src/test/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidatorTest.java (hunk 2 above)
Comment (ce-dmelnych) [reply operate/webapp/src/test/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidatorTest.java]: Agree, addressed this in https://github.com/camunda/camunda/pull/33928/commits/6a5813a115ff1f7bf23da1184a92206d78e094d9 commit.

File: operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java (hunk 3 above)
Comment (ce-dmelnych) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java]: Thanks Mustafa! 🙌
You're right, the message could be clearer.
Addressed it in [this](https://github.com/camunda/camunda/pull/33928/commits/6a5813a115ff1f7bf23da1184a92206d78e094d9) commit to improve the clarity.

File: operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java (hunk 4 above)
Comment (ce-dmelnych) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java]: 🤔 Hmmm... if an exception is thrown, we wouldn’t allow triggering `ADD_VARIABLE` operation. Not sure what exactly could cause it or how often it could occur.
For now, I’ll leave it as is.

File: operate/webapp/src/test/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidatorTest.java (hunk 2 above)
Comment (mustafadagher) [reply operate/webapp/src/test/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidatorTest.java]: great improvement, thank you 👍

File: operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java (hunk 3 above)
Comment (mustafadagher) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/rest/validation/CreateRequestOperationValidator.java]: Thank you

**Review by mustafadagher — APPROVED** [review]
Thanks for the improvements @ce-dmelnych, looks great!
