### PR TITLE
fix: ensure backup manager uses dynamic partition count

### LINKED ISSUE #21470: Backups use partition count from `ClusterConfiguration`
The `BackupRequestHandler` broadcasts a request to take backups over all partitions. With partition scaling, the number of partitions is dynamic and should be looked up from the routing info in `ClusterConfiguration` if it is available. Otherwise, if the feature flag is disabled, we can fall back to static configuration.

The `BackupService`  also needs to retrieve the dynamic partition count instead of using the statically configured one.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

To store the correct partition count in the backup, `CheckpointCreateProcessor` gets the current partition count from the runtime state and provide it to the backup manager. 

To avoid having the module depends on the engine module, we provide this information via a supplier. This is not ideal. We also have a supplier to provide the scaling information. At the moment, it is not clear what is the best way to refactor the modules to handle this dependency clearly. My first idea is to move all scaling related classes out of the engine. However, it would be good to consider this when implementing message relocation. 

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #21470

### CODE REVIEW

**Comment by deepthidevaki** [comment]
Note: This is a bug fix and should be backported to release 8.8 branch.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java [hunk 1]
```diff
@@ -99,6 +99,22 @@ public boolean isScalingInProgress() {
...
   }
 
+  /**
+   * Returns the current partition count from routing information. If routing state is not
+   * initialized, returns -1.
+   *
+   * @return the current partition count
+   */
+  public int getCurrentPartitionCount() {
+    if (processingState != null && processingState.getRoutingState() != null) {
```
Comment (panagiotisgts) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java]: 🔧  Are we able to use `RoutingInfo` instead of `RoutingState` here? It already contains the fallbacks to return the static partition count so as to remove the checks here and on the  [StreamProcessorTransitionStep](https://github.com/camunda/camunda/pull/37229/files#diff-2f816cfe882612c39cc34b3b2d8d555afa2ff78ecef1479f4d6f91a21d342bf0)

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/backup/ConcurrentBackupCompactionTest.java [hunk 2]
```diff
@@ -148,7 +148,8 @@ public void shouldNotFailWhenCompactionTriggers() throws Exception {
     // when
     // a backup is taken (but the snapshot store does not complete it,
     // because the BackupStore it's blocked)
-    final var backupResultFut = backupService.takeBackup(backupIdx, backupIdx);
+    final var backupResultFut =
+        backupService.takeBackup(backupIdx, backupIdx, 1); // Add partition count of 1
```
Comment (panagiotisgts) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/backup/ConcurrentBackupCompactionTest.java]: Comment here is unnecessary I believe

**Review by panagiotisgts — APPROVED** [review]
LGTM! Just a proposal to remove some conditional code

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java (hunk 1 above)
Comment (deepthidevaki) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java]: `RoutingInfo` is not available in this class. It is created in the factory and passed down into individual processors. I guess, this is a good indication that we need to refactor this out of Engine. :thinking:

Comment (panagiotisgts) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java]: :thinking:  Since the `RoutingState` is already present you can initialize a `RoutingInfo` instance again right? It's a read-only view to the `RoutingState` itself.

Comment (deepthidevaki) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java]: Yes. Then, this method should take the fallback partition count as parameter. ( :smile: This was my first implementation)

Comment (panagiotisgts) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java]: Ah I see what you mean now, you'd have to provide the configured partition count externally since it's not present in this context. 😮‍💨 

Maybe we should do it? We are also using the `RoutingState` for the `isScalingInProgress` check, we could instantiate a `RoutingInfo` on `init` and use it in both scenarios?

Comment (deepthidevaki) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java]: This configured paritition count is also not available in init. It is hidden via various layers of factories :) 
I updated `getPartitionCount` to take the configured partitionCount and use routingInfo for get the current partition count. I will leave it as it is now. Then we should look into how to refactor so that we split Engine (bpmn processing related functionalities) and system functionalities (scaling, backups etc.) into different modules.
