### PR TITLE
map RESOLVE incident intent to ACTIVE incident state

### LINKED ISSUE #37288: NullPointerException in SearchQueryResponseMapper when IncidentEntity state is null
### 

### 

### 

### 

### Description

A NullPointerException occurs in the SearchQueryResponseMapper when calling IncidentEntity$IncidentState.name() because IncidentEntity.state() is null. This breaks the incident search feature and may indicate missing or invalid incident state data.

Excerpt from stack trace:

    java.lang.NullPointerException: Cannot invoke "io.camunda.search.entities.IncidentEntity$IncidentState.name()" because the return value of "io.camunda.search.entities.IncidentEntity.state()" is null
        at io.camunda.zeebe.gateway.rest.SearchQueryResponseMapper.toIncident(SearchQueryResponseMapper.java:808)

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.search.entities.IncidentEntity$IncidentState.name()" because the return value of "io.camunda.search.entities.IncidentEntity.state()" is null
        at io.camunda.zeebe.gateway.rest.SearchQueryResponseMapper.toIncident(SearchQueryResponseMapper.java:808)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
        at io.camunda.zeebe.gateway.rest.SearchQueryResponseMapper.toIncidents(SearchQueryResponseMapper.java:794)
        at java.base/java.util.Optional.map(Unknown Source)
        at io.camunda.zeebe.gateway.rest.SearchQueryResponseMapper.toIncidentSearchQueryResponse(SearchQueryResponseMapper.java:468)
        at io.camunda.zeebe.gateway.rest.controller.IncidentController.search(IncidentController.java:93)
        at io.camunda.zeebe.util.Either$Right.fold(Either.java:445)
        at io.camunda.zeebe.gateway.rest.controller.IncidentController.searchIncidents(IncidentController.java:68)
        ... (rest of stack trace omitted for brevity)
```

</p>
</details>

Possible reason: IncidentEntity.state() can be null if IncidentEntityTransformer.toState() returns null, which may occur if the incident data is incomplete or the transformation logic fails to map a valid state.

### Steps to reproduce

1. Trigger an incident search via the REST API.
2. Ensure there is an IncidentEntity with a null state (e.g. due to incomplete incident data or transformation failure).
3. Observe the NullPointerException in SearchQueryResponseMapper.toIncident().

### Current behavior

The incident search fails with a NullPointerException when an IncidentEntity has a null state.

### Expected behavior

The system should gracefully handle incidents with null state and not throw a NullPointerException. A proper error message or a default/fallback state should be used.

### Environment

SaaS

### Version

`8.8.0-alpha7`

### Rootcause

Likely cause: IncidentEntity.state() returns null, which can happen if IncidentEntityTransformer.toState() returns null. However, toIncident() assumes state is always non-null and directly calls .name().

### Solution ideas

Add a null check for IncidentEntity.state() in SearchQueryResponseMapper.toIncident() before calling .name(). Consider handling or logging invalid or incomplete incident states.

### Dev -> QA handover

_No response_

### Links

- Seen in [SUPPORT-30488](https://jira.camunda.com/browse/SUPPORT-30488)

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

The client side does not know of any incident status `RESOLVE`, therefore it should instead map a `RESOLVE` incident intent to an `ACTIVE` incident status.

## Related issues

closes #37288

### CODE REVIEW

**Review by houssain-barouni — COMMENTED** [review]
Hi @EuroLew , thank you for the fix
💭 @tmetzke has suggested that the exporter should not process the records with this `RESOLVE` intent, cause it is coming from a command rather than a change of the actual state of the incident itself.
Can we consider updating [PostImporterQueueFromIncidentHandler](https://github.com/camunda/camunda/blob/main/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/PostImporterQueueFromIncidentHandler.java), and make `handlesRecord` check that the intent is different from `RESOLVE`, or better, that it is one of a Set of supported intents. This should prevent the problem where a zeebe intent is not handled as an incident state, in the Incident Update job

File: webapps-schema/src/main/java/io/camunda/webapps/schema/entities/incident/IncidentState.java [hunk 1]
```diff
@@ -7,34 +7,34 @@
...
   MIGRATED("MIGRATED"),
   RESOLVED("RESOLVED"),
-  RESOLVE("RESOLVE"),
   PENDING(null);
 
   private static final Map<String, IncidentState> INTENT_MAP = new HashMap<>();
 
   static {
-    Arrays.stream(IncidentState.values()).forEach(is -> INTENT_MAP.put(is.getZeebeIntent(), is));
+    for (final IncidentState state : IncidentState.values()) {
```
Comment (RomanJRW) [inline webapps-schema/src/main/java/io/camunda/webapps/schema/entities/incident/IncidentState.java:22]: Just because this gets a little convoluted compared to most of our enums, what about adding a little test for this. Co-pilot just made me this, which I think should suffice:

```
public class IncidentStateTest {

  @Test
  void testCreateFrom_withValidIntents() {
    assertEquals(IncidentState.ACTIVE, IncidentState.createFrom("CREATED"));
    assertEquals(IncidentState.ACTIVE, IncidentState.createFrom("RESOLVE"));
    assertEquals(IncidentState.MIGRATED, IncidentState.createFrom("MIGRATED"));
    assertEquals(IncidentState.RESOLVED, IncidentState.createFrom("RESOLVED"));
  }

  @Test
  void testCreateFrom_withNullIntent() {
    assertNull(IncidentState.createFrom(null));
  }

  @Test
  void testCreateFrom_withUnknownIntent() {
    assertNull(IncidentState.createFrom("UNKNOWN_INTENT"));
  }
}
```

**Review by RomanJRW — APPROVED** [review]
I think the changes are fine, but there is an open question [here](https://camunda.slack.com/archives/C08GPP57D8R/p1761252079291119) that I would appreciate an answer on as it might resolve multiple open issues we have right now
