### PR TITLE
Idempotent message correlation retries

### LINKED ISSUE #26926: Message correlation on a non-interrupting message event is not idempotent
**Describe the bug**

When a message is published with a message id we[ claim that it is only processed once](https://docs.camunda.io/docs/components/concepts/messages/#message-uniqueness). This is not always true. When we have non-interrupting message event like in the process below there is a chance it gets correlated multiple times by a single message.

Image

**To Reproduce**

I've reproduced it in a test. For this test I had to "hack" some things in the code as I wasn't sure how else to do it.

First we need to modify the timeout and interval of the `MessageObserver`:

```java
  public static final Duration SUBSCRIPTION_TIMEOUT = Duration.ofSeconds(1);
  public static final Duration SUBSCRIPTION_CHECK_INTERVAL = Duration.ofSeconds(1);
```

Next we need to make it possible to create a process instance on a specific partition in our test case. We add a method to the `ProcessInstanceClient`:

```java
    public long createOnPartition(final int partitionId) {
      final long position =
          writer.writeCommandOnPartition(
              partitionId, ProcessInstanceCreationIntent.CREATE, processInstanceCreationRecord);

      final var resultingRecord = expectation.apply(position);
      return resultingRecord.getValue().getProcessInstanceKey();
    }
```

Finally we run the test case below:

```java
  @Test
  public void test() throws InterruptedException { // TODO rename
    // given
    final var processId = Strings.newRandomValidBpmnId();
    final var messageName = "event_message";
    final var correlationKey = CORRELATION_KEYS.get(START_PARTITION_ID);
    final var eventSubProcessStartId = "eventSubProcessStart";
    engine
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(processId)
                .eventSubProcess(
                    "subprocess",
                    s ->
                        s.startEvent(eventSubProcessStartId)
                            .interrupting(false)
                            .message(
                                m ->
                                    m.name(messageName)
                                        .zeebeCorrelationKeyExpression("correlationKey"))
                            .userTask()
                            .endEvent())
                .startEvent()
                .userTask()
                .endEvent()
                .done())
        .deploy();
    final var processInstanceKey =
        engine
            .processInstance()
            .ofBpmnProcessId(processId)
            .withVariable("correlationKey", correlationKey)
            .createOnPartition(2);

    // when
    engine.pauseProcessing(2);
    engine
        .message()
        .withId("messageId")
        .withName(messageName)
        .withCorrelationKey(correlationKey)
        .withTimeToLive(Duration.ofMinutes(30))
        .onPartition(1)
        .publish();
    Thread.sleep(3000);
    engine.resumeProcessing(2);

    // then
    RecordingExporter.processMessageSubscriptionRecords(ProcessMessageSubscriptionIntent.CREATED)
        .withMessageName(messageName)
        .withCorrelationKey(correlationKey)
        .withPartitionId(2)
        .await();
    assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
                .withProcessInstanceKey(processInstanceKey)
                .withElementId(eventSubProcessStartId)
                .limit(2)
                .count())
        .isEqualTo(1);
  }
```

The test will start a process instance on partition 2. The process will have a subscription for messages due to the non-interrupting message start event in the event subprocess. The correlation key we use ensures the messasge gets published to partition 1. It's important this is a different partition!

We simulate a scenario where partition 2 is very busy and it takes a while to process new commands. We do this by pausing processing on partition 2. This means new commands can be written to the log, but they won't be processed yet.

Whilst partition 2 is working through the backlog of commands on the queue, the `PendingMessageSubscriptionChecker` of partition 1 will keep sending new `CORRELATE` command to partition 2. These all end up on the log.

Once partition 2 catches up with the `CORRELATE` commands (we resume processing) it will process them all. Since the event is non-interrupting the subscription is not cleared after the first correlation. Instead all of correlations send by partition 1 correlate and trigger the message event. As a result a single published message is correlated multiple times to the same event.

**Expected behavior**

The on-interrupting event should only trigger a single time per message. Subsequent correlations on the log should not succeed.

**Log/Stacktrace**

<details><summary>Logged records from the test</summary>
 <p>

```
1 C DPLY         CREATE         - #01-> -1    -1 - 
1 E PROC         CREATED        - #02->#01 P1K01 - process.xml -> "id-6a03..ac4affc" (version:1)
2 C DPLY         CREATE         - #01-> -1 P1K02 - process.xml
3 C DPLY         CREATE         - #01-> -1 P1K02 - process.xml
1 E DPLY         CREATED        - #03->#01 P1K02 - process.xml
1 E DSTR         STARTED        - #04->#01 P1K02 - DEPLOYMENT CREATE on partition 1
1 E DSTR         DISTRIBUTING   - #05->#01 P1K02 - DEPLOYMENT CREATE to partition 2
1 E DSTR         DISTRIBUTING   - #06->#01 P1K02 - DEPLOYMENT CREATE to partition 3
2 E PROC         CREATED        - #02->#01 P1K01 - process.xml -> "id-6a03..ac4affc" (version:1)
1 C DSTR         ACKNOWLEDGE    - #07-> -1 P1K02 - DEPLOYMENT CREATE for partition 2
2 E DPLY         CREATED        - #03->#01 P1K02 - process.xml
1 E DSTR         ACKNOWLEDGED   - #08->#07 P1K02 - DEPLOYMENT CREATE for partition 2
3 E PROC         CREATED        - #02->#01 P1K01 - process.xml -> "id-6a03..ac4affc" (version:1)
1 C DSTR         ACKNOWLEDGE    - #09-> -1 P1K02 - DEPLOYMENT CREATE for partition 3
3 E DPLY         CREATED        - #03->#01 P1K02 - process.xml
1 E DSTR         ACKNOWLEDGED   - #10->#09 P1K02 - DEPLOYMENT CREATE for partition 3
1 E DSTR         FINISHED       - #11->#09 P1K02 - DEPLOYMENT CREATE on partition 1
2 C CREA         CREATE         - #04-> -1    -1 - new <process "id-6a03..ac4affc"> (default start)  with variables: {correlationKey=item-2}
2 E VAR          CREATED        - #05->#04 P2K02 - correlationKey->"item-2" in <process [P2K01]>
1 C MSG_SUB      CREATE         - #12-> -1    -1 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 C PI           ACTIVATE       - #06->#04 P2K01 - PROCESS "id-6a03..ac4affc" in <process "id-6a03..ac4affc"[P2K01]>
2 E CREA         CREATED        - #07->#04 P2K03 - new <process "id-6a03..ac4affc"> (default start)  with variables: {correlationKey=item-2}
2 E PI           ACTIVATING     - #08->#04 P2K01 - PROCESS "id-6a03..ac4affc" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATED      - #09->#04 P2K01 - PROCESS "id-6a03..ac4affc" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #10->#04    -1 - START_EVENT "startEv..6ec9b27" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #11->#04 P2K04 - START_EVENT "startEv..6ec9b27" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATED      - #12->#04 P2K04 - START_EVENT "startEv..6ec9b27" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           COMPLETE       - #13->#04 P2K04 - START_EVENT "startEv..6ec9b27" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           COMPLETING     - #14->#04 P2K04 - START_EVENT "startEv..6ec9b27" in <process "id-6a03..ac4affc"[P2K01]>
2 E PROC_MSG_SUB CREATING       - #15->#04 P2K05 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
2 E PI           COMPLETED      - #16->#04 P2K04 - START_EVENT "startEv..6ec9b27" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           SEQ_FLOW_TAKEN - #17->#04 P2K06 - SEQUENCE_FLOW "sequenc..a549079" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #18->#04 P2K07 - USER_TASK "userTas..96cb32f" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #19->#04 P2K07 - USER_TASK "userTas..96cb32f" in <process "id-6a03..ac4affc"[P2K01]>
2 E JOB          CREATED        - #20->#04 P2K08 - P2K08 "io.camunda.zeebe:userTask" @"userTas..96cb32f"[P2K07] (BPMN_ELEMENT), 1 retries, in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PI           ACTIVATED      - #21->#04 P2K07 - USER_TASK "userTas..96cb32f" in <process "id-6a03..ac4affc"[P2K01]>
1 E MSG_SUB      CREATED        - #13->#12 P1K03 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 C PROC_MSG_SUB CREATE         - #22-> -1    -1 - "event_message" @[P2K01] in <process ?[P2K01]> (no vars) (tenant: <default>)
1 C MSG          PUBLISH        - #14-> -1    -1 - "event_message" correlationKey: item-2 (no vars)
1 E MSG          PUBLISHED      - #15->#14 P1K04 - "event_message" correlationKey: item-2 (no vars)
2 C PROC_MSG_SUB CORRELATE      - #23-> -1    -1 - "event_message" (inter.) correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
1 E MSG_SUB      CORRELATING    - #16->#14 P1K03 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 C PROC_MSG_SUB CORRELATE      - #24-> -1    -1 - "event_message" (inter.) correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
2 C PROC_MSG_SUB CORRELATE      - #25-> -1    -1 - "event_message" (inter.) correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
2 C PROC_MSG_SUB CORRELATE      - #26-> -1    -1 - "event_message" (inter.) correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
2 E PROC_MSG_SUB CREATED        - #27->#22 P2K05 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
1 C MSG_SUB      CORRELATE      - #17-> -1    -1 - "event_message" (inter.) @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PROC_MSG_SUB CORRELATED     - #28->#23 P2K05 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
2 E PROC_EVNT    TRIGGERING     - #29->#23 P2K09 -  @"eventSu..ssStart"[P2K01] in <process P1K01[P2K01]> (no vars)
2 C PI           ACTIVATE       - #30->#23    -1 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #31->#23 P2K10 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATED      - #32->#23 P2K10 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #33->#23    -1 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #34->#23 P2K11 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATED      - #35->#23 P2K11 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           COMPLETE       - #36->#23 P2K11 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           COMPLETING     - #37->#23 P2K11 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PROC_EVNT    TRIGGERED      - #38->#23 P2K09 -  @"eventSu..ssStart"[P2K11] in <process P1K01[P2K01]> (no vars)
2 E PI           COMPLETED      - #39->#23 P2K11 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           SEQ_FLOW_TAKEN - #40->#23 P2K12 - SEQUENCE_FLOW "sequenc..36f2c26" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #41->#23 P2K13 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #42->#23 P2K13 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E JOB          CREATED        - #43->#23 P2K14 - P2K14 "io.camunda.zeebe:userTask" @"userTas..62687fb"[P2K13] (BPMN_ELEMENT), 1 retries, in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PI           ACTIVATED      - #44->#23 P2K13 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E PROC_MSG_SUB CORRELATED     - #45->#24 P2K05 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
2 E PROC_EVNT    TRIGGERING     - #46->#24 P2K15 -  @"eventSu..ssStart"[P2K01] in <process P1K01[P2K01]> (no vars)
2 C PI           ACTIVATE       - #47->#24    -1 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #48->#24 P2K16 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATED      - #49->#24 P2K16 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #50->#24    -1 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #51->#24 P2K17 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
1 C MSG_SUB      CORRELATE      - #18-> -1    -1 - "event_message" (inter.) @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
1 E MSG_SUB      CORRELATED     - #19->#17 P1K03 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PI           ACTIVATED      - #52->#24 P2K17 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           COMPLETE       - #53->#24 P2K17 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
1 E MSG_SUB      CORRELATED     - #20->#18 P1K03 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PI           COMPLETING     - #54->#24 P2K17 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PROC_EVNT    TRIGGERED      - #55->#24 P2K15 -  @"eventSu..ssStart"[P2K17] in <process P1K01[P2K01]> (no vars)
2 E PI           COMPLETED      - #56->#24 P2K17 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           SEQ_FLOW_TAKEN - #57->#24 P2K18 - SEQUENCE_FLOW "sequenc..36f2c26" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #58->#24 P2K19 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #59->#24 P2K19 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E JOB          CREATED        - #60->#24 P2K20 - P2K20 "io.camunda.zeebe:userTask" @"userTas..62687fb"[P2K19] (BPMN_ELEMENT), 1 retries, in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PI           ACTIVATED      - #61->#24 P2K19 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
1 C MSG_SUB      CORRELATE      - #21-> -1    -1 - "event_message" (inter.) @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
1 E MSG_SUB      CORRELATED     - #22->#21 P1K03 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PROC_MSG_SUB CORRELATED     - #62->#25 P2K05 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
2 E PROC_EVNT    TRIGGERING     - #63->#25 P2K21 -  @"eventSu..ssStart"[P2K01] in <process P1K01[P2K01]> (no vars)
2 C PI           ACTIVATE       - #64->#25    -1 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #65->#25 P2K22 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATED      - #66->#25 P2K22 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #67->#25    -1 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #68->#25 P2K23 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATED      - #69->#25 P2K23 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           COMPLETE       - #70->#25 P2K23 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           COMPLETING     - #71->#25 P2K23 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PROC_EVNT    TRIGGERED      - #72->#25 P2K21 -  @"eventSu..ssStart"[P2K23] in <process P1K01[P2K01]> (no vars)
2 E PI           COMPLETED      - #73->#25 P2K23 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           SEQ_FLOW_TAKEN - #74->#25 P2K24 - SEQUENCE_FLOW "sequenc..36f2c26" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #75->#25 P2K25 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #76->#25 P2K25 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E JOB          CREATED        - #77->#25 P2K26 - P2K26 "io.camunda.zeebe:userTask" @"userTas..62687fb"[P2K25] (BPMN_ELEMENT), 1 retries, in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PI           ACTIVATED      - #78->#25 P2K25 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E PROC_MSG_SUB CORRELATED     - #79->#26 P2K05 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars) (tenant: <default>)
1 C MSG_SUB      CORRELATE      - #23-> -1    -1 - "event_message" (inter.) @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PROC_EVNT    TRIGGERING     - #80->#26 P2K27 -  @"eventSu..ssStart"[P2K01] in <process P1K01[P2K01]> (no vars)
2 C PI           ACTIVATE       - #81->#26    -1 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #82->#26 P2K28 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATED      - #83->#26 P2K28 - EVENT_SUB_PROCESS "subprocess" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #84->#26    -1 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #85->#26 P2K29 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATED      - #86->#26 P2K29 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           COMPLETE       - #87->#26 P2K29 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           COMPLETING     - #88->#26 P2K29 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
2 E PROC_EVNT    TRIGGERED      - #89->#26 P2K27 -  @"eventSu..ssStart"[P2K29] in <process P1K01[P2K01]> (no vars)
2 E PI           COMPLETED      - #90->#26 P2K29 - START_EVENT "eventSu..ssStart" in <process "id-6a03..ac4affc"[P2K01]>
1 E MSG_SUB      CORRELATED     - #24->#23 P1K03 - "event_message" correlationKey: item-2 @[P2K01] in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PI           SEQ_FLOW_TAKEN - #91->#26 P2K30 - SEQUENCE_FLOW "sequenc..36f2c26" in <process "id-6a03..ac4affc"[P2K01]>
2 C PI           ACTIVATE       - #92->#26 P2K31 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E PI           ACTIVATING     - #93->#26 P2K31 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
2 E JOB          CREATED        - #94->#26 P2K32 - P2K32 "io.camunda.zeebe:userTask" @"userTas..62687fb"[P2K31] (BPMN_ELEMENT), 1 retries, in <process "id-6a03..ac4affc"[P2K01]> (no vars)
2 E PI           ACTIVATED      - #95->#26 P2K31 - USER_TASK "userTas..62687fb" in <process "id-6a03..ac4affc"[P2K01]>
```

</p>
</details>

In these record we see that:
- P1 created a message subscription (position 13)
- P1 receives a published message (position 15)
- P2 has 4 `CORRELATE` commands on the log (position 23, 24, 25, 26). This is due to the `PendingMessageSubscriptionChecker`
- P2 resumes processing and triggers the message event 4 times (position 38, 55, 72, 89)

This problem arose in a support case: https://jira.camunda.com/browse/SUPPORT-25086. We received some logging that clearly showcases that the extra correlations are triggered by the `PendingMessageSubscriptionChecker`:

```
2025-01-09 13:42:29.355 [Broker-2] [zb-fs-workers-1] [Exporter-3] INFO 
      io.camunda.zeebe.broker.exporter.trace - Exporting record with key 6755399441584969 at position 1258771 on partition 3 of type EVENT with value type PROCESS_MESSAGE_SUBSCRIPTION and intent CORRELATED
2025-01-09 13:42:32.139 [Broker-2] [zb-fs-workers-1] [Exporter-3] INFO 
      io.camunda.zeebe.broker.exporter.trace - Exporting record with key 6755399441584969 at position 1259289 on partition 3 of type EVENT with value type PROCESS_MESSAGE_SUBSCRIPTION and intent CORRELATED
```

This specific log occurred 194 times for the key `6755399441584969`, but with different positions. This indicates that the same message is correlated multiple times. Aside from that there's logging like:

```
2025-01-09 14:51:40.615 [Broker-2] [zb-actors-0] [AsyncProcessingScheduleActor-3] WARN 
      io.camunda.zeebe.broker.logstreams - Expected to find a subscription with key 11258999068657018 and message name ..., but none found. The state is inconsistent.
2025-01-09 14:51:40.615 [Broker-2] [zb-actors-0] [AsyncProcessingScheduleActor-3] WARN 
      io.camunda.zeebe.broker.logstreams - Expected to find a subscription with key 9007199254944655 and message name ..., but none found. The state is inconsistent.
2025-01-09 14:51:40.615 [Broker-2] [zb-actors-0] [AsyncProcessingScheduleActor-3] WARN 
      io.camunda.zeebe.broker.logstreams - Expected to find a subscription with key 2251799813878699 and message name ..., but none found. The state is inconsistent.
```

The only place where we log this message is [here](https://github.com/camunda/camunda/blob/fba75d7aacf19b1ebebf4a371fc96c3a2f022e3a/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageSubscriptionState.java#L280-L283). This method is called in 1 place, by the `PendingMessageSubscriptionChecker`.

**Environment:**
- Zeebe Version: 8.5.7, but likely exists on all versions.

### PR DESCRIPTION
**Pull request by korthout**
## Description

This pull request resolves a bug related to message correlation retries by ensuring that message correlation commands are processed idempotently.

### Problem context
A message correlation is split across two partitions: the message partition (where the message is expected) and the process instance partition (where the process instance exists that awaits a message). When a message is published to the message partition, and that partition is aware of a process instance awaiting the message (represented by a message subscription on the message partition), it attempts to correlate the message by sending a `CORRELATE` command to the process instance partition. This command must be processed and then acknowledged by sending a `CORRELATE` command back to the message partition. The communication between these partition is unreliable, and so either of these commands may fail to arrive at the other partition. Therefore, a retry mechanism exists in the message subscription partition to re-send this `CORRELATE` command to the process instance partition. The checker runs every 30s and only retries commands that haven't been communicated about at least 10s.

If the acknowledgement would be lost, or the partition is down for some time, then multiple `CORRELATE` commands for the same message may exist on the process instance partition due to the retry. Each of these commands would trigger a non-interrupting message catch event an additional time.

```mermaid
sequenceDiagram
    participant MP as Message Partition
    participant PIP as Process Instance Partition

    MP->>PIP: CORRELATE (Message 1)
    Note right of MP: Initial correlation attempt

    PIP->>PIP: Trigger non-interrupting message catch event
    PIP-->>MP: ACK (CORRELATE)
    Note left of PIP: ACK lost due to network issues

    MP->>PIP: CORRELATE (Message 1) [Retry]
    Note right of MP: Retry due to missing ACK
    
    PIP->>PIP: Trigger non-interrupting message catch event again
    Note right of PIP: Multiple correlations trigger the event multiple times
```

### Solving the problem

This pull request solves the problem by deduplicating the `CORRELATE` commands on the process instance partition. It can do this because only one message will be correlating to the message subscription at a time. This means that ordering is guaranteed already, and we can simply reject a secondary `CORRELATE` command for the same message (by its message key). Note that the last correlated message key is stored in the process message subscription.

```mermaid
sequenceDiagram
    participant MP as Message Partition
    participant PIP as Process Instance Partition

    MP->>PIP: CORRELATE (Message 1)
    Note right of MP: Initial correlation attempt

    PIP->>PIP: Trigger non-interrupting message catch event
    PIP-->>MP: ACK (CORRELATE)
    Note left of PIP: ACK lost due to network issues

    MP->>PIP: CORRELATE (Message 1) [Retry]
    Note right of MP: Retry due to missing ACK
    
    PIP->>PIP: Reject duplicate CORRELATE (Message 1)
    Note right of PIP: Subscription knows message 1 correlated last
```

This change required an additional change: Reject retried acknowledgements. We must acknowledge again, because the acknowledgement can be lost. If we would not do this, then we may accidentally change things about our message subscription that are no longer valid because it may have already moved on. We have to reject it:
- if the message key of the acknowledgement doesn't match the message key currently on the message subscription, because this means that we're already correlating a different message
- or if the message subscription is already not correlating anymore. This simply means that we've processed the previous acknowledgement and there were no messages that correlated to it afterward.

```mermaid
sequenceDiagram
    participant MP as Message Partition
    participant PIP as Process Instance Partition

    MP->>PIP: CORRELATE (Message 1)
    MP->>PIP: CORRELATE (Message 1) [Retry]

    PIP->>PIP: Trigger non-interrupting message catch event
    PIP-->>MP: ACK (Message 1)

    MP->>MP: Accept ACK (Message 1)

    PIP->>PIP: Reject duplicate CORRELATE (Message 1)
    PIP-->>MP: ACK (Message 1)

    MP->>MP: Reject ACK (Message 1)
    Note right of MP: Subscription already accepted this ack
```

### Additional changes

- As part of resolving this bug, a test case is added for the bug specifically. To ensure that the test case worked, some special test infrastructure required changes. For the test, see 222c0de. For the infrastructure changes, see 9ab9c37, d5413e1, 8fdbfc5.
- The bugfix itself also requires some test changes. Correlate commands must now reference a message key, otherwise they can be rejected. This was not always the case in existing tests. See 303fbcd and e4d55c4.
- A warning log was lowered to debug level, as it is not anything actionable for a user. See 5c76a8e.
- The compact record logger didn't print the message key for message subscription. See 2dc4545.
- I've added some documentation where useful.

### Backporting

This problems seems to be very old, and will require backporting to all supported versions. I'll be backporting this to 8.7, 8.6, 8.5, 8.4, and 8.3.

Given that some of the test infrastructure changes are specific to authorizations in zeebe (a so far unreleased feature), I expect some conflicts. I'll let backport-action take care of creating the pull requests for me, and will record the conflict resolutions locally for easy re-applying.

## Related issues

closes #26926

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageSubscriptionCorrelateProcessor.java [hunk 1]
```diff
@@ -71,10 +76,39 @@ public void processRecord(final TypedRecord<MessageSubscriptionRecord> record) {
     if (subscription == null) {
       rejectCommand(record);
       return;
+
+    } else if (subscription.getRecord().getMessageKey() != record.getValue().getMessageKey()) {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageSubscriptionCorrelateProcessor.java:80]: 💭 In theory it could happen we already have this command on the log where the message key will still be `-1` as the default. We will reject the command and not do anything. The message correlation will then be retried and that acknowledgement will get a message key. The other partition will detect it already correlated and just send the acknowledgement without correlating it again.

Just dumping this thought for myself to see if it'd work. It looks like it does, but there's a chance we run into this scenario. In the end it results in an extra back and forth between partitions but that should be fine imo.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageSubscriptionCorrelateProcessor.java [hunk 2]
```diff
@@ -86,45 +81,30 @@ public void processRecord(final TypedRecord<MessageSubscriptionRecord> record) {
...
-          subscription.getRecord().getMessageKey());
       final var reason =
-          String.format(
-              NO_SUBSCRIPTION_FOUND_MESSAGE,
-              record.getValue().getElementInstanceKey(),
-              BufferUtil.bufferAsString(record.getValue().getMessageNameBuffer()));
-      rejectionWriter.appendRejection(record, RejectionType.NOT_FOUND, reason);
+          """
+          Expected to acknowledge correlating message with key '%d' to subscription with key '%d' \
+          but the subscription is already correlating to another message with key '%d'"""
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageSubscriptionCorrelateProcessor.java:87]: 🤡 You could consider pulling this out into a constant like we did with the other error message

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageSubscriptionCorrelateProcessor.java [hunk 3]
```diff
@@ -86,45 +81,30 @@ public void processRecord(final TypedRecord<MessageSubscriptionRecord> record) {
...
-          subscription.getKey());
       final var reason =
-          String.format(
-              NO_SUBSCRIPTION_FOUND_MESSAGE,
-              record.getValue().getElementInstanceKey(),
-              BufferUtil.bufferAsString(record.getValue().getMessageNameBuffer()));
-      rejectionWriter.appendRejection(record, RejectionType.NOT_FOUND, reason);
+          """
+          Expected to acknowledge correlating message with key '%d' to subscription with key '%d' \
+          but the subscription is already correlating'"""
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageSubscriptionCorrelateProcessor.java:102]: 🤡 You could consider pulling this out into a constant like we did with the other error message. You could actually reuse part of the other error message as well.

**Review by remcowesterhoud — APPROVED** [review]
Looks good to me! Just some small comments and thought-dumps

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java [hunk 4]
```diff
@@ -143,6 +147,18 @@ final var record = command.getValue();
...
 
+  private boolean hasAlreadyBeenCorrelated(
+      final ProcessMessageSubscriptionRecord record,
+      final ProcessMessageSubscription subscription) {
+    // we only want to correlate a subscription once per message (by key)
+    final var messageKey = record.getMessageKey();
+
+    // return true if it has already been correlated, otherwise false
+    final var lastCorrelatedMessageKey = subscription.getRecord().getMessageKey();
+    return lastCorrelatedMessageKey == messageKey;
```
[the remark this answers is not in the document]
Comment (korthout) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java:162]: This can only happen if the ordering was broken I think.
- message n was correlating, correlated, and acknowledged
- when message n+1 is correlating, we see that the last correlated message is lower than n+1 (specifically it's `n`)
- so if we would reject this correlation wrongly (`lastCorrelatedMessageKey <= messageKey` so `n <= n+1` is true)

Or do you mean the other way?
- message n was correlating, correlated, and acknowledged
- when message n+1 is correlating, we see that the last correlated message is lower than n+1 (specifically it's `n`)
- so we still accept this correlation correctly (`lastCorrelatedMessageKey >= messageKey` so `n >= n+1` is false)
- But in what case could n actually be larger than n+1?

I prefer rejecting in this case, because something has happened that we didn't expect.

[the remark this answers is not in the document]
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java:162]: Ah sorry my bad, I meant `>=` indeed.

I don't think there could be a case where that happens. But the method checks has it been correlated already, so to me if the `lastCorrelatedMessageKey >= messageKey` than the `messageKey` has already been correlated.

**Comment by korthout** [comment]
Thanks @remcowesterhoud. I've applied the requested changes, and refactored the rejection reason formatting a bit. I've also taken the liberty to apply early returns one of the processors to clean it up a bit. Please have another look before we merge it

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java [hunk 5]
```diff
@@ -96,9 +96,11 @@ final var record = command.getValue();
 
     if (subscription == null) {
       rejectCommand(command, RejectionType.NOT_FOUND, NO_SUBSCRIPTION_FOUND_MESSAGE);
+      return;
 
     } else if (subscription.isClosing()) {
       rejectCommand(command, RejectionType.INVALID_STATE, ALREADY_CLOSING_MESSAGE);
+      return;
 
     } else if (hasAlreadyBeenCorrelated(record, subscription)) {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java:105]: 🙃 The else-ifs can now just be regular ifs

**Review by remcowesterhoud — APPROVED** [review]
🚀

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java (hunk 5 above)
Comment (korthout) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java:105]: 🤡 This is one fewer line per block:

```
if (..) {
  return;
} else if (..) {
///
```

compared to:

```
if (..) {
  return;
}
if (..) {
///
```

Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java:105]: You mean you don't get paid per line? 🫢

**Comment by remcowesterhoud** [comment]
@korthout fyi your CI failed so merging stopped.

**Comment by korthout** [comment]
I'll give it a third attempt, if it fails, I'll rebase on `main`
