### PR TITLE
fix: Preserve initial command context for retried listener job

### LINKED ISSUE #31089: First retried task listener after `EXTRACT_VALUE_ERROR` incident loses original command context
### 

### 

### 

### 

### Description

When a user task operation (e.g., `UPDATE`, `ASSIGN`, or `CLAIM`) triggers task listeners and one of them fails with an `EXTRACT_VALUE_ERROR`, the first listener job retried after resolving the incident does not see the data changed by the original command.

This leads to inconsistent behavior:
- The first retried listener receives headers with values reflecting the user task state before the current command was received.
- The second and subsequent listeners (if defined), receive the correct set of headers as were changed by the original command.

### Steps to reproduce

1. Create a process with a user task that has two `updating` task listeners.
2. One listener should have a valid `type`, another should use an expression that evaluates to a missing variable (`typeExpression("missing_var_name")`).
3. Perform a user task update with multiple attributes changed (`priority`, `candidateUsers`, `dueDate`, `action`).
4. An incident is created due to the missing variable in one listener's expression.
5. Resolve the incident by supplying the missing variable, listener jobs should be re-created and re-tryed.

**🧪 Test to reproduce:**
<details>
<summary>Click here to expand test</summary>

```java
  @Test
  public void retriedTaskListenerShouldHaveAccessToDataProvidedByOriginalCommand() {
    // given: process instance is created with a UT having `updating` listeners
    final long processInstanceKey =
        helper.createProcessInstance(
            helper.createProcessWithZeebeUserTask(
                task ->
                    task.zeebeTaskListener(l -> l.updating().type(listenerType))
                        .zeebeTaskListener(l -> l.updating().typeExpression("missing_var_name"))));

    // when:
    ENGINE
        .userTask()
        .ofInstance(processInstanceKey)
        .withCandidateUsers("bob", "alice")
        .withDueDate("new_due_date")
        .withPriority(88)
        .withAction("custom_update")
        .update();

    // then: assert expected header for the first listener job and complete it
    final Consumer<JobRecordValue> jobHeadersAssertion =
        job ->
            assertThat(job.getCustomHeaders())
                .contains(
                    entry(Protocol.USER_TASK_CANDIDATE_USERS_HEADER_NAME, "[\"bob\",\"alice\"]"),
                    entry(Protocol.USER_TASK_DUE_DATE_HEADER_NAME, "new_due_date"),
                    entry(Protocol.USER_TASK_PRIORITY_HEADER_NAME, "88"),
                    entry(
                        Protocol.USER_TASK_CHANGED_ATTRIBUTES_HEADER_NAME,
                        "[\"candidateUsersList\",\"dueDate\",\"priority\"]"),
                    entry(Protocol.USER_TASK_ACTION_HEADER_NAME, "custom_update"));
    helper.assertActivatedJob(processInstanceKey, listenerType, jobHeadersAssertion);
    ENGINE.job().ofInstance(processInstanceKey).withType(listenerType).complete();

    // then: expect an incident due to missing `assign_listener_var_name` variable
    final var incident =
        RecordingExporter.incidentRecords(IncidentIntent.CREATED)
            .withProcessInstanceKey(processInstanceKey)
            .getFirst();

    Assertions.assertThat(incident.getValue())
        .hasProcessInstanceKey(processInstanceKey)
        .hasErrorType(ErrorType.EXTRACT_VALUE_ERROR)
        .hasErrorMessage(
            """
                Expected result of the expression 'missing_var_name' to be 'STRING', but was 'NULL'. \
                The evaluation reported the following warnings:
                [NO_VARIABLE_FOUND] No variable found with name 'missing_var_name'""");

    // when: fix the missing variable and resolve the incident
    ENGINE
        .variables()
        .ofScope(processInstanceKey)
        .withDocument(Map.of("missing_var_name", listenerType + "_2"))
        .update();
    ENGINE.incident().ofInstance(processInstanceKey).withKey(incident.getKey()).resolve();

    // then: assert and complete the retried task listener job
    helper.assertActivatedJob(processInstanceKey, listenerType, jobHeadersAssertion); // <-  ❌ fails here
    helper.completeRecreatedJobWithType(processInstanceKey, listenerType);

    // assert headers for the next job, they should be same as for the fist one
    helper.assertActivatedJob(processInstanceKey, listenerType + "_2", jobHeadersAssertion);
  }
```

fails with the following error:
```shell
java.lang.AssertionError: 
Expecting map:
  {"io.camunda.zeebe:priority"="50", "io.camunda.zeebe:userTaskKey"="2251799813685256"}
to contain entries:
  ["io.camunda.zeebe:candidateUsers"="["bob","alice"]",
    "io.camunda.zeebe:dueDate"="new_due_date",
    "io.camunda.zeebe:priority"="88",
    "io.camunda.zeebe:changedAttributes"="["candidateUsersList","dueDate","priority"]",
    "io.camunda.zeebe:action"="custom_update"]
but could not find the following map entries:
  ["io.camunda.zeebe:candidateUsers"="["bob","alice"]",
    "io.camunda.zeebe:dueDate"="new_due_date",
    "io.camunda.zeebe:changedAttributes"="["candidateUsersList","dueDate","priority"]",
    "io.camunda.zeebe:action"="custom_update"]
and the following map entries had different values:
  ["io.camunda.zeebe:priority"="50" (expected: "88")]
```
</details>

### Current behavior

The retried first listener receives headers with values reflecting the user task state before the current command was received.

### Expected behavior

The first retried listener should receive the same custom headers with values (reflecting the received user task command) as it did before the failure.

### Environment

SaaS & SM

### Version

- Zeebe: [8.8.0-SNAPSHOT]

### Rootcause

This issue occurs because after retrying the failed command, we skip the `UserTaskCommandProcessor#onCommand` method. As a result, we do not extract values from the command again. Instead, we use the `UserTask` state as it was before the command was processed to create the task listener job.

### Solution ideas

We can provide the `UserTask` from the intermediate state that was already built during the initial command processing (before the transition was interrupted by the incident). This intermediate state contains all the updated attributes, and by using it to re-create a listener job would ensure that it will receive the most recent headers.

### Dev -> QA handover

- Resources:
- Versions to validate: 8.8
- Release version (in which version this feature will be released): 8.8

### Links
- Related stretch goal (potentially solves this issue by skipping re-execution):
  - #24107

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description
This PR fixes an issue where task listener jobs retried after incident resolution lacked the expected headers derived from the original user task command.

### Root cause
When listener job creation failed and was retried after incident resolution, the recreated listener job lost the context of the initial command (e.g., `UPDATE`, `ASSIGN`, `CLAIM`) that triggered the transition. As a result, it did not receive the correct headers such as `assignee`, `dueDate`, `candidateUsers`, `changedAttributes`, `action`, etc. This was due to reading the persisted user task state that represents the task state that was before the transition-triggering command.

### Fix
The issue was resolved by using the value of the retried command directly. After an incident is resolved, the `IncidentResolveProcessor` reconstructs and emits the user task command with the latest user task taken from the intermediate state. This ensures the recreated listener job has access to the correct context.

### Additional improvements (refactoring)
* Refactored `processOperationCommand` for better readability and separation of concerns;
* Skipped redundant `validateCommand` and `onCommand` invocations for retried commands;
* Introduced deterministic sorting for the `changedAttributes` header to ensure consistent listener job metadata;
* Renamed `IncidentRecordWrapper` to `RetryTypedRecord` for better clarity.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #31089

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/UserTaskProcessor.java [hunk 1]
```diff
@@ -165,28 +166,32 @@ private void processDenyTaskListener(final TypedRecord<UserTaskRecord> command)
...
-                handleCommandProcessing(commandProcessor, command, persistedRecord.copy(), intent),
-            rejection -> handleCommandRejection(command, rejection));
+
+    if (isRetriedCommand(command)) {
+      // Skip `validateCommand` and `onCommand` invocations for retried command,
+      // as it was already validated during the original execution
+      finalizeCommandOrCreateTaskListenerJob(commandProcessor, command, command.getValue(), intent);
+    } else {
+      commandProcessor
+          .validateCommand(command)
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/UserTaskProcessor.java:176]: 💭 I've been trying to wrap my head around this part. I agree that we don't have to re-validate commands for which the task is already transitioning. However, we must watch out that we continue to validate commands after resolving certain incidents. I was unable to find examples for this though. I think that is because all task listener related incidents occur after the operation has already started and thus validation has already happened. I haven't been able to proof this though. So, I believe we can apply this solution.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/UserTaskProcessor.java [hunk 2]
```diff
@@ -215,7 +220,11 @@ private void handleCommandProcessing(
     }
   }
 
-  void storeUserTaskRecordRequestMetadata(final TypedRecord<UserTaskRecord> command) {
+  private boolean isRetriedCommand(final TypedRecord<UserTaskRecord> command) {
+    return command instanceof RetryTypedRecord<UserTaskRecord>;
+  }
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/UserTaskProcessor.java:225]: 👍 That's a really easy to understand solution! Well done!

**Review by korthout — APPROVED** [review]
Thanks @ce-dmelnych 🚀 

💭 It took me some time to review this, as I played around with test cases, and tried to see if there's some guarantee that we can use to say that we can safely skip validations on all retried commands. I was unable to, but I think we can just move forward.

👍 LGTM

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/UserTaskProcessor.java (hunk 1 above)
Comment (ce-dmelnych) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/usertask/UserTaskProcessor.java:176]: Thanks, Nico! I also explored whether re-validation might be useful in some scenarios but didn’t find any clear cases. We can always adjust the behavior later if needed.
