### PR TITLE
fix: add input validation and message for tenant id field on tenant creation

### LINKED ISSUE #34152: [Tenants UI] Missing input field validation for the Tenant ID
### 

### 

### 

### 

### Description

There's no UI feedback for the user which indicates that ID has restricted characters in it.

### Steps to reproduce

1. navigate to Create Tenant modal
2. enter any restricted special characters=> no UI feedback
3. Press save button=> there's no error message

### Current behavior

Missing input field validation, missing error message for the failed request.

### Expected behavior

We should validate input field value like we do for the roles for instance. On request failure we should return an error in UI.

### Environment

SM

### Version

- Component Version: main 23.06

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by vitorwtavares**
## Description

Add validation for Tenant ID field on tenant creation modal (including clear error message with the allowed special characters).

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #34152

### CODE REVIEW

File: identity/client/src/pages/tenants/modals/AddModal.tsx [hunk 1]
```diff
@@ -61,8 +67,12 @@ const AddTenantModal: FC<UseModalProps> = ({ open, onClose, onSuccess }) => {
         <TextField
           label={t("tenantId")}
           placeholder={t("tenantIdPlaceholder")}
-          onChange={setTenantId}
+          onChange={(value) => {
+            validateTenantId(value);
+            setTenantId(value);
```
Comment (vsgoulart) [inline identity/client/src/pages/tenants/modals/AddModal.tsx]: For accessibility reasons it's better to run the validation on submit
Could we change that?

**Review by vsgoulart — CHANGES_REQUESTED** [review]
Tests are failing, we need to fix that too

File: identity/client/src/pages/tenants/modals/AddModal.tsx (hunk 1 above)
Comment (vitorwtavares) [reply identity/client/src/pages/tenants/modals/AddModal.tsx]: I took a look at other examples and it seems we're default to validating on `onBlur`, so I'll match that as it also provides a bit more feedback to the user when they change the value on that field but it's probably better than onChange for accessibility.

File: identity/client/src/pages/tenants/modals/AddModal.tsx [hunk 2]
```diff
@@ -26,8 +27,13 @@ const AddTenantModal: FC<UseModalProps> = ({ open, onClose, onSuccess }) => {
   const [name, setName] = useState("");
   const [tenantId, setTenantId] = useState("");
   const [description, setDescription] = useState("");
+  const [isTenantIdValid, setIsTenantIdValid] = useState(true);
+
+  const submitDisabled = loading || !name || !tenantId || !isTenantIdValid;
```
Comment (vsgoulart) [inline identity/client/src/pages/tenants/modals/AddModal.tsx]: Let's be consistent with the rest of the booleans
```suggestion
  const isSubmitDisabled = loading || !name || !tenantId || !isTenantIdValid;
```

**Review by vsgoulart — APPROVED** [review]
