### PR TITLE
fix: show total count on multi instance body selection

### LINKED ISSUE #45553: Wrong instances count on multi instance bodies in modification mode
### 

### 

### 

### 

### Description

The selected instances count in modification mode is wrong when a multi instance subprocess with multiple instance is selected:

Image

### Steps to reproduce

1. Select a process instance with a multi instance sub process (e.g. _Multi-Instance Process_ from demo data)
2. Enter modification mode
3. Select multi instance sub process

### Current behavior

- The modification dropdown shows: _Selected running instances: 1_

### Expected behavior

- The modification dropdown should show all running instances: _Selected running instances: 3_

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- Component Version: 8.9-SNAPSHOT (with `IS_ELEMENT_SELECTION_V2` set true)

### Rootcause

The instance count is probably 1, because 1 element instance is resolved, which is the multi instance body. While this is technically correct, it leads to confusion in the UI.

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by pedesen**
## Description

- Show total element instances count on multi instance body selection in modification mode
- Add test coverage

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #45553

### CODE REVIEW

File: operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx [hunk 1]
```diff
@@ -69,20 +69,33 @@ const ModificationDropdown: React.FC<Props> = observer(
...
+      selectedElementInstanceKey !== null;
+
+    // true if an element is selected from diagram or element history tree,
+    // and a single specific element instance is resolved for the selection
+    const isElementInstanceResolved = resolvedElementInstance !== null;
+
+    let selectedElementRunningInstancesCount = totalRunningInstancesCount;
+    if (isElementInstanceResolved) {
+      if (isSelectedInstanceMultiInstanceBody) {
+        selectedElementRunningInstancesCount = totalRunningInstancesVisible;
```
Comment (christoph-fricke) [inline operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx]: 🔧 I have taken a deep look, and `totalRunningInstancesCount` and `totalRunningInstancesVisible` are the same code logic just different names for the "parser"... 🤨
If I am not missing something, this code could simplified to:
```ts
let selectedElementRunningInstancesCount = totalRunningInstancesCount;
if (isElementInstanceResolved && !isSelectedInstanceMultiInstanceBody) {
    selectedElementRunningInstancesCount = 1;
}
```

Fun Fact: It is basically the inverse multi-instance check I had before using another count in the metadata-popover: https://github.com/camunda/camunda/pull/45940/changes/4d93397dcbfa7e64300d27588e2d7eb2f17e980b#diff-6ef5473f6ea5b7f25ecc095bf16b020b711bbf5d0be4e01c83a274c923579cceL50

**Review by juliasaienko — APPROVED** [review]
Reviewed, agree with the suggestion

File: operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx (hunk 1 above)
Comment (pedesen) [reply operate/client/src/App/ProcessInstance/TopPanel/ModificationDropdown/index.tsx]: Oh, interesting. I updated it.

**Review by vsgoulart — APPROVED** [review]
Can we merge this @pedesen ?
