### PR TITLE
Importers not communicated completion

### LINKED ISSUE #26046: Importer(s) are not communicating import done correctly
**Describe the bug**

When running a benchmark, we observed that the Camunda Exporter failed after restart, [because the Importer doesn't seem to be completed (where it should be).](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22ck-main-exporter%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zeebe-benchmark-test%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22;pinnedLogId=2024-12-12T21:20:50.478899335Z%2F58efh5mbgslw9b7p;cursorTimestamp=2024-12-12T21:20:50.489646788Z;duration=PT1H?inv=1&invt=Abj9IQ&project=zeebe-io)

```
INFO 2024-12-12T21:20:50.478899335Z Waiting for importers to finish, cached record with key 2251799814997670 but did not flush
```

The importer seems to not complete all documents.

import-completed

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

The importers were not correctly marking their import position documents as completed to signify the record readers were done. This was due to missing zeebe indices causing a `NoSuchIndex` exception which means the path through which record reader completion was checked and set was missed.

The fix involves treating a no such index exception as an empty batch with regards to record reader completion check as they signify the same thing (no records to export).

## Checklist

- [x] Given missing zeebe indices record readers can still get marked as completed.

## Related issues

closes #26046

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
Thanks 👍🏼 🚀

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/os/OpensearchFinishedImportingIT.java [hunk 1]
```diff
@@ -363,6 +364,26 @@ public void shouldWriteDefaultEmptyDefaultImportPositionDocumentsOnRecordReaderS
...
+    for (int i = 0; i <= RecordsReaderHolder.MINIMUM_EMPTY_BATCHES_FOR_COMPLETED_READER; i++) {
+      zeebeImporter.performOneRoundOfImport();
+    }
+
+    // then
+    for (final var type : ImportValueType.values()) {
+      await()
+          .atMost(Duration.ofSeconds(30))
+          .until(() -> isRecordReaderIsCompleted("1-" + type.getAliasTemplate()));
+    }
```
Comment (ChrisKujawa) [inline tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/os/OpensearchFinishedImportingIT.java:384]: 🔧 I guess we could also simply request all documents and validate that all are set to complete.

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/es/ElasticsearchFinishedImportingIT.java [hunk 2]
```diff
@@ -372,6 +374,26 @@ public void shouldWriteDefaultEmptyDefaultImportPositionDocumentsOnRecordReaderS
...
+  public void shouldMarkRecordReadersCompletedEvenIfZeebeIndicesDontExist() throws IOException {
+    // given
+    final var record = generateRecord(ValueType.PROCESS_INSTANCE, "8.7.0", 1);
+    EXPORTER.export(record);
+    tasklistEsClient.indices().refresh(new RefreshRequest("*"), RequestOptions.DEFAULT);
+
+    // when 
+    for (int i = 0; i <= RecordsReaderHolder.MINIMUM_EMPTY_BATCHES_FOR_COMPLETED_READER; i++) {
+      zeebeImporter.performOneRoundOfImport();
+    }
```
Comment (ChrisKujawa) [inline tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/es/ElasticsearchFinishedImportingIT.java:387]:
```suggestion

    // when
    for (int i = 0; i <= RecordsReaderHolder.MINIMUM_EMPTY_BATCHES_FOR_COMPLETED_READER; i++) {
      zeebeImporter.performOneRoundOfImport();
    }
```

File: tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/os/OpensearchFinishedImportingIT.java [hunk 3]
```diff
@@ -363,6 +364,26 @@ public void shouldWriteDefaultEmptyDefaultImportPositionDocumentsOnRecordReaderS
...
   }
 
+  @Test
+  public void shouldMarkRecordReadersCompletedEvenIfZeebeIndicesDontExist() throws IOException {
+    // given
+    final var record = generateRecord(ValueType.PROCESS_INSTANCE, "8.7.0", 1);
+    EXPORTER.export(record);
+    openSearchClient.indices().refresh(new RefreshRequest.Builder().index("*").build());
+
+     // when
```
Comment (ChrisKujawa) [inline tasklist/qa/integration-tests/src/test/java/io/camunda/tasklist/os/OpensearchFinishedImportingIT.java:374]:
```suggestion
    // when
```
