### PR TITLE
Fix bug where wrong start event got activated

### LINKED ISSUE #7669: BpmnProcessingException: Expected to activate the none start event of the process but not found
**Describe the bug**
I deployed a process with a timer start event that triggers every 10 seconds. The process worked fine for some time. But at some point, I saw the following failures in the log:

```
io.camunda.zeebe.engine.processing.bpmn.BpmnProcessingException: 
Expected to activate the none start event of the process but not found. 
[context: {intent=ELEMENT_ACTIVATED, elementId=timer-event-process, bpmnElementType=PROCESS, 
elementInstanceKey=2251799987594468, flowScopeKey=-1, processInstanceKey=2251799987594468, 
parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=timer-event-process, 
processVersion=2, processDefinitionKey=2251799813814592}]
```

Looking at Operate, it seems that the duration between two timers increases over time:

image

image

image

image

image

Until it takes minutes to trigger the next timer.

image

**To Reproduce**
It is not clear what causes the problem.

The process has one timer start event with a timer cycle `R/PT10S`. See the [BPMN](https://github.com/zeebe-io/camunda-cloud-smoke-test/blob/main/src/main/resources/bpmn/timer-event.bpmn) (from our smoke-test project :wink:)

image

**Expected behavior**
It creates a new instance of the process every 10 seconds.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.engine.processing.bpmn.BpmnProcessingException: Expected to activate the none start event of the process but not found. [context: {intent=ELEMENT_ACTIVATED, elementId=timer-event-process, bpmnElementType=PROCESS, elementInstanceKey=2251799982896084, flowScopeKey=-1, processInstanceKey=2251799982896084, parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=timer-event-process, processVersion=2, processDefinitionKey=2251799813814592}]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.activateNoneStartEvent(ProcessProcessor.java:116) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$activateStartEvent$7(ProcessProcessor.java:106) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.activateStartEvent(ProcessProcessor.java:103) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$onActivate$2(ProcessProcessor.java:61) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:238) ~[zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onActivate(ProcessProcessor.java:60) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onActivate(ProcessProcessor.java:27) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$3(BpmnStreamProcessor.java:202) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:238) ~[zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:201) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$1(BpmnStreamProcessor.java:133) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:238) ~[zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:130) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:295) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:285) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:253) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:219) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:210) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.1.0.jar:1.1.0]
```

</p>
</details>

[Error Reporing Tool](https://console.cloud.google.com/errors/CIPtl7imgone7AE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911)

[Log Entry](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22integration-worker-1%22%0Aresource.labels.namespace_name%3D%2229c3ebf3-393e-447b-b739-5a56e64e74b5-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2021-08-20T09:00:00.078Z%2F2021-08-20T09:00:00.078Z--PT1H;pinnedLogId=2021-08-20T09:52:44.254185Z%2F3huvuu6oia0xrm2b;cursorTimestamp=2021-08-20T09:52:44.254185Z?project=camunda-cloud-240911)

[Grafana Dashboard](https://grafana-worker-1.internal.ultrawombat.com/d/I4lo7_EZk/zeebe?orgId=1&var-DS_PROMETHEUS=Prometheus&var-namespace=29c3ebf3-393e-447b-b739-5a56e64e74b5-zeebe&var-pod=All&var-partition=All&from=1629410400000&to=1629496800000)

Camunda Cloud Cluster-Id: [29c3ebf3-393e-447b-b739-5a56e64e74b5](https://console.cloud.ultrawombat.com/org/1b8b19aa-3cf4-4cff-8a25-f3dd46efca4d/cluster/29c3ebf3-393e-447b-b739-5a56e64e74b5)

**Environment:**
 - OS: Camunda Cloud 1.1.0
 - Zeebe Version: `1.1.0`
 - Configuration: GA Hardware Package

### LINKED ISSUE #33952: Process instances get started from non-start event instead of signal event
### 

### 

### 

### 

### Description

When a process with a none-start event and a signal start event has multiple instances created by a parent process through broadcasting that signal in a multi-instance process, not all of those instances get started from the signal start event.

### Steps to reproduce

1. Create a process that has a none-start event and a signal start event
2. Create a parent process with a multi-instance sub-process that broadcasts a signal to start a child process for an input collection
3. Start the parent process with a big number of input collection variables (~50+)

Alternatively, run the test case here:
[SignalStartEventBatchBugTest.txt](https://github.com/user-attachments/files/20799115/SignalStartEventBatchBugTest.txt)
or check out the `signal-broadcast-bug-testcase` branch and run `SignalStartEventBatchBugTest`.

### Current behavior

Only some of the child process instances will get started through the signal event. The rest gets started from the none-start event.

### Expected behavior

All child process instances get started through the signal event.

### Environment

SaaS & SM

### Version

- Component Version: 8.8

### Rootcause

Not fully root-caused yet, but it looks like a bug with the command batch size related to the collection input size.

The amount of entries in the input collection and the maxCommandsInBatch size both play into whether this fails or not. E.g.: for input collection size / batch size
succeeds: 4/20, 10/15, 20/3
fails: 4/21, 10/16, 20/4

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Related [support case](https://jira.camunda.com/browse/SUPPORT-27544?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D) and [slack channel](https://camunda.slack.com/archives/C08V6SPGT3R) (internal)

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

On activation of a start event we try to find the first event trigger for this process definition. If this event triggers its process instance key doesn't match the process instance key of the process that gets activated, we activate the none start event.

This code contains the assumption that there is only one event trigger for this process definitions. That doesn't have to be to true. Instead of fetching the first event trigger we should look for one that matches our process instance key. Only if we, after iterating through the state, do not find a matching event trigger we should activate the none start event.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #33952 
closes #7669

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalStartEventTest.java [hunk 1]
```diff
@@ -29,7 +29,7 @@ public class SignalStartEventTest {
   private static final String SIGNAL_NAME_1 = "a";
   private static final String SIGNAL_NAME_2 = "b";
 
-  @Rule public final EngineRule engine = EngineRule.singlePartition();
+  @Rule public final EngineRule engine = EngineRule.singlePartition().maxCommandsInBatch(21);
```
Comment (kristinkomschow) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalStartEventTest.java:37]: Should we add a comment here that briefly explains why we set this? It may be changed or removed otherwise, which would make the new test case useless since it would have passed without this option even before the new test case.

**Review by kristinkomschow — APPROVED** [review]
LGTM, just one small remark

**Comment by kristinkomschow** [comment]
Also, should we create a follow-up issue for cleaning up the event triggers properly?

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalStartEventTest.java (hunk 1 above)
Comment (remcowesterhoud) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalStartEventTest.java:37]: Good point, I forgot to add this one.
