### PR TITLE
fix: update lifecycle policy for existing indices when retention config changes on elasticsearch exporter re-run.

### LINKED ISSUE #16720: Retention policy is not applied to existing zeebe indices when enabled
**Describe the bug**

If you run the zeebe exporter with ilm disabled and enable it later on, previosuly existing indices don't get the policy applied. This leads to those indices staying "forever" and require manual intervention, e.g. reapplication of the policy to those.

**To Reproduce**

1. run zeebe with the elastic/opensearch exporter and disabled ilm:
```
ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_RETENTION_ENABLED=false
```
2. Let it run and create indices
3. Enable the retention and restart
```
ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_RETENTION_ENABLED=true
```
4. Already existing indices lack the policy

**Expected behavior**

The policy needs to applied to all existing zeebe indices

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.2.0+
- Configuration: elasticsearch or opensearch exporter is used

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description

Update lifecycle policy for existing indices when retention config changes on elasticsearch exporter re-run.

The changes adds `lifecycle policy` to existing index settings when `retention` is enabled, and removes it when retention is disabled

## Related issues

closes #16720 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by megglos — APPROVED** [review]
Nice! Great job! I really like you adopted the solution adhering to existing approached like a custom elastic client and corresponding request/response classes as needed. 🙌 

👍 you also thought of the release backport label, that wasn't obvious to be aware of!

❌  wasn't clear before but while we are at it, let's also add this fix to the Opensearch exporter, which is affected by the same bug as that part of the logic and behavior is identical. I only realized this now and this wasn't clear upfront, apologies for that. Would be fine with either doing it at once with one atomic PR or do a follow-up would leave that you.

Would also like to align on the other more minor suggestions I made.

Still pre-approving as the ❌  can be a follow-up so not blocking.

**Comment by mustafadagher** [comment]
💭 Changes like these, while they fix bugs, they might also impact the performance. (I'm not sure on a production cluster how many indices would the call impact, and how performant is elasticsearch applying the PUT command).

In previous companies, I'd guard them with a `feature toggle/flag`, and monitor their performance for a while after rollout.

I'm not sure if we use `feature toggles` around zeebe for similar purposes. And also if we have any dashboards that monitor our exporters.

CC: @megglos @korthout

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java [hunk 1]
```diff
@@ -195,4 +198,65 @@ final var record = factory.generateRecord();
         .extracting(ComponentTemplateWrapper::name)
         .isEqualTo(config.index.prefix);
   }
+
+  @Test
+  void shouldUpdateIndexLifecycleSettingsOnRerunWhenRetentionConfigChanges() {
```
[the remark this answers is not in the document]
Comment (mustafadagher) [reply zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:203]: While I tested this manually to work, another test case for the same wouldn't harm indeed!

File: zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java [hunk 2]
```diff
@@ -356,6 +358,23 @@ private void createValueIndexTemplate(final ValueType valueType) {
...
+    } else {
+      acknowledged = client.bulkPutIndexLifecycleSettings(null);
+    }
+
+    if (!acknowledged) {
+      log.warn("Failed to acknowledge the the update of retention policy for existing indices");
+    }
+  }
+
+  void setIndexTemplatesCreated(final boolean indexTemplatesCreated) {
```
[the remark this answers is not in the document]
Comment (mustafadagher) [reply zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java:374]: I agree with you on how you feel. My fingers also hesitated writing it. It's only `package-private` though. For now, it felt like a safer call than to change how the whole check works just for the sake of one test method. 
But I can look into making it better.

**Comment by megglos** [comment]
> 💭 Changes like these, while they fix bugs, they might also impact the performance. (I'm not sure on a production cluster how many indices would the call impact, and how performant is elasticsearch applying the PUT command).
> 
> In previous companies, I'd guard them with a `feature toggle/flag`, and monitor their performance for a while after rollout.
> 
> I'm not sure if we use `feature toggles` around zeebe for similar purposes. And also if we have any dashboards that monitor our exporters.
> 
> CC: @megglos @korthout

Good point, updating the settings with a wildcard query should only happens once after a restart on the very first export and then not again though. So given a high cardinality of record exports the impact of one potentially bad performing export call due to the overhead is an acceptable risk. Also it effectively depends on the existing amount of indices, which should be at most one per type and day. 

In contrast to that we already to N requests in that case for every index template which are individual request/response interactions, which might as of now already cause a bigger delay.

Would be curious if you could do a one off test here, having like 30 days of indices for each type and check the duration of the settings requests, to be sure the impact is indeed not that big of deal, wdyt?

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (megglos) [reply zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:203]: as greed not needed

**Comment by mustafadagher** [comment]
> > 💭 Changes like these, while they fix bugs, they might also impact the performance. (I'm not sure on a production cluster how many indices would the call impact, and how performant is elasticsearch applying the PUT command).
> > In previous companies, I'd guard them with a `feature toggle/flag`, and monitor their performance for a while after rollout.
> > I'm not sure if we use `feature toggles` around zeebe for similar purposes. And also if we have any dashboards that monitor our exporters.
> > CC: @megglos @korthout
> 
> Good point, updating the settings with a wildcard query should only happens once after a restart on the very first export and then not again though. So given a high cardinality of record exports the impact of one potentially bad performing export call due to the overhead is an acceptable risk. Also it effectively depends on the existing amount of indices, which should be at most one per type and day.
> 
> In contrast to that we already to N requests in that case for every index template, which might as of now already cause a bigger delay due to the larger IO overhead on network level.
> 
> Would be curious if you could do a one off test here, having like 30 days of indices for each type and check the duration of the settings requests, to be sure the impact is indeed not that big of deal, wdyt?
> 
> As it is a fix indeed I would then rather look for a better solution than a toggle, as without this behavior we have a bug 😅

As discussed in our conversation, elasticsearch has a default timeout for this call of `30s`. I will rather create a test to verify the call won't timeout. And that should be good enough of a validation for performance's sake in this case.

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java [hunk 3]
```diff
@@ -195,4 +210,165 @@ final var record = factory.generateRecord();
...
+
+      /* Tests when retention is later enabled all indices should have lifecycle policy */
+      // given
+      configureExporter(true);
+      final var record2 = factory.generateRecord(ValueType.JOB);
+
+      // when
+      await("New record is exported, and existing indices are updated")
+          .atMost(Duration.ofSeconds(30))
+          .until(() -> export(record2));
```
Comment (megglos) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:326]: 🔧 I don't think we need to test the non-application of the policy here?  this is already covered by `shouldAddIndexLifecycleSettingsToExistingIndicesOnRerunWhenRetentionIsEnabled`, would thus suggest to shorten it a bit.

```suggestion
      // given
      configureExporter(false);
      final var records = new ArrayList<Record<RecordValue>>();
     // using 498 here as we will export one more record after (1 main shard, 1 replica)
      final int limit = 498;
      for (int i = 0; i < limit; i++) {
        final var record = factory.generateRecord(ValueType.JOB);
        records.add(record);
        export(record);
      }

      // when
      configureExporter(true);
      final var record2 = factory.generateRecord(ValueType.JOB);

      // when
      await("New record is exported, and existing indices are updated")
          .atMost(Duration.ofSeconds(30))
          .until(() -> export(record2));
```

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java [hunk 4]
```diff
@@ -58,6 +70,8 @@ final class ElasticsearchExporterIT {
   private final RecordIndexRouter indexRouter = new RecordIndexRouter(config.index);
 
   private TestClient testClient;
+  private ExporterTestContext exporterTestContext;
+  private int exportedRecordsCounter = 0;
```
Comment (megglos) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:74]: ❌  I would prefer to clear elastic after/before each test instead of handling test side effects via this counter. Then you can be sure you always have clean state and not worry about what other tests do.
```
  @BeforeEach
  void cleanup() {
    testClient.deleteIndices();
  }
```

with extending TestClient with https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html which will also require you to set the env var`action.destructive_requires_name=false` on the test container so you can do wildcard deletes.

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java [hunk 5]
```diff
@@ -195,4 +210,165 @@ final var record = factory.generateRecord();
...
+    exporter.export(record);
+    exportedRecordsCounter++;
+    return true;
+  }
+
+  @Nested
+  @TestMethodOrder(OrderAnnotation.class)
+  final class IndexSettingsTest {
+    @Test
+    @Order(1)
```
Comment (megglos) [inline zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:224]: ❓ why does the order matter?

**Review by megglos — APPROVED** [review]
Glad you could assess the settings update overhead doesn't trigger a timeout, even on hitting the shard count limit! Great job!

The only thing I would like to change is the handling of side-effects in the tests, instead of using a counter to dynamically change the record count based on existing indices, I would rather go for cleaning up elastic after each test.

Pre-approving to unblock once ready, no need for another review if you agree.

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java (hunk 4 above)
Comment (mustafadagher) [reply zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:74]: thanks a lot! that's a great hint!

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java (hunk 5 above)
Comment (mustafadagher) [reply zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java:224]: will remove now, it mattered when I relied on state (which I hated, it's ugly)

**Comment by mustafadagher** [comment]
nooo not agaain 😢 😢

**Comment by megglos** [comment]
likely because of the sub-path changes again, basically whenever we have new files a backport fails
