### PR TITLE
Display error on login page to provide user feedback

### LINKED ISSUE #29849: No error is displayed if the login credentials are invalid
#### Description  
When a user enters incorrect login credentials, no error message is displayed. This makes it unclear whether the login attempt failed due to invalid credentials or another issue.  

#### Steps To Reproduce  
1. Open the login page.  
2. Enter an incorrect username and/or password.  
3. Click the login button.  
4. Observe that no error message is shown.  

#### Expected Behavior  
- A clear error message should be displayed when login credentials are invalid.  
- The user should be informed that the credentials are incorrect and prompted to retry.  

#### Actual Behavior  
- The login form does not display any error message.  
- The user is left without feedback on why the login attempt failed.

### PR DESCRIPTION
**Pull request by vitorwtavares**
## Description

Display error on login page to provide user feedback

- Add notification on failed login
- Add validation for fields when one of them is empty on blur and on submit

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #29849

### CODE REVIEW

**Comment by vitorwtavares** [comment]
Note for the reviewer: the first and last commits can be ignored, long story short - I thought about adding zod to do some validation but realized it was not needed for this use case, we can still add it in a later date if we decide to have more thorough validation, but for now I think the solution I came up with it pretty good.

File: identity/client/src/pages/login/LoginPage.tsx [hunk 1]
```diff
@@ -41,18 +69,31 @@ const LoginForm: React.FC<LoginFormProps> = ({ onSuccess }) => {
...
+              hasError: true,
+              errorText: "Username field is required",
+            });
+          } else {
+            setUsernameError({
+              hasError: false,
+              errorText: "",
+            });
+          }
+        }}
```
Comment (vsgoulart) [inline identity/client/src/pages/login/LoginPage.tsx:90]: We don't have this behavior on Tasklist or Operate. I think you should check it if it's not better to be consistent across apps.

IMO we should just remove it

File: identity/client/src/pages/login/LoginPage.tsx [hunk 2]
```diff
@@ -86,10 +140,19 @@ export const LoginPage: React.FC = () => {
...
   const onSuccess = useCallback(() => {
     window.location.href = redirectUrl ?? "/identity/users";
   }, [redirectUrl]);
+  const onFail = useCallback(() => {
+    enqueueNotification({
+      kind: "error",
+      title: "Login failed",
+      subtitle: "That username and password combination is incorrect.",
+    });
+  }, [enqueueNotification]);
```
Comment (vsgoulart) [inline identity/client/src/pages/login/LoginPage.tsx:155]: Here it's also inconsistent. We don't show toast notifications for failed login credentials

**Review by vsgoulart — COMMENTED** [review]
@vitorwtavares The code looks ok but I think we should double check if we should not be consistent with the other apps

**Comment by vitorwtavares** [comment]
@vsgoulart I get your points, but I think this is the whole point of this issue that was raised, that we don't have enough feedback on failed attempts and would like to have more. I added these things to be in line with what we're using on Identity (toast notifications for most success/fail feedback for operations) and some field validation with user feedback.

On Operate/Tasklist from what I've seen we're using form and form validation libraries, but I think that's a bit overkill for the current state of Identity, therefore I'm not sure what to add in terms of validation and user feedback if we don't add these things that differ from the existing apps (toast notification, validation on fields).

@gastonpillet01 If you could give your opinion here on what to add or not to add that would be great too (in the matter of toast notifications and/or fields validation.

**Comment by gastonpillet01** [comment]
@vitorwtavares in Operate we have the same approach (see image). Currently I can not see that login screen as I have no localhost SNAPSHOT running. I have a 8.6 Docker installation and all components login are handled by Identity.

Having that Carbon toast is ok, that is his intended use, and the error messages under empty or wrong fields are ok, as long as they use the correct color tokens for text = $text-error, and vectors with $support-error (borders, icons, etc).

image

**Comment by vsgoulart** [comment]
@gastonpillet01 But that's not how this PR implements it. Operate/Tasklist has an inline notification this PR adds a toast notification for Identity

image

Regarding the validation on blur, I was wrong on that. We implement like on the other apps

File: identity/client/src/pages/login/LoginPage.tsx (hunk 1 above)
Comment (vsgoulart) [reply identity/client/src/pages/login/LoginPage.tsx:90]: This comment is wrong, we do validate on blur in Operate and Tasklist

**Comment by gastonpillet01** [comment]
@vsgoulart that toast notification only remains 5 seconds and then dissapear, not helping the user with providing context/feedback about what happened. For better UX, message should be fixed in the screen, like inline toasts. (see image)
image

File: identity/client/src/pages/login/styled.ts [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+  width: 100%;
+  font-size: ${spacing04};
+  font-weight: 400;
+  text-align: center;
+  line-height: 1.3333;
+
+  a {
+    font-size: ${spacing04};
+  }
+`;
```
Comment (vsgoulart) [inline identity/client/src/pages/login/styled.ts:66]: If you use SCSS you can do use this util for [the font tokens](https://github.com/camunda/camunda/blob/main/tasklist/client/src/common/auth/Login/styles.module.scss#L43)

**Review by vsgoulart — APPROVED** [review]

File: identity/client/src/pages/login/styled.ts (hunk 3 above)
Comment (vitorwtavares) [reply identity/client/src/pages/login/styled.ts:66]: @vsgoulart Do you mean it doesn't work with styled components?

Comment (vsgoulart) [reply identity/client/src/pages/login/styled.ts:66]: @vitorwtavares  The syntax `@include type.type-style('legal-01');` is SCSS only

I would actually recommend against adding more `styled-components` to our projects. I would like to start an initiative to remove it since it requires less strict CSP config which are important to us, it has some performance impact and it prevents us from using these SCSS utils Carbon provides us.

But since this initiative is not official yet I won't block this PR but you could at least use the vars like the screenshot below (which is what that Carbon util does)
image
