### PR TITLE
fix: assigning roles to groups in initialization

### LINKED ISSUE #48856: Assigning roles to groups during initialization doesn't work
### 

### 

, 

### 

### 

### Description

When creating a group using `camunda.security.initialization.groups`, assigning roles to it doesn't work.

### Steps to reproduce

Start the current main branch using the following configuration:
```
CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_TENANT_ID="test-config-tenant"
CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_NAME="test config tenant"
CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_DESCRIPTION="test tenant description"
CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_USERS='demo,test,UserA,UserB,UserC'
CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_ROLES='admin,connectors,R4,test-config-role'
CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_GROUPS='adminGr,connectorsGr,R4GR,test-config-group'
CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_CLIENTS='adminCl,connectorsCl,msdfdsjhb'
CAMUNDA_SECURITY_INITIALIZATION_TENANTS_0_MAPPING_RULES='M1,m2,m.'
CAMUNDA_SECURITY_INITIALIZATION_ROLES_0_ROLE_ID=test-config-role
CAMUNDA_SECURITY_INITIALIZATION_ROLES_0_NAME='Test Role'
CAMUNDA_SECURITY_INITIALIZATION_ROLES_0_DESCRIPTION='A cool test role!'
CAMUNDA_SECURITY_INITIALIZATION_ROLES_0_USERS='UserA,UserB,UserC'
CAMUNDA_SECURITY_INITIALIZATION_ROLES_0_GROUPS='adminGr,connectorsGr,R4GR,test-config-group'
CAMUNDA_SECURITY_INITIALIZATION_ROLES_0_CLIENTS='adminCl,connectorsCl,R4Cl.,msdfdsjhb'
CAMUNDA_SECURITY_INITIALIZATION_ROLES_0_MAPPING_RULES='M1,m2,m.'
CAMUNDA_SECURITY_INITIALIZATION_GROUPS_0_GROUP_ID=test-config-group
CAMUNDA_SECURITY_INITIALIZATION_GROUPS_0_NAME='Test Group'
CAMUNDA_SECURITY_INITIALIZATION_GROUPS_0_DESCRIPTION='A cool test group!'
CAMUNDA_SECURITY_INITIALIZATION_GROUPS_0_USERS='UserA,UserB,UserC'
CAMUNDA_SECURITY_INITIALIZATION_GROUPS_0_CLIENTS='adminCl,connectorsCl,msdfdsjhb'
CAMUNDA_SECURITY_INITIALIZATION_GROUPS_0_MAPPING_RULES='M1,m2,m.'
CAMUNDA_SECURITY_INITIALIZATION_GROUPS_0_ROLES='admin,connectors,R4,test-config-role'
```

### Current behavior

the `test-config-group` will only have the role `test-config-role`, not `admin` or `connectors`.

### Expected behavior

the `test-config-group` has all three roles `test-config-role`, `admin` and `connectors`.

### Workaround

Do it the other way round. Set the group as member of the role or defaultRole.

### Environment

SM

### Version

current main branch

### Rootcause

In `io.camunda.zeebe.engine.processing.identity.initialize.GroupConfigurer` all member types are returned as `GroupEntity`,
but this kind of relation must be creating the other way round using a `RoleEntity` that has the group as member.

### Solution ideas

1. Keep this way of configuration (which matches the Identity UI) and add a special case for the role-group relationship.
2. Remove the possibility for this way of creating the relation and limit users to create it from role -> group.

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by mrm1st3r**
## Description

fix assigning roles to groups in initialization

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #48856

### CODE REVIEW

File: qa/acceptance-tests/src/test/java/io/camunda/it/identity/InitializeEntityRelationsIT.java [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+      new TestUser(
+          USERNAME_ADMIN,
+          DEFAULT_PASSWORD,
+          List.of(
+              new Permissions(GROUP, READ, List.of("*")),
+              new Permissions(ROLE, READ, List.of("*")),
+              new Permissions(TENANT, READ, List.of("*"))));
+
+  @Test
+  void shouldMakeRoleGroupRelations(
```
Comment (Ben-Sheppard) [inline qa/acceptance-tests/src/test/java/io/camunda/it/identity/InitializeEntityRelationsIT.java:101]: 🔧 NABD but a phrasing thing, I would say that these tests are related to ensuring that entities are assigned to the parent under test so a method name like `shouldAssignEntitiesToAGroup` may be easier to read

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/GroupConfigurer.java [hunk 2]
```diff
@@ -43,13 +44,32 @@ public List<GroupRecord> configureMembers(final ConfiguredGroup group) {
...
+
+  private static Stream<RoleRecord> mapToRoleMembers(
+      final String groupId, final List<String> memberIds) {
+    if (memberIds == null) {
+      return Stream.empty();
+    }
+    return memberIds.stream()
+        .map(
+            id ->
+                new RoleRecord()
```
Comment (Ben-Sheppard) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/GroupConfigurer.java:67]: ❓ I think the answer is "yes" but here, I believe the roles need to be in place as there is an existence check, am I right in remembering that before we do any of the member assigning tasks we make sure all the "parents" are in place i.e. groups, roles, tenants?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/IdentitySetupInitializer.java [hunk 3]
```diff
@@ -150,6 +150,11 @@ private IdentitySetupRecord buildSetupRecord() {
         .getGroups()
         .forEach(
             group -> groupConfigurer.configureMembers(group).forEach(setupRecord::addGroupMember));
+    initialization
+        .getGroups()
+        .forEach(
+            group ->
+                groupConfigurer.configureRoleMembers(group).forEach(setupRecord::addRoleMember));
```
[the remark this answers is not in the document]
Comment (Ben-Sheppard) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/IdentitySetupInitializer.java:157]: This is a good spot Copilot

**Review by Ben-Sheppard — COMMENTED** [review]
On the whole the changes seem good, just some small comments (+ copilot) and a question for my understanding

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/GroupConfigurer.java (hunk 2 above)
Comment (mrm1st3r) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/initialize/GroupConfigurer.java:67]: Yes, exactly. That is ensured by the order of follow up commands in `io.camunda.zeebe.engine.processing.identity.IdentitySetupInitializeProcessor#processRecord`

**Review by Ben-Sheppard — APPROVED** [review]
