### PR TITLE
fix: stabilize flakey Batch Operation tests

### LINKED ISSUE #34600: BatchOperationLifecycleManagementTest and BatchOperationAuthorizationIT tests are flaky
BatchOperationLifecycleManagementTest and BatchOperationAuthorizationIT tests are flaky
> Top 5 flakiest tests yesterday:
> ```
> • 60x BatchOperationLifecycleManagementTest.shouldResumeBatchOperation
> • 33x BatchOperationAuthorizationIT.restrictedUserShouldStartBatchOperationWithRestrictedItemsOnly(CamundaClient, CamundaClient)
> • 23x BatchOperationAuthorizationIT.restrictedUserShouldStartBatchOperationAndFailOnRestrictedItem(CamundaClient, CamundaClient)
> ```
> :bar_chart: Check out [Grafana for links and more details](https://dashboard.int.camunda.com/d/ae2j69npxh3b4f/flaky-tests-camunda-camunda-monorepo?orgId=1&from=now-1d%2Fd&to=now-1d%2Fd&timezone=browser&var-branch=main).

See https://camunda.slack.com/archives/C071KP5BTHB/p1751350292699259

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description

- `shouldResumeBatchOperation`
The batch operation might complete too fast, or take too long to complete. So we wait for either state
- `BatchOperationAuthorizationIT` tests
After https://github.com/camunda/camunda/issues/33936, items won't be exported until BO is completed or failed.
We should wait for the BO to complete before asserting the items

- `shouldResumeOnAllPartitions`
 The assert fails because it's expecting only the exact value sequence since the recording exporter has been reset. but it could be that distribution was slower and the recording exporter reset before one partition appended `suspended`

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #34600

### CODE REVIEW

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/BatchOperationLifecycleManagementTest.java [hunk 1]
```diff
@@ -147,7 +148,12 @@ void shouldResumeBatchOperation() {
...
 
-    // then it's again active and can complete
-    waitForBatchOperationStatus(camundaClient, batchOperationId, BatchOperationState.ACTIVE);
+    // Then it should be activated again, and eventually completed
+    // Note: The batch operation might complete too fast, or take too long to complete. So we wait
+    // for either state.
+    waitForBatchOperationStatus(
+        camundaClient,
+        batchOperationId,
+        Set.of(BatchOperationState.ACTIVE, BatchOperationState.COMPLETED));
```
Comment (stoerti) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/BatchOperationLifecycleManagementTest.java:157]: 🔧 The scheduler interval is configured to 3 seconds in line 56. In the engine tests I have set this to some rather infinite number to deactivate the scheduler. Then we never reach a `COMPLETED` state, but for the tests in this class this should be irrelevant, since we only want to verify that a batch operation can be canceled/paused/resumed and that the state is reflected in the secondaryDb accordingly.

The assert `status in (ACTIVE, COMPLETED)` may solve the flakiness but is a bit vague.

**Review by stoerti — APPROVED** [review]
I have a remark to the second flaky test, but approved anyway since it solves the flakiness.

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/BatchOperationLifecycleManagementTest.java (hunk 1 above)
Comment (mustafadagher) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/BatchOperationLifecycleManagementTest.java:157]: @stoerti if you check the flaky test failures, like [this one](https://github.com/camunda/camunda/actions/runs/15996749787/attempts/1#summary-45121841797).. you can see the following. 
```java
org.awaitility.core.ConditionTimeoutException: 
Condition with alias 'batch operation should have state ACTIVE' didn't complete within 2 minutes because assertion condition defined as a Lambda expression in io.camunda.it.util.TestHelper 
expected: ACTIVE
 but was: COMPLETED
```

So it definitely reaches `COMPLETED`

Comment (stoerti) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/BatchOperationLifecycleManagementTest.java:157]: Yes. Because the configured 3 seconds is an interval where the scheduler eventually picks up the resumed batch operation and completes it before the assert can read the `ACTIVE` state ( the time between `ACTIVE` and `COMPLETE` is too short). In [BatchOperationMultiPartitionTest](https://github.com/camunda/camunda/blob/557f56ae2fb95e9c9781792f779b15010c4691b6/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationMultiPartitionTest.java#L47) I have set it to one day. That basically disables the scheduler and keeps the batch operation in `ACTIVE` state.

**Comment by mustafadagher** [comment]
Still seeing some failures 
https://github.com/camunda/camunda/actions/runs/16002200476/attempts/1#summary-45139832534

**Comment by mustafadagher** [comment]
> Still seeing some failures https://github.com/camunda/camunda/actions/runs/16002200476/attempts/1#summary-45139832534

Tried resolving the items issues with waiting, but the configuration error for duplicate user is weird, since users are cached in the entity manager

> <no name>: io.camunda.it.auth.BatchOperationAuthorizationIT
Failed with code 409: 'Conflict'. Details: 'class ProblemDetail {
    type: about:blank
    title: ALREADY_EXISTS
    status: 409
    detail: Command 'CREATE' rejected with code 'ALREADY_EXISTS': Expected to create user with username 'admin', but a user with this username already exists
    instance: /v2/users
}'
io.camunda.client.api.command.ProblemException: 
Failed with code 409: 'Conflict'. Details: 'class ProblemDetail {
    type: about:blank
    title: ALREADY_EXISTS
    status: 409
    detail: Command 'CREATE' rejected with code 'ALREADY_EXISTS': Expected to create user with username 'admin', but a user with this username already exists
    instance: /v2/users
}'
	at io.camunda.client.impl.http.ApiCallback.handleErrorResponse(ApiCallback.java:123)
	at io.camunda.client.impl.http.ApiCallback.completed(ApiCallback.java:62)
	at io.camunda.client.impl.http.ApiCallback.completed(ApiCallback.java:32)
	at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:148)
	at org.apache.hc.core5.concurrent.ComplexFuture.completed(ComplexFuture.java:72)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$2$1.completed(InternalAbstractHttpAsyncClient.java:321)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer$1.completed(AbstractAsyncResponseConsumer.java:101)
	at org.apache.hc.core5.http.nio.entity.AbstractBinAsyncEntityConsumer.completed(AbstractBinAsyncEntityConsumer.java:87)
	at org.apache.hc.core5.http.nio.entity.AbstractBinDataConsumer.streamEnd(AbstractBinDataConsumer.java:83)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer.streamEnd(AbstractAsyncResponseConsumer.java:142)
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.streamEnd(HttpAsyncMainClientExec.java:283)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamHandler.dataEnd(ClientHttp1StreamHandler.java:285)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamDuplexer.dataEnd(ClientHttp1StreamDuplexer.java:371)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onInput(AbstractHttp1StreamDuplexer.java:340)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.inputReady(AbstractHttp1IOEventHandler.java:64)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.inputReady(ClientHttp1IOEventHandler.java:41)
	at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:143)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:176)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:125)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:92)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	at java.base/java.lang.Thread.run(Thread.java:1583)

File: qa/acceptance-tests/src/test/java/io/camunda/it/auth/BatchOperationAuthorizationIT.java [hunk 2]
```diff
@@ -202,25 +204,18 @@ void restrictedUserShouldStartBatchOperationWithRestrictedItemsOnly(
...
     assertThat(batchOperationCreatedResponse).isNotNull();
     final var batchOperationId = batchOperationCreatedResponse.getBatchOperationId();
-    waitForBatchOperation(camundaClient, batchOperationId, 1);
+    waitForBatchOperation(camundaClient, batchOperationId, 1, BatchOperationState.COMPLETED);
 
     // then
-    final var batchOperationResponse =
-        camundaClient.newBatchOperationGetRequest(batchOperationId).send().join();
-    assertThat(batchOperationResponse).isNotNull();
-    assertThat(batchOperationResponse.getOperationsTotalCount()).isEqualTo(1);
```
Comment (mustafadagher) [inline qa/acceptance-tests/src/test/java/io/camunda/it/auth/BatchOperationAuthorizationIT.java:211]: 💭 this was unnecessary, since the exact same is verified inside `waitForBatchOperation`
