### PR TITLE
fix: refresh session's authentication on api calls

### LINKED ISSUE #37539: authentications is not refresh with api calls using the session cookie
### 

### 

### 

### 

### Description

When a user logs in, we determine their associations once (membership in roles, groups, tenants; application authorizations) and put them into the web session.

When these associations change (e.g. user is removed from a group; authorizations change), then this is not reflected in this cached state. Accordingly, as long as the user's session is alive, the changes do not take effect for them.

This problem is already fixed for webapp but the api calls from webapps when using session cookie still has the problem.

### Steps to reproduce

See examples in description of #34698 

### Current behavior

The authentication object of api calls don't trigger the refresh authentication.

### Expected behavior

The authentication object stored in a session get updated for api calls as well.

### Environment

SaaS & SM

### Version

- Component Version: [e.g. 2.0.0]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Related to: #34698

### PR DESCRIPTION
**Pull request by maryarm**
## Description

When a user logs in, we determine their associations once (membership in roles, groups, tenants; application authorizations) and put them into the web session.

When these associations change (e.g. user is removed from a group; authorizations change), then this is not reflected in this cached state. Accordingly, as long as the user's session is alive, the changes do not take effect for them.

This problem is already fixed for webapp but the api calls from webapps when using session cookie still has the problem.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #37539

### CODE REVIEW

File: authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java
Comment (bmudric) [inline authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java:1]: @maryarm it seems it would be a good idea to duplicate (or expand) this test so the OIDC configuration is also covered. I'm assuming that only Basic is covered in this test class based on the lack of extra configuration. 
WDYT?

Comment (maryarm) [reply authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java:1]: Good point, I'm going to add oidc test as well.

File: authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java [hunk 1]
```diff
@@ -31,172 +32,241 @@
...
+              successfulRequests.incrementAndGet();
+            } catch (final Exception e) {
+              throw new RuntimeException(e);
+            }
+          };
+
+      final Thread[] threads = new Thread[5];
+      for (int i = 0; i < threads.length; i++) {
+        threads[i] = new Thread(requestTask);
+        threads[i].start();
```
Comment (bmudric) [inline authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java]: I tried running the tests locally and they are still flaky. I put the testing on repeat and increased thread count to 100 to induce failure faster. There seems to be an occasional issue (ca 5% of runs) with Mockito stubbing where it throws an exception due to `refresh()` not being stubbed properly. There could be a hidden underlying issue but I could not find it quickly.
I tried using a `CountDownLatch` and `ExecutorService` but that did not help.
The only thing that made an effect is separating the spin of the Threads a bit, even by sleeping for 1 ms.
Therefore I suggest we add the following line to stabilize the test, unless someone has the time to dig more into root causes now :) 
```suggestion
        threads[i].start();
        Thread.sleep(10);
```

File: authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java [hunk 2]
```diff
@@ -31,172 +32,241 @@
...
+        final CamundaAuthenticationProvider authenticationProvider,
+        final MockMvcTester mockMvcTester)
+        throws InterruptedException {
+      doAnswer(
+              invocation -> {
+                Thread.sleep(100);
+                return null; // because it's a void method
+              })
+          .when(authenticationProvider)
+          .refresh();
```
Comment (bmudric) [inline authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java]: I could not detect a difference between doing nothing and this sleep block (that only evaluates once).
So I suggest we just use `doNothing()`, unless there is a specific reason not to.
```suggestion
      doNothing().when(authenticationProvider).refresh();
```

**Review by bmudric — CHANGES_REQUESTED** [review]
Thank you for adding the tests!
Check out my comment on stabilizing the run, please.

File: authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java (hunk 2 above)
Comment (maryarm) [reply authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java]: It was for simulation the delay of refresh to be able to test that we have the potential of race condition without having so many threads.

Comment (bmudric) [reply authentication/src/test/java/io/camunda/authentication/filters/SessionAuthenticationRefreshFilterTest.java]: OK, got it, ignore my comment then :)

**Review by bmudric — APPROVED** [review]

**Comment by romansmirnov** [comment]
See my comment: https://github.com/camunda/camunda/issues/37539#issuecomment-3257984836

**Review by ana-vinogradova-camunda — APPROVED** [review]
LGTM 🚀 
Thank you @maryarm !
