### PR TITLE
Don't create ZeebeState on compaction

### LINKED ISSUE #3877: Why I see weird FeelEngine logs in unexpected threads
**Describe the bug**

I'm doing currently lot of benchmarks and I saw now at several times the following log
`INFO  org.camunda.feel.FeelEngine - Engine created` in unexpected places. Furthermore with unexpected threads. How can this happen? :sweat_smile: @saig0 any idea?

For example on log compaction:
```
I 2020-02-19T01:03:24.736209104Z 2020-02-19 01:03:24.736 [] [Broker-0-StateReplication-3] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/48099528-2-1582074203540-112094357523920, metadata=DbSnapshotMetadata{index=48099528, term=2, timestamp=2020-02-19 01:03:23,540, position=112094357523920}}
 
I 2020-02-19T01:03:24.893153639Z 2020-02-19 01:03:24.892 [Broker-0-DeletionService-3] [Broker-0-zb-actors-3] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.spi.JavaValueMapper@ffd271f)), function-provider: org.camunda.feel.interpreter.FunctionProvider$EmptyFunctionProvider$@7b94b62b]
 
I 2020-02-19T01:03:24.895182940Z 2020-02-19 01:03:24.894 [Broker-0-DeletionService-3] [Broker-0-zb-actors-3] DEBUG io.zeebe.broker.system - The last processed position for snapshot /usr/local/zeebe/data/raft-partition/partitions/3/snapshots/46771469-2-1582072401300-109019157358104 is 109049227545992
 
I 2020-02-19T01:03:24.895691869Z 2020-02-19 01:03:24.895 [Broker-0-DeletionService-3] [Broker-0-zb-actors-3] DEBUG io.zeebe.broker.system - The lowest exported position for snapshot /usr/local/zeebe/data/raft-partition/partitions/3/snapshots/46771469-2-1582072401300-109019157358104 is 109049226466064
 
```

Or on start up, https://github.com/zeebe-io/zeebe/issues/3028#issuecomment-588061106

```
I 2020-02-18T19:47:49.286950310Z 2020-02-18 19:47:49.286 [] [raft-server-1-raft-partition-partition-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.spi.JavaValueMapper@1a8f4603)), function-provider: org.camunda.feel.interpreter.FunctionProvider$EmptyFunctionProvider$@731a21ff]
 
I 2020-02-18T19:47:49.836773481Z 2020-02-18 19:47:49.836 [GatewayTopologyManager] [Broker-1-zb-actors-0] DEBUG io.zeebe.gateway - Received REACHABILITY_CHANGED for broker 0, do nothing.
 
I 2020-02-18T19:47:50.001219551Z 2020-02-18 19:47:50.000 [] [raft-server-1-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - The last processed position for snapshot /usr/local/zeebe/data/raft-partition/partitions/1/pending/1800815-17-1582054781144 is 4028680908576
 
I 2020-02-18T19:47:50.019909697Z 2020-02-18 19:47:50.019 [] [raft-server-1-raft-partition-partition-1] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/1800815-17-1582054781144-4028680908576, metadata=DbSnapshotMetadata{index=1800815, term=17, timestamp=2020-02-18 07:39:41,144, position=4028680908576}}
 
I 2020-02-18T19:47:50.311516613Z 2020-02-18 19:47:50.311 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-1 [7/11]: cluster services started in 11104336 ms
 
```

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

 Introduces a LastProcessState, which can be used by the ZeebeState and the StatePositionSupplier.
 This avoids to creating the ZeebeState in the StatePositionSupplier, which does a lot other things like creating FeelEngine etc. 

It caused on compaction log messages like:

```
I 2020-02-19T01:03:24.736209104Z 2020-02-19 01:03:24.736 [] [Broker-0-StateReplication-3] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/48099528-2-1582074203540-112094357523920, metadata=DbSnapshotMetadata{index=48099528, term=2, timestamp=2020-02-19 01:03:23,540, position=112094357523920}}
 
I 2020-02-19T01:03:24.893153639Z 2020-02-19 01:03:24.892 [Broker-0-DeletionService-3] [Broker-0-zb-actors-3] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.spi.JavaValueMapper@ffd271f)), function-provider: org.camunda.feel.interpreter.FunctionProvider$EmptyFunctionProvider$@7b94b62b]
 
I 2020-02-19T01:03:24.895182940Z 2020-02-19 01:03:24.894 [Broker-0-DeletionService-3] [Broker-0-zb-actors-3] DEBUG io.zeebe.broker.system - The last processed position for snapshot /usr/local/zeebe/data/raft-partition/partitions/3/snapshots/46771469-2-1582072401300-109019157358104 is 109049227545992
 
I 2020-02-19T01:03:24.895691869Z 2020-02-19 01:03:24.895 [Broker-0-DeletionService-3] [Broker-0-zb-actors-3] DEBUG io.zeebe.broker.system - The lowest exported position for snapshot /usr/local/zeebe/data/raft-partition/partitions/3/snapshots/46771469-2-1582072401300-109019157358104 is 109049226466064
 ```

Which is really confusing. 

## Related issues

closes #3877 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: engine/src/main/java/io/zeebe/engine/state/LastProcessedState.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+        zeebeDb.createColumnFamily(
+            ZbColumnFamilies.DEFAULT, dbContext, lastProcessedEventKey, lastProcessedEventPosition);
+  }
+
+  public void markAsProcessed(final long position) {
+    lastProcessedEventPosition.wrapLong(position);
+    lastProcessedRecordPositionColumnFamily.put(lastProcessedEventKey, lastProcessedEventPosition);
+  }
+
+  public long getLastSuccessfulProcessedRecordPosition() {
```
Comment (MiguelPires) [inline engine/src/main/java/io/zeebe/engine/state/LastProcessedState.java]: These method names mirror the methods in ZeebeState but I think here they can be shortened to be less redudant. So instead of `LastProcessedState#getLastSuccessfulProcessedRecordPosition()` something like `LastProcessedState#getPosition`. I think you get the same information from both. What do you think?

**Review by miguelpires — COMMENTED** [review]
Just have one question about naming

File: engine/src/main/java/io/zeebe/engine/state/LastProcessedState.java (hunk 1 above)
Comment (Zelldon) [reply engine/src/main/java/io/zeebe/engine/state/LastProcessedState.java]: I think you are right. I will change it.

**Comment by Zelldon** [comment]
Thanks @MiguelPires I changed the field names and methods

**Review by miguelpires — APPROVED** [review]
Looks good :+1:
