### PR TITLE
Unable to deploy process with boundary event without outgoing flows

### LINKED ISSUE #33589: Unable to deploy process with boundary event without outgoing flows
### 

### 

, , , , , 

### 

### 

### Description

Deploying a process with an attached boundary event fails in Camunda 8.

This is a just fine modeling construct, a BPMN element without outgoing flows is a token sink, consumes the token, in this particular diagram (attached), it completes the process.

We should relax the validation to improve BPMN compliance and interoperability with other BPMN tools (and portability to/from other workflow engines).

Image

Note that the rule probably exists because of our [best-practices](https://docs.camunda.io/docs/components/best-practices/modeling/creating-readable-process-models/#modeling-start-and-end-events):

> **Modeling start and end events**
> Model the trigger and the end status of processes by always explicitly showing the start and end event symbols.

There already exists a linting rule to [discourage users from using implicit end events](https://github.com/bpmn-io/bpmnlint/blob/main/docs/rules/no-implicit-end.md). 

### Steps to reproduce

1. model a process with a boundary event without any outgoing sequence flows
2. deploy it
3. notice the rejection

### Current behavior

Deploying such a process is rejected.

### Expected behavior

It should be possible to deploy and execute such a process correctly. Users should be discouraged by the modeler when not following our best-practices.

### Environment

SaaS & SM

### Version

- Component Version: 8.0+

### Rootcause

There's an explicit validation rule in `BoundaryEventValidator`:

https://github.com/camunda/camunda/blob/2c09f8d9254ecb82eb34a8a217bdb715ff1e029a/zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java#L68-L71

### Solution ideas

- Remove the validation rule
- Expand the test coverage

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

- [Slack discussion](https://camunda.slack.com/archives/C08MRKHJ0CD/p1749122219637289)
- [Linting rule: no implicit end](https://github.com/bpmn-io/bpmnlint/blob/main/docs/rules/no-implicit-end.md)

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

Relax the boundary‐event outgoing‐flow rule so non-compensation events can be sink, while still enforcing “no outgoing + association” for compensation boundaries; update the validator messages and existing BPMN validation tests, and add a concise parameterized runtime test covering interrupting vs. non-interrupting behavior for all boundary event types.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #33589

### CODE REVIEW

**Comment by berkaycanbc** [comment]
@korthout I asked a review from you as you were involved in the conversation. But let me know if you do not have the capacity.

**Comment by korthout** [comment]
@berkaycanbc I don't have capacity for it. This PR might be a good opportunity to share knowledge about the engine in your team.

**Comment by berkaycanbc** [comment]
Hey @georgios-goulos and @tsedekey, did you remember we talked about a PR that you can review in the team meeting? It is this one. Please let me know if you need more context.

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java [hunk 1]
```diff
@@ -100,17 +101,19 @@ public void validate(
         });
   }
 
+  private boolean hasCompensationDefinition(final BoundaryEvent element) {
+    return element.getEventDefinitions().stream()
+        .anyMatch(CompensateEventDefinition.class::isInstance);
```
Comment (georgios-goulos) [inline zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java]: Why are we targeting specifically compensation events here?

Comment (berkaycanbc) [reply zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java]: @georgios-goulos compensation events should not have an outgoing sequence flow and an associated compensation activity by definition. See docs https://docs.camunda.io/docs/components/modeler/bpmn/compensation-handler/

**Comment by berkaycanbc** [comment]
@georgios-goulos thanks for following up on the fix! Still waiting for a full review. I would like to merge this before I get far away from the topic. Thanks already! FYI also @tsedekey

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java (hunk 1 above)
Comment (georgios-goulos) [reply zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java]: So I take it we are focusing on these here specifically because they are the only type of event that should not have an outgoing sequence flow. Thanks for clarifying.

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java [hunk 2]
```diff
@@ -65,9 +65,10 @@ public void validate(
       validationResultCollector.addError(0, "Cannot have incoming sequence flows");
     }
 
-    if (element.getOutgoing().isEmpty() && !isValidCompensationBoundaryEvent(element)) {
+    if (hasCompensationDefinition(element) && !isValidCompensationBoundaryEvent(element)) {
```
Comment (georgios-goulos) [inline zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java]: nitpick: for readability purposes I would change this condition to 
```
if (isInvalidCompensationEvent(element)) 
```

or something similar. Then, `isInvalidCompensationEvent` could contain the logic in these 2 methods, or even call these 2 methods.

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java [hunk 3]
```diff
@@ -100,17 +101,19 @@ public void validate(
...
     // A compensation boundary event should have no outgoing sequence flows. The compensation
     // handler is connected by an association.
     final Optional<Association> association =
         element.getModelInstance().getModelElementsByType(Association.class).stream()
             .filter(a -> a.getSource().getId().equals(element.getId()))
             .findFirst();
-    return element.getOutgoing().isEmpty()
-        && association.isPresent()
-        && element.getEventDefinitions().stream()
-            .anyMatch(CompensateEventDefinition.class::isInstance);
```
Comment (georgios-goulos) [inline zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java:113]: Without this logic here there is no guarantee that the `element` is a compensation boundary, right? I understand that this is a private method, but it could still be used incorrectly.

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java (hunk 2 above)
Comment (berkaycanbc) [reply zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java]: Nice, updated 👍 I've used `isValidCompensationEvent` still because there happen to be too many negation operations inside the method when I try `isInvalidCompensationEvent`.

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java (hunk 3 above)
Comment (berkaycanbc) [reply zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java:113]: We check if the element is compensation via checking the compensation definition existence first.

```
if (noCompensationDefinition) {
      // nothing to validate if there is no compensation definition
      return true;
    }
```

I am not sure if I understand it correctly but let me know if that answers the question.

Comment (georgios-goulos) [reply zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/BoundaryEventValidator.java:113]: Nevermind, I missed that this part was moved further up 👍

**Review by georgios-goulos — APPROVED** [review]

**Comment by nikku** [comment]
Amazing to see this fixed :star:
