### PR TITLE
A call activity can't be completed or terminated

### LINKED ISSUE #6957: ProcessExecutionRandomizedPropertyTest.shouldExecuteProcessToEnd is flaky
**Summary**

- How often does the test fail? twice
- Does it block your work? blocks some PRs
- Do we suspect that it is a real failure? let's assume yes for now

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.camunda.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:72)
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessExecutionRandomizedPropertyTest.shouldExecuteProcessToEnd(ProcessExecutionRandomizedPropertyTest.java:81)
</pre>
</details>

**Logs**

Failing build: https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/337/tests

<details><summary>Logs</summary>
<pre>
07:46:59.491 [Broker-0-LogStream-1] DEBUG io.camunda.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
07:46:59.569 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Recovering state of partition 1 from snapshot
07:46:59.570 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@578a1690)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@594df211, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@5d727de0, configuration: Configuration(false)]
07:46:59.571 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
07:46:59.572 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@1870f82a)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@1fc95322, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@2922e7b0, configuration: Configuration(false)]
07:46:59.573 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@67711209)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@785f0765, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@2dda0b0f, configuration: Configuration(false)]
07:46:59.595 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@144ec9)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@58d4ffae, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@662c8ecb, configuration: Configuration(false)]
07:46:59.619 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@a46da52)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@32e8054f, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@770f266d, configuration: Configuration(false)]
07:46:59.635 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@6397da0f)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@e876e39, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@2e8cb0f6, configuration: Configuration(false)]
07:47:04.791 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
07:47:04.895 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DEPLOYMENT   CREATE         - #001->  -1   -1 - 
E PROC         CREATED        - #002->#001 K001 - process.xml->"process_id_24" (version:1)
E PROC         CREATED        - #003->#001 K002 - process.xml->"process..ld_id_3" (version:1)
E PROC         CREATED        - #004->#001 K003 - process.xml->"process..ld_id_0" (version:1)
E TIMER        CREATED        - #005->#001 K005 -  @"id_26"[  -1]  in <process "K001"[?]> due T08:15:59.644
E DEPLOYMENT   CREATED        - #006->#001 K004 - process.xmlprocess.xmlprocess.xml
E DEPLOYMENT   FULLY_DISTR    - #007->#001 K004 - 
C TIMER        TRIGGER        - #008->#001 K005 -  @"id_26"[  -1]  in <process "K001"[?]> due T08:15:59.644
E TIMER        TRIGGERED      - #009->#008 K005 -  @"id_26"[  -1]  in <process "K001"[?]> due T08:15:59.644
E PROC_EVNT    TRIGGERING     - #010->#008 K007 -  @"id_26"[K001] in <process K001[K006]> (no vars)
C PROC_INST    ACTIVATE       - #011->#008 K006 - PROCESS "process_id_24" in <process "process_id_24"[K006]>
E PROC_INST    ACTIVATING     - #012->#011 K006 - PROCESS "process_id_24" in <process "process_id_24"[K006]>
E PROC_MSG_SUB CREATING       - #013->#011 K008 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATED      - #014->#011 K006 - PROCESS "process_id_24" in <process "process_id_24"[K006]>
E PROC_EVNT    TRIGGERED      - #015->#011 K007 -  @"id_26"[K001] in <process K001[K006]> (no vars)
C PROC_INST    ACTIVATE       - #016->#011 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
C MSG_SUB      CREATE         - #017->  -1   -1 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATING     - #018->#016 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
E PROC_INST    ACTIVATED      - #019->#016 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
C PROC_INST    COMPLETE       - #020->#016 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
E MSG_SUB      CREATED        - #021->#017 K010 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> (no vars)
C PROC_MSG_SUB CREATE         - #022->  -1   -1 - "message_eventSubProcess_id_25" (inter.) @[K006] in <process ?[K006]> (no vars)
E PROC_INST    COMPLETING     - #023->#020 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
E PROC_INST    COMPLETED      - #024->#020 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
E PROC_INST    SEQ_FLOW_TAKEN - #025->#020 K011 - SEQUENCE_FLOW "sequenc..e59f9ad" in <process "process_id_24"[K006]>
C PROC_INST    ACTIVATE       - #026->#020 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E PROC_MSG_SUB CREATED        - #027->#022 K008 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATING     - #028->#026 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E JOB          CREATED        - #029->#026 K013 - K013 "id_26_variables" @"id_26_v..es_task"[K012] 3 retries, in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATED      - #030->#026 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
C JOB_BATCH    ACTIVATE       - #031->  -1   -1 - "id_26_variables" max: 10
E JOB_BATCH    ACTIVATED      - #032->#031 K014 - "id_26_variables" 1/10
                   K013 "id_26_variables" @"id_26_v..es_task"[K012] 3 retries, in <process "process_id_24"[K006]> (no vars)
C JOB          COMPLETE       - #033->  -1 K013 - K013 -1 retries, in <process ?[?]> with variables: {=default_correlation_key, correlationKey=default_correlation_key}
E JOB          COMPLETED      - #034->#033 K013 - K013 "id_26_variables" @"id_26_v..es_task"[K012] 3 retries, in <process "process_id_24"[K006]> with variables: {=default_correlation_key, correlationKey=default_correlation_key}
C PROC_INST    COMPLETE       - #035->#033 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E PROC_INST    COMPLETING     - #036->#035 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E VAR          CREATED        - #037->#035 K015 - correlationKey->"default_correlation_key" in <process [K006]>
E VAR          CREATED        - #038->#035 K016 - ->"default_correlation_key" in <process [K006]>
E PROC_INST    COMPLETED      - #039->#035 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E PROC_INST    SEQ_FLOW_TAKEN - #040->#035 K017 - SEQUENCE_FLOW "sequenc..1d3e91a" in <process "process_id_24"[K006]>
C PROC_INST    ACTIVATE       - #041->#035 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
E PROC_INST    ACTIVATING     - #042->#041 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
E PROC_INST    ACTIVATED      - #043->#041 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
C PROC_INST    ACTIVATE       - #044->#041 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
E VAR          CREATED        - #045->#041 K020 - correlationKey->"default_correlation_key" in <process [K019]>
E VAR          CREATED        - #046->#041 K021 - ->"default_correlation_key" in <process [K019]>
E PROC_INST    ACTIVATING     - #047->#044 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATED      - #048->#044 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #049->#044   -1 - START_EVENT "startEv..e143ef4" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATING     - #050->#049 K022 - START_EVENT "startEv..e143ef4" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATED      - #051->#049 K022 - START_EVENT "startEv..e143ef4" in <process "process..ld_id_0"[K019]>
C PROC_INST    COMPLETE       - #052->#049 K022 - START_EVENT "startEv..e143ef4" in <process "process..ld_id_0"[K019]>
E PROC_INST    COMPLETING     - #053->#052 K022 - START_EVENT "startEv..e143ef4" in <process "process..ld_id_0"[K019]>
E PROC_INST    COMPLETED      - #054->#052 K022 - START_EVENT "startEv..e143ef4" in <process "process..ld_id_0"[K019]>
E PROC_INST    SEQ_FLOW_TAKEN - #055->#052 K023 - SEQUENCE_FLOW "sequenc..6a66e80" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #056->#052 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATING     - #057->#056 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
E PROC_MSG_SUB CREATING       - #058->#056 K025 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> (no vars)
E PROC_INST    ACTIVATED      - #059->#056 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
C MSG_SUB      CREATE         - #060->  -1   -1 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> (no vars)
E MSG_SUB      CREATED        - #061->#060 K026 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> (no vars)
C PROC_MSG_SUB CREATE         - #062->  -1   -1 - "message_id_1" (inter.) @[K024] in <process ?[K019]> (no vars)
E PROC_MSG_SUB CREATED        - #063->#062 K025 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> (no vars)
C MSG          PUBLISH        - #064->  -1   -1 - "message_id_1" correlationKey: default_correlation_key with variables: {correlationKey=default_correlation_key}
E MSG          PUBLISHED      - #065->#064 K027 - "message_id_1" correlationKey: default_correlation_key with variables: {correlationKey=default_correlation_key}
E MSG_SUB      CORRELATING    - #066->#064 K026 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
C PROC_MSG_SUB CORRELATE      - #067->  -1   -1 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_MSG_SUB CORRELATED     - #068->#067 K025 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_EVNT    TRIGGERING     - #069->#067 K028 -  @"id_1"[K024] in <process K003[K019]> with variables: {correlationKey=default_correlation_key}
C PROC_INST    COMPLETE       - #070->#067 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
C MSG_SUB      CORRELATE      - #071->  -1   -1 - "message_id_1" (inter.) @[K024] in <process "process..ld_id_0"[K019]> (no vars)
E PROC_INST    COMPLETING     - #072->#070 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
E VAR          UPDATED        - #073->#070 K020 - correlationKey->"default_correlation_key" in <process [K019]>
E PROC_INST    COMPLETED      - #074->#070 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
E PROC_INST    SEQ_FLOW_TAKEN - #075->#070 K029 - SEQUENCE_FLOW "sequenc..72aaa9f" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #076->#070 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
E MSG_SUB      CORRELATED     - #077->#071 K026 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_INST    ACTIVATING     - #078->#076 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
E PROC_MSG_SUB CREATING       - #079->#076 K031 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> (no vars)
E PROC_INST    ACTIVATED      - #080->#076 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
C MSG_SUB      CREATE         - #081->  -1   -1 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> (no vars)
E MSG_SUB      CREATED        - #082->#081 K032 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> (no vars)
C PROC_MSG_SUB CREATE         - #083->  -1   -1 - "message_id_2" (inter.) @[K030] in <process ?[K019]> (no vars)
E PROC_MSG_SUB CREATED        - #084->#083 K031 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> (no vars)
C MSG          PUBLISH        - #085->  -1   -1 - "message_id_2" correlationKey: default_correlation_key with variables: {correlationKey=default_correlation_key}
E MSG          PUBLISHED      - #086->#085 K033 - "message_id_2" correlationKey: default_correlation_key with variables: {correlationKey=default_correlation_key}
E MSG_SUB      CORRELATING    - #087->#085 K032 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
C PROC_MSG_SUB CORRELATE      - #088->  -1   -1 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_MSG_SUB CORRELATED     - #089->#088 K031 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_EVNT    TRIGGERING     - #090->#088 K034 -  @"id_2"[K030] in <process K003[K019]> with variables: {correlationKey=default_correlation_key}
C PROC_INST    COMPLETE       - #091->#088 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
C MSG_SUB      CORRELATE      - #092->  -1   -1 - "message_id_2" (inter.) @[K030] in <process "process..ld_id_0"[K019]> (no vars)
E PROC_INST    COMPLETING     - #093->#091 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
E VAR          UPDATED        - #094->#091 K020 - correlationKey->"default_correlation_key" in <process [K019]>
E PROC_INST    COMPLETED      - #095->#091 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
E PROC_INST    SEQ_FLOW_TAKEN - #096->#091 K035 - SEQUENCE_FLOW "sequenc..9f993f4" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #097->#091 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
E MSG_SUB      CORRELATED     - #098->#092 K032 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
C MSG          PUBLISH        - #099->  -1   -1 - "message_eventSubProcess_id_25" correlationKey: default_correlation_key with variables: {=default_correlation_key}
E PROC_INST    ACTIVATING     - #100->#097 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATED      - #101->#097 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #102->#097 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E VAR          CREATED        - #103->#097 K038 - correlationKey->"default_correlation_key" in <process [K037]>
E VAR          CREATED        - #104->#097 K039 - ->"default_correlation_key" in <process [K037]>
E MSG          PUBLISHED      - #105->#099 K040 - "message_eventSubProcess_id_25" correlationKey: default_correlation_key with variables: {=default_correlation_key}
E MSG_SUB      CORRELATING    - #106->#099 K010 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> with variables: {=default_correlation_key}
C PROC_MSG_SUB CORRELATE      - #107->  -1   -1 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> with variables: {=default_correlation_key}
E PROC_INST    ACTIVATING     - #108->#102 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E PROC_INST    ACTIVATED      - #109->#102 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
C PROC_INST    ACTIVATE       - #110->#102   -1 - START_EVENT "startEv..54b440d" in <process "process..ld_id_3"[K037]>
E PROC_MSG_SUB CORRELATED     - #111->#107 K008 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> with variables: {=default_correlation_key}
E PROC_EVNT    TRIGGERING     - #112->#107 K041 -  @"start_e..s_id_25"[K006] in <process K001[K006]> with variables: {=default_correlation_key}
C PROC_INST    TERMINATE      - #113->#107 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
C MSG_SUB      CORRELATE      - #114->  -1   -1 - "message_eventSubProcess_id_25" (inter.) @[K006] in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATING     - #115->#110 K042 - START_EVENT "startEv..54b440d" in <process "process..ld_id_3"[K037]>
E PROC_INST    ACTIVATED      - #116->#110 K042 - START_EVENT "startEv..54b440d" in <process "process..ld_id_3"[K037]>
C PROC_INST    COMPLETE       - #117->#110 K042 - START_EVENT "startEv..54b440d" in <process "process..ld_id_3"[K037]>
E PROC_INST    TERMINATING    - #118->#113 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
C PROC_INST    TERMINATE      - #119->#113 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
E MSG_SUB      CORRELATED     - #120->#114 K010 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> with variables: {=default_correlation_key}
E PROC_INST    COMPLETING     - #121->#117 K042 - START_EVENT "startEv..54b440d" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETED      - #122->#117 K042 - START_EVENT "startEv..54b440d" in <process "process..ld_id_3"[K037]>
E PROC_INST    SEQ_FLOW_TAKEN - #123->#117 K043 - SEQUENCE_FLOW "sequenc..2211b78" in <process "process..ld_id_3"[K037]>
C PROC_INST    ACTIVATE       - #124->#117 K044 - END_EVENT "endEven..7e4f723" in <process "process..ld_id_3"[K037]>
E PROC_INST    TERMINATING    - #125->#119 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
C PROC_INST    TERMINATE      - #126->#119 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATING     - #127->#124 K044 - END_EVENT "endEven..7e4f723" in <process "process..ld_id_3"[K037]>
E PROC_INST    ACTIVATED      - #128->#124 K044 - END_EVENT "endEven..7e4f723" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETING     - #129->#124 K044 - END_EVENT "endEven..7e4f723" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETED      - #130->#124 K044 - END_EVENT "endEven..7e4f723" in <process "process..ld_id_3"[K037]>
C PROC_INST    COMPLETE       - #131->#124 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E PROC_INST    TERMINATING    - #132->#126 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
C PROC_INST    TERMINATE      - #133->#126 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETING     - #134->#131 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETED      - #135->#131 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
C PROC_INST    COMPLETE       - #136->#131 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
R PROC_INST    TERMINATE      - #137->#133 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]> !INVALID_STATE (Expected element instance with key '2251799813685285' to be present in state but not found.)
R PROC_INST    COMPLETE       - #138->#136 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]> !INVALID_STATE (Expected element instance to be in state 'ELEMENT_ACTIVATED' or one of '[ELEMENT_COMPLETING]' but was 'ELEMENT_TERMINATING'.)
-------------- Deployed Processes ----------------------
process.xml ------ 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" id="definitions_6698e366-7c59-44c8-ab2b-2b5e983e8541" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process_child_id_0" isExecutable="true">
    <startEvent id="startEvent_301882f3-6378-4c56-a1b5-1f86de143ef4">
      <outgoing>sequenceFlow_47126806-6a8d-4d71-8ead-d75286a66e80</outgoing>
    </startEvent>
    <receiveTask id="id_1" messageRef="message_f52f4202-812f-4b46-a5bf-2f4b18afe675" name="id_1">
      <incoming>sequenceFlow_47126806-6a8d-4d71-8ead-d75286a66e80</incoming>
      <outgoing>sequenceFlow_83e02a44-724a-47a2-b034-d9aa572aaa9f</outgoing>
    </receiveTask>
    <sequenceFlow id="sequenceFlow_47126806-6a8d-4d71-8ead-d75286a66e80" sourceRef="startEvent_301882f3-6378-4c56-a1b5-1f86de143ef4" targetRef="id_1"/>
    <receiveTask id="id_2" messageRef="message_9932a5ab-02a5-465e-af4a-5425b3bfe3c3" name="id_2">
      <incoming>sequenceFlow_83e02a44-724a-47a2-b034-d9aa572aaa9f</incoming>
      <outgoing>sequenceFlow_2eadfbe0-03ca-4f44-9423-342209f993f4</outgoing>
    </receiveTask>
    <sequenceFlow id="sequenceFlow_83e02a44-724a-47a2-b034-d9aa572aaa9f" sourceRef="id_1" targetRef="id_2"/>
    <callActivity id="call_activity_id_3" name="call_activity_id_3">
      <extensionElements>
        <ns0:calledElement processId="process_child_id_3" propagateAllChildVariables="true"/>
      </extensionElements>
      <incoming>sequenceFlow_2eadfbe0-03ca-4f44-9423-342209f993f4</incoming>
      <outgoing>sequenceFlow_4897196b-9853-4acf-851d-4c2cb52a04fb</outgoing>
    </callActivity>
    <sequenceFlow id="sequenceFlow_2eadfbe0-03ca-4f44-9423-342209f993f4" sourceRef="id_2" targetRef="call_activity_id_3"/>
    <endEvent id="endEvent_67376a32-0397-44eb-a020-f9738757e9c9">
      <incoming>sequenceFlow_4897196b-9853-4acf-851d-4c2cb52a04fb</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_4897196b-9853-4acf-851d-4c2cb52a04fb" sourceRef="call_activity_id_3" targetRef="endEvent_67376a32-0397-44eb-a020-f9738757e9c9"/>
  </process>
  <message id="message_f52f4202-812f-4b46-a5bf-2f4b18afe675" name="message_id_1">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <message id="message_9932a5ab-02a5-465e-af4a-5425b3bfe3c3" name="message_id_2">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_c0ecbe08-ca79-45dc-a13e-25ee3eb6778a">
    <bpmndi:BPMNPlane bpmnElement="process_child_id_0" id="BPMNPlane_d3eb766c-ca2d-4d68-a4ec-417412791709">
      <bpmndi:BPMNShape bpmnElement="startEvent_301882f3-6378-4c56-a1b5-1f86de143ef4" id="BPMNShape_e2d4a971-e709-47ba-a643-f39272e6b1fa">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="id_1" id="BPMNShape_f023c553-5d34-4a72-9aad-22c87374721f">
        <dc:Bounds height="80.0" width="100.0" x="186.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_47126806-6a8d-4d71-8ead-d75286a66e80" id="BPMNEdge_563150b0-a6f3-42a9-88d6-a3d889085fa5">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_2" id="BPMNShape_ba80586d-f166-485a-881a-637962d66bbb">
        <dc:Bounds height="80.0" width="100.0" x="336.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_83e02a44-724a-47a2-b034-d9aa572aaa9f" id="BPMNEdge_a48a1b88-be0f-494f-b72f-c8c328aa0774">
        <di:waypoint x="286.0" y="118.0"/>
        <di:waypoint x="336.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="call_activity_id_3" id="BPMNShape_905015a6-0878-4761-bce7-c6a999a180f5">
        <dc:Bounds height="80.0" width="100.0" x="486.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_2eadfbe0-03ca-4f44-9423-342209f993f4" id="BPMNEdge_eb02e09b-10d0-4781-a571-253f6eae57c4">
        <di:waypoint x="436.0" y="118.0"/>
        <di:waypoint x="486.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="endEvent_67376a32-0397-44eb-a020-f9738757e9c9" id="BPMNShape_29d465fa-d029-4f78-b276-d3241c31b479">
        <dc:Bounds height="36.0" width="36.0" x="636.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_4897196b-9853-4acf-851d-4c2cb52a04fb" id="BPMNEdge_8be47854-df2f-45b8-82aa-08309d1c3802">
        <di:waypoint x="586.0" y="118.0"/>
        <di:waypoint x="636.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
--------------- Decomposed keys (for debugging) -----------------
  -1 <-> -1
K001 <-> 2251799813685249
K002 <-> 2251799813685250
K003 <-> 2251799813685251
K004 <-> 2251799813685252
K005 <-> 2251799813685253
K006 <-> 2251799813685254
K007 <-> 2251799813685255
K008 <-> 2251799813685256
K009 <-> 2251799813685257
K010 <-> 2251799813685258
K011 <-> 2251799813685259
K012 <-> 2251799813685260
K013 <-> 2251799813685261
K014 <-> 2251799813685262
K015 <-> 2251799813685263
K016 <-> 2251799813685264
K017 <-> 2251799813685265
K018 <-> 2251799813685266
K019 <-> 2251799813685267
K020 <-> 2251799813685268
K021 <-> 2251799813685269
K022 <-> 2251799813685270
K023 <-> 2251799813685271
K024 <-> 2251799813685272
K025 <-> 2251799813685273
K026 <-> 2251799813685274
K027 <-> 2251799813685275
K028 <-> 2251799813685276
K029 <-> 2251799813685277
K030 <-> 2251799813685278
K031 <-> 2251799813685279
K032 <-> 2251799813685280
K033 <-> 2251799813685281
K034 <-> 2251799813685282
K035 <-> 2251799813685283
K036 <-> 2251799813685284
K037 <-> 2251799813685285
K038 <-> 2251799813685286
K039 <-> 2251799813685287
K040 <-> 2251799813685288
K041 <-> 2251799813685289
K042 <-> 2251799813685290
K043 <-> 2251799813685291
K044 <-> 2251799813685292
07:47:04.900 [] DEBUG io.camunda.zeebe.util.buffer - Close stream processor
07:47:04.901 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
07:47:04.932 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - Close appender for log stream stream-1
07:47:04.932 [stream-1-write-buffer] DEBUG io.camunda.zeebe.dispatcher - Dispatcher closed
07:47:04.932 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-1 close 2 readers
07:47:04.933 [] DEBUG io.camunda.zeebe.broker.test - Clean up test files on path /tmp/junit3778013920858921612
07:47:04.933 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
07:47:04.934 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
07:47:04.935 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
07:47:04.935 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
07:47:04.936 [] INFO  io.camunda.zeebe.engine.processing.streamprocessor.FailedPropertyBasedTestDataPrinter - Data of failed test case: TestDataRecord{processSeed=-3355698362188536227, executionPathSeed=-3156714708834832115}
07:47:04.962 [] INFO  io.camunda.zeebe.engine.processing.streamprocessor.FailedPropertyBasedTestDataPrinter - Test case failed at: ScheduledExecutionStep{step=StepPublishMessage[correlationKeyValue=default_correlation_key,messageName=message_eventSubProcess_id_25,variables={=default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}
07:47:04.964 [] INFO  io.camunda.zeebe.engine.processing.streamprocessor.FailedPropertyBasedTestDataPrinter - Execution path of failed test case:
ScheduledExecutionStep{step=StepTriggerTimerStartEvent[timeToAdd=PT29M,variables={}], activationTime=PT0S, startTime=PT0S, endTime=PT29M, activationDuration=PT29M}
ScheduledExecutionStep{step=StepActivateAndCompleteJob[jobType=id_26_variables,variables={correlationKey=default_correlation_key, =default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}
ScheduledExecutionStep{step=StepPublishMessage[correlationKeyValue=default_correlation_key,messageName=message_id_1,variables={correlationKey=default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}
ScheduledExecutionStep{step=StepPublishMessage[correlationKeyValue=default_correlation_key,messageName=message_id_2,variables={correlationKey=default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}
--failed here--> ScheduledExecutionStep{step=StepPublishMessage[correlationKeyValue=default_correlation_key,messageName=message_eventSubProcess_id_25,variables={=default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}
</pre>
</details>

### LINKED ISSUE #6959: A call activity can't be completed or terminated
**Describe the bug**
The process instance is stuck on terminating a call activity.

If the call activity is interrupted (e.g. by a boundary event, an event subprocess, or a cancel command) and the child process instance transitions to completing then the process instance can get stuck on the call activity. 

The child process instance is in state `completed` and the call activity is in state `terminating`. 

The follow-up command `terminate` of the child process is rejected because the process is completed.
The follow-up command `complete` of the call activity is rejected because the call activity is in state `terminating`.

**To Reproduce**
1. deploy a parent process that contains a call activity with an attached boundary event
2. deploy a child process that is invoked by the call activity
3. create an instance of the parent process
4. await until the child instance is activated
5. transition the child instance to completing and trigger the boundary event concurrently
6. verify that the call activity is not completed or terminated   

<details><summary>Unit Test</summary>
 <p>

```
@Test
  public void test() {
    // given
    ENGINE
        .deployment()
        .withXmlResource(
            "parent-wf.bpmn",
            Bpmn.createExecutableProcess(PROCESS_ID_PARENT)
                .startEvent()
                .callActivity("call", c -> c.zeebeProcessId(PROCESS_ID_CHILD))
                .boundaryEvent("timeout", b -> b.cancelActivity(true).timerWithDuration("PT10S"))
                .endEvent()
                .moveToActivity("call")
                .endEvent()
                .done())
        .withXmlResource(
            "child-wf.bpmn",
            Bpmn.createExecutableProcess(PROCESS_ID_CHILD)
                .startEvent()
                .serviceTask("task", t -> t.zeebeJobType("test"))
                .done())
        .deploy();

    // when
    final var processInstanceKey =
        ENGINE.processInstance().ofBpmnProcessId(PROCESS_ID_PARENT).create();

    final var timerCreated =
        RecordingExporter.timerRecords(TimerIntent.CREATED)
            .withProcessInstanceKey(processInstanceKey)
            .getFirst();

    final var jobCreated =
        RecordingExporter.jobRecords(JobIntent.CREATED).withElementId("task").getFirst();

    ENGINE.writeRecords(
        RecordToWrite.command()
            .job(JobIntent.COMPLETE, jobCreated.getValue())
            .key(jobCreated.getKey()),
        RecordToWrite.command()
            .timer(TimerIntent.TRIGGER, timerCreated.getValue())
            .key(timerCreated.getKey()));

    // then
    assertThat(
            RecordingExporter.records()
                .limitToProcessInstance(processInstanceKey)
                .processInstanceRecords())
        .extracting(r -> tuple(r.getValue().getBpmnElementType(), r.getIntent()))
        .containsSubsequence(
            tuple(BpmnElementType.CALL_ACTIVITY, ProcessInstanceIntent.TERMINATE_ELEMENT),
            tuple(BpmnElementType.CALL_ACTIVITY, ProcessInstanceIntent.ELEMENT_TERMINATING),
            tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.TERMINATE_ELEMENT),
            tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.ELEMENT_COMPLETED),
            tuple(BpmnElementType.CALL_ACTIVITY, ProcessInstanceIntent.ELEMENT_TERMINATED),
            tuple(BpmnElementType.BOUNDARY_EVENT, ProcessInstanceIntent.ELEMENT_ACTIVATED),
            tuple(BpmnElementType.SEQUENCE_FLOW, ProcessInstanceIntent.SEQUENCE_FLOW_TAKEN),
            tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.ELEMENT_COMPLETED));
  }
```

</p>
</details>

**Expected behavior**
The call activity is terminated and the boundary is activated.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
/usr/lib/jvm/java-11-openjdk-amd64/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:/home/philipp/Downloads/idea-IU-192.5728.98/lib/idea_rt.jar=37641:/home/philipp/Downloads/idea-IU-192.5728.98/bin -Dfile.encoding=UTF-8 -classpath /home/philipp/Downloads/idea-IU-192.5728.98/lib/idea_rt.jar:/home/philipp/Downloads/idea-IU-192.5728.98/plugins/junit/lib/junit5-rt.jar:/home/philipp/Downloads/idea-IU-192.5728.98/plugins/junit/lib/junit-rt.jar:/home/philipp/IdeaProjects/zeebe/engine/target/test-classes:/home/philipp/IdeaProjects/zeebe/engine/target/classes:/home/philipp/IdeaProjects/zeebe/util/target/classes:/home/philipp/.m2/repository/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar:/home/philipp/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar:/home/philipp/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar:/home/philipp/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.3/jackson-datatype-jsr310-2.12.3.jar:/home/philipp/.m2/repository/org/springframework/spring-core/5.3.6/spring-core-5.3.6.jar:/home/philipp/.m2/repository/org/springframework/spring-jcl/5.3.6/spring-jcl-5.3.6.jar:/home/philipp/.m2/repository/org/springframework/spring-context/5.3.6/spring-context-5.3.6.jar:/home/philipp/.m2/repository/org/springframework/spring-aop/5.3.6/spring-aop-5.3.6.jar:/home/philipp/.m2/repository/org/springframework/spring-expression/5.3.6/spring-expression-5.3.6.jar:/home/philipp/.m2/repository/org/springframework/boot/spring-boot/2.4.5/spring-boot-2.4.5.jar:/home/philipp/.m2/repository/org/springframework/boot/spring-boot-actuator/2.4.5/spring-boot-actuator-2.4.5.jar:/home/philipp/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.4.5/spring-boot-autoconfigure-2.4.5.jar:/home/philipp/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.4.5/spring-boot-actuator-autoconfigure-2.4.5.jar:/home/philipp/.m2/repository/org/agrona/agrona/1.10.0/agrona-1.10.0.jar:/home/philipp/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/home/philipp/IdeaProjects/zeebe/protocol/target/classes:/home/philipp/IdeaProjects/zeebe/zb-db/target/classes:/home/philipp/.m2/repository/org/rocksdb/rocksdbjni/6.19.3/rocksdbjni-6.19.3.jar:/home/philipp/IdeaProjects/zeebe/protocol-impl/target/classes:/home/philipp/.m2/repository/org/msgpack/jackson-dataformat-msgpack/0.8.22/jackson-dataformat-msgpack-0.8.22.jar:/home/philipp/IdeaProjects/zeebe/logstreams/target/classes:/home/philipp/IdeaProjects/zeebe/dispatcher/target/classes:/home/philipp/.m2/repository/com/netflix/concurrency-limits/concurrency-limits-core/0.3.6/concurrency-limits-core-0.3.6.jar:/home/philipp/IdeaProjects/zeebe/atomix/cluster/target/classes:/home/philipp/IdeaProjects/zeebe/atomix/utils/target/classes:/home/philipp/.m2/repository/com/esotericsoftware/minlog/1.3.1/minlog-1.3.1.jar:/home/philipp/IdeaProjects/zeebe/snapshot/target/classes:/home/philipp/IdeaProjects/zeebe/journal/target/classes:/home/philipp/.m2/repository/io/netty/netty-transport/4.1.63.Final/netty-transport-4.1.63.Final.jar:/home/philipp/.m2/repository/io/netty/netty-resolver/4.1.63.Final/netty-resolver-4.1.63.Final.jar:/home/philipp/.m2/repository/io/netty/netty-codec/4.1.63.Final/netty-codec-4.1.63.Final.jar:/home/philipp/.m2/repository/io/netty/netty-common/4.1.63.Final/netty-common-4.1.63.Final.jar:/home/philipp/.m2/repository/io/netty/netty-transport-native-epoll/4.1.63.Final/netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:/home/philipp/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.63.Final/netty-transport-native-unix-common-4.1.63.Final.jar:/home/philipp/.m2/repository/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar:/home/philipp/.m2/repository/com/esotericsoftware/kryo/5.1.1/kryo-5.1.1.jar:/home/philipp/.m2/repository/com/esotericsoftware/reflectasm/1.11.9/reflectasm-1.11.9.jar:/home/philipp/.m2/repository/io/netty/netty-buffer/4.1.63.Final/netty-buffer-4.1.63.Final.jar:/home/philipp/.m2/repository/com/google/guava/guava/30.1.1-jre/guava-30.1.1-jre.jar:/home/philipp/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/philipp/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/philipp/.m2/repository/org/checkerframework/checker-qual/3.8.0/checker-qual-3.8.0.jar:/home/philipp/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/home/philipp/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar:/home/philipp/IdeaProjects/zeebe/msgpack-core/target/classes:/home/philipp/IdeaProjects/zeebe/expression-language/target/classes:/home/philipp/.m2/repository/org/camunda/feel/feel-engine/1.13.2/feel-engine-1.13.2.jar:/home/philipp/.m2/repository/com/lihaoyi/fastparse_2.13/2.3.1/fastparse_2.13-2.3.1.jar:/home/philipp/.m2/repository/com/lihaoyi/sourcecode_2.13/0.2.3/sourcecode_2.13-0.2.3.jar:/home/philipp/.m2/repository/com/lihaoyi/geny_2.13/0.6.5/geny_2.13-0.6.5.jar:/home/philipp/.m2/repository/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar:/home/philipp/IdeaProjects/zeebe/msgpack-value/target/classes:/home/philipp/IdeaProjects/zeebe/bpmn-model/target/classes:/home/philipp/.m2/repository/org/camunda/bpm/model/camunda-xml-model/7.15.0/camunda-xml-model-7.15.0.jar:/home/philipp/.m2/repository/uk/co/real-logic/sbe-tool/1.22.0/sbe-tool-1.22.0.jar:/home/philipp/.m2/repository/io/prometheus/simpleclient/0.10.0/simpleclient-0.10.0.jar:/home/philipp/IdeaProjects/zeebe/protocol-asserts/target/classes:/home/philipp/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar:/home/philipp/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/philipp/.m2/repository/org/hamcrest/hamcrest-core/2.2/hamcrest-core-2.2.jar:/home/philipp/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.7.1/junit-jupiter-params-5.7.1.jar:/home/philipp/.m2/repository/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar:/home/philipp/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.7.1/junit-jupiter-api-5.7.1.jar:/home/philipp/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/home/philipp/.m2/repository/org/junit/platform/junit-platform-commons/1.7.1/junit-platform-commons-1.7.1.jar:/home/philipp/.m2/repository/org/assertj/assertj-core/3.19.0/assertj-core-3.19.0.jar:/home/philipp/.m2/repository/org/msgpack/msgpack-core/0.8.22/msgpack-core-0.8.22.jar:/home/philipp/IdeaProjects/zeebe/test-util/target/classes:/home/philipp/IdeaProjects/zeebe/exporter-api/target/classes:/home/philipp/IdeaProjects/zeebe/clients/java/target/classes:/home/philipp/IdeaProjects/zeebe/gateway-protocol-impl/target/classes:/home/philipp/IdeaProjects/zeebe/gateway-protocol/target/classes:/home/philipp/.m2/repository/io/grpc/grpc-protobuf/1.37.0/grpc-protobuf-1.37.0.jar:/home/philipp/.m2/repository/com/google/api/grpc/proto-google-common-protos/2.1.0/proto-google-common-protos-2.1.0.jar:/home/philipp/.m2/repository/io/grpc/grpc-protobuf-lite/1.37.0/grpc-protobuf-lite-1.37.0.jar:/home/philipp/.m2/repository/io/grpc/grpc-stub/1.37.0/grpc-stub-1.37.0.jar:/home/philipp/.m2/repository/io/grpc/grpc-core/1.37.0/grpc-core-1.37.0.jar:/home/philipp/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar:/home/philipp/.m2/repository/com/google/android/annotations/4.1.1.4/annotations-4.1.1.4.jar:/home/philipp/.m2/repository/io/perfmark/perfmark-api/0.23.0/perfmark-api-0.23.0.jar:/home/philipp/.m2/repository/io/grpc/grpc-netty/1.37.0/grpc-netty-1.37.0.jar:/home/philipp/.m2/repository/io/netty/netty-codec-http2/4.1.63.Final/netty-codec-http2-4.1.63.Final.jar:/home/philipp/.m2/repository/io/netty/netty-codec-http/4.1.63.Final/netty-codec-http-4.1.63.Final.jar:/home/philipp/.m2/repository/io/netty/netty-handler-proxy/4.1.63.Final/netty-handler-proxy-4.1.63.Final.jar:/home/philipp/.m2/repository/io/netty/netty-codec-socks/4.1.63.Final/netty-codec-socks-4.1.63.Final.jar:/home/philipp/.m2/repository/com/google/protobuf/protobuf-java/3.15.8/protobuf-java-3.15.8.jar:/home/philipp/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.39.Final/netty-tcnative-boringssl-static-2.0.39.Final.jar:/home/philipp/.m2/repository/io/netty/netty-handler/4.1.63.Final/netty-handler-4.1.63.Final.jar:/home/philipp/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.3/jackson-dataformat-yaml-2.12.3.jar:/home/philipp/.m2/repository/org/testcontainers/testcontainers/1.15.3/testcontainers-1.15.3.jar:/home/philipp/.m2/repository/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar:/home/philipp/.m2/repository/org/rnorth/duct-tape/duct-tape/1.0.8/duct-tape-1.0.8.jar:/home/philipp/.m2/repository/org/rnorth/visible-assertions/visible-assertions/2.1.2/visible-assertions-2.1.2.jar:/home/philipp/.m2/repository/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar:/home/philipp/.m2/repository/com/github/docker-java/docker-java-api/3.2.8/docker-java-api-3.2.8.jar:/home/philipp/.m2/repository/com/github/docker-java/docker-java-transport-zerodep/3.2.8/docker-java-transport-zerodep-3.2.8.jar:/home/philipp/.m2/repository/com/github/docker-java/docker-java-transport/3.2.8/docker-java-transport-3.2.8.jar:/home/philipp/.m2/repository/org/springframework/spring-beans/5.3.6/spring-beans-5.3.6.jar:/home/philipp/.m2/repository/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar:/home/philipp/.m2/repository/io/grpc/grpc-api/1.37.0/grpc-api-1.37.0.jar:/home/philipp/.m2/repository/io/grpc/grpc-context/1.37.0/grpc-context-1.37.0.jar:/home/philipp/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/philipp/.m2/repository/com/google/errorprone/error_prone_annotations/2.6.0/error_prone_annotations-2.6.0.jar:/home/philipp/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.20/animal-sniffer-annotations-1.20.jar:/home/philipp/.m2/repository/org/mockito/mockito-core/3.9.0/mockito-core-3.9.0.jar:/home/philipp/.m2/repository/net/bytebuddy/byte-buddy/1.10.20/byte-buddy-1.10.20.jar:/home/philipp/.m2/repository/net/bytebuddy/byte-buddy-agent/1.10.20/byte-buddy-agent-1.10.20.jar:/home/philipp/.m2/repository/org/objenesis/objenesis/3.2/objenesis-3.2.jar:/home/philipp/.m2/repository/org/awaitility/awaitility/4.0.3/awaitility-4.0.3.jar:/home/philipp/.m2/repository/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar:/home/philipp/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/home/philipp/IdeaProjects/zeebe/logstreams/target/test-classes:/home/philipp/IdeaProjects/zeebe/build-tools/target/classes:/home/philipp/.m2/repository/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar:/home/philipp/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.14.1/log4j-slf4j-impl-2.14.1.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 io.camunda.zeebe.engine.processing.streamprocessor.ProcessExecutionRandomizedPropertyTest Until Failure
Process finished with exit code 255
13:30:12.979 [Broker-0-LogStream-1] DEBUG io.camunda.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
13:30:13.169 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Recovering state of partition 1 from snapshot
13:30:13.277 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@613df8bf)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@4d3d430, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@342d1d4e, configuration: Configuration(false)]
13:30:13.366 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
13:30:13.377 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@6c3bbec5)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@47ece204, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@58ef84a8, configuration: Configuration(false)]
13:30:13.384 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@5ea1590)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@14222312, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@38c9e850, configuration: Configuration(false)]
13:30:13.659 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@6877cc99)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@133d317d, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@2a7af501, configuration: Configuration(false)]
13:30:13.712 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@4c0aee8a)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@26f84ffc, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@2ee4f907, configuration: Configuration(false)]
13:30:13.739 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@31828eb8)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@6f203c0, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@3d5de794, configuration: Configuration(false)]
13:30:19.062 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
13:30:19.138 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DEPLOYMENT   CREATE         - #001->  -1   -1 - 
E PROC         CREATED        - #002->#001 K001 - process.xml->"process_id_24" (version:1)
E PROC         CREATED        - #003->#001 K002 - process.xml->"process..ld_id_3" (version:1)
E PROC         CREATED        - #004->#001 K003 - process.xml->"process..ld_id_0" (version:1)
E TIMER        CREATED        - #005->#001 K005 -  @"id_26"[  -1]  in <process "K001"[?]> due T13:59:13.754
E DEPLOYMENT   CREATED        - #006->#001 K004 - process.xml, process.xml, process.xml
E DEPLOYMENT   FULLY_DISTR    - #007->#001 K004 - 
C TIMER        TRIGGER        - #008->#001 K005 -  @"id_26"[  -1]  in <process "K001"[?]> due T13:59:13.754
E TIMER        TRIGGERED      - #009->#008 K005 -  @"id_26"[  -1]  in <process "K001"[?]> due T13:59:13.754
E PROC_EVNT    TRIGGERING     - #010->#008 K007 -  @"id_26"[K001] in <process K001[K006]> (no vars)
C PROC_INST    ACTIVATE       - #011->#008 K006 - PROCESS "process_id_24" in <process "process_id_24"[K006]>
E PROC_INST    ACTIVATING     - #012->#011 K006 - PROCESS "process_id_24" in <process "process_id_24"[K006]>
E PROC_MSG_SUB CREATING       - #013->#011 K008 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATED      - #014->#011 K006 - PROCESS "process_id_24" in <process "process_id_24"[K006]>
E PROC_EVNT    TRIGGERED      - #015->#011 K007 -  @"id_26"[K001] in <process K001[K006]> (no vars)
C PROC_INST    ACTIVATE       - #016->#011 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
C MSG_SUB      CREATE         - #017->  -1   -1 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATING     - #018->#016 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
E PROC_INST    ACTIVATED      - #019->#016 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
C PROC_INST    COMPLETE       - #020->#016 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
E MSG_SUB      CREATED        - #021->#017 K010 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> (no vars)
C PROC_MSG_SUB CREATE         - #022->  -1   -1 - "message_eventSubProcess_id_25" (inter.) @[K006] in <process ?[K006]> (no vars)
E PROC_INST    COMPLETING     - #023->#020 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
E PROC_INST    COMPLETED      - #024->#020 K009 - START_EVENT "id_26" in <process "process_id_24"[K006]>
E PROC_INST    SEQ_FLOW_TAKEN - #025->#020 K011 - SEQUENCE_FLOW "sequenc..acdb5a5" in <process "process_id_24"[K006]>
C PROC_INST    ACTIVATE       - #026->#020 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E PROC_MSG_SUB CREATED        - #027->#022 K008 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATING     - #028->#026 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E JOB          CREATED        - #029->#026 K013 - K013 "id_26_variables" @"id_26_v..es_task"[K012] 3 retries, in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATED      - #030->#026 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
C JOB_BATCH    ACTIVATE       - #031->  -1   -1 - "id_26_variables" max: 10
E JOB_BATCH    ACTIVATED      - #032->#031 K014 - "id_26_variables" 1/10
                   K013 "id_26_variables" @"id_26_v..es_task"[K012] 3 retries, in <process "process_id_24"[K006]> (no vars)
C JOB          COMPLETE       - #033->  -1 K013 - K013 -1 retries, in <process ?[?]> with variables: {=default_correlation_key, correlationKey=default_correlation_key}
E JOB          COMPLETED      - #034->#033 K013 - K013 "id_26_variables" @"id_26_v..es_task"[K012] 3 retries, in <process "process_id_24"[K006]> with variables: {=default_correlation_key, correlationKey=default_correlation_key}
C PROC_INST    COMPLETE       - #035->#033 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E PROC_INST    COMPLETING     - #036->#035 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E VAR          CREATED        - #037->#035 K015 - correlationKey->"default_correlation_key" in <process [K006]>
E VAR          CREATED        - #038->#035 K016 - ->"default_correlation_key" in <process [K006]>
E PROC_INST    COMPLETED      - #039->#035 K012 - SERVICE_TASK "id_26_v..es_task" in <process "process_id_24"[K006]>
E PROC_INST    SEQ_FLOW_TAKEN - #040->#035 K017 - SEQUENCE_FLOW "sequenc..15e1f7e" in <process "process_id_24"[K006]>
C PROC_INST    ACTIVATE       - #041->#035 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
E PROC_INST    ACTIVATING     - #042->#041 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
E PROC_INST    ACTIVATED      - #043->#041 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
C PROC_INST    ACTIVATE       - #044->#041 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
E VAR          CREATED        - #045->#041 K020 - correlationKey->"default_correlation_key" in <process [K019]>
E VAR          CREATED        - #046->#041 K021 - ->"default_correlation_key" in <process [K019]>
E PROC_INST    ACTIVATING     - #047->#044 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATED      - #048->#044 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #049->#044   -1 - START_EVENT "startEv..fa66314" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATING     - #050->#049 K022 - START_EVENT "startEv..fa66314" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATED      - #051->#049 K022 - START_EVENT "startEv..fa66314" in <process "process..ld_id_0"[K019]>
C PROC_INST    COMPLETE       - #052->#049 K022 - START_EVENT "startEv..fa66314" in <process "process..ld_id_0"[K019]>
E PROC_INST    COMPLETING     - #053->#052 K022 - START_EVENT "startEv..fa66314" in <process "process..ld_id_0"[K019]>
E PROC_INST    COMPLETED      - #054->#052 K022 - START_EVENT "startEv..fa66314" in <process "process..ld_id_0"[K019]>
E PROC_INST    SEQ_FLOW_TAKEN - #055->#052 K023 - SEQUENCE_FLOW "sequenc..c0609e9" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #056->#052 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATING     - #057->#056 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
E PROC_MSG_SUB CREATING       - #058->#056 K025 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> (no vars)
E PROC_INST    ACTIVATED      - #059->#056 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
C MSG_SUB      CREATE         - #060->  -1   -1 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> (no vars)
E MSG_SUB      CREATED        - #061->#060 K026 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> (no vars)
C PROC_MSG_SUB CREATE         - #062->  -1   -1 - "message_id_1" (inter.) @[K024] in <process ?[K019]> (no vars)
E PROC_MSG_SUB CREATED        - #063->#062 K025 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> (no vars)
C MSG          PUBLISH        - #064->  -1   -1 - "message_id_1" correlationKey: default_correlation_key with variables: {correlationKey=default_correlation_key}
E MSG          PUBLISHED      - #065->#064 K027 - "message_id_1" correlationKey: default_correlation_key with variables: {correlationKey=default_correlation_key}
E MSG_SUB      CORRELATING    - #066->#064 K026 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
C PROC_MSG_SUB CORRELATE      - #067->  -1   -1 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_MSG_SUB CORRELATED     - #068->#067 K025 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_EVNT    TRIGGERING     - #069->#067 K028 -  @"id_1"[K024] in <process K003[K019]> with variables: {correlationKey=default_correlation_key}
C PROC_INST    COMPLETE       - #070->#067 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
C MSG_SUB      CORRELATE      - #071->  -1   -1 - "message_id_1" (inter.) @[K024] in <process "process..ld_id_0"[K019]> (no vars)
E PROC_INST    COMPLETING     - #072->#070 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
E VAR          UPDATED        - #073->#070 K020 - correlationKey->"default_correlation_key" in <process [K019]>
E PROC_INST    COMPLETED      - #074->#070 K024 - RECEIVE_TASK "id_1" in <process "process..ld_id_0"[K019]>
E PROC_INST    SEQ_FLOW_TAKEN - #075->#070 K029 - SEQUENCE_FLOW "sequenc..74f724a" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #076->#070 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
E MSG_SUB      CORRELATED     - #077->#071 K026 - "message_id_1" (inter.) correlationKey: default_correlation_key @[K024] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_INST    ACTIVATING     - #078->#076 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
E PROC_MSG_SUB CREATING       - #079->#076 K031 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> (no vars)
E PROC_INST    ACTIVATED      - #080->#076 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
C MSG_SUB      CREATE         - #081->  -1   -1 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> (no vars)
E MSG_SUB      CREATED        - #082->#081 K032 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> (no vars)
C PROC_MSG_SUB CREATE         - #083->  -1   -1 - "message_id_2" (inter.) @[K030] in <process ?[K019]> (no vars)
E PROC_MSG_SUB CREATED        - #084->#083 K031 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> (no vars)
C MSG          PUBLISH        - #085->  -1   -1 - "message_id_2" correlationKey: default_correlation_key with variables: {correlationKey=default_correlation_key}
E MSG          PUBLISHED      - #086->#085 K033 - "message_id_2" correlationKey: default_correlation_key with variables: {correlationKey=default_correlation_key}
E MSG_SUB      CORRELATING    - #087->#085 K032 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
C PROC_MSG_SUB CORRELATE      - #088->  -1   -1 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_MSG_SUB CORRELATED     - #089->#088 K031 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
E PROC_EVNT    TRIGGERING     - #090->#088 K034 -  @"id_2"[K030] in <process K003[K019]> with variables: {correlationKey=default_correlation_key}
C PROC_INST    COMPLETE       - #091->#088 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
C MSG_SUB      CORRELATE      - #092->  -1   -1 - "message_id_2" (inter.) @[K030] in <process "process..ld_id_0"[K019]> (no vars)
E PROC_INST    COMPLETING     - #093->#091 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
E VAR          UPDATED        - #094->#091 K020 - correlationKey->"default_correlation_key" in <process [K019]>
E PROC_INST    COMPLETED      - #095->#091 K030 - RECEIVE_TASK "id_2" in <process "process..ld_id_0"[K019]>
E PROC_INST    SEQ_FLOW_TAKEN - #096->#091 K035 - SEQUENCE_FLOW "sequenc..39c7590" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #097->#091 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
E MSG_SUB      CORRELATED     - #098->#092 K032 - "message_id_2" (inter.) correlationKey: default_correlation_key @[K030] in <process "process..ld_id_0"[K019]> with variables: {correlationKey=default_correlation_key}
C MSG          PUBLISH        - #099->  -1   -1 - "message_eventSubProcess_id_25" correlationKey: default_correlation_key with variables: {=default_correlation_key}
E PROC_INST    ACTIVATING     - #100->#097 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATED      - #101->#097 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
C PROC_INST    ACTIVATE       - #102->#097 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E VAR          CREATED        - #103->#097 K038 - correlationKey->"default_correlation_key" in <process [K037]>
E VAR          CREATED        - #104->#097 K039 - ->"default_correlation_key" in <process [K037]>
E MSG          PUBLISHED      - #105->#099 K040 - "message_eventSubProcess_id_25" correlationKey: default_correlation_key with variables: {=default_correlation_key}
E MSG_SUB      CORRELATING    - #106->#099 K010 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> with variables: {=default_correlation_key}
C PROC_MSG_SUB CORRELATE      - #107->  -1   -1 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> with variables: {=default_correlation_key}
E PROC_INST    ACTIVATING     - #108->#102 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E PROC_INST    ACTIVATED      - #109->#102 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
C PROC_INST    ACTIVATE       - #110->#102   -1 - START_EVENT "startEv..d6be67d" in <process "process..ld_id_3"[K037]>
E PROC_MSG_SUB CORRELATED     - #111->#107 K008 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> with variables: {=default_correlation_key}
E PROC_EVNT    TRIGGERING     - #112->#107 K041 -  @"start_e..s_id_25"[K006] in <process K001[K006]> with variables: {=default_correlation_key}
C PROC_INST    TERMINATE      - #113->#107 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
C MSG_SUB      CORRELATE      - #114->  -1   -1 - "message_eventSubProcess_id_25" (inter.) @[K006] in <process "process_id_24"[K006]> (no vars)
E PROC_INST    ACTIVATING     - #115->#110 K042 - START_EVENT "startEv..d6be67d" in <process "process..ld_id_3"[K037]>
E PROC_INST    ACTIVATED      - #116->#110 K042 - START_EVENT "startEv..d6be67d" in <process "process..ld_id_3"[K037]>
C PROC_INST    COMPLETE       - #117->#110 K042 - START_EVENT "startEv..d6be67d" in <process "process..ld_id_3"[K037]>
E PROC_INST    TERMINATING    - #118->#113 K018 - CALL_ACTIVITY "call_ac..ty_id_0" in <process "process_id_24"[K006]>
C PROC_INST    TERMINATE      - #119->#113 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
E MSG_SUB      CORRELATED     - #120->#114 K010 - "message_eventSubProcess_id_25" (inter.) correlationKey: default_correlation_key @[K006] in <process "process_id_24"[K006]> with variables: {=default_correlation_key}
E PROC_INST    COMPLETING     - #121->#117 K042 - START_EVENT "startEv..d6be67d" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETED      - #122->#117 K042 - START_EVENT "startEv..d6be67d" in <process "process..ld_id_3"[K037]>
E PROC_INST    SEQ_FLOW_TAKEN - #123->#117 K043 - SEQUENCE_FLOW "sequenc..47bee35" in <process "process..ld_id_3"[K037]>
C PROC_INST    ACTIVATE       - #124->#117 K044 - END_EVENT "endEven..71638a8" in <process "process..ld_id_3"[K037]>
E PROC_INST    TERMINATING    - #125->#119 K019 - PROCESS "process..ld_id_0" in <process "process..ld_id_0"[K019]>
C PROC_INST    TERMINATE      - #126->#119 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
E PROC_INST    ACTIVATING     - #127->#124 K044 - END_EVENT "endEven..71638a8" in <process "process..ld_id_3"[K037]>
E PROC_INST    ACTIVATED      - #128->#124 K044 - END_EVENT "endEven..71638a8" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETING     - #129->#124 K044 - END_EVENT "endEven..71638a8" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETED      - #130->#124 K044 - END_EVENT "endEven..71638a8" in <process "process..ld_id_3"[K037]>
C PROC_INST    COMPLETE       - #131->#124 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E PROC_INST    TERMINATING    - #132->#126 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
C PROC_INST    TERMINATE      - #133->#126 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETING     - #134->#131 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
E PROC_INST    COMPLETED      - #135->#131 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]>
C PROC_INST    COMPLETE       - #136->#131 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]>
R PROC_INST    TERMINATE      - #137->#133 K037 - PROCESS "process..ld_id_3" in <process "process..ld_id_3"[K037]> !INVALID_STATE (Expected element instance with key '2251799813685285' to be present in state but not found.)
R PROC_INST    COMPLETE       - #138->#136 K036 - CALL_ACTIVITY "call_ac..ty_id_3" in <process "process..ld_id_0"[K019]> !INVALID_STATE (Expected element instance to be in state 'ELEMENT_ACTIVATED' or one of '[ELEMENT_COMPLETING]' but was 'ELEMENT_TERMINATING'.)
-------------- Deployed Processes ----------------------
process.xml "process_id_24"[K001] (version:1) ------ 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" id="definitions_29fb99bc-e147-4026-9c11-b7fb703bfa34" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process_id_24" isExecutable="true">
    <subProcess id="eventSubProcess_id_25" name="eventSubProcess_id_25" triggeredByEvent="true">
      <startEvent id="start_event_eventSubProcess_id_25" isInterrupting="true" name="start_event_eventSubProcess_id_25">
        <outgoing>sequenceFlow_2ddf0ba9-5aaf-4ae5-893d-bf9a05b04a7e</outgoing>
        <messageEventDefinition id="messageEventDefinition_2d62fcfc-bc14-4fbf-b7c5-d16619dc8c58" messageRef="message_14ad0df6-884f-4a86-9ef4-f9f9f64d404f"/>
      </startEvent>
      <endEvent id="end_event_eventSubProcess_id_25" name="end_event_eventSubProcess_id_25">
        <incoming>sequenceFlow_2ddf0ba9-5aaf-4ae5-893d-bf9a05b04a7e</incoming>
      </endEvent>
      <sequenceFlow id="sequenceFlow_2ddf0ba9-5aaf-4ae5-893d-bf9a05b04a7e" sourceRef="start_event_eventSubProcess_id_25" targetRef="end_event_eventSubProcess_id_25"/>
    </subProcess>
    <startEvent id="id_26" name="id_26">
      <outgoing>sequenceFlow_3048f908-4fb1-4fd0-9bd3-2c3bbacdb5a5</outgoing>
      <timerEventDefinition id="timerEventDefinition_d355229b-545d-40ab-8095-f1e1661c781e">
        <timeDate id="timeDate_cd7c714f-a202-4b37-b877-933a1c59f3d4">=now() + duration("PT29M")</timeDate>
      </timerEventDefinition>
    </startEvent>
    <serviceTask id="id_26_variables_task" name="id_26_variables_task">
      <extensionElements>
        <ns0:taskDefinition type="id_26_variables"/>
      </extensionElements>
      <incoming>sequenceFlow_3048f908-4fb1-4fd0-9bd3-2c3bbacdb5a5</incoming>
      <outgoing>sequenceFlow_f9537a6c-e23f-4678-9c7e-a82cd15e1f7e</outgoing>
    </serviceTask>
    <sequenceFlow id="sequenceFlow_3048f908-4fb1-4fd0-9bd3-2c3bbacdb5a5" sourceRef="id_26" targetRef="id_26_variables_task"/>
    <callActivity id="call_activity_id_0" name="call_activity_id_0">
      <extensionElements>
        <ns0:calledElement processId="process_child_id_0" propagateAllChildVariables="false"/>
      </extensionElements>
      <incoming>sequenceFlow_f9537a6c-e23f-4678-9c7e-a82cd15e1f7e</incoming>
      <outgoing>sequenceFlow_f230cd76-68d2-4b5f-b00e-ce52c12b4bd8</outgoing>
    </callActivity>
    <sequenceFlow id="sequenceFlow_f9537a6c-e23f-4678-9c7e-a82cd15e1f7e" sourceRef="id_26_variables_task" targetRef="call_activity_id_0"/>
    <eventBasedGateway id="fork_id_4" name="fork_id_4">
      <incoming>sequenceFlow_f230cd76-68d2-4b5f-b00e-ce52c12b4bd8</incoming>
      <outgoing>sequenceFlow_4d7d042b-b017-49e7-8a2e-d57d32e98716</outgoing>
      <outgoing>sequenceFlow_8ea7d338-8b95-4a25-8cdf-213822b80098</outgoing>
    </eventBasedGateway>
    <sequenceFlow id="sequenceFlow_f230cd76-68d2-4b5f-b00e-ce52c12b4bd8" sourceRef="call_activity_id_0" targetRef="fork_id_4"/>
    <intermediateCatchEvent id="id_6" name="id_6">
      <incoming>sequenceFlow_4d7d042b-b017-49e7-8a2e-d57d32e98716</incoming>
      <outgoing>sequenceFlow_fdaa89f0-f5bc-4cb6-996a-3e8fccf1ec10</outgoing>
      <messageEventDefinition id="messageEventDefinition_aa285c63-9047-4a19-91b2-bef160d00b0f" messageRef="message_aa30e0fe-efc0-4365-bc42-0510a4e4484a"/>
    </intermediateCatchEvent>
    <sequenceFlow id="sequenceFlow_4d7d042b-b017-49e7-8a2e-d57d32e98716" sourceRef="fork_id_4" targetRef="id_6"/>
    <parallelGateway id="fork_id_7" name="fork_id_7">
      <incoming>sequenceFlow_fdaa89f0-f5bc-4cb6-996a-3e8fccf1ec10</incoming>
      <outgoing>sequenceFlow_9247481d-db06-4ed0-970f-cab0fe467ae3</outgoing>
      <outgoing>id_12</outgoing>
    </parallelGateway>
    <sequenceFlow id="sequenceFlow_fdaa89f0-f5bc-4cb6-996a-3e8fccf1ec10" sourceRef="id_6" targetRef="fork_id_7"/>
    <receiveTask id="id_10" messageRef="message_41ad3702-3d72-48cb-90c1-d63d953b4c75" name="id_10">
      <incoming>sequenceFlow_9247481d-db06-4ed0-970f-cab0fe467ae3</incoming>
      <outgoing>sequenceFlow_bdd39ef0-dc12-41a0-b786-c9662004f461</outgoing>
    </receiveTask>
    <sequenceFlow id="sequenceFlow_9247481d-db06-4ed0-970f-cab0fe467ae3" sourceRef="fork_id_7" targetRef="id_10"/>
    <receiveTask id="id_11" messageRef="message_50f74c50-0fe2-4237-8c85-38c7d308f8f5" name="id_11">
      <incoming>sequenceFlow_bdd39ef0-dc12-41a0-b786-c9662004f461</incoming>
      <outgoing>sequenceFlow_c9926523-9639-4c07-aa0b-a48e398e6d35</outgoing>
    </receiveTask>
    <sequenceFlow id="sequenceFlow_bdd39ef0-dc12-41a0-b786-c9662004f461" sourceRef="id_10" targetRef="id_11"/>
    <parallelGateway id="join_id_8" name="join_id_8">
      <incoming>sequenceFlow_c9926523-9639-4c07-aa0b-a48e398e6d35</incoming>
      <incoming>sequenceFlow_261cceb0-e30a-449b-8e5b-2e3c08077c76</incoming>
      <outgoing>sequenceFlow_2af7390d-8e97-4dc5-bfeb-e46fe82dce16</outgoing>
    </parallelGateway>
    <sequenceFlow id="sequenceFlow_c9926523-9639-4c07-aa0b-a48e398e6d35" sourceRef="id_11" targetRef="join_id_8"/>
    <sequenceFlow id="id_12" sourceRef="fork_id_7" targetRef="id_13"/>
    <serviceTask id="id_13" name="id_13">
      <extensionElements>
        <ns0:taskDefinition retries="3" type="job_id_13"/>
      </extensionElements>
      <incoming>id_12</incoming>
      <outgoing>sequenceFlow_17ff3152-4d4b-43a8-8a89-2522078f8743</outgoing>
    </serviceTask>
    <receiveTask id="id_14" messageRef="message_224b1044-5a9a-4158-ae9f-a55ba35a4194" name="id_14">
      <incoming>sequenceFlow_17ff3152-4d4b-43a8-8a89-2522078f8743</incoming>
      <outgoing>sequenceFlow_261cceb0-e30a-449b-8e5b-2e3c08077c76</outgoing>
    </receiveTask>
    <sequenceFlow id="sequenceFlow_17ff3152-4d4b-43a8-8a89-2522078f8743" sourceRef="id_13" targetRef="id_14"/>
    <sequenceFlow id="sequenceFlow_261cceb0-e30a-449b-8e5b-2e3c08077c76" sourceRef="id_14" targetRef="join_id_8"/>
    <receiveTask id="id_15" messageRef="message_6b5014bf-6e09-4674-92ae-30ea493d46a3" name="id_15">
      <incoming>sequenceFlow_2af7390d-8e97-4dc5-bfeb-e46fe82dce16</incoming>
      <outgoing>sequenceFlow_5c1c75e6-d1a3-488d-afe9-bd1349924e50</outgoing>
    </receiveTask>
    <sequenceFlow id="sequenceFlow_2af7390d-8e97-4dc5-bfeb-e46fe82dce16" sourceRef="join_id_8" targetRef="id_15"/>
    <parallelGateway id="fork_id_16" name="fork_id_16">
      <incoming>sequenceFlow_5c1c75e6-d1a3-488d-afe9-bd1349924e50</incoming>
      <outgoing>sequenceFlow_9426a80e-ff47-4c92-b2ed-2bbeddf88d50</outgoing>
      <outgoing>id_20</outgoing>
    </parallelGateway>
    <sequenceFlow id="sequenceFlow_5c1c75e6-d1a3-488d-afe9-bd1349924e50" sourceRef="id_15" targetRef="fork_id_16"/>
    <serviceTask id="id_19" name="id_19">
      <extensionElements>
        <ns0:taskDefinition retries="3" type="job_id_19"/>
      </extensionElements>
      <incoming>sequenceFlow_9426a80e-ff47-4c92-b2ed-2bbeddf88d50</incoming>
      <outgoing>sequenceFlow_a5a92611-b5ae-40dc-ac2e-f7f1b244d624</outgoing>
    </serviceTask>
    <sequenceFlow id="sequenceFlow_9426a80e-ff47-4c92-b2ed-2bbeddf88d50" sourceRef="fork_id_16" targetRef="id_19"/>
    <parallelGateway id="join_id_17" name="join_id_17">
      <incoming>sequenceFlow_a5a92611-b5ae-40dc-ac2e-f7f1b244d624</incoming>
      <incoming>sequenceFlow_f797d75f-e4d4-4477-934f-b20d45373976</incoming>
      <outgoing>sequenceFlow_e607d406-0f23-471d-88fb-440ef301656e</outgoing>
    </parallelGateway>
    <sequenceFlow id="sequenceFlow_a5a92611-b5ae-40dc-ac2e-f7f1b244d624" sourceRef="id_19" targetRef="join_id_17"/>
    <sequenceFlow id="id_20" sourceRef="fork_id_16" targetRef="id_21"/>
    <receiveTask id="id_21" messageRef="message_d741b9f5-b41a-4870-8768-bb4840996083" name="id_21">
      <incoming>id_20</incoming>
      <outgoing>sequenceFlow_e909dc76-b629-4d00-a345-51c312911e56</outgoing>
    </receiveTask>
    <receiveTask id="id_22" messageRef="message_2b14010d-6dbd-4046-aa9a-b93fe94c61e8" name="id_22">
      <incoming>sequenceFlow_e909dc76-b629-4d00-a345-51c312911e56</incoming>
      <outgoing>sequenceFlow_f797d75f-e4d4-4477-934f-b20d45373976</outgoing>
    </receiveTask>
    <sequenceFlow id="sequenceFlow_e909dc76-b629-4d00-a345-51c312911e56" sourceRef="id_21" targetRef="id_22"/>
    <sequenceFlow id="sequenceFlow_f797d75f-e4d4-4477-934f-b20d45373976" sourceRef="id_22" targetRef="join_id_17"/>
    <exclusiveGateway id="join_id_5" name="join_id_5">
      <incoming>sequenceFlow_e607d406-0f23-471d-88fb-440ef301656e</incoming>
      <incoming>sequenceFlow_e600fb91-437b-4526-9f52-feb582347aff</incoming>
      <outgoing>sequenceFlow_77671685-9a10-4751-81d2-332fc01daa2c</outgoing>
    </exclusiveGateway>
    <sequenceFlow id="sequenceFlow_e607d406-0f23-471d-88fb-440ef301656e" sourceRef="join_id_17" targetRef="join_id_5"/>
    <intermediateCatchEvent id="id_23" name="id_23">
      <incoming>sequenceFlow_8ea7d338-8b95-4a25-8cdf-213822b80098</incoming>
      <outgoing>sequenceFlow_e600fb91-437b-4526-9f52-feb582347aff</outgoing>
      <messageEventDefinition id="messageEventDefinition_5f543012-beb2-4e0f-942d-ef0a90d03595" messageRef="message_889503dd-92fc-4413-a4c7-27cf7f75b710"/>
    </intermediateCatchEvent>
    <sequenceFlow id="sequenceFlow_8ea7d338-8b95-4a25-8cdf-213822b80098" sourceRef="fork_id_4" targetRef="id_23"/>
    <sequenceFlow id="sequenceFlow_e600fb91-437b-4526-9f52-feb582347aff" sourceRef="id_23" targetRef="join_id_5"/>
    <endEvent id="id_27" name="id_27">
      <incoming>sequenceFlow_77671685-9a10-4751-81d2-332fc01daa2c</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_77671685-9a10-4751-81d2-332fc01daa2c" sourceRef="join_id_5" targetRef="id_27"/>
  </process>
  <message id="message_14ad0df6-884f-4a86-9ef4-f9f9f64d404f" name="message_eventSubProcess_id_25">
    <extensionElements>
      <ns0:subscription correlationKey="=&quot;default_correlation_key&quot;"/>
    </extensionElements>
  </message>
  <message id="message_aa30e0fe-efc0-4365-bc42-0510a4e4484a" name="message_id_6">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <message id="message_41ad3702-3d72-48cb-90c1-d63d953b4c75" name="message_id_10">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <message id="message_50f74c50-0fe2-4237-8c85-38c7d308f8f5" name="message_id_11">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <message id="message_224b1044-5a9a-4158-ae9f-a55ba35a4194" name="message_id_14">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <message id="message_6b5014bf-6e09-4674-92ae-30ea493d46a3" name="message_id_15">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <message id="message_d741b9f5-b41a-4870-8768-bb4840996083" name="message_id_21">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <message id="message_2b14010d-6dbd-4046-aa9a-b93fe94c61e8" name="message_id_22">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <message id="message_889503dd-92fc-4413-a4c7-27cf7f75b710" name="message_id_23">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_c7d3f3d2-a6e2-41b0-8d71-dd4e69d3fcc0">
    <bpmndi:BPMNPlane bpmnElement="process_id_24" id="BPMNPlane_3ce10200-6838-426a-b94c-99f72583951d">
      <bpmndi:BPMNShape bpmnElement="eventSubProcess_id_25" id="BPMNShape_2837f9a6-0f06-4ad3-a48d-1d4dd8e7f86a" isExpanded="true">
        <dc:Bounds height="200.0" width="350.0" x="100.0" y="250.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="start_event_eventSubProcess_id_25" id="BPMNShape_ba891b3f-3806-45cc-837b-c64d91fbad2b">
        <dc:Bounds height="36.0" width="36.0" x="150.0" y="332.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="end_event_eventSubProcess_id_25" id="BPMNShape_2c160ef1-d6c3-40c7-93af-dcdad26052d2">
        <dc:Bounds height="36.0" width="36.0" x="236.0" y="332.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_2ddf0ba9-5aaf-4ae5-893d-bf9a05b04a7e" id="BPMNEdge_9fe19638-d48b-4fac-b627-98c64b67b138">
        <di:waypoint x="186.0" y="350.0"/>
        <di:waypoint x="236.0" y="350.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_26" id="BPMNShape_b9471601-bfa6-42be-bd92-489c485d88d2">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="id_26_variables_task" id="BPMNShape_12cff77e-230a-47ee-bcbc-df0d53789da3">
        <dc:Bounds height="80.0" width="100.0" x="186.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_3048f908-4fb1-4fd0-9bd3-2c3bbacdb5a5" id="BPMNEdge_c4661eb4-e64d-4792-a099-8e453c13ebe4">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="call_activity_id_0" id="BPMNShape_534a265a-7235-4f04-b163-e31bdec39a83">
        <dc:Bounds height="80.0" width="100.0" x="336.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_f9537a6c-e23f-4678-9c7e-a82cd15e1f7e" id="BPMNEdge_cdc67c9e-92bd-49ef-8bc9-1dc868dec8f6">
        <di:waypoint x="286.0" y="118.0"/>
        <di:waypoint x="336.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="fork_id_4" id="BPMNShape_a516ed40-e9d5-4486-bab3-731e2f91e865">
        <dc:Bounds height="50.0" width="50.0" x="486.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_f230cd76-68d2-4b5f-b00e-ce52c12b4bd8" id="BPMNEdge_e942015f-ee6d-4bc5-88c8-ad4322be7513">
        <di:waypoint x="436.0" y="118.0"/>
        <di:waypoint x="486.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_6" id="BPMNShape_741e4253-a77e-4f45-8590-28c33ee3cecd">
        <dc:Bounds height="36.0" width="36.0" x="586.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_4d7d042b-b017-49e7-8a2e-d57d32e98716" id="BPMNEdge_febb4979-4cfe-442a-9209-e2424f782b9e">
        <di:waypoint x="536.0" y="118.0"/>
        <di:waypoint x="586.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="fork_id_7" id="BPMNShape_4acf8b8a-7b49-4f0a-9f2b-4cbf21352b67">
        <dc:Bounds height="50.0" width="50.0" x="672.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_fdaa89f0-f5bc-4cb6-996a-3e8fccf1ec10" id="BPMNEdge_c17ce387-13e4-442a-8f8a-82b01fa7293b">
        <di:waypoint x="622.0" y="118.0"/>
        <di:waypoint x="672.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_10" id="BPMNShape_e2758530-344b-4b4b-a980-c12ef8c07b47">
        <dc:Bounds height="80.0" width="100.0" x="772.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_9247481d-db06-4ed0-970f-cab0fe467ae3" id="BPMNEdge_1b7afeee-45f0-43c5-a6bc-a89ce2c0f48a">
        <di:waypoint x="722.0" y="118.0"/>
        <di:waypoint x="772.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_11" id="BPMNShape_4f844f92-5126-4ce6-9d7f-9d3853fd0636">
        <dc:Bounds height="80.0" width="100.0" x="922.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_bdd39ef0-dc12-41a0-b786-c9662004f461" id="BPMNEdge_c8e63ae3-06e8-42ce-80ac-410089726e8f">
        <di:waypoint x="872.0" y="118.0"/>
        <di:waypoint x="922.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="join_id_8" id="BPMNShape_593ab53e-ce5f-4643-8c05-8afdfd19d400">
        <dc:Bounds height="50.0" width="50.0" x="1072.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_c9926523-9639-4c07-aa0b-a48e398e6d35" id="BPMNEdge_4c696256-4759-4fd5-b149-c73209a8cadf">
        <di:waypoint x="1022.0" y="118.0"/>
        <di:waypoint x="1072.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_13" id="BPMNShape_80a5019b-bd33-45f6-ba85-2bd029335a48">
        <dc:Bounds height="80.0" width="100.0" x="772.0" y="208.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="id_12" id="BPMNEdge_7b10d9ad-91b1-4abc-a2ba-fec2d71da0a8">
        <di:waypoint x="697.0" y="143.0"/>
        <di:waypoint x="697.0" y="248.0"/>
        <di:waypoint x="772.0" y="248.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_14" id="BPMNShape_c2ca8530-a161-4c10-8db1-685e2551d105">
        <dc:Bounds height="80.0" width="100.0" x="922.0" y="208.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_17ff3152-4d4b-43a8-8a89-2522078f8743" id="BPMNEdge_3d1abb06-b303-4232-a06d-0347b302f6d9">
        <di:waypoint x="872.0" y="248.0"/>
        <di:waypoint x="922.0" y="248.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_261cceb0-e30a-449b-8e5b-2e3c08077c76" id="BPMNEdge_79921735-cfbd-4890-a05f-c45d7da04d9b">
        <di:waypoint x="1022.0" y="248.0"/>
        <di:waypoint x="1072.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_15" id="BPMNShape_a8523ed5-c98d-4601-964b-29ab4489f467">
        <dc:Bounds height="80.0" width="100.0" x="1172.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_2af7390d-8e97-4dc5-bfeb-e46fe82dce16" id="BPMNEdge_943bb3da-2c83-4dd9-88a0-50d59fef76bf">
        <di:waypoint x="1122.0" y="118.0"/>
        <di:waypoint x="1172.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="fork_id_16" id="BPMNShape_0103059f-a5b2-430d-9d48-585e44b44eac">
        <dc:Bounds height="50.0" width="50.0" x="1322.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_5c1c75e6-d1a3-488d-afe9-bd1349924e50" id="BPMNEdge_a983800c-398b-4e13-98e4-842023751d19">
        <di:waypoint x="1272.0" y="118.0"/>
        <di:waypoint x="1322.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_19" id="BPMNShape_b5ea343a-24d2-43eb-9ceb-dd49dc8f768d">
        <dc:Bounds height="80.0" width="100.0" x="1422.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_9426a80e-ff47-4c92-b2ed-2bbeddf88d50" id="BPMNEdge_2a2ed368-1fa5-442e-8c92-0ff614e5bfe2">
        <di:waypoint x="1372.0" y="118.0"/>
        <di:waypoint x="1422.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="join_id_17" id="BPMNShape_6af8897c-1316-471f-a568-a13e50a469e1">
        <dc:Bounds height="50.0" width="50.0" x="1572.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_a5a92611-b5ae-40dc-ac2e-f7f1b244d624" id="BPMNEdge_c35ece4c-a0b5-4a7a-969d-0b434923ffd8">
        <di:waypoint x="1522.0" y="118.0"/>
        <di:waypoint x="1572.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_21" id="BPMNShape_9150fbf2-b6b8-4b1d-a64d-2f56e2645cb8">
        <dc:Bounds height="80.0" width="100.0" x="1422.0" y="208.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="id_20" id="BPMNEdge_fb71c283-dad4-43dc-96c7-bfc8add1c367">
        <di:waypoint x="1347.0" y="143.0"/>
        <di:waypoint x="1347.0" y="248.0"/>
        <di:waypoint x="1422.0" y="248.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_22" id="BPMNShape_a994aa96-43ba-41ef-b768-f94136ca8eca">
        <dc:Bounds height="80.0" width="100.0" x="1572.0" y="208.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_e909dc76-b629-4d00-a345-51c312911e56" id="BPMNEdge_e827ed7f-d568-48d8-84f7-0a4793f92331">
        <di:waypoint x="1522.0" y="248.0"/>
        <di:waypoint x="1572.0" y="248.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_f797d75f-e4d4-4477-934f-b20d45373976" id="BPMNEdge_c3e587f8-cbf6-4a11-85f4-3e50d176d1fb">
        <di:waypoint x="1672.0" y="248.0"/>
        <di:waypoint x="1572.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="join_id_5" id="BPMNShape_1b987438-bc31-4cf8-bdfb-78a6c99fc722" isMarkerVisible="true">
        <dc:Bounds height="50.0" width="50.0" x="1672.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_e607d406-0f23-471d-88fb-440ef301656e" id="BPMNEdge_f1e0904e-08dd-4d4d-9961-3caf9bd63fad">
        <di:waypoint x="1622.0" y="118.0"/>
        <di:waypoint x="1672.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_23" id="BPMNShape_9969c8b3-1761-4a1c-88fa-de1630a85d9a">
        <dc:Bounds height="36.0" width="36.0" x="586.0" y="186.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_8ea7d338-8b95-4a25-8cdf-213822b80098" id="BPMNEdge_7329e74e-2f3b-4192-9182-729df8168171">
        <di:waypoint x="511.0" y="143.0"/>
        <di:waypoint x="511.0" y="204.0"/>
        <di:waypoint x="586.0" y="204.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_e600fb91-437b-4526-9f52-feb582347aff" id="BPMNEdge_ed4aecb5-d2aa-46f3-958a-62e984830513">
        <di:waypoint x="622.0" y="204.0"/>
        <di:waypoint x="1672.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_27" id="BPMNShape_94e5044c-d71c-4467-8afc-96312bd2b29a">
        <dc:Bounds height="36.0" width="36.0" x="1772.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_77671685-9a10-4751-81d2-332fc01daa2c" id="BPMNEdge_482c7366-85a4-4a21-947e-5791142d9f8c">
        <di:waypoint x="1722.0" y="118.0"/>
        <di:waypoint x="1772.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
process.xml "process_child_id_3"[K002] (version:1) ------ 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="definitions_d7269ac3-abf8-4592-b6f0-24b451fcbd13" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process_child_id_3" isExecutable="true">
    <startEvent id="startEvent_5da7dbbe-117e-4227-91c1-f3178d6be67d">
      <outgoing>sequenceFlow_f00fb93b-3fbc-4911-85c1-324d447bee35</outgoing>
    </startEvent>
    <endEvent id="endEvent_da4c6aa1-2819-4d14-80dc-4d9df71638a8">
      <incoming>sequenceFlow_f00fb93b-3fbc-4911-85c1-324d447bee35</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_f00fb93b-3fbc-4911-85c1-324d447bee35" sourceRef="startEvent_5da7dbbe-117e-4227-91c1-f3178d6be67d" targetRef="endEvent_da4c6aa1-2819-4d14-80dc-4d9df71638a8"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_0f46faef-223e-4feb-a393-e6d506634216">
    <bpmndi:BPMNPlane bpmnElement="process_child_id_3" id="BPMNPlane_ff967b7e-fdff-4fe2-ba0d-e85181f90e31">
      <bpmndi:BPMNShape bpmnElement="startEvent_5da7dbbe-117e-4227-91c1-f3178d6be67d" id="BPMNShape_b5f9b445-326f-4305-abb6-01433ad45988">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endEvent_da4c6aa1-2819-4d14-80dc-4d9df71638a8" id="BPMNShape_9b8a4583-d2bb-4fe1-bcbd-401371902865">
        <dc:Bounds height="36.0" width="36.0" x="186.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_f00fb93b-3fbc-4911-85c1-324d447bee35" id="BPMNEdge_67a9eef6-33bd-433e-9ad1-89f338b54616">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
process.xml "process_child_id_0"[K003] (version:1) ------ 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" id="definitions_e9cb434b-b608-4a00-b58d-3bb0f147501f" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process_child_id_0" isExecutable="true">
    <startEvent id="startEvent_9a3801ec-dab2-4b19-a33d-f31c6fa66314">
      <outgoing>sequenceFlow_a04afd03-c92d-41a6-a11e-5aa8dc0609e9</outgoing>
    </startEvent>
    <receiveTask id="id_1" messageRef="message_5a951a71-2aec-4211-a94d-0585d0a49233" name="id_1">
      <incoming>sequenceFlow_a04afd03-c92d-41a6-a11e-5aa8dc0609e9</incoming>
      <outgoing>sequenceFlow_b572a849-48cc-44d7-85a1-c6be874f724a</outgoing>
    </receiveTask>
    <sequenceFlow id="sequenceFlow_a04afd03-c92d-41a6-a11e-5aa8dc0609e9" sourceRef="startEvent_9a3801ec-dab2-4b19-a33d-f31c6fa66314" targetRef="id_1"/>
    <receiveTask id="id_2" messageRef="message_0ce578d1-056d-4db8-9c41-bc8e766831c7" name="id_2">
      <incoming>sequenceFlow_b572a849-48cc-44d7-85a1-c6be874f724a</incoming>
      <outgoing>sequenceFlow_76838392-99ed-49f2-a063-bf33339c7590</outgoing>
    </receiveTask>
    <sequenceFlow id="sequenceFlow_b572a849-48cc-44d7-85a1-c6be874f724a" sourceRef="id_1" targetRef="id_2"/>
    <callActivity id="call_activity_id_3" name="call_activity_id_3">
      <extensionElements>
        <ns0:calledElement processId="process_child_id_3" propagateAllChildVariables="true"/>
      </extensionElements>
      <incoming>sequenceFlow_76838392-99ed-49f2-a063-bf33339c7590</incoming>
      <outgoing>sequenceFlow_6610660c-2695-4edc-bf53-40d0e4b5624e</outgoing>
    </callActivity>
    <sequenceFlow id="sequenceFlow_76838392-99ed-49f2-a063-bf33339c7590" sourceRef="id_2" targetRef="call_activity_id_3"/>
    <endEvent id="endEvent_90eebbda-8d38-431a-921d-4cb109f1389e">
      <incoming>sequenceFlow_6610660c-2695-4edc-bf53-40d0e4b5624e</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_6610660c-2695-4edc-bf53-40d0e4b5624e" sourceRef="call_activity_id_3" targetRef="endEvent_90eebbda-8d38-431a-921d-4cb109f1389e"/>
  </process>
  <message id="message_5a951a71-2aec-4211-a94d-0585d0a49233" name="message_id_1">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <message id="message_0ce578d1-056d-4db8-9c41-bc8e766831c7" name="message_id_2">
    <extensionElements>
      <ns0:subscription correlationKey="=correlationKey"/>
    </extensionElements>
  </message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_f9cc24f8-b647-4184-a723-edbc857184a6">
    <bpmndi:BPMNPlane bpmnElement="process_child_id_0" id="BPMNPlane_44c51c1d-1b99-4e39-af74-705bd5385496">
      <bpmndi:BPMNShape bpmnElement="startEvent_9a3801ec-dab2-4b19-a33d-f31c6fa66314" id="BPMNShape_8b523182-cebf-4b2d-bc39-5bb5a31dbc56">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="id_1" id="BPMNShape_6e545eee-878c-46a3-9b6c-41b266ec1aaf">
        <dc:Bounds height="80.0" width="100.0" x="186.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_a04afd03-c92d-41a6-a11e-5aa8dc0609e9" id="BPMNEdge_bb72456d-ecf7-423f-b8ac-dc02b897b2b1">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_2" id="BPMNShape_a3f6cfa6-c645-40a3-952d-9b0bdb7dfad2">
        <dc:Bounds height="80.0" width="100.0" x="336.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_b572a849-48cc-44d7-85a1-c6be874f724a" id="BPMNEdge_0564d9f8-879a-471f-8d62-9b199fd35685">
        <di:waypoint x="286.0" y="118.0"/>
        <di:waypoint x="336.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="call_activity_id_3" id="BPMNShape_58a1c2c6-c2ad-4df9-b8e7-d1484aba161c">
        <dc:Bounds height="80.0" width="100.0" x="486.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_76838392-99ed-49f2-a063-bf33339c7590" id="BPMNEdge_d92c82e3-f6b4-4f43-844d-8fa7a16939c8">
        <di:waypoint x="436.0" y="118.0"/>
        <di:waypoint x="486.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="endEvent_90eebbda-8d38-431a-921d-4cb109f1389e" id="BPMNShape_258fef68-791d-4a8e-af9b-3a9df020c5df">
        <dc:Bounds height="36.0" width="36.0" x="636.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_6610660c-2695-4edc-bf53-40d0e4b5624e" id="BPMNEdge_dd0a257c-64cf-455f-a643-0abb3024c4aa">
        <di:waypoint x="586.0" y="118.0"/>
        <di:waypoint x="636.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
--------------- Decomposed keys (for debugging) -----------------
  -1 <-> -1
K001 <-> 2251799813685249
K002 <-> 2251799813685250
K003 <-> 2251799813685251
K004 <-> 2251799813685252
K005 <-> 2251799813685253
K006 <-> 2251799813685254
K007 <-> 2251799813685255
K008 <-> 2251799813685256
K009 <-> 2251799813685257
K010 <-> 2251799813685258
K011 <-> 2251799813685259
K012 <-> 2251799813685260
K013 <-> 2251799813685261
K014 <-> 2251799813685262
K015 <-> 2251799813685263
K016 <-> 2251799813685264
K017 <-> 2251799813685265
K018 <-> 2251799813685266
K019 <-> 2251799813685267
K020 <-> 2251799813685268
K021 <-> 2251799813685269
K022 <-> 2251799813685270
K023 <-> 2251799813685271
K024 <-> 2251799813685272
K025 <-> 2251799813685273
K026 <-> 2251799813685274
K027 <-> 2251799813685275
K028 <-> 2251799813685276
K029 <-> 2251799813685277
K030 <-> 2251799813685278
K031 <-> 2251799813685279
K032 <-> 2251799813685280
K033 <-> 2251799813685281
K034 <-> 2251799813685282
K035 <-> 2251799813685283
K036 <-> 2251799813685284
K037 <-> 2251799813685285
K038 <-> 2251799813685286
K039 <-> 2251799813685287
K040 <-> 2251799813685288
K041 <-> 2251799813685289
K042 <-> 2251799813685290
K043 <-> 2251799813685291
K044 <-> 2251799813685292
13:30:19.142 [] DEBUG io.camunda.zeebe.util.buffer - Close stream processor
13:30:19.144 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
13:30:19.180 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - Close appender for log stream stream-1
13:30:19.180 [stream-1-write-buffer] DEBUG io.camunda.zeebe.dispatcher - Dispatcher closed
13:30:19.180 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-1 close 2 readers
13:30:19.181 [] DEBUG io.camunda.zeebe.broker.test - Clean up test files on path /tmp/junit658390812768213013
13:30:19.181 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
13:30:19.182 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
13:30:19.182 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
13:30:19.183 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
13:30:19.183 [] INFO  io.camunda.zeebe.engine.processing.streamprocessor.FailedPropertyBasedTestDataPrinter - Data of failed test case: TestDataRecord{processSeed=-3355698362188536227, executionPathSeed=-3156714708834832115}
13:30:19.200 [] INFO  io.camunda.zeebe.engine.processing.streamprocessor.FailedPropertyBasedTestDataPrinter - Test case failed at: ScheduledExecutionStep{step=StepPublishMessage[correlationKeyValue=default_correlation_key,messageName=message_eventSubProcess_id_25,variables={=default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}
13:30:19.201 [] INFO  io.camunda.zeebe.engine.processing.streamprocessor.FailedPropertyBasedTestDataPrinter - Execution path of failed test case:
ScheduledExecutionStep{step=StepTriggerTimerStartEvent[timeToAdd=PT29M,variables={}], activationTime=PT0S, startTime=PT0S, endTime=PT29M, activationDuration=PT29M}
ScheduledExecutionStep{step=StepActivateAndCompleteJob[jobType=id_26_variables,variables={correlationKey=default_correlation_key, =default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}
ScheduledExecutionStep{step=StepPublishMessage[correlationKeyValue=default_correlation_key,messageName=message_id_1,variables={correlationKey=default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}
ScheduledExecutionStep{step=StepPublishMessage[correlationKeyValue=default_correlation_key,messageName=message_id_2,variables={correlationKey=default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}
--failed here--> ScheduledExecutionStep{step=StepPublishMessage[correlationKeyValue=default_correlation_key,messageName=message_eventSubProcess_id_25,variables={=default_correlation_key}], activationTime=PT29M, startTime=PT29M, endTime=PT29M, activationDuration=PT0S}

io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.camunda.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:72)
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessExecutionRandomizedPropertyTest.shouldExecuteProcessToEnd(ProcessExecutionRandomizedPropertyTest.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:52)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

        

```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: `1.0.0-alpha7`
 - Configuration:

### PR DESCRIPTION
**Pull request by saig0**
## Description

* terminate the call activity if an interrupting boundary event is triggered and the child instance transitions to completing concurrently
* avoid that the process instance gets stuck in the call activity if the child process instance processes a `complete` command and the call activity is in state `terminating`
  * previously, it wrote a `complete` command for the call activity after the child instance is completed
  * the command was rejected because the call activity is in state `terminating`  
 
## Related issues

closes #6959 
closes #6957

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/CallActivityProcessor.java [hunk 1]
```diff
@@ -104,27 +104,27 @@ public void beforeExecutionPathCompleted(
...
-        break;
-      case ELEMENT_TERMINATING:
-        // the call activity is already terminating, it doesn't matter that the child completed
-        // do nothing
-        break;
-      default:
-        final var message = String.format(UNABLE_TO_COMPLETE_FROM_STATE_MESSAGE, currentState);
-        throw new BpmnProcessingException(callActivityContext, message);
-    }
+    // nothing to do before the child is completed
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/CallActivityProcessor.java:107]: Should we add an empty body as default implementation of this `beforeExecutionPathCompleted` on the interface?

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java [hunk 2]
```diff
@@ -471,6 +473,62 @@ public void shouldTerminateOnCompleting() {
...
+            .key(timerCreated.getKey()));
+
+    // then
+    assertThat(
+            RecordingExporter.records()
+                .limitToProcessInstance(processInstanceKey)
+                .processInstanceRecords())
+        .extracting(r -> tuple(r.getValue().getBpmnElementType(), r.getIntent()))
+        .containsSubsequence(
+            tuple(BpmnElementType.CALL_ACTIVITY, ProcessInstanceIntent.TERMINATE_ELEMENT),
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java:522]: I would remove the commands from the assertion, we just want to make sure the correct events have happened.

**Review by korthout — APPROVED** [review]
Great solution. LGTM 🥂 

Please have a look at my minor comments before merging

PS: note that the backport bot is having problems. I expect it will fail, so manual cherry-picking is probably required.
