### PR TITLE
Store message correlate request data in state

### LINKED ISSUE #20568: Store request data in state
<h2>Description</h2>

In #20196 we stored the request data in the `MessageSubscriptionRecord`. After further implementation we've come to the conclusion that this doesn't work in all cases. Specifically in the case where the `MessageSubscription` gets rejected, we have no way to access the request data we need in order to send a response.

Instead we will create a new `ColumnFamily`. This will store the request data using the key of the message. The data will be stored using the `MessageCorrelation.CORRELATING` event. It gets removed in either the `MessageCorrelation.CORRELATED` or `MessageCorrelation.NOT_CORRELATED` events.

What should we do:
- Create the new `ColumnFamily`
- Add a new `MessageCorrelation.CORRELATING` intent
- Add the request data and message key to the `MessageCorrelationRecord`
- Create the `MessageCorrelationCorrelatingApplier` and store the request data in the new `ColumnFamily`
- Revert the changes of #20196 
- Change all usages of the request data in the `MessageSubscriptionRecord` to the new `ColumnFamily` instead.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

This PR reverts a change that was made earlier where we stored the request data on the `MessageSubscriptionRecord`. It turns out this option doesn't work properly for all cases (see [here](https://github.com/camunda/camunda/issues/16304#issuecomment-2268366752)).

The PR introduces a new `ColumnFamily`. This will be responsible for storing the request data. To store the data we also needed a new intent (`MessageCorrelation.CORRELATING`). This comes with the applier to actually store the data.

Note that I've changed the id's of the intents in this PR. As this functionality is not released yet this does't cause any issues regarding backwards compatibility.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #20568

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageCorrelationState.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+      final long messageKey, final long requestId, final int requestStreamId) {
+    this.messageKey.wrapLong(messageKey);
+    requestData.setRequestIdProp(requestId).setRequestStreamIdProp(requestStreamId);
+    messageCorrelationColumnFamily.insert(this.messageKey, requestData);
+  }
+
+  @Override
+  public RequestData getRequestData(final long messageKey) {
+    this.messageKey.wrapLong(messageKey);
+    return messageCorrelationColumnFamily.get(this.messageKey);
```
Comment (nicpuppa) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageCorrelationState.java:51]: ❓ Should we return a copy of the record instead of the record itself ? Like we do for other records

❓ What happens if the request data is not found in the state ? Is it possible ?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/RequestData.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+ * except in compliance with the Camunda License 1.0.
+ */
+package io.camunda.zeebe.engine.state.message;
+
+import io.camunda.zeebe.db.DbValue;
+import io.camunda.zeebe.msgpack.UnpackedObject;
+import io.camunda.zeebe.msgpack.property.IntegerProperty;
+import io.camunda.zeebe.msgpack.property.LongProperty;
+
+public class RequestData extends UnpackedObject implements DbValue {
```
Comment (nicpuppa) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/RequestData.java:15]: 🔧 Is the name too generic ? Should we specify that this is related to messages ?

**Review by nicpuppa — COMMENTED** [review]
Hey @remcowesterhoud great work, overall it looks good. I left some questions to discuss, please have a look

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/RequestData.java (hunk 2 above)
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/RequestData.java:15]: I don't think that's necessary. The object only stores request data, if we ever need this for a different feature there's no problem with this being reused.

Comment (nicpuppa) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/RequestData.java:15]: Ok, I see. Then should we move this class into another package ?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageCorrelationState.java (hunk 1 above)
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageCorrelationState.java:51]: > Should we return a copy of the record instead of the record itself ? Like we do for other records

This isn't required, please note that the `RequestData` is not a record but a `DbValue`. We don't make copies for other `DbValues` either, e.g.:

```java
  @Override
  public StoredMessage getMessage(final long messageKey) {
    this.messageKey.wrapLong(messageKey);
    return messageColumnFamily.get(this.messageKey);
  }
```

> What happens if the request data is not found in the state ? Is it possible ?

This method will return `null` and we will likely end up in an NPE. This is why before getting it I check if it exists using the `existsRequestDataForMessageKey` method.
This does remind me that I missed to write a test for getting without value so I'll add that 😄

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/RequestData.java (hunk 2 above)
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/RequestData.java:15]: > Ok, I see. Then should we move this class into another package ?

If you have a good suggestion I'm happy to move it. I figured we could move it if we ever actually use it in multiple places.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageCorrelationState.java (hunk 1 above)
Comment (nicpuppa) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageCorrelationState.java:51]: > This isn't required, please note that the `RequestData` is not a record but a `DbValue`. We don't make copies for other `DbValues` either, e.g.:

This is not true:

```
  @Override
  public CompensationSubscription get(
      final String tenantId, final long processInstanceKey, final long recordKey) {
    wrapCompensationKeys(processInstanceKey, recordKey, tenantId);
    return compensationSubscriptionColumnFamily
        .get(tenantAwareProcessInstanceKeyCompensableActivityId)
        .copy();
  }
```

We had a discussion about this as a team [internal](https://camunda.slack.com/archives/C05DH1F5TAR/p1707908005239069) . `TransactionalColumnFamily.get` returns an object which gets mutated with every future get invocation

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/RequestData.java (hunk 2 above)
Comment (nicpuppa) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/RequestData.java:15]: Not really. I'd suggest to leave the class there and if needed we can move it as you said 👍

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageCorrelationState.java (hunk 1 above)
Comment (remcowesterhoud) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageCorrelationState.java:51]: I see. It's not a problem at this time as we won't get request data twice, but I'll change it to be future proof 👍

**Comment by remcowesterhoud** [comment]
@nicpuppa Please have a look at the last commit that adds the copy 🙂

**Comment by nicpuppa** [comment]
@remcowesterhoud are you adding also the missing test ?

**Comment by remcowesterhoud** [comment]
@nicpuppa The test has arrived

**Review by nicpuppa — APPROVED** [review]
Thanks @remcowesterhoud
