### PR TITLE
fix: bail out when processing results were written but not committed

### LINKED ISSUE #24675: Unrecoverable errors when updating state are not handled correctly
In `ProcessingStateMachine#updateState` we have already written processing results and try to commit the corresponding transaction. All `RecoverableException`s , such as `ZeebeDbException` are handled by the `RecoverableRetryStrategy` by simply retrying to commit the transaction.

When an exception occurs that is not a `RecoverableException`, the behavior is wrong however: https://github.com/camunda/camunda/blob/56c6fca751a0fb919982e17d55782698e7e12b65/zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L659-L667

Here we call `errorHandlingInTransaction` which calls the current processor with the exception. This can result in a new processing result, for example a rejection of the command. Then we try to `updateState` again. The problem is that the processing result from `errorHandlingInTransaction` is discarded and that runtime state and log have diverged: We already wrote previous processing results, but didn't commit the resulting state changes. Instead, we commit the state changes and not write the processing results from error handling.

This _might_ be a theoretical case because there's not much that can go wrong in `updateState` that is not a `ZeebeDbException`. However, we should still ensure that we behave correctly in this case. Because writing the processing results but failing to commit the corresponding state changes is not a recoverable state, we should fail the stream processor entirely, possibly relying on a step-down such that another member can take over and eventually arrive at the correct state by replaying the already written events.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
If committing state changes fails unexpectedly, i.e. not due to a regular `ZeebeDbException`, we can't continue processing because log and runtime state have diverged. We bail out by stopping processing and indicating a dead partition.

A test is added to assert this new behavior. It uses reflection to inject a broken transaction into the `ProcessingStateMachine` because it did not seem worth to add dedicated testing infrastructure for this test alone.

closes #24675

### CODE REVIEW

**Comment by lenaschoenburg** [comment]
@ChrisKujawa I've assigned you to review because we have discussed this problem before and you are most familiar with the StreamProcessor. Let me know if I should find someone else to review though.

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 1]
```diff
@@ -652,13 +652,11 @@ private void updateState() {
...
         (bool, throwable) -> {
           if (throwable != null) {
-            LOG.error(ERROR_MESSAGE_UPDATE_STATE_FAILED, currentRecord, metadata, throwable);
-            onError(
-                throwable,
-                () -> {
-                  errorHandlingInTransaction(throwable);
-                  updateState();
-                });
+            // Log entries were written already, but committing state changes failed with an
```
Comment (ChrisKujawa) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:655]: 🔧 Can you change the state machine documentation above  then as well https://github.com/camunda/camunda/pull/31459/files#diff-aca559d3c449b7f34472294c4e1de56a525bc6a80b875de0d4328380d543f4f2L83-L95

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 2]
```diff
@@ -652,13 +652,11 @@ private void updateState() {
         retryFuture,
         (bool, throwable) -> {
           if (throwable != null) {
-            LOG.error(ERROR_MESSAGE_UPDATE_STATE_FAILED, currentRecord, metadata, throwable);
```
Comment (ChrisKujawa) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:655]: ❓ I think we can delete the const `ERROR_MESSAGE_UPDATE_STATE_FAILED` then as well?

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 1 above)
Comment (ChrisKujawa) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:655]: ❓ Does it make sense to switch the order then? 🤔 I think before we had it like this because it could failed to write to the dispatcher, but now it can only fail when OOD? 🤔 And it would be retried on IOE? This would also be the case for the update state?

File: zeebe/stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorTest.java [hunk 3]
```diff
@@ -1499,6 +1503,49 @@ void shouldUseProcessingFilter() {
...
+    final var processingStateMachineField =
+        StreamProcessor.class.getDeclaredField("processingStateMachine");
+    processingStateMachineField.setAccessible(true);
+    final var processingStateMachine =
+        (ProcessingStateMachine)
+            processingStateMachineField.get(streamPlatform.getStreamProcessor());
+    final var transactionContextField =
+        ProcessingStateMachine.class.getDeclaredField("transactionContext");
+    transactionContextField.setAccessible(true);
+    transactionContextField.set(processingStateMachine, mockTransactionContext);
```
Comment (ChrisKujawa) [inline zeebe/stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorTest.java:1528]: 🙈

Comment (ChrisKujawa) [reply zeebe/stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorTest.java:1528]: Couldn't we pass in a DB when creating the StreamProcessor, that fails on commit a transaction ? 🤔

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @lenaschoenburg I have added some comments, but might make sense to shortly sync on this PR :)

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 1 above)
Comment (lenaschoenburg) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:655]: Hm good point, I haven't considered that at all. I think we should still stick with the current order though, first writing follow up records, then committing state. Otherwise, we might commit state, then restart. That'd be an unrecoverable scenario because state and log have diverged again. The current node has committed state changes that others will never see because there are no corresponding log entries.

File: zeebe/stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorTest.java (hunk 3 above)
Comment (lenaschoenburg) [reply zeebe/stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorTest.java:1528]: In theory sure :+1: But as I tried to justify in the PR description:
> It uses reflection to inject a broken transaction into the ProcessingStateMachine because it did not seem worth to add dedicated testing infrastructure for this test alone.

I don't see this being a common use case and hacking in support for this in `StreamPlatformExtension` and `StreamProcessorTestContext` did not seem worth the effort.

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 1 above)
Comment (ChrisKujawa) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:653]: Please change the doc as above mentioned https://github.com/camunda/camunda/pull/31459/files#diff-aca559d3c449b7f34472294c4e1de56a525bc6a80b875de0d4328380d543f4f2L83-L95

Comment (ChrisKujawa) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:650]: Done with https://github.com/camunda/camunda/pull/31459/commits/8034cee2cb9b0d0a6757a6ac0bb1401c217f1975

File: zeebe/stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorTest.java (hunk 3 above)
Comment (ChrisKujawa) [reply zeebe/stream-platform/src/test/java/io/camunda/zeebe/stream/impl/StreamProcessorTest.java:1528]: I did this via https://github.com/camunda/camunda/pull/31459/commits/7651a1c119b3990f7a96846e02add83a0d241fdd (just to try it out and see how it looks).

I feel it can become useful if we want to test further edge cases regarding failing transaction or any db related. WDYT? 

Feel free to dismiss it if you disagree or dont like it :)

**Review by ChrisKujawa — APPROVED** [review]
Thanks for fixing @lenaschoenburg 👍🏼

**Comment by lenaschoenburg** [comment]
Well thanks for fixing my fix :sweat_smile:
