### PR TITLE
Revert storing migrations in MigrationState

### LINKED ISSUE #14406: Migration could result in inconsistent data on rolling update
**Describe the bug**

Kudos to @romansmirnov for identifying this issue!

With https://github.com/camunda/zeebe/issues/13763, already executed migration tasks are marked as finished in the runtime state, to avoid rerunning already executed migrations with every restart.

This can lead to inconsistent states of snapshots across the brokers when a rolling update is performed. This is due to the fact that during the update brokers running an old version of zeebe are create a different state when replaying events than it would be the case when running the new version already.

**To Reproduce/Scenario**

_Given_
With 8.3 a new column family `PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY` has been introduced. It maps a process instance key to its process definition. This new column family is used when trying to delete a process definition. However, in 8.2 that specific column family `PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY` does not exist.

_When_
The user upgrades from 8.2 to 8.3, and the upgrade happens in a rolling update manner, broker by broker.

During that update, it may happen that a broker `x` (already updated to 8.3) will replicate a (already migrated) snapshot `s1` to a broker `y` which is still on version 8.2.

As the snapshot `s1` was already migrated by broker `x`, it contains an entry marking the migration task as finished.

After broker `y` installed the received snapshot `s1`, it will start to replay the events.

While replaying, it won't put anything into the column family `PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY` because broker `y` is still running the previous version where this column family didn't exist.

In the meantime, broker `y` takes a new snapshot `s2`. Eventually, broker `y` gets updated to 8.3

_Then_
, it will recover from snapshot `s2` but it won't run the migration task anymore because the respective migration task was already marked as finished in snapshot `s1`. Thus the snapshot state of broker `y` will not be consistent with the one of broker `x`. If broker `y` eventually becomes leader, the corrupted state will be used going forward.

**Expected behavior**

Migrations must be executed in a way to ensure all brokers have eventually a consistent snapshot state.

**Environment:**
- OS: 
- Zeebe Version: 8.3.x
- Configuration:

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

As explained in the linked issue there is an issue with storing migrations in the state. This could cause inconsistencies during rolling updates. This PR reverts this change and combines some existing migrations to no longer rely on this change.

⚠️ The migration mechanism was backported and some migrations rely on it in patch versions. I don't see much risk in this as long as we don't add any new migrations that rely on this mechanism!

## Related issues

closes #14406 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/DbProcessMigrationState.java [hunk 1]
```diff
@@ -185,11 +185,19 @@ public void migrateProcessStateForMultiTenancy() {
...
+          for (long version = 1; version <= highestVersion; version++) {
+            if (!value.getKnownVersions().contains(version)) {
+              value.addKnownVersion(version);
+            }
+          }
+
           versionInfoColumnFamily.insert(tenantAwareIdKey, value);
-          deprecatedNextValueColumnFamily.deleteExisting(key);
+          deprecatedProcessVersionColumnFamily.deleteExisting(key);
         });
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/DbProcessMigrationState.java:201]: 😍

File: engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java [hunk 2]
```diff
@@ -22,6 +24,12 @@ public String getIdentifier() {
     return getClass().getSimpleName();
   }
 
+  @Override
+  public boolean needsToRun(final ProcessingState processingState) {
+    return processingState.isEmpty(ZbColumnFamilies.PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY)
+        && !processingState.isEmpty(ZbColumnFamilies.ELEMENT_INSTANCE_KEY);
+  }
+
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: ❌ I believe this condition is wrong. In the current migration setup, it's possible that:
- a migration task was run by a leader storing it in a snapshot
- the snapshot is installed on a follower running a previous version
- the follower doesn't apply events the same way, but does build state in follower-mode
- when becoming leader (after upgrade to the newer version), the follower must still run the migration on this newly added data to the `ELEMENT_INSTANCE_KEY` CF
- it won't run the migration because there are already entries in the `PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY` CF
- So not all entries in the `ELEMENT_INSTANCE_KEY` CF have a corresponding entry in the `PROCESS_INSTANCE_KEY_BY_DEFITINION_KEY` CF

File: engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/MultiTenancyMigration.java [hunk 3]
```diff
@@ -35,5 +51,11 @@ public void runMigration(final MutableProcessingState processingState) {
     migrationState.migrateMessageEventSubscriptionForMultiTenancy();
     migrationState.migrateProcessMessageSubscriptionForMultiTenancy();
     migrationState.migrateJobStateForMultiTenancy();
+
+    // These migrations are not related to MT! However, they perform a migration within a
+    // ColumnFamily. Because of this there is no easy way to detect if they should run, or not. By
+    // making them part of this MigrationTask we can use the 'needToRun' of this task.
+    processingState.getJobState().cleanupTimeoutsWithoutJobs();
+    processingState.getJobState().cleanupBackoffsWithoutJobs();
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/MultiTenancyMigration.java:59]: ❌ In order to make this safe, we need to add an additional condition to the `needsToRun`. Consider the following:
- leader runs multi-tenancy migrations because it has process or decisions deployed and stored in deprecated CF
- it makes a snapshot
- follower on an older version installs the snapshot
- follower applies events without cleaning up job timeout/backoff CFs as it's on older version, but not new process/decision is deployed
- follower upgrades to newer version and becomes leader
- it doesn't run the migration because no new process/decision was deployed, but job timeout/backoff CF are still dirty

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @remcowesterhoud 👏 

❌ I think there are a few mistakes in the `needsToRun` conditions. Please have a look.

>⚠️ The migration mechanism was backported and some migrations rely on it in patch versions. I don't see much risk in this as long as we don't add any new migrations that rely on this mechanism!

❓ I'd like to verify that it doesn't pose any problems before assuming this. Can you share some more details (link) about when/how these were backported? 

>Revert "refactor(engine): invert if-statement"

🔧 For reverts, you can use the commit type `revert: ...` which is accepted by commitlint.

**Comment by remcowesterhoud** [comment]
> 🔧 For reverts, you can use the commit type revert: ... which is accepted by commitlint.

Commitlint accepts reverts either way 🤷

**Comment by remcowesterhoud** [comment]
> ❓ I'd like to verify that it doesn't pose any problems before assuming this. Can you share some more details (link) about when/how these were backported?

It's backported as a result of https://github.com/camunda/zeebe/pull/13886

File: engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java (hunk 2 above)
Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: AFAIk there is no way to prevent this except for always running the migration. This is what we've been doing since we had migrations. Do you know a better check?

Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: Just `!processingState.isEmpty(ZbColumnFamilies.ELEMENT_INSTANCE_KEY)` should be enough right

Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: Oh wait, problem is that this is then run every time....

Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: Exactly 😅

Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: I'm confused why this is a problem now and for all the other older migration we've had since 1.3. Do you know?

Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: 🤔 How about a different approach... Can we use `parentChildColumnFamily` to find all process instances?

This CF contains either:
1. 👍 `[-1, process instance key] -> [nil]` for process instances
2. 🚫 `[an element instance key, another element instance key] -> [nil]` for any other element instance

Point 1 is also the case for child process instances, as no flowScopeKey is set for the child process instance: https://github.com/camunda/zeebe/blob/013a8bcd888b5d715593eaeb16bcbae62fcad5b4/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnStateTransitionBehavior.java#L498-L516. Which is used by the activating applier to determine the parent of the instance to create: https://github.com/camunda/zeebe/blob/013a8bcd888b5d715593eaeb16bcbae62fcad5b4/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementActivatingApplier.java#L54-L56. Which is used to set the parent of the instance to create: https://github.com/camunda/zeebe/blob/013a8bcd888b5d715593eaeb16bcbae62fcad5b4/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbElementInstanceState.java#L148-L152. And finally, inserted with either `-1` or an actual element instance key: https://github.com/camunda/zeebe/blob/013a8bcd888b5d715593eaeb16bcbae62fcad5b4/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbElementInstanceState.java#L198-L201

Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: >I'm confused why this is a problem now and not for all the other older migration we've had since 1.3. Do you know?

Perhaps those aren't correct either. Let's focus on this one first, and then we look at the others again to make sure.

Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: > How about a different approach... Can we use `parentChildColumnFamily` to find all process instances?

TIL we insert a parent-child relationship for something without a parent. That's so weird 😆 I guess it could work then. We iterate with startAtKey `-1` and we should find everything without a parent, which if I understand correct would be all process instances.

Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: > Use the -1 in a whileEqualPrefix to find all process instances that need to be migrated. Perhaps we can also use this to know whether it must be run or not.

I don't see how it solves the migration issue. We can iterate over a different CF but the problem remains the same. What I was thinking of is we could remove the migration altogether and just use the parent-child column family. It's kind of confusing but it solves the migration issue until we have a better solution.

Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: > What I was thinking of is we could remove the migration altogether and just use the parent-child column family. 

This will actually be a big performance hit if there's many process instances as it requires looping over all of them, getting the element instance and checking if the process definition key matches.

Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: >  It can also help determine whether it should be run, if we can efficiently count all entries. It's supposed to be a 1:1 relation, so if the counts don't match we must run migration. I'm not sure how efficiently we can count though

Clever, I like it. Let's see how easy it is to find the amount of entries.

> Hmm, so you're saying it isn't a solution to remove the migration altogether? Or are you referring here to using the parent-child column family to determine whether to run the migration? Or something else?

I was referring to determine if there's running instances using the parent-child CF. It's a possibility, but I prefer the migration as it will be infinitely faster. If we would go this way we'd iterate over more element instances and have to manually get them from the state to be able to check the process definition.

Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/migration/to_8_3/ProcessInstanceByProcessDefinitionMigration.java:32]: We resolved this by introducing a count (with prefix) method and comparing the entries in the two column families.

**Review by korthout — APPROVED** [review]
Blocking comments have been resolved.

LGTM 👍 

💭 Considering the backporting to previous releases, we should still consider this. It does not have to block the merging of this pull request, and the release of 8.3 though.

bors merge
