### PR TITLE
fix: flaky command distribution tests by disabling the scheduler

### LINKED ISSUE #30294: Make batch operation execution configurable
The batch operation execution should be configurable, this means following fields: 

* pollingInterval (Currently it's configured hardcoded in BatchOperationSetupProcessors)
* QUERY_SIZE (in BatchOperationExecutionScheduler)
  * Maybe something which is related to the underlying DB (ES just supports 10000) 
* CHUNK_SIZE_IN_RECORD (in BatchOperationExecutionScheduler)
* MAX_DB_CHUNK_SIZE (in DbBatchOperationState)
* ...

### PR DESCRIPTION
**Pull request by stoerti**
## Description

This PR tries to fix the flakiness of batch operation CANCEL/PAUSE/RESUME commands in the `CommandDistributionIdempotencyTest` by introducing a new engineConfig `batchOperationSchedulerInterval`.

This enables us to basically deactivate the scheduler in specific tests. This way we make sure, that the batchOperation is not already processed and can be paused/resumed/canceled.

### CODE REVIEW

**Review by p-wunderlich — APPROVED** [review]
LGTM, thanks @stoerti !

Just one node, can you maybe split the commits? Introducing the config is also a feature since we need it nevertheless, and I think this should be an own feat commit. The fix is then to use this in the test. 

Besides of this, no re-review from me is needed, so I already approve it.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationSetupProcessors.java [hunk 1]
```diff
@@ -93,6 +94,6 @@ public static void addBatchOperationProcessors(
             new BatchOperationExecutionScheduler(
                 scheduledTaskStateFactory,
                 new BatchOperationItemKeyProvider(searchClientsProxy),
-                Duration.ofMillis(1000)));
+                engineConfiguration.getBatchOperationSchedulerInterval()));
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationSetupProcessors.java:97]: 🔧 we might want to pass the `engineConfig` as a constructor parameter, and use it from within the scheduler to get the scheduler interval config. since we might want to pass other configs too

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/configuration/engine/BatchOperationCfg.java [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+ * except in compliance with the Camunda License 1.0.
+ */
+package io.camunda.zeebe.broker.system.configuration.engine;
+
+import io.camunda.zeebe.broker.system.configuration.ConfigurationEntry;
+import io.camunda.zeebe.engine.EngineConfiguration;
+import java.time.Duration;
+
+public class BatchOperationCfg implements ConfigurationEntry {
+  private Duration batchOperationSchedulerInterval =
```
Comment (mustafadagher) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/configuration/engine/BatchOperationCfg.java:15]: 🔧 too long of a name. it's a given that the field is a `batchOperation` field from the class name.
I think `schedulingInterval` is enough

the long name makes more sense in the `EngineConfiguration` class, but not here

**Review by mustafadagher — APPROVED** [review]
LGTM. Only a couple of suggestions.
