### PR TITLE
fix: resolve serialization issue with persistent web session

### LINKED ISSUE #28367: ConversionFailedException on WebSessionPersistence
**Describe the bug**

When running with the cluster identity setup and enabling persistent sessions, an actually successful login to e.g. Operate fails with a 500, caused by an exception during serialization of the WebSession.

**To Reproduce**

1. Run StandaloneCamunda with the following config: profiles `identity,operate,tasklist,broker,consolidated-auth` and enabling  `camunda.persistent.sessions.enabled=true` + `camunda.rest.enabled=true`
2. Login to e.g. Operate
3. Login fails with a 500

**Expected behavior**

Should just work.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.Object] to type [byte[]] for value [org.springframework.security.core.context.SecurityContextImpl@15d1438a]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:182) ~[spring-core-6.2.1.jar:6.2.1]
	at io.camunda.authentication.session.WebSessionMapper$SpringBasedWebSessionAttributeConverter.serialize(WebSessionMapper.java:111) ~[camunda-authentication-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.authentication.session.WebSessionMapper.lambda$serializeSessionAttributes$0(WebSessionMapper.java:69) ~[camunda-authentication-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at io.camunda.authentication.session.WebSessionMapper.serializeSessionAttributes(WebSessionMapper.java:68) ~[camunda-authentication-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.authentication.session.WebSessionMapper.toPersistentWebSession(WebSessionMapper.java:34) ~[camunda-authentication-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at java.base/java.util.Optional.map(Unknown Source) ~[?:?]
	at io.camunda.authentication.session.WebSessionRepository.saveWebSessionIfChanged(WebSessionRepository.java:103) ~[camunda-authentication-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.authentication.session.WebSessionRepository.save(WebSessionRepository.java:52) ~[camunda-authentication-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.authentication.session.WebSessionRepository.save(WebSessionRepository.java:19) ~[camunda-authentication-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:229) ~[spring-session-core-3.4.1.jar:3.4.1]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:145) ~[spring-session-core-3.4.1.jar:3.4.1]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82) ~[spring-session-core-3.4.1.jar:3.4.1]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:362) ~[spring-web-6.2.1.jar:6.2.1]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:278) ~[spring-web-6.2.1.jar:6.2.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.2.1.jar:6.2.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:633) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:411) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:331) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:268) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:380) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:208) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:285) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:149) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.34.jar:10.1.34]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:64) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:33) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:358) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-6.2.1.jar:6.2.1]
	... 40 more
Caused by: java.io.NotSerializableException: io.camunda.authentication.entity.AuthenticationContext
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:?]
	at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source) ~[?:?]
	at org.springframework.core.serializer.DefaultSerializer.serialize(DefaultSerializer.java:46) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.core.serializer.Serializer.serializeToByteArray(Serializer.java:56) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:60) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:33) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:358) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-6.2.1.jar:6.2.1]
	... 40 more
```

</p>
</details>

**Environment:**
- OS: 
- Camunda Version: 8.8.0-SNAPSHOT
- Configuration:

### PR DESCRIPTION
**Pull request by Ben-Sheppard**
## Description

As per the related issue, when persistent sessions are enabled, there is a serialization exception thrown. This is due to two nested objects that are unable to be serialized (`RoleEntity` and `AuthenticationContext`). In this PR I:

1.  Make those two classes serializable
2. Add tests to check that moving to and from those serializations work as expected

## Related issues

closes https://github.com/camunda/camunda/issues/28367

### CODE REVIEW

File: authentication/src/test/java/io/camunda/authentication/session/WebSessionMapperTest.java [hunk 1]
```diff
@@ -31,6 +36,34 @@ void setUp() {
     webSessionMapper = new WebSessionMapper(webSessionAttributeConverter);
   }
 
+  @Test
+  void toPersistentSessionWithCamundaPrinciple() {
```
Comment (remcowesterhoud) [inline authentication/src/test/java/io/camunda/authentication/session/WebSessionMapperTest.java:40]:
```suggestion
  void toPersistentSessionWithCamundaPrincipal() {
```

🤡 In principle, this should be principal

File: authentication/src/test/java/io/camunda/authentication/session/WebSessionMapperTest.java [hunk 2]
```diff
@@ -93,5 +126,43 @@ void fromPersistentSession() {
     assertThat((TestAttribute) webSession.getAttribute("attribute2")).isEqualTo(testAttribute);
   }
 
+  @Test
+  void fromPersistentSessionWithCamundaPrinciple() {
```
Comment (remcowesterhoud) [inline authentication/src/test/java/io/camunda/authentication/session/WebSessionMapperTest.java:130]:
```suggestion
  void fromPersistentSessionWithCamundaPrincipal() {
```

🤡 Same here

**Review by remcowesterhoud — APPROVED** [review]
Glad it was an easy fix. Can't wait to try it once there's a snapshot image available 😎

File: authentication/src/test/java/io/camunda/authentication/session/WebSessionMapperTest.java (hunk 1 above)
Comment (Ben-Sheppard) [reply authentication/src/test/java/io/camunda/authentication/session/WebSessionMapperTest.java:40]: Damn it! 🙈
