### PR TITLE
Fix flaky BackupRestoreIT

### LINKED ISSUE #27850: io.camunda.it.backup.BackupRestoreIT is flaky
**Summary**

- How often does the test fail? 15 times in the last 48 hours
- Does it block your work? Sort of
- Do we suspect that it is a real failure? No

**Failures**

See: https://dashboard.int.camunda.com/d/ae2j69npxh3b4f/flaky-tests-camunda-camunda-monorepo?orgId=1&from=now-2d&to=now&timezone=browser&var-branch=main

You can find links to failed runs associated to the tests in the dashboard.

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

```
  <testcase name="shouldBackupAndRestoreToPreviousState(BackupRestoreTestConfig)[2] config=BackupRestoreTestConfig[databaseType=opensearch, bucket=bucket] (Flaky Test)" classname="io.camunda.it.backup.BackupRestoreIT" time="39.106">
    <failure type="feign.FeignException$NotFound (Flaky Test)"><![CDATA[feign.FeignException$NotFound: [404] during [GET] to [http://0.0.0.0:1431/actuator/backupHistory/1] [HistoryBackupClient#getBackup(long)]: [{"message":"No backup with id [1] found."}]
	at feign.FeignException.clientErrorStatus(FeignException.java:249)
	at feign.FeignException.errorStatus(FeignException.java:223)
	at feign.FeignException.errorStatus(FeignException.java:213)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:103)
	at feign.InvocationContext.decodeError(InvocationContext.java:133)
	at feign.InvocationContext.proceed(InvocationContext.java:80)
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:69)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:109)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:53)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:104)
	at jdk.proxy2/jdk.proxy2.$Proxy214.getBackup(Unknown Source)
	at io.camunda.it.backup.BackupRestoreIT.lambda$shouldBackupAndRestoreToPreviousState$1(BackupRestoreIT.java:137)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
```

Error happens when checking for the first time for the backup state. This might be a race condition as this is still not ready to poll even though the backup is already in progress. 

The solution might be to add one poll delay for the first check to avoid this race condition. 

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes https://github.com/camunda/camunda/issues/27850

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java [hunk 1]
```diff
@@ -131,6 +127,7 @@ public void shouldBackupAndRestoreToPreviousState(final BackupRestoreTestConfig
     final var snapshots = takeResponse.getScheduledSnapshots();
 
     Awaitility.await("Backup completed")
+        .pollDelay(Duration.ofSeconds(1))
```
Comment (entangled90) [inline qa/integration-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java:130]: :thought_balloon: I'm not sure if this is enough, as it just waits 1 second before checking the condition the first time, but it should retry afterwards anyway..

Comment (rodrigo-lourenco-lopes) [reply qa/integration-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java:130]: We do retry after, at an unspecified poll interval, up until 600 seconds correct? Poll delay: "Specify the delay that will be used before Awaitility starts polling for the result the first time. If you don't specify a poll delay explicitly it'll be the same as the poll interval."
In the tests I did locally from the take backup command until we check this backup status was just a few miliseconds, thats why I though one second should be eneugh, or should it be larger?

Comment (entangled90) [reply qa/integration-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java:130]: I don't think that by waiting a bit before checking the first time the flakyness would resolve. Awaitility will retry to check the condition every `pollDelay`.
Were you able to reproduce the flakyness on your local machine before doing any changes?

Comment (rodrigo-lourenco-lopes) [reply qa/integration-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java:130]: Yes, but only when changing the code so that the get request is imediatly followed by the backup:

```
final var takeResponse = historyBackupClient.takeBackup(1L);
final var backupResponse = historyBackupClient.getBackup(1L);
 ```
 That's why I believe its just a race condition on the first get request being to fast after the backup is taken. 
 With the original test where we check the `takeResponse` contents first I was never able to reproduce, likely too slow on my machine.

Comment (entangled90) [reply qa/integration-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java:130]: I think i get why it works now:
if the first call is done immediately it may throw an exception, which is not catched.
By adding a second of sleep this is exception is not thrown.
I think we can get rid of the initial `pollDelay`, but catch exception thrown by `backupClient.getBackup(1L)`. 
It should work as long as the exception is considered an `AssertionFailure`

**Review by entangled90 — APPROVED** [review]
:rocket: Thank you very much!

File: qa/integration-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java (hunk 1 above)
Comment (rodrigo-lourenco-lopes) [reply qa/integration-tests/src/test/java/io/camunda/it/backup/BackupRestoreIT.java]: Thanks! Implemented your suggestion :)
