### PR TITLE
fix: rework message batch expiry to avoid scheduled command cache

### LINKED ISSUE #15574: Scheduled commands cache uses the wrong intent for caching message expiry
With https://github.com/camunda/zeebe/issues/13870, we introduced a cache for scheduled commands. On all branches, it is setup to cache `TimerIntent.TRIGGER`, `JobIntent.TIME_OUT`,`JobIntent.RECUR_AFTER_BACKOFF` and `MessageIntent.EXPIRE`:
https://github.com/camunda/zeebe/blob/1701fe1492277fac142b6285e79e0a40bd507e7f/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/StreamProcessorTransitionStep.java#L144-L149

The `MessageIntent.EXPIRE` intent is no longer used for message expiry though, instead we use `MessageBatchIntent.EXPIRE`, introduced in https://github.com/camunda/zeebe/pull/13400.

The impact is that message expiry is _not_ cached and https://github.com/camunda/zeebe/issues/13870 is not resolved for all cases. 

Relates to https://jira.camunda.com/browse/SUPPORT-28579

### PR DESCRIPTION
**Pull request by lenaschoenburg**
The scheduled command cache was configured with `MessageIntent.EXPIRE` but message expiry uses `MessageBatchIntent.EXPIRE`, making the cache completely ineffective.

Rather than just swapping the intent, this reworks the mechanism: the scheduler becomes a simple trigger that writes an empty `MessageBatchIntent.EXPIRE` command, and the processor queries messages that are expired (according to the current actor clock), expires up to `batchLimit` (now defaults to 100) messages, and writes a follow-up `MessageBatchIntent.EXPIRE` command if more remain, allowing batch processing to kick in.

The scheduled command cache now ensures that there's at most one scheduled `MessageBatchIntent.EXPIRE` command in the processing queue. Follow-up commands from previous runs might still be in flight.

closes #15574

### CODE REVIEW

**Comment by lenaschoenburg** [comment]
@lev-safro you were auto-assigned, feel free to assign someone else from core features for review.

**Comment by lenaschoenburg** [comment]
Hey @mustafadagher, since I just saw you worked on #50342, would you mind reviewing this one? :pray:

**Comment by entangled90** [comment]
I like how we all three decided to fix this after years in the same day :-D

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java [hunk 1]
```diff
@@ -7,95 +7,78 @@
...
+    final var expiredCount = new MutableLong(0);
+    final boolean hasMore =
+        messageState.visitMessagesWithDeadlineBeforeTimestamp(
+            clock.millis(),
+            null,
+            (deadline, messageKey) -> {
+              final var expiredMessageRecord =
+                  appendMessageBodyOnExpired
+                      ? messageState.getMessage(messageKey).getMessage()
+                      : emptyDeleteMessageCommand;
```
[the remark this answers is not in the document]
Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java:65]: Agreed, this edge case was handled before, but is missing here. It can happen that there's no message in the state with the given key.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java [hunk 2]
```diff
@@ -7,95 +7,78 @@
...
-      return 1;
-    } else {
-      // the message was expired before processing it here, so we can skip it
-      LOG.warn(
-          "Expected to expire messages in a batch, but message with key {} was not found.",
-          messageKey);
-      return 0;
+    if (hasMore) {
+      commandWriter.appendFollowUpCommand(
+          record.getKey(), MessageBatchIntent.EXPIRE, new MessageBatchRecord());
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java:81]: ❓ do we know that the batch record has a valid key here? 
💭 The only other place that appends this batch record is in `MessageTimeToLiveCheckScheduler` and it appends with a `NULL_KEY`. I don't know from the top of my mind right now if the StreamProcessor overrides this, but I doubt that it does.

⚠️ This might also influence caching batch expiry records.

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/MessageBatchRecord.java [hunk 3]
```diff
@@ -7,48 +7,13 @@
...
-import io.camunda.zeebe.msgpack.value.LongValue;
-import io.camunda.zeebe.msgpack.value.StringValue;
-import io.camunda.zeebe.msgpack.value.ValueArray;
 import io.camunda.zeebe.protocol.impl.record.UnifiedRecordValue;
 import io.camunda.zeebe.protocol.record.value.MessageBatchRecordValue;
-import java.util.List;
-import java.util.stream.Collectors;
-import java.util.stream.StreamSupport;
 
 public final class MessageBatchRecord extends UnifiedRecordValue
```
Comment (mustafadagher) [inline zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/MessageBatchRecord.java:13]: 🔧 this is solely used for message expiry. I'd rename it to `MessageExpiryBatchRecord`.

File: zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/MessageBatchRecordValue.java [hunk 4]
```diff
@@ -17,20 +17,13 @@
...
 @Value.Immutable
 @ImmutableProtocol(builder = ImmutableMessageBatchRecordValue.Builder.class)
-public interface MessageBatchRecordValue extends RecordValue {
-
-  /**
-   * @return list of the keys from the messages assigned to this batch
-   */
-  List<Long> getMessageKeys();
-}
+public interface MessageBatchRecordValue extends RecordValue {}
```
Comment (mustafadagher) [inline zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/MessageBatchRecordValue.java:29]: 🔧 this is solely used for message expiry. I'd rename it to `MessageExpiryBatchRecordValue`.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/StreamProcessorTransitionStep.java [hunk 5]
```diff
@@ -158,7 +158,7 @@ private static StreamProcessor createStreamProcessor(
             TimerIntent.TRIGGER,
             JobIntent.TIME_OUT,
             JobIntent.RECUR_AFTER_BACKOFF,
-            MessageIntent.EXPIRE);
+            MessageBatchIntent.EXPIRE);
```
Comment (mustafadagher) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/StreamProcessorTransitionStep.java:161]: ❌ with message batch key being always `-1` currently, what are we actually caching?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (lenaschoenburg) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java:65]: > It can happen that there's no message in the state with the given key

How can this happen?

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/StreamProcessorTransitionStep.java (hunk 5 above)
Comment (lenaschoenburg) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/StreamProcessorTransitionStep.java:161]: >The scheduled command cache now ensures that there's at most one scheduled MessageBatchIntent.EXPIRE command in the processing queue. Follow-up commands from previous runs might still be in flight.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java (hunk 2 above)
Comment (lenaschoenburg) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java:81]: We are using `-1` as key for the original `MessageBatchIntent.EXPIRE` command so the follow-up command will have `-1` too. That should be fine for commands?

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/StreamProcessorTransitionStep.java (hunk 5 above)
Comment (mustafadagher) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/StreamProcessorTransitionStep.java:161]: I see! Sorry, I overlooked this.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java (hunk 2 above)
Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java:81]: It's fine, I was just asking to be sure that we are aware of it.
💭 If we expect it to be always `-1`, we could have also used the `appendFollowUpCommand()` that doesn't take a key. It won't change anything, I'm just saying.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageBatchExpireProcessor.java:65]: could it not happen because of an invalid state, in worst case? 

💭 If I think logically about it: 
- The only way a message is removed from the state, is by `expirey`. 
- Expired messages are processed sync (using event appliers) in the batch expire processor.
- We have only one batch expire command being processed at a time.

So logically this should not happen in any happy scenario.

**Review by mustafadagher — APPROVED** [review]
Thanks @lenaschoenburg for working on this and responding to my comments. 
This looks good to me right now 👍 🚀

File: zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/MessageBatchRecord.java (hunk 3 above)
Comment (lenaschoenburg) [reply zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/MessageBatchRecord.java:13]: I'll leave this as is, I'm afraid of causing more confusion by renaming an already existing record.
