### PR TITLE
Fix boundary event connection in randomized tests

### LINKED ISSUE #11072: ProcessExecutionRandomizedPropertyTest failed to complete a process with a terminate end event
**Describe the bug**

The `ProcessExecutionRandomizedPropertyTest` failed with the following seed:

```
processSeed=5993146284312904381, 
executionPathSeed=-1211250216592319980
```

Other test cases with the same process seed failed as well.

The process contains a terminate end event and an error boundary event. The process looks incomplete because a flow end in a joining gateway without an end event.

image

**To Reproduce**

Run the `ProcessExecutionRandomizedPropertyTest` with 
* processSeed: `5993146284312904381`
* executionPathSeed `-1211250216592319980`

Related commit: https://github.com/camunda/zeebe/commit/d17bb4351de4b88b752b27027ad8985bd1af9a69. It includes the merged PR: https://github.com/camunda/zeebe/pull/10595.

**Expected behavior**

The `ProcessExecutionRandomizedPropertyTest` run successfully.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
--------
	[Timestamp] ['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
13:35:04 C DPLY      CREATE            - #01-> -1  -1 - 
13:35:04 E PROC      CREATED           - #02->#01 K01 - process.xml -> "process_id_4" (version:1)
13:35:04 E TIME      CREATED           - #03->#01 K03 -  @"id_5"[ -1]  in <process "K01"[?]> due T14:35:04.78
13:35:04 E DPLY      CREATED           - #04->#01 K02 - process.xml
13:35:04 E DPLY      FULLY_DISTRIBUTED - #05->#01 K02 - 
14:35:05 C TIME      TRIGGER           - #06-> -1 K03 -  @"id_5"[ -1]  in <process "K01"[?]> due T14:35:04.78
14:35:05 E TIME      TRIGGERED         - #07->#06 K03 -  @"id_5"[ -1]  in <process "K01"[K04]> due T14:35:04.78
14:35:05 E PROC_EVNT TRIGGERING        - #08->#06 K05 -  @"id_5"[K01] in <process K01[K04]> (no vars)
14:35:05 C PI        ACTIVATE          - #09->#06 K04 - PROCESS "process_id_4" in <process "process_id_4"[K04]>
14:35:05 E PI        ACTIVATING        - #10->#09 K04 - PROCESS "process_id_4" in <process "process_id_4"[K04]>
14:35:05 E PI        ACTIVATED         - #11->#09 K04 - PROCESS "process_id_4" in <process "process_id_4"[K04]>
14:35:05 E PROC_EVNT TRIGGERED         - #12->#09 K05 -  @"id_5"[K01] in <process K01[K04]> (no vars)
14:35:05 E PI        ACTIVATING        - #13->#09 K06 - START_EVENT "id_5" in <process "process_id_4"[K04]>
14:35:05 E PI        ACTIVATED         - #14->#09 K06 - START_EVENT "id_5" in <process "process_id_4"[K04]>
14:35:05 C PI        COMPLETE          - #15->#09 K06 - START_EVENT "id_5" in <process "process_id_4"[K04]>
14:35:05 E PI        COMPLETING        - #16->#15 K06 - START_EVENT "id_5" in <process "process_id_4"[K04]>
14:35:05 E PI        COMPLETED         - #17->#15 K06 - START_EVENT "id_5" in <process "process_id_4"[K04]>
14:35:05 E PI        SEQ_FLOW_TAKEN    - #18->#15 K07 - SEQUENCE_FLOW "sequenc..5dc7e98" in <process "process_id_4"[K04]>
14:35:05 C PI        ACTIVATE          - #19->#15 K08 - SERVICE_TASK "id_5_va..es_task" in <process "process_id_4"[K04]>
14:35:05 E PI        ACTIVATING        - #20->#19 K08 - SERVICE_TASK "id_5_va..es_task" in <process "process_id_4"[K04]>
14:35:05 E JOB       CREATED           - #21->#19 K09 - K09 "id_5_variables" @"id_5_va..es_task"[K08] 3 retries, in <process "process_id_4"[K04]> (no vars)
14:35:05 E PI        ACTIVATED         - #22->#19 K08 - SERVICE_TASK "id_5_va..es_task" in <process "process_id_4"[K04]>
14:35:05 C JOB_BATCH ACTIVATE          - #23-> -1  -1 - "id_5_variables" max: 10
14:35:05 E JOB_BATCH ACTIVATED         - #24->#23 K10 - "id_5_variables" 1/10
                K09 "id_5_variables" @"id_5_va..es_task"[K08] 3 retries, in <process "process_id_4"[K04]> (no vars)
14:35:05 C JOB       COMPLETE          - #25-> -1 K09 - K09 -1 retries, in <process ?[?]> with variables: {boundary_timer_id_1=PT8760H}
14:35:05 E JOB       COMPLETED         - #26->#25 K09 - K09 "id_5_variables" @"id_5_va..es_task"[K08] 3 retries, in <process "process_id_4"[K04]> with variables: {boundary_timer_id_1=PT8760H}
14:35:05 E PROC_EVNT TRIGGERING        - #27->#25 K11 -  @"id_5_va..es_task"[K08] in <process K01[K04]> with variables: {boundary_timer_id_1=PT8760H}
14:35:05 C PI        COMPLETE          - #28->#25 K08 - SERVICE_TASK "id_5_va..es_task" in <process "process_id_4"[K04]>
14:35:05 E PI        COMPLETING        - #29->#28 K08 - SERVICE_TASK "id_5_va..es_task" in <process "process_id_4"[K04]>
14:35:05 E VAR       CREATED           - #30->#28 K12 - boundary_timer_id_1->"PT8760H" in <process [K04]>
14:35:05 E PI        COMPLETED         - #31->#28 K08 - SERVICE_TASK "id_5_va..es_task" in <process "process_id_4"[K04]>
14:35:05 E PI        SEQ_FLOW_TAKEN    - #32->#28 K13 - SEQUENCE_FLOW "sequenc..ec34024" in <process "process_id_4"[K04]>
14:35:05 C PI        ACTIVATE          - #33->#28 K14 - SEND_TASK "id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        ACTIVATING        - #34->#33 K14 - SEND_TASK "id_1" in <process "process_id_4"[K04]>
14:35:05 E TIME      CREATED           - #35->#33 K15 -  @"boundar..er_id_1"[K14]  in <process "K01"[K04]> due 2023-11-22T14:35:05.314
14:35:05 E JOB       CREATED           - #36->#33 K16 - K16 "job_id_1" @"id_1"[K14] 3 retries, in <process "process_id_4"[K04]> (no vars)
14:35:05 E PI        ACTIVATED         - #37->#33 K14 - SEND_TASK "id_1" in <process "process_id_4"[K04]>
14:35:05 C JOB_BATCH ACTIVATE          - #38-> -1  -1 - "job_id_1" max: 10
14:35:05 E JOB_BATCH ACTIVATED         - #39->#38 K17 - "job_id_1" 1/10
                K16 "job_id_1" @"id_1"[K14] 3 retries, in <process "process_id_4"[K04]> with variables: {boundary_timer_id_1=PT8760H}
14:35:05 C JOB       THROW_ERROR       - #40-> -1 K16 - K16 -1 retries, error_id_1: in <process ?[?]> (no vars)
14:35:05 E JOB       ERROR_THROWN      - #41->#40 K16 - K16 "job_id_1" @"id_1"[K14] 3 retries, error_id_1: in <process "process_id_4"[K04]> (no vars)
14:35:05 E PROC_EVNT TRIGGERING        - #42->#40 K18 -  @"boundar..or_id_1"[K14] in <process K01[K04]> (no vars)
14:35:05 C PI        TERMINATE         - #43->#40 K14 - SEND_TASK "id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        TERMINATING       - #44->#43 K14 - SEND_TASK "id_1" in <process "process_id_4"[K04]>
14:35:05 E TIME      CANCELED          - #45->#43 K15 -  @"boundar..er_id_1"[K14]  in <process "K01"[K04]> due 2023-11-22T14:35:05.314
14:35:05 E PI        TERMINATED        - #46->#43 K14 - SEND_TASK "id_1" in <process "process_id_4"[K04]>
14:35:05 E PROC_EVNT TRIGGERED         - #47->#43 K18 -  @"boundar..or_id_1"[K14] in <process K01[K04]> (no vars)
14:35:05 E PI        ACTIVATING        - #48->#43 K19 - BOUNDARY_EVENT "boundar..or_id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        ACTIVATED         - #49->#43 K19 - BOUNDARY_EVENT "boundar..or_id_1" in <process "process_id_4"[K04]>
14:35:05 C PI        COMPLETE          - #50->#43 K19 - BOUNDARY_EVENT "boundar..or_id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        COMPLETING        - #51->#50 K19 - BOUNDARY_EVENT "boundar..or_id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        COMPLETED         - #52->#50 K19 - BOUNDARY_EVENT "boundar..or_id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        SEQ_FLOW_TAKEN    - #53->#50 K20 - SEQUENCE_FLOW "sequenc..42f476c" in <process "process_id_4"[K04]>
14:35:05 C PI        ACTIVATE          - #54->#50 K21 - EXCLUSIVE_GATEWAY "boundar..in_id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        ACTIVATING        - #55->#54 K21 - EXCLUSIVE_GATEWAY "boundar..in_id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        ACTIVATED         - #56->#54 K21 - EXCLUSIVE_GATEWAY "boundar..in_id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        COMPLETING        - #57->#54 K21 - EXCLUSIVE_GATEWAY "boundar..in_id_1" in <process "process_id_4"[K04]>
14:35:05 E PI        COMPLETED         - #58->#54 K21 - EXCLUSIVE_GATEWAY "boundar..in_id_1" in <process "process_id_4"[K04]>
14:35:05 C PI        COMPLETE          - #59->#54 K04 - PROCESS "process_id_4" in <process "process_id_4"[K04]>
14:35:05 E PI        COMPLETING        - #60->#59 K04 - PROCESS "process_id_4" in <process "process_id_4"[K04]>
14:35:05 E PI        COMPLETED         - #61->#59 K04 - PROCESS "process_id_4" in <process "process_id_4"[K04]>

-------------- Deployed Processes ----------------------
process.xml -> "process_id_4" (version:1)[K01] ------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" id="definitions_791e5009-f1e0-4a3e-b842-750a5b2d1b28" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process_id_4" isExecutable="true">
    <startEvent id="id_5" name="id_5">
      <outgoing>sequenceFlow_ddf38b33-61b1-4103-b211-11f2c5dc7e98</outgoing>
      <timerEventDefinition id="timerEventDefinition_856b84ca-6634-4368-bd2b-994a407c9994">
        <timeDate id="timeDate_da6ed194-b09d-42f7-b174-446e340be66e">=now() + duration("PT1H")</timeDate>
      </timerEventDefinition>
    </startEvent>
    <serviceTask id="id_5_variables_task" name="id_5_variables_task">
      <extensionElements>
        <ns0:taskDefinition type="id_5_variables"/>
      </extensionElements>
      <incoming>sequenceFlow_ddf38b33-61b1-4103-b211-11f2c5dc7e98</incoming>
      <outgoing>sequenceFlow_5b4d3578-867c-4b65-bc69-8be2bec34024</outgoing>
    </serviceTask>
    <sequenceFlow id="sequenceFlow_ddf38b33-61b1-4103-b211-11f2c5dc7e98" sourceRef="id_5" targetRef="id_5_variables_task"/>
    <sendTask id="id_1" name="id_1">
      <extensionElements>
        <ns0:taskDefinition retries="3" type="job_id_1"/>
      </extensionElements>
      <incoming>sequenceFlow_5b4d3578-867c-4b65-bc69-8be2bec34024</incoming>
      <outgoing>sequenceFlow_dccbbc45-2b22-496c-b998-dec5cb62a1eb</outgoing>
      <outgoing>sequenceFlow_958249d8-0010-4099-99f0-425e9a54e318</outgoing>
    </sendTask>
    <sequenceFlow id="sequenceFlow_5b4d3578-867c-4b65-bc69-8be2bec34024" sourceRef="id_5_variables_task" targetRef="id_1"/>
    <exclusiveGateway id="boundary_join_id_1" name="boundary_join_id_1">
      <incoming>sequenceFlow_dccbbc45-2b22-496c-b998-dec5cb62a1eb</incoming>
      <incoming>sequenceFlow_f1085ac7-d298-4432-a5ae-e3f9c42f476c</incoming>
    </exclusiveGateway>
    <sequenceFlow id="sequenceFlow_dccbbc45-2b22-496c-b998-dec5cb62a1eb" sourceRef="id_1" targetRef="boundary_join_id_1"/>
    <boundaryEvent attachedToRef="id_1" id="boundary_error_id_1" name="boundary_error_id_1">
      <outgoing>sequenceFlow_f1085ac7-d298-4432-a5ae-e3f9c42f476c</outgoing>
      <errorEventDefinition errorRef="error_bea42e11-05d9-4c1c-924e-e17015f9a612" id="errorEventDefinition_c8b7dd53-dc42-43f1-8c51-b0a33593aacf"/>
    </boundaryEvent>
    <sequenceFlow id="sequenceFlow_f1085ac7-d298-4432-a5ae-e3f9c42f476c" sourceRef="boundary_error_id_1" targetRef="boundary_join_id_1"/>
    <boundaryEvent attachedToRef="id_1" id="boundary_timer_id_1" name="boundary_timer_id_1">
      <outgoing>sequenceFlow_62c232a2-07f0-41f7-a3d4-6aeb6393ffb0</outgoing>
      <timerEventDefinition id="timerEventDefinition_0d6735c1-8d19-44a1-b7cf-bcd7b5e773bc">
        <timeDuration id="timeDuration_a57eda75-0687-45e9-a418-09e98475d78b">=boundary_timer_id_1</timeDuration>
      </timerEventDefinition>
    </boundaryEvent>
    <endEvent id="endEvent_fcf3a91d-6486-4185-a849-fd65c26846c8">
      <incoming>sequenceFlow_62c232a2-07f0-41f7-a3d4-6aeb6393ffb0</incoming>
      <terminateEventDefinition id="terminateEventDefinition_a67a56ab-bb7d-4f87-9560-b7ab106e9a92"/>
    </endEvent>
    <sequenceFlow id="sequenceFlow_62c232a2-07f0-41f7-a3d4-6aeb6393ffb0" sourceRef="boundary_timer_id_1" targetRef="endEvent_fcf3a91d-6486-4185-a849-fd65c26846c8"/>
    <sendTask id="id_2" name="id_2">
      <extensionElements>
        <ns0:taskDefinition retries="3" type="job_id_2"/>
      </extensionElements>
      <incoming>sequenceFlow_958249d8-0010-4099-99f0-425e9a54e318</incoming>
      <outgoing>sequenceFlow_92c54a4a-32db-44e7-82a8-b935d6ab6f9c</outgoing>
    </sendTask>
    <sequenceFlow id="sequenceFlow_958249d8-0010-4099-99f0-425e9a54e318" sourceRef="id_1" targetRef="id_2"/>
    <sendTask id="id_3" name="id_3">
      <extensionElements>
        <ns0:taskDefinition retries="3" type="job_id_3"/>
      </extensionElements>
      <incoming>sequenceFlow_92c54a4a-32db-44e7-82a8-b935d6ab6f9c</incoming>
      <outgoing>sequenceFlow_652fb0c8-6ef4-44fc-8340-a565d9af5aae</outgoing>
    </sendTask>
    <sequenceFlow id="sequenceFlow_92c54a4a-32db-44e7-82a8-b935d6ab6f9c" sourceRef="id_2" targetRef="id_3"/>
    <endEvent id="id_6" name="id_6">
      <incoming>sequenceFlow_652fb0c8-6ef4-44fc-8340-a565d9af5aae</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_652fb0c8-6ef4-44fc-8340-a565d9af5aae" sourceRef="id_3" targetRef="id_6"/>
  </process>
  <error errorCode="error_id_1" id="error_bea42e11-05d9-4c1c-924e-e17015f9a612"/>
  <bpmndi:BPMNDiagram id="BPMNDiagram_34e19cca-e9f3-4d4f-91f0-320614afec83">
    <bpmndi:BPMNPlane bpmnElement="process_id_4" id="BPMNPlane_eb04dc8b-d621-4b3e-8642-3cc8274011f8">
      <bpmndi:BPMNShape bpmnElement="id_5" id="BPMNShape_f28ca205-715e-45a6-9bda-68c57deacd0e">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="id_5_variables_task" id="BPMNShape_086aacbb-804a-4c74-a035-88a21595d827">
        <dc:Bounds height="80.0" width="100.0" x="186.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_ddf38b33-61b1-4103-b211-11f2c5dc7e98" id="BPMNEdge_ee1c9144-93f9-4401-a344-73c80e69e304">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_1" id="BPMNShape_76592f78-13ef-4145-84b1-80ceeb45762d">
        <dc:Bounds height="80.0" width="100.0" x="336.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_5b4d3578-867c-4b65-bc69-8be2bec34024" id="BPMNEdge_4c5ace45-b922-4adc-8ea8-0389a3697906">
        <di:waypoint x="286.0" y="118.0"/>
        <di:waypoint x="336.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="boundary_join_id_1" id="BPMNShape_075243af-8999-4b1d-ba16-b11f45918538" isMarkerVisible="true">
        <dc:Bounds height="50.0" width="50.0" x="486.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_dccbbc45-2b22-496c-b998-dec5cb62a1eb" id="BPMNEdge_f0e1413e-9a3a-42a2-bc9d-87220db89774">
        <di:waypoint x="436.0" y="118.0"/>
        <di:waypoint x="486.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="boundary_error_id_1" id="BPMNShape_775f6da8-c7e5-44a7-b482-b8093ce4d0a0">
        <dc:Bounds height="36.0" width="36.0" x="368.0" y="140.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_f1085ac7-d298-4432-a5ae-e3f9c42f476c" id="BPMNEdge_f12034ab-70a3-46c1-a1f8-cffe302954cc">
        <di:waypoint x="386.0" y="176.0"/>
        <di:waypoint x="386.0" y="226.0"/>
        <di:waypoint x="486.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="boundary_timer_id_1" id="BPMNShape_0aaef615-5f2c-492f-8854-9bc2bd280cbc">
        <dc:Bounds height="36.0" width="36.0" x="404.0" y="140.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endEvent_fcf3a91d-6486-4185-a849-fd65c26846c8" id="BPMNShape_f590b0d9-c016-43b0-9fb4-22acc8a664b5">
        <dc:Bounds height="36.0" width="36.0" x="452.5" y="208.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_62c232a2-07f0-41f7-a3d4-6aeb6393ffb0" id="BPMNEdge_8b0b1f5b-3948-4530-af29-84ea259bbf3c">
        <di:waypoint x="422.0" y="176.0"/>
        <di:waypoint x="422.0" y="226.0"/>
        <di:waypoint x="452.5" y="226.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_2" id="BPMNShape_f408dfbc-5919-4205-8b41-08cf2d2ffd54">
        <dc:Bounds height="80.0" width="100.0" x="486.0" y="193.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_958249d8-0010-4099-99f0-425e9a54e318" id="BPMNEdge_97454bde-5a3a-43cf-bd57-359186b9eb67">
        <di:waypoint x="386.0" y="158.0"/>
        <di:waypoint x="386.0" y="233.0"/>
        <di:waypoint x="486.0" y="233.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_3" id="BPMNShape_c0d90380-ede7-45fb-968c-ed1cb6454ec0">
        <dc:Bounds height="80.0" width="100.0" x="636.0" y="193.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_92c54a4a-32db-44e7-82a8-b935d6ab6f9c" id="BPMNEdge_141a2576-f67e-4a05-8977-7f266a0d02a2">
        <di:waypoint x="586.0" y="233.0"/>
        <di:waypoint x="636.0" y="233.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="id_6" id="BPMNShape_d99705a1-cfa7-4705-9b70-95148cdb1a36">
        <dc:Bounds height="36.0" width="36.0" x="786.0" y="215.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_652fb0c8-6ef4-44fc-8340-a565d9af5aae" id="BPMNEdge_af94a7bd-2c67-49a3-8c54-8245a8c52c39">
        <di:waypoint x="736.0" y="233.0"/>
        <di:waypoint x="786.0" y="233.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>


--------------- Decomposed keys (for debugging) -----------------
 -1 <-> -1
K01 <-> 2251799813685249
K02 <-> 2251799813685250
K03 <-> 2251799813685251
K04 <-> 2251799813685252
K05 <-> 2251799813685253
K06 <-> 2251799813685254
K07 <-> 2251799813685255
K08 <-> 2251799813685256
K09 <-> 2251799813685257
K10 <-> 2251799813685258
K11 <-> 2251799813685259
K12 <-> 2251799813685260
K13 <-> 2251799813685261
K14 <-> 2251799813685262
K15 <-> 2251799813685263
K16 <-> 2251799813685264
K17 <-> 2251799813685265
K18 <-> 2251799813685266
K19 <-> 2251799813685267
K20 <-> 2251799813685268
K21 <-> 2251799813685269

13:35:10.726 [] DEBUG io.camunda.zeebe.broker.logstreams - Close stream processor
13:35:10.731 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
13:35:10.814 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - Close appender for log stream stream-1
13:35:10.823 [stream-1-write-buffer] DEBUG io.camunda.zeebe.dispatcher - Dispatcher closed
13:35:10.823 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-1 close 2 readers
13:35:10.824 [] DEBUG io.camunda.zeebe.broker.test - Clean up test files on path /tmp/junit18055719865843167754
13:35:10.824 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
13:35:10.825 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
13:35:10.825 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
13:35:10.826 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
13:35:10.869 [] INFO  io.camunda.zeebe.engine.processing.randomized.FailedPropertyBasedTestDataPrinter - Data of failed test case: TestDataRecord{processSeed=5993146284312904381, executionPathSeed=-1211250216592319980}
13:35:10.880 [] INFO  io.camunda.zeebe.engine.processing.randomized.FailedPropertyBasedTestDataPrinter - Test case failed at: ScheduledExecutionStep{step=StepActivateAndTimeoutJob[elementId=id_2,jobType=job_id_2,variables={}], activationTime=PT1H, startTime=PT1H, endTime=PT2H, activationDuration=PT1H}
13:35:10.882 [] INFO  io.camunda.zeebe.engine.processing.randomized.FailedPropertyBasedTestDataPrinter - Execution path of failed test case:
ScheduledExecutionStep{step=StepTriggerTimerStartEvent[timeToAdd=PT1H,variables={}], activationTime=PT0S, startTime=PT0S, endTime=PT1H, activationDuration=PT1H}
ScheduledExecutionStep{step=StepActivateAndCompleteJob[elementId=id_5_variables_task,jobType=id_5_variables,variables={boundary_timer_id_1=PT8760H}], activationTime=PT1H, startTime=PT1H, endTime=PT1H, activationDuration=PT0S}
ScheduledExecutionStep{step=StepActivateBPMNElement[elementId=id_1,variables={}], activationTime=PT1H, startTime=PT1H, endTime=PT1H, activationDuration=PT0S}
ScheduledExecutionStep{step=StepActivateJobAndThrowError[elementId=id_1,errorCode=error_id_1,jobType=job_id_1,variables={}], activationTime=PT1H, startTime=PT1H, endTime=PT1H, activationDuration=PT0S}
ScheduledExecutionStep{step=StepActivateBPMNElement[elementId=id_2,variables={}], activationTime=PT1H, startTime=PT1H, endTime=PT1H, activationDuration=PT0S}
--failed here--> ScheduledExecutionStep{step=StepActivateAndTimeoutJob[elementId=id_2,jobType=job_id_2,variables={}], activationTime=PT1H, startTime=PT1H, endTime=PT2H, activationDuration=PT1H}
ScheduledExecutionStep{step=StepActivateAndFailJob[elementId=id_2,jobType=job_id_2,updateRetries=false,variables={}], activationTime=PT2H, startTime=PT2H, endTime=PT2H, activationDuration=PT0S}
ScheduledExecutionStep{step=StepActivateAndCompleteJob[elementId=id_2,jobType=job_id_2,variables={}], activationTime=PT1H, startTime=PT2H, endTime=PT2H, activationDuration=PT1H}
ScheduledExecutionStep{step=StepActivateBPMNElement[elementId=id_3,variables={}], activationTime=PT2H, startTime=PT2H, endTime=PT2H, activationDuration=PT0S}
ScheduledExecutionStep{step=StepActivateAndTimeoutJob[elementId=id_3,jobType=job_id_3,variables={}], activationTime=PT2H, startTime=PT2H, endTime=PT3H, activationDuration=PT1H}
ScheduledExecutionStep{step=StepActivateAndFailJob[elementId=id_3,jobType=job_id_3,updateRetries=true,variables={}], activationTime=PT3H, startTime=PT3H, endTime=PT3H, activationDuration=PT0S}
ScheduledExecutionStep{step=StepActivateAndCompleteJob[elementId=id_3,jobType=job_id_3,variables={}], activationTime=PT2H, startTime=PT3H, endTime=PT3H, activationDuration=PT1H}

io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria

	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.camunda.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:77)
	at io.camunda.zeebe.engine.util.ProcessExecutor.waitForJobToBeCreated(ProcessExecutor.java:206)
	at io.camunda.zeebe.engine.util.ProcessExecutor.activateAndTimeoutJob(ProcessExecutor.java:166)
	at io.camunda.zeebe.engine.util.ProcessExecutor.applyStep(ProcessExecutor.java:69)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.camunda.zeebe.engine.processing.randomized.ProcessExecutionRandomizedPropertyTest.shouldExecuteProcessToEnd(ProcessExecutionRandomizedPropertyTest.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: `8.2.0-SNAPSHOT`
- Configuration:

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

When a task contains 2 boundary event, of which the 2nd one is a terminate end event we'd move the process builder to the task. If the first boundary created a gateway we should move to the gateway instead.

By adding a small check to decide which node we should move to we can make sure we end up at the correct task to continue processing as expected.

## Related issues

closes #11072 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@saig0 Please have a look at this fix. This resolves the issue where a gateway doesn't get any outgoing sequence flows. Here is the process with the seed mentioned in the issue after this change:
image

File: engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ProcessExecutionRandomizedPropertyTest.java [hunk 1]
```diff
@@ -83,9 +84,9 @@ public void shouldExecuteProcessToEnd() {
...
   @Parameters(name = "{0}")
   public static Collection<TestDataGenerator.TestDataRecord> getTestRecords() {
-    return TestDataGenerator.generateTestRecords(
-        Integer.parseInt(PROCESS_COUNT), Integer.parseInt(EXECUTION_PATH_COUNT));
-    //    return List.of(
-    //        TestDataGenerator.regenerateTestRecord(-8532388551768899121L, -6565756334590616537L));
+    //    return TestDataGenerator.generateTestRecords(
+    //        Integer.parseInt(PROCESS_COUNT), Integer.parseInt(EXECUTION_PATH_COUNT));
+    return List.of(
+        TestDataGenerator.regenerateTestRecord(5993146284312904381L, -1211250216592319980L));
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ProcessExecutionRandomizedPropertyTest.java:90]: :x: Don't change the process generator to a fixed seed. We want to generate random processes. :rofl:

**Review by saig0 — APPROVED** [review]
@remcowesterhoud the fix looks good. :+1: 

:x: But please revoke the changes in `ProcessExecutionRandomizedPropertyTest.java` before merging the PR.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ProcessExecutionRandomizedPropertyTest.java (hunk 1 above)
Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/randomized/ProcessExecutionRandomizedPropertyTest.java]: Oops 🙈

**Comment by remcowesterhoud** [comment]
Not sure why bors got cancelled 🤔 

bors merge
