### PR TITLE
fix(engine): propagate only defined variables

### LINKED ISSUE #13959: When using a call activity, only the variables defined via input mappings are propagated
**Description**

As a user/developer, I can specify which variables are propagated from parent to child called process instances. They can specify whether all variables or specific ones need to be propagated.

Therefore, a property called `propagateAllParentVariables` is introduced to enable/disable copying all variables to its child process instance:

1. When `propagateAllParentVariables` is set to `true`, all variables are propagated to the child process instance.
2. When `propagateAllParentVariables` is set to `false`, only the variables defined via _input mappings_ are propagated to the child process instance.

The current default behavior - propagating all variables - does not change, meaning, the property's `propagateAllParentVariables` default value is `true`.

---

related to https://github.com/camunda/product-hub/issues/141

### PR DESCRIPTION
**Pull request by romansmirnov**
This commit introduces a new property called
`propagateAllParentVariables` to allow a user to control if all variables or just specific ones need to be propagated to a child process instances when activating a call activity.

1. (Default) `propagateAllParentVariables = true`, then Zeebe behaves as currently (i.e., all variables a propagated to the child process instance).
2. `propagateAllParentVariables = false`, only the variables defined via input mappings are propagated to the child process instance (if any).

The property `propagateAllParentVariables` can be set per call activity.

## Related issues

closes #13959 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [x] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [x] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java [hunk 1]
```diff
@@ -279,6 +279,67 @@ public void shouldApplyInputMappings() {
...
+            .withVariables(Map.of("x", 1))
+            .create();
+
+    // then
+    final var childInstance = getChildInstanceOf(processInstanceKey);
+
+    assertThat(
+            RecordingExporter.variableRecords()
+                .withProcessInstanceKey(childInstance.getProcessInstanceKey())
+                .limit(2))
```
Comment (remcowesterhoud) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java:307]: 🔧 We limit for 2, but there's only 1 variable record written for this process instance. As a result the test takes >5 seconds to execute. We should limit it to 1 instead.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java [hunk 2]
```diff
@@ -279,6 +279,67 @@ public void shouldApplyInputMappings() {
...
+        .extracting(Record::getValue)
+        .extracting(v -> tuple(v.getName(), v.getValue()))
+        .contains(tuple("y", "1"))
+        .doesNotContain(tuple("x", "1"));
```
Comment (remcowesterhoud) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java:311]:
```suggestion
        .containsExactly(tuple("y", "1"));
```

🙃 Slightly, nitpicky but we can combine this into one. `containsExactly` checks if the result only contains the given element and in order.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java (hunk 1 above)
Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java:307]: If you don't want to limit on 1 record because you might miss more records we'd have to get more creative with the filter. The child instance has a wait-state because of the service task. If we get all records, limit it to the Job.CREATED intent and then get our variables we make sure we get all of the variable created records.

```java
    assertThat(
            RecordingExporter.records()
                .limit(r -> r.getIntent() == JobIntent.CREATED)
                .variableRecords()
                .withIntent(VariableIntent.CREATED)
                .withProcessInstanceKey(childInstance.getProcessInstanceKey()))
        .extracting(Record::getValue)
        .extracting(v -> tuple(v.getName(), v.getValue()))
        .containsExactly(tuple("y", "1"));
```

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java [hunk 3]
```diff
@@ -279,6 +279,67 @@ public void shouldApplyInputMappings() {
...
+    // then
+    final var childInstance = getChildInstanceOf(processInstanceKey);
+
+    assertThat(
+            RecordingExporter.variableRecords()
+                .withProcessInstanceKey(childInstance.getProcessInstanceKey())
+                .limit(2))
+        .extracting(Record::getValue)
+        .extracting(v -> tuple(v.getName(), v.getValue()))
+        .doesNotContain(tuple("x", "1"));
```
Comment (remcowesterhoud) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityTest.java:340]: 🔧 Same problem as with the other assertion. Here we can make it slightly easier as we don't need to extract anything. If we don't find a `Variable.CREATED` it's enough:

```java
    assertThat(
            RecordingExporter.records()
                .limit(r -> r.getIntent() == JobIntent.CREATED)
                .variableRecords()
                .withIntent(VariableIntent.CREATED)
                .withProcessInstanceKey(childInstance.getProcessInstanceKey()))
        .isEmpty();
```

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]
Thanks @romansmirnov! I have some minor comments on your tests, everything else looks great 🚀 

❌  I would like to see a testcase where you set `zeebePropagateAllParentVariables` to `true` explicitly. These cases are now only covered implicitly using the default value in other test cases.

**Comment by romansmirnov** [comment]
@remcowesterhoud, thank you for your feedback. I have made the adjustments as requested.

> Will you also collab with the Modeler team to add support for this?

**Review by remcowesterhoud — APPROVED** [review]
Thanks @romansmirnov 🙇 

bors merge
