### PR TITLE
Update ES client to 8.16.4 to fix ES index template update issues [8.7 to 8.8]

### LINKED ISSUE #29132: Camunda Exporter index update blocked by serialization issues
## Description

> [!Important]
> 
> This is currently blocking the update to 8.8

During migration testing, we ran into issues with Elasticsearch de-/serialization of indices and their settings. 

```
11:14:40.477 [Broker-0] [Exporter-1] [zb-fs-workers-0] ERROR io.camunda.zeebe.broker.exporter - Failed to open exporter 'CamundaExporter'. Retrying...
io.camunda.exporter.exceptions.ElasticsearchExporterException: Failed retrieving mappings from index/index templates with pattern [*]

    [...]

Caused by: co.elastic.clients.transport.TransportException: node: http://localhost:35257/, status: 200, [es/indices.get_index_template] Failed to decode response

    [...]


Caused by: co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch._types.analysis.Normalizer: Property 'type' not found (JSON path: index_templates[60].index_template.template.settings.index.analysis.normalizer.case_insensitive) (line no=1, column no=126745, offset=-1)

    [...]

11:14:40.496 [Broker-0] [Exporter-1] [zb-fs-workers-0] WARN  io.camunda.zeebe.broker.exporter.CamundaExporter - Error on exporting record with key 2251799813685249
java.lang.NullPointerException: Cannot invoke "io.camunda.exporter.store.ExporterBatchWriter.getBatchSize()" because "this.writer" is null

    [...]

```

A related bug was fixed in ES https://github.com/elastic/elasticsearch-java/issues/696

This was previously encountered here:

  * https://github.com/camunda/camunda/pull/26707
  * https://github.com/camunda/camunda/issues/28111

This was tried to fix with:

 * https://github.com/camunda/camunda/pull/28567
 * https://github.com/camunda/camunda/pull/26707
 * https://github.com/camunda/camunda/pull/28585

## Possible solutions:

1. We can update to a higher minor ES client version
2. We can remove the custom type from the Listview
3. We can somehow update this index more reliably (recreation wouldn't be safe enough as with race conditions archiver could create indices without an template)

## Regression test:

 * There exists an 8.7 schema in ES
 * We can update to 8.8, and the CamundaExporter is able to update the schema, if necessary
 * Exporting should be possible afterwards in updated schema

I wrote an example test case:

```java
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.it.migration;

import static org.assertj.core.api.Assertions.assertThat;

import com.github.dockerjava.api.command.CreateContainerCmd;
import io.camunda.client.CamundaClient;
import io.camunda.client.api.search.response.ProcessDefinition;
import io.camunda.client.api.search.response.SearchQueryResponse;
import io.camunda.qa.util.multidb.ElasticOpenSearchSetupHelper;
import io.camunda.qa.util.multidb.MultiDbConfigurator;
import io.camunda.webapps.schema.descriptors.IndexDescriptors;
import io.camunda.zeebe.model.bpmn.Bpmn;
import io.camunda.zeebe.qa.util.cluster.TestStandaloneBroker;
import io.camunda.zeebe.test.util.testcontainers.TestSearchContainers;
import java.time.Duration;
import org.awaitility.Awaitility;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.Network;
import org.testcontainers.containers.output.Slf4jLogConsumer;
import org.testcontainers.elasticsearch.ElasticsearchContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
public class ElasticsearchUpdateRegressionTest {

  private static final Logger LOGGER =
      LoggerFactory.getLogger(ElasticsearchUpdateRegressionTest.class);

  private static final Network NETWORK = Network.newNetwork();
  private static final String ELASTIC_ALIAS = "elasticsearch";

  @Container
  public static final ElasticsearchContainer elasticsearchContainer =
      TestSearchContainers.createDefeaultElasticsearchContainer()
          .withNetwork(NETWORK)
          .withNetworkAliases(ELASTIC_ALIAS)
          .withStartupTimeout(Duration.ofMinutes(5)); // can be slow in CI

  @BeforeAll
  public static void setup() {
    final var esUrl = String.format("http://%s:%d", ELASTIC_ALIAS, 9200);
    final GenericContainer<?> schemaManagerContainer =
        new GenericContainer<>("camunda/zeebe:8.7.0-SNAPSHOT")
            .withCreateContainerCmdModifier(
                (final CreateContainerCmd cmd) -> cmd.withEntrypoint("/usr/local/zeebe/bin/schema"))
            .withNetwork(NETWORK)
            .withNetworkAliases("camunda")
            .withEnv("CAMUNDA_DATABASE_URL", esUrl)
            .withEnv(
                "ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME",
                "io.camunda.zeebe.exporter.ElasticsearchExporter")
            .withEnv("CAMUNDA_OPERATE_ELASTICSEARCH_URL", esUrl)
            .withEnv("CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL", esUrl)
            .withEnv("CAMUNDA_TASKLIST_ELASTICSEARCH_URL", esUrl)
            .withEnv("CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL", esUrl)
            .withEnv("ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL", esUrl);

    schemaManagerContainer.start();
    schemaManagerContainer.followOutput(new Slf4jLogConsumer(LOGGER));
  }

  @Test
  public void shouldBeAbleToUpdateAndExport() {
    // given
    final String httpHostAddress = "http://" + elasticsearchContainer.getHttpHostAddress();
    final var expectedDescriptors = new IndexDescriptors("", true).all();
    final var setupHelper = new ElasticOpenSearchSetupHelper(httpHostAddress, expectedDescriptors);

    Awaitility.await("Await schema readiness")
        .timeout(Duration.ofMinutes(1))
        .pollInterval(Duration.ofMillis(500))
        .until(() -> setupHelper.validateSchemaCreation(""));
    final TestStandaloneBroker testStandaloneBroker = new TestStandaloneBroker();
    final MultiDbConfigurator multiDbConfigurator = new MultiDbConfigurator(testStandaloneBroker);
    multiDbConfigurator.configureElasticsearchSupport(httpHostAddress, "");

    // when
    testStandaloneBroker.start();
    final CamundaClient camundaClient = testStandaloneBroker.newClientBuilder().build();
    camundaClient
        .newDeployResourceCommand()
        .addProcessModel(
            Bpmn.createExecutableProcess("test").startEvent().endEvent().done(), "test.bpmn")
        .send()
        .join();

    // then
    Awaitility.await("wait for processes")
        .untilAsserted(
            () -> {
              final SearchQueryResponse<ProcessDefinition> searchQueryResponse =
                  camundaClient.newProcessDefinitionQuery().send().join();
              assertThat(searchQueryResponse.items().size()).isNotZero();
            });
  }
}
```

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

We dectected https://github.com/camunda/camunda/issues/29132 during migration testing

> **TL;DR:** The problem lies in the ES java client version we are using, not being able to deserialize old index templates with normalizers defined and missing a type field.

**Details (incl. root cause):**

- We have an index template (operate-list-view), where we define a normalizer
- In the past, the template or the normalizer configuration didn't need any type property (it was optional)
- This means the type property is not set in the old templates (8.7)
- Previously, we have used an old RestHighLevel client; with the CamundaExporter, we migrated to the ES java client
- The newer ES java client (8.13.x) we use [is failing if the type property is not set](https://github.com/elastic/elasticsearch-java/issues/696), as it uses a[ default null - this causes to fail the deserialization](https://github.com/elastic/elasticsearch-java/blob/8.13/java-client/src/main/java/co/elastic/clients/elasticsearch/_types/analysis/Normalizer.java#L213)
- This is a bug in the client and was fixed here [elastic/elasticsearch-java@cb0bb35#diff-9a776587666f90cd3feecd30d7bddaf145ea88c109db5a8fa70fa4b979c2fea1R213](https://github.com/elastic/elasticsearch-java/commit/cb0bb35da862feefa0617c65b8c5bde75b79c681#diff-9a776587666f90cd3feecd30d7bddaf145ea88c109db5a8fa70fa4b979c2fea1R213)
- This fix is available in 8.15+ ES clients

## What the PR does

1. Add a regression test that:
    1. creates the schema in 8.7
    2. Updates to 8.8
    3. Exports data and awaits availability of data
    4. :x: This fails with old client
2. Update the ES export version to 8.16.4, see related discussion [here](https://camunda.slack.com/archives/C05QBRGMA9F/p1741170277082429?thread_ts=1741099983.818569&cid=C05QBRGMA9F)
  1. Migrate all ES Client API broken usage in search clients, exporter, migration app and tests
      1. I time boxed the migration of Optimize, but realized it will be a lot of work, see related commit https://github.com/camunda/camunda/pull/29167/commits/90e9b915572cf9213075b8251aa6ba4638586d63
      2. I stepped back, reverted the Optimize changes https://github.com/camunda/camunda/pull/29167/commits/b5aa25103ff19bc366f98357e576e642c85fc988, but kept them for transparency
      3. I pinned Optimize to 8.13.4 ES version - 79aedb4c09f9cb9844d08b5c757110f05502ff8f 62a080a9d546a6de0f6e66d229e19bf596a61c50
      4. \cc @RomanJRW 
5. ✔️ Test is passing with newest client version
6. I had to bump the ES container version https://github.com/camunda/camunda/pull/29167/commits/9d50a99fffc4821d3c697b5af6064d31a13d8c5b, as several tests were failing with using an older ES version and newer client, see https://github.com/camunda/camunda/pull/29167#issuecomment-2700966096
 

## Related issues

See https://camunda.slack.com/archives/C05QBRGMA9F/p1741099983818569

closes https://github.com/camunda/camunda/issues/29132
related https://github.com/camunda/product-hub/issues/2700

### CODE REVIEW

**Comment by ChrisKujawa** [comment]
Looking at the failing tests:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tasklistElasticsearchClient' defined in class path resource [io/camunda/tasklist/es/ElasticsearchConnector.class]: Failed to instantiate [co.elastic.clients.elasticsearch.ElasticsearchClient]: Factory method 'tasklistElasticsearchClient' threw exception with message: Couldn't connect to Elasticsearch. Abort.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:489)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1361)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:346)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1606)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1552)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:785)
	... 48 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [co.elastic.clients.elasticsearch.ElasticsearchClient]: Factory method 'tasklistElasticsearchClient' threw exception with message: Couldn't connect to Elasticsearch. Abort.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:199)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiateWithFactoryMethod(SimpleInstantiationStrategy.java:88)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:168)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 60 more
Caused by: io.camunda.tasklist.exceptions.TasklistRuntimeException: Couldn't connect to Elasticsearch. Abort.
	at io.camunda.tasklist.es.ElasticsearchConnector.checkHealth(ElasticsearchConnector.java:313)
	at io.camunda.tasklist.es.ElasticsearchConnector.tasklistElasticsearchClient(ElasticsearchConnector.java:135)
	at io.camunda.tasklist.es.ElasticsearchConnector$$SpringCGLIB$$0.CGLIB$tasklistElasticsearchClient$2(<generated>)
	at io.camunda.tasklist.es.ElasticsearchConnector$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:372)
	at io.camunda.tasklist.es.ElasticsearchConnector$$SpringCGLIB$$0.tasklistElasticsearchClient(<generated>)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:171)
	... 63 more
Caused by: co.elastic.clients.transport.TransportException: node: http://localhost:32771/, status: 200, [es/cluster.health] Failed to decode response
	at co.elastic.clients.transport.ElasticsearchTransportBase.decodeTransportResponse(ElasticsearchTransportBase.java:409)
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:367)
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:148)
	at co.elastic.clients.elasticsearch.cluster.ElasticsearchClusterClient.health(ElasticsearchClusterClient.java:439)
	at io.camunda.tasklist.es.ElasticsearchConnector.lambda$checkHealth$4(ElasticsearchConnector.java:306)
	at io.camunda.tasklist.util.RetryOperation.retry(RetryOperation.java:60)
	at io.camunda.tasklist.es.ElasticsearchConnector.checkHealth(ElasticsearchConnector.java:311)
	... 71 more
Caused by: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'HealthResponse.unassignedPrimaryShards'
	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76)
	at co.elastic.clients.elasticsearch.cluster.health.HealthResponseBody.<init>(HealthResponseBody.java:132)
	at co.elastic.clients.elasticsearch.cluster.HealthResponse.<init>(HealthResponse.java:59)
	at co.elastic.clients.elasticsearch.cluster.HealthResponse.<init>(HealthResponse.java:55)
	at co.elastic.clients.elasticsearch.cluster.HealthResponse$Builder.build(HealthResponse.java:90)
	at co.elastic.clients.elasticsearch.cluster.HealthResponse$Builder.build(HealthResponse.java:73)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:80)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.ElasticsearchTransportBase.decodeTransportResponse(ElasticsearchTransportBase.java:404)
	... 77 more
```

It looks like the newer client is not compatible with older ES 8.x versions.

**Comment by ChrisKujawa** [comment]
The failing docker tests still experience this issue

```
2025-03-05 14:34:31.825 [] [main] [] WARN 
      io.camunda.tasklist.util.RetryOperation - Retry Operation Connect to Elasticsearch cluster [elasticsearch] at http://elasticsearch:9200 failed: node: http://elasticsearch:9200/, status: 200, [es/cluster.health] Failed to decode response
co.elastic.clients.transport.TransportException: node: http://elasticsearch:9200/, status: 200, [es/cluster.health] Failed to decode response
	at co.elastic.clients.transport.ElasticsearchTransportBase.decodeTransportResponse(ElasticsearchTransportBase.java:409) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:367) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:148) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.elasticsearch.cluster.ElasticsearchClusterClient.health(ElasticsearchClusterClient.java:439) ~[elasticsearch-java-8.16.4.jar:?]
	at io.camunda.tasklist.es.ElasticsearchConnector.lambda$checkHealth$4(ElasticsearchConnector.java:306) ~[tasklist-common-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.tasklist.util.RetryOperation.retry(RetryOperation.java:60) ~[tasklist-common-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.tasklist.es.ElasticsearchConnector.checkHealth(ElasticsearchConnector.java:311) ~[tasklist-common-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.tasklist.es.ElasticsearchConnector.tasklistElasticsearchClient(ElasticsearchConnector.java:135) ~[tasklist-common-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.tasklist.es.ElasticsearchConnector$$SpringCGLIB$$0.CGLIB$tasklistElasticsearchClient$9(<generated>) ~[tasklist-common-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.tasklist.es.ElasticsearchConnector$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[tasklist-common-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.2.3.jar:6.2.3]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:372) ~[spring-context-6.2.3.jar:6.2.3]
	at io.camunda.tasklist.es.ElasticsearchConnector$$SpringCGLIB$$0.tasklistElasticsearchClient(<generated>) ~[tasklist-common-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiateWithFactoryMethod(SimpleInstantiationStrategy.java:88) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:168) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:489) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1361) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:346) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1606) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1552) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:913) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:240) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1381) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1218) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:346) [spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) [spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) [spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.instantiateSingleton(DefaultListableBeanFactory.java:1155) [spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingleton(DefaultListableBeanFactory.java:1121) [spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:1056) [spring-beans-6.2.3.jar:6.2.3]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:987) [spring-context-6.2.3.jar:6.2.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627) [spring-context-6.2.3.jar:6.2.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) [spring-boot-3.4.3.jar:3.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-3.4.3.jar:3.4.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) [spring-boot-3.4.3.jar:3.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) [spring-boot-3.4.3.jar:3.4.3]
	at io.camunda.application.StandaloneTasklist.main(StandaloneTasklist.java:48) [camunda-zeebe-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
Caused by: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'HealthResponse.unassignedPrimaryShards'
	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.elasticsearch.cluster.health.HealthResponseBody.<init>(HealthResponseBody.java:132) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.elasticsearch.cluster.HealthResponse.<init>(HealthResponse.java:59) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.elasticsearch.cluster.HealthResponse.<init>(HealthResponse.java:55) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.elasticsearch.cluster.HealthResponse$Builder.build(HealthResponse.java:90) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.elasticsearch.cluster.HealthResponse$Builder.build(HealthResponse.java:73) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:80) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.decodeTransportResponse(ElasticsearchTransportBase.java:404) ~[elasticsearch-java-8.16.4.jar:?]
	... 50 more
```

Looks like it is still using an old version of ES 🤔 

```
  841 2025-03-05 14:31:04.258 DEBUG ${sys:PID} --- [           main] o.t.u.ImageNameSubstitutor               : Did not find a substitute image for docker.elastic.co/elasticsearch/elasticsearch:7.17.28 (using image substitutor: Def      aultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor'))
  842 2025-03-05 14:31:04.259 DEBUG ${sys:PID} --- [           main] t.d.e.c.1.28                             : docker.elastic.co/elasticsearch/elasticsearch:7.17.28 is not in image name cache, updating...
  843 2025-03-05 14:31:04.259 DEBUG ${sys:PID} --- [           main] o.t.s.c.g.d.c.c.AbstrDockerCmd           : Cmd: docker.elastic.co/elasticsearch/elasticsearch:7.17.28    

```

File: operate/qa/util/src/main/java/io/camunda/operate/qa/util/TestContainerUtil.java [hunk 1]
```diff
@@ -300,7 +299,9 @@ public void startElasticsearch(final TestContext testContext) {
                 String.format(
                     "%s:%s",
                     DOCKER_ELASTICSEARCH_IMAGE_NAME,
-                    ElasticsearchClient.class.getPackage().getImplementationVersion()))
```
Comment (ChrisKujawa) [inline operate/qa/util/src/main/java/io/camunda/operate/qa/util/TestContainerUtil.java:303]: 🙃 We can't use the old way, as the new client doesn't has the implementation version in its MANIFEST

**Comment by ChrisKujawa** [comment]
@pedesen are the Operate E2E failures expected? https://github.com/camunda/camunda/actions/runs/13693712024/job/38291438076?pr=29167

**Comment by pedesen** [comment]
@ChrisKujawa I'm aware they're failing. I'll do some root-causing tomorrow.

**Comment by ChrisKujawa** [comment]
@ThorbenLindhauer or @sdorokhova can someone support me here regarding the Operate IT

It looks like the `Error:  io.camunda.operate.elasticsearch.DecisionIT` is also failing on main. Regarding `ElasticsearchConnectorIT` I'm not sure. Locally it is green 🤷🏼

**Comment by ThorbenLindhauer** [comment]
Looking at the rootcause of `DecisionIT`, my guess would be an Identity-related PR broke it. Maybe you can report it there? And maybe we can even spot the PR that introduced it.

For the other one, happy to have a call with you. I think it's best if we review it together. Just reach out.

**Comment by grlimacan** [comment]
> @RomanJRW are the Optimize CI failures expected?

Hi @ChrisKujawa , the `[Optimize CI / Upgrade (opensearch) (pull_request)](https://github.com/camunda/camunda/actions/runs/13774270864/job/38519874124?pr=29167)` is also failing on `main`, so yes, it's expected. The E2E tests _should_ be passing, but they are notoriously flaky. So if they always fail this is sth to look at, if they pass sporadically you're good

**Comment by ChrisKujawa** [comment]
I think I did everything I could, with migration of the ES client dependency and adjusting the usage (except for Optimize).


What I see is the following:

1. Operate IT CI [is failing ](https://github.com/camunda/camunda/actions/runs/13787964430/job/38560398351?pr=29167). Similar error we can observe on main. See [slack thread](https://camunda.slack.com/archives/C06UYJMMETZ/p1741686837756839)
2. Operate E2E tests [are failing](https://github.com/camunda/camunda/actions/runs/13787964368/job/38560389326?pr=29167) - also expected see https://github.com/camunda/camunda/pull/29167#issuecomment-2711198975
3. Optimize IT upgrade OpenSearch [is failing](https://github.com/camunda/camunda/actions/runs/13787964440/job/38560415166?pr=29167) - also expected see https://github.com/camunda/camunda/pull/29167#issuecomment-2713614053

With that, I think we can continue and get this merged (after review) to unblock our Migration testing efforts for 8.8 and Elasticsearch https://github.com/camunda/camunda/issues/29132


@ThorbenLindhauer @romansmirnov has someone of you time to review this PR? I can clean up and squash the commits before if necessary. 


_**Side note:** I feel these failing pipelines are a waste of time and resources. It is not clear for people whether they are failing because of changes they made or they were broken before. People like me, not familiar with the CI and tests, have to spent time and effort to understand what they are doing and why they are failing to realize they have been broken before. They bring not really any value, as there is not much confidence we get out of breaking pipelines. People start to ignore them, and they get more broken._

File: migration/process-migration/src/main/java/io/camunda/migration/process/adapter/es/ElasticsearchAdapter.java [hunk 2]
```diff
@@ -90,10 +89,13 @@ public List<ProcessEntity> nextBatch(final String lastMigratedEntity) throws Mig
                 q ->
                     q.range(
                         m ->
-                            m.field(PROCESS_DEFINITION_KEY)
-                                .gt(
-                                    JsonData.of(
-                                        lastMigratedEntity == null ? "" : lastMigratedEntity))))
+                            m.number(
```
Comment (romansmirnov) [inline migration/process-migration/src/main/java/io/camunda/migration/process/adapter/es/ElasticsearchAdapter.java:92]: ❓ Should this be `term()`? Because the process definition key is stored as a keyword in ES.

**Review by romansmirnov — APPROVED** [review]
Just a minor question (see below), but besides that it looks good to me.
