### PR TITLE
Validate duplicated extension elements

### LINKED ISSUE #14040: Unexpected error while transforming resource
**Describe the bug**

Observed the following error in a cluster. We don't have access to the bpmn deployed.

[logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-08-28T13:01:57.241212759Z;endTime=2023-08-28T14:32:27.241Z;pinnedLogId=2023-08-28T12:46:46.780041927Z%2F4s3f1u6v602ghqdj;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22prod-worker-2%22%0Aresource.labels.namespace_name%3D%22fa4cf96b-ed94-45f6-853d-db0f4a394fe1-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.container_name%3D%22zeebe%22%0Atimestamp%3D%222023-08-28T13:01:57.241212759Z%22%0AinsertId%3D%22fp8vvt36ynb2ta9z%22;startTime=2023-08-28T12:32:27.241Z;summaryFields=resource%252Flabels%252Fpod_name,jsonPayload%252Fcontext%252FpartitionId:false:32:beginning?project=camunda-cloud-240911)
 
```
Unexpected error while processing resource 'xxxx.bpmn'
"io.camunda.zeebe.model.bpmn.BpmnModelException: Collection expected to have <1> entry but has <2>
	at io.camunda.zeebe.model.bpmn.impl.QueryImpl.singleResult(QueryImpl.java:82) ~[zeebe-bpmn-model-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.model.bpmn.impl.instance.BaseElementImpl.getSingleExtensionElement(BaseElementImpl.java:110) ~[zeebe-bpmn-model-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transformIoMappings(FlowNodeTransformer.java:57) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:38) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:21) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:118) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$2(BpmnResourceTransformer.java:76) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:69) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:125) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:101) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:90) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:139) ~[zeebe-workflow-engine-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:352) ~[zeebe-stream-platform-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.10.jar:8.2.10]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:205) [zeebe-scheduler-8.2.10.jar:8.2.10]
```

**Expected behavior**

1. Invalid resources should be detected during validation.
2. This should not be logged as error, as it is most likely a user error. It is enough to reject the command with proper error message.

**Environment:**
- Zeebe Version: 8.2.10

Sample support case: https://jira.camunda.com/browse/SUPPORT-26513

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

A parameterised test is added for each validation.

## Related issues

closes #14040

### CODE REVIEW

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/ZeebeDesignTimeValidators.java [hunk 1]
```diff
@@ -149,6 +149,7 @@ public final class ZeebeDesignTimeValidators {
         ZeebeElementValidator.verifyThat(ZeebePriorityDefinition.class)
             .hasNonEmptyAttribute(
                 ZeebePriorityDefinition::getPriority, ZeebeConstants.ATTRIBUTE_PRIORITY));
+    validators.addAll(ExtensionElementDuplicationValidators.VALIDATORS);
```
Comment (georgios-goulos) [inline zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/ZeebeDesignTimeValidators.java:152]: So this is added to the validators configured in the class `ZeebeDesignTimeValidators`. 

1. Can you please explain to me what we mean by "design time" here?
2. Any chance we need to perform this validation during another step?

**Comment by georgios-goulos** [comment]
How likely is it that we will add support for more such extension elements in the future?

File: zeebe/engine/src/test/resources/processes/invalid_user_task_extensions.bpmn [hunk 2]
```diff
@@ -0,0 +1,43 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:modeler="http://camunda.org/schema/modeler/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Web Modeler" exporterVersion="edcd342" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.7.0">
+  <bpmn:process id="Process_1tk79f8" name="invalid_user_task_extension" isExecutable="true">
+    <bpmn:startEvent id="StartEvent_1">
+      <bpmn:outgoing>Flow_1o8eny3</bpmn:outgoing>
+    </bpmn:startEvent>
+    <bpmn:sequenceFlow id="Flow_1o8eny3" sourceRef="StartEvent_1" targetRef="Activity_1cq8igv" />
+    <bpmn:userTask id="Activity_1cq8igv" name="invalid user task">
+      <bpmn:extensionElements>
+        <zeebe:userTask />
```
Comment (georgios-goulos) [inline zeebe/engine/src/test/resources/processes/invalid_user_task_extensions.bpmn:10]: Perhaps one thing we could do is to have a parameterised test the dynamically adds a different extension element each time and asserts that validation was applied. Don't know how easy that would be though

File: zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/ZeebeDesignTimeValidators.java (hunk 1 above)
Comment (berkaycanbc) [reply zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/ZeebeDesignTimeValidators.java:152]: @georgios-goulos 
> Can you please explain to me what we mean by "design time" here?

Design time validators: validates the properties that are related to BPMN design elements. For example, end events cannot have outgoing sequence flows.

Runtime validators: validations on the BPMN properties that will be used during runtime. Mainly they are validations for expressions. If an expression needs to be evaluated to array of values, we check if expression is valid. E.g. if it is static expression, it should already be evaluated to an array of values.

I agree, the naming here is a bit misleading because runtime validators usually referred to something that is validated during runtime. However, in this case they are both validated before deploying the XML.

> Any chance we need to perform this validation during another step?

We collect errors from all validations and return to user. Therefore, changing its step shouldn't make a difference.

**Comment by berkaycanbc** [comment]
@georgios-goulos 
> How likely is it that we will add support for more such extension elements in the future?

We cover most of the BPMN elements ([BPMN coverage](https://docs.camunda.io/docs/components/modeler/bpmn/bpmn-coverage/)) but there are obviously some to come (e.g. conditional events). But this is a valid concern. I will check if we can force adding a validator for newly added elements which must be defined only once.

File: zeebe/engine/src/test/resources/processes/invalid_user_task_extensions.bpmn (hunk 2 above)
Comment (berkaycanbc) [reply zeebe/engine/src/test/resources/processes/invalid_user_task_extensions.bpmn]: Hmm, we need to find a way to create a different XML for every extension element. Never seen that done before. I can check if that is possible. But if we find a way to force adding a validation for new element types, I expect it should be enough to make sure we have validations in place.

**Comment by berkaycanbc** [comment]
@georgios-goulos I was able to further refactor and add parametrised tests. 🎉 Please take another look 👀

**Comment by berkaycanbc** [comment]
@georgios-goulos I've also add the test for forcing developers to add parameterised test once they use `.getSingleExtensionElement()` in a transformer. But then there are some transformers retrieving single extension element but requires these elements to exist (so not optional). There is another validator for them `ExtensionElementsValidator`. That makes it tricky to force adding test for each element retrieved through `.getSingleExtensionElement()` because sometimes it is required and there is another validator for that one. So, I skip adding a guard for that one as part of this PR.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/DuplicateExtensionElementDeploymentRejectionTest.java [hunk 3]
```diff
@@ -0,0 +1,379 @@
+/*
+ * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
+ * one or more contributor license agreements. See the NOTICE file distributed
+ * with this work for additional information regarding copyright ownership.
+ * Licensed under the Camunda License 1.0. You may not use this file
+ * except in compliance with the Camunda License 1.0.
+ */
```
Comment (georgios-goulos) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/DuplicateExtensionElementDeploymentRejectionTest.java:7]: Was this auto-generated? I see it's different in the other new files in this PR. It could be because of different directories but I thought it's worth bringing it up

Comment (berkaycanbc) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/DuplicateExtensionElementDeploymentRejectionTest.java:7]: @georgios-goulos yes. In the zeebe-bpmn-model module (where validator classes located), there is a specific configuration:

```
<properties>
  …
  <license.header>com/mycila/maven/plugin/license/templates/APACHE-2.txt</license.header>
</properties>
```


which tells the plugin to pull in the standard Apache 2.0 boilerplate for all source files.

However, zeebe-workflow-engine module (where this PR's tests are located), we do not override that setting and use the default Camunda-1.0 header.

**Review by georgios-goulos — APPROVED** [review]

**Comment by berkaycanbc** [comment]
I should've squashed changes in one commit for backporting. 🤦 I will create an 8.7 version and backport it from there.
