### PR TITLE
Fix job backoff restore migration

### LINKED ISSUE #15954: Job backoff migration causes duplicate incidents
**Describe the bug**

With https://github.com/camunda/zeebe/issues/14329 we fixed an issue that would cause failed jobs with `retries > 0` to not be re-activated after a migration, i.e. the jobs aren't placed in the `JOB_BACKOFF` column family. 

However, the fix doesn't check if a failed job has `retries > 0` or if it already has an incident, which wouldn't make it activatable.

The above leads to a job with an incident being made activatable. When this type of job is processed, and failed again, it raises a second incident. If Zeebe has the `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS` env var set to `true`, then a consistency violation error will be thrown by RocksDB, crashing the partition.

**To Reproduce**

1. Use Zeebe `8.1.21`, `8.2.19`, `8.3.4`, or `8.4.0`.
2. Set the `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS` env var to `true`.
3. Set the `retries` of a job to `0` and `fail` it.
4. Migrate to the next patch version of Zeebe (`8.1.22`, `8.2.20`, `8.3.5`)
5. Activate the same job (from [3]) and fail it again.
6. An error will be thrown that an entry already exists in the `INCIDENT_JOBS` column family, and the partition will crash.

**Expected behavior**

Jobs with incidents are not made activatable after a migration.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
10:18:09.846 [Broker-0] [zb-actors-1] [StreamProcessor-1] ERROR io.camunda.zeebe.logstreams - Actor StreamProcessor-1 failed in phase STARTED.
io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{2251799819040844}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda/0x00007f751880b920@57433d1d] in ColumnFamily INCIDENT_JOBS already exists
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyDoesNotExist(TransactionalColumnFamily.java:297) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$insert$0(TransactionalColumnFamily.java:81) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:325) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:324) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.insert(TransactionalColumnFamily.java:76) ~[classes/:?]
	at io.camunda.zeebe.engine.state.instance.DbIncidentState.createIncident(DbIncidentState.java:85) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.IncidentCreatedApplier.applyState(IncidentCreatedApplier.java:30) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.IncidentCreatedApplier.applyState(IncidentCreatedApplier.java:17) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:335) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:56) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:42) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.job.JobFailProcessor.raiseIncident(JobFailProcessor.java:173) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.job.JobFailProcessor.failJob(JobFailProcessor.java:135) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.job.JobFailProcessor.lambda$processRecord$0(JobFailProcessor.java:86) ~[classes/:?]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.job.JobFailProcessor.processRecord(JobFailProcessor.java:85) ~[classes/:?]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:356) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:272) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:272) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:231) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:207) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [classes/:?]
10:18:09.857 [Broker-0] [zb-actors-0] [ZeebePartition-1] ERROR io.camunda.zeebe.broker.system - StreamProcessor-1 failed, marking it as dead: StreamProcessor-1{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{2251799819040844}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda/0x00007f751880b920@57433d1d] in ColumnFamily INCIDENT_JOBS already exists, cause=null]}
```

</p>
</details>

**Environment:**
- OS:  Camudna SaaS and SM
- Zeebe Version:  `8.1.22`, `8.2.20`, `8.3.5`, `8.4.0`
- Configuration:  `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS=true`

**Workaround**
* Setting `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS=false` will avoid the issue from happening until a fix is provided.

**Additional context:**
* The bug can also be reproduced by starting a `StandaloneBroker` (on the `stable/8.3` branch) with [this (internal) partition data](https://drive.google.com/file/d/19SDLOKRu6jwxDeG05CNHrIL1wYZYL5ft/view?usp=sharing).
* The problematic code is [here](https://github.com/camunda/zeebe/blob/86db453f1aef24e2fb02e7a739dda12a12b1997c/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java#L288) (on branch `main`/`8.4`) since we don't exclude jobs with incidents/`retries < 1`.
* [Support case](https://jira.camunda.com/browse/SUPPORT-20055)
* [Support case](https://jira.camunda.com/browse/SUPPORT-20113)

### PR DESCRIPTION
**Pull request by nicpuppa**
## Related issues

closes #15954 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java [hunk 1]
```diff
@@ -534,4 +534,25 @@ private Set<Long> getBackoffJobKey() {
...
+    final var type = job.getTypeBuffer();
+    final var tenantId = job.getTenantId();
+    EnsureUtil.ensureNotNullOrEmpty("type", job.getTypeBuffer());
+    EnsureUtil.ensureNotNullOrEmpty("tenantId", job.getTenantId());
+
+    jobTypeKey.wrapBuffer(type);
+    jobKey.wrapLong(key);
+    tenantIdKey.wrapString(tenantId);
+
+    return activatableColumnFamily.get(tenantAwareTypeJobKey) != null;
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:556]: :question: @nicpuppa why are we checking if the job is activatable?

If the job is already in the `activatableColumnFamily` that means that it hasn't been `FAILED`, and it shouldn't be in the `backoffColumnFamily`.

So if we can find the job in the `activatableColumnFamily`, then we shouldn't put it in the `backoffColumnFamily`.

Am I missing some steps in my logic?

Comment (nicpuppa) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:556]: Probably I misunderstood, but in the `backoffColumnFamily` you should find only activatable jobs. When a job is failed, and have retries, is still available in the `activatableColumnFamily`

Comment (koevskinikola) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:556]: There are 3 scenarios once a Job is `FAILED` (see code [here](https://github.com/camunda/zeebe/blob/86db453f1aef24e2fb02e7a739dda12a12b1997c/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java#L193-L205)):
1. If `retires <= 0`
   - `JobState` is set to `FAILED`.
   - `Job` is removed from the `activatableColumnFamily`
   - Incident is added for this Job.
2. If `retries > 0` and `retryBackoff > 0`
   - `JobState` is set to `FAILED`.
   - `Job` was already removed from the `activatableColumnFamily` [when the job was activated](https://github.com/camunda/zeebe/blob/86db453f1aef24e2fb02e7a739dda12a12b1997c/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java#L132). So it's currently not there.
   - `Job` is added to the `backoffColumnFamily` since we want to delay the next job activation until some time has passed.
3. If `retries > 0` and `retryBackoff <= 0`
   - `JobState` is set to `ACTIVATABLE`.
   - `Job` is added to the `activatableColumnFamily` since we want it to be immediately available for activation.

For this migration, we need to fix case [2], so:
1. A job should have `retries > 0` :heavy_check_mark: 
2. A job should have `recurringTime > -1` :heavy_check_mark: 
3. A job is not activatable, i.e. `!isJobActivatable(key, job) :x:

Since we already do [`getFailedJobKeys()`](https://github.com/camunda/zeebe/pull/16047/files#diff-ef73a79bfa12b3c9cc862cff7aefcdc63b8cb9efaa732c6de49b842915017b20R281), i.e. [jobs in state `FAILED`](https://github.com/camunda/zeebe/pull/16047/files#diff-ef73a79bfa12b3c9cc862cff7aefcdc63b8cb9efaa732c6de49b842915017b20R524), finding the job in the `activatableColumnFamily` would indicate a bug since a job in that CF must be in the `ACTIVATABLE` state.

Comment (koevskinikola) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:556]: And I think we might have another bug, since the `JobFailProcessor` allows to `FAIL` an `ACTIVATABLE` job ([src](https://github.com/camunda/zeebe/blob/2e22958504385ec243ffd4e932c2283b3ad5104f/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobFailProcessor.java#L72)).

When an `ACTIVATABLE` job is failed **with backoff**, it isn't removed from the `activatableColumnFamily` when it's marked as `FAILED` and placed in the `backoffColumnFamily`. This would make it possible for a Job to be activated earlier than the `recurringTime`. This defeats the purpose of `backoff`.

Comment (nicpuppa) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:556]: Oh thanks for clarify this, the current behaviour mislead me 👍

**Comment by nicpuppa** [comment]
Hey @koevskinikola, thanks for the review and the clarification. I changed the implementation following your comments, please have another look 👀

**Comment by nicpuppa** [comment]
If we fail a job with `retries > 0`, the current implementation doesn't work @koevskinikola. I think we should change the behaviour of the `fail` method

**Comment by koevskinikola** [comment]
Just to document the decision that we made:

For this bug fix, we don't have to check if a job with a `State.FAILED` is in the `activatableColumnFamily` when performing the checks in the `restoreBackoff()` method. 

If a job is in the `activatableColumnFamily`, then it should be in `State.ACTIVATABLE`. This is a separate bug that I described [here](https://github.com/camunda/zeebe/pull/16047#discussion_r1464932462), and we need to handle it separately.

File: engine/src/test/java/io/camunda/zeebe/engine/state/migration/JobBackoffRestoreMigrationTest.java [hunk 2]
```diff
@@ -135,6 +135,32 @@ public void shouldDoNothingIfFailedJobsAreTheSameAsBackoff() {
...
+  @Test
+  public void shouldNotRestoreJobWithoutRetries() {
+    // given
+    final MutableJobState jobState = processingState.getJobState();
+    final JobRecord record = createJobRecord(1000);
+    jobState.create(jobKey.getValue(), record);
+    jobState.fail(jobKey.getValue(), record);
+    backoffKey.wrapLong(record.getRecurringTime());
+    backoffColumnFamily.deleteExisting(backoffJobKey);
+    jobState.updateJobRetries(jobKey.getValue(), 0);
```
Comment (koevskinikola) [inline engine/src/test/java/io/camunda/zeebe/engine/state/migration/JobBackoffRestoreMigrationTest.java:147]: :upside_down_face: If the `retires` are already set to `0` before the job is `failed` you won't need to remove it from the `backoffColumnFamily`. This would actually simulate the real-world behavior.

The current test still reproduces the bug in our code, but in a real-world scenario (if the job isn't removed from the `backoffColumnFamily`) it would still be valid, and the job would be made activatable as expected.

**Review by koevskinikola — APPROVED** [review]
Looks good now @nicpuppa :tada: 

There are some CodeQL complaints and a small nit-pick about the test case, but this doesn't impact the correctness of the fix, so I'm approving the PR.

File: engine/src/test/java/io/camunda/zeebe/engine/state/migration/JobBackoffRestoreMigrationTest.java (hunk 2 above)
Comment (nicpuppa) [reply engine/src/test/java/io/camunda/zeebe/engine/state/migration/JobBackoffRestoreMigrationTest.java:147]: Nice one 💪
