### PR TITLE
fix: prevent modifications with orphaned variables

### LINKED ISSUE #45268: Operate UI allows applying modification with only variable changes, returns 'Modification failed' error
### 

### 

### 

### 

### Description

When the user adds or cancels a token (or performs any general action), the Add Variable button becomes visible, allowing the user to add variables. After clicking Modification, the user can remove the Add Token or Move Token actions from the modification table and keep only the Add Variable action. In this scenario, the user is able to apply the changes even though the modification now contains only variable changes. After clicking Apply, operate returns a “Modification failed” error. This behavior is confusing, as the UI allows the user to proceed with applying the modification, but the operation ultimately fails.

### Steps to reproduce

1. Perform an action on a process instance (e.g., add or cancel a token) so that the Add Variable button becomes visible.
2. Click Modification.
3. Remove the Add Token or Move Token actions, keep only the Add Variable action in the modification table.
4. Click Apply.
5. Observe that the operation fails with a “Modification failed” error, although the UI allowed proceeding.

### Current behavior

The UI allows the user to submit a modification that contains only variable changes. Upon submission, Operate returns a “Modification failed” error, resulting in confusing UX.

### Expected behavior

The UI should prevent the user from applying a modification if only variable changes are present and such modifications are not supported, or it should provide a warning or disable the apply button in this scenario to prevent user confusion and errors.

### Workaround

https://github.com/user-attachments/assets/6cce114d-658d-4180-824a-fb7da5f861dc

### Environment

SaaS

### Version

8.9. Snapshot 

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by christoph-fricke**
## Description

This PR adds an error message and prevents users from applying a modification when it contains variable modifications that cannot be scoped to a token modification. These variable modifications are "considered" orphaned as they cannot be mapped into the payload for the C8 API. 

## Checklist

- [X] The solution of showing an error message is up for discussion and [awaits a decision from product and design](https://github.com/camunda/camunda/issues/45268#issuecomment-3915560038).

## Related issues

closes #45268

### CODE REVIEW

File: operate/client/src/App/ProcessInstance/ModificationSummaryModal/Messages/OrphanedVariablesError.tsx [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+      hideCloseButton
+      lowContrast
+      title="Invalid modification plan"
+      children={
+        <Text>
+          Some planned variable modifications cannot be applied. They must be
+          scoped to elements with a pending ADD or MOVE token modification. For
+          global variable modifications (scoped to the process instance), at
+          least one ADD or MOVE modification must be planned.
+        </Text>
```
Comment (christoph-fricke) [inline operate/client/src/App/ProcessInstance/ModificationSummaryModal/Messages/OrphanedVariablesError.tsx:24]: Have a look at this text (preview [here](https://github.com/camunda/camunda/issues/45268#issuecomment-3915560038)). Does it make sense. Is the wording correct?

Does the wording "token modification" work? It is used in the [docs](https://docs.camunda.io/docs/next/components/operate/userguide/process-instance-modification/#unsupported-modifications) as well, but listed as flow-node modifications in the table below.

File: operate/client/src/App/ProcessInstance/ModificationSummaryModal/index.tsx
Comment (christoph-fricke) [inline operate/client/src/App/ProcessInstance/ModificationSummaryModal/index.tsx:1]: This change diff looks more complicated than it actually is... -.-

I switched the existing early return to check `processInstance === undefined` as well, which made the additional check in the main return obsolete. Inside the JSX, I only added L.186 `{hasOrphanedVariables && <OrphanedVariablesError />}`. Hint: VS Code displays a way cleaner diff.

File: operate/client/src/App/ProcessInstance/ModificationSummaryModal/Messages/OrphanedVariablesError.tsx (hunk 1 above)
Comment (juliasaienko) [reply operate/client/src/App/ProcessInstance/ModificationSummaryModal/Messages/OrphanedVariablesError.tsx:24]: > Does the wording "token modification" work?

I think its fine, the minor note I have on it:  the terms "ADD or MOVE token modification"(second sentence) and "ADD or MOVE modification"(last sentence) are slightly inconsistent - the last sentence drops "token".

**Review by juliasaienko — APPROVED** [review]
