### PR TITLE
fix(engine): cleanup orphaned job timeouts and backoffs on migration

### LINKED ISSUE #13881: Upgrading leaves deadline entries without jobs
**Describe the bug**

Upgrading a Zeebe cluster to a new version that includes fixes for https://github.com/camunda/zeebe/issues/12797 and https://github.com/camunda/zeebe/issues/13041, entries in the job deadline column family might be leaked, causing repeated error logs that a corresponding job cannot be found.
The cause is a change in behavior where we now expect no duplicate deadline entries and don't clean up duplicated or orphaned entries. 

**To Reproduce**

Use 8.2.8, force the creation of duplicated deadline entries (probably happens with a long processing queue) and then upgrade to 8.2.9 or later.

**Expected behavior**

A migration cleans up orphaned entries so that they are removed from the state and do not cause error logs forever.

**Environment:**
Zeebe <=8.2.8 upgrades to > 8.2.8
Zeebe <= 8.1.? upgrades to > 8.1.?
Zeebe <= 8.0.? upgrades to > 8.0.?

### PR DESCRIPTION
**Pull request by lenaschoenburg**
After an update from a previous version, both backoff and deadline column families might contain entries without a corresponding job or multiple entries for a single job. 
Before fixing #12797 and #13041, these were cleaned up ad-hoc whenever they were found. This is no longer the case because we now prevent the creation of duplicated entries and always cleanup properly.

This adds two necessary migrations that remove orphaned entries that were left by a previous version. The migrations run once and walk through all deadline and backoff entries, removing those without a job and duplicates which don't match the current job state.

closes #13881

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java [hunk 1]
```diff
@@ -206,6 +206,34 @@ public JobRecord updateJobRetries(final long jobKey, final int retries) {
...
   }
 
+  @Override
+  public void cleanupTimeoutsWithoutJob() {
+    deadlinesColumnFamily.whileTrue(
+        (key, value) -> {
+          final var jobKey = key.second().inner();
+          final var deadline = key.first().getValue();
+          final var job = jobsColumnFamily.get(jobKey);
+          if (job == null || job.getRecord().getDeadline() != deadline) {
```
Comment (oleschoenburg) [inline engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:216]: :question: I'm not entirely sure if this is safe. Could there be a case where the deadline of this job is not in the deadline column family and we would end up deleting all deadlines for this job?

File: engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java [hunk 2]
```diff
@@ -206,6 +206,34 @@ public JobRecord updateJobRetries(final long jobKey, final int retries) {
...
+  }
+
+  @Override
+  public void cleanupBackoffsWithoutJobs() {
+    backoffColumnFamily.whileTrue(
+        (key, value) -> {
+          final var jobKey = key.second().inner();
+          final var backoff = key.first().getValue();
+          final var job = jobsColumnFamily.get(jobKey);
+          if (job == null || job.getRecord().getRetryBackoff() != backoff) {
```
Comment (oleschoenburg) [inline engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:230]: :question: I'm not entirely sure if this is safe. Could there be a case where the backoff of this job is not in the backoff column family and we would end up deleting all backoffs for this job?

File: engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java (hunk 1 above)
Comment (megglos) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:216]: we need this case as there could be multiple entries from the previous logic and the new logic only deletes one exact entry, right?

Comment (oleschoenburg) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:216]: Yes, exactly.

Comment (oleschoenburg) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:216]: The safest thing to do would be to completely clear the deadline column family and recreate it based on deadlines found for each job.

File: engine/src/main/java/io/camunda/zeebe/engine/state/migration/JobBackoffCleanup.java
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/state/migration/JobBackoffCleanup.java:1]: :wrench: Should we suffix the name of this class with `*Migration`? That way it's clear what the usage is.

File: engine/src/main/java/io/camunda/zeebe/engine/state/migration/JobTimeoutCleanup.java
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/state/migration/JobTimeoutCleanup.java:1]: :wrench: Should we suffix the name of this class with `*Migration`? That way it's clear what the usage is.

File: engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java (hunk 1 above)
Comment (koevskinikola) [reply engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java:216]: AFAIK there isn't a case where an activated job wouldn't have an entry in the deadline column family. Every time a job is activated, its deadline and key are added to the deadline column family.

> The safest thing to do would be to completely clear the deadline column family and recreate it based on deadlines found for each job.

It's safest, but it's probably more expensive since we would be going through all the available jobs instread of the activated jobs subset.

**Review by koevskinikola — CHANGES_REQUESTED** [review]
Nice job @oleschoenburg  :rocket: 

I left some naming-related comments only. Otherwise, the changes look good.

File: engine/src/main/java/io/camunda/zeebe/engine/state/mutable/MutableJobState.java [hunk 3]
```diff
@@ -37,4 +37,8 @@ public interface MutableJobState extends JobState {
   void resolve(long key, JobRecord updatedValue);
 
   JobRecord updateJobRetries(long jobKey, int retries);
+
+  void cleanupTimeoutsWithoutJob();
+
+  void cleanupBackoffsWithoutJobs();
```
[the remark this answers is not in the document]
Comment (oleschoenburg) [reply engine/src/main/java/io/camunda/zeebe/engine/state/mutable/MutableJobState.java:43]: Argh, yeah I'll fix this :+1:

**Review by koevskinikola — APPROVED** [review]
LGTM :rocket: 

bors merge

**Comment by remcowesterhoud** [comment]
FYI, the backport of this will most likely fail because of changes I made to migrations recently. Let me know if you need help resolving this.

**Comment by koevskinikola** [comment]
Seems like https://github.com/camunda/zeebe/issues/13537 is popping up again.

**Comment by oleschoenburg** [comment]
@remcowesterhoud I was hoping that https://github.com/camunda/zeebe/pull/13780 would be backported too :sweat_smile: 
The tracking would be really useful here because we want to run the migration only once and we don't have a good indicator on whether it needs to run or not. Do you think you could backport https://github.com/camunda/zeebe/pull/13780?
