### PR TITLE
Move atomix logstorage to broker

### LINKED ISSUE #8975: Move Atomix log storage implementation into the broker
**Description**

The Atomix log storage implementation is currently located in the log stream module. This means the logstream, and anything depending on it, are dependent on Atomix as well. This is unnecessary, and in fact wrong. We should move the implementation into the broker, which will simplify the dependency tree and decouple our Raft from the engine.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

I wanted to code a bit on Zeebe again, so sorry if someone else wanted to do it.

* I moved the list logstorage to the logstreams to simplify the tests, as discussed in #8975 
* Engine tests uses the same logstorage
* Moved atomix logstorage related tests to broker
* Move atomix logstorage related classes to broker
* Remove atomix-cluster dependency from logstreams
* Removed some unused classes

Note: One thing I was not sure, is regarding the Listener. We seem to check for a certain atomix exception. I'm not sure whether this is really necessary. I guess we could also just fail here if this is anyway no leader anymore.

## Related issues

closes #8975 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStoragePartitionTransitionStep.java [hunk 1]
```diff
@@ -140,12 +148,4 @@ public void appendEntry(
               lowestPosition, highestPosition));
     }
   }
-
-  public static final class LogStorageTermMissmatchException
-      extends RecoverablePartitionTransitionException {
-    private LogStorageTermMissmatchException(
-        final long expectedTerm, final long actualTerm, final int partitionId) {
-      super(String.format(WRONG_TERM_ERROR_MSG, expectedTerm, actualTerm, partitionId));
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStoragePartitionTransitionStep.java:148]: :question: Do I have a wrong config? Seems I moved some methods in some classes

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java [hunk 2]
```diff
@@ -36,7 +35,12 @@ public void onWrite(final long address) {
...
   @Override
   public void onWriteError(final Throwable error) {
-    if (error instanceof NoSuchElementException || error instanceof NoLeader) {
+    if (error instanceof NoSuchElementException
+        || error
+            .getMessage()
+            .contains(
+                "Failed to locate leader") // this is sub-optimal and should be checked elsewhere
+    ) {
       // Not a failure. It is probably during transition to follower.
```
Comment (Zelldon) [inline logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: :wrench: I would like to remove this

Comment (npepinpe) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: I agree that this should be hidden, as it leaks knowledge of Atomix. This should be pushed down either to the LogStorage or to the ZeebeLogAppender (or whatever the implementation is called :smile:)

File: logstreams/pom.xml [hunk 3]
```diff
@@ -75,11 +75,6 @@
       <artifactId>simpleclient</artifactId>
     </dependency>
 
-    <dependency>
-      <groupId>io.camunda</groupId>
-      <artifactId>zeebe-atomix-cluster</artifactId>
```
Comment (npepinpe) [inline logstreams/pom.xml:80]: :tada:

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java (hunk 2 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: Do we need it at all? If we anyway not the leader we do not care right? :shrug:

File: broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java [hunk 4]
```diff
@@ -5,18 +5,15 @@
...
 import io.atomix.raft.zeebe.ZeebeLogAppender.AppendListener;
 import io.camunda.zeebe.logstreams.storage.LogStorage;
 
-public final class AtomixAppendListenerAdapter implements AppendListener {
-  private final LogStorage.AppendListener delegate;
-
-  public AtomixAppendListenerAdapter(final LogStorage.AppendListener delegate) {
-    this.delegate = delegate;
-  }
+public record AtomixAppendListenerAdapter(
```
Comment (npepinpe) [inline broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java]: :question: So I know we haven't talked about this in the team before. IntelliJ just tells you that something can be a record if all its properties are immutable, which is technically true. However, it's a little strange for me semantically. A record is a data/value class. See, for example, the Oracle docs:

> Record classes, which are a special kind of class, help to model plain data aggregates with less ceremony than normal classes.
>
>For background information about record classes, see JEP 395.
>
>A record declaration specifies in a header a description of its contents; the appropriate accessors, constructor, equals, hashCode, and toString methods are created automatically. A record's fields are final because the class is intended to serve as a simple "data carrier". 

I don't think the adapter is a data carrier here, so I would keep it as a normal class. I see the benefit in indicating intent, mostly.

This is fairly new though, so my thoughts on it are also fairly new :smile: Happy to discuss that

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStoragePartitionTransitionStep.java (hunk 1 above)
Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStoragePartitionTransitionStep.java:148]: Not sure, that sometimes happens to me too (although not in a long time). Maybe @korthout or @remcowesterhoud have some ideas?

File: broker/src/test/java/io/camunda/zeebe/broker/logstreams/AtomixLogStorageRule.java [hunk 5]
```diff
@@ -38,7 +34,7 @@
 import org.junit.rules.TemporaryFolder;
 
 public final class AtomixLogStorageRule extends ExternalResource
```
Comment (npepinpe) [inline broker/src/test/java/io/camunda/zeebe/broker/logstreams/AtomixLogStorageRule.java:36]: :+1: So much deleted code :star_struck:

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java (hunk 2 above)
Comment (deepthidevaki) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: If the write fails due to other error, we would like to catch it and stop LogStorageAppender to stop writing new records.

File: logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamReaderTest.java [hunk 6]
```diff
@@ -26,26 +26,21 @@
 import org.junit.Test;
 import org.junit.rules.ExpectedException;
 import org.junit.rules.RuleChain;
-import org.junit.rules.TemporaryFolder;
 
 public final class LogStreamReaderTest {
   private static final UnsafeBuffer EVENT_VALUE = new UnsafeBuffer(getBytes("test"));
   private static final int LOG_SEGMENT_SIZE = (int) ByteValue.ofMegabytes(4);
 
   @Rule public final ExpectedException expectedException = ExpectedException.none();
```
Comment (npepinpe) [inline logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamReaderTest.java:34]: :wrench: We can address the warning now - I think this is not used anywhere, so let's just remove it

File: logstreams/src/test/java/io/camunda/zeebe/logstreams/log/LogStreamBatchWriterTest.java [hunk 7]
```diff
@@ -46,17 +45,13 @@ public final class LogStreamBatchWriterTest {
 
   @Rule public ExpectedException expectedException = ExpectedException.none();
```
Comment (npepinpe) [inline logstreams/src/test/java/io/camunda/zeebe/logstreams/log/LogStreamBatchWriterTest.java:46]: :wrench: Same, I think we can remove it?

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java (hunk 2 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: Exactly, so why we make here the difference with the exception? We can handle both the same or not?

File: logstreams/src/test/java/io/camunda/zeebe/logstreams/log/LogStreamWriterTest.java [hunk 8]
```diff
@@ -40,17 +39,13 @@ public final class LogStreamWriterTest {
 
   @Rule public ExpectedException expectedException = ExpectedException.none();
```
Comment (npepinpe) [inline logstreams/src/test/java/io/camunda/zeebe/logstreams/log/LogStreamWriterTest.java:40]: :wrench: Same :smile: At least I see no usage :thinking:

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java (hunk 2 above)
Comment (deepthidevaki) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: If it is not leader, then it is an expected case because of asynchronous leader transition. We can just ignore them - as we do here. We just log it in debug and continue. The other error cause it to go unhealthy, if I remember correctly.

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamWriterImpl.java [hunk 9]
```diff
@@ -39,7 +39,7 @@ public final class LogStreamWriterImpl implements LogStreamRecordWriter {
   private BufferWriter metadataWriter;
   private BufferWriter valueWriter;
 
-  LogStreamWriterImpl(final int partitionId, final Dispatcher logWriteBuffer) {
+  public LogStreamWriterImpl(final int partitionId, final Dispatcher logWriteBuffer) {
```
Comment (npepinpe) [inline logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamWriterImpl.java:42]: :x: I understand we use it in the broker tests now, but this should be implementation detail for the broker - is there no way to just get a `LogStreamWriter` for those tests? I would ideally not want to depend on `impl` stuff from outside the module.

**Review by npepinpe — CHANGES_REQUESTED** [review]
:rocket: 

Thanks for doing this! The only thing for me is that we now depend on logstreams implementation details in the broker, which we should avoid. Can be a follow up PR, or directly here depending on how much changes that would cause.

- :wrench: I was thinking we would move the in memory storage into the production code of the logstreams, actually. We use it in the tests, in the engine tests, and also in `zeebe-process-test`. So I figured, why not, it's simple enough and not that much to maintain. But maybe someone from the automation team would have a different opinion. Generally I would hope we don't depend on `test-jar`.

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java (hunk 2 above)
Comment (npepinpe) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: Can we not handle it on our side and simply return a `NoSuchElementException` or a new exception that is part of the API, and not an Atomix detail?

Comment (deepthidevaki) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: That would be possible.

Comment (Zelldon) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: I feel we talk past each other. I see the point that we CAN ignore it in the cause, but it is not necessary, right? Means we could just handle it the same which would simplify our code here and reduce the dependencies. Currently, the code has knowledge of atomix internals which is sub-optimal. 

@npepinpe I haven't looked into much detail here, but I can do if you want. I first wanted to discuss this gem. :gem:

Comment (deepthidevaki) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: > I feel we talk past each other. I see the point that we CAN ignore it in the cause, but it is not necessary, right? Means we could just handle it the same which would simplify our code here and reduce the dependencies. Currently, the code has knowledge of atomix internals which is sub-optimal.

If you handle it the same, there will be error logs whenever a leader transition to follower. One error which says "Failed to append block .." and the second error which logs this partition as unhealthy.

**Comment by deepthidevaki** [comment]
@Zelldon I have only started to look into this PR. Nicolas has already reviewed it. Let me know if you need a review from me as well. Otherwise I would not review this.

File: broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java (hunk 4 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java]: Tbh I don't care. I just followed the instructions from intellij and thought we want to migrate most of our classes :shrug: I can revert this if you want.

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java (hunk 2 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java:44]: I will take a look how I could circle around it

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStoragePartitionTransitionStep.java (hunk 1 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/LogStoragePartitionTransitionStep.java:148]: Or we haven't updated all classes yet? :man_shrugging:

File: logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamReaderTest.java (hunk 6 above)
Comment (Zelldon) [reply logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamReaderTest.java]: Interesting that intellij doesn't show any warning or hint here

Comment (npepinpe) [reply logstreams/src/test/java/io/camunda/zeebe/logstreams/impl/log/LogStreamReaderTest.java]: I guess because it's a rule, and rules are implicitly used. But technically as we never change the expectation, it sounds to me like it's useless? Maybe I misunderstood how the rule works? :thinking:

File: broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java (hunk 4 above)
Comment (npepinpe) [reply broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java]: I would like to keep records for what they're meant to be, i.e. data carrier, since by default all their properties become public (which we may not always want). So let's do that. If you don't care, then let's keep doing that :wink: And when you do we can discuss it :smile:

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamWriterImpl.java (hunk 9 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamWriterImpl.java:42]: I think the test which uses this should completely replaced by something else. We totally depend on internals and add more glue code for logstorage as a separate rule. I feel this can totally diverge since we rely on test code and not on real production code.

Comment (npepinpe) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamWriterImpl.java:42]: Please either do it in this scope or create a follow up issue for this :+1:

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java (hunk 2 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Listener.java]: @deepthidevaki and @npepinpe what do you think of the last commit https://github.com/camunda/zeebe/pull/9235/commits/ae15d717561119435fd546d4a5b8e536cc2e2cde I moved the handling into the adapter. BTW for what is the `NoSuchElementException` handling I found no place where this can be caused?

File: broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java [hunk 10]
```diff
@@ -25,6 +35,17 @@ public void onWrite(final IndexedRaftLogEntry indexed) {
 
   @Override
   public void onWriteError(final Throwable error) {
+    if (error instanceof NoSuchElementException || error instanceof NoLeader) {
+      // Not a failure. It is probably during transition to follower.
+      Broker.LOG.debug(
```
Comment (npepinpe) [inline broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java:40]: :x: Either use its own logger or one from `Loggers`. I think it's just confusing if it uses the `Broker` class' logger.

**Review by npepinpe — COMMENTED** [review]
I like the new adapter :+1:

File: broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java (hunk 10 above)
Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/logstreams/AtomixAppendListenerAdapter.java:40]: Yeah was also not sure about that. I guess we still have no real policy here.

File: logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamWriterImpl.java (hunk 9 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamWriterImpl.java:42]: I created https://github.com/camunda/zeebe/issues/9244 for this

**Comment by Zelldon** [comment]
@npepinpe thanks again for your review. I guess I applied all your comments please have another look. :bow:

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by npepinpe** [comment]
Reminder for Monday: I think logstreams were part of the "slow" unit tests for the GHA CI - can we now remove them from that?

**Comment by Zelldon** [comment]
Is this something I have to do ? @npepinpe

**Comment by npepinpe** [comment]
No, it was a reminder so I wouldn't forget. I'll post it in the GHA slack channel to know if that was the reason the log streams were added to the slow unit tests. TBH I don't know why we have a slow unit test separate job :man_shrugging:
