### PR TITLE
Load Optimize spring.config props as lists

### LINKED ISSUE #47473: Optimize: spring.config.import cannot process YAML list
### 

### 

### 

### 

### Description

Unable to load multiple extra configurations into Optimize using `spring.config.import` when specified as a YAML list. The list entries are not loaded at all. The root cause is a limitation in Spring Framework, see https://github.com/spring-projects/spring-framework/issues/35179. See related issues in this repository: #44820 and #47472.

### Steps to reproduce

1. Configure Optimize with `spring.config.import` as a YAML list:
```yaml
spring:
  config:
    import:
      - optional:file:/optimize/config/boat.yaml
      - optional:file:/optimize/config/about.yaml
      - optional:file:/optimize/config/env.yaml
```
2. Deploy Optimize with this config
3. Observe that none of the listed files are loaded

### Current behavior

No extra configuration files from the list are loaded. Optimize does not read them and ignores the configuration.

### Expected behavior

All configuration files listed in `spring.config.import` should be loaded automatically when specified as a YAML list.

### Workaround

You can specify `spring.config.import` as a comma-delimited string without whitespaces:
```yaml
spring:
  config:
    import: optional:file:/optimize/config/boat.yaml,optional:file:/optimize/config/about.yaml,optional:file:/optimize/config/env.yaml
```
Do not use whitespaces, see #47472.

### Environment

SaaS & SM

### Version

- 8.9
- main

### Rootcause

Root cause is a limitation in Spring Framework's handling of YAML lists, see https://github.com/spring-projects/spring-framework/issues/35179.

### Solution ideas

Potential solutions include updating Optimize to handle YAML list entries for `spring.config.import`, once Spring Framework supports it. Track upstream and apply a workaround if necessary.

Alternatively, use the workaround proposed in https://github.com/spring-projects/spring-framework/issues/35179#issuecomment-3989747033.

### Dev -> QA handover

_No response_

### Links

Related issues:
- #44820
- #47472
- https://github.com/spring-projects/spring-framework/issues/35179

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by korthout**
## Description

Adds support for `spring.config.import` and `spring.config.location` properties specified as YAML lists in Optimize's `ConfigurationServiceBuilder`.

```
spring:
  config:
    import:
      - optional:file:/boat.yaml
      - optional:file:/about.yaml
      - optional:file:/env.yaml
```

When these properties are specified as YAML lists (rather than comma-delimited strings), Spring loads them as indexed properties (e.g. `spring.config.import[0]`, `spring.config.import[1]`, ...). However, Spring's `Environment.getProperty()` cannot resolve indexed list properties directly ([spring-framework#35179](https://github.com/spring-projects/spring-framework/issues/35179)), causing Optimize to silently ignore all listed config files.

This PR introduces a `getListProperty()` helper that:
1. First attempts a direct `getProperty()` lookup (for comma-delimited string values)
2. Falls back to iterating over indexed properties (`propertyName[0]`, `propertyName[1]`, ...) to collect list entries

This is a workaround for the upstream Spring Framework bug, following the approach suggested in [spring-framework#35179 (comment)](https://github.com/spring-projects/spring-framework/issues/35179#issuecomment-3989747033).

### Changes

- **`ConfigurationServiceBuilder.java`** — Refactored `resolveConfigLocations()` to use the new `getListProperty()` method instead of `Environment.getProperty()` + manual comma-splitting. Whitespace trimming is now handled centrally in `getListProperty()`.
- **`ConfigurationServiceBuilderTest.java`** — Added a parameterized test (`shouldResolveConfigLocationsFromEnvironmentAsList`) that runs all existing test cases with properties loaded as indexed list entries, ensuring parity between comma-delimited and YAML list formats.
- **`ExtraConfigurationConfigImportIT.java`** — Added an integration-level regression test (`shouldLoadEnvYamlImportedAsList`) that mimics a Kubernetes ConfigMap setup where `spring.config.import` is specified as a YAML list importing multiple files.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #47473

### CODE REVIEW

File: optimize/util/optimize-commons/src/test/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilderTest.java [hunk 1]
```diff
@@ -43,6 +44,33 @@ void shouldResolveConfigLocationsFromEnvironment(
       Assertions.assertThat(configLocations).containsExactlyElementsOf(expectedLocations);
     }
 
+    @ParameterizedTest(name = "{0}")
+    @MethodSource("configLocationCases")
+    void shouldResolveConfigLocationsFromEnvironmentAsList(
+        final String caseName,
+        final String importValues,
+        final String locationValues,
+        final List<String> expectedLocations) {
```
[the remark this answers is not in the document]
Comment (korthout) [reply optimize/util/optimize-commons/src/test/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilderTest.java]: IMO, the tiny bit of duplication is fine for such tests.

File: optimize/backend/src/it/java/io/camunda/optimize/ExtraConfigurationConfigImportIT.java [hunk 2]
```diff
@@ -169,4 +169,71 @@ void shouldLoadEnvYamlImportedFromApplicationCcsmProfile() throws Exception {
     final var configService = embeddedOptimizeExtension.getConfigurationService();
     assertThat(configService.getConfiguredZeebe().getPartitionCount()).isEqualTo(3);
   }
+
+  /** Regression test for <a href="https://github.com/camunda/camunda/issues/47473">#47473</a> */
+  @Test
+  void shouldLoadEnvYamlImportedAsList() throws Exception {
+    // given: a setup mimicking Kubernetes ConfigMap with application-ccsm.yaml importing files
+    // where the import is specified as a list
+    Files.writeString(
```
[the remark this answers is not in the document]
Comment (korthout) [reply optimize/backend/src/it/java/io/camunda/optimize/ExtraConfigurationConfigImportIT.java:178]: I don't agree. This helps to [keep the reader in the test](https://mtlynch.io/good-developers-bad-tests/#keep-the-reader-in-your-test-function).

File: optimize/util/optimize-commons/src/test/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilderTest.java [hunk 3]
```diff
@@ -43,6 +44,33 @@ void shouldResolveConfigLocationsFromEnvironment(
...
+
+      // with spring.config values loaded as lists
+      final var strings = StringUtils.commaDelimitedListToStringArray(importValues);
+      for (var i = 0; i < strings.length; i++) {
+        environment.setProperty("spring.config.import[" + i + "]", strings[i]);
+      }
+      final var locationStrings = StringUtils.commaDelimitedListToStringArray(locationValues);
+      for (var i = 0; i < locationStrings.length; i++) {
+        environment.setProperty("spring.config.location[" + i + "]", locationStrings[i]);
+      }
```
Comment (fabiopaini-camunda) [inline optimize/util/optimize-commons/src/test/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilderTest.java]: ❓ This also injects the whitespaces in the environment variables, is it desired?

💭 I don't really like the fact that we start from a comma-separated list as the test input when it has not relation to this test. It could make sense to refactor the tests in order to work the other way around:
- provide a `List` of paths in the `configLocationCases`
- have three tests:
  - `shouldResolveConfigLocationsFromEnvironmentAsCommaSeparatedList`
  - `shouldResolveConfigLocationsFromEnvironmentAsCommaSeparatedListWithWhitespace`
  - `shouldResolveConfigLocationsFromEnvironmentAsIndexedProperties`
- in each test, construct the environment properties as required

The whitespace-related test cases added in #47477 can then be removed since they are handled by the specific `shouldResolveConfigLocationsFromEnvironmentAsCommaSeparatedListWithWhitespace` test for all other test cases.

File: optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java [hunk 4]
```diff
@@ -169,5 +169,38 @@ static List<String> resolveConfigLocations(final Environment environment) {
...
+      final List<String> collectedValues = new ArrayList<>();
+      for (int index = 0; index < Integer.MAX_VALUE; index++) {
+        final String indexedKey = propertyName + "[" + index + "]";
+        if (!environment.containsProperty(indexedKey)) {
+          break;
+        }
+        final String rawIndexedValue = environment.getProperty(indexedKey);
+        if (rawIndexedValue == null) {
+          continue;
+        }
```
Comment (fabiopaini-camunda) [inline optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java:205]: 🔧 This shouldn't be needed since you already check `environment.containsProperty` above

File: optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java [hunk 5]
```diff
@@ -169,5 +169,38 @@ static List<String> resolveConfigLocations(final Environment environment) {
...
+     */
+    private static List<String> getListProperty(
+        final Environment environment, final String propertyName) {
+      final String directMatch = environment.getProperty(propertyName);
+      if (directMatch != null) {
+        // direct matches may still be comma delimited
+        final var asArray = StringUtils.commaDelimitedListToStringArray(directMatch);
+        // comma delimitation may require whitespace trimming
+        return Arrays.stream(asArray).map(String::trim).toList();
+      }
```
Comment (fabiopaini-camunda) [inline optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java]: 💭 Looking at the referenced Spring issue made me look into the conversion capabilities of `environment.getProperty`, which already handles comma-separated string and whitespace trimming. I think we can simplify this with:
```suggestion
      final List<String> directMatch = environment.getProperty(propertyName, List.class);
      if (directMatch != null) {
        return directMatch;
      }
```
This would both simplify our code as well as ensure that we are parsing the properties the same way as Spring does.

File: optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java [hunk 6]
```diff
@@ -169,5 +169,38 @@ static List<String> resolveConfigLocations(final Environment environment) {
...
+        if (!environment.containsProperty(indexedKey)) {
+          break;
+        }
+        final String rawIndexedValue = environment.getProperty(indexedKey);
+        if (rawIndexedValue == null) {
+          continue;
+        }
+        // indexed values may still require whitespace trimming
+        collectedValues.add(rawIndexedValue.trim());
+      }
```
Comment (fabiopaini-camunda) [inline optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java:208]: 💭 We could again use the conversion capabilities of `environment.getProperty` to handle comma-separated lists in each individual entry (is it supported?) and whitespace trimming.

```suggestion
      final List<String> indexedValue = environment.getProperty(indexedKey, List.class);
      collectedValues.addAll(indexedValue);
```

**Review by fabiopaini-camunda — APPROVED** [review]
@korthout I am very sad to see that this is not yet supported by Spring, but very happy to see you are handling it on our side without getting blocked 👍 

I added some ideas that I think could improve the code, but I am already approving it in the meantime.

❌ Just one thing: please review the commit messages to be a little bit more informative.

File: optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java (hunk 6 above)
Comment (korthout) [reply optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java:208]: I'm not sure that this is supposed to work like that. I'd expect that a list entry with comma-separated entries actually is a list of strings where the commas are just part of the strings.

File: optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java (hunk 4 above)
Comment (korthout) [reply optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/util/configuration/ConfigurationServiceBuilder.java:205]: Depends on whether this is threadsafe or not. I'd prefer being on the safe side.
