### PR TITLE
fix: eliminate duplicated snapshot request for indices (not template)

### LINKED ISSUE #26066: Matchers used for index descriptor make impossible to restore a backup
Only ` IndexTemplateDescriptor` should  generate patterns with matchers like:
- `index_*`
- `-index`
But currently these matching patterns are generated for all indices, making impossible to restore.

The error reported by elasticsearch when trying to restore in tasklist `BackupRestorTest` is the following:
```
Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://localhost:50271/], URI [/_snapshot/testRepository/camunda_webapps_123_8.7.0-snapshot_part_4_of_8/_restore?master_timeout=30s&wait_for_completion=true], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"snapshot_restore_exception","reason":"[testRepository:camunda_webapps_123_8.7.0-snapshot_part_4_of_8/u9IYf5RdTrCrDBvlJQpHbQ] cannot restore index [operate-flownode-instance-8.3.1_] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"}],"type":"snapshot_restore_exception","reason":"[testRepository:camunda_webapps_123_8.7.0-snapshot_part_4_of_8/u9IYf5RdTrCrDBvlJQpHbQ] cannot restore index [operate-flownode-instance-8.3.1_] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"},"status":500}
```

When checking the content of the snapshots before restoring, we see that some indices are "duplicated", i.e. present in more than one part of the snapshot.

### PR DESCRIPTION
**Pull request by entangled90**
## Description

Indices (that were not templates) where included twice in the snapshot requests, making it impossible to restore them.

Extracted the logic for generating the list of indices to be included in the requests from BackupServiceImpl to BackupProperties to ease the testing.

Added a unit test where each list of indices is checked. Comparing this with the original requirements some  discrepancies were found. Most of these discrepancies are related to indices not existing anymore or being renamed.

Notable changes compared to the table in this [comment](https://github.com/camunda/camunda/issues/24464#issuecomment-2517086937)
- These templates have been moved to the following  part of the snapshot:
  -  tasklist-draft-task-variable-8.3.0_
  -  -tasklist-draft-task-variable-8.3.0_
  -  tasklist-task-variable-8.3.0_
  -  -tasklist-task-variable-8.3.0_
- In the original table I don't see operate's template matchers, even though in the code they are included, see version [BackupService](https://github.com/camunda/camunda/blob/8.6.5/operate/webapp/src/main/java/io/camunda/operate/webapp/backup/BackupService.java#L168) from version 8.6.5:
```java
// dated indices
            prio3BackupTemplates.stream()
                .map(
                    index ->
                        new String[] {
                          ((TemplateDescriptor) index).getFullQualifiedName() + "*",
                          "-" + ((TemplateDescriptor) index).getFullQualifiedName()
                        })
                .flatMap(Arrays::stream)
                .toArray(String[]::new),
```
These template matchers from operate are:
- operate-event-8.3.0_*
- -operate-event-8.3.0_
- operate-flownode-instance-8.3.1_*
- -operate-flownode-instance-8.3.1_
- operate-incident-8.3.1_*
- -operate-incident-8.3.1_
- operate-job-8.6.0_*
- -operate-job-8.6.0_
- operate-message-8.5.0_*
- -operate-message-8.5.0_
- operate-post-importer-queue-8.3.0_*
- -operate-post-importer-queue-8.3.0_
- operate-sequence-flow-8.3.0_*
- -operate-sequence-flow-8.3.0_
- operate-user-task-8.5.0_*
- -operate-user-task-8.5.0_
- operate-variable-8.3.0_*
- -operate-variable-8.3.0_
- -operate-decision-instance-8.3.0_
- operate-decision-instance-8.3.0_*

## Related issues

relates #26066

### CODE REVIEW

File: webapps-schema/src/main/java/io/camunda/webapps/schema/descriptors/backup/BackupPriorities.java [hunk 1]
```diff
@@ -21,4 +23,35 @@ public record BackupPriorities(
...
+      final Collection<A> backups) {
+    final var indices = backups.stream().map(BackupPriority::getFullQualifiedName).toList();
+    return new SnapshotIndexCollection(indices);
+  }
+
+  private static <A extends BackupPriority> SnapshotIndexCollection fullQualifiedNameWithMatcher(
+      final Collection<A> backups) {
+    final var indices =
+        backups.stream()
+            .filter(IndexTemplateDescriptor.class::isInstance)
```
Comment (entangled90) [inline webapps-schema/src/main/java/io/camunda/webapps/schema/descriptors/backup/BackupPriorities.java:51]: This is the filter that was previously missing

**Comment by marcosgvieira** [comment]
> * In the original table I don't see operate's template matchers, even though in the code they are included, see version [BackupService](https://github.com/camunda/camunda/blob/8.6.5/operate/webapp/src/main/java/io/camunda/operate/webapp/backup/BackupService.java#L168) from version 8.6.5:

This is probably a discrepancy/copy and paste issue, we should be ok following the code from 8.6.

File: dist/src/test/java/io/camunda/application/commons/backup/BackupPrioritiesTest.java [hunk 2]
```diff
@@ -120,6 +120,96 @@ public void testBackupPriorities(
...
+            "operate-decision-instance-8.3.0_*",
+            "-tasklist-draft-task-variable-8.3.0_",
+            "tasklist-draft-task-variable-8.3.0_*",
+            "-tasklist-task-variable-8.3.0_",
+            "tasklist-task-variable-8.3.0_*");
+
+    // PRIO 5
+    assertThat(indices.get(6).indices())
+        .containsExactlyInAnyOrder(
+            //            "operate-web-session-1.1.0_", // TODO Does it exist?
```
Comment (marcosgvieira) [inline dist/src/test/java/io/camunda/application/commons/backup/BackupPrioritiesTest.java:197]: can we remove the TODO?

**Review by marcosgvieira — APPROVED** [review]
Thanks for adjusting this @entangled90, I liked the refactorings and improvements.

File: dist/src/test/java/io/camunda/application/commons/backup/BackupPrioritiesTest.java (hunk 2 above)
Comment (entangled90) [reply dist/src/test/java/io/camunda/application/commons/backup/BackupPrioritiesTest.java:197]: I did not get a reply yet on the thread, that's why I didn't remove it :+1:
