### PR TITLE
Group similar error bulk messages from ES.

### LINKED ISSUE #31627: Huge error logs when ES is out of disk space
### 

### 

### 

### 

### Description

When ES reaches the hwm for the disk space size, all requests start failing. 
In the releae-8-8-0-alpha3 branch the log messages reporting the failure for `ElasticsearchBatchRequest` become huge and even "break" Google's Logs exporter.
See for example this [log](https://console.cloud.google.com/logs/query;aroundTime=2025-04-19T12:27:11.841Z;cursorTimestamp=2025-04-19T02:01:56.689488523Z;duration=PT24H;query=resource.labels.namespace_name%3D%22release-8-8-0-alpha3%22%0Atimestamp%3D%222025-04-19T02:01:56.689488523Z%22%0AinsertId%3D%22anurabnxotl7jakh%22?project=zeebe-io) message. 
Here's the message (truncated):

<pre>Bulk request execution failed: 
[Update failed for type [operate-event-8.3.0_] and id [4503600003005213_4503600003005237]: index [operate-event-8.3.0_] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block; for more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.17/fix-watermark-errors.html];, 
Update failed for type [operate-list-view-8.3.0_] and id [4503600003005514-var2]: index [operate-list-view-8.3.0_] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block; for more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.17/fix-watermark-errors.html];, 
Update failed for type [operate-list-view-8.3.0_] and id [4503600003005489-var2]: index [operate-list-view-8.3.0_] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block; for more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.17/fix-watermark-errors.html];, 
Update failed for type [operate-list-view-8.3.0_] and id [4503600003005386-var11]: index [operate-list-view-8.3.0_] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block; for more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.17/fix-watermark-errors.html];, 
Update failed for type [operate-list-view-8.3.0_] and id [4503600003005414-var14]: index [operate-list-view-8.3.0_] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block; for more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.17/fix-watermark-errors.html];, 
Update failed for type [tasklist-task-8.5.0_] and id [4503600003005539-var14]: index [tasklist-task-8.5.0_] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block; for more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.17/fix-watermark-errors.html];, 
Update failed for type [operate-event-8.3.0_] and id [4503600003005213_4503600003005213]: index [operate-event-8.3.0_] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block; for more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.17/fix-watermark-errors.html];, 
Update failed for type [operate-list-view-8.3.0_] and id [4503600003005413]: index [operate-list-view-8.3.0_] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block; for more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.17/fix-watermark-errors.html];, 
Update failed for type [operate-list-view-8.3.0_] and id [4503600003005414-var13]: index [operate-list-view-8.3.0_] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block; for more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.17/fix-watermark-errors.html];,  </pre>

### Steps to reproduce

Make ES reach its disk space limit. It may happen in other situations as well, when many requests fail

### Current behavior

A huge log message is reported 

### Expected behavior

The error message is truncated to avoid going over a certain size. 
Ideally the same error code can group indices experiencing the same issue, without duplicates.

### Environment

SM

### Version

- Zeebe 8.8.0-alpha3

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

Sometimes it can happen that, in OpenSearch or ElasticSearch bulk requests, the log messages reporting the failure for BatchRequests become too large and even "break" Google's Logs exporter.

This PR groups similar messages and shows the IDs where this happens instead of printing unique message for each ID. Additionally also limits the number of possible group errors by 50.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes https://github.com/camunda/camunda/issues/31627

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java [hunk 1]
```diff
@@ -188,14 +191,29 @@ private void validateNoErrors(
...
     }
 
-    final String errorMessages =
+    final Map<ErrorKey, List<String>> groupedErrors =
         errorItems.stream()
+            .collect(
+                Collectors.groupingBy(
+                    item -> new ErrorKey(item.operationType(), item.index(), item.error().reason()),
+                    LinkedHashMap::new,
+                    Collectors.mapping(BulkResponseItem::id, Collectors.toList())));
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java:200]: You could merge this with the `items.stream()...` on line 189, as it iterates through the same list

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java [hunk 2]
```diff
@@ -188,14 +191,29 @@ private void validateNoErrors(
...
+            // these error groups can sometimes be too large and even
+            // overflow the logger buffer.
+            .limit(100)
             .map(
-                item ->
+                entry ->
                     String.format(
-                        "%s failed for type [%s] and id [%s]: %s",
-                        item.operationType(), item.index(), item.id(), item.error().reason()))
+                        "%s failed for type %s with ids: %s: %s",
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java:210]: I know this is not new, but I think we should change it to this:
```suggestion
                        "%s failed on index %s with ids: %s: %s",
```

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/OpensearchBatchRequest.java [hunk 3]
```diff
@@ -189,13 +192,27 @@ private void validateNoErrors(
       return;
     }
 
-    final String errorMessages =
+    final Map<ErrorKey, List<String>> groupedErrors =
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/OpensearchBatchRequest.java:195]: same as in the ES file

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/OpensearchBatchRequest.java [hunk 4]
```diff
@@ -189,13 +192,27 @@ private void validateNoErrors(
...
+            // these error groups can sometimes be too large and even
+            // overflow the logger buffer.
+            .limit(100)
             .map(
-                item ->
+                entry ->
                     String.format(
-                        "%s failed for type [%s] and id [%s]: %s",
-                        item.operationType(), item.index(), item.id(), item.error().reason()))
+                        "%s failed for type %s with ids: %s: %s",
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/OpensearchBatchRequest.java:211]: same as in the ES file

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java [hunk 5]
```diff
@@ -188,14 +191,29 @@ private void validateNoErrors(
...
+            .collect(
+                Collectors.groupingBy(
+                    item -> new ErrorKey(item.operationType(), item.index(), item.error().reason()),
+                    LinkedHashMap::new,
+                    Collectors.mapping(BulkResponseItem::id, Collectors.toList())));
+
+    final String errorMessages =
+        groupedErrors.entrySet().stream()
+            // these error groups can sometimes be too large and even
+            // overflow the logger buffer.
```
Comment (RomanJRW) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java:205]: would it help if we did not group by index? We could instead just group by operation and error message, and then log the pairs of index and IDs per group

**Review by RomanJRW — APPROVED** [review]
Generally LGTM, just some small suggestions to consider 👍

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java (hunk 5 above)
Comment (rodrigo-lourenco-lopes) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java]: Good point, I added this suggestion by also displaying unique indexes and removed the limit 👍

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java [hunk 6]
```diff
@@ -188,21 +191,38 @@ private void validateNoErrors(
...
     }
 
-    final String errorMessages =
+    final Map<ErrorKey, ErrorValues> groupedErrors =
         errorItems.stream()
+            .collect(
+                Collectors.groupingBy(
+                    item -> new ErrorKey(item.operationType(), item.error().reason()),
+                    LinkedHashMap::new,
+                    Collectors.collectingAndThen(
```
[the remark this answers is not in the document]
Comment (rodrigo-lourenco-lopes) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java:200]: Now that we have already grouped the errors in a list of IDs with the same indexes and types, the number of error messages should be much smaller, but I can add back the `limit()` that I had initially. I don't have a strong opinion here.

[the remark this answers is not in the document]
Comment (entangled90) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ElasticsearchBatchRequest.java:199]: Correct, I misinterpreted the code to generate a `Map<ErrorKey, List<String>>` instead it's just a map :+1:

**Review by entangled90 — APPROVED** [review]
:rocket: thanks!
