### PR TITLE
Exclude authorizations from ES/OS exporters

### LINKED ISSUE #35178: `Record#getAuthorizations` is invoked by `ElasticsearchExporter` when exporting
### 

### 

### 

### 

### Description

The method `Record#getAuthorization` is visible in the profiler output in the callstack of `ElasticsearchExporter.export`.
Based on the flamegraph, it looks like that field is in included in the json sent to ES, but I haven't checked yet.

If the field is not indexed by ES, then it's just a performance problem for the `ElasticsearchExporter`, for which it consumes ~ 10% of cpu time

Image

### Steps to reproduce

1. Enable elasticsearchExporter (enabled by default in SM)
2. Export data to ES 

### Current behavior

The method `Record#getAuthorization` is visible in the profiler output in the callstack of `ElasticsearchExporter.export`.

### Expected behavior

The authorization field should not be accessed by the `ElasticsearchExporter` and it should not cause a performance penalty

### Environment

SM

### Version

- Zeebe 8.8.0-SNAPSHOT

### Rootcause

_No response_

### Solution ideas

That field probably doesn't have to be exported, so it should be removed probably from the interface `Record` and be kept under `TypedRecordImpl`

### Dev -> QA handover

_No response_

### Links

_No response_

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR removes the authorizations from the exported `Record<?>` instances in the ES and OS exporters. Nothing was required for the `CamundaExporter` because we don't export raw records there.

## Related issues

closes #35178

### CODE REVIEW

File: zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/BulkIndexRequestTest.java [hunk 1]
```diff
@@ -223,6 +223,25 @@ void shouldIndexRecordWithSequence() {
...
+      // when
+      request.index(actions.get(0), records.get(0), new RecordSequence(PARTITION_ID, 10));
+
+      // then
+      assertThat(request.bulkOperations())
+          .hasSize(1)
+          .map(operation -> MAPPER.readValue(operation.source(), MAP_TYPE_REFERENCE))
+          .extracting(source -> source.get("authorizations"))
+          .describedAs("Expect that the records are NOT serialized with authorizations")
+          .containsExactly(new Object[] {null});
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply zeebe/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/BulkIndexRequestTest.java:244]: False positive - this will lead to an error. We explicitly want to pass an array of nulls.

File: zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/BulkIndexRequestTest.java [hunk 2]
```diff
@@ -223,6 +223,25 @@ void shouldIndexRecordWithSequence() {
...
+      // when
+      request.index(actions.get(0), records.get(0), new RecordSequence(PARTITION_ID, 10));
+
+      // then
+      assertThat(request.bulkOperations())
+          .hasSize(1)
+          .map(operation -> MAPPER.readValue(operation.source(), MAP_TYPE_REFERENCE))
+          .extracting(source -> source.get("authorizations"))
+          .describedAs("Expect that the records are NOT serialized with authorizations")
+          .containsExactly(new Object[] {null});
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/BulkIndexRequestTest.java:244]: False positive, sorry my dude.

File: zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/BulkIndexRequestTest.java [hunk 3]
```diff
@@ -148,8 +149,8 @@ void shouldIndexWithDifferentMetadata() {
   final class SerializationTest {
     @Test
     void shouldIndexRecordSerialized() {
-      // given
-      final var record = recordFactory.generateRecord();
+      // given - use an empty authorization for comparison, since the bulk request
```
Comment (RomanJRW) [inline zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/BulkIndexRequestTest.java]:
```suggestion
      // given - use an empty authorization for comparison, since the bulk request will remove it
```

File: zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/BulkIndexRequestTest.java [hunk 4]
```diff
@@ -165,8 +166,9 @@ final var record = recordFactory.generateRecord();
 
     @Test
     void shouldWriteOperationsAsNDJson() throws IOException {
-      // given
-      final var records = recordFactory.generateRecords().limit(2).toList();
+      // given - use an empty authorization for comparison, since the bulk request
```
Comment (RomanJRW) [inline zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/BulkIndexRequestTest.java]:
```suggestion
      // given - use an empty authorization for comparison, since the bulk request will remove it
```

**Review by RomanJRW — APPROVED** [review]
🚀

File: zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/BulkIndexRequestTest.java (hunk 4 above)
Comment (npepinpe) [reply zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/BulkIndexRequestTest.java]: Bamboozled by the AI auto completion :see_no_evil:
