### PR TITLE
Mappings and settings changes propagate to archived indices

### LINKED ISSUE #32018: SchemaManager does not update mappings and settings of archive indices
### 

### 

### 

### 

### Description

SchemaManager does not update mappings and settings of archive indices

### Steps to reproduce

1. Start a broker and wait for the schema to be created
2. Create and complete some PIs, wait for the archiver to created a new archive index
3. In local, add a dummy property in https://github.com/camunda/camunda/blob/main/webapps-schema/src/main/resources/schema/opensearch/create/template/operate-list-view.json
4. rebuild, and restart the broker

In another test, you can change the replicas setting `camunda.databatase.index.numberOfReplicas`

### Current behavior

the dummy property is added to list-view template mapping and to the runtime index mapping but not to the archived index
Same for the index settings (number of replicas) is not propagated to all indices 

### Expected behavior

the new mapping properties is added to all list-view indices mappings including the archived ones
the numberOfReplicas settings should be applied to all indices including archived ones

### Environment

SM

### Version

- Component Version: 8.8.0 alpha1 to 4

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

_No response_

### PR DESCRIPTION
**Pull request by EuroLew**
## Description

Mappings and settings changes propagate to archived indices

## Related issues

closes #32018

### CODE REVIEW

File: schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java [hunk 1]
```diff
@@ -728,6 +728,38 @@ void shouldHaveCorrectSchemaUpdatesWithConcurrentRuns(
...
+      final SearchEngineConfiguration config, final SearchClientAdapter clientAdapter)
+      throws IOException {
+    // given
+    final var archivedIndex =
+        mockIndex(
+            CONFIG_PREFIX + "-qualified_name_2025-01-01",
+            index.getAlias(),
+            index.getIndexName(),
+            index.getMappingsClasspathFilename());
+    final var schemaManager = createSchemaManager(Set.of(index, archivedIndex), Set.of(), config);
```
Comment (houssain-barouni) [inline schema-manager/src/test/java/io/camunda/search/schema/SchemaManagerIT.java]: 🔧 This is not a realistic test, as the archive index is passed to the schema manager as an IndexDescriptor which is not the way how the SchemaManager is used and implemented
We should rather use IndexTemplateDescriptor, and create the archive index (can be by inserting a document with and index matching the template pattern)

**Review by houssain-barouni — APPROVED** [review]
@EuroLew I took the liberty to replace the test by a couple of tests I used to reproduce the initial issue. https://github.com/camunda/camunda/pull/32028/commits/5ddf117d08595ec6fa09eac292beffa964c8305c

I also made the following [fix](https://github.com/camunda/camunda/pull/32028/commits/217bed594a3269a79d3367b320c153137bc2e3b0):
- the update settings takes care of the indices defined in indexDescriptor only
- we had a filtering on existing indices, now it is needed as we use the alias, same for the template, no need to check the existing templates, as they should be already created.

Please have a look and let me know if you have any concerns
