### PR TITLE
Prevent endless error loop when processing user commands

### LINKED ISSUE #16107: Endless processing state machine error loop
**Describe the bug**

Extracted from https://github.com/camunda/zeebe/issues/14929 and https://github.com/camunda/zeebe/issues/16104

When such cases produce an error, the processing state machine will try and handle it. Part of the error handling is to respond to the user with a rejection. However, in this case, we failed to serialize the record when appending the rejection, which causes a new error. This is then handled the same way, and simply loops forever.

**To Reproduce**

```java
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Zeebe Community License 1.1. You may not use this file
 * except in compliance with the Zeebe Community License 1.1.
 */
package io.camunda.zeebe.it.client.command;

import static org.assertj.core.api.Assertions.assertThat;

import io.camunda.zeebe.qa.util.cluster.TestStandaloneBroker;
import io.camunda.zeebe.qa.util.junit.ZeebeIntegration;
import io.camunda.zeebe.qa.util.junit.ZeebeIntegration.TestZeebe;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.concurrent.Future;
import org.junit.jupiter.api.Test;

@ZeebeIntegration
public class EndlessLoopTest {
  @TestZeebe private final TestStandaloneBroker broker = new TestStandaloneBroker();

  private final String dmn =
      """
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" id="_6f87b3aa-d613-4c41-93ad-832f021c8318" name="definitions" namespace="http://camunda.org/schema/1.0/dmn">
  <decision id="_51711_44808585-3491-42a8-87ea-3c4fcda46eff" name="">
    <decisionTable id="_07c6fdc3-7bdf-459a-a016-2ae12e474bd2">
      <input id="_f00d0717-d08a-4918-ad51-568788e92038" label="Percent Responsible (Loan Roles)">
        <inputExpression id="_0b922041-84c3-47bf-b94c-1dd423c394ae" typeRef="number">
          <text>proposedLoan.loanRoles.percentResponsible</text>
        </inputExpression>
      </input>
      <output id="_b304292d-98e5-4dde-8fbd-0de1981c97ea" label="" name="out" typeRef="string">
        <outputValues id="UnaryTests_1yu7moy">
          <text>"Approve","Decline","Review"</text>
        </outputValues>
      </output>
      <rule id="DecisionRule_1j6jzzn">
        <inputEntry id="UnaryTests_105fhm8">
          <text></text>
        </inputEntry>
        <outputEntry id="LiteralExpression_1ucr6zl">
          <text>"Approve"</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>
</definitions>
""";

  @Test
  void shouldNotLoopEndlessly() {
    // given
    try (final var client = broker.newClientBuilder().build()) {
      // when
      final Future<?> result =
          client
              .newDeployResourceCommand()
              .addResourceBytes(dmn.getBytes(StandardCharsets.UTF_8), "bork.dmn")
              .requestTimeout(Duration.ofSeconds(30))
              .send();

      // then - expand the assert to check that it's rejected appropriately within reasonable amount
      // of time
      assertThat(result).failsWithin(Duration.ofSeconds(10)).withThrowableThat();
    }
  }
}
```

**Expected behavior**

On error, attempt to handle it via the processor which caused it, then:

1. Write a rejection and send it
2. If this causes an error, then handle it by making it more generic: omit the record value (unfortunately) and make the record which caused it as failed.
3. Send a generic error back to the gateway/client.
4. If this causes an error, mark the record as failed (so we can skip it) but omit sending anything.

This affects all supported version as far as I can tell.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Ideally, when processing a record fails with unexpected errors, `RecordProcessor.onProcessingError` can handle this gracefully. That means if it is a user command, reject the command. If it is an internal events, raise incident or ban the instance.

However, there might be unknown cases mostly triggered by specific user input that the Engine cannot handle gracefully. In that case, the stream processor will end up in an endless loop retrying the error handling. To prevent that, in this PR we added a special error handling for user commands. 
1. First try to handle the error via the `RecordProcessor,onProcessingError`  (This is the existing behavior).
2. If it fails, then instead of retrying again, StreamProcessor attempts to write a rejection record with the exception message.
3. If that also fails, then it write a rejection record with a generic message. 
4. If that also fails, fall back to end less loop.

The chances of failing at step 3 is very low because it is a record independent of the user input. It only has the record type, intent and a static string for rejection message.

The errors when processing event or internal commands do not follow the above process. This is because we cannot simply reject an internal record. Errors during  processing should translate to incidents or banning the process instance. This logic is very specific to Engine, so we cannot have a generic error handler for events in the `StreamProcessor`. So this PR do not prevent endless error loop if there are unhandled errors when processing internal commands/events.

When it is in end less loop, the partition will be marked as "UNHEALTHY". (This is the existing behavior). 

## Related issues

closes #16107 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 1]
```diff
@@ -654,4 +750,22 @@ private record BatchProcessingStepResult(
   private interface NextProcessingStep {
     void run() throws Exception;
   }
+
+  private enum ErrorHandlingPhase {
```
Comment (npepinpe) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:754]: :heart:

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java [hunk 2]
```diff
@@ -443,12 +471,78 @@ private void onError(final NextProcessingStep nextStep) {
...
+        };
+  }
+
+  private void tryRejectingIfUserCommand(final String errorMessage) {
+    final var rejectionReason = errorMessage != null ? errorMessage : "";
+    final ProcessingResultBuilder processingResultBuilder =
+        new BufferedProcessingResultBuilder(logStreamWriter::canWriteEvents);
+    // reset value to minimize any potential error loop that can be caused by writing the full
+    // record.
+    typedCommand.getValue().reset();
```
Comment (npepinpe) [inline stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:516]: :question: Relating to the initial bug, this seems to be the magic :) Do you think we lose information if we immediately reset on the first phase instead of the second or third? Do you think we lose useful diagnostic information by immediately resetting it? :thinking: 

I was initially expecting we would keep it, and write an error record as replacement in the third phase, actually. But admittedly resetting is more elegant, I'm just not sure if it would lead to reduced observability in some cases.

**Review by npepinpe — APPROVED** [review]
:tada: Just one question, but I really wasn't sure. I can't remember ever having a case where I needed to look at the value of a rejection to debug anything, but :shrug:

File: stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java (hunk 2 above)
Comment (deepthidevaki) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:516]: If all goes well, `Engine.onProcessingError` should reject with a proper error message and full details. Since this is a fall back I think it is ok to go with the safer option. 

I just quickly checked how rejection is handled in Gateway. Guess what, the value is ignored. :smile: So I think it is ok to reset the value.

Comment (npepinpe) [reply stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:516]: I was thinking for exporters, though I'm not aware anyone is consuming rejections. But the rejection code makes it clear that it was an error, so hopefully that's enough to explain the semantics :+1:
