### PR TITLE
Make reprocessing deterministic again

### LINKED ISSUE #2228: On non deterministic exception reprocessing is likely to generate different keys
With introducing the blacklisting on processing/write error we skip all follow up events of the same workflow instance (if the error occurred on a non user command).
If the exception is non deterministic this will lead to problems on reprocessing.

This means if we reprocess the event and the exception does not occur again we will process this and also all follow up events, which might end in generating different keys for all other following events.

It is also possible that an exception only occurs on reprocessing and we blacklist this instance, even if on normal processing it has worked. This also lead to different keys.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
* introduce a new error record
 * error record is written when an error happens on: `#processEvent`, `#writeEvent` or `#updateState`
 * processing will continue after error event is committed
 * on reprocessing error records are collected in a blacklist
 * when event which should be reprocessed is on blacklist than `#onError` is instead of `#processEvent` is called
 * This means even if the exception will not appear for this event on `#processEvent` again, the `#onError` is called which makes the event/error handling for reprocessing deterministic again
 * If an event is not blacklisted, the normal `#processEvent` method is called, when an exception is thrown the processing will be retried. Because, the event have been processed before successfully, on normal processing, otherwise it had been on the blacklist

closes #2228

### CODE REVIEW

File: logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java [hunk 1]
```diff
@@ -118,53 +113,107 @@ private ReProcessingStateMachine(
...
+  ActorFuture<Void> startRecover(final long snapshotPosition) {
     recoveryFuture = new CompletableActorFuture<>();
-    reprocessNextEvent();
+
+    final long startPosition = logStreamReader.getPosition();
+
+    LOG.info("Start scanning the log for error events.");
+    lastSourceEventPosition = scanLog(snapshotPosition);
+    LOG.info(
+        "Processor {} starts reprocessing, until last source event position {}",
```
Comment (saig0) [inline logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java]: This log statement is only true if `lastSourceEventPosition` is greater than `snapshotPosition`. It could be confusing to write it in other cases.

File: logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java [hunk 2]
```diff
@@ -118,53 +113,107 @@ private ReProcessingStateMachine(
...
+    long lastSourceEventPosition = -1L;
+
+    if (!isReadOnlyProcessor && logStreamReader.hasNext()) {
+      lastSourceEventPosition = snapshotPosition;
+      while (logStreamReader.hasNext()) {
+        final LoggedEvent newEvent = logStreamReader.next();
+
+        final long errorPosition = streamProcessor.getFailedPosition(newEvent);
+        if (errorPosition >= 0) {
+          LOG.info(
```
Comment (saig0) [inline logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java]: We should change the log level to `TRACE` because the statement is mainly to understand the behavior while developing.

File: logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java [hunk 3]
```diff
@@ -106,8 +99,10 @@ public static ProcessingStateMachineBuilder builder() {
 
   private final ZeebeDb zeebeDb;
   private final RetryStrategy updateStateRetryStrategy;
+  private final RetryStrategy processRetryStrategy;
 
   private final BooleanSupplier abortCondition;
+  private final Set<Long> blacklist = new HashSet<>();
```
Comment (saig0) [inline logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java]: I would like to rename the field to `failedEventPositions` which make it more clear how it is used.

File: logstreams/src/test/java/io/zeebe/logstreams/processor/ReProcessingStateMachineTest.java [hunk 4]
```diff
@@ -58,14 +62,18 @@ public void setup() {
     final ControllableActor controllableActor = new ControllableActor();
     actor = controllableActor.getActor();
 
-    when(logStreamReader.hasNext()).thenReturn(true, false);
-    when(logStreamReader.next()).thenReturn(mock(LoggedEvent.class));
+    when(logStreamReader.hasNext()).thenReturn(true, true, false, true, false);
+    loggedEvent = mock(LoggedEvent.class);
+    //    when(loggedEvent.getPosition()).thenReturn(2L);
```
Comment (saig0) [inline logstreams/src/test/java/io/zeebe/logstreams/processor/ReProcessingStateMachineTest.java]: Remove dead code.

File: logstreams/src/test/java/io/zeebe/logstreams/processor/StreamProcessorReprocessingTest.java [hunk 5]
```diff
@@ -194,7 +193,7 @@ public void shouldNotReprocessEventFromOtherProcessor() {
   }
 
   @Test
-  public void shouldCallProcessingFailedOnReprocessingError() {
+  public void shouldRetryProcessingProcessingOnReprocessingError() {
```
Comment (saig0) [inline logstreams/src/test/java/io/zeebe/logstreams/processor/StreamProcessorReprocessingTest.java]:
```suggestion
  public void shouldRetryProcessingOnReprocessingError() {
```

File: protocol/src/main/java/io/zeebe/protocol/intent/ErrorIntent.java [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.zeebe.protocol.intent;
+
+public enum ErrorIntent implements Intent {
+  UNEXPECTED_EXCEPTION((short) 0);
```
Comment (saig0) [inline protocol/src/main/java/io/zeebe/protocol/intent/ErrorIntent.java]: This intent doesn't fit well to out other intents. Maybe we can rename it to `CREATED`?

**Review by saig0 — CHANGES_REQUESTED** [review]
:+1: Just some tiny things.

File: logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java (hunk 2 above)
Comment (menski) [reply logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java]: I would vote against putting it on trace, this is also an indication to users that something is going wrong.

Comment (saig0) [reply logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java]: No, it's a log statement that something went wrong on processing. On re-processing, we just see that an error happens on processing :thinking:

File: logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java (hunk 1 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java]: Ah moved this stmt, this was the log statement we saw in the morning right :sweat_smile:

File: protocol/src/main/java/io/zeebe/protocol/intent/ErrorIntent.java (hunk 6 above)
Comment (Zelldon) [reply protocol/src/main/java/io/zeebe/protocol/intent/ErrorIntent.java]: Hm or `ERROR`?

Comment (Zelldon) [reply protocol/src/main/java/io/zeebe/protocol/intent/ErrorIntent.java]: ok

File: logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java (hunk 2 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/processor/ReProcessingStateMachine.java]: So ? Meeting in the middle ? (debug) :sweat_smile:

**Review by saig0 — APPROVED** [review]
