### PR TITLE
Flush log before committing a snapshot if raft flush is disabled

### LINKED ISSUE #11423: Improve guarantees of experimental flag to disable flush
Users can use experimental flag to disable raft flush to get better performance by compromising safety guarantees. When flush is disabled there is no guarantee that a committed record is persisted after a node crash. However, sometimes users want to choose performance over consistency and they are ok with partial data loss.  But currently with disabled flush there are scenarios where the system end up in a non-recoverable state even if users accept partial data loss from the last flush. A partition's snapshot is recoverable only if the followup events until a particular position is available in the logs. If we disable flush, we cannot guarantee that those events are persisted to disk at the time snapshot is taken. In this case, Zeebe cannot recover from that snapshot and cannot process anything on that partition. It might require manual action to clean up that partition's data and the partition can suffer a full data loss.

To allow users to use this experimental flag, while accepting that there is a chance of partial data loss across restarts, we should ensure that the journal is flushed atleast when taking the snapshot. Thus we can ensure that even if data written after last flush is lost, the partition will be able to restart from the last snapshot.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

- Flush journal before committing a snapshot to ensure that the followup events required for the snapshot is persisted to the disk.
- Remove check for explicit flush in RaftLog to allow externally triggered flush even if explicit flush is disabled.

## Related issues

closes #11423

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/storage/log/RaftLog.java [hunk 1]
```diff
@@ -169,9 +169,7 @@ public void deleteAfter(final long index) {
   }
 
   public void flush() {
-    if (flushExplicitly) {
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/storage/log/RaftLog.java:172]: > All callers of this method check if it should explicit flush. So another check here is not necessary. Besides, for forceFlush we have to ensure that it overrides shouldFlushExplicitly flag.

:thinking: Not sure why we have this check tbh, but sounds like you had also do it the otherway around? Like just having one check instead of everywhere in the callers? 

:question: BTW can we remove the property `flushExplicity` now?

File: atomix/cluster/src/main/java/io/atomix/raft/RaftServer.java [hunk 2]
```diff
@@ -301,6 +301,13 @@ default CompletableFuture<RaftServer> bootstrap(final MemberId... members) {
    */
   CompletableFuture<Void> compact();
 
+  /**
+   * Ensures that all records written to the log is flushed to disk
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/RaftServer.java:305]:
```suggestion
   * Ensures that all records written to the log are flushed to disk
```

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java [hunk 3]
```diff
@@ -512,6 +512,24 @@ public CompletableFuture<Void> compact() {
...
+   * @return a future to be completed once the log is flushed to disk
+   */
+  public CompletableFuture<Void> flushLog() {
+    final CompletableFuture<Void> future = new CompletableFuture<>();
+    threadContext.execute(
+        () -> {
+          // Only flush if explicit flush is disabled
+          if (!raftLog.shouldFlushExplicitly()) {
+            raftLog.flush();
+          }
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:527]: :thinking: Wondering whether this is really necessary? Do you think this is an issue if we do it anyway without checking?

Comment (Zelldon) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:527]: :x: If we want this, then we should also document it as part of the method documentation.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 4]
```diff
@@ -166,14 +173,16 @@ public static AsyncSnapshotDirector ofProcessingMode(
       final int partitionId,
       final StreamProcessor streamProcessor,
       final StateController stateController,
-      final Duration snapshotRate) {
+      final Duration snapshotRate,
+      final Supplier<CompletableFuture<Void>> flushLog) {
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:177]: :wrench: Supplier is a bit weird here, since were are not really interested in the result but more on just the action we execute. Maybe a Callable might make more sense.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 5]
```diff
@@ -274,13 +284,34 @@ private ActorFuture<PersistedSnapshot> snapshot(final InProgressSnapshot inProgr
                     .onComplete(lastWrittenPositionCommittedFuture)));
 
     lastWrittenPositionCommittedFuture.onComplete(
+        proceed(
+            journalFlushFuture::completeExceptionally,
+            () -> flushJournal().onComplete(journalFlushFuture)));
+
+    journalFlushFuture.onComplete(
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:291]: :+1:

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @deepthidevaki great :+1: 

I have some smaller comments and questions lets clarify them before we merge it.

File: atomix/cluster/src/main/java/io/atomix/raft/storage/log/RaftLog.java (hunk 1 above)
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/storage/log/RaftLog.java:172]: > Not sure why we have this check tbh

Didn't understand your comment. This check is not needed here because the callers are always checking this. So this was duplicate and unnecessary. In addition, now we want to ensure the it flushes even flushExplicitly is false because we are force flushing it.

Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/storage/log/RaftLog.java:172]: >  BTW can we remove the property flushExplicity now?

Not yet. Raft roles uses this flag to decide if it should flush log before commit/ack.

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java (hunk 3 above)
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:527]: > Wondering whether this is really necessary? Do you think this is an issue if we do it anyway without checking?

It is more of an optimization. Since this is running on raft thread, we try to remove an unnecessary flush that can cause an i/o operation. If flush is not disabled, then the log are flushed before commit. So there is no need to flush again here.

Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:527]: I will update the docs.

**Comment by deepthidevaki** [comment]
Thanks @Zelldon I have applied your comments. Please take a look again.

**Review by ChrisKujawa — APPROVED** [review]
Great thanks :rocket:

**Comment by deepthidevaki** [comment]
bors merge
