### PR TITLE
Don't subscribe to events when raising incident

### LINKED ISSUE #14418: Inconsitency detected in PROCESS_SUBSCRIPTION_BY_KEY
**Describe the bug**

We got alerted in SaaS, an incident was created which contains several information to it https://app.slack.com/client/T0PM0P1SA/C05TG4DLD5H/thread/C05TG4DLD5H-1695364924.679279

We can see that a role change happened and on the new leader the corruption was detected. The partition was marked as dead afterward!

**To Reproduce**
Not clear yet.

**Expected behavior**

Not detection

**Log/Stacktrace**
Error group https://console.cloud.google.com/errors/detail/CKLTyeONkqLZCg;service=zeebe;time=P7D?project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=DbLong{2251799813994826}, second=optimus_entity_created_message} in ColumnFamily PROCESS_SUBSCRIPTION_BY_KEY already exists
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyDoesNotExist(TransactionalColumnFamily.java:286) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$insert$0(TransactionalColumnFamily.java:80) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:314) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:313) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.insert(TransactionalColumnFamily.java:75) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.state.message.DbProcessMessageSubscriptionState.put(DbProcessMessageSubscriptionState.java:82) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:28) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:15) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:327) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:56) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:42) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvent(CatchEventBehavior.java:271) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToMessageEvents$7(CatchEventBehavior.java:246) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvents(CatchEventBehavior.java:246) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToEvents$4(CatchEventBehavior.java:154) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRight(Either.java:371) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToEvents(CatchEventBehavior.java:152) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnEventSubscriptionBehavior.subscribeToEvents(BpmnEventSubscriptionBehavior.java:48) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.lambda$onActivate$0(CallActivityProcessor.java:64) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.onActivate(CallActivityProcessor.java:64) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.onActivate(CallActivityProcessor.java:29) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$2(BpmnStreamProcessor.java:144) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:143) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:92) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:89) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.incident.ResolveIncidentProcessor.lambda$attemptToContinueProcessProcessing$0(ResolveIncidentProcessor.java:105) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.incident.ResolveIncidentProcessor.attemptToContinueProcessProcessing(ResolveIncidentProcessor.java:103) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.incident.ResolveIncidentProcessor.processRecord(ResolveIncidentProcessor.java:81) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:353) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.3.0-alpha6
- Configuration:

### PR DESCRIPTION
**Pull request by korthout**
## Description

This resolves a critical bug, where certain flow nodes subscribe to events when raising an incident. This bug would surface when resolving the incident, where the flow-node subscribes again to those events.

For example, a call activity may fail to activate due to the called process not being found. If the call activity has a boundary event attached, it would attempt to subscribe twice to it when resolving the respective incident.

The pull request adds tests for:
- call activity
- job worker tasks

## Related issues

closes #14418

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/task/JobWorkerTaskProcessor.java [hunk 1]
```diff
@@ -50,10 +50,13 @@ public Class<ExecutableJobWorkerTask> getType() {
...
-        .flatMap(ok -> eventSubscriptionBehavior.subscribeToEvents(element, context))
-        .flatMap(ok -> jobBehavior.createNewJob(context, element))
+        .flatMap(ok -> jobBehavior.evaluateJobExpressions(element, context))
+        .flatMap(j -> eventSubscriptionBehavior.subscribeToEvents(element, context).map(ok -> j))
         .ifRightOrLeft(
-            ok -> stateTransitionBehavior.transitionToActivated(context),
+            jobProperties -> {
+              jobBehavior.createNewJob(context, element, jobProperties);
+              stateTransitionBehavior.transitionToActivated(context);
+            },
```
Comment (remcowesterhoud) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/task/JobWorkerTaskProcessor.java:59]: 👍 Very clear what happens now, I like it.

File: engine/src/test/java/io/camunda/zeebe/engine/util/JobWorkerElementBuilderProvider.java [hunk 2]
```diff
@@ -30,6 +31,14 @@ public Stream<? extends Arguments> provideArguments(final ExtensionContext exten
     return builders().map(Arguments::of);
   }
 
+  public static List<BpmnElementType> getSupportedActivities() {
+    return List.of(
+        BpmnElementType.SERVICE_TASK,
+        BpmnElementType.BUSINESS_RULE_TASK,
+        BpmnElementType.SCRIPT_TASK,
+        BpmnElementType.SEND_TASK);
```
Comment (remcowesterhoud) [inline engine/src/test/java/io/camunda/zeebe/engine/util/JobWorkerElementBuilderProvider.java:39]: 🔧 I'm a bit confused about this list of tasks. This is the `JobWorkerElementTest`. A `BUSINESS_RULE_TASK` and a `SCRIPT_TASK` don't create jobs. Meanwhile, `USER_TASK` does but it's not part of this list.

**Review by remcowesterhoud — APPROVED** [review]
Thanks @korthout! Your commit messages helped a lot with this review. I'm amazed we didn't catch this earlier 😄

Please have a look at my comment 👀  Feel free to merge after.

File: engine/src/test/java/io/camunda/zeebe/engine/util/JobWorkerElementBuilderProvider.java (hunk 2 above)
Comment (korthout) [reply engine/src/test/java/io/camunda/zeebe/engine/util/JobWorkerElementBuilderProvider.java:39]: 👍 Business rule task and script task have multiple implementations. Users can choose the implementation in Modeler. If they choose Job Worker, then they behave as a service task, which allows users to use their own script engine or their own business rule processor.

🤔 I'm also surprised to see that user task is missing. The reason is that it does not implement the same model, i.e. users cannot define the job type. It's just an implementation choice that we've implemented user tasks with a job for now.

**Comment by korthout** [comment]
bors merge

File: engine/src/test/java/io/camunda/zeebe/engine/util/JobWorkerElementBuilderProvider.java (hunk 2 above)
Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/util/JobWorkerElementBuilderProvider.java:39]: Ah that makes sense. Thanks for the explanation 👍

**Comment by korthout** [comment]
I expected this 😅
