### PR TITLE
fix(engine): catch error event on multi-instance activity

### LINKED ISSUE #4601: An error event is not caught by a boundary event on a multi-instance subprocess
**Describe the bug**
When an error event is thrown inside a multi-instance subprocess (e.g. by an error end event) then the error event is not caught by an error boundary event that is attached to the sub-process.

Instead, the workflow instance is stuck in the error event (i.e. the last event is `ELEMENT_ACTIVATED` of the error event).

image

image

**To Reproduce**
* deploy a workflow with a multi-instance subprocess and an error boundary event attach to it 
* create an instance of this workflow 
* throw the error event by an error end event or from a job worker
* verify that the boundary event is not activated

**Expected behavior**
The multi-instance subprocess is terminated and the error boundary is activated.

**Log/Stacktrace**

<details><summary>BPMN workflow</summary>
 <p>

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_0usf83o" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Zeebe Modeler" exporterVersion="0.9.0">
  <bpmn:process id="error-event" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_09tk2nz</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:subProcess id="Activity_105nqgn">
      <bpmn:incoming>Flow_09tk2nz</bpmn:incoming>
      <bpmn:outgoing>Flow_1vpp7gz</bpmn:outgoing>
      <bpmn:multiInstanceLoopCharacteristics>
        <bpmn:extensionElements>
          <zeebe:loopCharacteristics inputCollection="=[1,2]" />
        </bpmn:extensionElements>
      </bpmn:multiInstanceLoopCharacteristics>
      <bpmn:startEvent id="Event_11myone">
        <bpmn:outgoing>Flow_0hhyvgt</bpmn:outgoing>
      </bpmn:startEvent>
      <bpmn:sequenceFlow id="Flow_0hhyvgt" sourceRef="Event_11myone" targetRef="Event_0uummr5" />
      <bpmn:endEvent id="Event_0uummr5" name="error">
        <bpmn:incoming>Flow_0hhyvgt</bpmn:incoming>
        <bpmn:errorEventDefinition id="ErrorEventDefinition_11tkq8s" errorRef="Error_0kvygiz" />
      </bpmn:endEvent>
    </bpmn:subProcess>
    <bpmn:sequenceFlow id="Flow_09tk2nz" sourceRef="StartEvent_1" targetRef="Activity_105nqgn" />
    <bpmn:endEvent id="Event_0zv88hy">
      <bpmn:incoming>Flow_0wq5iy1</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0wq5iy1" sourceRef="Event_11dtgd1" targetRef="Event_0zv88hy" />
    <bpmn:boundaryEvent id="Event_11dtgd1" name="error" attachedToRef="Activity_105nqgn">
      <bpmn:outgoing>Flow_0wq5iy1</bpmn:outgoing>
      <bpmn:errorEventDefinition id="ErrorEventDefinition_0cj4bdn" errorRef="Error_0kvygiz" />
    </bpmn:boundaryEvent>
    <bpmn:endEvent id="Event_0r324uz">
      <bpmn:incoming>Flow_1vpp7gz</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1vpp7gz" sourceRef="Activity_105nqgn" targetRef="Event_0r324uz" />
  </bpmn:process>
  <bpmn:error id="Error_0kvygiz" name="error" errorCode="error" />
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="error-event">
      <bpmndi:BPMNEdge id="Flow_09tk2nz_di" bpmnElement="Flow_09tk2nz">
        <di:waypoint x="215" y="177" />
        <di:waypoint x="270" y="177" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0wq5iy1_di" bpmnElement="Flow_0wq5iy1">
        <di:waypoint x="470" y="295" />
        <di:waypoint x="470" y="360" />
        <di:waypoint x="602" y="360" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1vpp7gz_di" bpmnElement="Flow_1vpp7gz">
        <di:waypoint x="550" y="177" />
        <di:waypoint x="612" y="177" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0r324uz_di" bpmnElement="Event_0r324uz">
        <dc:Bounds x="612" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0zv88hy_di" bpmnElement="Event_0zv88hy">
        <dc:Bounds x="602" y="342" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_105nqgn_di" bpmnElement="Activity_105nqgn" isExpanded="true">
        <dc:Bounds x="270" y="77" width="280" height="200" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_0hhyvgt_di" bpmnElement="Flow_0hhyvgt">
        <di:waypoint x="346" y="177" />
        <di:waypoint x="452" y="177" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_11myone_di" bpmnElement="Event_11myone">
        <dc:Bounds x="310" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_197wtg8_di" bpmnElement="Event_0uummr5">
        <dc:Bounds x="452" y="159" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="458" y="202" width="24" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0jt56mw_di" bpmnElement="Event_11dtgd1">
        <dc:Bounds x="452" y="259" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="478" y="302" width="24" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

</p>
</details>

<details><summary>Audit Log of Workflow Instance</summary>
 <p>

Element Id | Element Instance Key | Flow Scope Key | State | Element Name | BPMN Element Type | Time
-- | -- | -- | -- | -- | -- | --
error-event | 2251799813686360 | -1 | ELEMENT_ACTIVATING |   | PROCESS | 2020-05-26T07:46:43.704Z
error-event | 2251799813686360 | -1 | ELEMENT_ACTIVATED |   | PROCESS | 2020-05-26T07:46:43.715Z
StartEvent_1 | 2251799813686362 | 2251799813686360 | ELEMENT_ACTIVATING |   | START_EVENT | 2020-05-26T07:46:43.736Z
StartEvent_1 | 2251799813686362 | 2251799813686360 | ELEMENT_ACTIVATED |   | START_EVENT | 2020-05-26T07:46:43.743Z
StartEvent_1 | 2251799813686362 | 2251799813686360 | ELEMENT_COMPLETING |   | START_EVENT | 2020-05-26T07:46:43.760Z
StartEvent_1 | 2251799813686362 | 2251799813686360 | ELEMENT_COMPLETED |   | START_EVENT | 2020-05-26T07:46:43.766Z
Flow_09tk2nz | 2251799813686363 | 2251799813686360 | SEQUENCE_FLOW_TAKEN |   | SEQUENCE_FLOW | 2020-05-26T07:46:43.775Z
Activity_105nqgn | 2251799813686364 | 2251799813686360 | ELEMENT_ACTIVATING |   | MULTI_INSTANCE_BODY | 2020-05-26T07:46:43.795Z
Activity_105nqgn | 2251799813686364 | 2251799813686360 | ELEMENT_ACTIVATED |   | MULTI_INSTANCE_BODY | 2020-05-26T07:46:43.807Z
Activity_105nqgn | 2251799813686365 | 2251799813686364 | ELEMENT_ACTIVATING |   | SUB_PROCESS | 2020-05-26T07:46:43.819Z
Activity_105nqgn | 2251799813686367 | 2251799813686364 | ELEMENT_ACTIVATING |   | SUB_PROCESS | 2020-05-26T07:46:43.819Z
Activity_105nqgn | 2251799813686365 | 2251799813686364 | ELEMENT_ACTIVATED |   | SUB_PROCESS | 2020-05-26T07:46:43.831Z
Activity_105nqgn | 2251799813686367 | 2251799813686364 | ELEMENT_ACTIVATED |   | SUB_PROCESS | 2020-05-26T07:46:43.838Z
Event_11myone | 2251799813686369 | 2251799813686365 | ELEMENT_ACTIVATING |   | START_EVENT | 2020-05-26T07:46:43.850Z
Event_11myone | 2251799813686370 | 2251799813686367 | ELEMENT_ACTIVATING |   | START_EVENT | 2020-05-26T07:46:43.856Z
Event_11myone | 2251799813686369 | 2251799813686365 | ELEMENT_ACTIVATED |   | START_EVENT | 2020-05-26T07:46:43.856Z
Event_11myone | 2251799813686370 | 2251799813686367 | ELEMENT_ACTIVATED |   | START_EVENT | 2020-05-26T07:46:43.867Z
Event_11myone | 2251799813686369 | 2251799813686365 | ELEMENT_COMPLETING |   | START_EVENT | 2020-05-26T07:46:43.867Z
Event_11myone | 2251799813686370 | 2251799813686367 | ELEMENT_COMPLETING |   | START_EVENT | 2020-05-26T07:46:43.881Z
Event_11myone | 2251799813686369 | 2251799813686365 | ELEMENT_COMPLETED |   | START_EVENT | 2020-05-26T07:46:43.881Z
Event_11myone | 2251799813686370 | 2251799813686367 | ELEMENT_COMPLETED |   | START_EVENT | 2020-05-26T07:46:43.894Z
Flow_0hhyvgt | 2251799813686371 | 2251799813686365 | SEQUENCE_FLOW_TAKEN |   | SEQUENCE_FLOW | 2020-05-26T07:46:43.894Z
Flow_0hhyvgt | 2251799813686372 | 2251799813686367 | SEQUENCE_FLOW_TAKEN |   | SEQUENCE_FLOW | 2020-05-26T07:46:43.906Z
Event_0uummr5 | 2251799813686373 | 2251799813686365 | ELEMENT_ACTIVATING | error | END_EVENT | 2020-05-26T07:46:43.913Z
Event_0uummr5 | 2251799813686374 | 2251799813686367 | ELEMENT_ACTIVATING | error | END_EVENT | 2020-05-26T07:46:43.918Z
Event_0uummr5 | 2251799813686373 | 2251799813686365 | ELEMENT_ACTIVATED | error | END_EVENT | 2020-05-26T07:46:43.918Z
Event_0uummr5 | 2251799813686374 | 2251799813686367 | ELEMENT_ACTIVATED | error | END_EVENT | 2020-05-26T07:46:43.935Z

</p>
</details>

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.23.0
 - Configuration: [e.g. exporters etc.]

### PR DESCRIPTION
**Pull request by saig0**
## Description

* be aware of multi-instance activities when looking for an error catch event
* add new helper method to resolve the element based on a given BPMN element type to handle multi-instance activities

## Related issues

closes #4601 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: engine/src/main/java/io/zeebe/engine/nwe/behavior/BpmnStateTransitionBehavior.java [hunk 1]
```diff
@@ -255,14 +254,17 @@ public void onElementTerminated(
     containerProcessor.onChildTerminated(containerScope, containerContext, childContext);
   }
 
-  private ExecutableCallActivity getParentWorkflowScope(
+  private ExecutableFlowElement getParentWorkflowScope(
```
Comment (korthout) [inline engine/src/main/java/io/zeebe/engine/nwe/behavior/BpmnStateTransitionBehavior.java:257]: I understand that the `getElementById` now needs an elementType, but this should always be `CALL_ACTIVITY` for this method. I also think that the return type can be specified to ExecutableCallActivity, as other elements should not be provided by this method.

File: engine/src/main/java/io/zeebe/engine/nwe/behavior/BpmnStateTransitionBehavior.java [hunk 2]
```diff
@@ -255,14 +254,17 @@ public void onElementTerminated(
...
       final BpmnElementContext callActivityContext, final BpmnElementContext childContext) {
     final var workflowKey = callActivityContext.getWorkflowKey();
     final var elementId = callActivityContext.getElementId();
+    final var elementType = callActivityContext.getBpmnElementType();
```
Comment (korthout) [inline engine/src/main/java/io/zeebe/engine/nwe/behavior/BpmnStateTransitionBehavior.java:261]: So I would change this to:
```suggestion
    final var elementType = BpmnElementType.CALL_ACTIVITY;
```

**Review by korthout — CHANGES_REQUESTED** [review]
Fix looks good, but I have a small comment

File: engine/src/main/java/io/zeebe/engine/nwe/behavior/BpmnStateTransitionBehavior.java (hunk 2 above)
Comment (saig0) [reply engine/src/main/java/io/zeebe/engine/nwe/behavior/BpmnStateTransitionBehavior.java:261]: :+1:

**Comment by saig0** [comment]
@korthout, please have a second look. I applied your hints :wink:

**Review by korthout — APPROVED** [review]
LGTM 👍
