### PR TITLE
Return UNAVAILABLE on publish message and create workflow instance commands if no partitions are known

### LINKED ISSUE #5783: Error logged on no topology available in gateway and INTERNAL status returned to client
**Describe the bug**

Found from the error reporting tool: https://console.cloud.google.com/errors/COfayLr3scKxFA?service=zeebe&time=P30D&project=camunda-cloud-240911

We currently return INTERNAL to clients if there is no topology available to the gateway. This is misleading, as INTERNAL indicates an unexpected and possibly unrecoverable error occurred in the gateway, which is not the case here since it is possible for the gateway to temporarily have no topology. We should return UNAVAILABLE to indicate to clients that this is most likely recoverable by retrying later on.

At the same time, this should not be logged as an error, as this is directed at the client; we can simply lower the log level to trace here.

**To Reproduce**

Start a gateway but don't connect it to a broker; send a create workflow instance command (or any which goes through `RequestRetryHandler`), and you will trigger this.

**Expected behavior**

The client receives the UNAVAILABLE error code, and the log level is lowered to trace.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.zeebe.gateway.cmd.NoTopologyAvailableException: Expected to send the request to a partition in the topology, but gateway does not know broker topology. Please try again later. If the error persists contact your zeebe operator.
	at io.zeebe.gateway.impl.broker.RequestRetryHandler.sendRequestInternal(RequestRetryHandler.java:81) [zeebe-gateway-0.24.4.jar:0.24.4]
	at io.zeebe.gateway.impl.broker.RequestRetryHandler.sendRequest(RequestRetryHandler.java:50) [zeebe-gateway-0.24.4.jar:0.24.4]
	at io.zeebe.gateway.EndpointManager.sendRequestWithRetryPartitions(EndpointManager.java:328) [zeebe-gateway-0.24.4.jar:0.24.4]
	at io.zeebe.gateway.EndpointManager.createWorkflowInstance(EndpointManager.java:151) [zeebe-gateway-0.24.4.jar:0.24.4]
	at io.zeebe.gateway.protocol.GatewayGrpc$MethodHandlers.invoke(GatewayGrpc.java:1500) [zeebe-gateway-protocol-impl-0.24.4.jar:0.24.4]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [grpc-stub-1.30.2.jar:1.30.2]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [grpc-api-1.30.2.jar:1.30.2]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [grpc-api-1.30.2.jar:1.30.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820) [grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.30.2.jar:1.30.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

</p>
</details>

**Environment:**
 - OS: official docker image
 - Zeebe Version: 0.24.4
 - Configuration: Camunda Cloud

### LINKED ISSUE #5788: Deadline exceeded on publish message due to ArithmeticException
**Describe the bug**

It's possible to sometimes have a non-null topology with no known partitions. This results in a repeated division by zero error when trying to determine the destination partition of a message, which eventually is returned as a DEADLINE_EXCEEDED error as the transport retries the request.

**To Reproduce**

In order to reproduce it, start a gateway with no brokers connected to it, and wait enough time for a topology to exist; it will have no partitions nor brokers, but will not be null. At this point, send a publish message command, and this error will pop up.

**Expected behavior**

If there are no known partitions, we should return UNAVAILABLE to the client, and on the gateway side, log this as TRACE.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
[gateway-scheduler-zb-actors-0] ERROR io.zeebe.util.actor - Uncaught exception in 'io.zeebe.gateway.impl.broker.BrokerRequestManager' in phase 'STARTED'. Continuing with next job.
java.lang.ArithmeticException: / by zero
	at io.zeebe.protocol.impl.SubscriptionUtil.getSubscriptionPartitionId(SubscriptionUtil.java:43) ~[classes/:?]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.determinePartitionIdForPublishMessageRequest(BrokerRequestManager.java:238) ~[classes/:?]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.determineBrokerNodeIdProvider(BrokerRequestManager.java:212) ~[classes/:?]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.sendRequestInternal(BrokerRequestManager.java:117) ~[classes/:?]
	at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$1(BrokerRequestManager.java:105) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [classes/:?]
19:04:46.872 [gateway-scheduler-zb-actors-0] DEBUG io.zeebe.gateway - Expected to handle gRPC request, but request timed out between gateway and broker
java.util.concurrent.TimeoutException: Request timed out after PT15S
	at io.zeebe.transport.impl.RequestContext.timeout(RequestContext.java:112) ~[classes/:?]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.timeoutFuture(AtomixClientTransportAdapter.java:218) ~[classes/:?]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestInternal$1(AtomixClientTransportAdapter.java:84) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [classes/:?]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [classes/:?]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [classes/:?]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [classes/:?]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [classes/:?]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [classes/:?]
```

</p>
</details>

**Environment:**
 - OS: official docker image
 - Zeebe Version: 0.26.0-SNAPSHOT
 - Configuration: default

### LINKED ISSUE #5789: Resource exhausted on create workflow instance if no topology available
**Describe the bug**

When sending a create workflow instance command, if the gateway does not know any partitions, it will return RESOURCE_EXHAUSTED even though it didn't actually try to send anything. The correct code to send here would be UNAVAILABLE to accurately reflect the state of the system.

**To Reproduce**

Start a gateway with no brokers connected, wait until there is a non-null topology (but it will have no partitions), then send a create workflow instance command. :boom: 

**Expected behavior**

As a client I expect to get UNAVAILABLE, as there are no brokers to forward requests to; resources exhausted makes it sound like there are, but they are currently overloaded.

**Environment:**
 - OS: official docker image
 - Zeebe Version: 0.26.0-SNAPSHOT
 - Configuration: default config

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR ensures we return UNAVAILABLE to clients on publish message and workflow instance creation commands if the gateway does not know any partitions. It also introduces a new system test for the gateway to check these cases, which can be extended to add more cases. 

## Related issues

closes #5783 
closes #5788 
closes #5789 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java [hunk 1]
```diff
@@ -86,6 +87,10 @@ private Status mapErrorToStatus(final Throwable error, final Logger logger) {
       // partitions - it will then also occur when back pressure kicks in, leading to a large burst
       // of error logs that is, in fact, expected
       logger.trace("Expected to handle gRPC request, but all retries have been exhausted", error);
+    } else if (error instanceof NoTopologyAvailableException) {
+      builder.setCode(Code.UNAVAILABLE_VALUE).setMessage(error.getMessage());
+      logger.trace(
+          "Expected to handle gRPC request, but the gateway does not know any partitions yet");
```
Comment (Zelldon) [inline gateway/src/main/java/io/zeebe/gateway/grpc/GrpcErrorMapper.java:93]:
```suggestion
          "Expected to handle gRPC request, but the gateway does not know any partitions yet", error);
```

File: gateway/src/test/java/io/zeebe/gateway/api/UnavailableBrokersTest.java [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+import java.util.concurrent.TimeUnit;
+import java.util.stream.Stream;
+import org.junit.jupiter.api.AfterAll;
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.parallel.Execution;
+import org.junit.jupiter.api.parallel.ExecutionMode;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.MethodSource;
+
+@Execution(ExecutionMode.CONCURRENT)
```
Comment (Zelldon) [inline gateway/src/test/java/io/zeebe/gateway/api/UnavailableBrokersTest.java:36]: What does this?

**Review by ChrisKujawa — APPROVED** [review]
No weekend for you ? :sweat_smile: 
Thanks @npepinpe for fixing this so quickly! :+1: I think https://github.com/zeebe-io/zeebe/issues/5702 is then also fixed or?

File: gateway/src/test/java/io/zeebe/gateway/api/UnavailableBrokersTest.java (hunk 2 above)
Comment (npepinpe) [reply gateway/src/test/java/io/zeebe/gateway/api/UnavailableBrokersTest.java:36]: Tests are executed concurrently instead of one after the other. Should be used only when we are sure that they don't interfere between each other :slightly_smiling_face:

Comment (Zelldon) [reply gateway/src/test/java/io/zeebe/gateway/api/UnavailableBrokersTest.java:36]: thanks :)

**Comment by npepinpe** [comment]
> No weekend for you ? :sweat_smile:
Actually I was showing Zeebe to a friend, trying to do a little demo app with him, and I found a bunch of small issues surrounding the gateway :see_no_evil: 

> Thanks @npepinpe for fixing this so quickly! +1 I think #5702 is then also fixed or?
I don't think I fixed that, really - right now if I add a test case for deployment, I get DEADLINE_EXCEEDED. You can see it in `BrokerRequestManager:221` that we explicitly set the deployment partition if there's no topology, so yeah... But it should be easier to fix now, and extend with this test.

**Comment by npepinpe** [comment]
btw, I wasn't sure to back port this because we didn't back port the GrpcErrorMapper and all this stuff, so it would be a pain to do so; if we want to backport this fix we'd need to backport that PR as well. Which imo we should do, but I could use a second opinion :slightly_smiling_face:

**Comment by Zelldon** [comment]
I vote for backporting both
