### PR TITLE
fix: don't fail on startup if disk usage monitor is disabled

### LINKED ISSUE #10735: Broker startup fails when disk usage monitoring is disabled
**Describe the bug**

As [reported by the community](https://camunda-platform.slack.com/archives/C6WGNHV2A/p1665997293516809):

Starting a broker with disk usage monitoring disabled fails with an NPE while starting the command API.

**To Reproduce**

Set `ZEEBE_BROKER_DATA_DISKUSAGEMONITORINGENABLED` to false and start a broker

**Expected behavior**

Broker startup be successful, regardless of whether disk usage monitoring is enabled or not.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2022-10-17 10:47:11.339 [Broker-0-Startup] [Broker-0-zb-actors-1] WARN 
      io.camunda.zeebe.broker.system - Aborting startup process due to exception during step Command API
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.broker.system.monitoring.DiskSpaceUsageMonitor.addDiskUsageListener(io.camunda.zeebe.broker.system.monitoring.DiskSpaceUsageListener)" because the return value of "io.camunda.zeebe.broker.bootstrap.BrokerStartupContext.getDiskSpaceUsageMonitor()" is null
	at io.camunda.zeebe.broker.bootstrap.CommandApiServiceStep.lambda$startCommandApiService$2(CommandApiServiceStep.java:91) ~[zeebe-broker-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.forwardExceptions(AbstractBrokerStartupStep.java:71) ~[zeebe-broker-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.lambda$proceed$3(AbstractBrokerStartupStep.java:87) ~[zeebe-broker-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
2022-10-17 10:47:11.355 [] [main] ERROR
      io.camunda.zeebe.broker.system - Failed to start broker 0!
java.util.concurrent.ExecutionException: Startup failed in the following steps: [Command API]. See suppressed exceptions for details.
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:142) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:109) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:21) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:198) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:101) ~[zeebe-broker-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23) ~[zeebe-util-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.broker.Broker.start(Broker.java:83) ~[zeebe-broker-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:92) ~[camunda-zeebe-8.1.0.jar:8.1.0]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.4.jar:2.7.4]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:82) ~[camunda-zeebe-8.1.0.jar:8.1.0]
Caused by: io.camunda.zeebe.scheduler.startup.StartupProcessException: Startup failed in the following steps: [Command API]. See suppressed exceptions for details.
	at io.camunda.zeebe.scheduler.startup.StartupProcess.aggregateExceptionsSynchronized(StartupProcess.java:282) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:183) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:167) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	Suppressed: io.camunda.zeebe.scheduler.startup.StartupProcessStepException: Bootstrap step Command API failed
		at io.camunda.zeebe.scheduler.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:185) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:167) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	Caused by: java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.broker.system.monitoring.DiskSpaceUsageMonitor.addDiskUsageListener(io.camunda.zeebe.broker.system.monitoring.DiskSpaceUsageListener)" because the return value of "io.camunda.zeebe.broker.bootstrap.BrokerStartupContext.getDiskSpaceUsageMonitor()" is null
		at io.camunda.zeebe.broker.bootstrap.CommandApiServiceStep.lambda$startCommandApiService$2(CommandApiServiceStep.java:91) ~[zeebe-broker-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.forwardExceptions(AbstractBrokerStartupStep.java:71) ~[zeebe-broker-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.lambda$proceed$3(AbstractBrokerStartupStep.java:87) ~[zeebe-broker-8.1.0.jar:8.1.0]
		at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
		... 6 more```

</p>
</details>

**Environment:**
- OS: <!-- [e.g. Linux] -->
- Zeebe Version: 8.1.0
- Configuration: `ZEEBE_BROKER_DATA_DISKUSAGEMONITORINGENABLED=false`

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Some components try to register themselves as disk usage listener on startup. When disk usage monitoring was disabled, these components would fail with an NPE during startup.

Instead of checking for null everywhere the monitor is used, we register a no-op disk usage monitor that other components can use for registering but that won't deliver any notifications.

closes #10735

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I tested manually and considered adding a test but writing a full integration test for this specific case felt a bit heavy-handed. Happy to be convinced otherwise though :)

File: broker/src/main/java/io/camunda/zeebe/broker/bootstrap/DiskSpaceUsageMonitorStep.java [hunk 1]
```diff
@@ -23,14 +27,43 @@ void startupInternal(
       final ActorFuture<BrokerStartupContext> startupFuture) {
 
     final var data = brokerStartupContext.getBrokerConfiguration().getData();
+
+    if (!data.isDiskUsageMonitoringEnabled()) {
+      brokerStartupContext.setDiskSpaceUsageMonitor(new DisabledDiskUsageMonitor());
```
Comment (deepthidevaki) [inline broker/src/main/java/io/camunda/zeebe/broker/bootstrap/DiskSpaceUsageMonitorStep.java:32]: :+1:

File: broker/src/main/java/io/camunda/zeebe/broker/bootstrap/DiskSpaceUsageMonitorStep.java [hunk 2]
```diff
@@ -23,14 +27,43 @@ void startupInternal(
...
+  }
+
+  @Override
+  void shutdownInternal(
+      final BrokerStartupContext brokerShutdownContext,
+      final ConcurrencyControl concurrencyControl,
+      final ActorFuture<BrokerStartupContext> shutdownFuture) {
+
+    final var diskSpaceUsageMonitor = brokerShutdownContext.getDiskSpaceUsageMonitor();
+    if (diskSpaceUsageMonitor instanceof DiskSpaceUsageMonitorActor actor) {
```
Comment (deepthidevaki) [inline broker/src/main/java/io/camunda/zeebe/broker/bootstrap/DiskSpaceUsageMonitorStep.java:47]: :wrench: It would be better to add a `close` method to the `DiskSpaceUsageMonitorInterface` interface.

**Review by deepthidevaki — APPROVED** [review]
LGTM. Please take a look at the comment before merging.

File: broker/src/main/java/io/camunda/zeebe/broker/bootstrap/DiskSpaceUsageMonitorStep.java (hunk 2 above)
Comment (oleschoenburg) [reply broker/src/main/java/io/camunda/zeebe/broker/bootstrap/DiskSpaceUsageMonitorStep.java:47]: Yeah, good point :+1: I've just added an `extends AsyncClosable` to the `DiskUsageMonitor` interface to implement this.
