### PR TITLE
fix(broker-core): Convert numeric correlation key to string

### LINKED ISSUE #1667: Message correlation with numerical correlation key not working as expected
At the moment the docs claim that it is possible to extract a numerical correlation key from the payload.

> The value must be either a string or a number.
https://docs.zeebe.io/bpmn-workflows/message-events.html

Although it is _possible_ to extract a numerical value, it is nearly impossible for the user to publish a message with this correlation key. The user would have to transform a byte array containing the numerical value to a string value, which is *not* the string representation of the number.

First we should remove the number part from the docs section to not confuse users, as they probably expect a different behavior. Then we should decide how we want to support numbers in a user friendly way.

Options:
1. Transform numerical value in broker to String representation, i.e. `123` -> `"123"`, so the user can publish a message with the String representation using the existing client API
1. Allow users to publish a byte array as correlation key, this would make the client API hard to use or requires some magic in the clients
1. Extend client API to support correlation key as string or number, which might be not intuitive to use and requires the user to know which type is expected in the workflow instance 

Personally I would prefer option 1 from a user perspective, but this should be discussed before implementing.

### PR DESCRIPTION
**Pull request by miguelpires**
Takes a numeric correlation key from the payload and converts it to a String such that it can be matched with an equivalent String correlation key from a published message.

closes #1667

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9292073bddf54b0e57074234e79753338427fd79
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

File: broker-core/src/main/java/io/zeebe/broker/workflow/processor/CatchEventOutput.java [hunk 1]
```diff
@@ -210,7 +213,11 @@ private DirectBuffer extractCorrelationKey(
       }
 
       if (result.isLong()) {
-        return result.getLongAsBuffer();
+        final DirectBuffer buffer = result.getLongAsBuffer();
```
Comment (saig0) [inline broker-core/src/main/java/io/zeebe/broker/workflow/processor/CatchEventOutput.java]: I think we can move this logic into `QueryResults`.

File: docs/src/bpmn-workflows/message-events.md [hunk 2]
```diff
@@ -11,7 +11,7 @@ A message can be referenced by one or more message events. It holds the informat
 * the name of the message
 * the correlation key
 
-The correlation key is specified as JSON Path expression. It is evaluated when the message event is entered and extracts the value from the workflow instance payload. The value must be a string. If the correlation key can't be resolved or it is not a string then an incident is created.
+The correlation key is specified as [JSON Path](reference/json-conditions.html) expression. It is evaluated when the message event is entered and extracts the value from the workflow instance payload. The value must be either a string or a number.
```
Comment (saig0) [inline docs/src/bpmn-workflows/message-events.md]: I think a sentence is removed by merging ;)

**Review by saig0 — CHANGES_REQUESTED** [review]

**Comment by MiguelPires** [comment]
Moved the conversion logic into the getLongAsString method in QueryResult and deleted getLongAsBuffer since it was no longer used. Also modified the tests and the documentation to reflect the changes.

**Review by saig0 — APPROVED** [review]
