### PR TITLE
Detect inconsistent state of local member in the topology

### LINKED ISSUE #16312: A broker can detect topology is overwritten forcefully and fix its local state
When a broker is force-removed from a cluster, it might not receive the topology update while it was disconnected from the network. The force removal operation would have overwritten its MemberState without its knowledge. When this broker is reconnected to the cluster, it should detect that it's state is updated. That means it may not be replicating the partitions as given in its outdated ClusterTopology. In that case it should either
- Persists the new topology and crash so that on restart it uses the correct topology
- Persists the new topology and graceful shutdown so that on restart it uses the correct topology 
- Persists the new topology and restart all partitions properly according to the new topology.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Usually, a broker is force-remove when it is unreachable. However, due to intermittent network issues we may have to force fully remove a broker. In that case, that broker may try to connect back to the cluster when the network is available. The partitions which are already running in that broker will repeatedly send send poll requests to the rest of the replicas, thus spamming them. Since it is already removed, the other replicas reject the request and will never sent a heartbeat or updated configuration.  This is not a dangerous situation, but can create noisy logs and difficult to debug other related issues.

To prevent this situation, a broker shuts down gracefully when it detects an inconsistent topology. The local topology is inconsistent with the received one if the received one is of higher version and the state of this member in the topology is different. That means it has been force-fully updated by some other broker. 

When the spring application is shutdown gracefully, the kubernetes pod is also shutdown and will be restarted. This has been verified manually. When the broker is restarted, it uses the new topology in which this broker is not part of and not having any partitions. As a result it doesn't start any partitions and remain in an "unready" state. The pod has to be manually removed. This is ok because force-remove is only used when the broker has to be removed from the cluster. 

## Related issues

closes #16312 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/bootstrap/PartitionManagerStep.java [hunk 1]
```diff
@@ -76,5 +93,25 @@ void shutdownInternal(
             shutdownFuture.complete(brokerShutdownContext);
           }
         });
+
+    brokerShutdownContext.getClusterTopology().removeTopologyChangeListener();
+  }
+
+  private void shutdownOnInconsistentTopology(
```
Comment (deepthidevaki) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/bootstrap/PartitionManagerStep.java:100]: I put this here because later we can replace the shutdown with stopping all partitions and restarting based on the new topology.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/bootstrap/PartitionManagerStep.java [hunk 2]
```diff
@@ -7,11 +7,19 @@
...
+import io.camunda.zeebe.broker.SpringBrokerBridge;
 import io.camunda.zeebe.broker.partitioning.PartitionManagerImpl;
 import io.camunda.zeebe.scheduler.ConcurrencyControl;
 import io.camunda.zeebe.scheduler.future.ActorFuture;
+import io.camunda.zeebe.topology.state.ClusterTopology;
+import org.slf4j.Logger;
 
 final class PartitionManagerStep extends AbstractBrokerStartupStep {
+  private static final Logger LOGGER = Loggers.SYSTEM_LOGGER;
+  private static final int ERROR_CODE_ON_INCONSISTENT_TOPOLOGY = 3;
```
Comment (oleschoenburg) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/bootstrap/PartitionManagerStep.java:21]: :question: Any particular reason for using `3`? In `VirtualMachineErrorHandler` we use 156 (ascii code Z + B)

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/dynamic/ForceScaleDownBrokersTest.java [hunk 3]
```diff
@@ -98,4 +101,28 @@ TestCluster createCluster(final int clusterSize, final int replicationFactor) {
     cluster.awaitCompleteTopology();
     return cluster;
   }
+
+  @Test
+  void shouldForceRemoveBrokerWhenBrokerIsUp() {
```
Comment (oleschoenburg) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/clustering/dynamic/ForceScaleDownBrokersTest.java:106]: :star_struck: Really nice test case :+1:

**Review by lenaschoenburg — APPROVED** [review]

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/bootstrap/PartitionManagerStep.java (hunk 2 above)
Comment (deepthidevaki) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/bootstrap/PartitionManagerStep.java:21]: Some exit codes have [commonly used meaning](https://tldp.org/LDP/abs/html/exitcodes.html). 3 is not defined in that sense. So no other reason. What is the significance of 156? Does it makes sense to re-use it here?

File: dist/src/main/java/io/camunda/zeebe/broker/BrokerShutdownHelper.java [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+ * Helper class to initiate the shutdown of the broker application. This is used to trigger graceful
+ * shutdown the broker from within the application itself.
+ */
+@Component
+public class BrokerShutdownHelper {
+
+  @Autowired private ApplicationContext appContext;
+
+  public void initiateShutdown(final int returnCode) {
+    SpringApplication.exit(appContext, () -> returnCode);
```
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply dist/src/main/java/io/camunda/zeebe/broker/BrokerShutdownHelper.java:25]: Yes. The shutdown hook will be invoked which calls `broker.close()`.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/bootstrap/PartitionManagerStep.java (hunk 2 above)
Comment (oleschoenburg) [reply zeebe/broker/src/main/java/io/camunda/zeebe/broker/bootstrap/PartitionManagerStep.java:21]: I wouldn't reuse it. I'm fine with using 3, I was just curious
