### PR TITLE
45635 make history deletion use process instance key

### LINKED ISSUE #45635: Make history deletion use process instance key, not root process instance key
### 

### 

### 

### 

### Description

During the work to change how history _cleanup_ works I also changed how history _deletion_ works: https://github.com/camunda/camunda/pull/44594

However history _deletion_ should not use the root process instance for deletion it should just use the process instance.

Currently this means that deleting a sub-process will probably not behave as expected (i.e. dependent entities will not get removed as we will be searching by root process instance).

### Steps to reproduce

Try to delete a (via call activity) sub-process and see that not all of it's dependent entities (flow nodes, variables etc) get deleted.

### Current behavior

See steps to reproduce

### Expected behavior

Deleting a sub-process should also delete it's dependent entities.

### Workaround

none

### Environment

SaaS & SM

### Version

- Data layer 8.9.0 (pre-alpha 5)

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by lilspikey**
This make the history deletion (not history _cleanup_) use process instance key (not _root_ process instance key) for it's deletes.  It was changed by accident when changing the code for history cleanup.

Most of the line count here is the addition of extra tests, to ensure both the root process + non-root process deletion stuff works for all relevant entities.  Also added some extra ITs to specifically check how things behave for non-root processes (which are processes started via call activity).

closes #45635

### CODE REVIEW

File: db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/HistoryDeletionService.java [hunk 1]
```diff
@@ -81,16 +81,19 @@ private List<Long> deleteProcessInstances(final HistoryDeletionBatch batch) {
...
-                      dependant.deleteRootProcessInstanceRelatedData(processInstanceKeys, limit);
-                  return deletedRows < limit;
-                });
+    boolean allProcessInstanceDependantDataDeleted = true;
+    final var limit = config.dependentRowLimit();
+    for (final var dependant : rdbmsWriters.getProcessInstanceDependantWriters()) {
+      // TODO check if we should still have this or not
+      // if (dependant instanceof AuditLogWriter) {
+      //  continue;
+      // }
```
Comment (houssain-barouni) [inline db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/HistoryDeletionService.java]: I think AuditLogs were intentionally excluded from History deletion, @remcowesterhoud can you please confirm that?

File: qa/acceptance-tests/src/test/java/io/camunda/it/historydeletion/DeleteProcessInstanceHistoryIT.java [hunk 2]
```diff
@@ -92,6 +95,59 @@ void shouldDeleteTwoProcessInstancesByProcessDefinitionIdUsingBatchOperation() {
     assertAllProcessInstanceDependantDataDeleted(camundaClient, piKey2);
   }
 
+  @Test
+  void shouldDeleteTwoProcessInstancesByProcessDefinitionIdUsingBatchOperation2() {
```
Comment (houssain-barouni) [inline qa/acceptance-tests/src/test/java/io/camunda/it/historydeletion/DeleteProcessInstanceHistoryIT.java]: 🔧 can we find a better name for this test 😄

**Review by houssain-barouni — COMMENTED** [review]
Thank you for fixing this! 👍 
We need to double check with @remcowesterhoud if audit logs should be removed in History deletion service, I think it was intentionally excluded

File: qa/acceptance-tests/src/test/java/io/camunda/it/historydeletion/DeleteProcessInstanceHistoryIT.java (hunk 2 above)
Comment (lilspikey) [reply qa/acceptance-tests/src/test/java/io/camunda/it/historydeletion/DeleteProcessInstanceHistoryIT.java]: doh - forgot to update it

File: db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/HistoryDeletionService.java (hunk 1 above)
Comment (lilspikey) [reply db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/HistoryDeletionService.java]: yeah I chatted to @remcowesterhoud on Slack and confirmed they should not get deleted.  I've changed the PR to reflect that.

**Review by houssain-barouni — APPROVED** [review]
LGTM!
