### PR TITLE
fix: deprecate `xCamundaVersion` in favor of `CamundaDockerImageVersion`

### LINKED ISSUE #31797: [CPT] I can't configure the Camunda version in the properties file (Java)
## Problem

In the Java version of Camunda Process Test, I can configure the version of the Camunda Docker image in the file `/camunda-container-runtime.properties`.

According to the [documentation](https://docs.camunda.io/docs/next/apis-tools/testing/getting-started/?client=java-client#configure-the-runtime), I can change the version using `camunda.version=8.8.0`.

However, the property `camunda.version` has no effect. 

Instead, I can change the version using the property `camunda.dockerImageVersion`. This works except for alpha/rc versions, such as `8.8.0-alpha4-rc1`. In this case, the runtime starts the `SNAPSHOT` version. 

## Expected behavior

I can configure the Camunda Docker image's version in the properties file, including versions with a label tag (e.g., `-alpha4`, `-RC`).

## Solution

We should align the properties file with the extension builder and the Spring version of CPT. 
- Expose the same configuration options 
- Use the same configuration names 
 
We need to adjust the documentation about the configuration options.

### LINKED ISSUE #31799: [CPT] Rename the configuration `camunda-version`
## Description

In Camunda Process Test, I can change the version of the Camunda Docker image in the configuration (see [docs](https://docs.camunda.io/docs/next/apis-tools/testing/getting-started/?client=spring-sdk#configure-the-runtime)). 

In Spring: `io.camunda.process.test.camunda-version: 8.8.0`

In Java:
- Properties file: `camunda.version=8.8.0` / `camunda.dockerImageVersion=8.8.0`
- In the extension builder: `withCamundaVersion("8.8.0")`

We should rename the configuration to `camunda-docker-image-version` to clarify that the version is for the Camunda Docker image and to align with `connectors-docker-image-version`. 

## Tasks

- [ ] Rename the property name (Java)
- [ ] Rename the builder method (Java)
- [ ] Rename the property name (Spring)
- [ ] Adjust the documentation

### PR DESCRIPTION
**Pull request by Christian-Broomfield**
## Description

Currently the file `/camunda-container-runtime.properties` has a property called `camunda.version` you can set to configure the camunda docker image version. However, the property `camunda.dockerImageVersion` does the exact same thing and its usage is mixed between CPT-Java and CPT-Spring. This bugfix changes the naming to `camundaDockerImageVersion` and deprecates all other methods. 

The other issue the story mentions, that you can't set a custom version tag such as `8.8.0-alpha4-rc1`, was already fixed in [#31795](https://github.com/camunda/camunda/issues/31795).

## Related issues

closes https://github.com/camunda/camunda/issues/31797
closes https://github.com/camunda/camunda/issues/31799

### CODE REVIEW

File: testing/camunda-process-test-java/src/main/java/io/camunda/process/test/api/CamundaProcessTestExtension.java [hunk 1]
```diff
@@ -263,11 +263,26 @@ private static boolean isTestFailed(final ExtensionContext extensionContext) {
...
+   * @return the extension builder
+   */
+  public CamundaProcessTestExtension withCamundaDockerImageVersion(
+      final String camundaDockerImageVersion) {
+
     runtimeBuilder
-        .withCamundaDockerImageVersion(camundaVersion)
-        .withConnectorsDockerImageVersion(camundaVersion);
+        .withCamundaDockerImageVersion(camundaDockerImageVersion)
+        .withConnectorsDockerImageVersion(camundaDockerImageVersion);
```
Comment (saig0) [inline testing/camunda-process-test-java/src/main/java/io/camunda/process/test/api/CamundaProcessTestExtension.java]: :x: The method should set only the version of the Camunda image. The previous method set both versions together.

File: testing/camunda-process-test-java/src/main/resources/camunda-container-runtime.properties [hunk 2]
```diff
@@ -1,4 +1,4 @@
-camunda.version=${project.version}
+camunda.version=${io.camunda.process.test.camundaDockerImageVersion}
```
Comment (saig0) [inline testing/camunda-process-test-java/src/main/resources/camunda-container-runtime.properties]: :wrench: We don't use the property anymore. We can remove it.

File: testing/camunda-process-test-spring/src/main/java/io/camunda/process/test/impl/configuration/CamundaProcessTestRuntimeConfiguration.java [hunk 3]
```diff
@@ -33,6 +33,8 @@ public class CamundaProcessTestRuntimeConfiguration {
   private String camundaVersion = CamundaProcessTestRuntimeDefaults.CAMUNDA_VERSION;
```
Comment (saig0) [inline testing/camunda-process-test-spring/src/main/java/io/camunda/process/test/impl/configuration/CamundaProcessTestRuntimeConfiguration.java]: :wrench: We don't use the property anymore. We can remove it.

File: testing/camunda-process-test-spring/src/main/java/io/camunda/process/test/impl/configuration/CamundaProcessTestRuntimeConfiguration.java [hunk 4]
```diff
@@ -48,14 +50,48 @@ public class CamundaProcessTestRuntimeConfiguration {
...
     this.camundaVersion = camundaVersion;
   }
 
+  /**
+   * Gets the Camunda docker image version.
+   *
+   * @return the camunda docker image version
+   */
+  public String getCamundaDockerImageVersion() {
+    return camundaDockerImageVersion;
```
[the remark this answers is not in the document]
Comment (saig0) [reply testing/camunda-process-test-spring/src/main/java/io/camunda/process/test/impl/configuration/CamundaProcessTestRuntimeConfiguration.java:82]: > Consider populating camundaDockerImageVersion inside setCamundaVersion

:wrench: We should follow this suggestion.

**Review by saig0 — CHANGES_REQUESTED** [review]
Looks good. :+1: 

I have some minor comments. Please have a look. :cookie:

**Review by saig0 — APPROVED** [review]
LTGM. :+1:
