### PR TITLE
Fix profiling github workflow and related script

### LINKED ISSUE #44000: Profiling of load tests doesn't work anymore
I realized recently that our load test profiling doesn't work anymore  https://github.com/camunda/camunda/actions/runs/20961660782/job/60240321373

Looks like it is referencing an old path

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

The GH workflow was outdated and no longer working.

 * Was referencing an outdated path from 8.8
 * Was using namespace + podname as actual podname, which is outdated
 * Script was using jps which is no longer available

All of the above is fixed.

## Example usage

https://github.com/camunda/camunda/actions/runs/21000055122

[flamegraph-camunda-0.zip](https://github.com/user-attachments/files/24616931/flamegraph-camunda-0.zip)

## Related issues

closes https://github.com/camunda/camunda/issues/44000

### CODE REVIEW

File: load-tests/docs/scripts/executeProfiling.sh [hunk 1]
```diff
@@ -36,7 +36,7 @@ fi
 
 # Run profiling
 filename=flamegraph-$(date +%Y-%m-%d_%H-%M-%S).html
-PID=$(kubectl exec "$node" -- jps | grep Standalone | cut -d " " -f 1)
+PID=$(kubectl exec "$node" -- ps -ax | grep java | awk '{$1=$1;print}' | cut -d " " -f 1)
```
Comment (entangled90) [inline load-tests/docs/scripts/executeProfiling.sh]: 🔧 I use copilot to explain a bit better this line and I think it came up with something interesting:
```suggestion
PID=$(kubectl exec "$node" -- ps -ax | awk '$5 ~ /java/ {print $1}')
```
Which uses awk to match on colum 5 (the command) with the regex `java` and then outputs the first colum (the pid).

**Review by entangled90 — APPROVED** [review]
Nice 🚀

File: load-tests/docs/scripts/executeProfiling.sh (hunk 1 above)
Comment (ChrisKujawa) [reply load-tests/docs/scripts/executeProfiling.sh]: Nice - looks like magic. I agree that we need some more comments. Neither version is really self-explanatory.

Comment (ChrisKujawa) [reply load-tests/docs/scripts/executeProfiling.sh]: I added a comment to this part
