### PR TITLE
Fix disk monitor notification on startup and during failover

### LINKED ISSUE #5093: Broker does not stops processing if it is already out of disk space on start
**Describe the bug**

When disk usage goes above a threshold, broker is expected to stop accepting new commands and stop processing. However, if the disk usage is already above the threshold when the broker starts, it does not behave as expected. 

Following test fails

```java
 @Test
  public void shouldNotProcessWhenOutofDiskSpace() {
    // given
    await()
        .timeout(Duration.ofMinutes(3))
        .pollInterval(1, TimeUnit.MICROSECONDS)
        .untilAsserted(
            () ->
                assertThatThrownBy(this::publishMessage)
                    .hasRootCauseMessage(
                        "RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space"));
   // when
    zeebeBrokerContainer.stop();
    zeebeBrokerContainer.start();

    client = createClient();
    // then
    await()
        .pollInterval(Duration.ofSeconds(10))
        .timeout(Duration.ofMinutes(1))
        .untilAsserted(
            () ->
                assertThatThrownBy(this::publishMessage)
                    .hasRootCauseMessage(
                        "RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space"));
  }
```
**Environment:**
 - Zeebe Version: 0.25.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

* Check for disk availability immediately on start
* Notify listeners if disk is not available when they are added
* Pause streamprocessor if no disk available during a leader change

## Related issues

closes #5093 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java [hunk 1]
```diff
@@ -56,11 +57,18 @@ private void checkDiskUsageAndNotifyListeners() {
...
+          // Listeners always assumes diskspace is available on start. So notify them if it is not.
+          if (!currentDiskAvailableStatus) {
+            listener.onDiskSpaceNotAvailable();
+          }
+        });
   }
 
   public void removeDiskUsageListener(final DiskSpaceUsageListener listener) {
-    diskSpaceUsageListeners.remove(listener);
+    actor.call(() -> diskSpaceUsageListeners.remove(listener));
```
Comment (pihme) [inline broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java:71]: Why this change? Why no longer do it immediately?

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java [hunk 2]
```diff
@@ -114,6 +114,7 @@
   private Gateway gateway;
   private CountDownLatch partitionLatch;
   private final Map<Integer, Leader> partitionLeader;
+  private final Map<Integer, SpringBrokerBridge> springBrokerBridge;
```
Comment (pihme) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java:117]: Please let us talk about this. 

The SpringBrokerBridge is intended to be treated like a Singleton, and managed by Spring. So nobody should call its constructor.

File: broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java [hunk 3]
```diff
@@ -34,6 +34,7 @@ public DiskSpaceUsageMonitor(final DataCfg dataCfg) {
 
   @Override
   protected void onActorStarted() {
+    checkDiskUsageAndNotifyListeners();
```
Comment (pihme) [inline broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java:37]: This comment is actually for line 30 `this.minFreeDiskSpaceRequired = dataCfg.getFreeDiskSpaceCommandWatermark();`

I am pretty (albeit not a 100%) sure that this can be wrong. During out game days one of the interventions that the cloud team was able to do was to increase the PVC of the running broker. That means in the cloud the disk can grow (or shrink) at runtime, so this should become a supplier instead of a cached vale.

**Review by pihme — CHANGES_REQUESTED** [review]
Good stuff.

Please let us talk about the use of `SpringBrokerBridge`

File: broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java (hunk 3 above)
Comment (pihme) [reply broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java:37]: Addendum: alistair is 99% sure this is done at runtime

File: broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java (hunk 1 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java:71]: This will be invoked by other actors. So to prevent concurrent access to `diskSpaceUsageListeners` we submit the task to this actor so that only this actor can modify it.

File: broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java (hunk 3 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java:37]: Oh is it? I thought we have to restart the pod for the change to be in effect.

Comment (pihme) [reply broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java:37]: Here what the cloud guys had to say: https://camunda.slack.com/archives/CKZK2E7RP/p1599037325041500

Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java:37]: I will create a new issue for it because it is unrelated to this PR.

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java (hunk 2 above)
Comment (pihme) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/ClusteringRule.java:117]: Sorry, my bad. Didn't realize that we are in the test code.

**Review by pihme — APPROVED** [review]

File: broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java (hunk 3 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/zeebe/broker/system/monitoring/DiskSpaceUsageMonitor.java:37]: https://github.com/zeebe-io/zeebe/issues/5280
