### PR TITLE
fix: on authorizations disabled, return wildcard app authorizations

### LINKED ISSUE #29355: Identity UI enforces application access checks when authorizations are disabled
**Describe the bug**

Currently the Identity UI applies application access checks regardless of if authorizations are enabled or not

**To Reproduce**

1. Start Identity with authorizations disabled
2. Access the Identity UI with demo:demo
3. Create a user with no authorizations
4. Login as the user with no authorizations
5. Observe 403 forbidden page

**Expected behavior**

With authorizations disabled I should be able to access the UI regardless of my authorizations.

### PR DESCRIPTION
**Pull request by megglos**
## Description

This serves as a backend/frontend integration fix. As the frontends are not aware of authorizations being enabled or not, we return wildcard access to applications when authorizations are disabled.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #29355

### CODE REVIEW

File: service/src/test/java/io/camunda/service/AuthorizationServiceTest.java [hunk 1]
```diff
@@ -16,23 +16,31 @@
...
 
 public class AuthorizationServiceTest {
 
   private AuthorizationServices services;
   private AuthorizationSearchClient client;
+  private SecurityConfiguration securityConfiguration;
 
   @BeforeEach
   public void before() {
+    securityConfiguration = new SecurityConfiguration();
```
Comment (Ben-Sheppard) [inline service/src/test/java/io/camunda/service/AuthorizationServiceTest.java:34]: ❓ Do we need to create a new object here or can we use a mock and then use a when in the tests to return the test value vs setting the field

File: service/src/main/java/io/camunda/service/AuthorizationServices.java [hunk 2]
```diff
@@ -82,8 +90,14 @@ public List<String> getAuthorizedResources(
   }
 
   public List<String> getAuthorizedApplications(final Set<String> ownerIds) {
-    return getAuthorizedResources(
-        ownerIds, PermissionType.ACCESS, AuthorizationResourceType.APPLICATION);
+    if (securityConfiguration.getAuthorizations().isEnabled()) {
```
Comment (Ben-Sheppard) [inline service/src/main/java/io/camunda/service/AuthorizationServices.java:93]: 💭 its preference of course but I would prefer this check to be the other way around so we have a return early style approach “if not enabled return *”, then the rest of the method is just normal/typical operation.

**Review by Ben-Sheppard — APPROVED** [review]
Just a couple of small things from my side but I don’t see them as blocking so I’ll approve early

File: service/src/test/java/io/camunda/service/AuthorizationServiceTest.java (hunk 1 above)
Comment (megglos) [reply service/src/test/java/io/camunda/service/AuthorizationServiceTest.java:34]: What would be the advantage? I didn't see a need to mock as the config POJO is simple enough and doesn't have any dependencies itself, kind of following a mock only when it makes it simpler approach.
