### PR TITLE
fix: Ensure incident query filter supports all error types

### LINKED ISSUE #26787: Incident query filter does not support the new  error types
### Description (required on creation)

The `IncidentFilterRequest`'s does not support the `errorType`:
- `TASK_LISTENER_NO_RETRIES`
- `EXECUTION_LISTENER_NO_RETRIES`

https://github.com/camunda/camunda/blob/222ffa7aba9bcfec95d034ab9a6e381ce86fa88d/zeebe/gateway-protocol/src/main/proto/rest-api.yaml#L5206-L5221

### Steps to reproduce (required on creation)

- Make an incident query request using either of the above mentioned error types
- Notice that the response is not 200

### Current behavior (required on creation)

Does not support:
- `TASK_LISTENER_NO_RETRIES`
- `EXECUTION_LISTENER_NO_RETRIES`

But does support the other error types.

### Expected behavior (required on creation)

Should support all of the following error types:

https://github.com/camunda/camunda/blob/222ffa7aba9bcfec95d034ab9a6e381ce86fa88d/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ErrorType.java#L18-L44

### Environment (required on creation)

- OS: [e.g. MacOS]
- Browser: [e.g. chrome, safari]
- Operate Version: `8.7.0-alpha3`
- Database: [e.g. Elasticsearch X.Y, Opensearch X.Z]

### Handover Dev to QA (required before manual testing)

- Resources:
  
- Versions to validate:
  
- Release version (in which version this feature will be released)
  

### Links

```[tasklist]
### Pull Requests
```

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

This PR resolves the issue where the `TASK_LISTENER_NO_RETRIES` error type was not recognized in incident queries. It ensures that all error types used for incidents creation in Zeebe are properly recognised across related components, including Gateway, CamundaClient, and Search Domain.

### Key changes:
- Fix:
  - Added missing `TASK_LISTENER_NO_RETRIES` to ensure full support for incident queries:
    - **Camunda Client:** Updated `IncidentErrorType` enum.
    - **Gateway Protocol:** Defined the missing `errorType` in `rest-api.yaml`.
    - **Search Domain:** Added missing value to `IncidentEntity.ErrorType`.
    - **Search Client Query Transformer:** Updated `IncidentEntityTransformer` to correctly map the new type.
- Refactoring:
  - Enforced explicit error type mapping in `IncidentEntityTransformer#toErrorType` by removing the `default` case in switch expressions. This prevents runtime exceptions and ensures compile-time enforcement when a new error type is added in `io.camunda.webapps.schema.entities.operate.ErrorType`.
- Test coverage:
  - Added a parameterized integration test in `IncidentQueryTest` to verify that all `ErrorType` values supported by Operate are correctly recognized when querying incidents.
  - The test provides guidance on necessary updates in case new error types are introduced.
- Documentation:
  - Added class-level JavaDoc to the `io.camunda.zeebe.protocol.record.value.ErrorType` enum, providing a guidelines on where to update when introducing new error types.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #26787

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/it/client/IncidentQueryTest.java [hunk 1]
```diff
@@ -221,6 +226,26 @@ void shouldFilterByErrorType() {
     assertThat(result.items().getFirst().getErrorType()).isEqualTo(errorType);
   }
 
+  @ParameterizedTest(name = "Querying incidents with filter.errorType = ''{0}''")
+  @EnumSource(value = ErrorType.class)
```
Comment (houssain-barouni) [inline qa/integration-tests/src/test/java/io/camunda/it/client/IncidentQueryTest.java:230]: 👍 
I guess the most important part of the test is `IncidentErrorType.valueOf(errorType.name()))` which throws exception when there is a missing enum value in the client's `IncidentErrorType`

Can we have similar test to ensure `io.camunda.search.entities.IncidentEntity.ErrorType` is not missing any value?

**Review by houssain-barouni — APPROVED** [review]
LGTM! I had a suggestion to add an extra test to make sure the enum used in the search module is also not missing any value

File: zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ErrorType.java [hunk 2]
```diff
@@ -15,6 +15,42 @@
...
+ *     <tr>
+ *       <td><b>Gateway Protocol</b></td>
+ *       <td>Add the new type in <code>src/main/proto/rest-api.yaml</code> for <code>IncidentFilterRequestBase</code> document</td>
+ *     </tr>
+ *   </tbody>
+ * </table>
+ *
+ * <p>Failure to update all necessary components may result in missing or unrecognized incidents
+ * when querying or displaying incidents in Operate.
+ */
```
Comment (ana-vinogradova-camunda) [inline zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ErrorType.java:53]: Such a great improvement, thank you @ce-dmelnych 👍

**Review by ana-vinogradova-camunda — APPROVED** [review]
Great work @ce-dmelnych ! Thank you! 🚀

File: qa/integration-tests/src/test/java/io/camunda/it/client/IncidentQueryTest.java (hunk 1 above)
Comment (ce-dmelnych) [reply qa/integration-tests/src/test/java/io/camunda/it/client/IncidentQueryTest.java:219]: Thanks for the suggestion, @houssain-barouni! 👍  

I’ve tested scenarios locally where a new error type was not defined in all required places, and it seems that this test already ensures `io.camunda.search.entities.IncidentEntity.ErrorType` includes all necessary values.  

If a new error type is missing in `IncidentEntity.ErrorType` but is defined in other required places, the test fails when executing `newIncidentQuery()....send().join()`, resulting in the following exception:  

```sh
Expecting code not to raise a throwable but caught
"io.camunda.client.api.command.ProblemException: Failed with code 400: 'Bad Request'. Details: 'class ProblemDetail {
    type: about:blank
    title: Bad Request
    status: 400
    detail: No enum constant io.camunda.search.entities.IncidentEntity.ErrorType.NEW
    instance: /v2/incidents/search
}'
...
"
```

Let me know if you think we should still add an explicit validation elsewhere. 🚀
