### PR TITLE
Fix flaky RequestTimeoutTest.shouldReturn504

### LINKED ISSUE #14906: BackupErrorResponseTest$RequestTimeoutTest.shouldReturn is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? no
- Do we suspect that it is a real failure? no

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Paste the failure here
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

```
Error:    Run 1: BackupErrorResponseTest$RequestTimeoutTest.shouldReturn504:157 
expected: 504
 but was: 400
 ```

CI [link](https://github.com/camunda/zeebe/actions/runs/6693823209/job/18185810373)

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
The nature of the flaky test seemed to be that the disconnect method was missing closing the commandApiMessagingService in the BrokerStartupContextImpl as well. Which caused that we could still reach the broker even after disconnecting. The test would pass most of the time because the timeout limit was smaller than the round trip time of the request, and we would get a 504 timeout.

closes https://github.com/camunda/zeebe/issues/14906

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/BackupErrorResponseTest.java [hunk 1]
```diff
@@ -139,7 +139,7 @@ final class RequestTimeoutTest {
     private BackupEndpoint backupEndpoint;
 
     private void lowerTimeout(final GatewayCfg config) {
-      config.getCluster().setRequestTimeout(Duration.ofMillis(1));
+      config.getCluster().setRequestTimeout(Duration.ofNanos(500));
```
Comment (deepthidevaki) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/backup/BackupErrorResponseTest.java:142]: :thought_balloon: I'm not sure if this is the actual cause. `400` indicates broker is receiving the request and rejecting with an `unsupported_message` error because backup store is configured. In this test, we are disconnecting broker 0 from the gateway, which means broker should never receive the message. So a lower timeout should not matter. The root cause would be to understand why broker 0 is receiving the message, even though we disconnect it. May be disconnect is not working as expected. Can you look into it?

**Review by deepthidevaki — COMMENTED** [review]
@rodrigo-lourenco-lopes Let's discuss this. The root cause is that the `disconnect` is not disconnecting broker as expected. I'm not sure if adding a wait would resolve it.

**Comment by rodrigo-lourenco-lopes** [comment]
@deepthidevaki 
I think this test might have been wrong from the start or maybe there was some change after it was added.
In main this test passes even after we comment out the disconnect method.

image

This seems to be due to the configured timeout being too small (1ms) that the probe never gets time to travel back and we always get a 504 Gateway Timeout.

The flakiness of the test seems to be due to _not_ configuring the backup store, as by sometimes by increasing slightly the timeout I am able to reproduce on my machine the flakiness with 400 and message `Cannot process backup requests. No backup store is configured. To use this feature, configure backup in broker configuration.`.

Now the test passes and should fix the flakiness, but the disconnect method still does not change the outcome. And maybe it should not since we are trying to catch RequestTimeoutTest and purposefully diminish it, wdyt?

Also changed to list() instead of a backup status(), since we don't have any at the time of query.

**Comment by deepthidevaki** [comment]
@rodrigo-lourenco-lopes I'm not sure how configuring backup store fixes the issue.

The expectation is that, `disconnect` disconnects gateway and broker. So the next `backup.status()` request never reaches the broker and eventually times out. We verify that the timeout is properly mapped to the excepted error response.

What happens is that  `disconnect` is **not** disconnecting gateway and the broker. So sometimes the request reaches the broker, and instead of the timeout the response is 404 because backup store is not configured. Most of the time test passes because the configured request timeout is very low. So even if `disconnect` is not working as expected, the request times out before broker can respond. 

Now with your changes with backup store configured is that, it doesn't get 404 response. But it can still get a valid success response because in rare chances broker responds fast with in the specified timeout. So the test can still be flaky. For the test to be not flaky, we have to ensure that the broker cannot respond with in the timeout.

**Review by deepthidevaki — APPROVED** [review]
:rocket:  Before merging please take care of the following:

This is not a bug fix. It is just fixing a flaky test. The problem was in the test, not the production code. So
- Update commit message of the first commit to "refactor: ...". 
- Update message of the second commit to "test:..."

**Comment by rodrigo-lourenco-lopes** [comment]
bors merge

**Comment by megglos** [comment]
@rodrigo-lourenco-lopes would that have been worth backporting to 8.3? 🤔

**Comment by rodrigo-lourenco-lopes** [comment]
> @rodrigo-lourenco-lopes would that have been worth backporting to 8.3? 🤔

Was there a flaky run for 8.3? I can backport it yes

**Comment by rodrigo-lourenco-lopes** [comment]
> Backport failed for `stable/8.5`, because it was unable to cherry-pick the commit(s).
> 
> Please cherry-pick the changes locally and resolve any conflicts.
> 
> ```shell
> git fetch origin stable/8.5
> git worktree add -d .worktree/backport-15309-to-stable/8.5 origin/stable/8.5
> cd .worktree/backport-15309-to-stable/8.5
> git switch --create backport-15309-to-stable/8.5
> git cherry-pick -x 73295674bdb6aea83fa2af729ffd9c5d895f6aec c191960c9a77e8489d490b3cab51de5b6ac587ca
> ```

These changes are already present in 8.5 so no need to backport to this one.
