### PR TITLE
fix: Adjust `@RequiresSecondaryStorage` annotation placement

### LINKED ISSUE #40199: Some endpoints are falsely disabled when secondary storage is disabled
### Description

`@RequiresSecondaryStorage` is a guard annotation that should only be placed on REST endpoints whose implementation reads from a search client (Elasticsearch/OpenSearch — secondary storage). Placing it at the **class level** is acceptable when **every** handler method in that controller requires secondary storage. However, several controllers have write and delete endpoints added over time that exclusively use the Zeebe broker (primary storage), while the class-level annotation was never revisited — incorrectly causing those endpoints to be disabled when secondary storage is unavailable.

PR #40200 fixed this for `UserController`, where the class-level annotation was removed and `@RequiresSecondaryStorage` was moved down to only `GET /v2/users/{username}` and `POST /v2/users/search`. The same problem persists in other controllers.

E.g. `ClusterVariableController` is annotated with `@RequiresSecondaryStorage` at class level. While the `GET /search`, `GET /global/{name}`, and `GET /tenants/{tenantId}/{name}` endpoints correctly require secondary storage, the following write endpoints go exclusively through the broker and are incorrectly disabled:

|HTTP Method | Endpoint |
|---|---|
| `POST` | `/v2/cluster-variables/global` | 
| `POST` | `/v2/cluster-variables/tenants/{tenantId}` |
| `DELETE` | `/v2/cluster-variables/global/{name}` |
| `DELETE` | `/v2/cluster-variables/tenants/{tenantId}/{name}` |
| `PUT` | `/v2/cluster-variables/global/{name}` |
| `PUT` | `/v2/cluster-variables/tenants/{tenantId}/{name}` |

The fix is to remove the class-level annotation and add `@RequiresSecondaryStorage` only to the handler methods that genuinely call the search client.

### Steps to reproduce

1. Start Camunda with secondary storage disabled (no Elasticsearch/OpenSearch or RDBMS configured).
2. Send any of the following requests (authenticated):
   - `POST /v2/cluster-variables/global` with a valid body
   - `DELETE /v2/cluster-variables/global/{name}`
   - `PUT /v2/cluster-variables/global/{name}` with a valid body
3. Observe: `503 Service Unavailable` — secondary storage unavailable.

### Current behavior

All endpoints in a controller annotated with `@RequiresSecondaryStorage` at class level return `503 Service Unavailable` when secondary storage is disabled, including write and delete endpoints that exclusively interact with the Zeebe broker.

### Expected behavior

Only endpoints that read from a search client (e.g., `GET /{id}`, `POST /search`) should return `503` when secondary storage is unavailable. Broker-only write and delete endpoints should respond normally with `2xx`.

### Workaround

Enable secondary storage (configure ES/OS or RDBMS). No workaround exists for primary-storage-only deployments.

### Rootcause

`@RequiresSecondaryStorage` was either misapplied directly on broker-only handler methods, or applied at the controller class level — initially as a valid shortcut when all endpoints required secondary storage — but never re-evaluated as new write and delete endpoints were added over time. In both cases, the absence of an automated architectural guard allowed incorrect and inconsistent annotation usage to go undetected.

### Solution ideas

1. **Add ArchUnit rules** to `zeebe/gateway-rest` architecture tests to identify and permanently enforce correct `@RequiresSecondaryStorage` usage:
   - **Rule 1 — Every handler method in a class annotated with `@RequiresSecondaryStorage` must transitively call a `*SearchClient`.** This rule acts as a safety net for the class-level annotation: it is allowed on a controller only as long as all its handler methods actually require secondary storage. As soon as a broker-only endpoint is added to such a class, this rule will fail the build and force the developer to reconsider the annotation placement. Running this rule against the current codebase will surface all existing violations — serving as the audit described in item 2.
   - **Rule 2 — Handler methods annotated with `@RequiresSecondaryStorage` must not reside in a class that is itself annotated with `@RequiresSecondaryStorage`.** Redundant nesting is a maintenance hazard — it signals that either the class-level annotation was not removed when the annotation was moved to method level, or a method was incorrectly annotated inside an already-gated class. The violation message should instruct the developer to either:
     - Remove the class-level annotation and keep only the necessary method-level ones (when not all handler methods require secondary storage), or
     - Remove the redundant method-level annotations (when all handler methods genuinely require secondary storage and the class-level annotation is intentional).
   - *(Optional — can be extracted to a follow-up task)* **Rule 3 (inverse) — any handler method that calls a `*SearchClient` must be covered by `@RequiresSecondaryStorage`, either at the method level or via its enclosing class.** Rules 1 and 2 guard against over-annotation (endpoints falsely gated). This inverse rule guards against under-annotation: a new `GET` or `POST /search` endpoint backed by a search client that is missing the annotation will fail with some unexpected exception instead of the expected `503`. Together, all three rules form a closed, bidirectional contract that fully machine-verifies correct annotation usage in both directions.

2. **Fix all violations identified by the ArchUnit rules:**
   - For controllers where only some endpoints need secondary storage: remove the class-level annotation and place `@RequiresSecondaryStorage` only on the individual handler methods that call a search client.
   - For controllers where all endpoints genuinely need secondary storage: the class-level annotation is correct and preferred. Remove any redundant method-level annotations.

### Links
- Related PR (fix for `UserController`): #40200

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

This PR revisits the usage of `@RequiresSecondaryStorage` in the Orchestration Cluster REST API, the core goal is to ensure that only endpoints that are intentionally unavailable without secondary storage are gated with `@RequiresSecondaryStorage`, while broker-only endpoints that can operate on primary storage remain available. And introduces ArchUnit rule to prevent redundant @RequiresSecondaryStorage usage on methods inside already-annotated controllers.

In practice, this means:
- removing class-level `@RequiresSecondaryStorage` from mixed controllers where only some endpoints truly require secondary storage,
- moving the annotation down to the individual read/search handlers that depend on secondary storage,
- keeping class-level annotation only where the entire controller/feature is intentionally disabled in no-db mode,
- and adding clarifying comments in places where the product decision is broader than the direct request-path dependency.

---

### Background

`@RequiresSecondaryStorage` was introduced to return a clear early `403 Forbidden` when a REST endpoint is unavailable without secondary storage, instead of letting the request fail later in deeper service/search layers.

Its intended usage is:

- **controller level** only when **all handler methods** in that controller are unavailable without secondary storage,
- **method level** when only **some endpoints** in the controller are unavailable.

Over time, several controllers evolved and gained write/delete/broker-only endpoints, but the original class-level annotation was not revisited. As a result, some endpoints became falsely disabled in no-db mode even though they only communicate with the Zeebe broker and do not require search-backed reads.

This PR addresses those inconsistencies for the controllers covered here.

---

### 1. Reclassifies mixed controllers
For controllers that contain both (e.g. `ClusterVariableController.java`):
- secondary-storage-backed read/search endpoints, and
- broker-only write/delete/command endpoints,

this PR removes the class-level `@RequiresSecondaryStorage` annotation and re-applies it only to the endpoints that should actually be unavailable in no-db mode.

This follows the same approach previously applied in #40200 for `UserController`.

### 2. Preserves controller-level gating where the whole feature is unavailable
For some controllers, the entire feature remains intentionally unavailable when secondary storage is disabled. In these cases, the class-level annotation is preserved.

A notable example is **batch operations** (`BatchOperationController.java`):
- some lifecycle endpoints such as **cancel**, **suspend**, and **resume** primarily send broker commands and do not directly query secondary storage in their own request path,
- however, **batch operations as a feature** depend heavily on secondary storage overall for:
  - creation from filters,
  - item discovery / materialization,
  - initialization,
  - status tracking,
  - and read/search APIs.

Because batch operations are intentionally treated as unavailable in no-db mode, the whole `BatchOperationController` remains guarded with `@RequiresSecondaryStorage`.
Clarification comment was added over it.

### 3. Introduces ArchUnit rule to prevent redundant `@RequiresSecondaryStorage` usage
Added an ArchUnit rule to prevent redundant `@RequiresSecondaryStorage` usage on methods inside already-annotated controllers.

### 4. Cleans up small controller inconsistencies
This PR also fixes small related issues discovered during the audit, such as request-mapped handler visibility inconsistencies where applicable.

---

### Why this change is needed

Without this cleanup, some endpoints that can operate correctly on primary storage alone are rejected in no-db mode simply because they live in a controller that was historically annotated at class level.

That behavior is misleading for users and makes no-db support more restrictive than intended.

This PR makes the behavior more precise:
- **search / secondary-storage-dependent endpoints** continue to return `403 Forbidden`,
- **broker-only endpoints** remain usable where supported,
- and **feature-wide no-db restrictions** stay explicit where they are an intentional product decision.

---

### Notes on `@RequiresSecondaryStorage`

This PR follows the practical interpretation discussed in [#40199](https://github.com/camunda/camunda/issues/34385):

- Use `@RequiresSecondaryStorage` to gate endpoints that are unavailable without secondary storage.
- Use **method-level annotation** for mixed controllers.
- Keep **class-level annotation** only if:
  - every endpoint in the controller is genuinely unavailable without secondary storage, or
  - the whole feature is intentionally disabled in no-db mode.

This means not every annotated endpoint necessarily performs a direct search query itself; some remain annotated because the **feature as a whole is unsupported without secondary storage**.

Batch operations are the main example of that distinction in this PR.

---

### Should generally be method-level gated
- `GET /...`
- `POST /search`
- other endpoints backed by search clients / secondary-storage reads

#### Should generally stay enabled in no-db mode
- pure broker commands
- create/update/delete endpoints that operate only through primary storage

#### Can still remain class-level gated
- controllers representing a feature that is intentionally unavailable without secondary storage, even if some individual handlers are broker-only in isolation

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #40199

### CODE REVIEW

File: zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ClusterVariableController.java [hunk 1]
```diff
@@ -39,7 +39,6 @@
 import org.springframework.web.bind.annotation.RequestParam;
 
 @CamundaRestController
-@RequiresSecondaryStorage
```
Comment (ce-dmelnych) [inline zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ClusterVariableController.java:42]: Adding @mathias-vandaele for review as you were involved in the cluster variables feature.

For `ClusterVariableController`, this PR assumes the create/update/delete endpoints are broker-only and should stay available without secondary storage, while only the read/search endpoints remain guarded by `@RequiresSecondaryStorage`.

Could you please confirm that assumption?

**Comment by korthout** [comment]
@ce-dmelnych Regarding the ArchUnit test: it doesn't prevent forgetting to annotate a method or class that actually needs it. Have you considered introducing a second annotation `@NoSecondaryStorageNeeded` (or similar) as a complement to the current one. The arch test could require that either one of the two is used on each controller method (or it's class).

**Comment by ce-dmelnych** [comment]
> @ce-dmelnych Regarding the ArchUnit test: it doesn't prevent forgetting to annotate a method or class that actually needs it. Have you considered introducing a second annotation `@NoSecondaryStorageNeeded` (or similar) as a complement to the current one. The arch test could require that either one of the two is used on each controller method (or it's class).

Thanks for the suggestion, @korthout — I like this idea! I've created a follow-up Tech Debt issue #51299 to track the introduction of `@NoSecondaryStorageNeeded` (or similar) and the exhaustiveness ArchUnit rule.
I'd prefer to keep this PR focused on the immediate fix and tackle the broader enforcement in a dedicated follow-up.

**Review by fabiopaini-camunda — APPROVED** [review]
LGTM, thank you @ce-dmelnych !
