### PR TITLE
fix: change to skip group existence check

### LINKED ISSUE #36379: Migration app is not working with BYOG enabled
Since the migration app bypass the authentication layer the commands don't contain the group claim extracted from the token when BYOG functionality is enabled. In particular [this check](https://github.com/camunda/camunda/pull/33631/files#diff-9e5ebd48355f47e4d16dc960e898cafd6bb401aca1019ede103988f8259085e2R134-R136) is failing.

## Solution proposal:

Remove the check that verifies the group claim in the command, as already did for USER and CLIENT

Please add IT to verify the correct behaviour

### PR DESCRIPTION
**Pull request by maryarm**
## Description

Since the migration app bypass the authentication layer the commands don't contain the group claim extracted from the token when BYOG functionality is enabled. In particular [this check](https://github.com/camunda/camunda/pull/33631/files#diff-9e5ebd48355f47e4d16dc960e898cafd6bb401aca1019ede103988f8259085e2R134-R136) is failing.

## Related issues

closes #36379

### CODE REVIEW

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/RolesByGroupIntegrationTest.java [hunk 1]
```diff
@@ -369,26 +368,47 @@ void shouldRejectUnassigningRoleFromGroupIfGroupIdIsEmpty() {
...
-                    .join())
-        .isInstanceOf(ProblemException.class)
-        .hasMessageContaining(
-            "Expected to remove an entity with ID '"
-                + groupId
-                + "' and type 'GROUP' from role with ID '"
-                + EXISTING_ROLE_ID
-                + "', but the entity doesn't exist.");
+                assertThat(
+                        searchRolesByGroupId(
```
Comment (nicpuppa) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/RolesByGroupIntegrationTest.java]: 🔧 Can you use the camunda client instead of the http client here ? I think we have the command now

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/RolesByGroupIntegrationTest.java [hunk 2]
```diff
@@ -215,21 +215,20 @@ void shouldRejectUnassigningIfRoleIsNotAssignedToGroup() {
...
+    // when
+    camundaClient
+        .newAssignRoleToGroupCommand()
+        .roleId(EXISTING_ROLE_ID)
+        .groupId(groupId)
+        .send()
+        .join();
+
+    // then
+    assertRoleAssignedToGroup(EXISTING_ROLE_ID, groupId);
```
Comment (nicpuppa) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/RolesByGroupIntegrationTest.java:199]: 🔧 Same here, we should use the client command

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/AssignGroupToTenantTest.java [hunk 3]
```diff
@@ -96,20 +96,19 @@ void shouldRejectIfGroupDoesNotExist() {
...
+    // when
+    client
+        .newAssignGroupToTenantCommand()
+        .groupId(nonExistentGroupId)
+        .tenantId(tenantId)
+        .send()
+        .join();
+
+    // then
+    ZeebeAssertHelper.assertEntityAssignedToTenant(
```
Comment (nicpuppa) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/AssignGroupToTenantTest.java:108]: ❌ We should use the client here to assert that the group is assigned to the tenant, if the command is not available please use an HttpClient

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/UnassignGroupFromTenantTest.java [hunk 4]
```diff
@@ -94,23 +94,26 @@ void shouldRejectIfTenantDoesNotExist() {
...
-        .isInstanceOf(ProblemException.class)
-        .hasMessageContaining("Failed with code 404: 'Not Found'")
-        .hasMessageContaining(
-            "Expected to remove group with ID '%s' from tenant with ID '%s', but the group doesn't exists."
-                .formatted(nonExistentGroupId, tenantId));
+    // when
+    client.newUnassignGroupFromTenantCommand(tenantId).groupId(nonExistentGroupId).send().join();
+
+    // then
+    ZeebeAssertHelper.assertGroupUnassignedFromTenant(
```
Comment (nicpuppa) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/UnassignGroupFromTenantTest.java:111]: ❌ Same as above

**Review by nicpuppa — CHANGES_REQUESTED** [review]

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/RolesByGroupIntegrationTest.java (hunk 1 above)
Comment (maryarm) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/RolesByGroupIntegrationTest.java]: Here I just adopted the existing tests, although I like your suggestion but I prefer to not doing it now as we have high prio bugs in the queue.

Comment (nicpuppa) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/RolesByGroupIntegrationTest.java]: I noticed that, but literally it takes 5 minutes to change this to use the client instead of the httpclient. I'm ok also to keep the method but just use the client inside the method

**Comment by nicpuppa** [comment]
I'm going to address the comments and merge the PR afterwards, as this PR blocks another [task](https://github.com/camunda/camunda/issues/34774) of the Identity Migration.

**Comment by maryarm** [comment]
> I'm going to address the comments and merge the PR afterwards, as this PR blocks another [task](https://github.com/camunda/camunda/issues/34774) of the Identity Migration.

I'm about to start working on it in half an hour (after I've finished with another bug) but it's ok if you want to take care of it, thanks. However If I'm doing it I will separate the PRs as the improving the test is not the critical part of the changes and this PR in its current status can unblock the migration.

**Review by nicpuppa — APPROVED** [review]
