### PR TITLE
fix: suspended batch operation should not block execution of future ones

### LINKED ISSUE #43097: Suspend Batch Operation unexpectedly blocks further Batch Operation progress
### 

### 

, 

### 

### 

### Description

While writing automated E2E tests for the Batch Operation endpoints I encountered a strange behavior for the [Suspend Batch Operation](https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/suspend-batch-operation/) endpoint.

Other batch operation tests, that were not related failed. Their error was that they did complete. To be precise that their state did not change from "CREATED" to "COMPLETED".

After multiple ways to make it work. I found out that I need to resume the batch operation which was suspend and then the test suite worked fine.

As today is my last day at Camunda: I informed @hilalbursalii and discussed the topic with @nicpuppa who referred me to @mustafadagher.

@mustafadagher explained to me, that the batch operation are executed one at a time. So the one which was suspend has been blocking all the other ones. This is by design.

## The Test Setup
Precondition: Run a test suite with multiple batch operations executed in paralllel.

1. Create 3 process instances
2. Create Batch Operation to cancel the three process instances.
3. Suspend the batch operation
4. Verify that the batch operation is suspended.

### Current behavior

Other batch operations will be blocked while the batch operation is suspended, which cases automated tests to fail.

### Expected behavior

1. suspended batch operations won't block the queue
2. The [Suspend Batch Operation endpoint documentation](https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/suspend-batch-operation/) warns that that scenario is possible to happen and calling resume is needed.

### Workaround

Call [Resume Batch Operation](https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/resume-batch-operation/)

### Environment

SM

### Version

stable/8.8

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description

A suspended batch operation blocks all subsequent pending batch operations from making progress. The root cause is that `getNextPendingBatchOperation()` always returns the first entry in the pending column family without checking whether it is suspended — the scheduler repeatedly picks up the suspended operation and never advances to the next one.

### Problem

When a batch operation is suspended, it remains in the pending batch operations column family. Since `getNextPendingBatchOperation()` returns the **first** entry unconditionally, the scheduler enters a loop where it always retrieves the suspended operation but cannot execute it, starving all batch operations that were created after it.

### Solution

This PR combines two complementary approaches to fix the issue:

#### Solution 1 — Skip suspended operations at query time

Change `getNextPendingBatchOperation()` in `DbBatchOperationState` to iterate through the pending column family and skip entries with `SUSPENDED` status, returning the first non-suspended pending batch operation.

- **Pros:** Minimal change in a single place; immediately fixes the issue for **existing** suspended operations that are already stuck in the pending queue (i.e. operations suspended before this fix is deployed).
- **Cons:** If there are *n* suspended operations at the head of the queue, the scheduler has to iterate over all of them on every tick.

#### Solution 2 — Remove suspended operations from the pending queue

Introduce V2 event appliers (`BatchOperationSuspendedV2Applier` / `BatchOperationResumedV2Applier`) that manage the pending column family alongside the status transition:

- **`SUSPENDED` V2 applier:** calls `suspend()` **and** `removeFromPending()` — the operation is no longer visible to the scheduler.
- **`RESUMED` V2 applier:** calls `resume()` **and** `addToPending()` — the operation is re-added so the scheduler can pick it up again.

- **Pros:** Better steady-state performance (no iteration over suspended entries) and correct by construction going forward.
- **Cons:** Requires new applier versions (V2) since event applier implementations must not be changed in-place; existing suspended operations (created before migration to V2) are **not** retroactively cleaned up.

#### Why both?

Neither solution alone covers all cases:

| Scenario | Solution 1 | Solution 2 |
|---|---|---|
| **Pre-existing** suspended ops stuck in the pending queue | ✅ Skips them at query time | ❌ V2 applier not yet applied to old events |
| **Newly** suspended ops going forward | ⚠️ Works but iterates on every tick | ✅ Removed from pending; zero iteration cost |

By combining both, Solution 1 acts as a **safety net** for already-dirty state, while Solution 2 prevents new suspensions from accumulating in the pending queue — effectively bounding the performance cost of Solution 1 to only legacy operations.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #43097

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/batchoperation/SuspendedBatchOperationBlocksQueueTest.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+ * href="https://github.com/camunda/camunda/issues/43097">camunda/camunda#43097</a>.
+ *
+ * <p>A suspended batch operation should not block other pending batch operations from making
+ * progress. When a batch operation is suspended, the scheduler should skip it and process the next
+ * pending batch operation in the queue.
+ */
+public final class SuspendedBatchOperationBlocksQueueTest extends AbstractBatchOperationTest {
+
+  @Test
+  public void shouldNotBlockOtherBatchOperationsWhenOneSuspended() {
```
[the remark this answers is not in the document]
Comment (fabiopaini-camunda) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/batchoperation/SuspendedBatchOperationBlocksQueueTest.java:28]: The test seems clear enough to me

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/batchoperation/SuspendedBatchOperationBlocksQueueTest.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    engine.batchOperation().newLifecycle().withBatchOperationKey(batchAKey).suspend();
+
+    // verify batchA is actually suspended
+    assertThat(
+            RecordingExporter.batchOperationLifecycleRecords()
+                .withBatchOperationKey(batchAKey)
+                .onlyEvents()
+                .limit(r -> r.getIntent() == BatchOperationIntent.SUSPENDED))
+        .extracting(Record::getIntent)
+        .contains(BatchOperationIntent.SUSPENDED);
```
Comment (fabiopaini-camunda) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/batchoperation/SuspendedBatchOperationBlocksQueueTest.java]: 🔧 I would personally simplify this as:
```suggestion
    RecordingExporter.batchOperationLifecycleRecords()
          .withBatchOperationKey(batchAKey)
          .withIntent(BatchOperationIntent.SUSPENDED)
          .await();
```

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/batchoperation/SuspendedBatchOperationBlocksQueueTest.java [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+            RecordingExporter.batchOperationLifecycleRecords()
+                .withBatchOperationKey(batchBKey)
+                .onlyEvents()
+                .limit(r -> r.getIntent() == BatchOperationIntent.COMPLETED))
+        .describedAs(
+            "Batch operation B (key=%d) should have completed, "
+                + "but it is blocked by the suspended batch operation A (key=%d).",
+            batchBKey, batchAKey)
+        .extracting(Record::getIntent)
+        .contains(BatchOperationIntent.COMPLETED);
```
Comment (fabiopaini-camunda) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/batchoperation/SuspendedBatchOperationBlocksQueueTest.java]: 🔧 I would personally find this clearer as:
```suggestion
    assertThat(
        RecordingExporter.batchOperationLifecycleRecords()
            .withBatchOperationKey(batchBKey)
            .withIntent(BatchOperationIntent.COMPLETED)
            .findFirst())
        .describedAs(
            "Batch operation B (key=%d) should have completed, "
                + "but it is blocked by the suspended batch operation A (key=%d).",
            batchBKey, batchAKey)
        .isPresent();
```
(`await` could be used here too, but it would hide the fact that we are asserting something)

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/batchoperation/BatchOperationStateTest.java [hunk 4]
```diff
@@ -689,6 +689,130 @@ void shouldReturnFalseForResumeBatch() {
...
+    state.create(batchOperationKey, batchRecord);
+    state.suspend(batchOperationKey);
+
+    // when
+    final var nextPending = state.getNextPendingBatchOperation();
+
+    // then — no pending operation should be returned
+    assertThat(nextPending).isEmpty();
+  }
+
```
Comment (fabiopaini-camunda) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/batchoperation/BatchOperationStateTest.java]: I think this can be removed since it is already tested in `shouldReturnEmptyWhenAllBatchesAreSuspended` (which also has a clearer name)

```suggestion
```

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java [hunk 5]
```diff
@@ -283,6 +283,20 @@ public void resume(final long batchOperationKey) {
     batchOperationColumnFamily.update(batchKey, batch);
   }
 
+  @Override
+  public void removeFromPending(final long batchOperationKey) {
+    LOGGER.trace("Removing batch operation with key {} from pending", batchOperationKey);
+    batchKey.wrapLong(batchOperationKey);
+    pendingBatchOperationColumnFamily.deleteIfExists(batchKey);
```
Comment (fabiopaini-camunda) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:290]: ❓ Why not:
```suggestion
    pendingBatchOperationColumnFamily.deleteExisting(batchKey);
```
Is it allowed to remove from pending without having added it before (i.e. suspending an already-suspended batch operation)?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java [hunk 6]
```diff
@@ -283,6 +283,20 @@ public void resume(final long batchOperationKey) {
...
+  }
+
+  @Override
+  public void addToPending(final long batchOperationKey) {
+    LOGGER.trace("Adding batch operation with key {} to pending", batchOperationKey);
+    batchKey.wrapLong(batchOperationKey);
+    pendingBatchOperationColumnFamily.upsert(batchKey, DbNil.INSTANCE);
```
Comment (fabiopaini-camunda) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:297]: ❓ Why not:
```suggestion
    pendingBatchOperationColumnFamily.insert(batchKey, DbNil.INSTANCE);
```
Is it allowed to add to pending while it is already present (i.e. resuming a non-suspended batch operation)?

**Review by fabiopaini-camunda — APPROVED** [review]
👍 Thank you @mustafadagher for this fix, handling both existing batch operations and new ones while being conscious of performance.

I added some small notes and a couple questions, but generally I don't see anything which should block this PR, so I am approving it!

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java (hunk 5 above)
Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:290]: your question actually uncovered an edge case that I need to think about and consider:

We can suspend a batch operation in the middle of execution, long after `initializing`.   
when we transition the operation to initialized `transitionToInitialized` we remove it from the pending queue.   

Now in the new appliers, suspend and resume remove and re-add to pending queue with no respect to the bo state.

I need to think about this edge case for a moment. 

But in all cases, I believe `deleteIfExists` is the right method to be used here.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java (hunk 6 above)
Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:297]: what is the difference between the current line and the suggestion? I can't see it. 

And as for the question, I only added this method to be used from the new applier, while still reusing the old resume method. But I could have combined and encapsulated the two calls in a `resumeAndAddToPending()` method, but I preferred the current setup.

Comment (fabiopaini-camunda) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:297]: You're right, I fixed my comment: use `insert` instead of `upsert`.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java (hunk 5 above)
Comment (fabiopaini-camunda) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:290]: So, if I understand correctly:
- it is possible to suspend a batch operation which is not in the pending queue (because it is already initialized)
- when resuming it, it should not necessarily be added to the pending queue (because it was suspended after already being initialized)

If this is the case, I agree that `deleteIfExists` is correct here, but then the applier for `RESUMED` should be changed.

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:290]: yes, I'm working on a change (the change is actually simple, a test case is more difficult 😄 )

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:290]: This is impossible to test, because if we wait for initialized to suspend, there's a big chance the bo will be completed before suspension is processed, unless if we try initializing a bo with a 1million operations or something 😄 

Fixed here 85d138b

**Comment by mustafadagher** [comment]
@fabiopaini-camunda , I made some changes, can you check again?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java (hunk 6 above)
Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:297]: I believe `upsert` is safer, for whatever could or could not happen :D
