### PR TITLE
fix: reject modifications that terminate flow scopes required by activation

### LINKED ISSUE #37079: Inconsistent state when terminating a sub-process element and activating a child element via process instance modification
### 

### 

 

### 

### 

### Description

When performing a process instance modification via the REST API, it is currently possible to terminate a sub-process element and simultaneously activate a child element within that sub-process. This leads to an invalid state in Zeebe where the child element requires a flow scope that no longer exists (because the sub-process was terminated), resulting in broken behavior and an unresolvable process instance.

**Linked Branch**
A [branch](https://github.com/camunda/camunda/tree/37079-subprocess-modification-invalid-state) has been created and linked to this issue that includes a unit test reproducing the bug in a failing state.

### Steps to reproduce

1. Deploy a BPMN model containing a sub-process with an end event inside it.
2. Start a process instance so that it reaches the sub-process scope.
3. Use the /process-instances/{key}/modification API with:
  - A terminateInstruction targeting the sub-process element instance key
  - An activateInstruction targeting the end event inside that sub-process
4. Observe the process instance state after the modification.

### Current behavior

- The sub-process element is terminated.
- The child element (e.g., the end event inside the sub-process) is activated, but fails due to a missing flow scope.
- Zeebe fails with an error similar to: `Expected flow scope instance with key '<key>' to be present in state but not found.`
- The process instance is left in an inconsistent and unresolved state — it is not completed, and it has no active elements or tokens.

### Expected behavior

This behaviour is undefined in the current implementation and should be clearly defined and validated. Two possible solutions are considered (see Solution ideas section).

### Environment

SM

### Version

- Component Version: 8.7.7

### Rootcause

The modification command does not validate whether the flow scope required by the activated element is also being terminated in the same request. As a result, Zeebe allows a logically conflicting instruction set to execute, leading to an invalid state.

#### Option A: Allow the operation by reconstructing the necessary flow scope

- When the modification attempts to activate an element whose required flow scope (e.g., the sub-process) is not currently active, Zeebe could:
  - Re-activate or recreate the sub-process scope element first.
  - Then activate the target element (e.g., end event) inside that newly created scope.
  - This would align with existing behavior where Zeebe creates a flow scope if it does not exist.

#### Option B: Reject the modification as invalid
- Zeebe could validate that:
   - The target activation element requires a specific flow scope
   - That scope is also being terminated in the same modification request
- If so, the request should be rejected with a descriptive error message.
  - Suggest that the user either:
      - Provide a valid ancestor scope key for the activation
      - Avoid terminating the required flow scope

This would ensure the engine stays in a consistent and predictable state and helps guide users toward proper usage of the modification API.

### Dev -> QA handover

- Resources:
- Versions to validate: 
- Release version (in which version this feature will be released):

### Links
related to: [SUPPORT-28674](https://jira.camunda.com/browse/SUPPORT-28674)

### PR DESCRIPTION
**Pull request by tsedekey**
## Description

This PR prevents invalid process instance modifications where a sub-process element is terminated while simultaneously activating a child element within it. This previously led to inconsistent process states where the activated element had no valid flow scope.

The solution follows [Option B](https://github.com/camunda/camunda/issues/37079#issuecomment-3254205191): such conflicting modification requests are now explicitly rejected with a clear error message. This ensures the engine remains in a consistent and predictable state.

A failing test was added to demonstrate the issue, and now verifies that the invalid scenario is correctly handled.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #37079

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 1]
```diff
@@ -132,6 +132,15 @@ public final class ProcessInstanceModificationModifyProcessor
       Expected to modify instance of process '%s' but it is currently suspended. \
       Suspended process instances cannot be modified.""";
 
+  private static final String ERROR_MESSAGE_ACTIVATION_FLOW_SCOPE_TERMINATED =
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:135]: 👍 I like the error message, very comprehensive!

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceRejectionTest.java [hunk 2]
```diff
@@ -879,4 +879,346 @@ public void shouldRejectActivationWhenAncestorBelongsToDifferentProcessInstance(
...
+        .hasRejectionReason(
+            ("Expected to modify instance of process '%s' but it contains one or more activate instructions "
+                    + "for elements whose required flow scope instance is also being terminated: "
+                    + "element 'B' requires flow scope instance '%s' which is being terminated. "
+                    + "Please provide a valid ancestor scope key for the activation or avoid terminating the required flow scope.")
+                .formatted(PROCESS_ID, eventSubProcessInstance.getKey()));
+  }
+
+  @Test
+  public void shouldAcceptActivationWithValidAncestorScopeKeyInEventSubProcess() {
```
Comment (berkaycanbc) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceRejectionTest.java:1304]: 🔧 Let's move the two non-rejection cases to the bottom of `ModifyProcessInstanceTest` class. Rejection tests solely focus on rejections and their message assertions.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 3]
```diff
@@ -674,6 +687,66 @@ private boolean isFlowScopeOfElement(
...
+        terminateInstructions.stream()
+            .map(ProcessInstanceModificationTerminateInstructionValue::getElementInstanceKey)
+            .collect(Collectors.toSet());
+
+    // For each activation, determine required flow scope instance key
+    final List<String> conflictingActivations = new ArrayList<>();
+    for (final var instruction : activateInstructions) {
+      final var elementToActivate = process.getProcess().getElementById(instruction.getElementId());
+      if (elementToActivate == null) {
+        continue; // Already validated elsewhere
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]: 💭 No need to check as this validation will not be invoked if existence check fails in the first flatMap. But I am okay with keeping it for explicitness.

**Review by berkaycanbc — CHANGES_REQUESTED** [review]
Thanks @tsedekey for working on this! 🚀 

⌛This one is open for a long time. Please keep an eye on PRs that are open for a long time because they can become outdated easily or miss to be in the next release. Please ask for another review if the original reviewer is not available.

⭐ Test cases are quite nicely covering different cases and the implementation looks good semantically.

❌ There is one case that is not working with the current implementation and needs to be handled; nested flow scopes. The test case below reproduces the original error `"!INVALID_STATE (Expected flow scope instance with key '<id>' to be present in state but not found.)"`:

```java
@Test
  public void shouldRejectActivationWhenFlowScopeIsTerminatedNested() {
    // given
    ENGINE
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(PROCESS_ID)
                .startEvent()
                .subProcess(
                    "subprocess",
                    sp ->
                        sp.embeddedSubProcess()
                            .startEvent()
                            .serviceTask("A", a -> a.zeebeJobType("A"))
                            .subProcess(
                                "subprocess-nested",
                                spn ->
                                    spn.embeddedSubProcess()
                                        .startEvent()
                                        .serviceTask("B", a -> a.zeebeJobType("B"))
                                        .endEvent("sub-end-nested"))
                            .endEvent("sub-end"))
                .endEvent()
                .done())
        .deploy();

    final var processInstanceKey = ENGINE.processInstance().ofBpmnProcessId(PROCESS_ID).create();
    final var subProcessElementInstance =
        RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
            .withProcessInstanceKey(processInstanceKey)
            .withElementType(BpmnElementType.SUB_PROCESS)
            .withElementId("subprocess")
            .getFirst();

    // when
    final var rejection =
        ENGINE
            .processInstance()
            .withInstanceKey(processInstanceKey)
            .modification()
            .activateElement("sub-end-nested")
            .terminateElement(subProcessElementInstance.getKey())
            .expectRejection()
            .modify();

    // then
    assertThat(rejection)
        .describedAs("Expect that activation is rejected when flow scope is terminated")
        .hasRejectionType(RejectionType.INVALID_ARGUMENT)
        .hasRejectionReason(
            """
              Expected to modify instance of process '%s' but it contains one or more activate instructions \
              for elements whose required flow scope instance is also being terminated: element 'sub-end-nested' requires flow scope instance '%s' \
              which is being terminated. Please provide a valid ancestor scope key for the activation or avoid terminating the required flow scope."""
                .formatted(PROCESS_ID, subProcessElementInstance.getKey()));
  }
```

The implementation needs to be adjusted to handle nested flow scopes.

**Comment by berkaycanbc** [comment]
@tsedekey any updates on this?

**Comment by tsedekey** [comment]
> @tsedekey any updates on this?

@berkaycanbc first of all, thank you for your patience with this PR, I’ve taken your point about not leaving PRs open for too long, and I’ll make a conscious effort to avoid that in future.

I’ve now addressed all your comments, and I really appreciate your suggestion to add the missing test — that was a crucial case, and I’ve updated the code accordingly to ensure that it passes as well.

Thanks again for your thoughtful review. Looking forward to your re-review! 🙏

**Comment by tsedekey** [comment]
Hi @berkaycanbc, thanks again for taking the time to sync with me the other day to walk through the issue and suggest improvements to the validation logic. Your approach to handling activations of elements whose flow scopes are being terminated — especially in the deeply nested cases — really helped clarify things for me. I now have a much better understanding of how flow scopes work and why your solution is more efficient.

I’ve implemented your suggested validation method, and I’ve also added a unit test that specifically covers the scenario where a three level nested element is activated while its parent flow scope (several levels up) is being terminated. The test correctly rejects the modification as expected. 🚀 🙌

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 4]
```diff
@@ -347,6 +356,10 @@ public ProcessingError tryHandleError(
         .flatMap(valid -> validateVariableScopeExists(process, activateInstructions))
         .flatMap(valid -> validateVariableScopeIsFlowScope(process, activateInstructions))
         .flatMap(valid -> validateAncestorKeys(process, value))
+        .flatMap(
+            valid ->
+                validateElementIsNotActivatedForTerminatedFlowScope(
+                    processInstance, process, activateInstructions, terminateInstructions))
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]:
```suggestion
                validateElementIsNotActivatedForTerminatedFlowScope(
                    process, activateInstructions, terminateInstructions))
```

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 5]
```diff
@@ -674,6 +687,149 @@ private boolean isFlowScopeOfElement(
     return false;
   }
 
+  private Either<Rejection, ?> validateElementIsNotActivatedForTerminatedFlowScope(
+      final ElementInstance processInstance,
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]:
```suggestion
```

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 6]
```diff
@@ -674,6 +687,149 @@ private boolean isFlowScopeOfElement(
...
+      if (terminatedInstance == null) {
+        continue;
+      }
+
+      final var terminatedElement =
+          process.getProcess().getElementById(terminatedInstance.getValue().getElementId());
+      // Find all elements that have the terminated element as flow scope
+      // consider nested flow scopes as well as activate instructions that has ancestor scope key
+      // set
+
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]:
```suggestion
```

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 7]
```diff
@@ -674,6 +687,149 @@ private boolean isFlowScopeOfElement(
...
+    final String reason =
+        String.format(
+            ERROR_MESSAGE_ACTIVATION_FLOW_SCOPE_TERMINATED,
+            BufferUtil.bufferAsString(process.getBpmnProcessId()),
+            String.join(", ", conflictingActivations));
+
+    return Either.left(new Rejection(RejectionType.INVALID_ARGUMENT, reason));
+  }
+
+  private Either<Rejection, ?> validateFlowScopeNotTerminatedForActivation(
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]: 🔧 This method is now unused, should be removed.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 8]
```diff
@@ -674,6 +687,149 @@ private boolean isFlowScopeOfElement(
...
+    }
+    final String reason =
+        String.format(
+            ERROR_MESSAGE_ACTIVATION_FLOW_SCOPE_TERMINATED,
+            BufferUtil.bufferAsString(process.getBpmnProcessId()),
+            String.join(", ", conflictingActivations));
+    return Either.left(new Rejection(RejectionType.INVALID_ARGUMENT, reason));
+  }
+
+  private Optional<Long> getRequiredFlowScopeKey(
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]: 🔧 Same as above, should be removed

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 9]
```diff
@@ -674,6 +687,149 @@ private boolean isFlowScopeOfElement(
...
+    final Set<Long> terminatedInstanceKeys =
+        terminateInstructions.stream()
+            .map(ProcessInstanceModificationTerminateInstructionValue::getElementInstanceKey)
+            .collect(Collectors.toSet());
+
+    final List<String> conflictingActivations = new ArrayList<>();
+    for (final var terminatedInstanceKey : terminatedInstanceKeys) {
+      final var terminatedInstance = elementInstanceState.getInstance(terminatedInstanceKey);
+      if (terminatedInstance == null) {
+        continue;
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java:705]:
```suggestion
        // this should be already validated in validateElementInstanceExists
        continue;
```

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java [hunk 10]
```diff
@@ -674,6 +687,149 @@ private boolean isFlowScopeOfElement(
...
+
+                    var flowScope = elementToActivate.getFlowScope();
+                    while (flowScope != null) {
+                      final String flowScopeId = BufferUtil.bufferAsString(flowScope.getId());
+                      if (flowScopeId.equals(terminatedElementId)) {
+                        return true;
+                      }
+                      flowScope = flowScope.getFlowScope();
+                    }
+                    return false;
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java]:
```suggestion
                    return isFlowScopeOfElement(elementToActivate, terminatedElementId);
```

**Review by berkaycanbc — APPROVED** [review]
Thanks @tsedekey for accepting the challenge and working on this bug! 🚀 

👍 I've suggested some last minor changes we need to tackle before merging this PR but they do not require another review.

✅ Pre-approved.
