### PR TITLE
Cancel job with incident when canceling the process instance

### LINKED ISSUE #8588: Job of cancelled instance can be activated if an error was thrown on it
**Describe the Bug**
A job can still be activated (that is, Zeebe will return it as part of an ActivateJobsResponse) even after its associated process instance has been cancelled, if an error was previously thrown on that job.

**To Reproduce**
@korthout's method is easier than mine, especially for Camunda folks:

> I was also able to reproduce it through zbctl:
> 
> ```
> zbctl deploy ./one_task.bpmn
> sleep 1
> zbctl create instance one_task
> zbctl activate jobs do_something
> zbctl throwError job 2251799813685256 --errorCode FOO --errorMessage foobar
> sleep 1
> zbctl cancel instance 2251799813685251
> sleep 1
> zbctl activate jobs do_something
> ```
> 
> This activated the job and returned:
> 
> ```
> {
>   "jobs":  [
>     {
>       "key":  "2251799813685256",
>       "type":  "do_something",
>       "processInstanceKey":  "2251799813685251",
>       "bpmnProcessId":  "one_task",
>       "processDefinitionVersion":  1,
>       "processDefinitionKey":  "2251799813685249",
>       "elementId":  "do_something",
>       "elementInstanceKey":  "2251799813685255",
>       "customHeaders":  "{\"what_to_do\":\"nothing\"}",
>       "worker":  "zbctl",
>       "retries":  2,
>       "deadline":  "1642166365427",
>       "variables":  "{}"
>     }
>   ]
> }
> ```

<details>
  <summary>My original method</summary>
  
  ZIP file: [reproduce_bug.zip](https://github.com/camunda-cloud/zeebe/files/7866658/reproduce_bug.zip)

  1. Ensure you have ruby installed, as well as the [zeebe_client ruby gem](https://github.com/zeebe-io/zeebe-client-ruby).
  2. Download the attached ZIP file and expand it to reveal the `reproduce_bug.rb` and `one_task.bpmn` files, and put them in a directory together.
  3. Ensure you have Zeebe running. If you need to change Zeebe's address away from `localhost:26500`, edit the `reproduce_bug.rb` file.
  4. Run `ruby reproduce_bug.rb` and observe the output.

  The script will deploy the included BPMN, create an instance of that process, and activate jobs for that process instance. If the jobs that Zeebe returns are for a running process instance, it will throw an error on them. It will then cancel that process instance and loop around and create another instance. If the jobs that it receives from Zeebe are from a process instance that was already successfully cancelled, it will write a line of output including "[!!! BUG !!!]". The script will exit after 5 occurrences of the bug or 50 loops, whichever happens first.
</details>

**Expected Behavior**
After Zeebe successfully cancels a process instance, no jobs from that instance should ever be returned to a future ActivateJobs request.

**Actual Behavior**
Jobs which previously had an error thrown on them before their process instance was cancelled are being returned to ActivateJobs requests that are placed after their process instance was cancelled.

**Log/Stacktrace**

<details>
  <summary>My original method</summary>
  
  Here is the output of a sample run of the `reproduce_bug.rb` script:
  ```
  $ ruby reproduce_bug.rb
  deploying process definition from /usr/src/app/one_task.bpmn
  deployed process `one_task` with key 2251799813685249
  created instance 2251799813685423
  activated job 2251799813685429 for process instance 2251799813685423
  threw error on job 2251799813685429
  cancelled instance 2251799813685423
  created instance 2251799813685432
  [!!! BUG !!!] activated job 2251799813685429 for cancelled process instance 2251799813685423 [!!! BUG !!!]
  cancelled instance 2251799813685432
  created instance 2251799813685439
  activated job 2251799813685445 for process instance 2251799813685439
  threw error on job 2251799813685445
  cancelled instance 2251799813685439
  created instance 2251799813685448
  [!!! BUG !!!] activated job 2251799813685445 for cancelled process instance 2251799813685439 [!!! BUG !!!]
  cancelled instance 2251799813685448
  created instance 2251799813685455
  activated job 2251799813685461 for process instance 2251799813685455
  threw error on job 2251799813685461
  cancelled instance 2251799813685455
  created instance 2251799813685464
  [!!! BUG !!!] activated job 2251799813685461 for cancelled process instance 2251799813685455 [!!! BUG !!!]
  cancelled instance 2251799813685464
  created instance 2251799813685471
  activated job 2251799813685477 for process instance 2251799813685471
  threw error on job 2251799813685477
  cancelled instance 2251799813685471
  created instance 2251799813685480
  [!!! BUG !!!] activated job 2251799813685429 for cancelled process instance 2251799813685423 [!!! BUG !!!]
  [!!! BUG !!!] activated job 2251799813685445 for cancelled process instance 2251799813685439 [!!! BUG !!!]
  [!!! BUG !!!] activated job 2251799813685477 for cancelled process instance 2251799813685471 [!!! BUG !!!]
  cancelled instance 2251799813685480
  ```
</details>

**Environment:**
 - OS: Debian GNU/Linux 10 in a Docker container
 - Zeebe Version: 1.2.9 and 1.3.0 (verified against both)
 - Configuration: zeebe-kafka-exporter v3.0.0

### PR DESCRIPTION
**Pull request by korthout**
## Description

This fixes a bug where canceling a process instance could lead to a job becoming activatable even though the process instance is terminated. See #8588 for more details.

The bug is fixed by making sure the job is immediately canceled (i.e. deleted from the state) when we terminate the related element instance. We achieve this by writing a Job Canceled event when the TERMINATE_ELEMENT command is being processed. 

This PR fixes the bug in a way that can be backported because it doesn't introduce too many changes. Alternatively, the bug could be fixed by tackling the main issue: applying the Incident Resolved event should not affect the state of a job. Instead, the job should be made activatable by writing a separate Job event in the Resolve Incident Processor. That would be a larger change, with more impact on the event appliers than what this PR proposes. Changes to event appliers should generally be avoided.

## Related issues

closes #8588 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnJobBehavior.java [hunk 1]
```diff
@@ -171,20 +172,15 @@ public void cancelJob(final BpmnElementContext context) {
     final var elementInstance = stateBehavior.getElementInstance(context);
     final long jobKey = elementInstance.getJobKey();
     if (jobKey > 0) {
-      writeJobCancelCommand(jobKey);
+      final State state = jobState.getState(jobKey);
+      if (CANCELABLE_STATES.contains(state)) {
+        final JobRecord job = jobState.getJob(jobKey);
+        stateWriter.appendFollowUpEvent(jobKey, JobIntent.CANCELED, job);
```
Comment (pihme) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnJobBehavior.java:178]: :question:/:x: Can you talk about why you write a `JobIntent.CANCELLED` now instead of using the old `JobIntent.CANCEL` command? (which in turn writes the `JobIntent.CANCELLED` event)

The difference currently is that `jobMetrics.jobCanceled(job.getType());` is not called anymore (which happens in `JobCancelProcessor`. And as soon as we add more logic to `JobCancelProcessor` it will be even more complicated to keep the logic in sync if this call site circumvents the command.

**Review by pihme — CHANGES_REQUESTED** [review]
One question/concern.

Please also create follow-up issues to address the general change you alluded to in your description (resolving incidents should not activate the Job)

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnJobBehavior.java (hunk 1 above)
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnJobBehavior.java:178]: The idea is that writing a command postpones canceling the job to when that command is processed. When the Incident Resolved event is applied shortly after the above code, it looks for a related job and then makes it activatable again. If the command is written, the job is not yet canceled/deleted. So the incident resolved event applier makes the job activatable again. Of course, a short bit later the job is canceled, but there is some period where the job is available to be activated.

IMO there is too much logic in this IncidentResolved event applier. However, I'd rather avoid making a change to the event appliers (remember that events should always lead to the same state, even if that means keeping the result of a bug). We could avoid that by building support for version-dependent event appliers, but we don't have that yet.

Instead, we can simply immediately cancel the job by writing the job canceled event, which deletes the job. The change is small enough to be backported. Does that make sense?

👍 You make a good point about the job metrics, which I completely missed. I'll make sure to add the metric here as well. 🤔 Why is there not a test for this?

Comment (pihme) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnJobBehavior.java:178]: Could you also look at whether `JobCancelProcessor` could get a dependency to `BpmnJobBehavior` ? 

Then we might be able to avoid code duplication if we split up the `cancelJob()` method in `BpmnJobBehavior` in `cancelByWorker()` (without resolving incident) and `cancelBycontainer()` (with resolving incident)

Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnJobBehavior.java]: We've discussed this F2F, but here's a recap. The cancel job command was only written by the engine, it is not available from the gRPC API. Since we'll no longer be writing the command we will deprecate it (this follows in another PR). We'll have some duplicated code between the JobCancelProcessor and the BpmnJobBehavior, but we'll document the duplication in both places.

**Comment by korthout** [comment]
@pihme Please have another look, I'll open an issue for the follow-up work.

**Review by pihme — APPROVED** [review]
good job!

**Comment by korthout** [comment]
bors merge
