### PR TITLE
fix(engine): always accept Deployment CREATE command

### LINKED ISSUE #5688: Chaos cluster is unhealthy because it detects inconsistency on reprocessing
**Describe the bug**

Yesterday I tried to fix our chaos builds, after fixing a script I was wondering why it was still failing. After several retries it was always the same partition which was not coming back. I checked the metrics and saw that partition three is marked as unhealthy.

We can see that the SnapshotDirector is running and tries to create snapshots but this fails with:

```
  exception: "java.lang.RuntimeException: Actor is closed
	at io.zeebe.util.sched.ActorJob.failFuture(ActorJob.java:166) ~[zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorTask.submit(ActorTask.java:98) ~[zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorControl.call(ActorControl.java:136) ~[zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.engine.processor.StreamProcessor.getLastProcessedPositionAsync(StreamProcessor.java:299) ~[zeebe-workflow-engine-0.24.4.jar:0.24.4]
	at io.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector.prepareTakingSnapshot(AsyncSnapshotDirector.java:122) ~[zeebe-broker-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.4.jar:0.24.4]
"   
  logger: "io.zeebe.logstreams.snapshot"   
  message: "Unexpected error in resolving last processed position." 
```

After checking the log it seems that on reprocessing the leader has detected an inconsistency
```
D 2020-10-26T15:28:04.210724Z Broker-0-ManagementRequestHandler Deployment CREATE command for deployment 2251799813760922 was written on partition 3  Broker-0-ManagementRequestHandler
W 2020-10-26T15:28:04.322460Z Broker-0-StreamProcessor-1 Failed to receive deployment response for partitions [3] (topic 'deployment-response-2251799813760928'). Retrying  Broker-0-StreamProcessor-1
D 2020-10-26T15:28:04.323141Z Broker-0-StreamProcessor-1 Pushed deployment 2251799813760928 to all partitions.  Broker-0-StreamProcessor-1
D 2020-10-26T15:28:04.323391Z Broker-0-ManagementRequestHandler Deployment CREATE command for deployment 2251799813760928 was written on partition 3  Broker-0-ManagementRequestHandler
E 2020-10-26T15:28:05.064069Z Broker-0-StreamProcessor-3 Unexpected error on recovery happens.  Broker-0-StreamProcessor-3
  undefined
E 2020-10-26T15:28:05.064851Z Broker-0-StreamProcessor-3 Actor Broker-0-StreamProcessor-3 failed in phase STARTED.  Broker-0-StreamProcessor-3
E 2020-10-26T15:28:05.066459Z Broker-0-ZeebePartition-3 Broker-0-StreamProcessor-3 failed, marking it as unhealthy  Broker-0-ZeebePartition-3

```

In more detail:
```
 insertId: "0mn9mhsyxyn4avzz1"  
 jsonPayload: {
  @type: "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent"   
  context: {…}   
  exception: "io.zeebe.engine.processor.InconsistentReprocessingException: Reprocessing issue detected! Restore the data from a backup and follow the recommended upgrade procedure. [cause: "The intent of the record on the log stream doesn't match to the record from reprocessing.", log-stream-record: {"partitionId":3,"value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPGJwbW46ZGVmaW5pdGlvbnMgeG1sbnM6YnBtbj0iaHR0cDovL3d3dy5vbWcub3JnL3NwZWMvQlBNTi8yMDEwMDUyNC9NT0RFTCIgeG1sbnM6YnBtbmRpPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L0RJIiB4bWxuczpkYz0iaHR0cDovL3d3dy5vbWcub3JnL3NwZWMvREQvMjAxMDA1MjQvREMiIHhtbG5zOnplZWJlPSJodHRwOi8vY2FtdW5kYS5vcmcvc2NoZW1hL3plZWJlLzEuMCIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iRGVmaW5pdGlvbnNfMTlleG96MiIgdGFyZ2V0TmFtZXNwYWNlPSJodHRwOi8vYnBtbi5pby9zY2hlbWEvYnBtbiIgZXhwb3J0ZXI9IlplZWJlIE1vZGVsZXIiIGV4cG9ydGVyVmVyc2lvbj0iMC42LjIiPgogIDxicG1uOnByb2Nlc3MgaWQ9ImJlbmNobWFyayIgbmFtZT0iT25lIHRhc2sgcHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxicG1uOnN0YXJ0RXZlbnQgaWQ9InN0YXJ0IiBuYW1lPSJzdGFydCI+CiAgICAgIDxicG1uOm91dGdvaW5nPlNlcXVlbmNlRmxvd18weGxsMzVqPC9icG1uOm91dGdvaW5nPgogICAgPC9icG1uOnN0YXJ0RXZlbnQ+CiAgICA8YnBtbjpzZXJ2aWNlVGFzayBpZD0idGFzayIgbmFtZT0idGFzayI+CiAgICAgIDxicG1uOmV4dGVuc2lvbkVsZW1lbnRzPgogICAgICAgIDx6ZWViZTp0YXNrRGVmaW5pdGlvbiB0eXBlPSJiZW5jaG1hcmstdGFzayIgLz4KICAgICAgPC9icG1uOmV4dGVuc2lvbkVsZW1lbnRzPgogICAgICA8YnBtbjppbmNvbWluZz5TZXF1ZW5jZUZsb3dfMHhsbDM1ajwvYnBtbjppbmNvbWluZz4KICAgICAgPGJwbW46b3V0Z29pbmc+U2VxdWVuY2VGbG93XzF3a2I1eDU8L2JwbW46b3V0Z29pbmc+CiAgICA8L2JwbW46c2VydmljZVRhc2s+CiAgICA8YnBtbjpzZXF1ZW5jZUZsb3cgaWQ9IlNlcXVlbmNlRmxvd18weGxsMzVqIiBzb3VyY2VSZWY9InN0YXJ0IiB0YXJnZXRSZWY9InRhc2siIC8+CiAgICA8YnBtbjplbmRFdmVudCBpZD0iZW5kIiBuYW1lPSJlbmQiPgogICAgICA8YnBtbjppbmNvbWluZz5TZXF1ZW5jZUZsb3dfMXdrYjV4NTwvYnBtbjppbmNvbWluZz4KICAgIDwvYnBtbjplbmRFdmVudD4KICAgIDxicG1uOnNlcXVlbmNlRmxvdyBpZD0iU2VxdWVuY2VGbG93XzF3a2I1eDUiIHNvdXJjZVJlZj0idGFzayIgdGFyZ2V0UmVmPSJlbmQiIC8+CiAgPC9icG1uOnByb2Nlc3M+CiAgPGJwbW5kaTpCUE1ORGlhZ3JhbSBpZD0iQlBNTkRpYWdyYW1fMSI+CiAgICA8YnBtbmRpOkJQTU5QbGFuZSBpZD0iQlBNTlBsYW5lXzEiIGJwbW5FbGVtZW50PSJiZW5jaG1hcmsiPgogICAgICA8YnBtbmRpOkJQTU5TaGFwZSBpZD0iX0JQTU5TaGFwZV9TdGFydEV2ZW50XzIiIGJwbW5FbGVtZW50PSJzdGFydCI+CiAgICAgICAgPGRjOkJvdW5kcyB4PSIxNzkiIHk9IjEwMyIgd2lkdGg9IjM2IiBoZWlnaHQ9IjM2IiAvPgogICAgICAgIDxicG1uZGk6QlBNTkxhYmVsPgogICAgICAgICAgPGRjOkJvdW5kcyB4PSIxODYiIHk9IjE0NiIgd2lkdGg9IjIzIiBoZWlnaHQ9IjE0IiAvPgogICAgICAgIDwvYnBtbmRpOkJQTU5MYWJlbD4KICAgICAgPC9icG1uZGk6QlBNTlNoYXBlPgogICAgICA8YnBtbmRpOkJQTU5TaGFwZSBpZD0iU2VydmljZVRhc2tfMDYwdWFoM19kaSIgYnBtbkVsZW1lbnQ9InRhc2siPgogICAgICAgIDxkYzpCb3VuZHMgeD0iMjkyIiB5PSI4MSIgd2lkdGg9IjEwMCIgaGVpZ2h0PSI4MCIgLz4KICAgICAgPC9icG1uZGk6QlBNTlNoYXBlPgogICAgICA8YnBtbmRpOkJQTU5FZGdlIGlkPSJTZXF1ZW5jZUZsb3dfMHhsbDM1al9kaSIgYnBtbkVsZW1lbnQ9IlNlcXVlbmNlRmxvd18weGxsMzVqIj4KICAgICAgICA8ZGk6d2F5cG9pbnQgeD0iMjE1IiB5PSIxMjEiIC8+CiAgICAgICAgPGRpOndheXBvaW50IHg9IjI5MiIgeT0iMTIxIiAvPgogICAgICA8L2JwbW5kaTpCUE1ORWRnZT4KICAgICAgPGJwbW5kaTpCUE1OU2hhcGUgaWQ9IkVuZEV2ZW50XzBoejJmbWJfZGkiIGJwbW5FbGVtZW50PSJlbmQiPgogICAgICAgIDxkYzpCb3VuZHMgeD0iNDY0IiB5PSIxMDMiIHdpZHRoPSIzNiIgaGVpZ2h0PSIzNiIgLz4KICAgICAgICA8YnBtbmRpOkJQTU5MYWJlbD4KICAgICAgICAgIDxkYzpCb3VuZHMgeD0iNDczIiB5PSIxNDYiIHdpZHRoPSIxOSIgaGVpZ2h0PSIxNCIgLz4KICAgICAgICA8L2JwbW5kaTpCUE1OTGFiZWw+CiAgICAgIDwvYnBtbmRpOkJQTU5TaGFwZT4KICAgICAgPGJwbW5kaTpCUE1ORWRnZSBpZD0iU2VxdWVuY2VGbG93XzF3a2I1eDVfZGkiIGJwbW5FbGVtZW50PSJTZXF1ZW5jZUZsb3dfMXdrYjV4NSI+CiAgICAgICAgPGRpOndheXBvaW50IHg9IjM5MiIgeT0iMTIxIiAvPgogICAgICAgIDxkaTp3YXlwb2ludCB4PSI0NjQiIHk9IjEyMSIgLz4KICAgICAgPC9icG1uZGk6QlBNTkVkZ2U+CiAgICA8L2JwbW5kaTpCUE1OUGxhbmU+CiAgPC9icG1uZGk6QlBNTkRpYWdyYW0+CjwvYnBtbjpkZWZpbml0aW9ucz4K","resourceType":"BPMN_XML","resourceName":"/tmp/one_task.bpmn"}],"deployedWorkflows":[{"version":1,"bpmnProcessId":"benchmark","workflowKey":2251799813685249,"resourceName":"/tmp/one_task.bpmn"}]},"sourceRecordPosition":199404,"position":199418,"key":2251799813760716,"rejectionType":"NULL_VAL","rejectionReason":"","valueType":"DEPLOYMENT","timestamp":1603726015041,"recordType":"EVENT","intent":"CREATED"}, reprocessing-record: {key=2251799813760716, sourceRecordPosition=199404, intent=DeploymentIntent:CREATE, recordType=COMMAND_REJECTION}]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$verifyRecordMatchesToReprocessing$12(ReProcessingStateMachine.java:407) ~[zeebe-workflow-engine-0.24.4.jar:0.24.4]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.zeebe.engine.processor.ReProcessingStateMachine.verifyRecordMatchesToReprocessing(ReProcessingStateMachine.java:394) ~[zeebe-workflow-engine-0.24.4.jar:0.24.4]
	at io.zeebe.engine.processor.ReProcessingStateMachine.reprocessEvent(ReProcessingStateMachine.java:258) ~[zeebe-workflow-engine-0.24.4.jar:0.24.4]
	at io.zeebe.engine.processor.ReProcessingStateMachine.reprocessNextEvent(ReProcessingStateMachine.java:226) ~[zeebe-workflow-engine-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.4.jar:0.24.4]
```

But this doesn't make any sense. The deployment is used always in the chaos tests and why it should be rejected. It contains only one task.

**To Reproduce**
Run the chaos pipeline.

**Expected behavior**
No errors on running the chaos experiments.

**Environment:**
 - OS: k8s - M cluster
 - Zeebe Version: 0.24.4
 - Configuration: normal

### LINKED ISSUE #5753: Deployment Reprocessing Inconsistency with DeploymentCache
After looking into `DeploymentCreateProcessor` and `WorkflowPersistenceCache`, we can say that the processor is definitely a problem for the reprocessing detection. Depending on the in-memory state of the cache, the `CREATE` command is accepted or rejected. So, it depends on which records the processor has processed before (independently from the actual records on the log stream). 

On reprocessing, if the processor reads more or less `CREATE` commands as the processor that wrote the follow-up event (`CREATED` / rejection) then it produces a different follow-up event and it is detected as reprocessing issue.

_Originally posted by @saig0 in https://github.com/zeebe-io/zeebe/issues/5688#issuecomment-721021464_

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

 * removes one of the in-memory deployment caches
 * always accept depmloyment create commands on other partitions, before it was rejected which can lead to inconsistency problems

## Related issues

closes https://github.com/zeebe-io/zeebe/issues/5753
closes https://github.com/zeebe-io/zeebe/issues/5688

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/main/java/io/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java [hunk 1]
```diff
@@ -13,10 +13,10 @@
 import io.zeebe.engine.processing.streamprocessor.writers.TypedStreamWriter;
 import io.zeebe.engine.state.deployment.WorkflowState;
 import io.zeebe.protocol.impl.record.value.deployment.DeploymentRecord;
-import io.zeebe.protocol.record.RejectionType;
 import io.zeebe.protocol.record.intent.DeploymentIntent;
 
 public final class DeploymentCreateProcessor implements TypedRecordProcessor<DeploymentRecord> {
+
   public static final String DEPLOYMENT_ALREADY_EXISTS_MESSAGE =
       "Expected to create a new deployment with key '%d', but there is already an existing deployment with that key";
```
Comment (saig0) [inline engine/src/main/java/io/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java:21]: This string is not used anymore :wastebasket:

File: engine/src/test/java/io/zeebe/engine/processing/deployment/DeploymentCreateProcessorTest.java [hunk 2]
```diff
@@ -73,12 +74,12 @@ public void shouldRejectTwoCreatingCommands() {
...
             DeploymentIntent.CREATED,
             DeploymentIntent.CREATE,
-            DeploymentIntent.CREATE);
+            DeploymentIntent.CREATED);
     //
     Assertions.assertThat(collect)
         .extracting(Record::getRecordType)
         .containsExactly(
-            RecordType.COMMAND, RecordType.EVENT, RecordType.COMMAND, RecordType.COMMAND_REJECTION);
+            RecordType.COMMAND, RecordType.EVENT, RecordType.COMMAND, RecordType.EVENT);
```
Comment (saig0) [inline engine/src/test/java/io/zeebe/engine/processing/deployment/DeploymentCreateProcessorTest.java:82]: Since the behavior changes, we should also change the name of the test method `shouldRejectTwoCreatingCommands()`.

**Review by saig0 — APPROVED** [review]
Thanks @Zelldon :cookie: 

Just two minor comments :wink:

**Comment by Zelldon** [comment]
Thanks @saig0 I have overseen that you alread accepted. So I squash and merge ok?

**Comment by saig0** [comment]
Sure! Go for it :+1:

**Review by saig0 — APPROVED** [review]
