### PR TITLE
fix: populate startDate for batch operations in ES/OS

### LINKED ISSUE #42165: V2 Batch Operation Search: `startDate` missing in API response despite being documented
### 

### 

### 

### 

### Description

In the V2 API endpoint `POST: /v2/batch-operations/search`, the response does not include a `startDate` field, although it is documented in the API and appears in the request and response schema. Example response:
```
{
  "items": [
    {
      "batchOperationKey": "2251799813687227",
      "state": "COMPLETED",
      "batchOperationType": "CANCEL_PROCESS_INSTANCE",
      "endDate": "2025-12-04T16:47:49.319+01:00",
      // startDate absent
    }
    ...
  ]
}
```
Feedback from internal acceptance test: startDate is null in the backend, and `null` fields are not sent in the V2 API. For ES/OS, the `BatchOperationInitializedHandler` never picks up records, so documents never have startDate set. For RDBMS, startDate is set on `CREATED` event, for ES/OS only on `INITIALIZED` (these semantics are inconsistent).

### Steps to reproduce

1. Call `POST: v2/batch-operations/search` for batch operations with the request schema documented in API
2. Observe that the startDate field is not present in the response (even when documented)
3. Compare behavior for different backends (RDBMS, ES/OS)
4. Check acceptance test: `BatchOperationSearchIT`, where documents in ES/OS never have startDate
5. Review handlers: `BatchOperationInitializedHandler` (ES/OS), `BatchOperationCreatedExportHandler` (RDBMS)

### Current behavior

- The API does not send the startDate field (it is null in ES/OS, and omitted in V2 API response).
- Documents in ES/OS never have startDate populated; RDBMS sometimes does.
- Backend implementation and event handling for batch operations divergent between ES/OS and RDBMS (see discussion above for handler details).
- This blocks FE functionality that relies on the startDate.

### Expected behavior

- startDate should be present in the API response when documented, and populated when available
- startDate semantics should be consistent between backends (ES/OS and RDBMS), set either on `INITIALIZED` or `CREATED` event based on what makes sense for both systems
- API should not omit documented fields critical for FE usage

### Workaround

Assume that `startDate` is provided as documented in the frontend for now (for FE development), and fix the backend bug to unblock correct data flow.

### Environment

SaaS & SM

### Version

- Component Version: [unknown, reproduced in current IT]
- Zeebe batch processing
- ES/OS and RDBMS variants
- See `BatchOperationSearchIT`, `BatchOperationInitializedHandler`, `BatchOperationCreatedExportHandler`

### Rootcause

`BatchOperationInitializedHandler` in ES/OS does not pick up records, so never sets `startDate`; for RDBMS, startDate set on CREATED event. Divergent event semantics. Null is omitted from API response per V2 API logic.

### Solution ideas

- Verify and align event handling for batch operations between ES/OS and RDBMS
- Ensure BatchOperationInitializedHandler picks up correct records in ES/OS
- Consider setting startDate on `CREATED` for both backends
- Ensure startDate is present and non-null in API if available
- Test via acceptance tests (`BatchOperationSearchIT`) for expected field population
- Discuss FE impact if field remains missing

### Dev -> QA handover

- Resources: `BatchOperationSearchIT` acceptance test, API documentation for V2
- Versions to validate: ES/OS and RDBMS, frontend integration
- Release version: TBD (upon bugfix)

### Links

- Source discussion: @korthout, @tmetzke, @OmranAbazid, charlie BE team
- Handler implementation: `BatchOperationInitializedHandler`, `BatchOperationCreatedExportHandler`
- Test: `BatchOperationSearchIT`
- API Docs: batch operations V2

### Automated Test Impact

Bug observed in acceptance test `BatchOperationSearchIT`. Fix must ensure that test passes and field is consistently populated for both backends.

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

The V2 API endpoint `POST: /v2/batch-operations/search` was not returning the `startDate` field for batch operations when using ES/OS as the secondary database.
The `startDate` was not populated because `BatchOperationInitializedHandler` was never invoked.

### Root cause

Two issues prevented the `BatchOperationInitializedHandler` from being invoked:
1. **Incorrect `ValueType` in handler:** `BatchOperationInitializedHandler.getHandledValueType()` incorrectly returned `ValueType.BATCH_OPERATION_CREATION` instead of `ValueType.BATCH_OPERATION_INITIALIZATION`. This caused a type mismatch since the handler expects `BatchOperationInitializationRecordValue` records but was registered for the wrong value type (see [ValueTypeMapping](https://github.com/camunda/camunda/blob/57b0dd55f8f907a8150ddd410472780c9d0369f8/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/ValueTypeMapping.java#L324-L326)).

2. **Missing value type in exporter filter:** `CamundaExporter.VALUE_TYPES_2_EXPORT` did not include `BATCH_OPERATION_INITIALIZATION`, causing records with this value type to be filtered out before reaching any handler.

As a result, the `INITIALIZED` event was never processed by the ES/OS exporter, so `startDate` and the `ACTIVE` state were never set on batch operation documents in Elasticsearch/OpenSearch.

### Changes

| File | Change |
|------|--------|
| `BatchOperationInitializedHandler` | Changed `getHandledValueType()` to return `ValueType.BATCH_OPERATION_INITIALIZATION` |
| `CamundaExporter` | Added `BATCH_OPERATION_INITIALIZATION` to the `VALUE_TYPES_2_EXPORT` set |
| `BatchOperationInitializedHandlerTest` | Updated test to verify correct value type |
| `BatchOperationSearchIT` | Added assertions to verify `startDate` field is populated in batch operation search responses |

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes)).

## Related issues

closes #42165

### CODE REVIEW

**Comment by ce-dmelnych** [comment]
Adding the `backport stable/8.8` label as this bug also affects the 8.8 branch, the [`BatchOperationInitializedHandler`](https://github.com/camunda/camunda/blob/2a780f1cb266c1dadcd76d94770027ed2ddd4d33/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationInitializedHandler.java#L36) has the same incorrect value type there.
Other versions are not affected since this handler was introduced in 8.8.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationInitializedHandler.java [hunk 1]
```diff
@@ -33,7 +33,7 @@ public BatchOperationInitializedHandler(final String indexName) {
 
   @Override
   public ValueType getHandledValueType() {
-    return ValueType.BATCH_OPERATION_CREATION;
+    return ValueType.BATCH_OPERATION_INITIALIZATION;
```
Comment (korthout) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationInitializedHandler.java:36]: 👍 Nice find!

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java [hunk 2]
```diff
@@ -372,6 +373,7 @@ private record CamundaExporterRecordFilter() implements RecordFilter {
             RESOURCE,
             USER_TASK,
             BATCH_OPERATION_CREATION,
+            BATCH_OPERATION_INITIALIZATION,
```
Comment (korthout) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/CamundaExporter.java:376]: 👍 Also, nice find!

**Review by korthout — APPROVED** [review]
Awesome work @ce-dmelnych! 

👍 Love the straightforward test case additions

LGTM 👍

**Review by mustafadagher — APPROVED** [review]
Thanks a lot @ce-dmelnych ! 🚀 

🔧 if it wouldn't be a lot of effort to ask from you. Could you go over the other handlers (specially from the initialization phase) and make sure they're also correctly mapped and configured to be exported?

**Comment by ce-dmelnych** [comment]
> Thanks a lot @ce-dmelnych ! 🚀
> 
> 🔧 if it wouldn't be a lot of effort to ask from you. Could you go over the other handlers (specially from the initialization phase) and make sure they're also correctly mapped and configured to be exported?

@mustafadagher!
I've gone through the batch and other ES/OS handlers, they all appear to be correctly mapped and configured.

To prevent similar issues from happening in the future, I've also created a PR with test enhancements that will automatically validate `ExportHandler` ValueType configurations and ValueType  registrations: #44994 (addresses #44910).

Feel free to review it when you have time! 🙇🏻
