### PR TITLE
Fix flaky ScaleDownBrokerTest

### LINKED ISSUE #15118: ScaleDownBrokersTest.shouldScaleDownClusterAgain is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 1
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

```
ScaleDownBrokersTest.shouldScaleDownClusterAgain:124 » ConditionTimeout Condition with alias 'until cluster topology is complete' didn't complete within 10 seconds because assertion condition with alias until cluster topology is complete 
Expecting all elements of:
  [TestStandaloneGateway{nodeId = gateway-0}]
to satisfy given requirements, but these elements did not:

TestStandaloneGateway{nodeId = gateway-0}
error: Expected cluster size to be <1> but was <2>.
```

[logs_103432.zip](https://github.com/camunda/zeebe/files/13309818/logs_103432.zip)

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

The test  was flaky because the clusterSize in the gateway topology was 2 instead of 1. This is updated via the gossip/sync from `ClusterTopologyGossiper`. Since it uses a hard-coded delay of 10s, waiting for only 10s is not enough. To fix the flakiness

- Increase the waiting timeout
- Remove dead nodes from sync list in ClusterTopologyGossiper. This ensures the surviving nodes (in this case the gateway) gets the update in next round of sync. 

A better solution is to make the  delays in ClusterTopologyGossiper configurable. We have pending task for it, and will be done later.

## Related issues

closes #15118

### CODE REVIEW

File: topology/src/main/java/io/camunda/zeebe/topology/gossip/ClusterTopologyGossiper.java [hunk 1]
```diff
@@ -284,19 +284,29 @@ public void removeUpdateListener(final TopologyUpdateListener listener) {
...
+      executor.run(
+          () -> {
+            if (config.enableSync()) {
+              sync(event.subject().id());
+            }
+          });
+      case MEMBER_REMOVED ->
+      // When a member is removed, remove it from the list of members to sync so that we don't try
+      // to sync with it in the next round. This is only for optimization.
+      executor.run(() -> membersToSync.remove(event.subject().id()));
```
Comment (oleschoenburg) [inline topology/src/main/java/io/camunda/zeebe/topology/gossip/ClusterTopologyGossiper.java:305]: :x: I believe this will fail until `refreshMembersToSync` is called for the first time because we initialize `membersToSync` with `List.of()` which is immutable and throws an exception on `remove`.

**Review by lenaschoenburg — APPROVED** [review]
Nice optimization :+1: 

Please take a look at my comment to prevent (probably very rare) exceptions.

**Comment by deepthidevaki** [comment]
bors merge
