### PR TITLE
fix(engine): Added null-check to ProcessMessageStartEventMessageNameValidator

### LINKED ISSUE #5510: NPE in ProcessMessageStartEventMessageNameValidator.validateMessageName
**Describe the bug**
Observed as error in production logs.

**Expected behavior**
* no NPEs in input validation

**Log/Stacktrace**
https://console.cloud.google.com/errors/CK-E7ry54eavQA?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Fix for NPE during validation of new deployment.

## Related issues

closes #5510 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java [hunk 1]
```diff
@@ -642,6 +642,29 @@ public void shouldRejectDeploymentWithInvalidTimerStartEventExpression() {
...
+
+    // then
+    Assertions.assertThat(deployment)
+        .hasRejectionType(RejectionType.INVALID_ARGUMENT)
+        .hasRejectionReason(
+            "Expected to deploy new resources, but encountered the following errors:\n"
+                + "'process.bpmn': - Element: messageEvent\n"
+                + "    - ERROR: Must reference a message\n");
+  }
+
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java:667]: :x: First of all, the test case is nicely written :+1: Since the class contains already many test cases, we should add the new test case somewhere else.

The unit test `ProcessMessageStartEventMessageNameValidatorTest` would be an option. The downside is that it just test the validator itself.

I suggest creating a new test class for message validation tests. It could look similar to `TimerValidationTest` (without the parameterized style) and follow the "new" JUnit 5 style.

In order to verify the expected message using `ProcessValidationUtil`. We need to add the `ZeebeDesignTimeValidators` to the validation result.

**Review by saig0 — CHANGES_REQUESTED** [review]
Looks good and works :+1: 

Please have a look at my suggestion :cake:

**Review by saig0 — APPROVED** [review]
I like it :1st_place_medal: 

One more JUnit 5 test :rocket:

**Comment by remcowesterhoud** [comment]
bors -r

**Comment by remcowesterhoud** [comment]
bors retry

**Comment by saig0** [comment]
@remcowesterhoud let's backport this fix to `stable/1.0` and `stable/1.1`.
