### PR TITLE
fix(snapshots): flush snapshot to disk

### LINKED ISSUE #7136: Follower doesn't start with corrupted snapshot
**Describe the bug**
For some reason, one follower of a three-node cluster has a corrupted snapshot. If the follower restarts then it detects that the snapshot is corrupted and shut down again.

The follower doesn't recover by itself. It requires manual interaction. 
After deleting the data of the follower, it starts again and joins the cluster.

Related issue: #6907

**To Reproduce**
It is not clear why the snapshot was corrupted. It may be related to an infrastructure issue where the volumes were unattached.

1. the snapshot was replicated from the leader ([logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%22995d359b-4e17-482f-a538-bd756585e31e-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22;timeRange=2021-05-23T11:33:08.633Z%2F2021-05-27T11:33:08.633820Z;pinnedLogId=2021-05-25T14:49:36.097674Z%2F1de9lmjg42mpjo5;cursorTimestamp=2021-05-25T14:57:41.501966111Z?authuser=0&project=camunda-cloud-240911))
2. after a restart (not gracefully), the node read the snapshot and detected that it is corrupted ([logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%22995d359b-4e17-482f-a538-bd756585e31e-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22;timeRange=2021-05-23T11:33:08.633Z%2F2021-05-27T11:33:08.633820Z;pinnedLogId=2021-05-25T14:57:47.118977Z%2Ft4vtvuf153wqh;cursorTimestamp=2021-05-25T14:57:49.327746Z?authuser=0&project=camunda-cloud-240911)) 
```
Expected snapshot /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/46497-11-46487-46488 to have checksum 1338043633, but the actual checksum is 892742735; the snapshot is most likely corrupted
```
3. the node failed to start and shut down

**Expected behavior**
The follower detects that the snapshot is corrupted but it can heal itself. For example, by purging the snapshot and receiving a new snapshot from the leader.  

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Expected snapshot /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/46497-11-46487-46488 to have checksum 1338043633, but the actual checksum is 892742735; the snapshot is most likely corrupted
```

</p>
</details>

image

image

The issue was raised as part of an incident (see the [incident doc](https://docs.google.com/document/d/1NCO_5NuDcYtFUHg6-SzC768bi-msaDBVy59qWWb6cDM/edit#)). 

A dump of the data folders was stored [here](https://drive.google.com/drive/u/0/folders/1mUVGUJ0Dt0xqr2ruKV8Zv17URKQFNPRu).

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `1.0.0`
 - Configuration: 
   - replication-factor: 3

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Flushes snapshot changes to disk before acknowledging the snapshot as valid. Also ensure that metadata changes are persisted.

## Related issues

closes #7136

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java [hunk 1]
```diff
@@ -169,12 +171,16 @@ private boolean isSnapshotIdInvalid(final String snapshotId) {
...
-        StandardOpenOption.WRITE);
+      final SnapshotChunk snapshotChunk, final Path snapshotFile) {
+    try (var file = new RandomAccessFile(snapshotFile.toFile(), "ws")) {
+      final FileChannel channel = file.getChannel();
+      final ByteBuffer buffer = ByteBuffer.wrap(snapshotChunk.getContent());
+      channel.write(buffer);
+    } catch (IOException e) {
+      LOGGER.warn("Failed to write snapshot chunk {}", snapshotChunk, e);
+      return FAILED;
+    }
```
Comment (npepinpe) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:182]: You can open a file channel directly by using `FileChannel.open`.

Additionally, the way `FileChannel.write` works, you want to write incrementally in small buffers. If you look into it, it uses a direct buffer to write all the time. This is a good indicator that we should eventually use direct buffers here, but for now as we can't/don't, it will use a cached native buffer - unless the buffer is too big, at which point it allocates it fresh every time. It'll still have to copy the memory though, but that's not really any different than with the old I/O since it still had to cross the JVM boundary before being written.

Additionally, you have to keep in mind that `FileChannel#write` may not write all bytes - so you want to make sure it does by running:

```java
while (buffer.hasRemaining()) {
  final var chunkSize = Math.min(buffer.capacity(), buffer.position() + IoUtil.BLOCK_SIZE);
  channel.write(buffer.limit(chunkSize));
}
```

I use `IoUtil.BLOCK_SIZE` here, but tbh I'm not sure what's the real optimal size. Generally aligned sizes are just better (since the underlying buffer is aligned as well, even if you don't use an aligned size), but I know some people report using bigger blocks will work better - might be true especially since we use network attached storage, so we might want to use something more like 512KB. I think over 1MB it might not get cached anyway, and 512KB is a good size for our snapshot files.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java [hunk 2]
```diff
@@ -505,6 +508,10 @@ private void tryAtomicDirectoryMove(final Path directory, final Path destination
       LOGGER.warn("Atomic move not supported. Moving the snapshot files non-atomically.");
       Files.move(directory, destination);
     }
+
+    try (var stream = new FileOutputStream(destination.toFile())) {
+      stream.getFD().sync();
```
Comment (npepinpe) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java:513]: Is opening a stream the only way to get a file descriptor? What about reusing the same as the file channel?

```java
try (final var channel = FileChannel.open(destination)) {
  channel.force(true);
}
```

I'm not sure if you can open a file channel to a directory though :sweat_smile:

Comment (npepinpe) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java:513]: Reading through https://mail.openjdk.java.net/pipermail/nio-dev/2015-May/003140.html, it looks like it should be possible.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java [hunk 3]
```diff
@@ -471,6 +473,7 @@ private void moveToSnapshotDirectory(final Path directory, final Path destinatio
           destination,
           e);
     } catch (final IOException e) {
+      LOGGER.warn("Failed to move snapshot directory {} to {}", directory, destination, e);
```
Comment (npepinpe) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java:476]: We already log the error after it bubbles up, no? What does it look like now if a failure occurs here? I'm not sure it's worth logging if we rethrow the exception.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java [hunk 4]
```diff
@@ -169,12 +171,16 @@ private boolean isSnapshotIdInvalid(final String snapshotId) {
...
-        snapshotFile,
-        snapshotChunk.getContent(),
-        StandardOpenOption.CREATE_NEW,
-        StandardOpenOption.WRITE);
+      final SnapshotChunk snapshotChunk, final Path snapshotFile) {
+    try (var file = new RandomAccessFile(snapshotFile.toFile(), "ws")) {
+      final FileChannel channel = file.getChannel();
+      final ByteBuffer buffer = ByteBuffer.wrap(snapshotChunk.getContent());
+      channel.write(buffer);
+    } catch (IOException e) {
```
Comment (npepinpe) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:179]: Why catch the error now? Actually, I wonder why bother with returning a boolean and let the error bubble up?

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java [hunk 5]
```diff
@@ -438,6 +438,7 @@ JournalSegment createSegment(final JournalSegmentDescriptor descriptor) {
       throw new JournalException(e);
     } finally {
       try {
+        channel.force(true);
```
Comment (npepinpe) [inline journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:441]: Let's drop this and create a separate PR to deal with the log stuff. I'd like to take that opportunity to refactor the segment creation anyway.

**Review by npepinpe — CHANGES_REQUESTED** [review]
Thanks!

I'm now also wondering if we need to fsync the directory after deleting files? I guess not? I think for our use cases it wouldn't matter anyway.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java (hunk 4 above)
Comment (MiguelPires) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:179]: Because the apply method returns true or false for sucess/failure. Bubbling up the error wouldn't meet that interface and it would fail the actor

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java (hunk 5 above)
Comment (MiguelPires) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java:441]: Do you want to create an issue for that?

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java (hunk 1 above)
Comment (MiguelPires) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:182]: Why is using more and "smaller" writes better? Looking at `write()`'s implementation, the maximum buffer (until it's too big to cache) is Long.MAX_VALUE unless 'jdk.nio.maxCachedBufferSize' is set. I googled around briefly for some best practices/analysis on this but didn't find anything conclusive
Also, that code snippet limits the buffer size and then calls `hasRemaining()` but I think we need to reset the limit to the capacity. Otherwise, if a buffer has more than BLOCK_SIZE, we would write that and then exit since `hasRemaining()` would return false

Comment (npepinpe) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java]: Yeah, that block is wrong, I just wrote it otoh, you're right that just setting the limit wouldn't work. I looked around, and I also couldn't find conclusive evidence that writing in smaller chunks is "better" - this is something I learned as a best practice a long time ago, and rule of thumb was always to read/write in smaller, aligned chunks. What I did find seems to corroborate this, but I couldn't find anyone giving a conclusive reason, just a bunch of benchmarks.

Regarding the buffer size, one potential issue I see here is allocating and caching an unknown buffer size. Keep in mind that direct memory is not managed by the heap, and while it's garbage collected, it works a bit differently (in that you don't really know when the native memory is really reclaimed). Additionally, it uses a different pool with different configuration (e.g. `-XX:MaxDirectMemorySize`). It's probably usually fine, but IDK - I'm not too hot about allocating a randomly sized buffer, even when it's cached. I'm not sure when is that cache cleaned - when the thread exits? But if it runs on the actor thread, then it's never cleaned? I'd rather get a smaller buffer if it's going to be long living.

IDK - wdyt?

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java (hunk 4 above)
Comment (npepinpe) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:190]: But previously we did let it bubble, which is why I was confused by the change. Can you elaborate on the differences?

File: journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java (hunk 5 above)
Comment (npepinpe) [reply journal/src/main/java/io/camunda/zeebe/journal/file/SegmentedJournal.java]: I can do that :+1:

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java [hunk 6]
```diff
@@ -31,6 +31,7 @@
   private static final Logger LOGGER = LoggerFactory.getLogger(FileBasedReceivedSnapshot.class);
   private static final boolean FAILED = false;
   private static final boolean SUCCESS = true;
+  private static final int BLOCK_SIZE = 1 << 19;
```
Comment (npepinpe) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:34]: Is that 512Kb? :smile: I always have an easier time reading `512 * 1024`, but idk if that's a strong argument for it.

Comment (MiguelPires) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:34]: That's fair, I'll change it

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java (hunk 1 above)
Comment (MiguelPires) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java]: Thanks, I just wanted to see if there was some mechanism I wasn't getting, performance/buffer issues are not very transparent. I definitely understand the concern of not allocating a buffer of unknown size. As it is atm, the buffer will be at most 512Kb so it should meet those criteria

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java [hunk 7]
```diff
@@ -169,12 +172,26 @@ private boolean isSnapshotIdInvalid(final String snapshotId) {
...
-        snapshotChunk.getContent(),
-        StandardOpenOption.CREATE_NEW,
-        StandardOpenOption.WRITE);
+      final SnapshotChunk snapshotChunk, final Path snapshotFile) {
+    try (var channel =
+        FileChannel.open(
+            snapshotFile,
+            StandardOpenOption.CREATE_NEW,
+            StandardOpenOption.WRITE,
+            StandardOpenOption.SYNC)) {
```
Comment (npepinpe) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:181]: If we open it in SYNC mode, will it basically sync after every `write` operation? Can we avoid this and sync only once at the end when we've written the whole file?

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java (hunk 4 above)
Comment (MiguelPires) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:190]: What I said was wrong, my bad. The interface does expect an IOException and its consumers handle it.  Although I think letting an exception bubble up would fail the actor and complete the future exceptionally so that's even more confusing. Seems like there's 3 ways this interface can inform a consumer of a failure: completing the future with false, completing the future exceptionally and throwing an exception. I can refactor this, should I do it in this PR or separately?

Comment (npepinpe) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:187]: Let's do it in a separate PR so we can merge this now. What's your plan for refactoring it?

**Review by npepinpe — APPROVED** [review]

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java (hunk 4 above)
Comment (MiguelPires) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedReceivedSnapshot.java:187]: I'll have to look closely but off the top of my head: remove the IOException from the interface, catch exceptions in the implementation and complete the future exceptionally. Then change `Future<Boolean>` to `Future<Void>` and throw some SnapshotFailureException instead of completing the future with false. Then the consumers wouldn't need to catch exceptions, check for exceptions in the future and for a future completed with "false". They could just check if the future is completed with an exception.

**Comment by npepinpe** [comment]
/backport

I forgot what the command is :sweat_smile:
