### PR TITLE
fix: do not retake backup if it already exists

### LINKED ISSUE #12623: After restoring from backup, a partition re-takes the backup
**Describe the bug**

After restoring from backup, if the leader that took the original backup is no more the leader of the partition, this can result in a duplicate backup of the partition with the same backup id. The new backup is logically equivalent to the old backup. So it doesn't matter which backup we use later. However, re-taking the backup is unnecessary as it wastes resources.

**To Reproduce**
Restore zeebe from a backup, and observe the logs or inspect the backup store.

**Expected behavior**
A partition should not re-take a backup after restore.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

In this PR, we check if the backup exists for that partition by listing using the wildcard. This returns the backups taken by other nodes as well. The backup is taken only if no backup exists for that partition with the same checkpointId. Previiously, we were checking using the full backupId which included the nodeId, so it can only find the backup taken by the same node. This is not ideal, because it can result in duplicate unnecessary backups, for example after restoring from a backup.

## Related issues

closes #12623 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: backup/src/main/java/io/camunda/zeebe/backup/management/BackupServiceImpl.java [hunk 1]
```diff
@@ -63,12 +71,17 @@ ActorFuture<Void> takeBackup(
...
+      final Collection<BackupStatus> availableBackups,
       final InProgressBackup inProgressBackup,
       final ConcurrencyControl concurrencyControl,
       final ActorFuture<Void> backupSaved) {
 
-    switch (status.statusCode()) {
+    final BackupStatusCode existingBackupStatus =
+        availableBackups.isEmpty()
+            ? BackupStatusCode.DOES_NOT_EXIST
+            : Collections.max(availableBackups, Comparator.comparing(BackupStatus::statusCode))
```
Comment (oleschoenburg) [inline backup/src/main/java/io/camunda/zeebe/backup/management/BackupServiceImpl.java:82]:
```suggestion
            : Collections.max(availableBackups, BackupStatusCode.BY_STATUS)
```

**Review by lenaschoenburg — APPROVED** [review]
Nice and simple solution, thanks @deepthidevaki :+1:

**Comment by deepthidevaki** [comment]
bors merge
