### PR TITLE
fix: properly limit s3 transfer concurrency

### LINKED ISSUE #33726: Thread starvation risk when taking backup on S3
### 

### 

, , , , , 

### 

### 

### Description

When lots of files are being backupped, there is a high risk of thread starvation in `S3BackupStore/FileSetManager`.

### Steps to reproduce

1. take a backup with a lot of files
2. Backup never terminates

### Current behavior

The backup never terminates. No new backup can be taken.

### Expected behavior

The backup is able to terminate successfully using at most the number of configured connections

### Environment

SaaS & SM

### Version

- from 8.3 onwards

### Rootcause

This is caused by a blocking semaphore that is used to limit the amount of concurrent uploads and the use of a fixed size (compute) pool (default ForkJoin).
All threads end up being blocked by the locked acquired by the semaphore and the completion callbacks from successful file uploads cannot continue.

### Solution ideas

Remove the use of semaphores altogether and create an executor with a maximum amount of threads equal to the connection limit.
Use this thread pool as executor for all futures related to backup uploads.
Potentially, a couple of threads more can be added so that callbacks can be run on them.
A `CachedThreadPool` may be a good pool if blocking IO is used.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Incident Internal: [#inc-support-27646-taking-a-s3-backup-of-zeebe-hangs](https://camunda.slack.com/archives/C08V5JE8VV5)

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This fixes two problems at the same time:
1. The previous approach that relied on orchestrating everything in
terms of CompletableFutures could deadlock on the uploadLimit semaphore.
2. Downloads were not limited properly.

Instead of combining futures, we now spawn virtual threads for each file to save/restore and use blocking code. Because semaphores play nicely with virtual threads, we avoid the deadlock.

closes #33726
closes #33957

### CODE REVIEW

File: zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java [hunk 1]
```diff
@@ -53,50 +54,62 @@ public FileSetManager(final S3AsyncClient client, final S3BackupConfig config) {
     // concurrent uploads to half of the number of available connections.
     // This should prevent ConnectionAcquisitionTimeout for backups with many and/or large files
     // where we would otherwise occupy all connections, preventing some uploads from starting.
-    uploadLimit = new Semaphore(Math.max(1, config.maxConcurrentConnections() / 2));
+    concurrencyLimit = new Semaphore(Math.max(1, config.maxConcurrentConnections() / 2));
+    threadBuilder = Thread.ofVirtual().name("zeebe-backup-", 0);
```
Comment (entangled90) [inline zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java]:
```suggestion
    threadBuilder = Thread.ofVirtual().name("zeebe-backup-s3", 0);
```
So it's clear it's the `S3BackupStore` and not for example the `BackupService`?

File: zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java [hunk 2]
```diff
@@ -53,50 +54,62 @@ public FileSetManager(final S3AsyncClient client, final S3BackupConfig config) {
...
             Entry::getKey,
-            namedFile -> saveFile(prefix, namedFile.getKey(), namedFile.getValue()))
+            namedFile -> schedule(() -> saveFile(prefix, namedFile.getKey(), namedFile.getValue())))
         .thenApply(FileSet::new);
   }
 
-  private CompletableFuture<FileSet.FileMetadata> saveFile(
-      final String prefix, final String fileName, final Path filePath) {
+  /** Schedules a task to be executed asynchronously, respecting the concurrency limit. */
+  private <T> CompletableFuture<T> schedule(final Supplier<T> task) {
```
Comment (entangled90) [inline zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java:71]: :wrench: why not using a `Executors.newThreadPerTaskExecutor` and do a `Executor.submit`?

File: zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java [hunk 3]
```diff
@@ -53,50 +54,62 @@ public FileSetManager(final S3AsyncClient client, final S3BackupConfig config) {
...
-              })
-          .whenComplete((success, error) -> uploadLimit.release());
+      final var compressedFile = compressFile(filePath, algorithm);
+      LOG.trace("Saving compressed file {}({}) in prefix {}", fileName, compressedFile, prefix);
+      client
+          .putObject(
+              put -> put.bucket(config.bucketName()).key(prefix + fileName),
+              AsyncRequestBody.fromFile(compressedFile))
+          .join();
+      cleanupCompressedFile(compressedFile);
```
Comment (entangled90) [inline zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java]: :wrench: can we cleanup with a `try/finally` clause?

File: zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java [hunk 4]
```diff
@@ -126,7 +139,7 @@ private Path compressFile(final Path file, final String algorithm) {
           final var output = new BufferedOutputStream(Files.newOutputStream(compressedFile));
           final var compressedOutput =
               new CompressorStreamFactory().createCompressorOutputStream(algorithm, output)) {
-        IOUtils.copy(input, compressedOutput);
+        input.transferTo(compressedOutput);
```
Comment (entangled90) [inline zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java:145]: :rocket:

File: docs/virtual_threads.md [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+```
+
+**Why this works well:**
+- Each file operation runs in its own virtual thread, so blocking code is simple and readable.
+- The semaphore ensures you never exceed the allowed number of concurrent S3 operations.
+- No thread pooling or complex future composition is needed.
+
+---
+
+This pattern is especially useful for I/O-heavy workloads where you want to avoid the complexity of asynchronous code, but still need to limit the number of concurrent operations to avoid exhausting resources (such as S3 connections).
```
Comment (entangled90) [inline docs/virtual_threads.md]: :thought_balloon:  I would get rid of this sentence, feels a bit repetitive

File: docs/virtual_threads.md [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+**Do not** use virtual threads for:
+- CPU-bound tasks (virtual threads do not make computation faster).
+- Long-running or infinite loops.
+
+## Best Practices
+
+- **Do not pool virtual threads.** Create a new virtual thread for each task.
+- **Keep virtual thread lifetimes short.** They are cheap to create, but should not be held indefinitely.
+- **Avoid thread-local state for resource pooling.** Use thread locals only when necessary, and never to pool expensive resources.
+- **Be aware of pinning:** Use of `synchronized` or native methods can pin a virtual thread to its carrier, reducing scalability. Prefer `ReentrantLock` for long-running or I/O-guarded critical sections.
```
Comment (entangled90) [inline docs/virtual_threads.md:23]: :question: how can one be sure that some code being called is not using `synchronized`? feels a bit risky until we target jdk 24+ (25 is an LTS)

File: zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java [hunk 7]
```diff
@@ -53,50 +54,62 @@ public FileSetManager(final S3AsyncClient client, final S3BackupConfig config) {
...
-                    .thenApply(unused -> FileSet.FileMetadata.withCompression(algorithm));
-              })
-          .whenComplete((success, error) -> uploadLimit.release());
+      final var compressedFile = compressFile(filePath, algorithm);
+      LOG.trace("Saving compressed file {}({}) in prefix {}", fileName, compressedFile, prefix);
+      client
+          .putObject(
+              put -> put.bucket(config.bucketName()).key(prefix + fileName),
+              AsyncRequestBody.fromFile(compressedFile))
+          .join();
```
Comment (entangled90) [inline zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java]: :thought_balloon: Should we add some configurable timeouts here?
It may be helpful in getting to the root cause in case it takes more time than expected.
If the timeout is too stringent, then the user can make a bigger one and retry

Comment (lenaschoenburg) [reply zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java]: Before we didn't have a timeout either so for now I'd continue to trust the client to timeout properly. I'm a bit hesitant to add too many layers of timeouts and concurrency layers. Keeping them all in sync (i.e. properly configured) is tedious and the resulting behavior can be confusing.

File: docs/virtual_threads.md (hunk 6 above)
Comment (lenaschoenburg) [reply docs/virtual_threads.md:23]: I'd refer you to the "Observability and Debugging" section :wink: 
> The system property `jdk.tracePinnedThreads` can help diagnose pinning issues.

I think it's generally an acceptable risk, it's mostly that performance is not good because the JFP has to spin up compensation threads on the fly.

File: zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java (hunk 2 above)
Comment (lenaschoenburg) [reply zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java:71]: Ha, @npepinpe had the same suggestion. I tried it out an the code is almost exactly the same, with the only difference being that we don't have to `close` the executor this way.

File: docs/virtual_threads.md [hunk 8]
```diff
@@ -0,0 +1,98 @@
...
+  void save(final String prefix, final NamedFileSet files) {
+    for (final var namedFile : files.namedFiles().values()) {
+      final var fileName = namedFile.fileName();
+      final var filePath = namedFile.filePath();
+
+      // Start a virtual thread for each file operation
+      threadBuilder.start(() -> {
+        try {
+          // Block until a permit is available
+          concurrencyLimit.acquire();
```
Comment (entangled90) [inline docs/virtual_threads.md:60]: :wrench: using `tryAcquire` with a large timeout can prevent deadlocks/leaks

Comment (lenaschoenburg) [reply docs/virtual_threads.md:60]: Yeah but here we don't want to time out on purpose. Uploading may be _super_ slow and finding the right timeout is just tedious and frustrating. I'd rather look at a thread dump from time to time than work through N support cases that complain about failed backups because the timeout happened to be too low.

File: zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java (hunk 7 above)
Comment (entangled90) [reply zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java]: That's true, but I would still put a large timeout just to make sure that eventually, this thread would *eventually* terminate and release all associated resources.

File: zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java (hunk 2 above)
Comment (entangled90) [reply zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java:71]: I just realized that we don't keep a handle of the threads created, so we may have a leak.
I assume running virtual threads are not garbage collected as they are GC roots?

File: docs/virtual_threads.md (hunk 8 above)
Comment (entangled90) [reply docs/virtual_threads.md:60]: At that point support can easily suggest to try to increase the timeout so it doesn't take too much. We could potentially tweak it so it's proportional to the number of files. 
Note that this is mostly to clean things up eventually, not really replying within a predefined time to the user.

**Review by entangled90 — APPROVED** [review]
Thanks for this contribution, it's a big improvement from the current state of things.

I see we have a different view on timeouts, so I'll leave that to something that can be done afterwards, depending on what other people think about them.

Thanks :rocket:

File: zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java (hunk 2 above)
Comment (lenaschoenburg) [reply zeebe/backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java:71]: Unless they are blocked (shouldn't happen), they would close and clean up after themselves once the task is done.
