### PR TITLE
test: improve resilience of cached test result extension

### LINKED ISSUE #25641: Improve `CachedTestResultsExtension` resilience on configuration reading
**Description**

* The `CachedTestResultsExtension` reads test configuration from text lines expected to contain at least 2 parts, separated by a `,` character.
* If the test configuration for whatever reason contains a non-conforming line, the extension fails in method `CachedInvocation::fromLine`.
* The extension should be more resilient to such input errors and ignore the line. It should also yield a warning when encountering such lines.

**Context**

* The `RollingUpdateTest` failed multiple times due to a malformed test configuration file.
   * Failed CI run: https://github.com/camunda/camunda/actions/runs/12174197469
   * Test log files: [zeebe-version-compatibility-0.zip](https://github.com/user-attachments/files/18021619/zeebe-version-compatibility-0.zip)
   * Trace:
   ```
   Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.016 s <<< FAILURE! -- in io.camunda.zeebe.test.RollingUpdateTest
   io.camunda.zeebe.test.RollingUpdateTest -- Time elapsed: 0.016 s <<< ERROR!
   java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.camunda.zeebe.test.util.junit.CachedTestResultsExtension$CachedInvocation.fromLine(CachedTestResultsExtension.java:293)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.camunda.zeebe.test.util.junit.CachedTestResultsExtension$InvocationCache.recover(CachedTestResultsExtension.java:252)
	at io.camunda.zeebe.test.util.junit.CachedTestResultsExtension.lambda$beforeAll$1(CachedTestResultsExtension.java:101)
	at io.camunda.zeebe.test.util.junit.CachedTestResultsExtension.beforeAll(CachedTestResultsExtension.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.NullPointerException
		at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:86)
		at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:281)
		at io.camunda.zeebe.test.util.junit.CachedTestResultsExtension.afterAll(CachedTestResultsExtension.java:125)
		... 1 more
   ```
   * Alternatively, we could delete the test configuration file and start anew. However, this would mean re-running 1,000s of test cases and still having a non-resilient test setup.

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

The `CachedTestResultsExtension` ignores configuration lines it cannot properly process and issues a warning in the log.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #25641

### CODE REVIEW

**Comment by tmetzke** [comment]
Successfully tested locally with a non-conforming config file like this one: [zeebe-compatibility.zip](https://github.com/user-attachments/files/18023025/zeebe-compatibility.zip)

The file is corrected and the log contains the following warning:
```
13:09:43.342 [main] [] WARN  io.camunda.zeebe.test.util.junit.CachedTestResultsExtension - Cannot parse the following line into a cached invocation: shouldRepli
```

File: zeebe/test-util/src/main/java/io/camunda/zeebe/test/util/junit/CachedTestResultsExtension.java [hunk 1]
```diff
@@ -249,6 +255,7 @@ static InvocationCache recover(final Path path) {
             reader
                 .lines()
                 .map(CachedInvocation::fromLine)
+                .<CachedInvocation>mapMulti(Optional::ifPresent)
```
Comment (tmetzke) [inline zeebe/test-util/src/main/java/io/camunda/zeebe/test/util/junit/CachedTestResultsExtension.java:258]: ℹ️ Just learned about `mapMulti` today. Some comparison to `flatMap` can be found here: https://nipafx.dev/java-16-stream-mapmulti/

**Review by lenaschoenburg — APPROVED** [review]
Thanks!
