### PR TITLE
Verify groups migration

### LINKED ISSUE #26318: `IdentityDefaultEntitiesIT` needs to be stabilized and enabled again
`IdentityDefaultEntitiesIT` failed too many times in CI and was disabled here: e60543fc97f91d8bb3e27c4e352cba6b395c937e

The logs indicate that Identity cannot connect to Keycloak.

<details><summary>Details</summary>
<p>

```
19:29:16.407 [] [] [testcontainers-lifecycle-0] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /charming_clarke: Waiting for 300 seconds for URL: http://localhost:32889/actuator/health/readiness (where port 32889 maps to container port 8082)
19:34:16.410 [] [] [testcontainers-lifecycle-0] ERROR tc.camunda/identity:SNAPSHOT - Could not start container
java.lang.IllegalStateException: Wait strategy failed. Container exited with code 1
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:533) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330) ~[testcontainers-1.19.8.jar:1.19.8]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:32889/actuator/health/readiness should return HTTP [200])
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:320) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:500) ~[testcontainers-1.19.8.jar:1.19.8]
	... 9 more
Caused by: org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:54) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:252) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:500) ~[testcontainers-1.19.8.jar:1.19.8]
	... 9 more
Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection refused
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$null$6(HttpWaitStrategy.java:312) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$waitUntilReady$7(HttpWaitStrategy.java:257) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:43) ~[duct-tape-1.0.8.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	... 3 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at java.base/sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at java.base/sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.base/java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1319) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1252) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1138) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1067) ~[?:?]
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$null$6(HttpWaitStrategy.java:274) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$waitUntilReady$7(HttpWaitStrategy.java:257) ~[testcontainers-1.19.8.jar:1.19.8]
	at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:43) ~[duct-tape-1.0.8.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	... 3 more
19:34:16.434 [] [] [testcontainers-lifecycle-0] ERROR tc.camunda/identity:SNAPSHOT - Log output from the failed container:
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
```

</p>
</details>

### LINKED ISSUE #33058: Create IT test scenario for group migration
1. Create Identity container
2. Create groups in the old Identity container
3. Create users in the old identity container
4. Assign users to groups
5. Run the migration
6. Assert that groups are migrated
7. Assert that groups memberships are migrated

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

Add IT test to verify groups migration

## Related issues

closes #33058 
closes #26318

### CODE REVIEW

File: migration/identity-migration/src/main/java/io/camunda/migration/identity/MigrationRunner.java [hunk 1]
```diff
@@ -54,12 +54,13 @@ public Void call() {
   private void migrate() {
     while (true) {
       try {
-        tenantMigrationHandler.migrate();
```
Comment (megglos) [inline migration/identity-migration/src/main/java/io/camunda/migration/identity/MigrationRunner.java]: @nicpuppa can you rebase, with https://github.com/camunda/camunda/pull/33375 merged individual handlers are not called here anymore

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityMigrationTestUtil.java [hunk 2]
```diff
@@ -7,131 +7,80 @@
...
-        .withEnv(
-            "JAVA_TOOL_OPTIONS",
-            "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:"
-                + 5005) // Pass debug options
-        .dependsOn(postgres, keycloak)
+        .withImagePullPolicy(PullPolicy.alwaysPull())
+        .dependsOn(keycloak)
         .withEnv("SERVER_PORT", Integer.toString(IDENTITY_PORT))
-        .withEnv("KEYCLOAK_URL", internalKeycloakUrl())
+        .withEnv("KEYCLOAK_URL", "http://keycloak:8080")
```
Comment (megglos) [inline qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityMigrationTestUtil.java]: 🔧  given the constants are there, let's use them here
```suggestion
        .withEnv("KEYCLOAK_URL", "http://%s:%d".formatted(KEYCLOAK_HOST, KEYCLOAK_PORT))
```

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityMigrationTestUtil.java [hunk 3]
```diff
@@ -7,131 +7,80 @@
...
-            "IDENTITY_AUTH_PROVIDER_ISSUER_URL", internalKeycloakUrl() + "/realms/camunda-platform")
-        .withEnv(
-            "IDENTITY_AUTH_PROVIDER_BACKEND_URL",
-            internalKeycloakUrl() + "/realms/camunda-platform")
-        .withEnv("IDENTITY_DATABASE_HOST", POSTGRES_HOST)
-        .withEnv("IDENTITY_DATABASE_PORT", Integer.toString(POSTGRES_PORT))
-        .withEnv("IDENTITY_DATABASE_NAME", IDENTITY_DATABASE_NAME)
-        .withEnv("IDENTITY_DATABASE_USERNAME", IDENTITY_DATABASE_USERNAME)
-        .withEnv("IDENTITY_DATABASE_PASSWORD", IDENTITY_DATABASE_PASSWORD)
+            "IDENTITY_AUTH_PROVIDER_BACKEND_URL", "http://keycloak:8080/realms/camunda-platform")
```
Comment (megglos) [inline qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityMigrationTestUtil.java]: 🔧  same here
```suggestion
            "IDENTITY_AUTH_PROVIDER_BACKEND_URL", "http://%s:%d/realms/camunda-platform".formatted(KEYCLOAK_HOST, KEYCLOAK_PORT))
```

File: migration/identity-migration/src/main/java/io/camunda/migration/identity/MigrationRunner.java (hunk 1 above)
Comment (nicpuppa) [reply migration/identity-migration/src/main/java/io/camunda/migration/identity/MigrationRunner.java]: done

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityMigrationTestUtil.java [hunk 4]
```diff
@@ -7,131 +7,80 @@
...
                 .forStatusCode(200)
-                .withReadTimeout(Duration.ofSeconds(10))
-                .withStartupTimeout(Duration.ofMinutes(5)));
+                .withStartupTimeout(Duration.ofMinutes(2)));
   }
 
-  static GenericContainer<?> getManagementIdentity(
-      final GenericContainer<?> postgres, final GenericContainer<?> keycloak) {
+  static GenericContainer<?> getManagementIdentity(final KeycloakContainer keycloak) {
     return new GenericContainer<>(DockerImageName.parse("camunda/identity:SNAPSHOT"))
```
Comment (megglos) [inline qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityMigrationTestUtil.java:60]: 💭  I wonder whether we want to bind this to a release version for the upcoming 8.8 stable branch, but we can handle that in a follow-up given this is already the status quo anyway

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java [hunk 5]
```diff
@@ -10,53 +10,76 @@
...
+          .withEnv("KEYCLOAK_USERS_1_PASSWORD", "password")
+          .withEnv("KEYCLOAK_USERS_1_GROUPS_0", "groupC")
+          .waitingFor(
+              new HttpWaitStrategy()
+                  .forPort(8082)
+                  .forPath("/actuator/health/readiness")
+                  .allowInsecure()
+                  .forStatusCode(200)
+                  .withReadTimeout(Duration.ofSeconds(10))
+                  .withStartupTimeout(Duration.ofMinutes(5)));
```
Comment (megglos) [inline qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java:81]: 🔧 better we move that to `IdentityMigrationTestUtil` ? or does the testcontainers api not allow that?

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java [hunk 6]
```diff
@@ -68,9 +91,49 @@ void canMigrateOldDefaultEntities() {
             "camunda.migration.identity.management-identity.client-secret", IDENTITY_CLIENT_SECRET)
         .withProperty(
             "camunda.migration.identity.management-identity.audience",
-            CAMUNDA_IDENTITY_RESOURCE_SERVER)
-        .start();
+            CAMUNDA_IDENTITY_RESOURCE_SERVER);
+    camunda.start();
```
Comment (megglos) [inline qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java]: 💭  could we await it's actual termination? 🤔 not relevant here though, I can follow-up in the context of https://github.com/camunda/camunda/issues/33068

**Review by megglos — APPROVED** [review]
LGTM! Mostly some minor suggestions and otherwise thoughts to align on.

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java (hunk 5 above)
Comment (nicpuppa) [reply qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java:81]: I don't want to move all the groups and users setup into the util class, that's why this waiting is placed here

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityMigrationTestUtil.java (hunk 4 above)
Comment (nicpuppa) [reply qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityMigrationTestUtil.java:60]: Yeah, good point. I think we can follow-up on this

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java (hunk 6 above)
Comment (nicpuppa) [reply qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java]: What do you mean ?

**Comment by nicpuppa** [comment]
@megglos we have an issue with the service beans, they are duplicated because Spring initialise them in `IdentityMigrationModuleConfiguration` and in `CamundaServicesConfiguration`. Should we add `  @ConditionalOnMissingBean` or simply remove the beans from the identity configuration class ?

File: migration/identity-migration/src/main/java/io/camunda/migration/identity/GroupMigrationHandler.java [hunk 7]
```diff
@@ -41,7 +41,7 @@ protected void process(final List<Group> batch) {
           try {
             final var normalizedGroupId = normalizeGroupID(group);
             final var groupDTO = new GroupDTO(normalizedGroupId, group.name(), "");
-            groupServices.createGroup(groupDTO);
+            groupServices.createGroup(groupDTO).join();
```
Comment (nicpuppa) [inline migration/identity-migration/src/main/java/io/camunda/migration/identity/GroupMigrationHandler.java:44]: Why do you want to wait here ?

Comment (megglos) [reply migration/identity-migration/src/main/java/io/camunda/migration/identity/GroupMigrationHandler.java:44]: Otherwise errors where swallowed.

File: zeebe/qa/util/src/main/java/io/camunda/zeebe/qa/util/cluster/TestStandaloneIdentityMigration.java [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+    extends TestSpringApplication<TestStandaloneIdentityMigration> {
+  private static final Logger LOGGER =
+      LoggerFactory.getLogger(TestStandaloneIdentityMigration.class);
+
+  private static final Logger log = LoggerFactory.getLogger(TestStandaloneIdentityMigration.class);
+  private final GatewayBasedProperties config;
+
+  public TestStandaloneIdentityMigration(final IdentityMigrationProperties migrationProperties) {
+    super(MigrationsRunner.class);
+    config = new GatewayBasedProperties();
```
Comment (megglos) [inline zeebe/qa/util/src/main/java/io/camunda/zeebe/qa/util/cluster/TestStandaloneIdentityMigration.java:31]: Follow-up: create a task to move away from abusing the gateway config here, instead we introduce a dedicated properties class covering all of the required config for joining the cluster and making use of the broker client

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java (hunk 6 above)
Comment (megglos) [reply qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java]: Effectively whether we can make the start call blocking in the sense that it only returns once the migration app completed, right now it appear to run async, right?

File: zeebe/qa/util/src/main/java/io/camunda/zeebe/qa/util/cluster/TestStandaloneIdentityMigration.java (hunk 8 above)
Comment (megglos) [reply zeebe/qa/util/src/main/java/io/camunda/zeebe/qa/util/cluster/TestStandaloneIdentityMigration.java:31]: https://github.com/camunda/camunda/issues/33553

File: qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java (hunk 6 above)
Comment (nicpuppa) [reply qa/acceptance-tests/src/test/java/io/camunda/it/migration/IdentityDefaultEntitiesIT.java]: yep
