### PR TITLE
fix(gateway): convert to string when logging correlationkey

### LINKED ISSUE #6655: Raw pointer value in rejection reason when correlating a message
**Description**

It seems when correlating a message with no brokers available in the gateway we return a raw UnsafeBuffer.toString(), e.g.

```
❯ clients/go/cmd/zbctl/dist/zbctl --insecure publish message name --correlationKey key                   
Error: rpc error: code = Unavailable desc = Expected to pick partition for message with correlation key 'UnsafeBuffer{addressOffset=16, capacity=3, byteArray=[B@3b37806f, byteBuffer=null}', but no topology is available
```

It's beautiful :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Convert to string when logging correlation key

## Related issues

closes #6655 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: gateway/src/main/java/io/zeebe/gateway/impl/broker/BrokerRequestManager.java [hunk 1]
```diff
@@ -240,7 +241,7 @@ private void determinePartitionIdForPublishMessageRequest(
       throw new NoTopologyAvailableException(
           String.format(
               "Expected to pick partition for message with correlation key '%s', but no topology is available",
-              request.getCorrelationKey()));
+              BufferUtil.bufferAsString(request.getCorrelationKey())));
```
Comment (deepthidevaki) [inline gateway/src/main/java/io/zeebe/gateway/impl/broker/BrokerRequestManager.java:244]: This is the fix. The other changes are auto-formatting by the IDE.

**Review by saig0 — APPROVED** [review]
bors r+

:tada:
