### PR TITLE
fix: exclusive gateway's default flow not allowed to have a condition

### LINKED ISSUE #10966: Exclusive gateway not allowed to have a condition
**Describe the bug**

According to the spec (10.5.2 - page 293):

> The default Sequence Flow should not have a conditionExpression.
> Any such Expression SHALL be ignored.

A default flow whose source is an exclusive gateway is not allowed to have a condition.

**To Reproduce**

- deploy a process with exclusive gateway with a default outgoing sequence flow with condition

- notice the rejection

**Expected behavior**

- Changed in accordance with the BPMN 2.0 specification

- Inclusive gateway's default flow should be allowed to have a condition, but not be required

- Zeebe should not evaluate this condition.

Related #10310

### PR DESCRIPTION
**Pull request by skayliu**
## Description

Fix exclusive gateway's default flow not allowed to have a condition.

This PR makes it so that:
- the default flow is allowed to have a condition
- the condition of the default flow is not evaluated

## Related issues

closes #10966 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [x] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by skayliu** [comment]
Hi, @korthout, Please take a moment to review this fix when you have time. Thanks.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/ExclusiveGatewayTest.java [hunk 1]
```diff
@@ -365,4 +365,55 @@ public void shouldResolveIncidentsWhenTerminating() {
...
+            .moveToLastGateway()
+            .sequenceFlowId("s2")
+            .conditionExpression("foo >= 5 and foo < 10")
+            .endEvent("b")
+            .moveToLastExclusiveGateway()
+            .defaultFlow()
+            .sequenceFlowId("s3")
+            .conditionExpression("foo >= 10")
+            .endEvent("c")
+            .done();
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/ExclusiveGatewayTest.java:389]: ❌ This test does not verify that the condition on the default flow is not evaluated

I suggest replacing your test case with two individual test cases:

1. Test that an end event is reached, even though there is a mistake in the default condition (`missing_var` is a reference to a variable that is not available in the process instance). This allows checking that the condition is not evaluated because if it were evaluated, an incident is raised, stopping the flow from reaching the end event.
Screen Shot 2022-11-10 at 16 48 17

2. The same test as above, but with a non-default sequence flow present as well, that evaluates to `false` so that the default flow must be taken. We should still check that the condition on the default flow is not evaluated, and we can do that in the same way as in the first test.
Screen Shot 2022-11-10 at 16 51 25

When you add these tests, you'll notice that we need to make a change to the ExclusiveGatewayProcessor as well to avoid evaluating the condition on the default flow.

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @skayliu 🚀 

We still have to make some adjustments to the existing code to avoid evaluating the Condition on the Default flow. Please have a look at my change request.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/ExclusiveGatewayTest.java [hunk 2]
```diff
@@ -365,4 +367,141 @@ public void shouldResolveIncidentsWhenTerminating() {
...
+            .conditionExpression("= contains(str,\"a\")")
+            .endEvent("end1")
+            .moveToLastGateway()
+            .sequenceFlowId("s2")
+            .conditionExpression("= contains(str,\"b\")")
+            .endEvent("end2")
+            .moveToLastExclusiveGateway()
+            .defaultFlow()
+            .sequenceFlowId("s3")
+            .conditionExpression("= true")
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/ExclusiveGatewayTest.java:440]: ❌  The assertion below `Expect that the default flow's condition is not evaluated` verifies that no incident is created. That is only relevant if the expression would create an incident when evaluated. Currently, it just evaluates to `true` and never creates an incident.

We should change the condition expression to `= nonexisting_variable` to make sure an incident would be created when this condition would be evaluated.

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @skayliu 🚀 

This looks really good already. We should, however make a small adjustment to one of the tests, so we can be sure it verifies what we intended.

After that this is ready to merge.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/ExclusiveGatewayTest.java (hunk 2 above)
Comment (lzgabel) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/ExclusiveGatewayTest.java:440]: > We should change the condition expression to = nonexisting_variable to make sure an incident would be created when this condition would be evaluated.

❓  Hi @korthout. I thought you may have missed something? 

According to the description in the specification
> The default Sequence Flow should not have a conditionExpression. Any such Expression SHALL be ignored.

When `default sequence Flow` has conditionExpression we should ignore it, so I thought we would not evaluate the expression and we never create the event. Please correct me if I understand wrong. ❤️

Comment (korthout) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/ExclusiveGatewayTest.java:440]: >When default sequence Flow has conditionExpression we should ignore it, so I thought we would not evaluate the expression and we never create the event. Please correct me if I understand wrong

That's correct, but we should verify that we don't evaluate it in a test. We do that by using an expression that we expect would create an incident in case it is evaluated. We can then verify that no incident is created. This tells us that the expression was not evaluated. Does that make sense?

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @skayliu this looks great! 👍 

❌ Please squash/rebase the commits and provide meaningful commit messages. As I've explained [in the other PR](https://github.com/camunda/zeebe/pull/10882#issuecomment-1311929100), this can be helpful for the reviewer, but is especially useful to others when trying to understand this code sometime in the future.

**Comment by lzgabel** [comment]
Done. 

Hi @korthout. Please check this out. 🙇

**Review by korthout — APPROVED** [review]
Thanks @skayliu @lzgabel 🏅 

LGTM 💯 

bors merge

~I'll create an issue to document the behavior.~ I'll also reach out to the Modeler team, to adjust the linting.

EDIT: I don't think this has to be documented. From the user's perspective, the default flow is taken only when the conditions of all other flows are not met. The condition on the default flow has no impact from the user's perspective (with one exception: it could raise an incident when Zeebe is unable to evaluate the expression successfully).

**Comment by korthout** [comment]
For completeness, we won't backport this PR, as we see no need for it.
