### PR TITLE
Fix inconsistent position creation

### LINKED ISSUE #3651: Inconsistent log positions
**Describe the bug**

During investigation of failed benchmarks I investigated the segmented raft journal and wrote an tool to verify the increasing of the positions and find the lowest and highest position etc. Code can be found here https://github.com/Zelldon/playground/tree/master/zb-log-check.

After copy from one broker the log (+ metadata) and running the tool, I got the following output.

```
Scan log...
===============
At idx 10108
Current position 180358561660928 (Segment id 41993 segment offset 0)
Is smaller then this last position 218180045888864 (Segment id 50799 segment offset 2219360)
Current lowest 218162869953992 current highest 218180045888864
===============
Scan finished
LOG IS INCONSISTENT!
Last position: 180358562692808
Lowest position: 180358561660928
Highest position: 218180045888864
```

As we can see from the output that the position somehow drops from `218180045888864` to `180358561660928`. 

This means on `LogStreamImpl#determineInitialPartitionId` finds the wrong position on restart/leader change. The term of the higher position is 11 and the term of the lower position is 12, which indicates/proofs that this happens on leader change.

Interesting is also that `lastReadAddress()` for position `218180045888864` returns `92682469` and for `180358561660928` `92682471`. It seems that one index is missing?

###  This bug causes

Further investigation showed that seeking to this position is not possible, which can also be a problem on deletion.
For example `reader.seek(218180045888864L);` return false. The problem is that binary search only works if the positions are increasing, since they are not it is not possible to find the right position. `AtomixLogStorageReader#llookUpApproximateAddress(final long position)` will not work as expected. It jumps in the middle and sees that the position is still lower. On next jump it goes over the border where the position dropped, which means it is still lower, it will repeat this until it reaches the end of the log.

### Related to 

It might be related to #3573 but this is not 100% clear, since this benchmark had only one maximum snapshot count.

### Configuration

Configuration for that benchmark was:

```
3 Partitions,
3 Nodes,
3 repl. factor
Default benchmark settings
+ logSegmentSize 128 MB 
+ max snapshot count 1
```

### LINKED ISSUE #3652: After Leader change old LogStorageAppender still tries to append
**Description**

After refactoring the Logstream, the appender is always open and only closed with the LogStream, since this is internal knowledge. On leader change it can happen that the old leader tries to append with his appender and error logs are printed, which might be confusing for users. 

It is not really an issue since nothing bad can happen, but we should probably then not log that as errors.

```
I 2020-01-09T23:58:31.850728925Z 2020-01-09 23:58:31.850 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Removing leader partition services for partition PartitionId{id=1, group=raft-partition}
 
I 2020-01-09T23:58:31.850777993Z 2020-01-09 23:58:31.850 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Closing exporter-1
 
I 2020-01-09T23:58:31.850785084Z 2020-01-09 23:58:31.850 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Partition role transitioning from LEADER to FOLLOWER
 
I 2020-01-09T23:58:31.853109515Z 2020-01-09 23:58:31.852 [exporter-1] [Broker-0-zb-fs-workers-2] INFO  io.zeebe.broker.exporter.elasticsearch - Exporter closed
 
I 2020-01-09T23:58:31.853860651Z 2020-01-09 23:58:31.853 [exporter-1] [Broker-0-zb-fs-workers-2] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter-1'.
 
I 2020-01-09T23:58:31.854379842Z 2020-01-09 23:58:31.854 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Closed exporter-1 successfully
 
I 2020-01-09T23:58:31.854413444Z 2020-01-09 23:58:31.854 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Closing partition-1-processor-snapshot-director
 
I 2020-01-09T23:58:31.856729270Z 2020-01-09 23:58:31.856 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-3] DEBUG io.zeebe.broker.system - Closed partition-1-processor-snapshot-director successfully
 
I 2020-01-09T23:58:31.856749984Z 2020-01-09 23:58:31.856 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-3] DEBUG io.zeebe.broker.system - Closing partition-1-processor
 
I 2020-01-09T23:58:31.857762294Z 2020-01-09 23:58:31.857 [partition-1-processor] [Broker-0-zb-actors-2] DEBUG io.zeebe.logstreams - Closed stream processor controller partition-1-processor.
 
I 2020-01-09T23:58:31.857803928Z 2020-01-09 23:58:31.857 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed partition-1-processor successfully
 
I 2020-01-09T23:58:31.857811188Z 2020-01-09 23:58:31.857 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing io.zeebe.broker.logstreams.LogStreamDeletionService
 
I 2020-01-09T23:58:31.857956670Z 2020-01-09 23:58:31.857 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.logstreams.LogStreamDeletionService successfully
 
I 2020-01-09T23:58:31.905722120Z 2020-01-09 23:58:31.905 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/usr/local/zeebe/data/raft-partition/partitions/1/runtime'.
 
I 2020-01-09T23:58:31.905755708Z 2020-01-09 23:58:31.905 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Installing follower partition service for partition PartitionId{id=1, group=raft-partition}
 
I 2020-01-09T23:58:32.142660035Z 2020-01-09 23:58:32.142 [] [raft-server-0-raft-partition-partition-2] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-2} - Transitioning to FOLLOWER
 
I 2020-01-09T23:58:32.143442330Z 2020-01-09 23:58:32.143 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Removing leader partition services for partition PartitionId{id=2, group=raft-partition}
 
I 2020-01-09T23:58:32.143464025Z 2020-01-09 23:58:32.143 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Closing exporter-2
 
I 2020-01-09T23:58:32.143470172Z 2020-01-09 23:58:32.143 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Partition role transitioning from LEADER to FOLLOWER
 
I 2020-01-09T23:58:32.144693596Z 2020-01-09 23:58:32.143 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210299600.
 
I 2020-01-09T23:58:32.144716960Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.145456077Z 2020-01-09 23:58:32.145 [exporter-2] [Broker-0-zb-fs-workers-0] INFO  io.zeebe.broker.exporter.elasticsearch - Exporter closed
 
I 2020-01-09T23:58:32.151376012Z 2020-01-09 23:58:32.150 [exporter-2] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter-2'.
 
I 2020-01-09T23:58:32.151402959Z 2020-01-09 23:58:32.151 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closed exporter-2 successfully
 
I 2020-01-09T23:58:32.151407223Z 2020-01-09 23:58:32.151 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing partition-2-processor-snapshot-director
 
I 2020-01-09T23:58:32.151814451Z 2020-01-09 23:58:32.151 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Closed partition-2-processor-snapshot-director successfully
 
I 2020-01-09T23:58:32.151843771Z 2020-01-09 23:58:32.151 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Closing partition-2-processor
 
I 2020-01-09T23:58:32.151880120Z 2020-01-09 23:58:32.151 [partition-2-processor] [Broker-0-zb-actors-3] DEBUG io.zeebe.logstreams - Closed stream processor controller partition-2-processor.
 
I 2020-01-09T23:58:32.151890066Z 2020-01-09 23:58:32.151 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Closed partition-2-processor successfully
 
I 2020-01-09T23:58:32.151916642Z 2020-01-09 23:58:32.151 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-2] DEBUG io.zeebe.broker.system - Closing io.zeebe.broker.logstreams.LogStreamDeletionService
 
I 2020-01-09T23:58:32.152127985Z 2020-01-09 23:58:32.151 [Broker-0-ZeebePartition-2] [Broker-0-zb-actors-3] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.logstreams.LogStreamDeletionService successfully
 
I 2020-01-09T23:58:32.174499485Z 2020-01-09 23:58:32.174 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: [SnapshotImpl{position=36760627433296, path=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/15656138-2-1578590092028-36760627433296}]
 
I 2020-01-09T23:58:32.174786348Z 2020-01-09 23:58:32.174 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210299816.
 
I 2020-01-09T23:58:32.174808696Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.174917412Z 2020-01-09 23:58:32.174 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210300120.
 
I 2020-01-09T23:58:32.174924447Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.175201974Z 2020-01-09 23:58:32.174 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210300424.
 
I 2020-01-09T23:58:32.175234412Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.175352268Z 2020-01-09 23:58:32.175 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210300728.
 
I 2020-01-09T23:58:32.175366316Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.175616021Z 2020-01-09 23:58:32.175 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210301032.
 
I 2020-01-09T23:58:32.175627476Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.175804847Z 2020-01-09 23:58:32.175 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210301336.
 
I 2020-01-09T23:58:32.175913096Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176167141Z 2020-01-09 23:58:32.175 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210301640.
 
I 2020-01-09T23:58:32.176189959Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176289862Z 2020-01-09 23:58:32.175 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210301944.
 
I 2020-01-09T23:58:32.176295141Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176353433Z 2020-01-09 23:58:32.175 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210302288.
 
I 2020-01-09T23:58:32.176358616Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176408927Z 2020-01-09 23:58:32.175 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210302632.
 
I 2020-01-09T23:58:32.176414073Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176470794Z 2020-01-09 23:58:32.176 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210302936.
 
I 2020-01-09T23:58:32.176475956Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176526554Z 2020-01-09 23:58:32.176 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210303280.
 
I 2020-01-09T23:58:32.176531712Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176589547Z 2020-01-09 23:58:32.176 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210303584.
 
I 2020-01-09T23:58:32.176594973Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176647256Z 2020-01-09 23:58:32.176 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210303928.
 
I 2020-01-09T23:58:32.176652586Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176719317Z 2020-01-09 23:58:32.176 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210304272.
 
I 2020-01-09T23:58:32.176724697Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.176946149Z 2020-01-09 23:58:32.176 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210304616.
 
I 2020-01-09T23:58:32.176956442Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.177048396Z 2020-01-09 23:58:32.176 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210304960.
 
I 2020-01-09T23:58:32.177054230Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.177181840Z 2020-01-09 23:58:32.176 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210305304.
 
I 2020-01-09T23:58:32.177254800Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.177345798Z 2020-01-09 23:58:32.177 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210305600.
 
I 2020-01-09T23:58:32.177352506Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.177422007Z 2020-01-09 23:58:32.177 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210305896.
 
I 2020-01-09T23:58:32.177428895Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.177501570Z 2020-01-09 23:58:32.177 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210306192.
 
I 2020-01-09T23:58:32.177517387Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.177590689Z 2020-01-09 23:58:32.177 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210306496.
 
I 2020-01-09T23:58:32.177597788Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.177667732Z 2020-01-09 23:58:32.177 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210306792.
 
I 2020-01-09T23:58:32.177675051Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.177788616Z 2020-01-09 23:58:32.177 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210307088.
 
I 2020-01-09T23:58:32.177809774Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.177938979Z 2020-01-09 23:58:32.177 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210307384.
 
I 2020-01-09T23:58:32.177947Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.178011935Z 2020-01-09 23:58:32.177 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210307680.
 
I 2020-01-09T23:58:32.178017850Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.178234852Z 2020-01-09 23:58:32.177 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210307976.
 
I 2020-01-09T23:58:32.178259518Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.178343478Z 2020-01-09 23:58:32.178 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210308272.
 
I 2020-01-09T23:58:32.178350200Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.178438774Z 2020-01-09 23:58:32.178 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210308568.
 
I 2020-01-09T23:58:32.178446299Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.178519864Z 2020-01-09 23:58:32.178 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210308864.
 
I 2020-01-09T23:58:32.178526087Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.178613774Z 2020-01-09 23:58:32.178 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210309208.
 
I 2020-01-09T23:58:32.178621271Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.178721684Z 2020-01-09 23:58:32.178 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210309512.
 
I 2020-01-09T23:58:32.178739242Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.178875622Z 2020-01-09 23:58:32.178 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210309816.
 
I 2020-01-09T23:58:32.178902711Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.179091660Z 2020-01-09 23:58:32.178 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210310120.
 
I 2020-01-09T23:58:32.179113570Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.179270741Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210310464.
 
I 2020-01-09T23:58:32.179283564Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.179383650Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210310808.
 
I 2020-01-09T23:58:32.179406008Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.179514483Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210311152.
 
I 2020-01-09T23:58:32.179523266Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.179634228Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210311456.
 
I 2020-01-09T23:58:32.179643167Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.179734787Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210311776.
 
I 2020-01-09T23:58:32.179741575Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180000784Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210312080.
 
I 2020-01-09T23:58:32.180018682Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180105290Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210312384.
 
I 2020-01-09T23:58:32.180113607Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180188275Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210312688.
 
I 2020-01-09T23:58:32.180195095Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180442958Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210312992.
 
I 2020-01-09T23:58:32.180451891Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180515821Z 2020-01-09 23:58:32.179 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210313296.
 
I 2020-01-09T23:58:32.180521335Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180580131Z 2020-01-09 23:58:32.180 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210313600.
 
I 2020-01-09T23:58:32.180585512Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180637890Z 2020-01-09 23:58:32.180 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210313904.
 
I 2020-01-09T23:58:32.180643362Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180699530Z 2020-01-09 23:58:32.180 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210314208.
 
I 2020-01-09T23:58:32.180704975Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180755734Z 2020-01-09 23:58:32.180 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210314512.
 
I 2020-01-09T23:58:32.180761457Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180817454Z 2020-01-09 23:58:32.180 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210314816.
 
I 2020-01-09T23:58:32.180822850Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.180911527Z 2020-01-09 23:58:32.180 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210315120.
 
I 2020-01-09T23:58:32.180952655Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.181049992Z 2020-01-09 23:58:32.180 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210330192.
 
I 2020-01-09T23:58:32.181057718Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.181126162Z 2020-01-09 23:58:32.180 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210359032.
 
I 2020-01-09T23:58:32.181132907Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.181198490Z 2020-01-09 23:58:32.181 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210500760.
 
I 2020-01-09T23:58:32.181205006Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.181326131Z 2020-01-09 23:58:32.181 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210628008.
 
I 2020-01-09T23:58:32.181332541Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.181470477Z 2020-01-09 23:58:32.181 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210642016.
 
I 2020-01-09T23:58:32.181479107Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.181622134Z 2020-01-09 23:58:32.181 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210642232.
 
I 2020-01-09T23:58:32.181627849Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.181702021Z 2020-01-09 23:58:32.181 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210656240.
 
I 2020-01-09T23:58:32.181709013Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.181797861Z 2020-01-09 23:58:32.181 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210684664.
 
I 2020-01-09T23:58:32.181804562Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.181941868Z 2020-01-09 23:58:32.181 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210698768.
 
I 2020-01-09T23:58:32.181969963Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.182118314Z 2020-01-09 23:58:32.181 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210712872.
 
I 2020-01-09T23:58:32.182136141Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.182189829Z 2020-01-09 23:58:32.182 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210726976.
 
I 2020-01-09T23:58:32.182195086Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.182313023Z 2020-01-09 23:58:32.182 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210755184.
 
I 2020-01-09T23:58:32.182329791Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.182463234Z 2020-01-09 23:58:32.182 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210769288.
 
I 2020-01-09T23:58:32.182470841Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.182541817Z 2020-01-09 23:58:32.182 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210798160.
 
I 2020-01-09T23:58:32.182547078Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.182697670Z 2020-01-09 23:58:32.182 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210827000.
 
I 2020-01-09T23:58:32.182711145Z java.lang.IllegalStateException: LeaderRole is closed and cannot be used as appender
	at io.atomix.protocols.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:1454) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.protocols.raft.roles.LeaderRole.lambda$appendEntry$32(LeaderRole.java:1439) ~[atomix-raft-3.2.0-20200106.173101-104.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20200106.173014-104.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
 
I 2020-01-09T23:58:32.182771233Z 2020-01-09 23:58:32.182 [] [raft-server-0-raft-partition-partition-2] ERROR io.zeebe.logstreams - Failed to append block with last event position 24829210841072.
 

```

### LINKED ISSUE #3667: Possible deadlock in Logstreams tests
**Describe the bug**

It happens from time to time that our build time out, but is not really clear from the output where it stopped.

```
[INFO] -------------------------------------------------------

[INFO]  T E S T S

[INFO] -------------------------------------------------------

[INFO] Running io.zeebe.msgpack.el.JsonConditionTest

[INFO] Running io.zeebe.msgpack.el.JsonConditionParserFailureMessageTest

[INFO] Running io.zeebe.msgpack.el.JsonConditionVariableNamesTest

[INFO] Running io.zeebe.msgpack.el.JsonConditionParserTest

[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.776 s - in io.zeebe.msgpack.el.JsonConditionParserFailureMessageTest

[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.899 s - in io.zeebe.msgpack.el.JsonConditionVariableNamesTest

[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.965 s - in io.zeebe.msgpack.el.JsonConditionParserTest

[INFO] Running io.zeebe.msgpack.el.JsonConditionInterpreterTest

[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.497 s - in io.zeebe.msgpack.el.JsonConditionTest

[INFO] Tests run: 55, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.186 s - in io.zeebe.msgpack.el.JsonConditionInterpreterTest

[INFO] 

[INFO] Results:

[INFO] 

[INFO] Tests run: 115, Failures: 0, Errors: 0, Skipped: 0

[INFO] 

[INFO] 

[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ zeebe-msgpack-json-el ---

[INFO] Building jar: /home/jenkins/agent/workspace/zeebe-io_zeebe_PR-3660/json-el/target/zeebe-msgpack-json-el-0.23.0-SNAPSHOT.jar

[INFO] 

[INFO] --- maven-jar-plugin:3.2.0:jar (empty-javadoc-jar) @ zeebe-msgpack-json-el ---

[WARNING] JAR will be empty - no content was marked for inclusion!

[INFO] 

[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (analyze-dependencies) @ zeebe-msgpack-json-el ---

[INFO] No dependency problems found

[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 46.511 s - in io.zeebe.gateway.broker.BrokerClientTest

[INFO] 

[INFO] Results:

[INFO] 

[INFO] Tests run: 61, Failures: 0, Errors: 0, Skipped: 0

[INFO] 

[INFO] 

[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ zeebe-gateway ---

[INFO] 

[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (analyze-dependencies) @ zeebe-gateway ---

[INFO] No dependency problems found

Sending interrupt signal to process

Killing processes

kill finished with exit code 0

Sending interrupt signal to process

Killing processes

kill finished with exit code 2

Terminated

script returned exit code 143
```

After taking a deeper look at the maven output.  [log.txt](https://github.com/zeebe-io/zeebe/files/4064333/log.txt)
We can see that the logstream never finished his test step. So my current assumption is that there is a deadlock during one of these tests.

This issue seem to happen more often on #3651 . Might be that this also introduced something.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

As I wrote here https://github.com/zeebe-io/zeebe/issues/3651#issuecomment-574259240

> On partition bootstrap the LogStream is created and on becoming a leader only the related actors, like processor, exporter etc. are created. This makes sense since the log stream has the same life time as the partition.

> On LogStream starting the Appender and WriteBuffer are created/opened.
https://github.com/zeebe-io/zeebe/blob/develop/logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java#L194

> To open the Writebuffer we need to determine the partition ID and scan the log. All nodes will start there write buffer and on leader change the log is not scanned again. This means the next leader will probably start to append on a lower position. We have currently a test which verifies that our log is consistent between restarts, but this test only checks this for a single node. This issue will only happen in a cluster.

To solve this issue we introduced reference counting for log stream writers 
 * on first writer creation the log appender and write buffer is created and the initial position is determined
 * on last writer closing the appender and write buffer is closed again

This also solves the issue, where we saw that the appender still runs after an leader change (https://github.com/zeebe-io/zeebe/issues/3652).

**Note:** I will setup a benchmark and add the results here.

## Related issues

closes #3651 
closes https://github.com/zeebe-io/zeebe/issues/3652
closes https://github.com/zeebe-io/zeebe/issues/3667

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java [hunk 1]
```diff
@@ -144,6 +149,38 @@ private void internalSetCommitPosition(final long commitPosition) {
     onCommitPositionUpdatedConditions.signalConsumers();
   }
 
+  @Override
+  public void delete(final long position) {
+    actor.call(
```
Comment (npepinpe) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: Out of curiosity, why `call` and not `run` if we don't return anything? Doesn't it just wrap the runnable in a `Callable<Void>`?

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java [hunk 2]
```diff
@@ -156,12 +193,55 @@ private void internalSetCommitPosition(final long commitPosition) {
 
   @Override
   public ActorFuture<LogStreamRecordWriter> newLogStreamRecordWriter() {
-    return actor.call(() -> new LogStreamWriterImpl(partitionId, writeBuffer));
+    final var writerFuture = new CompletableActorFuture<LogStreamRecordWriter>();
+    actor.call(() -> createWriter(writerFuture, LogStreamWriterImpl::new));
```
Comment (npepinpe) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: If using `call`, couldn't `createWriter` not just return the `LogStreamWriter`? Then you don't need to create an extra future. Or just switch to run; these `call` calls (:sweat_smile:) are strange to me when they return nothing.

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java [hunk 3]
```diff
@@ -156,12 +193,55 @@ private void internalSetCommitPosition(final long commitPosition) {
...
   public ActorFuture<LogStreamBatchWriter> newLogStreamBatchWriter() {
-    return actor.call(() -> new LogStreamBatchWriterImpl(partitionId, writeBuffer));
+    final var writerFuture = new CompletableActorFuture<LogStreamBatchWriter>();
+    actor.call(() -> createWriter(writerFuture, LogStreamBatchWriterImpl::new));
+    return writerFuture;
+  }
+
+  private <T extends LogStreamWriter> void createWriter(
+      final CompletableActorFuture<T> writerFuture, final WriterCreator<T> creator) {
+    final var alreadyOpenWriters = openWriterCount.getAndIncrement();
```
Comment (npepinpe) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: We're in an actor context, no? Why do we need an atomic integer?

**Review by npepinpe — APPROVED** [review]
Nice catch!

I had a few comments but nothing I consider a blocker anyway. I think we can eventually find a better approach than reference counting the writers, as I don't feel that confident that we won't run into the classic "oops I forgot to release/acquire a reference" in the future (:sweat_smile:), but let's go with that now to get Zeebe working :muscle:

**Comment by Zelldon** [comment]
> I had a few comments but nothing I consider a blocker anyway. I think we can eventually find a better approach than reference counting the writers, as I don't feel that confident that we won't run into the classic "oops I forgot to release/acquire a reference" in the future (sweat_smile), but let's go with that now to get Zeebe working

Agree. I normally tend also to avoid this, but I had no better idea without polluting the LogStream API again.

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java (hunk 3 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: Yes. At the beginning I was not 100% sure how I want to solve it. Either access the count directly, but I decided to sync with the actor. I can replace the count if you want.

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java (hunk 2 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: I need to handle this future in the createWriter method. I can change this to `#run` yes.

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java (hunk 1 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: I moved the method yes. In the past we had the pattern if there comes an request from outside we use call for the context switch. The run method was later improve to handle this as well.

**Comment by Zelldon** [comment]
I changed the calls to `#run`. Since I know the scheduler from the beginning it is for me sometimes a habit to use `call` and normally to avoid `run` because at the beginning it behaved weird.

I created an new issue #3666 to refactor and remove some of these methods.
