### PR TITLE
Skip docker verify on 8.0 patch releases

### LINKED ISSUE #10895: Allow 8.0 patch releases to skip docker verify step
**Description**
The release pipeline has as the last step to build, verify and upload a docker image. The verify step is simply a shell script that is executed, but this file is missing from the 8.0 branch.

>15:32:53 + ./docker/test/verify.sh camunda/zeebe:8.0.8
>15:32:53 /home/jenkins/agent/workspace/zeebe-docker@tmp/durable->02e9a64f/script.sh: line 1: ./docker/test/verify.sh: not found

This blocked the release of 8.0.8, but I was able to circumvent the problem by  starting the 'Docker Image' pipeline manually with parameters (where I was able to skip the verify step).

Note that Jenkins doesn't use the pipeline code from the stable/8.0 branch when starting the docker image step, but it uses the code from `main`. This is why the verification is not skipped, even though [this line](https://github.com/camunda/zeebe/blob/stable/8.0/.ci/pipelines/release_zeebe.groovy#L156) exists.

Failed pipelines:
- https://ci.zeebe.camunda.cloud/job/zeebe-release/297/
- https://ci.zeebe.camunda.cloud/job/zeebe-docker/2895/

### PR DESCRIPTION
**Pull request by korthout**
## Description

The 8.0.8 patch release failed because the Docker image step (the last step in the pipeline) tried to execute a verify.sh script that did not exist in that code base. The script was not supposed to be executed, due to a specific pipeline build param. However, that param has the value as specified on `main` during execution of the pipeline. Even when releasing older versions like patches for 8.0.

This PR adds a (mostly) empty verify.sh script to the `stable/8.0` branch, making sure the release is not failed by it.

Note that the real verify.sh script already exists in `stable/8.1`, so this PR does not require forward porting.

## Related issues

closes #10895

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: docker/test/verify.sh [hunk 1]
```diff
@@ -0,0 +1,10 @@
+#!/bin/bash -eu
+# This script can be used to verify certain properties of a docker image.
+# Returns:
+#   0 on success
+#   1 if one of the properties is invalid
+
+set -o pipefail
+
+echo "The docker image properties only need to verified on versions > 8.0"
+echo "Skipping docker image verification"
```
Comment (npepinpe) [inline docker/test/verify.sh:10]: :+1: Love that we write the reasoning here

**Review by npepinpe — APPROVED** [review]
bors merge
