### PR TITLE
3836, 3837, 3838 - several minor refactorings

### LINKED ISSUE #3836: Move and rename unit tests for configuration
**Description**

The unit tests for the configuration classes are not in the same package, and one has the wrong name:
* move `GatewayCfgTest` into `io.zeebe.gateway.impl.configuration`
* move `ConfigurationTest` into `io.zeebe.broker.syste.configutation`
* rename `ConfigurationTest` into `BrokerCfgTest`

### LINKED ISSUE #3837: Remove references to config setting 'maxMessageCount' from templates and code
**Describe the bug**
The configuration template for `zeebe.cfg.toml` and `gateway.cfg.toml` references a configuration setting `maxMessageCount`. Such a setting does not/no longer exist.

There are also constants in the code, but they are only used in tests.

**To Reproduce**
Look at config templates. You will see the setting being referenced. Setting it has no effect.

**Expected behavior**
* The templates/documentation should only reference valid configuration settings.
* The code should no longer reference obsolete configuration settings

### LINKED ISSUE #3838: Remove references to 'contactPoint' from 'zeebe.cfg.toml'
**Describe the bug**
The configuration template `zeebe.cfg.toml` references the setting `contactPoint`and as part of the gateway cluster configuration. However, this settings will be overwritten by settings which are made in the network section of the configuration. Thus, the setting in the gateway cluster section has no effect.

**To Reproduce**
* Change configuration
* Observe that it has no effect

**Expected behavior**
The documentation and templates should only reference configuration settings, which do have an effect

### PR DESCRIPTION
**Pull request by pihme**
## Description
* moved unit tests for configuration classes into the same package as the classes under test
* renamed one unit test
* removed apparently outdated setting `maxMessageCount` from templates and code
* removed reference to ineffective setting `contactPoint`from configuration template for broker

## Related issues

closes #3836 
closes #3837
closes #3838

## Pull Request Checklist

- [ X ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ X ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ X ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java [hunk 1]
```diff
@@ -58,7 +51,7 @@
 import org.junit.Test;
 import org.junit.rules.TemporaryFolder;
 
-public final class ConfigurationTest {
+public final class BrokerCfgTest {
```
Comment (npepinpe) [inline broker/src/test/java/io/zeebe/broker/system/configuration/BrokerCfgTest.java]: Nit: as this is testing configuration parsing and not just the `BrokerCfg` class, I'd leave it as `ConfigurationTest`.

**Review by npepinpe — APPROVED** [review]
:+1: Looks good
