### PR TITLE
Fix event-based gateway bug

### LINKED ISSUE #1838: If a event base gateway has multiple due timers only one should be triggered

### PR DESCRIPTION
**Pull request by miguelpires**
This PR does two things:
 * Fixes a bug where nearly simultaneous events could trigger more than one outgoing branch in an event-based gateway.
* Refactors ElementInstanceState and WorkflowEngineState so that operations related to deferred records mention "record" or "storedRecord" instead of "deferred token". This avoids confusing the "deferred record" concept with the concept of a token that is spawned and consumed.

closes #1838

### CODE REVIEW

File: broker-core/src/test/java/io/zeebe/broker/workflow/gateway/EventbasedGatewayTest.java [hunk 1]
```diff
@@ -215,6 +229,33 @@ public void shouldContinueWhenTimerIsTriggered() {
...
+
+    assertThat(
+            RecordingExporter.workflowInstanceRecords(WorkflowInstanceIntent.SEQUENCE_FLOW_TAKEN)
+                    .withElementId("to-end2")
+                    .exists()
+                ^ RecordingExporter.workflowInstanceRecords(
+                        WorkflowInstanceIntent.SEQUENCE_FLOW_TAKEN)
+                    .withElementId("to-end1")
+                    .exists())
+        .isTrue();
```
Comment (saig0) [inline broker-core/src/test/java/io/zeebe/broker/workflow/gateway/EventbasedGatewayTest.java]: This assertion would wait more than 5 seconds because only one of the events is present. I think it would be better to check that the second timer command is rejected.

**Review by saig0 — CHANGES_REQUESTED** [review]

**Review by saig0 — APPROVED** [review]

**Comment by MiguelPires** [comment]
I improved the tests like you mentioned
