### PR TITLE
fix: prevent duplicate batch operation processing issues

### LINKED ISSUE #40747: Foreign key constraint violation in batch-operation internal state
### 

### 

### 

### 

### Description

Originally reported on [slack](https://camunda.slack.com/archives/C089U9BSWEM/p1760711194437769). 

there were some foreign-key constraints violated in a benchmark:
- [Error log](https://console.cloud.google.com/logs/query;cursorTimestamp=2025-10-15T05:04:31.472783124Z;endTime=2025-10-15T05:35:01.470Z;pinnedLogId=2025-10-15T05:04:31.470249966Z%2Fm37myhwlu619rz1n;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.pod_name%3D%22camunda-0%22%0Aresource.labels.container_name%3D%22orchestration%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.namespace_name%3D%22remco-deletion-poc-1%22%0Atimestamp%3D%222025-10-15T05:04:31.472783124Z%22%0AinsertId%3D%22fv2p6khr8vbz8oby%22;startTime=2025-10-15T04:35:01.470Z?project=zeebe-io)
- [ERROR Group](https://console.cloud.google.com/errors/detail/CJSsyaTXmPqMjQE;service=zeebe;time=P7D;locations=global?project=zeebe-io)

<code>io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=DbForeignKey[inner=DbLong{6755399617246777}, columnFamily=BATCH_OPERATION, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda/0x00007d4710ea29d8@2d1172e9], second=DbLong{0}} in ColumnFamily BATCH_OPERATION_CHUNKS already exists
</code>

It was noticed that there have been multiple restarts during the initialization of the batch operation.

### Steps to reproduce

There are no clear steps to reproduce this issue, this was caught during a benchmark test run.

### Current behavior

An exception is thrown while trying to create a batch operation chunk (with chuck key 0) stating that a chunk with the same key already exists.

### Expected behavior

Such exception should never be seen, and the appliers / state changes should be idempotent. 

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SM

### Version

- Component Version: 8.8.0

### Rootcause

There's a possibility that the issue lies around the `BatchOperationExecutionScheduler`. 

The `BatchOperationExecutionScheduler` gets the next pending batch operation and tries initializing it (by creating/appending chunks), then when done,  it starts the execution phase.

RocksDB only offers read-committed and not repeatable-read isolation level. So the scheduled task could, while iterating through batch operations, first read the state as of TX1 and then see the changes of TX2.
Maybe it's something to do with that, for example because the scheduled task then writes commands with wrong/inconsistent data that ultimately cause this foreign-key violation?

More investigation needs to be done.

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by konstantinos-mylosis**
### 💥 Root Cause
`BatchOperationIntent.CREATED` event would be appended multiple times for the same batch operation key.
This happened when the command wasn’t acknowledged during `BatchOperationCreateProcessor#processDistributedCommand`, causing duplicate processing.
A new `PersistedBatchOperation` instance, with the same batch operation key, was created and `upsert` in the state via `DbBatchOperationState#deprecatedCreate`.
This overrode the previous instance, resetting all persisted properties.

### 🔁 Side Effects

The `BatchOperationExecutionScheduler` retrieves pending batch operations and tries to create chunks for them.
`BatchOperationChunkIntent.CREATED` command was generated multiple times for the same batch operation key.
Each attempt tried to recreate the same chunk repeatedly.

Since `PersistedBatchOperation#chunkKeysProp` were reset, this `PersistedBatchOperation#getMinChunkKey()` returned `-1` every time, causing every new chunk to receive the key `0` in `DbBatchOperationState`.

This resulted in a `ZeebeDbInconsistentException` when trying to insert multiple chunks with the same key.

### ✅ Resolution

- Ensure that batch operation created command is not going to be distributed again if already exists and processed
- Add `BatchOperationCreatedV2Applier` that use `create(long key, BatchOperationCreationRecord record)` and `insert`, instead of the deprecated method that used `upsert`, to prevent duplicate processing and maintain state consistency.

`CommandDistributionIdempotencyTest` can verify if `BatchOperation.CREATE` is idempotent.

### ❓ Question 
`BatchOperationCreatedV1Applier` and `BatchOperationCreatedV2Applier` are considered fixed.
However, the issue might still occur if an instance is still using the old `BatchOperationCreatedV1Applier`

Should we also update `BatchOperationChunkCreatedApplier` altering to `upsert`, to handle these legacy cases?
And introduce `BatchOperationChunkCreatedV2Applier` that will use current implementation with `insert` for new cases?

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #40747

### CODE REVIEW

**Review by remcowesterhoud — COMMENTED** [review]
@mustafadagher Could you take the review? I don't think I'm the best verification considering I helped with the implementation.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java [hunk 1]
```diff
@@ -45,6 +47,8 @@ public final class BatchOperationCreateProcessor
 
   private static final String EMPTY_JSON_OBJECT = "{}";
   private static final String MESSAGE_GIVEN_FILTER_IS_EMPTY = "Given filter is empty";
+  private static final String BATCH_OPERATION_ALREADY_EXISTS =
+      "Expected to create a batch operation with key: '%d', but a batch operation with this key already exists";
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java]: ❓ should the message specify that it's about distributing the `created` batch operation? also should it say `already exists on this partition`?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java [hunk 2]
```diff
@@ -120,13 +127,24 @@ public void processNewCommand(final TypedRecord<BatchOperationCreationRecord> co
...
     final var recordValue = command.getValue();
+    final var recordKey = command.getKey();
 
     LOGGER.debug("Processing distributed command with key '{}': {}", command.getKey(), recordValue);
-    stateWriter.appendFollowUpEvent(
-        command.getKey(),
-        BatchOperationIntent.CREATED,
-        command.getValue(),
-        FollowUpEventMetadata.of(b -> b.batchOperationReference(command.getKey())));
+
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java:133]: 💭 that makes me wonder about a different case actually, if (due to a browser or a network issue) we received the same batch creation on the `lead` partition multiple times.

❓ Should we also have a check on the `processNewCommand()` that if we have a `pending` batch operation with the same exact `filter`, and in that case reject the creation too.

This is a completely separate edge case than the one we are trying to solve here though

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java [hunk 3]
```diff
@@ -120,13 +127,24 @@ public void processNewCommand(final TypedRecord<BatchOperationCreationRecord> co
...
+    batchOperationState
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java:134]: 🔧 should we have any tests to validate the issue and proves this solves it?

**Review by mustafadagher — APPROVED** [review]
Thanks @konstantinos-mylosis for the great work! 🚀 
 👍 The solution looks good overall 

🔧 ❓ 💭 I've left some suggestions, thoughts and questions above, please consider them before merging.

✅ Pre-approving to help speeding up merging in case comments are considered.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java (hunk 3 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java:134]: On `CommandDistributionIdempotencyTest` there is a test case that verifies this 
"BatchOperation.CREATE is idempotent" 

1. sendCommand()
2. interrupt command -- No ack
3. sendCommand() -- will be skipped with fix since already exists

Comment (mustafadagher) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java:134]: the test was already there forever, but it has never caught the problem, so it alarms the need of another test

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java (hunk 1 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java]: Updated this in follow-up [commit](https://github.com/camunda/camunda/pull/40837/commits/6fa009bc72b0007214ae092c2699ab0082658bdd)

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java (hunk 2 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java:133]: Added a check in this [commit](https://github.com/camunda/camunda/pull/40837/commits/6fa009bc72b0007214ae092c2699ab0082658bdd)
better safe than sorry case

**Comment by mustafadagher** [comment]
@remcowesterhoud I'm too busy with medic, but I quickly checked the last changes (in the last two commits) and I don't find an issue there. it looks good to me. But maybe you can give it an extra pair of eyes too?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java [hunk 4]
```diff
@@ -97,6 +97,13 @@ public void processNewCommand(final TypedRecord<BatchOperationCreationRecord> co
       return;
     }
 
+    if (batchOperationState.get(command.getKey()).isPresent()) {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java]: ❌ This won't work. The command comes in through the API and there won't be a key set on the command. If we want to know if it's a duplicate we must check the actual filter that's inside the batch operation.

It'd mean we have to iterate over all the batch operations and compare the entity filter. Personally I'd propose to just leave this check out for now. It's not that important for the patch and is unrelated to the bugfix.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java [hunk 5]
```diff
@@ -349,12 +349,22 @@ private void deleteBatchOperation(final long batchOperationKey) {
...
     chunkKey.wrapLong(batchChunk.getKey());
 
+    final var existingChunk = batchOperationChunksColumnFamily.get(fkBatchKeyAndChunkKey);
+    if (existingChunk != null) {
+      LOGGER.debug(
+          "Chunk with key {} already exists for batch operation {}, returning existing chunk",
+          currentChunkKey,
+          batchOperationKey);
+      return existingChunk;
+    }
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:374]: ❓ Could we at a minimum explain why we need this check and reference this issue? It's really illogical to have this check here and I doubt we remember why we added this three years down the line.

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java (hunk 5 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/batchoperation/DbBatchOperationState.java:374]: Added an explanation

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java (hunk 4 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/batchoperation/BatchOperationCreateProcessor.java]: Removed this block of code

**Review by remcowesterhoud — APPROVED** [review]
