### PR TITLE
Support s3 backup fix connection acquisition timeout  

### LINKED ISSUE #12942: Support S3 backup httpclient custom configuration.
In our case，the directory of `/usr/local/zeebe/data/raft-partition/partitions/1` has about 60 .log files with each one has 128MB size data,and we have 3 patitions,so all the files‘s size almost reach 66GB.When we do backup api,it always failed by throwing exception like below:
image

`
{'backupId': 1685672012, 'status': 'FAILED', 'failureReason': "Backup on partition 3 failed due to java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.\nConsider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.\nIncreasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.\nIf the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.}
`
I also see the code source,S3BackupStore.java create NettyNioAsyncHttpClient with static number 45s of ConnectionAcquireTimeout,and other configuration used the default value.There is no any chance to customizing httpClient configurtation data .
I'm not sure if i have missing somthing important document.Could you help me with this problem?  Thanks.
@oleschoenburg 
image

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

Allow configuration of connectionAcquisitionTimeout and parallelUploadsLimit for S3 backup.

The number of concurrent uploads is now effectively limited by half of this parallelUploadsLimit which prevents uploads from having to wait for an available connection.

## Related issues

closes #12942 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java [hunk 1]
```diff
@@ -59,24 +67,39 @@ CompletableFuture<FileSet> save(final String prefix, final NamedFileSet files) {
...
+              (compressedFile) -> {
+                LOG.trace(
+                    "Saving compressed file {}({}) in prefix {}", fileName, compressedFile, prefix);
+                return client
+                    .putObject(
+                        put -> put.bucket(config.bucketName()).key(prefix + fileName),
+                        AsyncRequestBody.fromFile(compressedFile))
+                    .thenRunAsync(() -> cleanupCompressedFile(compressedFile))
+                    .thenApply(unused -> FileSet.FileMetadata.withCompression(algorithm))
+                    .whenComplete((success, error) -> uploadLimit.release());
```
Comment (oleschoenburg) [inline backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java:88]: :x: this needs to happen even if compressing the file fails. the `thenCompose` in line 78 only applies when the compression succeeded.

File: backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java [hunk 2]
```diff
@@ -59,24 +67,39 @@ CompletableFuture<FileSet> save(final String prefix, final NamedFileSet files) {
...
+    return CompletableFuture.runAsync(uploadLimit::acquireUninterruptibly)
+        .thenCompose(
+            (nothing) -> {
+              LOG.trace("Saving file {}({}) in prefix {}", fileName, filePath, prefix);
+              return client
+                  .putObject(
+                      put -> put.bucket(config.bucketName()).key(prefix + fileName),
+                      AsyncRequestBody.fromFile(filePath))
+                  .thenApply(unused -> FileSet.FileMetadata.none())
+                  .whenComplete((success, error) -> uploadLimit.release());
```
Comment (oleschoenburg) [inline backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java:101]: :wrench: Just for symmetry, this could also be on level higher, similar to the case where we first compress the file

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+    return client;
+  }
+
+  public S3BackupConfig getConfig() {
+    return config;
+  }
+
+  public S3BackupStore getStore() {
+    return store;
+  }
```
Comment (oleschoenburg) [inline backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java:67]: :wrench: No need to use getters here

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+      new LocalStackContainer(DockerImageName.parse("localstack/localstack"))
+          .withServices(Service.S3)
+          .withEnv("LS_LOG", "trace");
+
+  @RegisterExtension
+  final ContainerLogsDumper logsWatcher = new ContainerLogsDumper(() -> Map.of("localstack", S3));
+
+  private S3AsyncClient client;
+  private S3BackupStore store;
+  private S3BackupConfig config;
```
Comment (oleschoenburg) [inline backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java:55]: :wrench: both `client` and `config` are not needed as fields

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java [hunk 5]
```diff
@@ -0,0 +1,171 @@
...
+      client.createBucket(CreateBucketRequest.builder().bucket(config.bucketName()).build()).join();
+    }
+  }
+
+  @AfterEach
+  void tearDown() {
+    store.closeAsync();
+  }
+
+  public void setConfigParallelConnectionsAndTimeout(
```
Comment (oleschoenburg) [inline backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java:88]: :wrench: Instead of setting the `store` field, just return the `store` and rename to `buildStore` or something similar.

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java [hunk 6]
```diff
@@ -0,0 +1,171 @@
...
+    }
+
+    return new BackupImpl(
+        new BackupIdentifierImpl(1, 2, 3),
+        new BackupDescriptorImpl(Optional.of("test-snapshot-id"), 4, 5, "test"),
+        new NamedFileSetImpl(largeNumberOfSegments),
+        new NamedFileSetImpl(Map.of("snapshot-file-1", s1, "snapshot-file-2", s2)));
+  }
+
+  Backup configurableLargeBackup(final int sizeOfFileInBytes) throws IOException {
```
Comment (oleschoenburg) [inline backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java:151]: :wrench: give the two backup-creating methods a similar name. I'd suggest `backupWithManyFiles` and `backupWithLargeFiles`

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java [hunk 7]
```diff
@@ -0,0 +1,171 @@
...
+    Assertions.assertThat(saveFuture).succeedsWithin(Duration.ofSeconds(60));
+  }
+
+  @Test
+  void shouldNotTimeoutForAcquisitionOfConnection() throws IOException {
+    // given
+    // Even with just one connection, and low timeout limit, the second upload should not start
+    // until a connection is available, and therefore should not throw AcquisitionConnectionTimeout
+    setConfigParallelConnectionsAndTimeout(1, Duration.ofMillis(50));
+    final CompletableFuture<Void> saveFuture = getStore().save(configurableLargeBackup(500_000));
```
Comment (oleschoenburg) [inline backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java:124]: :thought_balloon: The files are just 500KB and I'm not sure this test is reliable enough. I'm fine merging as is but I think it could also be a nice opportunity to make use of [toxiproxy](https://java.testcontainers.org/modules/toxiproxy/) to instead introduce a lot of latency between or store and the s3 container. Let me know if you are interested in that, we could pair on it.

File: backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/S3BackupConfig.java [hunk 8]
```diff
@@ -45,7 +45,9 @@ public record S3BackupConfig(
     Optional<Duration> apiCallTimeout,
     boolean forcePathStyleAccess,
     Optional<String> compressionAlgorithm,
-    Optional<String> basePath) {
+    Optional<String> basePath,
+    Integer maxConcurrentConnections,
+    Duration connectionAcquisitionTimeout) {
```
Comment (oleschoenburg) [inline backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/S3BackupConfig.java:50]: :wrench: Please add some javadoc here

**Review by lenaschoenburg — CHANGES_REQUESTED** [review]
Nice progress @rodrigo-lourenco-lopes. I've found one blocker and a couple of suggestions, please take a look.
Additionally:
1. Please update the PR title. This PR does not allow users to configure the http client. It just tries to prevent connection acquisition timeouts by limiting the amount of parallel uploads.
2. Please rebase the branch on main so that we don't have merge commits in the history

File: backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/S3BackupConfig.java [hunk 9]
```diff
@@ -152,7 +152,23 @@ public S3BackupConfig build() {
...
+    @Override
+    public String toString() {
+      return "Credentials{"
+          + "accessKey='"
+          + accessKey
+          + '\''
+          + ", secretKey='"
+          + "<redacted>"
+          + '\''
+          + '}';
```
[the remark this answers is not in the document]
Comment (rodrigo-lourenco-lopes) [reply backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/S3BackupConfig.java:175]: This was changed automatically on my machine after saving. I will check my intelij config 🤔

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java (hunk 5 above)
Comment (rodrigo-lourenco-lopes) [reply backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java:78]: We still use the store for the teardown(), I left it just to have a similar implementation to other tests, but it would also work as you suggested since it is within the scope of the test. Let me know if I should remove it or leave it as is.

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java (hunk 7 above)
Comment (rodrigo-lourenco-lopes) [reply backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java]: I increased the file size to 50MB, which also works with larger files but is quite long. This module seems interesting, do we already use it somewhere in the code?

File: backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java (hunk 1 above)
Comment (rodrigo-lourenco-lopes) [reply backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java:88]: I added the .exceptionally() to return and release the upload channel. I am just wondering if the compression fails if we should try to upload the file uncompressed or just fail normally, wdyt?

Comment (oleschoenburg) [reply backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/FileSetManager.java:88]: This change is not correct unfortunately. Now we'd release the uploadLimit twice when uploading the compressed file fails.

What I meant before is that the `.whenComplete((success, error) -> uploadLimit.release()` should not be chained on the "inner" future where we try to upload the file but on the "outer" future that represents compression and upload.

So like this:

```java
  private CompletableFuture<FileSet.FileMetadata> saveFile(
      final String prefix, final String fileName, final Path filePath) {

    if (shouldCompressFile(filePath)) {
      final var algorithm = config.compressionAlgorithm().orElseThrow();
      return CompletableFuture.runAsync(uploadLimit::acquireUninterruptibly)
          .thenApply((success) -> compressFile(filePath, algorithm))
          .thenCompose(
              (compressedFile) -> {
                LOG.trace(
                    "Saving compressed file {}({}) in prefix {}", fileName, compressedFile, prefix);
                return client
                    .putObject(
                        put -> put.bucket(config.bucketName()).key(prefix + fileName),
                        AsyncRequestBody.fromFile(compressedFile))
                    .thenRunAsync(() -> cleanupCompressedFile(compressedFile))
                    .thenApply(unused -> FileSet.FileMetadata.withCompression(algorithm));
              })
          .whenComplete((success, error) -> uploadLimit.release());
    }

    return CompletableFuture.runAsync(uploadLimit::acquireUninterruptibly)
        .thenCompose(
            (nothing) -> {
              LOG.trace("Saving file {}({}) in prefix {}", fileName, filePath, prefix);
              return client
                  .putObject(
                      put -> put.bucket(config.bucketName()).key(prefix + fileName),
                      AsyncRequestBody.fromFile(filePath))
                  .thenApply(unused -> FileSet.FileMetadata.none());
            })
        .whenComplete((success, error) -> uploadLimit.release());
  }
```

File: backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java (hunk 5 above)
Comment (oleschoenburg) [reply backup-stores/s3/src/test/java/io/camunda/zeebe/backup/s3/BackupUploadIT.java:78]: :+1: Your call - I prefer the explicit handling in each test but both are okay.
If you keep the current style, please rename `setConfigParallelConnectionsAndTimeout` anyway. This method does not just set two config parameters, it builds the entire backup store.

**Review by lenaschoenburg — CHANGES_REQUESTED** [review]
:+1: Sorry for the late review. We are definitely getting closer :tada: 

:x: Please take another look at the section where we are releasing the uploadLimit.
:wrench: Please rename the PR as suggested above

File: backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/S3BackupConfig.java [hunk 10]
```diff
@@ -103,6 +108,12 @@ public static class Builder {
     private Credentials credentials;
     private String basePath;
 
+    /** Default from `SdkHttpConfigurationOption.MAX_CONNECTIONS` */
+    private Integer maxConcurrentConnections = 50;
+
+    /** Default from `SdkHttpConfigurationOption.DEFAULT_CONNECTION_ACQUIRE_TIMEOUT` */
+    private Duration connectionAcquisitionTimeout = Duration.ofSeconds(10);
```
Comment (oleschoenburg) [inline backup-stores/s3/src/main/java/io/camunda/zeebe/backup/s3/S3BackupConfig.java:115]: :x: Unless I'm missing something (it's friday after all :sweat_smile:) this changes the default timeout from 45 seconds to 10 seconds. I don't think we should do that.

**Review by lenaschoenburg — APPROVED** [review]
Nice @rodrigo-lourenco-lopes :partying_face: 

I spotted just one unintended (I think) change to the default connection acquisition timeout that we should revert. I'm approving anyway so that you can merge right after adjusting. :tada:

**Comment by rodrigo-lourenco-lopes** [comment]
bors merge
