### PR TITLE
Handle multi instance body correctly during migration

### LINKED ISSUE #26623: Catch event is attempted to be created for multi instance body during process instance migration
**Describe the bug**

Assume following process instance:
Screenshot 2025-01-07 at 18 36 01

is migrated to following process definition:
Screenshot 2025-01-07 at 18 37 27

during the migration, a message subscription needs to be created for each inner activity of the multi instance body. However, with the current migration implementation a message subscription is attempted to be created for the multi instance body itself as well:

https://github.com/camunda/camunda/blob/6c82cfbf015535782b27efd8551157832249da0e/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationCatchEventBehaviour.java#L296-L354

When `getEvents()` is called on the multi instance body instance:
https://github.com/camunda/camunda/blob/6c82cfbf015535782b27efd8551157832249da0e/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/CatchEventBehavior.java#L182-L188

the message start event inside the event subprocess is returned. Thus, the migration tries to create a subscription for the multi instance body instance as well.

This behaviour is wrong since we must only create message subscription for the inner activities of the multi instance body.

**To Reproduce**

<details><summary>Test case to reproduce</summary>
 <p>

```java
@Test
  public void shouldMigrateMultiInstanceSubprocessContainingEventSubprocess() {
    // given
    final String processId = helper.getBpmnProcessId();
    final String targetProcessId = helper.getBpmnProcessId() + "2";

    final var deployment =
        ENGINE
            .deployment()
            .withXmlResource(
                Bpmn.createExecutableProcess(processId)
                    .startEvent()
                    .subProcess(
                        "sub1",
                        sub ->
                            sub.multiInstance(
                                b ->
                                    b.zeebeInputCollectionExpression("[\"a\",\"b\",\"c\"]")
                                        .zeebeInputElement("i")))
                    .embeddedSubProcess()
                    .startEvent()
                    .serviceTask("A", t -> t.zeebeJobType("A"))
                    .endEvent()
                    .subProcessDone()
                    .endEvent()
                    .done())
            .withXmlResource(
                Bpmn.createExecutableProcess(targetProcessId)
                    .startEvent()
                    .subProcess(
                        "sub2",
                        sub ->
                            sub.multiInstance(
                                b ->
                                    b.zeebeInputCollectionExpression("[\"a\",\"b\",\"c\"]")
                                        .zeebeInputElement("i")))
                    .embeddedSubProcess()
                    .eventSubProcess(
                        "eventSub",
                        s ->
                            s.startEvent("start1")
                                .message(m -> m.name("msg").zeebeCorrelationKeyExpression("i"))
                                .userTask("eventSubprocessUserTask")
                                .endEvent())
                    .startEvent()
                    .serviceTask("B", t -> t.zeebeJobType("B"))
                    .endEvent()
                    .subProcessDone()
                    .endEvent("multi_instance_target_process_end")
                    .done())
            .deploy();

    final long targetProcessDefinitionKey =
        extractProcessDefinitionKeyByProcessId(deployment, targetProcessId);

    final var processInstanceKey = ENGINE.processInstance().ofBpmnProcessId(processId).create();

    assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
                .withProcessInstanceKey(processInstanceKey)
                .withElementId("A")
                .limit(3))
        .describedAs("Wait until all service tasks have activated")
        .hasSize(3);

    // when
    ENGINE
        .processInstance()
        .withInstanceKey(processInstanceKey)
        .migration()
        .withTargetProcessDefinitionKey(targetProcessDefinitionKey)
        .addMappingInstruction("sub1", "sub2")
        .addMappingInstruction("A", "B")
        .migrate();

    // then
    Assertions.assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_MIGRATED)
                .withProcessInstanceKey(processInstanceKey)
                .withElementType(BpmnElementType.MULTI_INSTANCE_BODY)
                .getFirst()
                .getValue())
        .describedAs("Expect that process definition key is changed")
        .hasProcessDefinitionKey(targetProcessDefinitionKey)
        .describedAs("Expect that bpmn process id and element id changed")
        .hasBpmnProcessId(targetProcessId)
        .hasElementId("sub2")
        .describedAs("Expect that version number did not change")
        .hasVersion(1);

    assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_MIGRATED)
                .withProcessInstanceKey(processInstanceKey)
                .withElementType(BpmnElementType.SUB_PROCESS)
                .limit(3))
        .extracting(Record::getValue)
        .extracting(
            r ->
                tuple(
                    r.getProcessDefinitionKey(),
                    r.getBpmnProcessId(),
                    r.getElementId(),
                    r.getVersion()))
        .containsExactly(
            tuple(targetProcessDefinitionKey, targetProcessId, "sub2", 1),
            tuple(targetProcessDefinitionKey, targetProcessId, "sub2", 1),
            tuple(targetProcessDefinitionKey, targetProcessId, "sub2", 1));

    assertThat(
            RecordingExporter.messageSubscriptionRecords(MessageSubscriptionIntent.CREATED)
                .withProcessInstanceKey(processInstanceKey)
                .limit(3))
        .extracting(Record::getValue)
        .extracting(MessageSubscriptionRecordValue::getCorrelationKey)
        .containsExactlyInAnyOrder("a", "b", "c");
  }
```

</p>
</details>

**Expected behavior**

Message subscriptions should only be created for inner activities during the migration.

**Links**
- Support case:  [link](https://jira.camunda.com/browse/SUPPORT-25177)
- Incident:  [link](https://camunda.slack.com/archives/C087JVACE7K)

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

Multi-instance body events are migrated wrong due to a bug in catch event behaviour of process instance migration. Since inner activities of the multi instance body has the same element id as the multi instance body, if we do not set the expected element type, the inner activity of the multi instance body is returned. As a result, event subscriptions are handled for wrong target element.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #26623

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationCatchEventBehaviour.java [hunk 1]
```diff
@@ -115,10 +116,14 @@ public void handleCatchEvents(
...
-            .getProcess()
-            .getElementById(targetElementId, ExecutableCatchEventSupplier.class);
+
+    // set type explicitly for multi-instance body because inner activities has the same element id
+    final var expectedType =
+        elementInstanceRecord.getBpmnElementType() == BpmnElementType.MULTI_INSTANCE_BODY
+            ? ExecutableMultiInstanceBody.class
+            : ExecutableCatchEventSupplier.class;
+    final ExecutableCatchEventSupplier targetElement =
+        targetProcessDefinition.getProcess().getElementById(targetElementId, expectedType);
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationCatchEventBehaviour.java:126]: 👍 Nice fix! I wasn't aware of the implementation details of that method!

🔧 Might be nice to extend the JavaDoc of that method a bit so it becomes clear that it can be used like this.

**Review by korthout — APPROVED** [review]
Great fix! 🥇 

LGTM 👍 

🔧 Pleas have a look at my suggestion before merging.

❓ Should we backport this?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationCatchEventBehaviour.java (hunk 1 above)
Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationCatchEventBehaviour.java:126]: Good point! Updated 👍

**Comment by korthout** [comment]
@berkaycanbc is this on your radar?

**Comment by berkaycanbc** [comment]
@korthout yes, I couldn't come back due to other tasks but I will resolve conflicts in backport PRs this week. 👍
