### PR TITLE
bugfix: message cardinality can be broken by instance migration

### LINKED ISSUE #26008: Message cardinality can be broken by instance migration
**Describe the bug**

Our documentation specifies:
>**A message is not correlated to a message start event subscription if an instance of the process is active and was created by a message with the same correlation key**. If the message is buffered, it can be correlated after the active instance is ended. Otherwise, it is discarded.

Using process instance migration, it's possible to migrate a process instance created by a message with a correlation key, to a process for which another instance was created by a message with the same correlation key. 

Generally, this happens if both process instances were created by the same message, and one of these process instances is migrated to the other process model. _There should generally not be any reason to do this in production environments. However, users can do it._

In addition to this unlikely case, it also breaks message cardinality if a process instance (created by a message) is migrated to a process with a different `processID`. It's now no longer possible to create a new process instance of the process that no longer has an active instance. At the same time, it's possible to create a new instance of the process that does have an active instance. _This may be a common case, with high likelihood, but that's not yet known. Marking as unknown likelihood._

This doesn't just break the message cardinality feature, but can also lead to the consistency check failing (if `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS` is set to `true`), when both instances are completed/terminated. This is because we attempt to delete the marker tracking the active process instances for the `processId` and the `correlationKey`. The second delete fails, as the value doesn't exist anymore.

**To Reproduce**

I've provided two test cases:
- d340c411a0554ffe2ac9ab4c23f3bda679b1dd96
- 78839ddd0a2f8955ed50639ff7d468ff52ceab3b

**Expected behavior**

The marker tracking the active process instances for the `processId` and the `correlationKey` must be adjusted on migration, to ensure we continue to track message cardinality for the correct process after migration.

The migration must be rejected if it would result in two active instances for a process both created by a message with the same correlation key.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2024-12-11 20:48:40.432 - io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=[redacted], second=[redacted]} in ColumnFamily MESSAGE_PROCESSES_ACTIVE_BY_CORRELATION_KEY does not exist
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyExists(TransactionalColumnFamily.java:332) ~[zeebe-db-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$deleteExisting$14(TransactionalColumnFamily.java:227) ~[zeebe-db-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:344) ~[zeebe-db-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[zeebe-db-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:343) ~[zeebe-db-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.deleteExisting(TransactionalColumnFamily.java:224) ~[zeebe-db-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.state.message.DbMessageState.removeActiveProcessInstance(DbMessageState.java:291) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.state.appliers.BufferedStartMessageEventStateApplier.removeProcessInstanceMessageLock(BufferedStartMessageEventStateApplier.java:61) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.state.appliers.BufferedStartMessageEventStateApplier.removeMessageLock(BufferedStartMessageEventStateApplier.java:41) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementTerminatedApplier.applyState(ProcessInstanceElementTerminatedApplier.java:38) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementTerminatedApplier.applyState(ProcessInstanceElementTerminatedApplier.java:19) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:499) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:56) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:42) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionTo(BpmnStateTransitionBehavior.java:223) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionToTerminated(BpmnStateTransitionBehavior.java:213) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$onChildTerminated$7(ProcessProcessor.java:194) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.transitionTo(ProcessProcessor.java:206) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:189) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:29) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.lambda$onElementTerminated$5(BpmnStateTransitionBehavior.java:428) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:478) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementTerminated(BpmnStateTransitionBehavior.java:423) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.event.IntermediateThrowEventProcessor.onTerminate(IntermediateThrowEventProcessor.java:105) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.event.IntermediateThrowEventProcessor.onTerminate(IntermediateThrowEventProcessor.java:29) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:174) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:110) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:107) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:129) ~[zeebe-workflow-engine-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:375) ~[zeebe-stream-platform-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:285) ~[zeebe-stream-platform-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:109) ~[zeebe-db-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:285) ~[zeebe-stream-platform-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:244) ~[zeebe-stream-platform-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:83) ~[zeebe-scheduler-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.5.jar:8.6.5]
```

</p>
</details>

**Environment:**
- Zeebe Version: At least in 8.6.5, possibly since 8.4+

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

@korthout please check my comment for the `correlatedMessageColumnFamily` in the commit message 0d5da339f63e6b082d9ddcb821909ee91a8c28b3 and verify if my inference about its usage is correct.

## Related issues

closes #26008

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java [hunk 1]
```diff
@@ -194,4 +195,64 @@ public void shouldWriteElementMigratedEventForProcessInstanceToNewVersion() {
...
+                Bpmn.createExecutableProcess(processId)
+                    .startEvent("msg_start")
+                    .message("msg1")
+                    .serviceTask("A", t -> t.zeebeJobType("A"))
+                    .endEvent()
+                    .done())
+            .withXmlResource(
+                Bpmn.createExecutableProcess(targetProcessId)
+                    .startEvent("msg_start")
+                    .message("msg2")
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java:218]: 🔧 It would be useful to clarify why these processes have different message names. For example, that it allows for this test to only trigger one of them at any time, but also to migrate that one instance over to the other process.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java [hunk 2]
```diff
@@ -255,4 +256,163 @@ public void shouldAdjustMessageCardinalityTrackingWhenMigratedForProcessInstance
...
+        .migrate();
+
+    // then
+    final long messagePosition =
+        ENGINE
+            .message()
+            .withName("msg2")
+            .withCorrelationKey("cardinality")
+            .publish()
+            .getSourceRecordPosition();
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java:312]: 🔧 While this solution works, another idea is to use the relatively new Correlate Message API to know whether the message was (or wasn't) correlated. Please only use that API if we can backport the solution to the required versions.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java [hunk 3]
```diff
@@ -255,4 +256,163 @@ public void shouldAdjustMessageCardinalityTrackingWhenMigratedForProcessInstance
...
+
+    Assertions.assertThat(
+            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
+                .withElementType(BpmnElementType.PROCESS)
+                .withBpmnProcessId(targetProcessId)
+                .exists())
+        .isTrue();
+  }
+
+  @Test
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java:339]: 🔧 These tests could use a little bit of java doc to explain what they try to achieve. For example, after migrating a process instance started by a message, we expect that a buffered message with the same correlation key cannot be correlated until the process instance completes. We expect that the buffered message is automatically correlated once the instance finishes.

**Review by korthout — CHANGES_REQUESTED** [review]
Nice work @berkaycanbc 🏗️ 

It covers most of the needs, but not yet all

❌ The test case (d340c411a0554ffe2ac9ab4c23f3bda679b1dd96 in the issue description) to reproduce the bug is missing and still fails when added and run.

Please have a look.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementMigratedApplier.java [hunk 4]
```diff
@@ -38,6 +44,24 @@ public void applyState(final long elementInstanceKey, final ProcessInstanceRecor
       return;
     }
 
+    if (value.getBpmnElementType() == BpmnElementType.PROCESS) {
+      final DirectBuffer correlationKey =
```
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementMigratedApplier.java]: Right, updated 👍

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementMigratedApplier.java [hunk 5]
```diff
@@ -38,6 +44,24 @@ public void applyState(final long elementInstanceKey, final ProcessInstanceRecor
...
+        // unlock old process instance
+        final var previousBpmnProcessId =
+            elementInstanceState
+                .getInstance(elementInstanceKey)
+                .getValue()
+                .getBpmnProcessIdBuffer();
+        messageState.removeActiveProcessInstance(previousBpmnProcessId, correlationKey);
+
+        // lock the target process for the correlation key
+        messageState.putActiveProcessInstance(value.getBpmnProcessIdBuffer(), correlationKey);
```
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementMigratedApplier.java]: Updated the implementation in the applier 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java (hunk 2 above)
Comment (berkaycanbc) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java:312]: I chose to skip it for now 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java (hunk 1 above)
Comment (berkaycanbc) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java:218]: > but also to migrate that one instance over to the other process.

@korthout This part needs a bit more clarification for me. If the message name stays the same, we can still migrate one instance over to the other process, right? Or I couldn't get the meaning.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java (hunk 3 above)
Comment (berkaycanbc) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java:339]: Updated!

**Comment by berkaycanbc** [comment]
@korthout I am finally back at this 🙇‍♂️.  Thanks for the initial review. ⭐ 

👀 Please take a look at my latest commits. Let me know if you wish more clarification on various test cases. I can create java doc for them.

**Review by korthout — COMMENTED** [review]
Thanks @berkaycanbc 

🙇 Sorry for the late review

🔧 There are still some things to improve on the test cases.

- Many were added that don't actually verify anything related to message cardinality.
- Given their size, they can all benefit from some additional explanations, perhaps moving them to a separate class, etc.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementMigratedApplier.java [hunk 6]
```diff
@@ -45,21 +46,7 @@ public void applyState(final long elementInstanceKey, final ProcessInstanceRecor
...
-            elementInstanceState
-                .getInstance(elementInstanceKey)
-                .getValue()
-                .getBpmnProcessIdBuffer();
-        messageState.removeActiveProcessInstance(previousBpmnProcessId, correlationKey);
-
-        // lock the target process for the correlation key
-        messageState.putActiveProcessInstance(value.getBpmnProcessIdBuffer(), correlationKey);
-      }
+      migrateCorrelatedMessageStartEvent(elementInstanceKey, value);
```
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementMigratedApplier.java]: Oh, I made changes directly in V2 after copying. 🤦

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java [hunk 7]
```diff
@@ -194,4 +196,619 @@ public void shouldWriteElementMigratedEventForProcessInstanceToNewVersion() {
...
+                .withElementType(BpmnElementType.PROCESS)
+                .getFirst()
+                .getValue())
+        .describedAs("Expect that process definition key changed")
+        .hasProcessDefinitionKey(targetProcessDefinitionKey)
+        .describedAs("Expect that bpmn process id and element id is the same")
+        .hasBpmnProcessId(processId1)
+        .hasElementId(processId1)
+        .describedAs("Expect that version number is changed")
+        .hasVersion(2);
```
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/migration/MigrateProcessInstanceTest.java]: @korthout these tests were verifying that precondition allows such migrations. But they were not directly checking the cardinality. So, they were just more tests to verify migration with message start events. I think, it is safe to remove them. 👍

**Comment by berkaycanbc** [comment]
@korthout I've added doc for each test case, moved them to a new test class and removed possibly unnecessary test cases. Please take a look. 👀

**Review by korthout — APPROVED** [review]
Thanks for the changes @berkaycanbc 🚀 

LGTM 💯 

EDIT: you'll need to rebase on `main` and resolve a conflict

**Comment by berkaycanbc** [comment]
@korthout yes, I couldn't come back due to other tasks but I will resolve conflicts this week and merge. 👍
