### PR TITLE
Fix job polling tenant check

### LINKED ISSUE #37472: Authorization exception for Job Activation with Multi Tenancy
### 

### 

### 

### 

### Description

Job activation rejected in Multi Tenancy setup - user not authorized

Endpoint: [/v2/jobs/activation](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/activate-jobs/)" \
Response: 
```
{
  "type": "about:blank",
  "title": "UNAUTHORIZED",
  "status": 401,
  "detail": "Command 'ACTIVATE' rejected with code 'UNAUTHORIZED': Expected to activate job batch for tenants '[tenantC]', but user is not authorized. Authorized tenants are '[]'",
  "instance": "/core/v2/jobs/activation"
}

```

### Steps to reproduce

1. user is assigned to tenant via mapping rule - client name 'hans'
2. Service task is executed and job is waiting for activation
3. double check if client belongs to the respective tenant

TOKEN payload:
```
{
  "exp": 1756803637,
  "iat": 1756803337,
  "jti": "53676cd7-5028-4b09-9b03-911f5f454856",
  "iss": "https://qa-sergii.ci.distro.ultrawombat.com/auth/realms/camunda-platform",
  "aud": [
    "orchestration-api",
    "account"
  ],
  "sub": "5a9b96c4-0031-428a-bb9e-ebd819fdd154",
  "typ": "Bearer",
  "azp": "hans",
  "acr": "1",
  "allowed-origins": [
    "/*"
  ],
  "realm_access": {
    "roles": [
      "Default user role"
    ]
  },
  "resource_access": {
    "orchestration-api": {
      "roles": [
        "read:*",
        "write:*"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "email_verified": false,
  "clientHost": "10.1.0.248",
  "permissions": {
    "orchestration-api": [
      "read:*",
      "write:*"
    ],
    "account": [
      "manage-account",
      "manage-account-links",
      "view-profile"
    ]
  },
  "preferred_username": "service-account-hans",
  "clientAddress": "10.1.0.248",
  "client_id": "hans"
}
```

> curl -X POST "http://qa-sergii.ci.distro.ultrawombat.com/core/v2/tenants/tenantC/mapping-rules/search" \
-H "Authorization: Bearer $TOKEN" \
-H "Content-Type: application/json" \
-d '{}'|jq
{
  "items": [
    {
      "claimName": "client_id",
      "claimValue": "hans",
      "name": "Hans Client",
      "mappingRuleId": "hans_client"
    }
  ]
}

4. Activate job via  [/v2/jobs/activation](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/activate-jobs/)" \

### Current behavior

```
{
  "type": "about:blank",
  "title": "UNAUTHORIZED",
  "status": 401,
  "detail": "Command 'ACTIVATE' rejected with code 'UNAUTHORIZED': Expected to activate job batch for tenants '[tenantC]', but user is not authorized. Authorized tenants are '[]'",
  "instance": "/core/v2/jobs/activation"
}

```

### Expected behavior

Activation successful 

### Environment

SM

### Version

- Component Version: SNAPSHOT as of today

### Rootcause

* [AuthorizationCheckBehavior#getAuthorizedTenantIds](https://github.com/camunda/camunda/blob/5da12dc5b5204e958ab65e73f1d1fd85d72d0ae5/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java#L455-L476) doesn't consider mapping rules when a username or client id is present in the request

### Solution ideas

* `AuthorizationCheckBehavior#getAuthorizedTenantIds` should apply tenant memberships from mapping rules on top of what is assinged to the user or client directly.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

* related issue: #37489

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Ensure that mapping rule tenant assignments are added on top of user or client tenant assignments.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #37472

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java [hunk 1]
```diff
@@ -452,18 +452,19 @@ public AuthorizedTenants getAuthorizedTenantIds(final TypedRecord<?> command) {
       return AuthorizedTenants.DEFAULT_TENANTS;
     }
 
+    final var authorizedTenants = new HashSet<String>();
     final var username = getUsername(command);
     if (username.isPresent()) {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java]: 🙃 Could use an `ifPresent` call here

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java [hunk 2]
```diff
@@ -452,18 +452,19 @@ public AuthorizedTenants getAuthorizedTenantIds(final TypedRecord<?> command) {
...
-      final var tenantIds =
-          getAuthorizedTenantIds(command, EntityType.USER, username.get()).toList();
-      return new AuthenticatedAuthorizedTenants(tenantIds);
+      authorizedTenants.addAll(
+          getAuthorizedTenantIds(command, EntityType.USER, username.get())
+              .collect(Collectors.toSet()));
     }
 
     final var clientId = getClientId(command);
     if (clientId.isPresent()) {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java]: 🙃 Could use an `ifPresent` call here

**Review by remcowesterhoud — APPROVED** [review]
LGTM! Just some nitpick, feel free to ignore
