### PR TITLE
fix: Add support for sorting Authorization records by `resourceId`

### LINKED ISSUE #40799: Authorizations search does not support sorting by `resourceId` (RDBMS, ES/OS)
### 

### 

, 

### 

### 

### Description

While CamundaClient and REST Authorizations Search endpoint support sorting authorizations by `resourceId`, the underlying RDBMS implementation does not. Attempting to sort by `resourceId` results in the following error:

```
java.lang.IllegalArgumentException: Unknown sortField: resourceId
	at io.camunda.db.rdbms.read.service.AbstractEntityReader.lambda$getSearchColumn$0(AbstractEntityReader.java:51)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.camunda.db.rdbms.read.service.AbstractEntityReader.getSearchColumn(AbstractEntityReader.java:51)
	at io.camunda.db.rdbms.read.service.AbstractEntityReader.convertSort(AbstractEntityReader.java:61)
	at io.camunda.db.rdbms.read.service.AuthorizationDbReader.search(AuthorizationDbReader.java:64)
	at io.camunda.db.rdbms.read.service.AuthorizationDbReader.search(AuthorizationDbReader.java:89)
```

This bug can lead to failed API commands/queries if a user attempts to sort by `resourceId`.

### Steps to reproduce

1. Call `CamundaClient.newAuthorizationSearchRequest`:
```java
    client
        .newAuthorizationSearchRequest()
        .sort(s -> s.resourceId().desc())
        .page(fn -> fn.limit(5))
        .send()
        .join();
```
or [Search authorizations](https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/search-authorizations/) REST endpoint with a sort parameter for `resourceId`
2. Use RDBMS as storage backend
3. Observe that the call fails with the provided stack trace

### Current behavior

Sorting by `resourceId` on authorizations with RDBMS as a secondary storage results in `IllegalArgumentException` and API failure.

### Expected behavior

Sorting authorizations by `resourceId` should be supported by the RDBMS secondary storage and work as for other sort fields.

### Workaround

No workaround in RDBMS backend. Avoid sorting by `resourceId`, or use a different (ES/OS) secondary storage.

### Environment

SM

### Version

- 8.9-SNAPSHOT

### Rootcause

The root cause is that [AuthorizationDbReader#search](https://github.com/camunda/camunda/blob/95bf9c99e604bba7d3a212b7057eadc181cd0b28/db/rdbms/src/main/java/io/camunda/db/rdbms/read/service/AuthorizationDbReader.java#L64-L68) doesn't recognize & handle sorting by `resourceId`.

### Solution ideas

- Add `RESOURCE_ID("resourceId")` to [AuthorizationSearchColumn](https://github.com/camunda/camunda/blob/main/db/rdbms/src/main/java/io/camunda/db/rdbms/sql/columns/AuthorizationSearchColumn.java) enum.
- Add tests, e.g., in [AuthorizationSpecificFilterIT](https://github.com/camunda/camunda/blob/95bf9c99e604bba7d3a212b7057eadc181cd0b28/qa/acceptance-tests/src/test/java/io/camunda/it/rdbms/db/authorization/AuthorizationSpecificFilterIT.java#L45), to verify sorting by `resourceId` is recognized and works as intended

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description

This PR fixes a bug where sorting authorizations by `resourceId` was not properly supported across storage backends.

### Additional issue discovered - ES/OS:
- While fixing the RDBMS issue, discovered that ES/OS backends also didn't properly support `resourceId` sorting.
  - The API accepted `resourceId` as a sort parameter but silently ignored it, leading to incorrect sorting behavior.

#### RDBMS implementation:
- Added `RESOURCE_ID("resourceId")` to `AuthorizationSearchColumn` enum to avoid `IllegalArgumentException: Unknown sortField: resourceId` exception.

#### ES/OS implementation:
- Fixed `resourceId` field name in authorization sort validation (from `"resourceIds"` to `"resourceId"`).

**Tests:**
- Added tests to `AuthorizationSpecificFilterIT` to verify sorting by `resourceId` works correctly, covering both ascending and descending sort orders (RDBMS).
- Added test to `AuthorizationIntegrationTest` that verifies sorting by `resourceId` properly works across all storage backends (RDBMS, ES, OS).

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #40799

### CODE REVIEW

File: db/rdbms/src/main/java/io/camunda/db/rdbms/sql/columns/AuthorizationSearchColumn.java [hunk 1]
```diff
@@ -12,7 +12,8 @@
 public enum AuthorizationSearchColumn implements SearchColumn<AuthorizationEntity> {
   OWNER_ID("ownerId"),
   OWNER_TYPE("ownerType"),
-  RESOURCE_TYPE("resourceType");
+  RESOURCE_TYPE("resourceType"),
+  RESOURCE_ID("resourceId");
```
Comment (ce-dmelnych) [inline db/rdbms/src/main/java/io/camunda/db/rdbms/sql/columns/AuthorizationSearchColumn.java:16]: ❓ Should we also provide `AuthorizationSearchColumn.RESOURCE_ID` as a `discriminatorColumn` in the [AuthorizationDbReader#search -> AbstractEntityReader#convertSort](https://github.com/camunda/camunda/blob/1175c45f1c7ff72624122a2ee70f8e7d98363985/db/rdbms/src/main/java/io/camunda/db/rdbms/read/service/AuthorizationDbReader.java#L64-L68) method.

As I understand it, adding this would result in default `ASC` secondary sorting on the `resourceId` property.  

Some examples for clarity:
1. No sort specified in `AuthorizationQuery`:  
   `ORDER BY ownerId ASC, ownerType ASC, resourceType ASC, resourceId ASC`

2. Sort by `resourceId DESC`: 
   `ORDER BY resourceId DESC, ownerId ASC, ownerType ASC, resourceType ASC`  
   (`resourceId` would be removed from discriminators to avoid duplicate sorting)

Do you think including `resourceId` here makes sense for consistency? Or could it introduce any unintended side effects?
_Considering that with https://github.com/camunda/camunda/pull/40353 we will also have `resorucePropetyName` property, which - in case of adding `RESOURCE_ID` - would follow it._

Curious to hear your thoughts! 🤓

Comment (fabiopaini-camunda) [reply db/rdbms/src/main/java/io/camunda/db/rdbms/sql/columns/AuthorizationSearchColumn.java:16]: I do think it would make sense, since we are already doing it for all other search columns and it does not break retro-compatibility (we had no assurance on how authorizations are sorted after "resourceType").
You should just take care about whether already-existing tests expect authorizations to be sorted in a different way than how they will be sorted after this change.

:thought_balloon: If we actually want to always include all search columns as discriminator columns too, it could make sense to edit `AuthorizationDbReader#search` to include all of them, so we avoid the risk of forgetting about it when adding a new search column:
```
    final var dbSort =
        convertSort(
            query.sort(),
-            AuthorizationSearchColumn.OWNER_ID,
-            AuthorizationSearchColumn.OWNER_TYPE,
-            AuthorizationSearchColumn.RESOURCE_TYPE
+            AuthorizationSearchColumn.values());
```

**Review by fabiopaini-camunda — APPROVED** [review]
:rocket:  LGTM

:thought_balloon: I added an idea in the discussion about discriminator columns, but I think this can be postponed after merging this PR

File: db/rdbms/src/main/java/io/camunda/db/rdbms/sql/columns/AuthorizationSearchColumn.java (hunk 1 above)
Comment (ce-dmelnych) [reply db/rdbms/src/main/java/io/camunda/db/rdbms/sql/columns/AuthorizationSearchColumn.java:16]: Thanks Fabio 🙏🏻

I like the idea of providing `AuthorizationSearchColumn.values()`. However, what holds me back is that, looking at other `*DbReader` classes, it seems the values for `discriminatorColumns` are chosen deliberately. For example, in [CorrelatedMessageSubscriptionSearchColumn](https://github.com/camunda/camunda/blob/ea76dbdc45c74282bfb0f5e610a069c1ee344faf/db/rdbms/src/main/java/io/camunda/db/rdbms/sql/columns/CorrelatedMessageSubscriptionSearchColumn.java#L14-L25), there are 12 possible values, but in the corresponding [CorrelatedMessageSubscriptionDbReader](https://github.com/camunda/camunda/blob/ea76dbdc45c74282bfb0f5e610a069c1ee344faf/db/rdbms/src/main/java/io/camunda/db/rdbms/read/service/CorrelatedMessageSubscriptionDbReader.java#L50-L51) only `MESSAGE_KEY` and `SUBSCRIPTION_KEY` are used. I see a similar pattern in other readers too.

I assume this is for performance reasons - to restrict default sorting to a limited set of sortable fields and avoid possible overhead. 

Also, since this PR will be backported to 8.8 as a bug-fix, and adding default sorting could be seen as a feature, I prefer to keep it as it is for now. We could address default sorting improvements separately.

Thanks for your input!
