### PR TITLE
fix: allow fullscreen api in permissions-policy header

### LINKED ISSUE #48823: Fullscreen toggle does not work in Operate diagram controls (Chrome)
### 

### 

### 

### 

### Description

The full-screen toggle fails to activate the full-screen mode in the diagram controls (Operate component).

Browser: Chrome (latest)

### Steps to reproduce

1. Open Operate and navigate to a Process Instance page.
2. Locate the diagram controls area (bottom-right).
3. Click the Fullscreen button.
4. Observe that the diagram does not enter fullscreen mode.

### Current behavior

Clicking Fullscreen does not affect the diagram; it remains at its regular size. No fullscreen overlay appears, and no exit control is shown.

https://github.com/user-attachments/assets/a16bfc2f-0c6a-43f7-8d3c-9db48c0dce76

### Expected behavior

Diagram should expand to fullscreen view, minimizing surrounding UI, and allow exiting fullscreen via control or Esc key.

### Workaround

Workaround

### Environment

SaaS

### Version

8.9

### Rootcause

_No response_

### Solution ideas

Solution ideas

### Dev -> QA handover

_No response_

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by juliasaienko**
## Description

  - Change `fullscreen=()` to `fullscreen=(self)` in the default `Permissions-Policy` HTTP header to allow the Fullscreen API for same-origin documents
  - Add `.catch()` to `requestFullscreen()` in the diagram component to handle policy rejections
  
 Root cause analysis: 
In deployed environments, clickig the diagram fullscreen button logs `[Violation] Permissions policy violation: fullscreen is not allowed in this document` and does nothing. This works locally because the dev server doesn't set the `Permissions-Policy` header.
The root cause is the server-side `Permissions-Policy` header includes `fullscreen=()`, which completely disables the Fullscreen API for the document. The Diagram component `el.requestFullscreen()` call then fail because browser enforces this policy.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #48823

### CODE REVIEW

File: operate/client/src/modules/components/Diagram/index.tsx [hunk 1]
```diff
@@ -72,7 +72,9 @@ const useFullscreen = (
       return;
     }
 
-    el.requestFullscreen();
+    el.requestFullscreen().catch(() => {
+      // Fullscreen blocked by Permissions Policy — silently ignore
+    });
```
Comment (vsgoulart) [inline operate/client/src/modules/components/Diagram/index.tsx:75]: @juliasaienko An idea would be to display a toast notification that fullscreen is not permitted and save it on the session storage so we can hide the button on the other pages.

What do you think? I think it's not that hard to implement, is it?

**Review by vsgoulart — APPROVED** [review]
Frontend part looks good to me, just ma de a minor suggestion.

We need to wait for the review of a backend engineer though

**Review by Ben-Sheppard — APPROVED** [review]
Backend seems fine to me, interestingly it looks like `fullscreen=(self)` is actually the default behaviour ([REF](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#controlling_access)) :)
