### PR TITLE
fix(topology): do not update the topology if the operation was cancelled

### LINKED ISSUE #15726: After cancellation, a completed change operation should not overwrite updated topology

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

The change must be cancelled only the operation cannot make progress. But it might still happen that after it was cancelled, operation was applied successfully and incorrectly apply the changes on the cancelled topology. To prevent this, we now compare the expected topology with the current topology before applying the change.

## Related issues

closes #15726

### CODE REVIEW

File: topology/src/main/java/io/camunda/zeebe/topology/ClusterTopologyManagerImpl.java [hunk 1]
```diff
@@ -245,10 +245,12 @@ private void applyTopologyChangeOperation(final ClusterTopology mergedTopology)
       return;
     }
 
+    final var updatedTopology = initialized.get();
```
Comment (oleschoenburg) [inline topology/src/main/java/io/camunda/zeebe/topology/ClusterTopologyManagerImpl.java:248]: :wrench: Can we call this `initializedTopology`? `updatedTopology` sounds to me like the result of applying the transformer which happens later.

File: topology/src/main/java/io/camunda/zeebe/topology/ClusterTopologyManagerImpl.java [hunk 2]
```diff
@@ -276,6 +279,15 @@ private void onOperationApplied(
...
+          != topologyOnWhichOperationIsApplied.version()) {
+        LOG.debug(
+            "Topology changed while applying operation {}. Expected topology is {}. Current topology is {}. Most likely the change operation was cancelled.",
+            operation,
+            topologyOnWhichOperationIsApplied,
+            persistedClusterTopology.getTopology());
+        return;
+      }
       updateLocalTopology(
           persistedClusterTopology.getTopology().advanceTopologyChange(localMemberId, transformer));
```
Comment (oleschoenburg) [inline topology/src/main/java/io/camunda/zeebe/topology/ClusterTopologyManagerImpl.java:292]: :thought_balloon: Could we just make `updateLocalTopology` a CAS operation? So `onOperationApplied` just takes the expected current topology as input and passes it to `updateLocalTopology` which then compares it with the persisted one and bails out if it's different.
To me this would feel a bit more robust

**Review by lenaschoenburg — APPROVED** [review]
:+1:

File: topology/src/main/java/io/camunda/zeebe/topology/ClusterTopologyManagerImpl.java (hunk 2 above)
Comment (deepthidevaki) [reply topology/src/main/java/io/camunda/zeebe/topology/ClusterTopologyManagerImpl.java:292]: Not sure whether that is worth. `onOperationApplied` is the only place where this CAS is required. Other usages are directly updating the current topology.
