### PR TITLE
fix: json mapping errors in cpt due to ignored mapping configuration

### LINKED ISSUE #37758: hasVariableSatisfies assertion fails on deserializing values written with a customized ObjectMapper
### 

### 

### 

### 

### Description

Given a customized ObjectMapper setup is used for workers, e.g.:
```
    @Bean
    public JsonMapper jsonMapper() {
        ObjectMapper objectMapper = new ObjectMapper()
                .configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true)
                .registerModule(new JavaTimeModule());
        return new CamundaObjectMapper(objectMapper);
    }
```
It can lead to `hasVariableSatisfies` failing to convert a variable to a certain Type as documented [here](https://docs.camunda.io/docs/next/apis-tools/testing/assertions/#hasvariablesatisfies), logging.

```
java.lang.AssertionError: Process instance [key: 2251799813685293] should have a variable 'bpt2' of type 'io.camunda.support.job_worker.BlueprintTest', but was: '{"id":1,"createdDate":[2025,9,8,14,43,7,603921000],"modifiedDate":null,"businessKey":"testBusinessKey"}'

	at io.camunda.process.test.impl.assertions.VariableAssertj.hasVariableSatisfies(VariableAssertj.java:267)
	at io.camunda.process.test.impl.assertions.VariableAssertj.hasVariableSatisfies(VariableAssertj.java:206)
	at io.camunda.process.test.impl.assertions.ProcessInstanceAssertj.hasVariableSatisfies(ProcessInstanceAssertj.java:291)
	at io.camunda.support.job_worker.MyProcessTest.shouldHaveVariables_worker_ok(MyProcessTest.java:76)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
```

Note:
due to #37608 the underlying cause is not transparent to the user, in the particular case it was:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (or disable `MapperFeature.REQUIRE_HANDLERS_FOR_JAVA8_TIMES`)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 23] (through reference chain: io.camunda.support.job_worker.BlueprintTest["createdDate"])
```

### Steps to reproduce

See `MyProcessTest#shouldHaveVariables_worker_issue3_failing_to_parse_jsr310` in the attached reproducer project.

[test-cpt-bug2.zip](https://github.com/user-attachments/files/22211296/test-cpt-bug2.zip)

### Current behavior

* You cannot adapt the ObjectMapper setting to be aligned with the one used by the job worker, as `hasVariableSatisfies` is using the static mapper setup in [AssertionJsonMapper](https://github.com/camunda/camunda/blob/main/testing/camunda-process-test-java/src/main/java/io/camunda/process/test/impl/assertions/util/AssertionJsonMapper.java#L25)

### Expected behavior

* allow the user to configure CPT to make use of the same mapper setup as the client code/job worker

### Workaround

Not pretty but you can workaround this limitation/bug by parsing manually in the `hasVariableSatisfies` lambda:
```
// have the objectmapper injected
    @Autowired private JsonMapper jsonMapper;

    @Test
    void shouldHaveVariables_worker_issue3_workaround_to_parse_jsr310() {
        // start instance code

        CamundaAssert.assertThat(processInstance).hasVariableSatisfies("bpt2", Map.class, bptString -> {
            // use the jsonMapper to convert the generic map to a string and parse it as the desired type
            BlueprintTest bpt = jsonMapper.fromJson(jsonMapper.toJson(bptString), BlueprintTest.class);

            // your assertions go here
        });
    }


```

### Environment

SaaS & SM

### Version

- Component Version: 8.8.0-SNAPSHOT

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by Christian-Broomfield**
## Description

The JsonAssertionMapper would fail to (de)serialize objects because of missing configuration options, e.g. the JSR 310 module for LocalDateTime objects. This PR fixes the issue by ensuring that an existing JsonMapper or zeebe JsonMapper configuration is either found or configured, then injected into the CamundaProcessTestContext and CamundaAssert. This way, both the CamundaClient and the assertion classes have the correct JsonMapper dependency to handle all (de)serialization tasks.

Dev Note: From what I can tell, JsonMapper and zeebe JsonMapper can't be merged or migrated. Thus, I had to create a new UnifiedJsonMapper that accepts either implementation and (de)serializes code with one of them. This may lead to some confusion that despite the documentation in the CamundaAssert class.

## Related issues

closes #37758

### CODE REVIEW

File: testing/camunda-process-test-java/src/main/java/io/camunda/process/test/impl/assertions/util/UnifiedJsonMapper.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+ * limitations under the License.
+ */
+package io.camunda.process.test.impl.assertions.util;
+
+import com.fasterxml.jackson.databind.JsonNode;
+import com.fasterxml.jackson.databind.node.NullNode;
+import io.camunda.client.api.JsonMapper;
+import io.camunda.client.api.command.InternalClientException;
+
+public class UnifiedJsonMapper {
```
Comment (Christian-Broomfield) [inline testing/camunda-process-test-java/src/main/java/io/camunda/process/test/impl/assertions/util/UnifiedJsonMapper.java]: Dev Note:  my first attempt was to extend the AssertionJsonMapper with a new static `setJsonMapper` implementation and call it a day. However, since the AssertionJsonMapper is a static object, it would become a source of magic as users delving into the code couldn't immediately see where the JsonMapper was being injected from. I decided to turn it into a non-static class that is managed by the CamundaAssert, where all assertion classes are used anyway. That makes it much more obvious to understand in my opinion.

File: testing/camunda-process-test-java/src/main/java/io/camunda/process/test/api/CamundaProcessTestExtension.java [hunk 2]
```diff
@@ -564,6 +584,18 @@ public CamundaProcessTestExtension withMultitenancyEnabled() {
...
+    this.jsonMapper = jsonMapper;
+    return this;
+  }
+
+  public CamundaProcessTestExtension withJsonMapper(
+      final io.camunda.zeebe.client.api.JsonMapper jsonMapper) {
+
+    this.zeebeJsonMapper = jsonMapper;
+    return this;
+  }
```
Comment (saig0) [inline testing/camunda-process-test-java/src/main/java/io/camunda/process/test/api/CamundaProcessTestExtension.java]: :wrench: We should annotate the method with `@Deprecated` because `io.camunda.zeebe.client.api.JsonMapper` is deprecated.

File: testing/camunda-process-test-java/src/main/java/io/camunda/process/test/api/CamundaAssert.java [hunk 3]
```diff
@@ -134,6 +142,22 @@ public static void setAwaitBehavior(final CamundaAssertAwaitBehavior awaitBehavi
...
+   * other environments, you can use `CamundaProcessTestExension::withJsonMapper` to specify the
+   * jsonMapper to be used both here and in the injected CamundaClient.
+   *
+   * @param jsonMapper the unified json mapper containing either the JsonMapper or zeebe's
+   *     JsonMapper.
+   * @see #DEFAULT_JSON_MAPPER
+   */
+  public static void setJsonMapper(final UnifiedJsonMapper jsonMapper) {
+    unifiedJsonMapper = jsonMapper;
+  }
```
Comment (saig0) [inline testing/camunda-process-test-java/src/main/java/io/camunda/process/test/api/CamundaAssert.java]: :wrench: We could simplify the public API by using only the `io.camunda.client.api.JsonMapper` interface for the public setter to avoid exposing the new JSON mapper class.

File: testing/camunda-process-test-java/src/main/java/io/camunda/process/test/api/CamundaProcessTestExtension.java (hunk 2 above)
Comment (saig0) [reply testing/camunda-process-test-java/src/main/java/io/camunda/process/test/api/CamundaProcessTestExtension.java]: :wrench: We should add JavaDoc.

**Review by saig0 — COMMENTED** [review]
@Christian-Broomfield looks good. I like the integration in Spring and the JUnit extension. :+1: 

I will commit some minor improvements to address my comments.

**Review by saig0 — APPROVED** [review]
