### PR TITLE
Ensure safe concurrent access to snapshot store

### LINKED ISSUE #6255: Concurrent access to snapshotstore causes partial snapshots to get committed
https://github.com/zeebe-io/zeebe/issues/3670#issuecomment-773238863_

Broker-1 initiates taking snapshot. Takes the snapshot in the pending directory and waits for the follow up event to be committed.
```
2021-01-14 02:52:52.877 [Broker-1-SnapshotDirector-3] [Broker-1-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 21488378670 is committed, current commit position is 21488376579. After that snapshot can be marked as valid.
```

Raft transition to follower. On transitioning to follower it deletes all pending snapshots. It also deletes the latest pending snapshot for which the SnapshotDirector is waiting to commit.  But it fails to delete it completely. It is probably due to concurrent operation by the SnapshotDirector, but it is not clear from the logs. So we have a snapshot in pending which is partially deleted.
```
at io.atomix.raft.roles.PassiveRole.abortPendingSnapshots(PassiveRole.java:418) ~[atomix-cluster-0.25.2.jar:0.25.2]
at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore.purgePendingSnapshots(FileBasedSnapshotStore.java:112) ~[zeebe-snapshots-0.25.2.jar:0.25.2]
java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/3/pending/10926499-195-1610591887661-21488376573-21488376579.tmp/229345.sst
2021-01-14 02:52:52.878 [] [raft-server-1-raft-partition-partition-3] ERROR io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore - Failed to delete not completed (orphaned) snapshot /usr/local/zeebe/data/raft-partition/partitions/3/pending/10926499-195-1610591887661-21488376573-21488376579.tmp
2021-01-14 02:53:00.272 [] [raft-server-2-raft-partition-partition-3] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-3}{role=FOLLOWER} - Poll request to 0 failed: java.util.concurrent.TimeoutException: Request type raft-partition-partition-3-poll timed out in 5000 milliseconds
```

Leader services are still running because transition on raft and zeebe services are asynchronous. (The following error is expected during a failover, and we handle this.)
```
java.lang.IllegalStateException: Unexpected position 21488378687 was encountered after position 21488378677 when appending positions <21488378687, 21488378688>.
2021-01-14 02:53:46.001 [] [raft-server-1-raft-partition-partition-3] ERROR io.zeebe.logstreams - Failed to append block with last event position 21488378688.
```

At some point the follow up event is committed. The SnapshotDirector tries to commit the snapshot. But the snapshot in pending directory is partially deleted. 
```
2021-01-14 03:02:10.879 [Broker-1-SnapshotDirector-3] [Broker-1-zb-fs-workers-1] INFO  io.zeebe.logstreams.snapshot - Current commit position 21488378670 is greater than 21488378670, snapshot 10926499-195-1610591887661-21488376573-21488376579 is valid and has been persisted.
```
As a result the committed snapshot is broken. 

Root cause:
Concurrent access to snapshots does not work correctly. When the pending snapshot is being deleted by the follower role in raft, SnapshotDirectory is trying to commit the same snapshot which is now partially deleted. 
Concurrent access to snapshot happened because role transitions in raft is asynchronous with role transition in zeebe. As a result when raft is running follower operation, zeebe may be still running leader services.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

- Make FileBasedSnapshotStore an actor
- Creating, persisting and deleting a snapshot always goes through the actor. So there are no concurrent modifications to the snapshots. Reading snapshot chunks is still outside of the actor.
- RaftContext keeps track of the current snapshot in a local member which is updated via snapshot listeners. This would prevent repeated async access to the snapshot store actor.

## Related issues

closes #6255 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.
* [ ] The changes are backwards compatibility with previous versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java [hunk 1]
```diff
@@ -134,21 +141,21 @@ public void shouldReturnFalseOnConsumingChunkTwice() throws Exception {
...
+      receivedSnapshot.apply(snapshotChunkReader.next()).join();
     }
 
     try (final var snapshotChunkReader = persistedSnapshot.newChunkReader()) {
-      final var success = receivedSnapshot.apply(snapshotChunkReader.next());
+      final var success = receivedSnapshot.apply(snapshotChunkReader.next()).join();
 
-      // then
-      assertThat(success).isFalse();
+      // then - TODO: Semantics have changed
```
Comment (MiguelPires) [inline snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java:157]: I guess you missed this when changing the tests. If this test no longer makes sense, we can remove it

File: snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java [hunk 2]
```diff
@@ -193,33 +200,33 @@ public void shouldReturnAlreadyExistingSnapshotOnPersist() throws Exception {
...
-    final var persistedReceivedSnapshot = receivedSnapshot.persist();
+    final var persistedReceivedSnapshot = receivedSnapshot.persist().join();
 
     // then
     assertThat(persistedReceivedSnapshot).isEqualTo(alreadyPeristedSnapshot);
     assertThat(persistedReceivedSnapshot == alreadyPeristedSnapshot).isTrue();
   }
 
-  @Test
+  /*@Test
```
Comment (MiguelPires) [inline snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java:229]: This test is commented out and, judging by the TransientSnapshot interface changes, should be removed

File: snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java [hunk 3]
```diff
@@ -246,9 +253,9 @@ public void shouldCheckForExistingChunk() throws Exception {
         snapshotChunkReader.next();
       }
     }
-  }
+  }*/
 
-  @Test
+  /* @Test
```
Comment (MiguelPires) [inline snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java:258]: Same as before

File: snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java [hunk 4]
```diff
@@ -277,9 +284,9 @@ public void shouldNotExistChunkWithDifferentReceivingSnapshot() throws Exception
...
```
Comment (MiguelPires) [inline snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java:289]: Same as before

File: snapshot/src/test/java/io/zeebe/snapshots/broker/impl/TransientSnapshotTest.java [hunk 5]
```diff
@@ -142,29 +149,30 @@ public void shouldReturnFalseOnExceptionInTake() {
...
-    final var time = WallClockTimestamp.from(123);
     final var transientSnapshot =
         persistedSnapshotStore.newTransientSnapshot(index, term, 1, 0).get();
-    transientSnapshot.take(p -> true);
+    transientSnapshot.take(p -> true).join();
 
     // when - then
-    assertThatThrownBy(transientSnapshot::persist).hasCauseInstanceOf(NoSuchFileException.class);
+    assertThatThrownBy(() -> transientSnapshot.persist().join()).isNotNull();
+    // .hasCauseInstanceOf(NoSuchFileException.class);
```
Comment (MiguelPires) [inline snapshot/src/test/java/io/zeebe/snapshots/broker/impl/TransientSnapshotTest.java:168]: If we can't check the underlying exception, we can at least remove this

File: snapshot/src/test/java/io/zeebe/snapshots/broker/impl/TransientSnapshotTest.java [hunk 6]
```diff
@@ -142,29 +149,30 @@ public void shouldReturnFalseOnExceptionInTake() {
...
 
     // then
-    assertThat(success).isFalse();
+    assertThatThrownBy(success::join)
+        .hasCauseInstanceOf(RuntimeException.class)
+        .hasMessageContaining("EXPECTED");
   }
 
   @Test
   public void shouldFailToPersistWhenTakeDoesntWrote() {
```
Comment (MiguelPires) [inline snapshot/src/test/java/io/zeebe/snapshots/broker/impl/TransientSnapshotTest.java:158]:
```suggestion
  public void shouldFailToPersistWhenTakeDoesntWrite() {
```

**Review by miguelpires — CHANGES_REQUESTED** [review]

File: snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java [hunk 7]
```diff
@@ -49,24 +56,34 @@
...
     receivingSnapshotStartCount = new AtomicLong();
 
     listeners = new CopyOnWriteArraySet<>();
 
     // load previous snapshots
     currentPersistedSnapshotRef = new AtomicReference<>(loadLatestSnapshot(snapshotsDirectory));
+    purgePendingSnapshotsDirectoryOnStartup();
+  }
+
+  public void open() {
```
[the remark this answers is not in the document]
Comment (deepthidevaki) [reply snapshot/src/main/java/io/zeebe/snapshots/broker/impl/FileBasedSnapshotStore.java:85]: :+1:

File: snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java (hunk 2 above)
Comment (deepthidevaki) [reply snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java:229]: :see_no_evil:

File: snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java (hunk 1 above)
Comment (deepthidevaki) [reply snapshot/src/test/java/io/zeebe/snapshots/broker/impl/ReceivedSnapshotTest.java:157]: Oops. Yes. I think it make sense to keep the test, but test that success == true.

**Comment by deepthidevaki** [comment]
@MiguelPires I have applied your comments. Plus also fixed some flaky tests because the tests were not calling join on the future.

File: atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java [hunk 8]
```diff
@@ -348,7 +347,16 @@ private void addSnapshotListener() {
                 .build()));
   }
 
+  private void setNextExpected(final ByteBuffer nextChunkId) {
+    nextPendingSnapshotChunkId = nextChunkId;
+  }
```
Comment (MiguelPires) [inline atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:352]: Why have this setter? It's a single line and it's only called in one place. In line 359 we're also setting the variable directly

**Review by miguelpires — CHANGES_REQUESTED** [review]
Just a couple of very small nits. Looks good otherwise.

**Review by miguelpires — APPROVED** [review]
