### PR TITLE
Fix flaky BrokerReprocessingTest.should​ContinueWorkflowInstanceAtSeco​ndTaskAfterRestart 

### LINKED ISSUE #6317: BrokerReprocessingTest.should​ContinueWorkflowInstanceAtSeco​ndTaskAfterRestart is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
  - Once on develope and once on BORS
- Does it block your work?
  - Yes
- Do we suspect that it is a real failure?
  - Not sure

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
io.zeebe.broker.it.startup.BrokerReprocessingTest.shouldContinueWorkflowInstanceAtSecondTaskAfterRestart[1: restart-without-snapshot]  Time elapsed: 18.163 s  <<< FAILURE!

[2021-02-11T09:12:25.745Z] java.lang.AssertionError: 

[2021-02-11T09:12:25.745Z] 

[2021-02-11T09:12:25.745Z] Expecting actual not to be null

[2021-02-11T09:12:25.746Z] 	at io.zeebe.broker.it.util.ZeebeAssertHelper.assertJobCompleted(ZeebeAssertHelper.java:137)

[2021-02-11T09:12:25.746Z] 	at io.zeebe.broker.it.util.ZeebeAssertHelper.assertJobCompleted(ZeebeAssertHelper.java:125)

[2021-02-11T09:12:25.746Z] 	at io.zeebe.broker.it.startup.BrokerReprocessingTest.shouldContinueWorkflowInstanceAtSecondTaskAfterRestart(BrokerReprocessingTest.java:276)

[2021-02-11T09:12:25.746Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2021-02-11T09:12:25.746Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2021-02-11T09:12:25.746Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-02-11T09:12:25.746Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

[2021-02-11T09:12:25.746Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

[2021-02-11T09:12:25.746Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

[2021-02-11T09:12:25.746Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

[2021-02-11T09:12:25.746Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

[2021-02-11T09:12:25.746Z] 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)

[2021-02-11T09:12:25.746Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2021-02-11T09:12:25.746Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)

[2021-02-11T09:12:25.746Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2021-02-11T09:12:25.746Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

[2021-02-11T09:12:25.746Z] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)

[2021-02-11T09:12:25.746Z] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)

[2021-02-11T09:12:25.746Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[2021-02-11T09:12:25.746Z] 	at java.base/java.lang.Thread.run(Thread.java:834)
Paste the failure here
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
09:09:28.298 [] [main] INFO  io.zeebe.test - Test finished: shouldAssignUniqueDeploymentKeyAfterRestart[1: restart-without-snapshot](io.zeebe.broker.it.startup.BrokerReprocessingTest)
09:09:28.298 [] [main] INFO  io.zeebe.test - Test started: shouldContinueWorkflowInstanceAtSecondTaskAfterRestart[1: restart-without-snapshot](io.zeebe.broker.it.startup.BrokerReprocessingTest)
09:09:28.303 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7144 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=220}
09:09:28.303 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7145 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=221}
09:09:28.303 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7146 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=222}
09:09:28.303 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7147 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=223}
09:09:28.303 [] [Time-limited test] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 7148 for test fork 1 with range PortRange{host='localhost', basePort=7125, maxOffset=100, currentOffset=224}
09:09:28.303 [] [Time-limited test] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/d61c3a23-1678-475c-9d58-a128f3b22402
09:09:28.304 [] [Time-limited test] INFO  io.zeebe.broker.system - Version: 1.0.0-SNAPSHOT
09:09:28.305 [] [Time-limited test] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 7146,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7146,
      "address" : "0.0.0.0:7146",
      "advertisedAddress" : "0.0.0.0:7146"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 7147,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7147,
      "address" : "0.0.0.0:7147",
      "advertisedAddress" : "0.0.0.0:7147"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 7148,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7148,
      "address" : "0.0.0.0:7148",
      "advertisedAddress" : "0.0.0.0:7148"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 1,
    "clusterSize" : 1,
    "clusterName" : "zeebe-cluster",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : null,
    "directory" : "/tmp/d61c3a23-1678-475c-9d58-a128f3b22402/data",
    "logSegmentSize" : "128MB",
    "snapshotPeriod" : "PT5M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.99,
    "diskUsageCommandWatermark" : 0.97,
    "diskUsageMonitoringInterval" : "PT1S",
    "logSegmentSizeInBytes" : 134217728,
    "atomixStorageLevel" : "MAPPED",
    "freeDiskSpaceCommandWatermark" : 0,
    "freeDiskSpaceReplicationWatermark" : 0
  },
  "exporters" : {
    "test-recorder" : {
      "jarPath" : null,
      "className" : "io.zeebe.test.util.record.RecordingExporter",
      "args" : null,
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 7144,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:7147",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 7145,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT0.1S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      }
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "initialized" : true,
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "0MB",
    "disableExplicitRaftFlush" : false,
    "detectReprocessingInconsistency" : false,
    "rocksdb" : {
      "columnFamilyOptions" : { },
      "statisticsEnabled" : false,
      "memoryLimit" : "512MB",
      "maxOpenFiles" : -1
    },
    "maxAppendBatchSizeInBytes" : 32768
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
09:09:28.305 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/14]: actor scheduler
09:09:28.306 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/14]: actor scheduler started in 1 ms
09:09:28.306 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/14]: membership and replication protocol
09:09:28.308 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/14]: membership and replication protocol started in 2 ms
09:09:28.308 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/14]: command api transport
09:09:28.310 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:7146
09:09:28.310 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
09:09:28.311 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bound command API to [0.0.0.0:7146], using advertised address 0.0.0.0:7146 
09:09:28.311 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/14]: command api transport started in 3 ms
09:09:28.311 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/14]: command api handler
09:09:28.311 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/14]: command api handler started in 0 ms
09:09:28.311 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/14]: subscription api
09:09:28.311 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/14]: subscription api started in 0 ms
09:09:28.311 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services
09:09:28.311 [] [Time-limited test] INFO  io.atomix.core.Atomix - 1.0.0-SNAPSHOT (revision 474259 built on 2021-02-11 08:54:57)
09:09:28.313 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:7147
09:09:28.313 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
09:09:28.314 [] [netty-unicast-event-nio-client-0] INFO  io.atomix.cluster.messaging.impl.NettyUnicastService - UDP server listening for connections on 0.0.0.0:7147
09:09:28.315 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
09:09:28.315 [] [atomix-cluster-0] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - Nodes from discovery service []
09:09:28.315 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
09:09:28.315 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
09:09:28.315 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started
09:09:28.316 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
09:09:28.316 [] [atomix-0] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-1} - Starting server for partition PartitionId{id=1, group=raft-partition}
09:09:28.322 [] [atomix-0] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=1, version=1, index=1}
09:09:28.325 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
09:09:28.325 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Single member cluster. Transitioning directly to candidate.
09:09:28.325 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE
09:09:28.325 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.raft.roles.FollowerRole$$Lambda$712/0x0000000840673840@383095b not registered
09:09:28.325 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Single member cluster. Transitioning directly to leader.
09:09:28.329 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Set term 1
09:09:28.331 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Voted for 0
09:09:28.331 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to LEADER
09:09:28.332 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 0
09:09:28.334 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 1. RaftServer is ready only after it has committed events upto this index
09:09:28.334 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server join completed. Waiting for the server to be READY
09:09:28.334 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server started successfully!
09:09:28.334 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-1} - Successfully started server for partition PartitionId{id=1, group=raft-partition} in 18ms
09:09:28.334 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
09:09:28.334 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.primitive.partition.impl.DefaultPartitionService - Started class io.atomix.primitive.partition.impl.DefaultPartitionService
09:09:28.335 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services started in 24 ms
09:09:28.335 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/14]: topology manager
09:09:28.335 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/14]: topology manager started in 0 ms
09:09:28.335 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/14]: embedded gateway
09:09:28.335 [] [Time-limited test] INFO  io.zeebe.gateway - Version: 1.0.0-SNAPSHOT
09:09:28.335 [] [Time-limited test] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 7144,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "0.0.0.0:7147",
    "requestTimeout" : "PT15S",
    "clusterName" : "zeebe-cluster",
    "memberId" : "gateway",
    "host" : "0.0.0.0",
    "port" : 7145,
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "0.0.0.0",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  },
  "longPolling" : {
    "enabled" : true
  },
  "initialized" : true,
  "enable" : true
}
09:09:28.335 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Received new broker BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=1, replicationFactor=1, partitionRoles={}, partitionLeaderTerms={}, partitionHealthStatuses={}, version=1.0.0-SNAPSHOT}.
09:09:28.337 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/14]: embedded gateway started in 2 ms
09:09:28.337 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/14]: monitoring services
09:09:28.337 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [9/14]: monitoring services started in 0 ms
09:09:28.337 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/14]: disk space monitor
09:09:28.337 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/14]: disk space monitor started in 0 ms
09:09:28.337 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [11/14]: leader management request handler
09:09:28.337 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [11/14]: leader management request handler started in 0 ms
09:09:28.337 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [12/14]: zeebe partitions
09:09:28.337 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
09:09:28.338 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER
09:09:28.338 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition 1 closed all previous open resources, before transitioning.
09:09:28.338 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {logstream-raft-partition-partition-1=HEALTHY}
09:09:28.408 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/d61c3a23-1678-475c-9d58-a128f3b22402/data/raft-partition/partitions/1/runtime'.
09:09:28.473 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
09:09:28.473 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
09:09:28.474 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@1011f640)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@ac2a2c7, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@46213a78, configuration: Configuration(false)]
09:09:28.475 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
09:09:28.475 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@1ee3338e)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@1a86e0f, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@4e9566b8, configuration: Configuration(false)]
09:09:28.475 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@3480ee17)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@3378d44a, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@71e20c3c, configuration: Configuration(false)]
09:09:28.477 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
09:09:28.477 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition 1 transition complete, installed 11 resources!
09:09:28.477 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
09:09:28.477 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 140 ms
09:09:28.477 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovered exporter 'Broker-0-Exporter-1' from snapshot at lastExportedPosition -1
09:09:28.477 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 140 ms.
09:09:28.477 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'test-recorder'
09:09:28.477 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [12/14]: zeebe partitions started in 140 ms
09:09:28.477 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [13/14]: register diskspace usage listeners
09:09:28.477 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {Partition-1=HEALTHY}
09:09:28.477 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] INFO  io.zeebe.broker.system - Partition-1 recovered, marking it as healthy
09:09:28.477 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [13/14]: register diskspace usage listeners started in 0 ms
09:09:28.477 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [14/14]: upgrade manager
09:09:28.477 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [14/14]: upgrade manager started in 0 ms
09:09:28.477 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 14 steps in 172 ms.
09:09:28.477 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={COMMAND=true, COMMAND_REJECTION=true, NULL_VAL=true, SBE_UNKNOWN=true, EVENT=true}, acceptValueTypes={WORKFLOW_INSTANCE=true, VARIABLE=true, MESSAGE=true, INCIDENT=true, WORKFLOW=true, DEPLOYMENT=true, WORKFLOW_INSTANCE_CREATION=true, ERROR=true, JOB_BATCH=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, JOB=true, NULL_VAL=true, WORKFLOW_INSTANCE_RESULT=true, SBE_UNKNOWN=true, WORKFLOW_INSTANCE_SUBSCRIPTION=true, MESSAGE_SUBSCRIPTION=true, TIMER=true, VARIABLE_DOCUMENT=true}}
09:09:28.477 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Open exporter with id 'test-recorder'
09:09:28.565 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MTQ2BQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}
09:09:28.566 [GatewayTopologyManager] [Broker-0-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER}, terms {1=1} and health {1=HEALTHY}.
09:09:28.577 [] [Time-limited test] INFO  io.zeebe.broker.test - 
====
Broker startup time: 275
====
09:09:28.579 [] [Time-limited test] INFO  io.zeebe.broker.test - 
====
Client startup time: 2
====
09:09:28.597 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@585841ca)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@38c63b04, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@60444e67, configuration: Configuration(false)]
09:09:28.730 [] [grpc-default-executor-3] INFO  io.zeebe.client.job.poller - Activated 1 jobs for worker default and job type foo
09:09:28.750 [] [grpc-default-executor-3] INFO  io.zeebe.client.job.poller - Activated 1 jobs for worker default and job type bar
09:09:28.751 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [1/14]: upgrade manager
09:09:28.751 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [1/14]: upgrade manager closed in 0 ms
09:09:28.751 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [2/14]: register diskspace usage listeners
09:09:28.751 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [2/14]: register diskspace usage listeners closed in 0 ms
09:09:28.751 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [3/14]: zeebe partitions
09:09:28.751 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe Partition 1.
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] ERROR io.zeebe.broker.system - ZeebePartition-1 failed, marking it as unhealthy
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {ZeebePartition-1=UNHEALTHY, Raft-1=HEALTHY, Broker-0-StreamProcessor-1=HEALTHY, logstream-raft-partition-partition-1=HEALTHY}
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ExporterDirector
09:09:28.751 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] ERROR io.zeebe.broker.system - Partition-1 failed, marking it as unhealthy
09:09:28.751 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {Partition-1=UNHEALTHY}
09:09:28.751 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Closed exporter director 'Broker-0-Exporter-1'.
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ExporterDirector closed successfully
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RocksDB metric timer
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RocksDB metric timer closed successfully
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AsyncSnapshotDirector
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AsyncSnapshotDirector closed successfully
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StreamProcessor
09:09:28.751 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StreamProcessor closed successfully
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ZeebeDb
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ZeebeDb closed successfully
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RegisterSnapshotListener
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RegisterSnapshotListener closed successfully
09:09:28.751 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: LogDeletionService
09:09:28.752 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: LogDeletionService closed successfully
09:09:28.752 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StateController
09:09:28.782 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/d61c3a23-1678-475c-9d58-a128f3b22402/data/raft-partition/partitions/1/runtime'.
09:09:28.782 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StateController closed successfully
09:09:28.782 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: SnapshotReplication
09:09:28.782 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: SnapshotReplication closed successfully
09:09:28.783 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RaftLogReader
09:09:28.783 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RaftLogReader closed successfully
09:09:28.783 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: logstream
09:09:28.783 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Close appender for log stream logstream-raft-partition-partition-1
09:09:28.783 [logstream-raft-partition-partition-1-write-buffer] [Broker-0-zb-actors-1] DEBUG io.zeebe.dispatcher - Dispatcher closed
09:09:28.783 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-1 close 3 readers
09:09:28.783 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Close log storage with name logstream-raft-partition-partition-1
09:09:28.783 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: logstream closed successfully
09:09:28.783 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition 1 closed all previous open resources, before transitioning.
09:09:28.783 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition 1 transition complete, installed 0 resources!
09:09:28.783 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1 closed in 32 ms
09:09:28.783 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 partitions succeeded. Closed 1 steps in 32 ms.
09:09:28.783 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [3/14]: zeebe partitions closed in 32 ms
09:09:28.783 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [4/14]: leader management request handler
09:09:28.783 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [4/14]: leader management request handler closed in 0 ms
09:09:28.783 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [5/14]: disk space monitor
09:09:28.783 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [5/14]: disk space monitor closed in 0 ms
09:09:28.783 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [6/14]: monitoring services
09:09:28.783 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [6/14]: monitoring services closed in 0 ms
09:09:28.783 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [7/14]: embedded gateway
09:09:28.785 [] [Time-limited test] DEBUG io.zeebe.gateway - Closing gateway broker client ...
09:09:28.785 [] [Time-limited test] DEBUG io.zeebe.gateway - topology manager closed
09:09:28.786 [] [Time-limited test] DEBUG io.zeebe.gateway - Gateway broker client closed.
09:09:28.786 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [7/14]: embedded gateway closed in 3 ms
09:09:28.786 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [8/14]: topology manager
09:09:28.785 [] [grpc-default-executor-4] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type foo
io.grpc.StatusRuntimeException: CANCELLED: RST_STREAM closed stream. HTTP/2 error code: CANCEL
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
09:09:28.786 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [8/14]: topology manager closed in 0 ms
09:09:28.786 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [9/14]: cluster services
09:09:28.786 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [9/14]: cluster services closed in 0 ms
09:09:28.786 [] [grpc-default-executor-4] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to CANCELLED: RST_STREAM closed stream. HTTP/2 error code: CANCEL, delay retry for 145 ms
09:09:28.786 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [10/14]: subscription api
09:09:28.786 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [10/14]: subscription api closed in 0 ms
09:09:28.786 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [11/14]: command api handler
09:09:28.786 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [11/14]: command api handler closed in 0 ms
09:09:28.786 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [12/14]: command api transport
09:09:28.791 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [Broker-0-zb-actors-0] WARN  io.zeebe.gateway - Failed to activate jobs for type bar from partition 1
java.net.ConnectException: null
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.close(AbstractClientConnection.java:123) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$getOrCreateClientConnection$31(NettyMessagingService.java:510) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1174) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:761) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:737) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:608) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.shutdownInput(AbstractEpollChannel.java:485) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:818) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
09:09:28.816 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MTQ2BQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}
09:09:28.933 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type foo
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:28.933 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 246 ms
09:09:29.180 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type foo
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:29.180 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 431 ms
09:09:29.612 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type foo
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:29.612 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 627 ms
09:09:30.240 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type foo
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:30.240 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 948 ms
09:09:30.796 [] [ForkJoinPool.commonPool-worker-27] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
09:09:30.796 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [12/14]: command api transport closed in 2010 ms
09:09:30.796 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [13/14]: membership and replication protocol
09:09:30.796 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
09:09:30.797 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.zeebe.LogCompactor - LogCompactor{raft-partition-partition-1} - Closing the log compactor raft-partition-partition-1
09:09:30.797 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Closing segment: JournalSegment{id=1, version=1, index=1}
09:09:30.798 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
09:09:30.798 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.primitive.partition.impl.DefaultPartitionService - Stopped
09:09:30.798 [] [atomix-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Stopped
09:09:30.798 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Stopped
09:09:30.798 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Member deactivated: Member{id=0, address=0.0.0.0:7147, properties={brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MTQ2BQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}
09:09:30.798 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Stopped
09:09:30.798 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Left
09:09:30.798 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Stopped
09:09:31.188 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type foo
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:31.189 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 1396 ms
09:09:32.585 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type foo
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:32.586 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 2394 ms
09:09:34.815 [] [ForkJoinPool.commonPool-worker-27] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
09:09:34.815 [] [atomix-cluster-0] INFO  io.atomix.cluster.AtomixCluster - Stopped
09:09:34.815 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [13/14]: membership and replication protocol closed in 4019 ms
09:09:34.815 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [14/14]: actor scheduler
09:09:34.815 [] [Time-limited test] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers'
09:09:34.815 [] [Time-limited test] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors'
09:09:34.816 [] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers': closed successfully
09:09:34.816 [] [Broker-0-zb-actors-0] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors': closed successfully
09:09:34.816 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [14/14]: actor scheduler closed in 1 ms
09:09:34.817 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 14 steps in 6066 ms.
09:09:34.817 [] [Time-limited test] INFO  io.zeebe.broker.system - Broker shut down.
09:09:34.901 [] [Time-limited test] DEBUG io.zeebe.broker.system - Initializing system with base path /tmp/d61c3a23-1678-475c-9d58-a128f3b22402
09:09:34.902 [] [Time-limited test] INFO  io.zeebe.broker.system - Version: 1.0.0-SNAPSHOT
09:09:34.902 [] [Time-limited test] INFO  io.zeebe.broker.system - Starting broker 0 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "0.0.0.0",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 7146,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7146,
      "address" : "0.0.0.0:7146",
      "advertisedAddress" : "0.0.0.0:7146"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 7147,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7147,
      "address" : "0.0.0.0:7147",
      "advertisedAddress" : "0.0.0.0:7147"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 7148,
      "advertisedHost" : "0.0.0.0",
      "advertisedPort" : 7148,
      "address" : "0.0.0.0:7148",
      "advertisedAddress" : "0.0.0.0:7148"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ ],
    "partitionIds" : [ 1 ],
    "nodeId" : 0,
    "partitionsCount" : 1,
    "replicationFactor" : 1,
    "clusterSize" : 1,
    "clusterName" : "zeebe-cluster",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directories" : null,
    "directory" : "/tmp/d61c3a23-1678-475c-9d58-a128f3b22402/data",
    "logSegmentSize" : "128MB",
    "snapshotPeriod" : "PT5M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.99,
    "diskUsageCommandWatermark" : 0.97,
    "diskUsageMonitoringInterval" : "PT1S",
    "logSegmentSizeInBytes" : 134217728,
    "atomixStorageLevel" : "MAPPED",
    "freeDiskSpaceCommandWatermark" : 3037238723,
    "freeDiskSpaceReplicationWatermark" : 1012412908
  },
  "exporters" : {
    "test-recorder" : {
      "jarPath" : null,
      "className" : "io.zeebe.test.util.record.RecordingExporter",
      "args" : null,
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 7144,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:7147",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 7145,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT0.1S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      }
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "initialized" : true,
    "enable" : true
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "0MB",
    "disableExplicitRaftFlush" : false,
    "detectReprocessingInconsistency" : false,
    "rocksdb" : {
      "columnFamilyOptions" : { },
      "statisticsEnabled" : false,
      "memoryLimit" : "512MB",
      "maxOpenFiles" : -1
    },
    "maxAppendBatchSizeInBytes" : 32768
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
09:09:34.903 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/14]: actor scheduler
09:09:34.904 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/14]: actor scheduler started in 0 ms
09:09:34.904 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/14]: membership and replication protocol
09:09:34.906 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/14]: membership and replication protocol started in 2 ms
09:09:34.906 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/14]: command api transport
09:09:34.908 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:7146
09:09:34.909 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
09:09:34.909 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bound command API to [0.0.0.0:7146], using advertised address 0.0.0.0:7146 
09:09:34.909 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/14]: command api transport started in 3 ms
09:09:34.909 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/14]: command api handler
09:09:34.909 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/14]: command api handler started in 0 ms
09:09:34.909 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/14]: subscription api
09:09:34.909 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/14]: subscription api started in 0 ms
09:09:34.909 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services
09:09:34.909 [] [Time-limited test] INFO  io.atomix.core.Atomix - 1.0.0-SNAPSHOT (revision 474259 built on 2021-02-11 08:54:57)
09:09:34.911 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 0.0.0.0:7147
09:09:34.911 [] [netty-messaging-event-epoll-server-0] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Started
09:09:34.913 [] [netty-unicast-event-nio-client-0] INFO  io.atomix.cluster.messaging.impl.NettyUnicastService - UDP server listening for connections on 0.0.0.0:7147
09:09:34.913 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
09:09:34.914 [] [atomix-cluster-0] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - Nodes from discovery service []
09:09:34.914 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Started
09:09:34.914 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
09:09:34.914 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started
09:09:34.914 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started
09:09:34.915 [] [atomix-0] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-1} - Starting server for partition PartitionId{id=1, group=raft-partition}
09:09:34.916 [] [atomix-0] DEBUG io.atomix.storage.journal.SegmentedJournal - Loaded disk segment: 1 (raft-partition-partition-1-1.log)
09:09:34.916 [] [atomix-0] DEBUG io.atomix.storage.journal.SegmentedJournal - Found segment: 1 (raft-partition-partition-1-1.log)
09:09:34.917 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
09:09:34.917 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Single member cluster. Transitioning directly to candidate.
09:09:34.917 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE
09:09:34.917 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.raft.roles.FollowerRole$$Lambda$712/0x0000000840673840@32ac756b not registered
09:09:34.917 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Single member cluster. Transitioning directly to leader.
09:09:34.923 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Set term 2
09:09:34.925 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Voted for 0
09:09:34.925 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to LEADER
09:09:34.926 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 0
09:09:34.927 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 35. RaftServer is ready only after it has committed events upto this index
09:09:34.927 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server join completed. Waiting for the server to be READY
09:09:34.928 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.DefaultRaftServer - RaftServer{raft-partition-partition-1} - Server started successfully!
09:09:34.928 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.impl.RaftPartitionServer - RaftPartitionServer{raft-partition-partition-1} - Successfully started server for partition PartitionId{id=1, group=raft-partition} in 13ms
09:09:34.928 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.RaftPartitionGroup - Started
09:09:34.928 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.primitive.partition.impl.DefaultPartitionService - Started class io.atomix.primitive.partition.impl.DefaultPartitionService
09:09:34.928 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services started in 19 ms
09:09:34.928 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/14]: topology manager
09:09:34.928 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/14]: topology manager started in 0 ms
09:09:34.928 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/14]: embedded gateway
09:09:34.928 [] [Time-limited test] INFO  io.zeebe.gateway - Version: 1.0.0-SNAPSHOT
09:09:34.928 [] [Time-limited test] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 7144,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "0.0.0.0:7147",
    "requestTimeout" : "PT15S",
    "clusterName" : "zeebe-cluster",
    "memberId" : "gateway",
    "host" : "0.0.0.0",
    "port" : 7145,
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "0.0.0.0",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  },
  "longPolling" : {
    "enabled" : true
  },
  "initialized" : true,
  "enable" : true
}
09:09:34.929 [GatewayTopologyManager] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Received new broker BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=1, replicationFactor=1, partitionRoles={}, partitionLeaderTerms={}, partitionHealthStatuses={}, version=1.0.0-SNAPSHOT}.
09:09:34.930 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/14]: embedded gateway started in 2 ms
09:09:34.930 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/14]: monitoring services
09:09:34.931 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [9/14]: monitoring services started in 1 ms
09:09:34.931 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/14]: disk space monitor
09:09:34.931 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/14]: disk space monitor started in 0 ms
09:09:34.931 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [11/14]: leader management request handler
09:09:34.931 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [11/14]: leader management request handler started in 0 ms
09:09:34.931 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [12/14]: zeebe partitions
09:09:34.931 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
09:09:34.931 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER
09:09:34.931 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition 1 closed all previous open resources, before transitioning.
09:09:34.933 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {logstream-raft-partition-partition-1=HEALTHY}
09:09:34.980 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type foo
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:34.981 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 3859 ms
09:09:35.002 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/d61c3a23-1678-475c-9d58-a128f3b22402/data/raft-partition/partitions/1/runtime'.
09:09:35.068 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
09:09:35.069 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
09:09:35.069 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@1c003ecd)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@3467f40b, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@24c9ff6f, configuration: Configuration(false)]
09:09:35.070 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
09:09:35.070 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@62a3fb8a)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@696f9c79, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@2b624bc, configuration: Configuration(false)]
09:09:35.070 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@3fe4df06)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@42e60cdb, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@577fdcaa, configuration: Configuration(false)]
09:09:35.072 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.zeebe.processor - Processor starts reprocessing, until last source event position 34
09:09:35.072 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition 1 transition complete, installed 11 resources!
09:09:35.072 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
09:09:35.073 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
09:09:35.073 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {Partition-1=HEALTHY}
09:09:35.073 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 142 ms
09:09:35.073 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] INFO  io.zeebe.broker.system - Partition-1 recovered, marking it as healthy
09:09:35.073 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 142 ms.
09:09:35.073 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [12/14]: zeebe partitions started in 142 ms
09:09:35.073 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [13/14]: register diskspace usage listeners
09:09:35.073 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [13/14]: register diskspace usage listeners started in 0 ms
09:09:35.073 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [14/14]: upgrade manager
09:09:35.073 [] [Time-limited test] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [14/14]: upgrade manager started in 0 ms
09:09:35.073 [] [Time-limited test] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 14 steps in 170 ms.
09:09:35.073 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Recovered exporter 'Broker-0-Exporter-1' from snapshot at lastExportedPosition -1
09:09:35.073 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'test-recorder'
09:09:35.073 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={COMMAND=true, COMMAND_REJECTION=true, NULL_VAL=true, SBE_UNKNOWN=true, EVENT=true}, acceptValueTypes={WORKFLOW_INSTANCE=true, VARIABLE=true, MESSAGE=true, INCIDENT=true, WORKFLOW=true, DEPLOYMENT=true, WORKFLOW_INSTANCE_CREATION=true, ERROR=true, JOB_BATCH=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, JOB=true, NULL_VAL=true, WORKFLOW_INSTANCE_RESULT=true, SBE_UNKNOWN=true, WORKFLOW_INSTANCE_SUBSCRIPTION=true, MESSAGE_SUBSCRIPTION=true, TIMER=true, VARIABLE_DOCUMENT=true}}
09:09:35.073 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Open exporter with id 'test-recorder'
09:09:35.080 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@30904809)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@52a093c5, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@31c84927, configuration: Configuration(false)]
09:09:35.094 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  io.zeebe.processor - Processor finished reprocessing at event position 35
09:09:35.095 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.transport - Expected to have a rate limiter listener for request-1-7, but none found. (This can happen during fail over.)
09:09:35.164 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MTQ2BQABAQAAAAAMAAEBAAAAAgAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}
09:09:35.165 [GatewayTopologyManager] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER}, terms {1=2} and health {1=HEALTHY}.
09:09:35.178 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {ZeebePartition-1=HEALTHY, Raft-1=HEALTHY, Broker-0-StreamProcessor-1=UNHEALTHY, logstream-raft-partition-partition-1=HEALTHY}
09:09:35.178 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] ERROR io.zeebe.broker.system - Partition-1 failed, marking it as unhealthy
09:09:35.178 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {Partition-1=UNHEALTHY}
09:09:35.178 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Based on lowest exporter position '37' and last processed position '36', determined '36' as snapshot position.
09:09:35.178 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] WARN  io.zeebe.logstreams.snapshot - Failed to take snapshot. Expected to find an indexed entry for determined snapshot position 36, but found no matching indexed entry which contains this position.
09:09:35.281 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {ZeebePartition-1=HEALTHY, Raft-1=HEALTHY, Broker-0-StreamProcessor-1=HEALTHY, logstream-raft-partition-partition-1=HEALTHY}
09:09:35.281 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] INFO  io.zeebe.broker.system - Partition-1 recovered, marking it as healthy
09:09:35.281 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - The components are healthy. The current health status of components: {Partition-1=HEALTHY}
09:09:35.306 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Based on lowest exporter position '39' and last processed position '38', determined '38' as snapshot position.
09:09:35.306 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] WARN  io.zeebe.logstreams.snapshot - Failed to take snapshot. Expected to find an indexed entry for determined snapshot position 38, but found no matching indexed entry which contains this position.
09:09:35.374 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type bar
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:35.375 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 152 ms
09:09:35.527 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type bar
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:35.527 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 250 ms
09:09:35.778 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type bar
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:35.778 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 361 ms
09:09:36.140 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type bar
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:36.140 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 551 ms
09:09:36.692 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type bar
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:36.692 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 819 ms
09:09:37.512 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type bar
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:37.512 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 1327 ms
09:09:38.840 [] [grpc-default-executor-4] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type foo
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:38.840 [] [grpc-default-executor-2] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type bar
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:534) ~[grpc-api-1.35.0.jar:1.35.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.35.0.jar:1.35.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.35.0.jar:1.35.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /0.0.0.0:7144
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-transport-native-unix-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	... 1 more
09:09:38.840 [] [grpc-default-executor-4] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 5177 ms
09:09:38.840 [] [grpc-default-executor-2] DEBUG io.zeebe.client.job.worker - Failed to activate jobs due to UNAVAILABLE: io exception, delay retry for 1954 ms
09:09:40.274 [] [Time-limited test] INFO  io.zeebe.broker.test - Client Rule assumption: Test execution time: 11695
09:09:40.276 [] [Time-limited test] INFO  io.zeebe.broker.test - Client closing time: 1
09:09:40.278 [] [Time-limited test] INFO  io.zeebe.test.records - Test failed, following records were exported:
09:09:40.287 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":-1,"position":1,"timestamp":1613034568587,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04Mjg2LTNjYjljYzYzMT...
09:09:40.288 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW","key":2251799813685249,"position":2,"timestamp":1613034568606,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04Mjg2LTNjYjljYzYzMTBiN...
09:09:40.289 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":3,"timestamp":1613034568606,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04Mjg2L...
09:09:40.289 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4,"timestamp":1613034568610,"recordType":"COMMAND","intent":"DISTRIBUTE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04...
09:09:40.290 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":5,"timestamp":1613034568613,"recordType":"EVENT","intent":"DISTRIBUTED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04M...
09:09:40.291 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":-1,"position":6,"timestamp":1613034568618,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":-1,"bpmnProcessId":"process","workflowInstanceKey":-1,"variables":{},"workflowKey":0},"sourceRecordPosition":-1}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685251,"position":7,"timestamp":1613034568620,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"process","workflowInstanceKey":2251799813685251,"flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":6}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":2251799813685252,"position":8,"timestamp":1613034568620,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","workflowInstanceKey":2251799813685251,"variables":{},"workflowKey":2251799813685249},"sourceRecordPosition":6}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685251,"position":9,"timestamp":1613034568620,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"process","workflowInstanceKey":2251799813685251,"flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":7}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":10,"timestamp":1613034568622,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"start","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":9}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":11,"timestamp":1613034568623,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"start","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":10}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":12,"timestamp":1613034568628,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"start","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":11}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":13,"timestamp":1613034568629,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"start","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":12}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685254,"position":14,"timestamp":1613034568631,"recordType":"EVENT","intent":"SEQUENCE_FLOW_TAKEN","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"sequenceFlow_206bbb3c-abef-4bab-8286-3cb9cc6310b4","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SEQUENCE_FLOW","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":13}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":15,"timestamp":1613034568632,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task1","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":14}
09:09:40.293 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":16,"timestamp":1613034568635,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task1","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":15}
09:09:40.295 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":-1,"position":17,"timestamp":1613034568636,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task1","elementInstanceKey":2251799813685255,"workflowDefinitionVersion":1,"retries":3,"worker":"","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":-1,"workflowKey":2251799813685249},"sourceRecordPosition":16}
09:09:40.295 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685256,"position":18,"timestamp":1613034568637,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task1","elementInstanceKey":2251799813685255,"workflowDefinitionVersion":1,"retries":3,"worker":"","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":-1,"workflowKey":2251799813685249},"sourceRecordPosition":17}
09:09:40.297 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":-1,"position":19,"timestamp":1613034568724,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":-1}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":-1,"position":20,"timestamp":1613034568724,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":-1}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":2251799813685257,"position":21,"timestamp":1613034568728,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[2251799813685256],"jobs":[{"type":"foo","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task1","elementInstanceKey":2251799813685255,"workflowDefinitionVersion":1,"retries":3,"worker":"default","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":1613034868724,"workflowKey":2251799813685249}],"timeout":300000},"sourceRecordPosition":19}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":2251799813685258,"position":22,"timestamp":1613034568728,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":20}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685256,"position":23,"timestamp":1613034568733,"recordType":"COMMAND","intent":"COMPLETE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"","errorMessage":"","bpmnProcessId":"","customHeaders":{},"elementId":"","elementInstanceKey":-1,"workflowDefinitionVersion":-1,"retries":-1,"worker":"","workflowInstanceKey":-1,"variables":{},"errorCode":"","deadline":-1,"workflowKey":-1},"sourceRecordPosition":-1}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":-1,"position":24,"timestamp":1613034568733,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":-1}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685256,"position":25,"timestamp":1613034568734,"recordType":"EVENT","intent":"COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task1","elementInstanceKey":2251799813685255,"workflowDefinitionVersion":1,"retries":3,"worker":"default","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":1613034868724,"workflowKey":2251799813685249},"sourceRecordPosition":23}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":2251799813685259,"position":26,"timestamp":1613034568735,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":24}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":27,"timestamp":1613034568735,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task1","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":25}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":28,"timestamp":1613034568740,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task1","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":27}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685260,"position":29,"timestamp":1613034568741,"recordType":"EVENT","intent":"SEQUENCE_FLOW_TAKEN","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"sequenceFlow_df343b84-5a99-4695-b216-454377a5a8b4","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SEQUENCE_FLOW","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":28}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685261,"position":30,"timestamp":1613034568743,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task2","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":29}
09:09:40.298 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685261,"position":31,"timestamp":1613034568744,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task2","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":30}
09:09:40.299 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":-1,"position":32,"timestamp":1613034568745,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task2","elementInstanceKey":2251799813685261,"workflowDefinitionVersion":1,"retries":3,"worker":"","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":-1,"workflowKey":2251799813685249},"sourceRecordPosition":31}
09:09:40.299 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685262,"position":33,"timestamp":1613034568746,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task2","elementInstanceKey":2251799813685261,"workflowDefinitionVersion":1,"retries":3,"worker":"","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":-1,"workflowKey":2251799813685249},"sourceRecordPosition":32}
09:09:40.299 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":-1,"position":34,"timestamp":1613034568747,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":-1}
09:09:40.299 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":2251799813685263,"position":35,"timestamp":1613034568749,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[2251799813685262],"jobs":[{"type":"bar","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task2","elementInstanceKey":2251799813685261,"workflowDefinitionVersion":1,"retries":3,"worker":"default","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":1613034868747,"workflowKey":2251799813685249}],"timeout":300000},"sourceRecordPosition":34}
09:09:40.299 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":-1,"position":1,"timestamp":1613034568587,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04Mjg2LTNjYjljYzYzMT...
09:09:40.299 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW","key":2251799813685249,"position":2,"timestamp":1613034568606,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04Mjg2LTNjYjljYzYzMTBiN...
09:09:40.300 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":3,"timestamp":1613034568606,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04Mjg2L...
09:09:40.300 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":4,"timestamp":1613034568610,"recordType":"COMMAND","intent":"DISTRIBUTE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04...
09:09:40.300 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"DEPLOYMENT","key":2251799813685250,"position":5,"timestamp":1613034568613,"recordType":"EVENT","intent":"DISTRIBUTED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"resources":[{"resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiB4bWxuczpuczA9Imh0dHA6Ly9jYW11bmRhLm9yZy9zY2hlbWEvemVlYmUvMS4wIiBpZD0iZGVmaW5pdGlvbnNfNmZiNmE5MTQtNGY4NS00YzVkLWFjYjAtZWQ0MTRlNDU0YzAzIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydCIgbmFtZT0ic3RhcnQiPgogICAgICA8b3V0Z29pbmc+c2VxdWVuY2VGbG93XzIwNmJiYjNjLWFiZWYtNGJhYi04M...
09:09:40.300 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":-1,"position":6,"timestamp":1613034568618,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":-1,"bpmnProcessId":"process","workflowInstanceKey":-1,"variables":{},"workflowKey":0},"sourceRecordPosition":-1}
09:09:40.300 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685251,"position":7,"timestamp":1613034568620,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"process","workflowInstanceKey":2251799813685251,"flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":6}
09:09:40.300 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE_CREATION","key":2251799813685252,"position":8,"timestamp":1613034568620,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","workflowInstanceKey":2251799813685251,"variables":{},"workflowKey":2251799813685249},"sourceRecordPosition":6}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685251,"position":9,"timestamp":1613034568620,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"process","workflowInstanceKey":2251799813685251,"flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":7}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":10,"timestamp":1613034568622,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"start","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":9}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":11,"timestamp":1613034568623,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"start","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":10}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":12,"timestamp":1613034568628,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"start","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":11}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685253,"position":13,"timestamp":1613034568629,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"start","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"START_EVENT","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":12}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685254,"position":14,"timestamp":1613034568631,"recordType":"EVENT","intent":"SEQUENCE_FLOW_TAKEN","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"sequenceFlow_206bbb3c-abef-4bab-8286-3cb9cc6310b4","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SEQUENCE_FLOW","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":13}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":15,"timestamp":1613034568632,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task1","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":14}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":16,"timestamp":1613034568635,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task1","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":15}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":-1,"position":17,"timestamp":1613034568636,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task1","elementInstanceKey":2251799813685255,"workflowDefinitionVersion":1,"retries":3,"worker":"","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":-1,"workflowKey":2251799813685249},"sourceRecordPosition":16}
09:09:40.302 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685256,"position":18,"timestamp":1613034568637,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task1","elementInstanceKey":2251799813685255,"workflowDefinitionVersion":1,"retries":3,"worker":"","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":-1,"workflowKey":2251799813685249},"sourceRecordPosition":17}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":-1,"position":19,"timestamp":1613034568724,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":-1}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":-1,"position":20,"timestamp":1613034568724,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":-1}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":2251799813685257,"position":21,"timestamp":1613034568728,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[2251799813685256],"jobs":[{"type":"foo","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task1","elementInstanceKey":2251799813685255,"workflowDefinitionVersion":1,"retries":3,"worker":"default","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":1613034868724,"workflowKey":2251799813685249}],"timeout":300000},"sourceRecordPosition":19}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":2251799813685258,"position":22,"timestamp":1613034568728,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":20}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685256,"position":23,"timestamp":1613034568733,"recordType":"COMMAND","intent":"COMPLETE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"","errorMessage":"","bpmnProcessId":"","customHeaders":{},"elementId":"","elementInstanceKey":-1,"workflowDefinitionVersion":-1,"retries":-1,"worker":"","workflowInstanceKey":-1,"variables":{},"errorCode":"","deadline":-1,"workflowKey":-1},"sourceRecordPosition":-1}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":-1,"position":24,"timestamp":1613034568733,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":-1}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685256,"position":25,"timestamp":1613034568734,"recordType":"EVENT","intent":"COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task1","elementInstanceKey":2251799813685255,"workflowDefinitionVersion":1,"retries":3,"worker":"default","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":1613034868724,"workflowKey":2251799813685249},"sourceRecordPosition":23}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":2251799813685259,"position":26,"timestamp":1613034568735,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"foo","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":24}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":27,"timestamp":1613034568735,"recordType":"EVENT","intent":"ELEMENT_COMPLETING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task1","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":25}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685255,"position":28,"timestamp":1613034568740,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task1","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":27}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685260,"position":29,"timestamp":1613034568741,"recordType":"EVENT","intent":"SEQUENCE_FLOW_TAKEN","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"sequenceFlow_df343b84-5a99-4695-b216-454377a5a8b4","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SEQUENCE_FLOW","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":28}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685261,"position":30,"timestamp":1613034568743,"recordType":"EVENT","intent":"ELEMENT_ACTIVATING","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task2","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":29}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685261,"position":31,"timestamp":1613034568744,"recordType":"EVENT","intent":"ELEMENT_ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"version":1,"bpmnProcessId":"process","elementId":"task2","workflowInstanceKey":2251799813685251,"flowScopeKey":2251799813685251,"bpmnElementType":"SERVICE_TASK","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1,"workflowKey":2251799813685249},"sourceRecordPosition":30}
09:09:40.303 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":-1,"position":32,"timestamp":1613034568745,"recordType":"COMMAND","intent":"CREATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task2","elementInstanceKey":2251799813685261,"workflowDefinitionVersion":1,"retries":3,"worker":"","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":-1,"workflowKey":2251799813685249},"sourceRecordPosition":31}
09:09:40.304 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685262,"position":33,"timestamp":1613034568746,"recordType":"EVENT","intent":"CREATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task2","elementInstanceKey":2251799813685261,"workflowDefinitionVersion":1,"retries":3,"worker":"","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":-1,"workflowKey":2251799813685249},"sourceRecordPosition":32}
09:09:40.304 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":-1,"position":34,"timestamp":1613034568747,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":-1}
09:09:40.306 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":2251799813685263,"position":35,"timestamp":1613034568749,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[2251799813685262],"jobs":[{"type":"bar","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task2","elementInstanceKey":2251799813685261,"workflowDefinitionVersion":1,"retries":3,"worker":"default","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":1613034868747,"workflowKey":2251799813685249}],"timeout":300000},"sourceRecordPosition":34}
09:09:40.307 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":-1,"position":36,"timestamp":1613034568752,"recordType":"COMMAND","intent":"ACTIVATE","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":-1}
09:09:40.307 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB_BATCH","key":2251799813685264,"position":37,"timestamp":1613034875095,"recordType":"EVENT","intent":"ACTIVATED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","worker":"default","maxJobsToActivate":32,"truncated":false,"jobKeys":[],"jobs":[],"timeout":300000},"sourceRecordPosition":36}
09:09:40.307 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685262,"position":38,"timestamp":1613035205178,"recordType":"COMMAND","intent":"TIME_OUT","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task2","elementInstanceKey":2251799813685261,"workflowDefinitionVersion":1,"retries":3,"worker":"default","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":1613034868747,"workflowKey":2251799813685249},"sourceRecordPosition":36}
09:09:40.307 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"JOB","key":2251799813685262,"position":39,"timestamp":1613035205180,"recordType":"EVENT","intent":"TIMED_OUT","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"1.0.0","value":{"type":"bar","errorMessage":"","bpmnProcessId":"process","customHeaders":{},"elementId":"task2","elementInstanceKey":2251799813685261,"workflowDefinitionVersion":1,"retries":3,"worker":"default","workflowInstanceKey":2251799813685251,"variables":{},"errorCode":"","deadline":1613034868747,"workflowKey":2251799813685249},"sourceRecordPosition":38}
09:09:40.307 [] [Time-limited test] INFO  io.zeebe.broker.test - Test execution time: 11730
09:09:40.307 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [1/14]: upgrade manager
09:09:40.307 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [1/14]: upgrade manager closed in 0 ms
09:09:40.307 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [2/14]: register diskspace usage listeners
09:09:40.307 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [2/14]: register diskspace usage listeners closed in 0 ms
09:09:40.307 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [3/14]: zeebe partitions
09:09:40.307 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1
09:09:40.307 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe Partition 1.
09:09:40.307 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] ERROR io.zeebe.broker.system - ZeebePartition-1 failed, marking it as unhealthy
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {ZeebePartition-1=UNHEALTHY, Raft-1=HEALTHY, Broker-0-StreamProcessor-1=HEALTHY, logstream-raft-partition-partition-1=HEALTHY}
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ExporterDirector
09:09:40.308 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] ERROR io.zeebe.broker.system - Partition-1 failed, marking it as unhealthy
09:09:40.308 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Detected unhealthy components. The current health status of components: {Partition-1=UNHEALTHY}
09:09:40.308 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter - Closed exporter director 'Broker-0-Exporter-1'.
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ExporterDirector closed successfully
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RocksDB metric timer
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RocksDB metric timer closed successfully
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AsyncSnapshotDirector
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: AsyncSnapshotDirector closed successfully
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StreamProcessor
09:09:40.308 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StreamProcessor closed successfully
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ZeebeDb
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: ZeebeDb closed successfully
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RegisterSnapshotListener
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RegisterSnapshotListener closed successfully
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: LogDeletionService
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: LogDeletionService closed successfully
09:09:40.308 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StateController
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/d61c3a23-1678-475c-9d58-a128f3b22402/data/raft-partition/partitions/1/runtime'.
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: StateController closed successfully
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: SnapshotReplication
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: SnapshotReplication closed successfully
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RaftLogReader
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: RaftLogReader closed successfully
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: logstream
09:09:40.339 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream logstream-raft-partition-partition-1
09:09:40.339 [logstream-raft-partition-partition-1-write-buffer] [Broker-0-zb-actors-0] DEBUG io.zeebe.dispatcher - Dispatcher closed
09:09:40.339 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - On closing logstream logstream-raft-partition-partition-1 close 3 readers
09:09:40.339 [Broker-0-LogStream-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Close log storage with name logstream-raft-partition-partition-1
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Closing Zeebe-Partition-1: logstream closed successfully
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition 1 closed all previous open resources, before transitioning.
09:09:40.339 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - Partition 1 transition complete, installed 0 resources!
09:09:40.339 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1 closed in 32 ms
09:09:40.339 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 partitions succeeded. Closed 1 steps in 32 ms.
09:09:40.339 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [3/14]: zeebe partitions closed in 32 ms
09:09:40.339 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [4/14]: leader management request handler
09:09:40.340 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [4/14]: leader management request handler closed in 1 ms
09:09:40.340 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [5/14]: disk space monitor
09:09:40.340 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [5/14]: disk space monitor closed in 0 ms
09:09:40.340 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [6/14]: monitoring services
09:09:40.340 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [6/14]: monitoring services closed in 0 ms
09:09:40.340 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [7/14]: embedded gateway
09:09:40.340 [] [Time-limited test] DEBUG io.zeebe.gateway - Closing gateway broker client ...
09:09:40.340 [] [Time-limited test] DEBUG io.zeebe.gateway - topology manager closed
09:09:40.341 [] [Time-limited test] DEBUG io.zeebe.gateway - Gateway broker client closed.
09:09:40.341 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [7/14]: embedded gateway closed in 1 ms
09:09:40.341 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [8/14]: topology manager
09:09:40.341 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [8/14]: topology manager closed in 0 ms
09:09:40.341 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [9/14]: cluster services
09:09:40.341 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [9/14]: cluster services closed in 0 ms
09:09:40.341 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [10/14]: subscription api
09:09:40.341 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [10/14]: subscription api closed in 0 ms
09:09:40.341 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [11/14]: command api handler
09:09:40.341 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [11/14]: command api handler closed in 0 ms
09:09:40.341 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [12/14]: command api transport
09:09:40.418 [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Detected local properties change {brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MTQ2BQABAQAAAAAMAAEBAAAAAgAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}
09:09:42.352 [] [ForkJoinPool.commonPool-worker-27] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
09:09:42.352 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [12/14]: command api transport closed in 2011 ms
09:09:42.352 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [13/14]: membership and replication protocol
09:09:42.352 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
09:09:42.353 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.raft.impl.zeebe.LogCompactor - LogCompactor{raft-partition-partition-1} - Closing the log compactor raft-partition-partition-1
09:09:42.353 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Closing segment: JournalSegment{id=1, version=1, index=1}
09:09:42.354 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.raft.partition.RaftPartitionGroup - Stopped
09:09:42.354 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.primitive.partition.impl.DefaultPartitionService - Stopped
09:09:42.354 [] [atomix-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Stopped
09:09:42.354 [] [atomix-cluster-0] INFO  io.atomix.cluster.messaging.impl.DefaultClusterEventService - Stopped
09:09:42.354 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Member deactivated: Member{id=0, address=0.0.0.0:7147, properties={brokerInfo=EADJAAAAAwAAAAAAAQAAAAEAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDo3MTQ2BQABAQAAAAAMAAEBAAAAAgAAAAAAAAAOAAAAMS4wLjAtU05BUFNIT1QFAAEBAAAAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}
09:09:42.354 [] [atomix-cluster-0] INFO  io.atomix.cluster.protocol.SwimMembershipProtocol - Stopped
09:09:42.354 [] [atomix-cluster-0] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Left
09:09:42.354 [] [atomix-cluster-0] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Stopped
09:09:46.371 [] [ForkJoinPool.commonPool-worker-27] INFO  io.atomix.cluster.messaging.impl.NettyMessagingService - Stopped
09:09:46.371 [] [atomix-cluster-0] INFO  io.atomix.cluster.AtomixCluster - Stopped
09:09:46.371 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [13/14]: membership and replication protocol closed in 4019 ms
09:09:46.371 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 [14/14]: actor scheduler
09:09:46.371 [] [Time-limited test] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers'
09:09:46.371 [] [Time-limited test] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors'
09:09:46.371 [] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-fs-workers': closed successfully
09:09:46.372 [] [Broker-0-zb-actors-0] DEBUG io.zeebe.util.actor - Closing actor thread ground 'Broker-0-zb-actors': closed successfully
09:09:46.372 [] [Time-limited test] DEBUG io.zeebe.broker.system - Closing Broker-0 [14/14]: actor scheduler closed in 1 ms
09:09:46.372 [] [Time-limited test] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 14 steps in 6065 ms.
09:09:46.372 [] [Time-limited test] INFO  io.zeebe.broker.system - Broker shut down.
09:09:46.451 [] [Time-limited test] INFO  io.zeebe.broker.test - Broker closing time: 6144
</pre>
</details>

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Replace worker usage with normal complete command send.

## Related issues

closes #6317

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/startup/BrokerReprocessingTest.java [hunk 1]
```diff
@@ -168,19 +168,16 @@ public void shouldContinueWorkflowInstanceAtTaskAfterRestart() {
...
-
     clientRule
         .getClient()
-        .newWorker()
-        .jobType("foo")
-        .handler(
-            (client, job) ->
-                client.newCompleteCommand(job.getKey()).variables(NULL_VARIABLES).send())
-        .open();
+        .newCompleteCommand(jobFoo.getKey())
```
Comment (korthout) [inline qa/integration-tests/src/test/java/io/zeebe/broker/it/startup/BrokerReprocessingTest.java:177]: wait... doesn't the job have to be `ACTIVATED` first?

**Review by korthout — APPROVED** [review]
Changes look good to me, I was just surprised that this can work. See question

File: qa/integration-tests/src/test/java/io/zeebe/broker/it/startup/BrokerReprocessingTest.java (hunk 1 above)
Comment (Zelldon) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/startup/BrokerReprocessingTest.java:177]: Nope this is also what TaskList for example does :)

Comment (korthout) [reply qa/integration-tests/src/test/java/io/zeebe/broker/it/startup/BrokerReprocessingTest.java:177]: mind is 🤯
