### PR TITLE
fix: add instance history 403 message

### LINKED ISSUE #48728: Process instance details page doesn't handle permission errors on process instance history
### 

### 

, 

### 

### 

### Description

When a user doesn't have permissions to read a specific process instance we simply show a generic error on the UI showing we couldn't fetch the process instance history like the other areas of the UI.

This is a bit confusing since the user might not understand what's happening

### Steps to reproduce

1. Create a process instance
2. Access the Operate process instance page with user that doesn't have read rights for that process

### Current behavior

The instance history panel shows `Instance History could not be fetched`

### Expected behavior

We should show an error similar to the other UI areas showing that the user doesn't have rights to read that process

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- Component Version: 8.8, 8.9

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Reported on: https://camunda.slack.com/archives/C09HWN20VJL/p1773418163266189

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by vsgoulart**
## Description

Adds lack of permissions error message to process instance history

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #48728

### CODE REVIEW

File: operate/client/src/App/ProcessInstance/ElementInstanceLog/ElementInstancesTree/index.tsx [hunk 1]
```diff
@@ -817,11 +818,20 @@ const ElementInstancesTree: React.FC<ElementInstancesTreeProps> = observer(
...
-    ) {
+    const rootNodeData = elementInstancesTreeStore.state.nodes.get(
+      processInstance.processInstanceKey,
+    );
+
+    if (rootNodeData?.status === 'error-permissions') {
+      return (
+        <ErrorMessage
+          message="Missing permissions to access Instance History"
+          additionalInfo="Please contact your organization owner or admin to give you the necessary permissions to access this instance history"
```
Comment (juliasaienko) [inline operate/client/src/App/ProcessInstance/ElementInstanceLog/ElementInstancesTree/index.tsx]: These messages seem the same as `FORBIDDEN_MESSAGE`, `FORBIDDEN_ADDITIONAL_INFO` from audit log page. Should we extract them to a shared constant?

File: operate/client/src/App/ProcessInstance/ElementInstanceLog/ElementInstancesTree/elementInstancesTreeStore.ts [hunk 2]
```diff
@@ -154,7 +156,7 @@ class ElementInstancesTreeStore extends NetworkReconnectionHandler {
         status: 'loaded',
       });
     } else {
-      this.setNodeStatus(scopeKey, 'error');
+      this.setNodeStatus(scopeKey, 'error', error);
```
Comment (juliasaienko) [inline operate/client/src/App/ProcessInstance/ElementInstanceLog/ElementInstancesTree/elementInstancesTreeStore.ts]: New error parameter has confusing semantics: `setNodeStatus`  takes a status of `error` but may resolve it to `error-permissions` internally. Lookd like the method silently "upgrades" erros, is it intentional?

File: operate/client/src/App/ProcessInstance/ElementInstanceLog/ElementInstancesTree/elementInstancesTreeStore.ts
Comment (juliasaienko) [inline operate/client/src/App/ProcessInstance/ElementInstanceLog/ElementInstancesTree/elementInstancesTreeStore.ts:496]: It seems that polling continues even when `pollExpandedNodes` gets a 403, it sets error-permissions but doesn't stop polling. The next poll cycle will hit the same 403. Should we stop it?

**Comment by vsgoulart** [comment]
@juliasaienko I addressed your comments

**Review by juliasaienko — APPROVED** [review]
Looks good. Minor suggestion: `getForbiddenPermissionsError` called at render time in `ElementInstancesTree` while `ElementInstanceLog` calls it once at module scope as
INSTANCE_HISTORY_FORBIDDEN. We might use a module-level constant in both places for consistency.
