### PR TITLE
fix: prevent numeric strings from being parsed as dates during Optimize import

### LINKED ISSUE #22104: On a report, numeric variables that have a length of 16 are displayed as a date
### Describe the bug

When numeric variables with a length of 16 are displayed in a raw data report, they are formatted as a date, rather than a string of numbers

### Expected behaviour

The value is displayed as a string

### To Reproduce

- Start Optimize in Self-Service mode
- Create an deploy a new process
- Start a process instance with this variable
```
{
  "inner": {
    "sixteen": "1234567890123456",
    "seventeen": "12345678901234567",
    "fifteen": "123456789012345"
  }
}
```
- Wait for Optimize to pick up the process
- Create a new Raw Data report in Optimize. Select the process you just created
- Enable preview updates
- Click the 'Configuration Options' button, the gear icon
- Open up the variables section, and add in the variables you ran the process with
- Look at the value for the `var` column

### Notes

- The 16 length variable is treated as a date. The column has a `date` type for the call to the `/variables` endpoint
- The `/evaluate` endpoint returns a date formatted value for a number of length 16
- Isolated to numeric strings. A string of length 16 that has a letter in it will be formatted properly and will not display as a date

### Environment observed:

- Optimize mode(s): Self-Service
- Optimize version(s): 3.14.4 / 8.5.4
- Database(s) (Elasticsearch/OpenSearch): ElasticSearch

### Breakdown

```[tasklist]
### Pull Requests
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [x] Yes. If so:
  - [x] The bug description is clear
  - [x] The steps to reproduce are clear
  - [x] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

https://jira.camunda.com/browse/SUPPORT-23475

### PR DESCRIPTION
**Pull request by Christian-Broomfield**
## Description

The date parsing library [DateParser](https://github.com/sisyphsu/dateparser) contains a list of 240+ rules for parsing potential date strings to date objects. This includes interpreting numeric strings of a fixed length (10-13, 16, 19) as unix timestamps, microseconds or nanoseconds.

The fix prevents such matches by ensuring that only strings containing alphanumeric characters should be parsed. Doing so allows us to continue using the DateParser library for parsing dates of an unknown format without having to specify them beforehand.

There's a potential discussion to be had whether this library, which has been inactive for over three years, still serves our needs or should be replaced by a newer library or different approach during our import process.

## Checklist

- [ ] Enable backports for optimize-8.7 and optimize-8.6

## Related issues

closes #22104

### CODE REVIEW

File: optimize/backend/src/main/java/io/camunda/optimize/service/importing/engine/service/ObjectVariableService.java [hunk 1]
```diff
@@ -317,12 +317,28 @@ private void addIdToSkeletonVariable(
...
+       * The DateParserUtils uses a list of 240+ rules/regexes to attempt and convert a string to
+       * a date. This includes fixed-length (10-13, 16, 19), numeric strings which it interprets
+       * as unix timestamps, microseconds or nanoseconds. In those cases it will incorrectly map
+       * such a String to a date, leading Optimize reports to display the value as a nonsensical
+       * date. Therefore, we first check to see if the string is composed of only digits and skip
+       * calling the DateParserUtils if that's the case.
+       */
+      if (isDigitOnlyString(dateAsString)) {
+        return Optional.empty();
+      }
```
Comment (korthout) [inline optimize/backend/src/main/java/io/camunda/optimize/service/importing/engine/service/ObjectVariableService.java:330]: This fix would prevent any timestamp from being parsed as a possible date. 

❓ Are we sure there are no cases where the `parsePossibleDate` method is called with an actual timestamp?

Comment (Christian-Broomfield) [reply optimize/backend/src/main/java/io/camunda/optimize/service/importing/engine/service/ObjectVariableService.java:330]: No, but it's also not possible to have both without specifying the type somewhere. Since DateParser attempts to parse a date with numerous permutations, we have to either disallow specific rules such as numeric strings of a fixed length or accept that such a string may be interpreted as a date.

The calling code:
```java
  private void parseStringOrDateVariableAndSet(
      final Object firstValue, final List<Object> valueList, final ProcessVariableDto newVariable) {
    final Optional<OffsetDateTime> optDate = parsePossibleDate(String.valueOf(firstValue));
    if (optDate.isPresent()) {
      parseDateVariableAndSet(valueList, newVariable);
    } else {
      parseStringVariableAndSet(valueList, newVariable);
    }
  }
```

Attempts to parse it as a date or ignores the attempt and continues with the variable as a string.  The caller for this method does check the variable to see if it's a primitive of some kind, e.g. 

```java
  private void formatNativeVariableAndAddToResult(
      final ProcessVariableUpdateDto variableUpdateDto, final List<ProcessVariableDto> resultList) {
    final ProcessVariableDto processVariableDto = createSkeletonVariableDto(variableUpdateDto);
    processVariableDto.setId(variableUpdateDto.getId());
    processVariableDto.setName(variableUpdateDto.getName());
    if (variableUpdateDto.getType().equals(STRING_TYPE)) {
      parseStringOrDateVariableAndSet(
          variableUpdateDto.getValue(),
          Collections.singletonList(variableUpdateDto.getValue()),
          processVariableDto);
    } else {
      processVariableDto.setType(variableUpdateDto.getType());
      processVariableDto.setValue(Collections.singletonList(variableUpdateDto.getValue()));
    }
    resultList.add(processVariableDto);
  }
```

or

```java
  private List<ProcessVariableDto> mapToFlattenedVariable(
      final String name, final Object value, final ProcessVariableUpdateDto origin) {
    // <snip some code>

    if (value instanceof JsonifyArrayList) {
      newVariable.setName(String.join(".", newVariable.getName(), LIST_SIZE_VARIABLE_SUFFIX));
      newVariable.setType(VariableType.LONG.getId());
      newVariable.setValue(
          Collections.singletonList(String.valueOf(((JsonifyArrayList<?>) value).size())));
      addVariableForListProperty(name, value, origin, resultList);
    } else if (value instanceof String) {
      parseStringOrDateVariableAndSet(value, Collections.singletonList(value), newVariable);
    } else if (value instanceof Boolean) {
      parseBooleanVariableAndSet(Collections.singletonList(value), newVariable);
    } else if (value instanceof Number) {
      parseNumberVariableAndSet(Collections.singletonList(value), newVariable);
    } else {
      LOG.debug(
          "Variable attribute '{}' of '{}' with type {} is not supported and won't be imported.",
          name,
          origin.getName(),
          value.getClass().getSimpleName());
      return Collections.emptyList();
    }
    addIdToSkeletonVariable(name, newVariable, origin);
    resultList.add(newVariable);
    return resultList;
  }
```

However, there is no such option for the DATE type. I'm assuming that a date string is functionally identical to a regular string as opposed to numbers and booleans. Since clients aren't forced to type their JSON data we are making a best effort guess to try and parse the data as the client intended. 

A better solution would be to add an option in the report generator to override a variable's type. If the string-to-date conversion is incorrect, the client could manually set the column type to whatever they want and Optimize will attempt to honor the new type. It should be noted though that this is part of the data import pipeline and so a wrong type conversion will ripple all the way through to the UI. Converting the date type back to the correct numeric string may prove tricky.

Comment (korthout) [reply optimize/backend/src/main/java/io/camunda/optimize/service/importing/engine/service/ObjectVariableService.java:330]: Can we duplicate the method and use the new and improved one only on the specific place you encountered? It might be easier to state whether or not timestamps are unexpected there.

Comment (Christian-Broomfield) [reply optimize/backend/src/main/java/io/camunda/optimize/service/importing/engine/service/ObjectVariableService.java:330]: It's being called in multiple places (`mapToFlattenedVariable`, `formatNativeVariableAndAddToResult`, `addVariableForListProperty`) depending on where the string variable is (value or list element) converted from. The two test cases verify that the bug no longer occurs if the variable is part of a key/value pair or as a list element. These are all steps within the `convertToProcessVariableDtos` method.

I could feasibly refactor the solution to only consider key-value pairs and not list elements because the bug ticket didn't include list elements. There's no telling if that's a good solution though or if we'll get another bug ticket sometime in the future because a numeric string is being parsed as a date in a JSON array.

**Comment by fabiopaini-camunda** [comment]
@Christian-Broomfield the issue was confirmed in 8.5, 8.6, 8.7 but not in 8.8+, yet this fix is implemented in main. If this change is necessary to fix the issue, why is the bug not present in 8.8+?

File: optimize/backend/src/main/java/io/camunda/optimize/service/importing/engine/service/ObjectVariableService.java (hunk 1 above)
Comment (korthout) [reply optimize/backend/src/main/java/io/camunda/optimize/service/importing/engine/service/ObjectVariableService.java:330]: @Christian-Broomfield Please consider the use cases.

Zeebe always tracks date and time variables as strings (e.g. when a FEEL expression produces a date and time `now()` it is [converted to a string](https://github.com/camunda/camunda/blob/1c3f7177a709cbf36d6f4ac08ffe089d974240a4/zeebe/feel/src/main/java/io/camunda/zeebe/feel/impl/FeelToMessagePackTransformer.java#L97-L105) when it enters Zeebe). So, such variables are still correctly displayed as parsed dates.

However, it's possible that users store timestamps as a [number](https://docs.camunda.io/docs/next/components/modeler/feel/language-guide/feel-data-types/#number) or string. Previously, these would be displayed in Optimize as parsed dates. I think it's fine to no longer do that to avoid the bug where we accidentally parse numbers that aren't meant as timestamps at all. The impact is that user provided timestamps are not displayed as dates in optimize, but to be fair the user had provided a timestamps anyway and not a date time object.

I believe this is fine. Feel free to resolve this conversation if you agree with that assessment.

File: optimize/backend/src/it/java/io/camunda/optimize/service/importing/ZeebeVariableCreationImportIT.java [hunk 2]
```diff
@@ -522,11 +590,11 @@ private void assertThatVariablesHaveBeenImportedForProcessInstance(
...
-            Tuple.tuple("var1", Collections.singletonList("someValue"), STRING_TYPE),
-            Tuple.tuple("var2", Collections.singletonList("false"), BOOLEAN_TYPE),
-            Tuple.tuple("var3", Collections.singletonList("123"), DOUBLE_TYPE),
-            Tuple.tuple("var4", Collections.singletonList("123.3"), DOUBLE_TYPE),
-            Tuple.tuple("var5", Collections.singletonList(""), STRING_TYPE));
+            Tuple.tuple("var1", singletonList("someValue"), STRING_TYPE),
+            Tuple.tuple("var2", singletonList("false"), BOOLEAN_TYPE),
+            Tuple.tuple("var3", singletonList("123"), DOUBLE_TYPE),
+            Tuple.tuple("var4", singletonList("123.3"), DOUBLE_TYPE),
+            Tuple.tuple("var5", singletonList(""), STRING_TYPE));
```
Comment (korthout) [inline optimize/backend/src/it/java/io/camunda/optimize/service/importing/ZeebeVariableCreationImportIT.java]: 🔧 These changes appear unintended to me (looking at the commit message). Might be good to revert or split to another commit if it was on purpose. Not making this change everywhere may help avoid conflicts when backporting.

**Review by korthout — APPROVED** [review]
Nice work @Christian-Broomfield 👍 

LGTM 👍 

🔧 I see one thing you can consider to avoid conflicts (and keep a cleaner history). Please have a look before merging.

File: optimize/backend/src/main/java/io/camunda/optimize/service/importing/engine/service/ObjectVariableService.java (hunk 1 above)
Comment (Christian-Broomfield) [reply optimize/backend/src/main/java/io/camunda/optimize/service/importing/engine/service/ObjectVariableService.java:330]: I discussed the numeric strings issue in the core-teams-features channel and the suggestion is to go ahead with the proposed fix.

- We should exclude numeric strings from being parsed as dates.
- Such a use case was unintended and they aren't aware if any customers rely on this logic.
- If so, we may receive new reports because of this breaking change.

I should confirm with you if we're okay with the risk and merge the PR if so. (addendum: this happened in the #core-features-charlie slack channel)

In that case I would go ahead and merge it in main because then the logic would be present in all versions going forward and explicitly disallow parsing timestamps as dates. I'll then backport the changes to 8.8 8.7 and 8.6. Fabio was able to access the customer's jira issue and confirmed that they have migrated to 8.7 since the issue was first reported (up from 8.5).
