### PR TITLE
fix: handle runtime instructions for multi-instance activities

### LINKED ISSUE #39812: Runtime error when instance started with `runtimeInstructions` for multi-instance element
### 

### 

### 

### 

### Description

When I start an instance with `runtimeInstructions` for an element with multi-instance characteristics, Orchestration Cluster returns a 400 error:

```
{"type":"about:blank","title":"Bad Request","status":400,"detail":"Request property [runtimeInstructions.null] cannot be parsed","instance":"/v2/process-instances"}
```

### Steps to reproduce

1. Create a diagram with a multi-instance task
2. Try to use Desktop Modeler task testing feature on the task
3. Error happens

You can also use the focussed test that I wrote to verify that it's not a Desktop Modeler issue. It assumes that REST API is available at localhost:8088

[test.zip](https://github.com/user-attachments/files/23022411/test.zip)

### Current behavior

Orchestration Cluster returns a 400 with `Request property [runtimeInstructions.null] cannot be parsed`

### Expected behavior

Either we make it work, or we outright declare is as unsupported.

### Workaround

No workaround known.

### Environment

SaaS & SM

### Version

8.8.0

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Discovered in https://github.com/camunda/camunda-modeler/issues/5353 (thanks @mschoe)

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by chillleader**
## Description

This PR adds a check before executing the runtime instruction to determine if the element is running as part of a multi-instance activity.

If it is part of a multi-instance, we should not execute the runtime instruction for every individual instance of the activity. Instead, we should only execute it once when the whole multi-instance activity finishes (i.e. token leaves the element from the user's perspective).

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #39812

### CODE REVIEW

**Comment by chillleader** [comment]
Re. Flaky tests: I assume those are not related to my changes, one of them was Zeebe unit tests that failed due to a runner issue, the other one was Opensearch with no related errors.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java [hunk 1]
```diff
@@ -271,4 +271,60 @@ record ->
...
+        .extracting(Record::getIntent, record -> record.getValue().getElementId())
+        .containsSubsequence(
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_ACTIVATED, multiInstanceTaskId),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_COMPLETED, multiInstanceTaskId),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_ACTIVATED, multiInstanceTaskId),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_COMPLETED, multiInstanceTaskId),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_ACTIVATED, multiInstanceTaskId),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_COMPLETED, multiInstanceTaskId),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_TERMINATING, processId),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_TERMINATED, processId));
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java]: ❌ This assertion is missing the element type which is relevant to this test case explicitly because you want to differentiate between the multi-instance body and the inner script tasks.

I would suggest the following (no need to check element id if you're checking element type):
```suggestion
    assertThat(result)
        .extracting(Record::getIntent, r -> r.getValue().getBpmnElementType())
        .containsSubsequence(
            Tuple.tuple(
                ProcessInstanceIntent.ELEMENT_ACTIVATED, BpmnElementType.MULTI_INSTANCE_BODY),
            Tuple.tuple(ProcessInstanceIntent.ELEMENT_ACTIVATED, BpmnElementType.SCRIPT_TASK),
            Tuple.tuple(ProcessInstanceIntent.ELEMENT_COMPLETED, BpmnElementType.SCRIPT_TASK),
            Tuple.tuple(ProcessInstanceIntent.ELEMENT_ACTIVATED, BpmnElementType.SCRIPT_TASK),
            Tuple.tuple(ProcessInstanceIntent.ELEMENT_COMPLETED, BpmnElementType.SCRIPT_TASK),
            Tuple.tuple(ProcessInstanceIntent.ELEMENT_ACTIVATED, BpmnElementType.SCRIPT_TASK),
            Tuple.tuple(ProcessInstanceIntent.ELEMENT_COMPLETED, BpmnElementType.SCRIPT_TASK),
            Tuple.tuple(
                ProcessInstanceIntent.ELEMENT_COMPLETED, BpmnElementType.MULTI_INSTANCE_BODY),
            Tuple.tuple(ProcessInstanceIntent.ELEMENT_TERMINATING, BpmnElementType.PROCESS),
            Tuple.tuple(ProcessInstanceIntent.ELEMENT_TERMINATED, BpmnElementType.PROCESS));
```

🔧 Even more explicit would be to switch to `containsSequence` rather than `containsSubsequence`.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnStateTransitionBehavior.java [hunk 2]
```diff
@@ -483,6 +483,17 @@ Either<ProcessInstanceInterrupted, BpmnElementContext> executeRuntimeInstruction
...
+    // if an element is part of a multi-instance, we skip runtime instructions as they are applied
+    // to the multi-instance container element
+
+    final var flowScopeInstance = stateBehavior.getFlowScopeInstance(context);
+    final var isMultiInstanceActivity =
+        flowScopeInstance != null && flowScopeInstance.getMultiInstanceLoopCounter() > 0;
+
+    if (isMultiInstanceActivity) {
+      return Either.right(context);
+    }
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnStateTransitionBehavior.java:493]: ❌ You can check this without a state lookup because we already have the process model available in `element`.

```suggestion
    // if an element is part of a multi-instance, we skip runtime instructions as they are applied
    // to the multi-instance container element
    final var isMultiInstanceActivity =
        element.getFlowScope() != null
            && element.getFlowScope().getElementType() == BpmnElementType.MULTI_INSTANCE_BODY;
    if (isMultiInstanceActivity) {
      return Either.right(context);
    }
```

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java [hunk 3]
```diff
@@ -271,4 +271,60 @@ record ->
...
+                .scriptTask()
+                .id(multiInstanceTaskId)
+                .zeebeExpression("i + 2")
+                .zeebeResultVariable("j")
+                .multiInstance(
+                    b ->
+                        b.zeebeInputCollectionExpression("[1,2,3]")
+                            .zeebeInputElement("i")
+                            .zeebeOutputCollection("out")
+                            .zeebeOutputElementExpression("j + 2"))
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java]: 🔧 This is not necessary for the test case. Let's remove it to focus the test case.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java [hunk 4]
```diff
@@ -271,4 +271,60 @@ record ->
...
+    // given
+    final String processId = "process";
+    final String multiInstanceTaskId = "multiInstanceTask";
+    ENGINE
+        .deployment()
+        .withXmlResource(
+            Bpmn.createExecutableProcess(processId)
+                .startEvent()
+                .scriptTask()
+                .id(multiInstanceTaskId)
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java]: 🔧 You can inline this:

```suggestion
                .scriptTask(multiInstanceTaskId)
```

**Review by korthout — CHANGES_REQUESTED** [review]
Good catch @chillleader 🚀 

👍 Generally looks like the right approach.
👍 I like the test case!

❌ I see some possible improvements to performance (not using a state lookup to determine whether this is an inner instance of a multi-instance body) and test accuracy (does the test case really check for the difference between multi-instance body and inner instance?)

Please have a look at my change requests and suggestions.

**Comment by chillleader** [comment]
Thanks for reviewing @korthout, I applied your suggestions 👍

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnStateTransitionBehavior.java [hunk 5]
```diff
@@ -485,11 +485,9 @@ Either<ProcessInstanceInterrupted, BpmnElementContext> executeRuntimeInstruction
 
     // if an element is part of a multi-instance, we skip runtime instructions as they are applied
     // to the multi-instance container element
-
-    final var flowScopeInstance = stateBehavior.getFlowScopeInstance(context);
     final var isMultiInstanceActivity =
-        flowScopeInstance != null && flowScopeInstance.getMultiInstanceLoopCounter() > 0;
-
+        element.getFlowScope() != null
+            && element.getFlowScope().getElementType() == BpmnElementType.MULTI_INSTANCE_BODY;
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnStateTransitionBehavior.java]: 🔧 The reason for this change should be described in the commit message.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java [hunk 6]
```diff
@@ -282,16 +283,11 @@ public void shouldTerminateOnlyOnceForMultiInstanceElements() {
         .withXmlResource(
             Bpmn.createExecutableProcess(processId)
                 .startEvent()
-                .scriptTask()
-                .id(multiInstanceTaskId)
+                .scriptTask(multiInstanceTaskId)
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java]: 💭 This change could've been a separate commit with it's own message explaining why.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java [hunk 7]
```diff
@@ -282,16 +283,11 @@ public void shouldTerminateOnlyOnceForMultiInstanceElements() {
...
                 .zeebeExpression("i + 2")
                 .zeebeResultVariable("j")
                 .multiInstance(
-                    b ->
-                        b.zeebeInputCollectionExpression("[1,2,3]")
-                            .zeebeInputElement("i")
-                            .zeebeOutputCollection("out")
-                            .zeebeOutputElementExpression("j + 2"))
+                    b -> b.zeebeInputCollectionExpression("[1,2,3]").zeebeInputElement("i"))
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java]: 💭 This change could've been a separate commit with it's own message explaining why.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java [hunk 8]
```diff
@@ -316,15 +312,19 @@ record ->
...
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_ACTIVATED, BpmnElementType.SCRIPT_TASK),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_COMPLETED, BpmnElementType.SCRIPT_TASK),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_ACTIVATED, BpmnElementType.SCRIPT_TASK),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_COMPLETED, BpmnElementType.SCRIPT_TASK),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_ACTIVATED, BpmnElementType.SCRIPT_TASK),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_COMPLETED, BpmnElementType.SCRIPT_TASK),
+            Tuple.tuple(
+                ProcessInstanceIntent.ELEMENT_COMPLETED, BpmnElementType.MULTI_INSTANCE_BODY),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_TERMINATING, BpmnElementType.PROCESS),
+            Tuple.tuple(ProcessInstanceIntent.ELEMENT_TERMINATED, BpmnElementType.PROCESS));
```
Comment (korthout) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceWithTerminationInstructionTest.java]: 💭 This change could've been a separate commit with it's own message explaining why.

**Review by korthout — APPROVED** [review]
Nice! 👏 

LGTM 👍 

🔧 I see opportunity to share more details about why these changes were needed in the commit messages. This helps future readers of the code to understand why it works the way it does. Please take a moment to expand your commit messages with more context and details before merging.
