### PR TITLE
Not subscribe to new subscription if element is in ACTIVATING state

### LINKED ISSUE #19212: Instance migration subscribes element instance with incident to message event
We detected an inconsistency while processing the following record:
```
Expected to process record 'LoggedEvent [position=3534407, key=4503599629136776, timestamp=1717796404395, sourceEventPosition=-1] RecordMetadata{recordType=COMMAND, valueType=INCIDENT, intent=RESOLVE, authorization=[REDACTED]}' successfully on stream processor, but caught unrecoverable exception.
```

Full stacktrace:

```
 io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=DbLong{4503599629136774}, second=DbTenantAwareKey[tenantKey=<default>, wrappedKey=[REDACTED], placementType=PREFIX]} in ColumnFamily PROCESS_SUBSCRIPTION_BY_KEY already exists
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyDoesNotExist(TransactionalColumnFamily.java:316) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$insert$0(TransactionalColumnFamily.java:87) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:344) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:343) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.insert(TransactionalColumnFamily.java:82) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.state.message.DbProcessMessageSubscriptionState.put(DbProcessMessageSubscriptionState.java:94) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:28) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:15) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:440) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:56) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:42) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvent(CatchEventBehavior.java:299) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToMessageEvents$10(CatchEventBehavior.java:273) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvents(CatchEventBehavior.java:273) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToEvents$7(CatchEventBehavior.java:181) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.ifRight(Either.java:428) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToEvents(CatchEventBehavior.java:179) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToEvents(CatchEventBehavior.java:151) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnEventSubscriptionBehavior.subscribeToEvents(BpmnEventSubscriptionBehavior.java:48) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.lambda$finalizeActivation$1(JobWorkerTaskProcessor.java:65) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:417) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.finalizeActivation(JobWorkerTaskProcessor.java:65) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskSupportingProcessor.finalizeActivation(JobWorkerTaskSupportingProcessor.java:39) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskSupportingProcessor.finalizeActivation(JobWorkerTaskSupportingProcessor.java:18) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processElementWithListeners(BpmnStreamProcessor.java:236) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.afterActivating(BpmnStreamProcessor.java:204) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$3(BpmnStreamProcessor.java:162) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:417) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:162) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:110) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:107) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.incident.IncidentResolveProcessor.lambda$attemptToContinueProcessProcessing$0(IncidentResolveProcessor.java:113) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.incident.IncidentResolveProcessor.attemptToContinueProcessProcessing(IncidentResolveProcessor.java:111) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.incident.IncidentResolveProcessor.processRecord(IncidentResolveProcessor.java:90) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:369) ~[zeebe-stream-platform-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:282) ~[zeebe-stream-platform-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:116) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:282) ~[zeebe-stream-platform-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:240) ~[zeebe-stream-platform-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.5.1.jar:8.5.1] 
```

Error Group: https://console.cloud.google.com/errors/detail/CPDM9-CV9Nvk3wE;service=zeebe;time=P7D?project=camunda-saas-prod
Incident: https://camunda.slack.com/archives/C0778L3662G
Data from zeebe-2: https://drive.google.com/file/d/1JV1K0GwibNRBHMrAI8l5670GLyZYc38h/view?usp=drive_link

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

During PIM (Process Instance Migration) an element shouldn't subscribe into a new subscription if the element state is `ACTIVATING`, due to a previous incident occurred

## Related issues

closes #19212

### CODE REVIEW

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @nicpuppa 

❌ We need some more changes, because the bug can also surface when completing the activity.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java [hunk 1]
```diff
@@ -285,6 +286,19 @@ private void tryMigrateElementInstance(
...
+      migrateCatchEvent(elementInstance, targetProcessDefinition, sourceElementIdToTargetElementId,
+          elementInstanceRecord, targetElementId, processInstanceKey, elementId);;
+    }
+  }
+
+  private void migrateCatchEvent(final ElementInstance elementInstance,
+      final DeployedProcess targetProcessDefinition,
+      final Map<String, String> sourceElementIdToTargetElementId,
+      final ProcessInstanceRecord elementInstanceRecord, final String targetElementId,
+      final long processInstanceKey, final String elementId) {
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java:301]: This will require some auto formatting: `mvn spotless:apply`

**Comment by korthout** [comment]
@nicpuppa Can you have a look at my last changes?

**Review by korthout — APPROVED** [review]

**Comment by korthout** [comment]
@berkaycanbc Would be nice to have a review from you on these changes as well 🙇

**Review by nicpuppa — COMMENTED** [review]
LGTM

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java [hunk 2]
```diff
@@ -285,6 +286,28 @@ private void tryMigrateElementInstance(
                         .setBpmnProcessId(targetProcessDefinition.getBpmnProcessId())
                         .setTenantId(elementInstance.getValue().getTenantId())));
 
+    if (ProcessInstanceIntent.ELEMENT_ACTIVATING != elementInstance.getState()) {
+      // element in ACTIVATING state should not be subscribed into new subscription during migration
```
Comment (berkaycanbc) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java:290]: 🔧 This comment doesn't explain the "why". Let's mention the ACTIVATING element will not have any message subscriptions created yet, so we shouldn't create one in the target process. The subscription will be created when the incident is resolved in the target element.

**Review by berkaycanbc — APPROVED** [review]
✅ Allowing incident migration on intents `ELEMENT_TERMINATING` and `ELEMENT_COMPLETING` looks okay. For `ELEMENT_TERMINATING`, we already resolve incidents right after writing the command, so we won't fall into this case at all. For `ELEMENT_COMPLETING`, we already have the message subscription created.

👍 I requested one change which only adds more clarity around the implementation. Feel free to merge afterwards. 


⚠️ **Note:** for the implementation of message subscriptions migration (migrating message subscriptions instead of re-creating), we need to reject migration when the element is in `ELEMENT_ACTIVATING` state. Because, a boundary event actually exists in the source definition but the subscription is not created, so nothing to migrate.

**Review by berkaycanbc — APPROVED** [review]

**Comment by korthout** [comment]
> ⚠️ Note: for the implementation of message subscriptions migration (migrating message subscriptions instead of re-creating), we need to reject migration when the element is in ELEMENT_ACTIVATING state. Because, a boundary event actually exists in the source definition but the subscription is not created, so nothing to migrate.

@berkaycanbc I believe we can find a better solution. I'll write down my thoughts in some follow-up issues that we should take a long with the instance migration topic.

**Comment by korthout** [comment]
What is happening with the merge queue? 🤔

**Comment by korthout** [comment]
Keep on getting `Could not acquire write lock for ...` maven build errors. Another try

**Comment by korthout** [comment]
>java.lang.IllegalStateException: Could not acquire lock(s)

Again...
