### PR TITLE
fix(broker): detect out of cluster messages received in NettyUnicastService 

### LINKED ISSUE #5641: Gateway communicated with broker in different cluster
**Describe the bug**
The benchmark for the 0.25 release went down today (20/10) at around 03:14 when broker 2 restarted and broker 0 and 1 got stuck in an election loop. It seems like 0 and 1 are not able to communicate so one broker starts an election and is elected until, eventually the other broker starts another election because it doesn't get heartbeats. More or less around this time this was logged several times:
```{
  "insertId": "18omypxf3ou7ul",
  "jsonPayload": {
    "message": "Received invalid handshake, closing connection",
    "thread": "netty-messaging-event-epoll-client-9",
    "logger": "io.atomix.cluster.messaging.impl.NettyMessagingService",
```
Hours later the loop stops and both 0 and 1 believe they're leader.

Getting the topology from the gateway returns the following:
```
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.25.0-SNAPSHOT
Brokers:
  Broker 1 - release-0-24-4-rc2-zeebe-1.release-0-24-4-rc2-zeebe.release-0-24-4-rc2.svc.cluster.local:26501
    Version: 0.24.4
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Leader
```

This indicates that the gateway in the `release-0-25-0` namespace is communicating with a broker in the `relase-0-24-4-rc2` namespace. It also explains the `invalid handshake` log statement, since that is logged when a preamble in the message is different from what the NettyMessagingService expects. This preamble is the hashcode of the clusterName which is based on the version (e.g., "release-0-25-0-zeebe"), so they're different in different namespaces.
The `release-0-24-4` cluster is also down.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

BREAKING CHANGE

* Use a preamble in every message send by NettyUnicastService
* If the preamble of the received message does not match the preamble of this cluster, it simply ignores the message

Preamble is generated from the clusterIds. The assumption here is that clusterIds are unique.

## Related issues

closes #5641

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by deepthidevaki** [comment]
No idea how to test if it really fixes the issue. @Zelldon Do you have any suggestion?

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyUnicastService.java [hunk 1]
```diff
@@ -95,7 +98,8 @@ public void unicast(final Address address, final String subject, final byte[] pa
 
     final Message message = new Message(this.address, subject, payload);
     final byte[] bytes = SERIALIZER.encode(message);
-    final ByteBuf buf = channel.alloc().buffer(4 + bytes.length);
+    final ByteBuf buf = channel.alloc().buffer(4 + 4 + bytes.length);
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyUnicastService.java:101]:
```suggestion
    final ByteBuf buf = channel.alloc().buffer(Integer.BYTES + Integer.BYTES + bytes.length);
```

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyUnicastService.java [hunk 2]
```diff
@@ -150,6 +144,24 @@ protected void channelRead0(
     return bind(serverBootstrap);
   }
 
+  private void handleReceivedPacket(final DatagramPacket packet) {
+    final int preambleReceived = packet.content().readInt();
+    if (preambleReceived != preamble) {
+      log.warn("Received unicast message from outside of the cluster. Ignoring the message");
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyUnicastService.java:150]: Could we add more context here like where does it came from etc.

**Review by ChrisKujawa — COMMENTED** [review]
Looks good thanks for fixing :+1: Two smaller things

File: atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyUnicastService.java (hunk 2 above)
Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyUnicastService.java]: Added sender address.

Comment (Zelldon) [reply atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyUnicastService.java]: Thanks :+1:

**Review by ChrisKujawa — APPROVED** [review]

**Comment by deepthidevaki** [comment]
Since this is a breaking change, I guess this should not be backported. @Zelldon 
I will remove the backport labels.

**Comment by Zelldon** [comment]
We could also build it in a way that it is not breaking :smile:

**Comment by deepthidevaki** [comment]
> We could also build it in a way that it is not breaking smile

:smile: Then it is not probably fixing the bug.
