### PR TITLE
fix: use composite cache IDs in batch operation exporters to prevent entity collisions

### LINKED ISSUE #42478: Batch Operations show 'Completed' state even when operationsCompletedCount !== operationsTotalCount
### 

### 

### 

### 

### Description

There is a mismatch between the “Items” field (calculated as operationsTotalCount, operationsFailedCount, and operationsCompletedCount) and the “Batch State” (provided as state in the API). The UI displays the batch operation as 'Completed' even if operationsCompletedCount is not equal to operationsTotalCount, which is misleading. See the attached screenshot for an example where these values are out of sync.

### Steps to reproduce

1. Trigger a batch operation in Camunda (e.g., Resolve Incident or Cancel Process Instance).
2. Monitor the batch operation's progress in the Batch Operations list.
3. Observe a scenario where the batch is shown as 'Completed' in the Batch State column but the Operations Completed count does not match the Operations Total count.

### Current behavior

The Batch State field shows 'Completed' even if not all operations are completed (i.e., operationsCompletedCount !== operationsTotalCount).

### Expected behavior

The Batch State field should only show 'Completed' when operationsCompletedCount === operationsTotalCount. Otherwise, it should reflect the correct progress/state of the batch.

### Workaround

Currently, there doesn’t seem to be a reliable workaround. Manual checking of the operations counts is required to verify batch completion state.

### Environment

SaaS & SM

### Version

8.9-SNAPSHOT

### Rootcause

Possibly, either the backend marks batch operations as completed prematurely or there is a discrepancy in how the total/complete counts are updated. Feedback from backend engineers in the related Slack thread supports this hypothesis.

### Solution ideas

Double-check the logic for marking a batch as completed. Ensure batch completion only happens when operationsCompletedCount matches operationsTotalCount. Audit both backend and frontend code paths.

### Dev -> QA handover

_No response_

### Links

Slack discussion and screenshot available. Example API response:
```
{
  "items": [
    {
      "batchOperationKey": "2251799813688248",
      "state": "COMPLETED",
      "batchOperationType": "RESOLVE_INCIDENT",
      "endDate": "2025-12-08T11:19:55.321+01:00",
      "operationsTotalCount": 2,
      "operationsFailedCount": 0,
      "operationsCompletedCount": 1,
      "errors": []
    },
  ]
}
```
Batch Operations UI screenshot

### Automated Test Impact

It’s possible the automated and manual tests are not covering this edge case, as this is a regression noticed during regular operation and visual validation.

### LINKED ISSUE #44209: Summary items show “Pending” on Batch Operation overview/detail page when no items are pending
### 

### 

### 

### 

### Description

On the Batch Operation overview and detail pages, the Summary Items section displays items with a “Pending” status even when there are no pending items associated with the batch operation.

This results in inaccurate status information being shown to the user and may cause confusion about the actual state of the batch operation.

### Steps to reproduce

1. Deploy process and start 5 process instances
2. Go to Operate
3. Select the 5 process instances and cancel those
4. Click View batch operations

### Current behavior

- On the overview page the Items section shows “Pending” items despite there being none.
- On the detail page the Summary of Items section shows “Pending” items despite there being none.

**overview page**
Image

**detail page**
Image

### Expected behavior

When there are no pending items, the Summary Items section should not display any items with a “Pending” status for both overview and details page.

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS

### Version

- Version 8.9.0-SNAPSHOT

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description

Fixes multiple bugs caused by the `ExporterBatchWriter` sharing cached
entities between logically independent handlers. All stem from the same
root cause: the writer caches by `(entityId, entityType)`, so two
handlers that produce the same key silently share — and corrupt — each
other's state.

### Bug 1 — `operationsTotalCount` double-counting

`BatchOperationCreatedHandler` and `BatchOperationChunkCreatedHandler`
both used the bare `batchOperationKey` as their entity ID, sharing the
same `BatchOperationEntity`. This caused `operationsTotalCount` to be
counted once during `updateEntity` and then incremented again by the
Painless script at flush time.

### Bug 2 — list-view `batchOperationIds` silently dropped

When two batch operations target the same process instance and their
records land in the same export batch, both list-view handlers produced
the same cache key (`processInstanceKey`). The second record's
`setBatchOperationIds` overwrote the first, silently losing it.

### Fix

Introduce **composite cache IDs** in all affected handlers so each
logical unit gets its own cached entity, while the Elasticsearch
document ID remains unchanged (extracted at flush time):

| Handler | Cache ID | ES doc ID |
|---|---|---|
| `BatchOperationChunkCreatedHandler` | `batchOpKey:chunk` | `batchOpKey` |
| `ListViewBatchOperationHandler` | `piKey:batchOpKey` | `piKey` |

Additional changes:
- **Collapsed chunk entities** — all chunks for the same batch operation
  now accumulate into a single cached entity (`batchKey:chunk` static
  suffix) instead of one per chunk, avoiding exporter batch inflation
  for large operations.
- **Switched to `updateWithScript`** in the chunk handler — the
  `CREATED` event is always exported before any `CHUNK_CREATED` events
  on every partition, so the document is guaranteed to exist and
  `upsertWithScript` is unnecessary (and harmful with composite IDs).

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #42478

### CODE REVIEW

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandlerTest.java [hunk 1]
```diff
@@ -118,25 +119,22 @@ void shouldUpdateEntityFromMultipleRecords() {
...
+    // then - the ES document ID should be just the batchKey (123), not the composite entity ID
     final var scriptCaptor = ArgumentCaptor.forClass(String.class);
     verify(mockRequest, times(1))
         .upsertWithScript(
-            eq(indexName),
-            eq(entity.getId()),
-            eq(entity),
-            scriptCaptor.capture(),
-            eq(updateFields));
+            eq(indexName), eq("123"), eq(entity), scriptCaptor.capture(), eq(expectedParams));
```
[the remark this answers is not in the document]
Comment (mustafadagher) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandlerTest.java]: converted back to draft to think and address this.

I think replacing upsert with `updateWithScript` could be a solution, but I need to think it through if it won't lead to other issues.

**Comment by mustafadagher** [comment]
Cross-posting my latest comment on the issue: https://github.com/camunda/camunda/issues/42478#issuecomment-4215617058

>💭 For what it's worth, I think the same issue that led to double-counting here could also impact the addition of `batchOperationIds` in `ListViewFromChunkItemHandler` and `AbstractProcessInstanceFromOperationItemHandler`
>
>- If several flushes related to the same entity id (`ProcessInstanceKey` in this case) happened to be in the same exporter batch for exporter entity (`ProcessInstanceForListViewEntity`), they will use the same cashed exporter entity, and the batch ids will be appended to the same cached instance. 
>- in the flush script we use `entity.getBatchOperationIds().getFirst()` assuming that per handler there should only be one operation id there. But with caching used, this might not be the case.

**Review by fabiopaini-camunda — APPROVED** [review]
LGTM, thank you @mustafadagher for the fix!

**Comment by mustafadagher** [comment]
I'll copy below a conversation that was triggered by a question from @RomanJRW for reference ([slack](https://camunda.slack.com/archives/C08GPP57D8R/p1775829307554969))

@RomanJRW :
❓**Can you help me understand whether and to what extent this will result in more frequent flushes?** 

@mustafadagher :
This PR will increase the `cachedEntities` count (i.e., `getBatchSize()`) during batch operations, which can cause the exporter to flush slightly more often, but only during batch operation processing, and the effect should be modest.

To explain it a bit in depth:
How the flush decision works
The exporter flushes when any of these conditions is met (`CamundaExporter.shouldFlush()`):
- **Size-based:** `writer.getBatchSize() >= configuration.getBulk().getSize()`
- **Memory-based:** `writer.getBatchMemoryEstimateInMb() >= configuration.getBulk().getMemoryLimit()`
- **Time-based:** batch age exceeds `flushDelayMs` and batch is non-empty

Before, **all chunk records for the same batch operation** collapsed into a **single** cached entity (sharing the same key with the `CreatedHandler`). After this PR, **each chunk gets its own cached entity**.

The change **does increase `getBatchSize()`** during batch operation export, which theoretically can trigger earlier size-based flushes.

I think the argument here is that this would be only a problem when we have batch operations processing.

However;
**If I choose to play the advocate of the devil:**
- The default batch operation chunk size (`DEFAULT_BATCH_OPERATION_CHUNK_SIZE`) is `100`. Meaning a chunk can have a max of `100` items. if we have a batch operation that involves a `1M` process instances, this means `10000` chunk entities... 
- The default exporter bulk size is now `5000`. So what might have been treated as a single entity in one flush, would now add two extra flushes to export only the chunks of a batch operation of 1M instances

**Review by RomanJRW — APPROVED** [review]

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java [hunk 2]
```diff
@@ -79,15 +83,16 @@ public void updateEntity(
...
-    // BatchOperationUpdateTask will re-process this batch operation to update all counts.
-    batchRequest.upsertWithScript(
+    // The document always exists: on every partition, BatchOperation CREATED is exported before any
+    // CHUNK_CREATED events. We use updateWithScript to atomically increment the total and reset
+    // endDate so the BatchOperationUpdateTask re-processes the counts.
+
+    // Extract just the batchKey from the composite cache ID (batchKey:chunkKey).
+    final String batchOperationKey = entity.getId().split(":")[0];
+
+    batchRequest.updateWithScript(
```
Comment (remcowesterhoud) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java]: ❓ This was explicitly changed to `upsertWithScript` [here](https://github.com/camunda/camunda/pull/47635). Could you explain to me what changed so this is no longer necessary? Because the other changes in this PR seem irrelevant to this?

Comment (remcowesterhoud) [inline zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java:90]: 💭 Handlers should be idempotent, as the engine could export the same event multiple times. Using this update with script means we'd potentially increment the total twice, right?

We already have this problem atm so I see it as out of scope for this issue. But it seems to me like this is another scenario where the count wouldn't be corect.

**Review by remcowesterhoud — APPROVED** [review]
I'll approve, but I left a question and a thought.

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java (hunk 2 above)
Comment (mustafadagher) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java]: @remcowesterhoud does my commit message on 2710f3b37ed6fe3fe5b6151001607bcd971de692 explain it enough? or do you still need more elaboration?

**Comment by mustafadagher** [comment]
I having merged this PR yet because I wanted to get an opportunity to make address [this comment](https://github.com/camunda/camunda/pull/50639#issuecomment-4224804318).

💭 In the change I've made, I did not use the value of `chunk key` in any meaningful way. Only to get a separate cache entity and avoid the double counting.
But I was thinking what if I just use a static `:chunk` suffix instead of the chunk key (so the id becomes `<batchKey>:chunk`), and this way we will just have one single (cached) entity for all chunks, and we will then call the handler flush only once.

I'm not sure if I'm over-analyzing here, but I'd like your opinion @RomanJRW @remcowesterhoud

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java (hunk 2 above)
Comment (remcowesterhoud) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java]: It does, sorry I missed that one.

**Comment by remcowesterhoud** [comment]
> But I was thinking what if I just use a static :chunk suffix instead of the chunk key (so the id becomes <batchKey>:chunk), and this way we will just have one single (cached) entity for all chunks, and we will then call the handler flush only once.

Imo this sounds like a good idea to reduce the amount of flushing.

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/batchoperation/listview/AbstractProcessInstanceFromOperationItemHandlerTest.java [hunk 3]
```diff
@@ -178,21 +180,23 @@ final var record = createCompletedRecord(123456789L);
...
   void shouldFlushEntity() {
-    // Given
-    final var entity = underTest.createNewEntity("test-id");
-    entity.setBatchOperationIds(List.of("batch-op-1"));
+    // Given - entity uses composite cache ID (processInstanceKey:batchOperationReference)
+    final String processInstanceKey = "42";
+    final String batchOperationKey = "batch-op-1";
+    final var entity = underTest.createNewEntity(processInstanceKey + ":" + batchOperationKey);
+    entity.setBatchOperationIds(List.of(batchOperationKey));
     final var batchRequest = mock(BatchRequest.class);
```
[the remark this answers is not in the document]
Comment (mustafadagher) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/batchoperation/listview/AbstractProcessInstanceFromOperationItemHandlerTest.java:188]: the test is only concerned about `flush()`, not how the entity was constructed.

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/batchoperation/listview/ListViewFromChunkItemHandlerTest.java [hunk 4]
```diff
@@ -108,19 +108,21 @@ void shouldFlushEntity() {
     final Record<BatchOperationChunkRecordValue> record =
         factory.generateRecordWithIntent(
             ValueType.BATCH_OPERATION_CHUNK, BatchOperationChunkIntent.CREATED);
-    final var entity = underTest.createNewEntity("id");
     final String batchOpKey = String.valueOf(record.getBatchOperationReference());
+    // entity uses composite cache ID (processInstanceKey:batchOperationKey)
+    final String processInstanceKey = "42";
+    final var entity = underTest.createNewEntity(processInstanceKey + ":" + batchOpKey);
     entity.setBatchOperationIds(List.of(batchOpKey));
```
[the remark this answers is not in the document]
Comment (mustafadagher) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/batchoperation/listview/ListViewFromChunkItemHandlerTest.java]: actually, there's no need to generate the record at all, since the test only concerns `flush()`

File: zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java (hunk 2 above)
Comment (mustafadagher) [reply zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/batchoperation/BatchOperationChunkCreatedHandler.java:90]: created this follow-up issue https://github.com/camunda/camunda/issues/51122 with the help of co-pilot
