### PR TITLE
fix: correct error usage from useApiCall to show detailed error

### LINKED ISSUE #34496: Error message not shown on first form submission of creating initial admin user
### 

### 

### 

### 

### Description

When I already have an admin user and try to create a new initial admin user through `/identity/setup` I expect to receive an error message indicating an admin user already exists, and to consult the existing admin to create a new admin user.

This error message doesn't appear on the first time I submit the form. When I submit it again, it does appear.

### Steps to reproduce

1. Startup a fresh environment (empty elasticsearch, empty broker)
2. Navigate to `/identity/setup`
3. Create an initial admin user -> All should be good and you'll be redirected to the `/login` page
4. Navigate back to `/identity/setup`
5. Try to create another initial admin user -> You'll be forbidden, but no detailed error message appears

Image

6. Submit the form a second time -> You are forbidden again, this time the detailed error message does appear

Image

### Current behavior

I need to submit the form twice to understand what's going wrong.

### Expected behavior

The detailed error message should appear after the first submission.

### Environment

SaaS & SM

### Version

See affected versions

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by vitorwtavares**
## Description

- Correct usage of error from `useApiCall` function so detailed error is immediately available upon failure to create setup admin user
- Suppress default error notifications for setup page as the feedback for the user is confusing with 2 different error messages

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #34496

### CODE REVIEW

File: identity/client/src/pages/setup/SetupPage.tsx [hunk 1]
```diff
@@ -69,7 +72,8 @@ const SetupForm: React.FC<SetupFormProps> = ({ onSuccess }) => {
       if (success) {
         onSuccess();
       } else {
-        setSubmitError(error?.detail || "");
+        const detail = (error as ErrorResponse<"detailed">)?.detail;
+        setSubmitError(detail || "");
```
Comment (vsgoulart) [inline identity/client/src/pages/setup/SetupPage.tsx]: @vitorwtavares I think it's better to provide some generic error message instead of having an empty string here

File: identity/client/src/utility/localization/en/components.json [hunk 2]
```diff
@@ -67,5 +67,6 @@
   "setupEmailLabel": "Email",
   "setupEmailPlaceholder": "Enter email",
   "setupEmailInvalid": "Please enter a valid email",
-  "setupCreateUser": "Create user"
+  "setupCreateUser": "Create user",
+  "setupCreateAdminUserGenericError": "An error occurred while creating the admin user. Please try again."
```
Comment (vsgoulart) [inline identity/client/src/utility/localization/en/components.json:71]: Don't we have to add translations?

**Review by vsgoulart — APPROVED** [review]

File: identity/client/src/utility/localization/en/components.json (hunk 2 above)
Comment (vitorwtavares) [reply identity/client/src/utility/localization/en/components.json:71]: @vsgoulart Do you mean for other languages? If so, we only have english translations currently, but yes, this has to be done eventually. I'll create a ticket for it as well. 

There's a large backlog of FE improvements to be implemented [here](https://github.com/camunda/camunda/issues/32312) I'm trying to tackle little by little, it's a mix of bugs, improvements and things that were considered not top priority for this first version. I'm planning to re-organize the tickets next week then we'll have a better view of what's missing.
