### PR TITLE
Not write the entire command for rejection

### LINKED ISSUE #12699: Do not write the entire command for rejection
In https://github.com/camunda/zeebe/issues/12591, we found that when engine rejects the deployment request it cannot write the rejection record because it was attempting to write the whole deployment which is greater than maxMessageSize. This resulted in a loop in StreamProcessor, where it repeatedly fails to write the rejection record leading to the partition being fully blocked and not making any progress. https://github.com/camunda/zeebe/issues/12591#issuecomment-1535879364 

To fix this, now we reject the request in CommandAPI before writing to the logstream https://github.com/camunda/zeebe/pull/12676. But, to be safer we should also ensure that we are not writing rejection records that are too large, to prevent such accidental cases.

Ensure that rejections records can be written reliably, even if the original command is rejected due to ExceededBatchSize. Ideally, rejection record should only have a reference to the original command, but not the full command. If possible, do not write the entire command for any type of rejections. Or atleast, trim rejection record in case of ExceededBatchSize exception.

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

With this fix we are able to wright a rejection record without encounter `ExceededBatchSize ` error. 

## Related issues

closes #12699 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by deepthidevaki** [comment]
@abbasadel Since the changes are entirely in engine, I don't think my review is required.

File: engine/src/main/java/io/camunda/zeebe/engine/Engine.java [hunk 1]
```diff
@@ -195,6 +197,25 @@ private void handleUnexpectedError(
     }
   }
 
+  /**
+   * This method remove unuseful information from rejected records in order to not encounter the
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/Engine.java:201]: :upside_down_face: Maybe we can say "removes redundant information" instead.

```suggestion
   * This method removes redundant information from rejected records in order to avoid the
```

File: engine/src/main/java/io/camunda/zeebe/engine/Engine.java [hunk 2]
```diff
@@ -195,6 +197,25 @@ private void handleUnexpectedError(
...
+   *   <li>Commands of type {@link DeploymentRecord}: for those records the resources information
+   *       are not necessary
+   * </ul>
+   *
+   * @param record the record to transform
+   * @return the {@link TypedRecord} with only necessary information
+   */
+  private TypedRecord getRejectionRecord(final TypedRecord record) {
+    if (record.getValue() instanceof final DeploymentRecord deploymentRecord) {
+      deploymentRecord.resetResources();
```
Comment (koevskinikola) [inline engine/src/main/java/io/camunda/zeebe/engine/Engine.java:214]: :+1: Nice!

**Review by koevskinikola — CHANGES_REQUESTED** [review]
Runtime code looks good :rocket: but it would be good if we can add some test coverage for this fix.

Maybe we can use the [`LargeMessageSizeTest`](https://github.com/camunda/zeebe/blob/39d9f4296f4d6183b9d944715dbeaffb6ab63704/qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/LargeMessageSizeTest.java#L59-L107) as inspiration?

**Comment by nicpuppa** [comment]
Hey @koevskinikola, thanks for the review 💪 

As suggested, I created a new test case to verify the new behaviour. Please have another look 👀

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/CreateDeploymentTest.java [hunk 3]
```diff
@@ -153,4 +164,35 @@ public void shouldRejectDeployIfResourceIsTooLarge() {
...
+    rejectedRecords.stream()
+        .map(Record::getValue)
+        .forEach(
+            recordValue -> {
+              if (recordValue instanceof DeploymentRecord) {
+                assertThat(((DeploymentRecord) recordValue).getResources()).isEmpty();
+              }
+            }
+        );
+  }
```
Comment (koevskinikola) [inline qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/CreateDeploymentTest.java:197]: :1st_place_medal:

**Review by koevskinikola — APPROVED** [review]
Nice one! :rocket: 

bors merge

**Comment by nicpuppa** [comment]
bors retry

**Comment by korthout** [comment]
@nicpuppa @koevskinikola Should this be backported?

**Comment by koevskinikola** [comment]
@korthout I think we should backport it to 8.2 only, as the original report (#12591) mentions that this is a regression in that version.
