### PR TITLE
fix: use correct url template for cloud rest address

### LINKED ISSUE #32759: [JavaClient] The Camunda cloud client builder sets the wrong REST address
### 

### 

### 

### 

### Description

I use the Cloud client builder from the Java SDK to create a client. When I do a REST request with the client (e.g., a search request), the request fails because of an unknown host address.   

The issue is related to REST requests. gRPC requests work fine. 

### Steps to reproduce

1. Run the following Java snippet
2. Verify that the request fails

```java
        try (CamundaClient camundaClient =
                     CamundaClient
                             .newCloudClientBuilder()
                             .withClusterId("MY_CLUSTER_ID")
                             .withClientId("MY_CLIENT_ID")
                             .withClientSecret("MY_CLIENT_SECRET")
                             .withRegion("syd-1")
                             .preferRestOverGrpc(true)   
                             .build()) {

            // The request fails with an UnknownHostException
            camundaClient.newDeployResourceCommand()
                    .addResourceFromClasspath("bpmn/Sign-up process.bpmn").send().join();
        }
```

### Current behavior

The REST request fails with the following error:

```
Exception in thread "main" io.camunda.client.api.command.ClientException: io.camunda.client.api.command.ClientException: java.net.UnknownHostException: syd-1.zeebe.zeebe.camunda.io: Name or service not known
	at io.camunda.client.impl.http.HttpCamundaFuture.unwrapExecutionException(HttpCamundaFuture.java:87)
	at io.camunda.client.impl.http.HttpCamundaFuture.join(HttpCamundaFuture.java:43)
	at io.camunda.example.PlainJavaApplication.main(PlainJavaApplication.java:22)
Caused by: io.camunda.client.api.command.ClientException: java.net.UnknownHostException: syd-1.zeebe.zeebe.camunda.io: Name or service not known
	at io.camunda.client.impl.http.ApiCallback.failed(ApiCallback.java:72)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:166)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$2.failed(InternalAbstractHttpAsyncClient.java:356)
	at org.apache.hc.client5.http.impl.async.AsyncRedirectExec$1.failed(AsyncRedirectExec.java:246)
	at org.apache.hc.client5.http.impl.async.AsyncHttpRequestRetryExec$1.failed(AsyncHttpRequestRetryExec.java:195)
	at org.apache.hc.client5.http.impl.async.AsyncProtocolExec$1.failed(AsyncProtocolExec.java:295)
	at org.apache.hc.client5.http.impl.async.AsyncConnectExec$2.failed(AsyncConnectExec.java:233)
	at org.apache.hc.core5.concurrent.CallbackContribution.failed(CallbackContribution.java:52)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:166)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager$4.failed(PoolingAsyncClientConnectionManager.java:482)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:166)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.nio.DefaultAsyncClientConnectionOperator$1.failed(DefaultAsyncClientConnectionOperator.java:170)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:166)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.nio.MultihomeIOSessionRequester.connect(MultihomeIOSessionRequester.java:118)
	at org.apache.hc.client5.http.impl.nio.DefaultAsyncClientConnectionOperator.connect(DefaultAsyncClientConnectionOperator.java:115)
	at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager.connect(PoolingAsyncClientConnectionManager.java:453)
	at org.apache.hc.client5.http.impl.async.InternalHttpAsyncExecRuntime.connectEndpoint(InternalHttpAsyncExecRuntime.java:226)
	at org.apache.hc.client5.http.impl.async.AsyncConnectExec.doProceedToNextHop(AsyncConnectExec.java:220)
	at org.apache.hc.client5.http.impl.async.AsyncConnectExec.proceedToNextHop(AsyncConnectExec.java:195)
	at org.apache.hc.client5.http.impl.async.AsyncConnectExec.access$000(AsyncConnectExec.java:90)
	at org.apache.hc.client5.http.impl.async.AsyncConnectExec$1.completed(AsyncConnectExec.java:162)
	at org.apache.hc.client5.http.impl.async.AsyncConnectExec$1.completed(AsyncConnectExec.java:151)
	at org.apache.hc.client5.http.impl.async.InternalHttpAsyncExecRuntime$1.completed(InternalHttpAsyncExecRuntime.java:128)
	at org.apache.hc.client5.http.impl.async.InternalHttpAsyncExecRuntime$1.completed(InternalHttpAsyncExecRuntime.java:120)
	at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:148)
	at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager$3$1.leaseCompleted(PoolingAsyncClientConnectionManager.java:336)
	at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager$3$1.completed(PoolingAsyncClientConnectionManager.java:321)
	at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager$3$1.completed(PoolingAsyncClientConnectionManager.java:282)
	at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:148)
	at org.apache.hc.core5.pool.StrictConnPool.fireCallbacks(StrictConnPool.java:401)
	at org.apache.hc.core5.pool.StrictConnPool.lease(StrictConnPool.java:219)
	at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager$3.<init>(PoolingAsyncClientConnectionManager.java:279)
	at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager.lease(PoolingAsyncClientConnectionManager.java:274)
	at org.apache.hc.client5.http.impl.async.InternalHttpAsyncExecRuntime.acquireEndpoint(InternalHttpAsyncExecRuntime.java:115)
	at org.apache.hc.client5.http.impl.async.AsyncConnectExec.execute(AsyncConnectExec.java:150)
	at org.apache.hc.client5.http.impl.async.AsyncExecChainElement.execute(AsyncExecChainElement.java:54)
	at org.apache.hc.client5.http.impl.async.AsyncProtocolExec.internalExecute(AsyncProtocolExec.java:207)
	at org.apache.hc.client5.http.impl.async.AsyncProtocolExec.execute(AsyncProtocolExec.java:172)
	at org.apache.hc.client5.http.impl.async.AsyncExecChainElement.execute(AsyncExecChainElement.java:54)
	at org.apache.hc.client5.http.impl.async.AsyncHttpRequestRetryExec.internalExecute(AsyncHttpRequestRetryExec.java:113)
	at org.apache.hc.client5.http.impl.async.AsyncHttpRequestRetryExec.execute(AsyncHttpRequestRetryExec.java:211)
	at org.apache.hc.client5.http.impl.async.AsyncExecChainElement.execute(AsyncExecChainElement.java:54)
	at org.apache.hc.client5.http.impl.async.AsyncRedirectExec.internalExecute(AsyncRedirectExec.java:111)
	at org.apache.hc.client5.http.impl.async.AsyncRedirectExec.execute(AsyncRedirectExec.java:278)
	at org.apache.hc.client5.http.impl.async.AsyncExecChainElement.execute(AsyncExecChainElement.java:54)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient.executeImmediate(InternalAbstractHttpAsyncClient.java:378)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient.lambda$doExecute$0(InternalAbstractHttpAsyncClient.java:234)
	at org.apache.hc.core5.http.nio.support.BasicRequestProducer.sendRequest(BasicRequestProducer.java:93)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient.doExecute(InternalAbstractHttpAsyncClient.java:208)
	at org.apache.hc.client5.http.impl.async.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:96)
	at org.apache.hc.client5.http.impl.async.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:106)
	at org.apache.hc.client5.http.impl.async.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:115)
	at io.camunda.client.impl.http.HttpClient.sendRequest(HttpClient.java:339)
	at io.camunda.client.impl.http.HttpClient.postMultipart(HttpClient.java:183)
	at io.camunda.client.impl.http.HttpClient.postMultipart(HttpClient.java:163)
	at io.camunda.client.impl.command.DeployResourceCommandImpl.sendRestRequest(DeployResourceCommandImpl.java:250)
	at io.camunda.client.impl.command.DeployResourceCommandImpl.send(DeployResourceCommandImpl.java:223)
	... 1 more
Caused by: java.net.UnknownHostException: syd-1.zeebe.zeebe.camunda.io: Name or service not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52)
	at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1221)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1817)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1149)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1807)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1676)
	at org.apache.hc.client5.http.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:61)
	at org.apache.hc.client5.http.impl.nio.MultihomeIOSessionRequester.connect(MultihomeIOSessionRequester.java:113)
	... 44 more
```

### Expected behavior

I can build a client with the Cloud client builder and send REST requests.  

### Environment

SaaS

### Version

- camunda-client-java: `8.8.0-SNAPSHOT`

### Rootcause

The Cloud client builder sets the wrong REST address: `syd-1.zeebe.zeebe.camunda.io` instead of `syd-1.zeebe.camunda.io`.

Code: [CamundaClientCloudBuilderImpl](https://github.com/camunda/camunda/blob/8cc6c9f84605a698f20bec8990556ca698f42e2d/clients/java/src/main/java/io/camunda/client/impl/CamundaClientCloudBuilderImpl.java#L311-L324)

### Solution ideas

Fix the setting of the REST address in `CamundaClientCloudBuilderImpl`. 

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by megglos**
## Description

Current URL template resulted in invalid host names with a duplicated `zeebe` element as `BASE_ADDRESS` is already `zeebe.camunda.io`.

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #32759

### CODE REVIEW

**Comment by jonathanlukas** [comment]
@megglos to align with the Spring SDK, would it make sense to remove the `zeebe.` from the `BASE_ADDRESS`?

Ref: https://github.com/camunda/camunda/blob/main/clients/spring-boot-starter-camunda-sdk/src/main/resources/modes/saas.yaml#L5

Also, the base address could be configurable, but that would be a new FR.

**Comment by megglos** [comment]
> Also, the base address could be configurable, but that would be a new FR.

Good point, I think while we are here, it's ok to do that right away, so you could connect to different stages as easy as
```
                     CamundaClient
                             .newCloudClientBuilder()
                             ...
                             .withBaseAddress("dev.ultrawombat.com")
...
```

Will amend, if this becomes a rabbithole I can move this into a follow-up still.

**Comment by megglos** [comment]
I actually don't like the name of `baseAddress`/`baseUrl`, it's actually a domain thus introduced it as such. Would you agree @jonathanlukas then I would add it to the sdk config as well and deprecate base-url.

**Comment by jonathanlukas** [comment]
How would you call the property then? `domain`?

**Comment by megglos** [comment]
> How would you call the property then? `domain`?

Yes see the second commit https://github.com/camunda/camunda/pull/35044/files#diff-272c3b6cb211949f4cc942bbd5a3658b6d2599bee3b08f78cb4a5d69fe9ecc42R56-R64

**Review by jonathanlukas — APPROVED** [review]
lgtm.

Thank you for picking up the property naming. I think we found a good solution across the clients.

**Comment by megglos** [comment]
@nicpuppa as this became a joint venture of me doing client changes and @jonathanlukas doing the sdk adaptation, would you be up to do the final review? :D

File: clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/properties/CamundaClientCloudProperties.java [hunk 1]
```diff
@@ -45,14 +48,25 @@ public void setClusterId(final String clusterId) {
     this.clusterId = clusterId;
   }
 
+  @Deprecated
+  @DeprecatedConfigurationProperty(replacement = "camunda.client.cloud.domain")
```
Comment (megglos) [inline clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/properties/CamundaClientCloudProperties.java:52]: For me as a learning, this annotation has no functional impact but only instructs spring to highlight a deprecated prop is used? (so is informational)

In `CamundaClientLegacyPropertiesMappingsLoader` & `CamundaClientPropertiesPostProcessor` we have the actual functional handling based on the `camunda-client-legacy-property-mappings.properties` content, that will load the deprecated value if the replacement is not present, right?

Comment (megglos) [reply clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/properties/CamundaClientCloudProperties.java:52]: @jonathanlukas

Comment (jonathanlukas) [reply clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/properties/CamundaClientCloudProperties.java:52]: >For me as a learning, this annotation has no functional impact but only instructs spring to highlight a deprecated prop is used? (so is informational)

Yes, this adds the details to the generated properties-description json document created by the configuration processor.

>In CamundaClientLegacyPropertiesMappingsLoader & CamundaClientPropertiesPostProcessor we have the actual functional handling based on the camunda-client-legacy-property-mappings.properties content, that will load the deprecated value if the replacement is not present, right?

Also correct. I was looking into writing my own extension to the configuration processor to apply these mappings, but I did not really find the entrypoint...

**Review by nicpuppa — APPROVED** [review]
