### PR TITLE
fix(engine): complete closeFuture when streamprocessor fails

### LINKED ISSUE #8547: Flaky BrokerAdminServiceClusterTest#shouldReportPartitionStatusOnFollowersAndLeader
**Summary**

- How often does the test fail?
  - at least twice
- Does it block your work?
  - no
- Do we suspect that it is a real failure?
  - Don't think so

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
	at app//io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:133)
	at app//io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:108)
	at app//io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:21)
	at app//io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:196)
	at app//io.camunda.zeebe.broker.Broker.lambda$close$0(Broker.java:170)
	at app//io.camunda.zeebe.broker.Broker$$Lambda$1324/0x0000000100880228.accept(Unknown Source)
	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base@17.0.1/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
	at app//io.camunda.zeebe.broker.Broker.lambda$close$1(Broker.java:168)
	at app//io.camunda.zeebe.broker.Broker$$Lambda$1323/0x0000000100880000.run(Unknown Source)
	at app//io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23)
	at app//io.camunda.zeebe.broker.Broker.close(Broker.java:163)
	at app/zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.lambda$after$3(ClusteringRule.java:259)
	at app/zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule$$Lambda$1784/0x0000000100939480.accept(Unknown Source)
	at java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base@17.0.1/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base@17.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.1/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base@17.0.1/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base@17.0.1/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base@17.0.1/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1223)
	at java.base@17.0.1/java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1915)
	at java.base@17.0.1/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:433)
	at java.base@17.0.1/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:687)
	at java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base@17.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base@17.0.1/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base@17.0.1/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
	at app/zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.after(ClusteringRule.java:256)
</pre>
</details>

**Hypotheses**

Didn't dig into it

**Logs**

[Link to the build](https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/remove-zeebe-test/6/)

[Here's a gist, because the logs were too long :smile:](https://gist.github.com/npepinpe/61c776b50f94fe3fcadd53037f82a682)

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

The test failed because the StreamProcessor#close was stuck because the actor failed. The future that the caller waits on was never completed.

To fix it, now when the StreamProcessor actor fails the closeFuture is completed, so any caller that waits for the close is not blocked for ever. This logic is now abstracted into the `Actor`. However many actors have more complex operations during the close, so this is not re-usable for all actors.

## Related issues

closes #8547 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: util/src/main/java/io/camunda/zeebe/util/sched/Actor.java [hunk 1]
```diff
@@ -70,7 +72,7 @@ protected void onActorClosing() {
   }
 
   protected void onActorClosed() {
-    // what ever
+    closeFuture.complete(null);
```
Comment (romansmirnov) [inline util/src/main/java/io/camunda/zeebe/util/sched/Actor.java:75]: Actors that override this method are required to call `super.onActorClosed()` to ensure that the future gets completed accordingly.

For example, the `ExporterDirector` overrides `onActorClosed()` and currently does not call `super.onActorClosed()` (and does not have it's own logic to close itself):
https://github.com/camunda-cloud/zeebe/blob/4f4b36922a73a50283c804690cd8af0bdb29890d/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java#L213-L217

So that with this change, the `ExporterDirectorPartitionTransitionStep` would get stuck here and wait for the completion of the future:
https://github.com/camunda-cloud/zeebe/blob/4f4b36922a73a50283c804690cd8af0bdb29890d/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/steps/ExporterDirectorPartitionTransitionStep.java#L40

I think this is also the reason why the build is failing with some test failures: https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/dd-8547-close-actor-when-failed/2/pipeline/

Also, this change seems to introduce a potential point of failure. Meaning, if someone overwrites the `onActorClosed()` method (and does not implement their own closing mechanism), they always need to ensure that they are calling `super.onActorClosed()`.

File: util/src/main/java/io/camunda/zeebe/util/sched/Actor.java [hunk 2]
```diff
@@ -119,7 +122,7 @@ protected void handleFailure(final Throwable failure) {
   }
 
   public void onActorFailed() {
-    // clean ups
+    closeFuture.complete(null);
```
Comment (romansmirnov) [inline util/src/main/java/io/camunda/zeebe/util/sched/Actor.java:125]: The same here as with `onActorClosed()`, this introduces a potential point of failure, if someone forgets to call `super.onActorFailed()` when overwriting this method.

**Review by romansmirnov — CHANGES_REQUESTED** [review]
@deepthidevaki, sorry for the delay! Just thinking out loud here with regards my inline comments:

1. Maybe we could wrap those methods `onActorClosed()` and `onActorFailed()` and do something like this:
```
private void onActorXWrapper() {
  try {
    onActorX();
  } catch (exception) {
    // do something;
  } finally {
    closeFuture.complete(null);
  }
}
```
That way, we ensure that the future gets always completed and the implementation of `Actor` does not need to care about that concern.

2. To my understanding, there is not a common sense on how the close should behave because it depends on the component/actor which may need to close first some sub-components asynchronously before closing itself. Not sure, if there is something we can build that works in 90% of the case, but yeah... Maybe it is easier to keep that concern to the implementations of the actor and they must ensure that in all cases the future gets closed.

WDYT?

**Comment by deepthidevaki** [comment]
> 2\. To my understanding, there is not a common sense on how the close should behave because it depends on the component/actor which may need to close first some sub-components asynchronously before closing itself. Not sure, if there is something we can build that works in 90% of the case, but yeah... Maybe it is easier to keep that concern to the implementations of the actor and they must ensure that in all cases the future gets closed.

I agree. I will remove the abstraction and move the closing logic to StreamProcessor. As you said, in most cases the abstraction may not be useful and is error-prone.

**Comment by deepthidevaki** [comment]
Thanks @romansmirnov for the review. I have updated the PR.

**Review by romansmirnov — APPROVED** [review]

**Comment by deepthidevaki** [comment]
bros merge
