### PR TITLE
fix: increase tomcat max part count to 50

### LINKED ISSUE #34322: /v2/deployments endpoint fails with >10 files in multipart request
### 

### 

, 

### 

### 

### Description
When deploying resources via the Zeebe client to the `/v2/deployments` endpoint, the request fails with a `500 Internal Server Error` if more than **10 files** are included in the multipart request — even if the files are very small.

This behavior appears to have started recently (noticed on `8.7-SNAPSHOT`, `8.8-SNAPSHOT` and 8.6) 

---

**Error Message:**

```json
{
  "type": "about:blank",
  "status": 500,
  "title": "Filter issue",
  "detail": "Request processing failed: org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request",
  "instance": "/v2/deployments"
}
```

### Steps to reproduce

1. Use ZeebeClient to deploy more than 10 resource files via `/v2/deployments`
2. Observe the 500 Internal Server Error
3. Try again with 10 or fewer files — it works

### Current behavior

Deployment fails with 500 status code

### Expected behavior

The endpoint should either continue supporting more than 10 files (as it did before), or the new limit should be documented and clearly communicated.

### Environment

SaaS & SM

### Version

- Component Version: 8.7.0-SNAPSHOT and  8.8.0-SNAPSHOT, 8.6

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

https://github.com/user-attachments/assets/52e57085-f2ab-4464-82f9-bbc596d6ca4a

### PR DESCRIPTION
**Pull request by abremard**
## Description

When deploying resources via the Zeebe client to the /v2/deployments endpoint, the request fails with a 500 Internal Server Error if more than 10 files are included in the multipart request.
This happens because [Tomcat has a maxPartCount](https://tomcat.apache.org/tomcat-9.0-doc/changelog.html) parameter that limits the total number of parts in a multipart requests. In our version, the default is set to 10. This PR is increasing the default to 50 for our orchestration cluster API. 

## Checklist

- [x] Document that this part count is configurable for customers => I will update the [deployment API](https://github.com/camunda/camunda-docs/blob/337900e1f15def9082db704987d525e43fae0052/versioned_docs/version-8.6/apis-tools/camunda-api-rest/camunda-api-rest-overview.md?plain=1#L31-L44) docs section for 8.6, 8.7 and 8.8
- [x] Double-check if this config can be an env variable (capital case with underscores?) => checked locally with `SERVER_TOMCAT_MAX_PART_COUNT` and the override happens (see [relaxed bindings](https://docs.spring.io/spring-boot/docs/2.0.9.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding))
- [x] Backport to 8.7 and 8.6

## Related issues

closes #34322

### CODE REVIEW

File: dist/src/main/resources/application.properties [hunk 1]
```diff
@@ -66,6 +66,8 @@ management.sanitize.keywords=user,pass,secret,accessKey,accountKey,token,\
 # Multipart file uploads
 spring.servlet.multipart.max-file-size=10MB
 spring.servlet.multipart.max-request-size=10MB
+server.tomcat.max-part-count=50
```
Comment (eppdot) [inline dist/src/main/resources/application.properties:69]: 💭 will this be enough to provide a great customer experience? what happens when the customer has their own `application.properties` already in place? Wouldn't it be nice that with the next patch version this gets automatically set? I don't have a clear idea to implement this, but probably we need a small piece of code that checks if the limit was automatically set via `application.properties` and if not defaults to 50

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/DeployResourceTest.java [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+import io.camunda.zeebe.model.bpmn.BpmnModelInstance;
+import org.junit.jupiter.api.Test;
+
+@MultiDbTest
+public final class DeployResourceTest {
+
+  private static CamundaClient client;
+
+  @Test
+  public void shouldDeployMultipleProcessModels() {
```
Comment (eppdot) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/DeployResourceTest.java]: 💭 do we wanna keep this test? as we know now it's not testing our business logic, but rather a config of a third party library. Thus not sure how much value it brings for the cost it has (maintenance, bit longer runtime, etc.). On the other hand, we make sure we don't hit a regression when the tomcat lib changes their configuration or the like (thus might be unlikely). wdyt?

File: dist/src/main/resources/application.properties [hunk 3]
```diff
@@ -66,6 +66,8 @@ management.sanitize.keywords=user,pass,secret,accessKey,accountKey,token,\
...
+
 #
 # RDBMS extension default properties
 #
```
Comment (eppdot) [inline dist/src/main/resources/application.properties:73]: ❓ are there any other `.properties` files that we should adjust? helm or any other deployments that might bring their own props file? maybe we should raise this in a larger channel to make SM & SaaS aware. (cc @hisImminence)

**Review by eppdot — APPROVED** [review]
I left some thoughts, but they wouldn't be merge blockers as this PR already clearly improves the status quo. 🚀

File: dist/src/main/resources/application.properties (hunk 1 above)
Comment (abremard) [reply dist/src/main/resources/application.properties:69]: That's a good point, a simple solution could be to add spring's `@ConfigurationProperties` which adds a default fallback in-code while keeping the `application.properties` and env variables higher priority compared to `@ConfigurationProperties`.

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/DeployResourceTest.java (hunk 2 above)
Comment (abremard) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/DeployResourceTest.java]: I guess based on the unlikeliness that tomcat changes their config, let's default to removing this test to save us some maintenance and cost

File: dist/src/main/resources/application.properties (hunk 1 above)
Comment (abremard) [reply dist/src/main/resources/application.properties:69]: I tried using `@ConfigurationProperties` to set a default in code, but this does not work as expected because Tomcat is managed internally by Spring Boot, and programmatic property injection is ignored or overridden... 

The cleanest and most reliable approach IMO is to set the property in application.properties, letting Spring Boot handle it through its standard configuration mechanism. I'm making sure to document the config [here](https://github.com/camunda/camunda-docs/pull/6140) for users.

File: dist/src/main/resources/application.properties (hunk 3 above)
Comment (abremard) [reply dist/src/main/resources/application.properties:73]: Asking [here](https://camunda.slack.com/archives/C01H4NG9XDY/p1752461482716279)

**Comment by mschoe** [comment]
@abremard, is QA support required here?

**Comment by abremard** [comment]
> @abremard, is QA support required here?

This was already tested in #34322, see [comment](https://github.com/camunda/camunda/issues/34322#issuecomment-3113593034)
