### PR TITLE
fix(logstreams): retry append on failure

### LINKED ISSUE #3370: Processing stops because sessions of the DistributedLogStreamClient are closed
**Describe the bug**

Lately we observed in our long running test suite that the processing of one partition (eventually most of the partitions) stop processing.

processing-stopped

We saw no broker restart nor leader change at this time.
The only thing we saw at this point in time was the reconfiguration of the DistributedLogPrimitive.
That is the reason why we assumed the session might be closed and the append was not happening afterwards.

If we take a look at the Heartbeat rate we see that at some point only the real heartbeat requests are send, no longer any append requests.

heartbeats

In the log we saw log statements like this:

```
I 2019-11-14T13:29:40.145523760Z zeebe-1 2019-11-14 13:29:40.144 [] [raft-partition-group-raft-atomix-13] ERROR io.zeebe.logstreams - Failed to append block with last event position 1099516985048, retry.
  zeebe-1
I 2019-11-14T13:29:40.145546797Z zeebe-1 java.util.concurrent.CompletionException: io.atomix.primitive.PrimitiveException$ClosedSession: session closed
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.Futures.lambda$null$3(Futures.java:159) ~[atomix-utils-3.2.0-20191112.114214-59.jar:?]
	at io.atomix.utils.concurrent.ThreadPoolContext.lambda$new$0(ThreadPoolContext.java:81) ~[atomix-utils-3.2.0-20191112.114214-59.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: io.atomix.primitive.PrimitiveException$ClosedSession: session closed
	at io.atomix.protocols.raft.session.impl.RaftSessionInvoker.close(RaftSessionInvoker.java:217) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.DefaultRaftSessionClient.lambda$null$0(DefaultRaftSessionClient.java:236) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionState.lambda$setState$0(RaftSessionState.java:221) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionState.setState(RaftSessionState.java:221) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionInvoker$CommandAttempt.accept(RaftSessionInvoker.java:388) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionInvoker$CommandAttempt.accept(RaftSessionInvoker.java:327) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionConnection.handleResponse(RaftSessionConnection.java:282) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionConnection.lambda$sendRequest$7(RaftSessionConnection.java:238) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	... 7 more
  zeebe-1
I 2019-11-14T13:29:40.146362510Z zeebe-1 2019-11-14 13:29:40.145 [] [raft-partition-group-raft-atomix-13] ERROR io.zeebe.logstreams - Failed to append block with last event position 1099516999056, retry.
  zeebe-1
I 2019-11-14T13:29:40.146404536Z zeebe-1 java.util.concurrent.CompletionException: io.atomix.primitive.PrimitiveException$ClosedSession: session closed
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.Futures.lambda$null$3(Futures.java:159) ~[atomix-utils-3.2.0-20191112.114214-59.jar:?]
	at io.atomix.utils.concurrent.ThreadPoolContext.lambda$new$0(ThreadPoolContext.java:81) ~[atomix-utils-3.2.0-20191112.114214-59.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: io.atomix.primitive.PrimitiveException$ClosedSession: session closed
	at io.atomix.protocols.raft.session.impl.RaftSessionInvoker.close(RaftSessionInvoker.java:217) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.DefaultRaftSessionClient.lambda$null$0(DefaultRaftSessionClient.java:236) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionState.lambda$setState$0(RaftSessionState.java:221) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionState.setState(RaftSessionState.java:221) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionInvoker$CommandAttempt.accept(RaftSessionInvoker.java:388) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionInvoker$CommandAttempt.accept(RaftSessionInvoker.java:327) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionConnection.handleResponse(RaftSessionConnection.java:282) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at io.atomix.protocols.raft.session.impl.RaftSessionConnection.lambda$sendRequest$7(RaftSessionConnection.java:238) ~[atomix-raft-3.2.0-20191112.114310-59.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	... 7 more
  zeebe-1
I 2019-11-14T13:29:40.147062892Z zeebe-1 2019-11-14 13:29:40.146 [] [raft-partition-group-raft-atomix-13] ERROR io.zeebe.logstreams - Failed to append block with last event position 1099516999352, retry.
  zeebe-1
```

As you can see in the following code from the `LogStorageAppender`:

```java
  private void appendToPrimitive(byte[] bytesToAppend, long lastEventPosition) {
    actor.submit(
        () -> {
          distributedLog
              .asyncAppend(bytesToAppend, lastEventPosition)
              .whenComplete(
                  (appendPosition, error) -> {
                    if (error != null) {
                      LOG.error(
                          "Failed to append block with last event position {}, retry.",
                          lastEventPosition,
                          error);
                      appendToPrimitive(bytesToAppend, lastEventPosition);
                    } else {
                      actor.run(
                          () -> {
                            appendEntryLimiter.onCommit(lastEventPosition);
                            currentInFlightBytes -= bytesToAppend.length;
                            actor.run(this::peekBlock);
                          });
                    }
                  });
        });
  }
```

The append is retried on error, but `actor.submit` will throw an exception since it is not called in the `ActorThread` it self. This means the retry will fail.

But even if the retry will succeed we would have the problem that it might happen that events are then appended out of order. 

**Example**:

We append `1, 2, 3, 4` and the session close exception will happen for 2 and 3. Then it can happen that we have in the end `1, 4, 2, 3` as appended entries. This might be detected by the `DistributedLogPrimitive`, such that it does not append `2` and `3` to the log storage.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

 The log storage appender will retry on failure. Failure means either
 an exception happened or a negative result was returned.

 The log storage appender will send an index with the append request such
 that the primitive is able to determine whether the requests are in
 order or not. The log appender will query the last index on restart.
 If the primitive detects an inconsistency it will return an negative
 result, such that the log appender retries and eventually the events
 are in order.

This problem was observed due to session timeouts on the primitive client.
This fix https://github.com/zeebe-io/atomix/pull/70 makes it less likely to fail, but it is still possible that is the reason we need to handle this case. 

In the following screenshot we see this fix in a benchmark.

only-append-fix

The the second screenshot both fixes are in use. The processing looks much more stable with these fixes.

both-fixes

## Related issues

closes #3370 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java [hunk 1]
```diff
@@ -181,7 +190,20 @@ public String getName() {
 
   @Override
   protected void onActorStarting() {
+    try {
+      appendIndex = distributedLog.getLastAppendIndex();
```
Comment (deepthidevaki) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java]: Doesn't this block the current thread? Can we use async operation for this?

File: logstreams/src/test/java/io/zeebe/distributedlog/DistributedLogTest.java [hunk 2]
```diff
@@ -105,6 +112,52 @@ public void shouldReplicateMultipleEvents()
...
+              latch.countDown();
+              return i.callRealMethod();
+            })
+        .doCallRealMethod()
+        .when(node1.getSpy(PARTITION_ID))
+        .asyncAppend(eq(3L), any(byte[].class), anyLong());
+
+    // when
+    final Event event1 = writeEvent("record1");
+    Thread.sleep(100L); // to get events in different chunks
```
Comment (deepthidevaki) [inline logstreams/src/test/java/io/zeebe/distributedlog/DistributedLogTest.java]: Instead of sleep, can we do something like 
`verify(node1.getSpy(PARTITION_ID), timeout(1000).times(1)).asyncAppend(1L, any(), any());`

File: logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java [hunk 3]
```diff
@@ -236,19 +271,35 @@ public void backup(BackupOutput backupOutput) {
...
 
   @Override
   public void restore(BackupInput backupInput) {
+    LOG.debug("Restoring primitive of partition {}", partitionId);
     final long backupPosition = backupInput.readLong();
+    final long backLastAppendIndex = backupInput.readLong();
+    lastAppendIndex = backLastAppendIndex;
 
     if (lastPosition < backupPosition) {
+      // We had a fail over or the follower just lags behind.
```
Comment (deepthidevaki) [inline logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: A minor thing: failover doesn't cause a restore.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Looks good. Some small comments.

File: logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java [hunk 4]
```diff
@@ -175,9 +177,32 @@ public long append(String nodeId, long commitPosition, byte[] blockBuffer) {
...
+    // if the lastAppendIndex + 1 is less then the appendIndex, we missed some events
+    if (lastAppendIndex + 1 < appendIndex) {
+      logger.trace(
+          "We received an event out of order. Last append index {} and try to append index {}, will reject this event.",
+          lastAppendIndex,
+          appendIndex);
+      return -lastAppendIndex;
+    }
+
+    if (commitPosition <= lastPosition && lastAppendIndex <= appendIndex) {
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: Here I was not 100% sure if this can even happen

File: logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java (hunk 1 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java]: Yes my first thought was to block the thread to not start before (servicontainer like start) but this makes here in the model no sense. I think i should use runBlockCurrentPhase or something similar. You're right

File: logstreams/src/test/java/io/zeebe/distributedlog/DistributedLogTest.java (hunk 2 above)
Comment (Zelldon) [reply logstreams/src/test/java/io/zeebe/distributedlog/DistributedLogTest.java]: This wouldnt split the blocks, since the appender tries to consume as many as possible from the dispatcher

File: logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java (hunk 3 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: Sure? As we discussed today? Follower already received the snapshot but didnt reached the index yet?

File: logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: Actually it worked fine before on the benchmark without this. But the Distributed Recovery test failed. With this addition the benchmark fails 😅

[the remark this answers is not in the document]
Comment (deepthidevaki) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: What we want is that `lastAppendIndex` is updated to the appendIndex of last append. When we use  `lastAppendIndex <= appendIndex`, `lastAppendIndex` will be `appendIndex + 1`. It wouldn't matter if, instead of `lastAppendIndex++`,  we just assign the value `lastAppendIndex = appendIndex`.

File: logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java (hunk 3 above)
Comment (deepthidevaki) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: If the follower is fast enough to apply the operations, then it never have to install the snapshot. The case we discussed today is when the follower is slow in applying and then it receives a snapshot. In that case, it will always install the snapshot whether a fail-over happens or not.

Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: so it just when someone lags behind :D

File: logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: So do you mean in general `lastAppendIndex = appendIndex.` or just for this case (i think I had this once)? Which solution you would like to have :smile:

[the remark this answers is not in the document]
Comment (deepthidevaki) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: If it is possible to use everywhere `lastAppendIndex = appendIndex`, it would be better. It is more understandable for me. But, just here would also be enough :slightly_smiling_face:

[the remark this answers is not in the document]
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: Agree I will verify that

File: logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java (hunk 3 above)
Comment (deepthidevaki) [reply logstreams/src/main/java/io/zeebe/distributedlog/impl/DefaultDistributedLogstreamService.java]: Yes :smile:

**Comment by Zelldon** [comment]
Thanks for your review @deepthidevaki  i applied some requested changes and also did some minor improvements. Please have a look

File: logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java [hunk 5]
```diff
@@ -110,44 +115,56 @@ private void appendBlock() {
...
+                      currentInFlightBytes -= bytesToAppend.length;
+                      actor.run(this::peekBlock);
                     }
                   });
-        });
+            });
   }
 
-  /* Iterate over the events in buffer and find the position of the last event */
+  /* Iterate over the even1ts in buffer and find the position of the last event */
```
Comment (deepthidevaki) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java]:
```suggestion
  /* Iterate over the events in buffer and find the position of the last event */
```

File: logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java [hunk 6]
```diff
@@ -181,7 +198,35 @@ public String getName() {
...
+    distributedLog
+        .getLastAppendIndex()
+        .thenAccept(appendIndexFuture::complete)
+        .exceptionally(
+            t -> {
+              appendIndexFuture.completeExceptionally(t);
+              return null;
+            });
+
+    actor.runOnCompletionBlockingCurrentPhase(
```
Comment (deepthidevaki) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java]: This means, `onActorStarted()` is called only after this callback is executed. Right?

**Review by deepthidevaki — COMMENTED** [review]
:+1:

**Review by deepthidevaki — APPROVED** [review]

File: logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java (hunk 6 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/LogStorageAppender.java]: yes exactly

**Comment by Zelldon** [comment]
Bors r+
