### PR TITLE
Align permission types with permissions document

### LINKED ISSUE #24612: Align permission types with permissions document
<h2>Description</h2>

At this moment Zeebe only support general permission types (`CREATE`, `READ`, `UPDATE`, `DELETE`), with a few exceptions (`DELETE_PROCESS`, `DELETE_FORM`, `DELETE_DRD`). 

[This document](https://docs.google.com/document/d/1ikxw9ARCv-MBwASnj7WhW5uHCndCRk2B35xi-cB2N0M/edit?tab=t.0#heading=h.m2zg2f7pb01i) (internal) described the permission types as more specific. An example would be `CREATE_USER_TASK` or `CREATE_PROCESS_INSTANCE`. We must align the authorization checks in Zeebe with the permission types (highlighted in gray) in this document.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

[Link to document (internal)](https://docs.google.com/document/d/1ikxw9ARCv-MBwASnj7WhW5uHCndCRk2B35xi-cB2N0M/edit?tab=t.0)

This PR changes the permissionTypes of the authorization checks we're doing in Zeebe and aligns them with what's written in the document.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #24612

### CODE REVIEW

File: security/security-core/src/main/java/io/camunda/zeebe/protocol/record/value/PermissionType.java [hunk 1]
```diff
@@ -9,10 +9,17 @@
...
 public enum PermissionType {
   CREATE,
+  CREATE_PROCESS_INSTANCE,
+  CREATE_DECISION_INSTANCE,
+
   READ,
-  READ_INSTANCE,
+  READ_PROCESS_INSTANCE,
   READ_USER_TASK,
+
```
Comment (houssain-barouni) [inline security/security-core/src/main/java/io/camunda/zeebe/protocol/record/value/PermissionType.java:18]: @remcowesterhoud it is still missing 
```
READ_DECISION_DEFINITION
READ_DECISION_INSTANCE
UPDATE_DECISION_INSTANCE
CREATE_DECISION_INSTANCE
DELETE_DECISION_INSTANCE
```

Comment (remcowesterhoud) [reply security/security-core/src/main/java/io/camunda/zeebe/protocol/record/value/PermissionType.java:18]: I only fixed the ones that were being used for verification in Zeebe. I assume anyone who needs others will add them when they require them.

**Review by Ben-Sheppard — APPROVED** [review]
Looking at the doc and the changes here they look aligned, I agree that when we need the next permissions they can be added then.
