### PR TITLE
fix: do not retry deserializing a record in ExporterDirector

### LINKED ISSUE #31919: Deserialization errors in Exporter are retried to aggressively
### 

### 

, , , , , 

### 

### 

### Description

When the `ExporterDirector` fails to deserialize a record, it immediately retries without backoff. For many errors, this does not make sense at all and we should, at most, retry with exponential backoff.

### Steps to reproduce

In this specific case, the errors were triggered by an upgrade of snapshot versions where we introduced backwards incompatible changes.

### Current behavior

The director keeps retrying, each time running into an exception such as:
```
 java.lang.RuntimeException: Could not deserialize object [RoleRecord]. Deserialization stuck at offset 63 of length 63
	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:48) ~[zeebe-msgpack-value-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LoggedEventImpl.readValue(LoggedEventImpl.java:106) ~[zeebe-logstreams-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.records.RecordValues.readRecordValue(RecordValues.java:34) ~[zeebe-stream-platform-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.RecordExporter.wrap(RecordExporter.java:46) ~[zeebe-broker-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$exportEvent$19(ExporterDirector.java:642) ~[zeebe-broker-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:51) ~[zeebe-scheduler-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:84) [zeebe-scheduler-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:43) [zeebe-scheduler-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125) [zeebe-scheduler-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127) [zeebe-scheduler-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104) [zeebe-scheduler-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224) [zeebe-scheduler-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
Caused by: java.lang.RuntimeException: Property 'roleId' has no valid value
	at io.camunda.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:131) ~[zeebe-msgpack-value-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:42) ~[zeebe-msgpack-value-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
```

### Expected behavior

- No immediate retries without backoff
- No retries of errors during deserialization

### Environment

SaaS & SM

### Version

- Snapshot

### Rootcause

- No backoff used
- No error handling for errors during deserialization

### Solution ideas

- Exponential backoff for retries
- Handle deserialization errors by not retrying

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

[Error Report](https://console.cloud.google.com/errors/detail/COHDsen37-GgUg;service=zeebe;time=P7D;locations=global?inv=1&invt=AbxL3g&project=camunda-saas-int)

### PR DESCRIPTION
**Pull request by entangled90**
## Description
Record deserialization was endlessly retry.
Considering that retrying to deserialize a record should not succeed, it's better to avoid retrying it altogether. 

Testing that no retry is performed is a bit difficult, as records are not really serialized in `ExporterDirectorTest`, but just saved in a list. 
There was no test beforehand testing the retries.
If there is a simple way to test it, I will add a test case

## Related issues
closes #31919

### CODE REVIEW

**Review by ChrisKujawa — COMMENTED** [review]
I would really like to see a regression test here. Can we for example do some AT, where we do some processing, stop, mess up the log or some records and then restart. The partition should fail 🤔 Or can we improve the ExporterDirector so we can pass in a RecordExporter, allowing us to better test this? 🤔

**Comment by entangled90** [comment]
In the end it was much faster to spy on the `RecordExporter` and easier to verify what was actually invoked :shrug:

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java [hunk 1]
```diff
@@ -482,6 +485,25 @@ public void shouldRetryExportingOnException() {
...
+        .untilAsserted(() -> assertThat(recordExporterRef.get()).isNotNull());
+    final var recordExporter = recordExporterRef.get();
+    doThrow(new RuntimeException("deserialization exception")).when(recordExporter).wrap(any());
+
+    final long eventPosition1 = writeEvent();
+
+    verify(recordExporter, timeout(10000))
+        .wrap(argThat(evt -> evt.getPosition() == eventPosition1));
+    verifyNoMoreInteractions(recordExporter);
+  }
```
Comment (ChrisKujawa) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java]:
```suggestion
  @Test
  public void shouldNotRetryExportingOnDeserializationException() {
    // given
    final var recordExporterRef = new AtomicReference<RecordExporter>();
    rule.startExporterDirector(
        exporterDescriptors,
        ExporterPhase.EXPORTING,
        recordExporter -> failingRecordExporter(recordExporter, recordExporterRef));
    Awaitility.await("exporter director has started")
        .untilAsserted(() -> assertThat(recordExporterRef.get()).isNotNull());
    final var recordExporter = recordExporterRef.get();
    doThrow(new RuntimeException("deserialization exception")).when(recordExporter).wrap(any());

    // when
    final long eventPosition1 = writeEvent();

    // then
    verify(recordExporter, timeout(10000))
        .wrap(argThat(evt -> evt.getPosition() == eventPosition1));
    verifyNoMoreInteractions(recordExporter);
  }
```

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java [hunk 2]
```diff
@@ -114,9 +123,9 @@ public ExporterDirector(
             .collect(Collectors.toCollection(ArrayList::new));
     metrics = new ExporterMetrics(meterRegistry);
     metrics.initializeExporterState(exporterPhase);
-    recordExporter = new RecordExporter(metrics, containers, partitionId, clock);
+    recordExporter =
+        recorderExporter.apply(new RecordExporter(metrics, containers, partitionId, clock));
```
Comment (ChrisKujawa) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java:127]: 👍🏼 As the exporter is so complicated to construct, we just give the possibility to exten/modify it via the function 👍🏼 I was first wondering why we not "simply" pass the record exporter in, but I understand now.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterRule.java [hunk 3]
```diff
@@ -107,6 +108,13 @@ public void startExporterDirector(final List<ExporterDescriptor> exporterDescrip
 
   public void startExporterDirector(
       final List<ExporterDescriptor> exporterDescriptors, final ExporterPhase phase) {
+    startExporterDirector(exporterDescriptors, phase, Function.identity());
+  }
+
+  public void startExporterDirector(
+      final List<ExporterDescriptor> exporterDescriptors,
+      final ExporterPhase phase,
+      final Function<RecordExporter, RecordExporter> recordExporter) {
```
Comment (ChrisKujawa) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterRule.java:117]: ❓ But here we could for simplicity simply accept the record exporter? As in tests it would be mostly an mock? Which we can then use to replace the real one? Wdyt?

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java [hunk 4]
```diff
@@ -482,6 +485,25 @@ public void shouldRetryExportingOnException() {
...
+    Awaitility.await("exporter director has started")
+        .untilAsserted(() -> assertThat(recordExporterRef.get()).isNotNull());
+    final var recordExporter = recordExporterRef.get();
+    doThrow(new RuntimeException("deserialization exception")).when(recordExporter).wrap(any());
+
+    final long eventPosition1 = writeEvent();
+
+    verify(recordExporter, timeout(10000))
+        .wrap(argThat(evt -> evt.getPosition() == eventPosition1));
+    verifyNoMoreInteractions(recordExporter);
```
Comment (ChrisKujawa) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java:508]: 🔧 \ ❌ I think we should validate whether the director is now in a failed state.

**Review by ChrisKujawa — APPROVED** [review]
Thanks 👍🏼 cool that we have a test now 👍🏼

**Comment by npepinpe** [comment]
Merging so we can release tomorrow, but let's follow up on the comments immediately in subsequent PRs :+1:

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterRule.java (hunk 3 above)
Comment (entangled90) [reply zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterRule.java:117]: My idea was that we could just spy on the real instance, so instead of building a mock you can just spy on a method for example.

**Comment by entangled90** [comment]
It failed to merge, is it too late for the release?

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java (hunk 4 above)
Comment (entangled90) [reply zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java:508]: Good point, I think it was not actually handled correctly, at least the `HealthReport`. Should we mark it as DEAD or UNHEALTHY? I would say DEAD since there is little way out of this exception.

Comment (entangled90) [reply zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java:508]: I see that other exceptions are handled through `onFailure()` which fails the actor, should we we use this callback as well here?

**Comment by entangled90** [comment]
Applied suggested changes and update the `HealthReport` to DEAD. It was previously marked as HEALTHY. 
Added checks on the `ExporterPhase` as well

**Review by ChrisKujawa — APPROVED** [review]
