### PR TITLE
Complete start/close futures when an actor fails

### LINKED ISSUE #8302: Unhealthy partition in long running benchmark
**Describe the bug**

Partition 1 is unhalthy.

Observed in benchmark on non-preemptiable nodes: http://35.189.240.202/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=release-1-3-alpha1&var-pod=All&var-partition=All

**Environment:**
- Benchmark running on non-premptible nodes
 - Zeebe Version: 1.3.0.alpha1

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

When explicitly failing an actor, we want to ensure that anyone waiting on its start and/or close futures is notified that these will never complete. We complete the start future exceptionally on failure, and the close future successfully. This is because a caller may want to react differently if the actor did not start correctly, but most likely does not care if it did not close correctly.

Hopefully this helps reduce the number of deadlocks where an actor is waiting on another actor to start/close and it never does.

## Related issues

related to #8302

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: scheduler/src/main/java/io/camunda/zeebe/scheduler/ActorTask.java [hunk 1]
```diff
@@ -500,8 +505,21 @@ public void insertJob(final ActorJob job) {
...
+    if (previousPhase == ActorLifecyclePhase.FAILED) {
+      return;
+    }
+
+    if (previousPhase == ActorLifecyclePhase.STARTING) {
+      startingFuture.completeExceptionally(error);
+    }
+
+    if (previousPhase != ActorLifecyclePhase.CLOSED) {
+      closeFuture.complete(null);
```
Comment (deepthidevaki) [inline scheduler/src/main/java/io/camunda/zeebe/scheduler/ActorTask.java:520]: :thought_balloon: Since closeFuture is completed in multiple places now, I was wondering if we ever try to complete already completed future. I guess not, but just want to think it aloud.

File: scheduler/src/test/java/io/camunda/zeebe/scheduler/lifecycle/ActorLifecyclePhasesTest.java [hunk 2]
```diff
@@ -351,4 +352,137 @@ public void onActorStarted() {
...
+            List.of(
+                ActorLifecyclePhase.STARTING,
+                ActorLifecyclePhase.STARTED,
+                ActorLifecyclePhase.CLOSE_REQUESTED,
+                ActorLifecyclePhase.CLOSING));
+    assertThat(closeFuture).failsWithin(Duration.ofSeconds(1));
+  }
+
+  @Test
+  public void shouldCompleteCloseFutureWhenFailingOnClosing() {
```
Comment (deepthidevaki) [inline scheduler/src/test/java/io/camunda/zeebe/scheduler/lifecycle/ActorLifecyclePhasesTest.java:413]: :x: For the sake of completion, we should also add test for "close_requested" phase. `shouldCompleteCloseFutureWhenFailingOnCloseRequested` and `shouldCompleteCloseFutureWhenExceptionOnCloseRequested`

**Review by deepthidevaki — APPROVED** [review]
:rocket: LGTM. Please add the suggested tests. No need for another review.

File: scheduler/src/test/java/io/camunda/zeebe/scheduler/lifecycle/ActorLifecyclePhasesTest.java (hunk 2 above)
Comment (npepinpe) [reply scheduler/src/test/java/io/camunda/zeebe/scheduler/lifecycle/ActorLifecyclePhasesTest.java:413]: Interestingly, if you throw an exception in close requested, we will keep going to `closing` then `closed`. OTOH this seems acceptable, though maybe a little strange that here it doesn't short circuit the lifecycle (e.g. throwing an exception in closing means you stop there).

Comment (deepthidevaki) [reply scheduler/src/test/java/io/camunda/zeebe/scheduler/lifecycle/ActorLifecyclePhasesTest.java:413]: hmm.. interesting. I thought it will go to FAIL.

Comment (npepinpe) [reply scheduler/src/test/java/io/camunda/zeebe/scheduler/lifecycle/ActorLifecyclePhasesTest.java:413]: If you `fail` then it does. But if you just throw an exception it keeps going. It might be what I changed here, i.e. that we only handle failures/go to fail in STARTED when an exception is thrown. I can add CLOSE_REQUESTED as well, if that's the expected behavior.

Comment (npepinpe) [reply scheduler/src/test/java/io/camunda/zeebe/scheduler/lifecycle/ActorLifecyclePhasesTest.java:413]: Actually, come to think of it, should we not treat CLOSE_REQUESTED and CLOSING the same in this instance?

Comment (deepthidevaki) [reply scheduler/src/test/java/io/camunda/zeebe/scheduler/lifecycle/ActorLifecyclePhasesTest.java:413]: Yes. I think so. In `ActorTask::onFailure` we are not currently handling it CLOSE_REQUESTED. But it should be.

**Comment by deepthidevaki** [comment]
> I'm on the fence about backporting this. On one hand, it may help resolve bugs - on the other, changes to the actor scheduler are always, hm, touchy. I'm leaning towards backporting them, but I'd like to hear your thoughts.

Sorry. Didn't see this comment.

I think we should backport them.

**Review by deepthidevaki — APPROVED** [review]
:rocket:

**Comment by npepinpe** [comment]
bors merge
