### PR TITLE
fix(engine): cannot resolve output mapping incident on a none end event

### LINKED ISSUE #12833: Cannot resolve output mapping incident on a none end event
**Describe the bug**

There was an incident in one of the chaos test models, where a none end event had an output mapping referencing a non-existent variable `source` to be mapped to `target`. I resolved the incident by adding a dummy variable (the mapping should not have been there anyway), but then the process was stuck on the none end event.

See https://bru-2.operate.camunda.io/eeef5734-cfd6-47a5-a2ed-5fe13269e589/processes/2251799815205221

**To Reproduce**

Add the following test case to `io.camunda.zeebe.engine.processing.incidentOutputMappingIncidentTest`:

```java
          {
            "None end event",
            ENGINE
                .deployment()
                .withXmlResource(
                    Bpmn.createExecutableProcess(PROCESS_ID)
                        .startEvent()
                        .endEvent("endEventId", b -> b.zeebeOutputExpression("foo", "bar"))
                        .done()),
            "endEventId",
            false
          },
```

**Expected behavior**

I can resolve incidents on a none end event.

**Environment:**
- Zeebe Version: 8.2.3
- Configuration: SaaS - G3 S

### PR DESCRIPTION
**Pull request by skayliu**
## Description

In [PR#10618](https://github.com/camunda/zeebe/pull/10618), we add the `apply output mappings for none end events` feature for the `none end events` on  `onActive()` method.

It's will produce incident when a none end event had an output mapping referencing a non-existent variable `source` to be mapped to `target` and stuck the process.

To fix this, we need to move the `variableMappingBehavior.applyOutputMappings()` from on `onActivate()` to `onComplete()`, because incident resolution will attempt to complete the end event while that method was unimplemented.

## Related issues

closes #12833 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by skayliu** [comment]
Hey, @korthout. Please take a moment to check this out, When you have time. 🙇

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @skayliu 👏 

Clean solution! LGTM 👍 

❌ The pull request description and the commit message don't describe the change and how the change resolves the bug. Instead, the pull request description and the commit message describe how the bug was detected. Please change the descriptions to clarify how this resolves the bug. I'm strict on this, because I believe such descriptions may help future readers of our code.

**Comment by skayliu** [comment]
> Thanks @skayliu 👏
> 
> Clean solution! LGTM 👍
> 
> ❌ The pull request description and the commit message don't describe the change and how the change resolves the bug. Instead, the pull request description and the commit message describe how the bug was detected. Please change the descriptions to clarify how this resolves the bug. I'm strict on this, because I believe such descriptions may help future readers of our code.

@korthout Sorry about that, I've changed the pull request description and the commit message, please review agian.🙇

**Review by korthout — APPROVED** [review]
Thank you @skayliu ❤️ 

LGTM 👍 

I'll backport it to 8.2 as well since the bug exists on that version too.

bors merge

**Comment by korthout** [comment]
@skayliu It appears that we overlooked a test case: `MultiInstanceSubProcessTest.shouldActivateAllElementsOfSubProcess`

On lines 130-148, it attempts to verify exported records of a sub process and a none end event. It does so looking at both commands and events. However, we just changed the records for none end event (there is now a complete command added).

Tests should not verify the commands, but only the events produced in a certain scenario. That is because events are the actual behavior that happened, while commands are just requests to do something (these may be rejected).

Let's adjust that test case to verify only events: 
```java
RecordingExporter.processInstanceRecords()
    .onlyEvents()
    ...
    // remove the commands from the containsExactly
```

File: engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityInterruptionTest.java [hunk 1]
```diff
@@ -102,13 +102,14 @@ public void shouldTriggerBoundaryEventIfChildIsCompleting() {
...
+                .onlyEvents()
                 .betweenProcessInstance(processInstanceKey)
                 .processInstanceRecords())
         .extracting(r -> tuple(r.getValue().getBpmnElementType(), r.getIntent()))
         .containsSubsequence(
-            tuple(BpmnElementType.CALL_ACTIVITY, ProcessInstanceIntent.TERMINATE_ELEMENT),
             tuple(BpmnElementType.CALL_ACTIVITY, ProcessInstanceIntent.ELEMENT_TERMINATING),
-            tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.ELEMENT_COMPLETED),
+            tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.ELEMENT_TERMINATING),
+            tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.ELEMENT_TERMINATED),
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/CallActivityInterruptionTest.java:112]: 💭 This failing test case made me wonder why it failed at all. It failed because the child PROCESS was ELEMENT_COMPLETED, but now it is ELEMENT_TERMINATED. Why is that the case?

Well, the COMPLETE_ELEMENT command written on line 95 sets in motion the completion of the child process in several steps:
- first completing the task
- then activating and completing the end event
- and finally completing the process. 

💡 Simultaneously, the Timer TRIGGER command sets in motion an interruption, also in several steps. However, the completion of the child process takes more steps now, because the End Event is no longer activated and completed in a single step but instead in an additional step. This is why the Process does not make it in time to be completed and instead is terminated.

❌ The test is called `shouldTriggerBoundaryEventIfChildIsCompleting` which makes me wonder whether the test is simply no longer valid in its current form. The child is not completing when the boundary event triggers. 

💭 However, setting up this scenario in a test is really difficult. I have managed through some very hacky code that I'm not sure we want to have in our test code base.

🔧 I want to propose a different solution:

Let's not write `COMPLETE_ELEMENT` for End Event, but let's keep the `onComplete()` method implemented. The `onActivate()` can be implemented like:

```java
public void onActivate(final ExecutableEndEvent element, final BpmnElementContext activating) {
  final var activated = stateTransitionBehavior.transitionToActivated(activating);
  final var completing = stateTransitionBehavior.transitionToCompleting(activated);
  onComplete(element, completing);
}
```

This also requires a small change to the `OutputMappingIncidentTest` lines 137-142:
```java
final var failureElementInstance =
    RecordingExporter.processInstanceRecords()
        .withElementId(elementId)
        .withIntent(ProcessInstanceIntent.ELEMENT_COMPLETING)
        .withProcessInstanceKey(processInstanceKey)
        .getFirst();
```

💭 This way, we can avoid having to adjust any test cases. Note that we should reconsider the `CallActivityInterruptionTest` at some point because it's hard to set up this test scenario. But let's keep that out of scope for now.

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks for your changes @skayliu 🚀 

👍 I like what you did to most of the test cases. Let's keep those changes for all except the `CallActivityInterruptionTest` and the `EscalationEventTest`.

❌ The `CallActivityInterruptionTest` is not correct anymore, but it's difficult to improve.

🔧 I suggest we take a pragmatic solution. Please have a look at my suggestion to resolve this problem. 

🙇 Let me know if you have any questions.

**Comment by skayliu** [comment]
> 👍 I like what you did to most of the test cases. Let's keep those changes for all except the `CallActivityInterruptionTest` and the `EscalationEventTest`.
> 
> ❌ The `CallActivityInterruptionTest` is not correct anymore, but it's difficult to improve.
> 
> 🔧 I suggest we take a pragmatic solution. Please have a look at my suggestion to resolve this problem.
> 
> 🙇 Let me know if you have any questions.

Hi, @korthout, I've applied you suggestion, i've never think of this solution, that's a new one to me, thank you very much.

**Comment by skayliu** [comment]
-> ❌You have commit messages with errors, body's lines must not be longer than 120 characters [body-max-line-length]

So let's cut the commit messages body's length.

**Review by korthout — APPROVED** [review]
Thanks for all the great work on this @skayliu 👏 

LGTM 👍 

bors merge
