### PR TITLE
Fix default user delete default tenant

### LINKED ISSUE #32340: [Tenants] Demo user cannot delete <default> tenant
### 

### 

### 

### 

### Description

Demo user cannot delete <default> tenant

### Steps to reproduce

1. try to delete default tenant
2. confirm deletion 
3. error is shown: 
`Command 'DELETE' rejected with code 'PROCESSING_ERROR': Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=TENANT, intent=DELETE, authorization=AuthInfo{format=UNKNOWN, authData=, claims={user_token_nonce=68o8jAljxhUC-QWwhJtZc4gFchgxWvKuYxxWZZz9vTI, authorized_username=demo, user_token_azp=core, user_token_typ=ID, user_token_aud=[core], user_token_acr=0, user_token_sid=797bc988-8958-4bd5-8584-fc37b1f4cabc, user_token_at_hash=90Z47vf_dygcZJRUuTuKHA, user_token_email_verified=false, user_token_name=Demo, user_token_sub=fe57ba65-4477-40aa-ab56-1437a1f4e316, user_token_preferred_username=demo, user_token_family_name=Demo, user_token_jti=977bdbbe-038a-4d2f-9425-ed47653a24d2}}}, value={"tenantKey":2251799813685253,"tenantId":"<default>","name":"Default","description":"","entityId":"","entityType":"UNSPECIFIED"}}' without errors, but exception occurred with message 'Expected to remove entity with id rpa and type ROLE from tenant <default>, but the type is not supported.'.`

### Current behavior

The text in the modal is malformed and user cannot delete default tenant.

Image

### Expected behavior

Demo user should be able to delete default tenant.

### Environment

SM

### Version

https://maryamtest.ci.distro.ultrawombat.com/core/identity/tenants

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links
UI issue - https://github.com/camunda/camunda/issues/32377
_No response_

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Allow the TenantDeleteProcessor to be able to delete all member entities from its membership list.

ℹ️ Note: this PR is based on https://github.com/camunda/camunda/pull/32647. However, the related issue seems to be fixed already, so we can merge this PR without waiting on the base one.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #32340

### CODE REVIEW

**Comment by koevskinikola** [comment]
Hey @remcowesterhoud let me know if you don't have the time to review this PR.

**Comment by remcowesterhoud** [comment]
> Hey @remcowesterhoud let me know if you don't have the time to review this PR.

Depends on when you need it. This is my last day this week and next Monday I'm medic. So realistically I can probably it review on Tuesday next week 😅

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/tenant/DeleteTenantAuthorizationTest.java [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+    // when
+    engine.tenant().deleteTenant(tenantId).delete(user.getUsername());
+
+    // then
+    assertThat(
+            RecordingExporter.tenantRecords()
+                .withTenantId(tenantId)
+                .withIntent(TenantIntent.DELETED)
+                .count())
+        .isOne();
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/tenant/DeleteTenantAuthorizationTest.java]: 🔧 We should change this assertion so it breaks out of the 5 second wait. Since we are collecting a count and checking it's 1, how about using exists() and true?

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/tenant/DeleteTenantAuthorizationTest.java [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+        .withPermissions(permissionType)
+        .withOwnerId(user.getUsername())
+        .withOwnerType(AuthorizationOwnerType.USER)
+        .withResourceType(authorization)
+        .withResourceId(resourceId)
+        .create(DEFAULT_USER.getUsername());
+  }
+
+  private TenantRecordValue createTenant(final String tenantId) {
+    return engine.tenant().newTenant().withTenantId(tenantId).create().getValue();
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/tenant/DeleteTenantAuthorizationTest.java:139]: ❓ I'm confused why we don't need the default user to create the tenant 🤔 Aren't we unauthorized otherwise?

Comment (remcowesterhoud) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/tenant/DeleteTenantAuthorizationTest.java:139]: Ah it's cause it's considered an internal command, that's why it works.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/util/client/TenantClient.java [hunk 3]
```diff
@@ -336,6 +336,7 @@ public static class TenantDeleteClient {
     private final CommandWriter writer;
     private final TenantRecord tenantRecord;
     private Function<Long, Record<TenantRecordValue>> expectation = SUCCESS_SUPPLIER;
+    private final boolean expectRejection = false;
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/util/client/TenantClient.java]: 🔧 This is unused and can safely be removed.

**Review by remcowesterhoud — APPROVED** [review]
Nice work 👍 Just some minor stuff.
