### PR TITLE
fix: only update the batch operation list view field if the id is not already present

### LINKED ISSUE #44423: Non unique batchOperationIds in operate-list-view
### 

### 

### 

### 

### Description

Batch operation IDs stored in `operate-list-view` index for Process Instance records are represented as a `List`, meaning that you can get duplicate ids in the flushed document. As seen in the screenshot, there are ~12k operation ids. Expanding this JSON array contains the same id on all entries.

Engine replaying can have this side effect.

Image

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Current behavior

Batch operation IDs can be duplicated in the Process Instance entities.

### Expected behavior

Secondary storage entries for `operate-list-view` and Process Instance entities should not contain duplicate ids.

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- Component Version: 8.8

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

Side effect of: https://github.com/camunda/camunda/issues/44356

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by RomanJRW**
## Description

The list view `batchOperations` field is a list that has no consistent guard against duplicate entries being added to the list (see attached issue). This PR checks the existence of a given batch operation ID, only adding it to the record if it does not already exist.

Scope:
- Fixing old records: This would require us to _always_ check for whether or not the field needs fixing, so this is not in scope
- Handling concurrent writes: the retry handling should ensure that concurrent writes are handled already and we don't risk further duplicated IDs getting written
- RDBMS: I don't think the same problem exists there, so the change is only necessary for ES/OS

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #44423

### CODE REVIEW

**Comment by RomanJRW** [comment]
@mustafadagher: I couldn't find an easy way to test this as we are mostly covered with Unit Tests where painless is not really relevant. Do you know of any existing ITs that are already checking the e2e batch operation logic, including what gets written to ES/OS?

File: operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/writer/BatchOperationWriter.java [hunk 1]
```diff
@@ -200,7 +200,7 @@ public BatchOperationEntity scheduleSingleOperation(
       final String script =
           "if (ctx._source.batchOperationIds == null){"
               + "ctx._source.batchOperationIds = new String[]{params.batchOperationId};"
-              + "} else {"
+              + "} else else if (!ctx._source.batchOperationIds.contains(params.batchOperationId)) {"
```
[the remark this answers is not in the document]
Comment (mustafadagher) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/writer/BatchOperationWriter.java]: good catch

**Comment by mustafadagher** [comment]
> @mustafadagher: I couldn't find an easy way to test this as we are mostly covered with Unit Tests where painless is not really relevant. Do you know of any existing ITs that are already checking the e2e batch operation logic, including what gets written to ES/OS?

@RomanJRW we have some batch operation ITs here https://github.com/camunda/camunda/tree/main/qa/acceptance-tests/src/test/java/io/camunda/it/client 
But I'm not sure if any of them covers that specific use case.

File: operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/writer/BatchOperationWriter.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (RomanJRW) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/writer/BatchOperationWriter.java]: copilot saves me from trusting my late evening coding 😄

File: operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/writer/BatchOperationWriter.java
Comment (mustafadagher) [inline operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/writer/BatchOperationWriter.java]: ❓ should this be covered too?

File: operate/webapp/src/main/java/io/camunda/operate/webapp/opensearch/writer/OpensearchBatchOperationWriter.java
Comment (mustafadagher) [inline operate/webapp/src/main/java/io/camunda/operate/webapp/opensearch/writer/OpensearchBatchOperationWriter.java]: ❓ should this case be covered too?

Comment (mustafadagher) [inline operate/webapp/src/main/java/io/camunda/operate/webapp/opensearch/writer/OpensearchBatchOperationWriter.java]: ❓ should this case be covered too?

File: operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/writer/BatchOperationWriter.java
Comment (RomanJRW) [reply operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/writer/BatchOperationWriter.java]: Sorry for not making it clear, my tagging wasn't a review request, more just a question because I didn't see a clear pattern for testing some of this. Thanks for the nudges though, all your comments are right and should be covered here 👍

**Comment by RomanJRW** [comment]
@mustafadagher: I spent a little time again on this and I can't easily write a test because:
- The batch operation ID field isn't exposed by the API, making assertions difficult
- Unit tests are pointless because the logic is not controlled, i.e. it is part of a painless script

Given the relative low risk of the scripting change, wdyt about proceeding here without additional tests? I don't think it's ideal but it's also already the case that we don't have tests for this

**Comment by mustafadagher** [comment]
> * The batch operation ID field isn't exposed by the API, making assertions difficult

That's interesting to hear, if the search API does not expose it, how/where do we actually use it? I thought there was a requirement to be able to know the batch operations a certain process instance is part of.

> Given the relative low risk of the scripting change, wdyt about proceeding here without additional tests? I don't think it's ideal but it's also already the case that we don't have tests for this

I think it should be fine to go.

💭 In general, if the API provided the IDs, to be able to test it, we would have needed to figure out how it would have happened to begin with. 
I can't think that the batch operation chunks contained the same process instance key multiple times, leading to this repeated insertion.
💭 The only one possible way I can think of, is one process instance had so many incidents, but then I can't see 12k incidents for the same process instance either.
It could be coming from the legacy operate batch operations, but we also can't prove this so far.

My only fear, is that if it's the first case, we might be covering up for another bug that needs to be resolved; which is how did we come to do that much repeated insertions anyway?

**Comment by RomanJRW** [comment]
> That's interesting to hear, if the search API does not expose it, how/where do we actually use it?

As far as I can see, nowhere. We store this on the list view entity but it is not consumed.

> we would have needed to figure out how it would have happened to begin with

I believe it is because the handler updates for each record in the chunk and the painless script was not deduplicating the batch operation ID on write (with this `if` guard for example). So I guess if x items in a chunk belong to the same root entity, the ID will get written x times to that field.

I think this also happened in this case because the exporter writes were failing because of [this issue](https://github.com/camunda/camunda/issues/44356). If the exporter restarts, then the same chunk items could be written and result in the duplicated IDs being written again (i.e. it's not idempotent until this change is in effect).

With that in mind, would you mind reviewing this and approving if you are happy to proceed?

**Review by mustafadagher — APPROVED** [review]
LGTM @RomanJRW !
🔧 I'd split the first commit into two separate ones: one that enhances the condition, and another refactoring one that deletes the dead code.
