### PR TITLE
[Forward main] Limit expire message commands in result

### LINKED ISSUE #11762: MessageTimeToLiveChecker clogs the log stream with commands
**Describe the bug**

The `MessageTimeToLiveChecker` appends `Message:Expire` commands to the log for each message that has surpassed its TTL. If there are many messages in the state with an expired TTL, it will write many commands to the log in a single batch. This means the engine doesn't have time to process anything else until it processed all the commands in that batch. This can lead to latency spikes, see #11591.

**To Reproduce**

- send a huge number of messages with a TTL of some minutes, continuously
- once those minutes have passed, notice that publishing more messages suffers from increased latency

**Expected behavior**

The `MessageTimeToLiveChecker` should limit the number of message expiration commands it appends in a single batch.

Since there can still be more messages with an expired TTL in the state (and the state is already being iterated), the checker should just continue after appending the batch by starting to append to another batch. Once the checker is out of messages to expire, it can be rescheduled to run after the fixed interval that currently also already exists.

### PR DESCRIPTION
**Pull request by korthout**
## Description

Forwards #11856 to `main`.

## Related issues

closes #11762

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageTimeToLiveChecker.java [hunk 1]
```diff
@@ -8,32 +8,74 @@
 package io.camunda.zeebe.engine.processing.message;
 
 import io.camunda.zeebe.engine.state.immutable.MessageState;
+import io.camunda.zeebe.engine.state.immutable.MessageState.Index;
 import io.camunda.zeebe.protocol.impl.record.value.message.MessageRecord;
 import io.camunda.zeebe.protocol.record.intent.MessageIntent;
 import io.camunda.zeebe.scheduler.clock.ActorClock;
+import io.camunda.zeebe.stream.api.scheduling.ProcessingScheduleService;
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageTimeToLiveChecker.java:15]: The backport-action was unable to cherry-pick b4ff81eba6 because of this file. IntelliJ-IDEA could "automagically" resolve all changes in this file, except for this import statement 🤷

**Review by romansmirnov — APPROVED** [review]
LGTM

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
bors cancel

Awaiting review by @Zelldon or @oleschoenburg

File: engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java [hunk 2]
```diff
@@ -358,4 +368,16 @@ public boolean exist(
...
+  private static boolean visit(
+      final long timestamp,
+      final ExpiredMessageVisitor visitor,
+      final DbCompositeKey<DbLong, DbForeignKey<DbLong>> compositeDeadlineKey) {
+    final long deadline = compositeDeadlineKey.first().getValue();
+    if (deadline <= timestamp) {
+      final long messageKey = compositeDeadlineKey.second().inner().getValue();
+      return visitor.visit(deadline, messageKey);
+    }
+    return false;
```
Comment (Zelldon) [inline engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java:381]: :question: :x: Isn't that an issue now? If the deadline is larger then the current timestamp, this means we return false, which indicates visitor stopped, which indicates we should continue, which causes to immediately reschedule?

File: engine/src/test/java/io/camunda/zeebe/engine/state/message/MessageStateTest.java [hunk 3]
```diff
@@ -192,7 +194,8 @@ public void shouldNotVisitMessagesBeforeTime() {
 
     // then
     final List<Long> readMessage = new ArrayList<>();
-    messageState.visitMessagesWithDeadlineBefore(1_000, readMessage::add);
+    messageState.visitMessagesWithDeadlineBeforeTimestamp(
```
Comment (Zelldon) [inline engine/src/test/java/io/camunda/zeebe/engine/state/message/MessageStateTest.java:197]: :wrench: might make sense to assert the return value, then we might had catched the issue from above.

**Review by ChrisKujawa — APPROVED** [review]
Hey @korthout I have some questions/remarks, since I'm not 100% sure whether they are true, please let me know whether they are wrong assumptions and everything fine. 

Since we already had the other PR merged I will approve it already, I think we can anyway iterate over it.

File: engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java [hunk 4]
```diff
@@ -336,17 +337,26 @@ public StoredMessage getMessage(final long messageKey) {
...
-          return false;
-        }));
+        startAtKey,
+        (key, value) -> {
+          final var shouldContinue = visit(timestamp, visitor, key);
+          stoppedByVisitor.set(!shouldContinue);
+          return shouldContinue;
+        });
+
+    return stoppedByVisitor.get();
```
[the remark this answers is not in the document]
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java:359]: >So it it true when the visitor indicated to stop, which means we should come back later,

Not necessarily. That's up to the caller to decide. It just informs the caller of whether the visitor has stopped the iteration. That's all.

> stoppedToComeBackLater, suspendedForLaterIteration

These names make expectations about what the result is used for, not what the result is. The result of the method informs the caller of whether the visitor has stopped the iteration. That's all.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageTimeToLiveChecker.java [hunk 5]
```diff
@@ -8,35 +8,89 @@
...
-      final long expiredMessageKey, final TaskResultBuilder taskResultBuilder) {
-    return taskResultBuilder.appendCommandRecord(
-        expiredMessageKey, MessageIntent.EXPIRE, EMPTY_DELETE_MESSAGE_COMMAND);
+    final var counter = new MutableInteger(0);
+    final boolean shouldContinueWhereLeftOff =
+        messageState.visitMessagesWithDeadlineBeforeTimestamp(
+            currentTimestamp,
+            lastIndex,
+            (deadline, expiredMessageKey) -> {
+              final var newIndex = new Index(expiredMessageKey, deadline);
```
[the remark this answers is not in the document]
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageTimeToLiveChecker.java:71]: Yes, the order in which these are passed into the Index record is irrelevant to the execution. The order is only relevant for the key in the column family because that is ordered. This index is just a convenient way to track uniquely identifying data.

[the remark this answers is not in the document]
Comment (Zelldon) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageTimeToLiveChecker.java:71]: Yep saw it later, missed to remove the comment.

File: engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java:359]: Yeah I think you're right.

File: engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java (hunk 2 above)
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java:381]: You're right. This is a bug. Darn.

Thanks for catching ❤️

Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/message/DbMessageState.java]: I've cherry-picked the changes of #11959 onto this branch so the fix is immediately provided.

If that pull request is accepted, I'll consider this one accepted.

**Comment by korthout** [comment]
Merging this, since #11959 was accepted.

bors merge
