### PR TITLE
fix: gracefully handle ES/OS failures in health indicators

### LINKED ISSUE #49148: Downgrade transient ES/OS connection errors in schema retrieval to WARN
### 

### 

### 

### 

### Description

Currently, when there is a transient Elasticsearch/OpenSearch connectivity problem (such as 'Connection is closed') during schema mapping retrieval (e.g., from `getMappings` in `ElasticsearchEngineClient`), the resulting exception bubbles up and is logged at ERROR by the servlet framework. This creates noise in error reporting systems and suggests a critical bug even for recoverable or expected startup conditions.

The repo already includes a `SuppressLogger` utility aimed at downgrading transient connection issues to WARN, but schema retrieval paths do not route these exceptions through `SuppressLogger`. In addition, not all connection-related exception types are included in the suppressed set.

### Steps to reproduce

1. Start Camunda 8 with Elasticsearch or OpenSearch on a slow startup or temporarily unavailable
2. Observe logs as schema mapping retrieval fails with a 'Connection is closed' IOException
3. See ERROR-level log and error reported by servlet framework

### Current behavior

- Transient search engine connection issues (e.g., connection closed) are not handled via `SuppressLogger`
- The exception is not downgraded and ultimately logged at ERROR in frameworks such as Spring
- Fails CI error log scanning and surfaces in issue monitoring, even if self-resolving

<details><summary>Error message</summary>
<p>

```
Servlet.service() for servlet [dispatcherServletRegistration] in context with path [] threw exception [Request processing failed: io.camunda.search.schema.exceptions.SearchEngineException: Failed retrieving mappings from index/index templates with pattern [camunda-tenant-8.8.0_*,camunda-authorization-8.8.0_*,tasklist-form-8.4.0_*,operate-decision-8.3.0_*,camunda-group-8.8.0_*,camunda-web-session-8.8.0_*,camunda-user-8.8.0_*,operate-process-8.3.0_*,camunda-history-deletion-8.9.0_*,operate-decision-requirements-8.3.0_*,camunda-mapping-rule-8.8.0_*,camunda-audit-log-cleanup-8.9.0_*,operate-metadata-8.8.0_*,camunda-global-listener-8.9.0_*,camunda-cluster-variable-8.9.0_*,camunda-role-8.8.0_*,operate-batch-operation-1.0.0_*,operate-post-importer-queue-8.3.0_*,tasklist-task-8.8.0_*,operate-decision-instance-8.3.0_*,camunda-usage-metric-tu-8.8.0_*,operate-operation-8.4.1_*,camunda-job-metrics-batch-8.9.0_*,operate-event-8.3.0_*,tasklist-task-variable-8.3.0_*,operate-message-8.5.0_*,tasklist-draft-task-variable-8.3.0_*,camunda-usage-metric-8.8.0_*,operate-incident-8.3.1_*,operate-variable-8.3.0_*,camunda-correlated-message-subscription-8.8.0_*,camunda-audit-log-8.9.0_*,operate-list-view-8.3.0_*,operate-sequence-flow-8.3.0_*,operate-job-8.6.0_*,operate-flownode-instance-8.3.1_*]: Connection is closed] with root cause
```

</p>
</details> 

<details><summary>Stacktrace</summary>
<p>

```
org.apache.http.ConnectionClosedException: Connection is closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</p>
</details> 

### Expected behavior

- Expected, recoverable connection exceptions for mapping retrieval should be logged at WARN, not ERROR
- The `SuppressLogger` set should contain common transient connection exceptions (like `ConnectionClosedException`, `IOException` with message 'Connection is closed', etc)
- Exceptions from schema mapping retrieval should be caught, logged at the appropriate level, and only escalated at ERROR if not in the suppressed (recoverable) set

### Workaround

None – errors are not fatal and Camunda will continue running, but this creates false positives in log monitoring systems.

### Environment

SaaS & SM

### Version

(affects all current Camunda 8 versions using Elasticsearch or OpenSearch schema manager)

### Rootcause

_No response_

### Solution ideas

- Expand SuppressLogger.SUPPRESSED_EXCEPTIONS to cover more transient network exceptions
- Log connection exceptions during schema retrieval with SuppressLogger (WARN)
- Add checks for typical IOException subclasses and messages
- Optionally, adjust top-level servlet exception mapping for these cases if logging cannot be moved down

### Dev -> QA handover

_No response_

### Links

- Error: https://console.cloud.google.com/errors/detail/CPbl4OrCgZPgeA;service=zeebe;time=P7D;locations=global?project=camunda-saas-int
- Logs: https://cloudlogging.app.goo.gl/87KPcqS8ytHqSbgNA

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Summary

- Consolidated duplicate health check logic (Operate's `IndicesCheck` + Tasklist's `IndexSchemaValidator` with ES/OS implementations) into a shared `SearchEngineHealthCheck` class in `schema-manager`
- Added `isHealthy()` guard to Tasklist's `SearchEngineHealthIndicator` so it short-circuits before calling `getMappings()` when ES is unreachable
- Added try-catch in both Operate and Tasklist health indicators so ES/OS failures return `Health.down()` with a WARN log instead of propagating as unhandled servlet ERRORs

Closes #49148

### CODE REVIEW

File: schema-manager/src/main/java/io/camunda/search/schema/SearchEngineHealthCheck.java [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+  private static final Logger LOG = LoggerFactory.getLogger(SearchEngineHealthCheck.class);
+
+  private final SearchEngineClient searchEngineClient;
+  private final SchemaManager schemaManager;
+  private final boolean healthCheckEnabled;
+
+  public SearchEngineHealthCheck(
+      final SearchEngineConfiguration configuration, final boolean healthCheckEnabled) {
+    final boolean isElasticSearch = configuration.connect().getTypeEnum().isElasticSearch();
+    final com.fasterxml.jackson.databind.ObjectMapper objectMapper;
```
Comment (RomanJRW) [inline schema-manager/src/main/java/io/camunda/search/schema/SearchEngineHealthCheck.java:39]: 🔧 can use import

**Review by RomanJRW — COMMENTED** [review]
LGTM ✅

**Review by RomanJRW — APPROVED** [review]
I forgot to approve before, accidentally only commented
