### PR TITLE
Simplify interface for taking snapshots

### LINKED ISSUE #7906: Clean up interface of StateController and TransientSnapshot
**Description**

We have one method is StateController that returns a future with Optional.
`ActorFuture<Optional<TransientSnapshot>> takeTransientSnapshot(long lowerBoundSnapshotPosition);`

Wrapping Optional with in future is unnecessary. It can be simplified to return `ActorFuture<TransientSnapshot>`. For the cases where the Optional can be empty, it should fail the future with exception. Since those cases are not critical errors, we should also have a way to categorize the errors and ignore them if possible.

* Define exceptions that can be thrown by `takeTransientSnapshot`. Eg:- SnapshotAlreadyExists, DbClosed, etc.
* Document them in the interface
* AsyncSnapshotDirector that calls this method can react on this exceptions based on the type. For example, if SnapshotAlreadyExists, the exception can be ignored. 

A related issue is `TransientSnapshot#take` returns an `ActorFuture<Boolean>`. If the value is false, the reason why snapshot was not taken is lost. Instead, it would be better to always fail with exception if the snapshot is not taken successfully.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

To simplify the code for taking snapshots:
* Removed Optional and used Either instead. Using Either is useful to return the errors. Optional hides the reason why the snapshot was not taken
* Similarly, removed the predicate that returns a boolean to indicate a snapshot was taken and instead throw an exception. This makes the error handling consistent.
* Introduced new exceptions to identify failures when taking or persisting a snapshot. 
* Update all tests to reflect the api change.

## Related issues

closes #7906 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java [hunk 1]
```diff
@@ -155,16 +155,19 @@ private void takeTransientSnapshotInternal(
...
         constructableSnapshotStore.newTransientSnapshot(
             snapshotIndexedEntry.index(),
             snapshotIndexedEntry.term(),
             lowerBoundSnapshotPosition,
             exportedPosition);
 
     // Now takeSnapshot result can be either true, false or error.
-    transientSnapshot.ifPresentOrElse(
-        snapshot -> takeSnapshot(snapshot, future), () -> future.complete(Optional.empty()));
+    if (transientSnapshot.isLeft()) {
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java:165]: :thought_balloon: Either supports as well  `ifRightOrLeft`

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 2]
```diff
@@ -235,18 +237,18 @@ private void takeSnapshot() {
     final var transientSnapshotFuture =
         stateController.takeTransientSnapshot(lowerBoundSnapshotPosition);
     transientSnapshotFuture.onComplete(
-        (optionalTransientSnapshot, snapshotTakenError) -> {
+        (transientSnapshot, snapshotTakenError) -> {
           if (snapshotTakenError != null) {
-            LOG.error("Could not take a snapshot for {}", processorName, snapshotTakenError);
-            resetStateOnFailure();
+            if (snapshotTakenError instanceof SnapshotException.SnapshotAlreadyExistsException) {
+              LOG.debug("Did not take a snapshot. {}", snapshotTakenError.getMessage());
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:243]: :x: Please pass the error to the logger as well.

Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:243]: Is it correct that we not reset here the state?

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java [hunk 3]
```diff
@@ -313,7 +315,14 @@ private void persistSnapshotIfLastWrittenPositionCommitted() {
       snapshotPersistFuture.onComplete(
           (snapshot, persistError) -> {
             if (persistError != null) {
-              LOG.error(ERROR_MSG_MOVE_SNAPSHOT, persistError);
+              if (persistError instanceof SnapshotNotFoundException) {
+                LOG.warn(
+                    "Failed to persist transient snapshot {}. Nothing to worry if a newer snapshot exists.",
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:320]: :+1: such a friendly message :D

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java [hunk 4]
```diff
@@ -199,35 +201,25 @@ boolean isDbOpened() {
...
       final TransientSnapshot snapshot,
-      final ActorFuture<Optional<TransientSnapshot>> transientSnapshotFuture) {
+      final ActorFuture<TransientSnapshot> transientSnapshotFuture) {
     final var snapshotTaken =
         snapshot.take(
             snapshotDir -> {
               if (db == null) {
-                LOG.error("Expected to take a snapshot, but no database was opened");
-                return false;
+                throw new StateClosedException(
```
Comment (Zelldon) [inline broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java:209]: :x:  Not so optimal I think. What about just complete the future?

Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java:209]: Or will the returned future be completed with the exception, sorry might be that I missed that.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/ConstructableSnapshotStore.java [hunk 5]
```diff
@@ -19,9 +19,9 @@
    * @param term the term to which the snapshots corresponds to
    * @param processedPosition the processed position in the snapshot
    * @param exportedPosition the exported position in the snapshot
-   * @return an optional with a transient snapshot if new transient snapshot was taken successfully,
-   *     otherwise return an empty optional
+   * @return an Either that contains and exception or transientSnapshot if it was taken
```
Comment (Zelldon) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/ConstructableSnapshotStore.java:22]: :thought_balloon: could be shorten like this
```suggestion
   * @return either an exception or transientSnapshot, if it was taken
```

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/ConstructableSnapshotStore.java [hunk 6]
```diff
@@ -19,9 +19,9 @@
...
+   *     successfully.
    */
-  Optional<TransientSnapshot> newTransientSnapshot(
+  Either<SnapshotException, TransientSnapshot> newTransientSnapshot(
```
Comment (Zelldon) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/ConstructableSnapshotStore.java:25]: :thought_balloon: First I thought why not just return the message (string), but I think this is necessary because in some cases you want to handle it differently?

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java [hunk 7]
```diff
@@ -342,18 +342,18 @@ public FileBasedReceivedSnapshot newReceivedSnapshot(final String snapshotId) {
...
-      LOGGER.debug(
-          "Previous snapshot was taken for the same processed position {} and exported position {}, will not take snapshot.",
-          processedPosition,
-          exportedPosition);
-      return Optional.empty();
+      final String error =
+          String.format(
+              "Previous snapshot was taken for the same processed position %d and exported position %d.",
+              processedPosition, exportedPosition);
+      return Either.left(new SnapshotAlreadyExistsException(error));
```
Comment (Zelldon) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java:349]: :+1:

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java [hunk 8]
```diff
@@ -119,7 +126,7 @@ private void persistInternal(final CompletableActorFuture<PersistedSnapshot> fut
 
     if (!isValid) {
       future.completeExceptionally(
-          new IllegalStateException("Snapshot is not valid. It may have been deleted."));
+          new SnapshotNotFoundException("Snapshot is not valid. It may have been deleted."));
```
Comment (Zelldon) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java:129]: :x: This message is confusing. The exception says not found, but the message says not valid, and it may have been deleted? What is true now?

File: snapshot/src/test/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshotTest.java [hunk 9]
```diff
@@ -234,33 +234,10 @@ public void shouldNotRemoveTransientSnapshotWithGreaterIdOnPersist() {
         .hasParent(pendingDir);
   }
 
-  @Test
-  public void shouldRemoveTransientDirectoryOnTakeFailure() {
```
Comment (Zelldon) [inline snapshot/src/test/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshotTest.java:238]: :question: Do we have an replacement for this test?

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @deepthidevaki I like it, I had just some smaller comments please take a look below.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java (hunk 1 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java:165]: I found this more readable. With `ifRightOrLeft` there are too many lambdas.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java (hunk 2 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:243]: It is not necessary to reset here, as nothing has happened. But to avoid confusion, I will reset it once in the outer if block.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java (hunk 4 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java:209]: TransientSnapshot#take will complete the future (snapshotTaken) exceptionally, and do some additional error handling. That is why it doesn't complete `transientSnapshotFuture` here.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/ConstructableSnapshotStore.java (hunk 5 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/ConstructableSnapshotStore.java:22]: Thanks. I was struggling to write this :smile:

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/ConstructableSnapshotStore.java (hunk 6 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/ConstructableSnapshotStore.java:25]: Yes. That is the idea. If snapshot already exists, it is not an error. So AsyncSnapshotDirector can just log it as debug and ignore it. Anything else could indicate a real error.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java (hunk 8 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java:129]: How about "Snapshot is not valid. Either it is not taken or it is already deleted."

File: snapshot/src/test/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshotTest.java (hunk 9 above)
Comment (deepthidevaki) [reply snapshot/src/test/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshotTest.java:238]: Yes. There was an existing test `shouldRemoveTransientDirectoryOnTakeException()`.

File: broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java (hunk 2 above)
Comment (deepthidevaki) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:243]: > Please pass the error to the logger as well.

Was not sure if we have to print the entire stack trace here, since this is an expected case. That's why I only logged the message from the error. Wdyt?

Comment (Zelldon) [reply broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/AsyncSnapshotDirector.java:243]: yeah you're probably right

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java (hunk 8 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java:129]: Ignore my previous comment. It does not reflect the correct state.

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java [hunk 10]
```diff
@@ -48,28 +49,34 @@
...
-        if (!isValid) {
-          abortInternal();
-        } else if (!directory.toFile().exists() || directory.toFile().listFiles().length == 0) {
+        takeSnapshot.accept(getPath());
+        if (!directory.toFile().exists() || directory.toFile().listFiles().length == 0) {
           // If no snapshot files are created, snapshot is not valid
-          isValid = false;
+          abortInternal();
+          takenFuture.completeExceptionally(
+              new IllegalStateException(
```
Comment (Zelldon) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java:67]: Does it make sense here to use also snapshot not found exception?

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java (hunk 8 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java:129]: At this point, if the snapshot is not valid, most likely the transient snapshot is already deleted because a newer snapshot was received. This is what we should convey here.

Comment (Zelldon) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java:129]: Hm Ok I think I was confused because of the term "valid", because I thought it is related to the checksum or something. But it seems valid is just when it was taken successfully. Invalid if there was an error in between. Maybe we can just reuse the takenFuture? Or get the exception from this future and pass it into the given future? What do you think?

**Review by ChrisKujawa — APPROVED** [review]

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java (hunk 8 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java:129]: It is also invalid if it was deleted before persisting.

Comment (Zelldon) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java]: Ok this wouldn't be covered by the other future then right?

Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java]: See this change https://github.com/camunda-cloud/zeebe/pull/7922/commits/4e829e00fbb972048cb9bdcd90a9e1dcc7094239
Is it better?

Comment (Zelldon) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java]: Hm I think isDone will return true, if it was completed exceptionally :)

Comment (Zelldon) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java]: But yes I like it more to distinguish to get better messages.

Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java]: > Hm I think isDone will return true, if it was completed exceptionally 

Yes. This change https://github.com/camunda-cloud/zeebe/commit/4e829e00fbb972048cb9bdcd90a9e1dcc7094239 will cover it, no?

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java (hunk 10 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java:67]: I thought about it too. But didn't use it because it is still during "taking" a snapshot. So snapshot not found did not make sense to me.

**Comment by deepthidevaki** [comment]
> If isDone is false then isCompleteExceptionally cant be true either.

Yes. That is why it is an OR
`!takenFuture.isDone() || takenFuture.isCompletedExceptionally()`

**Comment by Zelldon** [comment]
Sorry I think my brain hasn't fully recovered yet

**Comment by deepthidevaki** [comment]
@Zelldon No worries.
