### PR TITLE
fix(broker): Log Invalid Static Config When Detected

### LINKED ISSUE #5394: Log invalid static configuration when detected
**Description**

In the broker topology, we currently check if the static configuration of two brokers match - that is, that the cluster size, replication factor, and partition count all match. When this is false, we log that there's a mismatch, but do not log what exactly was mismatched, reducing the usefulness of the log statement. See: https://console.cloud.google.com/errors/CM_ridKXqsyn4QE?service=zeebe&version=0.24.2&time=P1D&project=camunda-cloud-240911&organizationId=669107107215

No need to log the exact differences, but we need to log at least both configurations so a human can find the differences.

### PR DESCRIPTION
**Pull request by sccalabr**
## Description

This change is to log the differences for the static
configuration and local configuration. Only the
values checked in isStaticConfigValid are logged.

## Related issues

closes #5394

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [x] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java [hunk 1]
```diff
@@ -189,9 +189,22 @@ private BrokerInfo readBrokerInfo(final Member eventSource) {
     final BrokerInfo brokerInfo = BrokerInfo.fromProperties(eventSource.properties());
     if (brokerInfo != null && !isStaticConfigValid(brokerInfo)) {
       LOG.error(
-          "Static configuration of node {} differs from local node {}",
+          "Static configuration of node {} differs from local node {}.",
           eventSource.id(),
           atomix.getMembershipService().getLocalMember().id());
+
+          LOG.error(
```
Comment (korthout) [inline broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java:196]: Since this is not really a different error than the error log statement at line 191, I'd prefer to see these log statements combined into a single statement. Otherwise our error tooling for pick it up as 2 separate errors.

File: broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java [hunk 2]
```diff
@@ -189,9 +189,22 @@ private BrokerInfo readBrokerInfo(final Member eventSource) {
...
+            "Static Configuration :: Local Node Configuration \n" 
+             + "NodeId: {} >= 0 \n"
```
Comment (korthout) [inline broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java:198]: Please change this such that it states that node id should be >= 0 and < localBroker.getClusterSize()

File: broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java [hunk 3]
```diff
@@ -189,9 +189,22 @@ private BrokerInfo readBrokerInfo(final Member eventSource) {
     final BrokerInfo brokerInfo = BrokerInfo.fromProperties(eventSource.properties());
     if (brokerInfo != null && !isStaticConfigValid(brokerInfo)) {
       LOG.error(
-          "Static configuration of node {} differs from local node {}",
+          "Static configuration of node {} differs from local node {}.",
           eventSource.id(),
           atomix.getMembershipService().getLocalMember().id());
+
+          LOG.error(
+            "Static Configuration :: Local Node Configuration \n"
```
Comment (korthout) [inline broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java:197]: I like that you spend effort on making the entire statement human readable such that we can easily find the diff, but multi error log statements are generally not well received by error tooling. It would be great if you could find a way to get everything on one line, but still in a human readable format in which we can easily find the diff.

**Review by korthout — CHANGES_REQUESTED** [review]
Hi @sccalabr 🎖️  Thanks for this PR. I like how you put effort into making it human readable. I just have a few comments.

File: broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java (hunk 3 above)
Comment (sccalabr) [reply broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java]: Made some changes. Let me know what you think.

File: broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java [hunk 4]
```diff
@@ -189,9 +190,17 @@ private BrokerInfo readBrokerInfo(final Member eventSource) {
     final BrokerInfo brokerInfo = BrokerInfo.fromProperties(eventSource.properties());
     if (brokerInfo != null && !isStaticConfigValid(brokerInfo)) {
       LOG.error(
-          "Static configuration of node {} differs from local node {}",
-          eventSource.id(),
-          atomix.getMembershipService().getLocalMember().id());
+          "Static configuration of node {} differs from local node {}."
```
Comment (korthout) [inline broker/src/main/java/io/zeebe/broker/clustering/topology/TopologyManagerImpl.java:193]: I ran a little manual test, by changing the above if statement to always evaluate to true, locally building the project and running `./dist/target/zeebe-broker/bin/broker`. It outputted the following log statement:
```
2020-10-12 10:44:49.002 [] [atomix-cluster-events] ERROR io.zeebe.broker.clustering - Static configuration of node 0 differs from local node 0.NodeId: 0 <= 0 < 1, ClusterSize: 1 == 1, PartitionsCount: 1 == 1, ReplicationFactor: 1 == 1.
```

So here we see that we also compare our own static configuration to our own configuration 😆. The statement itself is nicely readable and it's clear what would be wrong in a failure case. The only thing we missed was an additional space and it might make sense to change the dot into a colon.

```suggestion
          "Static configuration of node {} differs from local node {}: " 
```

**Review by korthout — COMMENTED** [review]
Thanks for applying the changes. It looks great like this. I have 1 last tiny change request and then its done.

Also please don't forget to run `mvn com.coveo:fmt-maven-plugin:format` before you commit, to make sure the changes adhere to our styling rules.

**Review by korthout — APPROVED** [review]
LGTM 🎉
