### PR TITLE
fix: make CommandWrapper response type agnostic

### LINKED ISSUE #26418: CommandWrapper#executeAsyncWithMetrics fails with ClassCastException
**Describe the bug**

Some spring client metric recordings fail, e.g. Job Completion commands, basically all that have not the ResponseType Void, which [is statically used in CommandWrapper](https://github.com/camunda/camunda/blob/main/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/CommandWrapper.java#L28).

RuntimeException:
```
java.util.concurrent.CompletionException: java.lang.ClassCastException: class io.camunda.zeebe.client.impl.response.CompleteJobResponseImpl cannot be cast to class java.lang.Void (io.camunda.zeebe.client.impl.response.CompleteJobResponseImpl is in unnamed module of loader 'app'; java.lang.Void is in module java.base of loader 'bootstrap')
```

The issue was introduced with https://github.com/camunda/camunda/commit/08549f1a333b2d79a435953883742676163f619a#diff-72dbd98a316339b0694a986876f59994f004caaba30d0607d865752449c66c68R61
where metric handling was moved inside the CommandWrapper using `thenApply` which casts the result to "Void" at runtime, which it may not be compatible with.

Relates to #26424 where I encountered the issue it when running tests.

**To Reproduce**

Use Spring SDK and complete jobs, job completion metrics are not updated due to the exception. General client usage is not impacted as the error is swallowed in the `CommandWrapper` implementation

**Expected behavior**

MetricsRecorder should record job completion metrics.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.CompletionException: java.lang.ClassCastException: class io.camunda.zeebe.client.impl.response.CompleteJobResponseImpl cannot be cast to class java.lang.Void (io.camunda.zeebe.client.impl.response.CompleteJobResponseImpl is in unnamed module of loader 'app'; java.lang.Void is in module java.base of loader 'bootstrap')
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.onNext(ZeebeClientFutureImpl.java:85)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:468)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:657)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:644)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassCastException: class io.camunda.zeebe.client.impl.response.CompleteJobResponseImpl cannot be cast to class java.lang.Void (io.camunda.zeebe.client.impl.response.CompleteJobResponseImpl is in unnamed module of loader 'app'; java.lang.Void is in module java.base of loader 'bootstrap')
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 11 more

```

</p>
</details>

**Environment:**
- Zeebe Version: 8.6+
- Configuration: Spring SDK client

### PR DESCRIPTION
**Pull request by megglos**
## Description

Previously Void was used statically, which wasn't a problem as the response wasn't consumed in the wrapper. Since the introduction of [executeAsyncWithMetrics](https://github.com/camunda/camunda/blob/7975ade4b85293ce24da1e1424a5f442f6751d83/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/CommandWrapper.java#L67) it is consumed though.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #26418

### CODE REVIEW

File: clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java [hunk 1]
```diff
@@ -116,7 +117,7 @@ private List<Object> createParameters(final JobClient jobClient, final Activated
     return parameterResolvers.stream().map(resolver -> resolver.resolve(jobClient, job)).toList();
   }
 
-  private FinalCommandStep createCompleteCommand(
+  private FinalCommandStep<CompleteJobResponse> createCompleteCommand(
```
Comment (megglos) [inline clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java:120]: The missing generic declaration here was the cause for the compiler to not raise the conflict already when the CommandWrapper for the Complete Command is created [here](https://github.com/camunda/camunda/blob/main/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java#L92)

File: clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/CommandWrapper.java [hunk 2]
```diff
@@ -35,7 +35,7 @@ public class CommandWrapper {
   private final int maxRetries;
 
   public CommandWrapper(
-      final FinalCommandStep<Void> command,
+      final FinalCommandStep<?> command,
```
Comment (megglos) [inline clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/CommandWrapper.java:38]: Didn't see a need to force specific generic type usage as the value is not used internally. We could change it when this is actually needed, till then the wildcard type should be suffice.

File: clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java (hunk 1 above)
Comment (megglos) [inline clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java:120]: The missing generic type declaration here was the cause for the compiler to not raise the conflict already when the CommandWrapper for the Complete Command is created [here](https://github.com/camunda/camunda/blob/main/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java#L92)

**Review by nicpuppa — APPROVED** [review]
Thanks for spotting this 💪
