### PR TITLE
fix: replace load test secret placeholder on redeploy

### LINKED ISSUE #50388: Fix bug when redeploying twice and replacing the client-secret
There is a bug in the load test setup that causes issues when redeploying twice and replacing the client-secret. This needs to be investigated and fixed.

Reference: https://camunda.github.io/zeebe-chaos/2026/04/02/REST-API-and-OIDC

### PR DESCRIPTION
**Pull request by pranjalg13**
## Summary

- Fixes a bug where redeploying a load test via `camunda-load-test.yml` left the `__SECRET__` placeholder in `load-test-values.yaml` unreplaced, causing the load test starter/worker pods to use an invalid credential.

### Root cause

When a load test is redeployed to an existing namespace:
1. `newLoadTest.sh` copies fresh template files (including `load-test-values.yaml` with `__SECRET__` placeholder)
2. `createCredsLoadTest.sh` detects that the `camunda-credentials` secret already exists and exits early
3. The `sed_inplace` that replaces `__SECRET__` with the actual orchestration secret **never runs**

### Fix

When the secret already exists, retrieve the `orchestration-security-authentication-oidc-secret` from the existing Kubernetes secret and perform the sed replacement before exiting. This ensures `load-test-values.yaml` always has the correct credential value regardless of whether it's a fresh deploy or a redeploy.

## Test plan

- [x] Deploy a load test with `camunda-load-test.yml` (first deploy — creates namespace and secret)
- [x] Redeploy the same load test (same namespace) — verify `load-test-values.yaml` in the namespace dir has the actual secret value, not `__SECRET__`
- [x] Verify starter/worker pods authenticate successfully on redeploy

Run1: https://github.com/camunda/camunda/actions/runs/23893431681/attempts/1
Redeployed with same image and typical to max: Run2https://github.com/camunda/camunda/actions/runs/23894145438

closes #50388

### CODE REVIEW

File: load-tests/setup/default/createCredsLoadTest.sh [hunk 1]
```diff
@@ -10,9 +10,12 @@ set -euo pipefail
 # Usage: ./createCredsLoadTest.sh [namespace]
 NS="${1:-__NAMESPACE__}"
 
-# Check if the secret already exists; if so, skip creation.
+# Check if the secret already exists; if so, retrieve the existing orchestration secret
+# for the sed replacement and skip creation.
 if kubectl -n "$NS" get secret camunda-credentials &>/dev/null; then
   echo "Secret 'camunda-credentials' already exists in namespace '$NS'. Skipping creation."
+  ORCHESTRATION_SECRET=$(kubectl -n "$NS" get secret camunda-credentials -o jsonpath='{.data.orchestration-security-authentication-oidc-secret}' | base64 -d)
```
Comment (ChrisKujawa) [inline load-tests/setup/default/createCredsLoadTest.sh:18]: @pranjalg13 can we try this? With a load test?

Comment (pranjalg13) [reply load-tests/setup/default/createCredsLoadTest.sh:18]: Yep Already added in the description of the PR

**Review by ChrisKujawa — APPROVED** [review]
Thanks @pranjalg13 👍🏼 

I think there is a valid point regarding the base64 -d but let's see whether this is really an issue

File: load-tests/setup/default/createCredsLoadTest.sh (hunk 1 above)
Comment (ChrisKujawa) [inline load-tests/setup/default/createCredsLoadTest.sh:18]: 🔧 We could add as log, that we read the existing secret.

[the remark this answers is not in the document]
Comment (pranjalg13) [reply load-tests/setup/default/createCredsLoadTest.sh:18]: We can check if it is breaking but for modern macOS (Ventura+) supports both, so it's less of an issue now
