### PR TITLE
Fix race condition between receiving a new snapshot and aborting previous pending one

### LINKED ISSUE #14670: Failure to delete pending snapshot leads to inactive partition until restart
**Describe the bug**

If a snapshot is being replicated during startup, and it fails to delete an existing pending snapshot directory (could be a leftover from a crash, or simply the replication restarting due to some errors), the partition transitions to inactive and is stuck, preventing startup from finishing.

**To Reproduce**

It seems to happen more often with large state, >= 8GB. Simply cause data loss on one node to force replication on restart, and it might happen.

**Expected behavior**

Even if an I/O error occurs during replication, it should be able to recover and retry the snapshot replication.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Expected to delete pending received snapshot, but failed.
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:373) ~[zeebe-snapshots-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:51) ~[zeebe-snapshots-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.onInstall(PassiveRole.java:191) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.raft.roles.FollowerRole.onInstall(FollowerRole.java:83) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$8(RaftContext.java:315) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$27(RaftContext.java:334) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) [zeebe-atomix-utils-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/6651-18-6637-6635/001698.sst
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.implDelete(Unknown Source) ~[?:?]
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source) ~[?:?]
	at java.nio.file.Files.delete(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.visitFile(FileUtil.java:204) ~[zeebe-util-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.visitFile(FileUtil.java:187) ~[zeebe-util-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil.deleteFolder(FileUtil.java:134) ~[zeebe-util-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:371) ~[zeebe-snapshots-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	... 12 more
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

When `newReceivedSnapshot` is run on the caller thread (raft), the directory deletion conflicts with the concurrent abort run on the SnapshotStore actor. Ideally, all access/changes to snapshot should be serialized via snapshot store actor.

To fix this, now `newReceivedSnapshot` runs on the SnapshotStore actor and returns an ActorFuture. Since raft thread has to wait until a new pending snapshot is created, as an optimization, we only run the code that has to modify snapshot store state/directory in the actor. 

This has a minor impact on raft thread, as raft thread will be blocked during this operation. However, we use the same pattern when applying a snapshot chunk or when committing. Also, since this code is executed on the slowest follower, this is not in the critical path. So blocking raft thread is an acceptable trade-off between performance and complexity.

## Related issues

closes #14670 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java [hunk 1]
```diff
@@ -362,6 +356,34 @@ public FileBasedReceivedSnapshot newReceivedSnapshot(final String snapshotId) {
...
+          () -> {
+            try {
+              checkAndCleanupExistingDirectory(snapshotId, parsedSnapshotId, directory);
+              createReceivedSnapshot(parsedSnapshotId, directory, newSnapshotFuture);
+            } catch (final Exception e) {
+              newSnapshotFuture.completeExceptionally(e);
+            }
+          });
+    } else {
+      createReceivedSnapshot(parsedSnapshotId, directory, newSnapshotFuture);
```
Comment (npepinpe) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java:370]: :question: Isn't there still a race condition if we don't synchronize the complete `newReceivedSnapshot` call? I think it would be safer to just wrap the whole method body in the actor context.

**Review by npepinpe — COMMENTED** [review]
One small question, but generally looks good. I also would have liked a regression test for this case, but I had trouble writing one myself (:sweat_smile:) so I can see how it'd be complicated to have one

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java (hunk 1 above)
Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java:370]: Here the assumption was that on raft thread is creating a new received snapshot. So there won't be any race-condition between two creations. But, as you said, I will wrap the whole body in the actor context. The optimization is probably not worth.

**Review by npepinpe — APPROVED** [review]
