### PR TITLE
fix: adjust job update processor

### LINKED ISSUE #40517: Job update retries event are not handled correctly
### 

### 

, , , 

### 

### 

### Description

The job update flow is broken after [this changes](https://github.com/camunda/camunda/pull/20950/files#diff-b008f90ab9adf3b3083a3a89291fa94f6e98c4379a53cc5c0c5d48340fa8bd2eL64). We mistakenly removed follow up events (RETRIES_UPDATE and UPDATE_TIMEOUT) from the `JobUpdateProcessor`. In addition we introduced a new applier `JobUpdatedApplier` that took care of updating the retries/timeout of the job

This is wrong as zeebe used to export RETRIES_UPDATED events and not UPDATED events as the applier wasn't present. We should revert those changes and rollback to the previous behaviour, we basically introduced a breaking change 

### Steps to reproduce

see this [thread](https://camunda.slack.com/archives/C08MRKHJ0CD/p1762319157603759)

### Current behavior

see this [thread](https://camunda.slack.com/archives/C08MRKHJ0CD/p1762319157603759)

### Expected behavior

see this [thread](https://camunda.slack.com/archives/C08MRKHJ0CD/p1762319157603759)

### Workaround

see this [thread](https://camunda.slack.com/archives/C08MRKHJ0CD/p1762319157603759)

### Environment

SaaS & SM

### Version

- Component Version: 8.6/8.7/8.8

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

The job update flow was broken due to a wrong change in the processor. The RETRIES_UPDATED and TIMEOUT_UPDATED event weren't written anymore, for this reason the outcome in the second storage was wrong. With this changes we reset the old behaviour, the JobUpdateProcessor writes the appropriate followup event based on the changeset, the JobUpdatedApplier is removed because the job updates are handled by the specific appliers

## Related issues

closes https://github.com/camunda/camunda/issues/40517

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobUpdateRetriesProcessor.java [hunk 1]
```diff
@@ -51,7 +51,6 @@ public void processRecord(final TypedRecord<JobRecord> command) {
                               command, RejectionType.INVALID_ARGUMENT, errorMessage);
                         },
                         () -> {
-                          stateWriter.appendFollowUpEvent(jobKey, JobIntent.RETRIES_UPDATED, job);
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobUpdateRetriesProcessor.java:54]: 💭 As `jobUpdateBehaviour.updateJobRetries` already writes the event in the behavior class, we don't have to write it again here. That's why removing this is safe.

I'm going to assume we have this covered with tests, otherwise someone coud change the behavior class and not realize they are breaking this processor in multiple ways:
1. It doesn't write any event anymore
2. It doesn't actually update the retries 😄

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/EventAppliers.java [hunk 2]
```diff
@@ -327,7 +327,8 @@ private void registerJobIntentEventAppliers(final MutableProcessingState state)
     register(JobIntent.TIMED_OUT, new JobTimedOutApplier(state));
     register(JobIntent.RECURRED_AFTER_BACKOFF, new JobRecurredApplier(state));
     register(JobIntent.TIMEOUT_UPDATED, new JobTimeoutUpdatedApplier(state));
-    register(JobIntent.UPDATED, new JobUpdatedApplier(state));
+    register(JobIntent.UPDATED, 1, new JobUpdatedApplier(state));
+    register(JobIntent.UPDATED, 2, new JobUpdatedV2Applier());
```
Comment (remcowesterhoud) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/EventAppliers.java]:
```suggestion
    register(JobIntent.UPDATED, 2, NOOP_APPLIER);
```

❓ Any reason you create an actual empty applier?

Comment (nicpuppa) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/EventAppliers.java]: Sorry, I thought I did remove the empty applier but apparently I didn't push the change 🤦

**Review by remcowesterhoud — APPROVED** [review]
