### PR TITLE
Document timeout responses

### LINKED ISSUE #44179: Document 504 response scenarios for Complete user task API and related endpoints
## Context

The documentation at https://docs.camunda.io/docs/next/components/concepts/user-task-listeners/#blocking-behavior indicates:

> Listeners are blocking, meaning the user task lifecycle transition is paused until the task listener completes.

In practice, this means that user task API requests such as completing a task may be delayed or time out if the required listener job is not completed in time. This can happen for a variety of reasons:
- No job workers are available for the listener job
- Existing job workers are busy
- A job worker crashed during job execution
- Network issues occurred when transmitting or completing the job
- Any other cases where the listener job is not completed quickly enough

**In these cases, affected APIs can return a `504 Gateway Timeout` error.**

### Affected APIs
The lack of documentation about the possible 504 Gateway Timeout applies to multiple APIs:
- Complete user task API: https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/complete-user-task/
- Assign user task API: https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/assign-user-task/
- Update user task API: https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/update-user-task/
- Cancel process instance API: https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/cancel-process-instance/
- Update element instance variables: https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/create-element-instance-variables/
- SetVariables RPC: https://docs.camunda.io/docs/next/apis-tools/zeebe-api/gateway-service/#setvariables-rpc

**Expected improvement:**

- Update documentation for all above APIs to include information about the 504 response and under what scenarios it may occur (e.g., when listener job isn't completed in time due to missing or delayed job workers, failures, etc).
- Example error response, context, troubleshooting, and user guidance should be included where applicable.

See more context in: https://camunda.slack.com/archives/C08MRKHJ0CD/p1768469805889299

### PR DESCRIPTION
**Pull request by korthout**
## Summary

This PR updates the API documentation to explicitly include timeout responses for relevant endpoints.

## Motivation

Timeouts can occur in normal operation. Additionally, some user task and process APIs can time out when task listener jobs are not completed in time. These timeout responses were possible in practice but not clearly documented.

## Changes

- Added timeout responses to the endpoint documentation
- Updated OpenAPI/gRPC docs so timeout behavior is represented consistently
- Kept existing documentation structure while extending response coverage

## Impact

- **No runtime behavior changes**
- Documentation and test-only update
- Improves clarity for client-side timeout handling

## Testing

- Verified the documentation changes render correctly
- Confirmed timeout responses are reflected in the generated API docs

## Related

closes #44179

### CODE REVIEW

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/engine/client/command/UserTaskListenersTest.java [hunk 1]
```diff
@@ -1049,6 +1049,51 @@ void shouldRejectVariableUpdateRequestWhenUserTaskIsCanceledDuringTransition() {
...
+        RecordingExporter.userTaskRecords(UserTaskIntent.CREATED)
+            .withRecordKey(userTaskKey)
+            .getFirst()
+            .getValue();
+
+    try (final var restClient =
+        ZEEBE
+            .newClientBuilder()
+            .preferRestOverGrpc(false)
+            .defaultRequestTimeout(Duration.ofSeconds(60))
```
Comment (fabiopaini-camunda) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/engine/client/command/UserTaskListenersTest.java:1072]: Am I understanding correctly that this will cause this test to always run for at least a minute waiting for the timeout to occur?

🔧 If so, it would be best to reduce it as low as possible, maybe just long enough to ensure that the job is created and thus the timeout is actually related to the listener being stuck

**Review by fabiopaini-camunda — APPROVED** [review]
Thank you @korthout for surfacing this possibility to the API documentation, greatly simplifying troubleshooting! 👍 

I added just a small comment on a test which I think risks making CI runs take longer than necessary, but I'll let you decide if it actually makes sense to edit it, meanwhile I'm approving it!

**Review by shay-matasaro-camunda — APPROVED** [review]
looks good. 
 very detailed info, which would help API users

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/engine/client/command/UserTaskListenersTest.java (hunk 1 above)
Comment (korthout) [reply zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/engine/client/command/UserTaskListenersTest.java:1072]: Great point @fabiopaini-camunda and I didn't realize it during development.

This particular timeout does not affect the duration of the test. It's just the client-side timeout (so between the client and gateway). The test expects a timeout between the gateway and broker. The default timeout is set to 15s, so by setting the client-side to 60s, it can await this timeout.

👍 I've now adjusted the test to configure the timeout used between gateway and broker to speed up the test.
