### PR TITLE
fix: Write `PI:ELEMENT_TERMINATED` event with `operationReference`

### LINKED ISSUE #31701: Process cancel operations in Operate remain in `"SENT"` state when user task has `"canceling"` listeners
### 

### 

### 

### 

### Description

When a Camunda User Task is configured with a `"canceling"` task listener, canceling the process instance via Operate causes the associated `CANCEL_PROCESS_INSTANCE` operation to remain in the `"SENT"` state, even after the process instance has been successfully canceled.

**Impact:**
- Operate shows an infinite spinner instead of "Cancel instance" button (see screenshots). This spinner never resolves, even though the process instance is successfully canceled(terminated) in the background.

Image

and:
Image

### Steps to reproduce

1. Deploy a process with a User Task that includes a `"canceling"` task listener.
2. Start a process instance and reach the user task.
3. Trigger process instance cancellation from the Operate UI.
4. Observe the following:
    - The process instance is eventually terminated (after the canceling job completes).
    - The associated cancel operation remains stuck in `"SENT"`.

Reproducible with the following test :arrow_down:
<details>
<summary><code> shouldCancelProcessInstanceWithUserTaskAfterCancelingListener </code></summary>

```java
  @Test
  void shouldCancelProcessInstanceWithUserTaskAfterCancelingListener() {
    // given
    final int operationReference = 111;
    final var listenerType = "canceling_listener";
    final var userTaskKey =
        resourcesHelper.createSingleUserTask(
            t -> t.zeebeTaskListener(l -> l.canceling().type(listenerType)));
    final var processInstanceKey =
        RecordingExporter.userTaskRecords()
            .withRecordKey(userTaskKey)
            .getFirst()
            .getValue()
            .getProcessInstanceKey();

    final JobHandler completeJob =
        (jobClient, job) ->
            client
                .newCompleteCommand(job)
                .withResult()
                .send()
                .join();
    client.newWorker().jobType(listenerType).handler(completeJob).open();

    // when: cancel process instance to trigger a canceling transition for user task
    final var cancelProcessInstanceFuture =
        client
            .newCancelInstanceCommand(processInstanceKey)
            .operationReference(operationReference)
            .send();

    ZeebeAssertHelper.assertJobCompleted(listenerType);
    assertThatCode(cancelProcessInstanceFuture::join).doesNotThrowAnyException();

    assertUserTaskIntentsSequence(
        UserTaskIntent.CANCELING, UserTaskIntent.COMPLETE_TASK_LISTENER, UserTaskIntent.CANCELED);

    assertThat(
        RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_TERMINATED)
            .withProcessInstanceKey(processInstanceKey)
            .getFirst())
        .hasOperationReference(operationReference); // ❌ fails here
  }
```
</details>

### Current behavior

Due to a missing `operationReference` on the exported `PI.ELEMENT_TERMINATED` record (after the canceling listener completes), [OperationFromProcessInstanceHandler](https://github.com/camunda/camunda/blob/d81998197f80b582622472c44a815f24a09cccaa/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/operation/OperationFromProcessInstanceHandler.java#L20) cannot correlate the termination with the triggered operation. As a result, the operation is never completed and remains in the `"SENT"` state.

### Expected behavior

The `CANCEL_PROCESS_INSTANCE` operation should transition to `"COMPLETED"` after the instance is fully canceled(terminated) and the `PI.ELEMENT_TERMINATED` record is exported.

### Environment

SaaS & SM

### Version

- Zeebe: [8.8.0-SNAPSHOT]

### Rootcause

When `"canceling"` task listeners are involved, the `operationReference` is not preserved throughout the process instance cancelation(termination) transition lifecycle. This prevents the [exporter](https://github.com/camunda/camunda/blob/d81998197f80b582622472c44a815f24a09cccaa/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/operation/OperationFromProcessInstanceHandler.java#L20) from completing the original operation.

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

This issue has the same root cause as #30686, when `"updating"` task listeners are involved.

### PR DESCRIPTION
**Pull request by ce-dmelnych**
> [!TIP]
> For clarity, this PR was intentionally split into focused commits.
Reviewing it commit-by-commit (rather than as one diff) will make it easier to understand the purpose and motivation of each change.

## Description

This PR was build on the mechanisms introduced in #32687 and #30686 PRs to preserve and provide `operationReference` in `ProcessInstance:ELEMENT_TERMINATED` event.

### Problem

When canceling a process instance that includes a user task with a `canceling` listener, the final `ProcessInstance:ELEMENT_TERMINATED` event lacked the original `operationReference` passed via the `ProcessInstance:CANCEL` command.

As a result, Operate was unable to correlate the `ProcessInstance:ELEMENT_TERMINATED` event with the user-triggered operation. The cancel operation remained stuck in `"SENT"` state, leaving the UI in a perpetual loading state — despite the process being successfully terminated by the engine.

### Solution

This PR:

- Writes `AsyncRequest:RECEIVED` event on handling `ProcessInstance:CANCEL` command to capture the request metadata
- Leverages `FollowUpEventMetadata` to enrich `PI:ELEMENT_TERMINATED` events with the original `operationReference` from `AsyncRequestMetadata`
- Writes `AsyncRequest:PROCESSED` event after `PI:ELEMENT_TERMINATED` to make clean metadata of `PI:CANCEL` request
- Ensures only one cancel request per process instance is allowed by rejecting duplicate `PI:CANCEL` commands
- Refactors `ProcessProcessor` and `BpmnStateTransitionBehavior` to support request metadata-aware flow

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)
  - [ ] enable backports [when recommended](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)

## Related issues

closes #31701

### CODE REVIEW

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/OperationReferenceTest.java [hunk 1]
```diff
@@ -149,6 +149,47 @@ void shouldAcceptNegativeOneAsOperationReference() {
...
+        .open();
+
+    // When
+    final var cancelFuture =
+        client
+            .newCancelInstanceCommand(processInstanceKey)
+            .operationReference(OPERATION_REFERENCE)
+            .send();
+
+    assertThatCode(cancelFuture::join).doesNotThrowAnyException();
```
Comment (mustafadagher) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/OperationReferenceTest.java]: 🔧 [nitpicking] this can be `assumeThat()`, since this is not a condition we are testing here

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceCancelProcessor.java [hunk 2]
```diff
@@ -131,6 +138,16 @@ private boolean validateCommand(
       return false;
     }
 
+    final var existingAsyncRequest =
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceCancelProcessor.java:141]: 👍

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceCommandRejectionTest.java [hunk 3]
```diff
@@ -653,6 +649,12 @@ private void assertThatCommandIsRejected(
             .withProcessInstanceKey(command.getValue().getProcessInstanceKey())
             .getFirst();
 
+    System.out.println(
+        "DMK: source record position: "
+            + rejection.getSourceRecordPosition()
+            + ", position: "
+            + rejection.getPosition());
+
```
Comment (mustafadagher) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceCommandRejectionTest.java]: ❌ please remove the print line before merging

**Review by mustafadagher — APPROVED** [review]
LGTM! 🚀 

I left one comment to remove the `sysout`, please remove it before merging

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/OperationReferenceTest.java (hunk 1 above)
Comment (ce-dmelnych) [reply zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/OperationReferenceTest.java]: 👍🏻 Thanks for the suggestion, Mustafa!
I've updated the new tests in this class to drop redundant assertions like `assertThatCode(...).doesNotThrowAnyException()` and now focus only on the relevant operationReference verifications.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceCommandRejectionTest.java (hunk 3 above)
Comment (ce-dmelnych) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceCommandRejectionTest.java]: :man_facepalming:

**Review by mustafadagher — APPROVED** [review]
Thanks @ce-dmelnych ! Looks good 🎉
