### PR TITLE
fix: prevent ActivateJobsCommand timeout before the server

### LINKED ISSUE #28466: Job Activation via REST Times Out When No Job is Available
### Description

When making use of REST in the java client to activate a job and. when no job is available, the request times out instead of returning a response.

Logs:
```
10:04:20.976 [httpclient-dispatch-1] WARN io.camunda.client.job.poller -- Failed to activate jobs for worker default and job type test
io.camunda.zeebe.client.api.command.ClientException: java.net.SocketTimeoutException: 10000 MILLISECONDS
	at io.camunda.zeebe.client.impl.http.ApiCallback.failed(ApiCallback.java:71)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:166)
	...
Caused by: java.net.SocketTimeoutException: 10000 MILLISECONDS
	at org.apache.hc.core5.io.SocketTimeoutExceptionFactory.create(SocketTimeoutExceptionFactory.java:50)
	...
```

**Affects all versions >= 8.6**

[Slack discussion](https://camunda.slack.com/archives/CSQ2E3BT4/p1740042805607769)

### Expected Behavior:

The request should not time out but instead return an appropriate response when no jobs are available.

### Root cause

The default request timeout configured in the client is set to 10 seconds https://github.com/camunda/camunda/blob/bec770767d0f14b2b82b909297e13082d367a84a/clients/java/src/main/java/io/camunda/client/impl/CamundaClientBuilderImpl.java#L107
which is the same value as the default long polling timeout configured in the server side https://github.com/camunda/camunda/blob/bec770767d0f14b2b82b909297e13082d367a84a/zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/configuration/ConfigurationDefaults.java#L27

That makes the client timing out just before receiving a response from the server

### Potential Fix:

We may want to consider increasing the default request timeout of the client. However, this timeout applies to all commands used by the client, so we should evaluate the impact.

### PR DESCRIPTION
**Pull request by danielkelemen**
## Description

- Configure ActivateJobsCommand's response timeout slightly higher than the request timeout
- Add client/java property for activate jobs response timeout offset

## Related issues

closes https://github.com/camunda/camunda/issues/28466

### CODE REVIEW

**Comment by danielkelemen** [comment]
### Notes

I decided to just increment the client response timeout for the `ActivateJobsCommand`:
- No change in the global timeout that would impact all commands.
- The response timeout is incremented by 100ms.
  - This is also applied if a user changes the global or the command specific timeout.

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/ActivateJobsTest.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+import io.camunda.client.CamundaClient;
+import io.camunda.qa.util.multidb.MultiDbTest;
+import java.time.Duration;
+import org.junit.jupiter.api.Test;
+
+@MultiDbTest
+public class ActivateJobsTest {
```
Comment (tmetzke) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/ActivateJobsTest.java:18]: 💭 We already have [this test class](https://github.com/camunda/camunda/blob/955dd34fb9e82817d5599d3bcb5a7d939e05755d/zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/ActivateJobsTest.java#L65) for job activation tests. I think we don't need a multi-DB test for this as this is not DB-specific. 

The test in there for activation without jobs already works. Can we try to find out why that works but fails in production setups so we can hopefully create something reproducible that we can fix afterward? 😅

File: clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java [hunk 2]
```diff
@@ -142,7 +142,8 @@ public FinalCommandStep<ActivateJobsResponse> requestTimeout(final Duration requ
     grpcRequestObjectBuilder.setRequestTimeout(requestTimeout.toMillis());
     httpRequestObject.setRequestTimeout(requestTimeout.toMillis());
     this.requestTimeout = requestTimeout;
-    httpRequestConfig.setResponseTimeout(requestTimeout.toMillis(), TimeUnit.MILLISECONDS);
+    // increment response timeout so client doesn't time out before the server
+    httpRequestConfig.setResponseTimeout(requestTimeout.toMillis() + 100, TimeUnit.MILLISECONDS);
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java:146]: 💭 Generally makes sense. I am wondering though if 100ms make enough of a difference and how we'll determine what duration makes the decisive difference 😅 

💭 Another thought: this is set by users to define how long we want to wait for a response. Should we give the server less time to find something instead of silently increasing the client timeout? That would mean sending a lower value to the server than provided by the user to account for the threshold we need to make the call work.

**Review by tmetzke — COMMENTED** [review]
👍 Generally looks fine but there are some considerations we could make here.

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/ActivateJobsTest.java (hunk 1 above)
Comment (danielkelemen) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/ActivateJobsTest.java:18]: I didn't notice this test yet. The test I wrote did fail first, so that does reproduce it correctly.

`@MultiDbTest` is a good point.

I'll check what the problem with the already existing test is.

File: clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java (hunk 2 above)
Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java:146]: > Should we give the server less time to find something instead of silently increasing the client timeout? That would mean sending a lower value to the server than provided by the user to account for the threshold we need to make the call work.

I feel like both have some disadvantages.
- The one you mentioned, that we silently increase it and users might wonder why isn't the time out exactly at the configured value.
- If we set a lower one on the server, then the timeout will be in fact shorter what they set up.

I guess in either case we should document it on the `requestTimeout` method.

I personally find the first one (increasing the response timeout) less confusing. In this case it is a request property, it's also explained in API docs so users probably expect it to be exactly what they configured. And the response timeout being slightly more won't have a huge impact, the client might wait slightly longer but they will receive the jobs with correct timeout.

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/ActivateJobsTest.java (hunk 1 above)
Comment (danielkelemen) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/ActivateJobsTest.java]: Fixed and extended the linked test, long polling was disabled.
Removed the unnecessary new test.

File: clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java (hunk 2 above)
Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java:146]: > I am wondering though if 100ms make enough of a difference and how we'll determine what duration makes the decisive difference

This is a good question. In the tests 100ms appears to be enough, even less would be enough but there is obviously no network delay. I'm not sure how we could determine the best value. I could imagine use-cases with high latency still experiencing timeout with 100ms but also in most of the use-cases it is probably high enough.
Maybe we should make this configurable, too?

Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java:146]: Adding to the second point, we could also make it 500ms or one second even. If people need tighter client-side timeouts (do people, though?), they can reduce it. That way, it's more resilient and users can still lower the additional timeout if needed.

Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java:146]: In the end, the server has the correct timeout and will respond anyway almost in time with a small delay in most cases. So having an extra 1s margin on the client side simply makes it safer in higher-latency cases.

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/ActivateJobsTest.java [hunk 3]
```diff
@@ -62,14 +62,41 @@ void shouldRespondActivatedJobsWhenJobsAreAvailable(
...
+
+  @ParameterizedTest
+  @ValueSource(booleans = {true, false})
+  public void shouldReturnEmptyListOnUserDefinedCommandRequestTimeout(final boolean useRest) {
+    // when
+    final var actual =
+        getCommand(client, useRest)
+            .jobType("notExisting")
+            .maxJobsToActivate(1)
+            .requestTimeout(Duration.ofSeconds(5))
```
Comment (tmetzke) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/ActivateJobsTest.java:94]: ❓ Will this make the test last 5 seconds each time? 😄 Don't get caught for wasting that much CI time!

File: clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java (hunk 2 above)
Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java:146]: Yes, I agree too.
I will set it to 1 second and create a config for it. (What should be the name🤔)

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/ActivateJobsTest.java (hunk 3 above)
Comment (danielkelemen) [reply zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/ActivateJobsTest.java:94]: Yes, it blocks the test for 5 seconds :) I'll lower it to 1sec.

File: clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java (hunk 2 above)
Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java]: Decremented test timeout to 1s and added a new config param `activateJobsResponseTimeoutOffset`.

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java [hunk 4]
```diff
@@ -145,6 +145,12 @@ CamundaClientBuilder jobWorkerExecutor(
   /** The request timeout used if not overridden by the command. Default is 10 seconds. */
   CamundaClientBuilder defaultRequestTimeout(Duration requestTimeout);
 
+  /**
+   * The {@link io.camunda.client.impl.command.ActivateJobsCommandImpl}'s response timeout offset.
+   * Default is 1 second.
+   */
+  CamundaClientBuilder defaultActivateJobsResponseTimeoutOffset(Duration responseTimeoutOffset);
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:152]: 🔧 To align it with the above, I guess it should be **request** timeout, not response timeout?

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java [hunk 5]
```diff
@@ -145,6 +145,12 @@ CamundaClientBuilder jobWorkerExecutor(
   /** The request timeout used if not overridden by the command. Default is 10 seconds. */
   CamundaClientBuilder defaultRequestTimeout(Duration requestTimeout);
 
+  /**
+   * The {@link io.camunda.client.impl.command.ActivateJobsCommandImpl}'s response timeout offset.
+   * Default is 1 second.
```
Comment (tmetzke) [inline clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:150]: 🔧 Let's provide a bit more context what this does, e.g. why this offset is needed.

Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:150]: Hm, hard to say, actually. We set the response timeout in the HTTP request, not the request timeout. For the client user it might be confusing though to use response timeout here now.

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java (hunk 4 above)
Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:152]: Hm, hard to say, actually. We set the response timeout in the HTTP request, not the request timeout. For the client user it might be confusing though to use response timeout here now.

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java (hunk 5 above)
Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:150]: You have a good explanation in `ActivateJobsCommandStep1`. Let's move this here maybe, and reference it from there?
I was also wondering if we should name this more generally, maybe just `defaultRequestTimeoutOffset`? We can explain that this can be used by commands if they pass on the timeout to the called server to avoid the client request timing out before it receives a response due to network latency. We can state that this is not used by all commands by default but just in such cases. Wdyt?

File: clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java (hunk 2 above)
Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/impl/command/ActivateJobsCommandImpl.java]: Nice!

**Review by tmetzke — COMMENTED** [review]
👍 Code looks good to me, nice job! 🚀 
💭 Let's figure out naming and Javadoc, and we're good to go here

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java (hunk 4 above)
Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:152]: Yes, I was about to say that this config is used in the HTTP response timeout. So it's the client side timeout.

Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:152]: But yeah, the `defaultRequestTimeout` is also used in HTTP response timeout for all  commands. I guess then it is confusing, I'll just call it requestTimeout, too.

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java (hunk 5 above)
Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:150]: We could make it generic, maybe something else will use this, too. I'll also add the list the commands that use this, right now only ActivateJobs.

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java (hunk 4 above)
Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:152]: I'm thinking about `defaultRequestTimeoutClientOffset`.

Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:152]: But we are in the client builder, so we're setting the request timeout offset for the client already, aren't we? 😆

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java (hunk 5 above)
Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java:150]: I would vote for not listing them in the docs. It will get outdated and you can also search for code usages and find the command(s) that use it, I guess?

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java (hunk 4 above)
Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java]: Well yes, but we also use the `defaultRequestTimeout` on the server.
Idk..

File: clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java (hunk 5 above)
Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java]: They could for sure find it out from the code, I just wanted to be nice. 😄

Comment (tmetzke) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java]: Yeah, I know, but it will backfire, I can already feel it 🤣

Comment (danielkelemen) [reply clients/java/src/main/java/io/camunda/client/CamundaClientBuilder.java]: Dropped it

**Review by tmetzke — APPROVED** [review]
🚀

**Comment by tmetzke** [comment]
Should we backport this to the Zeebe client as well?

**Comment by tmetzke** [comment]
> > Should we backport this to the Zeebe client as well?
> 
> I could try, I suspect the automatic might not work due to changes. To 8.7 only, or 8.6 too?

Let's try with 8.7 first. It might actually just work since we made changes mostly to classes that exist in 8.7 but have been moved from git's perspective in 8.8. When 8.7 is fine, we backport to 8.6 from there. I think this doesn't exist yet in 8.5.

**Comment by tmetzke** [comment]
Well, looks like it wasn't able to backport it, you win 😆

**Comment by danielkelemen** [comment]
No winner here 😄
I can create backports next week, shouldn't be a huge effort to do it manually.
