### PR TITLE
fix(broker): merge variable on output mapping

### LINKED ISSUE #3621: Output Parameters with result dict
Hi guys.
I'm create process with two steps. 
First step option output parameters:
`price : result.price`

after i see response `{"result":{"price":100}}`
Seconds step option output parameters:
`amount : result.amount`
and after i see `{"result":{"amount":1200}}`

But  i want to see response `{"result":{"price":100,"amount":1200}}`

### PR DESCRIPTION
**Pull request by saig0**
## Description

* a document variable is merged using an output mapping that adds a new entry to the document, instead of replacing the document

## Related issues

closes #3621 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: engine/src/main/java/io/zeebe/engine/processor/workflow/deployment/model/element/ExecutableFlowNode.java [hunk 1]
```diff
@@ -16,8 +16,8 @@
   private final List<ExecutableSequenceFlow> incoming = new ArrayList<>();
   private final List<ExecutableSequenceFlow> outgoing = new ArrayList<>();
 
-  private Mapping[] inputMappings = new Mapping[0];
-  private Mapping[] outputMappings = new Mapping[0];
+  private Mappings inputMappings = new Mappings();
```
Comment (Zelldon) [inline engine/src/main/java/io/zeebe/engine/processor/workflow/deployment/model/element/ExecutableFlowNode.java]: Why we haven't used that before ? :thinking:

File: engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java [hunk 2]
```diff
@@ -45,34 +48,56 @@
...
 
-    if (hasOutputMappings) {
-      mergeTool.reset();
-
-      final DirectBuffer variables =
-          determineVariables(variablesState, elementInstanceKey, outputMappings);
-
-      mergeTool.mergeDocumentStrictly(variables, outputMappings);
-      final DirectBuffer mergedVariables = mergeTool.writeResultToBuffer();
+    if (!outputMappings.isEmpty()) {
```
Comment (Zelldon) [inline engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: I like to have these kind of variables `hasOutputMappings` the `!` are often overseen

File: engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java [hunk 3]
```diff
@@ -45,34 +48,56 @@
...
+    // fetch the variables from the target mappings to allow merging with existing variables
+    final DirectBuffer targetVariables =
+        variablesState.getVariablesAsDocument(
+            elementInstanceKey, outputMappings.getTargetVariableNames());
+
+    // copy variables to not override them with next variable state access
+    buffer.putBytes(0, targetVariables, 0, targetVariables.capacity());
+    bufferView.wrap(buffer, 0, targetVariables.capacity());
+
+    mergeTool.mergeDocument(bufferView);
```
Comment (Zelldon) [inline engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: this is the old index right ? :sweat_smile:

File: engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java [hunk 4]
```diff
@@ -45,34 +48,56 @@
...
+    if (!outputMappings.isEmpty()) {
+      final DirectBuffer mergedVariables =
+          mergeOutputVariables(variablesState, elementInstanceKey, outputMappings);
 
       variablesState.setVariablesFromDocument(
           getVariableScopeKey(context), workflowKey, mergedVariables);
     }
   }
 
+  private DirectBuffer mergeOutputVariables(
```
Comment (Zelldon) [inline engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: I'm wondering why we haven't found this issue before :sweat_smile:

File: engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java [hunk 5]
```diff
@@ -45,34 +48,56 @@
...
+    buffer.putBytes(0, targetVariables, 0, targetVariables.capacity());
+    bufferView.wrap(buffer, 0, targetVariables.capacity());
+
+    mergeTool.mergeDocument(bufferView);
+
+    final DirectBuffer sourceVariables =
+        variablesState.getVariablesAsDocument(
+            elementInstanceKey, outputMappings.getSourceVariableNames());
+
+    mergeTool.mergeDocumentStrictly(sourceVariables, outputMappings.get());
```
Comment (Zelldon) [inline engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: Do you remember why this is called strictly ? :sweat_smile:

File: json-path/src/test/java/io/zeebe/msgpack/mapping/MappingMergeParameterizedTest.java [hunk 6]
```diff
@@ -322,25 +322,6 @@
             // expected result
             "{'obj':{'test':'value','newFoo':1},'int':1}"
           },
-          // 37. Test zeebe-io/zeebe#297
```
Comment (Zelldon) [inline json-path/src/test/java/io/zeebe/msgpack/mapping/MappingMergeParameterizedTest.java]: why :sweat_smile:

File: json-path/src/main/java/io/zeebe/msgpack/mapping/Mappings.java [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+ */
+package io.zeebe.msgpack.mapping;
+
+import io.zeebe.msgpack.jsonpath.JsonPathQuery;
+import java.util.Arrays;
+import java.util.Set;
+import java.util.stream.Collectors;
+import org.agrona.DirectBuffer;
+
+public class Mappings {
```
Comment (Zelldon) [inline json-path/src/main/java/io/zeebe/msgpack/mapping/Mappings.java]: I thought we had this utility before :see_no_evil: :D

File: engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/MessageOutputMappingTest.java [hunk 8]
```diff
@@ -104,6 +104,12 @@
         activityVariables(tuple("x", "{\"y\":2}")),
         scopeVariables(tuple("y", "2"))
       },
+      {
```
Comment (Zelldon) [inline engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/MessageOutputMappingTest.java]: This test is green without the fix :thinking:

File: engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/JobOutputMappingTest.java [hunk 9]
```diff
@@ -100,6 +100,12 @@
         activityVariables(tuple("x", "{\"y\":2}")),
         scopeVariables(tuple("y", "2"))
       },
+      {
```
Comment (Zelldon) [inline engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/JobOutputMappingTest.java]: This test is green without the fix :thinking:

File: engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/ActivityOutputMappingTest.java [hunk 10]
```diff
@@ -72,6 +72,16 @@
         scopeVariables(tuple("z", "{\"y\":2}"))
       },
       {"{'x': {'y': 2}}", mapping(b -> b.zeebeOutput("x.y", "z")), scopeVariables(tuple("z", "2"))},
+      {
+        "{'z': {'x': 1}, 'y': 2}",
+        mapping(b -> b.zeebeOutput("y", "z.y")),
+        scopeVariables(tuple("z", "{\"x\":1,\"y\":2}"))
+      },
+      {
+        "{'x': 1, 'y': 2}",
```
Comment (Zelldon) [inline engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/ActivityOutputMappingTest.java]: This test is green without the fix :thinking:

File: engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/ActivityOutputMappingTest.java [hunk 11]
```diff
@@ -72,6 +72,16 @@
         scopeVariables(tuple("z", "{\"y\":2}"))
       },
       {"{'x': {'y': 2}}", mapping(b -> b.zeebeOutput("x.y", "z")), scopeVariables(tuple("z", "2"))},
+      {
+        "{'z': {'x': 1}, 'y': 2}",
+        mapping(b -> b.zeebeOutput("y", "z.y")),
```
Comment (Zelldon) [inline engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/ActivityOutputMappingTest.java]: This is the only one which failed without the fix :sweat_smile:

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Hey @saig0 thanks for fixing this! I have just some comments/questions :smile:

File: json-path/src/main/java/io/zeebe/msgpack/mapping/Mappings.java (hunk 7 above)
Comment (Zelldon) [reply json-path/src/main/java/io/zeebe/msgpack/mapping/Mappings.java]: I like it :+1:

File: engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java (hunk 3 above)
Comment (saig0) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: What do you mean with old index? 
By calling `mergeDocument(...)` without any mapping, it passes all variables to the result document. Then merging the other variables on top.

Comment (Zelldon) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: In the past the method was called index. For me it looks weird  that it is called merge but anyhow.

File: engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java (hunk 4 above)
Comment (saig0) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: Yeah :see_no_evil:

File: engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java (hunk 5 above)
Comment (saig0) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: I checked it. `Strictly` means here that an exception is thrown when a mapping cannot be applied (i.e. no variable or nested property with the given name). The other method doesn't fail in this case. But it seems that we don't use the non-strict version of this anywhere :thinking:

Comment (Zelldon) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: Ah ok thanks. Maybe we can delete it in a separate issue?

File: engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java (hunk 3 above)
Comment (saig0) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: Agree. A good topic for another day :sweat_smile:

File: engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java (hunk 5 above)
Comment (saig0) [reply engine/src/main/java/io/zeebe/engine/processor/workflow/handlers/IOMappingHelper.java]: Sure. I'll try to remove it :wastebasket:

File: json-path/src/test/java/io/zeebe/msgpack/mapping/MappingMergeParameterizedTest.java (hunk 6 above)
Comment (saig0) [reply json-path/src/test/java/io/zeebe/msgpack/mapping/MappingMergeParameterizedTest.java]: I deleted the test case because it was outdated since a while :smile:

Comment (Zelldon) [reply json-path/src/test/java/io/zeebe/msgpack/mapping/MappingMergeParameterizedTest.java]: ok :smile:

File: engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/ActivityOutputMappingTest.java (hunk 11 above)
Comment (saig0) [reply engine/src/test/java/io/zeebe/engine/processor/workflow/variable/mapping/ActivityOutputMappingTest.java]: Correct. It would be more work to write a similar test for message and job. However, the other case (two variables into one document) was not tested yet. So, I think it is good to have one ;)

**Comment by saig0** [comment]
@Zelldon, I applied your hints and removed the non-strict merging method. Please have a look.

**Review by ChrisKujawa — APPROVED** [review]
thanks @saig0 :+1:
