### PR TITLE
Remove service container

### LINKED ISSUE #788: Timeout for composite service installations
related to #782 

When installing a composite service, one or multiple of the services may fail to install. In that case, it would be nice to be able to specify a timeout after which the operation is cancelled and all the other services are taken down again.

This can then be used to replace the "required start actions" on broker start

### LINKED ISSUE #999: The lifecyclePhase in ActorTask is not volatile
We should validate if this is a real problem. See for example `ActorTask#tryWait`,  where it is checked and another thread could have waken up the task already again (is this flag written concurrently?).

### LINKED ISSUE #2400: Atomix port is not released properly in the tests
In the CI it often happens that we see the following exception or test fail:

```java
java.lang.RuntimeException: Deployment partition not installed into the container within 15 SECONDS.
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:258)
	at io.zeebe.broker.test.EmbeddedBrokerRule.before(EmbeddedBrokerRule.java:151)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.util.concurrent.TimeoutException: Timeout after: 15 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:145)
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:253)
	... 30 more
```

Which is in most cases caused by:

```java

08:14:27.040 [] [netty-messaging-event-epoll-server-0] WARN  io.atomix.cluster.messaging.impl.NettyMessagingService - Failed to bind TCP server to port 0.0.0.0:25811 due to io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
08:14:27.041 [service-controller] [0.0.0.0:25807-zb-actors-1] ERROR io.zeebe.servicecontainer - Service failed to start while in AwaitStartState
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:700) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_212]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bind$31(NettyMessagingService.java:569) ~[atomix-cluster-3.2.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1018) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:565) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:488) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:473) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-transport-native-unix-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.unix.Socket.bind(Socket.java:287) ~[netty-transport-native-unix-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.doBind(AbstractEpollChannel.java:686) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar:4.1.34.Final]
	at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:70) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	... 11 more
08:14:27.058 [service-container-main] [0.0.0.0:25807-zb-actors-0] ERROR io.zeebe.servicecontainer - Failed to build service
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:700) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_212]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bind$31(NettyMessagingService.java:569) ~[atomix-cluster-3.2.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1018) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:565) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:488) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:473) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-transport-native-unix-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.unix.Socket.bind(Socket.java:287) ~[netty-transport-native-unix-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.doBind(AbstractEpollChannel.java:686) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar:4.1.34.Final]
	at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:70) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
```

### LINKED ISSUE #2749: Should we replace or refactor the ServiceContainer
We should think about whether we want to maintain the service container as our own dependency injection and management framework and refactor it or move to a more common solution which is widely used and proved.

If we want to keep the service container I think we should take a look whether we can refactor it,
since the complexity of the implementation is high and not easy to understand or follow.
Furthermore to install a service we need a lot of boilerplate code, which is not ideal. See for example the `EngineService`:

```java

public class EngineService implements Service<EngineService> {

  private final Injector<ServerTransport> commandApiTransportInjector = new Injector<>();
  private final Injector<TopologyManager> topologyManagerInjector = new Injector<>();
  private final Injector<Atomix> atomixInjector = new Injector<>();

  private ServerTransport commandApiTransport;
  private TopologyManager topologyManager;
  private Atomix atomix;
  private final ServiceGroupReference<Partition> partitionsGroupReference =
      ServiceGroupReference.<Partition>create().onAdd(this::startEngineForPartition).build();

  public EngineService(ServiceContainer serviceContainer, BrokerCfg brokerCfg) {
    clusterCfg = brokerCfg.getCluster();

    this.serviceContainer = serviceContainer;
    final DataCfg dataCfg = brokerCfg.getData();
    this.snapshotPeriod = DurationUtil.parse(dataCfg.getSnapshotPeriod());
  }

  @Override
  public void start(final ServiceStartContext serviceContext) {
    this.serviceContext = serviceContext;
    this.commandApiTransport = commandApiTransportInjector.getValue();
    this.topologyManager = topologyManagerInjector.getValue();
    this.atomix = atomixInjector.getValue();
  }

 // ...


  @Override
  public EngineService get() {
    return this;
  }

  public Injector<ServerTransport> getCommandApiTransportInjector() {
    return commandApiTransportInjector;
  }

  public ServiceGroupReference<Partition> getPartitionsGroupReference() {
    return partitionsGroupReference;
  }

  public Injector<TopologyManager> getTopologyManagerInjector() {
    return topologyManagerInjector;
  }

  public Injector<Atomix> getAtomixInjector() {
    return atomixInjector;
  }
```

And installing the service then looks like this:

```java

    final EngineService streamProcessorService =
        new EngineService(serviceContainer, brokerConfiguration);
    serviceContainer
        .createService(ENGINE_SERVICE_NAME, streamProcessorService)
        .dependency(
            TransportServiceNames.serverTransport(TransportServiceNames.COMMAND_API_SERVER_NAME),
            streamProcessorService.getCommandApiTransportInjector())
        .dependency(
            ClusterBaseLayerServiceNames.TOPOLOGY_MANAGER_SERVICE,
            streamProcessorService.getTopologyManagerInjector())
        .dependency(
            ClusterBaseLayerServiceNames.ATOMIX_SERVICE, streamProcessorService.getAtomixInjector())
        .groupReference(
            ClusterBaseLayerServiceNames.LEADER_PARTITION_GROUP_NAME,
            streamProcessorService.getPartitionsGroupReference())
        .install();
```

I think if we use a different framework or just refactor the container, we could write the dependencies and service like this.

```java
@Service
public class EngineService implements Service<EngineService> {

  private final ClusterCfg clusterCfg;
  private final Duration snapshotPeriod;
  private ServiceStartContext serviceContext;

  private ServerTransport commandApiTransport;
  private TopologyManager topologyManager;
  private Atomix atomix;
  private BrokerCfg brokerCfg;

  @Inject
  public EngineService(
      ServerTransport commandApiTransport,
      TopologyManager topologyManager,
      Atomix atomix,
      BrokerCfg brokerCfg) {
    this.commandApiTransport = commandApiTransport;
    this.topologyManager = topologyManager;
    this.atomix = atomix;
    final DataCfg dataCfg = brokerCfg.getData();
    this.snapshotPeriod = DurationUtil.parse(dataCfg.getSnapshotPeriod());
  }
```

### LINKED ISSUE #3295: EmbeddedBrokerRule#startBroker sometimes times out
**Describe the bug**

It happens that waiting for the deployment partition to be installed in the container sometimes fails, and the start of the broker times out. Whether this is a bug or an issue with our test setup is to be investigated.

**To Reproduce**

Happens in CI with the following test: `io.zeebe.broker.it.network.LargeMessageSizeTest`

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Deployment partition not installed into the container within 15 SECONDS.
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:238)
	at io.zeebe.broker.test.EmbeddedBrokerRule.before(EmbeddedBrokerRule.java:135)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.util.concurrent.TimeoutException: Timeout after: 15 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131)
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:233)
	... 22 more
```

</p>
</details>

<details><summary>Standard output</summary>
<p>

```
17:26:35.351 [] [main] INFO  io.zeebe.test.util.SocketUtil - Starting socket assignment with testForkNumber 1 and testMavenId 2
17:26:35.555 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 26800 for test fork 1 with range PortRange{host='localhost', basePort=26800, maxOffset=100, currentOffset=1}
17:26:35.558 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 26801 for test fork 1 with range PortRange{host='localhost', basePort=26800, maxOffset=100, currentOffset=2}
17:26:35.560 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 26802 for test fork 1 with range PortRange{host='localhost', basePort=26800, maxOffset=100, currentOffset=3}
17:26:35.570 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 26803 for test fork 1 with range PortRange{host='localhost', basePort=26800, maxOffset=100, currentOffset=4}
17:26:35.572 [] [main] INFO  io.zeebe.test.util.SocketUtil - Choosing next port 26804 for test fork 1 with range PortRange{host='localhost', basePort=26800, maxOffset=100, currentOffset=5}
17:26:35.582 [] [main] DEBUG io.zeebe.broker.system - Initializing configuration with base path /tmp/9401e17b-a8e0-4020-be1a-e5d4229d72b6
17:26:36.139 [] [main] INFO  io.zeebe.broker.system - Version: 0.22.0-SNAPSHOT
17:26:36.359 [] [main] INFO  io.zeebe.broker.system - Starting broker with configuration {
  "network": {
    "host": "0.0.0.0",
    "portOffset": 0,
    "maxMessageSize": "4M",
    "commandApi": {
      "defaultPort": 26501,
      "host": "0.0.0.0",
      "port": 26802,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 26802
    },
    "internalApi": {
      "defaultPort": 26502,
      "host": "0.0.0.0",
      "port": 26803,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 26803
    },
    "monitoringApi": {
      "defaultPort": 9600,
      "host": "0.0.0.0",
      "port": 26804,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 26804
    }
  },
  "cluster": {
    "initialContactPoints": [],
    "partitionIds": [
      1
    ],
    "nodeId": 0,
    "partitionsCount": 1,
    "replicationFactor": 1,
    "clusterSize": 1,
    "clusterName": "zeebe-cluster"
  },
  "threads": {
    "cpuThreadCount": 2,
    "ioThreadCount": 2
  },
  "data": {
    "directories": [
      "/tmp/9401e17b-a8e0-4020-be1a-e5d4229d72b6/data"
    ],
    "logSegmentSize": "512M",
    "snapshotPeriod": "15m",
    "raftSegmentSize": "512M",
    "maxSnapshots": 3
  },
  "exporters": [
    {
      "id": "test-recorder",
      "className": "io.zeebe.test.util.record.RecordingExporter"
    }
  ],
  "gateway": {
    "enable": true,
    "network": {
      "host": "0.0.0.0",
      "port": 26800
    },
    "cluster": {
      "contactPoint": "0.0.0.0:26803",
      "maxMessageSize": "4M",
      "requestTimeout": "15s",
      "clusterName": "zeebe-cluster",
      "memberId": "gateway",
      "host": "0.0.0.0",
      "port": 26801
    },
    "threads": {
      "managementThreads": 1
    },
    "monitoring": {
      "enabled": false,
      "host": "0.0.0.0",
      "port": 9600
    },
    "security": {
      "enabled": false
    }
  },
  "backpressure": {
    "enabled": true,
    "useWindowed": true,
    "algorithm": "vegas"
  }
}
17:26:37.641 [service-controller] [0.0.0.0:26802-zb-actors-1] INFO  io.zeebe.transport - Bound commandApi.server to /0.0.0.0:26802
17:26:38.162 [service-controller] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.broker.clustering - Setup atomix node in cluster zeebe-cluster
17:26:47.840 [service-controller] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.broker.clustering - Adding Node{nodeId=0, commandApi=0.0.0.0:26802} to list of known members
17:26:47.845 [] [zb-blocking-task-runner-1-0.0.0.0:26802] INFO  io.zeebe.gateway - Version: 0.22.0-SNAPSHOT
17:26:47.848 [] [zb-blocking-task-runner-1-0.0.0.0:26802] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "enable": true,
  "network": {
    "host": "0.0.0.0",
    "port": 26800
  },
  "cluster": {
    "contactPoint": "0.0.0.0:26803",
    "maxMessageSize": "4M",
    "requestTimeout": "15s",
    "clusterName": "zeebe-cluster",
    "memberId": "gateway",
    "host": "0.0.0.0",
    "port": 26801
  },
  "threads": {
    "managementThreads": 1
  },
  "monitoring": {
    "enabled": false,
    "host": "0.0.0.0",
    "port": 9600
  },
  "security": {
    "enabled": false
  }
}
17:26:49.667 [] [atomix-cluster-events] DEBUG io.zeebe.broker.clustering - Broker 0 received new event of type MEMBER_ADDED and subject BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=1, replicationFactor=1, partitionRoles={}}
17:26:49.678 [GatewayTopologyManager] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.gateway - Gateway received new event of type: MEMBER_ADDED and subject BrokerInfo{nodeId=0, partitionsCount=1, clusterSize=1, replicationFactor=1, partitionRoles={}} 
17:26:49.750 [GatewayTopologyManager] [0.0.0.0:26802-zb-actors-0] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '0' with address '0.0.0.0:26802' on transport 'gateway-broker-client'
17:26:51.956 [] [raft-server-system-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.protocols.raft.roles.FollowerRole$$Lambda$475/0x0000000840416c40@10995d12 not registered
17:26:55.358 [] [raft-server-raft-atomix-partition-1] WARN  io.atomix.utils.event.ListenerRegistry - Listener io.atomix.protocols.raft.roles.FollowerRole$$Lambda$475/0x0000000840416c40@56798131 not registered
17:26:57.255 [service-controller] [0.0.0.0:26802-zb-actors-1] DEBUG io.zeebe.broker.clustering - Broker 0 created leader election service for partition 1.
17:26:57.267 [partition-1-leader-election] [0.0.0.0:26802-zb-actors-1] DEBUG io.zeebe.broker.clustering - Partition role transitioning from null to LEADER
17:26:57.270 [PartitionInstallService] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.broker.clustering - Removing follower partition service for partition 1
17:26:57.335 [PartitionInstallService] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.broker.clustering - Installing leader partition service for partition 1
17:26:57.353 [] [raft-server-raft-atomix-partition-1-state] DEBUG io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Configuring distributed-log on node 0 with logName raft-atomix-partition-1
17:26:57.634 [] [raft-server-raft-atomix-partition-1-state] DEBUG io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Configured with LogStream raft-atomix-partition-1 and last appended event at position -1
17:26:58.041 [] [raft-server-raft-atomix-partition-1-state] DEBUG io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-1 - Broker 0 claiming leadership for partition 1 at term 1.
17:26:58.042 [] [raft-partition-group-raft-atomix-3] DEBUG io.zeebe.distributedlog.impl.DistributedLogstreamPartition - Broker 0 claimed leadership for partition 1
17:27:00.767 [service-controller] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: []
17:27:05.652 [service-controller] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/9401e17b-a8e0-4020-be1a-e5d4229d72b6/data/partition-1/state/runtime'.
17:27:06.147 [] [main] INFO  io.zeebe.broker.system - Broker shutting down...
17:27:06.175 [service-container-main] [0.0.0.0:26802-zb-actors-1] DEBUG io.zeebe.servicecontainer - Removed service exporter.manager
17:27:06.350 [service-controller] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Started restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
17:27:06.352 [service-controller] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.broker.logstreams.restore.BrokerRestoreServer - Closed restore server for topics: log-replication-1, restore-info-1, snapshot-request-1, snapshot-info-request-1
17:27:06.433 [] [zb-blocking-task-runner-6-0.0.0.0:26802] DEBUG io.zeebe.gateway - Closing gateway broker client ...
17:27:06.436 [service-controller] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/9401e17b-a8e0-4020-be1a-e5d4229d72b6/data/partition-1/state/runtime'.
17:27:06.439 [service-container-main] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.servicecontainer - Service cluster.base.partition.raft-atomix-partition-1.leader interrupted while building
17:27:06.452 [service-container-main] [0.0.0.0:26802-zb-actors-1] DEBUG io.zeebe.servicecontainer - Removed service transport.commandApi.server.server
17:27:06.453 [service-container-main] [0.0.0.0:26802-zb-actors-1] DEBUG io.zeebe.servicecontainer - Removed service broker.httpServer
17:27:06.457 [] [zb-blocking-task-runner-6-0.0.0.0:26802] DEBUG io.zeebe.gateway - topology manager closed
17:27:06.548 [] [zb-blocking-task-runner-6-0.0.0.0:26802] DEBUG io.zeebe.gateway - transport closed
17:27:06.549 [] [zb-blocking-task-runner-6-0.0.0.0:26802] DEBUG io.zeebe.gateway - data frame receive buffer closed
17:27:06.556 [service-container-main] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.servicecontainer - Removed service logstream.raft-atomix-partition-1
17:27:06.554 [] [zb-blocking-task-runner-6-0.0.0.0:26802] DEBUG io.zeebe.gateway - Gateway broker client closed.
17:27:10.153 [service-container-main] [0.0.0.0:26802-zb-actors-0] DEBUG io.zeebe.servicecontainer - Removed service cluster.base.bootstrapped
17:27:10.158 [] [main] INFO  io.zeebe.broker.system - Broker shut down.
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.22.0-SNAPSHOT

### LINKED ISSUE #3315: ServiceContainer Test fail locally
**Description**

```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 17.682 s <<< FAILURE! - in io.zeebe.servicecontainer.impl.ServiceContainerIntegrationTest
[ERROR] testInstallAsync(io.zeebe.servicecontainer.impl.ServiceContainerIntegrationTest)  Time elapsed: 10.547 s  <<< ERROR!
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:979)
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.close(ServiceContainerImpl.java:124)
	at io.zeebe.servicecontainer.testing.ServiceContainerRule.after(ServiceContainerRule.java:57)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

```

### LINKED ISSUE #3339: BrokerReprocessingTest is flaky
**Description**

The BrokerReprocessingTest fails from time to time with:

```
Error
Deployment partition not installed into the container within 15 SECONDS.
Stacktrace
java.lang.RuntimeException: Deployment partition not installed into the container within 15 SECONDS.
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:238)
	at io.zeebe.broker.it.startup.BrokerReprocessingTest.restartBroker(BrokerReprocessingTest.java:705)
	at io.zeebe.broker.it.startup.BrokerReprocessingTest.shouldAssignUniqueWorkflowInstanceKeyAfterRestart(BrokerReprocessingTest.java:487)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException: Timeout after: 15 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131)
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:233)
	... 18 more
```

This is also reproducible locally. The real error lies in the broker stopping, see the following log.

```

13:47:28.930 [partition-1-processor-snapshot-director] [0.0.0.0:28802-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - The position of the last valid snapshot is '-1'. Taking snapshots beyond this position.
13:47:36.006 [] [Time-limited test] INFO  io.zeebe.broker.system - Broker shutting down...
13:47:36.209 [exporter-1] [0.0.0.0:28802-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter-1'.
13:47:36.521 [service-container-main] [0.0.0.0:28802-zb-actors-0] DEBUG io.zeebe.servicecontainer - Removed service broker.httpServer
13:47:36.611 [] [zb-blocking-task-runner-6-0.0.0.0:28802] DEBUG io.zeebe.gateway - Closing gateway broker client ...
13:47:36.620 [] [zb-blocking-task-runner-6-0.0.0.0:28802] DEBUG io.zeebe.gateway - topology manager closed
13:47:36.819 [] [zb-blocking-task-runner-6-0.0.0.0:28802] DEBUG io.zeebe.gateway - transport closed
13:47:36.820 [] [zb-blocking-task-runner-6-0.0.0.0:28802] DEBUG io.zeebe.gateway - data frame receive buffer closed
13:47:36.909 [] [zb-blocking-task-runner-6-0.0.0.0:28802] DEBUG io.zeebe.gateway - Gateway broker client closed.
13:47:56.010 [] [Time-limited test] DEBUG io.zeebe.servicecontainer - Service container closing failed. Print dependencies.
13:47:56.013 [] [Time-limited test] DEBUG io.zeebe.servicecontainer - 
logstream.raft-atomix-partition-1.service in AwaitDependentsStopped
	\
 	-- logstream.raft-atomix-partition-1 in AwaitDependentsStopped
 	-- logstream.raft-atomix-partition-1.storage in AwaitDependentsStopped
transport.commandApi.server.server in AwaitDependentsStopped
	\
cluster.base.bootstrapped in AwaitDependentsStopped
	\
cluster.base.atomix.join in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.topologyManager in AwaitDependentsStopped
cluster.base.partition.raft-atomix-partition-1.leader in AwaitDependentsStopped
	\
 	-- logstream.raft-atomix-partition-1.service in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
 	-- raft.leader.raft-atomix-partition-1.openLogStream in AwaitDependentsStopped
broker.system.management.requestHandler in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
cluster.base.atomix in AwaitDependentsStopped
	\
 	-- cluster.base.bootstrapped in AwaitDependentsStopped
 	-- cluster.base.raft.configurationManager in AwaitDependentsStopped
cluster.base.topologyManager in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.bootstrapped in AwaitDependentsStopped
cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
	\
 	-- cluster.base.partition.install.raft-atomix-partition-1 in AwaitDependentsStopped
cluster.base.partitions.bootstrap in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.raft.configurationManager in AwaitDependentsStopped
 	-- cluster.base.atomix.join in AwaitDependentsStopped
cluster.base.raft.configurationManager in AwaitDependentsStopped
	\
 	-- cluster.base.bootstrapped in AwaitDependentsStopped
logstream.raft-atomix-partition-1 in AwaitDependentsStopped
	\
raft.leader.raft-atomix-partition-1.openLogStream in AwaitDependentsStopped
	\
 	-- logstream.raft-atomix-partition-1.distributed.log in AwaitDependentsStopped
 	-- logstream.raft-atomix-partition-1.service in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
logstream.raft-atomix-partition-1.storage in AwaitDependentsStopped
	\
 	-- logstream.raft-atomix-partition-1 in AwaitDependentsStopped
cluster.base.partition.install.raft-atomix-partition-1 in AwaitDependentsStopped
	\
 	-- cluster.base.partitions.bootstrap in AwaitDependentsStopped
logstream.raft-atomix-partition-1.distributed.log in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
logstream.raft-atomix-partition-1.stream-processor in AwaitDependentsStopped
	\
 	-- cluster.base.atomix in AwaitDependentsStopped
 	-- cluster.base.topologyManager in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
 	-- transport.commandApi.messageHandler in AwaitDependentsStopped
 	-- cluster.base.partition.raft-atomix-partition-1.leader in AwaitDependentsStopped
 	-- broker.system.management.requestHandler in AwaitDependentsStopped
transport.commandApi.messageHandler in AwaitDependentsStopped
	\
 	-- transport.commandApi.server.server in AwaitDependentsStopped
logstream.raft-atomix-partition-1.snapshot-director in AwaitStopState
	\
 	-- logstream.raft-atomix-partition-1.stream-processor in AwaitDependentsStopped
 	-- cluster.base.partition.leader.install.root.raft-atomix-partition-1 in AwaitDependentsStopped
 	-- cluster.base.partition.raft-atomix-partition-1.leader in AwaitDependentsStopped
13:47:56.016 [] [Time-limited test] ERROR io.zeebe.broker.system - Failed to close broker within PT20S seconds.
java.util.concurrent.TimeoutException: Timeout after: 20000 MILLISECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131) ~[zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.servicecontainer.impl.ServiceContainerImpl.close(ServiceContainerImpl.java:117) ~[zeebe-service-container-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.system.SystemContext.close(SystemContext.java:175) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.Broker.lambda$close$1(Broker.java:71) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.Broker.close(Broker.java:67) ~[zeebe-broker-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.test.EmbeddedBrokerRule.stopBroker(EmbeddedBrokerRule.java:196) ~[zeebe-broker-0.22.0-SNAPSHOT-tests.jar:0.22.0-SNAPSHOT]
	at io.zeebe.broker.it.startup.BrokerReprocessingTest.restartBroker(BrokerReprocessingTest.java:701) ~[test-classes/:?]
	at io.zeebe.broker.it.startup.BrokerReprocessingTest.shouldAssignUniqueWorkflowInstanceKeyAfterRestart(BrokerReprocessingTest.java:487) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292) [junit-4.12.jar:4.12]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
13:47:56.204 [] [Time-limited test] INFO  io.zeebe.broker.system - Broker shut down.
13:47:56.615 [] [Time-limited test] DEBUG io.zeebe.broker.system - Initializing configuration with base path /tmp/3d719665-5291-4a0f-8930-f6e004831d36
13:47:56.712 [] [Time-limited test] INFO  io.zeebe.broker.system - Version: 0.22.0-SNAPSHOT
13:47:56.800 [] [Time-limited test] INFO  io.zeebe.broker.system - Starting broker with configuration {
  "network": {
    "host": "0.0.0.0",
    "portOffset": 0,
    "maxMessageSize": "4M",
    "commandApi": {
      "defaultPort": 26501,
      "host": "0.0.0.0",
      "port": 28802,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 28802
    },
    "internalApi": {
      "defaultPort": 26502,
      "host": "0.0.0.0",
      "port": 28803,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 28803
    },
    "monitoringApi": {
      "defaultPort": 9600,
      "host": "0.0.0.0",
      "port": 28804,
      "advertisedHost": "0.0.0.0",
      "advertisedPort": 28804
    }
  },
  "cluster": {
    "initialContactPoints": [],
    "partitionIds": [
      1
    ],
    "nodeId": 0,
    "partitionsCount": 1,
    "replicationFactor": 1,
    "clusterSize": 1,
    "clusterName": "zeebe-cluster",
    "gossipFailureTimeout": 10000,
    "gossipInterval": 250,
    "gossipProbeInterval": 1000
  },
  "threads": {
    "cpuThreadCount": 2,
    "ioThreadCount": 2
  },
  "data": {
    "directories": [
      "/tmp/3d719665-5291-4a0f-8930-f6e004831d36/data"
    ],
    "logSegmentSize": "512M",
    "snapshotPeriod": "15m",
    "raftSegmentSize": "512M",
    "maxSnapshots": 3
  },
  "exporters": [
    {
      "id": "test-recorder",
      "className": "io.zeebe.test.util.record.RecordingExporter"
    }
  ],
  "gateway": {
    "enable": true,
    "network": {
      "host": "0.0.0.0",
      "port": 28800
    },
    "cluster": {
      "contactPoint": "0.0.0.0:28803",
      "maxMessageSize": "4M",
      "requestTimeout": "15s",
      "clusterName": "zeebe-cluster",
      "memberId": "gateway",
      "host": "0.0.0.0",
      "port": 28801
    },
    "threads": {
      "managementThreads": 1
    },
    "monitoring": {
      "enabled": false,
      "host": "0.0.0.0",
      "port": 9600
    },
    "security": {
      "enabled": false
    }
  },
  "backpressure": {
    "enabled": true,
    "useWindowed": true,
    "algorithm": "vegas"
  }
}
13:47:56.817 [service-controller] [0.0.0.0:28802-zb-actors-0] INFO  io.zeebe.transport - Bound commandApi.server to /0.0.0.0:28802
13:47:57.100 [] [zb-blocking-task-runner-1-0.0.0.0:28802] INFO  io.zeebe.gateway - Version: 0.22.0-SNAPSHOT
13:47:57.103 [] [zb-blocking-task-runner-1-0.0.0.0:28802] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "enable": true,
  "network": {
    "host": "0.0.0.0",
    "port": 28800
  },
  "cluster": {
    "contactPoint": "0.0.0.0:28803",
    "maxMessageSize": "4M",
    "requestTimeout": "15s",
    "clusterName": "zeebe-cluster",
    "memberId": "gateway",
    "host": "0.0.0.0",
    "port": 28801
  },
  "threads": {
    "managementThreads": 1
  },
  "monitoring": {
    "enabled": false,
    "host": "0.0.0.0",
    "port": 9600
  },
  "security": {
    "enabled": false
  }
}
13:47:57.103 [service-controller] [0.0.0.0:28802-zb-actors-1] DEBUG io.zeebe.broker.clustering - Adding Node{nodeId=0, commandApi=0.0.0.0:28802} to list of known members
13:47:57.620 [] [netty-messaging-event-epoll-server-0] WARN  io.atomix.cluster.messaging.impl.NettyMessagingService - Failed to bind TCP server to port 0.0.0.0:28803 due to io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
13:47:57.622 [service-controller] [0.0.0.0:28802-zb-actors-0] ERROR io.zeebe.servicecontainer - Service cluster.base.atomix.join failed to start while in AwaitStartState
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:777) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bind$31(NettyMessagingService.java:577) ~[atomix-cluster-3.2.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:991) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:331) ~[netty-transport-native-epoll-4.1.39.Final-linux-x86_64.jar:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
13:47:57.809 [service-container-main] [0.0.0.0:28802-zb-actors-1] ERROR io.zeebe.servicecontainer - Failed to build service
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:777) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bind$31(NettyMessagingService.java:577) ~[atomix-cluster-3.2.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:991) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355) ~[netty-transport-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:331) ~[netty-transport-native-epoll-4.1.39.Final-linux-x86_64.jar:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.39.Final.jar:4.1.39.Final]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
13:48:12.808 [] [Time-limited test] INFO  io.zeebe.broker.system - Broker shutting down...
```

BrokerReprocessingTest

A clear and concise description of what this issue is about.

### LINKED ISSUE #3358: ExporterManagerPartitionTest#shouldRunExporterForEveryPartition flaky
**Description**
shouldRunExporterForEveryPartition – io.zeebe.broker.exporter.ExporterManagerPartitionTest
```
java.lang.RuntimeException: Deployment partition not installed into the container within 15 SECONDS.
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:238)
	at io.zeebe.broker.test.EmbeddedBrokerRule.before(EmbeddedBrokerRule.java:135)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.util.concurrent.TimeoutException: Timeout after: 15 SECONDS
	at io.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131)
	at io.zeebe.broker.test.EmbeddedBrokerRule.startBroker(EmbeddedBrokerRule.java:233)
	... 30 more
```

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

In the following I will list and try to explain the changes I made.

#### Actor model migration
 Migrated the Logstream to the actor model to avoid concurrent access of shared resources and remove the service container dependency.

Refactored/rewrote LogStream API, such that it is completely asynchronous due to the actor model migration. Synchronous access is only possible and necessary in tests. For that I created a new wrapper. 

#### Hide internals
It is no longer possible to access directly the dispatcher nor the logStorage, these are totally implementation details. The access was replaced with method to create new readers and writer, because this was the only use case.

The readers are now closed on closing the log stream, this solved also some memory leaks, since the reader allocating direct buffer memory.

#### Multi-Submit of an actor
Due to some mistakes on refactoring I observed issues when accidentally an actor was submitted multiple times, this is now no longer permitted.

#### CompletableFuture is now BiConsumer
To reduce boilerplate code and make it possible to complete futures by run on completion the future implements now BiConsumer.

#### Actor implements AutoClosable
Such that we can use actors with other AutoClosables, the actor implements now this interface.
It supports an async and a sync implementation. This is heavily used in the Broker closing phase.

### Broker

In order to remove the container all services have to be replaced by the actor counterparts. They are submitted in the Broker start up phase.

I created new helper for starting and stopping the broker. This makes it possible to submit start actions, which are then executed in order and closed in reversed order. Furthermore it makes it possible to print the current installation phase  and the time it took to complete this step.

<details>
<pre>
14:41:31.656 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [1/10]: actor scheduler
14:41:31.660 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [1/10]: actor scheduler started in 3 ms
14:41:31.661 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [2/10]: membership and replication protocol
14:41:33.557 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [2/10]: membership and replication protocol started in 1896 ms
14:41:33.558 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [3/10]: command api
14:41:33.623 [] [main] INFO  io.zeebe.broker.system - Command api bound to /0.0.0.0:25602.
14:41:33.623 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/10]: command api started in 65 ms
14:41:33.624 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/10]: subscription api
14:41:33.657 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/10]: subscription api started in 33 ms
14:41:33.657 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/10]: embedded gateway
14:41:34.127 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/10]: embedded gateway started in 470 ms
14:41:34.127 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/10]: cluster services
14:41:34.720 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/10]: cluster services started in 592 ms
14:41:34.720 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/10]: topology manager
14:41:34.721 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/10]: topology manager started in 0 ms
14:41:34.722 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/10]: metric's server
14:41:34.723 [] [main] INFO  io.zeebe.broker.system - {1=false}
14:41:34.730 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/10]: metric's server started in 8 ms
14:41:34.730 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/10]: leader management request handler
14:41:34.732 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [9/10]: leader management request handler started in 1 ms
14:41:34.732 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/10]: zeebe partitions
14:41:34.735 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
14:41:34.850 [io.zeebe.logstreams.impl.log.LogStreamImpl] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 0 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
14:41:34.855 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.system - Removing follower partition service for partition PartitionId{id=1, group=raft-partition}
14:41:34.856 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER
14:41:34.856 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.system - Installing leader partition service for partition PartitionId{id=1, group=raft-partition}
14:41:34.944 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: []
14:41:34.971 [GatewayTopologyManager] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {} and terms {}.
14:41:34.973 [GatewayTopologyManager] [0.0.0.0:25602-zb-actors-1] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '0' with address '0.0.0.0:25602' on transport 'gateway-broker-client'
14:41:35.168 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/tmp/483f8f45-8752-42b5-ab15-591fff51b8b4/data/raft-partition/partitions/1/runtime'.
14:41:35.193 [partition-1-processor] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
14:41:35.260 [partition-1-processor] [0.0.0.0:25602-zb-actors-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
14:41:35.448 [partition-1-processor-snapshot-director] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - The position of the last valid snapshot is '-1'. Taking snapshots beyond this position.
14:41:35.465 [exporter-1] [0.0.0.0:25602-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
14:41:35.471 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 736 ms
14:41:35.472 [Broker-0-HealthCheckService] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
14:41:35.472 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 737 ms.
14:41:35.472 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/10]: zeebe partitions started in 740 ms
14:41:35.472 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 10 steps in 3816 ms.
14:41:35.484 [exporter-1] [0.0.0.0:25602-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovered exporter 'exporter-1' from snapshot at lastExportedPosition -1
14:41:35.485 [exporter-1] [0.0.0.0:25602-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'test-recorder'
14:41:35.488 [exporter-1] [0.0.0.0:25602-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={SBE_UNKNOWN=true, EVENT=true, COMMAND=true, COMMAND_REJECTION=true, NULL_VAL=true}, acceptValueTypes={WORKFLOW_INSTANCE_RESULT=true, ERROR=true, DEPLOYMENT=true, SBE_UNKNOWN=true, MESSAGE_SUBSCRIPTION=true, JOB_BATCH=true, JOB=true, TIMER=true, MESSAGE=true, WORKFLOW_INSTANCE_CREATION=true, VARIABLE_DOCUMENT=true, NULL_VAL=true, WORKFLOW_INSTANCE=true, INCIDENT=true, WORKFLOW_INSTANCE_SUBSCRIPTION=true, VARIABLE=true, MESSAGE_START_EVENT_SUBSCRIPTION=true}}
14:41:35.490 [exporter-1] [0.0.0.0:25602-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Open exporter with id 'test-recorder'
14:41:35.718 [GatewayTopologyManager] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER} and terms {1=1}.
14:41:35.837 [] [main] INFO  io.zeebe.broker.test - 
====
Broker startup time: 4603
====

14:41:35.839 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [1/10]: zeebe partitions
14:41:35.840 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1
14:41:35.840 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.broker.system - Closing exporter-1
14:41:35.842 [exporter-1] [0.0.0.0:25602-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Closed exporter director 'exporter-1'.
14:41:35.842 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.broker.system - Closed exporter-1 successfully
14:41:35.842 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.broker.system - Closing partition-1-processor-snapshot-director
14:41:35.845 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.broker.system - Closed partition-1-processor-snapshot-director successfully
14:41:35.846 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.broker.system - Closing partition-1-processor
14:41:35.847 [partition-1-processor] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.logstreams - Closed stream processor controller partition-1-processor.
14:41:35.847 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.system - Closed partition-1-processor successfully
14:41:35.847 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.system - Closing io.zeebe.broker.logstreams.LogStreamDeletionService
14:41:35.847 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.broker.system - Closed io.zeebe.broker.logstreams.LogStreamDeletionService successfully
14:41:35.860 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-0] DEBUG io.zeebe.logstreams.snapshot - Closed database from '/tmp/483f8f45-8752-42b5-ab15-591fff51b8b4/data/raft-partition/partitions/1/runtime'.
14:41:35.860 [io.zeebe.logstreams.impl.log.LogStreamImpl] [0.0.0.0:25602-zb-actors-0] INFO  io.zeebe.logstreams - Close appender for log stream raft-partition-partition-1
14:41:35.861 [raft-partition-partition-1-write-buffer] [0.0.0.0:25602-zb-actors-0] INFO  io.zeebe.dispatcher - Dispatcher closed
14:41:35.862 [io.zeebe.logstreams.impl.log.LogStreamImpl] [0.0.0.0:25602-zb-actors-0] INFO  io.zeebe.logstreams - On closing logstream raft-partition-partition-1 close 3 readers
14:41:35.862 [io.zeebe.logstreams.impl.log.LogStreamImpl] [0.0.0.0:25602-zb-actors-0] INFO  io.zeebe.logstreams - Close log storage with name raft-partition-partition-1
14:41:35.863 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 partitions [1/1]: partition 1 closed in 23 ms
14:41:35.863 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 partitions succeeded. Closed 1 steps in 24 ms.
14:41:35.863 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [1/10]: zeebe partitions closed in 24 ms
14:41:35.863 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [2/10]: leader management request handler
14:41:35.864 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [2/10]: leader management request handler closed in 1 ms
14:41:35.864 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [3/10]: metric's server
14:41:35.883 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [3/10]: metric's server closed in 19 ms
14:41:35.883 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [4/10]: topology manager
14:41:35.884 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [4/10]: topology manager closed in 1 ms
14:41:35.884 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [5/10]: cluster services
14:41:35.884 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [5/10]: cluster services closed in 0 ms
14:41:35.884 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [6/10]: embedded gateway
14:41:35.888 [] [main] DEBUG io.zeebe.gateway - Closing gateway broker client ...
14:41:35.889 [] [main] DEBUG io.zeebe.gateway - topology manager closed
14:41:35.893 [] [main] DEBUG io.zeebe.gateway - transport closed
14:41:35.894 [gateway-receive-buffer] [0.0.0.0:25602-zb-actors-0] INFO  io.zeebe.dispatcher - Dispatcher closed
14:41:35.894 [] [main] DEBUG io.zeebe.gateway - data frame receive buffer closed
14:41:35.895 [] [main] DEBUG io.zeebe.gateway - Gateway broker client closed.
14:41:35.895 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [6/10]: embedded gateway closed in 11 ms
14:41:35.895 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [7/10]: subscription api
14:41:35.896 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [7/10]: subscription api closed in 1 ms
14:41:35.896 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [8/10]: command api
14:41:35.897 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [8/10]: command api closed in 1 ms
14:41:35.897 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [9/10]: membership and replication protocol
14:41:38.150 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [9/10]: membership and replication protocol closed in 2253 ms
14:41:38.150 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 [10/10]: actor scheduler
14:41:38.155 [] [main] DEBUG io.zeebe.broker.system - Closing Broker-0 [10/10]: actor scheduler closed in 5 ms
14:41:38.155 [] [main] INFO  io.zeebe.broker.system - Closing Broker-0 succeeded. Closed 10 steps in 2316 ms.
14:41:38.155 [] [main] INFO  io.zeebe.broker.system - Broker shut down.
14:41:38.203 [] [main] INFO  io.zeebe.broker.test - Test execution time: 2364
14:41:38.203 [] [main] INFO  io.zeebe.broker.test - Broker closing time: 0

Process finished with exit code 0

</pre>
</details>

Partitions are installed on bootstrap and react on role changes. On Leader they submit the processor etc and on follower they stop all related actors. There is a follow up issue  #3499 to step down on install failure. 

Most of the actor names now follow the same naming pattern such that the node id is included in the name, this makes it much easier to read the log on cluster environment.

### Clean up

I removed from different modules unused classes, e.g. from util, broker etc.
After all these migration work I also removed the service container completely.

## Related issues

closes https://github.com/zeebe-io/zeebe/issues/3358
closes https://github.com/zeebe-io/zeebe/issues/3339
closes https://github.com/zeebe-io/zeebe/issues/3315
closes https://github.com/zeebe-io/zeebe/issues/3295
closes https://github.com/zeebe-io/zeebe/issues/2400
closes https://github.com/zeebe-io/zeebe/issues/999
closes https://github.com/zeebe-io/zeebe/issues/2749
closes https://github.com/zeebe-io/zeebe/issues/788

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

File: engine/src/test/java/io/zeebe/engine/util/EngineRule.java [hunk 1]
```diff
@@ -315,8 +324,13 @@ private void onNewEventCommitted() {
             final DeploymentRecord deploymentRecord = new DeploymentRecord();
             deploymentRecord.wrap(buffer);
 
-            environmentRule.writeCommandOnPartition(
-                partitionId, key, DeploymentIntent.CREATE, deploymentRecord);
+            // we run in processor actor, we are not allowed to wait on futures
+            // which means we cant get new writer in sync way
+            new Thread(
```
Comment (npepinpe) [inline engine/src/test/java/io/zeebe/engine/util/EngineRule.java]: I also get why we do this, but it feels a little hacky. The only alternative I can think of though is having async write APIs for tests as well, so you could them in cases like this (assuming here we would have access to the actor we're running in):

```java
actor.runOnCompletion(environmentRule.writeCommandOnPartitionAsync(partitionId, key, DeploymentIntent.CREATE, deploymentRecord), (result, error) -> CompletableActorFuture.completed(null));
```

But yeah not sure how much work it would be and how worth it it is :s

File: engine/src/test/java/io/zeebe/engine/util/StreamProcessorRule.java [hunk 2]
```diff
@@ -295,15 +309,18 @@ private static String getLogName(final int partitionId) {
...
 
       int partitionId = startPartitionId;
       for (int i = 0; i < partitionCount; i++) {
         streams.createLogStream(getLogName(partitionId), partitionId++);
       }
     }
+
+    @Override
+    protected void after() {
+      streams = null;
```
Comment (npepinpe) [inline engine/src/test/java/io/zeebe/engine/util/StreamProcessorRule.java]: Should we not close the `TestStreams`? I see it manages a bunch of `closeables`.

File: gateway/src/main/java/io/zeebe/gateway/impl/broker/cluster/BrokerTopologyManagerImpl.java [hunk 3]
```diff
@@ -27,22 +29,45 @@
 
   protected final BiConsumer<Integer, SocketAddress> registerEndpoint;
   protected final AtomicReference<BrokerClusterStateImpl> topology;
+  private final Supplier<Set<Member>> membersSupplier;
 
-  public BrokerTopologyManagerImpl(final BiConsumer<Integer, SocketAddress> registerEndpoint) {
+  public BrokerTopologyManagerImpl(
+      Supplier<Set<Member>> membersSupplier,
+      final BiConsumer<Integer, SocketAddress> registerEndpoint) {
```
Comment (npepinpe) [inline gateway/src/main/java/io/zeebe/gateway/impl/broker/cluster/BrokerTopologyManagerImpl.java]:
```suggestion
      final ObjIntConsumer<SocketAddress> registerEndpoint) {
```

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/BufferedLogStreamReader.java [hunk 4]
```diff
@@ -45,13 +44,15 @@
   private ByteBuffer byteBuffer;
   private int bufferOffset;
 
-  public BufferedLogStreamReader(final LogStorage logStorage) {
-    this();
-    wrap(logStorage);
-  }
-
-  public BufferedLogStreamReader() {
+  BufferedLogStreamReader(final LogStorage logStorage) {
```
Comment (npepinpe) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/log/BufferedLogStreamReader.java]: Could be simplified with getting the reader directly instead of the storage - but I plan on refactoring this so feel free to ignore this suggestion

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java [hunk 5]
```diff
@@ -0,0 +1,293 @@
...
+  public static final long INVALID_ADDRESS = -1L;
+
+  private static final Logger LOG = Loggers.LOGSTREAMS_LOGGER;
+  private static final String APPENDER_SUBSCRIPTION_NAME = "appender";
+
+  private final ActorConditions onCommitPositionUpdatedConditions;
+  private final String logName;
+  private final int partitionId;
+  private final ByteValue maxFrameLength;
+  private final Position commitPosition;
```
Comment (npepinpe) [inline logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: Do we still need a class with volatile semantic? Can't we just use a long now that the `LogStream` is an actor?

File: test/src/main/java/io/zeebe/test/EmbeddedBrokerRule.java [hunk 6]
```diff
@@ -192,32 +185,19 @@ public void stopBroker() {
   }
 
   public void startBroker() {
-    startTime = System.currentTimeMillis();
     broker = new Broker(brokerCfg, newTemporaryFolder.getAbsolutePath(), controlledActorClock);
-
-    final ServiceContainer serviceContainer = broker.getBrokerContext().getServiceContainer();
-
-    try {
```
Comment (npepinpe) [inline test/src/main/java/io/zeebe/test/EmbeddedBrokerRule.java]: :heart_eyes:

File: util/src/main/java/io/zeebe/util/sched/ActorJob.java [hunk 7]
```diff
@@ -44,6 +45,7 @@ void execute(ActorThread runner) {
       }
 
     } catch (Throwable e) {
+      LoggerFactory.getLogger(ActorJob.class).error("FAILED!", e);
```
Comment (npepinpe) [inline util/src/main/java/io/zeebe/util/sched/ActorJob.java]: Can we make this a constant? Also do we need to catch `Throwable` here? I know you didn't add this but maybe you know if it's safe to go to `Exception`?

File: util/src/main/java/io/zeebe/util/sched/future/CompletableActorFuture.java [hunk 8]
```diff
@@ -222,6 +227,15 @@ public Throwable getException() {
     return failureCause;
   }
 
+  @Override
+  public void accept(V value, Throwable throwable) {
```
Comment (npepinpe) [inline util/src/main/java/io/zeebe/util/sched/future/CompletableActorFuture.java]: :heart_eyes: will make my life much easier

**Review by npepinpe — CHANGES_REQUESTED** [review]
:tada: 

First of all, amazing job! And thanks for doing this. I only have a few comments, and I think most of them can be addressed as follow up issues; we can improve later, but just merging this now is a major improvement!

1. I like a lot the startup/shutdown process: list startup steps, which once executed return how they should be reversed (i.e. shutdown) :+1: I think the naming is not very descriptive right now, `*Helper` is always a strange name, though I'm guilty of using it as well :sweat_smile: Maybe we call them `Startup` or `Bootstrap` and `Shutdown` instead of `StartHelper` and `CloseHelper`? `ReversibleExecutionSteps` :joy: ?
1. The `Broker` class now is basically the whole bootstrap process - should we break it up into smaller pieces? I like that we describe the bootstrap process as a series of reversible steps, but most of these are contained in the `Broker`, which is the part I'm less sure of. I know not every body is a fan of many-small-classes :sweat_smile: so I'm open to discussing it, but I feel here the `Broker` is definitely not very "single-responsibility" minded :sweat_smile: (tbh this is more for a follow up issue), and contains many long-ish lambdas
1. I notice you rarely used local var inference, any reason for that? I think we never discussed if we should/shouldn't, and tbh I still haven't completely made up my mind about it - just curious here.
1. I like the logging improvements, and I think we could even go beyond and add a second logging context with the partitions. I'm not sure how easy that would be to do with MDC since MDC is thread specific, but maybe we could pass a `Logger` specially configured per-partition to all partition-scoped services? I think we try to do this but I don't think we do it everywhere. Again probably better as a follow up.
1. When adding interfaces, I think it's important to document them, even if they seem obvious - who knows when someone needs to add a new implementation and has to figure out exactly the expected contract. Things like `PartitionListener`, for example - I know it seems obvious but it's really helpful to implement well documented interfaces :sweat_smile: 
1. I like a lot that we now just get log stream readers/writers instead of the whole partition :+1: 
1. I like the `SynchronousLogStream` for testing - initially the name made me expect it extended the `LogStream`, but I actually like that it doesn't in practice (though if I'm not the only one confused maybe we just rename it to `SynchronousLogStreamWrapper` or something to make it obvious - as it is I'd leave it for now).

**Comment by npepinpe** [comment]
I finished looking into the Sonar report, I think most of the "bugs" are false positives, but some of the code smells might be good to fix (e.g. [these nested if clauses](https://sonarcloud.io/project/issues?id=io.zeebe%3Azeebe-root&issues=AW7rAjwAxTqMet1MK---&open=AW7rAjwAxTqMet1MK---&pullRequest=3513), or [use a specialized interface](https://sonarcloud.io/project/issues?id=io.zeebe%3Azeebe-root&issues=AW7rAjWVxTqMet1MK--F&open=AW7rAjWVxTqMet1MK--F&pullRequest=3513))

**Comment by Zelldon** [comment]
Yes I looked into it as well yesterday. Might be good if these are not marked as bugs then :sweat_smile: I will fix some of these issues. Thanks.

I lately run a benchmark on k8s, looked quite good.

failed-bench

The first failed after a while because the benchmark was not able to export to elastic. I recreate the helm release and it seems to work fine now. The exporting as well.

bench

**Review by saig0 — APPROVED** [review]

**Comment by saig0** [comment]
Great job :tada:

File: broker/src/main/java/io/zeebe/broker/system/monitoring/BrokerHealthCheckService.java [hunk 9]
```diff
@@ -7,103 +7,81 @@
...
-  public void start(ServiceStartContext startContext) {
-    atomix = atomixInjector.getValue();
-    initializePartitionInstallStatus();
-    startContext.getScheduler().submitActor(this);
-  }
-
-  @Override
-  public void stop(ServiceStopContext stopContext) {
-    actor.close();
+    LOG.info("{}", partitionInstallStatus);
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/monitoring/BrokerHealthCheckService.java]: thanks. this is a left over from fixing qa tests :sweat_smile:

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java [hunk 10]
```diff
@@ -0,0 +1,547 @@
...
+                actor.close();
+              }
+            });
+  }
+
+  @Override
+  public void close() {
+    // this is called from outside so it is safe to call join
+    final var closeFuture = new CompletableActorFuture<Void>();
+    actor.call(
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: Ok move this into the Actor Lifecycle

File: dispatcher/src/main/java/io/zeebe/dispatcher/Dispatcher.java [hunk 11]
```diff
@@ -100,6 +100,7 @@ protected void onActorClosing() {
 
     logBuffer.close();
     isClosed = true;
+    LOG.info("Dispatcher closed");
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply dispatcher/src/main/java/io/zeebe/dispatcher/Dispatcher.java]: nope

File: engine/src/main/java/io/zeebe/engine/processor/AsyncSnapshotDirector.java [hunk 12]
```diff
@@ -206,27 +219,38 @@ protected void enforceSnapshotCreation(
                         streamProcessor.getLastProcessedPositionAsync(),
                         (processedPosition, ex2) -> {
                           if (ex2 == null) {
-                            enforceSnapshotCreation(writtenPosition, processedPosition);
-                            close();
-                            future.complete(null);
+
+                            logStream
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply engine/src/main/java/io/zeebe/engine/processor/AsyncSnapshotDirector.java]: Try to call all methods and collect the futures. Call runOnCompletion(varargs) and then get the results from the futures.

File: engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java [hunk 13]
```diff
@@ -715,58 +714,6 @@ public void processRecord(
     inOrder.verify(commandResponseWriter, never()).tryWriteResponse(anyInt(), anyLong());
   }
 
-  @Test
-  public void shouldNotProcessNextEventBeforeErrorEventIsCommitted() throws Exception {
```
[the remark this answers is not in the document]
Comment (Zelldon) [reply engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java]: Try to write a test

File: engine/src/test/java/io/zeebe/engine/util/EngineRule.java (hunk 1 above)
Comment (Zelldon) [reply engine/src/test/java/io/zeebe/engine/util/EngineRule.java]: on the next use case we create a separate api for that :crossed_fingers:

File: engine/src/test/java/io/zeebe/engine/util/StreamProcessorRule.java (hunk 2 above)
Comment (Zelldon) [reply engine/src/test/java/io/zeebe/engine/util/StreamProcessorRule.java]: Closeables are managed outside

File: logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java (hunk 5 above)
Comment (Zelldon) [reply logstreams/src/main/java/io/zeebe/logstreams/impl/log/LogStreamImpl.java]: we will use long now

File: broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java]: Will do in follow up issue https://github.com/zeebe-io/zeebe/issues/3518

File: engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (Zelldon) [reply engine/src/test/java/io/zeebe/engine/processor/StreamProcessorTest.java]: https://github.com/zeebe-io/zeebe/issues/3520

**Comment by Zelldon** [comment]
Hey guys, thank you very much for your quick reviews! I tried to applied most of the hints.

Furthermore I created for the refactoring different issues. For the ZeebePartition https://github.com/zeebe-io/zeebe/issues/3518, for the Broker class https://github.com/zeebe-io/zeebe/issues/3519, for the missing test #3520.

Latest results from the benchmark look good
benchmark
resources

**Comment by npepinpe** [comment]
The Elastic PVC usage scared me for a second :scream:

**Review by npepinpe — APPROVED** [review]
:tada: :100: 10/10 would review again

**Comment by Zelldon** [comment]
Bors r+
