### PR TITLE
fix(exporters/elasticsearch-exporter): report ES errors on flush

### LINKED ISSUE #4667: Elasticsearch exporter ignores errors on flush
**Describe the bug**
If a failure occurs while exporting records to Elasticsearch then the failure is not reported and no retry happens. As a result, records may not be exported.   

**To Reproduce**
Not sure how to trigger a failure expect using mocks.

Found while fixing #4640.

**Expected behavior**
The failure is reported to the log and the exporter try again.

**Log/Stacktrace**
Nope.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.24.0-alpha2
 - Configuration: elasticsearch-exporter

### PR DESCRIPTION
**Pull request by saig0**
## Description

* fix deserialization of bulk response
* log errors from bulk response
* mark flush as not successful to try it again

## Related issues

closes #4667 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by miguelpires — APPROVED** [review]
bors r+

**Comment by saig0** [comment]
bors retry

File: exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java [hunk 1]
```diff
@@ -136,21 +140,36 @@ public boolean flush() {
...
+  private boolean checkBulkResponse(final BulkResponse bulkResponse) {
+    final var hasErrors = bulkResponse.hasErrors();
+    if (hasErrors) {
+      bulkResponse.getItems().stream()
+          .map(BulkItem::getIndex)
+          .map(BulkItemIndex::getError)
+          .forEach(
+              error ->
+                  log.warn(
+                      "Failed to flush item of bulk request [type: {}, reason: {}]",
```
Comment (menski) [inline exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java:155]: @saig0 I don't think it is a good idea to log every failed item, the reason is that we have thousands of records in a bulk request in a high load scenario. As far as I remember initial we had a similar approach in the first implementation which we saw as a potential problem with log pollution, see https://github.com/zeebe-io/zeebe/pull/1344#discussion_r218088251.

/cc @npepinpe wdyt?

Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java:155]: This is again a case where we would benefit from having a burst filter for errors, a way to log an error max X times over Y seconds; we have several other places where we could benefit from this.

As it is I agree, if ES is down this will create tons of logs, and it just creates noise. Suppressing it however hides an issue, so...maybe we can find a middle ground? Log the error every X errors?

Comment (menski) [reply exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java:155]: As a side note we also had the topic yesterday in the cloud product meeting that Operate is logging to much in case elastic is unavailable, this is also which would trigger an immense log burst with this code.

I would highly recommend to not release this as it is right now as this will immediately lead to problems in cloud.

Comment (Zelldon) [reply exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java:155]: Agree here with @menski maybe we can have a metric which count flash fails or something similar. And yes something like a burst filter would be nice.

Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java:155]: Agrona has a counters buffer which keeps track of errors and how often they happen.I guess this works well if each error gets a specific code or something, not sure how they deal with context. That said, I also don't think it plays well with logging systems; my point here is that it's definitely a common problem, so I'm sure there's a solution [out there](https://i.imgur.com/nHghxAr.gif)

Comment (saig0) [reply exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java:155]: If ES is not reachable then the log statement is not printed. Instead, an exception is thrown and the exporter gets back-off.

To avoid too much log messages, I could do the following:
* log message only once per type for one bulk flush operation
* throw an exception if the flush has errors to get back-off

What do you think about these changes?

Comment (npepinpe) [reply exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java:155]: Let's go for that :+1:

Comment (saig0) [reply exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java:155]: Will be fixed by #4732
