### PR TITLE
Prevent NPE when activating element inside flow scope that's being terminated

### LINKED ISSUE #10878: NPE in ProcessInstanceModifiedEventApplier
**Describe the bug**

The Zeebe medic process was stuck. The task `Inform new next medic via Slack DM` inside the non-interrupting event subprocess `Change the current medic` failed and created an incident.

I tried to modify the process instance and "move the token" from the task to the end event in this event subprocess. Since I can't select the instance of the task (for an unknown reason), I canceled the whole event subprocess and added a token to the end event in the subprocess. The modification was not applied. Instead, it produced the following exception: 

```
 java.lang.NullPointerException: null
  at io.camunda.zeebe.engine.state.appliers.ProcessInstanceModifiedEventApplier.applyState(ProcessInstanceModifiedEventApplier.java:32)
```

As a result, the process instance was blacklisted.

**To Reproduce**

I can reproduce the issue with the following process:

image

1. Deploy the process 
2. Create a new instance of the process
3. In Operate, modify the instance by **cancel the event subprocess** and **add a token to the end event of the subprocess**

**Expected behavior**

No NPE. 

I can apply the modification. As a result, the end event should be activated. But the whole event subprocess should be terminated because the activation instruction is applied before the termination instruction. 

**Log/Stacktrace**

The process instance:
image

The error message:
```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=MODIFY, requestStreamId=1, requestId=333448, protocolVersion=3, valueType=PROCESS_INSTANCE_MODIFICATION, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.1.2}, value={"processInstanceKey":2251799814752856,"terminateInstructions":[{"elementInstanceKey":2251799815068211}],"activateInstructions":[{"elementId":"Event_10bmtdo","ancestorScopeKey":-1,"variableInstructions":[]}],"activatedElementInstanceKeys":[2251799814752856,2251799815068211]}}' without errors, but exception occurred with message 'null'.
```

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: null
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceModifiedEventApplier.applyState(ProcessInstanceModifiedEventApplier.java:32) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceModifiedEventApplier.applyState(ProcessInstanceModifiedEventApplier.java:16) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:258) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:41) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.processRecord(ProcessInstanceModificationProcessor.java:218) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:261) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:257) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:206) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:182) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.2.jar:8.1.2] 
```

</p>
</details>

**Environment:**
- OS: Camunda SaaS
- Zeebe Version: `8.1.2`
- Configuration:

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

When a modify command contains an activate instruction for an element inside of a subprocess, and also a terminate instruction for the subprocess itself, Zeebe would run into a NullPointer.

This is caused by the fact that we keep track of the ancestor keys of an element that's getting activated. We need these to make sure we can clear the interrupted state from any of these ancestors. This is to ensure we support activating elements in an interrupted flow scope.

Since we first perform the activate instructions and after this the terminate instructions, we have already terminated the parent of the element that's being activated. We can not get the element instance and potentially remove the interrupted state. A null check needs to be added here.

## Related issues

closes #10878

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTerminationTest.java [hunk 1]
```diff
@@ -1061,6 +1062,77 @@ public void shouldTerminateMultiInstanceBodyAndNestedElements() {
             tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.ELEMENT_TERMINATED));
   }
 
+  @Test
+  public void shouldTerminateFlowScopeWhenElementInsideIsActivateAndFlowScopeIsTerminated() {
+    // given
+    final Consumer<EventSubProcessBuilder> eventSubProcess =
+        esp ->
+            esp.startEvent("startEvent")
+                .message(m -> m.name("message").zeebeCorrelationKeyExpression("\"correlationKey\""))
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTerminationTest.java:1071]: 🔧 The engine is not cleaned up between the tests. To avoid that the message correlates to multiple process instances (from other tests), we can use `CLASS_RULE_HELPER.getCorrelationValue()` to get a unique correlation key per test method. Using different correlation keys between the tests makes sure the tests stay isolated.

Thanks @saig0 for pointing this one out to me today

**Review by korthout — APPROVED** [review]
Thanks @remcowesterhoud LGTM 💯

File: engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTerminationTest.java [hunk 2]
```diff
@@ -1061,6 +1062,77 @@ public void shouldTerminateMultiInstanceBodyAndNestedElements() {
...
+            .withElementId("endEvent")
+            .onlyCommandRejections()
+            .getFirst();
+
+    assertThat(rejectedActivateCommand.getRejectionType()).isEqualTo(RejectionType.INVALID_STATE);
+    assertThat(rejectedActivateCommand.getRejectionReason())
+        .isEqualTo(
+            "Expected flow scope instance with key '%s' to be present in state but not found.",
+            eventSubprocessKey);
+    assertThatElementIsTerminated(processInstanceKey, "eventSubProcess");
```
[the remark this answers is not in the document]
Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTerminationTest.java:1133]: I believe this is poor wording and it should say that the activated command should be written to the log, as it's an asynchronous action.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTerminationTest.java (hunk 1 above)
Comment (remcowesterhoud) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceTerminationTest.java:1071]: Good catch

**Comment by remcowesterhoud** [comment]
bors merge
