### PR TITLE
fix: run scheduled tasks at a given timestamp

### LINKED ISSUE #17648: shouldRetryToCorrelateMessageSubscriptionAfterOpenedSubscription is flaky
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? - Failed once
- Does it block your work? - No
- Do we suspect that it is a real failure? - Don't know

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
org.awaitility.core.ConditionTimeoutException: 
Condition with alias 'retry correlation' didn't complete within 10 seconds because assertion condition defined as a Lambda expression in io.camunda.zeebe.engine.processing.message.MessageStreamProcessorTest 
interPartitionCommandSender.sendCommand(
    0,
    PROCESS_MESSAGE_SUBSCRIPTION,
    CORRELATE,
    <any>
);
Wanted 2 times:
-> at io.camunda.zeebe.engine.processing.message.MessageStreamProcessorTest.lambda$shouldRetryToCorrelateMessageSubscriptionAfterOpenedSubscription$5(MessageStreamProcessorTest.java:170)
But was 35 times:
</pre>
</details>

**Logs**

Link to the build: https://github.com/camunda/zeebe/actions/runs/8786935713/job/24110951937?pr=17646

Logs: 
[1_Unit tests.txt](https://github.com/camunda/zeebe/files/15065571/1_Unit.tests.txt)

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Checkers were scheduled by the `SimpleProcessingScheduleService#runDelayed` method which did not guarantee the exact execution time, but only the delay for which the scheduler will wait before triggering the task. Unfortunately, the delay may be extended. A fix is to replace the above-mentioned `runDelayed` method with the `runAt` method which will schedule a task to run at a given timestamp or exactly after it, which guarantees the same delay every time.

:information_source: Note 1:

The following classes and their related tests also invoke the `SimpleProcessingScheduleService#runDelayed` method. However, I was hesitant to refactor them as they are not "checker" classes, and I am not aware of the impact this refactoring may have on them.

* `ExtendedProcessingScheduleServiceImpl`
* `ProcessingScheduleServiceImpl`
* `CheckpointRecordsProcessor`

:information_source: Note 2:

It would be good to get some feedback on the changes in the `JobTimeoutCheckerTest` as they reduce the exactness of the `runAt` call verification. In my opinion, this doesn't impact the correctness of the test.

## Related issues

closes #17648

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/PendingProcessMessageSubscriptionChecker.java [hunk 1]
```diff
@@ -67,7 +67,12 @@ public void onResumed() {
 
   private void rescheduleTimer() {
     if (schouldRescheduleTimer) {
-      scheduleService.runDelayed(SUBSCRIPTION_CHECK_INTERVAL, this::checkPendingSubscriptions);
+      scheduleService.runAt(
+          ActorClock.currentTimeMillis() + SUBSCRIPTION_CHECK_INTERVAL.toMillis(),
+          taskResultBuilder -> {
+            checkPendingSubscriptions();
+            return taskResultBuilder.build();
```
Comment (mustafadagher) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/PendingProcessMessageSubscriptionChecker.java:74]: I'm curious if adding `taskResultBuilder.build()` here introduces any change to the original functionality? was that intentional?

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageTimeToLiveChecker.java [hunk 2]
```diff
@@ -110,7 +110,7 @@ private void reschedule(final Duration idleInterval) {
     if (enableMessageTtlCheckerAsync) {
       scheduleService.runDelayedAsync(idleInterval, this);
     } else {
-      scheduleService.runDelayed(idleInterval, this);
+      scheduleService.runAt(ActorClock.currentTimeMillis() + idleInterval.toMillis(), this);
```
Comment (korthout) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessageTimeToLiveChecker.java:113]: ❌ Same here

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @koevskinikola ❤️ 

Just a few small comments

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/PendingProcessMessageSubscriptionChecker.java (hunk 1 above)
Comment (korthout) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/PendingProcessMessageSubscriptionChecker.java:74]: That's a good point. The task is transformed into a runnable that something special: attempt to write the result batch to the log stream. What if the task result builder is empty? 

It may be better still to take the other approach of overloading the `runAt` method for a runnable. We avoided this originally, because we thought it wouldn't make a difference. Let's verify that it really doesn't make a difference.

**Comment by korthout** [comment]
@koevskinikola We should backport this, but only after the following is merged:
- #18857 
- https://github.com/camunda/camunda/pull/18895
- https://github.com/camunda/camunda/pull/18894
- https://github.com/camunda/camunda/pull/18893

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobTimeoutCheckerTest.java [hunk 3]
```diff
@@ -123,7 +124,7 @@ public void shouldRescheduleImmediatelyIfYieldedDueToBatchLimit() {
     inOrder.verify(mockTaskResultBuilder).build();
     verifyNoMoreInteractions(mockTaskResultBuilder);
 
-    verify(mockScheduleService, times(1)).runDelayed(eq(Duration.ZERO), any(Task.class));
+    verify(mockScheduleService, times(1)).runAt(anyLong(), any(Task.class));
```
[the remark this answers is not in the document]
Comment (koevskinikola) [reply zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobTimeoutCheckerTest.java:127]: That's a nice idea, I'll try it.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/PendingProcessMessageSubscriptionChecker.java (hunk 1 above)
Comment (koevskinikola) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/message/PendingProcessMessageSubscriptionChecker.java:74]: :+1: Will look into this tomorrow

**Review by korthout — APPROVED** [review]
Seems I forgot to approve this 🙇 Sorry @koevskinikola 

LGTM 👍

**Comment by koevskinikola** [comment]
@korthout I need to check some code before merging it, but didn't have the time at all in the last month 😦 (see [this](https://github.com/camunda/camunda/pull/18986#discussion_r1624108387) comment)

**Comment by koevskinikola** [comment]
@korthout here are the final changes. Have a look when you have the time. @lenaschoenburg it might be useful to have a look at this code as well, as I'm touching `stream-platform` code that you worked on before.

File: zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/api/scheduling/SimpleProcessingScheduleService.java [hunk 4]
```diff
@@ -35,6 +35,14 @@ public interface SimpleProcessingScheduleService {
    */
   ScheduledTask runAt(long timestamp, Task task);
 
+  /**
+   * Schedules the task to run at or after the given timestamp.
+   *
+   * @implNote Can be silently ignored if the scheduling service is not ready.
+   * @return A representation of the scheduled task.
+   */
+  ScheduledTask runAt(long timestamp, Runnable task);
```
Comment (mustafadagher) [inline zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/api/scheduling/SimpleProcessingScheduleService.java:44]: I think you need to implement this method in `TestScheduleServiceActorDecorator` to overcome the compilation error.

Comment (koevskinikola) [reply zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/api/scheduling/SimpleProcessingScheduleService.java:44]: Ah, I missed that, thanks @mustafadagher!

**Review by korthout — APPROVED** [review]
LGTM 💯 

💭 Apart from the already mentioned compile error

**Comment by koevskinikola** [comment]
The compilation error is fixed @korthout and @mustafadagher. I'll give it another day before merging in case @lenaschoenburg has some time to check out the changes.

**Comment by lenaschoenburg** [comment]
I only checked briefly and don't have much feedback. If it helps stabilize flaky tests then great :)

**Review by korthout — APPROVED** [review]
LGTM 👍 

Feel free to merge :shipit:
