### PR TITLE
fix: protect api resource only and not all

### LINKED ISSUE #37041: API without /v2 prefix returns 403 instead of 404
### 

### 

### 

### 

### Description

When making requests to the REST API without the `/v2` prefix, the server responds with `403 Forbidden`.
This could be misleading — the correct response should be 404 Not Found, since no endpoint exists at that path.

### Steps to reproduce

1. Run Camunda Standalone using 8.8 
2. Call an endpoint without the /v2 prefix (e.g. GET `http://localhost:8080/process-definitions/search`).
3. Response = 403 Forbidden.

### Current behavior

The server returns 403 Forbidden.

### Expected behavior

The server should return 404 Not Found.

### Environment

SM

### Version

- Component Version: 8.8 

### Rootcause

_No response_

### Solution ideas

@jwulf found the root cause and suggested the following:
```
    // Limit this security chain to REST API endpoints only. This ensures that
    // requests not starting with /v2 (e.g., missing the prefix) are not handled
    // by this chain and will fall through to the MVC dispatcher, resulting in a
    // 404 Not Found instead of a 403 from Spring Security.
    http.securityMatchers(matchers -> matchers.requestMatchers("/v2/**"));
```
on line 77 of dist/src/main/java/io/camunda/zeebe/shared/security/SecurityConfiguration.java then it will return a 404 instead of a 403.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by konstantinos-mylosis**
### Issue
Call an endpoint without the /v2 prefix (e.g. GET http://localhost:8080/process-definitions/search) used to return 403 Forbidden, while it should return 404 Not Found.

### Reason
"catch-all-unhandled"-chain at `WebSecurityConfig` used to protect ALL (not already handled) resources by default, that is why the 403 status.

### Proposed Fix
1. completely remove ORDER_UNHANDLED(2) bean SecurityFilterChain
2. add ArchUnit test verifying that every endpoint has a 'SecurityFilterChain' matching pattern, so it is either PROTECTED or UNPROTECTED

### TODO
add ArchUnit test

## Outcome
Run Camunda Standalone using 8.8
Call an endpoint without the /v2 prefix (e.g. GET http://localhost:8080/process-definitions/search).
~Response = 403 Forbidden.~
Response = 404 Not Found.

closes #37041

### CODE REVIEW

File: authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java [hunk 1]
```diff
@@ -241,10 +241,10 @@ public SecurityFilterChain unprotectedApiAuthSecurityFilterChain(
   @Order(ORDER_UNHANDLED)
   public SecurityFilterChain protectedUnhandledPathsSecurityFilterChain(
       final HttpSecurity httpSecurity) throws Exception {
-    // all resources not yet explicitly handled by any previous chain require an authenticated user
-    // thus by default unhandled paths are always protected
+    // all api resources not yet explicitly handled by any previous chain require an
+    // authenticated user thus by default unhandled paths are always protected
     return httpSecurity
-        .securityMatcher("/**")
+        .securityMatcher(API_PATHS.toArray(String[]::new))
```
Comment (eppdot) [inline authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java]: ❓ we have also lots of other "paths" like `UNPROTECTED_API_PATHS` or `UNPROTECTED_PATHS`. What is the expected and actual behavior for these right now? 🤔 maybe @tmetzke can quickly assess the impact of this change, I am not 100 sure though.

**Review by eppdot — COMMENTED** [review]
Looks good to me. But I would like to pull in @tmetzke for a quick look.

File: authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java (hunk 1 above)
Comment (tmetzke) [reply authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java]: I guess someone from the Identity re-arch team is better-suited here, haven't worked with this much to be honest.

Comment (konstantinos-mylosis) [reply authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java]: As far as I understood we have declared at `WebSecurityConfig` some `SecurityFilterChain` for:
1. `ORDER_UNPROTECTED(0)`
   1. Default unprotected paths -- `UNPROTECTED_PATHS`
   2. ConditionalOn**Un**protectedApi -- `API_PATHS`
2. `ORDER_WEBAPP_API(1)` (either AuthenticationMethod.BASIC or AuthenticationMethod.OIDC)
   1. Protect -- `WEBAPP_PATHS`
   2. ConditionalOnProtectedApi -- `API_PATHS`

I would suggest:
1. completely removing `ORDER_UNHANDLED(2)` bean `SecurityFilterChain`
2. add ArchUnit test verifying that every endpoint has a 'SecurityFilterChain' matching pattern, so it is either PROTECTED or UNPROTECTED

What do you think @eppdot?

Comment (eppdot) [reply authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java]: I am not an expert here, thus would rely on others 🤔 but overall I think of
1. we have unprotected endpoints -> should work
2. we have protected endpoints -> should throw forbidden when not authorized/authenticated
3. we have non-existing endpoints -> show throw not found

We should make sure we don't expose 2. by accident

File: authentication/src/test/java/io/camunda/authentication/config/ProtectedApiSecurityFilterChainTest.java [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+import java.util.Base64;
+import org.junit.jupiter.api.Test;
+import org.springframework.boot.test.context.SpringBootTest;
+import org.springframework.http.HttpHeaders;
+import org.springframework.http.HttpStatus;
+import org.springframework.test.web.servlet.assertj.MvcTestResult;
+
+/**
+ * Tests for the security filter chain behavior, specifically testing: - Valid /v2 endpoints with
+ * authorized/unauthorized users - Invalid endpoints returning 404 (security by obscurity) -
```
Comment (megglos) [inline authentication/src/test/java/io/camunda/authentication/config/ProtectedApiSecurityFilterChainTest.java:24]: ❓ `Invalid endpoints returning 404 (security by obscurity)` how does that qualify as "security by obscurity"?

File: authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java [hunk 3]
```diff
@@ -242,11 +242,20 @@ public SecurityFilterChain unprotectedApiAuthSecurityFilterChain(
   public SecurityFilterChain protectedUnhandledPathsSecurityFilterChain(
       final HttpSecurity httpSecurity) throws Exception {
     // all resources not yet explicitly handled by any previous chain require an authenticated user
-    // thus by default unhandled paths are always protected
+    // thus by default unhandled paths will always return 404 not found
```
Comment (megglos) [inline authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java]: 💭   I would split the fact that we deny access to all unhandles paths + the conversion to 404, see next comment
```suggestion
    // thus by default access to unhandled paths will always be denied
```

File: authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java [hunk 4]
```diff
@@ -242,11 +242,20 @@ public SecurityFilterChain unprotectedApiAuthSecurityFilterChain(
...
     return httpSecurity
         .securityMatcher("/**")
         .authorizeHttpRequests(
-            (authorizeHttpRequests) -> authorizeHttpRequests.anyRequest().denyAll())
+            authorizeHttpRequests -> authorizeHttpRequests.anyRequest().denyAll())
+        .exceptionHandling(
+            ex ->
+                ex.accessDeniedHandler(
+                    (request, response, accessDeniedException) ->
+                        response.sendError(HttpServletResponse.SC_NOT_FOUND)))
```
Comment (megglos) [inline authentication/src/main/java/io/camunda/authentication/config/WebSecurityConfig.java:256]: 💭  part 2
```suggestion
            // for unhandled paths return a 404 instead of a 403 - improves UX to detect misconfiguration of paths
            ex ->
                ex.accessDeniedHandler(
                    (request, response, accessDeniedException) ->
                        response.sendError(HttpServletResponse.SC_NOT_FOUND)))
```

**Review by megglos — APPROVED** [review]
LGTM! Just minor suggestions/thoughts you may consider.

File: authentication/src/test/java/io/camunda/authentication/config/ProtectedApiSecurityFilterChainTest.java (hunk 2 above)
Comment (konstantinos-mylosis) [reply authentication/src/test/java/io/camunda/authentication/config/ProtectedApiSecurityFilterChainTest.java:24]: Unhandled endpoint: /non-existent-endpoint, not unprotected nor protected
Consistent 404 response: All three auth scenarios (none, valid, invalid) should return 404
No information leakage

That's my thought behind security by obscurity, but I can remove it
