### PR TITLE
Ensure leader always commits when replicated to quorum

### LINKED ISSUE #8324: Raft leader sometimes does not update commitIndex even if the records are replicated to a quorum
**Describe the bug**

Found this strange behavior when investigating a support ticket. https://jira.camunda.com/browse/SUPPORT-12321
The main issue is that that after a failover, there is no leader for a partition when queried via `zbctl status`

From the logs:
After a failover, new leader is elected - broker 1. Hence the transition to leader is not completed and no Zeebe services are installed.

Analyzed heap dump I observed the following state in the leader:
```
commitIndex=37
term=39
```
`lastAppendedEntry` is the InitialEntry at term 39 and index 38. Indicating that it is not marked as committed.
image

Looking at the followers state, all of them have received the InitialEntry record at index 38.

Leader keeps a map of follower -> RaftMemberContext to keep track of follower's state. 
image

RaftMemberContext for the followers shows there are no pending inflight requests (ruling out previous issues we have seen where we observed there were inflight requests that never gets completed or time out).

`RaftMemberContext.matchIndex = 38` for all followers. 
This means that the leader can commit the record at index 38. But we see that the commitIndex is 37.

In the logs we see following error:
```
2021-12-07 08:50:54.392 [] [raft-server-1-raft-partition-partition-4] WARN 
      io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-4} - AppendRequest{term=39, leader=1, prevLogIndex=33, prevLogTerm=34, entries=5, commitIndex=37} to 0 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request ProtocolRequest{id=695, subject=raft-partition-partition-4-append, sender=10.184.0.147:26602, payload=byte[]{length=326, hash=-846329344}} to 10.184.0.147:26605 timed out in PT5S
2021-12-07 08:50:54.392 [] [raft-server-1-raft-partition-partition-4] WARN 
      io.atomix.raft.roles.LeaderAppender - RaftServer{raft-partition-partition-4} - AppendRequest{term=39, leader=1, prevLogIndex=33, prevLogTerm=34, entries=5, commitIndex=37} to 2 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request ProtocolRequest{id=696, subject=raft-partition-partition-4-append, sender=10.184.0.147:26602, payload=byte[]{length=326, hash=-846329344}} to 10.184.0.147:26604 timed out in PT5S
```

After that there are no errors, and there are no new leader elections happening. This means that both leaders and followers are able to communicate with each other.

After investigating further, I believe the problem is here:
https://github.com/camunda-cloud/zeebe/blob/6ffc0cb40ad355daf2b97882aa4db35765f41382/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java#L208-L210

Consider the following scenario:

1. Leader sends AppendRequest{index = 38} to follower1 and follower2
2. follower 1 and follower 2 receives request and writed record at index 38 to its log
3. follower 1 and follower 2 send ack back to leader
4. But leader does not receives ack => network problems. (Indicating the above two error logs)
5. Leader sends heartbeat in the next heartbeat interval (`AppendRequest {lastLogIndex = 38, commitIndex = 37}`)
6. Followers ack success `AppendResponse{success=true, lastLogIndex=38}` because they have already received record at index 38
7. Leader on receiving ack, update match index to 38. But it does not commit because `request.entries()` is empty.
8. There are no new records to replicate. So leader keeps sending heartbeats. But commitIndex does not get updated.

**To Reproduce**

I did not reproduce it yet. We have to find a way to simulate the scenario described above.

**Expected behavior**
Leader should commit as long as there is a  quorum.

**Environment:**
 - Zeebe Version: 1.2.4

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

* Added a randomized liveness test similar to consistency test that already exists. This test was able to reproduce the bug in #8324 The new test verifies that in the presence of no message lost or delay raft can make progress - that means a leader will be elected, all entries are replicated to all followers, and all entries are committed.
* Leader will now commit entries when receiving response for a heartbeat, thus ensuring that it can make progress.

## Related issues

closes #8324

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Code freeze is next Monday - @oleschoenburg or @Zelldon can one of you review and take this over so it can make it into 1.3.0? Thanks! Let me know if you don't have time, Roman or me could also look into it.

File: atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java [hunk 1]
```diff
@@ -359,4 +360,66 @@ private void updateAndVerifyLeaderTerm(final RaftContext s) {
...
+
+              return lastUncommittedEntry != null
+                  && !lastUncommittedEntry.equals(lastCommittedEntry);
+            });
+  }
+
+  boolean hasReplicatedAllEntries() {
+    return raftServers.values().stream().map(this::getLastUncommittedEntry).distinct().count() == 1;
+  }
+
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java:387]: :question: Not sure why we check here whether the count is equal to one.

File: atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java [hunk 2]
```diff
@@ -61,14 +66,18 @@ public ControllableRaftServerProtocol(
...
+      msg.getLeft().run();
+      timeoutQueue.remove(msg.getRight());
     }
   }
 
   public void receiveAll() {
     final var rcvQueue = messageQueue.get(localMemberId);
     while (!rcvQueue.isEmpty()) {
-      rcvQueue.poll().getLeft().run();
+      final var msg = rcvQueue.poll();
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java:78]: :wrench: this var name is confusing. It is a tuple which contains a runnable and future. This future we use to remove the timeout. I think we can improve here. Either by defining explicity mentioning the type or refine the name, at least indicating that it is a tuple and not a msg.

File: atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java [hunk 3]
```diff
@@ -99,6 +108,25 @@ private void send(
...
+  }
+
+  public void tick(final long timeoutMillis) {
+    currentTime += timeoutMillis;
+    timeoutQueue.forEach(
+        (future, deadline) -> {
+          if (currentTime >= deadline) {
+            if (!future.isDone()) {
+              future.completeExceptionally(new TimeoutException());
+            }
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java:127]: :wrench: I assume we also want to remove here the future from the timeout map?

File: atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java (hunk 1 above)
Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java:387]: So my current assumption is because:

it could return either null and than it is equal for all OR could also be that all have one uncommitted :thinking: 

If one has null and one uncommitted it is 2 and not replicated to everyone.

File: atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java [hunk 4]
```diff
@@ -359,4 +360,66 @@ private void updateAndVerifyLeaderTerm(final RaftContext s) {
...
+              final var lastUncommittedEntry = getLastUncommittedEntry(s);
+
+              assertThat(lastCommittedEntry)
+                  .describedAs("All entries should be committed")
+                  .isEqualTo(lastUncommittedEntry);
+            });
+
+    assertThat(raftServers.values().stream().map(this::getLastUncommittedEntry).distinct().count())
+        .describedAs("All entries are replicated to all followers")
+        .isEqualTo(1);
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java:403]: :wrench: he we could reuse the method from above.

File: atomix/cluster/src/test/java/io/atomix/raft/RandomizedRaftTest.java [hunk 5]
```diff
@@ -92,6 +94,62 @@ void raftProperty(
...
+    }
+
+    raftContexts.assertOnlyOneLeader();
+    raftContexts.assertAllLogsEqual();
+
+    // when - no more message loss
+
+    int maxStepsUntilLeader =
+        100; // hoping that 100 iterations are enough to elect a new leader, since there are no more
+    // failures
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RandomizedRaftTest.java:121]: :wrench: might make sense to move this comment in a separate lines above

File: atomix/cluster/src/test/java/io/atomix/raft/RandomizedRaftTest.java [hunk 6]
```diff
@@ -92,6 +94,62 @@ void raftProperty(
...
+
+    // given - when there are failures such as message loss
+    final var memberIter = raftMembers.iterator();
+    for (final RaftOperation operation : raftOperations) {
+      final MemberId member = memberIter.next();
+      LOG.info("{} on {}", operation, member);
+      operation.run(raftContexts, member);
+    }
+
+    raftContexts.assertOnlyOneLeader();
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RandomizedRaftTest.java:114]: :question: I'm wondering about this assert and the assert below plus the comments. 

`// then - eventually a leader should be elected` this was the case before with this assert or not?

File: atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java [hunk 7]
```diff
@@ -204,10 +204,7 @@ protected void handleAppendResponseOk(
       member.appendSucceeded();
       updateMatchIndex(member, response);
 
-      // If entries were committed to the replica then check commit indexes.
-      if (!request.entries().isEmpty()) {
-        commitEntries();
-      }
+      commitEntries();
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java:207]: :+1: nice catch. always nice how such small changes / single lines can affect a big system :)

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @deepthidevaki for your fix and work :medal_military: 

I have some comments and questions, @oleschoenburg could you also please review this PR and than we can discuss them maybe you have an answer or different opinion. Afterwards we could  adjust the PR and merge it :) What do you think ?

File: atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java (hunk 3 above)
Comment (oleschoenburg) [reply atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java:127]: It's not strictly necessary because they are removed on receive but as there is no way to directly use/inspect the timeout map I agree that we can safely remove them here.

File: atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java [hunk 8]
```diff
@@ -344,4 +360,66 @@ private void updateAndVerifyLeaderTerm(final RaftContext s) {
...
+    return raftServers.values().stream()
+        .noneMatch(
+            s -> {
+              final var lastCommittedEntry = getLastCommittedEntry(s);
+              final var lastUncommittedEntry = getLastUncommittedEntry(s);
+
+              return lastUncommittedEntry != null
+                  && !lastUncommittedEntry.equals(lastCommittedEntry);
+            });
+  }
```
Comment (oleschoenburg) [inline atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java:382]: :wrench: I found this method to be a bit difficult to understand, maybe we could simplify?

```java
boolean hasCommittedAllEntries() {
  return raftServers.values().stream().allMatch(s -> getLastUncommittedEntry(s) == getLastCommittedEntry(s));
}
```

**Review by lenaschoenburg — APPROVED** [review]
The fix itself looks great but I think some of the test code could be improved. Nothing blocking from my side though, so I'm approving.

File: atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java (hunk 3 above)
Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java:127]: But what if no receive is called due to timeout?

File: atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java (hunk 1 above)
Comment (deepthidevaki) [reply atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java:387]: Yes. That is correct.

File: atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java (hunk 3 above)
Comment (deepthidevaki) [reply atomix/cluster/src/test/java/io/atomix/raft/protocol/ControllableRaftServerProtocol.java:127]: :+1:

File: atomix/cluster/src/test/java/io/atomix/raft/RandomizedRaftTest.java (hunk 6 above)
Comment (deepthidevaki) [reply atomix/cluster/src/test/java/io/atomix/raft/RandomizedRaftTest.java:114]: This assert verifies there are no multiple leaders at the same time. It can be renamed to `assertAtMostOneLeader`.

**Comment by deepthidevaki** [comment]
Thanks @oleschoenburg @Zelldon for your review. I will apply your comments and try to get it merge this before code-freeze.

File: atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java (hunk 8 above)
Comment (deepthidevaki) [reply atomix/cluster/src/test/java/io/atomix/raft/ControllableRaftContexts.java:382]: I think `==` doesn't work here because each reader creates a different object for the same entry. But I will use `allMatch` instead of `noneMatch`.

**Comment by deepthidevaki** [comment]
@Zelldon @oleschoenburg I have updated the PR. Please take a look again.

**Review by ChrisKujawa — APPROVED** [review]
Thanks @deepthidevaki  :medal_military:

**Review by lenaschoenburg — APPROVED** [review]

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors merge
