### PR TITLE
fix: getActiveBucket npe

### LINKED ISSUE #35642: Usage Metrics getActiveBucket NPE
### 

### 

### 

### 

### Description

https://github.com/camunda/camunda/actions/runs/16345815139#summary-46179117871
It looks like a fairly basic NPE during regular processing (`CREATE_WITH_AWAITING_RESULT` in this case) that I could imagine contributes greatly to the [large number of flaky tests](https://camunda.slack.com/archives/C071KP5BTHB/p1752732683448679) at the moment.

### Steps to reproduce

1. Run StandaloneBrokerIT

### Current behavior

NPE
'Cannot invoke "io.camunda.zeebe.engine.state.metrics.PersistedUsageMetrics.recordRPI(String)" because the return value of "io.camunda.zeebe.engine.state.metrics.DbUsageMetricState.getActiveBucket()" is null'.

### Expected behavior

No Exception thrown

### Environment

SM

### Version

- Component Version: 8.8.0

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

- Discussion: https://camunda.slack.com/archives/C08F5RD5X8B/p1752758892901969

### PR DESCRIPTION
**Pull request by konstantinos-mylosis**
## Description

- Create usage metrics bucket on-demand
- Update usage metric bucket time in applier when null
- Remove usage metric export from tests

## Related issues

closes #35642

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/metrics/DbUsageMetricState.java [hunk 1]
```diff
@@ -41,9 +42,15 @@ public DbUsageMetricState(
...
+  public PersistedUsageMetrics getOrCreateActiveBucket() {
     setActiveBucketKeys();
-    return metricsBucketColumnFamily.get(metricsBucketKey);
+
+    var existingBucket = metricsBucketColumnFamily.get(metricsBucketKey);
+    if (existingBucket != null) {
+      return existingBucket;
+    }
+
+    return createAndInsertBucket(OffsetDateTime.now().toInstant().toEpochMilli());
```
Comment (danielkelemen) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/metrics/DbUsageMetricState.java]: ❌ We can't do this.

The state needs to be created deterministically, so it has to be initiated via events not just on demand. We use the first EXPORTED event to do this.

There is also a lot of CI issue here. Probably due to state difference after replay.

💭 I think there are two solutions to fix this permanently:
- 👎 Feature flag: Not preferred as this would allow customers to disable the feature.
   - https://github.com/camunda/camunda/pull/35013
- 👍 Wait in the tests for the first `EXPORTED` event.

Comment (danielkelemen) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/metrics/DbUsageMetricState.java]: Idea: initialize on-demand and let the first EXPORTED event to initialize the from & to times for the state.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java [hunk 2]
```diff
@@ -28,8 +28,15 @@ public UsageMetricsExportedApplier(final MutableProcessingState processingState)
 
   @Override
   public void applyState(final long key, final UsageMetricRecord record) {
-    final var activeBucket = usageMetricState.getActiveBucket();
-    if (activeBucket == null || activeBucket.getFromTime() != record.getResetTime()) {
+    final var activeBucket = usageMetricState.getOrCreateActiveBucket();
+
+    // uninitialized bucket created on-demand
+    if (activeBucket != null && activeBucket.getFromTime() == -1) {
```
Comment (konstantinos-mylosis) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java:34]: I think activeBucket here will always be nonNull after using getOrCreateActiveBucket()
also in the next condition line 39?!

Comment (danielkelemen) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java:34]: It can still be null if there was no event prior to this.

Line 39 has different checks.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java [hunk 3]
```diff
@@ -28,8 +28,15 @@ public UsageMetricsExportedApplier(final MutableProcessingState processingState)
...
+      LOG.debug("Update active bucket time {}", record.getResetTime());
+      usageMetricState.updateActiveBucketTime(record.getResetTime());
```
Comment (konstantinos-mylosis) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java:36]: I know resetTime will probably always have value, but would it make sense to add an assertion?

Comment (danielkelemen) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java:36]: It is set by the [ExportProcessor](https://github.com/camunda/camunda/blob/main/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/metrics/UsageMetricsExportProcessor.java#L57) from the record's timestamp.
It should be always set, if not that would mean an issue. I'd rather let the exception happen in that case, so we discover it.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java (hunk 2 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java:34]: I do not see any ways that this can be null
Maybe I am missing something

with these changes, getOrCreateActiveBucket() 
if no existingBucket it will always create new PersistedUsageMetrics(); 
https://github.com/camunda/camunda/pull/35644/files#diff-35e62263bcb3b3efdf345cb0c8958daa9ca43ee95169238fbd8db7dd611753c3R54

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java (hunk 3 above)
Comment (konstantinos-mylosis) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java:36]: Should we throw an exception if null?
Is there a case we'll have corrupted data persisted?
I am more like thinking out loud

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java (hunk 2 above)
Comment (danielkelemen) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java:34]: Ah, I thought the Applier still used the `getActiveBucket` method. Now I get it!
Yeah we should just get the bucket here, I'll change that.

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java (hunk 3 above)
Comment (danielkelemen) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java:36]: I mean we could add, why not. I don't think it can ever happen though.

Comment (danielkelemen) [reply zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/UsageMetricsExportedApplier.java:36]: Plus it raises some other questions: What do we do if not set?
We can't just throw exception, because we have to do something with the metrics and state. We won't export anything and state will just grow..

My suggestion would be to have a follow-up for that and a bit brainstorming as well.

**Review by danielkelemen — APPROVED** [review]
