### PR TITLE
Forms Linked to User Tasks Are Sometimes Wrong

### LINKED ISSUE #16311: Forms Linked to User Tasks Are Sometimes Wrong
**Describe the bug**

There is a [support case](https://jira.camunda.com/browse/SUPPORT-20526) where a customer observed wrong form linked to a user task. After checking exported Zeebe records, we find the aforementioned job created records in exporter logs:

**Correct form linked:**
```json
{
  "partitionId": 1,
  "value": {
    "processDefinitionVersion": 51,
    "retries": 1,
    "retryBackoff": 0,
    "recurringTime": -1,
    "processDefinitionKey": 2251799844220272,
    "processInstanceKey": 2251799844514613,
    "elementInstanceKey": 2251799844514692,
    "tenantId": "<default>",
    "elementId": <elementId>,
    "customHeaders": {
      "io.camunda.zeebe:assignee": <assignee>,
      "io.camunda.zeebe:formKey": "2251799844220271"
    },
    "bpmnProcessId": <bpmnProcessId>,
    "deadline": -1,
    "variables": {},
    "type": "io.camunda.zeebe:userTask",
    "errorMessage": "",
    "errorCode": "",
    "timeout": -1,
    "worker": ""
  },
  "key": 2251799844514693,
  "timestamp": 1707465839007,
  "valueType": "JOB",
  "recordType": "EVENT",
  "intent": "CREATED",
  "brokerVersion": "8.4.1",
  "rejectionType": "NULL_VAL",
  "rejectionReason": "",
  "authorizations": {
    "authorized_tenants": [
      "<default>"
    ]
  },
  "recordVersion": 1,
  "sourceRecordPosition": 61707690,
  "position": 61707706,
  "sequence": 2251799813698708
}
```

**Wrong form linked:**
```json
{
  "partitionId": 1,
  "value": {
    "processDefinitionVersion": 51,
    "retries": 1,
    "retryBackoff": 0,
    "recurringTime": -1,
    "processDefinitionKey": 2251799844220272,
    "processInstanceKey": 2251799844540359,
    "elementInstanceKey": 2251799844540457,
    "tenantId": "<default>",
    "elementId": <elementId>,
    "customHeaders": {
      "io.camunda.zeebe:assignee": <assignee>,
      "io.camunda.zeebe:formKey": "2251799844516282"
    },
    "bpmnProcessId": <bpmnProcessId>,
    "deadline": -1,
    "variables": {},
    "type": "io.camunda.zeebe:userTask",
    "errorMessage": "",
    "errorCode": "",
    "timeout": -1,
    "worker": ""
  },
  "key": 2251799844540458,
  "timestamp": 1707478874680,
  "valueType": "JOB",
  "recordType": "EVENT",
  "intent": "CREATED",
  "brokerVersion": "8.4.1",
  "rejectionType": "NULL_VAL",
  "rejectionReason": "",
  "authorizations": {
    "authorized_tenants": [
      "<default>"
    ]
  },
  "recordVersion": 1,
  "sourceRecordPosition": 61759305,
  "position": 61759321,
  "sequence": 2251799813698712
}
```

**Initial Observations**
- The wrong form key belongs to a completely different form (not an another version of the correct form).
- Issue happened in the same partition
- Issue happened with same tenant id, so multi tenancy shouldn't be a problem

**To Reproduce**

Couldn't reproduce locally yet. I will start with reproducing the issue locally.

**Expected behavior**

The linked form key should be the expected form's key.

**More Context**
Related to: https://github.com/camunda/zeebe/issues/15960

**Environment:**
- OS: 
- Zeebe Version:  8.4.1
- Configuration: 

**Support Cases:**
- https://jira.camunda.com/browse/SUPPORT-20526
- https://jira.camunda.com/browse/SUPPORT-20594

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

While putting the form to the cache during the retrieval for linking, we skip copying a re-used form record object. Then, when we insert another form, we modify that object. That means, we modify the object that we put to the cache. Afterwards, when we query formId1 from the cache, it returns the wrong form object (formId2's object in our case).
It happens only after broker restart because the cache is cleaned up during restart. Therefore, the correct form we put to the cache during the creation of form is gone.

The PR now copies the form before putting it to the cache on retrieval. Also, a test case is added to verify the behaviour. 

**Note:** We chose to add a test case to integration tests because it is easier to manipulate snapshot behaviour with the integration test setup

**Steps to Reproduce**

- Deploy a form with id formId1
- Deploy a process (id=process1) that contains a user task which has a link to form formId1
- Restart the broker
    - Take a snapshot
    - Stop the broker
    - Start broker from the last snapshot
- Create a process instance of process1 (the form linking is correct)
- Deploy another form with id formId2
- Create a process instance of process1 (the form linking is wrong) => it will retrieve the key for formId2

## Related issues

closes #16311 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/FormLinkingIT.java [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+                    .userTask()
+                    .zeebeFormId("formId1")
+                    .endEvent()
+                    .done(),
+                "form_linking_test.bpmn")
+            .addResourceFromClasspath(form1Path)
+            .send()
+            .join();
+
+    final Long formKey = deployment.getForm().getFirst().getFormKey();
```
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/FormLinkingIT.java:64]: We can also use Long.toString() during conversion in assertions. But I preferred this way to make a change only in one place.

File: engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbFormState.java [hunk 2]
```diff
@@ -137,8 +137,9 @@ public Optional<PersistedForm> findLatestFormById(
       return Optional.empty();
     }
 
-    formByTenantAndIdCache.put(new TenantIdAndFormId(tenantId, formId), persistedForm);
-    return Optional.of(persistedForm).map(PersistedForm::copy);
+    final PersistedForm copiedForm = persistedForm.copy();
+    formByTenantAndIdCache.put(new TenantIdAndFormId(tenantId, formId), copiedForm);
+    return Optional.of(copiedForm);
```
Comment (megglos) [inline engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbFormState.java:142]: out of interest, so the underlying cause is that
```
final PersistedForm persistedForm =
        formByIdAndVersionColumnFamily.get(tenantAwareIdAndVersionKey);
```
or generally `TransactionalColumnFamily.get` by design returns a mutable object, right?

Comment (berkaycanbc) [reply engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbFormState.java:142]: Yes, it fills the `dbPersistentForm` singular object existing in the DbFormState class with retrieved data and returns that object back.

Comment (megglos) [reply engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbFormState.java:142]: That seems like an easy and non obvious mistake to make, I wonder why it was designed that way. Will follow-up to learn or at least ensure we have the needed awareness of this.

Comment (berkaycanbc) [reply engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbFormState.java:142]: Yeah, we discussed the same thing with @korthout. It is designed to be performant and prevents Java object creation. Instead, it uses a single object and re-fill it on change.

Also, I think, there is a design improvement for the `get` method where it is a method with side effect but returns an object back. To emphasise its side effect, it should return `void` (probably the name should change from `get` as well). Therefore, db api users will know some state is mutated.

**Comment by megglos** [comment]
@berkaycanbc just added backport labels, as there is also already an existing release branch

**Review by korthout — APPROVED** [review]
Thanks @berkaycanbc 

As discussed, I've applied my review in a commit, rather than as comments. Please have a look and let me know what you think. Changes:
- use `@RegressionTest` rather than `@Test`
- use primitive long rather than `Long`
- only use form linking to produce the bug rather than form deployment

For the last change, we can consider the following steps to reproduce the issue:
- Deploy two forms with ids formId1 and formId2 and deploy two processes that contain a user task linking to each form respectively
- Take a snapshot
- Restart the broker, from last snapshot
- Create a process instance of process1 (the form linking is correct)
- Create a process instance of process2 (the form linking is correct but the cache will be corrupted)
- Create a process instance of process1 (the form linking is incorrect) => it will retrieve the key for formId2

I've also checked whether the change to the db state code could lead to issues on replay. But it doesn't. The affected method is only used by processors, so it's safe to change:

Screenshot 2024-02-14 at 11 52 10

LGTM 👍

File: engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbFormState.java (hunk 2 above)
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbFormState.java:142]: @megglos All column families are provided with objects representing the key and value. These are used by operations of the column family to perform their operations and to fill with output. Rather than providing constructors as suppliers, the object is reused for performance. In our code, we always need to copy objects before storing them because the object is likely reused in successive processing.

**Comment by berkaycanbc** [comment]
@korthout thanks for the updates. I think, looks like the thing changed in the test setup is that instead of creating a new form in between we create a process instance that refers to another form. As a result, the test looks simpler! 🚀 

LGTM!
