### PR TITLE
fix(engine): streamprocessor can recover on replay mode when no event available

### LINKED ISSUE #7662: Failed to recover Broker because snapshot position was not found.
**Describe the bug**

It seems due to latest changes we have now problems on restarting nodes. 

In general it seems to run (normal throughput etc.) but one node is not able to come up

broker

We see the following error on starting the corresponding broker `java.lang.IllegalStateException: Expected to find event with the snapshot position 18568732 in log stream, but nothing was found. Failed to recover 'Broker-1-StreamProcessor-2'.`

See related [stackdriver logs](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=0&project=zeebe-io&rif_reserved&minLogLevel=0&expandAll=false&timestamp=2021-08-20T08:36:48.390000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-state-on-followers%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-state-on-followers%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster-helm%22%0AjsonPayload.context.loggerName!%3D%22org.elasticsearch.client.RestClient%22&scrollTimestamp=2021-08-20T08:34:22.149121000Z&pinnedLogId=fzyda4yylyezfnsr&pinnedLogTimestamp=2021-08-20T08:34:22.149121Z&dateRangeStart=2021-08-20T07:36:48.390Z&dateRangeEnd=2021-08-20T09:36:48.390Z)

**To Reproduce**

Run a benchmark from develop.

**Expected behavior**

No issues on restart.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Expected to find event with the snapshot position 18568732 in log stream, but nothing was found. Failed to recover 'Broker-1-StreamProcessor-2'.
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:269) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:116) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
 - OS: k8
 - Zeebe Version: develop 
 - Configuration: benchmark

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

When starting on replay mode, the events that are already applied in the snapshot may not be available in the logstreams. This can happen because after the snapshot is received, the replication of events after the snapshot index is delayed. In this case, we don't want to fail the recovery. ReplayStateMachine can wait and apply the events when they are available.

## Related issues

closes #7662 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessorReplayModeTest.java [hunk 1]
```diff
@@ -109,6 +110,40 @@ public void shouldReplayContinuously() {
     assertThat(getCurrentPhase(replayContinuously)).isEqualTo(Phase.REPROCESSING);
   }
 
+  @Test
+  public void shouldRecoverAndReplayCorrectlyWhenEventAtSnapshotPositionIsNotAvailableOnStart() {
```
Comment (saig0) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessorReplayModeTest.java:114]: :upside_down_face: The name of the test is too long to read. 

We could rename it to something shorter like `shouldReplayIfNoEventsAfterSnapshot`.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessor.java [hunk 2]
```diff
@@ -264,7 +264,8 @@ private long recoverFromSnapshot() {
         zeebeState.getLastProcessedPositionState().getLastSuccessfulProcessedRecordPosition();
 
     final boolean failedToRecoverReader = !logStreamReader.seekToNextEvent(snapshotPosition);
-    if (failedToRecoverReader) {
+    if (failedToRecoverReader
+        && processingContext.getProcessorMode() == StreamProcessorMode.PROCESSING) {
```
Comment (saig0) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessor.java:268]: :thought_balloon: I'm not sure if we really need this check, even for processing. I guess that Raft ensures that the right node will be the next leader.

**Review by saig0 — APPROVED** [review]
@deepthidevaki looks good :+1: 

Please have a look at my comments. But feel free to merge :rocket:

File: engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessor.java (hunk 2 above)
Comment (deepthidevaki) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessor.java:268]: Raft ensures that this node has the latest data. So it is expected that the it will never fail here. But could there by any issues that can cause this to fail - such as bugs, data corruption etc? The question is should we guard against those?

Comment (saig0) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessor.java:268]: We can leave the check for now. I just had the feeling it is not necessary :sweat_smile:
