### PR TITLE
Raise incident on element instance commands exceeding max message size

### LINKED ISSUE #13521: Process instances are banned when trying to activate a call activity with large variables
**Describe the bug**

If activating a call activity with large variables causes processing to exceed the batch size, the complete process instance is banned and left in limbo.

The current workaround is to ensure that we don't run into this case; however, once you hit it, there's nothing you can do but recreate the instance with smaller payloads.

Support:
-  https://jira.camunda.com/browse/SUPPORT-17661
- https://jira.camunda.com/browse/SUPPORT-17882

**To Reproduce**

Create a process with a dummy service task which leads to a call activity. Once the task is activated, separately as to not exceed the batch size, create 4 large variables, e.g. of 1MB each (using the set variable command, one at a time). Then complete the task. Activating the call activity will fail and result in a banned instance.

**Expected behavior**

An incident is raised, such that I can modify my variables to save this instance.

**Log/Stacktrace**

I've anonymized the stacktrace below. You can find more logs here: https://cloudlogging.app.goo.gl/aarrs1J5TY22X5gXA

<details><summary>Full Stacktrace</summary>
 <p>

```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=PROCESS_INSTANCE, intent=ACTIVATE_ELEMENT}, value={"bpmnElementType":"CALL_ACTIVITY","elementId":"Activity_1aba60i","bpmnProcessId":"process","version":8,"processDefinitionKey":2251800414371946,"processInstanceKey":4503599979491273,"flowScopeKey":4503599979491273,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1}}' without errors, but exception occurred with message 'Can't append entry: 'RecordBatchEntry[recordMetadata=RecordMetadata{recordType=EVENT, valueType=VARIABLE, intent=CREATED}, key=4503599980117234, sourceIndex=-1, unifiedRecordValue={"name":"foo","value":"U2VkIHV0IHBlcnNwaWNpYXRpcyB1bmRlIG9tbmlzIGlzdGUgbmF0dXMgZXJyb3Igc2l0IHZvbHVwdGF0ZW0gYWNjdXNhbnRpdW0gZG9sb3JlbXF1ZSBsYXVkYW50aXVtLCB0b3RhbSByZW0gYXBlcmlhbSwgZWFxdWUgaXBzYSBxdWFlIGFiIGlsbG8gaW52ZW50b3JlIHZlcml0YXRpcyBldCBxdWFzaSBhcmNoaXRlY3RvIGJlYXRhZSB2aXRhZSBkaWN0YSBzdW50IGV4cGxpY2Fiby4gTmVtbyBlbmltIGlwc2FtIHZvbHVwdGF0ZW0gcXVpYSB2b2x1cHRhcyBzaXQgYXNwZXJuYXR1ciBhdXQgb2RpdCBhdXQgZnVnaXQsIHNlZCBxdWlhIGNvbnNlcXV1bnR1ciBtYWduaSBkb2xvcmVzIGVvcyBxdWkgcmF0aW9uZSB2b2x1cHRhdGVtIHNlcXVpIG5lc2NpdW50LiBOZXF1ZSBwb3JybyBxdWlzcXVhbSBlc3QsIHF1aSBkb2xvcmVtIGlwc3VtIHF1aWEgZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyLCBhZGlwaXNjaSB2ZWxpdCwgc2VkIHF1aWEgbm9uIG51bXF1YW0gZWl1cyBtb2RpIHRlbXBvcmEgaW5jaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWduYW0gYWxpcXVhbSBxdWFlcmF0IHZvbHVwdGF0ZW0uIFV0IGVuaW0gYWQgbWluaW1hIHZlbmlhbSwgcXVpcyBub3N0cnVtIGV4ZXJjaXRhdGlvbmVtIHVsbGFtIGNvcnBvcmlzIHN1c2NpcGl0IGxhYm9yaW9zYW0sIG5...' with size: 1725121 this would exceed the maximum batch size. [ currentBatchEntryCount: 18, currentBatchSize: 2874115]'.

```

</p>
</details>

**Environment:**
- OS: Ubuntu Focal
- Zeebe Version: 8.2.8
- Configuration: SaaS

### PR DESCRIPTION
**Pull request by korthout**
## Description

Instead of banning an instance when the processing of an element instance's command exceeds the max batch size (or max message size), this ensures we raise an incident.

In most cases, this incident is resolvable, allowing users to recover easily. In other cases, the incident makes the problem visual to the user and the user can recover using process instance modification.

Tests have been added to deal with the specifics of the referenced bug, which is the activation/completion of a call activity with many large variables. However, this should also help in most other cases.

This does not completely remove all cases where we ban instances. It only deals with those cases where we exceed the batch size, which is likely the biggest reason at this time.

More effort to deal with other unexpected errors is needed.

## Related issues

closes #13521
relates to #5121 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/BpmnStreamProcessor.java [hunk 1]
```diff
@@ -88,6 +96,40 @@ public void processRecord(final TypedRecord<ProcessInstanceRecord> record) {
...
+                // even though we don't know how to resolve this incident, we can still
+                // raise it so the user can use modification to recover. The incident resolution
+                // logic is smart enough to deal with this case. It will log an error due to
+                // IllegalStateException.
+              default -> context;
+            };
+        incidentBehavior.createIncident(
+            new Failure(
+                """
+                Expected to transition element '%s', but ran into MAX_MESSAGE_SIZE limitation. \
```
Comment (remcowesterhoud) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/BpmnStreamProcessor.java:122]: 💭 I wonder if it's clearer for users if we say "Expected to process element". Transitioning may be a vague concept for them.

Comment (remcowesterhoud) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/BpmnStreamProcessor.java:122]: 💭 If it's easy we could access the MAX_MESSAGE_SIZE here to be more specific about the limitation. But this could also be an improvement at a later stage.
It could also be confusing as the metadata makes it so they can't reach the exact max message size, so might cause confusing than it clarifies.

**Review by remcowesterhoud — APPROVED** [review]
🚀 Thanks for driving this one @korthout 🙇 

I have some thoughts about the error message, but nothing blocking. Have a look and merge at your convenience.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/BpmnStreamProcessor.java (hunk 1 above)
Comment (korthout) [reply engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/BpmnStreamProcessor.java:122]: About adding more details about the message size:
- we had this issue as well working on expiring messages in a single command ([comment](https://github.com/camunda/zeebe/pull/13400#discussion_r1269286574))
- I also think these details can be confusing to most users that will read this error message in Operate
- Users have little control over the messages, it's not actionable information
- I prefer to avoid these details

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
Backports to 8.2 and 8.1 completed
