### PR TITLE
fix: rename mapping to mapping rule in clients

### LINKED ISSUE #34868: Rename mapping to mapping rule in client
### 

### Description

Rename mapping to mapping rule in client

### PR DESCRIPTION
**Pull request by maryarm**
## Description

Rename mapping to mapping rule in camunda client

## Related issues

closes #34868

### CODE REVIEW

File: clients/java/src/main/java/io/camunda/client/CamundaClient.java [hunk 1]
```diff
@@ -1192,22 +1192,22 @@ ActivateAdHocSubProcessActivitiesCommandStep1 newActivateAdHocSubProcessActiviti
...
 
   /**
-   * Command to assign a role to a mapping.
+   * Command to assign a mapping role to a role.
    *
    * <pre>
    *
    * camundaClient
-   *  .newAssignRoleToMappingCommand()
+   *  .newAssignMappingRuleToRoleCommand()
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/CamundaClient.java]: 💭 If it is `AssignMappingRuleToRole` mapping rule ID should be the first one in the command according to the convention (I believe)

```
camundaClient
   .newAssignMappingRuleToRoleCommand()
   .mappingRuleId("mappingRuleId")
   .roleId("roleId")
   .send();
```

File: clients/java/src/main/java/io/camunda/client/CamundaClient.java [hunk 2]
```diff
@@ -1370,17 +1370,17 @@ ActivateAdHocSubProcessActivitiesCommandStep1 newActivateAdHocSubProcessActiviti
    *
    * <pre>
    * camundaClient
-   *   .newUnassignRoleFromMappingCommand()
+   *   .newUnassignMappingRuleFromRoleCommand()
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/CamundaClient.java]: 💭 same applies here I believe:

```
camundaClient
   .newUnassignMappingRuleFromRoleCommand()
   .mappingRuleId("mappingRuleId")
   .roleId("roleId")
   .send();
```

File: clients/java/src/main/java/io/camunda/client/CamundaClient.java [hunk 3]
```diff
@@ -1192,22 +1192,22 @@ ActivateAdHocSubProcessActivitiesCommandStep1 newActivateAdHocSubProcessActiviti
   UpdateRoleCommandStep1 newUpdateRoleCommand(String roleId);
 
   /**
-   * Command to assign a role to a mapping.
+   * Command to assign a mapping role to a role.
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/CamundaClient.java]: 💭 just a typo: `role` instead of `rule`

File: clients/java/src/main/java/io/camunda/client/CamundaClient.java [hunk 4]
```diff
@@ -1370,17 +1370,17 @@ ActivateAdHocSubProcessActivitiesCommandStep1 newActivateAdHocSubProcessActiviti
...
    *   .roleId("roleId")
-   *   .mappingId("mappingId")
+   *   .mappingRuleId("mappingRuleId")
    *   .send();
    * </pre>
    *
    * <p>This command is only sent via REST over HTTP, not via gRPC <br>
    *
-   * @return a builder for the unassign role from mapping command
+   * @return a builder for the unassign mapping rule from role command
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/CamundaClient.java]: 💭 It says `Command to unassign a role from a mapping.`, probably should be `Command to unassign a role from a mapping rule.`

File: clients/java/src/main/java/io/camunda/client/CamundaClient.java [hunk 5]
```diff
@@ -2491,34 +2491,34 @@ ProcessInstanceGetCallHierarchyRequest newProcessInstanceGetCallHierarchyRequest
...
+   *    .sort((s) -> s.mappingRuleId().asc())
    *    .page((p) -> p.limit(100))
    *    .send();
    * </pre>
    *
    * @param groupId the ID of the group
    * @return a builder for the mappings by group search request
    */
-  MappingsByGroupSearchRequest newMappingsByGroupSearchRequest(String groupId);
+  MappingRulesByGroupSearchRequest newMappingRulesByGroupSearchRequest(String groupId);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/CamundaClient.java:2504]: 💭 comment says `Executes a search request to query mappings by group.`, should probably be `Executes a search request to query mapping rules by group.`

File: clients/java/src/main/java/io/camunda/client/CamundaClient.java [hunk 6]
```diff
@@ -2491,34 +2491,34 @@ ProcessInstanceGetCallHierarchyRequest newProcessInstanceGetCallHierarchyRequest
...
+   *  .sort((s) -> s.mappingRuleId().asc())
    *  .page((p) -> p.limit(100))
    *  .send();
    * </pre>
    *
    * @param roleId the ID of the role
    * @return a builder for the mappings by role search request
    */
-  MappingsByRoleSearchRequest newMappingsByRoleSearchRequest(String roleId);
+  MappingRulesByRoleSearchRequest newMappingRulesByRoleSearchRequest(String roleId);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/CamundaClient.java:2521]: 💭 `Executes a search request to query mappings by role.` -> `Executes a search request to query mapping rules by role.`

File: clients/java/src/main/java/io/camunda/client/api/command/CreateMappingRuleCommandStep1.java [hunk 7]
```diff
@@ -26,7 +26,7 @@ public interface CreateMappingCommandStep1 extends FinalCommandStep<CreateMappin
    * @return the builder for this command. Call {@link #send()} to complete the command and send it
    *     to the broker.
    */
-  CreateMappingCommandStep1 claimName(final String claimName);
+  CreateMappingRuleCommandStep1 claimName(final String claimName);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/api/command/CreateMappingRuleCommandStep1.java:29]: 💭 `Set the claim name to create mapping with.` -> `Set the claim name to create mapping rule with.`

File: clients/java/src/main/java/io/camunda/client/api/command/CreateMappingRuleCommandStep1.java [hunk 8]
```diff
@@ -35,7 +35,7 @@ public interface CreateMappingCommandStep1 extends FinalCommandStep<CreateMappin
    * @return the builder for this command. Call {@link #send()} to complete the command and send it
    *     to the broker.
    */
-  CreateMappingCommandStep1 claimValue(final String claimValue);
+  CreateMappingRuleCommandStep1 claimValue(final String claimValue);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/api/command/CreateMappingRuleCommandStep1.java:38]: 💭 `Set the claim value to create mapping with.` -> `Set the claim value to create mapping rule with.`

File: clients/java/src/main/java/io/camunda/client/api/command/CreateMappingRuleCommandStep1.java [hunk 9]
```diff
@@ -44,14 +44,14 @@ public interface CreateMappingCommandStep1 extends FinalCommandStep<CreateMappin
    * @return the builder for this command. Call {@link #send()} to complete the command and send it
    *     to the broker.
    */
-  CreateMappingCommandStep1 name(final String name);
+  CreateMappingRuleCommandStep1 name(final String name);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/api/command/CreateMappingRuleCommandStep1.java:47]: 💭 `Set the name to create mapping with.` -> `Set the name to create mapping rule with.`

File: clients/java/src/main/java/io/camunda/client/api/command/CreateMappingRuleCommandStep1.java [hunk 10]
```diff
@@ -44,14 +44,14 @@ public interface CreateMappingCommandStep1 extends FinalCommandStep<CreateMappin
...
   /**
    * Set the id to create mapping with.
    *
-   * @param mappingId the mapping id value
+   * @param mappingRuleId the mapping rule id value
    * @return the builder for this command. Call {@link #send()} to complete the command and send it
    *     to the broker.
    */
-  CreateMappingCommandStep1 mappingId(final String mappingId);
+  CreateMappingRuleCommandStep1 mappingRuleId(final String mappingRuleId);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/api/command/CreateMappingRuleCommandStep1.java:56]: 💭 `Set the id to create mapping with.` -> `Set the id to create mapping rule with.`

File: clients/java/src/main/java/io/camunda/client/api/search/filter/MappingRuleFilter.java [hunk 11]
```diff
@@ -17,37 +17,37 @@
...
 
   /**
    * Filter mappings by the specified mapping id.
    *
-   * @param mappingId the id of the mapping
+   * @param mappingRuleId the id of the mapping
    * @return the updated filter
    */
-  MappingFilter mappingId(final String mappingId);
+  MappingRuleFilter mappingRuleId(final String mappingRuleId);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/api/search/filter/MappingRuleFilter.java:28]: 💭 `Filter mappings by the specified mapping id.` -> `Filter mapping rules by the specified mapping id.`

File: clients/java/src/main/java/io/camunda/client/api/search/filter/MappingRuleFilter.java [hunk 12]
```diff
@@ -17,37 +17,37 @@
...
 
   /**
    * Filter mappings by the specified claim name.
    *
    * @param claimName the name of the claim
    * @return the updated filter
    */
-  MappingFilter claimName(final String claimName);
+  MappingRuleFilter claimName(final String claimName);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/api/search/filter/MappingRuleFilter.java:36]: 💭 `Filter mappings by the specified claim name.` -> `Filter mapping rules by the specified claim name.`

File: clients/java/src/main/java/io/camunda/client/api/search/filter/MappingRuleFilter.java [hunk 13]
```diff
@@ -17,37 +17,37 @@
...
 
   /**
    * Filter mappings by the specified claim value.
    *
    * @param claimValue the value of the claim
    * @return the updated filter
    */
-  MappingFilter claimValue(final String claimValue);
+  MappingRuleFilter claimValue(final String claimValue);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/api/search/filter/MappingRuleFilter.java:44]: 💭 `Filter mappings by the specified claim value.` -> `Filter mapping rules by the specified claim value.`

File: clients/java/src/main/java/io/camunda/client/api/search/filter/MappingRuleFilter.java [hunk 14]
```diff
@@ -17,37 +17,37 @@
...
 
   /**
    * Filter mappings by the specified name.
    *
    * @param name the name of the mapping
    * @return the updated filter
    */
-  MappingFilter name(final String name);
+  MappingRuleFilter name(final String name);
```
Comment (ana-vinogradova-camunda) [inline clients/java/src/main/java/io/camunda/client/api/search/filter/MappingRuleFilter.java:52]: 💭 `Filter mappings by the specified name.` -> `Filter mapping rules by the specified name.`

**Review by ana-vinogradova-camunda — APPROVED** [review]
🚀 Nothing blocking the merge, just some comments need adjustment
