### PR TITLE
fix: mark operation as completed with count 0

### LINKED ISSUE #38518: Progress bar remain appear after retry in operate
### 

### 

### 

### 

### Description

The progress bar doesn’t disappear after retry instances in Operate 

### Steps to reproduce

1. Open Operate
2. Select some process instance 
3. Click on retry 

### Current behavior

When the operation panel opens, the progress bar is displayed. However, after the operation is completed, the progress bar remains visible

### Expected behavior

The progress bar disappears when the operation is done .

### Environment

SaaS

### Version

Image

- Component Version: [e.g. 2.0.0]

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by pedesen**
## Description

Shows "0 retries succeeded" in case a batch operation did not contain any incidents. 

image

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #38518

### CODE REVIEW

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/useLoadingProgress.ts [hunk 1]
```diff
@@ -9,24 +9,24 @@
...
 /**
- * Returns a (faked) progress percentage and an isComplete indicator
- * based on totalCount, completedCount and isFinished parameters.
+ * Returns a (faked) progress percentage and an isVisuallyCompleted indicator
+ * based on totalCount, processedCount and isCompleted parameters.
  *
- * isFinished means the operation itself is finished
- * isComplete is true when the visual progress has finished
+ * isCompleted is true when the operation itself is completed
+ * isVisuallyCompleted is true when the visual progress is completed
```
Comment (pedesen) [inline operate/client/src/modules/components/OperationsPanel/OperationsEntry/useLoadingProgress.ts:16]: I renamed this and hope it's more clear now.

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/OperationEntryStatus/index.tsx [hunk 2]
```diff
@@ -64,7 +64,8 @@ const OperationEntryStatus: React.FC<Props> = ({
       {state === 'PARTIALLY_COMPLETED' && <PartiallyCompleted />}
       {state === 'FAILED' && <Failed />}
       <StatusContainer>
-        {completedCount > 0 ? (
+        {completedCount > 0 ||
+        (completedCount === 0 && failedCount === 0 && state === 'COMPLETED') ? (
```
Comment (pedesen) [inline operate/client/src/modules/components/OperationsPanel/OperationsEntry/OperationEntryStatus/index.tsx]: This will show "0 operations completed" in case an operation was "empty".

**Comment by pedesen** [comment]
@zsofiakm After fixing this bug, the UI shows "0 retries succeeded". While this reflects the reality, it might be confusing why nothing was retried. I could use some input on how to improve this. Maybe by using the checkmark warning icon (or similar) from Carbon with a warning color and a popover hint?

image

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx [hunk 3]
```diff
@@ -49,10 +49,10 @@ const OperationsEntry: React.FC<Props> = ({operation}) => {
     state,
   } = operation;
 
-  const {fakeProgressPercentage, isComplete} = useLoadingProgress({
+  const {fakeProgressPercentage, isVisuallyCompleted} = useLoadingProgress({
     totalCount: operationsTotalCount,
     processedCount: operationsCompletedCount + operationsFailedCount,
-    isFinished: endDate !== undefined,
+    isCompleted: !['CREATED', 'ACTIVE'].includes(state),
```
Comment (christoph-fricke) [inline operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx]: 🔧 Nit: `state !== 'CREATED' && state !== 'ACTIVE'`

❓Should `"SUSPENDED" | "PARTIALLY_COMPLETED" | "CANCELED" | "FAILED"` count as completed? That would currently be the case.

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/OperationEntryStatus/index.tsx (hunk 2 above)
Comment (christoph-fricke) [reply operate/client/src/modules/components/OperationsPanel/OperationsEntry/OperationEntryStatus/index.tsx]: 🔧 Might be worth capturing in a local var to express the semantic, and make it easier to understand the intention behind this conditional.
```ts
const isEmptyCompletion = state === 'COMPLETED' && completedCount === 0 && failedCount === 0;
```

**Review by christoph-fricke — APPROVED** [review]

**Comment by zsofiakm** [comment]
> @zsofiakm After fixing this bug, the UI shows "0 retries succeeded". While this reflects the reality, it might be confusing why nothing was retried. I could use some input on how to improve this. Maybe by using the checkmark warning icon (or similar) from Carbon with a warning color and a popover hint?
> 
> image

@pedesen I don't believe an icon here would help. In this case, would it be possible to have an alternative copy instead? `Completed — No incidents to retry`

**Comment by pedesen** [comment]
> @pedesen I don't believe an icon here would help. In this case, would it be possible to have an alternative copy instead? Completed — No incidents to retry

@zsofiakm Thanks, makes sense and is possible. I'll change it. :smile:

File: operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx (hunk 3 above)
Comment (pedesen) [reply operate/client/src/modules/components/OperationsPanel/OperationsEntry/index.tsx]: > Should "SUSPENDED" | "PARTIALLY_COMPLETED" | "CANCELED" | "FAILED" count as completed? That would currently be the case.

Yes in these cases there should be no progress bar.

**Review by vsgoulart — APPROVED** [review]
@pedesen Can we merge this one?

**Comment by pedesen** [comment]
@vsgoulart Yes, Let me try to get a green CI.
