### PR TITLE
fix: include default sort field in AuthorizationQuery

### LINKED ISSUE #48857: Authorization search endpoint does not return `page.startCursor` and `page.endCursor`
### 

### 

### 

### 

### Description

When calling the endpoint `v2/authorizations/search`, the response body contains:
```json
{
  "items": [...],
  "page": {
    "totalItems": 38,
    "hasMoreTotalItems": false
  }
}
```

This response body is missing the cursor parameters (that are also documented, but missing from the actual API response)

### Steps to reproduce

1. Run Camunda 8 in docker compose (I did not test other setups so far)
2. Call `POST localhost:8088/v2/authorizations/search`
3. The response is missing `page.startCursor` and `page.endCursor`

### Current behavior

The response is missing these documented and critical fields.

### Expected behavior

The response contains these fields, effectively allowing for iterating multiple pages.

### Workaround

As you cannot use cursors, the paging via offset is still possible.

### Environment

SM

### Version

- OC: 8.8.14

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by megglos**
## Description

For ES/OS:
The default sort field "id" was filtered out by retainValidSortings(), causing no sort to be sent to ES/OS for authorization searches without explicit sort. Without sort values on hits, cursors were always null.

For RDBMS:
The previous discriminator columns (ownerId, ownerType, resourceType)
were not unique, causing keyset pagination to skip rows with identical
values. 

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes), [for CI changes](https://camunda.github.io/camunda/ci/#when-to-backport-ci-changes), or [for documentation changes](https://camunda.github.io/camunda/ci/#documentation-specific-backporting-monorepo-docs-folders)).

## Related issues

closes #48857

### CODE REVIEW

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/AuthorizationIT.java [hunk 1]
```diff
@@ -545,6 +545,108 @@ void searchShouldReturnAuthorizationsSortedByResourcePropertyNames() {
             });
   }
 
+  @Test
+  void searchShouldReturnCursorsWithDefaultSort() {
```
Comment (tmetzke) [inline qa/acceptance-tests/src/test/java/io/camunda/it/client/AuthorizationIT.java:610]: ❓ Should we add a test that ensures the authorization key is the discriminator for "tied" records and also yields cursors?

**Review by tmetzke — APPROVED** [review]
👍 Fix looks good to me
🔧 One more test suggestion since we mention that we fixed skipping result entries

File: qa/acceptance-tests/src/test/java/io/camunda/it/client/AuthorizationIT.java (hunk 1 above)
Comment (megglos) [reply qa/acceptance-tests/src/test/java/io/camunda/it/client/AuthorizationIT.java:610]: added searchShouldUsAuthorizationKeyAsDiscriminatorForTiedRecordsAndYieldCursors
