### PR TITLE
Fix race condition when replicating the first entry of a compacted log and taking a snapshot simultaneously

### LINKED ISSUE #13093: `RandomizedRaftTest.consistencyTestWithSnapshot` fails with unexpected exception
**Describe the bug**

Running `RandomizedRaftTest.consistencyTestWithSnapshot` on 8.0.17 leads to the following exception:
```
java.lang.IllegalStateException: Expected to delete index after 404, but it is lower than the commit index 405. Deleting committed entries can lead to inconsistencies and is prohibited. at io.atomix.raft.storage.log.RaftLog.deleteAfter(RaftLog.java:186) at io.atomix.raft.roles.PassiveRole.replaceExistingEntry(PassiveRole.java:623) at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:562) at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:514) at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:370) at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:50) at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:187) at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$13(RaftContext.java:263) at 
...
```

See [Test results for unit tests(1).zip](https://github.com/camunda/zeebe/files/11734753/Test.results.for.unit.tests.1.zip) from test run https://github.com/camunda/zeebe/actions/runs/5255172343/jobs/9494733250

**To Reproduce**
| jqwick | explanation |
|--------|--------|
| tries = 10                    | # of calls to property |
| checks = 10                   | # of not rejected calls |
| generation = RANDOMIZED       | parameters are randomly generated |
| after-failure = PREVIOUS_SEED | use the previous seed |
| when-fixed-seed = ALLOW       | fixing the random seed is allowed |
| edge-cases#mode = NONE        | edge cases are not explicitly generated |
| seed = 2349382887260487435    | random seed to reproduce generated values |

**Expected behavior**

Test does not fail.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Expected to delete index after 404, but it is lower than the commit index 405. Deleting committed entries can lead to inconsistencies and is prohibited. at io.atomix.raft.storage.log.RaftLog.deleteAfter(RaftLog.java:186) at io.atomix.raft.roles.PassiveRole.replaceExistingEntry(PassiveRole.java:623) at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:562) at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:514) at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:370) at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:50) at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:187) at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$13(RaftContext.java:263) at io.atomix.raft.impl.RaftContext.lambda$runOnContext$20(RaftContext.java:274) at io.atomix.raft.DeterministicSingleThreadContext$WrappedRunnable.run(DeterministicSingleThreadContext.java:129) at org.jmock.lib.concurrent.DeterministicScheduler$CallableRunnableAdapter.call(DeterministicScheduler.java:176) at org.jmock.lib.concurrent.DeterministicScheduler$ScheduledTask.run(DeterministicScheduler.java:251) at org.jmock.lib.concurrent.DeterministicScheduler.runNextPendingCommand(DeterministicScheduler.java:66) at io.atomix.raft.ControllableRaftContexts.runNextTask(ControllableRaftContexts.java:246) at io.atomix.raft.RaftOperation.lambda$getDefaultRaftOperations$0(RaftOperation.java:62) at io.atomix.raft.RaftOperation.run(RaftOperation.java:42) at io.atomix.raft.RandomizedRaftTest.consistencyTest(RandomizedRaftTest.java:123) at io.atomix.raft.RandomizedRaftTest.consistencyTestWithSnapshot(RandomizedRaftTest.java:88) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725) at org.junit.platform.commons.support.ReflectionSupport.invokeMethod(ReflectionSupport.java:198) at net.jqwik.engine.execution.CheckedPropertyFactory.lambda$createRawFunction$1(CheckedPropertyFactory.java:84) at net.jqwik.engine.execution.CheckedPropertyFactory.lambda$createRawFunction$2(CheckedPropertyFactory.java:91) at net.jqwik.engine.properties.CheckedFunction.execute(CheckedFunction.java:17) at net.jqwik.api.lifecycle.AroundTryHook.lambda$static$0(AroundTryHook.java:57) at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$2(HookSupport.java:48) at net.jqwik.engine.hooks.lifecycle.TryLifecycleMethodsHook.aroundTry(TryLifecycleMethodsHook.java:57) at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$3(HookSupport.java:53) at net.jqwik.engine.execution.CheckedPropertyFactory.lambda$createTryExecutor$0(CheckedPropertyFactory.java:60) at net.jqwik.engine.execution.lifecycle.AroundTryLifecycle.execute(AroundTryLifecycle.java:23) at net.jqwik.engine.properties.GenericProperty.testPredicate(GenericProperty.java:166) at net.jqwik.engine.properties.GenericProperty.check(GenericProperty.java:68) at net.jqwik.engine.execution.CheckedProperty.check(CheckedProperty.java:67) at net.jqwik.engine.execution.PropertyMethodExecutor.executeProperty(PropertyMethodExecutor.java:90) at net.jqwik.engine.execution.PropertyMethodExecutor.executeMethod(PropertyMethodExecutor.java:69) at net.jqwik.engine.execution.PropertyMethodExecutor.lambda$execute$0(PropertyMethodExecutor.java:49) at net.jqwik.api.lifecycle.AroundPropertyHook.lambda$static$0(AroundPropertyHook.java:46) at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26) at net.jqwik.engine.hooks.lifecycle.PropertyLifecycleMethodsHook.aroundProperty(PropertyLifecycleMethodsHook.java:57) at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31) at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26) at net.jqwik.engine.hooks.statistics.StatisticsHook.aroundProperty(StatisticsHook.java:37) at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31) at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26) at net.jqwik.engine.hooks.lifecycle.AutoCloseableHook.aroundProperty(AutoCloseableHook.java:13) at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31) at net.jqwik.engine.execution.PropertyMethodExecutor.execute(PropertyMethodExecutor.java:47) at net.jqwik.engine.execution.PropertyTaskCreator.executeTestMethod(PropertyTaskCreator.java:166) at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$1(PropertyTaskCreator.java:51) at net.jqwik.engine.execution.lifecycle.CurrentDomainContext.runWithContext(CurrentDomainContext.java:28) at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$2(PropertyTaskCreator.java:50) at net.jqwik.engine.execution.pipeline.ExecutionTask$1.lambda$execute$0(ExecutionTask.java:31) at net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor.runWithDescriptor(CurrentTestDescriptor.java:17) at net.jqwik.engine.execution.pipeline.ExecutionTask$1.execute(ExecutionTask.java:31) at net.jqwik.engine.execution.pipeline.ExecutionPipeline.runToTermination(ExecutionPipeline.java:82) at net.jqwik.engine.execution.JqwikExecutor.execute(JqwikExecutor.java:46) at net.jqwik.engine.JqwikTestEngine.executeTests(JqwikTestEngine.java:70) at net.jqwik.engine.JqwikTestEngine.execute(JqwikTestEngine.java:53) at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107) at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88) at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54) at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67) at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52) at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114) at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86) at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86) at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55) at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:234) at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:228) at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175) at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:131) at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456) at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169) at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595) at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581) 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.0.17

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes a bug discovered via #13093: a race condition which can occur if we are replicating the very first entry of a compacted log right after a new snapshot was taken. This can cause the `prevLogIndex` and `prevLogTerm` sent to the follower to be incorrect, leading to errors on the follower side as it tries to replace an existing entry with the wrong one.

The fix was to combine both snapshot listeners so we can control the ordering. That left the `LogDeletionService` to be kind of useless at that point. We could have instead done everything there, but I think it just added overhead even if it slightly decoupled things.

## Related issues

closes #13093 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/impl/LogCompactor.java [hunk 1]
```diff
@@ -69,14 +71,28 @@ public boolean compactIgnoringReplicationThreshold() {
...
+   *
+   * <p>NOTE: this method is thread safe
+   */
+  public void setCompactableIndex(final long index) {
+    logger.trace("Updated compactable index to {}", index);
+    compactableIndex = index;
+  }
+
+  /** Compacts the log based on the snapshot store's lowest compaction bound. */
+  public void compactFromSnapshots(
```
Comment (npepinpe) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/LogCompactor.java:86]: I opted to pass the store/executor as arguments instead of polluting the state of the compactor, but I'm happy to change that if you'd like.

File: atomix/cluster/src/main/java/io/atomix/raft/partition/impl/RaftPartitionServer.java [hunk 2]
```diff
@@ -198,6 +199,7 @@ public CompletableFuture<Void> flushLog() {
     return server.flushLog();
   }
 
+  @VisibleForTesting
```
Comment (npepinpe) [inline atomix/cluster/src/main/java/io/atomix/raft/partition/impl/RaftPartitionServer.java:202]: This method is called ONLY from the `ZeebeIT` test. Ideally we would remove it, but I figured it wouldn't hurt to add the annotation to make it clearer that ideally we shouldn't use it in production code.

File: atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverIT.java
Comment (npepinpe) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverIT.java:1]: Lots of these changes are because the snapshot replication threshold is 100. Meaning whenever we compact, _we compact whatever the snapshot index is minus 100, and we only replicate if the follower is 100 records behind_.

It feels very fragile/brittle to be honest, but :shrug:

File: snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java [hunk 3]
```diff
@@ -271,6 +271,16 @@ public ActorFuture<Set<PersistedSnapshot>> getAvailableSnapshots() {
     return actor.call(() -> Collections.unmodifiableSet(availableSnapshots));
   }
 
+  @Override
+  public ActorFuture<Long> getCompactionBound() {
+    return actor.call(
+        () ->
+            availableSnapshots.stream()
```
Comment (npepinpe) [inline snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java:278]: :thought_balloon: Alternatively, we could keep the available snapshots in a `NavigableMap` so we can easily delete the oldest ones always :shrug:

Comment (deepthidevaki) [reply snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java:278]: It doesn't matter much as we don't expect to keep more than 2 or 3 snapshots at a time. But if it simplifies the code then go for it.

File: snapshot/src/test/java/io/camunda/zeebe/snapshots/PersistedSnapshotTest.java [hunk 4]
```diff
@@ -1,48 +0,0 @@
...
-import java.io.File;
-import java.io.IOException;
-import java.io.UncheckedIOException;
-import java.nio.file.Files;
-import java.nio.file.Path;
-import org.junit.Before;
-import org.junit.Rule;
-import org.junit.rules.TemporaryFolder;
-
-public final class PersistedSnapshotTest {
```
Comment (deepthidevaki) [inline snapshot/src/test/java/io/camunda/zeebe/snapshots/PersistedSnapshotTest.java:22]: :rofl: Zombie test!

**Review by deepthidevaki — APPROVED** [review]
:rocket: Managing compaction in Raft makes perfect sense.

File: atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverIT.java [hunk 5]
```diff
@@ -119,34 +119,33 @@ public void shouldRecoverLeaderRestart() throws Throwable {
   @Test
   public void shouldTakeSnapshot() throws Exception {
     // given
-    raftRule.appendEntries(128);
+    raftRule.appendEntries(228);
 
     // when
-    raftRule.doSnapshot(100);
+    raftRule.takeCompactingSnapshot(200);
```
[the remark this answers is not in the document]
Comment (npepinpe) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverIT.java:125]: :+1: I think that was just automated refactoring, since the base case before was to wait for compaction

File: snapshot/src/test/java/io/camunda/zeebe/snapshots/PersistedSnapshotTest.java (hunk 4 above)
Comment (npepinpe) [reply snapshot/src/test/java/io/camunda/zeebe/snapshots/PersistedSnapshotTest.java:22]: ups :see_no_evil: I think it's also my name on the commit :smile:

**Comment by npepinpe** [comment]
The brittleness for me is the test code. i.e. we need to make sure we take snapshots in increments in 100 because that's the threshold. But maybe it just seems like it because the tests were now all written to ignore it :shrug:

**Comment by npepinpe** [comment]
bors merge
