### PR TITLE
fix(atomix): consume read buffer correctly

### LINKED ISSUE #4248: FileChannelJournalSegmentReader throws half buffers away
**Description**

During our investigation of the engine latency we found out that the atomix journal is a big hotspot performance wise. We had a deeper look at the code and found the `readNext` method.

We have to say before that per Zeebe default the `maxEntrySize` is 4 MB. The reader will allocate a buffer which is `8MB` big. Our assumption is that it wants to do a read a head, but actually it doesn't because it clears the buffer positions etc.

```java

  /** Reads the next entry in the segment. */
  @SuppressWarnings("unchecked")
  private void readNext() {
    // Compute the index of the next entry in the segment.
    final long index = getNextIndex();

    try {
      // Read more bytes from the segment if necessary.
      if (memory.remaining() < maxEntrySize) {
        final long position = channel.position() + memory.position();
        channel.position(position);
        memory.clear(); // <=== this resets to position 0, limit to capacity
        channel.read(memory);  // <=== we read now again 8 MB
        channel.position(position);
        memory.flip();
      }

      // Mark the buffer so it can be reset if necessary.
      memory.mark();

      try {
        // Read the length of the entry.
        final int length = memory.getInt();

        // If the buffer length is zero then return.
        if (length <= 0 || length > maxEntrySize) {
          memory.reset().limit(memory.position());
          nextEntry = null;
          return;
        }

        // Read the checksum of the entry.
        final long checksum = memory.getInt() & 0xFFFFFFFFL;

        // Compute the checksum for the entry bytes.
        final Checksum crc32 = new CRC32();
        crc32.update(memory.array(), memory.position(), length);

        // If the stored checksum equals the computed checksum, return the entry.
        if (checksum == crc32.getValue()) {
          final int limit = memory.limit();
          memory.limit(memory.position() + length);
          final E entry = namespace.deserialize(memory);
          memory.limit(limit);
          nextEntry = new Indexed<>(index, entry, length);
        } else {
          memory.reset().limit(memory.position());
          nextEntry = null;
        }
      } catch (final BufferUnderflowException e) {
        memory.reset().limit(memory.position());
        nextEntry = null;
      }
    } catch (final IOException e) {
      throw new StorageException(e);
    }
  }
```

This means we will read `8 MB` process from these `~4 MB`until our `remaining` is less then `maxEntrySize`, so after we reached half of the buffer. Then we will read again `8MB` where the other remaining is thrown away and will end at the beginning of the buffer, because it is re-read.

This problem is more an issue when the `maxEntrySize` and `realEntrySize` is very different, which is our case. We using `4MB` to support big deployments but actually most of our records are less then 1 kb. If the sizes would be nearer then we would probably also read most of the buffer, but this is not our use case so we should fix this!

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Fix issue where the read buffer was consumed only half and the rest was
 thrown away.

Refactor `FileChannelJournalSegmentReader#readNext` to improve readability and hopefully maintainability.

I run also a benchmark with these changes (https://github.com/zeebe-io/zeebe/pull/4358 was also part of the branch I run a benchmark with)

metrics

## Related issues

closes #4248 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
I didn't quite understand what was the problem in the previous version. But now the code is more readable , so :+1: :slightly_smiling_face: 

Can we add more tests for this in `FileChannelSegmentReaderTest`? I could find the problem with reading checksum length by tweaking the existing test to read all events, write entries of type Long and set max entry size to 2*Long. I think that we have to test it with different configuration - entry size, max entry size etc. to find potential bugs here.

**Comment by Zelldon** [comment]
Thanks @deepthidevaki for the review. I adjusted my PR and take the checksum length into account. I also changed to current tests such that they are failing if this check is missing. Furthermore I added one more test.

File: atomix/storage/src/test/java/io/atomix/storage/journal/AbstractJournalTest.java [hunk 1]
```diff
@@ -91,7 +91,7 @@ public static Collection primeNumbers() {
         .withNamespace(NAMESPACE)
         .withStorageLevel(storageLevel())
         .withMaxSegmentSize(maxSegmentSize)
-        .withMaxEntrySize(64)
+        .withMaxEntrySize(48)
```
Comment (deepthidevaki) [inline atomix/storage/src/test/java/io/atomix/storage/journal/AbstractJournalTest.java:94]: I'm thinking if it would be good to test with multiple max entry sizes to find other potential bugs in future.

**Review by deepthidevaki — APPROVED** [review]
:+1: Looks good. Just one minor comment.

File: atomix/storage/src/test/java/io/atomix/storage/journal/AbstractJournalTest.java (hunk 1 above)
Comment (Zelldon) [reply atomix/storage/src/test/java/io/atomix/storage/journal/AbstractJournalTest.java:94]: Are you fine in doing this in a separate issue? Then I would create an issue to improve in the journal tests.

Comment (deepthidevaki) [reply atomix/storage/src/test/java/io/atomix/storage/journal/AbstractJournalTest.java:94]: Yes :+1:

Comment (Zelldon) [reply atomix/storage/src/test/java/io/atomix/storage/journal/AbstractJournalTest.java:94]: https://github.com/zeebe-io/zeebe/issues/4407

**Comment by Zelldon** [comment]
Bors r+
