### PR TITLE
Fix startup failure due to old install requests

### LINKED ISSUE #14367: Duplicate snapshot replication causing to fail raft follower
**Describe the bug**

Error group https://console.cloud.google.com/errors/detail/CLXT_uWi3KaNSQ;service=zeebe;time=P7D?project=camunda-saas-int-chaos

We recently reworked how we store replicated snapshots, and added some error cases that should fail when we for example receive a duplicate snapshot.

This seemed to happen in one of our recent chaos tests. The impact is quite high since due to the exception, which is thrown in this case, the node transitions to inactive. It will no longer take part of the corresponding partition.

**To Reproduce**

Not clear yet.

**Expected behavior**

No duplicate snapshot replication

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.snapshots.SnapshotException$SnapshotAlreadyExistsException: Expected to receive snapshot with id 225-1-225-240, but was already persisted. This shouldn't happen.
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:381) ~[zeebe-snapshots-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:51) ~[zeebe-snapshots-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.onInstall(PassiveRole.java:190) ~[zeebe-atomix-cluster-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.atomix.raft.roles.FollowerRole.onInstall(FollowerRole.java:83) ~[zeebe-atomix-cluster-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$8(RaftContext.java:303) ~[zeebe-atomix-cluster-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$27(RaftContext.java:322) ~[zeebe-atomix-cluster-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) [zeebe-atomix-utils-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: snapshot 8.3
- Configuration:

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes an edge case where install requests were retried/queued after the snapshot had been persisted (e.g. an I/O stall causes the persist to slow down, causing the leader to retry the last chunk). This would prevent startup. This was due to the snapshot listeners being called asynchronously. Since this is what updates the Raft context's local current snapshot reference, it created a small window where the follower would reply with an outdated snapshot reference, and accept out of order install requests.

The fix is to immediately update local snapshot reference on update. Additionally, the `SnapshotAlreadyExistsException` is tolerated on the follower, and a warning issues when it happens.

Test infrastructure was updated to support multiple ways to configure a server. Previously, you could only configure the `RaftServer.Builder`, but since we have multiple builders, it wasn't very useful. By introducing a generic interface, and checking multiple types in different places, you can now pass a single object which can configure various builders.

The last commit also removes an outdated test which was incorrectly testing behavior that
does not exist anymore. We used to persist snapshots before resetting the log, and this is what the test was covering. However, it never worked because it was in fact restarting the node with no snapshot (which is also why it didn't fail when we removed the old behavior).

As we now always persist snapshots after resetting the log, this case simply cannot happen.

## Related issues

closes #14367 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java [hunk 1]
```diff
@@ -1214,6 +1210,12 @@ public PersistedSnapshot getCurrentSnapshot() {
     return currentSnapshot;
   }
 
+  public void setCurrentSnapshot(final PersistedSnapshot snapshot) {
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:1213]: ❓ Is this now called twice?

File: atomix/cluster/src/test/java/io/atomix/raft/RaftRule.java [hunk 2]
```diff
@@ -536,21 +530,27 @@ public void copySnapshotOffline(final String sourceNode, final String targetNode
...
-      final MemberId memberId,
-      final Function<RaftStorage.Builder, RaftStorage.Builder> configurator) {
-
+  private RaftStorage createStorage(final MemberId memberId, final Configurator configurator) {
     final var memberDirectory = getMemberDirectory(directory, memberId.toString());
-    final RaftStorage.Builder defaults =
+    final var snapshotStore = new TestSnapshotStore(getOrCreatePersistedSnapshot(memberId.id()));
+    snapshotStores.put(memberId.id(), snapshotStore);
+
+    if (configurator instanceof final SnapshotStoreConfigurator s) {
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftRule.java:528]: 🔧 It feels somehow wrong to use these instanceof 😅 couldn't we have different objects with the specific interfaces or all implementing/overloading/extending the same configure method ? 🤔


Or does this not work because we have to call it in different places?

Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftRule.java:528]: Or how about one interface with three default methods? Which can be implemented by the given configurators?

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java [hunk 3]
```diff
@@ -73,4 +75,36 @@ public void shouldNotFailRestartIfFollowerCrashedBeforeCommittingSnapshot() thro
                 assertThat(raftRule.getPersistedSnapshotStore(followerId).getCurrentSnapshotIndex())
                     .isEqualTo(snapshotIndex));
   }
+
+  @Test // regression test for https://github.com/camunda/zeebe/issues/14367
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:79]: 🔧 Didn't you had a annotation for regression tests or doesn't this work here?

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java [hunk 4]
```diff
@@ -73,4 +75,36 @@ public void shouldNotFailRestartIfFollowerCrashedBeforeCommittingSnapshot() thro
...
+    raftRule.takeCompactingSnapshot(leader, snapshotIndex - 1, 3);
+    final var lastIndex = raftRule.appendEntries(10);
+    leader.getContext().setPreferSnapshotReplicationThreshold(1);
+
+    // when -- persisting the snapshot on the follower is too slow, the leader will retry the
+    // `install` requests
+    final Runnable interceptor =
+        () -> {
+          try {
+            // TODO: better way to force a timeout?
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:96]: 😆 are you planning to do something here?

File: atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java [hunk 5]
```diff
@@ -185,8 +186,20 @@ public CompletableFuture<InstallResponse> onInstall(final InstallRequest request
                     .build()));
       }
 
-      pendingSnapshot =
-          raft.getPersistedSnapshotStore().newReceivedSnapshot(snapshotChunk.getSnapshotId());
+      try {
+        pendingSnapshot =
+            raft.getPersistedSnapshotStore().newReceivedSnapshot(snapshotChunk.getSnapshotId());
```
Comment (Zelldon) [inline atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java:191]: 🤔 Would it fail here or on the persist? If it fails here on start of the snapshot replication could we somehow disrupt the replication and say its ok we already have one?

File: atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverIT.java [hunk 6]
```diff
@@ -379,34 +379,6 @@ public void shouldTruncateLogOnNewerSnapshot() throws Throwable {
...
-    final var followerB = raftRule.shutdownFollower();
-    raftRule.appendEntries(250);
-    raftRule.takeCompactingSnapshot(200); // take into account the replication threshold
-    // Leader and Follower A Log [200-300].
-    // Follower B Log [1-51]
-
-    // Follower B has old log AND snapshot
-    final var nodes = raftRule.getNodes();
-    final var followerA = nodes.stream().findFirst().orElseThrow();
-    raftRule.copySnapshotOffline(followerA, followerB);
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverIT.java:395]: 🤔 in your PR/commit description you meant it was not working because it was restarting without snapshot, but here we copied one right do mimik the scenario that we were interrupted between snapshot replication/taking and resetting the log correct? This is nothing we need to consider now? As far as I have seen the previous code you changed regarding the listener there was also compaction done after persisting the snapshot ? 🤔

**Review by ChrisKujawa — COMMENTED** [review]
Thanks @npepinpe for taking a look at this and already providing a fix so quick 🚀 

I have some follow-up questions I would like to clarify first before we continue, we can also do this f2f if you want.

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java (hunk 4 above)
Comment (npepinpe) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:96]: I was hoping you'd have a better idea :smile:

File: atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverIT.java (hunk 6 above)
Comment (npepinpe) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftFailOverIT.java:395]: It was copying it, and then when it restarted the server was discarding the snapshot store, and thus discarding the snapshot it had just copied :smile:

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java (hunk 3 above)
Comment (npepinpe) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:79]: It's only for junit 5 :disappointed:

File: atomix/cluster/src/test/java/io/atomix/raft/RaftRule.java (hunk 2 above)
Comment (npepinpe) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftRule.java:528]: The main difference with this approach is you can pass a lambda which implements any of the interfaces, or a class which implements multiple. If you have different objects, then you end up with many params and/or overloaded methods. If you have a single interface with multiple overloaded configure methods, you can't use a lambda (or maybe you can, but only in one case).

At any rate, I don't care that much to be honest - I figured it was fine since this is just test code, and I would prioritize ergonomy over performance or the likes, but :shrug: Happy to change it :+1:

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java (hunk 1 above)
Comment (npepinpe) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:1213]: In the case of snapshot replication, yes - we can't really avoid it. And we need the listener for the case where the local node takes a snapshot (i.e. transient snapshots) =/

I think that's acceptable considering it's not the hot path, and it doesn't do much.

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java (hunk 4 above)
Comment (npepinpe) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:97]: I added a way to intercept requests in the test protocol so we don't need to sleep.

**Comment by npepinpe** [comment]
As discussed, feel free to make any changes required for merging, and if you have too much on your plate, don't hesitate to delegate to Deepthi who is semi-aware of what this is :+1:

File: atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java (hunk 1 above)
Comment (Zelldon) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:1243]: Maybe @deepthidevaki has an opinion on this since Nicolas is on FTO. 

We now call `setCurrentSnapshot` twice, one mostly directly and one later when the snapshot store persists the snapshots. Is this an issue during compacting?

Comment (deepthidevaki) [reply atomix/cluster/src/main/java/io/atomix/raft/impl/RaftContext.java:1243]: I don't think there is any correctness issue in calling it twice. It is just unnecessary work.

File: atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java [hunk 7]
```diff
@@ -104,7 +111,21 @@ public void shouldHandleRetriedRequestsAfterSnapshotPersist() throws Exception {
...
           @Override
-          public void configure(final MemberId id, final TestSnapshotStore snapshotStore) {
+          public void configure(final MemberId id, final Builder builder) {
+            final var protocol = (TestRaftServerProtocol) builder.protocol;
+            protocol.interceptRequest(
+                InstallRequest.class,
+                r -> {
+                  // only allow the persist method to complete if we know this request was received
+                  // AFTER we already tried persisting (i.e. when persist is currently blocking)
+                  if (snapshotPersistCalled.get()) {
```
Comment (Zelldon) [inline atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:121]: Hasn't this potential for race conditions 🤔 also wouldn't the above block the raft thread?

Comment (Zelldon) [reply atomix/cluster/src/test/java/io/atomix/raft/RaftStartupConsistencyCheckTest.java:121]: Ok nevermind I think I get it now, should be fine

**Review by ChrisKujawa — APPROVED** [review]
Thanks @npepinpe 👍🏼 

bors r+
