### PR TITLE
Fix overlapping ids with Identity entities

### LINKED ISSUE #35549: Overlapping IDs for child docs causing overwriting of records
### 

### 

### 

### 

### Description

In https://github.com/camunda/camunda/pull/34641 we updated the ids to be more unique when stored in specifically ES/OS. It appears that we have a similar issue with the members of another entity where an ID is shared amongst different member types.

Related Slack conversation is [here](https://camunda.slack.com/archives/C06UYJMMETZ/p1752746397524189)

### Steps to reproduce

[Whilst in Identity]

1. Create a Group with ID: test
2. Create a Role with ID: test
3. Create a Tenant with any name (we'll use this below)
4. Assign the Group (ID: test) to the Tenant created in step 3
5. Refresh the page to see the Group assigned
6. Assign the Role (ID: test) to the Tenant created in step 3
7. Refresh the page to see the Role assigned
8. Navigate back to the Groups tab to see the Group no longer assigned
9. Try to assign the Group (ID: test) to the Tenant created in step 3 and observe a 409 error

### Current behavior

The membership appears to be overwritten at the ES/OS layer due to the IDs not considering the member type, for example `member-test-tenant-test`

### Expected behavior

Memberships are not overwritten where IDs are shared amongst different entities

### Environment

SaaS & SM

### Version

8.8.0-alpha6+

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Ensure there are no ID conflicts between Identity-related entities when they are persisted in ES/OS.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #35549

### CODE REVIEW

**Comment by koevskinikola** [comment]
👋 Hey @Ben-Sheppard, I think you would be a good reviewer for this fix since you discovered the issue. Please let me know if you don't have the time to review the PR.

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/RoleMemberRemovedHandlerTest.java [hunk 1]
```diff
@@ -62,7 +62,8 @@ void shouldGenerateIds() {
     final var value = roleRecord.getValue();
     assertThat(idList)
         .containsExactly(
-            RoleIndex.JOIN_RELATION_FACTORY.createChildId(value.getRoleId(), value.getEntityId()));
+            RoleIndex.JOIN_RELATION_FACTORY.createChildId(
```
Comment (Ben-Sheppard) [inline zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/RoleMemberRemovedHandlerTest.java:64]: 💭 Not your change of course but I'm wondering why this class exists outside of the handler test package 🙃

**Review by Ben-Sheppard — APPROVED** [review]
LGTM :) I've also checked out the code locally to look at the ES state and its as expected.

I like the addition of the ITs here to test for regressions, nice one.

File: zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/RoleMemberRemovedHandlerTest.java (hunk 1 above)
Comment (koevskinikola) [reply zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/RoleMemberRemovedHandlerTest.java:64]: I assume that was just a personal preference when the tests were initially created. I'll move it in the handler test package to align it, and make it harder to miss for future changes 😄
