### PR TITLE
fix(engine): fix terminate xor incident terminating

### LINKED ISSUE #6593: Migrated elements are not correctly terminated
**Description**

After merging https://github.com/camunda-cloud/zeebe/pull/6562 and working on the event sub process generation I found a failing model.

diagram_1

The problem with this model is that the exclusive gateway is already migrated, which means we need to calculate here differently whether we can trigger the event sub process. Otherwise the sub process is not triggered.

*Reproducer*

```java
  @Test
  public void shouldTerminateXorWithIncident() {
    // given
    final ProcessBuilder process = Bpmn.createExecutableProcess(PROCESS_ID);

    process
        .eventSubProcess("event_sub_proc")
        .startEvent("event_sub_start")
        .interrupting(true)
        .message(b -> b.name(MSG_NAME).zeebeCorrelationKeyExpression("key"))
        .endEvent("event_sub_end");

    final BpmnModelInstance model =
        process
            .startEvent("start_proc")
            .sequenceFlowId("toXor")
            .exclusiveGateway("xor")
            .condition("=yolo")
            .endEvent()
            .done();

    engineRule.deployment().withXmlResource(model).deploy();

    final long processInstanceKey =
        engineRule
            .processInstance()
            .ofBpmnProcessId(PROCESS_ID)
            .withVariables(Map.of("key", 123, "key1", 123))
            .create();

    // when
    RecordingExporter.incidentRecords(IncidentIntent.CREATED)
        .withProcessInstanceKey(processInstanceKey)
        .await();

    engineRule
        .message()
        .withName(MSG_NAME)
        .withCorrelationKey("123")
        .withVariables(Map.of("key", "123"))
        .publish();

    // then
    assertThat(
            RecordingExporter.processInstanceRecords()
                .withProcessInstanceKey(processInstanceKey)
                .limitToProcessInstanceCompleted())
        .extracting(r -> tuple(r.getValue().getBpmnElementType(), r.getIntent()))
        .containsSubsequence(
            tuple(BpmnElementType.START_EVENT, ProcessInstanceIntent.EVENT_OCCURRED),
            tuple(BpmnElementType.SUB_PROCESS, ProcessInstanceIntent.ELEMENT_ACTIVATED),
            tuple(BpmnElementType.SUB_PROCESS, ProcessInstanceIntent.ELEMENT_COMPLETED),
            tuple(BpmnElementType.PROCESS, ProcessInstanceIntent.ELEMENT_COMPLETED));
  }
```

*Output*:
```
16:31:38.444 [] INFO  io.zeebe.test - Test failed, following records were exported:
16:31:38.495 [] INFO  io.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DEPLOYMENT             CREATE            - #01-> -1  -1 - process.xml
E PROC                   CREATED           - #02->#01 K01 - process.xml->"proc" (version:1)
E DEPLOYMENT             CREATED           - #03->#01 K02 - process.xml
E DEPLOYMENT             FULLY_DISTR       - #04->#01 K02 - 
C PROC_INSTANCE_CREATION CREATE            - #05-> -1  -1 - new <process "proc"> with variables: {key1=123, key=123}
E VARIABLE               CREATED           - #06->#05 K04 - key1->123 in <process [K03]>
E VARIABLE               CREATED           - #07->#05 K05 - key->123 in <process [K03]>
E PROC_INSTANCE          ELMNT_ACTIVATING  - #08->#05 K03 - PROCESS "proc" in <process "proc"[K03]>
E PROC_INSTANCE_CREATION CREATED           - #09->#05 K06 - new <process "proc"> with variables: {key1=123, key=123}
E PROC_MSG_SUB           CREATING          - #10->#08  -1 - "messageName" (inter.) correlationKey: 123 @[K03] in <process "proc"[K03]> (no vars)
E PROC_INSTANCE          ELMNT_ACTIVATED   - #11->#08 K03 - PROCESS "proc" in <process "proc"[K03]>
C MSG_SUB                CREATE            - #12-> -1  -1 - "messageName" (inter.) correlationKey: 123 @[K03] in <process "proc"[K03]> (no vars)
E PROC_INSTANCE          ELMNT_ACTIVATING  - #13->#11 K07 - START_EVENT "start_proc" in <process "proc"[K03]>
E MSG_SUB                CREATED           - #14->#12 K08 - "messageName" (inter.) correlationKey: 123 @[K03] in <process "proc"[K03]> (no vars)
C PROC_MSG_SUB           CREATE            - #15-> -1  -1 - "messageName" (inter.) @[K03] in <process ?> (no vars)
E PROC_INSTANCE          ELMNT_ACTIVATED   - #16->#13 K07 - START_EVENT "start_proc" in <process "proc"[K03]>
E PROC_MSG_SUB           CREATED           - #17->#15  -1 - "messageName" (inter.) @[K03] in <process ?> (no vars)
E PROC_INSTANCE          ELMNT_COMPLETING  - #18->#16 K07 - START_EVENT "start_proc" in <process "proc"[K03]>
E PROC_INSTANCE          ELMNT_COMPLETED   - #19->#18 K07 - START_EVENT "start_proc" in <process "proc"[K03]>
E PROC_INSTANCE          SEQ_FLOW_TAKEN    - #20->#19 K09 - SEQUENCE_FLOW "toXor" in <process "proc"[K03]>
C PROC_INSTANCE          ACTIVATE_ELMNT    - #21->#20 K10 - EXCLUSIVE_GATEWAY "xor" in <process "proc"[K03]>
E PROC_INSTANCE          ELMNT_ACTIVATING  - #22->#21 K10 - EXCLUSIVE_GATEWAY "xor" in <process "proc"[K03]>
C INCIDENT               CREATE            - #23->#21  -1 - EXTRACT_VALUE_ERROR failed to evaluate expression 'yolo': no variable found for name 'yolo',  @"xor"[K10] in <process "proc"[K03]>
E INCIDENT               CREATED           - #24->#23 K11 - EXTRACT_VALUE_ERROR failed to evaluate expression 'yolo': no variable found for name 'yolo',  @"xor"[K10] in <process "proc"[K03]>
C MSG                    PUBLISH           - #25-> -1  -1 - "messageName" correlationKey: 123 with variables: {key=123}
E MSG                    PUBLISHED         - #26->#25 K12 - "messageName" correlationKey: 123 with variables: {key=123}
E MSG_SUB                CORRELATING       - #27->#25 K08 - "messageName" (inter.) correlationKey: 123 @[K03] in <process "proc"[K03]> with variables: {key=123}
C PROC_MSG_SUB           CORRELATE         - #28-> -1  -1 - "messageName" (inter.) correlationKey: 123 @[K03] in <process "proc"[K03]> with variables: {key=123}
E PROC_MSG_SUB           CORRELATED        - #29->#28  -1 - "messageName" (inter.) correlationKey: 123 @[K03] in <process "proc"[K03]> with variables: {key=123}
E PROC_INSTANCE          EVENT_OCCURRED    - #30->#28 K13 - START_EVENT "event_sub_start" in <process "proc"[K03]>
C MSG_SUB                CORRELATE         - #31-> -1  -1 - "messageName" (inter.) @[K03] in <process "proc"[K03]> (no vars)
C PROC_INSTANCE          TERMINATE_ELMNT   - #32->#30 K10 - EXCLUSIVE_GATEWAY "xor" in <process "proc"[K03]>
E MSG_SUB                CORRELATED        - #33->#31 K08 - "messageName" (inter.) correlationKey: 123 @[K03] in <process "proc"[K03]> with variables: {key=123}
E PROC_INSTANCE          ELMNT_TERMINATING - #34->#32 K10 - EXCLUSIVE_GATEWAY "xor" in <process "proc"[K03]>
E INCIDENT               RESOLVED          - #35->#32 K11 - EXTRACT_VALUE_ERROR failed to evaluate expression 'yolo': no variable found for name 'yolo',  @"xor"[K10] in <process "proc"[K03]>
E PROC_INSTANCE          ELMNT_TERMINATED  - #36->#32 K10 - EXCLUSIVE_GATEWAY "xor" in <process "proc"[K03]>
```

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

We now decide based on whether the child is migrated or not what element instance count we check.

## Related issues

closes https://github.com/camunda-cloud/zeebe/issues/6593

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

File: engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnEventSubscriptionBehavior.java [hunk 1]
```diff
@@ -456,9 +457,13 @@ public void publishTriggeredEventSubProcess(final BpmnElementContext context) {
...
-        && elementInstance.isInterrupted()
-        && elementInstance.isActive();
+  private boolean isInterrupted(
+      final boolean isChildMigrated, final ElementInstance elementInstance) {
+    final boolean shouldITurnOffTheLights =
+        isChildMigrated
+            ? elementInstance.getNumberOfActiveElementInstances() == 0
+            : elementInstance.getNumberOfActiveElementInstances() == 1;
+
+    return shouldITurnOffTheLights && elementInstance.isInterrupted() && elementInstance.isActive();
```
Comment (npepinpe) [inline engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnEventSubscriptionBehavior.java:467]: :smile: great name

How about:

```suggestion
final int expectedActiveInstanceCount = isChildMigrated ? 0 : 1;
    return elementInstance.getNumberOfActiveElementInstances() == expectedActiveInstanceCount
        && elementInstance.isInterrupted()
        && elementInstance.isActive();
```

That way later we can just inline the variable and remove it.

**Review by npepinpe — APPROVED** [review]
:+1: good catch

I had one suggestion but not a blocker, and no need for another review if you accept it

File: engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnEventSubscriptionBehavior.java (hunk 1 above)
Comment (Zelldon) [reply engine/src/main/java/io/zeebe/engine/processing/bpmn/behavior/BpmnEventSubscriptionBehavior.java:467]: Haha lol actually it did this when I discussed with phil the solution but have forgotten to change the name again :laughing:
