### PR TITLE
Make resource deployments atomic

### LINKED ISSUE #5723: Deployments are stored in state even when one workflow is rejected
**Describe the bug**

Scenario:

 * Deployment with multiple workflows
 * One of the workflows is broken
 * If you send the deploy command you get an rejection back
 * If you fix the related workflow and deploy it again you can see that the other workflows have an higher version then the fixed one

deployerror

This means they are stored in the state, even if we reject the deployment. I'm not sure whether this makes really sense. Especially since the deployment is not distributed, this means the succeed workflow's are only existing at partition one and the exporter (+operate and simple monitor) doesn't know about them.
 

**To Reproduce**
See above.

**Expected behavior**
When it is rejected nothing is stored in the state.

**Environment:**
 - OS: k8s
 - Zeebe Version: snapshot
 - Configuration: simple monitor

**Support**
- https://jira.camunda.com/browse/SUPPORT-15590

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

The current deployment process conflicts with our documentation in a way that we are not doing atomic deployments. This fix is utilizing our generic error handling mechanism to rollback any events or commands that may have been written.

## Related issues

closes #5723 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java [hunk 1]
```diff
@@ -224,6 +226,39 @@ public void shouldCreateDeploymentResourceWithMultipleProcesses() {
...
   }
 
+  @Test
+  public void shouldDoAtomicDeployments() {
+    // given
+    final String process1Id = "process1";
+    final BpmnModelInstance process1 =
+        Bpmn.createExecutableProcess(process1Id)
+            .startEvent()
+            .businessRuleTask("invalid_business_rule_task_id")
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java:236]: This Business Rule Task is invalid only because it's missing the Called Decision. It's unclear to the reader what is invalid, unless they know this requirement.

❌ We should use something else to clarify that it is an invalid process. Let me know if you want any tips.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/transform/DeploymentTransformer.java [hunk 2]
```diff
@@ -150,6 +152,19 @@ private DeploymentResourceTransformer getResourceTransformer(final String resour
         .orElse(UNKNOWN_RESOURCE);
   }
 
+  /**
+   * Exception that can be thrown during processing of a command, in case the engine could not
+   * subscribe to an event. This exception can be handled by the processor in {@link
+   * io.camunda.zeebe.engine.processing.streamprocessor.CommandProcessor#tryHandleError(TypedRecord,
+   * Throwable)}.
+   */
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/transform/DeploymentTransformer.java:159]: ❌ This documentation is not entirely correct, specifically the part:
>in case the engine could not subscribe to an event

Instead, let's document that this can be thrown whenever the resource cannot be transformed successfully. This allows the platform to rollback any changes the engine made, and that it can be handled in the `DeploymentCreateProcessor#tryHandleError` method.

**Review by korthout — CHANGES_REQUESTED** [review]
Well done! I'm happy to get to review your first GitHub PR 🎉 

👏 I'm impressed with how you've focussed the test case to its essentials. Great job!

👍 And your solution solves the problem. Clearly, you've already understood where the problem is and how we can resolve it!

I have a few suggestions, and some actual change requests. Please have a look at my comments.

> **Note**
> I use [the EmojiCode](https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md#review-emoji-code) in my reviews to attempt clarifying my intentions.

By the way, sorry for my late review. I'll try to be a bit faster in the future 🙇

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java (hunk 1 above)
Comment (berkaycanbc) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java:236]: Yes, your point definitely makes sense. Updated using process without start event. That should be more trivial to understand. I also rename process instance variables to make it explicit.

**Review by berkaycanbc — COMMENTED** [review]
Thanks a lot for your comments!

:+1: They are very educational and totally makes sense. :rocket:

I refactor the changes based on your comments and separated each change into a different commit.

File: engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java [hunk 3]
```diff
@@ -85,26 +84,30 @@ public void processRecord(final TypedRecord<DeploymentRecord> command) {
...
 
-    try {
-      createTimerIfTimerStartEvent(command);
-    } catch (final RuntimeException e) {
-      final String reason = String.format(COULD_NOT_CREATE_TIMER_MESSAGE, e.getMessage());
-      responseWriter.writeRejectionOnCommand(command, RejectionType.PROCESSING_ERROR, reason);
-      rejectionWriter.appendRejection(command, RejectionType.PROCESSING_ERROR, reason);
-      return;
-    }
+    if (result.isRight()) {
```
Comment (korthout) [inline engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java:89]: 🔧 You could invert this if and fail early. This helps reduce the nesting of the rest of the code, which means the reader has less code/context to keep in mind.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/DeploymentRejectionTest.java [hunk 4]
```diff
@@ -265,22 +265,17 @@ public void shouldRejectDeploymentIfNoExecutableProcess() {
...
-            .endEvent()
-            .done();
-    final String process2Id = "process2";
-    final BpmnModelInstance process2 =
-        Bpmn.createExecutableProcess(process2Id).startEvent().task().endEvent().done();
+    final String invalidProcessId = "invalid_process_without_start_event";
+    final BpmnModelInstance invalidProcess = Bpmn.createExecutableProcess(invalidProcessId).done();
+    final String validProcessId = "valid_process";
+    final BpmnModelInstance validProcess =
+        Bpmn.createExecutableProcess(validProcessId).startEvent().task().endEvent().done();
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/DeploymentRejectionTest.java:272]: 🔧 You could consider inlining the process id strings, as they are not reused and distract a bit from what is being tested. They also don't provide much value in being named specifically because the `Bpmn.createExecuteableProcess(String)` method is used in almost every test and most readers know that this String is a process id.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/DeploymentRejectionTest.java [hunk 5]
```diff
@@ -281,9 +281,9 @@ public void shouldDoAtomicDeployments() {
 
     // then
     assertThat(
-        RecordingExporter.records()
-            .limit(r -> r.getRejectionType() == RejectionType.INVALID_ARGUMENT)
-            .collect(Collectors.toList()))
+          RecordingExporter.records()
+              .limit(r -> r.getRejectionType() == RejectionType.INVALID_ARGUMENT)
+              .collect(Collectors.toList()))
```
Comment (korthout) [inline engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/DeploymentRejectionTest.java]: 💭 Which IDE are you using? If you're using IntelliJ-IDEA, the Save Actions plugin should've been set up automatically to apply our code format as soon as you save the file. This way, you don't have to remember to apply our formatting. Let me know if you want to look at this together.

**Review by korthout — APPROVED** [review]
Great work @berkaycanbc 👏 

🙇 Sorry for my late review, I'll try to be better next time

🔧 Please have a look at my last suggestions before merging

LGTM 👍 

🥇 Congratulations on merging your first pull request! 

> **Note** Feel free to initiate the [merge](https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md#creating-a-pull-request) yourself once you feel this is ready to be merged, or let me know if you have any questions about merging.

File: engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java [hunk 6]
```diff
@@ -224,6 +226,39 @@ public void shouldCreateDeploymentResourceWithMultipleProcesses() {
...
+    ENGINE.deployment()
+            .withXmlResource(process1)
+            .withXmlResource(process2)
+            .expectRejection()
+            .deploy();
+
+    // then
+    assertThat(
+        RecordingExporter.records()
+            .limit(r -> r.getRejectionType() == RejectionType.INVALID_ARGUMENT)
```
[the remark this answers is not in the document]
Comment (berkaycanbc) [reply engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java]: I missed this one from previous feedback. Updated!

**Review by berkaycanbc — COMMENTED** [review]
:+1: Thanks for the latest comments, all useful!

bors merge

**Comment by korthout** [comment]
>🔒 Permission denied
>
>Existing reviewers: [click here to make berkaycanbc a reviewer](https://bors-camunda.zeebe.camunda.cloud/repositories/2/add-reviewer/berkaycanbc)

@berkaycanbc Seems we need to give you more credentials. I'll have a look.

>**Warning** I just noticed you merged `main` into the branch. We typically rebase our branches on top of `main`. This also helps the backport action, as it cannot cherry-pick the last commit (it's unclear which parent is the mainline).

**Comment by berkaycanbc** [comment]
@korthout Could you please check if the rebasing I performed looks okay now?

**Comment by lzgabel** [comment]
> @korthout Could you please check if the rebasing I performed looks okay now?

👋 Hi @berkaycanbc. 

🤔 Seems like you can drop the last commit [3cdcae8](https://github.com/camunda/zeebe/pull/11776/commits/3cdcae8f15a8703343563418af696b7be1824a8e), and run `mvn spotless:apply`.

**Comment by berkaycanbc** [comment]
Thanks @lzgabel, applied! I am still running into issues with applying Java Checks automatically by IDE. I will work on it.

**Comment by berkaycanbc** [comment]
Resolved duplicated commits.

bors merge

**Comment by remcowesterhoud** [comment]
@berkaycanbc The back ports couldn't be created automagically unfortunately. This mean we'll have to cherry-pick the changes and create the PRs ourselves. Reach out if you need help with this!

**Comment by remcowesterhoud** [comment]
We will only backport this to 8.1. It's impossibly to backport to 8.0 considering we require the engine abstraction for the solution.
