### PR TITLE
fix: fix shouldStaySoftPausedAfterRestart

### LINKED ISSUE #17836: Flaky test `shouldStaySoftPausedAfterRestart`
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? two times so far ([last failure](https://github.com/camunda/zeebe/actions/runs/8834204251/job/24255327709?pr=17581))
- Does it block your work? no
- Do we suspect that it is a real failure? Not sure

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
shouldStaySoftPausedAfterRestart (Flaky Test): io.camunda.zeebe.it.management.ExportingEndpointIT
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at io.camunda.zeebe.it.management.ExportingEndpointIT.shouldStaySoftPausedAfterRestart(ExportingEndpointIT.java:352)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**[Logs](https://drive.google.com/file/d/1yQ9YUdehYeJ0HXqmTt0InIihEckbr9WF/view?usp=drive_link)**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

### LINKED ISSUE #18410: Soft Paused exporter can possibly update last exported position.
**Describe the bug**

This bug was found during the investigation of the flaky test [shouldStaySoftPausedAfterRestart](https://github.com/camunda/zeebe/pull/17916).

It seems that the origin of the flakyness of the test came from the fact that, during the initialization of the exporter director that was soft paused, there was a small interval between the creation of the exporter containers and setting their phase after the exporter director was ready, where the container could have time to recover from a snapshot and increment the exporter position before being set as soft paused.

The solution for this is to set the exporter container phase during its initialization.

The impact of the bug is probably low and unlikely as this could only possibly happen if broker would restart during a backup being performed while this is soft paused. During the restart its possible that the exported position could be updated and lead to to creation of new snapshots during the backup.

**To Reproduce**

Run the test shouldStaySoftPausedAfterRestart until failure. 

-->

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version:  8.5, 8.4, 8.3, 8.2
- Configuration:

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

The issue was eventually possible to reproduce locally by running until failure dozens of times.

It seems that the origin of the flakyness of the test came from the fact that during the initialization of the exporter director that was soft paused there was a small interval between the creation of the exporter containers and setting their phase after the exporter director was ready, where the container could have time to recover from a snapshot and increment the exporter position before being set as soft paused.

The solution for this is to set the exporter container phase during its creation.
Another test shouldStartContainerSoftPaused was added to asssert the new logic.

## Related issues
closes https://github.com/camunda/zeebe/issues/17836
closes https://github.com/camunda/zeebe/issues/18410

### CODE REVIEW

**Comment by rodrigo-lourenco-lopes** [comment]
I ran the test locally around 100 times plus also the QA integration tests here in the CI 5 times just to be sure that is not flaky.

File: zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterContainer.java [hunk 1]
```diff
@@ -44,14 +45,18 @@ final class ExporterContainer implements Controller {
...
     context =
         new ExporterContext(
             Loggers.getExporterLogger(descriptor.getId()),
             descriptor.getConfiguration(),
             partitionId);
 
     exporter = descriptor.newInstance();
+    if (phase == ExporterPhase.SOFT_PAUSED) {
+      softPauseExporter();
+    }
```
Comment (deepthidevaki) [inline zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterContainer.java:59]: :wrench: No strong opinion. But I would  do this either in `initContainer` or explicitly call `softPauseExporter` from `ExporterDirector` where `initContainer` is called.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java [hunk 2]
```diff
@@ -664,6 +664,20 @@ public void shouldRecoverFromStartWithNonUpdatingExporter() throws Exception {
     assertThat(exporters.get(1).getExportedRecords()).isEmpty();
   }
 
+  @Test
+  public void shouldStartContainersSoftPaused() {
```
Comment (deepthidevaki) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java:668]: :x: This test is not enough. This is testing the implementation detail, not the actual expected behavior. I would suggest to verify the behavior. That is - new events are exported, but the position is not updated.

File: zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/management/ExportingEndpointIT.java [hunk 3]
```diff
@@ -347,15 +343,32 @@ void shouldStaySoftPausedAfterRestart() {
...
+        .isTrue();
+
     assertThat(recordsAfterRestart).isGreaterThan(recordsBeforePause);
+
+    // all partitions should be soft paused after restart
+    Awaitility.await().untilAsserted(this::allPartitionsSoftPausedExporting);
+
     // all partitions should have -1 as exported position due to restart and the exporter positions
     // not being able to update due to soft pause.
+    final Map<Integer, Long> exportedPositionsAfterSoftPause = getExportedPositions();
```
Comment (deepthidevaki) [inline zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/management/ExportingEndpointIT.java:369]: :x: Like we discussed before, comparing to -1 has a potential to be flaky because of snapshots. 

I would simplify the test as follows:

```
  @Test
  void shouldStaySoftPausedAfterRestart() {
    // given
    getActuator().softPause();
    client
        .newPublishMessageCommand()
        .messageName("soft-pause")
        .correlationKey("11")
        .messageId("11")
        .send()
        .join();
    final var recordsBeforePause =
        Awaitility.await()
            .atMost(Duration.ofSeconds(30))
            .during(Duration.ofSeconds(5))
            .until(RecordingExporter.getRecords()::size, hasStableValue());
    final var exportedPositionBeforeRestart = getExportedPositions();

    // when
    CLUSTER.shutdown();
    CLUSTER.start();

    client
        .newPublishMessageCommand()
        .messageName("soft-pause")
        .correlationKey("12")
        .messageId("12")
        .send()
        .join();

    final var recordsAfterRestart =
        Awaitility.await()
            .atMost(Duration.ofSeconds(30))
            .during(Duration.ofSeconds(5))
            .until(RecordingExporter.getRecords()::size, hasStableValue());

    // then
    // all partitions should be soft paused after restart
    Awaitility.await().untilAsserted(this::allPartitionsSoftPausedExporting);

    assertThat(
            RecordingExporter.messageRecords()
                .withName("soft-pause")
                .withIntent(MessageIntent.PUBLISHED)
                .limit(2)
                .count())
        .isEqualTo(2);

    assertThat(recordsAfterRestart).isGreaterThan(recordsBeforePause);

    final Map<Integer, Long> exportedPositionAfterRestart = getExportedPositions();
    exportedPositionAfterRestart.forEach(
        (partitionId, position) ->
            assertThat(position)
                .describedAs(
                    "Partition %d should not update exported position after restart", partitionId)
                .isLessThanOrEqualTo(exportedPositionBeforeRestart.get(partitionId)));
  }
```

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Great :rocket:  I did not approve because of a missing test case. Please add that. 

:upside_down_face: Please rephrase the PR title as this is fixing an actual bug not a flaky test.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java [hunk 4]
```diff
@@ -664,6 +664,29 @@ public void shouldRecoverFromStartWithNonUpdatingExporter() throws Exception {
...
+    writeEvent();
+
+    waitUntil(() -> exporters.get(0).getExportedRecords().size() == 2);
+    waitUntil(() -> exporters.get(1).getExportedRecords().size() == 2);
+
+    // then the position will not be updated.
+    assertThat(rule.getExportersState().getPosition(EXPORTER_ID_1)).isEqualTo(-1);
+    assertThat(rule.getExportersState().getPosition(EXPORTER_ID_2)).isEqualTo(-1);
+
+    assertThat(rule.getDirector().areAllExporterContainersSoftPaused()).isTrue();
```
Comment (deepthidevaki) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java:687]: :thought_balloon: I think this assert is not necessary.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java [hunk 5]
```diff
@@ -664,6 +664,29 @@ public void shouldRecoverFromStartWithNonUpdatingExporter() throws Exception {
...
 
+  @Test
+  public void shouldStartContainersSoftPaused() {
+    // All containers of an exporter should be initialized as soft paused if this is also
+    // the exporter director phase on initialization. This is to prevent that the
+    // that exporter containers can start to update the exported position before the exporter
+    // director is ready. When soft paused new events are exported the position should not update.
+
+    // when
+    rule.startExporterDirector(exporterDescriptors, ExporterPhase.SOFT_PAUSED);
```
Comment (deepthidevaki) [inline zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java:675]: :x: I just realized that the exporters are no updating the position by default. You have to set it explicitily:
```
exporters.get(0).shouldAutoUpdatePosition(true);
exporters.get(1).shouldAutoUpdatePosition(true);
```
Otherwise, the test passes even with the bug.  May be verify if the test can reproduce the bug with out the fix.

**Review by deepthidevaki — APPROVED** [review]
:rocket:  Please address my comment before merging.

File: zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java (hunk 5 above)
Comment (rodrigo-lourenco-lopes) [reply zeebe/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorTest.java:675]: Thanks good catch!
