### PR TITLE
35673 ensure identity entities are returned as a copy

### LINKED ISSUE #35673: SM Deleting One Mapping Also Deletes Other Mappings
### 

### 

### 

### 

### Description

When deleting a single mapping from a list of mappings, OC Identity deletes additional mappings that were not selected. This leads to partial data loss and inconsistent behavior.

### Steps to reproduce

1. Ensure  you have a mapping for demo, bart and lisa
2. Attempt to delete one specific mapping.
3. Observe that 2 of them are related. (sometimes all 3 are deleted)

### Current behavior

Deleting one mapping causes one or more unrelated mappings to be deleted as well.

### Expected behavior

Only the selected mapping should be deleted. All other mappings should remain untouched.

### Environment

SM

### Version

- Component Version: 

https://github.com/user-attachments/assets/0fa24452-ebb5-4ae1-8790-ca34badbfd8d

Identity SNAPHOST

### Rootcause

* Conditions to reproduce are:
  * Authorizations enabled
  * OIDC where the request is authorized via a matching mapping rule (i.e. on engine level `AuthInfo#claims` is populated with a claim name and value that matches a mapping rule)
  * Multiple mapping rules exist
* When we [delete a mapping rule](https://github.com/camunda/camunda/blob/d0da7437c77ddfaa2c498c20eeedd511cbbf36e0/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/MappingRuleDeleteProcessor.java#L85-L107)
  1. We [load the mapping rule to be deleted from state](https://github.com/camunda/camunda/blob/d0da7437c77ddfaa2c498c20eeedd511cbbf36e0/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/MappingRuleDeleteProcessor.java#L88)
     * Note that this uses a view into the Mapping Rule State's `mappingRuleColumnFamily`
  1. We [check the authorization to perform the command](https://github.com/camunda/camunda/blob/d0da7437c77ddfaa2c498c20eeedd511cbbf36e0/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/MappingRuleDeleteProcessor.java#L99)
     * In case the authorization is not directly granted to the user, [we check for applying mapping rules](https://github.com/camunda/camunda/blob/d0da7437c77ddfaa2c498c20eeedd511cbbf36e0/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/AuthorizationCheckBehavior.java#L120-L126)
     * This iterates the mapping rule state, particularly `mappingRuleColumnFamily` 
     * Accordingly, it changes the view that we had fetched in the first step if the last iterated value is not the mapping rule to be deleted
  1. [We use the object fetched in the first step](https://github.com/camunda/camunda/blob/d0da7437c77ddfaa2c498c20eeedd511cbbf36e0/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/MappingRuleDeleteProcessor.java#L173-L176) to write the `DELETED` event and change our state
     * This object now holds the values of the mapping rule that was last iterated in the second step; accordingly, an arbitrary mapping rule is deleted
* Failing test case: https://github.com/camunda/camunda/tree/35673-failing-test

### Solution ideas

* Reorder the interaction above, first perform the check, then the state access
  * Alternatively, copy the mapping rule value
* Check all Identity-related stream processors if this pattern applies there as well and we have more bugs

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

_No response_

### PR DESCRIPTION
**Pull request by eppdot**
## Description

There has been an issue with strange/unwanted side-effects that were caused by re-using a DbValue and not properly creating a copy.

## Checklist

- [ ] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #35673

### CODE REVIEW

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/mappingrule/MappingRuleDeleteAuthorizationTest.java [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+import io.camunda.zeebe.protocol.record.value.PermissionType;
+import io.camunda.zeebe.test.util.record.RecordingExporterTestWatcher;
+import java.util.List;
+import java.util.Map;
+import java.util.UUID;
+import org.junit.Rule;
+import org.junit.Test;
+import org.junit.rules.TestWatcher;
+
+public class MappingRuleDeleteAuthorizationTest {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/mappingrule/MappingRuleDeleteAuthorizationTest.java]: 🔧 Personally I'd cover this in a unit test for the state directly. No need to spin up a the whole broker. We already have test classes for this, eg `MappingRuleStateTest`.

I quickly created this example using copilot, didn't verify it thoroughly but it seems right and you'll understand what I mean 🙂 

```java
  @Test
  void shouldReturnDifferentObjectsForDifferentMappingRules() {
    // given
    final long key1 = 1L;
    final long key2 = 2L;
    final String mappingRuleId1 = "mappingRuleId1";
    final String mappingRuleId2 = "mappingRuleId2";
    final String claimName1 = "claimName1";
    final String claimValue1 = "claimValue1";
    final String claimName2 = "claimName2";
    final String claimValue2 = "claimValue2";

    final var mappingRule1 =
        new MappingRuleRecord()
            .setMappingRuleKey(key1)
            .setMappingRuleId(mappingRuleId1)
            .setClaimName(claimName1)
            .setClaimValue(claimValue1);
    final var mappingRule2 =
        new MappingRuleRecord()
            .setMappingRuleKey(key2)
            .setMappingRuleId(mappingRuleId2)
            .setClaimName(claimName2)
            .setClaimValue(claimValue2);

    mappingRuleState.create(mappingRule1);
    mappingRuleState.create(mappingRule2);

    // when
    final var retrieved1 = mappingRuleState.get(mappingRuleId1);
    final var retrieved2 = mappingRuleState.get(mappingRuleId2);

    // then
    assertThat(retrieved1).isNotEmpty();
    assertThat(retrieved2).isNotEmpty();
    assertThat(retrieved1.get()).isNotSameAs(retrieved2.get());
  }
```

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]
We have the same in some other identity related states:

- `DbGroupState`
- `DbTenantState`

I don't know if we'd run into the same problem as I haven't checked all usages, but in general when returning the object using a getter making a copy is just the safer option.

**Comment by eppdot** [comment]
> We have the same in some other identity related states:
> 
> * `DbGroupState`
> * `DbTenantState`
> 
> I don't know if we'd run into the same problem as I haven't checked all usages, but in general when returning the object using a getter making a copy is just the safer option.

Screenshot 2025-09-03 at 08 48 24
Screenshot 2025-09-03 at 08 57 39
Screenshot 2025-09-03 at 08 57 32

**Comment by eppdot** [comment]
dropped this [commit](https://github.com/camunda/camunda/commit/4cc72ace3742f1368b4e45b770b9a97a48ee05df) as we cover this by unit tests now

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/authorization/DbAuthorizationStateTest.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+import io.camunda.zeebe.engine.util.ProcessingStateExtension;
+import io.camunda.zeebe.protocol.impl.record.value.authorization.AuthorizationRecord;
+import io.camunda.zeebe.protocol.record.value.AuthorizationOwnerType;
+import io.camunda.zeebe.protocol.record.value.AuthorizationResourceMatcher;
+import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.ExtendWith;
+
+@ExtendWith(ProcessingStateExtension.class)
+class DbAuthorizationStateTest {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/authorization/DbAuthorizationStateTest.java]: 🔧 We could add this to the `AuthorizationStateTest`.

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/authorization/DbRoleStateTest.java [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+  private MutableProcessingState processingState;
+  private MutableRoleState state;
+
+  @BeforeEach
+  public void setup() {
+    state = processingState.getRoleState();
+  }
+
+  @Test
+  void shouldReturnNewCopiesOnGet() {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/authorization/DbRoleStateTest.java]: 🔧 We could add this to the `RoleStateTest`

File: zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/group/DbGroupStateTest.java [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+import io.camunda.zeebe.engine.state.mutable.MutableGroupState;
+import io.camunda.zeebe.engine.state.mutable.MutableProcessingState;
+import io.camunda.zeebe.engine.util.ProcessingStateExtension;
+import io.camunda.zeebe.protocol.impl.record.value.group.GroupRecord;
+import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.ExtendWith;
+
+@ExtendWith(ProcessingStateExtension.class)
+class DbGroupStateTest {
```
Comment (remcowesterhoud) [inline zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/group/DbGroupStateTest.java]: 🔧 We could add this to the `GroupStateTest`

**Review by remcowesterhoud — APPROVED** [review]
Thanks! Just some minor comments about adding the test cases to existing test classes instead of new ones. There's some naming incosistencies in test class names as well 😬
