### PR TITLE
fix: conditional jackson converter setup

### LINKED ISSUE #38487: No qualifying bean of type 'gatewayRestObjectMapper' error after recent JacksonConfig changes
### 

### 

### 

### 

### Description

After the backport of stricter Jackson configuration in PRs #38190 and #38046, chaos clusters intermittently throw:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.fasterxml.jackson.databind.ObjectMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.context.annotation.Lazy(true), @org.springframework.beans.factory.annotation.Qualifier("gatewayRestObjectMapper")}
```

This error appears when the gatewayRestObjectMapper bean is missing, resulting in failed HTTP response processing.

See also:
- https://github.com/camunda/camunda/pull/38190
- https://github.com/camunda/camunda/pull/38046

### Steps to reproduce

Not sure

### Current behavior

Requests to gateway REST endpoints fail with `NoSuchBeanDefinitionException` due to missing `gatewayRestObjectMapper`, resulting in HTTP 500 errors.

### Expected behavior

Requests should succeed, and the `gatewayRestObjectMapper` bean must always be present when the converter is registered.

### Workaround

None known. The issue is tied to Spring context/module scanning and cannot be worked around without restoring the bean definition.

### Environment

SaaS

### Version

Version: `8.8-SNAPSHOT`
Environment: `SaaS chaos`

### Rootcause

_No response_

### Solution ideas

_No response_

### Dev -> QA handover

_No response_

### Links

Related PRs: #38190, #38046
GCP Logs: [LINK](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CJy21qrwgZumgwE%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.namespace_name%3D%2213e91c8a-8e29-4a5f-bdd5-721200bfd90a-zeebe%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-west1%22;cursorTimestamp=2025-09-18T09:35:48.679327018Z;startTime=2025-09-18T09:06:18.679Z;endTime=2025-09-18T10:06:18.679Z?project=camunda-saas-int-chaos)
GCP Logs Downloaded: LINK

### Automated Test Impact

_No response_

### PR DESCRIPTION
**Pull request by megglos**
## Description

Ensure specific converters are only setup when required, in contrast to using lazy, which lead to failure when they were accidentally picked up still in configuration setups where the objectMapper was not provided though.

One example is described in the [last comment on the issue](https://github.com/camunda/camunda/issues/38487#issuecomment-3318700148) (standalone broker with rest api disabled).

## Checklist

- [x] Enable backports when necessary (fex. [for bug fixes](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#backporting-changes) or [for CI changes](https://github.com/camunda/camunda/wiki/CI-&-Automation#when-to-backport-ci-changes)).

## Related issues

closes #38487

### CODE REVIEW

File: dist/src/main/java/io/camunda/application/commons/rest/MappingJackson2HttpMessageConverterConfiguration.java [hunk 1]
```diff
@@ -27,18 +28,20 @@ public class MappingJackson2HttpMessageConverterConfiguration {
 
   @Bean
   @Order(1)
+  @ConditionalOnRestGatewayEnabled
   public MappingJackson2HttpMessageConverter gatewayRestMappingJackson2HttpMessageConverter(
-      @Lazy @Qualifier("gatewayRestObjectMapper") final ObjectMapper objectMapper) {
+      @Qualifier("gatewayRestObjectMapper") final ObjectMapper objectMapper) {
     final PackageSpecificJackson2HttpMessageConverter messageConverter =
-        new PackageSpecificJackson2HttpMessageConverter("io.camunda.zeebe");
+        new PackageSpecificJackson2HttpMessageConverter("io.camunda.zeebe.gateway.protocol.rest");
```
Comment (megglos) [inline dist/src/main/java/io/camunda/application/commons/rest/MappingJackson2HttpMessageConverterConfiguration.java:35]: I noticed this mapper was also picking up types for the actuator endpoints from the `io.camunda.zeebe.shared` package, thus providing a more rest API specific package.

**Review by nicpuppa — APPROVED** [review]
