### PR TITLE
fix: validate mappingRule in engine

### LINKED ISSUE #33186: `CommandDistributionIdempotencyTest` results in a segmentation fault
Running `CommandDistributionIdempotencyTest`, specifically the `User.UPDATE` case, sometimes triggers a segfault:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f22519716ed, pid=20658, tid=20751
#
# JRE version: OpenJDK Runtime Environment (23.0.2+7) (build 23.0.2+7-58)
# Java VM: OpenJDK 64-Bit Server VM (23.0.2+7-58, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [librocksdbjni16622659561759854129.so+0x9716ed]  std::_Hashtable<std::string, std::pair<std::string const, rocksdb::TrackedKeyInfo>, std::allocator<std::pair<std::string const, rocksdb::TrackedKeyInfo> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node(unsigned long, std::string const&, unsigned long) const+0x2d
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %d %F" (or dumping to /home/lena/Source/github.com/camunda/camunda/zeebe/engine/core.20658)
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -javaagent:/home/lena/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate-2/plugins/java/lib/rt/debugger-agent.jar=file:///tmp/capture6315925951593222422.props -ea -Didea.test.cyclic.buffer.size=4194304 -javaagent:/home/lena/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate-2/lib/idea_rt.jar=32913 -Dkotlinx.coroutines.debug.enable.creation.stack.trace=false -Ddebugger.agent.enable.coroutines=true -Dkotlinx.coroutines.debug.enable.flows.stack.trace=true -Dkotlinx.coroutines.debug.enable.mutable.state.flows.stack.trace=true -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 io.camunda.zeebe.engine.processing.distribution.CommandDistributionIdempotencyTest

Host: AMD Ryzen 7 PRO 8840HS w/ Radeon 780M Graphics, 16 cores, 27G, Fedora release 42 (Adams)
Time: Thu Jun  5 10:33:25 2025 CEST elapsed time: 28.298289 seconds (0d 0h 0m 28s)

---------------  T H R E A D  ---------------

Current thread (0x00007f22e61932a0):  JavaThread "zb-actors-1"        [_thread_in_native, id=20751, stack(0x00007f22a43fe000,0x00007f22a44fe000) (1024K)]

Stack: [0x00007f22a43fe000,0x00007f22a44fe000],  sp=0x00007f22a44fc110,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [librocksdbjni16622659561759854129.so+0x9716ed]  std::_Hashtable<std::string, std::pair<std::string const, rocksdb::TrackedKeyInfo>, std::allocator<std::pair<std::string const, rocksdb::TrackedKeyInfo> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node(unsigned long, std::string const&, unsigned long) const+0x2d
C  [librocksdbjni16622659561759854129.so+0x971805]  std::_Hashtable<std::string, std::pair<std::string const, rocksdb::TrackedKeyInfo>, std::allocator<std::pair<std::string const, rocksdb::TrackedKeyInfo> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(std::string const&) const+0x35
C  [librocksdbjni16622659561759854129.so+0x970e6a]  rocksdb::PointLockTracker::GetPointLockStatus(unsigned int, std::string const&) const+0x6a
C  [librocksdbjni16622659561759854129.so+0x99d5ac]  rocksdb::TransactionUtil::CheckKeysForConflicts(rocksdb::DBImpl*, rocksdb::LockTracker const&, bool)+0xec
C  [librocksdbjni16622659561759854129.so+0x97c5eb]  rocksdb::OptimisticTransaction::CommitWithParallelValidate()+0x29b
C  [librocksdbjni16622659561759854129.so+0x97c865]  rocksdb::OptimisticTransaction::Commit()+0x55
C  [librocksdbjni16622659561759854129.so+0x36cd6e]  Java_org_rocksdb_Transaction_commit+0x1e
J 5569  org.rocksdb.Transaction.commit(J)V (0 bytes) @ 0x00007f22c658575a [0x00007f22c65856a0+0x00000000000000ba]
J 6024 c1 io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commitInternal()V (13 bytes) @ 0x00007f22beff0dcc [0x00007f22beff0b60+0x000000000000026c]
j  io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commit()V+1
j  io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$updateState$17()Z+4
j  io.camunda.zeebe.stream.impl.ProcessingStateMachine$$Lambda+0x00007f22576d9be0.run()Z+4
J 6018 c1 io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run()Lio/camunda/zeebe/scheduler/retry/ActorRetryMechanism$Control; (62 bytes) @ 0x00007f22befef4bc [0x00007f22befef3a0+0x000000000000011c]
J 8021 c1 io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run()V (84 bytes) @ 0x00007f22bf343374 [0x00007f22bf3432e0+0x0000000000000094]
J 8020 c1 io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy$$Lambda+0x00007f22576da018.run()V (8 bytes) @ 0x00007f22bf342f2c [0x00007f22bf342ea0+0x000000000000008c]
J 7941 c2 io.camunda.zeebe.scheduler.ActorJob.execute$$$capture(Lio/camunda/zeebe/scheduler/ActorThread;)V (154 bytes) @ 0x00007f22c6646e5c [0x00007f22c6646920+0x000000000000053c]
J 5870 c1 io.camunda.zeebe.scheduler.ActorTask.execute(Lio/camunda/zeebe/scheduler/ActorThread;)Z (191 bytes) @ 0x00007f22befb7cdc [0x00007f22befb7780+0x000000000000055c]
J 5874 c1 io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask()V (213 bytes) @ 0x00007f22befba87c [0x00007f22befb9b00+0x0000000000000d7c]
J 7712 c1 io.camunda.zeebe.scheduler.ActorThread.doWork()V (183 bytes) @ 0x00007f22bf2ba614 [0x00007f22bf2b9ea0+0x0000000000000774]
j  io.camunda.zeebe.scheduler.ActorThread.run()V+31
v  ~StubRoutines::call_stub 0x00007f22c5c5fc86
V  [libjvm.so+0x8cfcdb]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*)+0x2db
V  [libjvm.so+0x8d15af]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, JavaThread*)+0x1bf
V  [libjvm.so+0x9a99ac]  thread_entry(JavaThread*, JavaThread*)+0x8c
V  [libjvm.so+0x8e64d8]  JavaThread::thread_main_inner() [clone .part.0]+0xb8
V  [libjvm.so+0xeaab7f]  Thread::call_run()+0x9f
V  [libjvm.so+0xcc6555]  thread_native_entry(Thread*)+0xd5
C  [libc.so.6+0x711d4]  start_thread+0x2e4
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 5569  org.rocksdb.Transaction.commit(J)V (0 bytes) @ 0x00007f22c65856e9 [0x00007f22c65856a0+0x0000000000000049]
J 6024 c1 io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commitInternal()V (13 bytes) @ 0x00007f22beff0dcc [0x00007f22beff0b60+0x000000000000026c]
j  io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commit()V+1
j  io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$updateState$17()Z+4
j  io.camunda.zeebe.stream.impl.ProcessingStateMachine$$Lambda+0x00007f22576d9be0.run()Z+4
J 6018 c1 io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run()Lio/camunda/zeebe/scheduler/retry/ActorRetryMechanism$Control; (62 bytes) @ 0x00007f22befef4bc [0x00007f22befef3a0+0x000000000000011c]
J 8021 c1 io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run()V (84 bytes) @ 0x00007f22bf343374 [0x00007f22bf3432e0+0x0000000000000094]
J 8020 c1 io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy$$Lambda+0x00007f22576da018.run()V (8 bytes) @ 0x00007f22bf342f2c [0x00007f22bf342ea0+0x000000000000008c]
J 7941 c2 io.camunda.zeebe.scheduler.ActorJob.execute$$$capture(Lio/camunda/zeebe/scheduler/ActorThread;)V (154 bytes) @ 0x00007f22c6646e5c [0x00007f22c6646920+0x000000000000053c]
J 5870 c1 io.camunda.zeebe.scheduler.ActorTask.execute(Lio/camunda/zeebe/scheduler/ActorThread;)Z (191 bytes) @ 0x00007f22befb7cdc [0x00007f22befb7780+0x000000000000055c]
J 5874 c1 io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask()V (213 bytes) @ 0x00007f22befba87c [0x00007f22befb9b00+0x0000000000000d7c]
J 7712 c1 io.camunda.zeebe.scheduler.ActorThread.doWork()V (183 bytes) @ 0x00007f22bf2ba614 [0x00007f22bf2b9ea0+0x0000000000000774]
j  io.camunda.zeebe.scheduler.ActorThread.run()V+31
v  ~StubRoutines::call_stub 0x00007f22c5c5fc86
```

[hs_err_pid20658.log](https://github.com/user-attachments/files/20606315/hs_err_pid20658.log)

### PR DESCRIPTION
**Pull request by maryarm**
## Description
Running CommandDistributionIdempotencyTest, specifically the User.UPDATE case, sometimes triggers a segfault, it seems it happens because of the Mapping.Update testcase creates a mapping with no name and claim name and value. So this is a bug in the MappingUpdateProcessor because it doesn't validate the updated mapping

## Related issues

closes #33186

### CODE REVIEW

File: zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/MappingCreateProcessor.java [hunk 1]
```diff
@@ -68,6 +71,21 @@ public void processNewCommand(final TypedRecord<MappingRecord> command) {
     }
 
     final var record = command.getValue();
+    if (!StringUtils.hasText(record.getMappingId())
+        || !StringUtils.hasText(record.getName())
+        || !StringUtils.hasText(record.getClaimName())
+        || !StringUtils.hasText(record.getClaimValue())) {
```
Comment (lenaschoenburg) [inline zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/MappingCreateProcessor.java]: :x: Let's not depend on Spring just for `StringUtils`. A simple `String#isBlank` should be enough.

**Review by lenaschoenburg — APPROVED** [review]
I'll approve to unblock but please address the one :x: comment.
