### PR TITLE
fix: Add missing resource checks

### LINKED ISSUE #48780: Add missing authorization checks to statistics readers
* There are a few db readers for statistics that don't follow the common logic for authorization checks, cf. https://github.com/camunda/camunda/pull/48304#discussion_r2938557278

### PR DESCRIPTION
**Pull request by stefanzilske**
## Description

* add authorization checks for ProcessDefinitionStatistics and ProcessInstanceStatistics

## Related issues

closes #48780

### CODE REVIEW

File: db/rdbms/src/main/java/io/camunda/db/rdbms/sql/ProcessDefinitionMapper.java [hunk 1]
```diff
@@ -27,7 +28,9 @@ public interface ProcessDefinitionMapper {
   List<ProcessDefinitionEntity> search(ProcessDefinitionDbQuery filter);
 
   List<ProcessFlowNodeStatisticsEntity> flowNodeStatistics(
-      ProcessDefinitionStatisticsFilter filter);
+      @Param("filter") ProcessDefinitionStatisticsFilter filter,
+      @Param("authorizedResourceIds") List<String> authorizedResourceIds,
+      @Param("authorizedTenantIds") List<String> authorizedTenantIds);
```
Comment (stoerti) [inline db/rdbms/src/main/java/io/camunda/db/rdbms/sql/ProcessDefinitionMapper.java]: 💭 We never used this `@Param` notation before but rather used a `DbQuery` object. This this not applicable here?

File: db/rdbms/src/main/java/io/camunda/db/rdbms/sql/ProcessInstanceMapper.java [hunk 2]
```diff
@@ -37,7 +38,10 @@ public interface ProcessInstanceMapper {
 
   List<ProcessInstanceEntity> search(ProcessInstanceDbQuery filter);
 
-  List<ProcessFlowNodeStatisticsEntity> flowNodeStatistics(long processInstanceKey);
+  List<ProcessFlowNodeStatisticsEntity> flowNodeStatistics(
+      @Param("processInstanceKey") long processInstanceKey,
+      @Param("authorizedResourceIds") List<String> authorizedResourceIds,
+      @Param("authorizedTenantIds") List<String> authorizedTenantIds);
```
Comment (stoerti) [inline db/rdbms/src/main/java/io/camunda/db/rdbms/sql/ProcessInstanceMapper.java]: 💭 We never used this `@Param` notation before but rather used a `DbQuery` object. This this not applicable here?

**Review by stoerti — COMMENTED** [review]
Should we also add some tests in the `qa/acceptance-tests->auth` package?

**Comment by stefanzilske** [comment]
@tanjinyi now that you PR is merged, would you mind having a final look here as well?

**Comment by tanjinyi** [comment]
🔧 https://github.com/camunda/camunda/issues/48780#issuecomment-4089553212 in case you missed this comment, could you help to remove https://github.com/camunda/camunda/pull/48304/changes#diff-92b269387f5784fd979a2c278b673f0e3d4bbb45874a9fcef98726466286d202R32-R34 as part of your PR for validation too?

**Review by stoerti — APPROVED** [review]

**Comment by stefanzilske** [comment]
@tanjinyi I saw your comment and re-enabled the test, it's working fine!
